######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 23 18:02:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
