Visible: rcBidirectionalRing< T > Class Template Reference
rcBidirectionalRing< T > Class Template Reference
#include <include/util/rc_ring.h>
Public Member Functions
rcBidirectionalRing (uint32 sz)
rcBidirectionalRing (uint32 sz, sMemAllocator allocFct)
bool giveResource (T *tp)
T * takeResource (void)
bool releaseResource (T *tp)
T * recoverResource (void)
uint32 availNewResources ()
uint32 availNewSlots ()
uint32 availReleasedResources ()
uint32 availReleasedSlots ()
size_t size ()
Private Member Functions
rcBidirectionalRing (rcBidirectionalRing< T > &)
rcBidirectionalRing (const rcBidirectionalRing< T > &)
rcBidirectionalRing< T > & operator= (const rcBidirectionalRing< T > &)
rcBidirectionalRing< T > & operator= (rcBidirectionalRing< T > &)
Private Attributes
rcRingBuffer< T > _available
rcRingBuffer< T > _freed
Detailed Description
template<class T>
class rcBidirectionalRing< T >
Definition at line 231 of file rc_ring.h.
Constructor & Destructor Documentation
template<class T> rcBidirectionalRing< T >::rcBidirectionalRing (uint32 sz) inline
Definition at line 235 of file rc_ring.h.
                                  : _available(sz), _freed(sz)
   {
   }
template<class T> rcBidirectionalRing< T >::rcBidirectionalRing (uint32 sz, sMemAllocator allocFct) inline
Definition at line 239 of file rc_ring.h.
                                                          :
     _available(sz, allocFct), _freed(sz, allocFct)
   {
}
template<class T> rcBidirectionalRing< T >::rcBidirectionalRing (rcBidirectionalRing< T > &) private
template<class T> rcBidirectionalRing< T >::rcBidirectionalRing (const rcBidirectionalRing< T > &) private
Member Function Documentation
template<class T> uint32 rcBidirectionalRing< T >::availNewResources () inline
Definition at line 264 of file rc_ring.h.
Referenced by rcEngineMovieSaver::closeHdlr(), rcEngineMovieCapture::saveComplete(), rcEngineMovieSaver::saveHdlr(), and rcEngineMovieCapture::startSaveThread().
   {
     return _available.availValues();
   }
template<class T> uint32 rcBidirectionalRing< T >::availNewSlots () inline
Definition at line 269 of file rc_ring.h.
Referenced by rcEngineMovieSaver::closeHdlr(), and rcEngineMovieCapture::startSaveThread().
   {
     return _available.availFreeSlots();
   }
template<class T> uint32 rcBidirectionalRing< T >::availReleasedResources () inline
Definition at line 274 of file rc_ring.h.
Referenced by rcEngineMovieSaver::closeHdlr(), rcEngineMovieCapture::closeSaveFile(), rcEngineMovieCapture::run(), and rcEngineMovieCapture::startSaveThread().
   {
     return _freed.availValues();
   }
template<class T> uint32 rcBidirectionalRing< T >::availReleasedSlots () inline
Definition at line 279 of file rc_ring.h.
Referenced by rcEngineMovieSaver::closeHdlr(), and rcEngineMovieCapture::startSaveThread().
   {
     return _freed.availFreeSlots();
   }
template<class T> bool rcBidirectionalRing< T >::giveResource (T * tp) inline
Definition at line 244 of file rc_ring.h.
Referenced by rcEngineMovieCapture::closeSaveFile(), and rcEngineMovieCapture::run().
   {
     return _available.putValue(tp);
   }
template<class T> rcBidirectionalRing<T>& rcBidirectionalRing< T >::operator= (const rcBidirectionalRing< T > &) private
template<class T> rcBidirectionalRing<T>& rcBidirectionalRing< T >::operator= (rcBidirectionalRing< T > &) private
template<class T> T* rcBidirectionalRing< T >::recoverResource (void) inline
Definition at line 259 of file rc_ring.h.
Referenced by rcEngineMovieCapture::closeSaveFile(), and rcEngineMovieCapture::run().
   {
     return _freed.getValue();
   }
template<class T> bool rcBidirectionalRing< T >::releaseResource (T * tp) inline
Definition at line 254 of file rc_ring.h.
Referenced by rcEngineMovieSaver::error_cleanup(), rcEngineMovieCapture::rcEngineMovieCapture(), rcEngineMovieCapture::saveComplete(), and rcEngineMovieSaver::saveHdlr().
   {
     return _freed.putValue(tp);
   }
template<class T> size_t rcBidirectionalRing< T >::size (void) inline
Definition at line 284 of file rc_ring.h.
   {
       return _freed.size(); // Could have used _available too.
   }
template<class T> T* rcBidirectionalRing< T >::takeResource (void) inline
Definition at line 249 of file rc_ring.h.
Referenced by rcEngineMovieCapture::saveComplete(), and rcEngineMovieSaver::saveHdlr().
   {
     return _available.getValue();
   }
Member Data Documentation
template<class T> rcRingBuffer<T> rcBidirectionalRing< T >::_available private
Definition at line 291 of file rc_ring.h.
Referenced by rcBidirectionalRing< rcSharedFrameBufPtr >::availNewResources(), rcBidirectionalRing< rcSharedFrameBufPtr >::availNewSlots(), rcBidirectionalRing< rcSharedFrameBufPtr >::giveResource(), and rcBidirectionalRing< rcSharedFrameBufPtr >::takeResource().
template<class T> rcRingBuffer<T> rcBidirectionalRing< T >::_freed private
Definition at line 292 of file rc_ring.h.
Referenced by rcBidirectionalRing< rcSharedFrameBufPtr >::availReleasedResources(), rcBidirectionalRing< rcSharedFrameBufPtr >::availReleasedSlots(), rcBidirectionalRing< rcSharedFrameBufPtr >::recoverResource(), rcBidirectionalRing< rcSharedFrameBufPtr >::releaseResource(), and rcBidirectionalRing< rcSharedFrameBufPtr >::size().
The documentation for this class was generated from the following file:
include/util/rc_ring.h