Visible: rcSettingPanel Class Reference
rcSettingPanel Class Reference
#include <include/visUI/rc_settingpanel.h>
Public Slots
void updateState (rcExperimentState state)
void updatePages (void)
Public Member Functions
rcSettingPanel (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
~rcSettingPanel ()
Detailed Description
Definition at line 10 of file rc_settingpanel.h.
Constructor & Destructor Documentation
rcSettingPanel::rcSettingPanel (QWidget * parent = 0, const char * name = 0, Qt::WFlags f = 0)
Definition at line 13 of file rc_settingpanel.cpp.
References rcModelDomain::getModelDomain(), rcUNUSED, updatePages(), and updateState().
     : QTabWidget( parent, name )
 {
     rcUNUSED( f );
     setMinimumWidth( 430 );
     updatePages();
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateDebugging( void ) ) ,
              this   , SLOT( updatePages( void ) ) );
 #ifdef HIPPOW
     connect ( domain, SIGNAL (updateTrackingDisplayGL (void)),
          this, SLOT (requestTrackingDisplayGL(void)));
 #endif
 }
rcSettingPanel::~rcSettingPanel ()
Definition at line 31 of file rc_settingpanel.cpp.
 {
 }
Member Function Documentation
void rcSettingPanel::updatePages (void) slot
Definition at line 69 of file rc_settingpanel.cpp.
References count(), rcSettingCategory::getDescription(), rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcSettingCategory::getName(), rcExperiment::getNSettingCategories(), and rcExperiment::getSettingCategory().
Referenced by rcSettingPanel(), and updateState().
 {
     int i;
     // Save currently selected tab
     int currentPage = currentPageIndex();
     hide();
     // Delete any previous settings pages
     for (i = count() - 1; i >= 0 ; i--)
     {
         QWidget* aPage = page( i );
         removePage( aPage );
         delete aPage;
     }
     // add the new settings pages
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     int nPages = experiment->getNSettingCategories();
     for (i = 0; i < nPages; i++)
     {
       rcSettingCategory category = experiment->getSettingCategory(i);
       if (category.getName () == "Capture")
         {
           QWidget* tab = new rcSettingPage( this, category );
           insertTab( tab , category.getName() );
           setTabToolTip( tab , category.getDescription() );
         }
     }
     for (i = 0; i < nPages; i++)
     {
       rcSettingCategory category = experiment->getSettingCategory(i);
       if (category.getName () == "Analyze")
         {
           QWidget* tab = new rcSettingPage( this, category );
           insertTab( tab , category.getName() );
           setTabToolTip( tab , category.getDescription() );
         }
     }
     for (i = 0; i < nPages; i++)
     {
       rcSettingCategory category = experiment->getSettingCategory(i);
       if (category.getName () == "Visualize")
         {
           QWidget* tab = new rcSettingPage( this, category );
           insertTab( tab , category.getName() );
           setTabToolTip( tab , category.getDescription() );
         }
     }
 #ifdef EXPR
     for (i = 0; i < nPages; i++)
     {
       rcSettingCategory category = experiment->getSettingCategory(i);
       if (category.getName () == "Experiment")
         {
           QWidget* tab = new rcSettingPage( this, category );
           insertTab( tab , category.getName() );
           setTabToolTip( tab , category.getDescription() );
         }
     }
 #endif
     // Restore selected tab
     if ( currentPage >= 0 )
         setCurrentPage( currentPage );
     show();
 }
void rcSettingPanel::updateState (rcExperimentState state) slot
Definition at line 35 of file rc_settingpanel.cpp.
References eExperimentEmpty, eExperimentEnded, eExperimentLocked, eExperimentPlayback, eExperimentRunning, and updatePages().
Referenced by rcSettingPanel().
 {
     switch( state ) {
         case eExperimentEmpty:          // experiment was created but not run
             updatePages();
         case eExperimentRunning:        // experiment is running
         case eExperimentPlayback:       // experiment is playing back
         case eExperimentEnded:          // experiment has ended
         case eExperimentLocked:         // experiment has ended and been saved
         default:
             break;
     }
 }
The documentation for this class was generated from the following files:
include/visUI/rc_settingpanel.h
src/visible/qt/rc_settingpanel.cpp