Visible: rcFpsCalculator Class Reference
rcFpsCalculator Class Reference
#include <include/util/rc_timestamp.h>
Public Member Functions
rcFpsCalculator (uint32 size)
double fps () const
void addTime (const rcTimestamp &time)
void reset ()
Private Member Functions
void addInterval (double frameInterval)
Private Attributes
rcTimestamp mLastTime
uint32 mWindowSize
double mTotalTime
deque< double > mFrameIntervals
Detailed Description
Definition at line 210 of file rc_timestamp.h.
Constructor & Destructor Documentation
rcFpsCalculator::rcFpsCalculator (uint32 size) inline
Definition at line 213 of file rc_timestamp.h.
References rmAssert.
                                    :  mLastTime( cZeroTime ), mWindowSize( size ), mTotalTime( -1.0 ) {
         rmAssert( mWindowSize > 0 ); };
Member Function Documentation
void rcFpsCalculator::addInterval (double frameInterval) inline private
Definition at line 249 of file rc_timestamp.h.
{
         // Check for window overflow
         if ( mFrameIntervals.size() > mWindowSize ) {
             // Remove first interval
             mTotalTime -= mFrameIntervals.front();
             mFrameIntervals.pop_front();
         }
         // Add new interval
         mFrameIntervals.push_back( frameInterval );
         mTotalTime += frameInterval;
     }
void rcFpsCalculator::addTime (const rcTimestamp & time) inline
Definition at line 228 of file rc_timestamp.h.
References rcTimestamp::secs().
Referenced by rcEngineImpl::frameInterrupt(), rcMonitor::updateCachedImage(), and rcTimeline::updateDisplay().
{
         if ( mTotalTime >= 0.0 ) {
             // Add interval
             rcTimestamp newInterval = time - mLastTime;
             addInterval( newInterval.secs() );
         } else {
             // First time ever, just store the time
             mTotalTime = 0.0;
         }
         mLastTime = time;
     }
double rcFpsCalculator::fps () const inline
Definition at line 217 of file rc_timestamp.h.
Referenced by rcEngineImpl::processCapturedData(), and rcMonitor::updateStatus().
{
         if ( mTotalTime > 0.0 ) {
             if ( !mFrameIntervals.empty() ) {
                 return 1.0 / (mTotalTime / (mFrameIntervals.size()));
             }
         }
         return 0.0;
     }
void rcFpsCalculator::reset (void) inline
Definition at line 241 of file rc_timestamp.h.
References cZeroTime.
Referenced by rcEngineImpl::setSettingValue(), rcEngineImpl::unlockedReset(), rcTimeline::updateState(), and rcMonitor::updateState().
                  {
         mLastTime = cZeroTime;
         mTotalTime = 0.0;
         mFrameIntervals.clear();
     };
Member Data Documentation
deque<double> rcFpsCalculator::mFrameIntervals private
Definition at line 264 of file rc_timestamp.h.
rcTimestamp rcFpsCalculator::mLastTime private
Definition at line 261 of file rc_timestamp.h.
double rcFpsCalculator::mTotalTime private
Definition at line 263 of file rc_timestamp.h.
uint32 rcFpsCalculator::mWindowSize private
Definition at line 262 of file rc_timestamp.h.
The documentation for this class was generated from the following file:
include/util/rc_timestamp.h