Visible: rcCell Class Reference
rcCell Class Reference
#include <include/analysis/rc_cell.h>
Public Member Functions
rcCell ()
rcCell (uint32 id, rc2Dvector com, uint32 area, RC_CellPlateImaging ic=rcCellImagingUnknown)
uint32 isValid ()
uint32 id () const
rc2Dvector com () const
rc2Dvector ctr () const
uint32 rawArea () const
void enclosingBox (rcRect &rect)
rcRect enclosingBox ()
bool operator< (const rcCell &rhs) const
bool operator== (const rcCell &rhs) const
Private Attributes
uint32 mId
rcRect mBox
rc2Dvector mBoxCtr
rc2Dvector mCom
uint32 mPelCount
RC_CellPlateImaging mImaging
uint32 mIsValid
Detailed Description
Definition at line 27 of file rc_cell.h.
Constructor & Destructor Documentation
rcCell::rcCell () inline
Definition at line 30 of file rc_cell.h.
 : mIsValid (0) {}
rcCell::rcCell (uint32 id, rc2Dvector com, uint32 area, RC_CellPlateImaging ic = rcCellImagingUnknown) inline
Definition at line 32 of file rc_cell.h.
                                                                                                  :
     mId (id), mCom (com), mPelCount (area), mImaging (ic), mIsValid (1) {}
Member Function Documentation
rc2Dvector rcCell::com () const inline
Definition at line 42 of file rc_cell.h.
 {return mCom;}
rc2Dvector rcCell::ctr () const inline
Definition at line 44 of file rc_cell.h.
 {return mBoxCtr;}
void rcCell::enclosingBox (rcRect & rect) inline
Definition at line 48 of file rc_cell.h.
References rcRectangle< T >::height(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
   {
     mBox = rect;
     mBoxCtr.x(((double) (rect.x() + rect.width()/2)));
     mBoxCtr.y(((double) (rect.y() + rect.height()/2)));
   }
rcRect rcCell::enclosingBox () inline
Definition at line 55 of file rc_cell.h.
 { return mBox; }
uint32 rcCell::id () const inline
Definition at line 40 of file rc_cell.h.
 {return mId;}
uint32 rcCell::isValid () inline
Definition at line 38 of file rc_cell.h.
 {return mIsValid;}
bool rcCell::operator< (const rcCell & rhs) const inline
Definition at line 58 of file rc_cell.h.
References mId.
 { return mId < rhs.mId; };
bool rcCell::operator== (const rcCell & rhs) const inline
Definition at line 59 of file rc_cell.h.
References mId.
 { return mId == rhs.mId; };
uint32 rcCell::rawArea () const inline
Definition at line 46 of file rc_cell.h.
 {return mPelCount; }
Member Data Documentation
rcRect rcCell::mBox private
Definition at line 63 of file rc_cell.h.
rc2Dvector rcCell::mBoxCtr private
Definition at line 64 of file rc_cell.h.
rc2Dvector rcCell::mCom private
Definition at line 65 of file rc_cell.h.
uint32 rcCell::mId private
Definition at line 59 of file rc_cell.h.
Referenced by operator<(), and operator==().
RC_CellPlateImaging rcCell::mImaging private
Definition at line 67 of file rc_cell.h.
uint32 rcCell::mIsValid private
Definition at line 68 of file rc_cell.h.
uint32 rcCell::mPelCount private
Definition at line 66 of file rc_cell.h.
The documentation for this class was generated from the following file:
include/analysis/rc_cell.h