Visible: rcAtomicValue< T > Class Template Reference
rcAtomicValue< T > Class Template Reference
#include <include/util/rc_atomic.h>
Public Types
enum { is_boost = 1 }
typedef boost::atomic< T > super
Public Member Functions
rcAtomicValue (const T &v)
rcAtomicValue (const rcAtomicValue< T > &av)
rcAtomicValue & operator= (rcAtomicValue &other)
T & getValue (T &v) const
void setValue (const T &v)
Detailed Description
template<typename T>
class rcAtomicValue< T >
Definition at line 294 of file rc_atomic.h.
Member Typedef Documentation
template<typename T> typedef boost::atomic<T> rcAtomicValue< T >::super
Definition at line 300 of file rc_atomic.h.
Member Enumeration Documentation
template<typename T> anonymous enum
Enumerator
is_boost
Definition at line 298 of file rc_atomic.h.
 {is_boost = 1 };
Constructor & Destructor Documentation
template<typename T> rcAtomicValue< T >::rcAtomicValue (const T & v) inline explicit
Definition at line 302 of file rc_atomic.h.
   {
     setValue(v); // Initializes all member data
   }
template<typename T> rcAtomicValue< T >::rcAtomicValue (const rcAtomicValue< T > & av) inline
Definition at line 307 of file rc_atomic.h.
   {
         T temp;
         setValue(av.getValue (temp));
   }
Member Function Documentation
template<typename T> T& rcAtomicValue< T >::getValue (T & v) const inline
Definition at line 321 of file rc_atomic.h.
Referenced by rcSharedMemoryUser::acquireSharedMemory(), rcRingBuffer< rcSharedFrameBufPtr >::availFreeSlots(), rcRingBuffer< rcSharedFrameBufPtr >::availValues(), rcEngineImpl::createSharedWriters(), rcEngineMovieSaver::doneHdlr(), rcEngineImpl::flushSharedWriters(), rcEngineImpl::frameFlush(), rcEngineImpl::frameInterrupt(), rcVideoCaptureCtrlReader::getACIEnabled(), rcVideoCaptureCtrlReader::getBinning(), rcVideoCaptureStatusReader::getCaptureDepth(), rcVideoCaptureStatusReader::getCaptureRect(), rcMovieSaveStatusReader::getCaptureTime(), rcMoviePlaybackCtrlReader::getCtrlInfo(), rcExperimentDomainImpl::getCursorTime(), rcVideoCaptureCtrlReader::getDecimationRate(), rcMovieSaveStatusReader::getDelayLeft(), rcVideoCaptureCtrlReader::getEntropyDefinition(), rcMovieSaveCtrlReader::getFrameCaptureDelayTime(), rcMovieSaveCtrlReader::getFrameCaptureTime(), rcVideoCaptureCtrlReader::getGain(), rcVideoCaptureStatusReader::getMaxFramesPerSecond(), rcVideoCaptureCtrlReader::getShutter(), rcVideoCaptureCtrlReader::getSlidingWindowEnabled(), rcVideoCaptureCtrlReader::getSlidingWindowOrigin(), rcVideoCaptureCtrlReader::getSlidingWindowSize(), rcMoviePlaybackStatusReader::getState(), rcMovieSaveStatusReader::getState(), rcEngineImpl::getState(), rcMovieSaveStatusReader::getStatus(), rcRingBuffer< rcSharedFrameBufPtr >::getValue(), rcEngineImpl::loadFrames(), rcAtomicValue< rcAnalyzerResultOrigin >::operator=(), rcEngineImpl::processCapturedData(), rcRingBuffer< rcSharedFrameBufPtr >::putValue(), rcAtomicValue< rcAnalyzerResultOrigin >::rcAtomicValue(), rcResCtrlWatchdog(), rcEngineMovieSaver::reset(), rcCreateChildShmem::~rcCreateChildShmem(), and rcEngineImpl::~rcEngineImpl().
     {
         v = super::load ();
         return v;
   }
template<typename T> rcAtomicValue& rcAtomicValue< T >::operator= (rcAtomicValue< T > & other) inline
Definition at line 313 of file rc_atomic.h.
         {
             T temp;
             setValue(other.getValue (temp) );
             return *this;
        }
template<typename T> void rcAtomicValue< T >::setValue (const T & v) inline
Definition at line 327 of file rc_atomic.h.
Referenced by rcVideoCaptureCtrl::ACIEnabled(), rcVideoCaptureCtrl::binning(), rcVideoCaptureStatus::captureDepth(), rcVideoCaptureStatus::captureRect(), rcMovieSaveStatus::captureTime(), rcMoviePlaybackCtrl::ctrlInfo(), rcVideoCaptureCtrl::decimationRate(), rcMovieSaveStatus::delayLeft(), rcVideoCaptureCtrl::entropyDefinition(), rcMovieSaveCtrl::frameCaptureDelayTime(), rcMovieSaveCtrl::frameCaptureTime(), rcEngineImpl::frameFlush(), rcEngineImpl::frameInterrupt(), rcVideoCaptureCtrl::gain(), rcRingBuffer< rcSharedFrameBufPtr >::getValue(), rcVideoCaptureStatus::maxFramesPerSecond(), rcExperimentDomainImpl::notifyCursorTime(), rcEngineImpl::pauseTracking(), rcRingBuffer< rcSharedFrameBufPtr >::putValue(), rcResCtrlWatchdog(), rcEngineMovieSaver::reset(), rcEngineImpl::resumeTracking(), rcEngineImpl::setInternalState(), rcEngineImpl::setState(), rcVideoCaptureCtrl::shutter(), rcVideoCaptureCtrl::slidingWindowEnabled(), rcVideoCaptureCtrl::slidingWindowOrigin(), rcVideoCaptureCtrl::slidingWindowSize(), rcEngineImpl::start(), rcMoviePlaybackStatus::state(), rcMovieSaveStatus::state(), rcMovieSaveStatus::status(), rcCreateChildShmem::~rcCreateChildShmem(), and rcExecWithShmem::~rcExecWithShmem().
   {
         super::store (v);
   }
The documentation for this class was generated from the following file:
include/util/rc_atomic.h