Visible: rcLicenseManager Class Reference
rcLicenseManager Class Reference
#include <include/util/rc_security.h>
Public Types
enum { eLicenseChecksumLength = 2, eLicenseComponentLength = rcSecurityKey::eTextKeyLength*2, eLicenseTotalLength = eLicenseComponentLength*2 + eLicenseChecksumLength }
Public Member Functions
rcLicenseManager (const std::string &licenseFileName, bool readAlways)
rcLicenseManager (const std::string &licenseString)
rcSecurityError validHost ()
rcSecurityError validTime ()
std::string getLicenseExpirationTime ()
std::string getLicenseHost ()
std::string getHostId () const
Static Public Member Functions
static std::string getErrorString (rcSecurityError error)
static std::string unhexifyString (const std::string &str)
static std::string hexifyString (const std::string &str)
static time_t unhexifyTime (const std::string &str)
static std::string generateChecksum (const std::string &str)
Private Member Functions
std::string getTime () const
rcSecurityError licenseChecksumIsValid ()
rcSecurityError licenseHostHasValidFormat ()
rcSecurityError licenseTimeHasValidFormat ()
rcSecurityError readFile ()
rcSecurityError validFile ()
Private Attributes
std::string mLicenseFile
std::string mLicenseString
rcSecurityKey mHostKey
rcEncryptionEngine mEncryptor
time_t mExpirationTime
bool mReadAlways
std::string mDecryptedTimeString
std::string mDecryptedHostString
Friends
class UT_Security
Detailed Description
Definition at line 122 of file rc_security.h.
Member Enumeration Documentation
anonymous enum
Enumerator
eLicenseChecksumLength
eLicenseComponentLength
eLicenseTotalLength
Definition at line 125 of file rc_security.h.
          {
         eLicenseChecksumLength = 2,
         eLicenseComponentLength = rcSecurityKey::eTextKeyLength*2, // Length of hexified component
         eLicenseTotalLength = eLicenseComponentLength*2 + eLicenseChecksumLength // Length of hexified license + checksum
     };
Constructor & Destructor Documentation
rcLicenseManager::rcLicenseManager (const std::string & licenseFileName, bool readAlways)
Definition at line 216 of file rc_security.cpp.
References rcSecurityKey::eTextKeyLength, mEncryptor, mHostKey, mReadAlways, rcA, rcB, rcK, and readFile().
                                                                                       :
         mLicenseFile( licenseFileName ),
         mLicenseString(),
         mHostKey( rcSecurityKey( std::string( rcE, rcSecurityKey::eTextKeyLength ) ) ),
         mEncryptor( mHostKey ),
         mExpirationTime( 0 ),
         mReadAlways( true )
 {
     // Dummy ctors for obfuscation
     mHostKey = rcSecurityKey( std::string( rcB, rcSecurityKey::eTextKeyLength ) );
     mEncryptor = rcEncryptionEngine( mHostKey );
     mHostKey = rcSecurityKey( std::string( rcK, rcSecurityKey::eTextKeyLength ) );
     mEncryptor = rcEncryptionEngine( mHostKey );
     // The real thing
     mHostKey = rcSecurityKey( std::string( rcA, rcSecurityKey::eTextKeyLength ) );
     mEncryptor = rcEncryptionEngine( mHostKey );
     // Read file once
     readFile();
     mReadAlways = readAlways;
}
rcLicenseManager::rcLicenseManager (const std::string & licenseString)
Definition at line 238 of file rc_security.cpp.
References rcSecurityKey::eTextKeyLength, mEncryptor, mHostKey, rcA, rcC, and rcI.
                                                                    :
         mLicenseFile(),
         mLicenseString( licenseString ),
         mHostKey( rcSecurityKey( std::string( rcD, rcSecurityKey::eTextKeyLength ) ) ),
         mEncryptor( mHostKey ),
         mExpirationTime( 0 ),
         mReadAlways( false )
 {
     // Dummy ctors for obfuscation
     mHostKey = rcSecurityKey( std::string( rcC, rcSecurityKey::eTextKeyLength ) );
     mEncryptor = rcEncryptionEngine( mHostKey );
     mHostKey = rcSecurityKey( std::string( rcI, rcSecurityKey::eTextKeyLength ) );
     mEncryptor = rcEncryptionEngine( mHostKey );
     // The real thing
     mHostKey = rcSecurityKey( std::string( rcA, rcSecurityKey::eTextKeyLength ) );
     mEncryptor = rcEncryptionEngine( mHostKey );
}
Member Function Documentation
std::string rcLicenseManager::generateChecksum (const std::string & str) static
Definition at line 431 of file rc_security.cpp.
References eLicenseChecksumLength, hexifyString(), and rmAssert.
Referenced by licenseChecksumIsValid().
 {
     int32 sum = 0;
     // Sum all char values
     for ( uint32 i = 0; i < str.length(); i++ ) {
         unsigned char c = str[i];
         sum += c;
     }
     // Checksum is the remainder
     char c = (sum % 256);
     std::string checkString = hexifyString( std::string( &c, 1 ) );
     rmAssert( checkString.length() == eLicenseChecksumLength );
     return checkString;
 }
std::string rcLicenseManager::getErrorString (rcSecurityError error) static
Definition at line 406 of file rc_security.cpp.
References eSecurityErrorInternal, eSecurityErrorInvalidHost, eSecurityErrorInvalidLicense, eSecurityErrorLicenseExpired, eSecurityErrorNoLicense, eSecurityErrorOK, and eSecurityErrorUnknown.
Referenced by rcModelDomain::rle().
 {
     switch ( error ) {
         case eSecurityErrorOK:
             return std::string( "License manager: OK" );
         case eSecurityErrorUnknown:
             return std::string( "License manager: unknown error" );
         case eSecurityErrorNoLicense:
             return std::string( "License manager: cannot read license file" );
         case eSecurityErrorInvalidLicense:
             return std::string( "License manager: invalid license file" );
         case eSecurityErrorInvalidHost:
             return std::string( "License manager: no license for this host" );
         case eSecurityErrorLicenseExpired:
             return std::string( "License manager: license has expired" );
         case eSecurityErrorInternal:
             return std::string( "License manager: internal error" );
             // Note: no default case to force a compiler warning if a new enum value
             // is defined without adding a corresponding string here.
     }
     return std::string( "License manager: undefined error" );
 }
std::string rcLicenseManager::getHostId () const
Definition at line 451 of file rc_security.cpp.
References rcSecurityKey::eTextKeyLength, findEthernetInterfaces(), and getMACAddress().
Referenced by rcModelDomain::rle(), and validHost().
 {
     std::string id;
     io_iterator_t   intfIterator;
     kern_return_t   kernResult = KERN_SUCCESS; // on PowerPC this is an int (4 bytes)
     size_t len = kIOEthernetAddressSize;
     if ( len < rcSecurityKey::eTextKeyLength )
         len = rcSecurityKey::eTextKeyLength;
     // Allocate memory for id
     char* buf = new char[len];
     memset(buf, 0, len);
     kernResult = findEthernetInterfaces(&intfIterator);
     if ( kernResult == KERN_SUCCESS  ) {
         kernResult = getMACAddress(intfIterator, (UInt8*)buf);
         if ( kernResult == KERN_SUCCESS ) {
             id = std::string( buf, len );
         }
     }
     delete [] buf;
     (void) IOObjectRelease(intfIterator);   // Release the iterator.
     return id;
 }
std::string rcLicenseManager::getLicenseExpirationTime ()
Definition at line 301 of file rc_security.cpp.
References eSecurityErrorNoLicense, eSecurityErrorOK, mExpirationTime, and validFile().
Referenced by rcModelDomain::getLicenseExpirationTime().
 {
     std::string exp = "N/A";
     rcSecurityError status = validFile();
     if ( status == eSecurityErrorOK ) {
         char buf[27];
         if ( ctime_r( &mExpirationTime, buf ) )
             exp = std::string( buf );
         else
             exp = "invalid license";
     } else {
         switch ( status ) {
             case eSecurityErrorNoLicense:
                 exp = "no license";
                 break;
             default:
                 exp = "invalid license";
                 break;
         }
     }
     return exp;
 }
std::string rcLicenseManager::getLicenseHost ()
Definition at line 327 of file rc_security.cpp.
References eSecurityErrorNoLicense, eSecurityErrorOK, mDecryptedHostString, and validFile().
Referenced by rcModelDomain::rle().
 {
     std::string host = "N/A";
     rcSecurityError status = validFile();
     if ( status == eSecurityErrorOK ) {
         host = mDecryptedHostString;
     } else {
         switch ( status ) {
             case eSecurityErrorNoLicense:
                 host = "no license";
                 break;
             default:
                 host = "invalid license";
                 break;
         }
     }
     return host;
 }
std::string rcLicenseManager::getTime () const private
Definition at line 480 of file rc_security.cpp.
References count(), and rmDim.
 {
     std::string curTime;
     time_t t = time( 0 );
     char buf[32];
     int count = snprintf( buf, rmDim(buf), "%lx", t );
     // Use value only if buf does not overflow
     if ( static_cast<unsigned>(count) <  rmDim(buf) )
         curTime = buf;
     return curTime;
 }
std::string rcLicenseManager::hexifyString (const std::string & str) static
Definition at line 390 of file rc_security.cpp.
References rmDim.
Referenced by generateChecksum(), and rcModelDomain::rle().
 {
     std::string hexString;
     for ( uint32 i = 0; i < str.length(); i++ ) {
         unsigned char c = str[i];
         char buf[3];
         snprintf( buf, rmDim(buf), "%.2x", c );
         hexString += buf;
     }
     return hexString;
 }
rcSecurityError rcLicenseManager::licenseChecksumIsValid () private
Definition at line 495 of file rc_security.cpp.
References eLicenseChecksumLength, eLicenseTotalLength, eSecurityErrorInvalidLicense, eSecurityErrorOK, eSecurityErrorUnknown, generateChecksum(), and mLicenseString.
Referenced by validFile().
 {
     rcSecurityError status = eSecurityErrorUnknown;
     // Checksum verification
     std::string licenseChecksum( mLicenseString, eLicenseTotalLength - eLicenseChecksumLength, eLicenseChecksumLength );
     std::string licenseWithoutChecksum( mLicenseString, 0, eLicenseTotalLength - eLicenseChecksumLength );
     std::string generatedChecksum = generateChecksum( licenseWithoutChecksum );
     if ( generatedChecksum == licenseChecksum )
         status = eSecurityErrorOK;
     else
         status = eSecurityErrorInvalidLicense;
     return status;
 }
rcSecurityError rcLicenseManager::licenseHostHasValidFormat () private
Definition at line 514 of file rc_security.cpp.
References rcEncryptionEngine::decrypt(), eLicenseComponentLength, rcEncryptionEngine::encrypt(), eSecurityErrorInvalidLicense, eSecurityErrorOK, eSecurityErrorUnknown, rcSecurityKey::eTextKeyLength, mDecryptedHostString, mEncryptor, mLicenseString, and unhexifyString().
Referenced by validFile().
 {
     rcSecurityError status = eSecurityErrorUnknown;
     // Get host component
     std::string hostString( mLicenseString, 0, eLicenseComponentLength );
     // Unhexify encrypted host string
     std::string encryptedHostString = unhexifyString( hostString );
     if ( encryptedHostString.length() == rcSecurityKey::eTextKeyLength ) {
         // Dummy string
         std::string dString = encryptedHostString;
         dString[5] = 32;
         // Do dummy encryptions/decryptions
         mDecryptedHostString = mEncryptor.decrypt( dString );
         dString = mEncryptor.encrypt( mDecryptedHostString );
         dString = mEncryptor.decrypt( mDecryptedHostString );
         // Decrypt the real thing
         dString = mEncryptor.decrypt( encryptedHostString );
         // Encrypt the real thing
         mDecryptedHostString = mEncryptor.encrypt( dString );
         // Decrypt the real thing
         mDecryptedHostString = mEncryptor.decrypt( mDecryptedHostString );
         // Do a dummy decryption
         dString = mEncryptor.decrypt( mDecryptedHostString );
         // Check validity of decryption
         if ( mDecryptedHostString.length() == rcSecurityKey::eTextKeyLength ) {
             // Host is valid
             status = eSecurityErrorOK;
         } else {
             status = eSecurityErrorInvalidLicense;
         }
     } else {
         status = eSecurityErrorInvalidLicense;
     }
     return status;
 }
rcSecurityError rcLicenseManager::licenseTimeHasValidFormat () private
Definition at line 555 of file rc_security.cpp.
References rcEncryptionEngine::decrypt(), eLicenseChecksumLength, eLicenseComponentLength, eLicenseTotalLength, rcEncryptionEngine::encrypt(), eSecurityErrorInvalidLicense, eSecurityErrorOK, eSecurityErrorUnknown, rcSecurityKey::eTextKeyLength, mDecryptedTimeString, mEncryptor, mExpirationTime, mLicenseString, unhexifyString(), and unhexifyTime().
Referenced by validFile().
 {
     rcSecurityError status = eSecurityErrorUnknown;
     // Get time component
     std::string timeString( mLicenseString, eLicenseComponentLength, eLicenseComponentLength );
     // Get checksum
     std::string checkString( mLicenseString, eLicenseTotalLength-eLicenseChecksumLength, eLicenseChecksumLength );
     // Unhexify encrypted time string
     std::string encryptedTimeString = unhexifyString( timeString );
     if ( encryptedTimeString.length() == rcSecurityKey::eTextKeyLength ) {
         // Dummy string
         std::string dString = encryptedTimeString;
         dString[3] = 37;
         // Do dummy encryptions/decryptions
         mDecryptedTimeString = mEncryptor.decrypt( dString );
         dString = mEncryptor.encrypt( mDecryptedTimeString );
         dString = mEncryptor.decrypt( mDecryptedTimeString );
         // Decrypt the real thing
         dString = mEncryptor.decrypt( encryptedTimeString );
         // Encrypt the real thing
         mDecryptedTimeString = mEncryptor.encrypt( dString );
         // Decrypt the real thing
         mDecryptedTimeString = mEncryptor.decrypt( mDecryptedTimeString );
         // Do a dummy decryption
         dString = mEncryptor.decrypt( mDecryptedTimeString );
         // Check validity of decryption
         if ( mDecryptedTimeString.length() == rcSecurityKey::eTextKeyLength ) {
             // Time is valid
             mExpirationTime = unhexifyTime( mDecryptedTimeString );
             status = eSecurityErrorOK;
         } else {
             status = eSecurityErrorInvalidLicense;
         }
     } else {
         status = eSecurityErrorInvalidLicense;
     }
     return status;
 }
rcSecurityError rcLicenseManager::readFile () private
Definition at line 600 of file rc_security.cpp.
References count(), eLicenseTotalLength, eSecurityErrorInvalidLicense, eSecurityErrorNoLicense, eSecurityErrorOK, eSecurityErrorUnknown, mLicenseFile, mLicenseString, and mReadAlways.
Referenced by rcLicenseManager(), and validFile().
 {
     rcSecurityError status = eSecurityErrorUnknown;
     if ( mReadAlways ) {
         FILE* file = fopen( mLicenseFile.c_str(), "r" );
         if ( file ) {
             char buf[eLicenseTotalLength+1];
             // Construct license format string
             strstream format;
             format << "%" << eLicenseTotalLength << "s" << ends;
             // Read from license file
             int count = fscanf( file, format.str(), buf );
             format.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
             // If read succeeded, set license string
             if ( count == 1 ) {
                 mLicenseString = buf;
                 status = eSecurityErrorOK;
             } else {
                 status = eSecurityErrorInvalidLicense;
             }
             fclose( file );
         } else {
             status = eSecurityErrorNoLicense;
         }
     }
     return status;
 }
std::string rcLicenseManager::unhexifyString (const std::string & str) static
Definition at line 350 of file rc_security.cpp.
Referenced by licenseHostHasValidFormat(), and licenseTimeHasValidFormat().
 {
     std::string keyString;
     // Hex string is supposed to have two chars per digit
     // If the length is odd, we'll discard the last char
     uint32 len = str.length()/2;
     char digit[3];
     digit[2] = 0;
     for ( uint32 i = 0; i < len; ++i ) {
         digit[0] = str[i*2];
         digit[1] = str[i*2+1];
         uint32 d;
         if ( sscanf( digit, "%x", &d ) == 1 ) {
             keyString += static_cast<unsigned char>(d);
         } else {
             // Error, bail out
             break;
         }
     }
     return keyString;
 }
time_t rcLicenseManager::unhexifyTime (const std::string & str) static
Definition at line 377 of file rc_security.cpp.
Referenced by licenseTimeHasValidFormat().
 {
     time_t t = 0;
     if ( sscanf( str.c_str(), "%lx", &t ) == 1 ) {
     } else {
         // Error
     }
     return t;
 }
rcSecurityError rcLicenseManager::validFile () private
Definition at line 635 of file rc_security.cpp.
References eLicenseTotalLength, eSecurityErrorInvalidLicense, eSecurityErrorNoLicense, eSecurityErrorOK, eSecurityErrorUnknown, licenseChecksumIsValid(), licenseHostHasValidFormat(), licenseTimeHasValidFormat(), mLicenseString, mReadAlways, and readFile().
Referenced by getLicenseExpirationTime(), getLicenseHost(), validHost(), and validTime().
 {
     rcSecurityError status = eSecurityErrorUnknown;
     if ( mReadAlways )
         status = readFile();
     else
         status = eSecurityErrorOK;
     if ( status == eSecurityErrorOK ) {
         // Note: these checks only verify whether the values have
         // a valid format/range, their actual values may be incorrect.
         if ( mLicenseString.length() == eLicenseTotalLength ) {
             // Check host
             status = licenseHostHasValidFormat();
             if ( status == eSecurityErrorOK ) {
                 // Host is valid, now check time
                 status = licenseTimeHasValidFormat();
                 if ( status == eSecurityErrorOK ) {
                     // Host and time are valid, now verify checksum
                     status = licenseChecksumIsValid();
                 }
             } else {
                 // Invalid checksum
             }
         } else {
             // Invalid license string length
             if ( mLicenseString.empty() )
                 status = eSecurityErrorNoLicense;
             else
                 status = eSecurityErrorInvalidLicense;
         }
     }
     return status;
 }
rcSecurityError rcLicenseManager::validHost ()
Definition at line 257 of file rc_security.cpp.
References eSecurityErrorInternal, eSecurityErrorInvalidHost, eSecurityErrorInvalidLicense, eSecurityErrorOK, getHostId(), mDecryptedHostString, and validFile().
Referenced by rcModelDomain::vl().
 {
     rcSecurityError status = validFile();
     if ( status == eSecurityErrorOK ) {
         std::string host = getHostId();
         if ( host.length() ) {
             if ( mDecryptedHostString.length() ) {
                 if ( mDecryptedHostString == host ) {
                     status = eSecurityErrorOK;
                 } else {
                     status = eSecurityErrorInvalidHost;
                 }
             } else {
                 status = eSecurityErrorInvalidLicense;
             }
         } else {
             status = eSecurityErrorInternal;
         }
     }
     return status;
 }
rcSecurityError rcLicenseManager::validTime ()
Definition at line 283 of file rc_security.cpp.
References eSecurityErrorLicenseExpired, eSecurityErrorOK, mExpirationTime, and validFile().
Referenced by rcModelDomain::vl().
 {
     rcSecurityError status = validFile();
     if ( status == eSecurityErrorOK ) {
         time_t cur = time( 0 );
         if ( cur >= mExpirationTime ) {
             status = eSecurityErrorLicenseExpired;
         } else {
             status = eSecurityErrorOK;
         }
     }
     return status;
 }
Friends And Related Function Documentation
friend class UT_Security friend
Definition at line 160 of file rc_security.h.
Member Data Documentation
std::string rcLicenseManager::mDecryptedHostString private
Definition at line 185 of file rc_security.h.
Referenced by getLicenseHost(), licenseHostHasValidFormat(), and validHost().
std::string rcLicenseManager::mDecryptedTimeString private
Definition at line 184 of file rc_security.h.
Referenced by licenseTimeHasValidFormat().
rcEncryptionEngine rcLicenseManager::mEncryptor private
Definition at line 180 of file rc_security.h.
Referenced by licenseHostHasValidFormat(), licenseTimeHasValidFormat(), and rcLicenseManager().
time_t rcLicenseManager::mExpirationTime private
Definition at line 182 of file rc_security.h.
Referenced by getLicenseExpirationTime(), licenseTimeHasValidFormat(), and validTime().
rcSecurityKey rcLicenseManager::mHostKey private
Definition at line 179 of file rc_security.h.
Referenced by rcLicenseManager().
std::string rcLicenseManager::mLicenseFile private
Definition at line 177 of file rc_security.h.
Referenced by readFile().
std::string rcLicenseManager::mLicenseString private
Definition at line 178 of file rc_security.h.
Referenced by licenseChecksumIsValid(), licenseHostHasValidFormat(), licenseTimeHasValidFormat(), readFile(), and validFile().
bool rcLicenseManager::mReadAlways private
Definition at line 183 of file rc_security.h.
Referenced by rcLicenseManager(), readFile(), and validFile().
The documentation for this class was generated from the following files:
include/util/rc_security.h
src/util/code/rc_security.cpp