Visible: rcUnitTest Class Reference
rcUnitTest Class Reference abstract
#include <include/util/rc_unittest.h>
Public Member Functions
rcUnitTest ()
virtual ~rcUnitTest ()
virtual uint32 run ()=0
void printSuccessMessage (const char *msg, uint32 errors)
uint32 Assert (uint32 expr, const char *exprString, const char *file, int lineNumber)
void randomSeed ()
Static Public Member Functions
static std::string makeTmpName (const char *pathFormat, const char *baseName)
static std::string makeTmpName (const char *baseName)
Protected Attributes
uint32 mErrors
std::string mFileName
Detailed Description
Definition at line 45 of file rc_unittest.h.
Constructor & Destructor Documentation
rcUnitTest::rcUnitTest () inline
Definition at line 47 of file rc_unittest.h.
 : mErrors( 0 ) { };
virtual rcUnitTest::~rcUnitTest () inline virtual
Definition at line 49 of file rc_unittest.h.
 { };
Member Function Documentation
uint32 rcUnitTest::Assert (uint32 expr, const char * exprString, const char * file, int lineNumber) inline
Definition at line 67 of file rc_unittest.h.
References mErrors.
{
         if ( ! expr ) {
             ++mErrors;
             fprintf( stderr, "Assertion %s failed in %s at line %i\n",
                      exprString, file, lineNumber );
         }
         return expr;
     }
static std::string rcUnitTest::makeTmpName (const char * pathFormat, const char * baseName) inline static
Definition at line 88 of file rc_unittest.h.
References rcTimestamp::now(), rmDim, and rcTimestamp::secs().
Referenced by makeTmpName().
     {
       char buf[2048];
       static const char *defaultFormat = "/tmp/um%d_%s";
       // Use current time in seconds as a pseudo-unique prefix
       double secs = rcTimestamp::now().secs();
       snprintf( buf, rmDim(buf), pathFormat ? pathFormat : defaultFormat,
         uint32(secs), baseName );
       return std::string( buf );
     }
static std::string rcUnitTest::makeTmpName (const char * baseName) inline static
Definition at line 101 of file rc_unittest.h.
References makeTmpName().
     {
       return makeTmpName (0, baseName);
     }
void rcUnitTest::printSuccessMessage (const char * msg, uint32 errors) inline
Definition at line 55 of file rc_unittest.h.
 {}
void rcUnitTest::randomSeed () inline
Definition at line 77 of file rc_unittest.h.
References getTimestampResolution(), rcTimestamp::now(), and rcTimestamp::secs().
     {
       // Set a seed from two clocks
       uint32 seed;
       rcTimestamp now = rcTimestamp::now();
       uint32 secs = uint32(now.secs());
       seed = uint32( (now.secs() - secs) / getTimestampResolution() + clock() );
       srandom (seed);
     }
virtual uint32 rcUnitTest::run () pure virtual
Member Data Documentation
uint32 rcUnitTest::mErrors protected
Definition at line 107 of file rc_unittest.h.
Referenced by Assert().
std::string rcUnitTest::mFileName protected
Definition at line 108 of file rc_unittest.h.
The documentation for this class was generated from the following file:
include/util/rc_unittest.h