Visible: rcCameraGrabber Class Reference
rcCameraGrabber Class Reference abstract
#include <include/visual/rc_qvideograbber.h>
Public Member Functions
virtual rcFrameGrabberStatus getAcqInfo (rcAcqInfo &acqInfo, bool isBlocking, bool releaseMemory=TRUE)=0
virtual rcFrameGrabberStatus setAcqControl (rcAcqControl &acqCtrl, bool isBlocking, bool releaseMemory=TRUE)=0
virtual int32 cacheSize ()
virtual void setFrameCount (int32 frameCount)=0
virtual void addBuffer (rcSharedFrameBufPtr &buf)=0
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
virtual bool isValid () const =0
virtual rcFrameGrabberError getLastError () const =0
virtual bool start ()=0
virtual bool stop ()=0
virtual int32 frameCount ()=0
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)=0
virtual const std::string getInputSourceName ()=0
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Detailed Description
Definition at line 25 of file rc_qvideograbber.h.
Member Function Documentation
virtual void rcCameraGrabber::addBuffer (rcSharedFrameBufPtr & buf) pure virtual
Implemented in rcQVideoGrabber.
Referenced by rcEngineMovieCapture::initializeCamera().
virtual int32 rcCameraGrabber::cacheSize () inline virtual
Implements rcFrameGrabber.
Definition at line 38 of file rc_qvideograbber.h.
 { return 0; }
virtual rcFrameGrabberStatus rcCameraGrabber::getAcqInfo (rcAcqInfo & acqInfo, bool isBlocking, bool releaseMemory = TRUE) pure virtual
Implemented in rcQVideoGrabber.
Referenced by rcEngineMovieCapture::getCameraState(), and rcEngineMovieCapture::initializeCamera().
virtual rcFrameGrabberStatus rcCameraGrabber::setAcqControl (rcAcqControl & acqCtrl, bool isBlocking, bool releaseMemory = TRUE) pure virtual
Implemented in rcQVideoGrabber.
Referenced by rcEngineMovieCapture::initializeCamera(), rcEngineMovieCapture::sendShutdown(), and rcEngineMovieCapture::updateCameraSettings().
virtual void rcCameraGrabber::setFrameCount (int32 frameCount) pure virtual
Implemented in rcQVideoGrabber.
Referenced by rcEngineMovieCapture::run().
The documentation for this class was generated from the following file:
include/visual/rc_qvideograbber.h