Visible: rcMainWindow Class Reference
rcMainWindow Class Reference
#include <include/visUI/rc_mainwindow.h>
Public Slots
void settingChanged ()
Public Member Functions
rcMainWindow (QWidget *parent=0, const char *name=0, Qt::WFlags fl=Qt::WType_TopLevel)
~rcMainWindow ()
Protected Member Functions
void closeEvent (QCloseEvent *)
Private Attributes
rcStatusBar * mStatusBar
Detailed Description
Definition at line 19 of file rc_mainwindow.h.
Constructor & Destructor Documentation
rcMainWindow::rcMainWindow (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = Qt::WType_TopLevel)
Definition at line 43 of file rc_mainwindow.cpp.
References cAppBuildDate, cAppName, cLayoutSpacing, cVersionName, rcModelDomain::getModelDomain(), rcPersistenceManagerFactory::getPersistenceManager(), mStatusBar, rcPersistenceManager::setGeneratorComment(), and settingChanged().
     : QWidget( parent, name, fl )
 {
     // Make the top-level layout; a vertical box to contain all widgets
     // and sub-layouts.
     Q3BoxLayout *topLayout = new Q3VBoxLayout( this , cLayoutSpacing );
     // Create a menubar and tell the layout about it.
     rcMenuBar* menuBar = new rcMenuBar( this , "menubar" );
     topLayout->setMenuBar( menuBar );
     // Create a horizontal layout to put the Monitor in.
     Q3BoxLayout *setMonLayout = new Q3HBoxLayout( topLayout );
     // Create a Monitor
     rcMonitor* monitor = new rcMonitor( this, "monitor" );
     setMonLayout->addWidget( monitor );
     // Create a vertical layout to put the SettingsPanel and ControlPanel in.
     Q3BoxLayout *tlCpLayout = new Q3VBoxLayout( setMonLayout );
     // Create a rcSettingsPanel
     rcSettingPanel* settingPanel = new rcSettingPanel( this , "settingsPanel" );
     tlCpLayout->addWidget( settingPanel, Qt::AlignTop );
     // Create a rcControlPanel
     rcControlPanel* controlPanel = new rcControlPanel( this , "controlPanel" );
     tlCpLayout->addWidget( controlPanel, Qt::AlignTop );
     // Create a horizontal layout to put the trackpanel and timeline in.
     Q3BoxLayout *tpTlLayout = new Q3HBoxLayout( topLayout );
     // Create a Track Panel
     rcTrackPanel* trackPanel = new rcTrackPanel( this, "trackPanel" );
     tpTlLayout->addWidget( trackPanel );
     // Create a Timeline
     rcTimeline* timeline = new rcTimeline( this, "timeline" );
     tpTlLayout->addWidget( timeline , 2 );
     // Create a status bar
     mStatusBar = new rcStatusBar( this , "status" );
     topLayout->addWidget( mStatusBar );
     // Stretch factors for resizing
     topLayout->setStretchFactor( setMonLayout , 10 );
     topLayout->setStretchFactor( tlCpLayout , 1 );
     topLayout->setStretchFactor( tpTlLayout , 1 );
     topLayout->setStretchFactor( mStatusBar , 0 );
     setMonLayout->setStretchFactor( monitor , 10 );
     tpTlLayout->setStretchFactor( trackPanel, 1 );
     tpTlLayout->setStretchFactor( timeline, 2 );
     tlCpLayout->setStretchFactor( settingPanel, 1 );
     tlCpLayout->setStretchFactor( controlPanel, 0 );
     topLayout->activate();
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     // Set application (generator) info
     rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     // Concatenate application name, version and build date
     std::string comment = cAppName;
     comment += " ";
     comment += cVersionName;
     comment += " ";
     comment += cAppBuildDate;
     persistenceManager->setGeneratorComment( comment );
 }
rcMainWindow::~rcMainWindow ()
Definition at line 121 of file rc_mainwindow.cpp.
 {
     // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void rcMainWindow::closeEvent (QCloseEvent * event) protected
Definition at line 176 of file rc_mainwindow.cpp.
References cAppName, eExperimentEmpty, eExperimentLocked, eExperimentNativeFormat, rcModelDomain::getExperimentState(), rcModelDomain::getModelDomain(), and rcModelDomain::requestSave().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperimentState state = domain->getExperimentState();
     if ( state != eExperimentEmpty && state != eExperimentLocked ) {
         // No data has been saved, prompt user
         switch( QMessageBox::warning( 0, cAppName,
                                       "Do you want to save experiment data before quitting?\n\n"
                                       "If you don't save, your data will be lost.",
                                       "&Don't Save", "Cancel", "&Save",
                                       2, 1 ) ) {
             case 0: // Don't Save clicked or Alt+D pressed
                 event->accept();
                 break;
             case 1: // Cancel clicked or Alt+C pressed or Escape pressed
                     // Do nothing
                 break;
             case 2: // Save clicked or Alt+S pressed
                 domain->requestSave( eExperimentNativeFormat );
                 if ( domain->getExperimentState() == eExperimentLocked )
                     event->accept();
                 break;
         }
     } else
         event->accept();
 }
void rcMainWindow::settingChanged (void) slot
Definition at line 128 of file rc_mainwindow.cpp.
References FALSE, rcExperimentAttributes::frameDepth, rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcExperimentAttributes::inputName, rcExperimentAttributes::liveInput, mStatusBar, rcExperimentAttributes::title, and TRUE.
Referenced by rcMainWindow().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     // Get current experiment attributes
     rcExperimentAttributes attr = domain->getExperimentAttributes();
     uint32 maxX = attr.frameWidth;
     uint32 maxY = attr.frameHeight;
     int depth = attr.frameDepth * 8; // Bits per pixel
     std::string title = attr.title;
     if (title == std::string ("Untitled"))
       title = attr.inputName;
     string::size_type pos = title.find (';', 0);
     if ( pos != string::npos)
       {
     //make a string up to the ;
     title = std::string (title, 0, pos);
     pos = title.find_last_of ('/', string::npos);
     if ( pos != string::npos)
       {
         title = std::string (title, 0, pos);
         pos = title.find ('/', 0);
         if ( pos != string::npos)
           {
         title = std::string (title, pos, title.size());
           }
       }
       }
     strstream caption;
     // Concatenate experiment title, video frame size and depth
     caption << title;
     if ( depth > 0 )
         caption << " (" << maxX << "x" << maxY << "x" << depth << ")";
     caption << ends;
     // Set window bar caption
     setCaption( caption.str() );
     caption.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
     // Disable resizing for camera
     if ( attr.liveInput ) {
         mStatusBar->setSizeGripEnabled( FALSE );
     } else {
         mStatusBar->setSizeGripEnabled( TRUE );
     }
 }
Member Data Documentation
rcStatusBar* rcMainWindow::mStatusBar private
Definition at line 34 of file rc_mainwindow.h.
Referenced by rcMainWindow(), and settingChanged().
The documentation for this class was generated from the following files:
include/visUI/rc_mainwindow.h
src/visible/qt/rc_mainwindow.cpp