Visible: rcVisualTarget Class Reference
rcVisualTarget Class Reference
#include <include/analysis/rc_visualtarget.h>
Public Types
enum Lines {
eVectors, eBoundingBox, eBoundingPoly, eCurl,
eRelief
}
enum State {
eUnInitialized =0, eIsMoving, eIsDirected, eIsRandom,
eIsOutSide
}
enum Measure { eHasTemporal = 0, eVelocity, eSpeed, edPersistence }
enum ChainDirection {
eMinusY, ePlusY, eMinusX, ePlusX =0,
eEnd
}
enum Haves { eHaveNothing = 0, ekeepCurrentOnly, eKeepImages }
Public Member Functions
rcVisualTarget ()
rcVisualTarget (const rc2Fvector &anchor, const rcFRect &bBox)
virtual ~rcVisualTarget ()
uint32 id () const
float area () const
float rmsQuality () const
float distance () const
const rc2Fvector & velocity () const
float speed () const
float persistence () const
float minSqDisplacement () const
State state () const
const int32 history () const
const deque< rcWindow > & snaps () const
const deque< rcIRect > & rectSnaps () const
const rcIRect & minTemporalEnclosingRect () const
const rcIRect & minTemporalIntersectingRect () const
virtual void measure ()
virtual void reconcile ()
virtual void update (const rc2Fvector &, const double &time, const float &quality)
bool operator< (const rcVisualTarget &rhs) const
bool operator== (const rcVisualTarget &rhs) const
Public Member Functions inherited from rcBaseMotionPath
rcBaseMotionPath ()
virtual ~rcBaseMotionPath ()
virtual void update ()=0
bool isWithin (rcFPair &) const
const float & dob () const
const rc2Fvector position () const
dob :Return date of birth relative to kinetoscope start
rcIPair iAnchor () const
position Position with respect to the image from it was created from
const rc2Fvector & travelled () const
const rc2Fvector & motion () const
const rc2Fvector & anchor () const
void move (const rc2Fvector &t)
void move (const rc2Xform &xm)
move (vector) Move assuming the (t) -> (t+1) for motion vectors we assume translation
const rc2Fvector & anchor (const rc2Fvector &a)
move (xform) Move assuming the (t) -> (t+1) for motion vectors we assume translation
void step ()
uint32 steps () const
bool isAtStep (uint32 step) const
Private Attributes
State mState
uint32 mId
int32 mSize
float mArea
float mCosSums
float mQuality
float mLastQuality
rcRadian mLastAngle
float mRdiffuse
deque< rcWindow > mSnaps
deque< rcIRect > mRectSnaps
rcIRect mMinTemporalEncRect
rcIRect mMinTemporalIntRect
double mDistance
rcFRect mFixed
float mMotionPattern
rc2Fvector mV
Static Private Attributes
static const float inValidOrigin = rcFLT_MIN
static const float inValidDispersion = rcFLT_MIN
Friends
ostream & operator<< (ostream &, const rcVisualTarget &)
Additional Inherited Members
Protected Attributes inherited from rcBaseMotionPath
float mGenesis
rc2Fvector mStartPosition
rc2Fvector mDxDt
rc2Fvector mSumPos
uint32 mSteps
Detailed Description
Definition at line 38 of file rc_visualtarget.h.
Member Enumeration Documentation
enum rcVisualTarget::ChainDirection
Enumerator
eMinusY
ePlusY
eMinusX
ePlusX
eEnd
Definition at line 159 of file rc_visualtarget.h.
   {
     eMinusY,            // up
     ePlusY,         // down
     eMinusX,            // left
     ePlusX=0,           // right
     eEnd
   };
enum rcVisualTarget::Haves
Enumerator
eHaveNothing
ekeepCurrentOnly
eKeepImages
Definition at line 218 of file rc_visualtarget.h.
   {
     eHaveNothing = 0,
     ekeepCurrentOnly,
     eKeepImages
   };
enum rcVisualTarget::Lines
Enumerator
eVectors
eBoundingBox
eBoundingPoly
eCurl
eRelief
Definition at line 132 of file rc_visualtarget.h.
   {
     eVectors,
     eBoundingBox,
     eBoundingPoly,
     eCurl,
     eRelief
   };
enum rcVisualTarget::Measure
Enumerator
eHasTemporal
eVelocity
eSpeed
edPersistence
Definition at line 151 of file rc_visualtarget.h.
   {
     eHasTemporal = 0,
     eVelocity,
     eSpeed,
     edPersistence
   };
enum rcVisualTarget::State
Enumerator
eUnInitialized
eIsMoving
eIsDirected
eIsRandom
eIsOutSide
Definition at line 142 of file rc_visualtarget.h.
   {
     eUnInitialized=0,
     eIsMoving,
     eIsDirected,
     eIsRandom,
     eIsOutSide
   };
Constructor & Destructor Documentation
rcVisualTarget::rcVisualTarget ()
rcVisualTarget::rcVisualTarget (const rc2Fvector & anchor, const rcFRect & bBox)
Definition at line 49 of file rc_visualtarget.cpp.
References eUnInitialized, rcRectangle< T >::height(), mCosSums, mDistance, mFixed, mQuality, mRdiffuse, mRectSnaps, rcBaseMotionPath::mStartPosition, mState, rcBaseMotionPath::mSumPos, rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
     mDistance = 0.0;
   mSumPos.x(0.0);
   mSumPos.y(0.0);
   mStartPosition.x(anchor.x());
   mStartPosition.y(anchor.y());
   mCosSums = 0.0f;
   mQuality = 1.0f;
   mRectSnaps.push_back (rcIRect ((int) bBox.ul().x(), (int)bBox.ul().y(), (int) bBox.width(), (int) bBox.height()));
   mRdiffuse = 0.0f;
   mState = eUnInitialized;
   mFixed = bBox;
 }
virtual rcVisualTarget::~rcVisualTarget () inline virtual
Definition at line 56 of file rc_visualtarget.h.
 {}
Member Function Documentation
float rcVisualTarget::area () const inline
Definition at line 70 of file rc_visualtarget.h.
Referenced by operator<<().
   {
     return mArea;
   }
float rcVisualTarget::distance () const inline
Definition at line 88 of file rc_visualtarget.h.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mDistance;
   }
const int32 rcVisualTarget::history () const inline
Definition at line 177 of file rc_visualtarget.h.
 {return mSize; }
uint32 rcVisualTarget::id () const inline
Definition at line 62 of file rc_visualtarget.h.
Referenced by rcCellWriterGroupCollection::addCell().
 {return mId; }
void rcVisualTarget::measure () virtual
Implements rcBaseMotionPath.
Definition at line 85 of file rc_visualtarget.cpp.
References rmAssert.
 {
     rmAssert (0);
 }
float rcVisualTarget::minSqDisplacement () const inline
Definition at line 122 of file rc_visualtarget.h.
   {
     return mRdiffuse;
   }
const rcIRect& rcVisualTarget::minTemporalEnclosingRect () const inline
Definition at line 197 of file rc_visualtarget.h.
 {return mMinTemporalEncRect; }
const rcIRect& rcVisualTarget::minTemporalIntersectingRect () const inline
Definition at line 203 of file rc_visualtarget.h.
 {return mMinTemporalIntRect; }
bool rcVisualTarget::operator< (const rcVisualTarget & rhs) const inline
Definition at line 228 of file rc_visualtarget.h.
References mId.
 { return mId < rhs.mId; };
bool rcVisualTarget::operator== (const rcVisualTarget & rhs) const inline
Definition at line 229 of file rc_visualtarget.h.
References mId.
 { return mId == rhs.mId; };
float rcVisualTarget::persistence () const
Definition at line 79 of file rc_visualtarget.cpp.
References mCosSums, rcBaseMotionPath::mSteps, and rmMax.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
 {
   double p = mCosSums / ((float) (rmMax (1, mSteps)));
   return (p);
 }
void rcVisualTarget::reconcile () virtual
Implements rcBaseMotionPath.
Definition at line 90 of file rc_visualtarget.cpp.
References rmAssert.
 {
     rmAssert (0);
 }
const deque<rcIRect>& rcVisualTarget::rectSnaps () const inline
Definition at line 190 of file rc_visualtarget.h.
Referenced by operator<<().
 {return mRectSnaps; }
float rcVisualTarget::rmsQuality () const inline
Definition at line 79 of file rc_visualtarget.h.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mQuality;
   }
const deque<rcWindow>& rcVisualTarget::snaps () const inline
Definition at line 183 of file rc_visualtarget.h.
 {return mSnaps; }
float rcVisualTarget::speed () const
Definition at line 164 of file rc_visualtarget.cpp.
References mV, rmSquare, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by operator<<().
 {
   return sqrt (rmSquare(mV.x()) + rmSquare(mV.y()));
 }
State rcVisualTarget::state () const inline
Definition at line 172 of file rc_visualtarget.h.
 {return mState; }
void rcVisualTarget::update (const rc2Fvector & pos, const double & time, const float & quality) virtual
Definition at line 96 of file rc_visualtarget.cpp.
References eIsOutSide, endl(), rcRectangle< T >::height(), mDistance, mFixed, mLastAngle, mLastQuality, mRdiffuse, mRectSnaps, mState, rcBaseMotionPath::mSumPos, rcRectangle< T >::origin(), quality, rfRoundNeg(), rfRoundPlus(), rmABS, rmMax, rcRectangle< T >::translate(), rcRectangle< T >::width(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
   rcRadian angle;
   double len;
   rcIRect last = mRectSnaps.back();
   if (mState == eIsOutSide) return;
 /* Note on Coordinate Transformation:
  * A 2x2 matrix is defined as follows in terms of these variables:
  *   |dX|   |-1  0  |   |Translation in X|
  *   |dY| = |0   -1 | * |Translation in Y|
  *
  */
 //  const rc2Fvector& pos = feature().pos();
   mSumPos -= pos;
   mRdiffuse += (pos.x() * pos.x() + pos.y() * pos.y());
 #if 0
   if (feature().hasPolar())
     feature().polar (len, angle);
   else
     {
       len = 0.0;
       angle = mLastAngle;
     }
   mDistance += len;
 #endif
   // Velocity is instant velocity
 //  mV.x (pos.x() / mKine->deltaTime());
 //  mV.y (pos.y() / mKine->deltaTime());
   // Calculate dR/dS
   // Adjust region size proportional to correlation match.
   // Notice that we shrink if correlation is improvign, and expand when
   // it is not. A consistenly scoring object will oscilate on the edge
   // of shrink and expand but of a very small amount.
   float drds = 1. / (log(rmMax (rmABS (mLastQuality - quality), 0.001)));
   drds = (mLastQuality > quality) ? - drds : drds;
   mLastQuality = quality;
   // Translate according to our velocity
   // Note triming a rect by negative expands the rect
   const rcFPair trans (-pos.x(), -pos.y());
   mFixed.translate (trans);
   //  mFixed = mFixed.trim (drds, drds, drds, drds);
   static const int32 dummy (0);
   // Round up ul -- round down lr
   rcIPair ul (rfRoundNeg (mFixed.origin().x(), dummy),
           rfRoundNeg (mFixed.origin().y(), dummy));
   rcIPair lr (rfRoundPlus (mFixed.origin().x() + mFixed.width(), dummy),
           rfRoundPlus (mFixed.origin().y() + mFixed.height(), dummy));
    mRectSnaps.push_back (last);
 #ifdef TRACKDEBUG
   cout << "Update: " << endl;
   cout << *this << endl;
 #endif
 }
const rc2Fvector& rcVisualTarget::velocity () const inline
Definition at line 97 of file rc_visualtarget.h.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mV;
   }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcVisualTarget & p) friend
Definition at line 170 of file rc_visualtarget.cpp.
 {
   o << "====> Target   : " << p.mId << "<=======" << endl;
   o << "Trace        :" << p.anchor() << endl;
   o << "Area         :" << p.area() << endl;
   o << "Distance     :" << p.distance() << endl;
   o << "Persistance  :" << p.persistence() << endl;
   o << "Anchor       :" << p.anchor() << endl;
   o << "Position     :" << p.position () << endl;
   o << "Velocity     :" << p.velocity() << endl;
   o << "Speed        :" << p.speed() << endl;
   o << "Mean Quality : " << p.rmsQuality() << endl;
 #if 0
   deque<rcIRect>::const_iterator rq = p.rectSnaps().begin();
   int q = 0;
   for (; rq != p.rectSnaps().end(); rq++, q++)
     cout << "[" << q << ":" << *rq << "]";
 #endif
   return o;
 }
Member Data Documentation
const float rcVisualTarget::inValidDispersion = rcFLT_MIN static private
Definition at line 41 of file rc_visualtarget.h.
const float rcVisualTarget::inValidOrigin = rcFLT_MIN static private
Definition at line 40 of file rc_visualtarget.h.
float rcVisualTarget::mArea private
Definition at line 235 of file rc_visualtarget.h.
float rcVisualTarget::mCosSums private
Definition at line 237 of file rc_visualtarget.h.
Referenced by persistence(), and rcVisualTarget().
double rcVisualTarget::mDistance private
Definition at line 247 of file rc_visualtarget.h.
Referenced by rcVisualTarget(), and update().
rcFRect rcVisualTarget::mFixed private
Definition at line 248 of file rc_visualtarget.h.
Referenced by rcVisualTarget(), and update().
uint32 rcVisualTarget::mId private
Definition at line 233 of file rc_visualtarget.h.
Referenced by operator<(), operator<<(), and operator==().
rcRadian rcVisualTarget::mLastAngle private
Definition at line 240 of file rc_visualtarget.h.
Referenced by update().
float rcVisualTarget::mLastQuality private
Definition at line 239 of file rc_visualtarget.h.
Referenced by update().
rcIRect rcVisualTarget::mMinTemporalEncRect private
Definition at line 245 of file rc_visualtarget.h.
rcIRect rcVisualTarget::mMinTemporalIntRect private
Definition at line 246 of file rc_visualtarget.h.
float rcVisualTarget::mMotionPattern private
Definition at line 249 of file rc_visualtarget.h.
float rcVisualTarget::mQuality private
Definition at line 238 of file rc_visualtarget.h.
Referenced by rcVisualTarget().
float rcVisualTarget::mRdiffuse private
Definition at line 241 of file rc_visualtarget.h.
Referenced by rcVisualTarget(), and update().
deque<rcIRect> rcVisualTarget::mRectSnaps private
Definition at line 244 of file rc_visualtarget.h.
Referenced by rcVisualTarget(), and update().
int32 rcVisualTarget::mSize private
Definition at line 234 of file rc_visualtarget.h.
deque<rcWindow> rcVisualTarget::mSnaps private
Definition at line 243 of file rc_visualtarget.h.
State rcVisualTarget::mState private
Definition at line 229 of file rc_visualtarget.h.
Referenced by rcVisualTarget(), and update().
rc2Fvector rcVisualTarget::mV private
Definition at line 252 of file rc_visualtarget.h.
Referenced by speed().
The documentation for this class was generated from the following files:
include/analysis/rc_visualtarget.h
src/analysis/code/rc_visualtarget.cpp