Visible: error_handler_base Class Reference
error_handler_base Class Reference
#include <include/stlplus/error_handler.hpp>
Public Member Functions
error_handler_base (bool show=true) throw ()
error_handler_base (const std::string &message_file, bool show=true) throw (error_handler_read_error)
error_handler_base (const std::vector< std::string > &message_files, bool show=true) throw (error_handler_read_error)
virtual ~error_handler_base (void) throw ()
void add_message_file (const std::string &message_file) throw (error_handler_read_error)
void add_message_files (const std::vector< std::string > &message_files) throw (error_handler_read_error)
void add_message (const std::string &id, const std::string &text) throw ()
void set_information_format (const std::string &format) throw ()
void set_warning_format (const std::string &format) throw ()
void set_error_format (const std::string &format) throw ()
void set_fatal_format (const std::string &format) throw ()
void set_context_format (const std::string &format) throw ()
void set_supplement_format (const std::string &format) throw ()
void set_position_format (const std::string &format) throw ()
void show_position (void) throw ()
void hide_position (void) throw ()
std::vector< std::string > information_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
unsigned context_depth (void) const throw ()
void pop_context (void) throw ()
void pop_context (unsigned) throw ()
error_context auto_push_context (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
Private Attributes
smart_ptr_nocopy
< error_handler_base_body > m_base_body
Friends
class error_handler_base_body
Detailed Description
Definition at line 180 of file error_handler.hpp.
Constructor & Destructor Documentation
error_handler_base::error_handler_base (bool show = true) throw ()
Definition at line 583 of file error_handler.cpp.
           :
   m_base_body(new error_handler_base_body)
 {
   m_base_body->set_show(show);
 }
error_handler_base::error_handler_base (const std::string & message_file, bool show = true) throw (error_handler_read_error)
Definition at line 590 of file error_handler.cpp.
                                   :
   m_base_body(new error_handler_base_body)
 {
   m_base_body->set_show(show);
   add_message_file(file);
 }
error_handler_base::error_handler_base (const std::vector< std::string > & message_files, bool show = true) throw (error_handler_read_error)
Definition at line 598 of file error_handler.cpp.
                                   :
   m_base_body(new error_handler_base_body)
 {
   m_base_body->set_show(show);
   add_message_files(files);
 }
error_handler_base::~error_handler_base (void) throw () virtual
Definition at line 606 of file error_handler.cpp.
 {
 }
Member Function Documentation
void error_handler_base::add_message (const std::string & id, const std::string & text) throw ()
Definition at line 626 of file error_handler.cpp.
 {
   m_base_body->add_message(id,text);
 }
void error_handler_base::add_message_file (const std::string & message_file) throw (error_handler_read_error)
Definition at line 613 of file error_handler.cpp.
 {
   m_base_body->add_message_file(file);
 }
void error_handler_base::add_message_files (const std::vector< std::string > & message_files) throw (error_handler_read_error)
Definition at line 619 of file error_handler.cpp.
 {
   for (unsigned i = 0; i < files.size(); i++)
     add_message_file(files[i]);
 }
error_context error_handler_base::auto_push_context (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1275 of file error_handler.cpp.
 {
   return auto_push_context(error_position(), id, args);
 }
error_context error_handler_base::auto_push_context (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1281 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return auto_push_context(id, args);
 }
error_context error_handler_base::auto_push_context (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1288 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return auto_push_context(id, args);
 }
error_context error_handler_base::auto_push_context (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1296 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return auto_push_context(id, args);
 }
error_context error_handler_base::auto_push_context (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1307 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return auto_push_context(id, args);
 }
error_context error_handler_base::auto_push_context (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1320 of file error_handler.cpp.
 {
   error_context result(new error_context_body(*this));
   m_base_body->push_context(position, id, args);
   return result;
 }
error_context error_handler_base::auto_push_context (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1330 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return auto_push_context(position, id, args);
 }
error_context error_handler_base::auto_push_context (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1338 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return auto_push_context(position, id, args);
 }
error_context error_handler_base::auto_push_context (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1348 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return auto_push_context(position, id, args);
 }
error_context error_handler_base::auto_push_context (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1360 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return auto_push_context(position, id, args);
 }
unsigned error_handler_base::context_depth (void) const throw ()
Definition at line 1269 of file error_handler.cpp.
References error_handler_base_body::context_depth(), and m_base_body.
Referenced by error_context_body::set().
 {
   return m_base_body->context_depth();
 }
std::vector< std::string > error_handler_base::error_message (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 878 of file error_handler.cpp.
 {
   return error_message(error_position(), id, args);
 }
std::vector< std::string > error_handler_base::error_message (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 885 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return error_message(id, args);
 }
std::vector< std::string > error_handler_base::error_message (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 892 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return error_message(id, args);
 }
std::vector< std::string > error_handler_base::error_message (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 901 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return error_message(id, args);
 }
std::vector< std::string > error_handler_base::error_message (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 911 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return error_message(id, args);
 }
std::vector< std::string > error_handler_base::error_message (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 922 of file error_handler.cpp.
References error_id.
 {
   return m_base_body->format_report(position, id, error_id, args);
 }
std::vector< std::string > error_handler_base::error_message (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 930 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return error_message(position, id, args);
 }
std::vector< std::string > error_handler_base::error_message (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 938 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return error_message(position, id, args);
 }
std::vector< std::string > error_handler_base::error_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 948 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return error_message(position, id, args);
 }
std::vector< std::string > error_handler_base::error_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 959 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return error_message(position, id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 974 of file error_handler.cpp.
 {
   return fatal_message(error_position(), id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 981 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return fatal_message(id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 988 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return fatal_message(id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 997 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return fatal_message(id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1007 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return fatal_message(id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1018 of file error_handler.cpp.
References fatal_id.
 {
   return m_base_body->format_report(position, id, fatal_id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1026 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return fatal_message(position, id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1034 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return fatal_message(position, id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1044 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return fatal_message(position, id, args);
 }
std::vector< std::string > error_handler_base::fatal_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1055 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return fatal_message(position, id, args);
 }
void error_handler_base::hide_position (void) throw ()
Definition at line 677 of file error_handler.cpp.
References m_base_body, and error_handler_base_body::set_show().
 {
   m_base_body->set_show(false);
 }
std::vector< std::string > error_handler_base::information_message (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 686 of file error_handler.cpp.
 {
   return information_message(error_position(), id, args);
 }
std::vector< std::string > error_handler_base::information_message (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 693 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return information_message(id, args);
 }
std::vector< std::string > error_handler_base::information_message (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 700 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return information_message(id, args);
 }
std::vector< std::string > error_handler_base::information_message (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 709 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return information_message(id, args);
 }
std::vector< std::string > error_handler_base::information_message (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 719 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return information_message(id, args);
 }
std::vector< std::string > error_handler_base::information_message (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 730 of file error_handler.cpp.
References information_id.
 {
   return m_base_body->format_report(position, id, information_id, args);
 }
std::vector< std::string > error_handler_base::information_message (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 738 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return information_message(position, id, args);
 }
std::vector< std::string > error_handler_base::information_message (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 746 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return information_message(position, id, args);
 }
std::vector< std::string > error_handler_base::information_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 756 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return information_message(position, id, args);
 }
std::vector< std::string > error_handler_base::information_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 767 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return information_message(position, id, args);
 }
void error_handler_base::pop_context (void) throw ()
Definition at line 1259 of file error_handler.cpp.
References error_handler_base_body::context_depth(), m_base_body, and error_handler_base_body::pop_context().
Referenced by error_context_body::pop().
 {
   m_base_body->pop_context(m_base_body->context_depth()-1);
 }
void error_handler_base::pop_context (unsigned depth) throw ()
Definition at line 1264 of file error_handler.cpp.
 {
   m_base_body->pop_context(depth);
 }
void error_handler_base::push_context (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1166 of file error_handler.cpp.
 {
   push_context(error_position(), id, args);
 }
void error_handler_base::push_context (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1173 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   push_context(id, args);
 }
void error_handler_base::push_context (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1180 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   push_context(id, args);
 }
void error_handler_base::push_context (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1189 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   push_context(id, args);
 }
void error_handler_base::push_context (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1199 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   push_context(id, args);
 }
void error_handler_base::push_context (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1210 of file error_handler.cpp.
 {
   m_base_body->push_context(position, id, args);
 }
void error_handler_base::push_context (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1218 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   push_context(position, id, args);
 }
void error_handler_base::push_context (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1226 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   push_context(position, id, args);
 }
void error_handler_base::push_context (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1236 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   push_context(position, id, args);
 }
void error_handler_base::push_context (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1247 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   push_context(position, id, args);
 }
void error_handler_base::push_supplement (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1070 of file error_handler.cpp.
 {
   push_supplement(error_position(), id, args);
 }
void error_handler_base::push_supplement (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1077 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   push_supplement(id, args);
 }
void error_handler_base::push_supplement (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1084 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   push_supplement(id, args);
 }
void error_handler_base::push_supplement (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1093 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   push_supplement(id, args);
 }
void error_handler_base::push_supplement (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1103 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   push_supplement(id, args);
 }
void error_handler_base::push_supplement (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1114 of file error_handler.cpp.
 {
   m_base_body->push_supplement(position, id, args);
 }
void error_handler_base::push_supplement (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1122 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   push_supplement(position, id, args);
 }
void error_handler_base::push_supplement (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1130 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   push_supplement(position, id, args);
 }
void error_handler_base::push_supplement (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1140 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   push_supplement(position, id, args);
 }
void error_handler_base::push_supplement (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1151 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   push_supplement(position, id, args);
 }
void error_handler_base::set_context_format (const std::string & format) throw ()
Definition at line 659 of file error_handler.cpp.
References context_id.
 {
   add_message(context_id, format);
 }
void error_handler_base::set_error_format (const std::string & format) throw ()
Definition at line 644 of file error_handler.cpp.
References error_id.
 {
   add_message(error_id, format);
 }
void error_handler_base::set_fatal_format (const std::string & format) throw ()
Definition at line 649 of file error_handler.cpp.
References fatal_id.
 {
   add_message(fatal_id, format);
 }
void error_handler_base::set_information_format (const std::string & format) throw ()
Definition at line 634 of file error_handler.cpp.
References information_id.
 {
   add_message(information_id, format);
 }
void error_handler_base::set_position_format (const std::string & format) throw ()
Definition at line 654 of file error_handler.cpp.
References position_id.
 {
   add_message(position_id, format);
 }
void error_handler_base::set_supplement_format (const std::string & format) throw ()
Definition at line 664 of file error_handler.cpp.
References supplement_id.
 {
   add_message(supplement_id, format);
 }
void error_handler_base::set_warning_format (const std::string & format) throw ()
Definition at line 639 of file error_handler.cpp.
References warning_id.
 {
   add_message(warning_id, format);
 }
void error_handler_base::show_position (void) throw ()
Definition at line 671 of file error_handler.cpp.
References m_base_body, and error_handler_base_body::set_show().
 {
   m_base_body->set_show(true);
 }
std::vector< std::string > error_handler_base::warning_message (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 782 of file error_handler.cpp.
 {
   return warning_message(error_position(), id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 789 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return warning_message(id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 796 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return warning_message(id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 805 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return warning_message(id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 815 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return warning_message(id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 826 of file error_handler.cpp.
References warning_id.
 {
   return m_base_body->format_report(position, id, warning_id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 834 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   return warning_message(position, id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 842 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   return warning_message(position, id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 852 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   return warning_message(position, id, args);
 }
std::vector< std::string > error_handler_base::warning_message (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 863 of file error_handler.cpp.
 {
   std::vector<std::string> args;
   args.push_back(arg1);
   args.push_back(arg2);
   args.push_back(arg3);
   return warning_message(position, id, args);
 }
Friends And Related Function Documentation
friend class error_handler_base_body friend
Definition at line 719 of file error_handler.hpp.
Member Data Documentation
smart_ptr_nocopy<error_handler_base_body> error_handler_base::m_base_body private
Definition at line 720 of file error_handler.hpp.
Referenced by context_depth(), hide_position(), pop_context(), and show_position().
The documentation for this class was generated from the following files:
include/stlplus/error_handler.hpp
include/stlplus/error_handler.cpp