Visible: iftext Class Reference
iftext Class Reference
#include <include/stlplus/fileio.hpp>
Public Member Functions
iftext (void)
iftext (FILE *handle)
iftext (const char *filename, size_t bufsize=preferred_buffer)
iftext (const std::string &filename, size_t bufsize=preferred_buffer)
void open (FILE *handle)
void open (const char *filename, size_t bufsize=preferred_buffer)
void open (const std::string &filename, size_t bufsize=preferred_buffer)
operator FILE * (void)
Public Member Functions inherited from itext
itext (void)
itext (ibuff *)
virtual ~itext (void)
bool initialised (void) const
void open (ibuff *)
void close (void)
itext (const itext &)
itext & operator= (const itext &)
bool error (void) const
int error_number (void) const
std::string error_string (void) const
void set_error (int error)
void clear_error (void)
void set_newline_mode (newline_t newline=convert_mode)
void set_convert_mode (void)
void set_binary_mode (void)
newline_t newline_mode (void) const
bool is_convert_mode (void)
bool is_binary_mode (void)
bool eof (void)
bool eoln (void)
int peek (void)
int get (void)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
bool good (void)
operator bool (void)
bool operator! (void)
itext & operator>> (char &)
itext & operator>> (signed char &)
itext & operator>> (unsigned char &)
itext & operator>> (std::string &)
bool getline (std::string &line)
itext & operator>> (std::vector< std::string > &)
itext & operator>> (bool &)
itext & operator>> (short &)
itext & operator>> (unsigned short &)
itext & operator>> (int &)
itext & operator>> (unsigned int &)
itext & operator>> (long &)
itext & operator>> (unsigned long &)
itext & operator>> (float &)
itext & operator>> (double &)
itext & operator>> (void *&)
itext & operator>> (manipulator_function)
itext & operator>> (otext &)
Static Public Attributes
static size_t preferred_buffer = 4096
Additional Inherited Members
Public Types inherited from itext
enum newline_t { binary_mode, convert_mode }
typedef void(* manipulator_function)(itext &)
Protected Attributes inherited from itext
ibuff * m_buffer
Detailed Description
Definition at line 64 of file fileio.hpp.
Constructor & Destructor Documentation
iftext::iftext (void)
Definition at line 259 of file fileio.cpp.
                    :
   itext()
 {
 }
iftext::iftext (FILE * handle)
Definition at line 264 of file fileio.cpp.
                        :
   itext(new ifbuff(fh))
 {
 }
iftext::iftext (const char * filename, size_t bufsize = preferred_buffer)
Definition at line 269 of file fileio.cpp.
                                                 :
   itext(new ifbuff(fname, bufsize))
 {
 }
iftext::iftext (const std::string & filename, size_t bufsize = preferred_buffer)
Definition at line 274 of file fileio.cpp.
                                                      :
   itext(new ifbuff(fname, bufsize))
 {
 }
Member Function Documentation
void iftext::open (FILE * handle)
Definition at line 279 of file fileio.cpp.
References itext::open().
 {
   itext::open(new ifbuff(fh));
 }
void iftext::open (const char * filename, size_t bufsize = preferred_buffer)
Definition at line 284 of file fileio.cpp.
References itext::open().
 {
   itext::open(new ifbuff(fname, bufsize));
 }
void iftext::open (const std::string & filename, size_t bufsize = preferred_buffer)
Definition at line 289 of file fileio.cpp.
References itext::open().
 {
   itext::open(new ifbuff(fname.c_str(), bufsize));
 }
iftext::operator FILE * (void)
Definition at line 294 of file fileio.cpp.
References ifbuff::m_handle.
 {
   ifbuff* filebuf = dynamic_cast<ifbuff*>(m_buffer);
   return filebuf ? filebuf->m_handle : 0;
 };
Member Data Documentation
size_t iftext::preferred_buffer = 4096 static
Definition at line 67 of file fileio.hpp.
The documentation for this class was generated from the following files:
include/stlplus/fileio.hpp
include/stlplus/fileio.cpp