Visible: rcPair< T > Class Template Reference
rcPair< T > Class Template Reference
#include <include/util/rc_pair.h>
Public Member Functions
rcPair ()
rcPair (T x, T y)
rcPair (T x)
const T & x () const
T & x ()
const T & y () const
T & y ()
rcPair< T > operator+ (const rcPair< T > &r) const
rcPair< T > & operator+= (const rcPair< T > &r)
rcPair< T > operator- () const
rcPair< T > operator- (const rcPair< T > &r) const
rcPair< T > & operator-= (const rcPair< T > &r)
rcPair< T > operator* (const rcPair< T > &r) const
rcPair< T > & operator*= (const rcPair< T > &r)
rcPair< T > operator/ (const rcPair< T > &r) const
rcPair< T > & operator/= (const rcPair< T > &r)
rcPair< T > operator/ (const T &r) const
rcPair< T > & operator/= (const T &r)
T & operator[] (int d)
T operator[] (int d) const
bool operator== (const rcPair< T > &r) const
bool operator!= (const rcPair< T > &r) const
Friends
ostream & operator<< (ostream &ous, const rcPair< T > &dis)
Detailed Description
template<class T>
class rcPair< T >
Definition at line 38 of file rc_pair.h.
Constructor & Destructor Documentation
template<class T> rcPair< T >::rcPair () inline
Definition at line 63 of file rc_pair.h.
 :  pair<T,T>() {}
template<class T> rcPair< T >::rcPair (T x, T y) inline
Definition at line 64 of file rc_pair.h.
 :  pair<T,T>(x, y) {}
template<class T> rcPair< T >::rcPair (T x) inline
Definition at line 65 of file rc_pair.h.
 :  pair<T,T>(x, x) {}
Member Function Documentation
template<class T> bool rcPair< T >::operator!= (const rcPair< T > & r) const inline
Definition at line 95 of file rc_pair.h.
 { return !(*this == r); }
template<class T> rcPair< T > rcPair< T >::operator* (const rcPair< T > & r) const
Definition at line 160 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return rcPair<T>(T(pair<T,T>::first * r.x()), T(pair<T,T>::second * r.y()));
 }
template<class T> rcPair< T > & rcPair< T >::operator*= (const rcPair< T > & r)
Definition at line 166 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   pair<T,T>::first *= r.x();
   pair<T,T>::second *= r.y();
   return *this;
 }
template<class T> rcPair< T > rcPair< T >::operator+ (const rcPair< T > & r) const
Definition at line 113 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return rcPair<T>(T(x() + r.x()), T(y() + r.y()));
 }
template<class T> rcPair< T > & rcPair< T >::operator+= (const rcPair< T > & r)
Definition at line 118 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   x() += r.x();
   y() += r.y();
   return *this;
 }
template<class T > rcPair< T > rcPair< T >::operator- () const
Definition at line 140 of file rc_pair.h.
 {
   return rcPair<T>(T(-pair<T,T>::first), T(-pair<T,T>::second));
 }
template<class T> rcPair< T > rcPair< T >::operator- (const rcPair< T > & r) const
Definition at line 146 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return rcPair<T>(T(pair<T,T>::first - r.x()), T(pair<T,T>::second - r.y()));
 }
template<class T> rcPair< T > & rcPair< T >::operator-= (const rcPair< T > & r)
Definition at line 152 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   pair<T,T>::first -= r.x();
   pair<T,T>::second -= r.y();
   return *this;
 }
template<class T> rcPair< T > rcPair< T >::operator/ (const rcPair< T > & r) const
Definition at line 174 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return rcPair<T>(T(pair<T,T>::first / r.x()), T(pair<T,T>::second / r.y()));
 }
template<class T> rcPair< T > rcPair< T >::operator/ (const T & r) const
Definition at line 188 of file rc_pair.h.
 {
   return rcPair<T>(T(pair<T,T>::first / r), T(pair<T,T>::second / r));
 }
template<class T> rcPair< T > & rcPair< T >::operator/= (const rcPair< T > & r)
Definition at line 180 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   pair<T,T>::first /= r.x();
   pair<T,T>::second /= r.y();
   return *this;
 }
template<class T> rcPair< T > & rcPair< T >::operator/= (const T & r)
Definition at line 194 of file rc_pair.h.
 {
   pair<T,T>::first /= r;
   pair<T,T>::second /= r;
   return *this;
 }
template<class T> bool rcPair< T >::operator== (const rcPair< T > & r) const
Definition at line 201 of file rc_pair.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return pair<T,T>::first == r.x() && pair<T,T>::second == r.y();
 }
template<class T > T & rcPair< T >::operator[] (int d)
Definition at line 126 of file rc_pair.h.
 {
   assert(d >= 0 && d < 2);
   return (!d) ? pair<T,T>::first : pair<T,T>::second;
 }
template<class T > T rcPair< T >::operator[] (int d) const
Definition at line 133 of file rc_pair.h.
 {
   assert(d >= 0 && d < 2);
   return (!d) ? pair<T,T>::first : pair<T,T>::second;
 }
template<class T> const T& rcPair< T >::x () const inline
Definition at line 69 of file rc_pair.h.
Referenced by rcMutualInfo::add(), rcMonitor::buildPositionCross(), rcMonitor::buildPositionPath(), rcKinetoscope::canonicalMotionField(), rcWindow::canPeekOutSide(), rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcWindow::CGImage(), rcKinetoscope::connectFunction(), rcRectangle< T >::contains(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcMuscleSegmenter::debugWrite(), rcVisualFunction::direct(), rcVisualFunction::dividingProcess(), rcImageCanvasGL::drawModelRect(), rcKinetoscope::epiMotionField(), rcAffineRectangle::expand(), rcMuscleSegmenter::filterAtEdge(), rcMuscleSegmenter::filterByAR(), rcImageCanvasGL::findCellPositionTracks(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcEngineImpl::focusScript(), rcKinetoscope::frame(), rcMonitor::gatherTrackData(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcDefGenerateImage::genImage(), rcPolygon::genMinEnclosingRect(), rcMuscleSegmenter::genPolygons(), rcPointCorrelation::genSpace(), genSpatialSDImg(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcAffineRectangle::getPixelLoc(), rcMonitor::getPosition(), rcImageCanvasGL::getToolTipText(), getTrackValue(), rcFeature::hasPolar(), rcDistanceTrackRenderInfo::init(), rcRectangle< T >::intersect(), rcAffineRectangle::isValid(), rcImageCanvasGL::keyPressEvent(), main(), rcShape::majorEndConstraints(), rcKinetoscope::maxRadialSpeed(), rcDbDtParams::maxSpeed(), rcWindow::maxTrim(), rcMotionVectorPath::measure(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcShape::needAffineRect(), rcShape::needMajorDimension(), rcShape::needMinorDimension(), rcFeature::octants(), rcPair< T >::operator*(), rcFeature::operator*(), rcPair< T >::operator*=(), rcPair< T >::operator+(), rc2dVector< T >::operator+(), rcPair< T >::operator+=(), rcPair< T >::operator-(), rc2dVector< T >::operator-(), rcPair< T >::operator-=(), rcPair< T >::operator/(), rcPair< T >::operator/=(), rcFeature::operator<(), operator<<(), rcPair< T >::operator==(), rcRectangle< T >::origin(), rcShape::orthogonalBoundingBoxCenter(), rcRectangle< T >::overlaps(), rcMotionVectorPath::parabolicDisparity(), rcShape::peakDetect1d(), rcFeature::polar(), rcFeature::pos(), rcVisualFunction::predictedTolerance(), rcExporter::produceValue(), rcShape::profiles(), rcDefGenerateImage::project(), rc2dVector< float >::rc2dVector(), rcAffineRectangle::rcAffineRectangle(), rcFeature::rcFeature(), rcMatrix< 2 >::rcMatrix(), rcMatrix_2d::rcMatrix_2d(), rcValue::rcValue(), rcVisualTarget::rcVisualTarget(), rcWindow::rcWindow(), rcMotionVectorPath::reconcile(), rcSpatialPyramid< 2 >::region(), rf2key(), rfComponentPolygons(), rfDrawLine(), rfGetRects(), rfImageACfield(), rfImageVerticalReflect(), rfkey2xy(), rfPlot1Dsignal(), rfRegisteredWindows(), rfRoundRectangle(), rcVisualFunction::roundRectangle(), rcImageCanvasGL::select(), rcKinetoscope::selfSimilarMotionField(), rcKinetoscope::selfSimilarMotionField_AttentiveCapture(), rcWindow::setDoublePixel(), rcPositionTrackImpl::setMinMaxValues(), rcWindow::setPixel(), rcRect::setX(), rcRectangle< T >::size(), rcEngineImpl::start(), rcRectangle< T >::translate(), rcWindow::translate(), rcWindow::trim(), rcLatticeSimilarator::ttc(), rcLatticeSimilarator::update(), rcVisualTarget::update(), rcVisualFunction::updateRects(), rcVisualFunction::updateSims(), rcScalarTrackWidget::updateTrackDisplay(), rcDbDtParams::validate(), rcKinetoscope::visualDebugGraphics(), rcKinetoscope::visualFunctionHistory(), rcKinetoscope::visualFunctionMap(), withinPreSegmentedBodies(), rcCellWriterGroup::writeValues(), and rcRect::x().
 {return pair<T,T>::first;}
template<class T> T& rcPair< T >::x () inline
Definition at line 70 of file rc_pair.h.
 {return pair<T,T>::first;}
template<class T> const T& rcPair< T >::y () const inline
Definition at line 72 of file rc_pair.h.
Referenced by rcMutualInfo::add(), rcMonitor::buildPositionCross(), rcMonitor::buildPositionPath(), rcKinetoscope::canonicalMotionField(), rcWindow::canPeekOutSide(), rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcWindow::CGImage(), rcKinetoscope::connectFunction(), rcRectangle< T >::contains(), copyImage(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcMuscleSegmenter::debugWrite(), rcVisualFunction::direct(), rcVisualFunction::dividingProcess(), rcKinetoscope::epiMotionField(), rcAffineRectangle::expand(), rcMuscleSegmenter::filterAtEdge(), rcMuscleSegmenter::filterByAR(), rcImageCanvasGL::findCellPositionTracks(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcEngineImpl::focusScript(), rcKinetoscope::frame(), rcMonitor::gatherTrackData(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcDefGenerateImage::genImage(), rcPolygon::genMinEnclosingRect(), rcMuscleSegmenter::genPolygons(), rcPointCorrelation::genSpace(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcAffineRectangle::getPixelLoc(), rcMonitor::getPosition(), rcImageCanvasGL::getToolTipText(), getTrackValue(), rcFeature::hasPolar(), rcRectangle< T >::intersect(), rcAffineRectangle::isValid(), rcImageCanvasGL::keyPressEvent(), main(), rcShape::majorEndConstraints(), rcWindow::maxTrim(), rcMotionVectorPath::measure(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcShape::needAffineRect(), rcShape::needMajorDimension(), rcShape::needMinorDimension(), rcFeature::octants(), rcPair< T >::operator*(), rcFeature::operator*(), rcPair< T >::operator*=(), rcPair< T >::operator+(), rc2dVector< T >::operator+(), rcPair< T >::operator+=(), rcPair< T >::operator-(), rc2dVector< T >::operator-(), rcPair< T >::operator-=(), rcPair< T >::operator/(), rcPair< T >::operator/=(), rcFeature::operator<(), rcPair< T >::operator==(), rcRectangle< T >::origin(), rcShape::orthogonalBoundingBoxCenter(), rcRectangle< T >::overlaps(), rcMotionVectorPath::parabolicDisparity(), rcShape::peakDetect1d(), rcFeature::polar(), rcFeature::pos(), rcVisualFunction::predictedTolerance(), rcExporter::produceValue(), rcShape::profiles(), rcDefGenerateImage::project(), rc2dVector< float >::rc2dVector(), rcAffineRectangle::rcAffineRectangle(), rcFeature::rcFeature(), rcMatrix< 2 >::rcMatrix(), rcMatrix_2d::rcMatrix_2d(), rcValue::rcValue(), rcVisualTarget::rcVisualTarget(), rcWindow::rcWindow(), rcMotionVectorPath::reconcile(), rcSpatialPyramid< 2 >::region(), rf2key(), rfComponentPolygons(), rfDrawLine(), rfGetRects(), rfImageACfield(), rfImageVerticalReflect(), rfkey2xy(), rfPlot1Dsignal(), rfRegisteredWindows(), rfRoundRectangle(), rcVisualFunction::roundRectangle(), rcImageCanvasGL::select(), rcKinetoscope::selfSimilarMotionField(), rcKinetoscope::selfSimilarMotionField_AttentiveCapture(), rcWindow::setDoublePixel(), rcPositionTrackImpl::setMinMaxValues(), rcWindow::setPixel(), rcRect::setY(), rcRectangle< T >::size(), rcEngineImpl::start(), rcRectangle< T >::translate(), rcWindow::translate(), rcWindow::trim(), rcLatticeSimilarator::ttc(), rcLatticeSimilarator::update(), rcVisualTarget::update(), rcVisualFunction::updateRects(), rcVisualFunction::updateSims(), rcScalarTrackWidget::updateTrackDisplay(), rcDbDtParams::validate(), rcKinetoscope::visualDebugGraphics(), rcKinetoscope::visualFunctionHistory(), rcKinetoscope::visualFunctionMap(), withinPreSegmentedBodies(), rcCellWriterGroup::writeValues(), and rcRect::y().
 {return pair<T,T>::second;}
template<class T> T& rcPair< T >::y () inline
Definition at line 73 of file rc_pair.h.
 {return pair<T,T>::second;}
Friends And Related Function Documentation
template<class T> ostream& operator<< (ostream & ous, const rcPair< T > & dis) friend
Definition at line 97 of file rc_pair.h.
   {
     ous << dis.x() << "," << dis.y();
     return ous;
   }
The documentation for this class was generated from the following file:
include/util/rc_pair.h