Visible: rcLineSegment< T > Class Template Reference
rcLineSegment< T > Class Template Reference
#include <include/util/rc_line.h>
Public Member Functions
rcLineSegment ()
rcLineSegment (const rcRadian &angle, const T distance)
rcLineSegment (const rcRadian &angle, const rc2dVector< T > &pb)
rcLineSegment (const rc2dVector< T > &pa, const rc2dVector< T > &pb)
T distanceFrom (const rc2dVector< T > &point) const
T distanceAlong (const rc2dVector< T > &point) const
vector< rc2dVector< T > > intersection (const rcLineSegment< T > &line) const
rc2dVector< T > closestPoint (const rc2dVector< T > &point) const
const rcRadian & angle () const
T distance () const
T Sin () const
T Cos () const
bool operator== (const rcLineSegment< T > &ls) const
bool operator!= (const rcLineSegment< T > &ls) const
Private Attributes
rcRadian mAngle
T mSin
T mCos
T mDist
Detailed Description
template<class T>
class rcLineSegment< T >
Definition at line 49 of file rc_line.h.
Constructor & Destructor Documentation
template<class T> rcLineSegment< T >::rcLineSegment () inline
Definition at line 52 of file rc_line.h.
                    :
mAngle (rcRadian (0.0)), mSin (T (0)), mCos (T (1.0)), mDist (T (0)) {}
template<class T> rcLineSegment< T >::rcLineSegment (const rcRadian & angle, const T distance) inline
Definition at line 55 of file rc_line.h.
References rcLineSegment< T >::distance(), rcLineSegment< T >::mDist, and rmAssert.
                                                           :
   mAngle (angle), mSin (sin (angle)),  mCos (cos (angle))
   {
     rmAssert (distance >= T (0));
     mDist = distance;
}
template<class T > rcLineSegment< T >::rcLineSegment (const rcRadian & angle, const rc2dVector< T > & pb)
Definition at line 122 of file rc_line.h.
References cos(), rkPI, sin(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   mAngle = angle;
   T sn = sin (- mAngle);
   T cs = cos (- mAngle);
   rc2dVector<T> p (cs*pa.x()-sn*pa.y(),sn*pa.x()+cs*pa.y());
   mDist = p.y();
   if (mDist < 0)
     {
       mDist = - mDist;
       mAngle = rcRadian (rkPI) + mAngle;
     }
   mSin = sin(mAngle);
   mCos = cos(mAngle);
 }
template<class T > rcLineSegment< T >::rcLineSegment (const rc2dVector< T > & pa, const rc2dVector< T > & pb)
Definition at line 102 of file rc_line.h.
References cos(), rkPI, sin(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   if (pa == pb)
     throw general_exception ("Degenerate Line");
   mAngle = (pa - pb).angle();
   T sn = sin (- mAngle);
   T cs = cos (- mAngle);
   rc2dVector<T> p (cs*pa.x()-sn*pa.y(),sn*pa.x()+cs*pa.y());
   mDist = p.y();
   if (mDist < 0)
     {
       mDist = - mDist;
       mAngle = rcRadian (rkPI) + mAngle;
     }
   mSin = sin(mAngle);
   mCos = cos(mAngle);
 }
Member Function Documentation
template<class T> const rcRadian& rcLineSegment< T >::angle () const inline
Definition at line 76 of file rc_line.h.
References rcLineSegment< T >::mAngle.
Referenced by rcVisualFunction::beatProcess(), rcLsFit< T >::error(), and rcOptoKineticImage::genLogRMS().
 { return mAngle; }
template<class T > rc2dVector< T > rcLineSegment< T >::closestPoint (const rc2dVector< T > & point) const
Definition at line 141 of file rc_line.h.
References rkPI, and rmAssert.
 {
   // This is the easy, not necessarily the efficient, thing to do:
   vector<rc2dVector<T> > intersecting = intersection(rcLineSegment<T>(angle()+
                                       rcRadian(rkPI/2),
                                       point));
   rmAssert(intersecting.size() == 1);
   return intersecting[0];
 }
template<class T> T rcLineSegment< T >::Cos () const inline
Definition at line 80 of file rc_line.h.
References rcLineSegment< T >::mCos.
 { return mCos; }
template<class T> T rcLineSegment< T >::distance () const inline
Definition at line 78 of file rc_line.h.
References rcLineSegment< T >::mDist.
Referenced by rcLsFit< T >::error(), and rcLineSegment< T >::rcLineSegment().
 { return mDist; }
template<class T> T rcLineSegment< T >::distanceAlong (const rc2dVector< T > & point) const inline
Definition at line 69 of file rc_line.h.
References rcLineSegment< T >::mCos, rcLineSegment< T >::mSin, rc2dVector< T >::x(), and rc2dVector< T >::y().
   { return (point.x() * mCos + point.y() * mSin); }
template<class T> T rcLineSegment< T >::distanceFrom (const rc2dVector< T > & point) const inline
Definition at line 66 of file rc_line.h.
References rcLineSegment< T >::mCos, rcLineSegment< T >::mDist, rcLineSegment< T >::mSin, rc2dVector< T >::x(), and rc2dVector< T >::y().
   { return (point.x() * mSin - point.y() * mCos + mDist); }
template<class T > vector< rc2dVector< T > > rcLineSegment< T >::intersection (const rcLineSegment< T > & line) const
Definition at line 157 of file rc_line.h.
References rcLineSegment< T >::mCos, rcLineSegment< T >::mDist, and rcLineSegment< T >::mSin.
 {
   vector<rc2dVector<T> > pts;
   double denom = line.mCos * mSin - mCos * line.mSin;
   if(denom == 0.0)
     return pts;
   pts.push_back((rc2dVector<T> (mCos,mSin)* line.mDist -
          rc2dVector<T> (line.mCos,line.mSin) * mDist)/denom);
   return pts;
 }
template<class T > bool rcLineSegment< T >::operator!= (const rcLineSegment< T > & ls) const
Definition at line 97 of file rc_line.h.
      { return !(*this == ls); }
template<class T > bool rcLineSegment< T >::operator== (const rcLineSegment< T > & ls) const
Definition at line 93 of file rc_line.h.
References rcLineSegment< T >::mAngle, rcLineSegment< T >::mCos, rcLineSegment< T >::mDist, and rcLineSegment< T >::mSin.
       { return mSin == ls.mSin && mCos == ls.mCos && mDist == ls.mDist && mAngle == ls.mAngle; }
template<class T> T rcLineSegment< T >::Sin () const inline
Definition at line 79 of file rc_line.h.
References rcLineSegment< T >::mSin.
 { return mSin; }
Member Data Documentation
template<class T> rcRadian rcLineSegment< T >::mAngle private
Definition at line 87 of file rc_line.h.
Referenced by rcLineSegment< T >::angle(), and rcLineSegment< T >::operator==().
template<class T> T rcLineSegment< T >::mCos private
Definition at line 88 of file rc_line.h.
Referenced by rcLineSegment< T >::Cos(), rcLineSegment< T >::distanceAlong(), rcLineSegment< T >::distanceFrom(), rcLineSegment< T >::intersection(), and rcLineSegment< T >::operator==().
template<class T> T rcLineSegment< T >::mDist private
Definition at line 88 of file rc_line.h.
Referenced by rcLineSegment< T >::distance(), rcLineSegment< T >::distanceFrom(), rcLineSegment< T >::intersection(), rcLineSegment< T >::operator==(), and rcLineSegment< T >::rcLineSegment().
template<class T> T rcLineSegment< T >::mSin private
Definition at line 88 of file rc_line.h.
Referenced by rcLineSegment< T >::distanceAlong(), rcLineSegment< T >::distanceFrom(), rcLineSegment< T >::intersection(), rcLineSegment< T >::operator==(), and rcLineSegment< T >::Sin().
The documentation for this class was generated from the following file:
include/util/rc_line.h