Visible: rcTrackPanel Class Reference
rcTrackPanel Class Reference
#include <include/visUI/rc_trackpanel.h>
Public Slots
void updateState (rcExperimentState state)
void updateCamera (bool live, bool storage)
void updateSource (int source)
void updateTrackGroups ()
Public Member Functions
rcTrackPanel (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
~rcTrackPanel ()
Private Member Functions
void updateTrackGroups (bool cameraInput, bool cameraStorage)
Private Attributes
QWidget * mContents
rcExperimentState mOldState
int mManagedGroups
bool mLiveInput
bool mLiveStorage
Detailed Description
Definition at line 14 of file rc_trackpanel.h.
Constructor & Destructor Documentation
rcTrackPanel::rcTrackPanel (QWidget * parent = 0, const char * name = 0, Qt::WFlags f = 0)
Definition at line 15 of file rc_trackpanel.cpp.
References eExperimentEmpty, rcModelDomain::getModelDomain(), rcUNUSED, updateCamera(), updateSource(), updateState(), and updateTrackGroups().
         : Q3ScrollView( parent, name ), mContents( 0 ), mOldState(eExperimentEmpty),
           mManagedGroups( 0 ), mLiveInput( false ), mLiveStorage( false )
 {
     rcUNUSED( f );
     setMinimumWidth( 250 );
     setMaximumWidth( 300 );
     setVScrollBarMode( AlwaysOn );
     setHScrollBarMode( AlwaysOff );
     setResizePolicy( Q3ScrollView::AutoOneFit );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateInputSource( int ) ) ,
              this   , SLOT( updateSource( int ) ) );
     connect( domain , SIGNAL( updateCameraState( bool, bool ) ) ,
              this   , SLOT( updateCamera( bool, bool ) ) );
     connect( domain , SIGNAL( updateDebugging() ) ,
              this   , SLOT( updateTrackGroups() ) );
     updateState( eExperimentEmpty );
 }
rcTrackPanel::~rcTrackPanel ()
Definition at line 43 of file rc_trackpanel.cpp.
 {
     // Qt will delete children widgets automatically
 }
Member Function Documentation
void rcTrackPanel::updateCamera (bool live, bool storage) slot
Definition at line 48 of file rc_trackpanel.cpp.
References endl(), rmUnused, and updateTrackGroups().
Referenced by rcTrackPanel().
 {
 #ifdef DEBUG_LOG
     cerr << "rcTrackPanel::updateCamera " << live << " " << storage << endl;
 #endif
     // Camera state has changed, preview vs. storage
     rmUnused( storage );
     updateTrackGroups( live, storage );
 }
void rcTrackPanel::updateSource (int source) slot
Definition at line 81 of file rc_trackpanel.cpp.
References endl(), mContents, mLiveInput, mLiveStorage, mManagedGroups, and updateTrackGroups().
Referenced by rcTrackPanel().
 {
 #ifdef DEBUG_LOG
     cerr << "rcTrackPanel::updateSource " << source << " " << mManagedGroups << endl;
 #endif
     // when the state of the experiment changes, the
     // track group list needs to be recomputed.
     if ( source > 0 ) {
         // Ignore redundant calls if we have a track list already
         if ( mLiveInput && mContents && mManagedGroups )
             return;
         mLiveInput = true;
         mLiveStorage = false;
     } else {
         if ( !mLiveInput )
             return;
         mLiveInput = false;
         mLiveStorage = false;
     }
     updateTrackGroups( mLiveInput, mLiveStorage );
 }
void rcTrackPanel::updateState (rcExperimentState state) slot
Definition at line 59 of file rc_trackpanel.cpp.
References eExperimentEnded, eExperimentPlayback, endl(), mLiveInput, mLiveStorage, mOldState, and updateTrackGroups().
Referenced by rcTrackPanel().
 {
 #ifdef DEBUG_LOG
     cerr << "rcTrackPanel::updateState " << state << endl;
 #endif
     // Ignore video playback states
     if ( state == eExperimentPlayback ||
          (mOldState == eExperimentPlayback && state == eExperimentEnded)) {
         mOldState = state;
         return;
     }
     mOldState = state;
     // when the state of the experiment changes, the
     // track group list needs to be recomputed.
     if ( mLiveStorage && state == eExperimentEnded )
         mLiveStorage = false;
     updateTrackGroups( mLiveInput, mLiveStorage );
 }
void rcTrackPanel::updateTrackGroups () slot
Definition at line 105 of file rc_trackpanel.cpp.
References mLiveInput, and mLiveStorage.
Referenced by rcTrackPanel(), updateCamera(), updateSource(), and updateState().
 {
     updateTrackGroups( mLiveInput, mLiveStorage );
 }
void rcTrackPanel::updateTrackGroups (bool cameraInput, bool cameraStorage) private
Definition at line 111 of file rc_trackpanel.cpp.
References endl(), rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getNTrackGroups(), rcTrackManager::hasManageableTracks(), mContents, mLiveInput, mLiveStorage, and mManagedGroups.
 {
     mLiveInput = cameraInput;
     mLiveStorage = cameraStorage;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     int nTrackGroups = experiment->getNTrackGroups();
     // TODO: implement a redundancy check, sometimes all the new widgets will be
     // identical to the old widgets so there is no need to recreate them.
     // remove any existing track widgets.
     if ( mContents != 0 )
     {
         // this will automatically remove the contents from the scroll
         //  view - thanks Qt!
         removeChild( mContents );
         delete mContents;
         mContents = 0;
     }
     if ( nTrackGroups == 0 )
     {
         hide();
         return;
     }
     // Add new groups
     Q3VBox* vBox = new Q3VBox( viewport() );
     addChild( vBox );
     mContents = vBox;
     mManagedGroups = 0;
     for (int i = 0; i < nTrackGroups; i++)
     {
         if ( rcTrackManager::hasManageableTracks( i, cameraInput, cameraStorage ) ) {
             // Create a widget only for groups that have manageable tracks
             new rcTrackGroupWidget( vBox , i );
             ++mManagedGroups;
         }
     }
     if ( mManagedGroups ) {
         show();
         vBox->show();
     } else {
         hide();
 #ifdef DEBUG_LOG
         if ( cameraInput )
             if ( cameraStorage )
                 cerr << "rcTrackPanel::updateTrackGroups: camera enabled but no storage track(s) found" << endl;
             else
                 cerr << "rcTrackPanel::updateTrackGroups: camera enabled but no preview track(s) found" << endl;
 #endif
     }
 }
Member Data Documentation
QWidget* rcTrackPanel::mContents private
Definition at line 36 of file rc_trackpanel.h.
Referenced by updateSource(), and updateTrackGroups().
bool rcTrackPanel::mLiveInput private
Definition at line 39 of file rc_trackpanel.h.
Referenced by updateSource(), updateState(), and updateTrackGroups().
bool rcTrackPanel::mLiveStorage private
Definition at line 40 of file rc_trackpanel.h.
Referenced by updateSource(), updateState(), and updateTrackGroups().
int rcTrackPanel::mManagedGroups private
Definition at line 38 of file rc_trackpanel.h.
Referenced by updateSource(), and updateTrackGroups().
rcExperimentState rcTrackPanel::mOldState private
Definition at line 37 of file rc_trackpanel.h.
Referenced by updateState().
The documentation for this class was generated from the following files:
include/visUI/rc_trackpanel.h
src/visible/qt/rc_trackpanel.cpp