Visible: rcStyle Class Reference
rcStyle Class Reference
#include <include/visual/rc_style.h>
Public Member Functions
rcStyle ()
rcStyle (uint32 color)
rcStyle (uint32 color, uint32 lineWidth)
rcStyle (uint32 color, uint32 lineWidth, const rc2Fvector &origin)
uint32 color () const
uint32 lineWidth () const
rc2Fvector pixelOrigin () const
void color (uint32 color)
void lineWidth (uint32 lineWidth)
void pixelOrigin (rc2Fvector origin)
bool operator== (const rcStyle &v) const
bool operator!= (const rcStyle &v) const
Protected Attributes
uint32 mColor
uint32 mLineWidth
rc2Fvector mPixelOrigin
Detailed Description
Definition at line 16 of file rc_style.h.
Constructor & Destructor Documentation
rcStyle::rcStyle ()
Definition at line 19 of file rc_style.cpp.
                  :
         mColor( rfRgb( 255, 0, 0 ) ), mLineWidth( 1 ), mPixelOrigin( 0.0f, 0.0f )
 {
}
rcStyle::rcStyle (uint32 color)
Definition at line 24 of file rc_style.cpp.
                                :
         mColor( color ), mLineWidth( 1 ), mPixelOrigin( 0.0f, 0.0f )
 {
}
rcStyle::rcStyle (uint32 color, uint32 lineWidth)
Definition at line 29 of file rc_style.cpp.
                                                  :
         mColor( color ), mLineWidth( lineWidth ), mPixelOrigin( 0.0f, 0.0f )
 {
}
rcStyle::rcStyle (uint32 color, uint32 lineWidth, const rc2Fvector & origin)
Definition at line 34 of file rc_style.cpp.
                                                                            :
         mColor( color ), mLineWidth( lineWidth ), mPixelOrigin( origin )
 {
}
Member Function Documentation
uint32 rcStyle::color () const inline
Definition at line 25 of file rc_style.h.
References mColor.
Referenced by rcImageCanvasGL::addDefaultText(), rcImageCanvasGL::draw(), operator==(), and rcImageCanvasGL::setStyle().
 { return mColor; };
void rcStyle::color (uint32 color) inline
Definition at line 30 of file rc_style.h.
References color(), and mColor.
Referenced by color().
 { mColor = color; };
uint32 rcStyle::lineWidth () const inline
Definition at line 26 of file rc_style.h.
References mLineWidth.
Referenced by rcImageCanvasGL::draw(), operator==(), and rcImageCanvasGL::setStyle().
 { return mLineWidth; };
void rcStyle::lineWidth (uint32 lineWidth) inline
Definition at line 31 of file rc_style.h.
References lineWidth(), and mLineWidth.
Referenced by lineWidth().
 { mLineWidth = lineWidth; };
bool rcStyle::operator!= (const rcStyle & v) const inline
Definition at line 37 of file rc_style.h.
 { return !(*this == v); }
bool rcStyle::operator== (const rcStyle & v) const inline
Definition at line 35 of file rc_style.h.
References color(), lineWidth(), mColor, mLineWidth, mPixelOrigin, and pixelOrigin().
         { return (mColor == v.color() && mLineWidth == v.lineWidth() && mPixelOrigin == v.pixelOrigin()); }
rc2Fvector rcStyle::pixelOrigin () const inline
Definition at line 27 of file rc_style.h.
References mPixelOrigin.
Referenced by rcImageCanvasGL::draw(), and operator==().
 { return mPixelOrigin; };
void rcStyle::pixelOrigin (rc2Fvector origin) inline
Definition at line 32 of file rc_style.h.
References mPixelOrigin.
 { mPixelOrigin = origin; };
Member Data Documentation
uint32 rcStyle::mColor protected
Definition at line 42 of file rc_style.h.
Referenced by color(), and operator==().
uint32 rcStyle::mLineWidth protected
Definition at line 43 of file rc_style.h.
Referenced by lineWidth(), and operator==().
rc2Fvector rcStyle::mPixelOrigin protected
Definition at line 44 of file rc_style.h.
Referenced by operator==(), and pixelOrigin().
The documentation for this class was generated from the following files:
include/visual/rc_style.h
src/visual/code/rc_style.cpp