Visible: rcAffineRectangle Class Reference
rcAffineRectangle Class Reference
#include <include/visual/rc_affine.h>
Public Member Functions
rcAffineRectangle ()
default constructor takes no arguments
rcAffineRectangle (const rc2Dvector &org, const rcRadian &angle, const rcDPair &scale, const rcIPair &imgSz, const rcDPair &affineOrigin=rcDPair(0.5, 0.5))
constructor making an affine rectangle at org oriented angle
rcAffineRectangle (const rc2Dvector &anch, const rc2Dvector &endpoint, const double &otherDimension, const rcDPair &affineOrigin=rcDPair(0.5, 0.5))
constructor taking endpoints and otherDimension
bool isValid () const
const rc2Dvector & origin () const
rcRadian angle () const
rcDPair xyScale () const
const rcIPair & cannonicalSize () const
bool cannonicalXsizeIsGreater () const
rcRect boundingBox () const
rc2Dvector imageToAffine (const rc2Dvector &pt) const
rc2Fvector imageToAffine (const rc2Fvector &pt) const
rc2Dvector affineToImage (const rc2Dvector &pt) const
rc2Fvector affineToImage (const rc2Fvector &pt) const
rc2Dvector getPixelLoc (int32 x, int32 y) const
rc2Dvector getPixelLoc (double x, double y) const
rcAffineRectangle expand (const rcIPair &steps) const
bool operator== (const rcAffineRectangle &aRect) const
bool operator!= (const rcAffineRectangle &aRect) const
Public Member Functions inherited from rc2Xform
rc2Xform ()
rc2Xform (const rcMatrix_2d &c, const rc2Dvector &t)
rc2Xform (const rcMatrix_2d &c, const rc2Fvector &t)
const rcMatrix_2d & matrix () const
const rc2Dvector & trans () const
const rc2Fvector transf () const
void matrix (const rcMatrix_2d &c)
void trans (const rc2Dvector &t)
void trans (const rc2Fvector &t)
rc2Xform inverse () const
rc2Xform operator* (const rc2Xform &xform) const
rc2Xform compose (const rc2Xform &xform) const
double xRot () const
double yRot () const
double xScale () const
double yScale () const
double scale () const
double aspect () const
double shear () const
rcRadian rotation () const
double mapAngle (const double &ang) const
double invMapAngle (const double &ang) const
rc2Dvector mapPoint (const rc2Dvector &pt) const
rc2Fvector mapPoint (const rc2Fvector &pt) const
rc2Dvector operator* (const rc2Dvector &pt) const
rc2Fvector operator* (const rc2Fvector &pt) const
rc2Dvector invMapPoint (const rc2Dvector &pt) const
rc2Fvector invMapPoint (const rc2Fvector &pt) const
rc2Dvector mapVector (const rc2Dvector &vect) const
rc2Dvector invMapVector (const rc2Dvector &vect) const
double mapArea (double area) const
double invMapArea (double area) const
bool operator== (const rc2Xform &xform) const
bool operator!= (const rc2Xform &xform) const
bool operator< (const rc2Xform &) const
bool isIdentity () const
bool isSingular () const
Private Attributes
rc2Dvector mStep
rcIPair mImgSz
rc2Dvector mOrg
Friends
ostream & operator<< (ostream &ous, const rcAffineRectangle &dis)
Additional Inherited Members
Static Public Attributes inherited from rc2Xform
static const rc2Xform I
Detailed Description
Definition at line 121 of file rc_affine.h.
Constructor & Destructor Documentation
rcAffineRectangle::rcAffineRectangle ()
default constructor takes no arguments
Definition at line 65 of file rc_affine.cpp.
References mImgSz, rcPair< T >::x(), and rcPair< T >::y().
Referenced by expand().
 {
   // Negative Size is a No No
   mImgSz.x() =   mImgSz.y() = -1;
 }
rcAffineRectangle::rcAffineRectangle (const rc2Dvector & org, const rcRadian & angle, const rcDPair & scale, const rcIPair & imgSz, const rcDPair & affineOrigin = rcDPair(0.5, 0.5))
constructor making an affine rectangle at org oriented angle
org defines the translation of the affine relative to the image plane, in image coordinates. affineOrigin defines the point to use as the origin of the affine rectangle itself, and is in affine coordinates.
Definition at line 94 of file rc_affine.cpp.
References affineToImage(), mImgSz, mOrg, mStep, rmAssert, rc2Xform::trans(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
   : rc2Xform(rcMatrix_2d(ang, scale), org), mImgSz(imgSz)
 {
   rmAssert(mImgSz.x() > 0);
   rmAssert(mImgSz.y() > 0);
   mStep = rc2Dvector(1./mImgSz.x(), 1./mImgSz.y());
   mOrg.x(affineOrigin.x() == 0.0 ? 0.0 : -affineOrigin.x());
   mOrg.y(affineOrigin.y() == 0.0 ? 0.0 : -affineOrigin.y());
   if ((mOrg.x() != 0.0) || (mOrg.y() != 0.0))
     trans(affineToImage(mOrg));
 }
rcAffineRectangle::rcAffineRectangle (const rc2Dvector & anch, const rc2Dvector & endpoint, const double & otherDimension, const rcDPair & affineOrigin = rcDPair(0.5, 0.5))
constructor taking endpoints and otherDimension
Definition at line 72 of file rc_affine.cpp.
References affineToImage(), angle(), rc2dVector< T >::distance(), rc2Xform::matrix(), mImgSz, mOrg, mStep, rmAssert, rc2Xform::scale(), rc2Xform::trans(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
   // set angle to angle connecting anchor to end point
   // angle (positive x to positive y
   rcRadian angle = (ep - anch).angle();
   rcDPair scale (anch.distance (ep), otherDimension);
   mImgSz = rcIPair ((int32) scale.x(), (int32) scale.y());
   rmAssert(mImgSz.x() > 0);
   rmAssert(mImgSz.y() > 0);
   mStep = rc2Dvector(1./mImgSz.x(), 1./mImgSz.y());
   matrix (rcMatrix_2d (angle, scale));
   trans (anch);
   mOrg.x(affineOrigin.x() == 0.0 ? 0.0 : -affineOrigin.x());
   mOrg.y(affineOrigin.y() == 0.0 ? 0.0 : -affineOrigin.y());
   if ((mOrg.x() != 0.0) || (mOrg.y() != 0.0))
     trans(affineToImage(mOrg));
 }
Member Function Documentation
rc2Dvector rcAffineRectangle::affineToImage (const rc2Dvector & pt) const inline
Definition at line 186 of file rc_affine.h.
References rc2Xform::mapPoint().
Referenced by boundingBox(), getPixelLoc(), rcEngineImpl::muscleTracker(), rcShape::needCenterOfmass(), rcShape::needMedian(), rcAffineRectangle(), rcDrawAffineRectangle(), rcPolygon::rcPolygon(), rfAffineRectangleToSegmentsCollection(), rfPlot1Dsignal(), rcAffineWindow::vImageTransform(), rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
   { return mapPoint(pt); }
rc2Fvector rcAffineRectangle::affineToImage (const rc2Fvector & pt) const inline
Definition at line 189 of file rc_affine.h.
References rc2Xform::mapPoint().
   { return mapPoint(pt); }
rcRadian rcAffineRectangle::angle () const inline
Definition at line 155 of file rc_affine.h.
References rc2Xform::rotation().
Referenced by rcShape::angle(), expand(), rcAffineRectangle(), and rcValue::rcValue().
   { return rotation(); }
rcRect rcAffineRectangle::boundingBox () const
Definition at line 111 of file rc_affine.cpp.
References affineToImage(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcCubicGeneratePixel::genPixel(), rcShape::orthogonalBoundingBox(), and rcAffineWindow::rcAffineWindow().
 {
   double minX, minY, maxX, maxY;
   const rc2Dvector four[4] = { affineToImage(rc2Dvector(0.0, 0.0)),
                    affineToImage(rc2Dvector(0.0, 1.0)),
                    affineToImage(rc2Dvector(1.0, 0.0)),
                    affineToImage(rc2Dvector(1.0, 1.0)) };
   minX = maxX = four[0].x();
   minY = maxY = four[0].y();
   for (uint32 i = 1; i < 4; i++) {
     if (four[i].x() > maxX)
       maxX = four[i].x();
     if (four[i].x() < minX)
       minX = four[i].x();
     if (four[i].y() > maxY)
       maxY = four[i].y();
     if (four[i].y() < minY)
       minY = four[i].y();
   }
   int32 xo = int32(floor(minX)), yo = int32(floor(minY));
   int32 aMaxX = (int32)ceil(maxX) + 1, aMaxY = (int32)ceil(maxY) + 1;
   int32 w = aMaxX - xo, h = aMaxY - yo;
   return rcRect (xo, yo, w, h);
 }
const rcIPair& rcAffineRectangle::cannonicalSize () const inline
Definition at line 161 of file rc_affine.h.
References mImgSz.
Referenced by cannonicalXsizeIsGreater(), rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), expand(), rcMuscleSegmenter::filterByAR(), rcAffineWindow::getImageSz(), rcEngineImpl::muscleTracker(), rcShape::needAffineRect(), rcShape::profiles(), rcDefGenerateImage::project(), rcValue::rcValue(), rfPlot1Dsignal(), rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
   { return mImgSz; }
bool rcAffineRectangle::cannonicalXsizeIsGreater () const inline
Definition at line 164 of file rc_affine.h.
References cannonicalSize().
   {
     return (cannonicalSize().x() >= cannonicalSize().y());
   }
rcAffineRectangle rcAffineRectangle::expand (const rcIPair & steps) const
Definition at line 160 of file rc_affine.cpp.
References angle(), cannonicalSize(), rc2Xform::mapPoint(), mOrg, rcAffineRectangle(), rmAssert, rc2Xform::scale(), rcPair< T >::x(), rc2dVector< T >::x(), xyScale(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by rcShape::needAffineRect().
 {
   // Get the center in image coordiantes
   // Assumption currently about the origin in this code
   // TBD: fix
   rmAssert (mOrg.x() == 0 && mOrg.y() == 0);
   rcDPair half (0.5, 0.5);
   rc2Dvector ctr = rc2Dvector (half) - mOrg;
   ctr = mapPoint (ctr);
   // Now create a Xform scaled appropriately
   rcIPair ic = steps + steps + cannonicalSize ();
   rcDPair scale ((double) ic.x() / (double) cannonicalSize().x(),
          (double) ic.y() / (double) cannonicalSize().y());
   rcRadian none (0.0); rc2Fvector org (0.0f, 0.0f);
   rcMatrix_2d mat (none, scale);
   rc2Xform exp (mat, org);
   exp = exp * *this; // Note: Order of composition is left to right
   // Now place this affine rectangle anchored at the center
   scale = scale * xyScale();
   return rcAffineRectangle (ctr, angle(), scale, ic, half);
 }
rc2Dvector rcAffineRectangle::getPixelLoc (int32 x, int32 y) const
Definition at line 143 of file rc_affine.cpp.
References affineToImage(), mImgSz, mStep, rmAssert, rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by rcAffineWindow::getPixelLoc().
 {
   rmAssert(x >= 0 && x < mImgSz.x());
   rmAssert(y >= 0 && y < mImgSz.y());
   return affineToImage(rc2Dvector(x*mStep.x(), y*mStep.y()));
 }
rc2Dvector rcAffineRectangle::getPixelLoc (double x, double y) const
Definition at line 151 of file rc_affine.cpp.
References affineToImage(), mImgSz, mStep, rmAssert, rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
   rmAssert(x >= 0 && x < (double)mImgSz.x());
   rmAssert(y >= 0 && y < (double)mImgSz.y());
   return affineToImage(rc2Dvector(x*mStep.x(), y*mStep.y()));
 }
rc2Dvector rcAffineRectangle::imageToAffine (const rc2Dvector & pt) const inline
Definition at line 178 of file rc_affine.h.
References rc2Xform::invMapPoint().
Referenced by rcVisualFunction::cardiacMeasure().
   { return invMapPoint(pt); }
rc2Fvector rcAffineRectangle::imageToAffine (const rc2Fvector & pt) const inline
Definition at line 181 of file rc_affine.h.
References rc2Xform::invMapPoint().
   { return invMapPoint(pt); }
bool rcAffineRectangle::isValid () const inline
Definition at line 147 of file rc_affine.h.
References mImgSz, rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcPolygon::rcPolygon().
   {
     return (mImgSz.x() > 0 && mImgSz.y() > 0);
   }
bool rcAffineRectangle::operator!= (const rcAffineRectangle & aRect) const inline
Definition at line 226 of file rc_affine.h.
   { return !(*this == aRect); }
bool rcAffineRectangle::operator== (const rcAffineRectangle & aRect) const inline
Definition at line 223 of file rc_affine.h.
References mImgSz.
   { return (mImgSz == aRect.mImgSz) && ((rc2Xform*)this)->operator==(aRect); }
const rc2Dvector& rcAffineRectangle::origin () const inline
Definition at line 152 of file rc_affine.h.
References rc2Xform::trans().
Referenced by rcValue::rcValue().
   { return trans(); }
rcDPair rcAffineRectangle::xyScale () const inline
Definition at line 158 of file rc_affine.h.
References rc2Xform::xScale(), and rc2Xform::yScale().
Referenced by expand(), and rcShape::needAffineRect().
   { return rcDPair(xScale(), yScale()); }
Friends And Related Function Documentation
ostream& operator<< (ostream & ous, const rcAffineRectangle & dis) friend
Definition at line 214 of file rc_affine.h.
   {
     ous << "[AR: O: " << dis.origin() << " A: " << dis.angle().Double() << " D: "
     << dis.cannonicalSize() << "S: " << dis.xScale() << " " << dis.yScale();
     ous << dis.matrix() << endl << "Axy: " << dis.xRot() << " " << dis.yRot() << endl;
     ous << dis.boundingBox () << " AR] " << endl;
     return ous;
   }
Member Data Documentation
rcIPair rcAffineRectangle::mImgSz private
Definition at line 231 of file rc_affine.h.
Referenced by cannonicalSize(), getPixelLoc(), isValid(), operator==(), and rcAffineRectangle().
rc2Dvector rcAffineRectangle::mOrg private
Definition at line 232 of file rc_affine.h.
Referenced by expand(), and rcAffineRectangle().
rc2Dvector rcAffineRectangle::mStep private
Definition at line 230 of file rc_affine.h.
Referenced by getPixelLoc(), and rcAffineRectangle().
The documentation for this class was generated from the following files:
include/visual/rc_affine.h
src/visual/code/rc_affine.cpp