Visible: rcRect Class Reference
rcRect Class Reference
#include <include/visual/rc_rect.h>
Public Member Functions
rcRect ()
rcRect (int32 x, int32 y, int32 width, int32 height)
rcRect (const rcIRect &other)
int32 x () const
int32 y () const
bool empty () const
int32 setX (int32 x)
int32 setY (int32 y)
int32 setWidth (int32 w)
int32 setHeight (int32 h)
Public Member Functions inherited from rcRectangle< int32 >
rcRectangle ()
rcRectangle (int32w, int32h)
rcRectangle (int32x, int32y, int32w, int32h)
rcRectangle (const rcPair< int32 > &v1, const rcPair< int32 > &v2)
bool operator== (const rcRectangle< int32 > &) const
bool operator!= (const rcRectangle< int32 > &rhs) const
const rcPair< int32 > & origin () const
void origin (const rcPair< int32 > &)
void translate (const rcPair< int32 > &)
const rcPair< int32 > & ul () const
rcPair< int32 > ur () const
rcPair< int32 > ll () const
const rcPair< int32 > & lr () const
rcPair< int32 > center () const
int32 width () const
void width (int32w)
int32 height () const
void height (int32h)
int32 area () const
rcPair< int32 > size () const
void size (const rcPair< int32 > &)
bool isNull (void) const
bool overlaps (const rcRectangle< int32 > &, bool touching=false) const
bool contains (const rcRectangle< int32 > &) const
bool contains (const rcPair< int32 > &) const
rcRectangle< int32 > intersect (const rcRectangle< int32 > &other, bool throwIfNoOverlap=false) const
rcRectangle operator& (const rcRectangle< int32 > &other) const
rcRectangle< int32 > & operator&= (const rcRectangle< int32 > &other)
rcRectangle< int32 > enclose (const rcRectangle< int32 > &) const
rcRectangle< int32 > operator| (const rcRectangle< int32 > &) const
rcRectangle< int32 > & operator|= (const rcRectangle< int32 > &)
rcRectangle< int32 > trim (int32left, int32right, int32top, int32bottom, bool throwIfNegativeSize=false) const
rcRectangle< int32 > trim (int32pad, bool throwIfNegativeSize=false) const
rcRectangle< int32 > transpose () const
Additional Inherited Members
Protected Member Functions inherited from rcRectangle< int32 >
void normalize ()
Protected Attributes inherited from rcRectangle< int32 >
rcPair< int32 > mUpperLeft
rcPair< int32 > mLowerRight
Detailed Description
Definition at line 17 of file rc_rect.h.
Constructor & Destructor Documentation
rcRect::rcRect () inline
Definition at line 21 of file rc_rect.h.
 : rcIRect () {}
rcRect::rcRect (int32 x, int32 y, int32 width, int32 height) inline
Definition at line 23 of file rc_rect.h.
     : rcIRect (x, y, width, height) {}
rcRect::rcRect (const rcIRect & other) inline
Definition at line 26 of file rc_rect.h.
     : rcIRect (other) {}
Member Function Documentation
bool rcRect::empty (void) const inline
Definition at line 40 of file rc_rect.h.
References rcRectangle< int32 >::isNull().
Referenced by rcAnalyzer::getNextResult().
 { return isNull (); }
int32 rcRect::setHeight (int32 h) inline
Definition at line 54 of file rc_rect.h.
References rcRectangle< int32 >::height().
Referenced by rcRectSettingWidget::valueChanged().
 { height(h); return h; }
int32 rcRect::setWidth (int32 w) inline
Definition at line 53 of file rc_rect.h.
References rcRectangle< int32 >::width().
Referenced by rcRectSettingWidget::valueChanged().
 { width(w); return w; }
int32 rcRect::setX (int32 x) inline
Definition at line 51 of file rc_rect.h.
References rcRectangle< int32 >::mUpperLeft, x(), and rcPair< T >::x().
 { mUpperLeft.x() = x; return x; }
int32 rcRect::setY (int32 y) inline
Definition at line 52 of file rc_rect.h.
References rcRectangle< int32 >::mUpperLeft, y(), and rcPair< T >::y().
 { mUpperLeft.y() = y; return y; }
int32 rcRect::x () const inline
Definition at line 36 of file rc_rect.h.
References rcRectangle< int32 >::mUpperLeft, and rcPair< T >::x().
Referenced by rcMonitor::buildCellBoundary(), rcMuscleTracker::calculateCellLocation(), rcWindow::canTrim(), rcMonitor::displayScalarFocusArea(), rcImageCanvasGL::drawCurrentFocus(), rcCell::enclosingBox(), rcWindow::entire(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcMuscleTracker::genEdgePoints(), rcAutoCorrelation::genPoint(), rcPointCorrelation::genSpace(), rcMomentGenerator::genSumSumSq1D(), rcMomentGenerator::genSumSumSq2D(), rcMomentGenerator::genSumSumSq2DFast(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcEngineImpl::muscleTracker(), rcWindow::operator()(), rcWindow::pelPointer(), rcEngineImpl::postTrackingResults(), rcEngineImpl::produceDebugResults(), rcCellWriterGroup::rcCellWriterGroup(), rcEngineFocusData::rcEngineFocusData(), rcValue::rcValue(), rcWindow::rowPointer(), rcWindow::setDoublePixel(), rcWindow::setPixel(), rcRectSettingWidget::settingChanged(), setX(), rcWindow::translate(), rcWindow::trim(), rcImageCanvasGL::updateAnalysisRect(), rcRectSettingWidget::valueChanged(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), and rcEngineImpl::writeEntropyData().
 { return mUpperLeft.x(); }
int32 rcRect::y () const inline
Definition at line 37 of file rc_rect.h.
References rcRectangle< int32 >::mUpperLeft, and rcPair< T >::y().
Referenced by rcMonitor::buildCellBoundary(), rcMuscleTracker::calculateCellLocation(), rcWindow::canTrim(), rcMonitor::displayScalarFocusArea(), rcImageCanvasGL::drawCurrentFocus(), rcCell::enclosingBox(), rcWindow::entire(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcMuscleTracker::genEdgePoints(), rcAutoCorrelation::genPoint(), rcPointCorrelation::genSpace(), rcMomentGenerator::genSumSumSq1D(), rcMomentGenerator::genSumSumSq2D(), rcMomentGenerator::genSumSumSq2DFast(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcEngineImpl::muscleTracker(), rcWindow::operator()(), rcWindow::pelPointer(), rcEngineImpl::postTrackingResults(), rcEngineImpl::produceDebugResults(), rcCellWriterGroup::rcCellWriterGroup(), rcEngineFocusData::rcEngineFocusData(), rcValue::rcValue(), rcWindow::rowPointer(), rcWindow::setDoublePixel(), rcWindow::setPixel(), rcRectSettingWidget::settingChanged(), setY(), rcWindow::translate(), rcWindow::trim(), rcImageCanvasGL::updateAnalysisRect(), rcRectSettingWidget::valueChanged(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), and rcEngineImpl::writeEntropyData().
 { return mUpperLeft.y(); }
The documentation for this class was generated from the following file:
include/visual/rc_rect.h