Visible: restore_context_body Class Reference
restore_context_body Class Reference
Public Types
typedef smart_ptr_clone
< persistent > persistent_ptr
typedef std::map< unsigned,
void * > magic_map
typedef std::map< unsigned
short,
restore_context::callback_data > callback_map
typedef std::map< unsigned
short, persistent_ptr > interface_map
Public Member Functions
restore_context_body (const itext &device) throw (persistent_restore_failed)
~restore_context_body (void)
const itext & device (void) const
unsigned char version (void) const
bool little_endian (void) const
int get (void) throw (persistent_restore_failed)
std::pair< bool, void * > pointer_map (unsigned magic)
void pointer_add (unsigned magic, void *new_pointer)
unsigned short register_type (restore_context::create_callback create, restore_context::restore_callback restore)
bool is_callback (unsigned short key) const
restore_context::callback_data lookup_type (unsigned short key) const throw (persistent_illegal_type)
unsigned short register_interface (const persistent &sample)
bool is_interface (unsigned short key) const
const persistent & lookup_interface (unsigned short key) const throw (persistent_illegal_type)
Public Attributes
unsigned short m_max_key
unsigned char m_version
bool m_little_endian
itext m_device
magic_map m_pointers
callback_map m_callbacks
interface_map m_interfaces
Detailed Description
Definition at line 265 of file persistent.cpp.
Member Typedef Documentation
typedef std::map<unsigned short,restore_context::callback_data> restore_context_body::callback_map
Definition at line 270 of file persistent.cpp.
typedef std::map<unsigned short,persistent_ptr> restore_context_body::interface_map
Definition at line 271 of file persistent.cpp.
typedef std::map<unsigned,void*> restore_context_body::magic_map
Definition at line 269 of file persistent.cpp.
typedef smart_ptr_clone<persistent> restore_context_body::persistent_ptr
Definition at line 268 of file persistent.cpp.
Constructor & Destructor Documentation
restore_context_body::restore_context_body (const itext & device) throw (persistent_restore_failed) inline
Definition at line 281 of file persistent.cpp.
References m_device, m_pointers, m_version, itext::set_binary_mode(), and to_string().
                                                                              :
     m_max_key(0), m_little_endian(::little_endian()), m_device(device)
     {
       m_device.set_binary_mode();
       // map a null pointer onto magic number zero
       m_pointers[0] = 0;
       // get the dump version and see if we support it
       m_version = (unsigned char)get();
       if (m_version != 1 && m_version != 2)
         throw persistent_restore_failed(std::string("wrong version: ") + to_string(m_version));
     }
restore_context_body::~restore_context_body (void) inline
Definition at line 293 of file persistent.cpp.
     {
     }
Member Function Documentation
const itext& restore_context_body::device (void) const inline
Definition at line 297 of file persistent.cpp.
References m_device.
Referenced by restore_context::device().
     {
       return m_device;
     }
int restore_context_body::get (void) throw (persistent_restore_failed) inline
Definition at line 312 of file persistent.cpp.
References itext::error(), itext::error_string(), itext::get(), and m_device.
Referenced by restore_context::get().
     {
       int result = m_device.get();
       if (result < 0)
       {
         if (m_device.error()) throw persistent_restore_failed(std::string("input device error: ") + m_device.error_string());
         throw persistent_restore_failed(std::string("premature end of file"));
       }
       return result;
     }
bool restore_context_body::is_callback (unsigned short key) const inline
Definition at line 346 of file persistent.cpp.
References m_callbacks.
Referenced by restore_context::is_callback().
     {
       return m_callbacks.find(key) != m_callbacks.end();
     }
bool restore_context_body::is_interface (unsigned short key) const inline
Definition at line 366 of file persistent.cpp.
References m_interfaces.
Referenced by restore_context::is_interface().
     {
       return m_interfaces.find(key) != m_interfaces.end();
     }
bool restore_context_body::little_endian (void) const inline
Definition at line 307 of file persistent.cpp.
References m_little_endian.
Referenced by restore_context::little_endian().
     {
       return m_little_endian;
     }
const persistent& restore_context_body::lookup_interface (unsigned short key) const throw (persistent_illegal_type) inline
Definition at line 371 of file persistent.cpp.
References m_interfaces.
     {
       interface_map::const_iterator found = m_interfaces.find(key);
       if (found == m_interfaces.end())
         throw persistent_illegal_type(key);
       return *(found->second);
     }
restore_context::callback_data restore_context_body::lookup_type (unsigned short key) const throw (persistent_illegal_type) inline
Definition at line 351 of file persistent.cpp.
References m_callbacks.
     {
       callback_map::const_iterator found = m_callbacks.find(key);
       if (found == m_callbacks.end())
         throw persistent_illegal_type(key);
       return found->second;
     }
void restore_context_body::pointer_add (unsigned magic, void * new_pointer) inline
Definition at line 334 of file persistent.cpp.
References m_pointers.
Referenced by restore_context::pointer_add().
     {
       m_pointers[magic] = new_pointer;
     }
std::pair<bool,void*> restore_context_body::pointer_map (unsigned magic) inline
Definition at line 323 of file persistent.cpp.
References m_pointers.
Referenced by restore_context::pointer_map().
     {
       magic_map::iterator found = m_pointers.find(magic);
       if (found == m_pointers.end())
       {
         // this magic number has never been seen before
         return std::pair<bool,void*>(false,0);
       }
       return std::pair<bool,void*>(true,found->second);
     }
unsigned short restore_context_body::register_interface (const persistent & sample) inline
Definition at line 359 of file persistent.cpp.
References m_interfaces, and m_max_key.
Referenced by restore_context::register_interface().
     {
       unsigned short key = ++m_max_key;
       m_interfaces[key] = persistent_ptr(sample);
       return key;
     }
unsigned short restore_context_body::register_type (restore_context::create_callback create, restore_context::restore_callback restore) inline
Definition at line 339 of file persistent.cpp.
References m_callbacks, and m_max_key.
Referenced by restore_context::register_type().
     {
       unsigned short key = ++m_max_key;
       m_callbacks[key] = std::make_pair(create,restore);
       return key;
     }
unsigned char restore_context_body::version (void) const inline
Definition at line 302 of file persistent.cpp.
References m_version.
Referenced by restore_context::version().
     {
       return m_version;
     }
Member Data Documentation
callback_map restore_context_body::m_callbacks
Definition at line 278 of file persistent.cpp.
Referenced by is_callback(), lookup_type(), and register_type().
itext restore_context_body::m_device
Definition at line 276 of file persistent.cpp.
Referenced by device(), get(), and restore_context_body().
interface_map restore_context_body::m_interfaces
Definition at line 279 of file persistent.cpp.
Referenced by is_interface(), lookup_interface(), and register_interface().
bool restore_context_body::m_little_endian
Definition at line 275 of file persistent.cpp.
Referenced by little_endian().
unsigned short restore_context_body::m_max_key
Definition at line 273 of file persistent.cpp.
Referenced by register_interface(), and register_type().
magic_map restore_context_body::m_pointers
Definition at line 277 of file persistent.cpp.
Referenced by pointer_add(), pointer_map(), and restore_context_body().
unsigned char restore_context_body::m_version
Definition at line 274 of file persistent.cpp.
Referenced by restore_context_body(), and version().
The documentation for this class was generated from the following file:
include/stlplus/persistent.cpp