Visible: oiobuff Class Reference
oiobuff Class Reference
#include <include/stlplus/iostreamio.hpp>
Public Member Functions
oiobuff (std::ostream &)
~oiobuff (void)
Public Member Functions inherited from obuff
obuff (bool line_buffer=false, otext::newline_t newline=otext::native_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_line_buffer (bool mode)
bool line_buffer (void) const
void set_newline_mode (otext::newline_t newline)
otext::newline_t newline_mode (void) const
unsigned integer_width (void) const
void set_integer_width (unsigned)
unsigned integer_radix (void) const
void set_integer_radix (unsigned)
radix_display_t integer_display (void) const
void set_integer_display (radix_display_t)
unsigned real_width (void) const
void set_real_width (unsigned)
unsigned real_precision (void) const
void set_real_precision (unsigned)
real_display_t real_display (void) const
void set_real_display (real_display_t)
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual std::string error_string (void) const
virtual ~obuff (void)
Protected Member Functions
virtual unsigned put (unsigned char)
virtual void flush (void)
Protected Attributes
std::ostream & m_stream
Protected Attributes inherited from obuff
bool m_line_buffer
otext::newline_t m_newline
unsigned long m_bytes
unsigned m_line
unsigned m_column
unsigned m_integer_width
unsigned m_integer_radix
radix_display_t m_integer_display
unsigned m_real_width
unsigned m_real_precision
real_display_t m_real_display
int m_error_number
int m_aliases
Private Member Functions
oiobuff (const oiobuff &)
oiobuff & operator= (const oiobuff &)
Friends
class oiotext
Detailed Description
Definition at line 47 of file iostreamio.hpp.
Constructor & Destructor Documentation
oiobuff::oiobuff (std::ostream & str)
Definition at line 41 of file iostreamio.cpp.
                                 : m_stream(str)
 {
 }
oiobuff::~oiobuff (void)
Definition at line 45 of file iostreamio.cpp.
References flush().
 {
   flush();
 }
oiobuff::oiobuff (const oiobuff &) private
Member Function Documentation
void oiobuff::flush (void) protected virtual
Reimplemented from obuff.
Definition at line 63 of file iostreamio.cpp.
References m_stream, obuff::set_error(), and textio_put_failed.
Referenced by ~oiobuff().
 {
   m_stream.flush();
   if (m_stream.fail())
   {
     set_error(textio_put_failed);
     m_stream.clear(m_stream.rdstate() & (~std::ios::failbit));
   }
 }
oiobuff& oiobuff::operator= (const oiobuff &) private
unsigned oiobuff::put (unsigned char ch) protected virtual
Implements obuff.
Definition at line 50 of file iostreamio.cpp.
References m_stream, obuff::set_error(), and textio_put_failed.
 {
   m_stream.put(ch);
   // capture any errors and clear non-fatal errors
   if (m_stream.fail())
   {
     set_error(textio_put_failed);
     m_stream.clear(m_stream.rdstate() & (~std::ios::failbit));
     return 0;
   }
   return 1;
 }
Friends And Related Function Documentation
friend class oiotext friend
Definition at line 49 of file iostreamio.hpp.
Member Data Documentation
std::ostream& oiobuff::m_stream protected
Definition at line 51 of file iostreamio.hpp.
Referenced by flush(), oiotext::get_stream(), and put().
The documentation for this class was generated from the following files:
include/stlplus/iostreamio.hpp
include/stlplus/iostreamio.cpp