Visible: rcAnalyzerResult Class Reference
rcAnalyzerResult Class Reference
#include <include/analysis/rc_analyzer.h>
Public Member Functions
rcAnalyzerResult ()
double entropy () const
const rcSharedFrameBufPtr & frameBuf () const
void setEntropy (double e)
void setFrameBuf (const rcSharedFrameBufPtr &r)
Private Attributes
double mEntropy
rcSharedFrameBufPtr mFrame
Detailed Description
Definition at line 137 of file rc_analyzer.h.
Constructor & Destructor Documentation
rcAnalyzerResult::rcAnalyzerResult () inline
Definition at line 140 of file rc_analyzer.h.
 : mEntropy(-1.0), mFrame(0) { };
Member Function Documentation
double rcAnalyzerResult::entropy () const inline
Definition at line 145 of file rc_analyzer.h.
References mEntropy.
Referenced by rcEngineImpl::entropyTrackerWindow(), and rcEngineImpl::processCapturedData().
 { return mEntropy; };
const rcSharedFrameBufPtr& rcAnalyzerResult::frameBuf () const inline
Definition at line 147 of file rc_analyzer.h.
References mFrame.
Referenced by rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::frameInterrupt(), rcEngineImpl::processCapturedData(), and rcEngineMovieCapture::run().
 { return mFrame; };
void rcAnalyzerResult::setEntropy (double e) inline
Definition at line 151 of file rc_analyzer.h.
References mEntropy.
Referenced by rcAnalyzer::getNextResult(), and rcAnalyzer::popResult().
 { mEntropy = e; };
void rcAnalyzerResult::setFrameBuf (const rcSharedFrameBufPtr & r) inline
Definition at line 152 of file rc_analyzer.h.
References mFrame.
Referenced by rcAnalyzer::getNextResult(), and rcAnalyzer::popResult().
 { mFrame= r; };
Member Data Documentation
double rcAnalyzerResult::mEntropy private
Definition at line 152 of file rc_analyzer.h.
Referenced by entropy(), and setEntropy().
rcSharedFrameBufPtr rcAnalyzerResult::mFrame private
Definition at line 156 of file rc_analyzer.h.
Referenced by frameBuf(), and setFrameBuf().
The documentation for this class was generated from the following file:
include/analysis/rc_analyzer.h