Visible: rcXMLParser Class Reference
rcXMLParser Class Reference
#include <include/visUI/rc_xmlparser.h>
Public Member Functions
rcXMLParser (rcExperimentImportMode mode, uint32 textLines, rcProgressIndicator *progress, QXmlErrorHandler *errorHandler)
bool startDocument ()
bool endDocument ()
bool startElement (const QString &, const QString &, const QString &, const QXmlAttributes &)
bool endElement (const QString &, const QString &, const QString &)
bool characters (const QString &ch)
QString errorString ()
const rcXMLElementTree & elementTree () const
rcXMLElementTree & elementTree ()
void setIgnoreMode (rcXMLElementType elementType, bool startElement)
Private Attributes
rcXMLElementTree mElementTree
rcXMLElementTree::iterator mElementLatest
uint32 mErrors
rcExperimentImportMode mMode
bool mIgnoreAll
rcTimestamp mStartTime
bool mEmptyTree
uint32 mExpectedElements
uint32 mParsedElements
rcProgressIndicator * mProgress
QXmlErrorHandler * mErrorHandler
QString mErrorString
const rcXMLNameMapper * mNameMapper
bool mVersionDetected
Detailed Description
Definition at line 24 of file rc_xmlparser.h.
Constructor & Destructor Documentation
rcXMLParser::rcXMLParser (rcExperimentImportMode mode, uint32 textLines, rcProgressIndicator * progress, QXmlErrorHandler * errorHandler)
Definition at line 22 of file rc_xmlparser.cpp.
                                                            :
         QXmlDefaultHandler(),
         mErrors( 0 ),
         mMode( mode ),
         mIgnoreAll( false ),
         mStartTime( 0.0 ),
         mEmptyTree( true ),
         mExpectedElements( textLines ), // Just a guess, one element per line
         mParsedElements( 0 ),
         mProgress( progress ),
         mErrorHandler( errorHandler ),
         mNameMapper( rfGetXMLNameMapper(0) ),
         mVersionDetected( false )
 {
 }
Member Function Documentation
bool rcXMLParser::characters (const QString & ch)
Definition at line 178 of file rc_xmlparser.cpp.
References rcXMLElement::content(), mElementLatest, mEmptyTree, mErrors, and mIgnoreAll.
 {
     if ( !mIgnoreAll ) {
         // Strip extra whitespace
         QString stripped = ch.stripWhiteSpace();
         if ( !stripped.isEmpty() ) {
             if ( !mEmptyTree ) {
                 rcXMLElement& e = *mElementLatest;
                 // Add content to latest element
                             std::string& content = e.content();
                 content += ch.latin1();
             }
         }
     }
     return !mErrors;
 }
const rcXMLElementTree& rcXMLParser::elementTree () const inline
Definition at line 43 of file rc_xmlparser.h.
References mElementTree.
Referenced by rcModelDomain::requestOpen().
 { return mElementTree; };
rcXMLElementTree& rcXMLParser::elementTree () inline
Definition at line 44 of file rc_xmlparser.h.
References mElementTree.
 { return mElementTree; };
bool rcXMLParser::endDocument ()
Definition at line 54 of file rc_xmlparser.cpp.
References endl(), mElementTree, mProgress, mStartTime, rcTimestamp::now(), rcProgressIndicator::progress(), rcTimestamp::secs(), and TRUE.
 {
     rcTimestamp elapsedTime = rcTimestamp::now() - mStartTime;
     cout << mElementTree.size() << " XML elements imported from file in " << elapsedTime.secs() << " seconds" << endl;
     if ( mProgress)
         mProgress->progress( 100.0 );
     return TRUE;
 }
bool rcXMLParser::endElement (const QString & , const QString & , const QString & name)
Definition at line 122 of file rc_xmlparser.cpp.
References rcXMLElement::content(), rcXMLNameMapper::elementType(), eXMLElementVersion, mElementLatest, mElementTree, mEmptyTree, mErrors, mErrorString, mIgnoreAll, mNameMapper, mVersionDetected, rcXMLFileVersion, rcXMLOldestSupportedFileVersion, rfGetXMLNameMapper(), and setIgnoreMode().
 {
     if ( !mEmptyTree ) {
         rcXMLElementType elementType = mNameMapper->elementType( name.latin1() );
        if ( elementType == eXMLElementVersion && !mVersionDetected ) {
              rcXMLElement& e = *mElementLatest;
                  std::string& content = e.content();
              rcValue fileVer( content.c_str() );
              int v = fileVer;
              if ( v < rcXMLOldestSupportedFileVersion ) {
                  ostrstream estr;
                  // File version too obsolete to parse, bail out now
                  ++mErrors;
                  estr <<  "\nobsolete experiment file version " << v
                       << " not supported.";
                  estr << ends;
                  estr.freeze();
                  mErrorString = estr.str();
              } else if ( v > rcXMLFileVersion ) {
                  ostrstream estr;
                  // File version too new to parse, bail out now
                  ++mErrors;
                  estr <<  "\nexperiment file version " << v
                       << " not supported.";
                  estr << ends;
                  estr.freeze();
                  mErrorString = estr.str();
              }
              mNameMapper = rfGetXMLNameMapper( v );
              mVersionDetected = true;
         }
         // Control mode
         setIgnoreMode( elementType, false );
         if ( ! mIgnoreAll ) {
             if ( mElementLatest->type() == elementType ) {
                 // Pop latest
                 mElementLatest = mElementTree.parent( mElementLatest );
             } else {
                 // Mismatched start and end tags, serious error!
                 // This will be reported by rcXMLErrorHandler so don't count it here
             }
         }
     } else {
         // Empty tree, serious error!
         // This will be reported by rcXMLErrorHandler so don't count it here
     }
     return !mErrors;
 }
QString rcXMLParser::errorString ()
Definition at line 223 of file rc_xmlparser.cpp.
References mErrorString.
 {
     return mErrorString;
 }
void rcXMLParser::setIgnoreMode (rcXMLElementType elementType, bool startElement)
Definition at line 198 of file rc_xmlparser.cpp.
References eExperimentImportAll, eExperimentImportAllData, eExperimentImportAllSettings, eExperimentImportExperimentSettings, eXMLElementExperimentData, eXMLElementExperimentSettingCategory, mIgnoreAll, mMode, and startElement().
Referenced by endElement(), and startElement().
 {
      switch ( mMode ) {
          case eExperimentImportAllSettings:
          case eExperimentImportExperimentSettings:
              if ( elementType == eXMLElementExperimentData ) {
                  // We want to load settings only, ignore all measurement data
                  mIgnoreAll = startElement;
              }
              break;
          case eExperimentImportAllData:
              if ( elementType == eXMLElementExperimentSettingCategory ) {
                  // We want to load measurements only, ignore all settings data
                  mIgnoreAll = startElement;
              }
              break;
          case eExperimentImportAll:
              // Load everything
              break;
      }
 }
bool rcXMLParser::startDocument ()
Definition at line 41 of file rc_xmlparser.cpp.
References mElementLatest, mElementTree, mEmptyTree, mErrors, mIgnoreAll, mProgress, mStartTime, rcTimestamp::now(), rcProgressIndicator::progress(), and TRUE.
 {
     mErrors = 0;
     mElementLatest = mElementTree.begin();
     mIgnoreAll = false;
     mStartTime = rcTimestamp::now();
     mEmptyTree = true;
     if ( mProgress)
         mProgress->progress( 0.0 );
     return TRUE;
 }
bool rcXMLParser::startElement (const QString & , const QString & , const QString & name, const QXmlAttributes & attributes)
Definition at line 64 of file rc_xmlparser.cpp.
References rcXMLNameMapper::attributeType(), rcXMLNameMapper::elementType(), endl(), eXMLAttributeMax, eXMLElementMax, mElementLatest, mElementTree, mEmptyTree, mErrors, mExpectedElements, mIgnoreAll, mNameMapper, mParsedElements, mProgress, rcProgressIndicator::progress(), and setIgnoreMode().
Referenced by setIgnoreMode().
 {
     if ( mProgress ) {
         ++mParsedElements;
         if ( !(mParsedElements % 32) )
             mProgress->progress( 100.0 * mParsedElements/mExpectedElements );
     }
     rcXMLElementType type = mNameMapper->elementType( name.latin1() );
     if ( type != eXMLElementMax ) {
         // Control mode
         setIgnoreMode( type, true );
         if ( !mIgnoreAll ) {
             rcAttributeList attrs;
             const int attrCount = attributes.count();
             if ( attrCount > 0 ) {
                 attrs.reserve( attrCount );
                 // Produce attributes
                 for ( int i = 0; i < attrCount; ++i ) {
                                     const std::string attributeName = attributes.qName( i ).latin1();
                     // Check validity
                     rcXMLAttributeType type = mNameMapper->attributeType( attributeName );
                     if ( type != eXMLAttributeMax ) {
                                             const std::string attributeValue( attributes.value( i ).latin1() );
                         attrs.push_back( rcAttribute( type, attributeValue ) );
                     } else {
                         // Unknown attribute
                         cerr << "rcXMLParser error: unknown attribute \"" << attributeName << "\"" << endl;
                     }
                 }
             }
             // Create element
             rcXMLElement e( type, attrs );
             // Populate tree
             if ( mEmptyTree ) {
                 // Add first element as a special case
                 mElementLatest = mElementTree.insert( mElementLatest, e );
                 if ( mElementTree.size() > 0 )
                     mEmptyTree = false;
             } else {
                 mElementLatest = mElementTree.append_child( mElementLatest, e );
             }
         }
     }
     else {
         // Error, unknown element
 //        cerr << "rcXMLParser error: unknown element <" << name << ">" << endl;
     }
     return !mErrors;
 }
Member Data Documentation
rcXMLElementTree::iterator rcXMLParser::mElementLatest private
Definition at line 51 of file rc_xmlparser.h.
Referenced by characters(), endElement(), startDocument(), and startElement().
rcXMLElementTree rcXMLParser::mElementTree private
Definition at line 50 of file rc_xmlparser.h.
Referenced by elementTree(), endDocument(), endElement(), startDocument(), and startElement().
bool rcXMLParser::mEmptyTree private
Definition at line 56 of file rc_xmlparser.h.
Referenced by characters(), endElement(), startDocument(), and startElement().
QXmlErrorHandler* rcXMLParser::mErrorHandler private
Definition at line 60 of file rc_xmlparser.h.
uint32 rcXMLParser::mErrors private
Definition at line 52 of file rc_xmlparser.h.
Referenced by characters(), endElement(), startDocument(), and startElement().
QString rcXMLParser::mErrorString private
Definition at line 61 of file rc_xmlparser.h.
Referenced by endElement(), and errorString().
uint32 rcXMLParser::mExpectedElements private
Definition at line 57 of file rc_xmlparser.h.
Referenced by startElement().
bool rcXMLParser::mIgnoreAll private
Definition at line 54 of file rc_xmlparser.h.
Referenced by characters(), endElement(), setIgnoreMode(), startDocument(), and startElement().
rcExperimentImportMode rcXMLParser::mMode private
Definition at line 53 of file rc_xmlparser.h.
Referenced by setIgnoreMode().
const rcXMLNameMapper* rcXMLParser::mNameMapper private
Definition at line 62 of file rc_xmlparser.h.
Referenced by endElement(), and startElement().
uint32 rcXMLParser::mParsedElements private
Definition at line 58 of file rc_xmlparser.h.
Referenced by startElement().
rcProgressIndicator* rcXMLParser::mProgress private
Definition at line 59 of file rc_xmlparser.h.
Referenced by endDocument(), startDocument(), and startElement().
rcTimestamp rcXMLParser::mStartTime private
Definition at line 55 of file rc_xmlparser.h.
Referenced by endDocument(), and startDocument().
bool rcXMLParser::mVersionDetected private
Definition at line 63 of file rc_xmlparser.h.
Referenced by endElement().
The documentation for this class was generated from the following files:
include/visUI/rc_xmlparser.h
src/visible/qt/rc_xmlparser.cpp