Visible: rcSparseHistogram Class Reference
rcSparseHistogram Class Reference
#include <include/util/rc_sparsehist.h>
Public Types
typedef std::map< uint32, uint32 > sparseArray
Public Member Functions
rcSparseHistogram (uint32 maxBins=0)
bool add (uint32 slot)
bool isValid () const
double average () const
double sum () const
void range (uint32 &min, uint32 &max) const
size_t binsUsed () const
void reset ()
const sparseArray & getArray () const
Private Attributes
sparseArray _bins
uint32 _maxBins
double _elementCount
double _weightedCount
bool _isValid
Detailed Description
Definition at line 28 of file rc_sparsehist.h.
Member Typedef Documentation
typedef std::map<uint32, uint32> rcSparseHistogram::sparseArray
Definition at line 72 of file rc_sparsehist.h.
Constructor & Destructor Documentation
rcSparseHistogram::rcSparseHistogram (uint32 maxBins = 0)
Definition at line 5 of file rc_sparsehist.cpp.
                                                    :
   _maxBins(maxBins), _elementCount(0), _weightedCount(0), _isValid(true)
 {
}
Member Function Documentation
bool rcSparseHistogram::add (uint32 slot)
Definition at line 10 of file rc_sparsehist.cpp.
References _bins, _elementCount, _isValid, _maxBins, and _weightedCount.
Referenced by MungGrabDataProc(), rcSettingPage::rcSettingPage(), rfGenerateTimeline(), and rcEngineMovieSaver::saveHdlr().
 {
   sparseArray::iterator index = _bins.find(slot);
   if (index == _bins.end())
   {
     if (_maxBins && (_bins.size() == _maxBins))
     {
       _isValid = false;
       return false;
     }
     _bins[slot] = 0;
     index = _bins.find(slot);
     assert(index != _bins.end());
   }
   (*index).second++;
   _elementCount += 1;
   _weightedCount += slot;
   return true;
 }
double rcSparseHistogram::average () const
Definition at line 35 of file rc_sparsehist.cpp.
References _bins, _elementCount, and _weightedCount.
Referenced by rcEngineMovieSaver::closeHdlr(), and rfGenerateTimeline().
 {
   if (_bins.size() == 0)
     return -1;
   return _weightedCount/_elementCount;
 }
size_t rcSparseHistogram::binsUsed () const inline
Definition at line 66 of file rc_sparsehist.h.
References _bins.
Referenced by rcEngineMovieSaver::closeHdlr(), MungGrabDataProc(), and rfDCAMVideoCapture().
 { return _bins.size(); }
const sparseArray& rcSparseHistogram::getArray () const inline
Definition at line 74 of file rc_sparsehist.h.
References _bins.
Referenced by rcEngineMovieSaver::closeHdlr(), MungGrabDataProc(), rcSettingPage::rcSettingPage(), rfDCAMVideoCapture(), and rfGenerateTimeline().
 { return _bins; }
bool rcSparseHistogram::isValid () const inline
Definition at line 48 of file rc_sparsehist.h.
References _isValid.
Referenced by rfGenerateTimeline().
 { return _isValid; }
void rcSparseHistogram::range (uint32 & min, uint32 & max) const
Definition at line 43 of file rc_sparsehist.cpp.
References _bins.
Referenced by rcEngineMovieSaver::closeHdlr(), MungGrabDataProc(), and rfDCAMVideoCapture().
 {
   if (_bins.size() == 0)
     return;
   min = (*_bins.begin()).first;
   max = (*_bins.rbegin()).first;
 }
void rcSparseHistogram::reset (void)
Definition at line 52 of file rc_sparsehist.cpp.
References _bins, _elementCount, _isValid, and _weightedCount.
Referenced by rcEngineMovieSaver::doneHdlr(), and rfDCAMVideoCapture().
 {
   _elementCount = _weightedCount = 0;
   _isValid = true;
   _bins.erase(_bins.begin(), _bins.end());
 }
double rcSparseHistogram::sum () const inline
Definition at line 57 of file rc_sparsehist.h.
References _elementCount.
 { return _elementCount; }
Member Data Documentation
sparseArray rcSparseHistogram::_bins private
Definition at line 78 of file rc_sparsehist.h.
Referenced by add(), average(), binsUsed(), getArray(), range(), and reset().
double rcSparseHistogram::_elementCount private
Definition at line 80 of file rc_sparsehist.h.
Referenced by add(), average(), reset(), and sum().
bool rcSparseHistogram::_isValid private
Definition at line 82 of file rc_sparsehist.h.
Referenced by add(), isValid(), and reset().
uint32 rcSparseHistogram::_maxBins private
Definition at line 79 of file rc_sparsehist.h.
Referenced by add().
double rcSparseHistogram::_weightedCount private
Definition at line 81 of file rc_sparsehist.h.
Referenced by add(), average(), and reset().
The documentation for this class was generated from the following files:
include/util/rc_sparsehist.h
src/util/code/rc_sparsehist.cpp