Visible: rcMovieFileExt Class Reference
rcMovieFileExt Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileExt ()
rcMovieFileExt (movieExtensionType t)
rcMovieFileExt (movieExtensionType t, int64 o)
const movieExtensionType & type () const
const int64 & offset () const
bool write (FILE *saveStream) const
void fixEndian (const reByteOrder &fileByteOrder)
Private Attributes
movieExtensionType mType
int64 mOffset
Detailed Description
Definition at line 226 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileExt::rcMovieFileExt ()
Definition at line 223 of file rc_moviefileformat.cpp.
                                :
         mType( movieExtensionEOF ), mOffset(sizeof(rcMovieFileExt))
 {
}
rcMovieFileExt::rcMovieFileExt (movieExtensionType t)
Definition at line 228 of file rc_moviefileformat.cpp.
                                                      :
         mType( t ), mOffset( sizeof(rcMovieFileExt) )
 {
}
rcMovieFileExt::rcMovieFileExt (movieExtensionType t, int64 o)
Definition at line 233 of file rc_moviefileformat.cpp.
                                                               :
         mType( t ), mOffset( o )
 {
}
Member Function Documentation
void rcMovieFileExt::fixEndian (const reByteOrder & fileByteOrder)
Definition at line 254 of file rc_moviefileformat.cpp.
References ByteSwapN, mOffset, mType, and rfPlatformByteOrder().
Referenced by rcMovieFileTocExt::fixEndian(), rcMovieFileOrgExt::fixEndian(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcMovieFileExpExt::fixEndian(), rcVideoCache::headerLoadRev1(), rcVideoCache::headerLoadRev2(), and write().
 {
     if ( rfPlatformByteOrder() != fileByteOrder )
 {
     ByteSwapN ( mType);
     ByteSwapN  (mOffset); // This is a byte offset to the beginning of the
                                 // next extension starting at the beginning of this one.
 }
 }
const int64& rcMovieFileExt::offset (void) const inline
Definition at line 236 of file rc_moviefileformat.h.
References mOffset.
Referenced by rcVideoCache::headerLoadRev1(), rcVideoCache::headerLoadRev2(), and operator<<().
 { return mOffset; };
const movieExtensionType& rcMovieFileExt::type (void) const inline
Definition at line 235 of file rc_moviefileformat.h.
References mType.
Referenced by rcVideoCache::camLoad(), rcVideoCache::cnvLoad(), rcVideoCache::expLoad(), rcVideoCache::headerLoadRev1(), rcVideoCache::headerLoadRev2(), operator<<(), rcVideoCache::orgLoad(), and rcVideoCache::tocLoadFromTOC().
 { return mType; };
bool rcMovieFileExt::write (FILE * saveStream) const
Definition at line 239 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), rfPlatformByteOrder(), and rfPlatformByteOrderMark().
Referenced by rcEngineMovieSaver::closeHdlr(), and rcGenMovieFile::flush().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileExt *>(this)->fixEndian (rfPlatformByteOrder(rfPlatformByteOrderMark()) );
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("Hdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
Member Data Documentation
int64 rcMovieFileExt::mOffset private
Definition at line 245 of file rc_moviefileformat.h.
Referenced by fixEndian(), and offset().
movieExtensionType rcMovieFileExt::mType private
Definition at line 244 of file rc_moviefileformat.h.
Referenced by fixEndian(), and type().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp