Visible: rcVectorGrabber Class Reference
rcVectorGrabber Class Reference
#include <include/visual/rc_framegrabber.h>
Public Member Functions
rcVectorGrabber (const vector< rcWindow > &images, int32 cacheSz=0)
virtual ~rcVectorGrabber ()
virtual bool isValid () const
virtual rcFrameGrabberError getLastError () const
virtual bool start ()
virtual bool stop ()
virtual int32 frameCount ()
virtual int32 cacheSize ()
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)
virtual const std::string getInputSourceName ()
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
Private Attributes
const vector< rcWindow > & mImages
uint32 mCurrentIndex
rcFrameGrabberError mLastError
int32 mCacheSz
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Detailed Description
Definition at line 127 of file rc_framegrabber.h.
Constructor & Destructor Documentation
rcVectorGrabber::rcVectorGrabber (const vector< rcWindow > & images, int32 cacheSz = 0) inline
Definition at line 130 of file rc_framegrabber.h.
                                                                        :
         mImages( images ),
         mCurrentIndex( 0 ),
     mLastError( eFrameErrorOK ),
     mCacheSz(cacheSz) {
};
virtual rcVectorGrabber::~rcVectorGrabber () inline virtual
Definition at line 137 of file rc_framegrabber.h.
 { };
Member Function Documentation
virtual int32 rcVectorGrabber::cacheSize () inline virtual
Implements rcFrameGrabber.
Definition at line 158 of file rc_framegrabber.h.
References mCacheSz.
 { return mCacheSz; }
virtual int32 rcVectorGrabber::frameCount () inline virtual
Implements rcFrameGrabber.
Definition at line 156 of file rc_framegrabber.h.
References mImages.
Referenced by rcEngineImpl::muscleTracker().
 { return mImages.size(); };
virtual const std::string rcVectorGrabber::getInputSourceName () inline virtual
Implements rcFrameGrabber.
Definition at line 174 of file rc_framegrabber.h.
Referenced by rcEngineImpl::modelTracker().
 { return "Vector of images"; };
virtual rcFrameGrabberError rcVectorGrabber::getLastError () const inline virtual
Implements rcFrameGrabber.
Definition at line 147 of file rc_framegrabber.h.
References mLastError.
Referenced by rcEngineImpl::reportOnBadGrabber().
 { return mLastError; };
virtual rcFrameGrabberStatus rcVectorGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) inline virtual
Implements rcFrameGrabber.
Definition at line 161 of file rc_framegrabber.h.
References eFrameStatusEOF, eFrameStatusOK, mCurrentIndex, mImages, and rmUnused.
{
         rmUnused( isBlocking );
         if ( mCurrentIndex < mImages.size() ) {
             // TODO: we need geometry info to allow cropping
             ptr = mImages[mCurrentIndex++].frameBuf();
             return eFrameStatusOK;
         } else {
             ptr = 0;
             return eFrameStatusEOF;
         }
     }
virtual bool rcVectorGrabber::isValid () const inline virtual
Implements rcFrameGrabber.
Definition at line 144 of file rc_framegrabber.h.
References mImages.
Referenced by rcEngineImpl::modelTracker(), and rcEngineImpl::muscleTracker().
 { return !mImages.empty(); };
virtual bool rcVectorGrabber::start (void) inline virtual
Implements rcFrameGrabber.
Definition at line 150 of file rc_framegrabber.h.
 { return true; };
virtual bool rcVectorGrabber::stop (void) inline virtual
Implements rcFrameGrabber.
Definition at line 153 of file rc_framegrabber.h.
 { return true; };
Member Data Documentation
int32 rcVectorGrabber::mCacheSz private
Definition at line 180 of file rc_framegrabber.h.
Referenced by cacheSize().
uint32 rcVectorGrabber::mCurrentIndex private
Definition at line 178 of file rc_framegrabber.h.
Referenced by getNextFrame().
const vector<rcWindow>& rcVectorGrabber::mImages private
Definition at line 174 of file rc_framegrabber.h.
Referenced by frameCount(), getNextFrame(), and isValid().
rcFrameGrabberError rcVectorGrabber::mLastError private
Definition at line 179 of file rc_framegrabber.h.
Referenced by getLastError().
The documentation for this class was generated from the following file:
include/visual/rc_framegrabber.h