Visible: rcEngineBaseImpl Class Reference
rcEngineBaseImpl Class Reference
#include <include/visiCore/rc_engineimplbase.h>
Public Member Functions
rcEngineBaseImpl ()
virtual ~rcEngineBaseImpl ()
virtual void initialize (rcEngineObserver *observer)
virtual void start (void)
virtual void stop (void)
virtual void shutdown (void)
virtual void reset (void)
virtual void process (void)
virtual rcTimestamp getElapsedTime (void)
virtual rcTimestamp getStartTime (void)
virtual rcEngineState getState (void)
virtual const rcEngineAttributes getAttributes (void)
virtual int getNSettingCategories (void)
virtual rcSettingCategory getSettingCategory (int categoryNo)
Public Member Functions inherited from rcEngine
virtual ~rcEngine ()
virtual bool operatingOnLiveInput (void)=0
virtual bool storingLiveInput (void)=0
virtual bool pauseTracking (void)=0
virtual bool resumeTracking (void)=0
virtual void notifyEngineOfPolys (const rcPolygonGroupRef *polys)=0
Protected Member Functions
bool checkSettings ()
virtual void setInternalState (rcEngineState newState)
void assertInitialized (void)
void writeData (rcEngineFocusData *focus)
Protected Attributes
rcEngineObserver * _observer
rcEngineState _state
int _frameWidth
int _frameHeight
rcPixel _frameDepth
rcWriterManager * _writerManager
rcTimestamp _startTime
rcTimestamp _currentTime
vector< rcSettingCategory > _settings
Detailed Description
Definition at line 306 of file rc_engineimplbase.h.
Constructor & Destructor Documentation
rcEngineBaseImpl::rcEngineBaseImpl ()
Definition at line 160 of file rc_engineimplbase.cpp.
                                    :
         _observer( 0 ),
         _state( eEngineUninitialized ),
         _frameWidth( 0 ),
         _frameHeight( 0 ),
         _frameDepth( rcPixelUnknown ),
         _writerManager( 0 ),
         _startTime( 0.0 ),
         _currentTime( 0.0 )
 {
}
rcEngineBaseImpl::~rcEngineBaseImpl () virtual
Definition at line 172 of file rc_engineimplbase.cpp.
References _writerManager.
 {
     delete _writerManager;
 }
Member Function Documentation
void rcEngineBaseImpl::assertInitialized (void) protected
Definition at line 377 of file rc_engineimplbase.cpp.
References _state, and eEngineUninitialized.
Referenced by getElapsedTime(), getNSettingCategories(), getSettingCategory(), and getStartTime().
 {
     if (_state == eEngineUninitialized)
         throw rcEngineException( "engine uninitialized" );
 }
bool rcEngineBaseImpl::checkSettings () protected
Definition at line 292 of file rc_engineimplbase.cpp.
References _settings, endl(), rcSettingCategory::getNSettings(), rcSettingCategory::getSettingInfo(), rcSettingInfo::getTag(), and rcSettingCategory::getTag().
Referenced by initialize().
 {
     bool success = true;
     vector<rcSettingCategory>::iterator i, j;
     for ( i = _settings.begin(); i < _settings.end(); ++i ) {
         rcSettingCategory c1 = *i;
         uint32 nSettings = c1.getNSettings();
         // Verify that all settings have a unique tag
         for ( uint32 x = 0; x < nSettings; ++x )
         {
             rcSettingInfo s1 = c1.getSettingInfo( x );
             for ( uint32 y = x+1; y < nSettings; ++y )
             {
                 rcSettingInfo s2 = c1.getSettingInfo( y );
                 if ( !strcmp( s1.getTag(), s2.getTag() ) ) {
                     success = false;
                     cerr << "rcEngineBaseImpl::checkSettings error: ";
                     cerr << "two rcSettingInfo objects have the same XML tag \"" << c1.getTag() << "\"" << endl;
                 }
             }
         }
         // Verify that all categories have a unique tag
         for ( j = i+1; j < _settings.end(); ++j ) {
             rcSettingCategory c2 = *j;
             if ( !strcmp( c1.getTag(), c2.getTag() ) ) {
                 success = false;
                 cerr << "rcEngineBaseImpl::checkSettings error: ";
                 cerr << "two rcSettingCategory objects have the same XML tag \"" << c1.getTag() << "\"" << endl;
             }
         }
     }
     return success;
 }
const rcEngineAttributes rcEngineBaseImpl::getAttributes (void) virtual
Implements rcEngine.
Definition at line 257 of file rc_engineimplbase.cpp.
References _frameDepth, _frameHeight, _frameWidth, rcEngineAttributes::frameDepth, rcEngineAttributes::frameHeight, rcEngineAttributes::frameWidth, rcEngineAttributes::inputName, rcEngineAttributes::liveInput, and rcEngineAttributes::liveStorage.
 {
     rcEngineAttributes attr;
     attr.frameWidth = _frameWidth;
     attr.frameHeight = _frameHeight;
     attr.frameDepth = _frameDepth;
     attr.liveInput = false;
     attr.liveStorage = false;
     attr.inputName = std::string();
     return attr;
 }
rcTimestamp rcEngineBaseImpl::getElapsedTime (void) virtual
Implements rcEngine.
Definition at line 235 of file rc_engineimplbase.cpp.
References _currentTime, _startTime, and assertInitialized().
 {
     assertInitialized();
     return _currentTime - _startTime;
 }
int rcEngineBaseImpl::getNSettingCategories (void) virtual
Implements rcEngine.
Definition at line 272 of file rc_engineimplbase.cpp.
References _settings, and assertInitialized().
 {
     assertInitialized();
     return _settings.size();
 }
rcSettingCategory rcEngineBaseImpl::getSettingCategory (int categoryNo) virtual
Implements rcEngine.
Definition at line 280 of file rc_engineimplbase.cpp.
References _settings, assertInitialized(), and rmAssert.
 {
     assertInitialized();
     rmAssert( uint32(categoryNo) < _settings.size() );
     return _settings[categoryNo];
 }
rcTimestamp rcEngineBaseImpl::getStartTime (void) virtual
Implements rcEngine.
Definition at line 243 of file rc_engineimplbase.cpp.
References _startTime, and assertInitialized().
 {
     assertInitialized();
     return _startTime;
 }
rcEngineState rcEngineBaseImpl::getState (void) virtual
Implements rcEngine.
Definition at line 251 of file rc_engineimplbase.cpp.
References _state.
Referenced by process(), start(), and stop().
 {
     return _state;
 }
void rcEngineBaseImpl::initialize (rcEngineObserver * observer) virtual
Implements rcEngine.
Definition at line 180 of file rc_engineimplbase.cpp.
References _observer, _writerManager, checkSettings(), reset(), and rmAssert.
 {
     // save the pointer to the instance of the engine observer
     _observer = observer;
     // create writer manager
     _writerManager = new rcWriterManager( observer );
     // reset state
     reset();
     // Check settings consistency
     bool settingsOK = checkSettings();
     rmAssert( settingsOK );
 }
void rcEngineBaseImpl::process (void) virtual
Implements rcEngine.
Definition at line 226 of file rc_engineimplbase.cpp.
References eEngineRunning, eEngineStopped, getState(), PRINT_STATE_CHANGE, and setInternalState().
 {
     PRINT_STATE_CHANGE("process", getState(), eEngineRunning);
     // Gentlemen, start your engines
     setInternalState( eEngineRunning );
     setInternalState( eEngineStopped );
 }
void rcEngineBaseImpl::reset (void) virtual
Implements rcEngine.
Definition at line 214 of file rc_engineimplbase.cpp.
References _currentTime, _frameDepth, _frameHeight, _frameWidth, _startTime, _state, eEngineStopped, and rcPixelUnknown.
Referenced by initialize().
 {
     _startTime = 0.0;
     _currentTime = 0.0;
     _state = eEngineStopped; // Do not send a notification
     _frameWidth = 640;
     _frameHeight = 480;
     _frameDepth = rcPixelUnknown;
 }
void rcEngineBaseImpl::setInternalState (rcEngineState newState) protected virtual
Definition at line 331 of file rc_engineimplbase.cpp.
References _observer, _state, eEnginePlayback, eEngineProcessing, eEngineRunning, eEngineShuttingDown, eEngineStopped, eEngineUninitialized, rcEngineObserver::notifyState(), and PRINT_STATE_CHANGE.
Referenced by process(), and stop().
 {
     // ignore setting to current state
     if (newState == _state)
         return;
     // validate state transition
     switch (_state)
     {
         case eEngineUninitialized:  // engine has not been initialized
             if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eUninitialized" );
             break;
         case eEngineStopped:            // engine is stopped and not generating data
             if (newState != eEngineRunning && newState != eEngineProcessing )
                 throw general_exception( "illegal state transition from eEngineStopped" );
             break;
         case eEngineRunning:            // engine is running and generating data
             if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eEngineRunning" );
             break;
         case eEnginePlayback:           // engine is running and generating data
             if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eEnginePlayback" );
             break;
         case eEngineProcessing:            // engine is processing a focus area
             if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eEngineProcessing" );
             break;
         case eEngineShuttingDown:       // engine is in the process of shutting down
             throw general_exception( "illegal state transition from eEngineShuttingDown" );
             break;
     }
     PRINT_STATE_CHANGE("setInternalState", _state, newState);
     _state = newState;
     if ( _observer )
         _observer->notifyState( _state );
 }
void rcEngineBaseImpl::shutdown (void) virtual
Implements rcEngine.
Definition at line 207 of file rc_engineimplbase.cpp.
References _state, and eEngineShuttingDown.
 {
     _state = eEngineShuttingDown;
 }
void rcEngineBaseImpl::start (void) virtual
Implements rcEngine.
Definition at line 194 of file rc_engineimplbase.cpp.
References getState(), and PRINT_STATE_CHANGE.
 {
     PRINT_STATE_CHANGE("start", getState(), eEngineStart);
 }
void rcEngineBaseImpl::stop (void) virtual
Implements rcEngine.
Definition at line 200 of file rc_engineimplbase.cpp.
References eEngineStopped, getState(), PRINT_STATE_CHANGE, and setInternalState().
 {
     PRINT_STATE_CHANGE("stop", getState(), eEngineStop);
     setInternalState( eEngineStopped );
 }
void rcEngineBaseImpl::writeData (rcEngineFocusData * focus) protected
Definition at line 384 of file rc_engineimplbase.cpp.
References _currentTime, _observer, rcEngineFocusData::flushFocusData(), rcEngineObserver::notifyTime(), rcEngineFocusData::timeStamps(), and rcEngineFocusData::writeFocusData().
 {
     const vector<rcTimestamp>& sTimestamps = focus->timeStamps();
     // Produce data for all images
     for ( uint32 i = 0; i < sTimestamps.size(); ++i ) {
         // Write all data
         focus->writeFocusData( sTimestamps[i], i );
     }
     // Flush writers
     focus->flushFocusData();
     // Update elapsed time
     _observer->notifyTime( _currentTime );
 }
Member Data Documentation
rcTimestamp rcEngineBaseImpl::_currentTime protected
Definition at line 374 of file rc_engineimplbase.h.
Referenced by getElapsedTime(), reset(), and writeData().
rcPixel rcEngineBaseImpl::_frameDepth protected
Definition at line 371 of file rc_engineimplbase.h.
Referenced by getAttributes(), and reset().
int rcEngineBaseImpl::_frameHeight protected
Definition at line 370 of file rc_engineimplbase.h.
Referenced by getAttributes(), and reset().
int rcEngineBaseImpl::_frameWidth protected
Definition at line 369 of file rc_engineimplbase.h.
Referenced by getAttributes(), and reset().
rcEngineObserver* rcEngineBaseImpl::_observer protected
Definition at line 367 of file rc_engineimplbase.h.
Referenced by initialize(), setInternalState(), and writeData().
vector<rcSettingCategory> rcEngineBaseImpl::_settings protected
Definition at line 375 of file rc_engineimplbase.h.
Referenced by checkSettings(), getNSettingCategories(), and getSettingCategory().
rcTimestamp rcEngineBaseImpl::_startTime protected
Definition at line 373 of file rc_engineimplbase.h.
Referenced by getElapsedTime(), getStartTime(), and reset().
rcEngineState rcEngineBaseImpl::_state protected
Definition at line 368 of file rc_engineimplbase.h.
Referenced by assertInitialized(), getState(), reset(), setInternalState(), and shutdown().
rcWriterManager* rcEngineBaseImpl::_writerManager protected
Definition at line 372 of file rc_engineimplbase.h.
Referenced by initialize(), and ~rcEngineBaseImpl().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplbase.h
src/visible/src/rc_engineimplbase.cpp