Visible: rcMoviePlaybackCtrlReader Class Reference
rcMoviePlaybackCtrlReader Class Reference
#include <include/visiCore/rc_playbackregs.h>
Public Member Functions
rcMoviePlaybackCtrlReader ()
virtual ~rcMoviePlaybackCtrlReader ()
int getCtrlInfo () const
Protected Attributes
rcAtomicValue< int > _ctrlInfo
Detailed Description
Definition at line 24 of file rc_playbackregs.h.
Constructor & Destructor Documentation
rcMoviePlaybackCtrlReader::rcMoviePlaybackCtrlReader () inline
Definition at line 27 of file rc_playbackregs.h.
                               : _ctrlInfo(0)
   { }
virtual rcMoviePlaybackCtrlReader::~rcMoviePlaybackCtrlReader () inline virtual
Definition at line 30 of file rc_playbackregs.h.
   { }
Member Function Documentation
int rcMoviePlaybackCtrlReader::getCtrlInfo () const inline
Definition at line 33 of file rc_playbackregs.h.
References _ctrlInfo, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), and rcEngineImpl::setSettingValue().
   { int x; return _ctrlInfo.getValue(x); }
Member Data Documentation
rcAtomicValue<int> rcMoviePlaybackCtrlReader::_ctrlInfo protected
Definition at line 37 of file rc_playbackregs.h.
Referenced by rcMoviePlaybackCtrl::ctrlInfo(), and getCtrlInfo().
The documentation for this class was generated from the following file:
include/visiCore/rc_playbackregs.h