Visible: error_context_body Class Reference
error_context_body Class Reference
#include <include/stlplus/error_handler.hpp>
Public Member Functions
error_context_body (error_handler_base &handler)
~error_context_body (void)
void set (error_handler_base &handler)
void pop (void)
Private Member Functions
error_context_body (const error_context_body &)
error_context_body & operator= (const error_context_body &)
Private Attributes
unsigned m_depth
error_handler_base * m_handler
Friends
class error_handler_base
Detailed Description
Definition at line 79 of file error_handler.hpp.
Constructor & Destructor Documentation
error_context_body::error_context_body (error_handler_base & handler)
Definition at line 558 of file error_handler.cpp.
                                                                   :
   m_depth(0), m_handler(0)
 {
   set(handler);
 }
error_context_body::~error_context_body (void)
Definition at line 564 of file error_handler.cpp.
References pop().
 {
   pop();
 }
error_context_body::error_context_body (const error_context_body &) private
Member Function Documentation
error_context_body& error_context_body::operator= (const error_context_body &) private
void error_context_body::pop (void)
Definition at line 575 of file error_handler.cpp.
References m_depth, m_handler, and error_handler_base::pop_context().
Referenced by ~error_context_body().
 {
   if (m_handler)
     m_handler->pop_context(m_depth);
 }
void error_context_body::set (error_handler_base & handler)
Definition at line 569 of file error_handler.cpp.
References error_handler_base::context_depth(), m_depth, and m_handler.
 {
   m_handler = &handler;
   m_depth = m_handler->context_depth();
 }
Friends And Related Function Documentation
friend class error_handler_base friend
Definition at line 81 of file error_handler.hpp.
Member Data Documentation
unsigned error_context_body::m_depth private
Definition at line 90 of file error_handler.hpp.
Referenced by pop(), and set().
error_handler_base* error_context_body::m_handler private
Definition at line 91 of file error_handler.hpp.
Referenced by pop(), and set().
The documentation for this class was generated from the following files:
include/stlplus/error_handler.hpp
include/stlplus/error_handler.cpp