Visible: rcEngineMovieCapture Class Reference
rcEngineMovieCapture Class Reference
#include <include/visiCore/rc_engineimplcapture.h>
Public Member Functions
rcEngineMovieCapture (rcEngineImpl *engine, rcVideoCaptureCtrl &captureCtrl, const rcMovieSaveCtrlReader &saveCtrl, rcEngineObserver *observer)
virtual ~rcEngineMovieCapture ()
const rcVideoCaptureStatusReader & captureStatus () const
uint32 delayLeft ()
rcMovieFileState saveState ()
void saveReset ()
virtual void run ()
Public Member Functions inherited from rcRunnable
rcRunnable ()
virtual ~rcRunnable ()
void requestSeppuku ()
void clearSeppuku ()
Static Public Attributes
static const uint32 _bufRingSz = 5
Private Member Functions
rcCameraGrabber * createGrabber ()
bool initializeCamera (rcCameraGrabber &grabber, char *&errorString, bool &allocError)
bool getCameraState (rcCameraGrabber &grabber)
bool updateCameraSettings (rcCameraGrabber &grabber)
void sendShutdown (rcCameraGrabber &grabber)
void startSaveThread ()
void closeSaveFile ()
void saveComplete ()
void killSaveThread ()
Private Attributes
vector< rcSharedFrameBufPtr > _frameBufPtrs
rcBidirectionalRing
< rcSharedFrameBufPtr > _saveRing
rcConditionVariable _buffersInTransmit
rcAtomicValue< rcMovieFileErr > _saveStatus
rcThread * _saveThread
rcMutex _saverMutex
rcEngineMovieSaver * _movieSaver
rcEngineImpl * _engine
rcVideoCaptureCtrl & _captureCtrl
rcVideoCaptureStatus _captureStatus
const rcMovieSaveCtrlReader & _saveCtrl
rcEngineObserver * _observer
rcAcqInfo _acqInfo
rcAcqControl _acqControl
rcAcqControl _acqSavedControl
Additional Inherited Members
Protected Member Functions inherited from rcRunnable
bool seppukuRequested ()
Detailed Description
Definition at line 25 of file rc_engineimplcapture.h.
Constructor & Destructor Documentation
rcEngineMovieCapture::rcEngineMovieCapture (rcEngineImpl * engine, rcVideoCaptureCtrl & captureCtrl, const rcMovieSaveCtrlReader & saveCtrl, rcEngineObserver * observer)
Definition at line 167 of file rc_engineimplcapture.cpp.
References _acqControl, _acqInfo, _engine, _frameBufPtrs, _observer, _saveRing, rcAcqInfo::acqState, rcAcqControl::binning, rcAcqControl::decimationRate, rcAcqControl::doAcquire, rcAcqControl::doShutdown, FALSE, rcAcqControl::gain, rcAcqFullResXY, rcAcqUnknown, rcBidirectionalRing< T >::releaseResource(), rcAcqControl::resolution, rmAssert, and rcAcqControl::shutter.
         : _frameBufPtrs(_bufRingSz), _saveRing(_bufRingSz), _buffersInTransmit(0),
           _saveStatus(eMovieFileErr_NoErr), _saveThread(0), _movieSaver(0),
           _engine(engine), _captureCtrl(captureCtrl), _saveCtrl(saveCtrl),
           _observer(observer)
 {
     rmAssert(_engine);
     rmAssert(_observer);
     for (uint32 i = 0; i < _frameBufPtrs.size(); i++) {
         bool status = _saveRing.releaseResource(&_frameBufPtrs[i]);
         rmAssert(status == true);
     }
     // set default acq control values
     _acqControl.doAcquire = FALSE;
     _acqControl.resolution = rcAcqFullResXY;
     _acqControl.doShutdown = 0;
     _acqControl.gain = 0;
     _acqControl.shutter = 0;
     _acqControl.binning = 1;
     _acqControl.decimationRate = 1;
     // set default acq info values
     _acqInfo.acqState = rcAcqUnknown; // Ignore other fields until this is valid
 }
virtual rcEngineMovieCapture::~rcEngineMovieCapture () inline virtual
Definition at line 32 of file rc_engineimplcapture.h.
 {}
Member Function Documentation
const rcVideoCaptureStatusReader& rcEngineMovieCapture::captureStatus () const inline
Definition at line 37 of file rc_engineimplcapture.h.
References _captureStatus.
Referenced by rcEngineImpl::getAttributes(), rcEngineImpl::getSettingValue(), and rcEngineImpl::setSettingValue().
   { return _captureStatus; }
void rcEngineMovieCapture::closeSaveFile () private
Definition at line 569 of file rc_engineimplcapture.cpp.
References _acqInfo, _buffersInTransmit, _bufRingSz, _movieSaver, _saveRing, _saveThread, rcBidirectionalRing< T >::availReleasedResources(), eMovieFileErr_NoErr, eMovieFileState_Save, rcMovieSaveStatusReader::getState(), rcMovieSaveStatusReader::getStatus(), rcBidirectionalRing< T >::giveResource(), rcConditionVariable::incrementVariable(), rcBidirectionalRing< T >::recoverResource(), rmAssert, rcEngineMovieSaver::saveStatus(), rcEngineMovieSaver::updateAcqInfo(), and rcConditionVariable::waitUntilLessThan().
Referenced by run().
 {
     rmAssert(_saveThread);
     rmAssert(_movieSaver);
     /* If movie save is still proceeding without error, send out NULL
      * frame to inform save thread that the movie is complete.
      */
     if ((_movieSaver->saveStatus().getStatus() == eMovieFileErr_NoErr) &&
         (_movieSaver->saveStatus().getState() == eMovieFileState_Save)) {
         if (_saveRing.availReleasedResources() == 0) {
             _buffersInTransmit.waitUntilLessThan(_bufRingSz);
             rmAssert(_saveRing.availReleasedResources());
         }
         // Update acquisition info so cam header will use up-to-date
         // camera settings
         _movieSaver->updateAcqInfo( _acqInfo );
         rcSharedFrameBufPtr* sbp = _saveRing.recoverResource();
         rmAssert(sbp);
         *sbp = 0; // Send NULL frame as signal that movie is done
         bool retval = _saveRing.giveResource(sbp);
         rmAssert(retval == true);
         _buffersInTransmit.incrementVariable(1, 0);
     }
 }
rcCameraGrabber * rcEngineMovieCapture::createGrabber () private
Definition at line 229 of file rc_engineimplcapture.cpp.
References _acqInfo, _observer, rcAcqInfo::acqState, rcFrameGrabber::getErrorString(), rcFrameGrabber::getInputSourceName(), rcFrameGrabber::getLastError(), rcFrameGrabber::isValid(), rcEngineObserver::notifyStatus(), rcAcqDisabled, rcPixel32, and rcPixel8.
Referenced by run().
 {
     rcCameraGrabber* grabber = 0;
 #ifdef rcSIMULATED_CAMERA
     // Hack to produce simulated dummy images
     // Create a grabber to produce random images
     // Gray
     grabber = new rcDummyCameraGrabber( 1024, 768, rcPixel8, 14.0 );
     // Color
     grabber = new rcDummyCameraGrabber( 320, 240, rcPixel32, 14.0 );
 #endif
     /* Creates and initializes both shared memory and shared
      * semaphores, and starts up child process RCQCAM.
      */
     grabber = new rcQVideoGrabber("RCDCAM", 0, 0,
                                   sizeof(rcVideoSharedMemLayout));
 #if 0
   /* Creates and initializes both shared memory and shared
      * semaphores, and starts up child process RCQCAM.
      */
     grabber = new rcQVideoGrabber("RCQTIME", 0, 0,
                                   sizeof(rcVideoSharedMemLayout));
 #endif
     /* Check for grabber creation failure
      */
     if (!grabber) {
         strstream s;
         s << "Grabber creation error: Out of memory error\n" << ends;
         _observer->notifyStatus(s.str());
         cerr << s;
         s.freeze(false); // Without freeze(), strstream::str() leaks
         // the string it returns
         return 0;
     }
     else if (!grabber->isValid()) {
         strstream s;
         s << rcFrameGrabber::getErrorString( grabber->getLastError() )
           << " for " << grabber->getInputSourceName() << ends;
         _observer->notifyStatus(s.str());
         cerr << s;
         s.freeze(false); // Without freeze(), strstream::str() leaks
         // the string it returns
         delete grabber;
         _acqInfo.acqState = rcAcqDisabled;
         return 0;
     }
     return grabber;
 }
uint32 rcEngineMovieCapture::delayLeft ()
Definition at line 197 of file rc_engineimplcapture.cpp.
References _movieSaver, _saverMutex, rcMovieSaveStatusReader::getDelayLeft(), and rcEngineMovieSaver::saveStatus().
Referenced by rcEngineImpl::processCapturedData().
 {
     rcLock lock(_saverMutex);
     if (_movieSaver == 0)
         return 0;
     return _movieSaver->saveStatus().getDelayLeft();
 }
bool rcEngineMovieCapture::getCameraState (rcCameraGrabber & grabber) private
Definition at line 388 of file rc_engineimplcapture.cpp.
References _acqInfo, eFrameStatusError, eFrameStatusOK, rcCameraGrabber::getAcqInfo(), rcFrameGrabber::getErrorString(), and rcFrameGrabber::getLastError().
Referenced by run().
 {
     rcFrameGrabberStatus status;
     if ((status = grabber.getAcqInfo(_acqInfo, true, false)) != eFrameStatusOK) {
         char* errorString;
         if (status == eFrameStatusError)
             errorString = "Error accessing shared memory, error %s\n";
         else
             errorString = "Unknown error getting acq info, error %s\n";
         fprintf(stderr, errorString,
                 rcFrameGrabber::getErrorString(grabber.getLastError()).data());
         return false;
     }
     return true;
 }
bool rcEngineMovieCapture::initializeCamera (rcCameraGrabber & grabber, char *& errorString, bool & allocError) private
Definition at line 291 of file rc_engineimplcapture.cpp.
References _acqControl, _acqInfo, _bufRingSz, _captureCtrl, rcAcqInfo::acqCtrlUpdateID, rcAcqControl::acqCtrlUpdateID, rcAcqInfo::acqState, rcCameraGrabber::addBuffer(), rcVideoCaptureCtrl::binning(), rcAcqControl::binning, rcAcqInfo::cameraPixelDepth, rcAcqInfo::ctrlFlags, rcAcqInfo::curBinning, rcAcqInfo::curDecimationRate, rcAcqInfo::curGain, rcAcqInfo::curShutter, rcAcqControl::decimationRate, rcAcqControl::doAcquire, rcAcqControl::doShutdown, eFrameStatusError, eFrameStatusOK, rcVideoCaptureCtrl::gain(), rcAcqControl::gain, rcCameraGrabber::getAcqInfo(), rcFrameGrabber::getErrorString(), rcFrameGrabber::getLastError(), rcFrame::initGrayColorMap(), rcAcqInfo::maxFrameHeight, rcAcqInfo::maxFrameWidth, rcAcqDisabled, rcAcqFullResXY, rcCTRLFLAGS_ERRLIC, rcPixel16, rcPixel8, rcAcqControl::resolution, rfFillColorMap(), rcCameraGrabber::setAcqControl(), rcVideoCaptureCtrl::shutter(), and rcAcqControl::shutter.
Referenced by run().
 {
     errorString = 0;
     allocError = false;
     rcFrameGrabberStatus status;
     // Get the initial camera state
     //
     if ((status = grabber.getAcqInfo(_acqInfo, true, false)) !=
         eFrameStatusOK) { // Figure out error message
         if (status == eFrameStatusError)
             errorString = "Error accessing shared memory, error %s\n";
         else
             errorString = "Unknown error getting acq info, error %s\n";
     }
     else if (_acqInfo.acqState == rcAcqDisabled) {
         if ( _acqInfo.ctrlFlags & rcCTRLFLAGS_ERRLIC )
             errorString = "No DCAM license installed for this host\n";
         else
             errorString = "Couldn't initialize camera\n";
         status = eFrameStatusError;
     }
     else { // Set up initial camera settings and start acquiring
         // Only 8-bit gray is supported now
         if ( _acqInfo.cameraPixelDepth != rcPixel8 ) {
             errorString = "Warning: camera does not support 8-bit monochrome mode\n";
             fprintf(stderr, errorString );
             //return false;
         }
         /* Pre-allocate frame buffers to be used.
          */
         for (uint32 i = 0; i < _bufRingSz; i++) {
             rcSharedFrameBufPtr bufP = new rcFrame(_acqInfo.maxFrameWidth,
                                                     _acqInfo.maxFrameHeight,
                                                     _acqInfo.cameraPixelDepth);
             if (!bufP) {
                 errorString = "Not enough memory available to allocate frame buffers\n";
                 allocError = true;
                 return false;
             }
             /* As an extra effort to make sure everything is set before
              * starting to accept frames, touch one pixel in each row
              * to make sure all the frames have actual been loaded into
              * memory.
             for (uint32 y = 0; y < _acqInfo.maxFrameHeight; y++)
                 bufP->setPixel(0, y, 0);
              */
             if ( _acqInfo.cameraPixelDepth == rcPixel8) {
                 bufP->initGrayColorMap();
             } else if ( _acqInfo.cameraPixelDepth == rcPixel16)
                 rfFillColorMap(0, bufP);
             grabber.addBuffer(bufP);
         }
         _acqControl.gain = _acqInfo.curGain;
         _acqControl.shutter = _acqInfo.curShutter;
             _acqControl.binning = _acqInfo.curBinning;
         _captureCtrl.gain( _acqControl.gain );
         _captureCtrl.shutter( _acqControl.shutter );
             _captureCtrl.binning ( _acqControl.binning);
         _acqControl.doShutdown = 0;
         _acqControl.resolution = rcAcqFullResXY;
         _acqControl.decimationRate = _acqInfo.curDecimationRate;
         _acqControl.acqCtrlUpdateID = _acqInfo.acqCtrlUpdateID+1;
         _acqControl.doAcquire = true;
         if ((status = grabber.setAcqControl(_acqControl, false, true)) !=
             eFrameStatusOK) { // Figure out error messsage
             if (status == eFrameStatusError)
                 errorString = "Error accessing shared memory, error %s\n";
             else
                 errorString = "Unknown error setting acq control, error %s\n";
         }
     } // End of: if (status == eFrameStatusOK)
     if (eFrameStatusOK == status)
         return true;
     fprintf(stderr, errorString,
             &(rcFrameGrabber::getErrorString(grabber.getLastError()))[0]);
     return false;
 }
void rcEngineMovieCapture::killSaveThread () private
Definition at line 620 of file rc_engineimplcapture.cpp.
References _movieSaver, _saverMutex, _saveThread, eMovieFileState_Delay, eMovieFileState_Done, eMovieFileState_Uninitialized, eMovieFileState_Wait, endl(), rcMovieSaveStatusReader::getState(), rcThread::join(), rmAssert, and rcEngineMovieSaver::saveStatus().
Referenced by run().
 {
     rmAssert(_saveThread);
     rmAssert(_movieSaver);
     rcMovieFileState state = _movieSaver->saveStatus().getState();
     while (state == eMovieFileState_Uninitialized) {
         usleep(1);
         state = _movieSaver->saveStatus().getState();
     }
     rmAssert((state == eMovieFileState_Done) || (state == eMovieFileState_Wait) ||
              (state == eMovieFileState_Delay));
     /* Now wait for save thread to finish writing movie file
      * and return.
      */
     int status = _saveThread->join();
     if (status)
         cout << "save thread join error " << status << endl;
     else
         cout << "save thread join OK" << endl;
     delete _saveThread;
     _saveThread = 0;
     {
         rcLock lock(_saverMutex);
         delete _movieSaver;
         _movieSaver = 0;
     }
 }
void rcEngineMovieCapture::run (void) virtual
Implements rcRunnable.
Definition at line 654 of file rc_engineimplcapture.cpp.
References _acqInfo, _buffersInTransmit, _captureCtrl, _captureStatus, _engine, _movieSaver, _observer, _saveRing, _saveThread, rcAcqInfo::acqState, rcBidirectionalRing< T >::availReleasedResources(), rcAcqInfo::cameraInfo, rcAcqInfo::cameraPixelDepth, rcVideoCaptureStatus::captureDepth(), rcVideoCaptureStatus::captureRect(), closeSaveFile(), cMaxSaveFrameCount, createGrabber(), rcAcqInfo::curDecimationRate, rcAcqInfo::curResolution, eAnalyzerFullCorrelation, eEngineStopped, eFrameStatusEOF, eFrameStatusOK, eMovieFileState_Done, eMovieFileState_Save, eVideoCaptureState_MovieClose, eVideoCaptureState_MovieSave, eVideoCaptureState_MovieWait, eVideoCaptureState_Uninitialized, rcAnalyzerResult::frameBuf(), rcEngineImpl::frameInterrupt(), getCameraState(), rcVideoCaptureStatusReader::getCaptureRect(), rcMovieSaveStatusReader::getCaptureTime(), rcVideoCaptureCtrlReader::getEntropyDefinition(), rcFrameGrabber::getErrorString(), rcFrameGrabber::getLastError(), rcVideoCaptureCtrlReader::getSlidingWindowOrigin(), rcVideoCaptureCtrlReader::getSlidingWindowSize(), rcMovieSaveStatusReader::getState(), rcEngineImpl::getState(), rcBidirectionalRing< T >::giveResource(), rcRectangle< T >::height(), rcConditionVariable::incrementVariable(), initializeCamera(), killSaveThread(), rcTimestamp::localtime(), rcAcqInfo::maxFrameHeight, rcAcqInfo::maxFramesPerSecond, rcVideoCaptureStatus::maxFramesPerSecond(), rcAcqInfo::maxFrameWidth, rcAcqInfo::missedFrames, rcMovieFileCamExt::name(), rcEngineObserver::notifyAnalysisRect(), rcEngineObserver::notifyError(), rcEngineObserver::notifyMultiplier(), rcEngineObserver::notifyStatus(), rcEngineObserver::notifyVideoRect(), rcTimestamp::now(), rcAcqDisabled, rcAcqHalfResXY, rcAcqUnknown, rcBidirectionalRing< T >::recoverResource(), rmAssert, saveComplete(), rcEngineMovieSaver::saveStatus(), sendShutdown(), rcRunnable::seppukuRequested(), rcEngineImpl::setCameraInfo(), rcCameraGrabber::setFrameCount(), rcEngineImpl::setFrameSize(), rcEngineImpl::start(), rcEngineImpl::startPreview(), startSaveThread(), rcEngineImpl::stop(), updateCameraSettings(), and rcRectangle< T >::width().
 {
     char* errorString = 0;
     rcCameraGrabber* grabber = createGrabber();
     /* Init counters to track how many frames were lost because the
      * capture thread couldn't process them fast enough vs how many
      * were lost because the movie save thread couldn't save them
      * fast enough.
      */
     uint32 missedFramesCurValue = 0;
     uint32 missedFramesOnCapture = 0;
     uint32 missedFramesOnSave = 0;
     if (grabber) {
         _observer->notifyStatus( "Initializing camera..." );
         bool allocError;
         if (initializeCamera(*grabber, errorString, allocError)) {
             rcVideoCaptureState captureState = eVideoCaptureState_Uninitialized;
             startSaveThread();
             _observer->notifyStatus( "Initializing camera...OK" );
             rsCorrParams corrParams;
             // Analyzer options
             rcAnalyzerOptions startOpt(corrParams,
                                        eAnalyzerFullCorrelation,
                                        _captureCtrl.getSlidingWindowOrigin(),
                                        _captureStatus.getCaptureRect(),
                                        _captureCtrl.getSlidingWindowSize(),
                                        _captureCtrl.getEntropyDefinition(),
                                        _acqInfo.cameraPixelDepth);
             // Create an analyzer
             rcAnalyzer analyzer(startOpt, *grabber);
             rcFrameGrabberStatus status = eFrameStatusOK;
             std::string cameraStatus;
             // Loop until grabber is exhausted or engine is shut down
             while (!seppukuRequested() && (_acqInfo.acqState != rcAcqDisabled)) {
                 /* Read the current camera state info into _acqInfo.
                  */
                 if (!getCameraState(*grabber)) {
                     _acqInfo.acqState = rcAcqDisabled;
                     break;
                 }
                 if ((captureState == eVideoCaptureState_MovieSave) &&
                     (missedFramesCurValue != _acqInfo.missedFrames)) {
                     rmAssert(_acqInfo.missedFrames > missedFramesCurValue);
                     missedFramesOnCapture += _acqInfo.missedFrames - missedFramesCurValue;
                     missedFramesCurValue = _acqInfo.missedFrames;
                 }
                 if (captureState == eVideoCaptureState_Uninitialized) {
                     captureState = eVideoCaptureState_MovieWait;
                     rcRect videoRect(0, 0, _acqInfo.maxFrameWidth,
                                      _acqInfo.maxFrameHeight);
                     if (_acqInfo.curResolution == rcAcqHalfResXY)
                         videoRect = rcRect(0, 0, _acqInfo.maxFrameWidth/2,
                                            _acqInfo.maxFrameHeight/2);
                     _captureStatus.captureRect(videoRect);
                     _captureStatus.captureDepth(_acqInfo.cameraPixelDepth);
                     _captureStatus.maxFramesPerSecond(_acqInfo.maxFramesPerSecond);
                     _observer->notifyVideoRect(videoRect);
                     _observer->notifyAnalysisRect(videoRect);
                     _engine->setFrameSize(videoRect.width(), videoRect.height(), _acqInfo.cameraPixelDepth);
                     _observer->notifyMultiplier(1000/_acqInfo.maxFramesPerSecond);
                     rcAnalyzerOptions newOpt(corrParams,
                                              eAnalyzerFullCorrelation,
                                              _captureCtrl.getSlidingWindowOrigin(),
                                              _captureStatus.getCaptureRect(),
                                              _captureCtrl.getSlidingWindowSize(),
                                              _captureCtrl.getEntropyDefinition(),
                                              _acqInfo.cameraPixelDepth);
                     if (newOpt != startOpt) {
                         analyzer.setOptions(newOpt);
                     }
                     /* Format string to show on status line. First, make sure string
                      * is null terminated.
                      */
                     std::string cameraName = std::string(_acqInfo.cameraInfo.name());
                     cameraStatus = std::string("Camera: ") + cameraName +
                         std::string("    Action: ");
                     // Write camera info header
                     _engine->setCameraInfo( _acqInfo.cameraInfo );
                     // Start preview track
                     _engine->startPreview();
                 }
                 /* When we first detect that the movie saver thread has
                  * entered the "save" state we want to start sending frames
                  * to the movie saver. Initialize the grabber's frame
                  * capture count and set the "saving movie" state variable
                  * to true.
                  */
                 if ((captureState == eVideoCaptureState_MovieWait) &&
                     (_movieSaver->saveStatus().getState() == eMovieFileState_Save)) {
                     uint32 captureTime = _movieSaver->saveStatus().getCaptureTime();
                     // cMaxSaveFrameCount sets the ultimate upper limit for
                     // number of captured frames
                     if (captureTime) {
                         uint32 frameCaptureCount =
                             (uint32)(((captureTime*_acqInfo.maxFramesPerSecond)/
                                         _acqInfo.curDecimationRate) + .4999);
                         if ( frameCaptureCount > cMaxSaveFrameCount-1 )
                             frameCaptureCount = cMaxSaveFrameCount-1;
                         grabber->setFrameCount(frameCaptureCount);
                     } else
                         grabber->setFrameCount(cMaxSaveFrameCount-1);
                     missedFramesCurValue = _acqInfo.missedFrames;
                     missedFramesOnCapture = missedFramesOnSave = 0;
                     captureState = eVideoCaptureState_MovieSave;
                 } // End of: if ((captureState == eVideoCaptureState_MovieWait) && ...)
                 /* See if frame grabber settings need to be changed, but only
                  * if we aren't currently saving a movie.
                  */
                 if ((captureState == eVideoCaptureState_MovieWait) &&
                     !updateCameraSettings(*grabber)) {
                     _acqInfo.acqState = rcAcqDisabled;
                     break;
                 }
                 if ((captureState == eVideoCaptureState_MovieSave) &&
                     (_engine->getState() == eEngineStopped)) {
                     rcTimestamp now = rcTimestamp::now();
                     fprintf(stderr, "Capture stopped at %s\n",
                             now.localtime().c_str());
                     grabber->setFrameCount(-1);
                     closeSaveFile();
                     captureState = eVideoCaptureState_MovieClose;
                 }
                 rcAnalyzerResult result;
                 status = analyzer.getNextResult(result, true);
                 if (status == eFrameStatusOK) {
                     /* If movie save is active handle this activity first
                      */
                     bool frameSaved = false; // Has this frame been saved to disk
                     if ((captureState == eVideoCaptureState_MovieSave) &&
                         result.frameBuf()) {
                         if (_movieSaver->saveStatus().getState() != eMovieFileState_Save) {
                             rcTimestamp now = rcTimestamp::now();
                             fprintf(stderr, "Movie saver aborted at %s\n",
                                     now.localtime().c_str());
                             grabber->setFrameCount(-1);
                             closeSaveFile();
                             captureState = eVideoCaptureState_MovieClose;
                         }
                         else if (_saveRing.availReleasedResources() != 0) {
                             rcSharedFrameBufPtr* sbp = _saveRing.recoverResource();
                             rmAssert(sbp);
                             *sbp = result.frameBuf();
                             bool retval = _saveRing.giveResource(sbp);
                             rmAssert(retval == true);
                             _buffersInTransmit.incrementVariable(1, 0);
                             frameSaved = true;
                         }
                         else
                             missedFramesOnSave++;
                     } // End of: if ((captureState==eVideoCaptureState_MovieSave) && ...
                     /* Now give analyzer and GUI a chance to process result
                      */
                     uint32 missedFrames = _acqInfo.missedFrames;
                     if (captureState == eVideoCaptureState_MovieSave)
                         missedFrames = missedFramesOnCapture;
                     _engine->frameInterrupt(result, cameraStatus, missedFrames,
                                             missedFramesOnSave, frameSaved);
                     // Set new options if applicable
                     rcAnalyzerOptions newOpt(corrParams,
                                              eAnalyzerFullCorrelation,
                                              _captureCtrl.getSlidingWindowOrigin(),
                                              _captureStatus.getCaptureRect(),
                                              _captureCtrl.getSlidingWindowSize(),
                                              _captureCtrl.getEntropyDefinition(),
                                              _acqInfo.cameraPixelDepth );
                     if (newOpt != analyzer.getOptions() ) {
                         analyzer.setOptions(newOpt);
                     }
                 }
                 else if (status == eFrameStatusEOF) {
                     rcTimestamp now = rcTimestamp::now();
                     fprintf(stderr, "Grabber reached EOF at %s\n",
                             now.localtime().c_str());
                     grabber->setFrameCount(-1);
                     analyzer.reset();
                     closeSaveFile();
                     captureState = eVideoCaptureState_MovieClose;
                 }
                 else {
                     rcTimestamp now = rcTimestamp::now();
                     fprintf(stderr, "Got some other error at %s\n",
                             now.localtime().c_str());
                     grabber->setFrameCount(-1);
                     closeSaveFile();
                     captureState = eVideoCaptureState_MovieClose;
                     rcFrameGrabberError error = analyzer.getLastError();
                     _observer->notifyError(rcFrameGrabber::getErrorString(error).c_str());
                     break; // Bail out of while loop
                 } // End of: if (status == eFrameStatusOK) ...
                 //         else if (status == eFrameStatusEOF) ... else ...
                 /* Wait until movie saver says it is done before cleaning up shared
                  * ring.
                  */
                 if ((captureState == eVideoCaptureState_MovieClose) &&
                     (_movieSaver->saveStatus().getState() == eMovieFileState_Done)) {
                     saveComplete();
                     captureState = eVideoCaptureState_MovieWait;
                 }
             } //End of: while (!seppukuRequested()&&(_acqInfo.acqState!=rcAcqDisabled))
             /* Before returning make sure that any pending movie save has a
              * chance to complete.
              */
             if ((captureState == eVideoCaptureState_MovieSave)) {
                 closeSaveFile();
                 captureState = eVideoCaptureState_MovieClose;
             }
             if (captureState == eVideoCaptureState_MovieClose) {
                 while (_movieSaver->saveStatus().getState() != eMovieFileState_Done)
                     usleep(10000); // sleep 10ms
                 saveComplete();
                 captureState = eVideoCaptureState_MovieWait;
             }
             killSaveThread();
         } else { // Error initing camera
             rmAssert(errorString);
             std::string eMsg = "";
             if (!allocError)
                 std::string eMsg = rcFrameGrabber::getErrorString(grabber->getLastError());
             const size_t blen = 256;
             char buf[blen];
             snprintf(buf, blen, errorString, eMsg.c_str());
             eMsg = std::string(buf);
             fprintf(stderr, "%s", eMsg.c_str());
             _engine->start(); _engine->stop();
             if (allocError)
                 _observer->notifyStatus("Cannot Initialize Camera");
             else
                 _observer->notifyStatus("No Camera");
             _observer->notifyError(eMsg.c_str());
             _acqInfo.acqState = rcAcqDisabled;
         } // End of: if (initializeCamera(*grabber)) ... else // Error initing camera
     } else { // Grabber creation failure
         _acqInfo.acqState = rcAcqDisabled;
     }
     rmAssert(!_saveThread);
     rmAssert(!_movieSaver);
     if (_acqInfo.acqState != rcAcqDisabled)
         sendShutdown(*grabber);
     delete grabber;
     _acqInfo.acqState = rcAcqUnknown;
 }
void rcEngineMovieCapture::saveComplete () private
Definition at line 597 of file rc_engineimplcapture.cpp.
References _buffersInTransmit, _movieSaver, _saveRing, rcBidirectionalRing< T >::availNewResources(), rcConditionVariable::decrementVariable(), eMovieFileErr_NoErr, eMovieFileState_Done, rcMovieSaveStatusReader::getState(), rcMovieSaveStatusReader::getStatus(), rcBidirectionalRing< T >::releaseResource(), rmAssert, rcEngineMovieSaver::saveStatus(), and rcBidirectionalRing< T >::takeResource().
Referenced by run().
 {
     rmAssert(_movieSaver->saveStatus().getState() == eMovieFileState_Done);
     /* If an error happened during save process, some frames may
      * still be in transit. Clear these out.
      */
     if (_movieSaver->saveStatus().getStatus() != eMovieFileErr_NoErr) {
         rcSharedFrameBufPtr* sbp;
         while (_saveRing.availNewResources()) {
             sbp = _saveRing.takeResource();
             rmAssert(sbp);
             *sbp = 0; // Free resource
             bool retval = _saveRing.releaseResource(sbp);
             rmAssert(retval);
             _buffersInTransmit.decrementVariable(1, -1);
         }
     }
 }
void rcEngineMovieCapture::saveReset ()
Definition at line 217 of file rc_engineimplcapture.cpp.
References _movieSaver, _saverMutex, eMovieFileState_Done, rcMovieSaveStatusReader::getState(), rcEngineMovieSaver::reset(), and rcEngineMovieSaver::saveStatus().
Referenced by rcEngineImpl::unlockedReset().
 {
     rcLock lock(_saverMutex);
     if (_movieSaver &&
         (_movieSaver->saveStatus().getState() == eMovieFileState_Done))
         _movieSaver->reset();
 }
rcMovieFileState rcEngineMovieCapture::saveState ()
Definition at line 207 of file rc_engineimplcapture.cpp.
References _movieSaver, _saverMutex, eMovieFileState_Uninitialized, rcMovieSaveStatusReader::getState(), and rcEngineMovieSaver::saveStatus().
Referenced by rcEngineImpl::frameInterrupt(), rcEngineImpl::getAttributes(), rcEngineImpl::isSettingEditable(), and rcEngineImpl::storingLiveInput().
 {
     rcLock lock(_saverMutex);
     if (_movieSaver == 0)
         return eMovieFileState_Uninitialized;
     return _movieSaver->saveStatus().getState();
 }
void rcEngineMovieCapture::sendShutdown (rcCameraGrabber & grabber) private
Definition at line 510 of file rc_engineimplcapture.cpp.
References _acqControl, rcAcqControl::acqCtrlUpdateID, rcAcqControl::doShutdown, eFrameStatusError, eFrameStatusOK, rcFrameGrabber::getErrorString(), rcFrameGrabber::getLastError(), and rcCameraGrabber::setAcqControl().
Referenced by run().
 {
     _acqControl.doShutdown = 1;
     _acqControl.acqCtrlUpdateID++;
     rcFrameGrabberStatus status;
     if ((status = grabber.setAcqControl(_acqControl, true, true))
         != eFrameStatusOK) {
         char* errorString;
         if (status == eFrameStatusError)
             errorString = "Error accessing shared memory, error %s\n";
         else
             errorString = "Unknown error setting acq control, error %s\n";
         fprintf(stderr, errorString,
                 rcFrameGrabber::getErrorString(grabber.getLastError()).c_str());
     }
 }
void rcEngineMovieCapture::startSaveThread () private
Definition at line 537 of file rc_engineimplcapture.cpp.
References _acqInfo, _buffersInTransmit, _engine, _frameBufPtrs, _movieSaver, _observer, _saveCtrl, _saveRing, _saverMutex, _saveThread, rcBidirectionalRing< T >::availNewResources(), rcBidirectionalRing< T >::availNewSlots(), rcBidirectionalRing< T >::availReleasedResources(), rcBidirectionalRing< T >::availReleasedSlots(), rcConditionVariable::decrementVariable(), eHighPriority, rmAssert, rcThread::setPriority(), and rcThread::start().
Referenced by run().
 {
     /* Validate initial state.
      */
     rmAssert(!_saveThread);
     rmAssert(!_movieSaver);
     rmAssert(_saveRing.availReleasedResources() == _frameBufPtrs.size());
     rmAssert(_saveRing.availNewSlots() == _frameBufPtrs.size());
     rmAssert(_saveRing.availReleasedSlots() == 0);
     rmAssert(_saveRing.availNewResources() == 0);
     rmAssert(_buffersInTransmit.decrementVariable(0, -1) == 0);
     for (uint32 i = 0; i < _frameBufPtrs.size(); i++)
         rmAssert(!_frameBufPtrs[i]); // Make sure its currently NULL
     /* Set up and start save thread.
      */
     {
         rcLock lock(_saverMutex);
         _movieSaver = new rcEngineMovieSaver(_engine, _saveCtrl, _acqInfo, _observer,
                                              _saveRing, _buffersInTransmit);
     }
     rmAssert(_movieSaver);
     _saveThread = new rcThread(_movieSaver);
     rmAssert(_saveThread);
     _saveThread->setPriority(eHighPriority);
     _saveThread->start();
 }
bool rcEngineMovieCapture::updateCameraSettings (rcCameraGrabber & grabber) private
Definition at line 449 of file rc_engineimplcapture.cpp.
References _acqControl, _acqInfo, _acqSavedControl, _captureCtrl, _observer, rcVideoCaptureCtrl::binning(), rcAcqInfo::ctrlFlags, eFrameStatusError, eFrameStatusOK, rcVideoCaptureCtrl::gain(), rcFrameGrabber::getErrorString(), rcFrameGrabber::getLastError(), rcEngineObserver::notifyExperimentChange(), rcCTRLFLAGS_ERRBINNING, rcCTRLFLAGS_ERRCTRL, rcCTRLFLAGS_ERRGAIN, rcCTRLFLAGS_ERRSHUTTER, rcCameraGrabber::setAcqControl(), rcVideoCaptureCtrl::shutter(), and updateControl().
Referenced by run().
 {
     rcFrameGrabberStatus status;
     if (_acqInfo.ctrlFlags & rcCTRLFLAGS_ERRCTRL) {
         fprintf(stderr, "Failed acq ctrl: status 0x%X\n", _acqInfo.ctrlFlags);
 #ifdef IMPL_DEBUG_LOG
         cerr << "CurCtrl: " << _acqControl;
         cerr << "SavedCtrl: " << _acqSavedControl;
 #endif
         // Control error, restore old values
         if ( _acqInfo.ctrlFlags & rcCTRLFLAGS_ERRSHUTTER ) {
             _captureCtrl.shutter( _acqSavedControl.shutter );
             _acqControl.shutter = _acqSavedControl.shutter;
             _observer->notifyExperimentChange();
         }
         if ( _acqInfo.ctrlFlags & rcCTRLFLAGS_ERRGAIN ) {
             _captureCtrl.gain( _acqSavedControl.gain );
             _acqControl.gain = _acqSavedControl.gain;
             _observer->notifyExperimentChange();
         }
         if ( _acqInfo.ctrlFlags & rcCTRLFLAGS_ERRBINNING ) {
             _captureCtrl.binning( _acqSavedControl.binning);
             _acqControl.binning = _acqSavedControl.binning;
             _observer->notifyExperimentChange();
         }
     }
     // If the user wants to change something and the last update
     // has been handled, send out a new update.
     //
     // Save old values
     _acqSavedControl = _acqControl;
     if ( updateControl( _captureCtrl, _acqInfo, _acqControl ) ) {
         if ((status = grabber.setAcqControl(_acqControl, false, false))
             != eFrameStatusOK) {
             char* errorString;
             if (status == eFrameStatusError)
                 errorString = "Error accessing shared memory, error %s\n";
             else
                 errorString = "Unknown error setting acq control, error %s\n";
             fprintf(stderr, errorString,
                     rcFrameGrabber::getErrorString(grabber.getLastError()).c_str());
             return false;
         }
     }
     return true;
 }
Member Data Documentation
rcAcqControl rcEngineMovieCapture::_acqControl private
Definition at line 96 of file rc_engineimplcapture.h.
Referenced by initializeCamera(), rcEngineMovieCapture(), sendShutdown(), and updateCameraSettings().
rcAcqInfo rcEngineMovieCapture::_acqInfo private
Definition at line 95 of file rc_engineimplcapture.h.
Referenced by closeSaveFile(), createGrabber(), getCameraState(), initializeCamera(), rcEngineMovieCapture(), run(), startSaveThread(), and updateCameraSettings().
rcAcqControl rcEngineMovieCapture::_acqSavedControl private
Definition at line 97 of file rc_engineimplcapture.h.
Referenced by updateCameraSettings().
rcConditionVariable rcEngineMovieCapture::_buffersInTransmit private
Definition at line 82 of file rc_engineimplcapture.h.
Referenced by closeSaveFile(), run(), saveComplete(), and startSaveThread().
const uint32 rcEngineMovieCapture::_bufRingSz = 5 static
Definition at line 60 of file rc_engineimplcapture.h.
Referenced by rcEngineMovieSaver::closeHdlr(), closeSaveFile(), rcEngineMovieSaver::error_cleanup(), initializeCamera(), and rcEngineMovieSaver::saveHdlr().
rcVideoCaptureCtrl& rcEngineMovieCapture::_captureCtrl private
Definition at line 91 of file rc_engineimplcapture.h.
Referenced by initializeCamera(), run(), and updateCameraSettings().
rcVideoCaptureStatus rcEngineMovieCapture::_captureStatus private
Definition at line 92 of file rc_engineimplcapture.h.
Referenced by captureStatus(), and run().
rcEngineImpl* rcEngineMovieCapture::_engine private
Definition at line 90 of file rc_engineimplcapture.h.
Referenced by rcEngineMovieCapture(), run(), and startSaveThread().
vector<rcSharedFrameBufPtr> rcEngineMovieCapture::_frameBufPtrs private
Definition at line 80 of file rc_engineimplcapture.h.
Referenced by rcEngineMovieCapture(), and startSaveThread().
rcEngineMovieSaver* rcEngineMovieCapture::_movieSaver private
Definition at line 87 of file rc_engineimplcapture.h.
Referenced by closeSaveFile(), delayLeft(), killSaveThread(), run(), saveComplete(), saveReset(), saveState(), and startSaveThread().
rcEngineObserver* rcEngineMovieCapture::_observer private
Definition at line 94 of file rc_engineimplcapture.h.
Referenced by createGrabber(), rcEngineMovieCapture(), run(), startSaveThread(), and updateCameraSettings().
const rcMovieSaveCtrlReader& rcEngineMovieCapture::_saveCtrl private
Definition at line 93 of file rc_engineimplcapture.h.
Referenced by startSaveThread().
rcBidirectionalRing<rcSharedFrameBufPtr> rcEngineMovieCapture::_saveRing private
Definition at line 81 of file rc_engineimplcapture.h.
Referenced by closeSaveFile(), rcEngineMovieCapture(), run(), saveComplete(), and startSaveThread().
rcMutex rcEngineMovieCapture::_saverMutex private
Definition at line 86 of file rc_engineimplcapture.h.
Referenced by delayLeft(), killSaveThread(), saveReset(), saveState(), and startSaveThread().
rcAtomicValue<rcMovieFileErr> rcEngineMovieCapture::_saveStatus private
Definition at line 83 of file rc_engineimplcapture.h.
rcThread* rcEngineMovieCapture::_saveThread private
Definition at line 84 of file rc_engineimplcapture.h.
Referenced by closeSaveFile(), killSaveThread(), run(), and startSaveThread().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplcapture.h
src/visible/src/rc_engineimplcapture.cpp