Visible: rcEngineImporter Class Reference
rcEngineImporter Class Reference
#include <include/visiCore/rc_engineimpl.h>
Public Member Functions
rcEngineImporter (rcEngineImpl *engine)
virtual void run ()
Public Member Functions inherited from rcRunnable
rcRunnable ()
virtual ~rcRunnable ()
void requestSeppuku ()
void clearSeppuku ()
Private Attributes
rcEngineImpl * _engine
Additional Inherited Members
Protected Member Functions inherited from rcRunnable
bool seppukuRequested ()
Detailed Description
Definition at line 87 of file rc_engineimpl.h.
Constructor & Destructor Documentation
rcEngineImporter::rcEngineImporter (rcEngineImpl * engine) inline
Definition at line 89 of file rc_engineimpl.h.
References rmAssert.
 : _engine( engine ) { rmAssert( engine ); };
Member Function Documentation
void rcEngineImporter::run (void) virtual
Implements rcRunnable.
Definition at line 1876 of file rc_engineimpl.cpp.
References _engine, rcEngineImpl::_exportImagesDir, rcEngineImpl::_inputSource, eImages, eMovie, rcEngineImpl::loadImages(), rcEngineImpl::loadMovie(), and rcEngineImpl::saveFrames().
 {
   if ( _engine ) {
     int inputSource = _engine->_inputSource;
     if ( inputSource == eImages)
       _engine->loadImages();
     else if ( inputSource == eMovie )
       _engine->loadMovie();
     // Save loaded images if we have been asked to
     _engine->saveFrames(_engine->_exportImagesDir);
   }
 }
Member Data Documentation
rcEngineImpl* rcEngineImporter::_engine private
Definition at line 95 of file rc_engineimpl.h.
Referenced by run().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimpl.h
src/visible/src/rc_engineimpl.cpp