Visible: rcBasicCorrRowFunc< T > Class Template Reference
rcBasicCorrRowFunc< T > Class Template Reference
#include <include/analysis/rc_rowfunc.h>
Public Member Functions
rcBasicCorrRowFunc (const rcWindow &srcA, const rcWindow &srcB, T &dummy)
rcBasicCorrRowFunc (rcCorrelationWindow< T > &srcA, rcCorrelationWindow< T > &srcB)
rcBasicCorrRowFunc (const T *baseA, const T *baseB, uint32 rupA, uint32 rupB, uint32 width, uint32 height)
virtual void prolog ()
virtual void rowFunc ()
virtual void areaFunc ()
void epilog (rcCorr &)
virtual ~rcBasicCorrRowFunc ()
template<>
void rowFunc ()
template<>
void epilog (rcCorr &res)
Public Member Functions inherited from rcRowFuncTwoSource< T >
rcRowFuncTwoSource ()
virtual ~rcRowFuncTwoSource ()
Private Member Functions
void setCache (const rcCorrelationWindow< T > &srcA, const rcCorrelationWindow< T > &srcB)
void rowFuncNoneCached ()
void rowFuncICached ()
void rowFuncMCached ()
void rowFuncIMCached ()
template<>
void rowFuncNoneCached ()
template<>
void rowFuncICached ()
template<>
void rowFuncMCached ()
template<>
void rowFuncIMCached ()
Private Attributes
rcCorr mRes
rcUIPair mRUP
rcCorrMomentsCached mCacheState
Additional Inherited Members
Protected Member Functions inherited from rcRowFuncTwoSource< T >
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
Static Protected Member Functions inherited from rcRowFuncTwoSource< T >
static bool checkAssigned (const rcWindow &, const rcWindow &)
Protected Attributes inherited from rcRowFuncTwoSource< T >
const T * mFirst
const T * mSecond
uint32 mWidth
uint32 mHeight
Detailed Description
template<class T>
class rcBasicCorrRowFunc< T >
Definition at line 116 of file rc_rowfunc.h.
Constructor & Destructor Documentation
template<class T > rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc (const rcWindow & srcA, const rcWindow & srcB, T & dummy)
Definition at line 305 of file rc_rowfunc.h.
References rcRowFuncTwoSource< T >::checkAssigned(), rcWindow::height(), rmAssertDebug, rmUnused, rcWindow::rowPointer(), rcWindow::size(), and rcWindow::width().
                                                                                                 :
 mRUP( srcA.rowUpdate () / sizeof (T), srcB.rowUpdate () / sizeof (T) ),
 mCacheState( eNone )
 {
   rmUnused (dummy);
   rcRowFuncTwoSource<T>::checkAssigned (srcB, srcA);
   rmAssertDebug (srcA.size() == srcB.size());
   rcRowFuncTwoSource<T>::mWidth = srcA.width();
   rcRowFuncTwoSource<T>::mHeight = srcB.height();
   rcRowFuncTwoSource<T>::mFirst = (T *) srcA.rowPointer(0);
   rcRowFuncTwoSource<T>::mSecond = (T *) srcB.rowPointer(0);
}
template<class T > rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc (rcCorrelationWindow< T > & srcA, rcCorrelationWindow< T > & srcB)
Definition at line 276 of file rc_rowfunc.h.
References rcRowFuncTwoSource< T >::checkAssigned(), rcWindow::height(), rmAssertDebug, rcWindow::rowPointer(), rcBasicCorrRowFunc< T >::setCache(), rcWindow::size(), rcWindow::width(), and rcCorrelationWindow< T >::window().
                                                                                                      :
 mRUP( srcA.rowUpdate () / sizeof (T), srcB.rowUpdate () / sizeof (T) )
 {
     const rcWindow& winA = srcA.window();
     const rcWindow& winB = srcB.window();
     rcRowFuncTwoSource<T>::checkAssigned (winB, winA);
     rmAssertDebug (winA.size() == winB.size());
     rcRowFuncTwoSource<T>::mWidth = winA.width();
     rcRowFuncTwoSource<T>::mHeight = winB.height();
     rcRowFuncTwoSource<T>::mFirst = (T *) winA.rowPointer(0);
     rcRowFuncTwoSource<T>::mSecond = (T *) winB.rowPointer(0);
     setCache( srcA, srcB );
}
template<class T > rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc (const T * baseA, const T * baseB, uint32 rupA, uint32 rupB, uint32 width, uint32 height)
Definition at line 293 of file rc_rowfunc.h.
                                                                         :
 mRUP( rowPelsA / sizeof (T), rowPelsB / sizeof (T) ),
 mCacheState( eNone )
 {
     rcRowFuncTwoSource<T>::mWidth = width;
     rcRowFuncTwoSource<T>::mHeight = height;
     rcRowFuncTwoSource<T>::mFirst = baseA;
     rcRowFuncTwoSource<T>::mSecond = baseB;
}
template<class T > rcBasicCorrRowFunc< T >::~rcBasicCorrRowFunc< T > () virtual
Definition at line 375 of file rc_rowfunc.h.
 {}
Member Function Documentation
template<class T > void rcBasicCorrRowFunc< T >::areaFunc () virtual
Implements rcRowFuncTwoSource< T >.
Definition at line 341 of file rc_rowfunc.h.
References eImageI, eImageIM, eImageM, and eNone.
Referenced by correlate16a32(), rfCorrelate(), and rfCorrelateWindow().
 {
     uint32 height = rcRowFuncTwoSource<T>::mHeight;
     switch ( mCacheState ) {
         case eNone:
             do { rowFuncNoneCached(); } while (--height);
             break;
         case eImageI:
             do { rowFuncICached(); } while (--height);
             break;
         case eImageM:
             do { rowFuncMCached(); } while (--height);
             break;
         case eImageIM:
             do { rowFuncIMCached(); } while (--height);
             break;
     }
 }
template<class T > void rcBasicCorrRowFunc< T >::epilog (rcCorr & res)
Definition at line 362 of file rc_rowfunc.h.
Referenced by correlate16a32(), rfCorrelate(), and rfCorrelateWindow().
 {
     mRes.n (rcRowFuncTwoSource<T>::mWidth * rcRowFuncTwoSource<T>::mHeight);
     mRes.compute ();
     res = mRes;
 }
template<> void rcBasicCorrRowFunc< uint8 >::epilog (rcCorr & res) inline
Definition at line 556 of file rc_rowfuncs.cpp.
 {
     mRes.Sim ((mRes.Sim() - mRes.Sii() - mRes.Smm())/2.);
     mRes.n (mWidth * mHeight);
     mRes.compute ();
     res = mRes;
 }
template<class T > void rcBasicCorrRowFunc< T >::prolog () virtual
Implements rcRowFuncTwoSource< T >.
Definition at line 370 of file rc_rowfunc.h.
Referenced by correlate16a32(), rfCorrelate(), and rfCorrelateWindow().
 {
 }
template<class T > void rcBasicCorrRowFunc< T >::rowFunc () virtual
Implements rcRowFuncTwoSource< T >.
Definition at line 319 of file rc_rowfunc.h.
References eImageI, eImageIM, eImageM, and eNone.
 {
   switch ( mCacheState ) {
         case eNone:
             rowFuncNoneCached();
             break;
         case eImageI:
             rowFuncICached();
             break;
         case eImageM:
             rowFuncMCached();
             break;
         case eImageIM:
             rowFuncIMCached();
             break;
   }
 }
template<> void rcBasicCorrRowFunc< uint8 >::rowFunc () inline virtual
Implements rcRowFuncTwoSource< T >.
Definition at line 508 of file rc_rowfuncs.cpp.
References eImageI, eImageIM, eImageM, and eNone.
 {
     switch ( mCacheState ) {
         case eNone:
             rowFuncNoneCached();
             break;
         case eImageI:
             rowFuncICached();
             break;
         case eImageM:
             rowFuncMCached();
             break;
         case eImageIM:
             rowFuncIMCached();
             break;
     }
 }
template<class T > void rcBasicCorrRowFunc< T >::rowFuncICached () private
Definition at line 430 of file rc_rowfunc.h.
 {
   double Sm(0), Smm(0), Sim(0);
   const T *pFirst (rcRowFuncTwoSource<T>::mFirst);
   const T *pSecond (rcRowFuncTwoSource<T>::mSecond);
   for (const T *pEnd = rcRowFuncTwoSource<T>::mFirst + rcRowFuncTwoSource<T>::mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
   {
         const T i = *pFirst;
         const T j = *pSecond;
         Sm  += j;
         Smm += j * j;
         Sim += i * j;
   }
   mRes.accumulateM (Sim, Smm, Sm);
   rcRowFuncTwoSource<T>::mFirst += mRUP.x();
   rcRowFuncTwoSource<T>::mSecond += mRUP.y();
 }
template<> void rcBasicCorrRowFunc< uint8 >::rowFuncICached () inline private
Definition at line 447 of file rc_rowfuncs.cpp.
 {
     uint32 Sm (0), Sim (0), Smm (0);
     const uint8 *pFirst (mFirst);
     const uint8 *pSecond (mSecond);
     for (const uint8 *pEnd = mFirst + mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
     {
         const uint8 i = *pFirst;
         const uint8 j = *pSecond;
         Sm  += j;
         Smm += gSquareTable512[j];
         Sim += gSquareTable512[i + j];
     }
     mRes.accumulateM (Sim, Smm, Sm);
     mFirst += mRUP.x();
     mSecond += mRUP.y();
 }
template<class T > void rcBasicCorrRowFunc< T >::rowFuncIMCached () private
Definition at line 474 of file rc_rowfunc.h.
 {
   double Sim(0);
   const T *pFirst (rcRowFuncTwoSource<T>::mFirst);
   const T *pSecond (rcRowFuncTwoSource<T>::mSecond);
   for (const T *pEnd = rcRowFuncTwoSource<T>::mFirst + rcRowFuncTwoSource<T>::mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
   {
         const T i = *pFirst;
         const T j = *pSecond;
         Sim += i * j;
   }
   mRes.accumulate (Sim);
   rcRowFuncTwoSource<T>::mFirst += mRUP.x();
   rcRowFuncTwoSource<T>::mSecond += mRUP.y();
 }
template<> void rcBasicCorrRowFunc< uint8 >::rowFuncIMCached () inline private
Definition at line 489 of file rc_rowfuncs.cpp.
 {
     uint32 Sim (0);
     const uint8 *pFirst (mFirst);
     const uint8 *pSecond (mSecond);
     for (const uint8 *pEnd = mFirst + mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
     {
         const uint8 i = *pFirst;
         const uint8 j = *pSecond;
         Sim += gSquareTable512[i + j];
     }
     mRes.accumulate (Sim);
     mFirst += mRUP.x();
     mSecond += mRUP.y();
 }
template<class T > void rcBasicCorrRowFunc< T >::rowFuncMCached () private
Definition at line 452 of file rc_rowfunc.h.
 {
   double Si(0), Sii(0), Sim(0);
   const T *pFirst (rcRowFuncTwoSource<T>::mFirst);
   const T *pSecond (rcRowFuncTwoSource<T>::mSecond);
   for (const T *pEnd = rcRowFuncTwoSource<T>::mFirst + rcRowFuncTwoSource<T>::mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
   {
         const T i = *pFirst;
         const T j = *pSecond;
         Si  += i;
         Sii += i * i;
         Sim += i * j;
   }
   mRes.accumulate (Sim, Sii, Si);
   rcRowFuncTwoSource<T>::mFirst += mRUP.x();
   rcRowFuncTwoSource<T>::mSecond += mRUP.y();
 }
template<> void rcBasicCorrRowFunc< uint8 >::rowFuncMCached () inline private
Definition at line 468 of file rc_rowfuncs.cpp.
 {
     uint32 Si (0), Sim (0), Sii (0);
     const uint8 *pFirst (mFirst);
     const uint8 *pSecond (mSecond);
     for (const uint8 *pEnd = mFirst + mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
     {
         const uint8 i = *pFirst;
         const uint8 j = *pSecond;
         Si  += i;
         Sii += gSquareTable512[i];
         Sim += gSquareTable512[i + j];
     }
     mRes.accumulate (Sim, Sii, Si);
     mFirst += mRUP.x();
     mSecond += mRUP.y();
 }
template<class T > void rcBasicCorrRowFunc< T >::rowFuncNoneCached () private
Definition at line 406 of file rc_rowfunc.h.
 {
   double Si(0), Sm(0), Sii(0), Smm(0), Sim(0);
   const T *pFirst (rcRowFuncTwoSource<T>::mFirst);
   const T *pSecond (rcRowFuncTwoSource<T>::mSecond);
   for (const T *pEnd = rcRowFuncTwoSource<T>::mFirst + rcRowFuncTwoSource<T>::mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
     {
         const T i = *pFirst;
         const T j = *pSecond;
         Si  += i;
         Sm  += j;
         Sii += i * i;
         Smm += j * j;
         Sim += i * j;
   }
   mRes.accumulate (Sim, Sii, Smm, Si, Sm);
   rcRowFuncTwoSource<T>::mFirst += mRUP.x();
   rcRowFuncTwoSource<T>::mSecond += mRUP.y();
 }
template<> void rcBasicCorrRowFunc< uint8 >::rowFuncNoneCached () inline private
Definition at line 424 of file rc_rowfuncs.cpp.
 {
     uint32 Si (0), Sm (0), Sim (0), Smm (0), Sii (0);
     const uint8 *pFirst (mFirst);
     const uint8 *pSecond (mSecond);
     for (const uint8 *pEnd = mFirst + mWidth; pFirst < pEnd; ++pFirst, ++pSecond)
     {
         const uint8 i = *pFirst;
         const uint8 j = *pSecond;
         Si  += i;
         Sm  += j;
         Sii += gSquareTable512[i];
         Smm += gSquareTable512[j];
         Sim += gSquareTable512[i + j];
     }
     mRes.accumulate (Sim, Sii, Smm, Si, Sm);
     mFirst += mRUP.x();
     mSecond += mRUP.y();
 }
template<class T > void rcBasicCorrRowFunc< T >::setCache (const rcCorrelationWindow< T > & srcA, const rcCorrelationWindow< T > & srcB) private
Definition at line 380 of file rc_rowfunc.h.
References eImageI, eImageIM, eImageM, eNone, rcCorrelationWindow< T >::sum(), rcCorrelationWindow< T >::sumSquares(), and rcCorrelationWindow< T >::sumValid().
Referenced by rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc().
 {
     // Set cache state and sums
     if ( srcA.sumValid() ) {
         if ( srcB.sumValid() ) {
             mCacheState = eImageIM;
             mRes.Sii( srcA.sumSquares() );
             mRes.Si( srcA.sum() );
             mRes.Smm( srcB.sumSquares() );
             mRes.Sm( srcB.sum() );
         }
         else {
             mCacheState = eImageI;
             mRes.Sii( srcA.sumSquares() );
             mRes.Si( srcA.sum() );
         }
     } else if ( srcB.sumValid() ) {
         mCacheState = eImageM;
         mRes.Smm( srcB.sumSquares() );
         mRes.Sm( srcB.sum() );
     } else {
         mCacheState = eNone;
     }
 }
Member Data Documentation
template<class T> rcCorrMomentsCached rcBasicCorrRowFunc< T >::mCacheState private
Definition at line 141 of file rc_rowfunc.h.
template<class T> rcCorr rcBasicCorrRowFunc< T >::mRes private
Definition at line 139 of file rc_rowfunc.h.
template<class T> rcUIPair rcBasicCorrRowFunc< T >::mRUP private
Definition at line 140 of file rc_rowfunc.h.
The documentation for this class was generated from the following file:
include/analysis/rc_rowfunc.h