Visible: TCP_connection Class Reference
TCP_connection Class Reference
#include <include/stlplus/tcp.hpp>
Public Member Functions
TCP_connection (void)
~TCP_connection (void)
TCP_connection (const TCP_connection &)
TCP_connection & operator= (const TCP_connection &)
int error (void) const
std::string message (void) const
bool initialised (void) const
unsigned long address (void) const
unsigned short port (void) const
bool send_ready (unsigned wait)
bool send (std::string &data)
bool receive_ready (unsigned wait)
bool receive (std::string &data)
bool close (void)
Protected Attributes
smart_ptr< TCP_connection_data > m_data
Friends
class TCP_connection_data
class TCP_server_data
Detailed Description
Definition at line 37 of file tcp.hpp.
Constructor & Destructor Documentation
TCP_connection::TCP_connection (void)
Definition at line 454 of file tcp.cpp.
                                    : m_data(TCP_connection_data())
 {
 }
TCP_connection::~TCP_connection (void)
Definition at line 458 of file tcp.cpp.
 {
 }
TCP_connection::TCP_connection (const TCP_connection & connection)
Definition at line 462 of file tcp.cpp.
References TCP_server_data::connection().
 {
   *this = connection;
 }
Member Function Documentation
unsigned long TCP_connection::address (void) const
Definition at line 488 of file tcp.cpp.
References TCP_connection_data::address(), and m_data.
 {
   return m_data->address();
 }
bool TCP_connection::close (void)
Definition at line 518 of file tcp.cpp.
References TCP_connection_data::close(), and m_data.
 {
   return m_data->close();
 }
int TCP_connection::error (void) const
Definition at line 473 of file tcp.cpp.
References TCP_connection_data::error(), and m_data.
 {
   return m_data->error();
 }
bool TCP_connection::initialised (void) const
Definition at line 483 of file tcp.cpp.
References TCP_connection_data::initialised(), and m_data.
 {
   return m_data->initialised();
 }
std::string TCP_connection::message (void) const
Definition at line 478 of file tcp.cpp.
References m_data, and TCP_connection_data::message().
 {
   return m_data->message();
 }
TCP_connection & TCP_connection::operator= (const TCP_connection & connection)
Definition at line 467 of file tcp.cpp.
References m_data.
 {
   m_data = connection.m_data;
   return *this;
 }
unsigned short TCP_connection::port (void) const
Definition at line 493 of file tcp.cpp.
References m_data, and TCP_connection_data::port().
 {
   return m_data->port();
 }
bool TCP_connection::receive (std::string & data)
Definition at line 513 of file tcp.cpp.
References m_data, and TCP_connection_data::receive().
 {
   return m_data->receive(data);
 }
bool TCP_connection::receive_ready (unsigned wait)
Definition at line 508 of file tcp.cpp.
References m_data, and TCP_connection_data::receive_ready().
 {
   return m_data->receive_ready(wait);
 }
bool TCP_connection::send (std::string & data)
Definition at line 503 of file tcp.cpp.
References m_data, and TCP_connection_data::send().
 {
   return m_data->send(data);
 }
bool TCP_connection::send_ready (unsigned wait)
Definition at line 498 of file tcp.cpp.
References m_data, and TCP_connection_data::send_ready().
 {
   return m_data->send_ready(wait);
 }
Friends And Related Function Documentation
friend class TCP_connection_data friend
Definition at line 58 of file tcp.hpp.
friend class TCP_server_data friend
Definition at line 59 of file tcp.hpp.
Member Data Documentation
smart_ptr<TCP_connection_data> TCP_connection::m_data protected
Definition at line 60 of file tcp.hpp.
Referenced by address(), close(), TCP_server_data::connection(), error(), initialised(), message(), operator=(), port(), receive(), receive_ready(), send(), and send_ready().
The documentation for this class was generated from the following files:
include/stlplus/tcp.hpp
include/stlplus/tcp.cpp