Visible: rcExecWithShmem Class Reference
rcExecWithShmem Class Reference
#include <include/util/rc_resource_ctrl.h>
Public Member Functions
rcExecWithShmem (char *progName, int arg1, char *arg2, uint32 sz, uint8 childControlsBufferFirst=TRUE)
virtual ~rcExecWithShmem ()
rcSharedMemoryUser & getShmemUser ()
pid_t getChildPID ()
bool isValid () const
rcEWSError getCreationError () const
uint8 isChildDone ()
uint8 isParentDone ()
void setParentDone ()
Static Public Member Functions
static void setPathName (char *nameArg)
static std::string pathName ()
Private Member Functions
rcExecWithShmem (const rcExecWithShmem &)
rcExecWithShmem & operator= (const rcExecWithShmem &)
void freeSystemResources ()
Private Attributes
rcSharedMemoryUser * _shMemUserP
shMemCtrl * _shMemCtrlP
int _semSetId
int _shmId
pid_t _childPID
rcEWSError _createError
pthread_t _watchdogThread
watchdogInfo _watchdogData
Static Private Attributes
static char * _progPath = 0
Detailed Description
Definition at line 142 of file rc_resource_ctrl.h.
Constructor & Destructor Documentation
rcExecWithShmem::rcExecWithShmem (char * progName, int arg1, char * arg2, uint32 sz, uint8 childControlsBufferFirst = TRUE)
Definition at line 183 of file rc_resource_ctrl.cpp.
References _childPID, _createError, _progPath, _semSetId, _shMemCtrlP, _shMemUserP, _shmId, _watchdogData, _watchdogThread, shMemCtrl::childControlsBufferFirst, shMemCtrl::childDone, shMemCtrl::childTouch, eProcessFork, eSemaphoreInit, eShmemInit, freeSystemResources(), NULL, shMemCtrl::parentDone, shMemCtrl::parentTouch, watchdogInfo::peerDead, rcResCtrlWatchdog(), watchdogInfo::readP, rmDim, shMemCtrl::semSetId, watchdogInfo::shMemUser, shMemCtrl::shmId, and watchdogInfo::writeP.
         : _shMemUserP(0), _semSetId(-1), _shmId(-1), _childPID( 0 ),
           _createError(eNoError)
 {
   assert(sz);
   assert(_progPath);
   assert(progName);
   /* Figure out how to round up the size of the shared memory control area
    * so that the user data starts on a 0 mod 16 boundary.
    */
   uint32 ctrlSz = sizeof(shMemCtrl);
   ctrlSz += ((ctrlSz & 0xF) == 0) ? 0 : (16 - (ctrlSz & 0xF));
   assert((ctrlSz & 0xF) == 0);
   /* Set up complete path to executable.
    */
   int progPathLen = strlen(_progPath);
   char* execPath = (char*)malloc(progPathLen + strlen(progName) + 1);
   assert(execPath);
   strcpy(execPath, _progPath);
   strcpy(execPath + progPathLen, progName);
   /* Allocate System V shared memory */
   _shmId = shmget(IPC_PRIVATE, ctrlSz + sz, (IPC_CREAT | 0600));
   if (_shmId == -1)
   {
     perror("shmem init step 1");
     free(execPath);
     _createError = eShmemInit;
     return;
   }
   _shMemCtrlP = (shMemCtrl *)shmat(_shmId, 0, 0);
   if ((int)_shMemCtrlP == -1)
   {
     perror("shmem init step 2");
     freeSystemResources();
     free(execPath);
     _createError = eShmemInit;
     return;
   }
   /* Allocate System V semaphores */
   _semSetId = semget(IPC_PRIVATE, 2, (IPC_CREAT | 0600));
   if (_semSetId == -1)
   {
     perror("sem init step 1");
     freeSystemResources();
     free(execPath);
     _createError = eSemaphoreInit;
     return;
   }
   struct sembuf semBufParent, semBufChild;
   semBufParent.sem_num = 0;
   semBufParent.sem_op = 0; // Do a read operation
   semBufParent.sem_flg = IPC_NOWAIT;
   /* Check to see that semaphores have initial value of 0 (locked).
    */
   if (semop(_semSetId, &semBufParent, 1) == -1)
   {
     perror("sem init step 2");
     freeSystemResources();
     free(execPath);
     assert(0);
   }
   semBufChild.sem_num = 1;
   semBufChild.sem_op = 0; // Do a read operation
   semBufChild.sem_flg = IPC_NOWAIT;
   if (semop(_semSetId, &semBufChild, 1) == -1)
   {
     perror("sem init step 3");
     freeSystemResources();
     free(execPath);
     assert(0);
   }
   /* As final setup before exec'ing the new process, initialize shared memory.
    */
   _shMemCtrlP->semSetId = _semSetId;
   _shMemCtrlP->shmId = _shmId;
   _shMemCtrlP->childDone = 0;
   _shMemCtrlP->parentDone = 0;
   _shMemCtrlP->childControlsBufferFirst = childControlsBufferFirst;
   new ((void*)&_shMemCtrlP->childTouch) rcAtomicValue<uint16> (0);
   new ((void*)&_shMemCtrlP->parentTouch) rcAtomicValue<uint16> (0);
   /* Do fork.
    */
   _childPID = fork();
   if (_childPID == -1)
   {
     perror("fork step");
     freeSystemResources();
     free(execPath);
     _createError = eProcessFork;
     return;
   }
   else if (_childPID) // Then this is parent
   {
     /* After the fork() the child cannot see writes by the parent.
      * This seems like an OS bug. To get around it, reattach the
      * current address and then detach.
      */
     shMemCtrl* tempShmemP = (shMemCtrl *)shmat(_shmId, 0, 0);
     if ((int)tempShmemP == -1)
     {
       perror("shmem init step 3");
       freeSystemResources();
       free(execPath);
       _createError = eShmemInit;
       return;
     }
     if (shmdt(_shMemCtrlP) == -1)
     {
       perror("shmem init step 4");
       _shMemCtrlP = (shMemCtrl*)-1;
       freeSystemResources();
       free(execPath);
       _createError = eShmemInit;
       return;
     }
     _shMemCtrlP = tempShmemP;
     /* Set up semaphore values the way the parent wants them and then
      * use them to construct a shared memory control object.
      */
     semBufParent.sem_num = 1;
     semBufParent.sem_op = -1; // Decrement semaphore (lock operation)
     semBufParent.sem_flg = 0;
     semBufChild.sem_num = 0;
     semBufChild.sem_op = 1; // Increment semaphore (unlock operation)
     semBufChild.sem_flg = 0;
     _shMemUserP =
       new rcSharedMemoryUser(semBufParent, semBufChild, _semSetId,
                  (void*)((uint8 *)_shMemCtrlP + ctrlSz),
                  !childControlsBufferFirst, _watchdogData.peerDead);
     if (!_shMemUserP)
     {
       perror("shmem init step 5");
       freeSystemResources();
       free(execPath);
       _createError = eShmemInit;
       return;
     }
     /* Set the watchdogData fields.
      */
     printf("Parent: Shared memory start at 0x%X, size %u + %u. sizeof atomic 0x%lX Creating "
        "atomics at locations 0x%X and 0x%X\n",
        (unsigned int)(_shMemCtrlP),
        ctrlSz, sz,
        sizeof(rcAtomicValue<uint16>),
        (unsigned int)(&_shMemCtrlP->childTouch),
        (unsigned int)(&_shMemCtrlP->parentTouch));
     _watchdogData.readP = (rcAtomicValue<uint16>*)(&_shMemCtrlP->childTouch);
     _watchdogData.writeP =(rcAtomicValue<uint16>*)(&_shMemCtrlP->parentTouch);
     _watchdogData.shMemUser = _shMemUserP;
     /* Start watchdog and then done.
      */
     pthread_create(&_watchdogThread, NULL, rcResCtrlWatchdog,
            (void*)&_watchdogData);
     return;
   }
   /* Otherwise, this is the child. Set up and perform exec()
    */
   char shmIdString[50];
   char arg1String[50];
   snprintf(shmIdString, rmDim(shmIdString), "%d", _shmId);
   snprintf(arg1String, rmDim(arg1String), "%d", arg1);
   if (execl(execPath, execPath, shmIdString, arg1String, arg2, 0) == -1)
   {
     perror("error on exec");
     exit(0);
   }
   assert(0); // Should never get here!
 }
rcExecWithShmem::~rcExecWithShmem () virtual
Definition at line 384 of file rc_resource_ctrl.cpp.
References _childPID, _shMemUserP, _watchdogData, _watchdogThread, freeSystemResources(), isValid(), rcAtomicValue< T >::setValue(), and watchdogInfo::shutdown.
 {
   if (!isValid())
     return;
   if (_childPID == 0)
     return; // Only parent should be freeing stuff
   /* Tell watchdog handler to shutdown and wait for it to complete.
    */
   _watchdogData.shutdown.setValue(1);
   int err;
   fprintf(stderr, "~rcExecWithShmem: Waiting on watchdog thread\n");
   if ((err = pthread_join(_watchdogThread, 0)))
     fprintf(stderr, "Error on join with watchdog thread %d\n", err);
   fprintf(stderr, "~rcExecWithShmem: freeing system resources\n");
   freeSystemResources();
   if (_shMemUserP) {
     delete _shMemUserP;
     _shMemUserP = 0;
   }
 }
rcExecWithShmem::rcExecWithShmem (const rcExecWithShmem &) private
Member Function Documentation
void rcExecWithShmem::freeSystemResources () private
Definition at line 457 of file rc_resource_ctrl.cpp.
References _semSetId, _shMemCtrlP, and _shmId.
Referenced by rcExecWithShmem(), and ~rcExecWithShmem().
 {
   semun dummy;
   if (_semSetId != -1)
   {
     if (semctl(_semSetId, 0, IPC_RMID, dummy) == -1)
       perror("freeSystemResources(): Free of semaphores failed");
     else
       fprintf(stderr, "freeSystemResources: Semaphores freed\n");
     _semSetId = -1;
   }
   if ((int)_shMemCtrlP != -1)
   {
     if (shmdt(_shMemCtrlP) == -1)
       perror("freeSystemResources(): Detach of shared memory failed");
     else
       fprintf(stderr, "freeSystemResources: Shared memory detached\n");
     _shMemCtrlP = (shMemCtrl*)-1;
   }
   if (_shmId != -1)
   {
     if (shmctl(_shmId, IPC_RMID, 0) == -1)
       perror("freeSystemResources(): Free of shared memory failed");
     else
       fprintf(stderr, "freeSystemResources: Shared memory freed\n");
     _shmId = -1;
   }
 }
pid_t rcExecWithShmem::getChildPID () inline
Definition at line 164 of file rc_resource_ctrl.h.
References _childPID.
Referenced by rcQVideoGrabber::~rcQVideoGrabber().
 { return _childPID; }
rcEWSError rcExecWithShmem::getCreationError () const inline
Definition at line 168 of file rc_resource_ctrl.h.
References _createError.
Referenced by rcQVideoGrabber::rcQVideoGrabber().
 { return _createError; }
rcSharedMemoryUser& rcExecWithShmem::getShmemUser () inline
Definition at line 162 of file rc_resource_ctrl.h.
References _shMemUserP.
Referenced by rcQVideoGrabber::getAcqInfo(), rcQVideoGrabber::getNextFrame(), and rcQVideoGrabber::setAcqControl().
 { return *_shMemUserP; }
uint8 rcExecWithShmem::isChildDone ()
Definition at line 411 of file rc_resource_ctrl.cpp.
References _shMemCtrlP, shMemCtrl::childDone, genSync(), and isValid().
Referenced by rcQVideoGrabber::~rcQVideoGrabber().
 {
   if ( !isValid() )
       return 1;
   genSync();
   uint8 ret = _shMemCtrlP->childDone;
   genSync();
   return ret;
 }
uint8 rcExecWithShmem::isParentDone ()
Definition at line 422 of file rc_resource_ctrl.cpp.
References _shMemCtrlP, isValid(), and shMemCtrl::parentDone.
 {
   assert(isValid());
   return _shMemCtrlP->parentDone;
 }
bool rcExecWithShmem::isValid () const inline
Definition at line 166 of file rc_resource_ctrl.h.
References _createError, and eNoError.
Referenced by isChildDone(), isParentDone(), setParentDone(), and ~rcExecWithShmem().
 { return _createError == eNoError; }
rcExecWithShmem& rcExecWithShmem::operator= (const rcExecWithShmem &) private
static std::string rcExecWithShmem::pathName () inline static
Definition at line 179 of file rc_resource_ctrl.h.
References _progPath.
Referenced by rcEngineImpl::initialize().
 { return std::string (_progPath); }
void rcExecWithShmem::setParentDone ()
Definition at line 429 of file rc_resource_ctrl.cpp.
References _shMemCtrlP, genSync(), isValid(), shMemCtrl::parentDone, and TRUE.
 {
   assert(isValid());
   genSync();
   _shMemCtrlP->parentDone = TRUE;
   genSync();
 }
void rcExecWithShmem::setPathName (char * nameArg) static
Definition at line 438 of file rc_resource_ctrl.cpp.
References _progPath.
Referenced by main().
 {
   assert(pathName);
   assert(!_progPath);
   int i = strlen(pathName) - 1;
   while ((i >= 0) && (pathName[i] != '/'))
     i--;
   _progPath = (char*)malloc(i+2);
   assert(_progPath);
   if (i >= 0)
     strncpy(_progPath, pathName, i+1);
   _progPath[i+1] = 0;
 }
Member Data Documentation
pid_t rcExecWithShmem::_childPID private
Definition at line 196 of file rc_resource_ctrl.h.
Referenced by getChildPID(), rcExecWithShmem(), and ~rcExecWithShmem().
rcEWSError rcExecWithShmem::_createError private
Definition at line 197 of file rc_resource_ctrl.h.
Referenced by getCreationError(), isValid(), and rcExecWithShmem().
char * rcExecWithShmem::_progPath = 0 static private
Definition at line 200 of file rc_resource_ctrl.h.
Referenced by pathName(), rcExecWithShmem(), and setPathName().
int rcExecWithShmem::_semSetId private
Definition at line 194 of file rc_resource_ctrl.h.
Referenced by freeSystemResources(), and rcExecWithShmem().
shMemCtrl* rcExecWithShmem::_shMemCtrlP private
Definition at line 193 of file rc_resource_ctrl.h.
Referenced by freeSystemResources(), isChildDone(), isParentDone(), rcExecWithShmem(), and setParentDone().
rcSharedMemoryUser* rcExecWithShmem::_shMemUserP private
Definition at line 192 of file rc_resource_ctrl.h.
Referenced by getShmemUser(), rcExecWithShmem(), and ~rcExecWithShmem().
int rcExecWithShmem::_shmId private
Definition at line 195 of file rc_resource_ctrl.h.
Referenced by freeSystemResources(), and rcExecWithShmem().
watchdogInfo rcExecWithShmem::_watchdogData private
Definition at line 199 of file rc_resource_ctrl.h.
Referenced by rcExecWithShmem(), and ~rcExecWithShmem().
pthread_t rcExecWithShmem::_watchdogThread private
Definition at line 198 of file rc_resource_ctrl.h.
Referenced by rcExecWithShmem(), and ~rcExecWithShmem().
The documentation for this class was generated from the following files:
include/util/rc_resource_ctrl.h
src/util/code/rc_resource_ctrl.cpp