Visible: rcTextCollection Class Reference
rcTextCollection Class Reference
#include <include/visual/rc_graphics.h>
Public Member Functions
rcTextCollection ()
rcTextCollection (const rcStyle &style, const rcTextSegmentCollection &texts)
const rcStyle & style () const
rcStyle & style ()
const rcTextSegmentCollection & texts () const
rcTextSegmentCollection & texts ()
bool empty () const
uint32 size () const
void style (const rcStyle &s)
Private Attributes
rcStyle mStyle
rcTextSegmentCollection mTexts
Detailed Description
Definition at line 324 of file rc_graphics.h.
Constructor & Destructor Documentation
rcTextCollection::rcTextCollection () inline
Definition at line 326 of file rc_graphics.h.
 {};
rcTextCollection::rcTextCollection (const rcStyle & style, const rcTextSegmentCollection & texts) inline
Definition at line 327 of file rc_graphics.h.
                                                                                    :
mStyle(style), mTexts(texts) {};
Member Function Documentation
bool rcTextCollection::empty (void) const inline
Definition at line 336 of file rc_graphics.h.
References mTexts.
Referenced by rcImageCanvasGL::draw().
 { return mTexts.empty(); };
uint32 rcTextCollection::size (void) const inline
Definition at line 337 of file rc_graphics.h.
References mTexts.
 { return mTexts.size(); };
const rcStyle& rcTextCollection::style () const inline
Definition at line 331 of file rc_graphics.h.
References mStyle.
Referenced by rcImageCanvasGL::draw().
 { return mStyle; };
rcStyle& rcTextCollection::style () inline
Definition at line 332 of file rc_graphics.h.
References mStyle.
 { return mStyle; };
void rcTextCollection::style (const rcStyle & s) inline
Definition at line 340 of file rc_graphics.h.
References mStyle.
 { mStyle = s; };
const rcTextSegmentCollection& rcTextCollection::texts () const inline
Definition at line 333 of file rc_graphics.h.
References mTexts.
Referenced by rcImageCanvasGL::draw().
 { return mTexts; };
rcTextSegmentCollection& rcTextCollection::texts () inline
Definition at line 334 of file rc_graphics.h.
References mTexts.
 { return mTexts; };
Member Data Documentation
rcStyle rcTextCollection::mStyle private
Definition at line 340 of file rc_graphics.h.
Referenced by style().
rcTextSegmentCollection rcTextCollection::mTexts private
Definition at line 344 of file rc_graphics.h.
Referenced by empty(), size(), and texts().
The documentation for this class was generated from the following file:
include/visual/rc_graphics.h