Visible: rcMovieSaveStatus Class Reference
rcMovieSaveStatus Class Reference
#include <include/visiCore/rc_saveregs.h>
Public Member Functions
rcMovieSaveStatus ()
void status (rcMovieFileErr saveStatus)
void state (rcMovieFileState saveState)
void delayLeft (uint32 delayLeft)
void captureTime (uint32 captureTime)
Public Member Functions inherited from rcMovieSaveStatusReader
rcMovieSaveStatusReader ()
virtual ~rcMovieSaveStatusReader ()
rcMovieFileErr getStatus () const
rcMovieFileState getState () const
uint32 getDelayLeft () const
uint32 getCaptureTime () const
Additional Inherited Members
Protected Attributes inherited from rcMovieSaveStatusReader
rcAtomicValue< rcMovieFileErr > _saveStatus
rcAtomicValue< rcMovieFileState > _saveState
rcAtomicValue< uint32 > _delayLeft
rcAtomicValue< uint32 > _captureTime
Detailed Description
Definition at line 176 of file rc_saveregs.h.
Constructor & Destructor Documentation
rcMovieSaveStatus::rcMovieSaveStatus () inline
Definition at line 179 of file rc_saveregs.h.
                       : rcMovieSaveStatusReader()
   { }
Member Function Documentation
void rcMovieSaveStatus::captureTime (uint32 captureTime) inline
Definition at line 191 of file rc_saveregs.h.
References rcMovieSaveStatusReader::_captureTime, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieSaver::doneHdlr(), and rcEngineMovieSaver::waitHdlr().
   { _captureTime.setValue(captureTime); }
void rcMovieSaveStatus::delayLeft (uint32 delayLeft) inline
Definition at line 188 of file rc_saveregs.h.
References rcMovieSaveStatusReader::_delayLeft, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieSaver::delayHdlr(), rcEngineMovieSaver::doneHdlr(), and rcEngineMovieSaver::waitHdlr().
   { _delayLeft.setValue(delayLeft); }
void rcMovieSaveStatus::state (rcMovieFileState saveState) inline
Definition at line 185 of file rc_saveregs.h.
References rcMovieSaveStatusReader::_saveState, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieSaver::run().
   { _saveState.setValue(saveState); }
void rcMovieSaveStatus::status (rcMovieFileErr saveStatus) inline
Definition at line 182 of file rc_saveregs.h.
References rcMovieSaveStatusReader::_saveStatus, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieSaver::closeHdlr(), rcEngineMovieSaver::delayHdlr(), rcEngineMovieSaver::doneHdlr(), rcEngineMovieSaver::openHdlr(), rcEngineMovieSaver::saveHdlr(), and rcEngineMovieSaver::waitHdlr().
   { _saveStatus.setValue(saveStatus); }
The documentation for this class was generated from the following file:
include/visiCore/rc_saveregs.h