Visible: PeakSpotter Class Reference
PeakSpotter Class Reference
#include <include/visigmatch/peakspotter.hpp>
Public Types
typedef double value_type
typedef PeakSpotter ThisType
Public Member Functions
PeakSpotter (const std::deque< double > &src)
Constructor.
bool transform ()
const std::deque< double > & transformed () const
const std::deque< int > & frame_indices () const
const std::deque< double > & peaks () const
bool transformed (const std::string &filef, bool row_wise) const
bool frame_indices (const std::string &filef, bool row_wise) const
bool peaks (const std::string &filef, bool row_wise) const
Static Public Member Functions
static const double invalid_val ()
Private Member Functions
bool to_csv (const std::deque< double > &dm, const std::string &filef, bool row_wise) const
bool to_csv (const std::deque< int > &dm, const std::string &filef, bool row_wise) const
Private Attributes
bool _acc_hist_done
std::deque< double > _acc_hist
std::deque< double > _sorted
std::deque< double > _copy
std::deque< double > _dst
std::deque< int > _frames
std::deque< double > _peaks
LLSQ _lsq
double _m
double _c
rc2fvector _mean_point
rcRadian _direction
Histogram _sH
rcMutex _mu
Detailed Description
Definition at line 34 of file peakspotter.hpp.
Member Typedef Documentation
typedef PeakSpotter PeakSpotter::ThisType
Definition at line 39 of file peakspotter.hpp.
typedef double PeakSpotter::value_type
Definition at line 37 of file peakspotter.hpp.
Constructor & Destructor Documentation
PeakSpotter::PeakSpotter (const std::deque< double > & src) inline
Constructor.
Definition at line 47 of file peakspotter.hpp.
References endl(), and rmAssert.
                                             :
     {
         rmAssert (src.size());
         _copy.resize (src.size ());
         std::copy (src.begin (), src.end(), _copy.begin ());
         _sH.setup (_copy);
         _sH.build (_copy, _sH.min(), _sH.max(), 100);
         for (int i = 0; i < src.size (); i++)
             _lsq.Add ((double) i, src[i]);
         _m = _lsq.m();
         _c = _lsq.c(_m);
         _mean_point = _lsq.mean_point ();
         _direction = _lsq.vector_fit();
         std::cerr << " PeakSpotter Ctor " << std::endl;
}
Member Function Documentation
const std::deque<int>& PeakSpotter::frame_indices () const inline
Definition at line 90 of file peakspotter.hpp.
     {
         return _frames;
     }
bool PeakSpotter::frame_indices (const std::string & filef, bool row_wise) const inline
Definition at line 106 of file peakspotter.hpp.
References to_csv().
     {
         return to_csv (_frames, filef, row_wise );
     }
static const double PeakSpotter::invalid_val () inline static
Definition at line 41 of file peakspotter.hpp.
     {
         return std::numeric_limits<double>::max ();
     }
const std::deque<double>& PeakSpotter::peaks () const inline
Definition at line 95 of file peakspotter.hpp.
     {
         return _peaks;
     }
bool PeakSpotter::peaks (const std::string & filef, bool row_wise) const inline
Definition at line 111 of file peakspotter.hpp.
References to_csv().
     {
         return to_csv (_peaks, filef, row_wise );
     }
bool PeakSpotter::to_csv (const std::deque< double > & dm, const std::string & filef, bool row_wise) const inline private
Definition at line 119 of file peakspotter.hpp.
References endl().
     {
          rcLock lock (_mu);
         bool ok = false; // assume failure
         try
         {
             std::string ending = row_wise ? "," : ",\n";
             ofstream output_stream(filef.c_str());
             uint32 j;
             output_stream.precision(12);
             output_stream.setf(std::ios::fixed, std::ios::floatfield);
             for (j = 0; j < dm.size() - 1 ; j++)
                 output_stream << dm[j] << ending;
             output_stream << dm[j] << endl;
             output_stream.close ();
             ok = true;
         }
         catch (...)
         {
             ok = false;
         }
         return ok;
     }
bool PeakSpotter::to_csv (const std::deque< int > & dm, const std::string & filef, bool row_wise) const inline private
Definition at line 144 of file peakspotter.hpp.
References endl().
     {
          rcLock lock (_mu);
         bool ok = false; // assume failure
         try
         {
             std::string ending = row_wise ? "," : ",\n";
             ofstream output_stream(filef.c_str());
             uint32 j;
             output_stream.precision(12);
             for (j = 0; j < dm.size() - 1 ; j++)
                 output_stream << dm[j] << ending;
             output_stream << dm[j] << endl;
             output_stream.close ();
             ok = true;
         }
         catch (...)
         {
             ok = false;
         }
         return ok;
     }
bool PeakSpotter::transform () inline
Definition at line 66 of file peakspotter.hpp.
References count().
     {
          rcLock lock (_mu);
         _dst.resize (_copy.size ());
         std::copy (_copy.begin(), _copy.end(), _dst.begin ());
         int frame_index = 0;
         _frames.clear ();
         uint32 count (_dst.size ());
         for (; frame_index < count; frame_index++)
         {
             double d = 1.0 - _dst[frame_index];
             _frames.push_back (frame_index);
             _dst[frame_index] = (d < tqueryP) ? d : (d + tqueryP) / 2;
         }
         return true;
     }
const std::deque<double>& PeakSpotter::transformed () const inline
Definition at line 85 of file peakspotter.hpp.
Referenced by main().
     {
         return _copy;
     }
bool PeakSpotter::transformed (const std::string & filef, bool row_wise) const inline
Definition at line 100 of file peakspotter.hpp.
References to_csv().
     {
         return to_csv (_copy, filef, row_wise );
     }
Member Data Documentation
std::deque<double> PeakSpotter::_acc_hist private
Definition at line 171 of file peakspotter.hpp.
bool PeakSpotter::_acc_hist_done private
Definition at line 170 of file peakspotter.hpp.
double PeakSpotter::_c private
Definition at line 178 of file peakspotter.hpp.
std::deque<double> PeakSpotter::_copy private
Definition at line 173 of file peakspotter.hpp.
rcRadian PeakSpotter::_direction private
Definition at line 180 of file peakspotter.hpp.
std::deque<double> PeakSpotter::_dst private
Definition at line 174 of file peakspotter.hpp.
std::deque<int> PeakSpotter::_frames private
Definition at line 175 of file peakspotter.hpp.
LLSQ PeakSpotter::_lsq private
Definition at line 177 of file peakspotter.hpp.
double PeakSpotter::_m private
Definition at line 178 of file peakspotter.hpp.
rc2fvector PeakSpotter::_mean_point private
Definition at line 179 of file peakspotter.hpp.
rcMutex PeakSpotter::_mu mutable private
Definition at line 182 of file peakspotter.hpp.
std::deque<double> PeakSpotter::_peaks private
Definition at line 176 of file peakspotter.hpp.
Histogram PeakSpotter::_sH private
Definition at line 181 of file peakspotter.hpp.
std::deque<double> PeakSpotter::_sorted private
Definition at line 172 of file peakspotter.hpp.
The documentation for this class was generated from the following file:
include/visigmatch/peakspotter.hpp