Visible: rcCameraSpecification Class Reference
rcCameraSpecification Class Reference
#include <include/visual/rc_capture.hpp>
Public Member Functions
rcCameraSpecification (const dcam_properties &id, const rc2Fvector &s)
rcCameraSpecification ()
~rcCameraSpecification ()
const rc2Fvector & sensorElementSize () const
const dcam_properties & id () const
bool valid () const
bool operator< (const rcCameraSpecification &o) const
bool operator== (const rcCameraSpecification &o) const
bool operator!= (const rcCameraSpecification &o) const
Private Attributes
dcam_properties mId
rc2Fvector mSensorElementSize
Detailed Description
Definition at line 175 of file rc_capture.hpp.
Constructor & Destructor Documentation
rcCameraSpecification::rcCameraSpecification (const dcam_properties & id, const rc2Fvector & s) inline
Definition at line 180 of file rc_capture.hpp.
                                                                              :
mId(id), mSensorElementSize(s) {}
rcCameraSpecification::rcCameraSpecification () inline
Definition at line 182 of file rc_capture.hpp.
 : mSensorElementSize(-1.0f, -1.0f) {}
rcCameraSpecification::~rcCameraSpecification () inline
Definition at line 183 of file rc_capture.hpp.
 {}
Member Function Documentation
const dcam_properties& rcCameraSpecification::id (void) const inline
Definition at line 187 of file rc_capture.hpp.
Referenced by operator<(), and operator==().
 { return mId; }
bool rcCameraSpecification::operator!= (const rcCameraSpecification & o) const inline
Definition at line 200 of file rc_capture.hpp.
{
         return ! (*this == o);
     }
bool rcCameraSpecification::operator< (const rcCameraSpecification & o) const inline
Definition at line 191 of file rc_capture.hpp.
References id(), rc2dVector< T >::len(), and sensorElementSize().
     {
         return (mId.size() == o.id().size() && mSensorElementSize.len() < o.sensorElementSize().len() );
     }
bool rcCameraSpecification::operator== (const rcCameraSpecification & o) const inline
Definition at line 196 of file rc_capture.hpp.
References id(), and sensorElementSize().
     {
         return (mId.size() == o.id().size() && mSensorElementSize == o.sensorElementSize());
     }
const rc2Fvector& rcCameraSpecification::sensorElementSize () const inline
Definition at line 186 of file rc_capture.hpp.
Referenced by operator<(), and operator==().
 { return mSensorElementSize; }
bool rcCameraSpecification::valid (void) const inline
Definition at line 188 of file rc_capture.hpp.
 { return ! mId.empty(); }
Member Data Documentation
dcam_properties rcCameraSpecification::mId private
Definition at line 207 of file rc_capture.hpp.
rc2Fvector rcCameraSpecification::mSensorElementSize private
Definition at line 208 of file rc_capture.hpp.
The documentation for this class was generated from the following file:
include/visual/rc_capture.hpp