Visible: rcSegmentImpl Class Reference
rcSegmentImpl Class Reference
#include <include/visiCore/rc_segmentimpl.h>
Public Member Functions
rcSegmentImpl ()
rcSegmentImpl (const rcTimestamp &start, const rcTimestamp &length, const rcRect &focus)
virtual ~rcSegmentImpl ()
virtual rcTimestamp start (void) const
virtual rcTimestamp length (void) const
virtual void setLength (const rcTimestamp &length)
virtual rcRect focus (void) const
Private Attributes
rcTimestamp mStart
rcTimestamp mLength
rcRect mFocus
Detailed Description
Definition at line 26 of file rc_segmentimpl.h.
Constructor & Destructor Documentation
rcSegmentImpl::rcSegmentImpl () inline
Definition at line 30 of file rc_segmentimpl.h.
                     :
         mStart( cZeroTime ), mLength( cZeroTime ), mFocus( rcRect( 0, 0, 0, 0 ) ) { };
rcSegmentImpl::rcSegmentImpl (const rcTimestamp & start, const rcTimestamp & length, const rcRect & focus) inline
Definition at line 32 of file rc_segmentimpl.h.
                                                                                               :
         mStart( start ), mLength( length ), mFocus( focus ) { };
virtual rcSegmentImpl::~rcSegmentImpl () inline virtual
Definition at line 36 of file rc_segmentimpl.h.
 {};
Member Function Documentation
virtual rcRect rcSegmentImpl::focus (void) const inline virtual
Definition at line 46 of file rc_segmentimpl.h.
Referenced by rcSegmentIteratorImpl::getFocus().
 { return mFocus; }
virtual rcTimestamp rcSegmentImpl::length (void) const inline virtual
Definition at line 41 of file rc_segmentimpl.h.
Referenced by rcVideoTrackImpl::addSegment(), rcSegmentIteratorImpl::advanceNoLock(), rcSegmentIteratorImpl::contains(), rcSegmentIteratorImpl::findClosestSegment(), rcSegmentIteratorImpl::getSegmentLength(), and rcTrackImpl::lastSegmentLength().
 { return mLength; };
virtual void rcSegmentImpl::setLength (const rcTimestamp & length) inline virtual
Definition at line 43 of file rc_segmentimpl.h.
Referenced by rcSegmentIteratorImpl::rcSegmentIteratorImpl(), and rcSegmentIteratorImpl::reset().
 { mLength = length; };
virtual rcTimestamp rcSegmentImpl::start (void) const inline virtual
Definition at line 39 of file rc_segmentimpl.h.
Referenced by rcSegmentIteratorImpl::advanceNoLock(), rcSegmentIteratorImpl::contains(), rcSegmentIteratorImpl::findClosestSegment(), rcSegmentIteratorImpl::getSegmentStart(), and rcSegmentIteratorImpl::getSegmentStartAbsolute().
 { return mStart; };
Member Data Documentation
rcRect rcSegmentImpl::mFocus private
Definition at line 51 of file rc_segmentimpl.h.
rcTimestamp rcSegmentImpl::mLength private
Definition at line 50 of file rc_segmentimpl.h.
rcTimestamp rcSegmentImpl::mStart private
Definition at line 49 of file rc_segmentimpl.h.
The documentation for this class was generated from the following file:
include/visiCore/rc_segmentimpl.h