Visible: rcXMLErrorHandler Class Reference
rcXMLErrorHandler Class Reference
#include <include/visUI/rc_xmlparser.h>
Public Member Functions
rcXMLErrorHandler (QString fileName)
virtual ~rcXMLErrorHandler ()
virtual bool warning (const QXmlParseException &exception)
virtual bool error (const QXmlParseException &exception)
virtual bool fatalError (const QXmlParseException &exception)
QString errorString () const
uint32 warnings () const
uint32 errors () const
uint32 fatalErrors () const
Private Member Functions
QString buildErrorString (const QString &prefix, const QXmlParseException &exception)
Private Attributes
QString mFileName
QString mErrorString
uint32 mWarnings
uint32 mErrors
uint32 mFatalErrors
Detailed Description
Definition at line 67 of file rc_xmlparser.h.
Constructor & Destructor Documentation
rcXMLErrorHandler::rcXMLErrorHandler (QString fileName) inline
Definition at line 71 of file rc_xmlparser.h.
                                           :
     mFileName( fileName ),
         mErrorString(),
         mWarnings( 0 ),
         mErrors( 0 ),
         mFatalErrors( 0 ) { };
virtual rcXMLErrorHandler::~rcXMLErrorHandler () inline virtual
Definition at line 78 of file rc_xmlparser.h.
 { };
Member Function Documentation
QString rcXMLErrorHandler::buildErrorString (const QString & prefix, const QXmlParseException & exception) private
Definition at line 261 of file rc_xmlparser.cpp.
References error(), and mFileName.
Referenced by error(), fatalError(), and warning().
 {
     QString error;
     error = prefix + QString( "%1 %2 %3 line %4, column %5: %6\n" )
         .arg( mFileName )
         .arg( exception.systemId() )
         .arg( exception.publicId() )
         .arg( exception.lineNumber() )
         .arg( exception.columnNumber() )
         .arg( exception.message() );
     return error;
 }
bool rcXMLErrorHandler::error (const QXmlParseException & exception) virtual
Definition at line 240 of file rc_xmlparser.cpp.
References buildErrorString(), FALSE, mErrorString, and mFatalErrors.
Referenced by buildErrorString().
 {
     ++mFatalErrors;
     mErrorString = buildErrorString( "rcXMLErrorHandler error: ", exception );
     return FALSE;
 }
uint32 rcXMLErrorHandler::errors () const inline
Definition at line 90 of file rc_xmlparser.h.
References mErrors.
 { return mErrors; };
QString rcXMLErrorHandler::errorString () const
Definition at line 254 of file rc_xmlparser.cpp.
References mErrorString.
Referenced by rcModelDomain::requestOpen().
 {
     return mErrorString;
 }
bool rcXMLErrorHandler::fatalError (const QXmlParseException & exception) virtual
Definition at line 247 of file rc_xmlparser.cpp.
References buildErrorString(), FALSE, mErrorString, and mFatalErrors.
 {
     ++mFatalErrors;
     mErrorString = buildErrorString( "rcXMLErrorHandler fatal error: ", exception );
     return FALSE;
 }
uint32 rcXMLErrorHandler::fatalErrors () const inline
Definition at line 91 of file rc_xmlparser.h.
References mFatalErrors.
Referenced by rcModelDomain::requestOpen().
 { return mFatalErrors; };
bool rcXMLErrorHandler::warning (const QXmlParseException & exception) virtual
Definition at line 232 of file rc_xmlparser.cpp.
References buildErrorString(), mErrorString, mWarnings, and TRUE.
 {
     ++mWarnings;
     mErrorString = buildErrorString( "rcXMLErrorHandler warning: ", exception );
     return TRUE;
 }
uint32 rcXMLErrorHandler::warnings () const inline
Definition at line 89 of file rc_xmlparser.h.
References mWarnings.
 { return mWarnings; };
Member Data Documentation
uint32 rcXMLErrorHandler::mErrors private
Definition at line 102 of file rc_xmlparser.h.
Referenced by errors().
QString rcXMLErrorHandler::mErrorString private
Definition at line 99 of file rc_xmlparser.h.
Referenced by error(), errorString(), fatalError(), and warning().
uint32 rcXMLErrorHandler::mFatalErrors private
Definition at line 103 of file rc_xmlparser.h.
Referenced by error(), fatalError(), and fatalErrors().
QString rcXMLErrorHandler::mFileName private
Definition at line 98 of file rc_xmlparser.h.
Referenced by buildErrorString().
uint32 rcXMLErrorHandler::mWarnings private
Definition at line 101 of file rc_xmlparser.h.
Referenced by warning(), and warnings().
The documentation for this class was generated from the following files:
include/visUI/rc_xmlparser.h
src/visible/qt/rc_xmlparser.cpp