Visible: restore_context Class Reference
restore_context Class Reference
#include <include/stlplus/persistent.hpp>
Public Types
typedef void *(* create_callback)(void)
typedef void(* restore_callback)(restore_context &, void *)
typedef std::pair
< create_callback,
restore_callback > callback_data
typedef std::pair< unsigned
short, persistent * > interface_data
typedef void(* installer)(restore_context &)
Public Member Functions
restore_context (const itext &device) throw (persistent_restore_failed)
~restore_context (void)
int get (void) throw (persistent_restore_failed)
const itext & device (void) const
unsigned char version (void) const
bool little_endian (void) const
std::pair< bool, void * > pointer_map (unsigned magic)
void pointer_add (unsigned magic, void *new_pointer)
unsigned short register_type (create_callback, restore_callback)
bool is_callback (unsigned short) const
callback_data lookup_type (unsigned short) const throw (persistent_illegal_type)
unsigned short register_interface (const persistent &)
bool is_interface (unsigned short) const
const persistent & lookup_interface (unsigned short) const throw (persistent_illegal_type)
void register_all (installer)
Private Member Functions
restore_context (const restore_context &)
restore_context & operator= (const restore_context &)
Private Attributes
restore_context_body * m_body
Friends
class persistent
class restore_context_body
Detailed Description
Definition at line 130 of file persistent.hpp.
Member Typedef Documentation
typedef std::pair<create_callback, restore_callback> restore_context::callback_data
Definition at line 141 of file persistent.hpp.
typedef void*(* restore_context::create_callback)(void)
Definition at line 136 of file persistent.hpp.
typedef void(* restore_context::installer)(restore_context &)
Definition at line 149 of file persistent.hpp.
typedef std::pair<unsigned short,persistent*> restore_context::interface_data
Definition at line 146 of file persistent.hpp.
typedef void(* restore_context::restore_callback)(restore_context &, void *)
Definition at line 139 of file persistent.hpp.
Constructor & Destructor Documentation
restore_context::restore_context (const itext & device) throw (persistent_restore_failed)
Definition at line 382 of file persistent.cpp.
                                                                                      :
   m_body(0)
 {
   m_body = new restore_context_body(device);
 }
restore_context::~restore_context (void)
Definition at line 388 of file persistent.cpp.
References m_body.
 {
   delete m_body;
 }
restore_context::restore_context (const restore_context &) private
Member Function Documentation
const itext & restore_context::device (void) const
Definition at line 393 of file persistent.cpp.
References DEBUG_ASSERT, restore_context_body::device(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->device();
 }
int restore_context::get (void) throw (persistent_restore_failed)
Definition at line 411 of file persistent.cpp.
References DEBUG_ASSERT, restore_context_body::get(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->get();
 }
bool restore_context::is_callback (unsigned short key) const
Definition at line 435 of file persistent.cpp.
References DEBUG_ASSERT, restore_context_body::is_callback(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->is_callback(key);
 }
bool restore_context::is_interface (unsigned short key) const
Definition at line 453 of file persistent.cpp.
References DEBUG_ASSERT, restore_context_body::is_interface(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->is_interface(key);
 }
bool restore_context::little_endian (void) const
Definition at line 405 of file persistent.cpp.
References DEBUG_ASSERT, restore_context_body::little_endian(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->little_endian();
 }
const persistent & restore_context::lookup_interface (unsigned short key) const throw (persistent_illegal_type)
Definition at line 459 of file persistent.cpp.
References DEBUG_ASSERT.
 {
   DEBUG_ASSERT(m_body);
   return m_body->lookup_interface(key);
 }
restore_context::callback_data restore_context::lookup_type (unsigned short key) const throw (persistent_illegal_type)
Definition at line 441 of file persistent.cpp.
References DEBUG_ASSERT.
 {
   DEBUG_ASSERT(m_body);
   return m_body->lookup_type(key);
 }
restore_context& restore_context::operator= (const restore_context &) private
void restore_context::pointer_add (unsigned magic, void * new_pointer)
Definition at line 423 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and restore_context_body::pointer_add().
 {
   DEBUG_ASSERT(m_body);
   m_body->pointer_add(magic,new_pointer);
 }
std::pair< bool, void * > restore_context::pointer_map (unsigned magic)
Definition at line 417 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and restore_context_body::pointer_map().
 {
   DEBUG_ASSERT(m_body);
   return m_body->pointer_map(magic);
 }
void restore_context::register_all (restore_context::installer installer)
Definition at line 465 of file persistent.cpp.
References DEBUG_ASSERT, and m_body.
 {
   DEBUG_ASSERT(m_body);
   if (installer) installer(*this);
 }
unsigned short restore_context::register_interface (const persistent & sample)
Definition at line 447 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and restore_context_body::register_interface().
 {
   DEBUG_ASSERT(m_body);
   return m_body->register_interface(sample);
 }
unsigned short restore_context::register_type (restore_context::create_callback create, restore_context::restore_callback restore)
Definition at line 429 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and restore_context_body::register_type().
 {
   DEBUG_ASSERT(m_body);
   return m_body->register_type(create,restore);
 }
unsigned char restore_context::version (void) const
Definition at line 399 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and restore_context_body::version().
 {
   DEBUG_ASSERT(m_body);
   return m_body->version();
 }
Friends And Related Function Documentation
friend class persistent friend
Definition at line 145 of file persistent.hpp.
friend class restore_context_body friend
Definition at line 188 of file persistent.hpp.
Member Data Documentation
restore_context_body* restore_context::m_body private
Definition at line 189 of file persistent.hpp.
Referenced by device(), get(), is_callback(), is_interface(), little_endian(), pointer_add(), pointer_map(), register_all(), register_interface(), register_type(), version(), and ~restore_context().
The documentation for this class was generated from the following files:
include/stlplus/persistent.hpp
include/stlplus/persistent.cpp