Visible: rcDefGenerateImage Class Reference
rcDefGenerateImage Class Reference
#include <include/visual/rc_def_generators.h>
Public Member Functions
rcDefGenerateImage (rcGeneratePixel &genPixel)
virtual ~rcDefGenerateImage ()
void genImage (const rcAffineWindow *src, rcWindow &dest, const rcIRect &region)
void project (const rcAffineWindow *src, vector< float > &, const rcWindow &mask, rc2Xform &)
Public Member Functions inherited from rcGenerateImage
rcGenerateImage ()
virtual ~rcGenerateImage ()
Private Attributes
rcGeneratePixel & _genPixel
Detailed Description
Definition at line 40 of file rc_def_generators.h.
Constructor & Destructor Documentation
rcDefGenerateImage::rcDefGenerateImage (rcGeneratePixel & genPixel) inline
Definition at line 44 of file rc_def_generators.h.
 : _genPixel(genPixel) {}
virtual rcDefGenerateImage::~rcDefGenerateImage () inline virtual
Definition at line 46 of file rc_def_generators.h.
 {}
Member Function Documentation
void rcDefGenerateImage::genImage (const rcAffineWindow * src, rcWindow & dest, const rcIRect & region) virtual
Implements rcGenerateImage.
Definition at line 16 of file rc_def_generators.cpp.
References _genPixel, rcWindow::depth(), rcGeneratePixel::genPixel(), rcAffineWindow::getPixelLoc(), rcRectangle< T >::lr(), NULL, rcRectangle< T >::origin(), rcPixel8, rcPixelDouble, rmAssert, rcWindow::setDoublePixel(), rcWindow::setPixel(), rcWindow::vImage(), rcAffineWindow::vImageToAffine(), rcPair< T >::x(), rcWindow::x(), and rcPair< T >::y().
 {
   const int32 xOff = region.origin().x(), yOff = region.origin().y();
   const rcIPair endPt = region.lr();
   const int32 endX = endPt.x() - xOff;
   const int32 endY = endPt.y() - yOff;
   rmAssert(src && (src->depth() == dest.depth()));
   if (src->depth() == rcPixelDouble) {
     for (int32 x = 0; x < endX; x++)
       for (int32 y = 0; y < endX; y++) {
     rc2Dvector v(src->getPixelLoc(x, y));
     dest.setDoublePixel(x, y, _genPixel.genPixel(src, v.x(), v.y()));
       }
   }
   else {
     if (src->depth() == rcPixel8)
       {
     vImage_Error ve;
     vImage_Buffer vs, vd;
     src->vImage (vs);
     dest.vImage (vd);
     vImage_AffineTransform ga = src->vImageToAffine ();
     ve = vImageAffineWarp_Planar8( &vs, &vd, NULL, & ga, Pixel_8 (0), kvImageNoFlags);
     rmAssert (!ve);
       }
     else
       {
     for (int32 x = 0; x < endX; x++)
       for (int32 y = 0; y < endY; y++) {
     rc2Dvector v(src->getPixelLoc(x, y));
     //printf("x y %d %d %f %f\n", x, y, v.x(), v.y());
     dest.setPixel(x, y, (uint32)_genPixel.genPixel(src, v.x(), v.y()));
       }
       }
   }
 }
void rcDefGenerateImage::project (const rcAffineWindow * src, vector< float > & dst, const rcWindow & mask, rc2Xform & xform) virtual
Implements rcGenerateImage.
Definition at line 70 of file rc_def_generators.cpp.
References _genPixel, rcAffineWindow::ar(), rcAffineRectangle::cannonicalSize(), rcGeneratePixel::genPixel(), rcWindow::getPixel(), rcAffineWindow::getPixelLoc(), rcWindow::isBound(), rc2Xform::matrix(), rmAssert, rcPair< T >::x(), rcWindow::x(), and rcPair< T >::y().
 {
   rmAssert (dst.size());
   const rcMatrix_2d& mat = xform.matrix();
   bool yProj (mat.element(0,0) == 1.0 && mat.element(1,1) == 0.0 && (int32)dst.size() == src->ar().cannonicalSize().x());
   bool xProj (mat.element(0,0) == 0.0 && mat.element(1,1) == 1.0 && (int32)dst.size() == src->ar().cannonicalSize().y());
   bool maskOn = mask.isBound();
   rmAssert (xProj ^ yProj);
   int32 projectionWidth (dst.size());
   int32 projectionHeight = (yProj) ? src->ar().cannonicalSize().y() : src->ar().cannonicalSize().x();
   vector<float>::iterator accPtr = dst.begin();
   // Walk through projection image, project along the other dimension
   if (yProj)
     { // Projecting down columns
       for (int32 x = 0;  x < projectionWidth;  x++)
     {
       for (int32 y = 0;  y < projectionHeight;  y++)
         {
           rc2Dvector v (src->getPixelLoc (x, y));
           if (maskOn && mask.getPixel ((int32) v.x(), (int32) v.y()) == 0)
         continue;
           float pel = (float)_genPixel.genPixel (src, v.x(), v.y());
           accPtr[x] += pel;
         }
     }
     }
   if (xProj)
     { // Projecting down rows
       for (int32 y = 0;  y < projectionWidth;  y++)
     {
       for (int32 x = 0;  x < projectionHeight;  x++)
         {
           rc2Dvector v (src->getPixelLoc (x, y));
           if (maskOn && mask.getPixel ((int32) v.x(), (int32) v.y()) == 0)
         continue;
           float pel = (float)_genPixel.genPixel (src, v.x(), v.y());
           accPtr[y] += pel;
         }
     }
     }
   const rc2Xform dis (src->ar());
   xform = xform * dis;
 }
Member Data Documentation
rcGeneratePixel& rcDefGenerateImage::_genPixel private
Definition at line 91 of file rc_def_generators.h.
Referenced by genImage(), and project().
The documentation for this class was generated from the following files:
include/visual/rc_def_generators.h
src/visual/code/rc_def_generators.cpp