Visible: arg_vector Class Reference
arg_vector Class Reference
#include <include/stlplus/subprocesses.hpp>
Public Member Functions
arg_vector (void)
arg_vector (const arg_vector &)
arg_vector (char **)
arg_vector (const std::string &)
arg_vector (const char *)
~arg_vector (void)
arg_vector & operator= (const arg_vector &)
arg_vector & operator= (char **)
arg_vector & operator= (const std::string &)
arg_vector & operator= (const char *)
arg_vector & operator+= (const std::string &)
arg_vector & operator-= (const std::string &)
void insert (unsigned index, const std::string &)
void clear (unsigned index)
void clear (void)
unsigned size (void) const
operator char ** (void) const
char ** argv (void) const
char * operator[] (unsigned index) const
char * argv0 (void) const
std::string image (void) const
Private Attributes
char ** v
Friends
otext & operator<< (otext &, const arg_vector &)
Detailed Description
Definition at line 31 of file subprocesses.hpp.
Constructor & Destructor Documentation
arg_vector::arg_vector (void)
Definition at line 188 of file subprocesses.cpp.
References v.
 {
   v = 0;
 }
arg_vector::arg_vector (const arg_vector & a)
Definition at line 193 of file subprocesses.cpp.
References v.
 {
   v = 0;
   *this = a;
 }
arg_vector::arg_vector (char ** a)
Definition at line 199 of file subprocesses.cpp.
References v.
 {
   v = 0;
   *this = a;
 }
arg_vector::arg_vector (const std::string & command)
Definition at line 205 of file subprocesses.cpp.
References v.
 {
   v = 0;
   *this = command;
 }
arg_vector::arg_vector (const char * command)
Definition at line 211 of file subprocesses.cpp.
References v.
 {
   v = 0;
   *this = command;
 }
arg_vector::~arg_vector (void)
Definition at line 217 of file subprocesses.cpp.
References clear().
 {
   clear();
 }
Member Function Documentation
char ** arg_vector::argv (void) const
Definition at line 319 of file subprocesses.cpp.
References v.
Referenced by subprocess::spawn(), and async_subprocess::spawn().
 {
   return v;
 }
char * arg_vector::argv0 (void) const
Definition at line 330 of file subprocesses.cpp.
References operator[]().
Referenced by subprocess::spawn(), and async_subprocess::spawn().
 {
   return operator [] (0);
 }
void arg_vector::clear (unsigned index)
Definition at line 280 of file subprocesses.cpp.
References clear(), copy_string(), DEBUG_ASSERT, size(), and v.
 {
   DEBUG_ASSERT(index < size());
   // copy up to index, skip it, then copy the rest
   char** new_argv = new char*[size()];
   unsigned i = 0;
   for ( ; i < index; i++)
     new_argv[i] = copy_string(v[i]);
   i++;
   for ( ; i < size(); i++)
     new_argv[i-1] = copy_string(v[i]);
   new_argv[i-1] = 0;
   clear();
   v = new_argv;
 }
void arg_vector::clear (void)
Definition at line 296 of file subprocesses.cpp.
References v.
Referenced by clear(), insert(), operator=(), and ~arg_vector().
 {
   if (v)
   {
     for (unsigned i = 0; v[i]; i++)
       delete[] v[i];
     delete[] v;
     v = 0;
   }
 }
std::string arg_vector::image (void) const
Definition at line 335 of file subprocesses.cpp.
References make_argument(), size(), and v.
Referenced by operator<<().
 {
   std::string result;
   for (unsigned i = 0; i < size(); i++)
   {
     if (i) result += ' ';
     result += make_argument(v[i]);
   }
   return result;
 }
void arg_vector::insert (unsigned index, const std::string & str)
Definition at line 264 of file subprocesses.cpp.
References clear(), copy_string(), DEBUG_ASSERT, size(), and v.
Referenced by operator+=(), and operator-=().
 {
   DEBUG_ASSERT(index <= size());
   // copy up to but not including index, then add the new argument, then copy the rest
   char** new_argv = new char*[size()+2];
   unsigned i = 0;
   for ( ; i < index; i++)
     new_argv[i] = copy_string(v[i]);
   new_argv[index] = copy_string(str.c_str());
   for ( ; i < size(); i++)
     new_argv[i+1] = copy_string(v[i]);
   new_argv[i+1] = 0;
   clear();
   v = new_argv;
 }
arg_vector::operator char ** (void) const
Definition at line 314 of file subprocesses.cpp.
 {
   return v;
 }
arg_vector & arg_vector::operator+= (const std::string & str)
Definition at line 252 of file subprocesses.cpp.
References insert(), and size().
Referenced by operator=().
 {
   insert(size(), str);
   return *this;
 }
arg_vector & arg_vector::operator-= (const std::string & str)
Definition at line 258 of file subprocesses.cpp.
References insert().
 {
   insert(0, str);
   return *this;
 }
arg_vector & arg_vector::operator= (const arg_vector & a)
Definition at line 222 of file subprocesses.cpp.
References v.
Referenced by operator=().
 {
   return *this = a.v;
 }
arg_vector & arg_vector::operator= (char ** a)
Definition at line 227 of file subprocesses.cpp.
References clear().
 {
   clear();
   for (unsigned i = 0; a[i]; i++)
     operator += (a[i]);
   return *this;
 }
arg_vector & arg_vector::operator= (const std::string & command)
Definition at line 235 of file subprocesses.cpp.
References clear(), get_argument(), operator+=(), and skip_white().
 {
   clear();
   for (unsigned i = 0; i < command.size(); )
   {
     std::string argument = get_argument(command, i);
     operator += (argument);
     skip_white(command, i);
   }
   return *this;
 }
arg_vector & arg_vector::operator= (const char * command)
Definition at line 247 of file subprocesses.cpp.
References operator=().
 {
   return operator = (std::string(command));
 }
char * arg_vector::operator[] (unsigned index) const
Definition at line 324 of file subprocesses.cpp.
References DEBUG_ASSERT, size(), and v.
Referenced by argv0().
 {
   DEBUG_ASSERT(index < size());
   return v[index];
 }
unsigned arg_vector::size (void) const
Definition at line 307 of file subprocesses.cpp.
References v.
Referenced by clear(), image(), insert(), operator+=(), operator[](), subprocess::spawn(), and async_subprocess::spawn().
 {
   unsigned i = 0;
   if (v) while (v[i]) i++;
   return i;
 }
Friends And Related Function Documentation
otext& operator<< (otext & , const arg_vector &) friend
Definition at line 346 of file subprocesses.cpp.
 {
   return t << a.image();
 }
Member Data Documentation
char** arg_vector::v private
Definition at line 34 of file subprocesses.hpp.
Referenced by arg_vector(), argv(), clear(), image(), insert(), operator=(), operator[](), and size().
The documentation for this class was generated from the following files:
include/stlplus/subprocesses.hpp
include/stlplus/subprocesses.cpp