Visible: rcMovieConverter Class Reference
rcMovieConverter Class Reference abstract
#include <include/visual/rc_movieconverter.h>
Public Member Functions
rcMovieConverter (bool verbose=true, rcCarbonLock *l=NULL, rcProgressIndicator *p=NULL)
virtual ~rcMovieConverter ()
bool verbose () const
rcSharedFrameBufPtr clippedFrame (rcSharedFrameBufPtr orig, rcMovieConverterOptions opt)
void verbose (bool v)
virtual rcMovieConverterError convert (const std::string &inputFile, const std::string &outputFile)=0
Static Public Member Functions
static std::string getErrorString (const rcMovieConverterError &error)
static bool isReifyMovie (const std::string &name)
static bool isImageCollection (const std::string &name)
Protected Member Functions
void lock ()
void unlock ()
Protected Attributes
rcMovieConverterError mLastError
rcProgressIndicator * mProgress
bool mVerbose
rcCarbonLock * mCarbonLock
Detailed Description
Definition at line 122 of file rc_movieconverter.h.
Constructor & Destructor Documentation
rcMovieConverter::rcMovieConverter (bool verbose = true, rcCarbonLock * l = NULL, rcProgressIndicator * p = NULL) inline
Definition at line 125 of file rc_movieconverter.h.
                                                                                                    :
mLastError(eMovieConverterErrorUnknown), mProgress(p), mVerbose(verbose), mCarbonLock(l) {}
virtual rcMovieConverter::~rcMovieConverter () inline virtual
Definition at line 127 of file rc_movieconverter.h.
 {}
Member Function Documentation
rcSharedFrameBufPtr rcMovieConverter::clippedFrame (rcSharedFrameBufPtr orig, rcMovieConverterOptions opt)
Definition at line 201 of file rc_movieconverter.cpp.
References rcMovieConverterOptions::clipRect(), rcWindow::copyPixelsFromWindow(), rcFrame::depth(), rcRectangle< T >::height(), rcFrame::setTimestamp(), rcFrame::timestamp(), and rcRectangle< T >::width().
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), and rcMovieConverterToRfy::createRfyMovie().
 {
     const rcRect& clipRect = opt.clipRect();
     if ( clipRect.width() > 0 && clipRect.height() > 0 ) {
         // Clip
         rcWindow w( orig, clipRect );
         // Make a copy so input pixels are not mutated
         rcSharedFrameBufPtr newBuf = new rcFrame( clipRect.width(), clipRect.height(), orig->depth() );
         newBuf->setTimestamp( orig->timestamp() );
         rcWindow newW( newBuf );
         newW.copyPixelsFromWindow( w );
         return newBuf;
     }
     return orig;
 }
virtual rcMovieConverterError rcMovieConverter::convert (const std::string & inputFile, const std::string & outputFile) pure virtual
Implemented in rcMovieConverterToRfy, and rcMovieConverterToQT.
std::string rcMovieConverter::getErrorString (const rcMovieConverterError & error) static
Definition at line 142 of file rc_movieconverter.cpp.
References eMovieConverterErrorClose, eMovieConverterErrorExists, eMovieConverterErrorFlush, eMovieConverterErrorHeaderWrite, eMovieConverterErrorInternal, eMovieConverterErrorNull, eMovieConverterErrorOK, eMovieConverterErrorOpen, eMovieConverterErrorRead, eMovieConverterErrorSeek, eMovieConverterErrorUnknown, eMovieConverterErrorUnsupported, eMovieConverterErrorWrite, and eMovieConverterErrorWriteOpen.
Referenced by rcExperimentImpl::exportMovie(), rfConvertMovie(), and rfConvertTwoMovies().
 {
     switch ( error ) {
         case eMovieConverterErrorOK:
             return std::string("rcMovieConverterToRfy: OK");
         case eMovieConverterErrorUnknown:
             return std::string("rcMovieConverterToRfy: unknown error");
         case eMovieConverterErrorInternal:
             return std::string("rcMovieConverterToRfy: internal error");
         case eMovieConverterErrorNull:
             return std::string("rcMovieConverterToRfy: NULL error");
         case eMovieConverterErrorHeaderWrite:
             return std::string("rcMovieConverterToRfy: cannot write output file header");
         case eMovieConverterErrorExists:
             return std::string("rcMovieConverterToRfy: output file exists");
         case eMovieConverterErrorOpen:
             return std::string("rcMovieConverterToRfy: cannot open input file");
         case eMovieConverterErrorRead:
             return std::string("rcMovieConverterToRfy: cannot read input file");
         case eMovieConverterErrorWriteOpen:
             return std::string("rcMovieConverterToRfy: cannot open output file");
         case eMovieConverterErrorWrite:
             return std::string("rcMovieConverterToRfy: cannot write to output file");
         case eMovieConverterErrorSeek:
             return std::string("rcMovieConverterToRfy: seek failed for input file");
         case eMovieConverterErrorClose:
             return std::string("rcMovieConverterToRfy: cannot close output file");
         case eMovieConverterErrorFlush:
             return std::string("rcMovieConverterToRfy: cannot flush output file");
         case eMovieConverterErrorUnsupported:
             return std::string("rcMovieConverterToRfy: unsupported operation");
     }
     return std::string("rcMovieConverterToRfy: undefined error");
 }
bool rcMovieConverter::isImageCollection (const std::string & name) static
Definition at line 191 of file rc_movieconverter.cpp.
Referenced by rcMovieConverterToRfy::convert().
 {
     if ( !name.empty() ) {
         if ( strchr( name.c_str(), ';' ) )
             return true;
     }
     return false;
 }
bool rcMovieConverter::isReifyMovie (const std::string & name) static
Definition at line 179 of file rc_movieconverter.cpp.
Referenced by rcMovieConverterToQT::convert(), and rcMovieConverterToRfy::convert().
 {
     if ( !name.empty() ) {
         int lth = name.size();
         if ( lth > 7 && !strcasecmp(&name[lth-7], ".rfymov")) {
             return true;
         }
     }
     return false;
 }
void rcMovieConverter::lock () protected
Definition at line 221 of file rc_movieconverter.cpp.
References rcCarbonLock::lock(), and mCarbonLock.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), and rcMovieConverterToQT::createQTMovie().
 {
     if ( mCarbonLock )
         mCarbonLock->lock();
 }
void rcMovieConverter::unlock () protected
Definition at line 228 of file rc_movieconverter.cpp.
References mCarbonLock, and rcCarbonLock::unlock().
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), and rcMovieConverterToQT::createQTMovie().
 {
     if ( mCarbonLock )
         mCarbonLock->unlock();
 }
bool rcMovieConverter::verbose () const inline
Definition at line 136 of file rc_movieconverter.h.
References mVerbose.
Referenced by rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), rcMovieConverterToQT::createQTMovie(), and rcMovieConverterToRfy::createRfyMovie().
 { return mVerbose; }
void rcMovieConverter::verbose (bool v) inline
Definition at line 142 of file rc_movieconverter.h.
References mVerbose.
 { mVerbose = v; }
Member Data Documentation
rcCarbonLock* rcMovieConverter::mCarbonLock protected
Definition at line 159 of file rc_movieconverter.h.
Referenced by rcMovieConverterToRfy::convert(), lock(), and unlock().
rcMovieConverterError rcMovieConverter::mLastError protected
Definition at line 156 of file rc_movieconverter.h.
Referenced by rcMovieConverterToQT::convert(), and rcMovieConverterToRfy::convert().
rcProgressIndicator* rcMovieConverter::mProgress protected
Definition at line 157 of file rc_movieconverter.h.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), and rcMovieConverterToRfy::createRfyMovie().
bool rcMovieConverter::mVerbose protected
Definition at line 158 of file rc_movieconverter.h.
Referenced by verbose().
The documentation for this class was generated from the following files:
include/visual/rc_movieconverter.h
src/visual/code/rc_movieconverter.cpp