Visible: rc2DTrackRenderInfo Class Reference
rc2DTrackRenderInfo Class Reference
#include <include/visUI/rc_trackrender.h>
Public Member Functions
rc2DTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, const rcFPair &min, const rcFPair &max, const QRect &dataRect)
const rcFPair & minValue () const
const rcFPair & maxValue () const
const std::string & xAxisName () const
const std::string & yAxisName () const
const std::string & xAxisNameNeg () const
const std::string & yAxisNameNeg () const
const std::string & xFormatString () const
const std::string & yFormatString () const
const rcIPair & tickCount () const
void minValue (const rcFPair &v)
void maxValue (const rcFPair &v)
void xAxisName (const std::string &n)
void yAxisName (const std::string &n)
void xAxisNameNeg (const std::string &n)
void yAxisNameNeg (const std::string &n)
void xFormatString (const std::string &s)
void yFormatString (const std::string &s)
void tickCount (const rcIPair &c)
Public Member Functions inherited from rcTrackRenderInfo
rcTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, rcTimestamp startTime, rcTimestamp endTime, const QRect &dataRect, bool logDisplay=false)
Protected Attributes
rcFPair mMinValue
rcFPair mMaxValue
std::string mXAxisName
std::string mYAxisName
std::string mXAxisNameNeg
std::string mYAxisNameNeg
std::string mXFormatString
std::string mYFormatString
rcIPair mTickCount
Additional Inherited Members
Public Attributes inherited from rcTrackRenderInfo
rcTrack * _track
rcTimestamp _startTime
rcTimestamp _endTime
double _minValue
double _maxValue
QRect _dataRect
QPen _tickMarkPen
QPen _dataPen
bool _isEnabled
bool _isHilited
QFont _tickMarkFont
bool _logDisplay
Detailed Description
Definition at line 49 of file rc_trackrender.h.
Constructor & Destructor Documentation
rc2DTrackRenderInfo::rc2DTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack * track, const rcFPair & min, const rcFPair & max, const QRect & dataRect)
Definition at line 47 of file rc_trackrender.cpp.
                                                                   :
         rcTrackRenderInfo( trackGroupNo, trackNo, track, cZeroTime, cZeroTime, dataRect ),
         mMinValue( min ), mMaxValue( max ),
         mXAxisName( "X" ), mYAxisName( "Y" ),
         mXAxisNameNeg( "X" ), mYAxisNameNeg( "Y" ),
         mXFormatString( "%.0f" ), mYFormatString( "%.0f" ),
         mTickCount( rcIPair( 10, 10 ) )
 {
}
Member Function Documentation
const rcFPair& rc2DTrackRenderInfo::maxValue () const inline
Definition at line 61 of file rc_trackrender.h.
References mMaxValue.
Referenced by rcPositionTrackRenderInfo::rcPositionTrackRenderInfo().
 { return mMaxValue; }
void rc2DTrackRenderInfo::maxValue (const rcFPair & v) inline
Definition at line 72 of file rc_trackrender.h.
References mMaxValue.
 { mMaxValue = v; }
const rcFPair& rc2DTrackRenderInfo::minValue () const inline
Definition at line 60 of file rc_trackrender.h.
References mMinValue.
Referenced by rcPositionTrackRenderInfo::rcPositionTrackRenderInfo().
 { return mMinValue; }
void rc2DTrackRenderInfo::minValue (const rcFPair & v) inline
Definition at line 71 of file rc_trackrender.h.
References mMinValue.
 { mMinValue = v; }
const rcIPair& rc2DTrackRenderInfo::tickCount () const inline
Definition at line 68 of file rc_trackrender.h.
References mTickCount.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), and rcDistanceTrackRenderInfo::init().
 { return mTickCount; }
void rc2DTrackRenderInfo::tickCount (const rcIPair & c) inline
Definition at line 79 of file rc_trackrender.h.
References mTickCount.
 { mTickCount = c; }
const std::string& rc2DTrackRenderInfo::xAxisName () const inline
Definition at line 62 of file rc_trackrender.h.
References mXAxisName.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), and rcDistanceTrackRenderInfo::init().
 { return mXAxisName; }
void rc2DTrackRenderInfo::xAxisName (const std::string & n) inline
Definition at line 73 of file rc_trackrender.h.
References mXAxisName.
 { mXAxisName = n; }
const std::string& rc2DTrackRenderInfo::xAxisNameNeg () const inline
Definition at line 64 of file rc_trackrender.h.
References mXAxisNameNeg.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), and rcDistanceTrackRenderInfo::init().
 { return mXAxisNameNeg; }
void rc2DTrackRenderInfo::xAxisNameNeg (const std::string & n) inline
Definition at line 75 of file rc_trackrender.h.
References mXAxisNameNeg.
 { mXAxisNameNeg = n; }
const std::string& rc2DTrackRenderInfo::xFormatString () const inline
Definition at line 66 of file rc_trackrender.h.
References mXFormatString.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), rcDistanceTrackRenderInfo::init(), and rcPositionTrackRenderInfo::rcPositionTrackRenderInfo().
 { return mXFormatString; }
void rc2DTrackRenderInfo::xFormatString (const std::string & s) inline
Definition at line 77 of file rc_trackrender.h.
References mXFormatString.
 { mXFormatString = s; }
const std::string& rc2DTrackRenderInfo::yAxisName () const inline
Definition at line 63 of file rc_trackrender.h.
References mYAxisName.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), and rcDistanceTrackRenderInfo::init().
 { return mYAxisName; }
void rc2DTrackRenderInfo::yAxisName (const std::string & n) inline
Definition at line 74 of file rc_trackrender.h.
References mYAxisName.
 { mYAxisName = n; }
const std::string& rc2DTrackRenderInfo::yAxisNameNeg () const inline
Definition at line 65 of file rc_trackrender.h.
References mYAxisNameNeg.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), and rcDistanceTrackRenderInfo::init().
 { return mYAxisNameNeg; }
void rc2DTrackRenderInfo::yAxisNameNeg (const std::string & n) inline
Definition at line 76 of file rc_trackrender.h.
References mYAxisNameNeg.
 { mYAxisNameNeg = n; }
const std::string& rc2DTrackRenderInfo::yFormatString () const inline
Definition at line 67 of file rc_trackrender.h.
References mYFormatString.
Referenced by rcSpeedDirectionTrackRenderInfo::init(), rcSpeedDirectionCompassTrackRenderInfo::init(), rcPersistenceCompassTrackRenderInfo::init(), rcPersistenceHistogramTrackRenderInfo::init(), rcACICompassTrackRenderInfo::init(), rcACIHistogramTrackRenderInfo::init(), rcDistanceTrackRenderInfo::init(), and rcPositionTrackRenderInfo::rcPositionTrackRenderInfo().
 { return mYFormatString; }
void rc2DTrackRenderInfo::yFormatString (const std::string & s) inline
Definition at line 78 of file rc_trackrender.h.
References mYFormatString.
 { mYFormatString = s; }
Member Data Documentation
rcFPair rc2DTrackRenderInfo::mMaxValue protected
Definition at line 83 of file rc_trackrender.h.
Referenced by maxValue().
rcFPair rc2DTrackRenderInfo::mMinValue protected
Definition at line 82 of file rc_trackrender.h.
Referenced by minValue().
rcIPair rc2DTrackRenderInfo::mTickCount protected
Definition at line 90 of file rc_trackrender.h.
Referenced by tickCount().
std::string rc2DTrackRenderInfo::mXAxisName protected
Definition at line 84 of file rc_trackrender.h.
Referenced by xAxisName().
std::string rc2DTrackRenderInfo::mXAxisNameNeg protected
Definition at line 86 of file rc_trackrender.h.
Referenced by xAxisNameNeg().
std::string rc2DTrackRenderInfo::mXFormatString protected
Definition at line 88 of file rc_trackrender.h.
Referenced by xFormatString().
std::string rc2DTrackRenderInfo::mYAxisName protected
Definition at line 85 of file rc_trackrender.h.
Referenced by yAxisName().
std::string rc2DTrackRenderInfo::mYAxisNameNeg protected
Definition at line 87 of file rc_trackrender.h.
Referenced by yAxisNameNeg().
std::string rc2DTrackRenderInfo::mYFormatString protected
Definition at line 89 of file rc_trackrender.h.
Referenced by yFormatString().
The documentation for this class was generated from the following files:
include/visUI/rc_trackrender.h
src/visible/qt/rc_trackrender.cpp