Visible: rcEngineMoviePlayback Class Reference
rcEngineMoviePlayback Class Reference
#include <include/visiCore/rc_engineimplplayback.h>
Classes
class pbRec
Public Member Functions
rcEngineMoviePlayback (rcEngineImpl *engine, const rcMoviePlaybackCtrlReader &playbackCtrl, rcEngineObserver *observer, double msPerUpdate, bool noSkip)
virtual ~rcEngineMoviePlayback ()
void setupTimeCtrlPlayback (rcVideoCache &cache, rcTimestamp startTime, int32 rateMultiplier, uint32 prefetchCnt)
void reset ()
const rcMoviePlaybackStatusReader & playbackStatus () const
virtual void run ()
Public Member Functions inherited from rcRunnable
rcRunnable ()
virtual ~rcRunnable ()
void requestSeppuku ()
void clearSeppuku ()
Private Member Functions
void genMovieData (vector< pbRec > &movieData, double msPerUpdate)
void playbackCleanup (rcVideoCacheError error, uint32 eIndex)
Private Attributes
rcEngineImpl * _engine
const rcMoviePlaybackCtrlReader & _playbackCtrl
rcMoviePlaybackStatus _playbackStatus
rcEngineObserver * _observer
rcTimestamp _firstTime
int32 _prefetchCnt
int32 _rateMultiplier
vector< uint32 > _timeline
double _startTimeInMS
double _msPerUpdate
double _msPerFrame
const bool _noSkip
rcVideoCache * _cacheP
Additional Inherited Members
Protected Member Functions inherited from rcRunnable
bool seppukuRequested ()
Detailed Description
Definition at line 21 of file rc_engineimplplayback.h.
Constructor & Destructor Documentation
rcEngineMoviePlayback::rcEngineMoviePlayback (rcEngineImpl * engine, const rcMoviePlaybackCtrlReader & playbackCtrl, rcEngineObserver * observer, double msPerUpdate, bool noSkip)
Definition at line 19 of file rc_engineimplplayback.cpp.
References _engine, _msPerUpdate, and rmAssert.
   : _engine(engine), _playbackCtrl(playbackCtrl), _observer(observer),
     _firstTime(-1.0), _prefetchCnt(0), _msPerUpdate(msPerUpdate),
     _msPerFrame(0), _noSkip(noSkip), _cacheP(0)
 {
   rmAssert(_engine);
   rmAssert(_msPerUpdate >= 1.0);
 }
virtual rcEngineMoviePlayback::~rcEngineMoviePlayback () inline virtual
Definition at line 28 of file rc_engineimplplayback.h.
 {}
Member Function Documentation
void rcEngineMoviePlayback::genMovieData (vector< pbRec > & movieData, double msPerUpdate) private
Definition at line 205 of file rc_engineimplplayback.cpp.
References _msPerFrame, _rateMultiplier, _startTimeInMS, _timeline, and rmAssert.
Referenced by run().
 {
   uint32 updateCnt = 1;
   uint32 curFrame = 0xFFFFFFFF;
   movieData.resize(0);
   double curTime = (_startTimeInMS < 0.0) ? 0.0 : _startTimeInMS;
   uint32 slotIndex = (uint32)(curTime/_msPerFrame + .5);
   if (slotIndex >= _timeline.size()) {
     slotIndex = _timeline.size() - 1;
     curTime = slotIndex * _msPerFrame;
   }
   while (slotIndex < _timeline.size()) {
     if (curFrame != _timeline[slotIndex]) {
       if (!movieData.empty()) {
     rmAssert(movieData.back().frameIndex == curFrame);
     movieData.back().nextUpdateCnt = updateCnt;
       }
       updateCnt = 0;
       curFrame = _timeline[slotIndex];
       movieData.push_back(pbRec(curFrame, 1));
     }
     updateCnt++;
     curTime += msPerUpdate * _rateMultiplier;
     slotIndex = (uint32)(curTime/_msPerFrame + .5);
   }
 }
void rcEngineMoviePlayback::playbackCleanup (rcVideoCacheError error, uint32 eIndex) private
Definition at line 234 of file rc_engineimplplayback.cpp.
References _engine, _observer, _playbackStatus, _timeline, eMoviePlaybackState_Exit, endl(), eVideoCacheErrorOK, rcVideoCache::getErrorString(), rcEngineObserver::notifyStatus(), rcMoviePlaybackStatus::state(), and rcEngineImpl::stop().
Referenced by run().
 {
   if (error != eVideoCacheErrorOK)
     cerr << "Error reading frame during playback at: " << eIndex << ". Error: "
      << rcVideoCache::getErrorString(error) << endl;
   _timeline.resize(0);
   _playbackStatus.state(eMoviePlaybackState_Exit);
   _engine->stop();
   _observer->notifyStatus("Ready");
 }
const rcMoviePlaybackStatusReader& rcEngineMoviePlayback::playbackStatus () const inline
Definition at line 42 of file rc_engineimplplayback.h.
References _playbackStatus.
Referenced by rcEngineImpl::getSettingValue(), and rcEngineImpl::setSettingValue().
   { return _playbackStatus; }
void rcEngineMoviePlayback::reset (void) inline
Definition at line 35 of file rc_engineimplplayback.h.
References _playbackStatus, eMoviePlaybackState_Exit, eMoviePlaybackState_Uninitialized, rcMoviePlaybackStatusReader::getState(), and rcMoviePlaybackStatus::state().
Referenced by rcEngineImpl::getSettingValue().
                {
     if (_playbackStatus.getState() == eMoviePlaybackState_Exit)
       _playbackStatus.state(eMoviePlaybackState_Uninitialized);
   }
void rcEngineMoviePlayback::run (void) virtual
Implements rcRunnable.
Definition at line 64 of file rc_engineimplplayback.cpp.
References _cacheP, _engine, _firstTime, _msPerFrame, _msPerUpdate, _noSkip, _observer, _playbackStatus, _prefetchCnt, _rateMultiplier, _startTimeInMS, _timeline, abs(), eMoviePlaybackState_Initialized, eMoviePlaybackState_Playback, eVideoCacheErrorOK, eVideoCacheStatusOK, genMovieData(), rcVideoCache::getFrame(), rcMoviePlaybackStatusReader::getState(), rcTimingInfo::nextPass(), rcEngineObserver::notifyTime(), playbackCleanup(), rcSharedFrameBufPtr::prefetch(), rmAssert, rcRunnable::seppukuRequested(), rcThread::sleep(), rcEngineImpl::start(), rcMoviePlaybackStatus::state(), rcEngineObserver::timeEventCount(), and rcFrame::timestamp().
 {
   _engine->start();
   rmAssert(_playbackStatus.getState() == eMoviePlaybackState_Initialized);
   rmAssert(_cacheP);
   _playbackStatus.state(eMoviePlaybackState_Playback);
   /* If the requested update rate is slower than the maximum allowed,
    * adjust the actual update rate to match the requested update rate.
    */
   double rateMult = abs(_rateMultiplier);
   double msPerUpdate =
     (_msPerUpdate > _msPerFrame/rateMult) ? _msPerUpdate : _msPerFrame/rateMult;
   /* Calculate which frames to display and when.
    */
   vector<pbRec> movieData;
   genMovieData(movieData, msPerUpdate);
   rmAssert(!movieData.empty());
 #if 0
   fprintf(stderr, "Start Time %f ms MS per Update B: %f A: %f MS per Frame %f\n",
       _startTimeInMS, _msPerUpdate, msPerUpdate, _msPerFrame);
   fprintf(stderr, "\nTimeline:\n");
   for (uint32 i = 0; i < _timeline.size(); i++) {
     if ((i & 0x7) == 0)
       fprintf(stderr, "\n%02d:", i);
     fprintf(stderr, " %04d", _timeline[i]);
   }
   fprintf(stderr, "\n");
   uint32 totUpdates = 0;
   fprintf(stderr, "\nMovie Data:\n");
   for (uint32 i = 0; i < movieData.size(); i++) {
     if ((i & 0x7) == 0)
       fprintf(stderr, "\n%02d:", i);
     fprintf(stderr, " (%04d,%02d)", movieData[i].frameIndex,
         movieData[i].nextUpdateCnt);
     totUpdates += movieData[i].nextUpdateCnt;
   }
   fprintf(stderr, "\n");
   fprintf(stderr, "Tot Updates %d Exp Time %f\n", totUpdates,
       totUpdates*msPerUpdate);
   playbackCleanup(eVideoCacheErrorOK, 99);
   return;
 #endif
   /* Start out by prefetching the first few frames.
    */
   rcVideoCacheStatus status;
   rcVideoCacheError error;
   uint32 prefetchCnt = (_prefetchCnt <= (int32)movieData.size()) ?
     _prefetchCnt : movieData.size();
   uint32 curPrefetch = 0;
   for ( ; curPrefetch < prefetchCnt; curPrefetch++) {
     rcSharedFrameBufPtr buf;
     status = _cacheP->getFrame(movieData[curPrefetch].frameIndex, buf,
                    &error, true);
     if (status != eVideoCacheStatusOK) {
       playbackCleanup(error, 0);
       return;
     }
   } // End of: for ( ; curPrefetch < prefetchCnt; curPrefetch++) {
   /* Main playback loop.
    */
   uint32 delayCnt = 0, droppedCnt = 0; // Debugging info
   rcTimingInfo profile(7, movieData.size() + 1); // Debugging info
   for (uint32 curDisplay = 0;
        (curDisplay < movieData.size()) && !seppukuRequested();
        curDisplay++) {
     profile.nextPass(false);
     /* Read the count of unprocessed time events. If _noSkip is true,
      * wait for the count to go to 0.
      */
     int32 backupCnt = _observer->timeEventCount();
     while (backupCnt && _noSkip) {
       delayCnt++;
       rcThread::sleep((uint32)(msPerUpdate + .5));
       backupCnt = _observer->timeEventCount();
     }
     profile.touch(0);
     /* Prefetch the next frame.
      */
     if (curPrefetch < movieData.size()) {
       rcSharedFrameBufPtr pBuf;
       status = _cacheP->getFrame(movieData[curPrefetch].frameIndex, pBuf,
                  &error, false);
       if (status != eVideoCacheStatusOK) {
     playbackCleanup(error, 1);
     return;
       }
       profile.touch(1);
       pBuf.prefetch();
       profile.touch(2);
       curPrefetch++;
     } // End of: if (curPrefetch < movieData.size()) {
     /* If display side isn't backed up, send new time event to cause
      * next frame to display. Note that backupCnt will only be true if
      * _noSkip is false.
      */
     if (backupCnt)
       droppedCnt++;
     else {
       rcSharedFrameBufPtr buf;
       profile.touch(3);
       status = _cacheP->getFrame(movieData[curDisplay].frameIndex, buf,
                  &error, true);
       profile.touch(4);
       if (status != eVideoCacheStatusOK) {
     playbackCleanup(error, 2);
     return;
       }
       /* Among other things, this causes monitor to update to new frame.
        */
       _observer->notifyTime(buf->timestamp() - _firstTime);
       profile.touch(5);
     } // End of: if (!backupCnt) {
     /* Let frame display for the appropriate amount of time.
      */
     profile.touch(6);
     uint32 msToSleep =
       (uint32)(msPerUpdate * movieData[curDisplay].nextUpdateCnt + .5);
     rcThread::sleep(msToSleep);
   }
   fprintf(stderr, "dc %d dt %d sc %d\n", delayCnt,
       delayCnt*(uint32)(msPerUpdate + .5), droppedCnt);
   //  profile.printInfo(movieData.size() + 1);
   playbackCleanup(eVideoCacheErrorOK, 3);
 }
void rcEngineMoviePlayback::setupTimeCtrlPlayback (rcVideoCache & cache, rcTimestamp startTime, int32 rateMultiplier, uint32 prefetchCnt)
Definition at line 32 of file rc_engineimplplayback.cpp.
References _cacheP, _firstTime, _msPerFrame, _playbackStatus, _prefetchCnt, _rateMultiplier, _startTimeInMS, _timeline, eMoviePlaybackState_Initialized, eMoviePlaybackState_Playback, endl(), eVideoCacheStatusOK, rcVideoCache::firstTimestamp(), rcVideoCache::getErrorString(), rcMoviePlaybackStatusReader::getState(), rfGenerateTimeline(), rmAssert, rcTimestamp::secs(), and rcMoviePlaybackStatus::state().
Referenced by rcEngineImpl::setSettingValue().
 {
   rmAssert(_playbackStatus.getState() != eMoviePlaybackState_Playback);
   rmAssert(rateMultiplier);
   _rateMultiplier = rateMultiplier;
   if (!rfGenerateTimeline(_timeline, _msPerFrame, cache))
     return;
   rcVideoCacheStatus status;
   rcVideoCacheError error;
   status = cache.firstTimestamp(_firstTime, &error);
   if (status != eVideoCacheStatusOK) {
     cerr << "Couldn't read first timestamp. Error: "
      << rcVideoCache::getErrorString(error) << endl;
     return;
   }
   _startTimeInMS = startTime.secs() * 1000;
   _prefetchCnt = prefetchCnt ? prefetchCnt : 1;
   _cacheP = &cache;
   _playbackStatus.state(eMoviePlaybackState_Initialized);
 }
Member Data Documentation
rcVideoCache* rcEngineMoviePlayback::_cacheP private
Definition at line 83 of file rc_engineimplplayback.h.
Referenced by run(), and setupTimeCtrlPlayback().
rcEngineImpl* rcEngineMoviePlayback::_engine private
Definition at line 71 of file rc_engineimplplayback.h.
Referenced by playbackCleanup(), rcEngineMoviePlayback(), and run().
rcTimestamp rcEngineMoviePlayback::_firstTime private
Definition at line 75 of file rc_engineimplplayback.h.
Referenced by run(), and setupTimeCtrlPlayback().
double rcEngineMoviePlayback::_msPerFrame private
Definition at line 81 of file rc_engineimplplayback.h.
Referenced by genMovieData(), run(), and setupTimeCtrlPlayback().
double rcEngineMoviePlayback::_msPerUpdate private
Definition at line 80 of file rc_engineimplplayback.h.
Referenced by rcEngineMoviePlayback(), and run().
const bool rcEngineMoviePlayback::_noSkip private
Definition at line 82 of file rc_engineimplplayback.h.
Referenced by run().
rcEngineObserver* rcEngineMoviePlayback::_observer private
Definition at line 74 of file rc_engineimplplayback.h.
Referenced by playbackCleanup(), and run().
const rcMoviePlaybackCtrlReader& rcEngineMoviePlayback::_playbackCtrl private
Definition at line 72 of file rc_engineimplplayback.h.
rcMoviePlaybackStatus rcEngineMoviePlayback::_playbackStatus private
Definition at line 73 of file rc_engineimplplayback.h.
Referenced by playbackCleanup(), playbackStatus(), reset(), run(), and setupTimeCtrlPlayback().
int32 rcEngineMoviePlayback::_prefetchCnt private
Definition at line 76 of file rc_engineimplplayback.h.
Referenced by run(), and setupTimeCtrlPlayback().
int32 rcEngineMoviePlayback::_rateMultiplier private
Definition at line 77 of file rc_engineimplplayback.h.
Referenced by genMovieData(), run(), and setupTimeCtrlPlayback().
double rcEngineMoviePlayback::_startTimeInMS private
Definition at line 79 of file rc_engineimplplayback.h.
Referenced by genMovieData(), run(), and setupTimeCtrlPlayback().
vector<uint32> rcEngineMoviePlayback::_timeline private
Definition at line 78 of file rc_engineimplplayback.h.
Referenced by genMovieData(), playbackCleanup(), run(), and setupTimeCtrlPlayback().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplplayback.h
src/visible/src/rc_engineimplplayback.cpp