Visible: rcCameraProperty Class Reference
rcCameraProperty Class Reference
#include <include/visual/rc_dcam.h>
Public Member Functions
rcCameraProperty ()
rcCameraProperty (UInt32 type, UInt32 cntl)
const UInt32 & type () const
const UInt32 & cntl () const
const UInt32 & minValue () const
const UInt32 & maxValue () const
const UInt32 & curValue () const
const Boolean & canOnePush () const
const Boolean & canReadOut () const
const Boolean & canOnOff () const
const Boolean & canAuto () const
const Boolean & canManual () const
const bool & active () const
bool operator< (const rcCameraProperty &o) const
UInt32 & type ()
UInt32 & cntl ()
UInt32 & minValue ()
UInt32 & maxValue ()
UInt32 & curValue ()
Boolean & canOnePush ()
Boolean & canReadOut ()
Boolean & canOnOff ()
Boolean & canAuto ()
Boolean & canManual ()
bool & active ()
Friends
ostream & operator<< (ostream &os, const rcCameraProperty &c)
Detailed Description
Definition at line 162 of file rc_dcam.h.
Constructor & Destructor Documentation
rcCameraProperty::rcCameraProperty () inline
Definition at line 165 of file rc_dcam.h.
 {};
rcCameraProperty::rcCameraProperty (UInt32 type, UInt32 cntl) inline
Definition at line 166 of file rc_dcam.h.
     :
         boost::tuple< boost::tuple<UInt32,UInt32,UInt32,UInt32,UInt32>, Boolean,Boolean,Boolean,Boolean,Boolean,bool> (make_tuple (make_tuple(type,cntl,(UInt32) -1, UInt32(-1), UInt32(-1)), false,false,false,false,false,false) )
{ }
Member Function Documentation
const bool& rcCameraProperty::active () const inline
Definition at line 183 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), InitializeMungData2(), operator<<(), rfGetCameraCapabilities(), and rfGetCameraInformation().
 { return get<6>(); }
bool& rcCameraProperty::active () inline
Definition at line 206 of file rc_dcam.h.
 { return get<6>(); }
const Boolean& rcCameraProperty::canAuto () const inline
Definition at line 181 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<4>(); }
Boolean& rcCameraProperty::canAuto () inline
Definition at line 204 of file rc_dcam.h.
 { return get<4>(); }
const Boolean& rcCameraProperty::canManual () const inline
Definition at line 182 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<5>(); }
Boolean& rcCameraProperty::canManual () inline
Definition at line 205 of file rc_dcam.h.
 { return get<5>(); }
const Boolean& rcCameraProperty::canOnePush () const inline
Definition at line 178 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<1>(); }
Boolean& rcCameraProperty::canOnePush () inline
Definition at line 201 of file rc_dcam.h.
 { return get<1>(); }
const Boolean& rcCameraProperty::canOnOff () const inline
Definition at line 180 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<3>(); }
Boolean& rcCameraProperty::canOnOff () inline
Definition at line 203 of file rc_dcam.h.
 { return get<3>(); }
const Boolean& rcCameraProperty::canReadOut () const inline
Definition at line 179 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<2>(); }
Boolean& rcCameraProperty::canReadOut () inline
Definition at line 202 of file rc_dcam.h.
 { return get<2>(); }
const UInt32& rcCameraProperty::cntl () const inline
Definition at line 173 of file rc_dcam.h.
Referenced by operator<<(), and setProperty().
 { return get<0>().get<1>(); }
UInt32& rcCameraProperty::cntl () inline
Definition at line 196 of file rc_dcam.h.
 { return get<0>().get<1>(); }
const UInt32& rcCameraProperty::curValue () const inline
Definition at line 176 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), operator<<(), and setProperty().
 { return get<0>().get<4>(); }
UInt32& rcCameraProperty::curValue () inline
Definition at line 199 of file rc_dcam.h.
 { return get<0>().get<4>(); }
const UInt32& rcCameraProperty::maxValue () const inline
Definition at line 175 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<0>().get<3>(); }
UInt32& rcCameraProperty::maxValue () inline
Definition at line 198 of file rc_dcam.h.
 { return get<0>().get<3>(); }
const UInt32& rcCameraProperty::minValue () const inline
Definition at line 174 of file rc_dcam.h.
Referenced by GetCameraProperty(), rcCameraMapper::GetCameraProperty(), and operator<<().
 { return get<0>().get<2>(); }
UInt32& rcCameraProperty::minValue () inline
Definition at line 197 of file rc_dcam.h.
 { return get<0>().get<2>(); }
bool rcCameraProperty::operator< (const rcCameraProperty & o) const inline
Definition at line 186 of file rc_dcam.h.
References type().
     {
         return type() < o.type();
     }
const UInt32& rcCameraProperty::type (void) const inline
Definition at line 172 of file rc_dcam.h.
Referenced by operator<(), operator<<(), rfGetCameraCapabilities(), and setProperty().
 { return get<0>().get<0>(); }
UInt32& rcCameraProperty::type (void) inline
Definition at line 195 of file rc_dcam.h.
 { return get<0>().get<0>(); }
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const rcCameraProperty & c) friend
The documentation for this class was generated from the following file:
include/visual/rc_dcam.h