Visible: rcTrackElement Class Reference
rcTrackElement Class Reference
#include <include/visiCore/rc_nativeimporter.h>
Public Member Functions
rcTrackElement ()
rcTrackElement (rcWriter *track, const rcRect &rect)
rcTrackElement (rcWriter *track, const rcRect &rect, uint32 version)
bool isValid () const
rcWriter * track () const
const rcRect & rect () const
const uint32 version () const
Private Attributes
rcWriter * mTrack
rcRect mAnalysisRect
uint32 mVersion
Detailed Description
Definition at line 25 of file rc_nativeimporter.h.
Constructor & Destructor Documentation
rcTrackElement::rcTrackElement () inline
Definition at line 27 of file rc_nativeimporter.h.
                      :
         mTrack( 0 ),
         mAnalysisRect(),
         mVersion( 0 ) { };
rcTrackElement::rcTrackElement (rcWriter * track, const rcRect & rect) inline
Definition at line 31 of file rc_nativeimporter.h.
                                                           :
           mTrack( track ),
           mAnalysisRect( rect ),
           mVersion( 0 ) { };
rcTrackElement::rcTrackElement (rcWriter * track, const rcRect & rect, uint32 version) inline
Definition at line 36 of file rc_nativeimporter.h.
                                                                                 :
           mTrack( track ),
           mAnalysisRect( rect ),
           mVersion( version ) { };
Member Function Documentation
bool rcTrackElement::isValid () const inline
Definition at line 41 of file rc_nativeimporter.h.
References mTrack.
Referenced by rcIdMapper::flushWriters(), and rcNativeImporter::parseValue().
 { return mTrack != 0; };
const rcRect& rcTrackElement::rect () const inline
Definition at line 43 of file rc_nativeimporter.h.
References mAnalysisRect.
Referenced by rcIdMapper::addTrack(), and rcNativeImporter::parseValue().
 { return mAnalysisRect; };
rcWriter* rcTrackElement::track () const inline
Definition at line 42 of file rc_nativeimporter.h.
References mTrack.
Referenced by rcIdMapper::addTrack(), rcIdMapper::flushWriters(), and rcNativeImporter::parseValue().
 { return mTrack; };
const uint32 rcTrackElement::version (void) const inline
Definition at line 44 of file rc_nativeimporter.h.
References mVersion.
Referenced by rcNativeImporter::parseValue().
 { return mVersion; };
Member Data Documentation
rcRect rcTrackElement::mAnalysisRect private
Definition at line 48 of file rc_nativeimporter.h.
Referenced by rect().
rcWriter* rcTrackElement::mTrack private
Definition at line 44 of file rc_nativeimporter.h.
Referenced by isValid(), and track().
uint32 rcTrackElement::mVersion private
Definition at line 49 of file rc_nativeimporter.h.
Referenced by version().
The documentation for this class was generated from the following file:
include/visiCore/rc_nativeimporter.h