Visible: library_manager Class Reference
library_manager Class Reference
#include <include/stlplus/library_manager.hpp>
Public Types
typedef std::list< lm_library > library_list
Public Member Functions
bool is_library (const std::string &path)
std::string library_name (const std::string &path)
library_manager (const std::string &owner, bool library_case=false, bool unit_case=false)
~library_manager (void)
bool library_case (void) const
void set_library_case (bool library_case)
bool unit_case (void) const
void set_unit_case (bool library_case)
bool add_type (const std::string &type, const std::string &description, lm_create_callback fn=0, void *type_data=0)
bool remove_type (const std::string &type)
std::vector< std::string > types (void) const
std::string description (const std::string &type) const
lm_create_callback callback (const std::string &type) const
void * type_data (const std::string &type) const
void set_mapping_file (const std::string &mapping_file)
bool load_mappings (const std::string &mapping_file)
std::string mapping_file ()
bool set_ini_manager (ini_manager *ini_files, const std::string &library_section, const std::string &work_section)
ini_manager * get_ini_manager (void) const
bool save_mappings (void)
bool exists (const std::string &name) const
lm_library * create (const std::string &name, const std::string &path, bool writable=true)
lm_library * open (const std::string &path)
bool load (const std::string &name)
bool save (const std::string &name)
bool purge (const std::string &name)
bool close (const std::string &name)
bool erase (const std::string &name)
bool load (void)
bool save (void)
bool purge (void)
bool close (void)
bool erase (void)
std::string name (const std::string &library) const
std::string path (const std::string &library) const
bool set_writable (const std::string &library)
bool set_read_only (const std::string &library)
bool writable (const std::string &library) const
bool read_only (const std::string &library) const
bool os_writable (const std::string &library) const
bool os_read_only (const std::string &library) const
bool lm_writable (const std::string &library) const
bool lm_read_only (const std::string &library) const
lm_library * find (const std::string &name)
const lm_library * find (const std::string &name) const
std::vector< std::string > names (void) const
std::vector< const lm_library * > handles (void) const
std::vector< lm_library * > handles (void)
bool setwork (const std::string &library)
bool unsetwork (void)
const lm_library * work (void) const
lm_library * work (void)
std::string work_name (void) const
bool exists (const std::string &library, const lm_unit_name &name) const
lm_unit_ptr create (const std::string &library, const lm_unit_name &name)
bool loaded (const std::string &library, const lm_unit_name &name) const
bool load (const std::string &library, const lm_unit_name &name)
bool purge (const std::string &library, const lm_unit_name &name)
bool save (const std::string &library, const lm_unit_name &name)
bool erase (const std::string &library, const lm_unit_name &name)
bool mark (const std::string &library, const lm_unit_name &name)
time_t modified (const std::string &library, const lm_unit_name &name) const
bool erase_by_source (const std::string &source_file)
const lm_unit_ptr find (const std::string &library, const lm_unit_name &name) const
lm_unit_ptr find (const std::string &library, const lm_unit_name &name)
std::vector< lm_unit_name > names (const std::string &library) const
std::vector< std::string > names (const std::string &library, const std::string &type) const
std::vector< lm_unit_ptr > handles (const std::string &library) const
std::vector< lm_unit_ptr > handles (const std::string &library, const std::string &type) const
bool out_of_date (const std::string &library, const lm_unit_name &name) const
bool up_to_date (const std::string &library, const lm_unit_name &name) const
lm_dependencies out_of_date_reason (const std::string &library, const lm_unit_name &name) const
lm_tidy_result tidy (const std::string &library)
lm_tidy_result tidy (void)
bool pretty_print (otext &str, unsigned indent=0, bool print_units=false, const std::string &library=std::string(), const std::string &type=std::string()) const
otext & print (otext &str, unsigned indent=0) const
otext & print_long (otext &str, unsigned indent=0) const
Static Public Member Functions
static bool is_library (const std::string &path, const std::string &owner)
static std::string library_name (const std::string &path, const std::string &owner)
Protected Member Functions
library_list::iterator local_find (const std::string &name)
library_list::const_iterator local_find (const std::string &name) const
Protected Attributes
std::string m_owner
std::string m_mapping_file
ini_manager * m_ini_files
std::string m_ini_section
std::string m_ini_work
library_list m_libraries
std::string m_work
lm_callback_map m_callbacks
bool m_library_case
bool m_unit_case
Private Member Functions
library_manager (const library_manager &)
library_manager & operator= (const library_manager &)
Friends
class lm_library
class lm_unit
otext & print (otext &str, const library_manager &manager, unsigned indent=0)
otext & print_long (otext &str, const library_manager &manager, unsigned indent=0)
otext & operator<< (otext &str, const library_manager &libraries)
Detailed Description
Definition at line 527 of file library_manager.hpp.
Member Typedef Documentation
typedef std::list<lm_library> library_manager::library_list
Definition at line 532 of file library_manager.hpp.
Constructor & Destructor Documentation
library_manager::library_manager (const std::string & owner, bool library_case = false, bool unit_case = false) explicit
Definition at line 1559 of file library_manager.cpp.
                                                                                           :
   m_owner(owner), m_ini_files(0), m_library_case(library_case), m_unit_case(unit_case)
 {
 }
library_manager::~library_manager (void)
Definition at line 1564 of file library_manager.cpp.
References close().
 {
   close();
 }
library_manager::library_manager (const library_manager & r) private
Definition at line 1569 of file library_manager.cpp.
 {
   *this = r;
 }
Member Function Documentation
bool library_manager::add_type (const std::string & type, const std::string & description, lm_create_callback fn = 0, void * type_data = 0)
Definition at line 1606 of file library_manager.cpp.
References DEBUG_ASSERT, m_callbacks, and m_libraries.
 {
   bool result = true;
   m_callbacks[type] = lm_callback_entry(fn, description, type_data);
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result &= i->load_type(type);
   }
   return result;
 }
lm_create_callback library_manager::callback (const std::string & type) const
Definition at line 1645 of file library_manager.cpp.
References m_callbacks.
 {
   lm_callback_map::const_iterator found = m_callbacks.find(type);
   if (found == m_callbacks.end()) return 0;
   return found->second.m_callback;
 }
bool library_manager::close (const std::string & name)
Definition at line 1951 of file library_manager.cpp.
References local_find(), m_libraries, and m_work.
 {
   bool result= true;
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   result &= found->close();
   m_libraries.erase(found);
   if (name == m_work) m_work = "";
   return result;
 }
bool library_manager::close (void)
Definition at line 2008 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
Referenced by open(), and ~library_manager().
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); )
   {
     DEBUG_ASSERT(i->m_manager == this);
     library_list::iterator next = i;
     next++;
     result &= i->close();
     m_libraries.erase(i);
     i = next;
   }
   return result;
 }
lm_library * library_manager::create (const std::string & name, const std::string & path, bool writable = true)
Definition at line 1906 of file library_manager.cpp.
References create_library(), m_owner, and open().
 {
   if (!create_library(path, m_owner, name, writable)) return 0;
   return open(path);
 }
lm_unit_ptr library_manager::create (const std::string & library, const lm_unit_name & name)
Definition at line 2210 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return lm_unit_ptr();
   return found->create(unit);
 }
std::string library_manager::description (const std::string & type) const
Definition at line 1638 of file library_manager.cpp.
References m_callbacks.
Referenced by lm_unit::print_long().
 {
   lm_callback_map::const_iterator found = m_callbacks.find(type);
   if (found == m_callbacks.end()) return std::string();
   return found->second.m_description;
 }
bool library_manager::erase (const std::string & name)
Definition at line 1962 of file library_manager.cpp.
References local_find(), m_libraries, and m_work.
 {
   bool result= true;
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   result &= found->erase();
   m_libraries.erase(found);
   if (name == m_work) m_work = "";
   return result;
 }
bool library_manager::erase (void)
Definition at line 2023 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); )
   {
     DEBUG_ASSERT(i->m_manager == this);
     library_list::iterator next = i;
     next++;
     result &= i->erase();
     m_libraries.erase(i);
     i = next;
   }
   return result;
 }
bool library_manager::erase (const std::string & library, const lm_unit_name & name)
Definition at line 2245 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->erase(unit);
 }
bool library_manager::erase_by_source (const std::string & source_file)
Definition at line 2266 of file library_manager.cpp.
References m_libraries.
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
     if (i->writable())
       result &= i->erase_by_source(source_file);
   return result;
 }
bool library_manager::exists (const std::string & name) const
Definition at line 1901 of file library_manager.cpp.
References find().
Referenced by save_mappings().
 {
   return find(name) != 0;
 }
bool library_manager::exists (const std::string & library, const lm_unit_name & name) const
Definition at line 2203 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->exists(unit);
 }
lm_library * library_manager::find (const std::string & name)
Definition at line 2114 of file library_manager.cpp.
References local_find(), and m_libraries.
Referenced by exists(), out_of_date_chk(), and work().
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return 0;
   return &(*found);
 }
const lm_library * library_manager::find (const std::string & name) const
Definition at line 2121 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return 0;
   return &(*found);
 }
const lm_unit_ptr library_manager::find (const std::string & library, const lm_unit_name & name) const
Definition at line 2275 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end())
     return lm_unit_ptr();
   return found->find(unit);
 }
lm_unit_ptr library_manager::find (const std::string & library, const lm_unit_name & name)
Definition at line 2283 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return lm_unit_ptr();
   return found->find(unit);
 }
ini_manager * library_manager::get_ini_manager (void) const
Definition at line 1774 of file library_manager.cpp.
References m_ini_files.
 {
   return m_ini_files;
 }
std::vector< const lm_library * > library_manager::handles (void) const
Definition at line 2143 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
 {
   std::vector<const lm_library*> result;
   for (library_list::const_iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result.push_back(&(*i));
   }
   return result;
 }
std::vector< lm_library * > library_manager::handles (void)
Definition at line 2154 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
 {
   std::vector<lm_library*> result;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result.push_back(&(*i));
   }
   return result;
 }
std::vector< lm_unit_ptr > library_manager::handles (const std::string & library) const
Definition at line 2304 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return std::vector<lm_unit_ptr>();
   return found->handles();
 }
std::vector< lm_unit_ptr > library_manager::handles (const std::string & library, const std::string & type) const
Definition at line 2311 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return std::vector<lm_unit_ptr>();
   return found->handles(type);
 }
bool library_manager::is_library (const std::string & path, const std::string & owner) static
Definition at line 1531 of file library_manager.cpp.
References create_filespec(), file_exists(), and LibraryNameExtension.
Referenced by is_library(), load_mappings(), and set_ini_manager().
 {
   std::string spec = create_filespec(path, owner, LibraryNameExtension);
   return file_exists(spec);
 }
bool library_manager::is_library (const std::string & path)
Definition at line 1546 of file library_manager.cpp.
References is_library(), and m_owner.
 {
   return is_library(path, m_owner);
 }
bool library_manager::library_case (void) const
Definition at line 1583 of file library_manager.cpp.
References m_library_case.
Referenced by set_library_case().
 {
   return m_library_case;
 }
std::string library_manager::library_name (const std::string & path, const std::string & owner) static
Definition at line 1537 of file library_manager.cpp.
References name(), read_context(), and writable().
Referenced by library_name(), and set_ini_manager().
 {
   std::string name;
   bool writable = false;
   if (!read_context(path, owner, name, writable))
     return std::string();
   return name;
 }
std::string library_manager::library_name (const std::string & path)
Definition at line 1551 of file library_manager.cpp.
References library_name(), and m_owner.
 {
   return library_name(path, m_owner);
 }
bool library_manager::lm_read_only (const std::string & library) const
Definition at line 2105 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(library);
   if (found == m_libraries.end()) return false;
   return found->lm_read_only();
 }
bool library_manager::lm_writable (const std::string & library) const
Definition at line 2098 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(library);
   if (found == m_libraries.end()) return false;
   return found->lm_writable();
 }
bool library_manager::load (const std::string & name)
Definition at line 1930 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->load();
 }
bool library_manager::load (void)
Definition at line 1975 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result &= i->load();
   }
   return result;
 }
bool library_manager::load (const std::string & library, const lm_unit_name & name)
Definition at line 2224 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return lm_unit_ptr();
   return found->load(unit);
 }
bool library_manager::load_mappings (const std::string & mapping_file)
Definition at line 1667 of file library_manager.cpp.
References DEBUG_ASSERT, itext::error(), file_exists(), folder_part(), folder_to_path(), full_path(), itext::getline(), is_library(), itext::line(), lm_library::m_manager, m_mapping_file, mapping_file(), lm_library::name(), open(), path(), and setwork().
 {
   m_mapping_file = mapping_file;
   if (!file_exists(mapping_file))
   {
     return false;
   }
   iftext input(mapping_file);
   if (input.error())
   {
     return false;
   }
   // each line of the map file is a path to a library
   // the first line is the work library - may be empty
   // mappings are saved as paths relative to the mapping file and converted to full paths on load
   bool result = true;
   unsigned line = 1;
   for (std::string path = ""; input.getline(path); line++)
   {
     if (path.empty()) continue;
     std::string full_path = folder_to_path(folder_part(m_mapping_file), path);
     if (!library_manager::is_library(full_path))
     {
       result = false;
     }
     else
     {
       lm_library* lib = open(full_path);
       if (!lib)
       {
         result = false;
       }
       else
       {
         DEBUG_ASSERT(lib->m_manager == this);
         if (line == 1)
           setwork(lib->name());
       }
     }
   }
   return result;
 }
bool library_manager::loaded (const std::string & library, const lm_unit_name & name) const
Definition at line 2217 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return lm_unit_ptr();
   return found->loaded(unit);
 }
library_manager::library_list::iterator library_manager::local_find (const std::string & name) protected
Definition at line 1496 of file library_manager.cpp.
References lowercase(), m_libraries, m_library_case, and name().
Referenced by close(), create(), erase(), exists(), find(), handles(), lm_read_only(), lm_writable(), load(), loaded(), mark(), modified(), name(), names(), os_read_only(), os_writable(), path(), purge(), read_only(), save(), set_read_only(), set_writable(), setwork(), tidy(), and writable().
 {
   for (library_manager::library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     if (m_library_case)
     {
       if (i->name() == name) return i;
     }
     else
     {
       if (lowercase(i->name()) == lowercase(name)) return i;
     }
   }
   return m_libraries.end();
 }
library_manager::library_list::const_iterator library_manager::local_find (const std::string & name) const protected
Definition at line 1512 of file library_manager.cpp.
References lowercase(), m_libraries, m_library_case, and name().
 {
   for (library_manager::library_list::const_iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     if (m_library_case)
     {
       if (i->name() == name) return i;
     }
     else
     {
       if (lowercase(i->name()) == lowercase(name)) return i;
     }
   }
   return m_libraries.end();
 }
std::string library_manager::mapping_file ()
Definition at line 1710 of file library_manager.cpp.
References m_mapping_file.
Referenced by load_mappings(), and set_mapping_file().
 {
   return m_mapping_file;
 }
bool library_manager::mark (const std::string & library, const lm_unit_name & name)
Definition at line 2252 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->mark(unit);
 }
time_t library_manager::modified (const std::string & library, const lm_unit_name & name) const
Definition at line 2259 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return 0;
   return found->modified(unit);
 }
std::string library_manager::name (const std::string & library) const
Definition at line 2040 of file library_manager.cpp.
References local_find(), and m_libraries.
Referenced by library_name(), local_find(), and open().
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return std::string();
   return found->name();
 }
std::vector< std::string > library_manager::names (void) const
Definition at line 2130 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
Referenced by save_mappings().
 {
   std::vector<std::string> result;
   for (library_list::const_iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result.push_back(i->name());
   }
   return result;
 }
std::vector< lm_unit_name > library_manager::names (const std::string & library) const
Definition at line 2290 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return std::vector<lm_unit_name>();
   return found->names();
 }
std::vector< std::string > library_manager::names (const std::string & library, const std::string & type) const
Definition at line 2297 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return std::vector<std::string>();
   return found->names(type);
 }
lm_library * library_manager::open (const std::string & path)
Definition at line 1912 of file library_manager.cpp.
References close(), folder_to_path(), lm_library, m_libraries, m_owner, name(), read_context(), and writable().
Referenced by create(), load_mappings(), and set_ini_manager().
 {
   std::string name;
   bool writable = false;
   if (!read_context(path, m_owner, name, writable)) return 0;
   // remove any pre-existing library with the same name
   close(name);
   // add the library to the manager and open it
   m_libraries.push_back(lm_library(this));
   if (!m_libraries.back().open(folder_to_path(path)))
   {
     // remove the library in the event of an error
     m_libraries.erase(--m_libraries.end());
     return 0;
   }
   return &m_libraries.back();
 }
library_manager & library_manager::operator= (const library_manager & r) private
Definition at line 1574 of file library_manager.cpp.
References DEBUG_ASSERT.
 {
   DEBUG_ASSERT(false);
   return *this;
 }
bool library_manager::os_read_only (const std::string & library) const
Definition at line 2091 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(library);
   if (found == m_libraries.end()) return false;
   return found->os_read_only();
 }
bool library_manager::os_writable (const std::string & library) const
Definition at line 2084 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(library);
   if (found == m_libraries.end()) return false;
   return found->os_writable();
 }
bool library_manager::out_of_date (const std::string & library, const lm_unit_name & name) const
Definition at line 2322 of file library_manager.cpp.
References up_to_date().
Referenced by lm_library::out_of_date().
 {
   return !up_to_date(library, name);
 }
lm_dependencies library_manager::out_of_date_reason (const std::string & library, const lm_unit_name & name) const
Definition at line 2333 of file library_manager.cpp.
References out_of_date_chk().
Referenced by lm_library::out_of_date_reason(), and up_to_date().
 {
   std::map<std::pair<std::string,lm_unit_name>,lm_dependencies> visited;
   return out_of_date_chk(visited, this, library, name);
 }
std::string library_manager::path (const std::string & library) const
Definition at line 2047 of file library_manager.cpp.
References local_find(), and m_libraries.
Referenced by load_mappings(), and save_mappings().
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return std::string();
   return found->path();
 }
bool library_manager::pretty_print (otext & str, unsigned indent = 0, bool print_units = false, const std::string & library = std::string(), const std::string & type = std::string()) const
Definition at line 2364 of file library_manager.cpp.
References endl(), and m_libraries.
 {
   bool library_found = false;
   for (library_list::const_iterator l = m_libraries.begin(); l != m_libraries.end(); l++)
   {
     // select the library
     if (lib.empty() || lib == l->name())
     {
       l->pretty_print(str, indent, print_units, type);
       library_found = true;
     }
   }
   if (!library_found)
   {
     if (lib.empty())
       str << "there are no libraries in the library list" << endl;
     else
       str << "there is no library called " << lib << " in the library list" << endl;
     return false;
   }
   return true;
 }
otext & library_manager::print (otext & str, unsigned indent = 0) const
Definition at line 2394 of file library_manager.cpp.
References m_libraries.
Referenced by operator<<(), and print().
 {
   for (library_list::const_iterator l = m_libraries.begin(); l != m_libraries.end(); l++)
     l->print(str, indent);
   return str;
 }
otext & library_manager::print_long (otext & str, unsigned indent = 0) const
Definition at line 2401 of file library_manager.cpp.
References m_libraries.
Referenced by print_long().
 {
   for (library_list::const_iterator l = m_libraries.begin(); l != m_libraries.end(); l++)
     l->print_long(str, indent);
   return str;
 }
bool library_manager::purge (const std::string & name)
Definition at line 1944 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->purge();
 }
bool library_manager::purge (void)
Definition at line 1997 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result &= i->purge();
   }
   return result;
 }
bool library_manager::purge (const std::string & library, const lm_unit_name & name)
Definition at line 2231 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->purge(unit);
 }
bool library_manager::read_only (const std::string & library) const
Definition at line 2077 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->read_only();
 }
bool library_manager::remove_type (const std::string & type)
Definition at line 1618 of file library_manager.cpp.
References DEBUG_ASSERT, m_callbacks, and m_libraries.
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result &= i->remove_type(type);
   }
   m_callbacks.erase(type);
   return result;
 }
bool library_manager::save (const std::string & name)
Definition at line 1937 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->save();
 }
bool library_manager::save (void)
Definition at line 1986 of file library_manager.cpp.
References DEBUG_ASSERT, and m_libraries.
 {
   bool result = true;
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     DEBUG_ASSERT(i->m_manager == this);
     result &= i->save();
   }
   return result;
 }
bool library_manager::save (const std::string & library, const lm_unit_name & name)
Definition at line 2238 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->save(unit);
 }
bool library_manager::save_mappings (void)
Definition at line 1779 of file library_manager.cpp.
References ini_manager::add_blank(), ini_manager::add_comment(), ini_manager::add_variable(), ini_manager::clear_section(), ini_manager::empty_section(), endl(), ini_manager::erase_section(), otext::error(), exists(), file_delete(), folder_part(), folder_to_path(), folder_to_relative_path(), m_ini_files, m_ini_section, m_ini_work, m_libraries, m_mapping_file, names(), output(), path(), relative_path(), ini_manager::save(), ini_manager::variable_exists(), ini_manager::variable_filename(), ini_manager::variable_names(), ini_manager::variable_value(), and work_name().
 {
   bool result = true;
   // save to mapping file or ini manager or both
   if (!m_mapping_file.empty())
   {
     if (m_libraries.size() == 0)
     {
       // if the file would be empty, delete it
       if (!file_delete(m_mapping_file))
       {
         result = false;
       }
     }
     else
     {
       oftext output(m_mapping_file);
       if (output.error())
       {
         result = false;
       }
       else
       {
         // each line of the map file is a path to a library
         // the first line is the work library
         // mappings are saved as relative paths to the mapping file and converted to full paths on load
         if (work_name().empty())
         {
           output << endl;
         }
         else
         {
           std::string work_path = folder_to_relative_path(folder_part(m_mapping_file), path(work_name()));
           output << work_path << endl;
         }
         std::vector<std::string> libraries = names();
         for (unsigned i = 0; i < libraries.size(); ++i)
         {
           if (libraries[i] != work_name())
           {
             std::string lib_path = folder_to_relative_path(folder_part(m_mapping_file), path(libraries[i]));
             output << lib_path << endl;
           }
         }
         if (output.error())
         {
           result = false;
         }
       }
     }
   }
   if (m_ini_files)
   {
     // this is somewhat tricky!
     // first remove all local mappings
     // then need to compare the surviving library mappings with the contents of the library manager
     // if there's a library in the ini files not in the library manager, mask it with an empty local declaration
     // if there's a library in the ini files with the same mapping as the library manager, do nothing
     // if there's a library in the ini files with a different mapping write that library mapping
     // if there's a mapping missing from the ini files, write it
     // finally write the work mapping if there is one
     // clear all local mappings
     // TODO - rework this so that the ini files only change if the mappings change
     m_ini_files->clear_section(m_ini_section);
     m_ini_files->add_comment(m_ini_section, "generated automatically by the library manager");
     // look for globally defined library mappings that need to be overridden in the local ini file
     std::vector<std::string> ini_names = m_ini_files->variable_names(m_ini_section);
     for (unsigned i = 0; i < ini_names.size(); i++)
     {
       std::string ini_name = ini_names[i];
       // chk for a global library that needs to be locally masked
       if (!exists(ini_name))
         m_ini_files->add_variable(m_ini_section, ini_name, "");
       else
       {
         // chk for a library that is locally remapped
         std::string value = m_ini_files->variable_value(m_ini_section, ini_name);
         std::string filename = m_ini_files->variable_filename(m_ini_section, ini_name);
         std::string full_ini_path = folder_to_path(folder_part(filename), value);
         std::string full_lib_path = folder_to_path(path(ini_name));
         if (full_ini_path != full_lib_path)
         {
           // write the path relative to the ini file
           std::string relative_path = folder_to_relative_path(folder_part(filename), full_lib_path);
           m_ini_files->add_variable(m_ini_section, ini_name, relative_path);
         }
       }
     }
     // now scan the library for mappings that aren't yet in the ini file
     std::vector<std::string> lib_names = names();
     for (unsigned j = 0; j < lib_names.size(); j++)
     {
       std::string lib_name = lib_names[j];
       if (std::find(ini_names.begin(), ini_names.end(), lib_name) == ini_names.end())
       {
         // write the path relative to the ini file
         std::string full_lib_path = folder_to_path(path(lib_name));
         std::string filename = m_ini_files->variable_filename(m_ini_section, lib_name);
         std::string relative_path = folder_to_relative_path(folder_part(filename), full_lib_path);
         m_ini_files->add_variable(m_ini_section, lib_name, relative_path);
       }
     }
     // write the work library - also write a blank value if work is not set but is defined in another library
     if (!work_name().empty())
       m_ini_files->add_variable(m_ini_section, m_ini_work, work_name());
     else if (m_ini_files->variable_exists(m_ini_section, m_ini_work))
       m_ini_files->add_variable(m_ini_section, m_ini_work, "");
     m_ini_files->add_blank(m_ini_section);
     // remove the section from the ini file manager if there's nothing in it
     if (m_ini_files->empty_section(m_ini_section))
       m_ini_files->erase_section(m_ini_section);
     if (!m_ini_files->save())
     {
       result = false;
     }
   }
   return result;
 }
bool library_manager::set_ini_manager (ini_manager * ini_files, const std::string & library_section, const std::string & work_section)
Definition at line 1715 of file library_manager.cpp.
References DEBUG_ASSERT, folder_part(), folder_to_path(), full_path(), is_library(), library_name(), m_ini_files, m_ini_section, m_ini_work, open(), ini_manager::section_exists(), setwork(), unsetwork(), ini_manager::variable_filename(), ini_manager::variable_names(), ini_manager::variable_value(), and work_name().
 {
   DEBUG_ASSERT(ini_files);
   bool result = true;
   m_ini_files = ini_files;
   m_ini_section = library_section;
   m_ini_work = work_name;
   // now load the existing library mappings if present - in any case create the sections
   // Note: a library mapping is saved as a path relative to the ini file - on load convert it to a path relative to the current directory
   if (m_ini_files->section_exists(m_ini_section))
   {
     std::vector<std::string> library_names = m_ini_files->variable_names(m_ini_section);
     std::string work_name;
     for (unsigned i = 0; i < library_names.size(); i++)
     {
       std::string library_name = library_names[i];
       // if the variable name is the work name, then this is a mapping to an existing library name
       // if it is null, then it is masking a global library definition so ignore it
       // otherwise it is a mapping to a directory containing the library
       if (library_name.empty())
       {
       }
       else if (library_name == m_ini_work)
       {
         work_name = m_ini_files->variable_value(m_ini_section, library_name);
       }
       else
       {
         std::string value = m_ini_files->variable_value(m_ini_section, library_name);
         std::string filename = m_ini_files->variable_filename(m_ini_section, library_name);
         // get the path to the ini file defining this library, strip off the ini filename to get the folder
         // then combine this with the library path from that ini file to the library to get a full path to the library
         // whew!
         std::string full_path = folder_to_path(folder_part(filename),value);
         if (!library_manager::is_library(full_path))
         {
           result = false;
         }
         else
         {
           lm_library* lib = open(full_path);
           if (!lib)
           {
             result = false;
           }
         }
       }
     }
     // work must be set after all the libraries have benn opened because it is
     // illegal to set work to a library that doesn't already exist in the
     // library manager
     if (work_name.empty())
       unsetwork();
     else
       result &= setwork(work_name);
   }
   return result;
 }
void library_manager::set_library_case (bool library_case)
Definition at line 1588 of file library_manager.cpp.
References library_case(), and m_library_case.
 {
   m_library_case = library_case;
 }
void library_manager::set_mapping_file (const std::string & mapping_file)
Definition at line 1662 of file library_manager.cpp.
References m_mapping_file, and mapping_file().
 {
   m_mapping_file = mapping_file;
 }
bool library_manager::set_read_only (const std::string & library)
Definition at line 2063 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->set_read_only();
 }
void library_manager::set_unit_case (bool library_case)
Definition at line 1598 of file library_manager.cpp.
References m_unit_case, and unit_case().
 {
   m_unit_case = unit_case;
 }
bool library_manager::set_writable (const std::string & library)
Definition at line 2056 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->set_writable();
 }
bool library_manager::setwork (const std::string & library)
Definition at line 2168 of file library_manager.cpp.
References local_find(), m_libraries, m_work, and unsetwork().
Referenced by load_mappings(), and set_ini_manager().
 {
   unsetwork();
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   m_work = found->name();
   return true;
 }
lm_tidy_result library_manager::tidy (const std::string & library)
Definition at line 2339 of file library_manager.cpp.
References local_find(), and m_libraries.
 {
   library_list::iterator found = local_find(library);
   if (found == m_libraries.end()) return std::make_pair(false,0);
   return found->tidy();
 }
lm_tidy_result library_manager::tidy (void)
Definition at line 2346 of file library_manager.cpp.
References m_libraries.
 {
   lm_tidy_result result = std::make_pair(true,0);
   for (library_list::iterator i = m_libraries.begin(); i != m_libraries.end(); i++)
   {
     if (i->writable())
     {
       lm_tidy_result library_result = i->tidy();
       result.second += library_result.second;
       result.first &= library_result.first;
     }
   }
   return result;
 }
void * library_manager::type_data (const std::string & type) const
Definition at line 1652 of file library_manager.cpp.
References m_callbacks.
 {
   lm_callback_map::const_iterator found = m_callbacks.find(type);
   if (found == m_callbacks.end()) return 0;
   return found->second.m_type_data;
 }
std::vector< std::string > library_manager::types (void) const
Definition at line 1630 of file library_manager.cpp.
References m_callbacks.
 {
   std::vector<std::string> result;
   for (lm_callback_map::const_iterator i = m_callbacks.begin(); i != m_callbacks.end(); i++)
     result.push_back(i->first);
   return result;
 }
bool library_manager::unit_case (void) const
Definition at line 1593 of file library_manager.cpp.
References m_unit_case.
Referenced by set_unit_case().
 {
   return m_unit_case;
 }
bool library_manager::unsetwork (void)
Definition at line 2177 of file library_manager.cpp.
References m_work.
Referenced by set_ini_manager(), and setwork().
 {
   m_work = "";
   return true;
 }
bool library_manager::up_to_date (const std::string & library, const lm_unit_name & name) const
Definition at line 2327 of file library_manager.cpp.
References lm_dependencies::empty(), and out_of_date_reason().
Referenced by out_of_date(), and lm_library::up_to_date().
 {
   lm_dependencies reason = out_of_date_reason(library, name);
   return reason.empty();
 }
const lm_library * library_manager::work (void) const
Definition at line 2183 of file library_manager.cpp.
References find(), and m_work.
Referenced by lm_library::pretty_print().
 {
   if (m_work.empty()) return 0;
   return find(m_work);
 }
lm_library * library_manager::work (void)
Definition at line 2189 of file library_manager.cpp.
References find(), and m_work.
 {
   if (m_work.empty()) return 0;
   return find(m_work);
 }
std::string library_manager::work_name (void) const
Definition at line 2195 of file library_manager.cpp.
References m_work.
Referenced by save_mappings(), and set_ini_manager().
 {
   return m_work;
 }
bool library_manager::writable (const std::string & library) const
Definition at line 2070 of file library_manager.cpp.
References local_find(), and m_libraries.
Referenced by library_name(), and open().
 {
   library_list::const_iterator found = local_find(name);
   if (found == m_libraries.end()) return false;
   return found->writable();
 }
Friends And Related Function Documentation
friend class lm_library friend
Definition at line 530 of file library_manager.hpp.
Referenced by open().
friend class lm_unit friend
Definition at line 531 of file library_manager.hpp.
otext& operator<< (otext & str, const library_manager & libraries) friend
Definition at line 2418 of file library_manager.cpp.
 {
   return manager.print(str);
 }
otext& print (otext & str, const library_manager & manager, unsigned indent = 0) friend
Definition at line 2408 of file library_manager.cpp.
 {
   return manager.print(str, indent);
 }
otext& print_long (otext & str, const library_manager & manager, unsigned indent = 0) friend
Definition at line 2413 of file library_manager.cpp.
 {
   return manager.print_long(str, indent);
 }
Member Data Documentation
lm_callback_map library_manager::m_callbacks protected
Definition at line 731 of file library_manager.hpp.
Referenced by add_type(), callback(), lm_library::create(), description(), lm_unit::load(), lm_library::load_type(), lm_library::load_types(), lm_library::pretty_print(), remove_type(), lm_unit::save(), type_data(), and types().
ini_manager* library_manager::m_ini_files protected
Definition at line 726 of file library_manager.hpp.
Referenced by get_ini_manager(), save_mappings(), and set_ini_manager().
std::string library_manager::m_ini_section protected
Definition at line 727 of file library_manager.hpp.
Referenced by save_mappings(), and set_ini_manager().
std::string library_manager::m_ini_work protected
Definition at line 728 of file library_manager.hpp.
Referenced by save_mappings(), and set_ini_manager().
library_list library_manager::m_libraries protected
Definition at line 729 of file library_manager.hpp.
Referenced by add_type(), close(), create(), erase(), erase_by_source(), exists(), find(), handles(), lm_read_only(), lm_writable(), load(), loaded(), local_find(), mark(), modified(), name(), names(), open(), os_read_only(), os_writable(), path(), pretty_print(), print(), print_long(), purge(), read_only(), remove_type(), save(), save_mappings(), set_read_only(), set_writable(), setwork(), tidy(), and writable().
bool library_manager::m_library_case protected
Definition at line 732 of file library_manager.hpp.
Referenced by library_case(), local_find(), and set_library_case().
std::string library_manager::m_mapping_file protected
Definition at line 725 of file library_manager.hpp.
Referenced by load_mappings(), mapping_file(), save_mappings(), and set_mapping_file().
std::string library_manager::m_owner protected
Definition at line 724 of file library_manager.hpp.
Referenced by lm_library::create(), create(), lm_library::erase(), is_library(), library_name(), lm_library::open(), open(), and lm_library::set_read_write().
bool library_manager::m_unit_case protected
Definition at line 733 of file library_manager.hpp.
Referenced by lm_library::create(), lm_library::load_type(), lm_library::local_find(), set_unit_case(), and unit_case().
std::string library_manager::m_work protected
Definition at line 730 of file library_manager.hpp.
Referenced by close(), erase(), setwork(), unsetwork(), work(), and work_name().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp