Visible: ini_entry Class Reference
ini_entry Class Reference
Public Types
enum kind_t { BLANK, COMMENT, VARIABLE }
Public Member Functions
ini_entry (unsigned line)
ini_entry (unsigned line, const std::string &comment)
ini_entry (unsigned line, const std::string &name, const std::string &value)
~ini_entry (void)
unsigned line (void) const
kind_t kind (void) const
bool blank (void) const
bool comment (void) const
bool variable (void) const
const std::string & text (void) const
const std::string & variable_name (void) const
const std::string & variable_value (void) const
Private Attributes
unsigned m_line
kind_t m_kind
std::string m_text
std::string m_name
std::string m_value
Friends
std::string to_string (kind_t kind)
otext & print (otext &str, const ini_entry &entry, unsigned indent)
Detailed Description
Definition at line 22 of file ini_manager.cpp.
Member Enumeration Documentation
enum ini_entry::kind_t
Enumerator
BLANK
COMMENT
VARIABLE
Definition at line 25 of file ini_manager.cpp.
 {BLANK, COMMENT, VARIABLE};
Constructor & Destructor Documentation
ini_entry::ini_entry (unsigned line) inline
Definition at line 45 of file ini_manager.cpp.
 : m_line(line), m_kind(BLANK) {}
ini_entry::ini_entry (unsigned line, const std::string & comment) inline
Definition at line 46 of file ini_manager.cpp.
 : m_line(line), m_kind(COMMENT), m_text("; " + comment) {}
ini_entry::ini_entry (unsigned line, const std::string & name, const std::string & value) inline
Definition at line 47 of file ini_manager.cpp.
 : m_line(line), m_kind(VARIABLE), m_text(name + " = " + value), m_name(name), m_value(value) {}
ini_entry::~ini_entry (void) inline
Definition at line 48 of file ini_manager.cpp.
 {}
Member Function Documentation
bool ini_entry::blank (void) const inline
Definition at line 52 of file ini_manager.cpp.
References BLANK, and m_kind.
 {return m_kind == BLANK;}
bool ini_entry::comment (void) const inline
Definition at line 53 of file ini_manager.cpp.
References COMMENT, and m_kind.
 {return m_kind == COMMENT;}
kind_t ini_entry::kind (void) const inline
Definition at line 51 of file ini_manager.cpp.
References m_kind.
 {return m_kind;}
unsigned ini_entry::line (void) const inline
Definition at line 50 of file ini_manager.cpp.
References m_line.
 {return m_line;}
const std::string& ini_entry::text (void) const inline
Definition at line 56 of file ini_manager.cpp.
References m_text.
 {return m_text;}
bool ini_entry::variable (void) const inline
Definition at line 54 of file ini_manager.cpp.
References m_kind, and VARIABLE.
Referenced by variable_name(), and variable_value().
 {return m_kind == VARIABLE;}
const std::string& ini_entry::variable_name (void) const inline
Definition at line 57 of file ini_manager.cpp.
References DEBUG_ASSERT, m_name, and variable().
 {DEBUG_ASSERT(variable()); return m_name;}
const std::string& ini_entry::variable_value (void) const inline
Definition at line 58 of file ini_manager.cpp.
References DEBUG_ASSERT, m_value, and variable().
 {DEBUG_ASSERT(variable()); return m_value;}
Friends And Related Function Documentation
otext& print (otext & str, const ini_entry & entry, unsigned indent) friend
Definition at line 60 of file ini_manager.cpp.
     {
       print_indent(str, indent);
       str << to_string(entry.line()) << ":" << to_string(entry.kind()) << ": " << entry.text() << endl;
       return str;
     }
std::string to_string (kind_t kind) friend
Definition at line 26 of file ini_manager.cpp.
     {
       switch(kind)
       {
       case BLANK: return "BLANK";
       case COMMENT: return "COMMENT";
       case VARIABLE: return "VARIABLE";
       }
       return "<*unknown kind*>";
     }
Member Data Documentation
kind_t ini_entry::m_kind private
Definition at line 39 of file ini_manager.cpp.
Referenced by blank(), comment(), kind(), and variable().
unsigned ini_entry::m_line private
Definition at line 38 of file ini_manager.cpp.
Referenced by line().
std::string ini_entry::m_name private
Definition at line 41 of file ini_manager.cpp.
Referenced by variable_name().
std::string ini_entry::m_text private
Definition at line 40 of file ini_manager.cpp.
Referenced by text().
std::string ini_entry::m_value private
Definition at line 42 of file ini_manager.cpp.
Referenced by variable_value().
The documentation for this class was generated from the following file:
include/stlplus/ini_manager.cpp