Visible: lm_unit Class Reference
lm_unit Class Reference
#include <include/stlplus/library_manager.hpp>
Public Member Functions
lm_unit (const lm_unit_name &name, lm_library *library)
virtual ~lm_unit (void)
const lm_unit_name & unit_name (void) const
const std::string & name (void) const
const std::string & type (void) const
void set_source_file (const lm_file_dependency &)
bool source_file_present (void) const
const lm_file_dependency & source_file (void) const
unsigned file_add (const lm_file_dependency &dependency)
unsigned file_size (void) const
const lm_file_dependency & file_dependency (unsigned) const
void file_erase (unsigned)
unsigned unit_add (const lm_unit_dependency &dependency)
unsigned unit_size (void) const
const lm_unit_dependency & unit_dependency (unsigned) const
void unit_erase (unsigned)
const lm_dependencies & dependencies (void) const
void set_dependencies (const lm_dependencies &)
void clear_dependencies (void)
bool empty_dependencies (void) const
bool out_of_date (void) const
bool up_to_date (void) const
lm_dependencies out_of_date_reason (void) const
const std::string & supplementary_data (void) const
void set_supplementary_data (const std::string &data)
bool load (void)
bool save (void)
bool loaded (void) const
void mark (void)
time_t modified (void) const
const lm_library * library (void) const
lm_library * library (void)
const std::string & library_name (void) const
const std::string & library_path (void) const
bool error (void) const
int error_number (void) const
std::string error_string (void) const
virtual bool read (const std::string &filename, void *type_data)
virtual bool read (itext &file, void *type_data)
virtual bool write (const std::string &filename, void *type_data)
virtual bool write (otext &file, void *type_data)
virtual bool purge (void)
virtual lm_unit * clone (void) const
virtual otext & print (otext &) const
virtual otext & print_long (otext &, unsigned indent=0) const
Protected Member Functions
std::string filename (void) const
std::string header_filename (void) const
bool dump_header (void)
bool restore_header (void)
Private Attributes
lm_unit_name m_name
lm_dependencies m_dependencies
std::string m_supplement
bool m_header_modified
bool m_loaded
bool m_marked
lm_library * m_library
int m_error
std::string m_error_string
Friends
class lm_library
otext & print (otext &str, const lm_unit &u)
otext & print_long (otext &str, const lm_unit &u, unsigned indent)
otext & operator<< (otext &str, const lm_unit &u)
Detailed Description
Definition at line 215 of file library_manager.hpp.
Constructor & Destructor Documentation
lm_unit::lm_unit (const lm_unit_name & name, lm_library * library)
Definition at line 579 of file library_manager.cpp.
References restore_header().
Referenced by clone().
                                                               :
   m_name(name), m_header_modified(false), m_loaded(false), m_marked(false), m_library(library), m_error(0)
 {
   restore_header();
 }
lm_unit::~lm_unit (void) virtual
Definition at line 585 of file library_manager.cpp.
References dump_header().
 {
   dump_header();
 }
Member Function Documentation
void lm_unit::clear_dependencies (void)
Definition at line 688 of file library_manager.cpp.
References lm_dependencies::clear(), m_dependencies, and m_header_modified.
 {
   m_header_modified = true;
   m_dependencies.clear();
 }
lm_unit * lm_unit::clone (void) const virtual
Definition at line 876 of file library_manager.cpp.
References lm_unit().
 {
   return new lm_unit(*this);
 }
const lm_dependencies & lm_unit::dependencies (void) const
Definition at line 677 of file library_manager.cpp.
References m_dependencies.
Referenced by set_dependencies().
 {
   return m_dependencies;
 }
bool lm_unit::dump_header (void) protected
Definition at line 558 of file library_manager.cpp.
References dump(), header_filename(), m_dependencies, m_header_modified, m_supplement, and output().
Referenced by ~lm_unit().
 {
   if (!m_header_modified) return true;
 //   try
 //   {
     oftext output(header_filename());
     dump_context context(output);
     dump(context, m_dependencies);
     dump(context, m_supplement);
 //   }
 //   catch(persistent_dump_failed&)
 //   {
 //     return false;
 //   }
   m_header_modified = false;
   return true;
 }
bool lm_unit::empty_dependencies (void) const
Definition at line 694 of file library_manager.cpp.
References lm_dependencies::empty(), and m_dependencies.
 {
   return m_dependencies.empty();
 }
bool lm_unit::error (void) const
Definition at line 800 of file library_manager.cpp.
References error_number().
 {
   return error_number() != 0;
 }
int lm_unit::error_number (void) const
Definition at line 805 of file library_manager.cpp.
References m_error.
Referenced by error().
 {
   return m_error;
 }
std::string lm_unit::error_string (void) const
Definition at line 810 of file library_manager.cpp.
References m_error_string.
 {
   return m_error_string;
 }
unsigned lm_unit::file_add (const lm_file_dependency & dependency)
Definition at line 631 of file library_manager.cpp.
References lm_dependencies::file_add(), m_dependencies, and m_header_modified.
 {
   m_header_modified = true;
   return m_dependencies.file_add(dependency);
 }
const lm_file_dependency & lm_unit::file_dependency (unsigned i) const
Definition at line 642 of file library_manager.cpp.
References lm_dependencies::file_dependency(), and m_dependencies.
 {
   return m_dependencies.file_dependency(i);
 }
void lm_unit::file_erase (unsigned i)
Definition at line 647 of file library_manager.cpp.
References lm_dependencies::file_erase(), m_dependencies, and m_header_modified.
 {
   m_header_modified = true;
   m_dependencies.file_erase(i);
 }
unsigned lm_unit::file_size (void) const
Definition at line 637 of file library_manager.cpp.
References lm_dependencies::file_size(), and m_dependencies.
 {
   return m_dependencies.file_size();
 }
std::string lm_unit::filename (void) const protected
Definition at line 528 of file library_manager.cpp.
References create_filespec(), library_path(), m_name, lm_unit_name::name(), and lm_unit_name::type().
Referenced by load(), modified(), and save().
 {
   return create_filespec(library_path(), m_name.name(), m_name.type());
 }
std::string lm_unit::header_filename (void) const protected
Definition at line 533 of file library_manager.cpp.
References create_filespec(), HeaderExtension, library_path(), m_name, lm_unit_name::name(), and lm_unit_name::type().
Referenced by dump_header(), and restore_header().
 {
   return create_filespec(library_path(), m_name.name(), m_name.type() + std::string(HeaderExtension));
 }
const lm_library * lm_unit::library (void) const
Definition at line 776 of file library_manager.cpp.
References m_library.
Referenced by print_long().
 {
   return m_library;
 }
lm_library * lm_unit::library (void)
Definition at line 781 of file library_manager.cpp.
References m_library.
 {
   return m_library;
 }
const std::string & lm_unit::library_name (void) const
Definition at line 786 of file library_manager.cpp.
References DEBUG_ASSERT, m_library, and lm_library::name().
 {
   DEBUG_ASSERT(m_library);
   return m_library->name();
 }
const std::string & lm_unit::library_path (void) const
Definition at line 792 of file library_manager.cpp.
References DEBUG_ASSERT, m_library, and lm_library::path().
Referenced by filename(), and header_filename().
 {
   DEBUG_ASSERT(m_library);
   return m_library->path();
 }
bool lm_unit::load (void)
Definition at line 732 of file library_manager.cpp.
References filename(), library_manager::m_callbacks, m_library, m_loaded, lm_library::m_manager, out_of_date(), read(), and type().
 {
   if (out_of_date()) return false;
   if (m_loaded) return true;
   // get the user data for this type
   lm_callback_map::iterator callback = m_library->m_manager->m_callbacks.find(type());
   if (callback == m_library->m_manager->m_callbacks.end()) return false;
   void* data = callback->second.m_type_data;
   bool result = read(filename(), data);
   m_loaded = true;
   return result;
 }
bool lm_unit::loaded (void) const
Definition at line 758 of file library_manager.cpp.
References m_loaded.
 {
   return m_loaded;
 }
void lm_unit::mark (void)
Definition at line 763 of file library_manager.cpp.
References m_marked.
 {
   m_marked = true;
 }
time_t lm_unit::modified (void) const
Definition at line 768 of file library_manager.cpp.
References file_modified(), and filename().
 {
   return file_modified(filename());
 }
const std::string & lm_unit::name (void) const
Definition at line 598 of file library_manager.cpp.
References m_name, and lm_unit_name::name().
 {
   return m_name.name();
 }
bool lm_unit::out_of_date (void) const
Definition at line 701 of file library_manager.cpp.
References m_library, m_name, and lm_library::out_of_date().
Referenced by load().
 {
   return m_library->out_of_date(m_name);
 }
lm_dependencies lm_unit::out_of_date_reason (void) const
Definition at line 711 of file library_manager.cpp.
References m_library, m_name, and lm_library::out_of_date_reason().
 {
   return m_library->out_of_date_reason(m_name);
 }
otext & lm_unit::print (otext & str) const virtual
Definition at line 881 of file library_manager.cpp.
References m_loaded, m_marked, and m_name.
 {
   return str << m_name << " " << (m_loaded ? "loaded" : "") << " " << (m_marked ? "needs saving" : "");
 }
otext & lm_unit::print_long (otext & str, unsigned indent = 0) const virtual
Definition at line 886 of file library_manager.cpp.
References lm_file_dependency::column(), library_manager::description(), endl(), lm_dependencies::file_dependency(), lm_dependencies::file_size(), filespec_to_relative_path(), lm_unit_dependency::library(), library(), lm_file_dependency::line(), m_dependencies, m_name, m_supplement, lm_library::manager(), lm_unit_name::name(), lm_unit_dependency::name(), lm_file_dependency::path_full(), print_indent(), lm_dependencies::source_file(), lm_dependencies::source_file_present(), lm_unit_name::type(), lm_unit_dependency::type(), lm_dependencies::unit_dependency(), and lm_dependencies::unit_size().
 {
   print_indent(str, indent);
   str << "header:" << endl;
   print_indent(str, indent+1);
   str << "name: " << m_name.name() << endl;
   print_indent(str, indent+1);
   str << "type: " << library()->manager()->description(m_name.type()) << endl;
   print_indent(str, indent+1);
   str << "dependencies:" << endl;
   // Note: I've inlined this rather than call the above-defined print for dependencies
   // This is so that I can use the library manager to look up the descriptions of unit types
   // I can also convert paths so that they are relative to the current directory rather than the library
   // print the source file dependency if present
   if (m_dependencies.source_file_present())
   {
     print_indent(str, indent+2);
     str << "source file: ";
     str << filespec_to_relative_path(m_dependencies.source_file().path_full(library()->path()));
     if (m_dependencies.source_file().line() != 0)
       str << ":" << m_dependencies.source_file().line() << ":" << m_dependencies.source_file().column();
     str << endl;
   }
   // now print other file dependencies
   // convert these to relative paths too
   for (unsigned f = 0; f < m_dependencies.file_size(); f++)
   {
     print_indent(str, indent+2);
     str << "file: ";
     str << filespec_to_relative_path(m_dependencies.file_dependency(f).path_full(library()->path()));
     if (m_dependencies.file_dependency(f).line() != 0)
       str << ":" << m_dependencies.file_dependency(f).line() << ":" << m_dependencies.file_dependency(f).column();
     str << endl;
   }
   // now print unit dependencies
   // convert unit types to their descriptive strings
   for (unsigned u = 0; u < m_dependencies.unit_size(); u++)
   {
     print_indent(str, indent+2);
     str << library()->manager()->description(m_dependencies.unit_dependency(u).type()) << ": ";
     str << m_dependencies.unit_dependency(u).library() << "." << m_dependencies.unit_dependency(u).name();
     str << endl;
   }
   if (!m_supplement.empty())
   {
     print_indent(str, indent+1);
     str << "supplementary data: " << m_supplement << endl;
   }
   return str;
 }
bool lm_unit::purge (void) virtual
Definition at line 871 of file library_manager.cpp.
 {
   return true;
 }
bool lm_unit::read (const std::string & filename, void * type_data) virtual
Definition at line 834 of file library_manager.cpp.
References itext::error(), itext::error_number(), itext::error_string(), m_error, and m_error_string.
Referenced by load().
 {
   iftext input(filespec);
   bool result = read(input, type_data);
   if (input.error())
   {
     result = false;
     m_error = input.error_number();
     m_error_string = input.error_string();
   }
   return result;
 }
bool lm_unit::read (itext & file, void * type_data) virtual
Definition at line 847 of file library_manager.cpp.
 {
   return false;
 }
bool lm_unit::restore_header (void) protected
Definition at line 538 of file library_manager.cpp.
References file_exists(), header_filename(), m_dependencies, m_header_modified, m_supplement, and restore().
Referenced by lm_unit().
 {
 //   try
 //   {
     if (file_exists(header_filename()))
     {
       iftext input(header_filename());
       restore_context context(input);
       restore(context, m_dependencies);
       restore(context, m_supplement);
     }
 //   }
 //   catch(persistent_restore_failed&)
 //   {
 //     return false;
 //   }
   m_header_modified = false;
   return true;
 }
bool lm_unit::save (void)
Definition at line 745 of file library_manager.cpp.
References filename(), library_manager::m_callbacks, m_library, m_loaded, lm_library::m_manager, m_marked, type(), and write().
 {
   if (!m_marked) return true;
   if (!m_loaded) return false;
   // get the user data for this type
   lm_callback_map::iterator callback = m_library->m_manager->m_callbacks.find(type());
   if (callback == m_library->m_manager->m_callbacks.end()) return false;
   void* data = callback->second.m_type_data;
   bool result = write(filename(), data);
   if (result) m_marked = false;
   return result;
 }
void lm_unit::set_dependencies (const lm_dependencies & dependencies)
Definition at line 682 of file library_manager.cpp.
References dependencies(), m_dependencies, and m_header_modified.
 {
   m_header_modified = true;
   m_dependencies = dependencies;
 }
void lm_unit::set_source_file (const lm_file_dependency & dependency)
Definition at line 612 of file library_manager.cpp.
References m_dependencies, m_header_modified, and lm_dependencies::set_source_file().
 {
   m_header_modified = true;
   m_dependencies.set_source_file(dependency);
 }
void lm_unit::set_supplementary_data (const std::string & data)
Definition at line 723 of file library_manager.cpp.
References m_header_modified, and m_supplement.
 {
   m_supplement = data;
   m_header_modified = true;
 }
const lm_file_dependency & lm_unit::source_file (void) const
Definition at line 623 of file library_manager.cpp.
References m_dependencies, and lm_dependencies::source_file().
 {
   return m_dependencies.source_file();
 }
bool lm_unit::source_file_present (void) const
Definition at line 618 of file library_manager.cpp.
References m_dependencies, and lm_dependencies::source_file_present().
 {
   return m_dependencies.source_file_present();
 }
const std::string & lm_unit::supplementary_data (void) const
Definition at line 718 of file library_manager.cpp.
References m_supplement.
 {
   return m_supplement;
 }
const std::string & lm_unit::type (void) const
Definition at line 603 of file library_manager.cpp.
References m_name, and lm_unit_name::type().
Referenced by load(), and save().
 {
   return m_name.type();
 }
unsigned lm_unit::unit_add (const lm_unit_dependency & dependency)
Definition at line 655 of file library_manager.cpp.
References m_dependencies, m_header_modified, and lm_dependencies::unit_add().
 {
   m_header_modified = true;
   return m_dependencies.unit_add(dependency);
 }
const lm_unit_dependency & lm_unit::unit_dependency (unsigned i) const
Definition at line 666 of file library_manager.cpp.
References m_dependencies, and lm_dependencies::unit_dependency().
 {
   return m_dependencies.unit_dependency(i);
 }
void lm_unit::unit_erase (unsigned i)
Definition at line 671 of file library_manager.cpp.
References m_dependencies, m_header_modified, and lm_dependencies::unit_erase().
 {
   m_header_modified = true;
   m_dependencies.unit_erase(i);
 }
const lm_unit_name & lm_unit::unit_name (void) const
Definition at line 593 of file library_manager.cpp.
References m_name.
 {
   return m_name;
 }
unsigned lm_unit::unit_size (void) const
Definition at line 661 of file library_manager.cpp.
References m_dependencies, and lm_dependencies::unit_size().
 {
   return m_dependencies.unit_size();
 }
bool lm_unit::up_to_date (void) const
Definition at line 706 of file library_manager.cpp.
References m_library, m_name, and lm_library::up_to_date().
 {
   return m_library->up_to_date(m_name);
 }
bool lm_unit::write (const std::string & filename, void * type_data) virtual
Definition at line 852 of file library_manager.cpp.
References otext::error(), otext::error_number(), otext::error_string(), m_error, m_error_string, and output().
Referenced by save().
 {
   oftext output(filespec);
   if (output.error()) return false;
   bool result = write(output, type_data);
   if (output.error())
   {
     result = false;
     m_error = output.error_number();
     m_error_string = output.error_string();
   }
   return result;
 }
bool lm_unit::write (otext & file, void * type_data) virtual
Definition at line 866 of file library_manager.cpp.
 {
   return false;
 }
Friends And Related Function Documentation
friend class lm_library friend
Definition at line 217 of file library_manager.hpp.
otext& operator<< (otext & str, const lm_unit & u) friend
Definition at line 827 of file library_manager.cpp.
 {
   return u.print(str);
 }
otext& print (otext & str, const lm_unit & u) friend
Definition at line 817 of file library_manager.cpp.
Referenced by operator<<(), and print().
 {
   return u.print(str);
 }
otext& print_long (otext & str, const lm_unit & u, unsigned indent) friend
Definition at line 822 of file library_manager.cpp.
Referenced by print_long().
 {
   return u.print_long(str, indent);
 }
Member Data Documentation
lm_dependencies lm_unit::m_dependencies private
Definition at line 349 of file library_manager.hpp.
Referenced by clear_dependencies(), dependencies(), dump_header(), empty_dependencies(), file_add(), file_dependency(), file_erase(), file_size(), print_long(), restore_header(), set_dependencies(), set_source_file(), source_file(), source_file_present(), unit_add(), unit_dependency(), unit_erase(), and unit_size().
int lm_unit::m_error private
Definition at line 361 of file library_manager.hpp.
Referenced by error_number(), read(), and write().
std::string lm_unit::m_error_string private
Definition at line 362 of file library_manager.hpp.
Referenced by error_string(), read(), and write().
bool lm_unit::m_header_modified private
Definition at line 351 of file library_manager.hpp.
Referenced by clear_dependencies(), dump_header(), file_add(), file_erase(), restore_header(), set_dependencies(), set_source_file(), set_supplementary_data(), unit_add(), and unit_erase().
lm_library* lm_unit::m_library private
Definition at line 358 of file library_manager.hpp.
Referenced by library(), library_name(), library_path(), load(), out_of_date(), out_of_date_reason(), save(), and up_to_date().
bool lm_unit::m_loaded private
Definition at line 354 of file library_manager.hpp.
Referenced by load(), loaded(), print(), and save().
bool lm_unit::m_marked private
Definition at line 355 of file library_manager.hpp.
Referenced by mark(), print(), and save().
lm_unit_name lm_unit::m_name private
Definition at line 348 of file library_manager.hpp.
Referenced by filename(), header_filename(), name(), out_of_date(), out_of_date_reason(), print(), print_long(), type(), unit_name(), and up_to_date().
std::string lm_unit::m_supplement private
Definition at line 350 of file library_manager.hpp.
Referenced by dump_header(), print_long(), restore_header(), set_supplementary_data(), and supplementary_data().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp