Visible: inf Class Reference
inf Class Reference
#include <include/stlplus/inf.hpp>
Classes
class divide_by_zero
Public Member Functions
inf (void)
inf (short)
inf (unsigned short)
inf (int)
inf (unsigned)
inf (long)
inf (unsigned long)
inf (const std::string &) throw (std::invalid_argument)
inf (const inf &)
~inf (void)
inf & operator= (short)
inf & operator= (unsigned short)
inf & operator= (int)
inf & operator= (unsigned)
inf & operator= (long)
inf & operator= (unsigned long)
inf & operator= (const std::string &) throw (std::invalid_argument)
inf & operator= (const inf &)
short to_short (void) const throw (std::overflow_error)
unsigned short to_ushort (void) const throw (std::overflow_error)
int to_int (void) const throw (std::overflow_error)
unsigned to_unsigned (void) const throw (std::overflow_error)
unsigned to_uint (void) const throw (std::overflow_error)
long to_long (void) const throw (std::overflow_error)
unsigned long to_ulong (void) const throw (std::overflow_error)
void resize (unsigned bits)
void reduce (void)
unsigned bits (void) const
unsigned size (void) const
unsigned indexable_bits (void) const
bool bit (unsigned index) const throw (std::out_of_range)
bool operator[] (unsigned index) const throw (std::out_of_range)
void set (unsigned index) throw (std::out_of_range)
void clear (unsigned index) throw (std::out_of_range)
void preset (unsigned index, bool value) throw (std::out_of_range)
inf slice (unsigned low, unsigned high) const throw (std::out_of_range)
bool negative (void) const
bool natural (void) const
bool positive (void) const
bool zero (void) const
bool non_zero (void) const
bool operator! (void) const
inf & invert (void)
inf & operator&= (const inf &)
inf & operator|= (const inf &)
inf & operator^= (const inf &)
inf & operator<<= (unsigned shift)
inf & operator>>= (unsigned shift)
inf & negate (void)
inf & abs (void)
inf & operator+= (const inf &)
inf & operator-= (const inf &)
inf & operator*= (const inf &)
inf & operator/= (const inf &) throw (divide_by_zero)
inf & operator%= (const inf &) throw (divide_by_zero)
inf & operator++ (void)
inf operator++ (int)
inf & operator-- (void)
inf operator-- (int)
std::string image_debug (void) const
std::string to_string (unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) const throw (std::invalid_argument)
void dump (dump_context &) const throw (persistent_dump_failed)
void restore (restore_context &) throw (persistent_restore_failed)
Private Member Functions
void set_head (void)
Private Attributes
std::string m_data
Friends
bool operator== (const inf &, const inf &)
bool operator!= (const inf &, const inf &)
bool operator< (const inf &, const inf &)
bool operator<= (const inf &, const inf &)
bool operator> (const inf &, const inf &)
bool operator>= (const inf &, const inf &)
inf operator~ (const inf &)
inf operator& (const inf &, const inf &)
inf operator| (const inf &, const inf &)
inf operator^ (const inf &, const inf &)
inf operator<< (const inf &, unsigned shift)
inf operator>> (const inf &, unsigned shift)
inf operator- (const inf &)
inf abs (const inf &)
inf operator+ (const inf &, const inf &)
inf operator- (const inf &, const inf &)
inf operator* (const inf &, const inf &)
inf operator/ (const inf &, const inf &) throw (divide_by_zero)
inf operator% (const inf &, const inf &) throw (divide_by_zero)
std::pair< inf, inf > divide (const inf &, const inf &) throw (divide_by_zero)
std::string to_string (const inf &i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
inf to_inf (const std::string &, unsigned radix=0) throw (std::invalid_argument)
otext & operator<< (otext &, const inf &)
itext & operator>> (itext &, inf &)
void dump (dump_context &str, const inf &data) throw (persistent_dump_failed)
void restore (restore_context &str, inf &data) throw (persistent_restore_failed)
Detailed Description
Definition at line 21 of file inf.hpp.
Constructor & Destructor Documentation
inf::inf (void)
Definition at line 59 of file inf.cpp.
References m_data, and value_type().
Referenced by negate(), operator++(), and operator--().
 {
   // void constructor initialises to zero - represented as a single-byte value containing zero
   m_data.append(1,std::string::value_type(0));
 }
inf::inf (short r) explicit
Definition at line 65 of file inf.cpp.
References operator=().
 {
   operator=(r);
 }
inf::inf (unsigned short r) explicit
Definition at line 70 of file inf.cpp.
References operator=().
 {
   operator=(r);
 }
inf::inf (int r) explicit
Definition at line 75 of file inf.cpp.
References operator=().
 {
   operator=(r);
 }
inf::inf (unsigned r) explicit
Definition at line 80 of file inf.cpp.
References operator=().
 {
   operator=(r);
 }
inf::inf (long r) explicit
Definition at line 85 of file inf.cpp.
References operator=().
 {
   operator=(r);
 }
inf::inf (unsigned long r) explicit
Definition at line 90 of file inf.cpp.
References operator=().
 {
   operator=(r);
 }
inf::inf (const std::string & r) throw (std::invalid_argument) explicit
Definition at line 95 of file inf.cpp.
References hash< K, T, H, E >::operator=().
 {
   operator=(r);
 }
inf::inf (const inf & r)
Definition at line 100 of file inf.cpp.
References m_data.
 {
   m_data = r.m_data;
 }
inf::~inf (void)
Definition at line 107 of file inf.cpp.
 {
 }
Member Function Documentation
inf & inf::abs (void)
Definition at line 698 of file inf.cpp.
References negate(), and negative().
Referenced by abs(), divide(), operator*=(), and to_string().
 {
   if (negative()) negate();
   return *this;
 }
bool inf::bit (unsigned index) const throw (std::out_of_range)
Definition at line 307 of file inf.cpp.
References to_string().
Referenced by bits(), and negative().
 {
   if (index >= indexable_bits())
     throw std::out_of_range(std::string("inf::bit: index ") + to_string(index) +
                             std::string(" out of range of inf size ") + to_string(indexable_bits()));
   // first split the offset into byte offset and bit offset
   unsigned byte_offset = index/8;
   unsigned bit_offset = index%8;
   return (byte(m_data[byte_offset]) & (byte(1) << bit_offset)) != 0;
 }
unsigned inf::bits (void) const
Definition at line 282 of file inf.cpp.
References bit(), and indexable_bits().
Referenced by divide(), operator*=(), operator<<=(), and size().
 {
   // The number of significant bits in the integer value - this is the number
   // of indexable bits less any redundant sign bits at the msb
   // This does not assume that the inf has been reduced to its minimum form
   unsigned result = indexable_bits();
   bool sign = bit(result-1);
   while (result > 1 && (sign == bit(result-2)))
     result--;
   return result;
 }
void inf::clear (unsigned index) throw (std::out_of_range)
Definition at line 334 of file inf.cpp.
References to_string().
 {
   if (index >= indexable_bits())
     throw std::out_of_range(std::string("inf::clear: index ") + to_string(index) +
                             std::string(" out of range of inf size ") + to_string(indexable_bits()));
   // first split the offset into byte offset and bit offset
   unsigned byte_offset = index/8;
   unsigned bit_offset = index%8;
   m_data[byte_offset] &= (~(byte(1) << bit_offset));
 }
void inf::dump (dump_context & str) const throw (persistent_dump_failed)
Definition at line 1411 of file inf.cpp.
References dump(), and to_string().
 {
   // don't support dumping of old versions
   if (str.version() < 2)
     throw persistent_dump_failed(std::string("inf::dump: wrong version: ") + to_string(str.version()));
   // just dump the string
   ::dump(str,m_data);
 }
std::string inf::image_debug (void) const
Definition at line 1364 of file inf.cpp.
References DEBUG_ASSERT, and m_data.
 {
   // create this dump in the human-readable form, i.e. msB to the left
   std::string result = "0x";
   for (std::string::size_type i = m_data.size(); i--; )
   {
     byte current = m_data[i];
     byte msB = (current & byte(0xf0)) >> 8;
     DEBUG_ASSERT(msB < 16);
     result += to_char[msB];
     byte lsB = (current & byte(0x0f));
     DEBUG_ASSERT(lsB < 16);
     result += to_char[lsB];
   }
   return result;
 }
unsigned inf::indexable_bits (void) const
Definition at line 299 of file inf.cpp.
References m_data.
Referenced by bits(), and negative().
 {
   return 8 * unsigned(m_data.size());
 }
inf & inf::invert (void)
Definition at line 509 of file inf.cpp.
References m_data.
Referenced by negate(), and operator~().
 {
   for (std::string::size_type i = 0; i < m_data.size(); i++)
     m_data[i] = ~m_data[i];
   return *this;
 }
bool inf::natural (void) const
Definition at line 385 of file inf.cpp.
References negative().
Referenced by inf_to_unsigned(), and positive().
 {
   return !negative();
 }
inf & inf::negate (void)
Definition at line 682 of file inf.cpp.
References inf(), invert(), and operator+=().
Referenced by abs(), divide(), operator*=(), operator-(), and to_inf().
 {
   // do 2's-complement negation
   // equivalent to negation plus one
   invert();
   operator += (inf(1));
   return *this;
 }
bool inf::negative (void) const
Definition at line 380 of file inf.cpp.
References bit(), and indexable_bits().
Referenced by abs(), divide(), inf_to_signed(), natural(), operator&=(), operator*=(), operator+=(), operator<(), operator<<=(), operator==(), operator>>=(), operator^=(), operator|=(), resize(), and to_string().
 {
   return bit(indexable_bits()-1);
 }
bool inf::non_zero (void) const
Definition at line 405 of file inf.cpp.
References zero().
Referenced by inf_to_signed(), and inf_to_unsigned().
 {
   return !zero();
 }
bool inf::operator! (void) const
Definition at line 410 of file inf.cpp.
References zero().
 {
   return zero();
 }
inf & inf::operator%= (const inf & r) throw (divide_by_zero)
Definition at line 818 of file inf.cpp.
References divide(), and hash< K, T, H, E >::operator=().
 {
   std::pair<inf,inf> result = divide(*this,r);
   operator=(result.second);
   return *this;
 }
inf & inf::operator&= (const inf & r)
Definition at line 523 of file inf.cpp.
References m_data, maximum(), and negative().
 {
   // bitwise AND is extended to the length of the largest argument
   byte l_extend = negative() ? byte(255) : byte (0);
   byte r_extend = r.negative() ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(m_data.size(),r.m_data.size());
   for (std::string::size_type i = 0; i < bytes; i++)
   {
     byte l_byte = (i < m_data.size() ? byte(m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     byte result = l_byte & r_byte;
     if (i < m_data.size())
       m_data[i] = result;
     else
       m_data.append(1,result);
   }
   return *this;
 }
inf & inf::operator*= (const inf & r)
Definition at line 770 of file inf.cpp.
References abs(), bits(), negate(), negative(), operator+=(), and operator=().
 {
   // 2's complement multiplication
   // one day I'll do a more efficient version than this based on the underlying representation
   inf left = *this;
   inf right = r;
   // make the right value natural but preserve its sign for later
   bool right_negative = right.negative();
   right.abs();
   // implemented as a series of conditional additions
   operator = (0);
 //  left.resize(right.bits() + left.bits() - 1);
   left <<= right.bits()-1;
   for (unsigned i = right.bits(); i--; )
   {
     if (right[i])
       operator += (left);
     left >>= 1;
   }
   if (right_negative)
     negate();
   return *this;
 }
inf & inf::operator++ (void)
Definition at line 884 of file inf.cpp.
References inf(), and operator+=().
 {
   operator += (inf(1));
   return *this;
 }
inf inf::operator++ (int)
Definition at line 890 of file inf.cpp.
References inf(), and operator+=().
 {
   inf old = *this;
   operator += (inf(1));
   return old;
 }
inf & inf::operator+= (const inf & r)
Definition at line 714 of file inf.cpp.
References m_data, maximum(), and negative().
Referenced by negate(), operator*=(), operator++(), and operator-=().
 {
   // do 2's-complement addition
   // Note that the addition can give a result that is larger than either argument
   byte carry = 0;
   std::string::size_type max_size = maximum(m_data.size(),r.m_data.size());
   byte l_extend = negative() ? byte(255) : byte (0);
   byte r_extend = r.negative() ? byte(255) : byte (0);
   for (std::string::size_type i = 0; i < max_size; i++)
   {
     byte l_byte = (i < m_data.size() ? byte(m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     // calculate the addition in a type that is bigger than a byte in order to catch the carry-out
     unsigned short result = ((unsigned short)(l_byte)) + ((unsigned short)(r_byte)) + carry;
     // now truncate the result to get the lsB
     if (i < m_data.size())
       m_data[i] = byte(result);
     else
       m_data.append(1,byte(result));
     // and capture the carry out by grabbing the second byte of the result
     carry = byte(result >> 8);
   }
   // if the result overflowed or underflowed, add an extra byte to catch it
   unsigned short result = ((unsigned short)(l_extend)) + ((unsigned short)(r_extend)) + carry;
   if (byte(result) != (negative() ? byte(255) : byte(0)))
     m_data.append(1,byte(result));
   return *this;
 }
inf & inf::operator-- (void)
Definition at line 897 of file inf.cpp.
References inf(), and operator-=().
 {
   operator -= (inf(1));
   return *this;
 }
inf inf::operator-- (int)
Definition at line 903 of file inf.cpp.
References inf(), and operator-=().
 {
   inf old = *this;
   operator -= (inf(1));
   return old;
 }
inf & inf::operator-= (const inf & r)
Definition at line 753 of file inf.cpp.
References operator+=().
Referenced by operator--().
 {
   // subtraction is defined in terms of negation and addition
   operator += (-r);
   return *this;
 }
inf & inf::operator/= (const inf & r) throw (divide_by_zero)
Definition at line 804 of file inf.cpp.
References divide(), and hash< K, T, H, E >::operator=().
 {
   std::pair<inf,inf> result = divide(*this,r);
   operator=(result.first);
   return *this;
 }
inf & inf::operator<<= (unsigned shift)
Definition at line 604 of file inf.cpp.
References bits(), m_data, and negative().
 {
   // left shift is a shift towards the msb, with 0s being shifted in at the lsb
   // split this into a byte shift followed by a bit shift
   // first expand the value to be big enough for the result
   // only count significant bits though
   std::string::size_type new_size = (bits() + shift + 7) / 8;
   byte extend = negative() ? byte(255) : byte (0);
   while (m_data.size() < new_size)
     m_data.append(1,extend);
   // now do the byte shift
   unsigned byte_shift = shift/8;
   if (byte_shift > 0)
   {
     for (std::string::size_type b = new_size; b--; )
       m_data[b] = (b >= byte_shift) ? m_data[b-byte_shift] : byte(0);
   }
   // and finally the bit shift
   unsigned bit_shift = shift%8;
   if (bit_shift > 0)
   {
     for (std::string::size_type b = new_size; b--; )
     {
       byte current = byte(m_data[b]);
       byte previous = b > 0 ? m_data[b-1] : byte(0);
       m_data[b] = (current << bit_shift) | (previous >> (8 - bit_shift));
     }
   }
   return *this;
 }
inf & inf::operator= (short r)
Definition at line 113 of file inf.cpp.
References little_endian(), m_data, and reduce().
Referenced by inf(), and operator*=().
 {
   m_data.erase();
   bool lsb_first = little_endian();
   byte* address = (byte*)&r;
   size_t bytes = sizeof(short);
   for (size_t i = 0; i < bytes; i++)
     m_data.append(1,address[(lsb_first ? i : (bytes - i - 1))]);
   reduce();
   return *this;
 }
inf & inf::operator= (unsigned short r)
Definition at line 125 of file inf.cpp.
References little_endian(), m_data, reduce(), and value_type().
 {
   m_data.erase();
   bool lsb_first = little_endian();
   byte* address = (byte*)&r;
   size_t bytes = sizeof(unsigned short);
   for (size_t i = 0; i < bytes; i++)
     m_data.append(1,address[(lsb_first ? i : (bytes - i - 1))]);
   // inf is signed - so there is a possible extra sign bit to add
   m_data.append(1,std::string::value_type(0));
   reduce();
   return *this;
 }
inf & inf::operator= (int r)
Definition at line 139 of file inf.cpp.
References little_endian(), m_data, and reduce().
 {
   m_data.erase();
   bool lsb_first = little_endian();
   byte* address = (byte*)&r;
   size_t bytes = sizeof(int);
   for (size_t i = 0; i < bytes; i++)
     m_data.append(1,address[(lsb_first ? i : (bytes - i - 1))]);
   reduce();
   return *this;
 }
inf & inf::operator= (unsigned r)
Definition at line 151 of file inf.cpp.
References little_endian(), m_data, reduce(), and value_type().
 {
   m_data.erase();
   bool lsb_first = little_endian();
   byte* address = (byte*)&r;
   size_t bytes = sizeof(unsigned);
   for (size_t i = 0; i < bytes; i++)
     m_data.append(1,address[(lsb_first ? i : (bytes - i - 1))]);
   // inf is signed - so there is a possible extra sign bit to add
   m_data.append(1,std::string::value_type(0));
   reduce();
   return *this;
 }
inf & inf::operator= (long r)
Definition at line 165 of file inf.cpp.
References little_endian(), m_data, and reduce().
 {
   m_data.erase();
   bool lsb_first = little_endian();
   byte* address = (byte*)&r;
   size_t bytes = sizeof(long);
   for (size_t i = 0; i < bytes; i++)
     m_data.append(1,address[(lsb_first ? i : (bytes - i - 1))]);
   reduce();
   return *this;
 }
inf & inf::operator= (unsigned long r)
Definition at line 177 of file inf.cpp.
References little_endian(), m_data, reduce(), and value_type().
 {
   m_data.erase();
   bool lsb_first = little_endian();
   byte* address = (byte*)&r;
   size_t bytes = sizeof(unsigned long);
   for (size_t i = 0; i < bytes; i++)
     m_data.append(1,address[(lsb_first ? i : (bytes - i - 1))]);
   // inf is signed - so there is a possible extra sign bit to add
   m_data.append(1,std::string::value_type(0));
   reduce();
   return *this;
 }
inf & inf::operator= (const std::string & r) throw (std::invalid_argument)
Definition at line 191 of file inf.cpp.
References hash< K, T, H, E >::operator=(), and to_inf().
 {
   operator = (::to_inf(r, 10));
   return *this;
 }
inf & inf::operator= (const inf & r)
Definition at line 197 of file inf.cpp.
References m_data.
 {
   m_data = r.m_data;
   return *this;
 }
inf & inf::operator>>= (unsigned shift)
Definition at line 643 of file inf.cpp.
References m_data, and negative().
 {
   // right shift is a shift towards the lsb, with sign bits being shifted in at the msb
   // split this into a byte shift followed by a bit shift
   // a byte of sign bits
   byte extend = negative() ? byte(255) : byte (0);
   // do the byte shift
   unsigned byte_shift = shift/8;
   if (byte_shift > 0)
   {
     for (std::string::size_type b = 0; b < m_data.size(); b++)
       m_data[b] = (b + byte_shift < m_data.size()) ? m_data[b+byte_shift] : extend;
   }
   // and finally the bit shift
   unsigned bit_shift = shift%8;
   if (bit_shift > 0)
   {
     for (std::string::size_type b = 0; b < m_data.size(); b++)
     {
       byte current = byte(m_data[b]);
       byte next = ((b+1) < m_data.size()) ? m_data[b+1] : extend;
       byte shifted = (current >> bit_shift) | (next << (8 - bit_shift));
       m_data[b] = shifted;
     }
   }
   return *this;
 }
bool inf::operator[] (unsigned index) const throw (std::out_of_range)
Definition at line 318 of file inf.cpp.
 {
   return bit(index);
 }
inf & inf::operator^= (const inf & r)
Definition at line 575 of file inf.cpp.
References m_data, maximum(), and negative().
 {
   // bitwise XOR is extended to the length of the largest argument
   byte l_extend = negative() ? byte(255) : byte (0);
   byte r_extend = r.negative() ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(m_data.size(),r.m_data.size());
   for (std::string::size_type i = 0; i < bytes; i++)
   {
     byte l_byte = (i < m_data.size() ? byte(m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     byte result = l_byte ^ r_byte;
     if (i < m_data.size())
       m_data[i] = result;
     else
       m_data.append(1,result);
   }
   return *this;
 }
inf & inf::operator|= (const inf & r)
Definition at line 549 of file inf.cpp.
References m_data, maximum(), and negative().
 {
   // bitwise OR is extended to the length of the largest argument
   byte l_extend = negative() ? byte(255) : byte (0);
   byte r_extend = r.negative() ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(m_data.size(),r.m_data.size());
   for (std::string::size_type i = 0; i < bytes; i++)
   {
     byte l_byte = (i < m_data.size() ? byte(m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     byte result = l_byte | r_byte;
     if (i < m_data.size())
       m_data[i] = result;
     else
       m_data.append(1,result);
   }
   return *this;
 }
bool inf::positive (void) const
Definition at line 390 of file inf.cpp.
References natural(), and zero().
 {
   return natural() && !zero();
 }
void inf::preset (unsigned index, bool value) throw (std::out_of_range)
Definition at line 345 of file inf.cpp.
References hash< K, T, H, E >::clear().
Referenced by slice(), and to_inf().
 {
   if (value)
     set(index);
   else
     clear(index);
 }
void inf::reduce (void)
Definition at line 1396 of file inf.cpp.
References m_data.
Referenced by operator=().
 {
   // remove leading bytes providing that it doesn't change the value
   // however, don't reduce to zero bytes
   while(m_data.size() > 1 &&
         ((byte(m_data[m_data.size()-1]) == byte(0) && byte(m_data[m_data.size()-2]) < byte(128)) ||
          (byte(m_data[m_data.size()-1]) == byte(255) && byte(m_data[m_data.size()-2]) >= byte(128))))
   {
     m_data.erase(m_data.end()-1);
   }
 }
void inf::resize (unsigned bits)
Definition at line 1385 of file inf.cpp.
References m_data, and negative().
Referenced by divide(), and to_inf().
 {
   if (bits == 0) bits = 1;
   unsigned bytes = (bits+7)/8;
   byte extend = negative() ? byte(255) : byte (0);
   while(bytes > m_data.size())
     m_data.append(1,extend);
 }
void inf::restore (restore_context & str) throw (persistent_restore_failed)
Definition at line 1420 of file inf.cpp.
References restore(), and to_string().
 {
   if (str.version() < 1)
     throw persistent_restore_failed(std::string("inf::restore: wrong version: ") + to_string(str.version()));
   if (str.version() == 1)
   {
     // old-style restore relies on the word size being the same - 32-bits - on all platforms
     // this can be restored on such machines but is not portable to 64-bit machines
     unsigned bits = 0;
     ::restore(str,bits);
     unsigned words = (bits+7)/32;
     // inf was dumped msB first
     for (unsigned i = words; i--; )
     {
       // restore a word
       unsigned data = 0;
       ::restore(str,data);
       // now extract the bytes
       unsigned char* word = (unsigned char*)(&data);
       for (unsigned b = 4; b--; )
         m_data.insert(m_data.begin(),byte(word[str.little_endian() ? b : 3 - b]));
     }
   }
   else
   {
     // new-style dump just uses the string persistence
     ::restore(str,m_data);
   }
 }
void inf::set (unsigned index) throw (std::out_of_range)
Definition at line 323 of file inf.cpp.
References to_string().
Referenced by divide().
 {
   if (index >= indexable_bits())
     throw std::out_of_range(std::string("inf::set: index ") + to_string(index) +
                             std::string(" out of range of inf size ") + to_string(indexable_bits()));
   // first split the offset into byte offset and bit offset
   unsigned byte_offset = index/8;
   unsigned bit_offset = index%8;
   m_data[byte_offset] |= (byte(1) << bit_offset);
 }
void inf::set_head (void) private
Definition at line 52 of file inf.cpp.
 {
 }
unsigned inf::size (void) const
Definition at line 294 of file inf.cpp.
References bits().
 {
   return bits();
 }
inf inf::slice (unsigned low, unsigned high) const throw (std::out_of_range)
Definition at line 353 of file inf.cpp.
References m_data, preset(), and to_string().
 {
   if (low >= indexable_bits())
     throw std::out_of_range(std::string("inf::slice: low index ") + to_string(low) +
                             std::string(" out of range of inf size ") + to_string(indexable_bits()));
   if (high >= indexable_bits())
     throw std::out_of_range(std::string("inf::slice: high index ") + to_string(high) +
                             std::string(" out of range of inf size ") + to_string(indexable_bits()));
   inf result;
   if (high >= low)
   {
     // create a result the right size and filled with sign bits
     std::string::size_type result_size = (high-low+1+7)/8;
     result.m_data.erase();
     byte extend = bit(high) ? byte(255) : byte (0);
     while (result.m_data.size() < result_size)
       result.m_data.append(1,extend);
     // now set the relevant bits
     for (unsigned i = low; i <= high; i++)
       result.preset(i-low, bit(i));
   }
   return result;
 }
int inf::to_int (void) const throw (std::overflow_error)
Definition at line 228 of file inf.cpp.
References little_endian(), and m_data.
 {
   int result = 0;
   bool lsb_first = little_endian();
   byte* address = (byte*)&result;
   size_t bytes = sizeof(int);
   for (size_t i = 0; i < bytes; i++)
     address[(lsb_first ? i : (bytes - i - 1))] =
       (i < m_data.size()) ? byte(m_data[i]) : (m_data.empty() || (byte(m_data[m_data.size()-1]) < (byte(128)))) ? byte(0) : byte(255);
   return result;
 }
long inf::to_long (void) const throw (std::overflow_error)
Definition at line 256 of file inf.cpp.
References little_endian(), and m_data.
 {
   long result = 0;
   bool lsb_first = little_endian();
   byte* address = (byte*)&result;
   size_t bytes = sizeof(long);
   for (size_t i = 0; i < bytes; i++)
     address[(lsb_first ? i : (bytes - i - 1))] =
       (i < m_data.size()) ? byte(m_data[i]) : (m_data.empty() || (byte(m_data[m_data.size()-1]) < (byte(128)))) ? byte(0) : byte(255);
   return result;
 }
short inf::to_short (void) const throw (std::overflow_error)
Definition at line 205 of file inf.cpp.
References little_endian(), and m_data.
 {
   short result = 0;
   bool lsb_first = little_endian();
   byte* address = (byte*)&result;
   size_t bytes = sizeof(short);
   for (size_t i = 0; i < bytes; i++)
     address[(lsb_first ? i : (bytes - i - 1))] =
       (i < m_data.size()) ? byte(m_data[i]) : (m_data.empty() || (byte(m_data[m_data.size()-1]) < (byte(128)))) ? byte(0) : byte(255);
   return result;
 }
std::string inf::to_string (unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) const throw (std::invalid_argument)
Definition at line 938 of file inf.cpp.
References to_string().
 {
   return ::to_string(*this, radix, display, width);
 }
unsigned inf::to_uint (void) const throw (std::overflow_error)
Definition at line 251 of file inf.cpp.
References to_unsigned().
 {
   return to_unsigned();
 }
unsigned long inf::to_ulong (void) const throw (std::overflow_error)
Definition at line 268 of file inf.cpp.
References little_endian(), and m_data.
 {
   unsigned long result = 0;
   bool lsb_first = little_endian();
   byte* address = (byte*)&result;
   size_t bytes = sizeof(unsigned long);
   for (size_t i = 0; i < bytes; i++)
     address[(lsb_first ? i : (bytes - i - 1))] = (i < m_data.size()) ? byte(m_data[i]) : byte(0);
   return result;
 }
unsigned inf::to_unsigned (void) const throw (std::overflow_error)
Definition at line 240 of file inf.cpp.
References little_endian(), and m_data.
Referenced by to_uint().
 {
   unsigned result = 0;
   bool lsb_first = little_endian();
   byte* address = (byte*)&result;
   size_t bytes = sizeof(unsigned);
   for (size_t i = 0; i < bytes; i++)
     address[(lsb_first ? i : (bytes - i - 1))] = (i < m_data.size()) ? byte(m_data[i]) : byte(0);
   return result;
 }
unsigned short inf::to_ushort (void) const throw (std::overflow_error)
Definition at line 217 of file inf.cpp.
References little_endian(), and m_data.
 {
   unsigned short result = 0;
   bool lsb_first = little_endian();
   byte* address = (byte*)&result;
   size_t bytes = sizeof(unsigned short);
   for (size_t i = 0; i < bytes; i++)
     address[(lsb_first ? i : (bytes - i - 1))] = (i < m_data.size()) ? byte(m_data[i]) : byte(0);
   return result;
 }
bool inf::zero (void) const
Definition at line 395 of file inf.cpp.
References m_data.
Referenced by non_zero(), operator!(), positive(), and to_string().
 {
   for (std::string::size_type i = 0; i < m_data.size(); i++)
   {
     if (m_data[i] != 0)
       return false;
   }
   return true;
 }
Friends And Related Function Documentation
inf abs (const inf &) friend
Definition at line 704 of file inf.cpp.
 {
   inf result = i;
   result.abs();
   return result;
 }
std::pair<inf,inf> divide (const inf & , const inf &) throw (divide_by_zero) friend
Definition at line 832 of file inf.cpp.
 {
   if(right.zero()) throw inf::divide_by_zero("divide by zero in divide: " + ::to_string(left) + "/" + ::to_string(right));
   inf numerator = left;
   inf denominator = right;
   // make the numerator natural but preserve the sign for later
   bool numerator_negative = numerator.negative();
   numerator.abs();
   // same with the denominator
   bool denominator_negative = denominator.negative();
   denominator.abs();
   // the quotient and remainder will form the result
   // start with the quotiont zero and the remainder equal to the whole of the numerator, then do trial subtraction from this
   inf quotient;
   inf remainder = numerator;
   // there's nothing more to do if the numerator is smaller than the denominator
   // but otherwise do the division
   if (numerator.bits() >= denominator.bits())
   {
     // make the quotient big enough to take the result
     quotient.resize(numerator.bits());
     // start with the numerator shifted to the far left
     unsigned shift = numerator.bits() - denominator.bits();
     denominator <<= shift;
     // do the division by repeated subtraction,
     for (unsigned i = shift+1; i--; )
     {
       if (remainder >= denominator)
       {
         remainder -= denominator;
         quotient.set(i);
       }
       denominator >>= 1;
     }
   }
   // now adjust the signs
   // x/(-y) == (-x)/y == -(x/y)
   if (numerator_negative != denominator_negative)
   {
     quotient.negate();
   }
   // x%(-y) == x%y and (-x)%y == -(x%y)
   if (numerator_negative)
   {
     remainder.negate();
   }
   return std::pair<inf,inf>(quotient,remainder);
 }
void dump (dump_context & str, const inf & data) throw (persistent_dump_failed) friend
Definition at line 1452 of file inf.cpp.
 {
   data.dump(str);
 }
bool operator!= (const inf & , const inf &) friend
Definition at line 436 of file inf.cpp.
 {
   return !(l == r);
 }
inf operator% (const inf & , const inf &) throw (divide_by_zero) friend
Definition at line 825 of file inf.cpp.
 {
   inf result = l;
   result %= r;
   return result;
 }
inf operator& (const inf & , const inf &) friend
Definition at line 542 of file inf.cpp.
 {
   inf result = l;
   result &= r;
   return result;
 }
inf operator* (const inf & , const inf &) friend
Definition at line 794 of file inf.cpp.
 {
   inf result = l;
   result *= r;
   return result;
 }
inf operator+ (const inf & , const inf &) friend
Definition at line 743 of file inf.cpp.
 {
   inf result = l;
   result += r;
   return result;
 }
inf operator- (const inf &) friend
Definition at line 691 of file inf.cpp.
 {
   inf result = r;
   result.negate();
   return result;
 }
inf operator- (const inf & , const inf &) friend
Definition at line 760 of file inf.cpp.
 {
   inf result = l;
   result -= r;
   return result;
 }
inf operator/ (const inf & , const inf &) throw (divide_by_zero) friend
Definition at line 811 of file inf.cpp.
 {
   inf result = l;
   result /= r;
   return result;
 }
bool operator< (const inf & , const inf &) friend
Definition at line 441 of file inf.cpp.
 {
   // This was originally implemented in terms of subtraction. However, it can
   // be simplified since there is no need to calculate the accurate
   // difference, just the direction of the difference. I compare from msB down
   // and as soon as a byte difference is found, that defines the ordering. The
   // problem is that in 2's-complement, all negative values are greater than
   // all natural values if you just do a straight unsigned comparison. I
   // handle this by doing a preliminary test for different signs.
   // For example, a 3-bit signed type has the coding:
   // 000 = 0
   // ...
   // 011 = 3
   // 100 = -4
   // ...
   // 111 = -1
   // So, for natural values, the ordering of the integer values is the ordering of the bit patterns
   // Similarly, for negative values, the ordering of the integer values is the ordering of the bit patterns
   // However, the bit patterns for the negative values are *greater than* the natural values
   // This is a side-effect of the naffness of 2's-complement representation
   // first handle the case of comparing two values with different signs
   bool l_sign = l.negative();
   bool r_sign = r.negative();
   if (l_sign != r_sign)
   {
     // one argument must be negative and the other natural
     // the left is less if it is the negative one
     return l_sign;
   }
   // the arguments are the same sign
   // so the ordering is a simple unsigned byte-by-byte comparison
   // However, this is complicated by the possibility that the values could be different lengths
   byte l_extend = l_sign ? byte(255) : byte (0);
   byte r_extend = r_sign ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(l.m_data.size(),r.m_data.size());
   for (std::string::size_type i = bytes; i--; )
   {
     byte l_byte = (i < l.m_data.size() ? byte(l.m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     if (l_byte != r_byte)
     {
       return l_byte < r_byte;
     }
   }
   // if I get here, the two are equal, so that is not less-than
   return false;
 }
inf operator<< (const inf & , unsigned shift) friend
Definition at line 636 of file inf.cpp.
 {
   inf result = l;
   result <<= shift;
   return result;
 }
otext& operator<< (otext & , const inf &) friend
Definition at line 1332 of file inf.cpp.
 {
   try
   {
     str << to_string(i, str.integer_radix(), str.integer_display(), str.integer_width());
   }
   catch(const std::invalid_argument)
   {
     str.set_error(textio_format_error);
   }
   return str;
 }
bool operator<= (const inf & , const inf &) friend
Definition at line 491 of file inf.cpp.
 {
   return !(r < l);
 }
bool operator== (const inf & , const inf &) friend
Definition at line 418 of file inf.cpp.
 {
   // Two infs are equal if they are numerically equal, even if they are different sizes (i.e. they could be non-reduced values).
   // This makes life a little more complicated than if I could assume that values were reduced.
   // In the first version I defined equality in terms of subtraction but I'd like to use a more direct approach here.
   byte l_extend = l.negative() ? byte(255) : byte (0);
   byte r_extend = r.negative() ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(l.m_data.size(),r.m_data.size());
   for (std::string::size_type i = bytes; i--; )
   {
     byte l_byte = (i < l.m_data.size() ? byte(l.m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     if (l_byte != r_byte)
       return false;
   }
   return true;
 }
bool operator> (const inf & , const inf &) friend
Definition at line 496 of file inf.cpp.
 {
   return r < l;
 }
bool operator>= (const inf & , const inf &) friend
Definition at line 501 of file inf.cpp.
 {
   return !(l < r);
 }
inf operator>> (const inf & , unsigned shift) friend
Definition at line 672 of file inf.cpp.
 {
   inf result = l;
   result >>= shift;
   return result;
 }
itext& operator>> (itext & , inf &) friend
Definition at line 1345 of file inf.cpp.
 {
   try
   {
     std::string image;
     str >> image;
     i = to_inf(image);
   }
   catch(const std::invalid_argument)
   {
     str.set_error(textio_format_error);
   }
   return str;
 }
inf operator^ (const inf & , const inf &) friend
Definition at line 594 of file inf.cpp.
 {
   inf result = l;
   result ^= r;
   return result;
 }
inf operator| (const inf & , const inf &) friend
Definition at line 568 of file inf.cpp.
 {
   inf result = l;
   result |= r;
   return result;
 }
inf operator~ (const inf &) friend
Definition at line 516 of file inf.cpp.
 {
   inf result = r;
   result.invert();
   return result;
 }
void restore (restore_context & str, inf & data) throw (persistent_restore_failed) friend
Definition at line 1458 of file inf.cpp.
 {
   data.restore(str);
 }
inf to_inf (const std::string & , unsigned radix = 0) throw (std::invalid_argument) friend
Definition at line 1111 of file inf.cpp.
 {
   if (radix != 0 && (radix < 2 || radix > 36))
     throw std::invalid_argument("invalid radix value " + to_string(radix));
   unsigned i = 0;
   // the radix passed as a parameter is just the default - it can be overridden by either the C prefix or the hash prefix
   // Note: a leading zero is the C-style prefix for octal - I only make this override the default when the default prefix is not specified
   // first chk for a C-style prefix
   bool c_style = false;
   if (i < str.size() && str[i] == '0')
   {
     // binary or hex
     if (i+1 < str.size() && tolower(str[i+1]) == 'x')
     {
       radix = 16;
       i += 2;
       c_style = true;
     }
     else if (i+1 < str.size() && tolower(str[i+1]) == 'b')
     {
       radix = 2;
       i += 2;
       c_style = true;
     }
     else if (radix == 0)
     {
       radix = 8;
       i += 1;
       c_style = true;
     }
   }
   // now chk for a hash-style prefix if a C-style prefix was not found
   if (i == 0)
   {
     // scan for the sequence {digits}#
     bool hash_found = false;
     unsigned j = i;
     for (; j < str.size(); j++)
     {
       if (!isdigit(str[j]))
       {
         if (str[j] == '#')
           hash_found = true;
         break;
       }
     }
     if (hash_found)
     {
       // use the hash prefix to define the radix
       // i points to the start of the radix and j points to the # character
       std::string slice = str.substr(i, j-i);
       radix = to_uint(slice);
       i = j+1;
     }
   }
   if (radix == 0)
     radix = 10;
   if (radix < 2 || radix > 36)
     throw std::invalid_argument("invalid radix value " + to_string(radix));
   inf val;
   if (c_style)
   {
     // the C style formats are bit patterns not integer values - these need to be sign-extended to get the right value
     std::string binary;
     DEBUG_ASSERT(radix == 2 || radix == 8 || radix == 16);
     if (radix == 2)
     {
       for (unsigned j = i; j < str.size(); j++)
       {
         switch(str[j])
         {
         case '0':
           binary += '0';
           break;
         case '1':
           binary += '1';
           break;
         default:
           throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
           break;
         }
       }
     }
     else if (radix == 8)
     {
       for (unsigned j = i; j < str.size(); j++)
       {
         switch(str[j])
         {
         case '0':
           binary += "000";
           break;
         case '1':
           binary += "001";
           break;
         case '2':
           binary += "010";
           break;
         case '3':
           binary += "011";
           break;
         case '4':
           binary += "100";
           break;
         case '5':
           binary += "101";
           break;
         case '6':
           binary += "110";
           break;
         case '7':
           binary += "111";
           break;
         default:
           throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
           break;
         }
       }
     }
     else
     {
       for (unsigned j = i; j < str.size(); j++)
       {
         switch(tolower(str[j]))
         {
         case '0':
           binary += "0000";
           break;
         case '1':
           binary += "0001";
           break;
         case '2':
           binary += "0010";
           break;
         case '3':
           binary += "0011";
           break;
         case '4':
           binary += "0100";
           break;
         case '5':
           binary += "0101";
           break;
         case '6':
           binary += "0110";
           break;
         case '7':
           binary += "0111";
           break;
         case '8':
           binary += "1000";
           break;
         case '9':
           binary += "1001";
           break;
         case 'a':
           binary += "1010";
           break;
         case 'b':
           binary += "1011";
           break;
         case 'c':
           binary += "1100";
           break;
         case 'd':
           binary += "1101";
           break;
         case 'e':
           binary += "1110";
           break;
         case 'f':
           binary += "1111";
           break;
         default:
           throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
           break;
         }
       }
     }
     // now convert the value
     val.resize(binary.size());
     for (unsigned j = 0; j < binary.size(); j++)
     {
       DEBUG_ASSERT(from_char[(unsigned char)binary[j]] != -1);
       val.preset(binary.size() - j - 1, binary[j] == '1');
     }
   }
   else
   {
     // now scan for a sign and find whether this is a negative number
     bool negative = false;
     if (i < str.size())
     {
       switch (str[i])
       {
       case '-':
         negative = true;
         i++;
         break;
       case '+':
         i++;
         break;
       }
     }
     for (; i < str.size(); i++)
     {
       val *= inf(radix);
       int ch = from_char[(unsigned char)str[i]] ;
       if (ch == -1)
       {
         throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
       }
       val += inf(ch);
     }
     if (negative)
       val.negate();
   }
   return val;
 }
std::string to_string (const inf & i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument) friend
Definition at line 944 of file inf.cpp.
 {
   if (radix < 2 || radix > 36)
     throw std::invalid_argument("invalid radix value " + to_string(radix));
   inf local_i = i;
   // untangle all the options
   bool hashed = false;
   bool binary = false;
   bool octal = false;
   bool hex = false;
   switch(display)
   {
   case radix_none:
     break;
   case radix_hash_style:
     hashed = radix != 10;
     break;
   case radix_hash_style_all:
     hashed = true;
     break;
   case radix_c_style:
     if (radix == 16)
       hex = true;
     else if (radix == 8)
       octal = true;
     else if (radix == 2)
       binary = true;
     break;
   case radix_c_style_or_hash:
     if (radix == 16)
       hex = true;
     else if (radix == 8)
       octal = true;
     else if (radix == 2)
       binary = true;
     else if (radix != 10)
       hashed = true;
     break;
   default:
     throw std::invalid_argument("invalid radix display value");
   }
   // create constants of the same type as the template parameter to avoid type mismatches
   const inf t_zero(0);
   const inf t_radix(radix);
   // the C representations for binary, octal and hex use 2's-complement representation
   // all other represenations use sign-magnitude
   std::string result;
   if (hex || octal || binary)
   {
     // bit-pattern representation
     // this is the binary representation optionally shown in octal or hex
     // first generate the binary by masking the bits
     for (unsigned j = i.bits(); j--; )
       result += (i.bit(j) ? '1' : '0');
     // the result is now the full width of the type - e.g. int will give a 32-bit result
     // now interpret this as either binary, octal or hex and add the prefix
     if (binary)
     {
       // the result is already binary - but the width may be wrong
       // if this is still smaller than the width field, sign extend
       // otherwise trim down to either the width or the smallest string that preserves the value
       while (result.size() < width)
         result.insert((std::string::size_type)0, 1, result[0]);
       while (result.size() > width)
       {
         // do not trim to less than 1 bit (sign only)
         if (result.size() <= 1) break;
         // only trim if it doesn't change the sign and therefore the value
         if (result[0] != result[1]) break;
         result.erase(0,1);
       }
       // add the prefix
       result.insert((std::string::size_type)0, "0b");
     }
     else if (octal)
     {
       // the result is currently binary - but before converting get the width right
       // the width is expressed in octal digits so make the binary 3 times this
       // if this is still smaller than the width field, sign extend
       // otherwise trim down to either the width or the smallest string that preserves the value
       // also ensure that the binary is a multiple of 3 bits to make the conversion to octal easier
       while (result.size() < 3*width)
         result.insert((std::string::size_type)0, 1, result[0]);
       while (result.size() > 3*width)
       {
         // do not trim to less than 2 bits (sign plus 1-bit magnitude)
         if (result.size() <= 2) break;
         // only trim if it doesn't change the sign and therefore the value
         if (result[0] != result[1]) break;
         result.erase(0,1);
       }
       while (result.size() % 3 != 0)
         result.insert((std::string::size_type)0, 1, result[0]);
       // now convert to octal
       std::string octal_result;
       for (unsigned i = 0; i < result.size()/3; i++)
       {
         std::string slice = result.substr(i*3, 3);
         unsigned value = to_uint(slice, 2);
         octal_result += to_char[value];
       }
       result = octal_result;
       // add the prefix
       result.insert((std::string::size_type)0, "0");
     }
     else
     {
       // similar to octal
       while (result.size() < 4*width)
         result.insert((std::string::size_type)0, 1, result[0]);
       while (result.size() > 4*width)
       {
         // do not trim to less than 2 bits (sign plus 1-bit magnitude)
         if (result.size() <= 2) break;
         // only trim if it doesn't change the sign and therefore the value
         if (result[0] != result[1]) break;
         result.erase(0,1);
       }
       while (result.size() % 4 != 0)
         result.insert((std::string::size_type)0, 1, result[0]);
       // now convert to hex
       std::string hex_result;
       for (unsigned i = 0; i < result.size()/4; i++)
       {
         std::string slice = result.substr(i*4, 4);
         unsigned value = to_uint(slice, 2);
         hex_result += to_char[value];
       }
       result = hex_result;
       // add the prefix
       result.insert((std::string::size_type)0, "0x");
     }
   }
   else
   {
     // convert to sign-magnitude
     // the representation is:
     // [radix#][sign]magnitude
     bool negative = local_i.negative();
     local_i.abs();
     // create a representation of the magnitude by successive division
     do
     {
       std::pair<inf,inf> divided = divide(local_i, t_radix);
       unsigned remainder = divided.second.to_unsigned();
       DEBUG_ASSERT(remainder < radix);
       char digit = to_char[remainder];
       result.insert((std::string::size_type)0, 1, digit);
       local_i = divided.first;
     }
     while(!local_i.zero() || result.size() < width);
     // add the prefixes
     // add a sign only for negative values
     if (negative)
       result.insert((std::string::size_type)0, 1, '-');
     // then prefix everything with the radix if the hashed representation was requested
     if (hashed)
       result.insert((std::string::size_type)0, to_string(radix) + "#");
   }
   return result;
 }
Member Data Documentation
std::string inf::m_data private
Definition at line 206 of file inf.hpp.
Referenced by image_debug(), indexable_bits(), inf(), invert(), operator&=(), operator+=(), operator<(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), reduce(), resize(), slice(), to_int(), to_long(), to_short(), to_ulong(), to_unsigned(), to_ushort(), and zero().
The documentation for this class was generated from the following files:
include/stlplus/inf.hpp
include/stlplus/inf.cpp