Visible: rcChainCode Class Reference
rcChainCode Class Reference
#include <src/analysis/code/rc_chaincode.h>
Public Types
enum { eDefaultChainCapacity = 512 }
enum { eFatScale = 4 }
enum { eFatMargin = 2 }
Public Member Functions
rcChainCode ()
~rcChainCode ()
void add (uint8 code)
rcChainCode * postProcess ()
void printSelf () const
void segments (const rc2Fvector &startPoint, rcVisualSegmentCollection &segments) const
pt2 getDirectionOffset (uint8 code) const
rc2Fvector getDirectionOffsetHires (uint8 code) const
float perimeterLength () const
Private Member Functions
char getDirectionChar (uint8 code) const
Private Attributes
uint8 * mCode
int mLength
int mCapacity
uint32 mDiagonalEdges
uint32 mStraightEdges
Detailed Description
Definition at line 11 of file rc_chaincode.h.
Member Enumeration Documentation
anonymous enum
Enumerator
eDefaultChainCapacity
Definition at line 14 of file rc_chaincode.h.
 { eDefaultChainCapacity = 512 }; // Chain array default capacity
anonymous enum
Enumerator
eFatScale
Definition at line 15 of file rc_chaincode.h.
 { eFatScale = 4 };               // Scale of fat pixel array
anonymous enum
Enumerator
eFatMargin
Definition at line 16 of file rc_chaincode.h.
 { eFatMargin = 2 };              // Number of margin pixels on all sides
Constructor & Destructor Documentation
rcChainCode::rcChainCode ()
Definition at line 88 of file rc_chaincode.cpp.
References mCapacity, mCode, NULL, and rmAssert.
Referenced by postProcess().
                          :
         mLength( 0 ),
         mCapacity( eDefaultChainCapacity ),
         mDiagonalEdges( 0 ),
         mStraightEdges( 0 )
 {
     mCode = (uint8*) malloc( mCapacity * sizeof(uint8) );
     rmAssert( mCode != NULL );
}
rcChainCode::~rcChainCode ()
Definition at line 104 of file rc_chaincode.cpp.
References mCode.
 {
     if ( mCode )
         free( mCode );
 }
Member Function Documentation
void rcChainCode::add (uint8 code)
Definition at line 120 of file rc_chaincode.cpp.
References mCapacity, mCode, mDiagonalEdges, mLength, mStraightEdges, rmDiagonalDirection, and sDiagonalComponents.
Referenced by postProcess().
 {
     if ( mLength >= mCapacity-3 ) {
         mCapacity *= 2;
         mCode = (uint8*) realloc( mCode, mCapacity );
     }
     if ( rmDiagonalDirection( code ) ) {
         ++mDiagonalEdges;
 #ifdef NO_DIAGONALS
         // Convert diagonal direction to horz and vert
         uint8 d1 = sDiagonalComponents[code-4][0];
         uint8 d2 = sDiagonalComponents[code-4][1];
         mCode[mLength++] = d1;
         mCode[mLength++] = d2;
 #endif
     } else {
         ++mStraightEdges;
         mCode[mLength] = code;
         ++mLength;
     }
 }
char rcChainCode::getDirectionChar (uint8 code) const private
Definition at line 263 of file rc_chaincode.cpp.
References rmAssertDebug, and sDirectionChar.
Referenced by printSelf().
 {
     rmAssertDebug( code < 8 );
     return sDirectionChar[code];
 }
pt2 rcChainCode::getDirectionOffset (uint8 code) const
Definition at line 190 of file rc_chaincode.cpp.
References rmAssertDebug.
 {
     rmAssertDebug( code < 8 );
     return sContourScaledOffset[code];
 }
rc2Fvector rcChainCode::getDirectionOffsetHires (uint8 code) const
Definition at line 197 of file rc_chaincode.cpp.
References rmAssertDebug.
Referenced by segments().
 {
     rmAssertDebug( code < 8 );
     return sContourOffset[code];
 }
float rcChainCode::perimeterLength () const
Definition at line 255 of file rc_chaincode.cpp.
References cSquare2, mDiagonalEdges, and mStraightEdges.
 {
     return mStraightEdges + mDiagonalEdges * cSquare2;
 }
rcChainCode * rcChainCode::postProcess ()
Definition at line 156 of file rc_chaincode.cpp.
References add(), eFatScale, mCode, mLength, and rcChainCode().
 {
     int    i = 0, j;
     int    trueLength = mLength;
     rcChainCode * filtCode = new rcChainCode();
     while ( i < trueLength ){
         if ( i+eFatScale-1 < trueLength ){
             for ( j=0; j<eFatScale-1; ++j )
                 if ( mCode[i+j] != mCode[i+j+1] )
                     break;
             if ( j == eFatScale-1 ){
                 filtCode->add( mCode[i] );
                 i += eFatScale;
                 continue;
             }
         }
         if ( i+eFatScale-2 < trueLength ){
             for ( j=0; j < eFatScale-2; ++j )
                 if ( mCode[i+j] != mCode[i+j+1] )
                     break;
             if ( j == eFatScale-2 ){
                 i += eFatScale-1;
                 continue;
             }
         }
         filtCode->add( mCode[i] );
         ++i;
     }
     return filtCode;
 }
void rcChainCode::printSelf () const
Definition at line 209 of file rc_chaincode.cpp.
References getDirectionChar(), mCode, and mLength.
 {
     for ( int i = 0; i < mLength; ++i )
         fprintf( stderr, "%c", getDirectionChar(mCode[i]) );
     fprintf( stderr, "\n" );
 }
void rcChainCode::segments (const rc2Fvector & startPoint, rcVisualSegmentCollection & segments) const
Definition at line 217 of file rc_chaincode.cpp.
References eFatMargin, eFatScale, getDirectionOffsetHires(), mCode, and mLength.
 {
     if ( mCode && mLength ) {
         // Compensate for margin pixels
         rc2Fvector marginOffset( -eFatMargin/(float)eFatScale, -eFatMargin/(float)eFatScale );
         // Add 1/8 pixel offset
         marginOffset += rc2Fvector( 1/(float)(eFatScale*2), 1/(float)(eFatScale*2) );
         rc2Fvector cur = startPoint + marginOffset;
         rc2Fvector prev = cur;
         uint8 prevCode = mCode[0];
         uint8 novelPoints = 1;
         for ( int i = 0; i < mLength; ++i ) {
             const uint8 c = mCode[i];
             // Keep accumulating until direction changes
             if ( prevCode != c ) {
                 ++novelPoints;
                 // Gather two novel points before producing a segment
                 // because line strips in a collection are connected
                 // together automatically.
                 if ( novelPoints == 2 ) {
                     segments.push_back( rcVisualLineStrip( prev, cur ) );
                     novelPoints = 0;
                 }
                 prev = cur;
             }
             // Accumulate direction offset
             cur +=  getDirectionOffsetHires( c );
             prevCode = c;
         }
         // Add final segment
         segments.push_back( rcVisualLineStrip( prev, cur ) );
     }
 }
Member Data Documentation
int rcChainCode::mCapacity private
Definition at line 44 of file rc_chaincode.h.
Referenced by add(), and rcChainCode().
uint8* rcChainCode::mCode private
Definition at line 42 of file rc_chaincode.h.
Referenced by add(), postProcess(), printSelf(), rcChainCode(), segments(), and ~rcChainCode().
uint32 rcChainCode::mDiagonalEdges private
Definition at line 45 of file rc_chaincode.h.
Referenced by add(), and perimeterLength().
int rcChainCode::mLength private
Definition at line 43 of file rc_chaincode.h.
Referenced by add(), postProcess(), printSelf(), and segments().
uint32 rcChainCode::mStraightEdges private
Definition at line 46 of file rc_chaincode.h.
Referenced by add(), and perimeterLength().
The documentation for this class was generated from the following files:
src/analysis/code/rc_chaincode.h
src/analysis/code/rc_chaincode.cpp