Visible: lm_dependencies Class Reference
lm_dependencies Class Reference
#include <include/stlplus/library_manager.hpp>
Public Member Functions
lm_dependencies (void)
~lm_dependencies (void)
void set_source_file (const lm_file_dependency &)
bool source_file_present (void) const
const lm_file_dependency & source_file (void) const
unsigned file_add (const lm_file_dependency &dependency)
unsigned file_size (void) const
const lm_file_dependency & file_dependency (unsigned) const
void file_erase (unsigned)
unsigned unit_add (const lm_unit_dependency &dependency)
unsigned unit_size (void) const
const lm_unit_dependency & unit_dependency (unsigned) const
void unit_erase (unsigned)
void clear (void)
bool empty (void) const
Private Attributes
smart_ptr< lm_file_dependency > m_source
std::vector< lm_file_dependency > m_files
std::vector< lm_unit_dependency > m_units
Friends
void dump (dump_context &context, const lm_dependencies &) throw (persistent_dump_failed)
void restore (restore_context &context, lm_dependencies &) throw (persistent_restore_failed)
otext & print (otext &, const lm_dependencies &, unsigned indent=0)
otext & operator<< (otext &, const lm_dependencies &)
Detailed Description
Definition at line 165 of file library_manager.hpp.
Constructor & Destructor Documentation
lm_dependencies::lm_dependencies (void)
Definition at line 420 of file library_manager.cpp.
 {
 }
lm_dependencies::~lm_dependencies (void)
Definition at line 424 of file library_manager.cpp.
 {
 }
Member Function Documentation
void lm_dependencies::clear (void)
Definition at line 485 of file library_manager.cpp.
References m_files, m_source, and m_units.
Referenced by lm_unit::clear_dependencies().
 {
   m_source = smart_ptr<lm_file_dependency>();
   m_files.clear();
   m_units.clear();
 }
bool lm_dependencies::empty (void) const
Definition at line 492 of file library_manager.cpp.
References m_files, m_source, m_units, and smart_ptr< T >::null().
Referenced by lm_unit::empty_dependencies(), out_of_date_chk(), lm_library::pretty_print(), and library_manager::up_to_date().
 {
   return m_source.null() && m_files.empty() && m_units.empty();
 }
unsigned lm_dependencies::file_add (const lm_file_dependency & dependency)
Definition at line 443 of file library_manager.cpp.
References m_files.
Referenced by lm_unit::file_add().
 {
   m_files.push_back(dependency);
   return m_files.size()-1;
 }
const lm_file_dependency & lm_dependencies::file_dependency (unsigned i) const
Definition at line 454 of file library_manager.cpp.
References m_files.
Referenced by lm_unit::file_dependency(), lm_library::pretty_print(), and lm_unit::print_long().
 {
   return m_files[i];
 }
void lm_dependencies::file_erase (unsigned i)
Definition at line 459 of file library_manager.cpp.
References m_files.
Referenced by lm_unit::file_erase().
 {
   m_files.erase(m_files.begin()+i);
 }
unsigned lm_dependencies::file_size (void) const
Definition at line 449 of file library_manager.cpp.
References m_files.
Referenced by lm_unit::file_size(), lm_library::pretty_print(), and lm_unit::print_long().
 {
   return m_files.size();
 }
void lm_dependencies::set_source_file (const lm_file_dependency & source)
Definition at line 428 of file library_manager.cpp.
References m_source.
Referenced by lm_unit::set_source_file().
 {
   m_source = source;
 }
const lm_file_dependency & lm_dependencies::source_file (void) const
Definition at line 438 of file library_manager.cpp.
References m_source.
Referenced by lm_library::pretty_print(), lm_unit::print_long(), and lm_unit::source_file().
 {
   return *m_source;
 }
bool lm_dependencies::source_file_present (void) const
Definition at line 433 of file library_manager.cpp.
References m_source, and smart_ptr< T >::present().
Referenced by lm_library::pretty_print(), lm_unit::print_long(), and lm_unit::source_file_present().
 {
   return m_source.present();
 }
unsigned lm_dependencies::unit_add (const lm_unit_dependency & dependency)
Definition at line 464 of file library_manager.cpp.
References m_units.
Referenced by out_of_date_chk(), and lm_unit::unit_add().
 {
   m_units.push_back(dependency);
   return m_units.size()-1;
 }
const lm_unit_dependency & lm_dependencies::unit_dependency (unsigned i) const
Definition at line 475 of file library_manager.cpp.
References m_units.
Referenced by lm_library::pretty_print(), lm_unit::print_long(), and lm_unit::unit_dependency().
 {
   return m_units[i];
 }
void lm_dependencies::unit_erase (unsigned i)
Definition at line 480 of file library_manager.cpp.
References m_units.
Referenced by lm_unit::unit_erase().
 {
   m_units.erase(m_units.begin()+i);
 }
unsigned lm_dependencies::unit_size (void) const
Definition at line 470 of file library_manager.cpp.
References m_units.
Referenced by lm_library::pretty_print(), lm_unit::print_long(), and lm_unit::unit_size().
 {
   return m_units.size();
 }
Friends And Related Function Documentation
void dump (dump_context & context, const lm_dependencies &) throw (persistent_dump_failed) friend
Definition at line 497 of file library_manager.cpp.
 {
   dump_smart_ptr(context, dependencies.m_source);
   dump_vector(context, dependencies.m_files);
   dump_vector(context, dependencies.m_units);
 }
otext& operator<< (otext & , const lm_dependencies &) friend
Definition at line 519 of file library_manager.cpp.
 {
   return print(str, dependencies, 0);
 }
otext& print (otext & , const lm_dependencies & , unsigned indent = 0) friend
Definition at line 511 of file library_manager.cpp.
 {
   print_indent(str, indent); str << "source file: "; print_smart_ptr(str, dependencies.m_source, "<null>"); str << endl;
   print_vector(str, dependencies.m_files, indent);
   print_vector(str, dependencies.m_units, indent);
   return str;
 }
void restore (restore_context & context, lm_dependencies &) throw (persistent_restore_failed) friend
Definition at line 504 of file library_manager.cpp.
 {
   restore_smart_ptr(context, dependencies.m_source);
   restore_vector(context, dependencies.m_files);
   restore_vector(context, dependencies.m_units);
 }
Member Data Documentation
std::vector<lm_file_dependency> lm_dependencies::m_files private
Definition at line 201 of file library_manager.hpp.
Referenced by clear(), empty(), file_add(), file_dependency(), file_erase(), file_size(), and print().
smart_ptr<lm_file_dependency> lm_dependencies::m_source private
Definition at line 200 of file library_manager.hpp.
Referenced by clear(), empty(), print(), set_source_file(), source_file(), and source_file_present().
std::vector<lm_unit_dependency> lm_dependencies::m_units private
Definition at line 202 of file library_manager.hpp.
Referenced by clear(), empty(), print(), unit_add(), unit_dependency(), unit_erase(), and unit_size().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp