Visible: rcBasicPixelMap< T > Class Template Reference
rcBasicPixelMap< T > Class Template Reference
#include <include/analysis/rc_rowfunc.h>
Public Member Functions
rcBasicPixelMap (const rcWindow &srcA, const rcWindow &dst, const vector< T > &lut)
virtual void prolog ()
virtual void rowFunc ()
virtual void areaFunc ()
virtual ~rcBasicPixelMap ()
template<>
void rowFunc ()
template<>
void rowFunc ()
Public Member Functions inherited from rcRowFuncOneSourceOneDestination< T >
rcRowFuncOneSourceOneDestination ()
virtual ~rcRowFuncOneSourceOneDestination ()
Private Attributes
const T * mLut
rcUIPair mRUP
Additional Inherited Members
Protected Member Functions inherited from rcRowFuncOneSourceOneDestination< T >
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
Static Protected Member Functions inherited from rcRowFuncOneSourceOneDestination< T >
static bool checkAssigned (const rcWindow &, const rcWindow &)
Protected Attributes inherited from rcRowFuncOneSourceOneDestination< T >
const T * mFirst
T * mSecond
uint32 mWidth
uint32 mHeight
Detailed Description
template<class T>
class rcBasicPixelMap< T >
Definition at line 98 of file rc_rowfunc.h.
Constructor & Destructor Documentation
template<class T > rcBasicPixelMap< T >::rcBasicPixelMap (const rcWindow & srcA, const rcWindow & dst, const vector< T > & lut)
Definition at line 497 of file rc_rowfunc.h.
References rcBasicPixelMap< T >::mLut, rmAssertDebug, rcWindow::rowPointer(), rcWindow::size(), and rcWindow::width().
                                                                                                :
 mRUP( srcA.rowUpdate () / sizeof (T), srcB.rowUpdate () / sizeof (T) )
 {
   rcRowFuncOneSourceOneDestination <T>::checkAssigned (srcB, srcA);
   rmAssertDebug (srcA.size() == srcB.size());
   rcRowFuncOneSourceOneDestination<T>::mWidth = srcA.width();
   rcRowFuncOneSourceOneDestination<T>::mHeight = srcB.height();
   rcRowFuncOneSourceOneDestination<T>::mFirst = (T *) srcA.rowPointer(0);
   rcRowFuncOneSourceOneDestination<T>::mSecond = (T *) srcB.rowPointer(0);
   mLut = (T *) (& lut[0]);
}
template<class T > rcBasicPixelMap< T >::~rcBasicPixelMap< T > () virtual
Definition at line 519 of file rc_rowfunc.h.
 {}
Member Function Documentation
template<class T > void rcBasicPixelMap< T >::areaFunc () virtual
Implements rcRowFuncOneSourceOneDestination< T >.
Definition at line 512 of file rc_rowfunc.h.
Referenced by rfPixel16Map(), and rfPixel8Map().
 {
     uint32 height = rcRowFuncOneSourceOneDestination<T>::mHeight;
     do { rowFunc(); } while (--height);
 }
template<class T > void rcBasicPixelMap< T >::prolog () virtual
Implements rcRowFuncOneSourceOneDestination< T >.
Definition at line 521 of file rc_rowfunc.h.
 {}
template<class T> virtual void rcBasicPixelMap< T >::rowFunc () virtual
Implements rcRowFuncOneSourceOneDestination< T >.
template<> void rcBasicPixelMap< uint8 >::rowFunc () inline virtual
Implements rcRowFuncOneSourceOneDestination< T >.
Definition at line 526 of file rc_rowfuncs.cpp.
 {
     const uint8 *pFirst (mFirst);
     uint8 *pSecond (mSecond);
     for (const uint8 *pEnd = mFirst + mWidth; pFirst < pEnd; )
     {
         *pSecond++ = mLut[*pFirst++];
     }
     mFirst += mRUP.x();
     mSecond += mRUP.y();
 }
template<> void rcBasicPixelMap< uint16 >::rowFunc () inline virtual
Implements rcRowFuncOneSourceOneDestination< T >.
Definition at line 539 of file rc_rowfuncs.cpp.
 {
     const uint16 *pFirst (mFirst);
     uint16 *pSecond (mSecond);
     for (const uint16 *pEnd = mFirst + mWidth; pFirst < pEnd; )
     {
         *pSecond++ = mLut[*pFirst++];
     }
     mFirst += mRUP.x();
     mSecond += mRUP.y();
 }
Member Data Documentation
template<class T> const T* rcBasicPixelMap< T >::mLut private
Definition at line 110 of file rc_rowfunc.h.
Referenced by rcBasicPixelMap< T >::rcBasicPixelMap().
template<class T> rcUIPair rcBasicPixelMap< T >::mRUP private
Definition at line 111 of file rc_rowfunc.h.
The documentation for this class was generated from the following file:
include/analysis/rc_rowfunc.h