Visible: rcImageGrabber Class Reference
rcImageGrabber Class Reference
#include <include/visual/rc_imagegrabber.h>
Public Member Functions
rcImageGrabber (const vector< std::string > &fileNames, rcCarbonLock *lock, double frameInterval=0.0, bool nameSort=true)
virtual ~rcImageGrabber ()
virtual bool start ()
virtual bool stop ()
virtual int32 frameCount ()
virtual int32 cacheSize ()
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)
virtual const std::string getInputSourceName ()
Public Member Functions inherited from rcFileGrabber
rcFileGrabber (rcCarbonLock *lock)
virtual ~rcFileGrabber ()
virtual rcFrameGrabberError getLastError () const
virtual bool isValid () const
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
Private Attributes
vector< std::string > mFileNames
vector< FSSpec * > mFileHandles
GraphicsImportComponent mImporter
uint32 mCurrentIndex
double mFrameInterval
rcTimestamp mCurrentTimeStamp
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Protected Member Functions inherited from rcFileGrabber
void setLastError (rcFrameGrabberError)
void lock ()
void unlock ()
Detailed Description
Definition at line 24 of file rc_imagegrabber.h.
Constructor & Destructor Documentation
rcImageGrabber::rcImageGrabber (const vector< std::string > & fileNames, rcCarbonLock * lock, double frameInterval = 0.0, bool nameSort = true)
Definition at line 159 of file rc_imagegrabber.cpp.
References eFrameErrorFileInit, rcFileGrabber::lock(), mFileHandles, mFileNames, rfImageFrameNum(), rfImageNameSort(), rfMakeFSSpecFromPosixPath(), rmAssert, rcFileGrabber::setLastError(), rcFileGrabber::unlock(), and ValidFSSpec().
                                                                                                                              :
         rcFileGrabber( cLock ),
         mFileNames( fileNames ),
         mCurrentIndex( 0 ),
         mFrameInterval( frameInterval ), mCurrentTimeStamp( frameInterval )
 {
     lock();
     rmAssert( mFileHandles.empty() );
     // Sort names just in case
     if (nameSort)
       rfImageNameSort( mFileNames );
 #ifdef DEBUG
     // Paranoia, verify sort order
     for (vector<std::string>::iterator name = mFileNames.begin(); name < mFileNames.end()-1; name++ ) {
         char* str1 = (char*)name->c_str();
         char* str2 = (char*)(name+1)->c_str();
         int num1 = rfImageFrameNum( str1 );
         int num2 = rfImageFrameNum( str2 );
         rmAssert( num1 <= num2 );
     }
 #endif
     for( vector<std::string>::iterator file = mFileNames.begin(); file < mFileNames.end(); ++file )
         {
             bool isdir = false;
             FSSpec spec = rfMakeFSSpecFromPosixPath( file->c_str(), isdir);
         if ( ValidFSSpec( &spec ) == noErr )
         {
             FSSpec* newSpec = new FSSpec( spec );
             mFileHandles.push_back( newSpec );
         }
     }
     if ( mFileHandles.empty() )
         setLastError( eFrameErrorFileInit );
     unlock();
}
rcImageGrabber::~rcImageGrabber () virtual
Definition at line 204 of file rc_imagegrabber.cpp.
References mFileHandles.
 {
     // Delete specs
     for (vector<FSSpec*>::iterator f = mFileHandles.begin(); f != mFileHandles.end(); f++)
         delete *f;
 }
Member Function Documentation
virtual int32 rcImageGrabber::cacheSize () inline virtual
Implements rcFrameGrabber.
Definition at line 48 of file rc_imagegrabber.h.
 { return 0; }
int32 rcImageGrabber::frameCount () virtual
Implements rcFileGrabber.
Definition at line 233 of file rc_imagegrabber.cpp.
References mFileHandles.
 {
     if ( mFileHandles.size() > 0 )
         return mFileHandles.size();
     else
         return -1;
 }
const std::string rcImageGrabber::getInputSourceName () virtual
Implements rcFrameGrabber.
Definition at line 289 of file rc_imagegrabber.cpp.
References mCurrentIndex, and mFileNames.
Referenced by rcEngineImpl::loadImages().
 {
     if ( !mFileNames.empty() ) {
         if ( mCurrentIndex < mFileNames.size() )
             return mFileNames[mCurrentIndex];
         else
             return mFileNames[0];
     }
     // We don't even have a file...
     return "empty file";
 }
rcFrameGrabberStatus rcImageGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) virtual
Implements rcFileGrabber.
Definition at line 242 of file rc_imagegrabber.cpp.
References eFrameErrorFileRead, eFrameErrorNotImplemented, eFrameErrorOK, eFrameErrorUnknown, eFrameStatusEOF, eFrameStatusError, eFrameStatusOK, rcWindow::frameBuf(), rcFileGrabber::lock(), mCurrentIndex, mCurrentTimeStamp, mFileHandles, mFrameInterval, mImporter, NULL, rfImageFileToRcWindow(), rcFileGrabber::setLastError(), rcFrame::setTimestamp(), and rcFileGrabber::unlock().
Referenced by main().
 {
     lock();
     setLastError( eFrameErrorUnknown );
     ptr = NULL;
     rcFrameGrabberStatus ret = eFrameStatusError;
     if ( isBlocking ) {
         if ( mCurrentIndex < mFileHandles.size() ) {
             rcWindow image;
             FSSpec *spec = mFileHandles[mCurrentIndex];
             ++mCurrentIndex;
             // Get the frame and convert it from 32 to 8 bit if possible
             OSErr status = rfImageFileToRcWindow( spec, image, mImporter );
             if ( status == noErr ) {
                 ptr = image.frameBuf();
                 if ( mFrameInterval > 0.0 ) {
                     // Force a fixed frame interval
                     image.frameBuf()->setTimestamp( mCurrentTimeStamp );
                     mCurrentTimeStamp += mFrameInterval;
                 }
                 ret = eFrameStatusOK;
                 setLastError( eFrameErrorOK );
             } else {
                 ret = eFrameStatusError;
                 // TODO: analyze OSErr and map it to proper eFrameError
                 setLastError( eFrameErrorFileRead );
             }
         } else {
             ret = eFrameStatusEOF;
             setLastError( eFrameErrorOK );
         }
     } else {
          // Non-blocking operation not implemented yet
         setLastError( eFrameErrorNotImplemented );
         ret = eFrameStatusError;
     }
     unlock();
     return ret;
 }
bool rcImageGrabber::start (void) virtual
Implements rcFileGrabber.
Definition at line 212 of file rc_imagegrabber.cpp.
References eFrameErrorOK, and rcFileGrabber::getLastError().
 {
     if ( getLastError() == eFrameErrorOK )
         return true;
     else
         return false;
 }
bool rcImageGrabber::stop (void) virtual
Implements rcFileGrabber.
Definition at line 221 of file rc_imagegrabber.cpp.
References rcFileGrabber::lock(), mImporter, and rcFileGrabber::unlock().
 {
     lock();
     CloseComponent( mImporter );
     unlock();
     return true;
 }
Member Data Documentation
uint32 rcImageGrabber::mCurrentIndex private
Definition at line 60 of file rc_imagegrabber.h.
Referenced by getInputSourceName(), and getNextFrame().
rcTimestamp rcImageGrabber::mCurrentTimeStamp private
Definition at line 62 of file rc_imagegrabber.h.
Referenced by getNextFrame().
vector<FSSpec*> rcImageGrabber::mFileHandles private
Definition at line 58 of file rc_imagegrabber.h.
Referenced by frameCount(), getNextFrame(), rcImageGrabber(), and ~rcImageGrabber().
vector<std::string> rcImageGrabber::mFileNames private
Definition at line 57 of file rc_imagegrabber.h.
Referenced by getInputSourceName(), and rcImageGrabber().
double rcImageGrabber::mFrameInterval private
Definition at line 61 of file rc_imagegrabber.h.
Referenced by getNextFrame().
GraphicsImportComponent rcImageGrabber::mImporter private
Definition at line 59 of file rc_imagegrabber.h.
Referenced by getNextFrame(), and stop().
The documentation for this class was generated from the following files:
include/visual/rc_imagegrabber.h
src/visual/code/rc_imagegrabber.cpp