Visible: rcConversionProgress Class Reference
rcConversionProgress Class Reference
Public Member Functions
rcConversionProgress (const std::string &message, const rcTimestamp &updateInterval)
virtual ~rcConversionProgress ()
virtual bool progress (double percentComplete)
virtual bool progress (uint32 percentComplete)
Public Member Functions inherited from rcProgressIndicator
virtual ~rcProgressIndicator ()
Private Attributes
const std::string mFormatMessage
char mMessageBuf [1024]
rcTimestamp mUpdateInterval
rcTimestamp mLastUpdate
Detailed Description
Definition at line 51 of file bcnvrt_main.cpp.
Constructor & Destructor Documentation
rcConversionProgress::rcConversionProgress (const std::string & message, const rcTimestamp & updateInterval) inline
Definition at line 54 of file bcnvrt_main.cpp.
                                                                                  :
     mFormatMessage( message ),
     mUpdateInterval( updateInterval ),
mLastUpdate(cZeroTime) { }
virtual rcConversionProgress::~rcConversionProgress () inline virtual
Definition at line 60 of file bcnvrt_main.cpp.
 { };
Member Function Documentation
virtual bool rcConversionProgress::progress (double percentComplete) inline virtual
Implements rcProgressIndicator.
Definition at line 63 of file bcnvrt_main.cpp.
References cZeroTime, endl(), mFormatMessage, mLastUpdate, mMessageBuf, mUpdateInterval, rcTimestamp::now(), and rmDim.
Referenced by progress(), rfCompareMovies(), and rfCompareReifyMovies().
{
     const rcTimestamp now = rcTimestamp::now();
     // If interval is zero, update with every call
     // Otherwise update after mUpdateInterval seconds have passed since last update
     if ( mUpdateInterval == cZeroTime ||
                 ( (now - mLastUpdate) > mUpdateInterval ) ) {
       mLastUpdate = now;
       snprintf( mMessageBuf, rmDim( mMessageBuf ), mFormatMessage.c_str(), percentComplete );
       // Display progress to stdout
       cout << mMessageBuf << endl;
     }
     return false;
   }
virtual bool rcConversionProgress::progress (uint32 percentComplete) inline virtual
Implements rcProgressIndicator.
Definition at line 77 of file bcnvrt_main.cpp.
References progress().
{
     return progress( double(percentComplete) );
   }
Member Data Documentation
const std::string rcConversionProgress::mFormatMessage private
Definition at line 82 of file bcnvrt_main.cpp.
Referenced by progress().
rcTimestamp rcConversionProgress::mLastUpdate private
Definition at line 85 of file bcnvrt_main.cpp.
Referenced by progress().
char rcConversionProgress::mMessageBuf[1024] private
Definition at line 83 of file bcnvrt_main.cpp.
Referenced by progress().
rcTimestamp rcConversionProgress::mUpdateInterval private
Definition at line 84 of file bcnvrt_main.cpp.
Referenced by progress().
The documentation for this class was generated from the following file:
src/support/bcnvrt_main.cpp