Visible: rc1Xform Class Reference
rc1Xform Class Reference
#include <include/util/rc_xforms.h>
Public Member Functions
rc1Xform ()
rc1Xform (double scale, double offset)
double scale () const
double offset () const
void scale (double scale)
void offset (double offset)
rc1Xform inverse () const
rc1Xform operator* (const rc1Xform &xform) const
rc1Xform compose (const rc1Xform &xform) const
double mapPoint (double pt) const
double operator* (double pt) const
double invMapPoint (double pt) const
double mapVector (double vect) const
double invMapVector (double vect) const
bool operator== (const rc1Xform &xform) const
bool operator!= (const rc1Xform &xform) const
bool isIdentity () const
bool isSingular () const
Static Public Attributes
static const rc1Xform I
Private Attributes
double mScale
double mOffset
Detailed Description
Definition at line 52 of file rc_xforms.h.
Constructor & Destructor Documentation
rc1Xform::rc1Xform () inline
Definition at line 56 of file rc_xforms.h.
Referenced by inverse(), and operator*().
 : mScale(1), mOffset(0) {}
rc1Xform::rc1Xform (double scale, double offset) inline
Definition at line 61 of file rc_xforms.h.
 : mScale(scale), mOffset(offset) {}
Member Function Documentation
rc1Xform rc1Xform::compose (const rc1Xform & xform) const inline
Definition at line 83 of file rc_xforms.h.
 { return (*this * xform); }
rc1Xform rc1Xform::inverse () const inline
Definition at line 70 of file rc_xforms.h.
References isSingular(), mOffset, mScale, and rc1Xform().
Referenced by invMapPoint().
   {
       if (isSingular()) throw general_exception ("xform is Singular");
       double inverseScale = 1/mScale;
       return rc1Xform(inverseScale, inverseScale * -mOffset);
   }
double rc1Xform::invMapPoint (double pt) const inline
Definition at line 97 of file rc_xforms.h.
References inverse().
 { return (inverse() * pt); }
double rc1Xform::invMapVector (double vect) const inline
Definition at line 110 of file rc_xforms.h.
References isSingular(), and mScale.
   {
       if (isSingular()) throw general_exception ("xform is Singular");
       return (vect / mScale);
   }
bool rc1Xform::isIdentity () const inline
Definition at line 129 of file rc_xforms.h.
References mOffset, and mScale.
Referenced by rcKinetoscope::clear().
 { return ((mScale == 1) && (mOffset == 0)); }
bool rc1Xform::isSingular () const inline
Definition at line 134 of file rc_xforms.h.
References mScale.
Referenced by inverse(), and invMapVector().
 {return mScale == 0;}
double rc1Xform::mapPoint (double pt) const inline
Definition at line 89 of file rc_xforms.h.
 { return (*this * pt); }
double rc1Xform::mapVector (double vect) const inline
Definition at line 106 of file rc_xforms.h.
References mScale.
Referenced by rcKinetoscope::currentTime(), rcKinetoscope::deltaTime(), and rcKinetoscope::elapsedTime().
 { return (mScale * vect); }
double rc1Xform::offset (void) const inline
Definition at line 66 of file rc_xforms.h.
References mOffset.
Referenced by rfRealEq().
 { return mOffset; }
void rc1Xform::offset (double offset) inline
Definition at line 68 of file rc_xforms.h.
References mOffset, and offset().
Referenced by offset().
 { mOffset = offset; }
bool rc1Xform::operator!= (const rc1Xform & xform) const inline
Definition at line 123 of file rc_xforms.h.
References mOffset, and mScale.
       { return ( (mScale != xform.mScale) || (mOffset != xform.mOffset) ); }
rc1Xform rc1Xform::operator* (const rc1Xform & xform) const inline
Definition at line 81 of file rc_xforms.h.
References mOffset, mScale, and rc1Xform().
   { return rc1Xform(mScale * xform.mScale, mScale * xform.mOffset + mOffset); }
double rc1Xform::operator* (double pt) const inline
Definition at line 90 of file rc_xforms.h.
References mOffset, and mScale.
 { return (mScale * pt) + mOffset; }
bool rc1Xform::operator== (const rc1Xform & xform) const inline
Definition at line 120 of file rc_xforms.h.
References mOffset, and mScale.
       { return ( (mScale == xform.mScale) && (mOffset == xform.mOffset) ); }
double rc1Xform::scale () const inline
Definition at line 65 of file rc_xforms.h.
References mScale.
Referenced by rfRealEq(), and rcKinetoscope::temporalScale().
 { return mScale; }
void rc1Xform::scale (double scale) inline
Definition at line 67 of file rc_xforms.h.
References mScale, and scale().
Referenced by scale().
 { mScale  = scale; }
Member Data Documentation
const rc1Xform rc1Xform::I static
Definition at line 127 of file rc_xforms.h.
double rc1Xform::mOffset private
Definition at line 142 of file rc_xforms.h.
Referenced by inverse(), isIdentity(), offset(), operator!=(), operator*(), and operator==().
double rc1Xform::mScale private
Definition at line 141 of file rc_xforms.h.
Referenced by inverse(), invMapVector(), isIdentity(), isSingular(), mapVector(), operator!=(), operator*(), operator==(), and scale().
The documentation for this class was generated from the following file:
include/util/rc_xforms.h