Visible: rcSimilarator Class Reference
rcSimilarator Class Reference
#include <include/analysis/rc_similarity.h>
Classes
class progressNotification
Public Types
enum rcMatrixGeneration { eExhaustive, eApproxNoMatrix, eApproximate }
enum rcEntropyDefinition { eACI, eVisualEntropy }
enum rcFilteringOp { eSavgol, eMovingAverage, eNone }
enum rcCorrelationDefinition {
eNorm, eRelative, eHintersect, eLowSpT,
eShading
}
Public Member Functions
rcSimilarator ()
virtual ~rcSimilarator ()
rcSimilarator (rcMatrixGeneration type, rcPixel depth, uint32 matrixSz, uint32 cacheSz, rcCorrelationDefinition cdl=eNorm, bool notify=false, rcProgressIndicator *guiUpdate=0, double tiny=1e-10)
rcSimilarator (uint32 matrixSz, bool notify, double tiny)
bool fill (vector< rcWindow > &firstImages)
bool fill (deque< rcWindow > &firstImages)
bool fill (vector< double > &firstData)
bool fill (deque< double > &firstData)
bool fill (const rcWindow &projective, bool isColumns=true)
bool update (rcWindow nextImage)
bool update (double &nextData)
rcIPair fillImageSize () const
void setMask (const rcWindow &mask)
void clearMask ()
bool longTermCache (bool)
bool longTermCache () const
const vector< float > & longTermEntropy () const
bool entropies (deque< double > &signal, rcEntropyDefinition d=eACI, rcFilteringOp f=eNone) const
bool sequentialCorrelations (deque< double > &slist) const
bool selfSimilarityMatrix (deque< deque< double > > &matrix) const
bool filter (vector< double > &)
double periodicity (const vector< double > &signal, const vector< double > &absc, rcDPair &freq)
void mu (vector< double > &src, vector< double > &dst)
bool aborted () const
uint32 matrixSz () const
rcMatrixGeneration matGenType () const
uint32 cacheSz () const
rcPixel depth () const
rcCorrelationDefinition corrDefinition () const
Private Member Functions
rcSimilarator (const rcSimilarator &rhs)
rcSimilarator & operator= (const rcSimilarator &rhs)
bool operator< (const rcSimilarator &rhs) const
bool operator== (const rcSimilarator &rhs) const
bool entropiesVisualEntropy (deque< double > &signal) const
template<class I , class T >
bool internalFill (I start, I end, deque< rcCorrelationWindow< T > > &tWin)
template<class T >
bool ssMatrixFill (deque< rcCorrelationWindow< T > > &tWin)
template<class T >
bool ssMatrixApproxFill (deque< rcCorrelationWindow< T > > &tWin)
template<class T >
bool ssListFill (deque< rcCorrelationWindow< T > > &tWin)
bool ssMatrixFill (deque< double > &data)
template<class T >
bool internalUpdate (rcWindow &nextImage, deque< rcCorrelationWindow< T > > &tWin)
bool internalUpdate (double &nextImage, deque< double > &tWin)
void shiftSList ()
void shiftSMatrix ()
template<class T >
bool ssMatrixUpdate (deque< rcCorrelationWindow< T > > &tWin)
template<class T >
bool ssMatrixApproxUpdate (deque< rcCorrelationWindow< T > > &tWin)
template<class T >
bool ssListUpdate (deque< rcCorrelationWindow< T > > &tWin)
bool ssMatrixUpdate (deque< double > &data)
template<class T >
double relativeCorrelate (rcCorrelationWindow< T > &i, rcCorrelationWindow< T > &m) const
template<class T >
double correlate (rcCorrelationWindow< T > &i, rcCorrelationWindow< T > &m) const
template<class T >
float histogramIntersection (rcCorrelationWindow< T > &i, rcCorrelationWindow< T > &m) const
double distance (double &i, double &m) const
bool genMatrixEntropy (uint32 tWinSz)
bool genListEntropy (uint32 tWinSz)
template<class T >
bool filterOp (vector< T > &)
template<class T >
double genPeriodicity (const vector< T > &signal, const vector< T > &absc, rcDPair &freq)
void unity ()
double shannon (double r) const
Private Attributes
bool _maskValid
rcWindow _mask
int32 _maskN
const rcMatrixGeneration _type
const rcPixel _depth
const uint32 _matrixSz
const uint32 _cacheSz
const rcCorrelationDefinition _cdl
const bool _notify
bool _finished
rcProgressIndicator *const _guiUpdate
const double _tiny
double _log2MSz
rsCorrParams _corrParams
deque< rcCorrelationWindow
< uint8 > > _tw8
deque< rcCorrelationWindow
< uint16 > > _tw16
deque< rcCorrelationWindow
< uint32 > > _tw32
deque< double > _seqD
deque< deque< double > > _SMatrix
deque< double > _SList
deque< double > _entropies
deque< double > _sums
vector< double > _kernel
bool _ltOn
vector< float > _ltEntropies
Friends
ostream & operator<< (ostream &, const rcSimilarator &)
Detailed Description
Definition at line 43 of file rc_similarity.h.
Member Enumeration Documentation
enum rcSimilarator::rcCorrelationDefinition
Enumerator
eNorm
eRelative
eHintersect
eLowSpT
eShading
Definition at line 93 of file rc_similarity.h.
enum rcSimilarator::rcEntropyDefinition
Enumerator
eACI
eVisualEntropy
Definition at line 75 of file rc_similarity.h.
enum rcSimilarator::rcFilteringOp
Enumerator
eSavgol
eMovingAverage
eNone
Definition at line 80 of file rc_similarity.h.
enum rcSimilarator::rcMatrixGeneration
Enumerator
eExhaustive
eApproxNoMatrix
eApproximate
Definition at line 69 of file rc_similarity.h.
Constructor & Destructor Documentation
rcSimilarator::rcSimilarator ()
Definition at line 19 of file rc_similarity.cpp.
                              : _matrixSz (0), _maskValid(false), _cacheSz (0),
 _type(eExhaustive),_depth (rcPixel8),  _cdl (eNorm),  _notify(NULL), _finished(true),_guiUpdate(NULL), _tiny(1e-10)
 {
 }
rcSimilarator::~rcSimilarator () virtual
Definition at line 24 of file rc_similarity.cpp.
 {}
rcSimilarator::rcSimilarator (rcMatrixGeneration type, rcPixel depth, uint32 matrixSz, uint32 cacheSz, rcCorrelationDefinition cdl = eNorm, bool notify = false, rcProgressIndicator * guiUpdate = 0, double tiny = 1e-10)
Definition at line 26 of file rc_similarity.cpp.
References _depth, _log2MSz, _ltOn, _matrixSz, rcPixel16, rcPixel32, rcPixel8, and rmAssert.
   : _maskValid(false), _type(type), _depth(depth), _matrixSz(matrixSz),
     _cacheSz(cacheSz),  _cdl (cdl),
     _notify(notify), _finished(true),
     _guiUpdate(guiUpdate), _tiny(tiny)
 {
   switch (_depth) {
   case rcPixel8:
   case rcPixel16:
   case rcPixel32:
     break;
   default:
     rmAssert(0);
     break;
   }
   _log2MSz = log2(_matrixSz);
   _ltOn = false;
 }
rcSimilarator::rcSimilarator (uint32 matrixSz, bool notify, double tiny)
Definition at line 54 of file rc_similarity.cpp.
References _log2MSz, and _matrixSz.
   : _maskValid(false), _type(eExhaustive), _matrixSz(matrixSz), _depth (rcPixel8),
     _notify(notify), _finished(true),_tiny(tiny), _cacheSz (matrixSz), _cdl (eNorm), _guiUpdate (NULL)
 {
   _log2MSz = log2(_matrixSz);
 }
rcSimilarator::rcSimilarator (const rcSimilarator & rhs) private
Member Function Documentation
bool rcSimilarator::aborted () const inline
Definition at line 232 of file rc_similarity.h.
References _finished.
uint32 rcSimilarator::cacheSz () const inline
Definition at line 236 of file rc_similarity.h.
References _cacheSz.
Referenced by ssMatrixFill().
void rcSimilarator::clearMask ()
Definition at line 307 of file rc_similarity.cpp.
References _mask, _maskValid, _matrixSz, and rmAssert.
 {
   rmAssert (_matrixSz);
   _maskValid = false;
   _mask = rcWindow();
 }
rcCorrelationDefinition rcSimilarator::corrDefinition () const inline
Definition at line 238 of file rc_similarity.h.
References _cdl.
Referenced by correlate().
template<class T > double rcSimilarator::correlate (rcCorrelationWindow< T > & i, rcCorrelationWindow< T > & m) const private
Definition at line 748 of file rc_similarity.cpp.
References _corrParams, _mask, _maskN, _maskValid, _tiny, corrDefinition(), rcCorrelationWindow< T >::depth(), eHintersect, eLowSpT, eNorm, eRelative, eShading, rcCorrelationWindow< T >::height(), rcCorr::r(), rf1dSignalIntersection(), rfCorrelate(), rfCorrelateWindow(), rfGaussianConv(), rfSetWindowBorder(), rfSobelEdge(), rmAssert, rcCorrelationWindow< T >::width(), and rcCorrelationWindow< T >::window().
Referenced by ssListFill(), ssMatrixFill(), and ssMatrixUpdate().
 {
   rcCorr res;
   if (corrDefinition () == rcSimilarator::eHintersect)
     {
       rcHistoStats ih (i.window ());
       rcHistoStats mh (m.window());
       double ir = rf1dSignalIntersection (ih.histogram().begin(), ih.histogram().end(),
                       mh.histogram().begin(), mh.histogram().end());
       return ir + _tiny;
     }
   if (corrDefinition () == rcSimilarator::eLowSpT)
     {
       rcWindow isampled (i.width(), i.height(), i.depth());
       rcWindow msampled (m.width(), m.height(), m.depth());
       rfGaussianConv (i.window(), isampled, 5);
       rfGaussianConv (m.window(), msampled, 5);
       rfCorrelate(isampled, msampled, _corrParams, res);
       return res.r() + _tiny;
     }
   if (corrDefinition () == rcSimilarator::eShading)
     {
       rcWindow tmp (i.width(), i.height(), i.depth());
       rcWindow mag (i.width(), i.height(), i.depth());
       rcWindow g (i.width(), i.height(), i.depth());
       rcWindow gg (i.width(), i.height(), i.depth());
       rfSetWindowBorder(mag, uint8 (0));
       rfSetWindowBorder(g, uint8 (0));
       rfSetWindowBorder(gg, uint8 (0));
       rcWindow gwin (g, 1, 1, g.width()-2, g.height()-2);
       rcWindow ggwin (gg, 1, 1, gg.width()-2, gg.height()-2);
       rcWindow mwin (mag, 1, 1, m.width()-2, m.height()-2);
       rfGaussianConv (i.window(), tmp, 5);
       rfSobelEdge (tmp, mwin, gwin);
       rfGaussianConv (m.window(), tmp, 5);
       rfSobelEdge (tmp, mwin, ggwin);
       rfCorrelate(g, gg, _corrParams, res);
       return res.r() + _tiny;
     }
   if (_maskValid)
     rfCorrelate(i.window(), m.window(), _mask, _corrParams, res, _maskN);
   else
     rfCorrelateWindow(i, m, _corrParams, res);
   if (corrDefinition () == rcSimilarator::eNorm)
     return res.r() + _tiny;
   else if (corrDefinition () == rcSimilarator::eRelative)
     return res.relative() + _tiny;
   else
     {
       rmAssert (1);
       return 0;
     }
 }
rcPixel rcSimilarator::depth () const inline
Definition at line 237 of file rc_similarity.h.
References _depth.
double rcSimilarator::distance (double & i, double & m) const private
Definition at line 824 of file rc_similarity.cpp.
References rmSquare.
Referenced by ssMatrixFill(), and ssMatrixUpdate().
 {
   return (rmSquare ((i-m)/(i+m)));
 }
bool rcSimilarator::entropies (deque< double > & signal, rcEntropyDefinition d = eACI, rcFilteringOp f = eNone) const
Definition at line 314 of file rc_similarity.cpp.
References _entropies, _finished, _matrixSz, entropiesVisualEntropy(), eVisualEntropy, and rmAssert.
Referenced by calcMusclePeriod(), rcMuscleSegmenter::getEMI(), main(), and segPointByEnergy().
 {
   rmAssert (_matrixSz);
   if (definition == eVisualEntropy)
     return entropiesVisualEntropy (signal);
   if (_finished && !_entropies.empty())
     {
       signal = _entropies;
       for (unsigned int i = 0; i < signal.size(); i++)
     {
       signal[i] = 1 - signal[i];
     }
       return true;
     }
   return false;
 }
bool rcSimilarator::entropiesVisualEntropy (deque< double > & signal) const private
Definition at line 338 of file rc_similarity.cpp.
References _finished, _matrixSz, _sums, and rmAssert.
Referenced by entropies().
 {
   rmAssert (_matrixSz);
   if (_finished && !_sums.empty())
     {
       signal = _sums;
       return true;
     }
   return false;
 }
bool rcSimilarator::fill (vector< rcWindow > & firstImages)
Definition at line 63 of file rc_similarity.cpp.
References _depth, _matrixSz, _tw16, _tw32, _tw8, internalFill(), rcPixel16, rcPixel32, rcPixel8, and rmAssert.
Referenced by calcMusclePeriod(), rcEngineImpl::entropyTracker(), rcMuscleSegmenter::getEMI(), main(), rcShape::projectMI(), and segPointByEnergy().
 {
   rmAssert (_matrixSz);
   vector<rcWindow>::iterator start = firstImages.begin();
   if (firstImages.size() > _matrixSz)
     start += (firstImages.size() - _matrixSz);
   switch (_depth) {
   case rcPixel8:
     _tw8.resize(0);
     return internalFill(start, firstImages.end(), _tw8);
   case rcPixel16:
     _tw16.resize(0);
     return internalFill(start, firstImages.end(), _tw16);
   case rcPixel32:
     _tw32.resize(0);
     return internalFill(start, firstImages.end(), _tw32);
   default:
     rmAssert(0);
     break;
   }
   return false;
 }
bool rcSimilarator::fill (deque< rcWindow > & firstImages)
Definition at line 210 of file rc_similarity.cpp.
References _depth, _matrixSz, _tw16, _tw32, _tw8, internalFill(), rcPixel16, rcPixel32, rcPixel8, and rmAssert.
 {
   rmAssert (_matrixSz);
   deque<rcWindow>::iterator start = firstImages.begin();
   if (firstImages.size() > _matrixSz)
     start += (firstImages.size() - _matrixSz);
   switch (_depth) {
   case rcPixel8:
     _tw8.resize(0);
     return internalFill(start, firstImages.end(), _tw8);
   case rcPixel16:
     _tw16.resize(0);
     return internalFill(start, firstImages.end(), _tw16);
   case rcPixel32:
     _tw32.resize(0);
     return internalFill(start, firstImages.end(), _tw32);
   default:
     rmAssert(0);
     break;
   }
   return false;
 }
bool rcSimilarator::fill (vector< double > & firstData)
Definition at line 136 of file rc_similarity.cpp.
References _finished, _matrixSz, _seqD, _SMatrix, _type, eExhaustive, genMatrixEntropy(), rmAssert, ssMatrixFill(), and unity().
 {
   rmAssert (_matrixSz);
   vector<double>::iterator start = firstData.begin();
   vector<double>::iterator end = firstData.end();
   if (firstData.size() > _matrixSz)
     start += (firstData.size() - _matrixSz);
   _finished = true;
   for (; start < end; start++) {
     _seqD.push_back(*start);
   }
   rmAssert (_type == eExhaustive);
   if (_SMatrix.empty()) {
     _SMatrix.resize(_matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       _SMatrix[i].resize(_matrixSz);
   }
   else {
     rmAssert(_SMatrix.size() == _matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       rmAssert(_SMatrix[i].size() == _matrixSz);
   }
   /* Initialize identity diagonal of _SMatrix.
    */
   unity();
   return (_finished = ssMatrixFill(_seqD)) && genMatrixEntropy(_seqD.size());
 }
bool rcSimilarator::fill (deque< double > & firstData)
Definition at line 173 of file rc_similarity.cpp.
References _finished, _matrixSz, _seqD, _SMatrix, _type, eExhaustive, genMatrixEntropy(), rmAssert, ssMatrixFill(), and unity().
 {
   rmAssert (_matrixSz);
   deque<double>::iterator start = firstData.begin();
   deque<double>::iterator end = firstData.end();
   if (firstData.size() > _matrixSz)
     start += (firstData.size() - _matrixSz);
   _finished = true;
   for (; start < end; start++) {
     _seqD.push_back(*start);
   }
   rmAssert (_type == eExhaustive);
   if (_SMatrix.empty()) {
     _SMatrix.resize(_matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       _SMatrix[i].resize(_matrixSz);
   }
   else {
     rmAssert(_SMatrix.size() == _matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       rmAssert(_SMatrix[i].size() == _matrixSz);
   }
   /* Initialize identity diagonal of _SMatrix.
    */
   unity();
   return (_finished = ssMatrixFill(_seqD)) && genMatrixEntropy(_seqD.size());
 }
bool rcSimilarator::fill (const rcWindow & projective, bool isColumns = true)
Definition at line 89 of file rc_similarity.cpp.
References _depth, _matrixSz, _tw16, _tw32, _tw8, rcWindow::frameBuf(), rcWindow::height(), internalFill(), rcPixel16, rcPixel32, rcPixel8, rfImage8Transpose(), rmAssert, and rcWindow::width().
 {
   rmAssert (_matrixSz);
   vector<rcWindow> firstImages (isColumns ? projective.width() :
                 projective.height());
   vector<rcWindow>::iterator start = firstImages.begin();
   // Call transpose so that the columns are organised in rows
   if (isColumns)
     {
       for (int32 x = 0; start < firstImages.end (); start++, x++)
     *start = rfImage8Transpose (rcWindow (projective.frameBuf (),
                           x, 0, 1, projective.height()));
     }
   else
     {
       rmAssert (start == firstImages.begin());
       for (int32 y = 0; start < firstImages.end (); start++, y++)
     *start = rcWindow (projective.frameBuf (), 0, y, projective.width(), 1);
     }
   start = firstImages.begin();
   if (firstImages.size() > _matrixSz)
     start += (firstImages.size() - _matrixSz);
   switch (_depth) {
   case rcPixel8:
     _tw8.resize(0);
     return internalFill(start, firstImages.end(), _tw8);
   case rcPixel16:
     _tw16.resize(0);
     return internalFill(start, firstImages.end(), _tw16);
   case rcPixel32:
     _tw32.resize(0);
     return internalFill(start, firstImages.end(), _tw32);
   default:
     rmAssert(0);
     break;
   }
   return false;
 }
rcIPair rcSimilarator::fillImageSize () const
Definition at line 235 of file rc_similarity.cpp.
References _depth, _matrixSz, _tw16, _tw32, _tw8, rcPixel16, rcPixel32, rcPixel8, and rmAssert.
 {
   rmAssert (_matrixSz);
   switch (_depth) {
   case rcPixel8:
     return rcIPair (_tw8[0].width(), _tw8[0].height());
   case rcPixel16:
     return rcIPair (_tw16[0].width(), _tw16[0].height());
   case rcPixel32:
     return rcIPair (_tw32[0].width(), _tw32[0].height());
   default:
     rmAssert(0);
     break;
   }
   return rcIPair (0,0);
 }
bool rcSimilarator::filter (vector< double > &)
template<class T > bool rcSimilarator::filterOp (vector< T > &) private
bool rcSimilarator::genListEntropy (uint32 tWinSz) private
bool rcSimilarator::genMatrixEntropy (uint32 tWinSz) private
Definition at line 829 of file rc_similarity.cpp.
References _entropies, _log2MSz, _matrixSz, _SMatrix, _sums, rmAssert, and shannon().
Referenced by fill(), internalFill(), and internalUpdate().
 {
   if (tWinSz != _matrixSz)
     return false;
   /* Create sums array and initialize all the elements.
    */
   rmAssert(_SMatrix.size() == _matrixSz);
     if (_sums.empty())
         _sums.resize(_matrixSz);
     else
         rmAssert(_sums.size() == _matrixSz);
   if (_entropies.empty())
     _entropies.resize(_matrixSz);
   else
     rmAssert(_entropies.size() == _matrixSz);
   for (uint32 i = 0; i < _matrixSz; i++) {
     rmAssert(_SMatrix[i].size() == _matrixSz);
     _sums[i] = _SMatrix[i][i];
     _entropies[i] = 0.0;
   }
   for (uint32 i = 0; i < (_matrixSz-1); i++)
     for (uint32 j = (i+1); j < _matrixSz; j++) {
       _sums[i] += _SMatrix[i][j];
       _sums[j] += _SMatrix[i][j];
     }
     for (uint32  i = 0; i < _matrixSz; i++) {
     for (uint32 j = i; j < _matrixSz; j++) {
       double rr =
     _SMatrix[i][j]/_sums[i]; // Normalize for total energy in samples
       _entropies[i] += shannon(rr);
       if (i != j) {
     rr = _SMatrix[i][j]/_sums[j];//Normalize for total energy in samples
     _entropies[j] += shannon(rr);
       }
     }
     _entropies[i] = _entropies[i]/_log2MSz;// Normalize for cnt of samples
   }
     for (uint32  i = 0; i < _matrixSz; i++)
         _sums[i] = _sums[i] / _matrixSz;
   return true;
 }
template<class T > double rcSimilarator::genPeriodicity (const vector< T > & signal, const vector< T > & absc, rcDPair & freq) private
template<class T > float rcSimilarator::histogramIntersection (rcCorrelationWindow< T > & i, rcCorrelationWindow< T > & m) const private
template<class I , class T > bool rcSimilarator::internalFill (I start, I end, deque< rcCorrelationWindow< T > > & tWin) private
Definition at line 394 of file rc_similarity.cpp.
References _entropies, _finished, _ltEntropies, _ltOn, _matrixSz, _SMatrix, genMatrixEntropy(), matrixSz(), rmAssert, ssMatrixFill(), and unity().
Referenced by fill().
 {
   _finished = true;
   for (; start < end; start++) {
     tWin.push_back(rcCorrelationWindow<T>(*start));
     (*start).frameBuf().unlock();
   }
   if (tWin.empty()) {
     if (!_SMatrix.empty())
       _SMatrix.resize(0);
     return false;
   }
   if (_SMatrix.empty()) {
     _SMatrix.resize(_matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       _SMatrix[i].resize(_matrixSz);
   }
   else {
     rmAssert(_SMatrix.size() == _matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       rmAssert(_SMatrix[i].size() == _matrixSz);
   }
   /* Initialize identity diagonal of _SMatrix.
    */
   unity();
   /*
    * if longtermCache is on, write the first matrix size entropies
    */
   bool rtn = (_finished = ssMatrixFill(tWin)) && genMatrixEntropy(tWin.size());
   if (rtn && _ltOn && !_entropies.empty())
     {
       for (uint32 i = 0; i < matrixSz(); i++)
     _ltEntropies[i] = (float) _entropies[i];
     }
   return rtn;
 }
template<class T > bool rcSimilarator::internalUpdate (rcWindow & nextImage, deque< rcCorrelationWindow< T > > & tWin) private
Definition at line 628 of file rc_similarity.cpp.
References _entropies, _finished, _ltEntropies, _ltOn, _matrixSz, _SMatrix, _type, eApproximate, eExhaustive, rcWindow::frameBuf(), genMatrixEntropy(), rmAssert, shiftSMatrix(), ssMatrixUpdate(), and rcSharedFrameBufPtr::unlock().
Referenced by update().
 {
   /* First, see if an image and its associated results needs to be
    * removed.
    */
   if (tWin.size() == _matrixSz) {
     tWin.pop_front();
     if ((_type == eApproximate) || (_type == eExhaustive))
       shiftSMatrix();
   }
   if ((_type == eApproximate) || (_type == eExhaustive)) {
     if (_SMatrix.empty()) {
       _SMatrix.resize(_matrixSz);
       for (uint32 i = 0; i < _matrixSz; i++)
     _SMatrix[i].resize(_matrixSz);
     }
     rmAssert(_SMatrix.size() == _matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       rmAssert(_SMatrix[i].size() == _matrixSz);
   }
   tWin.push_back(rcCorrelationWindow<T>(nextImage));
   nextImage.frameBuf().unlock();
   /*
    * if longtermCache is on, write the last entropy value to the cache line
    */
   bool rtn = (_finished=ssMatrixUpdate(tWin)) && genMatrixEntropy(tWin.size());
   if (rtn && _ltOn && !_entropies.empty())
     {
       _ltEntropies.push_back ((float) _entropies.back ());
     }
   return rtn;
 }
bool rcSimilarator::internalUpdate (double & nextImage, deque< double > & tWin) private
Definition at line 597 of file rc_similarity.cpp.
References _finished, _matrixSz, _SMatrix, _type, eApproximate, eExhaustive, genMatrixEntropy(), rmAssert, shiftSMatrix(), and ssMatrixUpdate().
 {
   /* First, see if an image and its associated results needs to be
    * removed.
    */
   if (tWin.size() == _matrixSz) {
     tWin.pop_front();
     if ((_type == eApproximate) || (_type == eExhaustive))
       shiftSMatrix();
   }
   if ((_type == eApproximate) || (_type == eExhaustive)) {
     if (_SMatrix.empty()) {
       _SMatrix.resize(_matrixSz);
       for (uint32 i = 0; i < _matrixSz; i++)
     _SMatrix[i].resize(_matrixSz);
     }
     rmAssert(_SMatrix.size() == _matrixSz);
     for (uint32 i = 0; i < _matrixSz; i++)
       rmAssert(_SMatrix[i].size() == _matrixSz);
   }
   tWin.push_back(nextImage);
   return (_finished=ssMatrixUpdate(tWin)) && genMatrixEntropy(tWin.size());
 }
bool rcSimilarator::longTermCache (bool onOrOff)
Definition at line 375 of file rc_similarity.cpp.
References _ltEntropies, _ltOn, _matrixSz, and rmAssert.
 {
   rmAssert (_matrixSz);
   _ltEntropies.resize (_matrixSz);
   _ltOn = onOrOff;
   return _ltOn;
 }
bool rcSimilarator::longTermCache () const
Definition at line 383 of file rc_similarity.cpp.
References _ltOn.
 {
   return _ltOn;
 }
const vector< float > & rcSimilarator::longTermEntropy () const
Definition at line 388 of file rc_similarity.cpp.
References _ltEntropies.
 {
   return _ltEntropies;
 }
rcMatrixGeneration rcSimilarator::matGenType () const inline
Definition at line 235 of file rc_similarity.h.
References _type.
uint32 rcSimilarator::matrixSz () const inline
Definition at line 234 of file rc_similarity.h.
References _matrixSz.
Referenced by internalFill().
void rcSimilarator::mu (vector< double > & src, vector< double > & dst)
bool rcSimilarator::operator< (const rcSimilarator & rhs) const private
rcSimilarator& rcSimilarator::operator= (const rcSimilarator & rhs) private
bool rcSimilarator::operator== (const rcSimilarator & rhs) const private
double rcSimilarator::periodicity (const vector< double > & signal, const vector< double > & absc, rcDPair & freq)
template<class T > double rcSimilarator::relativeCorrelate (rcCorrelationWindow< T > & i, rcCorrelationWindow< T > & m) const private
Definition at line 811 of file rc_similarity.cpp.
References _corrParams, _mask, _maskN, _maskValid, _tiny, rfCorrelate(), rfCorrelateWindow(), and rcCorrelationWindow< T >::window().
 {
   rcCorr res;
   if (_maskValid)
     rfCorrelate(i.window(), m.window(), _mask, _corrParams, res, _maskN);
   else
     rfCorrelateWindow(i, m, _corrParams, res);
   return res.relative() + _tiny;
 }
bool rcSimilarator::selfSimilarityMatrix (deque< deque< double > > & matrix) const
Definition at line 351 of file rc_similarity.cpp.
References _entropies, _finished, _matrixSz, _SMatrix, and rmAssert.
 {
   rmAssert (_matrixSz);
   if (_finished && !_entropies.empty() && !_SMatrix.empty()) {
     matrix = _SMatrix;
     return true;
   }
   return false;
 }
bool rcSimilarator::sequentialCorrelations (deque< double > & slist) const
Definition at line 363 of file rc_similarity.cpp.
References _finished, _matrixSz, _SList, and rmAssert.
 {
   rmAssert (_matrixSz);
   if (_finished && !_SList.empty()) {
     slist = _SList;
     return true;
   }
   return false;
 }
void rcSimilarator::setMask (const rcWindow & mask)
Definition at line 277 of file rc_similarity.cpp.
References _depth, _mask, _maskN, _maskValid, _matrixSz, rcWindow::copyPixelsFromWindow(), rcWindow::depth(), rcWindow::getPixel(), rcWindow::height(), rcPixel16, rcPixel32, rcPixel8, rmAssert, and rcWindow::width().
Referenced by segPointByEnergy().
 {
   rmAssert (_matrixSz);
   rmAssert(mask.depth() == _depth);
   _maskValid = true;
   if ((_mask.width() != mask.width()) ||
       (_mask.height() != mask.height()))
     _mask = rcWindow(mask.width(), mask.height(), mask.depth());
   _mask.copyPixelsFromWindow(mask);
   _maskN = 0;
   uint32 allOnes = 0xFF;
   if (_depth == rcPixel16)
     allOnes = 0xFFFF;
   else if (_depth == rcPixel32)
     allOnes = 0xFFFFFFFF;
   else
     rmAssert(_depth == rcPixel8);
   _maskN = 0;
   for (int32 y = 0; y < _mask.height(); y++)
     for (int32 x = 0; x < _mask.width(); x++) {
       uint32 val = _mask.getPixel(x, y);
       if (val == allOnes)
     _maskN++;
       else
     rmAssert(val == 0);
     }
 }
double rcSimilarator::shannon (double r) const inline private
Definition at line 359 of file rc_similarity.h.
Referenced by genMatrixEntropy().
void rcSimilarator::shiftSList () private
Definition at line 669 of file rc_similarity.cpp.
References _SList, and rmAssert.
 {
   rmAssert(!_SList.empty());
   _SList.pop_front();
   _SList.push_back(-1.0);
 }
void rcSimilarator::shiftSMatrix () private
Definition at line 676 of file rc_similarity.cpp.
References _matrixSz, _SMatrix, and rmExceptionMacro.
Referenced by internalUpdate().
 {
   if (_SMatrix.size() != _matrixSz)
     rmExceptionMacro(<<"Similarity Engine Failure");
   _SMatrix.pop_front();
   for (uint32 i = 0; i < (_matrixSz - 1); i++) {
     _SMatrix[i].pop_front();
     _SMatrix[i].push_back(-1.0);
   }
   deque<double> empty;
   _SMatrix.push_back(empty);
   _SMatrix.back().resize(_matrixSz);
 }
template<class T > bool rcSimilarator::ssListFill (deque< rcCorrelationWindow< T > > & tWin) private
Definition at line 569 of file rc_similarity.cpp.
References _guiUpdate, _notify, _SList, correlate(), rmAssert, and rcSimilarator::progressNotification::update().
 {
   if (tWin.size() < 2)
     return true;
   rmAssert(_SList.size() >= (tWin.size()-1));
   progressNotification* progress = 0;
   if (_notify) progress =
     new progressNotification((int32)tWin.size()-1, _guiUpdate);
   for (uint32 i = 1; i < tWin.size(); i++) {
     _SList[i-1] = correlate(tWin[i-1], tWin[i]);
     tWin[i-1].frameBuf().unlock();
     if (progress && progress->update()) {
       tWin[i].frameBuf().unlock();
       delete progress;
       return false;
     }
   }
   tWin[tWin.size()-1].frameBuf().unlock();
   if (progress) delete progress;
   return true;
 }
template<class T > bool rcSimilarator::ssListUpdate (deque< rcCorrelationWindow< T > > & tWin) private
template<class T > bool rcSimilarator::ssMatrixApproxFill (deque< rcCorrelationWindow< T > > & tWin) private
template<class T > bool rcSimilarator::ssMatrixApproxUpdate (deque< rcCorrelationWindow< T > > & tWin) private
template<class T > bool rcSimilarator::ssMatrixFill (deque< rcCorrelationWindow< T > > & tWin) private
Definition at line 460 of file rc_similarity.cpp.
References _cacheSz, _guiUpdate, _matrixSz, _notify, _SMatrix, cacheSz(), correlate(), rmAssert, and rcSimilarator::progressNotification::update().
Referenced by fill(), and internalFill().
 {
   rmAssert(_SMatrix.size() == _matrixSz);
   const int32 tWinSz = tWin.size();
   rmAssert(tWinSz <= (int32)_matrixSz);
   int32 cacheSz = _cacheSz;
   if (cacheSz <= 2)
     cacheSz = tWinSz + 2;
   const int32 cacheBlkSz = cacheSz - 2;
   progressNotification* progress = 0;
   if (_notify) progress =
     new progressNotification(tWinSz*(tWinSz-1)/2, _guiUpdate);
   /* The following was designed to work well when the number of images
    * that can be stored in memory at any one time is space limited.
    * In the absence of other consumers of cache resources, it reads in
    * O((N^2)/C) images from disk, where N is the number of images in
    * the movie fifo and C is the count of cache entries available.
    * The basic algorithm works as follows:
    *
    * Step 1 - Use the first cache block size number of images
    * remaining and perform cross correlations on all of them.
    *
    * Step 2 - For all the remaining images, read in one image at a
    * time, correlating each with every image from step 1 before moving
    * on to the next image.
    *
    * Note: In both steps 1) and 2), passes through the cached images
    * are done in alternating directions to guarantee that the most
    * recently used images get processed first. This is done to make
    * performance degradation more linear in the presence of other
    * consumers of the cache. In particular, it limits pathological
    * cases where reading needed images into the cache causes other
    * needed images to be flushed from the cache before they get
    * used. Note that this assumes an LRU type caching policy.
    *
    * Step 3 - Update the current starting point by the cache block
    * size.
    *
    * Repeat the entire process until the new starting point is >= the
    * fifo size.
    */
   for (int32 i = 0; i < tWinSz;
        /* Step 3 - Update start */ i += cacheBlkSz) {
     int32 cacheIncr = 1, cacheBegin, cacheEnd;
     int32 firstUncachedFrame = i + cacheBlkSz;
     if (firstUncachedFrame > tWinSz)
       firstUncachedFrame = tWinSz;
     /* Step 1 - Fill cache.
      */
     for (int32 j = i + 1; j < firstUncachedFrame; j++) {
       if (cacheIncr == 1) {
     cacheIncr = -1; cacheBegin = j - 1; cacheEnd = i - 1;
       }
       else {
     cacheIncr = 1;  cacheBegin = i; cacheEnd = j;
       }
       for (int32 k = cacheBegin; k != cacheEnd; k += cacheIncr) {
     rmAssert((j >= 0) && (j < tWinSz));
     rmAssert((k >= 0) && (k < tWinSz));
     const double r = correlate(tWin[j], tWin[k]);
     _SMatrix[j][k] = _SMatrix[k][j] = r;
     tWin[k].frameBuf().unlock();
     if (progress && progress->update()) {
       tWin[j].frameBuf().unlock();
       delete progress;
       return false;
     }
       } // End of: for ( k = cacheBegin; k != cacheEnd; k += cacheIncr)
       tWin[j].frameBuf().unlock();
     } // End of: for (int32 j = i + 1; j < firstUncachedFrame; j++)
     /* Step 2 - Correlate remaining images against cached images.
      */
     for (int32 j = firstUncachedFrame; j < tWinSz; j++) {
       if (cacheIncr == 1) {
     cacheIncr = -1; cacheBegin = firstUncachedFrame-1; cacheEnd = i-1;
       }
       else {
     cacheIncr = 1; cacheBegin = i; cacheEnd = firstUncachedFrame;
       }
       for (int32 k = cacheBegin; k != cacheEnd; k += cacheIncr) {
     rmAssert((j >= 0) && (j < tWinSz));
     rmAssert((k >= 0) && (k < tWinSz));
     const double r = correlate(tWin[j], tWin[k]);
     _SMatrix[j][k] = _SMatrix[k][j] = r;
     tWin[k].frameBuf().unlock();
     if (progress && progress->update()) {
       tWin[j].frameBuf().unlock();
       delete progress;
       return false;
     }
       } // End of: for (k = cacheBegin; k != cacheEnd; k += cacheIncr)
       tWin[j].frameBuf().unlock();
     } // End of: for (int32 j = i + 1; j < firstUncachedFrame; j++)
   }
   if (progress) delete progress;
   return true;
 }
bool rcSimilarator::ssMatrixFill (deque< double > & data) private
Definition at line 440 of file rc_similarity.cpp.
References _matrixSz, _SMatrix, distance(), and rmAssert.
 {
   rmAssert(_SMatrix.size() == _matrixSz);
   const int32 dataSz = data.size();
   rmAssert(dataSz <= (int32)_matrixSz);
   for (int32 i = 0; i < dataSz; i++)
     {
       for (int32 j = i + 1; j < dataSz; j++)
     {
       const double r = distance (data[i], data[j]);
       _SMatrix[j][i] = _SMatrix[i][j] = r;
     }
     }
   return true;
 }
template<class T > bool rcSimilarator::ssMatrixUpdate (deque< rcCorrelationWindow< T > > & tWin) private
Definition at line 714 of file rc_similarity.cpp.
References _guiUpdate, _matrixSz, _notify, _SMatrix, _tiny, correlate(), rmAssert, and rcSimilarator::progressNotification::update().
Referenced by internalUpdate().
 {
   rmAssert(_SMatrix.size() == _matrixSz);
   rmAssert(!tWin.empty());
   const uint32 lastImgIndex = tWin.size() - 1;
   rmAssert(lastImgIndex < _matrixSz);
   progressNotification* progress = 0;
   if (_notify) progress =
     new progressNotification(lastImgIndex, _guiUpdate);
   _SMatrix[lastImgIndex][lastImgIndex] = 1.0 + _tiny;
   for (uint32 i = 0; i < lastImgIndex; i++) {
     _SMatrix[i][lastImgIndex] = _SMatrix[lastImgIndex][i] =
       correlate(tWin[i], tWin[lastImgIndex]);
     tWin[i].frameBuf().unlock();
     if (progress && progress->update()) {
       tWin[lastImgIndex].frameBuf().unlock();
       delete progress;
       return false;
     }
   }
   tWin[lastImgIndex].frameBuf().unlock();
   if (progress) delete progress;
   return true;
 }
bool rcSimilarator::ssMatrixUpdate (deque< double > & data) private
Definition at line 694 of file rc_similarity.cpp.
References _matrixSz, _SMatrix, _tiny, distance(), and rmAssert.
 {
   rmAssert(_SMatrix.size() == _matrixSz);
   rmAssert(!tWin.empty());
   const uint32 lastImgIndex = tWin.size() - 1;
   rmAssert(lastImgIndex < _matrixSz);
   _SMatrix[lastImgIndex][lastImgIndex] = 1.0 + _tiny;
   for (uint32 i = 0; i < lastImgIndex; i++) {
     _SMatrix[i][lastImgIndex] = _SMatrix[lastImgIndex][i] =
       distance (tWin[i], tWin[lastImgIndex]);
   }
   return true;
 }
void rcSimilarator::unity () private
Definition at line 881 of file rc_similarity.cpp.
References _matrixSz, _SMatrix, _tiny, and rmAssert.
Referenced by fill(), and internalFill().
 {
   rmAssert(_SMatrix.size() == _matrixSz);
   for (uint32 i = 0; i < _matrixSz; i++)
     _SMatrix[i][i] = 1.0 + _tiny;
 }
bool rcSimilarator::update (rcWindow nextImage)
Definition at line 253 of file rc_similarity.cpp.
References _depth, _matrixSz, _tw16, _tw32, _tw8, internalUpdate(), rcPixel16, rcPixel32, rcPixel8, and rmAssert.
Referenced by calcMusclePeriod(), rcMuscleSegmenter::getEMI(), and segPointByEnergy().
 {
   rmAssert (_matrixSz);
   switch (_depth) {
   case rcPixel8:
     return internalUpdate(nextImage, _tw8);
   case rcPixel16:
     return internalUpdate(nextImage, _tw16);
   case rcPixel32:
     return internalUpdate(nextImage, _tw32);
   default:
     rmAssert(0);
     break;
   }
   return false;
 }
bool rcSimilarator::update (double & nextData)
Definition at line 271 of file rc_similarity.cpp.
References _matrixSz, _seqD, internalUpdate(), and rmAssert.
 {
   rmAssert (_matrixSz);
   return internalUpdate(nextData, _seqD);
 }
Friends And Related Function Documentation
ostream& operator<< (ostream & ous, const rcSimilarator & rc) friend
Definition at line 889 of file rc_similarity.cpp.
 {
   rcSimilarator* rc2 = const_cast<rcSimilarator*>(&rc);
   deque<deque<double> >& cm = rc2->_SMatrix;
   if (!cm.empty()) {
     ous << "{";
     for (uint32 i = 0; i < cm.size(); i++) {
       ous << "{";
       deque<double>::iterator ds = cm[i].begin();
       for (uint32 j = 0; j < cm.size() - 1; j++, ds++)
     ous << *ds << ",";
       if (i < cm.size() - 1)
     ous << *ds << "}," << endl;
       else ous << *ds << "}" << endl;
     }
     ous << "}" << endl;
   }
   return ous;
 }
Member Data Documentation
const uint32 rcSimilarator::_cacheSz private
Definition at line 373 of file rc_similarity.h.
Referenced by cacheSz(), and ssMatrixFill().
const rcCorrelationDefinition rcSimilarator::_cdl private
Definition at line 374 of file rc_similarity.h.
Referenced by corrDefinition().
rsCorrParams rcSimilarator::_corrParams private
Definition at line 380 of file rc_similarity.h.
Referenced by correlate(), and relativeCorrelate().
const rcPixel rcSimilarator::_depth private
Definition at line 371 of file rc_similarity.h.
Referenced by depth(), fill(), fillImageSize(), rcSimilarator(), setMask(), and update().
deque<double> rcSimilarator::_entropies private
Definition at line 402 of file rc_similarity.h.
Referenced by entropies(), genMatrixEntropy(), internalFill(), internalUpdate(), and selfSimilarityMatrix().
bool rcSimilarator::_finished private
Definition at line 376 of file rc_similarity.h.
Referenced by aborted(), entropies(), entropiesVisualEntropy(), fill(), internalFill(), internalUpdate(), selfSimilarityMatrix(), and sequentialCorrelations().
rcProgressIndicator* const rcSimilarator::_guiUpdate private
Definition at line 377 of file rc_similarity.h.
Referenced by ssListFill(), ssMatrixFill(), and ssMatrixUpdate().
vector<double> rcSimilarator::_kernel private
Definition at line 404 of file rc_similarity.h.
double rcSimilarator::_log2MSz private
Definition at line 379 of file rc_similarity.h.
Referenced by genMatrixEntropy(), and rcSimilarator().
vector<float> rcSimilarator::_ltEntropies private
Definition at line 409 of file rc_similarity.h.
Referenced by internalFill(), internalUpdate(), longTermCache(), and longTermEntropy().
bool rcSimilarator::_ltOn private
Definition at line 408 of file rc_similarity.h.
Referenced by internalFill(), internalUpdate(), longTermCache(), and rcSimilarator().
rcWindow rcSimilarator::_mask private
Definition at line 365 of file rc_similarity.h.
Referenced by clearMask(), correlate(), relativeCorrelate(), and setMask().
int32 rcSimilarator::_maskN private
Definition at line 366 of file rc_similarity.h.
Referenced by correlate(), relativeCorrelate(), and setMask().
bool rcSimilarator::_maskValid private
Definition at line 364 of file rc_similarity.h.
Referenced by clearMask(), correlate(), relativeCorrelate(), and setMask().
const uint32 rcSimilarator::_matrixSz private
Definition at line 372 of file rc_similarity.h.
Referenced by clearMask(), entropies(), entropiesVisualEntropy(), fill(), fillImageSize(), genMatrixEntropy(), internalFill(), internalUpdate(), longTermCache(), matrixSz(), rcSimilarator(), selfSimilarityMatrix(), sequentialCorrelations(), setMask(), shiftSMatrix(), ssMatrixFill(), ssMatrixUpdate(), unity(), and update().
const bool rcSimilarator::_notify private
Definition at line 375 of file rc_similarity.h.
Referenced by ssListFill(), ssMatrixFill(), and ssMatrixUpdate().
deque<double> rcSimilarator::_seqD private
Definition at line 395 of file rc_similarity.h.
Referenced by fill(), and update().
deque<double> rcSimilarator::_SList private
Definition at line 401 of file rc_similarity.h.
Referenced by sequentialCorrelations(), shiftSList(), and ssListFill().
deque<deque<double> > rcSimilarator::_SMatrix private
Definition at line 399 of file rc_similarity.h.
Referenced by fill(), genMatrixEntropy(), internalFill(), internalUpdate(), operator<<(), selfSimilarityMatrix(), shiftSMatrix(), ssMatrixFill(), ssMatrixUpdate(), and unity().
deque<double> rcSimilarator::_sums private
Definition at line 403 of file rc_similarity.h.
Referenced by entropiesVisualEntropy(), and genMatrixEntropy().
const double rcSimilarator::_tiny private
Definition at line 378 of file rc_similarity.h.
Referenced by correlate(), relativeCorrelate(), ssMatrixUpdate(), and unity().
deque<rcCorrelationWindow<uint16> > rcSimilarator::_tw16 private
Definition at line 388 of file rc_similarity.h.
Referenced by fill(), fillImageSize(), and update().
deque<rcCorrelationWindow<uint32> > rcSimilarator::_tw32 private
Definition at line 389 of file rc_similarity.h.
Referenced by fill(), fillImageSize(), and update().
deque<rcCorrelationWindow<uint8> > rcSimilarator::_tw8 private
Definition at line 387 of file rc_similarity.h.
Referenced by fill(), fillImageSize(), and update().
const rcMatrixGeneration rcSimilarator::_type private
Definition at line 370 of file rc_similarity.h.
Referenced by fill(), internalUpdate(), and matGenType().
The documentation for this class was generated from the following files:
include/analysis/rc_similarity.h
src/analysis/code/rc_similarity.cpp