Visible: lm_unit_dependency Class Reference
lm_unit_dependency Class Reference
#include <include/stlplus/library_manager.hpp>
Public Member Functions
lm_unit_dependency (void)
lm_unit_dependency (const std::string &library, const lm_unit_name &name)
~lm_unit_dependency (void)
const std::string & library (void) const
void set_library (const std::string &library)
const lm_unit_name & unit_name (void) const
void set_unit_name (const lm_unit_name &unit_name)
const std::string & name (void) const
void set_name (const std::string &name)
const std::string & type (void) const
void set_type (const std::string &type)
Private Attributes
std::string m_library
lm_unit_name m_name
Friends
void dump (dump_context &context, const lm_unit_dependency &) throw (persistent_dump_failed)
void restore (restore_context &context, lm_unit_dependency &) throw (persistent_restore_failed)
otext & print (otext &, const lm_unit_dependency &)
otext & print (otext &, const lm_unit_dependency &, unsigned indent)
otext & operator<< (otext &, const lm_unit_dependency &)
Detailed Description
Definition at line 126 of file library_manager.hpp.
Constructor & Destructor Documentation
lm_unit_dependency::lm_unit_dependency (void)
Definition at line 337 of file library_manager.cpp.
 {
 }
lm_unit_dependency::lm_unit_dependency (const std::string & library, const lm_unit_name & name)
Definition at line 341 of file library_manager.cpp.
                                                                                          : m_library(library), m_name(name)
 {
 }
lm_unit_dependency::~lm_unit_dependency (void)
Definition at line 345 of file library_manager.cpp.
 {
 }
Member Function Documentation
const std::string & lm_unit_dependency::library (void) const
Definition at line 349 of file library_manager.cpp.
References m_library.
Referenced by out_of_date_chk(), lm_library::pretty_print(), lm_unit::print_long(), and set_library().
 {
   return m_library;
 }
const std::string & lm_unit_dependency::name (void) const
Definition at line 369 of file library_manager.cpp.
References m_name, and lm_unit_name::name().
Referenced by lm_library::pretty_print(), and lm_unit::print_long().
 {
   return m_name.name();
 }
void lm_unit_dependency::set_library (const std::string & library)
Definition at line 354 of file library_manager.cpp.
References library(), and m_library.
 {
   m_library = library;
 }
void lm_unit_dependency::set_name (const std::string & name)
Definition at line 374 of file library_manager.cpp.
References m_name, and lm_unit_name::set_name().
 {
   m_name.set_name(name);
 }
void lm_unit_dependency::set_type (const std::string & type)
Definition at line 384 of file library_manager.cpp.
References m_name, and lm_unit_name::set_type().
 {
   m_name.set_type(type);
 }
void lm_unit_dependency::set_unit_name (const lm_unit_name & unit_name)
Definition at line 364 of file library_manager.cpp.
References m_name, and unit_name().
 {
   m_name = unit_name;
 }
const std::string & lm_unit_dependency::type (void) const
Definition at line 379 of file library_manager.cpp.
References m_name, and lm_unit_name::type().
Referenced by lm_library::pretty_print(), and lm_unit::print_long().
 {
   return m_name.type();
 }
const lm_unit_name & lm_unit_dependency::unit_name (void) const
Definition at line 359 of file library_manager.cpp.
References m_name.
Referenced by out_of_date_chk(), and set_unit_name().
 {
   return m_name;
 }
Friends And Related Function Documentation
void dump (dump_context & context, const lm_unit_dependency &) throw (persistent_dump_failed) friend
Definition at line 389 of file library_manager.cpp.
 {
   dump(context, dependency.m_library);
   dump(context, dependency.m_name);
 }
otext& operator<< (otext & , const lm_unit_dependency &) friend
Definition at line 413 of file library_manager.cpp.
 {
   return print(str, dependency);
 }
otext& print (otext & , const lm_unit_dependency &) friend
Definition at line 401 of file library_manager.cpp.
 {
   return str << "unit: " << dependency.m_library << "." << dependency.m_name;
 }
otext& print (otext & , const lm_unit_dependency & , unsigned indent) friend
Definition at line 406 of file library_manager.cpp.
 {
   print_indent(str, indent);
   print(str, dependency);
   return str << endl;
 }
void restore (restore_context & context, lm_unit_dependency &) throw (persistent_restore_failed) friend
Definition at line 395 of file library_manager.cpp.
 {
   restore(context, dependency.m_library);
   restore(context, dependency.m_name);
 }
Member Data Documentation
std::string lm_unit_dependency::m_library private
Definition at line 152 of file library_manager.hpp.
Referenced by library(), print(), and set_library().
lm_unit_name lm_unit_dependency::m_name private
Definition at line 153 of file library_manager.hpp.
Referenced by name(), print(), set_name(), set_type(), set_unit_name(), type(), and unit_name().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp