Visible: rcGraphicsTrackImpl Class Reference
rcGraphicsTrackImpl Class Reference
#include <include/visiCore/rc_graphicstrackimpl.h>
Public Member Functions
rcGraphicsTrackImpl (const char *tag, const char *name, const char *description, const char *displayFormat, uint32 sizeLimit)
virtual ~rcGraphicsTrackImpl ()
virtual uint32 segments ()
virtual rcSegmentImpl segment (uint32 index)
virtual void popSegment ()
virtual rcGraphicsSegmentIterator * getDataSegmentIterator (const rcTimestamp &pos)
virtual uint32 getSegmentCount (void)
virtual void writeValue (const rcTimestamp &timestamp, const rcRect &focus, const rcVisualGraphicsCollection &value)
virtual void flush (void)
virtual rcWriter * down_cast ()
Public Member Functions inherited from rcTrackImpl
rcTrackImpl (rcTrackType trackType, rcWriterType writerType, const char *tag, const char *name, const char *description, const char *displayFormat, uint32 limit, rcTimestamp firstTime=-1.0)
virtual ~rcTrackImpl ()
virtual rcTrackType getTrackType (void)
virtual rcWriterType getWriterType (void)
virtual const char * getTag (void)
virtual const char * getName (void)
virtual const char * getDescription (void)
virtual uint32 getSizeLimit () const
virtual const char * getDisplayFormatString (void)
virtual rcTimestamp getTrackStart (void)
virtual void setTrackStart (const rcTimestamp &time)
virtual void setExportable (bool e)
virtual void setDescription (const char *text)
virtual void setName (const char *text)
virtual bool isExportable (void)
virtual rcTrackSemantics getSemantics (void)
virtual void setSemantics (const rcTrackSemantics &s)
virtual rcRect getAnalysisRect (void)
virtual void setAnalysisRect (const rcRect &f)
Public Member Functions inherited from rcTrack
virtual ~rcTrack ()
Public Member Functions inherited from rcWriter
virtual ~rcWriter ()
Public Member Functions inherited from rcGraphicsTrack
virtual ~rcGraphicsTrack ()
Public Member Functions inherited from rcGraphicsWriter
virtual ~rcGraphicsWriter ()
Private Member Functions
void setWriterState (rcTimestamp time, rcRect focus, const rcVisualGraphicsCollection &value)
void addSegment (rcTimestamp segmentLength)
Private Attributes
deque< rcGraphicsSegment > _segments
rcVisualGraphicsCollection _currentValue
Friends
class rcGraphicsSegmentIteratorImpl
Additional Inherited Members
Public Types inherited from rcGraphicsTrack
enum { ePersistenceVersion = 1 }
Static Public Member Functions inherited from rcTrack
static rcTrackType type (const std::string &name)
static const std::string & name (rcTrackType type)
Protected Member Functions inherited from rcTrackImpl
rcTimestamp lastSegmentLength ()
rcTimestamp nextSegmentLength (const rcTimestamp &timestamp)
rcTimestamp nextSegmentStart ()
virtual void setWriterState (const rcTimestamp &time, rcRect focus)
void updateFirstTime (const rcTimestamp &timestamp)
Protected Attributes inherited from rcTrackImpl
rcMutex _mutex
rcTimestamp _currentLength
rcRect _currentFocus
uint32 _sizeLimit
rcTimestamp _firstTime
rcTimestamp _expStartTime
bool _isExportable
rcTrackSemantics _dataSemantics
rcRect _analysisFocus
Detailed Description
Definition at line 46 of file rc_graphicstrackimpl.h.
Constructor & Destructor Documentation
rcGraphicsTrackImpl::rcGraphicsTrackImpl (const char * tag, const char * name, const char * description, const char * displayFormat, uint32 sizeLimit)
Definition at line 173 of file rc_graphicstrackimpl.cpp.
References _currentValue, and rcTrackImpl::_isExportable.
         : rcTrackImpl( eGraphicsTrack , eGraphicsWriter , tag , name , description, displayFormat, sizeLimit )
 {
     _isExportable = true;
     _currentValue = rcVisualGraphicsCollection();
 }
virtual rcGraphicsTrackImpl::~rcGraphicsTrackImpl () inline virtual
Definition at line 55 of file rc_graphicstrackimpl.h.
 { };
Member Function Documentation
void rcGraphicsTrackImpl::addSegment (rcTimestamp segmentLength) private
Definition at line 264 of file rc_graphicstrackimpl.cpp.
References rcTrackImpl::_currentFocus, _currentValue, _segments, cZeroTime, and rcTrackImpl::nextSegmentStart().
Referenced by flush(), and writeValue().
 {
     // Zero segment length is not allowed
     if ( segmentLength > cZeroTime ) {
          // Push new segment
         _segments.push_back( rcGraphicsSegment( nextSegmentStart(), segmentLength, _currentFocus, _currentValue ) );
     }
 }
rcWriter * rcGraphicsTrackImpl::down_cast () virtual
Implements rcGraphicsWriter.
Definition at line 251 of file rc_graphicstrackimpl.cpp.
 {
     return dynamic_cast<rcWriter*>( this );
 }
void rcGraphicsTrackImpl::flush (void) virtual
Implements rcGraphicsWriter.
Definition at line 241 of file rc_graphicstrackimpl.cpp.
References rcTrackImpl::_currentFocus, rcTrackImpl::_currentLength, _currentValue, rcTrackImpl::_mutex, addSegment(), rcTrackImpl::lastSegmentLength(), and setWriterState().
 {
     rcLock lock (_mutex);
     // Add final segment
     addSegment( lastSegmentLength() );
     // Update writer state
     setWriterState( _currentLength, _currentFocus, _currentValue );
 }
rcGraphicsSegmentIterator * rcGraphicsTrackImpl::getDataSegmentIterator (const rcTimestamp & pos) virtual
Implements rcGraphicsTrack.
Definition at line 213 of file rc_graphicstrackimpl.cpp.
References rcTrackImpl::_mutex, and rcGraphicsSegmentIteratorImpl.
 {
   return new rcGraphicsSegmentIteratorImpl( this , pos, _mutex );
 }
uint32 rcGraphicsTrackImpl::getSegmentCount (void) virtual
Implements rcGraphicsTrack.
Definition at line 219 of file rc_graphicstrackimpl.cpp.
References rcTrackImpl::_mutex, and _segments.
 {
     rcLock lock (_mutex);
     return _segments.size();
 }
void rcGraphicsTrackImpl::popSegment () virtual
Reimplemented from rcTrackImpl.
Definition at line 199 of file rc_graphicstrackimpl.cpp.
References _segments.
 {
     // We have hit the maximum size limit, we must prune oldest value
     // TODO: this wont work right until we use absolute timestamps instead of relative timestamps
     _segments.pop_front();
     // Try to compact container
     deque<rcGraphicsSegment>(_segments).swap(_segments);
 }
rcSegmentImpl rcGraphicsTrackImpl::segment (uint32 index) virtual
Reimplemented from rcTrackImpl.
Definition at line 190 of file rc_graphicstrackimpl.cpp.
References _segments, and cZeroTime.
 {
     if ( index < _segments.size() )
         return _segments[index];
     else
         return rcSegmentImpl( cZeroTime, cZeroTime, rcRect() );
 }
uint32 rcGraphicsTrackImpl::segments (void) virtual
Reimplemented from rcTrackImpl.
Definition at line 184 of file rc_graphicstrackimpl.cpp.
References _segments.
Referenced by rcGraphicsSegmentIteratorImpl::setCurrentValue().
 {
     return _segments.size();
 }
void rcGraphicsTrackImpl::setWriterState (rcTimestamp time, rcRect focus, const rcVisualGraphicsCollection & value) private
Definition at line 257 of file rc_graphicstrackimpl.cpp.
References _currentValue, and rcTrackImpl::setWriterState().
Referenced by flush(), and writeValue().
 {
     rcTrackImpl::setWriterState( time, focus );
     _currentValue = value;
 }
void rcGraphicsTrackImpl::writeValue (const rcTimestamp & timestamp, const rcRect & focus, const rcVisualGraphicsCollection & value) virtual
Implements rcGraphicsWriter.
Definition at line 228 of file rc_graphicstrackimpl.cpp.
References rcTrackImpl::_mutex, addSegment(), rcTrackImpl::nextSegmentLength(), setWriterState(), and rcTrackImpl::updateFirstTime().
 {
     rcLock lock (_mutex);
     // Update first value time
     updateFirstTime( timestamp );
     // Add new segment
     rcTimestamp length = nextSegmentLength( timestamp );
     addSegment( length );
     // Update writer state
     setWriterState( timestamp, focus, value );
 }
Friends And Related Function Documentation
friend class rcGraphicsSegmentIteratorImpl friend
Definition at line 86 of file rc_graphicstrackimpl.h.
Referenced by getDataSegmentIterator().
Member Data Documentation
rcVisualGraphicsCollection rcGraphicsTrackImpl::_currentValue private
Definition at line 95 of file rc_graphicstrackimpl.h.
Referenced by addSegment(), flush(), rcGraphicsTrackImpl(), and setWriterState().
deque<rcGraphicsSegment> rcGraphicsTrackImpl::_segments private
Definition at line 94 of file rc_graphicstrackimpl.h.
Referenced by addSegment(), getSegmentCount(), popSegment(), segment(), segments(), and rcGraphicsSegmentIteratorImpl::setCurrentValue().
The documentation for this class was generated from the following files:
include/visiCore/rc_graphicstrackimpl.h
src/visible/src/rc_graphicstrackimpl.cpp