Visible: rcWindow Class Reference
rcWindow Class Reference
#include <include/visual/rc_window.h>
Public Member Functions
rcWindow ()
default constructor takes no arguments
rcWindow (std::string absPath2TiffFile)
rcWindow (const rcWindow &other)
copy / assignment takes one arguments
const rcWindow & operator= (const rcWindow &rhs)
copy / assignment takes one arguments
rcWindow (rcVideoCache &cache, uint32 frameIndex)
rcWindow (rcSharedFrameBufPtr ptr, int32 x, int32 y, int32 width, int32 height)
rcWindow (rcSharedFrameBufPtr ptr, const rcIPair &icenter, const rcIPair &span, bool &withIn)
rcWindow (rcSharedFrameBufPtr ptr, const rcRect &cropRect)
rcWindow (rcSharedFrameBufPtr ptr)
rcWindow (const rcWindow &parentWindow, int32 x, int32 y, int32 width, int32 height, bool clip=false)
rcWindow (const rcWindow &parentWindow, int32 width, int32 height)
rcWindow (const rcWindow &parentWindow, const rcRect &cropRect, bool clip=false)
rcWindow (const rcWindow &parentWindow, const rcIRect &cropRect, int32 &isInside)
rcWindow (const rcWindow &parentWindow, const rcIPair &icenter, const rcIPair &span, bool &withIn)
rcWindow (int32 width, int32 height, rcPixel depth=rcPixel8)
rcWindow (const rcIPair &size, rcPixel depth=rcPixel8)
virtual ~rcWindow ()
const rcSharedFrameBufPtr & frameBuf () const
rcSharedFrameBufPtr & frameBuf ()
rcPixel depth () const
uint32 pixelCount () const
int32 n () const
bool isGray () const
bool isD32Float () const
int32 x () const
int32 y () const
int32 width () const
int32 height () const
const rcIPair & position () const
rcIPair position ()
rcIPair size () const
rcRect rcBound () const
rcIRect frame () const
const rcRect & rectangle () const
bool contains (const rcWindow &other) const
bool contains (const rcIRect &other) const
bool canPeekOutSide (const rcIPair range) const
bool contains (const uint8 *ptr) const
uint32 isBound () const
bool isWithin (int32 x, int32 y) const
isWithin / isWithin takes a position in the frameBuf coordinate
bool isWithin (const rcIPair &where) const
bool isWithin (const rcRect &rect) const
bool canTrim (int32 delta) const
canTrim / can takes a desired trim tba to all sides
void maxTrim (rcIPair &tl, rcIPair &br) const
int32 maxTrim () const
bool vImage (vImage_Buffer &) const
CGImageRef CGImage () const
int32 bits () const
int32 bytes () const
double operator() (double, double) const
uint32 getPixel (int32 x, int32 y) const
double getDoublePixel (int32 x, int32 y) const
uint32 getPixel (const rcIPair &where) const
double getDoublePixel (const rcIPair &where) const
const uint8 * rowPointer (int32 y) const
uint8 * rowPointer (int32 y)
const uint8 * pelPointer (int32 x, int32 y) const
uint8 * pelPointer (int32 x, int32 y)
int32 rowUpdate () const
int32 rowPixelUpdate () const
double zVal () const
bool sameTime (const rcWindow &other) const
rcTimestamp timestamp () const
rcWindow & windowRelativeTo (const rcWindow &parentWindow, int32 x, int32 y, int32 width, int32 height)
bool translate (const rcIPair &delta)
void entire ()
rcWindow & trim (uint32 delta)
bool trim (int32 delta)
bool trim (rcIPair delta)
uint32 setPixel (int32 x, int32 y, uint32 value)
double setDoublePixel (int32 x, int32 y, double value)
uint32 setPixel (const rcIPair &where, uint32 value)
double setDoublePixel (const rcIPair &where, double value)
rcWindow & copyPixelsFromWindow (const rcWindow &srcWindow, bool mirror=false)
rcWindow & set (double pixelValue)
rcWindow & setAllPixels (uint32 pixelValue)
rcWindow & setAllDoublePixels (double pixelValue)
void atTime (const rcWindow &other)
void zVal (double dv)
uint32 randomFill (uint32 seed=0)
void mirror ()
bool operator== (const rcWindow &) const
bool operator!= (const rcWindow &) const
bool contentCompare (const rcWindow &, bool verbose=false) const
bool contentMaskCompare (const rcWindow &, const rcWindow &mask) const
bool tiff (std::string &outfile, bool compress=false) const
template<class T >
void print (T, ostream &=cerr)
template<class T >
void print (T)
Protected Member Functions
void init (int32 w, int32 h, rcPixel depth)
bool window (const rcWindow &parentWindow, int32 x, int32 y, int32 width, int32 height, bool clip)
Protected Attributes
rcSharedFrameBufPtr mFrameBuf
rcRect mGeometry
Friends
ostream & operator<< (ostream &, const rcWindow &)
Detailed Description
Definition at line 24 of file rc_window.h.
Constructor & Destructor Documentation
rcWindow::rcWindow () inline
default constructor takes no arguments
Definition at line 32 of file rc_window.h.
Referenced by rcWindow(), and window().
 : mFrameBuf(NULL), mGeometry (0,0,0,0) {}
rcWindow::rcWindow (std::string absPath_filename)
From a Tiff File
Definition at line 213 of file rc_window.cpp.
References TIFFImageIO::CanReadFile(), rcWindow(), TIFFImageIO::ReadImageInformation(), and TIFFImageIO::ReadSinglePage().
 {
     // Get a TIFF Importer
     TIFFImageIO t_importer;
     if (! t_importer.CanReadFile (absPath_filename.c_str () ) )
         *this = rcWindow ();
     t_importer.SetFileName (absPath_filename.c_str ());
     t_importer.ReadImageInformation ();
     *this = t_importer.ReadSinglePage ();
 }
rcWindow::rcWindow (const rcWindow & other) inline
copy / assignment takes one arguments
Parameters
other Copy and assignment constructors increment the refcount
Definition at line 41 of file rc_window.h.
                                    :
     mFrameBuf( other.frameBuf() ),
mGeometry(other.x(), other.y(), other.width(), other.height()) {}
rcWindow::rcWindow (rcVideoCache & cache, uint32 frameIndex)
Definition at line 193 of file rc_window.cpp.
References eVideoCacheStatusOK, rcVideoCache::getFrame(), rcRectangle< T >::height(), mFrameBuf, mGeometry, rmAssert, and rcRectangle< T >::width().
                                                          :
         mFrameBuf(0), mGeometry(0, 0, cache.frameWidth(), cache.frameHeight())
 {
     rmAssert( mGeometry.width() > 0 );
     rmAssert( mGeometry.height() > 0 );
     rcVideoCacheStatus status =
         cache.getFrame(frameIndex, mFrameBuf, 0, false);
     rmAssert(status == eVideoCacheStatusOK);
}
rcWindow::rcWindow (rcSharedFrameBufPtr ptr, int32 x, int32 y, int32 width, int32 height)
Attach to an existing buffer takes up to four arguments
Parameters
ptr is a frame buffer pointer (ref counted)
icenter is a pair of integers indicating center position in the frame buffer
span is the span on each side. width & height are 2*span + 1
rcWindow::rcWindow (rcSharedFrameBufPtr ptr, const rcIPair & icenter, const rcIPair & span, bool & withIn)
rcWindow::rcWindow (rcSharedFrameBufPtr ptr, const rcRect & cropRect)
rcWindow::rcWindow (rcSharedFrameBufPtr ptr)
rcWindow::rcWindow (const rcWindow & parentWindow, int32 x, int32 y, int32 width, int32 height, bool clip = false)
Attach to an existing window takes up to four arguments
Parameters
ptr is a frame buffer pointer (ref counted)
icenter is a pair of integers indicating center position in the frame buffer
span is the span on each side. width & height are 2*span + 1
Definition at line 325 of file rc_window.cpp.
References rmUnused, and window().
 {
   bool what = window (parentWindow, x, y, width, height, clip);
   rmUnused (what);
 }
rcWindow::rcWindow (const rcWindow & parentWindow, int32 width, int32 height)
Definition at line 338 of file rc_window.cpp.
References rmUnused, and window().
 {
   bool what = window (parentWindow, 0, 0, width, height, false);
   rmUnused (what);
 }
rcWindow::rcWindow (const rcWindow & parentWindow, const rcRect & cropRect, bool clip = false)
Definition at line 331 of file rc_window.cpp.
References rcRectangle< T >::height(), rcRectangle< T >::origin(), rmUnused, rcRectangle< T >::width(), window(), rcPair< T >::x(), and rcPair< T >::y().
 {
   bool what = window (parentWindow, cropRect.origin().x(), cropRect.origin().y(),
               cropRect.width(), cropRect.height(), clip);
   rmUnused (what);
 }
rcWindow::rcWindow (const rcWindow & parentWindow, const rcIRect & cropRect, int32 & isInside)
Definition at line 345 of file rc_window.cpp.
References rcRectangle< T >::height(), rcRectangle< T >::origin(), rcRectangle< T >::width(), window(), rcPair< T >::x(), and rcPair< T >::y().
 {
   bool what = window (parentWindow, cropRect.origin().x(), cropRect.origin().y(),
               cropRect.width(), cropRect.height(), false);
   isInside = (int32) !what;
 }
rcWindow::rcWindow (const rcWindow & parentWindow, const rcIPair & icenter, const rcIPair & span, bool & withIn)
Definition at line 318 of file rc_window.cpp.
References window(), rcPair< T >::x(), and rcPair< T >::y().
 {
   bool what = window (parentWindow, icenter.x() - span.x(), icenter.y() - span.y() ,
               span.x()+span.x()+1, span.y()+span.y()+1, false);
   withIn = !what;
 }
rcWindow::rcWindow (int32 width, int32 height, rcPixel depth = rcPixel8)
Create a frameBuffer and become a entire window to its frameBuf takes up to four arguments
Parameters
size is a pair of integers indicating size of the to be created frame buffer
depth is the the pixel depth of the to be created framebuf
Definition at line 238 of file rc_window.cpp.
References init().
 {
     init (width, height, depth);
 }
rcWindow::rcWindow (const rcIPair & size, rcPixel depth = rcPixel8)
Definition at line 243 of file rc_window.cpp.
References depth(), init(), rmAssert, rcPair< T >::x(), and rcPair< T >::y().
 {
     rmAssert (size.x() >= 0);
     rmAssert (size.y() >= 0);
     init (size.x(), size.y(), depth);
 }
virtual rcWindow::~rcWindow () inline virtual
Definition at line 97 of file rc_window.h.
 {  }
Member Function Documentation
void rcWindow::atTime (const rcWindow & other) inline
Definition at line 246 of file rc_window.h.
References frameBuf(), and rcFrame::timestamp().
Referenced by rcSpatialPyramid< 2 >::intensityProcess().
   {
     frameBuf()->setTimestamp(other.frameBuf()->timestamp());
   }
int32 rcWindow::bits (void) const
Definition at line 702 of file rc_window.cpp.
References bytes().
Referenced by CGImage(), rfDirectionSignal(), rfImageConvert168(), and sobelEdgeProcess().
 {
   return (bytes () * 8);
 }
int32 rcWindow::bytes (void) const
Definition at line 707 of file rc_window.cpp.
References depth().
Referenced by bits().
 {
   return ((int32)depth());
 }
bool rcWindow::canPeekOutSide (const rcIPair range) const
Definition at line 712 of file rc_window.cpp.
References contains(), mGeometry, rmExceptionMacro, rcRectangle< T >::trim(), rcPair< T >::x(), and rcPair< T >::y().
 {
   if (range.x() < 0 || range.y() < 0)
     rmExceptionMacro (<< "Window Geometry Error");
   // Try growing it to see if we can use the frameBuf
   rcRect expanded = mGeometry.trim (-range.x(), -range.x(), -range.y(), -range.y());
   return contains (expanded);
 }
bool rcWindow::canTrim (int32 delta) const
canTrim / can takes a desired trim tba to all sides
Parameters
delta returns if the window can be trimmed in the framebuf by delta
Definition at line 405 of file rc_window.cpp.
References rcFrame::height(), rcRectangle< T >::height(), mFrameBuf, mGeometry, rcFrame::width(), rcRectangle< T >::width(), rcRect::x(), x(), rcRect::y(), and y().
 {
     int32 x, y, w, h;
     bool flag = false;
     x = mGeometry.x() + delta;
     y = mGeometry.y() + delta;
     w = mGeometry.width() - 2 * delta;
     h = mGeometry.height() - 2 * delta;
     flag = (x >= 0 && w > 0 && (x+w-1) < (mFrameBuf->width()) &&
         h > 0 && y >= 0 && (y+h-1) < (mFrameBuf->height()));
     return flag;
 }
CGImageRef rcWindow::CGImage () const
Returns CGImage rep of the window
Returns
CGImageRef for the new image. (Remember to release it when finished with it.)
Note
CGBitmapInfo bmpInfo = imageCopy->hasAlphaBuffer() ? kCGImageAlphaFirst : kCGImageAlphaNoneSkipFirst;
Definition at line 972 of file rc_window.cpp.
References bits(), depth(), frameBuf(), height(), NULL, position(), rcPixel32, rmAssert, rmExceptionMacro, rowPointer(), rowUpdate(), width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rfImageExport2JPG().
 {
     CGDataProviderRef provider = NULL;
     rcWindow root (frameBuf(), 0, 0, frameBuf()->width(), frameBuf()->height());
     CGColorSpaceRef colorSpace;
     CGImageRef rootImage, imageWin;
     CGBitmapInfo alphaInfo = kCGImageAlphaFirst;
     void  *bitmapData = (void *) root.rowPointer (0);
     int    bitmapBytesPerRow = ( root.rowUpdate ());
     colorSpace = depth () == rcPixel32 ? CGColorSpaceCreateDeviceRGB () : CGColorSpaceCreateDeviceGray();
     // Create a data provider with a pointer to the memory bits
     provider = CGDataProviderCreateWithData(NULL, bitmapData, bitmapBytesPerRow * root.height(), NULL);
     if (NULL == provider)
         rmExceptionMacro(<< "rcWindow::CGImage exporter not available ");
     // Create the root image
     rootImage = CGImageCreate(root.width(), root.height (), 8, root.bits (),bitmapBytesPerRow, colorSpace, alphaInfo, provider,
                                                 NULL, false, kCGRenderingIntentDefault);
     // rcWindows are refCounted ectangular regions in the root image
     float x = (float) position().x(); float y =  (float) position().y();
     float w = (float) width(); float h =  (float) height ();
     imageWin = CGImageCreateWithImageInRect (rootImage, CGRectMake (x, y, w, h));
     CGColorSpaceRelease (colorSpace);
     CGDataProviderRelease (provider);
     rmAssert (imageWin);
     return imageWin;
 }
bool rcWindow::contains (const rcWindow & other) const
Definition at line 760 of file rc_window.cpp.
References rcRectangle< T >::contains(), isBound(), mFrameBuf, mGeometry, and rectangle().
Referenced by canPeekOutSide(), rcDrawPolygon(), and rcFillPolygon().
 {
   return (isBound() && other.isBound() && mFrameBuf == other.mFrameBuf && mGeometry.contains (other.rectangle()));
 }
bool rcWindow::contains (const rcIRect & other) const inline
Definition at line 128 of file rc_window.h.
{
     return (isBound() && mGeometry.contains (other));
   }
bool rcWindow::contains (const uint8 * ptr) const
Definition at line 264 of file rc_window.cpp.
References height(), isBound(), pelPointer(), rmAssert, and rowUpdate().
 {
     if (!isBound()) return 0;
     rmAssert(rowUpdate() > 0);
     const uint8 *pels = pelPointer (0,0);
     if ((ptr - pels) < 0) return 0;
     int32 y = (ptr - pels) / rowUpdate();
     int32 x = (ptr - pels) % rowUpdate();
     return ((x >= 0) && (x < width()) && (y >= 0) && (y < height()));
 }
bool rcWindow::contentCompare (const rcWindow & other, bool verbose = false) const
Definition at line 865 of file rc_window.cpp.
References depth(), isBound(), isD32Float(), PIXELCOMPARE, PIXELCOMPAREVERBOSE, PIXELEQUAL, rcPixel16, rcPixel32, rcPixel8, rmExceptionMacro, and size().
     {
         if (!isBound()) return false;
         if (!other.isBound()) return false;
         if (depth() != other.depth()) return false;
         if (size() != other.size()) return false;
         if (isD32Float() && other.isD32Float())
         {
             switch (depth())
             {
                 PIXELEQUAL(rcPixel32, float*, 0.1f);
                 default:
                 rmExceptionMacro ("Pixel Type Not Implemented");
             }
         }
         if (! verbose)
         {
             switch (depth())
             {
                 PIXELCOMPARE(rcPixel8, uint8*);
                 PIXELCOMPARE(rcPixel16, uint16*);
                 PIXELCOMPARE(rcPixel32, uint32*);
                 default:
                 rmExceptionMacro ("Pixel Type Not Implemented");
             }
         }
         else
         {
                 switch (depth())
                 {
                     PIXELCOMPAREVERBOSE(rcPixel8, uint8*);
                     PIXELCOMPAREVERBOSE(rcPixel16, uint16*);
                     PIXELCOMPAREVERBOSE(rcPixel32, uint32*);
                     default:
                     rmExceptionMacro ("Pixel Type Not Implemented");
                 }
         }
     }
bool rcWindow::contentMaskCompare (const rcWindow & other, const rcWindow & mask) const
Definition at line 906 of file rc_window.cpp.
References depth(), isBound(), MASKEDPIXELCOMPARE, rcPixel16, rcPixel32, rcPixel8, rmAssert, rmExceptionMacro, and size().
 {
   if (!isBound()) return false;
   if (!other.isBound()) return false;
   if (!mask.isBound()) return false;
   if (depth() != other.depth()) return false;
   if (size() != other.size()) return false;
   if (size() != mask.size()) return false;
   rmAssert (mask.depth() == rcPixel8);
   switch (depth())
     {
       MASKEDPIXELCOMPARE(rcPixel8, uint8*,uint8*);
       MASKEDPIXELCOMPARE(rcPixel16, uint16*,uint8*);
       MASKEDPIXELCOMPARE(rcPixel32, uint32*,uint8*);
     default:
     rmExceptionMacro ("Pixel Type Not Implemented");
     }
 }
rcWindow & rcWindow::copyPixelsFromWindow (const rcWindow & srcWindow, bool mirror = false)
Definition at line 420 of file rc_window.cpp.
References depth(), height(), rmExceptionMacro, rmMin, rowPointer(), and width().
Referenced by rcVisualFunction::cardiacUpdate(), rcMovieConverter::clippedFrame(), copyImage(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcKinetoscope::debugScreen(), rcMuscleSegmenter::debugWrite(), rcMuscleSegmenter::filterByActivity(), rcMuscleSegmenter::getCells(), main(), rfCopyWindowBorder(), segment(), rcMuscleSegmenter::segment(), rcSimilarator::setMask(), and rcVisualFunction::updateSims().
 {
   if (srcWindow.depth() != depth())
     rmExceptionMacro(<< "IP Window::mismatch");
     const int32 rowCount = rmMin(height(), srcWindow.height());
     const int32 rowLth = rmMin(width(), srcWindow.width()) * depth();
     // Note: lastRow is not rowCount - 1 but height() - 1. This does not matter if the
     // images are the same size or src is bigger but when the destination is larger
     // it copies from height() - srcWindow.height().
     if ( mirror ) {
         // Mirror vertically
         const int32 lastRow = height()-1;
         for (int32 row = 0; row < rowCount; row++)
             bcopy(srcWindow.rowPointer(row), rowPointer(lastRow-row), rowLth);
     } else {
         for (int32 row = 0; row < rowCount; row++)
             bcopy(srcWindow.rowPointer(row), rowPointer(row), rowLth);
     }
     return *this;
 }
rcPixel rcWindow::depth () const inline
Definition at line 103 of file rc_window.h.
Referenced by _rfRcWindow32to8(), rcGenMovieFile::addFrame(), rcEngineImpl::analyzeFocusArea(), binarize(), binarizeFloatWindow(), rcImageCanvasGL::buildImageDlist(), bytes(), CGImage(), rcRowFuncTwoSource< T >::checkAssigned(), rcRowFuncOneSourceOneDestination< T >::checkAssigned(), contentCompare(), contentMaskCompare(), copyImage(), copyPixelsFromWindow(), correlate16a32(), rcMovieConverterToRfy::createRfyMovie(), rcKinetoscope::debugScreen(), rcOptoKineticImage::decrementU8(), rcCorrelationWindow< uint8 >::depth(), rcKinetoscope::epiMotionField(), rcOptoKineticImage::gen1DCorrKineticImgs(), rcCubicGeneratePixel::gen2D2ndD(), rcCubicGeneratePixel::gen2ndD(), rcOptoKineticImage::genAccelEntropyImg(), rcOptoKineticImage::genDFT(), rcOptoKineticImage::genEightBitDFT(), rcOptoKineticImage::genEightBitFreq(), rcOptoKineticImage::genEightBitImg(), rcOptoKineticImage::genFreqImg(), rcDefGenerateImage::genImage(), rcOptoKineticImage::genKineticStats(), rcOptoKineticImage::genLogRMS(), rcLinGeneratePixel::genPixel(), rcDefGeneratePixel::genPixel(), genSpatialSDImg(), genSpatialSDSum(), rcOptoKineticImage::genStdDevImg(), rcOptoKineticImage::genThetaEntropyImg(), rcOptoKineticImage::genVarImg(), rcOptoKineticImage::genVelEntropyImg(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rcSpatialPyramid< 2 >::gradientProcess(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcOptoKineticImage::incrementU8(), rcGenMovieFile::initHeader(), rcSpatialPyramid< 2 >::intensityProcess(), rcCubicGeneratePixel::interpolate(), rcEngineImpl::ipp(), rcEngineImpl::loadFrames(), rcImageCanvasGL::loadrcWindow(), main(), rcMotionVectorPath::match(), mirror(), rcMathematicalImage::mMakeField(), rcMathematicalImage::mMakeImage(), rcEngineImpl::modelTracker(), operator<<(), rcMotionVectorPath::parabolicDisparity(), rcOptoKineticImage::push(), randomFill(), rcCorrelationWindow< uint8 >::rcCorrelationWindow(), rcHistoStats::rcHistoStats(), rcLabelRLE::rcLabelRLE(), rcSpatialPyramid< 2 >::rcSpatialPyramid(), rcWindow(), rfAndImage(), rfCorrelate(), rfDetectPeaks(), rfDirectionSignal(), rfGauss3(), rfGaussianConv(), rfGen1DMomentIntegrals(), rfGen2DIMIntegrals(), rfGen2DIMIntegralsFast(), rfGen2DMomentIntegrals(), rfGen2DMomentIntegralsFast(), rfGenDepth8Histogram(), rfGetComponents(), rfGetRects(), rfImage8Integrals(), rfImageAddMask(), rfImageConvert168(), rfImageConvert32to8(), rfImageConvert8to32(), rfImageConvert8ToARGB(), rfImageFileToRcWindow(), rfImageGradientToVisualSegment(), rfImageIntegrals(), rfImageOrthogonalProjections(), rfImagePairMaskNeq(), rfImagePairMax(), rfImagePairMin(), rfImageVerticalReflect(), rfMutualChannel(), rfPeakDetect8Bit(), rfPixel8Map(), rfPixelMax3By3(), rfPixelMin3By3(), rfRcWindow8to32(), rfReversePixels16(), rfReversePixels8(), rfRLEstimate(), rfSetWindowBorder(), rfSobel(), rfSobelEdge(), rfSpatialEdge(), rfTemporalMedian(), rfTemporalMedianPixel16(), rfTemporalMedianPixel8(), rfWindow8to32(), segPoint(), segPointByEnergy(), rcKinetoscope::selfSimilarMotionField_AttentiveCapture(), set(), setAllPixels(), rcSimilarator::setMask(), rcImageCanvasGL::statusString(), rcLatticeSimilarator::ttc(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), and rcGenMovieFile::write().
 { return mFrameBuf->depth(); }
void rcWindow::entire ()
Definition at line 722 of file rc_window.cpp.
References rcFrame::height(), mFrameBuf, mGeometry, rmAssert, rcFrame::width(), rcRect::x(), and rcRect::y().
 {
   mGeometry = rcRect (0, 0, mFrameBuf->width(), mFrameBuf->height());
   rmAssert( mGeometry.x() < mFrameBuf->width() );
   rmAssert( mGeometry.y() < mFrameBuf->height() );
 }
rcIRect rcWindow::frame () const inline
Definition at line 120 of file rc_window.h.
References rmAssert.
Referenced by maxTrim().
                          { rmAssert (isBound());
     return rcIRect (0, 0, mFrameBuf->width(), mFrameBuf->height()); }
const rcSharedFrameBufPtr& rcWindow::frameBuf () const inline
Definition at line 100 of file rc_window.h.
Referenced by rcGenMovieFile::addFrame(), rcEngineImpl::analyzeFocusArea(), atTime(), rcImageCanvasGL::buildImageDlist(), CGImage(), rcRowFuncTwoSource< T >::checkAssigned(), rcKinetoscope::connectedFunctions(), copyImage(), rcSimilarator::fill(), rcCorrelationWindow< uint8 >::frameBuf(), rcAutoCorrelation::genCache(), rcAutoCorrelation::genPoint(), rcImageGrabber::getNextFrame(), rcMovieGrabber::getNextFrame(), rcGenMovieFile::initHeader(), rcSimilarator::internalUpdate(), rcEngineImpl::ipp(), rcEngineImpl::muscleTracker(), operator=(), rcShape::operator==(), rcKinetoscope::resultTime(), rfImageACfield(), rfImageConvert8to32(), rfIsWhiteReversed(), rfRcWindow8to32(), rfReversePixels16(), rfReversePixels8(), sameTime(), rcImageCanvasGL::statusString(), and yourDisplayCallback().
 { return mFrameBuf; }
rcSharedFrameBufPtr& rcWindow::frameBuf () inline
Definition at line 101 of file rc_window.h.
 { return mFrameBuf; }
double rcWindow::getDoublePixel (int32 x, int32 y) const
Definition at line 772 of file rc_window.cpp.
References rcFrame::getDoublePixel(), isBound(), mFrameBuf, mGeometry, rmExceptionMacro, rcRect::x(), and rcRect::y().
Referenced by rcLinGeneratePixel::genPixel(), rcDefGeneratePixel::genPixel(), getDoublePixel(), rcCubicGeneratePixel::interpolate(), and operator<<().
   {
   if (x < 0 || y < 0 || !isBound())
     rmExceptionMacro ("Window Geometry Error");
     double r = mFrameBuf->getDoublePixel (x + mGeometry.x (), y + mGeometry.y ());
     return r;
   }
double rcWindow::getDoublePixel (const rcIPair & where) const
Definition at line 658 of file rc_window.cpp.
References getDoublePixel(), rcPair< T >::x(), and rcPair< T >::y().
 {
   return getDoublePixel (where.x(), where.y());
 }
uint32 rcWindow::getPixel (int32 x, int32 y) const
Definition at line 765 of file rc_window.cpp.
References rcFrame::getPixel(), isBound(), mFrameBuf, mGeometry, rmExceptionMacro, rcRect::x(), and rcRect::y().
Referenced by rcMutualInfo::add(), rcMuscleTracker::calculateCellLocation(), rcMuscleTracker::genEdgePoints(), rcEdgeFilter1D::genPeaks(), rcLinGeneratePixel::genPixel(), rcDefGeneratePixel::genPixel(), getPixel(), rcCubicGeneratePixel::interpolate(), operator<<(), rcDefGenerateImage::project(), rc_fill_poly(), rcGaussKernel2D< T, ksize >::rcGaussKernel2D(), rfCorrelate(), rfCverAndImages(), rfImageIntegrals(), rcSimilarator::setMask(), and rcImageCanvasGL::statusString().
   {
   if (x < 0 || y < 0 || !isBound())
     rmExceptionMacro ("Window Geometry Error");
     return mFrameBuf->getPixel (x + mGeometry.x (), y + mGeometry.y ());
   }
uint32 rcWindow::getPixel (const rcIPair & where) const
Definition at line 653 of file rc_window.cpp.
References getPixel(), rcPair< T >::x(), and rcPair< T >::y().
 {
   return getPixel (where.x(), where.y());
 }
int32 rcWindow::height () const inline
Definition at line 113 of file rc_window.h.
Referenced by _exhaustiveImageFind(), _rfRcWindow32to8(), rcMutualInfo::add(), rcGenMovieFile::addFrame(), binarize(), binarizeFloatWindow(), rcSegmentationLevel::binaryImage(), rcImageCanvasGL::buildImageDlist(), rcMuscleTracker::calculateCellLocation(), rcVisualFunction::cardiacUpdate(), CGImage(), contains(), copyImage(), copyPixelsFromWindow(), rcOptoKineticImage::decrementU8(), rcVisualFunction::dividingProcess(), rcSimilarator::fill(), rcMuscleSegmenter::filterAtEdge(), rcMuscleSegmenter::filterByActivity(), rcMuscleSegmenter::filterByAR(), rcMuscleSegmenter::filterBySize(), gaussEdge(), rcOptoKineticImage::gen1DCorrKineticImgs(), rcCubicGeneratePixel::gen2D2ndD(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcOptoKineticImage::genAccelEntropyImg(), rcOptoKineticImage::genDFT(), rcMuscleTracker::genEdgePoints(), rcOptoKineticImage::genEightBitDFT(), rcOptoKineticImage::genEightBitFreq(), rcOptoKineticImage::genEightBitImg(), generateExpansionMovie(), generateRandomMovie(), generateTranslationMovie(), rcOptoKineticImage::genFreqImg(), rcOptoKineticImage::genKineticStats(), rcOptoKineticImage::genLogRMS(), rcLinGeneratePixel::genPixel(), rcAutoCorrelation::genPoint(), rcMuscleTracker::genSpace(), rcPointCorrelation::genSpace(), genSpatialSDImg(), genSpatialSDSum(), rcOptoKineticImage::genStdDevImg(), rcMomentGenerator::genSumSumSq1D(), rcMomentGenerator::genSumSumSq2D(), rcMomentGenerator::genSumSumSq2DFast(), rcOptoKineticImage::genThetaEntropyImg(), rcOptoKineticImage::genVarImg(), rcOptoKineticImage::genVelEntropyImg(), rcMuscleSegmenter::getCells(), rcSpatialPyramid< 2 >::gradientProcess(), rcCorrelationWindow< uint8 >::height(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcLabelRLE::image2runs(), rcOptoKineticImage::incrementU8(), rcSpatialPyramid< 2 >::intensityProcess(), rcImageCanvasGL::loadrcWindow(), mirror(), rcMathematicalImage::mMakeField(), rcMathematicalImage::mMakeImage(), rcEngineImpl::modelTracker(), operator<<(), rcEngineImpl::postTrackingResults(), rcShape::project(), rcShape::projectMI(), rcOptoKineticImage::push(), randomFill(), rc_fill_poly(), rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc(), rcDrawLine(), rcGaussKernel2D< T, ksize >::rcGaussKernel2D(), rcHistoStats::rcHistoStats(), rcLabelRLE::rcLabelRLE(), rcSpatialPyramid< 2 >::rcSpatialPyramid(), rcSpatialPyramid< 2 >::region(), rcKinetoscope::reichardt(), rf_SetWindowBorder(), rfAndImage(), rfCompareMovies(), rfCopyWindowBorder(), rfCorrelate(), rfCubicShiftImage(), rfCverAndImages(), rfDetectPeaks(), rfDirectionSignal(), rfDrawCircle(), rfGauss163by3(), rfGauss3(), rfGauss3by3(), rfGaussianConv(), rfGen1DMomentIntegrals(), rfGen2DIMIntegrals(), rfGen2DIMIntegralsFast(), rfGen2DMomentIntegrals(), rfGen2DMomentIntegralsFast(), rfGenDepth8Histogram(), rfGetComponents(), rfGetRects(), rfGradientImageToVisualSegment(), rfHysteresisThreshold(), rfImage8Integrals(), rfImage8Transpose(), rfImageACfield(), rfImageAddMask(), rfImageConvert168(), rfImageConvert32to8(), rfImageConvert816(), rfImageConvert8888ToARGB(), rfImageConvert8to32(), rfImageConvert8ToARGB(), rfImageConvertARGBto8888(), rfImageConvertFloat8(), rfImageGradientToVisualSegment(), rfImageIntegrals(), rfImageOrthogonalProjections(), rfImagePairMaskNeq(), rfImagePairMax(), rfImagePairMin(), rfImageVerticalReflect(), rfMedian(), rfMedian3By3Depth8(), rfMutualChannel(), rfPeakDetect8Bit(), rfPeakDetectAsym8Bit(), rfPixel8Max3By3(), rfPixel8Min3By3(), rfPixelExpand(), rfPixelMax3By3(), rfPixelMin3By3(), rfPixelSample(), rfPrintCorrSpace(), rfRcWindow8to32(), rfReversePixels16(), rfReversePixels8(), rfRLEstimate(), rfSetWindowBorder(), rfSobel(), rfSobelEdge(), rfSpatialEdge(), rfSurfaceHessian(), rfTemporalMedian(), rfTemporalMedianPixel16(), rfTemporalMedianPixel8(), rfWindow8to32(), segment(), rcMuscleSegmenter::segment(), segPoint(), segPointByEnergy(), set(), setAllDoublePixels(), setAllPixels(), rcShape::setMask(), rcSimilarator::setMask(), sobelEdgeProcess(), translate(), trim(), rcPointCorrelation::update(), rcMomentGenerator::update(), rcVisualFunction::updateSims(), rcAffineWindow::vImageTransform(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), window(), and rcGenMovieFile::write().
 { return mGeometry.height(); }
void rcWindow::init (int32 w, int32 h, rcPixel depth) protected
Definition at line 250 of file rc_window.cpp.
References rcFrame::height(), mFrameBuf, mGeometry, rcFrameBufPtr, rmAssert, rmExceptionMacro, and rcFrame::width().
Referenced by rcWindow().
 {
   if ( width <= 0 || height <= 0)
       {
     rmExceptionMacro(<< "IP Window::init");
       }
     rcFrameBufPtr ptr = new rcFrame( width, height, depth );
     mFrameBuf = ptr;
     mGeometry = rcRect (0, 0, width, height);
     rmAssert( (width - 1) < mFrameBuf->width() );
     rmAssert( (height - 1) < mFrameBuf->height() );
 }
uint32 rcWindow::isBound () const inline
Definition at line 139 of file rc_window.h.
Referenced by _exhaustiveImageFind(), rcImageCanvasGL::buildImageDlist(), contains(), contentCompare(), contentMaskCompare(), copyImage(), rcKinetoscope::createFunctionSpecificObjects(), rcMuscleSegmenter::filterByActivity(), rcMuscleTracker::genEdgePoints(), getDoublePixel(), getPixel(), rcImageCanvasGL::initializeGL(), rcImageCanvasGL::loadrcWindow(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcShape::needCenterOfmass(), rcShape::profiles(), rcDefGenerateImage::project(), rcShape::project(), rcShape::rcShape(), rcSpatialPyramid< 2 >::rcSpatialPyramid(), rfDirectionSignal(), rfGetRects(), rfHysteresisThreshold(), rfImage8Integrals(), rfImage8Transpose(), rfImageACfield(), rfImageAddMask(), rfImageConvert168(), rfImageConvert32to8(), rfImageConvert816(), rfImageConvert8888ToARGB(), rfImageConvert8ToARGB(), rfImageConvertARGBto8888(), rfImageConvertFloat8(), rfImageIntegrals(), rfImageOrthogonalProjections(), rfImagePairMaskNeq(), rfImagePairMax(), rfImagePairMin(), rfImageVerticalReflect(), rfMedian(), rfMedian3By3Depth8(), rfMutualChannel(), rfPixel8Map(), rfPixel8Max3By3(), rfPixel8Min3By3(), rfPixelExpand(), rfPixelMax3By3(), rfPixelMin3By3(), rfPixelSample(), rfRLEstimate(), rfSobel(), rfSpatialEdge(), rfTemporalMedian(), segment(), setDoublePixel(), setPixel(), rcImageCanvasGL::statusString(), rcLatticeSimilarator::ttc(), rcPointCorrelation::update(), vImage(), and window().
 { return mFrameBuf != 0; }
bool rcWindow::isD32Float () const inline
Definition at line 107 of file rc_window.h.
Referenced by contentCompare(), rcMathematicalImage::mMakeField(), rfGaussianConv(), rfSetWindowBorder(), and set().
 { return mFrameBuf->isD32Float(); }
bool rcWindow::isGray () const inline
Definition at line 106 of file rc_window.h.
Referenced by _rfRcWindow32to8(), rcImageCanvasGL::buildImageDlist(), rcEngineImpl::ipp(), rfImageConvert32to8(), rfMutualChannel(), and rcImageCanvasGL::statusString().
 { return mFrameBuf->isGray(); }
bool rcWindow::isWithin (int32 x, int32 y) const inline
isWithin / isWithin takes a position in the frameBuf coordinate
Parameters
rhs return if the point is in this window
Definition at line 146 of file rc_window.h.
Referenced by rcImageCanvasGL::mousePanEvent(), rcAffineWindow::rcAffineWindow(), rcMotionVectorPath::reconcile(), and rcImageCanvasGL::statusString().
 { rcIPair where (x, y); return (mGeometry.contains (where)); }
bool rcWindow::isWithin (const rcIPair & where) const inline
Definition at line 147 of file rc_window.h.
 { return (mGeometry.contains (where)); }
bool rcWindow::isWithin (const rcRect & rect) const inline
Definition at line 148 of file rc_window.h.
 { return (mGeometry.contains (rect)); }
void rcWindow::maxTrim (rcIPair & tl, rcIPair & br) const
Definition at line 392 of file rc_window.cpp.
References frame(), position(), size(), and rcRectangle< T >::size().
 {
   tl = position ();
   br = frame().size()  - size();
 }
int32 rcWindow::maxTrim () const
Definition at line 398 of file rc_window.cpp.
References rmMin, rcPair< T >::x(), and rcPair< T >::y().
 {
   rcIPair tl, br;
   maxTrim (tl, br);
   return rmMin (rmMin (tl.x(), tl.y()), rmMin (br.x(), br.y()));
 }
void rcWindow::mirror ()
Definition at line 446 of file rc_window.cpp.
References depth(), height(), rowPointer(), and width().
 {
     const int32 mid = height()/2;
     const int32 lastRow = height()-1;
     const int32 rowLen = width() * depth();
     uint8 tmp[rowLen];
     for (int32 row = 0; row < mid; row++) {
         // Swap two rows
         bcopy( rowPointer(row), tmp, rowLen );
         bcopy( rowPointer(lastRow-row), rowPointer(row), rowLen );
         bcopy( tmp, rowPointer(lastRow-row), rowLen );
     }
 }
int32 rcWindow::n () const inline
Definition at line 105 of file rc_window.h.
 { return mGeometry.width () * mGeometry.height (); }
bool rcWindow::operator!= (const rcWindow & other) const
Definition at line 697 of file rc_window.cpp.
References mFrameBuf, and mGeometry.
 {
   return (mFrameBuf != other.mFrameBuf || mGeometry != other.mGeometry);
 }
double rcWindow::operator() (double xDb, double yDb) const
Definition at line 647 of file rc_window.cpp.
References mFrameBuf, mGeometry, rcRect::x(), and rcRect::y().
 {
   return mFrameBuf->operator () (xDb + mGeometry.x(), yDb + mGeometry.y());
 }
const rcWindow& rcWindow::operator= (const rcWindow & rhs) inline
copy / assignment takes one arguments
Parameters
rhs Copy and assignment constructors increment the refcount
Definition at line 50 of file rc_window.h.
References frameBuf(), and rcBound().
   {
     if (this == &rhs) return *this;
     mFrameBuf = rhs.frameBuf();
     mGeometry = rhs.rcBound ();
     return *this;
   }
bool rcWindow::operator== (const rcWindow & other) const
Definition at line 692 of file rc_window.cpp.
References mFrameBuf, and mGeometry.
 {
   return (mFrameBuf == other.mFrameBuf && mGeometry == other.mGeometry);
 }
const uint8 * rcWindow::pelPointer (int32 x, int32 y) const
Definition at line 150 of file rc_window.cpp.
References mFrameBuf, mGeometry, rcFrame::pelPointer(), rmAssertDebug, rcRect::x(), and rcRect::y().
Referenced by _exhaustiveImageFind(), rcKinetoscope::canonicalMotionField(), contains(), rcKinetoscope::epiMotionField(), rcCorrelationWindow< uint8 >::pelPointer(), rcLabelRLE::rcLabelRLE(), rcMotionVectorPath::reconcile(), rfCubicShiftImage(), rfDetectPeaks(), rfGradientImageToVisualSegment(), rfImage8Integrals(), rfImage8Transpose(), rfImageIntegrals(), rfImageOrthogonalProjections(), rfMutualChannel(), rfPixel8Max3By3(), rfPixel8Min3By3(), rfPixelExpand(), rfPixelSample(), rfPrintCorrSpace(), rfRLEstimate(), rcKinetoscope::selfSimilarMotionField_AttentiveCapture(), and vImage().
   {
     rmAssertDebug( x >= 0 && y >= 0 );
     return (mFrameBuf->pelPointer (x + mGeometry.x(), y + mGeometry.y()));
   }
uint8 * rcWindow::pelPointer (int32 x, int32 y)
Definition at line 156 of file rc_window.cpp.
References mFrameBuf, mGeometry, rcFrame::pelPointer(), rmAssertDebug, rcRect::x(), and rcRect::y().
 {
   rmAssertDebug( x >= 0 && y >= 0 );
   return (mFrameBuf->pelPointer (x + mGeometry.x(), y + mGeometry.y()));
 }
uint32 rcWindow::pixelCount () const inline
Definition at line 104 of file rc_window.h.
Referenced by rfSurfaceHessian().
 { return mGeometry.width () * mGeometry.height (); }
const rcIPair& rcWindow::position (void) const inline
Definition at line 115 of file rc_window.h.
Referenced by rcVisualFunction::cardiacMeasure(), CGImage(), maxTrim(), rcShape::operator==(), and rfRegisteredWindows().
 { return mGeometry.origin(); }
rcIPair rcWindow::position (void) inline
Definition at line 116 of file rc_window.h.
 { return rcIPair (mGeometry.origin()); }
template<class T > void rcWindow::print (T , ostream & o = cerr)
Definition at line 321 of file rc_window.h.
References endl().
 {
   o << endl;
   for (int32 j = 0; j < height(); j++)
     {
       for (int32 i = 0; i < width(); i++)
     {
       o <<  getPixel (i, j);
       if (i < width() - 1)
         o << " ";
     }
       o << endl;
     }
   //  return o;
 }
template<class T > void rcWindow::print (T)
uint32 rcWindow::randomFill (uint32 seed = 0)
Definition at line 612 of file rc_window.cpp.
References depth(), getTimestampResolution(), height(), rcTimestamp::now(), rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, rowPointer(), rcTimestamp::secs(), setDoublePixel(), setPixel(), and width().
 {
     if ( seed == 0 ) {
         // Set a seed from two clocks
         const rcTimestamp now = rcTimestamp::now();
         const uint32 secs = uint32(now.secs());
         const float s = (now.secs() - secs) / getTimestampResolution();
         seed = uint32( s + clock() );
     }
     // TODO: is this thread-safe? Probably not
     srandom( seed );
     if (depth() == rcPixel8)
         for (int32 j = 0; j < height(); j++) {
             uint8 *oneRow = rowPointer (j);
             for (int32 i = 0; i < width(); ++i, ++oneRow)
                 *oneRow = uint8(random ());
         }
     else if (depth() == rcPixel16)
         for (int32 j = 0; j < height(); j++)
             for (int32 i = 0; i < width(); i++)
                 setPixel (i, j, uint32 (uint16 (random ())));
     else if (depth() == rcPixel32)
         for (int32 j = 0; j < height(); j++)
             for (int32 i = 0; i < width(); i++)
                 setPixel (i, j, uint32 (random ()));
     else if (depth() == rcPixelDouble)
         for (int32 j = 0; j < height(); j++)
             for (int32 i = 0; i < width(); i++)
                 setDoublePixel (i, j, random ());
     return seed;
 }
rcRect rcWindow::rcBound () const inline
Definition at line 119 of file rc_window.h.
Referenced by operator=().
 { return mGeometry; }
const rcRect& rcWindow::rectangle () const inline
Definition at line 122 of file rc_window.h.
Referenced by rcVisualFunction::cardiacMeasure(), contains(), rcShape::orthogonalBoundingBox(), rcShape::profiles(), and rcDbDtParams::validate().
 { return mGeometry; }
int32 rcWindow::rowPixelUpdate () const inline
Definition at line 187 of file rc_window.h.
Referenced by gaussEdge(), rfGauss163by3(), rfGauss3by3(), rfImageIntegrals(), and sobelEdgeProcess().
 { return mFrameBuf->rowPixelUpdate (); }
const uint8 * rcWindow::rowPointer (int32 y) const
Definition at line 138 of file rc_window.cpp.
References rcFrame::depth(), mFrameBuf, mGeometry, rmAssertDebug, rcFrame::rowPointer(), rcRect::x(), and rcRect::y().
Referenced by _rfRcWindow32to8(), rcMutualInfo::add(), rcMPEG2Grabber::add_frame(), binarize(), binarizeFloatWindow(), CGImage(), copyPixelsFromWindow(), rcOptoKineticImage::decrementU8(), gaussEdge(), rcOptoKineticImage::gen1DCorrKineticImgs(), rcCubicGeneratePixel::gen2ndD(), rcOptoKineticImage::genAccelEntropyImg(), rcOptoKineticImage::genDFT(), rcOptoKineticImage::genEightBitDFT(), rcOptoKineticImage::genEightBitFreq(), rcOptoKineticImage::genEightBitImg(), rcOptoKineticImage::genFreqImg(), rcOptoKineticImage::genKineticStats(), rcOptoKineticImage::genLogRMS(), genSpatialSDImg(), rcOptoKineticImage::genStdDevImg(), rcOptoKineticImage::genThetaEntropyImg(), rcOptoKineticImage::genVarImg(), rcOptoKineticImage::genVelEntropyImg(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rcLabelRLE::image2runs(), rcOptoKineticImage::incrementU8(), mirror(), rcEngineImpl::model2use(), randomFill(), rc_fill_poly(), rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc(), rcBasicPixelMap< T >::rcBasicPixelMap(), rcHistoStats::rcHistoStats(), TIFFImageIO::Read(), TIFFImageIO::ReadGenericImage(), rf_SetWindowBorder(), rfAndImage(), rfCorrelate(), rfDirectionSignal(), rfGauss163by3(), rfGauss3(), rfGauss3by3(), rfGen1DMomentIntegrals(), rfGen2DIMIntegrals(), rfGen2DIMIntegralsFast(), rfGen2DMomentIntegrals(), rfGen2DMomentIntegralsFast(), rfGenDepth8Histogram(), rfGetComponents(), rfGetRects(), rfHysteresisThreshold(), rfImage8Integrals(), rfImageAddMask(), rfImageConvert816(), rfImageConvert8to32(), rfImageFileToRcWindow(), rfImageIntegrals(), rfImageOrthogonalProjections(), rfImagePairMaskNeq(), rfImagePairMax(), rfImagePairMin(), rfMedian3By3Depth8(), rfMutualChannel(), rfOptoKineticVariance(), rfPeakDetect8Bit(), rfPeakDetectAsym8Bit(), rfPixel8Max3By3(), rfPixel8Min3By3(), rfPixelSample(), rfRcWindow8to32(), rfReversePixels16(), rfReversePixels8(), rfSetWindowBorder(), rfSobelEdge(), rfSpatialEdge(), rfSurfaceHessian(), rfTemporalMedianPixel16(), rfTemporalMedianPixel8(), rfWindow8to32(), rcCorrelationWindow< uint8 >::rowPelPointer(), rcCorrelationWindow< uint8 >::rowPointer(), segment(), segPoint(), set(), setAllDoublePixels(), setAllPixels(), sobelEdgeProcess(), rcPointCorrelation::update(), rcMomentGenerator::update(), and rcGenMovieFile::write().
  {
    rmAssertDebug( y >= 0 );
    return (mFrameBuf->rowPointer (y + mGeometry.y() ) + mGeometry.x() * mFrameBuf->depth ());
  }
uint8 * rcWindow::rowPointer (int32 y)
Definition at line 144 of file rc_window.cpp.
References rcFrame::depth(), mFrameBuf, mGeometry, rmAssertDebug, rcFrame::rowPointer(), rcRect::x(), and rcRect::y().
  {
    rmAssertDebug( y >= 0 );
    return (mFrameBuf->rowPointer (y + mGeometry.y() ) + mGeometry.x() * mFrameBuf->depth ());
  }
int32 rcWindow::rowUpdate () const inline
Definition at line 186 of file rc_window.h.
Referenced by CGImage(), contains(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), operator<<(), rc_fill_poly(), rfAndImage(), rfCorrelate(), rfDetectPeaks(), rfGen1DMomentIntegrals(), rfGen2DIMIntegrals(), rfGen2DIMIntegralsFast(), rfGen2DMomentIntegrals(), rfGen2DMomentIntegralsFast(), rfGetComponents(), rfHysteresisThreshold(), rfImage8Integrals(), rfImage8Transpose(), rfImageACfield(), rfImageFileToRcWindow(), rfMedian3By3Depth8(), rfPeakDetect8Bit(), rfPeakDetectAsym8Bit(), rfPixel8Max3By3(), rfPixel8Min3By3(), rfPixelExpand(), rfSetWindowBorder(), rfSpatialEdge(), rfSurfaceHessian(), rcCorrelationWindow< uint8 >::rowPelUpdate(), rcCorrelationWindow< uint8 >::rowUpdate(), segment(), rcPointCorrelation::update(), rcMomentGenerator::update(), and vImage().
 { return mFrameBuf->rowUpdate (); }
bool rcWindow::sameTime (const rcWindow & other) const inline
Definition at line 191 of file rc_window.h.
References frameBuf(), and rcFrame::timestamp().
   {
     return frameBuf()->timestamp() == other.frameBuf()->timestamp();
   }
rcWindow & rcWindow::set (double pixelValue)
Definition at line 461 of file rc_window.cpp.
References depth(), height(), isD32Float(), rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, rmExceptionMacro, rowPointer(), setAllDoublePixels(), setAllPixels(), and width().
Referenced by _exhaustiveImageFind(), rf_SetWindowBorder(), rfImageIntegrals(), and rfImageOrthogonalProjections().
 {
   switch (depth())
     {
     case rcPixelDouble:
       return setAllDoublePixels (pixelValue);
     case rcPixel8:
     case rcPixel16:
       return setAllPixels ((uint32) pixelValue);
     case rcPixel32:
       if (!isD32Float ())
     return setAllPixels ((uint32) pixelValue);
       else
       {
       int32 lastRow = height() - 1, row = 0;
       const int32 unrollCount = 8;
       int32 unrollCnt = width() / unrollCount;
       int32 unrollRem = width() % unrollCount;
             for ( ; row <= lastRow; row++)
             {
                 float* pixelPtr = (float *) rowPointer(row);
                 for (int32 copyCount = 0; copyCount < unrollCnt; copyCount++)
                 {
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                 }
                 for (int32 copyCount = 0; copyCount < unrollRem; copyCount++)
                     *pixelPtr++ = pixelValue;
             }
       }
       return *this;
     default:
       rmExceptionMacro(<< "IP Window::not implemented");
     }
 }
rcWindow & rcWindow::setAllDoublePixels (double pixelValue)
Definition at line 580 of file rc_window.cpp.
References height(), rowPointer(), and width().
Referenced by rfSetWindowBorder(), and set().
 {
     int32 lastRow = height() - 1, row = 0;
     const uint32 unrollCount = 8;
     int32 unrollCnt = width() / unrollCount;
     int32 unrollRem = width() % unrollCount;
     for ( ; row <= lastRow; row++)
     {
         double* pixelPtr = (double *) rowPointer(row);
         for (int32 copyCount = 0; copyCount < unrollCnt; copyCount++)
         {
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
             *pixelPtr++ = pixelValue;
         }
         for (int32 copyCount = 0; copyCount < unrollRem; copyCount++)
             *pixelPtr++ = pixelValue;
     }
     return *this;
 }
rcWindow & rcWindow::setAllPixels (uint32 pixelValue)
Definition at line 510 of file rc_window.cpp.
References depth(), height(), rcPixel16, rcPixel32, rcPixel8, rmAssert, rowPointer(), and width().
Referenced by rcKinetoscope::advance(), rcKinetoscope::createFunctionSpecificObjects(), rcMuscleSegmenter::debugWrite(), drawCells(), rcMuscleSegmenter::filterByActivity(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), rcMuscleSegmenter::genFrequencySegmentation(), rcMuscleSegmenter::genSpatialSegmentation(), rcOptoKineticImage::incrementU8(), rcKinetoscope::preSegmentedBodies(), rcMutualInfo::rcMutualInfo(), rfDrawCircle(), rfDrawShape(), rfGetComponents(), rfHysteresisThreshold(), rfImage8Integrals(), rfImageConvert8to32(), rfMutualChannel(), rfOptoKineticVariance(), rcMuscleSegmenter::segment(), set(), rcShape::setMask(), rcKinetoscope::start(), rcLatticeSimilarator::ttc(), and rcVisualFunction::updateSims().
 {
     int32 lastRow = height() - 1, row = 0;
     const int32 unrollCount = 8;
     int32 unrollCnt = width() / unrollCount;
     int32 unrollRem = width() % unrollCount;
     switch (depth())
     {
         case rcPixel8:
             for ( ; row <= lastRow; row++)
             {
                 memset(rowPointer(row), pixelValue, width());
             }
             break;
         case rcPixel16:
             for ( ; row <= lastRow; row++)
             {
                 uint16 valueAsShort = pixelValue;
                 uint16* pixelPtr = (uint16*) rowPointer(row);
                 for (int32 copyCount = 0; copyCount < unrollCnt; copyCount++)
                 {
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                     *pixelPtr++ = valueAsShort;
                 }
                 for (int32 copyCount = 0; copyCount < unrollRem; copyCount++)
                     *pixelPtr++ = valueAsShort;
             }
             break;
         case rcPixel32:
             for ( ; row <= lastRow; row++)
             {
                 uint32* pixelPtr = (uint32*) rowPointer(row);
                 for (int32 copyCount = 0; copyCount < unrollCnt; copyCount++)
                 {
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                     *pixelPtr++ = pixelValue;
                 }
                 for (int32 copyCount = 0; copyCount < unrollRem; copyCount++)
                     *pixelPtr++ = pixelValue;
             }
             break;
         default:
             rmAssert(0);
     }
     return *this;
 }
double rcWindow::setDoublePixel (int32 x, int32 y, double value)
Definition at line 752 of file rc_window.cpp.
References isBound(), mFrameBuf, mGeometry, rmExceptionMacro, rcFrame::setDoublePixel(), rcRect::x(), and rcRect::y().
Referenced by rcDefGenerateImage::genImage(), randomFill(), and setDoublePixel().
   {
   if (x < 0 || y < 0 || !isBound())
     rmExceptionMacro ("Window Geometry Error");
     return mFrameBuf->setDoublePixel (x + mGeometry.x (), y + mGeometry.y (), value);
   }
double rcWindow::setDoublePixel (const rcIPair & where, double value)
Definition at line 668 of file rc_window.cpp.
References setDoublePixel(), rcPair< T >::x(), and rcPair< T >::y().
 {
   return setDoublePixel (where.x(), where.y(), value);
 }
uint32 rcWindow::setPixel (int32 x, int32 y, uint32 value)
Definition at line 745 of file rc_window.cpp.
References isBound(), mFrameBuf, mGeometry, rmExceptionMacro, rcFrame::setPixel(), rcRect::x(), and rcRect::y().
Referenced by rcMutualInfo::add(), rcMuscleTracker::calculateCellLocation(), rcMuscleTracker::genEdgePoints(), rcOptoKineticImage::genEightBitDFT(), rcOptoKineticImage::genEightBitFreq(), rcDefGenerateImage::genImage(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcMathematicalImage::mMakeField(), rcMathematicalImage::mMakeImage(), randomFill(), rc_fill_poly(), rc_zonePlate(), rcDrawLine(), rcDrawPolygon(), rcFillPolygon(), rfCverAndImages(), rfDrawCircle(), rfDrawLine(), rfDrawShape(), setPixel(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), and rcMomentGenerator::vProject2DFast().
  {
   if (x < 0 || y < 0 || !isBound())
     rmExceptionMacro ("Window Geometry Error");
    return mFrameBuf->setPixel (x + mGeometry.x (), y + mGeometry.y (), value);
  }
uint32 rcWindow::setPixel (const rcIPair & where, uint32 value)
Definition at line 663 of file rc_window.cpp.
References setPixel(), rcPair< T >::x(), and rcPair< T >::y().
 {
   return setPixel (where.x(), where.y(), value);
 }
rcIPair rcWindow::size (void) const inline
Definition at line 117 of file rc_window.h.
Referenced by _exhaustiveImageFind(), rcMutualInfo::add(), rcGenMovieFile::addFrame(), contentCompare(), contentMaskCompare(), copyImage(), rcMuscleSegmenter::debugWrite(), maxTrim(), rcShape::operator==(), rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc(), rcBasicPixelMap< T >::rcBasicPixelMap(), rfGetRects(), rfGradientImageToVisualSegment(), rfHysteresisThreshold(), rfImage8Integrals(), rfImageACfield(), rfImageACfieldArea(), rfImageIntegrals(), rfImageVerticalReflect(), rfPixelMax3By3(), rfPixelMin3By3(), rfSobel(), rcMuscleSegmenter::segment(), rcLatticeSimilarator::ttc(), and rcVisualFunction::updateSims().
 { return rcIPair (mGeometry.width(), mGeometry.height()); }
bool rcWindow::tiff (std::string & outfile, bool compress = false) const
Definition at line 80 of file rc_window2tiff.cpp.
References _TIFFfree(), _TIFFmalloc(), BAND, compression, COMPRESSION_DEFLATE, COMPRESSION_JPEG, COMPRESSION_LZW, COMPRESSION_PACKBITS, endl(), FILLORDER_MSB2LSB, jpegcolormode, JPEGCOLORMODE_RGB, NULL, ORIENTATION_TOPLEFT, PHOTOMETRIC_MINISBLACK, PHOTOMETRIC_RGB, PHOTOMETRIC_YCBCR, PIXEL, PLANARCONFIG_CONTIG, predictor, quality, rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, rcPixelUnknown, SAMPLEFORMAT_IEEEFP, SAMPLEFORMAT_INT, SAMPLEFORMAT_UINT, SAMPLEFORMAT_VOID, TIFF_BYTE, TIFF_DOUBLE, TIFF_FLOAT, TIFF_LONG, TIFF_SBYTE, TIFF_SHORT, TIFF_SLONG, TIFF_SSHORT, TIFFClose(), TIFFDefaultStripSize(), TIFFOpen(), TIFFSetField(), TIFFTAG_BITSPERSAMPLE, TIFFTAG_COMPRESSION, TIFFTAG_FILLORDER, TIFFTAG_IMAGELENGTH, TIFFTAG_IMAGEWIDTH, TIFFTAG_JPEGCOLORMODE, TIFFTAG_JPEGQUALITY, TIFFTAG_ORIENTATION, TIFFTAG_PHOTOMETRIC, TIFFTAG_PLANARCONFIG, TIFFTAG_PREDICTOR, TIFFTAG_ROWSPERSTRIP, TIFFTAG_SAMPLEFORMAT, TIFFTAG_SAMPLESPERPIXEL, and TIFFWriteScanline().
Referenced by rcVisualFunction::cardiacMeasure(), rcEngineImpl::muscleTracker(), and rfDirectionSignal().
 {
   uint32    _width = width(), length = height(), linebytes;
   uint32    nbands = 1;         /* number of bands in input image*/
   off_t hdr_size = 0;           /* size of the header to skip */
   TIFFDataType dtype = TIFF_BYTE;
   int16 _depth = 1;         /* bytes per pixel in input image */
   InterleavingType interleaving = PIXEL;  /* interleaving type flag */
   uint32  rowsperstrip = (uint32) 1;
   uint16    photometric = PHOTOMETRIC_MINISBLACK;
   uint16    config = PLANARCONFIG_CONTIG;
   uint16    fillorder = FILLORDER_MSB2LSB;
   int   fd;
   TIFF  *out;
   uint32 row;
   unsigned char *buf = NULL;
   switch (depth())
     {
     case rcPixel8:
       dtype = TIFF_BYTE;
       _depth = 1;
       break;
     case rcPixel16:
       dtype = TIFF_SHORT;
       _depth = 2;
       break;
     case rcPixel32:
       dtype = isD32Float() ? TIFF_FLOAT : TIFF_LONG;
       _depth = 4;
       break;
     case rcPixelDouble:
       dtype = TIFF_DOUBLE;
       _depth = 8;
       break;
     default:
     case rcPixelUnknown:
       return false;
     }
   // Photometric needs to be handle
   out = TIFFOpen(outfile.c_str(), "wb");
   if (out == NULL)
     {
       cerr << outfile << "Cannot open file for output. " << endl;
       return 0;
     }
   TIFFSetField(out, TIFFTAG_IMAGEWIDTH, _width);
   TIFFSetField(out, TIFFTAG_IMAGELENGTH, length);
   TIFFSetField(out, TIFFTAG_ORIENTATION, ORIENTATION_TOPLEFT);
   TIFFSetField(out, TIFFTAG_SAMPLESPERPIXEL, nbands);
   TIFFSetField(out, TIFFTAG_BITSPERSAMPLE, _depth * 8);
   TIFFSetField(out, TIFFTAG_FILLORDER, fillorder);
   TIFFSetField(out, TIFFTAG_PLANARCONFIG, config);
   TIFFSetField(out, TIFFTAG_PHOTOMETRIC, photometric);
   switch (dtype) {
   case TIFF_BYTE:
   case TIFF_SHORT:
   case TIFF_LONG:
     TIFFSetField(out, TIFFTAG_SAMPLEFORMAT, SAMPLEFORMAT_UINT);
     break;
   case TIFF_SBYTE:
   case TIFF_SSHORT:
   case TIFF_SLONG:
     TIFFSetField(out, TIFFTAG_SAMPLEFORMAT, SAMPLEFORMAT_INT);
     break;
   case TIFF_FLOAT:
   case TIFF_DOUBLE:
     TIFFSetField(out, TIFFTAG_SAMPLEFORMAT, SAMPLEFORMAT_IEEEFP);
     break;
   default:
     TIFFSetField(out, TIFFTAG_SAMPLEFORMAT, SAMPLEFORMAT_VOID);
     break;
   }
   if (doCompress) compression = (uint16) -1;
   if (compression == (uint16) -1)
     compression = COMPRESSION_PACKBITS;
   TIFFSetField(out, TIFFTAG_COMPRESSION, compression);
   switch (compression) {
   case COMPRESSION_JPEG:
     if (photometric == PHOTOMETRIC_RGB
     && jpegcolormode == JPEGCOLORMODE_RGB)
       photometric = PHOTOMETRIC_YCBCR;
     TIFFSetField(out, TIFFTAG_JPEGQUALITY, quality);
     TIFFSetField(out, TIFFTAG_JPEGCOLORMODE, jpegcolormode);
     break;
   case COMPRESSION_LZW:
   case COMPRESSION_DEFLATE:
     if (predictor != 0)
       TIFFSetField(out, TIFFTAG_PREDICTOR, predictor);
     break;
   }
   switch(interleaving) {
   case BAND:                /* band interleaved data */
     linebytes = _width * _depth;
     buf = (unsigned char *)_TIFFmalloc(linebytes);
     break;
   case PIXEL:               /* pixel interleaved data */
   default:
     linebytes = _width * nbands * _depth;
     break;
   }
   TIFFSetField(out, TIFFTAG_ROWSPERSTRIP, TIFFDefaultStripSize(out, rowsperstrip));
   lseek(fd, hdr_size, SEEK_SET);        /* Skip the file header */
   for (row = 0; row < length; row++)
     {
       if (TIFFWriteScanline(out,  (unsigned char *) rowPointer (row), row, 0) < 0)
     {
       cerr << outfile << ": scanline" << row << ": Write error." << endl;
       break;
     }
     }
   if (buf)
     _TIFFfree(buf);
   TIFFClose(out);
   return true;
 }
rcTimestamp rcWindow::timestamp () const inline
Definition at line 197 of file rc_window.h.
   {
     return frameBuf()->timestamp();
   }
bool rcWindow::translate (const rcIPair & delta)
Definition at line 730 of file rc_window.cpp.
References height(), rcFrame::height(), mFrameBuf, mGeometry, rcRectangle< T >::origin(), width(), rcFrame::width(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
Referenced by rcCorrelationWindow< uint8 >::translate().
   {
     int32 x = mGeometry.x() + delta.x();
     int32 y = mGeometry.y() + delta.y();
     if (x >= 0 && (x+width()-1) < mFrameBuf->width() &&
     y >= 0 && (y+height()-1) < mFrameBuf->height())
       {
     mGeometry.origin(rcIPair (x,y));
     return true;
       }
     return false;
   }
rcWindow & rcWindow::trim (uint32 delta)
Definition at line 361 of file rc_window.cpp.
References height(), width(), and windowRelativeTo().
Referenced by rcVisualFunction::cardiacMeasure(), and trim().
 {
   windowRelativeTo (*this, delta , delta , width() - 2*delta, height() - 2*delta);
   return *this;
 }
bool rcWindow::trim (int32 delta)
Definition at line 367 of file rc_window.cpp.
References trim().
 {
   return trim (rcIPair (delta, delta));
 }
bool rcWindow::trim (rcIPair delta)
Definition at line 372 of file rc_window.cpp.
References rcFrame::height(), rcRectangle< T >::height(), mFrameBuf, mGeometry, rcRectangle< T >::origin(), rcRectangle< T >::size(), rcFrame::width(), rcRectangle< T >::width(), rcRect::x(), rcPair< T >::x(), x(), rcRect::y(), rcPair< T >::y(), and y().
 {
     int32 x, y, w, h;
     bool flag = false;
     x = mGeometry.x() + delta.x();
     y = mGeometry.y() + delta.y();
     w = mGeometry.width() - 2 * delta.x();
     h = mGeometry.height() - 2 * delta.y();
     if (x >= 0 && w > 0 && (x+w-1) < (mFrameBuf->width()) &&
         h > 0 && y >= 0 && (y+h-1) < (mFrameBuf->height()))
     {
         mGeometry.origin(rcIPair (x,y));
         mGeometry.size(rcIPair (w,h));
         flag = true;
     }
     return flag;
 }
bool rcWindow::vImage (vImage_Buffer & vi) const
Definition at line 278 of file rc_window.cpp.
References isBound(), pelPointer(), rmAssert, rowUpdate(), and width().
Referenced by rcDefGenerateImage::genImage(), rcKinetoscope::reichardt(), rfGauss3(), rfGaussianConv(), rfImageConvert168(), rfImageConvert32to8(), rfImageConvert8888ToARGB(), rfImageConvert8to32(), rfImageConvert8ToARGB(), rfImageConvertARGBto8888(), rfImageConvertFloat8(), rfImageVerticalReflect(), rfPixel8Map(), rfPixelMax3By3(), and rfPixelMin3By3().
 {
   if (!isBound()) return false;
   rmAssert(rowUpdate() > 0);
   // Get the top left pixel. vImage data pointer is a void *
   const uint8 *pels = pelPointer (0,0);
   vi.data = (void *) pels;
   vi.width = (uint32) width();
   vi.height = (uint32) height ();
   vi.rowBytes = (uint32) rowUpdate ();
   return true;
 }
int32 rcWindow::width () const inline
Definition at line 112 of file rc_window.h.
Referenced by _exhaustiveImageFind(), _rfRcWindow32to8(), rcMutualInfo::add(), rcGenMovieFile::addFrame(), binarize(), binarizeFloatWindow(), rcSegmentationLevel::binaryImage(), rcImageCanvasGL::buildImageDlist(), rcMuscleTracker::calculateCellLocation(), rcVisualFunction::cardiacUpdate(), CGImage(), copyImage(), copyPixelsFromWindow(), rcOptoKineticImage::decrementU8(), rcVisualFunction::dividingProcess(), rcSimilarator::fill(), rcMuscleSegmenter::filterAtEdge(), rcMuscleSegmenter::filterByActivity(), rcMuscleSegmenter::filterByAR(), rcMuscleSegmenter::filterBySize(), gaussEdge(), rcOptoKineticImage::gen1DCorrKineticImgs(), rcCubicGeneratePixel::gen2D2ndD(), rcCubicGeneratePixel::gen2ndD(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcOptoKineticImage::genAccelEntropyImg(), rcOptoKineticImage::genDFT(), rcMuscleTracker::genEdgePoints(), rcOptoKineticImage::genEightBitDFT(), rcOptoKineticImage::genEightBitFreq(), rcOptoKineticImage::genEightBitImg(), generateExpansionMovie(), generateRandomMovie(), generateTranslationMovie(), rcOptoKineticImage::genFreqImg(), rcOptoKineticImage::genKineticStats(), rcOptoKineticImage::genLogRMS(), rcEdgeFilter1D::genPeaks(), rcLinGeneratePixel::genPixel(), rcAutoCorrelation::genPoint(), rcMuscleTracker::genSpace(), rcPointCorrelation::genSpace(), genSpatialSDImg(), genSpatialSDSum(), rcOptoKineticImage::genStdDevImg(), rcMomentGenerator::genSumSumSq1D(), rcMomentGenerator::genSumSumSq2D(), rcMomentGenerator::genSumSumSq2DFast(), rcOptoKineticImage::genThetaEntropyImg(), rcOptoKineticImage::genVarImg(), rcOptoKineticImage::genVelEntropyImg(), rcMuscleSegmenter::getCells(), rcSpatialPyramid< 2 >::gradientProcess(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcLabelRLE::image2runs(), rcOptoKineticImage::incrementU8(), rcGenMovieFile::initHeader(), rcSpatialPyramid< 2 >::intensityProcess(), rcCubicGeneratePixel::interpolate(), rcImageCanvasGL::loadrcWindow(), mirror(), rcMathematicalImage::mMakeField(), rcMathematicalImage::mMakeImage(), rcEngineImpl::modelTracker(), operator<<(), rcEngineImpl::postTrackingResults(), rcShape::project(), rcShape::projectMI(), rcOptoKineticImage::push(), randomFill(), rc_fill_poly(), rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc(), rcBasicPixelMap< T >::rcBasicPixelMap(), rcDrawLine(), rcGaussKernel2D< T, ksize >::rcGaussKernel2D(), rcHistoStats::rcHistoStats(), rcSpatialPyramid< 2 >::rcSpatialPyramid(), TIFFImageIO::Read(), TIFFImageIO::ReadGenericImage(), rcSpatialPyramid< 2 >::region(), rcKinetoscope::reichardt(), rf_SetWindowBorder(), rfAndImage(), rfCompareMovies(), rfCopyWindowBorder(), rfCorrelate(), rfCubicShiftImage(), rfCverAndImages(), rfDetectPeaks(), rfDirectionSignal(), rfDrawCircle(), rfGauss163by3(), rfGauss3(), rfGauss3by3(), rfGaussianConv(), rfGen1DMomentIntegrals(), rfGen2DIMIntegrals(), rfGen2DIMIntegralsFast(), rfGen2DMomentIntegrals(), rfGen2DMomentIntegralsFast(), rfGenDepth8Histogram(), rfGetComponents(), rfGetRects(), rfGradientImageToVisualSegment(), rfHysteresisThreshold(), rfImage8Integrals(), rfImage8Transpose(), rfImageACfield(), rfImageAddMask(), rfImageConvert168(), rfImageConvert32to8(), rfImageConvert816(), rfImageConvert8888ToARGB(), rfImageConvert8to32(), rfImageConvert8ToARGB(), rfImageConvertARGBto8888(), rfImageConvertFloat8(), rfImageGradientToVisualSegment(), rfImageIntegrals(), rfImageOrthogonalProjections(), rfImagePairMaskNeq(), rfImagePairMax(), rfImagePairMin(), rfImageVerticalReflect(), rfMedian(), rfMedian3By3Depth8(), rfMutualChannel(), rfPeakDetect8Bit(), rfPeakDetectAsym8Bit(), rfPixel8Max3By3(), rfPixel8Min3By3(), rfPixelExpand(), rfPixelMax3By3(), rfPixelMin3By3(), rfPixelSample(), rfPrintCorrSpace(), rfRcWindow8to32(), rfReversePixels16(), rfReversePixels8(), rfRLEstimate(), rfSetWindowBorder(), rfSobel(), rfSobelEdge(), rfSpatialEdge(), rfSurfaceHessian(), rfTemporalMedian(), rfTemporalMedianPixel16(), rfTemporalMedianPixel8(), rfWindow8to32(), segment(), rcMuscleSegmenter::segment(), segPoint(), segPointByEnergy(), set(), setAllDoublePixels(), setAllPixels(), rcShape::setMask(), rcSimilarator::setMask(), sobelEdgeProcess(), translate(), trim(), rcPointCorrelation::update(), rcMomentGenerator::update(), rcVisualFunction::updateSims(), vImage(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), rcCorrelationWindow< uint8 >::width(), window(), and rcGenMovieFile::write().
 { return mGeometry.width(); }
bool rcWindow::window (const rcWindow & parentWindow, int32 x, int32 y, int32 width, int32 height, bool clip) protected
Definition at line 295 of file rc_window.cpp.
References rcRectangle< T >::contains(), height(), isBound(), mGeometry, rcRectangle< T >::origin(), rcWindow(), rmExceptionMacro, width(), x(), and y().
Referenced by rcWindow(), and windowRelativeTo().
 {
   if (x < 0 || y < 0 || !parentWindow.isBound())
     rmExceptionMacro ("Window Geometry Error");
   *this = rcWindow (parentWindow);
   rcIRect frm = mGeometry;
   mGeometry = rcIRect (parentWindow.x() + x, parentWindow.y() + y, width, height);
   bool what (false);
   if (!frm.contains (mGeometry))
     {
       if (!clip)
     rmExceptionMacro (<< "Window Geometry Error");
       what = true;
       mGeometry &= frm;
       if (!frm.contains (mGeometry))
     mGeometry.origin (rcIPair (0,0));
     }
   return what;
 }
rcWindow & rcWindow::windowRelativeTo (const rcWindow & parentWindow, int32 x, int32 y, int32 width, int32 height)
Definition at line 352 of file rc_window.cpp.
References rmUnused, and window().
Referenced by trim().
 {
   bool what = window (parentWindow, x, y, width, height, false);
   rmUnused (what);
   return *this;
 }
int32 rcWindow::x () const inline
Definition at line 109 of file rc_window.h.
Referenced by canTrim(), rcDefGenerateImage::genImage(), rcEngineImpl::modelTracker(), rcDefGenerateImage::project(), trim(), window(), and rcCorrelationWindow< uint8 >::x().
 { return mGeometry.x(); }
int32 rcWindow::y () const inline
Definition at line 110 of file rc_window.h.
Referenced by canTrim(), trim(), window(), and rcCorrelationWindow< uint8 >::y().
 { return mGeometry.y(); }
double rcWindow::zVal () const inline
Definition at line 189 of file rc_window.h.
 { return mFrameBuf->zVal (); }
void rcWindow::zVal (double dv) inline
Definition at line 251 of file rc_window.h.
 { mFrameBuf->zVal (dv); }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcWindow & w) friend
Definition at line 674 of file rc_window.cpp.
 {
   o << "Size:      " << w.width() << "," << w.height() << endl;
   o << "RowUpdate: " << w.rowUpdate() << endl;
   for (int32 j = 0; j < w.height(); j++)
     {
       o << "[" << setw (3) << j << "]";
       for (int32 i = 0; i < w.width(); i++)
     {
       if (w.depth() != 8)
         o <<  setw(3) << (int32) (w.getPixel (i, j));
       else o <<   fixed << setprecision(2) << w.getDoublePixel (i, j);
     }
       o << endl;
     }
   return o;
 }
Member Data Documentation
rcSharedFrameBufPtr rcWindow::mFrameBuf protected
Definition at line 315 of file rc_window.h.
Referenced by canTrim(), contains(), entire(), getDoublePixel(), getPixel(), init(), operator!=(), operator()(), operator==(), pelPointer(), rcWindow(), rowPointer(), setDoublePixel(), setPixel(), translate(), and trim().
rcRect rcWindow::mGeometry protected
Definition at line 316 of file rc_window.h.
Referenced by canPeekOutSide(), canTrim(), contains(), entire(), getDoublePixel(), getPixel(), init(), operator!=(), operator()(), operator==(), pelPointer(), rcWindow(), rowPointer(), setDoublePixel(), setPixel(), translate(), trim(), and window().
The documentation for this class was generated from the following files:
include/visual/rc_window.h
src/visual/code/rc_window.cpp
src/visual/code/rc_window2tiff.cpp