Visible: rcXMLElement Class Reference
rcXMLElement Class Reference
#include <include/visiCore/rc_xmlelem.h>
Public Member Functions
rcXMLElement ()
rcXMLElement (rcXMLElementType type)
rcXMLElement (rcXMLElementType type, const std::string &content)
rcXMLElement (rcXMLElementType type, const rcAttributeList &attrs)
rcXMLElement (rcXMLElementType type, const rcAttributeList &attrs, const std::string &content)
rcXMLElementType type () const
const rcAttributeList & attributes () const
const std::string & content () const
const std::string attributeValue (rcXMLAttributeType attributeType) const
std::string & content ()
Private Attributes
rcXMLElementType mType
rcAttributeList mAttributes
std::string mContent
Detailed Description
Definition at line 200 of file rc_xmlelem.h.
Constructor & Destructor Documentation
rcXMLElement::rcXMLElement () inline
Definition at line 203 of file rc_xmlelem.h.
 : mType( eXMLElementMax ) { };
rcXMLElement::rcXMLElement (rcXMLElementType type) inline
Definition at line 205 of file rc_xmlelem.h.
     : mType( type ), mAttributes( rcAttributeList() ), mContent( std::string() ) {
     };
rcXMLElement::rcXMLElement (rcXMLElementType type, const std::string & content) inline
Definition at line 208 of file rc_xmlelem.h.
         : mType( type ), mAttributes( rcAttributeList() ), mContent( content ) {
     };
rcXMLElement::rcXMLElement (rcXMLElementType type, const rcAttributeList & attrs) inline
Definition at line 211 of file rc_xmlelem.h.
     : mType( type ), mAttributes( attrs ), mContent( std::string() ) {
     };
rcXMLElement::rcXMLElement (rcXMLElementType type, const rcAttributeList & attrs, const std::string & content) inline
Definition at line 214 of file rc_xmlelem.h.
         : mType( type ), mAttributes( attrs ), mContent( content ) {
     };
Member Function Documentation
const rcAttributeList& rcXMLElement::attributes () const inline
Definition at line 220 of file rc_xmlelem.h.
References mAttributes.
Referenced by operator<<().
 { return mAttributes; };
const std::string rcXMLElement::attributeValue (rcXMLAttributeType attributeType) const inline
Definition at line 222 of file rc_xmlelem.h.
References mAttributes.
Referenced by rcNativeImporter::parseFrame(), rcNativeImporter::parseGroup(), rcNativeImporter::parseTime(), rcNativeImporter::parseTrack(), and rcNativeImporter::parseValue().
{
         // TODO: replace linear search with something faster
         rcAttributeList::const_iterator i;
         for ( i = mAttributes.begin(); i < mAttributes.end(); i++ ) {
             if ( i->first == attributeType ) {
                 // Found attribute with matching name
                 return i->second;
             }
         }
         return std::string();
     };
const std::string& rcXMLElement::content () const inline
Definition at line 221 of file rc_xmlelem.h.
References mContent.
Referenced by rcXMLParser::characters(), rcXMLParser::endElement(), rcNativeImporter::importExperiment(), operator<<(), rcNativeImporter::parseSetting(), rcNativeImporter::parseSettingCategory(), rcNativeImporter::parseTime(), and rcNativeImporter::parseValue().
 { return mContent; };
std::string& rcXMLElement::content () inline
Definition at line 236 of file rc_xmlelem.h.
 { return mContent; };
rcXMLElementType rcXMLElement::type (void) const inline
Definition at line 219 of file rc_xmlelem.h.
References mType.
Referenced by rcNativeImporter::importExperiment(), operator<<(), output(), rcNativeImporter::parseExperimentData(), rcNativeImporter::parseFrame(), rcNativeImporter::parseGroup(), rcNativeImporter::parseSetting(), rcNativeImporter::parseSettingCategory(), rcNativeImporter::parseTrack(), and rcNativeImporter::parseValue().
 { return mType; };
Member Data Documentation
rcAttributeList rcXMLElement::mAttributes private
Definition at line 240 of file rc_xmlelem.h.
Referenced by attributes(), and attributeValue().
std::string rcXMLElement::mContent private
Definition at line 241 of file rc_xmlelem.h.
Referenced by content().
rcXMLElementType rcXMLElement::mType private
Definition at line 236 of file rc_xmlelem.h.
Referenced by type().
The documentation for this class was generated from the following file:
include/visiCore/rc_xmlelem.h