Visible: rcReifyMovieGrabber Class Reference
rcReifyMovieGrabber Class Reference
#include <include/visual/rc_reifymoviegrabber.h>
Public Member Functions
rcReifyMovieGrabber (rcVideoCache &cache)
virtual ~rcReifyMovieGrabber ()
virtual bool start ()
virtual bool stop ()
virtual int32 frameCount ()
virtual int32 cacheSize ()
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)
const std::string getInputSourceName ()
Public Member Functions inherited from rcFileGrabber
rcFileGrabber (rcCarbonLock *lock)
virtual ~rcFileGrabber ()
virtual rcFrameGrabberError getLastError () const
virtual bool isValid () const
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
Static Private Member Functions
static rcFrameGrabberError errorNoTranslate (rcVideoCacheError error)
Private Attributes
int32 _framesLeft
int32 _curFrame
bool _started
rcVideoCache & _cache
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Protected Member Functions inherited from rcFileGrabber
void setLastError (rcFrameGrabberError)
void lock ()
void unlock ()
Detailed Description
Definition at line 20 of file rc_reifymoviegrabber.h.
Constructor & Destructor Documentation
rcReifyMovieGrabber::rcReifyMovieGrabber (rcVideoCache & cache)
Definition at line 11 of file rc_reifymoviegrabber.cpp.
References _cache, errorNoTranslate(), rcVideoCache::getFatalError(), rcVideoCache::isValid(), and rcFileGrabber::setLastError().
   : rcFileGrabber(0), _framesLeft(0), _curFrame(0), _started(false),
     _cache(cache)
 {
   if (!_cache.isValid())
     setLastError(errorNoTranslate(_cache.getFatalError()));
 }
rcReifyMovieGrabber::~rcReifyMovieGrabber () virtual
Definition at line 19 of file rc_reifymoviegrabber.cpp.
 {
 }
Member Function Documentation
virtual int32 rcReifyMovieGrabber::cacheSize () inline virtual
Implements rcFrameGrabber.
Definition at line 41 of file rc_reifymoviegrabber.h.
References _cache, and rcVideoCache::cacheSize().
 { return _cache.cacheSize(); }
rcFrameGrabberError rcReifyMovieGrabber::errorNoTranslate (rcVideoCacheError error) static private
Definition at line 82 of file rc_reifymoviegrabber.cpp.
References eFrameErrorFileClose, eFrameErrorFileFormat, eFrameErrorFileInit, eFrameErrorFileRead, eFrameErrorFileRevUnsupported, eFrameErrorFileUnsupported, eFrameErrorInternal, eFrameErrorOK, eFrameErrorSystemResources, eFrameErrorUnknown, eFrameErrorUnsupportedDepth, eVideoCacheErrorBomUnsupported, eVideoCacheErrorCacheInvalid, eVideoCacheErrorDepthUnsupported, eVideoCacheErrorFileClose, eVideoCacheErrorFileFormat, eVideoCacheErrorFileInit, eVideoCacheErrorFileRead, eVideoCacheErrorFileRevUnsupported, eVideoCacheErrorFileSeek, eVideoCacheErrorFileUnsupported, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, and eVideoCacheErrorSystemResources.
Referenced by getNextFrame(), and rcReifyMovieGrabber().
 {
   switch (error) {
   case eVideoCacheErrorFileInit:
     return eFrameErrorFileInit;
   case eVideoCacheErrorFileSeek:
   case eVideoCacheErrorFileRead:
     return eFrameErrorFileRead;
   case eVideoCacheErrorFileClose:
     return eFrameErrorFileClose;
   case eVideoCacheErrorFileFormat:
     return eFrameErrorFileFormat;
   case eVideoCacheErrorFileUnsupported:
     return eFrameErrorFileUnsupported;
   case eVideoCacheErrorFileRevUnsupported:
     return eFrameErrorFileRevUnsupported;
   case eVideoCacheErrorSystemResources:
     return eFrameErrorSystemResources;
   case eVideoCacheErrorNoSuchFrame:
   case eVideoCacheErrorCacheInvalid:
     return eFrameErrorInternal;
   case eVideoCacheErrorOK:
     return eFrameErrorOK;
   case eVideoCacheErrorBomUnsupported:
     return eFrameErrorFileUnsupported;
   case eVideoCacheErrorDepthUnsupported:
     return eFrameErrorUnsupportedDepth;
   }
   return eFrameErrorUnknown;
 }
virtual int32 rcReifyMovieGrabber::frameCount () inline virtual
Implements rcFileGrabber.
Definition at line 38 of file rc_reifymoviegrabber.h.
References _cache, and rcVideoCache::frameCount().
 { return _cache.frameCount(); }
const std::string rcReifyMovieGrabber::getInputSourceName () inline virtual
Implements rcFrameGrabber.
Definition at line 48 of file rc_reifymoviegrabber.h.
References _cache, and rcVideoCache::getInputSourceName().
   { return _cache.getInputSourceName(); }
rcFrameGrabberStatus rcReifyMovieGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) virtual
Implements rcFileGrabber.
Definition at line 47 of file rc_reifymoviegrabber.cpp.
References _cache, _curFrame, _framesLeft, _started, eFrameErrorNotImplemented, eFrameStatusEOF, eFrameStatusError, eFrameStatusOK, errorNoTranslate(), eVideoCacheStatusOK, rcVideoCache::getFrame(), rcFileGrabber::isValid(), rcFileGrabber::setLastError(), and start().
 {
   if (!isValid())
     return eFrameStatusError;
   if (!isBlocking) {
     setLastError(eFrameErrorNotImplemented);
     return eFrameStatusError;
   }
   if (!_started && !start())
     return eFrameStatusError;
   if (_framesLeft == 0)
     return eFrameStatusEOF;
   _framesLeft--;
   /*
    * Get reference to frame, but don't lock it so it won't be forced
    * into memory before it is needed.
    */
   rcVideoCacheError error;
   rcVideoCacheStatus status = _cache.getFrame(_curFrame++, ptr, &error, false);
   if (status != eVideoCacheStatusOK) {
     setLastError(errorNoTranslate(error));
     return eFrameStatusError;
   }
   return eFrameStatusOK;
 }
bool rcReifyMovieGrabber::start (void) virtual
Implements rcFileGrabber.
Definition at line 23 of file rc_reifymoviegrabber.cpp.
References _cache, _curFrame, _framesLeft, _started, rcVideoCache::frameCount(), and rcFileGrabber::isValid().
Referenced by getNextFrame().
 {
   if (!isValid())
     return false;
   if (_started == false) {
     _framesLeft = _cache.frameCount();
     _curFrame = 0;
     _started = true;
   }
   return true;
 }
bool rcReifyMovieGrabber::stop (void) virtual
Implements rcFileGrabber.
Definition at line 37 of file rc_reifymoviegrabber.cpp.
References _started, and rcFileGrabber::isValid().
 {
   if (!isValid())
     return false;
   _started = false;
   return true;
 }
Member Data Documentation
rcVideoCache& rcReifyMovieGrabber::_cache private
Definition at line 57 of file rc_reifymoviegrabber.h.
Referenced by cacheSize(), frameCount(), getInputSourceName(), getNextFrame(), rcReifyMovieGrabber(), and start().
int32 rcReifyMovieGrabber::_curFrame private
Definition at line 55 of file rc_reifymoviegrabber.h.
Referenced by getNextFrame(), and start().
int32 rcReifyMovieGrabber::_framesLeft private
Definition at line 54 of file rc_reifymoviegrabber.h.
Referenced by getNextFrame(), and start().
bool rcReifyMovieGrabber::_started private
Definition at line 56 of file rc_reifymoviegrabber.h.
Referenced by getNextFrame(), start(), and stop().
The documentation for this class was generated from the following files:
include/visual/rc_reifymoviegrabber.h
src/visual/code/rc_reifymoviegrabber.cpp