Visible: rcPlaybackSettingWidget Class Reference
rcPlaybackSettingWidget Class Reference
#include <include/visUI/rc_playbacksettingwidget.h>
Public Slots
void settingChanged ()
void valueChanged ()
void stopVideo ()
void fwdVideo ()
void revVideo ()
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcPlaybackSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcPlaybackSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
QSpinBox * _speedWidget
QPushButton * _revWidget
QPushButton * _fwdWidget
QPushButton * _stopWidget
int _currentValueBits
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 14 of file rc_playbacksettingwidget.h.
Constructor & Destructor Documentation
rcPlaybackSettingWidget::rcPlaybackSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 23 of file rc_playbacksettingwidget.cpp.
References _fwdWidget, _revWidget, _speedWidget, _stopWidget, cUINoBreakAlignment, cUIsettingLabelSpacing, rcSettingInfo::eCurrentSpeedMask, fwdVideo(), rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingWidget::mDisplayLabel, rcSettingWidget::mTopLayout, revVideo(), rmAssert, settingChanged(), stopVideo(), and valueChanged().
   : rcSettingWidget(parent, setting)
 {
   rcModelDomain* domain = rcModelDomain::getModelDomain();
   // use the setting description as a tool tip
   QToolTip::add(mDisplayLabel, setting.getDescription());
   mTopLayout->addSpacing(cUIsettingLabelSpacing);
   _revWidget = new QPushButton("<<" ,this);
   rmAssert(_revWidget);
   _revWidget->setFixedWidth(60);
   QToolTip::add(_revWidget, "Click to play current video in reverse");
   mTopLayout->addWidget(_revWidget);
   mTopLayout->addSpacing(1);
   _stopWidget = new QPushButton("-" ,this);
   rmAssert(_stopWidget);
   _stopWidget->setFixedWidth(60);
   QToolTip::add(_stopWidget, "Click to stop playing video");
   mTopLayout->addWidget(_stopWidget);
   mTopLayout->addSpacing(1);
   _fwdWidget = new QPushButton(">>" ,this);
   rmAssert(_fwdWidget);
   _fwdWidget->setFixedWidth(60);
   QToolTip::add(_fwdWidget, "Click to play current video");
   mTopLayout->addWidget(_fwdWidget);
   mTopLayout->addSpacing(1);
   QLabel* label = new QLabel("Rate:", this);
   label->setFixedWidth(30);
   label->setAlignment(cUINoBreakAlignment);
   mTopLayout->addWidget(label);
   _speedWidget = new QSpinBox(1, rcSettingInfo::eCurrentSpeedMask, 1,
                   this, "speed");
   _speedWidget->setFixedWidth(80);
   _speedWidget->setSuffix("x");
   QToolTip::add(_speedWidget, "Use to adjust real time speed multiplier");
   mTopLayout->addWidget(_speedWidget);
   mTopLayout->addSpacing(5);
   // update the text widget with the current value of the setting.
   settingChanged();
   // route all spinbox's valueChanged signal to our single
   //    'valueChanged' slot
   connect(_speedWidget, SIGNAL(valueChanged(int)),
       this,         SLOT(valueChanged(void)));
   // connect the "rev" button 'clicked' signal to our
   // 'revVideo' slot so we can start a reverse video playback.
   connect(_revWidget,   SIGNAL(clicked(void)),
        this,        SLOT(revVideo(void)));
   // connect the "fwd" button 'clicked' signal to our
   // 'fwdVideo' slot so we can start a video playback.
   connect(_fwdWidget,   SIGNAL(clicked(void)),
        this,        SLOT(fwdVideo(void)));
   // connect the "stop" button 'clicked' signal to our
   // 'stopVideo' slot so we can stop video playback.
   connect(_stopWidget,  SIGNAL(clicked(void)),
        this,        SLOT(stopVideo(void)));
   // route all spinbox's valueChanged signal to our single
   // "valueChanged' slot
   connect(_speedWidget, SIGNAL(valueChanged(int)),
        this,        SLOT(valueChanged(void)));
   // connect this widget to be notified by the updateSettings()
   // signal from the model domain
   connect(domain,       SIGNAL(updateSettings()),
       this,         SLOT(settingChanged()));
 }
rcPlaybackSettingWidget::~rcPlaybackSettingWidget ()
Definition at line 106 of file rc_playbacksettingwidget.cpp.
References _fwdWidget, _revWidget, _speedWidget, and _stopWidget.
 {
   QToolTip::remove(this);
   QToolTip::remove(_revWidget);
   QToolTip::remove(_fwdWidget);
   QToolTip::remove(_stopWidget);
   QToolTip::remove(_speedWidget);
 }
Member Function Documentation
void rcPlaybackSettingWidget::fwdVideo () slot
Definition at line 172 of file rc_playbacksettingwidget.cpp.
References _currentValueBits, rcSettingInfo::eCurrentStateFwd, rcSettingInfo::eCurrentStateRev, rcSettingInfo::eCurrentStateStopped, rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), rmAssert, and rcSettingInfo::setValue().
Referenced by rcPlaybackSettingWidget().
 {
   rmAssert(_currentValueBits & rcSettingInfo::eCurrentStateStopped);
   _currentValueBits |= rcSettingInfo::eCurrentStateFwd;
   _currentValueBits &= ~(rcSettingInfo::eCurrentStateStopped |
              rcSettingInfo::eCurrentStateRev);
   mSetting.setValue(_currentValueBits);
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
void rcPlaybackSettingWidget::revVideo () slot
Definition at line 185 of file rc_playbacksettingwidget.cpp.
References _currentValueBits, rcSettingInfo::eCurrentStateFwd, rcSettingInfo::eCurrentStateRev, rcSettingInfo::eCurrentStateStopped, rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), rmAssert, and rcSettingInfo::setValue().
Referenced by rcPlaybackSettingWidget().
 {
   rmAssert(_currentValueBits & rcSettingInfo::eCurrentStateStopped);
   _currentValueBits |= rcSettingInfo::eCurrentStateRev;
   _currentValueBits &= ~(rcSettingInfo::eCurrentStateStopped |
              rcSettingInfo::eCurrentStateFwd);
   mSetting.setValue(_currentValueBits);
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
void rcPlaybackSettingWidget::settingChanged (void) slot
Definition at line 117 of file rc_playbacksettingwidget.cpp.
References _currentValueBits, _fwdWidget, _revWidget, _speedWidget, _stopWidget, rcSettingInfo::eCurrentSpeedMask, rcSettingInfo::eCurrentStateFwd, rcSettingInfo::eCurrentStateRev, rcSettingInfo::eCurrentStateStopped, rcSettingInfo::getValue(), rcSettingInfo::isEditable(), rcSettingInfo::isEnabled(), rcSettingWidget::mSetting, and rmAssert.
Referenced by rcPlaybackSettingWidget().
 {
   _currentValueBits = mSetting.getValue();
   int currentSpeed = _currentValueBits & rcSettingInfo::eCurrentSpeedMask;
   bool fwd = (_currentValueBits & rcSettingInfo::eCurrentStateFwd) != 0;
   bool rev = (_currentValueBits & rcSettingInfo::eCurrentStateRev) != 0;
   bool stopped = (_currentValueBits & rcSettingInfo::eCurrentStateStopped) != 0;
   rmAssert(fwd ^ rev); // Exactly one should be true
   _speedWidget->setValue(currentSpeed);
   // Disable the widget if the setting is currently not editable.
   if (!mSetting.isEditable())
     setEnabled(false);
   else {
     setEnabled(true);
     _revWidget->setEnabled(stopped);
     _fwdWidget->setEnabled(stopped);
     _speedWidget->setEnabled(stopped);
     _stopWidget->setEnabled(!stopped);
   }
   // hide the widget if the setting is currently not enabled.
   if (isHidden() && mSetting.isEnabled()) {
     show();
   }
   else if (!isHidden() && !mSetting.isEnabled()) {
     hide();
   }
 }
void rcPlaybackSettingWidget::stopVideo () slot
Definition at line 161 of file rc_playbacksettingwidget.cpp.
References _currentValueBits, rcSettingInfo::eCurrentStateStopped, rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), rmAssert, and rcSettingInfo::setValue().
Referenced by rcPlaybackSettingWidget().
 {
   rmAssert((_currentValueBits & rcSettingInfo::eCurrentStateStopped) == 0);
   _currentValueBits |= rcSettingInfo::eCurrentStateStopped;
   mSetting.setValue(_currentValueBits);
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
void rcPlaybackSettingWidget::valueChanged (void) slot
Definition at line 151 of file rc_playbacksettingwidget.cpp.
References _currentValueBits, _speedWidget, rcSettingInfo::eCurrentSpeedMask, rcSettingInfo::eCurrentStateMask, rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcPlaybackSettingWidget().
 {
   int value = _speedWidget->value() & rcSettingInfo::eCurrentSpeedMask;
   value |= _currentValueBits & rcSettingInfo::eCurrentStateMask;
   _currentValueBits = value;
   mSetting.setValue(value);
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
int rcPlaybackSettingWidget::_currentValueBits private
Definition at line 37 of file rc_playbacksettingwidget.h.
Referenced by fwdVideo(), revVideo(), settingChanged(), stopVideo(), and valueChanged().
QPushButton* rcPlaybackSettingWidget::_fwdWidget private
Definition at line 35 of file rc_playbacksettingwidget.h.
Referenced by rcPlaybackSettingWidget(), settingChanged(), and ~rcPlaybackSettingWidget().
QPushButton* rcPlaybackSettingWidget::_revWidget private
Definition at line 34 of file rc_playbacksettingwidget.h.
Referenced by rcPlaybackSettingWidget(), settingChanged(), and ~rcPlaybackSettingWidget().
QSpinBox* rcPlaybackSettingWidget::_speedWidget private
Definition at line 33 of file rc_playbacksettingwidget.h.
Referenced by rcPlaybackSettingWidget(), settingChanged(), valueChanged(), and ~rcPlaybackSettingWidget().
QPushButton* rcPlaybackSettingWidget::_stopWidget private
Definition at line 36 of file rc_playbacksettingwidget.h.
Referenced by rcPlaybackSettingWidget(), settingChanged(), and ~rcPlaybackSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_playbacksettingwidget.h
src/visible/qt/rc_playbacksettingwidget.cpp