Visible: rcFixed16 Class Reference
rcFixed16 Class Reference
#include <include/util/rc_math.h>
Public Member Functions
rcFixed16 ()
rcFixed16 (int16 a)
rcFixed16 operator+ (rcFixed16 a) const
rcFixed16 operator- (rcFixed16 a) const
rcFixed16 operator* (int16 a) const
rcFixed16 operator/ (int16 a) const
rcFixed16 operator- () const
int16 operator* (rcFixed16 a) const
int16 operator/ (rcFixed16 a) const
double Double () const
int16 basic () const
rcFixed16 & operator= (int16 a)
rcFixed16 & operator*= (int16 a)
rcFixed16 & operator/= (int16 a)
rcFixed16 & operator*= (rcFixed16 a)
rcFixed16 & operator/= (rcFixed16 a)
rcFixed16 & operator+= (rcFixed16 a)
rcFixed16 & operator-= (rcFixed16 a)
bool operator== (rcFixed16 a) const
bool operator!= (rcFixed16 a) const
bool operator< (rcFixed16 a) const
bool operator<= (rcFixed16 a) const
bool operator> (rcFixed16 a) const
bool operator>= (rcFixed16 a) const
rcFixed16 (double d)
rcFixed16 (float d)
rcFixed16 (int32 d)
float real () const
Private Attributes
int16 val
Friends
rcFixed16 operator* (int16 a, rcFixed16 b)
Detailed Description
Definition at line 302 of file rc_math.h.
Constructor & Destructor Documentation
rcFixed16::rcFixed16 () inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16::rcFixed16 (int16 a) inline explicit
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16::rcFixed16 (double d) inline
Definition at line 307 of file rc_math.h.
 : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16::rcFixed16 (float d) inline
Definition at line 309 of file rc_math.h.
 : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16::rcFixed16 (int32 d) inline
Definition at line 311 of file rc_math.h.
 : val (int16 (d * (1<<rcFixed16Precision))) {}
Member Function Documentation
int16 rcFixed16::basic () const inline
Definition at line 304 of file rc_math.h.
Referenced by rcFeature::octants(), rcFeature::polar(), and rcFeature::pos().
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
double rcFixed16::Double () const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
bool rcFixed16::operator!= (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16 rcFixed16::operator* (int16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
int16 rcFixed16::operator* (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator*= (int16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator*= (rcFixed16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16 rcFixed16::operator+ (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator+= (rcFixed16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16 rcFixed16::operator- (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16 rcFixed16::operator- () const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator-= (rcFixed16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16 rcFixed16::operator/ (int16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
int16 rcFixed16::operator/ (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator/= (int16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator/= (rcFixed16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
bool rcFixed16::operator< (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
bool rcFixed16::operator<= (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
rcFixed16& rcFixed16::operator= (int16 a) inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
bool rcFixed16::operator== (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
bool rcFixed16::operator> (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
bool rcFixed16::operator>= (rcFixed16 a) const inline
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
float rcFixed16::real () const inline
Definition at line 381 of file rc_math.h.
References rcFixed16Precision.
Referenced by rcFeature::operator*(), and rcFeature::polar().
 { return val/((float) (1<<rcFixed16Precision)); }
Friends And Related Function Documentation
rcFixed16 operator* (int16 a, rcFixed16 b) friend
Definition at line 304 of file rc_math.h.
 :
inline rcFixed16 (double d) : val (int16 (d * (1<<rcFixed16Precision))) {}
Member Data Documentation
int16 rcFixed16::val private
Definition at line 304 of file rc_math.h.
The documentation for this class was generated from the following file:
include/util/rc_math.h