Visible: imbuff Class Reference
imbuff Class Reference
#include <include/stlplus/multiio.hpp>
Public Member Functions
imbuff (void)
unsigned add (const itext &)
void remove (unsigned)
virtual int peek (void)
virtual int get (void)
unsigned count (void) const
itext & device (unsigned)
const itext & device (unsigned) const
Public Member Functions inherited from ibuff
ibuff (itext::newline_t newline=itext::convert_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_newline_mode (itext::newline_t newline)
itext::newline_t newline_mode (void) const
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual std::string error_string (void) const
virtual ~ibuff (void)
Private Member Functions
imbuff (const imbuff &)
imbuff & operator= (const imbuff &)
Private Attributes
std::vector< itext > m_devices
Friends
class imtext
Additional Inherited Members
Protected Attributes inherited from ibuff
itext::newline_t m_newline_mode
unsigned long m_bytes
unsigned m_line
unsigned m_column
int m_error_number
int m_aliases
Detailed Description
Definition at line 78 of file multiio.hpp.
Constructor & Destructor Documentation
imbuff::imbuff (void)
Definition at line 194 of file multiio.cpp.
                    :
   // the individual devices define their own conversion modes
   ibuff(itext::binary_mode)
 {
 }
imbuff::imbuff (const imbuff &) private
Member Function Documentation
unsigned imbuff::add (const itext & str)
Definition at line 200 of file multiio.cpp.
References m_devices.
Referenced by imtext::add().
 {
   m_devices.push_back(str);
   return m_devices.size()-1;
 }
unsigned imbuff::count (void) const
Definition at line 226 of file multiio.cpp.
References m_devices.
Referenced by imtext::device_count().
 {
   return m_devices.size();
 }
itext & imbuff::device (unsigned i)
Definition at line 231 of file multiio.cpp.
References m_devices.
Referenced by imtext::device_get().
 {
   return m_devices[i];
 }
const itext & imbuff::device (unsigned i) const
Definition at line 236 of file multiio.cpp.
References m_devices.
 {
   return m_devices[i];
 }
int imbuff::get (void) virtual
Implements ibuff.
Definition at line 219 of file multiio.cpp.
References m_devices.
 {
   while (!m_devices.empty() && m_devices.begin()->eof())
     m_devices.erase(m_devices.begin());
   return m_devices.empty() ? -1 : m_devices.begin()->get();
 }
imbuff& imbuff::operator= (const imbuff &) private
int imbuff::peek (void) virtual
Implements ibuff.
Definition at line 212 of file multiio.cpp.
References m_devices.
 {
   while (!m_devices.empty() && m_devices.begin()->eof())
     m_devices.erase(m_devices.begin());
   return m_devices.empty() ? -1 : m_devices.begin()->peek();
 }
void imbuff::remove (unsigned offset)
Definition at line 206 of file multiio.cpp.
References DEBUG_ASSERT, and m_devices.
Referenced by imtext::remove().
 {
   DEBUG_ASSERT(offset < m_devices.size());
   m_devices.erase(m_devices.begin()+offset);
 }
Friends And Related Function Documentation
friend class imtext friend
Definition at line 80 of file multiio.hpp.
Member Data Documentation
std::vector<itext> imbuff::m_devices private
Definition at line 94 of file multiio.hpp.
Referenced by add(), count(), device(), get(), peek(), and remove().
The documentation for this class was generated from the following files:
include/stlplus/multiio.hpp
include/stlplus/multiio.cpp