Visible: cli_parser_data Class Reference
cli_parser_data Class Reference
Public Member Functions
cli_parser_data (error_handler &errors)
unsigned add_definition (const std::string &name, cli_parser::kind_t kind, cli_parser::mode_t mode, const std::string &message)
unsigned find_definition (const std::string &name)
void clear_definitions (void)
void reset_level (void)
void increase_level (void)
void clear_level (unsigned definition, unsigned level)
void set_valid (void)
void set_invalid (void)
bool valid (void) const
unsigned add_value (unsigned definition, const std::string &value, const std::string &source)
unsigned add_switch (unsigned definition, bool value, const std::string &source)
void erase_value (unsigned definition)
void add_ini_file (const std::string &file)
unsigned ini_file_size (void) const
const std::string & ini_file (unsigned) const
Public Attributes
error_handler & m_errors
std::string m_executable
cli_parser::definitions m_definitions
cli_value_vector m_values
unsigned m_level
bool m_valid
std::vector< std::string > m_ini_files
Private Member Functions
cli_parser_data (const cli_parser_data &)
cli_parser_data & operator= (const cli_parser_data &)
Detailed Description
Definition at line 58 of file cli_parser.cpp.
Constructor & Destructor Documentation
cli_parser_data::cli_parser_data (error_handler & errors)
Definition at line 96 of file cli_parser.cpp.
                                                       :
   m_errors(errors), m_level(1), m_valid(true)
 {
 }
cli_parser_data::cli_parser_data (const cli_parser_data &) private
Member Function Documentation
unsigned cli_parser_data::add_definition (const std::string & name, cli_parser::kind_t kind, cli_parser::mode_t mode, const std::string & message)
Definition at line 101 of file cli_parser.cpp.
References m_definitions.
 {
   m_definitions.push_back(cli_parser::definition(name, kind, mode, message));
   return m_definitions.size()-1;
 }
void cli_parser_data::add_ini_file (const std::string & file)
Definition at line 201 of file cli_parser.cpp.
References m_ini_files.
 {
   m_ini_files.push_back(file);
 }
unsigned cli_parser_data::add_switch (unsigned definition, bool value, const std::string & source)
Definition at line 190 of file cli_parser.cpp.
References add_value().
 {
   return add_value(definition, value ? "on" : "off", source);
 }
unsigned cli_parser_data::add_value (unsigned definition, const std::string & value, const std::string & source)
Definition at line 169 of file cli_parser.cpp.
References clear_level(), cli_cumulative_mode, cli_multiple_mode, cli_single_mode, m_definitions, m_level, and m_values.
Referenced by add_switch().
 {
   // behaviour depends on mode:
   //  - single: erase all previous values
   //  - multiple: erase values at a lower level than current
   //  - cumulative: erase no previous values
   switch (m_definitions[definition].m_mode)
   {
   case cli_single_mode:
     clear_level(definition, m_level);
     break;
   case cli_multiple_mode:
     clear_level(definition, m_level-1);
     break;
   case cli_cumulative_mode:
     break;
   }
   m_values.push_back(cli_value(definition,value,m_level,source));
   return m_values.size()-1;
 }
void cli_parser_data::clear_definitions (void)
Definition at line 123 of file cli_parser.cpp.
References m_definitions, m_values, reset_level(), and set_valid().
 {
   m_definitions.clear();
   m_values.clear();
   reset_level();
   set_valid();
 }
void cli_parser_data::clear_level (unsigned definition, unsigned level)
Definition at line 142 of file cli_parser.cpp.
References m_values.
Referenced by add_value(), and erase_value().
 {
   // clears all values with this definition at the specified level or below
   for (cli_value_vector::iterator i = m_values.begin(); i != m_values.end(); )
   {
     if (i->m_definition == definition && i->m_level <= level)
       i = m_values.erase(i);
     else
       i++;
   }
 }
void cli_parser_data::erase_value (unsigned definition)
Definition at line 195 of file cli_parser.cpp.
References clear_level(), and m_level.
 {
   // this simply erases all previous values
   clear_level(definition, m_level);
 }
unsigned cli_parser_data::find_definition (const std::string & name)
Definition at line 107 of file cli_parser.cpp.
References m_definitions.
 {
   // this does substring matching on the definitions and returns the first
   // match - however, it requires at least one character in the substring so
   // that the "" convention for command line arguments doesn't match with
   // anything. It returns size() if it fails
   for (unsigned i = 0; i < m_definitions.size(); i++)
   {
     std::string candidate = m_definitions[i].m_name;
     if ((candidate.empty() && name.empty()) ||
         (!name.empty() && candidate.size() >= name.size() && candidate.substr(0,name.size()) == name))
       return i;
   }
   return m_definitions.size();
 }
void cli_parser_data::increase_level (void)
Definition at line 137 of file cli_parser.cpp.
References m_level.
 {
   m_level++;
 }
const std::string & cli_parser_data::ini_file (unsigned i) const
Definition at line 211 of file cli_parser.cpp.
References m_ini_files.
Referenced by cli_parser::usage().
 {
   return m_ini_files[i];
 }
unsigned cli_parser_data::ini_file_size (void) const
Definition at line 206 of file cli_parser.cpp.
References m_ini_files.
Referenced by cli_parser::usage().
 {
   return m_ini_files.size();
 }
cli_parser_data& cli_parser_data::operator= (const cli_parser_data &) private
void cli_parser_data::reset_level (void)
Definition at line 131 of file cli_parser.cpp.
References m_level.
Referenced by clear_definitions().
 {
   // the starting level is 1 so that later functions can call clear_level with a value of m_level-1 without causing underflow
   m_level = 1;
 }
void cli_parser_data::set_invalid (void)
Definition at line 159 of file cli_parser.cpp.
References m_valid.
 {
   m_valid = false;
 }
void cli_parser_data::set_valid (void)
Definition at line 154 of file cli_parser.cpp.
References m_valid.
Referenced by clear_definitions().
 {
   m_valid = true;
 }
bool cli_parser_data::valid (void) const
Definition at line 164 of file cli_parser.cpp.
References m_valid.
Referenced by cli_parser::valid().
 {
   return m_valid;
 }
Member Data Documentation
cli_parser::definitions cli_parser_data::m_definitions
Definition at line 63 of file cli_parser.cpp.
Referenced by add_definition(), add_value(), clear_definitions(), find_definition(), and cli_parser::usage().
error_handler& cli_parser_data::m_errors
Definition at line 61 of file cli_parser.cpp.
Referenced by cli_parser::usage().
std::string cli_parser_data::m_executable
Definition at line 62 of file cli_parser.cpp.
Referenced by cli_parser::usage().
std::vector<std::string> cli_parser_data::m_ini_files
Definition at line 67 of file cli_parser.cpp.
Referenced by add_ini_file(), ini_file(), and ini_file_size().
unsigned cli_parser_data::m_level
Definition at line 65 of file cli_parser.cpp.
Referenced by add_value(), erase_value(), increase_level(), and reset_level().
bool cli_parser_data::m_valid
Definition at line 66 of file cli_parser.cpp.
Referenced by set_invalid(), set_valid(), and valid().
cli_value_vector cli_parser_data::m_values
Definition at line 64 of file cli_parser.cpp.
Referenced by add_value(), clear_definitions(), clear_level(), cli_parser::size(), and cli_parser::usage().
The documentation for this class was generated from the following file:
include/stlplus/cli_parser.cpp