Visible: rcLatticeSimilarator Class Reference
rcLatticeSimilarator Class Reference
#include <include/analysis/rc_latticesimilarity.h>
Public Types
typedef vector< rcIRect > rowOfRects
typedef vector< rcSimilaratorRef > rowOfSims
Public Member Functions
rcLatticeSimilarator ()
rcLatticeSimilarator (int32 tpipt, int32 lrad)
template<class Iterator >
bool fill (Iterator starting, Iterator afterLast)
template<class Iterator >
bool update (Iterator nextImage)
void ttc (rcWindow &, rcWindow &)
double wholeEntropy () const
Static Public Attributes
static const int32 defaultTileSize = 4
Private Attributes
int32 mTemporal
rcIPair mSize
rcIPair mImageSize
rcPixel mDepth
int32 mLrad
vector< rowOfRects > mTiles
vector< rowOfSims > mSims
rcSimilaratorRef mWholeSim
Detailed Description
Definition at line 39 of file rc_latticesimilarity.h.
Member Typedef Documentation
typedef vector<rcIRect> rcLatticeSimilarator::rowOfRects
Definition at line 44 of file rc_latticesimilarity.h.
typedef vector<rcSimilaratorRef> rcLatticeSimilarator::rowOfSims
Definition at line 45 of file rc_latticesimilarity.h.
Constructor & Destructor Documentation
rcLatticeSimilarator::rcLatticeSimilarator ()
rcLatticeSimilarator::rcLatticeSimilarator (int32 tpipt, int32 lrad)
Definition at line 55 of file rc_kinemotion.cpp.
References mLrad, and rmExceptionMacro.
   : mTemporal (tpipe), mLrad (lrad)
 {
   if (!mLrad)
     rmExceptionMacro (<< "Lrad can not be zero");
 }
Member Function Documentation
template<class Iterator > bool rcLatticeSimilarator::fill (Iterator starting, Iterator afterLast)
Definition at line 76 of file rc_latticesimilarity.h.
References defaultTileSize, rcSimilarator::eExhaustive, mDepth, mImageSize, mLrad, mSims, mSize, mTemporal, mTiles, mWholeSim, rmAssert, and value_type().
 {
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   if (mTemporal != distance (starting, afterLast)) return false;
   int32 width, height;
   value_type image (*starting);
   width = image.width(); height = image.height();
   rcIPair tileSize (defaultTileSize, defaultTileSize);
   // @note overlapping tiles. Amount of overlap is determined by step size.
   // if mLrad is set to defaultTileSize divided by 2, then neighboring tiles overlap 50 percent
   // that is 100 - mLrad / defaultTileSize.
   int32 rows ((height - defaultTileSize) / mLrad);
   int32 columns ((width - defaultTileSize) / mLrad);
   if (rows <= 0 || columns <=0) return false;
   mSize = rcIPair (columns, rows);
   mImageSize = rcIPair (width, height);
   mDepth = image.depth();
   // Allocate an array of tile rectangles
   mTiles.resize (rows);
   mSims.resize (rows);
   int32 tly (0);
   for (int32 j = 0; j < rows; j++)
     {
       mTiles[j].resize (columns);
       mSims[j].resize (columns);
       int32 tlx (0);
       for (int32 i = 0; i < columns; i++, tlx += mLrad)
     {
       rcIPair tl (tlx, tly);
       mTiles[j][i] = rcIRect (tl, tl + tileSize);
     }
       tly += mLrad;
     }
   bool rtn (false);
   for (int32 j = 0; j < rows; j++)
     for (int32 i = 0; i < columns; i++)
       {
     vector<rcWindow> wins;
     Iterator w = starting;
     while (w < afterLast)
       {
         value_type img (*w);
         rtn = (img.size() == mImageSize);
         if (rtn == false) return rtn;
         static const int32 inside (0);
         rcWindow tile (img, mTiles[j][i], inside);
         wins.push_back (tile);
         w++;
       }
           mSims[j][i] = boost::shared_ptr<rcSimilarator> (new rcSimilarator (rcSimilarator::eExhaustive,
                                                                              mDepth, mTemporal, mTemporal * 2));
     rtn = (mSims[j][i] && mSims[j][i]->fill (wins));
     if (rtn == false) return rtn;
     rmAssert (mSims[j][i]->longTermCache () == false);
     rtn = mSims[j][i]->longTermCache (true);
     if (rtn == false) return rtn;
       }
   if (rtn)
     {
     vector<rcWindow> wins;
     Iterator w = starting;
     while (w < afterLast)
       {
         value_type img (*w);
         rtn = (img.size() == mImageSize);
         if (rtn == false) return rtn;
         wins.push_back (img);
         w++;
       }
         mWholeSim = boost::shared_ptr<rcSimilarator> (new rcSimilarator (rcSimilarator::eExhaustive,
                      mDepth, mTemporal, mTemporal * 2));
       rtn = (mWholeSim && mWholeSim->fill (wins));
       if (rtn == false) return rtn;
       rmAssert (mWholeSim->longTermCache () == false);
       rtn = mWholeSim->longTermCache (true);
       if (rtn == false) return rtn;
     }
   return rtn;
 }
void rcLatticeSimilarator::ttc (rcWindow & horz, rcWindow & vert)
Definition at line 62 of file rc_kinemotion.cpp.
References rc2dVector< T >::angle(), rcAngle8::basic(), rcWindow::depth(), rcWindow::isBound(), rc2dVector< T >::isNull(), rc2dVector< T >::l2(), mImageSize, mSims, mSize, mTiles, mWholeSim, rcPixel8, rf1DRegister(), rmExceptionMacro, rcWindow::setAllPixels(), rcWindow::size(), rcPair< T >::x(), and rcPair< T >::y().
 {
   rcWindow hscreen = horz;
   rcWindow vscreen = vert;
   if (!hscreen.isBound() || hscreen.size() != mImageSize ||
       hscreen.depth() != rcPixel8)
     {
       hscreen = rcWindow (mImageSize, rcPixel8);
       horz = hscreen;
     }
   hscreen.setAllPixels (0);
   if (!vscreen.isBound() || vscreen.size() != mImageSize ||
       vscreen.depth() != rcPixel8)
     {
       vscreen = rcWindow (mImageSize, rcPixel8);
       vert = vscreen;
     }
   vscreen.setAllPixels (0);
   const vector<float>& dreal =  mWholeSim->longTermEntropy ();
   if (!(mWholeSim->longTermCache() && dreal.size()))
    rmExceptionMacro (<< "Lattice Similarity Cache Off");
   for (int32 j = 0; j < mSize.y(); j++)
     {
       for (int32 i = 0; i < mSize.x(); i++)
     {
       const vector<float>& real = mSims[j][i]->longTermEntropy ();
       if (!(mSims[j][i]->longTermCache() && dreal.size()) && real.size() != dreal.size())
         rmExceptionMacro (<< "Lattice Similarity Cache Off");
       if (dreal.size() <= 7)
         continue;
       rcWindow bb (hscreen, mTiles[j][i]);
       rcWindow cc (vscreen, mTiles[j][i]);
       double mTr (0.0), rTp (0.0), pe;
       // Dt / Dy estimate by y+ - y-
       if (j > 0 && j < (mSize.y() - 1))
         {
           const vector<float>& jmreal = mSims[j-1][i]->longTermEntropy ();
           if (!(mSims[j-1][i]->longTermCache() && jmreal.size()) && jmreal.size() != real.size())
         rmExceptionMacro (<< "Lattice Similarity Cache Off");
           // jm is at re registration with respect to real
           mTr = rf1DRegister (jmreal.begin(), jmreal.end(), real.begin(), real.end(), 1, pe);
           const vector<float>& jpreal = mSims[j+1][i]->longTermEntropy ();
           if (!(mSims[j+1][i]->longTermCache() && jpreal.size()) && jpreal.size() != real.size())
         rmExceptionMacro (<< "Lattice Similarity Cache Off");
           // real is at re registration with respect to jp
           // m to p is positive: if mTr and rTp agree (if both negative or positive)
           // composing these two motions is the sum of mTr and rTp.
           // returns are within range of - 0.5 to + 0.5. => sum - 1.0 to 1.0
           mTr += rf1DRegister (jpreal.begin(), jpreal.end(), real.begin(), real.end(),1, pe);
         }
       if (i > 0 && i < (mSize.x() - 1))
         {
           const vector<float>& jmreal = mSims[j][i-1]->longTermEntropy ();
           if (!(mSims[j][i-1]->longTermCache() && jmreal.size()) && jmreal.size() != real.size())
         rmExceptionMacro (<< "Lattice Similarity Cache Off");
           // jm is at re registration with respect to real
           rTp = rf1DRegister (jmreal.begin(), jmreal.end(), real.begin(), real.end(), 1, pe);
           const vector<float>& jpreal = mSims[j][i+1]->longTermEntropy ();
           if (!(mSims[j][i+1]->longTermCache() && jpreal.size()) && jpreal.size() != dreal.size())
         rmExceptionMacro (<< "Lattice Similarity Cache Off");
           // real is at re registration with respect to jp
           // m to p is positive: if mTr and rTp agree (if both negative or positive)
           // composing these two motions is the sum of mTr and rTp.
           // returns are within range of - 0.5 to + 0.5 ==> Sum - 1.0 to 1.0
           rTp += rf1DRegister (jpreal.begin(), jpreal.end(), real.begin(), real.end(), 1, pe);
         }
       rc2Dvector dt (rTp, mTr);
       if (dt.isNull ())
         continue;
       rcRadian ad = dt.angle ();
       rcAngle8 ab (ad);
       bb.setAllPixels (ab.basic ());
       cc.setAllPixels (127.0 * dt.l2 ());
     }
       //      cerr << endl;
     }
   //  cerr << "PipeLine: " << real.size() << endl;
 }
template<class Iterator > bool rcLatticeSimilarator::update (Iterator nextImage)
Definition at line 178 of file rc_latticesimilarity.h.
References mSims, mSize, mTiles, mWholeSim, value_type(), rcPair< T >::x(), and rcPair< T >::y().
 {
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   value_type image (*nextImage);
   bool rtn (false);
   rtn = mWholeSim->update (image);
   if (rtn == false) return rtn;
   for (int32 j = 0; j < mSize.y(); j++)
     for (int32 i = 0; i < mSize.x(); i++)
       {
     static const int32 inside (0);
     rcWindow tile (image, mTiles[j][i], inside);
     rtn = mSims[j][i]->update (tile);
     if (rtn == false) return rtn;
       }
   return rtn;
 }
double rcLatticeSimilarator::wholeEntropy () const
Member Data Documentation
const int32 rcLatticeSimilarator::defaultTileSize = 4 static
Definition at line 43 of file rc_latticesimilarity.h.
Referenced by fill().
rcPixel rcLatticeSimilarator::mDepth private
Definition at line 65 of file rc_latticesimilarity.h.
Referenced by fill().
rcIPair rcLatticeSimilarator::mImageSize private
Definition at line 64 of file rc_latticesimilarity.h.
Referenced by fill(), and ttc().
int32 rcLatticeSimilarator::mLrad private
Definition at line 66 of file rc_latticesimilarity.h.
Referenced by fill(), and rcLatticeSimilarator().
vector<rowOfSims> rcLatticeSimilarator::mSims private
Definition at line 68 of file rc_latticesimilarity.h.
Referenced by fill(), ttc(), and update().
rcIPair rcLatticeSimilarator::mSize private
Definition at line 63 of file rc_latticesimilarity.h.
Referenced by fill(), ttc(), and update().
int32 rcLatticeSimilarator::mTemporal private
Definition at line 62 of file rc_latticesimilarity.h.
Referenced by fill().
vector<rowOfRects> rcLatticeSimilarator::mTiles private
Definition at line 67 of file rc_latticesimilarity.h.
Referenced by fill(), ttc(), and update().
rcSimilaratorRef rcLatticeSimilarator::mWholeSim private
Definition at line 69 of file rc_latticesimilarity.h.
Referenced by fill(), ttc(), and update().
The documentation for this class was generated from the following files:
include/analysis/rc_latticesimilarity.h
src/analysis/code/rc_kinemotion.cpp