Visible: rcVideoCache Class Reference
rcVideoCache Class Reference
#include <include/visual/rc_videocache.h>
Classes
class rcVideoCachePrefetchUnit
Public Member Functions
rcVideoCacheStatus getFrame (uint32 frameIndex, rcSharedFrameBufPtr &frameBuf, rcVideoCacheError *error=0, bool locked=true)
rcVideoCacheStatus getFrame (const rcTimestamp &time, rcSharedFrameBufPtr &frameBuf, rcVideoCacheError *error=0, bool locked=true)
rcVideoCacheStatus closestTimestamp (const rcTimestamp &goalTime, rcTimestamp &match, rcVideoCacheError *error=0)
rcVideoCacheStatus nextTimestamp (const rcTimestamp &goalTime, rcTimestamp &match, rcVideoCacheError *error=0)
rcVideoCacheStatus prevTimestamp (const rcTimestamp &goalTime, rcTimestamp &match, rcVideoCacheError *error=0)
rcVideoCacheStatus firstTimestamp (rcTimestamp &match, rcVideoCacheError *error=0)
rcVideoCacheStatus lastTimestamp (rcTimestamp &match, rcVideoCacheError *error=0)
rcVideoCacheStatus frameIndexToTimestamp (uint32 frameIndex, rcTimestamp &match, rcVideoCacheError *error=0)
rcVideoCacheStatus timestampToFrameIndex (const rcTimestamp &timestamp, uint32 &match, rcVideoCacheError *error=0)
rcVideoCacheError getFatalError () const
bool isValid () const
uint32 frameCount () const
uint32 frameWidth () const
uint32 frameHeight () const
rcPixel frameDepth () const
off_t frameDataOffset (const uint32 &frameIndex) const
movieFormatRev rev () const
double averageFrameRate () const
const int64 & baseTime () const
uint32 cacheMisses () const
uint32 cacheHits () const
uint32 cacheSize () const
const vector< rcMovieFileOrgExt > & movieFileOrigins () const
const vector
< rcMovieFileConvExt > & movieFileConversions () const
const vector< rcMovieFileCamExt > & movieFileCameras () const
const vector< rcMovieFileExpExt > & movieFileExperiments () const
const std::string getInputSourceName () const
Static Public Member Functions
static rcVideoCache * rcVideoCacheCtor (const std::string fileName, uint32 cacheSize, bool getTOC, bool verbose=true, bool prefetch=false, uint32 maxMemory=0, rcProgressIndicator *pIndicator=0)
static void rcVideoCacheDtor (rcVideoCache *cache)
static std::string getErrorString (rcVideoCacheError error)
Private Types
typedef vector
< rcSharedFrameBufPtr * > vcPendingFills
Private Member Functions
rcVideoCache (const std::string fileName, uint32 cacheSize, bool getTOC, bool verbose, bool prefetch, uint32 maxMemory, rcProgressIndicator *pIndicator)
virtual ~rcVideoCache ()
rcVideoCache (const vector< rcTimestamp > &frameTimes)
void setError (rcVideoCacheError error)
rcVideoCacheStatus internalGetFrame (uint32 frameIndex, rcSharedFrameBufPtr &frameBuf, rcVideoCacheError *error, const uint32 dToken)
rcVideoCacheStatus cacheAlloc (uint32 frameIndex, rcSharedFrameBufPtr &userFrameBuf, rcSharedFrameBufPtr *&cacheFrameBufPtr, const uint32 dToken)
rcVideoCacheStatus cacheInsert (uint32 frameIndex, rcSharedFrameBufPtr &cacheFrameBuf, const uint32 dToken)
void createDefaultOriginHeader (movieFormatRev rev)
rcVideoCacheError headerLoadRev0 ()
rcVideoCacheError headerLoadRev1 (bool getTOC)
rcVideoCacheError headerLoadRev2 (bool getTOC)
rcVideoCacheError tocLoad ()
rcVideoCacheError tocLoadFromFrames ()
rcVideoCacheError tocLoadFromTOC ()
rcVideoCacheError orgLoad ()
rcVideoCacheError cnvLoad ()
rcVideoCacheError camLoad ()
rcVideoCacheError expLoad ()
void setCacheID (uint32 cacheID)
void unlockFrame (uint32 frameIndex)
void prefetchFrame (uint32 frameIndex)
uint32 getNextToken ()
Static Private Member Functions
static rcVideoCache * finishSetup (rcVideoCache *cacheP)
static rcVideoCache * rcVideoCacheUTCtor (const vector< rcTimestamp > &frameTimes)
static void cachePrefetch (uint32 cacheIndex, uint32 frameIndex)
static void cacheUnlock (uint32 cacheIndex, uint32 frameIndex)
static rcVideoCacheStatus cacheLock (uint32 cacheIndex, uint32 frameIndex, rcSharedFrameBufPtr &frameBuf, rcVideoCacheError *error=0)
Private Attributes
map< int64, uint32 > _unlockedFramesLtoI
map< uint32, int64 > _unlockedFramesItoL
int64 _lastTouchIndex
map< uint32,
rcSharedFrameBufPtr * > _cachedFramesItoB
deque< rcSharedFrameBufPtr * > _unusedCacheFrames
vector< rcTimestamp > _tocItoT
map< rcTimestamp, uint32 > _tocTtoI
vector< rcSharedFrameBufPtr > _frameCache
map< uint32, vcPendingFills > _pending
bool _verbose
bool _isValid
rcVideoCacheError _fatalError
const std::string _fileName
FILE * _movieFile
movieFormatRev _rev
uint32 _bytesInFrame
uint32 _frameCount
uint32 _frameWidth
uint32 _frameHeight
rcPixel _frameDepth
double _averageFrameRate
int64 _baseTime
reByteOrder _byteOrder
int64 _tocExtHdrOffset
vector< int64 > _orgExtHdrOffsets
vector< rcMovieFileOrgExt > _orgHdrs
vector< int64 > _cnvExtHdrOffsets
vector< rcMovieFileConvExt > _cnvExtHdrs
vector< int64 > _camExtHdrOffsets
vector< rcMovieFileCamExt > _camExtHdrs
vector< int64 > _expExtHdrOffsets
vector< rcMovieFileExpExt > _expExtHdrs
rcMutex _cacheMutex
rcMutex _diskMutex
rcSignalPending _pendingCtrl
uint32 _cacheOverflowLimit
uint32 _cacheSize
uint32 _cacheID
uint32 _cacheMisses
uint32 _cacheHits
rcVideoCachePrefetchUnit * _prefetchThread
rcProgressIndicator * _progressIndicator
uint32 _debuggingToken
Static Private Attributes
static map< uint32,
rcVideoCache * > _activeCachesItoP
static map< rcVideoCache
*, uint32 > _activeCachesPtoI
static uint32 _nextCacheID = 0
static rcMutex _cacheMgmtMutex
Friends
class rcSharedFrameBufPtr
class UT_PlaybackUtils
Detailed Description
Definition at line 67 of file rc_videocache.h.
Member Typedef Documentation
typedef vector<rcSharedFrameBufPtr*> rcVideoCache::vcPendingFills private
Definition at line 334 of file rc_videocache.h.
Constructor & Destructor Documentation
rcVideoCache::rcVideoCache (const std::string fileName, uint32 cacheSize, bool getTOC, bool verbose, bool prefetch, uint32 maxMemory, rcProgressIndicator * pIndicator) private
Definition at line 200 of file rc_videocache.cpp.
References _averageFrameRate, _baseTime, _byteOrder, _bytesInFrame, _cacheOverflowLimit, _cacheSize, _debuggingToken, _fileName, _frameCache, _frameCount, _frameDepth, _frameHeight, _frameWidth, _movieFile, _prefetchThread, _rev, _unusedCacheFrames, _verbose, cacheSize(), createDefaultOriginHeader(), eByteOrderUnknown, eVideoCacheErrorFileFormat, eVideoCacheErrorFileInit, eVideoCacheErrorFileRead, eVideoCacheErrorFileRevUnsupported, eVideoCacheErrorOK, eVideoCacheErrorSystemResources, headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), isValid(), movieFormatInvalid, movieFormatRev0, movieFormatRev1, movieFormatRev2, movieFormatRevLatest, NULL, rcPixel8, rev(), rmAssert, setError(), and rcThread::start().
Referenced by rcVideoCacheCtor(), and rcVideoCacheUTCtor().
         : _lastTouchIndex(0), _verbose(verbose),
           _isValid(true), _fatalError(eVideoCacheErrorOK), _fileName(fileName),
           _movieFile(NULL), _rev(movieFormatInvalid), _tocExtHdrOffset(-1), _pendingCtrl(_cacheMutex),
           _cacheID(0), _cacheMisses(0), _cacheHits(0), _prefetchThread(0),
           _progressIndicator(pIndicator)
 {
 #ifdef VID_TRACE
     _debuggingToken = 0;
 #endif
     _frameWidth = _frameHeight = _frameCount = 0;
     _frameDepth = rcPixel8;
     _averageFrameRate = 0.0;
     _baseTime = 0;
     _byteOrder = eByteOrderUnknown;
     if (_fileName.empty()) {
         setError(eVideoCacheErrorFileInit);
         return;
     }
     if ((_movieFile = fopen(_fileName.data(), "r")) == NULL)
     {
         if (_verbose) perror("fopen failed");
         setError(eVideoCacheErrorFileInit);
         return;
     }
     /* Read movie identifier and check that we support this type of file.
      */
     rcMovieFileIdentifier id;
     if (fread(&id, sizeof(rcMovieFileIdentifier), 1, _movieFile) != 1) {
         if (_verbose) perror("Read of identifier failed");
         setError(eVideoCacheErrorFileRead);
         return;
     }
     id.fixEndian();
     if (fseek( _movieFile, 0, SEEK_SET)) {
         if (_verbose) perror("fseek to start failed");
         setError(eVideoCacheErrorFileRead);
         return;
     }
     // Check identifier validity
     if ( !id.isValid() ) {
         if (_verbose) perror("Invalid file identifier");
         setError(eVideoCacheErrorFileFormat);
         return;
     } else if ((id.rev() > movieFormatRevLatest)) {
         if (_verbose) perror("Unsupported file revision");
         setError(eVideoCacheErrorFileRevUnsupported);
         return;
     }
     _rev = id.rev();
     rcVideoCacheError error = eVideoCacheErrorOK;
     // Load headers
     switch ( _rev ) {
         case movieFormatRev0:
             error = headerLoadRev0();
             createDefaultOriginHeader( _rev );
             break;
         case movieFormatRev1:
             // We may read TOC from frames so progress indication is
             // needed for long movies
             error = headerLoadRev1( getTOC );
             createDefaultOriginHeader( _rev );
             break;
         case movieFormatRev2:
             error = headerLoadRev2( getTOC );
             break;
         case movieFormatInvalid:
             error = eVideoCacheErrorFileFormat;
             break;
     }
     if ( error != eVideoCacheErrorOK )
         return;
     /* First, calculate the cache overflow number based on both the
      * number of frames in the movie and the maximum amount of memory
      * the caller wants to use for this purpose.
      */
     _cacheSize = _frameCount;
     if (maxMemory != 0) {
         if (_cacheSize > (maxMemory / _bytesInFrame)) {
             _cacheSize = maxMemory / _bytesInFrame;
             if (_cacheSize == 0) {
                 setError(eVideoCacheErrorSystemResources);
                 return;
             }
         }
     }
     /* If user specified a cache size use it as an upper bound on the
      * cache overflow limit.
      */
     if (cacheSize && (cacheSize < _cacheSize))
         _cacheSize = cacheSize;
     _frameCache.resize(_frameCount);
     /* Make all the cache entries available for use by pushing them all
      * onto the unused list.
      */
     for (uint32 i = 0; i < _frameCache.size(); i++)
         _unusedCacheFrames.push_back(&_frameCache[i]);
     rmAssert(_unusedCacheFrames.size() >= _cacheSize);
     _cacheOverflowLimit = _unusedCacheFrames.size() - _cacheSize;
     /* Just about done. If prefetch is enabled, create a prefetch thread
      * here.
      */
     if (prefetch) {
         _prefetchThread = new rcVideoCachePrefetchUnit(*this);
         rmAssert(_prefetchThread);
         _prefetchThread->start();
     }
 }
rcVideoCache::~rcVideoCache () private virtual
Definition at line 371 of file rc_videocache.cpp.
References _diskMutex, _movieFile, _prefetchThread, _progressIndicator, _verbose, endl(), rcThread::join(), NULL, rcVideoCache::rcVideoCachePrefetchUnit::prefetch(), and rcRunnable::requestSeppuku().
 {
     rcLock lock(_diskMutex);
     if (_movieFile && fclose(_movieFile) && _verbose)
         perror("fclose failed");
     _movieFile = NULL;
     if (_prefetchThread) {
         /* Want prefetch thread to end itself, but it may be asleep
          * waiting on input. deal with this using 3 step algorithm:
          * 1) Ask thread to kill itself.
          * 2) Send a phony prefetch request to jostle it awake.
          * 3) Join the thread.
          */
         _prefetchThread->requestSeppuku();
         _prefetchThread->prefetch(0);
         int status = _prefetchThread->join();
         if (_verbose) {
             cout << "Prefetch thread close: ";
             if (status)
                 cout << "error " << status << endl;
             else
                 cout << "OK" << endl;
         }
         delete _prefetchThread;
         _prefetchThread = 0;
     }
     _progressIndicator = 0;
 }
rcVideoCache::rcVideoCache (const vector< rcTimestamp > & frameTimes) private
Definition at line 327 of file rc_videocache.cpp.
References _averageFrameRate, _baseTime, _byteOrder, _cacheOverflowLimit, _cacheSize, _debuggingToken, _frameCache, _frameCount, _frameDepth, _frameHeight, _frameWidth, _tocItoT, _tocTtoI, _unusedCacheFrames, createDefaultOriginHeader(), eByteOrderUnknown, movieFormatRev1, rcPixel8, and rmAssert.
         : _lastTouchIndex(0), _verbose(false),
           _isValid(true), _fatalError(eVideoCacheErrorOK), _fileName(""),
           _movieFile(NULL), _rev(movieFormatInvalid), _tocExtHdrOffset(-1), _pendingCtrl(_cacheMutex),
           _cacheID(0), _cacheMisses(0), _cacheHits(0), _prefetchThread(0)
 {
 #ifdef VID_TRACE
     _debuggingToken = 0;
 #endif
     rmAssert(frameTimes.size());
     _byteOrder = eByteOrderUnknown;
     createDefaultOriginHeader( movieFormatRev1 );
     _frameWidth = _frameHeight = 0;
     _frameDepth = rcPixel8;
     _averageFrameRate = 0.0;
     _frameCount = frameTimes.size();
     _baseTime = 0;
     /* This stuff is normally done in tocLoad().
      */
     _tocItoT.resize(_frameCount);
     for (uint32 frameIndex = 0; frameIndex < _frameCount; frameIndex++) {
         if (frameIndex != 0)
             rmAssert(frameTimes[frameIndex] > frameTimes[frameIndex-1]);
         _tocItoT[frameIndex] = frameTimes[frameIndex];
         _tocTtoI[frameTimes[frameIndex]] = frameIndex;
     }
     _cacheSize = _frameCount;
     _frameCache.resize(_frameCount);
     /* Make all the cache entries available for use by pushing them all
      * onto the unused list.
      */
     for (uint32 i = 0; i < _frameCache.size(); i++)
         _unusedCacheFrames.push_back(&_frameCache[i]);
     rmAssert(_unusedCacheFrames.size() >= _cacheSize);
     _cacheOverflowLimit = _unusedCacheFrames.size() - _cacheSize;
 }
Member Function Documentation
double rcVideoCache::averageFrameRate () const inline
Definition at line 191 of file rc_videocache.h.
Referenced by rcEngineImpl::muscleTracker(), and rcEngineImpl::updateCaptureLog().
 { return _averageFrameRate; };
const int64& rcVideoCache::baseTime () const inline
Definition at line 192 of file rc_videocache.h.
Referenced by createDefaultOriginHeader().
 { return _baseTime; }
rcVideoCacheStatus rcVideoCache::cacheAlloc (uint32 frameIndex, rcSharedFrameBufPtr & userFrameBuf, rcSharedFrameBufPtr *& cacheFrameBufPtr, const uint32 dToken) private
Definition at line 965 of file rc_videocache.cpp.
References _cachedFramesItoB, _cacheHits, _cacheID, _cacheMisses, _cacheMutex, _cacheOverflowLimit, _pending, _unlockedFramesItoL, _unlockedFramesLtoI, _unusedCacheFrames, ADD_VID_TRACE, DUMP_VID_TRACE, eVideoCacheStatusError, eVideoCacheStatusOK, fnCacheAlloc, frameDepth(), frameHeight(), frameWidth(), rcFrame::mCacheCtrl, rcSharedFrameBufPtr::mFrameBuf, rcSharedFrameBufPtr, rcUNUSED, rcFrame::refCount(), rmAssert, and rcSharedFrameBufPtr::setCachedFrame().
Referenced by internalGetFrame().
 {
 #ifndef VID_TRACE
     rcUNUSED(dToken);
 #endif
     rcLock lock(_cacheMutex);
     ADD_VID_TRACE(fnCacheAlloc, true, frameIndex, userFrameBuf.mFrameBuf, dToken);
     /* First, look to see if the frame has been cached. If so, return
      * it to the caller.
      */
     map<uint32, rcSharedFrameBufPtr*>::iterator cachedEntryPtr;
     cachedEntryPtr = _cachedFramesItoB.find(frameIndex);
     if (cachedEntryPtr != _cachedFramesItoB.end()) {
         rcSharedFrameBufPtr* bufPtr = cachedEntryPtr->second;
         rmAssert((*bufPtr)->frameIndex() == frameIndex);
         /* If frame is in the unlocked map, remove it so no one else
          * tries to grab it.
          */
         map<uint32, int64>::iterator unlockedPtrItoL;
         unlockedPtrItoL = _unlockedFramesItoL.find(frameIndex);
         if (unlockedPtrItoL != _unlockedFramesItoL.end()) {
 #ifdef VID_TRACE
             if (bufPtr->refCount() != 1) {
                 fprintf(stderr, "C token %d fi %d frame* 0x%X\n", dToken, frameIndex,
                         (int)bufPtr->mFrameBuf);
                 DUMP_VID_TRACE();
             }
 #endif
             rmAssert(bufPtr->refCount() == 1);
             int64 lastUseIndex = unlockedPtrItoL->second;
             map<int64, uint32>::iterator unlockedPtrLtoI;
             unlockedPtrLtoI = _unlockedFramesLtoI.find(lastUseIndex);
             rmAssert(unlockedPtrLtoI != _unlockedFramesLtoI.end());
             rmAssert(unlockedPtrLtoI->second == frameIndex);
             _unlockedFramesItoL.erase(unlockedPtrItoL);
             _unlockedFramesLtoI.erase(unlockedPtrLtoI);
         }
         rmAssert(bufPtr->mCacheCtrl == 0);
         userFrameBuf.setCachedFrame(*bufPtr, _cacheID, frameIndex);
         _cacheHits++;
         ADD_VID_TRACE(fnCacheAlloc, false, frameIndex, userFrameBuf.mFrameBuf,
                       dToken);
         return eVideoCacheStatusOK;
     } // End of: if (cachedEntryPtr != _cachedFramesItoB.end())
     cacheFrameBufPtr = 0;
     /* Not currently in cache. If load is pending add the user frame
      * buffer to the pending list and return to caller to allow
      * him to wait for load to complete.
      */
     map<uint32, vector<rcSharedFrameBufPtr*> >::iterator pendingEntry;
     pendingEntry = _pending.find(frameIndex);
     if (pendingEntry != _pending.end()) {
         vector<rcSharedFrameBufPtr*>& pendingBuffers = pendingEntry->second;
         pendingBuffers.push_back(&userFrameBuf);
         return eVideoCacheStatusError;
     }
     /* Frame is neither in cache nor pending. Allocate a frame buffer
      * and return it to the caller. The caller is responsible for
      * loading the frame from disk and seeing that it gets linked
      * into the cache.
      */
     if ((_unusedCacheFrames.size() > _cacheOverflowLimit) ||
         (_unlockedFramesLtoI.empty())) {
         /* Grab an unused cache entry if either:
          * a) We haven't reached the cache's overflow limit, or
          * b) The unlocked portion of the cache is empty.
          */
         rmAssert(!_unusedCacheFrames.empty());
         cacheFrameBufPtr = _unusedCacheFrames.front();
         rmAssert(cacheFrameBufPtr->refCount() < 2);
         rmAssert(cacheFrameBufPtr->mCacheCtrl == 0);
         _unusedCacheFrames.pop_front();
         if (*cacheFrameBufPtr == 0) {
             *cacheFrameBufPtr =
                 rcSharedFrameBufPtr(new rcFrame(frameWidth(),
                                                  frameHeight(),
                                                  frameDepth()));
             rmAssert(*cacheFrameBufPtr != 0);
             (*cacheFrameBufPtr)->cacheCtrl(_cacheID);
         }
 #ifdef VID_TRACE
         if (cacheFrameBufPtr->refCount() != 1) {
             fprintf(stderr, "A token %d fi %d refCount %d frame* 0x%X\n", dToken,
                     frameIndex, cacheFrameBufPtr->refCount(),
                     (int)cacheFrameBufPtr->mFrameBuf);
             DUMP_VID_TRACE();
         }
 #endif
     }
     else if (!_unlockedFramesLtoI.empty()) {
         /* Reuse the least-recently-used unlocked frame. Step 1 is to
          * figure out the LRU frame's frame index and then clear the
          * related info from the unlocked frame maps.
          */
         map<int64, uint32>::iterator unlockedPtrLtoI;
         unlockedPtrLtoI = _unlockedFramesLtoI.begin();
         rmAssert(unlockedPtrLtoI != _unlockedFramesLtoI.end());
         uint32 oldFrameIndex = unlockedPtrLtoI->second;
         map<uint32, int64>::iterator unlockedPtrItoL;
         unlockedPtrItoL = _unlockedFramesItoL.find(oldFrameIndex);
         rmAssert(unlockedPtrItoL != _unlockedFramesItoL.end());
         rmAssert(unlockedPtrItoL->first == unlockedPtrLtoI->second);
         rmAssert(unlockedPtrItoL->second == unlockedPtrLtoI->first);
         _unlockedFramesItoL.erase(unlockedPtrItoL);
         _unlockedFramesLtoI.erase(unlockedPtrLtoI);
         /* Step 2 - Remove association of frame buffer with old frame
          * index.
          */
         cachedEntryPtr = _cachedFramesItoB.find(oldFrameIndex);
         rmAssert(cachedEntryPtr != _cachedFramesItoB.end());
         cacheFrameBufPtr = cachedEntryPtr->second;
         if (!((*cacheFrameBufPtr)->frameIndex() == oldFrameIndex))
             printf("error %d %d\n", (*cacheFrameBufPtr)->frameIndex(),
                    oldFrameIndex);
         rmAssert((*cacheFrameBufPtr)->frameIndex() == oldFrameIndex);
         (*cacheFrameBufPtr)->frameIndex(0);
         _cachedFramesItoB.erase(cachedEntryPtr);
 #ifdef VID_TRACE
         if (cacheFrameBufPtr->refCount() != 1) {
             fprintf(stderr, "B token %d fi %d refCount %d  frame* 0x%X\n", dToken,
                     frameIndex, cacheFrameBufPtr->refCount(),
                     (int)cacheFrameBufPtr->mFrameBuf);
             DUMP_VID_TRACE();
         }
 #endif
         rmAssert(cacheFrameBufPtr->refCount() == 1);
     }
     else {
         rmAssert(0); // Should always be able to find a free frame buffer ptr.
         return eVideoCacheStatusError;
     }
     /* Setting cacheFrameBufPtr to non-null and returning the error
      * status acts as a signal that the frame should be read from disk.
      */
     rmAssert(cacheFrameBufPtr);
     rmAssert(cacheFrameBufPtr->mCacheCtrl == 0);
     rmAssert((*cacheFrameBufPtr)->frameIndex() == 0);
     _cacheMisses++;
     /* As final step, create an entry in the pending map to allow all
      * the consumers of this frame to get serviced once the frame is
      * available.
      */
     pair<map<uint32, vcPendingFills>::iterator, bool> ret;
     ret = _pending.insert(pair<uint32, vcPendingFills>(frameIndex,
                                                          vcPendingFills()));
     rmAssert(ret.second); // Check that insert succeeded
     vcPendingFills& pendingBuffers = ret.first->second;
     pendingBuffers.push_back(&userFrameBuf);
     ADD_VID_TRACE(fnCacheAlloc, false, frameIndex+20,
                   cacheFrameBufPtr->mFrameBuf, dToken);
     return eVideoCacheStatusError;
 }
uint32 rcVideoCache::cacheHits () const
Definition at line 800 of file rc_videocache.cpp.
References _cacheHits, and _cacheMutex.
Referenced by main().
 {
     rcLock lock(const_cast<rcVideoCache*>(this)->_cacheMutex);
     return _cacheHits;
 }
rcVideoCacheStatus rcVideoCache::cacheInsert (uint32 frameIndex, rcSharedFrameBufPtr & cacheFrameBuf, const uint32 dToken) private
Definition at line 1148 of file rc_videocache.cpp.
References _cachedFramesItoB, _cacheID, _cacheMutex, _pending, _pendingCtrl, ADD_VID_TRACE, rcSignalPending::broadcast(), eVideoCacheStatusOK, fnCacheInsert, rcFrame::frameIndex(), rcSharedFrameBufPtr::mCacheCtrl, rcUNUSED, rcSharedFrameBufPtr::refCount(), and rmAssert.
Referenced by internalGetFrame().
 {
 #ifndef VID_TRACE
     rcUNUSED(dToken);
 #endif
     rcLock lock(_cacheMutex);
     ADD_VID_TRACE(fnCacheInsert, true, frameIndex, userFrameBuf.mFrameBuf, dToken);
     rmAssert(cacheFrameBuf.mCacheCtrl == 0);
     rmAssert(cacheFrameBuf.refCount() == 1);
     /* Frame shouldn't be in cache
      */
     rmAssert(_cachedFramesItoB.find(frameIndex) == _cachedFramesItoB.end());
     rmAssert(cacheFrameBuf->frameIndex() == 0);
     cacheFrameBuf->frameIndex(frameIndex);
     _cachedFramesItoB[frameIndex] = &cacheFrameBuf;
     /* Frame is loaded into cache and ready to use. Set up reference
      * to it in all the pending frame buffer ptrs.
      */
     map<uint32, vcPendingFills>::iterator pendingEntry;
     pendingEntry = _pending.find(frameIndex);
     rmAssert(pendingEntry != _pending.end());
     vcPendingFills& pendingBuffers = pendingEntry->second;
     uint32 pendingCount = pendingBuffers.size();
     rmAssert(pendingCount);
     for (uint32 i = 0; i < pendingCount; i++)
         (pendingBuffers[i])->setCachedFrame(cacheFrameBuf, _cacheID,
                                             frameIndex);
     /* Finished with list of pending frame buffers. Delete entry
      * from pending map.
      */
     _pending.erase(pendingEntry);
     rmAssert(cacheFrameBuf.refCount() == int32(pendingCount + 1));
     /* Broadcast signal to waiting threads so they can check and see if
      * their frame buffer is ready.
      */
     if (pendingCount > 1)
         _pendingCtrl.broadcast();
     ADD_VID_TRACE(fnCacheInsert, false, frameIndex, userFrameBuf.mFrameBuf, dToken);
     return eVideoCacheStatusOK;
 }
rcVideoCacheStatus rcVideoCache::cacheLock (uint32 cacheIndex, uint32 frameIndex, rcSharedFrameBufPtr & frameBuf, rcVideoCacheError * error = 0) static private
Definition at line 1788 of file rc_videocache.cpp.
References _activeCachesItoP, _cacheMgmtMutex, eVideoCacheErrorCacheInvalid, eVideoCacheStatusError, and getFrame().
Referenced by rcSharedFrameBufPtr::internalLock().
 {
     rcLock lock(_cacheMgmtMutex);
     map<uint32, rcVideoCache*>::iterator loc = _activeCachesItoP.find(cacheID);
     if (loc != _activeCachesItoP.end()) {
         rcVideoCache* cacheP = loc->second;
         return cacheP->getFrame(frameIndex, frameBuf, error);
     }
     if (error)
         *error = eVideoCacheErrorCacheInvalid;
     return eVideoCacheStatusError;
 }
uint32 rcVideoCache::cacheMisses () const
Definition at line 793 of file rc_videocache.cpp.
References _cacheMisses, and _cacheMutex.
Referenced by main().
 {
     rcLock lock(const_cast<rcVideoCache*>(this)->_cacheMutex);
     return _cacheMisses;
 }
void rcVideoCache::cachePrefetch (uint32 cacheIndex, uint32 frameIndex) static private
Definition at line 1764 of file rc_videocache.cpp.
References _activeCachesItoP, _cacheMgmtMutex, and prefetchFrame().
Referenced by rcSharedFrameBufPtr::prefetch().
 {
     rcLock lock(_cacheMgmtMutex);
     map<uint32, rcVideoCache*>::iterator loc = _activeCachesItoP.find(cacheID);
     if (loc == _activeCachesItoP.end())
         return;
     rcVideoCache* cacheP = loc->second;
     cacheP->prefetchFrame(frameIndex);
 }
uint32 rcVideoCache::cacheSize () const inline
Definition at line 196 of file rc_videocache.h.
Referenced by rcReifyMovieGrabber::cacheSize(), genSignatureFromMov(), main(), and rcVideoCache().
 { return _cacheSize; }
void rcVideoCache::cacheUnlock (uint32 cacheIndex, uint32 frameIndex) static private
Definition at line 1776 of file rc_videocache.cpp.
References _activeCachesItoP, _cacheMgmtMutex, and unlockFrame().
Referenced by rcSharedFrameBufPtr::internalUnlock().
 {
     rcLock lock(_cacheMgmtMutex);
     map<uint32, rcVideoCache*>::iterator loc = _activeCachesItoP.find(cacheID);
     if (loc == _activeCachesItoP.end())
         return;
     rcVideoCache* cacheP = loc->second;
     cacheP->unlockFrame(frameIndex);
 }
rcVideoCacheError rcVideoCache::camLoad () private
Definition at line 1596 of file rc_videocache.cpp.
References _byteOrder, _camExtHdrOffsets, _camExtHdrs, _movieFile, _verbose, endl(), eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, rcMovieFileCamExt::fixEndian(), movieExtensionCAM, rmAssert, setError(), and rcMovieFileExt::type().
Referenced by headerLoadRev2().
 {
     for ( uint32 i = 0; i < _camExtHdrOffsets.size(); ++i ) {
         rmAssert(_camExtHdrOffsets[i] != -1);
         if (fseeko(_movieFile, _camExtHdrOffsets[i] , SEEK_SET)) {
             if (_verbose) perror("fseeko during cam build failed");
             setError(eVideoCacheErrorFileSeek);
             return eVideoCacheErrorFileSeek;
         }
         rcMovieFileCamExt camHdr;
         if (fread(&camHdr, sizeof(camHdr), 1, _movieFile) != 1) {
             if (_verbose) perror("fread during cam build failed");
             setError(eVideoCacheErrorFileRead);
             return eVideoCacheErrorFileRead;
         }
         camHdr.fixEndian(_byteOrder);
         rmAssert(camHdr.type() == movieExtensionCAM);
         _camExtHdrs.push_back( camHdr );
         if (_verbose)
             cerr << camHdr << endl;
     }
     return eVideoCacheErrorOK;
 }
rcVideoCacheStatus rcVideoCache::closestTimestamp (const rcTimestamp & goalTime, rcTimestamp & match, rcVideoCacheError * error = 0)
Definition at line 535 of file rc_videocache.cpp.
References _tocTtoI, eVideoCacheErrorCacheInvalid, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), rmAssert, and tocLoad().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     /* Find timestamp > goal timestamp.
      */
     map<rcTimestamp, uint32>::iterator it;
     it = _tocTtoI.upper_bound(goalTime);
     if (it == _tocTtoI.end()) {
         /* Goal is >= last timestamp so just return it.
          */
         it--;
         match = it->first;
     } else if (it == _tocTtoI.begin()) {
         /* Goal is < first timestamp so just return it.
          */
         match = it->first;
     }
     else {
         rcTimestamp afterGoal = it->first;
         it--;
         rcTimestamp beforeOrEqualGoal = it->first;
         if ((afterGoal - goalTime) < (goalTime - beforeOrEqualGoal))
             match = afterGoal;
         else
             match = beforeOrEqualGoal;
     }
     return eVideoCacheStatusOK;
 }
rcVideoCacheError rcVideoCache::cnvLoad () private
Definition at line 1567 of file rc_videocache.cpp.
References _byteOrder, _cnvExtHdrOffsets, _cnvExtHdrs, _movieFile, _verbose, endl(), eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, rcMovieFileConvExt::fixEndian(), movieExtensionCNV, rmAssert, setError(), and rcMovieFileExt::type().
Referenced by headerLoadRev2().
 {
     for ( uint32 i = 0; i < _cnvExtHdrOffsets.size(); ++i ) {
         rmAssert(_cnvExtHdrOffsets[i] != -1);
         if (fseeko(_movieFile, _cnvExtHdrOffsets[i] , SEEK_SET)) {
             if (_verbose) perror("fseeko during cnv build failed");
             setError(eVideoCacheErrorFileSeek);
             return eVideoCacheErrorFileSeek;
         }
         rcMovieFileConvExt cnvHdr;
         if (fread(&cnvHdr, sizeof(cnvHdr), 1, _movieFile) != 1) {
             if (_verbose) perror("fread during cnv build failed");
             setError(eVideoCacheErrorFileRead);
             return eVideoCacheErrorFileRead;
         }
         cnvHdr.fixEndian(_byteOrder);
         rmAssert(cnvHdr.type() == movieExtensionCNV);
         _cnvExtHdrs.push_back( cnvHdr );
         if (_verbose)
             cerr << cnvHdr << endl;
     }
     return eVideoCacheErrorOK;
 }
void rcVideoCache::createDefaultOriginHeader (movieFormatRev rev) private
Definition at line 1203 of file rc_videocache.cpp.
References _orgHdrs, baseTime(), frameCount(), frameDepth(), frameHeight(), frameWidth(), movieFormatRev0, movieFormatRev2, movieOriginCaptureUncertified, and rmAssert.
Referenced by rcVideoCache().
 {
     rmAssert( rev < movieFormatRev2 );
     std::string creator;
     if ( rev == movieFormatRev0 )
         creator = "Visible/Batchconvert";
     else
         creator = "Batchconvert";
     rcMovieFileOrgExt orgHdr( movieOriginCaptureUncertified, baseTime(),
                               frameCount(), frameWidth(), frameHeight(), frameDepth(),
                               rev, creator.c_str() );
     _orgHdrs.push_back( orgHdr );
 }
rcVideoCacheError rcVideoCache::expLoad () private
Definition at line 1625 of file rc_videocache.cpp.
References _byteOrder, _expExtHdrOffsets, _expExtHdrs, _movieFile, _verbose, endl(), eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, rcMovieFileExpExt::fixEndian(), movieExtensionEXP, rmAssert, setError(), and rcMovieFileExt::type().
Referenced by headerLoadRev2().
 {
     for ( uint32 i = 0; i < _expExtHdrOffsets.size(); ++i ) {
         rmAssert(_expExtHdrOffsets[i] != -1);
         if (fseeko(_movieFile, _expExtHdrOffsets[i] , SEEK_SET)) {
             if (_verbose) perror("fseeko during exp build failed");
             setError(eVideoCacheErrorFileSeek);
             return eVideoCacheErrorFileSeek;
         }
         rcMovieFileExpExt expHdr;
         if (fread(&expHdr, sizeof(expHdr), 1, _movieFile) != 1) {
             if (_verbose) perror("fread during exp build failed");
             setError(eVideoCacheErrorFileRead);
             return eVideoCacheErrorFileRead;
         }
         expHdr.fixEndian(_byteOrder);
         rmAssert(expHdr.type() == movieExtensionEXP);
         _expExtHdrs.push_back( expHdr );
         if (_verbose)
             cerr << expHdr << endl;
     }
     return eVideoCacheErrorOK;
 }
rcVideoCache * rcVideoCache::finishSetup (rcVideoCache * cacheP) static private
Definition at line 159 of file rc_videocache.cpp.
References _activeCachesItoP, _activeCachesPtoI, _cacheMgmtMutex, _nextCacheID, rmAssert, and setCacheID().
Referenced by rcVideoCacheCtor(), and rcVideoCacheUTCtor().
 {
     rmAssert(cacheP);
     rcLock lock(_cacheMgmtMutex);
     ++_nextCacheID;
     rmAssert(_nextCacheID != 0);
     rmAssert(_activeCachesPtoI.find(cacheP) == _activeCachesPtoI.end());
     _activeCachesItoP[_nextCacheID] = cacheP;
     _activeCachesPtoI[cacheP] = _nextCacheID;
     cacheP->setCacheID(_nextCacheID);
     return cacheP;
 }
rcVideoCacheStatus rcVideoCache::firstTimestamp (rcTimestamp & match, rcVideoCacheError * error = 0)
Definition at line 656 of file rc_videocache.cpp.
References _tocTtoI, eVideoCacheErrorCacheInvalid, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), rmAssert, and tocLoad().
Referenced by rfGenerateTimeline(), and rcEngineMoviePlayback::setupTimeCtrlPlayback().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     match = _tocTtoI.begin()->first;
     return eVideoCacheStatusOK;
 }
uint32 rcVideoCache::frameCount () const inline
Definition at line 183 of file rc_videocache.h.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), createDefaultOriginHeader(), rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), rcReifyMovieGrabber::frameCount(), genSignatureFromMov(), main(), rfCompareMovies(), rfCompareReifyMovies(), rfGenerateTimeline(), and rcReifyMovieGrabber::start().
 { return _frameCount; }
off_t rcVideoCache::frameDataOffset (const uint32 & frameIndex) const
Definition at line 776 of file rc_videocache.cpp.
References _bytesInFrame, _rev, movieFormatInvalid, movieFormatRev0, movieFormatRev1, and movieFormatRev2.
Referenced by headerLoadRev1(), headerLoadRev2(), and internalGetFrame().
 {
     off_t movieRecordSz = sizeof(int64) + _bytesInFrame;
     switch ( _rev ) {
         case movieFormatRev0:
         case movieFormatRev1:
             return sizeof(rcMovieFileFormat) + movieRecordSz*frameIndex;
         case movieFormatRev2:
             return sizeof(rcMovieFileFormat2) + movieRecordSz*frameIndex;
         case movieFormatInvalid:
             break;
     }
     return 0;
 }
rcPixel rcVideoCache::frameDepth () const inline
Definition at line 186 of file rc_videocache.h.
Referenced by rcEngineImpl::analyzeFocusArea(), cacheAlloc(), createDefaultOriginHeader(), and genSignatureFromMov().
 { return _frameDepth; }
uint32 rcVideoCache::frameHeight () const inline
Definition at line 185 of file rc_videocache.h.
Referenced by cacheAlloc(), createDefaultOriginHeader(), rcMovieConverterToQT::createQTMovie(), and rcEngineImpl::loadFrames().
 { return _frameHeight; }
rcVideoCacheStatus rcVideoCache::frameIndexToTimestamp (uint32 frameIndex, rcTimestamp & match, rcVideoCacheError * error = 0)
Definition at line 706 of file rc_videocache.cpp.
References _tocItoT, eVideoCacheErrorCacheInvalid, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), and tocLoad().
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcEngineImpl::loadFrames(), and main().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     if (frameIndex >= _tocItoT.size()) {
         /* No frame for given frame index. Return error.
          */
         if (error) *error = eVideoCacheErrorNoSuchFrame;
         return eVideoCacheStatusError;
     }
     match = _tocItoT[frameIndex];
     return eVideoCacheStatusOK;
 }
uint32 rcVideoCache::frameWidth () const inline
Definition at line 184 of file rc_videocache.h.
Referenced by cacheAlloc(), createDefaultOriginHeader(), rcMovieConverterToQT::createQTMovie(), and rcEngineImpl::loadFrames().
 { return _frameWidth; }
std::string rcVideoCache::getErrorString (rcVideoCacheError error) static
Definition at line 490 of file rc_videocache.cpp.
References eVideoCacheErrorBomUnsupported, eVideoCacheErrorCacheInvalid, eVideoCacheErrorDepthUnsupported, eVideoCacheErrorFileClose, eVideoCacheErrorFileFormat, eVideoCacheErrorFileInit, eVideoCacheErrorFileRead, eVideoCacheErrorFileRevUnsupported, eVideoCacheErrorFileSeek, eVideoCacheErrorFileUnsupported, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, and eVideoCacheErrorSystemResources.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::loadFrames(), main(), rcEngineMoviePlayback::playbackCleanup(), rfCompareMovies(), rfCompareReifyMovies(), rfGenerateTimeline(), and rcEngineMoviePlayback::setupTimeCtrlPlayback().
 {
     switch (error) {
         case eVideoCacheErrorOK:
             return std::string("Video cache: OK");
         case eVideoCacheErrorFileInit:
             return std::string("Video cache: video file initialization error");
         case eVideoCacheErrorFileSeek:
             return std::string("Video cache: video file seek error");
         case eVideoCacheErrorFileRead:
             return std::string("Video cache: video file read error");
         case eVideoCacheErrorFileClose:
             return std::string("Video cache: video file close error");
         case eVideoCacheErrorFileFormat:
             return std::string("Video cache: video file invalid/corrupted error");
         case eVideoCacheErrorFileUnsupported:
             return std::string("Video cache: video file format unsupported error");
         case eVideoCacheErrorFileRevUnsupported:
             return std::string("Video cache: video file revision unsupported error");
         case eVideoCacheErrorSystemResources:
             return std::string("Video cache: Inadequate system resources");
         case eVideoCacheErrorNoSuchFrame:
             return std::string("Video cache: no video frame at given timestamp/frame index");
         case eVideoCacheErrorCacheInvalid:
             return std::string("Video cache: previous error put cache in invalid state");
         case eVideoCacheErrorBomUnsupported:
             return std::string("Video cache: unsupported byte order error");
         case eVideoCacheErrorDepthUnsupported:
             return std::string("Video cache: unsupported image depth error");
             // Note: no default case to force a compiler warning if a new enum
             // value is defined without adding a corresponding string here.
     }
     return std::string(" Video cache: undefined error" );
 }
rcVideoCacheError rcVideoCache::getFatalError () const
Definition at line 526 of file rc_videocache.cpp.
References _cacheMutex, and _fatalError.
Referenced by rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), main(), rcReifyMovieGrabber::rcReifyMovieGrabber(), rfCompareMovies(), and rfCompareReifyMovies().
 {
     rcLock lock(const_cast<rcVideoCache*>(this)->_cacheMutex);
     return _fatalError;
 }
rcVideoCacheStatus rcVideoCache::getFrame (uint32 frameIndex, rcSharedFrameBufPtr & frameBuf, rcVideoCacheError * error = 0, bool locked = true)
Definition at line 403 of file rc_videocache.cpp.
References _cacheID, _frameCount, ADD_VID_TRACE, eVideoCacheErrorCacheInvalid, eVideoCacheErrorNoSuchFrame, eVideoCacheStatusError, eVideoCacheStatusOK, fnGetFrameI, GET_TOKEN, internalGetFrame(), isValid(), rcSharedFrameBufPtr::mFrameBuf, rcSharedFrameBufPtr::setCachedFrameIndex(), and setError().
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), cacheLock(), rcMovieConverterToRfy::createRfyMovie(), rcReifyMovieGrabber::getNextFrame(), main(), rcWindow::rcWindow(), rfCompareMovies(), rfCompareReifyMovies(), and rcEngineMoviePlayback::run().
 {
     /* Before stuffing a new frame reference into here, invalidate any
      * existing reference.
      */
     frameBuf = 0;
     const uint32 dToken = GET_TOKEN();
     ADD_VID_TRACE(fnGetFrameI, true, frameIndex, frameBuf.mFrameBuf, dToken);
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         ADD_VID_TRACE(fnGetFrameI, false, frameIndex, frameBuf.mFrameBuf, dToken);
         return eVideoCacheStatusError;
     }
     if (frameIndex >= _frameCount) {
         setError(eVideoCacheErrorNoSuchFrame);
         if (error) *error = eVideoCacheErrorNoSuchFrame;
         ADD_VID_TRACE(fnGetFrameI, false, frameIndex, frameBuf.mFrameBuf, dToken);
         return eVideoCacheStatusError;
     }
     rcVideoCacheStatus status = eVideoCacheStatusOK;
     if (locked)
         status = internalGetFrame(frameIndex, frameBuf, error, dToken);
     else
         frameBuf.setCachedFrameIndex(_cacheID, frameIndex);
     ADD_VID_TRACE(fnGetFrameI, false, frameIndex, frameBuf.mFrameBuf, dToken);
     return status;
 }
rcVideoCacheStatus rcVideoCache::getFrame (const rcTimestamp & time, rcSharedFrameBufPtr & frameBuf, rcVideoCacheError * error = 0, bool locked = true)
Definition at line 439 of file rc_videocache.cpp.
References _cacheID, _tocTtoI, ADD_VID_TRACE, eVideoCacheErrorCacheInvalid, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, fnGetFrameT, GET_TOKEN, internalGetFrame(), isValid(), rcSharedFrameBufPtr::mFrameBuf, rmAssert, rcSharedFrameBufPtr::setCachedFrameIndex(), setError(), and tocLoad().
 {
     /* Before stuffing a new frame reference into here, invalidate any
      * existing reference.
      */
     frameBuf = 0;
     const uint32 dToken = GET_TOKEN();
     ADD_VID_TRACE(fnGetFrameT, true, 0xFFFFFFFF, frameBuf.mFrameBuf, dToken);
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         ADD_VID_TRACE(fnGetFrameT, false, 0xFFFFFFFF, frameBuf.mFrameBuf, dToken);
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         ADD_VID_TRACE(fnGetFrameT, false, 0xFFFFFFFF, frameBuf.mFrameBuf, dToken);
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     map<rcTimestamp, uint32>::iterator frameIndexPtr;
     frameIndexPtr = _tocTtoI.find(time);
     if (frameIndexPtr == _tocTtoI.end()) {
         setError(eVideoCacheErrorNoSuchFrame);
         if (error) *error = eVideoCacheErrorNoSuchFrame;
         ADD_VID_TRACE(fnGetFrameT, false, 0xFFFFFFFF, frameBuf.mFrameBuf, dToken);
         return eVideoCacheStatusError;
     }
     rcVideoCacheStatus status2 = eVideoCacheStatusOK;
     if (locked)
         status2 = internalGetFrame(frameIndexPtr->second, frameBuf, error, dToken);
     else
         frameBuf.setCachedFrameIndex(_cacheID, frameIndexPtr->second);
     ADD_VID_TRACE(fnGetFrameT, false, frameIndexPtr->second,
                   frameBuf.mFrameBuf, dToken);
     return status2;
 }
const std::string rcVideoCache::getInputSourceName () const inline
Definition at line 203 of file rc_videocache.h.
Referenced by rcReifyMovieGrabber::getInputSourceName().
 { return _fileName; }
uint32 rcVideoCache::getNextToken () private
Definition at line 130 of file rc_videocache.cpp.
References _cacheMutex, and _debuggingToken.
 {
     rcLock lock(_cacheMutex); return _debuggingToken++;
 }
rcVideoCacheError rcVideoCache::headerLoadRev0 () private
Definition at line 1218 of file rc_videocache.cpp.
References _averageFrameRate, _baseTime, _byteOrder, _bytesInFrame, _fatalError, _frameCount, _frameHeight, _frameWidth, _movieFile, _verbose, rcMovieFileFormat::averageFrameRate(), rcMovieFileFormat::baseTime(), rcMovieFileFormat::bytesInFrame(), eByteOrderBigEndian, endl(), eVideoCacheErrorFileRead, eVideoCacheErrorFileUnsupported, eVideoCacheErrorOK, rcMovieFileFormat::fixEndian(), rcMovieFileFormat::frameCount(), rcMovieFileFormat::height(), rmDim, rcMovieFileFormat::rowUpdate(), setError(), and rcMovieFileFormat::width().
Referenced by headerLoadRev1(), and rcVideoCache().
 {
     rcMovieFileFormat movieHdr;
     // Legacy format is always big-endian
     _byteOrder = eByteOrderBigEndian;
     /* Read movie header and check that we support this type of file.
      */
     if (fread(&movieHdr, sizeof(movieHdr), 1, _movieFile) != 1) {
         if (_verbose) perror("fread of header failed");
         setError(eVideoCacheErrorFileRead);
         return _fatalError;
     }
     movieHdr.fixEndian();
     if ((movieHdr.rowUpdate() & 0xF) != 0) {
         if (_verbose) {
             char buf[256];
             snprintf( buf, rmDim(buf), "Invalid header row update %i",
                       movieHdr.rowUpdate() );
             perror(buf);
         }
         setError(eVideoCacheErrorFileUnsupported);
         return _fatalError;
     }
     _bytesInFrame = movieHdr.bytesInFrame();
     _frameCount = movieHdr.frameCount();
     _frameWidth = movieHdr.width();
     _frameHeight = movieHdr.height();
     _averageFrameRate = movieHdr.averageFrameRate();
     _baseTime = movieHdr.baseTime();
     if (_verbose)
         cerr << movieHdr << endl;
     return eVideoCacheErrorOK;
 }
rcVideoCacheError rcVideoCache::headerLoadRev1 (bool getTOC) private
Definition at line 1258 of file rc_videocache.cpp.
References _byteOrder, _fatalError, _fileName, _frameCount, _movieFile, _tocExtHdrOffset, _verbose, endl(), eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, rcMovieFileExt::fixEndian(), frameDataOffset(), headerLoadRev0(), movieExtensionEOF, movieExtensionTOC, rcMovieFileExt::offset(), rev(), setError(), tocLoad(), and rcMovieFileExt::type().
Referenced by rcVideoCache().
 {
     rcVideoCacheError error = headerLoadRev0();
     if ( error == eVideoCacheErrorOK ) {
         /* Find the location of supported extensions, ignoring all others.
          */
         off_t offset = frameDataOffset( _frameCount );
         rcMovieFileExt ext;
         do {
             if (fseeko(_movieFile, offset, SEEK_SET)) {
                 if (_verbose) perror("Seek to header extension failed");
                 setError(eVideoCacheErrorFileSeek);
                 return _fatalError;
             }
             if (fread(&ext, sizeof(ext), 1, _movieFile) != 1) {
                 if (_verbose) perror("Read of header extension failed");
                 setError(eVideoCacheErrorFileRead);
                 return _fatalError;
             }
             ext.fixEndian(_byteOrder);
             switch ( ext.type() ) {
                 case movieExtensionTOC:
                     _tocExtHdrOffset = offset;
                     break;
                 case movieExtensionEOF:
                     break;
                 default:
                     cerr << "Warning: unsupported extension " << ext.type() << " found in rev" << rev()
                          << " file " << _fileName << endl;
                     break;
             }
             offset += ext.offset();
         } while (ext.type() != movieExtensionEOF);
     }
     if ( getTOC ) {
         error = tocLoad();
         if ( error != eVideoCacheErrorOK)
             return error;
     }
     return error;
 }
rcVideoCacheError rcVideoCache::headerLoadRev2 (bool getTOC) private
Definition at line 1306 of file rc_videocache.cpp.
References _averageFrameRate, _byteOrder, _bytesInFrame, _camExtHdrOffsets, _cnvExtHdrOffsets, _expExtHdrOffsets, _fatalError, _fileName, _frameCount, _frameDepth, _frameHeight, _frameWidth, _movieFile, _orgExtHdrOffsets, _tocExtHdrOffset, _verbose, rcMovieFileFormat2::averageFrameRate(), rcMovieFileFormat2::bom(), rcMovieFileFormat2::bytesInFrame(), camLoad(), cnvLoad(), rcMovieFileFormat2::depth(), eByteOrderUnknown, endl(), eVideoCacheErrorBomUnsupported, eVideoCacheErrorDepthUnsupported, eVideoCacheErrorFileFormat, eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, expLoad(), rcMovieFileFormat2::extensionOffset(), rcMovieFileFormat2::fixEndian(), rcMovieFileExt::fixEndian(), rcMovieFileFormat2::frameCount(), frameDataOffset(), rcMovieFileFormat2::height(), movieExtensionCAM, movieExtensionCNV, movieExtensionEOF, movieExtensionEXP, movieExtensionORG, movieExtensionTOC, rcMovieFileExt::offset(), orgLoad(), rcPixel32, rcPixel8, rev(), rfPlatformByteOrder(), rmDim, rcMovieFileFormat2::rowUpdate(), setError(), tocLoad(), rcMovieFileExt::type(), and rcMovieFileFormat2::width().
Referenced by rcVideoCache().
 {
     rcVideoCacheError error = eVideoCacheErrorOK;
     rcMovieFileFormat2 movieHdr;
     /* Read movie header and check that we support this type of file.
      */
     if (fread(&movieHdr, sizeof(movieHdr), 1, _movieFile) != 1) {
         if (_verbose) perror("Read of header2 failed");
         setError(eVideoCacheErrorFileRead);
         return _fatalError;
     }
     // check the bom (note: before endian fix)
     if ( rfPlatformByteOrder( movieHdr.bom() ) == eByteOrderUnknown ) {
         if (_verbose) perror("Unsupported BOM");
         setError(eVideoCacheErrorBomUnsupported);
         return _fatalError;
     }
     movieHdr.fixEndian();
     if ( movieHdr.depth() < rcPixel8 || movieHdr.depth() > rcPixel32 ) {
         if (_verbose) {
             char buf[256];
             snprintf( buf, rmDim(buf), "Unsupported pixel depth %i",
                       movieHdr.depth()*8 );
             perror(buf);
         }
         setError(eVideoCacheErrorDepthUnsupported);
         return _fatalError;
     }
     if ( movieHdr.extensionOffset() == 0 ) {
         if (_verbose) perror("Invalid extension offset");
         setError(eVideoCacheErrorFileFormat);
         return _fatalError;
     }
     _bytesInFrame = movieHdr.bytesInFrame();
     _frameCount = movieHdr.frameCount();
     _frameWidth = movieHdr.width();
     _frameHeight = movieHdr.height();
     _frameDepth = movieHdr.depth();
     _averageFrameRate = movieHdr.averageFrameRate();
  // Legacy format is always big-endian
     _byteOrder = rfPlatformByteOrder (movieHdr.bom() );
     _bytesInFrame = movieHdr.height() * movieHdr.rowUpdate();
     /* Find the location of supported extensions, ignoring all others.
      */
     off_t offset = frameDataOffset( _frameCount );
     rcMovieFileExt ext;
     do {
         if (fseeko(_movieFile, offset, SEEK_SET)) {
             if (_verbose) perror("Seek to header extension failed");
             setError(eVideoCacheErrorFileSeek);
             return _fatalError;
         }
         if (fread(&ext, sizeof(ext), 1, _movieFile) != 1) {
             if (_verbose) perror("Read of header extension failed");
             setError(eVideoCacheErrorFileRead);
             return _fatalError;
         }
         ext.fixEndian(_byteOrder);
         switch ( ext.type() ) {
             case movieExtensionTOC:
                 _tocExtHdrOffset = offset;
                 break;
             case movieExtensionORG:
                 _orgExtHdrOffsets.push_back(offset);
                 break;
             case movieExtensionCNV:
                 _cnvExtHdrOffsets.push_back(offset);
                 break;
             case movieExtensionCAM:
                 _camExtHdrOffsets.push_back(offset);
                 break;
             case movieExtensionEXP:
                 _expExtHdrOffsets.push_back(offset);
                 break;
             case movieExtensionEOF:
                 break;
             default:
                 cerr << "Warning: unsupported extension " << ext.type() << " found in rev" << rev()
                      << " file " << _fileName << endl;
                 break;
         }
         offset += ext.offset();
     } while (ext.type() != movieExtensionEOF);
     if (_verbose)
         cerr << movieHdr << endl;
     if ( getTOC ) {
         error = tocLoad();
         if ( error != eVideoCacheErrorOK)
             return error;
     }
     if ( !_orgExtHdrOffsets.empty() ) {
         error =  orgLoad();
         if ( error != eVideoCacheErrorOK )
             return error;
     }
     if ( !_cnvExtHdrOffsets.empty() ) {
         error = cnvLoad() ;
         if ( error != eVideoCacheErrorOK )
             return error;
     }
     if ( !_camExtHdrOffsets.empty() ) {
         error = camLoad() ;
         if ( error != eVideoCacheErrorOK )
             return error;
     }
     if ( !_expExtHdrOffsets.empty() ) {
         error = expLoad() ;
         if ( error != eVideoCacheErrorOK )
             return error;
     }
     return error;
 }
rcVideoCacheStatus rcVideoCache::internalGetFrame (uint32 frameIndex, rcSharedFrameBufPtr & frameBuf, rcVideoCacheError * error, const uint32 dToken) private
Definition at line 842 of file rc_videocache.cpp.
References _bytesInFrame, _cacheID, _diskMutex, _movieFile, _pendingCtrl, _verbose, ADD_VID_TRACE, cacheAlloc(), cacheInsert(), eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheStatusError, eVideoCacheStatusOK, fixEndian(), fnInternalGetFrame, frameDataOffset(), rcFrame::frameIndex(), rcSharedFrameBufPtr::mCacheCtrl, rcSharedFrameBufPtr::mFrameBuf, rcSharedFrameBufPtr::mFrameIndex, rcFrame::refCount(), rmAssert, setError(), and rcSignalPending::wait().
Referenced by getFrame().
 {
     ADD_VID_TRACE(fnInternalGetFrame, true, frameIndex,
                   frameBufPtr.mFrameBuf, dToken);
     /* Read in the frame using the following algorithm:
      *
      * Step 1: Call cache allocation fct to check and see if the frame
      * is already in cache. If so, frameBufPtr will be pointed towards
      * this frame and processing will be complete.
      *
      * Step 2: If not, the cache allocation fct will return a pointer to
      * an available frame buffer from within the cache. Read the frame
      * data in from disk and store it in this frame buffer. (Note: If
      * there aren't any cache slots available, an error is returned.)
      *
      * Step 3: Call cache insert fct to add this to the set of available
      * cached frames. This will also set frameBufPtr to point towards
      * the newly cached frame.
      *
      * Note that this gets broken into three steps to allow the cache
      * mutex to be freed during the possibly costly disk read operation,
      * with the idea of allowing other threads concurrent access to the
      * cache.
      */
     rcSharedFrameBufPtr* cacheFrameBufPtr;
     if (cacheAlloc(frameIndex, frameBufPtr, cacheFrameBufPtr, dToken) ==
         eVideoCacheStatusOK) {
         ADD_VID_TRACE(fnInternalGetFrame, false, frameIndex,
                       frameBufPtr.mFrameBuf, dToken);
         return eVideoCacheStatusOK;
     }
     /* If status is error but no frame was provided some other thread
      * is already loading the frame into memory. Go to sleep until
      * that thread completes the work.
      */
     if (!cacheFrameBufPtr) {
         _pendingCtrl.wait(frameBufPtr.mFrameBuf);
         rmAssert(frameBufPtr.mFrameBuf != 0);
         ADD_VID_TRACE(fnInternalGetFrame, false, frameIndex,
                       frameBufPtr.mFrameBuf, dToken);
         return eVideoCacheStatusOK;
     }
     rmAssert(cacheFrameBufPtr->refCount() == 1);
     rcTimestamp timestamp;
     int64 timeInfo;
     {
         rcLock lock(_diskMutex);
         rmAssert(_movieFile);
         /* Read in the frame from disk.
          */
         off_t offset = frameDataOffset( frameIndex );
         if (fseeko(_movieFile, offset, SEEK_SET)) {
             if (_verbose) perror("fseek during cache fill failed");
             setError(eVideoCacheErrorFileSeek);
             if (error) *error = eVideoCacheErrorFileSeek;
             ADD_VID_TRACE(fnInternalGetFrame, false, frameIndex,
                           frameBufPtr.mFrameBuf, dToken);
             /* Restore cache ID and frame index which were cleared by
              * calling function.
              */
             frameBufPtr.mCacheCtrl = _cacheID;
             frameBufPtr.mFrameIndex = frameIndex;
             return eVideoCacheStatusError;
         }
         if (fread(&timeInfo, sizeof(int64), 1, _movieFile) != 1) {
             if (_verbose) perror("fread of timestamp during cache fill failed");
             setError(eVideoCacheErrorFileRead);
             if (error) *error = eVideoCacheErrorFileRead;
             ADD_VID_TRACE(fnInternalGetFrame, false, frameIndex,
                           frameBufPtr.mFrameBuf, dToken);
             /* Restore cache ID and frame index which were cleared by
              * calling function.
              */
             frameBufPtr.mCacheCtrl = _cacheID;
             frameBufPtr.mFrameIndex = frameIndex;
             return eVideoCacheStatusError;
         }
         fixEndian(timeInfo);
         timestamp = timeInfo;
         if (fread((*cacheFrameBufPtr)->alignedRawData(), _bytesInFrame, 1,
                   _movieFile) != 1) {
             if (_verbose) perror("fread of frame data during cache fill failed");
             setError(eVideoCacheErrorFileRead);
             if (error) *error = eVideoCacheErrorFileRead;
             ADD_VID_TRACE(fnInternalGetFrame, false, frameIndex,
                           frameBufPtr.mFrameBuf, dToken);
             /* Restore cache ID and frame index which were cleared by
              * calling function.
              */
             frameBufPtr.mCacheCtrl = _cacheID;
             frameBufPtr.mFrameIndex = frameIndex;
             return eVideoCacheStatusError;
         }
     } // End of: { rcLock lock(_diskMutex);
     (*cacheFrameBufPtr)->setTimestamp(timestamp);
     rmAssert(cacheFrameBufPtr->refCount() == 1);
     rcVideoCacheStatus status = cacheInsert(frameIndex, *cacheFrameBufPtr,
                                             dToken);
     rmAssert(frameBufPtr->frameIndex() == frameIndex);
     ADD_VID_TRACE(fnInternalGetFrame, false, frameIndex, frameBufPtr.mFrameBuf,
                   dToken);
     return status;
 }
bool rcVideoCache::isValid () const
Definition at line 768 of file rc_videocache.cpp.
References _cacheMutex, and _isValid.
Referenced by closestTimestamp(), rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), firstTimestamp(), frameIndexToTimestamp(), getFrame(), lastTimestamp(), main(), nextTimestamp(), prevTimestamp(), rcReifyMovieGrabber::rcReifyMovieGrabber(), rcVideoCache(), rcVideoCache::rcVideoCachePrefetchUnit::rcVideoCachePrefetchUnit(), rfCompareMovies(), rfCompareReifyMovies(), and timestampToFrameIndex().
 {
     rcLock lock(const_cast<rcVideoCache*>(this)->_cacheMutex);
     return _isValid;
 }
rcVideoCacheStatus rcVideoCache::lastTimestamp (rcTimestamp & match, rcVideoCacheError * error = 0)
Definition at line 679 of file rc_videocache.cpp.
References _tocTtoI, eVideoCacheErrorCacheInvalid, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), rmAssert, and tocLoad().
Referenced by rfGenerateTimeline().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     map<rcTimestamp, uint32>::iterator it;
     it = _tocTtoI.end();
     it--;
     match = it->first;
     return eVideoCacheStatusOK;
 }
const vector<rcMovieFileCamExt>& rcVideoCache::movieFileCameras () const inline
Definition at line 200 of file rc_videocache.h.
Referenced by rcMovieConverterToRfy::createRfyMovie(), and rcEngineImpl::updateCameraLog().
 { return _camExtHdrs; }
const vector<rcMovieFileConvExt>& rcVideoCache::movieFileConversions () const inline
Definition at line 199 of file rc_videocache.h.
Referenced by rcMovieConverterToRfy::createRfyMovie(), and rcEngineImpl::updateConversionLog().
 { return _cnvExtHdrs; }
const vector<rcMovieFileExpExt>& rcVideoCache::movieFileExperiments () const inline
Definition at line 201 of file rc_videocache.h.
Referenced by rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::loadMovie(), and rcEngineImpl::updateCaptureLog().
 { return _expExtHdrs; }
const vector<rcMovieFileOrgExt>& rcVideoCache::movieFileOrigins () const inline
Definition at line 198 of file rc_videocache.h.
Referenced by rcEngineImpl::analyzeFocusArea(), rcMovieConverterToRfy::createRfyMovie(), and rcEngineImpl::updateCaptureLog().
 { return _orgHdrs; }
rcVideoCacheStatus rcVideoCache::nextTimestamp (const rcTimestamp & goalTime, rcTimestamp & match, rcVideoCacheError * error = 0)
Definition at line 583 of file rc_videocache.cpp.
References _tocTtoI, eVideoCacheErrorCacheInvalid, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), rmAssert, and tocLoad().
Referenced by rfGenerateTimeline().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     /* Find timestamp > goal timestamp.
      */
     map<rcTimestamp, uint32>::iterator it;
     it = _tocTtoI.upper_bound(goalTime);
     if (it == _tocTtoI.end()) {
         /* Goal is >= last timestamp. Return error.
          */
         if (error) *error = eVideoCacheErrorNoSuchFrame;
         return eVideoCacheStatusError;
     }
     match = it->first;
     return eVideoCacheStatusOK;
 }
rcVideoCacheError rcVideoCache::orgLoad () private
Definition at line 1537 of file rc_videocache.cpp.
References _byteOrder, _movieFile, _orgExtHdrOffsets, _orgHdrs, _verbose, endl(), eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, rcMovieFileOrgExt::fixEndian(), movieExtensionORG, rmAssert, setError(), and rcMovieFileExt::type().
Referenced by headerLoadRev2().
 {
     for ( uint32 i = 0; i < _orgExtHdrOffsets.size(); ++i ) {
         rmAssert( _orgExtHdrOffsets[i] != -1);
         if (fseeko(_movieFile, _orgExtHdrOffsets[i], SEEK_SET)) {
             if (_verbose) perror("fseeko during org build failed");
             setError(eVideoCacheErrorFileSeek);
             return eVideoCacheErrorFileSeek;
         }
         rcMovieFileOrgExt orgHdr;
         if (fread(&orgHdr, sizeof(orgHdr), 1, _movieFile) != 1) {
             if (_verbose) perror("fread during org build failed");
             setError(eVideoCacheErrorFileRead);
             return eVideoCacheErrorFileRead;
         }
         orgHdr.fixEndian(_byteOrder);
         rmAssert(orgHdr.type() == movieExtensionORG);
         _orgHdrs.push_back(orgHdr);
         if (_verbose)
             cerr << orgHdr << endl;
     }
     return eVideoCacheErrorOK;
 }
void rcVideoCache::prefetchFrame (uint32 frameIndex) private
Definition at line 1758 of file rc_videocache.cpp.
References _prefetchThread, and rcVideoCache::rcVideoCachePrefetchUnit::prefetch().
Referenced by cachePrefetch().
 {
     if (_prefetchThread)
         _prefetchThread->prefetch(frameIndex);
 }
rcVideoCacheStatus rcVideoCache::prevTimestamp (const rcTimestamp & goalTime, rcTimestamp & match, rcVideoCacheError * error = 0)
Definition at line 619 of file rc_videocache.cpp.
References _tocTtoI, eVideoCacheErrorCacheInvalid, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), rmAssert, and tocLoad().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     /* Find timestamp >= goal timestamp.
      */
     map<rcTimestamp, uint32>::iterator it;
     it = _tocTtoI.lower_bound(goalTime);
     if (it == _tocTtoI.begin()) {
         /* Goal is <= first timestamp. Return error.
          */
         if (error) *error = eVideoCacheErrorNoSuchFrame;
         return eVideoCacheStatusError;
     }
     it--;
     match = it->first;
     return eVideoCacheStatusOK;
 }
rcVideoCache * rcVideoCache::rcVideoCacheCtor (const std::string fileName, uint32 cacheSize, bool getTOC, bool verbose = true, bool prefetch = false, uint32 maxMemory = 0, rcProgressIndicator * pIndicator = 0) static
Definition at line 142 of file rc_videocache.cpp.
References finishSetup(), and rcVideoCache().
Referenced by rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), genSignatureFromMov(), rcEngineImpl::loadMovie(), main(), rfCompareMovies(), and rfCompareReifyMovies().
 {
     return finishSetup(new rcVideoCache(fileName, cacheSize, getTOC,
                                         verbose, prefetch, maxMemory, pIndicator));
 }
void rcVideoCache::rcVideoCacheDtor (rcVideoCache * cache) static
Definition at line 176 of file rc_videocache.cpp.
References _activeCachesItoP, _activeCachesPtoI, _cacheMgmtMutex, and rmAssert.
Referenced by rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), genSignatureFromMov(), rcEngineImpl::loadMovie(), main(), VideoCacheReleaser::operator()(), rfCompareMovies(), rfCompareReifyMovies(), and rcEngineImpl::unlockedReset().
 {
     {
         rcLock lock(_cacheMgmtMutex);
         map<rcVideoCache*, uint32>::iterator locI = _activeCachesPtoI.find(cacheP);
         if (locI == _activeCachesPtoI.end())
             return;
         uint32 cacheID = locI->second;
         map<uint32, rcVideoCache*>::iterator locP = _activeCachesItoP.find(cacheID);
         rmAssert(locP != _activeCachesItoP.end());
         rmAssert(locI->first == locP->second);
         rmAssert(locP->first == locI->second);
         _activeCachesItoP.erase(locP);
         _activeCachesPtoI.erase(locI);
     }
     delete cacheP;
 }
rcVideoCache * rcVideoCache::rcVideoCacheUTCtor (const vector< rcTimestamp > & frameTimes) static private
Definition at line 154 of file rc_videocache.cpp.
References finishSetup(), and rcVideoCache().
 {
     return finishSetup(new rcVideoCache(frameTimes));
 }
movieFormatRev rcVideoCache::rev () const inline
Definition at line 190 of file rc_videocache.h.
Referenced by headerLoadRev1(), headerLoadRev2(), and rcVideoCache().
 { return _rev; };
void rcVideoCache::setCacheID (uint32 cacheID) inline private
Definition at line 295 of file rc_videocache.h.
Referenced by finishSetup().
 { _cacheID = cacheID; }
void rcVideoCache::setError (rcVideoCacheError error) private
Definition at line 807 of file rc_videocache.cpp.
References _cacheMutex, _fatalError, _isValid, eVideoCacheErrorBomUnsupported, eVideoCacheErrorCacheInvalid, eVideoCacheErrorDepthUnsupported, eVideoCacheErrorFileClose, eVideoCacheErrorFileFormat, eVideoCacheErrorFileInit, eVideoCacheErrorFileRead, eVideoCacheErrorFileRevUnsupported, eVideoCacheErrorFileSeek, eVideoCacheErrorFileUnsupported, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, eVideoCacheErrorSystemResources, and rmAssert.
Referenced by camLoad(), cnvLoad(), expLoad(), getFrame(), headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), internalGetFrame(), orgLoad(), rcVideoCache(), tocLoadFromFrames(), and tocLoadFromTOC().
 {
     rcLock lock(_cacheMutex);
     /* Don't bother setting this if a fatal error has already occurred.
      */
     if (_isValid == false)
         return;
     switch (error) {
         case eVideoCacheErrorFileInit:
         case eVideoCacheErrorFileSeek:
         case eVideoCacheErrorFileRead:
         case eVideoCacheErrorFileClose:
         case eVideoCacheErrorFileFormat:
         case eVideoCacheErrorFileUnsupported:
         case eVideoCacheErrorFileRevUnsupported:
         case eVideoCacheErrorSystemResources:
         case eVideoCacheErrorBomUnsupported:
         case eVideoCacheErrorDepthUnsupported:
             _fatalError = error;
             _isValid = false;
             break;
         case eVideoCacheErrorNoSuchFrame:
         case eVideoCacheErrorOK:
             break;
         case eVideoCacheErrorCacheInvalid:
             rmAssert(0);
             break;
     }
 }
rcVideoCacheStatus rcVideoCache::timestampToFrameIndex (const rcTimestamp & timestamp, uint32 & match, rcVideoCacheError * error = 0)
Definition at line 736 of file rc_videocache.cpp.
References _tocTtoI, eVideoCacheErrorCacheInvalid, eVideoCacheErrorNoSuchFrame, eVideoCacheErrorOK, eVideoCacheStatusError, eVideoCacheStatusOK, isValid(), rmAssert, and tocLoad().
 {
     if (!isValid()) {
         if (error) *error = eVideoCacheErrorCacheInvalid;
         return eVideoCacheStatusError;
     }
     rcVideoCacheError status = tocLoad();
     if (status != eVideoCacheErrorOK) {
         if (error) *error = status;
         return eVideoCacheStatusError;
     }
     rmAssert(!_tocTtoI.empty());
     map<rcTimestamp, uint32>::iterator it;
     it = _tocTtoI.find(timestamp);
     if (it == _tocTtoI.end()) {
         /* No frame for given timestamp. Return error.
          */
         if (error) *error = eVideoCacheErrorNoSuchFrame;
         return eVideoCacheStatusError;
     }
     match = it->second;
     return eVideoCacheStatusOK;
 }
rcVideoCacheError rcVideoCache::tocLoad () private
Definition at line 1435 of file rc_videocache.cpp.
References _diskMutex, _frameCount, _movieFile, _tocExtHdrOffset, _tocItoT, _tocTtoI, eVideoCacheErrorOK, rmAssert, tocLoadFromFrames(), and tocLoadFromTOC().
Referenced by closestTimestamp(), firstTimestamp(), frameIndexToTimestamp(), getFrame(), headerLoadRev1(), headerLoadRev2(), lastTimestamp(), nextTimestamp(), prevTimestamp(), and timestampToFrameIndex().
 {
     rcLock lock(_diskMutex);
     if (!_tocItoT.empty())
         return eVideoCacheErrorOK;
     _tocItoT.resize(_frameCount);
     rmAssert(_tocTtoI.empty());
     rmAssert(_movieFile);
     if (_tocExtHdrOffset != -1)
         return tocLoadFromTOC();
     return tocLoadFromFrames();
 }
rcVideoCacheError rcVideoCache::tocLoadFromFrames () private
Definition at line 1452 of file rc_videocache.cpp.
References _bytesInFrame, _frameCount, _movieFile, _progressIndicator, _tocItoT, _tocTtoI, _verbose, eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, fixEndian(), rcProgressIndicator::progress(), and setError().
Referenced by tocLoad().
 {
     if (fseek(_movieFile, sizeof(rcMovieFileFormat), SEEK_SET)) {
         if (_verbose) perror("fseek during toc build failed");
         setError(eVideoCacheErrorFileSeek);
         return eVideoCacheErrorFileSeek;
     }
     for (uint32 frameIndex = 0; frameIndex < _frameCount; frameIndex++) {
         int64 timeInfo = 0;
         /* Skip seek for first frame because it was done before entering
          * loop.
          */
         if (frameIndex && fseek(_movieFile, _bytesInFrame, SEEK_CUR)) {
             if (_verbose) perror("fseek during toc build failed");
             setError(eVideoCacheErrorFileSeek);
             return eVideoCacheErrorFileSeek;
         }
         if (fread(&timeInfo, sizeof(int64), 1, _movieFile) != 1) {
             if (_verbose) perror("fread during toc build failed");
             setError(eVideoCacheErrorFileRead);
             return eVideoCacheErrorFileRead;
         }
         fixEndian(timeInfo);
         rcTimestamp timestamp(timeInfo);
         _tocItoT[frameIndex] = timestamp;
         _tocTtoI[timestamp] = frameIndex;
         if ( _progressIndicator )
              _progressIndicator->progress( 100.0 * frameIndex/_frameCount );
     }
     return eVideoCacheErrorOK;
 }
rcVideoCacheError rcVideoCache::tocLoadFromTOC () private
Definition at line 1490 of file rc_videocache.cpp.
References _byteOrder, _frameCount, _movieFile, _tocExtHdrOffset, _tocItoT, _tocTtoI, _verbose, rcMovieFileTocExt::count(), endl(), eVideoCacheErrorFileFormat, eVideoCacheErrorFileRead, eVideoCacheErrorFileSeek, eVideoCacheErrorOK, fixEndian(), rcMovieFileTocExt::fixEndian(), movieExtensionTOC, rmAssert, setError(), and rcMovieFileExt::type().
Referenced by tocLoad().
 {
     rmAssert(_tocExtHdrOffset != -1);
     if (fseeko(_movieFile, _tocExtHdrOffset, SEEK_SET)) {
         if (_verbose) perror("fseeko during toc build failed");
         setError(eVideoCacheErrorFileSeek);
         return eVideoCacheErrorFileSeek;
     }
     rcMovieFileTocExt tocHdr;
     if (fread(&tocHdr, sizeof(tocHdr), 1, _movieFile) != 1) {
         if (_verbose) perror("fread during toc build failed");
         setError(eVideoCacheErrorFileRead);
         return eVideoCacheErrorFileRead;
     }
     tocHdr.fixEndian(_byteOrder);
     if (_verbose)
         cerr << tocHdr << endl;
     rmAssert(tocHdr.type() == movieExtensionTOC);
     if (tocHdr.count() != _frameCount) {
         if (_verbose) cerr << "toc header count " << tocHdr.count()
                            << " != frame count " << _frameCount << endl;
         setError(eVideoCacheErrorFileFormat);
         return eVideoCacheErrorFileFormat;
     }
     for (uint32 frameIndex = 0; frameIndex < _frameCount; frameIndex++) {
         int64 timeInfo = 0;
         if (fread(&timeInfo, sizeof(int64), 1, _movieFile) != 1) {
             if (_verbose) perror("fread during toc build failed");
             setError(eVideoCacheErrorFileRead);
             return eVideoCacheErrorFileRead;
         }
         fixEndian(timeInfo);
         rcTimestamp timestamp(timeInfo);
         _tocItoT[frameIndex] = timestamp;
         _tocTtoI[timestamp] = frameIndex;
     }
     return eVideoCacheErrorOK;
 }
void rcVideoCache::unlockFrame (uint32 frameIndex) private
Definition at line 1653 of file rc_videocache.cpp.
References _cachedFramesItoB, _cacheID, _cacheMutex, _cacheOverflowLimit, _lastTouchIndex, _unlockedFramesItoL, _unlockedFramesLtoI, _unusedCacheFrames, ADD_VID_TRACE, fnUnlockFrame, GET_TOKEN, rcFrame::refCount(), and rmAssert.
Referenced by cacheUnlock().
 {
 #ifdef VID_TRACE
     const uint32 dToken = GET_TOKEN();
 #endif
     rcLock lock(_cacheMutex);
     ADD_VID_TRACE(fnUnlockFrame, true, frameIndex, 0, dToken);
     map<uint32, rcSharedFrameBufPtr*>::iterator cachedEntryPtr;
     cachedEntryPtr = _cachedFramesItoB.find(frameIndex);
     /* If someone else has already removed this frame from the
      * cache there is nothing left to do.
      */
     if (cachedEntryPtr == _cachedFramesItoB.end()) {
         ADD_VID_TRACE(fnUnlockFrame, false, frameIndex, 0, dToken);
         return;
     }
     /* Check to see if some other thread has locked this frame
      * between the time the calling frame buffer decremented the
      * count and this function call locked the cache mutex.
      */
     rcSharedFrameBufPtr* bufPtr = cachedEntryPtr->second;
     const uint32 refCount = (*bufPtr).refCount();
     if (refCount > 1) {
         ADD_VID_TRACE(fnUnlockFrame, false, frameIndex + 10,
                       (*bufPtr).mFrameBuf, dToken);
         return;
     }
     rmAssert((*bufPtr).refCount() == 1);
     rmAssert((*bufPtr)->frameIndex() == frameIndex);
     rmAssert((*bufPtr)->cacheCtrl() == _cacheID);
     /* Check to see if some other thread has locked and unlocked this
      * frame between the time the calling frame buffer decremented the
      * count and this function call locked the cache mutex.
      */
     map<uint32, int64>::iterator unlockedPtrItoL;
     unlockedPtrItoL = _unlockedFramesItoL.find(frameIndex);
     if (unlockedPtrItoL != _unlockedFramesItoL.end()) {
         ADD_VID_TRACE(fnUnlockFrame, false, frameIndex + 20,
                       (*bufPtr).mFrameBuf, dToken);
         return;
     }
     /* Have confirmed this frame buffer should be added to unlocked
      * maps.
      *
      * Note: Wrap around is bad. Could implement an algorithm to
      * compress last touch values down, but for now I think it is
      * good enough to just use a 64 bit counter.
      */
     rmAssert(_lastTouchIndex >= 0);
     rmAssert(_unlockedFramesLtoI.find(_lastTouchIndex) == _unlockedFramesLtoI.end());
     _unlockedFramesLtoI[_lastTouchIndex] = frameIndex;
     _unlockedFramesItoL[frameIndex] = _lastTouchIndex;
     _lastTouchIndex++;
     /* If the cache is currently overflowing its bounds, remove the LRU
      * element.
      */
     if (_unusedCacheFrames.size() < _cacheOverflowLimit) {
         /* Remove the least-recently-used unlocked frame. Step 1 is to
          * figure out the LRU frame's frame index and then clear the
          * related info from the unlocked frame maps.
          */
         map<int64, uint32>::iterator unlockedPtrLtoI;
         unlockedPtrLtoI = _unlockedFramesLtoI.begin();
         rmAssert(unlockedPtrLtoI != _unlockedFramesLtoI.end());
         uint32 oldFrameIndex = unlockedPtrLtoI->second;
         map<uint32, int64>::iterator unlockedPtrItoL;
         unlockedPtrItoL = _unlockedFramesItoL.find(oldFrameIndex);
         rmAssert(unlockedPtrItoL != _unlockedFramesItoL.end());
         rmAssert(unlockedPtrItoL->first == unlockedPtrLtoI->second);
         rmAssert(unlockedPtrItoL->second == unlockedPtrLtoI->first);
         _unlockedFramesItoL.erase(unlockedPtrItoL);
         _unlockedFramesLtoI.erase(unlockedPtrLtoI);
         /* Step 2 is to remove it from the cache entirely.
          */
         cachedEntryPtr = _cachedFramesItoB.find(oldFrameIndex);
         rmAssert(cachedEntryPtr != _cachedFramesItoB.end());
         bufPtr = cachedEntryPtr->second;
         _cachedFramesItoB.erase(cachedEntryPtr);
         /* Finally, free the associated buffer and put it back on the
          * unused list.
          */
         *bufPtr = 0;
         _unusedCacheFrames.push_back(bufPtr);
         return;
     }
     ADD_VID_TRACE(fnUnlockFrame, false, frameIndex, (*bufPtr).mFrameBuf, dToken);
 }
Friends And Related Function Documentation
friend class rcSharedFrameBufPtr friend
Definition at line 69 of file rc_videocache.h.
Referenced by cacheAlloc().
friend class UT_PlaybackUtils friend
Definition at line 70 of file rc_videocache.h.
Member Data Documentation
map< uint32, rcVideoCache * > rcVideoCache::_activeCachesItoP static private
Definition at line 379 of file rc_videocache.h.
Referenced by cacheLock(), cachePrefetch(), cacheUnlock(), finishSetup(), and rcVideoCacheDtor().
map< rcVideoCache *, uint32 > rcVideoCache::_activeCachesPtoI static private
Definition at line 380 of file rc_videocache.h.
Referenced by finishSetup(), and rcVideoCacheDtor().
double rcVideoCache::_averageFrameRate private
Definition at line 351 of file rc_videocache.h.
Referenced by headerLoadRev0(), headerLoadRev2(), and rcVideoCache().
int64 rcVideoCache::_baseTime private
Definition at line 352 of file rc_videocache.h.
Referenced by headerLoadRev0(), and rcVideoCache().
reByteOrder rcVideoCache::_byteOrder private
Definition at line 353 of file rc_videocache.h.
Referenced by camLoad(), cnvLoad(), expLoad(), headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), orgLoad(), rcVideoCache(), and tocLoadFromTOC().
uint32 rcVideoCache::_bytesInFrame private
Definition at line 346 of file rc_videocache.h.
Referenced by frameDataOffset(), headerLoadRev0(), headerLoadRev2(), internalGetFrame(), rcVideoCache(), and tocLoadFromFrames().
map<uint32, rcSharedFrameBufPtr*> rcVideoCache::_cachedFramesItoB private
Definition at line 317 of file rc_videocache.h.
Referenced by cacheAlloc(), cacheInsert(), and unlockFrame().
uint32 rcVideoCache::_cacheHits private
Definition at line 372 of file rc_videocache.h.
Referenced by cacheAlloc(), and cacheHits().
uint32 rcVideoCache::_cacheID private
Definition at line 370 of file rc_videocache.h.
Referenced by cacheAlloc(), cacheInsert(), getFrame(), internalGetFrame(), and unlockFrame().
rcMutex rcVideoCache::_cacheMgmtMutex static private
Definition at line 382 of file rc_videocache.h.
Referenced by cacheLock(), cachePrefetch(), cacheUnlock(), finishSetup(), and rcVideoCacheDtor().
uint32 rcVideoCache::_cacheMisses private
Definition at line 371 of file rc_videocache.h.
Referenced by cacheAlloc(), and cacheMisses().
rcMutex rcVideoCache::_cacheMutex private
Definition at line 364 of file rc_videocache.h.
Referenced by cacheAlloc(), cacheHits(), cacheInsert(), cacheMisses(), getFatalError(), getNextToken(), isValid(), setError(), and unlockFrame().
uint32 rcVideoCache::_cacheOverflowLimit private
Definition at line 368 of file rc_videocache.h.
Referenced by cacheAlloc(), rcVideoCache(), and unlockFrame().
uint32 rcVideoCache::_cacheSize private
Definition at line 369 of file rc_videocache.h.
Referenced by rcVideoCache().
vector<int64> rcVideoCache::_camExtHdrOffsets private
Definition at line 359 of file rc_videocache.h.
Referenced by camLoad(), and headerLoadRev2().
vector<rcMovieFileCamExt> rcVideoCache::_camExtHdrs private
Definition at line 360 of file rc_videocache.h.
Referenced by camLoad().
vector<int64> rcVideoCache::_cnvExtHdrOffsets private
Definition at line 357 of file rc_videocache.h.
Referenced by cnvLoad(), and headerLoadRev2().
vector<rcMovieFileConvExt> rcVideoCache::_cnvExtHdrs private
Definition at line 358 of file rc_videocache.h.
Referenced by cnvLoad().
uint32 rcVideoCache::_debuggingToken private
Definition at line 401 of file rc_videocache.h.
Referenced by getNextToken(), and rcVideoCache().
rcMutex rcVideoCache::_diskMutex private
Definition at line 365 of file rc_videocache.h.
Referenced by internalGetFrame(), tocLoad(), and ~rcVideoCache().
vector<int64> rcVideoCache::_expExtHdrOffsets private
Definition at line 361 of file rc_videocache.h.
Referenced by expLoad(), and headerLoadRev2().
vector<rcMovieFileExpExt> rcVideoCache::_expExtHdrs private
Definition at line 362 of file rc_videocache.h.
Referenced by expLoad().
rcVideoCacheError rcVideoCache::_fatalError private
Definition at line 342 of file rc_videocache.h.
Referenced by getFatalError(), headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), and setError().
const std::string rcVideoCache::_fileName private
Definition at line 343 of file rc_videocache.h.
Referenced by headerLoadRev1(), headerLoadRev2(), and rcVideoCache().
vector<rcSharedFrameBufPtr> rcVideoCache::_frameCache private
Definition at line 332 of file rc_videocache.h.
Referenced by rcVideoCache().
uint32 rcVideoCache::_frameCount private
Definition at line 347 of file rc_videocache.h.
Referenced by getFrame(), headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), rcVideoCache(), tocLoad(), tocLoadFromFrames(), and tocLoadFromTOC().
rcPixel rcVideoCache::_frameDepth private
Definition at line 350 of file rc_videocache.h.
Referenced by headerLoadRev2(), and rcVideoCache().
uint32 rcVideoCache::_frameHeight private
Definition at line 349 of file rc_videocache.h.
Referenced by headerLoadRev0(), headerLoadRev2(), and rcVideoCache().
uint32 rcVideoCache::_frameWidth private
Definition at line 348 of file rc_videocache.h.
Referenced by headerLoadRev0(), headerLoadRev2(), and rcVideoCache().
bool rcVideoCache::_isValid private
Definition at line 341 of file rc_videocache.h.
Referenced by isValid(), and setError().
int64 rcVideoCache::_lastTouchIndex private
Definition at line 313 of file rc_videocache.h.
Referenced by unlockFrame().
FILE* rcVideoCache::_movieFile private
Definition at line 344 of file rc_videocache.h.
Referenced by camLoad(), cnvLoad(), expLoad(), headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), internalGetFrame(), orgLoad(), rcVideoCache(), tocLoad(), tocLoadFromFrames(), tocLoadFromTOC(), and ~rcVideoCache().
uint32 rcVideoCache::_nextCacheID = 0 static private
Definition at line 381 of file rc_videocache.h.
Referenced by finishSetup().
vector<int64> rcVideoCache::_orgExtHdrOffsets private
Definition at line 355 of file rc_videocache.h.
Referenced by headerLoadRev2(), and orgLoad().
vector<rcMovieFileOrgExt> rcVideoCache::_orgHdrs private
Definition at line 356 of file rc_videocache.h.
Referenced by createDefaultOriginHeader(), and orgLoad().
map<uint32, vcPendingFills> rcVideoCache::_pending private
Definition at line 338 of file rc_videocache.h.
Referenced by cacheAlloc(), and cacheInsert().
rcSignalPending rcVideoCache::_pendingCtrl private
Definition at line 366 of file rc_videocache.h.
Referenced by cacheInsert(), and internalGetFrame().
rcVideoCachePrefetchUnit* rcVideoCache::_prefetchThread private
Definition at line 374 of file rc_videocache.h.
Referenced by prefetchFrame(), rcVideoCache(), and ~rcVideoCache().
rcProgressIndicator* rcVideoCache::_progressIndicator private
Definition at line 376 of file rc_videocache.h.
Referenced by tocLoadFromFrames(), and ~rcVideoCache().
movieFormatRev rcVideoCache::_rev private
Definition at line 345 of file rc_videocache.h.
Referenced by frameDataOffset(), and rcVideoCache().
int64 rcVideoCache::_tocExtHdrOffset private
Definition at line 354 of file rc_videocache.h.
Referenced by headerLoadRev1(), headerLoadRev2(), tocLoad(), and tocLoadFromTOC().
vector<rcTimestamp> rcVideoCache::_tocItoT private
Definition at line 327 of file rc_videocache.h.
Referenced by frameIndexToTimestamp(), rcVideoCache(), tocLoad(), tocLoadFromFrames(), and tocLoadFromTOC().
map<rcTimestamp, uint32> rcVideoCache::_tocTtoI private
Definition at line 328 of file rc_videocache.h.
Referenced by closestTimestamp(), firstTimestamp(), getFrame(), lastTimestamp(), nextTimestamp(), prevTimestamp(), rcVideoCache(), timestampToFrameIndex(), tocLoad(), tocLoadFromFrames(), and tocLoadFromTOC().
map<uint32, int64> rcVideoCache::_unlockedFramesItoL private
Definition at line 312 of file rc_videocache.h.
Referenced by cacheAlloc(), and unlockFrame().
map<int64, uint32> rcVideoCache::_unlockedFramesLtoI private
Definition at line 311 of file rc_videocache.h.
Referenced by cacheAlloc(), and unlockFrame().
deque<rcSharedFrameBufPtr*> rcVideoCache::_unusedCacheFrames private
Definition at line 322 of file rc_videocache.h.
Referenced by cacheAlloc(), rcVideoCache(), and unlockFrame().
bool rcVideoCache::_verbose private
Definition at line 340 of file rc_videocache.h.
Referenced by camLoad(), cnvLoad(), expLoad(), headerLoadRev0(), headerLoadRev1(), headerLoadRev2(), internalGetFrame(), orgLoad(), rcVideoCache(), tocLoadFromFrames(), tocLoadFromTOC(), and ~rcVideoCache().
The documentation for this class was generated from the following files:
include/visual/rc_videocache.h
src/visual/code/rc_videocache.cpp