Visible: hash< K, T, H, E > Class Template Reference
hash< K, T, H, E > Class Template Reference
#include <include/stlplus/hash.hpp>
Public Types
typedef unsigned size_type
typedef K key_type
typedef T data_type
typedef T mapped_type
typedef std::pair< const K, T > value_type
typedef hash_iterator< K, T, H,
E, value_type > iterator
typedef hash_iterator< K, T, H,
E, const value_type > const_iterator
Public Member Functions
hash (unsigned bins=0)
~hash (void)
hash (const hash &)
hash & operator= (const hash &)
bool empty (void) const
unsigned size (void) const
bool operator== (const hash &) const
bool operator!= (const hash &) const
void auto_rehash (void)
void manual_rehash (void)
void rehash (unsigned bins=0)
float loading (void) const
bool present (const K &key) const
size_type count (const K &key) const
iterator insert (const K &key, const T &data)
std::pair< iterator, bool > insert (const value_type &value)
iterator insert (const K &key)
bool erase (const K &key)
void erase (void)
void clear (void)
const_iterator find (const K &key) const
iterator find (const K &key)
const T & operator[] (const K &key) const
T & operator[] (const K &key)
const_iterator begin (void) const
iterator begin (void)
const_iterator end (void) const
iterator end (void)
void debug_report (otext &, unsigned indent=0) const
std::string debug_report (unsigned indent=0) const
void dump (dump_context &) const throw (persistent_dump_failed)
void restore (restore_context &) throw (persistent_restore_failed)
Private Attributes
unsigned m_rehash
unsigned m_bins
unsigned m_size
hash_element< K, T > ** m_values
Friends
class hash_element< K, T >
class hash_iterator< K, T, H, E, std::pair< const K, T > >
class hash_iterator< K, T, H, E, const std::pair< const K, T > >
Detailed Description
template<typename K, typename T, class H, class E>
class hash< K, T, H, E >
Definition at line 21 of file hash.hpp.
Member Typedef Documentation
template<typename K, typename T, class H, class E> typedef hash_iterator<K,T,H,E,const value_type> hash< K, T, H, E >::const_iterator
Definition at line 135 of file hash.hpp.
template<typename K, typename T, class H, class E> typedef T hash< K, T, H, E >::data_type
Definition at line 131 of file hash.hpp.
template<typename K, typename T, class H, class E> typedef hash_iterator<K,T,H,E,value_type> hash< K, T, H, E >::iterator
Definition at line 134 of file hash.hpp.
template<typename K, typename T, class H, class E> typedef K hash< K, T, H, E >::key_type
Definition at line 130 of file hash.hpp.
template<typename K, typename T, class H, class E> typedef T hash< K, T, H, E >::mapped_type
Definition at line 132 of file hash.hpp.
template<typename K, typename T, class H, class E> typedef unsigned hash< K, T, H, E >::size_type
Definition at line 129 of file hash.hpp.
template<typename K, typename T, class H, class E> typedef std::pair<const K, T> hash< K, T, H, E >::value_type
Definition at line 133 of file hash.hpp.
Constructor & Destructor Documentation
template<typename K, typename T, class H, class E> hash< K, T, H, E >::hash (unsigned bins = 0)
template<typename K, typename T, class H, class E> hash< K, T, H, E >::~hash (void)
template<typename K, typename T, class H, class E> hash< K, T, H, E >::hash (const hash< K, T, H, E > &)
Member Function Documentation
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::auto_rehash (void)
template<typename K, typename T, class H, class E> const_iterator hash< K, T, H, E >::begin (void) const
template<typename K, typename T, class H, class E> iterator hash< K, T, H, E >::begin (void)
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::clear (void)
Referenced by inf::preset().
template<typename K, typename T, class H, class E> size_type hash< K, T, H, E >::count (const K & key) const
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::debug_report (otext & , unsigned indent = 0) const
template<typename K, typename T, class H, class E> std::string hash< K, T, H, E >::debug_report (unsigned indent = 0) const
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::dump (dump_context &) const throw (persistent_dump_failed)
template<typename K, typename T, class H, class E> bool hash< K, T, H, E >::empty (void) const
template<typename K, typename T, class H, class E> const_iterator hash< K, T, H, E >::end (void) const
template<typename K, typename T, class H, class E> iterator hash< K, T, H, E >::end (void)
template<typename K, typename T, class H, class E> bool hash< K, T, H, E >::erase (const K & key)
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::erase (void)
template<typename K, typename T, class H, class E> const_iterator hash< K, T, H, E >::find (const K & key) const
template<typename K, typename T, class H, class E> iterator hash< K, T, H, E >::find (const K & key)
template<typename K, typename T, class H, class E> iterator hash< K, T, H, E >::insert (const K & key, const T & data)
template<typename K, typename T, class H, class E> std::pair<iterator, bool> hash< K, T, H, E >::insert (const value_type & value)
template<typename K, typename T, class H, class E> iterator hash< K, T, H, E >::insert (const K & key)
template<typename K, typename T, class H, class E> float hash< K, T, H, E >::loading (void) const
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::manual_rehash (void)
template<typename K, typename T, class H, class E> bool hash< K, T, H, E >::operator!= (const hash< K, T, H, E > &) const
template<typename K, typename T, class H, class E> hash& hash< K, T, H, E >::operator= (const hash< K, T, H, E > &)
Referenced by inf::inf(), inf::operator%=(), inf::operator/=(), and inf::operator=().
template<typename K, typename T, class H, class E> bool hash< K, T, H, E >::operator== (const hash< K, T, H, E > &) const
template<typename K, typename T, class H, class E> const T& hash< K, T, H, E >::operator[] (const K & key) const
template<typename K, typename T, class H, class E> T& hash< K, T, H, E >::operator[] (const K & key)
template<typename K, typename T, class H, class E> bool hash< K, T, H, E >::present (const K & key) const
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::rehash (unsigned bins = 0)
template<typename K, typename T, class H, class E> void hash< K, T, H, E >::restore (restore_context &) throw (persistent_restore_failed)
template<typename K, typename T, class H, class E> unsigned hash< K, T, H, E >::size (void) const
Friends And Related Function Documentation
template<typename K, typename T, class H, class E> friend class hash_element< K, T > friend
Definition at line 217 of file hash.hpp.
template<typename K, typename T, class H, class E> friend class hash_iterator< K, T, H, E, const std::pair< const K, T > > friend
Definition at line 219 of file hash.hpp.
template<typename K, typename T, class H, class E> friend class hash_iterator< K, T, H, E, std::pair< const K, T > > friend
Definition at line 218 of file hash.hpp.
Member Data Documentation
template<typename K, typename T, class H, class E> unsigned hash< K, T, H, E >::m_bins private
Definition at line 222 of file hash.hpp.
template<typename K, typename T, class H, class E> unsigned hash< K, T, H, E >::m_rehash private
Definition at line 221 of file hash.hpp.
template<typename K, typename T, class H, class E> unsigned hash< K, T, H, E >::m_size private
Definition at line 223 of file hash.hpp.
template<typename K, typename T, class H, class E> hash_element<K,T>** hash< K, T, H, E >::m_values private
Definition at line 224 of file hash.hpp.
The documentation for this class was generated from the following file:
include/stlplus/hash.hpp