Visible: rcTime Class Reference
rcTime Class Reference
#include <include/util/rc_time.h>
Public Member Functions
rcTime ()
void start ()
void reset ()
void end ()
double seconds ()
double sec ()
double milliseconds ()
double msec ()
double microseconds ()
double usec ()
rcUInt64 getUnixTime ()
void printUnixTime (rcUInt64 time)
Private Member Functions
double mGetTime (void)
uint64 mReadTBR (void)
Private Attributes
rcUInt64 mStartTime
rcUInt64 mElapsedTime
double mConversionFactor
Detailed Description
Definition at line 23 of file rc_time.h.
Constructor & Destructor Documentation
rcTime::rcTime () inline
Definition at line 26 of file rc_time.h.
References start().
   { start (); }
Member Function Documentation
void rcTime::end (void) inline
Definition at line 51 of file rc_time.h.
References mElapsedTime, mReadTBR(), and mStartTime.
    {
       mElapsedTime = mReadTBR() - mStartTime;
    }
rcUInt64 rcTime::getUnixTime () inline
Definition at line 86 of file rc_time.h.
References NULL.
Referenced by mReadTBR().
    {
       timeval tv;
       gettimeofday(&tv,NULL);
       return (rcUInt64)((tv.tv_sec)*1000000 + tv.tv_usec);
    }
double rcTime::mGetTime (void) inline private
Definition at line 101 of file rc_time.h.
Referenced by start().
    {
       uint64 time;
       Microseconds( (UnsignedWide*) &time );
       return (double) time * 1e-6;
    }
double rcTime::microseconds () inline
Definition at line 76 of file rc_time.h.
References mConversionFactor, and mElapsedTime.
Referenced by usec().
    {
       return mElapsedTime * mConversionFactor * 1000000;
    }
double rcTime::milliseconds () inline
Definition at line 66 of file rc_time.h.
References mConversionFactor, and mElapsedTime.
Referenced by msec().
    {
       return mElapsedTime * mConversionFactor * 1000;
    }
uint64 rcTime::mReadTBR (void) inline private
Definition at line 109 of file rc_time.h.
References getUnixTime().
Referenced by end(), and start().
       {
 #ifdef __ppc__
     register unsigned int temp1 asm ("r4");
     register unsigned int temp2 asm ("r5");
     __asm__ volatile
       ("0: mftbu r3\n"
        "mftb r4\n"
        "mftbu r5\n"
        "cmpw r3, r5\n"
        "bne- 0b\n");
     return ((UInt64)(temp2) << 32) + temp1;
 #else
     return getUnixTime ();
 #endif
       }
double rcTime::msec () inline
Definition at line 70 of file rc_time.h.
References milliseconds().
    {
      return milliseconds ();
    }
void rcTime::printUnixTime (rcUInt64 time) inline
Definition at line 93 of file rc_time.h.
    {
       cout << time << " microsecs\n";
    }
void rcTime::reset (void) inline
Definition at line 49 of file rc_time.h.
References start().
 { start (); }
double rcTime::sec () inline
Definition at line 61 of file rc_time.h.
References seconds().
    {
      return seconds ();
    }
double rcTime::seconds () inline
Definition at line 56 of file rc_time.h.
References mConversionFactor, and mElapsedTime.
Referenced by sec().
    {
       return mElapsedTime * mConversionFactor;
    }
void rcTime::start (void) inline
Definition at line 31 of file rc_time.h.
References mConversionFactor, mGetTime(), mReadTBR(), and mStartTime.
Referenced by rcTime(), and reset().
    {
       uint64 startTime, elapsedTime;
       double t0;
       //Calibrate the clock
       t0 = mGetTime ();
       startTime = mReadTBR();
       //spin for a second while we wait for a few ticks of the clock to go by
       while( mGetTime() - t0 < 1.0 )
          {}
       elapsedTime = mReadTBR() - startTime;
       mConversionFactor = 1.0/ (elapsedTime );
       mStartTime = mReadTBR();
    }
double rcTime::usec () inline
Definition at line 80 of file rc_time.h.
References microseconds().
    {
      return microseconds ();
    }
Member Data Documentation
double rcTime::mConversionFactor private
Definition at line 127 of file rc_time.h.
Referenced by microseconds(), milliseconds(), seconds(), and start().
rcUInt64 rcTime::mElapsedTime private
Definition at line 126 of file rc_time.h.
Referenced by end(), microseconds(), milliseconds(), and seconds().
rcUInt64 rcTime::mStartTime private
Definition at line 126 of file rc_time.h.
Referenced by end(), and start().
The documentation for this class was generated from the following file:
include/util/rc_time.h