Visible: rcBaseMotionPath Class Reference
rcBaseMotionPath Class Reference abstract
#include <include/analysis/rc_motionpath.h>
Public Member Functions
rcBaseMotionPath ()
virtual ~rcBaseMotionPath ()
virtual void measure ()=0
virtual void update ()=0
virtual void reconcile ()=0
bool isWithin (rcFPair &) const
const float & dob () const
const rc2Fvector position () const
dob :Return date of birth relative to kinetoscope start
rcIPair iAnchor () const
position Position with respect to the image from it was created from
const rc2Fvector & travelled () const
const rc2Fvector & motion () const
const rc2Fvector & anchor () const
void move (const rc2Fvector &t)
void move (const rc2Xform &xm)
move (vector) Move assuming the (t) -> (t+1) for motion vectors we assume translation
const rc2Fvector & anchor (const rc2Fvector &a)
move (xform) Move assuming the (t) -> (t+1) for motion vectors we assume translation
void step ()
uint32 steps () const
bool isAtStep (uint32 step) const
Protected Attributes
float mGenesis
rc2Fvector mStartPosition
rc2Fvector mDxDt
rc2Fvector mSumPos
uint32 mSteps
Detailed Description
Definition at line 148 of file rc_motionpath.h.
Constructor & Destructor Documentation
rcBaseMotionPath::rcBaseMotionPath () inline
Definition at line 153 of file rc_motionpath.h.
 : mGenesis (0.0f), mSteps(0) {}
virtual rcBaseMotionPath::~rcBaseMotionPath () inline virtual
Definition at line 155 of file rc_motionpath.h.
 {}
Member Function Documentation
const rc2Fvector& rcBaseMotionPath::anchor () const inline
Definition at line 201 of file rc_motionpath.h.
References mStartPosition.
Referenced by operator<<(), rcVisualFunction::rcVisualFunction(), and rcVisualFunction::update().
 { return mStartPosition; }
const rc2Fvector& rcBaseMotionPath::anchor (const rc2Fvector & a) inline
move (xform) Move assuming the (t) -> (t+1) for motion vectors we assume translation
Bug:
: not tested.
Definition at line 227 of file rc_motionpath.h.
References mStartPosition.
   {
     mStartPosition = a;
     return mStartPosition;
   }
const float& rcBaseMotionPath::dob () const inline
Definition at line 171 of file rc_motionpath.h.
References mGenesis.
Referenced by rcVisualFunction::age(), and rcVisualFunction::update().
   {
     return mGenesis;
   }
rcIPair rcBaseMotionPath::iAnchor () const inline
position Position with respect to the image from it was created from
Definition at line 190 of file rc_motionpath.h.
References mStartPosition, rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     return rcIPair (int32 (mStartPosition.x()),
             int32 (mStartPosition.y()));
   }
bool rcBaseMotionPath::isAtStep (uint32 step) const inline
Definition at line 237 of file rc_motionpath.h.
References mSteps, and step().
Referenced by rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcVisualFunction::correspondMutualChannel(), rcVisualFunction::predictedTolerance(), and rcVisualFunction::update().
   {
     return mSteps == step;
   }
bool rcBaseMotionPath::isWithin (rcFPair &) const
virtual void rcBaseMotionPath::measure () pure virtual
Implemented in rcVisualFunction, and rcVisualTarget.
const rc2Fvector& rcBaseMotionPath::motion () const inline
Definition at line 198 of file rc_motionpath.h.
References mDxDt.
Referenced by operator<<(), and rcVisualFunction::update().
 { return mDxDt; }
void rcBaseMotionPath::move (const rc2Fvector & t) inline
Definition at line 203 of file rc_motionpath.h.
References mDxDt, and mSumPos.
Referenced by rcVisualFunction::update().
   {
     mDxDt = t;
     mSumPos += t;
   }
void rcBaseMotionPath::move (const rc2Xform & xm) inline
move (vector) Move assuming the (t) -> (t+1) for motion vectors we assume translation
Definition at line 214 of file rc_motionpath.h.
References rc2Xform::invMapPoint(), mDxDt, and mSumPos.
   {
     rc2Fvector now = mSumPos;
     mSumPos = xm.invMapPoint (now);
     mDxDt = mSumPos - now;
   }
const rc2Fvector rcBaseMotionPath::position () const inline
dob :Return date of birth relative to kinetoscope start
Definition at line 181 of file rc_motionpath.h.
References mStartPosition, and mSumPos.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mSumPos + mStartPosition;
   }
virtual void rcBaseMotionPath::reconcile () pure virtual
Implemented in rcVisualFunction, and rcVisualTarget.
void rcBaseMotionPath::step () inline
Definition at line 233 of file rc_motionpath.h.
References mSteps.
Referenced by isAtStep(), and rcVisualFunction::measure().
 {mSteps++; return;}
uint32 rcBaseMotionPath::steps () const inline
Definition at line 235 of file rc_motionpath.h.
References mSteps.
Referenced by rcVisualFunction::minSqDisplacement(), rcVisualFunction::persistence(), rcVisualFunction::sideShorteningEstimate(), rcVisualFunction::update(), and rcVisualFunction::updateSims().
 { return mSteps; }
const rc2Fvector& rcBaseMotionPath::travelled () const inline
Definition at line 196 of file rc_motionpath.h.
References mSumPos.
Referenced by rcVisualFunction::update().
 { return mSumPos; }
virtual void rcBaseMotionPath::update () pure virtual
Implemented in rcVisualFunction.
Member Data Documentation
rc2Fvector rcBaseMotionPath::mDxDt protected
Definition at line 248 of file rc_motionpath.h.
Referenced by motion(), and move().
float rcBaseMotionPath::mGenesis protected
Definition at line 246 of file rc_motionpath.h.
Referenced by dob(), and rcVisualFunction::rcVisualFunction().
rc2Fvector rcBaseMotionPath::mStartPosition protected
Definition at line 247 of file rc_motionpath.h.
Referenced by anchor(), iAnchor(), position(), and rcVisualTarget::rcVisualTarget().
uint32 rcBaseMotionPath::mSteps protected
Definition at line 250 of file rc_motionpath.h.
Referenced by isAtStep(), operator<<(), rcVisualTarget::persistence(), step(), and steps().
rc2Fvector rcBaseMotionPath::mSumPos protected
Definition at line 249 of file rc_motionpath.h.
Referenced by move(), position(), rcVisualTarget::rcVisualTarget(), travelled(), and rcVisualTarget::update().
The documentation for this class was generated from the following file:
include/analysis/rc_motionpath.h