Visible: rcMoviePlaybackCtrl Class Reference
rcMoviePlaybackCtrl Class Reference
#include <include/visiCore/rc_playbackregs.h>
Public Member Functions
rcMoviePlaybackCtrl ()
void ctrlInfo (int ctrlInfo)
Public Member Functions inherited from rcMoviePlaybackCtrlReader
rcMoviePlaybackCtrlReader ()
virtual ~rcMoviePlaybackCtrlReader ()
int getCtrlInfo () const
Additional Inherited Members
Protected Attributes inherited from rcMoviePlaybackCtrlReader
rcAtomicValue< int > _ctrlInfo
Detailed Description
Definition at line 40 of file rc_playbackregs.h.
Constructor & Destructor Documentation
rcMoviePlaybackCtrl::rcMoviePlaybackCtrl () inline
Definition at line 43 of file rc_playbackregs.h.
                         : rcMoviePlaybackCtrlReader()
   { }
Member Function Documentation
void rcMoviePlaybackCtrl::ctrlInfo (int ctrlInfo) inline
Definition at line 46 of file rc_playbackregs.h.
References rcMoviePlaybackCtrlReader::_ctrlInfo, and rcAtomicValue< T >::setValue().
Referenced by rcEngineImpl::getSettingValue(), rcEngineImpl::internalReset(), and rcEngineImpl::setSettingValue().
   { _ctrlInfo.setValue(ctrlInfo); }
The documentation for this class was generated from the following file:
include/visiCore/rc_playbackregs.h