Visible: rcEdgeTables Class Reference
rcEdgeTables Class Reference
Public Types
enum {
eAtanPrecision = 16, eAtanRange = (1 << eAtanPrecision), eMagPrecision = 8, eMagTableSize = (1 << (eMagPrecision+eMagPrecision)),
eMagRange = (1 << eMagPrecision), eMaxMag = (eMagRange - 1)
}
Public Member Functions
rcEdgeTables ()
~rcEdgeTables ()
template<class T >
const T * angleTable (T) const
const uint8 * magnitudeTable () const
template<class T >
T binAtan (int32 y, int32 x, T) const
template<>
const uint8 * angleTable (uint8) const
template<>
const uint16 * angleTable (uint16) const
template<class T >
T binAtan (int y, int x, T) const
Private Attributes
double mMagScale
vector< uint8 > mThetaTable
vector< uint16 > mTheta16Table
vector< uint8 > mMagTable
Detailed Description
Definition at line 9 of file rc_edge.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
eAtanPrecision
eAtanRange
eMagPrecision
eMagTableSize
eMagRange
eMaxMag
Definition at line 15 of file rc_edge.cpp.
     {
       eAtanPrecision = 16,
       eAtanRange = (1 << eAtanPrecision),
       eMagPrecision = 8,
       eMagTableSize = (1 << (eMagPrecision+eMagPrecision)),
       eMagRange = (1 << eMagPrecision),
       eMaxMag = (eMagRange - 1)
     };
Constructor & Destructor Documentation
rcEdgeTables::rcEdgeTables ()
Definition at line 152 of file rc_edge.cpp.
References rcAngle8::basic(), rcAngle16::basic(), eAtanRange, eMagTableSize, eMaxMag, mMagScale, mMagTable, mTheta16Table, mThetaTable, rmMin, and rmSquare.
   :  mMagScale (255 / 256.)
 {
   int32 x, y, mapped;
   double realVal;
   mMagTable.resize (eMagTableSize);
   mThetaTable.resize (eAtanRange + 1);
   mTheta16Table.resize (eAtanRange + 1);
    // Magnitude Table: Linear Scale.
    uint8 *atIndex = &mMagTable [0];
    for(x = 0; x <= eMaxMag; x++)
      for(y = 0; y <= eMaxMag; y++)
       {
     realVal = sqrt (double (rmSquare (y) + rmSquare (x)));
     mapped = (int32) (rmMin(realVal * mMagScale, 255.0) + 0.5);
     *atIndex++ = uint8 (mapped);
       }
    for (int32 i = 0; i <= eAtanRange; ++i)
     {
       rcRadian rd (atan((double) i / eAtanRange));
       rcAngle8 r8 (rd);
       rcAngle16 r16 (rd);
       mThetaTable[i] = r8.basic ();
       mTheta16Table[i] = r16.basic ();
     }
 }
rcEdgeTables::~rcEdgeTables () inline
Definition at line 13 of file rc_edge.cpp.
 { }
Member Function Documentation
template<class T > const T* rcEdgeTables::angleTable (T) const inline
Definition at line 27 of file rc_edge.cpp.
References rmAssert.
Referenced by binAtan().
   {
     rmAssert (0);
   }
template<> const uint8* rcEdgeTables::angleTable (uint8) const
Definition at line 137 of file rc_edge.cpp.
References mThetaTable.
 {
   return &mThetaTable[0];
 }
template<> const uint16* rcEdgeTables::angleTable (uint16) const
Definition at line 142 of file rc_edge.cpp.
References mTheta16Table.
 {
   return &mTheta16Table[0];
 }
template<class T > T rcEdgeTables::binAtan (int32 y, int32 x, T) const
Referenced by sobelEdgeProcess().
template<class T > T rcEdgeTables::binAtan (int y, int x, T) const inline
Definition at line 184 of file rc_edge.cpp.
References angleTable(), and eAtanPrecision.
 {
   static T mPIover2  (1 << ((sizeof(T)*8)-2)), mPI (1 << ((sizeof(T)*8)-1)), m3PIover2 (mPIover2 + mPI);
   static int32 precision (eAtanPrecision);
   const T *ThetaTable = angleTable (mPI);
   if (y < 0)
     {
       y = -y;
       if (x >= 0)
     {
       if (y <= x) return       - ThetaTable[(y << precision) / x];
       else        return ( m3PIover2 + ThetaTable[(x << precision) / y]);
     }
       else
     {
       x = -x;
       if (y <= x) return ( mPI + ThetaTable[(y << precision) / x]);
       else        return ( m3PIover2 - ThetaTable[(x << precision) / y]);
     }
     }
   else
     {
       if (x >= 0)
     {
       if (x == 0 && y == 0) return 0;
       if (y <= x) return                  ThetaTable [(y << precision) / x];
       else        return (mPIover2 - ThetaTable[(x << precision) / y]);
     }
       else
     {
       x = -x;
       if (y <= x) return (mPI  - ThetaTable[(y << precision) / x]);
       else        return (mPIover2  + ThetaTable[(x << precision) / y]);
     }
     }
 }
const uint8* rcEdgeTables::magnitudeTable () const inline
Definition at line 33 of file rc_edge.cpp.
References mMagTable.
Referenced by sobelEdgeProcess().
 { return &mMagTable[0]; }
Member Data Documentation
double rcEdgeTables::mMagScale private
Definition at line 39 of file rc_edge.cpp.
Referenced by rcEdgeTables().
vector<uint8> rcEdgeTables::mMagTable private
Definition at line 42 of file rc_edge.cpp.
Referenced by magnitudeTable(), and rcEdgeTables().
vector<uint16> rcEdgeTables::mTheta16Table private
Definition at line 41 of file rc_edge.cpp.
Referenced by angleTable(), and rcEdgeTables().
vector<uint8> rcEdgeTables::mThetaTable private
Definition at line 40 of file rc_edge.cpp.
Referenced by angleTable(), and rcEdgeTables().
The documentation for this class was generated from the following file:
src/visual/code/rc_edge.cpp