Visible: rcBatchExperimentObserver Class Reference
rcBatchExperimentObserver Class Reference
#include <include/visiCore/rc_batchexperimentobserver.h>
Public Member Functions
rcBatchExperimentObserver (void)
uint32 errors ()
virtual void notifyError (const char *errorString)
virtual void notifyWarning (const char *warnString)
virtual void notifyStatus (const char *statusString)
virtual void notifyState (rcExperimentState newState, bool i)
virtual void notifyTime (const rcTimestamp &cursorTime)
virtual void notifyProgCursorTime (const rcTimestamp &cursorTime)
virtual int32 progCursorTimeEventCount () const
virtual void notifyCursorTime (const rcTimestamp &cursorTime)
void notifyTimelineRange (const rcTimestamp &start, const rcTimestamp &end)
void notifyEngineTimelineRange (const rcTimestamp &start, const rcTimestamp &end)
void notifyAnalysisRect (const rcRect &rect)
void notifyAnalysisRectRotation (const rcAffineRectangle &affine)
void notifyMultiplier (const double &multiplier)
virtual bool acceptingImageBlits (void)
virtual void notifyBlitData (const rcWindow *image)
virtual void notifyBlitGraphics (const rcVisualGraphicsCollection *graphics)
virtual void notifyLockApp (bool lock)
virtual void notifyExperimentChange ()
virtual void notifyVideoRect (const rcRect &rect)
virtual bool acceptingPolys (void)
virtual void notifyPolys ()
virtual void getPolys (rcPolygonGroupRef &polys)
virtual bool doneSelecting (void)
Public Member Functions inherited from rcExperimentObserver
virtual ~rcExperimentObserver ()
Private Attributes
uint32 mErrors
Detailed Description
Definition at line 24 of file rc_batchexperimentobserver.h.
Constructor & Destructor Documentation
rcBatchExperimentObserver::rcBatchExperimentObserver (void) inline
Definition at line 27 of file rc_batchexperimentobserver.h.
References mErrors.
     {
         mErrors = 0;
     }
Member Function Documentation
virtual bool rcBatchExperimentObserver::acceptingImageBlits (void) inline virtual
Implements rcExperimentObserver.
Definition at line 137 of file rc_batchexperimentobserver.h.
         {
             return false;
         }
virtual bool rcBatchExperimentObserver::acceptingPolys (void) inline virtual
Implements rcExperimentObserver.
Definition at line 170 of file rc_batchexperimentobserver.h.
 { return true;  }
virtual bool rcBatchExperimentObserver::doneSelecting (void) inline virtual
Definition at line 176 of file rc_batchexperimentobserver.h.
 { return true; }
uint32 rcBatchExperimentObserver::errors () inline
Definition at line 32 of file rc_batchexperimentobserver.h.
References mErrors.
                     {
         return mErrors;
     }
virtual void rcBatchExperimentObserver::getPolys (rcPolygonGroupRef & polys) inline virtual
Implements rcExperimentObserver.
Definition at line 174 of file rc_batchexperimentobserver.h.
References rmUnused.
 {rmUnused (polys); }
void rcBatchExperimentObserver::notifyAnalysisRect (const rcRect & rect) inline virtual
Implements rcExperimentObserver.
Definition at line 118 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( rect );
         }
void rcBatchExperimentObserver::notifyAnalysisRectRotation (const rcAffineRectangle & affine) inline virtual
Implements rcExperimentObserver.
Definition at line 124 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( affine );
         }
virtual void rcBatchExperimentObserver::notifyBlitData (const rcWindow * image) inline virtual
Implements rcExperimentObserver.
Definition at line 142 of file rc_batchexperimentobserver.h.
References endl(), mErrors, and silent().
         {
             if ( !silent )
                 cerr << "Visible[cmdLine]"  << " error: notifyBlitData called: " << image << endl;
             ++mErrors;
         }
virtual void rcBatchExperimentObserver::notifyBlitGraphics (const rcVisualGraphicsCollection * graphics) inline virtual
Implements rcExperimentObserver.
Definition at line 149 of file rc_batchexperimentobserver.h.
References endl(), mErrors, and silent().
         {
             if ( !silent )
                 cerr << "Visible[cmdLine]" << " error: notifyBlitGraphics called: " << graphics << endl;
             ++mErrors;
         }
virtual void rcBatchExperimentObserver::notifyCursorTime (const rcTimestamp & cursorTime) inline virtual
Definition at line 96 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( cursorTime );
         }
void rcBatchExperimentObserver::notifyEngineTimelineRange (const rcTimestamp & start, const rcTimestamp & end) inline virtual
Implements rcExperimentObserver.
Definition at line 110 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( start );
             rmUnused( end );
         }
virtual void rcBatchExperimentObserver::notifyError (const char * errorString) inline virtual
Implements rcExperimentObserver.
Definition at line 37 of file rc_batchexperimentobserver.h.
References endl(), rcTimestamp::localtime(), mErrors, rcTimestamp::now(), and silent().
         {
             if ( !silent ) {
                 rcTimestamp now = rcTimestamp::now();
                 cerr << "Visible[cmdLine]" << " error at " << now.localtime()
                      << ": " << errorString << endl;
             }
             ++mErrors;
         }
virtual void rcBatchExperimentObserver::notifyExperimentChange (void) inline virtual
Implements rcExperimentObserver.
Definition at line 161 of file rc_batchexperimentobserver.h.
         {
         }
virtual void rcBatchExperimentObserver::notifyLockApp (bool lock) inline virtual
Implements rcExperimentObserver.
Definition at line 156 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( lock );
         }
void rcBatchExperimentObserver::notifyMultiplier (const double & multiplier) inline virtual
Implements rcExperimentObserver.
Definition at line 130 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( multiplier );
         }
virtual void rcBatchExperimentObserver::notifyPolys () inline virtual
Implements rcExperimentObserver.
Definition at line 172 of file rc_batchexperimentobserver.h.
 {  }
virtual void rcBatchExperimentObserver::notifyProgCursorTime (const rcTimestamp & cursorTime) inline virtual
Implements rcExperimentObserver.
Definition at line 84 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( cursorTime );
         }
virtual void rcBatchExperimentObserver::notifyState (rcExperimentState newState, bool i) inline virtual
Implements rcExperimentObserver.
Definition at line 70 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( i );
             rmUnused( newState );
         }
virtual void rcBatchExperimentObserver::notifyStatus (const char * statusString) inline virtual
Implements rcExperimentObserver.
Definition at line 60 of file rc_batchexperimentobserver.h.
References endl(), rcTimestamp::localtime(), rcTimestamp::now(), and silent().
         {
             if ( !silent ) {
                 rcTimestamp now = rcTimestamp::now();
                 cerr << "Visible[cmdLine]" << " status at "  << now.localtime()
                      << ": " << statusString << endl;
             }
         }
virtual void rcBatchExperimentObserver::notifyTime (const rcTimestamp & cursorTime) inline virtual
Implements rcExperimentObserver.
Definition at line 78 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( cursorTime );
         }
void rcBatchExperimentObserver::notifyTimelineRange (const rcTimestamp & start, const rcTimestamp & end) inline virtual
Implements rcExperimentObserver.
Definition at line 102 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( start );
             rmUnused( end );
         }
virtual void rcBatchExperimentObserver::notifyVideoRect (const rcRect & rect) inline virtual
Implements rcExperimentObserver.
Definition at line 165 of file rc_batchexperimentobserver.h.
References rmUnused.
         {
             rmUnused( rect );
         }
virtual void rcBatchExperimentObserver::notifyWarning (const char * warnString) inline virtual
Implements rcExperimentObserver.
Definition at line 49 of file rc_batchexperimentobserver.h.
References endl(), rcTimestamp::localtime(), mErrors, rcTimestamp::now(), and silent().
         {
             if ( !silent ) {
                 rcTimestamp now = rcTimestamp::now();
                 cerr << "Visible[cmdLine]" << " warning at " << now.localtime()
                      << ": " << warnString << endl;
             }
             ++mErrors;
         }
virtual int32 rcBatchExperimentObserver::progCursorTimeEventCount () const inline virtual
Implements rcExperimentObserver.
Definition at line 90 of file rc_batchexperimentobserver.h.
         {
             return 0;
         }
Member Data Documentation
uint32 rcBatchExperimentObserver::mErrors private
Definition at line 179 of file rc_batchexperimentobserver.h.
Referenced by errors(), notifyBlitData(), notifyBlitGraphics(), notifyError(), notifyWarning(), and rcBatchExperimentObserver().
The documentation for this class was generated from the following file:
include/visiCore/rc_batchexperimentobserver.h