Visible: rcAffineWindow Class Reference
rcAffineWindow Class Reference
#include <include/visual/rc_affinewindow.h>
Public Member Functions
rcAffineWindow ()
rcAffineWindow (const rcAffineWindow &parent)
rcAffineWindow (const rcWindow &parent, const rcAffineRectangle &affine)
rcAffineWindow (const rcWindow &parent, const rcAffineRectangle &affine, bool &isInside)
rcAffineWindow (const rcAffineRectangle &affine, rcPixel depth=rcPixel8)
rcAffineWindow & operator= (const rcAffineWindow &rhs)
const rcAffineRectangle & ar () const
rc2Dvector getPixelLoc (int32 x, int32 y) const
rc2Dvector getPixelLoc (double x, double y) const
rcIPair getImageSz () const
rcGeneratePixel & pixelGenerator ()
rcGenerateImage & imageGenerator ()
vImage_AffineTransform vImageToAffine () const
vImage_AffineTransform vAffineToImage () const
void pixelGenerator (rcGeneratePixel &pixGen)
void imageGenerator (rcGenerateImage &imgGen)
void vImageTransform ()
double genPixel (int32 x, int32 y, rcGeneratePixel *pixGen=0) const
void genImage (rcWindow &dest, const rcIRect &region, rcGenerateImage *imgGen=0) const
void project (vector< float > &dest, rc2Xform &xform, const rcWindow &mask, rcGenerateImage *imgGen=0) const
Public Member Functions inherited from rcWindow
rcWindow ()
default constructor takes no arguments
rcWindow (std::string absPath2TiffFile)
rcWindow (const rcWindow &other)
copy / assignment takes one arguments
const rcWindow & operator= (const rcWindow &rhs)
copy / assignment takes one arguments
rcWindow (rcVideoCache &cache, uint32 frameIndex)
rcWindow (rcSharedFrameBufPtr ptr, int32 x, int32 y, int32 width, int32 height)
rcWindow (rcSharedFrameBufPtr ptr, const rcIPair &icenter, const rcIPair &span, bool &withIn)
rcWindow (rcSharedFrameBufPtr ptr, const rcRect &cropRect)
rcWindow (rcSharedFrameBufPtr ptr)
rcWindow (const rcWindow &parentWindow, int32 x, int32 y, int32 width, int32 height, bool clip=false)
rcWindow (const rcWindow &parentWindow, int32 width, int32 height)
rcWindow (const rcWindow &parentWindow, const rcRect &cropRect, bool clip=false)
rcWindow (const rcWindow &parentWindow, const rcIRect &cropRect, int32 &isInside)
rcWindow (const rcWindow &parentWindow, const rcIPair &icenter, const rcIPair &span, bool &withIn)
rcWindow (int32 width, int32 height, rcPixel depth=rcPixel8)
rcWindow (const rcIPair &size, rcPixel depth=rcPixel8)
virtual ~rcWindow ()
const rcSharedFrameBufPtr & frameBuf () const
rcSharedFrameBufPtr & frameBuf ()
rcPixel depth () const
uint32 pixelCount () const
int32 n () const
bool isGray () const
bool isD32Float () const
int32 x () const
int32 y () const
int32 width () const
int32 height () const
const rcIPair & position () const
rcIPair position ()
rcIPair size () const
rcRect rcBound () const
rcIRect frame () const
const rcRect & rectangle () const
bool contains (const rcWindow &other) const
bool contains (const rcIRect &other) const
bool canPeekOutSide (const rcIPair range) const
bool contains (const uint8 *ptr) const
uint32 isBound () const
bool isWithin (int32 x, int32 y) const
isWithin / isWithin takes a position in the frameBuf coordinate
bool isWithin (const rcIPair &where) const
bool isWithin (const rcRect &rect) const
bool canTrim (int32 delta) const
canTrim / can takes a desired trim tba to all sides
void maxTrim (rcIPair &tl, rcIPair &br) const
int32 maxTrim () const
bool vImage (vImage_Buffer &) const
CGImageRef CGImage () const
int32 bits () const
int32 bytes () const
double operator() (double, double) const
uint32 getPixel (int32 x, int32 y) const
double getDoublePixel (int32 x, int32 y) const
uint32 getPixel (const rcIPair &where) const
double getDoublePixel (const rcIPair &where) const
const uint8 * rowPointer (int32 y) const
uint8 * rowPointer (int32 y)
const uint8 * pelPointer (int32 x, int32 y) const
uint8 * pelPointer (int32 x, int32 y)
int32 rowUpdate () const
int32 rowPixelUpdate () const
double zVal () const
bool sameTime (const rcWindow &other) const
rcTimestamp timestamp () const
rcWindow & windowRelativeTo (const rcWindow &parentWindow, int32 x, int32 y, int32 width, int32 height)
bool translate (const rcIPair &delta)
void entire ()
rcWindow & trim (uint32 delta)
bool trim (int32 delta)
bool trim (rcIPair delta)
uint32 setPixel (int32 x, int32 y, uint32 value)
double setDoublePixel (int32 x, int32 y, double value)
uint32 setPixel (const rcIPair &where, uint32 value)
double setDoublePixel (const rcIPair &where, double value)
rcWindow & copyPixelsFromWindow (const rcWindow &srcWindow, bool mirror=false)
rcWindow & set (double pixelValue)
rcWindow & setAllPixels (uint32 pixelValue)
rcWindow & setAllDoublePixels (double pixelValue)
void atTime (const rcWindow &other)
void zVal (double dv)
uint32 randomFill (uint32 seed=0)
void mirror ()
bool operator== (const rcWindow &) const
bool operator!= (const rcWindow &) const
bool contentCompare (const rcWindow &, bool verbose=false) const
bool contentMaskCompare (const rcWindow &, const rcWindow &mask) const
bool tiff (std::string &outfile, bool compress=false) const
template<class T >
void print (T, ostream &=cerr)
template<class T >
void print (T)
Static Public Member Functions
static rcGeneratePixel * createDefGen ()
Private Attributes
rcAffineRectangle _affine
rcGeneratePixel * _pixGen
rcGenerateImage * _imgGen
vImage_AffineTransform mVa2i
vImage_AffineTransform mVi2a
Static Private Attributes
static rcGeneratePixel * _defPixGen = rcAffineWindow::createDefGen()
static rcGenerateImage * _defImgGen = 0
Additional Inherited Members
Protected Member Functions inherited from rcWindow
void init (int32 w, int32 h, rcPixel depth)
bool window (const rcWindow &parentWindow, int32 x, int32 y, int32 width, int32 height, bool clip)
Protected Attributes inherited from rcWindow
rcSharedFrameBufPtr mFrameBuf
rcRect mGeometry
Detailed Description
Definition at line 20 of file rc_affinewindow.h.
Constructor & Destructor Documentation
rcAffineWindow::rcAffineWindow () inline
Definition at line 23 of file rc_affinewindow.h.
 : _pixGen (NULL), _imgGen (NULL)  , _affine (rcAffineRectangle () ) {}
rcAffineWindow::rcAffineWindow (const rcAffineWindow & parent)
Definition at line 21 of file rc_affinewindow.cpp.
   : rcWindow(parent), _affine(parent.ar()),
     _pixGen(parent._pixGen), _imgGen(parent._imgGen)
 {
 }
rcAffineWindow::rcAffineWindow (const rcWindow & parent, const rcAffineRectangle & affine)
Definition at line 27 of file rc_affinewindow.cpp.
References _imgGen, _pixGen, rcAffineRectangle::boundingBox(), rcWindow::isWithin(), and rmAssert.
   : rcWindow(parent), _affine(affine), _pixGen(_defPixGen), _imgGen(_defImgGen)
 {
   rmAssert(_pixGen && _imgGen);
   rmAssert(isWithin(affine.boundingBox()));
 }
rcAffineWindow::rcAffineWindow (const rcWindow & parent, const rcAffineRectangle & affine, bool & isInside)
Definition at line 35 of file rc_affinewindow.cpp.
References _imgGen, _pixGen, rcAffineRectangle::boundingBox(), rcWindow::isWithin(), and rmAssert.
   : rcWindow(parent), _affine(affine), _pixGen(_defPixGen), _imgGen(_defImgGen)
 {
   rmAssert(_pixGen && _imgGen);
   isInside = isWithin(affine.boundingBox());
 }
rcAffineWindow::rcAffineWindow (const rcAffineRectangle & affine, rcPixel depth = rcPixel8)
Definition at line 45 of file rc_affinewindow.cpp.
References _imgGen, _pixGen, rcAffineRectangle::boundingBox(), rcWindow::isWithin(), and rmAssert.
   : rcWindow(affine.boundingBox().lr(), depth), _affine(affine),
     _pixGen(_defPixGen), _imgGen(_defImgGen)
 {
   rmAssert(_pixGen && _imgGen);
   rmAssert(isWithin(affine.boundingBox()));
 }
Member Function Documentation
const rcAffineRectangle& rcAffineWindow::ar () const inline
Definition at line 60 of file rc_affinewindow.h.
References _affine.
Referenced by rcCubicGeneratePixel::genPixel(), rcShape::needCenterOfmass(), rcShape::needMedian(), rcDefGenerateImage::project(), and vImageTransform().
   { return _affine; }
rcGeneratePixel * rcAffineWindow::createDefGen () static
Definition at line 54 of file rc_affinewindow.cpp.
References _defImgGen, _defPixGen, and rmAssert.
 {
   if (!_defPixGen) {
     _defPixGen = new rcDefGeneratePixel();
     rmAssert(_defPixGen);
     _defImgGen = new rcDefGenerateImage(*_defPixGen);
     rmAssert(_defImgGen);
   }
   return _defPixGen;
 }
void rcAffineWindow::genImage (rcWindow & dest, const rcIRect & region, rcGenerateImage * imgGen = 0) const inline
Definition at line 100 of file rc_affinewindow.h.
Referenced by rcShape::profiles().
   { if (imgGen)
       (*imgGen).genImage(this, dest, region);
     else
       (*_imgGen).genImage(this, dest, region);
   }
double rcAffineWindow::genPixel (int32 x, int32 y, rcGeneratePixel * pixGen = 0) const inline
Definition at line 94 of file rc_affinewindow.h.
References getPixelLoc(), rc2dVector< T >::x(), and rc2dVector< T >::y().
   { rc2Dvector v(getPixelLoc(x, y));
     if (pixGen)
       return (*pixGen).genPixel(this, v.x(), v.y());
     return (*_pixGen).genPixel(this, v.x(), v.y());
   }
rcIPair rcAffineWindow::getImageSz () const inline
Definition at line 66 of file rc_affinewindow.h.
References _affine, and rcAffineRectangle::cannonicalSize().
   { return _affine.cannonicalSize(); }
rc2Dvector rcAffineWindow::getPixelLoc (int32 x, int32 y) const inline
Definition at line 62 of file rc_affinewindow.h.
References _affine, and rcAffineRectangle::getPixelLoc().
Referenced by rcDefGenerateImage::genImage(), genPixel(), and rcDefGenerateImage::project().
   { return _affine.getPixelLoc(x, y); }
rc2Dvector rcAffineWindow::getPixelLoc (double x, double y) const inline
Definition at line 64 of file rc_affinewindow.h.
References _affine, and rcAffineRectangle::getPixelLoc().
   { return _affine.getPixelLoc(x, y); }
rcGenerateImage& rcAffineWindow::imageGenerator () inline
Definition at line 70 of file rc_affinewindow.h.
References _imgGen.
   { return *_imgGen; }
void rcAffineWindow::imageGenerator (rcGenerateImage & imgGen) inline
Definition at line 87 of file rc_affinewindow.h.
References _imgGen.
   { _imgGen = &imgGen; }
rcAffineWindow& rcAffineWindow::operator= (const rcAffineWindow & rhs) inline
Definition at line 45 of file rc_affinewindow.h.
References _affine, _imgGen, _pixGen, mVa2i, and mVi2a.
   {
     if (this != &rhs) {
       ((rcWindow*)this)->operator=(*(rcWindow*)&rhs);
       _affine = rhs._affine;
       _pixGen = rhs._pixGen;
       _imgGen = rhs._imgGen;
         mVa2i = rhs.mVa2i;
             mVi2a = rhs.mVi2a;
     }
     return *this;
   }
rcGeneratePixel& rcAffineWindow::pixelGenerator () inline
Definition at line 68 of file rc_affinewindow.h.
References _pixGen.
   { return *_pixGen; }
void rcAffineWindow::pixelGenerator (rcGeneratePixel & pixGen) inline
Definition at line 85 of file rc_affinewindow.h.
References _pixGen.
   { _pixGen = &pixGen; }
void rcAffineWindow::project (vector< float > & dest, rc2Xform & xform, const rcWindow & mask, rcGenerateImage * imgGen = 0) const inline
Definition at line 108 of file rc_affinewindow.h.
   { if (imgGen)
       (*imgGen).project(this, dest, mask, xform);
     else
       (*_imgGen).project(this, dest, mask, xform);
   }
vImage_AffineTransform rcAffineWindow::vAffineToImage () const
Definition at line 96 of file rc_affinewindow.cpp.
References mVa2i, and vImageTransform().
 {
   const_cast<rcAffineWindow *>(this)->vImageTransform ();
   return mVa2i;
 }
vImage_AffineTransform rcAffineWindow::vImageToAffine () const
Definition at line 102 of file rc_affinewindow.cpp.
References mVi2a, and vImageTransform().
Referenced by rcDefGenerateImage::genImage().
 {
   const_cast<rcAffineWindow *>(this)->vImageTransform ();
   return mVi2a;
 }
void rcAffineWindow::vImageTransform ()
Definition at line 71 of file rc_affinewindow.cpp.
References rcAffineRectangle::affineToImage(), ar(), arctan(), rcRadian::basic(), CG2VIMAGE, cos(), rcWindow::height(), mVa2i, mVi2a, sin(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by vAffineToImage(), and vImageToAffine().
 {
 /*      @note: (from /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/Headers/Geometry.h)
  *  For the Affine Transform function the coordinate space places the origin at the bottom left corner
  *  of the image. Positive movement in the X and Y direction moves you right and up. Both source and destination
  *  images are assumed to place their bottom left hand corner at the origin.
  */
   const rc2Dvector bl = ar().affineToImage(rc2Dvector(0.0, 1.0));
   // Angle goes from +x -> + y to +x -> - y.
   rcRadian r = arctan (-sin (ar().angle ()), cos (ar().angle()));
   // Image coordinates wrt top left of the image and then bottom left
   CGPoint blg = {(float) bl.x(), height() - bl.y()};
   CGAffineTransform a2i = CGAffineTransformRotate (CGAffineTransformMakeTranslation (blg.x, blg.y),
                    (float) r.basic ());
   CGAffineTransform i2a = CGAffineTransformInvert (a2i);
   CG2VIMAGE(mVa2i, a2i);
   CG2VIMAGE(mVi2a, i2a);
 }
Member Data Documentation
rcAffineRectangle rcAffineWindow::_affine private
Definition at line 121 of file rc_affinewindow.h.
Referenced by ar(), getImageSz(), getPixelLoc(), and operator=().
rcGenerateImage * rcAffineWindow::_defImgGen = 0 static private
Definition at line 128 of file rc_affinewindow.h.
Referenced by createDefGen().
rcGeneratePixel * rcAffineWindow::_defPixGen = rcAffineWindow::createDefGen() static private
Definition at line 127 of file rc_affinewindow.h.
Referenced by createDefGen().
rcGenerateImage* rcAffineWindow::_imgGen private
Definition at line 123 of file rc_affinewindow.h.
Referenced by imageGenerator(), operator=(), and rcAffineWindow().
rcGeneratePixel* rcAffineWindow::_pixGen private
Definition at line 122 of file rc_affinewindow.h.
Referenced by operator=(), pixelGenerator(), and rcAffineWindow().
vImage_AffineTransform rcAffineWindow::mVa2i private
Definition at line 124 of file rc_affinewindow.h.
Referenced by operator=(), vAffineToImage(), and vImageTransform().
vImage_AffineTransform rcAffineWindow::mVi2a private
Definition at line 125 of file rc_affinewindow.h.
Referenced by operator=(), vImageToAffine(), and vImageTransform().
The documentation for this class was generated from the following files:
include/visual/rc_affinewindow.h
src/visual/code/rc_affinewindow.cpp