Visible: rcCameraFormat Class Reference
rcCameraFormat Class Reference
#include <include/visual/rc_dcam.h>
Public Member Functions
rcCameraFormat ()
rcCameraFormat (uint16 width, uint16 height, uint8 format, uint8 mode, rcCameraColorFormat color, unsigned long dynamic_bitset_ulong, float specific_fps=0.0f, uint8 bin_x=1, uint8 bin_y=1)
const int32 & width () const
const int32 & height () const
const uint8 & format () const
const uint8 & mode () const
const rcCameraColorFormat & color () const
const float frames_per_second ()
bool operator< (const rcCameraFormat &o) const
const uint8 & bin_x () const
const uint8 & bin_y () const
rcPixel depth () const
bool isMono () const
bool isMono8 () const
float frames_per_second (int i)
Friends
ostream & operator<< (ostream &os, const rcCameraFormat &c)
Detailed Description
Definition at line 48 of file rc_dcam.h.
Constructor & Destructor Documentation
rcCameraFormat::rcCameraFormat () inline
Definition at line 51 of file rc_dcam.h.
     {
         }
rcCameraFormat::rcCameraFormat (uint16 width, uint16 height, uint8 format, uint8 mode, rcCameraColorFormat color, unsigned long dynamic_bitset_ulong, float specific_fps = 0.0f, uint8 bin_x = 1, uint8 bin_y = 1) inline
Definition at line 55 of file rc_dcam.h.
     :
         boost::tuple<rcIPair,uint8,uint8,rcCameraColorFormat,unsigned long,uint8,uint8,float>  (boost::make_tuple(rcIPair (width,height),format, mode , color, dynamic_bitset_ulong, specific_fps, bin_x, bin_y))
     {
}
Member Function Documentation
const uint8& rcCameraFormat::bin_x () const inline
Definition at line 96 of file rc_dcam.h.
 { return get<6>(); }
const uint8& rcCameraFormat::bin_y () const inline
Definition at line 97 of file rc_dcam.h.
 { return get<7>(); }
const rcCameraColorFormat& rcCameraFormat::color () const inline
Definition at line 70 of file rc_dcam.h.
 { return get<3>(); }
rcPixel rcCameraFormat::depth () const inline
Definition at line 100 of file rc_dcam.h.
References rcCameraColorFormatGray16, rcCameraColorFormatGray8, rcCameraColorFormatRGB24, rcCameraColorFormatYUV411, rcCameraColorFormatYUV422, rcCameraColorFormatYUV444, rcPixel16, rcPixel32, rcPixel8, and rcPixelUnknown.
     {
         switch ( get<3>() )
         {
             case rcCameraColorFormatYUV444:
             case rcCameraColorFormatYUV422:
             case rcCameraColorFormatYUV411:
             case rcCameraColorFormatRGB24:
                 return rcPixel32;
             case rcCameraColorFormatGray8:
                 return rcPixel8;
             case rcCameraColorFormatGray16:
                 return rcPixel16;
             default:
                 return rcPixelUnknown;
         }
     }
const uint8& rcCameraFormat::format (void) const inline
Definition at line 68 of file rc_dcam.h.
Referenced by operator<(), useLargestAvailableColorMode(), and useLargestAvailableMonoMode().
 { return get<1>(); }
const float rcCameraFormat::frames_per_second () inline
Definition at line 71 of file rc_dcam.h.
     {
         dynamic_bitset<>  maskfps (8,get<4>());
         if (maskfps.none())
             return get<5>();
         else
         {
             float maxfps = 0.0f;
             for (int i = 0; i < 8; i++)
                 if (maskfps[i])
                 {
                     float tmp = frames_per_second (i);
                     if (tmp > maxfps)
                         maxfps = tmp;
                 }
             return maxfps;
         }
     }
float rcCameraFormat::frames_per_second (int i) inline
Definition at line 150 of file rc_dcam.h.
     {
         return 1.875 * ( 1 << i );
     }
const int32& rcCameraFormat::height () const inline
Definition at line 67 of file rc_dcam.h.
Referenced by useLargestAvailableColorMode(), and useLargestAvailableMonoMode().
 { return get<0>().second; }
bool rcCameraFormat::isMono () const inline
Definition at line 118 of file rc_dcam.h.
References rcCameraColorFormatGray16, and rcCameraColorFormatGray8.
Referenced by useLargestAvailableColorMode().
     {
         switch ( get<3>() )
         {
             case rcCameraColorFormatGray8:
             case rcCameraColorFormatGray16:
                 return true;
             default:
                 return false;
         }
     }
bool rcCameraFormat::isMono8 () const inline
Definition at line 130 of file rc_dcam.h.
References rcCameraColorFormatGray8.
Referenced by useLargestAvailableMonoMode().
     {
         switch ( get<3>() )
         {
             case rcCameraColorFormatGray8:
                 return true;
             default:
                 return false;
         }
     }
const uint8& rcCameraFormat::mode (void) const inline
Definition at line 69 of file rc_dcam.h.
Referenced by useLargestAvailableColorMode(), and useLargestAvailableMonoMode().
 { return get<2>(); }
bool rcCameraFormat::operator< (const rcCameraFormat & o) const inline
Definition at line 91 of file rc_dcam.h.
References format().
     {
         return format() < o.format();
     }
const int32& rcCameraFormat::width () const inline
Definition at line 66 of file rc_dcam.h.
Referenced by useLargestAvailableColorMode(), and useLargestAvailableMonoMode().
 { return get<0>().first; }
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const rcCameraFormat & c) friend
Definition at line 141 of file rc_dcam.h.
     {
         os << "format " << int(c.format()) << " mode " << int(c.mode())
         <<  " " << c.width() << "x" << c.height() << "x" << c.depth()*8
         << " " << c.color();
         return os;
     }
The documentation for this class was generated from the following file:
include/visual/rc_dcam.h