Visible: rcExperimentDomain Class Reference
rcExperimentDomain Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcExperimentDomain ()
virtual void initialize (rcExperimentObserver *observer)=0
virtual void shutdown (void)=0
virtual rcExperiment * getExperiment (void)=0
virtual void newExperiment (void)=0
virtual int loadExperiment (const char *fileName, const rcXMLElementTree &tree, rcExperimentImportMode mode, rcProgressIndicator *progress=0)=0
virtual int saveExperiment (const char *fileName=0, rcExperimentFileFormat format=eExperimentCSVFormat, rcProgressIndicator *progress=0)=0
virtual rcExperimentState getExperimentState (void)=0
virtual const
rcExperimentAttributes getExperimentAttributes (void)=0
virtual void setExperimentAttributes (const rcExperimentAttributes &attrs)=0
virtual bool operatingOnLiveInput (void)=0
virtual bool storingLiveInput (void)=0
virtual rcTimestamp getExperimentLength (void)=0
virtual rcTimestamp getCursorTime (void)=0
virtual void notifyCursorTime (const rcTimestamp &time)=0
virtual void notifyMovieImport ()=0
virtual rcTimestamp getExperimentStart (void)=0
virtual void startExperiment (void)=0
virtual void stopExperiment (void)=0
virtual void processExperiment (void)=0
virtual bool pauseTrackingExperiment (void)=0
virtual bool doneSelecting (void)=0
virtual void notifyPolys (const rcPolygonGroupRef *polys)=0
Detailed Description
Definition at line 107 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcExperimentDomain::~rcExperimentDomain () inline virtual
Definition at line 111 of file rc_model.h.
 { };
Member Function Documentation
virtual bool rcExperimentDomain::doneSelecting (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::stopTrackingPause().
virtual rcTimestamp rcExperimentDomain::getCursorTime (void) pure virtual
Implemented in rcExperimentDomainImpl.
virtual rcExperiment* rcExperimentDomain::getExperiment (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::getExperiment().
virtual const rcExperimentAttributes rcExperimentDomain::getExperimentAttributes (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::getExperimentAttributes(), rcModelDomain::requestSave(), and rcModelDomain::requestStop().
virtual rcTimestamp rcExperimentDomain::getExperimentLength (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::getExperimentLength(), and rcModelDomain::timerTick().
virtual rcTimestamp rcExperimentDomain::getExperimentStart (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcCSVExporter::exportExperiment(), rcModelDomain::getExperimentStart(), rcNativeExporter::produceResults(), rcSegmentIteratorImpl::rcSegmentIteratorImpl(), and rcSegmentIteratorImpl::reset().
virtual rcExperimentState rcExperimentDomain::getExperimentState (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::getExperimentState().
virtual void rcExperimentDomain::initialize (rcExperimentObserver * observer) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::rcModelDomain().
virtual int rcExperimentDomain::loadExperiment (const char * fileName, const rcXMLElementTree & tree, rcExperimentImportMode mode, rcProgressIndicator * progress = 0) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestOpen().
virtual void rcExperimentDomain::newExperiment (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestClose(), and rcModelDomain::requestNew().
virtual void rcExperimentDomain::notifyCursorTime (const rcTimestamp & time) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::notifyCursorTime().
virtual void rcExperimentDomain::notifyMovieImport () pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestMovieImport(), and rcModelDomain::requestSTKImport().
virtual void rcExperimentDomain::notifyPolys (const rcPolygonGroupRef * polys) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::notifyPolys().
virtual bool rcExperimentDomain::operatingOnLiveInput (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::notifyTime(), rcModelDomain::operatingOnLiveInput(), and rcModelDomain::requestStop().
virtual bool rcExperimentDomain::pauseTrackingExperiment (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestTrackingPause().
virtual void rcExperimentDomain::processExperiment (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestProcess().
virtual int rcExperimentDomain::saveExperiment (const char * fileName = 0, rcExperimentFileFormat format = eExperimentCSVFormat, rcProgressIndicator * progress = 0) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestSave().
virtual void rcExperimentDomain::setExperimentAttributes (const rcExperimentAttributes & attrs) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::setExperimentAttributes().
virtual void rcExperimentDomain::shutdown (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::~rcModelDomain().
virtual void rcExperimentDomain::startExperiment (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestStart().
virtual void rcExperimentDomain::stopExperiment (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::requestStop().
virtual bool rcExperimentDomain::storingLiveInput (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcModelDomain::storingLiveInput().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h