Visible: rcCSVExporter Class Reference
rcCSVExporter Class Reference
#include <include/visiCore/rc_csvexporter.h>
Public Member Functions
rcCSVExporter (const char *fileName, rcExperiment *experiment, const char *comment, rcProgressIndicator *progress)
virtual ~rcCSVExporter ()
virtual int exportExperiment ()
Public Member Functions inherited from rcExporter
rcExporter (const char *fileName, rcExperimentFileFormat fileFormat, rcExperiment *experiment, const char *comment, rcProgressIndicator *progress)
virtual ~rcExporter ()
Private Member Functions
int exportTracks (ofstream &outfile, uint32 firstTrack, uint32 lastTrack, const vector< rcTimestamp > times, uint32 &cellCount)
Additional Inherited Members
Protected Member Functions inherited from rcExporter
void init (rcTimestamp startTime)
bool produceValue (ostream &stream, rcSegmentIterator *iter, rcTrackType type, rcExperimentFileFormat fileFormat)
bool isExportable (rcTrack *track) const
Protected Attributes inherited from rcExporter
const std::string mFileName
rcExperimentFileFormat mFileFormat
rcExperiment * mExperiment
vector< uint32 > mExportGroups
vector< rcTrack * > mExportTracks
vector< const char * > mExportTrackFormatStrings
vector< rcSegmentIterator * > mExportIterators
vector< uint32 > mExportIteratorGroups
std::string mExportGeneratorComment
vector< bool > mExportActiveIterators
rcProgressIndicator * mProgress
uint32 mValuesToExport
vector< rcTimestamp > mTimes
Detailed Description
Definition at line 16 of file rc_csvexporter.h.
Constructor & Destructor Documentation
rcCSVExporter::rcCSVExporter (const char * fileName, rcExperiment * experiment, const char * comment, rcProgressIndicator * progress)
Definition at line 32 of file rc_csvexporter.cpp.
                                                               :
         rcExporter( fileName, eExperimentCSVFormat, experiment, comment, progress )
 {
 }
rcCSVExporter::~rcCSVExporter () virtual
Definition at line 40 of file rc_csvexporter.cpp.
 {
 }
Member Function Documentation
int rcCSVExporter::exportExperiment () virtual
Implements rcExporter.
Definition at line 44 of file rc_csvexporter.cpp.
References endl(), exportTracks(), rcSettingInfo::getDisplayName(), rcExperimentDomainFactory::getExperimentDomain(), rcExperimentDomain::getExperimentStart(), rcExperiment::getNSettingCategories(), rcSettingCategory::getNSettings(), rcExperiment::getSettingCategory(), rcSettingCategory::getSettingInfo(), rcSettingInfo::getValue(), rcSettingInfo::isPersistable(), rcTimestamp::localtime(), rcExporter::mExperiment, rcExporter::mExportGeneratorComment, rcExporter::mExportTracks, rcExporter::mFileName, rcExporter::mProgress, rcExporter::mTimes, rcTimestamp::now(), rcProgressIndicator::progress(), and rcTimestamp::secs().
Referenced by rcExperimentImpl::saveTo().
 {
     int err = 0;
     int i, j;
     ofstream outfile( mFileName.c_str() );
     // Set a large output stream buffer for improved speed
     char streamBuf[65536*2];
     outfile.rdbuf()->pubsetbuf( streamBuf, sizeof( streamBuf ) );
      if ( outfile.fail() )
         err = EIO;
     if ( outfile.bad() )
         err = EIO;
     if ( mProgress )
         mProgress->progress( 0.0 );
     rcTimestamp startTime = rcTimestamp::now();
     rcExperimentDomain* domain = rcExperimentDomainFactory::getExperimentDomain();
     rcTimestamp experimentStart = domain->getExperimentStart();
     // output generator info
     std::string comment( "Document generator, " );
     comment += mExportGeneratorComment;
     outfile << comment << endl;
     // output settings at top of file
     int nCategories = mExperiment->getNSettingCategories();
     for (i = 0; i < nCategories; ++i)
     {
         rcSettingCategory category = mExperiment->getSettingCategory( i );
         int nSettings = category.getNSettings();
         for (j = 0; j < nSettings; ++j)
         {
             rcSettingInfo setting = category.getSettingInfo( j );
             // Persistability check
             if ( setting.isPersistable() ) {
                 outfile << setting.getDisplayName() << ", "
                         << setting.getValue() << endl;
             }
         }
         outfile << endl;
     }
     std::string timeString = experimentStart.localtime();
     if ( timeString.size() )
         outfile << "Experiment video capture date, " << timeString << endl;
     // Iterate all valid timestamps
     vector<rcTimestamp> times( mTimes.size() );
     for ( uint32 i = 0; i < mTimes.size(); ++i ) {
         // Compute iterator start times from experiment start
         times[i] = mTimes[i] - experimentStart;
     }
     const uint32 trackCount = mExportTracks.size();
     // Maximum number of columns to export
     const uint32 maxColumns = 255;
     // Count of cells exported
     uint32 cellCount = 0;
     // Export tracks in consecutive ranges
     // TODO: dynamically adjustable range lengths so that tracks from the same
     // cell group do not get split into two separate ranges
     for ( uint32 firstTrack = 0; firstTrack < trackCount; firstTrack += maxColumns ) {
         uint32 lastTrack = firstTrack + maxColumns - 1;
         if ( lastTrack > (trackCount-1) )
             lastTrack = trackCount-1;
         if ( firstTrack <= lastTrack ) {
             // Export one range
             err += exportTracks( outfile, firstTrack, lastTrack, times, cellCount );
         }
     }
     // close the file and exit.
     outfile.close();
     rcTimestamp elapsedTime = rcTimestamp::now() - startTime;
     cout << cellCount << " CSV data cells exported to file in " << elapsedTime.secs() << " seconds" << endl;
     if ( outfile.fail() )
         err = EIO;
     if ( outfile.bad() )
         err = EIO;
     return err;
 }
int rcCSVExporter::exportTracks (ofstream & outfile, uint32 firstTrack, uint32 lastTrack, const vector< rcTimestamp > times, uint32 & cellCount) private
Definition at line 137 of file rc_csvexporter.cpp.
References rcSegmentIterator::contains(), eExperimentCSVFormat, endl(), rcTrackGroup::getDescription(), rcTrack::getDescription(), rcSegmentIterator::getFocus(), rcTrackGroup::getName(), rcExperiment::getTrackGroup(), rcExporter::init(), rcExporter::mExperiment, rcExporter::mExportIteratorGroups, rcExporter::mExportIterators, rcExporter::mExportTracks, rcExporter::mProgress, rcExporter::mValuesToExport, rcExporter::produceValue(), rcProgressIndicator::progress(), and stripCommas().
Referenced by exportExperiment().
 {
     int err = 0;
     uint32 i;
     outfile << "Data tracks, [" << firstTrack << "-" << lastTrack << "]" << endl;
     // output group info
     outfile << "Measurement group name ";
     for (i = firstTrack; i <= lastTrack; ++i)
     {
         rcTrackGroup* group = mExperiment->getTrackGroup( mExportIteratorGroups[i] );
         std::string name( group->getName() );
         stripCommas( name );
         outfile << ", " << name;
     }
     outfile << endl;
     outfile << "Measurement group description ";
     for (i = firstTrack; i <= lastTrack; ++i)
     {
         rcTrackGroup* group = mExperiment->getTrackGroup( mExportIteratorGroups[i] );
         std::string descr( group->getDescription() );
         stripCommas( descr );
         outfile << ", " << descr;
     }
     outfile << endl;
     // output a line with the descriptions of the tracks
     outfile << "Frame / Time in seconds";
 #ifdef ANALYSIS_AREA_PER_FRAME
     outfile << ", Analysis area [x y w h]";
 #endif
     for (i = firstTrack; i <= lastTrack; ++i)
     {
         rcTrack* track = mExportTracks[ i ];
         outfile << ", " << track->getDescription();
     }
     outfile << endl;
     // Iterate all the active tracks
     for ( uint32 a = 0; a < times.size(); ++a ) {
         // Init all iterators with the correct start time
         init( times[a] );
         for ( uint32 i = firstTrack; i <= lastTrack; ++i)
         {
             rcSegmentIterator* iter = mExportIterators[ i ];
             if ( i == firstTrack ) {
                 // Output time as first column
           outfile << times[a].secs();
           //                outfile << a+1 << " / " <<  times[a].secs();
 #ifdef ANALYSIS_AREA_PER_FRAME
                 // output current focus area
                 rcValue focus( iter->getFocus() );
                 outfile << ", " << focus;
 #endif
             }
             outfile << ", ";
             bool hasValue = iter->contains( times[a] );
             if ( hasValue ) {
                 if ( !produceValue( outfile, iter,  mExportTracks[i]->getTrackType(), eExperimentCSVFormat ) ) {
                     fprintf( stderr, "rcCSVExporter error: produceValue() failed\n" );
                 }
             } else {
                 // No defined value at this time stamp
                 outfile << " ";
             }
             if ( mProgress && !(cellCount % 256)) {
                 mProgress->progress( 100.0*cellCount/mValuesToExport );
             }
             ++cellCount;
         }
         outfile << endl;
     }
     return err;
 }
The documentation for this class was generated from the following files:
include/visiCore/rc_csvexporter.h
src/visible/src/rc_csvexporter.cpp