Visible: subprocess Class Reference
subprocess Class Reference
#include <include/stlplus/subprocesses.hpp>
Public Member Functions
subprocess (void)
virtual ~subprocess (void)
void add_variable (const std::string &name, const std::string &value)
bool remove_variable (const std::string &name)
bool spawn (const std::string &path, const arg_vector &argv, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)
bool spawn (const std::string &command_line, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)
virtual bool callback (void)
bool kill (void)
int write_stdin (std::string &buffer)
int read_stdout (std::string &buffer)
int read_stderr (std::string &buffer)
void close_stdin (void)
void close_stdout (void)
void close_stderr (void)
bool error (void) const
int error_number (void) const
std::string error_text (void) const
int exit_status (void) const
Private Attributes
int pid
int child_in
int child_out
int child_err
env_vector env
int err
int status
Detailed Description
Definition at line 163 of file subprocesses.hpp.
Constructor & Destructor Documentation
subprocess::subprocess (void)
Definition at line 788 of file subprocesses.cpp.
References child_err, child_in, child_out, err, pid, and status.
 {
   pid = -1;
   child_in = -1;
   child_out = -1;
   child_err = -1;
   err = 0;
   status = 0;
 }
subprocess::~subprocess (void) virtual
Definition at line 818 of file subprocesses.cpp.
References close_stderr(), close_stdin(), close_stdout(), kill(), and pid.
 {
   if (pid != -1)
   {
     close_stdin();
     close_stdout();
     close_stderr();
     kill();
     for (;;)
     {
       int wait_status = 0;
       int wait_ret_val = waitpid(pid, &wait_status, 0);
       if (wait_ret_val != -1 || errno != EINTR) break;
     }
   }
 }
Member Function Documentation
void subprocess::add_variable (const std::string & name, const std::string & value)
Definition at line 837 of file subprocesses.cpp.
 {
   env.add(name, value);
 }
bool subprocess::callback (void) virtual
Reimplemented in backtick_subprocess.
Definition at line 1076 of file subprocesses.cpp.
Referenced by spawn().
 {
   return true;
 }
void subprocess::close_stderr (void)
Definition at line 1330 of file subprocesses.cpp.
References child_err, and close().
Referenced by kill(), read_stderr(), spawn(), and ~subprocess().
 {
   if (child_err != -1)
   {
     ::close(child_err);
     child_err = -1;
   }
 }
void subprocess::close_stdin (void)
Definition at line 1282 of file subprocesses.cpp.
References child_in, and close().
Referenced by kill(), spawn(), write_stdin(), and ~subprocess().
 {
   if (child_in != -1)
   {
     ::close(child_in);
     child_in = -1;
   }
 }
void subprocess::close_stdout (void)
Definition at line 1306 of file subprocesses.cpp.
References child_out, and close().
Referenced by kill(), read_stdout(), spawn(), and ~subprocess().
 {
   if (child_out != -1)
   {
     ::close(child_out);
     child_out = -1;
   }
 }
bool subprocess::error (void) const
Definition at line 1341 of file subprocesses.cpp.
References err.
Referenced by backtick_subprocess::callback().
 {
   return err != 0;
 }
int subprocess::error_number (void) const
Definition at line 1346 of file subprocesses.cpp.
References err.
 {
   return err;
 }
std::string subprocess::error_text (void) const
Definition at line 1370 of file subprocesses.cpp.
References err, and to_string().
 {
   if (err == 0) return std::string();
   char* text = strerror(err);
   if (text) return std::string(text);
   return "error number " + to_string(err);
 }
int subprocess::exit_status (void) const
Definition at line 1380 of file subprocesses.cpp.
References status.
 {
   return status;
 }
bool subprocess::kill (void)
Definition at line 1099 of file subprocesses.cpp.
References close_stderr(), close_stdin(), close_stdout(), err, and pid.
Referenced by spawn(), and ~subprocess().
 {
   if (pid == -1) return false;
   close_stdin();
   close_stdout();
   close_stderr();
   if (::kill(pid, SIGINT) == -1)
   {
     err = errno;
     return false;
   }
   return true;
 }
int subprocess::read_stderr (std::string & buffer)
Definition at line 1242 of file subprocesses.cpp.
References itext::bytes(), child_err, close_stderr(), and err.
 {
   if (child_err == -1) return -1;
   int buffer_size = 256;
   char* tmp = new char[buffer_size];
   int bytes = read(child_err, tmp, buffer_size);
   if (bytes == -1)
   {
     err = errno;
     close_stderr();
     delete[] tmp;
     return -1;
   }
   if (bytes == 0)
   {
     // EOF
     close_stderr();
     delete[] tmp;
     return -1;
   }
   buffer.append(tmp, bytes);
   delete[] tmp;
   return bytes;
 }
int subprocess::read_stdout (std::string & buffer)
Definition at line 1185 of file subprocesses.cpp.
References itext::bytes(), child_out, close_stdout(), and err.
Referenced by backtick_subprocess::callback().
 {
   if (child_out == -1) return -1;
   int buffer_size = 256;
   char* tmp = new char[buffer_size];
   int bytes = read(child_out, tmp, buffer_size);
   if (bytes == -1)
   {
     err = errno;
     close_stdout();
     delete[] tmp;
     return -1;
   }
   if (bytes == 0)
   {
     // EOF
     close_stdout();
     delete[] tmp;
     return -1;
   }
   buffer.append(tmp, bytes);
   delete[] tmp;
   return bytes;
 }
bool subprocess::remove_variable (const std::string & name)
Definition at line 842 of file subprocesses.cpp.
 {
   return env.remove(name);
 }
bool subprocess::spawn (const std::string & path, const arg_vector & argv, bool connect_stdin = false, bool connect_stdout = false, bool connect_stderr = false)
Definition at line 941 of file subprocesses.cpp.
References arg_vector::argv(), callback(), child_err, child_in, child_out, close(), close_stderr(), close_stdin(), close_stdout(), err, kill(), pid, and status.
Referenced by spawn(), and backtick_subprocess::spawn().
 {
   bool result = true;
   // first create the pipes to be used to connect to the child stdin/out/err
   int stdin_pipe [2] = {-1, -1};
   if (connect_stdin)
     pipe(stdin_pipe);
   int stdout_pipe [2] = {-1, -1};
   if (connect_stdout)
     pipe(stdout_pipe);
   int stderr_pipe [2] = {-1, -1};
   if (connect_stderr)
     pipe(stderr_pipe);
   // now create the subprocess
   // In Unix, this is done by forking (creating two copies of the parent), then overwriting the child copy using exec
   pid = ::fork();
   switch(pid)
   {
   case -1:   // failed to fork
     err = errno;
     if (connect_stdin)
     {
       ::close(stdin_pipe[0]);
       ::close(stdin_pipe[1]);
     }
     if (connect_stdout)
     {
       ::close(stdout_pipe[0]);
       ::close(stdout_pipe[1]);
     }
     if (connect_stderr)
     {
       ::close(stderr_pipe[0]);
       ::close(stderr_pipe[1]);
     }
     result = false;
     break;
   case 0:  // in child;
   {
     // for each pipe, close the end of the duplicated pipe that is being used by the parent
     // and connect the child's end of the pipe to the appropriate standard I/O device
     if (connect_stdin)
     {
       ::close(stdin_pipe[1]);
       dup2(stdin_pipe[0],STDIN_FILENO);
     }
     if (connect_stdout)
     {
       ::close(stdout_pipe[0]);
       dup2(stdout_pipe[1],STDOUT_FILENO);
     }
     if (connect_stderr)
     {
       ::close(stderr_pipe[0]);
       dup2(stderr_pipe[1],STDERR_FILENO);
     }
     execve(path.c_str(), argv.argv(), env.envp());
     // will only ever get here if the exec() failed completely - *must* now exit the child process
     // by using errno, the parent has some chance of diagnosing the cause of the problem
     exit(errno);
   }
   break;
   default:  // in parent
   {
     // for each pipe, close the end of the duplicated pipe that is being used by the child
     // and connect the parent's end of the pipe to the class members so that they are visible to the parent() callback
     if (connect_stdin)
     {
       ::close(stdin_pipe[0]);
       child_in = stdin_pipe[1];
     }
     if (connect_stdout)
     {
       ::close(stdout_pipe[1]);
       child_out = stdout_pipe[0];
     }
     if (connect_stderr)
     {
       ::close(stderr_pipe[1]);
       child_err = stderr_pipe[0];
     }
     // call the user's callback
     if (!callback())
     {
       result = false;
       kill();
     }
     // close the pipes and wait for the child to finish
     // wait exits on a signal which may be the child signalling its exit or may be an interrupt
     close_stdin();
     close_stdout();
     close_stderr();
     int wait_status = 0;
     for (;;)
     {
       int wait_ret_val = waitpid(pid, &wait_status, 0);
       if (wait_ret_val != -1 || errno != EINTR) break;
     }
     // establish whether an error occurred
     if (WIFSIGNALED(wait_status))
     {
       // set_error(errno);
       status = WTERMSIG(wait_status);
       result = false;
     }
     else if (WIFEXITED(wait_status))
     {
       status = WEXITSTATUS(wait_status);
       if (status != 0)
         result = false;
     }
     pid = -1;
   }
   break;
   }
   return result;
 }
bool subprocess::spawn (const std::string & command_line, bool connect_stdin = false, bool connect_stdout = false, bool connect_stderr = false)
Definition at line 1066 of file subprocesses.cpp.
References arg_vector::argv0(), path_lookup(), arg_vector::size(), and spawn().
 {
   arg_vector arguments = command_line;
   if (arguments.size() == 0) return false;
   std::string path = path_lookup(arguments.argv0());
   if (path.empty()) return false;
   return spawn(path, arguments, connect_stdin, connect_stdout, connect_stderr);
 }
int subprocess::write_stdin (std::string & buffer)
Definition at line 1136 of file subprocesses.cpp.
References itext::bytes(), child_in, close_stdin(), and err.
 {
   if (child_in == -1) return -1;
   // do a blocking write of the whole buffer
   int bytes = write(child_in, buffer.c_str(), buffer.size());
   if (bytes == -1)
   {
     err = errno;
     close_stdin();
     return -1;
   }
   // now discard that part of the buffer that was written
   if (bytes > 0)
     buffer.erase(0, bytes);
   return bytes;
 }
Member Data Documentation
int subprocess::child_err private
Definition at line 169 of file subprocesses.hpp.
Referenced by close_stderr(), read_stderr(), spawn(), and subprocess().
int subprocess::child_in private
Definition at line 167 of file subprocesses.hpp.
Referenced by close_stdin(), spawn(), subprocess(), and write_stdin().
int subprocess::child_out private
Definition at line 168 of file subprocesses.hpp.
Referenced by close_stdout(), read_stdout(), spawn(), and subprocess().
env_vector subprocess::env private
Definition at line 170 of file subprocesses.hpp.
int subprocess::err private
Definition at line 171 of file subprocesses.hpp.
Referenced by error(), error_number(), error_text(), kill(), read_stderr(), read_stdout(), spawn(), subprocess(), and write_stdin().
int subprocess::pid private
Definition at line 166 of file subprocesses.hpp.
Referenced by kill(), spawn(), subprocess(), and ~subprocess().
int subprocess::status private
Definition at line 172 of file subprocesses.hpp.
Referenced by exit_status(), spawn(), and subprocess().
The documentation for this class was generated from the following files:
include/stlplus/subprocesses.hpp
include/stlplus/subprocesses.cpp