Visible: rcGraphicsSegmentIteratorImpl Class Reference
rcGraphicsSegmentIteratorImpl Class Reference
Public Member Functions
rcGraphicsSegmentIteratorImpl (rcGraphicsTrackImpl *track, const rcTimestamp &position, rcMutex &mutex)
virtual rcTimestamp getSegmentLength (void)
virtual rcTimestamp getSegmentOffset (void)
virtual rcTimestamp getTrackOffset (void)
virtual int32 getSegmentIndex (void)
virtual rcTimestamp getSegmentStart (void)
virtual rcTimestamp getSegmentStartAbsolute (void)
virtual bool hasNextSegment (bool lock)
virtual uint32 getSegmentCount (void)
virtual bool contains (const rcTimestamp &time)
virtual void lock ()
virtual void unlock ()
virtual void reset (bool lock)
virtual void release (void)
virtual rcRect getFocus (void)
virtual void advance (const rcTimestamp &amount, bool lock)
virtual bool advance (int32 offset, bool lock)
virtual rcVisualGraphicsCollection getValue (void)
virtual uint32 getCount (void)
Public Member Functions inherited from rcGraphicsSegmentIterator
virtual ~rcGraphicsSegmentIterator ()
Public Member Functions inherited from rcSegmentIterator
virtual ~rcSegmentIterator ()
Private Member Functions
virtual void setCurrentValue (void)
Private Attributes
rcSegmentIteratorImpl _iter
rcGraphicsTrackImpl * _track
rcVisualGraphicsCollection _currentValue
Detailed Description
Definition at line 10 of file rc_graphicstrackimpl.cpp.
Constructor & Destructor Documentation
rcGraphicsSegmentIteratorImpl::rcGraphicsSegmentIteratorImpl (rcGraphicsTrackImpl * track, const rcTimestamp & position, rcMutex & mutex) inline
Definition at line 13 of file rc_graphicstrackimpl.cpp.
References _iter, lock(), rcSegmentIteratorImpl::mutex(), rmAssert, and setCurrentValue().
                                                   : _iter( track, position, mutex ),
                                                     _track( track )
     {
         rcLock lock( _iter.mutex() );
         rmAssert( track );
         setCurrentValue();
     }
Member Function Documentation
virtual void rcGraphicsSegmentIteratorImpl::advance (const rcTimestamp & amount, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 115 of file rc_graphicstrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             } else {
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             }
         }
virtual bool rcGraphicsSegmentIteratorImpl::advance (int32 offset, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 128 of file rc_graphicstrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 bool result = _iter.advanceNoLock( offset );
                 setCurrentValue();
                 return result;
             } else {
                 bool result = _iter.advanceNoLock( offset );
                 setCurrentValue();
                 return result;
             }
         }
virtual bool rcGraphicsSegmentIteratorImpl::contains (const rcTimestamp & time) inline virtual
Implements rcSegmentIterator.
Definition at line 74 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::contains().
         {
             return _iter.contains( time );
         }
virtual uint32 rcGraphicsSegmentIteratorImpl::getCount (void) inline virtual
Implements rcGraphicsSegmentIterator.
Definition at line 151 of file rc_graphicstrackimpl.cpp.
References _currentValue, and rcVisualGraphicsCollection::size().
         {
             return _currentValue.size();
         }
virtual rcRect rcGraphicsSegmentIteratorImpl::getFocus (void) inline virtual
Implements rcSegmentIterator.
Definition at line 109 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getFocus().
         {
             return _iter.getFocus();
         }
virtual uint32 rcGraphicsSegmentIteratorImpl::getSegmentCount (void) inline virtual
Implements rcSegmentIterator.
Definition at line 68 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentCount().
         {
             return _iter.getSegmentCount();
         }
virtual int32 rcGraphicsSegmentIteratorImpl::getSegmentIndex (void) inline virtual
Implements rcSegmentIterator.
Definition at line 44 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentIndex().
         {
             return _iter.getSegmentIndex();
         }
virtual rcTimestamp rcGraphicsSegmentIteratorImpl::getSegmentLength (void) inline virtual
Implements rcSegmentIterator.
Definition at line 26 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentLength().
         {
             return _iter.getSegmentLength();
         }
virtual rcTimestamp rcGraphicsSegmentIteratorImpl::getSegmentOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 32 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentOffset().
         {
             return _iter.getSegmentOffset();
         }
virtual rcTimestamp rcGraphicsSegmentIteratorImpl::getSegmentStart (void) inline virtual
Implements rcSegmentIterator.
Definition at line 50 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStart().
         {
             return _iter.getSegmentStart();
         }
virtual rcTimestamp rcGraphicsSegmentIteratorImpl::getSegmentStartAbsolute (void) inline virtual
Implements rcSegmentIterator.
Definition at line 56 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStartAbsolute().
         {
             return _iter.getSegmentStartAbsolute();
         }
virtual rcTimestamp rcGraphicsSegmentIteratorImpl::getTrackOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 38 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getTrackOffset().
         {
             return _iter.getTrackOffset();
         }
virtual rcVisualGraphicsCollection rcGraphicsSegmentIteratorImpl::getValue (void) inline virtual
Implements rcGraphicsSegmentIterator.
Definition at line 145 of file rc_graphicstrackimpl.cpp.
References _currentValue.
         {
             return _currentValue;
         }
virtual bool rcGraphicsSegmentIteratorImpl::hasNextSegment (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 62 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::hasNextSegment().
         {
             return _iter.hasNextSegment( lock );
         }
virtual void rcGraphicsSegmentIteratorImpl::lock () inline virtual
Implements rcSegmentIterator.
Definition at line 80 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::lock().
Referenced by advance(), and rcGraphicsSegmentIteratorImpl().
         {
             _iter.lock();
         }
virtual void rcGraphicsSegmentIteratorImpl::release (void) inline virtual
Implements rcSegmentIterator.
Definition at line 103 of file rc_graphicstrackimpl.cpp.
         {
             delete this;
         }
virtual void rcGraphicsSegmentIteratorImpl::reset (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 92 of file rc_graphicstrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::lock(), rcSegmentIteratorImpl::reset(), setCurrentValue(), and rcSegmentIteratorImpl::unlock().
         {
             if ( lock )
                 _iter.lock();
             _iter.reset( false );
             setCurrentValue();
             if ( lock )
                 _iter.unlock();
         }
virtual void rcGraphicsSegmentIteratorImpl::setCurrentValue (void) inline private virtual
Definition at line 158 of file rc_graphicstrackimpl.cpp.
References _currentValue, _iter, rcGraphicsTrackImpl::_segments, _track, rcSegmentIteratorImpl::getSegmentIndex(), and rcGraphicsTrackImpl::segments().
Referenced by advance(), rcGraphicsSegmentIteratorImpl(), and reset().
         {
             int32 index = _iter.getSegmentIndex();
             if ( index >= 0 && static_cast<uint32>(index) < _track->segments() )
                 _currentValue = _track->_segments[index].mValue;
             else
                 _currentValue = rcVisualGraphicsCollection();
         }
virtual void rcGraphicsSegmentIteratorImpl::unlock () inline virtual
Implements rcSegmentIterator.
Definition at line 86 of file rc_graphicstrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::unlock().
         {
             _iter.unlock();
         }
Member Data Documentation
rcVisualGraphicsCollection rcGraphicsSegmentIteratorImpl::_currentValue private
Definition at line 169 of file rc_graphicstrackimpl.cpp.
Referenced by getCount(), getValue(), and setCurrentValue().
rcSegmentIteratorImpl rcGraphicsSegmentIteratorImpl::_iter private
Definition at line 167 of file rc_graphicstrackimpl.cpp.
Referenced by advance(), contains(), getFocus(), getSegmentCount(), getSegmentIndex(), getSegmentLength(), getSegmentOffset(), getSegmentStart(), getSegmentStartAbsolute(), getTrackOffset(), hasNextSegment(), lock(), rcGraphicsSegmentIteratorImpl(), reset(), setCurrentValue(), and unlock().
rcGraphicsTrackImpl* rcGraphicsSegmentIteratorImpl::_track private
Definition at line 168 of file rc_graphicstrackimpl.cpp.
Referenced by setCurrentValue().
The documentation for this class was generated from the following file:
src/visible/src/rc_graphicstrackimpl.cpp