Visible: rcScalarWriter Class Reference
rcScalarWriter Class Reference abstract
#include <include/visiCore/rc_engine.h>
Public Member Functions
virtual ~rcScalarWriter ()
virtual void setExpectedMinValue (const double &minValue)=0
virtual void setExpectedMaxValue (const double &maxValue)=0
virtual void writeValue (const rcTimestamp &timestamp, const rcRect &focus, const double &value)=0
virtual void flush (void)=0
virtual void reset ()=0
virtual rcWriter * down_cast ()=0
Detailed Description
Definition at line 405 of file rc_engine.h.
Constructor & Destructor Documentation
virtual rcScalarWriter::~rcScalarWriter () inline virtual
Definition at line 409 of file rc_engine.h.
 { };
Member Function Documentation
virtual rcWriter* rcScalarWriter::down_cast () pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::entropyTracker(), rcEngineImpl::entropyTrackerWindow(), rcCellWriterGroup::rcCellWriterGroup(), and rcEngineFocusData::rcEngineFocusData().
virtual void rcScalarWriter::flush (void) pure virtual
Implemented in rcScalarTrackImpl.
virtual void rcScalarWriter::reset () pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcEngineImpl::resumePreview().
virtual void rcScalarWriter::setExpectedMaxValue (const double & maxValue) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcWriterManager::createScalarWriter(), rcEngineImpl::muscleTracker(), and rcNativeImporter::parseTrack().
virtual void rcScalarWriter::setExpectedMinValue (const double & minValue) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcWriterManager::createScalarWriter(), and rcNativeImporter::parseTrack().
virtual void rcScalarWriter::writeValue (const rcTimestamp & timestamp, const rcRect & focus, const double & value) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcEngineImpl::entropyTrackerWindow(), rcNativeImporter::parseValue(), rcEngineImpl::processCapturedData(), rcEngineFocusData::writeFocusData(), rcEngineImpl::writeTimedFloats(), rcEngineImpl::writeTimedScalar(), and rcCellWriterGroup::writeValues().
The documentation for this class was generated from the following file:
include/visiCore/rc_engine.h