Visible: rcScalarTrackWidget Class Reference
rcScalarTrackWidget Class Reference
#include <include/visUI/rc_scalartrackwidget.h>
Public Slots
void setEnabled (bool isEnabled)
void updateElapsedTime (const rcTimestamp &time)
void updateCursorTime (const rcTimestamp &time)
void updateState (rcExperimentState state)
void updateDisplay (void)
void updateSettings (void)
Public Member Functions
rcScalarTrackWidget (QWidget *parent, int trackGroupNo, int trackNo)
~rcScalarTrackWidget ()
Protected Member Functions
void mousePressEvent (QMouseEvent *mouseEvent)
void mouseReleaseEvent (QMouseEvent *mouseEvent)
void mouseMoveEvent (QMouseEvent *mouseEvent)
void keyPressEvent (QKeyEvent *keyEvent)
void keyReleaseEvent (QKeyEvent *keyEvent)
Private Member Functions
void updateTrackDisplay (void)
Private Attributes
int _trackGroupNo
int _trackNo
QCheckBox * _checkbox
QLabel * _legend
QLabel * _name
QLabel * _value
rcTimestamp _elapsedTime
rcTimestamp _cursorTime
rcTimestamp _currentTime
Detailed Description
Definition at line 17 of file rc_scalartrackwidget.h.
Constructor & Destructor Documentation
rcScalarTrackWidget::rcScalarTrackWidget (QWidget * parent, int trackGroupNo, int trackNo)
Definition at line 30 of file rc_scalartrackwidget.cpp.
References _checkbox, _legend, _name, _trackGroupNo, _trackNo, _value, cUINoBreakAlignment, cUIWordBreakAlignment, rcTrack::getDescription(), rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrack::getName(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), rcTrackManager::getTrackPen(), rcTrackManager::isHiliteTrack(), rcTrackManager::isTrackEnabled(), setEnabled(), updateCursorTime(), updateDisplay(), updateElapsedTime(), updateSettings(), and updateState().
     : QWidget( parent , "trackWidget" )
 {
     // Gets (keyboard) focus by mouse clicking
     setFocusPolicy( Qt::ClickFocus);
     _trackGroupNo = trackGroupNo;
     _trackNo = trackNo;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackGroup* trackGroup = experiment->getTrackGroup( _trackGroupNo );
     rcTrack* track = trackGroup->getTrack( _trackNo );
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     bool hilited = tmp->isHiliteTrack( _trackGroupNo , _trackNo );
     Q3BoxLayout* layout = new Q3HBoxLayout( this );
     _checkbox = new QCheckBox( this );
     // retain old enablement information
     if ( tmp->isTrackEnabled( _trackGroupNo , _trackNo ) )
         _checkbox->setChecked( true );
     else
         _checkbox->setChecked( false );
     QToolTip::add( _checkbox , "Show/hide track" );
     layout->addWidget( _checkbox );
     // Simulate graph line with a colored character
     _legend = new QLabel( "-" , this );
     _legend->setAlignment( cUINoBreakAlignment );
     _legend->setFrameStyle( Q3Frame::Panel );
     _legend->setFrameShadow( Q3Frame::Sunken );
     _legend->setFixedWidth( 25 );
     // Set the color to reflect graph color
     _legend->setPaletteForegroundColor( tmp->getTrackPen( _trackGroupNo , _trackNo ).color() );
     // Set big bold "graph" font for better visibility
     QFont font;
     font.setWeight( QFont::Black );
     font.setPointSize( 28 );
     _legend->setFont( font );
     layout->addWidget( _legend );
     // Name/value font
     QFont textFont;
     textFont.setPointSize( 10 );
     if ( hilited )
         textFont.setWeight( QFont::Bold );
     else
         textFont.setWeight( QFont::Normal );
     // Track name
     _name = new QLabel( track->getName() , this );
     _name->setAlignment( cUIWordBreakAlignment );
     _name->setFrameStyle( Q3Frame::Panel );
     _name->setFrameShadow( Q3Frame::Sunken );
     _name->setFixedWidth( 80 );
     _name->setFont( textFont );
     layout->addWidget( _name );
     // Track value
     _value = new QLabel( "N/A" , this );
     _value->setAlignment( cUINoBreakAlignment );
     //_value->setAlignment( cUIWordBreakAlignment );
     _value->setFrameStyle( Q3Frame::Panel );
     _value->setFrameShadow( Q3Frame::Sunken );
     _value->setFixedWidth( 80 );
     _value->setFont( textFont );
     layout->addWidget( _value );
     layout->addSpacing( 10 );
     layout->addStretch();
     // use the track description as a tool tip
     QToolTip::add( _name , track->getDescription() );
     // connect the checkbox signal
     connect( _checkbox , SIGNAL( toggled( bool ) ) ,
              this      , SLOT( setEnabled( bool ) ) );
     // connect to some domain signals
     connect( domain , SIGNAL( elapsedTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateElapsedTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( cursorTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateCursorTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateDisplay( void ) ) ,
              this   , SLOT( updateDisplay( void ) ) );
     connect( domain , SIGNAL( updateSettings( void ) ) ,
              this   , SLOT( updateSettings( void ) ) );
 }
rcScalarTrackWidget::~rcScalarTrackWidget ()
Definition at line 123 of file rc_scalartrackwidget.cpp.
References _checkbox, _name, and _value.
 {
     QToolTip::remove( _name );
     QToolTip::remove( _value );
     QToolTip::remove( _checkbox );
 }
Member Function Documentation
void rcScalarTrackWidget::keyPressEvent (QKeyEvent * keyEvent) protected
Definition at line 234 of file rc_scalartrackwidget.cpp.
References _trackGroupNo, rcTrackManager::copyTrackToClipboard(), rcTrackManager::eMathematica, rcTrackManager::getHiliteTrack(), rcTrackManager::getTrackManager(), rcModifierKeys::isCtrlDown(), and rcTrackManager::setHiliteTrack().
 {
     int key = keyEvent->key();
     bool cmdKeyDown = rcModifierKeys::isCtrlDown( keyEvent );
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     switch ( key ) {
         case Qt::Key_Escape:
             // Reset highlighting
             tmp->setHiliteTrack( _trackGroupNo , -1 );
             break;
         case Qt::Key_C:
             if ( cmdKeyDown ) {
                 // Copy track contents to clipboard
                 tmp->copyTrackToClipboard( tmp->getHiliteTrack() );
             }
             break;
         case Qt::Key_M:
             if ( cmdKeyDown ) {
                 // Copy track contents to clipboard
           tmp->copyTrackToClipboard( tmp->getHiliteTrack(), rcTrackManager::eMathematica );
             }
             break;
     }
 }
void rcScalarTrackWidget::keyReleaseEvent (QKeyEvent * keyEvent) protected
Definition at line 263 of file rc_scalartrackwidget.cpp.
 {
     keyEvent->ignore();
 }
void rcScalarTrackWidget::mouseMoveEvent (QMouseEvent * mouseEvent) protected
Definition at line 224 of file rc_scalartrackwidget.cpp.
References rmUnused.
 {
     rmUnused( mouseEvent );
 }
void rcScalarTrackWidget::mousePressEvent (QMouseEvent * mouseEvent) protected
Definition at line 197 of file rc_scalartrackwidget.cpp.
References _trackGroupNo, _trackNo, eScalarTrack, rcTrack::getAnalysisRect(), rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), rcTrack::getTrackType(), rcRectangle< T >::height(), rcTrackManager::isTrackEnabled(), rcModelDomain::notifyAnalysisRect(), rcModelDomain::notifyUpdateDisplay(), rmUnused, rcTrackManager::setHiliteTrack(), and rcRectangle< T >::width().
 {
     rmUnused( mouseEvent );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackGroup* trackGroup = experiment->getTrackGroup( _trackGroupNo );
     rcTrack* track = trackGroup->getTrack( _trackNo );
     if ( track->getTrackType() == eScalarTrack ) {
         // Grab keyboard focus
         setFocus();
         // Highlight this track
         rcTrackManager* tmp = rcTrackManager::getTrackManager();
         // Only enabled tracks can be highlighted
         if ( tmp->isTrackEnabled( _trackGroupNo , _trackNo ) ) {
             tmp->setHiliteTrack( _trackGroupNo , -1 );
             tmp->setHiliteTrack( _trackGroupNo , _trackNo );
             // Change current analysis rect to track analysis rect
             rcRect focusRect = track->getAnalysisRect();
             if ( focusRect.width() && focusRect.height() )
                 domain->notifyAnalysisRect( focusRect );
             domain->notifyUpdateDisplay();
         }
     }
 }
void rcScalarTrackWidget::mouseReleaseEvent (QMouseEvent * mouseEvent) protected
Definition at line 229 of file rc_scalartrackwidget.cpp.
References rmUnused.
 {
     rmUnused( mouseEvent );
 }
void rcScalarTrackWidget::setEnabled (bool isEnabled) slot
Definition at line 131 of file rc_scalartrackwidget.cpp.
References _trackGroupNo, _trackNo, eGroupSemanticsGlobalGraphics, rcModelDomain::getModelDomain(), rcTrackManager::getTrackInfo(), rcTrackManager::getTrackManager(), rcTrackManager::groupType(), rcTrackManager::monitorableTrack(), rcModelDomain::notifySettingChange(), rcModelDomain::notifyUpdateMonitor(), rcTrackManager::setTrackEnabled(), rcTrackManager::setTrackGroupEnabled(), and rcTrackInfo::track().
Referenced by rcScalarTrackWidget().
 {
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     tmp->setTrackEnabled( _trackGroupNo , _trackNo , isEnabled );
     // Enable the group, too
     if ( isEnabled )
         tmp->setTrackGroupEnabled( _trackGroupNo , isEnabled );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->notifySettingChange();
     // Enabling graphics groups can affect video monitor
     if ( tmp->groupType( _trackGroupNo ) == eGroupSemanticsGlobalGraphics )
         domain->notifyUpdateMonitor();
     else {
         // Enabling some tracks can affect video monitor
         rcTrackInfo info = tmp->getTrackInfo( _trackGroupNo , _trackNo );
         if ( tmp->monitorableTrack( info.track() ) )
              domain->notifyUpdateMonitor();
     }
 }
void rcScalarTrackWidget::updateCursorTime (const rcTimestamp & time) slot
Definition at line 159 of file rc_scalartrackwidget.cpp.
References _cursorTime, and updateTrackDisplay().
Referenced by rcScalarTrackWidget().
 {
     _cursorTime = time;
     updateTrackDisplay();
 }
void rcScalarTrackWidget::updateDisplay (void) slot
Definition at line 170 of file rc_scalartrackwidget.cpp.
References updateTrackDisplay().
Referenced by rcScalarTrackWidget().
 {
     updateTrackDisplay();
 }
void rcScalarTrackWidget::updateElapsedTime (const rcTimestamp & time) slot
Definition at line 152 of file rc_scalartrackwidget.cpp.
References _elapsedTime, and updateTrackDisplay().
Referenced by rcScalarTrackWidget().
 {
     _elapsedTime = time;
     updateTrackDisplay();
 }
void rcScalarTrackWidget::updateSettings (void) slot
Definition at line 175 of file rc_scalartrackwidget.cpp.
References _checkbox, _trackGroupNo, _trackNo, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getNTrackGroups(), rcTrackManager::getTrackManager(), rcTrackManager::isTrackEnabled(), and updateTrackDisplay().
Referenced by rcScalarTrackWidget().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     int groupCount = experiment->getNTrackGroups();
     if ( groupCount ) {
         rcTrackManager* tmp = rcTrackManager::getTrackManager();
         if ( tmp->isTrackEnabled( _trackGroupNo , _trackNo ) )
             _checkbox->setChecked( true );
         else
             _checkbox->setChecked( false );
         updateTrackDisplay();
     } else {
         // No groups available
         // Do nothing because we are about to be destructed soon
     }
 }
void rcScalarTrackWidget::updateState (rcExperimentState state) slot
Definition at line 165 of file rc_scalartrackwidget.cpp.
References rmUnused.
Referenced by rcScalarTrackWidget().
 {
     rmUnused( state );
 }
void rcScalarTrackWidget::updateTrackDisplay (void) private
Definition at line 271 of file rc_scalartrackwidget.cpp.
References _currentTime, _cursorTime, _elapsedTime, _name, _trackGroupNo, _trackNo, _value, rcSegmentIterator::advance(), cCursorTimeCurrent, rcSegmentIterator::contains(), cZeroTime, eGraphicsTrack, eGroupSemanticsGlobalMeasurements, ePositionTrack, eScalarTrack, eVideoTrack, rcGraphicsSegmentIterator::getCount(), rcScalarTrack::getDataSegmentIterator(), rcVideoTrack::getDataSegmentIterator(), rcGraphicsTrack::getDataSegmentIterator(), rcPositionTrack::getDataSegmentIterator(), rcTrack::getDisplayFormatString(), rcModelDomain::getExperiment(), rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcExperiment::getNTrackGroups(), rcSegmentIterator::getSegmentIndex(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), rcTrack::getTrackType(), rcTrackGroup::getType(), rcScalarSegmentIterator::getValue(), rcPositionSegmentIterator::getValue(), rcTrackManager::isHiliteTrack(), rcTrackManager::isTrackEnabled(), rcExperimentAttributes::liveInput, rmAssert, rmDim, rcPair< T >::x(), and rcPair< T >::y().
Referenced by updateCursorTime(), updateDisplay(), updateElapsedTime(), and updateSettings().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     // In camera mode we can only see the last value
     if ( domain->getExperimentAttributes().liveInput )
         _cursorTime = cCursorTimeCurrent;
     // determine the time to display
     rcTimestamp timeToDisplay = _cursorTime;
     if (_cursorTime < cZeroTime)
         timeToDisplay = _elapsedTime;
     // if we don't have a valid time we can skip out now.
     if ( timeToDisplay < cZeroTime )
         return;
     rcExperiment* experiment = domain->getExperiment();
     int nTrackGroups = experiment->getNTrackGroups();
     if ( nTrackGroups > _trackGroupNo ) {
         rcTrackManager* tmp = rcTrackManager::getTrackManager();
         if ( tmp->isTrackEnabled( _trackGroupNo , _trackNo ) ) {
             // Show current values only for enabled tracks
             rcTrackGroup* trackGroup = experiment->getTrackGroup( _trackGroupNo );
         const int32 semantic = trackGroup->getType();
             rcTrack* track = trackGroup->getTrack( _trackNo );
             if ( track ) {
                 rcTrackType type = track->getTrackType();
                 rcSegmentIterator* iter = 0;
                 if ( type == eScalarTrack ) {
                     // get the scalar track.
                     rcScalarTrack* scalarTrack = dynamic_cast<rcScalarTrack*>( track );
                     if (scalarTrack == 0)
                         return;
                     // get the scalar value at the time to display
                     iter = scalarTrack->getDataSegmentIterator( timeToDisplay );
                 } else if ( type == eVideoTrack ) {
                     // get the video track
                     rcVideoTrack* videoTrack = dynamic_cast<rcVideoTrack*>( track );
                     if (videoTrack == 0)
                         return;
                     iter = videoTrack->getDataSegmentIterator( timeToDisplay );
                 } else if ( type == eGraphicsTrack ) {
                     // get the graphics track.
                     rcGraphicsTrack* graphicsTrack = dynamic_cast<rcGraphicsTrack*>( track );
                     if (graphicsTrack == 0)
                         return;
                     // get the value at the time to display
                     iter = graphicsTrack->getDataSegmentIterator( timeToDisplay );
                 } else if ( type == ePositionTrack ) {
                     // get the position track.
                     rcPositionTrack* pTrack = dynamic_cast<rcPositionTrack*>( track );
                     if (pTrack == 0) {
                         rmAssert( 0 );
                         return;
                     }
                     // get the value at the time to display
                     iter = pTrack->getDataSegmentIterator( timeToDisplay );
                 } else {
                     rmAssert( 0 );
                 }
                 if ( iter ) {
                     char valueBuf[ 128 ];
                     bool hasValue = iter->contains( timeToDisplay );
                     // Trying to get the very last value?
                     if ( !hasValue && _cursorTime == cCursorTimeCurrent ) {
                         // The very last value may not be available yet so go back one segment
                         iter->advance( -1 );
                         if ( iter->getSegmentIndex() != -1 )
                             hasValue = true;
                     }
                     if ( hasValue ) {
                         // timeToDisplay is within the segment
                         if ( type == eScalarTrack ) {
                             rcScalarSegmentIterator* si = dynamic_cast<rcScalarSegmentIterator*>(iter);
                 double value = si->getValue();
                 if ( semantic == eGroupSemanticsGlobalMeasurements)
                   value = log (value);
                             snprintf( valueBuf , rmDim(valueBuf),
                                       track->getDisplayFormatString(), value );
                         } else if ( type == eVideoTrack ) {
                             int idx = iter->getSegmentIndex();
                             snprintf( valueBuf , rmDim(valueBuf), "Frame " );
                             int len = strlen( valueBuf );
                             snprintf( valueBuf + len , rmDim(valueBuf)-len,
                                       track->getDisplayFormatString(), idx );
                         } else if ( type == eGraphicsTrack ) {
                             rcGraphicsSegmentIterator* gi = dynamic_cast<rcGraphicsSegmentIterator*>(iter);
                             uint32 graphicCount = gi->getCount();
                             snprintf( valueBuf, rmDim(valueBuf),
                                       track->getDisplayFormatString(), graphicCount );
                         } else if ( type == ePositionTrack ) {
                             rcPositionSegmentIterator* pi = dynamic_cast<rcPositionSegmentIterator*>(iter);
                             rcFPair value = pi->getValue();
                             snprintf( valueBuf, rmDim(valueBuf),
                                       track->getDisplayFormatString(), value.x(), value.y() );
                         }
                     } else {
                         // timeToDisplay is either before track start or after track end
                         snprintf( valueBuf , rmDim(valueBuf), "Undefined" );
                     }
                     _value->setText( valueBuf );
                     // Add tool tip to show the value, too
                     QToolTip::remove( _value );
                     QToolTip::add( _value , valueBuf );
                     //cerr << *iter;
                     delete iter;
                 }
             }
         } else {
             // Value not available
             _value->setText( "N/A" );
             // Add tool tip to show the value, too
             QToolTip::remove( _value );
             QToolTip::add( _value , "N/A" );
         }
         QFont textFont = _value->font();
         bool hilited = tmp->isHiliteTrack( _trackGroupNo , _trackNo );
 #if 1
         if ( hilited ) {
             textFont.setWeight( QFont::Bold );
         } else {
             textFont.setWeight( QFont::Normal );
         }
 #else
         if ( hilited ) {
             textFont.setUnderline( true );
         } else {
             textFont.setUnderline( false );
         }
 #endif
         _value->setFont( textFont );
         _name->setFont( textFont );
     }
     _currentTime = timeToDisplay;
 }
Member Data Documentation
QCheckBox* rcScalarTrackWidget::_checkbox private
Definition at line 48 of file rc_scalartrackwidget.h.
Referenced by rcScalarTrackWidget(), updateSettings(), and ~rcScalarTrackWidget().
rcTimestamp rcScalarTrackWidget::_currentTime private
Definition at line 54 of file rc_scalartrackwidget.h.
Referenced by updateTrackDisplay().
rcTimestamp rcScalarTrackWidget::_cursorTime private
Definition at line 53 of file rc_scalartrackwidget.h.
Referenced by updateCursorTime(), and updateTrackDisplay().
rcTimestamp rcScalarTrackWidget::_elapsedTime private
Definition at line 52 of file rc_scalartrackwidget.h.
Referenced by updateElapsedTime(), and updateTrackDisplay().
QLabel* rcScalarTrackWidget::_legend private
Definition at line 49 of file rc_scalartrackwidget.h.
Referenced by rcScalarTrackWidget().
QLabel* rcScalarTrackWidget::_name private
Definition at line 50 of file rc_scalartrackwidget.h.
Referenced by rcScalarTrackWidget(), updateTrackDisplay(), and ~rcScalarTrackWidget().
int rcScalarTrackWidget::_trackGroupNo private
Definition at line 46 of file rc_scalartrackwidget.h.
Referenced by keyPressEvent(), mousePressEvent(), rcScalarTrackWidget(), setEnabled(), updateSettings(), and updateTrackDisplay().
int rcScalarTrackWidget::_trackNo private
Definition at line 47 of file rc_scalartrackwidget.h.
Referenced by mousePressEvent(), rcScalarTrackWidget(), setEnabled(), updateSettings(), and updateTrackDisplay().
QLabel* rcScalarTrackWidget::_value private
Definition at line 51 of file rc_scalartrackwidget.h.
Referenced by rcScalarTrackWidget(), updateTrackDisplay(), and ~rcScalarTrackWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_scalartrackwidget.h
src/visible/qt/rc_scalartrackwidget.cpp