Visible: dump_context Class Reference
dump_context Class Reference
#include <include/stlplus/persistent.hpp>
Public Types
typedef void(* dump_callback)(dump_context &, const void *)
typedef std::pair< unsigned
short, dump_callback > callback_data
typedef void(* installer)(dump_context &)
Public Member Functions
dump_context (const otext &device, unsigned char version=PersistentVersion) throw (persistent_dump_failed)
~dump_context (void)
void put (unsigned char data) throw (persistent_dump_failed)
const otext & device (void) const
unsigned char version (void) const
bool little_endian (void) const
std::pair< bool, unsigned > pointer_map (const void *const pointer)
unsigned short register_type (const std::type_info &info, dump_callback)
bool is_callback (const std::type_info &info) const
callback_data lookup_type (const std::type_info &) const throw (persistent_illegal_type)
unsigned short register_interface (const std::type_info &info)
bool is_interface (const std::type_info &info) const
unsigned short lookup_interface (const std::type_info &) const throw (persistent_illegal_type)
void register_all (installer)
Private Member Functions
dump_context (const dump_context &)
dump_context & operator= (const dump_context &)
Private Attributes
dump_context_body * m_body
Friends
class dump_context_body
Detailed Description
Definition at line 70 of file persistent.hpp.
Member Typedef Documentation
typedef std::pair<unsigned short,dump_callback> dump_context::callback_data
Definition at line 78 of file persistent.hpp.
typedef void(* dump_context::dump_callback)(dump_context &, const void *)
Definition at line 76 of file persistent.hpp.
typedef void(* dump_context::installer)(dump_context &)
Definition at line 81 of file persistent.hpp.
Constructor & Destructor Documentation
dump_context::dump_context (const otext & device, unsigned char version = PersistentVersion) throw (persistent_dump_failed)
Definition at line 178 of file persistent.cpp.
References version().
                                                                                                    :
   m_body(0)
 {
   m_body = new dump_context_body(device,version);
 }
dump_context::~dump_context (void)
Definition at line 184 of file persistent.cpp.
References m_body.
 {
   delete m_body;
 }
dump_context::dump_context (const dump_context &) private
Member Function Documentation
const otext & dump_context::device (void) const
Definition at line 195 of file persistent.cpp.
References DEBUG_ASSERT, dump_context_body::device(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->device();
 }
bool dump_context::is_callback (const std::type_info & info) const
Definition at line 225 of file persistent.cpp.
References DEBUG_ASSERT, dump_context_body::is_callback(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->is_callback(info);
 }
bool dump_context::is_interface (const std::type_info & info) const
Definition at line 243 of file persistent.cpp.
References DEBUG_ASSERT, dump_context_body::is_interface(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->is_interface(info);
 }
bool dump_context::little_endian (void) const
Definition at line 207 of file persistent.cpp.
References DEBUG_ASSERT, dump_context_body::little_endian(), and m_body.
 {
   DEBUG_ASSERT(m_body);
   return m_body->little_endian();
 }
unsigned short dump_context::lookup_interface (const std::type_info & info) const throw (persistent_illegal_type)
Definition at line 249 of file persistent.cpp.
References DEBUG_ASSERT.
 {
   DEBUG_ASSERT(m_body);
   return m_body->lookup_interface(info);
 }
dump_context::callback_data dump_context::lookup_type (const std::type_info & info) const throw (persistent_illegal_type)
Definition at line 231 of file persistent.cpp.
References DEBUG_ASSERT.
 {
   DEBUG_ASSERT(m_body);
   return m_body->lookup_type(info);
 }
dump_context& dump_context::operator= (const dump_context &) private
std::pair< bool, unsigned > dump_context::pointer_map (const void *const pointer)
Definition at line 213 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and dump_context_body::pointer_map().
 {
   DEBUG_ASSERT(m_body);
   return m_body->pointer_map(pointer);
 }
void dump_context::put (unsigned char data) throw (persistent_dump_failed)
Definition at line 189 of file persistent.cpp.
References DEBUG_ASSERT.
 {
   DEBUG_ASSERT(m_body);
   m_body->put(data);
 }
void dump_context::register_all (dump_context::installer installer)
Definition at line 255 of file persistent.cpp.
References DEBUG_ASSERT, and m_body.
 {
   DEBUG_ASSERT(m_body);
   if (installer) installer(*this);
 }
unsigned short dump_context::register_interface (const std::type_info & info)
Definition at line 237 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and dump_context_body::register_interface().
 {
   DEBUG_ASSERT(m_body);
   return m_body->register_interface(info);
 }
unsigned short dump_context::register_type (const std::type_info & info, dump_context::dump_callback callback)
Definition at line 219 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and dump_context_body::register_type().
 {
   DEBUG_ASSERT(m_body);
   return m_body->register_type(info,callback);
 }
unsigned char dump_context::version (void) const
Definition at line 201 of file persistent.cpp.
References DEBUG_ASSERT, m_body, and dump_context_body::version().
 {
   DEBUG_ASSERT(m_body);
   return m_body->version();
 }
Friends And Related Function Documentation
friend class dump_context_body friend
Definition at line 119 of file persistent.hpp.
Member Data Documentation
dump_context_body* dump_context::m_body private
Definition at line 120 of file persistent.hpp.
Referenced by device(), is_callback(), is_interface(), little_endian(), pointer_map(), register_all(), register_interface(), register_type(), version(), and ~dump_context().
The documentation for this class was generated from the following files:
include/stlplus/persistent.hpp
include/stlplus/persistent.cpp