Visible: rcThread Class Reference
rcThread Class Reference
#include <include/util/rc_thread.h>
Classes
struct state_t
Public Member Functions
rcThread (rcRunnable *runnable)
virtual ~rcThread (void)
void setPriority (rcThreadPriority pri)
rcThreadPriority getPriority (void)
void start (void)
bool isRunning (void)
void checkException (void)
virtual void run (void)
virtual int join (bool seppuku=true)
Public Member Functions inherited from rcRunnable
rcRunnable ()
virtual ~rcRunnable ()
void requestSeppuku ()
void clearSeppuku ()
Static Public Member Functions
static void sleep (long msec)
Protected Member Functions
rcThread (void)
Protected Member Functions inherited from rcRunnable
bool seppukuRequested ()
Private Attributes
state_t * _state
Detailed Description
Definition at line 62 of file rc_thread.h.
Constructor & Destructor Documentation
rcThread::rcThread (rcRunnable * runnable)
Definition at line 180 of file rc_thread_mac.cpp.
References _runnable, and _state.
 {
     _state = new state_t;
     _runnable = runnable;
 }
rcThread::~rcThread (void) virtual
Definition at line 186 of file rc_thread_mac.cpp.
References _running, and _state.
 {
     if (_running)
         throw general_exception( "deleting running thread" );
     delete _state;
 }
rcThread::rcThread (void) protected
Definition at line 173 of file rc_thread_mac.cpp.
References _runnable, and _state.
 {
     _state = new state_t;
     _runnable = this;
 }
Member Function Documentation
void rcThread::checkException (void)
Definition at line 307 of file rc_thread_mac.cpp.
References _died, and _error.
Referenced by start().
 {
     if (_died)
         throw general_exception( _error.c_str() );
 }
rcThreadPriority rcThread::getPriority (void)
Definition at line 203 of file rc_thread_mac.cpp.
References _priority.
Referenced by start().
 {
     return _priority;
 }
bool rcThread::isRunning (void)
Definition at line 301 of file rc_thread_mac.cpp.
References _running.
Referenced by rcEngineImpl::process(), rcEngineImpl::reset(), rcEngineImpl::setSettingValue(), rcEngineImpl::shutdown(), and rcEngineImpl::start().
 {
     return _running;
 }
int rcThread::join (bool seppuku = true) virtual
Definition at line 328 of file rc_thread_mac.cpp.
References _died, _runnable, _running, _threadId, and rmAssert.
Referenced by rcEngineMovieCapture::killSaveThread(), rcEngineImpl::process(), rcEngineImpl::reset(), rcEngineImpl::setSettingValue(), rcEngineImpl::shutdown(), rcEngineImpl::start(), and rcVideoCache::~rcVideoCache().
 {
     int ret = 0;
     int retVal;
     if (_threadId) {
       if (seppuku)
     _runnable->requestSeppuku();
       ret = pthread_join(_threadId, (void**)&retVal);
       if (seppuku)
     _runnable->clearSeppuku();
       _running = false;
       _died = retVal ? true : false;
     }
     rmAssert(!_running);
     return ret;
 }
void rcThread::run (void) virtual
Implements rcRunnable.
Reimplemented in rcVideoCache::rcVideoCachePrefetchUnit.
Definition at line 314 of file rc_thread_mac.cpp.
References _runnable.
 {
     if (_runnable != 0)
         _runnable->run();
 }
void rcThread::setPriority (rcThreadPriority pri)
Definition at line 194 of file rc_thread_mac.cpp.
References _priority, eMaxPriority, and eMinPriority.
Referenced by rcEngineImpl::initialize(), and rcEngineMovieCapture::startSaveThread().
 {
   if ((pri < eMinPriority) || (pri > eMaxPriority))
     throw general_exception( "New priority invalid" );
   _priority = pri;
 }
void rcThread::sleep (long msec) static
Definition at line 348 of file rc_thread_mac.cpp.
Referenced by rcEngineMoviePlayback::run().
 {
     usleep( msec * 1000 );
 }
void rcThread::start (void)
Definition at line 212 of file rc_thread_mac.cpp.
References _died, _running, _state, checkException(), eNormalPriority, getPriority(), rmDim, threadEntry(), and rcThread::state_t::threadId.
Referenced by rcEngineImpl::process(), rcVideoCache::rcVideoCache(), rcEngineImpl::reset(), rcEngineImpl::setSettingValue(), and rcEngineMovieCapture::startSaveThread().
 {
   if (_running)
     return;
   try
   {
     int pthread_err;
     char errMsg[100];
     pthread_attr_t attr;
     if ((pthread_err = pthread_attr_init(&attr)))
     {
       snprintf(errMsg, rmDim( errMsg ), "pthread_attr_init failed %d", pthread_err);
       throw general_exception( errMsg );
     }
 #ifdef REAL_TIME_SUPPORT
     if ((pthread_err = pthread_attr_setinheritsched(&attr, PTHREAD_EXPLICIT_SCHED)))
     {
       snprintf(errMsg, rmDim( errMsg ), "error setting inherit sched %d\n", pthread_err);
       throw general_exception( errMsg );
     }
     if ((pthread_err = pthread_attr_setschedpolicy(&attr, SCHED_RR)))
     {
       snprintf(errMsg, rmDim( errMsg ), "error setting sched policy %d\n", pthread_err);
       throw general_exception( errMsg );
     }
     if (getPriority() != eNormalPriority)
     {
       struct sched_param sched;
       if ((pthread_err = pthread_attr_getschedparam(&attr, &sched)))
       {
     snprintf(errMsg, rmDim( errMsg ), "pthread_attr_getschedparam failed %d", pthread_err);
     throw general_exception( errMsg );
       }
       sched.sched_priority += getPriority();
       if ((pthread_err = pthread_attr_setschedparam(&attr, &sched)))
       {
     snprintf(errMsg, rmDim( errMsg ), "pthread_attr_setschedparam failed %d", pthread_err);
     throw general_exception( errMsg );
       }
     }
 #endif
     if ((pthread_err = pthread_create( &_state->threadId, &attr, threadEntry,
                       _state)))
     {
       snprintf(errMsg, rmDim( errMsg ), "pthread_create failed %d", pthread_err);
       throw general_exception( errMsg );
     }
     _running = true;
     _died = false;
 #ifdef rcTHREAD_TIMEOUT_CHECK
     // Note: Even if enabled this check won't work correctly without
     // using locks or rcAtomicValue. The logic has been changed so
     // that neither of these are required, but the new logic doesn't
     // have the called thread set _running at all, so a new variable
     // would have to be added to get the desired effect.
     // wait for thread to become active
     int timeout = 200;
     while (!_running)
     {
       usleep( 1000 );
       checkException();
       if (--timeout < 0)
     throw general_exception( "timeout creating thread" );
     }
 #endif
   }
   catch (general_exception& x)
   {
     if ( _state->threadId )
       pthread_cancel( _state->threadId );
     throw x;
   } catch (exception& x)
   {
     throw x;
   }
 }
Member Data Documentation
state_t* rcThread::_state private
Definition at line 106 of file rc_thread.h.
Referenced by rcThread(), start(), and ~rcThread().
The documentation for this class was generated from the following files:
include/util/rc_thread.h
src/util/code/rc_thread_mac.cpp