Visible: rcCmdLine Class Reference
rcCmdLine Class Reference
#include <include/util/rc_parametermap.h>
Public Member Functions
int splitLine (int argc, char **argv)
bool hasSwitch (const char *pSwitch)
string getSafeArgument (const char *pSwitch, int iIdx, const char *pDefault)
string getArgument (const char *pSwitch, int iIdx)
int getArgumentCount (const char *pSwitch)
int32 atoi (string s)
Protected Member Functions
bool isSwitch (const char *pParam)
Detailed Description
Definition at line 126 of file rc_parametermap.h.
Member Function Documentation
int32 rcCmdLine::atoi (string s) inline
Definition at line 205 of file rc_parametermap.h.
Referenced by rcEngineImpl::setFromArgs().
    {
      return std::atoi (s.c_str());
    }
string rcCmdLine::getArgument (const char * pSwitch, int iIdx)
Definition at line 219 of file rc_parametermap.cpp.
References hasSwitch(), and rmAssert.
Referenced by getSafeArgument(), and rcEngineImpl::setFromArgs().
 {
   rmAssert (iIdx >= 0);
    if (hasSwitch(pSwitch))
    {
        rcCmdLine::iterator theIterator;
       theIterator = find(pSwitch);
        if (theIterator!=end())
       {
     if ((*theIterator).second.m_strings.size() > (uint32) (iIdx))
          {
             return (*theIterator).second.m_strings[iIdx];
          }
       }
    }
    throw (int)0;
    return "";
 }
int rcCmdLine::getArgumentCount (const char * pSwitch)
Definition at line 251 of file rc_parametermap.cpp.
References hasSwitch().
 {
    int iArgumentCount = -1;
    if (hasSwitch(pSwitch))
    {
        rcCmdLine::iterator theIterator;
       theIterator = find(pSwitch);
        if (theIterator!=end())
       {
          iArgumentCount = (*theIterator).second.m_strings.size();
       }
    }
    return iArgumentCount;
 }
string rcCmdLine::getSafeArgument (const char * pSwitch, int iIdx, const char * pDefault)
Definition at line 183 of file rc_parametermap.cpp.
References getArgument(), and NULL.
Referenced by rcEngineImpl::setFromArgs().
 {
    string sRet;
    if (pDefault!=NULL)
       sRet = pDefault;
    try
    {
       sRet = getArgument(pSwitch, iIdx);
    }
    catch (...)
    {
    }
    return sRet;
 }
bool rcCmdLine::hasSwitch (const char * pSwitch)
Definition at line 155 of file rc_parametermap.cpp.
Referenced by getArgument(), getArgumentCount(), and rcEngineImpl::setFromArgs().
 {
     rcCmdLine::iterator theIterator;
     theIterator = find(pSwitch);
     return (theIterator!=end());
 }
bool rcCmdLine::isSwitch (const char * pParam) protected
Definition at line 116 of file rc_parametermap.cpp.
References NULL.
Referenced by splitLine().
 {
    if (pParam==NULL)
       return false;
    // switches must non-empty
    // must have at least one character after the '-'
    int len = strlen(pParam);
    if (len <= 1)
    {
       return false;
    }
    // switches always start with '-'
    if (pParam[0]=='-')
    {
       // allow negative numbers as arguments.
       // ie., don't count them as switches
       return (!isdigit(pParam[1]));
    }
    else
    {
       return false;
    }
 }
int rcCmdLine::splitLine (int argc, char ** argv)
Definition at line 41 of file rc_parametermap.cpp.
References isSwitch(), rcCmdParam::m_strings, and value_type().
Referenced by rcEngineImpl::setFromArgs().
 {
    clear();
    string curParam; // current argv[x]
    // skip the exe name (start with i = 1)
    for (int i = 1; i < argc; i++)
    {
       // if it's a switch, start a new rcCmdLine
       if (isSwitch(argv[i]))
       {
          curParam = argv[i];
          string arg;
          // look at next input string to see if it's a switch or an argument
          if (i + 1 < argc)
          {
             if (!isSwitch(argv[i + 1]))
             {
                // it's an argument, not a switch
                arg = argv[i + 1];
                // skip to next
                i++;
             }
             else
             {
                arg = "";
             }
          }
          // add it
          rcCmdParam cmd;
          cmd.m_strings.push_back(arg);
          // add the rcCmdParam to 'this'
          pair<rcCmdLine::iterator, bool> res = insert(rcCmdLine::value_type(curParam, cmd));
       }
       else
       {
          // it's not a new switch, so it must be more stuff for the last switch
          // ...let's add it
           rcCmdLine::iterator theIterator;
          // get an iterator for the current param
          theIterator = find(curParam);
           if (theIterator!=end())
          {
             (*theIterator).second.m_strings.push_back(argv[i]);
          }
          else
          {
             // ??
          }
       }
    }
    return size();
 }
The documentation for this class was generated from the following files:
include/util/rc_parametermap.h
src/util/code/rc_parametermap.cpp