Visible: rcMovieFileFormat Class Reference
rcMovieFileFormat Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileFormat ()
rcMovieFileFormat (movieFormatRev rev)
rcMovieFileFormat (const rcSharedFrameBufPtr &frame, movieFormatRev rev=movieFormatInvalid)
bool write (FILE *saveStream) const
void fixEndian ()
const uint32 & width () const
const uint32 & height () const
const uint32 & rowUpdate () const
const double & averageFrameRate () const
const uint32 & frameCount () const
const int64 & baseTime () const
movieFormatRev rev () const
const char * magic () const
uint32 bytesInFrame () const
void rowUpdate (const uint32 &f)
void averageFrameRate (const double &f)
void frameCount (const uint32 &f)
void baseTime (const int64 &t)
Private Attributes
rcMovieFileIdentifier mId
uint32 mWidth
uint32 mHeight
uint32 mRowUpdate
double mAverageFrameRate
uint32 mFrameCount
int64 mBaseTime
Detailed Description
Definition at line 104 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileFormat::rcMovieFileFormat ()
Definition at line 99 of file rc_moviefileformat.cpp.
                                      :
         mId(movieFormatInvalid), mWidth(0), mHeight(0), mRowUpdate(0),
         mAverageFrameRate(0.0), mFrameCount(0), mBaseTime(0)
 {
}
rcMovieFileFormat::rcMovieFileFormat (movieFormatRev rev)
Definition at line 105 of file rc_moviefileformat.cpp.
                                                        :
         mId(r), mWidth(0), mHeight(0), mRowUpdate(0),
         mAverageFrameRate(0.0), mFrameCount(0), mBaseTime(0)
 {
}
rcMovieFileFormat::rcMovieFileFormat (const rcSharedFrameBufPtr & frame, movieFormatRev rev = movieFormatInvalid)
Definition at line 111 of file rc_moviefileformat.cpp.
                                                          :
         mId(r), mWidth(frame->width()), mHeight(frame->height()),
         mRowUpdate(frame->rowUpdate()),
         mAverageFrameRate(0.0), mFrameCount(0), mBaseTime(frame->timestamp()._timestamp)
 {
}
Member Function Documentation
const double& rcMovieFileFormat::averageFrameRate () const inline
Definition at line 122 of file rc_moviefileformat.h.
References mAverageFrameRate.
Referenced by rcGenMovieFile::flush(), rcVideoCache::headerLoadRev0(), and operator<<().
 { return mAverageFrameRate; }
void rcMovieFileFormat::averageFrameRate (const double & f) inline
Definition at line 131 of file rc_moviefileformat.h.
References mAverageFrameRate.
 { mAverageFrameRate = f; }
const int64& rcMovieFileFormat::baseTime () const inline
Definition at line 124 of file rc_moviefileformat.h.
References mBaseTime.
Referenced by rcVideoCache::headerLoadRev0(), rcGenMovieFile::initHeader(), and operator<<().
 { return mBaseTime; }
void rcMovieFileFormat::baseTime (const int64 & t) inline
Definition at line 133 of file rc_moviefileformat.h.
References mBaseTime.
 { mBaseTime = t; }
uint32 rcMovieFileFormat::bytesInFrame () const inline
Definition at line 127 of file rc_moviefileformat.h.
References height(), and rowUpdate().
Referenced by rcVideoCache::headerLoadRev0().
 { return height() * rowUpdate(); }
void rcMovieFileFormat::fixEndian ()
Definition at line 137 of file rc_moviefileformat.cpp.
References ByteSwapN, eByteOrderBigEndian, rcMovieFileIdentifier::fixEndian(), mAverageFrameRate, mBaseTime, mFrameCount, mHeight, mId, mRowUpdate, mWidth, and rfPlatformByteOrder().
Referenced by rcVideoCache::headerLoadRev0(), and write().
 {
     // Header is always stored in big endian form
     if ( rfPlatformByteOrder() != eByteOrderBigEndian )
 {
     ByteSwapN (mWidth);
     ByteSwapN (mHeight);
     ByteSwapN (mRowUpdate);
     ByteSwapN (mAverageFrameRate);
     /* Values to allow proper navigation through the rest of the file.
      */
     ByteSwapN (mFrameCount);
     ByteSwapN (mBaseTime);
     mId.fixEndian ();  // Common to all formats
 }
 }
const uint32& rcMovieFileFormat::frameCount () const inline
Definition at line 123 of file rc_moviefileformat.h.
References mFrameCount.
Referenced by rcGenMovieFile::flush(), rcVideoCache::headerLoadRev0(), and operator<<().
 { return mFrameCount; }
void rcMovieFileFormat::frameCount (const uint32 & f) inline
Definition at line 132 of file rc_moviefileformat.h.
References mFrameCount.
 { mFrameCount = f; }
const uint32& rcMovieFileFormat::height () const inline
Definition at line 120 of file rc_moviefileformat.h.
References mHeight.
Referenced by rcGenMovieFile::addFrame(), bytesInFrame(), rcGenMovieFile::frameSize(), rcVideoCache::headerLoadRev0(), and operator<<().
 { return mHeight; }
const char* rcMovieFileFormat::magic () const inline
Definition at line 126 of file rc_moviefileformat.h.
References rcMovieFileIdentifier::magic(), and mId.
 { return mId.magic(); }
movieFormatRev rcMovieFileFormat::rev () const inline
Definition at line 125 of file rc_moviefileformat.h.
References mId, and rcMovieFileIdentifier::rev().
Referenced by operator<<().
 { return mId.rev(); }
const uint32& rcMovieFileFormat::rowUpdate () const inline
Definition at line 121 of file rc_moviefileformat.h.
References mRowUpdate.
Referenced by bytesInFrame(), rcVideoCache::headerLoadRev0(), rcGenMovieFile::initHeader(), and operator<<().
 { return mRowUpdate; }
void rcMovieFileFormat::rowUpdate (const uint32 & f) inline
Definition at line 130 of file rc_moviefileformat.h.
References mRowUpdate.
 { mRowUpdate = f; }
const uint32& rcMovieFileFormat::width () const inline
Definition at line 119 of file rc_moviefileformat.h.
References mWidth.
Referenced by rcGenMovieFile::addFrame(), rcGenMovieFile::frameSize(), rcVideoCache::headerLoadRev0(), and operator<<().
 { return mWidth; }
bool rcMovieFileFormat::write (FILE * saveStream) const
Definition at line 120 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), and rfPlatformByteOrder().
Referenced by rcGenMovieFile::flush(), and rcGenMovieFile::open().
 {
     // We write in BigEndian format
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
     const_cast<rcMovieFileFormat *>(this)->fixEndian ();
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("MovieHdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
Member Data Documentation
double rcMovieFileFormat::mAverageFrameRate private
Definition at line 144 of file rc_moviefileformat.h.
Referenced by averageFrameRate(), and fixEndian().
int64 rcMovieFileFormat::mBaseTime private
Definition at line 149 of file rc_moviefileformat.h.
Referenced by baseTime(), and fixEndian().
uint32 rcMovieFileFormat::mFrameCount private
Definition at line 148 of file rc_moviefileformat.h.
Referenced by fixEndian(), and frameCount().
uint32 rcMovieFileFormat::mHeight private
Definition at line 142 of file rc_moviefileformat.h.
Referenced by fixEndian(), and height().
rcMovieFileIdentifier rcMovieFileFormat::mId private
Definition at line 136 of file rc_moviefileformat.h.
Referenced by fixEndian(), magic(), and rev().
uint32 rcMovieFileFormat::mRowUpdate private
Definition at line 143 of file rc_moviefileformat.h.
Referenced by fixEndian(), and rowUpdate().
uint32 rcMovieFileFormat::mWidth private
Definition at line 141 of file rc_moviefileformat.h.
Referenced by fixEndian(), and width().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp