Visible: rcVideoCaptureCtrl Class Reference
rcVideoCaptureCtrl Class Reference
#include <include/visiCore/rc_captureregs.h>
Public Member Functions
rcVideoCaptureCtrl ()
void decimationRate (uint32 decimationRate)
void slidingWindowSize (int slidingWindowSize)
void slidingWindowOrigin (rcAnalyzerResultOrigin slidingWindowOrigin)
void slidingWindowEnabled (bool slidingWindowEnabled)
void ACIEnabled (bool ACIEnabled)
void entropyDefinition (rcSimilarator::rcEntropyDefinition eDef)
void gain (int32 g)
void shutter (int32 g)
void binning (int32 g)
Public Member Functions inherited from rcVideoCaptureCtrlReader
rcVideoCaptureCtrlReader ()
virtual ~rcVideoCaptureCtrlReader ()
uint32 getDecimationRate (void) const
int getSlidingWindowSize () const
rcAnalyzerResultOrigin getSlidingWindowOrigin () const
bool getSlidingWindowEnabled () const
bool getACIEnabled () const
rcSimilarator::rcEntropyDefinition getEntropyDefinition () const
int32 getGain (void) const
int32 getShutter (void) const
int32 getBinning (void) const
Additional Inherited Members
Protected Attributes inherited from rcVideoCaptureCtrlReader
rcAtomicValue< uint32 > _decRate
rcAtomicValue< int > _slidingWindowSize
rcAtomicValue
< rcAnalyzerResultOrigin > _slidingWindowOrigin
rcAtomicValue< bool > _slidingWindowEnabled
rcAtomicValue< bool > _ACIEnabled
rcAtomicValue
< rcSimilarator::rcEntropyDefinition > _entropyDefinition
rcAtomicValue< int32 > _gain
rcAtomicValue< int32 > _shutter
rcAtomicValue< int32 > _binning
Detailed Description
Definition at line 76 of file rc_captureregs.h.
Constructor & Destructor Documentation
rcVideoCaptureCtrl::rcVideoCaptureCtrl () inline
Definition at line 79 of file rc_captureregs.h.
                        : rcVideoCaptureCtrlReader()
   { }
Member Function Documentation
void rcVideoCaptureCtrl::ACIEnabled (bool ACIEnabled) inline
Definition at line 95 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_ACIEnabled, and rcAtomicValue< T >::setValue().
   { _ACIEnabled.setValue(ACIEnabled); }
void rcVideoCaptureCtrl::binning (int32 g) inline
Definition at line 107 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_binning, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::initializeCamera(), rcEngineImpl::setSettingValue(), and rcEngineMovieCapture::updateCameraSettings().
   { _binning.setValue(g); }
void rcVideoCaptureCtrl::decimationRate (uint32 decimationRate) inline
Definition at line 82 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_decRate, and rcAtomicValue< T >::setValue().
Referenced by rcEngineImpl::setSettingValue().
   { _decRate.setValue(decimationRate); }
void rcVideoCaptureCtrl::entropyDefinition (rcSimilarator::rcEntropyDefinition eDef) inline
Definition at line 98 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_entropyDefinition, and rcAtomicValue< T >::setValue().
   {  _entropyDefinition.setValue(eDef); }
void rcVideoCaptureCtrl::gain (int32 g) inline
Definition at line 101 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_gain, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::initializeCamera(), rcEngineImpl::setSettingValue(), and rcEngineMovieCapture::updateCameraSettings().
   { _gain.setValue(g); }
void rcVideoCaptureCtrl::shutter (int32 g) inline
Definition at line 104 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_shutter, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::initializeCamera(), rcEngineImpl::setSettingValue(), and rcEngineMovieCapture::updateCameraSettings().
   { _shutter.setValue(g); }
void rcVideoCaptureCtrl::slidingWindowEnabled (bool slidingWindowEnabled) inline
Definition at line 92 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_slidingWindowEnabled, and rcAtomicValue< T >::setValue().
   { _slidingWindowEnabled.setValue(slidingWindowEnabled); }
void rcVideoCaptureCtrl::slidingWindowOrigin (rcAnalyzerResultOrigin slidingWindowOrigin) inline
Definition at line 89 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_slidingWindowOrigin, and rcAtomicValue< T >::setValue().
Referenced by rcEngineImpl::setSettingValue().
   { _slidingWindowOrigin.setValue(slidingWindowOrigin); }
void rcVideoCaptureCtrl::slidingWindowSize (int slidingWindowSize) inline
Definition at line 85 of file rc_captureregs.h.
References rcVideoCaptureCtrlReader::_slidingWindowSize, and rcAtomicValue< T >::setValue().
Referenced by rcEngineImpl::setSettingValue().
   { if ( slidingWindowSize < 1 ) slidingWindowSize = 1;
       _slidingWindowSize.setValue(slidingWindowSize); }
The documentation for this class was generated from the following file:
include/visiCore/rc_captureregs.h