Visible: rc2dVector< T > Class Template Reference
rc2dVector< T > Class Template Reference
#include <include/util/rc_vector2d.h>
Public Member Functions
rc2dVector ()
rc2dVector (T x, T y)
rc2dVector (T r, rcRadian t)
rc2dVector (const rcDPair &p)
rc2dVector (const rcIPair &p)
rc2dVector (const rcFPair &p)
T x () const
T y () const
void x (T newX)
void y (T newY)
T len () const
T l2 () const
bool isNull () const
bool isLenNull () const
T & operator[] (int d)
T operator[] (int d) const
T * Ref () const
rc2dVector< T > perpendicular () const
rc2dVector< T > unit () const
rc2dVector< T > project (const rc2dVector< T > &) const
T distance (const rc2dVector< T > &) const
T distanceSquared (const rc2dVector< T > &) const
rcRadian angle () const
rc2dVector< T > operator+ (const rc2dVector< T > &) const
rc2dVector< T > operator+ (const rcPair< T > &) const
rc2dVector< T > & operator+= (const rc2dVector< T > &)
rc2dVector< T > & operator+= (const rcPair< T > &)
rc2dVector< T > operator- () const
rc2dVector< T > operator- (const rc2dVector< T > &) const
rc2dVector< T > operator- (const rcPair< T > &) const
rc2dVector< T > & operator-= (const rc2dVector< T > &)
rc2dVector< T > & operator-= (const rcPair< T > &)
rc2dVector< T > operator* (T d) const
rc2dVector< T > & operator*= (T)
T operator* (const rc2dVector< T > &) const
T dot (const rc2dVector< T > &) const
T cross (const rc2dVector< T > &) const
rc2dVector< T > operator/ (T d) const
rc2dVector< T > & operator/= (T)
bool operator== (const rc2dVector< T > &) const
bool operator!= (const rc2dVector< T > &) const
bool operator< (const rc2dVector< T > &rhs) const
Private Attributes
T mX [2]
Friends
ostream & operator<< (ostream &ous, const rc2dVector< T > &vec)
Detailed Description
template<class T>
class rc2dVector< T >
Definition at line 66 of file rc_vector2d.h.
Constructor & Destructor Documentation
template<class T> rc2dVector< T >::rc2dVector () inline
Definition at line 71 of file rc_vector2d.h.
 {mX[0] = 0.;         mX[1] = 0.; }
template<class T> rc2dVector< T >::rc2dVector (T x, T y) inline
Definition at line 72 of file rc_vector2d.h.
 {mX[0] = x ;         mX[1] = y; }
template<class T> rc2dVector< T >::rc2dVector (T r, rcRadian t) inline
Definition at line 73 of file rc_vector2d.h.
 {mX[0] = r * cos(t); mX[1] = r * sin(t);}
template<class T> rc2dVector< T >::rc2dVector (const rcDPair & p) inline
Definition at line 74 of file rc_vector2d.h.
 {mX[0] = p.x();      mX[1] = p.y();}
template<class T> rc2dVector< T >::rc2dVector (const rcIPair & p) inline
Definition at line 75 of file rc_vector2d.h.
 {mX[0] = p.x();      mX[1] = p.y();}
template<class T> rc2dVector< T >::rc2dVector (const rcFPair & p) inline
Definition at line 76 of file rc_vector2d.h.
 {mX[0] = p.x();      mX[1] = p.y();}
Member Function Documentation
template<class T > rcRadian rc2dVector< T >::angle () const inline
Definition at line 259 of file rc_vector2d.h.
References atan2(), and rmExceptionMacro.
Referenced by rcMotionPath::add(), rcInfLine::angle(), rcPolygon::discBuffer(), rcImageCanvasGL::draw(), rcPolygon::genMinEnclosingRect(), rcKinetoscope::preSegmentedBodies(), rcVisualFunction::rcVisualFunction(), rfMutualChannel(), rcLatticeSimilarator::ttc(), and rcVisualFunction::update().
 {
   if (isNull())
     {
       rmExceptionMacro(<<"Zero Length");
     }
   return rcRadian ((atan2 (double (y()), double (x()))));
 }
template<class T> T rc2dVector< T >::cross (const rc2dVector< T > & v) const inline
Definition at line 234 of file rc_vector2d.h.
References rc2dVector< T >::mX.
Referenced by rcPolygon::contains(), and thetaOrder< T >::operator()().
 { return mX[0] * v.mX[1] - mX[1] * v.mX[0]; }
template<class T> T rc2dVector< T >::distance (const rc2dVector< T > & v) const inline
Definition at line 173 of file rc_vector2d.h.
Referenced by rcEngineImpl::modelTracker(), rcVisualFunction::populationMigration(), rcAffineRectangle::rcAffineRectangle(), rfDrawCircle(), rfDrawCylinder(), and rfGenerateSmoothingPts().
 { return (*this - v).len(); }
template<class T> T rc2dVector< T >::distanceSquared (const rc2dVector< T > & v) const inline
Definition at line 230 of file rc_vector2d.h.
References rc2dVector< T >::mX, and rmSquare.
Referenced by rcImageCanvasGL::mouseReleaseEvent(), rfAssociate(), and rcLsFit< T >::rms().
 { return (rmSquare (mX[0] - v.mX[0]) + rmSquare (mX[1] - v.mX[1]));}
template<class T> T rc2dVector< T >::dot (const rc2dVector< T > & v) const inline
Definition at line 226 of file rc_vector2d.h.
Referenced by rcPolygon::convexComparedToConvex(), and rcPolygon::convexIntersection().
 { return *this * v; }
template<class T> bool rc2dVector< T >::isLenNull () const inline
Definition at line 90 of file rc_vector2d.h.
Referenced by rcFeature::rcFeature(), and rfMutualChannel().
 { return rfRealEq (len(), 0); }
template<class T> bool rc2dVector< T >::isNull (void) const inline
Definition at line 89 of file rc_vector2d.h.
Referenced by rcImageCanvasGL::draw(), rc2Xform::isIdentity(), rcMathematicalImage::mMakeField(), rcKinetoscope::preSegmentedBodies(), rcFeature::rcFeature(), rcVisualFunction::rcVisualFunction(), rcVisualFunction::speed(), rcLatticeSimilarator::ttc(), and rcVisualFunction::update().
 { return ((rfRealEq (mX[0], 0)) && (rfRealEq (mX[1], 0)));}
template<class T> T rc2dVector< T >::l2 () const inline
Definition at line 85 of file rc_vector2d.h.
Referenced by rcImageCanvasGL::findCellPositionTracks(), rcMathematicalImage::mMakeField(), rcMotionVectorPath::reconcile(), and rcLatticeSimilarator::ttc().
 { return ( mX[0] * mX[0] + mX[1] * mX[1]) ; }
template<class T> T rc2dVector< T >::len () const inline
Definition at line 84 of file rc_vector2d.h.
Referenced by rcPolygon::discBuffer(), rcImageCanvasGL::draw(), rcPolygon::findPeak(), rcPolygon::genMinEnclosingRect(), rcPolygon::genMinRectBounds(), thetaOrder< T >::operator()(), rcCameraSpecification::operator<(), rcPolygon::perimeter(), rcKinetoscope::preSegmentedBodies(), rcFeature::rcFeature(), rcVisualFunction::rcVisualFunction(), rfMutualChannel(), rcVisualFunction::speed(), and rcVisualFunction::update().
 { return sqrt( mX[0] * mX[0] + mX[1] * mX[1]) ; }
template<class T> bool rc2dVector< T >::operator!= (const rc2dVector< T > & v) const inline
Definition at line 254 of file rc_vector2d.h.
 { return !(*this == v); }
template<class T> rc2dVector< T > rc2dVector< T >::operator* (T d) const inline
Definition at line 213 of file rc_vector2d.h.
 { return rc2dVector<T>(mX[0] * d, mX[1] * d); }
template<class T> T rc2dVector< T >::operator* (const rc2dVector< T > & v) const inline
Definition at line 222 of file rc_vector2d.h.
References rc2dVector< T >::mX.
 { return (mX[0] * v.mX[0] + mX[1] * v.mX[1]); }
template<class T> rc2dVector< T > & rc2dVector< T >::operator*= (T d) inline
Definition at line 218 of file rc_vector2d.h.
 { return *this = *this * d; }
template<class T> rc2dVector< T > rc2dVector< T >::operator+ (const rc2dVector< T > & v) const inline
Definition at line 177 of file rc_vector2d.h.
References rc2dVector< T >::mX.
 { return rc2dVector<T> ( mX[0] + v.mX[0], mX[1] + v.mX[1]); }
template<class T> rc2dVector< T > rc2dVector< T >::operator+ (const rcPair< T > & v) const inline
Definition at line 181 of file rc_vector2d.h.
References rcPair< T >::x(), and rcPair< T >::y().
 { return rc2dVector<T> ( mX[0] + v.x(), mX[1] + v.y()); }
template<class T> rc2dVector< T > & rc2dVector< T >::operator+= (const rc2dVector< T > & v) inline
Definition at line 185 of file rc_vector2d.h.
 { return *this = *this + v; }
template<class T> rc2dVector< T > & rc2dVector< T >::operator+= (const rcPair< T > & v) inline
Definition at line 189 of file rc_vector2d.h.
 { return *this = *this + v; }
template<class T > rc2dVector< T > rc2dVector< T >::operator- (void) const inline
Definition at line 193 of file rc_vector2d.h.
 { return rc2dVector<T>(-mX[0], -mX[1]); }
template<class T> rc2dVector< T > rc2dVector< T >::operator- (const rc2dVector< T > & v) const inline
Definition at line 197 of file rc_vector2d.h.
References rc2dVector< T >::mX.
 { return rc2dVector<T>( mX[0] - v.mX[0], mX[1] - v.mX[1]); }
template<class T> rc2dVector< T > rc2dVector< T >::operator- (const rcPair< T > & v) const inline
Definition at line 201 of file rc_vector2d.h.
References rcPair< T >::x(), and rcPair< T >::y().
 { return rc2dVector<T>( mX[0] - v.x(), mX[1] - v.y()); }
template<class T> rc2dVector< T > & rc2dVector< T >::operator-= (const rc2dVector< T > & v) inline
Definition at line 205 of file rc_vector2d.h.
 { return *this = *this - v; }
template<class T> rc2dVector< T > & rc2dVector< T >::operator-= (const rcPair< T > & v) inline
Definition at line 209 of file rc_vector2d.h.
 { return *this = *this - v; }
template<class T> rc2dVector< T > rc2dVector< T >::operator/ (T d) const inline
Definition at line 238 of file rc_vector2d.h.
References rmExceptionMacro.
 {
   if (d == 0.0)
     rmExceptionMacro(<<"Zero Length");
   return *this * (1. / d);
  } // divide once
template<class T> rc2dVector< T > & rc2dVector< T >::operator/= (T d) inline
Definition at line 246 of file rc_vector2d.h.
 { return *this = *this / d; }
template<class T> bool rc2dVector< T >::operator< (const rc2dVector< T > & rhs) const
template<class T> bool rc2dVector< T >::operator== (const rc2dVector< T > & v) const inline
Definition at line 250 of file rc_vector2d.h.
References rc2dVector< T >::mX.
 { return ((mX[0] == v.mX[0]) && (mX[1] == v.mX[1])); }
template<class T> T& rc2dVector< T >::operator[] (int d) inline
Definition at line 93 of file rc_vector2d.h.
 {assert(d >= 0 && d < 2); return mX[d];}
template<class T> T rc2dVector< T >::operator[] (int d) const inline
Definition at line 94 of file rc_vector2d.h.
 {assert(d >= 0 && d < 2); return mX[d];}
template<class T> rc2dVector<T> rc2dVector< T >::perpendicular () const inline
Definition at line 97 of file rc_vector2d.h.
Referenced by LLSQ::rms_orth().
    {
      return rc2dVector<T>(-mX[1], mX[0]);
    }
template<class T> rc2dVector< T > rc2dVector< T >::project (const rc2dVector< T > & other) const inline
Definition at line 282 of file rc_vector2d.h.
 {
   return ((other * *this) / (*this * *this)) * *this;
 }
template<class T > T * rc2dVector< T >::Ref () const inline
Definition at line 276 of file rc_vector2d.h.
Referenced by rcVisualStyle::color(), and rcVisualStyle::rcVisualStyle().
 {
   return ((T*) mX);
 }
template<class T > rc2dVector< T > rc2dVector< T >::unit () const inline
Definition at line 269 of file rc_vector2d.h.
References rmAssertDebug.
Referenced by rcFeature::rcFeature(), LLSQ::rms_orth(), and rcInfLine::transform().
 {
   rmAssertDebug (!isLenNull());
   return *this / len();
 }
template<class T> T rc2dVector< T >::x () const inline
Definition at line 80 of file rc_vector2d.h.
Referenced by rcMotionPath::add(), rcMotionCenter::add(), rcImageCanvasGL::addDefaultText(), rcInfLine::angle(), rcPolygon::areaSign(), rcVisualFunction::beatProcess(), rcPolygon::between(), rcAffineRectangle::boundingBox(), rcEllipse::boundingOrthRectangle(), rcImageCanvasGL::buildImageDlist(), rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcMotionCenter::center(), rcPolygon::centerOf(), rcKinetoscope::connectedFunctions(), rcPolygon::contains(), rcImageCanvasGL::convertEvent(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcPolygon::crossing(), rcEllipse::degenerate(), rcImageCanvasGL::devToWorldCoord(), rcImageCanvasGL::devViewSize(), rcVisualFunction::dimensions(), rcVisualFunction::direct(), rcLineSegment< T >::distanceAlong(), rcLineSegment< T >::distanceFrom(), rcImageCanvasGL::draw(), rcImageCanvasGL::drawAffineRect(), drawCells(), rcImageCanvasGL::drawModelRect(), rcImageCanvasGL::drawRubberBandRect(), rcAffineRectangle::expand(), generateRandomMovie(), generateTinyMovie(), rcPolygon::genMinEnclosingRect(), rcPolygon::genMinRectBounds(), rcAffineWindow::genPixel(), rcAffineRectangle::getPixelLoc(), rcBaseMotionPath::iAnchor(), rcMotionVectorPath::iAnchor(), rcPolygon::insertVertex(), rcInfLine::intersect(), rcPolygon::intersection(), rc2Xform::invMapPoint(), rcInfLine::isParallel(), rcImageCanvasGL::keyPressEvent(), rcMathematicalImage::mMakeField(), rcImageCanvasGL::modelRotate(), rcImageCanvasGL::modelToWorldCoord(), rcEngineImpl::modelTracker(), rcImageCanvasGL::modelTransformCurrent(), rcImageCanvasGL::mousePanEvent(), rcImageCanvasGL::mouseReleaseEvent(), rcShape::needAffineRect(), rcShape::needCenterOfmass(), rcShape::needMedian(), offsetGraphics(), uniqueOrder< T >::operator()(), rc2Xform::operator*(), rcMatrix< 2 >::operator*(), rcMatrix_2d::operator*(), operator*(), rcImageCanvasGL::panCurrent(), parfit2DR3(), rcVisualFunction::populationMigration(), rcVisualFunction::predictedTolerance(), rcExporter::produceValue(), rcPolygon::pushUniqueVertex(), rcPolygon::pushVertex(), rcAffineRectangle::rcAffineRectangle(), rcDrawLine(), rcDrawPolygon(), rcFillPolygon(), rcInfLine::rcInfLine(), rcLineSegment< T >::rcLineSegment(), rcValue::rcValue(), rcVisualTarget::rcVisualTarget(), rcImageCanvasGL::reconvertImage(), rfAffineRectangleToSegmentsCollection(), rfAssociate(), rfDivisionReport(), rfPlot1Dsignal(), rfPolygonToSegmentsCollection(), LLSQ::rms_orth(), rcPolygon::segmentInter(), rcLsFit< T >::solve3p(), rcLsFit< T >::solvetp(), rcVisualTarget::speed(), rcImageCanvasGL::statusString(), rcInfLine::toPoint(), rc2Xform::trans(), rc2Xform::transf(), rcPolygon::translate(), rcVisualFunction::translation(), rcPolygon::triArea2(), rcEllipse::unit(), rcLsFit< T >::update(), rcVisualTarget::update(), rcVisualFunction::update(), rcKinetoscope::validate(), rcAffineWindow::vImageTransform(), rcKinetoscope::visualDebugGraphics(), rcVisualRect::width(), rcImageCanvasGL::worldPixelSize(), rcImageCanvasGL::worldToDevCoord(), rcImageCanvasGL::worldToPixel(), rcCellWriterGroup::writeValues(), and rcVisualRect::x().
 { return mX[0]; }
template<class T> void rc2dVector< T >::x (T newX) inline
Definition at line 82 of file rc_vector2d.h.
 { mX[0] = newX; }
template<class T> T rc2dVector< T >::y () const inline
Definition at line 81 of file rc_vector2d.h.
Referenced by rcMotionPath::add(), rcMotionCenter::add(), rcImageCanvasGL::addDefaultText(), rcInfLine::angle(), rcPolygon::areaSign(), rcPolygon::between(), rcAffineRectangle::boundingBox(), rcEllipse::boundingOrthRectangle(), rcImageCanvasGL::buildImageDlist(), rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcMotionCenter::center(), rcPolygon::centerOf(), rcPolygon::contains(), rcImageCanvasGL::convertEvent(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcPolygon::crossing(), rcEllipse::degenerate(), rcImageCanvasGL::devViewSize(), rcVisualFunction::dimensions(), rcVisualFunction::direct(), rcLineSegment< T >::distanceAlong(), rcLineSegment< T >::distanceFrom(), rcImageCanvasGL::draw(), rcImageCanvasGL::drawAffineRect(), drawCells(), rcImageCanvasGL::drawModelRect(), rcImageCanvasGL::drawRubberBandRect(), rcAffineRectangle::expand(), generateRandomMovie(), generateTinyMovie(), rcPolygon::genMinEnclosingRect(), rcPolygon::genMinRectBounds(), rcAffineWindow::genPixel(), rcAffineRectangle::getPixelLoc(), rcVisualRect::height(), rcBaseMotionPath::iAnchor(), rcMotionVectorPath::iAnchor(), rcPolygon::insertVertex(), rcInfLine::intersect(), rcPolygon::intersection(), rc2Xform::invMapPoint(), rcInfLine::isParallel(), rcImageCanvasGL::keyPressEvent(), rcVisualStyle::lineWidth(), rcMathematicalImage::mMakeField(), rcImageCanvasGL::modelRotate(), rcImageCanvasGL::modelToWorldCoord(), rcEngineImpl::modelTracker(), rcImageCanvasGL::modelTransformCurrent(), rcImageCanvasGL::mousePanEvent(), rcImageCanvasGL::mouseReleaseEvent(), rcShape::needAffineRect(), rcShape::needCenterOfmass(), rcShape::needMedian(), offsetGraphics(), uniqueOrder< T >::operator()(), rc2Xform::operator*(), rcMatrix< 2 >::operator*(), rcMatrix_2d::operator*(), operator*(), rcImageCanvasGL::panCurrent(), parfit2DR3(), rcVisualFunction::populationMigration(), rcVisualFunction::predictedTolerance(), rcExporter::produceValue(), rcPolygon::pushUniqueVertex(), rcPolygon::pushVertex(), rcAffineRectangle::rcAffineRectangle(), rcDrawLine(), rcDrawPolygon(), rcFillPolygon(), rcInfLine::rcInfLine(), rcLineSegment< T >::rcLineSegment(), rcValue::rcValue(), rcVisualTarget::rcVisualTarget(), rcImageCanvasGL::reconvertImage(), rfAffineRectangleToSegmentsCollection(), rfAssociate(), rfPlot1Dsignal(), rfPolygonToSegmentsCollection(), LLSQ::rms_orth(), rcPolygon::segmentInter(), rcLsFit< T >::solve3p(), rcLsFit< T >::solvetp(), rcVisualTarget::speed(), rcImageCanvasGL::statusString(), rcInfLine::toPoint(), rc2Xform::trans(), rc2Xform::transf(), rcPolygon::translate(), rcPolygon::triArea2(), rcEllipse::unit(), rcLsFit< T >::update(), rcVisualTarget::update(), rcVisualFunction::update(), rcKinetoscope::validate(), rcAffineWindow::vImageTransform(), rcKinetoscope::visualDebugGraphics(), rcImageCanvasGL::worldPixelSize(), rcImageCanvasGL::worldToDevCoord(), rcImageCanvasGL::worldToPixel(), rcCellWriterGroup::writeValues(), and rcVisualRect::y().
 { return mX[1]; }
template<class T> void rc2dVector< T >::y (T newY) inline
Definition at line 83 of file rc_vector2d.h.
 { mX[1] = newY; }
Friends And Related Function Documentation
template<class T> ostream& operator<< (ostream & ous, const rc2dVector< T > & vec) friend
Definition at line 159 of file rc_vector2d.h.
   {
     ous << "[" << vec.x() << "," << vec.y() << "]";
     return ous;
   }
Member Data Documentation
template<class T> T rc2dVector< T >::mX[2] private
Definition at line 166 of file rc_vector2d.h.
Referenced by rc2dVector< T >::cross(), rc2dVector< T >::distanceSquared(), rc2dVector< T >::operator*(), rc2dVector< T >::operator+(), rc2dVector< T >::operator-(), and rc2dVector< T >::operator==().
The documentation for this class was generated from the following file:
include/util/rc_vector2d.h