Visible: rcMovieConverterToQT Class Reference
rcMovieConverterToQT Class Reference
#include <include/visual/rc_movieconverter.h>
Public Member Functions
rcMovieConverterToQT (const rcMovieConverterOptionsQT &opt, rcCarbonLock *l=NULL, rcProgressIndicator *p=NULL)
virtual ~rcMovieConverterToQT ()
const rcMovieConverterOptionsQT & options () const
void options (const rcMovieConverterOptionsQT &o)
rcMovieConverterError convert (const std::string &inputFile, const std::string &outputFile)
Public Member Functions inherited from rcMovieConverter
rcMovieConverter (bool verbose=true, rcCarbonLock *l=NULL, rcProgressIndicator *p=NULL)
virtual ~rcMovieConverter ()
bool verbose () const
rcSharedFrameBufPtr clippedFrame (rcSharedFrameBufPtr orig, rcMovieConverterOptions opt)
void verbose (bool v)
Private Member Functions
rcMovieConverterError createQTMovie (rcVideoCache *inputCache, const std::string &outputFile)
void copyFrame (PixMapHandle myPixMap, rcSharedFrameBufPtr &frameBuf)
OSErr addVideoSamplesToMedia (Media theMedia, rcVideoCache &cache, uint32 firstIndex, uint32 frameCount, uint32 offset, uint32 period, const rcRect &movieSize)
Private Attributes
rcMovieConverterOptionsQT mOptions
Additional Inherited Members
Static Public Member Functions inherited from rcMovieConverter
static std::string getErrorString (const rcMovieConverterError &error)
static bool isReifyMovie (const std::string &name)
static bool isImageCollection (const std::string &name)
Protected Member Functions inherited from rcMovieConverter
void lock ()
void unlock ()
Protected Attributes inherited from rcMovieConverter
rcMovieConverterError mLastError
rcProgressIndicator * mProgress
bool mVerbose
rcCarbonLock * mCarbonLock
Detailed Description
Definition at line 165 of file rc_movieconverter.h.
Constructor & Destructor Documentation
rcMovieConverterToQT::rcMovieConverterToQT (const rcMovieConverterOptionsQT & opt, rcCarbonLock * l = NULL, rcProgressIndicator * p = NULL)
Definition at line 801 of file rc_movieconverter.cpp.
                                                                      :
         rcMovieConverter( opt.verbose(), l, p ),
         mOptions( opt )
 {
}
rcMovieConverterToQT::~rcMovieConverterToQT () virtual
Definition at line 809 of file rc_movieconverter.cpp.
 {
 }
Member Function Documentation
OSErr rcMovieConverterToQT::addVideoSamplesToMedia (Media theMedia, rcVideoCache & cache, uint32 firstIndex, uint32 frameCount, uint32 offset, uint32 period, const rcRect & movieSize) private
Definition at line 993 of file rc_movieconverter.cpp.
References cleanupAndReturn, rcMovieConverter::clippedFrame(), copyFrame(), endl(), eVideoCacheStatusOK, rcVideoCache::frameCount(), rcVideoCache::frameIndexToTimestamp(), rcVideoCache::getErrorString(), rcVideoCache::getFrame(), rcRectangle< T >::height(), kVideoTimeScale, rcMovieConverter::lock(), mOptions, rcMovieConverter::mProgress, NULL, NR::period(), rcProgressIndicator::progress(), quality, rcMovieConverterOptions::reversePixels(), rfReversePixels8(), rcTimestamp::secs(), rcMovieConverter::unlock(), and rcRectangle< T >::width().
Referenced by createQTMovie().
 {
     GWorldPtr       myGWorld = NULL;
     PixMapHandle    myPixMap = NULL;
     CodecType       myCodecType = kRawCodecType; // kJPEGCodecType;
     const CodecQ    quality = codecLosslessQuality;
     long            myMaxComprSize = 0L;
     Handle          myComprDataHdl = NULL;
     CTabHandle      ctabHdl = NULL;
     Ptr             myComprDataPtr = NULL;
     ImageDescriptionHandle myImageDesc = NULL;
     CGrafPtr        mySavedPort = NULL;
     GDHandle        mySavedDevice = NULL;
     Rect            myRect;
     OSErr           myErr = noErr;
     MacSetRect(&myRect, 0, 0, movieSize.width(), movieSize.height());
     ctabHdl = (CTabHandle)NewHandle(sizeof(ColorTable) +
                                     sizeof(ColorSpec)*256);
     if (ctabHdl == NULL) {
         myErr = -1;
         cleanupAndReturn;
     }
     HLockHi((Handle)ctabHdl);
     {
         (**ctabHdl).ctSeed = 0;
         (**ctabHdl).ctFlags = 0;
         (**ctabHdl).ctSize = 255;
         ColorSpec* ctPtr = (ColorSpec*)&((**ctabHdl).ctTable);
         for (int i = 0; i <= (**ctabHdl).ctSize; i++) {
             ctPtr->value = 0;
             unsigned short val =  (unsigned short)(i*257);
             ctPtr->rgb.red = ctPtr->rgb.blue = ctPtr->rgb.green = val;
             ctPtr++;
         }
     }
     lock();
     myErr = NewGWorld(&myGWorld, 8, &myRect, ctabHdl, NULL, (GWorldFlags)0);
     unlock();
     if (myErr != noErr)
         cleanupAndReturn;
     lock();
     myPixMap = GetGWorldPixMap(myGWorld);
     unlock();
     if (myPixMap == NULL) {
         myErr = -1;
         cleanupAndReturn;
     }
     lock();
     LockPixels(myPixMap);
     myErr = GetMaxCompressionSize(myPixMap,
                                   &myRect,
                                   40, // 8 bit grey scale
                                   quality,
                                   myCodecType,
                                   (CompressorComponent)bestFidelityCodec,
                                   &myMaxComprSize);
     unlock();
     if (myErr != noErr)
         cleanupAndReturn;
     myComprDataHdl = NewHandle(myMaxComprSize);
     if (myComprDataHdl == NULL) {
         myErr = -1;
         cleanupAndReturn;
     }
     HLockHi(myComprDataHdl);
     myComprDataPtr = *myComprDataHdl;
     myImageDesc = (ImageDescriptionHandle)NewHandle(4);
     if (myImageDesc == NULL) {
         myErr = -1;
         cleanupAndReturn;
     }
     lock();
     GetGWorld(&mySavedPort, &mySavedDevice);
     SetGWorld(myGWorld, NULL);
     TimeValue frameDuration = 0;
     uint32 endMark = offset + (firstIndex + frameCount)*period;
     uint32 converted = 0;
     bool repeat = true;
     unlock();
     for (uint32 i = offset + firstIndex*period; repeat; i += period) {
         if (i >= endMark) {
             repeat = false;
             if ( i >= cache.frameCount())
                 continue;
         }
         EraseRect(&myRect);
         rcSharedFrameBufPtr frameBuf;
         rcVideoCacheError error;
         rcVideoCacheStatus status = cache.getFrame(i, frameBuf, &error);
         if (status != eVideoCacheStatusOK) {
             cerr << "Couldn't read frame: " << i << " error: "
                  << rcVideoCache::getErrorString(error) << endl;
             myErr = -1;
             cleanupAndReturn;
         }
         frameBuf = clippedFrame( frameBuf, mOptions );
         if ( mOptions.reversePixels() ) {
             rcWindow w( frameBuf );
             rfReversePixels8( w );
         }
         lock();
         copyFrame(myPixMap, frameBuf);
         myErr = CompressImage(myPixMap,
                               &myRect,
                               quality,
                               myCodecType,
                               myImageDesc,
                               myComprDataPtr);
         unlock();
         if (myErr != noErr)
             cleanupAndReturn;
         rcTimestamp startTime, endTime;
         status = cache.frameIndexToTimestamp(i, startTime, &error);
         if (status != eVideoCacheStatusOK) {
             cerr << "Couldn't read start time: " << i << " error: "
                  << rcVideoCache::getErrorString(error) << endl;
             myErr = -1;
             cleanupAndReturn;
         }
         if ((i+period) < cache.frameCount()) {
             status = cache.frameIndexToTimestamp(i+period, endTime, &error);
             if (status != eVideoCacheStatusOK) {
                 cerr << "Couldn't read end time: " << i+period << " error: "
                      << rcVideoCache::getErrorString(error) << endl;
                 myErr = -1;
                 cleanupAndReturn;
             }
             endTime = endTime - startTime;
             frameDuration = (TimeValue)(endTime.secs() * kVideoTimeScale);
         }
         TimeValue sampleTime;
         lock();
         myErr = AddMediaSample(theMedia,
                                myComprDataHdl,
                                0,     // no offset in data
                                (**myImageDesc).dataSize,
                                frameDuration,
                                (SampleDescriptionHandle)myImageDesc,
                                1,    // one sample
                                0,    // self-contained samples
                                &sampleTime);
         unlock();
         ++converted;
         if ( mProgress )
             mProgress->progress( double(converted)/frameCount * 100.0 );
 #ifdef DEBUG
         fprintf(stderr, "  Adding frame %d, duration %ld, idepth %d  icid %d "
                 "psize %d ptype %d sampleTime %ld\n", i, frameDuration,
                 (**myImageDesc).depth, (**myImageDesc).clutID,
                 (**myPixMap).pixelSize, (**myPixMap).pixelType,
                 sampleTime);
 #endif
         if (myErr != noErr)
             cleanupAndReturn;
     }
     cleanupAndReturn;
 }
rcMovieConverterError rcMovieConverterToQT::convert (const std::string & inputFile, const std::string & outputFile) virtual
Implements rcMovieConverter.
Definition at line 814 of file rc_movieconverter.cpp.
References cVideoCacheMem, cVideoCacheSize, eMovieConverterErrorOpen, eMovieConverterErrorUnknown, eMovieConverterErrorUnsupported, endl(), rcVideoCache::getErrorString(), rcVideoCache::getFatalError(), rcMovieConverter::isReifyMovie(), rcVideoCache::isValid(), rcMovieConverter::mLastError, rcVideoCache::rcVideoCacheCtor(), rcVideoCache::rcVideoCacheDtor(), and rcMovieConverter::verbose().
Referenced by rcExperimentImpl::exportMovie(), and rfConvertMovie().
 {
     mLastError = eMovieConverterErrorUnknown;
     bool srcReify = isReifyMovie( inputFile );
     if ( srcReify ) {
         rcVideoCache* cacheP = 0;
         cacheP = rcVideoCache::rcVideoCacheCtor( inputFile, cVideoCacheSize, false, false, false, cVideoCacheMem );
         if (!cacheP->isValid()) {
             if ( verbose() )
                 cerr << rcVideoCache::getErrorString( cacheP->getFatalError() ) << endl;
             mLastError = eMovieConverterErrorOpen;
         } else {
             mLastError = eMovieConverterErrorUnsupported;
                 //            mLastError = createQTMovie( cacheP, outputFile );
         }
         rcVideoCache::rcVideoCacheDtor( cacheP );
     } else {
         mLastError = eMovieConverterErrorUnsupported;
     }
     return mLastError;
 }
void rcMovieConverterToQT::copyFrame (PixMapHandle myPixMap, rcSharedFrameBufPtr & frameBuf) private
Definition at line 1177 of file rc_movieconverter.cpp.
References rcFrame::height(), rmAssert, rcFrame::rowPointer(), and rcFrame::width().
Referenced by addVideoSamplesToMedia().
 {
     rmAssert(myPixMap);
     int32 width = (**myPixMap).bounds.right - (**myPixMap).bounds.left;
     int32 height = (**myPixMap).bounds.bottom - (**myPixMap).bounds.top;
     uint8* rowPtr = (uint8 *)GetPixBaseAddr(myPixMap);
     int32 rowUpdate = QTGetPixMapHandleRowBytes(myPixMap);
     rmAssert(frameBuf->width() == width);
     rmAssert(frameBuf->height() == height);
     rmAssert(width <= rowUpdate);
     for (int32 curLine = 0; curLine < height; curLine++) {
         memmove(rowPtr, frameBuf->rowPointer(curLine), width);
         rowPtr += rowUpdate;
     }
 }
rcMovieConverterError rcMovieConverterToQT::createQTMovie (rcVideoCache * inputCache, const std::string & outputFile) private
Definition at line 842 of file rc_movieconverter.cpp.
References addVideoSamplesToMedia(), basename_part(), rcMovieConverterOptions::clipRect(), eMovieConverterErrorOK, eMovieConverterErrorWrite, eMovieConverterErrorWriteOpen, endl(), fileokandwritable, rcMovieConverterOptions::firstFrameIndex(), folder_part(), rcMovieConverterOptions::frameCount(), rcVideoCache::frameCount(), rcVideoCache::frameHeight(), rcMovieConverterOptions::frameOffset(), rcVideoCache::frameWidth(), rcRectangle< T >::height(), kVideoTimeScale, rcMovieConverter::lock(), mOptions, NULL, rfMakeFSSpecFromPosixPath(), rmAssert, rcMovieConverterOptions::samplePeriod(), rcMovieConverter::unlock(), ValidFSSpec(), rcMovieConverter::verbose(), and rcRectangle< T >::width().
 {
     rmAssert(inputCache);
     rcMovieConverterError error = eMovieConverterErrorOK;
     rcVideoCache& cache = *inputCache;
     Movie myMovie = NULL;
     Track myTrack = NULL;
     Media myMedia = NULL;
     FSSpec myFile;
     long myFlags = createMovieFileDeleteCurFile | createMovieFileDontCreateResFile;
     short myResRefNum = 0;
     short myResID = movieInDataForkResID;
     OSErr myErr = noErr;
     int32 frameCount = mOptions.frameCount();
     if ( frameCount < 0 )
         frameCount = inputCache->frameCount();
     if(! fileokandwritable (outputFile) )
     return eMovieConverterErrorWrite;
     string dirName = folder_part (outputFile);
     std::string destFullName;
     std::string tmp = basename_part (outputFile);
     if (dirName == ".")
     {
       std::vector<char> buffer (2048);
           if ( getcwd(&buffer[0], 2048) == 0)
             return eMovieConverterErrorWrite;
         destFullName = std::string(&buffer[0]) + std::string("/") + tmp;
     }
     else
         destFullName = std::string(dirName) + std::string("/") + tmp;
 #ifdef DEBUG
     fprintf(stderr, "destfile %s converted %s\n", outputFile.c_str(), destFullName.c_str());
 #endif
     /* Do some stupid stuff to make sure a "null" file exists. The file
      * needs to exist, otherwise rfMakeFSSpecFromPosixPath is unhappy.
      * The file gets deleted if it already exists just out of my own
      * personal paranoia.
      */
     FILE* tempFP = fopen(destFullName.c_str(), "r");
     if (tempFP) {
         fclose(tempFP);
         remove(destFullName.c_str());
     }
     tempFP = fopen(destFullName.c_str(), "w");
     fputc(0, tempFP);
     fclose(tempFP);
     lock();
     bool isDir;
     myFile = rfMakeFSSpecFromPosixPath(destFullName.c_str(), isDir);
     myErr = ValidFSSpec(&myFile);
     unlock();
     if (myErr != noErr)
         return eMovieConverterErrorWriteOpen;
     lock();
     myErr = EnterMovies();
     unlock();
     if (myErr != noErr)
         return eMovieConverterErrorWriteOpen;
     rcRect movieSize( 0, 0, cache.frameWidth(), cache.frameHeight() );
     if ( mOptions.clipRect().width() > 0 && mOptions.clipRect().height() > 0 )
         movieSize = rcRect( 0, 0, mOptions.clipRect().width(), mOptions.clipRect().height() );
     lock();
     // create a movie file for the destination movie
     myErr = CreateMovieFile(&myFile, smRoman /*sigMoviePlayer*/ ,
                             smCurrentScript, myFlags, &myResRefNum, &myMovie);
     unlock();
     if (myErr != noErr) {
         error = eMovieConverterErrorWriteOpen;
         goto bail;
     }
     lock();
     // create the movie track and media
     myTrack = NewMovieTrack(myMovie, FixRatio(movieSize.width(), 1),
                             FixRatio(movieSize.height(), 1), kNoVolume);
     myErr = GetMoviesError();
     unlock();
     if (myErr != noErr)
         goto bail;
     lock();
     myMedia = NewTrackMedia(myTrack, VideoMediaType, kVideoTimeScale, NULL, 0);
     myErr = GetMoviesError();
     unlock();
     if (myErr != noErr)
         goto bail;
     lock();
     // create the media samples
     myErr = BeginMediaEdits(myMedia);
     unlock();
     if (myErr != noErr)
         goto bail;
     myErr = addVideoSamplesToMedia(myMedia,
                                    cache,
                                    mOptions.firstFrameIndex(),
                                    frameCount,
                                    mOptions.frameOffset(),
                                    mOptions.samplePeriod(),
                                    movieSize);
     if (myErr != noErr)
         goto bail;
     lock();
     myErr = EndMediaEdits(myMedia);
     unlock();
     if (myErr != noErr)
         goto bail;
     lock();
     // add the media to the track
     myErr = InsertMediaIntoTrack(myTrack, 0, 0, GetMediaDuration(myMedia), fixed1);
     unlock();
     if (myErr != noErr)
         goto bail;
     lock();
     // add the movie atom to the movie file
     myErr = AddMovieResource(myMovie, myResRefNum, &myResID, NULL);
     unlock();
   bail:
     lock();
     if (myResRefNum != 0)
         CloseMovieFile(myResRefNum);
     if (myMovie != NULL)
         DisposeMovie(myMovie);
     if ( myErr != noErr) {
         if ( verbose() )
             cerr << "QT error " << myErr << endl;
         error = eMovieConverterErrorWrite;
     }
     unlock();
     return error;
 }
const rcMovieConverterOptionsQT& rcMovieConverterToQT::options () const inline
Definition at line 177 of file rc_movieconverter.h.
References mOptions.
 { return mOptions; }
void rcMovieConverterToQT::options (const rcMovieConverterOptionsQT & o) inline
Definition at line 182 of file rc_movieconverter.h.
References mOptions.
 { mOptions = o; }
Member Data Documentation
rcMovieConverterOptionsQT rcMovieConverterToQT::mOptions private
Definition at line 199 of file rc_movieconverter.h.
Referenced by addVideoSamplesToMedia(), createQTMovie(), and options().
The documentation for this class was generated from the following files:
include/visual/rc_movieconverter.h
src/visual/code/rc_movieconverter.cpp