Visible: rcVisualGraphicsCollection Class Reference
rcVisualGraphicsCollection Class Reference
#include <include/visual/rc_graphics.h>
Public Member Functions
rcVisualGraphicsCollection ()
rcVisualGraphicsCollection (const rcStyle &style, const rcVisualSegmentCollection &segments)
const rcStyle & style () const
rcStyle & style ()
const rcVisualSegmentCollection & segments () const
rcVisualSegmentCollection & segments ()
bool empty () const
uint32 size () const
int32 id () const
void style (const rcStyle &s)
void id (const int32 ii)
Private Attributes
rcStyle mStyle
rcVisualSegmentCollection mLines
int32 mId
Detailed Description
Definition at line 260 of file rc_graphics.h.
Constructor & Destructor Documentation
rcVisualGraphicsCollection::rcVisualGraphicsCollection () inline
Definition at line 263 of file rc_graphics.h.
 {};
rcVisualGraphicsCollection::rcVisualGraphicsCollection (const rcStyle & style, const rcVisualSegmentCollection & segments) inline
Definition at line 264 of file rc_graphics.h.
                                                               :
mStyle(style), mLines(segments), mId (-1) {};
Member Function Documentation
bool rcVisualGraphicsCollection::empty (void) const inline
Definition at line 275 of file rc_graphics.h.
References mLines.
 { return mLines.empty(); };
int32 rcVisualGraphicsCollection::id (void) const inline
Definition at line 277 of file rc_graphics.h.
References mId.
Referenced by rfPolygonGroupToGraphicsCollection().
 {return mId; }
void rcVisualGraphicsCollection::id (const int32 ii) inline
Definition at line 281 of file rc_graphics.h.
References mId.
 {if (ii >= 0) mId = ii; }
const rcVisualSegmentCollection& rcVisualGraphicsCollection::segments (void) const inline
Definition at line 272 of file rc_graphics.h.
References mLines.
Referenced by rcMonitor::buildCellBoundary(), rcMonitor::buildPositionCross(), rcMonitor::buildPositionPath(), rcEngineImpl::muscleTracker(), offsetGraphics(), rcNativeImporter::parseValue(), rcExporter::produceValue(), rfPolygonGroupToGraphicsCollection(), rcKinetoscope::visualDebugGraphics(), rcKinetoscope::visualFunctionHistory(), rcKinetoscope::visualFunctionMap(), rcKinetoscope::visualGraphics(), and rcEngineImpl::writeEntropyData().
 { return mLines; };
rcVisualSegmentCollection& rcVisualGraphicsCollection::segments (void) inline
Definition at line 273 of file rc_graphics.h.
References mLines.
 { return mLines; };
uint32 rcVisualGraphicsCollection::size (void) const inline
Definition at line 276 of file rc_graphics.h.
References mLines.
Referenced by rcGraphicsSegmentIteratorImpl::getCount(), rcExporter::produceValue(), and rcGraphicsSegment::rcGraphicsSegment().
 { return mLines.size(); };
const rcStyle& rcVisualGraphicsCollection::style () const inline
Definition at line 269 of file rc_graphics.h.
References mStyle.
 { return mStyle; };
rcStyle& rcVisualGraphicsCollection::style () inline
Definition at line 270 of file rc_graphics.h.
References mStyle.
 { return mStyle; };
void rcVisualGraphicsCollection::style (const rcStyle & s) inline
Definition at line 280 of file rc_graphics.h.
References mStyle.
 { mStyle = s; };
Member Data Documentation
int32 rcVisualGraphicsCollection::mId private
Definition at line 286 of file rc_graphics.h.
Referenced by id().
rcVisualSegmentCollection rcVisualGraphicsCollection::mLines private
Definition at line 285 of file rc_graphics.h.
Referenced by empty(), segments(), and size().
rcStyle rcVisualGraphicsCollection::mStyle private
Definition at line 284 of file rc_graphics.h.
Referenced by style().
The documentation for this class was generated from the following file:
include/visual/rc_graphics.h