Visible: rcMPEG2Grabber Class Reference
rcMPEG2Grabber Class Reference
#include <include/visual/rc_mpeg2grabber.h>
Classes
struct fbuf_s
Public Member Functions
rcMPEG2Grabber (const std::string fileName, rcCarbonLock *lock, double frameInterval=0.0)
virtual ~rcMPEG2Grabber ()
virtual bool start ()
virtual bool stop ()
virtual int32 frameCount ()
virtual int32 cacheSize ()
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)
bool getReifyMovie (const std::string &fName, const rcChannelConversion &conv, const movieFormatRev &rev, bool overWrite, const float &fInt, const int32 sample=1)
virtual const std::string getInputSourceName ()
Public Member Functions inherited from rcFileGrabber
rcFileGrabber (rcCarbonLock *lock)
virtual ~rcFileGrabber ()
virtual rcFrameGrabberError getLastError () const
virtual bool isValid () const
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
Static Public Attributes
static const int32 buffer_size = 4096
Private Member Functions
struct fbuf_s * get_fbuf (void)
rcWindow add_frame (int width, int height, uint8_t *buf)
void save_ppm (int width, int height, uint8_t *buf, int num)
int32 countFrames ()
bool isFormatYv12 ()
bool isFormat422p ()
Private Attributes
struct rcMPEG2Grabber::fbuf_s fbuf [3]
uint8_t mBuffer [buffer_size]
mpeg2dec_t * mDecoder
const mpeg2_info_t * mInfo
mpeg2_state_t mState
size_t mSize
vImage_Buffer mAlphaPels
const std::string mFileName
FILE * mFilePtr
int32 mFrameCount
short mRefnum
int32 mCurrentIndex
bool mGotFirstFrame
double mFrameInterval
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Protected Member Functions inherited from rcFileGrabber
void setLastError (rcFrameGrabberError)
void lock ()
void unlock ()
Detailed Description
Definition at line 25 of file rc_mpeg2grabber.h.
Constructor & Destructor Documentation
rcMPEG2Grabber::rcMPEG2Grabber (const std::string fileName, rcCarbonLock * lock, double frameInterval = 0.0)
Definition at line 25 of file rc_mpeg2grabber.cpp.
References eFrameErrorFileInit, rcFileGrabber::lock(), mAlphaPels, mFileName, mFilePtr, NULL, rcFileGrabber::setLastError(), and rcFileGrabber::unlock().
                                                                                                     :
   rcFileGrabber( cLock ),
   mSize ( (size_t)-1), mFileName( fileName ),
   mFrameCount(0), mFilePtr (NULL),
   mRefnum( 0 ),mCurrentIndex( 0 ), mGotFirstFrame( false ),
   mFrameInterval( frameInterval )
 {
   lock();
   OSErr err;
   if ( mFileName.empty() )
     setLastError( eFrameErrorFileInit );
   else {
     mFilePtr = fopen (mFileName.c_str(), "rb");
     if (!mFilePtr)
       setLastError( eFrameErrorFileInit );
   }
   mAlphaPels.data = (void *) NULL;
   mAlphaPels.width =   mAlphaPels.height =   mAlphaPels.rowBytes = 0;
   unlock();
}
rcMPEG2Grabber::~rcMPEG2Grabber () virtual
Definition at line 51 of file rc_mpeg2grabber.cpp.
 {
 }
Member Function Documentation
rcWindow rcMPEG2Grabber::add_frame (int width, int height, uint8_t * buf) private
Definition at line 217 of file rc_mpeg2grabber.cpp.
References rcPixel32, rfRgb, and rcWindow::rowPointer().
Referenced by getReifyMovie().
 {
   const int32 bytesInPixel = 3;
   rcWindow frame (width, height, rcPixel32);
   for (int32 j = 0; j < height; j++)
     {
       uint32 *fourbytepels = (uint32 *) frame.rowPointer (j);
       for (int32 i = 0; i < width; i++, data24+=bytesInPixel)
       {
 #ifdef __ppc__
     *fourbytepels++ = rfRgb (data24[0],data24[1],data24[2]);
 #else
     uint32 tmp = rfRgb (data24[2],data24[1],data24[0]);
     *fourbytepels++  = ( tmp & 0xff000000 ) | ( tmp & 0xff ) << 16 |
       ( tmp & 0xff00 ) | ( tmp & 0xff0000 ) >> 16;
 #endif
       }
     }
   return frame;
 }
virtual int32 rcMPEG2Grabber::cacheSize () inline virtual
Implements rcFrameGrabber.
Definition at line 51 of file rc_mpeg2grabber.h.
 { return 0; }
int32 rcMPEG2Grabber::countFrames () private
int32 rcMPEG2Grabber::frameCount () virtual
Implements rcFileGrabber.
Definition at line 100 of file rc_mpeg2grabber.cpp.
References mFrameCount.
Referenced by getReifyMovie().
 {
   return mFrameCount;
 }
struct fbuf_s* rcMPEG2Grabber::get_fbuf (void) inline read private
Definition at line 68 of file rc_mpeg2grabber.h.
References eFrameErrorFileInit, NULL, and rcMPEG2Grabber::fbuf_s::used.
Referenced by getReifyMovie().
   {
     int i;
     for (i = 0; i < 3; i++)
       if (!fbuf[i].used) {
     fbuf[i].used = 1;
     return fbuf + i;
       }
     setLastError( eFrameErrorFileInit );
     return NULL;
   }
const std::string rcMPEG2Grabber::getInputSourceName () virtual
Implements rcFrameGrabber.
Definition at line 191 of file rc_mpeg2grabber.cpp.
References mFileName.
 {
   return mFileName;
 }
rcFrameGrabberStatus rcMPEG2Grabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) virtual
Implements rcFileGrabber.
Definition at line 275 of file rc_mpeg2grabber.cpp.
References eFrameStatusNoFrame, and rmUnused.
  { rmUnused (ptr); rmUnused (isBlocking); return eFrameStatusNoFrame; }
bool rcMPEG2Grabber::getReifyMovie (const std::string & fName, const rcChannelConversion & conv, const movieFormatRev & rev, bool overWrite, const float & fInt, const int32 sample = 1)
Definition at line 106 of file rc_mpeg2grabber.cpp.
References add_frame(), rcGenMovieFile::addFrame(), rcGenMovieFile::addHeader(), mpeg2_fbuf_s::buf, buffer_size, cCreator(), mpeg2_info_s::discard_fbuf, mpeg2_info_s::display_fbuf, eFrameErrorOK, eFrameErrorUnknown, eGenMovieFileErrorOK, fbuf, rcGenMovieFile::flush(), frameCount(), generateHeader(), get_fbuf(), mpeg2_sequence_s::height, mpeg2_fbuf_s::id, rcFileGrabber::lock(), mBuffer, mDecoder, mFilePtr, mFrameCount, mInfo, movieOriginConversionExt, mpeg2_buffer(), mpeg2_convert(), mpeg2_parse(), mpeg2_set_buf(), mpeg2convert_rgb24, mSize, mState, NULL, rcMPEG2Grabber::fbuf_s::rgb, rmAssert, mpeg2_info_s::sequence, rcFileGrabber::setLastError(), STATE_BUFFER, STATE_END, STATE_INVALID_END, STATE_PICTURE, STATE_SEQUENCE, STATE_SLICE, rcFileGrabber::unlock(), rcMPEG2Grabber::fbuf_s::used, rcGenMovieFile::valid(), and mpeg2_sequence_s::width.
Referenced by genRFYmov(), and main().
 {
   lock();
   setLastError( eFrameErrorUnknown );
   rmAssert (sample > 0 && sample < 9999); // some sanity checks on sample
   struct fbuf_s * current_fbuf;
   const movieOriginType origin =  movieOriginConversionExt;
   rcGenMovieFileError error = eGenMovieFileErrorOK;
   //@note the frame rate is set to 30 fps
   rcGenMovieFile movie(fName, origin,  conv, cCreator, rev, overWrite, fInt);
   rmAssert( movie.valid() ); // @note replace with throw
   // Add an experiment header
   rcMovieFileExpExt expHdr = generateHeader();
   expHdr.title( "MPEG2Grabber" );
   do
     {
       mState = mpeg2_parse (mDecoder);
       switch (mState)
     {
     case STATE_BUFFER:
       mSize = fread (mBuffer, 1, rcMPEG2Grabber::buffer_size, mFilePtr);
       mpeg2_buffer (mDecoder, mBuffer, mBuffer + mSize);
       break;
     case STATE_SEQUENCE:
       mpeg2_convert (mDecoder, mpeg2convert_rgb24, NULL);
       for (int32 i = 0; i < 3; i++)
         {
           fbuf[i].rgb[0] = (uint8_t *) malloc (3 * mInfo->sequence->width * mInfo->sequence->height);
           fbuf[i].rgb[1] = fbuf[i].rgb[2] = NULL;
           if (!fbuf[i].rgb[0])
         {
           fprintf (stderr, "Could not allocate an output buffer.\n");
           exit (1);
         }
           fbuf[i].used = 0;
         }
       for (int32 i = 0; i < 2; i++)
         {
           current_fbuf = get_fbuf ();
           mpeg2_set_buf (mDecoder, current_fbuf->rgb, current_fbuf);
         }
       break;
     case STATE_PICTURE:
       current_fbuf = get_fbuf ();
       mpeg2_set_buf (mDecoder, current_fbuf->rgb, current_fbuf);
       break;
     case STATE_SLICE:
     case STATE_END:
     case STATE_INVALID_END:
       if (mInfo->display_fbuf)
         {
           if (! ( frameCount() % sample ) )
         movie.addFrame ( add_frame (mInfo->sequence->width, mInfo->sequence->height, mInfo->display_fbuf->buf[0]));
           mFrameCount++;
         }
       if (mInfo->discard_fbuf)
         ((struct fbuf_s *)mInfo->discard_fbuf->id)->used = 0;
       if (mState != STATE_SLICE)
         for (int32 i = 0; i < 3; i++)
           free (fbuf[i].rgb[0]);
       break;
     default:
       break;
     }
     } while (mSize);
   setLastError( eFrameErrorOK );
   // Add header and flush
   movie.addHeader( expHdr );
   error = movie.flush();
   unlock();
   return ( error == eGenMovieFileErrorOK );
 }
bool rcMPEG2Grabber::isFormat422p () private
Definition at line 249 of file rc_mpeg2grabber.cpp.
References mpeg2_sequence_s::chroma_height, mpeg2_sequence_s::chroma_width, mpeg2_sequence_s::height, mInfo, mpeg2_info_s::sequence, and mpeg2_sequence_s::width.
 {
   if (mInfo && mInfo->sequence->width >> 1 == mInfo->sequence->chroma_width &&
       mInfo->sequence->height == mInfo->sequence->chroma_height)
     return true;
   return false;
 }
bool rcMPEG2Grabber::isFormatYv12 () private
Definition at line 240 of file rc_mpeg2grabber.cpp.
References mpeg2_sequence_s::chroma_height, mpeg2_sequence_s::chroma_width, mpeg2_sequence_s::height, mInfo, mpeg2_info_s::sequence, and mpeg2_sequence_s::width.
 {
   if (mInfo && mInfo->sequence->width >> 1 == mInfo->sequence->chroma_width &&
       mInfo->sequence->height >> 1 == mInfo->sequence->chroma_height)
     return true;
   return false;
 }
void rcMPEG2Grabber::save_ppm (int width, int height, uint8_t * buf, int num) private
Definition at line 199 of file rc_mpeg2grabber.cpp.
 {
     char filename[100];
     FILE * ppmfile;
     sprintf (filename, "%d.ppm", num);
     ppmfile = fopen (filename, "wb");
     if (!ppmfile) {
     fprintf (stderr, "Could not open file \"%s\".\n", filename);
     exit (1);
     }
     fprintf (ppmfile, "P6\n%d %d\n255\n", width, height);
     fwrite (buf, 3 * width, height, ppmfile);
     fclose (ppmfile);
 }
bool rcMPEG2Grabber::start (void) virtual
Implements rcFileGrabber.
Definition at line 56 of file rc_mpeg2grabber.cpp.
References eFrameErrorOK, eFrameErrorQuicktimeInit, rcFileGrabber::getLastError(), rcFileGrabber::lock(), mDecoder, mInfo, mpeg2_accel(), MPEG2_ACCEL_PPC_ALTIVEC, MPEG2_ACCEL_X86_MMX, MPEG2_ACCEL_X86_MMXEXT, mpeg2_custom_fbuf(), mpeg2_info(), mpeg2_init(), mSize, NULL, rmAssert, rcFileGrabber::setLastError(), and rcFileGrabber::unlock().
Referenced by genRFYmov(), and main().
 {
   lock();
   int accel = 0;
 #if defined(__ppc__)
   accel |= MPEG2_ACCEL_PPC_ALTIVEC;
 #elif defined(__i386__)
   accel |= MPEG2_ACCEL_X86_MMX;
   accel |= MPEG2_ACCEL_X86_MMXEXT;
 #else
   rmAssert (1);
 #endif
   mpeg2_accel(accel);
   mDecoder = mpeg2_init ();
   if (mDecoder == NULL)
     setLastError( eFrameErrorQuicktimeInit );
   else
     {
       mInfo = mpeg2_info (mDecoder);
       mpeg2_custom_fbuf (mDecoder, 1);
       rmAssert (mSize == (size_t)-1);
     }
   unlock();
   return ( getLastError() == eFrameErrorOK );
 }
bool rcMPEG2Grabber::stop (void) virtual
Implements rcFileGrabber.
Definition at line 88 of file rc_mpeg2grabber.cpp.
References rcFileGrabber::lock(), mDecoder, mpeg2_close(), and rcFileGrabber::unlock().
 {
   lock();
   mpeg2_close (mDecoder);
   unlock();
   return true;
 }
Member Data Documentation
const int32 rcMPEG2Grabber::buffer_size = 4096 static
Definition at line 27 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie().
struct rcMPEG2Grabber::fbuf_s rcMPEG2Grabber::fbuf[3] private
Referenced by getReifyMovie().
vImage_Buffer rcMPEG2Grabber::mAlphaPels private
Definition at line 93 of file rc_mpeg2grabber.h.
Referenced by rcMPEG2Grabber().
uint8_t rcMPEG2Grabber::mBuffer[buffer_size] private
Definition at line 88 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie().
int32 rcMPEG2Grabber::mCurrentIndex private
Definition at line 99 of file rc_mpeg2grabber.h.
mpeg2dec_t* rcMPEG2Grabber::mDecoder private
Definition at line 89 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie(), start(), and stop().
const std::string rcMPEG2Grabber::mFileName private
Definition at line 95 of file rc_mpeg2grabber.h.
Referenced by getInputSourceName(), and rcMPEG2Grabber().
FILE* rcMPEG2Grabber::mFilePtr private
Definition at line 96 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie(), and rcMPEG2Grabber().
int32 rcMPEG2Grabber::mFrameCount private
Definition at line 97 of file rc_mpeg2grabber.h.
Referenced by frameCount(), and getReifyMovie().
double rcMPEG2Grabber::mFrameInterval private
Definition at line 101 of file rc_mpeg2grabber.h.
bool rcMPEG2Grabber::mGotFirstFrame private
Definition at line 100 of file rc_mpeg2grabber.h.
const mpeg2_info_t* rcMPEG2Grabber::mInfo private
Definition at line 90 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie(), isFormat422p(), isFormatYv12(), and start().
short rcMPEG2Grabber::mRefnum private
Definition at line 98 of file rc_mpeg2grabber.h.
size_t rcMPEG2Grabber::mSize private
Definition at line 92 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie(), and start().
mpeg2_state_t rcMPEG2Grabber::mState private
Definition at line 91 of file rc_mpeg2grabber.h.
Referenced by getReifyMovie().
The documentation for this class was generated from the following files:
include/visual/rc_mpeg2grabber.h
src/visual/code/rc_mpeg2grabber.cpp