Visible: error_handler Class Reference
error_handler Class Reference
#include <include/stlplus/error_handler.hpp>
Public Member Functions
error_handler (otext &device, unsigned limit=0, bool show=true) throw ()
error_handler (otext &device, const std::string &message_file, unsigned limit=0, bool show=true) throw (error_handler_read_error)
error_handler (otext &device, const std::vector< std::string > &message_files, unsigned limit=0, bool show=true) throw (error_handler_read_error)
~error_handler (void) throw ()
void set_error_limit (unsigned error_limit) throw ()
unsigned error_limit (void) const throw ()
void reset_error_count (void) throw ()
unsigned error_count (void) const throw ()
otext & device (void)
bool information (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
bool information (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
bool information (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
bool information (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
bool information (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
bool information (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
bool information (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
bool information (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
bool information (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
bool information (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
bool warning (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
bool warning (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
bool warning (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
bool warning (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
bool warning (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
bool warning (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
bool warning (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
bool warning (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
bool warning (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
bool warning (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
bool error (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const std::string &id) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool error (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
bool fatal (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const std::string &id) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool fatal (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
bool plaintext (const std::string &text)
Public Member Functions inherited from error_handler_base
error_handler_base (bool show=true) throw ()
error_handler_base (const std::string &message_file, bool show=true) throw (error_handler_read_error)
error_handler_base (const std::vector< std::string > &message_files, bool show=true) throw (error_handler_read_error)
virtual ~error_handler_base (void) throw ()
void add_message_file (const std::string &message_file) throw (error_handler_read_error)
void add_message_files (const std::vector< std::string > &message_files) throw (error_handler_read_error)
void add_message (const std::string &id, const std::string &text) throw ()
void set_information_format (const std::string &format) throw ()
void set_warning_format (const std::string &format) throw ()
void set_error_format (const std::string &format) throw ()
void set_fatal_format (const std::string &format) throw ()
void set_context_format (const std::string &format) throw ()
void set_supplement_format (const std::string &format) throw ()
void set_position_format (const std::string &format) throw ()
void show_position (void) throw ()
void hide_position (void) throw ()
std::vector< std::string > information_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > information_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > warning_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > error_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
std::vector< std::string > fatal_message (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_supplement (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_context (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
void push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
unsigned context_depth (void) const throw ()
void pop_context (void) throw ()
void pop_context (unsigned) throw ()
error_context auto_push_context (const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::string &arg1) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2) throw (error_handler_id_error,error_handler_format_error)
error_context auto_push_context (const error_position &, const std::string &id, const std::string &arg1, const std::string &arg2, const std::string &arg3) throw (error_handler_id_error,error_handler_format_error)
Private Attributes
smart_ptr_nocopy
< error_handler_body > m_body
Friends
class error_handler_body
Detailed Description
Definition at line 726 of file error_handler.hpp.
Constructor & Destructor Documentation
error_handler::error_handler (otext & device, unsigned limit = 0, bool show = true) throw ()
Definition at line 1402 of file error_handler.cpp.
           :
   error_handler_base(show), m_body(new error_handler_body(device, limit))
 {
 }
error_handler::error_handler (otext & device, const std::string & message_file, unsigned limit = 0, bool show = true) throw (error_handler_read_error)
Definition at line 1408 of file error_handler.cpp.
                                   :
   error_handler_base(message_file,show), m_body(new error_handler_body(device, limit))
 {
 }
error_handler::error_handler (otext & device, const std::vector< std::string > & message_files, unsigned limit = 0, bool show = true) throw (error_handler_read_error)
Definition at line 1414 of file error_handler.cpp.
                                   :
   error_handler_base(message_files,show), m_body(new error_handler_body(device, limit))
 {
 }
error_handler::~error_handler (void) throw ()
Definition at line 1420 of file error_handler.cpp.
References error_handler_body::device(), otext::flush(), and m_body.
 {
   m_body->device().flush();
 }
Member Function Documentation
otext & error_handler::device (void)
Definition at line 1453 of file error_handler.cpp.
References error_handler_body::device(), and m_body.
Referenced by plaintext().
 {
   return m_body->device();
 }
bool error_handler::error (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1633 of file error_handler.cpp.
References flush().
 {
   device() << error_message(id, args) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const std::string & id) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1643 of file error_handler.cpp.
References flush().
 {
   device() << error_message(id) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1652 of file error_handler.cpp.
References flush().
 {
   device() << error_message(id, arg1) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1662 of file error_handler.cpp.
References flush().
 {
   device() << error_message(id, arg1, arg2) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1672 of file error_handler.cpp.
References flush().
 {
   device() << error_message(id, arg1, arg2, arg3) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1682 of file error_handler.cpp.
References flush().
 {
   device() << error_message(position, id, args) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1693 of file error_handler.cpp.
References flush().
 {
   device() << error_message(position, id) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1703 of file error_handler.cpp.
References flush().
 {
   device() << error_message(position, id, arg1) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1714 of file error_handler.cpp.
References flush().
 {
   device() << error_message(position, id, arg1, arg2) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
bool error_handler::error (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_limit_error)
Definition at line 1725 of file error_handler.cpp.
References flush().
 {
   device() << error_message(position, id, arg1, arg2, arg3) << flush;
   m_body->increment();
   if (m_body->limit_reached()) throw error_handler_limit_error(m_body->limit());
   return false;
 }
unsigned error_handler::error_count (void) const throw ()
Definition at line 1447 of file error_handler.cpp.
References error_handler_body::count(), and m_body.
 {
   return m_body->count();
 }
unsigned error_handler::error_limit (void) const throw ()
Definition at line 1435 of file error_handler.cpp.
References error_handler_body::limit(), and m_body.
 {
   return m_body->limit();
 }
bool error_handler::fatal (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1739 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(id, args) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const std::string & id) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1747 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(id) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1754 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(id, arg1) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1762 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(id, arg1, arg2) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1770 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(id, arg1, arg2, arg3) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1778 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(position, id, args) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1787 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(position, id) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1795 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(position, id, arg1) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1804 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(position, id, arg1, arg2) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::fatal (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error,error_handler_fatal_error)
Definition at line 1813 of file error_handler.cpp.
References flush().
 {
   device() << fatal_message(position, id, arg1, arg2, arg3) << flush;
   throw error_handler_fatal_error(id);
 }
bool error_handler::information (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1461 of file error_handler.cpp.
References flush().
Referenced by cli_parser::usage().
 {
   device() << information_message(id, args) << flush;
   return true;
 }
bool error_handler::information (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1469 of file error_handler.cpp.
References flush().
 {
   device() << information_message(id) << flush;
   return true;
 }
bool error_handler::information (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1476 of file error_handler.cpp.
References flush().
 {
   device() << information_message(id, arg1) << flush;
   return true;
 }
bool error_handler::information (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1484 of file error_handler.cpp.
References flush().
 {
   device() << information_message(id, arg1, arg2) << flush;
   return true;
 }
bool error_handler::information (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1492 of file error_handler.cpp.
References flush().
 {
   device() << information_message(id, arg1, arg2, arg3) << flush;
   return true;
 }
bool error_handler::information (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1500 of file error_handler.cpp.
References flush().
 {
   device() << information_message(position, id, args) << flush;
   return true;
 }
bool error_handler::information (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1509 of file error_handler.cpp.
References flush().
 {
   device() << information_message(position, id) << flush;
   return true;
 }
bool error_handler::information (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1517 of file error_handler.cpp.
References flush().
 {
   device() << information_message(position, id, arg1) << flush;
   return true;
 }
bool error_handler::information (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1526 of file error_handler.cpp.
References flush().
 {
   device() << information_message(position, id, arg1, arg2) << flush;
   return true;
 }
bool error_handler::information (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1535 of file error_handler.cpp.
References flush().
 {
   device() << information_message(position, id, arg1, arg2, arg3) << flush;
   return true;
 }
bool error_handler::plaintext (const std::string & text)
Definition at line 1825 of file error_handler.cpp.
References device(), endl(), and flush().
 {
   device() << text << endl << flush;
   return true;
 }
void error_handler::reset_error_count (void) throw ()
Definition at line 1441 of file error_handler.cpp.
References m_body, and error_handler_body::set_count().
 {
   m_body->set_count(0);
 }
void error_handler::set_error_limit (unsigned error_limit) throw ()
Definition at line 1429 of file error_handler.cpp.
 {
   m_body->set_limit(error_limit);
 }
bool error_handler::warning (const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1547 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(id, args) << flush;
   return true;
 }
bool error_handler::warning (const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1555 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(id) << flush;
   return true;
 }
bool error_handler::warning (const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1562 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(id, arg1) << flush;
   return true;
 }
bool error_handler::warning (const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1570 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(id, arg1, arg2) << flush;
   return true;
 }
bool error_handler::warning (const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1578 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(id, arg1, arg2, arg3) << flush;
   return true;
 }
bool error_handler::warning (const error_position & position, const std::string & id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1586 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(position, id, args) << flush;
   return true;
 }
bool error_handler::warning (const error_position & position, const std::string & id) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1595 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(position, id) << flush;
   return true;
 }
bool error_handler::warning (const error_position & position, const std::string & id, const std::string & arg1) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1603 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(position, id, arg1) << flush;
   return true;
 }
bool error_handler::warning (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1612 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(position, id, arg1, arg2) << flush;
   return true;
 }
bool error_handler::warning (const error_position & position, const std::string & id, const std::string & arg1, const std::string & arg2, const std::string & arg3) throw (error_handler_id_error,error_handler_format_error)
Definition at line 1621 of file error_handler.cpp.
References flush().
 {
   device() << warning_message(position, id, arg1, arg2, arg3) << flush;
   return true;
 }
Friends And Related Function Documentation
friend class error_handler_body friend
Definition at line 1004 of file error_handler.hpp.
Member Data Documentation
smart_ptr_nocopy<error_handler_body> error_handler::m_body private
Definition at line 1005 of file error_handler.hpp.
Referenced by device(), error_count(), error_limit(), reset_error_count(), and ~error_handler().
The documentation for this class was generated from the following files:
include/stlplus/error_handler.hpp
include/stlplus/error_handler.cpp