Visible: rcPointCorrelation Class Reference
rcPointCorrelation Class Reference
#include <include/analysis/rc_point_corr.h>
Public Member Functions
rcPointCorrelation ()
virtual ~rcPointCorrelation ()
void gen3by3Space (const rcRect &srchSpace, const rcIPair &modelOrigin, rsCorr3by3Point &res) const
void gen5by5Space (const rcRect &srchSpace, const rcIPair &modelOrigin, rsCorr5by5Point &res) const
void genSpace (const rcRect &srchSpace, const rcIPair &modelOrigin, vector< vector< float > > &res, const int32 acRadius) const
void update (rcWindow imgWin, rcWindow mdlWin, const rcMomentGenerator &imgMom, const rcMomentGenerator &mdlMom)
void update (rcWindow imgWin, rcWindow mdlWin)
Private Attributes
rcWindow _imgWin
rcWindow _mdlWin
unsigned char * _iRowBase
unsigned char * _mRowBase
int32 _iRowUpdate
int32 _mRowUpdate
const rcMomentGenerator * _imgMom
const rcMomentGenerator * _mdlMom
unsigned char * _destSpaceBase
uint32 * _destSpacePtr
uint32 * _vectorSumPtr
uint32 * _vectorSumSqPtr
uint32 * _resultPtr
int32 _destSpaceSz
Detailed Description
Definition at line 25 of file rc_point_corr.h.
Constructor & Destructor Documentation
rcPointCorrelation::rcPointCorrelation ()
Definition at line 727 of file rc_point_corr.cpp.
References _destSpaceBase, _destSpacePtr, _destSpaceSz, _resultPtr, _vectorSumPtr, _vectorSumSqPtr, and rmAssert.
                                        :
   _iRowBase(0), _mRowBase(0), _iRowUpdate(0), _mRowUpdate(0), _imgMom(0),
   _mdlMom(0), _destSpaceBase(0), _destSpacePtr(0), _destSpaceSz(defDestSpcSz)
 {
   rmAssert(_destSpaceSz >= (int32)(5*8*sizeof(float) + 32 + 32 + 16));
   _destSpaceBase = (unsigned char*)malloc(_destSpaceSz);
   _vectorSumPtr = (uint32*)(((int)_destSpaceBase + 15) & 0xFFFFFFF0);
   _vectorSumSqPtr = _vectorSumPtr + 8;
   _resultPtr =  _vectorSumSqPtr + 8;
   _destSpacePtr = _resultPtr + 4;
}
rcPointCorrelation::~rcPointCorrelation () virtual
Definition at line 739 of file rc_point_corr.cpp.
References _destSpaceBase.
 {
   if (_destSpaceBase) {
     free(_destSpaceBase);
     _destSpaceBase = 0;
   }
 }
Member Function Documentation
void rcPointCorrelation::gen3by3Space (const rcRect & srchSpace, const rcIPair & modelOrigin, rsCorr3by3Point & res) const
Definition at line 782 of file rc_point_corr.cpp.
References _destSpacePtr, _imgMom, _imgWin, _iRowBase, _iRowUpdate, _mdlMom, _mdlWin, _mRowBase, _mRowUpdate, _vectorSumPtr, _vectorSumSqPtr, genSpace(), rcWindow::height(), rcRectangle< T >::height(), rcMomentGenerator::imgSumPtr(), rcMomentGenerator::imgSumSqPtrLow(), N, rmAssert, rsCorr3by3Point::score, rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
 {
 #ifndef __ppc__
     vector<vector<float> > results (3);
     for (uint32 i = 0; i < 3; i++)
             results[i].resize (3);
         genSpace(srchSpace, modelOrigin, results, 1);
         for (uint32 j = 0; j < 3; j++)
             for (uint32 i = 0; i < 3; i++)
             res.score[j][i] = results[j][i];
 #else
   /* Validate the current state of the object and the inputs.
    * Calculate model and image position and size.
    */
   rmAssert(_imgMom);
   rmAssert(_mdlMom);
   const int32 xImgOrigin = srchSpace.x();
   const int32 yImgOrigin = srchSpace.y();
   const int32 imgWidth = srchSpace.width();
   const int32 imgHeight = srchSpace.height();
   rmAssert(imgWidth <= 16);
   rmAssert(imgHeight <= 16);
   const int32 xSpcBound = xImgOrigin + imgWidth;
   const int32 ySpcBound = yImgOrigin + imgHeight;
   rmAssert(xImgOrigin < xSpcBound);
   rmAssert(xSpcBound <= _imgWin.width());
   rmAssert(yImgOrigin < ySpcBound);
   rmAssert(ySpcBound <= _imgWin.height());
   /* For 3x3 correlation space, model dimensions are always (-2,-2)
    * of the search space dimensions.
    */
   const int32 mdlWidth = imgWidth - 2;
   const int32 mdlHeight = imgHeight - 2;
   rmAssert(mdlWidth > 0);
   rmAssert(mdlHeight > 0);
   const int32 xMdlOrigin = modelOrigin.x();
   const int32 yMdlOrigin = modelOrigin.y();
   const int32 xMdlBound = xMdlOrigin + mdlWidth;
   const int32 yMdlBound = yMdlOrigin + mdlHeight;
   rmAssert(xMdlOrigin < xMdlBound);
   rmAssert(xMdlBound <= _mdlWin.width());
   rmAssert(yMdlOrigin < yMdlBound);
   rmAssert(yMdlBound <= _mdlWin.height());
   /* Request is valid. Calculate IM values for all the locations
    * within the search space.
    */
   vector short t0, t1, v0 = vec_splat_s16(0);
   vector unsigned char mModelPerm, mAlignPerm, iAlignPerm, rotatePerm;
   unsigned char* img =
     (unsigned char*)(_iRowBase + _iRowUpdate*yImgOrigin + xImgOrigin);
   vector unsigned char* iPtr =  (vector unsigned char*)img;
   unsigned char* mdl =
     (unsigned char*)(_mRowBase + _mRowUpdate*yMdlOrigin + xMdlOrigin);
   vector unsigned char* mPtr = (vector unsigned char*)mdl;
   vector signed int* destP = (vector signed int*)_destSpacePtr;
   const bool icb = (((int)iPtr & 0xF) + imgWidth) > 16;
   const bool mcb = (((int)mPtr & 0xF) + mdlWidth) > 16;
   /* Note: In the following comments, sample values are given based on the
    * assumption that:
    *
    *    mdlWidth = 5
    *    For mcb == true case: Address of mdl == 12 MOD 16
    *    For mcb == false case: Address of mdl == 10 MOD 16
    */
   iAlignPerm = vec_lvsl(0, img);
   T0_UC = vec_splat_u8(3);               // T0= 03030303030303030303030303030303
   T0_UC = vec_sl(T0_UC, T0_UC);          // T0= 18181818181818181818181818181818
   T1_UC = vec_lvsr(mdlWidth, (int*)0);   // T1= 0B0C0D0E0F101112131415161718191A
   T0_UC = vec_perm(V0_UC, T0_UC, T1_UC); // T0= 00000000001818181818181818181818
   if (mcb) {
     mAlignPerm = vec_lvsl(0, mdl);       // AP= 0C0D0E0F101112131415161718191A1B
     T1_UC = vec_lvsl(0, (int*)0);        // T1= 000102030405060708090A0B0C0D0E0F
     mModelPerm = vec_or(T1_UC, T0_UC);   // MP= 00010203041X1X1X1X1X1X1X1X1X1X1X
   }
   else {
     mAlignPerm = vec_splat_u8(0);        // Quiet compiler
     T1_UC = vec_lvsl(0, mdl);            // T1= 0A0B0C0D0E0F10111213141516171819
     mModelPerm = vec_or(T1_UC, T0_UC);   // MP= 0A0B0C0D0E1X1X1X1X1X1X1X1X1X1X1X
   }
   rotatePerm = vec_lvsr(4,(int*)0);
   if (icb) {
     if (mcb) {
       if (mdlHeight > 2) {
     GEN_LRG_3X3_SPACE(LOADI_CB, LOADM_CB, mdlHeight, ICBMCB);
       }
       else {
     GEN_SML_3X3_SPACE(LOADI_CB, LOADM_CB, mdlHeight);
       }
     }
     else {
       if (mdlHeight > 2) {
     GEN_LRG_3X3_SPACE(LOADI_CB, LOADM, mdlHeight, ICBM);
       }
       else {
     GEN_SML_3X3_SPACE(LOADI_CB, LOADM, mdlHeight);
       }
     }
   }
   else {
     if (mcb) {
       if (mdlHeight > 2) {
     GEN_LRG_3X3_SPACE(LOADI, LOADM_CB, mdlHeight, IMCB);
       }
       else {
     GEN_SML_3X3_SPACE(LOADI, LOADM_CB, mdlHeight);
       }
     }
     else {
       if (mdlHeight > 2) {
     GEN_LRG_3X3_SPACE(LOADI, LOADM, mdlHeight, IM);
       }
       else {
     GEN_SML_3X3_SPACE(LOADI, LOADM, mdlHeight);
       }
     }
   } // End of: if (icb) ... else ...
   /* Now calculate correlation scores for model and image at all
    * locations within the search space.
    */
   {
     vector unsigned short N, sumM;
     vector float varM, varI, varIM, vf1;
     T0_UI = vec_splat_u32(1);
     vf1 = vec_ctf(T0_UI, 0);
     /* Calculate and store N in vector.
      */
     *(uint16*)_vectorSumPtr = (uint16)(mdlWidth*mdlHeight);
     N = *(vector unsigned short*)_vectorSumPtr;
     N = vec_splat(N, 0);
     /* Calculate and store sumM and varM in vectors.
      */
     {
       const int32 x0 = xMdlOrigin*3;
       const int32 y0 = yMdlOrigin;
       const int32 x1 = x0 + mdlWidth*3;
       const int32 y1 = y0 + mdlHeight;
       const uint16 iSumM =
     (uint16)(*(_mdlMom->imgSumPtr(x1, y1)) - *(_mdlMom->imgSumPtr(x0, y1)) +
            *(_mdlMom->imgSumPtr(x0, y0)) - *(_mdlMom->imgSumPtr(x1, y0)));
       *(uint16*)_vectorSumPtr = iSumM;
       sumM = *(vector unsigned short*)_vectorSumPtr;
       sumM = vec_splat(sumM, 0);
       vector unsigned int sumMM, sumMSq;
       const uint32 iSumMM =
     *(_mdlMom->imgSumSqPtrLow(x1+1,y1)) - *(_mdlMom->imgSumSqPtrLow(x0+1,y1)) +
     *(_mdlMom->imgSumSqPtrLow(x0+1,y0)) - *(_mdlMom->imgSumSqPtrLow(x1+1,y0));
       *_vectorSumPtr = iSumMM;
       sumMM = *(vector unsigned int*)_vectorSumPtr;
       sumMM = vec_splat(sumMM, 0);
       /* Calculate (N*SumMM - SumM*SumM).
        *
        * Note that SumM always fits in 16 bits, so the multiply can be
        * done in a single instruction. SumMM can go over 16 bits, so
        * the multiply is done as a pair of 16 bit multiplies, a 16 bit
        * shift, and an add.
        */
       sumMSq = vec_mulo(sumM, sumM);
       T0_UI = vec_mule(N, *(vector unsigned short*)&sumMM);
       T0_UI = vec_sld(T0_UI, V0_UI, 2);
       sumMM = vec_mulo(N, *(vector unsigned short*)&sumMM);
       sumMM = vec_add(sumMM, T0_UI);
       T0_UI = vec_sub(sumMM, sumMSq); // T0 = (N*SumMM - SumM*SumM).
       varM = vec_ctf(T0_UI, 0);
     }
     /* At each location within the search space, calculate varI, varIM
      * and use these values to calculate the final correlation scores.
      */
     for (int32 yo = 0; yo < 3; yo++) {
       const int32 y0 = (yImgOrigin + yo);
       const int32 y1 = y0 + mdlHeight;
       for (int32 xo = 0; xo < 3; xo++) {
     const int32 x0 = (xImgOrigin + xo)*3;
     const int32 x1 = x0 + mdlWidth*3;
     const uint32 iSumI =
       *(_imgMom->imgSumPtr(x1, y1)) - *(_imgMom->imgSumPtr(x0, y1)) +
       *(_imgMom->imgSumPtr(x0, y0)) - *(_imgMom->imgSumPtr(x1, y0));
     _vectorSumPtr[3 - xo] = iSumI;
     const uint32 iSumII =
       *(_imgMom->imgSumSqPtrLow(x1+1,y1))-*(_imgMom->imgSumSqPtrLow(x0+1,y1)) +
       *(_imgMom->imgSumSqPtrLow(x0+1,y0))-*(_imgMom->imgSumSqPtrLow(x1+1,y0));
     _vectorSumSqPtr[3 - xo] = iSumII;
       } // End of: for (int32 xo = 0; xo < 3; xo++) {
       vector unsigned short sumI;
       /* Calculate (N*SumII - SumI*SumI).
        */
       {
     vector unsigned int sumII, sumISq;
     sumI = *(vector unsigned short*)_vectorSumPtr;
     sumII = *(vector unsigned int*)_vectorSumSqPtr;
     sumISq = vec_mulo(sumI, sumI);
     T0_UI = vec_mule(N, *(vector unsigned short*)&sumII);
     T0_UI = vec_sld(T0_UI, V0_UI, 2);
     sumII = vec_mulo(N, *(vector unsigned short*)&sumII);
     sumII = vec_add(sumII, T0_UI);
     T0_UI = vec_sub(sumII, sumISq);
     varI = vec_ctf(T0_UI, 0);
       }
       /* Calculate (N*SumIM - SumI*SumM).
        */
       {
     vector unsigned int sumIM, sumISumM;
     sumISumM = vec_mulo(sumI, sumM);
     sumIM = *(vector unsigned int*)(_destSpacePtr + 4*yo);
     T0_UI = vec_mule(N, *(vector unsigned short*)&sumIM);
     T0_UI = vec_sld(T0_UI, V0_UI, 2);
     sumIM = vec_mulo(N, *(vector unsigned short*)&sumIM);
     sumIM = vec_add(sumIM, T0_UI);
     T0_UI = vec_sub(sumIM, sumISumM);
     varIM = vec_ctf(T0_SI, 0);
       }
       vector bool int mask;
       /* Set T0_F = (N*sumII - (sumI*sumI)) * (N*sumMM - (sumM*sumM))
        *     T1_F = (N*sumIM - (sumI*sumM)) * (N*sumIM - (sumI*sumM))
        */
       T0_F = vec_madd(varI, varM, V0_F);
       mask = vec_cmpgt(T0_F, V0_F); // Used to mask out any division's by zero
       T1_F = vec_madd(varIM, varIM, V0_F);
       /* Now ready to perform division using reciprocal estimate
        * followed by "Newton-Raphson" refinement, as specified in
        * Altivec PEM section 4.2.2.1.1.
        */
       vector float f0, f1;
       f0 = vec_re(T0_F);
       f1 = vec_nmsub(f0, T0_F, vf1);
       f0 = vec_madd(f0, f1, f0);
       f1 = vec_nmsub(f0, T0_F, vf1);
       f1 = vec_madd(f0, f1, f0);
       f0 = vec_madd(T1_F, f1, V0_F);
       T1_F = vec_nmsub(T0_F, f0, T1_F);
       T0_F = vec_madd(T1_F, f1, f0);
       T0_F = vec_and(T0_F, mask); // If denominator was 0, return 0
       T0_F = vec_min(T0_F, vf1); // Clamp upper bound to <= 1.0
       *(vector float*)_vectorSumPtr = T0_F;
       res.score[yo][0] = *((float*)_vectorSumPtr + 3);
       res.score[yo][1] = *((float*)_vectorSumPtr + 2);
       res.score[yo][2] = *((float*)_vectorSumPtr + 1);
     } // End of: for (int32 yo = 0; yo < 3; yo++) {
   } // End of: "Now calculate correlation scores ..." block
 #endif
 }
void rcPointCorrelation::gen5by5Space (const rcRect & srchSpace, const rcIPair & modelOrigin, rsCorr5by5Point & res) const
Definition at line 1063 of file rc_point_corr.cpp.
References _destSpacePtr, _imgMom, _imgWin, _iRowBase, _iRowUpdate, _mdlMom, _mdlWin, _mRowBase, _mRowUpdate, _resultPtr, _vectorSumPtr, _vectorSumSqPtr, genSpace(), rcWindow::height(), rcRectangle< T >::height(), rcMomentGenerator::imgSumPtr(), rcMomentGenerator::imgSumSqPtrLow(), N, rmAssert, rsCorr5by5Point::score, rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
 {
 #ifndef __ppc__
     vector<vector<float> > results (5);
     for (uint32 i = 0; i < 5; i++)
         results[i].resize (5);
     genSpace(srchSpace, modelOrigin, results, 2);
     for (uint32 j = 0; j < 5; j++)
         for (uint32 i = 0; i < 5; i++)
         res.score[j][i] = results[j][i];
 #else
   /* Validate the current state of the object and the inputs.
    * Calculate model and image position and size.
    */
   rmAssert(_imgMom);
   rmAssert(_mdlMom);
   const int32 xImgOrigin = srchSpace.x();
   const int32 yImgOrigin = srchSpace.y();
   const int32 imgWidth = srchSpace.width();
   const int32 imgHeight = srchSpace.height();
   rmAssert(imgWidth <= 16);
   rmAssert(imgHeight <= 16);
   const int32 xSpcBound = xImgOrigin + imgWidth;
   const int32 ySpcBound = yImgOrigin + imgHeight;
   rmAssert(xImgOrigin < xSpcBound);
   rmAssert(xSpcBound <= _imgWin.width());
   rmAssert(yImgOrigin < ySpcBound);
   rmAssert(ySpcBound <= _imgWin.height());
   /* For 5x5 correlation space, model dimensions are always (-4,-4)
    * of the search space dimensions.
    */
   const int32 mdlWidth = imgWidth - 4;
   const int32 mdlHeight = imgHeight - 4;
   rmAssert(mdlWidth > 0);
   rmAssert(mdlHeight > 0);
   const int32 xMdlOrigin = modelOrigin.x();
   const int32 yMdlOrigin = modelOrigin.y();
   const int32 xMdlBound = xMdlOrigin + mdlWidth;
   const int32 yMdlBound = yMdlOrigin + mdlHeight;
   rmAssert(xMdlOrigin < xMdlBound);
   rmAssert(xMdlBound <= _mdlWin.width());
   rmAssert(yMdlOrigin < yMdlBound);
   rmAssert(yMdlBound <= _mdlWin.height());
   /* Request is valid. Calculate IM values for all the locations
    * within the search space.
    */
   vector short t0, t1, v0 = vec_splat_s16(0);
   vector unsigned char mModelPerm, mAlignPerm, iAlignPerm, rotatePerm;
   unsigned char* img =
     (unsigned char*)(_iRowBase + _iRowUpdate*yImgOrigin + xImgOrigin);
   vector unsigned char* iPtr =  (vector unsigned char*)img;
   unsigned char* mdl =
     (unsigned char*)(_mRowBase + _mRowUpdate*yMdlOrigin + xMdlOrigin);
   vector unsigned char* mPtr = (vector unsigned char*)mdl;
   vector signed int* destP = (vector signed int*)_destSpacePtr;
   const bool icb = (((int)iPtr & 0xF) + imgWidth) > 16;
   const bool mcb = (((int)mPtr & 0xF) + mdlWidth) > 16;
   /* Note: In the following comments, sample values are given based on the
    * assumption that:
    *
    *    mdlWidth = 5
    *    For mcb == true case: Address of mdl == 12 MOD 16
    *    For mcb == false case: Address of mdl == 10 MOD 16
    */
   iAlignPerm = vec_lvsl(0, img);
   T0_UC = vec_splat_u8(3);               // T0= 03030303030303030303030303030303
   T0_UC = vec_sl(T0_UC, T0_UC);          // T0= 18181818181818181818181818181818
   T1_UC = vec_lvsr(mdlWidth, (int*)0);   // T1= 0B0C0D0E0F101112131415161718191A
   T0_UC = vec_perm(V0_UC, T0_UC, T1_UC); // T0= 00000000001818181818181818181818
   if (mcb) {
     mAlignPerm = vec_lvsl(0, mdl);       // AP= 0C0D0E0F101112131415161718191A1B
     T1_UC = vec_lvsl(0, (int*)0);        // T1= 000102030405060708090A0B0C0D0E0F
     mModelPerm = vec_or(T1_UC, T0_UC);   // MP= 00010203041X1X1X1X1X1X1X1X1X1X1X
   }
   else {
     mAlignPerm = vec_splat_u8(0);        // Quiet compiler
     T1_UC = vec_lvsl(0, mdl);            // T1= 0A0B0C0D0E0F10111213141516171819
     mModelPerm = vec_or(T1_UC, T0_UC);   // MP= 0A0B0C0D0E1X1X1X1X1X1X1X1X1X1X1X
   }
   rotatePerm = vec_lvsr(4,(int*)0);
   if (icb) {
     if (mcb) {
       if (mdlHeight > 4) {
     GEN_LRG_5X5_SPACE(LOADI_CB, LOADM_CB, mdlHeight, ICBMCB);
       }
       else {
     GEN_SML_5X5_SPACE(LOADI_CB, LOADM_CB, mdlHeight);
       }
     }
     else {
       if (mdlHeight > 4) {
     GEN_LRG_5X5_SPACE(LOADI_CB, LOADM, mdlHeight, ICBM);
       }
       else {
     GEN_SML_5X5_SPACE(LOADI_CB, LOADM, mdlHeight);
       }
     }
   }
   else {
     if (mcb) {
       if (mdlHeight > 4) {
     GEN_LRG_5X5_SPACE(LOADI, LOADM_CB, mdlHeight, IMCB);
       }
       else {
     GEN_SML_5X5_SPACE(LOADI, LOADM_CB, mdlHeight);
       }
     }
     else {
       if (mdlHeight > 4) {
     GEN_LRG_5X5_SPACE(LOADI, LOADM, mdlHeight, IM);
       }
       else {
     GEN_SML_5X5_SPACE(LOADI, LOADM, mdlHeight);
       }
     }
   } // End of: if (icb) ... else ...
   /* Now calculate correlation scores for model and image at all
    * locations within the search space.
    */
   {
     vector unsigned short N, sumM;
     vector float varM, varI, varIM, vf1;
     T0_UI = vec_splat_u32(1);
     vf1 = vec_ctf(T0_UI, 0);
     /* Calculate and store N in vector.
      */
     *(uint16*)_vectorSumPtr = (uint16)(mdlWidth*mdlHeight);
     N = *(vector unsigned short*)_vectorSumPtr;
     N = vec_splat(N, 0);
     /* Calculate and store sumM and varM in vectors.
      */
     {
       const int32 x0 = xMdlOrigin*3;
       const int32 y0 = yMdlOrigin;
       const int32 x1 = x0 + mdlWidth*3;
       const int32 y1 = y0 + mdlHeight;
       const uint16 iSumM =
     (uint16)(*(_mdlMom->imgSumPtr(x1, y1)) - *(_mdlMom->imgSumPtr(x0, y1)) +
            *(_mdlMom->imgSumPtr(x0, y0)) - *(_mdlMom->imgSumPtr(x1, y0)));
       *(uint16*)_vectorSumPtr = iSumM;
       sumM = *(vector unsigned short*)_vectorSumPtr;
       sumM = vec_splat(sumM, 0);
       vector unsigned int sumMM, sumMSq;
       const uint32 iSumMM =
     *(_mdlMom->imgSumSqPtrLow(x1+1,y1)) - *(_mdlMom->imgSumSqPtrLow(x0+1,y1)) +
     *(_mdlMom->imgSumSqPtrLow(x0+1,y0)) - *(_mdlMom->imgSumSqPtrLow(x1+1,y0));
       *_vectorSumPtr = iSumMM;
       sumMM = *(vector unsigned int*)_vectorSumPtr;
       sumMM = vec_splat(sumMM, 0);
       /* Calculate (N*SumMM - SumM*SumM).
        *
        * Note that SumM always fits in 16 bits, so the multiply can be
        * done in a single instruction. SumMM can go over 16 bits, so
        * the multiply is done as a pair of 16 bit multiplies, a 16 bit
        * shift, and an add.
        */
       sumMSq = vec_mulo(sumM, sumM);
       T0_UI = vec_mule(N, *(vector unsigned short*)&sumMM);
       T0_UI = vec_sld(T0_UI, V0_UI, 2);
       sumMM = vec_mulo(N, *(vector unsigned short*)&sumMM);
       sumMM = vec_add(sumMM, T0_UI);
       T0_UI = vec_sub(sumMM, sumMSq); // T0_UI = (N*SumMM - SumM*SumM).
       varM = vec_ctf(T0_UI, 0);
     }
   /* At each location within the search space, calculate varI, varIM
    * and use these values to calculate the final correlation scores.
    */
     const int32 x0Start = xImgOrigin*3;
     const int32 x1Start = x0Start + mdlWidth*3;
     for (int32 yo = 0; yo < 5; yo++) {
       const int32 y0 = (yImgOrigin + yo);
       const int32 y1 = y0 + mdlHeight;
       int32 x0Cur = x0Start;
       int32 x1Cur = x1Start;
       for (int32 xo = 0; xo < 5; xo++) {
     const int32 x0 = x0Cur, x1 = x1Cur;
     const uint32 iSumI =
       *(_imgMom->imgSumPtr(x1, y1)) - *(_imgMom->imgSumPtr(x0, y1)) +
       *(_imgMom->imgSumPtr(x0, y0)) - *(_imgMom->imgSumPtr(x1, y0));
     _vectorSumPtr[7 - xo] = iSumI;
     const uint32 iSumII =
       *(_imgMom->imgSumSqPtrLow(x1+1,y1))-*(_imgMom->imgSumSqPtrLow(x0+1,y1)) +
       *(_imgMom->imgSumSqPtrLow(x0+1,y0))-*(_imgMom->imgSumSqPtrLow(x1+1,y0));
     _vectorSumSqPtr[7 - xo] = iSumII;
     x0Cur += 3;
     x1Cur += 3;
       } // End of: for (int32 xo = 0; xo < 5; xo++) {
       /* On the last 2 rows 2 set of results will be processed.
        * Otherwise the 5th I, II, IM on the row is saved for future
        * use and only one set of results is processed.
        */
       int32 loopCnt = 2;
       if (yo < 3) {
     loopCnt = 1;
     _vectorSumSqPtr[yo] = _vectorSumSqPtr[3];
     _vectorSumPtr[yo] = _vectorSumPtr[3];
     _destSpacePtr[3*8 + yo] = _destSpacePtr[yo*8 + 3];
       }
       int32 index = 4;
       for (int32 loop = 0; loop < loopCnt; loop++, (index = 0)) {
     vector unsigned short sumI;
     /* Calculate (N*SumII - SumI*SumI).
      */
     {
       vector unsigned int sumII, sumISq;
       sumI = *(vector unsigned short*)(_vectorSumPtr + index);
       sumII = *(vector unsigned int*)(_vectorSumSqPtr + index);
       sumISq = vec_mulo(sumI, sumI);
       T0_UI = vec_mule(N, *(vector unsigned short*)&sumII);
       T0_UI = vec_sld(T0_UI, V0_UI, 2);
       sumII = vec_mulo(N, *(vector unsigned short*)&sumII);
       sumII = vec_add(sumII, T0_UI);
       T0_UI = vec_sub(sumII, sumISq);
       varI = vec_ctf(T0_UI, 0);
     }
     /* Calculate (N*SumIM - SumI*SumM).
      */
     {
       vector unsigned int sumIM, sumISumM;
       sumISumM = vec_mulo(sumI, sumM);
       sumIM = *(vector unsigned int*)(_destSpacePtr + 8*yo + index);
       T0_UI = vec_mule(N, *(vector unsigned short*)&sumIM);
       T0_UI = vec_sld(T0_UI, V0_UI, 2);
       sumIM = vec_mulo(N, *(vector unsigned short*)&sumIM);
       sumIM = vec_add(sumIM, T0_UI);
       T0_UI = vec_sub(sumIM, sumISumM);
       varIM = vec_ctf(T0_SI, 0);
     }
     vector bool int mask;
     /* Set T0_F = (N*sumII - (sumI*sumI)) * (N*sumMM - (sumM*sumM))
      *     T1_F = (N*sumIM - (sumI*sumM)) * (N*sumIM - (sumI*sumM))
      */
     T0_F = vec_madd(varI, varM, V0_F);
     mask = vec_cmpgt(T0_F, V0_F); // Used to mask out any division's by zero
     T1_F = vec_madd(varIM, varIM, V0_F);
     /* Now ready to perform division using reciprocal estimate
      * followed by "Newton-Raphson" refinement, as specified in
      * Altivec PEM section 4.2.2.1.1.
      */
     vector float f0, f1;
     f0 = vec_re(T0_F);
     f1 = vec_nmsub(f0, T0_F, vf1);
     f0 = vec_madd(f0, f1, f0);
     f1 = vec_nmsub(f0, T0_F, vf1);
     f1 = vec_madd(f0, f1, f0);
     f0 = vec_madd(T1_F, f1, V0_F);
     T1_F = vec_nmsub(T0_F, f0, T1_F);
     T0_F = vec_madd(T1_F, f1, f0);
     T0_F = vec_and(T0_F, mask); // If denominator was 0, return 0
     T0_F = vec_min(T0_F, vf1); // Clamp upper bound to <= 1.0
     *(vector float*)_resultPtr = T0_F;
     if (loop == 0) {
       res.score[yo][0] = *((float*)_resultPtr + 3);
       res.score[yo][1] = *((float*)_resultPtr + 2);
       res.score[yo][2] = *((float*)_resultPtr + 1);
       res.score[yo][3] = *((float*)_resultPtr + 0);
     }
     else if (yo == 3) {
       res.score[0][4] = *((float*)_resultPtr + 0);
       res.score[1][4] = *((float*)_resultPtr + 1);
       res.score[2][4] = *((float*)_resultPtr + 2);
       res.score[3][4] = *((float*)_resultPtr + 3);
     }
     else
       res.score[4][4] = *((float*)_resultPtr + 3);
       } // End of: for (int32 loop = 0; loop < loopCnt; loop++) {
     } // End Of: for (int32 yo = 0; yo < 5; yo++) {
   } // End of: "Now calculate correlation scores ..." block
 #endif
 }
void rcPointCorrelation::genSpace (const rcRect & srchSpace, const rcIPair & modelOrigin, vector< vector< float > > & res, const int32 acRadius) const
Definition at line 1376 of file rc_point_corr.cpp.
References _imgWin, _mdlWin, rcWindow::height(), rcRectangle< T >::height(), rcCorr::r(), rfCorrelate(), rmAssert, rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
Referenced by gen3by3Space(), and gen5by5Space().
 {
   rmAssert(acRadius > 0);
   const int32 diameter = acRadius*2 + 1;
   const int32 xImgOrigin = srchSpace.x();
   const int32 yImgOrigin = srchSpace.y();
   rmAssert(srchSpace.width() > (diameter-1));
   rmAssert(srchSpace.height() > (diameter-1));
   const int32 imgWidth = srchSpace.width();
   const int32 imgHeight = srchSpace.height();
   const int32 xSpcBound = xImgOrigin + imgWidth;
   const int32 ySpcBound = yImgOrigin + imgHeight;
   rmAssert(xImgOrigin < xSpcBound);
   rmAssert(xSpcBound <= _imgWin.width());
   rmAssert(yImgOrigin < ySpcBound);
   rmAssert(ySpcBound <= _imgWin.height());
   const int32 xMdlOrigin = modelOrigin.x();
   const int32 yMdlOrigin = modelOrigin.y();
   /* For NxN correlation space, model dimensions are always
    * (diameter-1,diameter-1) of the search space dimensions.
    */
   const int32 mdlWidth = imgWidth - (diameter-1);
   const int32 mdlHeight = imgHeight - (diameter-1);
   const int32 xMdlBound = xMdlOrigin + mdlWidth;
   const int32 yMdlBound = yMdlOrigin + mdlHeight;
   rmAssert(xMdlOrigin < xMdlBound);
   rmAssert(xMdlBound <= _mdlWin.width());
   rmAssert(yMdlOrigin < yMdlBound);
   rmAssert(yMdlBound <= _mdlWin.height());
   rmAssert((int32)(res.size()) >= diameter);
   for (int32 i = 0; i < diameter; i++)
     rmAssert((int32)(res[i].size()) >= diameter);
   /* Request is valid. Calculate result space.
    */
   rsCorrParams cp;
   rcCorr cr;
   rcWindow model(_mdlWin, xMdlOrigin, yMdlOrigin, mdlWidth, mdlHeight);
   for (int32 y = 0; y < diameter; y++)
     for (int32 x = 0; x < diameter; x++) {
       rcWindow image(_imgWin, xImgOrigin + x, yImgOrigin + y,
              mdlWidth, mdlHeight);
       rfCorrelate(image, model, cp, cr);
       res[y][x] = cr.r();
     }
 }
void rcPointCorrelation::update (rcWindow imgWin, rcWindow mdlWin, const rcMomentGenerator & imgMom, const rcMomentGenerator & mdlMom)
Definition at line 747 of file rc_point_corr.cpp.
References _imgMom, rcMomentGenerator::_imgSq, _imgWin, _iRowBase, _iRowUpdate, _mdlMom, _mdlWin, _mRowBase, _mRowUpdate, rcMomentGenerator::_type, rcMomentGenerator::eMoment2D, rcWindow::height(), rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), VALID_2D_MOM_INT_HEIGHT, VALID_2D_MOM_INT_WIDTH, and rcWindow::width().
 {
   rmAssert(imgMom._type == rcMomentGenerator::eMoment2D);
   rmAssert(mdlMom._type == rcMomentGenerator::eMoment2D);
   rmAssert(VALID_2D_MOM_INT_WIDTH(imgWin.width()) == imgMom._imgSq.width());
   rmAssert(VALID_2D_MOM_INT_HEIGHT(imgWin.height())  == imgMom._imgSq.height());
   rmAssert(VALID_2D_MOM_INT_WIDTH(mdlWin.width()) == mdlMom._imgSq.width());
   rmAssert(VALID_2D_MOM_INT_HEIGHT(mdlWin.height())  == mdlMom._imgSq.height());
   _imgWin = imgWin;
   _iRowBase = _imgWin.rowPointer(0);
   _iRowUpdate = _imgWin.rowUpdate();
   _mdlWin = mdlWin;
   _mRowBase = _mdlWin.rowPointer(0);
   _mRowUpdate = _mdlWin.rowUpdate();
   _imgMom = &imgMom;
   _mdlMom = &mdlMom;
 }
void rcPointCorrelation::update (rcWindow imgWin, rcWindow mdlWin)
Definition at line 768 of file rc_point_corr.cpp.
References _imgMom, _imgWin, _iRowBase, _iRowUpdate, _mdlMom, _mdlWin, _mRowBase, _mRowUpdate, rcWindow::height(), rcWindow::isBound(), rmAssert, rcWindow::rowPointer(), and rcWindow::rowUpdate().
 {
   rmAssert(imgWin.isBound());
   rmAssert((mdlWin.height()));
   _imgWin = imgWin;
   _iRowBase = _imgWin.rowPointer(0);
   _iRowUpdate = _imgWin.rowUpdate();
   _mdlWin = mdlWin;
   _mRowBase = _mdlWin.rowPointer(0);
   _mRowUpdate = _mdlWin.rowUpdate();
   _imgMom = _mdlMom = 0;
 }
Member Data Documentation
unsigned char* rcPointCorrelation::_destSpaceBase private
Definition at line 157 of file rc_point_corr.h.
Referenced by rcPointCorrelation(), and ~rcPointCorrelation().
uint32* rcPointCorrelation::_destSpacePtr private
Definition at line 158 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and rcPointCorrelation().
int32 rcPointCorrelation::_destSpaceSz private
Definition at line 162 of file rc_point_corr.h.
Referenced by rcPointCorrelation().
const rcMomentGenerator* rcPointCorrelation::_imgMom private
Definition at line 156 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and update().
rcWindow rcPointCorrelation::_imgWin private
Definition at line 153 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), genSpace(), and update().
unsigned char* rcPointCorrelation::_iRowBase private
Definition at line 154 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and update().
int32 rcPointCorrelation::_iRowUpdate private
Definition at line 155 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and update().
const rcMomentGenerator * rcPointCorrelation::_mdlMom private
Definition at line 156 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and update().
rcWindow rcPointCorrelation::_mdlWin private
Definition at line 153 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), genSpace(), and update().
unsigned char * rcPointCorrelation::_mRowBase private
Definition at line 154 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and update().
int32 rcPointCorrelation::_mRowUpdate private
Definition at line 155 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and update().
uint32* rcPointCorrelation::_resultPtr private
Definition at line 161 of file rc_point_corr.h.
Referenced by gen5by5Space(), and rcPointCorrelation().
uint32* rcPointCorrelation::_vectorSumPtr private
Definition at line 159 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and rcPointCorrelation().
uint32* rcPointCorrelation::_vectorSumSqPtr private
Definition at line 160 of file rc_point_corr.h.
Referenced by gen3by3Space(), gen5by5Space(), and rcPointCorrelation().
The documentation for this class was generated from the following files:
include/analysis/rc_point_corr.h
src/analysis/code/rc_point_corr.cpp