Visible: rcFeature Class Reference
rcFeature Class Reference
#include <include/analysis/rc_dbdt.h>
Public Types
enum { notAvailable = -3 }
Public Member Functions
rcFeature ()
rcFeature (const double &quality, const rc2Dvector &p, const rcDPair &ctr, const rcIRect &target=mStdTargetSize, int32 speed=1)
rc2Dvector & pos ()
const rc2Dvector & pos () const
rcUIPair & polar ()
const rcUIPair & polar () const
rcIPair & in ()
const rcIPair & in () const
rcDPair & origin ()
const rcDPair & origin () const
double & quality ()
const double & quality () const
rcIRect & target ()
const rcIRect & target () const
bool operator== (const rcFeature &r) const
bool operator!= (const rcFeature &r) const
bool operator< (const rcFeature &r) const
rcFeature ()
template<class T >
rcFeature (const T length, rcRadian d)
template<class T >
rcFeature (const rc2dVector< T > &v)
template<class T >
rcFeature (const T x, const T y)
rcFeature (rcRadian d)
rcFeature (rcAngle8 d)
bool hasPolar (void) const
rc2Fvector pos () const
const rcPair< rcFixed16 > & pos16 () const
void polar (rcFixed16 &len, rcRadian &angle) const
rcAngle8 octants (int32 &dX, int32 &dY) const
void polar (double &len, rcRadian &angle) const
rcRadian angle () const
float len () const
rcFeature operator* (float fm) const
rcFeature & operator*= (float fm)
float operator* (const rcFeature &other) const
rcFeature project (const rcFeature &other) const
float length () const
bool operator== (const rcFeature &r) const
bool operator!= (const rcFeature &r) const
bool operator< (const rcFeature &r) const
Static Public Attributes
static const float rcFeatureMinLength = 1.0f / (1 << rcFxPrecision)
static const float oneOverMultConst = 1.0f / (1 << (rcFixed16Precision+rcFixed16Precision))
Private Member Functions
void init ()
Private Attributes
double mQuality
rcIRect mTarget
int32 mSpeed
rc2Dvector mPos
rcUIPair mRT
rcIPair mI
rcDPair mCtr
uint8 mDx
uint8 mDy
uint8 mDr
uint16 miX
uint16 miY
uint16 mQ
rcPair< rcFixed16 > mD
rcFixed16 mQ
Static Private Attributes
static rcIRect mStdTargetSize
Friends
ostream & operator<< (ostream &, const rcFeature &)
rcFeature operator* (float fm, const rcFeature &f)
ostream & operator<< (ostream &o, const rcFeature &f)
Detailed Description
Definition at line 164 of file rc_dbdt.h.
Member Enumeration Documentation
anonymous enum
Enumerator
notAvailable
Definition at line 270 of file rc_motionpath.h.
 { notAvailable = -3};
Constructor & Destructor Documentation
rcFeature::rcFeature () inline
Definition at line 168 of file rc_dbdt.h.
References init().
Referenced by operator*().
 { init (); }
rcFeature::rcFeature (const double & quality, const rc2Dvector & p, const rcDPair & ctr, const rcIRect & target = mStdTargetSize, int32 speed = 1) inline
Definition at line 170 of file rc_dbdt.h.
References mCtr, mI, mPos, mQuality, mSpeed, mTarget, quality(), rfRound(), target(), rcPair< T >::x(), and rcPair< T >::y().
   {
     mPos = p; mCtr = ctr;
     mTarget = target;
     mSpeed = speed;
     mQuality = quality;
     static int32 dummy;
     mI.x() = rfRound (ctr.x(), dummy);
     mI.y() = rfRound (ctr.y(), dummy);
   }
rcFeature::rcFeature () inline
Definition at line 274 of file rc_motionpath.h.
References mD, rcPair< T >::x(), and rcPair< T >::y().
                : mQ (notAvailable)
   {
     mD.x() = rcFixed16(0.0);
     mD.y() = rcFixed16(0.0);
   }
template<class T > rcFeature::rcFeature (const T length, rcRadian d) inline
Definition at line 282 of file rc_motionpath.h.
References cos(), mD, mQ, sin(), rcPair< T >::x(), and rcPair< T >::y().
   {
     mD.x() = rcFixed16 (sin (d));
     mD.y() = rcFixed16 (cos (d));
     mQ = rcFixed16 (length);
   }
template<class T > rcFeature::rcFeature (const rc2dVector< T > & v) inline
Definition at line 290 of file rc_motionpath.h.
References rc2dVector< T >::isLenNull(), rc2dVector< T >::len(), mD, mQ, notAvailable, rc2dVector< T >::unit(), rcPair< T >::x(), and rcPair< T >::y().
   {
     if (!v.isLenNull())
       {
     mQ = rcFixed16 (v.len());
     mD.x() = rcFixed16(v.unit().x());
     mD.y() = rcFixed16(v.unit().y());
       }
     else
       mQ = notAvailable;
   }
template<class T > rcFeature::rcFeature (const T x, const T y) inline
Definition at line 303 of file rc_motionpath.h.
References rc2dVector< T >::isLenNull(), rc2dVector< T >::isNull(), rc2dVector< T >::len(), mD, mQ, notAvailable, rc2dVector< T >::unit(), rcPair< T >::x(), and rcPair< T >::y().
   {
     rc2dVector<T> v (x, y);
     if (v.isNull())
       {
     mD.x() = mD.y() = rcFixed16 (0);
     mQ = notAvailable;
       }
     else
       {
     mD.x() = rcFixed16(v.unit().x());
     mD.y() = rcFixed16(v.unit().y());
     if (!v.isLenNull())
       mQ = rcFixed16 (v.len());
     else
       mQ = notAvailable;
       }
   }
rcFeature::rcFeature (rcRadian d) inline
Definition at line 324 of file rc_motionpath.h.
References cos(), mD, mQ, sin(), rcPair< T >::x(), and rcPair< T >::y().
   {
     mD.x() = rcFixed16 (sin (d));
     mD.y() = rcFixed16 (cos (d));
     mQ = rcFixed16 (1.0f);
   }
rcFeature::rcFeature (rcAngle8 d) inline
Definition at line 331 of file rc_motionpath.h.
References rcAngle8::basic(), mD, mQ, rcFixed16Precision, rcPair< T >::x(), and rcPair< T >::y().
   {
     static const int16 p (1<<rcFixed16Precision);
     static const int16 dxTable[8] = {  p,  p,  0, -p, -p, -p,  0,  p};
     static const int16 dyTable[8] = {  0,  p,  p,  p,  0, -p, -p, -p};
     int32 ti = ((d.basic() + 16) / 32 ) % 8;
     mD.x() = rcFixed16 (dxTable[ti]);
     mD.y() = rcFixed16 (dyTable[ti]);
     mQ = rcFixed16 (1.0f);
   }
Member Function Documentation
rcRadian rcFeature::angle () const inline
Definition at line 416 of file rc_motionpath.h.
References len(), and polar().
   {
     rcFixed16 len;
     rcRadian angle;
     polar (len, angle);
     return angle;
   }
bool rcFeature::hasPolar (void) const inline
Definition at line 345 of file rc_motionpath.h.
References mD, mQ, notAvailable, rcPair< T >::x(), and rcPair< T >::y().
   {
     return (mQ != notAvailable || mD.x() != 0 || mD.y() != 0);
   }
rcIPair& rcFeature::in () inline
Definition at line 195 of file rc_dbdt.h.
References mI.
Referenced by operator<().
 {return mI;}
const rcIPair& rcFeature::in () const inline
Definition at line 196 of file rc_dbdt.h.
References mI.
 {return mI;}
void rcFeature::init () inline private
Definition at line 217 of file rc_dbdt.h.
References mCtr, mI, mPos, mQuality, mRT, mSpeed, mStdTargetSize, mTarget, and rmStdSpeed.
Referenced by rcFeature().
   {
     mPos = rc2Dvector ();
     mRT = rcUIPair (0,0);
     mI = rcIPair (0, 0);
     mCtr = rcDPair (0., 0.);
     mTarget = mStdTargetSize;
     mSpeed = rmStdSpeed;
     mQuality = 0.0;
   }
float rcFeature::len () const inline
Definition at line 427 of file rc_motionpath.h.
References length().
Referenced by angle().
   {
     return length();
   }
float rcFeature::length () const inline
Definition at line 447 of file rc_motionpath.h.
References mQ.
Referenced by len().
   {
     if (mQ >=0)
       return mQ.real ();
     else return 0;
   }
rcAngle8 rcFeature::octants (int32 & dX, int32 & dY) const inline
Definition at line 386 of file rc_motionpath.h.
References rcAngle8::basic(), rcFixed16::basic(), mD, rcFeatureMinLength, rfFxPolarize(), rcPair< T >::x(), and rcPair< T >::y().
   {
     static const int32 dxTable[8] = {  1,  1,  0, -1, -1, -1,  0,  1};
     static const int32 dyTable[8] = {  0,  1,  1,  1,  0, -1, -1, -1};
     int32 r (mD.x().basic());
     int32 t (mD.y().basic());
     rfFxPolarize (&r, &t);
     rcAngle8 a8 (rcDegree ((double) (t * rcFeatureMinLength)));
     int32 octant = ((a8.basic() + 16) / 32) % 8;
     dX = dxTable[octant];
     dY = dyTable[octant];
     return a8;
   }
bool rcFeature::operator!= (const rcFeature & r) const inline
Definition at line 209 of file rc_dbdt.h.
 { return !(*this == r); }
bool rcFeature::operator!= (const rcFeature & r) const inline
Definition at line 459 of file rc_motionpath.h.
 { return !(*this == r); }
rcFeature rcFeature::operator* (float fm) const
Definition at line 210 of file rc_motionpath.cpp.
References mD, rcFeature(), rcFixed16::real(), rcPair< T >::x(), and rcPair< T >::y().
 {
     return rcFeature (mD.x().real() * fm, mD.y().real() * fm);
 }
float rcFeature::operator* (const rcFeature & other) const
Definition at line 222 of file rc_motionpath.cpp.
References mD, rcFixed16::real(), rcPair< T >::x(), and rcPair< T >::y().
 {
     // dot (inner) product
     return (mD.x().real() * other.mD.x().real() +
             mD.y().real() * other.mD.y().real());
 }
rcFeature & rcFeature::operator*= (float fm)
Definition at line 216 of file rc_motionpath.cpp.
 {
     return *this = *this * fm;
 }
bool rcFeature::operator< (const rcFeature & r) const inline
Definition at line 210 of file rc_dbdt.h.
References in(), mI, rcPair< T >::x(), and rcPair< T >::y().
 { return !(mI.x() < r.in().x() && mI.y() < r.in().y()); }
bool rcFeature::operator< (const rcFeature & r) const inline
Definition at line 460 of file rc_motionpath.h.
References mD, pos16(), rcPair< T >::x(), and rcPair< T >::y().
 { return !(mD.x() < r.pos16().x() && mD.y() < r.pos16().y()); }
bool rcFeature::operator== (const rcFeature & r) const inline
Definition at line 208 of file rc_dbdt.h.
 {return (*this == r); }
bool rcFeature::operator== (const rcFeature & r) const inline
Definition at line 458 of file rc_motionpath.h.
 {return (*this == r); }
rcDPair& rcFeature::origin () inline
Definition at line 197 of file rc_dbdt.h.
References mCtr.
 {return mCtr;}
const rcDPair& rcFeature::origin () const inline
Definition at line 198 of file rc_dbdt.h.
References mCtr.
 {return mCtr;}
rcUIPair& rcFeature::polar () inline
Definition at line 191 of file rc_dbdt.h.
References mRT.
Referenced by angle(), and polar().
 {return mRT;}
const rcUIPair& rcFeature::polar () const inline
Definition at line 192 of file rc_dbdt.h.
References mRT.
 {return mRT;}
void rcFeature::polar (rcFixed16 & len, rcRadian & angle) const inline
Definition at line 370 of file rc_motionpath.h.
References rcFixed16::basic(), mD, rcFeatureMinLength, rfFxPolarize(), rcPair< T >::x(), and rcPair< T >::y().
   {
     int32 r (mD.x().basic());
     int32 t (mD.y().basic());
     rfFxPolarize (&r, &t);
     angle = rcRadian (rcDegree ((double) (t * rcFeatureMinLength)));
     len = rcFixed16 (r);
   }
void rcFeature::polar (double & len, rcRadian & angle) const inline
Definition at line 407 of file rc_motionpath.h.
References polar(), rcFeatureMinLength, rcFixed16::real(), and rmMax.
   {
     rcFixed16 len16;
     polar (len16, angle);
     len = len16.real();
     len = rmMax (rcFeatureMinLength, len);
   }
rc2Dvector& rcFeature::pos () inline
Definition at line 189 of file rc_dbdt.h.
References mPos.
Referenced by rcMotionPath::add().
 {return mPos;}
const rc2Dvector& rcFeature::pos () const inline
Definition at line 190 of file rc_dbdt.h.
References mPos.
 {return mPos;}
rc2Fvector rcFeature::pos () const inline
Definition at line 354 of file rc_motionpath.h.
References rcFixed16::basic(), mD, mQ, oneOverMultConst, rcPair< T >::x(), and rcPair< T >::y().
   {
     return rc2Fvector (mD.x().basic() * mQ.basic(), mD.y().basic() * mQ.basic())
       * oneOverMultConst;
   }
const rcPair<rcFixed16>& rcFeature::pos16 () const inline
Definition at line 365 of file rc_motionpath.h.
References mD.
Referenced by operator<().
 {return mD;}
rcFeature rcFeature::project (const rcFeature & other) const
Definition at line 229 of file rc_motionpath.cpp.
 {
     return ((other * *this) / (*this * *this)) * *this;
 }
double& rcFeature::quality () inline
Definition at line 201 of file rc_dbdt.h.
References mQuality.
Referenced by rcMotionPath::add(), and rcFeature().
 {return mQuality;}
const double& rcFeature::quality () const inline
Definition at line 202 of file rc_dbdt.h.
References mQuality.
 {return mQuality;}
rcIRect& rcFeature::target () inline
Definition at line 205 of file rc_dbdt.h.
References mTarget.
Referenced by rcFeature().
 {return mTarget;}
const rcIRect& rcFeature::target () const inline
Definition at line 206 of file rc_dbdt.h.
References mTarget.
 {return mTarget;}
Friends And Related Function Documentation
rcFeature operator* (float fm, const rcFeature & f) friend
Definition at line 437 of file rc_motionpath.h.
   {
     return f * fm;
   }
ostream& operator<< (ostream & , const rcFeature &) friend
ostream& operator<< (ostream & o, const rcFeature & f) friend
Definition at line 462 of file rc_motionpath.h.
   {
     if (f.hasPolar())
       {
     rcRadian d (f.angle());
     float l = f.length();
     o << d.Double() << " Radians, Length:  " << f.len() << " Q: " << l << endl;
       }
     return o;
   }
Member Data Documentation
rcDPair rcFeature::mCtr private
Definition at line 234 of file rc_dbdt.h.
Referenced by init(), origin(), and rcFeature().
rcPair<rcFixed16> rcFeature::mD private
Definition at line 474 of file rc_motionpath.h.
Referenced by hasPolar(), octants(), operator*(), operator<(), polar(), pos(), pos16(), and rcFeature().
uint8 rcFeature::mDr private
Definition at line 238 of file rc_dbdt.h.
uint8 rcFeature::mDx private
Definition at line 236 of file rc_dbdt.h.
uint8 rcFeature::mDy private
Definition at line 237 of file rc_dbdt.h.
rcIPair rcFeature::mI private
Definition at line 233 of file rc_dbdt.h.
Referenced by in(), init(), operator<(), and rcFeature().
uint16 rcFeature::miX private
Definition at line 239 of file rc_dbdt.h.
uint16 rcFeature::miY private
Definition at line 240 of file rc_dbdt.h.
rc2Dvector rcFeature::mPos private
Definition at line 231 of file rc_dbdt.h.
Referenced by init(), pos(), and rcFeature().
uint16 rcFeature::mQ private
Definition at line 241 of file rc_dbdt.h.
Referenced by hasPolar(), length(), pos(), and rcFeature().
rcFixed16 rcFeature::mQ private
Definition at line 475 of file rc_motionpath.h.
double rcFeature::mQuality private
Definition at line 228 of file rc_dbdt.h.
Referenced by init(), quality(), and rcFeature().
rcUIPair rcFeature::mRT private
Definition at line 232 of file rc_dbdt.h.
Referenced by init(), and polar().
int32 rcFeature::mSpeed private
Definition at line 230 of file rc_dbdt.h.
Referenced by init(), and rcFeature().
rcIRect rcFeature::mStdTargetSize static private
Definition at line 215 of file rc_dbdt.h.
Referenced by init().
rcIRect rcFeature::mTarget private
Definition at line 229 of file rc_dbdt.h.
Referenced by init(), rcFeature(), and target().
const float rcFeature::oneOverMultConst = 1.0f / (1 << (rcFixed16Precision+rcFixed16Precision)) static
Definition at line 272 of file rc_motionpath.h.
Referenced by pos().
const float rcFeature::rcFeatureMinLength = 1.0f / (1 << rcFxPrecision) static
Definition at line 271 of file rc_motionpath.h.
Referenced by octants(), and polar().
The documentation for this class was generated from the following files:
include/analysis/rc_dbdt.h
include/analysis/rc_motionpath.h
src/analysis/code/rc_motionpath.cpp