Visible: rcGlob Class Reference
rcGlob Class Reference
C++ wrapper around the glob() system call.
#include <include/util/rc_fileutils.h>
Public Types
typedef rcGlobIterator const_iterator
STL-style iterator for this container.
typedef int size_type
type returned by size()
Public Member Functions
rcGlob ()
empty ctor – requires that you call push_back() to add some patterns
rcGlob (const std::string &inPattern) throw (std::runtime_error)
create an object with one pattern. You can still call push_back() to add more.
~rcGlob () throw ()
basic dtor – destroys the underlying glob_t
void push_back (const std::string &inPattern) throw (std::runtime_error)
adds a pattern to the list
const_iterator begin () const
returns an iterator to the beginning of the collection
const_iterator end () const
returns an iterator signaling past-the-end value of the collection
int size () const throw ()
returns number of elements in
Static Public Member Functions
static int globErrorHandler (const char *error_path, int error_num)
prints an error message when there's a problem expanding a pattern
Private Member Functions
rcGlob (const rcGlob &)
not implemented
rcGlob & operator= (const rcGlob &)
not implemented
Private Attributes
glob_t glob_
holds the expanded paths in a char**
Detailed Description
C++ wrapper around the glob() system call.
(extracted from my rpm_find_latest project, 2004/04)
It works similar to an STL container: Pass it a list<> of paths and use the iterators to touch each item, as expanded by the system call.
This class is named "rcGlob" because the name "Glob" conflicted with an existing class somewhere (but not within this project).
Definition at line 138 of file rc_fileutils.h.
Member Typedef Documentation
typedef rcGlobIterator rcGlob::const_iterator
STL-style iterator for this container.
Definition at line 142 of file rc_fileutils.h.
typedef int rcGlob::size_type
type returned by size()
Definition at line 145 of file rc_fileutils.h.
Constructor & Destructor Documentation
rcGlob::rcGlob ()
empty ctor – requires that you call push_back() to add some patterns
Definition at line 557 of file rc_fileutils.cpp.
     :
     glob_()
 {
     return ;
} // rcGlob::ctor()
rcGlob::rcGlob (const std::string & inPattern) throw (std::runtime_error)
create an object with one pattern. You can still call push_back() to add more.
Definition at line 566 of file rc_fileutils.cpp.
     :
     glob_()
 {
     push_back( inPattern ) ;
     return ;
} // rcGlob::ctor(const std::string&)
rcGlob::~rcGlob () throw ()
basic dtor – destroys the underlying glob_t
Definition at line 578 of file rc_fileutils.cpp.
References glob_.
 {
     globfree( &glob_ ) ;
     return ;
 } // rcGlob::dtor
rcGlob::rcGlob (const rcGlob &) private
not implemented
Member Function Documentation
rcGlob::const_iterator rcGlob::begin (void) const
returns an iterator to the beginning of the collection
Definition at line 615 of file rc_fileutils.cpp.
References glob_.
{
     rcGlob::const_iterator result( glob_.gl_pathv ) ;
     return( result ) ;
 } // rcGlob::begin()
rcGlob::const_iterator rcGlob::end (void) const
returns an iterator signaling past-the-end value of the collection
Definition at line 623 of file rc_fileutils.cpp.
{
     rcGlob::const_iterator result ;
     return( result ) ;
 } // rcGlob::end()
int rcGlob::globErrorHandler (const char * error_path, int error_num) static
prints an error message when there's a problem expanding a pattern
Definition at line 543 of file rc_fileutils.cpp.
References endl().
Referenced by push_back().
{
     std::cerr << "Unable to traverse directory \"" << error_path << "\": " << std::strerror( error_num ) << std::endl ;
     /*
     return something nonzero to cause
     glob() to halt processing with a
     GLOB_ABORT value
     */
     return( 0 ) ;
 } // rcGlob::globErrorHandler()
rcGlob& rcGlob::operator= (const rcGlob &) private
not implemented
void rcGlob::push_back (const std::string & inPattern) throw (std::runtime_error)
adds a pattern to the list
Calling this invalidates any existing iterators.
Exceptions
std::runtime_error when the pattern doesn't expand (i.e. the underlying glob() call fails)
Definition at line 589 of file rc_fileutils.cpp.
References globErrorHandler().
 {
     /*
     the glob() call both initiates a glob_t object and, when using
     the GLOB_DOOFFS and GLOB_APPEND flags, appends additional matches
     to the match list (glob_t.gl_pathv).
     */
     int globResult = glob(
         inPattern.c_str() ,
         GLOB_MARK | GLOB_DOOFFS | GLOB_APPEND ,
         rcGlob::globErrorHandler ,
         &glob_
     ) ;
     if( 0 != globResult ){
         throw( std::runtime_error( "Encountered error expanding pattern" ) ) ;
     }
     return ;
 } // rcGlob::push_back()
rcGlob::size_type rcGlob::size (void) const throw ()
returns number of elements in
Definition at line 628 of file rc_fileutils.cpp.
References glob_.
{
     return( glob_.gl_pathc ) ;
 } // rcGlob::size()
Member Data Documentation
glob_t rcGlob::glob_ private
holds the expanded paths in a char**
Definition at line 183 of file rc_fileutils.h.
Referenced by begin(), size(), and ~rcGlob().
The documentation for this class was generated from the following files:
include/util/rc_fileutils.h
src/util/code/rc_fileutils.cpp