Visible: rcTrack Class Reference
rcTrack Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcTrack ()
virtual rcTrackType getTrackType (void)=0
virtual const char * getTag (void)=0
virtual const char * getName (void)=0
virtual const char * getDescription (void)=0
virtual uint32 getSizeLimit () const =0
virtual const char * getDisplayFormatString (void)=0
virtual rcTimestamp getTrackStart (void)=0
virtual bool isExportable (void)=0
virtual rcTrackSemantics getSemantics (void)=0
virtual rcRect getAnalysisRect (void)=0
Static Public Member Functions
static rcTrackType type (const std::string &name)
static const std::string & name (rcTrackType type)
Detailed Description
Definition at line 354 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcTrack::~rcTrack () inline virtual
Definition at line 358 of file rc_model.h.
 { };
Member Function Documentation
virtual rcRect rcTrack::getAnalysisRect (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcScalarTrackWidget::mousePressEvent(), and rcNativeExporter::produceTracks().
virtual const char* rcTrack::getDescription (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcCSVExporter::exportTracks(), rcNativeExporter::produceTracks(), rcScalarTrackWidget::rcScalarTrackWidget(), and rcCellInfoWidget::updateTrackDisplay().
virtual const char* rcTrack::getDisplayFormatString (void) pure virtual
Implemented in rcTrackImpl.
Referenced by getTrackValue(), rcExporter::init(), rcTimeline::paintScalarScaleMarks(), rcNativeExporter::produceTracks(), and rcScalarTrackWidget::updateTrackDisplay().
virtual const char* rcTrack::getName (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcTrackManager::copyTrackToClipboard(), rcNativeExporter::produceTracks(), rcScalarTrackWidget::rcScalarTrackWidget(), and rcTrackManager::setTrackColor().
virtual rcTrackSemantics rcTrack::getSemantics (void) pure virtual
Implemented in rcTrackImpl.
virtual uint32 rcTrack::getSizeLimit () const pure virtual
Implemented in rcTrackImpl.
Referenced by rcNativeExporter::produceTracks().
virtual const char* rcTrack::getTag (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcTrackManager::displayableTrack(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcImageCanvasGL::getToolTipText(), getTrackValue(), rcExporter::isExportable(), rcTimeline::paintTimeline(), rcNativeExporter::produceTracks(), and rcTrackManager::setTrackEnabled().
virtual rcTimestamp rcTrack::getTrackStart (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcNativeExporter::produceTracks().
virtual rcTrackType rcTrack::getTrackType (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcTrackManager::addTracks(), rcTimeline::checkScalarTrackScales(), rcTrackManager::copyTrackToClipboard(), rcTrackManager::displayableTrack(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), getTrackValue(), rcImageCanvasGL::getTrackValue(), rcExporter::hasValidSegments(), rcTimeline::hasViewableTracks(), rcExporter::init(), rcExporter::isExportable(), rcTrackManager::monitorableTrack(), rcScalarTrackWidget::mousePressEvent(), rcTimeline::paintTimeline(), rcNativeExporter::produceTracks(), rcTrackGroupWidget::rcTrackGroupWidget(), and rcScalarTrackWidget::updateTrackDisplay().
virtual bool rcTrack::isExportable (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcExporter::isExportable(), and rcCellInfoWidget::updateTrackDisplay().
static const std::string& rcTrack::name (rcTrackType type) inline static
Definition at line 400 of file rc_model.h.
References cTrackTypeNames, eMaxTrack, rmAssert, rmDim, and type().
Referenced by rcNativeExporter::produceTracks().
{
         rmAssert( type <= eMaxTrack );
         rmAssert( type < static_cast<int>(rmDim(cTrackTypeNames)) );
         return cTrackTypeNames[type];
     }
static rcTrackType rcTrack::type (const std::string & name) inline static
Definition at line 391 of file rc_model.h.
References cTrackTypeNames, and eMaxTrack.
Referenced by name(), and rcNativeImporter::parseTrack().
{
         // TODO: replace linear search with something faster
         for ( uint32 i = 0; i < eMaxTrack; i++ )
             if ( cTrackTypeNames[i] == name )
                 return static_cast<rcTrackType>(i);
         return eMaxTrack;
     };
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h