Visible: rcMenuChoiceSettingWidget Class Reference
rcMenuChoiceSettingWidget Class Reference
#include <include/visUI/rc_menuchoicesettingwidget.h>
Public Slots
void choiceSelected (int choiceValue)
void settingChanged (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcMenuChoiceSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcMenuChoiceSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Member Functions
int findChoice (float value)
Private Attributes
QComboBox * mWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 9 of file rc_menuchoicesettingwidget.h.
Constructor & Destructor Documentation
rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 19 of file rc_menuchoicesettingwidget.cpp.
References choiceSelected(), rcSettingInfo::getChoice(), rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingInfo::getTag(), rcSettingChoice::getText(), rcSettingWidget::mTopLayout, mWidget, and settingChanged().
     : rcSettingWidget( parent, setting )
 {
   mWidget = new QComboBox( false, this , setting.getTag() );
     int nChoices = setting.getNChoices();
     for (int i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = setting.getChoice( i );
         QString text( choice.getText() );
         // Add one space before text for better layout
         mWidget->insertItem( QString( " %1" )
                              .arg( text ) );
     }
     mTopLayout->addWidget( mWidget );
     mTopLayout->addSpacing( 10 );
     QToolTip::add( mWidget , setting.getDescription() );
     mTopLayout->addStretch();
     // update the combo box with the current value of the setting.
     settingChanged();
     connect( mWidget , SIGNAL( activated( int ) ) , this , SLOT( choiceSelected( int ) ) );
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
 }
rcMenuChoiceSettingWidget::~rcMenuChoiceSettingWidget ()
Definition at line 50 of file rc_menuchoicesettingwidget.cpp.
References mWidget.
 {
      QToolTip::remove( mWidget );
 }
Member Function Documentation
void rcMenuChoiceSettingWidget::choiceSelected (int choiceValue) slot
Definition at line 59 of file rc_menuchoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingChoice::getValue(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcMenuChoiceSettingWidget().
 {
     int nChoices = mSetting.getNChoices();
     if ((choiceIndex >= 0) && (choiceIndex < nChoices))
     {
         rcSettingChoice choice = mSetting.getChoice( choiceIndex );
         mSetting.setValue( choice.getValue() );
     }
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
int rcMenuChoiceSettingWidget::findChoice (float value) private
Definition at line 95 of file rc_menuchoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcSettingInfo::getNChoices(), rcSettingChoice::getValue(), and rcSettingWidget::mSetting.
Referenced by settingChanged().
 {
     int nChoices = mSetting.getNChoices();
     int i;
     for (i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = mSetting.getChoice( i );
         if (choice.getValue() == value)
             break;
     }
     return i;
 }
void rcMenuChoiceSettingWidget::settingChanged (void) slot
Definition at line 74 of file rc_menuchoicesettingwidget.cpp.
References findChoice(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingInfo::getTag(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, mWidget, rcModelDomain::requestInputSource(), and rcSettingWidget::updateWidgetState().
Referenced by rcMenuChoiceSettingWidget().
 {
     float currentValue = mSetting.getValue();
     int nChoices = mSetting.getNChoices();
     int i = findChoice( currentValue );
     if (i < nChoices)
         mWidget->setCurrentItem( i );
     // Update visibility/editability
     updateWidgetState();
     // Hack alert: this is brittle
     // Send request for input source only
     if ( ! strcmp( mSetting.getTag(), "input-source" ) )
         rcModelDomain::getModelDomain()->requestInputSource( currentValue );
 }
Member Data Documentation
QComboBox* rcMenuChoiceSettingWidget::mWidget private
Definition at line 28 of file rc_menuchoicesettingwidget.h.
Referenced by rcMenuChoiceSettingWidget(), settingChanged(), and ~rcMenuChoiceSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_menuchoicesettingwidget.h
src/visible/qt/rc_menuchoicesettingwidget.cpp