Visible: rcScalarSegmentIteratorImpl Class Reference
rcScalarSegmentIteratorImpl Class Reference
Public Member Functions
rcScalarSegmentIteratorImpl (rcScalarTrackImpl *track, const rcTimestamp &position, rcMutex &mutex)
virtual rcTimestamp getSegmentLength (void)
virtual rcTimestamp getSegmentOffset (void)
virtual rcTimestamp getTrackOffset (void)
virtual int32 getSegmentIndex (void)
virtual rcTimestamp getSegmentStart (void)
virtual rcTimestamp getSegmentStartAbsolute (void)
virtual bool hasNextSegment (bool lock)
virtual uint32 getSegmentCount (void)
virtual bool contains (const rcTimestamp &time)
virtual void lock ()
virtual void unlock ()
virtual void reset (bool lock)
virtual void release (void)
virtual rcRect getFocus (void)
virtual void advance (const rcTimestamp &amount, bool lock)
virtual bool advance (int32 offset, bool lock)
virtual double getValue (void)
Public Member Functions inherited from rcScalarSegmentIterator
virtual ~rcScalarSegmentIterator ()
Public Member Functions inherited from rcSegmentIterator
virtual ~rcSegmentIterator ()
Private Member Functions
virtual void setCurrentValue (void)
Private Attributes
rcSegmentIteratorImpl _iter
rcScalarTrackImpl * _track
double _currentValue
Detailed Description
Definition at line 10 of file rc_scalartrackimpl.cpp.
Constructor & Destructor Documentation
rcScalarSegmentIteratorImpl::rcScalarSegmentIteratorImpl (rcScalarTrackImpl * track, const rcTimestamp & position, rcMutex & mutex) inline
Definition at line 13 of file rc_scalartrackimpl.cpp.
References _iter, lock(), rcSegmentIteratorImpl::mutex(), rmAssert, and setCurrentValue().
                                                 : _iter( track, position, mutex ),
                                                   _track( track ),
                                                   _currentValue( 0.0 )
     {
         rcLock lock( _iter.mutex() );
         rmAssert( track );
         setCurrentValue();
     }
Member Function Documentation
virtual void rcScalarSegmentIteratorImpl::advance (const rcTimestamp & amount, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 116 of file rc_scalartrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             } else {
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             }
         }
virtual bool rcScalarSegmentIteratorImpl::advance (int32 offset, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 129 of file rc_scalartrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 bool result = _iter.advanceNoLock( offset );
                 setCurrentValue();
                 return result;
             } else {
                 bool result = _iter.advanceNoLock( offset );
                 setCurrentValue();
                 return result;
             }
         }
virtual bool rcScalarSegmentIteratorImpl::contains (const rcTimestamp & time) inline virtual
Implements rcSegmentIterator.
Definition at line 75 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::contains().
         {
             return _iter.contains( time );
         }
virtual rcRect rcScalarSegmentIteratorImpl::getFocus (void) inline virtual
Implements rcSegmentIterator.
Definition at line 110 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getFocus().
         {
             return _iter.getFocus();
         }
virtual uint32 rcScalarSegmentIteratorImpl::getSegmentCount (void) inline virtual
Implements rcSegmentIterator.
Definition at line 69 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentCount().
         {
             return _iter.getSegmentCount();
         }
virtual int32 rcScalarSegmentIteratorImpl::getSegmentIndex (void) inline virtual
Implements rcSegmentIterator.
Definition at line 45 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentIndex().
         {
             return _iter.getSegmentIndex();
         }
virtual rcTimestamp rcScalarSegmentIteratorImpl::getSegmentLength (void) inline virtual
Implements rcSegmentIterator.
Definition at line 27 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentLength().
         {
             return _iter.getSegmentLength();
         }
virtual rcTimestamp rcScalarSegmentIteratorImpl::getSegmentOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 33 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentOffset().
         {
             return _iter.getSegmentOffset();
         }
virtual rcTimestamp rcScalarSegmentIteratorImpl::getSegmentStart (void) inline virtual
Implements rcSegmentIterator.
Definition at line 51 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStart().
         {
             return _iter.getSegmentStart();
         }
virtual rcTimestamp rcScalarSegmentIteratorImpl::getSegmentStartAbsolute (void) inline virtual
Implements rcSegmentIterator.
Definition at line 57 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStartAbsolute().
         {
             return _iter.getSegmentStartAbsolute();
         }
virtual rcTimestamp rcScalarSegmentIteratorImpl::getTrackOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 39 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getTrackOffset().
         {
             return _iter.getTrackOffset();
         }
virtual double rcScalarSegmentIteratorImpl::getValue (void) inline virtual
Implements rcScalarSegmentIterator.
Definition at line 146 of file rc_scalartrackimpl.cpp.
References _currentValue.
         {
             return _currentValue;
         }
virtual bool rcScalarSegmentIteratorImpl::hasNextSegment (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 63 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::hasNextSegment().
         {
             return _iter.hasNextSegment( lock );
         }
virtual void rcScalarSegmentIteratorImpl::lock () inline virtual
Implements rcSegmentIterator.
Definition at line 81 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::lock().
Referenced by advance(), and rcScalarSegmentIteratorImpl().
         {
             _iter.lock();
         }
virtual void rcScalarSegmentIteratorImpl::release (void) inline virtual
Implements rcSegmentIterator.
Definition at line 104 of file rc_scalartrackimpl.cpp.
         {
             delete this;
         }
virtual void rcScalarSegmentIteratorImpl::reset (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 93 of file rc_scalartrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::lock(), rcSegmentIteratorImpl::reset(), setCurrentValue(), and rcSegmentIteratorImpl::unlock().
         {
             if ( lock )
                 _iter.lock();
             _iter.reset( false );
             setCurrentValue();
             if ( lock )
                 _iter.unlock();
         }
virtual void rcScalarSegmentIteratorImpl::setCurrentValue (void) inline private virtual
Definition at line 153 of file rc_scalartrackimpl.cpp.
References _currentValue, _iter, rcScalarTrackImpl::_segments, _track, rcSegmentIteratorImpl::getSegmentIndex(), and rcScalarTrackImpl::segments().
Referenced by advance(), rcScalarSegmentIteratorImpl(), and reset().
         {
             int32 index = _iter.getSegmentIndex();
             if ( index >= 0 && static_cast<uint32>(index) < _track->segments() )
                 _currentValue = _track->_segments[index].mValue;
             else
                 _currentValue = 0.0;
         }
virtual void rcScalarSegmentIteratorImpl::unlock () inline virtual
Implements rcSegmentIterator.
Definition at line 87 of file rc_scalartrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::unlock().
         {
             _iter.unlock();
         }
Member Data Documentation
double rcScalarSegmentIteratorImpl::_currentValue private
Definition at line 164 of file rc_scalartrackimpl.cpp.
Referenced by getValue(), and setCurrentValue().
rcSegmentIteratorImpl rcScalarSegmentIteratorImpl::_iter private
Definition at line 162 of file rc_scalartrackimpl.cpp.
Referenced by advance(), contains(), getFocus(), getSegmentCount(), getSegmentIndex(), getSegmentLength(), getSegmentOffset(), getSegmentStart(), getSegmentStartAbsolute(), getTrackOffset(), hasNextSegment(), lock(), rcScalarSegmentIteratorImpl(), reset(), setCurrentValue(), and unlock().
rcScalarTrackImpl* rcScalarSegmentIteratorImpl::_track private
Definition at line 163 of file rc_scalartrackimpl.cpp.
Referenced by setCurrentValue().
The documentation for this class was generated from the following file:
src/visible/src/rc_scalartrackimpl.cpp