Visible: rcMomentGenerator Class Reference
rcMomentGenerator Class Reference
#include <include/analysis/rc_moments.h>
Public Types
enum integralType { eMoment1D, eMoment2D, eMoment2DFast }
Public Member Functions
rcMomentGenerator (integralType type=eMoment2D)
virtual ~rcMomentGenerator ()
void update (const rcWindow &frame)
void genSumSumSq (const rcRect &loc, float &sum, float &sumSq) const
void vProject (const rcRect &loc, rcWindow &project) const
void hProject (const rcRect &loc, rcWindow &project) const
Private Types
typedef void(rcMomentGenerator::* momGenFct)(const rcRect &loc, float &sum, float &sumSq) const
typedef void(rcMomentGenerator::* projectFct)(const rcRect &loc, rcWindow &project) const
Private Member Functions
uint32 * imgSumPtr (const int32 x, const int32 y) const
int64 * imgSumSqPtr (const int32 x, const int32 y) const
uint32 * imgSumSqPtrLow (const int32 x, const int32 y) const
uint32 * imgSumSqPtrFast (const int32 x, const int32 y) const
void genSumSumSq1D (const rcRect &loc, float &sum, float &sumSq) const
void genSumSumSq2D (const rcRect &loc, float &sum, float &sumSq) const
void genSumSumSq2DFast (const rcRect &loc, float &sum, float &sumSq) const
void vProject1D (const rcRect &loc, rcWindow &project) const
void vProject2D (const rcRect &loc, rcWindow &project) const
void vProject2DFast (const rcRect &loc, rcWindow &project) const
void hProject1D (const rcRect &loc, rcWindow &project) const
void hProject2D (const rcRect &loc, rcWindow &project) const
void hProject2DFast (const rcRect &loc, rcWindow &project) const
Private Attributes
const integralType _type
const momGenFct _momGen
const projectFct _vProject
const projectFct _hProject
rcWindow _imgSq
uint32 * _imgSqBase
int32 _imgSqRowUpdate
Friends
class rcAutoCorrelation
class rcPointCorrelation
Detailed Description
Definition at line 145 of file rc_moments.h.
Member Typedef Documentation
typedef void(rcMomentGenerator::* rcMomentGenerator::momGenFct)(const rcRect &loc, float &sum, float &sumSq) const private
Definition at line 147 of file rc_moments.h.
typedef void(rcMomentGenerator::* rcMomentGenerator::projectFct)(const rcRect &loc, rcWindow &project) const private
Definition at line 150 of file rc_moments.h.
Member Enumeration Documentation
enum rcMomentGenerator::integralType
Enumerator
eMoment1D
eMoment2D
eMoment2DFast
Definition at line 154 of file rc_moments.h.
                     {
     eMoment1D,
     eMoment2D,
     eMoment2DFast
   };
Constructor & Destructor Documentation
rcMomentGenerator::rcMomentGenerator (integralType type = eMoment2D)
Definition at line 159 of file rc_integral_corr.cpp.
   : _type(type),
     _momGen((_type == eMoment1D) ? &rcMomentGenerator::genSumSumSq1D :
         ((_type == eMoment2D) ? &rcMomentGenerator::genSumSumSq2D :
          &rcMomentGenerator::genSumSumSq2DFast)),
     _vProject((_type == eMoment1D) ? &rcMomentGenerator::vProject1D :
           ((_type == eMoment2D) ? &rcMomentGenerator::vProject2D :
            &rcMomentGenerator::vProject2DFast)),
     _hProject((_type == eMoment1D) ? &rcMomentGenerator::hProject1D :
           ((_type == eMoment2D) ? &rcMomentGenerator::hProject2D :
            &rcMomentGenerator::hProject2DFast)),
     _imgSqBase(0)
 {
 }
rcMomentGenerator::~rcMomentGenerator () virtual
Definition at line 174 of file rc_integral_corr.cpp.
 {
 }
Member Function Documentation
void rcMomentGenerator::genSumSumSq (const rcRect & loc, float & sum, float & sumSq) const inline
Definition at line 176 of file rc_moments.h.
References _momGen.
   { (this->*_momGen)(loc, sum, sumSq); }
void rcMomentGenerator::genSumSumSq1D (const rcRect & loc, float & sum, float & sumSq) const private
Definition at line 226 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), rmAssert, rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 x0 = loc.x()*2;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + (loc.width() - 1)*2;
   const int32 y1 = y0 + loc.height();
   rmAssert(0 <= x0);
   rmAssert(x0 <= x1);
   rmAssert(x1 <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < (_imgSq.height()-1)); // Subtract 1 to discount guard row
   uint32* iBottom = imgSumPtr(x0, y1);
   const uint32* iBLast = iBottom + (x1 - x0);
   uint32* iTop = imgSumPtr(x0, y0);
   const uint32* iTLast = iTop + (x1 - x0);
   int64 iSum = 0;
   int64 iSumSq = 0;
   while (iBottom <= iBLast) {
     iSum += *iBottom++ - *iTop++;
     iSumSq += *iBottom++ - *iTop++;
   }
   sum = iSum;
   sumSq = iSumSq;
   rmAssert(iBottom == (iBLast + 2));
   rmAssert(iTop == (iTLast + 2));
 }
void rcMomentGenerator::genSumSumSq2D (const rcRect & loc, float & sum, float & sumSq) const private
Definition at line 259 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), imgSumSqPtr(), rmAssert, rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 x0 = loc.x()*3;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + loc.width()*3;
   const int32 y1 = y0 + loc.height();
   rmAssert(0 <= x0);
   rmAssert(x0 < x1);
   rmAssert((x1+3) <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < _imgSq.height()-1); // Subtract 1 to discount guard row
   sum = *imgSumPtr(x1, y1) - *imgSumPtr(x0, y1) +
     *imgSumPtr(x0, y0) - *imgSumPtr(x1, y0);
   sumSq = *imgSumSqPtr(x1+1, y1) - *imgSumSqPtr(x0+1, y1) +
     *imgSumSqPtr(x0+1, y0) - *imgSumSqPtr(x1+1, y0);
 }
void rcMomentGenerator::genSumSumSq2DFast (const rcRect & loc, float & sum, float & sumSq) const private
Definition at line 282 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), imgSumSqPtrFast(), rmAssert, rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 width = loc.width();
   const int32 height = loc.height();
   rmAssert(width*height <= 65536);
   const int32 x0 = loc.x()*2;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + width*2;
   const int32 y1 = y0 + height;
   rmAssert(0 <= x0);
   rmAssert(x0 < x1);
   rmAssert((x1+2) <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < _imgSq.height()-1); // Subtract 1 to discount guard row
   sum = *imgSumPtr(x1, y1) - *imgSumPtr(x0, y1) +
     *imgSumPtr(x0, y0) - *imgSumPtr(x1, y0);
   sumSq = *imgSumSqPtrFast(x1+1, y1) - *imgSumSqPtrFast(x0+1, y1) +
     *imgSumSqPtrFast(x0+1, y0) - *imgSumSqPtrFast(x1+1, y0);
 }
void rcMomentGenerator::hProject (const rcRect & loc, rcWindow & project) const inline
Definition at line 208 of file rc_moments.h.
References _hProject.
Referenced by rcMuscleTracker::calculateCellLocation(), and rcShape::project().
   { (this->*_hProject)(loc, project); }
void rcMomentGenerator::hProject1D (const rcRect & loc, rcWindow & project) const private
Definition at line 427 of file rc_integral_corr.cpp.
References rmAssert.
 {
   rmAssert(0);
 }
void rcMomentGenerator::hProject2D (const rcRect & loc, rcWindow & project) const private
Definition at line 432 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, _imgSqRowUpdate, rcWindow::depth(), rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), rcPixel32, rmAssert, rcWindow::setPixel(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 height = loc.height();
   const int32 x0 = loc.x()*3;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + loc.width()*3;
   const int32 y1 = y0 + height;
   rmAssert(0 <= x0);
   rmAssert(x0 < x1);
   rmAssert((x1+3) <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < _imgSq.height()-1); // Subtract 1 to discount guard row
   rmAssert(project.depth() == rcPixel32);
   rmAssert(project.height() == 1);
   rmAssert(project.width() == loc.height());
   const int32 rowUpdate = _imgSqRowUpdate;
   uint32* iLeft = imgSumPtr(x0, y0);
   uint32* iRight = imgSumPtr(x1, y0);
   uint32 prevSum = *iRight - *iLeft;
   iLeft += rowUpdate;
   iRight += rowUpdate;
   for (int32 index = 0; index < height; index++) {
     uint32 sum = *iRight - *iLeft;
     iLeft += rowUpdate;
     iRight += rowUpdate;
     project.setPixel(index, 0, sum - prevSum);
     prevSum = sum;
   }
 }
void rcMomentGenerator::hProject2DFast (const rcRect & loc, rcWindow & project) const private
Definition at line 470 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, _imgSqRowUpdate, rcWindow::depth(), rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), rcPixel32, rmAssert, rcWindow::setPixel(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 width = loc.width();
   const int32 height = loc.height();
   rmAssert(width*height <= 65536);
   const int32 x0 = loc.x()*2;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + width*2;
   const int32 y1 = y0 + height;
   rmAssert(0 <= x0);
   rmAssert(x0 < x1);
   rmAssert((x1+2) <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < _imgSq.height()-1); // Subtract 1 to discount guard row
   rmAssert(project.depth() == rcPixel32);
   rmAssert(project.height() == 1);
   rmAssert(project.width() == loc.height());
   const int32 rowUpdate = _imgSqRowUpdate;
   uint32* iLeft = imgSumPtr(x0, y0);
   uint32* iRight = imgSumPtr(x1, y0);
   uint32 prevSum = *iRight - *iLeft;
   iLeft += rowUpdate;
   iRight += rowUpdate;
   for (int32 index = 0; index < height; index++) {
     uint32 sum = *iRight - *iLeft;
     iLeft += rowUpdate;
     iRight += rowUpdate;
     project.setPixel(index, 0, sum - prevSum);
     prevSum = sum;
   }
 }
uint32* rcMomentGenerator::imgSumPtr (const int32 x, const int32 y) const inline private
Definition at line 215 of file rc_moments.h.
References _imgSqBase, and _imgSqRowUpdate.
Referenced by rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), genSumSumSq1D(), genSumSumSq2D(), genSumSumSq2DFast(), hProject2D(), hProject2DFast(), vProject1D(), vProject2D(), and vProject2DFast().
   { return _imgSqBase + y*_imgSqRowUpdate + x; }
int64* rcMomentGenerator::imgSumSqPtr (const int32 x, const int32 y) const inline private
Definition at line 218 of file rc_moments.h.
References _imgSqBase, and _imgSqRowUpdate.
Referenced by genSumSumSq2D().
   { return (int64*)(_imgSqBase + y*_imgSqRowUpdate + x); }
uint32* rcMomentGenerator::imgSumSqPtrFast (const int32 x, const int32 y) const inline private
Definition at line 224 of file rc_moments.h.
References _imgSqBase, and _imgSqRowUpdate.
Referenced by genSumSumSq2DFast().
   { return (uint32*)(_imgSqBase + y*_imgSqRowUpdate + x); }
uint32* rcMomentGenerator::imgSumSqPtrLow (const int32 x, const int32 y) const inline private
Definition at line 221 of file rc_moments.h.
References _imgSqBase, and _imgSqRowUpdate.
Referenced by rcPointCorrelation::gen3by3Space(), and rcPointCorrelation::gen5by5Space().
   { return (uint32*)(_imgSqBase + y*_imgSqRowUpdate + x + 1); }
void rcMomentGenerator::update (const rcWindow & frame)
Definition at line 178 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, _imgSqRowUpdate, _type, eMoment1D, eMoment2D, eMoment2DFast, rcWindow::height(), rcPixel32, rfGen1DMomentIntegrals(), rfGen2DMomentIntegrals(), rfGen2DMomentIntegralsFast(), rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), VALID_1D_MOM_INT_HEIGHT, VALID_1D_MOM_INT_WIDTH, VALID_2D_MOM_INT_FAST_HEIGHT, VALID_2D_MOM_INT_FAST_WIDTH, VALID_2D_MOM_INT_HEIGHT, VALID_2D_MOM_INT_WIDTH, and rcWindow::width().
Referenced by rcMuscleTracker::calculateCellLocation(), and rcShape::project().
 {
   /* First, if necessary, resize _imgSq. Next, generate new moment
    * integrals.
    */
   if (_type == eMoment1D) {
     int32 validWidth = VALID_1D_MOM_INT_WIDTH(frame.width());
     int32 validHeight = VALID_1D_MOM_INT_HEIGHT(frame.height());
     if ((_imgSqBase == 0) || (validWidth != _imgSq.width()) ||
     (validHeight != _imgSq.height())) {
       _imgSq = rcWindow(validWidth, validHeight, rcPixel32);
       _imgSqBase = (uint32*)_imgSq.rowPointer(0);
       _imgSqRowUpdate = _imgSq.rowUpdate()/sizeof(uint32);
     }
     rfGen1DMomentIntegrals(frame, _imgSq);
   }
   else if (_type == eMoment2D) {
     int32 validWidth = VALID_2D_MOM_INT_WIDTH(frame.width());
     int32 validHeight = VALID_2D_MOM_INT_HEIGHT(frame.height());
     if ((_imgSqBase == 0) || (validWidth != _imgSq.width()) ||
     (validHeight != _imgSq.height())) {
       _imgSq = rcWindow(validWidth, validHeight, rcPixel32);
       _imgSqBase = (uint32*)_imgSq.rowPointer(0);
       _imgSqRowUpdate = _imgSq.rowUpdate()/sizeof(uint32);
     }
     rfGen2DMomentIntegrals(frame, _imgSq);
   }
   else if (_type == eMoment2DFast) {
     int32 validWidth = VALID_2D_MOM_INT_FAST_WIDTH(frame.width());
     int32 validHeight = VALID_2D_MOM_INT_FAST_HEIGHT(frame.height());
     if ((_imgSqBase == 0) || (validWidth != _imgSq.width()) ||
     (validHeight != _imgSq.height())) {
       _imgSq = rcWindow(validWidth, validHeight, rcPixel32);
       _imgSqBase = (uint32*)_imgSq.rowPointer(0);
       _imgSqRowUpdate = _imgSq.rowUpdate()/sizeof(uint32);
     }
     rfGen2DMomentIntegralsFast(frame, _imgSq);
   }
   else
     rmAssert(0);
 }
void rcMomentGenerator::vProject (const rcRect & loc, rcWindow & project) const inline
Definition at line 191 of file rc_moments.h.
References _vProject.
Referenced by rcMuscleTracker::calculateCellLocation(), and rcShape::project().
   { (this->*_vProject)(loc, project); }
void rcMomentGenerator::vProject1D (const rcRect & loc, rcWindow & project) const private
Definition at line 307 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, rcWindow::depth(), rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), rcPixel32, rmAssert, rcWindow::setPixel(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 x0 = loc.x()*2;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + (loc.width() - 1)*2;
   const int32 y1 = y0 + loc.height();
   rmAssert(0 <= x0);
   rmAssert(x0 <= x1);
   rmAssert(x1 <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < (_imgSq.height()-1)); // Subtract 1 to discount guard row
   rmAssert(project.depth() == rcPixel32);
   rmAssert(project.height() == 1);
   rmAssert(project.width() == loc.width());
   uint32* iBottom = imgSumPtr(x0, y1);
   const uint32* iBLast = iBottom + (x1 - x0);
   uint32* iTop = imgSumPtr(x0, y0);
   const uint32* iTLast = iTop + (x1 - x0);
   uint32 index = 0;
   while (iBottom <= iBLast) {
     project.setPixel(index++, 0, *iBottom - *iTop);
     iBottom += 2;
     iTop += 2;
   }
   rmAssert(iBottom == (iBLast + 2));
   rmAssert(iTop == (iTLast + 2));
 }
void rcMomentGenerator::vProject2D (const rcRect & loc, rcWindow & project) const private
Definition at line 342 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, rcWindow::depth(), rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), rcPixel32, rmAssert, rcWindow::setPixel(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 x0 = loc.x()*3;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + loc.width()*3;
   const int32 y1 = y0 + loc.height();
   rmAssert(0 <= x0);
   rmAssert(x0 < x1);
   rmAssert((x1+3) <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < _imgSq.height()-1); // Subtract 1 to discount guard row
   rmAssert(project.depth() == rcPixel32);
   rmAssert(project.height() == 1);
   rmAssert(project.width() == loc.width());
   uint32* iBottom = imgSumPtr(x0, y1);
   const uint32* iBLast = iBottom + (x1 - x0);
   uint32* iTop = imgSumPtr(x0, y0);
   const uint32* iTLast = iTop + (x1 - x0);
   uint32 index = 0;
   uint32 prevSum = *iBottom - *iTop;
   iBottom += 3;
   iTop += 3;
   while (iBottom <= iBLast) {
     uint32 sum = *iBottom - *iTop;
     iBottom += 3;
     iTop += 3;
     project.setPixel(index++, 0, sum - prevSum);
     prevSum = sum;
   }
   rmAssert(iBottom == (iBLast + 3));
   rmAssert(iTop == (iTLast + 3));
 }
void rcMomentGenerator::vProject2DFast (const rcRect & loc, rcWindow & project) const private
Definition at line 383 of file rc_integral_corr.cpp.
References _imgSq, _imgSqBase, rcWindow::depth(), rcWindow::height(), rcRectangle< T >::height(), imgSumPtr(), rcPixel32, rmAssert, rcWindow::setPixel(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_imgSqBase);
   const int32 width = loc.width();
   const int32 height = loc.height();
   rmAssert(width*height <= 65536);
   const int32 x0 = loc.x()*2;
   const int32 y0 = loc.y();
   const int32 x1 = x0 + width*2;
   const int32 y1 = y0 + height;
   rmAssert(0 <= x0);
   rmAssert(x0 < x1);
   rmAssert((x1+2) <= _imgSq.width());
   rmAssert(0 <= y0);
   rmAssert(y0 < y1);
   rmAssert(y1 < _imgSq.height()-1); // Subtract 1 to discount guard row
   rmAssert(project.depth() == rcPixel32);
   rmAssert(project.height() == 1);
   rmAssert(project.width() == loc.width());
   uint32* iBottom = imgSumPtr(x0, y1);
   const uint32* iBLast = iBottom + (x1 - x0);
   uint32* iTop = imgSumPtr(x0, y0);
   const uint32* iTLast = iTop + (x1 - x0);
   uint32 index = 0;
   uint32 prevSum = *iBottom - *iTop;
   iBottom += 2;
   iTop += 2;
   while (iBottom <= iBLast) {
     uint32 sum = *iBottom - *iTop;
     iBottom += 2;
     iTop += 2;
     project.setPixel(index++, 0, sum - prevSum);
     prevSum = sum;
   }
   rmAssert(iBottom == (iBLast + 2));
   rmAssert(iTop == (iTLast + 2));
 }
Friends And Related Function Documentation
friend class rcAutoCorrelation friend
Definition at line 212 of file rc_moments.h.
friend class rcPointCorrelation friend
Definition at line 213 of file rc_moments.h.
Member Data Documentation
const projectFct rcMomentGenerator::_hProject private
Definition at line 241 of file rc_moments.h.
Referenced by hProject().
rcWindow rcMomentGenerator::_imgSq private
Definition at line 242 of file rc_moments.h.
Referenced by rcAutoCorrelation::genCache(), genSumSumSq1D(), genSumSumSq2D(), genSumSumSq2DFast(), hProject2D(), hProject2DFast(), rcPointCorrelation::update(), update(), vProject1D(), vProject2D(), and vProject2DFast().
uint32* rcMomentGenerator::_imgSqBase private
Definition at line 243 of file rc_moments.h.
Referenced by genSumSumSq1D(), genSumSumSq2D(), genSumSumSq2DFast(), hProject2D(), hProject2DFast(), imgSumPtr(), imgSumSqPtr(), imgSumSqPtrFast(), imgSumSqPtrLow(), update(), vProject1D(), vProject2D(), and vProject2DFast().
int32 rcMomentGenerator::_imgSqRowUpdate private
Definition at line 244 of file rc_moments.h.
Referenced by hProject2D(), hProject2DFast(), imgSumPtr(), imgSumSqPtr(), imgSumSqPtrFast(), imgSumSqPtrLow(), and update().
const momGenFct rcMomentGenerator::_momGen private
Definition at line 240 of file rc_moments.h.
Referenced by genSumSumSq().
const integralType rcMomentGenerator::_type private
Definition at line 239 of file rc_moments.h.
Referenced by rcPointCorrelation::update(), and update().
const projectFct rcMomentGenerator::_vProject private
Definition at line 241 of file rc_moments.h.
Referenced by vProject().
The documentation for this class was generated from the following files:
include/analysis/rc_moments.h
src/analysis/code/rc_integral_corr.cpp