Visible: rcSettingCategory Class Reference
rcSettingCategory Class Reference
#include <include/baseUI/rc_setting.h>
Public Member Functions
rcSettingCategory (void)
rcSettingCategory (rcSettingSource *source, const rcSettingCategorySpec *spec)
const char * getTag () const
const char * getName () const
const char * getDescription () const
const int getNSettings (void) const
const rcSettingInfo getSettingInfo (int settingNo) const
const rcSettingInfo getSettingInfo (const std::string &settingTag) const
void dump (ostream &stream) const
const rcSettingInfo operator[] (int settingNo) const
const rcSettingInfo operator[] (const std::string &settingTag) const
Private Member Functions
void assertInitialized (void) const
Private Attributes
rcSettingSource * _source
const rcSettingCategorySpec * _spec
int _nSettings
Detailed Description
Definition at line 262 of file rc_setting.h.
Constructor & Destructor Documentation
rcSettingCategory::rcSettingCategory (void)
Definition at line 21 of file rc_setting.cpp.
 {
   _source = 0;
   _spec = 0;
   _nSettings = 0;
 }
rcSettingCategory::rcSettingCategory (rcSettingSource * source, const rcSettingCategorySpec * spec)
Definition at line 29 of file rc_setting.cpp.
References rcSettingInfoSpec::_name, and rcSettingCategorySpec::_settingInfoSpecs.
 {
   _source = source;
   _spec = spec;
   for (_nSettings = 0; ; _nSettings++)
     {
       const rcSettingInfoSpec* infoSpec = &(spec->_settingInfoSpecs[ _nSettings ]);
       if (infoSpec->_name == 0)
     break;
     }
 }
Member Function Documentation
void rcSettingCategory::assertInitialized (void) const private
Definition at line 114 of file rc_setting.cpp.
 {
   if ((_source == 0) || (_spec == 0))
     throw general_exception( "rcSettingCategory::assertInitialized failed" );
 }
void rcSettingCategory::dump (ostream & stream) const
Definition at line 102 of file rc_setting.cpp.
References endl(), rcSettingInfo::getDisplayName(), and rcSettingInfo::getValue().
 {
   stream << endl << getName() << " settings (" << getDescription() << ")" << endl;
   int nSettings = getNSettings();
   for (int i = 0; i < nSettings; i++)
     {
       rcSettingInfo setting = getSettingInfo( i );
       stream << "  " << setting.getDisplayName() << " = " << setting.getValue() << endl;
     }
 }
const char * rcSettingCategory::getDescription (void) const
Definition at line 57 of file rc_setting.cpp.
Referenced by rcNativeExporter::produceSettings(), and rcSettingPanel::updatePages().
 {
   assertInitialized();
   return _spec->_description;
 }
const char * rcSettingCategory::getName () const
Definition at line 50 of file rc_setting.cpp.
Referenced by rcNativeImporter::findSettingCategory(), rcNativeExporter::produceSettings(), and rcSettingPanel::updatePages().
 {
   assertInitialized();
   return _spec->_name;
 }
const int rcSettingCategory::getNSettings (void) const
Definition at line 64 of file rc_setting.cpp.
Referenced by rcEngineBaseImpl::checkSettings(), rcCSVExporter::exportExperiment(), rcNativeImporter::findSetting(), rcNativeExporter::produceSettings(), rcSettingPage::rcSettingPage(), and rcNativeImporter::setSettingValue().
 {
   assertInitialized();
   return _nSettings;
 }
const rcSettingInfo rcSettingCategory::getSettingInfo (int settingNo) const
Definition at line 71 of file rc_setting.cpp.
References rmDim.
Referenced by rcEngineBaseImpl::checkSettings(), rcCSVExporter::exportExperiment(), rcNativeImporter::findSetting(), rcTimeline::keyPressEvent(), rcNativeExporter::produceSettings(), rcSettingPage::rcSettingPage(), rcExperimentDomainImpl::saveExperiment(), rcNativeImporter::setSettingValue(), and rcMonitor::settingChanged().
 {
   assertInitialized();
   if ((settingNo < 0) || (settingNo >= _nSettings)) {
     char buf[512];
     snprintf( buf, rmDim(buf), "rcSettingCategory::getSettingInfo: index %i out-of-bounds in category %s",
           settingNo, getName() );
     throw general_exception( buf );
   }
   const rcSettingInfoSpec* settingInfoSpec = &(_spec->_settingInfoSpecs[ settingNo ]);
   return rcSettingInfo( _source , settingInfoSpec );
 }
const rcSettingInfo rcSettingCategory::getSettingInfo (const std::string & settingTag) const
Definition at line 86 of file rc_setting.cpp.
References rcSettingInfoSpec::_tag, and rmDim.
 {
   assertInitialized();
   for (int i = 0; i < _nSettings; i++)
     {
       const rcSettingInfoSpec* settingInfoSpec = &(_spec->_settingInfoSpecs[ i ]);
       if (settingTag == settingInfoSpec->_tag)
     return rcSettingInfo( _source , settingInfoSpec );
     }
   char buf[512];
   snprintf( buf, rmDim(buf), "rcSettingCategory::getSettingInfo: tag %s not found from category %s",
         settingTag.c_str(), getName() );
   throw general_exception( buf );
 }
const char * rcSettingCategory::getTag (void) const
Definition at line 43 of file rc_setting.cpp.
Referenced by rcEngineBaseImpl::checkSettings(), rcTimeline::keyPressEvent(), rcExperimentDomainImpl::saveExperiment(), and rcMonitor::settingChanged().
 {
   assertInitialized();
   return _spec->_tag;
 }
const rcSettingInfo rcSettingCategory::operator[] (int settingNo) const inline
Definition at line 293 of file rc_setting.h.
   {
     return getSettingInfo( settingNo );
   }
const rcSettingInfo rcSettingCategory::operator[] (const std::string & settingTag) const inline
Definition at line 299 of file rc_setting.h.
   {
     return getSettingInfo( settingTag );
   }
Member Data Documentation
int rcSettingCategory::_nSettings private
Definition at line 310 of file rc_setting.h.
rcSettingSource* rcSettingCategory::_source private
Definition at line 308 of file rc_setting.h.
const rcSettingCategorySpec* rcSettingCategory::_spec private
Definition at line 309 of file rc_setting.h.
The documentation for this class was generated from the following files:
include/baseUI/rc_setting.h
src/baseUI/rc_setting.cpp