Visible: rcWriterManager Class Reference
rcWriterManager Class Reference
#include <include/visiCore/rc_writermanager.h>
Public Member Functions
rcWriterManager (rcEngineObserver *observer)
rcWriterGroup * createWriterGroup (const char *name, const char *description, rcGroupSemantics type)
virtual rcWriter * createWriter (rcWriterGroup *group, rcWriterSemantics type, uint32 sizeLimit, const rcRect &analysisRect)
virtual rcScalarWriter * createScalarWriter (rcWriterGroup *group, rcWriterSemantics type, uint32 sizeLimit, const rcRect &analysisRect, const double &expectedMin, const double &expectedMax)
virtual rcPositionWriter * createPositionWriter (rcWriterGroup *group, rcWriterSemantics type, uint32 sizeLimit, const rcRect &analysisRect, const rcFPair &expectedMin, const rcFPair &expectedMax)
virtual rcGraphicsWriter * createGraphicsWriter (rcWriterGroup *group, rcWriterSemantics type, uint32 sizeLimit, const rcRect &analysisRect)
virtual rcVideoWriter * createVideoWriter (rcWriterGroup *group, rcWriterSemantics type, uint32 sizeLimit, const rcRect &analysisRect)
Static Public Member Functions
static std::string writerName (rcWriterSemantics id)
static std::string writerTag (rcWriterSemantics id)
static rcWriterSemantics nameType (const std::string &name)
static rcWriterSemantics tagType (const std::string &tag)
static std::string optionString (rcWriterSemantics type, rcWriterWindowOrigin origin, uint32 windowSize)
static std::string channelString (rcChannelConversion c)
static void renameEntropyTrack (rcWriter *writer, rcSimilarator::rcEntropyDefinition def, rcPixel inputDepth, rcChannelConversion channelConversion)
static void renameTrack (rcWriter *writer, std::string &name, std::string &desc)
Private Attributes
rcEngineObserver * mObserver
Detailed Description
Definition at line 104 of file rc_writermanager.h.
Constructor & Destructor Documentation
rcWriterManager::rcWriterManager (rcEngineObserver * observer)
Definition at line 81 of file rc_writermanager.cpp.
References NULL, and rmAssert.
                                                              :
         mObserver( observer )
 {
     rmAssert( observer != NULL );
}
Member Function Documentation
std::string rcWriterManager::channelString (rcChannelConversion c) static
Definition at line 295 of file rc_writermanager.cpp.
References rcSelectAll, rcSelectAverage, rcSelectBlue, rcSelectGreen, rcSelectMax, rcSelectRed, and rmDim.
Referenced by renameEntropyTrack().
 {
     std::string str;
     std::string channel;
     switch ( c ) {
         case rcSelectGreen:
             channel = "Green";
             break;
         case rcSelectRed:
             channel = "Red";
             break;
         case rcSelectBlue:
             channel = "Blue";
             break;
         case rcSelectAverage:
             channel = "Avg";
             break;
         case rcSelectMax:
             channel = "Max";
             break;
         case rcSelectAll:
             channel = "All";
             break;
     }
     char buf[256];
     // Add window size and origin indicator to string
     snprintf( buf, rmDim(buf), " [%s]",
               channel.c_str() );
     str += buf;
     return str;
 }
rcGraphicsWriter * rcWriterManager::createGraphicsWriter (rcWriterGroup * group, rcWriterSemantics type, uint32 sizeLimit, const rcRect & analysisRect) virtual
Definition at line 187 of file rc_writermanager.cpp.
References rcWriterGroup::createWriter(), rcWriterInfo::description(), eGraphicsWriter, eWriterUnknown, rcWriterInfo::format(), rcWriterMapper::info(), rcWriterInfo::name(), NULL, rmAssert, sWriterMapper, rcWriterInfo::tag(), rcWriterInfo::trackType(), and rcWriterInfo::type().
Referenced by rcEngineImpl::createGraphicsWriters(), and rcEngineFocusData::rcEngineFocusData().
 {
     rmAssert( group != NULL );
     rcGraphicsWriter* writer = 0;
     const rcWriterInfo info = sWriterMapper.info( type );
     if ( info.type() != eWriterUnknown && info.trackType() == eGraphicsWriter ) {
         writer = dynamic_cast<rcGraphicsWriter*>(group->createWriter( info.trackType(),
                                                                       info.tag().c_str(),
                                                                       info.name().c_str(),
                                                                       info.description().c_str(),
                                                                       info.format().c_str(),
                                                                       sizeLimit,
                                                                       analysisRect) );
     }
     return writer;
 }
rcPositionWriter * rcWriterManager::createPositionWriter (rcWriterGroup * group, rcWriterSemantics type, uint32 sizeLimit, const rcRect & analysisRect, const rcFPair & expectedMin, const rcFPair & expectedMax) virtual
Definition at line 157 of file rc_writermanager.cpp.
References rcWriterGroup::createWriter(), rcWriterInfo::description(), ePositionWriter, eWriterUnknown, rcWriterInfo::format(), rcWriterMapper::info(), rcWriterInfo::name(), NULL, rmAssert, rcPositionWriter::setExpectedMaxValue(), rcPositionWriter::setExpectedMinValue(), sWriterMapper, rcWriterInfo::tag(), rcWriterInfo::trackType(), and rcWriterInfo::type().
Referenced by rcCellWriterGroup::rcCellWriterGroup().
 {
     rmAssert( group != NULL );
     rcPositionWriter* writer = 0;
     const rcWriterInfo info = sWriterMapper.info( type );
     if ( info.type() != eWriterUnknown && info.trackType() == ePositionWriter ) {
         writer = dynamic_cast<rcPositionWriter*>(group->createWriter( info.trackType(),
                                                                       info.tag().c_str(),
                                                                       info.name().c_str(),
                                                                       info.description().c_str(),
                                                                       info.format().c_str(),
                                                                       sizeLimit,
                                                                       analysisRect ) );
         if ( writer ) {
             writer->setExpectedMinValue( expectedMin );
             writer->setExpectedMaxValue( expectedMax );
         }
     }
     return writer;
 }
rcScalarWriter * rcWriterManager::createScalarWriter (rcWriterGroup * group, rcWriterSemantics type, uint32 sizeLimit, const rcRect & analysisRect, const double & expectedMin, const double & expectedMax) virtual
Definition at line 127 of file rc_writermanager.cpp.
References rcWriterGroup::createWriter(), rcWriterInfo::description(), eScalarWriter, eWriterUnknown, rcWriterInfo::format(), rcWriterMapper::info(), rcWriterInfo::name(), NULL, rmAssert, rcScalarWriter::setExpectedMaxValue(), rcScalarWriter::setExpectedMinValue(), sWriterMapper, rcWriterInfo::tag(), rcWriterInfo::trackType(), and rcWriterInfo::type().
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcCellWriterGroup::rcCellWriterGroup(), and rcEngineFocusData::rcEngineFocusData().
 {
     rmAssert( group != NULL );
     rcScalarWriter* writer = 0;
     const rcWriterInfo info = sWriterMapper.info( type );
     if ( info.type() != eWriterUnknown && info.trackType() == eScalarWriter ) {
         writer = dynamic_cast<rcScalarWriter*>(group->createWriter( info.trackType(),
                                                                     info.tag().c_str(),
                                                                     info.name().c_str(),
                                                                     info.description().c_str(),
                                                                     info.format().c_str(),
                                                                     sizeLimit,
                                                                     analysisRect ) );
         if ( writer ) {
             writer->setExpectedMinValue( expectedMin );
             writer->setExpectedMaxValue( expectedMax );
         }
     }
     return writer;
 }
rcVideoWriter * rcWriterManager::createVideoWriter (rcWriterGroup * group, rcWriterSemantics type, uint32 sizeLimit, const rcRect & analysisRect) virtual
Definition at line 211 of file rc_writermanager.cpp.
References rcWriterGroup::createWriter(), rcWriterInfo::description(), eVideoWriter, eWriterUnknown, rcWriterInfo::format(), rcWriterMapper::info(), rcWriterInfo::name(), NULL, rmAssert, sWriterMapper, rcWriterInfo::tag(), rcWriterInfo::trackType(), and rcWriterInfo::type().
Referenced by rcEngineImpl::createSharedWriters(), and rcEngineFocusData::rcEngineFocusData().
 {
     rmAssert( group != NULL );
     rcVideoWriter* writer = 0;
     const rcWriterInfo info = sWriterMapper.info( type );
     if ( info.type() != eWriterUnknown && info.trackType() == eVideoWriter ) {
         writer = dynamic_cast<rcVideoWriter*>(group->createWriter( info.trackType(),
                                                                    info.tag().c_str(),
                                                                    info.name().c_str(),
                                                                    info.description().c_str(),
                                                                    info.format().c_str(),
                                                                    sizeLimit,
                                                                    analysisRect) );
     }
     return writer;
 }
rcWriter * rcWriterManager::createWriter (rcWriterGroup * group, rcWriterSemantics type, uint32 sizeLimit, const rcRect & analysisRect) virtual
Definition at line 103 of file rc_writermanager.cpp.
References rcWriterGroup::createWriter(), rcWriterInfo::description(), eWriterUnknown, rcWriterInfo::format(), rcWriterMapper::info(), rcWriterInfo::name(), NULL, rmAssert, sWriterMapper, rcWriterInfo::tag(), rcWriterInfo::trackType(), and rcWriterInfo::type().
 {
     rmAssert( group != NULL );
     rcWriter* writer = 0;
     const rcWriterInfo info = sWriterMapper.info( type );
     if ( info.type() != eWriterUnknown ) {
         writer = group->createWriter( info.trackType(),
                                       info.tag().c_str(),
                                       info.name().c_str(),
                                       info.description().c_str(),
                                       info.format().c_str(),
                                       sizeLimit,
                                       analysisRect );
     }
     return writer;
 }
rcWriterGroup * rcWriterManager::createWriterGroup (const char * name, const char * description, rcGroupSemantics type)
Definition at line 88 of file rc_writermanager.cpp.
References rcEngineObserver::createWriterGroup(), rcXMLNameMapper::elementName(), eXMLElementGroup, mObserver, rcXMLFileVersion, and rfGetXMLNameMapper().
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::createGraphicsWriters(), rcEngineImpl::createSharedWriters(), rcCellWriterGroup::rcCellWriterGroup(), and rcEngineFocusData::rcEngineFocusData().
 {
     const rcXMLNameMapper* nameMapper = rfGetXMLNameMapper( rcXMLFileVersion );
     std::string groupTag = nameMapper->elementName( eXMLElementGroup );
     return mObserver->createWriterGroup( groupTag.c_str(),
                                          name,
                                          description,
                                          type );
 }
rcWriterSemantics rcWriterManager::nameType (const std::string & name) static
Definition at line 251 of file rc_writermanager.cpp.
References sWriterMapper, and rcWriterMapper::type().
 {
     return sWriterMapper.type( name );
 }
std::string rcWriterManager::optionString (rcWriterSemantics type, rcWriterWindowOrigin origin, uint32 windowSize) static
Definition at line 263 of file rc_writermanager.cpp.
References eWindowOriginCenter, eWindowOriginLeft, eWindowOriginRight, rmDim, and rmUnused.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::entropyTrackerWindow(), and rcEngineFocusData::rcEngineFocusData().
 {
     rmUnused( type );
     std::string options;
     char originStr = '#';
     switch ( origin ) {
         case eWindowOriginLeft:
             originStr = 'L';
             break;
         case eWindowOriginCenter:
             originStr = 'C';
             break;
         case eWindowOriginRight:
             originStr = 'R';
             break;
     }
     char buf[256];
     // Add window size and origin indicator to string
     snprintf( buf, rmDim(buf), " [%i%c]",
               windowSize, originStr );
     options += buf;
     return options;
 }
void rcWriterManager::renameEntropyTrack (rcWriter * writer, rcSimilarator::rcEntropyDefinition def, rcPixel inputDepth, rcChannelConversion channelConversion) static
Definition at line 341 of file rc_writermanager.cpp.
References channelString(), rcSimilarator::eACI, endl(), rcSimilarator::eVisualEntropy, rcPixel32, rmAssert, rcWriter::setDescription(), and rcWriter::setName().
Referenced by rcEngineImpl::entropyTracker(), and rcEngineImpl::entropyTrackerWindow().
 {
     std::string name;
     switch (def) {
         case rcSimilarator::eACI:
             name = "Aggregate Change Index";
             break;
         case rcSimilarator::eVisualEntropy:
             name = "Mean Similarity Index";
             break;
         default:
             cerr <<  "Unknown Similarity Option " << def << endl;
             rmAssert( 0 );
     }
     if ( inputDepth == rcPixel32 ) {
         std::string channnelString = rcWriterManager::channelString( channelConversion );
         name += channnelString;
     }
     writer->setName ( name.c_str() );
     writer->setDescription ( name.c_str() );
 }
void rcWriterManager::renameTrack (rcWriter * writer, std::string & name, std::string & desc) static
Definition at line 334 of file rc_writermanager.cpp.
References rcWriter::setDescription(), and rcWriter::setName().
 {
     writer->setName ( name.c_str() );
     writer->setDescription ( desc.c_str() );
 }
rcWriterSemantics rcWriterManager::tagType (const std::string & tag) static
Definition at line 257 of file rc_writermanager.cpp.
References sWriterMapper, and rcWriterMapper::typeTag().
Referenced by rcTrackManager::displayableTrack(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcImageCanvasGL::getToolTipText(), getTrackValue(), rcExporter::isExportable(), rcTimeline::paintTimeline(), and rcTrackManager::setTrackEnabled().
 {
     return sWriterMapper.typeTag( tag );
 }
std::string rcWriterManager::writerName (rcWriterSemantics id) static
Definition at line 235 of file rc_writermanager.cpp.
References rcWriterMapper::info(), rcWriterInfo::name(), and sWriterMapper.
 {
     const rcWriterInfo info = sWriterMapper.info( type );
     return info.name();
 }
std::string rcWriterManager::writerTag (rcWriterSemantics id) static
Definition at line 243 of file rc_writermanager.cpp.
References rcWriterMapper::info(), sWriterMapper, and rcWriterInfo::tag().
 {
     const rcWriterInfo info = sWriterMapper.info( type );
     return info.tag();
 }
Member Data Documentation
rcEngineObserver* rcWriterManager::mObserver private
Definition at line 174 of file rc_writermanager.h.
Referenced by createWriterGroup().
The documentation for this class was generated from the following files:
include/visiCore/rc_writermanager.h
src/visible/src/rc_writermanager.cpp