Visible: rcPolygon Class Reference
rcPolygon Class Reference
#include <include/visual/rc_polygon.h>
Public Types
typedef double FT
typedef rc2dVector< FT > Point_2
typedef std::deque< Point_2 > Container_P
typedef
Container_P::difference_type difference_type
typedef Container_P::value_type value_type
typedef Container_P::pointer pointer
typedef Container_P::reference reference
typedef
Container_P::const_reference const_reference
typedef Container_P::iterator Vertex_iterator
typedef Container_P::iterator Vertex_const_iterator
typedef
Polygon_2_edge_iterator
< Container_P > Edge_const_iterator
Public Member Functions
rcPolygon ()
rcPolygon (const float, const int32)
rcPolygon (const float, const float, const int32)
rcPolygon (const rcAffineRectangle &af)
void pushVertex (const rc2Dvector &vertex)
bool pushUniqueVertex (const rc2Dvector &vertex)
void popVertex ()
void deleteVertex (int32 index)
void insertVertex (const rc2Dvector &vertex, int32 after)
void erase (Vertex_iterator pos)
void erase (Vertex_iterator first, Vertex_iterator last)
void clear ()
void reverse_orientation ()
void translate (const rc2Dvector &delta)
void translate (const rc2Fvector &delta)
void transform (const rc2Xform &xfm)
void convexHullConvert ()
const rc2Dvector & vertexAt (int32 index) const
bool isValid () const
bool isConvex () const
int32 vertexCnt () const
int32 size () const
bool contains (const rc2Dvector &point) const
bool contains (const rcPolygon &polygon) const
bool intersects (const rcPolygon &polygon) const
bool intersects (const vector< rcPolygon > &group, vector< rcPolygon > &groupIntersects, float areaRatio=0.25f) const
int32 intersects (const vector< rcPolygon > &group, float areaRatio=0.25f) const
bool centerOf (rc2Dvector &) const
bool centerOf (rc2Fvector &) const
double area () const
double perimeter () const
double circularity () const
double ellipseRatio () const
void convexIntersection (const rcPolygon &polygon, rcPolygon &polyInt) const
void convexUnion (const rcPolygon &polygon, rcPolygon &polyUnion) const
void convexHull (rcPolygon &polyHull) const
rcAffineRectangle minimumAreaEnclosingRect () const
rcAffineRectangle minimumPerimeterEnclosingRect () const
rcIRect orthogonalEnclosingRect () const
void orthogonalEnclosingRect (rcDRect &) const
void orthogonalEnclosingRect (rcFRect &) const
rcPolygon discBuffer (double diameter) const
Vertex_const_iterator vertices_begin () const
Vertex_const_iterator vertices_end () const
Edge_const_iterator edges_begin () const
Edge_const_iterator edges_end () const
Private Types
enum eInState { eInUnknown = 0, ePIn, eQIn }
enum eIntersection {
eInterUnknown = 0, eNoIntersection, eProperIntersection, eVertexIntersection,
eSharedCollinear
}
Private Member Functions
double triArea2 (const rc2Dvector &a, const rc2Dvector &b, const rc2Dvector &c) const
double polyArea2 () const
bool leftTurn (const rc2Dvector &a, const rc2Dvector &b, const rc2Dvector &c) const
bool leftTurnOrOn (const rc2Dvector &a, const rc2Dvector &b, const rc2Dvector &c) const
bool collinear (const rc2Dvector &a, const rc2Dvector &b, const rc2Dvector &c) const
bool intersection (const rc2Dvector &a0, const rc2Dvector &a1, const rc2Dvector &b0, const rc2Dvector &b1, rc2Dvector *inter) const
void createConvexHull (rcPolygon &poly, bool mastBeValid=true) const
int32 areaSign (const rc2Dvector &a, const rc2Dvector &b, const rc2Dvector &c) const
bool between (const rc2Dvector &a, const rc2Dvector &b, const rc2Dvector &c) const
eIntersection parallelInter (const rc2Dvector &a0, const rc2Dvector &a1, const rc2Dvector &b0, const rc2Dvector &b1, rc2Dvector &inter1, rc2Dvector &inter2) const
eIntersection segmentInter (const rc2Dvector &a0, const rc2Dvector &a1, const rc2Dvector &b0, const rc2Dvector &b1, rc2Dvector &inter1, rc2Dvector &inter2) const
bool convexComparedToConvex (const rcPolygon &polygon, const bool contains) const
int32 findPeak (const int32 startIndex, const rc2Dvector &b0, const rc2Dvector &b1) const
rc2Dvector crossing (const rc2Dvector &b0, const rc2Dvector &b1, const rc2Dvector &a) const
void genMinRectBounds (const rc2Dvector &topPt, const rc2Dvector &btmPt, const rc2Dvector &leftPt, const rc2Dvector &rightPt, double mx, double my, rc2Dvector &llPt, rc2Dvector &dim) const
rcAffineRectangle genMinEnclosingRect (bool area) const
const deque< rc2Dvector > & vert () const
Private Attributes
deque< rc2Dvector > _vert
bool _isConvex
bool _isValid
bool _knownConvex
bool _knownValid
bool _comValid
bool _areaValid
rc2Dvector _com
double _area
Friends
bool operator== (const rcPolygon &a, const rcPolygon &b)
bool operator!= (const rcPolygon &a, const rcPolygon &b)
ostream & operator<< (ostream &, const rcPolygon &)
Detailed Description
Definition at line 132 of file rc_polygon.h.
Member Typedef Documentation
typedef Container_P::const_reference rcPolygon::const_reference
Definition at line 143 of file rc_polygon.h.
typedef std::deque<Point_2> rcPolygon::Container_P
Definition at line 138 of file rc_polygon.h.
typedef Container_P::difference_type rcPolygon::difference_type
Definition at line 139 of file rc_polygon.h.
typedef Polygon_2_edge_iterator<Container_P> rcPolygon::Edge_const_iterator
Definition at line 146 of file rc_polygon.h.
typedef double rcPolygon::FT
Definition at line 136 of file rc_polygon.h.
typedef rc2dVector<FT> rcPolygon::Point_2
Definition at line 137 of file rc_polygon.h.
typedef Container_P::pointer rcPolygon::pointer
Definition at line 141 of file rc_polygon.h.
typedef Container_P::reference rcPolygon::reference
Definition at line 142 of file rc_polygon.h.
typedef Container_P::value_type rcPolygon::value_type
Definition at line 140 of file rc_polygon.h.
typedef Container_P::iterator rcPolygon::Vertex_const_iterator
Definition at line 145 of file rc_polygon.h.
typedef Container_P::iterator rcPolygon::Vertex_iterator
Definition at line 144 of file rc_polygon.h.
Member Enumeration Documentation
enum rcPolygon::eInState private
Enumerator
eInUnknown
ePIn
eQIn
Definition at line 416 of file rc_polygon.h.
                 {
     eInUnknown = 0,
     ePIn,
     eQIn
   };
enum rcPolygon::eIntersection private
Enumerator
eInterUnknown
eNoIntersection
eProperIntersection
eVertexIntersection
eSharedCollinear
Definition at line 422 of file rc_polygon.h.
                      {
     eInterUnknown = 0,
     eNoIntersection,
     eProperIntersection,
     eVertexIntersection,
     eSharedCollinear
   };
Constructor & Destructor Documentation
rcPolygon::rcPolygon ()
Definition at line 108 of file rc_polygon.cpp.
                      : _isConvex(true), _isValid(true),
              _knownConvex(true), _knownValid(true),
              _comValid (false),  _areaValid (false)
 {
 }
rcPolygon::rcPolygon (const float r, const int32 n)
Definition at line 114 of file rc_polygon.cpp.
References cos(), isConvex(), pushVertex(), rkPI, and sin().
                                                  : _isConvex(true), _isValid(true),
              _knownConvex(true), _knownValid(true),
              _comValid (false),  _areaValid (false)
 {
   if (n <= 0) return;
   for (int32 i = 0; i < n; i++)
     {
       double x = ( -r * sin ((2 * i * rkPI) / n));
       double y = (  r * cos ((2 * i * rkPI) / n));
       rc2Dvector p (x, y);
       pushVertex (p);
       if (!isConvex()) return;
     }
 }
rcPolygon::rcPolygon (const float a, const float b, const int32 n)
Definition at line 129 of file rc_polygon.cpp.
References cos(), isConvex(), pushVertex(), rkPI, and sin().
                                                                 : _isConvex(true), _isValid(true),
              _knownConvex(true), _knownValid(true),
              _comValid (false),  _areaValid (false)
 {
   if (n <= 0) return;
   for (int32 i = 0; i < n; i++)
     {
       double x = ( -a * sin ((2 * i * rkPI) / n));
       double y = (  b * cos ((2 * i * rkPI) / n));
       rc2Dvector p (x, y);
       pushVertex (p);
       if (!isConvex()) return;
     }
 }
rcPolygon::rcPolygon (const rcAffineRectangle & af)
Definition at line 145 of file rc_polygon.cpp.
References rcAffineRectangle::affineToImage(), isConvex(), rcAffineRectangle::isValid(), and pushVertex().
                                                 : _isConvex(true), _isValid(true),
              _knownConvex(true), _knownValid(true), _comValid (false)
 {
   if (! af.isValid ()) return;
   const rc2Dvector ul = af.affineToImage(rc2Dvector(0, 0));
   const rc2Dvector ur = af.affineToImage(rc2Dvector(1, 0));
   const rc2Dvector ll = af.affineToImage(rc2Dvector(0, 1));
   const rc2Dvector lr = af.affineToImage(rc2Dvector(1, 1));
   pushVertex (ul);
   if (!isConvex()) return;
   pushVertex (ur);
   if (!isConvex()) return;
   pushVertex (lr);
   if (!isConvex()) return;
   pushVertex (ll);
   if (!isConvex()) return;
 }
Member Function Documentation
double rcPolygon::area () const
Definition at line 630 of file rc_polygon.cpp.
References _area, _areaValid, isValid(), polyArea2(), and rmAssert.
Referenced by circularity(), ellipseRatio(), intersects(), rcMuscleSegmenter::mergePolygons(), rcShape::needArea(), rfComponentPolygons(), and rcVisualFunction::update().
 {
   rmAssert(isValid());
   if (_areaValid == false)
     {
       const_cast<rcPolygon *>(this)->_area = polyArea2() / 2;
       const_cast<rcPolygon *>(this)->_areaValid = true;
     }
   return _area;
 }
int32 rcPolygon::areaSign (const rc2Dvector & a, const rc2Dvector & b, const rc2Dvector & c) const private
Definition at line 1217 of file rc_polygon.cpp.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by convexComparedToConvex(), convexIntersection(), and parallelInter().
 {
   double area2 =
     (b.x() - a.x())*(c.y() - a.y()) - (c.x() - a.x())*(b.y() - a.y());
   if (area2 >  0.0001)
     return  1;
   else if (area2 < -0.0001)
     return -1;
   else
     return  0;
 }
bool rcPolygon::between (const rc2Dvector & a, const rc2Dvector & b, const rc2Dvector & c) const private
Definition at line 1234 of file rc_polygon.cpp.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by contains(), convexComparedToConvex(), and parallelInter().
 {
   /* If ab not vertical, check betweenness on x; else on y. */
   if ( a.x() != b.x() )
     return ((a.x() <= c.x()) && (c.x() <= b.x())) ||
       ((a.x() >= c.x()) && (c.x() >= b.x()));
   else
     return ((a.y() <= c.y()) && (c.y() <= b.y())) ||
       ((a.y() >= c.y()) && (c.y() >= b.y()));
 }
bool rcPolygon::centerOf (rc2Dvector & cof) const
Definition at line 666 of file rc_polygon.cpp.
References _com, _comValid, _vert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcShape::needCenterOfmass(), and rfPolygonToSegmentsCollection().
 {
   if (_vert.size() < 1)
     return false;
   if (_comValid)
     {
       cof = _com;
       return true;
     }
   double cx (0.0), cy (0.0);
   double a = 1.0 / _vert.size();
   for (uint32 i = 0; i < _vert.size(); i++)
     {
       cx += _vert[i].x();
       cy += _vert[i].y();
     }
   cof.x(a * cx);
   cof.y(a * cy);
   const_cast<rcPolygon *>(this)->_com = cof;
   const_cast<rcPolygon *>(this)->_comValid = true;
   return true;
 }
bool rcPolygon::centerOf (rc2Fvector & cof) const
Definition at line 693 of file rc_polygon.cpp.
References _com, _comValid, _vert, rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   if (_vert.size() < 1)
     return false;
   if (_comValid)
     {
       cof.x((float) _com.x());
       cof.y((float) _com.y());
       return true;
     }
   float cx (0.0f), cy (0.0f);
   float a = 1.0f / _vert.size();
   for (uint32 i = 0; i < _vert.size(); i++)
     {
       cx += _vert[i].x();
       cy += _vert[i].y();
     }
   cof.x(a * cx);
   cof.y(a * cy);
   const_cast<rcPolygon *>(this)->_com = rc2Dvector ((double) cof.x(), (double) cof.y());
   const_cast<rcPolygon *>(this)->_comValid = true;
   return true;
 }
double rcPolygon::circularity () const
Definition at line 721 of file rc_polygon.cpp.
References _vert, area(), perimeter(), rk2PI, and rmSquare.
Referenced by rcShape::needCircularity(), and rcVisualFunction::update().
 {
   if (_vert.size() < 2) return 0.0;
   double p (perimeter());
   p = 1.0 / rmSquare (p);
   return 2.0 * rk2PI *  const_cast<rcPolygon *>(this)->area() * p;
 }
void rcPolygon::clear (void) inline
Definition at line 206 of file rc_polygon.h.
   {
     _vert.clear();
   }
bool rcPolygon::collinear (const rc2Dvector & a, const rc2Dvector & b, const rc2Dvector & c) const inline private
Definition at line 1086 of file rc_polygon.cpp.
References triArea2().
 {
   return triArea2(a, b, c) == 0.0;
 }
bool rcPolygon::contains (const rc2Dvector & point) const
Definition at line 257 of file rc_polygon.cpp.
References _vert, between(), rc2dVector< T >::cross(), crossing(), isValid(), rmAssert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcKinetoscope::connectFunction(), contains(), convexComparedToConvex(), convexIntersection(), and intersects().
 {
   rmAssert(isValid());
   //  rc2Dvector rounded(floor(point.x() + 0.5), floor(point.y() + 0.5));
   rc2Dvector rounded = point;
   uint32 vCnt = _vert.size();
   if (vCnt < 3) {
     if (vCnt == 0)
       return false;
     if (vCnt == 1)
       return rounded == _vert[0];
     /* vCnt == 2
      */
     rc2Dvector inter = crossing(_vert[0], _vert[1], rounded);
     return inter == rounded && between(_vert[0], _vert[1], rounded);
   }
   uint32 crossings = 0;
   rc2Dvector normHead = _vert[vCnt-1] - rounded;
   for (uint32 headI = 0; headI < vCnt; headI++) {
     /* Normalize all vertices to have their origin at point. In this
      * way we can check to see if edges intersect the ray formed by
      * starting at the origin and moving in a positive direction along
      * the x axis.
      */
     rc2Dvector normTail = normHead;
     normHead = _vert[headI] - rounded;
     if (normHead == rc2Dvector(0,0))
       return true;
     else if ((normTail.y() == 0 && normHead.y() == 0) &&
          ((normHead.x() > 0 && normTail.x() < 0) ||
           (normHead.x() < 0 && normTail.x() > 0)))
       return true;
     /* Check to see if the edge created by these two vertices
      * crosses the y axis.
      */
     if (((normHead.y() > 0) && (normTail.y() <= 0)) ||
     ((normTail.y() > 0) && (normHead.y() <= 0))) {
       /* If so, find the x value for the location where the edge
        * crosses the y axis. If the crossing point is positive, the
        * edge crosses the ray.
        */
       double x = normHead.cross(normTail)/(normTail.y() - normHead.y());
       if (x == 0)
     return true;
       if (x > 0)
     crossings++;
     }
   }
   /* An odd number of crossings imply the point is inside the polygon,
    * otherwise it lies outside it.
    */
   return (crossings & 1) == 1;
 }
bool rcPolygon::contains (const rcPolygon & polygon) const
Definition at line 322 of file rc_polygon.cpp.
References _vert, contains(), convexComparedToConvex(), DBGPRT, eInterUnknown, endl(), eNoIntersection, eProperIntersection, eSharedCollinear, eVertexIntersection, isConvex(), isValid(), rmAssert, and segmentInter().
 {
   rmAssert(isValid());
   rmAssert(polygon.isValid());
   const int32 tEnd = _vert.size();
   const int32 bEnd = polygon._vert.size();
   if ((tEnd < 2) || (bEnd < 2)) {
     if (bEnd == 0)
       return true;
     else if (tEnd == 0)
       return false;
     if (tEnd == 1) {
       if (bEnd == 1)
     return _vert[0] == polygon._vert[0];
       else // bEnd > 1 ==> polygon is at least a 2D thing.
     return false;
     }
     /* tEnd >= 2 ==> bEnd == 1
      */
     rmAssert(bEnd == 1);
     return contains(polygon._vert[0]);
   }
   /* If the 2 polygons are convex, an O(N) algorithm, based on the
    * convex polygon intersecion code, can be used.  Otherwise, in lieu
    * of any faster known algorithm, the following O(N^2) algorithm is
    * used.
    */
   if (isConvex() && polygon.isConvex())
     return convexComparedToConvex(polygon, true);
   /* Go through and see if any of the edges in this cross any of the
    * edges in polygon. If so, this does not contain polygon. If not,
    * then check to see if any single point in polygon is contained in
    * *this. If this is true, then this contains polygon.
    */
   int32 tHeadI = 0;
   int32 tTailI = tEnd - 1;
   rc2Dvector i1, i2; // Used to to store values calculated by segmentInter().
   vector<bool> onEdge(bEnd), isCollinear(bEnd);
   for (int32 i = 0; i < bEnd; i++)
     onEdge[i] = isCollinear[i] = false;
   while (tHeadI != tEnd) {
     int32 bHeadI = 0;
     int32 bTailI = bEnd - 1;
     while(bHeadI != bEnd) {
       switch (segmentInter(_vert[tHeadI], _vert[tTailI],
                polygon._vert[bHeadI], polygon._vert[bTailI],
                i1, i2))
       {
       case eNoIntersection:
     break;
       case eProperIntersection:
     if (DBGPRT)
       cout << "Return false at: case eProperIntersection" << endl;
     return false;
       case eVertexIntersection:
     if (i1 == polygon._vert[bHeadI])
       onEdge[bHeadI] = true;
     else if (i1 != polygon._vert[bTailI]) {
       if (DBGPRT)
         cout << "Return false at: case eVertexIntersection" << endl;
       return false;
     }
     break;
       case eSharedCollinear:
     onEdge[bHeadI] = true;
     isCollinear[bHeadI] = true;
     break;
       case eInterUnknown:
     rmAssert(0);
     break;
      }
       bTailI = bHeadI;
       bHeadI++;
     }
     tTailI = tHeadI;
     tHeadI++;
   }
   /* No proper intersections were found. Look to see if any of the
    * touching edges can be used to find points outside of this.
    */
   int32 bHeadI = 0;
   int32 bTailI = bEnd - 1;
   while(bHeadI != bEnd) {
     if (onEdge[bHeadI] && !isCollinear[bHeadI]) {
       if (onEdge[bTailI]) {
     double x = polygon._vert[bHeadI].x() +
       (polygon._vert[bTailI].x() - polygon._vert[bHeadI].x())/2;
     double y = polygon._vert[bHeadI].y() +
       (polygon._vert[bTailI].y() - polygon._vert[bHeadI].y())/2;
     rc2Dvector point(x, y);
     if (!contains(point)) {
       if (DBGPRT)
         cout << "Return false at: if (!contains(point))" << endl;
       return false;
     }
       }
       else if (!contains(polygon._vert[bTailI])) {
     if (DBGPRT)
       cout << "Return false at: if (!contains(polygon._vert[bTailI]))" << endl;
     return false;
       }
     }
     bTailI = bHeadI;
     bHeadI++;
   }
   if (DBGPRT)
     cout << "Returning: " <<  contains(polygon._vert[0]) << endl;
   /* Either all the vertices in polygon are contained within this or
    * they are all outside of this.
    */
   return contains(polygon._vert[0]);
 }
bool rcPolygon::convexComparedToConvex (const rcPolygon & polygon, const bool contains) const private
Definition at line 1362 of file rc_polygon.cpp.
References areaSign(), between(), contains(), DBGPRT3, rc2dVector< T >::dot(), eInUnknown, endl(), eNoIntersection, ePIn, eProperIntersection, eQIn, eSharedCollinear, eVertexIntersection, isConvex(), rmAssert, segmentInter(), vert(), and vertexCnt().
Referenced by contains(), and intersects().
 {
   rmAssert(isConvex());
   rmAssert(polygon.isConvex());
   rcPolygon polyInt;
   const rcPolygon& polyP = *this;
   const rcPolygon& polyQ = polygon;
   const rc2Dvector origin(0, 0);
   const int32 pSize = polyP.vertexCnt();
   const int32 qSize = polyQ.vertexCnt();
   deque<rc2Dvector>::const_iterator pHeadI = polyP.vert().begin(),
     qHeadI = polyQ.vert().begin();
   deque<rc2Dvector>::const_iterator pTailI = polyP.vert().end() - 1,
     qTailI = polyQ.vert().end() - 1;
   int32 pAdvances = 0, qAdvances = 0;
   eInState inFlag = eInUnknown;
   bool firstPoint = true;
   rc2Dvector nv1, nv2;
   do {
     rc2Dvector pHead = *pHeadI, pTail = *pTailI;
     rc2Dvector qHead = *qHeadI, qTail = *qTailI;
     rc2Dvector pDelta = pHead - pTail;
     rc2Dvector qDelta = qHead - qTail;
     int cross = areaSign(origin, pDelta, qDelta);
     int qHP = areaSign(pTail, pHead, qHead);
     int pHQ = areaSign(qTail, qHead, pHead);
     eIntersection code = segmentInter(pTail, pHead, qTail, qHead, nv1, nv2);
     if (!contains && (code != eNoIntersection))
       return true;
     if (DBGPRT3) cout << "cross " << cross << " q in H(P) " << qHP
         << " p in H(Q) " << pHQ << endl << endl;
     if ((code == eProperIntersection) || (code == eVertexIntersection)) {
       if ((inFlag == eInUnknown) && firstPoint) {
     pAdvances = qAdvances = 0;
     firstPoint = false;
       }
       if (DBGPRT3) cout << "Case 0 Outputting: " << nv1 << endl;
       polyInt.pushUniqueVertex(nv1);
       if (pHQ > 0)
     inFlag = ePIn;
       else if (qHP > 0)
     inFlag = eQIn;
     }
     /* Advance rules */
     /* Special case: A & B overlap and oppositely oriented.
      */
     if ((code == eSharedCollinear) && (pDelta.dot(qDelta) < 0)) {
       if (DBGPRT3) printf("special case: A & B overlap and oppositely oriented.\n");
       if ((qSize == 2) &&
       between(pHead, pTail, qHead) && between(pHead, pTail, qTail))
     return true;
       else
     return false;
     }
     /* Special case: A & B parallel and separated.
      */
     if ((cross == 0) && (pHQ < 0) && (qHP < 0)) {
       if (DBGPRT3) printf("special case: A & B parallel and separated.\n");
       return false;
     }
     if ((cross == 0) && (pHQ == 0) && (qHP == 0)) {
       /* Advance but do not output point.
        */
       if (inFlag == ePIn) {
     qTailI = qHeadI;
     if (++qHeadI == polyQ.vert().end())
       qHeadI = polyQ.vert().begin();
     qAdvances++;
       }
       else {
     pTailI = pHeadI;
     if (++pHeadI == polyP.vert().end())
       pHeadI = polyP.vert().begin();
     pAdvances++;
       }
     } // else generic cases
     else if (cross >= 0) {
       if (qHP > 0) {
     if (inFlag == ePIn) {
       if (DBGPRT3) cout << "Case 1 Outputting: " << pHead << endl;
       polyInt.pushUniqueVertex(pHead);
     }
     pTailI = pHeadI;
     if (++pHeadI == polyP.vert().end())
       pHeadI = polyP.vert().begin();
     pAdvances++;
       }
       else {
     if (inFlag == eQIn) {
       if (DBGPRT3) cout << "Case 2 Outputting: " << qHead << endl;
       polyInt.pushUniqueVertex(qHead);
     }
     qTailI = qHeadI;
     if (++qHeadI == polyQ.vert().end())
       qHeadI = polyQ.vert().begin();
     qAdvances++;
       }
     }
     else { // cross < 0
       if (pHQ > 0) {
     if (inFlag == eQIn) {
       if (DBGPRT3) cout << "Case 3 Outputting: " << qHead << endl;
       polyInt.pushUniqueVertex(qHead);
     }
     qTailI = qHeadI;
     if (++qHeadI == polyQ.vert().end())
       qHeadI = polyQ.vert().begin();
     qAdvances++;
       }
       else {
     if (inFlag == ePIn) {
       if (DBGPRT3) cout << "Case 4 Outputting: " << pHead << endl;
       polyInt.pushUniqueVertex(pHead);
     }
     pTailI = pHeadI;
     if (++pHeadI == polyP.vert().end())
       pHeadI = polyP.vert().begin();
     pAdvances++;
       }
     }
   } while(((pAdvances < pSize) || (qAdvances < qSize)) &&
       (pAdvances < pSize*2) && (qAdvances < qSize*2));
   if ((polyInt._vert.size() >= 2) &&
       (polyInt._vert.front() == polyInt._vert.back()))
     polyInt._vert.pop_back();
   if (DBGPRT3) {
     cout << polyP << endl;
     cout << polyQ << endl;
     cout << polyInt << endl;
   }
   /* If inFlag has never been set, either the polygons don't intersect
    * or are nested.
    */
   if (inFlag == eInUnknown) {
     if (contains)
       return polyP.contains(polyQ.vert().front());
     else
       return (polyP.contains(polyQ.vert().front()) ||
           polyQ.contains(polyP.vert().front()));
   }
   rmAssert(contains);
   return polyQ == polyInt;
 }
void rcPolygon::convexHull (rcPolygon & polyHull) const inline
Definition at line 366 of file rc_polygon.h.
Referenced by convexIntersection(), convexUnion(), and genMinEnclosingRect().
   { createConvexHull(polyHull); }
void rcPolygon::convexHullConvert () inline
Definition at line 237 of file rc_polygon.h.
Referenced by convexUnion().
   { createConvexHull(*this); }
void rcPolygon::convexIntersection (const rcPolygon & polygon, rcPolygon & polyInt) const
Definition at line 740 of file rc_polygon.cpp.
References _isConvex, _isValid, _knownConvex, _knownValid, _vert, areaSign(), contains(), convexHull(), DBGPRT, rc2dVector< T >::dot(), eInUnknown, endl(), ePIn, eProperIntersection, eQIn, eSharedCollinear, eVertexIntersection, isConvex(), isValid(), pushUniqueVertex(), pushVertex(), rmAssert, rmExceptionMacro, segmentInter(), vert(), and vertexCnt().
Referenced by intersects(), rcMuscleSegmenter::mergePolygons(), and rfComponentPolygons().
 {
   rmAssert(isValid());
   rmAssert(poly.isValid());
   polyInt._vert.clear();
   polyInt._isConvex = polyInt._knownConvex = true;
   polyInt._isValid = polyInt._knownValid = true;
   if ((poly.vertexCnt() < 2) || vertexCnt() < 2) {
     if ((poly.vertexCnt() == 0) || vertexCnt() == 0)
       return;
     if (vertexCnt() == 1) {
       if (poly.contains(_vert[0]))
     polyInt.pushVertex(_vert[0]);
       return;
     }
     /* vertexCnt() >= 2 ==> poly.vertexCnt() == 1
      */
     rmAssert(poly.vertexCnt() == 1);
     if (contains(poly._vert[0]))
       polyInt.pushVertex(poly._vert[0]);
     return;
   }
   rcPolygon convexHullP, convexHullQ;
   if (!isConvex())
     convexHull(convexHullP);
   if (!poly.isConvex())
     poly.convexHull(convexHullQ);
   const rcPolygon& polyP = isConvex() ? *this : convexHullP;
   const rcPolygon& polyQ = poly.isConvex() ? poly : convexHullQ;
   const rc2Dvector origin(0, 0);
   const int32 pSize = polyP.vertexCnt();
   const int32 qSize = polyQ.vertexCnt();
   deque<rc2Dvector>::const_iterator pHeadI = polyP.vert().begin(),
     qHeadI = polyQ.vert().begin();
   deque<rc2Dvector>::const_iterator pTailI = polyP.vert().end() - 1,
     qTailI = polyQ.vert().end() - 1;
   int32 pAdvances = 0, qAdvances = 0;
   eInState inFlag = eInUnknown;
   bool firstPoint = true;
   rc2Dvector nv1, nv2;
   do {
     rc2Dvector pHead = *pHeadI, pTail = *pTailI;
     rc2Dvector qHead = *qHeadI, qTail = *qTailI;
     rc2Dvector pDelta = pHead - pTail;
     rc2Dvector qDelta = qHead - qTail;
     int cross = areaSign(origin, pDelta, qDelta);
     int qHP = areaSign(pTail, pHead, qHead);
     int pHQ = areaSign(qTail, qHead, pHead);
     eIntersection code = segmentInter(pTail, pHead, qTail, qHead, nv1, nv2);
     if (DBGPRT) cout << "cross " << cross << " q in H(P) " << qHP
         << " p in H(Q) " << pHQ << endl << endl;
     if ((code == eProperIntersection) || (code == eVertexIntersection)) {
       if ((inFlag == eInUnknown) && firstPoint) {
     pAdvances = qAdvances = 0;
     firstPoint = false;
       }
       if (DBGPRT) cout << "Case 0 Outputting: " << nv1 << endl;
       polyInt.pushUniqueVertex(nv1);
       if (pHQ > 0)
     inFlag = ePIn;
       else if (qHP > 0)
     inFlag = eQIn;
     }
     /* Advance rules */
     /* Special case: A & B overlap and oppositely oriented.
      */
     if ((code == eSharedCollinear) && (pDelta.dot(qDelta) < 0)) {
       if (DBGPRT) printf("special case: A & B overlap and oppositely oriented.\n");
       polyInt._vert.clear();
       polyInt.pushUniqueVertex(nv1);
       polyInt.pushUniqueVertex(nv2);
       polyInt._isConvex = polyInt._knownConvex = true;
       polyInt._isValid = polyInt._knownValid = true;
       return;
     }
     /* Special case: A & B parallel and separated.
      */
     if ((cross == 0) && (pHQ < 0) && (qHP < 0)) {
       if (DBGPRT) printf("special case: A & B parallel and separated.\n");
       if (polyInt.vertexCnt() != 0)
     rmExceptionMacro(<< "Unresolved Geometry");
       return;
     }
     if ((cross == 0) && (pHQ == 0) && (qHP == 0)) {
       /* Advance but do not output point.
        */
       if (inFlag == ePIn) {
     qTailI = qHeadI;
     if (++qHeadI == polyQ.vert().end())
       qHeadI = polyQ.vert().begin();
     qAdvances++;
       }
       else {
     pTailI = pHeadI;
     if (++pHeadI == polyP.vert().end())
       pHeadI = polyP.vert().begin();
     pAdvances++;
       }
     } // else generic cases
     else if (cross >= 0) {
       if (qHP > 0) {
     if (inFlag == ePIn) {
       if (DBGPRT) cout << "Case 1 Outputting: " << pHead << endl;
       polyInt.pushUniqueVertex(pHead);
     }
     pTailI = pHeadI;
     if (++pHeadI == polyP.vert().end())
       pHeadI = polyP.vert().begin();
     pAdvances++;
       }
       else {
     if (inFlag == eQIn) {
       if (DBGPRT) cout << "Case 2 Outputting: " << qHead << endl;
       polyInt.pushUniqueVertex(qHead);
     }
     qTailI = qHeadI;
     if (++qHeadI == polyQ.vert().end())
       qHeadI = polyQ.vert().begin();
     qAdvances++;
       }
     }
     else { // cross < 0
       if (pHQ > 0) {
     if (inFlag == eQIn) {
       if (DBGPRT) cout << "Case 3 Outputting: " << qHead << endl;
       polyInt.pushUniqueVertex(qHead);
     }
     qTailI = qHeadI;
     if (++qHeadI == polyQ.vert().end())
       qHeadI = polyQ.vert().begin();
     qAdvances++;
       }
       else {
     if (inFlag == ePIn) {
       if (DBGPRT) cout << "Case 4 Outputting: " << pHead << endl;
       polyInt.pushUniqueVertex(pHead);
     }
     pTailI = pHeadI;
     if (++pHeadI == polyP.vert().end())
       pHeadI = polyP.vert().begin();
     pAdvances++;
       }
     }
   } while(((pAdvances < pSize) || (qAdvances < qSize)) &&
       (pAdvances < pSize*2) && (qAdvances < qSize*2));
   if ((polyInt._vert.size() >= 2) &&
       (polyInt._vert.front() == polyInt._vert.back()))
     polyInt._vert.pop_back();
   if (DBGPRT) {
     cout << polyP << endl;
     cout << polyQ << endl;
     cout << polyInt << endl;
   }
   /* If inFlag has never been set, either the polygons don't intersect
    * or are nested.
    */
   if (inFlag == eInUnknown) {
     if (polyP.contains(*(polyQ.vert().begin())))
       polyInt = polyQ;
     else if (polyQ.contains(*(polyP.vert().begin())))
       polyInt = polyP;
   }
   else {
     polyInt._isConvex = polyInt._knownConvex = true;
     polyInt._isValid = polyInt._knownValid = true;
   }
 }
void rcPolygon::convexUnion (const rcPolygon & polygon, rcPolygon & polyUnion) const
Definition at line 956 of file rc_polygon.cpp.
References _isConvex, _isValid, _knownValid, _vert, convexHull(), convexHullConvert(), isConvex(), isValid(), and rmAssert.
Referenced by rcMuscleSegmenter::mergePolygons(), rfComponentPolygons(), and rfPolygonGroupMutualMerge().
 {
   rmAssert(isValid());
   rmAssert(polygon.isValid());
   /* The following algorithm is not from the O'Rourke book, so don't
    * blame him!
    *
    * Step 1: Get the convex hull of each polygon to guarantee that the
    *         minimum number of points are being looked at.
    *
    * Step 2: Create a polygon that is the union of unique vertices in
    *         the two convex hulls.
    *
    * Step 3: Convert the new polygon into a convex hull.
    *
    */
   rcPolygon convexHullP, convexHullQ;
   if (!isConvex())
     convexHull(convexHullP);
   if (!polygon.isConvex())
     polygon.convexHull(convexHullQ);
   const rcPolygon& polyP = isConvex() ? *this : convexHullP;
   const rcPolygon& polyQ = polygon.isConvex() ? polygon : convexHullQ;
   set<rc2Dvector, uniqueOrder<double> > uvert;
   uvert.insert(polyP._vert.begin(), polyP._vert.end());
   uvert.insert(polyQ._vert.begin(), polyQ._vert.end());
   polyUnion._vert.resize(uvert.size());
   polyUnion._isConvex = false;
   set<rc2Dvector>::iterator cur = uvert.begin(), end = uvert.end();
   uint32 i = 0;
   while (cur != end)
     polyUnion._vert[i++] = *cur++;
   polyUnion._knownValid = polyUnion._isValid = true;
   polyUnion.convexHullConvert();
 }
void rcPolygon::createConvexHull (rcPolygon & poly, bool mastBeValid = true) const private
Definition at line 1142 of file rc_polygon.cpp.
References _isConvex, _isValid, _knownConvex, _knownValid, _vert, endl(), isValid(), leftTurn(), and rmAssert.
Referenced by discBuffer().
 {
   if (mastBeValid)
     rmAssert(isValid());
   if (_vert.size() < 3) {
     if (&poly != this)
       poly = *this;
     return;
   }
   /* Find the rightmost lowest point and store an index to it in
    * oIndex.
    */
   uint32 oIndex = 0;
   for (uint32 i = _vert.size() - 1; i; i--) {
     if ((_vert[i].y() < _vert[oIndex].y()) ||
     ((_vert[i].y() == _vert[oIndex].y()) &&
      (_vert[i].x() > _vert[oIndex].x())))
       oIndex = i;
   }
   /* Sort the vertices in ascending theta order around the origin. In
    * case of a tie, the vertice closer to the origin will be deemed to
    * have a smaller value.
    */
   map<rc2Dvector, rc2Dvector, thetaOrder<double> > tOrder;
   const rc2Dvector origin = _vert[oIndex];
   for (uint32 i = 0; i < _vert.size(); i++) {
     const rc2Dvector normLoc = _vert[i] - origin;
     tOrder.insert(pair<rc2Dvector, rc2Dvector>(normLoc, _vert[i]));
   }
   uint32 hullTop = 1;
   deque<rc2Dvector> hullVertices;
   map<rc2Dvector, rc2Dvector>::iterator curr(tOrder.begin());
   map<rc2Dvector, rc2Dvector>::iterator last(tOrder.end());
   const map<rc2Dvector, rc2Dvector>::iterator end(tOrder.end());
   last--;
   hullVertices.push_back(last->second);
   hullVertices.push_back(curr->second);
   curr++;
   while (curr != end) {
     if (leftTurn(hullVertices[hullTop-1], hullVertices[hullTop],
          curr->second)) {
       hullTop++;
       hullVertices.push_back(curr->second);
       curr++;
     }
     else {
       hullTop--;
       hullVertices.pop_back();
     }
     if (0) {
       for (uint32 xx = 0; xx <= hullTop; xx++)
     cout << " " << hullVertices[xx];
       cout << endl;
     }
   }
   hullTop--;
   hullVertices.pop_back(); // Last elmt pushed twice, so pop it off
   poly._vert.clear();
   for (uint32 i = 0; i <= hullTop; i++)
     poly._vert.push_back(hullVertices[i]);
   poly._knownValid = poly._knownConvex = true;
   poly._isValid = poly._isConvex = true;
 }
rc2Dvector rcPolygon::crossing (const rc2Dvector & b0, const rc2Dvector & b1, const rc2Dvector & a) const private
Definition at line 1534 of file rc_polygon.cpp.
References rmAssert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by contains(), findPeak(), and genMinEnclosingRect().
 {
   rc2Dvector d = b1 - b0;
   if (d.x() == 0 || d.y() == 0) {
     if (d.y() == 0) {
       rmAssert(d.x() != 0);
       return rc2Dvector(a.x(), b1.y());
     }
     return rc2Dvector(b1.x(), a.y());
   }
   const double mBase = d.y()/d.x(), mOrth = -d.x()/d.y();
   const double intBase = b1.y() - mBase*b1.x();
   const double intOrth = a.y() - mOrth*a.x();
   const double crossingX = (intOrth - intBase)/(mBase - mOrth);
   const double crossingY = mOrth*crossingX + intOrth;
   return rc2Dvector(crossingX, crossingY);
 }
void rcPolygon::deleteVertex (int32 index)
Definition at line 196 of file rc_polygon.cpp.
References _areaValid, _comValid, _isConvex, _isValid, _knownConvex, _knownValid, _vert, and rmAssert.
 {
   rmAssert(!_vert.empty());
   index = index % (int32)_vert.size();
   _vert.erase(_vert.begin() + index);
   _isConvex = _isValid = _knownValid = _knownConvex = _comValid = _areaValid = false;
 }
rcPolygon rcPolygon::discBuffer (double diameter) const
Definition at line 1942 of file rc_polygon.cpp.
References _vert, rc2dVector< T >::angle(), createConvexHull(), rc2dVector< T >::len(), and pushVertex().
Referenced by rfPolygonGroupMutualMerge(), and rcKinetoscope::visualDebugGraphics().
 {
   rcPolygon buffer;
   for (uint32 i = 0; i < _vert.size(); i++)
     for (uint32 j = 0; j < _vert.size(); j++)
       {
     if (i == j) continue;
     rc2Dvector u2me = _vert[i] - _vert[j];
     double length = u2me.len ();
     rc2Dvector disc (length+diameter, u2me.angle());
     u2me = disc + _vert[j]; // the new stretched end point
     buffer.pushVertex (u2me);
       }
   // It might not be valid, so dont assert and make me valid
   buffer.createConvexHull (buffer, false);
   return buffer;
 }
Edge_const_iterator rcPolygon::edges_begin () const inline
Definition at line 408 of file rc_polygon.h.
   { return Edge_const_iterator(&_vert, _vert.begin()); }
Edge_const_iterator rcPolygon::edges_end () const inline
Definition at line 411 of file rc_polygon.h.
   { return Edge_const_iterator(&_vert, _vert.end()); }
double rcPolygon::ellipseRatio () const
Definition at line 729 of file rc_polygon.cpp.
References _vert, area(), perimeter(), rkPI, and rmSquare.
Referenced by rcShape::needEllipseRatio(), and rcVisualFunction::update().
 {
   if (_vert.size() < 2) return 0.0;
   double ar =  const_cast<rcPolygon *>(this)->area() / rkPI;
   double alpha = (sqrt (ar) + perimeter() / rkPI) / 3.0;
   double a = alpha + sqrt (rmSquare(alpha) - ar);
   return rmSquare (a) / ar;
 }
void rcPolygon::erase (Vertex_iterator pos) inline
Definition at line 198 of file rc_polygon.h.
   { _vert.erase(pos); }
void rcPolygon::erase (Vertex_iterator first, Vertex_iterator last) inline
Definition at line 201 of file rc_polygon.h.
   {
     _vert.erase(first, last);
   }
int32 rcPolygon::findPeak (const int32 startIndex, const rc2Dvector & b0, const rc2Dvector & b1) const private
Definition at line 1559 of file rc_polygon.cpp.
References _vert, crossing(), DBGPRT2, endl(), leftTurn(), rc2dVector< T >::len(), rmAssert, and vertexCnt().
Referenced by genMinEnclosingRect().
 {
   int32 curIndex = startIndex, maxIndex = startIndex;
   int32 vertEnd = vertexCnt() - 1;
   rc2Dvector cross = crossing(b0, b1, _vert[curIndex]);
   rc2Dvector delta = _vert[curIndex] - cross;
   bool lt = leftTurn(b0, b1, _vert[curIndex]);
   double mag = lt ? -1 : 1;
   double maxValue = delta.len() * mag;
   if (DBGPRT2) cout << "      FINDPEAK: SI " <<  startIndex << " B T " << b0
             << " H " << b1 << " VERT " << _vert[curIndex] << " CROSS "
             << cross << " LT " << lt << " VALUE " << maxValue << endl;
   for (;;) {
     if (curIndex == vertEnd)
       curIndex = 0;
     else
       curIndex++;
     cross = crossing(b0, b1, _vert[curIndex]);
     delta = _vert[curIndex] - cross;
     lt = leftTurn(b0, b1,  _vert[curIndex]);
     mag = lt ? -1 : 1;
     double value = delta.len() * mag;
     if (DBGPRT2) cout << "                CI " <<  curIndex << " VERT "
               << _vert[curIndex] << " CROSS " << cross
               << " LT " << lt << " MI " << maxIndex
               << " V " << value << " MV " << maxValue << endl;
     if (value <= maxValue) {
       if (DBGPRT2) cout << "                DONE MI " << maxIndex << endl;
       return maxIndex;
     }
     maxIndex = curIndex;
     maxValue = value;
   }
   rmAssert(0);
   return 0;
 }
rcAffineRectangle rcPolygon::genMinEnclosingRect (bool area) const private
Definition at line 1686 of file rc_polygon.cpp.
References _vert, rc2dVector< T >::angle(), convexHull(), crossing(), DBGPRT2, rcRadian::Double(), endl(), findPeak(), genMinRectBounds(), isConvex(), isValid(), rc2dVector< T >::len(), rcRadian::norm(), rfRoundPlus(), rkPI, rmAssert, size(), vertexCnt(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
   rmAssert(isValid());
   /* Another algorithm not from the O'Rourke book. Use the "rotating
    * caliper" algorithm to determine the polygon's minimum enclosing
    * rectangle.
    */
   rcPolygon hull;
   if (!isConvex())
     convexHull(hull);
   const rcPolygon& hullP = isConvex() ? *this : hull;
   if (hullP._vert.size() <= 2) {
     int32 width = 1;
     rcRadian theta(0);
     if (hullP._vert.size() == 2) {
       rc2Dvector span = _vert[1] - _vert[0];
       width = (int32)span.len();
       if (width == 0)
     width = 1;
       theta = span.angle().norm();
     }
     rc2Dvector origin(-1000000, -1000000);
     if (!hullP._vert.empty())
       origin = _vert[0];
     return rcAffineRectangle(origin, theta, rcDPair(width, 1),
                  rcIPair(width, 1), rcDPair(0, 0));
   }
   /* Step 1 - Choose an inital pair of consecutive points to serve
    *          as the initial base. Using this base, determine an
    *          initial set of points that describe the left, right
    *          and upper limits of the polygon.
    *
    * Step 2 - Replace one of the base points with the next
    *          consecutive point, effectively rotqating the polygon
    *          one turn. Using the existing left, right and upper
    *          limit points, calculate new ones. Check to see of
    *          these describe a new minimum enclosing rectangle.
    *
    * Step 3 - Repeat step 2 until the original base has been rotated
    *          >= pi/2 degrees.
    *
    * Note: This code assumes the points in a hull are stored
    *       counterclockwise.
    */
   int32 prevLoc = 0, curLoc = 1, nextLoc = 2;
   int32 vertEnd = vertexCnt() - 1;
   const rc2Dvector base = _vert[curLoc] - _vert[prevLoc];
   rcRadian minAreaTheta(base.angle().norm()), minPerimTheta(minAreaTheta);
   rc2Dvector orthCross = crossing(_vert[prevLoc], _vert[curLoc], _vert[nextLoc]);
   if (DBGPRT2) cout << "I: curLoc " << curLoc
             << " angle " << minAreaTheta.Double()*180/rkPI
             << " base T " <<  _vert[prevLoc]
             << " H " <<  _vert[curLoc]
             << " orth T " <<  orthCross
             << " H " <<  _vert[nextLoc] << endl;
   int32 leftPt, rightPt, topPt;
   /* Calculate extreme points and generate initial minimum area and
    * lower-left corner point.
    */
   rightPt = findPeak(curLoc, orthCross, _vert[nextLoc]);
   topPt = findPeak(curLoc, _vert[curLoc], _vert[prevLoc]);
   leftPt = findPeak(topPt, _vert[nextLoc], orthCross);
   if (DBGPRT2) cout << "   leftPt " << leftPt << " rightPt " << rightPt
             << " topPt " << topPt << endl;
   rc2Dvector minPerimLL, minPerimDim, minAreaLL, minAreaDim;
   genMinRectBounds(_vert[topPt], _vert[curLoc],
            _vert[leftPt], _vert[rightPt],
            base.x(), base.y(), minAreaLL, minAreaDim);
   minPerimLL = minAreaLL;
   minPerimDim = minAreaDim;
   if (DBGPRT2) cout << "   MIN AREA: lowerleft " << minAreaLL
             << " dim " << minAreaDim << " theta "
             << minAreaTheta.Double()*180/rkPI << endl
             << "   MIN PERIM: lowerleft " << minPerimLL
             << " dim " << minPerimDim << " theta "
             << minPerimTheta.Double()*180/rkPI << endl << endl;
   do {
     prevLoc = curLoc;
     curLoc = nextLoc;
     if (nextLoc == vertEnd)
       nextLoc = 0;
     else
       nextLoc++;
     const rc2Dvector curBase = _vert[curLoc] - _vert[prevLoc];
     const rcRadian curTheta = curBase.angle().norm();
     orthCross = crossing(_vert[prevLoc], _vert[curLoc], _vert[nextLoc]);
     if (DBGPRT2) cout << "M: curLoc " << curLoc
               << " angle " << curTheta.Double()*180/rkPI
               << " base T " <<  _vert[prevLoc]
               << " H " <<  _vert[curLoc]
               << " orth T " <<  _vert[nextLoc]
               << " H " <<  orthCross << endl;
     rightPt = findPeak(rightPt, orthCross, _vert[nextLoc]);
     topPt = findPeak(topPt, _vert[curLoc], _vert[prevLoc]);
     leftPt = findPeak(leftPt, _vert[nextLoc], orthCross);
     if (DBGPRT2) cout << "   leftPt " << leftPt << " rightPt " << rightPt
               << " topPt " << topPt << endl;
     rc2Dvector curLL, curDim;
     genMinRectBounds(_vert[topPt], _vert[curLoc],
              _vert[leftPt], _vert[rightPt],
              curBase.x(), curBase.y(), curLL, curDim);
     if (curDim.x() + curDim.y() < minPerimDim.x() + minPerimDim.y()) {
       minPerimLL = curLL;
       minPerimDim = curDim;
       minPerimTheta = curTheta;
     }
     else if ((curDim.x() + curDim.y() == minPerimDim.x() + minPerimDim.y()) &&
          (curDim.x()*curDim.y() < minPerimDim.x()*minPerimDim.y())) {
       minPerimLL = curLL;
       minPerimDim = curDim;
       minPerimTheta = curTheta;
     }
     if (curDim.x()*curDim.y() < minAreaDim.x()*minAreaDim.y()) {
       minAreaLL = curLL;
       minAreaDim = curDim;
       minAreaTheta = curTheta;
     }
     else if ((curDim.x()*curDim.y() == minAreaDim.x()*minAreaDim.y()) &&
          (curDim.x() + curDim.y() < minAreaDim.x() + minAreaDim.y())) {
       minAreaLL = curLL;
       minAreaDim = curDim;
       minAreaTheta = curTheta;
     }
     if (DBGPRT2) cout << "  ?lowerleft " << curLL << " ?dim " << curDim
               << " ?theta " << curTheta.Double()*180/rkPI << endl
               << "   MIN AREA: lowerleft " << minAreaLL
               << " dim " << minAreaDim << " theta "
               << minAreaTheta.Double()*180/rkPI << endl
               << "   MIN PERIM: lowerleft " << minPerimLL
               << " dim " << minPerimDim << " theta "
               << minPerimTheta.Double()*180/rkPI << endl << endl;
   } while (curLoc != 1);
   if (area) {
     rcDPair size;
     size.x() = minAreaDim.x() + 1;
     size.y() = minAreaDim.y() + 1;
     static const int32 dum (0);
     return rcAffineRectangle(minAreaLL, minAreaTheta, size,
                  rcIPair(rfRoundPlus(size.x(), dum),
                      rfRoundPlus(size.y(), dum)),
                  rcDPair(0, 0));
   }
   else {
     rcDPair size;
     size.x() = minPerimDim.x() + 1;
     size.y() = minPerimDim.y() + 1;
     static const int32 dum (0);
     return rcAffineRectangle(minPerimLL, minPerimTheta, size,
                  rcIPair(rfRoundPlus(size.x(), dum),
                      rfRoundPlus(size.y(), dum)),
                  rcDPair(0, 0));
   }
 }
void rcPolygon::genMinRectBounds (const rc2Dvector & topPt, const rc2Dvector & btmPt, const rc2Dvector & leftPt, const rc2Dvector & rightPt, double mx, double my, rc2Dvector & llPt, rc2Dvector & dim) const private
Definition at line 1609 of file rc_polygon.cpp.
References DBGPRT2, endl(), rc2dVector< T >::len(), rmAssert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by genMinEnclosingRect().
 {
   if (DBGPRT2) cout << "gmrb T " << topPt << " B " << btmPt
             << " L " << leftPt << " R " << rightPt
             << " mx " << mx << " my " << my << endl;
   /* First, handle case of rectangle orthogonal to image plane.
    */
   if ((mx == 0) || (my == 0)) {
     if (my == 0) {
       rmAssert(mx != 0);
       if (rightPt.x() > leftPt.x())
     dim = rc2Dvector(rightPt.x() - leftPt.x(), topPt.y() - btmPt.y()); // x+
       else
     dim = rc2Dvector(leftPt.x() - rightPt.x(), btmPt.y() - topPt.y()); // x-
       llPt = rc2Dvector(leftPt.x(), btmPt.y());
     }
     else { // mx == 0
       if (rightPt.y() > leftPt.y())
     dim = rc2Dvector(rightPt.y() - leftPt.y(), btmPt.x() - topPt.x()); // y+
       else
     dim = rc2Dvector(leftPt.y() - rightPt.y(), topPt.x() - btmPt.x()); // y-
       llPt = rc2Dvector(btmPt.x(), leftPt.y());
     }
     return;
   }
   /* Handle all other cases by using the following algorithm:
    *
    * 1) Find the slope and y-intercept formula for each side.
    *
    * 2) Set the equations equal for 3 of the pairs of intersecting
    *    sides.
    *
    * The result of this will be the extreme values of the enclosing
    * rectangle.
    */
   const double mHor = my/mx;
   const double mVert = -mx/my;
   double intT = topPt.y() - mHor*topPt.x();
   double intB = btmPt.y() - mHor*btmPt.x();
   double intL = leftPt.y() - mVert*leftPt.x();
   double intR = rightPt.y() - mVert*rightPt.x();
   const double upperLeftX = (intT - intL)/(mVert - mHor);
   const double upperLeftY = mHor*upperLeftX + intT;
   const double lowerLeftX = (intB - intL)/(mVert - mHor);
   const double lowerLeftY = mHor*lowerLeftX + intB;
   const double lowerRightX = (intB - intR)/(mVert - mHor);
   const double lowerRightY = mHor*lowerRightX + intB;
   /* Set up return values.
    */
   llPt = rc2Dvector(lowerLeftX, lowerLeftY);
   const rc2Dvector ulPt = rc2Dvector(upperLeftX, upperLeftY);
   const rc2Dvector hgtVec = ulPt - llPt;
   const rc2Dvector lrPt = rc2Dvector(lowerRightX, lowerRightY);
   const rc2Dvector widthVec = lrPt - llPt;
   dim = rc2Dvector(widthVec.len(), hgtVec.len());
 }
void rcPolygon::insertVertex (const rc2Dvector & vertex, int32 after)
Definition at line 206 of file rc_polygon.cpp.
References _areaValid, _comValid, _isConvex, _isValid, _knownConvex, _knownValid, _vert, rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   rc2Dvector rounded(floor(vertex.x() + 0.5), floor(vertex.y() + 0.5));
   if (_vert.size()) {
     after = (after+1) % (int32)(_vert.size() + 1);
     _vert.insert(_vert.begin() + after, rounded);
   }
   else
     _vert.push_back(rounded);
   _isConvex = _isValid = _knownValid = _knownConvex = _comValid = _areaValid = false;
 }
bool rcPolygon::intersection (const rc2Dvector & a0, const rc2Dvector & a1, const rc2Dvector & b0, const rc2Dvector & b1, rc2Dvector * inter) const private
Definition at line 1092 of file rc_polygon.cpp.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by isValid().
 {
   double denom =
     a0.x() * (b1.y() - b0.y()) +
     a1.x() * (b0.y() - b1.y()) +
     b0.x() * (a0.y() - a1.y()) +
     b1.x() * (a1.y() - a0.y());
   /* If denom is zero, the line segments are parallel. In this case,
    * return false even though the segments might overlap.
    */
   if (denom == 0.0)
     return false;
   double s =
     (a0.x() * (b1.y() - b0.y()) +
      b0.x() * (a0.y() - b1.y()) +
      b1.x() * (b0.y() - a0.y())) / denom;
   double t =
     -(a0.x() * (b0.y() - a1.y()) +
       a1.x() * (a0.y() - b0.y()) +
       b0.x() * (a1.y() - a0.y())) / denom;
   if (inter)
     *inter = rc2Dvector(a0.x() + s*(a1.x() - a0.x()),
             a0.y() + s*(a1.y() - a0.y()));
   return (0.0 <= s) && (s <= 1.0) && (0.0 <= t) && (t <= 1.0);
 }
bool rcPolygon::intersects (const rcPolygon & polygon) const
Definition at line 453 of file rc_polygon.cpp.
References _vert, contains(), convexComparedToConvex(), eInterUnknown, eNoIntersection, eProperIntersection, eSharedCollinear, eVertexIntersection, isConvex(), isValid(), rmAssert, and segmentInter().
Referenced by rcKinetoscope::associate(), intersects(), rcKinetoscope::newGeneration(), rfOfCellsAndPolys(), and rfPolygonGroupMutualMerge().
 {
   rmAssert(isValid());
   rmAssert(polygon.isValid());
   const int32 tEnd = _vert.size();
   const int32 bEnd = polygon._vert.size();
   if ((tEnd < 2) || (bEnd < 2)) {
     if (bEnd == 0 || tEnd == 0)
       return false;
     if (bEnd == 1 && tEnd == 1)
     return _vert[0] == polygon._vert[0];
     if (bEnd == 1) // and tEnd > 2
       return contains(polygon._vert[0]);
     else // tEnd == 1 and bEnd > 2
       return polygon.contains(_vert[0]);
   }
   /* If the 2 polygons are convex, an O(N) algorithm, based on the
    * convex polygon intersecion code, can be used.  Otherwise, in lieu
    * of any faster known algorithm, the following O(N^2) algorithm is
    * used.
    */
   if (isConvex() && polygon.isConvex())
     return convexComparedToConvex(polygon, false);
   /* Go through and see if any of the edges in this cross any of the
    * edges in polygon. If so, they intersect. If not, then check to
    * see if the polygons are nested.
    */
   int32 tHeadI = 0;
   int32 tTailI = tEnd - 1;
   rc2Dvector i1, i2; // Used to to store values calculated by segmentInter().
   while (tHeadI != tEnd) {
     int32 bHeadI = 0;
     int32 bTailI = bEnd - 1;
     while(bHeadI != bEnd) {
       switch (segmentInter(_vert[tHeadI], _vert[tTailI],
                polygon._vert[bHeadI], polygon._vert[bTailI],
                i1, i2))
       {
       case eNoIntersection:
     break;
       case eProperIntersection:
       case eVertexIntersection:
       case eSharedCollinear:
     return true;
       case eInterUnknown:
     rmAssert(0);
     break;
      }
       bTailI = bHeadI;
       bHeadI++;
     }
     tTailI = tHeadI;
     tHeadI++;
   }
   /* Either all the vertices in polygon are contained within this or
    * they are all outside of this.
    */
   return contains(polygon._vert[0]) || polygon.contains(_vert[0]);
 }
bool rcPolygon::intersects (const vector< rcPolygon > & group, vector< rcPolygon > & groupIntersects, float areaRatio = 0.25f) const
Definition at line 71 of file rc_polygongroup.cpp.
References area(), convexIntersection(), intersects(), orthogonalEnclosingRect(), rcRectangle< T >::overlaps(), and rmAssert.
 {
   vector<rcPolygon>::const_iterator mpolys = group.begin();
   groupIntersects.clear ();
   rmAssert (areaRatio > 0.0 || areaRatio <= 1.0);
   rcIRect br = orthogonalEnclosingRect ();
   for (; mpolys != group.end(); mpolys++)
     {
       rcIRect ar = mpolys->orthogonalEnclosingRect ();
       if (!br.overlaps (ar))
     continue;
       if (intersects (*mpolys) && (&(*mpolys) != this))
     {
       rcPolygon intPoly;
       float areaThr = mpolys->area () * areaRatio;
       convexIntersection(*mpolys, intPoly);
       if (intPoly.area() > areaThr)
         groupIntersects.push_back (*mpolys);
     }
     }
   return groupIntersects.size() != 0;
 }
int32 rcPolygon::intersects (const vector< rcPolygon > & group, float areaRatio = 0.25f) const
Definition at line 98 of file rc_polygongroup.cpp.
References area(), convexIntersection(), intersects(), orthogonalEnclosingRect(), rcRectangle< T >::overlaps(), and rmAssert.
 {
   vector<rcPolygon>::const_iterator mpolys = group.begin();
   rmAssert (areaRatio > 0.0 || areaRatio <= 1.0);
   int32 num (0);
   rcIRect br = orthogonalEnclosingRect ();
   for (; mpolys != group.end(); mpolys++)
     {
       rcIRect ar = mpolys->orthogonalEnclosingRect ();
       if (!br.overlaps (ar))
     continue;
       if (intersects (*mpolys) && (&(*mpolys) != this))
     {
       rcPolygon intPoly;
       float areaThr = mpolys->area () * areaRatio;
       convexIntersection(*mpolys, intPoly);
       num += intPoly.area() > areaThr;
     }
     }
   return num;
 }
bool rcPolygon::isConvex () const
Definition at line 594 of file rc_polygon.cpp.
References _isConvex, _knownConvex, _knownValid, _vert, isValid(), leftTurn(), and vertexCnt().
Referenced by contains(), convexComparedToConvex(), convexIntersection(), convexUnion(), genMinEnclosingRect(), intersects(), operator==(), and rcPolygon().
 {
   if (_knownConvex)
     return _isConvex;
   if (!_knownValid && !isValid())
     return false;
   rcPolygon* This = const_cast<rcPolygon*>(this);
   This->_knownConvex = This->_isConvex = true;
   int32 vertCnt = vertexCnt();
   if (vertCnt < 3)
     return true;
   for (int32 i = 2; i < vertCnt; i++)
     if (!leftTurn(_vert[i-2], _vert[i-1], _vert[i])) {
       This->_isConvex = false;
       return false;
     }
   if (!leftTurn(_vert[vertCnt-2], _vert[vertCnt-1], _vert[0]) ||
       !leftTurn(_vert[vertCnt-1], _vert[0], _vert[1]))
       This->_isConvex = false;
   return _isConvex;
 }
bool rcPolygon::isValid () const
Definition at line 524 of file rc_polygon.cpp.
References _isValid, _knownValid, _vert, DBGPRT, endl(), intersection(), and vertexCnt().
Referenced by area(), contains(), convexIntersection(), convexUnion(), createConvexHull(), genMinEnclosingRect(), intersects(), isConvex(), operator==(), orthogonalEnclosingRect(), and rcShape::rcShape().
 {
   if (_knownValid)
     return _isValid;
   rcPolygon* This = const_cast<rcPolygon*>(this);
   This->_knownValid = This->_isValid = true;
   int32 vertCnt = vertexCnt();
   if (vertCnt < 3)
     return true;
   for (int32 i = 1; i < vertCnt-1; i++) {
     /* Checks for duplicate points between consecutive line segments.
      */
     if ((_vert[i-1] == _vert[i]) ||
     (_vert[i-1] == _vert[i+1]) ||
     (_vert[i] == _vert[i+1])) {
       if (DBGPRT)
     cout << "Not valid 0: duplicates " << _vert[i-1] << _vert[i]
          << _vert[i+1] << endl;
       This->_isValid = false;
       return false;
     }
     /* For all others but the first line segment, check for a crossing
      * with the last line segment.
      */
     if ((i != 1) && intersection(_vert[vertCnt-1], _vert[0],
                  _vert[i-1], _vert[i], 0)) {
       if (DBGPRT)
     cout << "Not valid 1: intersection " << _vert[vertCnt-1] << _vert[0]
          << " and " << _vert[i-1] << _vert[i] << endl;
       This->_isValid = false;
       return false;
     }
     /* Now check for a crossing with all other line segments in the
      * polygon.
      */
     for (int32 j = i+2; j < vertCnt; j++) {
       if (intersection(_vert[i-1], _vert[i],
                _vert[j-1], _vert[j], 0)) {
     if (DBGPRT)
       cout << "Not valid 2: intersection " << _vert[i-1] << _vert[i]
            << " and " << _vert[j-1] << _vert[j] << endl;
     This->_isValid = false;
     return false;
       }
     }
   } // End of: for (int32 i = 1; i < vertCnt; i++) {
   /* Finally, check for duplicate points between consecutive line
    * segments in the range [vertCnt-2, 1].
    */
   if ((_vert[vertCnt-2] == _vert[0]) ||
       (_vert[vertCnt-1] == _vert[0]) ||
       (_vert[vertCnt-1] == _vert[1])) {
     if (DBGPRT)
       cout << "Not valid 3: duplicates " << _vert[vertCnt-2]
        << _vert[vertCnt-1] << _vert[1] << _vert[0] << endl;
     This->_isValid = false;
     return false;
   }
   return true;
 }
bool rcPolygon::leftTurn (const rc2Dvector & a, const rc2Dvector & b, const rc2Dvector & c) const inline private
Definition at line 1074 of file rc_polygon.cpp.
References triArea2().
Referenced by createConvexHull(), findPeak(), and isConvex().
 {
   return triArea2(a, b, c) > 0.0;
 }
bool rcPolygon::leftTurnOrOn (const rc2Dvector & a, const rc2Dvector & b, const rc2Dvector & c) const inline private
Definition at line 1080 of file rc_polygon.cpp.
References triArea2().
 {
   return triArea2(a, b, c) >= 0.0;
 }
rcAffineRectangle rcPolygon::minimumAreaEnclosingRect () const inline
Definition at line 376 of file rc_polygon.h.
Referenced by rcEngineImpl::muscleTracker(), and rcShape::needAffineRect().
   { return genMinEnclosingRect(true); }
rcAffineRectangle rcPolygon::minimumPerimeterEnclosingRect () const inline
Definition at line 378 of file rc_polygon.h.
Referenced by rcVisualFunction::rcVisualFunction().
   { return genMinEnclosingRect(false); }
rcIRect rcPolygon::orthogonalEnclosingRect () const
Definition at line 1043 of file rc_polygon.cpp.
References rcRectangle< T >::height(), rcRectangle< T >::ul(), and rcRectangle< T >::width().
Referenced by rcVisualFunction::cardiacUpdate(), intersects(), rcMuscleSegmenter::mergePolygons(), orthogonalEnclosingRect(), rcDrawPolygon(), rcFillPolygon(), rcVisualFunction::rcVisualFunction(), rfComponentPolygons(), rfPolygonToSegmentsCollection(), and rcVisualFunction::update().
 {
   rcDRect d;
   orthogonalEnclosingRect(d);
   return rcIRect((int32) d.ul().x(),
          (int32) d.ul().y(),
          (int32) d.width(), (int32) d.height());
 }
void rcPolygon::orthogonalEnclosingRect (rcDRect & r) const
Definition at line 1003 of file rc_polygon.cpp.
References _vert, isValid(), and rmAssert.
 {
   rmAssert(isValid());
   if (_vert.empty())
     {
       r = rcDRect ();
       return;
     }
   double minX = _vert[0].x(), minY = _vert[0].y();
   double maxX = minX, maxY = minY;
   for (uint32 i = 1; i < _vert.size(); i++) {
     if (_vert[i].x() < minX)
       minX = _vert[i].x();
     else if (_vert[i].x() > maxX)
       maxX = _vert[i].x();
     if (_vert[i].y() < minY)
       minY = _vert[i].y();
     else if (_vert[i].y() > maxY)
       maxY = _vert[i].y();
   }
   r = rcDRect(minX, minY, (maxX-minX), (maxY-minY));
 }
void rcPolygon::orthogonalEnclosingRect (rcFRect & fr) const
Definition at line 1031 of file rc_polygon.cpp.
References rcRectangle< T >::height(), orthogonalEnclosingRect(), rcRectangle< T >::ul(), and rcRectangle< T >::width().
 {
   rcDRect d;
   orthogonalEnclosingRect(d);
   fr = rcFRect((float) d.ul().x(),
          (float) d.ul().y(),
          (float) d.width(), (float) d.height());
 }
rcPolygon::eIntersection rcPolygon::parallelInter (const rc2Dvector & a0, const rc2Dvector & a1, const rc2Dvector & b0, const rc2Dvector & b1, rc2Dvector & inter1, rc2Dvector & inter2) const private
Definition at line 1247 of file rc_polygon.cpp.
References areaSign(), between(), DBGPRT, endl(), eNoIntersection, and eSharedCollinear.
Referenced by segmentInter().
 {
   eIntersection retVal = eNoIntersection;
   if (areaSign(a0, a1, b0) != 0)
     retVal = eNoIntersection;
   else if (between(a0, a1, b0) && between(a0, a1, b1)) {
     inter1 = b0;
     inter2 = b1;
     retVal = eSharedCollinear;
   }
   else if (between(b0, b1, a0) && between(b0, b1, a1)) {
     inter1 = a0;
     inter2 = a1;
     retVal = eSharedCollinear;
   }
   else if (between(a0, a1, b0) && between(b0, b1, a1)) {
     inter1 = b0;
     inter2 = a1;
     retVal = eSharedCollinear;
   }
   else if (between(a0, a1, b0) && between(b0, b1, a0)) {
     inter1 = b0;
     inter2 = a0;
     retVal = eSharedCollinear;
   }
   else if (between(a0, a1, b1) && between(b0, b1, a1)) {
     inter1 = b1;
     inter2 = a1;
     retVal = eSharedCollinear;
   }
   else if (between(a0, a1, b1) && between(b0, b1, a0)) {
     inter1 = b1;
     inter2 = a0;
     retVal = eSharedCollinear;
   }
   if (DBGPRT) {
     if (retVal == eNoIntersection) cout << " No intersection" << endl;
     if (retVal == eSharedCollinear) {
       cout << " INTER1: " << inter1 << " INTER2: " << inter2;
       cout << " Shared collinear vertices" << endl;
     }
   }
   return retVal;
 }
double rcPolygon::perimeter () const
Definition at line 643 of file rc_polygon.cpp.
References _vert, and rc2dVector< T >::len().
Referenced by circularity(), ellipseRatio(), rcShape::needPerimeter(), operator<<(), and rcVisualFunction::update().
 {
   if (_vert.size() < 2)
     return 0;
   deque<rc2Dvector>::const_iterator pHeadI = _vert.begin();
   deque<rc2Dvector>::const_iterator pTailI = _vert.end() - 1;
   double length = 0.0;
   while (pHeadI != _vert.end()) {
     rc2Dvector delta = *pHeadI - *pTailI;
     length += delta.len();
     pTailI = pHeadI;
     pHeadI++;
   }
   return length;
 }
double rcPolygon::polyArea2 () const private
Definition at line 1062 of file rc_polygon.cpp.
References _vert, count(), and triArea2().
Referenced by area().
 {
   int32 count = (int32)_vert.size() - 1;
   double sum = 0.0;
   for (int32 i = 1; i < count; i++) {
     sum += triArea2(_vert[0], _vert[i], _vert[i+1]);
   }
   return (sum < 0 ? -sum : sum);
 }
void rcPolygon::popVertex ()
Definition at line 187 of file rc_polygon.cpp.
References _areaValid, _comValid, _isConvex, _isValid, _knownConvex, _knownValid, _vert, and rmAssert.
 {
   rmAssert(!_vert.empty());
   _vert.pop_back();
   _isConvex = _isValid = _knownValid = _knownConvex = _comValid = _areaValid = false;
 }
bool rcPolygon::pushUniqueVertex (const rc2Dvector & vertex)
Definition at line 174 of file rc_polygon.cpp.
References _areaValid, _comValid, _isConvex, _isValid, _knownConvex, _knownValid, _vert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by convexIntersection().
 {
   rc2Dvector rounded(floor(vertex.x() + 0.5), floor(vertex.y() + 0.5));
   if (!_vert.empty() && (_vert.back() == rounded))
     return false;
   _vert.push_back(rounded);
   _isConvex = _isValid = _knownValid = _knownConvex = _comValid = _areaValid = false;
   return true;
 }
void rcPolygon::pushVertex (const rc2Dvector & vertex)
Definition at line 164 of file rc_polygon.cpp.
References _areaValid, _comValid, _isConvex, _isValid, _knownConvex, _knownValid, _vert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by convexIntersection(), discBuffer(), and rcPolygon().
 {
   rc2Dvector rounded(floor(vertex.x() + 0.5), floor(vertex.y() + 0.5));
   _vert.push_back(rounded);
   _isConvex = _isValid = _knownValid = _knownConvex = _comValid = _areaValid = false;
 }
void rcPolygon::reverse_orientation () inline
Definition at line 211 of file rc_polygon.h.
   {
     if (size() <= 1)
       return;
     Container_P::iterator i = _vert.begin();
     std::reverse(++i, _vert.end());
   }
rcPolygon::eIntersection rcPolygon::segmentInter (const rc2Dvector & a0, const rc2Dvector & a1, const rc2Dvector & b0, const rc2Dvector & b1, rc2Dvector & inter1, rc2Dvector & inter2) const private
Definition at line 1298 of file rc_polygon.cpp.
References DBGPRT, eInterUnknown, endl(), eNoIntersection, eProperIntersection, eSharedCollinear, eVertexIntersection, parallelInter(), rmAssert, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by contains(), convexComparedToConvex(), convexIntersection(), and intersects().
 {
   eIntersection retVal = eInterUnknown;
   if (DBGPRT) cout << "P (H,T): (" << a1 << "," << a0
            << ") Q (H,T): (" << b1 << "," << b0 << ") ==>";
   double denom =
     a0.x() * (b1.y() - b0.y()) +
     a1.x() * (b0.y() - b1.y()) +
     b0.x() * (a0.y() - a1.y()) +
     b1.x() * (a1.y() - a0.y());
   /* If denom is zero, the line segments are parallel. call special
    * case code to handle it.
    */
   if (denom == 0.0)
     return parallelInter(a0, a1, b0, b1, inter1, inter2);
   double s =
     (a0.x() * (b1.y() - b0.y()) +
      b0.x() * (a0.y() - b1.y()) +
      b1.x() * (b0.y() - a0.y()));
   if ((s == 0) || (s == denom))
     retVal = eVertexIntersection;
   s = s/denom;
   double t =
     -(a0.x() * (b0.y() - a1.y()) +
       a1.x() * (a0.y() - b0.y()) +
       b0.x() * (a1.y() - a0.y()));
   if ((t == 0) || (t == denom))
     retVal = eVertexIntersection;
   t = t/denom;
   inter1 = rc2Dvector(a0.x() + s*(a1.x() - a0.x()),
               a0.y() + s*(a1.y() - a0.y()));
   if ((0.0 < s) && (s < 1.0) && (0.0 < t) && (t < 1.0))
     retVal = eProperIntersection;
   else if ((0.0 > s) || (s > 1.0) || (0.0 > t) || (t > 1.0))
     retVal = eNoIntersection;
   rmAssert(retVal != eInterUnknown);
   if (DBGPRT) {
     if (retVal != eNoIntersection)
       cout << " INTER1: " << inter1;
     if (retVal == eNoIntersection) cout << " No intersection" << endl;
     if (retVal == eProperIntersection) cout << " Proper intersection" << endl;
     if (retVal == eVertexIntersection) cout << " Vertex intersection" << endl;
     if (retVal == eSharedCollinear) cout << " Shared collinear vertices" << endl;
   }
   return retVal;
 }
int32 rcPolygon::size () const
Referenced by genMinEnclosingRect().
void rcPolygon::transform (const rc2Xform & xfm)
Definition at line 238 of file rc_polygon.cpp.
References _areaValid, _comValid, _vert, rc2Xform::mapPoint(), and vertexCnt().
Referenced by rcVisualFunction::cardiacUpdate(), rcKinetoscope::preSegmentedBodies(), and rcVisualFunction::rcVisualFunction().
 {
   int32 vCnt = vertexCnt();
   for (int32 i = 0; i < vCnt; i++)
     const_cast<rcPolygon *>(this)->_vert[i] = xfm.mapPoint (const_cast<rcPolygon *>(this)->_vert[i]) + 0.5;
   const_cast<rcPolygon *>(this)->_comValid = false;
   const_cast<rcPolygon *>(this)->_areaValid = false;
 }
void rcPolygon::translate (const rc2Dvector & delta)
Definition at line 226 of file rc_polygon.cpp.
References _areaValid, _comValid, _vert, vertexCnt(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcMuscleSegmenter::genPolygons(), rfComponentPolygons(), and translate().
 {
   rc2Dvector rounded(floor(delta.x() + 0.5), floor(delta.y() + 0.5));
   int32 vCnt = vertexCnt();
   for (int32 i = 0; i < vCnt; i++)
     _vert[i] = _vert[i] + rounded;
   _comValid = false;
   _areaValid = false;
 }
void rcPolygon::translate (const rc2Fvector & delta)
Definition at line 220 of file rc_polygon.cpp.
References translate(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   rc2Dvector d (delta.x(), delta.y());
   translate (d);
 }
double rcPolygon::triArea2 (const rc2Dvector & a, const rc2Dvector & b, const rc2Dvector & c) const inline private
Definition at line 1054 of file rc_polygon.cpp.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by collinear(), leftTurn(), leftTurnOrOn(), and polyArea2().
 {
   return (a.x()*b.y() - a.y()*b.x() +
       a.y()*c.x() - a.x()*c.y() +
       b.x()*c.y() - b.y()*c.x());
 }
const deque<rc2Dvector>& rcPolygon::vert () const inline private
Definition at line 480 of file rc_polygon.h.
Referenced by convexComparedToConvex(), and convexIntersection().
 { return _vert; }
const rc2Dvector & rcPolygon::vertexAt (int32 index) const
Definition at line 248 of file rc_polygon.cpp.
References _vert, and rmAssert.
Referenced by operator<<(), operator==(), rcDrawPolygon(), rcFillPolygon(), rfGenerateSmoothingPts(), and rfPolygonToSegmentsCollection().
 {
   rmAssert(_vert.size());
   index = index % (int32)_vert.size();
   return _vert[index];
 }
int32 rcPolygon::vertexCnt () const
Definition at line 624 of file rc_polygon.cpp.
References _vert.
Referenced by convexComparedToConvex(), convexIntersection(), findPeak(), genMinEnclosingRect(), isConvex(), isValid(), operator<<(), operator==(), rcDrawPolygon(), rcFillPolygon(), rfGenerateSmoothingPts(), rfPolygonToSegmentsCollection(), transform(), and translate().
 {
   return (int32)_vert.size();
 }
Vertex_const_iterator rcPolygon::vertices_begin () const inline
Definition at line 402 of file rc_polygon.h.
References _vert.
   { return const_cast<rcPolygon&>(*this)._vert.begin(); }
Vertex_const_iterator rcPolygon::vertices_end () const inline
Definition at line 405 of file rc_polygon.h.
References _vert.
   { return const_cast<rcPolygon&>(*this)._vert.end(); }
Friends And Related Function Documentation
bool operator!= (const rcPolygon & a, const rcPolygon & b) friend
Definition at line 488 of file rc_polygon.h.
 {
   return !operator==(a, b);
 }
ostream& operator<< (ostream & ous, const rcPolygon & p) friend
Definition at line 1866 of file rc_polygon.cpp.
 {
   const int32 vertexCnt = p.vertexCnt();
   rc2Dvector cop;
   const_cast<rcPolygon *>(&p)->centerOf (cop);
   std::string yConvex("CY"), nConvex("CN"), uConvex("C?");
   std::string yValid("VY"), nValid("VN"), uValid("V?");
   ous << "{ " << vertexCnt << " ";
   ous << "Area: " << const_cast<rcPolygon *>(&p)->area () << " Perimeter: " << p.perimeter () << " Center Of Mass: " << cop << ", ";
   ous << (p._knownValid ? (p._isValid ? yValid.c_str() : nValid.c_str())
       : uValid.c_str());
   ous << (p._knownConvex ? (p._isConvex ? yConvex.c_str() : nConvex.c_str())
       : uConvex.c_str());
   ous << " |";
   for (int32 i = 0; i < vertexCnt; i++)
     ous << " " << i << " " << p.vertexAt(i);
   ous << " }";
   return ous;
 }
bool operator== (const rcPolygon & a, const rcPolygon & b) friend
Definition at line 1891 of file rc_polygon.cpp.
 {
   int32 count = a.vertexCnt();
   if (count != b.vertexCnt())
     return false;
   else if (count == 0)
     return true;
   int32 base = 0;
   for ( ; base < count; base++)
     if (a.vertexAt(0) == b.vertexAt(base))
       break;
   if (base == count)
     return false;
   for (int32 i = 0; i < count; i++)
     if (a.vertexAt(i) != b.vertexAt(base+i))
       return false;
   if (a._knownValid && b._knownValid)
     rmAssert(a.isValid() == b.isValid());
   if (a._knownConvex && b._knownConvex)
     rmAssert(a.isConvex() == b.isConvex());
   if (a._knownValid && !b._knownValid) {
     (const_cast<rcPolygon&>(b))._knownValid = a._knownValid;
     (const_cast<rcPolygon&>(b))._isValid = a._isValid;
   }
   if (!a._knownValid && b._knownValid) {
     (const_cast<rcPolygon&>(a))._knownValid = b._knownValid;
     (const_cast<rcPolygon&>(a))._isValid = b._isValid;
   }
   if (a._knownConvex && !b._knownConvex) {
     (const_cast<rcPolygon&>(b))._knownConvex = a._knownConvex;
     (const_cast<rcPolygon&>(b))._isConvex = a._isConvex;
   }
   if (!a._knownConvex && b._knownConvex) {
     (const_cast<rcPolygon&>(a))._knownConvex = b._knownConvex;
     (const_cast<rcPolygon&>(a))._isConvex = b._isConvex;
   }
   return true;
 }
Member Data Documentation
double rcPolygon::_area private
Definition at line 485 of file rc_polygon.h.
Referenced by area().
bool rcPolygon::_areaValid private
Definition at line 483 of file rc_polygon.h.
Referenced by area(), deleteVertex(), insertVertex(), popVertex(), pushUniqueVertex(), pushVertex(), transform(), and translate().
rc2Dvector rcPolygon::_com private
Definition at line 484 of file rc_polygon.h.
Referenced by centerOf().
bool rcPolygon::_comValid private
Definition at line 483 of file rc_polygon.h.
Referenced by centerOf(), deleteVertex(), insertVertex(), popVertex(), pushUniqueVertex(), pushVertex(), transform(), and translate().
bool rcPolygon::_isConvex private
Definition at line 483 of file rc_polygon.h.
Referenced by convexIntersection(), convexUnion(), createConvexHull(), deleteVertex(), insertVertex(), isConvex(), operator<<(), operator==(), popVertex(), pushUniqueVertex(), and pushVertex().
bool rcPolygon::_isValid private
Definition at line 483 of file rc_polygon.h.
Referenced by convexIntersection(), convexUnion(), createConvexHull(), deleteVertex(), insertVertex(), isValid(), operator<<(), operator==(), popVertex(), pushUniqueVertex(), and pushVertex().
bool rcPolygon::_knownConvex private
Definition at line 483 of file rc_polygon.h.
Referenced by convexIntersection(), createConvexHull(), deleteVertex(), insertVertex(), isConvex(), operator<<(), operator==(), popVertex(), pushUniqueVertex(), and pushVertex().
bool rcPolygon::_knownValid private
Definition at line 483 of file rc_polygon.h.
Referenced by convexIntersection(), convexUnion(), createConvexHull(), deleteVertex(), insertVertex(), isConvex(), isValid(), operator<<(), operator==(), popVertex(), pushUniqueVertex(), and pushVertex().
deque<rc2Dvector> rcPolygon::_vert private
Definition at line 482 of file rc_polygon.h.
Referenced by centerOf(), circularity(), contains(), convexIntersection(), convexUnion(), createConvexHull(), deleteVertex(), discBuffer(), ellipseRatio(), findPeak(), genMinEnclosingRect(), insertVertex(), intersects(), isConvex(), isValid(), orthogonalEnclosingRect(), perimeter(), polyArea2(), popVertex(), pushUniqueVertex(), pushVertex(), transform(), translate(), vertexAt(), vertexCnt(), vertices_begin(), and vertices_end().
The documentation for this class was generated from the following files:
include/visual/rc_polygon.h
src/visual/code/rc_polygon.cpp
src/visual/code/rc_polygongroup.cpp