Visible: rcChoiceRadioButton Class Reference
rcChoiceRadioButton Class Reference
#include <include/visUI/rc_choiceradiobutton.h>
Public Slots
void clickRelay (void)
Signals
void choiceSelected (int choiceValue)
Public Member Functions
rcChoiceRadioButton (QWidget *parent, const rcSettingChoice &choice)
int getChoiceValue (void)
Private Attributes
int _choiceValue
Detailed Description
Definition at line 10 of file rc_choiceradiobutton.h.
Constructor & Destructor Documentation
rcChoiceRadioButton::rcChoiceRadioButton (QWidget * parent, const rcSettingChoice & choice) inline
Definition at line 15 of file rc_choiceradiobutton.h.
References _choiceValue, clickRelay(), and rcSettingChoice::getValue().
         : QRadioButton( choice.getText() , parent )
     {
         _choiceValue = choice.getValue();
         connect( this , SIGNAL(clicked()) , this , SLOT(clickRelay()) );
     }
Member Function Documentation
void rcChoiceRadioButton::choiceSelected (int choiceValue) signal
Definition at line 78 of file moc_rc_choiceradiobutton.cpp.
Referenced by clickRelay().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
void rcChoiceRadioButton::clickRelay (void) inline slot
Definition at line 25 of file rc_choiceradiobutton.h.
References _choiceValue, and choiceSelected().
Referenced by rcChoiceRadioButton().
     {
         emit choiceSelected( _choiceValue );
     }
int rcChoiceRadioButton::getChoiceValue (void) inline
Definition at line 22 of file rc_choiceradiobutton.h.
References _choiceValue.
Referenced by rcRadioChoiceSettingWidget::settingChanged().
 { return _choiceValue; }
Member Data Documentation
int rcChoiceRadioButton::_choiceValue private
Definition at line 34 of file rc_choiceradiobutton.h.
Referenced by clickRelay(), getChoiceValue(), and rcChoiceRadioButton().
The documentation for this class was generated from the following files:
include/visUI/rc_choiceradiobutton.h
src/visible/moc/moc_rc_choiceradiobutton.cpp