Visible: rcTrackImpl Class Reference
rcTrackImpl Class Reference
#include <include/visiCore/rc_trackimpl.h>
Public Member Functions
rcTrackImpl (rcTrackType trackType, rcWriterType writerType, const char *tag, const char *name, const char *description, const char *displayFormat, uint32 limit, rcTimestamp firstTime=-1.0)
virtual ~rcTrackImpl ()
virtual rcTrackType getTrackType (void)
virtual rcWriterType getWriterType (void)
virtual const char * getTag (void)
virtual const char * getName (void)
virtual const char * getDescription (void)
virtual uint32 getSizeLimit () const
virtual const char * getDisplayFormatString (void)
virtual rcTimestamp getTrackStart (void)
virtual void setTrackStart (const rcTimestamp &time)
virtual void setExportable (bool e)
virtual void setDescription (const char *text)
virtual void setName (const char *text)
virtual void flush (void)
virtual bool isExportable (void)
virtual rcTrackSemantics getSemantics (void)
virtual void setSemantics (const rcTrackSemantics &s)
virtual rcRect getAnalysisRect (void)
virtual void setAnalysisRect (const rcRect &f)
virtual uint32 segments (void)
virtual rcSegmentImpl segment (uint32 index)
virtual void popSegment ()
Public Member Functions inherited from rcTrack
virtual ~rcTrack ()
Public Member Functions inherited from rcWriter
virtual ~rcWriter ()
Protected Member Functions
rcTimestamp lastSegmentLength ()
rcTimestamp nextSegmentLength (const rcTimestamp &timestamp)
rcTimestamp nextSegmentStart ()
virtual void setWriterState (const rcTimestamp &time, rcRect focus)
void updateFirstTime (const rcTimestamp &timestamp)
Protected Attributes
rcMutex _mutex
rcTimestamp _currentLength
rcRect _currentFocus
uint32 _sizeLimit
rcTimestamp _firstTime
rcTimestamp _expStartTime
bool _isExportable
rcTrackSemantics _dataSemantics
rcRect _analysisFocus
Private Attributes
rcTrackType _trackType
rcWriterType _writerType
std::string _tag
std::string _name
std::string _description
std::string _displayFormat
Additional Inherited Members
Static Public Member Functions inherited from rcTrack
static rcTrackType type (const std::string &name)
static const std::string & name (rcTrackType type)
Detailed Description
Definition at line 21 of file rc_trackimpl.h.
Constructor & Destructor Documentation
rcTrackImpl::rcTrackImpl (rcTrackType trackType, rcWriterType writerType, const char * tag, const char * name, const char * description, const char * displayFormat, uint32 limit, rcTimestamp firstTime = -1.0) inline
Definition at line 25 of file rc_trackimpl.h.
References cZeroTime, and eTrackSemanticsUnknown.
     {
         _dataSemantics = eTrackSemanticsUnknown;
         _trackType = trackType;
         _writerType = writerType;
         _tag = tag;
         _name = name;
         _description = description;
         if ( !displayFormat )
             _displayFormat = "%-8.4f";
         else
             _displayFormat = displayFormat;
         _sizeLimit = limit;
         _currentLength = cZeroTime;
         _firstTime = firstTime;
         if ( _firstTime >= cZeroTime )
             _currentLength = _firstTime;
         else
             _currentLength = cZeroTime;
         // Exportability has to be explicitly allowed by each derived class
         _isExportable = false;
     }
virtual rcTrackImpl::~rcTrackImpl () inline virtual
Definition at line 53 of file rc_trackimpl.h.
 { };
Member Function Documentation
virtual void rcTrackImpl::flush (void) inline virtual
Implements rcWriter.
Reimplemented in rcPositionTrackImpl, rcScalarTrackImpl, rcGraphicsTrackImpl, and rcVideoTrackImpl.
Definition at line 131 of file rc_trackimpl.h.
References rmAssert.
     {
         rmAssert( 0 ); // Derived classes must implement this
     }
virtual rcRect rcTrackImpl::getAnalysisRect (void) inline virtual
Implements rcTrack.
Definition at line 155 of file rc_trackimpl.h.
     {
         return _analysisFocus;
     }
virtual const char* rcTrackImpl::getDescription (void) inline virtual
Implements rcWriter.
Definition at line 82 of file rc_trackimpl.h.
     {
         return _description.c_str();
     }
virtual const char* rcTrackImpl::getDisplayFormatString (void) inline virtual
Implements rcTrack.
Definition at line 94 of file rc_trackimpl.h.
     {
         return _displayFormat.c_str();
     }
virtual const char* rcTrackImpl::getName (void) inline virtual
Implements rcWriter.
Definition at line 76 of file rc_trackimpl.h.
     {
         return _name.c_str();
     }
virtual rcTrackSemantics rcTrackImpl::getSemantics (void) inline virtual
Implements rcTrack.
Definition at line 143 of file rc_trackimpl.h.
     {
         return _dataSemantics;
     }
virtual uint32 rcTrackImpl::getSizeLimit () const inline virtual
Implements rcTrack.
Definition at line 88 of file rc_trackimpl.h.
     {
         return _sizeLimit;
     }
virtual const char* rcTrackImpl::getTag (void) inline virtual
Implements rcWriter.
Definition at line 70 of file rc_trackimpl.h.
     {
         return _tag.c_str();
     }
virtual rcTimestamp rcTrackImpl::getTrackStart (void) inline virtual
Implements rcWriter.
Definition at line 100 of file rc_trackimpl.h.
Referenced by rcSegmentIteratorImpl::rcSegmentIteratorImpl(), and rcSegmentIteratorImpl::reset().
     {
         return _firstTime;
     }
virtual rcTrackType rcTrackImpl::getTrackType (void) inline virtual
Implements rcTrack.
Definition at line 58 of file rc_trackimpl.h.
     {
         return _trackType;
     }
virtual rcWriterType rcTrackImpl::getWriterType (void) inline virtual
Implements rcWriter.
Definition at line 64 of file rc_trackimpl.h.
     {
         return _writerType;
     }
virtual bool rcTrackImpl::isExportable (void) inline virtual
Implements rcTrack.
Definition at line 137 of file rc_trackimpl.h.
     {
         return _isExportable;
     }
rcTimestamp rcTrackImpl::lastSegmentLength () inline protected
Definition at line 195 of file rc_trackimpl.h.
References cZeroTime, rcSegmentImpl::length(), and segment().
Referenced by rcVideoTrackImpl::flush(), rcGraphicsTrackImpl::flush(), rcScalarTrackImpl::flush(), and rcPositionTrackImpl::flush().
     {
         int segCount = segments();
         if ( segCount > 0 ) {
             rcSegmentImpl lastSegment = segment( segCount -1 );
             return lastSegment.length();
         } else
             return cZeroTime;
     }
rcTimestamp rcTrackImpl::nextSegmentLength (const rcTimestamp & timestamp) inline protected
Definition at line 207 of file rc_trackimpl.h.
References cZeroTime.
Referenced by rcVideoTrackImpl::writeValue(), rcGraphicsTrackImpl::writeValue(), rcScalarTrackImpl::writeValue(), and rcPositionTrackImpl::writeValue().
     {
         if ( timestamp <= _firstTime )
             return cZeroTime;
         return timestamp - _currentLength;
     }
rcTimestamp rcTrackImpl::nextSegmentStart () inline protected
Definition at line 216 of file rc_trackimpl.h.
References cZeroTime, and endl().
Referenced by rcVideoTrackImpl::addSegment(), rcGraphicsTrackImpl::addSegment(), rcPositionTrackImpl::addSegment(), and rcScalarTrackImpl::addSegment().
     {
         rcTimestamp startTime =  _currentLength - _firstTime;
         if ( startTime < cZeroTime ) {
             cerr << endl;
             cerr << "nextSegmentStart error for track \"" << _name << "\": negative first segment timestamp ";
             cerr << startTime << ", first segment time "  << _firstTime << endl << endl;
             startTime = cZeroTime;
             // TODO: make this assert when code has been debugged better
         }
         return startTime;
     }
virtual void rcTrackImpl::popSegment () inline virtual
Reimplemented in rcPositionTrackImpl, rcGraphicsTrackImpl, rcScalarTrackImpl, and rcVideoTrackImpl.
Definition at line 187 of file rc_trackimpl.h.
References rmAssert.
     {
         rmAssert( 0 );
         // Derived classed MUST implement this
     }
virtual rcSegmentImpl rcTrackImpl::segment (uint32 index) inline virtual
Reimplemented in rcPositionTrackImpl, rcGraphicsTrackImpl, rcScalarTrackImpl, and rcVideoTrackImpl.
Definition at line 177 of file rc_trackimpl.h.
References cZeroTime, rmAssert, and rmUnused.
Referenced by rcSegmentIteratorImpl::advanceNoLock(), and rcSegmentIteratorImpl::findClosestSegment().
     {
         rmUnused( index );
         rmAssert( 0 );
         // Derived classed MUST implement this
         return rcSegmentImpl( cZeroTime, cZeroTime, rcRect( 0, 0, 0, 0) );
     }
virtual uint32 rcTrackImpl::segments (void) inline virtual
Reimplemented in rcPositionTrackImpl, rcGraphicsTrackImpl, rcScalarTrackImpl, and rcVideoTrackImpl.
Definition at line 169 of file rc_trackimpl.h.
References rmAssert.
Referenced by rcSegmentIteratorImpl::advanceNoLock(), rcSegmentIteratorImpl::findClosestSegment(), rcSegmentIteratorImpl::getSegmentCount(), and rcSegmentIteratorImpl::hasNextSegment().
     {
         // Derived classed MUST implement this
         rmAssert( 0 );
         return 0;
     }
virtual void rcTrackImpl::setAnalysisRect (const rcRect & f) inline virtual
Implements rcWriter.
Definition at line 161 of file rc_trackimpl.h.
Referenced by rcTrackGroupImpl::createWriter().
     {
         _analysisFocus = f;
     }
virtual void rcTrackImpl::setDescription (const char * text) inline virtual
Implements rcWriter.
Definition at line 121 of file rc_trackimpl.h.
{
         _description = text;
     }
virtual void rcTrackImpl::setExportable (bool e) inline virtual
Implements rcWriter.
Definition at line 115 of file rc_trackimpl.h.
     {
         _isExportable = e;
     }
virtual void rcTrackImpl::setName (const char * text) inline virtual
Implements rcWriter.
Definition at line 126 of file rc_trackimpl.h.
{
         _name = text;
     }
virtual void rcTrackImpl::setSemantics (const rcTrackSemantics & s) inline virtual
Implements rcWriter.
Definition at line 149 of file rc_trackimpl.h.
     {
          _dataSemantics = s;
     }
virtual void rcTrackImpl::setTrackStart (const rcTimestamp & time) inline virtual
Implements rcWriter.
Definition at line 106 of file rc_trackimpl.h.
References rmAssert.
     {
         // We can only set track start once at the beginning
         rmAssert( _firstTime == -1.0 );
          _firstTime = time;
          _currentLength = _firstTime;
     }
virtual void rcTrackImpl::setWriterState (const rcTimestamp & time, rcRect focus) inline protected virtual
Definition at line 230 of file rc_trackimpl.h.
References cZeroTime, and rmAssert.
Referenced by rcVideoTrackImpl::setWriterState(), rcGraphicsTrackImpl::setWriterState(), rcPositionTrackImpl::setWriterState(), and rcScalarTrackImpl::setWriterState().
     {
         rmAssert( time >= cZeroTime );
         // Set current state
         _currentLength = time;
         _currentFocus = focus;
         // Prune old values if necessary
         if ( segments() > _sizeLimit )
             popSegment();
     };
void rcTrackImpl::updateFirstTime (const rcTimestamp & timestamp) inline protected
Definition at line 243 of file rc_trackimpl.h.
References cZeroTime.
Referenced by rcVideoTrackImpl::writeValue(), rcGraphicsTrackImpl::writeValue(), rcScalarTrackImpl::writeValue(), and rcPositionTrackImpl::writeValue().
     {
         if ( _firstTime < cZeroTime ) {
             _firstTime = timestamp;
             _currentLength = _firstTime;
         }
     };
Member Data Documentation
rcRect rcTrackImpl::_analysisFocus protected
Definition at line 259 of file rc_trackimpl.h.
rcRect rcTrackImpl::_currentFocus protected
Definition at line 253 of file rc_trackimpl.h.
Referenced by rcVideoTrackImpl::addSegment(), rcGraphicsTrackImpl::addSegment(), rcPositionTrackImpl::addSegment(), rcScalarTrackImpl::addSegment(), rcVideoTrackImpl::flush(), rcGraphicsTrackImpl::flush(), rcScalarTrackImpl::flush(), and rcPositionTrackImpl::flush().
rcTimestamp rcTrackImpl::_currentLength protected
Definition at line 252 of file rc_trackimpl.h.
Referenced by rcVideoTrackImpl::flush(), rcGraphicsTrackImpl::flush(), rcScalarTrackImpl::flush(), rcPositionTrackImpl::flush(), and rcScalarTrackImpl::reset().
rcTrackSemantics rcTrackImpl::_dataSemantics protected
Definition at line 258 of file rc_trackimpl.h.
std::string rcTrackImpl::_description private
Definition at line 267 of file rc_trackimpl.h.
std::string rcTrackImpl::_displayFormat private
Definition at line 268 of file rc_trackimpl.h.
rcTimestamp rcTrackImpl::_expStartTime protected
Definition at line 256 of file rc_trackimpl.h.
rcTimestamp rcTrackImpl::_firstTime protected
Definition at line 255 of file rc_trackimpl.h.
Referenced by rcScalarTrackImpl::reset().
bool rcTrackImpl::_isExportable protected
Definition at line 257 of file rc_trackimpl.h.
Referenced by rcGraphicsTrackImpl::rcGraphicsTrackImpl(), rcPositionTrackImpl::rcPositionTrackImpl(), rcScalarTrackImpl::rcScalarTrackImpl(), and rcVideoTrackImpl::rcVideoTrackImpl().
rcMutex rcTrackImpl::_mutex protected
Definition at line 249 of file rc_trackimpl.h.
Referenced by rcVideoTrackImpl::flush(), rcGraphicsTrackImpl::flush(), rcScalarTrackImpl::flush(), rcPositionTrackImpl::flush(), rcScalarTrackImpl::getCurrentMaximumValue(), rcPositionTrackImpl::getCurrentMaximumValue(), rcScalarTrackImpl::getCurrentMinimumValue(), rcPositionTrackImpl::getCurrentMinimumValue(), rcVideoTrackImpl::getDataSegmentIterator(), rcGraphicsTrackImpl::getDataSegmentIterator(), rcScalarTrackImpl::getDataSegmentIterator(), rcPositionTrackImpl::getDataSegmentIterator(), rcScalarTrackImpl::getExpectedMaximumValue(), rcPositionTrackImpl::getExpectedMaximumValue(), rcScalarTrackImpl::getExpectedMinimumValue(), rcPositionTrackImpl::getExpectedMinimumValue(), rcVideoTrackImpl::getSegmentCount(), rcGraphicsTrackImpl::getSegmentCount(), rcScalarTrackImpl::getSegmentCount(), rcPositionTrackImpl::getSegmentCount(), rcScalarTrackImpl::reset(), rcVideoTrackImpl::writeValue(), rcGraphicsTrackImpl::writeValue(), rcScalarTrackImpl::writeValue(), and rcPositionTrackImpl::writeValue().
std::string rcTrackImpl::_name private
Definition at line 266 of file rc_trackimpl.h.
uint32 rcTrackImpl::_sizeLimit protected
Definition at line 254 of file rc_trackimpl.h.
std::string rcTrackImpl::_tag private
Definition at line 265 of file rc_trackimpl.h.
rcTrackType rcTrackImpl::_trackType private
Definition at line 263 of file rc_trackimpl.h.
rcWriterType rcTrackImpl::_writerType private
Definition at line 264 of file rc_trackimpl.h.
The documentation for this class was generated from the following file:
include/visiCore/rc_trackimpl.h