Visible: rcWriterInfo Class Reference
rcWriterInfo Class Reference
#include <include/visiCore/rc_writermanagerimpl.h>
Public Member Functions
rcWriterInfo (rcWriterSemantics type, rcWriterType trackType, const std::string &tagName, const std::string &displayName, const std::string &description, const std::string &formatString)
rcWriterSemantics type () const
rcWriterType trackType () const
const std::string & tag () const
const std::string & name () const
const std::string & description () const
const std::string & format () const
Private Attributes
rcWriterSemantics mType
rcWriterType mTrackType
std::string mTagName
std::string mDisplayName
std::string mDescription
std::string mFormatString
Detailed Description
Definition at line 14 of file rc_writermanagerimpl.h.
Constructor & Destructor Documentation
rcWriterInfo::rcWriterInfo (rcWriterSemantics type, rcWriterType trackType, const std::string & tagName, const std::string & displayName, const std::string & description, const std::string & formatString) inline
Definition at line 17 of file rc_writermanagerimpl.h.
                                                   :
         mType( type ), mTrackType( trackType ), mTagName( tagName ), mDisplayName( displayName ),
mDescription(description),mFormatString(formatString) { }
Member Function Documentation
const std::string& rcWriterInfo::description () const inline
Definition at line 31 of file rc_writermanagerimpl.h.
References mDescription.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), and rcWriterManager::createWriter().
 { return mDescription; }
const std::string& rcWriterInfo::format (void) const inline
Definition at line 32 of file rc_writermanagerimpl.h.
References mFormatString.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), and rcWriterManager::createWriter().
 { return mFormatString; }
const std::string& rcWriterInfo::name (void) const inline
Definition at line 30 of file rc_writermanagerimpl.h.
References mDisplayName.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), rcWriterManager::createWriter(), and rcWriterManager::writerName().
 { return mDisplayName; }
const std::string& rcWriterInfo::tag () const inline
Definition at line 29 of file rc_writermanagerimpl.h.
References mTagName.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), rcWriterManager::createWriter(), and rcWriterManager::writerTag().
 { return mTagName; }
rcWriterType rcWriterInfo::trackType () const inline
Definition at line 28 of file rc_writermanagerimpl.h.
References mTrackType.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), and rcWriterManager::createWriter().
 { return mTrackType; }
rcWriterSemantics rcWriterInfo::type (void) const inline
Definition at line 27 of file rc_writermanagerimpl.h.
References mType.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), and rcWriterManager::createWriter().
 { return mType; }
Member Data Documentation
std::string rcWriterInfo::mDescription private
Definition at line 39 of file rc_writermanagerimpl.h.
Referenced by description().
std::string rcWriterInfo::mDisplayName private
Definition at line 38 of file rc_writermanagerimpl.h.
Referenced by name().
std::string rcWriterInfo::mFormatString private
Definition at line 40 of file rc_writermanagerimpl.h.
Referenced by format().
std::string rcWriterInfo::mTagName private
Definition at line 37 of file rc_writermanagerimpl.h.
Referenced by tag().
rcWriterType rcWriterInfo::mTrackType private
Definition at line 36 of file rc_writermanagerimpl.h.
Referenced by trackType().
rcWriterSemantics rcWriterInfo::mType private
Definition at line 35 of file rc_writermanagerimpl.h.
Referenced by type().
The documentation for this class was generated from the following file:
include/visiCore/rc_writermanagerimpl.h