Visible: rcModelProgress Class Reference
rcModelProgress Class Reference
#include <include/visUI/rc_modeldomain.h>
Public Member Functions
rcModelProgress (rcModelDomain *domain, const std::string &message, double updateInterval, QApplication *app, bool updateDisplay=false)
virtual ~rcModelProgress ()
virtual bool progress (uint32 percentComplete)
virtual bool progress (double percentComplete)
Public Member Functions inherited from rcProgressIndicator
virtual ~rcProgressIndicator ()
Private Attributes
rcModelDomain * mDomain
const std::string mFormatMessage
char mMessageBuf [1024]
double mLastPercentage
QApplication * mApp
double mUpdateInterval
rcTimestamp mLastUpdate
bool mUpdateDisplay
Detailed Description
Definition at line 261 of file rc_modeldomain.h.
Constructor & Destructor Documentation
rcModelProgress::rcModelProgress (rcModelDomain * domain, const std::string & message, double updateInterval, QApplication * app, bool updateDisplay = false) inline
Definition at line 264 of file rc_modeldomain.h.
                                                                                     :
     mDomain( domain), mFormatMessage( message ), mLastPercentage( -1.0 ),
     mApp( app ), mUpdateInterval( updateInterval), mLastUpdate( cZeroTime ),
mUpdateDisplay(updateDisplay) {};
virtual rcModelProgress::~rcModelProgress () inline virtual
Definition at line 270 of file rc_modeldomain.h.
 {};
Member Function Documentation
virtual bool rcModelProgress::progress (uint32 percentComplete) inline virtual
Implements rcProgressIndicator.
Definition at line 277 of file rc_modeldomain.h.
Referenced by rcModelDomain::requestOpen().
{
         return progress( static_cast<double>(percentComplete) );
     }
virtual bool rcModelProgress::progress (double percentComplete) inline virtual
Implements rcProgressIndicator.
Definition at line 282 of file rc_modeldomain.h.
References rcModelDomain::getExperimentLength(), mApp, mDomain, mFormatMessage, mLastPercentage, mLastUpdate, mMessageBuf, mUpdateDisplay, mUpdateInterval, rcModelDomain::notifyStatus(), rcModelDomain::notifyTime(), rcTimestamp::now(), rmDim, and rcTimestamp::secs().
{
         if ( percentComplete != mLastPercentage )
         {
             rcTimestamp now = rcTimestamp::now();
             rcTimestamp timeSinceLastUpdate = now - mLastUpdate;
             // Update only if specified interval has passed
             if ( timeSinceLastUpdate.secs() > mUpdateInterval )
             {
                 snprintf( mMessageBuf, rmDim( mMessageBuf ), mFormatMessage.c_str(), percentComplete );
                 mDomain->notifyStatus( mMessageBuf );
                 mLastPercentage = percentComplete;
                 if ( mUpdateDisplay ) {
                     mDomain->notifyTime( mDomain->getExperimentLength() );
                     mApp->processEvents(QEventLoop::ExcludeUserInputEvents, 5 ); // Allow 5 ms for event processing
                 } else {
                     mApp->processEvents( QEventLoop::ExcludeUserInputEvents, 1 ); // Allow 1 ms for event processing
                 }
                 mLastUpdate = now;
                 // TODO: add abort logic for shutting down
             }
         }
         return false;
     }
Member Data Documentation
QApplication* rcModelProgress::mApp private
Definition at line 312 of file rc_modeldomain.h.
Referenced by progress().
rcModelDomain* rcModelProgress::mDomain private
Definition at line 308 of file rc_modeldomain.h.
Referenced by progress().
const std::string rcModelProgress::mFormatMessage private
Definition at line 309 of file rc_modeldomain.h.
Referenced by progress().
double rcModelProgress::mLastPercentage private
Definition at line 311 of file rc_modeldomain.h.
Referenced by progress().
rcTimestamp rcModelProgress::mLastUpdate private
Definition at line 314 of file rc_modeldomain.h.
Referenced by progress().
char rcModelProgress::mMessageBuf[1024] private
Definition at line 310 of file rc_modeldomain.h.
Referenced by progress().
bool rcModelProgress::mUpdateDisplay private
Definition at line 315 of file rc_modeldomain.h.
Referenced by progress().
double rcModelProgress::mUpdateInterval private
Definition at line 313 of file rc_modeldomain.h.
Referenced by progress().
The documentation for this class was generated from the following file:
include/visUI/rc_modeldomain.h