Visible: rcCellWriterGroup Class Reference
rcCellWriterGroup Class Reference
#include <include/visiCore/rc_engineimplbase.h>
Public Member Functions
rcCellWriterGroup ()
rcCellWriterGroup (rcWriterManager *manager, const rcVisualFunction &bfun, const rcRect &imageRect, const rcRect &analysisRect, const rcTimestamp &trackStart, const char *label)
rcCellWriterGroup (rcWriterManager *manager, const rcVisualTarget &bfun, const rcRect &imageRect, const rcRect &analysisRect, const rcTimestamp &trackStart, const char *label)
~rcCellWriterGroup ()
uint32 size () const
rcWriter * getWriter (rcWriterSemantics type) const
void writeValues (const rcTimestamp &timestamp, const rcRect &focus, const rcVisualFunction &result)
void writeValues (const rcTimestamp &timestamp, const rcRect &focus, const rcVisualTarget &result)
void flush ()
Private Attributes
rcWriterGroup * mCellGroup
rcCellKey mKey
map< rcWriterSemantics,
rcWriter * > mWriters
Detailed Description
Definition at line 131 of file rc_engineimplbase.h.
Constructor & Destructor Documentation
rcCellWriterGroup::rcCellWriterGroup ()
Definition at line 17 of file rc_engineimplcells.cpp.
                                      :
         mCellGroup( 0 ), mKey( 0 )
 {
}
rcCellWriterGroup::rcCellWriterGroup (rcWriterManager * manager, const rcVisualFunction & bfun, const rcRect & imageRect, const rcRect & analysisRect, const rcTimestamp & trackStart, const char * label)
Definition at line 24 of file rc_engineimplcells.cpp.
References rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createWriterGroup(), rcScalarWriter::down_cast(), rcPositionWriter::down_cast(), eGroupSemanticsBodyMeasurements, eWriterBodyCircularity, eWriterBodyDistance, eWriterBodyEllipseRatio, eWriterBodyMajor, eWriterBodyPersistence, eWriterBodyPosition, eWriterBodyQuality, eWriterBodyScaleX, eWriterBodyScaleY, eWriterBodySpeedDirection, eWriterBodyState, eWriterCardiacShortening, eWriterContractionFreq, rcRectangle< T >::height(), rcVisualFunction::isCardiacCell(), mCellGroup, mWriters, rcWriter::setExportable(), rcWriter::setTrackStart(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
                                                          :
   mKey( bfun.id())
 {
   double maxDist = sqrt(double(imageRect.width()) * imageRect.width() + imageRect.height() * imageRect.height());
   uint32 maxSpeed = (uint32) log2 (maxDist);
     // Create cell group
     mCellGroup = manager->createWriterGroup( label,
                                              label,
                                              eGroupSemanticsBodyMeasurements );
     // Create writers Based on Biological Function Type
     if (bfun.isCardiacCell ())
       {
     // Cell center position writer
     rcPositionWriter* pWriter = manager->createPositionWriter( mCellGroup,
                                    eWriterBodyPosition,
                                    INT_MAX,
                                    analysisRect,
                                    rcFPair( imageRect.x(), imageRect.y() ) ,
                                    rcFPair( imageRect.width(), imageRect.height() ) );
     rcWriter* writer = pWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyPosition, writer) );
     // Cell Major axis scale writer, value is [10, 200]
     rcScalarWriter * sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyMajor,
                            INT_MAX,
                            analysisRect,
                            10.0,
                            200.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyMajor, writer) );
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterCardiacShortening,
                            INT_MAX,
                            analysisRect,
                            0.01,
                            1.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterCardiacShortening, writer) );
     // Cell contratcion frequency writer (is being used for shortening) , value is [0.1 to 10]
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterContractionFreq,
                            INT_MAX,
                            analysisRect,
                            0.01,
                            10.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterContractionFreq, writer) );
       }
     else
       {
     // Cell center position writer
     rcPositionWriter* pWriter = manager->createPositionWriter( mCellGroup,
                                    eWriterBodyPosition,
                                    INT_MAX,
                                    analysisRect,
                                    rcFPair( imageRect.x(), imageRect.y() ) ,
                                    rcFPair( imageRect.width(), imageRect.height() ) );
     rcWriter* writer = pWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyPosition, writer) );
     // Cell speed+direction writer
     pWriter = manager->createPositionWriter( mCellGroup,
                          eWriterBodySpeedDirection,
                          INT_MAX,
                          analysisRect,
                          rcFPair( 0.0, 0.0 ),
                          rcFPair( maxSpeed, 360.0 ) );
     writer = pWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodySpeedDirection, writer) );
     // Cell quality writer
     rcScalarWriter * sWriter = manager->createScalarWriter( mCellGroup,
                                 eWriterBodyQuality,
                                 INT_MAX,
                                 analysisRect,
                                 0.0,
                                 1.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     writer->setExportable( true );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyQuality, writer) );
     // Cell travel distance writer
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyDistance,
                            INT_MAX,
                            analysisRect,
                            0.0,
                            maxDist );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyDistance, writer) );
     // Cell persistence writer, value is [-1-1]
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyPersistence,
                            INT_MAX,
                            analysisRect,
                            -1.0,
                            1.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyPersistence, writer) );
     // Cell X axis scale writer, value is [0.1-10]
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyScaleX,
                            INT_MAX,
                            analysisRect,
                            50.0,
                            200.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyScaleX, writer) );
     // Cell Y axis scale writer, value is [0.1-10]
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyScaleY,
                            INT_MAX,
                            analysisRect,
                            50.0,
                            200.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyScaleY, writer) );
     // Cell Circularity writer, value is [0.1-10]
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyCircularity,
                            INT_MAX,
                            analysisRect,
                            0.0,
                            1.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyCircularity, writer) );
     // Cell EllipseRatio writer, value is [0.1-10]
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyEllipseRatio,
                            INT_MAX,
                            analysisRect,
                            0.1,
                            10.0);
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyEllipseRatio, writer) );
     // Cell state writer, value is an enum
     // @todo real min / max
     sWriter = manager->createScalarWriter( mCellGroup,
                            eWriterBodyState,
                            INT_MAX,
                            analysisRect,
                            0.0,
                            20.0 );
     writer = sWriter->down_cast();
     writer->setTrackStart( trackStart );
     // Enable export when state values have been implemented
     writer->setExportable(true);
     mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyState, writer) );
       }
}
rcCellWriterGroup::rcCellWriterGroup (rcWriterManager * manager, const rcVisualTarget & bfun, const rcRect & imageRect, const rcRect & analysisRect, const rcTimestamp & trackStart, const char * label)
Definition at line 448 of file rc_engineimplcells.cpp.
References rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createWriterGroup(), rcScalarWriter::down_cast(), rcPositionWriter::down_cast(), eGroupSemanticsBodyMeasurements, eWriterBodyDistance, eWriterBodyPersistence, eWriterBodyPosition, eWriterBodyQuality, eWriterBodySpeedDirection, rcRectangle< T >::height(), mCellGroup, mWriters, rcWriter::setExportable(), rcWriter::setTrackStart(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
                                                                                             : mKey( bfun.id())
 {
   double maxDist = sqrt(double(imageRect.width()) * imageRect.width() + imageRect.height() * imageRect.height());
   uint32 maxSpeed = (uint32) log2 (maxDist);
     // Create cell group
     mCellGroup = manager->createWriterGroup( label,
                                                                                     label,
                                                                                     eGroupSemanticsBodyMeasurements );
             // Cell center position writer
             rcPositionWriter* pWriter = manager->createPositionWriter( mCellGroup,
                                                                                                                                 eWriterBodyPosition,
                                                                                                                                 INT_MAX,
                                                                                                                                 analysisRect,
                                                                                                                                 rcFPair( imageRect.x(), imageRect.y() ) ,
                                                                                                                                 rcFPair( imageRect.width(), imageRect.height() ) );
             rcWriter* writer = pWriter->down_cast();
             writer->setTrackStart( trackStart );
             mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyPosition, writer) );
             // Cell speed+direction writer
             pWriter = manager->createPositionWriter( mCellGroup,
                                                                                             eWriterBodySpeedDirection,
                                                                                             INT_MAX,
                                                                                             analysisRect,
                                                                                             rcFPair( 0.0, 0.0 ),
                                                                                             rcFPair( maxSpeed, 360.0 ) );
             writer = pWriter->down_cast();
             writer->setTrackStart( trackStart );
             mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodySpeedDirection, writer) );
             // Cell quality writer
             rcScalarWriter * sWriter = manager->createScalarWriter( mCellGroup,
                                                                                                                          eWriterBodyQuality,
                                                                                                                          INT_MAX,
                                                                                                                          analysisRect,
                                                                                                                          0.0,
                                                                                                                          1.0 );
             writer = sWriter->down_cast();
             writer->setTrackStart( trackStart );
             writer->setExportable( true );
             mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyQuality, writer) );
             // Cell travel distance writer
             sWriter = manager->createScalarWriter( mCellGroup,
                                                                                         eWriterBodyDistance,
                                                                                         INT_MAX,
                                                                                         analysisRect,
                                                                                         0.0,
                                                                                         maxDist );
             writer = sWriter->down_cast();
             writer->setTrackStart( trackStart );
             mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyDistance, writer) );
             // Cell persistence writer, value is [-1-1]
             sWriter = manager->createScalarWriter( mCellGroup,
                                                                                         eWriterBodyPersistence,
                                                                                         INT_MAX,
                                                                                         analysisRect,
                                                                                         -1.0,
                                                                                         1.0 );
             writer = sWriter->down_cast();
             writer->setTrackStart( trackStart );
             mWriters.insert( pair<rcWriterSemantics, rcWriter*>(eWriterBodyPersistence, writer) );
     }
rcCellWriterGroup::~rcCellWriterGroup ()
Definition at line 208 of file rc_engineimplcells.cpp.
 {
     // No need to delete writers, observer does it
 }
Member Function Documentation
void rcCellWriterGroup::flush (void)
Definition at line 378 of file rc_engineimplcells.cpp.
References mWriters.
 {
     map<rcWriterSemantics, rcWriter*>::iterator w;
     for ( w = mWriters.begin(); w != mWriters.end(); ++w )
         w->second->flush();
 }
rcWriter * rcCellWriterGroup::getWriter (rcWriterSemantics type) const
Definition at line 218 of file rc_engineimplcells.cpp.
References mWriters.
Referenced by writeValues().
 {
     map<rcWriterSemantics, rcWriter*>::const_iterator w = mWriters.find( type );
     if ( w != mWriters.end() )
         return w->second;
     else
         return 0;
 }
uint32 rcCellWriterGroup::size (void) const
Definition at line 213 of file rc_engineimplcells.cpp.
References mWriters.
 {
     return mWriters.size();
 }
void rcCellWriterGroup::writeValues (const rcTimestamp & timestamp, const rcRect & focus, const rcVisualFunction & result)
Definition at line 231 of file rc_engineimplcells.cpp.
References rcVisualFunction::circularity(), rcVisualFunction::contractionFrequency(), rcVisualFunction::dimensions(), rcVisualFunction::distance(), rcDegree::Double(), rcVisualFunction::ellipseRatio(), eWriterBodyCircularity, eWriterBodyDistance, eWriterBodyEllipseRatio, eWriterBodyMajor, eWriterBodyPersistence, eWriterBodyPosition, eWriterBodyQuality, eWriterBodyScaleX, eWriterBodyScaleY, eWriterBodySpeedDirection, eWriterBodyState, eWriterBodyVelocity, eWriterCardiacShortening, eWriterContractionFreq, getWriter(), rcDegree::norm(), rcVisualFunction::persistence(), rcVisualFunction::position(), rcVisualFunction::rmsQuality(), rcVisualFunction::scale(), rcVisualFunction::shortenning(), rcVisualFunction::state(), rcVisualFunction::velocity(), rcScalarWriter::writeValue(), rcPositionWriter::writeValue(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
 #ifdef NOIMP
     // Write position value
   rcFPair pos (result.position().x(), result.position().y());
     rcWriter* writer = getWriter( eWriterBodyPosition );
     if ( writer ) {
         rcPositionWriter* pWriter = dynamic_cast<rcPositionWriter*>( writer );
         pWriter->writeValue( timestamp, focus, pos);
     }
     // Write velocity value
     rcFPair vel (result.velocity().x(), result.velocity().y());
     writer = getWriter( eWriterBodyVelocity );
     if ( writer ) {
         rcPositionWriter* pWriter = dynamic_cast<rcPositionWriter*>( writer );
         pWriter->writeValue( timestamp, focus, vel);
     }
     // Write speed+direction value
     writer = getWriter( eWriterBodySpeedDirection );
     if ( writer ) {
         rcPositionWriter* pWriter = dynamic_cast<rcPositionWriter*>( writer );
         const rc2Fvector v( result.velocity().x(), result.velocity().y() );
         // Transform velocity vector to speed+angle
         if ( !v.isNull() ) {
             rcDegree degAngle(rcRadian( v.angle() ));
             const float angle = degAngle.norm().Double();
             pWriter->writeValue( timestamp, focus, rcFPair(v.len(), angle) );
         } else {
             pWriter->writeValue( timestamp, focus, rcFPair(v.x(), v.y()) );
         }
     }
     // Write quality measure
     writer = getWriter( eWriterBodyQuality );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         double v = result.rmsQuality();
         sWriter->writeValue( timestamp, focus, v );
     }
     // Write distance traveled
     writer = getWriter( eWriterBodyDistance );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         double v = result.distance();
         sWriter->writeValue( timestamp, focus, v );
     }
     // Write persistence
     writer = getWriter( eWriterBodyPersistence );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         double v = result.persistence();
         sWriter->writeValue( timestamp, focus, v );
     }
     // Write state
     writer = getWriter( eWriterBodyState );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         // Enum to double
         double v = static_cast<double>(result.state());
         sWriter->writeValue( timestamp, focus, v );
     }
     // Write scale X
     const rcFPair& scale = result.scale();
     if ( scale.x() > 0.0 ) {
         writer = getWriter( eWriterBodyScaleX );
         if ( writer ) {
             rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
             // Enum to double
             double v = static_cast<double>(scale.x());
             sWriter->writeValue( timestamp, focus, v );
         }
     }
     // Write scale Y
     if ( scale.y() > 0.0 ) {
         writer = getWriter( eWriterBodyScaleY );
         if ( writer ) {
             rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
             // Enum to double
             double v = static_cast<double>(scale.y());
             sWriter->writeValue( timestamp, focus, v );
         }
     }
     // Write Circularity
     if ( result.circularity() > 0.0 ) {
         writer = getWriter( eWriterBodyCircularity);
         if ( writer ) {
             rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
             // Enum to double
             double v = static_cast<double>(result.circularity ());
             sWriter->writeValue( timestamp, focus, v );
         }
     }
     // Write ellipseRatio
     if ( result.ellipseRatio() > 0.0 ) {
         writer = getWriter( eWriterBodyEllipseRatio);
         if ( writer ) {
             rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
             // Enum to double
             double v = static_cast<double>(result.ellipseRatio());
             sWriter->writeValue( timestamp, focus, v );
         }
     }
     // Write Major
     const rcFPair& dimension = result.dimensions ();
     if ( dimension.x() > 0.0 ) {
         writer = getWriter( eWriterBodyMajor );
         if ( writer ) {
             rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
             // Enum to double
             double v = static_cast<double>(dimension.x());
             sWriter->writeValue( timestamp, focus, v );
         }
     }
     const float shortn = result.shortenning ();
     if ( shortn >= 0.0 ) {
         writer = getWriter( eWriterCardiacShortening);
         if ( writer ) {
             rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
             // Enum to double
             double v = static_cast<double>(shortn);
             sWriter->writeValue( timestamp, focus, v );
         }
     }
     // Contraction Frequency writer
     const float cfreq = result.contractionFrequency ();
     if ( cfreq > 0.0 ) {
       writer = getWriter( eWriterContractionFreq);
       if ( writer ) {
     rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
     // Enum to double
     double v = static_cast<double>(cfreq);
     sWriter->writeValue( timestamp, focus, v );
       }
     }
 #endif
 }
void rcCellWriterGroup::writeValues (const rcTimestamp & timestamp, const rcRect & focus, const rcVisualTarget & result)
Definition at line 539 of file rc_engineimplcells.cpp.
References rcVisualTarget::distance(), rcDegree::Double(), eWriterBodyDistance, eWriterBodyPersistence, eWriterBodyPosition, eWriterBodyQuality, eWriterBodySpeedDirection, eWriterBodyVelocity, getWriter(), rcDegree::norm(), rcVisualTarget::persistence(), rcBaseMotionPath::position(), rcVisualTarget::rmsQuality(), rcVisualTarget::velocity(), rcScalarWriter::writeValue(), rcPositionWriter::writeValue(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
     // Write position value
   rcFPair pos (result.position().x(), result.position().y());
     rcWriter* writer = getWriter( eWriterBodyPosition );
     if ( writer ) {
         rcPositionWriter* pWriter = dynamic_cast<rcPositionWriter*>( writer );
         pWriter->writeValue( timestamp, focus, pos);
     }
     // Write velocity value
     rcFPair vel (result.velocity().x(), result.velocity().y());
     writer = getWriter( eWriterBodyVelocity );
     if ( writer ) {
         rcPositionWriter* pWriter = dynamic_cast<rcPositionWriter*>( writer );
         pWriter->writeValue( timestamp, focus, vel);
     }
     // Write speed+direction value
     writer = getWriter( eWriterBodySpeedDirection );
     if ( writer ) {
         rcPositionWriter* pWriter = dynamic_cast<rcPositionWriter*>( writer );
         const rc2Fvector v( result.velocity().x(), result.velocity().y() );
         // Transform velocity vector to speed+angle
         if ( !v.isNull() ) {
             rcDegree degAngle(rcRadian( v.angle() ));
             const float angle = degAngle.norm().Double();
             pWriter->writeValue( timestamp, focus, rcFPair(v.len(), angle) );
         } else {
             pWriter->writeValue( timestamp, focus, rcFPair(v.x(), v.y()) );
         }
     }
     // Write quality measure
     writer = getWriter( eWriterBodyQuality );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         double v = result.rmsQuality();
         sWriter->writeValue( timestamp, focus, v );
     }
     // Write distance traveled
     writer = getWriter( eWriterBodyDistance );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         double v = result.distance();
         sWriter->writeValue( timestamp, focus, v );
     }
     // Write persistence
     writer = getWriter( eWriterBodyPersistence );
     if ( writer ) {
         rcScalarWriter* sWriter = dynamic_cast<rcScalarWriter*>( writer );
         double v = result.persistence();
         sWriter->writeValue( timestamp, focus, v );
     }
 }
Member Data Documentation
rcWriterGroup* rcCellWriterGroup::mCellGroup private
Definition at line 156 of file rc_engineimplbase.h.
Referenced by rcCellWriterGroup().
rcCellKey rcCellWriterGroup::mKey private
Definition at line 157 of file rc_engineimplbase.h.
map<rcWriterSemantics, rcWriter*> rcCellWriterGroup::mWriters private
Definition at line 158 of file rc_engineimplbase.h.
Referenced by flush(), getWriter(), rcCellWriterGroup(), and size().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplbase.h
src/visible/src/rc_engineimplcells.cpp