Visible: rcPersistenceManagerFactory Class Reference
rcPersistenceManagerFactory Class Reference
#include <include/baseUI/rc_persistencemanager.h>
Static Public Member Functions
static rcPersistenceManager * getPersistenceManager (const char *implKey=0)
Detailed Description
Definition at line 157 of file rc_persistencemanager.h.
Member Function Documentation
rcPersistenceManager * rcPersistenceManagerFactory::getPersistenceManager (const char * implKey = 0) static
Definition at line 191 of file rc_persistencemanagerimpl.cpp.
References rmUnused.
Referenced by rcFileSaveSettingWidget::browseRequest(), rcEngineMovieSaver::closeHdlr(), rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcEngineImpl::loadMovie(), main(), rcFileChoiceSettingWidget::multiFileBrowse(), rcMainWindow::rcMainWindow(), rcModelDomain::requestOpen(), rcModelDomain::requestSave(), rcExperimentDomainImpl::saveExperiment(), rcExperimentImpl::saveTo(), and rcFileChoiceSettingWidget::singleFileBrowse().
 {
     rmUnused( implKey );
     static rcPersistenceManagerImpl persistenceManager;
     return &persistenceManager;
 }
The documentation for this class was generated from the following files:
include/baseUI/rc_persistencemanager.h
src/baseUI/rc_persistencemanagerimpl.cpp