Visible: error_handler_base_body Class Reference
error_handler_base_body Class Reference
Public Member Functions
error_handler_base_body (void)
~error_handler_base_body (void)
void set_show (bool show)
void add_message_file (const std::string &file) throw (error_handler_read_error)
void add_message (const std::string &id, const std::string &text) throw ()
void push_supplement (const error_position &position, const std::string &message_id, const std::vector< std::string > &args)
void push_context (const error_position &position, const std::string &message_id, const std::vector< std::string > &args)
void pop_context (unsigned depth)
unsigned context_depth (void) const
std::vector< std::string > format_report (const error_position &position, const std::string &message_id, const std::string &status_id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::string format_id (const error_position &position, const std::string &message_id, const std::string &status_id, const std::vector< std::string > &args) throw (error_handler_id_error,error_handler_format_error)
std::string format_message (const message &mess, const std::vector< std::string > &args) throw (error_handler_format_error)
Public Attributes
std::vector< std::string > m_files
std::map< std::string, message > m_messages
bool m_show
std::list< pending_message > m_context
std::list< pending_message > m_supplement
Detailed Description
Definition at line 271 of file error_handler.cpp.
Constructor & Destructor Documentation
error_handler_base_body::error_handler_base_body (void) inline
Definition at line 281 of file error_handler.cpp.
References add_message(), context_id, default_context_format, default_error_format, default_fatal_format, default_information_format, default_position_format, default_supplement_format, default_warning_format, error_id, fatal_id, information_id, position_id, supplement_id, and warning_id.
     {
       // preload with default formats
       add_message(information_id,default_information_format);
       add_message(warning_id,default_warning_format);
       add_message(error_id,default_error_format);
       add_message(fatal_id,default_fatal_format);
       add_message(position_id,default_position_format);
       add_message(context_id,default_context_format);
       add_message(supplement_id,default_supplement_format);
     }
error_handler_base_body::~error_handler_base_body (void) inline
Definition at line 293 of file error_handler.cpp.
     {
     }
Member Function Documentation
void error_handler_base_body::add_message (const std::string & id, const std::string & text) throw () inline
Definition at line 344 of file error_handler.cpp.
References m_messages.
Referenced by error_handler_base_body().
     {
       m_messages[id] = message((unsigned)-1, 0, 0, text);
     }
void error_handler_base_body::add_message_file (const std::string & file) throw (error_handler_read_error) inline
Definition at line 302 of file error_handler.cpp.
References file_exists(), itext::getline(), m_files, and m_messages.
     {
       if (!file_exists(file)) throw error_handler_read_error(error_position(file,0,0), "file not found");
       m_files.push_back(file);
       iftext input(file);
       std::string line;
       unsigned l = 0;
       while(input.getline(line))
       {
         l++;
         if (line.size() > 0 && isalpha(line[0]))
         {
           // Get the id field which starts with an alphabetic and contains alphanumerics and underscore
           std::string id;
           unsigned i = 0;
           for (; i < line.size(); i++)
           {
             if (isalnum(line[i]) || line[i] == '_')
               id += line[i];
             else
               break;
           }
           // chk this ID is unique within the files - however it is legal to override a hard-coded message
           if (m_messages.find(id) != m_messages.end() && m_messages.find(id)->second.index() != (unsigned)-1)
             throw error_handler_read_error(error_position(file,l,i), std::string("repeated ID ") + id);
           // chk for at least one whitespace
           if (i >= line.size() || !isspace(line[i]))
             throw error_handler_read_error(error_position(file,l,i), "Missing whitespace");
           // skip whitespace
           for (; i < line.size(); i++)
           {
             if (!isspace(line[i]))
               break;
           }
           // now get the text part and add the message to the message map
           std::string text = line.substr(i, line.size()-i);
           m_messages[id] = message(m_files.size()-1, l, i, text);
         }
       }
     }
unsigned error_handler_base_body::context_depth (void) const inline
Definition at line 370 of file error_handler.cpp.
References m_context.
Referenced by error_handler_base::context_depth(), and error_handler_base::pop_context().
     {
       return m_context.size();
     }
std::string error_handler_base_body::format_id (const error_position & position, const std::string & message_id, const std::string & status_id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error) inline
Definition at line 398 of file error_handler.cpp.
References filespec_to_relative_path(), format_message(), m_messages, m_show, position_id, and to_string().
Referenced by format_report().
     {
       // This function creates a fully-formatted single-line message from a
       // combination of the position format and the status format plus the message
       // ID and its arguments. There are up to three levels of substitution
       // required to do this.
       // get the status format from the status_id
       std::map<std::string,message>::iterator status_found = m_messages.find(status_id);
       if (status_found == m_messages.end()) throw error_handler_id_error(status_id);
       // similarly get the message format
       std::map<std::string,message>::iterator message_found = m_messages.find(message_id);
       if (message_found == m_messages.end()) throw error_handler_id_error(message_id);
       // format the message contents
       std::string message_text = format_message(message_found->second, args);
       // now format the message in the status string (informational, warning etc).
       std::vector<std::string> status_args;
       status_args.push_back(message_text);
       std::string result = format_message(status_found->second, status_args);
       // finally, if the message is positional, format the status message in the positional string
       if (position.valid())
       {
         // get the position format from the message set
         std::map<std::string,message>::iterator position_found = m_messages.find(position_id);
         if (position_found == m_messages.end()) throw error_handler_id_error(position_id);
         // now format the message
         std::vector<std::string> position_args;
         position_args.push_back(result);
         position_args.push_back(filespec_to_relative_path(position.filename()));
         position_args.push_back(to_string(position.line()));
         position_args.push_back(to_string(position.column()));
         result = format_message(position_found->second, position_args);
         // add the source file text and position if that option is on
         if (m_show)
         {
           std::vector<std::string> show = position.show();
           for (unsigned i = 0; i < show.size(); i++)
           {
             result += std::string("\n");
             result += show[i];
           }
         }
       }
       return result;
     }
std::string error_handler_base_body::format_message (const message & mess, const std::vector< std::string > & args) throw (error_handler_format_error) inline
Definition at line 454 of file error_handler.cpp.
References error_handler_format_error::format(), m_files, and error_handler_format_error::offset().
Referenced by format_id().
     {
       // this function creates a formatted string from the stored message text and
       // the arguments. Most of the work is done in format_string. However, if a
       // formatting error is found, this function uses extra information stored in
       // the message data structure to improve the reporting of the error
       try
       {
         // This is the basic string formatter which performs parameter substitution
         // into a message. Parameter placeholders are in the form @0, @1 etc, where
         // the number is the index of the argument in the args vector. At present,
         // no field codes are supported as in printf formats Algorithm: scan the
         // input string and transfer it into the result. When an @nnn appears,
         // substitute the relevant argument from the args vector. Throw an exception
         // if its out of range. Also convert C-style escaped characters of the form
         // \n.
         std::string format = mess.text();
         std::string result;
         for (unsigned i = 0; i < format.size(); )
         {
           if (format[i] == '@')
           {
             // an argument substitution has been found - now find the argument number
             if (i+1 == format.size()) throw error_handler_format_error(format, i);
             i++;
             // chk for @@ which is an escaped form of '@'
             if (format[i] == '@')
             {
               result += '@';
               i++;
             }
             else
             {
               // there must be at least one digit in the substitution number
               if (!isdigit(format[i])) throw error_handler_format_error(format,i);
               unsigned a = 0;
               for (; i < format.size() && isdigit(format[i]); i++)
               {
                 a *= 10;
                 a += (format[i] - '0');
               }
               // chk for an argument request out of the range of the set of arguments
               if (a >= args.size()) throw error_handler_format_error(format,i-1);
               result += args[a];
             }
           }
           else if (format[i] == '\\')
           {
             // an escaped character has been found
             if (i+1 == format.size()) throw error_handler_format_error(format, i);
             i++;
             // do the special ones first, then all the others just strip off the \ and leave the following characters
             switch(format[i])
             {
             case '\\':
               result += '\\';
               break;
             case 't':
               result += '\t';
               break;
             case 'n':
               result += '\n';
               break;
             case 'r':
               result += '\r';
               break;
             case 'a':
               result += '\a';
               break;
             default:
               result += format[i];
               break;
             }
             i++;
           }
           else
           {
             // plain text found - just append to the result
             result += format[i++];
           }
         }
         return result;
       }
       catch(error_handler_format_error& exception)
       {
         // if the message came from a message file, improve the error reporting by adding file positional information
         // Also adjust the position from the start of the text (stored in the message field) to the column of the error
         if (mess.index() != (unsigned)-1)
           throw error_handler_format_error(error_position(m_files[mess.index()],
                                                           mess.line(),
                                                           mess.column()+exception.offset()),
                                            exception.format(),
                                            exception.offset());
         else
           throw exception;
       }
     }
std::vector<std::string> error_handler_base_body::format_report (const error_position & position, const std::string & message_id, const std::string & status_id, const std::vector< std::string > & args) throw (error_handler_id_error,error_handler_format_error) inline
Definition at line 375 of file error_handler.cpp.
References context_id, format_id(), m_context, m_supplement, and supplement_id.
     {
       // gathers everything together into a full multi-line report
       std::vector<std::string> result;
       // the first part of the report is the status message (info/warning/error/fatal)
       result.push_back(format_id(position, message_id, status_id, args));
       // now append any supplemental messages that have been stacked
       // these are printed in FIFO order i.e. the order that they were added to the handler
       for (std::list<pending_message>::iterator j = m_supplement.begin(); j != m_supplement.end(); j++)
         result.push_back(format_id(j->position(),j->id(),supplement_id,j->args()));
       // now discard any supplementary messages because they only persist until they are printed once
       m_supplement.clear();
       // now append any context messages that have been stacked
       // these are printed in LIFO order i.e. closest context first
       for (std::list<pending_message>::reverse_iterator i = m_context.rbegin(); i != m_context.rend(); i++)
         result.push_back(format_id(i->position(),i->id(),context_id,i->args()));
       return result;
     }
void error_handler_base_body::pop_context (unsigned depth) inline
Definition at line 364 of file error_handler.cpp.
References m_context.
Referenced by error_handler_base::pop_context().
     {
       while (depth < m_context.size())
         m_context.pop_back();
     }
void error_handler_base_body::push_context (const error_position & position, const std::string & message_id, const std::vector< std::string > & args) inline
Definition at line 357 of file error_handler.cpp.
References m_context.
     {
       m_context.push_back(pending_message(position,message_id,args));
     }
void error_handler_base_body::push_supplement (const error_position & position, const std::string & message_id, const std::vector< std::string > & args) inline
Definition at line 350 of file error_handler.cpp.
References m_supplement.
     {
       m_supplement.push_back(pending_message(position,message_id,args));
     }
void error_handler_base_body::set_show (bool show) inline
Definition at line 297 of file error_handler.cpp.
References m_show.
Referenced by error_handler_base::hide_position(), and error_handler_base::show_position().
     {
       m_show = show;
     }
Member Data Documentation
std::list<pending_message> error_handler_base_body::m_context
Definition at line 277 of file error_handler.cpp.
Referenced by context_depth(), format_report(), pop_context(), and push_context().
std::vector<std::string> error_handler_base_body::m_files
Definition at line 274 of file error_handler.cpp.
Referenced by add_message_file(), and format_message().
std::map<std::string,message> error_handler_base_body::m_messages
Definition at line 275 of file error_handler.cpp.
Referenced by add_message(), add_message_file(), and format_id().
bool error_handler_base_body::m_show
Definition at line 276 of file error_handler.cpp.
Referenced by format_id(), and set_show().
std::list<pending_message> error_handler_base_body::m_supplement
Definition at line 278 of file error_handler.cpp.
Referenced by format_report(), and push_supplement().
The documentation for this class was generated from the following file:
include/stlplus/error_handler.cpp