Visible: rcPeak< T > Class Template Reference
rcPeak< T > Class Template Reference
#include <include/visual/rc_peak.h>
Public Types
typedef T PeakType
Public Member Functions
rcPeak ()
rcPeak (T &v, const rcIPair &l)
rcPeak (T v, const rcIPair &l)
rcPeak (T v, const rcIPair &l, const rc2Fvector &interp, bool low_x_on_edge, bool high_x_on_edge, bool low_y_on_edge, bool high_y_on_edge)
const T & score () const
void score (T sc)
const rc2Fvector & location () const
const rc2Fvector & interpolated () const
const bitset< 4 > & edges () const
void interpolated (rc2Fvector &itp)
void location (rc2Fvector &itp)
void edges (bitset< 4 > &ned)
bool operator< (const rcPeak &rhs) const
bool operator== (const rcPeak &rhs) const
bool operator!= (const rcPeak &rhs) const
bool operator> (const rcPeak &rhs) const
Private Attributes
rcIPair _location
rc2Fvector _interp
T _value
bitset< 4 > _edge
Friends
ostream & operator<< (ostream &o, const rcPeak &p)
Detailed Description
template<typename T>
class rcPeak< T >
Definition at line 10 of file rc_peak.h.
Member Typedef Documentation
template<typename T > typedef T rcPeak< T >::PeakType
Definition at line 13 of file rc_peak.h.
Constructor & Destructor Documentation
template<typename T > rcPeak< T >::rcPeak () inline
Definition at line 15 of file rc_peak.h.
 : _location (0,0), _value ((T) 0), _interp (0.0f, 0.0f)  {};
template<typename T > rcPeak< T >::rcPeak (T & v, const rcIPair & l) inline
Definition at line 17 of file rc_peak.h.
     : _value (v), _location(l)
     {
     }
template<typename T > rcPeak< T >::rcPeak (T v, const rcIPair & l) inline
Definition at line 22 of file rc_peak.h.
     : _value (v), _location(l)
     {
     }
template<typename T > rcPeak< T >::rcPeak (T v, const rcIPair & l, const rc2Fvector & interp, bool low_x_on_edge, bool high_x_on_edge, bool low_y_on_edge, bool high_y_on_edge) inline
Definition at line 27 of file rc_peak.h.
References rcPeak< T >::_edge.
     : _value (v), _location(l), _interp (interp)
     {
         _edge[0] = low_x_on_edge;
         _edge[1] = high_x_on_edge;
         _edge[2] = low_y_on_edge;
         _edge[3] = high_y_on_edge;
     }
Member Function Documentation
template<typename T > const bitset<4>& rcPeak< T >::edges () const inline
Definition at line 40 of file rc_peak.h.
References rcPeak< T >::_edge.
 { return _edge; }
template<typename T > void rcPeak< T >::edges (bitset< 4 > & ned) inline
Definition at line 44 of file rc_peak.h.
References rcPeak< T >::_edge.
 { _edge = ned; }
template<typename T > const rc2Fvector& rcPeak< T >::interpolated () const inline
Definition at line 39 of file rc_peak.h.
References rcPeak< T >::_interp.
 { return _interp; }
template<typename T > void rcPeak< T >::interpolated (rc2Fvector & itp) inline
Definition at line 42 of file rc_peak.h.
References rcPeak< T >::_interp.
 { _interp = itp; }
template<typename T > const rc2Fvector& rcPeak< T >::location () const inline
Definition at line 38 of file rc_peak.h.
References rcPeak< T >::_interp.
 { return _interp; }
template<typename T > void rcPeak< T >::location (rc2Fvector & itp) inline
Definition at line 43 of file rc_peak.h.
References rcPeak< T >::_interp.
 { _interp = itp; }
template<typename T > bool rcPeak< T >::operator!= (const rcPeak< T > & rhs) const
template<typename T > bool rcPeak< T >::operator< (const rcPeak< T > & rhs) const inline
Definition at line 53 of file rc_peak.h.
References rcPeak< T >::score().
   {return score () < rhs.score ();}
template<typename T > bool rcPeak< T >::operator== (const rcPeak< T > & rhs) const inline
Definition at line 55 of file rc_peak.h.
References rcPeak< T >::score().
     {return score () == rhs.score ();}
template<typename T > bool rcPeak< T >::operator> (const rcPeak< T > & rhs) const
template<typename T > const T& rcPeak< T >::score () const inline
Definition at line 36 of file rc_peak.h.
References rcPeak< T >::_value.
Referenced by rcPeak< T >::operator<(), and rcPeak< T >::operator==().
 { return _value; }
template<typename T > void rcPeak< T >::score (T sc) inline
Definition at line 37 of file rc_peak.h.
References rcPeak< T >::_value.
 { _value = sc;  }
Friends And Related Function Documentation
template<typename T > ostream& operator<< (ostream & o, const rcPeak< T > & p) friend
Definition at line 47 of file rc_peak.h.
   {
     o << p.location << " , " << (int32) p.value << " , " << p.interp << "," << p.score;
     return o;
   }
Member Data Documentation
template<typename T > bitset<4> rcPeak< T >::_edge private
Definition at line 64 of file rc_peak.h.
Referenced by rcPeak< T >::edges(), and rcPeak< T >::rcPeak().
template<typename T > rc2Fvector rcPeak< T >::_interp private
Definition at line 62 of file rc_peak.h.
Referenced by rcPeak< T >::interpolated(), and rcPeak< T >::location().
template<typename T > rcIPair rcPeak< T >::_location private
Definition at line 61 of file rc_peak.h.
template<typename T > T rcPeak< T >::_value private
Definition at line 63 of file rc_peak.h.
Referenced by rcPeak< T >::score().
The documentation for this class was generated from the following file:
include/visual/rc_peak.h