Visible: rcEngineMovieSaver Class Reference
rcEngineMovieSaver Class Reference
#include <include/visiCore/rc_engineimplsave.h>
Public Member Functions
rcEngineMovieSaver (rcEngineImpl *engine, const rcMovieSaveCtrlReader &saveCtrl, const rcAcqInfo &acqInfo, rcEngineObserver *observer, rcBidirectionalRing< rcSharedFrameBufPtr > &saveRing, rcConditionVariable &buffersInTransmit)
virtual ~rcEngineMovieSaver ()
virtual void run ()
const rcMovieSaveStatusReader & saveStatus () const
void reset ()
void updateAcqInfo (const rcAcqInfo &acqInfo)
Public Member Functions inherited from rcRunnable
rcRunnable ()
virtual ~rcRunnable ()
void requestSeppuku ()
void clearSeppuku ()
Private Member Functions
void error_cleanup (rcSharedFrameBufPtr *sbp)
rcMovieFileState uninitializedHdlr (rcMovieFileState prevState)
rcMovieFileState waitHdlr (rcMovieFileState prevState)
rcMovieFileState delayHdlr (rcMovieFileState prevState)
rcMovieFileState openHdlr (rcMovieFileState prevState)
rcMovieFileState saveHdlr (rcMovieFileState prevState)
rcMovieFileState errorHdlr (rcMovieFileState prevState)
rcMovieFileState closeHdlr (rcMovieFileState prevState)
rcMovieFileState doneHdlr (rcMovieFileState prevState)
Private Attributes
FILE * _saveStream
rcSparseHistogram _hist
uint32 _histOverflow
rcMovieFileFormat2 _movieHdrRev2
rcTimestamp _prevTime
vector< int64 > _toc
rcEngineImpl * _engine
const rcMovieSaveCtrlReader & _saveCtrl
rcAcqInfo _acqInfo
rcMovieSaveStatus _saveStatus
rcEngineObserver * _observer
rcBidirectionalRing
< rcSharedFrameBufPtr > & _saveRing
rcConditionVariable & _buffersInTransmit
rcAtomicValue< uint32 > _curResetValue
uint32 _prevResetValue
std::string _saveFileName
char _warningMsg [1024]
Additional Inherited Members
Protected Member Functions inherited from rcRunnable
bool seppukuRequested ()
Detailed Description
Definition at line 29 of file rc_engineimplsave.h.
Constructor & Destructor Documentation
rcEngineMovieSaver::rcEngineMovieSaver (rcEngineImpl * engine, const rcMovieSaveCtrlReader & saveCtrl, const rcAcqInfo & acqInfo, rcEngineObserver * observer, rcBidirectionalRing< rcSharedFrameBufPtr > & saveRing, rcConditionVariable & buffersInTransmit)
Definition at line 57 of file rc_engineimplsave.cpp.
References _engine, _observer, and rmAssert.
         : _saveStream(NULL), _hist(6), _histOverflow(0), _engine(engine),
           _saveCtrl(saveCtrl), _acqInfo(acqInfo), _observer(observer), _saveRing(saveRing),
           _buffersInTransmit(buffersInTransmit), _curResetValue(0), _prevResetValue(0)
 {
   rmAssert(_engine);
   rmAssert(_observer);
 }
virtual rcEngineMovieSaver::~rcEngineMovieSaver () inline virtual
Definition at line 38 of file rc_engineimplsave.h.
 {}
Member Function Documentation
rcMovieFileState rcEngineMovieSaver::closeHdlr (rcMovieFileState prevState) private
Definition at line 456 of file rc_engineimplsave.cpp.
References _acqInfo, rcEngineMovieCapture::_bufRingSz, _engine, _hist, _histOverflow, _movieHdrRev2, _observer, _prevTime, _saveCtrl, _saveRing, _saveStatus, _saveStream, _toc, _warningMsg, rcBidirectionalRing< T >::availNewResources(), rcBidirectionalRing< T >::availNewSlots(), rcBidirectionalRing< T >::availReleasedResources(), rcBidirectionalRing< T >::availReleasedSlots(), rcSparseHistogram::average(), rcMovieFileFormat2::averageFrameRate(), rcMovieFileFormat2::baseTime(), rcSparseHistogram::binsUsed(), rcMovieFileFormat2::bytesInFrame(), rcAcqInfo::cameraInfo, rcExperimentAttributes::cellType, rcMovieFileExpExt::cellType(), rcExperimentAttributes::CO2, rcMovieFileExpExt::CO2(), rcMovieFileExpExt::comment(), rcExperimentAttributes::comments, rcMovieFileFormat2::depth(), eEngineRunning, eExperimentNativeFormat, eExperimentNativeMovieFormat, eMovieFileErr_CloseFailed, eMovieFileErr_NoErr, eMovieFileErr_SeekFailed, eMovieFileErr_VariableFrameRate, eMovieFileErr_WriteFailed, eMovieFileState_Done, eMovieFileState_Error, eMovieFileState_Save, endl(), rcMovieFileFormat2::extensionOffset(), rcPersistenceManager::fileFormatExportExtension(), rcMovieFileFormat2::frameCount(), rcEngineImpl::frameFlush(), rcPersistenceManager::generatorComment(), rcSparseHistogram::getArray(), rcEngineObserver::getExperimentAttributes(), getMovieErrorString(), rcMovieSaveCtrlReader::getMovieFileName(), rcPersistenceManagerFactory::getPersistenceManager(), rcEngineImpl::getState(), rcMovieFileFormat2::height(), rcMovieFileOrgExt::id(), rcMovieFileCamExt::id(), rcMovieFileExpExt::id(), rcExperimentAttributes::imagingMode, rcMovieFileExpExt::imagingMode(), rcExperimentAttributes::lensMag, rcMovieFileExpExt::lensMag(), movieExtensionEOF, movieOriginCaptureCertified, rcEngineObserver::notifyError(), rcEngineObserver::notifyRequestSave(), rcEngineObserver::notifyStatus(), rcEngineObserver::notifyWarning(), rcExperimentAttributes::O2, rcMovieFileExpExt::O2(), rcExperimentAttributes::otherMag, rcMovieFileExpExt::otherMag(), rcSparseHistogram::range(), rcMOVIE_WARN_MSG_SZ, rcEngineImpl::resumePreview(), rcMovieFileFormat2::rev(), rmAssert, rcTimestamp::secs(), rcEngineImpl::setCameraInfo(), rcEngineImpl::setCaptureInfo(), rcMovieSaveStatus::status(), rcEngineImpl::stop(), rcExperimentAttributes::temperature, rcMovieFileExpExt::temperature(), rcExperimentAttributes::title, rcMovieFileExpExt::title(), rcExperimentAttributes::treatment1, rcMovieFileExpExt::treatment1(), rcExperimentAttributes::treatment2, rcMovieFileExpExt::treatment2(), rcExperimentAttributes::userName, rcMovieFileExpExt::userName(), general_exception::what(), rcMovieFileFormat2::width(), rcMovieFileFormat2::write(), rcMovieFileExt::write(), rcMovieFileCamExt::write(), and rcMovieFileExpExt::write().
Referenced by run().
 {
   rmAssert(prevState == eMovieFileState_Save);
   rcMovieFileErr finalStatus = eMovieFileErr_NoErr;
   uint32 id = 1;
   uint32 min, max;
   _hist.range(min, max);
   if (_movieHdrRev2.frameCount() == 1)
       _movieHdrRev2.averageFrameRate(1); // Undefined, just put a number in here
   else if ((_hist.binsUsed() <= 2) && ((max - min) < 2))
       _movieHdrRev2.averageFrameRate(1000./_hist.average());
   else {
       rcTimestamp diff = _prevTime - rcTimestamp(_movieHdrRev2.baseTime());
       _movieHdrRev2.averageFrameRate((_movieHdrRev2.frameCount()-1)/diff.secs());
     finalStatus = eMovieFileErr_VariableFrameRate;
   }
 #ifdef rcWRITE_TOC
   // Resize to actual size
   _toc.resize(_movieHdrRev2.frameCount());
   // Write TOC
   rcMovieFileTocExt tocHdr( _toc.size() );
   if ( tocHdr.write( _saveStream, _toc ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;
   }
 #endif
   // Get generator name
   rcPersistenceManager* pm = rcPersistenceManagerFactory::getPersistenceManager();
   std::string generator = pm->generatorComment();
   // Write origin header
   rcMovieFileOrgExt orgHdr( movieOriginCaptureCertified, _movieHdrRev2.baseTime(), _movieHdrRev2.frameCount(),
                             _movieHdrRev2.width(), _movieHdrRev2.height(), _movieHdrRev2.depth(),
                             movieFormatRev(_movieHdrRev2.rev()), generator.c_str() );
   orgHdr.id( id++ );
   if ( orgHdr.write( _saveStream ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;
   }
 #ifdef rcWRITE_EXP
   const rcExperimentAttributes expAttr = _observer->getExperimentAttributes();
   // Write experiment info header
   rcMovieFileExpExt expHdr;
   expHdr.title( expAttr.title.c_str() );
   expHdr.userName( expAttr.userName.c_str() );
   expHdr.treatment1(expAttr.treatment1.c_str());
   expHdr.treatment2(expAttr.treatment2.c_str());
   expHdr.cellType(expAttr.cellType.c_str());
   expHdr.imagingMode(expAttr.imagingMode.c_str());
   expHdr.comment(expAttr.comments.c_str());
   try {
       // rcValue type conversion may throw en exception
       // catch it here so that movie save will not be compromised
       expHdr.lensMag(rcValue(expAttr.lensMag));
       expHdr.otherMag(rcValue(expAttr.otherMag));
       expHdr.temperature(rcValue(expAttr.temperature));
       expHdr.CO2(rcValue(expAttr.CO2));
       expHdr.O2(rcValue(expAttr.O2));
   } catch (general_exception& x) {
       cerr << "caught general_exception: " << x.what() << endl;
   }
   catch (...) {
       cerr << "caught unknown exception" << endl;
   }
   expHdr.id( id++ );
   if ( expHdr.write( _saveStream ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;
   }
   // Update GUI
   _engine->setCaptureInfo( orgHdr, expHdr );
 #else
   _engine->setCaptureInfo( orgHdr );
 #endif
 #ifdef rcWRITE_CAM
   // Write camera info header
   rcMovieFileCamExt camHdr = _acqInfo.cameraInfo;
   camHdr.id( id++ );
   if ( camHdr.write( _saveStream ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;
   }
   // Update GUI
   _engine->setCameraInfo( camHdr );
 #endif
   // Write EOF header
   rcMovieFileExt eofHdr( movieExtensionEOF );
   if ( eofHdr.write( _saveStream ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;;
   }
   /* Just about done. Rewind, write header and close file.
    */
   if (fseek(_saveStream, 0, SEEK_SET)) {
     perror("fseek failed");
     if (fclose(_saveStream))
       perror("fclose failed");
     _saveStatus.status(eMovieFileErr_SeekFailed);
     return eMovieFileState_Error;
   }
   // Update rev2 header
   const off_t movieRecordSz = sizeof(int64) + _movieHdrRev2.bytesInFrame();
   // Offset to start of headers
   _movieHdrRev2.extensionOffset( sizeof(_movieHdrRev2) + sizeof(_movieHdrRev2) +
                                  movieRecordSz*_movieHdrRev2.frameCount());
   // Write rev2 header
   if ( _movieHdrRev2.write( _saveStream ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;
   }
   if (fclose(_saveStream)) {
     perror("fclose failed");
     _saveStatus.status(eMovieFileErr_CloseFailed);
     return eMovieFileState_Error;
   }
   // Stop the engine
    if (_engine->getState() == eEngineRunning)
        _engine->stop();
   // Flush writers before saving
   _engine->frameFlush();
   _engine->resumePreview();
   rcExperimentFileFormat fileFormat = eExperimentNativeFormat;
   // Save experiment XML data
   rcPersistenceManager* persistenceManager =
     rcPersistenceManagerFactory::getPersistenceManager();
   std::string nativeExt = persistenceManager->fileFormatExportExtension(fileFormat);
   std::string reifyMovieExt =
     persistenceManager->fileFormatExportExtension( eExperimentNativeMovieFormat );
   // Choose movie save file name as base name
   std::string experimentFileName;
   std::string movieFile = _saveCtrl.getMovieFileName();
   std::string fileExt(movieFile, movieFile.size()-reifyMovieExt.length(),
            reifyMovieExt.length());
   // Strip movie extension
   if (fileExt == reifyMovieExt) {
       std::string baseName(movieFile, 0, movieFile.size()-reifyMovieExt.length());
       experimentFileName = baseName;
   }
   experimentFileName += nativeExt;
   int error = _observer->notifyRequestSave(experimentFileName.c_str(),
                        fileFormat);
   // Report error if necessary
   if (error) {
       // Error during XML save!
       std::string errorString("Capture metadata save error:\n");
       errorString += strerror( error );
       errorString += " for file " + experimentFileName;
       _observer->notifyError( errorString.c_str());
   }
   rmAssert(_saveRing.availReleasedResources() ==
        rcEngineMovieCapture::_bufRingSz);
   rmAssert(_saveRing.availNewSlots() == rcEngineMovieCapture::_bufRingSz);
   rmAssert(_saveRing.availReleasedSlots() == 0);
   rmAssert(_saveRing.availNewResources() == 0);
   {
     int64 bytesInMovie = ((_movieHdrRev2.bytesInFrame()) +
                             sizeof(int64))*_movieHdrRev2.frameCount();
     bytesInMovie += sizeof(_movieHdrRev2);
     fprintf(stderr, "Expected file size %12.0f frame count %d fps %f\n",
             (double)bytesInMovie, _movieHdrRev2.frameCount(),
             _movieHdrRev2.averageFrameRate());
   }
   if (finalStatus == eMovieFileErr_VariableFrameRate) {
     const rcSparseHistogram::sparseArray& histMap = _hist.getArray();
     rcSparseHistogram::sparseArray::const_iterator start = histMap.begin();
     rcSparseHistogram::sparseArray::const_iterator end = histMap.end();
     _warningMsg[0] = 0;
     uint32 curOffset = 0;
     for ( ; start != end; start++) {
       curOffset += strlen(_warningMsg + curOffset);
       const uint32 blen = rcMOVIE_WARN_MSG_SZ - curOffset;
       snprintf(_warningMsg + curOffset, blen, "\nInterval: %5d ms Count: %4d",
            (*start).first, (*start).second);
     }
     if (_histOverflow) {
       curOffset += strlen(_warningMsg + curOffset);
       const uint32 blen = rcMOVIE_WARN_MSG_SZ - curOffset;
       snprintf(_warningMsg + curOffset, blen, "\nInterval: Various  Count: %4d",
            _histOverflow);
     }
     std::string eMsg = "Warning! " +
       getMovieErrorString(eMovieFileErr_VariableFrameRate) + _warningMsg;
     fprintf(stderr, "Got warning: %s\n", eMsg.c_str());
     _observer->notifyWarning(eMsg.c_str());
   }
   else
     _observer->notifyStatus("Capture complete");
   _saveStatus.status(finalStatus);
   return eMovieFileState_Done;
 }
rcMovieFileState rcEngineMovieSaver::delayHdlr (rcMovieFileState prevState) private
Definition at line 156 of file rc_engineimplsave.cpp.
References _engine, _observer, _saveCtrl, _saveStatus, rcMovieSaveStatus::delayLeft(), eEngineStopped, eMovieFileErr_Aborted, eMovieFileState_Done, eMovieFileState_Open, eMovieFileState_Wait, rcMovieSaveStatusReader::getDelayLeft(), rcMovieSaveCtrlReader::getFrameCaptureDelayTime(), rcEngineImpl::getState(), rcEngineObserver::notifyWarning(), rmAssert, rcRunnable::seppukuRequested(), and rcMovieSaveStatus::status().
Referenced by run().
 {
   rmAssert(prevState == eMovieFileState_Wait);
   uint32 delayTime = _saveCtrl.getFrameCaptureDelayTime();
   if (delayTime) {
     uint32 delayTenthsSeconds = _saveStatus.getDelayLeft();
     rmAssert((delayTenthsSeconds & 1) == 0);
     do {
       usleep(200000); // sleep 200 ms
       if (seppukuRequested()) {
     _saveStatus.status(eMovieFileErr_Aborted);
     return eMovieFileState_Done;
       }
       if (_engine->getState() == eEngineStopped) {
     _observer->notifyWarning("Movie save aborted during delay "
                 "period.\nNo movie saved.");
     _saveStatus.status(eMovieFileErr_Aborted);
     return eMovieFileState_Done;
       }
       delayTenthsSeconds -= 2;
       _saveStatus.delayLeft(delayTenthsSeconds);
     } while (delayTenthsSeconds);
   }
   return eMovieFileState_Open;
 }
rcMovieFileState rcEngineMovieSaver::doneHdlr (rcMovieFileState prevState) private
Definition at line 681 of file rc_engineimplsave.cpp.
References _curResetValue, _engine, _hist, _histOverflow, _prevResetValue, _saveStatus, rcMovieSaveStatus::captureTime(), rcMovieSaveStatus::delayLeft(), eEngineRunning, eMovieFileErr_Aborted, eMovieFileErr_NoErr, eMovieFileState_Exit, eMovieFileState_Wait, rcEngineImpl::getState(), rcAtomicValue< T >::getValue(), rcSparseHistogram::reset(), rmAssert, rcRunnable::seppukuRequested(), rcMovieSaveStatus::status(), and rcEngineImpl::stop().
Referenced by run().
 {
   /* Regardless of the outcome of the movie save, the engine should be
    * stopped.
    */
   if (_engine->getState() == eEngineRunning) {
     _engine->stop();
   }
   rmAssert(_engine->getState() != eEngineRunning);
   uint32 curResetValue;
   /* Note: This would best be done with a condition variable instead
    * of a polling loop.
    */
   while (_curResetValue.getValue(curResetValue) == _prevResetValue) {
     if (seppukuRequested()) {
       _saveStatus.status(eMovieFileErr_Aborted);
       return eMovieFileState_Exit;
     }
     usleep(100000); // Sleep for 100ms
   }
   _prevResetValue = curResetValue;
   _saveStatus.delayLeft(0);
   _saveStatus.captureTime(0);
   _saveStatus.status(eMovieFileErr_NoErr);
   _hist.reset();
   _histOverflow = 0;
   return eMovieFileState_Wait;
 }
void rcEngineMovieSaver::error_cleanup (rcSharedFrameBufPtr * sbp) private
Definition at line 80 of file rc_engineimplsave.cpp.
References _buffersInTransmit, rcEngineMovieCapture::_bufRingSz, _saveRing, rcConditionVariable::decrementVariable(), rcBidirectionalRing< T >::releaseResource(), and rmAssert.
Referenced by saveHdlr().
 {
   rmAssert(sbp);
   *sbp = 0; // Free resource
   bool retval = _saveRing.releaseResource(sbp);
   rmAssert(retval);
   _buffersInTransmit.decrementVariable(1, rcEngineMovieCapture::_bufRingSz);
 }
rcMovieFileState rcEngineMovieSaver::errorHdlr (rcMovieFileState prevState) private
Definition at line 439 of file rc_engineimplsave.cpp.
References _observer, _saveStatus, eMovieFileState_Done, getMovieErrorString(), rcMovieSaveStatusReader::getStatus(), and rcEngineObserver::notifyError().
Referenced by run().
 {
   std::string eMsg = "Error!: " + getMovieErrorString(_saveStatus.getStatus());
   fprintf(stderr, "Got warning: %s\n", eMsg.c_str());
   _observer->notifyError(eMsg.c_str());
   return eMovieFileState_Done;
 }
rcMovieFileState rcEngineMovieSaver::openHdlr (rcMovieFileState prevState) private
Definition at line 194 of file rc_engineimplsave.cpp.
References _movieHdrRev2, _saveFileName, _saveStatus, _saveStream, _toc, cMaxSaveFrameCount, eMovieFileErr_OpenFailed, eMovieFileErr_SeekFailed, eMovieFileErr_WriteFailed, eMovieFileState_Delay, eMovieFileState_Error, eMovieFileState_Save, eMovieFileState_Wait, movieFormatInvalid, NULL, rmAssert, rcMovieSaveStatus::status(), and rcMovieFileFormat2::write().
Referenced by run().
 {
   rmAssert((prevState == eMovieFileState_Wait) ||
        (prevState == eMovieFileState_Delay));
   fprintf(stderr, "MS: output file name %s\n", _saveFileName.data());
   rmAssert(_saveFileName.size());
   _saveStream = fopen(_saveFileName.data(), "w+");
   if (_saveStream == NULL) {
     perror("fopen failed");
     _saveStatus.status(eMovieFileErr_OpenFailed);
     return eMovieFileState_Error;
   }
   /* Write out a dummy header indicating the movie is invalid.  Will
    * only be changed to a valid header at the very end when we know
    * the movie is good.
    */
   rcMovieFileFormat2 movieHdr(movieFormatInvalid);
   // Write basic header
   if ( movieHdr.write( _saveStream ) ) {
       _saveStatus.status(eMovieFileErr_WriteFailed);
       return eMovieFileState_Error;
   }
 #ifdef rcWRITE_TOC
   // Reserve plenty of space for TOC so it's fast to assign values
   // TODO: estimate number of frames to be captured
   _toc = vector<int64>(cMaxSaveFrameCount,0);
 #endif
   /* Should be good to go now, but there are problems with frames
    * getting lost at the beginning of a movie save. Investigation
    * revealed that the action of starting to save large amounts of
    * data was a cause of these symptoms. Why this happens is unknown
    * and should be investigated further. To work around this, simulate
    * starting a movie save by writing a bunch of random data to disk,
    * seeking back to the end of the movie header and then waiting a
    * short time to let any missed frames to to work there way out of
    * the video stream.
    */
 #if 0
   /*
    * Commented this out to prevent inexplicable disk write out freeze at start
    * of capture. Don't know why this works, but we'll try it out.
    *
    * peter
    *
    * 6/21/05
    */
   char* data = (char*)malloc(1000000);
   rmAssert(data);
   for (int i = 0; i < 10; i++) {
     if (fwrite(data, 1000000, 1, _saveStream) != 1) {
       perror("1st fwrite failed");
       if (fclose(_saveStream))
     perror("fclose failed");
       _saveStatus.status(eMovieFileErr_WriteFailed);
       free(data);
       return eMovieFileState_Error;
     }
     // fflush(_saveStream);
   }
   free(data);
 #endif
   if (fseek(_saveStream, sizeof(_movieHdrRev2), SEEK_SET)) {
     perror("fseek failed");
     if (fclose(_saveStream))
       perror("fclose failed");
     _saveStatus.status(eMovieFileErr_SeekFailed);
     return eMovieFileState_Error;
   }
 #ifdef rcWRITE_TOC
   // Touch first value again
   _toc[0] = 0;
 #endif
   for (int i = 0; i < 10; i++)
     usleep(200000);
   return eMovieFileState_Save;
 }
void rcEngineMovieSaver::reset (void)
Definition at line 71 of file rc_engineimplsave.cpp.
References _curResetValue, _saveStatus, eMovieFileState_Done, rcMovieSaveStatusReader::getState(), rcAtomicValue< T >::getValue(), rmAssert, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::saveReset().
 {
   rmAssert(eMovieFileState_Done == _saveStatus.getState());
   uint32 curValue;
   _curResetValue.getValue(curValue);
   _curResetValue.setValue(curValue+1);
 }
void rcEngineMovieSaver::run (void) virtual
Implements rcRunnable.
Definition at line 721 of file rc_engineimplsave.cpp.
References _saveStatus, closeHdlr(), delayHdlr(), doneHdlr(), eMovieFileState_Close, eMovieFileState_Delay, eMovieFileState_Done, eMovieFileState_Error, eMovieFileState_Exit, eMovieFileState_Open, eMovieFileState_Save, eMovieFileState_Uninitialized, eMovieFileState_Wait, errorHdlr(), rcMovieSaveStatusReader::getState(), openHdlr(), rmAssert, saveHdlr(), rcMovieSaveStatus::state(), uninitializedHdlr(), and waitHdlr().
 {
   rcMovieFileState curState  = _saveStatus.getState();
   rcMovieFileState prevState = curState;
   for ( ; curState != eMovieFileState_Exit; ) {
     rcMovieFileState newState = eMovieFileState_Uninitialized; // Quiet compiler
     switch (curState) {
     case eMovieFileState_Uninitialized:
       newState = uninitializedHdlr(prevState);
       break;
     case eMovieFileState_Wait:
       newState = waitHdlr(prevState);
       break;
     case eMovieFileState_Delay:
       newState = delayHdlr(prevState);
       break;
     case eMovieFileState_Open:
       newState = openHdlr(prevState);
       break;
     case eMovieFileState_Save:
       newState = saveHdlr(prevState);
       break;
     case eMovieFileState_Close:
       newState = closeHdlr(prevState);
       break;
     case eMovieFileState_Error:
       newState = errorHdlr(prevState);
       break;
     case eMovieFileState_Done:
       newState = doneHdlr(prevState);
       break;
     case eMovieFileState_Exit:
       rmAssert(0);
       break;
     } // End of: switch (curState)
     rmAssert(newState != eMovieFileState_Uninitialized);
     prevState = curState;
     curState = newState;
     _saveStatus.state(curState);
   } // for ( ; curState != eMovieFileState_Done; )
   return;
 }
rcMovieFileState rcEngineMovieSaver::saveHdlr (rcMovieFileState prevState) private
Definition at line 292 of file rc_engineimplsave.cpp.
References _buffersInTransmit, rcEngineMovieCapture::_bufRingSz, _hist, _histOverflow, _movieHdrRev2, _prevTime, _saveRing, _saveStatus, _saveStream, _toc, rcSparseHistogram::add(), rcBidirectionalRing< T >::availNewResources(), rcMovieFileFormat2::bytesInFrame(), cMaxSaveFrameCount, rcConditionVariable::decrementVariable(), eMovieFileErr_MaxFramesExceeded, eMovieFileErr_NotHomogenous, eMovieFileErr_NullInput, eMovieFileErr_UnsupportedType, eMovieFileErr_WriteFailed, eMovieFileState_Close, eMovieFileState_Error, eMovieFileState_Open, eMovieFileState_Uninitialized, error_cleanup(), rcMovieFileFormat2::frameCount(), rcMovieFileFormat2::height(), movieFormatRevLatest, rcBidirectionalRing< T >::releaseResource(), rmAssert, rcTimestamp::secs(), rcMovieSaveStatus::status(), rcBidirectionalRing< T >::takeResource(), rcConditionVariable::waitUntilGreaterThan(), and rcMovieFileFormat2::width().
Referenced by run(), and uninitializedHdlr().
 {
   if (prevState == eMovieFileState_Uninitialized) {
     /* If any functions different than those used by openHdlr are
      * required, try to make nop use of them here before returning.
      */
     return eMovieFileState_Uninitialized;
   }
   rmAssert(prevState == eMovieFileState_Open);
   /* Note: Something should always get sent - even if its just a NULL
    * buffer ptr.
    */
   if (_saveRing.availNewResources() == 0) {
     _buffersInTransmit.waitUntilGreaterThan(0);
     if (!_saveRing.availNewResources()) {
       if (fclose(_saveStream))
     perror("fclose failed");
       rmAssert(0);
     }
   }
   rcSharedFrameBufPtr* sbp = _saveRing.takeResource();
   if (!sbp) {
     if (fclose(_saveStream))
       perror("fclose failed");
     rmAssert(0);
   }
   if (!*sbp) {
     if (fclose(_saveStream))
       perror("fclose failed");
     _saveStatus.status(eMovieFileErr_NullInput);
     error_cleanup(sbp);
     return eMovieFileState_Error;
   }
   if ((*sbp)->rowPad()) {
     if (fclose(_saveStream))
       perror("fclose failed");
     _saveStatus.status(eMovieFileErr_UnsupportedType);
     error_cleanup(sbp);
     return eMovieFileState_Error;
   }
   /* Initialize the movie header with the info from the
    * first frame.
    */
   _movieHdrRev2 = rcMovieFileFormat2( *sbp, movieFormatRevLatest );
   size_t bytesInFrame = _movieHdrRev2.bytesInFrame();
   bool firstLoop = true;
   while (*sbp) {
       if ((static_cast<int32>(_movieHdrRev2.width()) != (*sbp)->width()) ||
           (static_cast<int32>(_movieHdrRev2.height()) != (*sbp)->height()) || (*sbp)->rowPad()) {
       if (fclose(_saveStream))
     perror("fclose failed");
       _saveStatus.status(eMovieFileErr_NotHomogenous);
       error_cleanup(sbp);
       return eMovieFileState_Error;
     }
     if (firstLoop)
       firstLoop = false;
     else {
       rcTimestamp diff = (*sbp)->timestamp() - _prevTime;
       if (!_hist.add(uint32(diff.secs() * 1000)))
     _histOverflow++;
     }
     int64 timestamp = (*sbp)->timestamp()._timestamp;
     _prevTime = (*sbp)->timestamp();
     if (fwrite(&timestamp, sizeof(int64), 1, _saveStream) != 1) {
       perror("fwrite of timestamp failed");
       if (fclose(_saveStream))
     perror("fclose failed");
       _saveStatus.status(eMovieFileErr_WriteFailed);
       error_cleanup(sbp);
       return eMovieFileState_Error;
     }
     if (fwrite((*sbp)->alignedRawData(), bytesInFrame, 1, _saveStream) != 1) {
       perror("fwrite of frame data failed");
       if (fclose(_saveStream))
     perror("fclose failed");
       _saveStatus.status(eMovieFileErr_WriteFailed);
       error_cleanup(sbp);
       return eMovieFileState_Error;
     }
     //   fflush(_saveStream);
     *sbp = 0; // Free frame buffer
     if (!_saveRing.releaseResource(sbp)) {
       if (fclose(_saveStream))
     perror("fclose failed");
       rmAssert(0);
     }
     _buffersInTransmit.decrementVariable(1, rcEngineMovieCapture::_bufRingSz);
     if (_saveRing.availNewResources() == 0) {
       _buffersInTransmit.waitUntilGreaterThan(0);
       if (!_saveRing.availNewResources()) {
     if (fclose(_saveStream))
       perror("fclose failed");
     rmAssert(0);
       }
     }
     sbp = _saveRing.takeResource();
     if (!sbp) {
       if (fclose(_saveStream))
     perror("fclose failed");
       rmAssert(0);
     }
     const uint32 frameCount = _movieHdrRev2.frameCount();
 #ifdef rcWRITE_TOC
     if ( frameCount < cMaxSaveFrameCount )
         _toc[frameCount] = timestamp;
     else {
         _saveStatus.status(eMovieFileErr_MaxFramesExceeded);
         perror("Maximum allowed frame count exceeded");
         return eMovieFileState_Error;
     }
 #endif
     _movieHdrRev2.frameCount(frameCount+1);
   } // End of: while (*sbp)
   if (!_saveRing.releaseResource(sbp)) {
     if (fclose(_saveStream))
       perror("fclose failed");
     rmAssert(0);
   }
   _buffersInTransmit.decrementVariable(1, rcEngineMovieCapture::_bufRingSz);
   return eMovieFileState_Close;
 }
const rcMovieSaveStatusReader& rcEngineMovieSaver::saveStatus () const inline
Definition at line 47 of file rc_engineimplsave.h.
References _saveStatus.
Referenced by rcEngineMovieCapture::closeSaveFile(), rcEngineMovieCapture::delayLeft(), rcEngineMovieCapture::killSaveThread(), rcEngineMovieCapture::run(), rcEngineMovieCapture::saveComplete(), rcEngineMovieCapture::saveReset(), and rcEngineMovieCapture::saveState().
 { return _saveStatus; }
rcMovieFileState rcEngineMovieSaver::uninitializedHdlr (rcMovieFileState prevState) private
Definition at line 97 of file rc_engineimplsave.cpp.
References eMovieFileState_Uninitialized, eMovieFileState_Wait, rmAssert, and saveHdlr().
Referenced by run().
 {
   rmAssert(prevState == eMovieFileState_Uninitialized);
   saveHdlr(eMovieFileState_Uninitialized);
   return eMovieFileState_Wait;
 }
void rcEngineMovieSaver::updateAcqInfo (const rcAcqInfo & acqInfo)
Definition at line 717 of file rc_engineimplsave.cpp.
References _acqInfo.
Referenced by rcEngineMovieCapture::closeSaveFile().
 {
     _acqInfo = acqInfo;
 }
rcMovieFileState rcEngineMovieSaver::waitHdlr (rcMovieFileState prevState) private
Definition at line 110 of file rc_engineimplsave.cpp.
References _engine, _saveCtrl, _saveFileName, _saveStatus, rcMovieSaveStatus::captureTime(), rcMovieSaveStatus::delayLeft(), delayTimeToSeconds, eEngineRunning, eEngineStopped, eMovieFileErr_Aborted, eMovieFileState_Delay, eMovieFileState_Done, eMovieFileState_Open, eMovieFileState_Uninitialized, rcMovieSaveCtrlReader::getFrameCaptureDelayTime(), rcMovieSaveCtrlReader::getFrameCaptureTime(), rcMovieSaveCtrlReader::getOutputFileName(), rcEngineImpl::getState(), rmAssert, rcRunnable::seppukuRequested(), rcEngineImpl::start(), and rcMovieSaveStatus::status().
Referenced by run().
 {
   rmAssert((prevState == eMovieFileState_Uninitialized) ||
        (prevState == eMovieFileState_Done));
   _saveFileName = _saveCtrl.getOutputFileName();
   /* Note: This would best be done with a condition variable instead
    * of a polling loop.
    */
   while (_saveFileName.empty()) {
     usleep(100000); // Sleep for 100ms
     if (seppukuRequested()) {
       _saveStatus.status(eMovieFileErr_Aborted);
       return eMovieFileState_Done;
     }
     _saveFileName = _saveCtrl.getOutputFileName();
   }
   if (_engine->getState() == eEngineStopped)
     _engine->start();
   rmAssert(_engine->getState() == eEngineRunning);
   uint32 captureTime = _saveCtrl.getFrameCaptureTime();
   _saveStatus.captureTime(captureTime * 60);
   uint32 delayTime = _saveCtrl.getFrameCaptureDelayTime();
   if (delayTime) {
     _saveStatus.delayLeft(delayTime * delayTimeToSeconds * 10);
     return eMovieFileState_Delay;
   }
   return eMovieFileState_Open;
 }
Member Data Documentation
rcAcqInfo rcEngineMovieSaver::_acqInfo private
Definition at line 132 of file rc_engineimplsave.h.
Referenced by closeHdlr(), and updateAcqInfo().
rcConditionVariable& rcEngineMovieSaver::_buffersInTransmit private
Definition at line 136 of file rc_engineimplsave.h.
Referenced by error_cleanup(), and saveHdlr().
rcAtomicValue<uint32> rcEngineMovieSaver::_curResetValue private
Definition at line 137 of file rc_engineimplsave.h.
Referenced by doneHdlr(), and reset().
rcEngineImpl* rcEngineMovieSaver::_engine private
Definition at line 130 of file rc_engineimplsave.h.
Referenced by closeHdlr(), delayHdlr(), doneHdlr(), rcEngineMovieSaver(), and waitHdlr().
rcSparseHistogram rcEngineMovieSaver::_hist private
Definition at line 120 of file rc_engineimplsave.h.
Referenced by closeHdlr(), doneHdlr(), and saveHdlr().
uint32 rcEngineMovieSaver::_histOverflow private
Definition at line 121 of file rc_engineimplsave.h.
Referenced by closeHdlr(), doneHdlr(), and saveHdlr().
rcMovieFileFormat2 rcEngineMovieSaver::_movieHdrRev2 private
Definition at line 122 of file rc_engineimplsave.h.
Referenced by closeHdlr(), openHdlr(), and saveHdlr().
rcEngineObserver* rcEngineMovieSaver::_observer private
Definition at line 134 of file rc_engineimplsave.h.
Referenced by closeHdlr(), delayHdlr(), errorHdlr(), and rcEngineMovieSaver().
uint32 rcEngineMovieSaver::_prevResetValue private
Definition at line 138 of file rc_engineimplsave.h.
Referenced by doneHdlr().
rcTimestamp rcEngineMovieSaver::_prevTime private
Definition at line 123 of file rc_engineimplsave.h.
Referenced by closeHdlr(), and saveHdlr().
const rcMovieSaveCtrlReader& rcEngineMovieSaver::_saveCtrl private
Definition at line 131 of file rc_engineimplsave.h.
Referenced by closeHdlr(), delayHdlr(), and waitHdlr().
std::string rcEngineMovieSaver::_saveFileName private
Definition at line 139 of file rc_engineimplsave.h.
Referenced by openHdlr(), and waitHdlr().
rcBidirectionalRing<rcSharedFrameBufPtr>& rcEngineMovieSaver::_saveRing private
Definition at line 135 of file rc_engineimplsave.h.
Referenced by closeHdlr(), error_cleanup(), and saveHdlr().
rcMovieSaveStatus rcEngineMovieSaver::_saveStatus private
Definition at line 133 of file rc_engineimplsave.h.
Referenced by closeHdlr(), delayHdlr(), doneHdlr(), errorHdlr(), openHdlr(), reset(), run(), saveHdlr(), saveStatus(), and waitHdlr().
FILE* rcEngineMovieSaver::_saveStream private
Definition at line 119 of file rc_engineimplsave.h.
Referenced by closeHdlr(), openHdlr(), and saveHdlr().
vector<int64> rcEngineMovieSaver::_toc private
Definition at line 124 of file rc_engineimplsave.h.
Referenced by closeHdlr(), openHdlr(), and saveHdlr().
char rcEngineMovieSaver::_warningMsg[1024] private
Definition at line 140 of file rc_engineimplsave.h.
Referenced by closeHdlr().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplsave.h
src/visible/src/rc_engineimplsave.cpp