Visible: rcStatusBar Class Reference
rcStatusBar Class Reference
#include <include/visUI/rc_statusbar.h>
Public Slots
void updateState (rcExperimentState state)
void updateStatus (const char *statusString)
Public Member Functions
rcStatusBar (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
~rcStatusBar ()
Detailed Description
Definition at line 8 of file rc_statusbar.h.
Constructor & Destructor Documentation
rcStatusBar::rcStatusBar (QWidget * parent = 0, const char * name = 0, Qt::WFlags f = 0)
Definition at line 9 of file rc_statusbar.cpp.
References eExperimentEmpty, rcModelDomain::getModelDomain(), rcUNUSED, updateState(), and updateStatus().
     : QStatusBar( parent, name )
 {
     rcUNUSED( f );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     setSizeGripEnabled( false );
     // Model connections
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateStatus( const char* ) ) ,
              this   , SLOT( updateStatus( const char* ) ) );
     // in case we don't get an initial signal
     updateState( eExperimentEmpty );
 }
rcStatusBar::~rcStatusBar ()
Definition at line 29 of file rc_statusbar.cpp.
 {
 }
Member Function Documentation
void rcStatusBar::updateState (rcExperimentState state) slot
Definition at line 33 of file rc_statusbar.cpp.
References eExperimentEmpty, eExperimentEnded, eExperimentLocked, eExperimentPlayback, and eExperimentRunning.
Referenced by rcStatusBar().
 {
     switch( state ) {
     case eExperimentEmpty:          // experiment was created but not run
         message("Ready");
         break;
     case eExperimentRunning:        // experiment is running
         message("Running...");
         break;
     case eExperimentPlayback:       // experiment is running
         message("Playing...");
         break;
     case eExperimentEnded:          // experiment has ended
         message("Ready");
         break;
     case eExperimentLocked:         // experiment has ended and been saved
         message("Saved");
         break;
     default:
         break;
     }
 }
void rcStatusBar::updateStatus (const char * statusString) slot
Definition at line 61 of file rc_statusbar.cpp.
Referenced by rcStatusBar().
 {
     if ( statusString ) {
         message( statusString );
     }
     else {
         clear();
     }
 }
The documentation for this class was generated from the following files:
include/visUI/rc_statusbar.h
src/visible/qt/rc_statusbar.cpp