Visible: async_subprocess Class Reference
async_subprocess Class Reference
#include <include/stlplus/subprocesses.hpp>
Public Member Functions
async_subprocess (void)
virtual ~async_subprocess (void)
void add_variable (const std::string &name, const std::string &value)
bool remove_variable (const std::string &name)
bool spawn (const std::string &path, const arg_vector &argv, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)
bool spawn (const std::string &command_line, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)
virtual bool callback (void)
bool tick (void)
bool kill (void)
int write_stdin (std::string &buffer)
int read_stdout (std::string &buffer)
int read_stderr (std::string &buffer)
void close_stdin (void)
void close_stdout (void)
void close_stderr (void)
bool error (void) const
int error_number (void) const
std::string error_text (void) const
int exit_status (void) const
Private Member Functions
void set_error (int)
Private Attributes
int pid
int child_in
int child_out
int child_err
env_vector env
int err
int status
Detailed Description
Definition at line 226 of file subprocesses.hpp.
Constructor & Destructor Documentation
async_subprocess::async_subprocess (void)
Definition at line 1455 of file subprocesses.cpp.
References child_err, child_in, child_out, err, pid, and status.
 {
   pid = -1;
   child_in = -1;
   child_out = -1;
   child_err = -1;
   err = 0;
   status = 0;
 }
async_subprocess::~async_subprocess (void) virtual
Definition at line 1485 of file subprocesses.cpp.
References close_stderr(), close_stdin(), close_stdout(), kill(), and pid.
 {
   if (pid != -1)
   {
     close_stdin();
     close_stdout();
     close_stderr();
     kill();
     for (;;)
     {
       int wait_status = 0;
       int wait_ret_val = waitpid(pid, &wait_status, 0);
       if (wait_ret_val != -1 || errno != EINTR) break;
     }
   }
 }
Member Function Documentation
void async_subprocess::add_variable (const std::string & name, const std::string & value)
Definition at line 1509 of file subprocesses.cpp.
 {
   env.add(name, value);
 }
bool async_subprocess::callback (void) virtual
Definition at line 1704 of file subprocesses.cpp.
Referenced by tick().
 {
   return true;
 }
void async_subprocess::close_stderr (void)
Definition at line 2061 of file subprocesses.cpp.
References child_err, and close().
Referenced by kill(), read_stderr(), and ~async_subprocess().
 {
   if (child_err != -1)
   {
     ::close(child_err);
     child_err = -1;
   }
 }
void async_subprocess::close_stdin (void)
Definition at line 2013 of file subprocesses.cpp.
References child_in, and close().
Referenced by kill(), write_stdin(), and ~async_subprocess().
 {
   if (child_in != -1)
   {
     ::close(child_in);
     child_in = -1;
   }
 }
void async_subprocess::close_stdout (void)
Definition at line 2037 of file subprocesses.cpp.
References child_out, and close().
Referenced by kill(), read_stdout(), and ~async_subprocess().
 {
   if (child_out != -1)
   {
     ::close(child_out);
     child_out = -1;
   }
 }
bool async_subprocess::error (void) const
Definition at line 2072 of file subprocesses.cpp.
References err.
 {
   return err != 0;
 }
int async_subprocess::error_number (void) const
Definition at line 2077 of file subprocesses.cpp.
References err.
 {
   return err;
 }
std::string async_subprocess::error_text (void) const
Definition at line 2101 of file subprocesses.cpp.
References err, and to_string().
 {
   if (err == 0) return std::string();
   char* text = strerror(err);
   if (text) return std::string(text);
   return "error number " + to_string(err);
 }
int async_subprocess::exit_status (void) const
Definition at line 2111 of file subprocesses.cpp.
References status.
 {
   return status;
 }
bool async_subprocess::kill (void)
Definition at line 1788 of file subprocesses.cpp.
References close_stderr(), close_stdin(), close_stdout(), pid, and set_error().
Referenced by tick(), and ~async_subprocess().
 {
   if (pid == -1) return false;
   close_stdin();
   close_stdout();
   close_stderr();
   if (::kill(pid, SIGINT) == -1)
   {
     set_error(errno);
     return false;
   }
   return true;
 }
int async_subprocess::read_stderr (std::string & buffer)
Definition at line 1964 of file subprocesses.cpp.
References itext::bytes(), child_err, close_stderr(), and set_error().
 {
   if (child_err == -1) return -1;
   // rely on the pipe being non-blocking
   int buffer_size = 256;
   char* tmp = new char[buffer_size];
   int bytes = read(child_err, tmp, buffer_size);
   if (bytes == -1 && errno == EAGAIN)
   {
     // not ready
     delete[] tmp;
     return 0;
   }
   if (bytes == -1)
   {
     // error
     set_error(errno);
     close_stderr();
     delete[] tmp;
     return -1;
   }
   if (bytes == 0)
   {
     // EOF
     close_stderr();
     delete[] tmp;
     return -1;
   }
   // successful read
   buffer.append(tmp, bytes);
   delete[] tmp;
   return bytes;
 }
int async_subprocess::read_stdout (std::string & buffer)
Definition at line 1890 of file subprocesses.cpp.
References itext::bytes(), child_out, close_stdout(), and set_error().
 {
   if (child_out == -1) return -1;
   // rely on the pipe being non-blocking
   int buffer_size = 256;
   char* tmp = new char[buffer_size];
   int bytes = read(child_out, tmp, buffer_size);
   if (bytes == -1 && errno == EAGAIN)
   {
     // not ready
     delete[] tmp;
     return 0;
   }
   if (bytes == -1)
   {
     // error
     set_error(errno);
     close_stdout();
     delete[] tmp;
     return -1;
   }
   if (bytes == 0)
   {
     // EOF
     close_stdout();
     delete[] tmp;
     return -1;
   }
   // successful read
   buffer.append(tmp, bytes);
   delete[] tmp;
   return bytes;
 }
bool async_subprocess::remove_variable (const std::string & name)
Definition at line 1514 of file subprocesses.cpp.
 {
   return env.remove(name);
 }
void async_subprocess::set_error (int e) private
Definition at line 1504 of file subprocesses.cpp.
References err.
Referenced by kill(), read_stderr(), read_stdout(), spawn(), tick(), and write_stdin().
 {
   err = e;
 }
bool async_subprocess::spawn (const std::string & path, const arg_vector & argv, bool connect_stdin = false, bool connect_stdout = false, bool connect_stderr = false)
Definition at line 1585 of file subprocesses.cpp.
References arg_vector::argv(), child_err, child_in, child_out, close(), pid, and set_error().
Referenced by spawn().
 {
   bool result = true;
   // first create the pipes to be used to connect to the child stdin/out/err
   int stdin_pipe [2] = {-1, -1};
   if (connect_stdin)
     pipe(stdin_pipe);
   int stdout_pipe [2] = {-1, -1};
   if (connect_stdout)
     pipe(stdout_pipe);
   int stderr_pipe [2] = {-1, -1};
   if (connect_stderr)
     pipe(stderr_pipe);
   // now create the subprocess
   // In Unix, this is done by forking (creating two copies of the parent), then overwriting the child copy using exec
   pid = ::fork();
   switch(pid)
   {
   case -1:   // failed to fork
     set_error(errno);
     if (connect_stdin)
     {
       ::close(stdin_pipe[0]);
       ::close(stdin_pipe[1]);
     }
     if (connect_stdout)
     {
       ::close(stdout_pipe[0]);
       ::close(stdout_pipe[1]);
     }
     if (connect_stderr)
     {
       ::close(stderr_pipe[0]);
       ::close(stderr_pipe[1]);
     }
     result = false;
     break;
   case 0:  // in child;
   {
     // for each pipe, close the end of the duplicated pipe that is being used by the parent
     // and connect the child's end of the pipe to the appropriate standard I/O device
     if (connect_stdin)
     {
       ::close(stdin_pipe[1]);
       dup2(stdin_pipe[0],STDIN_FILENO);
     }
     if (connect_stdout)
     {
       ::close(stdout_pipe[0]);
       dup2(stdout_pipe[1],STDOUT_FILENO);
     }
     if (connect_stderr)
     {
       ::close(stderr_pipe[0]);
       dup2(stderr_pipe[1],STDERR_FILENO);
     }
     execve(path.c_str(), argv.argv(), env.envp());
     // will only ever get here if the exec() failed completely - *must* now exit the child process
     // by using errno, the parent has some chance of diagnosing the cause of the problem
     exit(errno);
   }
   break;
   default:  // in parent
   {
     // for each pipe, close the end of the duplicated pipe that is being used by the child
     // and connect the parent's end of the pipe to the class members so that they are visible to the parent() callback
     if (connect_stdin)
     {
       ::close(stdin_pipe[0]);
       child_in = stdin_pipe[1];
       if (fcntl(child_in, F_SETFL, O_NONBLOCK) == -1)
       {
         set_error(errno);
         result = false;
       }
     }
     if (connect_stdout)
     {
       ::close(stdout_pipe[1]);
       child_out = stdout_pipe[0];
       if (fcntl(child_out, F_SETFL, O_NONBLOCK) == -1)
       {
         set_error(errno);
         result = false;
       }
     }
     if (connect_stderr)
     {
       ::close(stderr_pipe[1]);
       child_err = stderr_pipe[0];
       if (fcntl(child_err, F_SETFL, O_NONBLOCK) == -1)
       {
         set_error(errno);
         result = false;
       }
     }
   }
   break;
   }
   return result;
 }
bool async_subprocess::spawn (const std::string & command_line, bool connect_stdin = false, bool connect_stdout = false, bool connect_stderr = false)
Definition at line 1694 of file subprocesses.cpp.
References arg_vector::argv0(), path_lookup(), arg_vector::size(), and spawn().
 {
   arg_vector arguments = command_line;
   if (arguments.size() == 0) return false;
   std::string path = path_lookup(arguments.argv0());
   if (path.empty()) return false;
   return spawn(path, arguments, connect_stdin, connect_stdout, connect_stderr);
 }
bool async_subprocess::tick (void)
Definition at line 1735 of file subprocesses.cpp.
References callback(), kill(), pid, set_error(), and status.
 {
   bool result = true;
   if (!callback())
     kill();
   int wait_status = 0;
   int wait_ret_val = waitpid(pid, &wait_status, WNOHANG);
   if (wait_ret_val == -1 && errno != EINTR)
   {
     set_error(errno);
     result = false;
   }
   else if (wait_ret_val != 0)
   {
     // the only states that indicate a terminated child are WIFSIGNALLED and WIFEXITED
     if (WIFSIGNALED(wait_status))
     {
       // set_error(errno);
       status = WTERMSIG(wait_status);
       result = false;
     }
     else if (WIFEXITED(wait_status))
     {
       // child has exited
       status = WEXITSTATUS(wait_status);
       result = false;
     }
   }
   if (!result)
     pid = -1;
   return result;
 }
int async_subprocess::write_stdin (std::string & buffer)
Definition at line 1825 of file subprocesses.cpp.
References itext::bytes(), child_in, close_stdin(), and set_error().
 {
   if (child_in == -1) return -1;
   // relies on the pipe being non-blocking
   // This does block under Windows
   int bytes = write(child_in, buffer.c_str(), buffer.size());
   if (bytes == -1 && errno == EAGAIN)
   {
     // not ready
     return 0;
   }
   if (bytes == -1)
   {
     // error on write - close the pipe and give up
     set_error(errno);
     close_stdin();
     return -1;
   }
   // successful write
   // now discard that part of the buffer that was written
   if (bytes > 0)
     buffer.erase(0, bytes);
   return bytes;
 }
Member Data Documentation
int async_subprocess::child_err private
Definition at line 232 of file subprocesses.hpp.
Referenced by async_subprocess(), close_stderr(), read_stderr(), and spawn().
int async_subprocess::child_in private
Definition at line 230 of file subprocesses.hpp.
Referenced by async_subprocess(), close_stdin(), spawn(), and write_stdin().
int async_subprocess::child_out private
Definition at line 231 of file subprocesses.hpp.
Referenced by async_subprocess(), close_stdout(), read_stdout(), and spawn().
env_vector async_subprocess::env private
Definition at line 233 of file subprocesses.hpp.
int async_subprocess::err private
Definition at line 234 of file subprocesses.hpp.
Referenced by async_subprocess(), error(), error_number(), error_text(), and set_error().
int async_subprocess::pid private
Definition at line 229 of file subprocesses.hpp.
Referenced by async_subprocess(), kill(), spawn(), tick(), and ~async_subprocess().
int async_subprocess::status private
Definition at line 235 of file subprocesses.hpp.
Referenced by async_subprocess(), exit_status(), and tick().
The documentation for this class was generated from the following files:
include/stlplus/subprocesses.hpp
include/stlplus/subprocesses.cpp