Visible: NRVec< T > Class Template Reference
NRVec< T > Class Template Reference
#include <include/analysis/nrutil_nr.h>
Public Member Functions
NRVec ()
NRVec (int n)
NRVec (const T &a, int n)
NRVec (const T *a, int n)
NRVec (const NRVec &rhs)
NRVec & operator= (const NRVec &rhs)
NRVec & operator= (const T &a)
T & operator[] (const int i)
const T & operator[] (const int i) const
int size () const
~NRVec ()
Private Attributes
int nn
T * v
Detailed Description
template<class T>
class NRVec< T >
Definition at line 61 of file nrutil_nr.h.
Constructor & Destructor Documentation
template<class T > NRVec< T >::NRVec ()
Definition at line 80 of file nrutil_nr.h.
template<class T > NRVec< T >::NRVec (int n) explicit
Definition at line 83 of file nrutil_nr.h.
template<class T> NRVec< T >::NRVec (const T & a, int n)
Definition at line 86 of file nrutil_nr.h.
References NRVec< T >::v.
template<class T> NRVec< T >::NRVec (const T * a, int n)
Definition at line 93 of file nrutil_nr.h.
References NRVec< T >::v.
template<class T> NRVec< T >::NRVec (const NRVec< T > & rhs)
Definition at line 100 of file nrutil_nr.h.
References NRVec< T >::nn, and NRVec< T >::v.
template<class T > NRVec< T >::~NRVec ()
Definition at line 169 of file nrutil_nr.h.
Member Function Documentation
template<class T > NRVec< T > & NRVec< T >::operator= (const NRVec< T > & rhs)
Definition at line 124 of file nrutil_nr.h.
References NRVec< T >::nn.
template<class T> NRVec< T > & NRVec< T >::operator= (const T & a)
Definition at line 143 of file nrutil_nr.h.
template<class T > T & NRVec< T >::operator[] (const int i) inline
Definition at line 151 of file nrutil_nr.h.
template<class T > const T & NRVec< T >::operator[] (const int i) const inline
Definition at line 157 of file nrutil_nr.h.
template<class T > int NRVec< T >::size () const inline
Definition at line 163 of file nrutil_nr.h.
Referenced by NR::avevar(), NR::fleg(), NR::spread(), NR::svdfit(), and NR::svdvar().
Member Data Documentation
template<class T> int NRVec< T >::nn private
Definition at line 63 of file nrutil_nr.h.
Referenced by NRVec< T >::NRVec(), and NRVec< T >::operator=().
template<class T> T* NRVec< T >::v private
Definition at line 64 of file nrutil_nr.h.
Referenced by NRVec< T >::NRVec().
The documentation for this class was generated from the following file:
include/analysis/nrutil_nr.h