Visible: iiotext Class Reference
iiotext Class Reference
#include <include/stlplus/iostreamio.hpp>
Public Member Functions
iiotext (std::istream &)
void open (std::istream &)
std::istream & get_stream (void)
const std::istream & get_stream (void) const
Public Member Functions inherited from itext
itext (void)
itext (ibuff *)
virtual ~itext (void)
bool initialised (void) const
void open (ibuff *)
void close (void)
itext (const itext &)
itext & operator= (const itext &)
bool error (void) const
int error_number (void) const
std::string error_string (void) const
void set_error (int error)
void clear_error (void)
void set_newline_mode (newline_t newline=convert_mode)
void set_convert_mode (void)
void set_binary_mode (void)
newline_t newline_mode (void) const
bool is_convert_mode (void)
bool is_binary_mode (void)
bool eof (void)
bool eoln (void)
int peek (void)
int get (void)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
bool good (void)
operator bool (void)
bool operator! (void)
itext & operator>> (char &)
itext & operator>> (signed char &)
itext & operator>> (unsigned char &)
itext & operator>> (std::string &)
bool getline (std::string &line)
itext & operator>> (std::vector< std::string > &)
itext & operator>> (bool &)
itext & operator>> (short &)
itext & operator>> (unsigned short &)
itext & operator>> (int &)
itext & operator>> (unsigned int &)
itext & operator>> (long &)
itext & operator>> (unsigned long &)
itext & operator>> (float &)
itext & operator>> (double &)
itext & operator>> (void *&)
itext & operator>> (manipulator_function)
itext & operator>> (otext &)
Additional Inherited Members
Public Types inherited from itext
enum newline_t { binary_mode, convert_mode }
typedef void(* manipulator_function)(itext &)
Protected Attributes inherited from itext
ibuff * m_buffer
Detailed Description
Definition at line 34 of file iostreamio.hpp.
Constructor & Destructor Documentation
iiotext::iiotext (std::istream & str)
Definition at line 76 of file iostreamio.cpp.
References open().
 {
   open(str);
 }
Member Function Documentation
std::istream & iiotext::get_stream (void)
Definition at line 86 of file iostreamio.cpp.
References DEBUG_ASSERT, itext::m_buffer, and iiobuff::m_stream.
 {
   iiobuff* buf = dynamic_cast<iiobuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf->m_stream;
 }
const std::istream & iiotext::get_stream (void) const
Definition at line 93 of file iostreamio.cpp.
References DEBUG_ASSERT, itext::m_buffer, and iiobuff::m_stream.
 {
   const iiobuff* buf = dynamic_cast<const iiobuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf->m_stream;
 }
void iiotext::open (std::istream & str)
Definition at line 81 of file iostreamio.cpp.
References itext::open().
Referenced by iiotext().
 {
   itext::open(new iiobuff(str));
 }
The documentation for this class was generated from the following files:
include/stlplus/iostreamio.hpp
include/stlplus/iostreamio.cpp