Visible: rcPolygonGroupRef Class Reference
rcPolygonGroupRef Class Reference
#include <include/visual/rc_polygongroup.h>
Public Member Functions
rcPolygonGroupRef ()
default constructor takes no arguments
rcPolygonGroupRef (rcSharedPolygonGroupPtr ptr)
Attach to an existing buffer.
rcPolygonGroupRef (const rcPolygonGroupRef &other)
copy / assignment takes one arguments
const rcPolygonGroupRef & operator= (const rcPolygonGroupRef &rhs)
copy / assignment takes one arguments
const rcSharedPolygonGroupPtr & group () const
rcSharedPolygonGroupPtr & group ()
uint32 isBound () const
const vector< rcPolygon > & polys ()
const uint32 size () const
void push_back (const rcPolygon &p)
const rcPolygon & operator[] (int n)
Protected Attributes
rcSharedPolygonGroupPtr mGroup
Friends
bool operator== (const rcPolygonGroupRef &a, const rcPolygonGroupRef &b)
bool operator!= (const rcPolygonGroupRef &a, const rcPolygonGroupRef &b)
Detailed Description
Definition at line 47 of file rc_polygongroup.h.
Constructor & Destructor Documentation
rcPolygonGroupRef::rcPolygonGroupRef () inline
default constructor takes no arguments
Definition at line 54 of file rc_polygongroup.h.
 : mGroup( new rcPolygonGroup () ) {}
rcPolygonGroupRef::rcPolygonGroupRef (rcSharedPolygonGroupPtr ptr) inline
Attach to an existing buffer.
Parameters
ptr is a group pointer (ref counted)
Definition at line 60 of file rc_polygongroup.h.
 : mGroup (ptr) {}
rcPolygonGroupRef::rcPolygonGroupRef (const rcPolygonGroupRef & other) inline
copy / assignment takes one arguments
Parameters
other Copy and assignment constructors increment the refcount
Definition at line 67 of file rc_polygongroup.h.
                                                       :
mGroup(other.group ()) {}
Member Function Documentation
const rcSharedPolygonGroupPtr& rcPolygonGroupRef::group () const inline
Definition at line 83 of file rc_polygongroup.h.
References mGroup.
Referenced by operator=().
 { return mGroup; }
rcSharedPolygonGroupPtr& rcPolygonGroupRef::group () inline
Definition at line 84 of file rc_polygongroup.h.
References mGroup.
 { return mGroup; }
uint32 rcPolygonGroupRef::isBound () const inline
Definition at line 87 of file rc_polygongroup.h.
References mGroup.
Referenced by polys().
 { return mGroup != 0; }
const rcPolygonGroupRef& rcPolygonGroupRef::operator= (const rcPolygonGroupRef & rhs) inline
copy / assignment takes one arguments
Parameters
rhs Copy and assignment constructors increment the refcount
Definition at line 75 of file rc_polygongroup.h.
References group(), and mGroup.
   {
     if (this == &rhs) return *this;
     mGroup = rhs.group();
     return *this;
   }
const rcPolygon& rcPolygonGroupRef::operator[] (int n) inline
Definition at line 91 of file rc_polygongroup.h.
References mGroup.
 { return const_cast<vector<rcPolygon>&> (mGroup->polys()) [n]; }
const vector<rcPolygon>& rcPolygonGroupRef::polys () inline
Definition at line 88 of file rc_polygongroup.h.
References isBound(), mGroup, and rmAssert.
Referenced by rcImageCanvasGL::drawCurrentFocus(), rcModelDomain::dumpPolys(), rcImageCanvasGL::mouseReleaseEvent(), rcEngineImpl::muscleTracker(), operator==(), and rfPolygonGroupToGraphicsCollection().
 { rmAssert (isBound ()); return mGroup->polys (); }
void rcPolygonGroupRef::push_back (const rcPolygon & p) inline
Definition at line 90 of file rc_polygongroup.h.
References mGroup.
Referenced by rcEngineImpl::notifyEngineOfPolys().
 { mGroup->polys().push_back (p); }
const uint32 rcPolygonGroupRef::size (void) const inline
Definition at line 89 of file rc_polygongroup.h.
References mGroup.
Referenced by rcImageCanvasGL::drawCurrentFocus(), rcImageCanvasGL::mouseReleaseEvent(), rcEngineImpl::muscleTracker(), rcEngineImpl::notifyEngineOfPolys(), operator==(), rcModelDomain::polysSize(), and rfPolygonGroupToGraphicsCollection().
 { return mGroup->size ();}
Friends And Related Function Documentation
bool operator!= (const rcPolygonGroupRef & a, const rcPolygonGroupRef & b) friend
Definition at line 112 of file rc_polygongroup.h.
 {
   return !operator==(a, b);
 }
bool operator== (const rcPolygonGroupRef & a, const rcPolygonGroupRef & b) friend
Member Data Documentation
rcSharedPolygonGroupPtr rcPolygonGroupRef::mGroup protected
Definition at line 98 of file rc_polygongroup.h.
Referenced by group(), isBound(), operator=(), operator[](), polys(), push_back(), and size().
The documentation for this class was generated from the following file:
include/visual/rc_polygongroup.h