Visible: rcWriter Class Reference
rcWriter Class Reference abstract
#include <include/visiCore/rc_engine.h>
Public Member Functions
virtual ~rcWriter ()
virtual rcWriterType getWriterType (void)=0
virtual const char * getTag (void)=0
virtual const char * getName (void)=0
virtual const char * getDescription (void)=0
virtual rcTimestamp getTrackStart (void)=0
virtual void setTrackStart (const rcTimestamp &time)=0
virtual void flush (void)=0
virtual void setSemantics (const rcTrackSemantics &s)=0
virtual void setExportable (bool e)=0
virtual void setDescription (const char *text)=0
virtual void setName (const char *text)=0
virtual void setAnalysisRect (const rcRect &f)=0
Detailed Description
Definition at line 340 of file rc_engine.h.
Constructor & Destructor Documentation
virtual rcWriter::~rcWriter () inline virtual
Definition at line 344 of file rc_engine.h.
 { };
Member Function Documentation
virtual void rcWriter::flush (void) pure virtual
Implemented in rcTrackImpl, rcPositionTrackImpl, rcScalarTrackImpl, rcGraphicsTrackImpl, and rcVideoTrackImpl.
Referenced by rcIdMapper::flushWriters().
virtual const char* rcWriter::getDescription (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::entropyTrackerWindow(), and rcEngineFocusData::rcEngineFocusData().
virtual const char* rcWriter::getName (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::entropyTracker(), rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::modelTracker(), and rcEngineFocusData::rcEngineFocusData().
virtual const char* rcWriter::getTag (void) pure virtual
Implemented in rcTrackImpl.
virtual rcTimestamp rcWriter::getTrackStart (void) pure virtual
Implemented in rcTrackImpl.
virtual rcWriterType rcWriter::getWriterType (void) pure virtual
Implemented in rcTrackImpl.
Referenced by rcNativeImporter::parseValue().
virtual void rcWriter::setAnalysisRect (const rcRect & f) pure virtual
Implemented in rcTrackImpl.
virtual void rcWriter::setDescription (const char * text) pure virtual
Implemented in rcTrackImpl.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::entropyTrackerWindow(), rcEngineFocusData::rcEngineFocusData(), rcWriterManager::renameEntropyTrack(), and rcWriterManager::renameTrack().
virtual void rcWriter::setExportable (bool e) pure virtual
Implemented in rcTrackImpl.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::createGraphicsWriters(), rcNativeImporter::parseTrack(), rcCellWriterGroup::rcCellWriterGroup(), and rcEngineImpl::setSettingValue().
virtual void rcWriter::setName (const char * text) pure virtual
Implemented in rcTrackImpl.
Referenced by rcEngineImpl::createCameraPreviewWriters(), rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::modelTracker(), rcEngineFocusData::rcEngineFocusData(), rcWriterManager::renameEntropyTrack(), and rcWriterManager::renameTrack().
virtual void rcWriter::setSemantics (const rcTrackSemantics & s) pure virtual
Implemented in rcTrackImpl.
virtual void rcWriter::setTrackStart (const rcTimestamp & time) pure virtual
Implemented in rcTrackImpl.
Referenced by rcNativeImporter::parseTrack(), and rcCellWriterGroup::rcCellWriterGroup().
The documentation for this class was generated from the following file:
include/visiCore/rc_engine.h