Visible: rcPositionWriter Class Reference
rcPositionWriter Class Reference abstract
#include <include/visiCore/rc_engine.h>
Public Member Functions
virtual ~rcPositionWriter ()
virtual void setExpectedMinValue (const rcFPair &minValue)=0
virtual void setExpectedMaxValue (const rcFPair &maxValue)=0
virtual void writeValue (const rcTimestamp &timestamp, const rcRect &focus, const rcFPair &position)=0
virtual void flush (void)=0
virtual rcWriter * down_cast ()=0
Detailed Description
Definition at line 431 of file rc_engine.h.
Constructor & Destructor Documentation
virtual rcPositionWriter::~rcPositionWriter () inline virtual
Definition at line 435 of file rc_engine.h.
 { };
Member Function Documentation
virtual rcWriter* rcPositionWriter::down_cast () pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcCellWriterGroup::rcCellWriterGroup().
virtual void rcPositionWriter::flush (void) pure virtual
Implemented in rcPositionTrackImpl.
virtual void rcPositionWriter::setExpectedMaxValue (const rcFPair & maxValue) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcWriterManager::createPositionWriter(), and rcNativeImporter::parseTrack().
virtual void rcPositionWriter::setExpectedMinValue (const rcFPair & minValue) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcWriterManager::createPositionWriter(), and rcNativeImporter::parseTrack().
virtual void rcPositionWriter::writeValue (const rcTimestamp & timestamp, const rcRect & focus, const rcFPair & position) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcNativeImporter::parseValue(), and rcCellWriterGroup::writeValues().
The documentation for this class was generated from the following file:
include/visiCore/rc_engine.h