Visible: rcMovieGrabber Class Reference
rcMovieGrabber Class Reference
#include <include/visual/rc_moviegrabber.h>
Public Member Functions
rcMovieGrabber (const std::string fileName, rcCarbonLock *lock, double frameInterval=0.0, int32 startAfterFrame=-1, int32 frames=-1)
virtual ~rcMovieGrabber ()
virtual bool start ()
virtual bool stop ()
virtual int32 frameCount ()
virtual int32 cacheSize ()
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)
virtual const std::string getInputSourceName ()
Public Member Functions inherited from rcFileGrabber
rcFileGrabber (rcCarbonLock *lock)
virtual ~rcFileGrabber ()
virtual rcFrameGrabberError getLastError () const
virtual bool isValid () const
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
Private Member Functions
void getPixelInfoFromImageDesc (ImageDescriptionHandle anImageDesc)
OSErr getNextVideoSample (rcWindow &image, Media media, TimeValue fromTimePoint, bool reduceGrayTo8bit)
Private Attributes
const std::string mFileName
FSSpec mFileSpec
GraphicsImportComponent mImporter
int32 mFrameCount
short mRefnum
Movie mMovie
Media mMedia
int32 mMovieStartFrame
int32 mClipFrames
TimeValue mTimeScale
TimeValue mCurrentTime
int32 mCurrentIndex
bool mGotFirstFrame
double mFrameInterval
rcTimestamp mCurrentTimeStamp
std::vector< TimeValue > mFrameTimes
rcPixel m_pd
uint32 m_pf
CTabHandle m_ctb
bool m_isGray
bool m_isWhiteReversed
Rect m_qt_movie_rect
int16 m_width
int16 m_height
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Protected Member Functions inherited from rcFileGrabber
void setLastError (rcFrameGrabberError)
void lock ()
void unlock ()
Detailed Description
Definition at line 27 of file rc_moviegrabber.h.
Constructor & Destructor Documentation
rcMovieGrabber::rcMovieGrabber (const std::string fileName, rcCarbonLock * lock, double frameInterval = 0.0, int32 startAfterFrame = -1, int32 frames = -1)
Definition at line 49 of file rc_moviegrabber.cpp.
References eFrameErrorFileInit, eFrameErrorQuicktimeInit, rcFileGrabber::lock(), mFileName, mFileSpec, rfMakeFSSpecFromPosixPath(), rcFileGrabber::setLastError(), rcFileGrabber::unlock(), and ValidFSSpec().
                                                                                       :
     rcFileGrabber( cLock ),
     mFileName( fileName ),
     mFrameCount(-1),
     mRefnum( 0 ), mMovie( 0 ), mMedia( 0 ), mTimeScale( 0 ),
     mCurrentTime( kBogusStartingTime ), mCurrentIndex( 0 ), mGotFirstFrame( false ),
     mFrameInterval( frameInterval ), mCurrentTimeStamp( frameInterval ), mMovieStartFrame (startFrame), mClipFrames (frames), m_ctb (NULL)
 {
     lock();
     OSErr err;
     if ( mFileName.empty() )
         setLastError( eFrameErrorFileInit );
     else
     {
         bool isDir = false;
         mFileSpec = rfMakeFSSpecFromPosixPath( mFileName.c_str(), isDir);
         err = ValidFSSpec( &mFileSpec );
         // Cannot access file for some reason
         if ( err != noErr )
             setLastError( eFrameErrorFileInit );
         // Initialize QuickTime
         err = EnterMovies();
         if ( err != noErr ) {
             setLastError( eFrameErrorQuicktimeInit );
         }
     }
     unlock();
}
rcMovieGrabber::~rcMovieGrabber () virtual
Definition at line 85 of file rc_moviegrabber.cpp.
References m_ctb.
 {
     if( m_ctb ) {
         printf( "\n dtor: remove color table.\n" );
         DisposeCTable( m_ctb );
     }
 }
Member Function Documentation
virtual int32 rcMovieGrabber::cacheSize () inline virtual
Implements rcFrameGrabber.
Definition at line 52 of file rc_moviegrabber.h.
 { return 0; }
int32 rcMovieGrabber::frameCount () virtual
Implements rcFileGrabber.
Definition at line 186 of file rc_moviegrabber.cpp.
References mFrameCount.
Referenced by rfCompareMovies(), and rfCountMovieFrames().
 {
     return mFrameCount;
 }
const std::string rcMovieGrabber::getInputSourceName () virtual
Implements rcFrameGrabber.
Definition at line 244 of file rc_moviegrabber.cpp.
References mFileName.
 {
     return mFileName;
 }
rcFrameGrabberStatus rcMovieGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) virtual
Implements rcFileGrabber.
Definition at line 193 of file rc_moviegrabber.cpp.
References eFrameErrorFileRead, eFrameErrorOK, eFrameErrorUnknown, eFrameStatusEOF, eFrameStatusError, eFrameStatusOK, rcWindow::frameBuf(), getNextVideoSample(), rcFileGrabber::lock(), mCurrentIndex, mFrameInterval, mFrameTimes, mMedia, mMovie, NULL, rcFileGrabber::setLastError(), rcFrame::setTimestamp(), TRUE, and rcFileGrabber::unlock().
Referenced by rfCompareMovies().
 {
     lock();
     rcFrameGrabberStatus ret =  eFrameStatusOK;
     setLastError( eFrameErrorUnknown );
     if (mCurrentIndex < mFrameTimes.size())
     {
         ptr = NULL;
         ret = eFrameStatusOK;
         TimeScale  timescale   = GetMovieTimeScale      (mMovie);
         short flags = nextTimeMediaSample;
         flags += nextTimeEdgeOK;
         rcWindow image;
         // Get the frame and convert it from 32 to 8 bit if possible
         OSErr status = getNextVideoSample(image, mMedia, mFrameTimes[mCurrentIndex], TRUE );
         rcTimestamp tp ( ( mFrameInterval > 0.0 ) ? mCurrentIndex *  mFrameInterval
                          : static_cast<double> (mFrameTimes[mCurrentIndex] / 1000.0 * timescale) );
         if ( status == noErr )
         {
             ptr = image.frameBuf();
             image.frameBuf()->setTimestamp(tp);
             ret = eFrameStatusOK;
             setLastError( eFrameErrorOK );
             mCurrentIndex++;
         }
         else
         {
             ret = eFrameStatusError;
             // TODO: analyze OSErr and map it to proper eFrameError
             setLastError( eFrameErrorFileRead );
         }
     }
     else
         ret = eFrameStatusEOF;
     unlock();
     return ret;
 }
OSErr rcMovieGrabber::getNextVideoSample (rcWindow & image, Media media, TimeValue fromTimePoint, bool reduceGrayTo8bit) private
Definition at line 338 of file rc_moviegrabber.cpp.
References rcWindow::depth(), m_ctb, m_height, m_isGray, m_isWhiteReversed, m_pd, m_pf, m_qt_movie_rect, m_width, mMovie, NULL, rcPixel32, rcPixel8, rfFillColorMap(), rfRcWindow32to8(), rfReversePixels8(), rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcFrame::setIsGray().
Referenced by getNextFrame().
 {
     OSErr           anErr = noErr;
     GWorldPtr       gWorld = NULL;
     rcWindow        tmp, tmp2;
     PixMapHandle    pixMap = NULL;
     assert(mMovie != NULL);
     // Create aGWorld for writing the movie in to
     // We will allocate GWorld memory ourselves as a framebuf ===> Dispose will not free this memory
     try
     {
         rcPixel depth = m_pd;
         rcSharedFrameBufPtr buf(new rcFrame (m_width, m_height, depth));
         buf->setIsGray(m_isGray);
         rcWindow rw (buf);
         tmp = rw;
         tmp2 = rw;
         assert (m_pf);
         anErr = QTNewGWorldFromPtr( &gWorld, m_pf, &m_qt_movie_rect, m_ctb, NULL, 0, (char *) (tmp.rowPointer(0)), tmp.rowUpdate ());
         if (noErr != anErr)
         {
             goto Closure; // Should throw an exception ????
         }
         if ( reduceGrayTo8bit && m_isGray && depth > rcPixel8 )
         {
             depth = rcPixel8;
             rcSharedFrameBufPtr buf8(new rcFrame (m_width, m_height, depth));
             buf8->setIsGray(m_isGray);
             // Produce color map
             rfFillColorMap( m_ctb, buf8 );
             rcWindow image8(buf8);
             // Reduce image depth
             rfRcWindow32to8( tmp, image8 );
             tmp2 = image8;
         } else {
             // Produce color map if necessary
             if ( depth < rcPixel32 && !m_isWhiteReversed) {
                 rfFillColorMap( m_ctb, buf );
             }
         }
     }
     catch (...)
     {
         goto Closure;
     }
     //? Draw the next first video sample (frame) to GWorld number.
     SetMovieTimeValue(mMovie, fromTimePoint);
     SetMovieGWorld(mMovie, gWorld, GetGWorldDevice(gWorld));
     // Note that the work in rebuilding the drawing pipeline is not actually done in SetMovieGWorld,
     // but during the next call to MoviesTask.
     // invalidates the movie's display state ==>
     // Movie Toolbox redraws the movie the next time MoviesTask is called
     UpdateMovie (mMovie);
     anErr = GetMoviesError ();
     if (anErr != noErr)
     {
         fprintf (stderr, "Couldn't UpdateMovie() \n");
         return 0;
     }
     //  (= redraw immediately)
     MoviesTask (mMovie, 0L);
     anErr = GetMoviesError ();
     if (anErr != noErr)
     {
         fprintf (stderr, "MoviesTask() didn't succeed \n");
         return 0;
     }
     pixMap = GetGWorldPixMap(gWorld);
     LockPixels(pixMap);
     UnlockPixels(pixMap);
     if ( m_isWhiteReversed && tmp2.depth() == rcPixel8 ) {
         // Color map indicates that pixel value 0 is white
         // Reverse pixels and use default color map
         rfReversePixels8( tmp2 );
     }
     // Copy it to the vector
     image = tmp2;
     //? Closure. Clean up if we have handles.
 Closure:
     if(gWorld != NULL)
         DisposeGWorld(gWorld);
     return anErr;
 }
void rcMovieGrabber::getPixelInfoFromImageDesc (ImageDescriptionHandle anImageDesc) private
Definition at line 258 of file rc_moviegrabber.cpp.
References m_ctb, m_isGray, m_isWhiteReversed, m_pd, m_pf, NULL, rcPixel32, rcPixel8, and rcPixelUnknown.
Referenced by start().
 {
     int16 aPixelDepth = (*anImageDesc)->depth;
     // Get the color table
     CTabHandle m_ctb = NULL;
     GetImageDescriptionCTable (anImageDesc,&m_ctb);
     int16 csize = (*m_ctb)->ctSize;
     m_isGray = false;
     m_isWhiteReversed = false;
     // Check grayness
     if ( csize > 0 ) {
         m_isGray = true;
         // Test each color table entry
         for ( int16 i = 0; i < csize + 1; ++i ) {
             const int r = (*m_ctb)->ctTable[i].rgb.red;
             const int g = (*m_ctb)->ctTable[i].rgb.green;
             const int b = (*m_ctb)->ctTable[i].rgb.blue;
             if ( r != g || g != b ) {
                 m_isGray = false;
                 break;
             }
         }
         if ( m_isGray ) {
             // Test whether index 0 contains white
             m_isWhiteReversed = true;
             for ( int16 i = 1; i < csize + 1; ++i ) {
                 const int prev = (*m_ctb)->ctTable[i-1].rgb.red;
                 const int cur = (*m_ctb)->ctTable[i].rgb.red;
                 if ( prev < cur ) {
                     m_isWhiteReversed = false;
                     break;
                 }
             }
         }
     }
     switch( aPixelDepth ) {
         case 8:
             m_pd = rcPixel8;
             m_pf = k8IndexedPixelFormat;
             break;
         case 16:
             m_pd = rcPixel32;
             m_pf = k32ARGBPixelFormat;
             break;
         case 24:
             m_pd = rcPixel32;
             m_pf = k32ARGBPixelFormat;
             break;
         case 32:
             m_pd = rcPixel32;
             m_pf = k32ARGBPixelFormat;
             break;
         case 40:
             m_pd = rcPixel8;
             m_pf = k8IndexedGrayPixelFormat;
             break;
         default:
             m_pd = rcPixelUnknown;
             m_pf = k32ARGBPixelFormat;
             break;
     }
 #ifdef DEBUG_LOG
     fprintf (stderr, "Pixel depth in movie file is %d ==> %d bytes in depth - %s - %s - %s - color table size %i\n",
              aPixelDepth, m_pd, m_isGray ? "is Gray" : "is not Gray",
              m_isWhiteReversed ? "0 is white" : "0 is black",
              m_pf == k8IndexedPixelFormat ? "k8IndexedPixelFormat" :
              (m_pf == k8IndexedGrayPixelFormat) ? "k8IndexedGrayPixelFormat" :
              (m_pf == k32ARGBPixelFormat) ? "k32ARGBPixelFormat" : "Other",
              csize );
 #endif
 }
bool rcMovieGrabber::start (void) virtual
Implements rcFileGrabber.
Definition at line 95 of file rc_moviegrabber.cpp.
References eFrameErrorOK, eFrameErrorUnsupportedFormat, rcFileGrabber::getLastError(), getPixelInfoFromImageDesc(), getVideoMediaImageDesc(), rcFileGrabber::lock(), m_height, m_qt_movie_rect, m_width, mCurrentTime, mFileSpec, mFrameCount, mFrameTimes, mMedia, mMovie, mRefnum, mTimeScale, NULL, rcFileGrabber::setLastError(), and rcFileGrabber::unlock().
Referenced by rfCompareMovies(), and rfCountMovieFrames().
 {
     lock();
     ClearMoviesStickyError();
     // open a Movie file using the FSSpec and create a Movie from that file.
     OSErr err = OpenMovieFile( &mFileSpec, &mRefnum, fsRdPerm );
     mFrameTimes.clear ();
     if ( err == noErr )
     {
         NewMovieFromFile( &mMovie, mRefnum, NULL, NULL, newMovieActive, NULL );
         mMedia = GetTrackMedia( GetMovieIndTrack ( mMovie, 1 ) );
         // Allocate a handle for sample description
         SampleDescriptionHandle anImageDesc = (SampleDescriptionHandle) NewHandle( sizeof(Handle) );
         // Get the image description for the movie
         err = getVideoMediaImageDesc( mMedia, anImageDesc );
         if  ( err == noErr )
         {
             getPixelInfoFromImageDesc ( (ImageDescriptionHandle) anImageDesc);
             mTimeScale = GetMovieTimeScale(mMovie);
             Rect tmp = {0,0,0,0};
             GetMovieBox(mMovie, &tmp);
             m_width =  tmp.right - tmp.left;
             m_height = tmp.bottom - tmp.top;
             m_qt_movie_rect.right = m_width; m_qt_movie_rect.bottom = m_height;
             m_qt_movie_rect.left = tmp.left; m_qt_movie_rect.top = tmp.top;
             // count the number of video 'frames' in the movie by stepping through all of the
             // video 'interesting times', or in other words, the places where the movie displays
             // a new video sample. The time between these interesting times is not necessarily constant.
             {
                 OSType      whichMediaType = VisualMediaCharacteristic;
                 TimeValue   theTime        = -1;
                 // find out movie start time
                 GetMovieNextInterestingTime (mMovie, short (nextTimeMediaSample + nextTimeEdgeOK),
                                              1, & whichMediaType, TimeValue (0), 0, & theTime, NULL);
                 if (theTime == -1)
                 {
                     fprintf (stderr, "Couldn't inquire first frame time\n");
                     return 0;
                 }
                 mCurrentTime  = theTime;
                 // count all 'interesting times' of the movie
                 while (theTime >= 0)
                 {
                     mFrameTimes.push_back (theTime);
                     GetMovieNextInterestingTime (mMovie, short (nextTimeMediaSample),
                                                  1, & whichMediaType, theTime, 0, & theTime, NULL);
                 }
                 mFrameCount = mFrameTimes.size ();
             }
         }
         else {
             setLastError( eFrameErrorUnsupportedFormat );
         }
         DisposeHandle( (Handle) anImageDesc );
     }
         unlock();
         if ( getLastError() == eFrameErrorOK )
             return true;
         else
             return false;
 }
bool rcMovieGrabber::stop (void) virtual
Implements rcFileGrabber.
Definition at line 169 of file rc_moviegrabber.cpp.
References rcFileGrabber::lock(), mImporter, mMovie, mRefnum, and rcFileGrabber::unlock().
 {
     lock();
     DisposeMovie( mMovie );
     if ( mRefnum )
         CloseMovieFile( mRefnum );
     CloseComponent( mImporter );
     unlock();
     return true;
 }
Member Data Documentation
CTabHandle rcMovieGrabber::m_ctb private
Definition at line 84 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), getPixelInfoFromImageDesc(), and ~rcMovieGrabber().
int16 rcMovieGrabber::m_height private
Definition at line 88 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and start().
bool rcMovieGrabber::m_isGray private
Definition at line 85 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and getPixelInfoFromImageDesc().
bool rcMovieGrabber::m_isWhiteReversed private
Definition at line 86 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and getPixelInfoFromImageDesc().
rcPixel rcMovieGrabber::m_pd private
Definition at line 82 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and getPixelInfoFromImageDesc().
uint32 rcMovieGrabber::m_pf private
Definition at line 83 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and getPixelInfoFromImageDesc().
Rect rcMovieGrabber::m_qt_movie_rect private
Definition at line 87 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and start().
int16 rcMovieGrabber::m_width private
Definition at line 88 of file rc_moviegrabber.h.
Referenced by getNextVideoSample(), and start().
int32 rcMovieGrabber::mClipFrames private
Definition at line 73 of file rc_moviegrabber.h.
int32 rcMovieGrabber::mCurrentIndex private
Definition at line 76 of file rc_moviegrabber.h.
Referenced by getNextFrame().
TimeValue rcMovieGrabber::mCurrentTime private
Definition at line 75 of file rc_moviegrabber.h.
Referenced by start().
rcTimestamp rcMovieGrabber::mCurrentTimeStamp private
Definition at line 79 of file rc_moviegrabber.h.
const std::string rcMovieGrabber::mFileName private
Definition at line 65 of file rc_moviegrabber.h.
Referenced by getInputSourceName(), and rcMovieGrabber().
FSSpec rcMovieGrabber::mFileSpec private
Definition at line 66 of file rc_moviegrabber.h.
Referenced by rcMovieGrabber(), and start().
int32 rcMovieGrabber::mFrameCount private
Definition at line 68 of file rc_moviegrabber.h.
Referenced by frameCount(), and start().
double rcMovieGrabber::mFrameInterval private
Definition at line 78 of file rc_moviegrabber.h.
Referenced by getNextFrame().
std::vector<TimeValue> rcMovieGrabber::mFrameTimes private
Definition at line 80 of file rc_moviegrabber.h.
Referenced by getNextFrame(), and start().
bool rcMovieGrabber::mGotFirstFrame private
Definition at line 77 of file rc_moviegrabber.h.
GraphicsImportComponent rcMovieGrabber::mImporter private
Definition at line 67 of file rc_moviegrabber.h.
Referenced by stop().
Media rcMovieGrabber::mMedia private
Definition at line 71 of file rc_moviegrabber.h.
Referenced by getNextFrame(), and start().
Movie rcMovieGrabber::mMovie private
Definition at line 70 of file rc_moviegrabber.h.
Referenced by getNextFrame(), getNextVideoSample(), start(), and stop().
int32 rcMovieGrabber::mMovieStartFrame private
Definition at line 72 of file rc_moviegrabber.h.
short rcMovieGrabber::mRefnum private
Definition at line 69 of file rc_moviegrabber.h.
Referenced by start(), and stop().
TimeValue rcMovieGrabber::mTimeScale private
Definition at line 74 of file rc_moviegrabber.h.
Referenced by start().
The documentation for this class was generated from the following files:
include/visual/rc_moviegrabber.h
src/visual/code/rc_moviegrabber.cpp