Visible: rcXMLNameMapper Class Reference
rcXMLNameMapper Class Reference
#include <include/visiCore/rc_xmlelem.h>
Public Member Functions
rcXMLNameMapper (const std::string *elemArray, uint32 elemSize, const std::string *attrArray, uint32 attrSize)
const std::string & elementName (rcXMLElementType id) const
rcXMLElementType elementType (const std::string &name) const
const std::string & attributeName (rcXMLAttributeType id) const
rcXMLAttributeType attributeType (const std::string &name) const
Private Attributes
rcXMLElementNameMap mElementMap
rcXMLAttributeNameMap mAttributeMap
const std::string * mElemNames
const std::string * mAttrNames
Detailed Description
Definition at line 42 of file rc_xmlelem.h.
Constructor & Destructor Documentation
rcXMLNameMapper::rcXMLNameMapper (const std::string * elemArray, uint32 elemSize, const std::string * attrArray, uint32 attrSize) inline
Definition at line 44 of file rc_xmlelem.h.
References attributeType(), elementType(), mAttributeMap, mElementMap, and rmAssert.
                                                                                   :
         mElemNames( elemArray ), mAttrNames( attrArray ) {
         rmAssert( elemArray );
         rmAssert( attrArray );
         rmAssert( elemSize > 0 );
         rmAssert( attrSize > 0 );
         // Fill element map
         for ( uint32 i = 0; i < elemSize; ++i ) {
             mElementMap.insert( make_pair( elemArray[i], static_cast<rcXMLElementType>(i) ) );
             // Immediate self-test, it can catch duplicates
             rmAssert( elementType( elemArray[i] ) == static_cast<rcXMLElementType>(i) );
         }
         // Fill attribute map
         for ( uint32 i = 0; i < attrSize; ++i ) {
             mAttributeMap.insert( make_pair( attrArray[i], static_cast<rcXMLAttributeType>(i) ) );
             // Immediate self-test, it can catch duplicates
             rmAssert( attributeType( attrArray[i] ) == static_cast<rcXMLAttributeType>(i) );
         }
         // Each name should be unique, check final size
         rmAssert( mElementMap.size() == elemSize );
         rmAssert( mAttributeMap.size() == attrSize );
     };
Member Function Documentation
const std::string& rcXMLNameMapper::attributeName (rcXMLAttributeType id) const inline
Definition at line 86 of file rc_xmlelem.h.
References mAttrNames.
Referenced by operator<<().
{
         return mAttrNames[id];
     };
rcXMLAttributeType rcXMLNameMapper::attributeType (const std::string & name) const inline
Definition at line 91 of file rc_xmlelem.h.
References eXMLAttributeMax, and mAttributeMap.
Referenced by rcXMLNameMapper(), and rcXMLParser::startElement().
{
         rcXMLAttributeNameMap::const_iterator pos = mAttributeMap.find( name );
         if ( pos != mAttributeMap.end() )
             return pos->second;
         else
             return eXMLAttributeMax;
     };
const std::string& rcXMLNameMapper::elementName (rcXMLElementType id) const inline
Definition at line 72 of file rc_xmlelem.h.
References mElemNames.
Referenced by rcWriterManager::createWriterGroup(), rcNativeImporter::importExperiment(), operator<<(), rcNativeImporter::parseExperimentData(), rcNativeImporter::parseFrame(), rcNativeImporter::parseGroup(), rcNativeImporter::parseSetting(), rcNativeImporter::parseSettingCategory(), rcNativeImporter::parseTrack(), and rcNativeImporter::parseValue().
{
         return mElemNames[id];
     };
rcXMLElementType rcXMLNameMapper::elementType (const std::string & name) const inline
Definition at line 77 of file rc_xmlelem.h.
References eXMLElementMax, and mElementMap.
Referenced by rcXMLParser::endElement(), rcNativeExporter::produceGroups(), rcXMLNameMapper(), and rcXMLParser::startElement().
{
         rcXMLElementNameMap::const_iterator pos = mElementMap.find( name );
         if ( pos != mElementMap.end() )
             return pos->second;
         else
             return eXMLElementMax;
     };
Member Data Documentation
rcXMLAttributeNameMap rcXMLNameMapper::mAttributeMap private
Definition at line 101 of file rc_xmlelem.h.
Referenced by attributeType(), and rcXMLNameMapper().
const std::string* rcXMLNameMapper::mAttrNames private
Definition at line 103 of file rc_xmlelem.h.
Referenced by attributeName().
rcXMLElementNameMap rcXMLNameMapper::mElementMap private
Definition at line 97 of file rc_xmlelem.h.
Referenced by elementType(), and rcXMLNameMapper().
const std::string* rcXMLNameMapper::mElemNames private
Definition at line 102 of file rc_xmlelem.h.
Referenced by elementName().
The documentation for this class was generated from the following file:
include/visiCore/rc_xmlelem.h