Visible: rcIdMapper Class Reference
rcIdMapper Class Reference
#include <include/visiCore/rc_nativeimporter.h>
Public Member Functions
uint32 addGroup (const std::string &idString, rcWriterGroup *inst)
uint32 addTrack (const std::string &idString, rcTrackElement inst)
rcWriterGroup * group (const std::string &idString) const
rcTrackElement track (const std::string &idString) const
void flushWriters ()
Private Attributes
rcGroupIdMap mGroupMap
rcTrackIdMap mTrackMap
Detailed Description
Definition at line 55 of file rc_nativeimporter.h.
Member Function Documentation
uint32 rcIdMapper::addGroup (const std::string & idString, rcWriterGroup * inst) inline
Definition at line 59 of file rc_nativeimporter.h.
References group(), and mGroupMap.
Referenced by rcNativeImporter::parseGroup().
{
         uint32 errors = 0;
         mGroupMap.insert( make_pair( idString, inst ) );
         // Immediate self-test, it can catch duplicates
         if ( group( idString ) != inst )
             ++errors;
         return errors;
     };
uint32 rcIdMapper::addTrack (const std::string & idString, rcTrackElement inst) inline
Definition at line 71 of file rc_nativeimporter.h.
References mTrackMap, rcTrackElement::rect(), rcTrackElement::track(), and track().
Referenced by rcNativeImporter::parseTrack().
{
         uint32 errors = 0;
         mTrackMap.insert( make_pair( idString, inst ) );
         // Immediate self-test, it can catch duplicates
         rcTrackElement e = track( idString );
         if ( e.track() != inst.track() )
             ++errors;
         if ( e.rect() != inst.rect() )
             ++errors;
         return errors;
     };
void rcIdMapper::flushWriters () inline
Definition at line 108 of file rc_nativeimporter.h.
References rcWriter::flush(), rcTrackElement::isValid(), mTrackMap, and rcTrackElement::track().
Referenced by rcNativeImporter::importExperiment().
{
         rcTrackIdMap::iterator pos;
         for ( pos = mTrackMap.begin(); pos !=  mTrackMap.end(); ++pos )
         {
             rcTrackElement e = pos->second;
             if ( e.isValid() ) {
                 e.track()->flush();
             }
         }
     };
rcWriterGroup* rcIdMapper::group (const std::string & idString) const inline
Definition at line 86 of file rc_nativeimporter.h.
References mGroupMap.
Referenced by addGroup(), and rcNativeImporter::parseTrack().
{
         rcGroupIdMap::const_iterator pos;
         pos = mGroupMap.find( idString );
         if ( pos != mGroupMap.end() )
             return pos->second;
         else
             return 0;
     };
rcTrackElement rcIdMapper::track (const std::string & idString) const inline
Definition at line 97 of file rc_nativeimporter.h.
References mTrackMap.
Referenced by addTrack(), and rcNativeImporter::parseValue().
{
         rcTrackIdMap::const_iterator pos;
         pos = mTrackMap.find( idString );
         if ( pos != mTrackMap.end() )
             return pos->second;
         else
             return rcTrackElement();
     };
Member Data Documentation
rcGroupIdMap rcIdMapper::mGroupMap private
Definition at line 118 of file rc_nativeimporter.h.
Referenced by addGroup(), and group().
rcTrackIdMap rcIdMapper::mTrackMap private
Definition at line 122 of file rc_nativeimporter.h.
Referenced by addTrack(), flushWriters(), and track().
The documentation for this class was generated from the following file:
include/visiCore/rc_nativeimporter.h