Visible: rcMovieSaveStatusReader Class Reference
rcMovieSaveStatusReader Class Reference
#include <include/visiCore/rc_saveregs.h>
Public Member Functions
rcMovieSaveStatusReader ()
virtual ~rcMovieSaveStatusReader ()
rcMovieFileErr getStatus () const
rcMovieFileState getState () const
uint32 getDelayLeft () const
uint32 getCaptureTime () const
Protected Attributes
rcAtomicValue< rcMovieFileErr > _saveStatus
rcAtomicValue< rcMovieFileState > _saveState
rcAtomicValue< uint32 > _delayLeft
rcAtomicValue< uint32 > _captureTime
Detailed Description
Definition at line 147 of file rc_saveregs.h.
Constructor & Destructor Documentation
rcMovieSaveStatusReader::rcMovieSaveStatusReader () inline
Definition at line 150 of file rc_saveregs.h.
                             : _saveStatus(eMovieFileErr_NoErr),
     _saveState(eMovieFileState_Uninitialized), _delayLeft(0), _captureTime(0)
   { }
virtual rcMovieSaveStatusReader::~rcMovieSaveStatusReader () inline virtual
Definition at line 154 of file rc_saveregs.h.
   { }
Member Function Documentation
uint32 rcMovieSaveStatusReader::getCaptureTime () const inline
Definition at line 166 of file rc_saveregs.h.
References _captureTime, and rcAtomicValue< T >::getValue().
Referenced by rcEngineMovieCapture::run().
   { uint32 x; return _captureTime.getValue(x); }
uint32 rcMovieSaveStatusReader::getDelayLeft () const inline
Definition at line 163 of file rc_saveregs.h.
References _delayLeft, and rcAtomicValue< T >::getValue().
Referenced by rcEngineMovieSaver::delayHdlr(), and rcEngineMovieCapture::delayLeft().
   { uint32 x; return _delayLeft.getValue(x); }
rcMovieFileState rcMovieSaveStatusReader::getState (void) const inline
Definition at line 160 of file rc_saveregs.h.
References _saveState, and rcAtomicValue< T >::getValue().
Referenced by rcEngineMovieCapture::closeSaveFile(), rcEngineMovieCapture::killSaveThread(), rcEngineMovieSaver::reset(), rcEngineMovieSaver::run(), rcEngineMovieCapture::run(), rcEngineMovieCapture::saveComplete(), rcEngineMovieCapture::saveReset(), and rcEngineMovieCapture::saveState().
   { rcMovieFileState x; return _saveState.getValue(x); }
rcMovieFileErr rcMovieSaveStatusReader::getStatus () const inline
Definition at line 157 of file rc_saveregs.h.
References _saveStatus, and rcAtomicValue< T >::getValue().
Referenced by rcEngineMovieCapture::closeSaveFile(), rcEngineMovieSaver::errorHdlr(), and rcEngineMovieCapture::saveComplete().
   { rcMovieFileErr x; return _saveStatus.getValue(x); }
Member Data Documentation
rcAtomicValue<uint32> rcMovieSaveStatusReader::_captureTime protected
Definition at line 173 of file rc_saveregs.h.
Referenced by rcMovieSaveStatus::captureTime(), and getCaptureTime().
rcAtomicValue<uint32> rcMovieSaveStatusReader::_delayLeft protected
Definition at line 172 of file rc_saveregs.h.
Referenced by rcMovieSaveStatus::delayLeft(), and getDelayLeft().
rcAtomicValue<rcMovieFileState> rcMovieSaveStatusReader::_saveState protected
Definition at line 171 of file rc_saveregs.h.
Referenced by getState(), and rcMovieSaveStatus::state().
rcAtomicValue<rcMovieFileErr> rcMovieSaveStatusReader::_saveStatus protected
Definition at line 170 of file rc_saveregs.h.
Referenced by getStatus(), and rcMovieSaveStatus::status().
The documentation for this class was generated from the following file:
include/visiCore/rc_saveregs.h