Visible: TCP_socket Class Reference
TCP_socket Class Reference
Public Member Functions
TCP_socket (int socket=-1)
~TCP_socket (void)
TCP_socket (const TCP_socket &socket)
TCP_socket & operator= (const TCP_socket &socket)
bool set (int socket=-1)
bool initialise (void)
int socket (void) const
void set_error (int error)
int error (void) const
std::string message (void) const
bool initialised (void) const
bool send_ready (unsigned wait)
bool send (std::string &data)
bool receive_ready (unsigned wait)
bool receive (std::string &data)
bool close (void)
Private Attributes
int m_socket
int m_error
std::string m_message
Detailed Description
Definition at line 133 of file tcp.cpp.
Constructor & Destructor Documentation
TCP_socket::TCP_socket (int socket = -1) inline
Definition at line 142 of file tcp.cpp.
References m_socket, set_error(), socket(), and sockets_init().
                                              : m_socket(INVALID_SOCKET), m_error(0)
     {
       set_error(sockets_init());
       m_socket = socket;
     }
TCP_socket::~TCP_socket (void) inline
Definition at line 148 of file tcp.cpp.
References close(), set_error(), and sockets_close().
     {
       close();
       set_error(sockets_close());
     }
TCP_socket::TCP_socket (const TCP_socket & socket) inline
Definition at line 154 of file tcp.cpp.
References set_error(), socket(), and sockets_init().
                                        : m_socket(INVALID_SOCKET), m_error(0)
     {
       set_error(sockets_init());
       *this = socket;
     }
Member Function Documentation
bool TCP_socket::close (void) inline
Definition at line 331 of file tcp.cpp.
References CLOSE, ERRNO, initialised(), INVALID_SOCKET, m_socket, set_error(), and SOCKET_ERROR.
Referenced by TCP_connection_data::close(), TCP_server_data::close(), TCP_client_data::close(), initialise(), receive(), set(), and ~TCP_socket().
     {
       bool result = true;
       if (initialised())
       {
         if (shutdown(m_socket,SHUT_RDWR) == SOCKET_ERROR)
         {
           set_error(ERRNO);
           result = false;
         }
         if (CLOSE(m_socket) == SOCKET_ERROR)
         {
           set_error(ERRNO);
           result = false;
         }
       }
       m_socket = INVALID_SOCKET;
       return result;
     }
int TCP_socket::error (void) const inline
Definition at line 212 of file tcp.cpp.
References m_error.
Referenced by TCP_connection_data::error(), TCP_server_data::error(), TCP_client_data::error(), and set_error().
     {
       return m_error;
     }
bool TCP_socket::initialise (void) inline
Definition at line 177 of file tcp.cpp.
References close(), ERRNO, INVALID_SOCKET, IOCTL, m_socket, set_error(), socket(), and SOCKET_ERROR.
Referenced by TCP_server_data::initialise(), and TCP_client_data::initialise().
     {
       close();
       // create an anonymous socket
       m_socket = ::socket(AF_INET, SOCK_STREAM, 0);
       if (m_socket == INVALID_SOCKET)
       {
         set_error(ERRNO);
         close();
         return false;
       }
       // set the socket into non-blocking mode
       unsigned long nonblocking = 1;
       if (IOCTL(m_socket, FIONBIO, &nonblocking) == SOCKET_ERROR)
       {
         set_error(ERRNO);
         return false;
       }
       return true;
     }
bool TCP_socket::initialised (void) const inline
Definition at line 222 of file tcp.cpp.
References INVALID_SOCKET, and m_socket.
Referenced by close(), TCP_connection_data::initialised(), TCP_server_data::initialised(), TCP_client_data::initialised(), receive(), receive_ready(), send(), and send_ready().
     {
       return m_socket != INVALID_SOCKET;
     }
std::string TCP_socket::message (void) const inline
Definition at line 217 of file tcp.cpp.
References m_message.
Referenced by TCP_connection_data::message(), TCP_server_data::message(), and TCP_client_data::message().
     {
       return m_message;
     }
TCP_socket& TCP_socket::operator= (const TCP_socket & socket) inline
Definition at line 160 of file tcp.cpp.
References DEBUG_ASSERT, INVALID_SOCKET, m_error, m_message, and m_socket.
     {
       DEBUG_ASSERT(m_socket == INVALID_SOCKET);
       DEBUG_ASSERT(socket.m_socket == INVALID_SOCKET);
       m_socket = socket.m_socket;
       m_error = socket.m_error;
       m_message = socket.m_message;
       return *this;
     }
bool TCP_socket::receive (std::string & data) inline
Definition at line 294 of file tcp.cpp.
References close(), ERRNO, initialised(), IOCTL, m_socket, receive_ready(), set_error(), and SOCKET_ERROR.
Referenced by TCP_connection_data::receive(), and TCP_client_data::receive().
     {
       if (!initialised()) return false;
       if (!receive_ready(0)) return true;
       bool result = true;
       // determine how much data is available to read
       unsigned long bytes = 0;
       if (IOCTL(m_socket, FIONREAD, &bytes) == SOCKET_ERROR)
       {
         set_error(ERRNO);
         result = false;
       }
       else
       {
         // get the data up to the amount claimed to be present - this is non-blocking
         char* buffer = new char[bytes+1];
         int read = recv(m_socket, buffer, bytes, 0);
         if (read == SOCKET_ERROR)
         {
           set_error(ERRNO);
           close();
           result = false;
         }
         else if (read == 0)
         {
           close();
         }
         else
         {
           // this is binary data so copy the bytes including nulls
           data.append(buffer,read);
         }
         delete[] buffer;
       }
       return result;
     }
bool TCP_socket::receive_ready (unsigned wait) inline
Definition at line 268 of file tcp.cpp.
References ERRNO, initialised(), m_socket, set_error(), and SOCKET_ERROR.
Referenced by TCP_server_data::connection_ready(), receive(), TCP_connection_data::receive_ready(), and TCP_client_data::receive_ready().
     {
       if (!initialised()) return false;
       // determines whether the socket is ready to receive
       fd_set read_set;
       FD_ZERO(&read_set);
       FD_SET(m_socket,&read_set);
       timeval timeout;
       timeout.tv_sec = wait/1000000;
       timeout.tv_usec = wait%1000000;
       int select_result = select(m_socket+1, &read_set, 0, 0, &timeout);
       switch(select_result)
       {
       case SOCKET_ERROR:
         // select failed with an error - trap the error
         set_error(ERRNO);
         return false;
       case 0:
         // timeout exceeded without a connection appearing
         return false;
       default:
         // at least one connection is pending
         return true;
       }
     }
bool TCP_socket::send (std::string & data) inline
Definition at line 252 of file tcp.cpp.
References ERRNO, initialised(), m_socket, send_ready(), set_error(), and SOCKET_ERROR.
Referenced by TCP_connection_data::send(), and TCP_client_data::send().
     {
       if (!initialised()) return false;
       if (!send_ready(0)) return true;
       // send the data - this will never block but may not send all the data
       int bytes = ::send(m_socket, data.c_str(), data.size(), 0);
       if (bytes == SOCKET_ERROR)
       {
         set_error(ERRNO);
         return false;
       }
       // remove the sent bytes from the data buffer so that the buffer represents the data still to be sent
       data.erase(0,bytes);
       return true;
     }
bool TCP_socket::send_ready (unsigned wait) inline
Definition at line 227 of file tcp.cpp.
References ERRNO, initialised(), m_socket, set_error(), and SOCKET_ERROR.
Referenced by TCP_client_data::initialise(), send(), TCP_connection_data::send_ready(), and TCP_client_data::send_ready().
     {
       if (!initialised()) return false;
       // determines whether the socket is ready to send
       fd_set write_set; FD_ZERO(&write_set);
       FD_SET(m_socket,&write_set);
       timeval timeout;
       timeout.tv_sec = wait/1000000;
       timeout.tv_usec = wait%1000000;
       int select_result = select(m_socket+1, 0, &write_set, 0, &timeout);
       switch(select_result)
       {
       case SOCKET_ERROR:
         // select failed with an error - trap the error
         set_error(ERRNO);
         return false;
       case 0:
         // timeout exceeded without a connection appearing
         return false;
       default:
         // at least one connection is pending
         return true;
       }
     }
bool TCP_socket::set (int socket = -1) inline
Definition at line 170 of file tcp.cpp.
References close(), m_socket, and socket().
Referenced by TCP_connection_data::initialise().
     {
       close();
       m_socket = socket;
       return true;
     }
void TCP_socket::set_error (int error) inline
Definition at line 203 of file tcp.cpp.
References error(), error_string(), m_error, and m_message.
Referenced by close(), initialise(), receive(), receive_ready(), send(), send_ready(), TCP_connection_data::set_error(), TCP_server_data::set_error(), TCP_client_data::set_error(), TCP_socket(), and ~TCP_socket().
     {
       if (m_error == 0 && error != 0)
       {
         m_error = error;
         m_message = error_string(error);
       }
     }
int TCP_socket::socket (void) const inline
Definition at line 198 of file tcp.cpp.
References m_socket.
Referenced by TCP_server_data::connection(), initialise(), TCP_server_data::initialise(), TCP_client_data::initialise(), set(), and TCP_socket().
     {
       return m_socket;
     }
Member Data Documentation
int TCP_socket::m_error private
Definition at line 137 of file tcp.cpp.
Referenced by error(), operator=(), and set_error().
std::string TCP_socket::m_message private
Definition at line 138 of file tcp.cpp.
Referenced by message(), operator=(), and set_error().
int TCP_socket::m_socket private
Definition at line 136 of file tcp.cpp.
Referenced by close(), initialise(), initialised(), operator=(), receive(), receive_ready(), send(), send_ready(), set(), socket(), and TCP_socket().
The documentation for this class was generated from the following file:
include/stlplus/tcp.cpp