Visible: smart_ptr_nocopy< T > Class Template Reference
smart_ptr_nocopy< T > Class Template Reference
#include <include/stlplus/smart_ptr.hpp>
Public Types
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Member Functions
smart_ptr_nocopy (void)
smart_ptr_nocopy (const smart_ptr_nocopy< T > &r)
smart_ptr_nocopy< T > & operator= (const smart_ptr_nocopy< T > &)
smart_ptr_nocopy (T *data)
smart_ptr_nocopy< T > & operator= (T *data)
~smart_ptr_nocopy (void)
operator bool (void) const
bool operator! (void) const
bool present (void) const
bool null (void) const
T & operator* (void) throw (null_dereference)
const T & operator* (void) const throw (null_dereference)
T * operator-> (void) throw (null_dereference)
const T * operator-> (void) const throw (null_dereference)
T & value (void) throw (null_dereference)
const T & value (void) const throw (null_dereference)
void set (T *data=0)
T * pointer (void)
const T * pointer (void) const
bool aliases (const smart_ptr_nocopy< T > &) const
unsigned alias_count (void) const
void clear (void)
void clear_unique (void)
Protected Attributes
smart_ptr_holder< T > * m_holder
Detailed Description
template<typename T>
class smart_ptr_nocopy< T >
Definition at line 804 of file smart_ptr.hpp.
Member Typedef Documentation
template<typename T> typedef const T& smart_ptr_nocopy< T >::const_reference
Definition at line 812 of file smart_ptr.hpp.
template<typename T> typedef T& smart_ptr_nocopy< T >::reference
Definition at line 811 of file smart_ptr.hpp.
template<typename T> typedef T smart_ptr_nocopy< T >::value_type
Definition at line 810 of file smart_ptr.hpp.
Constructor & Destructor Documentation
template<typename T> smart_ptr_nocopy< T >::smart_ptr_nocopy (void)
template<typename T> smart_ptr_nocopy< T >::smart_ptr_nocopy (const smart_ptr_nocopy< T > & r)
template<typename T> smart_ptr_nocopy< T >::smart_ptr_nocopy (T * data) explicit
template<typename T> smart_ptr_nocopy< T >::~smart_ptr_nocopy (void)
Member Function Documentation
template<typename T> unsigned smart_ptr_nocopy< T >::alias_count (void) const
template<typename T> bool smart_ptr_nocopy< T >::aliases (const smart_ptr_nocopy< T > &) const
template<typename T> void smart_ptr_nocopy< T >::clear (void)
template<typename T> void smart_ptr_nocopy< T >::clear_unique (void)
template<typename T> bool smart_ptr_nocopy< T >::null (void) const
template<typename T> smart_ptr_nocopy< T >::operator bool (void) const
template<typename T> bool smart_ptr_nocopy< T >::operator! (void) const
template<typename T> T& smart_ptr_nocopy< T >::operator* (void) throw (null_dereference)
template<typename T> const T& smart_ptr_nocopy< T >::operator* (void) const throw (null_dereference)
template<typename T> T* smart_ptr_nocopy< T >::operator-> (void) throw (null_dereference)
template<typename T> const T* smart_ptr_nocopy< T >::operator-> (void) const throw (null_dereference)
template<typename T> smart_ptr_nocopy<T>& smart_ptr_nocopy< T >::operator= (const smart_ptr_nocopy< T > &)
template<typename T> smart_ptr_nocopy<T>& smart_ptr_nocopy< T >::operator= (T * data)
template<typename T> T* smart_ptr_nocopy< T >::pointer (void)
template<typename T> const T* smart_ptr_nocopy< T >::pointer (void) const
template<typename T> bool smart_ptr_nocopy< T >::present (void) const
Referenced by lm_library::exists().
template<typename T> void smart_ptr_nocopy< T >::set (T * data = 0)
Referenced by lm_library::create(), and lm_library::load_type().
template<typename T> T& smart_ptr_nocopy< T >::value (void) throw (null_dereference)
template<typename T> const T& smart_ptr_nocopy< T >::value (void) const throw (null_dereference)
Member Data Documentation
template<typename T> smart_ptr_holder<T>* smart_ptr_nocopy< T >::m_holder protected
Definition at line 890 of file smart_ptr.hpp.
The documentation for this class was generated from the following file:
include/stlplus/smart_ptr.hpp