Visible: rcWithinGroupInv Class Reference
rcWithinGroupInv Class Reference
#include <include/analysis/rc_level.h>
Public Member Functions
rcWithinGroupInv (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail, uint32 offset=0, uint32 cumulativeOffset=0)
rcWithinGroupInv (const vector< uint32 > &histogram, uint32 leftCutoffPels=0, uint32 rightCutoffPels=0)
rcWithinGroupInv (const rcWindow &image, uint32 leftCutoffPels=0, uint32 rightCutoffPels=0)
Public Member Functions inherited from rcSegmentationLevel
virtual ~rcSegmentationLevel ()
rcWindow binaryImage (const rcWindow &src, uint8 toGrayValue)
rcWindow binaryImage (const rcWindow &src, uint8 toGrayValue, uint8 setVal)
virtual rcLevelSets & results ()
Private Member Functions
void compute (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail, uint32 offset, uint32 cumulativeOffset, rcLevelSets &result)
Private Attributes
bool mIsValid
Detailed Description
Definition at line 120 of file rc_level.h.
Constructor & Destructor Documentation
rcWithinGroupInv::rcWithinGroupInv (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail, uint32 offset = 0, uint32 cumulativeOffset = 0)
Definition at line 97 of file rc_seglevel.cpp.
References compute(), mIsValid, and rcSegmentationLevel::results().
                                    : mIsValid (false)
 {
   compute(leftTail, rightTail, offset, cumulativeOffset, results());
   mIsValid = true;
 }
rcWithinGroupInv::rcWithinGroupInv (const vector< uint32 > & histogram, uint32 leftCutoffPels = 0, uint32 rightCutoffPels = 0)
Definition at line 106 of file rc_seglevel.cpp.
References compute(), rcTails::cumulativeOffset(), rcTails::leftTail(), mIsValid, rcTails::offset(), rcSegmentationLevel::results(), and rcTails::rightTail().
                                             : mIsValid (false)
 {
   rcTails tails(histogram, leftCutoffPels, rightCutoffPels);
   compute(tails.leftTail(), tails.rightTail(), tails.offset(),
       tails.cumulativeOffset(), results());
   mIsValid = true;
 }
rcWithinGroupInv::rcWithinGroupInv (const rcWindow & image, uint32 leftCutoffPels = 0, uint32 rightCutoffPels = 0)
Definition at line 116 of file rc_seglevel.cpp.
References compute(), rcHistoStats::histogram(), mIsValid, and rcSegmentationLevel::results().
                                             : mIsValid (false)
 {
   rcHistoStats h (image);
   rcTails tails(h.histogram (), leftCutoffPels, rightCutoffPels);
   compute(tails.leftTail(), tails.rightTail(), tails.offset(),
       tails.cumulativeOffset(), results());
   mIsValid = true;
 }
Member Function Documentation
void rcWithinGroupInv::compute (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail, uint32 offset, uint32 cumulativeOffset, rcLevelSets & result) private
Definition at line 129 of file rc_seglevel.cpp.
References rcHornMoments::first(), rcHornMoments::second(), rcLevelSets::update(), and rcHornMoments::zeroth().
Referenced by rcWithinGroupInv().
 {
   //  Between Group Variance (BGV) is defined as:
   //  BGV = (m0_l/m0) * (m0_r/m0) * (m1_l/m0_l - m1_r/m0_r)^2
   // oops, the above variable names are not quite descriptive
   rcHornMoments moment(leftTail, rightTail);
   double zerothMomentLeft = 0.0;
   double zerothMomentRight = 0.0;
   double firstMomentLeft = 0.0;
   double firstMomentRight = 0.0;
   double max = 0.0;
   double cumulative = 0.0;
   uint32 threshold = 0;
   uint32 i = 0;  // index to the (partial) histogram
    vector<uint32>::const_iterator p = leftTail;
   for(; p < rightTail; p++, i++) {
     if(*p == 0) continue;
     zerothMomentLeft += *p;
     zerothMomentRight = moment.zeroth() - zerothMomentLeft;
     firstMomentLeft += *p * i;
     firstMomentRight = moment.first() - firstMomentLeft;
     double dm = firstMomentRight * zerothMomentLeft -
                 firstMomentLeft * zerothMomentRight;
     double score = dm * dm / (zerothMomentLeft * zerothMomentRight);
     if(score > max) {
       threshold = i;
       cumulative = zerothMomentLeft;
       max = score;
     }
   }
   double denom = moment.second()*moment.zeroth()-moment.first()*moment.first();
   results.update(threshold + offset + 1, max/denom, (int32) cumulative);
 }
Member Data Documentation
bool rcWithinGroupInv::mIsValid private
Definition at line 158 of file rc_level.h.
Referenced by rcWithinGroupInv().
The documentation for this class was generated from the following files:
include/analysis/rc_level.h
src/analysis/code/rc_seglevel.cpp