Visible: rcPositionTrack Class Reference
rcPositionTrack Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Types
enum { ePersistenceVersion = 1 }
Public Member Functions
virtual ~rcPositionTrack ()
virtual rcFPair getExpectedMinimumValue (void)=0
virtual rcFPair getExpectedMaximumValue (void)=0
virtual rcFPair getCurrentMinimumValue (void)=0
virtual rcFPair getCurrentMaximumValue (void)=0
virtual rcPositionSegmentIterator * getDataSegmentIterator (const rcTimestamp &pos)=0
virtual uint32 getSegmentCount (void)=0
Detailed Description
Definition at line 497 of file rc_model.h.
Member Enumeration Documentation
anonymous enum
Enumerator
ePersistenceVersion
Definition at line 500 of file rc_model.h.
 { ePersistenceVersion = 1 };
Constructor & Destructor Documentation
virtual rcPositionTrack::~rcPositionTrack () inline virtual
Definition at line 503 of file rc_model.h.
 { };
Member Function Documentation
virtual rcFPair rcPositionTrack::getCurrentMaximumValue (void) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcPositionTrackRenderInfo::rcPositionTrackRenderInfo().
virtual rcFPair rcPositionTrack::getCurrentMinimumValue (void) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcPositionTrackRenderInfo::rcPositionTrackRenderInfo().
virtual rcPositionSegmentIterator* rcPositionTrack::getDataSegmentIterator (const rcTimestamp & pos) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcMonitor::buildPositionPath(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::getPosition(), getTrackValue(), rcImageCanvasGL::getTrackValue(), rcExporter::init(), and rcScalarTrackWidget::updateTrackDisplay().
virtual rcFPair rcPositionTrack::getExpectedMaximumValue (void) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcNativeExporter::produceTracks().
virtual rcFPair rcPositionTrack::getExpectedMinimumValue (void) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcNativeExporter::produceTracks().
virtual uint32 rcPositionTrack::getSegmentCount (void) pure virtual
Implemented in rcPositionTrackImpl.
Referenced by rcExporter::hasValidSegments().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h