Visible: rcCarbonLock Class Reference
rcCarbonLock Class Reference abstract
#include <include/visual/rc_framegrabber.h>
Public Member Functions
virtual ~rcCarbonLock ()
virtual void lock ()=0
virtual void unlock ()=0
Detailed Description
Definition at line 110 of file rc_framegrabber.h.
Constructor & Destructor Documentation
virtual rcCarbonLock::~rcCarbonLock () inline virtual
Definition at line 112 of file rc_framegrabber.h.
 {}
Member Function Documentation
virtual void rcCarbonLock::lock () pure virtual
Implemented in rcEngineImpl, and rcExperimentDomainImpl.
Referenced by rcFileGrabber::lock(), and rcMovieConverter::lock().
virtual void rcCarbonLock::unlock () pure virtual
Implemented in rcEngineImpl, and rcExperimentDomainImpl.
Referenced by rcFileGrabber::unlock(), and rcMovieConverter::unlock().
The documentation for this class was generated from the following file:
include/visual/rc_framegrabber.h