Visible: rcVideoCaptureStatusReader Class Reference
rcVideoCaptureStatusReader Class Reference
#include <include/visiCore/rc_captureregs.h>
Public Member Functions
rcVideoCaptureStatusReader ()
virtual ~rcVideoCaptureStatusReader ()
rcRect getCaptureRect () const
rcPixel getCaptureDepth () const
double getMaxFramesPerSecond () const
Protected Attributes
rcAtomicValue< rcRect > _captureRect
rcAtomicValue< rcPixel > _captureDepth
rcAtomicValue< double > _maxFramesPerSecond
Detailed Description
Definition at line 119 of file rc_captureregs.h.
Constructor & Destructor Documentation
rcVideoCaptureStatusReader::rcVideoCaptureStatusReader () inline
Definition at line 122 of file rc_captureregs.h.
                                  : _captureRect(rcRect(0, 0, 640, 480)), _captureDepth(rcPixelUnknown), _maxFramesPerSecond(0.0)
   { }
virtual rcVideoCaptureStatusReader::~rcVideoCaptureStatusReader () inline virtual
Definition at line 125 of file rc_captureregs.h.
   { }
Member Function Documentation
rcPixel rcVideoCaptureStatusReader::getCaptureDepth () const inline
Definition at line 130 of file rc_captureregs.h.
References _captureDepth, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getAttributes().
   { rcPixel x; return _captureDepth.getValue(x); }
rcRect rcVideoCaptureStatusReader::getCaptureRect () const inline
Definition at line 128 of file rc_captureregs.h.
References _captureRect, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getAttributes(), rcEngineImpl::getSettingValue(), and rcEngineMovieCapture::run().
   { rcRect x; return _captureRect.getValue(x); }
double rcVideoCaptureStatusReader::getMaxFramesPerSecond () const inline
Definition at line 132 of file rc_captureregs.h.
References _maxFramesPerSecond, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::setSettingValue().
   { double x; return  _maxFramesPerSecond.getValue(x); }
Member Data Documentation
rcAtomicValue<rcPixel> rcVideoCaptureStatusReader::_captureDepth protected
Definition at line 137 of file rc_captureregs.h.
Referenced by rcVideoCaptureStatus::captureDepth(), and getCaptureDepth().
rcAtomicValue<rcRect> rcVideoCaptureStatusReader::_captureRect protected
Definition at line 136 of file rc_captureregs.h.
Referenced by rcVideoCaptureStatus::captureRect(), and getCaptureRect().
rcAtomicValue<double> rcVideoCaptureStatusReader::_maxFramesPerSecond protected
Definition at line 138 of file rc_captureregs.h.
Referenced by getMaxFramesPerSecond(), and rcVideoCaptureStatus::maxFramesPerSecond().
The documentation for this class was generated from the following file:
include/visiCore/rc_captureregs.h