Visible: rcGaussKernel2D< T, ksize > Class Template Reference
rcGaussKernel2D< T, ksize > Class Template Reference
#include <include/analysis/rc_ip.h>
Public Member Functions
rmStaticConstMacro (size, int, ksize)
rcGaussKernel2D ()
const T * kernel () const
const int16 * usKernel () const
Private Attributes
double mVariance
T mKernel [ksize][ksize]
int16 mUSkernel [ksize][ksize]
Detailed Description
template<class T, int ksize = 3>
class rcGaussKernel2D< T, ksize >
Two-dimensional Gaussian filter kernel
Todo:
finish support for variances
Definition at line 76 of file rc_ip.h.
Constructor & Destructor Documentation
template<class T , int ksize> rcGaussKernel2D< T, ksize >::rcGaussKernel2D ()
Definition at line 55 of file rc_ip.cpp.
References rcMathematicalImage::eHiPeak, rcMathematicalImage::gauss(), rcWindow::getPixel(), rcWindow::height(), rcHistoStats::mean(), rcHistoStats::n(), rcPixel16, sGaussFloatKernel3, sGaussKernel3, and rcWindow::width().
 {
     if (ksize < 7)
     {
         for (int32 j = 0; j < ksize; j++)
             for (int32 i = 0; i < ksize; i++)
         {
             mKernel[j][i] = sGaussFloatKernel3[j][i];
             mUSkernel[j][i] = sGaussKernel3[j][i];
         }
         return;
     }
     rcWindow buf (ksize, ksize, rcPixel16);
     rcMathematicalImage g;
     g.gauss (buf, rcMathematicalImage::eHiPeak);
     rcHistoStats h (buf, 65536);
     double sum = h.mean () * h.n();
     for (int32 j = 0; j < buf.height (); j++)
         for (int32 i = 0; i < buf.width (); i++)
     {
         mKernel[j][i] = buf.getPixel(i, j) / sum;
         mUSkernel[j][i] = buf.getPixel(i, j);
     }
 }
Member Function Documentation
template<class T , int ksize = 3> const T* rcGaussKernel2D< T, ksize >::kernel () const inline
returns a pointer to the kernel
Definition at line 92 of file rc_ip.h.
References rcGaussKernel2D< T, ksize >::mKernel.
   {
     return mKernel[0];
   }
template<class T , int ksize = 3> rcGaussKernel2D< T, ksize >::rmStaticConstMacro (size , int , ksize)
constructor
Parameters
size is the dimension: size x size kernel
theVariance variance of the kernel.
Todo:
negative
template<class T , int ksize = 3> const int16* rcGaussKernel2D< T, ksize >::usKernel () const inline
Definition at line 97 of file rc_ip.h.
References rcGaussKernel2D< T, ksize >::mUSkernel.
     {
         return mUSkernel[0];
     }
Member Data Documentation
template<class T , int ksize = 3> T rcGaussKernel2D< T, ksize >::mKernel[ksize][ksize] private
Definition at line 103 of file rc_ip.h.
Referenced by rcGaussKernel2D< T, ksize >::kernel().
template<class T , int ksize = 3> int16 rcGaussKernel2D< T, ksize >::mUSkernel[ksize][ksize] private
Definition at line 104 of file rc_ip.h.
Referenced by rcGaussKernel2D< T, ksize >::usKernel().
template<class T , int ksize = 3> double rcGaussKernel2D< T, ksize >::mVariance private
Definition at line 102 of file rc_ip.h.
The documentation for this class was generated from the following files:
include/analysis/rc_ip.h
src/analysis/code/rc_ip.cpp