Visible: rcXMLTimeMapper Class Reference
rcXMLTimeMapper Class Reference
#include <include/visiCore/rc_xmlelem.h>
Public Member Functions
rcXMLTimeMapper ()
rcXMLTimeMapper (const vector< rcTimestamp > &timeArray)
const rcTimestamp timeValue (uint32 i) const
int32 timeIndex (const rcTimestamp &time) const
Private Attributes
rcXMLTimeMap mTimeMap
vector< rcTimestamp > mTimes
Detailed Description
Definition at line 106 of file rc_xmlelem.h.
Constructor & Destructor Documentation
rcXMLTimeMapper::rcXMLTimeMapper () inline
Definition at line 108 of file rc_xmlelem.h.
 {}
rcXMLTimeMapper::rcXMLTimeMapper (const vector< rcTimestamp > & timeArray) inline
Definition at line 109 of file rc_xmlelem.h.
References mTimeMap, mTimes, rmAssert, and timeIndex().
     {
         mTimes = timeArray;
         // Fill time map
         for ( uint32 i = 0; i < timeArray.size(); ++i ) {
             mTimeMap.insert( make_pair( timeArray[i], i ) );
             // Immediate self-test, it can catch duplicates
             rmAssert( timeIndex( mTimes[i] ) == int32(i) );
         }
         // Each time should be unique, check final size
         rmAssert( mTimeMap.size() == timeArray.size() );
     };
Member Function Documentation
int32 rcXMLTimeMapper::timeIndex (const rcTimestamp & time) const inline
Definition at line 132 of file rc_xmlelem.h.
References mTimeMap.
Referenced by rcXMLTimeMapper().
{
         rcXMLTimeMap::const_iterator pos = mTimeMap.find( time );
         if ( pos != mTimeMap.end() )
             return pos->second;
         else
             return -1;
     };
const rcTimestamp rcXMLTimeMapper::timeValue (uint32 i) const inline
Definition at line 124 of file rc_xmlelem.h.
References mTimes.
Referenced by rcNativeImporter::parseFrame(), rcNativeImporter::parseValue(), and rcNativeExporter::produceResults().
{
         if ( i < mTimes.size() )
             return mTimes[i];
         else
             return rcTimestamp(-1.0);
     };
Member Data Documentation
rcXMLTimeMap rcXMLTimeMapper::mTimeMap private
Definition at line 138 of file rc_xmlelem.h.
Referenced by rcXMLTimeMapper(), and timeIndex().
vector<rcTimestamp> rcXMLTimeMapper::mTimes private
Definition at line 142 of file rc_xmlelem.h.
Referenced by rcXMLTimeMapper(), and timeValue().
The documentation for this class was generated from the following file:
include/visiCore/rc_xmlelem.h