Visible: backtick_subprocess Class Reference
backtick_subprocess Class Reference
#include <include/stlplus/subprocesses.hpp>
Public Member Functions
backtick_subprocess (void)
virtual bool callback (void)
bool spawn (const std::string &path, const arg_vector &argv)
bool spawn (const std::string &command_line)
const std::vector< std::string > & text (void) const
std::vector< std::string > & text (void)
Public Member Functions inherited from subprocess
subprocess (void)
virtual ~subprocess (void)
void add_variable (const std::string &name, const std::string &value)
bool remove_variable (const std::string &name)
bool spawn (const std::string &path, const arg_vector &argv, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)
bool spawn (const std::string &command_line, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)
bool kill (void)
int write_stdin (std::string &buffer)
int read_stdout (std::string &buffer)
int read_stderr (std::string &buffer)
void close_stdin (void)
void close_stdout (void)
void close_stderr (void)
bool error (void) const
int error_number (void) const
std::string error_text (void) const
int exit_status (void) const
Private Attributes
osvtext device
Detailed Description
Definition at line 207 of file subprocesses.hpp.
Constructor & Destructor Documentation
backtick_subprocess::backtick_subprocess (void)
Definition at line 1388 of file subprocesses.cpp.
                                              : subprocess()
 {
 }
Member Function Documentation
bool backtick_subprocess::callback (void) virtual
Reimplemented from subprocess.
Definition at line 1392 of file subprocesses.cpp.
References device, subprocess::error(), and subprocess::read_stdout().
 {
   for (;;)
   {
     std::string buffer;
     int read_size = read_stdout(buffer);
     if (read_size < 0) break;
     device << buffer;
   }
   return !error();
 }
bool backtick_subprocess::spawn (const std::string & path, const arg_vector & argv)
Definition at line 1404 of file subprocesses.cpp.
References subprocess::spawn().
Referenced by backtick().
 {
   return subprocess::spawn(path, argv, false, true, false);
 }
bool backtick_subprocess::spawn (const std::string & command_line)
Definition at line 1409 of file subprocesses.cpp.
References subprocess::spawn().
 {
   return subprocess::spawn(command_line, false, true, false);
 }
const std::vector< std::string > & backtick_subprocess::text (void) const
Definition at line 1414 of file subprocesses.cpp.
References device, and osvtext::get_vector().
Referenced by backtick().
 {
   return device.get_vector();
 }
std::vector< std::string > & backtick_subprocess::text (void)
Definition at line 1419 of file subprocesses.cpp.
References device, and osvtext::get_vector().
 {
   return device.get_vector();
 }
Member Data Documentation
osvtext backtick_subprocess::device private
Definition at line 210 of file subprocesses.hpp.
Referenced by callback(), and text().
The documentation for this class was generated from the following files:
include/stlplus/subprocesses.hpp
include/stlplus/subprocesses.cpp