Visible: rcExperimentDomainFactory Class Reference
rcExperimentDomainFactory Class Reference
#include <include/visiCore/rc_model.h>
Static Public Member Functions
static rcExperimentDomain * getExperimentDomain (const char *implKey=0)
Detailed Description
Definition at line 95 of file rc_model.h.
Member Function Documentation
rcExperimentDomain * rcExperimentDomainFactory::getExperimentDomain (const char * implKey = 0) static
Definition at line 530 of file rc_experimentdomainimpl.cpp.
References rcUNUSED.
Referenced by rcCSVExporter::exportExperiment(), main(), rcNativeExporter::produceResults(), rcModelDomain::rcModelDomain(), rcSegmentIteratorImpl::rcSegmentIteratorImpl(), and rcSegmentIteratorImpl::reset().
 {
     // The domain singleton is created at run-time
     static rcExperimentDomainImpl experimentDomain;
     rcUNUSED( implKey );
     return &experimentDomain;
 }
The documentation for this class was generated from the following files:
include/visiCore/rc_model.h
src/visible/src/rc_experimentdomainimpl.cpp