Visible: rcPositionTrackRenderInfo Class Reference
rcPositionTrackRenderInfo Class Reference
#include <include/visUI/rc_trackrender.h>
Public Member Functions
rcPositionTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, const QRect &dataRect)
rcPositionTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, const rcFPair &min, const rcFPair &max, const QRect &dataRect)
Public Member Functions inherited from rc2DTrackRenderInfo
rc2DTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, const rcFPair &min, const rcFPair &max, const QRect &dataRect)
const rcFPair & minValue () const
const rcFPair & maxValue () const
const std::string & xAxisName () const
const std::string & yAxisName () const
const std::string & xAxisNameNeg () const
const std::string & yAxisNameNeg () const
const std::string & xFormatString () const
const std::string & yFormatString () const
const rcIPair & tickCount () const
void minValue (const rcFPair &v)
void maxValue (const rcFPair &v)
void xAxisName (const std::string &n)
void yAxisName (const std::string &n)
void xAxisNameNeg (const std::string &n)
void yAxisNameNeg (const std::string &n)
void xFormatString (const std::string &s)
void yFormatString (const std::string &s)
void tickCount (const rcIPair &c)
Public Member Functions inherited from rcTrackRenderInfo
rcTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, rcTimestamp startTime, rcTimestamp endTime, const QRect &dataRect, bool logDisplay=false)
Additional Inherited Members
Public Attributes inherited from rcTrackRenderInfo
rcTrack * _track
rcTimestamp _startTime
rcTimestamp _endTime
double _minValue
double _maxValue
QRect _dataRect
QPen _tickMarkPen
QPen _dataPen
bool _isEnabled
bool _isHilited
QFont _tickMarkFont
bool _logDisplay
Protected Attributes inherited from rc2DTrackRenderInfo
rcFPair mMinValue
rcFPair mMaxValue
std::string mXAxisName
std::string mYAxisName
std::string mXAxisNameNeg
std::string mYAxisNameNeg
std::string mXFormatString
std::string mYFormatString
rcIPair mTickCount
Detailed Description
Definition at line 94 of file rc_trackrender.h.
Constructor & Destructor Documentation
rcPositionTrackRenderInfo::rcPositionTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack * track, const QRect & dataRect)
Definition at line 63 of file rc_trackrender.cpp.
References rcPositionTrack::getCurrentMaximumValue(), rcPositionTrack::getCurrentMinimumValue(), rc2DTrackRenderInfo::maxValue(), and rc2DTrackRenderInfo::minValue().
                                                                               :
         rc2DTrackRenderInfo( trackGroupNo, trackNo, track, rcFPair(0.0,0.0), rcFPair(0.0,0.0), dataRect )
 {
     rcPositionTrack* positionTrack = dynamic_cast<rcPositionTrack*>( track );
     if ( positionTrack ) {
         minValue( positionTrack->getCurrentMinimumValue() );
         maxValue( positionTrack->getCurrentMaximumValue() );
     }
}
rcPositionTrackRenderInfo::rcPositionTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack * track, const rcFPair & min, const rcFPair & max, const QRect & dataRect)
Definition at line 76 of file rc_trackrender.cpp.
References rc2DTrackRenderInfo::xFormatString(), and rc2DTrackRenderInfo::yFormatString().
                                                                               :
         rc2DTrackRenderInfo( trackGroupNo, trackNo, track, min, max, dataRect )
 {
     xFormatString( "%.1f" );
     yFormatString( "%.1f" );
}
The documentation for this class was generated from the following files:
include/visUI/rc_trackrender.h
src/visible/qt/rc_trackrender.cpp