Visible: rcCameraMapper Class Reference
rcCameraMapper Class Reference
#include <include/visual/rc_capture.hpp>
Public Types
typedef int dummy_type
typedef boost::bimaps::bimap
< UInt32, rcCameraProperty > property_map_type
typedef boost::bimaps::bimap
< UInt32, std::vector
< rcCameraFormat > > format_map_type
typedef
property_map_type::value_type property
typedef format_map_type::value_type format
Public Member Functions
rcCameraMapper ()
const property_map_type & propertyMap () const
const format_map_type & formatMap () const
void Fill_dcam_info ()
const rcCameraFormat get_format (UInt32 format, UInt32 mode)
const std::vector
< rcCameraFormat > & get_all_supported_formats ()
const uint32 size () const
ostream & dump (ostream &os)
Static Public Member Functions
static void rfSetCapability (CameraCapabilitiesStruct &cap, int type)
Private Member Functions
rcCameraProperty GetCameraProperty (void *cameraPtr, UInt32 type, UInt32 cntl)
Static Private Member Functions
static OSStatus getOneProperty (void *cameraPtr, UInt32 type, UInt32 cntl, UInt32 *value)
static void dump_capabilities (ostream &os, const CameraCapabilitiesStruct &cap)
Static Private Member Functions inherited from Singleton< rcCameraMapper >
static rcCameraMapper & instance ()
static void init ()
Private Attributes
property_map_type _CameraPropertyMap
format_map_type _CameraFormatMap
Detailed Description
Definition at line 215 of file rc_capture.hpp.
Member Typedef Documentation
typedef int rcCameraMapper::dummy_type
Definition at line 223 of file rc_capture.hpp.
typedef format_map_type::value_type rcCameraMapper::format
Definition at line 235 of file rc_capture.hpp.
typedef boost::bimaps::bimap< UInt32, std::vector<rcCameraFormat> > rcCameraMapper::format_map_type
Definition at line 232 of file rc_capture.hpp.
typedef property_map_type::value_type rcCameraMapper::property
Definition at line 234 of file rc_capture.hpp.
typedef boost::bimaps::bimap< UInt32, rcCameraProperty > rcCameraMapper::property_map_type
Definition at line 227 of file rc_capture.hpp.
Constructor & Destructor Documentation
rcCameraMapper::rcCameraMapper () inline
Definition at line 238 of file rc_capture.hpp.
     {
     }
Member Function Documentation
ostream& rcCameraMapper::dump (ostream & os) inline
Definition at line 317 of file rc_capture.hpp.
References endl().
     {
         property_map_type::left_map m = _CameraPropertyMap.left;
         for ( property_map_type::left_map::const_iterator iter(m.begin()),
              iend(m.end());
              iter != iend;
              ++iter )
         {
             os << iter->first << "-->" << iter->second
             << std::endl;
         }
         for ( format_map_type::const_iterator iter(_CameraFormatMap.begin()),
              iend(_CameraFormatMap.end());
              iter != iend;
              ++iter )
         {
             os << "Camera " << iter->left << " < ---- > ";
             const std::vector<rcCameraFormat>& vec = iter->right;
             std::vector<rcCameraFormat>::const_iterator formatItr = vec.begin();
             for (; formatItr < vec.end(); formatItr++)
             {
                 os << "Format: " << (int) formatItr->format() << " Mode: " << (int) formatItr->mode() << std::endl;
             }
         }
         return os;
     }
static void rcCameraMapper::dump_capabilities (ostream & os, const CameraCapabilitiesStruct & cap) inline static private
Definition at line 460 of file rc_capture.hpp.
References endl().
     {
         os << "Camera name: " << (char*)&cap.deviceName << " UID: " <<  cap.uniqueID
         << endl;
         dcam_formats df;
         os << "Formats:" << endl;
         if ( cap.format0 ) {
             for ( int i = 0; i < 7; ++i )
                 if ( cap.format0Modes[i] )
                     os << "Format 0: " << " Mode : " << i << std::endl;
         }
         if ( cap.format1 ) {
             for ( int i = 0; i < 7; ++i )
                 if ( cap.format1Modes[i] )
                     os << "Format 1: " << " Mode : " << i << std::endl;
         }
         if ( cap.format2 ) {
             for ( int i = 0; i < 7; ++i )
                 if ( cap.format2Modes[i] )
                     os << "Format 2: " << " Mode : " << i << std::endl;
         }
         if ( cap.format7 ) {
             os << "Format 7:" << endl;
                 // If we have format 7. This is camera specific. So we need it from some place @todo
             int num = sizeof (cap.format7Modes) / sizeof(bool);
             for (int i = 0; i < num; i++)
                 if ( cap.format7Modes[i] )
                     os << "Format 2: " << " Mode : " << i << std::endl;
             os << endl;
         }
         os << "Controls:" << endl;
         if ( cap.hasBright )
             os << "Brightness ";
         if ( cap.hasExpos )
             os << "Exposure ";
         if ( cap.hasSharp )
             os << "Sharpness ";
         if ( cap.hasWhiteB )
             os << "WhiteBalance ";
         if ( cap.hasHue )
             os << "Hue ";
         if ( cap.hasSat )
             os << "Saturation ";
         if ( cap.hasGain )
             os << "Gain ";
         if ( cap.hasGamma )
             os << "Gamma ";
         if ( cap.hasShutter )
             os << "Shutter ";
         if ( cap.hasIris )
             os << "Iris ";
         if ( cap.hasFocus )
             os << "Focus ";
         if ( cap.hasTemp )
             os << "Tempr ";
         if ( cap.hasTrigger )
             os << "Trigger ";
         if ( cap.hasZoom )
             os << "Zoom ";
         if ( cap.hasPan )
             os << "Pan ";
         if ( cap.hasTilt )
             os << "Tilt ";
         if ( cap.hasOpticalFilter )
             os << "Filter ";
         os << endl;
     }
void rcCameraMapper::Fill_dcam_info () inline
Definition at line 245 of file rc_capture.hpp.
References dump(), dcam_formats::get_supported_formats(), GetCameraProperty(), and sDCAMformats.
     {
         OSStatus                                        err;
         dcamCameraList                          theCameraList;
         if (ASCDCAMGetListOfCameras(&theCameraList) != 0 && theCameraList.numCamerasFound == 0) return;
         for ( uint32 i = 0; i < theCameraList.numCamerasFound; ++i )
         {
             dcamCameraListStruct camera = theCameraList.theCameras[i];
             boost::shared_ptr<void> cameraPtr = boost::shared_ptr<void>(ASCDCAMOpenACamera(camera.uniqueID), dcam_camera_closer() );
             if ( cameraPtr )
             {
                 CameraCapabilitiesStruct theProperties;
                 if (ASCDCAMGetCameraProperties(get_pointer(cameraPtr), &theProperties) != 0) continue;
                 dump_capabilities (std::cout, theProperties);
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_BRIGHTNESS_REG, MANUAL_CNTL) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_EXPOSURE_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_SHARPNESS_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_WHITE_BAL_REG, U_OR_B_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_WHITE_BAL_REG, V_OR_R_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_HUE_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_SATURATION_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_GAIN_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_GAMMA_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_SHUTTER_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_IRIS_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_FOCUS_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_TEMPERATURE_REG, TARGET_TEMP_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_TEMPERATURE_REG, CURR_TEMP_CNTL ) ) );
 #ifdef notyet
                     // TODO: Sony cameras return an error for this, investigate
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_TRIGGER_REG, TRIG_POLARITY_CNTL ) ) );
 #endif
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_TRIGGER_REG, TRIG_MODE_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_TRIGGER_REG, TRIG_PARAM_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_ZOOM_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_PAN_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_TILT_REG, MANUAL_CNTL ) ) );
                 _CameraPropertyMap.insert ( property ( camera.uniqueID, GetCameraProperty( get_pointer(cameraPtr), ASC_OPTICAL_FILTER_REG, MANUAL_CNTL ) ) );
                     // Check Formats supported
                 std::vector<rcCameraFormat> _supported_formats;
                 int num_formats = sDCAMformats.get_supported_formats (theProperties, _supported_formats );
                 std::cerr << num_formats << " Found \n";
                 _CameraFormatMap.insert ( format ( camera.uniqueID, _supported_formats) );
             }
         }
         dump (std::cerr);
     }
const format_map_type& rcCameraMapper::formatMap () const inline
Definition at line 243 of file rc_capture.hpp.
 { return _CameraFormatMap; }
const std::vector<rcCameraFormat>& rcCameraMapper::get_all_supported_formats () inline
Definition at line 307 of file rc_capture.hpp.
     {
             //      return _supported_formats;
     }
const rcCameraFormat rcCameraMapper::get_format (UInt32 format, UInt32 mode) inline
Definition at line 301 of file rc_capture.hpp.
     {
         rcCameraFormat f;
     }
rcCameraProperty rcCameraMapper::GetCameraProperty (void * cameraPtr, UInt32 type, UInt32 cntl) inline private
Definition at line 428 of file rc_capture.hpp.
References rcCameraProperty::active(), rcCameraProperty::canAuto(), rcCameraProperty::canManual(), rcCameraProperty::canOnePush(), rcCameraProperty::canOnOff(), rcCameraProperty::canReadOut(), rcCameraProperty::curValue(), endl(), getOneProperty(), rcCameraProperty::maxValue(), and rcCameraProperty::minValue().
     {
         rcCameraProperty prop( type, cntl );
         OSStatus err = ASCDCAMGetPropertyCapability( cameraPtr,
                                                     type,
                                                     &prop.minValue(),
                                                     &prop.maxValue(),
                                                     &prop.canOnePush(),
                                                     &prop.canReadOut(),
                                                     &prop.canOnOff(),
                                                     &prop.canAuto(),
                                                     &prop.canManual() );
         if ( err == 0 ) {
             if ( prop.canReadOut() ) {
                 prop.active() = 1;
                 err = getOneProperty( cameraPtr,
                                      type,
                                      cntl,
                                      &prop.curValue() );
                 if ( err != 0 )
                     prop.active() = 0;
             }
         } else {
 #ifdef DEBUG_LOG
             cerr << "ASCDCAMGetPropertyCapability " <<  propertyName( type ) << " error " << err << endl;
 #endif
         }
         return prop;
     }
static OSStatus rcCameraMapper::getOneProperty (void * cameraPtr, UInt32 type, UInt32 cntl, UInt32 * value) inline static private
Definition at line 416 of file rc_capture.hpp.
     {
         OSStatus err = ASCDCAMGetPropertyValue( cameraPtr,
                                                type,
                                                cntl,
                                                value );
         return err;
     }
const property_map_type& rcCameraMapper::propertyMap () const inline
Definition at line 242 of file rc_capture.hpp.
 { return _CameraPropertyMap; }
static void rcCameraMapper::rfSetCapability (CameraCapabilitiesStruct & cap, int type) inline static
Definition at line 350 of file rc_capture.hpp.
References endl().
     {
         switch ( type ) {
             case ASC_BRIGHTNESS_REG:
                 cap.hasBright = 1;
                 break;
             case ASC_EXPOSURE_REG:
                 cap.hasExpos = 1;
                 break;
             case ASC_SHARPNESS_REG:
                 cap.hasSharp = 1;
                 break;
             case ASC_WHITE_BAL_REG:
                 cap.hasWhiteB = 1;
                 break;
             case ASC_HUE_REG:
                 cap.hasHue = 1;
                 break;
             case ASC_SATURATION_REG:
                 cap.hasSat = 1;
                 break;
             case ASC_GAMMA_REG:
                 cap.hasGamma = 1;
                 break;
             case ASC_SHUTTER_REG:
                 cap.hasShutter = 1;
                 break;
             case ASC_GAIN_REG:
                 cap.hasGain = 1;
                 break;
             case ASC_IRIS_REG:
                 cap.hasIris = 1;
                 break;
             case ASC_FOCUS_REG:
                 cap.hasFocus = 1;
                 break;
             case ASC_TEMPERATURE_REG:
                 cap.hasTemp = 1;
                 break;
             case ASC_TRIGGER_REG:
                 cap.hasTrigger = 1;
                 break;
             case ASC_ZOOM_REG:
                 cap.hasZoom = 1;
                 break;
             case ASC_PAN_REG:
                 cap.hasPan = 1;
                 break;
             case ASC_TILT_REG:
                 cap.hasTilt = 1;
                 break;
             case ASC_OPTICAL_FILTER_REG:
                 cap.hasOpticalFilter = 1;
                 break;
             default:
                 cerr << "Error: unknown control " << type << endl;
                 break;
         }
     }
const uint32 rcCameraMapper::size (void) const inline
Definition at line 315 of file rc_capture.hpp.
 { return _CameraPropertyMap.size(); }
Member Data Documentation
format_map_type rcCameraMapper::_CameraFormatMap private
Definition at line 413 of file rc_capture.hpp.
property_map_type rcCameraMapper::_CameraPropertyMap private
Definition at line 412 of file rc_capture.hpp.
The documentation for this class was generated from the following file:
include/visual/rc_capture.hpp