Visible: rcTextSegment Class Reference
rcTextSegment Class Reference
#include <include/visual/rc_graphics.h>
Public Member Functions
rcTextSegment ()
rcTextSegment (const rc2Fvector &pos, const std::string &text)
const std::string & text () const
std::string & text ()
const rc2Fvector & pos () const
rc2Fvector & pos ()
void text (const std::string &text)
void pos (const rc2Fvector &pos)
Private Attributes
rc2Fvector mPos
std::string mText
Detailed Description
Definition at line 296 of file rc_graphics.h.
Constructor & Destructor Documentation
rcTextSegment::rcTextSegment () inline
Definition at line 298 of file rc_graphics.h.
 {};
rcTextSegment::rcTextSegment (const rc2Fvector & pos, const std::string & text) inline
Definition at line 299 of file rc_graphics.h.
 : mPos( pos ), mText( text ) {};
Member Function Documentation
const rc2Fvector& rcTextSegment::pos () const inline
Definition at line 304 of file rc_graphics.h.
References mPos.
Referenced by rcImageCanvasGL::draw().
 { return mPos; };
rc2Fvector& rcTextSegment::pos () inline
Definition at line 305 of file rc_graphics.h.
References mPos.
 { return mPos; };
void rcTextSegment::pos (const rc2Fvector & pos) inline
Definition at line 309 of file rc_graphics.h.
References mPos, and pos().
Referenced by pos().
 { mPos = pos; };
const std::string& rcTextSegment::text (void) const inline
Definition at line 302 of file rc_graphics.h.
References mText.
Referenced by rcImageCanvasGL::draw().
 { return mText; };
std::string& rcTextSegment::text (void) inline
Definition at line 303 of file rc_graphics.h.
References mText.
 { return mText; };
void rcTextSegment::text (const std::string & text) inline
Definition at line 308 of file rc_graphics.h.
References mText, and text().
Referenced by text().
 { mText = text; };
Member Data Documentation
rc2Fvector rcTextSegment::mPos private
Definition at line 309 of file rc_graphics.h.
Referenced by pos().
std::string rcTextSegment::mText private
Definition at line 313 of file rc_graphics.h.
Referenced by text().
The documentation for this class was generated from the following file:
include/visual/rc_graphics.h