Visible: env_vector Class Reference
env_vector Class Reference
#include <include/stlplus/subprocesses.hpp>
Public Member Functions
env_vector (void)
env_vector (const env_vector &)
~env_vector (void)
env_vector & operator= (const env_vector &)
void clear (void)
void add (const std::string &name, const std::string &value)
bool remove (const std::string &name)
std::string operator[] (const std::string &name) const
std::string get (const std::string &name) const
unsigned size (void) const
std::pair< std::string,
std::string > operator[] (unsigned index) const
std::pair< std::string,
std::string > get (unsigned index) const
char ** envp (void) const
Private Attributes
char ** v
Friends
otext & operator<< (otext &, const env_vector &)
Detailed Description
Definition at line 107 of file subprocesses.hpp.
Constructor & Destructor Documentation
env_vector::env_vector (void)
Definition at line 492 of file subprocesses.cpp.
References envp_copy(), and v.
 {
   v = envp_copy(environ);
 }
env_vector::env_vector (const env_vector & a)
Definition at line 499 of file subprocesses.cpp.
References v.
 {
   v = 0;
   *this = a;
 }
env_vector::~env_vector (void)
Definition at line 505 of file subprocesses.cpp.
References clear().
 {
   clear();
 }
Member Function Documentation
void env_vector::add (const std::string & name, const std::string & value)
Definition at line 568 of file subprocesses.cpp.
References envp_append(), envp_clear(), envp_extract(), envp_size(), and v.
 {
   // the trick is to add the value in alphabetic order
   // this is done by copying the existing environment vector and inserting the new value when a name greater than it is found
   unsigned size = envp_size(v);
   unsigned new_size = size + 1;
   char** new_v = new char*[new_size];
   new_v[0] = 0;
   // now extract each name=value pair and chk the ordering
   bool added = false;
   unsigned i = 0;
   unsigned j = 0;
   while(v[i])
   {
     std::string current_name;
     std::string current_value;
     envp_extract(current_name, current_value, v, i);
     // Note: Unix variables are case-sensitive
     if (name == current_name)
     {
       // replace an existing value
       envp_append(name, value, new_v, j);
     }
     else if (!added && name < current_name)
     {
       // add the new value first, then the existing one
       envp_append(name, value, new_v, j);
       envp_append(current_name, current_value, new_v, j);
       added = true;
     }
     else
     {
       // just add the existing value
       envp_append(current_name, current_value, new_v, j);
     }
   }
   if (!added)
     envp_append(name, value, new_v, j);
   envp_clear(v);
   v = new_v;
 }
void env_vector::clear (void)
Definition at line 517 of file subprocesses.cpp.
References envp_clear(), and v.
Referenced by operator=(), and ~env_vector().
 {
   envp_clear(v);
 }
char ** env_vector::envp (void) const
Definition at line 753 of file subprocesses.cpp.
References v.
 {
   return v;
 }
std::string env_vector::get (const std::string & name) const
Definition at line 689 of file subprocesses.cpp.
References envp_extract(), and v.
Referenced by operator<<().
 {
   unsigned i = 0;
   while(v[i])
   {
     std::string current_name;
     std::string current_value;
     envp_extract(current_name, current_value, v, i);
     if (name == current_name)
       return current_value;
   }
   return std::string();
 }
std::pair< std::string, std::string > env_vector::get (unsigned index) const
Definition at line 738 of file subprocesses.cpp.
References envp_extract(), and v.
 {
   unsigned j = 0;
   for (unsigned i = 0; i < index; i++)
   {
     std::string current_name;
     std::string current_value;
     envp_extract(current_name, current_value, v, j);
   }
   std::string name;
   std::string value;
   envp_extract(name, value, v, j);
   return std::make_pair(name,value);
 }
env_vector & env_vector::operator= (const env_vector & a)
Definition at line 510 of file subprocesses.cpp.
References clear(), envp_copy(), and v.
 {
   clear();
   v = envp_copy(a.v);
   return *this;
 }
std::string env_vector::operator[] (const std::string & name) const
Definition at line 666 of file subprocesses.cpp.
 {
   return get(name);
 }
std::pair< std::string, std::string > env_vector::operator[] (unsigned index) const
Definition at line 733 of file subprocesses.cpp.
 {
   return get(index);
 }
bool env_vector::remove (const std::string & name)
Definition at line 640 of file subprocesses.cpp.
References envp_append(), envp_clear(), envp_extract(), envp_size(), size(), and v.
 {
   bool result = false;
   // this is done by copying the existing environment vector, but excluding the specified name
   unsigned size = envp_size(v);
   char** new_v = new char*[size];
   new_v[0] = 0;
   unsigned i = 0;
   unsigned j = 0;
   while(v[i])
   {
     std::string current_name;
     std::string current_value;
     envp_extract(current_name, current_value, v, i);
     if (name == current_name)
       result = true;
     else
       envp_append(current_name, current_value, new_v, j);
   }
   envp_clear(v);
   v = new_v;
   return result;
 }
unsigned env_vector::size (void) const
Definition at line 723 of file subprocesses.cpp.
References v.
Referenced by operator<<(), and remove().
 {
   unsigned i = 0;
   while(v[i])
     i++;
   return i;
 }
Friends And Related Function Documentation
otext& operator<< (otext & , const env_vector &) friend
Definition at line 758 of file subprocesses.cpp.
 {
   for (unsigned i = 0; i < a.size(); i++)
   {
     std::pair<std::string,std::string> current = a.get(i);
     t << current.first << "=" << current.second << endl;
   }
   return t;
 }
Member Data Documentation
char** env_vector::v private
Definition at line 110 of file subprocesses.hpp.
Referenced by add(), clear(), env_vector(), envp(), get(), operator=(), remove(), and size().
The documentation for this class was generated from the following files:
include/stlplus/subprocesses.hpp
include/stlplus/subprocesses.cpp