Visible: rcLsFit< T > Class Template Reference
rcLsFit< T > Class Template Reference
#include <include/util/rc_lsfit.h>
Public Member Functions
rcLsFit ()
void update (const rc2dVector< T > &xy, const rc2dVector< T > &uv)
void update (const rc2dVector< T > &uv)
bool solve3p (rc2dVector< T > &trans, rcRadian &rot)
bool solvetp (rc2dVector< T > &trans, rcMatrix_2d &mat)
bool solvetp (rc2Xform &xform)
bool solvetp (rc2dVector< T > &trans)
T rms (const rc2dVector< T > &xy, const rc2dVector< T > &uv, rc2dVector< T > &trans, rcMatrix_2d &mat)
T rms (const rc2dVector< T > &xy, const rc2dVector< T > &uv, const rc2Xform &)
rcLineSegment< T > fit () const
T error (const rcLineSegment< T > &) const
Private Attributes
T mSvx
T mSux
T mSuy
T mSvy
T mSxx
T mSxy
T mSyy
T mSuu
T mSuv
T mSvv
T mSu
T mSv
T mSx
T mSy
T mN
T mX2
int32 mRMSn
Detailed Description
template<class T>
class rcLsFit< T >
Definition at line 62 of file rc_lsfit.h.
Constructor & Destructor Documentation
template<class T> rcLsFit< T >::rcLsFit () inline
Definition at line 66 of file rc_lsfit.h.
              :
   mSvx (T(0)), mSux (T(0)), mSuy (T(0)), mSvy (T(0)),
     mSxx(T(0)), mSxy(T(0)), mSyy(T(0)),
     mSuu(T(0)), mSuv(T(0)), mSvv(T(0)), mSu (T(0)),
     mSv (T(0)), mSx (T(0)), mSy (T(0)), mN (0), mX2 (T(0)),
mRMSn (0) {}
Member Function Documentation
template<class T > T rcLsFit< T >::error (const rcLineSegment< T > & line) const
Definition at line 372 of file rc_lsfit.h.
References rcLineSegment< T >::angle(), cos(), rcLineSegment< T >::distance(), and sin().
 {
   T d, s, c;
   d = line.distance();
   s = sin (line.angle());
   c = cos (line.angle());
   return (  d*d*mN
       + 2*d*(s*mSu - c*mSv)
       + s*s*mSuu + c*c*mSvv
       - 2*s*c*mSuv);
 }
template<class T > rcLineSegment< T > rcLsFit< T >::fit () const
Definition at line 343 of file rc_lsfit.h.
References atan2(), rkPI, and rmSquare.
Referenced by rcOptoKineticImage::genLogRMS().
 {
   T
     xnom = mSu / mN,
     ynom = mSv / mN,
     a = mSuu - mSu * xnom,
     b = 2 * (mSuv - mSu * ynom),
     c = mSvv - mSv * ynom;
   if (fabs(b) < 1e-12 && fabs(a - c) < 1e-12)
     throw general_exception ("Unstable line Fit");
   T
     hypotenuse = sqrt(rmSquare(b) + rmSquare(a - c)),
     cos2theta = (a - c) / hypotenuse,
     sn = sqrt( (1 - cos2theta) / 2),
     cn = sqrt( (1 + cos2theta) / 2);
   if (b < 0) cn = -cn;
   T distance = -(xnom * sn)+(ynom * cn);
   rcRadian angle(atan2(sn,cn));
   if (distance >= 0)
     return rcLineSegment<T>(angle,distance);
   return rcLineSegment<T>(angle+rcRadian(rkPI),-distance);
 }
template<class T > T rcLsFit< T >::rms (const rc2dVector< T > & xy, const rc2dVector< T > & uv, rc2dVector< T > & trans, rcMatrix_2d & mat)
Definition at line 276 of file rc_lsfit.h.
References rc2dVector< T >::distanceSquared(), and rcMatrix_2d::inverse().
 {
   rc2Xform xm (mat, trans);
   return rcLsFit<T>::rms (xy, uv, xm);
 #if 0
   rc2Fvector d = xy * mat.inverse() + trans;
   mX2 += uv.distanceSquared (d);
   mRMSn++;
   return (T) (sqrt ((double) mX2 / mRMSn));
 #endif
 }
template<class T > T rcLsFit< T >::rms (const rc2dVector< T > & xy, const rc2dVector< T > & uv, const rc2Xform & xm)
Definition at line 290 of file rc_lsfit.h.
References rc2dVector< T >::distanceSquared(), and rc2Xform::invMapPoint().
 {
   rc2Fvector d = xm.invMapPoint (xy);
   mX2 += uv.distanceSquared (d);
   mRMSn++;
   return (T) (sqrt ((double) mX2 / mRMSn));
 }
template<class T > bool rcLsFit< T >::solve3p (rc2dVector< T > & trans, rcRadian & rot)
Definition at line 138 of file rc_lsfit.h.
References atan2(), cos(), sin(), rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     if (mN < 3) return false;
     T e = mN * (mSux + mSvy) - mSu * mSx - mSv * mSy;
     T d = mN * (mSvx + mSuy) + mSu * mSy - mSv * mSx;
     rot = atan2 ((double) d, (double) e);
     T c = (T) cos (rot);
     T s = (T) sin (rot);
     trans.x ((mSu - c * mSx + s * mSy) / mN);
     trans.y ((mSv - s * mSx - c * mSy) / mN);
     return true;
   }
template<class T > bool rcLsFit< T >::solvetp (rc2dVector< T > & trans, rcMatrix_2d & mat)
Definition at line 170 of file rc_lsfit.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcLsFit< T >::solvetp(), and rcVisualFunction::vXform().
   {
     if (mN < 3) return false;
     trans.x ((mSu - mSx) / mN);
     trans.y ((mSv - mSy) / mN);
     mat = rcMatrix_2d ((mSux - (mSu * mSx) / mN) /
              (mSxx - (mSx * mSx) / mN),
              0.0, 0.0,
              (mSvy - (mSv * mSy) / mN) /
              (mSyy - (mSy * mSy) / mN));
     return true;
   }
template<class T > bool rcLsFit< T >::solvetp (rc2Xform & xform)
Definition at line 158 of file rc_lsfit.h.
References rc2Xform::matrix(), rcLsFit< T >::solvetp(), and rc2Xform::trans().
   {
     if (mN < 3) return false;
     rc2dVector<T> trans; rcMatrix_2d mat;
     bool success = rcLsFit<T>::solvetp (trans, mat);
     xm.trans(trans);xm.matrix (mat);
     return success;
   }
template<class T > bool rcLsFit< T >::solvetp (rc2dVector< T > & trans)
Definition at line 187 of file rc_lsfit.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     if (mN < 2) return false;
     trans.x ((mSu - mSx) / mN);
     trans.y ((mSv - mSy) / mN);
     return true;
   }
template<class T > void rcLsFit< T >::update (const rc2dVector< T > & xy, const rc2dVector< T > & uv)
Definition at line 199 of file rc_lsfit.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcOptoKineticImage::genLogRMS(), and rcVisualFunction::vXform().
   {
     const T& x(xy.x()), y(xy.y()), u(uv.x()), v(uv.y());
     mSx += x, mSy += y, mSu += u, mSv +=v;
     mSxx += x * x;
     mSyy += y * y;
     mSxy += x * y;
     mSuu += u * u;
     mSuv += u * v;
     mSvv += v * v;
     mSux += u * x;
     mSvx += v * x;
     mSuy += u * y;
     mSvy += v * y;
     mN += T (1);
   };
template<class T > void rcLsFit< T >::update (const rc2dVector< T > & uv)
Definition at line 219 of file rc_lsfit.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     const T& u(uv.x()), v(uv.y());
     mSu += u, mSv +=v;
     mSuu += u * u;
     mSuv += u * v;
     mSvv += v * v;
     mN += T (1);
   };
Member Data Documentation
template<class T> T rcLsFit< T >::mN private
Definition at line 131 of file rc_lsfit.h.
template<class T> int32 rcLsFit< T >::mRMSn private
Definition at line 133 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSu private
Definition at line 127 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSuu private
Definition at line 124 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSuv private
Definition at line 125 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSux private
Definition at line 118 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSuy private
Definition at line 119 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSv private
Definition at line 128 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSvv private
Definition at line 126 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSvx private
Definition at line 117 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSvy private
Definition at line 120 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSx private
Definition at line 129 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSxx private
Definition at line 121 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSxy private
Definition at line 122 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSy private
Definition at line 130 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mSyy private
Definition at line 123 of file rc_lsfit.h.
template<class T> T rcLsFit< T >::mX2 private
Definition at line 132 of file rc_lsfit.h.
The documentation for this class was generated from the following file:
include/util/rc_lsfit.h