Visible: rcPositionSegmentIterator Class Reference
rcPositionSegmentIterator Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcPositionSegmentIterator ()
virtual rcFPair getValue (void)=0
Public Member Functions inherited from rcSegmentIterator
virtual ~rcSegmentIterator ()
virtual rcTimestamp getSegmentLength (void)=0
virtual rcTimestamp getSegmentOffset (void)=0
virtual rcTimestamp getTrackOffset (void)=0
virtual int32 getSegmentIndex (void)=0
virtual rcTimestamp getSegmentStart (void)=0
virtual rcTimestamp getSegmentStartAbsolute (void)=0
virtual bool hasNextSegment (bool lock=true)=0
virtual uint32 getSegmentCount (void)=0
virtual bool contains (const rcTimestamp &time)=0
virtual rcRect getFocus (void)=0
virtual void advance (const rcTimestamp &amount, bool lock=true)=0
virtual bool advance (int32 offset, bool lock=true)=0
virtual void lock ()=0
virtual void unlock ()=0
virtual void reset (bool lock=true)=0
virtual void release (void)=0
Detailed Description
Definition at line 655 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcPositionSegmentIterator::~rcPositionSegmentIterator () inline virtual
Definition at line 659 of file rc_model.h.
 {};
Member Function Documentation
virtual rcFPair rcPositionSegmentIterator::getValue (void) pure virtual
Implemented in rcPositionSegmentIteratorImpl.
Referenced by rcMonitor::buildPositionPath(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::getPosition(), getTrackValue(), rcImageCanvasGL::getTrackValue(), rcExporter::produceValue(), and rcScalarTrackWidget::updateTrackDisplay().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h