Visible: rcScalarTrack Class Reference
rcScalarTrack Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Types
enum { ePersistenceVersion = 1 }
Public Member Functions
virtual ~rcScalarTrack ()
virtual double getExpectedMinimumValue (void)=0
virtual double getExpectedMaximumValue (void)=0
virtual double getCurrentMinimumValue (void)=0
virtual double getCurrentMaximumValue (void)=0
virtual rcScalarSegmentIterator * getDataSegmentIterator (const rcTimestamp &pos)=0
virtual uint32 getSegmentCount (void)=0
Detailed Description
Definition at line 414 of file rc_model.h.
Member Enumeration Documentation
anonymous enum
Enumerator
ePersistenceVersion
Definition at line 417 of file rc_model.h.
 { ePersistenceVersion = 1 };
Constructor & Destructor Documentation
virtual rcScalarTrack::~rcScalarTrack () inline virtual
Definition at line 420 of file rc_model.h.
 { };
Member Function Documentation
virtual double rcScalarTrack::getCurrentMaximumValue (void) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcTimeline::getScalarTrackMinMax().
virtual double rcScalarTrack::getCurrentMinimumValue (void) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcTimeline::getScalarTrackMinMax().
virtual rcScalarSegmentIterator* rcScalarTrack::getDataSegmentIterator (const rcTimestamp & pos) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcTrackManager::copyTrackToClipboard(), rcTimeline::getFrameTime(), rcTimeline::getSegmentLength(), getTrackValue(), rcImageCanvasGL::getTrackValue(), rcExporter::init(), rcTimeline::paintScalarTrack(), rcMonitor::paintScalarTrackFocus(), and rcScalarTrackWidget::updateTrackDisplay().
virtual double rcScalarTrack::getExpectedMaximumValue (void) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcTimeline::getScalarTrackMinMax(), and rcNativeExporter::produceTracks().
virtual double rcScalarTrack::getExpectedMinimumValue (void) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcTimeline::getScalarTrackMinMax(), and rcNativeExporter::produceTracks().
virtual uint32 rcScalarTrack::getSegmentCount (void) pure virtual
Implemented in rcScalarTrackImpl.
Referenced by rcExporter::hasValidSegments().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h