Visible: rcMovieSaveCtrlReader Class Reference
rcMovieSaveCtrlReader Class Reference
#include <include/visiCore/rc_saveregs.h>
Public Member Functions
rcMovieSaveCtrlReader ()
virtual ~rcMovieSaveCtrlReader ()
uint32 getFrameCaptureTime () const
uint32 getFrameCaptureDelayTime () const
std::string getOutputFileName () const
std::string getMovieFileName () const
Protected Attributes
rcAtomicValue< uint32 > _frameCaptureTime
rcAtomicValue< uint32 > _frameCaptureDelayTime
rcMutex _mutex
std::string _outputFileName
std::string _movieFileName
Detailed Description
Definition at line 46 of file rc_saveregs.h.
Constructor & Destructor Documentation
rcMovieSaveCtrlReader::rcMovieSaveCtrlReader () inline
Definition at line 49 of file rc_saveregs.h.
     : _frameCaptureTime(0), _frameCaptureDelayTime(0), _outputFileName(""),
     _movieFileName("")
   { }
virtual rcMovieSaveCtrlReader::~rcMovieSaveCtrlReader () inline virtual
Definition at line 54 of file rc_saveregs.h.
   { }
Member Function Documentation
uint32 rcMovieSaveCtrlReader::getFrameCaptureDelayTime () const inline
Definition at line 69 of file rc_saveregs.h.
References _frameCaptureDelayTime, and rcAtomicValue< T >::getValue().
Referenced by rcEngineMovieSaver::delayHdlr(), rcEngineImpl::getSettingValue(), and rcEngineMovieSaver::waitHdlr().
   {
     uint32 x;
     return _frameCaptureDelayTime.getValue(x);
   }
uint32 rcMovieSaveCtrlReader::getFrameCaptureTime () const inline
Definition at line 60 of file rc_saveregs.h.
References _frameCaptureTime, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), and rcEngineMovieSaver::waitHdlr().
   {
     uint32 x;
     return _frameCaptureTime.getValue(x);
   }
std::string rcMovieSaveCtrlReader::getMovieFileName () const inline
Definition at line 86 of file rc_saveregs.h.
References _movieFileName, and _mutex.
Referenced by rcEngineMovieSaver::closeHdlr().
   {
     rcMutex* mutex = const_cast<rcMutex*>(&_mutex);
     rcLock lock(*mutex);
     std::string retVal = _movieFileName;
     return retVal;
   }
std::string rcMovieSaveCtrlReader::getOutputFileName () const inline
Definition at line 75 of file rc_saveregs.h.
References _mutex, and _outputFileName.
Referenced by rcEngineImpl::getSettingValue(), and rcEngineMovieSaver::waitHdlr().
   {
     rcMutex* mutex = const_cast<rcMutex*>(&_mutex);
     rcLock lock(*mutex);
     std::string retVal = _outputFileName;
     return retVal;
   }
Member Data Documentation
rcAtomicValue<uint32> rcMovieSaveCtrlReader::_frameCaptureDelayTime protected
Definition at line 101 of file rc_saveregs.h.
Referenced by rcMovieSaveCtrl::frameCaptureDelayTime(), and getFrameCaptureDelayTime().
rcAtomicValue<uint32> rcMovieSaveCtrlReader::_frameCaptureTime protected
Definition at line 100 of file rc_saveregs.h.
Referenced by rcMovieSaveCtrl::frameCaptureTime(), and getFrameCaptureTime().
std::string rcMovieSaveCtrlReader::_movieFileName protected
Definition at line 107 of file rc_saveregs.h.
Referenced by getMovieFileName(), and rcMovieSaveCtrl::movieFileName().
rcMutex rcMovieSaveCtrlReader::_mutex protected
Definition at line 105 of file rc_saveregs.h.
Referenced by getMovieFileName(), getOutputFileName(), rcMovieSaveCtrl::movieFileName(), and rcMovieSaveCtrl::outputFileName().
std::string rcMovieSaveCtrlReader::_outputFileName protected
Definition at line 106 of file rc_saveregs.h.
Referenced by getOutputFileName(), and rcMovieSaveCtrl::outputFileName().
The documentation for this class was generated from the following file:
include/visiCore/rc_saveregs.h