Visible: ini_file Class Reference
ini_file Class Reference
Public Member Functions
ini_file (void)
ini_file (const std::string &filename)
~ini_file (void)
bool initialised (void) const
bool writable (void) const
bool read_file (const std::string &filename)
bool save_file (void)
std::string filename (void) const
bool empty (void) const
bool section_exists (const std::string &title) const
bool add_section (const std::string &section)
bool empty_section (const std::string &section)
bool erase_section (const std::string &section)
bool clear_section (const std::string &section)
unsigned sections_size (void) const
const std::string & section_name (unsigned i) const
std::vector< std::string > section_names (void) const
bool variable_exists (const std::string &section, const std::string variable) const
std::vector< std::string > variable_names (const std::string &section) const
unsigned variables_size (const std::string &section) const
unsigned variable_line (const std::string &section, const std::string variable) const
std::string variable_name (const std::string &section, unsigned i) const
std::string variable_value (const std::string &section, unsigned i) const
std::string variable_value (const std::string &section, const std::string variable) const
bool add_variable (const std::string &section, const std::string &variable, const std::string &value)
bool add_comment (const std::string &section, const std::string &comment)
bool add_blank (const std::string &section)
bool erase_variable (const std::string &section, const std::string &variable)
Private Member Functions
std::list< smart_ptr
< ini_section >
>::const_iterator find_section (const std::string &section) const
std::list< smart_ptr
< ini_section > >::iterator find_section (const std::string &section)
Private Attributes
std::string m_filename
bool m_changed
bool m_writable
std::list< smart_ptr
< ini_section > > m_sections
Friends
class ini_section
otext & print (otext &str, const ini_file &manager, unsigned indent=0)
otext & operator<< (otext &str, const ini_file &manager)
Detailed Description
Definition at line 234 of file ini_manager.cpp.
Constructor & Destructor Documentation
ini_file::ini_file (void) inline
Definition at line 265 of file ini_manager.cpp.
                  : m_changed(false), m_writable(false)
     {
     }
ini_file::ini_file (const std::string & filename) inline
Definition at line 269 of file ini_manager.cpp.
References read_file().
                                       : m_changed(false), m_writable(false)
     {
       read_file(filename);
     }
ini_file::~ini_file (void) inline
Definition at line 274 of file ini_manager.cpp.
References save_file(), and writable().
     {
       if (writable())
         save_file();
     }
Member Function Documentation
bool ini_file::add_blank (const std::string & section) inline
Definition at line 518 of file ini_manager.cpp.
References find_section(), ini_section, m_changed, m_sections, and m_writable.
     {
       if (!m_writable) return false;
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) found = m_sections.insert(m_sections.end(),ini_section(section));
       if ((*found)->add_blank(0))
         m_changed = true;
       return true;
     }
bool ini_file::add_comment (const std::string & section, const std::string & comment) inline
Definition at line 508 of file ini_manager.cpp.
References find_section(), ini_section, m_changed, m_sections, and m_writable.
     {
       if (!m_writable) return false;
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) found = m_sections.insert(m_sections.end(),ini_section(section));
       if ((*found)->add_comment(0,comment))
         m_changed = true;
       return true;
     }
bool ini_file::add_section (const std::string & section) inline
Definition at line 395 of file ini_manager.cpp.
References ini_section, m_sections, and m_writable.
     {
       if (!m_writable) return false;
       m_sections.push_back(ini_section(section));
       return true;
     }
bool ini_file::add_variable (const std::string & section, const std::string & variable, const std::string & value) inline
Definition at line 498 of file ini_manager.cpp.
References find_section(), ini_section, m_changed, m_sections, and m_writable.
     {
       if (!m_writable) return false;
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) found = m_sections.insert(m_sections.end(),ini_section(section));
       if ((*found)->add_variable(0, variable,value))
         m_changed = true;
       return true;
     }
bool ini_file::clear_section (const std::string & section) inline
Definition at line 418 of file ini_manager.cpp.
References find_section(), m_sections, and m_writable.
     {
       if (!m_writable) return false;
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) return false;
       (*found)->clear();
       return true;
     }
bool ini_file::empty (void) const inline
Definition at line 382 of file ini_manager.cpp.
References m_sections.
     {
       // file is empty if it has either no sections or an empty header section
       if (m_sections.empty()) return true;
       if ((m_sections.begin() == --m_sections.end()) && (*m_sections.begin())->empty()) return true;
       return false;
     }
bool ini_file::empty_section (const std::string & section) inline
Definition at line 402 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) return false;
       return (*found)->empty();
     }
bool ini_file::erase_section (const std::string & section) inline
Definition at line 409 of file ini_manager.cpp.
References find_section(), m_sections, and m_writable.
     {
       if (!m_writable) return false;
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) return false;
       m_sections.erase(found);
       return true;
     }
bool ini_file::erase_variable (const std::string & section, const std::string & variable) inline
Definition at line 528 of file ini_manager.cpp.
References find_section(), m_changed, m_sections, and m_writable.
     {
       if (!m_writable) return false;
       std::list<smart_ptr<ini_section> >::iterator found = find_section(section);
       if (found == m_sections.end()) return false;
       if ((*found)->erase_variable(variable))
       {
         m_changed = true;
         return true;
       }
       return false;
     }
std::string ini_file::filename (void) const inline
Definition at line 377 of file ini_manager.cpp.
References m_filename.
Referenced by read_file().
     {
       return m_filename;
     }
std::list<smart_ptr<ini_section> >::const_iterator ini_file::find_section (const std::string & section) const inline private
Definition at line 243 of file ini_manager.cpp.
References m_sections.
Referenced by add_blank(), add_comment(), add_variable(), clear_section(), empty_section(), erase_section(), erase_variable(), section_exists(), variable_exists(), variable_line(), variable_name(), variable_names(), variable_value(), and variables_size().
     {
       for (std::list<smart_ptr<ini_section> >::const_iterator i = m_sections.begin(); i != m_sections.end(); i++)
       {
         if ((*i)->title() == section)
           return i;
       }
       return m_sections.end();
     }
std::list<smart_ptr<ini_section> >::iterator ini_file::find_section (const std::string & section) inline private
Definition at line 253 of file ini_manager.cpp.
References m_sections.
     {
       for (std::list<smart_ptr<ini_section> >::iterator i = m_sections.begin(); i != m_sections.end(); i++)
       {
         if ((*i)->title() == section)
           return i;
       }
       return m_sections.end();
     }
bool ini_file::initialised (void) const inline
Definition at line 280 of file ini_manager.cpp.
References m_filename.
Referenced by save_file().
     {
       return !m_filename.empty();
     }
bool ini_file::read_file (const std::string & filename) inline
Definition at line 290 of file ini_manager.cpp.
References file_exists(), file_writable(), filename(), itext::getline(), ini_section, m_changed, m_filename, m_sections, m_writable, ini_section::title(), and trim().
Referenced by ini_file().
     {
       m_filename = filename;
       m_changed = false;
       m_writable = file_writable(m_filename);
       // create a dummy top section to hold file comments
       std::list<smart_ptr<ini_section> >::iterator section = m_sections.insert(m_sections.end(), ini_section(""));
       if (!file_exists(m_filename))
         return true;
       iftext input(m_filename);
       std::string line;
       unsigned line_number = 0;
       while(input.getline(line))
       {
         line_number++;
         unsigned i = 0;
         while(i < line.size() && isspace(line[i]))
           i++;
         if (i < line.size() && line[i] == '[')
         {
           // found a section title
           // skip the [
           i++;
           // get the text up to the end ] or the end of the line
           std::string title;
           while (i < line.size() && line[i] != ']')
             title += line[i++];
           // create a new section and make it the current section
           section = m_sections.insert(m_sections.end(), ini_section(title));
         }
         else if (i < line.size() && line[i] == ';')
         {
           // found a comment
           // skip the ; because that is not part of the comment
           i++;
           // add the rest of the line as a comment to the current section
           (*section)->add_comment(line_number, line.substr(i, line.size()-1));
         }
         else if (i == line.size())
         {
           // found a blank line
           (*section)->add_blank(line_number);
         }
         else
         {
           // found a *possible* variable - now scan forwards for the = operator
           std::string name;
           while (i < line.size() && line[i] != '=')
             name += line[i++];
           // skip the = sign
           // TODO - detect a missing = sign here and convert to an error
           if (i < line.size())
             i++;
           // trim trailing whitespace off the name
           name = trim(name);
           // now get the value, minus any leading whitespace
           std::string value;
           while(i < line.size() && isspace(line[i]))
             i++;
           while (i < line.size())
             value += line[i++];
           // trim trailing whitespace off the value
           value = trim(value);
           // and finally add the name/value pair to the data structure
           (*section)->add_variable(line_number, name, value);
         }
       }
       return true;
     }
bool ini_file::save_file (void) inline
Definition at line 360 of file ini_manager.cpp.
References endl(), initialised(), m_changed, m_filename, m_sections, m_writable, and output().
Referenced by ~ini_file().
     {
       if (!initialised()) return false;
       if (!m_changed) return true;
       if (!m_writable) return false;
       oftext output(m_filename);
       for (std::list<smart_ptr<ini_section> >::iterator section = m_sections.begin(); section != m_sections.end(); section++)
       {
         if (!((*section)->title().empty()))
           output << "[" << (*section)->title() << "]" << endl;
         for (std::list<ini_entry>::iterator entry = (*section)->m_entries.begin(); entry != (*section)->m_entries.end(); entry++)
           output << entry->text() << endl;
       }
       m_changed = false;
       return true;
     }
bool ini_file::section_exists (const std::string & title) const inline
Definition at line 390 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       return find_section(title) != m_sections.end();
     }
const std::string& ini_file::section_name (unsigned i) const inline
Definition at line 432 of file ini_manager.cpp.
References DEBUG_ASSERT, and m_sections.
Referenced by section_names().
     {
       DEBUG_ASSERT(i < m_sections.size());
       std::list<smart_ptr<ini_section> >::const_iterator result = m_sections.begin();
       for (unsigned j = 1; j <= i; j++)
         result++;
       return (*result)->title();
     }
std::vector<std::string> ini_file::section_names (void) const inline
Definition at line 441 of file ini_manager.cpp.
References section_name(), and sections_size().
     {
       std::vector<std::string> result;
       for (unsigned j = 0; j < sections_size(); j++)
         result.push_back(section_name(j));
       return result;
     }
unsigned ini_file::sections_size (void) const inline
Definition at line 427 of file ini_manager.cpp.
References m_sections.
Referenced by section_names().
     {
       return m_sections.size();
     }
bool ini_file::variable_exists (const std::string & section, const std::string variable) const inline
Definition at line 449 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return false;
       return (*found)->variable_exists(variable);
     }
unsigned ini_file::variable_line (const std::string & section, const std::string variable) const inline
Definition at line 470 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return 0;
       return (*found)->variable_line(variable);
     }
std::string ini_file::variable_name (const std::string & section, unsigned i) const inline
Definition at line 477 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return std::string();
       return (*found)->variable_name(i);
     }
std::vector<std::string> ini_file::variable_names (const std::string & section) const inline
Definition at line 456 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return std::vector<std::string>();
       return (*found)->variable_names();
     }
std::string ini_file::variable_value (const std::string & section, unsigned i) const inline
Definition at line 484 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return std::string();
       return (*found)->variable_value(i);
     }
std::string ini_file::variable_value (const std::string & section, const std::string variable) const inline
Definition at line 491 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return std::string();
       return (*found)->variable_value(variable);
     }
unsigned ini_file::variables_size (const std::string & section) const inline
Definition at line 463 of file ini_manager.cpp.
References find_section(), and m_sections.
     {
       std::list<smart_ptr<ini_section> >::const_iterator found = find_section(section);
       if (found == m_sections.end()) return 0;
       return (*found)->variables_size();
     }
bool ini_file::writable (void) const inline
Definition at line 285 of file ini_manager.cpp.
References m_writable.
Referenced by ~ini_file().
     {
       return m_writable;
     }
Friends And Related Function Documentation
friend class ini_section friend
Definition at line 237 of file ini_manager.cpp.
Referenced by add_blank(), add_comment(), add_section(), add_variable(), and read_file().
otext& operator<< (otext & str, const ini_file & manager) friend
Definition at line 550 of file ini_manager.cpp.
     {
       return print(str, manager);
     }
otext& print (otext & str, const ini_file & manager, unsigned indent = 0) friend
Definition at line 541 of file ini_manager.cpp.
     {
       print_indent(str, indent);
       str << "file: " << manager.m_filename << endl;
       for (std::list<smart_ptr<ini_section> >::const_iterator section = manager.m_sections.begin(); section != manager.m_sections.end(); section++)
         print(str, **section, indent);
       return str;
     }
Member Data Documentation
bool ini_file::m_changed private
Definition at line 239 of file ini_manager.cpp.
Referenced by add_blank(), add_comment(), add_variable(), erase_variable(), read_file(), and save_file().
std::string ini_file::m_filename private
Definition at line 238 of file ini_manager.cpp.
Referenced by filename(), initialised(), read_file(), and save_file().
std::list<smart_ptr<ini_section> > ini_file::m_sections private
Definition at line 241 of file ini_manager.cpp.
Referenced by add_blank(), add_comment(), add_section(), add_variable(), clear_section(), empty(), empty_section(), erase_section(), erase_variable(), find_section(), read_file(), save_file(), section_exists(), section_name(), sections_size(), variable_exists(), variable_line(), variable_name(), variable_names(), variable_value(), and variables_size().
bool ini_file::m_writable private
Definition at line 240 of file ini_manager.cpp.
Referenced by add_blank(), add_comment(), add_section(), add_variable(), clear_section(), erase_section(), erase_variable(), read_file(), save_file(), and writable().
The documentation for this class was generated from the following file:
include/stlplus/ini_manager.cpp