Visible: rcLineEdit Class Reference
rcLineEdit Class Reference
#include <include/visUI/rc_lineedit.h>
Public Slots
void relayTextCommited (void)
Signals
void textCommited (const QString &text)
Public Member Functions
rcLineEdit (QWidget *parent, const char *name=0)
rcLineEdit (const QString &contents, QWidget *parent, const char *name=0)
Protected Member Functions
virtual void focusOutEvent (QFocusEvent *event)
Detailed Description
Definition at line 8 of file rc_lineedit.h.
Constructor & Destructor Documentation
rcLineEdit::rcLineEdit (QWidget * parent, const char * name = 0) inline
Definition at line 13 of file rc_lineedit.h.
References relayTextCommited().
         : QLineEdit( parent , name )
     {
         connect( this , SIGNAL( returnPressed( void ) ) ,
                  this , SLOT( relayTextCommited( void ) ) );
     }
rcLineEdit::rcLineEdit (const QString & contents, QWidget * parent, const char * name = 0) inline
Definition at line 20 of file rc_lineedit.h.
References relayTextCommited().
         : QLineEdit( contents , parent , name )
     {
         connect( this , SIGNAL( returnPressed( void ) ) ,
                  this , SLOT( relayTextCommited( void ) ) );
     }
Member Function Documentation
virtual void rcLineEdit::focusOutEvent (QFocusEvent * event) inline protected virtual
Definition at line 28 of file rc_lineedit.h.
References textCommited().
     {
         QLineEdit::focusOutEvent( event );
         emit textCommited( text() );
     }
void rcLineEdit::relayTextCommited (void) inline slot
Definition at line 35 of file rc_lineedit.h.
References textCommited().
Referenced by rcLineEdit().
     {
         emit textCommited( text() );
     }
void rcLineEdit::textCommited (const QString & text) signal
Definition at line 78 of file moc_rc_lineedit.cpp.
Referenced by focusOutEvent(), and relayTextCommited().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
The documentation for this class was generated from the following files:
include/visUI/rc_lineedit.h
src/visible/moc/moc_rc_lineedit.cpp