Visible: rcEngine Class Reference
rcEngine Class Reference abstract
#include <include/visiCore/rc_engine.h>
Public Member Functions
virtual ~rcEngine ()
virtual void initialize (rcEngineObserver *observer)=0
virtual void shutdown (void)=0
virtual int getNSettingCategories (void)=0
virtual rcSettingCategory getSettingCategory (int categoryNo)=0
virtual rcTimestamp getElapsedTime (void)=0
virtual rcTimestamp getStartTime (void)=0
virtual rcEngineState getState (void)=0
virtual const rcEngineAttributes getAttributes (void)=0
virtual bool operatingOnLiveInput (void)=0
virtual bool storingLiveInput (void)=0
virtual void start (void)=0
virtual void stop (void)=0
virtual void reset (void)=0
virtual void process (void)=0
virtual bool pauseTracking (void)=0
virtual bool resumeTracking (void)=0
virtual void notifyEngineOfPolys (const rcPolygonGroupRef *polys)=0
Detailed Description
Definition at line 129 of file rc_engine.h.
Constructor & Destructor Documentation
virtual rcEngine::~rcEngine () inline virtual
Definition at line 133 of file rc_engine.h.
 { };
Member Function Documentation
virtual const rcEngineAttributes rcEngine::getAttributes (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::getExperimentAttributes(), rcExperimentDomainImpl::notifyMovieImport(), and rcExperimentDomainImpl::notifyState().
virtual rcTimestamp rcEngine::getElapsedTime (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::getExperimentLength(), and rcEngineProgress::progress().
virtual int rcEngine::getNSettingCategories (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentImpl::rcExperimentImpl().
virtual rcSettingCategory rcEngine::getSettingCategory (int categoryNo) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentImpl::rcExperimentImpl().
virtual rcTimestamp rcEngine::getStartTime (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::getExperimentStart().
virtual rcEngineState rcEngine::getState (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcEngineProgress::progress().
virtual void rcEngine::initialize (rcEngineObserver * observer) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::initialize().
virtual void rcEngine::notifyEngineOfPolys (const rcPolygonGroupRef * polys) pure virtual
Implemented in rcEngineImpl.
Referenced by rcExperimentDomainImpl::notifyPolys().
virtual bool rcEngine::operatingOnLiveInput (void) pure virtual
Implemented in rcEngineImpl.
Referenced by rcExperimentDomainImpl::operatingOnLiveInput().
virtual bool rcEngine::pauseTracking (void) pure virtual
Implemented in rcEngineImpl.
Referenced by rcExperimentDomainImpl::pauseTrackingExperiment().
virtual void rcEngine::process (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::processExperiment().
virtual void rcEngine::reset (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::newExperiment().
virtual bool rcEngine::resumeTracking (void) pure virtual
Implemented in rcEngineImpl.
Referenced by rcExperimentDomainImpl::doneSelecting().
virtual void rcEngine::shutdown (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::shutdown().
virtual void rcEngine::start (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::startExperiment().
virtual void rcEngine::stop (void) pure virtual
Implemented in rcEngineBaseImpl, and rcEngineImpl.
Referenced by rcExperimentDomainImpl::stopExperiment().
virtual bool rcEngine::storingLiveInput (void) pure virtual
Implemented in rcEngineImpl.
Referenced by rcExperimentDomainImpl::storingLiveInput().
The documentation for this class was generated from the following file:
include/visiCore/rc_engine.h