Visible: rcVideoCache::rcVideoCachePrefetchUnit Class Reference
rcVideoCache::rcVideoCachePrefetchUnit Class Reference
Public Member Functions
rcVideoCachePrefetchUnit (rcVideoCache &cacheCtrl)
virtual ~rcVideoCachePrefetchUnit ()
virtual void run ()
void prefetch (uint32 frameIndex)
Public Member Functions inherited from rcThread
rcThread (rcRunnable *runnable)
virtual ~rcThread (void)
void setPriority (rcThreadPriority pri)
rcThreadPriority getPriority (void)
void start (void)
bool isRunning (void)
void checkException (void)
virtual int join (bool seppuku=true)
Public Member Functions inherited from rcRunnable
rcRunnable ()
virtual ~rcRunnable ()
void requestSeppuku ()
void clearSeppuku ()
Private Attributes
rcVideoCache & _cacheCtrl
rcMutex _prefetchMutex
deque< uint32 > _prefetchRequests
rcConditionVariable _wait
Additional Inherited Members
Static Public Member Functions inherited from rcThread
static void sleep (long msec)
Protected Member Functions inherited from rcThread
rcThread (void)
Detailed Description
Definition at line 217 of file rc_videocache.h.
Constructor & Destructor Documentation
rcVideoCache::rcVideoCachePrefetchUnit::rcVideoCachePrefetchUnit (rcVideoCache & cacheCtrl)
Definition at line 1814 of file rc_videocache.cpp.
References rcVideoCache::isValid(), and rmAssert.
         : _cacheCtrl(cacheCtrl), _wait(0)
 {
     rmAssert(cacheCtrl.isValid());
 }
rcVideoCache::rcVideoCachePrefetchUnit::~rcVideoCachePrefetchUnit () virtual
Definition at line 1820 of file rc_videocache.cpp.
 {
 }
Member Function Documentation
void rcVideoCache::rcVideoCachePrefetchUnit::prefetch (uint32 frameIndex)
Definition at line 1874 of file rc_videocache.cpp.
Referenced by rcVideoCache::prefetchFrame(), and rcVideoCache::~rcVideoCache().
 {
     bool empty;
     {
         rcLock lock(_prefetchMutex);
         empty = _prefetchRequests.empty();
         _prefetchRequests.push_back(frameIndex);
     }
     if (empty)
         _wait.incrementVariable(1, 0);
 }
void rcVideoCache::rcVideoCachePrefetchUnit::run (void) virtual
Reimplemented from rcThread.
Definition at line 1824 of file rc_videocache.cpp.
References endl(), eVideoCacheErrorNoSuchFrame, and eVideoCacheStatusError.
 {
     uint32 frameIndex = 0;
     bool active = true;
     bool killMe = false;
     while (!killMe) {
         bool wait = false;
         {
             rcLock lock(_prefetchMutex);
             if (_prefetchRequests.empty())
                 wait = true;
             else {
                 frameIndex = _prefetchRequests.front();
                 _prefetchRequests.pop_front();
             }
         }
         /* Guard against chance that above check of prefetch queue
          * didn't occur AFTER dtor gets called. (Because dtor
          * makes dummy prefetch request with disk mutex locked - this
          * will cause hang when this fuction tries to load frame from
          * disk)
          */
         killMe = seppukuRequested();
         if (wait) {
             int32 curVal = _wait.waitUntilGreaterThan(0);
             _wait.decrementVariable(curVal, 0);
         }
         else if (active && !killMe) {
             /* Have a frame to prefetch. Do this by using getFrame() to load
              * the frame into cache. Since we don't want to lock this frame
              * into memory, merely load it into cache, the frame is set up
              * in a temporary frame buffer.
              */
             rcVideoCacheError error;
             rcSharedFrameBufPtr frameBuf;
             rcVideoCacheStatus status = _cacheCtrl.getFrame(frameIndex, frameBuf,
                                                             &error);
             /* Stop processing if something bad happens */
             if ((status == eVideoCacheStatusError) &&
                 (error != eVideoCacheErrorNoSuchFrame)) {
                 cerr << "Prefetch error: " << _cacheCtrl.getErrorString(error) << endl;
                 active = false;
             }
         }
     }
 }
Member Data Documentation
rcVideoCache& rcVideoCache::rcVideoCachePrefetchUnit::_cacheCtrl private
Definition at line 235 of file rc_videocache.h.
rcMutex rcVideoCache::rcVideoCachePrefetchUnit::_prefetchMutex private
Definition at line 236 of file rc_videocache.h.
deque<uint32> rcVideoCache::rcVideoCachePrefetchUnit::_prefetchRequests private
Definition at line 237 of file rc_videocache.h.
rcConditionVariable rcVideoCache::rcVideoCachePrefetchUnit::_wait private
Definition at line 238 of file rc_videocache.h.
The documentation for this class was generated from the following files:
include/visual/rc_videocache.h
src/visual/code/rc_videocache.cpp