Visible: rcCorr Class Reference
rcCorr Class Reference
#include <include/analysis/rc_analysis.h>
Public Member Functions
rcCorr ()
double compute ()
double cosine ()
double relative ()
void accumulate (unsigned int &sim, unsigned int &sii, unsigned int &smm, unsigned int &si, unsigned int &sm)
void accumulate (unsigned int &sim, unsigned int &sii, unsigned int &si)
void accumulateM (unsigned int &sim, unsigned int &smm, unsigned int &sm)
void accumulate (unsigned int &sim)
void accumulate (double &sim, double &sii, double &smm, double &si, double &sm)
void accumulate (double &sim, double &sii, double &si)
void accumulateM (double &sim, double &smm, double &sm)
void accumulate (double &sim)
double iStd ()
double mStd ()
double r () const
double r (double r)
bool singular () const
int32 n () const
int32 n (int32 n)
double Si () const
double Si (double Si)
double Sm () const
double Sm (double Sm)
double Sii () const
double Sii (double Sii)
double Smm () const
double Smm (double Smm)
double Sim () const
double Sim (double Sim)
bool operator== (const rcCorr &o) const
bool operator!= (const rcCorr &o) const
Private Attributes
double mR
double mCosine
double mEim
double mSi
double mSm
double mSii
double mSmm
double mSim
int32 mN
bool mRp
Detailed Description
Definition at line 49 of file rc_analysis.h.
Constructor & Destructor Documentation
rcCorr::rcCorr () inline
Definition at line 52 of file rc_analysis.h.
 : mR(0.0), mSi(0), mSm (0), mSii (0), mSmm (0), mSim (0), mN(0), mRp(0), mEim (0), mCosine (0) {}
Member Function Documentation
void rcCorr::accumulate (unsigned int & sim, unsigned int & sii, unsigned int & smm, unsigned int & si, unsigned int & sm) inline
Definition at line 92 of file rc_analysis.h.
    {
      mSim += sim;
      mSii += sii;
      mSmm += smm;
      mSi += si;
      mSm += sm;
    }
void rcCorr::accumulate (unsigned int & sim, unsigned int & sii, unsigned int & si) inline
Definition at line 105 of file rc_analysis.h.
    {
      mSim += sim;
      mSii += sii;
      mSi += si;
    }
void rcCorr::accumulate (unsigned int & sim) inline
Definition at line 123 of file rc_analysis.h.
    {
      mSim += sim;
    }
void rcCorr::accumulate (double & sim, double & sii, double & smm, double & si, double & sm) inline
Definition at line 129 of file rc_analysis.h.
    {
      mSim += sim;
      mSii += sii;
      mSmm += smm;
      mSi += si;
      mSm += sm;
    }
void rcCorr::accumulate (double & sim, double & sii, double & si) inline
Definition at line 142 of file rc_analysis.h.
    {
      mSim += sim;
      mSii += sii;
      mSi += si;
    }
void rcCorr::accumulate (double & sim) inline
Definition at line 160 of file rc_analysis.h.
    {
      mSim += sim;
    }
void rcCorr::accumulateM (unsigned int & sim, unsigned int & smm, unsigned int & sm) inline
Definition at line 114 of file rc_analysis.h.
    {
      mSim += sim;
      mSmm += smm;
      mSm += sm;
    }
void rcCorr::accumulateM (double & sim, double & smm, double & sm) inline
Definition at line 151 of file rc_analysis.h.
    {
      mSim += sim;
      mSmm += smm;
      mSm += sm;
    }
double rcCorr::compute () inline
Definition at line 56 of file rc_analysis.h.
References rmAssertDebug.
Referenced by rfCorrelate().
     {
         rmAssertDebug( mSi >= 0.0 );
         rmAssertDebug( mSm >= 0.0 );
         const double ei = ((mN * mSii) - (mSi * mSi));
         const double em = ((mN * mSmm) - (mSm * mSm));
         const double mEim = ei * em;
         // Modified Normalized Correlation. If both image and model have zero standard deviation and equal moments then
         // they are identical. This case produces 0 in regression based correlation because you can not fit a line
         // through a single point. However, from image matching point of view it is a perfect match.
         mRp = (mEim == 0.) && (mSmm == mSii) && (mSi == mSm);
         mCosine = ((mN * mSim) - (mSi * mSm));
         mCosine = mCosine < 0 ? 0 : mCosine;
         mR = (mCosine * mCosine ) / mEim;
         return mR;
     }
double rcCorr::cosine () inline
Definition at line 77 of file rc_analysis.h.
     {
         return acos (mCosine / std::sqrt (mEim));
     }
double rcCorr::iStd () inline
Definition at line 166 of file rc_analysis.h.
   {
     double dN (mN);
     return sqrt (((mN * mSii) - (mSi * mSi)) / (dN * (dN - 1.)));
   }
double rcCorr::mStd () inline
Definition at line 172 of file rc_analysis.h.
   {
     double dN (mN);
     return sqrt (((mN * mSmm) - (mSm * mSm)) / (dN * (dN - 1.)));
   }
int32 rcCorr::n () const inline
Definition at line 185 of file rc_analysis.h.
Referenced by operator<<(), and rfCorrelate().
 { return mN; }
int32 rcCorr::n (int32 n) inline
Definition at line 187 of file rc_analysis.h.
References n().
Referenced by n().
 {return mN = n;}
bool rcCorr::operator!= (const rcCorr & o) const inline
Definition at line 215 of file rc_analysis.h.
References operator==().
 { return !(this->operator==(o)); }
bool rcCorr::operator== (const rcCorr & o) const inline
Definition at line 209 of file rc_analysis.h.
References mN, mR, mRp, mSi, mSii, mSim, mSm, and mSmm.
   {
     return (mR == o.mR && mRp == o.mRp && mN == o.mN && mSi == o.mSi && mSm == o.mSm &&
         mSii == o.mSii && mSmm == o.mSmm && mSim == o.mSim);
   }
double rcCorr::r () const inline
Definition at line 179 of file rc_analysis.h.
Referenced by _exhaustiveImageFind(), calcMusclePeriod(), rcSimilarator::correlate(), rcMuscleTracker::genSpace(), rcPointCorrelation::genSpace(), operator<<(), and rfOptoKineticEnergy().
 { return mR; }
double rcCorr::r (double r) inline
Definition at line 181 of file rc_analysis.h.
References r().
Referenced by r().
 {return mR = r;}
double rcCorr::relative () inline
Definition at line 82 of file rc_analysis.h.
References rmAssertDebug.
     {
         rmAssertDebug( mSi >= 0.0 );
         rmAssertDebug( mSm >= 0.0 );
         return std::sqrt (r () );
     }
double rcCorr::Si () const inline
Definition at line 189 of file rc_analysis.h.
Referenced by operator<<(), and rfCorrelateWindow().
 { return mSi; }
double rcCorr::Si (double Si) inline
Definition at line 191 of file rc_analysis.h.
References Si().
Referenced by Si().
 {return mSi = Si;}
double rcCorr::Sii () const inline
Definition at line 197 of file rc_analysis.h.
Referenced by operator<<(), and rfCorrelateWindow().
 { return mSii; }
double rcCorr::Sii (double Sii) inline
Definition at line 199 of file rc_analysis.h.
References Sii().
Referenced by Sii().
 {return mSii = Sii;}
double rcCorr::Sim () const inline
Definition at line 205 of file rc_analysis.h.
Referenced by operator<<().
 { return mSim; }
double rcCorr::Sim (double Sim) inline
Definition at line 207 of file rc_analysis.h.
References Sim().
Referenced by Sim().
 {return mSim = Sim;}
bool rcCorr::singular () const inline
Definition at line 183 of file rc_analysis.h.
Referenced by operator<<().
 { return mRp; }
double rcCorr::Sm () const inline
Definition at line 193 of file rc_analysis.h.
Referenced by operator<<(), and rfCorrelateWindow().
 { return mSm; }
double rcCorr::Sm (double Sm) inline
Definition at line 195 of file rc_analysis.h.
References Sm().
Referenced by Sm().
 {return mSm = Sm;}
double rcCorr::Smm () const inline
Definition at line 201 of file rc_analysis.h.
Referenced by operator<<(), and rfCorrelateWindow().
 { return mSmm; }
double rcCorr::Smm (double Smm) inline
Definition at line 203 of file rc_analysis.h.
References Smm().
Referenced by Smm().
 {return mSmm = Smm;}
Member Data Documentation
double rcCorr::mCosine private
Definition at line 218 of file rc_analysis.h.
double rcCorr::mEim private
Definition at line 218 of file rc_analysis.h.
int32 rcCorr::mN private
Definition at line 221 of file rc_analysis.h.
Referenced by operator==().
double rcCorr::mR private
Definition at line 218 of file rc_analysis.h.
Referenced by operator==().
bool rcCorr::mRp private
Definition at line 222 of file rc_analysis.h.
Referenced by operator==().
double rcCorr::mSi private
Definition at line 219 of file rc_analysis.h.
Referenced by operator==().
double rcCorr::mSii private
Definition at line 220 of file rc_analysis.h.
Referenced by operator==().
double rcCorr::mSim private
Definition at line 220 of file rc_analysis.h.
Referenced by operator==().
double rcCorr::mSm private
Definition at line 219 of file rc_analysis.h.
Referenced by operator==().
double rcCorr::mSmm private
Definition at line 220 of file rc_analysis.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
include/analysis/rc_analysis.h