Visible: rcMovieFileExpExt Class Reference
rcMovieFileExpExt Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileExpExt ()
bool write (FILE *saveStream) const
ostream & log (ostream &os, bool showUndefined=true) const
void fixEndian (const reByteOrder &fileByteOrder)
const int32 & id () const
const float & lensMag () const
const float & otherMag () const
const float & temperature () const
const float & CO2 () const
const float & O2 () const
const char * title () const
const char * userName () const
const char * treatment1 () const
const char * treatment2 () const
const char * cellType () const
const char * imagingMode () const
const char * comment () const
void id (const int32 &i)
void lensMag (const float &v)
void otherMag (const float &v)
void temperature (const float &v)
void CO2 (const float &v)
void O2 (const float &v)
void title (const char *n)
void userName (const char *n)
void treatment1 (const char *n)
void treatment2 (const char *n)
void cellType (const char *n)
void imagingMode (const char *n)
void comment (const char *n)
Public Member Functions inherited from rcMovieFileExt
rcMovieFileExt ()
rcMovieFileExt (movieExtensionType t)
rcMovieFileExt (movieExtensionType t, int64 o)
const movieExtensionType & type () const
const int64 & offset () const
bool write (FILE *saveStream) const
void fixEndian (const reByteOrder &fileByteOrder)
Private Attributes
float mLensMag
float mOtherMag
float mTemperature
float mCO2
float mO2
int32 mId
char mTitle [128]
char mUserName [128]
char mTreatment1 [128]
char mTreatment2 [128]
char mCellType [128]
char mImagingMode [128]
char mComment [128]
Detailed Description
Definition at line 483 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileExpExt::rcMovieFileExpExt ()
Definition at line 702 of file rc_moviefileformat.cpp.
References mCellType, mComment, mImagingMode, mTitle, mTreatment1, mTreatment2, mUserName, and rmDim.
                                      :
         rcMovieFileExt(movieExtensionEXP, sizeof(rcMovieFileExpExt)),
         mLensMag(-1.0f), mOtherMag(-1.0f), mTemperature(-1.0f),
         mCO2(-1.0f), mO2(-1.0f), mId(0)
 {
     memset( mTitle, 0, rmDim(mTitle) );
     memset( mUserName, 0, rmDim(mUserName) );
     memset( mTreatment1, 0, rmDim(mTreatment1) );
     memset( mTreatment2, 0, rmDim(mTreatment2) );
     memset( mCellType, 0, rmDim(mCellType) );
     memset( mImagingMode, 0, rmDim(mImagingMode) );
     memset( mComment, 0, rmDim(mComment) );
     snprintf( mCellType, rmDim(mCellType), "Unspecified" );
     snprintf( mImagingMode, rmDim(mImagingMode), "Unspecified" );
}
Member Function Documentation
const char* rcMovieFileExpExt::cellType () const inline
Definition at line 508 of file rc_moviefileformat.h.
References mCellType.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mCellType; }
void rcMovieFileExpExt::cellType (const char * n) inline
Definition at line 524 of file rc_moviefileformat.h.
References mCellType, and rmDim.
 { if ( n ) strncpy( mCellType, n, rmDim(mCellType) ); }
const float& rcMovieFileExpExt::CO2 () const inline
Definition at line 501 of file rc_moviefileformat.h.
References mCO2.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mCO2; }
void rcMovieFileExpExt::CO2 (const float & v) inline
Definition at line 517 of file rc_moviefileformat.h.
References mCO2.
 { mCO2 = v; }
const char* rcMovieFileExpExt::comment (void) const inline
Definition at line 510 of file rc_moviefileformat.h.
References mComment.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), log(), and operator<<().
 { return mComment; }
void rcMovieFileExpExt::comment (const char * n) inline
Definition at line 526 of file rc_moviefileformat.h.
References mComment, and rmDim.
 { if ( n ) strncpy( mComment, n, rmDim(mComment) ); }
void rcMovieFileExpExt::fixEndian (const reByteOrder & fileByteOrder)
Definition at line 735 of file rc_moviefileformat.cpp.
References ByteSwapN, rcMovieFileExt::fixEndian(), mCO2, mId, mLensMag, mO2, mOtherMag, mTemperature, and rfPlatformByteOrder().
Referenced by rcVideoCache::expLoad(), and write().
 {
     if ( rfPlatformByteOrder() != fileByteOrder )
     {
         rcMovieFileExt::fixEndian (fileByteOrder);
         ByteSwapN (mId);                         // Unique id, reserved for future use
         ByteSwapN (mLensMag); // = (float) EndianU32_LtoB ((uint32) mLensMag);
         ByteSwapN (mOtherMag); // = (float) EndianU32_LtoB ((uint32) mOtherMag);
         ByteSwapN (mTemperature); //  = (float) EndianU32_LtoB ((uint32) mTemperature);
         ByteSwapN(mCO2); //  = (float) EndianU32_LtoB ((uint32) mCO2);
         ByteSwapN(mO2); //  = (float) EndianU32_LtoB ((uint32) mO2);
     }
 }
const int32& rcMovieFileExpExt::id (void) const inline
Definition at line 497 of file rc_moviefileformat.h.
References mId.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), and operator<<().
 { return mId; }
void rcMovieFileExpExt::id (const int32 & i) inline
Definition at line 513 of file rc_moviefileformat.h.
References mId.
 { mId = i; }
const char* rcMovieFileExpExt::imagingMode () const inline
Definition at line 509 of file rc_moviefileformat.h.
References mImagingMode.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mImagingMode; }
void rcMovieFileExpExt::imagingMode (const char * n) inline
Definition at line 525 of file rc_moviefileformat.h.
References mImagingMode, and rmDim.
 { if ( n ) strncpy( mImagingMode, n, rmDim(mImagingMode) ); }
const float& rcMovieFileExpExt::lensMag () const inline
Definition at line 498 of file rc_moviefileformat.h.
References mLensMag.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mLensMag; }
void rcMovieFileExpExt::lensMag (const float & v) inline
Definition at line 514 of file rc_moviefileformat.h.
References mLensMag.
 { mLensMag = v; }
ostream & rcMovieFileExpExt::log (ostream & os, bool showUndefined = true) const
Definition at line 751 of file rc_moviefileformat.cpp.
References cellType(), CO2(), comment(), endl(), imagingMode(), lensMag(), O2(), otherMag(), temperature(), title(), treatment1(), treatment2(), and userName().
Referenced by rcEngineImpl::setCaptureInfo().
 {
     bool shown = false;
     if ( showUndefined || (!showUndefined && strlen(title())) )
         os << " Title: " << title() << endl;
     if ( showUndefined || (!showUndefined && strlen(userName())) )
         os << " UserName: " << userName() << endl;
     if ( showUndefined || (!showUndefined && strlen(treatment1())) )
         os << " Treatment1: " << treatment1() << endl;
     if ( showUndefined || (!showUndefined && strlen(treatment2())) )
         os << " Treatment2: " << treatment2() << endl;
     if ( showUndefined || (!showUndefined && strlen(cellType())) )
         os << " CellType: " << cellType() << endl;
     if ( showUndefined || (!showUndefined && strlen(imagingMode())) )
         os << " ImagingMode: " << imagingMode() << endl;
     if ( showUndefined || (!showUndefined && strlen(comment())) )
         os << " Comment: " << comment() << endl;
     if ( showUndefined || (!showUndefined && lensMag() >= 0))
         os << " LensMag: " << lensMag(), shown = true;
     if ( showUndefined || (!showUndefined && otherMag() >= 0))
         os << " OtherMag: " << otherMag(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && temperature() >= 0))
         os << " Temp: " << temperature() << "C", shown = true;
     if ( showUndefined || (!showUndefined && CO2() >= 0))
         os << " CO2: " << CO2() << "%", shown = true;
     if ( showUndefined || (!showUndefined && O2() >= 0))
         os << " O2: " << O2() << "%", shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     return os;
 }
const float& rcMovieFileExpExt::O2 () const inline
Definition at line 502 of file rc_moviefileformat.h.
References mO2.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mO2; }
void rcMovieFileExpExt::O2 (const float & v) inline
Definition at line 518 of file rc_moviefileformat.h.
References mO2.
 { mO2 = v; }
const float& rcMovieFileExpExt::otherMag () const inline
Definition at line 499 of file rc_moviefileformat.h.
References mOtherMag.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mOtherMag; }
void rcMovieFileExpExt::otherMag (const float & v) inline
Definition at line 515 of file rc_moviefileformat.h.
References mOtherMag.
 { mOtherMag = v; }
const float& rcMovieFileExpExt::temperature () const inline
Definition at line 500 of file rc_moviefileformat.h.
References mTemperature.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mTemperature; }
void rcMovieFileExpExt::temperature (const float & v) inline
Definition at line 516 of file rc_moviefileformat.h.
References mTemperature.
 { mTemperature = v; }
const char* rcMovieFileExpExt::title (void) const inline
Definition at line 504 of file rc_moviefileformat.h.
References mTitle.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), log(), and operator<<().
 { return mTitle; }
void rcMovieFileExpExt::title (const char * n) inline
Definition at line 520 of file rc_moviefileformat.h.
References mTitle, and rmDim.
 { if ( n ) strncpy( mTitle, n, rmDim(mTitle) ); }
const char* rcMovieFileExpExt::treatment1 () const inline
Definition at line 506 of file rc_moviefileformat.h.
References mTreatment1.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), log(), and operator<<().
 { return mTreatment1; }
void rcMovieFileExpExt::treatment1 (const char * n) inline
Definition at line 522 of file rc_moviefileformat.h.
References mTreatment1, and rmDim.
 { if ( n ) strncpy( mTreatment1, n, rmDim(mTreatment1) ); }
const char* rcMovieFileExpExt::treatment2 () const inline
Definition at line 507 of file rc_moviefileformat.h.
References mTreatment2.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), log(), and operator<<().
 { return mTreatment2; }
void rcMovieFileExpExt::treatment2 (const char * n) inline
Definition at line 523 of file rc_moviefileformat.h.
References mTreatment2, and rmDim.
 { if ( n ) strncpy( mTreatment2, n, rmDim(mTreatment2) ); }
const char* rcMovieFileExpExt::userName () const inline
Definition at line 505 of file rc_moviefileformat.h.
References mUserName.
Referenced by rcEngineImpl::attributes(), rcEngineMovieSaver::closeHdlr(), generateHeader(), log(), and operator<<().
 { return mUserName; }
void rcMovieFileExpExt::userName (const char * n) inline
Definition at line 521 of file rc_moviefileformat.h.
References mUserName, and rmDim.
 { if ( n ) strncpy( mUserName, n, rmDim(mUserName) ); }
bool rcMovieFileExpExt::write (FILE * saveStream) const
Definition at line 720 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), rfPlatformByteOrder(), and rfPlatformByteOrderMark().
Referenced by rcEngineMovieSaver::closeHdlr(), and rcGenMovieFile::flush().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileExpExt *>(this)->fixEndian (rfPlatformByteOrder(rfPlatformByteOrderMark()) );
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("EXP hdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
Member Data Documentation
char rcMovieFileExpExt::mCellType[128] private
Definition at line 540 of file rc_moviefileformat.h.
Referenced by cellType(), and rcMovieFileExpExt().
float rcMovieFileExpExt::mCO2 private
Definition at line 532 of file rc_moviefileformat.h.
Referenced by CO2(), and fixEndian().
char rcMovieFileExpExt::mComment[128] private
Definition at line 542 of file rc_moviefileformat.h.
Referenced by comment(), and rcMovieFileExpExt().
int32 rcMovieFileExpExt::mId private
Definition at line 534 of file rc_moviefileformat.h.
Referenced by fixEndian(), and id().
char rcMovieFileExpExt::mImagingMode[128] private
Definition at line 541 of file rc_moviefileformat.h.
Referenced by imagingMode(), and rcMovieFileExpExt().
float rcMovieFileExpExt::mLensMag private
Definition at line 529 of file rc_moviefileformat.h.
Referenced by fixEndian(), and lensMag().
float rcMovieFileExpExt::mO2 private
Definition at line 533 of file rc_moviefileformat.h.
Referenced by fixEndian(), and O2().
float rcMovieFileExpExt::mOtherMag private
Definition at line 530 of file rc_moviefileformat.h.
Referenced by fixEndian(), and otherMag().
float rcMovieFileExpExt::mTemperature private
Definition at line 531 of file rc_moviefileformat.h.
Referenced by fixEndian(), and temperature().
char rcMovieFileExpExt::mTitle[128] private
Definition at line 536 of file rc_moviefileformat.h.
Referenced by rcMovieFileExpExt(), and title().
char rcMovieFileExpExt::mTreatment1[128] private
Definition at line 538 of file rc_moviefileformat.h.
Referenced by rcMovieFileExpExt(), and treatment1().
char rcMovieFileExpExt::mTreatment2[128] private
Definition at line 539 of file rc_moviefileformat.h.
Referenced by rcMovieFileExpExt(), and treatment2().
char rcMovieFileExpExt::mUserName[128] private
Definition at line 537 of file rc_moviefileformat.h.
Referenced by rcMovieFileExpExt(), and userName().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp