Visible: rcMovieFileIdentifier Class Reference
rcMovieFileIdentifier Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileIdentifier ()
rcMovieFileIdentifier (movieFormatRev rev)
bool isValid () const
void fixEndian ()
movieFormatRev rev () const
const char * magic () const
Private Attributes
char mMagic [12]
uint32 mRev
Detailed Description
Definition at line 78 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileIdentifier::rcMovieFileIdentifier ()
Definition at line 52 of file rc_moviefileformat.cpp.
References mMagic, mRev, and setMagic().
                                              :
         mRev( movieFormatRevLatest )
 {
     setMagic( mMagic, static_cast<movieFormatRev>(mRev) );
}
rcMovieFileIdentifier::rcMovieFileIdentifier (movieFormatRev rev)
Definition at line 58 of file rc_moviefileformat.cpp.
References mMagic, and setMagic().
                                                                  :
         mRev( rev )
 {
     setMagic( mMagic, rev );
}
Member Function Documentation
void rcMovieFileIdentifier::fixEndian ()
Definition at line 85 of file rc_moviefileformat.cpp.
References ByteSwapN, eByteOrderBigEndian, mRev, and rfPlatformByteOrder().
Referenced by rcMovieFileFormat::fixEndian(), and rcMovieFileFormat2::fixEndian().
 {
     // Header is always stored in big endian form
     if ( rfPlatformByteOrder() != eByteOrderBigEndian )
         {
             ByteSwapN (mRev);
         }
 }
bool rcMovieFileIdentifier::isValid () const
Definition at line 64 of file rc_moviefileformat.cpp.
References mMagic, MOVIEFILE_MAGIC_LTH_REV0, MOVIEFILE_MAGIC_LTH_REV2, MOVIEFILE_MAGIC_REV0, MOVIEFILE_MAGIC_REV2, movieFormatInvalid, movieFormatRev0, movieFormatRev1, movieFormatRev2, and mRev.
 {
     if ( mRev == movieFormatInvalid )
         return false;
     switch ( mRev ) {
         case movieFormatRev0:
         case movieFormatRev1:
             if ( strncmp(mMagic, MOVIEFILE_MAGIC_REV0, MOVIEFILE_MAGIC_LTH_REV0) )
                 return false;
             break;
         case movieFormatRev2:
             if ( strncmp(mMagic, MOVIEFILE_MAGIC_REV2, MOVIEFILE_MAGIC_LTH_REV2) )
                 return false;
             break;
     }
     return true;
 }
const char* rcMovieFileIdentifier::magic () const inline
Definition at line 91 of file rc_moviefileformat.h.
References mMagic.
Referenced by rcMovieFileFormat::magic(), and rcMovieFileFormat2::magic().
 { return mMagic; }
movieFormatRev rcMovieFileIdentifier::rev () const inline
Definition at line 90 of file rc_moviefileformat.h.
References mRev.
Referenced by rcMovieFileFormat::rev(), and rcMovieFileFormat2::rev().
 { return static_cast<movieFormatRev>(mRev); }
Member Data Documentation
char rcMovieFileIdentifier::mMagic[12] private
Definition at line 94 of file rc_moviefileformat.h.
Referenced by isValid(), magic(), and rcMovieFileIdentifier().
uint32 rcMovieFileIdentifier::mRev private
Definition at line 95 of file rc_moviefileformat.h.
Referenced by fixEndian(), isValid(), rcMovieFileIdentifier(), and rev().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp