Visible: file_specification Class Reference
file_specification Class Reference
Public Member Functions
file_specification (void)
~file_specification (void)
bool initialise_folder (const std::string &spec)
bool initialise_file (const std::string &spec)
bool simplify (void)
bool make_absolute (const std::string &root=folder_current_full())
bool make_absolute (const file_specification &root)
bool make_relative (const std::string &root=folder_current_full())
bool make_relative (const file_specification &root)
bool relative (void) const
bool absolute (void) const
void set_relative (void)
void set_absolute (void)
const std::string & drive (void) const
std::string & drive (void)
void set_drive (const std::string &drive)
const std::vector< std::string > & path (void) const
std::vector< std::string > & path (void)
void set_path (const std::vector< std::string > &path)
void add_subpath (const std::string &subpath)
unsigned subpath_size (void) const
const std::string & subpath_element (unsigned i) const
void subpath_erase (unsigned i)
const std::string & file (void) const
std::string & file (void)
void set_file (const std::string &file)
std::string image (void) const
otext & print (otext &str) const
Private Attributes
bool m_relative
std::string m_drive
std::vector< std::string > m_path
std::string m_filename
Friends
otext & operator<< (otext &str, const file_specification &spec)
Detailed Description
Definition at line 81 of file file_system.cpp.
Constructor & Destructor Documentation
file_specification::file_specification (void) inline
Definition at line 90 of file file_system.cpp.
 : m_relative(false) {}
file_specification::~file_specification (void) inline
Definition at line 91 of file file_system.cpp.
 {}
Member Function Documentation
bool file_specification::absolute (void) const inline
Definition at line 101 of file file_system.cpp.
References relative().
Referenced by full_path(), image(), is_full_path(), and make_absolute().
 {return !relative();}
void file_specification::add_subpath (const std::string & subpath) inline
Definition at line 113 of file file_system.cpp.
References m_path.
Referenced by folder_down(), folder_up(), and make_absolute().
 {m_path.push_back(subpath);}
const std::string& file_specification::drive (void) const inline
Definition at line 105 of file file_system.cpp.
References m_drive.
Referenced by filespec_elements(), folder_elements(), make_relative(), and set_drive().
 {return m_drive;}
std::string& file_specification::drive (void) inline
Definition at line 106 of file file_system.cpp.
References m_drive.
 {return m_drive;}
const std::string& file_specification::file (void) const inline
Definition at line 118 of file file_system.cpp.
References m_filename.
Referenced by filespec_elements(), make_absolute(), and set_file().
 {return m_filename;}
std::string& file_specification::file (void) inline
Definition at line 119 of file file_system.cpp.
References m_filename.
 {return m_filename;}
std::string file_specification::image (void) const
Definition at line 342 of file file_system.cpp.
References absolute(), is_separator(), m_drive, m_filename, m_path, preferred_separator, relative(), and vector_to_string().
Referenced by folder_down(), folder_up(), full_path(), print(), and relative_path().
 {
   std::string result = m_drive;
   if (absolute())
     result += preferred_separator;
   if (!m_path.empty())
     result += vector_to_string(m_path, std::string(1,preferred_separator));
   else if (relative())
     result += '.';
   // add a trailing / to the last directory element
   if (result.empty() || !is_separator(result[result.size()-1]))
     result += preferred_separator;
   if (!m_filename.empty())
     result += m_filename;
   return result;
 }
bool file_specification::initialise_file (const std::string & spec)
Definition at line 214 of file file_system.cpp.
References initialise_folder(), is_separator(), and m_filename.
Referenced by filespec_elements().
 {
   m_filename.erase();
   // remove last element as the file and then treat the rest as a folder
   unsigned i = spec.size();
   while (--i)
   {
     if (is_separator(spec[i]))
       break;
 #ifdef MSWINDOWS
     // on windows you can say a:fred.txt so the colon separates the path from the filename
     else if (i == 1 && spec[i] == ':')
       break;
 #endif
   }
   bool result = initialise_folder(spec.substr(0,i+1));
   m_filename = spec.substr(i+1,spec.size()-i-1);
   // TODO - some error handling?
   return result;
 }
bool file_specification::initialise_folder (const std::string & spec)
Definition at line 127 of file file_system.cpp.
References is_separator(), m_drive, m_filename, m_path, m_relative, path(), and preferred_separator.
Referenced by folder_down(), folder_elements(), folder_up(), full_path(), initialise_file(), is_full_path(), is_relative_path(), make_absolute(), make_relative(), and relative_path().
 {
   std::string spec = folder_spec;
   m_relative = true;
   m_drive.erase();
   m_path.clear();
   m_filename.erase();
   unsigned i = 0;
 #if defined(MSWINDOWS) || defined(CYGWIN)
   // first split off the drive letter or UNC prefix on Windows - the Cygwin environment supports these too
   if (spec.size() >= 2 && isalpha(spec[0]) && spec[1] == ':')
   {
     // found a drive letter
     i = 2;
     m_drive = spec.substr(0, 2);
     m_relative = false;
     // if there is a drive but no path or a relative path, get the current path for this drive and prepend it to the path
     if (i == spec.size() || !is_separator(spec[i]))
     {
 #ifdef MSWINDOWS
       // getdcwd requires the drive number (1..26) not the letter (A..Z)
       char path [MAX_PATH+1];
       int drivenum = toupper(m_drive[0]) - 'A' + 1;
       if (_getdcwd(drivenum, path, MAX_PATH+1))
       {
         // the path includes the drive so we have the drive info twice
         // need to prepend this absolute path to the spec such that any remaining relative path is still retained
         if (!is_separator(path[strlen(path)-1])) spec.insert(2, 1, preferred_separator);
         spec.insert(2, path+2);
       }
       else
 #endif
       {
         // non-existent drive - fill in just the root directory
         spec.insert(2, 1, preferred_separator);
       }
     }
   }
   else if (spec.size() >= 2 && is_separator(spec[0]) && is_separator(spec[1]))
   {
     // found an UNC prefix
     i = 2;
     // find the end of the prefix by scanning for the next seperator or the end of the spec
     while (i < spec.size() && !is_separator(spec[i])) i++;
     m_drive = spec.substr(0, i);
     m_relative = false;
   }
 #endif
   // chk whether the path is absolute or relative and discard the leading / if absolute
   if (i < spec.size() && is_separator(spec[i]))
   {
     m_relative = false;
     i++;
 #ifdef MSWINDOWS
     // if there's no drive, fill it in on Windows since absolute paths must have a drive
     if (m_drive.empty())
     {
       m_drive += (char)(_getdrive() - 1 + 'A');
       m_drive += ':';
     }
 #endif
   }
   // now extract the path elements - note that a trailing / is not significant since /a/b/c/ === /a/b/c
   // also note that the leading / has been discarded - all paths are relative
   // if absolute() is set, then paths are relative to the drive, else they are relative to the current path
   unsigned start = i;
   while(i <= spec.size())
   {
     if (i == spec.size())
     {
       // path element terminated by the end of the string
       // discard this element if it is zero length because that represents the trailing /
       if (i != start)
         m_path.push_back(spec.substr(start, i-start));
     }
     else if (is_separator(spec[i]))
     {
       // path element terminated by a separator
       m_path.push_back(spec.substr(start, i-start));
       start = i+1;
     }
     i++;
   }
   // TODO - some error handling?
   return true;
 }
bool file_specification::make_absolute (const std::string & root = folder_current_full())
Definition at line 276 of file file_system.cpp.
References absolute(), and initialise_folder().
Referenced by full_path(), make_absolute(), make_relative(), and relative_path().
 {
   // test whether already an absolute path in which case there's nothing to do
   if (absolute()) return true;
   // now simply call the other version of make_absolute
   file_specification rootspec;
   rootspec.initialise_folder(root);
   return make_absolute(rootspec);
 }
bool file_specification::make_absolute (const file_specification & root)
Definition at line 286 of file file_system.cpp.
References absolute(), add_subpath(), file(), make_absolute(), set_file(), simplify(), subpath_element(), and subpath_size().
 {
   // test whether already an absolute path in which case there's nothing to do
   if (absolute()) return true;
   // initialise the result with the root and make the root absolute
   file_specification result = rootspec;
   result.make_absolute();
   // now append this's relative path and filename to the root's absolute path
   for (unsigned i = 0; i < subpath_size(); i++)
     result.add_subpath(subpath_element(i));
   result.set_file(file());
   // now the result is the absolute path, so transfer it to this
   *this = result;
   // and simplify to get rid of any unwanted .. or . elements
   simplify();
   return true;
 }
bool file_specification::make_relative (const std::string & root = folder_current_full())
Definition at line 304 of file file_system.cpp.
References initialise_folder(), and relative().
Referenced by relative_path().
 {
   // test whether already an relative path in which case there's nothing to do
   if (relative()) return true;
   // now simply call the other version of make_relative
   file_specification rootspec;
   rootspec.initialise_folder(root);
   return make_relative(rootspec);
 }
bool file_specification::make_relative (const file_specification & root)
Definition at line 314 of file file_system.cpp.
References drive(), m_path, make_absolute(), path_compare(), relative(), set_drive(), set_relative(), subpath_element(), subpath_erase(), and subpath_size().
 {
   // test whether already an relative path in which case there's nothing to do
   if (relative()) return true;
   // initialise the result with the root and make the root absolute
   file_specification absolute_root = rootspec;
   absolute_root.make_absolute();
   // now compare elements of the absolute root with elements of this to find the common path
   // if the drives are different, no conversion can take place and the result must be absolute, else clear the drive
   if (!path_compare(drive(), absolute_root.drive())) return true;
   set_drive("");
   // first remove leading elements that are identical to the corresponding element in root
   unsigned i = 0;
   while(subpath_size() > 0 && i < absolute_root.subpath_size() && path_compare(subpath_element(0), absolute_root.subpath_element(i)))
   {
     subpath_erase(0);
     i++;
   }
   // now add a .. prefix for every element in root that is different from this
   while (i < absolute_root.subpath_size())
   {
     m_path.insert(m_path.begin(), "..");
     i++;
   }
   set_relative();
   return true;
 }
const std::vector<std::string>& file_specification::path (void) const inline
Definition at line 109 of file file_system.cpp.
References m_path.
Referenced by filespec_elements(), folder_elements(), initialise_folder(), and set_path().
 {return m_path;}
std::vector<std::string>& file_specification::path (void) inline
Definition at line 110 of file file_system.cpp.
References m_path.
 {return m_path;}
otext& file_specification::print (otext & str) const inline
Definition at line 123 of file file_system.cpp.
References image().
 {return str << image();}
bool file_specification::relative (void) const inline
Definition at line 100 of file file_system.cpp.
References m_relative.
Referenced by absolute(), full_path(), image(), is_relative_path(), make_relative(), and relative_path().
 {return m_relative;}
void file_specification::set_absolute (void) inline
Definition at line 103 of file file_system.cpp.
References m_relative.
 {m_relative = false;}
void file_specification::set_drive (const std::string & drive) inline
Definition at line 107 of file file_system.cpp.
References drive(), and m_drive.
Referenced by make_relative().
 {m_drive = drive;}
void file_specification::set_file (const std::string & file) inline
Definition at line 120 of file file_system.cpp.
References file(), and m_filename.
Referenced by make_absolute().
 {m_filename = file;}
void file_specification::set_path (const std::vector< std::string > & path) inline
Definition at line 111 of file file_system.cpp.
References m_path, and path().
 {m_path = path;}
void file_specification::set_relative (void) inline
Definition at line 102 of file file_system.cpp.
References m_relative.
Referenced by make_relative().
 {m_relative = true;}
bool file_specification::simplify (void)
Definition at line 235 of file file_system.cpp.
References m_path, and m_relative.
Referenced by folder_up(), and make_absolute().
 {
   // simplify the path by removing unnecessary . and .. entries - Note that zero-length entries are treated like .
   for (unsigned i = 0; i < m_path.size(); )
   {
     if (m_path[i].empty() || m_path[i].compare(".") == 0)
     {
       // found . or null
       // these both mean do nothing - so simply delete this element
       m_path.erase(m_path.begin()+i);
     }
     else if (m_path[i].compare("..") == 0)
     {
       // found ..
       if (i == 0 && !m_relative)
       {
         // up from the root does nothing so can be deleted
         m_path.erase(m_path.begin()+i);
         i++;
       }
       else if (i == 0 || m_path[i-1].compare("..") == 0)
       {
         // the first element of a relative path or the previous element is .. then keep it
         i++;
       }
       else
       {
         // otherwise delete this element and the previous one
         m_path.erase(m_path.begin()+i);
         m_path.erase(m_path.begin()+i-1);
         i--;
       }
     }
     // keep all other elements
     else
       i++;
   }
   // TODO - error chking?
   return true;
 }
const std::string& file_specification::subpath_element (unsigned i) const inline
Definition at line 115 of file file_system.cpp.
References m_path.
Referenced by make_absolute(), and make_relative().
 {return m_path[i];}
void file_specification::subpath_erase (unsigned i) inline
Definition at line 116 of file file_system.cpp.
References m_path.
Referenced by make_relative().
 {m_path.erase(m_path.begin()+i);}
unsigned file_specification::subpath_size (void) const inline
Definition at line 114 of file file_system.cpp.
References m_path.
Referenced by make_absolute(), and make_relative().
 {return m_path.size();}
Friends And Related Function Documentation
otext& operator<< (otext & str, const file_specification & spec) friend
Definition at line 124 of file file_system.cpp.
 {return spec.print(str);}
Member Data Documentation
std::string file_specification::m_drive private
Definition at line 85 of file file_system.cpp.
Referenced by drive(), image(), initialise_folder(), and set_drive().
std::string file_specification::m_filename private
Definition at line 88 of file file_system.cpp.
Referenced by file(), image(), initialise_file(), initialise_folder(), and set_file().
std::vector<std::string> file_specification::m_path private
Definition at line 87 of file file_system.cpp.
Referenced by add_subpath(), image(), initialise_folder(), make_relative(), path(), set_path(), simplify(), subpath_element(), subpath_erase(), and subpath_size().
bool file_specification::m_relative private
Definition at line 84 of file file_system.cpp.
Referenced by initialise_folder(), relative(), set_absolute(), set_relative(), and simplify().
The documentation for this class was generated from the following file:
include/stlplus/file_system.cpp