Visible: _debug_trace Class Reference
_debug_trace Class Reference
#include <include/stlplus/debug.hpp>
Public Member Functions
_debug_trace (const char *f, int l, const char *fn)
~_debug_trace (void)
const char * file (void) const
int line (void) const
bool debug (void) const
void debug_on (int l, bool recurse)
void debug_off (int l)
void prefix (int l) const
void report (int l, const std::string &message) const
void report (const std::string &message) const
void error (int l, const std::string &message) const
void error (const std::string &message) const
void stackdump (int l, const std::string &message) const
void stackdump (const std::string &message) const
void stackdump (void) const
Private Member Functions
void do_report (int l, const std::string &message) const
void do_report (const std::string &message) const
_debug_trace (const _debug_trace &)
_debug_trace & operator= (const _debug_trace &)
Private Attributes
const char * m_file
int m_line
const char * m_function
unsigned m_depth
const _debug_trace * m_last
bool m_dbg
bool m_old
Detailed Description
Definition at line 68 of file debug.hpp.
Constructor & Destructor Documentation
_debug_trace::_debug_trace (const char * f, int l, const char * fn)
Definition at line 56 of file debug.cpp.
References debug(), debug_set, debug_trace_depth, filename_part(), m_dbg, m_depth, m_file, m_function, m_old, match_wildcard(), report(), and unknown_function.
                                                                :
   m_file(f), m_line(l), m_function(fn ? fn : unknown_function),
   m_depth(0), m_last(debug_last), m_dbg(false), m_old(false)
 {
   if (!debug_read)
   {
     debug_read = true;
     debug_match = getenv("DEBUG");
     debug_recurse = getenv("DEBUG_LOCAL") == 0;
   }
   m_dbg = debug_set || (debug_match && (!debug_match[0] || match_wildcard(debug_match, filename_part(m_file))));
   m_old = debug_set;
   if (m_dbg && debug_recurse)
     debug_set = true;
   m_depth = ++debug_trace_depth;
   debug_last = this;
   if (debug()) report(std::string("entering ") + (m_function ? m_function : unknown_function));
 }
_debug_trace::~_debug_trace (void)
Definition at line 75 of file debug.cpp.
References debug(), debug_trace_depth, m_last, m_old, and report().
 {
   if (debug()) report("leaving");
   --debug_trace_depth;
   debug_set = m_old;
   debug_last = m_last;
 }
_debug_trace::_debug_trace (const _debug_trace &) private
Member Function Documentation
bool _debug_trace::debug (void) const
Definition at line 93 of file debug.cpp.
References debug_global, and m_dbg.
Referenced by _debug_trace(), debug_off(), and ~_debug_trace().
 {
   return m_dbg || debug_global;
 }
void _debug_trace::debug_off (int l)
Definition at line 107 of file debug.cpp.
References debug(), m_dbg, m_old, and report().
 {
   if (debug()) report(l, std::string("debug off"));
   m_dbg = false;
   debug_set = m_old;
 }
void _debug_trace::debug_on (int l, bool recurse)
Definition at line 98 of file debug.cpp.
References debug_set, m_dbg, m_old, and report().
 {
   m_dbg = true;
   m_old = debug_set;
   if (recurse)
     debug_set = true;
   report(l, std::string("debug on") + (recurse ? " recursive" : ""));
 }
void _debug_trace::do_report (int l, const std::string & message) const private
Definition at line 119 of file debug.cpp.
References prefix().
Referenced by do_report(), error(), report(), and stackdump().
 {
   prefix(l);
   fprintf(stderr, "%s\n", message.c_str());
   fflush(stderr);
 }
void _debug_trace::do_report (const std::string & message) const private
Definition at line 126 of file debug.cpp.
References do_report(), and m_line.
 {
   do_report(m_line, message);
 }
void _debug_trace::error (int l, const std::string & message) const
Definition at line 141 of file debug.cpp.
References do_report().
Referenced by error().
 {
   do_report(l, "ERROR: " + message);
 }
void _debug_trace::error (const std::string & message) const
Definition at line 146 of file debug.cpp.
References error(), and m_line.
 {
   error(m_line, message);
 }
const char * _debug_trace::file (void) const
Definition at line 83 of file debug.cpp.
References m_file.
 {
   return m_file;
 }
int _debug_trace::line (void) const
Definition at line 88 of file debug.cpp.
References m_line.
 {
   return m_line;
 }
_debug_trace& _debug_trace::operator= (const _debug_trace &) private
void _debug_trace::prefix (int l) const
Definition at line 114 of file debug.cpp.
References filename_part(), m_depth, m_file, m_function, and unknown_function.
Referenced by do_report().
 {
   fprintf(stderr, "%s:%i:[%i]%s ", filename_part(m_file).c_str(), l, m_depth, m_function ? m_function : unknown_function);
 }
void _debug_trace::report (int l, const std::string & message) const
Definition at line 131 of file debug.cpp.
References do_report().
Referenced by _debug_trace(), debug_off(), debug_on(), report(), and ~_debug_trace().
 {
   do_report(l, message);
 }
void _debug_trace::report (const std::string & message) const
Definition at line 136 of file debug.cpp.
References m_line, and report().
 {
   report(m_line, message);
 }
void _debug_trace::stackdump (int l, const std::string & message) const
Definition at line 151 of file debug.cpp.
References do_report(), and stackdump().
Referenced by _debug_assert_fail().
 {
   do_report(l, message);
   stackdump();
 }
void _debug_trace::stackdump (const std::string & message) const
Definition at line 157 of file debug.cpp.
References m_line, and stackdump().
 {
   stackdump(m_line, message);
 }
void _debug_trace::stackdump (void) const
Definition at line 162 of file debug.cpp.
References m_last.
Referenced by stackdump().
 {
   for (const _debug_trace* item = this; item; item = item->m_last)
     item->do_report("...called from here");
 }
Member Data Documentation
bool _debug_trace::m_dbg private
Definition at line 93 of file debug.hpp.
Referenced by _debug_trace(), debug(), debug_off(), and debug_on().
unsigned _debug_trace::m_depth private
Definition at line 91 of file debug.hpp.
Referenced by _debug_trace(), and prefix().
const char* _debug_trace::m_file private
Definition at line 88 of file debug.hpp.
Referenced by _debug_trace(), file(), and prefix().
const char* _debug_trace::m_function private
Definition at line 90 of file debug.hpp.
Referenced by _debug_trace(), and prefix().
const _debug_trace* _debug_trace::m_last private
Definition at line 92 of file debug.hpp.
Referenced by stackdump(), and ~_debug_trace().
int _debug_trace::m_line private
Definition at line 89 of file debug.hpp.
Referenced by do_report(), error(), line(), report(), and stackdump().
bool _debug_trace::m_old private
Definition at line 94 of file debug.hpp.
Referenced by _debug_trace(), debug_off(), debug_on(), and ~_debug_trace().
The documentation for this class was generated from the following files:
include/stlplus/debug.hpp
include/stlplus/debug.cpp