Visible: rcHistoStats Class Reference
rcHistoStats Class Reference
#include <include/visual/rc_histstats.h>
Public Member Functions
rcHistoStats ()
rcHistoStats (const rcWindow &image, int32 bins=256)
rcHistoStats (vector< uint32 > &histogram, bool xown=false)
uint32 n () const
uint32 bins () const
double mean () const
int32 mode () const
int32 median () const
float interpolatedMedian () const
int32 min (const int32 discardPels=0) const
int32 max (const int32 discardPels=0) const
int32 inverseCum (int percent) const
double sDev () const
double entropy () const
double var () const
void stretchMapUs (vector< uint16 > &map, const int32 leftDicard, const int32 rightDiscard) const
const vector< uint32 > & histogram () const
void pdf (vector< float > &p) const
void integral (vector< uint32 > &hist) const
void integralPdf (vector< float > &ph) const
void equalizationMap (vector< uint8 > &hist) const
Private Member Functions
void computeNsamp ()
long computeInverseCum (int percent)
void computeMoments ()
Private Attributes
vector< uint32 > histogram_
uint8 computedMoments_
uint8 computedIC_
uint8 computedMode_
uint32 n_
long mode_
double mean_
double sDev_
double var_
vector< long > ic_
uint32 bins_
Friends
ostream & operator<< (ostream &o, const rcHistoStats &p)
Detailed Description
Definition at line 25 of file rc_histstats.h.
Constructor & Destructor Documentation
rcHistoStats::rcHistoStats ()
Definition at line 37 of file rc_histstats.cpp.
 {
 }
rcHistoStats::rcHistoStats (const rcWindow & image, int32 bins = 256)
Definition at line 41 of file rc_histstats.cpp.
References computeNsamp(), rcWindow::depth(), rcWindow::height(), histogram_, rcPixel16, rcPixel8, rfGenDepth8Histogram(), rmAssert, rcWindow::rowPointer(), and rcWindow::width().
   : computedMoments_(0), computedIC_(0), computedMode_(0), n_(0),
     mode_(0), mean_(0), sDev_(0), var_(0), ic_(101), bins_(bins)
 {
   if (src.depth() == rcPixel8)
     {
       rmAssert(src.depth() == rcPixel8);
       histogram_.resize(bins);
       rfGenDepth8Histogram (src, histogram_);
     }
   else if (src.depth() == rcPixel16)
     {
       rmAssert(src.depth() == rcPixel16);
       static uint32 zu (0);
       histogram_.resize (bins, zu);
       uint32 lastRow = src.height() - 1, row = 0;
       const uint32 opsPerLoop = 8;
       uint32 unrollCnt = src.width() / opsPerLoop;
       uint32 unrollRem = src.width() % opsPerLoop;
       for ( ; row <= lastRow; row++)
     {
       const uint16* pixelPtr = (uint16 *) src.rowPointer(row);
       for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
         {
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
           histogram_[ (*pixelPtr)]++; pixelPtr++;
         }
       for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++)
         {
           histogram_[ (*pixelPtr)]++; pixelPtr++;
         }
     }
     }
   computeNsamp();
 }
rcHistoStats::rcHistoStats (vector< uint32 > & histogram, bool xown = false)
Definition at line 129 of file rc_histstats.cpp.
References computeNsamp(), histogram(), and histogram_.
   : computedMoments_(0), computedIC_(0), computedMode_(0), n_(0),
     mode_(0), mean_(0), sDev_(0), var_(0), ic_(101)
 {
   if( xown )  // take ownership
     {
       histogram_.swap(histogram);
       histogram.resize(0);
     }
   else  // make copy
     histogram_ = histogram;
   computeNsamp();
 }
Member Function Documentation
uint32 rcHistoStats::bins () const inline
Definition at line 56 of file rc_histstats.h.
Referenced by operator<<(), and stretchMapUs().
 { return bins_; }
long rcHistoStats::computeInverseCum (int percent) private
Definition at line 249 of file rc_histstats.cpp.
References computedIC_, histogram_, ic_, n_, and percent().
 {
   // fill in ic_
   double one_percent = (double)n_ / 100.;
   double percent;
   uint32 sum = 0;
   long nextIndex = 0;
   long i = 0;
   long endI = histogram_.size();
   long j;
   if (n_)   // if no samples, leave ic_ all zeros
     while( i < endI )
     {
       if( histogram_[i] )
       {
         ic_[100] = i;
         sum += histogram_[i];
         percent = (double)sum / one_percent;
         if (percent > nextIndex)
         {
           for( j=nextIndex; j<percent; j++ ) ic_[j] = i;
           nextIndex = j;
         }
       }
       i++;
     }
   // validate inverseCum...
   computedIC_ = 1;
   return ic_[p];
 }
void rcHistoStats::computeMoments () private
Definition at line 285 of file rc_histstats.cpp.
References computedMoments_, histogram_, mean_, n_, sDev_, and var_.
 {
   if(n_)
   {
     long endI = histogram_.size();
     long i;
     uint32 sum = 0;
     double temp;
     // Accumulate the sum = SUM( i*hist[i] )
     for( i=0; i<endI; i++ )
       sum += histogram_[i] * i;
     // Calculate mean
     mean_ = (double)sum / n_;
     // Calculate variance
     if(n_ > 1)
     {
       for( i=0; i<endI; i++ )
         if( histogram_[i] )
         {
           temp = i - mean_;
           var_ += temp * temp * histogram_[i];
         }
       var_ /= (double)(n_-1);
     }
     else
       var_ = 0.0;
     // Calculate sDev
     sDev_ = sqrt(var_);
   }
   else
     mean_ = var_ = sDev_ = 0.0;
   computedMoments_ = 1;
 }
void rcHistoStats::computeNsamp () private
Definition at line 323 of file rc_histstats.cpp.
References histogram_, ic_, and n_.
Referenced by rcHistoStats().
 {
     // compute nSamp
     long tooHiSub = histogram_.size();
     long i;
     for(i=0; i<tooHiSub; i++ )
         n_ += histogram_[i];
     for(i = 0; i < 101; i++)
         ic_[i] = 0;
 }
double rcHistoStats::entropy () const
Definition at line 335 of file rc_histstats.cpp.
References histogram_, and n_.
 {
   double Sum (n_);
   double Entropy = 0.0;
   long tooHiSub = histogram_.size();
   long i;
   for(i=0; i<tooHiSub; i++ )
     {
       const double probability = histogram_[i] / Sum;
       if( probability > 1e-16 )
     {
       Entropy += - probability * log( probability ) / log( 2.0 );
     }
     }
   return Entropy;
 }
void rcHistoStats::equalizationMap (vector< uint8 > & hist) const
Definition at line 356 of file rc_histstats.cpp.
References histogram_, and n_.
 {
   uint32 tooHiSub = histogram_.size();
   uint32 sum  = 0;
   for (uint32 i = 0; i < tooHiSub; i++)
     {
       sum += histogram_[i];
       map [i] = (sum * 255) / n_;
     }
 }
const vector<uint32>& rcHistoStats::histogram () const inline
Definition at line 140 of file rc_histstats.h.
Referenced by rcSpatialPyramid< 2 >::gradientProcess(), operator<<(), rcHistoStats(), rcMutualInfoGrouping::rcMutualInfoGrouping(), and rcWithinGroupInv::rcWithinGroupInv().
 { return histogram_;}
void rcHistoStats::integral (vector< uint32 > & hist) const
Definition at line 92 of file rc_histstats.cpp.
References histogram_.
 {
   uint32 tooHiSub = histogram_.size();
   assert (tooHiSub && tooHiSub == ahist.size());
   uint32 sum  = 0;
   for (uint32 i = 0; i < tooHiSub; i++)
     {
       sum += histogram_[i];
       ahist[i] = sum;
     }
 }
void rcHistoStats::integralPdf (vector< float > & ph) const
Definition at line 105 of file rc_histstats.cpp.
References histogram_, and n().
 {
   uint32 tooHiSub = histogram_.size();
   assert (tooHiSub && tooHiSub == ph.size());
   uint32 sum  = 0;
   for (uint32 i = 0; i < tooHiSub; i++)
     {
       sum += histogram_[i];
       ph[i] = (float) sum / (float) n();
     }
 }
float rcHistoStats::interpolatedMedian () const
Definition at line 191 of file rc_histstats.cpp.
References histogram_, and inverseCum().
 {
   float med = (float) histogram_ [inverseCum(50)];
   float sum = (float) histogram_ [inverseCum(51)] +
     (float) histogram_ [inverseCum(49)] + med;
   float interp = (((float) inverseCum(51)) * histogram_ [inverseCum(51)]) +
     (((float) inverseCum(49)) * histogram_ [inverseCum(49)]) +
     (((float) inverseCum(50)) * histogram_ [inverseCum(50)]);
   return interp/sum;
 }
int32 rcHistoStats::inverseCum (int percent) const
Definition at line 31 of file rc_histstats.cpp.
References computedIC_, ic_, and percent().
Referenced by interpolatedMedian(), max(), median(), and min().
 {
   if( computedIC_ ) return ic_[percent];
   else return ((rcHistoStats* const)this)->computeInverseCum(percent);
 }
int32 rcHistoStats::max (const int32 discardPels = 0) const
Definition at line 219 of file rc_histstats.cpp.
References histogram_, inverseCum(), and n_.
Referenced by operator<<(), rfImageConvert168(), and stretchMapUs().
 {
   if (!discardPels)
     return inverseCum(100);
   int32 sum (0);
   long i = histogram_.size() - 1;
   if (n_)
     while (i >= 0 && sum < discardPels)
       {
     sum += histogram_[i--];
       }
   return i;
 }
double rcHistoStats::mean () const
Definition at line 146 of file rc_histstats.cpp.
References computedMoments_, and mean_.
Referenced by rcEngineImpl::entropyTracker(), operator<<(), and rcGaussKernel2D< T, ksize >::rcGaussKernel2D().
 {
   if( computedMoments_ ) return mean_;
   ((rcHistoStats* const)this)->computeMoments();
   return mean_;
 }
int32 rcHistoStats::median () const
Definition at line 186 of file rc_histstats.cpp.
References inverseCum().
Referenced by rcKinetoscope::epiMotionField(), rcSpatialPyramid< 2 >::gradientProcess(), and operator<<().
 {
   return inverseCum(50);
 }
int32 rcHistoStats::min (const int32 discardPels = 0) const
Definition at line 203 of file rc_histstats.cpp.
References histogram_, inverseCum(), and n_.
Referenced by operator<<(), rfImageConvert168(), and stretchMapUs().
 {
   if (!discardPels)
     return inverseCum(0);
   int32 sum (0);
   long i = 0;
   long endI = histogram_.size();
   if (n_)
     while (i < endI && sum < discardPels)
       {
     sum += histogram_[i++];
       }
   return i;
 }
int32 rcHistoStats::mode (void) const
Definition at line 153 of file rc_histstats.cpp.
References computedIC_, computedMode_, histogram_, ic_, and mode_.
Referenced by stretchMapUs().
 {
   if( computedMode_ ) return mode_;
   // compute mode, make valid, return mode_
   long startIndex;
   long lastIndex;
   if( computedIC_ )
   {
     startIndex = ic_[0];
     lastIndex = ic_[100];
   }
   else
   {
     lastIndex = histogram_.size() - 1;
   }
   long i, indexOfMax;
   uint32 maxCountSoFar;
   vector<uint32>::const_iterator pBinI;
   for( i = 1,
        indexOfMax = 0,
        pBinI = histogram_.begin(),
        maxCountSoFar = *pBinI;
        i<=lastIndex;
        i++ )
     if( *++pBinI > maxCountSoFar ) maxCountSoFar = *pBinI, indexOfMax = i;
   ((rcHistoStats* const)this)->computedMode_ = 1;
   return ((rcHistoStats* const)this)->mode_ = indexOfMax;
 }
uint32 rcHistoStats::n () const inline
Definition at line 49 of file rc_histstats.h.
Referenced by integralPdf(), operator<<(), pdf(), and rcGaussKernel2D< T, ksize >::rcGaussKernel2D().
 { return n_; }
void rcHistoStats::pdf (vector< float > & p) const
Definition at line 118 of file rc_histstats.cpp.
References histogram_, and n().
 {
   uint32 tooHiSub = histogram_.size();
   assert (tooHiSub && tooHiSub == ph.size());
   for (uint32 i = 0; i < tooHiSub; i++)
     {
       ph[i] = (float)  histogram_[i]/ (float) n();
     }
 }
double rcHistoStats::sDev () const
Definition at line 234 of file rc_histstats.cpp.
References computedMoments_, and sDev_.
 {
   if( computedMoments_ ) return sDev_;
   ((rcHistoStats* const)this)->computeMoments();
   return sDev_;
 }
void rcHistoStats::stretchMapUs (vector< uint16 > & map, const int32 leftDicard, const int32 rightDiscard) const
Definition at line 368 of file rc_histstats.cpp.
References bins(), max(), min(), mode(), rmABS, rmAssert, and rmMax.
 {
   int32 minVal = min (leftDiscard);
   int32 maxVal = max (rightDiscard);
   int32 modeVal = mode ();
   int32 val = rmMax ((maxVal - modeVal), (modeVal - minVal));
   rmAssert (val >= 0 & val < bins());
   static uint32 zus (0);
   map.resize (bins(), zus);
   uint16 *mPtr = &map[minVal];
   for (uint32 i = minVal; i < maxVal; i++)
     {
       int32 m = rmABS (m - i);
       m = (m * 255) / val;
       *mPtr++ = (uint16) m;
     }
 }
double rcHistoStats::var () const
Definition at line 241 of file rc_histstats.cpp.
References computedMoments_, and var_.
 {
   if( computedMoments_ ) return var_;
   ((rcHistoStats* const)this)->computeMoments();
   return var_;
 }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcHistoStats & p) friend
Definition at line 9 of file rc_histstats.cpp.
 {
     o << "{" << endl << "Mean: " << p.mean() << ",Median  " << p.median() <<
       "Min:  " << p.min() << "Max: " << p.max() << "Bins " << p.bins () << endl;
     uint32 i = 0;
     if (p.n())
       {
     while (i < p.bins ())
       {
         uint32 pd (p.histogram()[i]);
         if (pd)
           {
         cerr << "[" << i << "]: " << pd << "," << (float) pd / (float) p.n() << endl;
           }
         i++;
       }
       }
     return o;
 }
Member Data Documentation
uint32 rcHistoStats::bins_ private
Definition at line 189 of file rc_histstats.h.
uint8 rcHistoStats::computedIC_ private
Definition at line 179 of file rc_histstats.h.
Referenced by computeInverseCum(), inverseCum(), and mode().
uint8 rcHistoStats::computedMode_ private
Definition at line 180 of file rc_histstats.h.
Referenced by mode().
uint8 rcHistoStats::computedMoments_ private
Definition at line 178 of file rc_histstats.h.
Referenced by computeMoments(), mean(), sDev(), and var().
vector<uint32> rcHistoStats::histogram_ private
Definition at line 175 of file rc_histstats.h.
Referenced by computeInverseCum(), computeMoments(), computeNsamp(), entropy(), equalizationMap(), integral(), integralPdf(), interpolatedMedian(), max(), min(), mode(), pdf(), and rcHistoStats().
vector<long> rcHistoStats::ic_ private
Definition at line 188 of file rc_histstats.h.
Referenced by computeInverseCum(), computeNsamp(), inverseCum(), and mode().
double rcHistoStats::mean_ private
Definition at line 185 of file rc_histstats.h.
Referenced by computeMoments(), and mean().
long rcHistoStats::mode_ private
Definition at line 184 of file rc_histstats.h.
Referenced by mode().
uint32 rcHistoStats::n_ private
Definition at line 183 of file rc_histstats.h.
Referenced by computeInverseCum(), computeMoments(), computeNsamp(), entropy(), equalizationMap(), max(), and min().
double rcHistoStats::sDev_ private
Definition at line 186 of file rc_histstats.h.
Referenced by computeMoments(), and sDev().
double rcHistoStats::var_ private
Definition at line 187 of file rc_histstats.h.
Referenced by computeMoments(), and var().
The documentation for this class was generated from the following files:
include/visual/rc_histstats.h
src/visual/code/rc_histstats.cpp