Visible: rcMovieConverterOptionsRfy Class Reference
rcMovieConverterOptionsRfy Class Reference
#include <include/visual/rc_movieconverter.h>
Public Member Functions
rcMovieConverterOptionsRfy ()
rcMovieConverterOptionsRfy (const rcMovieConverterOptions &o)
virtual ~rcMovieConverterOptionsRfy ()
rcChannelConversion channelConversion () const
movieFormatRev rev () const
void channelConversion (const rcChannelConversion &v)
void rev (const movieFormatRev &v)
Public Member Functions inherited from rcMovieConverterOptions
rcMovieConverterOptions ()
rcMovieConverterOptions (const rcMovieConverterOptions &o)
virtual ~rcMovieConverterOptions ()
float frameInterval () const
int32 firstFrameIndex () const
int32 frameCount () const
int32 frameOffset () const
int32 samplePeriod () const
const std::string & creator () const
const rcRect & clipRect () const
bool overWrite () const
bool reversePixels () const
bool verbose () const
void frameInterval (const float &v)
void firstFrameIndex (const int32 &v)
void frameCount (const int32 &v)
void frameOffset (const int32 &v)
void samplePeriod (const int32 &v)
void creator (const std::string &v)
void clipRect (const rcRect &v)
void overWrite (bool v)
void reversePixels (bool v)
void verbose (bool v)
Private Attributes
rcChannelConversion mChannelConversion
movieFormatRev mRev
Additional Inherited Members
Protected Attributes inherited from rcMovieConverterOptions
float mFrameInterval
int32 mFirstFrameIndex
int32 mFrameCount
int32 mFrameOffset
int32 mSamplePeriod
std::string mCreator
rcRect mClipRect
bool mOverWrite
bool mReversePixels
bool mVerbose
Detailed Description
Definition at line 88 of file rc_movieconverter.h.
Constructor & Destructor Documentation
rcMovieConverterOptionsRfy::rcMovieConverterOptionsRfy ()
Definition at line 102 of file rc_movieconverter.cpp.
                                                        :
         rcMovieConverterOptions::rcMovieConverterOptions(),
         mChannelConversion( rcSelectAverage ),
         mRev( movieFormatRevLatest )
 {
}
rcMovieConverterOptionsRfy::rcMovieConverterOptionsRfy (const rcMovieConverterOptions & o)
Definition at line 109 of file rc_movieconverter.cpp.
                                                                                          :
         rcMovieConverterOptions( o ),
         mChannelConversion( rcSelectAverage ),
         mRev( movieFormatRevLatest )
 {
}
rcMovieConverterOptionsRfy::~rcMovieConverterOptionsRfy () virtual
Definition at line 116 of file rc_movieconverter.cpp.
 {
 }
Member Function Documentation
rcChannelConversion rcMovieConverterOptionsRfy::channelConversion () const inline
Definition at line 97 of file rc_movieconverter.h.
References mChannelConversion.
Referenced by rcMovieConverterToRfy::createRfyMovie(), rcExperimentImpl::exportMovie(), operator<<(), and rfConvertTwoMovies().
 { return mChannelConversion; }
void rcMovieConverterOptionsRfy::channelConversion (const rcChannelConversion & v) inline
Definition at line 101 of file rc_movieconverter.h.
References mChannelConversion.
 { mChannelConversion = v; }
movieFormatRev rcMovieConverterOptionsRfy::rev () const inline
Definition at line 98 of file rc_movieconverter.h.
References mRev.
Referenced by rcMovieConverterToRfy::createRfyMovie(), operator<<(), and rfConvertTwoMovies().
 { return mRev; }
void rcMovieConverterOptionsRfy::rev (const movieFormatRev & v) inline
Definition at line 102 of file rc_movieconverter.h.
References mRev.
 { mRev = v; }
Member Data Documentation
rcChannelConversion rcMovieConverterOptionsRfy::mChannelConversion private
Definition at line 105 of file rc_movieconverter.h.
Referenced by channelConversion().
movieFormatRev rcMovieConverterOptionsRfy::mRev private
Definition at line 106 of file rc_movieconverter.h.
Referenced by rev().
The documentation for this class was generated from the following files:
include/visual/rc_movieconverter.h
src/visual/code/rc_movieconverter.cpp