Visible: rcTrackInfo Class Reference
rcTrackInfo Class Reference
#include <include/visUI/rc_trackmanager.h>
Public Member Functions
bool isEnabled (void) const
QPen getPen (void) const
rcTrackType type (void) const
rcTrack * track (void) const
Private Member Functions
rcTrackInfo (void)
rcTrackInfo (bool enabled, const QPen &pen, rcTrackType t, rcTrack *p)
Private Attributes
bool _isEnabled
QPen _pen
rcTrackType _type
rcTrack * _track
Friends
class rcTrackManager
Detailed Description
Definition at line 19 of file rc_trackmanager.h.
Constructor & Destructor Documentation
rcTrackInfo::rcTrackInfo (void) inline private
Definition at line 40 of file rc_trackmanager.h.
         : _isEnabled( true )
         , _pen( QPen(Qt::black) )
         , _type( eMaxTrack )
         , _track( NULL )
     {}
rcTrackInfo::rcTrackInfo (bool enabled, const QPen & pen, rcTrackType t, rcTrack * p) inline private
Definition at line 46 of file rc_trackmanager.h.
         : _isEnabled( enabled )
         , _pen( pen )
         , _type( t )
         , _track ( p )
     {}
Member Function Documentation
QPen rcTrackInfo::getPen (void) const inline
Definition at line 27 of file rc_trackmanager.h.
References _pen.
Referenced by rcMonitor::displayScalarFocusArea(), and rcTrackRenderInfo::rcTrackRenderInfo().
 { return _pen; }
bool rcTrackInfo::isEnabled (void) const inline
Definition at line 24 of file rc_trackmanager.h.
References _isEnabled.
Referenced by rcMonitor::displayTrackFocus(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTrackManager::hiliteTracks(), and rcTrackRenderInfo::rcTrackRenderInfo().
 { return _isEnabled; }
rcTrack* rcTrackInfo::track (void) const inline
Definition at line 33 of file rc_trackmanager.h.
References _track.
Referenced by rcScalarTrackWidget::setEnabled(), and rcTrackManager::setTrackEnabled().
 { return _track; }
rcTrackType rcTrackInfo::type (void) const inline
Definition at line 30 of file rc_trackmanager.h.
References _type.
Referenced by rcTrackManager::hiliteTracks(), and rcTrackManager::setTrackEnabled().
 { return _type; }
Friends And Related Function Documentation
friend class rcTrackManager friend
Definition at line 37 of file rc_trackmanager.h.
Member Data Documentation
bool rcTrackInfo::_isEnabled private
Definition at line 53 of file rc_trackmanager.h.
Referenced by rcTrackManager::getTrackInfo(), isEnabled(), rcTrackManager::isTrackEnabled(), and rcTrackManager::setTrackEnabled().
QPen rcTrackInfo::_pen private
Definition at line 54 of file rc_trackmanager.h.
Referenced by getPen(), rcTrackManager::getTrackPen(), rcTrackManager::setHiliteTrack(), rcTrackManager::setTrackColor(), and rcTrackManager::setTrackPen().
rcTrack* rcTrackInfo::_track private
Definition at line 56 of file rc_trackmanager.h.
Referenced by rcTrackManager::setTrackColor(), and track().
rcTrackType rcTrackInfo::_type private
Definition at line 55 of file rc_trackmanager.h.
Referenced by type().
The documentation for this class was generated from the following file:
include/visUI/rc_trackmanager.h