Visible: rcMenuBar Class Reference
rcMenuBar Class Reference
#include <include/visUI/rc_menubar.h>
Public Slots
void updateState (rcExperimentState state)
void about ()
void help ()
void inputSource (int i)
void updateAnalysisRect (const rcRect &rect)
void doSave ()
void doExport ()
void doExportMovie ()
void doExportNativeMovie ()
void doOpen ()
void doOpenSettings ()
void requestCellInfoDisplay ()
Public Member Functions
rcMenuBar (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
~rcMenuBar ()
Private Attributes
Q3PopupMenu * _fileMenu
Q3PopupMenu * _analysisMenu
Q3PopupMenu * _captureMenu
Q3PopupMenu * _viewMenu
Q3TextBrowser * _helpBrowser
rcExperimentState _lastState
int _fileNewId
int _fileOpenId
int _fileOpenSettingsId
int _fileSaveId
int _fileExportId
int _movieExportId
int _movieNativeExportId
int _fileCloseId
int _fileImportImagesId
int _dirImportImagesId
int _fileImportMovieId
int _fileImportSTKId
int _fileQuitId
int _analysisAnalyzeId
int _fileSaveMovieId
int _viewTrackingGLId
int _viewCellInfoId
Detailed Description
Definition at line 18 of file rc_menubar.h.
Constructor & Destructor Documentation
rcMenuBar::rcMenuBar (QWidget * parent = 0, const char * name = 0, Qt::WFlags f = 0)
Definition at line 28 of file rc_menubar.cpp.
References _analysisAnalyzeId, _analysisMenu, _captureMenu, _dirImportImagesId, _fileCloseId, _fileExportId, _fileImportImagesId, _fileImportMovieId, _fileMenu, _fileNewId, _fileOpenId, _fileOpenSettingsId, _fileQuitId, _fileSaveId, _fileSaveMovieId, _helpBrowser, _lastState, _movieExportId, _movieNativeExportId, _viewMenu, about(), doExport(), doExportMovie(), doExportNativeMovie(), doOpen(), doOpenSettings(), doSave(), eExperimentEmpty, rcModelDomain::getModelDomain(), help(), inputSource(), rcUNUSED, updateAnalysisRect(), and updateState().
     : QMenuBar( parent, name )
 {
     rcUNUSED( f );
     _lastState = eExperimentEmpty;
     setSeparator( QMenuBar::InWindowsStyle );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     // create and populate the file menu
     _fileMenu = new Q3PopupMenu( this );
     _fileNewId  = _fileMenu->insertItem( "&New Experiment" , domain , SLOT( requestNewApp() ) , tr("CTRL+Key_N") );
     _fileOpenId = _fileMenu->insertItem( "&Open Experiment...", this , SLOT( doOpen() ) , tr("CTRL+Key_O "));
     _fileOpenSettingsId = _fileMenu->insertItem( "&Open Experiment Template...", this , SLOT( doOpenSettings() ) , tr("CTRL+SHIFT+Key_O"));
     _fileMenu->insertSeparator();
     _fileCloseId = _fileMenu->insertItem( "&Close", domain , SLOT( requestClose() ) , tr("CTRL+Key_W" ));
     _fileSaveId = _fileMenu->insertItem( "&Save As...", this , SLOT( doSave() ) , tr("(CTRL+Key_S" ));
     _movieNativeExportId = _fileMenu->insertItem( "&Save Movie As...", this , SLOT( doExportNativeMovie() ), tr("(CTRL+SHIFT+Key_S" ));
     _fileMenu->insertSeparator();
     _fileExportId = _fileMenu->insertItem( "&Export As CSV...", this , SLOT( doExport() ) ,  tr("CTRL+Key_E" ));
     _movieExportId = _fileMenu->insertItem( "&Export Movie As QuickTime...", this , SLOT( doExportMovie() ) , tr("(CTRL+SHIFT+Key_E" ));
     _fileMenu->insertSeparator();
     //    _fileImportLastMovieId = _fileMenu->insertItem( "&Import Last Movie...", domain , SLOT( requestLastMovieImport() ) , CTRL+Key_L );
     _fileImportMovieId = _fileMenu->insertItem( "&Import Movie...", domain , SLOT( requestMovieImport() ) ,  tr("CTRL+Key_I" ));
     _fileImportMovieId = _fileMenu->insertItem( "&Import STK...", domain , SLOT( requestSTKImport() ) ,  tr("CTRL+Key_U" ));
     _fileImportImagesId = _fileMenu->insertItem( "&Import Image Sequence...", domain , SLOT( requestImageImport() ) ,  tr("(CTRL+SHIFT+Key_I" ));
     _dirImportImagesId = _fileMenu->insertItem( "&Import Tiff Directory...", domain , SLOT( requestTifDirImport() ) ,  tr("(CTRL+SHIFT+Key_T" ));
     _fileQuitId = _fileMenu->insertItem( "&Quit", qApp   , SLOT( closeAllWindows() ) ,  tr("(CTRL+Key_Q" ));
     // create and populate the help menu
     Q3PopupMenu *help = new Q3PopupMenu( this );
     Q_CHECK_PTR( help );
     help->insertItem( "&About", this, SLOT( about() ),  tr("(CTRL+Key_H" ));
     help->insertItem( "&Help" , this, SLOT( help() ) ,  tr("(CTRL+Key_Question" ));
     // create and populate the analysis menu
     _analysisMenu = new Q3PopupMenu( this );
     _analysisAnalyzeId  = _analysisMenu->insertItem( "&Analyze" , domain , SLOT( requestProcess() ) ,  tr("(CTRL+Key_Z" ));
     _analysisMenu->setItemEnabled( _analysisAnalyzeId  , false );
     // create and populate the view menu
     _viewMenu = new Q3PopupMenu( this );
 //    _viewTrackingGLId  = _viewMenu->insertItem( "&Measurement Inspector" , domain , SLOT( requestTrackingDisplayGL() ) ,  tr("(CTRL+Key_T" ));
 //    _viewMenu->setItemEnabled( _viewTrackingGLId, true );
 //     _viewCellInfoId = _viewMenu->insertItem( "&Locomotive Body Text" , this , SLOT( requestCellInfoDisplay() ) ,  tr("(CTRL+Key_X" ));
 //    _viewMenu->setItemEnabled( _viewCellInfoId, true );
     // create and populate the capture menu
     _captureMenu = new Q3PopupMenu( this );
     _fileSaveMovieId = _captureMenu->insertItem( "&Capture Movie...", domain , SLOT( requestMovieSave() ) ,  tr("(CTRL+Key_M" ));
     _captureMenu->setItemEnabled( _fileSaveMovieId  , false );
     // Populate the menu bar
     insertItem( "&File", _fileMenu );
     insertItem( "&Analysis", _analysisMenu );
     insertItem( "&Capture", _captureMenu );
     insertItem( "&View", _viewMenu );
     insertItem( "&Help", help );
     // create help browser
     _helpBrowser = new Q3TextBrowser( this );
     _helpBrowser->setFrameStyle( Q3Frame::Panel | Q3Frame::Sunken );
     _helpBrowser->resize (640, 400);
     // Model connections
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateInputSource( int ) ) ,
              this   , SLOT( inputSource( int ) ) );
     connect( domain , SIGNAL( updateAnalysisRect( const rcRect& ) ) ,
              this   , SLOT( updateAnalysisRect( const rcRect& ) ) );
     // in case we don't get an initial signal
     updateState( eExperimentEmpty );
     //    requestTrackingDisplayGL();
 }
rcMenuBar::~rcMenuBar ()
Definition at line 110 of file rc_menubar.cpp.
 {
 }
Member Function Documentation
void rcMenuBar::about () slot
Definition at line 222 of file rc_menubar.cpp.
References cAppBuildDate, cAppName, cVersionName, rcModelDomain::getLicenseExpirationTime(), rcModelDomain::getModelDomain(), NULL, and version().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     std::string tmp = domain->getLicenseExpirationTime();
     QString expirationDate (tmp.c_str());
     QString svnversion ("Beta Release ");
     QString title( cAppName );
     QString version( cVersionName );
     QString richTitle =  "<h2>" + title + " " + version + "</h2>";
     QString buildDate = "<p>Build: ";
     buildDate += svnversion;
     buildDate += cAppBuildDate;
     QString expDate =   "<p>License expiration date: " + expirationDate;
     QString copyRight = "<p>Copyright (c) 2002-2009 Reify Corp. All rights reserved.";
     QString otherRight = "<p>Copyright (c) 1987-1992 Numerical Recipes Software";
     QString text = "<qt><center>" + richTitle + "</center>" + buildDate + expDate + copyRight + otherRight  + "</qt>";
     QMessageBox::about( NULL, title, text );
 }
void rcMenuBar::doExport () slot
Definition at line 298 of file rc_menubar.cpp.
References eExperimentCSVFormat, rcModelDomain::getModelDomain(), and rcModelDomain::requestSave().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->requestSave( eExperimentCSVFormat );
 }
void rcMenuBar::doExportMovie () slot
Definition at line 305 of file rc_menubar.cpp.
References eExperimentQuickTimeMovieFormat, rcModelDomain::getModelDomain(), and rcModelDomain::requestSave().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->requestSave( eExperimentQuickTimeMovieFormat );
 }
void rcMenuBar::doExportNativeMovie () slot
Definition at line 312 of file rc_menubar.cpp.
References eExperimentNativeMovieFormat, rcModelDomain::getModelDomain(), and rcModelDomain::requestSave().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->requestSave( eExperimentNativeMovieFormat );
 }
void rcMenuBar::doOpen () slot
Definition at line 319 of file rc_menubar.cpp.
References eExperimentImportAll, rcModelDomain::getModelDomain(), and rcModelDomain::requestOpen().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->requestOpen( eExperimentImportAll );
 }
void rcMenuBar::doOpenSettings () slot
Definition at line 326 of file rc_menubar.cpp.
References eExperimentImportExperimentSettings, rcModelDomain::getModelDomain(), and rcModelDomain::requestOpen().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->requestOpen( eExperimentImportExperimentSettings );
 }
void rcMenuBar::doSave () slot
Definition at line 291 of file rc_menubar.cpp.
References eExperimentNativeFormat, rcModelDomain::getModelDomain(), and rcModelDomain::requestSave().
Referenced by rcMenuBar().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     domain->requestSave( eExperimentNativeFormat );
 }
void rcMenuBar::help () slot
Definition at line 265 of file rc_menubar.cpp.
References cAppName.
Referenced by rcMenuBar().
 {
   QString title = cAppName;
   QString cmd;
   string docindexhtml (qApp->argv()[0]);
   string slash( "/" );
   uint32 s = docindexhtml.find_last_of( slash ); // |Visible
   if ( s != std::string::npos )
     {
       uint32 len = s + 1;
       if ( s > 0 )
     docindexhtml = docindexhtml.substr(0, len );
     }
   docindexhtml += "../Documentation/index.html";
   // Background task
   cmd.sprintf("open %s", docindexhtml.c_str());
   // Launch a new application instance
   system( cmd.latin1() );
 }
void rcMenuBar::inputSource (int i) slot
Definition at line 244 of file rc_menubar.cpp.
References _analysisAnalyzeId, _analysisMenu, _captureMenu, _fileSaveMovieId, _lastState, and eExperimentEmpty.
Referenced by rcMenuBar().
 {
     // Hack alert: value 0 is file, greater than 0 camera
     if ( i > 0 ) {
         // Camera input
         _analysisMenu->setItemEnabled( _analysisAnalyzeId  , false );
     if (_lastState == eExperimentEmpty)
       _captureMenu->setItemEnabled( _fileSaveMovieId , true );
     } else {
         // File input
         _captureMenu->setItemEnabled( _fileSaveMovieId , false );
     }
 }
void rcMenuBar::requestCellInfoDisplay () slot
Definition at line 333 of file rc_menubar.cpp.
 {
 //    rcCellInfoWidget* w = new rcCellInfoWidget( 0 );
   //  w->show();
 }
void rcMenuBar::updateAnalysisRect (const rcRect & rect) slot
Definition at line 258 of file rc_menubar.cpp.
References _analysisAnalyzeId, _analysisMenu, _lastState, eExperimentRunning, rcRectangle< T >::height(), and rcRectangle< T >::width().
Referenced by rcMenuBar().
 {
     // Enable/disable analyze command based on focus area size
     _analysisMenu->setItemEnabled( _analysisAnalyzeId,  rect.width() > 0 && rect.height() > 0 && _lastState != eExperimentRunning );
 }
void rcMenuBar::updateState (rcExperimentState state) slot
Definition at line 116 of file rc_menubar.cpp.
References _analysisAnalyzeId, _analysisMenu, _captureMenu, _dirImportImagesId, _fileCloseId, _fileExportId, _fileImportImagesId, _fileImportMovieId, _fileImportSTKId, _fileMenu, _fileNewId, _fileOpenId, _fileOpenSettingsId, _fileQuitId, _fileSaveId, _fileSaveMovieId, _lastState, _movieExportId, _movieNativeExportId, _viewMenu, eExperimentEmpty, eExperimentEnded, eExperimentLocked, eExperimentPlayback, and eExperimentRunning.
Referenced by rcMenuBar().
 {
     switch( state ) {
     case eExperimentEmpty:          // experiment was created but not run
         _fileMenu->setEnabled( true );
         _fileMenu->setItemEnabled( _fileNewId  , true );
         _fileMenu->setItemEnabled( _fileOpenId , true );
         _fileMenu->setItemEnabled( _fileOpenSettingsId , true );
         _fileMenu->setItemEnabled( _fileCloseId, true );
         _fileMenu->setItemEnabled( _fileSaveId , false );
         _fileMenu->setItemEnabled( _fileExportId , false );
         _fileMenu->setItemEnabled( _movieExportId , false );
         _fileMenu->setItemEnabled( _movieNativeExportId , false );
         _fileMenu->setItemEnabled( _fileQuitId , true );
         _fileMenu->setItemEnabled( _fileImportImagesId , true );
         _fileMenu->setItemEnabled( _fileImportMovieId , true );
         _fileMenu->setItemEnabled( _fileImportSTKId , true );
         _fileMenu->setItemEnabled( _dirImportImagesId , true);
         _analysisMenu->setEnabled( true );
         _analysisMenu->setItemEnabled( _analysisAnalyzeId  , false );
         _captureMenu->setEnabled( true );
         _captureMenu->setItemEnabled( _fileSaveMovieId , false );
         _viewMenu->setEnabled( true );
 //        _viewMenu->setItemEnabled( _viewTrackingGLId, true );
 //        _viewMenu->setItemEnabled( _viewCellInfoId, true );
         break;
     case eExperimentRunning:        // experiment is running
     case eExperimentPlayback:       // experiment is playing back
         _fileMenu->setItemEnabled( _fileNewId  , false );
         _fileMenu->setItemEnabled( _fileOpenId , false );
         _fileMenu->setItemEnabled( _fileOpenSettingsId , false );
         _fileMenu->setItemEnabled( _fileCloseId, false );
         _fileMenu->setItemEnabled( _fileSaveId , false );
         _fileMenu->setItemEnabled( _fileExportId , false );
         _fileMenu->setItemEnabled( _movieExportId , false );
         _fileMenu->setItemEnabled( _movieNativeExportId , false );
         _fileMenu->setItemEnabled( _fileImportImagesId , false );
         _fileMenu->setItemEnabled( _dirImportImagesId , false);
         _fileMenu->setItemEnabled( _fileImportMovieId , false );
         _fileMenu->setItemEnabled( _fileImportSTKId , false );
         _fileMenu->setItemEnabled( _fileQuitId , true );
     //        _fileMenu->setItemEnabled( _fileImportLastMovieId , false );
         _analysisMenu->setItemEnabled( _analysisAnalyzeId  , false );
         _captureMenu->setItemEnabled( _fileSaveMovieId , false );
 //        _viewMenu->setItemEnabled( _viewTrackingGLId, false );
 //        _viewMenu->setItemEnabled( _viewCellInfoId, false );
         break;
     case eExperimentEnded:          // experiment has ended
         _fileMenu->setItemEnabled( _fileNewId  , true );
         _fileMenu->setItemEnabled( _fileOpenId , true );
         _fileMenu->setItemEnabled( _fileOpenSettingsId , true );
         _fileMenu->setItemEnabled( _fileCloseId, true );
         _fileMenu->setItemEnabled( _fileSaveId , true );
         _fileMenu->setItemEnabled( _fileExportId , true );
         _fileMenu->setItemEnabled( _movieExportId , true );
         _fileMenu->setItemEnabled( _movieNativeExportId , true );
         _fileMenu->setItemEnabled( _fileQuitId , true );
         _fileMenu->setItemEnabled( _fileImportImagesId , false );
         _fileMenu->setItemEnabled( _dirImportImagesId , false);
         _fileMenu->setItemEnabled( _fileImportMovieId , false );
         _fileMenu->setItemEnabled( _fileImportSTKId , false );
     //        _fileMenu->setItemEnabled( _fileImportLastMovieId , true );
         _captureMenu->setItemEnabled( _fileSaveMovieId , false);
    //     _viewMenu->setItemEnabled( _viewTrackingGLId, true );
 //        _viewMenu->setItemEnabled( _viewCellInfoId, true );
         break;
     case eExperimentLocked:         // experiment has ended and been saved
         _fileMenu->setItemEnabled( _fileNewId  , true );
         _fileMenu->setItemEnabled( _fileOpenId , true );
         _fileMenu->setItemEnabled( _fileOpenSettingsId , true );
         _fileMenu->setItemEnabled( _fileCloseId, true );
         _fileMenu->setItemEnabled( _fileSaveId , true );
         _fileMenu->setItemEnabled( _fileExportId , true );
         _fileMenu->setItemEnabled( _movieExportId , true );
         _fileMenu->setItemEnabled( _movieNativeExportId , true );
         _fileMenu->setItemEnabled( _fileQuitId , true );
         _fileMenu->setItemEnabled( _fileImportImagesId , false );
         _fileMenu->setItemEnabled( _dirImportImagesId , false);
         _fileMenu->setItemEnabled( _fileImportMovieId , false );
         _fileMenu->setItemEnabled( _fileImportSTKId , false );
     //        _fileMenu->setItemEnabled( _fileImportLastMovieId , true );
         _captureMenu->setItemEnabled( _fileSaveMovieId , false);
  //       _viewMenu->setItemEnabled( _viewTrackingGLId, true );
 //        _viewMenu->setItemEnabled( _viewCellInfoId, true );
         break;
     default:
         break;
     }
     _lastState = state;
 }
Member Data Documentation
int rcMenuBar::_analysisAnalyzeId private
Definition at line 70 of file rc_menubar.h.
Referenced by inputSource(), rcMenuBar(), updateAnalysisRect(), and updateState().
Q3PopupMenu* rcMenuBar::_analysisMenu private
Definition at line 49 of file rc_menubar.h.
Referenced by inputSource(), rcMenuBar(), updateAnalysisRect(), and updateState().
Q3PopupMenu* rcMenuBar::_captureMenu private
Definition at line 50 of file rc_menubar.h.
Referenced by inputSource(), rcMenuBar(), and updateState().
int rcMenuBar::_dirImportImagesId private
Definition at line 65 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileCloseId private
Definition at line 63 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileExportId private
Definition at line 60 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileImportImagesId private
Definition at line 64 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileImportMovieId private
Definition at line 66 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileImportSTKId private
Definition at line 67 of file rc_menubar.h.
Referenced by updateState().
Q3PopupMenu* rcMenuBar::_fileMenu private
Definition at line 48 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileNewId private
Definition at line 56 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileOpenId private
Definition at line 57 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileOpenSettingsId private
Definition at line 58 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileQuitId private
Definition at line 68 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileSaveId private
Definition at line 59 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_fileSaveMovieId private
Definition at line 72 of file rc_menubar.h.
Referenced by inputSource(), rcMenuBar(), and updateState().
Q3TextBrowser* rcMenuBar::_helpBrowser private
Definition at line 52 of file rc_menubar.h.
Referenced by rcMenuBar().
rcExperimentState rcMenuBar::_lastState private
Definition at line 53 of file rc_menubar.h.
Referenced by inputSource(), rcMenuBar(), updateAnalysisRect(), and updateState().
int rcMenuBar::_movieExportId private
Definition at line 61 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_movieNativeExportId private
Definition at line 62 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_viewCellInfoId private
Definition at line 77 of file rc_menubar.h.
Q3PopupMenu* rcMenuBar::_viewMenu private
Definition at line 51 of file rc_menubar.h.
Referenced by rcMenuBar(), and updateState().
int rcMenuBar::_viewTrackingGLId private
Definition at line 75 of file rc_menubar.h.
The documentation for this class was generated from the following files:
include/visUI/rc_menubar.h
src/visible/qt/rc_menubar.cpp