Visible: rcPositionSegmentIteratorImpl Class Reference
rcPositionSegmentIteratorImpl Class Reference
Public Member Functions
rcPositionSegmentIteratorImpl (rcPositionTrackImpl *track, const rcTimestamp &position, rcMutex &mutex)
virtual rcTimestamp getSegmentLength (void)
virtual rcTimestamp getSegmentOffset (void)
virtual rcTimestamp getTrackOffset (void)
virtual int32 getSegmentIndex (void)
virtual rcTimestamp getSegmentStart (void)
virtual rcTimestamp getSegmentStartAbsolute (void)
virtual bool hasNextSegment (bool lock)
virtual uint32 getSegmentCount (void)
virtual bool contains (const rcTimestamp &time)
virtual void lock ()
virtual void unlock ()
virtual void reset (bool lock)
virtual void release (void)
virtual rcRect getFocus (void)
virtual void advance (const rcTimestamp &amount, bool lock)
virtual bool advance (int32 offset, bool lock)
virtual rcFPair getValue (void)
Public Member Functions inherited from rcPositionSegmentIterator
virtual ~rcPositionSegmentIterator ()
Public Member Functions inherited from rcSegmentIterator
virtual ~rcSegmentIterator ()
Private Member Functions
virtual void setCurrentValue (void)
Private Attributes
rcSegmentIteratorImpl _iter
rcPositionTrackImpl * _track
rcFPair _currentValue
Detailed Description
Definition at line 12 of file rc_positiontrackimpl.cpp.
Constructor & Destructor Documentation
rcPositionSegmentIteratorImpl::rcPositionSegmentIteratorImpl (rcPositionTrackImpl * track, const rcTimestamp & position, rcMutex & mutex) inline
Definition at line 15 of file rc_positiontrackimpl.cpp.
References _iter, lock(), rcSegmentIteratorImpl::mutex(), rmAssert, and setCurrentValue().
                                                   : _iter( track, position, mutex ),
                                                     _track( track ),
                                                     _currentValue( rcFPair() )
     {
         rcLock lock( _iter.mutex() );
         rmAssert( track );
         setCurrentValue();
     }
Member Function Documentation
virtual void rcPositionSegmentIteratorImpl::advance (const rcTimestamp & amount, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 118 of file rc_positiontrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             } else {
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             }
         }
virtual bool rcPositionSegmentIteratorImpl::advance (int32 offset, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 131 of file rc_positiontrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 bool result = _iter.advanceNoLock( offset );
                 setCurrentValue();
                 return result;
             } else {
                 bool result = _iter.advanceNoLock( offset );
                 setCurrentValue();
                 return result;
             }
         }
virtual bool rcPositionSegmentIteratorImpl::contains (const rcTimestamp & time) inline virtual
Implements rcSegmentIterator.
Definition at line 77 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::contains().
         {
             return _iter.contains( time );
         }
virtual rcRect rcPositionSegmentIteratorImpl::getFocus (void) inline virtual
Implements rcSegmentIterator.
Definition at line 112 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getFocus().
         {
             return _iter.getFocus();
         }
virtual uint32 rcPositionSegmentIteratorImpl::getSegmentCount (void) inline virtual
Implements rcSegmentIterator.
Definition at line 71 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentCount().
         {
             return _iter.getSegmentCount();
         }
virtual int32 rcPositionSegmentIteratorImpl::getSegmentIndex (void) inline virtual
Implements rcSegmentIterator.
Definition at line 47 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentIndex().
         {
             return _iter.getSegmentIndex();
         }
virtual rcTimestamp rcPositionSegmentIteratorImpl::getSegmentLength (void) inline virtual
Implements rcSegmentIterator.
Definition at line 29 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentLength().
         {
             return _iter.getSegmentLength();
         }
virtual rcTimestamp rcPositionSegmentIteratorImpl::getSegmentOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 35 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentOffset().
         {
             return _iter.getSegmentOffset();
         }
virtual rcTimestamp rcPositionSegmentIteratorImpl::getSegmentStart (void) inline virtual
Implements rcSegmentIterator.
Definition at line 53 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStart().
         {
             return _iter.getSegmentStart();
         }
virtual rcTimestamp rcPositionSegmentIteratorImpl::getSegmentStartAbsolute (void) inline virtual
Implements rcSegmentIterator.
Definition at line 59 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStartAbsolute().
         {
             return _iter.getSegmentStartAbsolute();
         }
virtual rcTimestamp rcPositionSegmentIteratorImpl::getTrackOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 41 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getTrackOffset().
         {
             return _iter.getTrackOffset();
         }
virtual rcFPair rcPositionSegmentIteratorImpl::getValue (void) inline virtual
Implements rcPositionSegmentIterator.
Definition at line 148 of file rc_positiontrackimpl.cpp.
References _currentValue.
         {
             return _currentValue;
         }
virtual bool rcPositionSegmentIteratorImpl::hasNextSegment (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 65 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::hasNextSegment().
         {
             return _iter.hasNextSegment( lock );
         }
virtual void rcPositionSegmentIteratorImpl::lock () inline virtual
Implements rcSegmentIterator.
Definition at line 83 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::lock().
Referenced by advance(), and rcPositionSegmentIteratorImpl().
         {
             _iter.lock();
         }
virtual void rcPositionSegmentIteratorImpl::release (void) inline virtual
Implements rcSegmentIterator.
Definition at line 106 of file rc_positiontrackimpl.cpp.
         {
             delete this;
         }
virtual void rcPositionSegmentIteratorImpl::reset (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 95 of file rc_positiontrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::lock(), rcSegmentIteratorImpl::reset(), setCurrentValue(), and rcSegmentIteratorImpl::unlock().
         {
             if ( lock )
                 _iter.lock();
             _iter.reset( false );
             setCurrentValue();
             if ( lock )
                 _iter.unlock();
         }
virtual void rcPositionSegmentIteratorImpl::setCurrentValue (void) inline private virtual
Definition at line 155 of file rc_positiontrackimpl.cpp.
References _currentValue, _iter, rcPositionTrackImpl::_segments, _track, rcSegmentIteratorImpl::getSegmentIndex(), and rcPositionTrackImpl::segments().
Referenced by advance(), rcPositionSegmentIteratorImpl(), and reset().
         {
             int32 index = _iter.getSegmentIndex();
             if ( index >= 0 && static_cast<uint32>(index) < _track->segments() )
                 _currentValue = _track->_segments[index].mValue;
             else
                 _currentValue = rcFPair();
         }
virtual void rcPositionSegmentIteratorImpl::unlock () inline virtual
Implements rcSegmentIterator.
Definition at line 89 of file rc_positiontrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::unlock().
         {
             _iter.unlock();
         }
Member Data Documentation
rcFPair rcPositionSegmentIteratorImpl::_currentValue private
Definition at line 166 of file rc_positiontrackimpl.cpp.
Referenced by getValue(), and setCurrentValue().
rcSegmentIteratorImpl rcPositionSegmentIteratorImpl::_iter private
Definition at line 164 of file rc_positiontrackimpl.cpp.
Referenced by advance(), contains(), getFocus(), getSegmentCount(), getSegmentIndex(), getSegmentLength(), getSegmentOffset(), getSegmentStart(), getSegmentStartAbsolute(), getTrackOffset(), hasNextSegment(), lock(), rcPositionSegmentIteratorImpl(), reset(), setCurrentValue(), and unlock().
rcPositionTrackImpl* rcPositionSegmentIteratorImpl::_track private
Definition at line 165 of file rc_positiontrackimpl.cpp.
Referenced by setCurrentValue().
The documentation for this class was generated from the following file:
src/visible/src/rc_positiontrackimpl.cpp