Visible: rcSegmentIterator Class Reference
rcSegmentIterator Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcSegmentIterator ()
virtual rcTimestamp getSegmentLength (void)=0
virtual rcTimestamp getSegmentOffset (void)=0
virtual rcTimestamp getTrackOffset (void)=0
virtual int32 getSegmentIndex (void)=0
virtual rcTimestamp getSegmentStart (void)=0
virtual rcTimestamp getSegmentStartAbsolute (void)=0
virtual bool hasNextSegment (bool lock=true)=0
virtual uint32 getSegmentCount (void)=0
virtual bool contains (const rcTimestamp &time)=0
virtual rcRect getFocus (void)=0
virtual void advance (const rcTimestamp &amount, bool lock=true)=0
virtual bool advance (int32 offset, bool lock=true)=0
virtual void lock ()=0
virtual void unlock ()=0
virtual void reset (bool lock=true)=0
virtual void release (void)=0
Detailed Description
Definition at line 537 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcSegmentIterator::~rcSegmentIterator () inline virtual
Definition at line 541 of file rc_model.h.
 {};
Member Function Documentation
virtual void rcSegmentIterator::advance (const rcTimestamp & amount, bool lock = true) pure virtual
Implemented in rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, rcGraphicsSegmentIteratorImpl, and rcSegmentIteratorImpl.
Referenced by rcMonitor::buildPositionPath(), rcTrackManager::copyTrackToClipboard(), rcTimeline::getFrameTime(), rcTimeline::paintFrameTicks(), rcTimeline::paintScalarTrack(), rcExporter::rcExporter(), and rcScalarTrackWidget::updateTrackDisplay().
virtual bool rcSegmentIterator::advance (int32 offset, bool lock = true) pure virtual
Implemented in rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, rcGraphicsSegmentIteratorImpl, and rcSegmentIteratorImpl.
virtual bool rcSegmentIterator::contains (const rcTimestamp & time) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcMonitor::addGraphics(), rcCSVExporter::exportTracks(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::getPosition(), getTrackValue(), rcImageCanvasGL::getTrackValue(), rcMonitor::paintScalarTrackFocus(), rcNativeExporter::produceResults(), and rcScalarTrackWidget::updateTrackDisplay().
virtual rcRect rcSegmentIterator::getFocus (void) pure virtual
Implemented in rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, rcGraphicsSegmentIteratorImpl, and rcSegmentIteratorImpl.
Referenced by rcCSVExporter::exportTracks(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::getPosition(), and rcMonitor::paintScalarTrackFocus().
virtual uint32 rcSegmentIterator::getSegmentCount (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcMonitor::buildPositionPath(), rcExporter::init(), and rcNativeExporter::produceResults().
virtual int32 rcSegmentIterator::getSegmentIndex (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcTrackManager::copyTrackToClipboard(), operator<<(), rcTimeline::paintScalarTrack(), and rcScalarTrackWidget::updateTrackDisplay().
virtual rcTimestamp rcSegmentIterator::getSegmentLength (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcTimeline::getSegmentLength(), and operator<<().
virtual rcTimestamp rcSegmentIterator::getSegmentOffset (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by operator<<().
virtual rcTimestamp rcSegmentIterator::getSegmentStart (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by operator<<(), rcTimeline::paintFrameTicks(), and rcExporter::rcExporter().
virtual rcTimestamp rcSegmentIterator::getSegmentStartAbsolute (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcMonitor::buildPositionPath(), operator<<(), and rcTimeline::paintScalarTrack().
virtual rcTimestamp rcSegmentIterator::getTrackOffset (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcTimeline::getFrameTime(), and operator<<().
virtual bool rcSegmentIterator::hasNextSegment (bool lock = true) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcTrackManager::copyTrackToClipboard().
virtual void rcSegmentIterator::lock () pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcMonitor::buildPositionPath(), rcTrackManager::copyTrackToClipboard(), rcTimeline::paintFrameTicks(), and rcTimeline::paintScalarTrack().
virtual void rcSegmentIterator::release (void) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
virtual void rcSegmentIterator::reset (bool lock = true) pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcExporter::rcExporter().
virtual void rcSegmentIterator::unlock () pure virtual
Implemented in rcSegmentIteratorImpl, rcVideoSegmentIteratorImpl, rcPositionSegmentIteratorImpl, rcScalarSegmentIteratorImpl, and rcGraphicsSegmentIteratorImpl.
Referenced by rcMonitor::buildPositionPath(), rcTrackManager::copyTrackToClipboard(), rcTimeline::paintFrameTicks(), and rcTimeline::paintScalarTrack().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h