Visible: rcProgressIndicator Class Reference
rcProgressIndicator Class Reference abstract
#include <include/util/rc_types.h>
Public Member Functions
virtual ~rcProgressIndicator ()
virtual bool progress (uint32 percentComplete)=0
virtual bool progress (double percentComplete)=0
Detailed Description
Definition at line 42 of file rc_types.h.
Constructor & Destructor Documentation
virtual rcProgressIndicator::~rcProgressIndicator () inline virtual
Definition at line 45 of file rc_types.h.
 {}
Member Function Documentation
virtual bool rcProgressIndicator::progress (uint32 percentComplete) pure virtual
Implemented in rcModelProgress, rcEngineProgress, and rcConversionProgress.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcMuscleTracker::calculateCellLocation(), rcMovieConverterToRfy::createRfyMovie(), rcXMLParser::endDocument(), rcCSVExporter::exportExperiment(), rcNativeExporter::exportExperiment(), rcCSVExporter::exportTracks(), rcNativeImporter::importExperiment(), output(), rcNativeImporter::parseExperimentData(), rcNativeExporter::produceResults(), rcSimilarator::progressNotification::progressNotification(), rfOptoKineticEnergy(), rcXMLParser::startDocument(), rcXMLParser::startElement(), rcVideoCache::tocLoadFromFrames(), and rcSimilarator::progressNotification::update().
virtual bool rcProgressIndicator::progress (double percentComplete) pure virtual
Implemented in rcModelProgress, rcEngineProgress, and rcConversionProgress.
The documentation for this class was generated from the following file:
include/util/rc_types.h