Visible: rcMovieConverterOptions Class Reference
rcMovieConverterOptions Class Reference
#include <include/visual/rc_movieconverter.h>
Public Member Functions
rcMovieConverterOptions ()
rcMovieConverterOptions (const rcMovieConverterOptions &o)
virtual ~rcMovieConverterOptions ()
float frameInterval () const
int32 firstFrameIndex () const
int32 frameCount () const
int32 frameOffset () const
int32 samplePeriod () const
const std::string & creator () const
const rcRect & clipRect () const
bool overWrite () const
bool reversePixels () const
bool verbose () const
void frameInterval (const float &v)
void firstFrameIndex (const int32 &v)
void frameCount (const int32 &v)
void frameOffset (const int32 &v)
void samplePeriod (const int32 &v)
void creator (const std::string &v)
void clipRect (const rcRect &v)
void overWrite (bool v)
void reversePixels (bool v)
void verbose (bool v)
Protected Attributes
float mFrameInterval
int32 mFirstFrameIndex
int32 mFrameCount
int32 mFrameOffset
int32 mSamplePeriod
std::string mCreator
rcRect mClipRect
bool mOverWrite
bool mReversePixels
bool mVerbose
Detailed Description
Definition at line 39 of file rc_movieconverter.h.
Constructor & Destructor Documentation
rcMovieConverterOptions::rcMovieConverterOptions ()
Definition at line 66 of file rc_movieconverter.cpp.
                                                  :
         mFrameInterval( -1.0 ),
         mFirstFrameIndex( 0 ),
         mFrameCount( -1 ),
         mFrameOffset( 0 ),
         mSamplePeriod( 1 ),
         mCreator( "Unknown" ),
         mClipRect( rcRect() ),
         mOverWrite( true ),
         mReversePixels( false ),
         mVerbose( true )
 {
}
rcMovieConverterOptions::rcMovieConverterOptions (const rcMovieConverterOptions & o)
Definition at line 80 of file rc_movieconverter.cpp.
                                                                                    :
         mFrameInterval( o.frameInterval() ),
         mFirstFrameIndex( o.firstFrameIndex() ),
         mFrameCount( o.frameCount() ),
         mFrameOffset( o.frameOffset() ),
         mSamplePeriod( o.samplePeriod() ),
         mCreator( o.creator() ),
         mClipRect( o.clipRect() ),
         mOverWrite( o.overWrite() ),
         mReversePixels( o.reversePixels() ),
         mVerbose( o.verbose() )
 {
}
rcMovieConverterOptions::~rcMovieConverterOptions () virtual
Definition at line 94 of file rc_movieconverter.cpp.
 {
 }
Member Function Documentation
const rcRect& rcMovieConverterOptions::clipRect () const inline
Definition at line 55 of file rc_movieconverter.h.
References mClipRect.
Referenced by rcMovieConverter::clippedFrame(), rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), and rcExperimentDomainImpl::saveExperiment().
 { return mClipRect; }
void rcMovieConverterOptions::clipRect (const rcRect & v) inline
Definition at line 67 of file rc_movieconverter.h.
References mClipRect.
 { mClipRect = v; }
const std::string& rcMovieConverterOptions::creator () const inline
Definition at line 54 of file rc_movieconverter.h.
References mCreator.
Referenced by rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), rfConvertTwoMovies(), and rcExperimentDomainImpl::saveExperiment().
 { return mCreator; }
void rcMovieConverterOptions::creator (const std::string & v) inline
Definition at line 66 of file rc_movieconverter.h.
References mCreator.
 { mCreator = v; }
int32 rcMovieConverterOptions::firstFrameIndex () const inline
Definition at line 50 of file rc_movieconverter.h.
References mFirstFrameIndex.
Referenced by rcMovieConverterToRfy::convert(), rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), rfConvertTwoMovies(), and rcExperimentDomainImpl::saveExperiment().
 { return mFirstFrameIndex; }
void rcMovieConverterOptions::firstFrameIndex (const int32 & v) inline
Definition at line 62 of file rc_movieconverter.h.
References mFirstFrameIndex.
 { mFirstFrameIndex = v; }
int32 rcMovieConverterOptions::frameCount () const inline
Definition at line 51 of file rc_movieconverter.h.
References mFrameCount.
Referenced by rcMovieConverterToRfy::convert(), rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), rfConvertTwoMovies(), and rcExperimentDomainImpl::saveExperiment().
 { return mFrameCount; }
void rcMovieConverterOptions::frameCount (const int32 & v) inline
Definition at line 63 of file rc_movieconverter.h.
References mFrameCount.
 { mFrameCount = v; }
float rcMovieConverterOptions::frameInterval () const inline
Definition at line 49 of file rc_movieconverter.h.
References mFrameInterval.
Referenced by rcMovieConverterToRfy::convert(), rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), and rfConvertTwoMovies().
 { return mFrameInterval; }
void rcMovieConverterOptions::frameInterval (const float & v) inline
Definition at line 61 of file rc_movieconverter.h.
References mFrameInterval.
 { mFrameInterval = v; }
int32 rcMovieConverterOptions::frameOffset () const inline
Definition at line 52 of file rc_movieconverter.h.
References mFrameOffset.
Referenced by rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), and rfConvertTwoMovies().
 { return mFrameOffset; }
void rcMovieConverterOptions::frameOffset (const int32 & v) inline
Definition at line 64 of file rc_movieconverter.h.
References mFrameOffset.
 { mFrameOffset = v; }
bool rcMovieConverterOptions::overWrite () const inline
Definition at line 56 of file rc_movieconverter.h.
References mOverWrite.
Referenced by rcMovieConverterToRfy::createRfyMovie(), and operator<<().
 { return mOverWrite; }
void rcMovieConverterOptions::overWrite (bool v) inline
Definition at line 68 of file rc_movieconverter.h.
References mOverWrite.
 { mOverWrite = v; }
bool rcMovieConverterOptions::reversePixels () const inline
Definition at line 57 of file rc_movieconverter.h.
References mReversePixels.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), and rfConvertTwoMovies().
 { return mReversePixels; }
void rcMovieConverterOptions::reversePixels (bool v) inline
Definition at line 69 of file rc_movieconverter.h.
References mReversePixels.
 { mReversePixels = v; }
int32 rcMovieConverterOptions::samplePeriod () const inline
Definition at line 53 of file rc_movieconverter.h.
References mSamplePeriod.
Referenced by rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), operator<<(), rfConvertMovie(), and rfConvertTwoMovies().
 { return mSamplePeriod; }
void rcMovieConverterOptions::samplePeriod (const int32 & v) inline
Definition at line 65 of file rc_movieconverter.h.
References mSamplePeriod.
 { mSamplePeriod = v; }
bool rcMovieConverterOptions::verbose () const inline
Definition at line 58 of file rc_movieconverter.h.
References mVerbose.
Referenced by rfConvertMovie(), and rfConvertTwoMovies().
 { return mVerbose; }
void rcMovieConverterOptions::verbose (bool v) inline
Definition at line 70 of file rc_movieconverter.h.
References mVerbose.
 { mVerbose = v; }
Member Data Documentation
rcRect rcMovieConverterOptions::mClipRect protected
Definition at line 79 of file rc_movieconverter.h.
Referenced by clipRect().
std::string rcMovieConverterOptions::mCreator protected
Definition at line 78 of file rc_movieconverter.h.
Referenced by creator().
int32 rcMovieConverterOptions::mFirstFrameIndex protected
Definition at line 74 of file rc_movieconverter.h.
Referenced by firstFrameIndex().
int32 rcMovieConverterOptions::mFrameCount protected
Definition at line 75 of file rc_movieconverter.h.
Referenced by frameCount().
float rcMovieConverterOptions::mFrameInterval protected
Definition at line 73 of file rc_movieconverter.h.
Referenced by frameInterval().
int32 rcMovieConverterOptions::mFrameOffset protected
Definition at line 76 of file rc_movieconverter.h.
Referenced by frameOffset().
bool rcMovieConverterOptions::mOverWrite protected
Definition at line 80 of file rc_movieconverter.h.
Referenced by overWrite().
bool rcMovieConverterOptions::mReversePixels protected
Definition at line 81 of file rc_movieconverter.h.
Referenced by reversePixels().
int32 rcMovieConverterOptions::mSamplePeriod protected
Definition at line 77 of file rc_movieconverter.h.
Referenced by samplePeriod().
bool rcMovieConverterOptions::mVerbose protected
Definition at line 82 of file rc_movieconverter.h.
Referenced by verbose().
The documentation for this class was generated from the following files:
include/visual/rc_movieconverter.h
src/visual/code/rc_movieconverter.cpp