Visible: rcNumericChoiceSettingWidget Class Reference
rcNumericChoiceSettingWidget Class Reference
#include <include/visUI/rc_numericchoicesettingwidget.h>
Public Slots
void choiceSelected (int choiceValue)
void settingChanged (void)
void settingChanged (const QString &value)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcNumericChoiceSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcNumericChoiceSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Member Functions
int findChoice (float value)
Private Attributes
QComboBox * mWidget
rcLineEdit * mTextWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 17 of file rc_numericchoicesettingwidget.h.
Constructor & Destructor Documentation
rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 25 of file rc_numericchoicesettingwidget.cpp.
References choiceSelected(), cTextWidth, cUIsettingLabelSpacing, cUIsettingLabelWidth, cUIWordBreakAlignment, rcSettingInfo::getChoice(), rcSettingInfo::getDescription(), rcSettingInfo::getDisplayName(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingInfo::getTag(), rcSettingChoice::getText(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, mTextWidget, mWidget, and settingChanged().
         : rcSettingWidget( parent, setting, false )
 {
     // We create our own laytout without using base class layout
     Q3BoxLayout* vLayout = new Q3VBoxLayout( this );
     Q3BoxLayout* layout = new Q3HBoxLayout( vLayout );
     QLabel* label = new QLabel( setting.getDisplayName() , this );
     label->setFixedWidth( cUIsettingLabelWidth );
     label->setAlignment( cUIWordBreakAlignment );
     layout->addWidget( label );
     layout->addSpacing( cUIsettingLabelSpacing );
     mWidget = new QComboBox( false, this , setting.getTag() );
     int nChoices = setting.getNChoices();
     for (int i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = setting.getChoice( i );
         QString text( choice.getText() );
         // Add one space before text for better layout
         mWidget->insertItem( QString( " %1" )
                              .arg( text ) );
     }
     layout->addWidget( mWidget );
     layout->addSpacing( 10 );
     QToolTip::add( mWidget , setting.getDescription() );
     // A text widget for arbitrary frame rates
     mTextWidget = new rcLineEdit( this , setting.getTag() );
     mTextWidget->setFixedWidth( cTextWidth );
     QToolTip::add(mTextWidget , setting.getDescription() );
     float value = mSetting.getValue();
     mTextWidget->setText( QString( "%1" )
                           .arg( value ) );
     layout->addWidget(mTextWidget );
     layout->addStretch();
     // update the combo box with the current value of the setting.
     settingChanged();
     connect( mWidget , SIGNAL( activated( int ) ) , this , SLOT( choiceSelected( int ) ) );
     connect(mTextWidget , SIGNAL( textCommited( const QString& ) ) ,
              this    , SLOT( settingChanged( const QString& ) ) );
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
 }
rcNumericChoiceSettingWidget::~rcNumericChoiceSettingWidget ()
Definition at line 79 of file rc_numericchoicesettingwidget.cpp.
References mTextWidget, and mWidget.
 {
     QToolTip::remove( mWidget );
     QToolTip::remove(mTextWidget );
 }
Member Function Documentation
void rcNumericChoiceSettingWidget::choiceSelected (int choiceValue) slot
Definition at line 89 of file rc_numericchoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcSettingChoice::getFloatValue(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcNumericChoiceSettingWidget().
 {
     int nChoices = mSetting.getNChoices();
     if ((choiceIndex >= 0) && (choiceIndex < nChoices))
     {
         rcSettingChoice choice = mSetting.getChoice( choiceIndex );
         mSetting.setValue( choice.getFloatValue() );
     }
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
int rcNumericChoiceSettingWidget::findChoice (float value) private
Definition at line 144 of file rc_numericchoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcSettingChoice::getFloatValue(), rcSettingInfo::getNChoices(), and rcSettingWidget::mSetting.
Referenced by settingChanged().
 {
     int nChoices = mSetting.getNChoices();
     int i;
     for (i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = mSetting.getChoice( i );
         if (choice.getFloatValue() == value)
             break;
     }
     return i;
 }
void rcNumericChoiceSettingWidget::settingChanged (void) slot
Definition at line 104 of file rc_numericchoicesettingwidget.cpp.
References findChoice(), rcSettingInfo::getNChoices(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, mTextWidget, mWidget, and rcSettingWidget::updateWidgetState().
Referenced by rcNumericChoiceSettingWidget().
 {
     float currentValue = mSetting.getValue();
     int nChoices = mSetting.getNChoices();
     int i = findChoice( currentValue );
     if ( i >= nChoices ) {
         // find "custom" value 0
         i = findChoice( 0 );
     }
     if (i < nChoices)
         mWidget->setCurrentItem( i );
     mTextWidget->setText( QString( "%1" )
                           .arg( currentValue ) );
     // Update visibility/editability
     updateWidgetState();
 }
void rcNumericChoiceSettingWidget::settingChanged (const QString & value) slot
Definition at line 126 of file rc_numericchoicesettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
 {
     if ( value.length() ) {
         bool ok = false;
         float currentValue = value.toFloat( &ok );
         if ( currentValue > 0 ) {
             mSetting.setValue( currentValue );
         } else {
             // Illegal value, revert to previous value
         }
     }
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
rcLineEdit* rcNumericChoiceSettingWidget::mTextWidget private
Definition at line 39 of file rc_numericchoicesettingwidget.h.
Referenced by rcNumericChoiceSettingWidget(), settingChanged(), and ~rcNumericChoiceSettingWidget().
QComboBox* rcNumericChoiceSettingWidget::mWidget private
Definition at line 38 of file rc_numericchoicesettingwidget.h.
Referenced by rcNumericChoiceSettingWidget(), settingChanged(), and ~rcNumericChoiceSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_numericchoicesettingwidget.h
src/visible/qt/rc_numericchoicesettingwidget.cpp