Visible: rcRateChoiceSettingWidget Class Reference
rcRateChoiceSettingWidget Class Reference
#include <include/visUI/rc_frameratechoicesettingwidget.h>
Public Slots
void choiceSelected (int choiceValue)
void settingChanged (void)
void settingChanged (const QString &value)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcRateChoiceSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcRateChoiceSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Member Functions
int findChoice (float value)
Private Attributes
QComboBox * _widget
rcLineEdit * _rateWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 36 of file rc_frameratechoicesettingwidget.h.
Constructor & Destructor Documentation
rcRateChoiceSettingWidget::rcRateChoiceSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 209 of file rc_frameratechoicesettingwidget.cpp.
References _rateWidget, _widget, cFrameRateWidth, choiceSelected(), cUIsettingLabelSpacing, cUIsettingLabelWidth, cUIWordBreakAlignment, rcSettingInfo::getChoice(), rcSettingInfo::getDescription(), rcSettingInfo::getDisplayName(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingInfo::getTag(), rcSettingChoice::getText(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, and settingChanged().
                                                                                                :
   rcSettingWidget( parent, setting, false )
 {
   // We create our own laytout without using base class layout
   Q3BoxLayout* vLayout = new Q3VBoxLayout( this );
   Q3BoxLayout* layout = new Q3HBoxLayout( vLayout );
   QLabel* label = new QLabel( setting.getDisplayName() , this );
   label->setFixedWidth( cUIsettingLabelWidth );
   label->setAlignment( cUIWordBreakAlignment );
   layout->addWidget( label );
   layout->addSpacing( cUIsettingLabelSpacing );
   _widget = new QComboBox(false,  this , setting.getTag() );
   int nChoices = setting.getNChoices();
   for (int i = 0; i < nChoices; i++)
     {
       rcSettingChoice choice = setting.getChoice( i );
       QString text( choice.getText() );
       // Add one space before text for better layout
       _widget->insertItem( QString( " %1" )
                .arg( text ) );
     }
   layout->addWidget( _widget );
   layout->addSpacing( 10 );
   QToolTip::add( _widget , setting.getDescription() );
   // A text widget for arbitrary frame rates
   _rateWidget = new rcLineEdit( this , setting.getTag() );
   _rateWidget->setFixedWidth( cFrameRateWidth / 2 );
   QToolTip::add( _rateWidget , setting.getDescription() );
   float value = mSetting.getValue();
   _rateWidget->setText( QString( "%1" ).arg( value ) );
   layout->addWidget( _rateWidget );
   layout->addStretch();
   vLayout->addSpacing( 10 );
   layout->addStretch();
   // update the combo box with the current value of the setting.
   settingChanged();
   connect( _widget , SIGNAL( activated( int ) ) , this , SLOT( choiceSelected( int ) ) );
   connect( _rateWidget , SIGNAL( textCommited( const QString& ) ) ,
        this    , SLOT( settingChanged( const QString& ) ) );
   // connect this widget to be notified by the updateSettings()
   //    signal from the model domain
   rcModelDomain* domain = rcModelDomain::getModelDomain();
   connect( domain , SIGNAL( updateSettings() ) ,
        this   , SLOT( settingChanged() ) );
}
rcRateChoiceSettingWidget::~rcRateChoiceSettingWidget ()
Definition at line 265 of file rc_frameratechoicesettingwidget.cpp.
References _rateWidget, and _widget.
 {
   QToolTip::remove( _widget );
   QToolTip::remove( _rateWidget );
 }
Member Function Documentation
void rcRateChoiceSettingWidget::choiceSelected (int choiceValue) slot
Definition at line 277 of file rc_frameratechoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingChoice::getValue(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcRateChoiceSettingWidget().
 {
   int nChoices = mSetting.getNChoices();
   if ((choiceIndex >= 0) && (choiceIndex < nChoices))
     {
       rcSettingChoice choice = mSetting.getChoice( choiceIndex );
       mSetting.setValue( choice.getValue() );
     }
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
int rcRateChoiceSettingWidget::findChoice (float value) private
Definition at line 330 of file rc_frameratechoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcSettingChoice::getFloatValue(), rcSettingInfo::getNChoices(), and rcSettingWidget::mSetting.
Referenced by settingChanged().
 {
   int nChoices = mSetting.getNChoices();
   int i;
   for (i = 0; i < nChoices; i++)
     {
       rcSettingChoice choice = mSetting.getChoice( i );
       if (choice.getFloatValue() == value)
     break;
     }
   //@note hack to return custom
   if (i == nChoices) return 1;
   return i;
 }
void rcRateChoiceSettingWidget::settingChanged (void) slot
Definition at line 292 of file rc_frameratechoicesettingwidget.cpp.
References _rateWidget, _widget, findChoice(), rcSettingInfo::getNChoices(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, and rcSettingWidget::updateWidgetState().
Referenced by rcRateChoiceSettingWidget().
 {
   int currentValue = mSetting.getValue();
   int nChoices = mSetting.getNChoices();
   int i = findChoice( currentValue );
   if ( i >= nChoices ) {
     // find "custom" value 0
     i = findChoice( 0 );
   }
   if (i < nChoices)
     _widget->setCurrentItem( i );
   _rateWidget->setText( QString( "%1" )
                  .arg( currentValue ) );
   // Update visibility/editability
   updateWidgetState();
 }
void rcRateChoiceSettingWidget::settingChanged (const QString & value) slot
Definition at line 314 of file rc_frameratechoicesettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
 {
   bool ok = false;
   float currentValue = value.toFloat( &ok );
   if ( ok && currentValue > 0 ) {
     mSetting.setValue( currentValue );
   } else {
     // Illegal value, revert to previous value
   }
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
rcLineEdit* rcRateChoiceSettingWidget::_rateWidget private
Definition at line 58 of file rc_frameratechoicesettingwidget.h.
Referenced by rcRateChoiceSettingWidget(), settingChanged(), and ~rcRateChoiceSettingWidget().
QComboBox* rcRateChoiceSettingWidget::_widget private
Definition at line 57 of file rc_frameratechoicesettingwidget.h.
Referenced by rcRateChoiceSettingWidget(), settingChanged(), and ~rcRateChoiceSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_frameratechoicesettingwidget.h
src/visible/qt/rc_frameratechoicesettingwidget.cpp