Visible: rcPositionTrackImpl Class Reference
rcPositionTrackImpl Class Reference
#include <include/visiCore/rc_positiontrackimpl.h>
Public Member Functions
rcPositionTrackImpl (const char *tag, const char *name, const char *description, const char *displayFormat, uint32 sizeLimit)
virtual ~rcPositionTrackImpl ()
virtual uint32 segments ()
virtual rcSegmentImpl segment (uint32 index)
virtual void popSegment ()
virtual rcFPair getExpectedMinimumValue (void)
virtual rcFPair getExpectedMaximumValue (void)
virtual rcFPair getCurrentMinimumValue (void)
virtual rcFPair getCurrentMaximumValue (void)
virtual rcPositionSegmentIterator * getDataSegmentIterator (const rcTimestamp &pos)
virtual uint32 getSegmentCount (void)
virtual void setExpectedMinValue (const rcFPair &minValue)
virtual void setExpectedMaxValue (const rcFPair &maxValue)
virtual void writeValue (const rcTimestamp &timestamp, const rcRect &focus, const rcFPair &value)
virtual void flush (void)
virtual rcWriter * down_cast ()
Public Member Functions inherited from rcTrackImpl
rcTrackImpl (rcTrackType trackType, rcWriterType writerType, const char *tag, const char *name, const char *description, const char *displayFormat, uint32 limit, rcTimestamp firstTime=-1.0)
virtual ~rcTrackImpl ()
virtual rcTrackType getTrackType (void)
virtual rcWriterType getWriterType (void)
virtual const char * getTag (void)
virtual const char * getName (void)
virtual const char * getDescription (void)
virtual uint32 getSizeLimit () const
virtual const char * getDisplayFormatString (void)
virtual rcTimestamp getTrackStart (void)
virtual void setTrackStart (const rcTimestamp &time)
virtual void setExportable (bool e)
virtual void setDescription (const char *text)
virtual void setName (const char *text)
virtual bool isExportable (void)
virtual rcTrackSemantics getSemantics (void)
virtual void setSemantics (const rcTrackSemantics &s)
virtual rcRect getAnalysisRect (void)
virtual void setAnalysisRect (const rcRect &f)
Public Member Functions inherited from rcTrack
virtual ~rcTrack ()
Public Member Functions inherited from rcWriter
virtual ~rcWriter ()
Public Member Functions inherited from rcPositionTrack
virtual ~rcPositionTrack ()
Public Member Functions inherited from rcPositionWriter
virtual ~rcPositionWriter ()
Private Member Functions
void setWriterState (const rcTimestamp &time, const rcRect &focus, const rcFPair &value)
void setMinMaxValues (const rcFPair &value)
void addSegment (const rcTimestamp &segmentLength)
Private Attributes
deque< rcPositionSegment > _segments
rcFPair _expectedMinimumValue
rcFPair _expectedMaximumValue
rcFPair _currentMinimumValue
rcFPair _currentMaximumValue
rcFPair _currentValue
Friends
class rcPositionSegmentIteratorImpl
Additional Inherited Members
Public Types inherited from rcPositionTrack
enum { ePersistenceVersion = 1 }
Static Public Member Functions inherited from rcTrack
static rcTrackType type (const std::string &name)
static const std::string & name (rcTrackType type)
Protected Member Functions inherited from rcTrackImpl
rcTimestamp lastSegmentLength ()
rcTimestamp nextSegmentLength (const rcTimestamp &timestamp)
rcTimestamp nextSegmentStart ()
virtual void setWriterState (const rcTimestamp &time, rcRect focus)
void updateFirstTime (const rcTimestamp &timestamp)
Protected Attributes inherited from rcTrackImpl
rcMutex _mutex
rcTimestamp _currentLength
rcRect _currentFocus
uint32 _sizeLimit
rcTimestamp _firstTime
rcTimestamp _expStartTime
bool _isExportable
rcTrackSemantics _dataSemantics
rcRect _analysisFocus
Detailed Description
Definition at line 48 of file rc_positiontrackimpl.h.
Constructor & Destructor Documentation
rcPositionTrackImpl::rcPositionTrackImpl (const char * tag, const char * name, const char * description, const char * displayFormat, uint32 sizeLimit)
Definition at line 170 of file rc_positiontrackimpl.cpp.
References _currentMaximumValue, _currentMinimumValue, _currentValue, _expectedMaximumValue, _expectedMinimumValue, and rcTrackImpl::_isExportable.
         : rcTrackImpl( ePositionTrack, ePositionWriter, tag, name, description, displayFormat, sizeLimit )
 {
     _expectedMinimumValue = rcFPair( 0.0, 0.0 );
     _expectedMaximumValue = rcFPair( 0.0, 0.0 );
     _currentMinimumValue = rcFPair( 1.0, 1.0 );
     _currentMaximumValue = rcFPair( 0.0, 0.0 );
     _currentValue = rcFPair( 0.0, 0.0 );
     _isExportable = true;
 }
virtual rcPositionTrackImpl::~rcPositionTrackImpl () inline virtual
Definition at line 57 of file rc_positiontrackimpl.h.
 { };
Member Function Documentation
void rcPositionTrackImpl::addSegment (const rcTimestamp & segmentLength) private
Definition at line 338 of file rc_positiontrackimpl.cpp.
References rcTrackImpl::_currentFocus, _currentValue, _segments, cZeroTime, and rcTrackImpl::nextSegmentStart().
Referenced by flush(), and writeValue().
 {
     // Zero segment length is not allowed
     if ( segmentLength > cZeroTime ) {
          // Push new segment
         _segments.push_back( rcPositionSegment( nextSegmentStart(), segmentLength, _currentFocus, _currentValue ) );
     }
 }
rcWriter * rcPositionTrackImpl::down_cast () virtual
Implements rcPositionWriter.
Definition at line 298 of file rc_positiontrackimpl.cpp.
 {
     return dynamic_cast<rcWriter*>( this );
 }
void rcPositionTrackImpl::flush (void) virtual
Implements rcPositionWriter.
Definition at line 288 of file rc_positiontrackimpl.cpp.
References rcTrackImpl::_currentFocus, rcTrackImpl::_currentLength, _currentValue, rcTrackImpl::_mutex, addSegment(), rcTrackImpl::lastSegmentLength(), and setWriterState().
 {
     rcLock lock (_mutex);
     // Add final segment
     addSegment( lastSegmentLength() );
     // Update writer state
     setWriterState( _currentLength, _currentFocus, _currentValue );
 }
rcFPair rcPositionTrackImpl::getCurrentMaximumValue (void) virtual
Implements rcPositionTrack.
Definition at line 237 of file rc_positiontrackimpl.cpp.
References _currentMaximumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _currentMaximumValue;
 }
rcFPair rcPositionTrackImpl::getCurrentMinimumValue (void) virtual
Implements rcPositionTrack.
Definition at line 230 of file rc_positiontrackimpl.cpp.
References _currentMinimumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _currentMinimumValue;
 }
rcPositionSegmentIterator * rcPositionTrackImpl::getDataSegmentIterator (const rcTimestamp & pos) virtual
Implements rcPositionTrack.
Definition at line 246 of file rc_positiontrackimpl.cpp.
References rcTrackImpl::_mutex, and rcPositionSegmentIteratorImpl.
 {
   return new rcPositionSegmentIteratorImpl( this , pos, _mutex );
 }
rcFPair rcPositionTrackImpl::getExpectedMaximumValue (void) virtual
Implements rcPositionTrack.
Definition at line 222 of file rc_positiontrackimpl.cpp.
References _expectedMaximumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _expectedMaximumValue;
 }
rcFPair rcPositionTrackImpl::getExpectedMinimumValue (void) virtual
Implements rcPositionTrack.
Definition at line 214 of file rc_positiontrackimpl.cpp.
References _expectedMinimumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _expectedMinimumValue;
 }
uint32 rcPositionTrackImpl::getSegmentCount (void) virtual
Implements rcPositionTrack.
Definition at line 252 of file rc_positiontrackimpl.cpp.
References rcTrackImpl::_mutex, and _segments.
 {
     rcLock lock (_mutex);
     return _segments.size();
 }
void rcPositionTrackImpl::popSegment () virtual
Reimplemented from rcTrackImpl.
Definition at line 200 of file rc_positiontrackimpl.cpp.
References _segments.
 {
     // We have hit the maximum size limit, we must prune oldest value
     // TODO: this wont work right until we use absolute timestamps instead of relative timestamps
     _segments.pop_front();
     // Try to compact container
     deque<rcPositionSegment>(_segments).swap(_segments);
 }
rcSegmentImpl rcPositionTrackImpl::segment (uint32 index) virtual
Reimplemented from rcTrackImpl.
Definition at line 191 of file rc_positiontrackimpl.cpp.
References _segments, and cZeroTime.
 {
     if ( index < _segments.size() )
         return _segments[index];
     else
         return rcSegmentImpl( cZeroTime, cZeroTime, rcRect() );
 }
uint32 rcPositionTrackImpl::segments (void) virtual
Reimplemented from rcTrackImpl.
Definition at line 185 of file rc_positiontrackimpl.cpp.
References _segments.
Referenced by rcPositionSegmentIteratorImpl::setCurrentValue().
 {
     return _segments.size();
 }
void rcPositionTrackImpl::setExpectedMaxValue (const rcFPair & maxValue) virtual
Implements rcPositionWriter.
Definition at line 267 of file rc_positiontrackimpl.cpp.
References _expectedMaximumValue.
 {
     _expectedMaximumValue = maxValue;
 }
void rcPositionTrackImpl::setExpectedMinValue (const rcFPair & minValue) virtual
Implements rcPositionWriter.
Definition at line 261 of file rc_positiontrackimpl.cpp.
References _expectedMinimumValue.
 {
     _expectedMinimumValue = minValue;
 }
void rcPositionTrackImpl::setMinMaxValues (const rcFPair & value) private
Definition at line 311 of file rc_positiontrackimpl.cpp.
References _currentMaximumValue, _currentMinimumValue, rcPair< T >::x(), and rcPair< T >::y().
Referenced by writeValue().
 {
     // First time through, set current min and max values
     if ( _currentMinimumValue.x() > _currentMaximumValue.x() )
     {
         _currentMinimumValue.x() = value.x();
         _currentMaximumValue.x() = value.x();
     }
     // First time through, set current min and max values
     if ( _currentMinimumValue.y() > _currentMaximumValue.y() )
     {
         _currentMinimumValue.y() = value.y();
         _currentMaximumValue.y() = value.y();
     }
     // Update min and max current values
     if ( value.x() < _currentMinimumValue.x() )
         _currentMinimumValue.x() = value.x();
     if ( value.x() > _currentMaximumValue.x() )
         _currentMaximumValue.x() = value.x();
     if ( value.y() < _currentMinimumValue.y() )
         _currentMinimumValue.y() = value.y();
     if ( value.y() > _currentMaximumValue.y() )
         _currentMaximumValue.y() = value.y();
 }
void rcPositionTrackImpl::setWriterState (const rcTimestamp & time, const rcRect & focus, const rcFPair & value) private
Definition at line 304 of file rc_positiontrackimpl.cpp.
References _currentValue, and rcTrackImpl::setWriterState().
Referenced by flush(), and writeValue().
 {
     rcTrackImpl::setWriterState( time, focus );
     _currentValue = value;
 }
void rcPositionTrackImpl::writeValue (const rcTimestamp & timestamp, const rcRect & focus, const rcFPair & value) virtual
Implements rcPositionWriter.
Definition at line 273 of file rc_positiontrackimpl.cpp.
References rcTrackImpl::_mutex, addSegment(), rcTrackImpl::nextSegmentLength(), setMinMaxValues(), setWriterState(), and rcTrackImpl::updateFirstTime().
 {
     rcLock lock (_mutex);
     // Update first value time
     updateFirstTime( timestamp );
     // Update historical min/max values
     setMinMaxValues( value );
     // Add new segment
     rcTimestamp length = nextSegmentLength( timestamp );
     addSegment( length );
     // Update writer state
     setWriterState( timestamp, focus, value );
 }
Friends And Related Function Documentation
friend class rcPositionSegmentIteratorImpl friend
Definition at line 108 of file rc_positiontrackimpl.h.
Referenced by getDataSegmentIterator().
Member Data Documentation
rcFPair rcPositionTrackImpl::_currentMaximumValue private
Definition at line 122 of file rc_positiontrackimpl.h.
Referenced by getCurrentMaximumValue(), rcPositionTrackImpl(), and setMinMaxValues().
rcFPair rcPositionTrackImpl::_currentMinimumValue private
Definition at line 121 of file rc_positiontrackimpl.h.
Referenced by getCurrentMinimumValue(), rcPositionTrackImpl(), and setMinMaxValues().
rcFPair rcPositionTrackImpl::_currentValue private
Definition at line 123 of file rc_positiontrackimpl.h.
Referenced by addSegment(), flush(), rcPositionTrackImpl(), and setWriterState().
rcFPair rcPositionTrackImpl::_expectedMaximumValue private
Definition at line 120 of file rc_positiontrackimpl.h.
Referenced by getExpectedMaximumValue(), rcPositionTrackImpl(), and setExpectedMaxValue().
rcFPair rcPositionTrackImpl::_expectedMinimumValue private
Definition at line 119 of file rc_positiontrackimpl.h.
Referenced by getExpectedMinimumValue(), rcPositionTrackImpl(), and setExpectedMinValue().
deque<rcPositionSegment> rcPositionTrackImpl::_segments private
Definition at line 118 of file rc_positiontrackimpl.h.
Referenced by addSegment(), getSegmentCount(), popSegment(), segment(), segments(), and rcPositionSegmentIteratorImpl::setCurrentValue().
The documentation for this class was generated from the following files:
include/visiCore/rc_positiontrackimpl.h
src/visible/src/rc_positiontrackimpl.cpp