Visible: rcStatistics Class Reference
rcStatistics Class Reference
#include <include/util/rc_stats.h>
Public Member Functions
rcStatistics ()
~rcStatistics ()
void reset ()
void add (double val)
uint32 n () const
double last () const
double mean () const
double min () const
double max () const
double variance () const
double rms () const
double stdDev () const
Private Attributes
uint32 mN
double mLast
double mSum
double mSumsq
double mMin
double mMax
Friends
ostream & operator<< (ostream &ous, const rcStatistics &rc)
Detailed Description
Definition at line 208 of file rc_stats.h.
Constructor & Destructor Documentation
rcStatistics::rcStatistics () inline
Definition at line 214 of file rc_stats.h.
    {
      reset ();
    }
rcStatistics::~rcStatistics () inline
Definition at line 223 of file rc_stats.h.
 {};
Member Function Documentation
void rcStatistics::add (double val) inline
Definition at line 245 of file rc_stats.h.
Referenced by calcExtendedMuscleCellFrame(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcVisualFunction::direct(), rcKinetoscope::keepPopulationMeasure(), rcEngineImpl::modelTracker(), rcKinetoscope::rawSpeedStats(), and rf1DRegister().
    {
      mN++;
      mLast = val;
      mSum += val;
      mSumsq += val * val;
      if (val < mMin) mMin = val;
      if (val > mMax) mMax = val;
    }
double rcStatistics::last () const inline
Definition at line 265 of file rc_stats.h.
 { return mLast; };
double rcStatistics::max () const inline
Definition at line 285 of file rc_stats.h.
 { assert(mN); return mMax; };
double rcStatistics::mean () const inline
Definition at line 271 of file rc_stats.h.
Referenced by rcEngineImpl::modelTracker(), and rf1DRegister().
 { return (mN) ? (mSum / mN) : 0.0; };
double rcStatistics::min () const inline
Definition at line 277 of file rc_stats.h.
 { assert(mN); return mMin; };
uint32 rcStatistics::n () const inline
Definition at line 259 of file rc_stats.h.
Referenced by rcEngineImpl::modelTracker(), rcKinetoscope::rawSpeedStats(), and rcVisualFunction::rmsQuality().
 { return mN; };
void rcStatistics::reset (void) inline
Definition at line 231 of file rc_stats.h.
References rcDBL_MAX, and rcDBL_MIN.
Referenced by rcVisualFunction::initFunction(), rcKinetoscope::step(), rcKinetoscope::stepContractile(), rcKinetoscope::stepDirectedFlow(), and rcKinetoscope::stepEpi().
    {
      mN = 0;
      mSum = 0;
      mSumsq = 0;
      mLast = 0;
      mMin = rcDBL_MAX;
      mMax = rcDBL_MIN;
    }
double rcStatistics::rms () const inline
Definition at line 299 of file rc_stats.h.
Referenced by rcVisualFunction::rmsQuality().
   { return (mN > 0) ? sqrt (mSumsq / mN) : 0; };
double rcStatistics::stdDev () const inline
Definition at line 306 of file rc_stats.h.
Referenced by rcEngineImpl::modelTracker().
      { return sqrt(variance()); };
double rcStatistics::variance () const inline
Definition at line 293 of file rc_stats.h.
      { return (mN > 1) ? (mSumsq - mSum * mean()) / (mN-1) : 0; };
Friends And Related Function Documentation
ostream& operator<< (ostream & ous, const rcStatistics & rc) friend
Definition at line 312 of file rc_stats.h.
    {
        ous << "Min (" << rc.min() << ")" << endl;
        ous << "Max (" << rc.max() <<  ")" << endl;
        ous << "Mean (" << rc.mean() << ")" << endl;
        ous << "Stdev (" << rc.stdDev() << ")" << endl;
        return ous;
    }
Member Data Documentation
double rcStatistics::mLast private
Definition at line 328 of file rc_stats.h.
double rcStatistics::mMax private
Definition at line 336 of file rc_stats.h.
double rcStatistics::mMin private
Definition at line 334 of file rc_stats.h.
uint32 rcStatistics::mN private
Definition at line 326 of file rc_stats.h.
double rcStatistics::mSum private
Definition at line 330 of file rc_stats.h.
double rcStatistics::mSumsq private
Definition at line 332 of file rc_stats.h.
The documentation for this class was generated from the following file:
include/util/rc_stats.h