Visible: rcKinetoscope Class Reference
rcKinetoscope Class Reference
#include <include/analysis/rc_kinetoscope.h>
Public Types
enum Source { eVideoCache = 0, eFileGrabber, eUnknownSource }
enum SourceMotion {
eAttentiveCapture = 0, eOverSampled, eUnderSampled, eContractile,
eCanonical, eEpiFluorescence, eDirectedFlow, eUnknownMotion
}
enum Defaults {
eMinMobSizeInPixels = 25, eMinSpeedInPixels = 2, eMaxSpeedInPixels = 10, eSplatSize =3,
eSplatArea =eSplatSize*eSplatSize, eEndDefault
}
enum Time { eFixed = 0, eMoving = 1 }
enum Detail { eFine = 0, eCoarse = 1 }
enum Option {
eBasic =0, eLineage, eMutualChannel, eCanStep,
eSelectedMyo, eNumOptions
}
typedef boost::shared_ptr
< rcKinetoscope > rcSharedKinetoscope
Public Member Functions
bool have (enum Option what) const
bool mark (enum Option what)
bool clear (enum Option what)
void reset ()
rcKinetoscope ()
rcKinetoscope (shared_video_cache &fg, const rcIRect rect, uint32 phase=0, uint32 sample=1, rcKinetoscope::Detail d=eFine, rcMovieFileOrgExt org=rcMovieFileOrgExt(), rcOrganismInfo::OrganismType c=rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n=rcOrganismInfo::eUnknown, int32 minMobSize=eMinMobSizeInPixels, bool debug=false)
rcKinetoscope (boost::shared_ptr< rcFrameGrabber > &fg, const rcIRect rect, uint32 phase=0, uint32 sample=1, rcKinetoscope::Detail d=eFine, rcMovieFileOrgExt org=rcMovieFileOrgExt(), rcOrganismInfo::OrganismType c=rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n=rcOrganismInfo::eUnknown, int32 minMobSize=eMinMobSizeInPixels, bool debug=false)
virtual ~rcKinetoscope ()
rcSharedKinetoscope shared ()
void visualFunctionInfo (rcOrganismInfo::OrganismType c=rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n=rcOrganismInfo::eUnknown)
rcOrganismInfo::OrganismType organism () const
rcOrganismInfo::OrganismName organismName () const
bool isOfOrganismType (rcOrganismInfo::OrganismType ot) const
bool isOfOrganismName (rcOrganismInfo::OrganismName onm) const
bool isOfOrganismTypeAndName (rcOrganismInfo::OrganismType ot, rcOrganismInfo::OrganismName onm) const
bool isCardiacCell () const
bool isLabelProtein () const
void fileOriginType (rcMovieFileOrgExt &orgx)
const rcMovieFileOrgExt & fileOriginType () const
const int32 frames () const
const bool channelAvailable () const
int32 sourceMotion () const
int32 sourceMotion (SourceMotion sm)
void preSegmentedBodies (const vector< rcPolygon > &bodies)
void preSegmentedBodies (const vector< vector< rc2Fvector > > &bodyEnds, vector< float > &rads)
uint32 sample () const
uint32 phase () const
void periodicMotion (float)
float periodicMotion () const
void averageFramesPerSecond (double)
float averageFramesPerSecond () const
int32 detail () const
int32 detail (const Detail d)
void target (int32 sam)
rcIPair target () const
void maxRadialSpeed (int32 sam)
int32 maxRadialSpeed () const
rcIPair capture () const
float sizeMultiplier () const
void sizeMultiplier (float)
const rcIRect & pframe () const
const rcIRect & iframe () const
void laminarSuppression (double over)
double laminarSuppression () const
void minMobSizeInPixels (int32 ms)
int32 minMobSizeInPixels ()
const rc1Xform & imageFromPhysical () const
const rc1Xform & physicalFromImage () const
const rc1Xform & secondsToUnits () const
void temporalScale (float ts)
const rc2Xform & xform () const
int32 step (uint32 steps=1, bool keepgoing=1)
int32 stepContractile (uint32 steps=1, bool keepgoing=1)
int32 stepDirectedFlow (uint32 steps=1, bool keepgoing=1)
int32 stepEpi (uint32 steps=1, bool keepgoing=1)
int32 stepDirectedFlowPreFill ()
void advance ()
void reconcileNewGeneration ()
void newGeneration (list< rcVisualFunction > &cells, vector< rcPolygon > &regions)
rcTimestamp resultTime () const
double deltaTime () const
double elapsedTime () const
double currentTime () const
const rcTimestamp & startingAbsoluteTime () const
const rcWindow & use4fixed () const
const rcWindow & use4moving () const
const rcWindow & use4when (const Time when) const
const rcWindow & fixed () const
const rcWindow & fixedPast () const
const rcWindow & movingPast () const
const rcWindow & moving () const
const rcWindow & movingDirection () const
const rcWindow & fixedDirection () const
const rcWindow & channelFixed () const
const rcWindow & channelFixedPast () const
const rcWindow & channelMovingPast () const
const rcWindow & channelMoving () const
const rcWindow & channelMovingDirection () const
const rcWindow & channelFixedDirection () const
const rcWindow debug () const
bool debug (bool db)
bool isDebugOn () const
void fieldMap (rcWindow &) const
vector< rcPolygon > & fixedPolygons ()
vector< rcPolygon > & movingPolygons ()
bool canStep () const
const rcStatistics & populationMeasures () const
float directedCellToCellMigration ()
float avgMeanSqCellDisplacements ()
void rawSpeedStats (rcStatistics &stats)
void rawDirectStats (rcHistoStats &)
list< rcVisualFunction > & visualBodies ()
ostream & temporalResults (ostream &, ostream &)
void visualGraphics (rcVisualSegmentCollection &segments, const rcVisualStyle &baseStyle)
void visualFunctionMap (rcVisualSegmentCollection &segments, const rcVisualStyle &baseStyle)
void visualFunctionHistory (rcVisualSegmentCollection &segments, const rcVisualStyle &baseStyle)
void visualDebugGraphics (rcVisualSegmentCollection &segments, const rcVisualStyle &baseStyle)
void visualGraphics (rcVisualGraphicsCollection &graphics)
void visualFunctionMap (rcVisualGraphicsCollection &graphics)
void visualFunctionHistory (rcVisualGraphicsCollection &graphics)
void visualDebugGraphics (rcVisualGraphicsCollection &graphics)
int32 count () const
Static Public Attributes
static const int32 defaultTargetRadius = 3
static const int32 defaultMaxRadSpeed = eMinSpeedInPixels
static const double defaultCutOff = 5.0
static const float notAvailable = -2.0
Protected Member Functions
void start ()
void connectedFunctions (Time when, vector< rcPolygon > &polys2fill)
void measure (rcMotionPathMap &)
void measure (list< rcVisualFunction > &)
void update (rcMotionPathMap &)
void update (list< rcVisualFunction > &)
void reconcile (rcMotionPathMap &)
void reconcile (list< rcVisualFunction > &)
void selfSimilarMotionField ()
void selfSimilarMotionField_AttentiveCapture ()
void selfSimilarMotionField_UnderSampled ()
void canonicalMotionField (const rcWindow &)
void epiMotionField ()
const rcIRect & uframe () const
const rcFRect & fpframe () const
bool isPointCorrOptimizationAvailable () const
bool preProcessConnect () const
bool isWithin (const rc2Fvector &) const
bool isWithin () const
bool isWithin (const rcIRect &) const
rcIPair kernelBorder () const
void reichardt (Time)
bool validate (const rcIRect &rect, rc2Fvector &) const
const rcIPair & movingSize () const
bool isBound ()
void clear ()
Private Member Functions
rcKinetoscope (const rcKinetoscope &)
rcKinetoscope & operator= (const rcKinetoscope &)
void createFunctionSpecificObjects ()
void debugScreen (const rcWindow &image)
rcWindow & connect ()
rcWindow & connected ()
rcWindow & velocityXfield ()
rcWindow & velocityYfield ()
bool connectFunction (const rcIRect &r, const rcPolygon &p, rc2Fvector &moc, vector< rc2Fvector > &anc, vector< rc2Fvector > &mot)
void associate (list< rcVisualFunction > &cells, vector< rcPolygon > &regions, Time when=eMoving)
const rcPointCorrelation & pointCorr () const
void keepPopulationMeasure ()
bool frame (uint32 deltaFrames, const Time when)
int32 frameCount () const
uint32 startFrame () const
void updateProcessingTime ()
void mov ()
void dumpMap (ostream &)
void dumpPolys (ostream &)
void printPolys () __attribute__((noinline))
void printMap () __attribute__((noinline))
void printConnect () __attribute__((noinline))
void printConnected () __attribute__((noinline))
Private Attributes
rcStatistics mPopulationStats
Source mSource
shared_video_cache mVc
rcVideoCacheStatus mVcStatus
boost::shared_ptr< rcFrameGrabber > mFg
rcFrameGrabberStatus mFgStatus
rcMovieFileOrgExt mOrgExt
vector< rc2LevelSpatialPyramid > mFrameData
vector< rc2LevelSpatialPyramid > mChannelData
vector< rcWindow > mConnectionMap
vector< rcMomentGenerator * > mMomentMap
rcWindow mXvelocityField
rcWindow mYvelocityField
vector< rcWindow > mSimBuffer
rcWindow mClearImage
rcWindow mFullImage
Detail mDetail
rcIRect mRect
rcIRect mProcessRect
rcIRect mUserRect
rcWindow mDebugScreen
rcWindow mMaskCellwFF
rcMotionPathMap mPathMap
list< rcVisualFunction > mFunctionMap
list< rcVisualFunction > mDaughterFunctionMap
vector< rcPolygon > mPOLYs
vector< rcPolygon > mFixedPOLYs
vector< rcPolygon > mMergedPOLYs
vector< vector< rc2Fvector > > mBodyEnds
vector< float > mBodyRads
vector< vector< rc2Fvector > > mVanchor
vector< vector< rc2Fvector > > mVmoved
vector< rcPolygon > mPrePOLYs
rcOrganismInfo::OrganismType mOtype
rcOrganismInfo::OrganismName mOname
rcLatticeSimilaratorRef mLsm
vector< float > mPopulationMeasure
rcTimestamp mStartAbsTimeStamp
rcTimestamp mCurrentAbsTimeStamp
float mElapsedTimeSecs
float mLastElapsedTimeSecs
double mStepProcessingTime
rcStatistics mSnapStats
double mGlobalMotionEst
SourceMotion mSourceMotion
float mPeriodicity
float mFramesPerSecond
int32 mSimPipe
bitset< eNumOptions > mOptions
rc1Xform mImageToPhysical
rc1Xform mPhysicalToImage
rc1Xform mTemporal
rc2Xform mGlobalXform
rsCorrParams mCorr
rcAutoCorrelation mAutoCorr
rcMomentGenerator mMomGen0
rcMomentGenerator mMomGen1
rcPointCorrelation mPointCorr
int32 mFc
uint32 mCount
int32 mDisVarError
int32 mDisGMEError
int32 mDisEdgeError
int32 mDisPolarError
uint32 mSample
uint32 mPhase
rcIPair mTargetRadius
rcIPair mCaptureRadius
rcIPair mVmaxRadial
rcIPair mMovingSize
int32 mMinParea
rcFPair mOrigin
rcFRect mFpFrame
double mCutOff
bool mDebug
float mSizeMultiplier
Friends
class rcMotionVectorPath
class rcVisualFunction
ostream & operator<< (ostream &, rcKinetoscope &)
Detailed Description
Definition at line 75 of file rc_kinetoscope.h.
Member Typedef Documentation
typedef boost::shared_ptr<rcKinetoscope> rcKinetoscope::rcSharedKinetoscope
Definition at line 150 of file rc_kinetoscope.h.
Member Enumeration Documentation
enum rcKinetoscope::Defaults
Enumerator
eMinMobSizeInPixels
eMinSpeedInPixels
eMaxSpeedInPixels
eSplatSize
eSplatArea
eEndDefault
Definition at line 106 of file rc_kinetoscope.h.
     {
       eMinMobSizeInPixels = 25,
       eMinSpeedInPixels = 2,
       eMaxSpeedInPixels = 10,
       eSplatSize=3,
       eSplatArea=eSplatSize*eSplatSize,
       eEndDefault
     };
enum rcKinetoscope::Detail
Enumerator
eFine
eCoarse
Definition at line 122 of file rc_kinetoscope.h.
     {
       eFine = 0,
       eCoarse = 1
     };
enum rcKinetoscope::Option
Enumerator
eBasic
eLineage
eMutualChannel
eCanStep
eSelectedMyo
eNumOptions
Definition at line 128 of file rc_kinetoscope.h.
   {
     eBasic=0,
     eLineage,
     eMutualChannel,
     eCanStep,
     eSelectedMyo,
     eNumOptions
   };
enum rcKinetoscope::Source
Enumerator
eVideoCache
eFileGrabber
eUnknownSource
Definition at line 82 of file rc_kinetoscope.h.
   {
     eVideoCache = 0,
     eFileGrabber,
     eUnknownSource
   };
enum rcKinetoscope::SourceMotion
Enumerator
eAttentiveCapture
eOverSampled
eUnderSampled
eContractile
eCanonical
eEpiFluorescence
eDirectedFlow
eUnknownMotion
Definition at line 93 of file rc_kinetoscope.h.
   {
     eAttentiveCapture = 0,
     eOverSampled,
     eUnderSampled,
     eContractile,
     eCanonical,
     eEpiFluorescence,
     eDirectedFlow,
     eUnknownMotion
   };
enum rcKinetoscope::Time
Enumerator
eFixed
eMoving
Definition at line 116 of file rc_kinetoscope.h.
     {
       eFixed = 0,
       eMoving = 1
     };
Constructor & Destructor Documentation
rcKinetoscope::rcKinetoscope ()
Definition at line 401 of file rc_kinetoscope.cpp.
References clear(), detail(), eFine, mChannelData, mConnectionMap, mDebug, mFrameData, mMomentMap, mPhase, mRect, mSample, mUserRect, and rcTimingInfo::turnOffPrint().
 {
   mSample = 1;
   mPhase = 1;
   mRect = mUserRect = rcIRect ();
   mConnectionMap.resize (2);
   mFrameData.resize (2);
   mChannelData.resize (2);
   mMomentMap.resize (2);
   detail (eFine);
   rcTimingInfo::turnOffPrint ();
   clear ();
   mDebug = false;
 }
rcKinetoscope::rcKinetoscope (shared_video_cache & fg, const rcIRect rect, uint32 phase = 0, uint32 sample = 1, rcKinetoscope::Detail d = eFine, rcMovieFileOrgExt org = rcMovieFileOrgExt (), rcOrganismInfo::OrganismType c = rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n = rcOrganismInfo::eUnknown, int32 minMobSize = eMinMobSizeInPixels, bool debug = false)
Definition at line 431 of file rc_kinetoscope.cpp.
References COMMONCTOR, mVc, and rmExceptionMacro.
 : mSource (eVideoCache), mVc (fg), mOrgExt (org)
   {
     if (!mVc)
       rmExceptionMacro(<<"Kinetoscope: inValid Video Cache");
     COMMONCTOR;
   }
rcKinetoscope::rcKinetoscope (boost::shared_ptr< rcFrameGrabber > & fg, const rcIRect rect, uint32 phase = 0, uint32 sample = 1, rcKinetoscope::Detail d = eFine, rcMovieFileOrgExt org = rcMovieFileOrgExt (), rcOrganismInfo::OrganismType c = rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n = rcOrganismInfo::eUnknown, int32 minMobSize = eMinMobSizeInPixels, bool debug = false)
Definition at line 442 of file rc_kinetoscope.cpp.
References COMMONCTOR, mFg, and rmExceptionMacro.
 : mSource (eFileGrabber), mFg (fg), mOrgExt (org)
   {
     if (! mFg || !mFg->start ())
       rmExceptionMacro(<<"Kinetoscope: Can start frame grabber");
     COMMONCTOR;
   }
rcKinetoscope::~rcKinetoscope () virtual
Definition at line 455 of file rc_kinetoscope.cpp.
   {
   }
rcKinetoscope::rcKinetoscope (const rcKinetoscope &) private
Member Function Documentation
void rcKinetoscope::advance ()
Definition at line 27 of file rc_kineframe.cpp.
References channelAvailable(), connect(), debugScreen(), detail(), eContractile, rcOrganismInfo::eDanioRerio, eFixed, rcOrganismInfo::eModel, isCardiacCell(), mChannelData, mConnectionMap, mFixedPOLYs, mFrameData, mMomentMap, mPOLYs, rcTimingInfo::nextPass(), organism(), organismName(), rcTimingInfo::printInfo(), rcWindow::setAllPixels(), sourceMotion(), and rcTimingInfo::touch().
Referenced by rcEngineImpl::muscleTracker().
 {
   rcTimingInfo profile (10, 1);
   profile.nextPass (true);
   // Debugging display
   profile.touch (0, std::string ("Start"));
   if (isCardiacCell ())
     {
       debugScreen (mFrameData[eFixed].base (detail ()));
     }
   else
     {
       if (organism() !=  rcOrganismInfo::eModel || organismName () != rcOrganismInfo::eDanioRerio)
     {
       if (channelAvailable ())
         debugScreen (mChannelData[eFixed].base (detail ()));
       else
         debugScreen (connect());
     }
     }
  // swap is constant time for containers. We keep a copy of the previous POLYS.
   profile.touch (1, std::string ("Debug"));
   mFixedPOLYs = mPOLYs;
   // Rotate Frame Collections
   profile.touch (2, std::string ("Poly Shuffle"));
   rotate (mFrameData.begin(), mFrameData.end() - 1, mFrameData.end());
   // Rotate Frame Collections
   profile.touch (3, std::string ("Frame Data Shuffle"));
   if (mChannelData.size())
     rotate (mChannelData.begin(), mChannelData.end() - 1, mChannelData.end());
   // Rotate Connection Maps
   profile.touch (4, std::string ("Channel Data"));
   rotate (mConnectionMap.begin(), mConnectionMap.end() - 1, mConnectionMap.end());
   // Rotate Moment Maps
   profile.touch (5, std::string ("Connection Map Shuffle"));
   rotate (mMomentMap.begin(), mMomentMap.end() - 1, mMomentMap.end());
   // @note use motion based or field based segmentation flags for this
   profile.touch (5, std::string ("Moment Map Shuffle"));
   if (sourceMotion() != eContractile)
     {
       // Clear Temporal
       rcWindow all (connect().frameBuf());
       all.setAllPixels (0);
     }
   // Other Clearing if we have to
   //  velocityXfield().setAllPixels (0);
   //  velocityYfield().setAllPixels (0);
   profile.touch (5, std::string ("Temporal Cleanup"));
   profile.printInfo (1);
 }
void rcKinetoscope::associate (list< rcVisualFunction > & cells, vector< rcPolygon > & regions, Time when = eMoving) private
Definition at line 716 of file rc_kinetrack.cpp.
References eMoving, endl(), rcPolygon::intersects(), mFixedPOLYs, rfAssociate(), rfCellNotViable(), rfPolygonGroupCenters(), rfPRINT_STL_ELEMENTS(), and rmAssert.
Referenced by connectedFunctions().
  {
    uint32 dividedCells (0), allCells (cells.size());
    // For each (moving) polygon see how many cells intersect with it
    list<rcVisualFunction>::iterator cell = cells.begin();
    static int32 zi (0);
    vector<int32> mflags (cells.size(), zi);
    vector<int32>::iterator mf = mflags.begin();
    vector<int32> fflags (mFixedPOLYs.size(), zi);
    vector<int32>::iterator ff = fflags.begin();
    for (; cell != cells.end(); cell++, mf++)
      {
        if (uint32 b = (uint32) rfCellNotViable (*cell))
      {
        dividedCells += b;
        continue;
      }
        rcPolygon cpg = cell->polygons().back();
        *mf = cpg.intersects (regions);
      }
    if (when == eMoving)
      {
        vector<rcPolygon>::iterator fp = mFixedPOLYs.begin();
        for (;fp != mFixedPOLYs.end(); fp++, ff++)
      {
        *ff = fp->intersects (regions);
      }
      }
 #ifdef TRACKDEBUG
    cerr << "Associate: " << "Total Registered Cells " << cells.size() << " Dead Cells: " << dividedCells << endl;
    rfPRINT_STL_ELEMENTS (mflags, "moving (cells) Flags");
    rfPRINT_STL_ELEMENTS (fflags, "moving (fixed) Flags");
 #endif
    //@note handle case where everyone has died!
    //@description LUT is a lookup table between living cell and their index among all cells
    // that is if we have LUT[i] = j, then ith living cell has j index among all cells
    uint32 liveCells = allCells - dividedCells;
    static const int32 inValid (-1);
    vector<int32> LUT (liveCells, inValid);
    vector<rc2Dvector> notDeadcells, regionCtrs;
    uint32 i (0);
    for(cell = cells.begin(); cell != cells.end(); ++cell, ++i )
      {
        if (rfCellNotViable (*cell)) continue;
        rc2Dvector p (cell->position().x(), cell->position().y());
        // remember indices are 0 based
        uint32 next (notDeadcells.size());
        notDeadcells.push_back (p);
        LUT[next] = (int32) i;
      }
    rmAssert (notDeadcells.size() == liveCells);
    rfPolygonGroupCenters (regions, regionCtrs);
    // Correspond Cells and Regions
    // @ what happens if you have more or less polys than cells ?
    vector<int32> labels (liveCells);
    vector<float> scores (liveCells);
    rfAssociate(notDeadcells, regionCtrs, labels, scores);
    for (uint32 i = 0; i < LUT.size(); i++)
      {
        int32 anyCellIndex = LUT[i];
        rmAssert (anyCellIndex >= 0 && anyCellIndex < (int32) (cells.size()));
        cell = cells.begin();
        std::advance (cell, anyCellIndex);
        cell->label (labels[i]);
        cell->cQuality (scores[i]);
      }
  }
void rcKinetoscope::averageFramesPerSecond (double p)
Definition at line 825 of file rc_kinetoscope.cpp.
References mFramesPerSecond.
Referenced by rcEngineImpl::muscleTracker().
 {
   mFramesPerSecond = p;
 }
float rcKinetoscope::averageFramesPerSecond () const
Definition at line 830 of file rc_kinetoscope.cpp.
References mFramesPerSecond.
 {
   return   mFramesPerSecond;
 }
float rcKinetoscope::avgMeanSqCellDisplacements ()
Definition at line 760 of file rc_kinetoscope.cpp.
References mFunctionMap.
 {
   list<rcVisualFunction>::iterator cTr = mFunctionMap.begin();
   float answer (0.0f);
   for (; cTr != mFunctionMap.end(); cTr++)
     {
       answer += cTr->minSqDisplacement ();
     }
   if (mFunctionMap.size())
     answer = answer / mFunctionMap.size();
   return answer;
 }
void rcKinetoscope::canonicalMotionField (const rcWindow & mEi) protected
Definition at line 279 of file rc_kinefield.cpp.
References iframe(), mOrigin, mPathMap, rcWindow::pelPointer(), rmAssert, rcRectangle< T >::size(), target(), rcPair< T >::x(), and rcPair< T >::y().
 {
 #if 0
   const rcIPair unit (1,1);
   const rcIPair two (2,2);
   const rcIPair& iOrigin = mOrigin;
   rcIPair dimension = iframe().size();
   rcIPair targetSize = target() * two + unit;
   rcIPair target4moments = targetSize + two + two;
   dimension -= target4moments; // dilated by half search size on both sides
   dimension += unit;
   const rcIPair searchSpace (target4moments - targetSize + unit);
   rmAssert (searchSpace > unit);
   rmAssert (dimension >= target4moments);
   rmAssert (searchSpace.x() == searchSpace.y());
   rmAssert (searchSpace.x() == 5);
   int32 index (0);
   rc2Fvector disp;
   // @note Skip over zero bytes. Perhaps the best way is to run length!
   for (int32 j = iOrigin.y(); j < (dimension.y() + iOrigin.y()); j++)
     {
       const uint8 *gPtr = (uint8 *) mEi.pelPointer (iOrigin.x(), j);
       int32 d (1);
       for (int32 i = iOrigin.x(); i < (dimension.x() + iOrigin.x()); i+=d, gPtr+=d, d = 1)
     {
       if (!(*(uint32 *) gPtr))
         {
           d = sizeof (uint32);
           continue;
         }
       if (!(*(uint16 *) gPtr))
         {
           d = sizeof (uint16);
           continue;
         }
       if (!(*(uint8 *) gPtr))
         {
           d = sizeof (uint8);
           continue;
         }
       const rc2Fvector anchor (i + mOrigin.x(), j + mOrigin.y());
       rcMotionVectorPath mvp (rcSharedKinetoscope (this), anchor, disp);
       index = (i<<16)+j;
       const pair<int32, rcMotionVectorPath> dmv (index, mvp);
       mPathMap.insert (dmv);
     }
     }
 #endif
 }
bool rcKinetoscope::canStep () const inline
Definition at line 504 of file rc_kinetoscope.h.
References eCanStep, and have().
 { return have (eCanStep); }
rcIPair rcKinetoscope::capture () const
const bool rcKinetoscope::channelAvailable () const inline
Definition at line 238 of file rc_kinetoscope.h.
References eMutualChannel, and have().
Referenced by advance(), frame(), start(), use4fixed(), and use4moving().
   {
     return have (eMutualChannel);
   }
const rcWindow& rcKinetoscope::channelFixed () const inline
Definition at line 477 of file rc_kinetoscope.h.
References detail(), eFixed, and mChannelData.
 { return mChannelData[eFixed].base(detail()); }
const rcWindow& rcKinetoscope::channelFixedDirection () const inline
Definition at line 482 of file rc_kinetoscope.h.
References detail(), eFixed, and mChannelData.
 { return mChannelData[eFixed].direction(detail()); }
const rcWindow& rcKinetoscope::channelFixedPast () const inline
Definition at line 478 of file rc_kinetoscope.h.
References detail(), eFixed, and mChannelData.
Referenced by use4fixed().
 { return mChannelData[eFixed].past (detail()); }
const rcWindow& rcKinetoscope::channelMoving () const inline
Definition at line 480 of file rc_kinetoscope.h.
References detail(), eMoving, and mChannelData.
 {return mChannelData[eMoving].base(detail()); }
const rcWindow& rcKinetoscope::channelMovingDirection () const inline
Definition at line 481 of file rc_kinetoscope.h.
References detail(), eMoving, and mChannelData.
 {return mChannelData[eMoving].direction (detail()); }
const rcWindow& rcKinetoscope::channelMovingPast () const inline
Definition at line 479 of file rc_kinetoscope.h.
References detail(), eMoving, and mChannelData.
Referenced by use4moving().
 { return mChannelData[eMoving].past (detail()); }
bool rcKinetoscope::clear (enum Option what)
Definition at line 624 of file rc_kinetoscope.cpp.
References have(), and mOptions.
 {
   mOptions.reset(what);
   return have (what);
 }
void rcKinetoscope::clear () protected
Definition at line 467 of file rc_kinetoscope.cpp.
References defaultMaxRadSpeed, defaultTargetRadius, detail(), eAttentiveCapture, eFine, rc1Xform::isIdentity(), rc2Xform::isIdentity(), maxRadialSpeed(), mCount, mElapsedTimeSecs, mGlobalXform, mImageToPhysical, mLastElapsedTimeSecs, mOrigin, mPeriodicity, mPhysicalToImage, mSimPipe, mSizeMultiplier, mSourceMotion, mStepProcessingTime, rmAssert, and target().
Referenced by connectedFunctions(), rcKinetoscope(), and start().
 {
   detail (eFine);
   mStepProcessingTime = -1.0;
   mElapsedTimeSecs = 0;
   mLastElapsedTimeSecs = 0;
   mPeriodicity = 0.0;
   mOrigin = rcFPair (0.0f, 0.0f);
   mCount = 0;
   target (defaultTargetRadius);
   maxRadialSpeed (defaultMaxRadSpeed);
   mSourceMotion = eAttentiveCapture;
   mSimPipe = 3;
 //  mLsm = new rcLatticeSimilarator (mSimPipe, 2);
   mSizeMultiplier = 0.0f;
   rmAssert (mGlobalXform.isIdentity());
   rmAssert (mImageToPhysical.isIdentity());
   rmAssert (mPhysicalToImage.isIdentity());
 }
rcWindow& rcKinetoscope::connect () inline private
Definition at line 715 of file rc_kinetoscope.h.
References eMoving, and mConnectionMap.
Referenced by advance(), connectedFunctions(), printConnect(), and start().
 {return mConnectionMap[eMoving]; }
rcWindow& rcKinetoscope::connected () inline private
Definition at line 716 of file rc_kinetoscope.h.
References eFixed, and mConnectionMap.
Referenced by connectedFunctions(), printConnected(), and start().
 {return mConnectionMap[eFixed]; }
void rcKinetoscope::connectedFunctions (Time when, vector< rcPolygon > & polys2fill) protected
Definition at line 427 of file rc_kinetrack.cpp.
References associate(), clear(), connect(), connected(), connectFunction(), eFixed, rcShape::eImage, eLineage, eSelectedMyo, FILLFUNCTION, rcWindow::frameBuf(), rcFrame::frameIndex(), have(), isCardiacCell(), isLabelProtein(), mBodyEnds, mBodyRads, mCount, mDaughterFunctionMap, mFixedPOLYs, mFunctionMap, mMinParea, mPathMap, mPOLYs, mPrePOLYs, mVanchor, mVmoved, newGeneration(), preProcessConnect(), reconcileNewGeneration(), rfComponentPolygons(), rfOfCellsAndPolys(), rfPixelMax3By3(), rfPixelMin3By3(), rmAssert, startFrame(), use4fixed(), use4moving(), validate(), visualBodies(), and rc2dVector< T >::x().
Referenced by step(), stepContractile(), and stepEpi().
 {
   vector<rcIRect> cRects;
   // @note:
   // mPrePOLYs empty && POLYs empty ==> no presegmentation information: cannonical operation
   // mPrePOLYs NOTempty && POLYs empty ==> presegmented, first time through: use presegmented
   // mPrePOLYs NOTempty && POLYs NOTempty ==> presegmented, after first time through: generate new polygons
   if (!mPrePOLYs.empty() && isCardiacCell ())
     {
       POLYs = mPrePOLYs;
       for (uint32 i = 0; i < POLYs.size(); i++)
     cRects.push_back (POLYs[i].orthogonalEnclosingRect());
     }
   else if (!mPrePOLYs.empty() && mCount <= startFrame())
     {
       POLYs = mPrePOLYs;
       for (uint32 i = 0; i < POLYs.size(); i++)
     cRects.push_back (POLYs[i].orthogonalEnclosingRect());
     }
   else
     {
       if (when == eFixed)
     {
       if (preProcessConnect ())
         {
           rcWindow buf =  rfPixelMin3By3 (connected());
           rfPixelMax3By3 (buf, connected());
         }
       rfComponentPolygons (connected(), mMinParea/2, POLYs, cRects, false);
     }
       else
     {
       if (preProcessConnect ())
         {
           rcWindow buf =  rfPixelMin3By3 (connect());
           rfPixelMax3By3 (buf, connect());
         }
       rfComponentPolygons (connect(), mMinParea/2, POLYs, cRects, false);
     }
     }
   rmAssert (cRects.size() == POLYs.size());
 #ifdef TRACKDEBUG
   rfOfCellsAndPolys (visualBodies(), mFixedPOLYs, mPOLYs);
 #endif
   // rfPolygonGroupMutualMerge (mFixedPOLYs, mPOLYs,  mMergedPOLYs, 5.0);
   // Free motion vectos space if any
   // We will have cell number of vectors for
   // copying the motion vectors. If we have no
   // motion vectors the little waste is ok
   if (!mPathMap.empty() && !isLabelProtein ())
     {
       for (uint32 i = 0; i < mVanchor.size(); i++)
     mVanchor[i].clear();
       for (uint32 i = 0; i < mVmoved.size(); i++)
     mVmoved[i].clear();
       mVanchor.clear();
       mVmoved.clear();
       mVanchor.resize (POLYs.size());
       mVmoved.resize (POLYs.size());
     }
   uint32 regionLabel = 1;
   bool wasEmpty = mFunctionMap.empty();
   // Cells are associate with locomotive regions by an index to the
   // regions that is stored in label data member of the cells. Note
   // each cell is through a pointer handle connected with kinetoscope
   // that owns regions
   // First time. Identify cells based on locomotive regions
   // @note Get the right frame index. Motion Based Segmentation is always
   // called with Moving time.
   rcWindow src =use4fixed();
   if (when != eFixed) src = use4moving();
   int32 videoFrameIndex = src.frameBuf()->frameIndex ();
   if (wasEmpty)
     {
       vector<rcPolygon>::iterator polyIter = POLYs.begin();
       vector<rcIRect>::iterator rectIter = cRects.begin();
       for (; polyIter != POLYs.end(); polyIter++, regionLabel++, rectIter++)
     {
       rc2Dvector cop;
       rc2Fvector motionCtr;
       double mass;
       if (!polyIter->centerOf (cop)) continue;
       // Validate the area by estimating its Hessian
       // Use motion center for origin
       if (!mPathMap.empty() && !isLabelProtein ())
         {
           rmAssert (regionLabel != 0);
           rc2Fvector df (-1.0f, -1.0f);
           if (!validate (*rectIter, df) || df.x() < 1.0)
         continue;
           connectFunction (*rectIter, *polyIter, motionCtr,
                    mVanchor[regionLabel-1], mVmoved[regionLabel-1]);
         }
       else // Use Irradiance
         {
           rcWindow tmp (src, *rectIter);
           rcShapeRef shaper = boost::shared_ptr<rcShape> (new rcShape (tmp));
           motionCtr = shaper->centerOfmass (rcShape::eImage);
           motionCtr += rc2Fvector (rectIter->ul());
         }
       // Now create the cell
       rmAssert (regionLabel!= 0);
       if (isCardiacCell () && have (eSelectedMyo))
         {
           vector< vector<rc2Fvector> >::iterator endsIter = mBodyEnds.begin();
           std::advance (endsIter, regionLabel - 1);
           rcVisualFunction vf ( this ,*polyIter, *endsIter,
                    mBodyRads[regionLabel - 1]);
           FILLFUNCTION;
         }
       else
         {
           rcVisualFunction vf ( this, motionCtr, *polyIter);
           FILLFUNCTION;
         }
     }
     } // if empty (that is the first time
   // New Generation ?
   // The detected off-springs at last moving are now accepted when moving-- is the
   // fixed.
   // If any cells @ fixed time are expecting, add them to the daughter list
   // @note daughters are set in moving at this time
   // In a cell lineage experiment, we are detecting the case where the cell is in the
   // final phases of mitosis where moving contains two newly separated daughter cells
   // After corrspondence, make sure we have cleared offsprings
   if (have(rcKinetoscope::eLineage))
     {
       reconcileNewGeneration ();
       rmAssert (mDaughterFunctionMap.empty());
       newGeneration (mFunctionMap, POLYs);
     }
   // Associate to moving
   if (!wasEmpty)
     {
       associate (mFunctionMap, POLYs);
     }
 }
bool rcKinetoscope::connectFunction (const rcIRect & r, const rcPolygon & p, rc2Fvector & moc, vector< rc2Fvector > & anc, vector< rc2Fvector > & mot) private
Definition at line 373 of file rc_kinetrack.cpp.
References rcMotionCenter::add(), rcMotionCenter::center(), rcPolygon::contains(), rcRectangle< T >::ll(), mPathMap, rcRectangle< T >::ul(), rcRectangle< T >::ur(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by connectedFunctions().
 {
   rcMotionPathMap::iterator dm;
   rcMotionCenter com;
   for (int32 j = r.ul().y(); j < r.ll().y(); j++)
     {
       for (int32 i = r.ul().x(); i < r.ur().x(); i++)
     {
       rcIPair ij (i, j);
       rc2Dvector dij (ij);
       if (!p.contains (dij)) continue;
       // Get the key for this ij and this time
       int32 index = (((i)<<16)+(j));
       dm = mPathMap.find (index);
       if (dm == mPathMap.end()) continue;
       // Accumulate info from this motion path
       rc2Fvector dM = dm->second.position () - dm->second.anchor ();
       com.add (dm->second.position (), dM);
       // Register the motion vectors for this cell
       anc.push_back (dm->second.anchor());
       mot.push_back (dm->second.position());
     }
     }
   return com.center (moc);
 }
int32 rcKinetoscope::count () const
Definition at line 104 of file rc_kineframe.cpp.
References mCount.
Referenced by debug(), dumpPolys(), frame(), frameCount(), reconcileNewGeneration(), reichardt(), resultTime(), start(), and stepDirectedFlowPreFill().
 {
   return mCount;
 }
void rcKinetoscope::createFunctionSpecificObjects () private
Definition at line 883 of file rc_kinetoscope.cpp.
References rcOrganismInfo::eCardioMyocyte, rcOrganismInfo::eCardioMyocyteCalcium, rcOrganismInfo::eDanioRerio, rcOrganismInfo::eModel, rcRectangle< T >::height(), iframe(), rcWindow::isBound(), mClearImage, mFullImage, mMaskCellwFF, organism(), organismName(), rcWindow::setAllPixels(), and rcRectangle< T >::width().
Referenced by preSegmentedBodies(), and step().
 {
   if (organism() ==  rcOrganismInfo::eModel && organismName () == rcOrganismInfo::eDanioRerio)
     {
       if (!mFullImage.isBound())
     {
       mFullImage = rcWindow (iframe().width(), iframe().height());
       mFullImage.setAllPixels (255);
     }
       if (!mClearImage.isBound())
     {
       mClearImage = rcWindow (iframe().width(), iframe().height());
       mClearImage.setAllPixels (0);
     }
     }
   if (organismName() == rcOrganismInfo::eCardioMyocyte ||
       organismName() == rcOrganismInfo::eCardioMyocyteCalcium)
     {
       if (!mMaskCellwFF.isBound())
     mMaskCellwFF = rcWindow (iframe().width(), iframe().height());
     }
 }
double rcKinetoscope::currentTime () const inline
Definition at line 452 of file rc_kinetoscope.h.
References rc1Xform::mapVector(), mCurrentAbsTimeStamp, mTemporal, and rcTimestamp::secs().
   {
     return mTemporal.mapVector (mCurrentAbsTimeStamp.secs());
   }
const rcWindow rcKinetoscope::debug () const
Definition at line 911 of file rc_kinetoscope.cpp.
References mDebugScreen.
Referenced by rcEngineImpl::muscleTracker().
 {
   return mDebugScreen;
 }
bool rcKinetoscope::debug (bool db) inline
Definition at line 486 of file rc_kinetoscope.h.
References count(), and mDebug.
 { if (count() < 2) mDebug = db; return mDebug;}
void rcKinetoscope::debugScreen (const rcWindow & image) private
Definition at line 578 of file rc_kinetoscope.cpp.
References rcWindow::copyPixelsFromWindow(), rcWindow::depth(), iframe(), isDebugOn(), and mDebugScreen.
Referenced by advance(), reichardt(), and start().
 {
   if (!isDebugOn ()) return;
   mDebugScreen = rcWindow (iframe().width(), iframe().height(), image.depth());
   mDebugScreen.copyPixelsFromWindow (image);
 }
double rcKinetoscope::deltaTime () const inline
Definition at line 434 of file rc_kinetoscope.h.
References rc1Xform::mapVector(), mElapsedTimeSecs, mLastElapsedTimeSecs, and mTemporal.
   {
     return mTemporal.mapVector (mElapsedTimeSecs - mLastElapsedTimeSecs);
   }
int32 rcKinetoscope::detail () const inline
Definition at line 275 of file rc_kinetoscope.h.
References mDetail.
Referenced by advance(), channelFixed(), channelFixedDirection(), channelFixedPast(), channelMoving(), channelMovingDirection(), channelMovingPast(), clear(), epiMotionField(), fixed(), fixedDirection(), fixedPast(), frame(), moving(), movingDirection(), movingPast(), rcKinetoscope(), reichardt(), start(), stepDirectedFlowPreFill(), and validate().
   {
     return (int32) mDetail;
   }
int32 rcKinetoscope::detail (const Detail d) inline
Definition at line 280 of file rc_kinetoscope.h.
References mDetail.
   {
     return mDetail = d;
   }
float rcKinetoscope::directedCellToCellMigration ()
Definition at line 741 of file rc_kinetoscope.cpp.
References mFunctionMap.
 {
   if (mFunctionMap.empty())
     {
       return 0;
     }
   list<rcVisualFunction>::const_iterator sit = mFunctionMap.begin();
   float sp (0.0f);
   for (; sit != mFunctionMap.end(); sit++)
     {
       sp += sit->directedCellPersistence();
     }
   sp /= mFunctionMap.size();
   return sp;
 }
void rcKinetoscope::dumpMap (ostream &) private
void rcKinetoscope::dumpPolys (ostream & output) private
Definition at line 47 of file rc_kinereport.cpp.
References count(), endl(), and mPOLYs.
 {
   output << "Time: " << count () << "Available Polys: " << mPOLYs.size() << endl;
   vector<rcPolygon>::iterator vc = mPOLYs.begin();
   for (; vc < mPOLYs.end(); vc++)
     {
       rc2Fvector cop;
       rcFRect fr;
       vc->centerOf (cop);
       vc->orthogonalEnclosingRect(fr);
       output << "(" << fr << "::" << cop << ")" << endl;
     }
 }
double rcKinetoscope::elapsedTime () const inline
Definition at line 443 of file rc_kinetoscope.h.
References rc1Xform::mapVector(), mElapsedTimeSecs, and mTemporal.
   {
     return mTemporal.mapVector (mElapsedTimeSecs);
   }
void rcKinetoscope::epiMotionField () protected
Definition at line 198 of file rc_kinefield.cpp.
References rsCorr5by5Line::count, rcWindow::depth(), detail(), rcAutoCorrelation::eFull, eMoving, iframe(), mCutOff, rcHistoStats::median(), mFrameData, mOrigin, mPathMap, rcWindow::pelPointer(), rcPixel8, rfHasSIMD(), rmAssert, rsCorr5by5Line::score, rcRectangle< T >::size(), target(), rcAutoCorrelation::update(), use4fixed(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by stepEpi().
 {
 #if 0
   int32 index (0);
   rcAutoCorrelation ac;
   rsCorr5by5Line result;
   const rcIPair& iOrigin = connectionPhase ();
   static const rcIPair unit (1,1);
   static const rcIPair two (2,2);
   rcIPair dimension = iframe().size();
   rcIPair targetSize = target() * two + unit;
   // @note this corresponds to requirement by gen5x5line that the model
   // it uses is -4,-4 fo the searchSize passed in.
   const rcIPair searchSpace (5, 5);
   rcIPair target4moments = targetSize + two + two;
   dimension -= target4moments; // dilated by half search size on both sides
   dimension += unit;
   rmAssert (dimension >= target4moments);
   rmAssert (searchSpace.x() == searchSpace.y());
   rmAssert (searchSpace.x() == 5);
   // @note this is the property of kinetoscope: 8bit is supported by SIMD on PPC.
   bool simd_ppc_or_pixel8 = rfHasSIMD () && use4fixed().depth() == rcPixel8;
   if (simd_ppc_or_pixel8)
     ac.update(use4fixed (), 2, rcAutoCorrelation::eFull, rcAutoCorrelation::eLine);
   else
     ac.update(use4fixed (), 2);
   // @note this is the property of kinetoscope:
   float cutOffVarianceTimesSize = mCutOff;
   cutOffVarianceTimesSize *= ((targetSize.x()* targetSize.y() - 1));
   cutOffVarianceTimesSize *= (targetSize.x()*targetSize.y());
   rcHistoStats h (use4fixed());
   const rcWindow& mAi = mFrameData[eMoving].direction (detail());
   rmAssert (mAi.depth() == rcPixel8);
   for (int32 j = iOrigin.y(); j < (dimension.y() + iOrigin.y()); j++)
     {
       const uint8 *gPtr = (const uint8 *) use4fixed().pelPointer (iOrigin.x(), j);
       const uint8 *dirPtr = (const uint8 *) mAi.pelPointer (iOrigin.x(), j);
       if (!(j%eScanDir)) continue;
       if (simd_ppc_or_pixel8)
     ac.gen5by5Line(target4moments, j - iOrigin.y(), result);
       else
     ac.genLine(targetSize, j - iOrigin.y(), result);
       rmAssert ((int32) result.count == dimension.x());
       for (int32 i = iOrigin.x(); i < (int32) (result.count+iOrigin.x()); i++, gPtr++, dirPtr++)
     {
       if (*gPtr <= h.median ()) continue;
       if (!(i % eScanDir)) continue;
       const uint32 ii (i - iOrigin.x());
       if (*(result.score[2][2] + ii ) < cutOffVarianceTimesSize)
         continue;
       static const rcAngle8 prepend8 (uint8 (64));
       rcAngle8 tt (*dirPtr);
       tt += prepend8;
       rcRadian rr (tt);
       rc2Fvector disp (1.0f, rr);
       const rc2Fvector anchor (i + mOrigin.x(), j + mOrigin.y());
       rcMotionVectorPath mvp (rcSharedKinetoscope (this), anchor, disp);
       index = (i<<16)+j;
       const pair<int32, rcMotionVectorPath> dmv (index, mvp);
       mPathMap.insert (dmv);
     }
     }
 #endif
 }
void rcKinetoscope::fieldMap (rcWindow &) const
void rcKinetoscope::fileOriginType (rcMovieFileOrgExt & orgx) inline
Definition at line 229 of file rc_kinetoscope.h.
References mOrgExt.
   { mOrgExt = orgx;}
const rcMovieFileOrgExt& rcKinetoscope::fileOriginType () const inline
Definition at line 232 of file rc_kinetoscope.h.
References mOrgExt.
Referenced by frame().
   { return mOrgExt;}
const rcWindow& rcKinetoscope::fixed () const inline
Definition at line 470 of file rc_kinetoscope.h.
References detail(), eFixed, and mFrameData.
Referenced by isBound(), rcEngineImpl::muscleTracker(), resultTime(), and use4fixed().
 { return mFrameData[eFixed].base(detail()); }
const rcWindow& rcKinetoscope::fixedDirection () const inline
Definition at line 475 of file rc_kinetoscope.h.
References detail(), eFixed, and mFrameData.
Referenced by selfSimilarMotionField_AttentiveCapture().
 { return mFrameData[eFixed].direction(detail()); }
const rcWindow& rcKinetoscope::fixedPast () const inline
Definition at line 471 of file rc_kinetoscope.h.
References detail(), eFixed, and mFrameData.
Referenced by isBound(), and use4fixed().
 { return mFrameData[eFixed].past (detail()); }
vector<rcPolygon>& rcKinetoscope::fixedPolygons () inline
Definition at line 501 of file rc_kinetoscope.h.
References mFixedPOLYs.
Referenced by visualDebugGraphics().
 { return mFixedPOLYs; }
const rcFRect& rcKinetoscope::fpframe () const inline protected
Definition at line 642 of file rc_kinetoscope.h.
References mFpFrame.
   {
     return mFpFrame;
   }
bool rcKinetoscope::frame (uint32 deltaFrames, const Time when) private
Definition at line 131 of file rc_kineframe.cpp.
References channelAvailable(), rcRectangle< T >::contains(), count(), rcFrame::depth(), detail(), eCoarse, eFileGrabber, eFrameStatusEOF, eFrameStatusOK, eMoving, eMutualChannel, eVideoCache, eVideoCacheStatusOK, fileOriginType(), rcFrame::height(), rcRectangle< T >::height(), isCardiacCell(), mark(), mChannelData, mCount, mCurrentAbsTimeStamp, mElapsedTimeSecs, mFg, mFgStatus, mFpFrame, mFrameData, mGlobalXform, mLastElapsedTimeSecs, mMomentMap, movieOriginGrayIsVisibleAlphaIsFlu, mProcessRect, mRect, mSource, mStartAbsTimeStamp, mUserRect, mVc, mVcStatus, rcMovieFileOrgExt::origin(), rcPixel32, rcPixel8, rfImageConvertARGBto8888(), rmAssert, rmExceptionMacro, rcTimestamp::secs(), startingAbsoluteTime(), uframe(), rcRectangle< T >::ul(), use4when(), rcFrame::width(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by start(), step(), stepContractile(), stepDirectedFlow(), and stepEpi().
 {
   rcSharedFrameBufPtr buf;
   if (mSource == eVideoCache)
     {
       uint32 c = mCount+deltaFrames;
       mVcStatus = mVc->getFrame (c, buf, 0);
       if (mVcStatus != eVideoCacheStatusOK)
           return false;
       rmAssert (mVc);
     }
   else if (mSource == eFileGrabber)
     {
       for (uint32 i = 0; i < deltaFrames; i++)
     {
       mFgStatus = mFg->getNextFrame (buf, 1);
       if (mFgStatus == eFrameStatusEOF)
           return false;
       rmAssert (mFgStatus == eFrameStatusOK);
     }
     }
   else
     {
       rmAssert (0);
     }
   // A blank rectangle implies entire
   // Else if the rectangle is within the frame use it.
   if (!count()) // First Frame
     {
       rcIRect thisBuf (0, 0, int32 (buf->width()),
                int32 (buf->height()));
       if (mUserRect == rcIRect (rcIPair (0,0), rcIPair (0,0)))
     mUserRect = thisBuf;
       else if (!thisBuf.contains (mUserRect))
     rmExceptionMacro(<< "Kinetoscope: invalid window");
       mStartAbsTimeStamp = buf-> timestamp ();
     }
   // Record The Current Time: in Msec
   // Note: do this before any processing
   mCurrentAbsTimeStamp = buf-> timestamp ();
   mLastElapsedTimeSecs = mElapsedTimeSecs;
   mElapsedTimeSecs = mCurrentAbsTimeStamp.secs() - startingAbsoluteTime ().secs();
   if (count() > 1)
     rmAssert (mElapsedTimeSecs > mLastElapsedTimeSecs);
   // @note Upto hear there are no assumption on the kind of frame
   // we have (number channels and so on. Frames should be 8 bit
   // with the exception of:
   // 1. fileOrgType movieOriginGrayIsVisibleAlphaIsFlu
   bool combinedPhaseAndFluor = (fileOriginType().origin () == movieOriginGrayIsVisibleAlphaIsFlu);
   rmAssert ((buf->depth() == rcPixel8) == (!combinedPhaseAndFluor));
   rcWindow tmp, channel;
   if (combinedPhaseAndFluor)
     {
       rmAssert (buf->depth() == rcPixel32);
       vector<rcWindow> planes;
       rcWindow argb (buf);
       rfImageConvertARGBto8888 (argb, planes);
       rmAssert(planes.size() == 4);
       channel = rcWindow (planes[0], uframe().origin().x(), uframe().origin().y(),
               uframe().width(),uframe().height());
       channel.atTime (argb);
       tmp = rcWindow (planes[1], uframe().origin().x(), uframe().origin().y(),
               uframe().width(),uframe().height());
       mark (eMutualChannel);
       tmp.atTime (argb);
     }
   else
     {
       tmp = rcWindow (buf, uframe().origin().x(), uframe().origin().y(),
         uframe().width(),uframe().height());
     }
   //@note: fix this!
   // double h = (sourceMotion () == eDirectedFlow ||
 //        sourceMotion () ==  eEpiFluorescence) ? 0.0 :
 //     laminarSuppression ();
   //@note this needs to be fixed
   mFrameData[when] = rc2LevelSpatialPyramid (tmp, 2, 5, 2,
                          0.0 , false);
   if (channelAvailable () && channel.isBound ())
     {
       mChannelData[when] = rc2LevelSpatialPyramid (channel,
                            2, 5, 2,
                            0.0 , false);
     }
   // @todo we need two Xforms but for now this is ok.
   if (detail () == eCoarse)
     mGlobalXform = rc2Xform (static_cast<rc2Xform> (mFrameData[when]));
   mRect = mFrameData[when].imageRect (detail());
   mFpFrame =  rcFRect ((float) mRect.ul().x(), (float) mRect.ul().y(),
                (float) mRect.width(), (float) mRect.height());
   //@note if we need to use motion field
   if (!isCardiacCell())
     {
       // update moment generators
       mMomentMap[when]->update(use4when(when));
       // update point corr
       if (when == eMoving && count() >= 1)
     {
       /* @note Within the context of kinetoscope's correspondence of fixed to
        * moving where fixed is before moving in time, "fixed" corresponds to
        * mdlWin and "moving" correspondes to imgWin.
        */
     //  mPointCorr.update (use4moving(), use4fixed(), *mMomentMap[eMoving], *mMomentMap[eFixed] );
     }
     }
   mProcessRect = mFrameData[when].region ();
   //  cerr << hex << "[" << (uint32) use4fixed().frameBuf()->rowPointer (0);
   //  if (mCount > 0)
   //    cerr << hex << ", " << (uint32) use4moving().frameBuf()->rowPointer (0);
   //  cerr << "]" << dec << endl;
   // @note: count from the start frame.
   mCount ++;
   return true;
 }
int32 rcKinetoscope::frameCount () const private
Definition at line 109 of file rc_kineframe.cpp.
References count(), eFileGrabber, eVideoCache, mFg, mSource, mVc, and rmAssert.
Referenced by measure(), reconcile(), start(), stepEpi(), and update().
 {
   int32 count (0);
   if (mSource == eVideoCache)
     {
       rmAssert (mVc);
       count = mVc->frameCount ();
     }
   else if (mSource == eFileGrabber)
     {
       rmAssert (mFg);
       count = mFg->frameCount ();
     }
   else
     {
       rmAssert (1);
     }
   return count;
 }
const int32 rcKinetoscope::frames () const inline
Definition at line 235 of file rc_kinetoscope.h.
References mFc.
   { return mFc; }
bool rcKinetoscope::have (enum Option what) const
Definition at line 613 of file rc_kinetoscope.cpp.
References mOptions.
Referenced by canStep(), channelAvailable(), clear(), connectedFunctions(), mark(), and visualDebugGraphics().
 {
   return mOptions[what];
 }
const rcIRect & rcKinetoscope::iframe () const
Definition at line 593 of file rc_kinetoscope.cpp.
References mRect.
Referenced by canonicalMotionField(), createFunctionSpecificObjects(), debugScreen(), epiMotionField(), selfSimilarMotionField(), and start().
 {
   return mRect;
 }
const rc1Xform& rcKinetoscope::imageFromPhysical () const
bool rcKinetoscope::isBound () protected
Definition at line 878 of file rc_kinetoscope.cpp.
References fixed(), fixedPast(), moving(), and movingPast().
Referenced by step(), stepContractile(), stepDirectedFlow(), and stepEpi().
 {
   return (fixedPast ().isBound() && moving ().isBound() && fixed ().isBound() && movingPast ().isBound());
 }
bool rcKinetoscope::isCardiacCell () const inline
Definition at line 215 of file rc_kinetoscope.h.
References rcOrganismInfo::eCardioMyocyte, rcOrganismInfo::eCardioMyocyteCalcium, rcOrganismInfo::eCardioMyocyteSelected, rcOrganismInfo::eCell, organism(), and organismName().
Referenced by advance(), connectedFunctions(), frame(), resultTime(), and step().
   {
     return (organism() == rcOrganismInfo::eCell &&
         (organismName() == rcOrganismInfo::eCardioMyocyte ||
          organismName() == rcOrganismInfo::eCardioMyocyteCalcium ||
          organismName() == rcOrganismInfo::eCardioMyocyteSelected));
   }
bool rcKinetoscope::isDebugOn () const inline
Definition at line 487 of file rc_kinetoscope.h.
References mDebug.
Referenced by debugScreen(), and start().
 { return mDebug; }
bool rcKinetoscope::isLabelProtein () const inline
Definition at line 223 of file rc_kinetoscope.h.
References rcOrganismInfo::eFluorescenceCluster, rcOrganismInfo::eProtein, rcOrganismInfo::eProteinP53, organism(), and organismName().
Referenced by connectedFunctions(), use4fixed(), and use4moving().
   {
     return (organism() == rcOrganismInfo::eFluorescenceCluster &&
         (organismName() == rcOrganismInfo::eProtein || organismName() == rcOrganismInfo::eProteinP53));
   }
bool rcKinetoscope::isOfOrganismName (rcOrganismInfo::OrganismName onm) const inline
Definition at line 209 of file rc_kinetoscope.h.
References mOname.
   { return mOname == onm; }
bool rcKinetoscope::isOfOrganismType (rcOrganismInfo::OrganismType ot) const inline
Definition at line 206 of file rc_kinetoscope.h.
References mOtype.
   { return mOtype == ot; }
bool rcKinetoscope::isOfOrganismTypeAndName (rcOrganismInfo::OrganismType ot, rcOrganismInfo::OrganismName onm) const inline
Definition at line 212 of file rc_kinetoscope.h.
References mOname, and mOtype.
   { return (mOtype == ot && mOname == onm); }
bool rcKinetoscope::isPointCorrOptimizationAvailable () const inline protected
Definition at line 651 of file rc_kinetoscope.h.
References eFixed, eMoving, and mMomentMap.
   {
     return (mMomentMap[eFixed] != 0 && mMomentMap[eMoving] != 0);
   }
bool rcKinetoscope::isWithin (const rc2Fvector &) const protected
bool rcKinetoscope::isWithin () const protected
Definition at line 726 of file rc_kinetoscope.cpp.
References mCount, and startFrame().
 {
   if (mCount <= startFrame()) return true;
   return false;
 }
bool rcKinetoscope::isWithin (const rcIRect & v) const protected
Definition at line 733 of file rc_kinetoscope.cpp.
References rcRectangle< T >::contains(), mRect, rcRectangle< T >::translate(), and rcRectangle< T >::ul().
 {
   // make a copy of v and translate it in to mRect
   rcIRect vcp = v;
   vcp.translate (mRect.ul());
   return (mRect.contains (vcp));
 }
void rcKinetoscope::keepPopulationMeasure () private
Definition at line 667 of file rc_kinetoscope.cpp.
References rcStatistics::add(), rcVisualFunction::eBeatInfo, mPopulationStats, rfMedian(), and visualBodies().
Referenced by stepContractile().
 {
   const list<rcVisualFunction>& vbs = visualBodies();
   list<rcVisualFunction>::const_iterator cell;
   vector<float> ameasure;
   for( cell = vbs.begin(); cell != vbs.end(); ++cell )
     {
       if (cell->have (rcVisualFunction::eBeatInfo))
     ameasure.push_back (cell->shortenning ());
     }
   if (ameasure.size())
     mPopulationStats.add (rfMedian (ameasure));
 }
rcIPair rcKinetoscope::kernelBorder () const protected
void rcKinetoscope::laminarSuppression (double over)
Definition at line 603 of file rc_kinetoscope.cpp.
References mCutOff.
   {
     if (over < 1.0) mCutOff = 1. / (1.0 - over);
   }
double rcKinetoscope::laminarSuppression () const
Definition at line 608 of file rc_kinetoscope.cpp.
References mCutOff.
   {
     return 1.0 - 1./mCutOff;
   }
bool rcKinetoscope::mark (enum Option what)
Definition at line 618 of file rc_kinetoscope.cpp.
References have(), and mOptions.
Referenced by frame(), preSegmentedBodies(), and start().
 {
   mOptions.set(what);
   return have (what);
 }
void rcKinetoscope::maxRadialSpeed (int32 sam)
Definition at line 845 of file rc_kinetoscope.cpp.
References mov(), mVmaxRadial, and rmAssert.
 {
   rmAssert (sam >= 2);
   mVmaxRadial = rcIPair (sam, sam); mov ();
 }
int32 rcKinetoscope::maxRadialSpeed () const
Definition at line 851 of file rc_kinetoscope.cpp.
References mVmaxRadial, and rcPair< T >::x().
Referenced by clear(), and selfSimilarMotionField().
 {
   return mVmaxRadial.x();
 }
void rcKinetoscope::measure (rcMotionPathMap & mp) protected
Definition at line 932 of file rc_kinetoscope.cpp.
Referenced by step(), stepContractile(), and stepEpi().
 {
   rcMotionPathMap::iterator pos;
   for (pos = mp.begin(); pos != mp.end(); pos++)
     {
       pos->second.measure();
     }
 }
void rcKinetoscope::measure (list< rcVisualFunction > & mp) protected
Definition at line 973 of file rc_kinetoscope.cpp.
References rcVisualFunction::eIsOutSide, frameCount(), general_exception::GetFile(), general_exception::GetLine(), rcTimingInfo::nextPass(), rcTimingInfo::printInfo(), rcTimingInfo::touch(), and general_exception::what().
 {
   list<rcVisualFunction>::iterator pos;
   rcTimingInfo profile (2, frameCount() + 1);
   profile.nextPass (0);
   for (pos = mp.begin(); pos != mp.end(); pos++)
     {
       profile.touch(0);
       try
     {
       pos->measure();
     }
       catch (general_exception& x)
     {
       pos->setState(rcVisualFunction::eIsOutSide);
       fprintf( stderr, "In Measure Function Caught general_exception %s %s %d\n",
            x.what(), x.GetFile (), x.GetLine () );
     }
       profile.touch(1);
     }
   profile.printInfo (1);
 }
void rcKinetoscope::minMobSizeInPixels (int32 ms)
Definition at line 801 of file rc_kinetoscope.cpp.
References mMinParea, and rmExceptionMacro.
Referenced by rcEngineImpl::muscleTracker().
 {
   if (ms < 5)
     rmExceptionMacro(<< "Kinetoscope: invalid organism size");
   mMinParea = ms;
 }
int32 rcKinetoscope::minMobSizeInPixels ()
Definition at line 809 of file rc_kinetoscope.cpp.
References mMinParea.
 {
   return mMinParea;
 }
void rcKinetoscope::mov () private
Definition at line 857 of file rc_kinetoscope.cpp.
References mMovingSize, mTargetRadius, and mVmaxRadial.
Referenced by maxRadialSpeed(), start(), and target().
 {
   mMovingSize = mTargetRadius + mVmaxRadial;
 }
const rcWindow& rcKinetoscope::moving () const inline
Definition at line 473 of file rc_kinetoscope.h.
References detail(), eMoving, and mFrameData.
Referenced by isBound(), resultTime(), and use4moving().
 {return mFrameData[eMoving].base(detail()); }
const rcWindow& rcKinetoscope::movingDirection () const inline
Definition at line 474 of file rc_kinetoscope.h.
References detail(), eMoving, and mFrameData.
 {return mFrameData[eMoving].direction (detail()); }
const rcWindow& rcKinetoscope::movingPast () const inline
Definition at line 472 of file rc_kinetoscope.h.
References detail(), eMoving, and mFrameData.
Referenced by isBound(), and use4moving().
 { return mFrameData[eMoving].past (detail()); }
vector<rcPolygon>& rcKinetoscope::movingPolygons () inline
Definition at line 502 of file rc_kinetoscope.h.
References mPOLYs.
Referenced by visualDebugGraphics().
 { return mPOLYs; }
const rcIPair & rcKinetoscope::movingSize () const protected
Definition at line 862 of file rc_kinetoscope.cpp.
References mMovingSize.
 {
   return mMovingSize;
 }
void rcKinetoscope::newGeneration (list< rcVisualFunction > & cells, vector< rcPolygon > & regions)
Definition at line 585 of file rc_kinetrack.cpp.
References rcVisualFunction::eIsDividing, rcVisualFunction::eIsJustDivided, endl(), rcPolygon::intersects(), mDaughterFunctionMap, and rfRealEq().
Referenced by connectedFunctions().
 {
    // For each cell (plus a disc buffer ) that is dividing, check to see if it overlaps two polygons.
    // If it does create daughters from the polys
    list<rcVisualFunction>::iterator aliveCell = cells.begin();
    for (; aliveCell != cells.end(); aliveCell++)
      {
        // Get the current (fixed) polygon representing the cell
        rcPolygon cpg = aliveCell->polygons().back();
        // How many of the moving polygons intersect with it?
        // If I am dividing these could be the daughters
        vector<rcPolygon> groupIntersects;
        if (aliveCell->isState (rcVisualFunction::eIsDividing) && cpg.intersects (regions, groupIntersects, 0.1f) &&
        groupIntersects.size() == 2 &&  rfRealEq (aliveCell->cQuality (), 1.0f, 0.01f))
      {
        // Do these polys belong to any other cells ?
        // Create daughter cells and set the cell to divided
        aliveCell->grow (groupIntersects, mDaughterFunctionMap);
        aliveCell->setState (rcVisualFunction::eIsJustDivided, true);
 #ifdef TRACKDEBUG
        cerr << "Cell " << aliveCell->id () << "Intersects with 2 polys" << endl;
 #endif
      }
      }
 }
rcKinetoscope& rcKinetoscope::operator= (const rcKinetoscope &) private
rcOrganismInfo::OrganismType rcKinetoscope::organism () const inline
Definition at line 200 of file rc_kinetoscope.h.
References mOtype.
Referenced by advance(), createFunctionSpecificObjects(), isCardiacCell(), isLabelProtein(), rcVisualFunction::rcVisualFunction(), start(), and step().
   { return mOtype;}
rcOrganismInfo::OrganismName rcKinetoscope::organismName () const inline
Definition at line 203 of file rc_kinetoscope.h.
References mOname.
Referenced by advance(), createFunctionSpecificObjects(), isCardiacCell(), isLabelProtein(), rcVisualFunction::rcVisualFunction(), start(), and step().
   { return mOname;}
void rcKinetoscope::periodicMotion (float p)
Definition at line 815 of file rc_kinetoscope.cpp.
References mPeriodicity.
Referenced by rcEngineImpl::muscleTracker(), and rcVisualFunction::rcVisualFunction().
 {
   mPeriodicity = p;
 }
float rcKinetoscope::periodicMotion () const
Definition at line 820 of file rc_kinetoscope.cpp.
References mPeriodicity.
 {
   return mPeriodicity;
 }
const rcIRect & rcKinetoscope::pframe () const
Definition at line 598 of file rc_kinetoscope.cpp.
References mProcessRect.
Referenced by selfSimilarMotionField_AttentiveCapture().
 {
   return mProcessRect;
 }
uint32 rcKinetoscope::phase () const
Definition at line 586 of file rc_kinetoscope.cpp.
References mPhase.
 { return mPhase; }
const rc1Xform& rcKinetoscope::physicalFromImage () const
const rcPointCorrelation& rcKinetoscope::pointCorr () const inline private
Definition at line 737 of file rc_kinetoscope.h.
References mPointCorr.
 { return mPointCorr; }
const rcStatistics & rcKinetoscope::populationMeasures () const
Definition at line 685 of file rc_kinetoscope.cpp.
References mPopulationStats.
 {
   return mPopulationStats;
 }
bool rcKinetoscope::preProcessConnect () const inline protected
Definition at line 660 of file rc_kinetoscope.h.
Referenced by connectedFunctions().
   {
     return false;
   }
void rcKinetoscope::preSegmentedBodies (const vector< rcPolygon > & bodies)
Definition at line 110 of file rc_kinestep.cpp.
References createFunctionSpecificObjects(), mCount, mMaskCellwFF, mPrePOLYs, rcFillPolygon(), rcWindow::setAllPixels(), and startFrame().
Referenced by rcEngineImpl::muscleTracker().
 {
   createFunctionSpecificObjects ();
   if (mCount <= startFrame())
     {
       mPrePOLYs = bodies;
       const uint8 bg = 0, fg = 0xff;
       mMaskCellwFF.setAllPixels(bg);
       for (uint32 ci = 0; ci < bodies.size(); ci++)
     rcFillPolygon(bodies[ci], mMaskCellwFF, fg);
     }
 }
void rcKinetoscope::preSegmentedBodies (const vector< vector< rc2Fvector > > & bodyEnds, vector< float > & rads)
Definition at line 124 of file rc_kinestep.cpp.
References rc2dVector< T >::angle(), createFunctionSpecificObjects(), eSelectedMyo, rc2dVector< T >::isNull(), rc2dVector< T >::len(), mark(), mBodyEnds, mBodyRads, mCount, mPrePOLYs, rmExceptionMacro, startFrame(), and rcPolygon::transform().
 {
   if (bodyEnds.size() == 0 || bodyEnds.size() != rads.size())
     {
       rmExceptionMacro(<<"Inconsistent Selection Data");
     }
   createFunctionSpecificObjects ();
   if (mCount <= startFrame())
     {
       for (uint32 i = 0; i < bodyEnds.size(); i++)
     {
       vector<rc2Fvector> ends = bodyEnds[i];
       // Create a polygon using the ellipse formed by the ends.
       // Rotate and move it to the center of the line contecting the ends.
       rc2Fvector m = (ends[0] + ends[1]) / 2.0f;
       rc2Fvector d = ends[1] - ends[0];
       if (d.isNull ())
         {
           rmExceptionMacro(<<"Length too short");
         }
       float a =d.len ();
       a = a / 2.0f;
       rcPolygon poly (a, rads[i], 12);
       static const rcDPair noscale (1.0, 1.0);
       rc2Xform xt (rcMatrix_2d (d.angle (), noscale), m);
       poly.transform (xt);
       mPrePOLYs.push_back (poly);
       mBodyEnds.push_back (ends);
       mBodyRads.push_back(rads[i]);
     }
       mark (eSelectedMyo);
     }
 }
void rcKinetoscope::printConnect () private
Definition at line 1064 of file rc_kinetoscope.cpp.
References connect().
 {
   cerr << connect();
 }
void rcKinetoscope::printConnected () private
Definition at line 1069 of file rc_kinetoscope.cpp.
References connected().
 {
   cerr << connected();
 }
void rcKinetoscope::printMap () private
Definition at line 1059 of file rc_kinetoscope.cpp.
 {
   //    dumpMap (cerr);
 }
void rcKinetoscope::printPolys () private
Definition at line 1054 of file rc_kinetoscope.cpp.
 {
   //    dumpPolys (cerr);
 }
void rcKinetoscope::rawDirectStats (rcHistoStats &)
void rcKinetoscope::rawSpeedStats (rcStatistics & stats)
Definition at line 781 of file rc_kinetoscope.cpp.
References rcStatistics::add(), mPathMap, mSnapStats, and rcStatistics::n().
 {
   if (mSnapStats.n())
     {
       stats = mSnapStats;
       return;
     }
   rcMotionPathMap::iterator pos;
   for (pos = mPathMap.begin(); pos != mPathMap.end(); pos++)
     {
       mSnapStats.add (pos->second.motion().len ());
     }
   stats = mSnapStats;
 }
void rcKinetoscope::reconcile (rcMotionPathMap & mp) protected
Definition at line 953 of file rc_kinetoscope.cpp.
Referenced by step(), stepContractile(), and stepEpi().
 {
 //  if ((organism() == rcOrganismInfo::eFluorescenceCluster &&
 //       ( organismName() == rcOrganismInfo::eProteinP53 ||
 //  organismName() == rcOrganismInfo::eProtein)))
 //    {
 //      rcWindow tmp (connect().size(), connect().depth());
 //      tmp.copyPixelsFromWindow (connect());
 //      rfGaussianConv (tmp, connect(), 3);
 //    }
 //  else
    {
      rcMotionPathMap::iterator pos;
      for (pos = mp.begin(); pos != mp.end(); pos++)
        pos->second.reconcile ();
    }
 }
void rcKinetoscope::reconcile (list< rcVisualFunction > & mp) protected
Definition at line 1026 of file rc_kinetoscope.cpp.
References rcVisualFunction::eIsOutSide, frameCount(), general_exception::GetFile(), general_exception::GetLine(), and general_exception::what().
 {
   list<rcVisualFunction>::iterator pos;
   uint32 i = 0, initialSize (mp.size());
   rcTimingInfo profile (2, frameCount() + 1);
   profile.nextPass (0);
   for (pos = mp.begin(); i < initialSize; pos++, i++)
     {
       profile.touch(0);
       try
     {
       pos->reconcile();
     }
       catch (general_exception& x)
     {
       pos->setState(rcVisualFunction::eIsOutSide);
       fprintf( stderr, "In Reconcile Function Caught general_exception %s %s %d\n",
            x.what(), x.GetFile (), x.GetLine () );
     }
       profile.touch(1);
     }
   profile.printInfo (1);
 }
void rcKinetoscope::reconcileNewGeneration ()
Definition at line 614 of file rc_kinetrack.cpp.
References count(), endl(), mDaughterFunctionMap, mFunctionMap, and rmMax.
Referenced by connectedFunctions().
 {
   if (mDaughterFunctionMap.empty()) return;
   // First find the highest Id used thusfar
   list<rcVisualFunction>::iterator vfunc = mFunctionMap.begin();
   uint32 numId (0);
   for (; vfunc != mFunctionMap.end(); vfunc++)
     {
       numId = rmMax (numId, vfunc->mId);
     }
 #ifdef TRACKDEBUG
   cerr << "Reconcile [" << count() << "]: ";
 #endif
   // If there are any daughters from last frame add them
   // This frames Id start at the next available id.
   numId++;
 #ifdef TRACKDEBUG
   cerr << "New Generation Cell #s start @ " << numId << endl;
 #endif
   vfunc = mDaughterFunctionMap.begin();
   for (; vfunc != mDaughterFunctionMap.end(); vfunc++, numId++)
     {
       vfunc->mId = numId;
       mFunctionMap.push_back (*vfunc);
 #ifdef TRACKDEBUG
       cerr << "{" << endl << *vfunc << "}" << endl;
 #endif
     }
   mDaughterFunctionMap.clear ();
 }
void rcKinetoscope::reichardt (Time when) protected
Definition at line 271 of file rc_kineframe.cpp.
References count(), debugScreen(), detail(), rcWindow::height(), mFrameData, mFullImage, mLsm, mSimBuffer, mSimPipe, rcPixel32, rfImageConvert8888ToARGB(), rfImageConvert8ToARGB(), rmAssert, rcWindow::vImage(), and rcWindow::width().
Referenced by stepDirectedFlow().
 {
   if (count () <= mSimPipe)
     {
       mSimBuffer.push_back (mFrameData[when].base (detail ()));
       if (mSimBuffer.size() == (uint32) mSimPipe)
     {
       rmAssert (mLsm->fill (mSimBuffer.begin(), mSimBuffer.end()));
     }
     }
   else if (count() > mSimPipe)
     {
       mLsm->update (&mFrameData[when].base (detail ()));
       rcWindow ttc, ttd;
       mLsm->ttc (ttc, ttd);
       // resultant_pixel_color = top_pixel_alpha/255 * top_pixel_color + (1 - top_pixel_alpha/255) * bottom_pixel_color
       vector<rcWindow> iargb (4);
       iargb[0] = ttc;
       iargb[1] = mFullImage;
       iargb[2] = mFrameData[when].base (detail ());
       iargb[3] = mFrameData[when].base (detail ());
       rcWindow grayargb = rfImageConvert8ToARGB (mFrameData[when].base (detail ()), mFullImage);
       rcWindow redmask = rcWindow (grayargb.width(), grayargb.height(), rcPixel32);
       rfImageConvert8888ToARGB (iargb, redmask);
       vImage_Buffer top, bot, dst;
       grayargb.vImage (bot);
       redmask.vImage (top);
       vImage_Error ve;
       rcWindow blend = rcWindow (grayargb.width(), grayargb.height(), rcPixel32);
       blend.vImage (dst);
       ve = vImageAlphaBlend_ARGB8888 (&top, &bot, &dst, kvImageNoFlags);
       iargb[0] = ttd;
       iargb[1] = mFrameData[when].base (detail ());
       iargb[2] = mFrameData[when].base (detail ());
       iargb[3] = mFullImage;
       rfImageConvert8888ToARGB (iargb, redmask);
       ve = vImageAlphaBlend_ARGB8888 (&top, &dst, &bot, kvImageNoFlags);
       debugScreen (grayargb);
     }
 }
void rcKinetoscope::reset ()
Definition at line 630 of file rc_kinetoscope.cpp.
References mOptions.
 {
   mOptions.reset ();
 }
rcTimestamp rcKinetoscope::resultTime () const
Definition at line 487 of file rc_kinetoscope.cpp.
References count(), fixed(), rcWindow::frameBuf(), isCardiacCell(), moving(), and rcFrame::timestamp().
Referenced by rcEngineImpl::muscleTracker().
 {
   rcTimestamp now = (isCardiacCell ()) ?  fixed ().frameBuf()->timestamp() :
     (count() > 1) ? moving().frameBuf()->timestamp() :
     fixed ().frameBuf()->timestamp();
   return now;
   }
uint32 rcKinetoscope::sample () const
Definition at line 585 of file rc_kinetoscope.cpp.
References mSample.
Referenced by step(), stepContractile(), stepDirectedFlow(), and stepEpi().
 { return mSample ; }
const rc1Xform& rcKinetoscope::secondsToUnits () const inline
Definition at line 327 of file rc_kinetoscope.h.
References mTemporal.
   {
     return mTemporal;
   }
void rcKinetoscope::selfSimilarMotionField () protected
Definition at line 63 of file rc_kinefield.cpp.
References iframe(), maxRadialSpeed(), pad(), rmAssert, selfSimilarMotionField_AttentiveCapture(), rcImageSetRegister< Iterator >::setRegister(), rcRectangle< T >::trim(), use4fixed(), use4moving(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by step().
 {
 #if 0
   // Calculate Registeration between fixed and moving.
   rmAssert (registeredFrameAnchors ().size() == 2);
   vector<rcWindow> fixedandmoving (2);
   rcIPair speed (maxRadialSpeed(), maxRadialSpeed());
   //@note this is a guess at good inner rectangle to use. We use hillclimbing to
   // register the frames. To do that:
   // 1. be large enough to allow registration among large number of cases
   // 2. the pad does not include the only unique features in the frame
   static float pad = 2.5f/100.0f; // percent shrinkage
   int32 tpad = (int32) (std::min (iframe().size().x(), iframe().size().y()) * pad);
   rcRectangle<int32> landmark = iframe().trim (tpad);
   fixedandmoving[0] = rcWindow (use4fixed (), landmark, tpad);
   fixedandmoving[1] = rcWindow (use4moving (), landmark, tpad);
   typedef vector<rcWindow>::iterator iterator;
   rcImageSetRegister<iterator> reg (fixedandmoving.begin (), fixedandmoving.end());
   reg.setRegister (fixedandmoving.begin (), speed, registeredFrameAnchors());
   mMovingFrameTranslation.x() = (int32) registeredFrameAnchors()[1].x() - speed.x();
   mMovingFrameTranslation.y() = (int32) registeredFrameAnchors()[1].y() - speed.y();
 #endif
   // Appraise sites for motion vector calculation
   selfSimilarMotionField_AttentiveCapture ();
 }
void rcKinetoscope::selfSimilarMotionField_AttentiveCapture () protected
Definition at line 111 of file rc_kinefield.cpp.
References rsCorr5by5Line::count, rcWindow::depth(), rcAutoCorrelation::eFull, fixedDirection(), mCutOff, mOrigin, mPathMap, rcWindow::pelPointer(), pframe(), rcPixel8, rfHasSIMD(), rmAssert, rsCorr5by5Line::score, sourceMotion(), rcAutoCorrelation::update(), use4fixed(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by selfSimilarMotionField().
 {
 #if 0
   int32 index (0);
   rcAutoCorrelation ac;
   rsCorr5by5Line result;
   const rcIPair& iOrigin = mOrigin;
   const rcIPair dimension = connectionSize ();
   const rcIPair targetSize = targetRect().size();
   // @note this corresponds to requirement by gen5x5line that the model
   // it uses is -4,-4 fo the searchSize passed in.
   const rcIPair searchSpace (5, 5);
   rcIPair target4moments = iOrigin * sTwo + rcIPair ((int32) (mOrigin.x()+mOrigin.x()),
                             (int32) (mOrigin.y()+mOrigin.y()));
   rmAssert (dimension >= target4moments);
   rmAssert (searchSpace.x() == searchSpace.y());
   rmAssert (searchSpace.x() == 5);
   // @note this is the property of kinetoscope: 8bit is supported by SIMD on PPC.
   bool simd_ppc_or_pixel8 = rfHasSIMD () && use4fixed().depth() == rcPixel8;
   if (simd_ppc_or_pixel8)
     ac.update(use4fixed (), 2, rcAutoCorrelation::eFull, rcAutoCorrelation::eLine);
   else
     ac.update(use4fixed (), 2, rcAutoCorrelation::eFull, rcAutoCorrelation::eLine, false, targetSize);
   // @note this is the property of kinetoscope:
   float cutOffVarianceTimesSize = mCutOff;
   cutOffVarianceTimesSize *= ((targetSize.x()* targetSize.y() - 1));
   cutOffVarianceTimesSize *= (targetSize.x()*targetSize.y());
   const rcWindow& mAi = fixedDirection ();
   rmAssert (mAi.depth() == rcPixel8);
   rcRectangle<int32> localPframe (pframe ());
   translateFromFrame (localPframe);
   for (int32 j = iOrigin.y(); j < (dimension.y() + iOrigin.y()); j++)
     {
       if (!localPframe.contains (rcIPair (iOrigin.x(), j) )) continue;
       // Fetch the row pointer for grad max.
       const uint8 *dirPtr = (const uint8 *) mAi.pelPointer (iOrigin.x(), j);
       if (eScanDir > 1 && !(j%eScanDir)) continue;
       if (simd_ppc_or_pixel8)
     {
       ac.gen5by5Line(target4moments, j - iOrigin.y(), result);
       rmAssert ((int32) result.count == dimension.x());
     }
       else
     {
       ac.genLine(targetSize, j - iOrigin.y(), result);
       rmAssert ((int32) result.count == (dimension.x()));
     }
       for (int32 i = iOrigin.x(); i < (int32) (result.count+iOrigin.x()); i++, dirPtr++)
     {
       if (eScanDir > 1 && !(i % eScanDir)) continue;
       if (!localPframe.contains (rcIPair (i, j) )) continue;
       const uint32 ii (i - iOrigin.x());
       if (sourceMotion () == eLongExposure && ! simd_ppc_or_pixel8 &&
           (*(result.score[2][2] + ii ) ) < 1)
         continue;
       else if (*(result.score[2][2] + ii ) < cutOffVarianceTimesSize)
         continue;
       static const rcAngle8 prepend8 (uint8 (64));
       rcAngle8 tt (*dirPtr);
       tt += prepend8;
       rcRadian rr (tt);
       rc2Fvector disp (1.0f, rr);
       const rc2Fvector anchor (i + mOrigin.x(), j + mOrigin.y());
       rcMotionVectorPath mvp (rcSharedKinetoscope (this), anchor);
       index = (i<<16)+j;
       const pair<int32, rcMotionVectorPath> dmv (index, mvp);
       mPathMap.insert (dmv);
     }
     }
 #endif
 }
void rcKinetoscope::selfSimilarMotionField_UnderSampled () protected
rcSharedKinetoscope rcKinetoscope::shared () inline
Definition at line 179 of file rc_kinetoscope.h.
     {
          return shared_from_this();
     }
float rcKinetoscope::sizeMultiplier () const
Definition at line 867 of file rc_kinetoscope.cpp.
References mSizeMultiplier.
 {
   return mSizeMultiplier;
 }
void rcKinetoscope::sizeMultiplier (float ms)
Definition at line 872 of file rc_kinetoscope.cpp.
References mSizeMultiplier.
 {
   mSizeMultiplier = ms;
 }
int32 rcKinetoscope::sourceMotion () const inline
Definition at line 243 of file rc_kinetoscope.h.
References mSourceMotion.
Referenced by advance(), rcEngineImpl::muscleTracker(), and selfSimilarMotionField_AttentiveCapture().
   {
     return mSourceMotion;
   }
int32 rcKinetoscope::sourceMotion (SourceMotion sm) inline
Definition at line 248 of file rc_kinetoscope.h.
References mSourceMotion.
   {
     return (mSourceMotion = sm);
   }
void rcKinetoscope::start () protected
Definition at line 496 of file rc_kinetoscope.cpp.
References channelAvailable(), clear(), connect(), connected(), count(), debugScreen(), detail(), eCanStep, rcOrganismInfo::eDanioRerio, eFileGrabber, eFixed, rcOrganismInfo::eFluorescenceCluster, rcOrganismInfo::eModel, eMoving, rcOrganismInfo::eProtein, rcOrganismInfo::eProteinP53, eVideoCache, frame(), frameCount(), rcRectangle< T >::height(), iframe(), isDebugOn(), mark(), mChannelData, mConnectionMap, mFc, mFrameData, mMomentMap, mMomGen0, mMomGen1, mov(), mPhase, mProcessRect, mSample, mSource, organism(), organismName(), rcPixel8, rmAssert, rmExceptionMacro, rcWindow::setAllPixels(), startFrame(), stepDirectedFlowPreFill(), temporalScale(), updateProcessingTime(), and rcRectangle< T >::width().
Referenced by visualFunctionMap().
 {
     rmAssert (mSource == eFileGrabber || mSource == eVideoCache);
     rmAssert (mFrameData.size () == 2);
     rmAssert (mChannelData.size () == 2);
     mFc = frameCount();
     clear ();
     rmAssert (count() == 0);
     if (mFc < int32 (2 * (mPhase + mSample)))
       rmExceptionMacro(<< "Kinetoscope: sequence too short");
     // Connect moment generators
     mMomentMap[eFixed] = &mMomGen0;
     mMomentMap[eMoving] = &mMomGen1;
     // Fetch the first frame
     frame (startFrame(), eFixed);
     if (mProcessRect.width() <= 0 || mProcessRect.height() <= 0)
       rmExceptionMacro (<< "Kinetoscope: Region Too Small");
     mov ();
   //  mCutOff = defaultCutOff;
     /*
      * Record The Start Time In MilliSeconds
      */
     temporalScale (1000.0f);
     // Create the connected component image
     // @todo: Update for MultiResolution
     // @note can use shallow copy in some cases.
     mConnectionMap[eMoving] = rcWindow (iframe().size(), rcPixel8);
     connect().setAllPixels (uint32 (0));
     mConnectionMap[eFixed] = rcWindow (iframe().size(), rcPixel8);
     connected().setAllPixels (uint32 (0));
     //
     // Create the potentialMap
     //   mXvelocityField = rcWindow (iframe().size(), rcPixel16);
     //     mYvelocityField = rcWindow (iframe().size(), rcPixel16);
     //     mXvelocityField.setAllPixels (uint32 (0));
     //     mYvelocityField.setAllPixels (uint32 (0));
     // Claim
     mark (eCanStep);
   if (organism() ==  rcOrganismInfo::eModel && organismName () == rcOrganismInfo::eDanioRerio)
     {
       stepDirectedFlowPreFill ();
     }
   // Debugging display
   if (isDebugOn ())
     {
   if (organism() !=  rcOrganismInfo::eModel || organismName () != rcOrganismInfo::eDanioRerio)
     {
       if ((organism() == rcOrganismInfo::eFluorescenceCluster &&
        ( organismName() == rcOrganismInfo::eProteinP53 ||
          organismName() == rcOrganismInfo::eProtein)))
     {
       if (channelAvailable ())
         debugScreen (mChannelData[eFixed].base (detail ()));
       else
         {
           debugScreen (mFrameData[eFixed].base(detail ()));
         }
     }
       else
     debugScreen (mFrameData[eFixed].base(detail ()));
     }
     }
   updateProcessingTime ();
 }
uint32 rcKinetoscope::startFrame () const private
Definition at line 91 of file rc_kineframe.cpp.
References eFileGrabber, eVideoCache, mPhase, mSource, and rmAssert.
Referenced by connectedFunctions(), isWithin(), preSegmentedBodies(), and start().
 {
     switch ( mSource ) {
         case eVideoCache:
             return mPhase;
         case eFileGrabber:
             return mPhase+1;
         default:
             rmAssert( 0 );
             return mPhase;
     }
 }
const rcTimestamp& rcKinetoscope::startingAbsoluteTime () const inline
Definition at line 462 of file rc_kinetoscope.h.
References mStartAbsTimeStamp.
Referenced by frame(), and rcVisualFunction::rcVisualFunction().
 { return mStartAbsTimeStamp; }
int32 rcKinetoscope::step (uint32 steps = 1, bool keepgoing = 1)
Definition at line 44 of file rc_kinestep.cpp.
References connectedFunctions(), createFunctionSpecificObjects(), rcOrganismInfo::eDanioRerio, rcOrganismInfo::eFluorescenceCluster, rcOrganismInfo::eModel, eMoving, rcOrganismInfo::eProtein, rcOrganismInfo::eProteinP53, frame(), isBound(), isCardiacCell(), measure(), mFunctionMap, mPathMap, mPOLYs, mSnapStats, organism(), organismName(), reconcile(), rcStatistics::reset(), rmAssert, sample(), selfSimilarMotionField(), stepContractile(), stepDirectedFlow(), stepEpi(), update(), and updateProcessingTime().
Referenced by rcEngineImpl::muscleTracker().
 {
   // Create any objects / models we need for what we are doing
   // If they have not been create already
   createFunctionSpecificObjects ();
   if (isCardiacCell ())
     return stepContractile (steps, keepgoing);
   if (organism() ==  rcOrganismInfo::eModel && organismName () == rcOrganismInfo::eDanioRerio)
    return stepDirectedFlow (steps, keepgoing);
   if ((organism() == rcOrganismInfo::eFluorescenceCluster &&
       ( organismName() == rcOrganismInfo::eProteinP53 ||
     organismName() == rcOrganismInfo::eProtein)))
     return stepEpi (steps, keepgoing);
   if (!keepgoing || !steps) return 0;
   // Invalidate per frame statistics
   mSnapStats.reset ();
   // Fetch next. First throttle to the next one
   uint32 sampledSteps = steps * sample ();
   if ( !frame (sampledSteps, eMoving) )
       return 0;
   rmAssert (isBound());
   if (!mPathMap.empty()) mPathMap.clear();
   selfSimilarMotionField ();
   // Clear Temporal Polygons
   // Temporal Information is used by selfSimilarMotionField
   mPOLYs.clear ();
   // And measure motion of fixed() in moving
   measure (mPathMap);
   // And correspond from fixed() to moving
   // We are not calling update. Measure register the motion. Saving the function call update (mPathMap);
   // And register from fixed() to moving
   reconcile (mPathMap);
   // Motion based Segmentation
   connectedFunctions (eMoving, mPOLYs);
   // Measure their motion
   measure (mFunctionMap);
   // Update
   update (mFunctionMap);
   // Reconcile
   reconcile (mFunctionMap);
   updateProcessingTime ();
   return 1;
 }
int32 rcKinetoscope::stepContractile (uint32 steps = 1, bool keepgoing = 1)
Definition at line 169 of file rc_kinestep.cpp.
References connectedFunctions(), eFixed, eMoving, frame(), isBound(), keepPopulationMeasure(), mDisEdgeError, mDisGMEError, mDisPolarError, mDisVarError, measure(), mFunctionMap, mPathMap, mPOLYs, mSnapStats, reconcile(), rcStatistics::reset(), rmAssert, sample(), update(), and updateProcessingTime().
Referenced by step().
 {
   if (!keepgoing || !steps) return 0;
   // Invalidate per frame statistics
   mSnapStats.reset ();
   mDisVarError = 0;
   mDisGMEError = 0;
   mDisEdgeError = 0;
   mDisPolarError = 0;
   // Fetch next. First throttle to the next one
   uint32 sampledSteps = steps * sample ();
   if ( !frame (sampledSteps, eMoving) )
       return 0;
   rmAssert (isBound());
   if (!mPathMap.empty()) mPathMap.clear();
   mPOLYs.clear ();
   connectedFunctions (eFixed , mPOLYs);
   // Measure their motion
   measure (mFunctionMap);
   // Update
   update (mFunctionMap);
   // Reconcile
   reconcile (mFunctionMap);
   // Compute average shortening and store it as a population measure
   keepPopulationMeasure ();
   updateProcessingTime ();
   return 1;
 }
int32 rcKinetoscope::stepDirectedFlow (uint32 steps = 1, bool keepgoing = 1)
Definition at line 292 of file rc_kinestep.cpp.
References eMoving, frame(), isBound(), mDisEdgeError, mDisGMEError, mDisPolarError, mDisVarError, mSnapStats, reichardt(), rcStatistics::reset(), rmAssert, sample(), and updateProcessingTime().
Referenced by step().
 {
   if (!keepgoing || !steps) return 0;
   // Invalidate per frame statistics
   mSnapStats.reset ();
   mDisVarError = 0;
   mDisGMEError = 0;
   mDisEdgeError = 0;
   mDisPolarError = 0;
   // Fetch next. First throttle to the next one
   uint32 sampledSteps = steps * sample ();
   if ( !frame (sampledSteps, eMoving) )
       return 0;
   rmAssert (isBound());
   // Update Sims
   reichardt (eMoving);
   updateProcessingTime ();
   //@note removed advance. It is now in the main loop in engineimpl
   //  advance ();
   return 1;
 }
int32 rcKinetoscope::stepDirectedFlowPreFill ()
Definition at line 212 of file rc_kinestep.cpp.
References count(), detail(), eFixed, mFrameData, mSimBuffer, and mSimPipe.
Referenced by start().
 {
   if (count () <= mSimPipe)
     {
       mSimBuffer.push_back (mFrameData[eFixed].base (detail ()));
     }
 }
int32 rcKinetoscope::stepEpi (uint32 steps = 1, bool keepgoing = 1)
Definition at line 221 of file rc_kinestep.cpp.
References connectedFunctions(), eMoving, epiMotionField(), frame(), frameCount(), isBound(), measure(), mFunctionMap, mPathMap, mPOLYs, mSnapStats, rcTimingInfo::nextPass(), rcTimingInfo::printInfo(), reconcile(), rcStatistics::reset(), rmAssert, sample(), rcTimingInfo::touch(), update(), and updateProcessingTime().
Referenced by step().
 {
   if (!keepgoing || !steps) return 0;
   rcTimingInfo profile (10, frameCount () + 1);
   profile.nextPass (false);
   // Invalidate per frame statistics
   mSnapStats.reset ();
   // Fetch next. First throttle to the next one
   uint32 sampledSteps = steps * sample ();
   profile.touch (0);
   if ( !frame (sampledSteps, eMoving) )
       return 0;
   profile.touch (1);
   rmAssert (isBound());
   profile.touch (2);
   if (!mPathMap.empty()) mPathMap.clear();
   epiMotionField ();
   profile.touch (3);
   // Clear Temporal Polygons
   // Temporal Information is used by selfSimilarMotionField
   mPOLYs.clear ();
   // And measure motion of fixed() in moving
   measure (mPathMap);
   // And correspond from fixed() to moving
   // We are not calling update. Measure register the motion. Saving the function call update (mPathMap);
   // And register from fixed() to moving
   reconcile (mPathMap);
   connectedFunctions (eMoving, mPOLYs);
   profile.touch (4);
   // Measure their motion
   measure (mFunctionMap);
   profile.touch (5);
   // Update
   update (mFunctionMap);
   profile.touch (6);
   profile.printInfo (4);
   // Reconcile
   reconcile (mFunctionMap);
   profile.touch (7);
   updateProcessingTime ();
   //@note removed advance. It is now in the main loop in engineimpl
   return 1;
 }
void rcKinetoscope::target (int32 sam)
Definition at line 835 of file rc_kinetoscope.cpp.
References mov(), and mTargetRadius.
 {
   mTargetRadius = rcIPair (sam, sam); mov();
 }
rcIPair rcKinetoscope::target () const
Definition at line 840 of file rc_kinetoscope.cpp.
References mTargetRadius.
Referenced by canonicalMotionField(), clear(), and epiMotionField().
 {
   return mTargetRadius;
 }
ostream & rcKinetoscope::temporalResults (ostream & output1, ostream & output2)
Definition at line 62 of file rc_kinereport.cpp.
References rcDegree::Double(), endl(), rcUINT32_MAX, rmMin, and visualBodies().
 {
   uint32 maxNumberOfFrames (rcUINT32_MAX);
   uint32 maxNumberOfCycles (rcUINT32_MAX);
   const list<rcVisualFunction>& vbs = visualBodies();
   output1 << "Positions in pixels, top to bottom, left to right" << endl;
   // First Line Cell IDs + Positions
   list<rcVisualFunction>::const_iterator cell;
   for( cell = vbs.begin(); cell != vbs.end(); ++cell )
     {
       output1 << "\t" << cell->id() << "\t" << "X" << (int32) cell->position().x()  << "Y" << (int32) cell->position().y() << "\t";
       maxNumberOfFrames = rmMin (maxNumberOfFrames, cell->interpolatedMin().size());
     }
   output1 << endl;
   // 2nd to frame size time and length
   for (uint32 i = 0; i < maxNumberOfFrames - 1;i++)
     {
       for( cell = vbs.begin(); cell != vbs.end(); ++cell )
     {
       if (i < cell->interpolatedMin().size())
         {
           float x (cell->interpolatedMin()[i].x());
           float y (cell->interpolatedMin()[i].y());
           output1 << std::fixed << "\t" << x << "\t" << y;
         }
     }
     }
   output1 << endl << endl;
   // Two different outputs
   for( cell = vbs.begin(); cell != vbs.end(); ++cell )
     {
       output2 << "\t" << cell->id() << "\t" << "X" << (int32) cell->position().x()  << "Y" << (int32) cell->position().y() << "\t";
       maxNumberOfCycles = rmMin (maxNumberOfCycles, cell->peakAngles().size());
     }
   output2 << endl;
   for (uint32 i = 0; i < maxNumberOfCycles - 1;i++)
     {
       for( cell = vbs.begin(); cell != vbs.end(); ++cell )
     {
       if (i < cell->peakAngles().size())
         {
           rcDegree c (cell->peakAngles()[i].x());
           rcDegree r (cell->peakAngles()[i].y());
           output2 << std::fixed << "\t" << c.Double() << "\t" << r.Double();
         }
     }
     }
   return output1;
 }
void rcKinetoscope::temporalScale (float ts) inline
Definition at line 337 of file rc_kinetoscope.h.
References mTemporal, and rc1Xform::scale().
Referenced by start().
   {
     mTemporal.scale (ts);
   }
const rcIRect& rcKinetoscope::uframe () const inline protected
Definition at line 637 of file rc_kinetoscope.h.
References mUserRect.
Referenced by frame().
   {
     return mUserRect;
   }
void rcKinetoscope::update (rcMotionPathMap & mp) protected
Definition at line 942 of file rc_kinetoscope.cpp.
Referenced by step(), stepContractile(), and stepEpi().
 {
   rcMotionPathMap::iterator pos;
   for (pos = mp.begin(); pos != mp.end(); pos++)
     {
       pos->second.update();
     }
 }
void rcKinetoscope::update (list< rcVisualFunction > & mp) protected
Definition at line 999 of file rc_kinetoscope.cpp.
References rcVisualFunction::eIsOutSide, frameCount(), general_exception::GetFile(), general_exception::GetLine(), rcTimingInfo::nextPass(), rcTimingInfo::printInfo(), rcTimingInfo::touch(), and general_exception::what().
 {
   list<rcVisualFunction>::iterator pos;
   rcTimingInfo profile (2, frameCount() + 1);
   profile.nextPass (0);
   for (pos = mp.begin(); pos != mp.end(); pos++)
     {
       profile.touch(0);
       try
     {
       pos->update();
     }
       catch (general_exception& x)
     {
       pos->setState(rcVisualFunction::eIsOutSide);
       fprintf( stderr, "In Update Function Caught general_exception %s %s %d\n",
            x.what(), x.GetFile (), x.GetLine () );
     }
       profile.touch(1);
     }
   profile.printInfo (1);
 }
void rcKinetoscope::updateProcessingTime () private
Definition at line 699 of file rc_kinetoscope.cpp.
References getCurrentTimestamp(), mCount, mStepProcessingTime, and rcTimestamp::secs().
Referenced by start(), step(), stepContractile(), stepDirectedFlow(), and stepEpi().
 {
   rcTimestamp rct (getCurrentTimestamp ());
   if (mStepProcessingTime < 0.0)
     mStepProcessingTime = rct.secs ();
   else
     mStepProcessingTime = rct.secs () - mStepProcessingTime;
   mStepProcessingTime /= mCount;
 }
const rcWindow & rcKinetoscope::use4fixed () const
Definition at line 648 of file rc_kinetoscope.cpp.
References channelAvailable(), channelFixedPast(), fixed(), fixedPast(), and isLabelProtein().
Referenced by connectedFunctions(), epiMotionField(), selfSimilarMotionField(), selfSimilarMotionField_AttentiveCapture(), and use4when().
 {
   if (isLabelProtein ())
     {
       if (channelAvailable ())
     return channelFixedPast();
       else
     return fixedPast();
     }
   else
     return fixed();
 }
const rcWindow & rcKinetoscope::use4moving () const
Definition at line 635 of file rc_kinetoscope.cpp.
References channelAvailable(), channelMovingPast(), isLabelProtein(), moving(), and movingPast().
Referenced by connectedFunctions(), selfSimilarMotionField(), and use4when().
 {
   if (isLabelProtein ())
     {
       if (channelAvailable ())
     return channelMovingPast();
       else
     return movingPast();
     }
   else
     return moving();
 }
const rcWindow & rcKinetoscope::use4when (const Time when) const
Definition at line 661 of file rc_kinetoscope.cpp.
References eFixed, use4fixed(), and use4moving().
Referenced by frame().
 {
   if (when == eFixed) return use4fixed();
   return use4moving ();
 }
bool rcKinetoscope::validate (const rcIRect & rect, rc2Fvector & df) const protected
Definition at line 712 of file rc_kinetoscope.cpp.
References detail(), eMoving, mFrameData, rfSurfaceHessian(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by connectedFunctions().
 {
   // Check to see If this is a valid Site
   // calculate hessian for this area
   int32 isInside;
   const rcWindow& mGi = mFrameData[eMoving].gradient (detail());
   rcWindow rw (mGi, rect, isInside);
   if (!isInside) return false;
   float meh = rfSurfaceHessian (rw);
   df.x(meh); df.y(meh);
   return true;
 }
rcWindow& rcKinetoscope::velocityXfield () inline private
Definition at line 717 of file rc_kinetoscope.h.
References mXvelocityField.
 {return mXvelocityField;}
rcWindow& rcKinetoscope::velocityYfield () inline private
Definition at line 718 of file rc_kinetoscope.h.
References mYvelocityField.
 {return mYvelocityField;}
list<rcVisualFunction>& rcKinetoscope::visualBodies () inline
Definition at line 535 of file rc_kinetoscope.h.
References mFunctionMap.
Referenced by connectedFunctions(), keepPopulationMeasure(), operator<<(), and temporalResults().
   {
     return mFunctionMap;
   }
void rcKinetoscope::visualDebugGraphics (rcVisualSegmentCollection & segments, const rcVisualStyle & baseStyle)
Definition at line 425 of file rc_kinegraphics.cpp.
References rcAffineRectangle::affineToImage(), affy, caliper, caliper2, rcAffineRectangle::cannonicalSize(), rcPolygon::discBuffer(), rcVisualFunction::eIsAffineXdirected, eLineage, fixedPolygons(), fnd, graph, have(), mFunctionMap, mMergedPOLYs, movingPolygons(), red, rfAffineRectangleToSegmentsCollection(), rfCellNotViable(), rfPlot1Dsignal(), rfPolygonToSegmentsCollection(), rmUnused, rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), rc2dVector< T >::y(), and yel.
Referenced by rcEngineImpl::muscleTracker(), and visualDebugGraphics().
 {
     rmUnused( baseStyle );
     // The first polygon is for fixed. But we want results for moving so start from the second
     vector<rcPolygon>::const_iterator vc = movingPolygons ().begin();
     for (;vc != movingPolygons ().end() && vc->isValid(); vc++)
       {
     segments.push_back (fnd);
     rfPolygonToSegmentsCollection (*vc, segments);
       }
     vc = fixedPolygons ().begin();
     for (;vc != fixedPolygons ().end() && vc->isValid(); vc++)
       {
     segments.push_back (graph);
     rfPolygonToSegmentsCollection (*vc, segments);
       }
     vc = mMergedPOLYs.begin();
     for (;vc != mMergedPOLYs.end() && vc->isValid(); vc++)
       {
     segments.push_back (red);
     rfPolygonToSegmentsCollection (*vc, segments);
       }
     // Show cell bounding box
     list<rcVisualFunction>::const_iterator cell;
     for( cell = mFunctionMap.begin(); cell != mFunctionMap.end(); ++cell ) {
       if (rfCellNotViable (*cell)) continue;
       rcPolygon pog = cell->polygons().back();
       segments.push_back (caliper2);
       rfPolygonToSegmentsCollection (pog, segments);
       if (cell->isCardiacCell ())
       {
         rcAffineRectangle ar = cell->affys().back();
         segments.push_back (affy);
         rfAffineRectangleToSegmentsCollection (ar, segments);
         const vector<float>& profile = cell->shape()->majorProfile();
         rfPlot1Dsignal (profile.begin(), profile.end(), ar, segments);
     // Draw Length Calipers
           rcFPair maj = cell->majorEnds();
           bool side = cell->isState (rcVisualFunction::eIsAffineXdirected);
           int32 d = side ? ar.cannonicalSize().x() : ar.cannonicalSize().y();
           rcFPair size ((double) d, (double) d);
           maj = maj / size;
           if (side)
         {
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(maj.x(), 0.33)),
                             ar.affineToImage(rc2Dvector(maj.x(), 0.67))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(maj.y(), 0.33)),
                             ar.affineToImage(rc2Dvector(maj.y(), 0.67))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(maj.x(), 0.5)),
                             ar.affineToImage(rc2Dvector(maj.y(), 0.5))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.0, 0.5)),
                             ar.affineToImage(rc2Dvector(0.0, 0.5))));
         }
           else
         {
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.33, maj.x())),
                             ar.affineToImage(rc2Dvector(0.67, maj.x()))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.33, maj.y())),
                             ar.affineToImage(rc2Dvector(0.67, maj.y()))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.5, maj.x())),
                             ar.affineToImage(rc2Dvector(0.5, maj.y()))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.5, 0.0)),
                             ar.affineToImage(rc2Dvector(0.5, 0.0))));
         }
         for (uint32 i = 0; i < cell->rectTemplates().size(); i++)
           {
         segments.push_back (fnd);
         rcVisualRect rect(cell->rectTemplates()[i]);
         segments.push_back( rect );
           }
         for (uint32 i = 0; i < cell->rectSearches().size(); i++)
           {
         segments.push_back (caliper2);
         rcVisualRect rect(cell->rectSearches()[i]);
         segments.push_back( rect );
           }
         // Place a rectangle at origin of the affine rect coordinate
         rc2Dvector ul = ar.affineToImage(rc2Dvector(0.0, 0.0));
         rc2Dvector lr = ar.affineToImage(rc2Dvector(0.05, 0.05));
         rcVisualRect rect (rc2Fvector ((float) ul.x(), (float) ul.y()), rc2Fvector ((float) lr.x(), (float) lr.y()));
         segments.push_back( rect );
       }
       else if (have (rcKinetoscope::eLineage))
     {
       segments.push_back (yel);
       segments.push_back(     rcVisualRect (cell->similarityArea ()));
       vector<rcPolygon>::const_iterator vc = movingPolygons ().begin() + cell->label();
       rcPolygon peg = vc->discBuffer (5.0);
       rfPolygonToSegmentsCollection (peg, segments);
     }
     }
 }
void rcKinetoscope::visualDebugGraphics (rcVisualGraphicsCollection & graphics)
Definition at line 568 of file rc_kinegraphics.cpp.
References rfRgb, rcVisualGraphicsCollection::segments(), and visualDebugGraphics().
 {
     // Collect line segments
     rcVisualSegmentCollection& segments = graphics.segments();
     // Yellow color, line width of 1 display pixel, 0.0 pixel origin
     rcVisualStyle style( rfRgb( 200, 200, 0 ), 1, rc2Fvector( 0.0f, 0.0f ) );
     // Set drawing style
     segments.push_back( style );
     visualDebugGraphics( segments, style );
 }
void rcKinetoscope::visualFunctionHistory (rcVisualSegmentCollection & segments, const rcVisualStyle & baseStyle)
Definition at line 394 of file rc_kinegraphics.cpp.
References rcRectangle< T >::height(), mFunctionMap, rcRectangle< T >::origin(), rmUnused, rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by visualFunctionHistory().
 {
     rmUnused( baseStyle );
     // Show cell bounding box
     list<rcVisualFunction>::const_iterator cell;
     for( cell = mFunctionMap.begin(); cell != mFunctionMap.end(); ++cell ) {
       rcIRect r = cell->roundRectangle (cell->rectSnaps().back());
         rcVisualRect rect( r.origin().x(), r.origin().y(), r.width(), r.height() );
         segments.push_back( rect );
     }
 }
void rcKinetoscope::visualFunctionHistory (rcVisualGraphicsCollection & graphics)
Definition at line 556 of file rc_kinegraphics.cpp.
References rfRgb, rcVisualGraphicsCollection::segments(), and visualFunctionHistory().
 {
     // Collect line segments
     rcVisualSegmentCollection& segments = graphics.segments();
     // Yellow color, line width of 1 display pixel, 0.0 pixel origin
     rcVisualStyle style( rfRgb( 200, 200, 0 ), 1, rc2Fvector( 0.0f, 0.0f ) );
     // Set drawing style
     segments.push_back( style );
     visualFunctionHistory( segments, style );
 }
void rcKinetoscope::visualFunctionInfo (rcOrganismInfo::OrganismType c = rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n = rcOrganismInfo::eUnknown)
Definition at line 693 of file rc_kinetoscope.cpp.
References mOname, and mOtype.
 {
   mOtype = c;
   mOname = n;
 }
void rcKinetoscope::visualFunctionMap (rcVisualSegmentCollection & segments, const rcVisualStyle & baseStyle)
Definition at line 260 of file rc_kinegraphics.cpp.
References rcAffineRectangle::affineToImage(), affy, affylow, caliper, caliper2, rcAffineRectangle::cannonicalSize(), rcVisualFunction::eDimensions, rcVisualFunction::eIsAffineXdirected, rcVisualFunction::eIsDivided, rcVisualFunction::eIsDividing, rcVisualFunction::eIsMoving, graph, rc2Xform::mapPoint(), mFunctionMap, mPathMap, rfAffineRectangleToSegmentsCollection(), rfPlot1Dsignal(), rfPolygonToSegmentsCollection(), rmUnused, start(), rcPair< T >::x(), xform(), and rcPair< T >::y().
Referenced by visualFunctionMap().
 {
   rmUnused( baseStyle );
   // Reserve space for one graphics token per motion vector
   segments.reserve( 1 + mPathMap.size() );
   // If there are motion vectors draw them.
   rcMotionPathMap::iterator pos;
   for (pos = mPathMap.begin(); pos != mPathMap.end(); pos++)
     {
       rc2Fvector p2(pos->second.anchor().x(),
             pos->second.anchor().y());
       rc2Fvector p1 (pos->second.position().x(),
             pos->second.position().y());
       rc2Fvector p21 (p1 - p2);
       if (p21.isNull())
           continue;
       p1 = xform().mapPoint (p1);
       p2 = xform().mapPoint (p2);
       rcVisualArrow arrow( p2, p1);
       segments.push_back( arrow );
     }
   list<rcVisualFunction>::const_iterator cell;
   for( cell = mFunctionMap.begin(); cell != mFunctionMap.end(); ++cell )
     {
       if (cell->isCardiacCell ())
     {
       rcAffineRectangle ar = cell->affys().back();
       segments.push_back (affy);
       rfAffineRectangleToSegmentsCollection (ar, segments);
       // if we have dimensios, draw projections
       if (cell->have(rcVisualFunction::eDimensions))
         {
           // Draw Length Calipers
           rcFPair maj = cell->majorEnds();
           bool side = cell->isState (rcVisualFunction::eIsAffineXdirected);
           int32 d = side ? ar.cannonicalSize().x() : ar.cannonicalSize().y();
           rcFPair size ((double) d, (double) d);
           maj = maj / size;
           if (side)
         {
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(maj.x(), 0.33)),
                             ar.affineToImage(rc2Dvector(maj.x(), 0.67))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(maj.y(), 0.33)),
                             ar.affineToImage(rc2Dvector(maj.y(), 0.67))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(maj.x(), 0.5)),
                             ar.affineToImage(rc2Dvector(maj.y(), 0.5))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.0, 0.5)),
                             ar.affineToImage(rc2Dvector(0.0, 0.5))));
         }
           else
         {
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.33, maj.x())),
                             ar.affineToImage(rc2Dvector(0.67, maj.x()))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.33, maj.y())),
                             ar.affineToImage(rc2Dvector(0.67, maj.y()))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.5, maj.x())),
                             ar.affineToImage(rc2Dvector(0.5, maj.y()))));
           segments.push_back (caliper);
           segments.push_back (rcVisualLine (ar.affineToImage(rc2Dvector(0.5, 0.0)),
                             ar.affineToImage(rc2Dvector(0.5, 0.0))));
         }
           // Draw the last framerPerPeriod in the affine Rectangle
           vector<float> lengthHistory ((uint32) cell->framesPerPeriod());
           const deque<rcFPair>& imin = cell->interpolatedMin ();
           deque<rcFPair>::const_iterator start = (imin.size() < lengthHistory.size()) ? imin.begin() :
         imin.end() - lengthHistory.size();
           deque<rcFPair>::const_iterator finish = imin.end();
           vector<float>::iterator lIter;
           vector<float>::iterator historyStart = lengthHistory.begin() + (imin.size() < lengthHistory.size() ?
                                           lengthHistory.size() - imin.size() : 0);
           for (lIter = historyStart; lIter < lengthHistory.end() && start < finish; lIter++, start++)
         *lIter = start->y();
           // Place a rectangle at cell position
           rcFRect ctr (cell->position().x() - cell->framesPerPeriod() / 2,
                cell->position().y() - cell->framesPerPeriod() / 2,
                cell->framesPerPeriod(), cell->framesPerPeriod());
           segments.push_back (graph);
           rfPlot1Dsignal (historyStart, lengthHistory.end(), ctr, segments, false);
         }
     }
       else
     {
       rcPolygon pog = cell->polygons().back();
       // @note: add other visual codes for cell function
       if (cell->isState (rcVisualFunction::eIsMoving))
         {
           segments.push_back (affy);
         }
       // @note: add other visual codes for cell function
       if (cell->isState (rcVisualFunction::eIsDivided))
         {
           segments.push_back (affylow);
         }
       if (cell->isState (rcVisualFunction::eIsDividing))
         {
           segments.push_back (caliper2);
         }
       rfPolygonToSegmentsCollection (pog, segments);
     }
     }
 }
void rcKinetoscope::visualFunctionMap (rcVisualGraphicsCollection & graphics)
Definition at line 544 of file rc_kinegraphics.cpp.
References rfRgb, rcVisualGraphicsCollection::segments(), and visualFunctionMap().
 {
     // Collect line segments
     rcVisualSegmentCollection& segments = graphics.segments();
     // Blue color, line width of 1 display pixel, 0.0 pixel origin
     rcVisualStyle style( rfRgb( 255, 240, 0 ), 1, rc2Fvector( 0.0f, 0.0f ) );
     // Set drawing style
     segments.push_back( style );
     visualFunctionMap( segments, style );
 }
void rcKinetoscope::visualGraphics (rcVisualSegmentCollection & segments, const rcVisualStyle & baseStyle)
Definition at line 250 of file rc_kinegraphics.cpp.
References rmUnused.
Referenced by visualGraphics().
 {
   rmUnused( baseStyle );
   rmUnused(segments );
 }
void rcKinetoscope::visualGraphics (rcVisualGraphicsCollection & graphics)
Definition at line 408 of file rc_kinegraphics.cpp.
References rfRgb, rcVisualGraphicsCollection::segments(), and visualGraphics().
 {
     // Collect line segments
     rcVisualSegmentCollection& segments = graphics.segments();
     // Green color, line width of 1 display pixel, 0.0 pixel origin
     rcVisualStyle style( rfRgb( 10, 255, 20 ), 1, rc2Fvector( 0.0f, 0.0f ) );
     // Set drawing style
     segments.push_back( style );
     visualGraphics( segments, style );
     rcVisualStyle style2 ( rfRgb( 10, 20, 255 ), 1, rc2Fvector( 0.0f, 0.0f ) );
     // Set drawing style
     segments.push_back( style2 );
     // Show cell bounding box
 }
const rc2Xform& rcKinetoscope::xform () const inline
Definition at line 347 of file rc_kinetoscope.h.
References mGlobalXform.
Referenced by rcVisualFunction::dimensions(), rcVisualFunction::distance(), rcVisualFunction::perimeter(), and visualFunctionMap().
   {
     return mGlobalXform;
   }
Friends And Related Function Documentation
ostream& operator<< (ostream & output, rcKinetoscope & kin) friend
Definition at line 14 of file rc_kinereport.cpp.
 {
   const list<rcVisualFunction>& visualBodies = kin.visualBodies();
   list<rcVisualFunction>::const_iterator cell;
   for( cell = visualBodies.begin(); cell != visualBodies.end(); ++cell )
     {
       output << "cell" << cell->id() << "minLaTtlX" << (int32) cell->position().x() << "tlY" << (int32) cell->position().y() << " = {";
       for (uint32 i = 0; i < cell->interpolatedMin().size() - 1;i++)
     {
       if (i) output << ",";
       output << "{" << cell->interpolatedMin()[i].x() << "," << cell->interpolatedMin()[i].y() << "}";
     }
       output << "};" << endl;
     }
   for( cell = visualBodies.begin(); cell != visualBodies.end(); ++cell )
     {
       output << "cell" << cell->id() << "ceAnglesTlX" << (int32) cell->position().x() << "tlY" << (int32) cell->position().y() << " = {";
       for (uint32 i = 0; i < cell->peakAngles().size() - 1;i++)
     {
       if (i) output << ",";
       rcDegree c (cell->peakAngles()[i].x());
       rcDegree r (cell->peakAngles()[i].y());
       output << "{" << c.Double() << "," << r.Double() << "}";
     }
       output << "};" << endl;
     }
   return output;
 }
friend class rcMotionVectorPath friend
Definition at line 77 of file rc_kinetoscope.h.
friend class rcVisualFunction friend
Definition at line 78 of file rc_kinetoscope.h.
Member Data Documentation
const double rcKinetoscope::defaultCutOff = 5.0 static
Definition at line 584 of file rc_kinetoscope.h.
const int32 rcKinetoscope::defaultMaxRadSpeed = eMinSpeedInPixels static
Definition at line 583 of file rc_kinetoscope.h.
Referenced by clear().
const int32 rcKinetoscope::defaultTargetRadius = 3 static
Definition at line 582 of file rc_kinetoscope.h.
Referenced by clear().
rcAutoCorrelation rcKinetoscope::mAutoCorr private
Definition at line 841 of file rc_kinetoscope.h.
vector<vector <rc2Fvector> > rcKinetoscope::mBodyEnds private
Definition at line 795 of file rc_kinetoscope.h.
Referenced by connectedFunctions(), and preSegmentedBodies().
vector<float> rcKinetoscope::mBodyRads private
Definition at line 796 of file rc_kinetoscope.h.
Referenced by connectedFunctions(), and preSegmentedBodies().
rcIPair rcKinetoscope::mCaptureRadius private
Definition at line 848 of file rc_kinetoscope.h.
vector<rc2LevelSpatialPyramid> rcKinetoscope::mChannelData private
Definition at line 773 of file rc_kinetoscope.h.
Referenced by advance(), channelFixed(), channelFixedDirection(), channelFixedPast(), channelMoving(), channelMovingDirection(), channelMovingPast(), frame(), rcKinetoscope(), and start().
rcWindow rcKinetoscope::mClearImage private
Definition at line 778 of file rc_kinetoscope.h.
Referenced by createFunctionSpecificObjects().
vector<rcWindow> rcKinetoscope::mConnectionMap private
Definition at line 774 of file rc_kinetoscope.h.
Referenced by advance(), connect(), connected(), rcKinetoscope(), and start().
rsCorrParams rcKinetoscope::mCorr private
Definition at line 840 of file rc_kinetoscope.h.
uint32 rcKinetoscope::mCount private
Definition at line 845 of file rc_kinetoscope.h.
Referenced by clear(), connectedFunctions(), count(), frame(), isWithin(), preSegmentedBodies(), and updateProcessingTime().
rcTimestamp rcKinetoscope::mCurrentAbsTimeStamp private
Definition at line 809 of file rc_kinetoscope.h.
Referenced by currentTime(), and frame().
double rcKinetoscope::mCutOff private
Definition at line 852 of file rc_kinetoscope.h.
Referenced by epiMotionField(), laminarSuppression(), and selfSimilarMotionField_AttentiveCapture().
list<rcVisualFunction> rcKinetoscope::mDaughterFunctionMap private
Definition at line 793 of file rc_kinetoscope.h.
Referenced by connectedFunctions(), newGeneration(), and reconcileNewGeneration().
bool rcKinetoscope::mDebug private
Definition at line 853 of file rc_kinetoscope.h.
Referenced by debug(), isDebugOn(), and rcKinetoscope().
rcWindow rcKinetoscope::mDebugScreen private
Definition at line 784 of file rc_kinetoscope.h.
Referenced by debug(), and debugScreen().
Detail rcKinetoscope::mDetail private
Definition at line 780 of file rc_kinetoscope.h.
Referenced by detail().
int32 rcKinetoscope::mDisEdgeError private
Definition at line 846 of file rc_kinetoscope.h.
Referenced by stepContractile(), and stepDirectedFlow().
int32 rcKinetoscope::mDisGMEError private
Definition at line 846 of file rc_kinetoscope.h.
Referenced by stepContractile(), and stepDirectedFlow().
int32 rcKinetoscope::mDisPolarError private
Definition at line 846 of file rc_kinetoscope.h.
Referenced by stepContractile(), and stepDirectedFlow().
int32 rcKinetoscope::mDisVarError private
Definition at line 846 of file rc_kinetoscope.h.
Referenced by stepContractile(), and stepDirectedFlow().
float rcKinetoscope::mElapsedTimeSecs private
Definition at line 810 of file rc_kinetoscope.h.
Referenced by clear(), deltaTime(), elapsedTime(), and frame().
int32 rcKinetoscope::mFc private
Definition at line 844 of file rc_kinetoscope.h.
Referenced by frames(), and start().
boost::shared_ptr<rcFrameGrabber> rcKinetoscope::mFg private
Definition at line 760 of file rc_kinetoscope.h.
Referenced by frame(), frameCount(), and rcKinetoscope().
rcFrameGrabberStatus rcKinetoscope::mFgStatus private
Definition at line 761 of file rc_kinetoscope.h.
Referenced by frame().
vector<rcPolygon> rcKinetoscope::mFixedPOLYs private
Definition at line 794 of file rc_kinetoscope.h.
Referenced by advance(), associate(), connectedFunctions(), and fixedPolygons().
rcFRect rcKinetoscope::mFpFrame private
Definition at line 851 of file rc_kinetoscope.h.
Referenced by fpframe(), and frame().
vector<rc2LevelSpatialPyramid> rcKinetoscope::mFrameData private
Definition at line 772 of file rc_kinetoscope.h.
Referenced by advance(), epiMotionField(), fixed(), fixedDirection(), fixedPast(), frame(), moving(), movingDirection(), movingPast(), rcKinetoscope(), reichardt(), start(), stepDirectedFlowPreFill(), and validate().
float rcKinetoscope::mFramesPerSecond private
Definition at line 817 of file rc_kinetoscope.h.
Referenced by averageFramesPerSecond().
rcWindow rcKinetoscope::mFullImage private
Definition at line 779 of file rc_kinetoscope.h.
Referenced by createFunctionSpecificObjects(), and reichardt().
list<rcVisualFunction> rcKinetoscope::mFunctionMap private
Definition at line 792 of file rc_kinetoscope.h.
Referenced by avgMeanSqCellDisplacements(), connectedFunctions(), directedCellToCellMigration(), reconcileNewGeneration(), step(), stepContractile(), stepEpi(), visualBodies(), visualDebugGraphics(), visualFunctionHistory(), and visualFunctionMap().
double rcKinetoscope::mGlobalMotionEst private
Definition at line 814 of file rc_kinetoscope.h.
rc2Xform rcKinetoscope::mGlobalXform private
Definition at line 829 of file rc_kinetoscope.h.
Referenced by clear(), frame(), and xform().
rc1Xform rcKinetoscope::mImageToPhysical private
Definition at line 826 of file rc_kinetoscope.h.
Referenced by clear().
float rcKinetoscope::mLastElapsedTimeSecs private
Definition at line 811 of file rc_kinetoscope.h.
Referenced by clear(), deltaTime(), and frame().
rcLatticeSimilaratorRef rcKinetoscope::mLsm private
Definition at line 802 of file rc_kinetoscope.h.
Referenced by reichardt().
rcWindow rcKinetoscope::mMaskCellwFF private
Definition at line 785 of file rc_kinetoscope.h.
Referenced by createFunctionSpecificObjects(), and preSegmentedBodies().
vector<rcPolygon> rcKinetoscope::mMergedPOLYs private
Definition at line 794 of file rc_kinetoscope.h.
Referenced by visualDebugGraphics().
int32 rcKinetoscope::mMinParea private
Definition at line 849 of file rc_kinetoscope.h.
Referenced by connectedFunctions(), and minMobSizeInPixels().
vector<rcMomentGenerator *> rcKinetoscope::mMomentMap private
Definition at line 775 of file rc_kinetoscope.h.
Referenced by advance(), frame(), isPointCorrOptimizationAvailable(), rcKinetoscope(), and start().
rcMomentGenerator rcKinetoscope::mMomGen0 private
Definition at line 842 of file rc_kinetoscope.h.
Referenced by start().
rcMomentGenerator rcKinetoscope::mMomGen1 private
Definition at line 842 of file rc_kinetoscope.h.
Referenced by start().
rcIPair rcKinetoscope::mMovingSize private
Definition at line 848 of file rc_kinetoscope.h.
Referenced by mov(), and movingSize().
rcOrganismInfo::OrganismName rcKinetoscope::mOname private
Definition at line 801 of file rc_kinetoscope.h.
Referenced by isOfOrganismName(), isOfOrganismTypeAndName(), organismName(), and visualFunctionInfo().
bitset<eNumOptions> rcKinetoscope::mOptions private
Definition at line 822 of file rc_kinetoscope.h.
Referenced by clear(), have(), mark(), and reset().
rcMovieFileOrgExt rcKinetoscope::mOrgExt private
Definition at line 762 of file rc_kinetoscope.h.
Referenced by fileOriginType().
rcFPair rcKinetoscope::mOrigin private
Definition at line 850 of file rc_kinetoscope.h.
Referenced by canonicalMotionField(), clear(), epiMotionField(), and selfSimilarMotionField_AttentiveCapture().
rcOrganismInfo::OrganismType rcKinetoscope::mOtype private
Definition at line 800 of file rc_kinetoscope.h.
Referenced by isOfOrganismType(), isOfOrganismTypeAndName(), organism(), and visualFunctionInfo().
rcMotionPathMap rcKinetoscope::mPathMap private
Definition at line 791 of file rc_kinetoscope.h.
Referenced by canonicalMotionField(), connectedFunctions(), connectFunction(), epiMotionField(), rawSpeedStats(), selfSimilarMotionField_AttentiveCapture(), step(), stepContractile(), stepEpi(), and visualFunctionMap().
float rcKinetoscope::mPeriodicity private
Definition at line 816 of file rc_kinetoscope.h.
Referenced by clear(), and periodicMotion().
uint32 rcKinetoscope::mPhase private
Definition at line 847 of file rc_kinetoscope.h.
Referenced by phase(), rcKinetoscope(), start(), and startFrame().
rc1Xform rcKinetoscope::mPhysicalToImage private
Definition at line 827 of file rc_kinetoscope.h.
Referenced by clear().
rcPointCorrelation rcKinetoscope::mPointCorr private
Definition at line 843 of file rc_kinetoscope.h.
Referenced by pointCorr().
vector<rcPolygon> rcKinetoscope::mPOLYs private
Definition at line 794 of file rc_kinetoscope.h.
Referenced by advance(), connectedFunctions(), dumpPolys(), movingPolygons(), step(), stepContractile(), and stepEpi().
vector<float> rcKinetoscope::mPopulationMeasure private
Definition at line 803 of file rc_kinetoscope.h.
rcStatistics rcKinetoscope::mPopulationStats private
Definition at line 743 of file rc_kinetoscope.h.
Referenced by keepPopulationMeasure(), and populationMeasures().
vector<rcPolygon> rcKinetoscope::mPrePOLYs private
Definition at line 799 of file rc_kinetoscope.h.
Referenced by connectedFunctions(), and preSegmentedBodies().
rcIRect rcKinetoscope::mProcessRect private
Definition at line 782 of file rc_kinetoscope.h.
Referenced by frame(), pframe(), and start().
rcIRect rcKinetoscope::mRect private
Definition at line 781 of file rc_kinetoscope.h.
Referenced by frame(), iframe(), isWithin(), and rcKinetoscope().
uint32 rcKinetoscope::mSample private
Definition at line 847 of file rc_kinetoscope.h.
Referenced by rcKinetoscope(), sample(), and start().
vector<rcWindow> rcKinetoscope::mSimBuffer private
Definition at line 777 of file rc_kinetoscope.h.
Referenced by reichardt(), and stepDirectedFlowPreFill().
int32 rcKinetoscope::mSimPipe private
Definition at line 819 of file rc_kinetoscope.h.
Referenced by clear(), reichardt(), and stepDirectedFlowPreFill().
float rcKinetoscope::mSizeMultiplier private
Definition at line 854 of file rc_kinetoscope.h.
Referenced by clear(), and sizeMultiplier().
rcStatistics rcKinetoscope::mSnapStats private
Definition at line 813 of file rc_kinetoscope.h.
Referenced by rawSpeedStats(), step(), stepContractile(), stepDirectedFlow(), and stepEpi().
Source rcKinetoscope::mSource private
Definition at line 757 of file rc_kinetoscope.h.
Referenced by frame(), frameCount(), start(), and startFrame().
SourceMotion rcKinetoscope::mSourceMotion private
Definition at line 815 of file rc_kinetoscope.h.
Referenced by clear(), and sourceMotion().
rcTimestamp rcKinetoscope::mStartAbsTimeStamp private
Definition at line 808 of file rc_kinetoscope.h.
Referenced by frame(), and startingAbsoluteTime().
double rcKinetoscope::mStepProcessingTime private
Definition at line 812 of file rc_kinetoscope.h.
Referenced by clear(), and updateProcessingTime().
rcIPair rcKinetoscope::mTargetRadius private
Definition at line 848 of file rc_kinetoscope.h.
Referenced by mov(), and target().
rc1Xform rcKinetoscope::mTemporal private
Definition at line 828 of file rc_kinetoscope.h.
Referenced by currentTime(), deltaTime(), elapsedTime(), secondsToUnits(), and temporalScale().
rcIRect rcKinetoscope::mUserRect private
Definition at line 783 of file rc_kinetoscope.h.
Referenced by frame(), rcKinetoscope(), and uframe().
vector<vector <rc2Fvector> > rcKinetoscope::mVanchor private
Definition at line 797 of file rc_kinetoscope.h.
Referenced by connectedFunctions().
shared_video_cache rcKinetoscope::mVc private
Definition at line 758 of file rc_kinetoscope.h.
Referenced by frame(), frameCount(), and rcKinetoscope().
rcVideoCacheStatus rcKinetoscope::mVcStatus private
Definition at line 759 of file rc_kinetoscope.h.
Referenced by frame().
rcIPair rcKinetoscope::mVmaxRadial private
Definition at line 848 of file rc_kinetoscope.h.
Referenced by maxRadialSpeed(), and mov().
vector<vector <rc2Fvector> > rcKinetoscope::mVmoved private
Definition at line 798 of file rc_kinetoscope.h.
Referenced by connectedFunctions().
rcWindow rcKinetoscope::mXvelocityField private
Definition at line 776 of file rc_kinetoscope.h.
Referenced by velocityXfield().
rcWindow rcKinetoscope::mYvelocityField private
Definition at line 776 of file rc_kinetoscope.h.
Referenced by velocityYfield().
const float rcKinetoscope::notAvailable = -2.0 static
Definition at line 585 of file rc_kinetoscope.h.
The documentation for this class was generated from the following files:
include/analysis/rc_kinetoscope.h
src/analysis/code/rc_kinefield.cpp
src/analysis/code/rc_kineframe.cpp
src/analysis/code/rc_kinegraphics.cpp
src/analysis/code/rc_kinereport.cpp
src/analysis/code/rc_kinestep.cpp
src/analysis/code/rc_kinetoscope.cpp
src/analysis/code/rc_kinetrack.cpp