Visible: obuff Class Reference
obuff Class Reference abstract
#include <include/stlplus/textio.hpp>
Public Member Functions
obuff (bool line_buffer=false, otext::newline_t newline=otext::native_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_line_buffer (bool mode)
bool line_buffer (void) const
void set_newline_mode (otext::newline_t newline)
otext::newline_t newline_mode (void) const
unsigned integer_width (void) const
void set_integer_width (unsigned)
unsigned integer_radix (void) const
void set_integer_radix (unsigned)
radix_display_t integer_display (void) const
void set_integer_display (radix_display_t)
unsigned real_width (void) const
void set_real_width (unsigned)
unsigned real_precision (void) const
void set_real_precision (unsigned)
real_display_t real_display (void) const
void set_real_display (real_display_t)
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual std::string error_string (void) const
virtual void flush (void)
virtual unsigned put (unsigned char)=0
virtual ~obuff (void)
Protected Attributes
bool m_line_buffer
otext::newline_t m_newline
unsigned long m_bytes
unsigned m_line
unsigned m_column
unsigned m_integer_width
unsigned m_integer_radix
radix_display_t m_integer_display
unsigned m_real_width
unsigned m_real_precision
real_display_t m_real_display
int m_error_number
int m_aliases
Private Member Functions
obuff & operator= (const obuff &)
obuff (const obuff &)
Friends
class otext
Detailed Description
Definition at line 398 of file textio.hpp.
Constructor & Destructor Documentation
obuff::obuff (bool line_buffer = false, otext::newline_t newline = otext::native_mode)
Definition at line 1083 of file textio.cpp.
                                                       :
   m_line_buffer(line_buffer),
   m_newline(newline),
   m_bytes(0),
   m_line(1),
   m_column(0),
   m_integer_width(0),
   m_integer_radix(10),
   m_integer_display(radix_c_style_or_hash),
   m_real_width(0),
   m_real_precision(6),
   m_real_display(display_mixed),
   m_error_number(0),
   m_aliases(0)
 {
 }
obuff::~obuff (void) virtual
Definition at line 1100 of file textio.cpp.
 {
 }
obuff::obuff (const obuff &) private
Member Function Documentation
unsigned long obuff::bytes (void) const
Definition at line 1118 of file textio.cpp.
References m_bytes.
Referenced by otext::bytes().
 {
   return m_bytes;
 }
void obuff::clear_error (void)
Definition at line 1218 of file textio.cpp.
References m_error_number.
Referenced by otext::clear_error().
 {
   m_error_number = 0;
 }
unsigned obuff::column (void) const
Definition at line 1128 of file textio.cpp.
References m_column.
Referenced by otext::column().
 {
   return m_column;
 }
int obuff::error_number (void) const
Definition at line 1223 of file textio.cpp.
References m_error_number.
Referenced by otext::error_number(), ofbuff::error_string(), and error_string().
 {
   return m_error_number;
 }
std::string obuff::error_string (void) const virtual
Reimplemented in ofbuff.
Definition at line 1228 of file textio.cpp.
References error_number(), and textio_error_string().
Referenced by otext::error_string(), and ofbuff::error_string().
 {
   return textio_error_string(error_number());
 }
void obuff::flush (void) virtual
Reimplemented in ofbuff, and oiobuff.
Definition at line 1233 of file textio.cpp.
Referenced by otext::flush().
 {
 }
void obuff::increment (bool newline = false)
Definition at line 1104 of file textio.cpp.
References m_bytes, m_column, and m_line.
Referenced by otext::put().
 {
   m_bytes++;
   if (newline)
   {
     m_line++;
     m_column = 0;
   }
   else
   {
     m_column++;
   }
 }
radix_display_t obuff::integer_display (void) const
Definition at line 1173 of file textio.cpp.
References m_integer_display.
Referenced by otext::integer_display().
 {
   return m_integer_display;
 }
unsigned obuff::integer_radix (void) const
Definition at line 1163 of file textio.cpp.
References m_integer_radix.
Referenced by otext::integer_radix().
 {
   return m_integer_radix;
 }
unsigned obuff::integer_width (void) const
Definition at line 1153 of file textio.cpp.
References m_integer_width.
Referenced by otext::integer_width().
 {
   return m_integer_width;
 }
unsigned obuff::line (void) const
Definition at line 1123 of file textio.cpp.
References m_line.
Referenced by otext::line().
 {
   return m_line;
 }
bool obuff::line_buffer (void) const
Definition at line 1133 of file textio.cpp.
References m_line_buffer.
Referenced by otext::put().
 {
   return m_line_buffer;
 }
otext::newline_t obuff::newline_mode (void) const
Definition at line 1148 of file textio.cpp.
References m_newline.
Referenced by otext::newline_mode(), and otext::put().
 {
   return m_newline;
 }
obuff& obuff::operator= (const obuff &) private
virtual unsigned obuff::put (unsigned char) pure virtual
Implemented in ofbuff, ombuff, oiobuff, osvbuff, and osbuff.
Referenced by otext::put().
real_display_t obuff::real_display (void) const
Definition at line 1203 of file textio.cpp.
References m_real_display.
Referenced by otext::real_display().
 {
   return m_real_display;
 }
unsigned obuff::real_precision (void) const
Definition at line 1193 of file textio.cpp.
References m_real_precision.
Referenced by otext::real_precision().
 {
   return m_real_precision;
 }
unsigned obuff::real_width (void) const
Definition at line 1183 of file textio.cpp.
References m_real_width.
Referenced by otext::real_width().
 {
   return m_real_width;
 }
void obuff::set_error (int error)
Definition at line 1213 of file textio.cpp.
References TCP_client_data::error(), and m_error_number.
Referenced by oiobuff::flush(), ofbuff::flush(), ofbuff::open(), oiobuff::put(), ofbuff::put(), and otext::set_error().
 {
   if (!m_error_number) m_error_number = error;
 }
void obuff::set_integer_display (radix_display_t display)
Definition at line 1178 of file textio.cpp.
References m_integer_display.
Referenced by otext::set_integer_display().
 {
   m_integer_display = display;
 }
void obuff::set_integer_radix (unsigned radix)
Definition at line 1168 of file textio.cpp.
References m_integer_radix.
Referenced by otext::set_integer_radix().
 {
   m_integer_radix = radix;
 }
void obuff::set_integer_width (unsigned width)
Definition at line 1158 of file textio.cpp.
References m_integer_width.
Referenced by otext::set_integer_width().
 {
   m_integer_width = width;
 }
void obuff::set_line_buffer (bool mode)
Definition at line 1138 of file textio.cpp.
References m_line_buffer.
Referenced by ofbuff::open().
 {
   m_line_buffer = mode;
 }
void obuff::set_newline_mode (otext::newline_t newline)
Definition at line 1143 of file textio.cpp.
References m_newline, and newline.
Referenced by otext::set_newline_mode().
 {
   m_newline = newline;
 }
void obuff::set_real_display (real_display_t display)
Definition at line 1208 of file textio.cpp.
References m_real_display.
Referenced by otext::set_real_display().
 {
   m_real_display = display;
 }
void obuff::set_real_precision (unsigned precision)
Definition at line 1198 of file textio.cpp.
References m_real_precision.
Referenced by otext::set_real_precision().
 {
   m_real_precision = precision;
 }
void obuff::set_real_width (unsigned width)
Definition at line 1188 of file textio.cpp.
References m_real_width.
Referenced by otext::set_real_width().
 {
   m_real_width = width;
 }
Friends And Related Function Documentation
friend class otext friend
Definition at line 484 of file textio.hpp.
Member Data Documentation
int obuff::m_aliases protected
Definition at line 497 of file textio.hpp.
Referenced by otext::close(), and otext::open().
unsigned long obuff::m_bytes protected
Definition at line 487 of file textio.hpp.
Referenced by bytes(), and increment().
unsigned obuff::m_column protected
Definition at line 489 of file textio.hpp.
Referenced by column(), and increment().
int obuff::m_error_number protected
Definition at line 496 of file textio.hpp.
Referenced by clear_error(), error_number(), and set_error().
radix_display_t obuff::m_integer_display protected
Definition at line 492 of file textio.hpp.
Referenced by integer_display(), and set_integer_display().
unsigned obuff::m_integer_radix protected
Definition at line 491 of file textio.hpp.
Referenced by integer_radix(), and set_integer_radix().
unsigned obuff::m_integer_width protected
Definition at line 490 of file textio.hpp.
Referenced by integer_width(), and set_integer_width().
unsigned obuff::m_line protected
Definition at line 488 of file textio.hpp.
Referenced by increment(), and line().
bool obuff::m_line_buffer protected
Definition at line 485 of file textio.hpp.
Referenced by line_buffer(), and set_line_buffer().
otext::newline_t obuff::m_newline protected
Definition at line 486 of file textio.hpp.
Referenced by newline_mode(), and set_newline_mode().
real_display_t obuff::m_real_display protected
Definition at line 495 of file textio.hpp.
Referenced by real_display(), and set_real_display().
unsigned obuff::m_real_precision protected
Definition at line 494 of file textio.hpp.
Referenced by real_precision(), and set_real_precision().
unsigned obuff::m_real_width protected
Definition at line 493 of file textio.hpp.
Referenced by real_width(), and set_real_width().
The documentation for this class was generated from the following files:
include/stlplus/textio.hpp
include/stlplus/textio.cpp