Visible: rcAngle8 Class Reference
rcAngle8 Class Reference
#include <include/util/rc_math.h>
Public Member Functions
rcAngle8 ()
rcAngle8 (uint8 a)
rcAngle8 operator+ (rcAngle8 a) const
rcAngle8 operator- (rcAngle8 a) const
rcAngle8 operator* (uint8 a) const
rcAngle8 operator/ (uint8 a) const
rcAngle8 operator- () const
uint8 operator* (rcAngle8 a) const
uint8 operator/ (rcAngle8 a) const
double Double () const
uint8 basic () const
rcAngle8 & operator= (uint8 a)
rcAngle8 & operator*= (uint8 a)
rcAngle8 & operator/= (uint8 a)
rcAngle8 & operator*= (rcAngle8 a)
rcAngle8 & operator/= (rcAngle8 a)
rcAngle8 & operator+= (rcAngle8 a)
rcAngle8 & operator-= (rcAngle8 a)
bool operator== (rcAngle8 a) const
bool operator!= (rcAngle8 a) const
bool operator< (rcAngle8 a) const
bool operator<= (rcAngle8 a) const
bool operator> (rcAngle8 a) const
bool operator>= (rcAngle8 a) const
rcAngle8 (rcRadian)
rcAngle8 (rcDegree)
rcAngle8 (rcAngle16)
Static Public Member Functions
static const rcAngle8 piOverTwo ()
Private Attributes
uint8 val
Friends
rcAngle8 operator* (uint8 a, rcAngle8 b)
Detailed Description
Definition at line 275 of file rc_math.h.
Constructor & Destructor Documentation
rcAngle8::rcAngle8 () inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8::rcAngle8 (uint8 a) inline explicit
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8::rcAngle8 (rcRadian x) inline
Definition at line 360 of file rc_math.h.
 { return rcRadian (acos (x));}
rcAngle8::rcAngle8 (rcDegree x) inline
Definition at line 362 of file rc_math.h.
 { return rcRadian (acos (x));}
rcAngle8::rcAngle8 (rcAngle16 x) inline
Definition at line 365 of file rc_math.h.
 { return rcRadian (acos (x));}
Member Function Documentation
uint8 rcAngle8::basic () const inline
Definition at line 277 of file rc_math.h.
Referenced by rcMathematicalImage::mMakeField(), rcFeature::octants(), rcEdgeTables::rcEdgeTables(), rcFeature::rcFeature(), and rcLatticeSimilarator::ttc().
 :
inline rcAngle8 (rcRadian);
double rcAngle8::Double () const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
bool rcAngle8::operator!= (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8 rcAngle8::operator* (uint8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
uint8 rcAngle8::operator* (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator*= (uint8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator*= (rcAngle8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8 rcAngle8::operator+ (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator+= (rcAngle8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8 rcAngle8::operator- (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8 rcAngle8::operator- () const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator-= (rcAngle8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8 rcAngle8::operator/ (uint8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
uint8 rcAngle8::operator/ (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator/= (uint8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator/= (rcAngle8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
bool rcAngle8::operator< (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
bool rcAngle8::operator<= (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
rcAngle8& rcAngle8::operator= (uint8 a) inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
bool rcAngle8::operator== (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
bool rcAngle8::operator> (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
bool rcAngle8::operator>= (rcAngle8 a) const inline
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
static const rcAngle8 rcAngle8::piOverTwo () inline static
Definition at line 283 of file rc_math.h.
References rcUINT8_MAX.
 { return rcAngle8 (rcUINT8_MAX / 4); }
Friends And Related Function Documentation
rcAngle8 operator* (uint8 a, rcAngle8 b) friend
Definition at line 277 of file rc_math.h.
 :
inline rcAngle8 (rcRadian);
Member Data Documentation
uint8 rcAngle8::val private
Definition at line 277 of file rc_math.h.
The documentation for this class was generated from the following file:
include/util/rc_math.h