Visible: rcTrackGroup Class Reference
rcTrackGroup Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcTrackGroup ()
virtual const char * getTag (void) const =0
virtual const char * getName (void) const =0
virtual const char * getDescription (void) const =0
virtual rcGroupSemantics getType ()=0
virtual int getNTracks (void) const =0
virtual rcTrack * getTrack (int trackNo)=0
Detailed Description
Definition at line 318 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcTrackGroup::~rcTrackGroup () inline virtual
Definition at line 322 of file rc_model.h.
 { };
Member Function Documentation
virtual const char* rcTrackGroup::getDescription (void) const pure virtual
Implemented in rcTrackGroupImpl.
Referenced by rcImageCanvasGL::enableCellGroup(), rcCSVExporter::exportTracks(), rcImageCanvasGL::getToolTipText(), rcNativeExporter::produceGroups(), and rcTrackGroupWidget::rcTrackGroupWidget().
virtual const char* rcTrackGroup::getName (void) const pure virtual
Implemented in rcTrackGroupImpl.
Referenced by countDisplayableGroups(), rcCSVExporter::exportTracks(), rcMonitor::gatherTrackData(), rcNativeExporter::produceGroups(), rcTrackGroupWidget::rcTrackGroupWidget(), and rcCellInfoWidget::updateTrackDisplay().
virtual int rcTrackGroup::getNTracks (void) const pure virtual
Implemented in rcTrackGroupImpl.
Referenced by rcTrackManager::addTracks(), rcTimeline::checkScalarTrackScales(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), rcImageCanvasGL::getToolTipText(), rcExporter::hasExportableTracks(), rcTrackManager::hasManageableTracks(), rcTimeline::hasViewableTracks(), rcExporter::init(), rcTimeline::paintTimeline(), rcTrackGroupWidget::rcTrackGroupWidget(), rcTrackGroupWidget::setEnabled(), and rcCellInfoWidget::updateTrackDisplay().
virtual const char* rcTrackGroup::getTag (void) const pure virtual
Implemented in rcTrackGroupImpl.
Referenced by rcNativeExporter::produceGroups().
virtual rcTrack* rcTrackGroup::getTrack (int trackNo) pure virtual
Implemented in rcTrackGroupImpl.
Referenced by rcTrackManager::addTracks(), rcTimeline::checkScalarTrackScales(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), rcTrackManager::getHiliteTrack(), rcImageCanvasGL::getToolTipText(), rcExporter::hasExportableTracks(), rcTrackManager::hasManageableTracks(), rcTimeline::hasViewableTracks(), rcExporter::init(), rcScalarTrackWidget::mousePressEvent(), rcTimeline::paintTimeline(), rcScalarTrackWidget::rcScalarTrackWidget(), rcTrackGroupWidget::rcTrackGroupWidget(), rcCellInfoWidget::updateTrackDisplay(), and rcScalarTrackWidget::updateTrackDisplay().
virtual rcGroupSemantics rcTrackGroup::getType () pure virtual
Implemented in rcTrackGroupImpl.
Referenced by rcTimeline::checkScalarTrackScales(), countDisplayableGroups(), rcImageCanvasGL::findCellPositionTracks(), rcImageCanvasGL::getToolTipText(), rcTrackManager::groupType(), rcTrackManager::hasManageableTracks(), rcTimeline::hasViewableTracks(), rcTrackGroupWidget::setEnabled(), rcCellInfoWidget::updateTrackDisplay(), and rcScalarTrackWidget::updateTrackDisplay().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h