Visible: rcCustomEventManager Class Reference
rcCustomEventManager Class Reference
#include <include/visUI/rc_customeventmanager.h>
Public Member Functions
rcCustomEventManager (QObject *receiver)
int32 queuedEvents (rcCustomEvent type)
void postEvent (QEvent *e)
int32 processedEvent (QEvent *e)
Private Member Functions
int32 postedEvent (rcCustomEvent type)
int32 processedEvent (rcCustomEvent type)
Private Attributes
QObject * mReceiver
QMutex mutex
int32 mQueueCount [eNotifyMaxEvent]
Detailed Description
Definition at line 76 of file rc_customeventmanager.h.
Constructor & Destructor Documentation
rcCustomEventManager::rcCustomEventManager (QObject * receiver)
Definition at line 21 of file rc_customeventmanager.cpp.
References mQueueCount, mutex, and rmDim.
                                                               : mReceiver( receiver ), mutex  ()
 {
      QMutexLocker locker(&mutex);
     // Initialize queue counts
     for ( uint32 i = 0; i < rmDim( mQueueCount ); ++i )
         mQueueCount[i] = 0;
 }
Member Function Documentation
int32 rcCustomEventManager::postedEvent (rcCustomEvent type) private
Definition at line 70 of file rc_customeventmanager.cpp.
References eNotifyMaxEvent, eNotifyMinEvent, mQueueCount, mutex, and rmAssert.
Referenced by postEvent().
 {
      QMutexLocker locker(&mutex);
     rmAssert( type > eNotifyMinEvent && type < eNotifyMaxEvent );
     return ++mQueueCount[type];
 }
void rcCustomEventManager::postEvent (QEvent * e)
Definition at line 47 of file rc_customeventmanager.cpp.
References endl(), mReceiver, postedEvent(), and rmUnused.
Referenced by rcModelDomain::notifyAnalysisRect(), rcModelDomain::notifyAnalysisRectRotation(), rcModelDomain::notifyBlitData(), rcModelDomain::notifyBlitGraphics(), rcModelDomain::notifyEngineTimelineRange(), rcModelDomain::notifyError(), rcModelDomain::notifyExperimentChange(), rcModelDomain::notifyMultiplier(), rcModelDomain::notifyProgCursorTime(), rcModelDomain::notifyState(), rcModelDomain::notifyStatus(), rcModelDomain::notifyTime(), rcModelDomain::notifyVideoRect(), and rcModelDomain::notifyWarning().
 {
     rcCustomEvent type = static_cast<rcCustomEvent> (e->type());
     int32 unprocessed = postedEvent( type );
 #ifdef DEBUG_LOG
     if ( unprocessed > 1 ) {
         cerr << "postEvent(" << type <<  ") " << unprocessed << " events already queued" << endl;
     }
 #else
     rmUnused( unprocessed );
 #endif
     QApplication::postEvent( mReceiver, e );
 }
int32 rcCustomEventManager::processedEvent (QEvent * e)
Definition at line 33 of file rc_customeventmanager.cpp.
Referenced by rcModelDomain::customEvent().
 {
     return processedEvent( static_cast<rcCustomEvent> (e->type()));
 }
int32 rcCustomEventManager::processedEvent (rcCustomEvent type) private
Definition at line 80 of file rc_customeventmanager.cpp.
References endl(), eNotifyMaxEvent, eNotifyMinEvent, mQueueCount, mutex, and rmAssert.
 {
      QMutexLocker locker(&mutex);
     rmAssert( type > eNotifyMinEvent && type < eNotifyMaxEvent );
     if ( mQueueCount[type] <= 0 )
         cerr << "rcCustomEventManager::processedEvent: rcCustomEvent(" << type << ") invalid queue count " <<  mQueueCount[type] << endl;
     return --mQueueCount[type];
 }
int32 rcCustomEventManager::queuedEvents (rcCustomEvent type)
Definition at line 39 of file rc_customeventmanager.cpp.
References mQueueCount, and mutex.
Referenced by rcModelDomain::notifyBlitData(), rcModelDomain::notifyBlitGraphics(), rcModelDomain::notifyTime(), and rcModelDomain::progCursorTimeEventCount().
 {
      QMutexLocker locker(&mutex);
     return mQueueCount[type];
 }
Member Data Documentation
int32 rcCustomEventManager::mQueueCount[eNotifyMaxEvent] private
Definition at line 101 of file rc_customeventmanager.h.
Referenced by postedEvent(), processedEvent(), queuedEvents(), and rcCustomEventManager().
QObject* rcCustomEventManager::mReceiver private
Definition at line 99 of file rc_customeventmanager.h.
Referenced by postEvent().
QMutex rcCustomEventManager::mutex private
Definition at line 100 of file rc_customeventmanager.h.
Referenced by postedEvent(), processedEvent(), queuedEvents(), and rcCustomEventManager().
The documentation for this class was generated from the following files:
include/visUI/rc_customeventmanager.h
src/visible/qt/rc_customeventmanager.cpp