Visible: lm_unit_name Class Reference
lm_unit_name Class Reference
#include <include/stlplus/library_manager.hpp>
Public Member Functions
lm_unit_name (const std::string &name=std::string(), const std::string &type=std::string())
~lm_unit_name (void)
const std::string & name (void) const
void set_name (const std::string &name)
void lowercase (void)
const std::string & type (void) const
void set_type (const std::string &type)
Private Attributes
std::string m_name
std::string m_type
Friends
void dump (dump_context &context, const lm_unit_name &name) throw (persistent_dump_failed)
void restore (restore_context &context, lm_unit_name &name) throw (persistent_restore_failed)
std::string to_string (const lm_unit_name &name)
otext & print (otext &, const lm_unit_name &)
otext & operator<< (otext &, const lm_unit_name &)
bool operator== (const lm_unit_name &l, const lm_unit_name &r)
bool operator< (const lm_unit_name &l, const lm_unit_name &r)
Detailed Description
Definition at line 44 of file library_manager.hpp.
Constructor & Destructor Documentation
lm_unit_name::lm_unit_name (const std::string & name = std::string(), const std::string & type = std::string())
Definition at line 174 of file library_manager.cpp.
                                                                        :
   m_name(name), m_type(type)
 {
 }
lm_unit_name::~lm_unit_name (void)
Definition at line 179 of file library_manager.cpp.
 {
 }
Member Function Documentation
void lm_unit_name::lowercase (void)
Definition at line 193 of file library_manager.cpp.
References m_name.
Referenced by lm_library::create(), lm_library::load_type(), and lm_library::local_find().
 {
   m_name = ::lowercase(m_name);
 }
const std::string & lm_unit_name::name (void) const
Definition at line 183 of file library_manager.cpp.
References m_name.
Referenced by lm_unit::filename(), lm_unit::header_filename(), lm_library::local_find(), lm_unit_dependency::name(), lm_unit::name(), lm_unit::print_long(), and set_name().
 {
   return m_name;
 }
void lm_unit_name::set_name (const std::string & name)
Definition at line 188 of file library_manager.cpp.
References m_name, and name().
Referenced by lm_library::local_find(), and lm_unit_dependency::set_name().
 {
   m_name = name;
 }
void lm_unit_name::set_type (const std::string & type)
Definition at line 203 of file library_manager.cpp.
References m_type, and type().
Referenced by lm_unit_dependency::set_type().
 {
   m_type = type;
 }
const std::string & lm_unit_name::type (void) const
Definition at line 198 of file library_manager.cpp.
References m_type.
Referenced by lm_library::create(), lm_unit::filename(), lm_unit::header_filename(), lm_unit::print_long(), set_type(), lm_unit_dependency::type(), and lm_unit::type().
 {
   return m_type;
 }
Friends And Related Function Documentation
void dump (dump_context & context, const lm_unit_name & name) throw (persistent_dump_failed) friend
Definition at line 208 of file library_manager.cpp.
 {
   dump(context, name.m_name);
   dump(context, name.m_type);
 }
bool operator< (const lm_unit_name & l, const lm_unit_name & r) friend
Definition at line 240 of file library_manager.cpp.
 {
   // sort by name then type
   return (l.m_name != r.m_name) ? l.m_name < r.m_name : l.m_type < r.m_type;
 }
otext& operator<< (otext & , const lm_unit_name &) friend
Definition at line 230 of file library_manager.cpp.
 {
   return print(str, name);
 }
bool operator== (const lm_unit_name & l, const lm_unit_name & r) friend
Definition at line 235 of file library_manager.cpp.
 {
   return l.m_name == r.m_name && l.m_type == r.m_type;
 }
otext& print (otext & , const lm_unit_name &) friend
Definition at line 225 of file library_manager.cpp.
 {
   return print(str, to_string(name));
 }
void restore (restore_context & context, lm_unit_name & name) throw (persistent_restore_failed) friend
Definition at line 214 of file library_manager.cpp.
 {
   restore(context, name.m_name);
   restore(context, name.m_type);
 }
std::string to_string (const lm_unit_name & name) friend
Definition at line 220 of file library_manager.cpp.
 {
   return name.m_name + ":" + name.m_type;
 }
Member Data Documentation
std::string lm_unit_name::m_name private
Definition at line 68 of file library_manager.hpp.
Referenced by lowercase(), name(), operator<(), operator==(), set_name(), and to_string().
std::string lm_unit_name::m_type private
Definition at line 69 of file library_manager.hpp.
Referenced by operator<(), operator==(), set_type(), to_string(), and type().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp