Visible: rcSegmentationLevel Class Reference
rcSegmentationLevel Class Reference
#include <include/analysis/rc_level.h>
Public Member Functions
virtual ~rcSegmentationLevel ()
rcWindow binaryImage (const rcWindow &src, uint8 toGrayValue)
rcWindow binaryImage (const rcWindow &src, uint8 toGrayValue, uint8 setVal)
virtual rcLevelSets & results ()
Private Attributes
rcLevelSets mResults
Detailed Description
Definition at line 34 of file rc_level.h.
Constructor & Destructor Documentation
virtual rcSegmentationLevel::~rcSegmentationLevel () inline virtual
Definition at line 38 of file rc_level.h.
 {}
Member Function Documentation
rcWindow rcSegmentationLevel::binaryImage (const rcWindow & src, uint8 toGrayValue)
Definition at line 171 of file rc_seglevel.cpp.
Referenced by rcMutualInfoGrouping::rcMutualInfoGrouping().
 {
   return binaryImage (src, level, level);
 }
rcWindow rcSegmentationLevel::binaryImage (const rcWindow & src, uint8 toGrayValue, uint8 setVal)
Definition at line 176 of file rc_seglevel.cpp.
References rcWindow::height(), rfPixel8Map(), rmAssert, and rcWindow::width().
 {
   rmAssert (level != 0 && level != 255);
   vector<uint8> lut (256);
   memset (&lut[0], 0, level-1);
   memset (&lut[level], setVal, 256 - level);
   rcWindow dst (src.width(), src.height());
   rfPixel8Map (src, dst, lut);
   return dst;
 }
virtual rcLevelSets& rcSegmentationLevel::results () inline virtual
Definition at line 52 of file rc_level.h.
References mResults.
Referenced by rcMutualInfoGrouping::rcMutualInfoGrouping(), and rcWithinGroupInv::rcWithinGroupInv().
 {return mResults;}
Member Data Documentation
rcLevelSets rcSegmentationLevel::mResults private
Definition at line 56 of file rc_level.h.
Referenced by results().
The documentation for this class was generated from the following files:
include/analysis/rc_level.h
src/analysis/code/rc_seglevel.cpp