Visible: rcDegree Class Reference
rcDegree Class Reference
#include <include/util/rc_math.h>
Public Member Functions
rcDegree ()
rcDegree (double a)
rcDegree operator+ (rcDegree a) const
rcDegree operator- (rcDegree a) const
rcDegree operator* (double a) const
rcDegree operator/ (double a) const
rcDegree operator- () const
double operator* (rcDegree a) const
double operator/ (rcDegree a) const
double Double () const
double basic () const
rcDegree & operator= (double a)
rcDegree & operator*= (double a)
rcDegree & operator/= (double a)
rcDegree & operator*= (rcDegree a)
rcDegree & operator/= (rcDegree a)
rcDegree & operator+= (rcDegree a)
rcDegree & operator-= (rcDegree a)
bool operator== (rcDegree a) const
bool operator!= (rcDegree a) const
bool operator< (rcDegree a) const
bool operator<= (rcDegree a) const
bool operator> (rcDegree a) const
bool operator>= (rcDegree a) const
rcDegree (rcRadian)
rcDegree (rcAngle8)
rcDegree (rcAngle16)
rcDegree norm () const
rcDegree normSigned () const
Private Attributes
double val
Friends
rcDegree operator* (double a, rcDegree b)
Detailed Description
Definition at line 262 of file rc_math.h.
Constructor & Destructor Documentation
rcDegree::rcDegree () inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree::rcDegree (double a) inline explicit
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree::rcDegree (rcRadian x) inline
Definition at line 358 of file rc_math.h.
 { return rcRadian (acos (x));}
rcDegree::rcDegree (rcAngle8 x) inline
Definition at line 362 of file rc_math.h.
 { return rcRadian (acos (x));}
rcDegree::rcDegree (rcAngle16 x) inline
Definition at line 363 of file rc_math.h.
 { return rcRadian (acos (x));}
Member Function Documentation
double rcDegree::basic () const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
double rcDegree::Double () const inline
Definition at line 264 of file rc_math.h.
Referenced by abs(), operator<<(), rcKinetoscope::temporalResults(), and rcCellWriterGroup::writeValues().
 :
inline rcDegree (rcRadian);
rcDegree rcDegree::norm () const
Definition at line 78 of file rc_units.cpp.
References val.
Referenced by normSigned(), and rcCellWriterGroup::writeValues().
 {
   rcDegree r;
   r.val = fmod (val, 360.);
   if (r.val < 0.) r.val += 360.;
   return r;
 }
rcDegree rcDegree::normSigned () const
Definition at line 103 of file rc_units.cpp.
References norm(), and val.
 {
   rcDegree r;
   r = norm();
   if (r.val < 360. - r.val)
     return r;
   r.val = r.val - 360.;
   return r;
 }
bool rcDegree::operator!= (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree rcDegree::operator* (double a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
double rcDegree::operator* (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator*= (double a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator*= (rcDegree a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree rcDegree::operator+ (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator+= (rcDegree a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree rcDegree::operator- (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree rcDegree::operator- () const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator-= (rcDegree a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree rcDegree::operator/ (double a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
double rcDegree::operator/ (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator/= (double a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator/= (rcDegree a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
bool rcDegree::operator< (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
bool rcDegree::operator<= (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
rcDegree& rcDegree::operator= (double a) inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
bool rcDegree::operator== (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
bool rcDegree::operator> (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
bool rcDegree::operator>= (rcDegree a) const inline
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
Friends And Related Function Documentation
rcDegree operator* (double a, rcDegree b) friend
Definition at line 264 of file rc_math.h.
 :
inline rcDegree (rcRadian);
Member Data Documentation
double rcDegree::val private
Definition at line 264 of file rc_math.h.
Referenced by norm(), and normSigned().
The documentation for this class was generated from the following files:
include/util/rc_math.h
src/util/code/rc_units.cpp