Visible: rcMuscleTracker Class Reference
rcMuscleTracker Class Reference
#include <include/analysis/rc_muscletracker.h>
Public Types
typedef void(* mtDebug)(rcWindow &vProj, rcWindow &hProj)
Public Member Functions
rcMuscleTracker (uint32 smoothingRadius)
void setEdgeFilter (uint32 oneCnt, uint32 zeroCnt)
void setEdgeStrength (double stdDev)
void setEdgePersistence (double percent)
bool calculateCellLocation (vector< rcWindow > &images, mtDebug showDiags, rcProgressIndicator *progressIndicator=0)
rcDPair genEdgePoints (rcWindow image, vector< double > *lCorrSpace, vector< double > *rCorrSpace)
rcRect leftModel () const
rcRect rightModel () const
rcRect leftSpace () const
rcRect rightSpace () const
rcIPair leftOffset () const
rcIPair rightOffset () const
const vector< uint32 > & vCandPosDist () const
const vector< uint32 > & vCandNegDist () const
const vector< uint32 > & hCandPosDist () const
const vector< uint32 > & hCandNegDist () const
Private Member Functions
void genSpace (rcWindow &srchWin, rcWindow &model, vector< vector< double > > &space, uint32 &peakOffsetX, uint32 &peakOffsetY)
Private Attributes
rcRect _leftModel
rcRect _rightModel
rcRect _leftSpace
rcRect _rightSpace
rcIPair _leftOffset
rcIPair _rightOffset
vector< uint32 > _vCandPosDist
vector< uint32 > _vCandNegDist
vector< uint32 > _hCandPosDist
vector< uint32 > _hCandNegDist
uint32 _leftFrameIndex
uint32 _rightFrameIndex
rcWindow _lMdlWin
rcWindow _rMdlWin
rcWindow _lSrchWin
rcWindow _rSrchWin
vector< vector< double > > _lResSpace
vector< vector< double > > _rResSpace
double _rightToLeftOffset
vector< int32 > _filter
uint32 _filterOffset
double _stdDev
double _persistPct
vector< uint16 > _smoothing
uint32 _smoothingNorm
Detailed Description
Definition at line 18 of file rc_muscletracker.h.
Member Typedef Documentation
typedef void(* rcMuscleTracker::mtDebug)(rcWindow &vProj, rcWindow &hProj)
Definition at line 64 of file rc_muscletracker.h.
Constructor & Destructor Documentation
rcMuscleTracker::rcMuscleTracker (uint32 smoothingRadius)
Definition at line 17 of file rc_muscletracker.cpp.
References _smoothing, _smoothingNorm, and setEdgeFilter().
   : _filterOffset(4), _stdDev(4.0),
     _persistPct(.6), _smoothing(smoothingRadius*2 + 1)
 {
   uint32 curValue = 1;
   uint32 curSum = 0;
   uint32 backI = smoothingRadius*2;
   uint32 frtI = 0;
   while (frtI < smoothingRadius) {
     _smoothing[frtI++] = _smoothing[backI--] = curValue;
     curValue <<= 1;
     curSum += curValue;
   }
   _smoothing[frtI] = curValue;
   curSum += curValue;
   _smoothingNorm = curSum >> 1;
   setEdgeFilter(4, 0);
 }
Member Function Documentation
bool rcMuscleTracker::calculateCellLocation (vector< rcWindow > & images, mtDebug showDiags, rcProgressIndicator * progressIndicator = 0)
Definition at line 55 of file rc_muscletracker.cpp.
References _filter, _filterOffset, _hCandNegDist, _hCandPosDist, _leftFrameIndex, _leftModel, _leftOffset, _leftSpace, _lMdlWin, _lSrchWin, _persistPct, _rightFrameIndex, _rightModel, _rightOffset, _rightSpace, _rightToLeftOffset, _rMdlWin, _rSrchWin, _stdDev, _vCandNegDist, _vCandPosDist, rcMomentGenerator::eMoment2D, rcEdgeFilter1D::filter(), rcEdgeFilter1D::genPeaks(), rcWindow::getPixel(), rcWindow::height(), rcRectangle< T >::height(), rcMomentGenerator::hProject(), rcProgressIndicator::progress(), rcPixel32, rcWindow::setPixel(), rcMomentGenerator::update(), rcMomentGenerator::vProject(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   if (images.size() == 0) {
     _lMdlWin = rcWindow();
     _rMdlWin = rcWindow();
     return false;
   }
   rcEdgeFilter1D edgeGen;
   edgeGen.filter(_filter);
   rcMomentGenerator mom(rcMomentGenerator::eMoment2D);
   const uint32 width = images[0].width();
   const uint32 height = images[0].height();
   rcWindow vProj(width, 1, rcPixel32);
   rcWindow hProj(height, 1, rcPixel32);
   /* The following vectors will hold the number of times a strong edge
    * is found at each vertical/horizontal position. The array names
    * are chosen to reflect the fact that each position is a potential
    * candidate location for a cell edge.
    */
   if (_vCandPosDist.size() != width)
     _vCandPosDist.resize(width);
   if (_vCandNegDist.size() != width)
     _vCandNegDist.resize(width);
   for (uint32 i = 0; i < width; i++)
     _vCandPosDist[i] = _vCandNegDist[i] = 0;
   if (_hCandPosDist.size() != height)
     _hCandPosDist.resize(height);
   if (_hCandNegDist.size() != height)
     _hCandNegDist.resize(height);
   for (uint32 i = 0; i < height; i++)
     _hCandPosDist[i] = _hCandNegDist[i] = 0;
   /* Place to store the indices of frames that can be used as a source
    * of model pixels.
    */
   vector<uint32> vCandPosFrmNum(width), vCandNegFrmNum(width);
   rcRect loc(0, 0, width, height);
   fprintf(stderr, "loc x %d y %d w %d h %d fi x %d y %d w %d h %d\n",
       loc.x(), loc.y(), loc.width(), loc.height(),
       images[0].x(), images[0].y(),
       images[0].width(), images[0].height());
   /* Generate the frequency distribution of strong "positive" and
    * "negative" edges.
    */
   for (uint32 i = images.size() - 1; i != 0xFFFFFFFF; i--) {
       if ( progressIndicator )
           if ( progressIndicator->progress( 100.0 * (images.size() - i)/images.size() ) )
               return false;
     mom.update(images[i]);
     images[i].frameBuf().unlock();
     mom.vProject(loc, vProj);
     mom.hProject(loc, hProj);
     if (showDiags)
       (*showDiags)(vProj, hProj);
     vector<rcEdgeFilter1DPeak> vPeaks, hPeaks;
     /* Generate edge points that have a strength value >= _StdDev
      * std. dev. of norm.
      */
     edgeGen.genPeaks(vProj, 0, vPeaks, _filterOffset, 0, _stdDev);
     /* Now update running history of peaks found at each location,
      * both in the vertical and horizontal dimensions. Also store
      * indice of frame where, given a particular location is chosen,
      * model pixels may be found. Note that this is only needed in the
      * vertical direction, since it assumed that cells only move along
      * the horizontal axis.
      */
     for (uint32 pIndex = 0; pIndex < vPeaks.size(); pIndex++) {
       const int32 curLoc = vPeaks[pIndex]._location;
       if (vPeaks[pIndex]._value > 0) {
     _vCandPosDist[curLoc]++;
     vCandPosFrmNum[curLoc] = i;
       }
       else {
     _vCandNegDist[curLoc]++;
     vCandNegFrmNum[curLoc] = i;
       }
     }
     /* Lather, Rinse, and Repeat in the horizontal direction.
      */
     edgeGen.genPeaks(hProj, 0, hPeaks, _filterOffset, 0, _stdDev);
     for (uint32 pIndex = 0; pIndex < hPeaks.size(); pIndex++) {
       const int32 curLoc = hPeaks[pIndex]._location;
       if (hPeaks[pIndex]._value > 0)
     _hCandPosDist[curLoc]++;
       else
     _hCandNegDist[curLoc]++;
     }
   }
   /* The following heurisitic is used to calculate the edge positions
    * that will form the boundary of the cell:
    *
    * 1) Edge persistence is used to cull out transient edges. The
    *    previously calculated frequency distribution is used to
    *    determine this. An edge will be considered to be persisitent
    *    if it was found at least _persistPct percent of the time.
    *
    * 2) It is assumed that the scene is not confusing, so the
    *    outermost persistent edges will be chosen as the final cell
    *    limits.
    */
   uint32 pCutOff = (uint32)(images.size()*_persistPct);
   uint32 leftEdge = 0xFFFFFFFF, rightEdge = 0;
   uint32 topEdge = 0xFFFFFFFF, bottomEdge = 0;
   for (uint32 x = 0; x < width; x++)
     if (_vCandPosDist[x] > pCutOff) {
       leftEdge = x;
       _leftFrameIndex = vCandPosFrmNum[x];
       break;
     }
     else if (_vCandNegDist[x] > pCutOff) {
       leftEdge = x;
       _leftFrameIndex = vCandNegFrmNum[x];
       break;
     }
   for (uint32 x = width; x-- > 0; )
     if (_vCandPosDist[x] > pCutOff) {
       rightEdge = x;
       _rightFrameIndex = vCandPosFrmNum[x];
       break;
     }
     else if (_vCandNegDist[x] > pCutOff) {
       rightEdge = x;
       _rightFrameIndex = vCandNegFrmNum[x];
       break;
     }
   for (uint32 y = 0; y < height; y++)
     if ((_hCandPosDist[y] > pCutOff) || (_hCandNegDist[y] > pCutOff)) {
       topEdge = y;
       break;
     }
   for (uint32 y = height; y-- > 0; )
     if ((_hCandPosDist[y] > pCutOff) || (_hCandNegDist[y] > pCutOff)) {
       bottomEdge = y;
       break;
     }
   if ((leftEdge >= rightEdge) || (topEdge >= bottomEdge)) {
     printf("Couldn't find cell boundaries l %d r %d t %d b %d\n",
        leftEdge, rightEdge, topEdge, bottomEdge);
     _lMdlWin = rcWindow();
     _rMdlWin = rcWindow();
     return false;
   }
   /* Use the previously calculated edge locations to generate the results:
    * models, search spaces, and initial offset within search space.
    */
   const uint32 cellWidth = rightEdge - leftEdge + 1;
   const uint32 cellHeight = bottomEdge - topEdge + 1;
   const uint32 outerSlop = 6;
   const uint32 innerSlop = cellWidth/20 > 8 ? cellWidth/20 : 8;
   const uint32 heightSlop = 2;
   _leftModel = rcRect(leftEdge - outerSlop,
               topEdge - heightSlop,
               innerSlop + outerSlop,
               cellHeight + heightSlop*2);
   _leftSpace = rcRect(_leftModel.x() - 4,
               _leftModel.y() - 2,
               _leftModel.width() + 4 + (cellWidth*10)/100,
               _leftModel.height() + 4);
   _leftOffset = rcIPair(outerSlop, 0);
   _rightModel = rcRect(rightEdge - innerSlop,
                topEdge - heightSlop,
                innerSlop + outerSlop,
                cellHeight + heightSlop*2);
   _rightSpace = rcRect(_rightModel.x() - (cellWidth*10)/100,
                _rightModel.y() - 2,
                _rightModel.width() + 4 + (cellWidth*10)/100,
                _rightModel.height() + 4);
   _rightOffset = rcIPair(innerSlop, 0);
   _lMdlWin = rcWindow(_leftModel.width(), _leftModel.height());
   rcWindow lp(images[_leftFrameIndex],
           _leftModel.x(), _leftModel.y() - 2,
           _leftModel.width(), _leftModel.height() + 4);
   for (int32 yo = 0; yo < _lMdlWin.height(); yo++) {
     for (int32 xo = 0; xo < _lMdlWin.width(); xo++) {
       uint32 pixel =
     (lp.getPixel(xo, yo) + lp.getPixel(xo, yo+4))*3 +
     (lp.getPixel(xo, yo+1) + lp.getPixel(xo, yo+3))*11 +
     lp.getPixel(xo, yo+2)*17;
       _lMdlWin.setPixel(xo, yo, (pixel+22)/45);
     }
   }
   _rMdlWin = rcWindow(_rightModel.width(), _rightModel.height());
   rcWindow rp(images[_rightFrameIndex],
           _rightModel.x(), _rightModel.y() - 2,
           _rightModel.width(), _rightModel.height() + 4);
   for (int32 yo = 0; yo < _rMdlWin.height(); yo++) {
     for (int32 xo = 0; xo < _rMdlWin.width(); xo++) {
       uint32 pixel =
     (rp.getPixel(xo, yo) + rp.getPixel(xo, yo+4))*3 +
     (rp.getPixel(xo, yo+1) + rp.getPixel(xo, yo+3))*11 +
     rp.getPixel(xo, yo+2)*17;
       _rMdlWin.setPixel(xo, yo, (pixel+22)/45);
     }
   }
   _lSrchWin = rcWindow(_leftSpace.width(), _leftSpace.height());
   _rSrchWin = rcWindow(_rightSpace.width(), _rightSpace.height());
   _rightToLeftOffset = _rightSpace.x() - _leftSpace.x();
   return true;
 }
rcDPair rcMuscleTracker::genEdgePoints (rcWindow image, vector< double > * lCorrSpace, vector< double > * rCorrSpace)
Definition at line 290 of file rc_muscletracker.cpp.
References _leftSpace, _lMdlWin, _lResSpace, _lSrchWin, _rightSpace, _rightToLeftOffset, _rMdlWin, _rResSpace, _rSrchWin, genSpace(), rcWindow::getPixel(), rcWindow::height(), rcRectangle< T >::height(), rcWindow::isBound(), parabolicFit(), rmAssert, rcWindow::setPixel(), rcWindow::width(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
   rmAssert(_lMdlWin.isBound() && _rMdlWin.isBound());
   /* Create smoothed versions of image pixels and generate xorrelation
    * spaces.
    */
   rcWindow lp(image, _leftSpace.x(), _leftSpace.y() - 2,
           _leftSpace.width(), _leftSpace.height() + 4);
   for (int32 yo = 0; yo < _lSrchWin.height(); yo++) {
     for (int32 xo = 0; xo < _lSrchWin.width(); xo++) {
       uint32 pixel =
     (lp.getPixel(xo, yo) + lp.getPixel(xo, yo+4))*3 +
     (lp.getPixel(xo, yo+1) + lp.getPixel(xo, yo+3))*11 +
     lp.getPixel(xo, yo+2)*17;
     _lSrchWin.setPixel(xo, yo, (pixel+22)/45);
     }
   }
   uint32 lPeakOffsetX, lPeakOffsetY;
   genSpace(_lSrchWin, _lMdlWin, _lResSpace, lPeakOffsetX, lPeakOffsetY);
   rcWindow rp(image, _rightSpace.x(), _rightSpace.y() - 2,
           _rightSpace.width(), _rightSpace.height() + 4);
   for (int32 yo = 0; yo < _rSrchWin.height(); yo++) {
     for (int32 xo = 0; xo < _rSrchWin.width(); xo++) {
       uint32 pixel =
     (rp.getPixel(xo, yo) + rp.getPixel(xo, yo+4))*3 +
     (rp.getPixel(xo, yo+1) + rp.getPixel(xo, yo+3))*11 +
     rp.getPixel(xo, yo+2)*17;
       _rSrchWin.setPixel(xo, yo, (pixel+22)/45);
     }
   }
   uint32 rPeakOffsetX, rPeakOffsetY;
   genSpace(_rSrchWin, _rMdlWin, _rResSpace, rPeakOffsetX, rPeakOffsetY);
   /* Generate interpolated position information.
    */
   double lPeakInterpolatedOffsetX, rPeakInterpolatedOffsetX;
   if ((lPeakOffsetX == 0) ||
       (lPeakOffsetX == _lResSpace[lPeakOffsetY].size() - 1)) {
     fprintf(stderr, "WARNING: Left peak at edge!!!: ");
     lPeakInterpolatedOffsetX = lPeakOffsetX;
   }
   else {
     double offset = parabolicFit(_lResSpace[lPeakOffsetY][lPeakOffsetX-1],
                  _lResSpace[lPeakOffsetY][lPeakOffsetX],
                  _lResSpace[lPeakOffsetY][lPeakOffsetX+1],
                  (double*)0);
     lPeakInterpolatedOffsetX = lPeakOffsetX + offset;
   }
   if ((rPeakOffsetX == 0) ||
       (rPeakOffsetX == _rResSpace[rPeakOffsetY].size() - 1)) {
     printf("WARNING: Right peak at edge!!!: ");
     rPeakInterpolatedOffsetX = rPeakOffsetX;
   }
   else {
     double offset = parabolicFit(_rResSpace[rPeakOffsetY][rPeakOffsetX-1],
                  _rResSpace[rPeakOffsetY][rPeakOffsetX],
                  _rResSpace[rPeakOffsetY][rPeakOffsetX+1],
                  (double*)0);
     rPeakInterpolatedOffsetX = rPeakOffsetX + offset;
   }
   /* If client has passed a pointer to a 1D correlation space vector,
    * fill it with a compressed version of the the actual correlation
    * space: for each location in x, pick the highest score in the y
    * dimension.
    */
   if (lCorrSpace) {
     if (lCorrSpace->size() != _lResSpace[0].size())
       lCorrSpace->resize(_lResSpace[0].size());
     for (uint32 x = 0; x < _lResSpace[0].size(); x++) {
       double maxX = -1.0;
       for (uint32 y = 0; y < _lResSpace.size(); y++)
     if (_lResSpace[y][x] > maxX)
       maxX = _lResSpace[y][x];
       (*lCorrSpace)[x] = maxX;
     }
   }
   if (rCorrSpace) {
     if (rCorrSpace->size() != _rResSpace[0].size())
       rCorrSpace->resize(_rResSpace[0].size());
     for (uint32 x = 0; x < _rResSpace[0].size(); x++) {
       double maxX = -1.0;
       for (uint32 y = 0; y < _rResSpace.size(); y++)
     if (_rResSpace[y][x] > maxX)
       maxX = _rResSpace[y][x];
       (*rCorrSpace)[x] = maxX;
     }
   }
   return rcDPair(lPeakInterpolatedOffsetX,
          rPeakInterpolatedOffsetX + _rightToLeftOffset);
 }
void rcMuscleTracker::genSpace (rcWindow & srchWin, rcWindow & model, vector< vector< double > > & space, uint32 & peakOffsetX, uint32 & peakOffsetY) private
Definition at line 389 of file rc_muscletracker.cpp.
References rcWindow::height(), rcCorr::r(), rfCorrelate(), rmAssert, space, and rcWindow::width().
Referenced by genEdgePoints().
 {
   rmAssert(srchWin.width() >= model.width());
   rmAssert(srchWin.height() >= model.height());
   uint32 spaceWidth = srchWin.width() - model.width() + 1;
   uint32 spaceHeight = srchWin.height() - model.height() + 1;
   if (space.size() != spaceHeight) {
     space.resize(spaceHeight);
     for (uint32 y = 0; y < spaceHeight; y++)
       space[y].resize(spaceWidth);
   }
   else {
     for (uint32 y = 0; y < spaceHeight; y++)
       if (space[y].size() != spaceWidth)
     space[y].resize(spaceWidth);
   }
   rsCorrParams params;
   rcCorr res;
   double maxScore = -1.0;
   const rcIPair shiftRightOne(1, 0);
   for (uint32 y = 0; y < spaceHeight; y++) {
     rcWindow image(srchWin, 0, y, model.width(), model.height());
     for (uint32 x = 0; x < spaceWidth; ) {
       rfCorrelate(model, image, params, res);
       const double score = res.r();
       if (score > maxScore) {
     maxScore = score;
     peakOffsetX = x;
     peakOffsetY = y;
       }
       space[y][x++] = score;
       if (x != spaceWidth)
     image.translate(shiftRightOne);
     }
   }
 }
const vector<uint32>& rcMuscleTracker::hCandNegDist () const inline
Definition at line 105 of file rc_muscletracker.h.
References _hCandNegDist.
 { return _hCandNegDist; }
const vector<uint32>& rcMuscleTracker::hCandPosDist () const inline
Definition at line 104 of file rc_muscletracker.h.
References _hCandPosDist.
 { return _hCandPosDist; }
rcRect rcMuscleTracker::leftModel () const inline
Definition at line 96 of file rc_muscletracker.h.
References _leftModel.
 { return _leftModel; }
rcIPair rcMuscleTracker::leftOffset () const inline
Definition at line 100 of file rc_muscletracker.h.
References _leftOffset.
 { return _leftOffset; }
rcRect rcMuscleTracker::leftSpace () const inline
Definition at line 98 of file rc_muscletracker.h.
References _leftSpace.
 { return _leftSpace; }
rcRect rcMuscleTracker::rightModel () const inline
Definition at line 97 of file rc_muscletracker.h.
References _rightModel.
 { return _rightModel; }
rcIPair rcMuscleTracker::rightOffset () const inline
Definition at line 101 of file rc_muscletracker.h.
References _rightOffset.
 { return _rightOffset; }
rcRect rcMuscleTracker::rightSpace () const inline
Definition at line 99 of file rc_muscletracker.h.
References _rightSpace.
 { return _rightSpace; }
void rcMuscleTracker::setEdgeFilter (uint32 oneCnt, uint32 zeroCnt)
Definition at line 38 of file rc_muscletracker.cpp.
References _filter, _filterOffset, and rcEdgeFilter1D::genFilter().
Referenced by rcMuscleTracker().
 {
   rcEdgeFilter1D::genFilter(_filter, oneCnt, zeroCnt);
   _filterOffset = oneCnt + (zeroCnt+1)/2;
 }
void rcMuscleTracker::setEdgePersistence (double percent)
Definition at line 50 of file rc_muscletracker.cpp.
References _persistPct, and percent().
 {
   _persistPct = percent;
 }
void rcMuscleTracker::setEdgeStrength (double stdDev)
Definition at line 45 of file rc_muscletracker.cpp.
References _stdDev.
 {
   _stdDev = stdDev;
 }
const vector<uint32>& rcMuscleTracker::vCandNegDist () const inline
Definition at line 103 of file rc_muscletracker.h.
References _vCandNegDist.
 { return _vCandNegDist; }
const vector<uint32>& rcMuscleTracker::vCandPosDist () const inline
Definition at line 102 of file rc_muscletracker.h.
References _vCandPosDist.
 { return _vCandPosDist; }
Member Data Documentation
vector<int32> rcMuscleTracker::_filter private
Definition at line 125 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and setEdgeFilter().
uint32 rcMuscleTracker::_filterOffset private
Definition at line 126 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and setEdgeFilter().
vector<uint32> rcMuscleTracker::_hCandNegDist private
Definition at line 117 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and hCandNegDist().
vector<uint32> rcMuscleTracker::_hCandPosDist private
Definition at line 117 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and hCandPosDist().
uint32 rcMuscleTracker::_leftFrameIndex private
Definition at line 119 of file rc_muscletracker.h.
Referenced by calculateCellLocation().
rcRect rcMuscleTracker::_leftModel private
Definition at line 113 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and leftModel().
rcIPair rcMuscleTracker::_leftOffset private
Definition at line 115 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and leftOffset().
rcRect rcMuscleTracker::_leftSpace private
Definition at line 114 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), genEdgePoints(), and leftSpace().
rcWindow rcMuscleTracker::_lMdlWin private
Definition at line 120 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and genEdgePoints().
vector<vector<double> > rcMuscleTracker::_lResSpace private
Definition at line 122 of file rc_muscletracker.h.
Referenced by genEdgePoints().
rcWindow rcMuscleTracker::_lSrchWin private
Definition at line 121 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and genEdgePoints().
double rcMuscleTracker::_persistPct private
Definition at line 128 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and setEdgePersistence().
uint32 rcMuscleTracker::_rightFrameIndex private
Definition at line 119 of file rc_muscletracker.h.
Referenced by calculateCellLocation().
rcRect rcMuscleTracker::_rightModel private
Definition at line 113 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and rightModel().
rcIPair rcMuscleTracker::_rightOffset private
Definition at line 115 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and rightOffset().
rcRect rcMuscleTracker::_rightSpace private
Definition at line 114 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), genEdgePoints(), and rightSpace().
double rcMuscleTracker::_rightToLeftOffset private
Definition at line 123 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and genEdgePoints().
rcWindow rcMuscleTracker::_rMdlWin private
Definition at line 120 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and genEdgePoints().
vector<vector<double> > rcMuscleTracker::_rResSpace private
Definition at line 122 of file rc_muscletracker.h.
Referenced by genEdgePoints().
rcWindow rcMuscleTracker::_rSrchWin private
Definition at line 121 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and genEdgePoints().
vector<uint16> rcMuscleTracker::_smoothing private
Definition at line 129 of file rc_muscletracker.h.
Referenced by rcMuscleTracker().
uint32 rcMuscleTracker::_smoothingNorm private
Definition at line 130 of file rc_muscletracker.h.
Referenced by rcMuscleTracker().
double rcMuscleTracker::_stdDev private
Definition at line 127 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and setEdgeStrength().
vector<uint32> rcMuscleTracker::_vCandNegDist private
Definition at line 116 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and vCandNegDist().
vector<uint32> rcMuscleTracker::_vCandPosDist private
Definition at line 116 of file rc_muscletracker.h.
Referenced by calculateCellLocation(), and vCandPosDist().
The documentation for this class was generated from the following files:
include/analysis/rc_muscletracker.h
src/analysis/code/rc_muscletracker.cpp