Visible: rcFileSaveSettingWidget Class Reference
rcFileSaveSettingWidget Class Reference
#include <include/visUI/rc_filesavesettingwidget.h>
Public Slots
void browseRequest (void)
void valueChanged (void)
void settingChanged (void)
void updateState (rcExperimentState state)
void movieSave (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcFileSaveSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcFileSaveSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
QLineEdit * mFilenameWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 12 of file rc_filesavesettingwidget.h.
Constructor & Destructor Documentation
rcFileSaveSettingWidget::rcFileSaveSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 24 of file rc_filesavesettingwidget.cpp.
References rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), mFilenameWidget, movieSave(), rcSettingWidget::mTopLayout, settingChanged(), and updateState().
   : rcSettingWidget(parent, setting)
 {
   mFilenameWidget = new QLineEdit( this , setting.getTag() );
   mTopLayout->addWidget( mFilenameWidget );
   mTopLayout->addSpacing( 5 );
   // use the setting description as a tool tip
   QToolTip::add( mFilenameWidget , setting.getDescription() );
   mFilenameWidget->setReadOnly( true );
   // update the text widget with the current value of the setting.
   settingChanged();
   // connect this widget to be notified by the updateSettings()
   //    signal from the model domain
   rcModelDomain* domain = rcModelDomain::getModelDomain();
   connect( domain , SIGNAL( updateSettings() ) ,
        this   , SLOT( settingChanged() ) );
   connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
        this   , SLOT( updateState( rcExperimentState ) ) );
   // Import signals (from File menu)
   connect( domain , SIGNAL( movieSave( void ) )  ,
        this , SLOT( movieSave( void ) ) );
 }
rcFileSaveSettingWidget::~rcFileSaveSettingWidget ()
Definition at line 55 of file rc_filesavesettingwidget.cpp.
References mFilenameWidget.
 {
     QToolTip::remove( mFilenameWidget );
 }
Member Function Documentation
void rcFileSaveSettingWidget::browseRequest (void) slot
Definition at line 62 of file rc_filesavesettingwidget.cpp.
References cAppName, eExperimentNativeMovieFormat, rcPersistenceManager::fileFormatExportCaption(), rcPersistenceManager::fileFormatExportExtension(), rcPersistenceManager::fileFormatExportFilter(), rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcPersistenceManagerFactory::getPersistenceManager(), rcSettingInfo::getTag(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), null, rcSettingInfo::setValue(), rcValue::stringValue(), and rcExperimentAttributes::title.
Referenced by movieSave().
 {
     QString defaultName( mSetting.getValue().stringValue ().c_str() );
   if ( defaultName.isEmpty() ) {
       rcModelDomain* domain = rcModelDomain::getModelDomain();
       // Use experiment title as default name
       rcExperimentAttributes attr = domain->getExperimentAttributes();
       defaultName = attr.title.c_str();
       // We need to replace slashes with something else
       defaultName.replace( QChar('/'), "-" );
   }
   rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     std::string tmp = persistenceManager->fileFormatExportFilter(eExperimentNativeMovieFormat );
     QString filter (tmp.c_str());
     tmp = persistenceManager->fileFormatExportCaption(eExperimentNativeMovieFormat );
     QString caption (tmp.c_str());
   QString s = Q3FileDialog::getSaveFileName(defaultName,
                                            filter,
                                            0,
                                            mSetting.getTag(),
                                            caption,
                                            &filter);
   if (s != QString::null)
   {
     std::string tmp = persistenceManager->fileFormatExportExtension(eExperimentNativeMovieFormat );
     QString ext (tmp.c_str());
     // Force to lowercase for case-insensitive comparison
     QString sLower = s.lower();
     ext = ext.lower();
     if (!sLower.endsWith( ext ))
       s += ext;
     // warn if file already exists
     if (QFile::exists(s))
     {
       if (QMessageBox::warning( 0,
                 cAppName,
                 "File already exists: overwrite?",
                 QMessageBox::Ok , QMessageBox::Cancel)
       == QMessageBox::Cancel)
     return;
     }
     // if a file was selected, update the setting
     mSetting.setValue( s.latin1() );
     // notify everybody (including us) about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
   }
 }
void rcFileSaveSettingWidget::movieSave (void) slot
Definition at line 166 of file rc_filesavesettingwidget.cpp.
References browseRequest().
Referenced by rcFileSaveSettingWidget().
 {
   browseRequest();
 }
void rcFileSaveSettingWidget::settingChanged (void) slot
Definition at line 128 of file rc_filesavesettingwidget.cpp.
References rcSettingInfo::getValue(), mFilenameWidget, rcSettingWidget::mSetting, and rcSettingWidget::updateWidgetState().
Referenced by rcFileSaveSettingWidget().
 {
     string currentValue = mSetting.getValue();
     mFilenameWidget->setText( currentValue.c_str() );
     updateWidgetState();
 }
void rcFileSaveSettingWidget::updateState (rcExperimentState state) slot
Definition at line 136 of file rc_filesavesettingwidget.cpp.
References eExperimentEmpty, eExperimentEnded, eExperimentLocked, eExperimentPlayback, and eExperimentRunning.
Referenced by rcFileSaveSettingWidget().
 {
   // The widget is read-only so it can always remain enabled
   switch( state ) {
   case eExperimentEmpty:          // experiment was created but not run
     setEnabled( true );
     break;
   case eExperimentRunning:        // experiment is running
     setEnabled( true );
     break;
   case eExperimentPlayback:       // experiment is playing back
     setEnabled( true );
     break;
   case eExperimentEnded:          // experiment has ended
     setEnabled( true );
     break;
   case eExperimentLocked:         // experiment has ended and been saved
     setEnabled( true );
     break;
   default:
     break;
   }
 }
void rcFileSaveSettingWidget::valueChanged (void) slot
Definition at line 118 of file rc_filesavesettingwidget.cpp.
References rcModelDomain::getModelDomain(), mFilenameWidget, rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
 {
   mSetting.setValue( mFilenameWidget->text().latin1() );
   // notify everybody about the change
   rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
QLineEdit* rcFileSaveSettingWidget::mFilenameWidget private
Definition at line 31 of file rc_filesavesettingwidget.h.
Referenced by rcFileSaveSettingWidget(), settingChanged(), valueChanged(), and ~rcFileSaveSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_filesavesettingwidget.h
src/visible/qt/rc_filesavesettingwidget.cpp