Visible: rcExperimentImpl Class Reference
rcExperimentImpl Class Reference
#include <include/visiCore/rc_experimentimpl.h>
Public Member Functions
rcExperimentImpl (void)
rcExperimentImpl (const char *filename)
virtual ~rcExperimentImpl (void)
int saveTo (const char *filename, rcExperimentFileFormat format, const rcMovieConverterOptions &opt, rcCarbonLock *lock, rcProgressIndicator *progress)
void loadTemplateData (const char *filename)
void saveTemplateData (const char *filename)
int loadExperiment (const rcXMLElementTree &tree, rcExperimentImportMode mode, rcEngineObserver *observer, rcProgressIndicator *progress)
rcTrackGroupImpl * createTrackGroup (const char *tag, const char *name, const char *description, rcGroupSemantics type)
virtual int getNSettingCategories (void)
virtual rcSettingCategory getSettingCategory (int categoryNo)
virtual int getNTrackGroups (void)
virtual rcTrackGroup * getTrackGroup (int trackGroupNo)
virtual rcTimestamp getLength (void)
virtual const rcValue getSettingValue (int settingId)
virtual void setSettingValue (int settingId, const rcValue &value)
virtual bool isSettingEnabled (int settingId)
virtual bool isSettingEditable (int settingId)
virtual bool isSettingPersistable (int settingId)
void editableSettings (bool enabled)
Public Member Functions inherited from rcExperiment
virtual ~rcExperiment ()
Private Member Functions
void unspecifySettings ()
int exportMovie (const std::string &outputFile, const rcMovieConverterOptions &baseOpt, rcExperimentFileFormat format, rcCarbonLock *lock, rcProgressIndicator *progress)
Private Member Functions inherited from rcSettingSource
virtual ~rcSettingSource ()
Private Attributes
rcMutex _settingMutex
rcMutex _trackMutex
vector< rcSettingCategory > _settings
vector< rcTrackGroupImpl * > _trackGroups
bool _settingsEditable
std::string _fileName
std::string _userName
std::string _title
std::string _comments
std::string _inputImageSource
std::string _microscopeMag
std::string _otherMag
std::string _cellType
std::string _cellTreatment1
std::string _cellTreatment2
std::string _cellTemperature
std::string _cellCO2
std::string _cellO2
std::string _imagingMode
Detailed Description
Definition at line 50 of file rc_experimentimpl.h.
Constructor & Destructor Documentation
rcExperimentImpl::rcExperimentImpl (void)
Definition at line 260 of file rc_experimentimpl.cpp.
References generalSettings, generalSettingsSpec, rcEngineFactory::getEngine(), rcEngine::getNSettingCategories(), and rcEngine::getSettingCategory().
 {
     unspecifySettings();
     rcLock lock( _settingMutex );
     rcSettingCategory generalSettings( this , &generalSettingsSpec );
     _settings.push_back( generalSettings );
     rcEngine* engine = rcEngineFactory::getEngine();
     for (int i = 0; i < engine->getNSettingCategories(); i++)
         _settings.push_back( engine->getSettingCategory( i ) );
     _settingsEditable = true;
 }
rcExperimentImpl::rcExperimentImpl (const char * filename)
Definition at line 276 of file rc_experimentimpl.cpp.
References rcUNUSED.
 {
     rcUNUSED( filename );
 }
rcExperimentImpl::~rcExperimentImpl (void) virtual
Definition at line 282 of file rc_experimentimpl.cpp.
 {
     rcLock lock( _trackMutex );
     _title = "Deleted";
     for ( uint32 i = 0; i < _trackGroups.size(); i++ ) {
         if ( _trackGroups[i] ) {
             delete _trackGroups[i];
             _trackGroups[i] = 0;
         }
     }
 }
Member Function Documentation
rcTrackGroupImpl * rcExperimentImpl::createTrackGroup (const char * tag, const char * name, const char * description, rcGroupSemantics type)
Definition at line 447 of file rc_experimentimpl.cpp.
Referenced by rcExperimentDomainImpl::createWriterGroup().
 {
     rcTrackGroupImpl* trackGroup = new rcTrackGroupImpl( tag , name , description, type );
     _trackGroups.push_back( trackGroup );
     return trackGroup;
 }
void rcExperimentImpl::editableSettings (bool enabled)
Definition at line 700 of file rc_experimentimpl.cpp.
Referenced by rcExperimentDomainImpl::notifyState().
 {
     rcLock lock( _settingMutex );
     _settingsEditable = enabled;
 }
int rcExperimentImpl::exportMovie (const std::string & outputFile, const rcMovieConverterOptions & baseOpt, rcExperimentFileFormat format, rcCarbonLock * lock, rcProgressIndicator * progress) private
Definition at line 296 of file rc_experimentimpl.cpp.
References rcMovieConverterOptionsRfy::channelConversion(), rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), eExperimentNativeMovieFormat, eExperimentQuickTimeMovieFormat, eMovieConverterErrorOK, eMovieConverterErrorUnknown, eMovieConverterErrorUnsupported, endl(), rcMovieConverter::getErrorString(), and rcSelectAll.
 {
     int err = 0;
     if ( !_inputImageSource.empty() ) {
         rcMovieConverterError error = eMovieConverterErrorUnknown;
         switch( format ) {
             case eExperimentQuickTimeMovieFormat:
             {
                 rcMovieConverterOptionsQT opt( baseOpt );
                 rcMovieConverterToQT converter( opt, lock, progress );
                 error = converter.convert( _inputImageSource, outputFile );
             }
             break;
             case eExperimentNativeMovieFormat:
             {
                 rcMovieConverterOptionsRfy opt( baseOpt );
                 opt.channelConversion( rcSelectAll );
                 rcMovieConverterToRfy converter( opt, lock, progress );
                 error = converter.convert( _inputImageSource, outputFile );
             }
             break;
             default:
                 break;
         }
         if ( error != eMovieConverterErrorOK ) {
             cerr << rcMovieConverter::getErrorString( error ) << endl;
             if ( error == eMovieConverterErrorUnsupported )
                 err = ENOTSUP;
             else
                 err = EIO;
         }
     } else {
         cerr << "Export error: no input image file defined" << endl;
     }
     return err;
 }
rcTimestamp rcExperimentImpl::getLength (void) virtual
Implements rcExperiment.
Definition at line 491 of file rc_experimentimpl.cpp.
 {
     return 0.0;
 }
int rcExperimentImpl::getNSettingCategories (void) virtual
Implements rcExperiment.
Definition at line 460 of file rc_experimentimpl.cpp.
Referenced by rcNativeImporter::findSettingCategory(), rcExperimentDomainImpl::saveExperiment(), and rcNativeImporter::setSettingValue().
 {
     rcLock lock( _settingMutex );
     return _settings.size();
 }
int rcExperimentImpl::getNTrackGroups (void) virtual
Implements rcExperiment.
Definition at line 474 of file rc_experimentimpl.cpp.
 {
     rcLock lock( _trackMutex );
     return _trackGroups.size();
 }
rcSettingCategory rcExperimentImpl::getSettingCategory (int categoryNo) virtual
Implements rcExperiment.
Definition at line 467 of file rc_experimentimpl.cpp.
Referenced by rcNativeImporter::findSetting(), rcNativeImporter::findSettingCategory(), rcExperimentDomainImpl::saveExperiment(), and rcNativeImporter::setSettingValue().
 {
     rcLock lock( _settingMutex );
     return _settings[ categoryNo ];
 }
const rcValue rcExperimentImpl::getSettingValue (int settingId) virtual
Implements rcSettingSource.
Definition at line 499 of file rc_experimentimpl.cpp.
References cCellCO2SettingId, cCellO2SettingId, cCellTemperatureSettingId, cCellTreatment2SettingId, cCellTreatmentSettingId, cCellTypeSettingId, cCommentsSettingId, cFileNameSettingId, cImagingModeSettingId, cInputImageSourceNameSettingId, cMicroscopeMagnificationSettingId, cOtherMagnificationSettingId, cTitleSettingId, and cUserNameSettingId.
Referenced by rcExperimentDomainImpl::getExperimentAttributes().
 {
     rcLock lock( _settingMutex );
     switch (settingId)
     {
     case cFileNameSettingId:
         return _fileName;
     case cUserNameSettingId:
         return _userName;
     case cTitleSettingId:
         return _title;
     case cCommentsSettingId:
         return _comments;
     case cInputImageSourceNameSettingId:
         return _inputImageSource;
     case cMicroscopeMagnificationSettingId:
         return _microscopeMag;
     case cOtherMagnificationSettingId:
         return _otherMag;
     case cCellTypeSettingId:
         return _cellType;
     case cCellTreatmentSettingId:
         return _cellTreatment1;
     case cCellTreatment2SettingId:
         return _cellTreatment2;
     case cCellTemperatureSettingId:
         return _cellTemperature;
     case cCellCO2SettingId:
         return _cellCO2;
     case cCellO2SettingId:
         return _cellO2;
     case cImagingModeSettingId:
         return _imagingMode;
     }
     return "unknown setting";
 }
rcTrackGroup * rcExperimentImpl::getTrackGroup (int trackGroupNo) virtual
Implements rcExperiment.
Definition at line 481 of file rc_experimentimpl.cpp.
 {
     rcLock lock( _trackMutex );
     if ( trackNo <  int(_trackGroups.size()) )
         return _trackGroups[ trackNo ];
     else
         return 0;
 }
bool rcExperimentImpl::isSettingEditable (int settingId) virtual
Implements rcSettingSource.
Definition at line 655 of file rc_experimentimpl.cpp.
References cFileNameSettingId, and cInputImageSourceNameSettingId.
 {
     rcLock lock( _settingMutex );
     if ( !_settingsEditable )
         return false;
     switch (settingId)
     {
         // Read-only setting, this is set by data import
         case cInputImageSourceNameSettingId:
             return false;
         // Read-only setting, this is set by file save dialog
         case cFileNameSettingId:
             return false;
         default:
             break;
     }
     return true;
 }
bool rcExperimentImpl::isSettingEnabled (int settingId) virtual
Implements rcSettingSource.
Definition at line 646 of file rc_experimentimpl.cpp.
References rmUnused.
 {
     rcLock lock( _settingMutex );
     rmUnused( settingId );
     return true;
 }
bool rcExperimentImpl::isSettingPersistable (int settingId) virtual
Implements rcSettingSource.
Definition at line 680 of file rc_experimentimpl.cpp.
References cFileNameSettingId, and cInputImageSourceNameSettingId.
 {
     rcLock lock( _settingMutex );
     switch (settingId)
     {
         case cInputImageSourceNameSettingId:
         case cFileNameSettingId:
             return true;
         default:
             break;
     }
     // Most settings are persisted in a movie header
     return false;
 }
int rcExperimentImpl::loadExperiment (const rcXMLElementTree & tree, rcExperimentImportMode mode, rcEngineObserver * observer, rcProgressIndicator * progress)
Definition at line 407 of file rc_experimentimpl.cpp.
References rcSettingCategorySpec::_name, eExperimentImportExperimentSettings, generalSettingsSpec, and rcNativeImporter::importExperiment().
Referenced by rcExperimentDomainImpl::loadExperiment().
 {
     vector<std::string> importableSettings;
     unspecifySettings();
     switch ( mode ) {
         case eExperimentImportExperimentSettings:
         {
             rcLock lock( _settingMutex );
             // Load only settings from this experiment
             std::string expName( generalSettingsSpec._name );
             importableSettings.push_back( expName );
         }
             break;
         default:
             break;
     }
     rcNativeImporter importer( this, observer, progress );
     int errors = importer.importExperiment( tree, importableSettings );
     return errors;
 }
void rcExperimentImpl::loadTemplateData (const char * filename)
Definition at line 435 of file rc_experimentimpl.cpp.
References rcUNUSED.
 {
     rcUNUSED( filename );
 }
void rcExperimentImpl::saveTemplateData (const char * filename)
Definition at line 441 of file rc_experimentimpl.cpp.
References rcUNUSED.
 {
     rcUNUSED( filename );
 }
int rcExperimentImpl::saveTo (const char * filename, rcExperimentFileFormat format, const rcMovieConverterOptions & opt, rcCarbonLock * lock, rcProgressIndicator * progress)
Definition at line 345 of file rc_experimentimpl.cpp.
References eExperimentCSVFormat, eExperimentNativeFormat, eExperimentNativeMovieFormat, eExperimentQuickTimeMovieFormat, rcCSVExporter::exportExperiment(), rcNativeExporter::exportExperiment(), rcPersistenceManager::fileFormatExportExtension(), rcPersistenceManager::generatorComment(), rcPersistenceManagerFactory::getPersistenceManager(), and rmAssert.
Referenced by rcExperimentDomainImpl::saveExperiment().
 {
     rmAssert( filename != 0 );
     int err = 0;
     // Get application (generator) info
     rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     const std::string comment = persistenceManager->generatorComment();
     const std::string ext = persistenceManager->fileFormatExportExtension( format );
     std::string nameWithExt = filename;
     // Add file name extension if necessary
     if ( nameWithExt.find( ext ) == std::string::npos )
         nameWithExt += ext;
     switch ( format ) {
         case eExperimentCSVFormat:
         {
             rcCSVExporter exporter( nameWithExt.c_str(), this, comment.c_str(), progress );
             err = exporter.exportExperiment();
         }
         break;
         case eExperimentNativeFormat:
         {
             // Remember filename
             _fileName = nameWithExt.c_str();
             rcNativeExporter exporter( nameWithExt.c_str(), this, format, comment.c_str(), progress );
             err = exporter.exportExperiment();
         }
         break;
 #if 0
         case eExperimentNativeGraphicsFormat:
         {
             rcNativeExporter exporter( nameWithExt.c_str(), this, format, comment.c_str(), progress );
             err = exporter.exportExperiment();
         }
         break;
 #endif
         case eExperimentNativeMovieFormat:
         case eExperimentQuickTimeMovieFormat:
             err = exportMovie( nameWithExt, opt, format, lock, progress );
             break;
         default:
             rmAssert( 0 );
             err = ENOTSUP;
             break;
     }
     return err;
 }
void rcExperimentImpl::setSettingValue (int settingId, const rcValue & value) virtual
Implements rcSettingSource.
Definition at line 552 of file rc_experimentimpl.cpp.
References cCellCO2SettingId, cCellO2SettingId, cCellTemperatureSettingId, cCellTreatment2SettingId, cCellTreatmentSettingId, cCellTypeSettingId, cCommentsSettingId, cFileNameSettingId, cImagingModeSettingId, cInputImageSourceNameSettingId, cMicroscopeMagnificationSettingId, cOtherMagnificationSettingId, cTitleSettingId, and cUserNameSettingId.
Referenced by rcExperimentDomainImpl::loadExperiment(), rcExperimentDomainImpl::notifyMovieImport(), rcExperimentDomainImpl::notifyState(), and rcExperimentDomainImpl::setExperimentAttributes().
 {
     rcLock lock( _settingMutex );
     std::string value = v;
     switch (settingId)
     {
     case cFileNameSettingId:
         _fileName = value;
         break;
     case cUserNameSettingId:
         _userName = value;
         break;
     case cTitleSettingId:
         _title = value;
         break;
     case cCommentsSettingId:
         _comments = value;
         break;
     case cInputImageSourceNameSettingId:
         _inputImageSource = value;
         break;
     case cCellTreatmentSettingId:
         _cellTreatment1 = value;
         break;
     case cCellTreatment2SettingId:
         _cellTreatment2 = value;
         break;
     case cMicroscopeMagnificationSettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _microscopeMag = value;
     }
     break;
     case cOtherMagnificationSettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _otherMag = value;
     }
     break;
     case cCellTypeSettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _cellType = value;
     }
     break;
     case cCellTemperatureSettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _cellTemperature = value;
     }
     break;
     case cCellCO2SettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _cellCO2 = value;
     }
     break;
     case cCellO2SettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _cellO2 = value;
     }
     break;
     case cImagingModeSettingId:
     {
         // Empty string must be ignored for menu-based settings
         if ( value.size() )
             _imagingMode = value;
     }
     break;
     }
 }
void rcExperimentImpl::unspecifySettings () private
Definition at line 709 of file rc_experimentimpl.cpp.
 {
      rcLock lock( _settingMutex );
     _title = "Untitled";
     _cellTemperature = "-1.0";
     _microscopeMag = "-1.0";
     _otherMag = "-1.0";
     _cellCO2 = "-1.0";
     _cellO2 = "-1.0";
     _imagingMode = "Unspecified";
     _cellType = "Unspecified";
 }
Member Data Documentation
std::string rcExperimentImpl::_cellCO2 private
Definition at line 155 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_cellO2 private
Definition at line 156 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_cellTemperature private
Definition at line 154 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_cellTreatment1 private
Definition at line 150 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_cellTreatment2 private
Definition at line 151 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_cellType private
Definition at line 149 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_comments private
Definition at line 145 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_fileName private
Definition at line 142 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_imagingMode private
Definition at line 157 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_inputImageSource private
Definition at line 146 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_microscopeMag private
Definition at line 147 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_otherMag private
Definition at line 148 of file rc_experimentimpl.h.
rcMutex rcExperimentImpl::_settingMutex private
Definition at line 136 of file rc_experimentimpl.h.
vector<rcSettingCategory> rcExperimentImpl::_settings private
Definition at line 138 of file rc_experimentimpl.h.
bool rcExperimentImpl::_settingsEditable private
Definition at line 140 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_title private
Definition at line 144 of file rc_experimentimpl.h.
vector<rcTrackGroupImpl*> rcExperimentImpl::_trackGroups private
Definition at line 139 of file rc_experimentimpl.h.
rcMutex rcExperimentImpl::_trackMutex private
Definition at line 137 of file rc_experimentimpl.h.
std::string rcExperimentImpl::_userName private
Definition at line 143 of file rc_experimentimpl.h.
The documentation for this class was generated from the following files:
include/visiCore/rc_experimentimpl.h
src/visible/src/rc_experimentimpl.cpp