Visible: rcTextAreaSettingWidget Class Reference
rcTextAreaSettingWidget Class Reference
#include <include/visUI/rc_textareasettingwidget.h>
Public Slots
void valueChanged (const QString &text)
void settingChanged (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcTextAreaSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcTextAreaSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
rcTextEdit * mWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 7 of file rc_textareasettingwidget.h.
Constructor & Destructor Documentation
rcTextAreaSettingWidget::rcTextAreaSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 17 of file rc_textareasettingwidget.cpp.
References rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), rcSettingInfo::getXArgs(), rcTextAreaArgs::minLines, rcSettingWidget::mTopLayout, mWidget, settingChanged(), and valueChanged().
     : rcSettingWidget( parent, setting )
 {
     // Default text area height
     int lines = 5;
     const rcTextAreaArgs* argsP = static_cast<const rcTextAreaArgs*>(setting.getXArgs());
     if ( argsP ) {
         lines = argsP->minLines;
     }
     mWidget = new rcTextEdit( this, lines, setting.getTag() );
     mTopLayout->addWidget( mWidget );
     // Reduce default point size
     mWidget->zoomOut(1);
     QToolTip::add( mWidget , setting.getDescription() );
     connect( mWidget , SIGNAL( textCommited( const QString& ) ) ,
              this    , SLOT( valueChanged( const QString& ) ) );
     // update the text widget with the current value of the setting.
     settingChanged();
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
 }
rcTextAreaSettingWidget::~rcTextAreaSettingWidget ()
Definition at line 48 of file rc_textareasettingwidget.cpp.
References mWidget.
 {
     QToolTip::remove( mWidget );
 }
Member Function Documentation
void rcTextAreaSettingWidget::settingChanged (void) slot
Definition at line 65 of file rc_textareasettingwidget.cpp.
References rcSettingInfo::getValue(), rcSettingWidget::mSetting, mWidget, and rcSettingWidget::updateWidgetState().
Referenced by rcTextAreaSettingWidget().
 {
     string currentValue = mSetting.getValue();
     mWidget->setText( currentValue.c_str() );
     // Update visibility/editability
     updateWidgetState();
 }
void rcTextAreaSettingWidget::valueChanged (const QString & text) slot
Definition at line 55 of file rc_textareasettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcTextAreaSettingWidget().
 {
     mSetting.setValue( text.latin1() );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
rcTextEdit* rcTextAreaSettingWidget::mWidget private
Definition at line 24 of file rc_textareasettingwidget.h.
Referenced by rcTextAreaSettingWidget(), settingChanged(), and ~rcTextAreaSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_textareasettingwidget.h
src/visible/qt/rc_textareasettingwidget.cpp