Visible: rcRectSettingWidget Class Reference
rcRectSettingWidget Class Reference
#include <include/visUI/rc_rectsettingwidget.h>
Public Slots
void valueChanged (void)
void settingChanged (void)
void settingChanged (const rcRect &)
void selectAll ()
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcRectSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcRectSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Member Functions
void setMaxValues ()
Private Attributes
QSpinBox * _xWidget
QSpinBox * _yWidget
QSpinBox * _wWidget
QSpinBox * _hWidget
QPushButton * _selectWidget
bool _ignoreValueChanged
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 10 of file rc_rectsettingwidget.h.
Constructor & Destructor Documentation
rcRectSettingWidget::rcRectSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 28 of file rc_rectsettingwidget.cpp.
References _hWidget, _ignoreValueChanged, _selectWidget, _wWidget, _xWidget, _yWidget, cSpinboxWidth, rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcSettingInfo::getDescription(), rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcSettingWidget::mTopLayout, selectAll(), settingChanged(), and valueChanged().
     : rcSettingWidget( parent, setting )
 {
     _ignoreValueChanged = false;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     int maxX = domain->getExperimentAttributes().frameWidth;
     int maxY = domain->getExperimentAttributes().frameHeight;
     QGridLayout *grid = new QGridLayout (mTopLayout, 3, 2);
     _xWidget = new QSpinBox( 0 , maxX , 1 , this , "x" );
     _xWidget->setPrefix( "x:" );
     _xWidget->setFixedWidth( cSpinboxWidth );
     grid->addWidget( _xWidget, 0, 1);
     _yWidget = new QSpinBox( 0 , maxY , 1 , this , "y" );
     _yWidget->setPrefix( "y:" );
     _yWidget->setFixedWidth( cSpinboxWidth );
     grid->addWidget( _yWidget, 0, 2);
     _wWidget = new QSpinBox( 0 , maxX , 1 , this , "w" );
     _wWidget->setPrefix( "w:" );
     _wWidget->setFixedWidth( cSpinboxWidth );
     grid->addWidget( _wWidget, 1, 1);
     _hWidget = new QSpinBox( 0 , maxY , 1 , this , "h" );
     _hWidget->setPrefix( "h:" );
     _hWidget->setFixedWidth( cSpinboxWidth );
     grid->addWidget( _hWidget, 1, 2);
     mTopLayout->addSpacing( 5 );
     _selectWidget = new QPushButton( "Entire" , this );
     //    _selectWidget->setFixedWidth( 40 );
     QToolTip::add( _selectWidget , "Click to select whole input frame for analysis" );
     grid->addWidget( _selectWidget , 0, 0);
     // use the setting description as a tool tip
     QToolTip::add( this , setting.getDescription() );
     // update the text widget with the current value of the setting.
     settingChanged();
     // route all spinbox's valueChanged signal to our single
     //  'valueChanged' slot
     connect( _xWidget , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( void ) ) );
     connect( _yWidget , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( void ) ) );
     connect( _wWidget , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( void ) ) );
     connect( _hWidget , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( void ) ) );
     // connect the "select all" button 'clicked' signal to our
     //  'selectAll' slot so we can start a file dialog.
     connect( _selectWidget , SIGNAL( clicked( void ) )  ,
              this , SLOT( selectAll( void ) ) );
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     // connect this widget to focus rect update signal
     connect( domain , SIGNAL( updateAnalysisRect( const rcRect& ) ) ,
              this   , SLOT( settingChanged( const rcRect& ) ) );
 }
rcRectSettingWidget::~rcRectSettingWidget ()
Definition at line 98 of file rc_rectsettingwidget.cpp.
References _selectWidget.
 {
     QToolTip::remove( this );
     QToolTip::remove( _selectWidget );
 }
Member Function Documentation
void rcRectSettingWidget::selectAll () slot
Definition at line 170 of file rc_rectsettingwidget.cpp.
References rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcModelDomain::notifyAnalysisRect(), and settingChanged().
Referenced by rcRectSettingWidget().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     uint32 maxX = domain->getExperimentAttributes().frameWidth;
     uint32 maxY = domain->getExperimentAttributes().frameHeight;
     rcRect wholeImage( 0, 0, maxX, maxY );
     settingChanged( wholeImage );
     // notify widgets who want to draw this rect
     rcModelDomain::getModelDomain()->notifyAnalysisRect( wholeImage );
 }
void rcRectSettingWidget::setMaxValues () private
Definition at line 186 of file rc_rectsettingwidget.cpp.
References _hWidget, _wWidget, _xWidget, _yWidget, rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcModelDomain::getExperimentAttributes(), and rcModelDomain::getModelDomain().
Referenced by settingChanged(), and valueChanged().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     uint32 maxX = domain->getExperimentAttributes().frameWidth;
     uint32 maxY = domain->getExperimentAttributes().frameHeight;
     _xWidget->setMaxValue( maxX );
     _yWidget->setMaxValue( maxY );
     _wWidget->setMaxValue( maxX );
     _hWidget->setMaxValue( maxY );
 }
void rcRectSettingWidget::settingChanged (void) slot
Definition at line 140 of file rc_rectsettingwidget.cpp.
References _hWidget, _ignoreValueChanged, _wWidget, _xWidget, _yWidget, rcSettingInfo::getValue(), rcRectangle< T >::height(), rcSettingWidget::mSetting, setMaxValues(), rcSettingWidget::updateWidgetState(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
Referenced by rcRectSettingWidget(), and selectAll().
 {
     setMaxValues();
     rcRect currentValue = mSetting.getValue();
     // Temporarily disable valueChanged updates to avoid
     // getting old setting values by accident
     _ignoreValueChanged = true;
     _xWidget->setValue( currentValue.x() );
     _yWidget->setValue( currentValue.y() );
     _wWidget->setValue( currentValue.width() );
     _hWidget->setValue( currentValue.height() );
     _ignoreValueChanged = false;
     // Update visibility/editability
     updateWidgetState();
 }
void rcRectSettingWidget::settingChanged (const rcRect & currentValue) slot
Definition at line 160 of file rc_rectsettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), setMaxValues(), and rcSettingInfo::setValue().
 {
     setMaxValues();
     mSetting.setValue( currentValue );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
void rcRectSettingWidget::valueChanged (void) slot
Definition at line 108 of file rc_rectsettingwidget.cpp.
References _hWidget, _ignoreValueChanged, _wWidget, _xWidget, _yWidget, rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcRectangle< T >::height(), rcSettingWidget::mSetting, rcModelDomain::notifyAnalysisRect(), rcModelDomain::notifySettingChange(), rcRect::setHeight(), setMaxValues(), rcSettingInfo::setValue(), rcRect::setWidth(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
Referenced by rcRectSettingWidget().
 {
     if ( _ignoreValueChanged )
         return;
     setMaxValues();
     // set the new value from the state of the spin boxes
     int x = _xWidget->value();
     int y = _yWidget->value();
     int w = _wWidget->value();
     int h = _hWidget->value();
     rcRect newRect( x , y , w , h );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     int32 maxX = domain->getExperimentAttributes().frameWidth;
     int32 maxY = domain->getExperimentAttributes().frameHeight;
     // Throttle values
     if ( newRect.x() + newRect.width() > maxX )
         newRect.setWidth( maxX - newRect.x() );
     if ( newRect.y() + newRect.height() > maxY )
         newRect.setHeight( maxY - newRect.y() );
     mSetting.setValue( newRect );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
     // notify widgets who want to draw this rect
     rcModelDomain::getModelDomain()->notifyAnalysisRect( newRect );
 }
Member Data Documentation
QSpinBox* rcRectSettingWidget::_hWidget private
Definition at line 32 of file rc_rectsettingwidget.h.
Referenced by rcRectSettingWidget(), setMaxValues(), settingChanged(), and valueChanged().
bool rcRectSettingWidget::_ignoreValueChanged private
Definition at line 34 of file rc_rectsettingwidget.h.
Referenced by rcRectSettingWidget(), settingChanged(), and valueChanged().
QPushButton* rcRectSettingWidget::_selectWidget private
Definition at line 33 of file rc_rectsettingwidget.h.
Referenced by rcRectSettingWidget(), and ~rcRectSettingWidget().
QSpinBox* rcRectSettingWidget::_wWidget private
Definition at line 31 of file rc_rectsettingwidget.h.
Referenced by rcRectSettingWidget(), setMaxValues(), settingChanged(), and valueChanged().
QSpinBox* rcRectSettingWidget::_xWidget private
Definition at line 29 of file rc_rectsettingwidget.h.
Referenced by rcRectSettingWidget(), setMaxValues(), settingChanged(), and valueChanged().
QSpinBox* rcRectSettingWidget::_yWidget private
Definition at line 30 of file rc_rectsettingwidget.h.
Referenced by rcRectSettingWidget(), setMaxValues(), settingChanged(), and valueChanged().
The documentation for this class was generated from the following files:
include/visUI/rc_rectsettingwidget.h
src/visible/qt/rc_rectsettingwidget.cpp