Visible: rcFrameGrabber Class Reference
rcFrameGrabber Class Reference abstract
#include <include/visual/rc_framegrabber.h>
Public Member Functions
virtual ~rcFrameGrabber ()
virtual bool isValid () const =0
virtual rcFrameGrabberError getLastError () const =0
virtual bool start ()=0
virtual bool stop ()=0
virtual int32 frameCount ()=0
virtual int32 cacheSize ()=0
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)=0
virtual const std::string getInputSourceName ()=0
Static Public Member Functions
static std::string getErrorString (rcFrameGrabberError error)
Detailed Description
Definition at line 56 of file rc_framegrabber.h.
Constructor & Destructor Documentation
rcFrameGrabber::~rcFrameGrabber () virtual
Definition at line 67 of file rc_framegrabber.cpp.
 {
 }
Member Function Documentation
virtual int32 rcFrameGrabber::cacheSize () pure virtual
Implemented in rcVectorGrabber, rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, rcReifyMovieGrabber, and rcCameraGrabber.
Referenced by rcAnalyzer::rcAnalyzer().
virtual int32 rcFrameGrabber::frameCount () pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, rcFileGrabber, and rcReifyMovieGrabber.
Referenced by rcMovieConverterToRfy::createRfyMovie(), and rcEngineImpl::loadFrames().
std::string rcFrameGrabber::getErrorString (rcFrameGrabberError error) static
Definition at line 12 of file rc_framegrabber.cpp.
References eFrameErrorCameraCapture, eFrameErrorCameraInit, eFrameErrorFileClose, eFrameErrorFileFormat, eFrameErrorFileInit, eFrameErrorFileRead, eFrameErrorFileRevUnsupported, eFrameErrorFileUnsupported, eFrameErrorFrameNotAvailable, eFrameErrorInit, eFrameErrorInternal, eFrameErrorInvalidOptions, eFrameErrorIPC, eFrameErrorNotImplemented, eFrameErrorOK, eFrameErrorOutOfMemory, eFrameErrorQuicktimeInit, eFrameErrorQuicktimeRead, eFrameErrorSystemResources, eFrameErrorUnknown, eFrameErrorUnsupportedDepth, and eFrameErrorUnsupportedFormat.
Referenced by rcEngineMovieCapture::createGrabber(), rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::entropyTrackerWindow(), rcEngineMovieCapture::getCameraState(), rcEngineMovieCapture::initializeCamera(), rcEngineImpl::loadImages(), rcEngineImpl::loadMovie(), rcEngineImpl::reportOnBadGrabber(), rfCountMovieFrames(), rcEngineMovieCapture::run(), rcEngineMovieCapture::sendShutdown(), and rcEngineMovieCapture::updateCameraSettings().
 {
     switch ( error ) {
         case eFrameErrorOK:
             return std::string( "Frame grabber: OK" );
         case eFrameErrorUnknown:
             return std::string( "Frame grabber: unknown error" );
         case eFrameErrorInit:
             return std::string( "Frame grabber: unknown initialization error" );
         case eFrameErrorFileInit:
             return std::string( "Frame grabber: file not found" );
         case eFrameErrorFileClose:
             return std::string( "Frame grabber: file close failed" );
         case eFrameErrorFileFormat:
             return std::string( "Frame grabber: file is corrupted" );
         case eFrameErrorFileUnsupported:
             return std::string( "Frame grabber: unsupported file format" );
         case eFrameErrorFileRevUnsupported:
             return std::string( "Frame grabber: unsupported file revision" );
         case eFrameErrorFileRead:
             return std::string( "Frame grabber: file read failed" );
         case eFrameErrorSystemResources:
             return std::string("Frame grabber: inadequate system resources");
         case eFrameErrorIPC:
             return std::string("Frame grabber: error communicating with peer process");
         case eFrameErrorCameraInit:
             return std::string( "Frame grabber: camera initialization failed" );
         case eFrameErrorCameraCapture:
             return std::string( "Frame grabber: camera capture failed" );
         case eFrameErrorQuicktimeInit:
             return std::string( "Frame grabber: QuickTime initialization failed" );
         case eFrameErrorQuicktimeRead:
             return std::string( "Frame grabber: QuickTime read failed" );
         case eFrameErrorUnsupportedDepth:
             return std::string( "Frame grabber: got an image with unsupported depth" );
         case eFrameErrorUnsupportedFormat:
             return std::string( "Frame grabber: got an image with unsupported format" );
         case eFrameErrorNotImplemented:
             return std::string( "Frame grabber: feature not implemented yet" );
         case eFrameErrorFrameNotAvailable:
             return std::string( "Frame grabber: frame not available" );
         case eFrameErrorInternal:
             return std::string( "Frame grabber: internal logic error" );
         case eFrameErrorOutOfMemory:
             return std::string( "Frame grabber: out of memory" );
         case eFrameErrorInvalidOptions:
             return std::string( "Frame grabber: invalid options specified" );
             // Note: no default case to force a compiler warning if a new enum value
             // is defined without adding a corresponding string here.
     }
     return std::string(" Frame grabber: undefined error" );
 }
virtual const std::string rcFrameGrabber::getInputSourceName () pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, rcMPEG2Grabber, rcMovieGrabber, rcImageGrabber, and rcReifyMovieGrabber.
Referenced by rcEngineMovieCapture::createGrabber().
virtual rcFrameGrabberError rcFrameGrabber::getLastError () const pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, and rcFileGrabber.
Referenced by rcEngineMovieCapture::createGrabber(), rcMovieConverterToRfy::createRfyMovie(), rcEngineMovieCapture::getCameraState(), rcAnalyzer::getNextResult(), rcEngineMovieCapture::initializeCamera(), rcEngineImpl::loadFrames(), rcAnalyzer::rcAnalyzer(), rcEngineMovieCapture::run(), rcEngineMovieCapture::sendShutdown(), rcAnalyzer::start(), rcAnalyzer::stop(), and rcEngineMovieCapture::updateCameraSettings().
virtual rcFrameGrabberStatus rcFrameGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, rcFileGrabber, and rcReifyMovieGrabber.
Referenced by rcMovieConverterToRfy::createRfyMovie(), rcAnalyzer::getNextResult(), and rcEngineImpl::loadFrames().
virtual bool rcFrameGrabber::isValid () const pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, and rcFileGrabber.
Referenced by rcEngineMovieCapture::createGrabber(), rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::loadFrames(), and rcAnalyzer::rcAnalyzer().
virtual bool rcFrameGrabber::start () pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, rcFileGrabber, and rcReifyMovieGrabber.
Referenced by rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::loadFrames(), and rcAnalyzer::start().
virtual bool rcFrameGrabber::stop () pure virtual
Implemented in rcVectorGrabber, rcQVideoGrabber, rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, rcFileGrabber, and rcReifyMovieGrabber.
Referenced by rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::loadFrames(), and rcAnalyzer::stop().
The documentation for this class was generated from the following files:
include/visual/rc_framegrabber.h
src/visual/code/rc_framegrabber.cpp