Visible: rcFileGrabber Class Reference
rcFileGrabber Class Reference abstract
#include <include/visual/rc_filegrabber.h>
Public Member Functions
rcFileGrabber (rcCarbonLock *lock)
virtual ~rcFileGrabber ()
virtual rcFrameGrabberError getLastError () const
virtual bool isValid () const
virtual bool start ()=0
virtual bool stop ()=0
virtual int32 frameCount ()=0
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)=0
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
virtual int32 cacheSize ()=0
virtual const std::string getInputSourceName ()=0
Protected Member Functions
void setLastError (rcFrameGrabberError)
void lock ()
void unlock ()
Private Attributes
rcFrameGrabberError mLastError
rcCarbonLock * mCarbonLock
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Detailed Description
Definition at line 20 of file rc_filegrabber.h.
Constructor & Destructor Documentation
rcFileGrabber::rcFileGrabber (rcCarbonLock * lock)
Definition at line 18 of file rc_filegrabber.cpp.
                                                  :
         mLastError( eFrameErrorOK ),
         mCarbonLock( lock )
 {
}
rcFileGrabber::~rcFileGrabber () virtual
Definition at line 25 of file rc_filegrabber.cpp.
 {
 }
Member Function Documentation
virtual int32 rcFileGrabber::frameCount () pure virtual
Implements rcFrameGrabber.
Implemented in rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, and rcReifyMovieGrabber.
rcFrameGrabberError rcFileGrabber::getLastError () const virtual
Implements rcFrameGrabber.
Definition at line 30 of file rc_filegrabber.cpp.
References mLastError.
Referenced by isValid(), rfCountMovieFrames(), rcImageGrabber::start(), rcMPEG2Grabber::start(), and rcMovieGrabber::start().
 {
     return mLastError;
 }
virtual rcFrameGrabberStatus rcFileGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) pure virtual
Implements rcFrameGrabber.
Implemented in rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, and rcReifyMovieGrabber.
bool rcFileGrabber::isValid () const virtual
Implements rcFrameGrabber.
Definition at line 36 of file rc_filegrabber.cpp.
References eFrameErrorOK, and getLastError().
Referenced by rcReifyMovieGrabber::getNextFrame(), rfCompareMovies(), rfCountMovieFrames(), rcReifyMovieGrabber::start(), and rcReifyMovieGrabber::stop().
 {
     if ( getLastError() == eFrameErrorOK )
         return true;
     else
         return false;
 }
void rcFileGrabber::lock () protected
Definition at line 53 of file rc_filegrabber.cpp.
References rcCarbonLock::lock(), and mCarbonLock.
Referenced by rcImageGrabber::getNextFrame(), rcMovieGrabber::getNextFrame(), rcMPEG2Grabber::getReifyMovie(), rcImageGrabber::rcImageGrabber(), rcMovieGrabber::rcMovieGrabber(), rcMPEG2Grabber::rcMPEG2Grabber(), rcMPEG2Grabber::start(), rcMovieGrabber::start(), rcImageGrabber::stop(), rcMPEG2Grabber::stop(), and rcMovieGrabber::stop().
 {
     if ( mCarbonLock )
         mCarbonLock->lock();
 }
void rcFileGrabber::setLastError (rcFrameGrabberError error) protected
Definition at line 47 of file rc_filegrabber.cpp.
References mLastError.
Referenced by rcReifyMovieGrabber::getNextFrame(), rcImageGrabber::getNextFrame(), rcMovieGrabber::getNextFrame(), rcMPEG2Grabber::getReifyMovie(), rcImageGrabber::rcImageGrabber(), rcMovieGrabber::rcMovieGrabber(), rcMPEG2Grabber::rcMPEG2Grabber(), rcReifyMovieGrabber::rcReifyMovieGrabber(), rcMPEG2Grabber::start(), and rcMovieGrabber::start().
 {
     mLastError = error;
 }
virtual bool rcFileGrabber::start () pure virtual
Implements rcFrameGrabber.
Implemented in rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, and rcReifyMovieGrabber.
virtual bool rcFileGrabber::stop () pure virtual
Implements rcFrameGrabber.
Implemented in rcMovieGrabber, rcMPEG2Grabber, rcImageGrabber, and rcReifyMovieGrabber.
void rcFileGrabber::unlock () protected
Definition at line 60 of file rc_filegrabber.cpp.
References mCarbonLock, and rcCarbonLock::unlock().
Referenced by rcImageGrabber::getNextFrame(), rcMovieGrabber::getNextFrame(), rcMPEG2Grabber::getReifyMovie(), rcImageGrabber::rcImageGrabber(), rcMovieGrabber::rcMovieGrabber(), rcMPEG2Grabber::rcMPEG2Grabber(), rcMPEG2Grabber::start(), rcMovieGrabber::start(), rcImageGrabber::stop(), rcMPEG2Grabber::stop(), and rcMovieGrabber::stop().
 {
     if ( mCarbonLock )
         mCarbonLock->unlock();
 }
Member Data Documentation
rcCarbonLock* rcFileGrabber::mCarbonLock private
Definition at line 59 of file rc_filegrabber.h.
Referenced by lock(), and unlock().
rcFrameGrabberError rcFileGrabber::mLastError private
Definition at line 58 of file rc_filegrabber.h.
Referenced by getLastError(), and setLastError().
The documentation for this class was generated from the following files:
include/visual/rc_filegrabber.h
src/visual/code/rc_filegrabber.cpp