Visible: rcRowFuncOneSourceOneDestination< T > Class Template Reference
rcRowFuncOneSourceOneDestination< T > Class Template Reference abstract
#include <include/analysis/rc_rowfunc.h>
Public Member Functions
rcRowFuncOneSourceOneDestination ()
virtual ~rcRowFuncOneSourceOneDestination ()
virtual void prolog ()=0
virtual void rowFunc ()=0
virtual void areaFunc ()=0
Protected Member Functions
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
Static Protected Member Functions
static bool checkAssigned (const rcWindow &, const rcWindow &)
Protected Attributes
const T * mFirst
T * mSecond
uint32 mWidth
uint32 mHeight
Detailed Description
template<class T>
class rcRowFuncOneSourceOneDestination< T >
Definition at line 77 of file rc_rowfunc.h.
Constructor & Destructor Documentation
template<class T> rcRowFuncOneSourceOneDestination< T >::rcRowFuncOneSourceOneDestination () inline
Definition at line 81 of file rc_rowfunc.h.
 {}
template<class T> virtual rcRowFuncOneSourceOneDestination< T >::~rcRowFuncOneSourceOneDestination () inline virtual
Definition at line 82 of file rc_rowfunc.h.
 {}
Member Function Documentation
template<class T> virtual void rcRowFuncOneSourceOneDestination< T >::areaFunc () pure virtual
Implemented in rcBasicPixelMap< T >.
template<class T> static bool rcRowFuncOneSourceOneDestination< T >::checkAssigned (const rcWindow & , const rcWindow &) static protected
template<> bool rcRowFuncOneSourceOneDestination< uint8 >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 90 of file rc_rowfuncs.cpp.
References rcWindow::depth(), and rcPixel8.
 {
   return (srcA.depth() == rcPixel8 && srcB.depth() == rcPixel8);
 }
template<> bool rcRowFuncOneSourceOneDestination< uint16 >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 95 of file rc_rowfuncs.cpp.
References rcWindow::depth(), rcPixel16, and rcPixel8.
 {
   return (srcA.depth() == rcPixel8 && srcB.depth() == rcPixel16);
 }
template<> bool rcRowFuncOneSourceOneDestination< uint32 >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 100 of file rc_rowfuncs.cpp.
References rcWindow::depth(), rcPixel32, and rcPixel8.
 {
   return (srcA.depth() == rcPixel8 && srcB.depth() == rcPixel32);
 }
template<> bool rcRowFuncOneSourceOneDestination< double >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 105 of file rc_rowfuncs.cpp.
References rcWindow::depth(), and rcPixelDouble.
 {
   return (srcA.depth() == rcPixelDouble && srcB.depth() == rcPixelDouble);
 }
template<class T> virtual void rcRowFuncOneSourceOneDestination< T >::prolog () pure virtual
Implemented in rcBasicPixelMap< T >.
template<class T> virtual void rcRowFuncOneSourceOneDestination< T >::rowFunc () pure virtual
Implemented in rcBasicPixelMap< T >, rcBasicPixelMap< T >, and rcBasicPixelMap< T >.
Member Data Documentation
template<class T> const T* rcRowFuncOneSourceOneDestination< T >::mFirst protected
Definition at line 90 of file rc_rowfunc.h.
template<class T> uint32 rcRowFuncOneSourceOneDestination< T >::mHeight protected
Definition at line 93 of file rc_rowfunc.h.
template<class T> T* rcRowFuncOneSourceOneDestination< T >::mSecond protected
Definition at line 91 of file rc_rowfunc.h.
template<class T> uint32 rcRowFuncOneSourceOneDestination< T >::mWidth protected
Definition at line 92 of file rc_rowfunc.h.
The documentation for this class was generated from the following file:
include/analysis/rc_rowfunc.h