Visible: rcVideoSegmentIteratorImpl Class Reference
rcVideoSegmentIteratorImpl Class Reference
Public Member Functions
rcVideoSegmentIteratorImpl (rcVideoTrackImpl *track, const rcTimestamp &position, rcMutex &mutex)
virtual ~rcVideoSegmentIteratorImpl ()
virtual rcTimestamp getSegmentLength (void)
virtual rcTimestamp getSegmentOffset (void)
virtual rcTimestamp getTrackOffset (void)
virtual int32 getSegmentIndex (void)
virtual rcTimestamp getSegmentStart (void)
virtual rcTimestamp getSegmentStartAbsolute (void)
virtual bool hasNextSegment (bool lock)
virtual uint32 getSegmentCount (void)
virtual bool contains (const rcTimestamp &time)
virtual void lock ()
virtual void unlock ()
virtual void reset (bool lock)
virtual void release (void)
virtual rcRect getFocus (void)
virtual void advance (const rcTimestamp &amount, bool lock)
virtual rcWindow getValue (void)
virtual bool advance (int32 count, bool lock)
Public Member Functions inherited from rcVideoSegmentIterator
virtual ~rcVideoSegmentIterator ()
Public Member Functions inherited from rcSegmentIterator
virtual ~rcSegmentIterator ()
Private Member Functions
virtual void setCurrentValue (void)
Private Attributes
rcSegmentIteratorImpl _iter
rcVideoTrackImpl * _track
rcWindow _currentValue
Detailed Description
Definition at line 11 of file rc_videotrackimpl.cpp.
Constructor & Destructor Documentation
rcVideoSegmentIteratorImpl::rcVideoSegmentIteratorImpl (rcVideoTrackImpl * track, const rcTimestamp & position, rcMutex & mutex) inline
Definition at line 14 of file rc_videotrackimpl.cpp.
References _iter, lock(), rcSegmentIteratorImpl::mutex(), rmAssert, and setCurrentValue().
                                                  : _iter( track, position, mutex ),
                                                    _track( track ),
                                                    _currentValue()
         {
             rcLock lock( _iter.mutex() );
             rmAssert( track );
             setCurrentValue();
         }
virtual rcVideoSegmentIteratorImpl::~rcVideoSegmentIteratorImpl () inline virtual
Definition at line 25 of file rc_videotrackimpl.cpp.
 { };
Member Function Documentation
virtual void rcVideoSegmentIteratorImpl::advance (const rcTimestamp & amount, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 119 of file rc_videotrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             } else {
                 _iter.advanceNoLock( amount );
                 setCurrentValue();
             }
         }
virtual bool rcVideoSegmentIteratorImpl::advance (int32 count, bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 140 of file rc_videotrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::advanceNoLock(), lock(), rcSegmentIteratorImpl::mutex(), and setCurrentValue().
         {
             if ( lock ) {
                 rcLock lock( _iter.mutex() );
                 bool result = _iter.advanceNoLock( count );
                 setCurrentValue();
                 return result;
             } else {
                 bool result = _iter.advanceNoLock( count );
                 setCurrentValue();
                 return result;
             }
         }
virtual bool rcVideoSegmentIteratorImpl::contains (const rcTimestamp & time) inline virtual
Implements rcSegmentIterator.
Definition at line 78 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::contains().
         {
             return _iter.contains( time );
         }
virtual rcRect rcVideoSegmentIteratorImpl::getFocus (void) inline virtual
Implements rcSegmentIterator.
Definition at line 113 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getFocus().
         {
             return _iter.getFocus();
         }
virtual uint32 rcVideoSegmentIteratorImpl::getSegmentCount (void) inline virtual
Implements rcSegmentIterator.
Definition at line 72 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentCount().
         {
             return _iter.getSegmentCount();
         }
virtual int32 rcVideoSegmentIteratorImpl::getSegmentIndex (void) inline virtual
Implements rcSegmentIterator.
Definition at line 48 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentIndex().
         {
             return _iter.getSegmentIndex();
         }
virtual rcTimestamp rcVideoSegmentIteratorImpl::getSegmentLength (void) inline virtual
Implements rcSegmentIterator.
Definition at line 30 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentLength().
         {
             return _iter.getSegmentLength();
         }
virtual rcTimestamp rcVideoSegmentIteratorImpl::getSegmentOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 36 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentOffset().
         {
             return _iter.getSegmentOffset();
         }
virtual rcTimestamp rcVideoSegmentIteratorImpl::getSegmentStart (void) inline virtual
Implements rcSegmentIterator.
Definition at line 54 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStart().
         {
             return _iter.getSegmentStart();
         }
virtual rcTimestamp rcVideoSegmentIteratorImpl::getSegmentStartAbsolute (void) inline virtual
Implements rcSegmentIterator.
Definition at line 60 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getSegmentStartAbsolute().
         {
             return _iter.getSegmentStartAbsolute();
         }
virtual rcTimestamp rcVideoSegmentIteratorImpl::getTrackOffset (void) inline virtual
Implements rcSegmentIterator.
Definition at line 42 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::getTrackOffset().
         {
             return _iter.getTrackOffset();
         }
virtual rcWindow rcVideoSegmentIteratorImpl::getValue (void) inline virtual
Implements rcVideoSegmentIterator.
Definition at line 133 of file rc_videotrackimpl.cpp.
References _currentValue.
         {
             return _currentValue;
         }
virtual bool rcVideoSegmentIteratorImpl::hasNextSegment (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 66 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::hasNextSegment().
         {
             return _iter.hasNextSegment( lock );
         }
virtual void rcVideoSegmentIteratorImpl::lock () inline virtual
Implements rcSegmentIterator.
Definition at line 84 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::lock().
Referenced by advance(), and rcVideoSegmentIteratorImpl().
         {
             _iter.lock();
         }
virtual void rcVideoSegmentIteratorImpl::release (void) inline virtual
Implements rcSegmentIterator.
Definition at line 107 of file rc_videotrackimpl.cpp.
         {
             delete this;
         }
virtual void rcVideoSegmentIteratorImpl::reset (bool lock) inline virtual
Implements rcSegmentIterator.
Definition at line 96 of file rc_videotrackimpl.cpp.
References _iter, rcSegmentIteratorImpl::lock(), rcSegmentIteratorImpl::reset(), setCurrentValue(), and rcSegmentIteratorImpl::unlock().
         {
             if ( lock )
                 _iter.lock();
             _iter.reset( false );
             setCurrentValue();
             if ( lock )
                 _iter.unlock();
         }
virtual void rcVideoSegmentIteratorImpl::setCurrentValue (void) inline private virtual
Definition at line 156 of file rc_videotrackimpl.cpp.
References _currentValue, _iter, rcVideoTrackImpl::_segments, _track, rcSegmentIteratorImpl::getSegmentIndex(), and rcVideoTrackImpl::segments().
Referenced by advance(), rcVideoSegmentIteratorImpl(), and reset().
         {
             int32 index = _iter.getSegmentIndex();
             if ( index >= 0 && static_cast<uint32>(index) < _track->segments() )
                 _currentValue = _track->_segments[index].mValue;
             else
                 _currentValue = rcWindow();
         }
virtual void rcVideoSegmentIteratorImpl::unlock () inline virtual
Implements rcSegmentIterator.
Definition at line 90 of file rc_videotrackimpl.cpp.
References _iter, and rcSegmentIteratorImpl::unlock().
         {
             _iter.unlock();
         }
Member Data Documentation
rcWindow rcVideoSegmentIteratorImpl::_currentValue private
Definition at line 167 of file rc_videotrackimpl.cpp.
Referenced by getValue(), and setCurrentValue().
rcSegmentIteratorImpl rcVideoSegmentIteratorImpl::_iter private
Definition at line 165 of file rc_videotrackimpl.cpp.
Referenced by advance(), contains(), getFocus(), getSegmentCount(), getSegmentIndex(), getSegmentLength(), getSegmentOffset(), getSegmentStart(), getSegmentStartAbsolute(), getTrackOffset(), hasNextSegment(), lock(), rcVideoSegmentIteratorImpl(), reset(), setCurrentValue(), and unlock().
rcVideoTrackImpl* rcVideoSegmentIteratorImpl::_track private
Definition at line 166 of file rc_videotrackimpl.cpp.
Referenced by setCurrentValue().
The documentation for this class was generated from the following file:
src/visible/src/rc_videotrackimpl.cpp