Visible: rc2Xform Class Reference
rc2Xform Class Reference
#include <include/util/rc_xforms.h>
Public Member Functions
rc2Xform ()
rc2Xform (const rcMatrix_2d &c, const rc2Dvector &t)
rc2Xform (const rcMatrix_2d &c, const rc2Fvector &t)
const rcMatrix_2d & matrix () const
const rc2Dvector & trans () const
const rc2Fvector transf () const
void matrix (const rcMatrix_2d &c)
void trans (const rc2Dvector &t)
void trans (const rc2Fvector &t)
rc2Xform inverse () const
rc2Xform operator* (const rc2Xform &xform) const
rc2Xform compose (const rc2Xform &xform) const
double xRot () const
double yRot () const
double xScale () const
double yScale () const
double scale () const
double aspect () const
double shear () const
rcRadian rotation () const
double mapAngle (const double &ang) const
double invMapAngle (const double &ang) const
rc2Dvector mapPoint (const rc2Dvector &pt) const
rc2Fvector mapPoint (const rc2Fvector &pt) const
rc2Dvector operator* (const rc2Dvector &pt) const
rc2Fvector operator* (const rc2Fvector &pt) const
rc2Dvector invMapPoint (const rc2Dvector &pt) const
rc2Fvector invMapPoint (const rc2Fvector &pt) const
rc2Dvector mapVector (const rc2Dvector &vect) const
rc2Dvector invMapVector (const rc2Dvector &vect) const
double mapArea (double area) const
double invMapArea (double area) const
bool operator== (const rc2Xform &xform) const
bool operator!= (const rc2Xform &xform) const
bool operator< (const rc2Xform &) const
bool isIdentity () const
bool isSingular () const
Static Public Attributes
static const rc2Xform I
Private Attributes
rc2Dvector mT
rcMatrix_2d mC
Friends
ostream & operator<< (ostream &ous, const rc2Xform &xform)
Detailed Description
Definition at line 153 of file rc_xforms.h.
Constructor & Destructor Documentation
rc2Xform::rc2Xform () inline
Definition at line 156 of file rc_xforms.h.
Referenced by inverse(), and operator*().
 : mT(rc2Dvector()), mC(rcMatrix_2d()) {}
rc2Xform::rc2Xform (const rcMatrix_2d & c, const rc2Dvector & t) inline
Definition at line 161 of file rc_xforms.h.
 : mT(t), mC(c) {}
rc2Xform::rc2Xform (const rcMatrix_2d & c, const rc2Fvector & t) inline
Definition at line 162 of file rc_xforms.h.
References trans().
 : mC(c) { trans (t); }
Member Function Documentation
double rc2Xform::aspect () const inline
Definition at line 203 of file rc_xforms.h.
References rcMatrix_2d::aspect(), and mC.
 {return mC.aspect();}
rc2Xform rc2Xform::compose (const rc2Xform & xform) const inline
Definition at line 187 of file rc_xforms.h.
 {return *this * xform;}
rc2Xform rc2Xform::inverse () const inline
Definition at line 175 of file rc_xforms.h.
References rcMatrix_2d::inverse(), mC, mT, and rc2Xform().
Referenced by invMapPoint(), and rcVisualFunction::vXform().
   {
     rcMatrix_2d ic = mC.inverse();
     return rc2Xform(ic, ic * -mT);
   }
double rc2Xform::invMapAngle (const double & ang) const
double rc2Xform::invMapArea (double area) const inline
Definition at line 284 of file rc_xforms.h.
References rcMatrix_2d::determinant(), isSingular(), mC, and rmABS.
   {
     if (isSingular())
       throw (general_exception ("Singular"));
     return (area / (rmABS (mC.determinant())));
   }
rc2Dvector rc2Xform::invMapPoint (const rc2Dvector & pt) const inline
Definition at line 245 of file rc_xforms.h.
References inverse().
Referenced by rcAffineRectangle::imageToAffine(), rcBaseMotionPath::move(), and rcLsFit< T >::rms().
   { return (inverse() * pt); }
rc2Fvector rc2Xform::invMapPoint (const rc2Fvector & pt) const inline
Definition at line 247 of file rc_xforms.h.
References inverse(), rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     rc2Dvector tmp (pt.x(), pt.y());
     tmp = inverse() * tmp;
     return rc2Fvector ((float) tmp.x(), (float) tmp.y());
   }
rc2Dvector rc2Xform::invMapVector (const rc2Dvector & vect) const inline
Definition at line 267 of file rc_xforms.h.
References rcMatrix_2d::inverse(), and mC.
   { return (mC.inverse() * vect); }
bool rc2Xform::isIdentity () const inline
Definition at line 320 of file rc_xforms.h.
References rcMatrix_2d::isIdentity(), rc2dVector< T >::isNull(), mC, and mT.
Referenced by rcKinetoscope::clear().
 { return mT.isNull() && mC.isIdentity(); }
bool rc2Xform::isSingular () const inline
Definition at line 324 of file rc_xforms.h.
References rcMatrix_2d::isSingular(), and mC.
Referenced by invMapArea().
 {return mC.isSingular();}
double rc2Xform::mapAngle (const double & ang) const inline
Definition at line 212 of file rc_xforms.h.
References atan2(), cos(), mC, and sin().
   {
       rc2Dvector v( cos(ang),sin(ang) );
       v = mC * v;
       return ( atan2 (v.y(), v.x()) );
   }
double rc2Xform::mapArea (double area) const inline
Definition at line 280 of file rc_xforms.h.
References rcMatrix_2d::determinant(), mC, and rmABS.
   { return (area * rmABS (mC.determinant())); }
rc2Dvector rc2Xform::mapPoint (const rc2Dvector & pt) const inline
Definition at line 226 of file rc_xforms.h.
Referenced by rcAffineRectangle::affineToImage(), rcAffineRectangle::expand(), rcEngineImpl::modelTracker(), rcEngineImpl::postTrackingResults(), rcVisualFunction::rcVisualFunction(), rcVisualFunction::speed(), rcInfLine::transform(), rcPolygon::transform(), rcVisualFunction::update(), and rcKinetoscope::visualFunctionMap().
   { return *this * pt; }
rc2Fvector rc2Xform::mapPoint (const rc2Fvector & pt) const inline
Definition at line 228 of file rc_xforms.h.
   { return *this * pt; }
rc2Dvector rc2Xform::mapVector (const rc2Dvector & vect) const inline
Definition at line 262 of file rc_xforms.h.
References mC.
Referenced by rcInfLine::transform().
   { return (mC * vect); }
const rcMatrix_2d& rc2Xform::matrix () const inline
Definition at line 166 of file rc_xforms.h.
References mC.
Referenced by rcVisualFunction::distance(), rcDefGenerateImage::project(), rcAffineRectangle::rcAffineRectangle(), rcVisualFunction::rcVisualFunction(), rcVisualFunction::scale(), and rcLsFit< T >::solvetp().
 { return mC; }
void rc2Xform::matrix (const rcMatrix_2d & c) inline
Definition at line 171 of file rc_xforms.h.
References mC.
 { mC = c; }
bool rc2Xform::operator!= (const rc2Xform & xform) const inline
Definition at line 313 of file rc_xforms.h.
       { return !(*this == xform); }
rc2Xform rc2Xform::operator* (const rc2Xform & xform) const inline
Definition at line 185 of file rc_xforms.h.
References mC, mT, and rc2Xform().
   { return rc2Xform(mC * xform.mC, mC * xform.mT + mT); }
rc2Dvector rc2Xform::operator* (const rc2Dvector & pt) const inline
Definition at line 231 of file rc_xforms.h.
References mC, and mT.
   { return (mC * pt) + mT; }
rc2Fvector rc2Xform::operator* (const rc2Fvector & pt) const inline
Definition at line 233 of file rc_xforms.h.
References mC, mT, rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     rc2Dvector tmp (pt.x(), pt.y());
     tmp = (mC * tmp) + mT;
     return rc2Fvector ((float) tmp.x(), (float) tmp.y());
   }
bool rc2Xform::operator< (const rc2Xform &) const
bool rc2Xform::operator== (const rc2Xform & xform) const inline
Definition at line 310 of file rc_xforms.h.
References mC, and mT.
       { return ( (mC == xform.mC) && (mT == xform.mT) ); }
rcRadian rc2Xform::rotation () const inline
Definition at line 205 of file rc_xforms.h.
References mC, and rcMatrix_2d::rotation().
Referenced by rcAffineRectangle::angle().
 {return mC.rotation();}
double rc2Xform::scale () const inline
Definition at line 202 of file rc_xforms.h.
References mC, and rcMatrix_2d::scale().
Referenced by rcVisualFunction::dimensions(), rcVisualFunction::distance(), rcAffineRectangle::expand(), rcVisualFunction::perimeter(), and rcAffineRectangle::rcAffineRectangle().
 {return mC.scale();}
double rc2Xform::shear () const inline
Definition at line 204 of file rc_xforms.h.
References mC, and rcMatrix_2d::shear().
 {return mC.shear();}
const rc2Dvector& rc2Xform::trans () const inline
Definition at line 168 of file rc_xforms.h.
References mT.
Referenced by rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcVisualFunction::direct(), rcEngineImpl::modelTracker(), rcAffineRectangle::origin(), rc2Xform(), rcAffineRectangle::rcAffineRectangle(), rcVisualFunction::rcVisualFunction(), rcLsFit< T >::solvetp(), and rcVisualFunction::translation().
 { return mT; }
void rc2Xform::trans (const rc2Dvector & t) inline
Definition at line 172 of file rc_xforms.h.
References mT.
 { mT = t; }
void rc2Xform::trans (const rc2Fvector & t) inline
Definition at line 173 of file rc_xforms.h.
References mT, rc2dVector< T >::x(), and rc2dVector< T >::y().
 { mT.x((double) t.x());mT.y((double) t.y()); }
const rc2Fvector rc2Xform::transf () const inline
Definition at line 169 of file rc_xforms.h.
References mT, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcVisualFunction::measure(), and rcVisualFunction::update().
 { return rc2Fvector ((float) mT.x(), (float) mT.y()); }
double rc2Xform::xRot () const inline
Definition at line 192 of file rc_xforms.h.
References mC, and rcMatrix_2d::xRot().
 {return mC.xRot();}
double rc2Xform::xScale () const inline
Definition at line 194 of file rc_xforms.h.
References mC, and rcMatrix_2d::xScale().
Referenced by rcAffineRectangle::xyScale().
 {return mC.xScale();}
double rc2Xform::yRot () const inline
Definition at line 193 of file rc_xforms.h.
References mC, and rcMatrix_2d::yRot().
 {return mC.yRot();}
double rc2Xform::yScale () const inline
Definition at line 195 of file rc_xforms.h.
References mC, and rcMatrix_2d::yScale().
Referenced by rcAffineRectangle::xyScale().
 {return mC.yScale();}
Friends And Related Function Documentation
ostream& operator<< (ostream & ous, const rc2Xform & xform) friend
Definition at line 329 of file rc_xforms.h.
   {
     ous << xform.matrix() << "v" << xform.trans();
     return ous;
   }
Member Data Documentation
const rc2Xform rc2Xform::I static
Definition at line 318 of file rc_xforms.h.
rcMatrix_2d rc2Xform::mC private
Definition at line 337 of file rc_xforms.h.
Referenced by aspect(), inverse(), invMapArea(), invMapVector(), isIdentity(), isSingular(), mapAngle(), mapArea(), mapVector(), matrix(), operator*(), operator==(), rotation(), scale(), shear(), xRot(), xScale(), yRot(), and yScale().
rc2Dvector rc2Xform::mT private
Definition at line 336 of file rc_xforms.h.
Referenced by inverse(), isIdentity(), operator*(), operator==(), trans(), and transf().
The documentation for this class was generated from the following file:
include/util/rc_xforms.h