Visible: ibuff Class Reference
ibuff Class Reference abstract
#include <include/stlplus/textio.hpp>
Public Member Functions
ibuff (itext::newline_t newline=itext::convert_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_newline_mode (itext::newline_t newline)
itext::newline_t newline_mode (void) const
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual std::string error_string (void) const
virtual int peek (void)=0
virtual int get (void)=0
virtual ~ibuff (void)
Protected Attributes
itext::newline_t m_newline_mode
unsigned long m_bytes
unsigned m_line
unsigned m_column
int m_error_number
int m_aliases
Private Member Functions
ibuff & operator= (const ibuff &)
ibuff (const ibuff &)
Friends
class itext
Detailed Description
Definition at line 502 of file textio.hpp.
Constructor & Destructor Documentation
ibuff::ibuff (itext::newline_t newline = itext::convert_mode)
Definition at line 1240 of file textio.cpp.
                                     :
   m_newline_mode(newline),
   m_bytes(0),
   m_line(1),
   m_column(0),
   m_error_number(0),
   m_aliases(0)
 {
 }
ibuff::~ibuff (void) virtual
Definition at line 1250 of file textio.cpp.
 {
 }
ibuff::ibuff (const ibuff &) private
Member Function Documentation
unsigned long ibuff::bytes (void) const
Definition at line 1268 of file textio.cpp.
References m_bytes.
Referenced by itext::bytes().
 {
   return m_bytes;
 }
void ibuff::clear_error (void)
Definition at line 1298 of file textio.cpp.
References m_error_number.
Referenced by itext::clear_error().
 {
   m_error_number = 0;
 }
unsigned ibuff::column (void) const
Definition at line 1278 of file textio.cpp.
References m_column.
Referenced by itext::column().
 {
   return m_column;
 }
int ibuff::error_number (void) const
Definition at line 1303 of file textio.cpp.
References m_error_number.
Referenced by itext::error_number(), ifbuff::error_string(), and error_string().
 {
   return m_error_number;
 }
std::string ibuff::error_string (void) const virtual
Reimplemented in ifbuff.
Definition at line 1308 of file textio.cpp.
References error_number(), and textio_error_string().
Referenced by ifbuff::error_string(), and itext::error_string().
 {
   return textio_error_string(error_number());
 }
virtual int ibuff::get (void) pure virtual
Implemented in ifbuff, imbuff, iiobuff, isvbuff, and isbuff.
Referenced by itext::get().
void ibuff::increment (bool newline = false)
Definition at line 1254 of file textio.cpp.
References m_bytes, m_column, and m_line.
Referenced by itext::get().
 {
   m_bytes++;
   if (newline)
   {
     m_line++;
     m_column = 0;
   }
   else
   {
     m_column++;
   }
 }
unsigned ibuff::line (void) const
Definition at line 1273 of file textio.cpp.
References m_line.
Referenced by isvbuff::get(), itext::line(), and isvbuff::peek().
 {
   return m_line;
 }
itext::newline_t ibuff::newline_mode (void) const
Definition at line 1288 of file textio.cpp.
References m_newline_mode.
Referenced by itext::get(), itext::newline_mode(), and itext::peek().
 {
   return m_newline_mode;
 }
ibuff& ibuff::operator= (const ibuff &) private
virtual int ibuff::peek (void) pure virtual
Implemented in ifbuff, imbuff, iiobuff, isvbuff, and isbuff.
Referenced by itext::get(), and itext::peek().
void ibuff::set_error (int error)
Definition at line 1293 of file textio.cpp.
References TCP_client_data::error(), and m_error_number.
Referenced by iiobuff::get(), ifbuff::get(), ifbuff::open(), iiobuff::peek(), ifbuff::peek(), and itext::set_error().
 {
   if (!m_error_number) m_error_number = error;
 }
void ibuff::set_newline_mode (itext::newline_t newline)
Definition at line 1283 of file textio.cpp.
References m_newline_mode, and newline.
Referenced by itext::set_newline_mode().
 {
   m_newline_mode = newline;
 }
Friends And Related Function Documentation
friend class itext friend
Definition at line 550 of file textio.hpp.
Member Data Documentation
int ibuff::m_aliases protected
Definition at line 556 of file textio.hpp.
Referenced by itext::close(), and itext::open().
unsigned long ibuff::m_bytes protected
Definition at line 552 of file textio.hpp.
Referenced by bytes(), and increment().
unsigned ibuff::m_column protected
Definition at line 554 of file textio.hpp.
Referenced by column(), and increment().
int ibuff::m_error_number protected
Definition at line 555 of file textio.hpp.
Referenced by clear_error(), error_number(), and set_error().
unsigned ibuff::m_line protected
Definition at line 553 of file textio.hpp.
Referenced by increment(), and line().
itext::newline_t ibuff::m_newline_mode protected
Definition at line 551 of file textio.hpp.
Referenced by newline_mode(), and set_newline_mode().
The documentation for this class was generated from the following files:
include/stlplus/textio.hpp
include/stlplus/textio.cpp