Visible: rcMoviePlaybackStatusReader Class Reference
rcMoviePlaybackStatusReader Class Reference
#include <include/visiCore/rc_playbackregs.h>
Public Member Functions
rcMoviePlaybackStatusReader ()
virtual ~rcMoviePlaybackStatusReader ()
rcMoviePlaybackState getState () const
Protected Attributes
rcAtomicValue
< rcMoviePlaybackState > _playbackState
Detailed Description
Definition at line 58 of file rc_playbackregs.h.
Constructor & Destructor Documentation
rcMoviePlaybackStatusReader::rcMoviePlaybackStatusReader () inline
Definition at line 61 of file rc_playbackregs.h.
     : _playbackState(eMoviePlaybackState_Uninitialized)
   { }
virtual rcMoviePlaybackStatusReader::~rcMoviePlaybackStatusReader () inline virtual
Definition at line 65 of file rc_playbackregs.h.
   { }
Member Function Documentation
rcMoviePlaybackState rcMoviePlaybackStatusReader::getState (void) const inline
Definition at line 68 of file rc_playbackregs.h.
References _playbackState, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), rcEngineMoviePlayback::reset(), rcEngineMoviePlayback::run(), rcEngineImpl::setSettingValue(), and rcEngineMoviePlayback::setupTimeCtrlPlayback().
   { rcMoviePlaybackState x; return _playbackState.getValue(x); }
Member Data Documentation
rcAtomicValue<rcMoviePlaybackState> rcMoviePlaybackStatusReader::_playbackState protected
Definition at line 72 of file rc_playbackregs.h.
Referenced by getState(), and rcMoviePlaybackStatus::state().
The documentation for this class was generated from the following file:
include/visiCore/rc_playbackregs.h