Visible: rcMatrix_2d Class Reference
rcMatrix_2d Class Reference
#include <include/util/matrix.hpp>
Public Types
typedef
boost::numeric::ublas::c_matrix
< double, 2, 2 > matrix_type
Public Member Functions
rcMatrix_2d ()
rcMatrix_2d (double f11, double f12, double f21, double f22)
rcMatrix_2d (const rcDPair &rot, const rcDPair &scale)
rcMatrix_2d (const rcRadian &rot, const rcDPair &scale)
rcMatrix_2d (double scale, double aspect, const double &shear, const rcRadian &rotation)
double determinant () const
rcMatrix_2d inverse () const
bool isSingular () const
bool isIdentity () const
rcMatrix_2d transpose () const
double element (int32 row, int32 column) const
void element (int32 row, int32 column, double value)
double xRot () const
double yRot () const
double xScale () const
double yScale () const
double scale () const
double aspect () const
double shear () const
rcRadian rotation () const
rcMatrix_2d operator+ (const rcMatrix_2d &) const
rcMatrix_2d & operator+= (const rcMatrix_2d &)
rcMatrix_2d operator- () const
rcMatrix_2d operator- (const rcMatrix_2d &) const
rcMatrix_2d & operator-= (const rcMatrix_2d &)
rcMatrix_2d operator* (double) const
rcMatrix_2d & operator*= (double)
rcMatrix_2d operator* (const rcMatrix_2d &other) const
rcMatrix_2d & operator*= (const rcMatrix_2d &)
rcMatrix_2d operator/ (double) const
rcMatrix_2d & operator/= (double)
rcMatrix_2d operator/ (const rcMatrix_2d &) const
rcMatrix_2d & operator/= (const rcMatrix_2d &)
bool operator== (const rcMatrix_2d &other) const
bool operator!= (const rcMatrix_2d &other) const
template<typename V >
rc2dVector< V > operator* (const rc2dVector< V > &v) const
Static Public Attributes
static const rcMatrix_2d I
Private Member Functions
void setdt ()
Private Attributes
double mDt
Friends
ostream & operator<< (ostream &ous, const rcMatrix_2d &dis)
Detailed Description
Definition at line 60 of file matrix.hpp.
Member Typedef Documentation
typedef boost::numeric::ublas::c_matrix< double, 2, 2 > rcMatrix_2d::matrix_type
Definition at line 104 of file matrix.hpp.
Constructor & Destructor Documentation
rcMatrix_2d::rcMatrix_2d () inline
Definition at line 108 of file matrix.hpp.
                   : mDt(0)
     {
       matrix_type (2,2);
     }
rcMatrix_2d::rcMatrix_2d (double f11, double f12, double f21, double f22) inline
Definition at line 114 of file matrix.hpp.
                                                                 : mDt (0)
     {
       matrix_type (2,2);
       matrix_type::insert_element (0,0,f11);
       matrix_type::insert_element (0,1,f12);
       matrix_type::insert_element (1,0,f21);
       matrix_type::insert_element (1,1,f22);
       setdt();
     }
rcMatrix_2d::rcMatrix_2d (const rcDPair & rot, const rcDPair & scale) inline
Definition at line 124 of file matrix.hpp.
References cos(), sin(), rcPair< T >::x(), and rcPair< T >::y().
     {
       matrix_type(2,2);
         matrix_type::insert_element (0,0,scale.x() * std::cos(rot.x()));
         matrix_type::insert_element (0,0,-scale.y() * std::sin(rot.y()));
         matrix_type::insert_element (0,0,scale.x() * std::sin(rot.x()));
         matrix_type::insert_element (0,0,scale.y() * std::cos(rot.y()));
       setdt();
     }
rcMatrix_2d::rcMatrix_2d (const rcRadian & rot, const rcDPair & scale) inline
Definition at line 135 of file matrix.hpp.
References cos(), sin(), rcPair< T >::x(), and rcPair< T >::y().
     {
       matrix_type (2,2);
       double cosR = cos(rot);
       double sinR = sin(rot);
       matrix_type::insert_element (0,0, scale.x() * cosR);
       matrix_type::insert_element (0,0,  -scale.y() * sinR);
       matrix_type::insert_element (0,0,  scale.x() * sinR);
       matrix_type::insert_element (0,0,  scale.y() * cosR);
     }
rcMatrix_2d::rcMatrix_2d (double scale, double aspect, const double & shear, const rcRadian & rotation) inline
Definition at line 147 of file matrix.hpp.
References cos(), sin(), and tan().
     {
       matrix_type (2,2);
       double cosR = cos(rotation);
       double sinR = sin(rotation);
         double tanK = std::tan(shear);
       matrix_type::insert_element (0,0, scale * cosR);
       matrix_type::insert_element (0,0, aspect * scale * (- sinR - cosR * tanK ));
       matrix_type::insert_element (0,0,  scale * sinR);
       matrix_type::insert_element (0,0,  aspect * scale * (  cosR - sinR * tanK ));
       setdt();
     }
Member Function Documentation
double rcMatrix_2d::aspect () const inline
Definition at line 236 of file matrix.hpp.
References e11, e21, and rmSquare.
Referenced by rc2Xform::aspect().
     {
       if (isSingular()) throw general_exception ("Singular");
       return determinant() / (rmSquare(e11) + rmSquare(e21));
     }
double rcMatrix_2d::determinant () const inline
Definition at line 161 of file matrix.hpp.
Referenced by rc2Xform::invMapArea(), and rc2Xform::mapArea().
 { return mDt;}
double rcMatrix_2d::element (int32 row, int32 column) const inline
Definition at line 184 of file matrix.hpp.
     {
       return matrix_type::operator() (row,  column);
     }
void rcMatrix_2d::element (int32 row, int32 column, double value) inline
Definition at line 189 of file matrix.hpp.
     {
       matrix_type::insert_element (row, column, value);
     }
rcMatrix_2d rcMatrix_2d::inverse () const inline
Definition at line 163 of file matrix.hpp.
References e11, e12, e21, and e22.
Referenced by rc2Xform::inverse(), rc2Xform::invMapVector(), and rcLsFit< T >::rms().
     {
       if (isSingular()) throw general_exception ("is Singular");
       double idt = 1. / mDt; // do division once
       return rcMatrix_2d( e22 * idt, -e12 * idt,
                           -e21 * idt,  e11 * idt);
     }
bool rcMatrix_2d::isIdentity () const inline
Definition at line 175 of file matrix.hpp.
References e11, e12, e21, and e22.
Referenced by rc2Xform::isIdentity().
     {return (e11 == 1. && e12 == 0. &&
              e21 == 0. && e22 == 1.);
     }
bool rcMatrix_2d::isSingular () const inline
Definition at line 172 of file matrix.hpp.
Referenced by rcVisualFunction::distance(), and rc2Xform::isSingular().
     {return (mDt == 0.); }
bool rcMatrix_2d::operator!= (const rcMatrix_2d & other) const inline
Definition at line 298 of file matrix.hpp.
       {
           return *this != other;
       }
rcMatrix_2d rcMatrix_2d::operator* (double) const inline
rcMatrix_2d rcMatrix_2d::operator* (const rcMatrix_2d & other) const inline
Definition at line 277 of file matrix.hpp.
       {
           return (rcMatrix_2d) (*this * other);
       }
template<typename V > rc2dVector<V> rcMatrix_2d::operator* (const rc2dVector< V > & v) const inline
Definition at line 305 of file matrix.hpp.
References e11, e12, e21, e22, rc2dVector< T >::x(), and rc2dVector< T >::y().
       {
           return rc2dVector<V> ((V) (e11 * v.x() + e12 * v.y()) , (V) (e21 * v.x() + e22 * v.y()) );
       }
rcMatrix_2d& rcMatrix_2d::operator*= (double) inline
rcMatrix_2d& rcMatrix_2d::operator*= (const rcMatrix_2d &) inline
rcMatrix_2d rcMatrix_2d::operator+ (const rcMatrix_2d &) const inline
rcMatrix_2d& rcMatrix_2d::operator+= (const rcMatrix_2d &) inline
rcMatrix_2d rcMatrix_2d::operator- () const inline
rcMatrix_2d rcMatrix_2d::operator- (const rcMatrix_2d &) const inline
rcMatrix_2d& rcMatrix_2d::operator-= (const rcMatrix_2d &) inline
rcMatrix_2d rcMatrix_2d::operator/ (double) const inline
rcMatrix_2d rcMatrix_2d::operator/ (const rcMatrix_2d &) const inline
rcMatrix_2d& rcMatrix_2d::operator/= (double) inline
rcMatrix_2d& rcMatrix_2d::operator/= (const rcMatrix_2d &) inline
bool rcMatrix_2d::operator== (const rcMatrix_2d & other) const inline
Definition at line 293 of file matrix.hpp.
       {
           return *this == other;
       }
rcRadian rcMatrix_2d::rotation () const inline
Definition at line 249 of file matrix.hpp.
References arctan(), e11, and e21.
Referenced by rc2Xform::rotation().
     {
       if (isSingular()) throw general_exception ("Singular");
       return arctan (e21, e11);
     }
double rcMatrix_2d::scale () const inline
Definition at line 230 of file matrix.hpp.
References e11, e21, and rmSquare.
Referenced by rc2Xform::scale().
     {
       if (isSingular()) throw general_exception ("Singular");
       return sqrt(rmSquare(e11) + rmSquare(e21));
     }
void rcMatrix_2d::setdt () inline private
Definition at line 318 of file matrix.hpp.
References e11, e12, e21, and e22.
     { mDt = e11 * e22 - e21 * e12;}
double rcMatrix_2d::shear () const inline
Definition at line 242 of file matrix.hpp.
References e11, e12, e21, and e22.
Referenced by rc2Xform::shear().
     {
       if (isSingular()) throw general_exception ("Singular");
       // Shear is limited to (-PI/2, PI/2) so use arctan(x) = atan(x)
       return ( -atan((e11 * e12 + e21 * e22) / determinant()) );
     }
rcMatrix_2d rcMatrix_2d::transpose (void) const inline
Definition at line 180 of file matrix.hpp.
References e11, e12, e21, and e22.
     { return rcMatrix_2d(e11, e21, e12, e22); }
double rcMatrix_2d::xRot () const inline
Definition at line 203 of file matrix.hpp.
References atan2(), e11, and e21.
Referenced by rc2Xform::xRot().
     {
       if (isSingular()) throw general_exception ("Singular");
       // Full angle so use arctan(y,x) = atan2(y,x)
       return atan2(e21, e11);
     }
double rcMatrix_2d::xScale () const inline
Definition at line 217 of file matrix.hpp.
References e11, e21, and rmSquare.
Referenced by rcVisualFunction::scale(), and rc2Xform::xScale().
     {
       if (isSingular()) throw general_exception ("Singular");
       return sqrt(rmSquare(e11) + rmSquare(e21));
     }
double rcMatrix_2d::yRot () const inline
Definition at line 210 of file matrix.hpp.
References atan2(), e12, and e22.
Referenced by rc2Xform::yRot().
     {
       if (isSingular()) throw general_exception ("Singular");
       // Full angle so use arctan(y,x) = atan2(y,x)
       return atan2(-e12, e22);
     }
double rcMatrix_2d::yScale () const inline
Definition at line 223 of file matrix.hpp.
References e12, e22, and rmSquare.
Referenced by rcVisualFunction::scale(), and rc2Xform::yScale().
     {
       if (isSingular()) throw general_exception ("Singular");
       return sqrt(rmSquare(e12) + rmSquare(e22));
     }
Friends And Related Function Documentation
ostream& operator<< (ostream & ous, const rcMatrix_2d & dis) friend
Definition at line 310 of file matrix.hpp.
     {
       ous << "[" << dis.element (0,0) << " " << dis.element(0,1) << endl << dis.element(1,0) << " " << dis.element(1,1) << "]" << endl;
       return ous;
     }
Member Data Documentation
const rcMatrix_2d rcMatrix_2d::I static
Definition at line 264 of file matrix.hpp.
double rcMatrix_2d::mDt private
Definition at line 317 of file matrix.hpp.
The documentation for this class was generated from the following file:
include/util/matrix.hpp