Visible: rcVideoCaptureStatus Class Reference
rcVideoCaptureStatus Class Reference
#include <include/visiCore/rc_captureregs.h>
Public Member Functions
rcVideoCaptureStatus ()
void captureRect (const rcRect &captureRect)
void captureDepth (const rcPixel &captureDepth)
void maxFramesPerSecond (const double &f)
Public Member Functions inherited from rcVideoCaptureStatusReader
rcVideoCaptureStatusReader ()
virtual ~rcVideoCaptureStatusReader ()
rcRect getCaptureRect () const
rcPixel getCaptureDepth () const
double getMaxFramesPerSecond () const
Additional Inherited Members
Protected Attributes inherited from rcVideoCaptureStatusReader
rcAtomicValue< rcRect > _captureRect
rcAtomicValue< rcPixel > _captureDepth
rcAtomicValue< double > _maxFramesPerSecond
Detailed Description
Definition at line 141 of file rc_captureregs.h.
Constructor & Destructor Documentation
rcVideoCaptureStatus::rcVideoCaptureStatus () inline
Definition at line 144 of file rc_captureregs.h.
                          : rcVideoCaptureStatusReader()
   { }
Member Function Documentation
void rcVideoCaptureStatus::captureDepth (const rcPixel & captureDepth) inline
Definition at line 149 of file rc_captureregs.h.
References rcVideoCaptureStatusReader::_captureDepth, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::run().
   { _captureDepth.setValue(captureDepth); }
void rcVideoCaptureStatus::captureRect (const rcRect & captureRect) inline
Definition at line 147 of file rc_captureregs.h.
References rcVideoCaptureStatusReader::_captureRect, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::run().
   { _captureRect.setValue(captureRect); }
void rcVideoCaptureStatus::maxFramesPerSecond (const double & f) inline
Definition at line 151 of file rc_captureregs.h.
References rcVideoCaptureStatusReader::_maxFramesPerSecond, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieCapture::run().
   {  _maxFramesPerSecond.setValue(f); }
The documentation for this class was generated from the following file:
include/visiCore/rc_captureregs.h