Visible: rcMotionCenter Class Reference
rcMotionCenter Class Reference
#include <include/analysis/rc_motionpath.h>
Public Member Functions
rcMotionCenter ()
void add (const rc2Fvector &pos, const rc2Fvector &motion)
bool center (rc2Fvector &center)
Private Attributes
double mSumUU
double mSumVV
double mSumUV
double mSumUR
double mSumVR
bool mValid
Detailed Description
Definition at line 481 of file rc_motionpath.h.
Constructor & Destructor Documentation
rcMotionCenter::rcMotionCenter () inline
Definition at line 484 of file rc_motionpath.h.
 : mSumUU (0), mSumVV (0), mSumUV (0), mSumUR (0), mSumVR (0), mValid (false) {}
Member Function Documentation
void rcMotionCenter::add (const rc2Fvector & pos, const rc2Fvector & motion) inline
Definition at line 486 of file rc_motionpath.h.
References mSumUR, mSumUU, mSumUV, mSumVR, mSumVV, mValid, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcKinetoscope::connectFunction(), and rcVisualFunction::vXform().
   {
       mValid = false;
       double u = motion.x();
       double v = motion.y();
       double r = pos.x() * u + pos.y() * v;
       mSumUU += u * u;
       mSumVV += v * v;
       mSumUV += u * v;
       mSumUR += u * r;
       mSumVR += v * r;
     }
bool rcMotionCenter::center (rc2Fvector & center) inline
Definition at line 499 of file rc_motionpath.h.
References mSumUR, mSumUU, mSumUV, mSumVR, mSumVV, mValid, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcKinetoscope::connectFunction(), and rcVisualFunction::vXform().
   {
     double d = mSumUU * mSumVV - mSumUV * mSumUV;
     mValid = d > 0;
     if (mValid == true)
       {
     center.x((mSumUR * mSumVV - mSumUV * mSumVR)/d);
     center.y((mSumVR * mSumUU - mSumUV * mSumUR)/d);
       }
     return mValid;
   }
Member Data Documentation
double rcMotionCenter::mSumUR private
Definition at line 515 of file rc_motionpath.h.
Referenced by add(), and center().
double rcMotionCenter::mSumUU private
Definition at line 512 of file rc_motionpath.h.
Referenced by add(), and center().
double rcMotionCenter::mSumUV private
Definition at line 514 of file rc_motionpath.h.
Referenced by add(), and center().
double rcMotionCenter::mSumVR private
Definition at line 516 of file rc_motionpath.h.
Referenced by add(), and center().
double rcMotionCenter::mSumVV private
Definition at line 513 of file rc_motionpath.h.
Referenced by add(), and center().
bool rcMotionCenter::mValid private
Definition at line 517 of file rc_motionpath.h.
Referenced by add(), and center().
The documentation for this class was generated from the following file:
include/analysis/rc_motionpath.h