Visible: rcPersistenceManager Class Reference
rcPersistenceManager Class Reference abstract
#include <include/baseUI/rc_persistencemanager.h>
Public Member Functions
virtual ~rcPersistenceManager ()
virtual const std::string fileFormatExportExtension (rcExperimentFileFormat format) const =0
virtual const std::string fileFormatExportFilter (rcExperimentFileFormat format) const =0
virtual const std::string fileFormatExportCaption (rcExperimentFileFormat format) const =0
virtual const std::string fileFormatImportFilter (rcExperimentFileFormat format) const =0
virtual const std::string fileFormatImportCaption (rcExperimentFileFormat format) const =0
virtual void setGeneratorComment (const std::string &comment)=0
virtual const std::string generatorComment ()=0
virtual void setImportDirectory (const std::string &dir)=0
virtual const std::string getImportDirectory ()=0
Detailed Description
Definition at line 117 of file rc_persistencemanager.h.
Constructor & Destructor Documentation
virtual rcPersistenceManager::~rcPersistenceManager () inline virtual
Definition at line 121 of file rc_persistencemanager.h.
 { };
Member Function Documentation
virtual const std::string rcPersistenceManager::fileFormatExportCaption (rcExperimentFileFormat format) const pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcFileSaveSettingWidget::browseRequest(), and rcModelDomain::requestSave().
virtual const std::string rcPersistenceManager::fileFormatExportExtension (rcExperimentFileFormat format) const pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcFileSaveSettingWidget::browseRequest(), rcEngineMovieSaver::closeHdlr(), rcEngineImpl::loadMovie(), rcModelDomain::requestSave(), and rcExperimentImpl::saveTo().
virtual const std::string rcPersistenceManager::fileFormatExportFilter (rcExperimentFileFormat format) const pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcFileSaveSettingWidget::browseRequest(), and rcModelDomain::requestSave().
virtual const std::string rcPersistenceManager::fileFormatImportCaption (rcExperimentFileFormat format) const pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcFileChoiceSettingWidget::multiFileBrowse(), rcModelDomain::requestOpen(), and rcFileChoiceSettingWidget::singleFileBrowse().
virtual const std::string rcPersistenceManager::fileFormatImportFilter (rcExperimentFileFormat format) const pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcFileChoiceSettingWidget::multiFileBrowse(), rcModelDomain::requestOpen(), and rcFileChoiceSettingWidget::singleFileBrowse().
virtual const std::string rcPersistenceManager::generatorComment () pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcEngineMovieSaver::closeHdlr(), rcExperimentDomainImpl::saveExperiment(), and rcExperimentImpl::saveTo().
virtual const std::string rcPersistenceManager::getImportDirectory () pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcEngineImpl::loadMovie().
virtual void rcPersistenceManager::setGeneratorComment (const std::string & comment) pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by main(), and rcMainWindow::rcMainWindow().
virtual void rcPersistenceManager::setImportDirectory (const std::string & dir) pure virtual
Implemented in rcPersistenceManagerImpl.
Referenced by rcModelDomain::requestOpen().
The documentation for this class was generated from the following file:
include/baseUI/rc_persistencemanager.h