Visible: rcQVideoGrabber Class Reference
rcQVideoGrabber Class Reference
#include <include/visual/rc_qvideograbber.h>
Public Member Functions
rcQVideoGrabber (char *progName, int arg1, char *arg2, uint32 sz, uint8 childControlsBufferFirst=TRUE)
virtual ~rcQVideoGrabber ()
virtual rcFrameGrabberStatus getAcqInfo (rcAcqInfo &acqInfo, bool isBlocking, bool releaseMemory=TRUE)
virtual rcFrameGrabberStatus setAcqControl (rcAcqControl &acqCtrl, bool isBlocking, bool releaseMemory=TRUE)
virtual void setFrameCount (int32 frameCount)
virtual void addBuffer (rcSharedFrameBufPtr &buf)
virtual bool isValid () const
virtual rcFrameGrabberError getLastError () const
virtual bool start ()
virtual bool stop ()
virtual int32 frameCount ()
virtual rcFrameGrabberStatus getNextFrame (rcSharedFrameBufPtr &ptr, bool isBlocking)
virtual const std::string getInputSourceName ()
Public Member Functions inherited from rcCameraGrabber
virtual int32 cacheSize ()
Public Member Functions inherited from rcFrameGrabber
virtual ~rcFrameGrabber ()
Private Attributes
rcExecWithShmem * _shmemCtrlP
rcFrameGrabberError _lastError
bool _isValid
int32 _frameCount
vector< rcSharedFrameBufPtr > _buffers
Additional Inherited Members
Static Public Member Functions inherited from rcFrameGrabber
static std::string getErrorString (rcFrameGrabberError error)
Detailed Description
Definition at line 51 of file rc_qvideograbber.h.
Constructor & Destructor Documentation
rcQVideoGrabber::rcQVideoGrabber (char * progName, int arg1, char * arg2, uint32 sz, uint8 childControlsBufferFirst = TRUE)
Definition at line 19 of file rc_qvideograbber.cpp.
References _isValid, _lastError, _shmemCtrlP, eFrameErrorOutOfMemory, eFrameErrorSystemResources, eFrameErrorUnknown, eNoError, eProcessFork, eSemaphoreInit, eShmemInit, FALSE, rcExecWithShmem::getCreationError(), and rmAssert.
         : _shmemCtrlP(new rcExecWithShmem(progName, arg1, arg2, sz,
                                           childControlsBufferFirst)),
           _lastError(eFrameErrorOK), _isValid(TRUE), _frameCount(-1)
 {
     if (!_shmemCtrlP)
     {
         _lastError = eFrameErrorOutOfMemory;
         _isValid = FALSE;
     }
     switch (_shmemCtrlP->getCreationError())
     {
         case eNoError:
             break;
         case eShmemInit:
         case eSemaphoreInit:
             _lastError = eFrameErrorSystemResources;
             _isValid = FALSE;
             break;
         case eProcessFork:
             _lastError = eFrameErrorUnknown;
             _isValid = FALSE;
             break;
         default:
             rmAssert(0);
     }
 }
rcQVideoGrabber::~rcQVideoGrabber () virtual
Definition at line 53 of file rc_qvideograbber.cpp.
References _shmemCtrlP, rcExecWithShmem::getChildPID(), rcExecWithShmem::isChildDone(), and NULL.
 {
   /* Give child a second to clean things up.
    */
     fprintf(stderr, "waiting...\n");
     for (int i = 0; (i < 1000) && !_shmemCtrlP->isChildDone(); i++)
         usleep(1000);
     fprintf(stderr, "Done waiting\n");
     /* Send terminate signal to child and wait for child process to end
      */
     pid_t pid = _shmemCtrlP->getChildPID();
     if ( pid > 0 ) {
         kill(_shmemCtrlP->getChildPID(), SIGKILL);
         wait(NULL);
     }
     delete _shmemCtrlP;
 }
Member Function Documentation
void rcQVideoGrabber::addBuffer (rcSharedFrameBufPtr & buf) virtual
Implements rcCameraGrabber.
Definition at line 174 of file rc_qvideograbber.cpp.
References _buffers.
 {
     _buffers.push_back(buf);
 }
int32 rcQVideoGrabber::frameCount () virtual
Implements rcFrameGrabber.
Definition at line 194 of file rc_qvideograbber.cpp.
References _frameCount.
Referenced by setFrameCount().
 {
     return _frameCount;
 }
rcFrameGrabberStatus rcQVideoGrabber::getAcqInfo (rcAcqInfo & acqInfo, bool isBlocking, bool releaseMemory = TRUE) virtual
Implements rcCameraGrabber.
Definition at line 73 of file rc_qvideograbber.cpp.
References _isValid, _lastError, _shmemCtrlP, rcSharedMemoryUser::acquireSharedMemory(), eFrameErrorIPC, eFrameStatusError, eFrameStatusOK, rcExecWithShmem::getShmemUser(), rcSharedMemNoError, rcSharedMemoryUser::releaseSharedMemory(), rmAssert, and rcVideoSharedMemLayout::videoState.
 {
     if (!_isValid)
         return eFrameStatusError;
     rcSharedMemoryUser& consumer = _shmemCtrlP->getShmemUser();
     rcSharedMemError err;
     rcVideoSharedMemLayout* acqData =
         (rcVideoSharedMemLayout*)consumer.acquireSharedMemory(err, isBlocking);
     if (!acqData)
     {
         fprintf(stderr, "Parent: error acquiring shared data. err: %d\n", err);
         perror("Parent: ");
         _lastError = eFrameErrorIPC;
         return eFrameStatusError;
     }
     /* Read acq state info from shared memory.
      */
     rmAssert(sizeof(acqInfo) == sizeof(acqData->videoState));
     memmove(&acqInfo, &(acqData->videoState), sizeof(acqInfo));
     /* All data read from shared buffer. Free it.
      */
     if (releaseMemory)
     {
         switch (err = consumer.releaseSharedMemory())
         {
             case rcSharedMemNoError:
                 break;
             default:
                 fprintf(stderr, "Parent: error freeing shared data, err: %d\n", err);
                 perror("Parent: ");
                 _lastError = eFrameErrorIPC;
                 return eFrameStatusError;
         } // End of: switch (consumer.releaseSharedMemory())
     } // End of: if (releaseMemory)
     return eFrameStatusOK;
 }
const std::string rcQVideoGrabber::getInputSourceName () virtual
Implements rcFrameGrabber.
Definition at line 326 of file rc_qvideograbber.cpp.
 {
     // TODO: add camera model name here if it can be queried from
     // the device
     std::string cameraName = "Fireware camera";
     return cameraName;
 }
rcFrameGrabberError rcQVideoGrabber::getLastError () const virtual
Implements rcFrameGrabber.
Definition at line 179 of file rc_qvideograbber.cpp.
References _lastError.
 {
     return _lastError;
 }
rcFrameGrabberStatus rcQVideoGrabber::getNextFrame (rcSharedFrameBufPtr & ptr, bool isBlocking) virtual
Implements rcFrameGrabber.
Definition at line 199 of file rc_qvideograbber.cpp.
References _buffers, _frameCount, _isValid, _lastError, _shmemCtrlP, rcAcqInfo::acqFlags, rcSharedMemoryUser::acquireSharedMemory(), eFrameErrorCameraCapture, eFrameErrorFrameNotAvailable, eFrameErrorIPC, eFrameErrorSystemResources, eFrameStatusEOF, eFrameStatusError, eFrameStatusNoFrame, eFrameStatusOK, rcExecWithShmem::getShmemUser(), rcVideoSharedMemLayout::height, rcFrame::initGrayColorMap(), rcVideoSharedMemLayout::isGray, rcFrame::loadImage(), rcVideoSharedMemLayout::pixelDepth, rcVideoSharedMemLayout::rawPixels, rcACQFLAGS_FRAMEAVAIL, rcACQFLAGS_FRAMEERROR, rcACQFLAGS_FRAMESKIPPED, rcPixel16, rcPixel8, rcSharedMemNoError, rcSharedMemNotAvailable, rcSharedMemoryUser::releaseSharedMemory(), rfFillColorMap(), rcVideoSharedMemLayout::rowUpdate, rcFrame::setTimestamp(), rcVideoSharedMemLayout::timestamp, rcVideoSharedMemLayout::videoState, and rcVideoSharedMemLayout::width.
 {
     if (!_isValid)
         return eFrameStatusError;
     if (_frameCount > 0)
         _frameCount--;
     else if (_frameCount == 0)
         return eFrameStatusEOF;
     /* fgStatus is a place to collect errors that happen before shared
      * resources have been freed.
      */
     rcFrameGrabberStatus fgStatus = eFrameStatusOK;
     rcSharedMemoryUser& consumer = _shmemCtrlP->getShmemUser();
     rcSharedMemError err;
     bool needFrame = true;
     while (needFrame)
     {
         rcVideoSharedMemLayout* imgData =
             (rcVideoSharedMemLayout*)consumer.acquireSharedMemory(err, isBlocking);
         if (!imgData)
         {
             if (err == rcSharedMemNotAvailable)
             {
                 _lastError = eFrameErrorFrameNotAvailable;
                 return eFrameStatusNoFrame;
             }
             fprintf(stderr, "Parent: error acquiring shared data. err: %d\n", err);
             perror("Parent: ");
             _lastError = eFrameErrorIPC;
             return eFrameStatusError;
         }
         if ((imgData->videoState.acqFlags & ~rcACQFLAGS_FRAMESKIPPED) ==
             rcACQFLAGS_FRAMEAVAIL)
         {
             /* Copy pixels from shared data into a new frame buffer created from the
              * heap.
              */
             try
             {
                 /* First, try to find a buffer that is currently only
                  * referenced by the rcSharedFrameBufPtr _buffers in
                  * _buffers. Its reference count therefore should be 1.
                  */
                 vector<rcSharedFrameBufPtr>::iterator bufptr = _buffers.begin();
                 for ( ; bufptr != _buffers.end(); bufptr++)
                     if ((*bufptr).refCount() == 1)
                         break;
                 if (bufptr == _buffers.end()) {
                     fptr = rcSharedFrameBufPtr(new rcFrame(imgData->rawPixels,
                                                             imgData->rowUpdate,
                                                             imgData->width,
                                                             imgData->height,
                                                             imgData->pixelDepth,
                                                             imgData->isGray));
                     // Init color map
                     if (imgData->pixelDepth == rcPixel8)
                     {
                         fptr->initGrayColorMap();
                     }
                     else if (imgData->pixelDepth == rcPixel16)
                         rfFillColorMap(0, fptr);
                 }
                 else {
                     fptr = *bufptr;
                     fptr->loadImage(imgData->rawPixels, imgData->rowUpdate, imgData->width,
                                     imgData->height, imgData->pixelDepth, imgData->isGray);
                 }
                 if (!fptr) {
                     _lastError = eFrameErrorSystemResources;
                     fgStatus = eFrameStatusError;
                 }
                 else
                     fptr->setTimestamp(imgData->timestamp);
             }
             catch (...)
             {
                 _lastError = eFrameErrorSystemResources;
                 fgStatus = eFrameStatusError;
             }
             needFrame = false;
         }
         else if (imgData->videoState.acqFlags & rcACQFLAGS_FRAMEERROR)
         {
             _lastError = eFrameErrorCameraCapture;
             fgStatus = eFrameStatusError;
         }
 #ifdef DEBUGGING
         else
             fprintf(stderr, "xyzzy looping...\n");
 #endif
         /* All data read from shared buffer. Free it.
          */
         switch (err = consumer.releaseSharedMemory())
         {
             case rcSharedMemNoError:
                 break;
             default:
                 fprintf(stderr, "Parent: error freeing shared data, err: %d\n", err);
                 perror("Parent: ");
                 _lastError = eFrameErrorIPC;
                 fgStatus = eFrameStatusError;
         } // End of: switch (consumer.releaseSharedMemory())
         if (fgStatus != eFrameStatusOK)
             return fgStatus;
     } // End of: while (needFrame)
     return eFrameStatusOK;
 }
virtual bool rcQVideoGrabber::isValid () const inline virtual
Implements rcFrameGrabber.
Definition at line 84 of file rc_qvideograbber.h.
 { return _isValid; }
rcFrameGrabberStatus rcQVideoGrabber::setAcqControl (rcAcqControl & acqCtrl, bool isBlocking, bool releaseMemory = TRUE) virtual
Implements rcCameraGrabber.
Definition at line 121 of file rc_qvideograbber.cpp.
References _isValid, _lastError, _shmemCtrlP, rcSharedMemoryUser::acquireSharedMemory(), eFrameErrorIPC, eFrameStatusError, eFrameStatusOK, rcExecWithShmem::getShmemUser(), rcSharedMemNoError, rcSharedMemoryUser::releaseSharedMemory(), rmAssert, and rcVideoSharedMemLayout::videoControl.
 {
     if (!_isValid)
         return eFrameStatusError;
     rcSharedMemoryUser& consumer = _shmemCtrlP->getShmemUser();
     rcSharedMemError err;
     rcVideoSharedMemLayout* acqData =
         (rcVideoSharedMemLayout*)consumer.acquireSharedMemory(err, isBlocking);
     if (!acqData)
     {
         fprintf(stderr, "Parent: error acquiring shared data. err: %d\n", err);
         perror("Parent: ");
         _lastError = eFrameErrorIPC;
         return eFrameStatusError;
     }
     /* Copy acq control info into shared memory.
      */
     rmAssert(sizeof(acqCtrl) == sizeof(acqData->videoControl));
     memmove(&(acqData->videoControl), &acqCtrl, sizeof(acqCtrl));
     /* All data read from shared buffer. Free it.
      */
     if (releaseMemory)
     {
         switch (err = consumer.releaseSharedMemory())
         {
             case rcSharedMemNoError:
                 break;
             default:
                 fprintf(stderr, "Parent: error freeing shared data, err: %d\n", err);
                 perror("Parent: ");
                 _lastError = eFrameErrorIPC;
                 return eFrameStatusError;
         } // End of: switch (consumer.releaseSharedMemory())
     } // End of: if (releaseMemory)
     return eFrameStatusOK;
 }
void rcQVideoGrabber::setFrameCount (int32 frameCount) virtual
Implements rcCameraGrabber.
Definition at line 169 of file rc_qvideograbber.cpp.
References _frameCount, and frameCount().
 {
     _frameCount = frameCount;
 }
bool rcQVideoGrabber::start (void) virtual
Implements rcFrameGrabber.
Definition at line 184 of file rc_qvideograbber.cpp.
References _isValid.
 {
     return _isValid; // Will have to do until I add IPC code to really do this
 }
bool rcQVideoGrabber::stop (void) virtual
Implements rcFrameGrabber.
Definition at line 189 of file rc_qvideograbber.cpp.
References _isValid.
 {
     return _isValid; // Will have to do until I add IPC code to really do this
 }
Member Data Documentation
vector<rcSharedFrameBufPtr> rcQVideoGrabber::_buffers private
Definition at line 110 of file rc_qvideograbber.h.
Referenced by addBuffer(), and getNextFrame().
int32 rcQVideoGrabber::_frameCount private
Definition at line 109 of file rc_qvideograbber.h.
Referenced by frameCount(), getNextFrame(), and setFrameCount().
bool rcQVideoGrabber::_isValid private
Definition at line 108 of file rc_qvideograbber.h.
Referenced by getAcqInfo(), getNextFrame(), rcQVideoGrabber(), setAcqControl(), start(), and stop().
rcFrameGrabberError rcQVideoGrabber::_lastError private
Definition at line 107 of file rc_qvideograbber.h.
Referenced by getAcqInfo(), getLastError(), getNextFrame(), rcQVideoGrabber(), and setAcqControl().
rcExecWithShmem* rcQVideoGrabber::_shmemCtrlP private
Definition at line 106 of file rc_qvideograbber.h.
Referenced by getAcqInfo(), getNextFrame(), rcQVideoGrabber(), setAcqControl(), and ~rcQVideoGrabber().
The documentation for this class was generated from the following files:
include/visual/rc_qvideograbber.h
src/visual/code/rc_qvideograbber.cpp