Visible: rcExperimentObserver Class Reference
rcExperimentObserver Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcExperimentObserver ()
virtual void notifyError (const char *errorString)=0
virtual void notifyWarning (const char *warnString)=0
virtual void notifyStatus (const char *statusString)=0
virtual void notifyState (rcExperimentState newState, bool immediateDispatch=false)=0
virtual void notifyTime (const rcTimestamp &elapsedTime)=0
virtual void notifyProgCursorTime (const rcTimestamp &elapsedTime)=0
virtual int32 progCursorTimeEventCount () const =0
virtual void notifyTimelineRange (const rcTimestamp &start, const rcTimestamp &end)=0
virtual void notifyEngineTimelineRange (const rcTimestamp &start, const rcTimestamp &end)=0
virtual void notifyAnalysisRect (const rcRect &rect)=0
virtual void notifyAnalysisRectRotation (const rcAffineRectangle &affine)=0
virtual void notifyMultiplier (const double &multiplier)=0
virtual bool acceptingImageBlits (void)=0
virtual void notifyBlitData (const rcWindow *image)=0
virtual void notifyBlitGraphics (const rcVisualGraphicsCollection *graphics)=0
virtual void notifyLockApp (bool lock)=0
virtual void notifyExperimentChange (void)=0
virtual void notifyVideoRect (const rcRect &rect)=0
virtual bool acceptingPolys (void)=0
virtual void notifyPolys ()=0
virtual void getPolys (rcPolygonGroupRef &polys)=0
Detailed Description
Definition at line 197 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcExperimentObserver::~rcExperimentObserver () inline virtual
Definition at line 201 of file rc_model.h.
 { };
Member Function Documentation
virtual bool rcExperimentObserver::acceptingImageBlits (void) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::acceptingImageBlits().
virtual bool rcExperimentObserver::acceptingPolys (void) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::acceptingPolys().
virtual void rcExperimentObserver::getPolys (rcPolygonGroupRef & polys) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::getPolys().
virtual void rcExperimentObserver::notifyAnalysisRect (const rcRect & rect) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyAnalysisRect().
virtual void rcExperimentObserver::notifyAnalysisRectRotation (const rcAffineRectangle & affine) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyAnalysisRectRotation().
virtual void rcExperimentObserver::notifyBlitData (const rcWindow * image) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyBlitData().
virtual void rcExperimentObserver::notifyBlitGraphics (const rcVisualGraphicsCollection * graphics) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyBlitGraphics().
virtual void rcExperimentObserver::notifyEngineTimelineRange (const rcTimestamp & start, const rcTimestamp & end) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::notifyTimelineRange().
virtual void rcExperimentObserver::notifyError (const char * errorString) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::notifyError().
virtual void rcExperimentObserver::notifyExperimentChange (void) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyExperimentChange(), and rcExperimentDomainImpl::notifyRequestSave().
virtual void rcExperimentObserver::notifyLockApp (bool lock) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::lock(), and rcExperimentDomainImpl::unlock().
virtual void rcExperimentObserver::notifyMultiplier (const double & multiplier) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyMultiplier().
virtual void rcExperimentObserver::notifyPolys () pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
virtual void rcExperimentObserver::notifyProgCursorTime (const rcTimestamp & elapsedTime) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::notifyTime().
virtual void rcExperimentObserver::notifyState (rcExperimentState newState, bool immediateDispatch = false) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::loadExperiment(), rcExperimentDomainImpl::newExperiment(), and rcExperimentDomainImpl::setInternalState().
virtual void rcExperimentObserver::notifyStatus (const char * statusString) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::notifyStatus().
virtual void rcExperimentObserver::notifyTime (const rcTimestamp & elapsedTime) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::newExperiment(), and rcExperimentDomainImpl::notifyTime().
virtual void rcExperimentObserver::notifyTimelineRange (const rcTimestamp & start, const rcTimestamp & end) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
virtual void rcExperimentObserver::notifyVideoRect (const rcRect & rect) pure virtual
Implemented in rcBatchExperimentObserver, and rcModelDomain.
Referenced by rcExperimentDomainImpl::notifyVideoRect().
virtual void rcExperimentObserver::notifyWarning (const char * warnString) pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::notifyWarning().
virtual int32 rcExperimentObserver::progCursorTimeEventCount () const pure virtual
Implemented in rcModelDomain, and rcBatchExperimentObserver.
Referenced by rcExperimentDomainImpl::timeEventCount().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h