Visible: rcRadioChoiceSettingWidget Class Reference
rcRadioChoiceSettingWidget Class Reference
#include <include/visUI/rc_radiochoicesettingwidget.h>
Public Slots
void choiceSelected (int choiceValue)
void settingChanged (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcRadioChoiceSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcRadioChoiceSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 6 of file rc_radiochoicesettingwidget.h.
Constructor & Destructor Documentation
rcRadioChoiceSettingWidget::rcRadioChoiceSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 21 of file rc_radiochoicesettingwidget.cpp.
References choiceSelected(), rcSettingInfo::getChoice(), rcSettingChoice::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingWidget::mTopLayout, and settingChanged().
     : rcSettingWidget( parent, setting )
 {
     Q3BoxLayout* radioLayout = new Q3HBoxLayout( mTopLayout );
     int nChoices = setting.getNChoices();
     for (int i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = setting.getChoice( i );
         rcChoiceRadioButton* widget = new rcChoiceRadioButton( this , choice );
         connect( widget , SIGNAL( choiceSelected( int ) ) , this , SLOT( choiceSelected( int ) ) );
         radioLayout->addWidget( widget );
         QToolTip::add( widget , choice.getDescription() );
     }
     // update the radio buttons with the current value of the setting.
     settingChanged();
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
 }
rcRadioChoiceSettingWidget::~rcRadioChoiceSettingWidget ()
Definition at line 46 of file rc_radiochoicesettingwidget.cpp.
 {
     // Remove all tool tips
     QObjectList list = queryList( "rcChoiceRadioButton" , 0, false , false );
     for (unsigned int i = 0; i < list.count(); i++)
     {
         rcChoiceRadioButton* button = (rcChoiceRadioButton*) list.at( i );
         QToolTip::remove( button );
     }
 }
Member Function Documentation
void rcRadioChoiceSettingWidget::choiceSelected (int choiceValue) slot
Definition at line 61 of file rc_radiochoicesettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcRadioChoiceSettingWidget().
 {
     mSetting.setValue( choiceValue );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
void rcRadioChoiceSettingWidget::settingChanged (void) slot
Definition at line 74 of file rc_radiochoicesettingwidget.cpp.
References rcChoiceRadioButton::getChoiceValue(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, rcModelDomain::requestInputSource(), and rcSettingWidget::updateWidgetState().
Referenced by rcRadioChoiceSettingWidget().
 {
     int currentValue = mSetting.getValue();
     QObjectList list = queryList( "rcChoiceRadioButton" , 0, false , false );
     for (unsigned int i = 0; i < list.count(); i++)
     {
         rcChoiceRadioButton* button = (rcChoiceRadioButton*) list.at( i );
         button->setChecked( currentValue == button->getChoiceValue() );
     }
     // Update visibility/editability
     updateWidgetState();
     // Hack alert: this is brittle
     // Send request for input source only
     if ( ! strcmp( mSetting.getTag(), "input-source" ) )
         rcModelDomain::getModelDomain()->requestInputSource( currentValue );
 }
The documentation for this class was generated from the following files:
include/visUI/rc_radiochoicesettingwidget.h
src/visible/qt/rc_radiochoicesettingwidget.cpp