Visible: rcHornMoments Class Reference
rcHornMoments Class Reference
#include <include/analysis/rc_level.h>
Public Member Functions
rcHornMoments (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail)
void compute (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail)
double zeroth () const
double first () const
double second () const
Private Attributes
double mZeroth
double mFirst
double mSecond
Detailed Description
Definition at line 93 of file rc_level.h.
Constructor & Destructor Documentation
rcHornMoments::rcHornMoments (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail) inline
Definition at line 96 of file rc_level.h.
References compute().
     {compute(leftTail, rightTail);}
Member Function Documentation
void rcHornMoments::compute (vector< uint32 >::const_iterator leftTail, vector< uint32 >::const_iterator rightTail)
Definition at line 74 of file rc_seglevel.cpp.
References mFirst, mSecond, and mZeroth.
Referenced by rcHornMoments().
 {
   // we shift the interval [left tail, right tail] to [0, right - left]
   double m0 = 0.0, m1 = 0.0, m2 = 0.0;
   // Horn Accumulator
   // the left tail is intentionally excluded
   for( vector<uint32>::const_iterator p = rightTail;
       p > leftTail;
       p--){
     m0 += *p;
     m1 += m0;
     m2 += m1;
   }
   // since we assume left tail == 0, we do not have to add i * hist[i] to m1
   mZeroth = m0 + *leftTail;     // number of sample
   mFirst = m1;                  // mean * number of sample
   mSecond = m2 * 2 - m1;        // var = second_/zeroth_ - (first_/zeroth_)^2
 }
double rcHornMoments::first () const inline
Definition at line 109 of file rc_level.h.
References mFirst.
Referenced by rcWithinGroupInv::compute().
 {return mFirst;}
double rcHornMoments::second () const inline
Definition at line 110 of file rc_level.h.
References mSecond.
Referenced by rcWithinGroupInv::compute().
 {return mSecond;}
double rcHornMoments::zeroth () const inline
Definition at line 108 of file rc_level.h.
References mZeroth.
Referenced by rcWithinGroupInv::compute().
 {return mZeroth;}
Member Data Documentation
double rcHornMoments::mFirst private
Definition at line 114 of file rc_level.h.
Referenced by compute(), and first().
double rcHornMoments::mSecond private
Definition at line 115 of file rc_level.h.
Referenced by compute(), and second().
double rcHornMoments::mZeroth private
Definition at line 113 of file rc_level.h.
Referenced by compute(), and zeroth().
The documentation for this class was generated from the following files:
include/analysis/rc_level.h
src/analysis/code/rc_seglevel.cpp