Visible: rcMutualInfo Class Reference
rcMutualInfo Class Reference
#include <include/visual/rc_mutualinfo.h>
Public Member Functions
rcMutualInfo ()
void add (const rcWindow &a, const rcWindow &b)
void add (int32 a, int32 b)
const rcWindow & hist () const
Private Attributes
rcWindow mMi
rcWindow mRatio
Friends
ostream & operator<< (ostream &o, const rcMutualInfo &mu)
Detailed Description
Definition at line 16 of file rc_mutualinfo.h.
Constructor & Destructor Documentation
rcMutualInfo::rcMutualInfo () inline
Definition at line 20 of file rc_mutualinfo.h.
References mMi, rcPixel32, and rcWindow::setAllPixels().
   {
     mMi = rcWindow (256, 256, rcPixel32);
     mMi.setAllPixels (0);
   }
Member Function Documentation
void rcMutualInfo::add (const rcWindow & a, const rcWindow & b) inline
Definition at line 27 of file rc_mutualinfo.h.
References rcWindow::height(), rmAssert, rcWindow::rowPointer(), rcWindow::size(), rcWindow::width(), rcPair< T >::x(), and rcPair< T >::y().
   {
     rmAssert (a.size() == b.size());
     rcIPair largeAoverB (-1,-1);
     rcIPair largeBoverA (-1,-1);
     for (int32 j = 0; j < a.height(); j++)
       {
     const uint8* aPtr = a.rowPointer (j);
     const uint8* bPtr = b.rowPointer (j);
     for (int32 i = 0; i < a.width(); i++)
       {
         int32 ai = (*aPtr++);
         int32 bi = (*bPtr++);
         add (ai, bi);
         if (ai > bi && ai != largeAoverB.x() && bi != largeAoverB.y())
           largeAoverB = rcIPair (ai,bi);
         if (bi > ai && ai != largeBoverA.x() && bi != largeBoverA.y())
           largeBoverA = rcIPair (ai,bi);
       }
       }
   }
void rcMutualInfo::add (int32 a, int32 b) inline
Definition at line 51 of file rc_mutualinfo.h.
References rcWindow::getPixel(), mMi, and rcWindow::setPixel().
   {
     uint32 p = mMi.getPixel (a, b);
     p += 1;
     mMi.setPixel (a, b, p);
   }
const rcWindow& rcMutualInfo::hist () const inline
Definition at line 58 of file rc_mutualinfo.h.
References mMi.
   {
     return mMi;
   }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcMutualInfo & mu) friend
Definition at line 64 of file rc_mutualinfo.h.
   {
     o << "{";
     for (int32 j = 0; j < mu.hist().height(); j++)
     {
       o << "{";
       for (int32 i = 0; i < mu.hist().width(); i++)
     {
       o <<  mu.hist().getPixel (i, j);
       if (i < mu.hist().width() - 1)
         o << ",";
     }
       o << "}";
       if (j < mu.hist().height() - 1)
     o << ",";
       o << endl;
     }
     o << "};" << endl;
     return o;
   }
Member Data Documentation
rcWindow rcMutualInfo::mMi private
Definition at line 89 of file rc_mutualinfo.h.
Referenced by add(), hist(), and rcMutualInfo().
rcWindow rcMutualInfo::mRatio private
Definition at line 90 of file rc_mutualinfo.h.
The documentation for this class was generated from the following file:
include/visual/rc_mutualinfo.h