Visible: lm_file_dependency Class Reference
lm_file_dependency Class Reference
#include <include/stlplus/library_manager.hpp>
Public Member Functions
lm_file_dependency (void)
lm_file_dependency (const std::string &library_path, const std::string &path, unsigned line=0, unsigned column=0)
~lm_file_dependency (void)
const std::string & path (void) const
std::string path_full (const std::string &library_path) const
void set_path (const std::string &library_path, const std::string &path)
unsigned line (void) const
void set_line (unsigned line=0)
unsigned column (void) const
void set_column (unsigned column=0)
Private Attributes
std::string m_path
unsigned m_line
unsigned m_column
Friends
void dump (dump_context &context, const lm_file_dependency &) throw (persistent_dump_failed)
void restore (restore_context &context, lm_file_dependency &) throw (persistent_restore_failed)
otext & print (otext &, const lm_file_dependency &)
otext & print (otext &, const lm_file_dependency &, unsigned indent)
otext & operator<< (otext &, const lm_file_dependency &)
Detailed Description
Definition at line 87 of file library_manager.hpp.
Constructor & Destructor Documentation
lm_file_dependency::lm_file_dependency (void)
Definition at line 251 of file library_manager.cpp.
                                            : m_line(0), m_column(0)
 {
 }
lm_file_dependency::lm_file_dependency (const std::string & library_path, const std::string & path, unsigned line = 0, unsigned column = 0)
Definition at line 255 of file library_manager.cpp.
References set_column(), set_line(), and set_path().
 {
   set_path(library_path, path);
   set_line(line);
   set_column(column);
 }
lm_file_dependency::~lm_file_dependency (void)
Definition at line 262 of file library_manager.cpp.
 {
 }
Member Function Documentation
unsigned lm_file_dependency::column (void) const
Definition at line 291 of file library_manager.cpp.
References m_column.
Referenced by lm_unit::print_long(), and set_column().
 {
   return m_column;
 }
unsigned lm_file_dependency::line (void) const
Definition at line 281 of file library_manager.cpp.
References m_line.
Referenced by lm_unit::print_long(), and set_line().
 {
   return m_line;
 }
const std::string & lm_file_dependency::path (void) const
Definition at line 266 of file library_manager.cpp.
References m_path.
 {
   return m_path;
 }
std::string lm_file_dependency::path_full (const std::string & library_path) const
Definition at line 271 of file library_manager.cpp.
References filespec_to_path(), and m_path.
Referenced by out_of_date_chk(), lm_library::pretty_print(), and lm_unit::print_long().
 {
   return filespec_to_path(library_path, m_path);
 }
void lm_file_dependency::set_column (unsigned column = 0)
Definition at line 296 of file library_manager.cpp.
References column(), and m_column.
Referenced by lm_file_dependency().
 {
   m_column = column;
 }
void lm_file_dependency::set_line (unsigned line = 0)
Definition at line 286 of file library_manager.cpp.
References line(), and m_line.
Referenced by lm_file_dependency().
 {
   m_line = line;
 }
void lm_file_dependency::set_path (const std::string & library_path, const std::string & path)
Definition at line 276 of file library_manager.cpp.
References filespec_to_relative_path(), and m_path.
Referenced by lm_file_dependency().
 {
   m_path = filespec_to_relative_path(library_path, path);
 }
Friends And Related Function Documentation
void dump (dump_context & context, const lm_file_dependency &) throw (persistent_dump_failed) friend
Definition at line 301 of file library_manager.cpp.
 {
   dump(context, dependency.m_path);
   dump(context, dependency.m_line);
   dump(context, dependency.m_column);
 }
otext& operator<< (otext & , const lm_file_dependency &) friend
Definition at line 330 of file library_manager.cpp.
 {
   return print(str, dependency);
 }
otext& print (otext & , const lm_file_dependency &) friend
Definition at line 315 of file library_manager.cpp.
 {
   str << "file: " << dependency.m_path;
   if (dependency.m_line != 0)
     str << ":" << dependency.m_line << ":" << dependency.m_column;
   return str;
 }
otext& print (otext & , const lm_file_dependency & , unsigned indent) friend
Definition at line 323 of file library_manager.cpp.
 {
   print_indent(str, indent);
   print(str, dependency);
   return str << endl;
 }
void restore (restore_context & context, lm_file_dependency &) throw (persistent_restore_failed) friend
Definition at line 308 of file library_manager.cpp.
 {
   restore(context, dependency.m_path);
   restore(context, dependency.m_line);
   restore(context, dependency.m_column);
 }
Member Data Documentation
unsigned lm_file_dependency::m_column private
Definition at line 114 of file library_manager.hpp.
Referenced by column(), print(), and set_column().
unsigned lm_file_dependency::m_line private
Definition at line 113 of file library_manager.hpp.
Referenced by line(), print(), and set_line().
std::string lm_file_dependency::m_path private
Definition at line 112 of file library_manager.hpp.
Referenced by path(), path_full(), print(), and set_path().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp