Visible: NRMat< T > Class Template Reference
NRMat< T > Class Template Reference
#include <include/analysis/nrutil_nr.h>
Public Member Functions
NRMat ()
NRMat (int n, int m)
NRMat (const T &a, int n, int m)
NRMat (const T *a, int n, int m)
NRMat (const NRMat &rhs)
NRMat & operator= (const NRMat &rhs)
NRMat & operator= (const T &a)
T * operator[] (const int i)
const T * operator[] (const int i) const
int nrows () const
int ncols () const
~NRMat ()
Private Attributes
int nn
int mm
T ** v
Detailed Description
template<class T>
class NRMat< T >
Definition at line 176 of file nrutil_nr.h.
Constructor & Destructor Documentation
template<class T > NRMat< T >::NRMat ()
Definition at line 197 of file nrutil_nr.h.
template<class T > NRMat< T >::NRMat (int n, int m)
Definition at line 200 of file nrutil_nr.h.
References NRMat< T >::v.
template<class T > NRMat< T >::NRMat (const T & a, int n, int m)
Definition at line 208 of file nrutil_nr.h.
References NRMat< T >::v.
template<class T > NRMat< T >::NRMat (const T * a, int n, int m)
Definition at line 220 of file nrutil_nr.h.
References NRMat< T >::v.
template<class T > NRMat< T >::NRMat (const NRMat< T > & rhs)
Definition at line 232 of file nrutil_nr.h.
References NRMat< T >::mm, NRMat< T >::nn, and NRMat< T >::v.
template<class T > NRMat< T >::~NRMat ()
Definition at line 304 of file nrutil_nr.h.
Member Function Documentation
template<class T > int NRMat< T >::ncols () const inline
Definition at line 298 of file nrutil_nr.h.
Referenced by NR::svbksb(), and NR::svdcmp().
template<class T > int NRMat< T >::nrows () const inline
Definition at line 292 of file nrutil_nr.h.
Referenced by NR::svbksb(), and NR::svdcmp().
template<class T > NRMat< T > & NRMat< T >::operator= (const NRMat< T > & rhs)
Definition at line 244 of file nrutil_nr.h.
References NRMat< T >::mm, and NRMat< T >::nn.
template<class T > NRMat< T > & NRMat< T >::operator= (const T & a)
Definition at line 271 of file nrutil_nr.h.
template<class T > T * NRMat< T >::operator[] (const int i) inline
Definition at line 280 of file nrutil_nr.h.
template<class T > const T * NRMat< T >::operator[] (const int i) const inline
Definition at line 286 of file nrutil_nr.h.
Member Data Documentation
template<class T> int NRMat< T >::mm private
Definition at line 179 of file nrutil_nr.h.
Referenced by NRMat< T >::NRMat(), and NRMat< T >::operator=().
template<class T> int NRMat< T >::nn private
Definition at line 178 of file nrutil_nr.h.
Referenced by NRMat< T >::NRMat(), and NRMat< T >::operator=().
template<class T> T** NRMat< T >::v private
Definition at line 180 of file nrutil_nr.h.
Referenced by NRMat< T >::NRMat().
The documentation for this class was generated from the following file:
include/analysis/nrutil_nr.h