Visible: timer Class Reference
timer Class Reference
#include <include/stlplus/timer.hpp>
Public Member Functions
timer (void)
~timer (void)
void reset (void)
float elapsed (void) const
float cpu (void) const
std::string text (void) const
Private Attributes
clock_t m_clock
time_t m_time
Friends
otext & operator<< (otext &, const timer &)
Detailed Description
Definition at line 18 of file timer.hpp.
Constructor & Destructor Documentation
timer::timer (void)
Definition at line 13 of file timer.cpp.
References reset().
 {
   reset();
 }
timer::~timer (void)
Definition at line 18 of file timer.cpp.
 {
 }
Member Function Documentation
float timer::cpu (void) const
Definition at line 28 of file timer.cpp.
References m_clock.
Referenced by text().
 {
   return ((float)(clock() - m_clock)) / ((float)CLOCKS_PER_SEC);
 }
float timer::elapsed (void) const
Definition at line 33 of file timer.cpp.
References m_time.
 {
   return ((float)(time(0) - m_time));
 }
void timer::reset (void)
Definition at line 22 of file timer.cpp.
References m_clock, and m_time.
Referenced by main(), and timer().
 {
   m_clock = clock();
   m_time = time(0);
 }
std::string timer::text (void) const
Definition at line 38 of file timer.cpp.
References cpu(), dformat(), display_time(), and m_time.
Referenced by main(), and operator<<().
 {
   return dformat("%4.2fs CPU, %s elapsed", cpu(), display_time(time(0)-m_time).c_str());
 }
Friends And Related Function Documentation
otext& operator<< (otext & , const timer &) friend
Definition at line 43 of file timer.cpp.
 {
   return str << t.text();
 }
Member Data Documentation
clock_t timer::m_clock private
Definition at line 21 of file timer.hpp.
Referenced by cpu(), and reset().
time_t timer::m_time private
Definition at line 22 of file timer.hpp.
Referenced by elapsed(), reset(), and text().
The documentation for this class was generated from the following files:
include/stlplus/timer.hpp
include/stlplus/timer.cpp