Visible: TCP_client_data Class Reference
TCP_client_data Class Reference
Public Member Functions
TCP_client_data (void)
~TCP_client_data (void)
TCP_client_data (const TCP_client_data &client)
TCP_client_data & operator= (const TCP_client_data &client)
void set_error (int error)
int error (void) const
std::string message (void) const
bool initialise (const std::string &address, unsigned short port, unsigned int timeout=0)
bool initialised (void) const
unsigned long address (void) const
unsigned short port (void) const
bool send_ready (unsigned wait)
bool send (std::string &data)
bool receive_ready (unsigned wait)
bool receive (std::string &data)
bool close (void)
Private Attributes
TCP_socket m_socket
unsigned long m_address
unsigned short m_port
Detailed Description
Definition at line 697 of file tcp.cpp.
Constructor & Destructor Documentation
TCP_client_data::TCP_client_data (void) inline
Definition at line 706 of file tcp.cpp.
References m_address, and m_port.
     {
       m_address = 0;
       m_port = 0;
     }
TCP_client_data::~TCP_client_data (void) inline
Definition at line 712 of file tcp.cpp.
References close().
     {
       close();
     }
TCP_client_data::TCP_client_data (const TCP_client_data & client) inline
Definition at line 717 of file tcp.cpp.
References m_address, and m_port.
     {
       m_address = 0;
       m_port = 0;
       *this = client;
     }
Member Function Documentation
unsigned long TCP_client_data::address (void) const inline
Definition at line 817 of file tcp.cpp.
References m_address.
Referenced by TCP_client::address().
     {
       return m_address;
     }
bool TCP_client_data::close (void) inline
Definition at line 847 of file tcp.cpp.
References TCP_socket::close(), m_address, m_port, and m_socket.
Referenced by TCP_client::close(), initialise(), operator=(), and ~TCP_client_data().
     {
       m_address = 0;
       m_port = 0;
       return m_socket.close();
     }
int TCP_client_data::error (void) const inline
Definition at line 738 of file tcp.cpp.
References TCP_socket::error(), and m_socket.
Referenced by TCP_client::error(), initialise(), otext::operator bool(), obuff::set_error(), and ibuff::set_error().
     {
       return m_socket.error();
     }
bool TCP_client_data::initialise (const std::string & address, unsigned short port, unsigned int timeout = 0) inline
Definition at line 749 of file tcp.cpp.
References close(), ERRNO, error(), HERRNO, TCP_socket::initialise(), m_address, m_port, m_socket, TCP_socket::send_ready(), set_error(), TCP_socket::socket(), and SOCKET_ERROR.
Referenced by TCP_client::initialise().
     {
       close();
       bool result = true;
       if (!m_socket.initialise())
       {
         result = false;
       }
       else
       {
         // this DOES lookup IP address names as well (not according to MS help !!)
         hostent* host_info = gethostbyname(address.c_str());
         if (!host_info)
         {
           set_error(HERRNO);
           result = false;
         }
         else
         {
           sockaddr connect_data;
           connect_data.sa_family = host_info->h_addrtype;
           unsigned short network_port = htons((unsigned short)port);
           memcpy(&connect_data.sa_data[0], &network_port, sizeof(network_port));
           memcpy(&connect_data.sa_data[2], host_info->h_addr, host_info->h_length);
           // fill in our copy of the server address and port too
           memcpy(&m_port, &connect_data.sa_data[0], sizeof(m_port));
           m_port = ntohs(m_port);
           memcpy(&m_address, &connect_data.sa_data[2], sizeof(m_address));
           m_address = ntohl(m_address);
           // the socket is non-blocking, so connect will almost certainly fail with EINPROGRESS
           if (connect(m_socket.socket(), &connect_data, sizeof(connect_data)) == SOCKET_ERROR)
           {
             int error = ERRNO;
             if (error == EINPROGRESS || error == EWOULDBLOCK)
             {
               // the Linux docs say detect completion by selecting the socket for writing
               // TODO - do something more sensible with the timeout
               if (!timeout)
               {
                 // the connection has been initialised correctly, but not connected yet.
                 // do NOT wait for the connection in this non-blocking initialise
               }
               else if (!m_socket.send_ready(timeout))
               {
                 // TODO - how do I get the real error?
                 set_error(error);
                 result = false;
               }
             }
             else
             {
               set_error(error);
               result = false;
             }
           }
         }
       }
       if (!result) close();
       return result;
     }
bool TCP_client_data::initialised (void) const inline
Definition at line 812 of file tcp.cpp.
References TCP_socket::initialised(), and m_socket.
Referenced by TCP_client::initialised().
     {
       return m_socket.initialised();
     }
std::string TCP_client_data::message (void) const inline
Definition at line 743 of file tcp.cpp.
References m_socket, and TCP_socket::message().
Referenced by TCP_client::message().
     {
       return m_socket.message();
     }
TCP_client_data& TCP_client_data::operator= (const TCP_client_data & client) inline
Definition at line 724 of file tcp.cpp.
References close(), m_address, m_port, and m_socket.
     {
       close();
       m_socket = client.m_socket;
       m_address = client.m_address;
       m_port = client.m_port;
       return *this;
     }
unsigned short TCP_client_data::port (void) const inline
Definition at line 822 of file tcp.cpp.
References m_port.
Referenced by TCP_client::port().
     {
       return m_port;
     }
bool TCP_client_data::receive (std::string & data) inline
Definition at line 842 of file tcp.cpp.
References m_socket, and TCP_socket::receive().
Referenced by TCP_client::receive().
     {
       return m_socket.receive(data);
     }
bool TCP_client_data::receive_ready (unsigned wait) inline
Definition at line 837 of file tcp.cpp.
References m_socket, and TCP_socket::receive_ready().
Referenced by TCP_client::receive_ready().
     {
       return m_socket.receive_ready(wait);
     }
bool TCP_client_data::send (std::string & data) inline
Definition at line 832 of file tcp.cpp.
References m_socket, and TCP_socket::send().
Referenced by TCP_client::send().
     {
       return m_socket.send(data);
     }
bool TCP_client_data::send_ready (unsigned wait) inline
Definition at line 827 of file tcp.cpp.
References m_socket, and TCP_socket::send_ready().
Referenced by TCP_client::connected(), and TCP_client::send_ready().
     {
       return m_socket.send_ready(wait);
     }
void TCP_client_data::set_error (int error) inline
Definition at line 733 of file tcp.cpp.
References m_socket, and TCP_socket::set_error().
Referenced by initialise().
     {
       m_socket.set_error(error);
     }
Member Data Documentation
unsigned long TCP_client_data::m_address private
Definition at line 701 of file tcp.cpp.
Referenced by address(), close(), initialise(), operator=(), and TCP_client_data().
unsigned short TCP_client_data::m_port private
Definition at line 702 of file tcp.cpp.
Referenced by close(), initialise(), operator=(), port(), and TCP_client_data().
TCP_socket TCP_client_data::m_socket private
Definition at line 700 of file tcp.cpp.
Referenced by close(), error(), initialise(), initialised(), message(), operator=(), receive(), receive_ready(), send(), send_ready(), and set_error().
The documentation for this class was generated from the following file:
include/stlplus/tcp.cpp