Visible: TCP_client Class Reference
TCP_client Class Reference
#include <include/stlplus/tcp.hpp>
Public Member Functions
TCP_client (void)
TCP_client (const std::string &address, unsigned short port, unsigned int timeout=0)
~TCP_client (void)
TCP_client (const TCP_client &)
TCP_client & operator= (const TCP_client &)
int error (void) const
std::string message (void) const
bool initialise (const std::string &address, unsigned short port, unsigned int timeout=0)
bool initialised (void) const
bool connected (void)
unsigned long address (void) const
unsigned short port (void) const
bool send_ready (unsigned wait=0)
bool send (std::string &data)
bool receive_ready (unsigned wait=0)
bool receive (std::string &data)
bool close (void)
Private Attributes
smart_ptr< TCP_client_data > m_data
Friends
class TCP_client_data
Detailed Description
Definition at line 109 of file tcp.hpp.
Constructor & Destructor Documentation
TCP_client::TCP_client (void)
Definition at line 859 of file tcp.cpp.
                            : m_data(TCP_client_data())
 {
 }
TCP_client::TCP_client (const std::string & address, unsigned short port, unsigned int timeout = 0)
Definition at line 863 of file tcp.cpp.
References initialise().
                                                                                           : m_data(TCP_client_data())
 {
   initialise(address,port,timeout);
 }
TCP_client::~TCP_client (void)
Definition at line 868 of file tcp.cpp.
 {
 }
TCP_client::TCP_client (const TCP_client & client)
Definition at line 872 of file tcp.cpp.
 {
   *this = client;
 }
Member Function Documentation
unsigned long TCP_client::address (void) const
Definition at line 909 of file tcp.cpp.
References TCP_client_data::address(), and m_data.
 {
   return m_data->address();
 }
bool TCP_client::close (void)
Definition at line 939 of file tcp.cpp.
References TCP_client_data::close(), and m_data.
 {
   return m_data->close();
 }
bool TCP_client::connected (void)
Definition at line 903 of file tcp.cpp.
References m_data, and TCP_client_data::send_ready().
 {
 //  return m_data->connected();
   return m_data->send_ready(0);
 }
int TCP_client::error (void) const
Definition at line 883 of file tcp.cpp.
References TCP_client_data::error(), and m_data.
 {
   return m_data->error();
 }
bool TCP_client::initialise (const std::string & address, unsigned short port, unsigned int timeout = 0)
Definition at line 893 of file tcp.cpp.
References TCP_client_data::initialise(), and m_data.
Referenced by TCP_client().
 {
   return m_data->initialise(address, port, timeout);
 }
bool TCP_client::initialised (void) const
Definition at line 898 of file tcp.cpp.
References TCP_client_data::initialised(), and m_data.
 {
   return m_data->initialised();
 }
std::string TCP_client::message (void) const
Definition at line 888 of file tcp.cpp.
References m_data, and TCP_client_data::message().
 {
   return m_data->message();
 }
TCP_client & TCP_client::operator= (const TCP_client & client)
Definition at line 877 of file tcp.cpp.
References m_data.
 {
   m_data = client.m_data;
   return *this;
 }
unsigned short TCP_client::port (void) const
Definition at line 914 of file tcp.cpp.
References m_data, and TCP_client_data::port().
 {
   return m_data->port();
 }
bool TCP_client::receive (std::string & data)
Definition at line 934 of file tcp.cpp.
References m_data, and TCP_client_data::receive().
 {
   return m_data->receive(data);
 }
bool TCP_client::receive_ready (unsigned wait = 0)
Definition at line 929 of file tcp.cpp.
References m_data, and TCP_client_data::receive_ready().
 {
   return m_data->receive_ready(wait);
 }
bool TCP_client::send (std::string & data)
Definition at line 924 of file tcp.cpp.
References m_data, and TCP_client_data::send().
 {
   return m_data->send(data);
 }
bool TCP_client::send_ready (unsigned wait = 0)
Definition at line 919 of file tcp.cpp.
References m_data, and TCP_client_data::send_ready().
 {
   return m_data->send_ready(wait);
 }
Friends And Related Function Documentation
friend class TCP_client_data friend
Definition at line 133 of file tcp.hpp.
Member Data Documentation
smart_ptr<TCP_client_data> TCP_client::m_data private
Definition at line 134 of file tcp.hpp.
Referenced by address(), close(), connected(), error(), initialise(), initialised(), message(), operator=(), port(), receive(), receive_ready(), send(), and send_ready().
The documentation for this class was generated from the following files:
include/stlplus/tcp.hpp
include/stlplus/tcp.cpp