Visible: LLSQ Class Reference
LLSQ Class Reference
#include <include/util/linlsq.h>
Public Member Functions
LLSQ ()
void clear ()
void add (double x, double y)
void add (double x, double y, double weight)
void add (const LLSQ &other)
void remove (double x, double y)
int32 count () const
double m () const
double c (double m) const
double rms (double m, double c) const
double pearson () const
rc2Fvector mean_point () const
double rms_orth (const rc2Fvector &dir) const
rc2Fvector vector_fit () const
rcRadian vector_fit_angle () const
double covariance () const
double x_variance () const
double y_variance () const
Private Attributes
double total_weight
double sigx
double sigy
double sigxx
double sigxy
double sigyy
Detailed Description
Definition at line 11 of file linlsq.h.
Constructor & Destructor Documentation
LLSQ::LLSQ () inline
Definition at line 14 of file linlsq.h.
          {  // constructor
     clear();  // set to zeros
   }
Member Function Documentation
void LLSQ::add (double x, double y)
Definition at line 29 of file linlsq.cpp.
References sigx, sigxx, sigxy, sigy, sigyy, and total_weight.
Referenced by MedianOfCircularValues().
                                  {          // add an element
   total_weight++;                           // count elements
   sigx += x;                     // update accumulators
   sigy += y;
   sigxx += x * x;
   sigxy += x * y;
   sigyy += y * y;
 }
void LLSQ::add (double x, double y, double weight)
Definition at line 38 of file linlsq.cpp.
References sigx, sigxx, sigxy, sigy, sigyy, and total_weight.
{
   total_weight += weight;
   sigx += x * weight;                     // update accumulators
   sigy += y * weight;
   sigxx += x * x * weight;
   sigxy += x * y * weight;
   sigyy += y * y * weight;
 }
void LLSQ::add (const LLSQ & other)
Definition at line 47 of file linlsq.cpp.
References sigx, sigxx, sigxy, sigy, sigyy, and total_weight.
{
   total_weight += other.total_weight;
   sigx += other.sigx;                     // update accumulators
   sigy += other.sigy;
   sigxx += other.sigxx;
   sigxy += other.sigxy;
   sigyy += other.sigyy;
 }
double LLSQ::c (double m) const
Definition at line 97 of file linlsq.cpp.
References sigx, sigy, and total_weight.
                              {          // get constant
   if (total_weight > 0.0)
     return (sigy - m * sigx) / total_weight;
   else
     return 0;                    // too little
 }
void LLSQ::clear (void)
Definition at line 13 of file linlsq.cpp.
References sigx, sigxx, sigxy, sigy, sigyy, and total_weight.
                  {  // initialize
   total_weight = 0.0;                         // no elements
   sigx = 0.0;                      // update accumulators
   sigy = 0.0;
   sigxx = 0.0;
   sigxy = 0.0;
   sigyy = 0.0;
 }
int32 LLSQ::count (void) const inline
Definition at line 27 of file linlsq.h.
                       {  // no of elements
     return static_cast<int>(total_weight + 0.5);
   }
double LLSQ::covariance () const inline
Definition at line 60 of file linlsq.h.
Referenced by m(), pearson(), rms_orth(), and vector_fit_angle().
{
     if (total_weight > 0.0)
       return (sigxy - sigx * sigy / total_weight) / total_weight;
     else
       return 0.0;
   }
double LLSQ::m () const
Definition at line 81 of file linlsq.cpp.
References covariance(), and x_variance().
                      {  // get gradient
   double covar = covariance();
   double x_var = x_variance();
   if (x_var != 0.0)
     return covar / x_var;
   else
     return 0.0;                    // too little
 }
rc2Fvector LLSQ::mean_point () const
Definition at line 147 of file linlsq.cpp.
References sigx, sigy, and total_weight.
{
   if (total_weight > 0.0) {
     return rc2Fvector(sigx / total_weight, sigy / total_weight);
   } else {
     return rc2Fvector(0.0f, 0.0f);
   }
 }
double LLSQ::pearson () const
Definition at line 134 of file linlsq.cpp.
References covariance(), x_variance(), and y_variance().
                            {  // get correlation
   double r = 0.0;                  // Correlation is 0 if insufficent data.
   double covar = covariance();
   if (covar != 0.0) {
     double var_product = x_variance()  * y_variance();
     if (var_product > 0.0)
       r = covar / sqrt(var_product);
   }
   return r;
 }
void LLSQ::remove (double x, double y)
Definition at line 63 of file linlsq.cpp.
References sigx, sigxx, sigxy, sigy, sigyy, and total_weight.
                                     {          // delete an element
     assert (total_weight > 0.0);                       // illegal
   total_weight--;                           // count elements
   sigx -= x;                     // update accumulators
   sigy -= y;
   sigxx -= x * x;
   sigxy -= x * y;
   sigyy -= y * y;
 }
double LLSQ::rms (double m, double c) const
Definition at line 111 of file linlsq.cpp.
References sigx, sigxx, sigxy, sigy, sigyy, and total_weight.
                                           {          // get error
   double error;                  // total error
   if (total_weight > 0) {
     error = sigyy + m * (m * sigxx + 2 * (c * sigx - sigxy)) + c *
             (total_weight * c - 2 * sigy);
     if (error >= 0)
       error = sqrt(error / total_weight);  // sqrt of mean
     else
       error = 0;
   } else {
     error = 0;                   // too little
   }
   return error;
 }
double LLSQ::rms_orth (const rc2Fvector & dir) const
Definition at line 177 of file linlsq.cpp.
References covariance(), rc2dVector< T >::perpendicular(), rc2dVector< T >::unit(), rc2dVector< T >::x(), x_variance(), rc2dVector< T >::y(), and y_variance().
{
     rc2Fvector v = dir.perpendicular ();
     v = v.unit ();
   return sqrt(v.x() * v.x() * x_variance() +
               2 * v.x() * v.y() * covariance() +
               v.y() * v.y() * y_variance());
 }
rc2Fvector LLSQ::vector_fit () const
Definition at line 244 of file linlsq.cpp.
References cos(), sin(), and vector_fit_angle().
 {
     rcRadian theta = vector_fit_angle ();
     rc2Fvector result(cos(theta), sin(theta));
 }
rcRadian LLSQ::vector_fit_angle () const
Definition at line 234 of file linlsq.cpp.
References atan2(), covariance(), x_variance(), and y_variance().
Referenced by vector_fit().
 {
   double x_var = x_variance();
   double y_var = y_variance();
   double covar = covariance();
   double theta = 0.5 * atan2(2.0 * covar, x_var - y_var);
     return rcRadian(theta);
  }
double LLSQ::x_variance () const inline
Definition at line 66 of file linlsq.h.
Referenced by m(), MedianOfCircularValues(), pearson(), rms_orth(), and vector_fit_angle().
{
     if (total_weight > 0.0)
       return (sigxx - sigx * sigx / total_weight) / total_weight;
     else
       return 0.0;
   }
double LLSQ::y_variance () const inline
Definition at line 72 of file linlsq.h.
Referenced by MedianOfCircularValues(), pearson(), rms_orth(), and vector_fit_angle().
{
     if (total_weight > 0.0)
       return (sigyy - sigy * sigy / total_weight) / total_weight;
     else
       return 0.0;
   }
Member Data Documentation
double LLSQ::sigx private
Definition at line 81 of file linlsq.h.
Referenced by add(), c(), clear(), mean_point(), remove(), and rms().
double LLSQ::sigxx private
Definition at line 83 of file linlsq.h.
Referenced by add(), clear(), remove(), and rms().
double LLSQ::sigxy private
Definition at line 84 of file linlsq.h.
Referenced by add(), clear(), remove(), and rms().
double LLSQ::sigy private
Definition at line 82 of file linlsq.h.
Referenced by add(), c(), clear(), mean_point(), remove(), and rms().
double LLSQ::sigyy private
Definition at line 85 of file linlsq.h.
Referenced by add(), clear(), remove(), and rms().
double LLSQ::total_weight private
Definition at line 80 of file linlsq.h.
Referenced by add(), c(), clear(), mean_point(), remove(), and rms().
The documentation for this class was generated from the following files:
include/util/linlsq.h
src/util/code/linlsq.cpp