Visible: rcCellInfoWidget Class Reference
rcCellInfoWidget Class Reference
#include <include/visUI/rc_cellinfowidget.h>
Public Slots
void updateCursorTime (const rcTimestamp &time)
void updateState (rcExperimentState state)
void updateDisplay (void)
void updateSettings (void)
Public Member Functions
rcCellInfoWidget (QWidget *parent)
~rcCellInfoWidget ()
Private Member Functions
void updateTrackDisplay (void)
Private Attributes
Q3BoxLayout * mTopLayout
Q3BoxLayout * mDataLayout
QLabel * mDataName
QLabel * mDataValue
QLabel * mDataComment
rcTimestamp mLastUpdateTime
Detailed Description
Definition at line 24 of file rc_cellinfowidget.h.
Constructor & Destructor Documentation
rcCellInfoWidget::rcCellInfoWidget (QWidget * parent)
Definition at line 128 of file rc_cellinfowidget.cpp.
References cBaseCaption(), cWidgetBackgroundMode, cWordBreakAlignment, rcModelDomain::getModelDomain(), mDataComment, mDataLayout, mDataName, mDataValue, mTopLayout, updateCursorTime(), updateDisplay(), updateSettings(), updateState(), and updateTrackDisplay().
     : QWidget( parent , "cellInfoWidget" )
 {
     setCaption( cBaseCaption );
     setMinimumSize( 400, 160 );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     mTopLayout = new Q3VBoxLayout( this );
     mDataLayout = new Q3HBoxLayout( mTopLayout );
     // Name/value font
     QFont textFont;
     textFont.setPointSize( 10 );
     textFont.setWeight( QFont::Normal );
     mDataLayout->addSpacing( 10 );
     // Track name
     mDataName = new QLabel( "\t" , this );
     mDataName->setAlignment( cWordBreakAlignment );
     mDataName->setFont( textFont );
     QToolTip::add( mDataName, "Data field name" );
     mDataLayout->addWidget( mDataName );
     mDataLayout->addSpacing( 10 );
     // Track value
     mDataValue = new QLabel( "\t" , this );
     mDataValue->setAlignment( cWordBreakAlignment );
     mDataValue->setFont( textFont );
     QToolTip::add( mDataValue, "Data field value" );
     mDataLayout->addWidget( mDataValue );
     mDataLayout->addSpacing( 10 );
     // Track comment
     mDataComment = new QLabel( "\t" , this );
     mDataComment->setAlignment( cWordBreakAlignment );
     mDataComment->setFont( textFont );
     QToolTip::add( mDataComment, "Exportability" );
     mDataLayout->addWidget( mDataComment );
     mDataLayout->addSpacing( 10 );
     mDataLayout->addStretch();
     // connect to some domain signals
     connect( domain , SIGNAL( cursorTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateCursorTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateDisplay( void ) ) ,
              this   , SLOT( updateDisplay( void ) ) );
     connect( domain , SIGNAL( updateSettings( void ) ) ,
              this   , SLOT( updateSettings( void ) ) );
     // Use a fixed color to erase background, it's faster than default widget erase pixmap
     QColor backgroundColor = QColor( 238, 238, 238 );
     setBackgroundMode( cWidgetBackgroundMode, cWidgetBackgroundMode );
     setPaletteBackgroundColor( backgroundColor );
     updateTrackDisplay();
 }
rcCellInfoWidget::~rcCellInfoWidget ()
Definition at line 189 of file rc_cellinfowidget.cpp.
References mDataName, and mDataValue.
 {
     QToolTip::remove( mDataName );
     QToolTip::remove( mDataValue );
 }
Member Function Documentation
void rcCellInfoWidget::updateCursorTime (const rcTimestamp & time) slot
Definition at line 195 of file rc_cellinfowidget.cpp.
References rmUnused, and updateTrackDisplay().
Referenced by rcCellInfoWidget().
 {
     rmUnused( time );
     updateTrackDisplay();
 }
void rcCellInfoWidget::updateDisplay (void) slot
Definition at line 207 of file rc_cellinfowidget.cpp.
References updateTrackDisplay().
Referenced by rcCellInfoWidget().
 {
     updateTrackDisplay();
 }
void rcCellInfoWidget::updateSettings (void) slot
Definition at line 212 of file rc_cellinfowidget.cpp.
References updateTrackDisplay().
Referenced by rcCellInfoWidget().
 {
     updateTrackDisplay();
 }
void rcCellInfoWidget::updateState (rcExperimentState state) slot
Definition at line 201 of file rc_cellinfowidget.cpp.
References rmUnused, and updateTrackDisplay().
Referenced by rcCellInfoWidget().
 {
     rmUnused( state );
     updateTrackDisplay();
 }
void rcCellInfoWidget::updateTrackDisplay (void) private
Definition at line 222 of file rc_cellinfowidget.cpp.
References countDisplayableGroups(), cZeroTime, eGroupSemanticsBodyMeasurements, rcModelDomain::getCursorTime(), rcTrack::getDescription(), rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getName(), rcExperiment::getNTrackGroups(), rcTrackGroup::getNTracks(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), getTrackValue(), rcTrackGroup::getType(), rcTrack::isExportable(), rcTrackManager::isTrackGroupEnabled(), mDataComment, mDataName, mDataValue, and mLastUpdateTime.
Referenced by rcCellInfoWidget(), updateCursorTime(), updateDisplay(), updateSettings(), and updateState().
 {
     // determine the time to display
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcTimestamp timeToDisplay  = domain->getCursorTime();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     int nTrackGroups = experiment->getNTrackGroups();
     // Count displayable groups and get caption
     QString caption;
     countDisplayableGroups( caption );
     setCaption( caption );
     QString name, value, comment;
     if ( timeToDisplay >= cZeroTime ) {
         // Gather all data track values
         for (int i = 0; i < nTrackGroups; ++i)
         {
             rcTrackGroup* trackGroup = experiment->getTrackGroup( i );
             if ( tmp->isTrackGroupEnabled( i ) ) {
                 // Only display data from cell info groups
                 if ( trackGroup->getType() == eGroupSemanticsBodyMeasurements ) {
                     int nTracks = trackGroup->getNTracks();
                     name += trackGroup->getName();
                     name += "\n";
                     value += "\n";
                     comment += "\n";
                     for ( int j = 0; j < nTracks; j++)
                     {
                         rcTrack* track = trackGroup->getTrack( j );
                         // Track name
                         QString tn;
                         tn.sprintf( " %s\n", track->getDescription() );
                         name += tn;
                         // Track value
                         QString tv;
                         getTrackValue( track, timeToDisplay, tv );
                         value += tv;
                         // Track comment
                         if ( track->isExportable() ) {
                             // Track is exportable to file
                             comment += "E\n";
                         }
                         else
                             comment += "\n";
                     }
             }
             }
         }
     }
     // Update texts
     mDataName->setText( name );
     mDataValue->setText( value );
     mDataComment->setText( comment );
     mLastUpdateTime = timeToDisplay;
 }
Member Data Documentation
QLabel* rcCellInfoWidget::mDataComment private
Definition at line 47 of file rc_cellinfowidget.h.
Referenced by rcCellInfoWidget(), and updateTrackDisplay().
Q3BoxLayout* rcCellInfoWidget::mDataLayout private
Definition at line 44 of file rc_cellinfowidget.h.
Referenced by rcCellInfoWidget().
QLabel* rcCellInfoWidget::mDataName private
Definition at line 45 of file rc_cellinfowidget.h.
Referenced by rcCellInfoWidget(), updateTrackDisplay(), and ~rcCellInfoWidget().
QLabel* rcCellInfoWidget::mDataValue private
Definition at line 46 of file rc_cellinfowidget.h.
Referenced by rcCellInfoWidget(), updateTrackDisplay(), and ~rcCellInfoWidget().
rcTimestamp rcCellInfoWidget::mLastUpdateTime private
Definition at line 48 of file rc_cellinfowidget.h.
Referenced by updateTrackDisplay().
Q3BoxLayout* rcCellInfoWidget::mTopLayout private
Definition at line 43 of file rc_cellinfowidget.h.
Referenced by rcCellInfoWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_cellinfowidget.h
src/visible/qt/rc_cellinfowidget.cpp