Visible: rcMovieFileFormat2 Class Reference
rcMovieFileFormat2 Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileFormat2 ()
rcMovieFileFormat2 (movieFormatRev rev)
rcMovieFileFormat2 (const rcSharedFrameBufPtr &frame, movieFormatRev rev=movieFormatInvalid)
bool write (FILE *saveStream) const
void fixEndian ()
const uint32 & width () const
const uint32 & height () const
const uint32 & rowUpdate () const
const double & averageFrameRate () const
const uint32 & frameCount () const
const int64 & baseTime () const
movieFormatRev rev () const
const char * magic () const
uint32 bytesInFrame () const
const uint16 & bom () const
const rcPixel & depth () const
const int64 & extensionOffset () const
void rowUpdate (const uint32 &f)
Mutators.
void averageFrameRate (const double &f)
void frameCount (const uint32 &f)
void baseTime (const int64 &t)
void extensionOffset (const int64 &o)
void depth (const rcPixel &d)
Private Attributes
rcMovieFileIdentifier mId
uint16 mBom
uint32 mWidth
uint32 mHeight
rcPixel mDepth
uint32 mRowUpdate
double mAverageFrameRate
uint32 mFrameCount
int64 mBaseTime
int64 mExtensionOffset
Detailed Description
Definition at line 164 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileFormat2::rcMovieFileFormat2 ()
Definition at line 162 of file rc_moviefileformat.cpp.
                                        :
         mId(movieFormatInvalid), mBom(rfPlatformByteOrderMark()), mWidth(0), mHeight(0), mDepth(rcPixel8), mRowUpdate(0),
         mAverageFrameRate(0.0), mFrameCount(0), mBaseTime(0), mExtensionOffset(0)
 {
}
rcMovieFileFormat2::rcMovieFileFormat2 (movieFormatRev rev)
Definition at line 168 of file rc_moviefileformat.cpp.
                                                          :
         mId(r), mBom(rfPlatformByteOrderMark()), mWidth(0), mHeight(0), mDepth(rcPixel8), mRowUpdate(0),
         mAverageFrameRate(0.0), mFrameCount(0), mBaseTime(0), mExtensionOffset(0)
 {
}
rcMovieFileFormat2::rcMovieFileFormat2 (const rcSharedFrameBufPtr & frame, movieFormatRev rev = movieFormatInvalid)
Definition at line 174 of file rc_moviefileformat.cpp.
                                                            :
         mId(r), mBom(rfPlatformByteOrderMark()), mWidth(frame->width()), mHeight(frame->height()),
         mDepth(frame->depth()), mRowUpdate(frame->rowUpdate()),
         mAverageFrameRate(0.0), mFrameCount(0), mBaseTime(frame->timestamp()._timestamp), mExtensionOffset(0)
 {
}
Member Function Documentation
const double& rcMovieFileFormat2::averageFrameRate () const inline
Definition at line 182 of file rc_moviefileformat.h.
References mAverageFrameRate.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcVideoCache::headerLoadRev2(), and operator<<().
 { return mAverageFrameRate; }
void rcMovieFileFormat2::averageFrameRate (const double & f) inline
Definition at line 194 of file rc_moviefileformat.h.
References mAverageFrameRate.
 { mAverageFrameRate = f; }
const int64& rcMovieFileFormat2::baseTime () const inline
Definition at line 184 of file rc_moviefileformat.h.
References mBaseTime.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcGenMovieFile::initHeader(), and operator<<().
 { return mBaseTime; }
void rcMovieFileFormat2::baseTime (const int64 & t) inline
Definition at line 196 of file rc_moviefileformat.h.
References mBaseTime.
 { mBaseTime = t; }
const uint16& rcMovieFileFormat2::bom () const inline
Definition at line 188 of file rc_moviefileformat.h.
References mBom.
Referenced by rcVideoCache::headerLoadRev2(), and operator<<().
 { return mBom; }
uint32 rcMovieFileFormat2::bytesInFrame () const inline
Definition at line 187 of file rc_moviefileformat.h.
References height(), and rowUpdate().
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcVideoCache::headerLoadRev2(), and rcEngineMovieSaver::saveHdlr().
 { return height() * rowUpdate(); }
const rcPixel& rcMovieFileFormat2::depth () const inline
Definition at line 189 of file rc_moviefileformat.h.
References mDepth.
Referenced by rcEngineMovieSaver::closeHdlr(), rcVideoCache::headerLoadRev2(), rcGenMovieFile::initHeader(), and operator<<().
 { return mDepth; }
void rcMovieFileFormat2::depth (const rcPixel & d) inline
Definition at line 198 of file rc_moviefileformat.h.
References mDepth.
 { mDepth = d; }
const int64& rcMovieFileFormat2::extensionOffset () const inline
Definition at line 190 of file rc_moviefileformat.h.
References mExtensionOffset.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcVideoCache::headerLoadRev2(), and operator<<().
 { return mExtensionOffset;}
void rcMovieFileFormat2::extensionOffset (const int64 & o) inline
Definition at line 197 of file rc_moviefileformat.h.
References mExtensionOffset.
 { mExtensionOffset = o; }
void rcMovieFileFormat2::fixEndian ()
Definition at line 198 of file rc_moviefileformat.cpp.
References ByteSwapN, eByteOrderBigEndian, rcMovieFileIdentifier::fixEndian(), mAverageFrameRate, mBaseTime, mBom, mDepth, mExtensionOffset, mFrameCount, mHeight, mId, mRowUpdate, mWidth, and rfPlatformByteOrder().
Referenced by rcVideoCache::headerLoadRev2(), and write().
 {
        // Header is always stored in big endian form
         if ( rfPlatformByteOrder() != eByteOrderBigEndian )
     {
         ByteSwapN (mBom);
         ByteSwapN (mWidth);
         ByteSwapN ( mDepth);
         ByteSwapN (mHeight);
         ByteSwapN (mRowUpdate);
         ByteSwapN (mAverageFrameRate);
         /* Values to allow proper navigation through the rest of the file.
          */
         ByteSwapN (mFrameCount);
         ByteSwapN (mBaseTime);
         ByteSwapN (mExtensionOffset); // Offset to start of extension headers
         mId.fixEndian ();  // Common to all formats
     }
 }
const uint32& rcMovieFileFormat2::frameCount () const inline
Definition at line 183 of file rc_moviefileformat.h.
References mFrameCount.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcVideoCache::headerLoadRev2(), operator<<(), and rcEngineMovieSaver::saveHdlr().
 { return mFrameCount; }
void rcMovieFileFormat2::frameCount (const uint32 & f) inline
Definition at line 195 of file rc_moviefileformat.h.
References mFrameCount.
 { mFrameCount = f; }
const uint32& rcMovieFileFormat2::height () const inline
Definition at line 180 of file rc_moviefileformat.h.
References mHeight.
Referenced by rcGenMovieFile::addFrame(), bytesInFrame(), rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcGenMovieFile::frameSize(), rcVideoCache::headerLoadRev2(), operator<<(), and rcEngineMovieSaver::saveHdlr().
 { return mHeight; }
const char* rcMovieFileFormat2::magic () const inline
Definition at line 186 of file rc_moviefileformat.h.
References rcMovieFileIdentifier::magic(), and mId.
 { return mId.magic(); }
movieFormatRev rcMovieFileFormat2::rev () const inline
Definition at line 185 of file rc_moviefileformat.h.
References mId, and rcMovieFileIdentifier::rev().
Referenced by rcEngineMovieSaver::closeHdlr(), and operator<<().
 { return mId.rev(); }
const uint32& rcMovieFileFormat2::rowUpdate () const inline
Definition at line 181 of file rc_moviefileformat.h.
References mRowUpdate.
Referenced by bytesInFrame(), rcVideoCache::headerLoadRev2(), rcGenMovieFile::initHeader(), and operator<<().
 { return mRowUpdate; }
void rcMovieFileFormat2::rowUpdate (const uint32 & f) inline
Mutators.
Definition at line 193 of file rc_moviefileformat.h.
References mRowUpdate.
 { mRowUpdate = f; }
const uint32& rcMovieFileFormat2::width () const inline
Definition at line 179 of file rc_moviefileformat.h.
References mWidth.
Referenced by rcGenMovieFile::addFrame(), rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcGenMovieFile::frameSize(), rcVideoCache::headerLoadRev2(), operator<<(), and rcEngineMovieSaver::saveHdlr().
 { return mWidth; }
bool rcMovieFileFormat2::write (FILE * saveStream) const
Definition at line 183 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), and rfPlatformByteOrder().
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), rcGenMovieFile::open(), and rcEngineMovieSaver::openHdlr().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileFormat2 *>(this)->fixEndian ();
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("MovieHdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
Member Data Documentation
double rcMovieFileFormat2::mAverageFrameRate private
Definition at line 210 of file rc_moviefileformat.h.
Referenced by averageFrameRate(), and fixEndian().
int64 rcMovieFileFormat2::mBaseTime private
Definition at line 215 of file rc_moviefileformat.h.
Referenced by baseTime(), and fixEndian().
uint16 rcMovieFileFormat2::mBom private
Definition at line 202 of file rc_moviefileformat.h.
Referenced by bom(), and fixEndian().
rcPixel rcMovieFileFormat2::mDepth private
Definition at line 208 of file rc_moviefileformat.h.
Referenced by depth(), and fixEndian().
int64 rcMovieFileFormat2::mExtensionOffset private
Definition at line 216 of file rc_moviefileformat.h.
Referenced by extensionOffset(), and fixEndian().
uint32 rcMovieFileFormat2::mFrameCount private
Definition at line 214 of file rc_moviefileformat.h.
Referenced by fixEndian(), and frameCount().
uint32 rcMovieFileFormat2::mHeight private
Definition at line 207 of file rc_moviefileformat.h.
Referenced by fixEndian(), and height().
rcMovieFileIdentifier rcMovieFileFormat2::mId private
Definition at line 201 of file rc_moviefileformat.h.
Referenced by fixEndian(), magic(), and rev().
uint32 rcMovieFileFormat2::mRowUpdate private
Definition at line 209 of file rc_moviefileformat.h.
Referenced by fixEndian(), and rowUpdate().
uint32 rcMovieFileFormat2::mWidth private
Definition at line 206 of file rc_moviefileformat.h.
Referenced by fixEndian(), and width().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp