Visible: rcDbDtParams Class Reference
rcDbDtParams Class Reference
#include <include/analysis/rc_dbdt.h>
Public Types
enum method { e2D2D, e1D2D, e1D1D, eEnd }
Public Member Functions
rcDbDtParams ()
bool validate (const rcWindow &src) const
const rcIPair & sample () const
void sample (rcIPair &sam)
const int32 maxSpeed () const
void maxSpeed (int32 s)
const rcIPair & search () const
void search (rcIPair &sea)
const rcIPair & target () const
void target (rcIPair &sam)
const bool debug () const
void debug (bool dog)
const double reckon () const
void reckon (double reckon)
const int32 method () const
void method (enum method m)
const rsCorrParams & corrParams () const
Private Attributes
rsCorrParams mCorr
double mReckon
rcIPair mSample
rcIPair mSearchSize
rcIPair mTargetSize
bool mDebug
enum method mMethod
Friends
ostream & operator<< (ostream &, const rcDbDtParams &)
Detailed Description
Definition at line 89 of file rc_dbdt.h.
Member Enumeration Documentation
enum rcDbDtParams::method
Enumerator
e2D2D
e1D2D
e1D1D
eEnd
Definition at line 97 of file rc_dbdt.h.
     {
       e2D2D,
       e1D2D,
       e1D1D,
       eEnd
     };
Constructor & Destructor Documentation
rcDbDtParams::rcDbDtParams () inline
Definition at line 93 of file rc_dbdt.h.
 : mSample (1,1), mSearchSize (9,9), mTargetSize (5,5), mDebug (false), mMethod (e2D2D) {}
Member Function Documentation
const rsCorrParams& rcDbDtParams::corrParams () const inline
Definition at line 136 of file rc_dbdt.h.
References mCorr.
 {return mCorr; }
const bool rcDbDtParams::debug () const inline
Definition at line 129 of file rc_dbdt.h.
References mDebug.
 { return mDebug; }
void rcDbDtParams::debug (bool dog) inline
Definition at line 130 of file rc_dbdt.h.
References mDebug.
 { mDebug = dog; }
const int32 rcDbDtParams::maxSpeed () const inline
Definition at line 122 of file rc_dbdt.h.
References mSearchSize, mTargetSize, and rcPair< T >::x().
 {return (mSearchSize.x()-mTargetSize.x())/2; }
void rcDbDtParams::maxSpeed (int32 s) inline
Definition at line 123 of file rc_dbdt.h.
References mSearchSize, and mTargetSize.
 {mSearchSize = mTargetSize + rcIPair (s,s) + rcIPair (s,s);}
const int32 rcDbDtParams::method () const inline
Definition at line 133 of file rc_dbdt.h.
References mMethod.
 { return mMethod; }
void rcDbDtParams::method (enum method m) inline
Definition at line 134 of file rc_dbdt.h.
References mMethod.
 { mMethod = m; }
const double rcDbDtParams::reckon () const inline
Definition at line 131 of file rc_dbdt.h.
References mReckon.
 { return mReckon; }
void rcDbDtParams::reckon (double reckon) inline
Definition at line 132 of file rc_dbdt.h.
References mReckon, and reckon().
Referenced by reckon().
 { mReckon = reckon; }
const rcIPair& rcDbDtParams::sample () const inline
Definition at line 119 of file rc_dbdt.h.
References mSample.
 {return mSample; }
void rcDbDtParams::sample (rcIPair & sam) inline
Definition at line 120 of file rc_dbdt.h.
References mSample.
 {mSample = sam;}
const rcIPair& rcDbDtParams::search () const inline
Definition at line 125 of file rc_dbdt.h.
References mSearchSize.
 {return mSearchSize; }
void rcDbDtParams::search (rcIPair & sea) inline
Definition at line 126 of file rc_dbdt.h.
References mSearchSize.
 {mSearchSize = sea;}
const rcIPair& rcDbDtParams::target () const inline
Definition at line 127 of file rc_dbdt.h.
References mTargetSize.
 {return mTargetSize; }
void rcDbDtParams::target (rcIPair & sam) inline
Definition at line 128 of file rc_dbdt.h.
References mTargetSize.
 {mTargetSize = sam;}
bool rcDbDtParams::validate (const rcWindow & src) const inline
Definition at line 107 of file rc_dbdt.h.
References rcRectangle< T >::contains(), rcRectangle< T >::height(), mSample, mSearchSize, mTargetSize, rcWindow::rectangle(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
   {
     bool flag = true;
     rcUIRect s (0, 0, uint32 (mSearchSize.x()), uint32 (mSearchSize.y()));
     rcUIRect t (0, 0, uint32 (mTargetSize.x()), uint32 (mTargetSize.y()));
     flag = s.contains (t);
     flag &= (src.rectangle().width() > uint32 (mSearchSize.x()) && src.rectangle().height() > uint32 (mSearchSize.y()));
     flag &= (mSample.x()  > 0 && mSample.y() > 0);
     flag &= (src.rectangle().width() > uint32 (mSample.x()) && src.rectangle().height() > uint32 (mSample.y()));
     return flag;
   };
Friends And Related Function Documentation
ostream& operator<< (ostream & , const rcDbDtParams &) friend
Member Data Documentation
rsCorrParams rcDbDtParams::mCorr private
Definition at line 141 of file rc_dbdt.h.
Referenced by corrParams().
bool rcDbDtParams::mDebug private
Definition at line 146 of file rc_dbdt.h.
Referenced by debug().
enum method rcDbDtParams::mMethod private
Definition at line 147 of file rc_dbdt.h.
Referenced by method().
double rcDbDtParams::mReckon private
Definition at line 142 of file rc_dbdt.h.
Referenced by reckon().
rcIPair rcDbDtParams::mSample private
Definition at line 143 of file rc_dbdt.h.
Referenced by sample(), and validate().
rcIPair rcDbDtParams::mSearchSize private
Definition at line 144 of file rc_dbdt.h.
Referenced by maxSpeed(), search(), and validate().
rcIPair rcDbDtParams::mTargetSize private
Definition at line 145 of file rc_dbdt.h.
Referenced by maxSpeed(), target(), and validate().
The documentation for this class was generated from the following file:
include/analysis/rc_dbdt.h