Visible: rcTrackGroupImpl Class Reference
rcTrackGroupImpl Class Reference
#include <include/visiCore/rc_trackgroupimpl.h>
Public Member Functions
rcTrackGroupImpl (const char *tag, const char *name, const char *description, rcGroupSemantics type)
virtual ~rcTrackGroupImpl ()
virtual const char * getTag (void) const
virtual const char * getName (void) const
virtual const char * getDescription (void) const
virtual rcGroupSemantics getType ()
virtual int getNTracks (void) const
virtual rcTrack * getTrack (int trackNo)
virtual rcWriter * createWriter (rcWriterType type, const char *tag, const char *name, const char *description, const char *formatString, uint32 sizeLimit, const rcRect &analysisRect)
virtual void release ()
Public Member Functions inherited from rcTrackGroup
virtual ~rcTrackGroup ()
Public Member Functions inherited from rcWriterGroup
virtual ~rcWriterGroup ()
Private Attributes
std::string _tag
std::string _name
std::string _description
deque< rcTrackImpl * > _tracks
rcGroupSemantics _type
Detailed Description
Definition at line 23 of file rc_trackgroupimpl.h.
Constructor & Destructor Documentation
rcTrackGroupImpl::rcTrackGroupImpl (const char * tag, const char * name, const char * description, rcGroupSemantics type) inline
Definition at line 27 of file rc_trackgroupimpl.h.
     {
         _tag = tag;
         _name = name;
         _description = description;
         _type = type;
     }
rcTrackGroupImpl::~rcTrackGroupImpl () virtual
Definition at line 16 of file rc_trackgroupimpl.cpp.
References release().
 {
     release();
 }
Member Function Documentation
rcWriter * rcTrackGroupImpl::createWriter (rcWriterType type, const char * tag, const char * name, const char * description, const char * formatString, uint32 sizeLimit, const rcRect & analysisRect) virtual
Implements rcWriterGroup.
Definition at line 22 of file rc_trackgroupimpl.cpp.
References _tracks, eGraphicsTrack, ePositionTrack, eScalarTrack, eVideoTrack, rmExceptionMacro, and rcTrackImpl::setAnalysisRect().
 {
     rcTrackImpl* track = 0;
     switch (type)
     {
         case eVideoTrack:       // track contains video frames
             track = new rcVideoTrackImpl( tag, name, description, formatString, sizeLimit );
             break;
         case eScalarTrack:      // track contains scalar data
             track = new rcScalarTrackImpl( tag , name , description, formatString, sizeLimit );
             break;
         case eGraphicsTrack:        // track contains graphigs visualization data
             track = new rcGraphicsTrackImpl( tag , name , description, formatString, sizeLimit );
             break;
         case ePositionTrack:    // track contains <x,y> position data
             track = new rcPositionTrackImpl( tag , name , description, formatString, sizeLimit );
             break;
         default:
       rmExceptionMacro (<< "unsupported track type" );
     }
     track->setAnalysisRect( analysisRect );
     _tracks.push_back( track );
     return track;
 }
virtual const char* rcTrackGroupImpl::getDescription (void) const inline virtual
Implements rcTrackGroup.
Definition at line 54 of file rc_trackgroupimpl.h.
     {
         return _description.c_str();
     }
virtual const char* rcTrackGroupImpl::getName (void) const inline virtual
Implements rcTrackGroup.
Definition at line 48 of file rc_trackgroupimpl.h.
     {
         return _name.c_str();
     }
virtual int rcTrackGroupImpl::getNTracks (void) const inline virtual
Implements rcTrackGroup.
Definition at line 66 of file rc_trackgroupimpl.h.
     {
         return _tracks.size();
     }
virtual const char* rcTrackGroupImpl::getTag (void) const inline virtual
Implements rcTrackGroup.
Definition at line 42 of file rc_trackgroupimpl.h.
     {
         return _tag.c_str();
     }
virtual rcTrack* rcTrackGroupImpl::getTrack (int trackNo) inline virtual
Implements rcTrackGroup.
Definition at line 72 of file rc_trackgroupimpl.h.
References rmAssertDebug.
     {
         rmAssertDebug( uint32(trackNo) < _tracks.size() );
         return _tracks[ trackNo ];
     }
virtual rcGroupSemantics rcTrackGroupImpl::getType (void) inline virtual
Implements rcTrackGroup.
Definition at line 60 of file rc_trackgroupimpl.h.
     {
         return _type;
     }
void rcTrackGroupImpl::release (void) virtual
Implements rcWriterGroup.
Definition at line 57 of file rc_trackgroupimpl.cpp.
References _tracks.
Referenced by ~rcTrackGroupImpl().
 {
     for ( uint32 i = 0; i < _tracks.size(); i++ ) {
         delete _tracks[i];
         _tracks[i] = 0;
     }
 }
Member Data Documentation
std::string rcTrackGroupImpl::_description private
Definition at line 92 of file rc_trackgroupimpl.h.
std::string rcTrackGroupImpl::_name private
Definition at line 91 of file rc_trackgroupimpl.h.
std::string rcTrackGroupImpl::_tag private
Definition at line 90 of file rc_trackgroupimpl.h.
deque<rcTrackImpl*> rcTrackGroupImpl::_tracks private
Definition at line 93 of file rc_trackgroupimpl.h.
Referenced by createWriter(), and release().
rcGroupSemantics rcTrackGroupImpl::_type private
Definition at line 94 of file rc_trackgroupimpl.h.
The documentation for this class was generated from the following files:
include/visiCore/rc_trackgroupimpl.h
src/visible/src/rc_trackgroupimpl.cpp