Visible: rcEngineObserver Class Reference
rcEngineObserver Class Reference abstract
#include <include/visiCore/rc_engine.h>
Public Member Functions
virtual ~rcEngineObserver ()
virtual rcWriterGroup * createWriterGroup (const char *tag, const char *name, const char *description, rcGroupSemantics type)=0
virtual bool acceptingImageBlits (void)=0
virtual void notifyError (const char *errorString)=0
virtual void notifyWarning (const char *warnString)=0
virtual void notifyStatus (const char *statusString)=0
virtual void notifyState (rcEngineState newState)=0
virtual void notifyTime (const rcTimestamp &timestamp)=0
virtual int32 timeEventCount () const =0
virtual void notifyTimelineRange (const rcTimestamp &start, const rcTimestamp &end)=0
virtual void notifyAnalysisRect (const rcRect &rect)=0
virtual void notifyAnalysisRectRotation (const rcAffineRectangle &)=0
virtual void notifyMultiplier (const double &multiplier)=0
virtual void notifyBlitData (const rcWindow *image)=0
virtual void notifyBlitGraphics (const rcVisualGraphicsCollection *graphics)=0
virtual void notifyLockApp (bool lock)=0
virtual int notifyRequestSave (const char *fileName, rcExperimentFileFormat format)=0
virtual void notifyVideoRect (const rcRect &rect)=0
virtual void notifyExperimentChange ()=0
virtual rcTimestamp getCursorTime (void)=0
virtual const
rcExperimentAttributes getExperimentAttributes (void)=0
virtual void setExperimentAttributes (const rcExperimentAttributes &attr)=0
virtual bool acceptingPolys (void)=0
virtual void notifyPolys (const rcPolygonGroupRef *polys)=0
virtual void getPolys (rcPolygonGroupRef &polys)=0
Detailed Description
Definition at line 208 of file rc_engine.h.
Constructor & Destructor Documentation
virtual rcEngineObserver::~rcEngineObserver () inline virtual
Definition at line 212 of file rc_engine.h.
 { };
Member Function Documentation
virtual bool rcEngineObserver::acceptingImageBlits (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::loadFrames(), and rcEngineImpl::processCapturedData().
virtual bool rcEngineObserver::acceptingPolys (void) pure virtual
Implemented in rcExperimentDomainImpl.
virtual rcWriterGroup* rcEngineObserver::createWriterGroup (const char * tag, const char * name, const char * description, rcGroupSemantics type) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcWriterManager::createWriterGroup(), and rcNativeImporter::parseGroup().
virtual rcTimestamp rcEngineObserver::getCursorTime (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::setSettingValue().
virtual const rcExperimentAttributes rcEngineObserver::getExperimentAttributes (void) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineMovieSaver::closeHdlr().
virtual void rcEngineObserver::getPolys (rcPolygonGroupRef & polys) pure virtual
Implemented in rcExperimentDomainImpl.
virtual void rcEngineObserver::notifyAnalysisRect (const rcRect & rect) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::analyze(), rcEngineImpl::loadFrames(), and rcEngineMovieCapture::run().
virtual void rcEngineObserver::notifyAnalysisRectRotation (const rcAffineRectangle &) pure virtual
Implemented in rcExperimentDomainImpl.
virtual void rcEngineObserver::notifyBlitData (const rcWindow * image) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::loadFrames(), and rcEngineImpl::processCapturedData().
virtual void rcEngineObserver::notifyBlitGraphics (const rcVisualGraphicsCollection * graphics) pure virtual
Implemented in rcExperimentDomainImpl.
virtual void rcEngineObserver::notifyError (const char * errorString) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::analyze(), rcEngineImpl::analyzeFocusArea(), rcEngineMovieSaver::closeHdlr(), rcEngineImpl::engineAbort(), rcEngineMovieSaver::errorHdlr(), rcEngineImpl::loadImages(), rcEngineImpl::loadMovie(), rcEngineImpl::modelTracker(), rcEngineImpl::reportOnBadGrabber(), and rcEngineMovieCapture::run().
virtual void rcEngineObserver::notifyExperimentChange () pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineMovieCapture::updateCameraSettings().
virtual void rcEngineObserver::notifyLockApp (bool lock) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::lock(), and rcEngineImpl::unlock().
virtual void rcEngineObserver::notifyMultiplier (const double & multiplier) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineMovieCapture::run().
virtual void rcEngineObserver::notifyPolys (const rcPolygonGroupRef * polys) pure virtual
Implemented in rcExperimentDomainImpl.
virtual int rcEngineObserver::notifyRequestSave (const char * fileName, rcExperimentFileFormat format) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineMovieSaver::closeHdlr().
virtual void rcEngineObserver::notifyState (rcEngineState newState) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::setInternalState(), and rcEngineBaseImpl::setInternalState().
virtual void rcEngineObserver::notifyStatus (const char * statusString) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::analyzeFocusArea(), rcEngineMovieSaver::closeHdlr(), rcEngineMovieCapture::createGrabber(), rcEngineImpl::entropyTracker(), rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::loadFrames(), rcEngineImpl::loadImages(), rcEngineImpl::loadMovie(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcEngineMoviePlayback::playbackCleanup(), rcEngineImpl::processCapturedData(), rcEngineProgress::progress(), rcEngineMovieCapture::run(), rcEngineImpl::setSettingValue(), rcEngineImpl::start(), and rcEngineImpl::stop().
virtual void rcEngineObserver::notifyTime (const rcTimestamp & timestamp) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::loadFrames(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcEngineImpl::processCapturedData(), rcEngineProgress::progress(), rcEngineMoviePlayback::run(), and rcEngineBaseImpl::writeData().
virtual void rcEngineObserver::notifyTimelineRange (const rcTimestamp & start, const rcTimestamp & end) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::loadFrames(), and rcEngineImpl::setTimeLineRange().
virtual void rcEngineObserver::notifyVideoRect (const rcRect & rect) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::loadFrames(), and rcEngineMovieCapture::run().
virtual void rcEngineObserver::notifyWarning (const char * warnString) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineMovieSaver::closeHdlr(), and rcEngineMovieSaver::delayHdlr().
virtual void rcEngineObserver::setExperimentAttributes (const rcExperimentAttributes & attr) pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineImpl::loadMovie().
virtual int32 rcEngineObserver::timeEventCount () const pure virtual
Implemented in rcExperimentDomainImpl.
Referenced by rcEngineMoviePlayback::run().
The documentation for this class was generated from the following file:
include/visiCore/rc_engine.h