Visible: rcFileChoiceSettingWidget Class Reference
rcFileChoiceSettingWidget Class Reference
#include <include/visUI/rc_filechoicesettingwidget.h>
Public Slots
void browseRequest (void)
void valueChanged (void)
void settingChanged (void)
void updateState (rcExperimentState state)
void singleFileBrowse (void)
void multiFileBrowse (void)
void directoryBrowse (void)
void directoryBrowse4Tiffs (void)
void imageImport (void)
void movieImport (void)
void tifDirImport (void)
void stkImport (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcFileChoiceSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcFileChoiceSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
QLineEdit * mFilenameWidget
rcExperimentFileFormat mFormat
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 12 of file rc_filechoicesettingwidget.h.
Constructor & Destructor Documentation
rcFileChoiceSettingWidget::rcFileChoiceSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 25 of file rc_filechoicesettingwidget.cpp.
References rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), imageImport(), mFilenameWidget, movieImport(), rcSettingWidget::mTopLayout, settingChanged(), stkImport(), tifDirImport(), and updateState().
     : rcSettingWidget( parent, setting )
 {
     mFilenameWidget = new QLineEdit( this , setting.getTag() );
     mTopLayout->addWidget( mFilenameWidget );
     mTopLayout->addSpacing( 5 );
     // use the setting description as a tool tip
     QToolTip::add( mFilenameWidget , setting.getDescription() );
     mFilenameWidget->setReadOnly( true );
     // update the text widget with the current value of the setting.
     settingChanged();
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     // Import signals (from File menu)
     connect( domain , SIGNAL( imageImport( void ) )  ,
              this , SLOT( imageImport( void ) ) );
     connect( domain , SIGNAL( tifDirImport( void ) )  ,
              this , SLOT( tifDirImport( void ) ) );
     connect( domain , SIGNAL( movieImport( void ) )  ,
              this , SLOT( movieImport( void ) ) );
     connect( domain , SIGNAL( stkImport( void ) )  ,
                  this , SLOT( stkImport( void ) ) );
 }
rcFileChoiceSettingWidget::~rcFileChoiceSettingWidget ()
Definition at line 63 of file rc_filechoicesettingwidget.cpp.
References mFilenameWidget.
 {
     QToolTip::remove( mFilenameWidget );
 }
Member Function Documentation
void rcFileChoiceSettingWidget::browseRequest (void) slot
Definition at line 217 of file rc_filechoicesettingwidget.cpp.
References directoryBrowse4Tiffs(), eDirectoryChoice, eFileChoice, eMultiFileChoice, rcSettingInfo::getDisplayType(), rcSettingWidget::mSetting, multiFileBrowse(), rmExceptionMacro, and singleFileBrowse().
 {
     switch (mSetting.getDisplayType())
     {
         case eFileChoice:       // setting is a file name (text + "browse" button)
             singleFileBrowse();
             break;
         case eMultiFileChoice:  // setting is a semicolon separated list of file names (text + "browse" button)
             multiFileBrowse();
             break;
         case eDirectoryChoice:  // setting is a directory name (text + "browse" button)
             directoryBrowse4Tiffs();
             break;
         default:
             rmExceptionMacro ( "unknown setting type" );
     }
 }
void rcFileChoiceSettingWidget::directoryBrowse (void) slot
Definition at line 140 of file rc_filechoicesettingwidget.cpp.
References rcSettingInfo::getDisplayName(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), null, and rcSettingInfo::setValue().
 {
     string currentValue = mSetting.getValue();
     QString s = QFileDialog::getExistingDirectory(
                     currentValue.c_str(),
                     0,
                     mSetting.getTag(),
                     mSetting.getDisplayName() );
     if (s != QString::null)
     {
         // if a directory was selected, update the setting
         mSetting.setValue( s.latin1() );
         // notify everybody (including us) about the change
         rcModelDomain::getModelDomain()->notifySettingChange();
     }
 }
void rcFileChoiceSettingWidget::directoryBrowse4Tiffs (void) slot
Definition at line 161 of file rc_filechoicesettingwidget.cpp.
References rcPersistenceManager::fileFormatImportCaption(), rcPersistenceManager::fileFormatImportFilter(), rcModelDomain::getModelDomain(), rcPersistenceManagerFactory::getPersistenceManager(), rcSettingInfo::getValue(), mFormat, rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), null, rfGetDirEntries(), and rcSettingInfo::setValue().
Referenced by browseRequest(), and tifDirImport().
 {
     rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     std::string tmp = persistenceManager->fileFormatImportFilter( mFormat );
     QString filter (tmp.c_str());
     tmp = persistenceManager->fileFormatImportCaption( mFormat );
     QString caption (tmp.c_str());
     string currentValue = mSetting.getValue();
     QString s = QFileDialog::getExistingDirectory(
                           currentValue.c_str(),
                           0,
                           "Select a Directory of Tiff Image Files",
                           "Select a Directory of Tiff Image Files");
     if (s != QString::null)
     {
       vector<std::string> files;
       //@note gets tiff files: .tif or .TIF
           std::string tmp ((char *) (s.data ()));
       rfGetDirEntries (tmp, files);
       if (files.size())
         {
           // Iterate all selected files
           QString selectedFiles;
           vector<std::string>::iterator it = files.begin();
           while (it != files.end())
         {
                     QString sg (it->c_str ());
           if (sg != QString::null)
             {
               // Create a list of semicolon separated file names
               selectedFiles += sg;
               selectedFiles +=";";
             }
           ++it;
         }
           if (!selectedFiles.isEmpty())
         {
           // if a file was selected, update the setting
           mSetting.setValue( selectedFiles.latin1() );
           // notify everybody (including us) about the change
           rcModelDomain::getModelDomain()->notifySettingChange();
         }
         }
     }
 }
void rcFileChoiceSettingWidget::imageImport (void) slot
Definition at line 320 of file rc_filechoicesettingwidget.cpp.
References eExperimentQuickTimeImageFormat, eMultiFileChoice, rcSettingInfo::getDisplayType(), mFormat, rcSettingWidget::mSetting, and multiFileBrowse().
Referenced by rcFileChoiceSettingWidget().
 {
     mFormat = eExperimentQuickTimeImageFormat;
     switch (mSetting.getDisplayType())
     {
         case eMultiFileChoice:  // setting is a semicolon separated list of file names (text + "browse" button)
             multiFileBrowse();
             break;
         default:
             // Ignore request if this is not a multi-file widget
             break;
     }
 }
void rcFileChoiceSettingWidget::movieImport (void) slot
Definition at line 289 of file rc_filechoicesettingwidget.cpp.
References eExperimentQuickTimeMovieFormat, eFileChoice, rcSettingInfo::getDisplayType(), mFormat, rcSettingWidget::mSetting, and singleFileBrowse().
Referenced by rcFileChoiceSettingWidget().
 {
     mFormat = eExperimentQuickTimeMovieFormat;
     switch (mSetting.getDisplayType())
     {
         case eFileChoice:       // setting is a file name (text + "browse" button)
             singleFileBrowse();
             break;
         default:
             // Ignore request if this is not a single-file widget
             break;
     }
 }
void rcFileChoiceSettingWidget::multiFileBrowse (void) slot
Definition at line 98 of file rc_filechoicesettingwidget.cpp.
References rcPersistenceManager::fileFormatImportCaption(), rcPersistenceManager::fileFormatImportFilter(), rcModelDomain::getModelDomain(), rcPersistenceManagerFactory::getPersistenceManager(), mFormat, rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), null, and rcSettingInfo::setValue().
Referenced by browseRequest(), and imageImport().
 {
     rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     std::string tmp = persistenceManager->fileFormatImportFilter( mFormat );
     QString filter (tmp.c_str());
     tmp = persistenceManager->fileFormatImportCaption( mFormat );
     QString caption (tmp.c_str());
     QStringList list = QFileDialog::getOpenFileNames(
         filter,
         "",
         0,
         caption,
         caption );
     // Iterate all selected files
     QString selectedFiles;
     QStringList::Iterator it = list.begin();
     while (it != list.end())
     {
         QString& s = *it;
         if (s != QString::null)
         {
             // Create a list of semicolon separated file names
             selectedFiles += s;
             selectedFiles +=";";
         }
         ++it;
     }
     if (!selectedFiles.isEmpty())
     {
         // if a file was selected, update the setting
        mSetting.setValue( selectedFiles.latin1() );
         // notify everybody (including us) about the change
         rcModelDomain::getModelDomain()->notifySettingChange();
     }
 }
void rcFileChoiceSettingWidget::settingChanged (void) slot
Definition at line 250 of file rc_filechoicesettingwidget.cpp.
References rcSettingInfo::getValue(), mFilenameWidget, rcSettingWidget::mSetting, and rcSettingWidget::updateWidgetState().
Referenced by rcFileChoiceSettingWidget().
 {
     string currentValue = mSetting.getValue();
     mFilenameWidget->setText( currentValue.c_str() );
     // Update visibility/editability
     updateWidgetState();
 }
void rcFileChoiceSettingWidget::singleFileBrowse (void) slot
Definition at line 70 of file rc_filechoicesettingwidget.cpp.
References rcPersistenceManager::fileFormatImportCaption(), rcPersistenceManager::fileFormatImportFilter(), rcModelDomain::getModelDomain(), rcPersistenceManagerFactory::getPersistenceManager(), rcSettingInfo::getValue(), mFormat, rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), null, and rcSettingInfo::setValue().
Referenced by browseRequest(), movieImport(), and stkImport().
 {
     string currentValue = mSetting.getValue();
     rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     std::string tmp = persistenceManager->fileFormatImportFilter( mFormat );
     QString filter (tmp.c_str());
     tmp = persistenceManager->fileFormatImportCaption( mFormat );
     QString caption (tmp.c_str());
     QString s = QFileDialog::getOpenFileName(
                     currentValue.c_str(),
                     filter,
                     0,
                     caption,
                     caption );
     if (s != QString::null)
     {
         // if a file was selected, update the setting
         mSetting.setValue( s.latin1() );
         // notify everybody (including us) about the change
         rcModelDomain::getModelDomain()->notifySettingChange();
     }
 }
void rcFileChoiceSettingWidget::stkImport (void) slot
Definition at line 304 of file rc_filechoicesettingwidget.cpp.
References eExperimentMolDevSTKFormat, eFileChoice, rcSettingInfo::getDisplayType(), mFormat, rcSettingWidget::mSetting, and singleFileBrowse().
Referenced by rcFileChoiceSettingWidget().
 {
     mFormat = eExperimentMolDevSTKFormat;
     switch (mSetting.getDisplayType())
     {
         case eFileChoice:       // setting is a file name (text + "browse" button)
             singleFileBrowse();
             break;
         default:
             // Ignore request if this is not a single-file widget
             break;
     }
 }
void rcFileChoiceSettingWidget::tifDirImport (void) slot
Definition at line 335 of file rc_filechoicesettingwidget.cpp.
References directoryBrowse4Tiffs(), eDirectoryChoice, eExperimentQuickTimeImageFormat, rcSettingInfo::getDisplayType(), mFormat, and rcSettingWidget::mSetting.
Referenced by rcFileChoiceSettingWidget().
 {
     mFormat = eExperimentQuickTimeImageFormat;
     switch (mSetting.getDisplayType())
     {
         case eDirectoryChoice:  // setting is a directory name (text + "browse" button)
             directoryBrowse4Tiffs();
             break;
         default:
             // Ignore request if this is not a multi-file widget
             break;
     }
 }
void rcFileChoiceSettingWidget::updateState (rcExperimentState state) slot
Definition at line 259 of file rc_filechoicesettingwidget.cpp.
References eExperimentEmpty, eExperimentEnded, eExperimentLocked, eExperimentPlayback, and eExperimentRunning.
Referenced by rcFileChoiceSettingWidget().
 {
     // The widget is read-only so it can always remain enabled
     switch( state ) {
         case eExperimentEmpty:          // experiment was created but not run
             setEnabled( true );
             break;
         case eExperimentRunning:        // experiment is running
             setEnabled( true );
             break;
         case eExperimentPlayback:       // experiment is playing back
             setEnabled( true );
             break;
         case eExperimentEnded:          // experiment has ended
             setEnabled( true );
             break;
         case eExperimentLocked:         // experiment has ended and been saved
             setEnabled( true );
             break;
         default:
             break;
     }
 }
void rcFileChoiceSettingWidget::valueChanged (void) slot
Definition at line 240 of file rc_filechoicesettingwidget.cpp.
References rcModelDomain::getModelDomain(), mFilenameWidget, rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
 {
     mSetting.setValue( mFilenameWidget->text().latin1() );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
QLineEdit* rcFileChoiceSettingWidget::mFilenameWidget private
Definition at line 46 of file rc_filechoicesettingwidget.h.
Referenced by rcFileChoiceSettingWidget(), settingChanged(), valueChanged(), and ~rcFileChoiceSettingWidget().
rcExperimentFileFormat rcFileChoiceSettingWidget::mFormat private
Definition at line 47 of file rc_filechoicesettingwidget.h.
Referenced by directoryBrowse4Tiffs(), imageImport(), movieImport(), multiFileBrowse(), singleFileBrowse(), stkImport(), and tifDirImport().
The documentation for this class was generated from the following files:
include/visUI/rc_filechoicesettingwidget.h
src/visible/qt/rc_filechoicesettingwidget.cpp