Visible: rcGenMovieFile Class Reference
rcGenMovieFile Class Reference
#include <include/visual/rc_gen_movie_file.h>
Public Member Functions
rcGenMovieFile (const std::string &fName)
rcGenMovieFile (const std::string &fName, const movieOriginType &orig, const std::string &creator, const movieFormatRev &rev, bool overWrite, const float &fInt)
rcGenMovieFile (const std::string &fName, const rcChannelConversion &conv, const movieFormatRev &rev, bool overWrite, const float &fInt)
rcGenMovieFile (const std::string &fName, const movieOriginType &orig, const rcChannelConversion &conv, const std::string &creator, const movieFormatRev &rev, bool overWrite, const float &fInt)
~rcGenMovieFile ()
const rcChannelConversion & conversion () const
const std::string & fileName () const
rcIPair frameSize () const
bool valid () const
rcGenMovieFileError lastError () const
rcGenMovieFileError addFrame (const rcWindow &frame)
rcGenMovieFileError addFrame (const rcWindow &frame, const rcWindow &alpha)
rcGenMovieFileError addHeader (const rcMovieFileConvExt &hdr)
rcGenMovieFileError addHeader (const rcMovieFileCamExt &hdr)
rcGenMovieFileError addHeader (const rcMovieFileOrgExt &hdr)
rcGenMovieFileError addHeader (const rcMovieFileExpExt &hdr)
rcGenMovieFileError flush ()
Private Member Functions
rcGenMovieFileError open (const std::string &fName, bool overwrite)
rcGenMovieFileError write (const rcWindow &frame, const int64 &timestamp)
rcGenMovieFileError initHeader (const rcWindow &frame)
Private Attributes
std::string _fileName
vector< int64 > _toc
vector< rcMovieFileConvExt > _cnvHdrs
vector< rcMovieFileCamExt > _camHdrs
vector< rcMovieFileOrgExt > _orgHdrs
vector< rcMovieFileExpExt > _expHdrs
movieOriginType _origin
rcChannelConversion _conversion
rcMovieFileFormat _movieHdr
rcMovieFileFormat2 _movieHdr2
std::string _creator
movieFormatRev _rev
FILE * _saveStream
rcGenMovieFileError _lastError
bool _overWrite
bool _flushed
float _frameInterval
bool _verbose
rcPixel _inputDepth
Detailed Description
Definition at line 36 of file rc_gen_movie_file.h.
Constructor & Destructor Documentation
rcGenMovieFile::rcGenMovieFile (const std::string & fName)
Definition at line 20 of file rc_gen_movie_file.cpp.
References _fileName, _lastError, _overWrite, and open().
                                                        :
         _fileName( fName ),
         _origin(movieOriginSynthetic), _conversion(rcSelectAverage), _creator("Unknown"),
         _rev(movieFormatRevLatest), _saveStream(0), _lastError( eGenMovieFileErrorOK ),
         _overWrite( false ), _flushed( false ), _frameInterval( -1.0 ),
         _verbose( false ), _inputDepth( rcPixelUnknown )
 {
     _lastError = open(_fileName, _overWrite);
}
rcGenMovieFile::rcGenMovieFile (const std::string & fName, const movieOriginType & orig, const std::string & creator, const movieFormatRev & rev, bool overWrite, const float & fInt)
Definition at line 30 of file rc_gen_movie_file.cpp.
References _fileName, _lastError, _overWrite, and open().
                                                     :
         _fileName( fName ), _origin(o), _conversion(rcSelectAverage), _creator(c),
         _rev(rev), _saveStream(0), _lastError( eGenMovieFileErrorOK ),
         _overWrite( over ), _flushed( false ), _frameInterval( fInt ),
         _verbose( false ), _inputDepth( rcPixelUnknown )
 {
     _lastError = open(_fileName, _overWrite);
}
rcGenMovieFile::rcGenMovieFile (const std::string & fName, const rcChannelConversion & conv, const movieFormatRev & rev, bool overWrite, const float & fInt)
Definition at line 44 of file rc_gen_movie_file.cpp.
References _fileName, _lastError, _overWrite, and open().
                                                     :
         _fileName( fName ), _origin(movieOriginUnknown), _conversion(conv), _creator("Unknown"),
         _rev(rev), _saveStream(0), _lastError( eGenMovieFileErrorOK ),
         _overWrite( over ), _flushed( false ), _frameInterval( fInt ),
         _verbose( false ), _inputDepth( rcPixelUnknown )
 {
     _lastError = open(_fileName, _overWrite);
}
rcGenMovieFile::rcGenMovieFile (const std::string & fName, const movieOriginType & orig, const rcChannelConversion & conv, const std::string & creator, const movieFormatRev & rev, bool overWrite, const float & fInt)
Definition at line 57 of file rc_gen_movie_file.cpp.
References _fileName, _lastError, _overWrite, and open().
                                                     :
         _fileName( fName ), _origin(o), _conversion(conv), _creator(c),
         _rev(rev), _saveStream(0), _lastError( eGenMovieFileErrorOK ),
         _overWrite( over ), _flushed( false ), _frameInterval( fInt ),
         _verbose( false ), _inputDepth( rcPixelUnknown )
 {
     _lastError = open(_fileName, _overWrite);
}
rcGenMovieFile::~rcGenMovieFile ()
Definition at line 72 of file rc_gen_movie_file.cpp.
References flush().
 {
     flush();
 }
Member Function Documentation
rcGenMovieFileError rcGenMovieFile::addFrame (const rcWindow & frame)
Definition at line 105 of file rc_gen_movie_file.cpp.
References _conversion, _flushed, _frameInterval, _inputDepth, _lastError, _movieHdr, _movieHdr2, _rev, rcTimestamp::_timestamp, _toc, convertSecondsToTimestamp(), rcWindow::depth(), eGenMovieFileErrorFlush, eGenMovieFileErrorOK, rcWindow::frameBuf(), rcWindow::height(), rcMovieFileFormat::height(), rcMovieFileFormat2::height(), initHeader(), movieFormatRev1, movieFormatRev2, rcPixel16, rcPixel32, rcPixel8, rcSelectAll, rfImageConvert168(), rfImageConvert32to8(), rmAssert, rcFrame::timestamp(), valid(), rcWindow::width(), rcMovieFileFormat::width(), rcMovieFileFormat2::width(), and write().
Referenced by addFrame(), rcMuscleSegmenter::debugWrite(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), rcMPEG2Grabber::getReifyMovie(), and main().
 {
     if ( _flushed )
         return eGenMovieFileErrorFlush;
     if ( !valid() )
         return _lastError;
     if ( _toc.empty() ) {
         _lastError = initHeader( frame );
         if ( !valid() )
             return _lastError;
     } else {
         if ( _rev <= movieFormatRev1 ) {
             // All added frames must be the same size
             rmAssert(int(_movieHdr.width()) == frame.width());
             rmAssert(int(_movieHdr.height()) == frame.height());
         } else if ( _rev >= movieFormatRev2 ) {
             // All added frames must be the same size
             rmAssert(int(_movieHdr2.width()) == frame.width());
             rmAssert(int(_movieHdr2.height()) == frame.height());
         }
         rmAssert( _inputDepth == frame.depth() );
     }
     int64 timestamp = 0;
     if ( _frameInterval > 0.0f ) {
         // Generate timestamps from forced frame rate
         if ( !_toc.empty() )
             timestamp = convertSecondsToTimestamp((rcTimestamp(_toc.back()) + rcTimestamp(_frameInterval)).secs());
     } else
         timestamp = frame.frameBuf()->timestamp()._timestamp;
     if ( frame.depth() == rcPixel8 ) {
         // 8-bit, no conversion
         write( frame, timestamp );
     } else if ( frame.depth() == rcPixel32 ) {
         if (  _conversion == rcSelectAll ) {
             // 32-bit, no conversion
             write( frame, timestamp );
         } else {
             // Convert 32-bit to 8-bit
             rcWindow frame8(frame.width(), frame.height());
         rfImageConvert32to8 (frame, frame8, _conversion);
             rmAssert( rcPixel8 == frame8.depth() );
             frame8.frameBuf()->setIsGray(true);
             frame8.frameBuf()->setTimestamp(rcTimestamp(timestamp));
             write( frame8, timestamp );
         }
     } else if ( frame.depth() == rcPixel16) {
       if (  _conversion == rcSelectAll ) {
     // 16-bit, no conversion
     write( frame, timestamp );
       } else {
       // @todo merge this and rc_ipconvert{h,cpp} move them to visual
       // Convert 16-bit to 8-bit
             rcWindow frame8(frame.width(), frame.height());
         rfImageConvert168 (frame, frame8, _conversion);
             rmAssert( rcPixel8 == frame8.depth() );
             frame8.frameBuf()->setIsGray(true);
             frame8.frameBuf()->setTimestamp(rcTimestamp(timestamp));
             write( frame8, timestamp );
         }
     } else {
       // Unsupported depth
       rmAssert( 0 );
     }
     _toc.push_back(timestamp);
     return eGenMovieFileErrorOK;
 }
rcGenMovieFileError rcGenMovieFile::addFrame (const rcWindow & frame, const rcWindow & alpha)
Definition at line 180 of file rc_gen_movie_file.cpp.
References _origin, addFrame(), rcWindow::depth(), movieOriginGrayIsVisibleAlphaIsFlu, rfImageConvert8ToARGB(), rmAssert, and rcWindow::size().
 {
   rmAssert(alpha.size() == frame.size());
   rmAssert(int(alpha.depth()) == frame.depth());
   rmAssert (_origin == movieOriginGrayIsVisibleAlphaIsFlu);
   // Combine two frames in to a 32 bit image
   rcWindow newFrame = rfImageConvert8ToARGB (frame, alpha);
   return addFrame (newFrame);
 }
rcGenMovieFileError rcGenMovieFile::addHeader (const rcMovieFileConvExt & hdr)
Definition at line 194 of file rc_gen_movie_file.cpp.
References _cnvHdrs, _flushed, eGenMovieFileErrorFlush, and eGenMovieFileErrorOK.
Referenced by generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), and rcMPEG2Grabber::getReifyMovie().
 {
     if ( _flushed )
         return eGenMovieFileErrorFlush;
     _cnvHdrs.push_back( hdr );
     return eGenMovieFileErrorOK;
 }
rcGenMovieFileError rcGenMovieFile::addHeader (const rcMovieFileCamExt & hdr)
Definition at line 216 of file rc_gen_movie_file.cpp.
References _camHdrs, _flushed, eGenMovieFileErrorFlush, and eGenMovieFileErrorOK.
 {
     if ( _flushed )
         return eGenMovieFileErrorFlush;
     _camHdrs.push_back( hdr );
     return eGenMovieFileErrorOK;
 }
rcGenMovieFileError rcGenMovieFile::addHeader (const rcMovieFileOrgExt & hdr)
Definition at line 205 of file rc_gen_movie_file.cpp.
References _flushed, _orgHdrs, eGenMovieFileErrorFlush, and eGenMovieFileErrorOK.
 {
     if ( _flushed )
         return eGenMovieFileErrorFlush;
     _orgHdrs.push_back( hdr );
     return eGenMovieFileErrorOK;
 }
rcGenMovieFileError rcGenMovieFile::addHeader (const rcMovieFileExpExt & hdr)
Definition at line 227 of file rc_gen_movie_file.cpp.
References _expHdrs, _flushed, eGenMovieFileErrorFlush, and eGenMovieFileErrorOK.
 {
     if ( _flushed )
         return eGenMovieFileErrorFlush;
     _expHdrs.push_back( hdr );
     return eGenMovieFileErrorOK;
 }
const rcChannelConversion& rcGenMovieFile::conversion () const inline
Definition at line 74 of file rc_gen_movie_file.h.
References _conversion.
 { return _conversion; };
const std::string& rcGenMovieFile::fileName () const inline
Definition at line 75 of file rc_gen_movie_file.h.
References _fileName.
 { return  _fileName; };
rcGenMovieFileError rcGenMovieFile::flush (void)
Definition at line 239 of file rc_gen_movie_file.cpp.
References _camHdrs, _cnvHdrs, _creator, _expHdrs, _flushed, _inputDepth, _movieHdr, _movieHdr2, _orgHdrs, _origin, _rev, _saveStream, _toc, _verbose, rcMovieFileFormat::averageFrameRate(), rcMovieFileFormat2::averageFrameRate(), rcMovieFileFormat2::baseTime(), rcMovieFileFormat2::bytesInFrame(), rcMovieFileConvExt::channel(), eGenMovieFileErrorClose, eGenMovieFileErrorNull, eGenMovieFileErrorOK, eGenMovieFileErrorSeek, eGenMovieFileErrorWrite, endl(), rcMovieFileFormat2::extensionOffset(), rcMovieFileFormat::frameCount(), rcMovieFileFormat2::frameCount(), rcMovieFileFormat2::height(), rcMovieFileOrgExt::id(), rcMovieFileConvExt::id(), rcMovieFileCamExt::id(), rcMovieFileExpExt::id(), movieChannelUnknown, movieExtensionEOF, movieFormatInvalid, movieFormatRev0, movieFormatRev1, movieFormatRev2, rmAssert, rcMovieFileFormat2::width(), rcMovieFileFormat::write(), rcMovieFileFormat2::write(), rcMovieFileExt::write(), rcMovieFileOrgExt::write(), rcMovieFileConvExt::write(), rcMovieFileCamExt::write(), and rcMovieFileExpExt::write().
Referenced by generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), rcMPEG2Grabber::getReifyMovie(), main(), and ~rcGenMovieFile().
 {
     if ( _flushed )
         return eGenMovieFileErrorOK;
     if ( !_saveStream )
         return eGenMovieFileErrorNull;
     _flushed = true;
     if (_toc.size() < 2) {
         if ( fclose(_saveStream)) {
             perror("fclose in flush(0) failed");
             return eGenMovieFileErrorClose;
         }
         return eGenMovieFileErrorNull;
     }
     // Update basic header
     int64 firstTime = _toc[0];
     double movieTime = rcTimestamp(_toc[_toc.size()-1] - firstTime).secs();
     switch ( _rev ) {
         case movieFormatRev0:
             _movieHdr.averageFrameRate((_toc.size()-1)/movieTime);
             _movieHdr.frameCount(_toc.size());
             break;
         case movieFormatRev1:
         {
             _movieHdr.averageFrameRate((_toc.size()-1)/movieTime);
             _movieHdr.frameCount(_toc.size());
             // Store TOC header
             rcMovieFileTocExt tocHdr( _toc.size() );
             if ( tocHdr.write( _saveStream, _toc ) )
                 return eGenMovieFileErrorWrite;
             if ( _verbose )
                 cerr << tocHdr << endl;
             /* Store EOF header.
              */
             rcMovieFileExt eofHdr(movieExtensionEOF);
             if (eofHdr.write(_saveStream))
                 return eGenMovieFileErrorWrite;
             if ( _verbose )
                 cerr << eofHdr << endl;
         }
         break;
         case movieFormatRev2:
         {
             _movieHdr2.averageFrameRate((_toc.size()-1)/movieTime);
             _movieHdr2.frameCount(_toc.size());
             // Update rev2 header additions
             const off_t movieRecordSz = sizeof(int64) + _movieHdr2.bytesInFrame();
             // Offset to start of headers
             _movieHdr2.extensionOffset( sizeof(_movieHdr2) +
                                         movieRecordSz*_movieHdr2.frameCount());
             // Store TOC header
             rcMovieFileTocExt tocHdr( _toc.size() );
             if ( tocHdr.write( _saveStream, _toc ) )
                 return eGenMovieFileErrorWrite;
             if ( _verbose )
                 cerr << tocHdr << endl;
             std::string creator = _creator;
             // Each rev2 header needs a unique id
             int32 id = 1;
             // Store origin headers
             if ( !_orgHdrs.empty() ) {
                 for ( uint32 i = 0; i < _orgHdrs.size(); ++i ) {
                     rcMovieFileOrgExt orgHdr = _orgHdrs[i];
                     orgHdr.id( id++ );
                     if ( orgHdr.write( _saveStream ) )
                         return eGenMovieFileErrorWrite;
                     if ( _verbose )
                         cerr << orgHdr << endl;
                 }
             } else {
                 // User added no headers, produce a default header
                 rcMovieFileOrgExt orgHdr( _origin,
                                           _movieHdr2.baseTime(),
                                           _movieHdr2.frameCount(),
                                           _movieHdr2.width(),
                                           _movieHdr2.height(),
                                           _inputDepth,
                                           _rev,
                                           _creator.c_str() );
                 orgHdr.id( id++ );
                 if ( orgHdr.write( _saveStream ) )
                     return eGenMovieFileErrorWrite;
                 if ( _verbose )
                     cerr << orgHdr << endl;
             }
             // Store camera headers
             for ( uint32 i = 0; i < _camHdrs.size(); ++i ) {
                 rcMovieFileCamExt cam = _camHdrs[i];
                 cam.id( id++ );
                 if ( cam.write( _saveStream ) )
                     return eGenMovieFileErrorWrite;
             }
             // Store conversion headers
             for ( uint32 i = 0; i < _cnvHdrs.size(); ++i ) {
                 rcMovieFileConvExt cnv = _cnvHdrs[i];
                 if ( cnv.channel() != movieChannelUnknown ) {
                     cnv.id( id++ );
                     if ( cnv.write( _saveStream ) )
                         return eGenMovieFileErrorWrite;
                 }
             }
             // Store experiment headers
             for ( uint32 i = 0; i < _expHdrs.size(); ++i ) {
                 rcMovieFileExpExt exp = _expHdrs[i];
                 exp.id( id++ );
                 if ( exp.write( _saveStream ) )
                     return eGenMovieFileErrorWrite;
             }
             /* Store EOF header.
              */
             rcMovieFileExt eofHdr(movieExtensionEOF);
             if (eofHdr.write(_saveStream))
                 return eGenMovieFileErrorWrite;
             if ( _verbose )
                 cerr << eofHdr << endl;
         }
         break;
         case movieFormatInvalid:
             rmAssert( 0 );
             break;
     }
     if (fseek(_saveStream, 0, SEEK_SET)) {
         perror("fseek in flush failed");
         if (fclose(_saveStream))
             perror("fclose in flush(5) failed");
         return eGenMovieFileErrorSeek;
     }
     if ( _rev <= movieFormatRev1 ) {
         // Write basic header
         if ( _movieHdr.write( _saveStream ) )
             return eGenMovieFileErrorWrite;
     } else if ( _rev >= movieFormatRev2 ) {
         // Write rev2 header
         if ( _movieHdr2.write( _saveStream ) )
             return eGenMovieFileErrorWrite;
     } else {
         rmAssert( 0 );
     }
     if (fclose(_saveStream)) {
         perror("fclose in flush(7) failed");
         return eGenMovieFileErrorClose;
     }
     return eGenMovieFileErrorOK;
 }
rcIPair rcGenMovieFile::frameSize () const
Definition at line 77 of file rc_gen_movie_file.cpp.
References _movieHdr, _movieHdr2, _rev, _toc, rcMovieFileFormat::height(), rcMovieFileFormat2::height(), movieFormatRev1, movieFormatRev2, rmAssert, rcMovieFileFormat::width(), and rcMovieFileFormat2::width().
Referenced by rcMuscleSegmenter::segment().
 {
   if (_toc.empty())
     return rcIPair(0, 0);
   if (_rev <= movieFormatRev1)
     return rcIPair((int32)_movieHdr.width(), (int32)_movieHdr.height());
   if (_rev >= movieFormatRev2)
   return rcIPair((int32)_movieHdr2.width(), (int32)_movieHdr2.height());
   rmAssert( 0 );        // We should never get here
   return rcIPair(0, 0); // Silences compiler warning
 }
rcGenMovieFileError rcGenMovieFile::initHeader (const rcWindow & frame) private
Definition at line 492 of file rc_gen_movie_file.cpp.
References _conversion, _frameInterval, _inputDepth, _movieHdr, _movieHdr2, _origin, _rev, rcMovieFileFormat::baseTime(), rcMovieFileFormat2::baseTime(), rcWindow::depth(), rcMovieFileFormat2::depth(), eGenMovieFileErrorOK, rcWindow::frameBuf(), getCurrentTimestamp(), movieFormatRev1, movieFormatRev2, movieOriginSynthetic, rcPixel16, rcPixel32, rcPixel8, rcSelectAll, rmAssert, rcMovieFileFormat::rowUpdate(), rcMovieFileFormat2::rowUpdate(), and rcWindow::width().
Referenced by addFrame().
 {
     rmAssert(rcPixel8 == frame.depth() || rcPixel16 == frame.depth() ||
              rcPixel32 == frame.depth());
     uint32 rowDataLth = frame.width();
     uint32 rowUpdateLth = (rowDataLth + 15) & 0xFFFFFFF0;
     if ( _conversion == rcSelectAll && frame.depth() == rcPixel32) {
         rowDataLth = frame.width() * frame.depth();
         rowUpdateLth = (rowDataLth + 15) & 0xFFFFFFF0;
     }
     if ( _conversion == rcSelectAll && frame.depth() == rcPixel16) {
       rowDataLth = frame.width() * frame.depth();
       rowUpdateLth = (rowDataLth + 15) & 0xFFFFFFF0;
     }
     if ( _rev <= movieFormatRev1 ) {
         _movieHdr = rcMovieFileFormat( frame.frameBuf(), _rev );
         _movieHdr.rowUpdate( rowUpdateLth );
         if ( _frameInterval > 0.0f && _origin == movieOriginSynthetic ) {
             // Synthetic frame rate, set base time to current time
             _movieHdr.baseTime( getCurrentTimestamp() );
         }
     } else if ( _rev >= movieFormatRev2 ) {
         _movieHdr2 = rcMovieFileFormat2( frame.frameBuf(), _rev );
         _movieHdr2.rowUpdate( rowUpdateLth );
         if ( _conversion != rcSelectAll ) {
             // Output will be 8-bit
             _movieHdr2.depth( rcPixel8 );
         }
         if ( _frameInterval > 0.0f && _origin == movieOriginSynthetic ) {
             // Synthetic frame rate, set base time to current time
             _movieHdr2.baseTime( getCurrentTimestamp() );
         }
     }
     _inputDepth = frame.depth();
     return eGenMovieFileErrorOK;
 }
rcGenMovieFileError rcGenMovieFile::lastError () const
Definition at line 99 of file rc_gen_movie_file.cpp.
References _lastError.
 {
     return _lastError;
 }
rcGenMovieFileError rcGenMovieFile::open (const std::string & fName, bool overwrite) private
Definition at line 407 of file rc_gen_movie_file.cpp.
References _movieHdr, _movieHdr2, _rev, _saveStream, eGenMovieFileErrorExists, eGenMovieFileErrorOK, eGenMovieFileErrorOpen, eGenMovieFileErrorWrite, movieFormatInvalid, movieFormatRev1, movieFormatRev2, NULL, rmAssert, rmDim, rcMovieFileFormat::write(), and rcMovieFileFormat2::write().
Referenced by rcGenMovieFile().
 {
     if (fName.empty())
         return eGenMovieFileErrorOpen;
     if (!overwrite) {
         FILE* temp = fopen(fName.c_str(), "r");
         if (temp) {
             fclose(temp);
             perror("fclose in open(1) failed");
             return eGenMovieFileErrorExists;
         }
     }
     _saveStream = fopen(fName.c_str(), "w+");
     if (_saveStream == NULL) {
         char buf[1024];
         snprintf( buf, rmDim(buf), "fopen in open failed for %s",
                   fName.c_str() );
         perror(buf);
         return eGenMovieFileErrorOpen;
     }
     /* Write out a dummy header indicating the movie is invalid.  Will
      * only be changed to a valid header at the very end when we know
      * the movie is good.
      */
     _movieHdr = rcMovieFileFormat(movieFormatInvalid);
     _movieHdr2 = rcMovieFileFormat2(movieFormatInvalid);
     if ( _rev <= movieFormatRev1 ) {
         // Write basic header
         if ( _movieHdr.write( _saveStream ) )
             return eGenMovieFileErrorWrite;
     } else if ( _rev >= movieFormatRev2 ) {
         // Write rev2 header
         if ( _movieHdr2.write( _saveStream ) )
             return eGenMovieFileErrorWrite;
     } else {
         rmAssert( 0 );
     }
     return eGenMovieFileErrorOK;
 }
bool rcGenMovieFile::valid (void) const
Definition at line 93 of file rc_gen_movie_file.cpp.
References _lastError, and eGenMovieFileErrorOK.
Referenced by addFrame(), rcMovieConverterToRfy::createRfyMovie(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), rcMPEG2Grabber::getReifyMovie(), and write().
 {
     return (_lastError == eGenMovieFileErrorOK);
 }
rcGenMovieFileError rcGenMovieFile::write (const rcWindow & frame, const int64 & timestamp) private
Definition at line 454 of file rc_gen_movie_file.cpp.
References _flushed, _lastError, _saveStream, rcWindow::depth(), eGenMovieFileErrorFlush, eGenMovieFileErrorOK, eGenMovieFileErrorWrite, rcWindow::height(), rcMovieFrameFormat::rawPixels, rmAssert, rcWindow::rowPointer(), rcMovieFrameFormat::timestamp, valid(), and rcWindow::width().
Referenced by addFrame().
 {
     if ( _flushed )
         return eGenMovieFileErrorFlush;
     if ( !valid() )
         return _lastError;
     const uint32 rowDataLth = frame.width() * frame.depth();
     const uint32 rowUpdateLth = (rowDataLth + 15) & 0xFFFFFFF0;
     const uint32 byteCnt = sizeof(int64) + rowUpdateLth*frame.height();
     rcMovieFrameFormat* fPtr = (rcMovieFrameFormat*)malloc(byteCnt);
     rmAssert(fPtr);
     fPtr->timestamp = timestamp;
     for (int32 yo = 0; yo < frame.height(); yo++) {
         uint8* dPtr = (uint8*)&fPtr->rawPixels[yo*rowUpdateLth];
         const uint8* sPtr = (uint8*)frame.rowPointer(yo);
         memcpy(dPtr, sPtr, rowDataLth);
     }
     if (fwrite(fPtr, byteCnt, 1, _saveStream) != 1) {
         perror("fwrite of frame in saveToDisk failed");
         if (fclose(_saveStream))
             perror("fclose in saveToDisk(1) failed");
         free (fPtr);
         return eGenMovieFileErrorWrite;
     }
     free(fPtr);
     return eGenMovieFileErrorOK;
 }
Member Data Documentation
vector<rcMovieFileCamExt> rcGenMovieFile::_camHdrs private
Definition at line 135 of file rc_gen_movie_file.h.
Referenced by addHeader(), and flush().
vector<rcMovieFileConvExt> rcGenMovieFile::_cnvHdrs private
Definition at line 134 of file rc_gen_movie_file.h.
Referenced by addHeader(), and flush().
rcChannelConversion rcGenMovieFile::_conversion private
Definition at line 140 of file rc_gen_movie_file.h.
Referenced by addFrame(), conversion(), and initHeader().
std::string rcGenMovieFile::_creator private
Definition at line 143 of file rc_gen_movie_file.h.
Referenced by flush().
vector<rcMovieFileExpExt> rcGenMovieFile::_expHdrs private
Definition at line 137 of file rc_gen_movie_file.h.
Referenced by addHeader(), and flush().
std::string rcGenMovieFile::_fileName private
Definition at line 132 of file rc_gen_movie_file.h.
Referenced by fileName(), and rcGenMovieFile().
bool rcGenMovieFile::_flushed private
Definition at line 149 of file rc_gen_movie_file.h.
Referenced by addFrame(), addHeader(), flush(), and write().
float rcGenMovieFile::_frameInterval private
Definition at line 150 of file rc_gen_movie_file.h.
Referenced by addFrame(), and initHeader().
rcPixel rcGenMovieFile::_inputDepth private
Definition at line 152 of file rc_gen_movie_file.h.
Referenced by addFrame(), flush(), and initHeader().
rcGenMovieFileError rcGenMovieFile::_lastError private
Definition at line 147 of file rc_gen_movie_file.h.
Referenced by addFrame(), lastError(), rcGenMovieFile(), valid(), and write().
rcMovieFileFormat rcGenMovieFile::_movieHdr private
Definition at line 141 of file rc_gen_movie_file.h.
Referenced by addFrame(), flush(), frameSize(), initHeader(), and open().
rcMovieFileFormat2 rcGenMovieFile::_movieHdr2 private
Definition at line 142 of file rc_gen_movie_file.h.
Referenced by addFrame(), flush(), frameSize(), initHeader(), and open().
vector<rcMovieFileOrgExt> rcGenMovieFile::_orgHdrs private
Definition at line 136 of file rc_gen_movie_file.h.
Referenced by addHeader(), and flush().
movieOriginType rcGenMovieFile::_origin private
Definition at line 139 of file rc_gen_movie_file.h.
Referenced by addFrame(), flush(), and initHeader().
bool rcGenMovieFile::_overWrite private
Definition at line 148 of file rc_gen_movie_file.h.
Referenced by rcGenMovieFile().
movieFormatRev rcGenMovieFile::_rev private
Definition at line 144 of file rc_gen_movie_file.h.
Referenced by addFrame(), flush(), frameSize(), initHeader(), and open().
FILE* rcGenMovieFile::_saveStream private
Definition at line 146 of file rc_gen_movie_file.h.
Referenced by flush(), open(), and write().
vector<int64> rcGenMovieFile::_toc private
Definition at line 133 of file rc_gen_movie_file.h.
Referenced by addFrame(), flush(), and frameSize().
bool rcGenMovieFile::_verbose private
Definition at line 151 of file rc_gen_movie_file.h.
Referenced by flush().
The documentation for this class was generated from the following files:
include/visual/rc_gen_movie_file.h
src/visual/code/rc_gen_movie_file.cpp