Visible: rcMonitor Class Reference
rcMonitor Class Reference
#include <include/visUI/rc_monitor.h>
Public Slots
void updateDisplay (const rcWindow *image)
void updateDisplay (const rcVisualGraphicsCollection *graphics)
void updateDisplay (void)
void updateAnalysisRect (const rcRect &rect)
void updateAnalysisRectRotation (const rcAffineRectangle &)
void updateTime (const rcTimestamp &time)
void updateCursorTime (const rcTimestamp &time)
void updateState (rcExperimentState)
void updateScale (double)
void updateMonitorSize (const rcRect &size)
void scaleChanged (int)
void settingChanged ()
void saturationChanged (bool)
Public Member Functions
rcMonitor (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
~rcMonitor ()
bool inputIsCamera () const
bool inputIsStored () const
void setMaxScale (int scale)
void updateStatus ()
QRect imageRect () const
Protected Member Functions
void paintEvent (QPaintEvent *paintEvent)
void resizeEvent (QResizeEvent *sizeEvent)
void mousePressEvent (QMouseEvent *mouseEvent)
void mouseReleaseEvent (QMouseEvent *mouseEvent)
void mouseMoveEvent (QMouseEvent *mouseEvent)
void keyPressEvent (QKeyEvent *keyEvent)
void keyReleaseEvent (QKeyEvent *keyEvent)
Private Member Functions
bool scaleChanged (int, bool updateWidget)
bool updateCachedImage (const rcWindow *image)
void deleteCachedImage ()
void displayTrackFocus (rcTrackType trackType)
void displayScalarFocusArea (const rcRect &rect, rcTrackInfo &info)
rcRect paintScalarTrackFocus (rcTimestamp currentTime, rcTrack *track, rcTrackInfo &info)
void paintVideoTrackFocus (rcTimestamp currentTime, rcTrack *track)
void internalUpdateDisplay (void)
void gatherTrackData (rcVisualGraphicsCollectionCollection &globalGraphics, rcVisualGraphicsCollectionCollection &cellGraphics, rcTextSegmentCollection &texts) const
void gatherDevelopmentTrackData (rcVisualGraphicsCollectionCollection &globalGraphics, rcVisualGraphicsCollectionCollection &cellGraphics, rcTextSegmentCollection &texts) const
bool getPosition (rcTimestamp cursorTime, rcTrack *track, rcFPair &pos, rcRect &rect) const
bool addGraphics (rcTimestamp cursorTime, rcTrack *track, rcVisualGraphicsCollectionCollection &globalGraphics) const
void buildPositionCross (const rcFPair &pos, rcVisualGraphicsCollection &graphics) const
void buildCellBoundary (const rcRect &rect, rcVisualGraphicsCollection &graphics) const
void buildPositionPath (const rcTimestamp &cursorTime, rcTrack *track, rcVisualGraphicsCollection &graphics) const
bool showDevelopmentData () const
Private Attributes
rcTimestamp mCursorTime
rcImageCanvasGL * mCanvas
Q3BoxLayout * mTopLayout
Q3BoxLayout * mStatusLayout
QSpinBox * mScaleWidget
QLabel * mStatusWidget
QCheckBox * mSaturationWidget
QLabel * mSaturationWidgetLabel
rcFpsCalculator mSpeedCalc
QColor mBackgroundColor
bool mCellText
bool mCellPos
bool mCellPath
bool mDevelopmentData
Detailed Description
Definition at line 41 of file rc_monitor.h.
Constructor & Destructor Documentation
rcMonitor::rcMonitor (QWidget * parent = 0, const char * name = 0, Qt::WFlags f = 0)
Definition at line 61 of file rc_monitor.cpp.
References cCursorTimeCurrent, cMaxScaleFactor, cMinScaleFactor, cScaleUpFactor, cWidgetBackgroundMode, rcModelDomain::getModelDomain(), mBackgroundColor, mCanvas, mCellPath, mCellPos, mCellText, mCursorTime, mDevelopmentData, mSaturationWidget, mSaturationWidgetLabel, mScaleWidget, mStatusLayout, mStatusWidget, mTopLayout, red, rmUnused, saturationChanged(), scaleChanged(), settingChanged(), updateAnalysisRect(), updateAnalysisRectRotation(), updateCursorTime(), updateDisplay(), updateMonitorSize(), updateScale(), updateState(), and updateTime().
         : QWidget( parent, name ), mSpeedCalc( 15 )
 {
     rmUnused( f );
     mCellText = mCellPath = mCellPos = mDevelopmentData = false;
     mCursorTime = cCursorTimeCurrent;
     // Create top level layout
     mTopLayout = new Q3VBoxLayout( this );
     mTopLayout->setAlignment( Qt::AlignLeft | Qt::AlignBottom );
     // 2D information display
     mCanvas = new rcImageCanvasGL( this );
     mTopLayout->addWidget( mCanvas );
     mTopLayout->setStretchFactor( mCanvas, 20 );
     // Create a horizontal layout
     mStatusLayout = new Q3HBoxLayout( mTopLayout );
     mStatusLayout->setAlignment( Qt::AlignRight | Qt::AlignBottom );
     mStatusLayout->addSpacing( 2 );
     // Create scale control widget
     mScaleWidget = new QSpinBox( int(cMinScaleFactor*100), int(cMaxScaleFactor*100), int(cScaleUpFactor*100), this, "scale" );
     mScaleWidget->setSuffix( " %" );
     mScaleWidget->setValue( static_cast<int>(100) );
     QToolTip::add( mScaleWidget, "Image scale factor" );
     mScaleWidget->setMaximumWidth( fontMetrics().width('M') * 7 );
     mStatusLayout->addWidget( mScaleWidget );
     connect( mScaleWidget , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( scaleChanged( int ) ) );
     // Create saturation detector widget label
     mSaturationWidgetLabel = new QLabel( this );
     mSaturationWidgetLabel->setText( "Sat" );
     mSaturationWidgetLabel->setTextFormat( Qt::PlainText );
     mSaturationWidgetLabel->setAlignment( Qt::AlignAuto | Qt::AlignVCenter | Qt::SingleLine );
     QToolTip::add( mSaturationWidgetLabel, "Enable/disable saturated pixel coloring (red)" );
     mStatusLayout->addWidget( mSaturationWidgetLabel );
     mSaturationWidgetLabel->setPaletteForegroundColor( Qt::red );
     // Create saturation detector widget
     mSaturationWidget = new QCheckBox( this );
     QToolTip::add( mSaturationWidget, "Enable/disable saturated pixel coloring (red)" );
     mSaturationWidget->setChecked( true );
     mStatusLayout->addWidget( mSaturationWidget );
     mStatusLayout->addSpacing( 2 );
     connect( mSaturationWidget , SIGNAL( toggled( bool ) ) , this , SLOT( saturationChanged( bool ) ) );
     // Create status display widget
     mStatusWidget = new QLabel( this );
     mStatusWidget->setFrameStyle( Q3Frame::WinPanel | Q3Frame::Sunken );
     mStatusWidget->setFixedHeight( fontMetrics().height() + 4 );
     mStatusWidget->setMinimumWidth( fontMetrics().width('M') * 40 );
     // Make the text format as simple as possible for speed
     mStatusWidget->setTextFormat( Qt::PlainText );
     mStatusWidget->setAlignment( Qt::AlignAuto | Qt::AlignVCenter | Qt::SingleLine );
     QToolTip::add( mStatusWidget, "Image status details" );
     mStatusLayout->addWidget( mStatusWidget );
     mStatusLayout->setStretchFactor( mStatusWidget, 10 );
     // Receive mouse events even when no buttons are pressed
     setMouseTracking( true );
     // Gets (keyboard) focus by mouse clicking
     setFocusPolicy( Qt::ClickFocus );
     // Connect image display refresh
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateDisplay( const rcWindow* ) ) ,
              this   , SLOT( updateDisplay( const rcWindow* ) ) );
     connect( domain , SIGNAL( updateDisplay( const rcVisualGraphicsCollection* ) ) ,
              this   , SLOT( updateDisplay( const rcVisualGraphicsCollection* ) ) );
     connect( domain , SIGNAL( updateDisplay( void ) ) ,
              this   , SLOT( updateDisplay( void ) ) );
     connect( domain , SIGNAL( updateMonitorDisplay( void ) ) ,
              this   , SLOT( updateDisplay( void ) ) );
     connect( domain , SIGNAL( updateDebugging( void ) ) ,
              this   , SLOT( updateDisplay( void ) ) );
     connect( domain , SIGNAL( updateAnalysisRect( const rcRect& ) ) ,
              this   , SLOT( updateAnalysisRect( const rcRect& ) ) );
     connect( domain , SIGNAL( elapsedTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( cursorTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateCursorTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     connect( domain , SIGNAL( updateMonitorScale( double ) ),
              this   , SLOT( updateScale( double ) ) );
     connect( domain , SIGNAL( updateVideoRect( const rcRect& ) ) ,
              this   , SLOT( updateMonitorSize( const rcRect& ) ) );
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              mCanvas   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateAnalysisRectRotation( const rcAffineRectangle& ) ) ,
              this   , SLOT( updateAnalysisRectRotation( const rcAffineRectangle& ) ) );
     // Use a fixed color to erase background, it's faster than default widget erase pixmap
     mBackgroundColor = QColor( 238, 238, 238 );
     setBackgroundMode( cWidgetBackgroundMode, cWidgetBackgroundMode );
     setPaletteBackgroundColor( mBackgroundColor );
     mStatusWidget->setPaletteBackgroundColor( mBackgroundColor );
     mStatusWidget->setBackgroundMode( cWidgetBackgroundMode, cWidgetBackgroundMode );
     mSaturationWidgetLabel->setPaletteBackgroundColor( mBackgroundColor );
     mSaturationWidgetLabel->setBackgroundMode( cWidgetBackgroundMode, cWidgetBackgroundMode );
     // TODO: saturation checkbox has some white background, fix it
     mSaturationWidget->setPaletteBackgroundColor( mBackgroundColor );
     mSaturationWidget->setBackgroundMode( cWidgetBackgroundMode, cWidgetBackgroundMode );
     mScaleWidget->setPaletteBackgroundColor( mBackgroundColor );
     mScaleWidget->setBackgroundMode( cWidgetBackgroundMode, cWidgetBackgroundMode );
 }
rcMonitor::~rcMonitor ()
Definition at line 191 of file rc_monitor.cpp.
References deleteCachedImage(), mSaturationWidget, mSaturationWidgetLabel, mScaleWidget, and mStatusWidget.
 {
     deleteCachedImage();
     // Remove old tips
     QToolTip::remove( this );
     QToolTip::remove( mScaleWidget );
     QToolTip::remove( mStatusWidget );
     QToolTip::remove( mSaturationWidget );
     QToolTip::remove( mSaturationWidgetLabel );
 }
Member Function Documentation
bool rcMonitor::addGraphics (rcTimestamp cursorTime, rcTrack * track, rcVisualGraphicsCollectionCollection & globalGraphics) const private
Definition at line 723 of file rc_monitor.cpp.
References cCursorTimeCurrent, rcSegmentIterator::contains(), rcGraphicsTrack::getDataSegmentIterator(), and rcGraphicsSegmentIterator::getValue().
Referenced by gatherDevelopmentTrackData(), and gatherTrackData().
 {
     bool valid = false;
     rcGraphicsTrack* graphicsTrack = dynamic_cast<rcGraphicsTrack*>( track );
     if ( graphicsTrack == 0 )
         return valid;
     if ( cursorTime != cCursorTimeCurrent ) {
         rcGraphicsSegmentIterator* iter = graphicsTrack->getDataSegmentIterator( cursorTime );
         if ( iter->contains( cursorTime ) ) {
             // Current segment contains cursorTime
             globalGraphics.push_back( iter->getValue() );
             valid = true;
         }
         delete iter;
     }
     return valid;
 }
void rcMonitor::buildCellBoundary (const rcRect & rect, rcVisualGraphicsCollection & graphics) const private
Definition at line 813 of file rc_monitor.cpp.
References rcRectangle< T >::height(), rcVisualGraphicsCollection::segments(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
Referenced by gatherTrackData().
 {
     // Get cross for each cell
     rcVisualSegmentCollection& segments = graphics.segments();
     rcVisualRect bounds( rect.x(), rect.y(), rect.width(), rect.height() );
     segments.push_back( bounds );
 }
void rcMonitor::buildPositionCross (const rcFPair & pos, rcVisualGraphicsCollection & graphics) const private
Definition at line 802 of file rc_monitor.cpp.
References rcVisualGraphicsCollection::segments(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by gatherTrackData().
 {
     // Get cross for each cell
     rcVisualSegmentCollection& segments = graphics.segments();
     rcVisualCross cross( rc2Fvector( pos.x(), pos.y() ),
                          rc2Fvector( cPositionCrossLength, cPositionCrossLength ) );
     segments.push_back( cross );
 }
void rcMonitor::buildPositionPath (const rcTimestamp & cursorTime, rcTrack * track, rcVisualGraphicsCollection & graphics) const private
Definition at line 746 of file rc_monitor.cpp.
References rcSegmentIterator::advance(), cCursorTimeCurrent, cZeroTime, rcPositionTrack::getDataSegmentIterator(), rcSegmentIterator::getSegmentCount(), rcSegmentIterator::getSegmentStartAbsolute(), rcPositionSegmentIterator::getValue(), rcSegmentIterator::lock(), rcVisualGraphicsCollection::segments(), rcSegmentIterator::unlock(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by gatherTrackData().
 {
     rcPositionTrack* posTrack = dynamic_cast<rcPositionTrack*>( track );
     if ( posTrack == 0 )
         return;
     if ( cursorTime != cCursorTimeCurrent ) {
         rcPositionSegmentIterator* iter = posTrack->getDataSegmentIterator( cZeroTime );
         const uint32 segmentCount = iter->getSegmentCount();
         if ( segmentCount > 0 ) {
             rcFPair prevPos( 0, 0 );
             // Lock iterator for the total duration of value access
             iter->lock();
             // Gather points in point array
             vector<rcFPair> posPoints;
             posPoints.reserve( segmentCount );
             // Accumulate all values up to current time
             while ( iter->getSegmentStartAbsolute() <= cursorTime ) {
                 const rcFPair pos = iter->getValue();
                 // Add only unique points
                 if ( pos != prevPos ) {
                     // Add one point to array
                     posPoints.push_back( pos );
                     prevPos = pos;
                 }
                 if ( ! iter->advance( 1, false ) ) // Unlocked advance for speed
                     break;
             }
             if ( !posPoints.empty() ) {
                 // Add one more point if number of points is odd
                 if ( posPoints.size() % 2 )
                     posPoints.push_back( posPoints.back() );
                 // Build line strip collection
                 rcVisualSegmentCollection& lines = graphics.segments();
                 lines.reserve( lines.size() + posPoints.size()/2 );
                 uint32 size = posPoints.size()-1;
                 for ( uint32 i = 0; i < size; i +=2 ) {
                     const rcFPair& pos = posPoints[i];
                     const rcFPair& pos2 = posPoints[i+1];
                     rcVisualLineStrip line( rc2Fvector( pos.x(), pos.y() ),
                                             rc2Fvector( pos2.x(), pos2.y()) );
                     lines.push_back( line );
                 }
             }
             iter->unlock();
         }
         delete iter;
     }
 }
void rcMonitor::deleteCachedImage () private
Definition at line 857 of file rc_monitor.cpp.
References cTextStyle, rcImageCanvasGL::loadrcWindow(), mCanvas, and mSaturationWidget.
Referenced by updateDisplay(), updateState(), and ~rcMonitor().
 {
     // Delete all canvas data
     rcVisualGraphicsCollectionCollection lines;
     rcTextSegmentCollection textSegments;
     rcTextCollection texts( cTextStyle, textSegments );
     rcWindow empty;
     mCanvas->loadrcWindow( empty, lines, lines, texts,
                            mSaturationWidget->isEnabled() && mSaturationWidget->isChecked() );
 }
void rcMonitor::displayScalarFocusArea (const rcRect & rect, rcTrackInfo & info) private
Definition at line 868 of file rc_monitor.cpp.
References rcTrackInfo::getPen(), rcRectangle< T >::height(), rmUnused, rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
Referenced by paintScalarTrackFocus().
 {
 #if 0
     if ( rect.width() > 0 && rect.height() > 0 ) {
         QPainter paint( this );
         // Use the same pen the timeline graph uses
         paint.setPen( trackInfo.getPen() );
         // Focus area is in model coords, tranform it to device coords
         rcRect devRect = modelToDevCoord( rect );
         paint.drawRect( devRect.x(),
                         devRect.y(),
                         devRect.width(),
                         devRect.height() );
     }
 #else
     // TODO: implement this
     rmUnused( rect );
     rmUnused( trackInfo );
 #endif
 }
void rcMonitor::displayTrackFocus (rcTrackType trackType) private
Definition at line 500 of file rc_monitor.cpp.
References eScalarTrack, eVideoTrack, eWriterVideo, eWriterVideoDevelopment, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getNTrackGroups(), rcTrackGroup::getNTracks(), rcTrack::getTag(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackInfo(), rcTrackManager::getTrackManager(), rcTrack::getTrackType(), rcTrackInfo::isEnabled(), mCursorTime, paintVideoTrackFocus(), rmAssert, showDevelopmentData(), rcWriterManager::tagType(), and updateCachedImage().
Referenced by internalUpdateDisplay().
 {
     // draw focus of each data track.
     bool drawCurrentFocus = false;
     if ( trackType == eScalarTrack )
         drawCurrentFocus = true;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     int lastVideoGroup = -1;
     int lastVideoTrack = -1;
     rcWriterSemantics wantedTrack = eWriterVideo;
     if ( showDevelopmentData() )
         wantedTrack = eWriterVideoDevelopment;
     // paint video track focus areas (and raw full frame video, too)
     int nTrackGroups = experiment->getNTrackGroups();
     for (int i = 0; i < nTrackGroups; i++)
     {
         rcTrackGroup* trackGroup = experiment->getTrackGroup( i );
         int nTracks = trackGroup->getNTracks();
         for ( int j = 0; j < nTracks; j++)
         {
             rcTrack* track = trackGroup->getTrack( j );
             if ( track->getTrackType() == trackType )
             {
                 switch ( trackType ) {
                     case eVideoTrack:
                         if ( rcWriterManager::tagType( track->getTag() ) == wantedTrack ) {
                             rcTrackInfo trackInfo = tmp->getTrackInfo( i, j );
                             if ( trackInfo.isEnabled() ) {
                                 lastVideoGroup = i;
                                 lastVideoTrack = j;
                             }
                         }
                         break;
                     default:
                         rmAssert( 0 );
                         break;
                 }
             }
         }
     }
     // Display only last valid track, there is no video overlay support yet
     if ( lastVideoGroup >= 0 && lastVideoTrack >= 0 ) {
             rcTrackGroup* trackGroup = experiment->getTrackGroup( lastVideoGroup );
             rcTrack* track = trackGroup->getTrack( lastVideoTrack );
             paintVideoTrackFocus( mCursorTime, track );
     } else {
         // Paint graphics and text with no video
         rcWindow empty;
         updateCachedImage( &empty );
     }
 }
void rcMonitor::gatherDevelopmentTrackData (rcVisualGraphicsCollectionCollection & globalGraphics, rcVisualGraphicsCollectionCollection & cellGraphics, rcTextSegmentCollection & texts) const private
Definition at line 646 of file rc_monitor.cpp.
References addGraphics(), eGraphicsTrack, eWriterGraphicsDevelopment, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getNTrackGroups(), rcTrackGroup::getNTracks(), rcTrack::getTag(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackInfo(), rcTrackManager::getTrackManager(), rcTrack::getTrackType(), rcTrackInfo::isEnabled(), mCursorTime, rmUnused, rcTimestamp::secs(), and rcWriterManager::tagType().
Referenced by updateCachedImage().
 {
     rmUnused( cellGraphics );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     // paint video track focus areas (and raw full frame video, too)
     int nTrackGroups = experiment->getNTrackGroups();
     for (int i = 0; i < nTrackGroups; i++)
     {
         rcTrackGroup* trackGroup = experiment->getTrackGroup( i );
         int nTracks = trackGroup->getNTracks();
         for ( int j = 0; j < nTracks; j++)
         {
             rcTrack* track = trackGroup->getTrack( j );
             rcTrackType trackType = track->getTrackType();
             switch ( trackType ) {
                 case eGraphicsTrack:
                 {
                     if ( rcWriterManager::tagType( track->getTag() ) == eWriterGraphicsDevelopment ) {
                         rcTrackInfo trackInfo = tmp->getTrackInfo( i , j );
                         if ( trackInfo.isEnabled() ) {
                             // Gather all graphics
                             addGraphics( mCursorTime, track, globalGraphics );
                         }
                     }
                 }
                 break;
                 default:
                     break;
             }
         }
     }
     // Write our frame count
     rc2Fvector z;
     ostringstream os;
     os<< "Development Display [" << mCursorTime.secs() << "]";
     rcTextSegment text( rc2Fvector(0.0f, 0.0f), os.str());
     texts.push_back( text );
 }
void rcMonitor::gatherTrackData (rcVisualGraphicsCollectionCollection & globalGraphics, rcVisualGraphicsCollectionCollection & cellGraphics, rcTextSegmentCollection & texts) const private
Definition at line 561 of file rc_monitor.cpp.
References addGraphics(), buildCellBoundary(), buildPositionCross(), buildPositionPath(), cPositionCrossStyle, eGraphicsTrack, ePositionTrack, eWriterBodyPosition, eWriterGraphicsDevelopment, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getName(), rcExperiment::getNTrackGroups(), rcTrackGroup::getNTracks(), getPosition(), rcTrack::getTag(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackInfo(), rcTrackManager::getTrackManager(), rcTrack::getTrackType(), rcTrackInfo::isEnabled(), mCellPath, mCellPos, mCellText, mCursorTime, rcWriterManager::tagType(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by updateCachedImage().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     // paint video track focus areas (and raw full frame video, too)
     int nTrackGroups = experiment->getNTrackGroups();
     for (int i = 0; i < nTrackGroups; i++)
     {
         rcTrackGroup* trackGroup = experiment->getTrackGroup( i );
         int nTracks = trackGroup->getNTracks();
         for ( int j = 0; j < nTracks; j++)
         {
             rcTrack* track = trackGroup->getTrack( j );
             rcTrackType trackType = track->getTrackType();
             switch ( trackType ) {
                 case ePositionTrack:
                 {
                     rcTrackInfo trackInfo = tmp->getTrackInfo( i , j );
                     if ( trackInfo.isEnabled() ) {
                         // Use only body position values (there are other position tracks with other data)
                         if ( rcWriterManager::tagType( track->getTag() ) == eWriterBodyPosition ) {
                             rcFPair pos;
                             rcRect rect;
                             bool validPosition = getPosition( mCursorTime, track, pos, rect );
                             if ( validPosition ) {
                                 // Make a line segment collection with drawing style
                                 rcVisualSegmentCollection lines;
                                 rcVisualGraphicsCollection posGraphics( cPositionCrossStyle, lines );
                                 // TBD: can we get the whole path from kinetoscope or do we need
                                 // to accumulate cell positions?
                                 if ( mCellPath ) {
                                     // Get cumulative position path for each cell
                                     buildPositionPath( mCursorTime, track, posGraphics );
                                 }
                                 if ( mCellPos ) {
                                     // Get cross for each cell
                                     buildPositionCross( pos, posGraphics );
                                 }
 #ifdef notyet // We probably want the rect from a separate data track
                                 if ( mCellPos ) {
                                     // Get boundary for each cell
                                     buildCellBoundary( rect, posGraphics );
                                 }
 #endif
                                 cellGraphics.push_back( posGraphics );
                                 if ( mCellText ) {
                                     // Get name for each cell
                                     std::string cellName = trackGroup->getName();
                                     rcTextSegment text( rc2Fvector(pos.x(), pos.y()), cellName );
                                     texts.push_back( text );
                                 }
                             }
                         }
                     }
                 }
                 break;
                 case eGraphicsTrack:
                 {
                     if ( rcWriterManager::tagType( track->getTag() ) != eWriterGraphicsDevelopment ) {
                         rcTrackInfo trackInfo = tmp->getTrackInfo( i , j );
                         if ( trackInfo.isEnabled() ) {
                             // Gather all graphics
                             addGraphics( mCursorTime, track, globalGraphics );
                         }
                     }
                 }
                 break;
                 default:
                     break;
             }
         }
     }
 }
bool rcMonitor::getPosition (rcTimestamp cursorTime, rcTrack * track, rcFPair & pos, rcRect & rect) const private
Definition at line 695 of file rc_monitor.cpp.
References cCursorTimeCurrent, rcSegmentIterator::contains(), rcImageCanvasGL::focusRect(), rcPositionTrack::getDataSegmentIterator(), rcSegmentIterator::getFocus(), rcPositionSegmentIterator::getValue(), mCanvas, rcRectangle< T >::ul(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by gatherTrackData().
 {
     bool valid = false;
     rcPositionTrack* pTrack = dynamic_cast<rcPositionTrack*>( track );
     if ( pTrack == 0 )
         return valid;
     if ( cursorTime != cCursorTimeCurrent ) {
         rcPositionSegmentIterator* iter = pTrack->getDataSegmentIterator( cursorTime );
         if ( iter->contains( cursorTime ) ) {
             // Current segment contains cursorTime
       // Get focus rect position in the frame
       rcRect fr = mCanvas->focusRect ();
             pos = iter->getValue();
         pos.x() = pos.x() + fr.ul().x();
         pos.y() = pos.y() + fr.ul().y();
             rect = iter->getFocus();
             valid = true;
         }
         delete iter;
     }
     return valid;
 }
QRect rcMonitor::imageRect () const
Definition at line 929 of file rc_monitor.cpp.
References rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcModelDomain::getExperimentAttributes(), and rcModelDomain::getModelDomain().
Referenced by rcImageCanvasGL::mouseReleaseEvent().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     uint32 maxX = domain->getExperimentAttributes().frameWidth;
     uint32 maxY = domain->getExperimentAttributes().frameHeight;
     return QRect( 0, 0, maxX, maxY );
 }
bool rcMonitor::inputIsCamera () const
Definition at line 954 of file rc_monitor.cpp.
References rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), and rcExperimentAttributes::liveInput.
Referenced by internalUpdateDisplay(), saturationChanged(), settingChanged(), rcImageCanvasGL::statusString(), and updateStatus().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     return domain->getExperimentAttributes().liveInput;
 }
bool rcMonitor::inputIsStored () const
Definition at line 961 of file rc_monitor.cpp.
References rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), and rcExperimentAttributes::liveStorage.
Referenced by keyPressEvent(), settingChanged(), updateDisplay(), updateScale(), and updateState().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     return domain->getExperimentAttributes().liveStorage;
 }
void rcMonitor::internalUpdateDisplay (void) private
Definition at line 939 of file rc_monitor.cpp.
References displayTrackFocus(), eScalarTrack, eVideoTrack, inputIsCamera(), and updateStatus().
Referenced by paintEvent(), settingChanged(), updateAnalysisRect(), updateAnalysisRectRotation(), updateCursorTime(), updateDisplay(), and updateScale().
 {
     if ( !inputIsCamera() ) {
         // This method updates cached image if appropriate
         displayTrackFocus( eVideoTrack );
 #if 0
         displayTrackFocus( eScalarTrack );
 #endif
     }
     updateStatus();
 }
void rcMonitor::keyPressEvent (QKeyEvent * keyEvent) protected
Definition at line 470 of file rc_monitor.cpp.
References inputIsStored().
 {
     // No zoom/pan allowed during live storage
     if ( inputIsStored() )
         return;
     keyEvent->ignore();
 }
void rcMonitor::keyReleaseEvent (QKeyEvent * keyEvent) protected
Definition at line 479 of file rc_monitor.cpp.
 {
     keyEvent->ignore();
 }
void rcMonitor::mouseMoveEvent (QMouseEvent * mouseEvent) protected
Definition at line 438 of file rc_monitor.cpp.
References rmUnused.
 {
     rmUnused( mouseEvent );
 }
void rcMonitor::mousePressEvent (QMouseEvent * mouseEvent) protected
Definition at line 433 of file rc_monitor.cpp.
References rmUnused.
 {
     rmUnused( mouseEvent );
 }
void rcMonitor::mouseReleaseEvent (QMouseEvent * mouseEvent) protected
Definition at line 443 of file rc_monitor.cpp.
References focusCompare(), rcTrackManager::getTrackManager(), rmUnused, and rcTrackManager::setHiliteTrack().
 {
     rmUnused( mouseEvent );
 #if 0
     // Just a simple click
     deque<rcFocusTrack> tracks;
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     // Check if existing focus areas were hit
     if ( findFocusTracks( p, tracks ) > 0 ) {
             // Get the track (focus area) with the shortest distance to p
         partial_sort( tracks.begin(), tracks.begin()+1, tracks.end(), focusCompare );
         // Highlight the track
         tmp->setHiliteTrack( -1 , -1 );
         tmp->setHiliteTrack( tracks[0]._trackGroupNo , tracks[0]._trackNo );
         // Update current analysis rect
         domain->notifyAnalysisRect( tracks[0]._focusRect );
     } else {
         // Nothing hit, erase current focus and highlighting
         tmp->setHiliteTrack( -1 , -1 );
         newRect.setHeight( 0 );
         newRect.setWidth( 0 );
         domain->notifyAnalysisRect( newRect );
     }
 #endif
 }
void rcMonitor::paintEvent (QPaintEvent * paintEvent) protected
Definition at line 422 of file rc_monitor.cpp.
References internalUpdateDisplay().
 {
     internalUpdateDisplay();
 }
rcRect rcMonitor::paintScalarTrackFocus (rcTimestamp currentTime, rcTrack * track, rcTrackInfo & info) private
Definition at line 891 of file rc_monitor.cpp.
References cCursorTimeCurrent, rcSegmentIterator::contains(), displayScalarFocusArea(), rcScalarTrack::getDataSegmentIterator(), and rcSegmentIterator::getFocus().
 {
     rcRect focusRect;
     rcScalarTrack* scalarTrack = dynamic_cast<rcScalarTrack*>( track );
     if ( scalarTrack == 0 )
         return focusRect;
     if ( cursorTime != cCursorTimeCurrent ) {
         rcScalarSegmentIterator* iter = scalarTrack->getDataSegmentIterator( cursorTime );
         if ( iter->contains( cursorTime ) ) {
             focusRect = iter->getFocus();
             displayScalarFocusArea( focusRect, trackInfo );
         }
         delete iter;
     }
     return focusRect;
 }
void rcMonitor::paintVideoTrackFocus (rcTimestamp currentTime, rcTrack * track) private
Definition at line 912 of file rc_monitor.cpp.
References cCursorTimeCurrent, rcVideoTrack::getDataSegmentIterator(), rcVideoTrack::getSegmentCount(), rcVideoSegmentIterator::getValue(), and updateCachedImage().
Referenced by displayTrackFocus().
 {
     rcVideoTrack* videoTrack = dynamic_cast<rcVideoTrack*>( track );
     if ( videoTrack == 0 )
         return;
     if ( cursorTime != cCursorTimeCurrent ) {
         if ( videoTrack->getSegmentCount() > 0 ) {
             rcVideoSegmentIterator* iter = videoTrack->getDataSegmentIterator( cursorTime );
             rcWindow image = iter->getValue();
             updateCachedImage( &image );
             delete iter;
         }
     }
 }
void rcMonitor::resizeEvent (QResizeEvent * sizeEvent) protected
Definition at line 427 of file rc_monitor.cpp.
 {
 }
void rcMonitor::saturationChanged (bool enabled) slot
Definition at line 380 of file rc_monitor.cpp.
References inputIsCamera(), mCanvas, and rcImageCanvasGL::showSaturatedPixels().
Referenced by rcMonitor().
 {
     // With camera input the next image will obey the setting
     if ( !inputIsCamera() )
         mCanvas->showSaturatedPixels( enabled );
 }
void rcMonitor::scaleChanged (int scale) slot
Definition at line 300 of file rc_monitor.cpp.
References FALSE.
Referenced by rcMonitor(), and updateScale().
 {
     scaleChanged( scale, FALSE );
 }
bool rcMonitor::scaleChanged (int scale, bool updateWidget) private
Definition at line 487 of file rc_monitor.cpp.
References mCanvas, mScaleWidget, rcImageCanvasGL::scaleChanged(), and updateStatus().
 {
     scale = int(100 * mCanvas->scaleChanged( scale/100.0 ));
     // Update widget
     if ( updateWidget )
         mScaleWidget->setValue( scale );
     updateStatus();
     return true;
 }
void rcMonitor::setMaxScale (int scale)
Definition at line 388 of file rc_monitor.cpp.
References mScaleWidget.
 {
     mScaleWidget->setMaxValue( scale );
 }
void rcMonitor::settingChanged (void) slot
Definition at line 306 of file rc_monitor.cpp.
References cMaxHeight, cMaxWidth, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getNSettingCategories(), rcExperiment::getSettingCategory(), rcSettingCategory::getSettingInfo(), rcSettingCategory::getTag(), rcSettingInfo::getValue(), inputIsCamera(), inputIsStored(), internalUpdateDisplay(), mCellPath, mCellPos, mCellText, mDevelopmentData, mSaturationWidget, mSaturationWidgetLabel, and mScaleWidget.
Referenced by rcMonitor().
 {
     // Update scale widget
     mScaleWidget->setEnabled( !inputIsStored() );
     // TBD: should we enable saturation indicator in non-capture mode?
     // Update saturation widget
     mSaturationWidget->setEnabled( inputIsCamera() );
     // Hide saturation widget if the setting is currently not enabled.
     if ( mSaturationWidget->isHidden() && mSaturationWidget->isEnabled() )
     {
         mSaturationWidget->setChecked( true );
         mSaturationWidget->show();
         mSaturationWidgetLabel->show();
     }
     else if ( !mSaturationWidget->isHidden() && !mSaturationWidget->isEnabled() )
     {
         mSaturationWidget->hide();
         mSaturationWidgetLabel->hide();
     }
     // Disable resizing for capture
     if ( inputIsStored() ) {
         setMaximumSize( size() );
     } else {
         setMaximumSize( QSize( cMaxWidth, cMaxHeight ) );
     }
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     int nPages = experiment->getNSettingCategories();
     for (int i = 0; i < nPages; i++)
     {
         rcSettingCategory category = experiment->getSettingCategory( i );
         // Look for cell visualization settings
         if ( !strcmp( category.getTag(), "visualization-settings" ) ) {
             const rcSettingInfo path = category.getSettingInfo( "visualize-cell-path" );
             const rcSettingInfo position = category.getSettingInfo( "visualize-cell-position" );
             const rcSettingInfo text = category.getSettingInfo( "visualize-cell-text" );
             const rcSettingInfo dev = category.getSettingInfo( "visualize-development-data" );
             bool changed = false;
             int value = int(path.getValue());
             if ( value != mCellPath ) {
                 mCellPath = value;
                 changed = true;
             }
             value = int(position.getValue());
             if ( value != mCellPos ) {
                 mCellPos = value;
                 changed = true;
             }
             value = int(text.getValue());
             if ( value != mCellText ) {
                 mCellText = value;
                 changed = true;
             }
             value = int(dev.getValue());
             if ( value != mDevelopmentData ) {
                 mDevelopmentData = value;
                 changed = true;
             }
             if ( changed ) {
                 // Update whole widget
                 internalUpdateDisplay();
             }
         }
     }
 }
bool rcMonitor::showDevelopmentData () const private
Definition at line 968 of file rc_monitor.cpp.
References mDevelopmentData.
Referenced by displayTrackFocus(), and updateCachedImage().
 {
     return mDevelopmentData;
 }
void rcMonitor::updateAnalysisRect (const rcRect & rect) slot
Definition at line 248 of file rc_monitor.cpp.
References internalUpdateDisplay(), mCanvas, and rcImageCanvasGL::updateAnalysisRect().
Referenced by rcMonitor().
 {
     mCanvas->updateAnalysisRect( rect );
     internalUpdateDisplay();
 }
void rcMonitor::updateAnalysisRectRotation (const rcAffineRectangle & affine) slot
Definition at line 254 of file rc_monitor.cpp.
References internalUpdateDisplay(), mCanvas, and rcImageCanvasGL::updateAnalysisRectRotation().
Referenced by rcMonitor().
 {
   mCanvas->updateAnalysisRectRotation( affine );
   internalUpdateDisplay();
 }
bool rcMonitor::updateCachedImage (const rcWindow * image) private
Definition at line 823 of file rc_monitor.cpp.
References rcFpsCalculator::addTime(), cTextStyle, endl(), gatherDevelopmentTrackData(), gatherTrackData(), rcImageCanvasGL::loadrcWindow(), mCanvas, mSaturationWidget, mSpeedCalc, rcTimestamp::now(), and showDevelopmentData().
Referenced by displayTrackFocus(), paintVideoTrackFocus(), and updateDisplay().
 {
     bool wasAdded = false;
     if ( image ) {
         mSpeedCalc.addTime( rcTimestamp::now() );
         bool showSaturated = false;
         // Saturation display
         if ( mSaturationWidget->isEnabled() && mSaturationWidget->isChecked() ) {
             showSaturated = true;
         }
         // Gather displayble graphics and text
         rcVisualGraphicsCollectionCollection globalGraphics, cellGraphics;
         rcTextSegmentCollection textSegments;
         if ( showDevelopmentData() )
             gatherDevelopmentTrackData( globalGraphics, cellGraphics, textSegments );
         else
             gatherTrackData( globalGraphics, cellGraphics, textSegments );
         rcTextCollection texts( cTextStyle, textSegments );
         // Update OpenGL canvas
         mCanvas->loadrcWindow( *image, globalGraphics, cellGraphics, texts, showSaturated );
         wasAdded = true;
     }
 #ifdef DEBUG_LOG
     if ( wasAdded == false )
         cout << "updateCachedImage NOP" << endl;
 #endif
     return wasAdded;
 }
void rcMonitor::updateCursorTime (const rcTimestamp & time) slot
Definition at line 211 of file rc_monitor.cpp.
References internalUpdateDisplay(), and mCursorTime.
Referenced by rcMonitor().
 {
     mCursorTime = cursorTime;
     internalUpdateDisplay();
 }
void rcMonitor::updateDisplay (const rcWindow * image) slot
Definition at line 218 of file rc_monitor.cpp.
References cCursorTimeCurrent, deleteCachedImage(), inputIsStored(), mCursorTime, mScaleWidget, updateCachedImage(), and updateStatus().
 {
     if ( image ) {
         // Disable scaling for capture input
         if ( mScaleWidget->isEnabled() && inputIsStored() )
             mScaleWidget->setEnabled( false );
         // Update screen only when cursor is at current time
         if ( mCursorTime == cCursorTimeCurrent ) {
             updateCachedImage( image );
         }
         updateStatus();
     } else {
         deleteCachedImage();
     }
 }
void rcMonitor::updateDisplay (const rcVisualGraphicsCollection * graphics) slot
Definition at line 235 of file rc_monitor.cpp.
References endl(), rmUnused, and updateStatus().
 {
     rmUnused( graphics );
     cerr << "rcMonitor::updateDisplay( const rcVisualGraphicsCollection* graphics ) unimplemented!" << endl;
     updateStatus();
 }
void rcMonitor::updateDisplay (void) slot
Definition at line 243 of file rc_monitor.cpp.
References internalUpdateDisplay().
Referenced by rcMonitor().
 {
     internalUpdateDisplay();
 }
void rcMonitor::updateMonitorSize (const rcRect & size) slot
Definition at line 294 of file rc_monitor.cpp.
References rmUnused.
Referenced by rcMonitor().
 {
     rmUnused( nSize );
 }
void rcMonitor::updateScale (double scale) slot
Definition at line 278 of file rc_monitor.cpp.
References cMaxHeight, cMaxWidth, inputIsStored(), internalUpdateDisplay(), scaleChanged(), and TRUE.
Referenced by rcMonitor().
 {
     if ( scale > 0.0 ) {
         scaleChanged( static_cast<int>(scale*100), TRUE );
         internalUpdateDisplay();
     } else {
         // Disable resizing for capture
         if ( inputIsStored() ) {
             setMaximumSize( size() );
         } else {
             setMaximumSize( QSize( cMaxWidth, cMaxHeight ) );
         }
     }
 }
void rcMonitor::updateState (rcExperimentState state) slot
Definition at line 260 of file rc_monitor.cpp.
References deleteCachedImage(), eExperimentEmpty, inputIsStored(), mScaleWidget, mSpeedCalc, and rcFpsCalculator::reset().
Referenced by rcMonitor().
 {
     // Disable scaling for capture input
     mScaleWidget->setEnabled( !inputIsStored() );
     switch( state ) {
         case eExperimentEmpty:
             // Starting a new experiment
             // Remove cached image
             deleteCachedImage();
             break;
         default:
             break;
     }
     mSpeedCalc.reset();
 }
void rcMonitor::updateStatus ()
Definition at line 394 of file rc_monitor.cpp.
References rcImageCanvasGL::currentScale(), eExperimentPlayback, rcFpsCalculator::fps(), rcModelDomain::getExperimentState(), rcModelDomain::getModelDomain(), inputIsCamera(), mCanvas, mScaleWidget, mSpeedCalc, mStatusWidget, and rcImageCanvasGL::statusString().
Referenced by internalUpdateDisplay(), scaleChanged(), updateDisplay(), and rcImageCanvasGL::updateStatus().
 {
     QString text;
     // Update status bar
     mCanvas->statusString( text );
     bool cameraInput = inputIsCamera();
     rcExperimentState state = rcModelDomain::getModelDomain()->getExperimentState();
     // Display FPS for camera or movie playback
     if ( cameraInput || state == eExperimentPlayback ) {
         QString moremsg;
         moremsg.sprintf(", display %3.1f fps",
                         mSpeedCalc.fps() );
         text += moremsg;
     }
     mStatusWidget->setText( text );
     // Update scale widget
     int scale = mCanvas->currentScale();
     mScaleWidget->setValue( scale );
 }
void rcMonitor::updateTime (const rcTimestamp & time) slot
Definition at line 205 of file rc_monitor.cpp.
References rmUnused.
Referenced by rcMonitor().
 {
     rmUnused( cursorTime );
 }
Member Data Documentation
QColor rcMonitor::mBackgroundColor private
Definition at line 143 of file rc_monitor.h.
Referenced by rcMonitor().
rcImageCanvasGL* rcMonitor::mCanvas private
Definition at line 134 of file rc_monitor.h.
Referenced by deleteCachedImage(), getPosition(), rcMonitor(), saturationChanged(), scaleChanged(), updateAnalysisRect(), updateAnalysisRectRotation(), updateCachedImage(), and updateStatus().
bool rcMonitor::mCellPath private
Definition at line 146 of file rc_monitor.h.
Referenced by gatherTrackData(), rcMonitor(), and settingChanged().
bool rcMonitor::mCellPos private
Definition at line 145 of file rc_monitor.h.
Referenced by gatherTrackData(), rcMonitor(), and settingChanged().
bool rcMonitor::mCellText private
Definition at line 144 of file rc_monitor.h.
Referenced by gatherTrackData(), rcMonitor(), and settingChanged().
rcTimestamp rcMonitor::mCursorTime private
Definition at line 132 of file rc_monitor.h.
Referenced by displayTrackFocus(), gatherDevelopmentTrackData(), gatherTrackData(), rcMonitor(), updateCursorTime(), and updateDisplay().
bool rcMonitor::mDevelopmentData private
Definition at line 147 of file rc_monitor.h.
Referenced by rcMonitor(), settingChanged(), and showDevelopmentData().
QCheckBox* rcMonitor::mSaturationWidget private
Definition at line 139 of file rc_monitor.h.
Referenced by deleteCachedImage(), rcMonitor(), settingChanged(), updateCachedImage(), and ~rcMonitor().
QLabel* rcMonitor::mSaturationWidgetLabel private
Definition at line 140 of file rc_monitor.h.
Referenced by rcMonitor(), settingChanged(), and ~rcMonitor().
QSpinBox* rcMonitor::mScaleWidget private
Definition at line 137 of file rc_monitor.h.
Referenced by rcMonitor(), scaleChanged(), setMaxScale(), settingChanged(), updateDisplay(), updateState(), updateStatus(), and ~rcMonitor().
rcFpsCalculator rcMonitor::mSpeedCalc private
Definition at line 142 of file rc_monitor.h.
Referenced by updateCachedImage(), updateState(), and updateStatus().
Q3BoxLayout* rcMonitor::mStatusLayout private
Definition at line 136 of file rc_monitor.h.
Referenced by rcMonitor().
QLabel* rcMonitor::mStatusWidget private
Definition at line 138 of file rc_monitor.h.
Referenced by rcMonitor(), updateStatus(), and ~rcMonitor().
Q3BoxLayout* rcMonitor::mTopLayout private
Definition at line 135 of file rc_monitor.h.
Referenced by rcMonitor().
The documentation for this class was generated from the following files:
include/visUI/rc_monitor.h
src/visible/qt/rc_monitor.cpp