Visible: rcPersistenceHistogramTrackRenderInfo Class Reference
rcPersistenceHistogramTrackRenderInfo Class Reference
#include <include/visUI/rc_trackrender.h>
Public Member Functions
rcPersistenceHistogramTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, const rcFPair &min, const rcFPair &max, const QRect &dataRect)
Public Member Functions inherited from rc2DTrackRenderInfo
rc2DTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, const rcFPair &min, const rcFPair &max, const QRect &dataRect)
const rcFPair & minValue () const
const rcFPair & maxValue () const
const std::string & xAxisName () const
const std::string & yAxisName () const
const std::string & xAxisNameNeg () const
const std::string & yAxisNameNeg () const
const std::string & xFormatString () const
const std::string & yFormatString () const
const rcIPair & tickCount () const
void minValue (const rcFPair &v)
void maxValue (const rcFPair &v)
void xAxisName (const std::string &n)
void yAxisName (const std::string &n)
void xAxisNameNeg (const std::string &n)
void yAxisNameNeg (const std::string &n)
void xFormatString (const std::string &s)
void yFormatString (const std::string &s)
void tickCount (const rcIPair &c)
Public Member Functions inherited from rcTrackRenderInfo
rcTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack *track, rcTimestamp startTime, rcTimestamp endTime, const QRect &dataRect, bool logDisplay=false)
Private Member Functions
void init (const rcFPair &max)
Additional Inherited Members
Public Attributes inherited from rcTrackRenderInfo
rcTrack * _track
rcTimestamp _startTime
rcTimestamp _endTime
double _minValue
double _maxValue
QRect _dataRect
QPen _tickMarkPen
QPen _dataPen
bool _isEnabled
bool _isHilited
QFont _tickMarkFont
bool _logDisplay
Protected Attributes inherited from rc2DTrackRenderInfo
rcFPair mMinValue
rcFPair mMaxValue
std::string mXAxisName
std::string mYAxisName
std::string mXAxisNameNeg
std::string mYAxisNameNeg
std::string mXFormatString
std::string mYFormatString
rcIPair mTickCount
Detailed Description
Definition at line 172 of file rc_trackrender.h.
Constructor & Destructor Documentation
rcPersistenceHistogramTrackRenderInfo::rcPersistenceHistogramTrackRenderInfo (int trackGroupNo, int trackNo, rcTrack * track, const rcFPair & min, const rcFPair & max, const QRect & dataRect)
Definition at line 192 of file rc_trackrender.cpp.
References init().
                                                                                                       :
         rc2DTrackRenderInfo( trackGroupNo, trackNo, track, min, max, dataRect )
 {
     init( max );
}
Member Function Documentation
void rcPersistenceHistogramTrackRenderInfo::init (const rcFPair & max) private
Definition at line 205 of file rc_trackrender.cpp.
References rmUnused, rc2DTrackRenderInfo::tickCount(), rc2DTrackRenderInfo::xAxisName(), rc2DTrackRenderInfo::xAxisNameNeg(), rc2DTrackRenderInfo::xFormatString(), rc2DTrackRenderInfo::yAxisName(), rc2DTrackRenderInfo::yAxisNameNeg(), and rc2DTrackRenderInfo::yFormatString().
Referenced by rcPersistenceHistogramTrackRenderInfo().
 {
     rmUnused( max );
     xAxisName( "Persistence" );
     yAxisName( "Percentage");
     xAxisNameNeg( "Persistence" );
     yAxisNameNeg( "Percentage");
     xFormatString( "%.1f" );
     yFormatString( "%.1f%%" );
     tickCount( rcIPair( 20, 20 ) );
 }
The documentation for this class was generated from the following files:
include/visUI/rc_trackrender.h
src/visible/qt/rc_trackrender.cpp