Visible: rcLevelSets Class Reference
rcLevelSets Class Reference
#include <include/analysis/rc_level.h>
Public Member Functions
uint32 threshold () const
double score () const
double darkArea () const
void update (uint32 threshold, double score, uint32 darkArea)
Private Attributes
uint32 mThreshold
double mScore
double darkArea_
Detailed Description
Definition at line 14 of file rc_level.h.
Member Function Documentation
double rcLevelSets::darkArea () const inline
Definition at line 22 of file rc_level.h.
References darkArea_.
Referenced by update().
 {return darkArea_;}
double rcLevelSets::score () const inline
Definition at line 21 of file rc_level.h.
References mScore.
Referenced by update().
 {return mScore;}
uint32 rcLevelSets::threshold () const inline
Definition at line 20 of file rc_level.h.
References mThreshold.
Referenced by rcMutualInfoGrouping::rcMutualInfoGrouping(), and update().
 {return mThreshold;}
void rcLevelSets::update (uint32 threshold, double score, uint32 darkArea) inline
Definition at line 25 of file rc_level.h.
References darkArea(), darkArea_, mScore, mThreshold, score(), and threshold().
Referenced by rcWithinGroupInv::compute(), and rcMutualInfoGrouping::rcMutualInfoGrouping().
     {mThreshold = threshold, mScore = score, darkArea_ = darkArea;}
Member Data Documentation
double rcLevelSets::darkArea_ private
Definition at line 30 of file rc_level.h.
Referenced by darkArea(), and update().
double rcLevelSets::mScore private
Definition at line 29 of file rc_level.h.
Referenced by score(), and update().
uint32 rcLevelSets::mThreshold private
Definition at line 28 of file rc_level.h.
Referenced by threshold(), and update().
The documentation for this class was generated from the following file:
include/analysis/rc_level.h