Visible: otext Class Reference
otext Class Reference
#include <include/stlplus/textio.hpp>
Public Types
enum newline_t {
binary_mode, unix_mode, msdos_mode, macos_mode,
native_mode = unix_mode
}
enum open_t { overwrite, append }
typedef void(* manipulator_function)(otext &)
Public Member Functions
otext (void)
otext (obuff *)
virtual ~otext (void)
bool initialised (void) const
void open (obuff *)
void close (void)
otext (const otext &)
otext & operator= (const otext &)
bool error (void) const
int error_number (void) const
std::string error_string (void) const
void set_error (int error)
void clear_error (void)
void set_newline_mode (newline_t newline=native_mode)
void set_unix_mode (void)
void set_msdos_mode (void)
void set_macos_mode (void)
void set_native_mode (void)
void set_binary_mode (void)
newline_t newline_mode (void) const
bool is_unix_mode (void) const
bool is_msdos_mode (void) const
bool is_macos_mode (void) const
bool is_native_mode (void) const
bool is_binary_mode (void) const
void set_integer_width (unsigned width=0)
unsigned integer_width (void) const
void set_integer_radix (unsigned radix=10)
unsigned integer_radix (void) const
void set_integer_display (radix_display_t display=radix_c_style_or_hash)
radix_display_t integer_display (void) const
void set_real_width (unsigned width=0)
unsigned real_width (void) const
void set_real_precision (unsigned width=6)
unsigned real_precision (void) const
void set_real_display (real_display_t display=display_mixed)
real_display_t real_display (void) const
bool put (int ch)
bool put (const char *)
bool put (const std::string &)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void flush (void)
operator bool (void) const
bool operator! (void) const
otext & operator<< (char)
otext & operator<< (signed char)
otext & operator<< (unsigned char)
otext & operator<< (const char *)
otext & operator<< (const std::string &)
otext & operator<< (const std::vector< std::string > &)
otext & operator<< (bool)
otext & operator<< (short)
otext & operator<< (unsigned short)
otext & operator<< (int)
otext & operator<< (unsigned int)
otext & operator<< (long)
otext & operator<< (unsigned long)
otext & operator<< (float)
otext & operator<< (double)
otext & operator<< (const void *)
otext & operator<< (manipulator_function)
otext & operator<< (itext &)
Protected Attributes
obuff * m_buffer
Friends
class obuff
class itext
std::string to_string (newline_t)
std::string to_string (open_t)
Detailed Description
Definition at line 39 of file textio.hpp.
Member Typedef Documentation
typedef void(* otext::manipulator_function)(otext &)
Definition at line 80 of file textio.hpp.
Member Enumeration Documentation
enum otext::newline_t
Enumerator
binary_mode
unix_mode
msdos_mode
macos_mode
native_mode
Definition at line 55 of file textio.hpp.
   {
     binary_mode, // no end of line conversion
     unix_mode,   // Unix conversions (LF)
     msdos_mode,  // MS-DOS conversion (CR-LF)
     macos_mode,  // MacOS conversion (CR)
     // the mode of the platform you compiled this on
 #ifdef MSWINDOWS
     native_mode = msdos_mode
 #else
     native_mode = unix_mode
 #endif
   };
enum otext::open_t
Enumerator
overwrite
append
Definition at line 72 of file textio.hpp.
   {
     overwrite,  // destroy previous contents (default)
     append      // append to previous contents
   };
Constructor & Destructor Documentation
otext::otext (void)
Definition at line 64 of file textio.cpp.
                   : m_buffer(0)
 {
 }
otext::otext (obuff * b)
Definition at line 68 of file textio.cpp.
References open().
                       : m_buffer(0)
 {
   open(b);
 }
otext::~otext (void) virtual
Definition at line 73 of file textio.cpp.
References close().
 {
   close();
 }
otext::otext (const otext & source)
Definition at line 100 of file textio.cpp.
References m_buffer, and open().
                                  : m_buffer(0)
 {
   if (m_buffer != source.m_buffer)
     open(source.m_buffer);
 }
Member Function Documentation
unsigned long otext::bytes (void) const
Definition at line 375 of file textio.cpp.
References obuff::bytes(), and m_buffer.
 {
   return m_buffer ? m_buffer->bytes() : 0;
 }
void otext::clear_error (void)
Definition at line 134 of file textio.cpp.
References obuff::clear_error(), and m_buffer.
 {
   if (m_buffer) m_buffer->clear_error();
 }
void otext::close (void)
Definition at line 90 of file textio.cpp.
References obuff::m_aliases, and m_buffer.
Referenced by close(), open(), and ~otext().
 {
   if (m_buffer)
   {
     if (--m_buffer->m_aliases == 0)
       delete m_buffer;
     m_buffer = 0;
   }
 }
unsigned otext::column (void) const
Definition at line 385 of file textio.cpp.
References obuff::column(), and m_buffer.
 {
   return m_buffer ? m_buffer->column() : 0;
 }
bool otext::error (void) const
Definition at line 113 of file textio.cpp.
References error_number().
Referenced by error_string(), operator!(), dump_context_body::put(), library_manager::save_mappings(), and lm_unit::write().
 {
   return error_number() != 0;
 }
int otext::error_number (void) const
Definition at line 118 of file textio.cpp.
References obuff::error_number(), m_buffer, and textio_uninitialised.
Referenced by error(), and lm_unit::write().
 {
   return m_buffer ? m_buffer->error_number() : textio_uninitialised;
 }
std::string otext::error_string (void) const
Definition at line 123 of file textio.cpp.
References error(), obuff::error_string(), m_buffer, textio_error_string(), and textio_uninitialised.
Referenced by dump_context_body::put(), and lm_unit::write().
 {
   if (!error()) return std::string();
   return m_buffer ? m_buffer->error_string() : textio_error_string(textio_uninitialised);
 }
void otext::flush (void)
Definition at line 390 of file textio.cpp.
References obuff::flush(), and m_buffer.
Referenced by flush(), put(), and error_handler::~error_handler().
 {
   if (m_buffer) m_buffer->flush();
 }
bool otext::initialised (void) const
Definition at line 78 of file textio.cpp.
References m_buffer.
 {
   return m_buffer != 0;
 }
radix_display_t otext::integer_display (void) const
Definition at line 224 of file textio.cpp.
References obuff::integer_display(), m_buffer, and radix_c_style_or_hash.
Referenced by operator<<(), and operator<<().
 {
   return m_buffer ? m_buffer->integer_display() : radix_c_style_or_hash;
 }
unsigned otext::integer_radix (void) const
Definition at line 214 of file textio.cpp.
References obuff::integer_radix(), and m_buffer.
Referenced by operator<<(), and operator<<().
 {
   return m_buffer ? m_buffer->integer_radix() : 0;
 }
unsigned otext::integer_width (void) const
Definition at line 204 of file textio.cpp.
References obuff::integer_width(), and m_buffer.
Referenced by operator<<(), and operator<<().
 {
   return m_buffer ? m_buffer->integer_width() : 0;
 }
bool otext::is_binary_mode (void) const
Definition at line 194 of file textio.cpp.
References binary_mode, and newline_mode().
 {
   return newline_mode() == otext::binary_mode;
 }
bool otext::is_macos_mode (void) const
Definition at line 184 of file textio.cpp.
References macos_mode, and newline_mode().
 {
   return newline_mode() == otext::macos_mode;
 }
bool otext::is_msdos_mode (void) const
Definition at line 179 of file textio.cpp.
References msdos_mode, and newline_mode().
 {
   return newline_mode() == otext::msdos_mode;
 }
bool otext::is_native_mode (void) const
Definition at line 189 of file textio.cpp.
References native_mode, and newline_mode().
 {
   return newline_mode() == otext::native_mode;
 }
bool otext::is_unix_mode (void) const
Definition at line 174 of file textio.cpp.
References newline_mode(), and unix_mode.
 {
   return newline_mode() == otext::unix_mode;
 }
unsigned otext::line (void) const
Definition at line 380 of file textio.cpp.
References obuff::line(), and m_buffer.
 {
   return m_buffer ? m_buffer->line() : 0;
 }
otext::newline_t otext::newline_mode (void) const
Definition at line 169 of file textio.cpp.
References m_buffer, native_mode, and obuff::newline_mode().
Referenced by is_binary_mode(), is_macos_mode(), is_msdos_mode(), is_native_mode(), and is_unix_mode().
 {
   return m_buffer ? m_buffer->newline_mode() : otext::native_mode;
 }
void otext::open (obuff * b)
Definition at line 83 of file textio.cpp.
References close(), obuff::m_aliases, and m_buffer.
Referenced by oiotext::open(), omtext::open(), oftext::open(), operator=(), and otext().
 {
   close();
   m_buffer = b;
   if (m_buffer) m_buffer->m_aliases++;
 }
otext::operator bool (void) const
Definition at line 395 of file textio.cpp.
References TCP_client_data::error().
 {
   return !error();
 }
bool otext::operator! (void) const
Definition at line 400 of file textio.cpp.
References error().
 {
   return error();
 }
otext & otext::operator<< (char ch)
Definition at line 405 of file textio.cpp.
References put().
Referenced by operator<<().
 {
   put((unsigned char)ch);
   return *this;
 }
otext & otext::operator<< (signed char ch)
Definition at line 411 of file textio.cpp.
References put().
 {
   put((unsigned char)ch);
   return *this;
 }
otext & otext::operator<< (unsigned char ch)
Definition at line 417 of file textio.cpp.
References put().
 {
   put(ch);
   return *this;
 }
otext & otext::operator<< (const char * str)
Definition at line 423 of file textio.cpp.
References put().
 {
   put(str);
   return *this;
 }
otext & otext::operator<< (const std::string & str)
Definition at line 429 of file textio.cpp.
References put().
 {
   put(str);
   return *this;
 }
otext & otext::operator<< (const std::vector< std::string > & str)
Definition at line 435 of file textio.cpp.
References newline, and operator<<().
 {
   for (unsigned i = 0; i < str.size(); i++)
   {
     operator << (str[i]);
     operator << (newline);
   }
   return *this;
 }
otext & otext::operator<< (bool b)
Definition at line 445 of file textio.cpp.
References operator<<().
 {
   return operator << (b ? '1' : '0');
 }
otext & otext::operator<< (short s)
Definition at line 450 of file textio.cpp.
References integer_display(), integer_radix(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(s, integer_radix(), integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (unsigned short s)
Definition at line 463 of file textio.cpp.
References integer_display(), integer_radix(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(s, integer_radix(), integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (int i)
Definition at line 476 of file textio.cpp.
References integer_display(), integer_radix(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(i, integer_radix(), integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (unsigned int i)
Definition at line 489 of file textio.cpp.
References integer_display(), integer_radix(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(i, integer_radix(), integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (long l)
Definition at line 502 of file textio.cpp.
References integer_display(), integer_radix(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(l, integer_radix(), integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (unsigned long l)
Definition at line 515 of file textio.cpp.
References integer_display(), integer_radix(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(l, integer_radix(), integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (float f)
Definition at line 528 of file textio.cpp.
References operator<<(), real_display(), real_precision(), real_width(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(f, real_display(), real_width(), real_precision()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (double d)
Definition at line 541 of file textio.cpp.
References operator<<(), real_display(), real_precision(), real_width(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(d, real_display(), real_width(), real_precision()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (const void * p)
Definition at line 554 of file textio.cpp.
References integer_display(), integer_width(), operator<<(), set_error(), textio_format_error, and to_string.
 {
   try
   {
     operator << (to_string(p, 16, integer_display(), integer_width()));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
otext & otext::operator<< (otext::manipulator_function fn)
Definition at line 567 of file textio.cpp.
 {
   if (fn) fn(*this);
   return *this;
 }
otext & otext::operator<< (itext & in)
Definition at line 573 of file textio.cpp.
References itext::get(), and put().
 {
   while (in)
     put((unsigned char)in.get());
   return *this;
 }
otext & otext::operator= (const otext & source)
Definition at line 106 of file textio.cpp.
References m_buffer, and open().
 {
   if (m_buffer != source.m_buffer)
     open(source.m_buffer);
   return *this;
 }
bool otext::put (int ch)
Definition at line 260 of file textio.cpp.
References binary_mode, flush(), obuff::increment(), obuff::line_buffer(), m_buffer, macos_mode, msdos_mode, newline, obuff::newline_mode(), obuff::put(), set_error(), textio_put_failed, and unix_mode.
Referenced by endl(), operator<<(), itext::operator>>(), dump_context_body::put(), and put().
 {
   if (!m_buffer) return false;
   bool success = true;
   // its illegal to put a value outside the range of unsigned char
   if (ch < 0 || ch > 255)
   {
     set_error(textio_put_failed);
     success = false;
   }
   else if (ch != newline)
   {
     // no special handling for non-newline characters
     if (m_buffer->put((unsigned char)ch))
       m_buffer->increment();
     else
     {
       set_error(textio_put_failed);
       success = false;
     }
   }
   else
   {
     switch(m_buffer->newline_mode())
     {
     case otext::unix_mode:
       // convert the abstract newline character to the literal linefeed character
       if (m_buffer->put('\xa'))
         m_buffer->increment(true);
       else
       {
         set_error(textio_put_failed);
         success = false;
       }
       // test for line buffer condition only on end-of-line
       if (m_buffer->line_buffer())
         flush();
       break;
     case otext::msdos_mode:
       // convert the abstract newline character to the literal carriage-return/linefeed pair
       if (m_buffer->put('\xd'))
         m_buffer->increment();
       else
       {
         set_error(textio_put_failed);
         success = false;
       }
       if (m_buffer->put('\xa'))
         m_buffer->increment(true);
       else
       {
         set_error(textio_put_failed);
         success = false;
       }
       // test for line buffer condition only on end-of-line
       if (m_buffer->line_buffer())
         flush();
       break;
     case otext::macos_mode:
       // convert the abstract newline character to the literal carriage-return character
       if (m_buffer->put('\xd'))
         m_buffer->increment(true);
       else
       {
         set_error(textio_put_failed);
         success = false;
       }
       // test for line buffer condition only on end-of-line
       if (m_buffer->line_buffer())
         flush();
       break;
     case otext::binary_mode:
       // raw data mode so no special handling of newlines
       if (m_buffer->put((unsigned char)ch))
         m_buffer->increment(true);
       else
       {
         set_error(textio_put_failed);
         success = false;
       }
       break;
     }
   }
   return success;
 }
bool otext::put (const char * str)
Definition at line 346 of file textio.cpp.
References put().
 {
   // treat a null string as acceptable - the method does nothing but returns a success flag
   if (!str) return true;
   bool result = true;
   // C arrays are null terminated
   for (unsigned i = 0; str[i]; ++i)
   {
     // rely on the put method to set the error status
     if (!put((unsigned char)str[i]))
       result = false;
   }
   return result;
 }
bool otext::put (const std::string & str)
Definition at line 361 of file textio.cpp.
References put().
 {
   bool result = true;
   // STL strings are delimited by their size method and may contain nulls
   // it would therefore be a bug to call str.c_str() and use the above put(char*)
   for (unsigned i = 0; i < str.size(); ++i)
   {
     // rely on the put method to set the error status
     if (!put((unsigned char)str[i]))
       result = false;
   }
   return result;
 }
real_display_t otext::real_display (void) const
Definition at line 254 of file textio.cpp.
References display_mixed, m_buffer, and obuff::real_display().
Referenced by operator<<().
 {
   return m_buffer ? m_buffer->real_display() : display_mixed;
 }
unsigned otext::real_precision (void) const
Definition at line 244 of file textio.cpp.
References m_buffer, and obuff::real_precision().
Referenced by operator<<().
 {
   return m_buffer ? m_buffer->real_precision() : 0;
 }
unsigned otext::real_width (void) const
Definition at line 234 of file textio.cpp.
References m_buffer, and obuff::real_width().
Referenced by operator<<().
 {
   return m_buffer ? m_buffer->real_width() : 0;
 }
void otext::set_binary_mode (void)
Definition at line 164 of file textio.cpp.
References binary_mode, and set_newline_mode().
Referenced by dump_context_body::dump_context_body().
 {
   set_newline_mode(otext::binary_mode);
 }
void otext::set_error (int error)
Definition at line 129 of file textio.cpp.
References m_buffer, and obuff::set_error().
Referenced by operator<<(), operator<<(), and put().
 {
   if (m_buffer) m_buffer->set_error(error);
 }
void otext::set_integer_display (radix_display_t display = radix_c_style_or_hash)
Definition at line 219 of file textio.cpp.
References m_buffer, and obuff::set_integer_display().
 {
   if (m_buffer) m_buffer->set_integer_display(display);
 }
void otext::set_integer_radix (unsigned radix = 10)
Definition at line 209 of file textio.cpp.
References m_buffer, and obuff::set_integer_radix().
Referenced by dec(), hex(), and oct().
 {
   if (m_buffer) m_buffer->set_integer_radix(radix);
 }
void otext::set_integer_width (unsigned width = 0)
Definition at line 199 of file textio.cpp.
References m_buffer, and obuff::set_integer_width().
 {
   if (m_buffer) m_buffer->set_integer_width(width);
 }
void otext::set_macos_mode (void)
Definition at line 154 of file textio.cpp.
References macos_mode, and set_newline_mode().
 {
   set_newline_mode(otext::macos_mode);
 }
void otext::set_msdos_mode (void)
Definition at line 149 of file textio.cpp.
References msdos_mode, and set_newline_mode().
 {
   set_newline_mode(otext::msdos_mode);
 }
void otext::set_native_mode (void)
Definition at line 159 of file textio.cpp.
References native_mode, and set_newline_mode().
 {
   set_newline_mode(otext::native_mode);
 }
void otext::set_newline_mode (otext::newline_t newline = native_mode)
Definition at line 139 of file textio.cpp.
References m_buffer, and obuff::set_newline_mode().
Referenced by set_binary_mode(), set_macos_mode(), set_msdos_mode(), set_native_mode(), and set_unix_mode().
 {
   if (m_buffer) m_buffer->set_newline_mode(newline);
 }
void otext::set_real_display (real_display_t display = display_mixed)
Definition at line 249 of file textio.cpp.
References m_buffer, and obuff::set_real_display().
 {
   if (m_buffer) m_buffer->set_real_display(display);
 }
void otext::set_real_precision (unsigned width = 6)
Definition at line 239 of file textio.cpp.
References m_buffer, and obuff::set_real_precision().
 {
   if (m_buffer) m_buffer->set_real_precision(width);
 }
void otext::set_real_width (unsigned width = 0)
Definition at line 229 of file textio.cpp.
References m_buffer, and obuff::set_real_width().
 {
   if (m_buffer) m_buffer->set_real_width(width);
 }
void otext::set_unix_mode (void)
Definition at line 144 of file textio.cpp.
References set_newline_mode(), and unix_mode.
 {
   set_newline_mode(otext::unix_mode);
 }
Friends And Related Function Documentation
friend class itext friend
Definition at line 43 of file textio.hpp.
friend class obuff friend
Definition at line 42 of file textio.hpp.
std::string to_string (newline_t) friend
Definition at line 40 of file textio.cpp.
Referenced by operator<<().
 {
   switch(mode)
   {
   case otext::binary_mode: return std::string("binary");
   case otext::unix_mode: return std::string("unix");
   case otext::msdos_mode: return std::string("msdos");
   case otext::macos_mode: return std::string("macos");
   }
   return std::string("*unknown mode*");
 }
std::string to_string (open_t) friend
Definition at line 52 of file textio.cpp.
 {
   switch(mode)
   {
   case otext::overwrite: return std::string("overwrite");
   case otext::append: return std::string("append");
   }
   return std::string("*unknown mode*");
 }
Member Data Documentation
obuff* otext::m_buffer protected
Definition at line 44 of file textio.hpp.
Referenced by omtext::add(), bytes(), clear_error(), close(), column(), omtext::device_count(), omtext::device_get(), error_number(), error_string(), flush(), oiotext::get_stream(), ostext::get_string(), osvtext::get_vector(), initialised(), integer_display(), integer_radix(), integer_width(), line(), newline_mode(), open(), operator=(), otext(), put(), real_display(), real_precision(), real_width(), omtext::remove(), set_error(), set_integer_display(), set_integer_radix(), set_integer_width(), set_newline_mode(), set_real_display(), set_real_precision(), and set_real_width().
The documentation for this class was generated from the following files:
include/stlplus/textio.hpp
include/stlplus/textio.cpp