Visible: rcMutex Class Reference
rcMutex Class Reference
#include <include/util/rc_thread.h>
Public Member Functions
rcMutex (bool errorCheck=true, bool invertProtect=true, rcThreadPriority tp=eMaxPriority)
virtual ~rcMutex ()
void lock ()
bool tryLock ()
void unlock ()
Private Member Functions
rcMutex (const rcMutex &)
rcMutex & operator= (const rcMutex &)
Private Attributes
void * _mutex
Friends
class rcConditionVariable
class rcSignalPending
Detailed Description
Definition at line 113 of file rc_thread.h.
Constructor & Destructor Documentation
rcMutex::rcMutex (bool errorCheck = true, bool invertProtect = true, rcThreadPriority tp = eMaxPriority)
Definition at line 379 of file rc_thread_mac.cpp.
References _mutex, rcUNUSED, and rmDim.
 {
   pthread_mutexattr_t mutexAttr;
   int error;
   if ((error = pthread_mutexattr_init(&mutexAttr))) {
     char errMsg[100];
     snprintf(errMsg, rmDim( errMsg ), "error creating attr %d", error);
     throw general_exception( errMsg );
   }
   int type = errorCheck ? PTHREAD_MUTEX_ERRORCHECK : PTHREAD_MUTEX_NORMAL;
   if ((error = pthread_mutexattr_settype(&mutexAttr, type))) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "error setting attr type %d", error);
     throw general_exception(errMsg);
   }
 #ifdef REAL_TIME_SUPPORT
   int protocol = PTHREAD_PRIO_NONE;
   if (invertProtect) {
     protocol = PTHREAD_PRIO_PROTECT;
     if ((error = pthread_mutexattr_setprotocol(&mutexAttr, protocol))) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg), "error setting protocol %d", error);
       throw general_exception(errMsg);
     }
     int priority = threadPriorityInfo::defaultPriority() + tp;
     if ((priority < threadPriorityInfo::minPriority()) ||
     (priority > threadPriorityInfo::maxPriority())) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg), "invalid new priority %d", priority);
       throw general_exception(errMsg);
     }
     if ((error =pthread_mutexattr_setprioceiling(&mutexAttr, priority))) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg), "error setting priority ceiling %d", error);
       throw general_exception(errMsg);
     }
   }
   else {
     if ((error = pthread_mutexattr_setprotocol(&mutexAttr, protocol))) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg), "error setting protocol %d", error);
       throw general_exception(errMsg);
     }
   }
 #else
   rcUNUSED(invertProtect);
   rcUNUSED(tp);
 #endif
   pthread_mutex_t* mutex = new pthread_mutex_t;
   if ((error = pthread_mutex_init(mutex, &mutexAttr))) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "error initializing mutex %d", error);
     delete mutex;
     throw general_exception(errMsg);
   }
   _mutex = (void *)mutex;
 }
rcMutex::~rcMutex () virtual
Definition at line 450 of file rc_thread_mac.cpp.
References _mutex.
 {
   delete (pthread_mutex_t*)_mutex;
   _mutex = 0;
 }
rcMutex::rcMutex (const rcMutex &) private
Member Function Documentation
void rcMutex::lock ()
Definition at line 456 of file rc_thread_mac.cpp.
References _mutex, and rmDim.
Referenced by rcSegmentIteratorImpl::lock(), and rcSegmentIteratorImpl::reset().
 {
   if (!_mutex) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "Invalid mutex");
     throw general_exception(errMsg);
   }
   int error;
   if ((error = pthread_mutex_lock((pthread_mutex_t *)_mutex))) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "mutex lock failed %d", error);
     throw general_exception(errMsg);
   }
 }
rcMutex& rcMutex::operator= (const rcMutex &) private
bool rcMutex::tryLock ()
Definition at line 473 of file rc_thread_mac.cpp.
References _mutex, FALSE, rmDim, and TRUE.
 {
   if (!_mutex) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "Invalid mutex");
     throw general_exception(errMsg);
   }
   int error;
   if ((error = pthread_mutex_trylock((pthread_mutex_t *)_mutex))) {
     if (error != EBUSY) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg), "mutex trylock failed %d", error);
       throw general_exception(errMsg);
     }
     return FALSE;
   }
   return TRUE;
 }
void rcMutex::unlock ()
Definition at line 495 of file rc_thread_mac.cpp.
References _mutex, and rmDim.
Referenced by rcSegmentIteratorImpl::reset(), and rcSegmentIteratorImpl::unlock().
 {
   if (!_mutex) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "Invalid mutex");
     throw general_exception(errMsg);
   }
   int error;
   if ((error = pthread_mutex_unlock((pthread_mutex_t *)_mutex))) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "mutex unlock failed %d", error);
     throw general_exception(errMsg);
   }
 }
Friends And Related Function Documentation
friend class rcConditionVariable friend
Definition at line 144 of file rc_thread.h.
friend class rcSignalPending friend
Definition at line 145 of file rc_thread.h.
Member Data Documentation
void* rcMutex::_mutex private
Definition at line 152 of file rc_thread.h.
Referenced by lock(), rcMutex(), tryLock(), unlock(), rcSignalPending::wait(), rcConditionVariable::waitFct(), and ~rcMutex().
The documentation for this class was generated from the following files:
include/util/rc_thread.h
src/util/code/rc_thread_mac.cpp