Visible: rcSpatialPyramid< 2 > Class Template Reference
rcSpatialPyramid< 2 > Class Template Reference
#include <include/analysis/rc_kinepyr.h>
Public Member Functions
rcSpatialPyramid ()
rcSpatialPyramid (rcWindow &image, int32 sample, int32 baseSmooth=3, float edgeDetect=1.0f, float hyst=0.0f, bool zeroCross=false, bool highAccDir=false)
rcIRect imageRect (int32 level) const
const rcWindow & base (int32 level) const
const rcWindow & past (int32 level) const
const rcWindow & gradient (int32 level) const
const rcWindow & edge (int32 level) const
const rcWindow & direction (int32 level) const
const vector< uint32 > & directionHistogram (int32 level) const
const float hysteresis () const
const int32 granularity () const
rcIPair kernelBorder () const
bool isValid () const
rcIRect region () const
uint8 edgeLabel ()
int32 gradientCount (int32 level) const
int32 optimizedGradientCount (int32 level) const
Public Member Functions inherited from rc2Xform
rc2Xform ()
rc2Xform (const rcMatrix_2d &c, const rc2Dvector &t)
rc2Xform (const rcMatrix_2d &c, const rc2Fvector &t)
const rcMatrix_2d & matrix () const
const rc2Dvector & trans () const
const rc2Fvector transf () const
void matrix (const rcMatrix_2d &c)
void trans (const rc2Dvector &t)
void trans (const rc2Fvector &t)
rc2Xform inverse () const
rc2Xform operator* (const rc2Xform &xform) const
rc2Xform compose (const rc2Xform &xform) const
double xRot () const
double yRot () const
double xScale () const
double yScale () const
double scale () const
double aspect () const
double shear () const
rcRadian rotation () const
double mapAngle (const double &ang) const
double invMapAngle (const double &ang) const
rc2Dvector mapPoint (const rc2Dvector &pt) const
rc2Fvector mapPoint (const rc2Fvector &pt) const
rc2Dvector operator* (const rc2Dvector &pt) const
rc2Fvector operator* (const rc2Fvector &pt) const
rc2Dvector invMapPoint (const rc2Dvector &pt) const
rc2Fvector invMapPoint (const rc2Fvector &pt) const
rc2Dvector mapVector (const rc2Dvector &vect) const
rc2Dvector invMapVector (const rc2Dvector &vect) const
double mapArea (double area) const
double invMapArea (double area) const
bool operator== (const rc2Xform &xform) const
bool operator!= (const rc2Xform &xform) const
bool operator< (const rc2Xform &) const
bool isIdentity () const
bool isSingular () const
Private Member Functions
void intensityProcess (rcWindow &image, int32 level)
void gradientProcess ()
Private Attributes
int32 mSample
int32 mGranularity
float mEdgeDetect
float mHysteresis
vector< vector< rcWindow > > mLevels
vector< vector< uint32 > > mLevelDirectionHists
vector< int32 > mEdgeCount
vector< int32 > mLeft
rcWindow mUnbound
bool mZc
bool m16bitDir
Additional Inherited Members
Static Public Attributes inherited from rc2Xform
static const rc2Xform I
Detailed Description
template<>
class rcSpatialPyramid< 2 >
Definition at line 69 of file rc_kinepyr.h.
Constructor & Destructor Documentation
rcSpatialPyramid< 2 >::rcSpatialPyramid ()
Definition at line 80 of file rc_kinepyr.cpp.
 {
 }
rcSpatialPyramid< 2 >::rcSpatialPyramid (rcWindow & image, int32 sample, int32 baseSmooth = 3, float edgeDetect = 1.0f, float hyst = 0.0f, bool zeroCross = false, bool highAccDir = false)
Definition at line 86 of file rc_kinepyr.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rmAssert, rmExceptionMacro, rmMin, sample(), and rcWindow::width().
                                                             :
   mEdgeCount (0), mLeft (0), mZc (zc), m16bitDir (highAccDir)
 {
   rmAssert (image.isBound());
     mSample = sample;
     mGranularity = baseSmooth;
     mEdgeDetect = edgeDetect;
     mHysteresis = hyst;
     if (granularity() > (rmMin (image.width(), image.height())) / 2)
       rmExceptionMacro(<< "Invalid Granularity");
     mLevels.resize (2);
     mLevelDirectionHists.resize (2);
     mEdgeCount.resize (2);
     mLeft.resize (2);
     intensityProcess (image, 0);
     intensityProcess (image, 1);
     //@note create histograms that are twice as wide for a wrap around.
     // To match direction histograms we correlate the cannoical size in the ring
     // of the other histogram
     mLevelDirectionHists[0] = vector<uint32> ((1 << ((8+1) * image.depth())));
     if (edgeDetect != 0.0f)
       gradientProcess ();
     else
       {
     for (uint32 fi = 0; fi < mLevels.size(); fi++)
       {
         mLevels[fi].push_back (mUnbound);
         mLevels[fi].push_back (mUnbound);
         mLevels[fi].push_back (mUnbound);
       }
       }
   }
Member Function Documentation
const rcWindow & rcSpatialPyramid< 2 >::base (int32 level) const
Definition at line 277 of file rc_kinepyr.cpp.
 {
   if (isValid ())
     return mLevels[level][0];
   else
     return mUnbound;
 }
const rcWindow & rcSpatialPyramid< 2 >::direction (int32 level) const
Definition at line 302 of file rc_kinepyr.cpp.
 {
   if (isValid ())
     return mLevels[level][3];
   else
     return mUnbound;
 }
const vector<uint32>& rcSpatialPyramid< 2 >::directionHistogram (int32 level) const
const rcWindow & rcSpatialPyramid< 2 >::edge (int32 level) const
Definition at line 310 of file rc_kinepyr.cpp.
 {
   if (isValid ())
     return mLevels[level][4];
   else
     return mUnbound;
 }
uint8 rcSpatialPyramid< 2 >::edgeLabel () inline
Definition at line 113 of file rc_kinepyr.h.
References EDGELabel.
 { return EDGELabel; }
const rcWindow & rcSpatialPyramid< 2 >::gradient (int32 level) const
Definition at line 294 of file rc_kinepyr.cpp.
 {
   if (isValid ())
     return mLevels[level][2];
   else
     return mUnbound;
 }
int32 rcSpatialPyramid< 2 >::gradientCount (int32 level) const inline
Definition at line 115 of file rc_kinepyr.h.
 { return mEdgeCount[level]; };
void rcSpatialPyramid< 2 >::gradientProcess () private
Definition at line 174 of file rc_kinepyr.cpp.
References rcWindow::depth(), rcWindow::height(), rcHistoStats::histogram(), rcHistoStats::median(), rcPixel16, rfHysteresisThreshold(), rfSetWindowBorder(), rfSobelEdge(), rfSpatialEdge(), rfSum(), rmAssert, rmExceptionMacro, rmMax, and rcWindow::width().
 {
   rmAssert (mLevels[0].size () == 2 && mLevels[1].size () == 2);
   for (uint32 fi = 0; fi < mLevels.size(); fi++)
     {
       rcWindow& image = mLevels[fi][1];
       // Allocate images and 0 the borders
       rcWindow mEi (image.width(), image.height(), image.depth());
       rcWindow mGi (image.width(), image.height(), image.depth());
       rcWindow mAi (image.width(), image.height(), m16bitDir ? rcPixel16 : image.depth());
       rfSetWindowBorder(mEi, uint8 (0));
       rfSetWindowBorder(mGi, uint8 (0));
       if (!m16bitDir)
     rfSetWindowBorder(mAi, uint8 (0));
       else
     rfSetWindowBorder(mAi, uint16 (0));
       rcWindow energy ((mEi), 1, 1, (mEi).width()-2, (mEi).height()-2);
       rcWindow grad ((mGi), 1, 1, (mGi).width()-2, (mGi).height()-2);
       rcWindow angle ((mAi), 1, 1, (mAi).width()-2, (mAi).height()-2);
       rfSobelEdge (image, energy, angle);
       rcHistoStats h (energy);
       uint8 low = (uint8) mEdgeDetect;
       uint8 high = (uint8) mHysteresis;
       vector<uint32> hist = h.histogram ();
       hist[0] = 0; rcHistoStats hsz (hist);
       low = rmMax (1, (uint8) hsz.median () / 2);
       high = rmMax (low, (uint8) hsz.median () * 2);
       if (mHysteresis == 0.0f)
     {
       mEdgeCount[fi] = (int32) (rfSpatialEdge ((mEi), (mAi), grad, low));
     }
       else
     {
       rcWindow buffer ((mEi).width(), (mEi).height());
       rcWindow gradholder (buffer, 1, 1, (mEi).width() - 2, (mEi).height() - 2);
       if (mZc)
         {
           if (m16bitDir)
         rmExceptionMacro (<<" Unimplemented Functionality");
           mEdgeCount[fi] = (int32) (rfSpatialEdge ((mEi), (mAi), gradholder, low));
           rfHysteresisThreshold (gradholder, grad, low, high, mLeft[fi],
                      mEdgeCount[fi] + 1, 0,
                      edgeLabel ());
         }
       else
         {
           const vector<uint32>& hist = h.histogram ();
           mEdgeCount[fi] = (int32) rfSum (hist);
           for (int32 i = 0; i <  low; i++) mEdgeCount[fi] -= hist[i];
           rfHysteresisThreshold (energy, grad, low, high, mLeft[fi], mEdgeCount[fi] + 1, 0,
                      edgeLabel ());
         }
     }
       mLevels[fi].push_back (mEi);
       mLevels[fi].push_back (mAi);
       mLevels[fi].push_back (mGi);
     }
 }
const int32 rcSpatialPyramid< 2 >::granularity () const inline
Definition at line 92 of file rc_kinepyr.h.
   {
     return mGranularity;
   }
const float rcSpatialPyramid< 2 >::hysteresis () const inline
Definition at line 87 of file rc_kinepyr.h.
   {
     return mHysteresis;
   }
rcIRect rcSpatialPyramid< 2 >::imageRect (int32 level) const
Definition at line 269 of file rc_kinepyr.cpp.
 {
   if (isValid ())
     return mLevels[level][0].rectangle ();
   else
     return rcIRect ();
 }
void rcSpatialPyramid< 2 >::intensityProcess (rcWindow & image, int32 level) private
Definition at line 126 of file rc_kinepyr.cpp.
References rcWindow::atTime(), rcWindow::depth(), rcWindow::height(), rfGaussianConv(), rfPixelSample(), rmAssert, and rcWindow::width().
 {
   rmAssert (level < (int32) (mLevels.size()));
   mLevels[level].clear ();
   // We smooth by a 5x5 Gaussian for every sample by 2.
   // Sampling is done with Aspect ratio untouched
   if (level == 0)
     {
       mLevels[level].push_back (image);
       rcWindow mLi (image.width(), image.height(), image.depth());
       rfGaussianConv (image, mLi, mGranularity);
       mLi.atTime (image);
       mLevels[level].push_back (mLi);
       rmAssert (isIdentity ());
       return;
     }
   rmAssert (mSample > 1 && level == 1);
   rcWindow tmp (image.width(), image.height(), image.depth());
   int32 smoothKernelWidth = (mSample * 5) - 1;
   rfGaussianConv (image, tmp, smoothKernelWidth);
   rcWindow sampled = rfPixelSample (tmp, mSample, mSample);
   sampled.atTime (image);
   mLevels[level].push_back (sampled);
   rcWindow mLi (sampled.width(), sampled.height(), sampled.depth());
   rfGaussianConv (sampled, mLi, mGranularity);
   mLi.atTime (image);
   mLevels[level].push_back (mLi);
   const rcRadian zr (0.0);
   const bool is_odd = mSample % 2;
  rc2Dvector translation (!is_odd ? -0.5 : 0.0, !is_odd ? -0.5 : 0.0);
   matrix (rcMatrix_2d (zr, rcDPair ((double) mSample,
                   (double) mSample)));
   trans (translation);
 }
bool rcSpatialPyramid< 2 >::isValid () const
Definition at line 242 of file rc_kinepyr.cpp.
 {
   bool v = mLevels.size() == 2 &&
     mLevels[0].size () > 1 &&
     mLevels[1].size () > 1 &&
     mLevels[0][0].isBound() &&
     mLevels[0][1].isBound() &&
     mLevels[1][0].isBound() &&
     mLevels[1][1].isBound();
   if (mEdgeDetect == 0.0f)
     return v;
   v = v &&
     mLevels[0].size () == 5 &&
     mLevels[1].size () == 5 &&
     mLevels[0][2].isBound() &&
     mLevels[0][3].isBound() &&
     mLevels[0][4].isBound() &&
     mLevels[1][2].isBound() &&
     mLevels[1][3].isBound() &&
     mLevels[1][4].isBound();
   return v;
 }
rcIPair rcSpatialPyramid< 2 >::kernelBorder () const inline
Definition at line 97 of file rc_kinepyr.h.
   {
     return (rcIPair (granularity()/2,granularity()/2) +
         rcIPair (5/2,5/2));
   }
int32 rcSpatialPyramid< 2 >::optimizedGradientCount (int32 level) const inline
Definition at line 117 of file rc_kinepyr.h.
 { return mLeft[level]; };
const rcWindow & rcSpatialPyramid< 2 >::past (int32 level) const
Definition at line 285 of file rc_kinepyr.cpp.
 {
   if (isValid ())
     return mLevels[level][1];
   else
     return mUnbound;
 }
rcIRect rcSpatialPyramid< 2 >::region () const inline
Definition at line 105 of file rc_kinepyr.h.
References rcWindow::height(), rcWindow::width(), rcPair< T >::x(), and rcPair< T >::y().
   {
     rcIPair kb = kernelBorder ();
     return rcIRect (kb.x(), kb.x(),
             base(0).width() - 2*kb.x(),
             base(0).height() - 2*kb.y());
   }
Member Data Documentation
bool rcSpatialPyramid< 2 >::m16bitDir private
Definition at line 132 of file rc_kinepyr.h.
vector<int32> rcSpatialPyramid< 2 >::mEdgeCount private
Definition at line 128 of file rc_kinepyr.h.
float rcSpatialPyramid< 2 >::mEdgeDetect private
Definition at line 124 of file rc_kinepyr.h.
int32 rcSpatialPyramid< 2 >::mGranularity private
Definition at line 123 of file rc_kinepyr.h.
float rcSpatialPyramid< 2 >::mHysteresis private
Definition at line 125 of file rc_kinepyr.h.
vector<int32> rcSpatialPyramid< 2 >::mLeft private
Definition at line 129 of file rc_kinepyr.h.
vector<vector<uint32> > rcSpatialPyramid< 2 >::mLevelDirectionHists private
Definition at line 127 of file rc_kinepyr.h.
vector<vector<rcWindow> > rcSpatialPyramid< 2 >::mLevels private
Definition at line 126 of file rc_kinepyr.h.
int32 rcSpatialPyramid< 2 >::mSample private
Definition at line 122 of file rc_kinepyr.h.
rcWindow rcSpatialPyramid< 2 >::mUnbound private
Definition at line 130 of file rc_kinepyr.h.
bool rcSpatialPyramid< 2 >::mZc private
Definition at line 131 of file rc_kinepyr.h.
The documentation for this class was generated from the following files:
include/analysis/rc_kinepyr.h
src/analysis/code/rc_kinepyr.cpp