Visible: rcMovieConverterToRfy Class Reference
rcMovieConverterToRfy Class Reference
#include <include/visual/rc_movieconverter.h>
Public Member Functions
rcMovieConverterToRfy (const rcMovieConverterOptionsRfy &opt, rcCarbonLock *l=NULL, rcProgressIndicator *p=NULL)
virtual ~rcMovieConverterToRfy ()
const rcMovieConverterOptionsRfy & options () const
void options (const rcMovieConverterOptionsRfy &o)
rcMovieConverterError convert (const std::string &inputFile, const std::string &outputFile)
rcMovieConverterError convert (const std::string &inputFile, const std::string &input2File, const std::string &outputFile, movieOriginType, std::string &typeInfo)
Public Member Functions inherited from rcMovieConverter
rcMovieConverter (bool verbose=true, rcCarbonLock *l=NULL, rcProgressIndicator *p=NULL)
virtual ~rcMovieConverter ()
bool verbose () const
rcSharedFrameBufPtr clippedFrame (rcSharedFrameBufPtr orig, rcMovieConverterOptions opt)
void verbose (bool v)
Private Member Functions
rcMovieConverterError createRfyMovie (rcVideoCache *inputCache, const std::string &outputFile)
rcMovieConverterError createRfyMovie (rcVideoCache *inputCache, rcVideoCache *input2Cache, const std::string &outputFile, movieOriginType, std::string &typeInfo)
rcMovieConverterError createRfyMovie (rcFrameGrabber &inputGrabber, const std::string &outputFile)
Private Attributes
rcMovieConverterOptionsRfy mOptions
Additional Inherited Members
Static Public Member Functions inherited from rcMovieConverter
static std::string getErrorString (const rcMovieConverterError &error)
static bool isReifyMovie (const std::string &name)
static bool isImageCollection (const std::string &name)
Protected Member Functions inherited from rcMovieConverter
void lock ()
void unlock ()
Protected Attributes inherited from rcMovieConverter
rcMovieConverterError mLastError
rcProgressIndicator * mProgress
bool mVerbose
rcCarbonLock * mCarbonLock
Detailed Description
Definition at line 205 of file rc_movieconverter.h.
Constructor & Destructor Documentation
rcMovieConverterToRfy::rcMovieConverterToRfy (const rcMovieConverterOptionsRfy & opt, rcCarbonLock * l = NULL, rcProgressIndicator * p = NULL)
Definition at line 239 of file rc_movieconverter.cpp.
                                                                        :
         rcMovieConverter( opt.verbose(), l, p ),
         mOptions( opt )
 {
}
rcMovieConverterToRfy::~rcMovieConverterToRfy () virtual
Definition at line 247 of file rc_movieconverter.cpp.
 {
 }
Member Function Documentation
rcMovieConverterError rcMovieConverterToRfy::convert (const std::string & inputFile, const std::string & outputFile) virtual
Implements rcMovieConverter.
Definition at line 253 of file rc_movieconverter.cpp.
References createRfyMovie(), cVideoCacheMem, cVideoCacheSize, eMovieConverterErrorOpen, eMovieConverterErrorUnknown, endl(), rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcMovieConverterOptions::frameInterval(), rcVideoCache::getErrorString(), rcVideoCache::getFatalError(), rcMovieConverter::isImageCollection(), rcMovieConverter::isReifyMovie(), rcVideoCache::isValid(), rcMovieConverter::mCarbonLock, rcMovieConverter::mLastError, mOptions, rcVideoCache::rcVideoCacheCtor(), rcVideoCache::rcVideoCacheDtor(), and rcMovieConverter::verbose().
Referenced by rcExperimentImpl::exportMovie(), rfConvertMovie(), and rfConvertTwoMovies().
 {
     mLastError = eMovieConverterErrorUnknown;
     bool srcReify = isReifyMovie( inputFile );
     if ( srcReify ) {
         rcVideoCache* cacheP = 0;
         cacheP = rcVideoCache::rcVideoCacheCtor( inputFile, cVideoCacheSize, false, false, false, cVideoCacheMem );
         if (!cacheP->isValid()) {
             if ( verbose() )
                 cerr << rcVideoCache::getErrorString( cacheP->getFatalError() ) << endl;
             mLastError = eMovieConverterErrorOpen;
         } else {
             mLastError = createRfyMovie( cacheP, outputFile );
         }
         rcVideoCache::rcVideoCacheDtor( cacheP );
     } else {
         if ( !isImageCollection( inputFile ) ) {
             rcMovieGrabber grabber( inputFile, mCarbonLock, mOptions.frameInterval() );
             mLastError = createRfyMovie( grabber, outputFile );
         } else {
             vector<std::string> fileNames;
             // Export selected images
             if ( !inputFile.empty() ) {
                 vector<const char*> files;
                 std::string::size_type str = 0, idx = 0;
                 int32 i = 0;
                 int32 firstIndex = mOptions.firstFrameIndex();
                 int32 frameCount = mOptions.frameCount();
                 while ( str < inputFile.size() ) {
                     idx = inputFile.find( ';', str );
                     if ( idx != std::string::npos ) {
                         if ( i >= firstIndex ) {
                             if ( frameCount >= 0 && fileNames.size() == uint32(frameCount) )
                                 break;
                             std::string oneFile = inputFile.substr( str, idx - str );
                             fileNames.push_back( oneFile );
                         }
                         str = idx + 1;
                         ++i;
                     } else
                         break;
                 }
 #ifdef DEBUG_LOG
                 cerr << "Exporting " <<  fileNames.size() << " images " << endl;
                 for ( uint32 x = 0; x < fileNames.size(); ++x ) {
                     cerr << fileNames[x] << endl;
                 }
 #endif
                 // Hack: mutate frame interval for image grabber
                 if ( mOptions.frameInterval() <= 0.0 )
                     mOptions.frameInterval(1.0);
                 rcImageGrabber grabber( fileNames, mCarbonLock, mOptions.frameInterval() );
                 mLastError = createRfyMovie( grabber, outputFile );
             }
         }
     }
     return mLastError;
 }
rcMovieConverterError rcMovieConverterToRfy::convert (const std::string & inputFile, const std::string & input2File, const std::string & outputFile, movieOriginType mot, std::string & typeInfo)
Definition at line 321 of file rc_movieconverter.cpp.
References createRfyMovie(), cVideoCacheMem, cVideoCacheSize, eMovieConverterErrorOpen, eMovieConverterErrorUnknown, endl(), rcVideoCache::getErrorString(), rcVideoCache::getFatalError(), rcMovieConverter::isReifyMovie(), rcVideoCache::isValid(), rcMovieConverter::mLastError, rcVideoCache::rcVideoCacheCtor(), rcVideoCache::rcVideoCacheDtor(), and rcMovieConverter::verbose().
 {
     mLastError = eMovieConverterErrorUnknown;
     bool srcReify = isReifyMovie( inputFile ) && isReifyMovie ( input2File );
     if ( srcReify ) {
         rcVideoCache* cacheP = 0;
         rcVideoCache* cache2P = 0;
         cacheP = rcVideoCache::rcVideoCacheCtor( inputFile, cVideoCacheSize, false, false, false, cVideoCacheMem );
         cache2P = rcVideoCache::rcVideoCacheCtor( input2File, cVideoCacheSize, false, false, false, cVideoCacheMem );
         if (!cacheP->isValid() || !cache2P->isValid()) {
       if ( verbose() )
         cerr << rcVideoCache::getErrorString( cacheP->getFatalError() ) << endl;
       mLastError = eMovieConverterErrorOpen;
         } else {
       mLastError = createRfyMovie( cacheP, cache2P, outputFile, mot, typeInfo );
         }
         rcVideoCache::rcVideoCacheDtor( cacheP );
         rcVideoCache::rcVideoCacheDtor( cache2P );
     }
     return mLastError;
 }
rcMovieConverterError rcMovieConverterToRfy::createRfyMovie (rcVideoCache * inputCache, const std::string & outputFile) private
Definition at line 349 of file rc_movieconverter.cpp.
References rcMovieConverterOptionsRfy::channelConversion(), rcMovieConverter::clippedFrame(), rcMovieConverterOptions::clipRect(), rcMovieConverterOptions::creator(), eGenMovieFileErrorOK, eMovieConverterErrorFlush, eMovieConverterErrorHeaderWrite, eMovieConverterErrorInternal, eMovieConverterErrorOK, eMovieConverterErrorRead, eMovieConverterErrorWrite, endl(), eVideoCacheStatusOK, rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcVideoCache::frameCount(), rcMovieConverterOptions::frameInterval(), rcMovieConverterOptions::frameOffset(), rcVideoCache::getErrorString(), rcVideoCache::getFrame(), mOptions, movieChannelAll, rcVideoCache::movieFileCameras(), rcVideoCache::movieFileConversions(), rcVideoCache::movieFileExperiments(), rcVideoCache::movieFileOrigins(), movieFormatRev1, rcMovieConverter::mProgress, rcMovieConverterOptions::overWrite(), rcProgressIndicator::progress(), rcMovieConverterOptionsRfy::rev(), rcMovieConverterOptions::reversePixels(), rfReversePixels8(), rmAssert, rcMovieConverterOptions::samplePeriod(), rcGenMovieFile::valid(), and rcMovieConverter::verbose().
Referenced by convert().
 {
     rcMovieConverterError error = eMovieConverterErrorOK;
     rmAssert(inputCache);
     rcVideoCache& cache = *inputCache;
     // Copy origin headers
     const vector<rcMovieFileOrgExt>& orgHdrs = cache.movieFileOrigins();
     rmAssert( !orgHdrs.empty() );
     // Reify movie generator
     rcGenMovieFile generator( outputFile,
                               mOptions.channelConversion(),
                               mOptions.rev(),
                               mOptions.overWrite(),
                               mOptions.frameInterval() );
     bool failed = !generator.valid();
     if ( failed ) {
         if ( verbose() )
             cerr << "rcGenMovieFile ctor failed" << endl;
         return eMovieConverterErrorInternal;
     }
     for ( uint32 i = 0; i < orgHdrs.size(); ++i ) {
         const rcMovieFileOrgExt& org = orgHdrs[i];
         generator.addHeader( org );
     }
     // Copy camera headers
     const vector<rcMovieFileCamExt>& camHdrs = cache.movieFileCameras();
     for ( uint32 i = 0; i < camHdrs.size(); ++i ) {
         const rcMovieFileCamExt& cam = camHdrs[i];
         generator.addHeader( cam );
     }
     // Copy experiment headers
     const vector<rcMovieFileExpExt>& expHdrs = cache.movieFileExperiments();
     for ( uint32 i = 0; i < expHdrs.size(); ++i ) {
         const rcMovieFileExpExt& exp = expHdrs[i];
         generator.addHeader( exp );
     }
     rcSharedFrameBufPtr frameBuf;
     rcVideoCacheError verror;
     rcVideoCacheStatus status = cache.getFrame(mOptions.frameOffset(), frameBuf, &verror);
     if (status != eVideoCacheStatusOK) {
         if ( verbose() )
             cerr << "Couldn't read frame: " << 0 << " error: "
                  << rcVideoCache::getErrorString(verror) << endl;
         return eMovieConverterErrorRead;
     }
     uint32 converted = 0;
     int32 frameCount = mOptions.frameCount();
     if ( frameCount < 0 )
         frameCount = cache.frameCount();
     const uint32 endMark = mOptions.frameOffset() +
         (mOptions.firstFrameIndex() + frameCount)*mOptions.samplePeriod();
     for (uint32 i = mOptions.frameOffset() + mOptions.firstFrameIndex()*mOptions.samplePeriod(); i < endMark; i += mOptions.samplePeriod()) {
         status = cache.getFrame(i, frameBuf, &verror);
         if (status != eVideoCacheStatusOK) {
             if ( verbose() )
                 cerr << "Couldn't read frame: " << i << " error: "
                      << rcVideoCache::getErrorString(verror) << endl;
             return eMovieConverterErrorRead;
         }
         frameBuf = clippedFrame( frameBuf, mOptions );
         if ( mOptions.reversePixels() ) {
             rcWindow w( frameBuf );
             rfReversePixels8( w );
         }
         rcGenMovieFileError gerr = generator.addFrame( frameBuf );
         if ( gerr != eGenMovieFileErrorOK ) {
             if ( verbose() )
                 cerr << "Output movie addFrame error: " << gerr << " " << outputFile << endl;
             return eMovieConverterErrorWrite;
         }
         ++converted;
         if ( mProgress )
             mProgress->progress( double(converted)/frameCount * 100 );
     } // End of: for (i = offset + firstIndex*period; i < endMark; i += period) {
     if (mOptions.rev() >= movieFormatRev1) {
         // Copy old conversion headers
         const vector<rcMovieFileConvExt>& conversions = cache.movieFileConversions();
         if ( !conversions.empty() ) {
             for ( uint32 i = 0; i < conversions.size(); ++i ) {
                 rcMovieFileConvExt cnvHdr = conversions[i];
                  rcGenMovieFileError gerr = generator.addHeader( cnvHdr );
                  if ( gerr != eGenMovieFileErrorOK ) {
                      if ( verbose() )
                          cerr << "Output movie addHeader error: " << gerr << " " << outputFile << endl;
                      return eMovieConverterErrorHeaderWrite;
                  }
             }
         }
         // Add new conversion header
         rcMovieFileConvExt cnvHdr( mOptions.firstFrameIndex() + mOptions.frameOffset(),
                                    frameCount,
                                    mOptions.samplePeriod(),
                                    mOptions.clipRect(),
                                    movieChannelAll,
                                    mOptions.frameInterval(),
                                    mOptions.reversePixels(),
                                    mOptions.creator().c_str() );
         rcGenMovieFileError gerr = generator.addHeader( cnvHdr );
         if ( gerr != eGenMovieFileErrorOK ) {
             if ( verbose() )
                 cerr << "Output movie addHeader error: " << gerr << " " << outputFile << endl;
             return eMovieConverterErrorHeaderWrite;
         }
     }
     // Flush and close file
     rcGenMovieFileError gerr = generator.flush();
     if ( gerr != eGenMovieFileErrorOK ) {
         if ( verbose() )
              cerr << "Output movie flush error: " << gerr << " " << outputFile << endl;
         return eMovieConverterErrorFlush;
     }
     return error;
 }
rcMovieConverterError rcMovieConverterToRfy::createRfyMovie (rcVideoCache * inputCache, rcVideoCache * input2Cache, const std::string & outputFile, movieOriginType mot, std::string & typeInfo) private
Definition at line 485 of file rc_movieconverter.cpp.
References rcMovieConverter::clippedFrame(), rcMovieConverterOptions::clipRect(), rcMovieConverterOptions::creator(), eGenMovieFileErrorOK, eMovieConverterErrorFlush, eMovieConverterErrorHeaderWrite, eMovieConverterErrorInternal, eMovieConverterErrorOK, eMovieConverterErrorRead, eMovieConverterErrorWrite, endl(), eVideoCacheStatusOK, rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcVideoCache::frameCount(), rcMovieConverterOptions::frameInterval(), rcMovieConverterOptions::frameOffset(), rcVideoCache::getErrorString(), rcVideoCache::getFrame(), mOptions, movieChannelAll, rcVideoCache::movieFileCameras(), rcVideoCache::movieFileConversions(), rcVideoCache::movieFileExperiments(), rcVideoCache::movieFileOrigins(), movieFormatRev1, rcMovieConverter::mProgress, rcMovieConverterOptions::overWrite(), rcProgressIndicator::progress(), rcPixel32, rcSelectAll, rcMovieConverterOptionsRfy::rev(), rcMovieConverterOptions::reversePixels(), rfReversePixels8(), rmAssert, rcMovieConverterOptions::samplePeriod(), rcGenMovieFile::valid(), and rcMovieConverter::verbose().
 {
     rcMovieConverterError error = eMovieConverterErrorOK;
     rmAssert(inputCache);
     rmAssert(input2Cache);
     rcVideoCache& cache = *inputCache;
     rcVideoCache& cache2 = *input2Cache;
     // Copy origin headers
     // @note for now copy headers only from the first movie
     const vector<rcMovieFileOrgExt>& orgHdrs = cache.movieFileOrigins();
     rmAssert( !orgHdrs.empty() );
     // Reify movie generator
     // @ note this is fixed for movieOriginGrayIsVisibleAlphaIsFlu.
     // @todo cleanup
     rcGenMovieFile generator( outputFile, mot,
                               rcSelectAll, mOptions.creator().c_str(),
                               mOptions.rev(),
                               mOptions.overWrite(),
                               mOptions.frameInterval() );
     bool failed = !generator.valid();
     if ( failed ) {
         if ( verbose() )
             cerr << "rcGenMovieFile ctor failed" << endl;
         return eMovieConverterErrorInternal;
     }
     //@note: this is a hack for now. Needs to be throught through
     const char * combined = "movieOriginGrayIsVisibleAlphaIsFlu";
     rcMovieFileOrgExt comb (mot,
                 orgHdrs[0].baseTime(),
                 orgHdrs[0].frameCount(),
                 orgHdrs[0].width(),
                 orgHdrs[0].height(),
                 rcPixel32,
                 orgHdrs[0].rev(),
                 typeInfo.c_str());
     generator.addHeader (comb);
     for ( uint32 i = 0; i < orgHdrs.size(); ++i ) {
         const rcMovieFileOrgExt& org = orgHdrs[i];
         generator.addHeader( org );
     }
     // Copy camera headers
     const vector<rcMovieFileCamExt>& camHdrs = cache.movieFileCameras();
     for ( uint32 i = 0; i < camHdrs.size(); ++i ) {
         const rcMovieFileCamExt& cam = camHdrs[i];
         generator.addHeader( cam );
     }
     // Copy experiment headers
     const vector<rcMovieFileExpExt>& expHdrs = cache.movieFileExperiments();
     for ( uint32 i = 0; i < expHdrs.size(); ++i ) {
         const rcMovieFileExpExt& exp = expHdrs[i];
         generator.addHeader( exp );
     }
     rcSharedFrameBufPtr frameBuf, frame2Buf;
     rcVideoCacheError verror;
     rcVideoCacheStatus status = cache.getFrame(mOptions.frameOffset(), frameBuf, &verror);
     if (status != eVideoCacheStatusOK) {
         if ( verbose() )
             cerr << "Couldn't read frame: " << 0 << " error: "
                  << rcVideoCache::getErrorString(verror) << endl;
         return eMovieConverterErrorRead;
     }
     status = cache2.getFrame(mOptions.frameOffset(), frame2Buf, &verror);
     // @note both movies have exact number of frames
     uint32 converted = 0;
     int32 frameCount = mOptions.frameCount();
     if ( frameCount < 0 )
         frameCount = cache.frameCount();
     const uint32 endMark = mOptions.frameOffset() +
         (mOptions.firstFrameIndex() + frameCount)*mOptions.samplePeriod();
     for (uint32 i = mOptions.frameOffset() + mOptions.firstFrameIndex()*mOptions.samplePeriod();
      i < endMark;
      i += mOptions.samplePeriod())
       {
         status = cache.getFrame(i, frameBuf, &verror);
         if (status != eVideoCacheStatusOK) {
             if ( verbose() )
                 cerr << "Couldn't read frame: " << i << " error: "
                      << rcVideoCache::getErrorString(verror) << endl;
             return eMovieConverterErrorRead;
         }
         status = cache2.getFrame(i, frame2Buf, &verror);
         if (status != eVideoCacheStatusOK) {
             if ( verbose() )
                 cerr << "Couldn't read frame: " << i << " error: "
                      << rcVideoCache::getErrorString(verror) << endl;
             return eMovieConverterErrorRead;
         }
         frameBuf = clippedFrame( frameBuf, mOptions );
         frame2Buf = clippedFrame( frame2Buf, mOptions );
         if ( mOptions.reversePixels() ) {
             rcWindow w( frameBuf );
             rfReversePixels8( w );
         }
         rcGenMovieFileError gerr = generator.addFrame( frameBuf, frame2Buf );
         if ( gerr != eGenMovieFileErrorOK ) {
             if ( verbose() )
                 cerr << "Output movie addFrame error: " << gerr << " " << outputFile << endl;
             return eMovieConverterErrorWrite;
         }
         ++converted;
         if ( mProgress )
             mProgress->progress( double(converted)/frameCount * 100 );
     } // End of: for (i = offset + firstIndex*period; i < endMark; i += period) {
     if (mOptions.rev() >= movieFormatRev1) {
         // Copy old conversion headers
         const vector<rcMovieFileConvExt>& conversions = cache.movieFileConversions();
         if ( !conversions.empty() ) {
             for ( uint32 i = 0; i < conversions.size(); ++i ) {
                 rcMovieFileConvExt cnvHdr = conversions[i];
                  rcGenMovieFileError gerr = generator.addHeader( cnvHdr );
                  if ( gerr != eGenMovieFileErrorOK ) {
                      if ( verbose() )
                          cerr << "Output movie addHeader error: " << gerr << " " << outputFile << endl;
                      return eMovieConverterErrorHeaderWrite;
                  }
             }
         }
         // Add new conversion header
         rcMovieFileConvExt cnvHdr( mOptions.firstFrameIndex() + mOptions.frameOffset(),
                                    frameCount,
                                    mOptions.samplePeriod(),
                                    mOptions.clipRect(),
                                    movieChannelAll,
                                    mOptions.frameInterval(),
                                    mOptions.reversePixels(),
                                    mOptions.creator().c_str() );
         rcGenMovieFileError gerr = generator.addHeader( cnvHdr );
         if ( gerr != eGenMovieFileErrorOK ) {
             if ( verbose() )
                 cerr << "Output movie addHeader error: " << gerr << " " << outputFile << endl;
             return eMovieConverterErrorHeaderWrite;
         }
     }
     // Flush and close file
     rcGenMovieFileError gerr = generator.flush();
     if ( gerr != eGenMovieFileErrorOK ) {
         if ( verbose() )
              cerr << "Output movie flush error: " << gerr << " " << outputFile << endl;
         return eMovieConverterErrorFlush;
     }
     return error;
 }
rcMovieConverterError rcMovieConverterToRfy::createRfyMovie (rcFrameGrabber & inputGrabber, const std::string & outputFile) private
Definition at line 655 of file rc_movieconverter.cpp.
References rcMovieConverterOptionsRfy::channelConversion(), channelType(), rcMovieConverter::clippedFrame(), rcMovieConverterOptions::clipRect(), rcMovieConverterOptions::creator(), rcWindow::depth(), eFrameErrorOK, eFrameStatusEOF, eFrameStatusOK, eGenMovieFileErrorOK, eMovieConverterErrorFlush, eMovieConverterErrorHeaderWrite, eMovieConverterErrorInternal, eMovieConverterErrorOK, eMovieConverterErrorOpen, eMovieConverterErrorRead, eMovieConverterErrorUnknown, endl(), rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcFrameGrabber::frameCount(), rcMovieConverterOptions::frameInterval(), rcMovieConverterOptions::frameOffset(), rcFrameGrabber::getErrorString(), rcFrameGrabber::getLastError(), rcFrameGrabber::getNextFrame(), rcFrameGrabber::isValid(), mOptions, rcMovieConverter::mProgress, rcMovieConverterOptions::overWrite(), rcProgressIndicator::progress(), rcPixel8, rcMovieConverterOptionsRfy::rev(), rcMovieConverterOptions::reversePixels(), rfReversePixels8(), rmAssert, rcMovieConverterOptions::samplePeriod(), rcTimestamp::secs(), rcFrameGrabber::start(), rcFrameGrabber::stop(), rcFrame::timestamp(), and rcMovieConverter::verbose().
 {
     rcMovieConverterError err = eMovieConverterErrorUnknown;
     int32 frames = 0;
     bool pixelsReversed = false;
     rcFrameGrabberError error = inputGrabber.getLastError();
     // Reify movie generator
     rcGenMovieFile generator( outputFile,
                               mOptions.channelConversion(),
                               mOptions.rev(),
                               mOptions.overWrite(),
                               mOptions.frameInterval() );
     if ( !generator.valid() ) {
         if ( verbose() )
             cerr << "rcGenMovieFile ctor failed" << endl;;
         return eMovieConverterErrorInternal;
     }
     // Grab everything
     if ( inputGrabber.isValid() ) {
         bool started = inputGrabber.start();
         if ( started ) {
             const int32 first = mOptions.frameOffset() + mOptions.firstFrameIndex() * mOptions.samplePeriod();
             int32 frameCount = mOptions.frameCount();
             if ( frameCount < 0 )
                 frameCount = inputGrabber.frameCount();
             // Time stamp of previous frame
             rcTimestamp prevTimeStamp = 0.0;
             bool firstFrame = true;
             int lastIndex = -mOptions.samplePeriod();
             // Note: infinite loop
             for( int32 i = 0; ; ++i ) {
                 rcSharedFrameBufPtr framePtr;
                 rcFrameGrabberStatus status = inputGrabber.getNextFrame( framePtr, true );
                 if ( status == eFrameStatusOK ) {
                     if ( i < first )
                         continue;
                     if ( frames == frameCount )
                         break;
                     if ( (i - lastIndex) < mOptions.samplePeriod() )
                         continue;
                     rcTimestamp curTimeStamp = framePtr->timestamp();
                     rcTimestamp frameInt = curTimeStamp - prevTimeStamp;
                     if ( firstFrame ) {
                         firstFrame = false;
                     } else {
                         // Zero time between frames is not allowed
                         if ( frameInt <= 0.0 )
                             if ( verbose() )
                                 fprintf( stderr, "Error: invalid frame interval %f for frame %i\n", frameInt.secs(), i );
                         rmAssert( frameInt > 0.0 );
                     }
                     framePtr = clippedFrame( framePtr, mOptions );
                     lastIndex = i;
                     prevTimeStamp = curTimeStamp;
                     rcWindow image;
                     image = rcWindow( framePtr );
                     ++frames;
                     if ( image.depth() == rcPixel8 ) {
                         if ( mOptions.reversePixels() ) {
                             rfReversePixels8( image );
                             pixelsReversed = true;
                         }
                     }
                     // Write a frame to disk
                     rcGenMovieFileError err = generator.addFrame( image );
                     if ( err != eGenMovieFileErrorOK )
                         break;
                     if ( mProgress )
                         mProgress->progress( double(frames)/frameCount * 100 );
                 } else if ( status == eFrameStatusEOF ) {
                     // no more frames available
                     break;
                 }
                 else {
                     // getNextFrame() failed, bail out
                     error = inputGrabber.getLastError();
                     break;
                 }
             }
         } else {
             // start() failed
             error = inputGrabber.getLastError();
             err = eMovieConverterErrorRead;
         }
         if ( ! inputGrabber.stop() ) {
             // stop() failed
             error = inputGrabber.getLastError();
             err = eMovieConverterErrorRead;
         }
     } else {
         // isValid() failed
         error = inputGrabber.getLastError();
         err = eMovieConverterErrorOpen;
     }
     if ( error != eFrameErrorOK ) {
         if ( verbose() )
             cerr << rcFrameGrabber::getErrorString( error ) << endl;
         return err;
     } else
         err = eMovieConverterErrorOK;
     // Add conversion header
     rcMovieFileConvExt cnvHdr( mOptions.firstFrameIndex() + mOptions.frameOffset(),
                                frames,
                                mOptions.samplePeriod(),
                                mOptions.clipRect(),
                                channelType(generator.conversion()),
                                mOptions.frameInterval(),
                                pixelsReversed,
                                mOptions.creator().c_str() );
     rcGenMovieFileError gerr = generator.addHeader( cnvHdr );
     if ( gerr != eGenMovieFileErrorOK ) {
         if ( verbose() )
             cerr << "Output movie addHeader error: " << gerr << " " << generator.fileName() << endl;
         return eMovieConverterErrorHeaderWrite;
     }
     // Flush and close output file
     gerr = generator.flush();
     if ( gerr != eGenMovieFileErrorOK ) {
         if ( verbose() )
             cerr << "Output movie flush error: " << gerr << " " << generator.fileName() << endl;
         return eMovieConverterErrorFlush;
     }
     return err;
 }
const rcMovieConverterOptionsRfy& rcMovieConverterToRfy::options () const inline
Definition at line 217 of file rc_movieconverter.h.
References mOptions.
 { return mOptions; }
void rcMovieConverterToRfy::options (const rcMovieConverterOptionsRfy & o) inline
Definition at line 222 of file rc_movieconverter.h.
References mOptions.
 { mOptions = o; }
Member Data Documentation
rcMovieConverterOptionsRfy rcMovieConverterToRfy::mOptions private
Definition at line 242 of file rc_movieconverter.h.
Referenced by convert(), createRfyMovie(), and options().
The documentation for this class was generated from the following files:
include/visual/rc_movieconverter.h
src/visual/code/rc_movieconverter.cpp