Visible: TCP_connection_data Class Reference
TCP_connection_data Class Reference
Public Member Functions
TCP_connection_data (void)
~TCP_connection_data (void)
TCP_connection_data (const TCP_connection_data &data)
void set_error (int error)
int error (void) const
std::string message (void) const
bool initialise (const int &socket, unsigned long address, unsigned short port)
bool initialised (void) const
unsigned long address (void) const
unsigned short port (void) const
bool send_ready (unsigned wait)
bool send (std::string &data)
bool receive_ready (unsigned wait)
bool receive (std::string &data)
bool close (void)
Private Attributes
TCP_socket m_socket
unsigned long m_address
unsigned short m_port
Friends
class TCP_server_data
Detailed Description
Definition at line 355 of file tcp.cpp.
Constructor & Destructor Documentation
TCP_connection_data::TCP_connection_data (void) inline
Definition at line 365 of file tcp.cpp.
References m_address, and m_port.
     {
       m_address = 0;
       m_port = 0;
     }
TCP_connection_data::~TCP_connection_data (void) inline
Definition at line 371 of file tcp.cpp.
References close().
     {
       close();
     }
TCP_connection_data::TCP_connection_data (const TCP_connection_data & data) inline
Definition at line 376 of file tcp.cpp.
References m_address, and m_port.
     {
       m_address = 0;
       m_port = 0;
       *this = data;
     }
Member Function Documentation
unsigned long TCP_connection_data::address (void) const inline
Definition at line 413 of file tcp.cpp.
References m_address.
Referenced by TCP_connection::address(), and initialise().
     {
       return m_address;
     }
bool TCP_connection_data::close (void) inline
Definition at line 443 of file tcp.cpp.
References TCP_socket::close(), m_address, m_port, and m_socket.
Referenced by TCP_connection::close(), initialise(), and ~TCP_connection_data().
     {
       m_address = 0;
       m_port = 0;
       return m_socket.close();
     }
int TCP_connection_data::error (void) const inline
Definition at line 388 of file tcp.cpp.
References TCP_socket::error(), and m_socket.
Referenced by TCP_connection::error().
     {
       return m_socket.error();
     }
bool TCP_connection_data::initialise (const int & socket, unsigned long address, unsigned short port) inline
Definition at line 398 of file tcp.cpp.
References address(), close(), m_address, m_port, m_socket, port(), and TCP_socket::set().
Referenced by TCP_server_data::connection().
     {
       bool result = true;
       close();
       m_socket.set(socket);
       m_address = address;
       m_port = port;
       return result;
     }
bool TCP_connection_data::initialised (void) const inline
Definition at line 408 of file tcp.cpp.
References TCP_socket::initialised(), and m_socket.
Referenced by TCP_connection::initialised().
     {
       return m_socket.initialised();
     }
std::string TCP_connection_data::message (void) const inline
Definition at line 393 of file tcp.cpp.
References m_socket, and TCP_socket::message().
Referenced by TCP_connection::message().
     {
       return m_socket.message();
     }
unsigned short TCP_connection_data::port (void) const inline
Definition at line 418 of file tcp.cpp.
References m_port.
Referenced by initialise(), and TCP_connection::port().
     {
       return m_port;
     }
bool TCP_connection_data::receive (std::string & data) inline
Definition at line 438 of file tcp.cpp.
References m_socket, and TCP_socket::receive().
Referenced by TCP_connection::receive().
     {
       return m_socket.receive(data);
     }
bool TCP_connection_data::receive_ready (unsigned wait) inline
Definition at line 433 of file tcp.cpp.
References m_socket, and TCP_socket::receive_ready().
Referenced by TCP_connection::receive_ready().
     {
       return m_socket.receive_ready(wait);
     }
bool TCP_connection_data::send (std::string & data) inline
Definition at line 428 of file tcp.cpp.
References m_socket, and TCP_socket::send().
Referenced by TCP_connection::send().
     {
       return m_socket.send(data);
     }
bool TCP_connection_data::send_ready (unsigned wait) inline
Definition at line 423 of file tcp.cpp.
References m_socket, and TCP_socket::send_ready().
Referenced by TCP_connection::send_ready().
     {
       return m_socket.send_ready(wait);
     }
void TCP_connection_data::set_error (int error) inline
Definition at line 383 of file tcp.cpp.
References m_socket, and TCP_socket::set_error().
     {
       m_socket.set_error(error);
     }
Friends And Related Function Documentation
friend class TCP_server_data friend
Definition at line 358 of file tcp.cpp.
Member Data Documentation
unsigned long TCP_connection_data::m_address private
Definition at line 360 of file tcp.cpp.
Referenced by address(), close(), initialise(), and TCP_connection_data().
unsigned short TCP_connection_data::m_port private
Definition at line 361 of file tcp.cpp.
Referenced by close(), initialise(), port(), and TCP_connection_data().
TCP_socket TCP_connection_data::m_socket private
Definition at line 359 of file tcp.cpp.
Referenced by close(), error(), initialise(), initialised(), message(), receive(), receive_ready(), send(), send_ready(), and set_error().
The documentation for this class was generated from the following file:
include/stlplus/tcp.cpp