Visible: rcModelDomain Class Reference
rcModelDomain Class Reference
#include <include/visUI/rc_modeldomain.h>
Public Slots
void requestStart (void)
void requestStop (void)
void requestProcess (void)
void requestNew (void)
void requestNewApp (void)
void requestOpen (rcExperimentImportMode mode)
void requestClose (void)
void requestSave (rcExperimentFileFormat format)
void requestImageImport (void)
void requestTifDirImport (void)
void requestMovieImport (void)
void requestSTKImport (void)
void requestMovieSave (void)
void requestInputSource (int)
void timerTick (void)
void requestTrackingPause (void)
void stopTrackingPause (void)
Signals
void elapsedTime (const rcTimestamp &time)
void cursorTime (const rcTimestamp &time)
void newState (rcExperimentState state)
void updateDisplay (const rcWindow *image)
void updateDisplay (const rcVisualGraphicsCollection *graphics)
void updateSettings ()
void updateAnalysisRect (const rcRect &rect)
void updateAnalysisRectRotation (const rcAffineRectangle &affine)
void updateTimelineRange (const rcTimestamp &start, const rcTimestamp &end)
void updateTimelineScale (rcResultScaleMode scale)
void updateMultiplier (double multiplier)
void updateDisplay ()
void updateStatus (const char *statusString)
void imageImport ()
void tifDirImport ()
void movieImport ()
void stkImport ()
void movieSave ()
void updateInputSource (int i)
void updateMonitorScale (double scaleFactor)
void updateMonitorDisplay ()
void updateVideoRect (const rcRect &rect)
void updateCameraState (bool liveCamera, bool liveStorage)
void updateDebugging ()
void updateSelectionState (bool b)
Public Member Functions
rcModelDomain (QObject *parent, const char *modelKey)
~rcModelDomain ()
rcExperiment * getExperiment (void)
const rcExperimentAttributes getExperimentAttributes (void)
bool operatingOnLiveInput (void)
bool storingLiveInput (void)
virtual void setExperimentAttributes (const rcExperimentAttributes &attr)
rcExperimentState getExperimentState (void)
rcTimestamp getExperimentLength (void)
rcTimestamp getExperimentStart (void)
std::string getLicenseExpirationTime (void)
rcTimestamp getCursorTime (void)
void notifySettingChange (void)
void notifyUpdateDisplay (void)
virtual void notifyCursorTime (const rcTimestamp &cursorTime)
virtual void notifyAnalysisRect (const rcRect &rect)
virtual void notifyAnalysisRectRotation (const rcAffineRectangle &)
virtual void notifyTimelineScale (rcResultScaleMode scale)
virtual void notifyMultiplier (const double &multiplier)
void notifyUpdateMonitor (void)
void notifyUpdateDebugging (void)
virtual bool acceptingImageBlits (void)
virtual void notifyError (const char *errorString)
virtual void notifyWarning (const char *warnString)
virtual void notifyStatus (const char *statusString)
virtual void notifyState (rcExperimentState newState, bool immediateDispatch)
virtual void notifyTime (const rcTimestamp &elapsedTime)
virtual void notifyProgCursorTime (const rcTimestamp &elapsedTime)
virtual int32 progCursorTimeEventCount () const
virtual void notifyTimelineRange (const rcTimestamp &start, const rcTimestamp &end)
virtual void notifyEngineTimelineRange (const rcTimestamp &start, const rcTimestamp &end)
virtual void notifyBlitData (const rcWindow *image)
virtual void notifyBlitGraphics (const rcVisualGraphicsCollection *graphics)
virtual void notifyLockApp (bool lock)
virtual void notifyExperimentChange (void)
virtual void notifyVideoRect (const rcRect &rect)
void notifyStatusInternal (const char *statusString)
virtual bool acceptingPolys (void)
virtual void notifyPolys ()
virtual void getPolys (rcPolygonGroupRef &polys)
rcPolygonGroupRef polys ()
uint32 polysSize () const
void dumpPolys () const
void notifySelectionState (bool b)
Public Member Functions inherited from rcExperimentObserver
virtual ~rcExperimentObserver ()
Static Public Member Functions
static rcModelDomain * getModelDomain (void)
Protected Member Functions
void customEvent (QEvent *e)
Private Member Functions
void rle (rcSecurityError status)
bool vl ()
Private Attributes
rcExperimentDomain * mDomain
rcLicenseManager mLicenseManager
rcCustomEventManager mEventQueueManager
rcTimestamp mCursorTime
rcPolygonGroupRef mSelectPolygons
Detailed Description
Definition at line 30 of file rc_modeldomain.h.
Constructor & Destructor Documentation
rcModelDomain::rcModelDomain (QObject * parent, const char * modelKey)
Definition at line 35 of file rc_modeldomain.cpp.
References rcExperimentDomainFactory::getExperimentDomain(), rcExperimentDomain::initialize(), mDomain, mSelectPolygons, rcUNUSED, and rmExceptionMacro.
         : QObject( parent, cModelDomainName ),
           mLicenseManager( cLicenseFilePath, true ),
             mEventQueueManager( this ),
           mCursorTime( 0.0 )
 {
   rcUNUSED( modelName );
   mDomain = (rcExperimentDomain*)   rcExperimentDomainFactory::getExperimentDomain( "testDomain" );
   if (mDomain == 0)
     rmExceptionMacro ( "Can't find experiment domain" );
   mDomain->initialize( this );
   _modelDomainSingleton = this;
   // Optimize all Qt pixmaps for speed
 //  QPixmap::setDefaultOptimization( QPixmap::BestOptim );
     rcSharedPolygonGroupPtr c0 (new rcPolygonGroup );
   rcPolygonGroupRef cellsRef (c0) ;
   mSelectPolygons = cellsRef;
   installEventFilter (this);
 }
rcModelDomain::~rcModelDomain ()
Definition at line 58 of file rc_modeldomain.cpp.
References mDomain, and rcExperimentDomain::shutdown().
 {
     mDomain->shutdown();
 }
Member Function Documentation
bool rcModelDomain::acceptingImageBlits (void) virtual
Implements rcExperimentObserver.
Definition at line 298 of file rc_modeldomain.cpp.
 {
   return true;
 }
bool rcModelDomain::acceptingPolys (void) virtual
Implements rcExperimentObserver.
Definition at line 304 of file rc_modeldomain.cpp.
 {
   return true;
 }
void rcModelDomain::cursorTime (const rcTimestamp & time) signal
Definition at line 195 of file moc_rc_modeldomain.cpp.
Referenced by customEvent(), and notifyCursorTime().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 1, _a);
 }
void rcModelDomain::customEvent (QEvent * e) protected
Definition at line 885 of file rc_modeldomain.cpp.
References cAppName, cursorTime(), elapsedTime(), endl(), eNotifyAnalysisRectEvent, eNotifyAnalysisRectRotationEvent, eNotifyBlitEvent, eNotifyBlitGraphicsEvent, eNotifyCursorEvent, eNotifyErrorEvent, eNotifyExperimentChange, eNotifyMultiplierEvent, eNotifyStateEvent, eNotifyStatusEvent, eNotifyTimeEvent, eNotifyTimelineRangeEvent, eNotifyVideoRectEvent, eNotifyWarningEvent, rcTimestampPair::first(), mEventQueueManager, rcBaseEvent< T, id >::myData(), newState(), notifyStatusInternal(), rcCustomEventManager::processedEvent(), rcTimestampPair::second(), updateAnalysisRect(), updateAnalysisRectRotation(), updateDisplay(), updateMultiplier(), updateSettings(), updateTimelineRange(), and updateVideoRect().
 {
     int type = e->type();
 #ifdef DEBUG_LOG
     cout << "rcModelDomain user event " << type << endl;
 #endif
     switch ( type ) {
         case eNotifyErrorEvent:
         {
                     rcBaseErrorEvent* ev = static_cast<rcBaseErrorEvent *> (e);
                     const QString& string = ev->myData ();
                      QMessageBox::critical( 0 , cAppName , string , 1 , 0 );
         }
         break;
         case eNotifyWarningEvent:
         {
             rcBaseWarningEvent* ev = static_cast<rcBaseWarningEvent *> (e);
             const QString& string = ev->myData ();
             QMessageBox::warning( 0 , cAppName , string , 1 , 0 );
         }
         break;
         case eNotifyStatusEvent:
         {
             rcBaseStatusEvent* ev = static_cast<rcBaseStatusEvent *> (e);
             const QString& string = ev->myData();
             // Use status bar widget
             notifyStatusInternal( string.latin1() );
         }
         break;
         case eNotifyTimeEvent:
         {
                     rcBaseTimeEvent* ev = static_cast<rcBaseTimeEvent *> (e);
             // Produce elapsed time notification
                     const rcTimestamp& time = ev->myData();
             emit elapsedTime( time );
         }
         break;
         case eNotifyCursorEvent:
         {
             // Produce cursor movement notification
                     rcBaseCursorEvent* ev = static_cast<rcBaseCursorEvent *> (e);
             const rcTimestamp& time = ev->myData();
             emit cursorTime( time );
         }
         break;
         case eNotifyTimelineRangeEvent:
         {
             // Notify timeline range change
             rcBaseTimelineRangeEvent* ev = static_cast<rcBaseTimelineRangeEvent *> (e);
             rcTimestampPair timePair = ev->myData();
             emit updateTimelineRange( timePair.first(), timePair.second() );
         }
         break;
         case eNotifyStateEvent:
         {
             rcBaseStateEvent* ev = static_cast<rcBaseStateEvent *> (e);
             const rcExperimentState& state = ev->myData();
             // Notify the rest
             emit newState( state );
             emit updateSettings();
         }
         break;
         case eNotifyBlitEvent:
         {
             rcBaseBlitEvent* ev = static_cast<rcBaseBlitEvent *> (e);
             const rcWindow& image = ev->myData();
             emit updateDisplay( &image );
         }
         break;
         case eNotifyBlitGraphicsEvent:
         {
             rcBaseBlitGraphicsEvent* ev = static_cast<rcBaseBlitGraphicsEvent *> (e);
             const rcVisualGraphicsCollection& graphics = ev->myData();
             emit updateDisplay( & graphics );
         }
         break;
         case eNotifyAnalysisRectEvent:
         {
             rcBaseAnalysisRectEvent* ev = static_cast<rcBaseAnalysisRectEvent *> (e);
             const rcRect& rect = ev->myData();
             emit updateAnalysisRect( rect );
         }
         break;
         case eNotifyAnalysisRectRotationEvent:
         {
             rcBaseAnalysisRectRotationEvent* ev = static_cast<rcBaseAnalysisRectRotationEvent *> (e);
                     const rcAffineRectangle& affine = ev->myData();
       emit updateAnalysisRectRotation( affine );
         }
         break;
         case eNotifyMultiplierEvent:
         {
             rcBaseMultiplierEvent* ev = static_cast<rcBaseMultiplierEvent *> (e);
             const double& multiplier = ev->myData();
             emit updateMultiplier( multiplier );
         }
         break;
         case eNotifyExperimentChange:
             emit updateSettings();
             break;
         case eNotifyVideoRectEvent:
         {
             rcBaseVideoRectEvent* ev = static_cast<rcBaseVideoRectEvent *> (e);
             const rcRect& rect = ev->myData();
             emit updateVideoRect( rect );
         }
         break;
     }
    mEventQueueManager.processedEvent( e );
 }
void rcModelDomain::dumpPolys () const inline
Definition at line 174 of file rc_modeldomain.h.
References endl(), mSelectPolygons, and rcPolygonGroupRef::polys().
   {
     const vector<rcPolygon>& pgs = const_cast<rcModelDomain*>(this)->mSelectPolygons.polys ();
     for (uint32 i = 0; i < pgs.size (); i++)
       {
     cerr << pgs[i] << endl;
       }
   }
void rcModelDomain::elapsedTime (const rcTimestamp & time) signal
Definition at line 188 of file moc_rc_modeldomain.cpp.
Referenced by customEvent(), and timerTick().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
rcTimestamp rcModelDomain::getCursorTime (void)
Definition at line 139 of file rc_modeldomain.cpp.
References mCursorTime.
Referenced by rcImageCanvasGL::findCellPositionTracks(), rcImageCanvasGL::getToolTipText(), and rcCellInfoWidget::updateTrackDisplay().
 {
     return mCursorTime;
 }
rcExperiment * rcModelDomain::getExperiment (void)
Definition at line 76 of file rc_modeldomain.cpp.
References rcExperimentDomain::getExperiment(), and mDomain.
Referenced by rcTrackManager::addTracks(), rcTimeline::checkScalarTrackScales(), countDisplayableGroups(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::enableCellGroup(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), rcTrackManager::getHiliteTrack(), rcImageCanvasGL::getToolTipText(), rcTrackManager::groupType(), rcTrackManager::hasManageableTracks(), rcTimeline::keyPressEvent(), rcScalarTrackWidget::mousePressEvent(), rcTimeline::paintTimeline(), rcScalarTrackWidget::rcScalarTrackWidget(), rcTrackGroupWidget::rcTrackGroupWidget(), rcTrackGroupWidget::setEnabled(), rcMonitor::settingChanged(), rcSettingPanel::updatePages(), rcScalarTrackWidget::updateSettings(), rcCellInfoWidget::updateTrackDisplay(), rcScalarTrackWidget::updateTrackDisplay(), and rcTrackPanel::updateTrackGroups().
 {
     return mDomain->getExperiment();
 }
const rcExperimentAttributes rcModelDomain::getExperimentAttributes (void)
Definition at line 90 of file rc_modeldomain.cpp.
References rcExperimentDomain::getExperimentAttributes(), and mDomain.
Referenced by rcFileSaveSettingWidget::browseRequest(), rcTrackManager::copyTrackToClipboard(), rcTrackManager::hasManageableTracks(), rcMonitor::imageRect(), rcMonitor::inputIsCamera(), rcTimeline::inputIsCamera(), rcMonitor::inputIsStored(), rcTimeline::inputIsStored(), rcImageCanvasGL::keyPressEvent(), rcImageCanvasGL::mouseReleaseEvent(), rcRectSettingWidget::rcRectSettingWidget(), rcRectSettingWidget::selectAll(), rcRectSettingWidget::setMaxValues(), rcMainWindow::settingChanged(), rcScalarTrackWidget::updateTrackDisplay(), and rcRectSettingWidget::valueChanged().
 {
     return mDomain->getExperimentAttributes();
 }
rcTimestamp rcModelDomain::getExperimentLength (void)
Definition at line 121 of file rc_modeldomain.cpp.
References rcExperimentDomain::getExperimentLength(), and mDomain.
Referenced by rcTimeline::keyNavigateEvent(), rcTimeline::keyRangeScaleEvent(), rcTimeline::paintScalarTrack(), rcModelProgress::progress(), and rcTimeline::resetAllScales().
 {
     return mDomain->getExperimentLength();
 }
rcTimestamp rcModelDomain::getExperimentStart (void)
Definition at line 127 of file rc_modeldomain.cpp.
References rcExperimentDomain::getExperimentStart(), and mDomain.
Referenced by rcTimeline::paintScalarTrack().
 {
     return mDomain->getExperimentStart();
 }
rcExperimentState rcModelDomain::getExperimentState (void)
Definition at line 115 of file rc_modeldomain.cpp.
References rcExperimentDomain::getExperimentState(), and mDomain.
Referenced by rcMainWindow::closeEvent(), rcControlPanel::inputSource(), requestClose(), requestNew(), requestOpen(), and rcMonitor::updateStatus().
 {
     return mDomain->getExperimentState();
 }
std::string rcModelDomain::getLicenseExpirationTime (void)
Definition at line 133 of file rc_modeldomain.cpp.
References rcLicenseManager::getLicenseExpirationTime(), and mLicenseManager.
Referenced by rcMenuBar::about(), and rcAbout::languageChange().
 {
     return mLicenseManager.getLicenseExpirationTime();
 }
rcModelDomain * rcModelDomain::getModelDomain (void) static
Definition at line 64 of file rc_modeldomain.cpp.
References _modelDomainSingleton, and rmExceptionMacro.
Referenced by rcMenuBar::about(), rcTrackManager::addTracks(), rcFileSaveSettingWidget::browseRequest(), rcTimeline::checkScalarTrackScales(), rcRadioChoiceSettingWidget::choiceSelected(), rcFramerateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::choiceSelected(), rcTextChoiceSettingWidget::choiceSelected(), rcNumericChoiceSettingWidget::choiceSelected(), rcRateChoiceSettingWidget::choiceSelected(), rcMainWindow::closeEvent(), rcTrackManager::copyTrackToClipboard(), countDisplayableGroups(), rcFileChoiceSettingWidget::directoryBrowse(), rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcMonitor::displayTrackFocus(), rcMenuBar::doExport(), rcMenuBar::doExportMovie(), rcMenuBar::doExportNativeMovie(), rcMenuBar::doOpen(), rcMenuBar::doOpenSettings(), rcMenuBar::doSave(), rcImageCanvasGL::drawCurrentFocus(), rcImageCanvasGL::enableCellGroup(), rcImageCanvasGL::findCellPositionTracks(), rcPlaybackSettingWidget::fwdVideo(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), rcTrackManager::getHiliteTrack(), rcImageCanvasGL::getToolTipText(), rcTrackManager::groupType(), rcTrackManager::hasManageableTracks(), rcTrackManager::hiliteTracks(), rcMonitor::imageRect(), rcMonitor::inputIsCamera(), rcTimeline::inputIsCamera(), rcMonitor::inputIsStored(), rcTimeline::inputIsStored(), rcControlPanel::inputSource(), rcFramerateChoiceSettingWidget::intervalChanged(), rcTimeline::keyCameraEvent(), rcTimeline::keyNavigateEvent(), rcTimeline::keyPressEvent(), rcImageCanvasGL::keyPressEvent(), rcTimeline::keyRangeScaleEvent(), rcAbout::languageChange(), rcImageCanvasGL::mouseDoubleClickEvent(), rcTimeline::mouseMoveEvent(), rcScalarTrackWidget::mousePressEvent(), rcTimeline::mouseReleaseEvent(), rcImageCanvasGL::mouseReleaseEvent(), rcFileChoiceSettingWidget::multiFileBrowse(), rcTimeline::paintScalarTrack(), rcTimeline::paintTimeline(), rcCellInfoWidget::rcCellInfoWidget(), rcCheckboxSettingWidget::rcCheckboxSettingWidget(), rcControlPanel::rcControlPanel(), rcFileChoiceSettingWidget::rcFileChoiceSettingWidget(), rcFileSaveSettingWidget::rcFileSaveSettingWidget(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcMainWindow::rcMainWindow(), rcMenuBar::rcMenuBar(), rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget(), rcMonitor::rcMonitor(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcPlaybackSettingWidget::rcPlaybackSettingWidget(), rcRadioChoiceSettingWidget::rcRadioChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcRectSettingWidget::rcRectSettingWidget(), rcScalarTrackWidget::rcScalarTrackWidget(), rcSettingPanel::rcSettingPanel(), rcSpinboxSettingWidget::rcSpinboxSettingWidget(), rcStatusBar::rcStatusBar(), rcTextAreaSettingWidget::rcTextAreaSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), rcTextLineSettingWidget::rcTextLineSettingWidget(), rcThumbWheelSettingWidget::rcThumbWheelSettingWidget(), rcTimeline::rcTimeline(), rcTrackGroupWidget::rcTrackGroupWidget(), rcTrackManager::rcTrackManager(), rcTrackPanel::rcTrackPanel(), rcTimeline::resetAllScales(), rcPlaybackSettingWidget::revVideo(), rcTimeline::scrollRange(), rcRectSettingWidget::selectAll(), rcImageCanvasGL::selectButtonRelease(), rcScalarTrackWidget::setEnabled(), rcTrackGroupWidget::setEnabled(), rcTrackManager::setHiliteTrack(), rcRectSettingWidget::setMaxValues(), rcRadioChoiceSettingWidget::settingChanged(), rcMenuChoiceSettingWidget::settingChanged(), rcFramerateChoiceSettingWidget::settingChanged(), rcRectSettingWidget::settingChanged(), rcMainWindow::settingChanged(), rcNumericChoiceSettingWidget::settingChanged(), rcTextChoiceSettingWidget::settingChanged(), rcRateChoiceSettingWidget::settingChanged(), rcMonitor::settingChanged(), rcTrackManager::setTrackPen(), rcFileChoiceSettingWidget::singleFileBrowse(), rcPlaybackSettingWidget::stopVideo(), rcControlPanel::updateCursorTime(), rcControlPanel::updateElapsedTime(), rcSettingPanel::updatePages(), rcScalarTrackWidget::updateSettings(), rcTimeline::updateSettings(), rcControlPanel::updateState(), rcTimeline::updateState(), rcMonitor::updateStatus(), rcCellInfoWidget::updateTrackDisplay(), rcScalarTrackWidget::updateTrackDisplay(), rcTrackPanel::updateTrackGroups(), rcTextAreaSettingWidget::valueChanged(), rcCheckboxSettingWidget::valueChanged(), rcTextLineSettingWidget::valueChanged(), rcRectSettingWidget::valueChanged(), rcFileSaveSettingWidget::valueChanged(), rcFileChoiceSettingWidget::valueChanged(), rcPlaybackSettingWidget::valueChanged(), and rcSpinboxSettingWidget::valueChanged().
 {
     // this will should never happen (we should create an instance of
     //  the model domain right after the Qt application object), but
     //  just to be sure....
     if (_modelDomainSingleton == 0)
         rmExceptionMacro ( "Fatal error: null model domain singleton" );
     return _modelDomainSingleton;
 }
void rcModelDomain::getPolys (rcPolygonGroupRef & polys) virtual
Implements rcExperimentObserver.
Definition at line 346 of file rc_modeldomain.cpp.
References mSelectPolygons.
 {
   pgs = mSelectPolygons;
 }
void rcModelDomain::imageImport (void) signal
Definition at line 277 of file moc_rc_modeldomain.cpp.
Referenced by requestImageImport().
 {
     QMetaObject::activate(this, &staticMetaObject, 13, 0);
 }
void rcModelDomain::movieImport (void) signal
Definition at line 289 of file moc_rc_modeldomain.cpp.
Referenced by requestMovieImport().
 {
     QMetaObject::activate(this, &staticMetaObject, 15, 0);
 }
void rcModelDomain::movieSave (void) signal
Definition at line 301 of file moc_rc_modeldomain.cpp.
Referenced by requestMovieSave().
 {
     QMetaObject::activate(this, &staticMetaObject, 17, 0);
 }
void rcModelDomain::newState (rcExperimentState state) signal
Definition at line 202 of file moc_rc_modeldomain.cpp.
Referenced by customEvent(), and notifyState().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 2, _a);
 }
void rcModelDomain::notifyAnalysisRect (const rcRect & rect) virtual
Implements rcExperimentObserver.
Definition at line 281 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
Referenced by rcImageCanvasGL::keyPressEvent(), rcScalarTrackWidget::mousePressEvent(), rcImageCanvasGL::mouseReleaseEvent(), rcRectSettingWidget::selectAll(), and rcRectSettingWidget::valueChanged().
 {
     rcBaseAnalysisRectEvent *ev = new rcBaseAnalysisRectEvent (rect);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyAnalysisRectRotation (const rcAffineRectangle & affine) virtual
Implements rcExperimentObserver.
Definition at line 289 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
Referenced by rcImageCanvasGL::mouseReleaseEvent().
 {
     rcBaseAnalysisRectRotationEvent *ev = new rcBaseAnalysisRectRotationEvent (affine);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyBlitData (const rcWindow * image) virtual
Implements rcExperimentObserver.
Definition at line 311 of file rc_modeldomain.cpp.
References eNotifyBlitEvent, mEventQueueManager, rcCustomEventManager::postEvent(), and rcCustomEventManager::queuedEvents().
 {
     int32 queued = mEventQueueManager.queuedEvents( eNotifyBlitEvent );
     // Post new event only if queue is empty
     if ( queued < 1 ) {
             rcBaseBlitEvent *ev = new rcBaseBlitEvent (*image);
             mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
     }
 }
void rcModelDomain::notifyBlitGraphics (const rcVisualGraphicsCollection * graphics) virtual
Implements rcExperimentObserver.
Definition at line 326 of file rc_modeldomain.cpp.
References eNotifyBlitGraphicsEvent, mEventQueueManager, rcCustomEventManager::postEvent(), and rcCustomEventManager::queuedEvents().
 {
     int32 queued = mEventQueueManager.queuedEvents( eNotifyBlitGraphicsEvent );
     // Post new event only if queue has less than 2 pending events
     if ( queued < 2 ) {
             rcBaseBlitGraphicsEvent *ev = new rcBaseBlitGraphicsEvent (*graphics);
             mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
     }
 }
void rcModelDomain::notifyCursorTime (const rcTimestamp & cursorTime) virtual
Definition at line 170 of file rc_modeldomain.cpp.
References cursorTime(), mCursorTime, mDomain, and rcExperimentDomain::notifyCursorTime().
Referenced by rcTimeline::keyNavigateEvent(), rcTimeline::mouseMoveEvent(), rcTimeline::mouseReleaseEvent(), rcTimeline::updateSettings(), and rcTimeline::updateState().
 {
     mCursorTime = cTime;
     mDomain->notifyCursorTime(cTime);
     emit cursorTime( cTime );
 }
void rcModelDomain::notifyEngineTimelineRange (const rcTimestamp & start, const rcTimestamp & end) virtual
Implements rcExperimentObserver.
Definition at line 240 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     rcBaseTimelineRangeEvent *ev = new rcBaseTimelineRangeEvent (rcTimestampPair (start, end));
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyError (const char * errorString) virtual
Implements rcExperimentObserver.
Definition at line 205 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     rcBaseErrorEvent *ev = new rcBaseErrorEvent (QString( errorString ) );
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyExperimentChange (void) virtual
Implements rcExperimentObserver.
Definition at line 360 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     const int32 dummy (0);
     rcBaseExperimentChangeEvent* ev = new rcBaseExperimentChangeEvent (dummy);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyLockApp (bool lock) virtual
Implements rcExperimentObserver.
Definition at line 375 of file rc_modeldomain.cpp.
References endl().
 {
 #ifdef DEBUG_LOG
     cerr << "notifyLockApp " << lock << endl;
 #endif
     if ( lock )
         qApp->lock();
     else
         qApp->unlock();
 }
void rcModelDomain::notifyMultiplier (const double & multiplier) virtual
Implements rcExperimentObserver.
Definition at line 352 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     rcBaseMultiplierEvent *ev = new rcBaseMultiplierEvent (multiplier);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyPolys () virtual
Implements rcExperimentObserver.
Definition at line 341 of file rc_modeldomain.cpp.
References mDomain, mSelectPolygons, and rcExperimentDomain::notifyPolys().
Referenced by rcImageCanvasGL::mouseDoubleClickEvent().
 {
   mDomain->notifyPolys (&mSelectPolygons);
 }
void rcModelDomain::notifyProgCursorTime (const rcTimestamp & elapsedTime) virtual
Implements rcExperimentObserver.
Definition at line 266 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     rcBaseCursorEvent *ev = new rcBaseCursorEvent (cTime);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifySelectionState (bool b) inline
Definition at line 183 of file rc_modeldomain.h.
References updateSelectionState().
Referenced by rcImageCanvasGL::mouseDoubleClickEvent().
   {
     emit updateSelectionState (b);
   }
void rcModelDomain::notifySettingChange (void)
Definition at line 145 of file rc_modeldomain.cpp.
References updateSettings().
Referenced by rcFileSaveSettingWidget::browseRequest(), rcRadioChoiceSettingWidget::choiceSelected(), rcFramerateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::choiceSelected(), rcNumericChoiceSettingWidget::choiceSelected(), rcTextChoiceSettingWidget::choiceSelected(), rcRateChoiceSettingWidget::choiceSelected(), rcFileChoiceSettingWidget::directoryBrowse(), rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcPlaybackSettingWidget::fwdVideo(), rcFramerateChoiceSettingWidget::intervalChanged(), rcFileChoiceSettingWidget::multiFileBrowse(), notifyUpdateDebugging(), requestSave(), rcPlaybackSettingWidget::revVideo(), rcScalarTrackWidget::setEnabled(), rcTrackGroupWidget::setEnabled(), rcFramerateChoiceSettingWidget::settingChanged(), rcRectSettingWidget::settingChanged(), rcNumericChoiceSettingWidget::settingChanged(), rcTextChoiceSettingWidget::settingChanged(), rcRateChoiceSettingWidget::settingChanged(), rcFileChoiceSettingWidget::singleFileBrowse(), rcPlaybackSettingWidget::stopVideo(), rcTextAreaSettingWidget::valueChanged(), rcCheckboxSettingWidget::valueChanged(), rcTextLineSettingWidget::valueChanged(), rcRectSettingWidget::valueChanged(), rcFileChoiceSettingWidget::valueChanged(), rcFileSaveSettingWidget::valueChanged(), rcPlaybackSettingWidget::valueChanged(), and rcSpinboxSettingWidget::valueChanged().
 {
     emit updateSettings();
 }
void rcModelDomain::notifyState (rcExperimentState newState, bool immediateDispatch) virtual
Implements rcExperimentObserver.
Definition at line 227 of file rc_modeldomain.cpp.
References mEventQueueManager, newState(), rcCustomEventManager::postEvent(), and updateSettings().
 {
     if ( immediateDispatch ) {
         emit newState( state );
         emit updateSettings();
     } else {
             rcBaseStateEvent *ev = new rcBaseStateEvent (state);
             mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
     }
 }
void rcModelDomain::notifyStatus (const char * statusString) virtual
Implements rcExperimentObserver.
Definition at line 219 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
Referenced by rcModelProgress::progress(), requestOpen(), and requestSave().
 {
     rcBaseStatusEvent *ev = new rcBaseStatusEvent (QString( statusString ));
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyStatusInternal (const char * statusString)
Definition at line 1072 of file rc_modeldomain.cpp.
References updateStatus().
Referenced by customEvent(), requestClose(), and requestSave().
 {
     // Use status bar widget
     emit updateStatus( statusString );
 }
void rcModelDomain::notifyTime (const rcTimestamp & elapsedTime) virtual
Implements rcExperimentObserver.
Definition at line 248 of file rc_modeldomain.cpp.
References eNotifyTimeEvent, mDomain, mEventQueueManager, rcExperimentDomain::operatingOnLiveInput(), rcCustomEventManager::postEvent(), and rcCustomEventManager::queuedEvents().
Referenced by rcModelProgress::progress().
 {
     const int32 queued = mEventQueueManager.queuedEvents( eNotifyTimeEvent );
     // Drop time events during live camera input if they start
     // queuing up
     if ( queued > 1 ) {
         if (mDomain->operatingOnLiveInput ())
             return;
     }
     rcBaseTimeEvent *ev = new rcBaseTimeEvent (cTime);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
   }
void rcModelDomain::notifyTimelineRange (const rcTimestamp & start, const rcTimestamp & end) virtual
Implements rcExperimentObserver.
Definition at line 157 of file rc_modeldomain.cpp.
References updateTimelineRange().
Referenced by rcTimeline::keyRangeScaleEvent(), rcTimeline::mouseMoveEvent(), and rcTimeline::scrollRange().
 {
     emit updateTimelineRange( start, end );
 }
void rcModelDomain::notifyTimelineScale (rcResultScaleMode scale) virtual
Definition at line 164 of file rc_modeldomain.cpp.
References updateTimelineScale().
Referenced by rcTimeline::keyCameraEvent(), and rcTimeline::mouseMoveEvent().
 {
     emit updateTimelineScale( scale );
 }
void rcModelDomain::notifyUpdateDebugging (void)
Definition at line 184 of file rc_modeldomain.cpp.
References notifySettingChange(), and updateDebugging().
Referenced by rcTimeline::keyPressEvent().
 {
     emit updateDebugging();
     notifySettingChange();
 }
void rcModelDomain::notifyUpdateDisplay (void)
Definition at line 151 of file rc_modeldomain.cpp.
References updateDisplay().
Referenced by rcTrackManager::hiliteTracks(), rcScalarTrackWidget::mousePressEvent(), rcTrackManager::setHiliteTrack(), and rcTrackManager::setTrackPen().
 {
     emit updateDisplay();
 }
void rcModelDomain::notifyUpdateMonitor (void)
Definition at line 178 of file rc_modeldomain.cpp.
References updateMonitorDisplay().
Referenced by rcScalarTrackWidget::setEnabled(), and rcTrackGroupWidget::setEnabled().
 {
     emit updateMonitorDisplay();
 }
void rcModelDomain::notifyVideoRect (const rcRect & rect) virtual
Implements rcExperimentObserver.
Definition at line 368 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     rcBaseVideoRectEvent *ev = new rcBaseVideoRectEvent (rect);
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
void rcModelDomain::notifyWarning (const char * warnString) virtual
Implements rcExperimentObserver.
Definition at line 212 of file rc_modeldomain.cpp.
References mEventQueueManager, and rcCustomEventManager::postEvent().
 {
     rcBaseWarningEvent *ev = new rcBaseWarningEvent (QString( warningString ));
     mEventQueueManager.postEvent( dynamic_cast <QEvent *> (ev) );
 }
bool rcModelDomain::operatingOnLiveInput (void)
Definition at line 97 of file rc_modeldomain.cpp.
References mDomain, and rcExperimentDomain::operatingOnLiveInput().
Referenced by rcControlPanel::updateCursorTime(), rcControlPanel::updateElapsedTime(), and rcControlPanel::updateState().
 {
   return mDomain->operatingOnLiveInput ();
 }
rcPolygonGroupRef rcModelDomain::polys () inline
Definition at line 164 of file rc_modeldomain.h.
References mSelectPolygons.
Referenced by rcImageCanvasGL::drawCurrentFocus(), and rcImageCanvasGL::mouseReleaseEvent().
   {
     return mSelectPolygons;
   }
uint32 rcModelDomain::polysSize () const inline
Definition at line 169 of file rc_modeldomain.h.
References mSelectPolygons, and rcPolygonGroupRef::size().
Referenced by rcImageCanvasGL::mouseDoubleClickEvent().
   {
     return mSelectPolygons.size();
   }
int32 rcModelDomain::progCursorTimeEventCount () const virtual
Implements rcExperimentObserver.
Definition at line 273 of file rc_modeldomain.cpp.
References eNotifyCursorEvent, mEventQueueManager, and rcCustomEventManager::queuedEvents().
 {
   rcModelDomain* ptr = const_cast<rcModelDomain*>(this);
   return ptr->mEventQueueManager.queuedEvents( eNotifyCursorEvent );
 }
void rcModelDomain::requestClose (void) slot
Definition at line 644 of file rc_modeldomain.cpp.
References cAppName, eExperimentEmpty, eExperimentLocked, eExperimentNativeFormat, getExperimentState(), mDomain, rcExperimentDomain::newExperiment(), notifyStatusInternal(), requestSave(), and general_exception::what().
 {
     try
     {
         notifyStatusInternal( "Closing experiment..." );
         rcExperimentState state = getExperimentState();
         if ( state != eExperimentEmpty && state != eExperimentLocked ) {
             // No data has been saved, prompt user
             switch( QMessageBox::warning( 0, cAppName,
                                           "Do you want to save experiment data before closing?\n\n"
                                           "If you don't save, your data will be lost.",
                                           "&Don't Save", "Cancel", "&Save",
                                           2, 1 ) ) {
                 case 0: // Don't Save clicked or Alt+D pressed
                     mDomain->newExperiment();
                     break;
                 case 1: // Cancel clicked or Alt+C pressed or Escape pressed
                     // Do nothing
                     break;
                 case 2: // Save clicked or Alt+S pressed
                     requestSave( eExperimentNativeFormat );
                     if ( getExperimentState() == eExperimentLocked )
                         mDomain->newExperiment();
                     break;
             }
         } else {
             QApplication::setOverrideCursor( Qt::waitCursor );
             mDomain->newExperiment();
             QApplication::restoreOverrideCursor();
         }
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestImageImport (void) slot
Definition at line 815 of file rc_modeldomain.cpp.
References imageImport(), and vl().
 {
     if ( vl() )
         emit imageImport();
 }
void rcModelDomain::requestInputSource (int i) slot
Definition at line 859 of file rc_modeldomain.cpp.
References updateInputSource().
Referenced by rcRadioChoiceSettingWidget::settingChanged(), and rcMenuChoiceSettingWidget::settingChanged().
 {
     emit updateInputSource( i );
 }
void rcModelDomain::requestMovieImport (void) slot
Definition at line 827 of file rc_modeldomain.cpp.
References mDomain, movieImport(), rcExperimentDomain::notifyMovieImport(), and vl().
 {
     if ( vl() ) {
         emit movieImport();
         // Notify domain so that experiment title can be updated with movie name
         mDomain->notifyMovieImport();
     }
 }
void rcModelDomain::requestMovieSave (void) slot
Definition at line 845 of file rc_modeldomain.cpp.
References eResultScaleCurrentMinToMax, movieSave(), updateCameraState(), updateMonitorScale(), updateTimelineScale(), and vl().
 {
     if ( vl() ) {
          // Scale monitor to fit
         emit updateMonitorScale( -1.0 );
         // Change timeline mode
         emit updateTimelineScale( eResultScaleCurrentMinToMax );
         // Start saving capture to disk
         emit movieSave();
         // Camerate state change
         emit updateCameraState( true, true );
     }
 }
void rcModelDomain::requestNew (void) slot
Definition at line 460 of file rc_modeldomain.cpp.
References cAppName, eExperimentEmpty, eExperimentLocked, eExperimentNativeFormat, getExperimentState(), mDomain, rcExperimentDomain::newExperiment(), requestSave(), and general_exception::what().
 {
     try
     {
         rcExperimentState state = getExperimentState();
         if ( state != eExperimentEmpty && state != eExperimentLocked ) {
             // No data has been saved, prompt user
             switch( QMessageBox::warning( 0, cAppName,
                                           "Do you want to save experiment data before starting a new experiment?\n\n"
                                           "If you don't save, your data will be lost.",
                                           "&Don't Save", "Cancel", "&Save",
                                           2, 1 ) ) {
                 case 0: // Don't Save clicked or Alt+D pressed
                     mDomain->newExperiment();
                     break;
                 case 1: // Cancel clicked or Alt+C pressed or Escape pressed
                     // Do nothing
                     break;
                 case 2: // Save clicked or Alt+S pressed
                     requestSave( eExperimentNativeFormat );
                     if ( getExperimentState() == eExperimentLocked )
                         mDomain->newExperiment();
                     break;
             }
         } else
             mDomain->newExperiment();
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestNewApp (void) slot
Definition at line 495 of file rc_modeldomain.cpp.
 {
     // TODO: we should use multiple document window architecture
     QString cmd;
     const char* appName = qApp->argv()[0];
     // Background task
     cmd.sprintf("%s -psn &", appName );
     // Launch a new application instance
     system( cmd.latin1() );
 }
void rcModelDomain::requestOpen (rcExperimentImportMode mode) slot
Definition at line 509 of file rc_modeldomain.cpp.
References cAppName, countLines(), eExperimentEmpty, eExperimentImportAll, eExperimentImportAllData, eExperimentImportAllSettings, eExperimentImportExperimentSettings, eExperimentLocked, eExperimentNativeFormat, rcXMLParser::elementTree(), rcXMLErrorHandler::errorString(), rcXMLErrorHandler::fatalErrors(), rcPersistenceManager::fileFormatImportCaption(), rcPersistenceManager::fileFormatImportFilter(), getExperimentState(), rcPersistenceManagerFactory::getPersistenceManager(), rcExperimentDomain::loadExperiment(), mDomain, notifyStatus(), null, rcModelProgress::progress(), QStrFrcStr, requestSave(), rcPersistenceManager::setImportDirectory(), vl(), and general_exception::what().
Referenced by rcMenuBar::doOpen(), and rcMenuBar::doOpenSettings().
 {
     try
     {
         if ( !vl() )
             return;
         notifyStatus( "Loading experiment data..." );
         rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
         rcExperimentFileFormat format =  eExperimentNativeFormat;
         // First, prompt for unsaved data from current experiment
         rcExperimentState state = getExperimentState();
         if ( state != eExperimentEmpty && state != eExperimentLocked ) {
             // No data has been saved, prompt user
             switch( QMessageBox::warning( 0, cAppName,
                                           "Do you want to save experiment data before opening a new experiment?\n\n"
                                           "If you don't save, your data will be lost.",
                                           "&Don't Save", "Cancel", "&Save",
                                           2, 1 ) ) {
                 case 0: // Don't Save clicked or Alt+D pressed
                     break;
                 case 1: // Cancel clicked or Alt+C pressed or Escape pressed
                     // Do nothing
                     return;
                     break;
                 case 2: // Save clicked or Alt+S pressed
                     requestSave( format );
                     break;
             }
         }
         // TODO: query (some of) these from engine settings
         QString caption = QStrFrcStr (persistenceManager->fileFormatImportCaption( format ));
         switch ( mode ) {
             case eExperimentImportAllSettings:
                 caption += " Settings";
                 break;
             case eExperimentImportExperimentSettings:
                 caption += " Template";
                 break;
             case eExperimentImportAllData:
                 caption += " Data";
                 break;
             case eExperimentImportAll:
             default:
                 break;
         }
         QString filter = QStrFrcStr (persistenceManager->fileFormatImportFilter( eExperimentNativeFormat ));
         // Ready to choose a file to open
         QString s = Q3FileDialog::getOpenFileName(
             "Untitled",
             filter,
             0,
             caption,
             caption );
         if (s != QString::null)
         {
             rcModelProgress prepareProgress( this, "Preparing to load experiment data...%.2f%% complete", 1.0, qApp );
             rcModelProgress loadProgress( this, "Loading experiment data...%.2f%% complete", 2.5, qApp );
             prepareProgress.progress( 30.0 );
             // Import from file to XML tree
             QApplication::setOverrideCursor(Qt::waitCursor );
             // Determine import directory
             int idx = s.findRev( '/' );
             if ( idx != -1 ) {
                 QString dir = s.left( idx + 1 );
                 std::string d( dir.latin1() );
                 // Set import directory so that engine can access it
                 persistenceManager->setImportDirectory( d );
             }
             // Input file
             QFile xmlFile( s );
             // Special Reify handlers
             rcXMLErrorHandler errorHandler( s );
             rcXMLParser parser( mode, countLines( xmlFile ),
                                 &loadProgress, &errorHandler );
             prepareProgress.progress( 60.0 );
             // Setup parser
             QXmlInputSource source( &xmlFile );
             QXmlSimpleReader reader;
             reader.setContentHandler( &parser );
             reader.setErrorHandler( &errorHandler );
             prepareProgress.progress( 100.0 );
             // Parse input file
             reader.parse( source );
             qApp->processEvents( QEventLoop::ExcludeUserInputEvents, 10 );
             QApplication::restoreOverrideCursor();
             if ( errorHandler.fatalErrors() > 0 ) {
                 // Fatal errors, do not import
                 QString message = QString( "Experiment loading aborted: %1 fatal error(s):\n\n%2\n" )
                     .arg( errorHandler.fatalErrors() )
                     .arg( errorHandler.errorString() );
                 // Display error dialog
                 QMessageBox::critical( 0 , cAppName , message , 1 , 0 );
             } else {
                 // Import from tree to experiment
                 rcModelProgress treeIndicator( this, "Processing experiment data...%.2f%% complete",
                                                2.5, qApp, true );
                 notifyStatus( "Processing experiment data..." );
                 QApplication::setOverrideCursor( Qt::waitCursor );
                 qApp->processEvents(QEventLoop::ExcludeUserInputEvents, 10 );
                 int errors = mDomain->loadExperiment( s.latin1(), parser.elementTree(), mode, &treeIndicator );
                 QApplication::restoreOverrideCursor();
                 if ( errors > 0 ) {
                     // Errors during import, display warning
                     QString message = QString( "Experiment loading aborted: %1 fatal error(s) during XML tree import.\n\nExperiment data file may contain unsupported elements or it may be corrupted.\n" )
                         .arg( errors );
                     // Display error dialog
                     QMessageBox::critical( 0, cAppName, message, 1, 0 );
                 }
             }
         }
         notifyStatus( "Ready" );
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestProcess (void) slot
Definition at line 415 of file rc_modeldomain.cpp.
References cAppName, mDomain, rcExperimentDomain::processExperiment(), vl(), and general_exception::what().
 {
     try
     {
         if ( vl() )
             mDomain->processExperiment();
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestSave (rcExperimentFileFormat format) slot
Definition at line 699 of file rc_modeldomain.cpp.
References cAppName, eExperimentCSVFormat, eExperimentMolDevSTKFormat, eExperimentNativeFormat, eExperimentNativeMovieFormat, eExperimentQuickTimeMovieFormat, rcPersistenceManager::fileFormatExportCaption(), rcPersistenceManager::fileFormatExportExtension(), rcPersistenceManager::fileFormatExportFilter(), rcExperimentAttributes::fileName, rcExperimentDomain::getExperimentAttributes(), rcPersistenceManagerFactory::getPersistenceManager(), rcExperimentAttributes::inputName, mDomain, notifySettingChange(), notifyStatus(), notifyStatusInternal(), null, processExtension(), QStrFrcStr, rmAssert, rcExperimentDomain::saveExperiment(), rcExperimentAttributes::title, and general_exception::what().
Referenced by rcMainWindow::closeEvent(), rcMenuBar::doExport(), rcMenuBar::doExportMovie(), rcMenuBar::doExportNativeMovie(), rcMenuBar::doSave(), requestClose(), requestNew(), and requestOpen().
 {
     try
     {
         notifyStatusInternal( "Saving experiment data..." );
         rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
         rcExperimentAttributes attr =  mDomain->getExperimentAttributes();
         QString defaultName;
     if ( !attr.inputName.empty() )
       defaultName = attr.inputName.c_str();
         else if ( !attr.fileName.empty() )
             defaultName = attr.fileName.c_str();
         else if (! attr.title.empty() ) {
             defaultName = attr.title.c_str();
             // We need to replace slashes with something else
             defaultName.replace( QChar('/'), "-" );
         }
         QString filter = QStrFrcStr (persistenceManager->fileFormatExportFilter( format ));
         QString ext = QStrFrcStr (persistenceManager->fileFormatExportExtension( format ));
         QString caption = QStrFrcStr (persistenceManager->fileFormatExportCaption( format ));
         QString widgetName;
         QString errorProlog;
         // Native file format extension
         QString nativeExt = QStrFrcStr (persistenceManager->fileFormatExportExtension( eExperimentNativeFormat ));
         std::string progressMessage( "Saving experiment data...%.2f%% complete" );
         switch ( format ) {
             case eExperimentCSVFormat:
                 widgetName = QString( "export-dialog" );
                 progressMessage = std::string( "Exporting experiment data...%.2f%% complete" );
                 processExtension( defaultName, ext, nativeExt );
             case eExperimentNativeFormat:
                 widgetName = QString( "save-dialog" );
                 progressMessage = std::string( "Saving experiment data...%.2f%% complete" );
                 break;
             case eExperimentMolDevSTKFormat :
                 widgetName = QString( "save-dialog" );
                 progressMessage = std::string( "Saving stk data...%.2f%% complete" );
                 processExtension( defaultName, ext, nativeExt );
                 break;
             case eExperimentQuickTimeMovieFormat:
                 widgetName = QString( "export-dialog" );
                 progressMessage = std::string( "Exporting image data...%.2f%% complete" );
                 processExtension( defaultName, ext, nativeExt );
                 break;
             case eExperimentNativeMovieFormat:
                 widgetName = QString( "save-dialog" );
                 progressMessage = std::string( "Saving image data...%.2f%% complete" );
                 processExtension( defaultName, ext, nativeExt );
                 break;
             default:
                 rmAssert( 0 );
                 break;
         };
         QString fileName = Q3FileDialog::getSaveFileName(
             defaultName,
             filter,
             0,
             widgetName,
             caption,
             &filter,
             true );
         // If user canceled, the fileName will be QString::null
         if (fileName == QString::null) {
             notifyStatusInternal( "Ready" );
             return;
         }
         // Add extension if necessary
         if (!fileName.endsWith( ext ))
             fileName += ext;
         // Warn if file already exists
         if (QFile::exists( fileName ))
         {
             if (QMessageBox::warning( 0 , cAppName , "File already exists: overwrite?" ,
                                       QMessageBox::Ok , QMessageBox::Cancel ) == QMessageBox::Cancel) {
                 notifyStatusInternal( "Ready" );
                 return;
             }
         }
         // Export the experiment data.
         QApplication::setOverrideCursor(Qt::waitCursor );
         rcModelProgress progressIndicator( this, progressMessage, 2.5, qApp );
         int err = mDomain->saveExperiment( fileName.latin1(), format, &progressIndicator );
         QApplication::restoreOverrideCursor();
         if ( err ) {
             // Error during export/save!
             QString error( caption );
             error += " error: ";
             error += strerror( err );
             QMessageBox::critical( 0 , cAppName , error , 1 , 0 );
         }
         // Experiment file name may have changed, do a notification
         notifySettingChange();
         notifyStatus( "Ready" );
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestStart (void) slot
Definition at line 387 of file rc_modeldomain.cpp.
References cAppName, mDomain, rcExperimentDomain::startExperiment(), vl(), and general_exception::what().
 {
     try
     {
         if ( vl() )
             mDomain->startExperiment();
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestSTKImport (void) slot
Definition at line 836 of file rc_modeldomain.cpp.
References mDomain, rcExperimentDomain::notifyMovieImport(), stkImport(), and vl().
 {
     if ( vl() ) {
         emit stkImport();
         // Notify domain so that experiment title can be updated with STK name
         mDomain->notifyMovieImport();
     }
 }
void rcModelDomain::requestStop (void) slot
Definition at line 400 of file rc_modeldomain.cpp.
References cAppName, rcExperimentDomain::getExperimentAttributes(), mDomain, rcExperimentDomain::operatingOnLiveInput(), rcExperimentDomain::stopExperiment(), updateCameraState(), and general_exception::what().
 {
     try
     {
         mDomain->stopExperiment();
         // Camerate state change, no more storage
         rcExperimentAttributes attr = mDomain->getExperimentAttributes();
         emit updateCameraState(mDomain->operatingOnLiveInput(), false );
     }
     catch (general_exception& x)
     {
         QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::requestTifDirImport (void) slot
Definition at line 821 of file rc_modeldomain.cpp.
References tifDirImport(), and vl().
 {
     if ( vl() )
         emit tifDirImport();
 }
void rcModelDomain::requestTrackingPause (void) slot
Definition at line 429 of file rc_modeldomain.cpp.
References cAppName, mDomain, rcExperimentDomain::pauseTrackingExperiment(), vl(), and general_exception::what().
 {
     try
     {
       if ( vl() )
     {
       mDomain->pauseTrackingExperiment();
     }
     }
     catch (general_exception& x)
     {
       QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
void rcModelDomain::rle (rcSecurityError status) private
Definition at line 1022 of file rc_modeldomain.cpp.
References cAppName, cLicenseFilePath, eSecurityErrorInvalidHost, rcLicenseManager::getErrorString(), rcLicenseManager::getHostId(), rcLicenseManager::getLicenseHost(), rcLicenseManager::hexifyString(), and mLicenseManager.
Referenced by vl().
 {
     // Get basic error message
     std::string errorString = rcLicenseManager::getErrorString( status );
     if ( status == eSecurityErrorInvalidHost ) {
         std::string host = rcLicenseManager::hexifyString( mLicenseManager.getHostId() );
         std::string licensedHost = rcLicenseManager::hexifyString( mLicenseManager.getLicenseHost() );
         // Display mismatching host ids
         errorString += "\nLicensed host is \"";
         errorString += licensedHost;
         errorString += "\", this host is \"";
         errorString += host;
         errorString += "\"";
     }
     // Concatenate license file name
     errorString += "\n\nLicense file: ";
     errorString += cLicenseFilePath;
     QMessageBox::critical( 0 , cAppName , errorString.c_str() , 1 , 0 );
 }
void rcModelDomain::setExperimentAttributes (const rcExperimentAttributes & attr) virtual
Definition at line 109 of file rc_modeldomain.cpp.
References mDomain, and rcExperimentDomain::setExperimentAttributes().
 {
      mDomain->setExperimentAttributes( attrs );
 }
void rcModelDomain::stkImport (void) signal
Definition at line 295 of file moc_rc_modeldomain.cpp.
Referenced by requestSTKImport().
 {
     QMetaObject::activate(this, &staticMetaObject, 16, 0);
 }
void rcModelDomain::stopTrackingPause (void) slot
Definition at line 445 of file rc_modeldomain.cpp.
References cAppName, rcExperimentDomain::doneSelecting(), mDomain, vl(), and general_exception::what().
 {
     try
     {
       if ( vl() )
     {
       mDomain->doneSelecting ();
     }
     }
     catch (general_exception& x)
     {
       QMessageBox::critical( 0 , cAppName , x.what() , 1 , 0 );
     }
 }
bool rcModelDomain::storingLiveInput (void)
Definition at line 102 of file rc_modeldomain.cpp.
References mDomain, and rcExperimentDomain::storingLiveInput().
Referenced by rcControlPanel::updateCursorTime().
 {
   return mDomain->storingLiveInput ();
 }
void rcModelDomain::tifDirImport (void) signal
Definition at line 283 of file moc_rc_modeldomain.cpp.
Referenced by requestTifDirImport().
 {
     QMetaObject::activate(this, &staticMetaObject, 14, 0);
 }
void rcModelDomain::timerTick (void) slot
Definition at line 871 of file rc_modeldomain.cpp.
References elapsedTime(), endl(), rcExperimentDomain::getExperimentLength(), mDomain, and rcTimestamp::secs().
 {
     rcTimestamp time = mDomain->getExperimentLength();
 #ifdef DEBUG_LOG
     cout << "timerTick " << time.secs() << endl;
 #endif
     emit elapsedTime( time );
 }
void rcModelDomain::updateAnalysisRect (const rcRect & rect) signal
Definition at line 229 of file moc_rc_modeldomain.cpp.
Referenced by customEvent().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 6, _a);
 }
void rcModelDomain::updateAnalysisRectRotation (const rcAffineRectangle & affine) signal
Definition at line 236 of file moc_rc_modeldomain.cpp.
Referenced by customEvent().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 7, _a);
 }
void rcModelDomain::updateCameraState (bool liveCamera, bool liveStorage) signal
Definition at line 334 of file moc_rc_modeldomain.cpp.
Referenced by requestMovieSave(), and requestStop().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
     QMetaObject::activate(this, &staticMetaObject, 22, _a);
 }
void rcModelDomain::updateDebugging () signal
Definition at line 341 of file moc_rc_modeldomain.cpp.
Referenced by notifyUpdateDebugging().
 {
     QMetaObject::activate(this, &staticMetaObject, 23, 0);
 }
void rcModelDomain::updateDisplay (const rcWindow * image) signal
Definition at line 209 of file moc_rc_modeldomain.cpp.
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 3, _a);
 }
void rcModelDomain::updateDisplay (const rcVisualGraphicsCollection * graphics) signal
Definition at line 216 of file moc_rc_modeldomain.cpp.
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 4, _a);
 }
void rcModelDomain::updateDisplay (void) signal
Definition at line 264 of file moc_rc_modeldomain.cpp.
Referenced by customEvent(), and notifyUpdateDisplay().
 {
     QMetaObject::activate(this, &staticMetaObject, 11, 0);
 }
void rcModelDomain::updateInputSource (int i) signal
Definition at line 307 of file moc_rc_modeldomain.cpp.
Referenced by requestInputSource().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 18, _a);
 }
void rcModelDomain::updateMonitorDisplay () signal
Definition at line 321 of file moc_rc_modeldomain.cpp.
Referenced by notifyUpdateMonitor().
 {
     QMetaObject::activate(this, &staticMetaObject, 20, 0);
 }
void rcModelDomain::updateMonitorScale (double scaleFactor) signal
Definition at line 314 of file moc_rc_modeldomain.cpp.
Referenced by requestMovieSave().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 19, _a);
 }
void rcModelDomain::updateMultiplier (double multiplier) signal
Definition at line 257 of file moc_rc_modeldomain.cpp.
Referenced by customEvent().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 10, _a);
 }
void rcModelDomain::updateSelectionState (bool b) signal
Definition at line 347 of file moc_rc_modeldomain.cpp.
Referenced by notifySelectionState().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 24, _a);
 }
void rcModelDomain::updateSettings (void) signal
Definition at line 223 of file moc_rc_modeldomain.cpp.
Referenced by customEvent(), notifySettingChange(), and notifyState().
 {
     QMetaObject::activate(this, &staticMetaObject, 5, 0);
 }
void rcModelDomain::updateStatus (const char * statusString) signal
Definition at line 270 of file moc_rc_modeldomain.cpp.
Referenced by notifyStatusInternal().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 12, _a);
 }
void rcModelDomain::updateTimelineRange (const rcTimestamp & start, const rcTimestamp & end) signal
Definition at line 243 of file moc_rc_modeldomain.cpp.
Referenced by customEvent(), and notifyTimelineRange().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
     QMetaObject::activate(this, &staticMetaObject, 8, _a);
 }
void rcModelDomain::updateTimelineScale (rcResultScaleMode scale) signal
Definition at line 250 of file moc_rc_modeldomain.cpp.
Referenced by notifyTimelineScale(), and requestMovieSave().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 9, _a);
 }
void rcModelDomain::updateVideoRect (const rcRect & rect) signal
Definition at line 327 of file moc_rc_modeldomain.cpp.
Referenced by customEvent().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 21, _a);
 }
bool rcModelDomain::vl () private
Definition at line 1045 of file rc_modeldomain.cpp.
References eSecurityErrorOK, mLicenseManager, rle(), rcLicenseManager::validHost(), and rcLicenseManager::validTime().
Referenced by requestImageImport(), requestMovieImport(), requestMovieSave(), requestOpen(), requestProcess(), requestStart(), requestSTKImport(), requestTifDirImport(), requestTrackingPause(), and stopTrackingPause().
 {
     bool valid = true; // @Danger: takes this out
     // Check host validity
     rcSecurityError status = mLicenseManager.validHost();
     if ( status == eSecurityErrorOK ) {
         // Check expiration time
         status = mLicenseManager.validTime();
         if ( status == eSecurityErrorOK ) {
             // Lucky, everything is valid
             valid = true;
         } else {
             // Invalid time
             rle( status );
         }
     } else {
         // Invalid host
         rle( status );
     }
     return valid;
 }
Member Data Documentation
rcTimestamp rcModelDomain::mCursorTime private
Definition at line 253 of file rc_modeldomain.h.
Referenced by getCursorTime(), and notifyCursorTime().
rcExperimentDomain* rcModelDomain::mDomain private
Definition at line 250 of file rc_modeldomain.h.
Referenced by getExperiment(), getExperimentAttributes(), getExperimentLength(), getExperimentStart(), getExperimentState(), notifyCursorTime(), notifyPolys(), notifyTime(), operatingOnLiveInput(), rcModelDomain(), requestClose(), requestMovieImport(), requestNew(), requestOpen(), requestProcess(), requestSave(), requestStart(), requestSTKImport(), requestStop(), requestTrackingPause(), setExperimentAttributes(), stopTrackingPause(), storingLiveInput(), timerTick(), and ~rcModelDomain().
rcCustomEventManager rcModelDomain::mEventQueueManager private
Definition at line 252 of file rc_modeldomain.h.
Referenced by customEvent(), notifyAnalysisRect(), notifyAnalysisRectRotation(), notifyBlitData(), notifyBlitGraphics(), notifyEngineTimelineRange(), notifyError(), notifyExperimentChange(), notifyMultiplier(), notifyProgCursorTime(), notifyState(), notifyStatus(), notifyTime(), notifyVideoRect(), notifyWarning(), and progCursorTimeEventCount().
rcLicenseManager rcModelDomain::mLicenseManager private
Definition at line 251 of file rc_modeldomain.h.
Referenced by getLicenseExpirationTime(), rle(), and vl().
rcPolygonGroupRef rcModelDomain::mSelectPolygons private
Definition at line 254 of file rc_modeldomain.h.
Referenced by dumpPolys(), getPolys(), notifyPolys(), polys(), polysSize(), and rcModelDomain().
The documentation for this class was generated from the following files:
include/visUI/rc_modeldomain.h
src/visible/moc/moc_rc_modeldomain.cpp
src/visible/qt/rc_modeldomain.cpp