Visible: rcMuscleSegmenter Class Reference
rcMuscleSegmenter Class Reference
#include <include/analysis/rc_musclesegment.h>
Classes
struct polyInterInfo
Public Types
enum errorCode { cInvalidPeriod = -1, cWindowTooSmall = -2 }
enum rejectionCode {
cRejCodeSize = 0, cRejCodeAR, cRejCodeEdge, cRejCodeActivity,
cRejCodeCount
}
Public Member Functions
rcMuscleSegmenter (rcGenMovieFile *debugMovie=0)
int32 extendedMuscleCellIndex () const
float framesPerPeriod () const
int32 segment (const vector< rcWindow > &movie, int32 startFrame, int32 endFrame, bool fluo=false)
void filterBySize (double minArea)
void filterByAR (double minAspectRatio)
int32 filterByActivity (double minPct, const vector< rcWindow > &movie, int32 startFrame, int32 endFrame, float maxFramesPerPeriod, float framesPerPeriod=-1.0)
void filterAtEdge (int32 minDelta)
void getCells (vector< rcPolygon > &cells) const
void getRejects (vector< rcPolygon > &rejects) const
void rejectRange (int32 &startIndex, int32 &endIndex, rejectionCode reason, int32 instance=1) const
void hackInsertSegmentedImages (rcWindow &segSdImg, rcWindow &segFreqImg, rcWindow &emiImg)
Private Types
typedef struct
rcMuscleSegmenter::polyInterInfo polyInterInfo
Private Member Functions
int32 getEMI (const vector< rcWindow > &movie, int32 startFrame, int32 endFrame)
void genPolygons (const rcWindow &segImg, const int32 minDim, vector< rcPolygon > &p, const rcIPair delta) const
void mergePolygons (vector< rcPolygon > &poly, vector< rcPolygon > &polyCH, vector< rcPolygon > &mergedCH, vector< rcIRect > &mergedCHR, vector< polyInterInfo > &mergedInfo) const
void accumPolygons (vector< rcPolygon > &fg, vector< rcIRect > &fgR, vector< rcPolygon > &freq, vector< rcIRect > &freqR, vector< polyInterInfo > &accumInfo) const
void genSpatialSegmentation (const vector< rcWindow > &movie, int32 startFrame, int32 endFrame, int32 &emi, rcWindow &segSdImg)
int32 genFrequencySegmentation (const vector< rcWindow > &movie, int32 startFrame, int32 endFrame, int32 emi, float maxFramesPerPeriod, float framesPerPeriod, rcWindow &segFreqImg)
void debugWrite (const rcWindow &frame) const
Private Attributes
rcWindow _segSdImg
rcWindow _segFreqImg
rcWindow _emiImg
rcWindow _segSdImgDbg
rcWindow _emiImgDbg
rcGenMovieFile * _debugMovie
rcIPair _dSize
int32 _emi
float _framesPerPeriod
vector< rcPolygon > _cells
vector< rcPolygon > _activeRegions
vector< rcPolygon > _rejects
vector< rcIRect > _cellsR
vector< polyInterInfo > _cellsInfo
vector< int32 > _rejectIndex
vector< rejectionCode > _rejectReason
rcIPair _segSdImgSz
Detailed Description
Definition at line 23 of file rc_musclesegment.h.
Member Typedef Documentation
typedef struct rcMuscleSegmenter::polyInterInfo rcMuscleSegmenter::polyInterInfo private
Member Enumeration Documentation
enum rcMuscleSegmenter::errorCode
Enumerator
cInvalidPeriod
cWindowTooSmall
Definition at line 26 of file rc_musclesegment.h.
                  {
     cInvalidPeriod = -1,
     cWindowTooSmall = -2
   };
enum rcMuscleSegmenter::rejectionCode
Enumerator
cRejCodeSize
cRejCodeAR
cRejCodeEdge
cRejCodeActivity
cRejCodeCount
Definition at line 31 of file rc_musclesegment.h.
                      {
     cRejCodeSize = 0,
     cRejCodeAR,
     cRejCodeEdge,
     cRejCodeActivity,
     cRejCodeCount
   };
Constructor & Destructor Documentation
rcMuscleSegmenter::rcMuscleSegmenter (rcGenMovieFile * debugMovie = 0)
Definition at line 37 of file rc_musclesegment.cpp.
   : _debugMovie(debugMovie), _dSize(0, 0), _emi(-1), _framesPerPeriod(-1.0)
 {
 }
Member Function Documentation
void rcMuscleSegmenter::accumPolygons (vector< rcPolygon > & fg, vector< rcIRect > & fgR, vector< rcPolygon > & freq, vector< rcIRect > & freqR, vector< polyInterInfo > & accumInfo) const private
Definition at line 192 of file rc_musclesegment.cpp.
References rmAssert.
Referenced by filterByActivity().
 {
   const uint32 fgCnt = fg.size();
   rmAssert(fgCnt == fgR.size());
   rmAssert(freq.size() == freqR.size());
   accumInfo.clear();
   accumInfo.resize(fgCnt);
   for (uint32 fi = 0; fi < fgCnt; fi++)
     accumInfo[fi].area = 0.0;
   for (uint32 freqi = 0; freqi < freq.size(); freqi++) {
     for (uint32 fi = 0; fi < fgCnt; fi++) {
       if (fgR[fi].overlaps(freqR[freqi], true) &&
       fg[fi].intersects(freq[freqi])) {
     if (fg[fi].contains(freq[freqi])) {
       accumInfo[fi].polyInter.push_back(freq[freqi]);
       const double area = freq[freqi].area();
       accumInfo[fi].area += area;
       break;
     }
     else {
       accumInfo[fi].polyInter.push_back(rcPolygon());
       fg[fi].convexIntersection(freq[freqi],
                     accumInfo[fi].polyInter.back());
       const double area = accumInfo[fi].polyInter.back().area();
       accumInfo[fi].area += area;
     }
       }
     }
   }
 }
void rcMuscleSegmenter::debugWrite (const rcWindow & frame) const private
Definition at line 230 of file rc_musclesegment.cpp.
References _debugMovie, _dSize, rcGenMovieFile::addFrame(), rcWindow::copyPixelsFromWindow(), rmAssert, rcWindow::setAllPixels(), rcWindow::size(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), genFrequencySegmentation(), getCells(), and segment().
 {
   if(!_debugMovie)
     return;
   const rcIPair fSize = frame.size();
   if (_dSize == fSize) {
     _debugMovie->addFrame(frame);
     return;
   }
   if ((fSize.x() >= _dSize.x()) && (fSize.y() >= _dSize.y())) {
     const int32 xOff = (fSize.x() - _dSize.x())/2;
     const int32 yOff = (fSize.y() - _dSize.y())/2;
     rcWindow fWin(frame, xOff, yOff, _dSize.x(), _dSize.y());
     _debugMovie->addFrame(fWin);
     return;
   }
   rcWindow tImg(_dSize);
   tImg.setAllPixels(0);
   if ((fSize.x() <= _dSize.x()) && (fSize.y() <= _dSize.y())) {
     const int32 xOff  = (_dSize.x() - fSize.x())/2;
     const int32 yOff = (_dSize.y() - fSize.y())/2;
     rcWindow tWin(tImg, xOff, yOff, fSize.x(), fSize.y());
     tWin.copyPixelsFromWindow(frame);
     _debugMovie->addFrame(tImg);
     return;
   }
   int32 xOffF, yOffF, xOffT, yOffT, w, h;
   rcWindow fWin;
   if (fSize.x() > _dSize.x()) {
     rmAssert(_dSize.y() > fSize.y());
     xOffF = (fSize.x() - _dSize.x())/2;
     yOffF = 0;
     xOffT = 0;
     yOffT = (_dSize.y() - fSize.y())/2;
     w = _dSize.x();
     h = fSize.y();
   }
   else {
     rmAssert(_dSize.x() > fSize.x());
     rmAssert(fSize.y() > _dSize.y());
     xOffF = 0;
     yOffF = (fSize.y() - _dSize.y())/2;
     xOffT = (_dSize.x() - fSize.x())/2;
     yOffT = 0;
     w = fSize.x();
     h = _dSize.y();
   }
   fWin = rcWindow(frame, xOffF, yOffF, w, h);
   rcWindow tWin(tImg, xOffT, yOffT, w, h);
   tWin.copyPixelsFromWindow(frame);
   _debugMovie->addFrame(tImg);
 }
int32 rcMuscleSegmenter::extendedMuscleCellIndex () const inline
Definition at line 54 of file rc_musclesegment.h.
References _emi.
Referenced by rcEngineImpl::muscleTracker().
 { return _emi; }
void rcMuscleSegmenter::filterAtEdge (int32 minDelta)
Definition at line 771 of file rc_musclesegment.cpp.
References _cells, _cellsInfo, _cellsR, _debugMovie, _emiImgDbg, _rejectIndex, _rejectReason, _rejects, _segSdImgSz, color(), cRejCodeEdge, debugWrite(), rcWindow::height(), rcRectangle< T >::lr(), MSDBG1, MSDBG2, rcDrawPolygon(), rcRectangle< T >::ul(), rcWindow::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcEngineImpl::muscleTracker().
 {
   const rcIPair size = _segSdImgSz - rcIPair(1, 1);
   if (MSDBG1) printf("edge filter : img sz (%d, %d) min delta %d\n",
              size.x(), size.y(), minDelta);
   for (uint32 ci = 0; ci < _cells.size();) {
     const rcIRect bBox = _cells[ci].orthogonalEnclosingRect();
     const rcIPair ul = bBox.ul();
     const rcIPair lr = size - bBox.lr();
     if (MSDBG2) printf("ef @ %d: ul (%d, %d) lr (%d, %d) sz - lr (%d, %d)\n",
                ci, ul.x(), ul.y(), _cellsR[ci].lr().x(),
                _cellsR[ci].lr().y(), lr.x(), lr.y());
     if ((ul.x() < minDelta) || (ul.y() < minDelta) ||
     (lr.x() < minDelta) || (lr.y() < minDelta)) {
       _rejects.push_back(_cells[ci]);
       _cells[ci] = _cells.back();
       _cells.pop_back();
       _cellsR[ci] = _cellsR.back();
       _cellsR.pop_back();
       _cellsInfo[ci] = _cellsInfo.back();
       _cellsInfo.pop_back();
     }
     else
       ci++;
   }
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 color = 0xFF;
     const bool fill = true;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ci = 0; ci < _cells.size(); ci++)
       rcDrawPolygon(_cells[ci], scribble, color, fill);
     debugWrite(scribble);
   }
   _rejectIndex.push_back((int32)_rejects.size());
   _rejectReason.push_back(cRejCodeEdge);
   if (MSDBG1) printf("edge filtered count %d\n", (int)_cells.size());
 }
int32 rcMuscleSegmenter::filterByActivity (double minPct, const vector< rcWindow > & movie, int32 startFrame, int32 endFrame, float maxFramesPerPeriod, float framesPerPeriod = -1.0)
Definition at line 659 of file rc_musclesegment.cpp.
References _activeRegions, _cells, _cellsInfo, _cellsR, _debugMovie, _emi, _emiImgDbg, _framesPerPeriod, _rejectIndex, _rejectReason, _rejects, _segFreqImg, accumPolygons(), color(), rcWindow::copyPixelsFromWindow(), cRejCodeActivity, cWindowTooSmall, debugWrite(), framesPerPeriod(), genFrequencySegmentation(), genPolygons(), rcWindow::height(), rcWindow::isBound(), MSDBG1, MSDBG2, rcDrawPolygon(), rmAssert, rcWindow::setAllPixels(), and rcWindow::width().
Referenced by rcEngineImpl::muscleTracker().
 {
   rmAssert(endFrame > startFrame);
   rmAssert((int32)movie.size() >= endFrame);
   rmAssert((endFrame - startFrame) >= 2);
   rmAssert(_emi >= startFrame);
   rmAssert(_emi < endFrame);
   /* minWinDim of 10 may be overly large, but just wanted a value big
    * enough to keep window sizes from getting too small.
    */
   const int32 minWinDim = 10;
   if ((movie[0].width() < minWinDim) || (movie[0].height() < minWinDim))
     return cWindowTooSmall;
   rcWindow segFreqImg;
   bool hack = _segFreqImg.isBound();
   _framesPerPeriod = framesPerPeriod;
   if (hack)
     segFreqImg = _segFreqImg;
   else {
     int32 retVal = genFrequencySegmentation(movie, startFrame, endFrame,
                           _emi, maxFramesPerPeriod,
                           _framesPerPeriod, segFreqImg);
     if (retVal < 0)
       return retVal;
   }
   const int32 minDim = 4;
   genPolygons(segFreqImg, minDim, _activeRegions, rcIPair(1, 1));
   if (_debugMovie) {
     debugWrite(segFreqImg);
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 bgColor = 0;
     scribble.setAllPixels(bgColor);
     rcWindow scribWin(scribble, 1, 1, segFreqImg.width(), segFreqImg.height());
     const bool fill = true;
     const uint8 segColor = 0x7F;
     scribWin.copyPixelsFromWindow(segFreqImg);
     for (uint32 ai = 0; ai < _activeRegions.size(); ai++)
       rcDrawPolygon(_activeRegions[ai], scribble, segColor, fill);
     debugWrite(scribble);
     const uint8 imgColor = 0xFF;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ai = 0; ai < _activeRegions.size(); ai++)
       rcDrawPolygon(_activeRegions[ai], scribble, imgColor, fill);
     debugWrite(scribble);
   }
   vector<rcIRect> activeRegionsR(_activeRegions.size());
   for (uint32 ai = 0; ai < _activeRegions.size(); ai++)
     activeRegionsR[ai] = _activeRegions[ai].orthogonalEnclosingRect();
   vector<uint32> ciToAiMap(_cells.size());
   for (uint32 ci = 0; ci < _cells.size(); ci++)
     ciToAiMap[ci] = ci;
   vector<polyInterInfo> activeInfo;
   accumPolygons(_cells, _cellsR, _activeRegions, activeRegionsR, activeInfo);
   rmAssert(activeInfo.size() == _cells.size());
   for (uint32 ci = 0; ci < _cells.size(); ) {
     uint32 ai = ciToAiMap[ci];
     if (MSDBG2) printf("%d: ACTIVE %f FG %f FAR %f\n", ai,
                activeInfo[ai].area, _cellsInfo[ci].area,
                activeInfo[ai].area/_cellsInfo[ci].area);
     if (activeInfo[ai].area/_cellsInfo[ci].area < minPct) {
       ai = _cells.size() - 1;
       ciToAiMap[ci] = ai;
       _rejects.push_back(_cells[ci]);
       _cells[ci] = _cells[ai];
       _cells.pop_back();
       _cellsR[ci] = _cellsR[ai];
       _cellsR.pop_back();
       _cellsInfo[ci] = _cellsInfo[ai];
       _cellsInfo.pop_back();
     }
     else
       ci++;
   }
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 color = 0xFF;
     const bool fill = true;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ci = 0; ci < _cells.size(); ci++)
       rcDrawPolygon(_cells[ci], scribble, color, fill);
     debugWrite(scribble);
   }
   _rejectIndex.push_back((int32)_rejects.size());
   _rejectReason.push_back(cRejCodeActivity);
   if (MSDBG1) printf("activity filtered count %d\n", (int)_cells.size());
   return 0;
 }
void rcMuscleSegmenter::filterByAR (double minAspectRatio)
Definition at line 619 of file rc_musclesegment.cpp.
References _cells, _cellsInfo, _cellsR, _debugMovie, _emiImgDbg, _rejectIndex, _rejectReason, _rejects, rcAffineRectangle::cannonicalSize(), color(), cRejCodeAR, debugWrite(), rcWindow::height(), MSDBG1, MSDBG2, rcDrawPolygon(), rcWindow::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcEngineImpl::muscleTracker().
 {
   for (uint32 ci = 0; ci < _cells.size();) {
     rcAffineRectangle aRect = _cells[ci].minimumAreaEnclosingRect();
     rcIPair sz = aRect.cannonicalSize();
     int32 lSide = (sz.y() > sz.x()) ? sz.y() : sz.x();
     int32 sSide = (sz.y() > sz.x()) ? sz.x() : sz.y();
     double ar = (double)lSide/(double)sSide;
     if (MSDBG2) printf("%d: Long x Short %d x %d AR: %f\n", ci, lSide, sSide, ar);
     if (ar < minAspectRatio) {
       _rejects.push_back(_cells[ci]);
       _cells[ci] = _cells.back();
       _cells.pop_back();
       _cellsR[ci] = _cellsR.back();
       _cellsR.pop_back();
       _cellsInfo[ci] = _cellsInfo.back();
       _cellsInfo.pop_back();
     }
     else
       ci++;
   }
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 color = 0xFF;
     const bool fill = true;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ci = 0; ci < _cells.size(); ci++)
       rcDrawPolygon(_cells[ci], scribble, color, fill);
     debugWrite(scribble);
   }
   _rejectIndex.push_back((int32)_rejects.size());
   _rejectReason.push_back(cRejCodeAR);
   if (MSDBG1) printf("ar filtered count %d\n", (int)_cells.size());
 }
void rcMuscleSegmenter::filterBySize (double minArea)
Definition at line 553 of file rc_musclesegment.cpp.
References _cells, _cellsInfo, _cellsR, _debugMovie, _emiImgDbg, _rejectIndex, _rejectReason, _rejects, color(), cRejCodeSize, debugWrite(), rcWindow::height(), MSDBG1, rcDrawPolygon(), rfMedian(), and rcWindow::width().
Referenced by rcEngineImpl::muscleTracker().
 {
   // Remove too small
   for (uint32 ci = 0; ci < _cells.size();) {
     if (_cells[ci].area() < minArea) {
       _rejects.push_back(_cells[ci]);
       _cells[ci] = _cells.back();
       _cells.pop_back();
       _cellsR[ci] = _cellsR.back();
       _cellsR.pop_back();
       _cellsInfo[ci] = _cellsInfo.back();
       _cellsInfo.pop_back();
     }
     else
       ci++;
   }
   // Now find the median of the remaining
   if (_cells.size() > 2)
     {
       vector<double> sizes (_cells.size());
       for (uint32 ci = 0; ci < _cells.size(); ci++)
     {
       sizes[ci] = _cells[ci].area();
     }
       double cmed = rfMedian (sizes);
       cmed *= 1.5;
       // Get rid of anything 1.5 times the size of the median cell
       // ToDo: this is should be a parameter
       for (uint32 ci = 0; ci < _cells.size();) {
     double csize = _cells[ci].area();
     if (csize > cmed) {
       _rejects.push_back(_cells[ci]);
       _cells[ci] = _cells.back();
       _cells.pop_back();
       _cellsR[ci] = _cellsR.back();
       _cellsR.pop_back();
       _cellsInfo[ci] = _cellsInfo.back();
       _cellsInfo.pop_back();
     }
     else
       ci++;
       }
     }
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 color = 0xFF;
     const bool fill = true;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ci = 0; ci < _cells.size(); ci++)
       rcDrawPolygon(_cells[ci], scribble, color, fill);
     debugWrite(scribble);
   }
   _rejectIndex.push_back((int32)_rejects.size());
   _rejectReason.push_back(cRejCodeSize);
   if (MSDBG1) printf("size filtered count %d\n", (int)_cells.size());
 }
float rcMuscleSegmenter::framesPerPeriod () const inline
Definition at line 63 of file rc_musclesegment.h.
References _framesPerPeriod.
Referenced by filterByActivity(), genFrequencySegmentation(), and rcEngineImpl::muscleTracker().
 { return _framesPerPeriod; }
int32 rcMuscleSegmenter::genFrequencySegmentation (const vector< rcWindow > & movie, int32 startFrame, int32 endFrame, int32 emi, float maxFramesPerPeriod, float framesPerPeriod, rcWindow & segFreqImg) private
Definition at line 358 of file rc_musclesegment.cpp.
References _cells, _framesPerPeriod, binarizeFloatWindow(), calcMusclePeriod(), cInvalidPeriod, debugWrite(), rcOptoKineticImage::eKineTypeDummy, framesPerPeriod(), rcOptoKineticImage::genFreqImg(), MSDBG1, rcOptoKineticImage::push(), rcFillPolygon(), rcPixel32, rmAssert, and rcWindow::setAllPixels().
Referenced by filterByActivity().
 {
   rmAssert(startFrame >= 0);
   rmAssert(endFrame < (int32)movie.size());
   rmAssert((endFrame - startFrame) >= 2);
   /* Use the following algorithm to segment images:
    *
    * 1) Calculate the number of frames per beat. This requires the
    *    passed in emi value to use as a starting point.
    *
    * 2) Generate a frequency image based on the frames per beat value
    *    calculated in step 1). The foreground pixels in the segmented
    *    frequency image serve as the candidate active muscle cell
    *    areas.
    */
   /* Step 1
    */
   if (framesPerPeriod <= 0.0)
     framesPerPeriod = calcMusclePeriod(movie, startFrame, endFrame,
                        emi, maxFramesPerPeriod);
   if (MSDBG1) printf("FRAMES PER PERIOD %f\n", framesPerPeriod);
   _framesPerPeriod = framesPerPeriod;
   if (framesPerPeriod == 0.0)
     return cInvalidPeriod;
   /* Step 2
    */
   const uint8 bg = 0, fg = 0xFF;
   rcWindow maskImg(movie[0].width(), movie[0].height());
   maskImg.setAllPixels(bg);
   for (uint32 ci = 0; ci < _cells.size(); ci++)
     rcFillPolygon(_cells[ci], maskImg, fg);
   debugWrite(maskImg);
   rcOptoKineticImage kinetic(rcOptoKineticImage::eKineTypeDummy);
   for (int32 fi = startFrame; fi < endFrame; fi++)
     kinetic.push(movie[fi]);
   const int32 radius = 1;
   const int32 szOffset = radius+1;
   const int32 szAdjust = 2*szOffset;
   const int32 segWidth = movie[0].width() - szAdjust;
   const int32 segHeight = movie[0].height() - szAdjust;
   rcWindow freqImg(movie[0].width(), movie[0].height(), rcPixel32);
   kinetic.genFreqImg(freqImg, framesPerPeriod, &maskImg);
   rcWindow freqImgWin(freqImg, szOffset, szOffset, segWidth, segHeight);
   segFreqImg = rcWindow(segWidth + 2, segHeight + 2);
   segFreqImg.setAllPixels(bg);
   rcWindow segFreqWin(segFreqImg, 1, 1, segWidth, segHeight);
   const float segFreqVal = 0.10;
   binarizeFloatWindow(freqImgWin, segFreqWin, segFreqVal, fg, bg);
   return 0;
 }
void rcMuscleSegmenter::genPolygons (const rcWindow & segImg, const int32 minDim, vector< rcPolygon > & p, const rcIPair delta) const private
Definition at line 83 of file rc_musclesegment.cpp.
References endl(), rcRectangle< T >::height(), MSDBG1, MSDBG2, rfGetComponents(), rfGetRects(), rcPolygon::translate(), rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by filterByActivity(), and segment().
 {
   p.clear();
   uint32 blobCnt;
   rcWindow blobWin;
   rfGetComponents(segImg, blobCnt, blobWin);
   if (blobCnt == 0)
     return;
   const bool combineRects = false;
   vector<rcIRect> rects;
   vector<uint32> rectLabel;
   const rcIPair minPairSz(0, 0);
   rfGetRects(blobWin, blobCnt, minPairSz, combineRects, rects, rectLabel);
   uint32 polyCnt = 0;
   for (uint32 i = 0; i < blobCnt; i++)
     {
 #if 0
     const rcIRect r = rects[i];
     if ((r.width() < minDim) && (r.height() < minDim))
       continue;
     const rcWindow rw(blobWin, r.ul().x(), r.ul().y(), r.width(), r.height());
     rcRleWindow rle;
     rle.encode(rw, blobCnt, rectLabel[i]);
     rcPolygon poly;
     rle.polygon(poly);
     p.push_back(poly);
     p[polyCnt++].translate(rc2Dvector(r.ul().x() + delta.x(),
                       r.ul().y() + delta.y()));
 #endif
     if (MSDBG2) cout << polyCnt-1 << " has polygon: " << p[polyCnt-1] << endl;
   }
   if (MSDBG1) printf("Blob count %d Polygon count %d\n", blobCnt, polyCnt);
 }
void rcMuscleSegmenter::genSpatialSegmentation (const vector< rcWindow > & movie, int32 startFrame, int32 endFrame, int32 & emi, rcWindow & segSdImg) private
Definition at line 306 of file rc_musclesegment.cpp.
References binarizeFloatWindow(), genSpatialSDImg(), getEMI(), rcPixel32, rmAssert, segPoint(), and rcWindow::setAllPixels().
Referenced by segment().
 {
   rmAssert(startFrame >= 0);
   rmAssert(endFrame < (int32)movie.size());
   rmAssert((endFrame - startFrame) >= 2);
   /* Use the following algorithm to generate a segmented image:
    *
    * 1) Calculate the index of a frame that has fully extended
    *    muscle cells.
    *
    * 2) Generate the std dev image for the emi frame. Calculate a
    *    segmentation point and generate a segmented version of of the
    *    std dev image based on this. The foreground pixels in the
    *    segmented std dev image serve as the candidate muscle cell
    *    areas.
    */
   /* Step 1
    */
   emi = getEMI(movie, startFrame, endFrame);
   rmAssert(emi >= startFrame);
   rmAssert(emi < endFrame);
   /* Step 2
    */
   const int32 radius = 1;
   const int32 szOffset = radius+1;
   const int32 szAdjust = 2*szOffset;
   const int32 segWidth = movie[0].width() - szAdjust;
   const int32 segHeight = movie[0].height() - szAdjust;
   rcWindow sdImg(segWidth, segHeight, rcPixel32);
   genSpatialSDImg(movie[emi], sdImg, radius);
   const float minBinVal = 3.0, binSz = 0.2;
   const int32 binCnt = 40;
   const bool getPeak = true;
   const float segSdVal = segPoint(sdImg, minBinVal, binSz, binCnt, getPeak);
   const uint8 bg = 0, fg = 0xFF;
   rcWindow segSdImgBase(movie[0].width(), movie[0].height());
   segSdImgBase.setAllPixels(bg);
   segSdImg = rcWindow(segSdImgBase, 1, 1, segWidth + 2, segHeight + 2);
   rcWindow segSdWin(segSdImgBase, szAdjust, szAdjust, segWidth, segHeight);
   binarizeFloatWindow(sdImg, segSdWin, segSdVal, fg, bg);
   //@todo  rfImageConvertFloat8 (sdImg, segSdWin, segSdVal - 1e-10, segSdVal + 1e-10);
 }
void rcMuscleSegmenter::getCells (vector< rcPolygon > & cells) const
Definition at line 817 of file rc_musclesegment.cpp.
References _cells, _debugMovie, _emiImgDbg, rcWindow::copyPixelsFromWindow(), debugWrite(), rcWindow::height(), rcDrawAffineRectangle(), rcDrawPolygon(), and rcWindow::width().
Referenced by rcEngineImpl::muscleTracker().
 {
   cells.resize(_cells.size());
   for (uint32 ci = 0; ci < _cells.size(); ci++)
     cells[ci] = _cells[ci];
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 polyColor = 0x7F, boxColor = 0xFF;
     const bool fill = true;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ci = 0; ci < cells.size(); ci++) {
       const rcAffineRectangle aRect = cells[ci].minimumAreaEnclosingRect();
       rcDrawAffineRectangle(aRect, scribble, boxColor);
       rcDrawPolygon(cells[ci], scribble, polyColor, fill);
     }
     debugWrite(scribble);
   }
 }
int32 rcMuscleSegmenter::getEMI (const vector< rcWindow > & movie, int32 startFrame, int32 endFrame) private
Definition at line 42 of file rc_musclesegment.cpp.
References calcExtendedMuscleCellFrame(), rcSimilarator::eExhaustive, eMovie, rcSimilarator::entropies(), rcSimilarator::eVisualEntropy, rcSimilarator::fill(), rcPixel8, rmAssert, and rcSimilarator::update().
Referenced by genSpatialSegmentation().
 {
   /* First, generate the energy curve for the sample period. This will
    * be used by calcExtendedMuscleCellFrame() to calculate the
    * location of a frame with the muscle cell fully expanded.
    */
   deque<double> signal;
   const uint32 windowSz = 2, cacheSz = 0;
   rcSimilarator energy(rcSimilarator::eExhaustive,
                rcPixel8, windowSz, cacheSz);
   vector<rcWindow> eMovie;
   int32 fi;
   int32 lastWinFrame = startFrame + (int32)windowSz;
   for (fi = startFrame; fi < lastWinFrame; fi++)
     eMovie.push_back(movie[fi]);
   bool rval = energy.fill(eMovie);
   rmAssert(rval);
   const int32 targetValue = windowSz/2;
   deque<double> tempSig;
   energy.entropies(tempSig, rcSimilarator::eVisualEntropy);
   signal.push_back(tempSig[targetValue]);
   for ( ; fi < endFrame; fi++) {
     rval = energy.update(movie[fi]);
     rmAssert(rval);
     energy.entropies(tempSig, rcSimilarator::eVisualEntropy);
     signal.push_back(tempSig[targetValue]);
   }
   return calcExtendedMuscleCellFrame(signal, movie, startFrame);
 }
void rcMuscleSegmenter::getRejects (vector< rcPolygon > & rejects) const
Definition at line 838 of file rc_musclesegment.cpp.
References _rejects.
Referenced by rcEngineImpl::muscleTracker().
 {
   rejects.resize(_rejects.size());
   for (uint32 ri = 0; ri < _rejects.size(); ri++)
     rejects[ri] = _rejects[ri];
 }
void rcMuscleSegmenter::hackInsertSegmentedImages (rcWindow & segSdImg, rcWindow & segFreqImg, rcWindow & emiImg)
Definition at line 295 of file rc_musclesegment.cpp.
References _emi, _emiImg, _segFreqImg, and _segSdImg.
Referenced by rcEngineImpl::muscleTracker().
 {
   _segSdImg = segSdImg;
   _segFreqImg = segFreqImg;
   _emiImg = emiImg;
   _emi = 0;
 }
void rcMuscleSegmenter::mergePolygons (vector< rcPolygon > & poly, vector< rcPolygon > & polyCH, vector< rcPolygon > & mergedCH, vector< rcIRect > & mergedCHR, vector< polyInterInfo > & mergedInfo) const private
Definition at line 128 of file rc_musclesegment.cpp.
References rcRectangle< T >::area(), rcPolygon::area(), rcPolygon::convexIntersection(), rcPolygon::convexUnion(), MSDBG1, rcPolygon::orthogonalEnclosingRect(), and rmAssert.
Referenced by segment().
 {
   rmAssert(poly.size() == polyCH.size());
   mergedCH.clear();
   mergedCHR.clear();
   mergedInfo.clear();
   //@note less<> is the default sorting
   // merging start with largest. Hence the reverse iterators
   multimap<double, uint32> areaToIndex;
   for (uint32 si = 0; si < poly.size(); si++) {
     double area = poly[si].area();
     areaToIndex.insert(pair<double, uint32>(area,si));
   }
   vector<uint32> mergedToPoly(poly.size());
   for (multimap<double, uint32>::reverse_iterator si = areaToIndex.rbegin();
        si != areaToIndex.rend(); si++) {
     rcPolygon& pCH = polyCH[si->second];
     rcIRect boxCH = pCH.orthogonalEnclosingRect();
     double sAreaCH = -1.0;
     uint32 mi;
     for (mi = 0; mi < mergedCH.size(); mi++) {
       if (mergedCHR[mi].overlaps(boxCH, true)) {
     if (sAreaCH < 0.0)
       sAreaCH = pCH.area()*0.5;
     uint32 mpi = mergedToPoly[mi];
     rcPolygon intPoly;
     polyCH[mpi].convexIntersection(pCH, intPoly);
     if (intPoly.area() > sAreaCH) {
       mergedInfo[mi].area += si->first;
       mergedInfo[mi].polyInter.push_back(poly[si->second]);
       if (intPoly != pCH) {
         rcPolygon unionPoly;
         mergedCH[mi].convexUnion(pCH, unionPoly);
         mergedCH[mi] = unionPoly;
         mergedCHR[mi] = mergedCH[mi].orthogonalEnclosingRect();
       }
       break;
     }
       }
     }
     if (mi == mergedCH.size()) {
       mergedCH.push_back(pCH);
       mergedCHR.push_back(boxCH);
       mergedInfo.push_back(polyInterInfo());
       mergedInfo.back().area = si->first;
       mergedInfo.back().polyInter.push_back(poly[si->second]);
       mergedToPoly[mergedCH.size()-1] = si->second;
     }
   }
   if (MSDBG1) printf("merged count %d\n", (int)mergedCH.size());
 }
void rcMuscleSegmenter::rejectRange (int32 & startIndex, int32 & endIndex, rejectionCode reason, int32 instance = 1) const
Definition at line 847 of file rc_musclesegment.cpp.
References _rejectIndex, _rejectReason, cRejCodeCount, and rmAssert.
Referenced by rcEngineImpl::produceMuscleDebugResults().
 {
   rmAssert(reason < cRejCodeCount);
   const int32 rejSz = (int32)_rejectReason.size();
   rmAssert(rejSz == (int32)_rejectIndex.size());
   startIndex = endIndex = 0;
   if (instance < 1)
     return;
   int32 ri = -1;
   while (instance--) {
     ri++;
     for ( ;ri < rejSz; ri++) {
       if (_rejectReason[ri] == reason)
     break;
     }
   }
   if (ri != rejSz) {
     if (ri == 0)
       startIndex = 0;
     else
       startIndex = _rejectIndex[ri-1];
     endIndex = _rejectIndex[ri];
   }
 }
int32 rcMuscleSegmenter::segment (const vector< rcWindow > & movie, int32 startFrame, int32 endFrame, bool fluo = false)
Definition at line 428 of file rc_musclesegment.cpp.
References _activeRegions, _cells, _cellsInfo, _cellsR, _debugMovie, _dSize, _emi, _emiImgDbg, _rejectIndex, _rejectReason, _rejects, _segSdImgDbg, _segSdImgSz, color(), rcWindow::copyPixelsFromWindow(), cWindowTooSmall, debugWrite(), rcGenMovieFile::frameSize(), genPolygons(), genSpatialSegmentation(), rcWindow::height(), mergePolygons(), MSDBG1, rcDrawPolygon(), rfPixel8Map(), rmAssert, rcWindow::setAllPixels(), rcWindow::size(), and rcWindow::width().
Referenced by rcEngineImpl::muscleTracker().
 {
   rmAssert(endFrame > startFrame);
   rmAssert((int32)movie.size() >= endFrame);
   /* minWinDim of 10 may be overly large, but just wanted a value big
    * enough to keep window sizes from getting too small.
    */
   const int32 minWinDim = 10;
   if ((movie[0].width() < minWinDim) || (movie[0].height() < minWinDim))
     return cWindowTooSmall;
   _cells.clear();
   _cellsR.clear();
   _cellsInfo.clear();
   _activeRegions.clear();
   _rejects.clear();
   _rejectIndex.clear();
   _rejectReason.clear();
   if (_debugMovie) {
     _dSize = _debugMovie->frameSize();
     if (_dSize == rcIPair(0, 0))
       _dSize = movie[0].size();
   }
   rcWindow segSdImg, emiImg;
   //@note placeholder for passing in binary / pre-mapped images in to segmentation
   if (0) {
   const int32 radius = 1;
   const int32 szOffset = radius+1;
   const int32 szAdjust = 2*szOffset;
   const int32 segWidth = movie[0].width() - szAdjust;
   const int32 segHeight = movie[0].height() - szAdjust;
     rcWindow segSdImgBase(movie[0].width(), movie[0].height());
     segSdImgBase.setAllPixels(0);
     segSdImg = rcWindow(segSdImgBase, 1, 1, segWidth + 2, segHeight + 2);
     _emi = startFrame;
     emiImg = movie[_emi];
     static const uint8 zu (0);
     vector<uint8> bmap (256, zu);
     bmap[255] = 1;
     rfPixel8Map (emiImg, segSdImgBase, bmap);
   }
   else {
     genSpatialSegmentation(movie, startFrame, endFrame, _emi, segSdImg);
     emiImg = movie[_emi];
   }
   _segSdImgSz = segSdImg.size();
   if (_debugMovie) {
     _emiImgDbg = emiImg;
     debugWrite(_emiImgDbg);
     _segSdImgDbg = segSdImg;
     debugWrite(_segSdImgDbg);
   }
   else {
     _emiImgDbg = rcWindow();
     _segSdImgDbg = rcWindow();
   }
   const int32 minDim = 4;
   vector<rcPolygon> fgPoly;
   genPolygons(segSdImg, minDim, fgPoly, rcIPair(1, 1));
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 bgColor = 0;
     scribble.setAllPixels(bgColor);
     rcWindow scribWin(scribble, 1, 1, _segSdImgDbg.width(), _segSdImgDbg.height());
     const bool fill = true;
     const uint8 segColor = 0x7F;
     scribWin.copyPixelsFromWindow(_segSdImgDbg);
     for (uint32 fi = 0; fi < fgPoly.size(); fi++)
       rcDrawPolygon(fgPoly[fi], scribble, segColor, fill);
     debugWrite(scribble);
     const uint8 imgColor = 0xFF;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 i = 0; i < fgPoly.size(); i++)
       rcDrawPolygon(fgPoly[i], scribble, imgColor, fill);
     debugWrite(scribble);
   }
   vector<rcPolygon> fgPolyCH(fgPoly.size());
   for (uint32 fi = 0; fi < fgPoly.size(); fi++)
     fgPoly[fi].convexHull(fgPolyCH[fi]);
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const bool fill = true;
     const uint8 imgColor = 0xFF;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 fi = 0; fi < fgPolyCH.size(); fi++)
       rcDrawPolygon(fgPolyCH[fi], scribble, imgColor, fill);
     debugWrite(scribble);
   }
   mergePolygons(fgPoly, fgPolyCH, _cells, _cellsR, _cellsInfo);
   if (MSDBG1) printf("%d merged cell polygons\n", (int)_cells.size());
   if (_debugMovie) {
     rcWindow scribble(_emiImgDbg.width(), _emiImgDbg.height());
     const uint8 color = 0xFF;
     const bool fill = true;
     scribble.copyPixelsFromWindow(_emiImgDbg);
     for (uint32 ci = 0; ci < _cells.size(); ci++)
       rcDrawPolygon(_cells[ci], scribble, color, fill);
     debugWrite(scribble);
   }
   return 0;
 }
Member Data Documentation
vector<rcPolygon> rcMuscleSegmenter::_activeRegions private
Definition at line 202 of file rc_musclesegment.h.
Referenced by filterByActivity(), and segment().
vector<rcPolygon> rcMuscleSegmenter::_cells private
Definition at line 202 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), genFrequencySegmentation(), getCells(), and segment().
vector<polyInterInfo> rcMuscleSegmenter::_cellsInfo private
Definition at line 204 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), and segment().
vector<rcIRect> rcMuscleSegmenter::_cellsR private
Definition at line 203 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), and segment().
rcGenMovieFile* rcMuscleSegmenter::_debugMovie private
Definition at line 197 of file rc_musclesegment.h.
Referenced by debugWrite(), filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), getCells(), and segment().
rcIPair rcMuscleSegmenter::_dSize private
Definition at line 198 of file rc_musclesegment.h.
Referenced by debugWrite(), and segment().
int32 rcMuscleSegmenter::_emi private
Definition at line 200 of file rc_musclesegment.h.
Referenced by extendedMuscleCellIndex(), filterByActivity(), hackInsertSegmentedImages(), and segment().
rcWindow rcMuscleSegmenter::_emiImg private
Definition at line 194 of file rc_musclesegment.h.
Referenced by hackInsertSegmentedImages().
rcWindow rcMuscleSegmenter::_emiImgDbg private
Definition at line 196 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), getCells(), and segment().
float rcMuscleSegmenter::_framesPerPeriod private
Definition at line 201 of file rc_musclesegment.h.
Referenced by filterByActivity(), framesPerPeriod(), and genFrequencySegmentation().
vector<int32> rcMuscleSegmenter::_rejectIndex private
Definition at line 205 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), rejectRange(), and segment().
vector<rejectionCode> rcMuscleSegmenter::_rejectReason private
Definition at line 206 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), rejectRange(), and segment().
vector<rcPolygon> rcMuscleSegmenter::_rejects private
Definition at line 202 of file rc_musclesegment.h.
Referenced by filterAtEdge(), filterByActivity(), filterByAR(), filterBySize(), getRejects(), and segment().
rcWindow rcMuscleSegmenter::_segFreqImg private
Definition at line 194 of file rc_musclesegment.h.
Referenced by filterByActivity(), and hackInsertSegmentedImages().
rcWindow rcMuscleSegmenter::_segSdImg private
Definition at line 194 of file rc_musclesegment.h.
Referenced by hackInsertSegmentedImages().
rcWindow rcMuscleSegmenter::_segSdImgDbg private
Definition at line 196 of file rc_musclesegment.h.
Referenced by segment().
rcIPair rcMuscleSegmenter::_segSdImgSz private
Definition at line 207 of file rc_musclesegment.h.
Referenced by filterAtEdge(), and segment().
The documentation for this class was generated from the following files:
include/analysis/rc_musclesegment.h
src/analysis/code/rc_musclesegment.cpp