Visible: rcEngineImpl Class Reference
rcEngineImpl Class Reference
#include <include/visiCore/rc_engineimpl.h>
Public Member Functions
rcEngineImpl ()
virtual ~rcEngineImpl ()
virtual void initialize (rcEngineObserver *observer)
virtual void start (void)
virtual void stop (void)
virtual void shutdown (void)
virtual void internalReset ()
virtual void unlockedReset ()
virtual void reset ()
virtual void process ()
void analyze ()
void setPathNameToTemplate (std::string argv0)
bool setFromArgs (int32 argc, char **argv)
std::string outputFile () const
rcExperimentFileFormat outputFormat () const
virtual int getNSettingCategories (void)
virtual rcSettingCategory getSettingCategory (int categoryNo)
virtual rcSettingCategory getSettingCategory (char *categoryName)
void frameInterrupt (const rcAnalyzerResult &result, const std::string &cameraStatus, uint32 missedFramesOnCapture, uint32 missedFramesOnSave, bool frameSaved)
void frameFlush ()
void setFrameSize (uint32 width, uint32 height, rcPixel depth)
void startPreview ()
void resumePreview ()
void setCameraInfo (const rcMovieFileCamExt &info)
void setCaptureInfo (const rcMovieFileOrgExt &info)
void setCaptureInfo (const rcMovieFileOrgExt &org, const rcMovieFileExpExt &exp)
void setTimeLineRange ()
bool isEntire ()
void model2use ()
virtual rcTimestamp getElapsedTime (void)
virtual rcTimestamp getStartTime (void)
virtual rcEngineState getState (void)
virtual const rcEngineAttributes getAttributes (void)
virtual bool operatingOnLiveInput (void)
virtual bool storingLiveInput (void)
virtual bool pauseTracking ()
virtual bool resumeTracking ()
virtual void notifyEngineOfPolys (const rcPolygonGroupRef *polys)
rcEngineObserver & observer ()
virtual const rcValue getSettingValue (int settingId)
virtual void setSettingValue (int settingId, const rcValue &value)
virtual bool isSettingEnabled (int settingId)
virtual bool isSettingEditable (int settingId)
virtual bool isSettingPersistable (int settingId)
virtual void lock ()
virtual void unlock ()
Public Member Functions inherited from rcEngine
virtual ~rcEngine ()
Public Member Functions inherited from rcSettingSource
virtual ~rcSettingSource ()
Public Member Functions inherited from rcCarbonLock
virtual ~rcCarbonLock ()
Protected Member Functions
bool isTrackingPaused ()
void createSharedWriters ()
void flushSharedWriters ()
void createGraphicsWriters (bool motionVectors, bool bodyVectors, bool bodyHistoryVectors, bool segmentVectors)
void createGraphicsWriters ()
void flushGraphicsWriters ()
void createCameraPreviewWriters ()
void setState (rcEngineState newState)
void setInternalState (rcEngineState newState)
void engineAbort (const char *msg)
void assertInitialized (void)
int loadFrames (rcFrameGrabber &grabber, rcFrameGrabberError &error)
int loadImages ()
int loadMovie ()
int loadMovie (const std::string &movieFile, rcFrameGrabberError &error)
int32 framesLoaded () const
uint32 framesToAnalyze () const
int32 saveFrames (std::string imageExportDir) const
uint32 analyzeFocusArea (rcEngineFocusData *focus)
void writeEntropyData (rcEngineFocusData *focus, const vector< rcWindow > &images, const vector< double > &signal)
int writeTimedScalar (const rcEngineFocusData *focus, const vector< double > &signal, const vector< rcWindow > &focusImages, rcScalarWriter *writer)
int writeTimedFloats (const rcEngineFocusData *focus, const vector< float > &signal, const vector< rcWindow > &focusImages, rcScalarWriter *writer)
rcExperimentAttributes attributes (const rcMovieFileExpExt &exp) const
void processCapturedData (rcEngineFocusData *focus, rcTimestamp timestamp, const std::string &cameraStatus, const rcAnalyzerResult &result, bool delay, uint32 missedFramesOnCapture, uint32 missedFramesOnSave, bool frameSaved)
void produceCellResults (rcEngineFocusData *focus, rcKinetoscope &motionTracker, const rcRect &focusRect, const rcTimestamp &curTimeStamp, bool &firstCell)
void postTrackingResults (rcEngineFocusData *focus, rcFindList &, bool found, const rcRect &focusRect, const rc2Xform &mx, const rcTimestamp &curTimeStamp, const rcVisualSegmentCollection &)
void produceDebugResults (rcEngineFocusData *focus, rcWindow &debugImage, rcVisualGraphicsCollection &debugGraphics, const rcRect &focusRect, const rcTimestamp &curTimeStamp)
uint32 entropyTracker (rcEngineFocusData *focus, vector< rcWindow > &focusImages, int32 cacheSz)
uint32 entropyTrackerWindow (rcEngineFocusData *focus, vector< rcWindow > &focusImages, int32 cacheSz, bool clippedFrameBuf)
uint32 motionTracker (rcEngineFocusData *focus, const vector< rcWindow > &focusImages, int32 cacheSz)
uint32 modelTracker (rcEngineFocusData *focus, const vector< rcWindow > &focusImages, int32 cacheSz)
int32 muscleTracker (rcEngineFocusData *focus, const vector< rcWindow > &focusImages, int32 cacheSz, double msPerFrame)
void updateHeaderLogs ()
void updateCaptureLog ()
void updateCameraLog ()
void updateConversionLog ()
template<class T >
double groupStatistics (const vector< T > &)
void ipp (const rcWindow &image, rcWindow &dst, rcTimestamp &current)
std::string focusScript ()
void focusMyocyteSelection (const rcIRect &rect, vector< rc2Fvector > &ends, float &rad)
void registeredWindows (vector< rcWindow > &focusImages, int32 &range)
void reportOnBadGrabber (const rcVectorGrabber &imageGrabber) const
bool produceMuscleDebugResults (const vector< rcPolygon > &rejects, rcMuscleSegmenter &segmenter, rcVisualSegmentCollection &segments)
std::string makeTmpName (std::string exten)
Protected Attributes
bool _batchMode
rcInputSource _inputSource
rcInputMode _inputMode
rcIPPMode _ippMode
float _frameRate
std::string _movieFile
std::string _imageFileNames
rcRect _analysisRect
int _analysisMode
rcAffineRectangle _analysisAffine
rcSimilarator::rcEntropyDefinition _aciOptions
uint32 _writerSizeLimit
uint32 _previewWriterSizeLimit
int _slidingWindowSize
rcAnalyzerResultOrigin _slidingWindowOrigin
rcMutex _settingMutex
int32 _useMask
int32 _aciTemporalSampling
int32 _motionTrackingTargetSize
int32 _motionTrackingTargetSizeMultiplier
int32 _motionTrackingSampleSize
int32 _motionTrackingMaxSpeed
bool _motionTrackingMotionVectorDisplay
bool _motionTrackingBodyVectorDisplay
bool _motionTrackingBodyHistoryVectorDisplay
int32 _motionTrackingFrameSampling
int32 _motionTrackingStep
bool _exportMotionVectors
bool _exportBodyGraphics
bool _segmentationVectorDisplay
int32 _analysisFirstFrame
int32 _analysisLastFrame
rcChannelConversion _channelConversion
std::string _captureLog
std::string _cameraInfo
std::string _conversionInfo
int _analysisTreatmentObject
int _analysisTreatmentObjectSize
bool _developmentVideoEnabled
bool _developmentGraphicsEnabled
bool _visualizeDevelopment
int _cellType
int _statType
int _msPerContraction
bool _energyGraphicsEnabled
bool _exportEnergyGraphics
int _enableGlobalMotionEst
rcAtomicValue< rcEngineState > _state
int _frameWidth
int _frameHeight
int _frameDepth
vector< rcSettingCategory > _settings
rcEngineObserver * _observer
rcTimestamp _startTime
rcTimestamp _currentTime
rcWriterGroup * _writerGroup
rcWriterGroup * _graphicsWriterGroup
rcGraphicsWriter * _motionVectorWriter
rcGraphicsWriter * _bodyVectorWriter
rcGraphicsWriter * _bodyHistoryVectorWriter
rcGraphicsWriter * _segmentVectorWriter
rcGraphicsWriter * _energyPlotWriter
rcAtomicValue< rcVideoWriter * > _videoWriter
uint32 _groupCount
rcAtomicValue
< rcEngineFocusData * > _frameFocus
rcFpsCalculator _fpsCalculator
rcWriterManager * _writerManager
rcThread * _captureThread
rcEngineMovieCapture * _movieCapture
rcVideoCaptureCtrl _captureCtrl
rcMovieSaveCtrl _saveCtrl
rcAtomicValue< bool > _firstFrameSaved
rcWriterGroup * mPreviewWriterGroup
rcScalarWriter * mSlidingEnergyPreviewWriter
rcEngineAnalyzer * _analyzer
rcThread * _analyzerThread
uint32 _processCount
vector< rcWindow > _fileImages
vector< rc2Fvector > _offsetsToFirst
rcThread * _importThread
rcEngineImporter * _importer
rcVideoCache * _videoCacheP
rcEngineProgress * _videoCacheProgress
rcMovieFileOrgExt mOrgExt
rcMoviePlaybackCtrl _playbackCtrl
rcThread * _playbackThread
rcEngineMoviePlayback * _player
bool _showCellText
bool _showCellPosition
bool _showCellPath
rcExperimentFileFormat _saveFormat
std::string _outputFileName
rcIPair _cLineRectTL
rcIPair _cLineRectSize
int32 _cLineStartFrame
int32 _cLineEndFrame
std::string _exportImagesDir
std::string _model2useAbsPathFileName
rcWindow _model2use
std::string _resourceFolderPath
std::string _installPath
rcAtomicValue< bool > _isPausedToggle
rcPolygonGroupRef _selectedPolys
Friends
class rcEngineImporter
Detailed Description
Definition at line 117 of file rc_engineimpl.h.
Constructor & Destructor Documentation
rcEngineImpl::rcEngineImpl ()
Definition at line 131 of file rc_engineimpl.cpp.
References _analyzerThread, _captureThread, _importThread, _movieCapture, _observer, _playbackThread, _player, _videoCacheP, _writerManager, eEngineUninitialized, getState(), internalReset(), and PRINT_STATE_CHANGE.
                            : _state(eEngineUninitialized),
 _videoWriter(0),
 _frameFocus(0),
 _fpsCalculator( 15 ), // Speed fps for a buffer of 15 frames
 _firstFrameSaved(true), _isPausedToggle (false)
 {
   PRINT_STATE_CHANGE("ctor", getState(), eEngineUninitialized);
   _captureThread = 0;
   _importThread = 0;
   _movieCapture = 0;
   _analyzerThread = 0;
   _observer = 0;
   _writerManager = 0;
   _videoCacheP = 0;
   _playbackThread = 0;
   _player = 0;
   // reset default attributes
   internalReset();
 }
rcEngineImpl::~rcEngineImpl () virtual
Definition at line 153 of file rc_engineimpl.cpp.
References _analyzerThread, _captureThread, _frameFocus, _importer, _importThread, _movieCapture, _playbackThread, _player, _videoCacheProgress, _writerManager, and rcAtomicValue< T >::getValue().
 {
   delete _captureThread;
   delete _importThread;
   delete _analyzerThread;
   delete _playbackThread;
   delete _importer;
   delete _movieCapture;
   delete _player;
   rcEngineFocusData* temp;
   delete _frameFocus.getValue(temp);
   delete _writerManager;
   delete _videoCacheProgress;
 }
Member Function Documentation
void rcEngineImpl::analyze ()
Definition at line 770 of file rc_engineimpl.cpp.
References _analysisFirstFrame, _analysisLastFrame, _analysisMode, _frameHeight, _frameWidth, _groupCount, _inputMode, _observer, _processCount, _resourceFolderPath, _videoCacheP, _writerManager, _writerSizeLimit, analyzeFocusArea(), cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisCellTracking, cAnalysisCellTypeId, cAnalysisModeSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisObjectSettingId, cAnalysisRectSettingId, create_filespec(), cTemplateFileNameId, eCmd, eEngineRunning, eEngineStopped, eFile, folder_down(), folder_up(), framesLoaded(), framesToAnalyze(), getSettingValue(), rcRectangle< T >::height(), rcEngineObserver::notifyAnalysisRect(), rcEngineObserver::notifyError(), rmDim, setInternalState(), setSettingValue(), and rcRectangle< T >::width().
Referenced by process(), and rcEngineAnalyzer::run().
 {
   ++_processCount;
 #ifdef GOODMAN_LAB
     // Get the resource folder, fetch the target template and report
     if (_inputMode == eFile || _inputMode == eCmd)
         {
             std::string tmp = folder_up (_resourceFolderPath);
             tmp = folder_down (tmp, std::string ("Resources"));
             tmp = create_filespec (tmp, std::string ("tip"), std::string ("tif"));
             setSettingValue (cTemplateFileNameId, rcValue (tmp));
         }
 #endif
   if ( _inputMode == eFile || _inputMode == eCmd) {
     if ( framesLoaded() > 1 ) {
       uint32 imageCount = framesToAnalyze();
       if ( imageCount > 0 ) {
                 // At least one analysis operation is selected
                 rcEngineFocusData* focus = 0;
                 uint32 resultCount = 0;
                 rcRect aRect = getSettingValue( cAnalysisRectSettingId );
                 rcRect iRect = rcRect( 0, 0, _frameWidth, _frameHeight );
                 if ( aRect.width() > 0 && aRect.height() > 0 ) {
                     if ( _analysisMode == cAnalysisCellTracking && ! _videoCacheP ) {
                         // No video cache
                         // Motion analysis enabled for Reify movies only
                         _observer->notifyError( "Functional visual analysis can be performed for Reify movies (.rfymov) only" );
                     } else {
                         // Create a new focus object
                         focus = new rcEngineFocusData( _writerManager,
                                                                                     aRect,
                                                                                     iRect,
                                                                                     framesLoaded(),
                                                                                     static_cast<rcAnalysisMode>(int(getSettingValue( cAnalysisModeSettingId ))),
                                                                                     _writerSizeLimit,
                                                                                     static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisACISlidingWindowSizeSettingId ) )),
                                                                                     static_cast<rcAnalyzerResultOrigin>(static_cast<int>(getSettingValue( cAnalysisACISlidingWindowOriginSettingId ))),
                                                                                     _groupCount,
                                                                                     static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisMotionTrackingSpeedSettingId ))),
                                                                                     static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisObjectSettingId))),
                                                                                     static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisCellTypeId ))));
                         // Gentlemen, start your engines
                         setInternalState( eEngineRunning );
                         setInternalState( eEngineStopped );
                         setInternalState( eEngineRunning );
                         // Analyze current focus area
                         resultCount = analyzeFocusArea( focus );
                         delete focus;
                     }
                 } else {
                     // We need two or more images for analysis
                     _observer->notifyError( "No attention area specified for analysis" );
                 }
       } else {
                 // Image range is not valid
                 char buf[512];
                 snprintf( buf, rmDim(buf), "Invalid range of images to analyze: [%i-%i]",
                                  _analysisFirstFrame, _analysisLastFrame );
                 _observer->notifyError( buf );
       }
     } else {
       // We need two or more images for analysis
       _observer->notifyError( "Not enough images loaded for analysis" );
     }
   }
   if (_inputMode != eCmd)
     setInternalState( eEngineStopped );
   _observer->notifyAnalysisRect( getSettingValue( cAnalysisRectSettingId ) );
   // cerr << focusScript () << endl;
 }
uint32 rcEngineImpl::analyzeFocusArea (rcEngineFocusData * focus) protected
Definition at line 1516 of file rc_engineimpl.cpp.
References _analysisFirstFrame, _analysisLastFrame, _analysisMode, _channelConversion, _fileImages, _observer, _videoCacheP, cAnalysisACI, cAnalysisACISlidingWindow, cAnalysisACIStepSettingId, cAnalysisTemplateTracking, cImagePreMappingSettingId, rcWindow::depth(), eIPPNone, endl(), entropyTracker(), entropyTrackerWindow(), rcEngineFocusData::flushFocusData(), flushGraphicsWriters(), flushSharedWriters(), rcEngineFocusData::focusRect(), rcWindow::frameBuf(), rcVideoCache::frameDepth(), framesToAnalyze(), getSettingValue(), rcRectangle< T >::height(), ipp(), modelTracker(), mOrgExt, rcVideoCache::movieFileOrigins(), rcEngineObserver::notifyError(), rcEngineObserver::notifyStatus(), rcTimestamp::now(), rcPixel16, rcPixel32, rcPixel8, rfImageConvert32to8(), rmAssert, rmExceptionMacro, rcTimestamp::secs(), rcFrame::timestamp(), general_exception::what(), and rcRectangle< T >::width().
Referenced by analyze().
 {
   uint32 analysisCount = 0;
   rcIPPMode userMode = (rcIPPMode) (int) getSettingValue(cImagePreMappingSettingId);
   try {
     rcTimestamp duration = rcTimestamp::now();
     if ( focus ) {
       // Do analysis
       int32 cacheSz = 0;
       int32 aciTemporalSample (1);
       if (_analysisMode == cAnalysisACI || _analysisMode == cAnalysisACISlidingWindow)
                 {
                     aciTemporalSample  = getSettingValue( cAnalysisACIStepSettingId );
                     cerr << "Temporal ACI Sampling " << aciTemporalSample << " [" << _analysisFirstFrame << "..." << _analysisLastFrame << "] " << endl;
                 }
       uint32 imageCount = framesToAnalyze();
       cerr << imageCount << " Images ";
       if (aciTemporalSample > 1 && imageCount > ((uint32) (10 * aciTemporalSample)))
                 imageCount = imageCount / aciTemporalSample;
       cerr << "Sampled " << "1 out of " << aciTemporalSample << endl;
       vector<rcWindow> focusImages (imageCount);
       const rcRect clipRect = focus->focusRect();
       bool clippedFrameBuf = false;
       bool combinedPhaseAndFluor (false);
       if (_videoCacheP)
                 {
                     const vector<rcMovieFileOrgExt>& orgHdrs = _videoCacheP->movieFileOrigins();
                     rmAssert( !orgHdrs.empty() );
                     mOrgExt = orgHdrs[0];
                 }
       if ( clipRect.height() > 0 && clipRect.width() > 0 ) {
                 _observer->notifyStatus( "Preparing analysis..." );
                 // Clip to focus area
                 for (uint32 i = 0; i < imageCount; i++)
                     {
                         rcRect translatedRect (clipRect);
                         rcWindow rw (_fileImages[_analysisFirstFrame+i*aciTemporalSample], translatedRect);
             rcTimestamp _ts = rw.frameBuf()->timestamp ();
                         /* @note: Do not access rw properties or data if _videoCache is used and
                          * depth is one that analysis can take in (@todo). In all other cases
                          * we check depth of the videoCache first.
                          * @note read the above note in loadFrames regarding access frames through videoCache
                          */
                         if ((_videoCacheP && _videoCacheP->frameDepth() == rcPixel8) ||
                                 (!_videoCacheP && rw.depth() == rcPixel8))
{
                                 ipp (rw, focusImages[i], _ts);
                                 clippedFrameBuf = userMode != eIPPNone;
                             }
                         else if ((_videoCacheP && _videoCacheP->frameDepth() == rcPixel32) ||
                                          (!_videoCacheP && rw.depth() == rcPixel32))
{
                                 if (!combinedPhaseAndFluor)
{
                                         focusImages[i] = rcWindow(clipRect.width(), clipRect.height());
                                         rfImageConvert32to8(rw, focusImages[i], _channelConversion);
                                         focusImages[i].atTime (rw);
                                         clippedFrameBuf = true;
                                     }
                                 else  // @note: right way is to implement Channel conversion all
{
                                         focusImages[i] = rw;
                                         clippedFrameBuf = false;
                                     }
                             }
                         else if ((_videoCacheP && _videoCacheP->frameDepth() == rcPixel16) ||
                                          (!_videoCacheP && rw.depth() == rcPixel16))
{
                                 ipp (rw, focusImages[i], _ts);
                                 clippedFrameBuf = userMode != eIPPNone;
                             }
                         else
{
                                 rmExceptionMacro (<< "Invalid Source and Depth");
                             }
                         rmAssert ( _ts == focusImages[i].frameBuf()->timestamp ());
                     }
                 // Perform chosen analysis operation
                 switch ( _analysisMode )
                 {
                     case cAnalysisACI:
                         analysisCount = entropyTracker( focus, focusImages, cacheSz );
                         break;
                     case cAnalysisACISlidingWindow:
                         analysisCount = entropyTrackerWindow( focus, focusImages, cacheSz,
                                                                                                  clippedFrameBuf );
                         break;
                     case cAnalysisTemplateTracking:
                         modelTracker( focus, focusImages, cacheSz );
                         break;
                     default:
                         _observer->notifyError( "Unsupported analysis operation selected" );
                         break;
                 } // Analysis Mode
       } // Valid Clip Rect
       // Flush all writers
       flushSharedWriters();
       flushGraphicsWriters();
       focus->flushFocusData();
       // Display status message to stdout
       duration = rcTimestamp::now() - duration;
       cout << analysisCount << " image(s) analyzed in " << duration.secs() << " seconds";
       cout << ", " << duration.secs()/analysisCount << " seconds/image" << endl;
     } // Focus
   } // Try Block
   catch  (general_exception& x )
     {
         cerr << "Caught exception " << x.what() << endl;
         _observer->notifyError( x.what() );
     }
   catch (...)
     {
         cerr << "Caught unknown exception" << endl;
         _observer->notifyError( "Caught unknown exception\n" );
     }
   return analysisCount;
 }
void rcEngineImpl::assertInitialized (void) protected
Definition at line 1271 of file rc_engineimpl.cpp.
References eEngineUninitialized, and getState().
Referenced by getElapsedTime(), getNSettingCategories(), getSettingCategory(), getSettingValue(), getStartTime(), isSettingEnabled(), isSettingPersistable(), and setSettingValue().
 {
   if (getState() == eEngineUninitialized)
     throw rcEngineException( "engine uninitialized" );
 }
rcExperimentAttributes rcEngineImpl::attributes (const rcMovieFileExpExt & exp) const protected
Definition at line 96 of file rc_engineimpl.cpp.
References rcExperimentAttributes::cellType, rcMovieFileExpExt::cellType(), rcExperimentAttributes::CO2, rcMovieFileExpExt::CO2(), rcMovieFileExpExt::comment(), rcExperimentAttributes::comments, rcExperimentAttributes::fileName, rcExperimentAttributes::frameDepth, rcExperimentAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcExperimentAttributes::imagingMode, rcMovieFileExpExt::imagingMode(), rcExperimentAttributes::inputName, rcExperimentAttributes::lensMag, rcMovieFileExpExt::lensMag(), rcExperimentAttributes::liveInput, rcExperimentAttributes::liveStorage, rcExperimentAttributes::O2, rcMovieFileExpExt::O2(), rcExperimentAttributes::otherMag, rcMovieFileExpExt::otherMag(), rcExperimentAttributes::temperature, rcMovieFileExpExt::temperature(), rcExperimentAttributes::title, rcMovieFileExpExt::title(), rcExperimentAttributes::treatment1, rcMovieFileExpExt::treatment1(), rcExperimentAttributes::treatment2, rcMovieFileExpExt::treatment2(), rcExperimentAttributes::userName, and rcMovieFileExpExt::userName().
Referenced by loadMovie().
 {
   rcExperimentAttributes attrs;
   attrs.title = exp.title();
   attrs.userName = exp.userName();
   attrs.comments = exp.comment();
   attrs.treatment1 = exp.treatment1();
   attrs.treatment2 = exp.treatment2();
   attrs.cellType = exp.cellType();
   attrs.imagingMode = exp.imagingMode();
     rcValue tmp = exp.lensMag(); attrs.lensMag = (std::string) tmp;
   attrs.otherMag = (std::string) rcValue(exp.otherMag());
   attrs.temperature = (std::string) rcValue(exp.temperature());
   attrs.CO2 = (std::string) rcValue(exp.CO2());
   attrs.O2 = (std::string) rcValue(exp.O2());
   // These values are not used but define values just in case
   attrs.fileName = "Unspecified";
   attrs.inputName = "Unspecified";
   attrs.frameWidth = 0;
   attrs.frameHeight = 0;
   attrs.frameDepth = 0;
   attrs.liveInput = false;
   attrs.liveStorage = false;
   return attrs;
 }
void rcEngineImpl::createCameraPreviewWriters () protected
Definition at line 1082 of file rc_engineimpl.cpp.
References _analysisRect, _previewWriterSizeLimit, _writerManager, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cPreviewWriterGroupStrings, rcWriterManager::createScalarWriter(), rcWriterManager::createWriterGroup(), rcScalarWriter::down_cast(), eGroupSemanticsCameraPreview, eWriterACIPreview, eWriterACIWindow, rcWriter::getDescription(), rcWriter::getName(), getSettingValue(), mPreviewWriterGroup, mSlidingEnergyPreviewWriter, rcWriterManager::optionString(), rcWriter::setDescription(), rcWriter::setExportable(), and rcWriter::setName().
Referenced by startPreview().
 {
   // Create default writer group
   if ( !mPreviewWriterGroup ) {
     mPreviewWriterGroup = _writerManager->createWriterGroup( cPreviewWriterGroupStrings[0],
                                                                                                                         cPreviewWriterGroupStrings[1],
                                                                                                                         eGroupSemanticsCameraPreview );
   }
   if ( !mSlidingEnergyPreviewWriter ) {
     // Keep only a limited amount of values
     mSlidingEnergyPreviewWriter = _writerManager->createScalarWriter( mPreviewWriterGroup,
                                                                                                                                          eWriterACIPreview,
                                                                                                                                          _previewWriterSizeLimit,
                                                                                                                                          _analysisRect,
                                                                                                                                          0.0,
                                                                                                                                          1.0 );
     // Preview only, nothing to export
     mSlidingEnergyPreviewWriter->down_cast()->setExportable( false );
     // Add a human-readable string listing window options to track name and description
     int32 orig = getSettingValue( cAnalysisACISlidingWindowOriginSettingId );
     std::string optionString = rcWriterManager::optionString( eWriterACIWindow,
                                                                                                                          static_cast<rcWriterWindowOrigin>(orig),
                                                                                                                          static_cast<int32>(getSettingValue( cAnalysisACISlidingWindowSizeSettingId ) ) );
     rcWriter* writer = mSlidingEnergyPreviewWriter->down_cast();
     std::string nameWithOptions = writer->getName() + optionString;
     std::string descrWithOptions = writer->getDescription() + optionString;
     writer->setName( nameWithOptions.c_str() );
     writer->setDescription( descrWithOptions.c_str() );
   }
 }
void rcEngineImpl::createGraphicsWriters (bool motionVectors, bool bodyVectors, bool bodyHistoryVectors, bool segmentVectors) protected
Definition at line 1143 of file rc_engineimpl.cpp.
References _analysisRect, _bodyHistoryVectorWriter, _bodyVectorWriter, _exportBodyGraphics, _exportMotionVectors, _graphicsWriterGroup, _motionVectorWriter, _segmentVectorWriter, _writerManager, _writerSizeLimit, cGraphicsWriterGroupStrings, rcWriterManager::createGraphicsWriter(), rcWriterManager::createWriterGroup(), rcGraphicsWriter::down_cast(), eGroupSemanticsGlobalGraphics, eWriterBodyHistoryVector, eWriterBodyVector, eWriterMotionVector, eWriterSegmentVector, rmAssert, and rcWriter::setExportable().
 {
   // Create default visualization writer group
   if ( !_graphicsWriterGroup ) {
     _graphicsWriterGroup = _writerManager->createWriterGroup( cGraphicsWriterGroupStrings[0],
                                                                                                                          cGraphicsWriterGroupStrings[1],
                                                                                                                          eGroupSemanticsGlobalGraphics );
   }
   // Writer for displaying all motion vector graphics
   if ( motionVectors && !_motionVectorWriter ) {
     _motionVectorWriter = _writerManager->createGraphicsWriter( _graphicsWriterGroup,
                                                                                                                              eWriterMotionVector,
                                                                                                                              _writerSizeLimit,
                                                                                                                              _analysisRect );
     _motionVectorWriter->down_cast()->setExportable( _exportMotionVectors );
   }
   // Writer for displaying locomotive body graphics
   if ( bodyVectors && !_bodyVectorWriter ) {
     _bodyVectorWriter = _writerManager->createGraphicsWriter( _graphicsWriterGroup,
                                                                                                                          eWriterBodyVector,
                                                                                                                          _writerSizeLimit,
                                                                                                                          _analysisRect );
     _bodyVectorWriter->down_cast()->setExportable( _exportBodyGraphics );
   }
   // Writer for displaying locomotive body history vectors
   if ( bodyHistoryVectors && !_bodyHistoryVectorWriter ) {
     _bodyHistoryVectorWriter = _writerManager->createGraphicsWriter( _graphicsWriterGroup,
                                                                                                                                         eWriterBodyHistoryVector,
                                                                                                                                         _writerSizeLimit,
                                                                                                                                         _analysisRect );
     _bodyHistoryVectorWriter->down_cast()->setExportable( true );
   }
   // Writer for displaying segmentation vectors
   if ( segmentVectors && !_segmentVectorWriter ) {
     _segmentVectorWriter = _writerManager->createGraphicsWriter( _graphicsWriterGroup,
                                                                                                                                 eWriterSegmentVector,
                                                                                                                                 _writerSizeLimit,
                                                                                                                                 _analysisRect );
     rmAssert(_segmentVectorWriter);
     _segmentVectorWriter->down_cast()->setExportable( true );
   }
 }
void rcEngineImpl::createGraphicsWriters () protected
Definition at line 1124 of file rc_engineimpl.cpp.
References _analysisRect, _energyPlotWriter, _graphicsWriterGroup, _writerManager, _writerSizeLimit, cGraphicsWriterGroupStrings, rcWriterManager::createGraphicsWriter(), rcWriterManager::createWriterGroup(), rcGraphicsWriter::down_cast(), eGroupSemanticsGlobalGraphics, eWriterPlotter, and rcWriter::setExportable().
Referenced by entropyTracker(), modelTracker(), and muscleTracker().
 {
   // Create default visualization writer group
   if ( !_graphicsWriterGroup ) {
     _graphicsWriterGroup = _writerManager->createWriterGroup( cGraphicsWriterGroupStrings[0],
                                                                                                                          cGraphicsWriterGroupStrings[1],
                                                                                                                          eGroupSemanticsGlobalGraphics );
   }
   // Writer for displaying all Plotting
   if (!_energyPlotWriter ) {
     _energyPlotWriter = _writerManager->createGraphicsWriter( _graphicsWriterGroup,
                                                                                                                          eWriterPlotter,
                                                                                                                          _writerSizeLimit,
                                                                                                                          _analysisRect );
     _energyPlotWriter->down_cast()->setExportable( true );
   }
 }
void rcEngineImpl::createSharedWriters () protected
Definition at line 1050 of file rc_engineimpl.cpp.
References _analysisRect, _graphicsWriterGroup, _inputMode, _videoWriter, _writerGroup, _writerManager, _writerSizeLimit, cGraphicsWriterGroupStrings, rcWriterManager::createVideoWriter(), rcWriterManager::createWriterGroup(), cVideoWriterGroupStrings, eCmd, eGroupSemanticsGlobalGraphics, eWriterVideo, and rcAtomicValue< T >::getValue().
Referenced by loadFrames(), and start().
 {
   // Create default image data writer group
   if ( !_writerGroup ) {
     _writerGroup = _writerManager->createWriterGroup( cVideoWriterGroupStrings[0],
                                                                                                          cVideoWriterGroupStrings[1],
                                                                                                          eGroupSemanticsGlobalGraphics );
   }
   // Create default graphics data writer group
   if ( !_graphicsWriterGroup ) {
     _graphicsWriterGroup = _writerManager->createWriterGroup( cGraphicsWriterGroupStrings[0],
                                                                                                                          cGraphicsWriterGroupStrings[1],
                                                                                                                          eGroupSemanticsGlobalGraphics );
   }
   // Create shared writers (all focus areas share these)
   // Writer for displaying video
   if (_inputMode != eCmd)
     {
       rcVideoWriter* temp;
       if ( _videoWriter.getValue(temp) == 0) {
                 _videoWriter = _writerManager->createVideoWriter( _writerGroup,
                                                                                                                  eWriterVideo,
                                                                                                                  _writerSizeLimit,
                                                                                                                  _analysisRect );
       }
     }
 }
void rcEngineImpl::engineAbort (const char * msg) protected
Definition at line 1264 of file rc_engineimpl.cpp.
References _observer, eEngineStopped, rcEngineObserver::notifyError(), and setInternalState().
Referenced by frameInterrupt().
 {
   setInternalState( eEngineStopped );
   _observer->notifyError( msg );
 }
uint32 rcEngineImpl::entropyTracker (rcEngineFocusData * focus, vector< rcWindow > & focusImages, int32 cacheSz) protected
Definition at line 1278 of file rc_engineimpl.cpp.
References _aciOptions, _channelConversion, _frameDepth, _observer, cAnalysisObjectSettingId, cGlobalMotionEstId, createGraphicsWriters(), rcScalarWriter::down_cast(), rcSimilarator::eExhaustive, rcEngineFocusData::energyWriter(), rcSimilarator::eNorm, rcSimilarator::fill(), rcWriter::getName(), getSettingValue(), rcHistoStats::mean(), rcEngineObserver::notifyStatus(), rcEngineProgress::progress(), rcWriterManager::renameEntropyTrack(), rfRegisteredWindows(), rmAssert, and writeEntropyData().
Referenced by analyzeFocusArea().
 {
   // Compute entropy
   uint32 analysisCount = 0;
   vector<double> results;
   double statusUpdateInterval = 1.5;
   // Write Appropriate Track Titles
   rcWriterManager::renameEntropyTrack( focus->energyWriter()->down_cast(), _aciOptions,
                                                                             rcPixel(_frameDepth), _channelConversion );
   // Construct progress message string
   std::string progressMsg = "Computing ";
   progressMsg += focus->energyWriter()->down_cast()->getName();
   progressMsg += "...%.2f%% complete";
   // Create graphics writers if applicable
   createGraphicsWriters();
   rcEngineProgress progressIndicator( this, _observer,
                                                                          progressMsg,
                                                                          statusUpdateInterval );
   rcSimilarator::rcCorrelationDefinition cdl =  rcSimilarator::eNorm;
   // @note optimization if range has stayed the same but not now.
   // @note handle reusing the vectors better
   int32 range = (int) getSettingValue(cGlobalMotionEstId);
   int32 pOpt =  getSettingValue( cAnalysisObjectSettingId);
     if ( progressIndicator.progress( (100.0 * (analysisCount))/focusImages.size() ) ) {
         // Abort
         _observer->notifyStatus( "Analysis stopped" );
     return 0;   }
 #ifdef FIXED
     if (range && ! pOpt)
     {
       rfRegisteredWindows (focusImages, range);
       vector<rcWindow>::iterator wItr = focusImages.begin();
       vector<float> sums;
       for (; wItr !=  focusImages.end(); wItr++)
                 {
                     rcHistoStats h (*wItr);
                     sums.push_back ((float) h.mean());
                 }
     }
 #endif
   rcSimilarator sim(rcSimilarator::eExhaustive,
                                         focusImages[0].depth(), focusImages.size(),
                                         cacheSz, cdl, true, &progressIndicator);
   deque<double> signal;
   sim.fill(focusImages);
   if (sim.entropies(signal, _aciOptions))
     {
             results.resize(0);
       copy(signal.begin(), signal.end(),
                      back_inserter(results));
       rmAssert( results.size() == focusImages.size() );
       analysisCount = results.size();
       writeEntropyData( focus, focusImages, results );
     }
   return analysisCount;
 }
uint32 rcEngineImpl::entropyTrackerWindow (rcEngineFocusData * focus, vector< rcWindow > & focusImages, int32 cacheSz, bool clippedFrameBuf) protected
Definition at line 1352 of file rc_engineimpl.cpp.
References _aciOptions, _channelConversion, _frameDepth, _observer, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cGlobalMotionEstId, rcScalarWriter::down_cast(), eFrameStatusEOF, eFrameStatusOK, rcEngineFocusData::energyPeriodWriter(), rcAnalyzerResult::entropy(), rcAnalyzerOptions::entropyDefinition(), eWriterACIPeriod, eWriterACIWindow, rcEngineFocusData::focusRect(), rcAnalyzerResult::frameBuf(), rcWriter::getDescription(), rcFrameGrabber::getErrorString(), rcAnalyzer::getLastError(), rcWriter::getName(), rcAnalyzer::getNextResult(), getSettingValue(), rcEngineObserver::notifyStatus(), rcWriterManager::optionString(), rcAnalyzerOptions::origin(), rcEngineProgress::progress(), registeredWindows(), rcWriterManager::renameEntropyTrack(), rf1DAutoCorr(), rmAssert, rcAnalyzerOptions::setBound(), rcAnalyzerOptions::setDepth(), rcWriter::setDescription(), rcAnalyzerOptions::setEntropyDefinition(), rcWriter::setName(), rcAnalyzerOptions::setOrigin(), rcAnalyzerOptions::setWindowSize(), rcEngineFocusData::slidingEnergyWriter(), rcFrame::timestamp(), rcAnalyzerOptions::windowSize(), writeTimedScalar(), and rcScalarWriter::writeValue().
Referenced by analyzeFocusArea().
 {
   // Compute sliding window entropy
   uint32 analysisCount = 0;
   double statusUpdateInterval = 1.5;
   int slidingWindowSz = static_cast<int>(getSettingValue( cAnalysisACISlidingWindowSizeSettingId ));
   rcScalarWriter* sWriter = focus->slidingEnergyWriter();
   rcWriter* writer = sWriter->down_cast();
   rcAnalyzerOptions opt;
   // Set result origin
   opt.setOrigin( rcAnalyzerResultOrigin(static_cast<int>(getSettingValue( cAnalysisACISlidingWindowOriginSettingId ))) );
   // Set sliding window size
   opt.setWindowSize( static_cast<unsigned>( slidingWindowSz ) );
   // Set entropy definition
   opt.setEntropyDefinition( _aciOptions );
   // Set clip rect
   if ( !clippedFrameBuf )
     opt.setBound( focus->focusRect() );
   opt.setDepth (focusImages[0].depth());
   // Write Appropriate Track Titles
   rcWriterManager::renameEntropyTrack( writer, opt.entropyDefinition(),
                                                                             rcPixel(_frameDepth), _channelConversion );
   // Add a human-readable string listing window options to track name and description
   std::string optionString = rcWriterManager::optionString( eWriterACIWindow,
                                                                                                                      static_cast<rcWriterWindowOrigin>(opt.origin()),
                                                                                                                      opt.windowSize() );
   std::string name = writer->getName();
   std::string nameWithOptions = writer->getName() + std::string(" Short Term") + optionString;
   std::string descrWithOptions = writer->getDescription() + std::string(" Short Term") + optionString;
   writer->setName( nameWithOptions.c_str() );
   writer->setDescription( descrWithOptions.c_str() );
   // @note optimization if range has stayed the same but not now.
   // @note handle reusing the vectors better
 #if 0
   int32 range = (int) getSettingValue(cGlobalMotionEstId);
   if (range)
     {
       registeredWindows (focusImages, range);
     }
 #endif
   // Create a grabber to read the image vector
   rcVectorGrabber imageGrabber( focusImages, cacheSz );
   // Create an analyzer
   rcAnalyzer analyzer( opt, imageGrabber, true);
   uint32 i = 0;
   rcFrameGrabberStatus status = eFrameStatusOK;
   // Construct progress message string
   std::string progressMsg = "Computing ";
   progressMsg += name;
   progressMsg += "...%.2f%% complete";
   rcEngineProgress progressIndicator( this, _observer,
                                                                          progressMsg,
                                                                          statusUpdateInterval );
   vector<double> signal;
   while ( status != eFrameStatusEOF ) {
     rcAnalyzerResult result;
     status = analyzer.getNextResult( result, true );
     if ( status == eFrameStatusOK ) {
       ++i;
       ++analysisCount;
       double entropy = result.entropy();
       // Ignore undefined values
       if ( entropy == -1.0 )
                 continue;
       signal.push_back (entropy);
       sWriter->writeValue(result.frameBuf()->timestamp(), focus->focusRect(), entropy);
       if ( progressIndicator.progress( (100.0 * i)/(focusImages.size() - static_cast<int>(getSettingValue( cAnalysisACISlidingWindowSizeSettingId ))) ) ) {
                 // Abort
                 // Update elapsed time to refresh display
                 _observer->notifyStatus( "Analysis stopped" );
                 status = eFrameStatusEOF;
       }
       rmAssert( i <= focusImages.size() );
     } else {
       rcFrameGrabberError error = analyzer.getLastError();
       _observer->notifyStatus( rcFrameGrabber::getErrorString( error ).c_str() );
       // Bail out, we don't want to get stuck in an infinite loop
       break;
     }
   }
   {
     rcScalarWriter* sWriter = focus->energyPeriodWriter();
     rcWriter* writer = sWriter->down_cast();
     // Add a human-readable string listing window options to track name and description
     std::string optionString = rcWriterManager::optionString( eWriterACIPeriod,
                                                                                                                          static_cast<rcWriterWindowOrigin>(opt.origin()),
                                                                                                                          opt.windowSize() );
     std::string name = writer->getName();
     std::string nameWithOptions = writer->getName() + std::string(" Short Term") + optionString;
     std::string descrWithOptions = writer->getDescription() + std::string(" Short Term") + optionString;
     writer->setName( nameWithOptions.c_str() );
     writer->setDescription( descrWithOptions.c_str() );
     vector<double> ac (signal.size());
     rf1DAutoCorr (signal.begin(), signal.end(), ac.begin());
     writeTimedScalar (focus, ac, focusImages, sWriter);
   }
   // @note: simple test of correctness of longTermEntropies
   //    cerr << "Size: " << signal.size () << " ? " << analyzer.longTermEntropies().size ();
   //    for (uint32 i = 0; i < signal.size(); i++)
   //      cerr << signal[i] << " ;; " << 1.0f - analyzer.longTermEntropies()[i+2] << endl;
   return analysisCount;
 }
void rcEngineImpl::flushGraphicsWriters () protected
Definition at line 1191 of file rc_engineimpl.cpp.
References _bodyHistoryVectorWriter, _bodyVectorWriter, _energyPlotWriter, _motionVectorWriter, _segmentVectorWriter, and rcGraphicsWriter::flush().
Referenced by analyzeFocusArea().
 {
   // Writer for displaying graphics
   if ( _motionVectorWriter ) {
     _motionVectorWriter->flush();
   }
   if ( _bodyVectorWriter ) {
     _bodyVectorWriter->flush();
   }
   if ( _bodyHistoryVectorWriter ) {
     _bodyHistoryVectorWriter->flush();
   }
   if ( _segmentVectorWriter ) {
     _segmentVectorWriter->flush();
   }
   if ( _energyPlotWriter ) {
     _energyPlotWriter->flush();
   }
 }
void rcEngineImpl::flushSharedWriters () protected
Definition at line 1115 of file rc_engineimpl.cpp.
References _videoWriter, rcVideoWriter::flush(), and rcAtomicValue< T >::getValue().
Referenced by analyzeFocusArea(), and loadFrames().
 {
   // Writer for displaying video
     rcVideoWriter* videoWriter;
     videoWriter = _videoWriter.getValue (videoWriter);
     if (videoWriter != 0)
         videoWriter->flush();
 }
void rcEngineImpl::focusMyocyteSelection (const rcIRect & rect, vector< rc2Fvector > & ends, float & rad) protected
Definition at line 927 of file rc_engineimplsettings.cpp.
References rcRectangle< T >::height(), and rcRectangle< T >::width().
 {
   ends.clear ();
   bool side = rect.width() > rect.height();
 #if 0
   // Focus images are just the windows so ul of the rect has to be subtracted
   if (_focusRotation == 0)
     {
       if (side)
                 {
                     ends.push_back (rc2Fvector(0.0f, (float) rect.height()/2.0f));
                     ends.push_back (rc2Fvector( (float) rect.width(), (float) rect.height()/2.0f));
                     rad = rect.height()/2.0f;
                 }
       else
                 {
                     ends.push_back (rc2Fvector((float) rect.width() / 2.0f, 0.0f));
                     ends.push_back (rc2Fvector((float) rect.width() / 2.0f, (float) rect.height()));
                     rad = (float) rect.width()/2.0f;
                 }
     }
   else
     {
       // Create an affine rectangle at 0 degree and then rotate it
     }
 #endif
 }
std::string rcEngineImpl::focusScript () protected
Definition at line 13 of file rc_engineimplsettings.cpp.
References cAnalysisACI, cAnalysisACISlidingWindow, cAnalysisACISlidingWindowSizeSettingId, cAnalysisCellGeneral, cAnalysisCellMuscle, cAnalysisCellTracking, cAnalysisCellTypeId, cAnalysisFirstFrameSettingId, cAnalysisLabeledFluorescence, cAnalysisLastFrameSettingId, cAnalysisModeSettingId, cAnalysisRectSettingId, cInputMovieFileSettingId, getSettingValue(), rcRectangle< T >::height(), isSettingEnabled(), rcRectangle< T >::origin(), rfToString(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
 {
   std::string script ("perlvisible ");
   if (isSettingEnabled( cInputMovieFileSettingId ) )
     script += std::string (" -movie ") + std::string (getSettingValue( cInputMovieFileSettingId));
   rcRect r = getSettingValue( cAnalysisRectSettingId );
   script += std::string (" -size ") + rfToString (r.width());
   script += std::string (" -size ") + rfToString (r.height());
   script += std::string (" -position ") + rfToString (r.origin().x());
   script += std::string (" -position ") + rfToString (r.origin().y());
   script += std::string (" -duration ") + rfToString (getSettingValue (cAnalysisFirstFrameSettingId));
   script += std::string (" -duration ") + rfToString (getSettingValue (cAnalysisLastFrameSettingId));
   int32 am = getSettingValue( cAnalysisModeSettingId );
   switch (am)
     {
     case cAnalysisACISlidingWindow:
       script += std::string (" -slidingWindow ") + rfToString (getSettingValue( cAnalysisACISlidingWindowSizeSettingId));
             break;
     case cAnalysisACI:
                 script += std::string (" -analysis ") + std::string ("aci");
             break;
     case cAnalysisCellTracking:
       script += std::string (" -analysis ") + std::string ("cell");
       int32 ct = getSettingValue( cAnalysisCellTypeId );
       if (ct == cAnalysisCellGeneral)
                 script += std::string (" -type ") += std::string ("general");
       else if (ct == cAnalysisCellMuscle)
                 script += std::string (" -type ") += std::string ("smooth");
       else if (ct == cAnalysisLabeledFluorescence)
                 script += std::string (" -type ") += std::string ("Flu");
       break;
     }
   script += std::string (" -use ") += std::string ("<your Visible.app>");
   script += std::string (" -result ") += std::string ("/tmp/foo");
   script += std::string (" -report ") += std::string ("csv");
   script += std::string (" -graphics ") += std::string ("no");
   return script;
 }
void rcEngineImpl::frameFlush ()
Definition at line 898 of file rc_engineimpl.cpp.
References _frameFocus, rcEngineFocusData::flushFocusData(), rcAtomicValue< T >::getValue(), and rcAtomicValue< T >::setValue().
Referenced by rcEngineMovieSaver::closeHdlr().
 {
 #ifdef STATE_CHG_DEBUG
   fprintf(stderr, "rcEngineImpl::frameFlush called\n");
 #endif
   rcEngineFocusData* frameFocus;
   _frameFocus.getValue(frameFocus);
   if ( frameFocus ) {
     // Flush writers
     frameFocus->flushFocusData();
     _frameFocus.setValue(0);
   }
 }
void rcEngineImpl::frameInterrupt (const rcAnalyzerResult & result, const std::string & cameraStatus, uint32 missedFramesOnCapture, uint32 missedFramesOnSave, bool frameSaved)
Definition at line 851 of file rc_engineimpl.cpp.
References _currentTime, _firstFrameSaved, _fpsCalculator, _frameFocus, _movieCapture, _startTime, rcFpsCalculator::addTime(), eMovieFileState_Delay, engineAbort(), rcAnalyzerResult::frameBuf(), rcAtomicValue< T >::getValue(), rcTimestamp::now(), processCapturedData(), rmAssert, rcEngineMovieCapture::saveState(), rcAtomicValue< T >::setValue(), rcFrame::timestamp(), and general_exception::what().
Referenced by rcEngineMovieCapture::run().
 {
   if (!result.frameBuf())
     return;
   // process the frame interrupt
   try {
     // Calculate average capture speed
     _fpsCalculator.addTime( result.frameBuf()->timestamp() );
     rmAssert(_movieCapture);
     bool delay = (_movieCapture->saveState() == eMovieFileState_Delay);
     _currentTime = rcTimestamp::now();
     bool first;
     _firstFrameSaved.getValue(first);
     if ((_startTime == 0.0) || delay || (first && frameSaved)) {
       _startTime = _currentTime;
       if (first && frameSaved) {
                 _firstFrameSaved.setValue(false);
                 // Start time is time of first saved frame
                 _startTime =  result.frameBuf()->timestamp();
       }
     }
     rcTimestamp timestamp = _currentTime - _startTime;
     rcEngineFocusData* temp;
     processCapturedData(_frameFocus.getValue(temp), timestamp,
                                                 cameraStatus, result, delay,
                                                 missedFramesOnCapture, missedFramesOnSave,
                                                 frameSaved );
   }
   catch (general_exception& x) {
     engineAbort(x.what());
   }
   catch (...) {
     engineAbort("unknown exception type");
   }
 }
int32 rcEngineImpl::framesLoaded () const protected
Definition at line 1732 of file rc_engineimpl.cpp.
References _fileImages.
Referenced by analyze(), isSettingEditable(), isSettingEnabled(), setSettingValue(), and start().
 {
   return (int32) _fileImages.size();
 }
uint32 rcEngineImpl::framesToAnalyze () const protected
Definition at line 1738 of file rc_engineimpl.cpp.
References _analysisFirstFrame, and _analysisLastFrame.
Referenced by analyze(), and analyzeFocusArea().
 {
   int32 n = 0;
   if ( _analysisFirstFrame >= 0 && _analysisLastFrame >= 0 ) {
     n = _analysisLastFrame - _analysisFirstFrame + 1;
     if ( n < 0 )
       n = 0;
   }
   return n;
 }
const rcEngineAttributes rcEngineImpl::getAttributes (void) virtual
Implements rcEngine.
Definition at line 381 of file rc_engineimpl.cpp.
References _frameDepth, _frameHeight, _frameWidth, _movieCapture, rcEngineMovieCapture::captureStatus(), cInputImageFilesSettingId, cInputModeSettingId, cInputMovieFileSettingId, cOutputMovieFileSettingId, eCmd, eFile, eMovieFileState_Save, rcEngineAttributes::frameDepth, rcEngineAttributes::frameHeight, rcEngineAttributes::frameWidth, rcVideoCaptureStatusReader::getCaptureDepth(), rcVideoCaptureStatusReader::getCaptureRect(), getSettingValue(), rcRectangle< T >::height(), rcEngineAttributes::inputName, isSettingEnabled(), rcEngineAttributes::liveInput, rcEngineAttributes::liveStorage, rmAssert, rcEngineMovieCapture::saveState(), and rcRectangle< T >::width().
 {
   rcEngineAttributes attr;
   int inputMode = getSettingValue( cInputModeSettingId );
   if ( inputMode != eFile && inputMode != eCmd) {
     rmAssert(_movieCapture);
     rcRect captureRect = _movieCapture->captureStatus().getCaptureRect();
     rcPixel captureDepth = _movieCapture->captureStatus().getCaptureDepth();
     attr.frameWidth = captureRect.width();
     attr.frameHeight = captureRect.height();
     attr.frameDepth = captureDepth;
     attr.liveInput = true;
     attr.liveStorage = (_movieCapture->saveState() == eMovieFileState_Save);
     // In capture mode the output movie file name becomes the experiment
     // image input source name
     attr.inputName = (std::string) getSettingValue( cOutputMovieFileSettingId );
   }
   else {
     attr.frameWidth = _frameWidth;
     attr.frameHeight = _frameHeight;
     attr.frameDepth = _frameDepth;
     attr.liveInput = false;
     attr.liveStorage = false;
     // In file mode the input image/movie file name becomes the experiment
     // image input source name
     if (isSettingEnabled( cInputMovieFileSettingId ) )
       attr.inputName = (std::string) getSettingValue( cInputMovieFileSettingId );
     else if ( isSettingEnabled( cInputImageFilesSettingId ) )
       attr.inputName = (std::string) getSettingValue( cInputImageFilesSettingId );
   }
   return attr;
 }
rcTimestamp rcEngineImpl::getElapsedTime (void) virtual
Implements rcEngine.
Definition at line 312 of file rc_engineimpl.cpp.
References _currentTime, _startTime, and assertInitialized().
Referenced by loadFrames(), modelTracker(), muscleTracker(), and setTimeLineRange().
 {
   assertInitialized();
   return _currentTime - _startTime;
 }
int rcEngineImpl::getNSettingCategories (void) virtual
Implements rcEngine.
Definition at line 278 of file rc_engineimpl.cpp.
References _settings, and assertInitialized().
 {
   assertInitialized();
   return _settings.size();
 }
rcSettingCategory rcEngineImpl::getSettingCategory (int categoryNo) virtual
Implements rcEngine.
Definition at line 286 of file rc_engineimpl.cpp.
References _settings, assertInitialized(), and rmAssert.
 {
   assertInitialized();
   rmAssert( uint32(categoryNo) < _settings.size() );
   return _settings[categoryNo];
 }
rcSettingCategory rcEngineImpl::getSettingCategory (char * categoryName) virtual
Definition at line 296 of file rc_engineimpl.cpp.
References _settings, assertInitialized(), and rmAssert.
 {
   assertInitialized();
   rmAssert (categoryName != 0);
   for (uint32 i = 0; i < _settings.size(); i++)
     {
       if (_settings[i].getName () == categoryName)
                 return _settings[i];
     }
   rmAssert (0); // one of the compares must work.
 }
const rcValue rcEngineImpl::getSettingValue (int settingId) virtual
Implements rcSettingSource.
Definition at line 56 of file rc_engineimplsettings.cpp.
References _aciOptions, _aciTemporalSampling, _analysisAffine, _analysisFirstFrame, _analysisLastFrame, _analysisMode, _analysisRect, _analysisTreatmentObject, _cameraInfo, _captureCtrl, _captureLog, _cellType, _channelConversion, _conversionInfo, _developmentGraphicsEnabled, _developmentVideoEnabled, _enableGlobalMotionEst, _exportBodyGraphics, _exportMotionVectors, _frameRate, _imageFileNames, _inputMode, _ippMode, _model2useAbsPathFileName, _motionTrackingBodyHistoryVectorDisplay, _motionTrackingBodyVectorDisplay, _motionTrackingFrameSampling, _motionTrackingMaxSpeed, _motionTrackingMotionVectorDisplay, _motionTrackingTargetSize, _motionTrackingTargetSizeMultiplier, _movieCapture, _movieFile, _msPerContraction, _playbackCtrl, _player, _saveCtrl, _segmentationVectorDisplay, _settingMutex, _showCellPath, _showCellPosition, _showCellText, _slidingWindowOrigin, _slidingWindowSize, _statType, _useMask, _visualizeDevelopment, assertInitialized(), cAnalysisACIMaskSettingId, cAnalysisACIOptionSettingId, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisACIStepSettingId, cAnalysisCellTypeId, cAnalysisChannelSettingId, cAnalysisDevelopmentGraphicsDisplaySettingId, cAnalysisDevelopmentVideoDisplaySettingId, cAnalysisFirstFrameSettingId, cAnalysisLastFrameSettingId, cAnalysisModeSettingId, cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId, cAnalysisMotionTrackingBodyVectorDisplaySettingId, cAnalysisMotionTrackingFrameSampleSettingId, cAnalysisMotionTrackingMotionVectorDisplaySettingId, cAnalysisMotionTrackingMultiplierSettingId, cAnalysisMotionTrackingSampleSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisMotionTrackingStepSettingId, cAnalysisMotionTrackingTargetSettingId, cAnalysisMuscleAutoGenPeriodId, cAnalysisMuscleSegmentationVectorDisplaySettingId, cAnalysisObjectSettingId, cAnalysisRectSettingId, cAnalysisStatTypeId, rcEngineMovieCapture::captureStatus(), cCameraAcquireDelayTimeSettingId, cCameraAcquireTimeSettingId, cCameraFrameRateSettingId, cExportBodyGraphicsSettingId, cExportMotionVectorsSettingId, cFrameRateSettingId, cGlobalMotionEstId, cImagePreMappingSettingId, cInputBinningSettingId, cInputCameraHeaderSettingId, cInputConversionHeaderSettingId, cInputGainSettingId, cInputImageFilesSettingId, cInputModeSettingId, cInputMovieFileSettingId, cInputMovieGeneratorSettingId, cInputShutterSettingId, cOutputMovieFileSettingId, cPlaybackCtrlSettingId, cTemplateFileNameId, rcMoviePlaybackCtrl::ctrlInfo(), cVisualizeCellPathSettingId, cVisualizeCellPositionSettingId, cVisualizeCellTextSettingId, cVisualizeDevelopmentSettingId, cVisualizeFocusRotationSettingId, eCamera, rcSettingInfo::eCurrentStateStopped, eMoviePlaybackState_Exit, rcVideoCaptureCtrlReader::getBinning(), rcVideoCaptureStatusReader::getCaptureRect(), rcMoviePlaybackCtrlReader::getCtrlInfo(), rcVideoCaptureCtrlReader::getDecimationRate(), rcMovieSaveCtrlReader::getFrameCaptureDelayTime(), rcMovieSaveCtrlReader::getFrameCaptureTime(), rcVideoCaptureCtrlReader::getGain(), rcMovieSaveCtrlReader::getOutputFileName(), rcVideoCaptureCtrlReader::getShutter(), rcVideoCaptureCtrlReader::getSlidingWindowOrigin(), rcVideoCaptureCtrlReader::getSlidingWindowSize(), rcMoviePlaybackStatusReader::getState(), lock(), rcEngineMoviePlayback::playbackStatus(), rcEngineMoviePlayback::reset(), and rmAssert.
Referenced by analyze(), analyzeFocusArea(), createCameraPreviewWriters(), entropyTracker(), entropyTrackerWindow(), focusScript(), getAttributes(), groupStatistics(), ipp(), isEntire(), loadFrames(), modelTracker(), muscleTracker(), operatingOnLiveInput(), processCapturedData(), produceDebugResults(), and start().
 {
     rcLock lock( _settingMutex);
     assertInitialized();
     switch (settingId)
     {
         case cInputModeSettingId:
                     return _inputMode;
             case cTemplateFileNameId:
                                      return _model2useAbsPathFileName;
         case cFrameRateSettingId:
             return _frameRate;
         case cCameraFrameRateSettingId:
             return (int)_captureCtrl.getDecimationRate();
         case cCameraAcquireTimeSettingId:
             return (int)_saveCtrl.getFrameCaptureTime();
         case cCameraAcquireDelayTimeSettingId:
             return (int)_saveCtrl.getFrameCaptureDelayTime();
         case cInputMovieFileSettingId:
             return _movieFile;
         case cOutputMovieFileSettingId:
             return _saveCtrl.getOutputFileName();
         case cInputImageFilesSettingId:
             return _imageFileNames;
         case cAnalysisRectSettingId:
             if (_inputMode == eCamera) {
                 rmAssert(_movieCapture);
                 return _movieCapture->captureStatus().getCaptureRect();
             }
             else
                 return _analysisRect;
         case cAnalysisACIOptionSettingId:
             return _aciOptions;
         case cAnalysisACISlidingWindowSizeSettingId:
             if (_inputMode == eCamera)
                 return _captureCtrl.getSlidingWindowSize();
             else
                 return _slidingWindowSize;
         case cAnalysisACISlidingWindowOriginSettingId:
             if (_inputMode == eCamera)
                 return int(_captureCtrl.getSlidingWindowOrigin());
             else
                 return int(_slidingWindowOrigin);
     case cAnalysisMotionTrackingSampleSettingId:
     case cAnalysisACIStepSettingId:
       return _aciTemporalSampling;
     case cAnalysisACIMaskSettingId:
       return _useMask;
     case cImagePreMappingSettingId:
       return (_ippMode);
         case cAnalysisMotionTrackingTargetSettingId:
             return _motionTrackingTargetSize;
     case   cAnalysisMotionTrackingMultiplierSettingId:
       return _motionTrackingTargetSizeMultiplier;
         case cAnalysisMotionTrackingSpeedSettingId:
             return _motionTrackingMaxSpeed;
         case cAnalysisMotionTrackingMotionVectorDisplaySettingId:
             return _motionTrackingMotionVectorDisplay;
         case cAnalysisMuscleSegmentationVectorDisplaySettingId:
             return _segmentationVectorDisplay;
         case cAnalysisMotionTrackingBodyVectorDisplaySettingId:
             return _motionTrackingBodyVectorDisplay;
         case cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId:
             return _motionTrackingBodyHistoryVectorDisplay;
         case cAnalysisMotionTrackingFrameSampleSettingId:
             return _motionTrackingFrameSampling;
         case cAnalysisMotionTrackingStepSettingId:
             return _aciTemporalSampling;
         case cInputGainSettingId:
         {
             int gain = _captureCtrl.getGain();
             return gain;
         }
         case cInputShutterSettingId:
         {
             int shutter = _captureCtrl.getShutter();
             return shutter;
         }
         case cInputBinningSettingId:
         {
             int binning = _captureCtrl.getBinning();
             return binning;
         }
         case cPlaybackCtrlSettingId:
             if (_player && _player->playbackStatus().getState() ==
                     eMoviePlaybackState_Exit) {
                 int ctrlInfo = _playbackCtrl.getCtrlInfo();
                 ctrlInfo |= rcSettingInfo::eCurrentStateStopped;
                 _playbackCtrl.ctrlInfo(ctrlInfo);
                 _player->reset();
             }
             return _playbackCtrl.getCtrlInfo();
         case cAnalysisModeSettingId:
             return _analysisMode;
         case cAnalysisCellTypeId:
             return _cellType;
         case cAnalysisStatTypeId:
             return _statType;
         case cAnalysisMuscleAutoGenPeriodId:
             return _msPerContraction;
         case cVisualizeCellTextSettingId:
             return _showCellText;
         case cVisualizeCellPositionSettingId:
             return _showCellPosition;
         case cVisualizeCellPathSettingId:
             return _showCellPath;
         case cExportMotionVectorsSettingId:
             return _exportMotionVectors;
         case cExportBodyGraphicsSettingId:
             return _exportBodyGraphics;
         case cVisualizeFocusRotationSettingId:
             return _analysisAffine;
         case cAnalysisFirstFrameSettingId:
             return _analysisFirstFrame;
         case cAnalysisLastFrameSettingId:
             return _analysisLastFrame;
         case cAnalysisChannelSettingId:
             return _channelConversion;
         case cInputMovieGeneratorSettingId:
             return _captureLog;
         case cInputCameraHeaderSettingId:
             return _cameraInfo;
         case cInputConversionHeaderSettingId:
             return _conversionInfo;
     case cAnalysisObjectSettingId:
       return _analysisTreatmentObject;
         //        case cAnalysisTreatmentObjectSizeSettingId:
         //            return _analysisTreatmentObjectSize;
         case cAnalysisDevelopmentVideoDisplaySettingId:
             return _developmentVideoEnabled;
             break;
         case cAnalysisDevelopmentGraphicsDisplaySettingId:
             return _developmentGraphicsEnabled;
         case cVisualizeDevelopmentSettingId:
             return _visualizeDevelopment;
     case   cGlobalMotionEstId:
       return _enableGlobalMotionEst;
     }
     return 0;
 }
rcTimestamp rcEngineImpl::getStartTime (void) virtual
Implements rcEngine.
Definition at line 320 of file rc_engineimpl.cpp.
References _startTime, and assertInitialized().
 {
   assertInitialized();
   return _startTime;
 }
rcEngineState rcEngineImpl::getState (void) virtual
Implements rcEngine.
Definition at line 334 of file rc_engineimpl.cpp.
References _state, and rcAtomicValue< T >::getValue().
Referenced by assertInitialized(), rcEngineMovieSaver::closeHdlr(), rcEngineMovieSaver::delayHdlr(), rcEngineMovieSaver::doneHdlr(), internalReset(), isSettingEditable(), isSettingEnabled(), loadFrames(), loadImages(), loadMovie(), processCapturedData(), rcEngineImpl(), rcEngineMovieCapture::run(), setInternalState(), shutdown(), unlockedReset(), and rcEngineMovieSaver::waitHdlr().
 {
   rcEngineState dummy;
   return _state.getValue(dummy);
 }
template<class T > double rcEngineImpl::groupStatistics (const vector< T > & a) protected
Definition at line 77 of file rc_engineimpl.cpp.
References cAnalysisStatMean, cAnalysisStatMedian, cAnalysisStatTypeId, getSettingValue(), rfMean(), rfMedian(), and rmAssert.
 {
   int32 stat = getSettingValue( cAnalysisStatTypeId );
   if (stat == cAnalysisStatMean)
     {
       return (double) rfMean (a);
     }
   else if (stat == cAnalysisStatMedian)
     {
       return (double) rfMedian (a);
     }
   else
     {
       rmAssert (0);
     }
 }
void rcEngineImpl::initialize (rcEngineObserver * observer) virtual
Implements rcEngine.
Definition at line 169 of file rc_engineimpl.cpp.
References _analyzer, _analyzerThread, _captureCtrl, _captureThread, _importer, _importThread, _movieCapture, _observer, _playbackCtrl, _playbackThread, _player, _resourceFolderPath, _saveCtrl, _settings, _videoCacheProgress, _writerManager, analysisSettingsSpec, captureSettingsSpec, eEngineStopped, eHighPriority, eNormalPriority, observer(), rcExecWithShmem::pathName(), rcEngineImporter, setInternalState(), rcThread::setPriority(), and visualizationSettingsSpec.
 {
     _resourceFolderPath = rcExecWithShmem::pathName ();
   // save the pointer to the instance of the engine observer
   _observer = observer;
   // create writer manager
   _writerManager = new rcWriterManager( observer );
   // create setting categories given the specs defined above
   _settings.clear ();
   _settings.insert (_settings.begin(), rcSettingCategory( this , &visualizationSettingsSpec ));
   _settings.insert (_settings.begin (), rcSettingCategory( this , &captureSettingsSpec ));
   _settings.insert (_settings.begin(), rcSettingCategory( this , &analysisSettingsSpec ));
   // set the initial state once we're done setting up
   //    (notifies the observer).
   setInternalState( eEngineStopped );
   _captureThread = 0;
   _importThread = 0;
   _analyzerThread = 0;
   _playbackThread = 0;
   _movieCapture = new rcEngineMovieCapture( this, _captureCtrl,
                                                                                      _saveCtrl, _observer );
   _captureThread = new rcThread( _movieCapture );
   _captureThread->setPriority( eHighPriority );
   _importer = new rcEngineImporter( this );
   _importThread = new rcThread( _importer );
   _importThread->setPriority( eHighPriority );
   _analyzer = new rcEngineAnalyzer( this );
   _analyzerThread = new rcThread( _analyzer );
   _analyzerThread->setPriority( eNormalPriority );
   _player = new rcEngineMoviePlayback( this, _playbackCtrl, _observer,
                                                                             100.0, false );
   _playbackThread = new rcThread( _player );
   _playbackThread->setPriority( eNormalPriority );
   // rev0 TOC generation is the only slow video cache operation now
   _videoCacheProgress = new rcEngineProgress( this, _observer,
                                                                                          "Loading frames...%.2f%% complete",
                                                                                          rcTimestamp( 1.5 ) );
 }
void rcEngineImpl::internalReset () virtual
Definition at line 523 of file rc_engineimpl.cpp.
References _aciOptions, _aciTemporalSampling, _analysisFirstFrame, _analysisLastFrame, _analysisMode, _analysisTreatmentObject, _cellType, _channelConversion, _cLineEndFrame, _cLineRectSize, _cLineRectTL, _cLineStartFrame, _developmentGraphicsEnabled, _developmentVideoEnabled, _enableGlobalMotionEst, _energyGraphicsEnabled, _exportBodyGraphics, _exportEnergyGraphics, _exportMotionVectors, _frameRate, _imageFileNames, _inputMode, _inputSource, _ippMode, _movieFile, _msPerContraction, _playbackCtrl, _previewWriterSizeLimit, _saveCtrl, _segmentationVectorDisplay, _showCellPath, _showCellPosition, _showCellText, _slidingWindowOrigin, _slidingWindowSize, _statType, _useMask, _visualizeDevelopment, _writerSizeLimit, cAnalysisACISlidingWindow, cAnalysisCellGeneral, cAnalysisMuscleMsPerContractionDefault, cAnalysisStatMedian, rcMoviePlaybackCtrl::ctrlInfo(), rcSimilarator::eACI, eAnalyzerResultOriginCenter, rcSettingInfo::eCurrentStateFwd, rcSettingInfo::eCurrentStateStopped, eEngineUninitialized, eFile, eIPPNone, eMovie, getState(), rcMovieSaveCtrl::movieFileName(), rcMovieSaveCtrl::outputFileName(), PRINT_STATE_CHANGE, rcSelectAverage, setState(), and unlockedReset().
Referenced by rcEngineImpl().
 {
   PRINT_STATE_CHANGE("internalReset", getState(), eEngineUninitialized);
   setState(eEngineUninitialized);
   _slidingWindowSize = 3;
   _slidingWindowOrigin = eAnalyzerResultOriginCenter;
   _analysisMode = cAnalysisACISlidingWindow;
   _cellType = cAnalysisCellGeneral;
   _statType = cAnalysisStatMedian;
   _msPerContraction = cAnalysisMuscleMsPerContractionDefault;
   _aciOptions = rcSimilarator::eACI;
   // set the initial (default) setting values
   _inputSource = eMovie;
   _inputMode = eFile;
   _ippMode = eIPPNone;
   _frameRate = 0;
   _movieFile = "";
   _imageFileNames = "";
   _saveCtrl.outputFileName("");
   _saveCtrl.movieFileName("");
   _imageFileNames = "";
   _writerSizeLimit = INT_MAX;
   _previewWriterSizeLimit = 512;
   _playbackCtrl.ctrlInfo(rcSettingInfo::eCurrentStateStopped |
                                                  rcSettingInfo::eCurrentStateFwd | 1);
   _showCellText = true;
   _showCellPosition = true;
   _showCellPath = false;
   _aciTemporalSampling = 1;
   _segmentationVectorDisplay = true;
   _exportMotionVectors = false;
   _exportBodyGraphics = true;
   _analysisFirstFrame = -1;
   _analysisLastFrame = -1;
   _channelConversion = rcSelectAverage;
   _analysisTreatmentObject = false;
   _developmentVideoEnabled = false;
   _developmentGraphicsEnabled = false;
   _energyGraphicsEnabled = false;
   _exportEnergyGraphics = false;
   _visualizeDevelopment = false;
   _cLineRectTL = rcIPair (-1, -1);
   _cLineRectSize = rcIPair (-1, -1);
   _cLineStartFrame = -1;
   _cLineEndFrame = -1;
   _enableGlobalMotionEst = 0;
   _useMask = 0;
   unlockedReset();
 }
void rcEngineImpl::ipp (const rcWindow & image, rcWindow & dst, rcTimestamp & current) protected
Definition at line 490 of file rc_engineimplload.cpp.
References _channelConversion, _videoCacheP, cImagePreMappingSettingId, rcWindow::depth(), eIPPNone, rcWindow::frameBuf(), getSettingValue(), rcWindow::isGray(), rcPixel16, rcPixel32, rcPixel8, rfImageConvert32to8(), rmUnused, and rcFrame::setTimestamp().
Referenced by analyzeFocusArea(), and loadFrames().
 {
   rmUnused (current);
   // What the user has selected
   rcIPPMode userMode = (rcIPPMode) (int) getSettingValue(cImagePreMappingSettingId);
   // VideoCache case: Do not access frameData. Access for invalidate cache
   if (userMode == eIPPNone && _videoCacheP)
     {
       image = tmp;
       image.frameBuf()->setTimestamp (current);
       return;
     }
   if (userMode == eIPPNone && (tmp.depth() == rcPixel8 || !tmp.isGray ()))
     {
       image = tmp;
       image.frameBuf()->setTimestamp (current);
       return;
     }
   if (userMode == eIPPNone && tmp.depth() == rcPixel16)
     {
       image = tmp;
       image.frameBuf()->setTimestamp (current);
       return;
     }
   if (userMode == eIPPNone && tmp.depth() == rcPixel32)
     {
       image = rfImageConvert32to8 (tmp, _channelConversion);
       image.frameBuf()->setTimestamp (current);
       return;
     }
 }
bool rcEngineImpl::isEntire ()
Definition at line 1902 of file rc_engineimpl.cpp.
References _frameHeight, _frameWidth, cAnalysisRectSettingId, getSettingValue(), and rmAssert.
 {
   rmAssert (_frameWidth <= 0 || _frameHeight <= 0);
   rcRect aRect = getSettingValue( cAnalysisRectSettingId );
   rcRect iRect = rcRect( 0, 0, _frameWidth, _frameHeight );
   return aRect == iRect;
 }
bool rcEngineImpl::isSettingEditable (int settingId) virtual
Implements rcSettingSource.
Definition at line 823 of file rc_engineimplsettings.cpp.
References _inputMode, _movieCapture, _offsetsToFirst, _processCount, _settingMutex, _videoCacheP, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisCellTypeId, cAnalysisFirstFrameSettingId, cAnalysisLastFrameSettingId, cAnalysisModeSettingId, cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId, cAnalysisMotionTrackingBodyVectorDisplaySettingId, cAnalysisMotionTrackingFrameSampleSettingId, cAnalysisMotionTrackingMotionVectorDisplaySettingId, cAnalysisMotionTrackingSampleSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisMotionTrackingStepSettingId, cAnalysisMotionTrackingTargetSettingId, cAnalysisMuscleAutoGenPeriodId, cAnalysisMusclePeriodId, cAnalysisMuscleSegmentationVectorDisplaySettingId, cAnalysisRectSettingId, cCameraAcquireDelayTimeSettingId, cCameraAcquireTimeSettingId, cCameraFrameRateSettingId, cFrameRateSettingId, cGlobalMotionEstId, cInputImageFilesSettingId, cInputModeSettingId, cInputMovieFileSettingId, cOutputMovieFileSettingId, cPlaybackCtrlSettingId, cVisualizeFocusRotationSettingId, eCamera, eCmd, eEnginePlayback, eEngineRunning, eEngineStopped, eFile, eMovieFileState_Save, framesLoaded(), getState(), lock(), and rcEngineMovieCapture::saveState().
 {
     rcLock lock( _settingMutex);
     switch (settingId)
     {
         case cFrameRateSettingId:
             if ( _inputMode == eFile || _inputMode == eCmd )
                 return _processCount == 0;
             else
                 return false;
         case cCameraFrameRateSettingId:
         case cCameraAcquireTimeSettingId:
         case cCameraAcquireDelayTimeSettingId:
         case cOutputMovieFileSettingId:
             return _inputMode == eCamera &&
             getState() == eEngineStopped;
         case cInputMovieFileSettingId:
         case cInputImageFilesSettingId:
         case cInputModeSettingId:
             return _processCount == 0;
         case cAnalysisRectSettingId:
         case cVisualizeFocusRotationSettingId:
         case cAnalysisMotionTrackingMotionVectorDisplaySettingId:
         case cAnalysisMotionTrackingBodyVectorDisplaySettingId:
         case cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId:
         case cAnalysisMotionTrackingStepSettingId:
         case cAnalysisMotionTrackingFrameSampleSettingId:
         case cAnalysisMotionTrackingTargetSettingId:
         case cAnalysisMuscleAutoGenPeriodId:
         case cAnalysisMuscleSegmentationVectorDisplaySettingId:
         case cAnalysisMusclePeriodId:
         case cAnalysisCellTypeId:
         case cAnalysisModeSettingId:
         case cAnalysisMotionTrackingSpeedSettingId:
             if ((_inputMode != eFile) || (getState() == eEnginePlayback))
                 return false;
             break;
         case cPlaybackCtrlSettingId:
             if ((_inputMode != eFile) || !_videoCacheP)
                 return false;
             break;
             // Disable these until right default values have been determined
         case cAnalysisMotionTrackingSampleSettingId:
             return false;
         case cAnalysisACISlidingWindowSizeSettingId:
         case cAnalysisACISlidingWindowOriginSettingId:
             if (_inputMode != eFile) {
                 if ( _movieCapture->saveState() == eMovieFileState_Save )
                     return false;
             }
             break;
         case cAnalysisFirstFrameSettingId:
         case cAnalysisLastFrameSettingId:
             return (framesLoaded() > 0);
         // We compute this at load time. Disable it after the first time.
         case cGlobalMotionEstId:
             return (framesLoaded() > 0 && _offsetsToFirst.size() == 0);
     }
     return getState() != eEngineRunning;
 }
bool rcEngineImpl::isSettingEnabled (int settingId) virtual
Implements rcSettingSource.
Definition at line 683 of file rc_engineimplsettings.cpp.
References _analysisMode, _analysisTreatmentObject, _batchMode, _captureCtrl, _cellType, _frameDepth, _inputMode, _inputSource, _settingMutex, assertInitialized(), cAnalysisACI, cAnalysisACIOptionSettingId, cAnalysisACISlidingWindow, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisACIStepSettingId, cAnalysisCellGeneral, cAnalysisCellMuscle, cAnalysisCellMuscleSelected, cAnalysisCellTracking, cAnalysisCellTypeId, cAnalysisChannelSettingId, cAnalysisDevelopmentGraphicsDisplaySettingId, cAnalysisDevelopmentVideoDisplaySettingId, cAnalysisFirstFrameSettingId, cAnalysisLastFrameSettingId, cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId, cAnalysisMotionTrackingBodyVectorDisplaySettingId, cAnalysisMotionTrackingFrameSampleSettingId, cAnalysisMotionTrackingMotionVectorDisplaySettingId, cAnalysisMotionTrackingSampleSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisMotionTrackingTargetSettingId, cAnalysisMuscleAutoGenPeriodId, cAnalysisMusclePeriodId, cAnalysisMuscleSegmentationVectorDisplaySettingId, cAnalysisObjectSettingId, cAnalysisRectSettingId, cCameraAcquireDelayTimeSettingId, cCameraAcquireTimeSettingId, cCameraFrameRateSettingId, cFrameRateSettingId, cGlobalMotionEstId, cInputBinningSettingId, cInputCameraHeaderSettingId, cInputConversionHeaderSettingId, cInputGainSettingId, cInputImageFilesSettingId, cInputMovieFileSettingId, cInputMovieGeneratorSettingId, cInputShutterSettingId, cOutputMovieFileSettingId, cPlaybackCtrlSettingId, cVisualizeDevelopmentSettingId, cVisualizeFocusRotationSettingId, developerDebugging(), eCamera, eCmd, eEngineUninitialized, eFile, eImages, eLineageProcessing, eMacroDRGdiffusionProcessing, eMovie, eNoProcessingSelected, framesLoaded(), rcVideoCaptureCtrlReader::getSlidingWindowEnabled(), getState(), lock(), rcPixel16, and rcPixel32.
Referenced by focusScript(), getAttributes(), and isSettingPersistable().
 {
   if (_inputMode == eCmd) return true;
   rcLock lock( _settingMutex);
   assertInitialized();
   switch (settingId)
     {
     case cInputMovieFileSettingId:
       return ((_inputMode == eFile && _inputSource == eMovie) ||
                             (_batchMode && _inputMode == eCmd && _inputSource == eMovie));
       //@note: batch mode does not suppport image file set yet
     case cInputImageFilesSettingId:
             return ((_inputMode == eFile && _inputSource == eImages) ||
                             (_batchMode && _inputMode == eCmd && _inputSource == eImages));
     case cCameraFrameRateSettingId:
     case cCameraAcquireTimeSettingId:
     case cCameraAcquireDelayTimeSettingId:
     case cOutputMovieFileSettingId:
     case cInputGainSettingId:
     case cInputShutterSettingId:
     case cInputBinningSettingId:
       return _inputMode == eCamera;
     case cFrameRateSettingId:
       return _inputMode != eCamera;
     case cAnalysisRectSettingId:
     case cVisualizeFocusRotationSettingId:
       return getState() != eEngineUninitialized;
     case cAnalysisACISlidingWindowSizeSettingId:
     case cAnalysisACISlidingWindowOriginSettingId:
       if (_inputMode == eCamera)
                 return  _captureCtrl.getSlidingWindowEnabled();
       else
                 return _analysisMode == cAnalysisACISlidingWindow;
     case cAnalysisACIStepSettingId:
       return getState() != eEngineUninitialized &&
             _inputMode == eFile &&
             (_analysisMode == cAnalysisACI || _analysisMode == cAnalysisACISlidingWindow ||
              _analysisMode == cAnalysisCellTracking );
     case   cGlobalMotionEstId:
     case cAnalysisACIOptionSettingId:
       return getState() != eEngineUninitialized &&
             _inputMode == eFile &&
             (_analysisMode == cAnalysisACI || _analysisMode == cAnalysisACISlidingWindow);
     case cPlaybackCtrlSettingId:
       return getState() != eEngineUninitialized;
     case cAnalysisObjectSettingId:   // Used to indicate Lineage Processing and other options
         {
             switch (_analysisTreatmentObject)
             {
                 case eLineageProcessing:
                     return getState() != eEngineUninitialized &&
                     _analysisMode == cAnalysisCellTracking && _cellType == cAnalysisCellGeneral;
                 case eMacroDRGdiffusionProcessing:
                     return getState() != eEngineUninitialized && _analysisMode == cAnalysisACI;
                 case eNoProcessingSelected:
                 default:
                     return getState() != eEngineUninitialized &&
                     (_analysisMode == cAnalysisACI
                      ||
                      (_analysisMode == cAnalysisCellTracking && _cellType == cAnalysisCellGeneral));
             }
         }
     case cAnalysisMotionTrackingMotionVectorDisplaySettingId:
     case cAnalysisMotionTrackingBodyVectorDisplaySettingId:
     case cAnalysisMotionTrackingTargetSettingId:
     case cAnalysisCellTypeId:
       return getState() != eEngineUninitialized &&  _analysisMode == cAnalysisCellTracking;
     case cAnalysisMotionTrackingSpeedSettingId:
       return getState() != eEngineUninitialized &&  _analysisMode == cAnalysisCellTracking &&
             ! (_cellType == cAnalysisCellMuscle || _cellType == cAnalysisCellMuscleSelected);
     case cAnalysisMuscleAutoGenPeriodId:
     case cAnalysisMuscleSegmentationVectorDisplaySettingId:
       return getState() != eEngineUninitialized &&
             _analysisMode == cAnalysisCellTracking &&
             (_cellType == cAnalysisCellMuscle || _cellType == cAnalysisCellMuscleSelected);
     case cAnalysisMusclePeriodId:
       return getState() != eEngineUninitialized &&
             _analysisMode == cAnalysisCellTracking &&
             _cellType == cAnalysisCellMuscle;
       // This is not needed now, it can be enabled for internal debugging
     case cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId:
       if (!developerDebugging () )
                 return getState() != eEngineUninitialized && _analysisMode == cAnalysisCellTracking;
       else
                 return false;
       // Disable these until right default values have been determined
     case cAnalysisMotionTrackingFrameSampleSettingId:
     case cAnalysisMotionTrackingSampleSettingId:
       return false;
     case cAnalysisFirstFrameSettingId:
     case cAnalysisLastFrameSettingId:
       return (_inputMode == eFile);
     case cAnalysisChannelSettingId:
             return (_inputMode == eFile || _inputMode == eCmd) && (framesLoaded() > 0) &&
             (_frameDepth == rcPixel32 || _frameDepth == rcPixel16);
     case cInputMovieGeneratorSettingId:
       return true;
     case cInputCameraHeaderSettingId:
       return true;
     case cInputConversionHeaderSettingId:
       return (_inputMode == eFile);
     case cAnalysisDevelopmentVideoDisplaySettingId:
     case cAnalysisDevelopmentGraphicsDisplaySettingId:
     case cVisualizeDevelopmentSettingId:
       return developerDebugging();
     }
   return true;
 }
bool rcEngineImpl::isSettingPersistable (int settingId) virtual
Implements rcSettingSource.
Definition at line 894 of file rc_engineimplsettings.cpp.
References _inputMode, _settingMutex, assertInitialized(), cFrameRateSettingId, cInputImageFilesSettingId, cInputMovieFileSettingId, eCamera, eCmd, isSettingEnabled(), and lock().
 {
     bool enabled = isSettingEnabled( settingId );
     rcLock lock( _settingMutex);
     assertInitialized();
     bool persist = false;
     switch ( settingId )
     {
             // Persist these so file import works
         case cFrameRateSettingId:
             persist = enabled;
             break;
         case cInputImageFilesSettingId:
             if ( enabled && _inputMode != eCmd )
           persist = enabled;
             break;
         case cInputMovieFileSettingId:
             if ( enabled || _inputMode == eCamera )
                 persist = true;
             break;
         default:
             persist = false;
             break;
     }
     return persist;
 }
bool rcEngineImpl::isTrackingPaused () inline protected
Definition at line 280 of file rc_engineimpl.h.
         {
             bool tmp (false);
             return _isPausedToggle.getValue (tmp);
         }
int rcEngineImpl::loadFrames (rcFrameGrabber & grabber, rcFrameGrabberError & error) protected
Definition at line 54 of file rc_engineimplload.cpp.
References _analysisFirstFrame, _analysisLastFrame, _currentTime, _fileImages, _frameHeight, _frameWidth, _inputMode, _observer, _processCount, _startTime, _videoCacheP, _videoWriter, rcEngineObserver::acceptingImageBlits(), cAnalysisRectSettingId, createSharedWriters(), cZeroTime, rcWindow::depth(), eCmd, eEngineRunning, eEngineShuttingDown, eEngineStopped, eFrameStatusOK, endl(), eVideoCacheStatusOK, flushSharedWriters(), rcFrameGrabber::frameCount(), rcVideoCache::frameHeight(), rcVideoCache::frameIndexToTimestamp(), rcVideoCache::frameWidth(), getElapsedTime(), rcVideoCache::getErrorString(), rcFrameGrabber::getLastError(), rcFrameGrabber::getNextFrame(), getSettingValue(), getState(), rcAtomicValue< T >::getValue(), rcFrame::height(), rcRectangle< T >::height(), ipp(), rcFrameGrabber::isValid(), lastMovieUpdateTime, rcEngineObserver::notifyAnalysisRect(), rcEngineObserver::notifyBlitData(), rcEngineObserver::notifyStatus(), rcEngineObserver::notifyTime(), rcEngineObserver::notifyTimelineRange(), rcEngineObserver::notifyVideoRect(), rcTimestamp::now(), rmAssert, rmDim, rcTimestamp::secs(), setFrameSize(), setInternalState(), setSettingValue(), rcFrameGrabber::start(), rcFrameGrabber::stop(), updateHeaderLogs(), updateMovieInterval, rcFrame::width(), rcRectangle< T >::width(), and rcVideoWriter::writeValue().
Referenced by loadImages(), and loadMovie().
 {
     error = grabber.getLastError();
     int i = 0;
     // Remove old images
     if ( ! _fileImages.empty() )
         _fileImages.clear();
     rcTimestamp duration = rcTimestamp::now();
     // Grab everything
     if ( grabber.isValid() && grabber.start())
     {
         uint32 frameMax = grabber.frameCount();
         const double updateStatusInterval = 1.5; // Status display update interval in seconds
         const double updateMovieInterval = 3.0;  // Movie display update interval in seconds
         _currentTime = 0.0;
         createSharedWriters();
     // Gentlemen, start your engines
         if (_inputMode != eCmd)
             setInternalState( eEngineRunning );
         ++_processCount;
     // Timestamps for last updates
     // Initial value will cause an immediate update
         rcTimestamp lastStatusUpdateTime = rcTimestamp::now() - updateStatusInterval;
         rcTimestamp lastMovieUpdateTime = lastStatusUpdateTime - updateMovieInterval;
     // Time stamp of previous frame
         rcTimestamp prevTimeStamp = cZeroTime;
         bool firstFrame = true;
     // Set the analysis rect to zero-default for all modes
         setSettingValue( cAnalysisRectSettingId, rcRect( 0, 0, 0, 0 ) );
     // Note: infinite loop
         for( i = 0; ; ++i )
         {
             rcTimestamp curTimeStamp;
             rcRect videoFrame;
             rcWindow image, tmp;
             rcVideoCacheError error;
             rcSharedFrameBufPtr framePtr;
             rcFrameGrabberStatus status = grabber.getNextFrame( framePtr, true );
             if ( status != eFrameStatusOK )
             {
                 break;
             }
             if ( getState() == eEngineShuttingDown )
             {
                 break;
             }
         // @note
         // Note curTimeStamp fetching under VideoCache and normal fetch
         // Any access to the pixel data or time stamp of the frames cached will force a frame load.
         // ipp process needs to make sure that it only does that if setting is to other than none.
             if (_videoCacheP)
             {
                 if (_videoCacheP->frameIndexToTimestamp(i,curTimeStamp,&error) != eVideoCacheStatusOK)
                 {
                     cerr << "vfload: " << i << ": " << rcVideoCache::getErrorString(error) << endl;
                     rmAssert(0);
                 }
                 videoFrame = rcRect( 0, 0, _videoCacheP->frameWidth(),
                     _videoCacheP->frameHeight() );
                 tmp = rcWindow( *_videoCacheP, i );
             }
             else
             {
                 videoFrame = rcRect( 0, 0, framePtr->width(), framePtr->height() );
                 tmp = rcWindow( framePtr );
                 curTimeStamp = tmp.frameBuf()->timestamp();
             }
             rcTimestamp frameInt = curTimeStamp - prevTimeStamp;
             if ( firstFrame )
             {
                 firstFrame = false;_startTime = curTimeStamp;_currentTime = _startTime;
         // Update video frame size (readjusts monitor size)
                 setFrameSize( videoFrame.width(), videoFrame.height(), tmp.depth());
                 _observer->notifyVideoRect( videoFrame );
                 _observer->notifyAnalysisRect( videoFrame );
             }
             else
             {
         // Use true frame interval
                 _currentTime += frameInt;
                 rmAssert(frameInt > 0.0 );// Zero time between frames is not allowed
             }
             prevTimeStamp = curTimeStamp;
         // PreProcess the image if needed for Display
         // @note see and understand the above before you alter this code!
             ipp (tmp, image, curTimeStamp);
             _fileImages.push_back( image );
             rcVideoWriter* videoWriter;
             videoWriter = _videoWriter.getValue(videoWriter);
             if (videoWriter != 0)
                 videoWriter->writeValue( curTimeStamp, rcRect(), &image );
             const rcTimestamp curTime =  rcTimestamp::now();
             rcTimestamp updateInterval = curTime - lastStatusUpdateTime;
         // Update status bar
             if ( updateInterval.secs() > updateStatusInterval)  {
                 lastStatusUpdateTime = curTime;
                 char buf[512];
                 snprintf( buf, rmDim( buf ), "Loading %i frames...%i%% complete", frameMax, int(double(i)/frameMax * 100) );
                 _observer->notifyStatus( buf );
             }
             updateInterval = curTime - lastMovieUpdateTime;
             if ( updateInterval.secs() > updateMovieInterval ) {
         // Update movie display
                 lastMovieUpdateTime = curTime;
                 if ( _observer->acceptingImageBlits() )
                     _observer->notifyBlitData( &image );
             }
         }// End of For i++
     // @note this is the place to do motion compensation while we load images
     // Update elapsed time
         _observer->notifyTime( getElapsedTime() );
         _observer->notifyTimelineRange( 0.0, getElapsedTime() );
         flushSharedWriters ();
         if (_inputMode != eCmd)
             setInternalState( eEngineStopped );
         if ( ! grabber.stop() )
             error = grabber.getLastError();
     }
     else   // isValid() failed
         error = grabber.getLastError();
     // Done. Report
     duration = rcTimestamp::now() - duration;
     // Set analysis range
     _analysisFirstFrame = 0;
     _analysisLastFrame =  _fileImages.size();
     if ( !_fileImages.empty() ) {
         // Set analysis rect
         setSettingValue( cAnalysisRectSettingId, rcRect(0, 0, _frameWidth, _frameHeight ) );
         _observer->notifyAnalysisRect( getSettingValue( cAnalysisRectSettingId ) );
         // Display final status
         {
             char buf[512];
             snprintf( buf, rmDim( buf ), "%li %s frames [%d by %d] loaded\n",
                 _fileImages.size(),
                 _fileImages[0].isGray() ? "gray scale" : "color",
                 _fileImages[0].size().x(), _fileImages[0].size().y());
             _observer->notifyStatus( buf );
         }
         // stdout message
         cout << _fileImages.size() << " " << _fileImages[0].bits () << "-bit ";
         if ( _fileImages[0].isGray() )
             cout << "gray scale";
         else
             cout << "16bit gray or color";
         cout << "[" << _fileImages[0].size().x() << " by " << _fileImages[0].size().y() << "]";
         cout << " frames loaded in " << duration.secs() << " seconds" << endl;
     } else {
         // Nothing loaded
         cout << "done" << endl;
         cout << _fileImages.size() << " frames loaded in " << duration.secs() << " seconds" << endl;
     }
     updateHeaderLogs();
     return i;
 }
int rcEngineImpl::loadImages () protected
Definition at line 250 of file rc_engineimplload.cpp.
References _frameRate, _imageFileNames, _observer, count(), eEngineRunning, eFrameErrorOK, eFrameErrorUnknown, endl(), rcFrameGrabber::getErrorString(), rcImageGrabber::getInputSourceName(), getState(), loadFrames(), rcEngineObserver::notifyError(), and rcEngineObserver::notifyStatus().
Referenced by rcEngineImporter::run().
 {
     int count = 0;
     if ( getState() != eEngineRunning ) {
         vector<std::string> fileNames;
         if ( !_imageFileNames.empty() ) {
             vector<const char*> files;
             std::string::size_type str = 0, idx = 0;
             while ( str < _imageFileNames.size() ) {
                 idx = _imageFileNames.find( ';', str );
                 if ( idx != std::string::npos ) {
                     std::string oneFile = _imageFileNames.substr( str, idx - str );
                     fileNames.push_back( oneFile );
                     str = idx + 1;
                     } else
                         break;
                 }
             // No semicolon found, just keep the string as is
                 if ( fileNames.empty() )
                     fileNames.push_back( _imageFileNames );
                 double frameInterval = _frameRate ? 1.0/_frameRate : 1.0;
             // Create image grabber with a forced frame rate
                 rcImageGrabber grabber( fileNames, this, frameInterval );
             // Load frames
                 rcFrameGrabberError error = eFrameErrorUnknown;
                 count = loadFrames( grabber, error );
                 if ( error != eFrameErrorOK )
                 {
                     strstream s;
                     s << rcFrameGrabber::getErrorString( error ) << " " << grabber.getInputSourceName() << ends;
                     _observer->notifyError( s.str() );
                     _observer->notifyStatus( s.str() );
                     s.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
                     cerr << s.str() << endl;
                 }
             }
         }
         return count;
     }
int rcEngineImpl::loadMovie () protected
Definition at line 298 of file rc_engineimplload.cpp.
References _movieFile, _observer, count(), eEngineRunning, eFrameErrorFileInit, eFrameErrorOK, eFrameErrorUnknown, endl(), rcFrameGrabber::getErrorString(), rcPersistenceManager::getImportDirectory(), rcPersistenceManagerFactory::getPersistenceManager(), getState(), rcEngineObserver::notifyError(), and rcEngineObserver::notifyStatus().
Referenced by rcEngineImporter::run().
 {
     int count = 0;
     if ( getState() != eEngineRunning ) {
         if ( !_movieFile.empty() ) {
             rcFrameGrabberError error = eFrameErrorUnknown;
             count = loadMovie( _movieFile, error );
         cerr << count << " Frames in the movie " << _movieFile << endl;
             if ( error != eFrameErrorOK ) {
           cerr << "Loading Movie Again: " << endl;
                 if ( error == eFrameErrorFileInit ) {
                     // File not found, look for file in the current directory
                     // Get file name without preceding path
                     std::string rawFileName = _movieFile;
                     std::string slash( "/" );
                     uint32 s = _movieFile.find_last_of( slash );
                     if ( s != std::string::npos ) {
                         uint32 len = _movieFile.size() - s - 1;
                         if ( len > 0 )
                             rawFileName = _movieFile.substr( s+1, len );
                     }
                     rcPersistenceManager* pm = rcPersistenceManagerFactory::getPersistenceManager();
                     // Get current import directory
                     std::string importDir = pm->getImportDirectory();
                     // Concatenate import directory and movie file name
                     std::string newMovieFile = importDir + rawFileName;
                     std::string origMovieFile = _movieFile;
                     // Change movie name to the new name
                     _movieFile = newMovieFile;
                     error = eFrameErrorUnknown;
                     // Try loading with the same file name but current import directory
                     count = loadMovie( newMovieFile, error );
             cerr << count << " Frames in the movie " << _movieFile << endl;
                     if ( error == eFrameErrorOK ) {
                         cerr << "Loaded " << newMovieFile << " because ";
                         cerr << origMovieFile << " could not be found" << endl;
                     } else {
                         // Report failed file name without path as status
{
                             strstream s;
                             s << rcFrameGrabber::getErrorString( error ) << " " << rawFileName << ends;
                             _observer->notifyStatus( s.str() );
                             s.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
                         }
                         // Report both load failure paths as a popup error
                         strstream s;
                         s << rcFrameGrabber::getErrorString( error ) << " " << origMovieFile << endl;
                         if ( _movieFile != origMovieFile )
                             s << rcFrameGrabber::getErrorString( error ) << " " << _movieFile;
                         s << ends;
                         s.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
                         _observer->notifyError( s.str() );
                         cerr << s.str() << endl;
                     }
                 } else {
                     // Load failed, display an error dialog
                     if ( error != eFrameErrorOK ) {
                         strstream s;
                         s << rcFrameGrabber::getErrorString( error ) << " " << _movieFile << ends;
                         _observer->notifyError( s.str() );
                         _observer->notifyStatus( s.str() );
                         s.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
                         cerr << s.str() << endl;
                     }
                 }
             }
         }
     }
     return count;
 }
int rcEngineImpl::loadMovie (const std::string & movieFile, rcFrameGrabberError & error) protected
Definition at line 383 of file rc_engineimplload.cpp.
References _frameRate, _observer, _videoCacheP, _videoCacheProgress, attributes(), TIFFImageIO::CanReadFile(), count(), eExperimentMolDevSTKFormat, eExperimentNativeMovieFormat, eFrameErrorOK, endl(), rcPersistenceManager::fileFormatExportExtension(), rcPersistenceManagerFactory::getPersistenceManager(), insensitive_case_compare(), loadFrames(), rcVideoCache::movieFileExperiments(), rcVideoCache::rcVideoCacheCtor(), rcVideoCache::rcVideoCacheDtor(), TIFFImageIO::ReadImageInformation(), TIFFImageIO::ReadPages(), rfGetExtension(), rfStripPath(), rfSystemRam(), rmAssert, rmMin, and rcEngineObserver::setExperimentAttributes().
 {
     int count = 0;
     vector<rcWindow> zstk;
     if ( !movieFile.empty() ) {
         rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
         std::string reifyMovieExt = persistenceManager->fileFormatExportExtension( eExperimentNativeMovieFormat );
         std::string stkMovieExt = persistenceManager->fileFormatExportExtension( eExperimentMolDevSTKFormat );
         // Create movie grabber
         rcFrameGrabber* grabber = 0;
         std::string fileExt = rfStripPath( movieFile );
         fileExt = rfGetExtension (fileExt);
         if ( insensitive_case_compare (fileExt, reifyMovieExt ) )
         {
             rmAssert(_videoCacheP == 0);
             double physMem(rfSystemRam ());
             const uint32 maxMem = (1024*1024*256);
             physMem = rmMin (physMem / 4, maxMem);
             _videoCacheP =
                 rcVideoCache::rcVideoCacheCtor(movieFile, 0, true, false,
                 true, physMem, _videoCacheProgress );
             cerr << "Video cache size " << physMem/(1024*1024) << " MB" << endl;
             grabber = new rcReifyMovieGrabber(*_videoCacheP);
         }
         else if (insensitive_case_compare(fileExt, stkMovieExt) )
         {
     // Get a TIFF Importer
             TIFFImageIO t_importer;
             if (! t_importer.CanReadFile (movieFile.c_str () ) ) return 0;
             t_importer.SetFileName (movieFile.c_str ());
             t_importer.ReadImageInformation ();
             zstk = t_importer.ReadPages ();
             grabber = new rcVectorGrabber (zstk);
         }
         else
         {
                 // Forced frame rate
             double frameInterval = _frameRate ? 1.0/_frameRate : 0.0;
             grabber = new rcMovieGrabber( movieFile, this, frameInterval );
         }
         // Load frames
         count = loadFrames( *grabber, error );
         delete grabber;
         if ( error != eFrameErrorOK ) {
             if (_videoCacheP) {
                 rcVideoCache::rcVideoCacheDtor(_videoCacheP);
                 _videoCacheP = 0;
             }
         }
         if (_videoCacheP) {
             // Experiment headers
             const vector<rcMovieFileExpExt>& expExts = _videoCacheP->movieFileExperiments();
             if ( !expExts.empty() ) {
                 rcMovieFileExpExt exp = expExts[0];
                 // Set experiment attributes
                 rcExperimentAttributes attrs = attributes( exp );
                 _observer->setExperimentAttributes( attrs );
             }
         }
     }
     return count;
 }
void rcEngineImpl::lock () virtual
Implements rcCarbonLock.
Definition at line 756 of file rc_engineimpl.cpp.
References _observer, and rcEngineObserver::notifyLockApp().
Referenced by getSettingValue(), isSettingEditable(), isSettingEnabled(), isSettingPersistable(), reset(), setCameraInfo(), setCaptureInfo(), and setSettingValue().
 {
   if ( _observer )
     _observer->notifyLockApp( true );
 }
std::string rcEngineImpl::makeTmpName (std::string exten) protected
Definition at line 1936 of file rc_engineimpl.cpp.
References _inputMode, _movieFile, eCmd, rcTimestamp::now(), rfToString(), and rcTimestamp::secs().
 {
   // Get file name without preceding path
   std::string rawFileName = _movieFile;
   if (_inputMode == eCmd && !_movieFile.empty())
     {
       std::string slash( "/" );
       uint32 s = _movieFile.find_last_of( slash );
       if ( s != std::string::npos ) {
                 uint32 len = _movieFile.size() - s - 1;
                 if ( len > 0 )
                     rawFileName = _movieFile.substr( s+1, len );
       }
     }
   else
     rawFileName = std::string ("/tmp/exp");
   // Use current time in seconds as a pseudo-unique prefix
   double secs = rcTimestamp::now().secs();
   ostringstream strout;
   std::string resFileName = rawFileName + rfToString (secs) + exten;
   return resFileName;
 }
void rcEngineImpl::model2use ()
Definition at line 1986 of file rc_engineimpl.cpp.
References _model2use, rcWindow::rowPointer(), and sTarget_Image_tip.
Referenced by modelTracker(), and setFromArgs().
 {
    _model2use = rcWindow ();
   rcWindow foo (152, 128);
     for (int i = 0; i < 128; i++)
         memcpy (foo.rowPointer (i),  sTarget_Image_tip [i], 152);
     _model2use = foo;
 }
uint32 rcEngineImpl::modelTracker (rcEngineFocusData * focus, const vector< rcWindow > & focusImages, int32 cacheSz) protected
Definition at line 25 of file rc_engineimpl_modeltracker.cpp.
References _model2use, _observer, abs(), rcStatistics::add(), cAnalysisMotionTrackingBodyVectorDisplaySettingId, cAnalysisMotionTrackingMotionVectorDisplaySettingId, createGraphicsWriters(), rcWindow::depth(), rc2dVector< T >::distance(), endl(), rcEngineFocusData::focusRect(), getElapsedTime(), rcVectorGrabber::getInputSourceName(), rcWriter::getName(), getSettingValue(), rcWindow::height(), rcWindow::isBound(), rcVectorGrabber::isValid(), rc2Xform::mapPoint(), rcStatistics::mean(), model2use(), rcStatistics::n(), rcEngineObserver::notifyError(), rcEngineObserver::notifyStatus(), rcEngineObserver::notifyTime(), postTrackingResults(), rcEngineProgress::progress(), rfGaussianConv(), rfImageFind(), rfImageGradientToVisualSegment(), rfPixelSample(), rmAssert, rmMax, rcWriter::setName(), rcEngineFocusData::setTrackStartTimes(), rcStatistics::stdDev(), rcEngineFocusData::tipDistanceWriter(), rc2Xform::trans(), rcWindow::width(), rcPair< T >::x(), rc2dVector< T >::x(), rcWindow::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by analyzeFocusArea().
 {
     double statusUpdateInterval = 1.5;
     // Create template if you need to
     model2use ();
     rcWindow sampled_model (_model2use.width(), _model2use.height (), _model2use.depth());
     rfGaussianConv (_model2use, sampled_model, 9);
     rcVisualSegmentCollection visualModel;
     rfImageGradientToVisualSegment (sampled_model, visualModel);
     // Create a grabber to read the image vector
     rcVectorGrabber imageGrabber( focusImages, cacheSz );
     if ( ! imageGrabber.isValid()  || ! _model2use.isBound () )
     {
         strstream s;
         std::string cause = " Does not exist ";
         s << imageGrabber.getInputSourceName() << " Pre Defined Template " << cause << std::ends;
         _observer->notifyError( s.str() );
         s.freeze( false );
         cerr << s.str() << endl;
     }
     bool displayMotionVectors = getSettingValue( cAnalysisMotionTrackingMotionVectorDisplaySettingId );
     bool displayBodies = getSettingValue( cAnalysisMotionTrackingBodyVectorDisplaySettingId );
     createGraphicsWriters( displayMotionVectors, displayBodies, false, false );
     rcEngineProgress progressIndicator( this, _observer, "Target Tracking...%.2f%% complete", statusUpdateInterval );
     progressIndicator.progress( 0.0 );
     rcRect focusRect = focus->focusRect();
     const rcIPair pres (3,1); // pyramid resolution
     const rcRadian zr (0.0);
     rc2Dvector translation (0.0, 0.0);
     rcMatrix_2d mtt (zr, rcDPair ((double) pres.x(), (double) pres.y()));
     rc2Xform mx (mtt, translation);
     vector<rcWindow>::const_iterator imgItr = focusImages.begin ();
     focus->setTrackStartTimes( imgItr->timestamp ().secs() );
     rcWindow corr_space;
     rcWindow model2use, image2use, tmp2use;
     int32 smoothKernelWidth = rmMax (pres.x() , pres.y()) * 2 - 1; // same as 2*res - 1.
     if (pres.x() == 1 && pres.y() == 1)
     {
         image2use = *imgItr;
         model2use = _model2use;
     }
     else
     {
         // Generate Low resolution images and process the first image
         rcWindow tmp (imgItr->width(), imgItr->height(), imgItr->depth());
         tmp2use = tmp;
         rfGaussianConv (*imgItr, tmp2use, smoothKernelWidth);
         image2use= rfPixelSample (tmp2use, pres.x(), pres.y());
         rcWindow sampled_model (_model2use.width(), _model2use.height (), _model2use.depth());
         rfGaussianConv (_model2use, sampled_model, smoothKernelWidth);
         model2use = rfPixelSample (sampled_model, pres.x(), pres.y());
     }
     // Locate the target in the first image
     // @todo Run on the first image @todo remove assumption that the first image has to contain valid
     rcFindList firstFind;
     rfImageFind (image2use, model2use, firstFind, corr_space);
     rc2Fvector startp = mx.mapPoint (firstFind.begin()->interpolated ());
     // Setup a restricted window for future runs +/- modelwidth
         rcIPair limitTopLeft ((int32) (firstFind.begin()->interpolated().x() - model2use.width() / 2), model2use.height());
         rcIPair limitSize (model2use.width()*2, image2use.height() - model2use.height());
         rc2Fvector limitTL ((float) limitTopLeft.x(), (float) limitTopLeft.y());
         mx.trans (mx.mapPoint (limitTL));
     std::cout << "[ @ " << imgItr->timestamp ().secs() << " + " << startp.x() <<
       " , " << startp.y() << " ]: " <<  firstFind.begin()->score() <<
         " limit " << limitTopLeft.x() << " , " << limitTopLeft.y() << " -- " <<
         limitSize.x() << " , " << limitSize.y() <<  std::endl;
     // Assume we are tracking one object
     rc2Fvector anch = startp;
     rcFRect box (anch.x(), anch.y(), (float) _model2use.width(), (float) _model2use.height());
     // Setup Writer
     // Write the track out
     rcScalarWriter* sWriter = focus->tipDistanceWriter();
     rcWriter* speedwriter = sWriter->down_cast();
     std::string name = speedwriter->getName();
     std::string nameWithOptions = std::string("Instant Speed");
     speedwriter->setName( nameWithOptions.c_str() );
     rcStatistics xstats, rstats;
     bool enableMonitor = false;
     for (float pct=0.0f; imgItr != focusImages.end(); imgItr++, pct+= 100.0f)
     {
         // After 6 data points turn on stats monitoring
         if (!enableMonitor && xstats.n() > 6 && rstats.n() > 6) enableMonitor = true;
         if ( progressIndicator.progress( pct /(focusImages.size())))
         {
             // Abort Update elapsed time to refresh display
             _observer->notifyStatus( "Analysis stopped" );
             return 0;
         }
         rcFindList finds;
         if (pres.x() == 1 && pres.y() == 1) image2use = *imgItr;
         else
         {
             rmAssert (tmp2use.isBound());
             rfGaussianConv (*imgItr, tmp2use, smoothKernelWidth);
             rfPixelSample (tmp2use, image2use, pres.x(), pres.y());
         }
                 rcWindow window2use (image2use, limitTopLeft.x(), limitTopLeft.y(), limitSize.x(), limitSize.y());
         rfImageFind (window2use, model2use, finds, corr_space);
         rc2Fvector newp = mx.mapPoint (finds.begin()->interpolated());
                 // Validate the new point
         int x_error = std::abs (100 * ((startp.x() - xstats.mean() ) / xstats.stdDev ()));
                 // No error if corr values go over mean.
     int r_error = (100 * ((finds.begin()->score() - rstats.mean() ) / rstats.stdDev ()));
                 r_error = r_error >= 0 ? 0 : -r_error;
                 // Add this data point after we have read the stats so far
         xstats.add (newp.x());
         rstats.add (finds.begin()->score());
                 float distance (0.0f);
                 bool found = ! (enableMonitor &&  r_error > 270);
                 distance = newp.distance (startp);
                 if ( found )
                     {
                         startp = newp;
                     }
                 std::cerr << imgItr->timestamp ().secs() << "," << startp.x() << "," << startp.y() << "," <<  finds.begin()->score() << "," << distance;
         if (enableMonitor) std::cerr << "e: " << x_error << " " << r_error << " ";
                 std::cerr << std::endl;
         sWriter->writeValue(  imgItr->frameBuf()->timestamp(), focus->focusRect(), distance);
         postTrackingResults( focus, finds, found, focusRect, mx, imgItr->frameBuf()->timestamp(), visualModel);
     }
     _observer->notifyTime( getElapsedTime() );
     return focusImages.size();
 }
uint32 rcEngineImpl::motionTracker (rcEngineFocusData * focus, const vector< rcWindow > & focusImages, int32 cacheSz) protected
Referenced by muscleTracker().
int32 rcEngineImpl::muscleTracker (rcEngineFocusData * focus, const vector< rcWindow > & focusImages, int32 cacheSz, double msPerFrame) protected
Definition at line 18 of file rc_engineimplmuscle.cpp.
References _movieFile, _observer, _segmentVectorWriter, _selectedPolys, _videoCacheP, rcKinetoscope::advance(), rcAffineRectangle::affineToImage(), rcVideoCache::averageFrameRate(), rcKinetoscope::averageFramesPerSecond(), cAnalysisCellTypeId, cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId, cAnalysisMotionTrackingBodyVectorDisplaySettingId, cAnalysisMotionTrackingMotionVectorDisplaySettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisMotionTrackingTargetSettingId, cAnalysisMuscleAutoGenPeriodId, cAnalysisMuscleSegmentationVectorDisplaySettingId, rcAffineRectangle::cannonicalSize(), CellPolyBufferSize, rcEngineFocusData::cellSpeedMeanWriter(), rcMuscleSegmenter::cInvalidPeriod, createGraphicsWriters(), rcKinetoscope::debug(), developerDebugging(), rcOrganismInfo::eCardioMyocyteSelected, rcOrganismInfo::eCell, rcKinetoscope::eContractile, endl(), rcKinetoscope::eUnderSampled, rcMuscleSegmenter::extendedMuscleCellIndex(), rcMuscleSegmenter::filterAtEdge(), rcMuscleSegmenter::filterByActivity(), rcMuscleSegmenter::filterByAR(), rcMuscleSegmenter::filterBySize(), rcKinetoscope::fixed(), rcEngineFocusData::focusRect(), rcWindow::frameBuf(), rcVectorGrabber::frameCount(), rcMuscleSegmenter::framesPerPeriod(), rcMuscleSegmenter::getCells(), getElapsedTime(), rcMuscleSegmenter::getRejects(), getSettingValue(), rcMuscleSegmenter::hackInsertSegmentedImages(), rcRectangle< T >::height(), rcWindow::isBound(), rcVectorGrabber::isValid(), rcPolygon::minimumAreaEnclosingRect(), rcKinetoscope::minMobSizeInPixels(), motionTracker(), movieFormatRevLatest, movieOriginSynthetic, rcEngineObserver::notifyStatus(), rcEngineObserver::notifyTime(), NULL, offsetGraphics(), rcKinetoscope::periodicMotion(), rcPolygonGroupRef::polys(), rcKinetoscope::preSegmentedBodies(), produceCellResults(), produceDebugResults(), produceMuscleDebugResults(), rcEngineProgress::progress(), reportOnBadGrabber(), rcKinetoscope::resultTime(), rfPolygonToSegmentsCollection(), rfRgb, rfStripPath(), rmAssert, rmExceptionMacro, rmMax, rcTimestamp::secs(), rcMuscleSegmenter::segment(), rcVisualGraphicsCollection::segments(), rcScalarWriter::setExpectedMaxValue(), rcEngineFocusData::setTrackStartTimes(), rcPolygonGroupRef::size(), rcKinetoscope::sourceMotion(), rcKinetoscope::step(), stop(), rcWindow::tiff(), rcFrame::timestamp(), rcKinetoscope::visualDebugGraphics(), rcRectangle< T >::width(), rcGraphicsWriter::writeValue(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
 {
   //@note
   //If autoSelect is on (default), use segmenter to find phase and frequency and continue to find
   //Cell locations.
   //If autoSelect is off, still use the segmenter to find phase and frequency but accept end positions
   //for cell localizations
   if (!_videoCacheP) return 0;
   double msPerFrame = s_msPerFrame;
   rmAssert(msPerFrame > 0);
   // Get some of the parameters
   int32 minTargetSize = getSettingValue(cAnalysisMotionTrackingTargetSettingId);
   const double minCellArea = minTargetSize * minTargetSize;
   rcOrganismInfo::OrganismName oname = static_cast<rcOrganismInfo::OrganismName>
     (static_cast<int>(getSettingValue( cAnalysisCellTypeId)));
   rcOrganismInfo::OrganismType otype (rcOrganismInfo::eCell);
   bool autoSelect = oname != rcOrganismInfo::eCardioMyocyteSelected;
   // Ddebugging movie is generated if developer mode is on
   rcGenMovieFile debugMovie (std::string ("/Users/Shared/test.rfymov"),
                  movieOriginSynthetic, "Test Code",
                  movieFormatRevLatest, true, 30);
   // Create a segmenter
   rcMuscleSegmenter segmenter (developerDebugging() ? &debugMovie : NULL);
   _observer->notifyStatus( "SpatioTemporal Analysis..." );
   // Calculate how many frames to use for determination of periodicity
   const float framesPerMs = (float)(1/msPerFrame);
   const float maxFramesPerPeriod = 2000*framesPerMs;
   float framesPerPeriod  = -1;
   // AutoGen parameter is 0 (if auto) and hertz if specified by the user
   const int32 autoGen = getSettingValue(cAnalysisMuscleAutoGenPeriodId);
   if (autoGen > 0)
     {
       int32 msPerPeriod = 1000 / autoGen; // 1000 msec in a second
       rmAssert(msPerPeriod > 0);
     framesPerPeriod = msPerPeriod / (double) msPerFrame;
     }
   // Check 3 period need with movie size
   uint32 threePeriods = (uint32)(6000*framesPerMs);
   if (threePeriods > (focusImages.size() - 1))
     threePeriods = (focusImages.size() - 1);
   if (1) printf("%s %s framesPerMs %f maxFramesPerPeriod %f framesPerPeriod %f threePeriods %d w %d h %d\n",
         autoGen >= 0 ? "Paced" : "Not Paced" , (autoGen == 0) ? " Enabled " : " Specified",
         framesPerMs, maxFramesPerPeriod, framesPerPeriod, threePeriods,
         focusImages[0].width(), focusImages[0].height());
   // Now call the segmenter to segment
   // @note that this call will calculate phase, frquency of the paced plate as well as cell locations
   int32 segStatus = segmenter.segment(focusImages, 0, (int32)threePeriods,
                     autoSelect);
   //@note debugging
   {
     rcWindow segImg, freqImg, emiImg;
     segmenter.hackInsertSegmentedImages (segImg, freqImg, emiImg);
     std::string moviefn = std::string ("/Users/arman/tmpdir/") + rfStripPath (_movieFile);
     if (segImg.isBound())
       {
     std::string rawFileName = moviefn + std::string ("_seg.tif");
     cerr << "Result File Name: " << rawFileName << endl;
     segImg.tiff (rawFileName);
       }
     if (emiImg.isBound())
       {
     std::string rawFileName = moviefn + std::string ("_emi.tif");
     cerr << "Result File Name: " << rawFileName << endl;
     emiImg.tiff (rawFileName);
       }
     if (freqImg.isBound())
       {
     std::string rawFileName = moviefn + std::string ("_freq.tif");
     cerr << "Result File Name: " << rawFileName << endl;
     freqImg.tiff (rawFileName);
       }
   }
   if (segStatus >= 0)
     cerr << "fba: " << framesPerPeriod << " seg: " << segmenter.framesPerPeriod() << endl;
   // If we are auto selecting and had errors
   if (autoSelect && segStatus < 0)
     {
       cerr << "Segmenter returned: " << segStatus << endl;
       return segStatus;
     }
   // If we are not on autoSelect mode, continue filtering the segmenter results
   // Otherwise use specific data
   // Declare the cell polygon groups
   vector<rcPolygon> cells, ocells, rejects;
   vector<vector<rc2Fvector> > specs;
   vector<float> rads;
   if (!autoSelect && segStatus != rcMuscleSegmenter::cInvalidPeriod)
     {
       const double minActivePct = 0.25;
       segStatus = segmenter.filterByActivity(minActivePct, focusImages, 0, (int32)threePeriods,
                          maxFramesPerPeriod, framesPerPeriod);
       // Get Polygon Info From the Engine
    //   vector<rcPolygon>& pgs = const_cast<rcPolygonGroupRef*> (polys)_selectedPolys.polys ();
       for (uint32 i = 0; i < _selectedPolys.size (); i++)
       {
         const rcPolygon& p = _selectedPolys.polys ()[i];
     rcAffineRectangle ar = p.minimumAreaEnclosingRect ();
     bool side = ar.cannonicalSize().x() > ar.cannonicalSize().y();
     vector<rc2Fvector> c0;
     if (side)
       {
         c0.push_back (ar.affineToImage(rc2Fvector(0.0f, 0.5f)));
         c0.push_back (ar.affineToImage(rc2Fvector(1.0f, 0.5f)));
       }
     else
       {
         c0.push_back (ar.affineToImage(rc2Fvector(0.5f, 0.0f)));
         c0.push_back (ar.affineToImage(rc2Fvector(0.5f, 1.0f)));
       }
     specs.push_back (c0);
     rads.push_back (c0[0].distance (c0[1]));
       }
     }
   else // AutoSelect and segStatus >= 0
     {
       segmenter.filterBySize(minCellArea);
       const double minAspectRatio = 1.5;
       segmenter.filterByAR(minAspectRatio);
       const int32 minDelta = 18;
       segmenter.filterAtEdge(minDelta);
       const double minActivePct = 0.25;
       segStatus = segmenter.filterByActivity(minActivePct, focusImages, 0, (int32)threePeriods, maxFramesPerPeriod, framesPerPeriod);
       if (segStatus < 0)
     return segStatus;
       segmenter.getCells(ocells);
     }
   // Create a buffer around a cell
   for (uint32 i = 0; i < ocells.size(); i++)
     {
       cells.push_back (ocells[i].discBuffer (CellPolyBufferSize));
     }
   double statusUpdateInterval = 1.5;
   const rc2Fvector centerPixelOffset; // ((float)0.5, (float)0.5);
   bool displayMotionVectors =
     getSettingValue(cAnalysisMotionTrackingMotionVectorDisplaySettingId);
   bool displayBodies =
     getSettingValue(cAnalysisMotionTrackingBodyVectorDisplaySettingId);
   bool displayBodyHistories =
     getSettingValue(cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId);
   bool displaySegmentation =
     getSettingValue(cAnalysisMuscleSegmentationVectorDisplaySettingId);
   // Create graphics writers if applicable
   createGraphicsWriters(displayMotionVectors, displayBodies, displayBodyHistories, displaySegmentation);
   // If we have a graphics track, draw results
   if (_segmentVectorWriter != 0 && (cells.size () || specs.size () ) )
     {
       printf("made it %d cells\n", (int) rmMax (cells.size(), specs.size ()) );
       rcVisualGraphicsCollection graphics;
       rcVisualSegmentCollection& segments = graphics.segments();
       // Green color, line width of 1 display pixel, 0.0 pixel origin
       rcVisualStyle validCell(rfRgb(128, 255, 20), 1, rc2Fvector(0.0f, 0.0f));
       // Set drawing style
       segments.push_back(validCell);
       const uint32 cellCnt = cells.size();
       const uint32 rejectCnt = rejects.size();
       uint32 elmtCnt = cellCnt + rejectCnt;
       for (uint32 ci = 0; ci < cellCnt; ci++)
     elmtCnt += cells[ci].vertexCnt();
       for (uint32 ri = 0; ri < rejectCnt; ri++)
     elmtCnt += rejects[ri].vertexCnt();
       if (displayBodies)
     {
       segments.reserve(elmtCnt + 1);
       for (uint32 ci = 0; ci < cellCnt; ci++)
         rfPolygonToSegmentsCollection(cells[ci], segments);
     }
       segmenter.getRejects(rejects);
       produceMuscleDebugResults (rejects, segmenter, segments);
       // Hack for displaying segmenter results on the graphics track just once.
       rcRect focusRect(focus->focusRect());
       const rc2Fvector focusOffset(focusRect.x(), focusRect.y());
       offsetGraphics(graphics, focusOffset + centerPixelOffset);
       _segmentVectorWriter->writeValue(focusImages[0].frameBuf()->timestamp(), focusRect, graphics);
       {
     rcVisualGraphicsCollection nullGraphics;
     _segmentVectorWriter->writeValue(focusImages.back().frameBuf()->timestamp(),
                      focusRect, nullGraphics);
       }
     }  // _segmentVectorWriter != 0
   _observer->notifyStatus( "Processing experiment..." );
   if (cells.size() == 0 && specs.size () == 0)
     return 0;
   // Create a grabber to read the image vector
   rcVectorGrabber imageGrabber(focusImages, cacheSz);
   if (! imageGrabber.isValid())
     {
       reportOnBadGrabber (imageGrabber);
       return 0;
     }
   rcRect focusRect = focus->focusRect();
   rcIRect rect(focusRect.x(), focusRect.y(),
            focusRect.width(), focusRect.height());
   // @note do we need these ?
   // Specify tracker options
   const int32 maxSpeed =
     getSettingValue(cAnalysisMotionTrackingSpeedSettingId );
   // Set aggregate speed writer expected max values
   rcScalarWriter* speedWriter = focus->cellSpeedMeanWriter();
   if (speedWriter) speedWriter->setExpectedMaxValue(maxSpeed);
   // Figure out phase and frequency to pass to kinetoscope
   // @note emi is the index of the fully extended muscle for a paced
   // experiment. The interface to Kinetescope expects # of frames
   int32 emi (0);
   if ((emi = segmenter.extendedMuscleCellIndex ()) > 0)
     {
       float kinePhase = (float) emi;
       kinePhase = fmod (kinePhase, segmenter.framesPerPeriod());
       emi = (int32) kinePhase;
     }
   cerr <<  "Pacing @ " <<  segmenter.framesPerPeriod() << " Starting Phase: " << emi << endl;
   rcEngineProgress progressIndicator(this, _observer, "MyoSight Processing"
                      "...%.2f%% complete", statusUpdateInterval);
   progressIndicator.progress(0.0);
   // Create a Kinetoscope
   rmAssert (emi >= 0);
   rcKinetoscopeParams params; params.phase = emi;params.c = otype;params.n = oname;
   rcKinetoscope motionTracker(imageGrabber, rect, params);
   if (cells.size())
     motionTracker.preSegmentedBodies(cells);
   else if (specs.size() && rads.size () && specs.size() == rads.size ())
     motionTracker.preSegmentedBodies(specs, rads);
   motionTracker.minMobSizeInPixels(minTargetSize);
   motionTracker.sourceMotion (rcKinetoscope::eUnderSampled);
   motionTracker.sourceMotion (rcKinetoscope::eContractile);
   motionTracker.periodicMotion (segmenter.framesPerPeriod ());
   motionTracker.averageFramesPerSecond (_videoCacheP->averageFrameRate());
   int32 maxFrames = imageGrabber.frameCount();
   if ( maxFrames < 0 )
     maxFrames = 1;
   // Time stamp of previous frame
   //@note a constructed motiontracker already has the first frame
   // ProduceCellResults is called at (moving) time: 2nd / later stage of the motion
   // All results need to be at moving time.
   // @note this needs to be redone to support both operational modes.
   // In isLabelProtein() after ctor we have the first results ready
   bool firstCell = true;
   rcTimestamp prevTimeStamp = motionTracker.fixed().frameBuf()->timestamp(); // return fixed
   focus->setTrackStartTimes( prevTimeStamp );
   //   int32 maxFrames = 0;
   //     // Time stamp of previous frame
   //     rcTimestamp prevTimeStamp = cZeroTime;
   //     bool firstFrame = true;
   //     bool firstCell = true;
   uint32 analysisCount = 0;
   while (motionTracker.step(1))
     {
       ++analysisCount;
       rcTimestamp curTimeStamp = motionTracker.resultTime ();  // returns fixed for paced cardiomyocyte
       rcTimestamp frameInt = curTimeStamp - prevTimeStamp;
       if (analysisCount > 1 && frameInt <= 0.0)
     rmExceptionMacro (<< "Error: invalid frame interval " << frameInt.secs() << "f[" << analysisCount+1 << "]" << endl);
       if (analysisCount > 1)
     {
       // Development/debug image and graphics
       rcVisualGraphicsCollection debugGraphics;
       motionTracker.visualDebugGraphics( debugGraphics );
       rcWindow debugImage = motionTracker.debug();
       produceDebugResults( focus, debugImage, debugGraphics, focusRect, curTimeStamp );
       // Produce results for each cell
       produceCellResults(focus, motionTracker, focusRect, curTimeStamp, firstCell);
     }
       // Update progress bar
       if (progressIndicator.progress((100.0 * (analysisCount+1))/maxFrames)) {
     // Abort
     _observer->notifyStatus("Analysis stopped");
     goto stop;
       }
       // Roll Over
       prevTimeStamp = curTimeStamp;
       motionTracker.advance ();  // moving -> fixed, moving to fixed
     }
  stop:
   // Temporary: Now Dump the results stored in the cell
   // @note: make a file name for the results.
   // Movie file path is used if it exists and that we are running in the
   // cmd line mode.
   // Update elapsed time to refresh display
   _observer->notifyTime(getElapsedTime());
   return analysisCount;
 }
void rcEngineImpl::notifyEngineOfPolys (const rcPolygonGroupRef * polys) virtual
Implements rcEngine.
Definition at line 366 of file rc_engineimpl.cpp.
References _selectedPolys, rcPolygonGroupRef::push_back(), and rcPolygonGroupRef::size().
 {
   //  const vector<rcPolygon>& pgs = const_cast<vector<rcPolygon>&> (polys->polys ());
   if (polys->size ())
     {
         rcSharedPolygonGroupPtr c0 ( new rcPolygonGroup );
       rcPolygonGroupRef cref (c0);
       for (uint32 i = 0; i < polys->size (); i++)
                 {
                     cref.push_back (const_cast<rcPolygonGroupRef*> (polys) ->operator[] (i) );
                 }
       _selectedPolys = cref;
     }
 }
rcEngineObserver& rcEngineImpl::observer () inline
Definition at line 244 of file rc_engineimpl.h.
References rmAssert.
Referenced by initialize().
 { rmAssert(_observer); return *_observer; };
bool rcEngineImpl::operatingOnLiveInput (void) virtual
Implements rcEngine.
Definition at line 341 of file rc_engineimpl.cpp.
References cInputModeSettingId, eCmd, eFile, and getSettingValue().
 {
   int inputMode = getSettingValue( cInputModeSettingId );
   return (inputMode != eFile && inputMode != eCmd);
 }
std::string rcEngineImpl::outputFile () const inline
Definition at line 166 of file rc_engineimpl.h.
Referenced by main().
         {
             return _outputFileName;
         }
rcExperimentFileFormat rcEngineImpl::outputFormat () const inline
Definition at line 171 of file rc_engineimpl.h.
Referenced by main().
         {
             return _saveFormat;
         }
bool rcEngineImpl::pauseTracking (void) virtual
Implements rcEngine.
Definition at line 352 of file rc_engineimpl.cpp.
References _isPausedToggle, and rcAtomicValue< T >::setValue().
 {
   bool tmp (true);
   _isPausedToggle.setValue (tmp);
   return tmp;
 }
void rcEngineImpl::postTrackingResults (rcEngineFocusData * focus, rcFindList & locs, bool found, const rcRect & focusRect, const rc2Xform & mx, const rcTimestamp & curTimeStamp, const rcVisualSegmentCollection & vism) protected
Definition at line 184 of file rc_engineimpl_modeltracker.cpp.
References _bodyVectorWriter, _model2use, rcWindow::height(), rc2Xform::mapPoint(), offsetGraphics(), sAffy, sBlue, sRed, rcWindow::width(), rcGraphicsWriter::writeValue(), rcRect::x(), and rcRect::y().
Referenced by modelTracker().
 {
     const rc2Fvector focusOffset( static_cast<int>(focusRect.x()),
                                   static_cast<int>(focusRect.y()) ); // Origin offset
     rcRect boundingBox = focusRect;  // Same as analysis area for now
     rc2Fvector  lr ((float) _model2use.width(), (float) _model2use.height());
     rc2Fvector  center = lr / 2.0f;
     rcFindList::const_iterator loc;
     loc = locs.begin();
     rc2Fvector interp = loc->interpolated ();
     interp = mx.mapPoint (interp);
     // Move the model to visually overlap the image accordring to the registration results
     rcVisualSegmentCollection null_segs;
     rcVisualSegmentCollection segs = (! found ) ? null_segs : vism;
     rcVisualSegmentCollection::iterator sItr = segs.begin();
     for (; sItr != segs.end(); sItr++) *sItr += interp;
     segs.push_back (sAffy);
     segs.push_back (rcVisualRect (interp, interp+lr));
         segs.push_back (found ? sRed : sBlue);
     segs.push_back (rcVisualEllipse (interp+center, center));
     if (_bodyVectorWriter != 0)
     {
         rcVisualGraphicsCollection graphics (rcStyle (), segs);
         const rc2Fvector PixelOffset((float)0.5, (float)0.5);
         offsetGraphics( graphics, focusOffset + PixelOffset);
         _bodyVectorWriter->writeValue( curTimeStamp, focusRect, graphics );
     }
 }
void rcEngineImpl::process (void) virtual
Implements rcEngine.
Definition at line 648 of file rc_engineimpl.cpp.
References _analyzerThread, _inputMode, analyze(), eCmd, endl(), rcThread::isRunning(), rcThread::join(), and rcThread::start().
 {
   if (_inputMode == eCmd)
     {
       analyze ();
       return;
     }
   if ( _analyzerThread ) {
     if (_analyzerThread->isRunning()) {
       cout << "    analyzer thread shutdown ";
       int status = _analyzerThread->join();
       if (status)
                 cout << "error " << status << endl;
       else
                 cout << "OK" << endl;
     }
     _analyzerThread->start();
   }
 }
void rcEngineImpl::processCapturedData (rcEngineFocusData * focus, rcTimestamp timestamp, const std::string & cameraStatus, const rcAnalyzerResult & result, bool delay, uint32 missedFramesOnCapture, uint32 missedFramesOnSave, bool frameSaved) protected
Definition at line 918 of file rc_engineimpl.cpp.
References _fpsCalculator, _movieCapture, _observer, _videoWriter, rcEngineObserver::acceptingImageBlits(), cAnalysisRectSettingId, rcEngineMovieCapture::delayLeft(), eEngineRunning, endl(), rcAnalyzerResult::entropy(), rcEngineFocusData::focusRect(), rcFpsCalculator::fps(), rcAnalyzerResult::frameBuf(), getSettingValue(), getState(), rcAtomicValue< T >::getValue(), lastMovieUpdateTime, mSlidingEnergyPreviewWriter, rcEngineObserver::notifyBlitData(), rcEngineObserver::notifyStatus(), rcEngineObserver::notifyTime(), rcTimestamp::now(), rmAssert, rcTimestamp::secs(), rcEngineFocusData::slidingEnergyWriter(), rcFrame::timestamp(), updateMovieInterval, and rcScalarWriter::writeValue().
Referenced by frameInterrupt().
 {
   // Keep a reference to result frame
   rcWindow window(result.frameBuf());
   const size_t blen = 2048;
   char buf[blen];
   double captureFps = _fpsCalculator.fps();
   // ignore interrupts if we're not running
   if ( (getState() == eEngineRunning) || frameSaved ) {
     // Capturing
     // Timestamps for last video update
     // Initial value will cause an immediate update
     rcTimestamp now = rcTimestamp::now();
     rcTimestamp updateInterval = now - lastMovieUpdateTime;
     if ( updateInterval.secs() > updateMovieInterval ) {
       // Update movie display
       lastMovieUpdateTime = now;
       // Write video frame
       rcVideoWriter* temp;
       if (_videoWriter.getValue(temp) != 0) {
                 if (_observer->acceptingImageBlits()) {
                     _observer->notifyBlitData(&window);
                 }
       }
     }
     if (delay) {
       rmAssert(_movieCapture);
       uint32 tenthsSecondsLeft = _movieCapture->delayLeft();
       uint32 minLeft = tenthsSecondsLeft / 600;
       uint32 secLeft = (tenthsSecondsLeft % 600) / 10;
       uint32 tenthsLeft = (tenthsSecondsLeft % 10);
       if (missedFramesOnCapture)
                 snprintf(buf, blen, "Starting capture in %02d:%02d.%01d   "
                                  "Missed Frames: %d",
                                  minLeft, secLeft, tenthsLeft, missedFramesOnCapture);
       else
                 snprintf(buf, blen, "Starting capture in %02d:%02d.%01d",
                                  minLeft, secLeft, tenthsLeft);
     }
     else {
       uint32 tenthsSeconds = uint32(timestamp.secs() * 10);
       uint32 minutes = tenthsSeconds / 600;
       uint32 seconds = (tenthsSeconds % 600) / 10;
       uint32 tenths = (tenthsSeconds % 10);
       if (missedFramesOnCapture || missedFramesOnSave)
                 snprintf(buf, blen, "Capturing %02d:%02d.%01d"
                                  "    Missed Frames: %d Dropped Frames: %d    Rate: %4.2f fps",
                                  minutes, seconds, tenths,
                                  missedFramesOnCapture, missedFramesOnSave, captureFps);
       else
                 snprintf(buf, blen, "Capturing %02d:%02d.%01d    Rate: %4.2f fps",
                                  minutes, seconds, tenths, captureFps);
       if (focus) {
                 // Store results only for saved frames
                 if ( frameSaved ) {
                     // Produce aggregate change index for sliding window
                     rcScalarWriter* sWriter = focus->slidingEnergyWriter();
                     // Write the latest result
                     double entropy = result.entropy();
                     // Ignore undefined values
                     if ( entropy != -1.0 ) {
                         // Result time MUST be synchronized with frame time
                         sWriter->writeValue( result.frameBuf()->timestamp(), focus->focusRect(), entropy );
                         if ( getState() != eEngineRunning ) {
                             cerr << "rcEngineImpl::processCapturedData notification: frame ";// << result.frameBuf();
                             cerr << " at " << result.frameBuf()->timestamp() << " saved";
                             cerr << ", result " <<  result.entropy() << " saved after engine stopped running" << endl;
                         }
                     }
                 }
 #if 0
                 else {
                     cerr << "rcEngineImpl::processCapturedData notification: frame " << result.frameBuf() << " at ";
                     cerr << result.frameBuf()->timestamp() << " unsaved, ";
                     cerr << "result " << result.entropy() << " not stored" << endl;
                 }
 #endif
       }
       // Notify elapsed time
       _observer->notifyTime(timestamp);
     }
   }
   else {
     if ( frameSaved ) {
       cerr << "rcEngineImpl::processCapturedData error: frame " /*<< result.frameBuf()*/ << " at " << result.frameBuf()->timestamp();
       cerr << " saved but " << "result " << result.entropy() << " not stored" << endl;
     }
     // Previewing
     if (_observer->acceptingImageBlits() ) {
       _observer->notifyBlitData(&window);
     }
     if (missedFramesOnCapture)
       snprintf(buf, blen, "Previewing    Missed Frames: %d    Rate: %4.2f fps",
                              missedFramesOnCapture, captureFps);
     else
       snprintf(buf, blen, "Previewing    Rate: %4.2f fps",
                              captureFps);
     if ( mSlidingEnergyPreviewWriter ) {
       rcRect aRect = getSettingValue( cAnalysisRectSettingId );
       double res = result.entropy();
       // Replace undefined values
       if ( res < 0.0 )
                 res = 0.0;
       mSlidingEnergyPreviewWriter->writeValue( result.frameBuf()->timestamp(), aRect, res );
     }
     // Notify elapsed time
     _observer->notifyTime(timestamp);
   }
   std::string compositeStatus = cameraStatus + std::string(buf);
   // Time does not REALLY pass in preview mode, update status only
   _observer->notifyStatus(compositeStatus.c_str());
 }
void rcEngineImpl::produceCellResults (rcEngineFocusData * focus, rcKinetoscope & motionTracker, const rcRect & focusRect, const rcTimestamp & curTimeStamp, bool & firstCell) protected
Referenced by muscleTracker().
void rcEngineImpl::produceDebugResults (rcEngineFocusData * focus, rcWindow & debugImage, rcVisualGraphicsCollection & debugGraphics, const rcRect & focusRect, const rcTimestamp & curTimeStamp) protected
Definition at line 1695 of file rc_engineimpl.cpp.
References cAnalysisDevelopmentGraphicsDisplaySettingId, cAnalysisDevelopmentVideoDisplaySettingId, developerDebugging(), rcEngineFocusData::developmentGraphicsWriter(), rcEngineFocusData::developmentVideoWriter(), rcEngineFocusData::focusRect(), getSettingValue(), offsetGraphics(), rcVideoWriter::writeValue(), rcGraphicsWriter::writeValue(), rcRect::x(), and rcRect::y().
Referenced by muscleTracker().
 {
   if ( !developerDebugging() )
     return;
   const int writeImage = getSettingValue( cAnalysisDevelopmentVideoDisplaySettingId );
   const int writeGraphics = getSettingValue( cAnalysisDevelopmentGraphicsDisplaySettingId );
   // Write debugging image and graphics to debug tracks
   if ( writeImage ) {
     rcVideoWriter* devVideo = focus->developmentVideoWriter();
     if ( devVideo )
       {
                 devVideo->writeValue( curTimeStamp, focus->focusRect(), &debugImage );
       }
   }
   if ( writeGraphics  )
     {
       rcGraphicsWriter* devGraphics = focus->developmentGraphicsWriter();
       if ( devGraphics )
                 {
                     const rc2Fvector centerPixelOffset((float)1.5, (float)1.5);
                     const rc2Fvector focusOffset(static_cast<int>(focusRect.x()),
                                                                              static_cast<int>(focusRect.y())); // Origin offset
                     offsetGraphics( debugGraphics, /* focusOffset + */ centerPixelOffset);
                     devGraphics->writeValue( curTimeStamp, focus->focusRect(), debugGraphics );
                 }
     }
 }
bool rcEngineImpl::produceMuscleDebugResults (const vector< rcPolygon > & rejects, rcMuscleSegmenter & segmenter, rcVisualSegmentCollection & segments) protected
Definition at line 358 of file rc_engineimplmuscle.cpp.
References rcMuscleSegmenter::cRejCodeActivity, rcMuscleSegmenter::cRejCodeAR, rcMuscleSegmenter::cRejCodeEdge, rcMuscleSegmenter::cRejCodeSize, rcMuscleSegmenter::rejectRange(), rfPolygonToSegmentsCollection(), and rfRgb.
Referenced by muscleTracker().
 {
   int32 startIndex, endIndex;
   segmenter.rejectRange(startIndex, endIndex, rcMuscleSegmenter::cRejCodeSize);
   if (startIndex != endIndex) {
     // Red color, line width of 1 display pixel, 0.0 pixel origin
     rcVisualStyle rejectCell(rfRgb(255, 0, 0), 1, rc2Fvector(0.0f, 0.0f));
     // Set drawing style
     segments.push_back(rejectCell);
     for (int32 ri = startIndex; ri < endIndex; ri++)
       rfPolygonToSegmentsCollection(rejects[ri], segments);
   }
   segmenter.rejectRange(startIndex, endIndex, rcMuscleSegmenter::cRejCodeAR);
   if (startIndex != endIndex) {
     // Red color, line width of 2 display pixel, 0.0 pixel origin
     rcVisualStyle rejectCell(rfRgb(128, 128, 0), 2, rc2Fvector(0.0f, 0.0f));
     // Set drawing style
     segments.push_back(rejectCell);
     for (int32 ri = startIndex; ri < endIndex; ri++)
       rfPolygonToSegmentsCollection(rejects[ri], segments);
   }
   segmenter.rejectRange(startIndex, endIndex, rcMuscleSegmenter::cRejCodeEdge);
   if (startIndex != endIndex) {
     // Red color, line width of 2 display pixel, 0.0 pixel origin
     rcVisualStyle rejectCell(rfRgb(0, 0, 0), 4, rc2Fvector(0.0f, 0.0f));
     // Set drawing style
     segments.push_back(rejectCell);
     for (int32 ri = startIndex; ri < endIndex; ri++)
       rfPolygonToSegmentsCollection(rejects[ri], segments);
   }
   segmenter.rejectRange(startIndex, endIndex,
             rcMuscleSegmenter::cRejCodeActivity);
   if (startIndex != endIndex) {
     // Red color, line width of 4 display pixel, 0.0 pixel origin
     rcVisualStyle rejectCell(rfRgb(0, 10, 128), 2, rc2Fvector(0.0f, 0.0f));
     // Set drawing style
     segments.push_back(rejectCell);
     for (int32 ri = startIndex; ri < endIndex; ri++)
       rfPolygonToSegmentsCollection(rejects[ri], segments);
   }
 }
void rcEngineImpl::registeredWindows (vector< rcWindow > & focusImages, int32 & range) protected
Referenced by entropyTrackerWindow().
void rcEngineImpl::reportOnBadGrabber (const rcVectorGrabber & imageGrabber) const protected
Definition at line 1965 of file rc_engineimpl.cpp.
References _observer, eFrameErrorOK, endl(), rcFrameGrabber::getErrorString(), rcVectorGrabber::getLastError(), and rcEngineObserver::notifyError().
Referenced by muscleTracker().
 {
   rcFrameGrabberError error = imageGrabber.getLastError();
   // Display grabber error message
   if (error != eFrameErrorOK) {
     strstream s;
     s << rcFrameGrabber::getErrorString( error ) << " "
         << const_cast<rcVectorGrabber&>(imageGrabber).getInputSourceName() << ends;
     _observer->notifyError(s.str());
     s.freeze(false);
     cerr << s.str() << endl;
   }
 }
void rcEngineImpl::reset (void) virtual
Implements rcEngine.
Definition at line 617 of file rc_engineimpl.cpp.
References _captureThread, _importThread, _inputMode, _settingMutex, eCmd, eFile, endl(), rcThread::isRunning(), rcThread::join(), lock(), rmAssert, rcThread::start(), and unlockedReset().
 {
   rcInputMode inputMode;
   {
     rcLock lock( _settingMutex );
     unlockedReset();
     inputMode = _inputMode;
   }
   if (inputMode != eFile && inputMode != eCmd) {
     rmAssert(!_importThread || !_importThread->isRunning());
     if (_captureThread) {
       if (_captureThread->isRunning()) {
                 cout << "    reset capture thread shutdown ";
                 int status = _captureThread->join();
                 if (status)
                     cout << "error " << status << endl;
                 else
                     cout << "OK" << endl;
       }
       _captureThread->start();
     }
   }
 }
void rcEngineImpl::resumePreview ()
Definition at line 687 of file rc_engineimpl.cpp.
References mSlidingEnergyPreviewWriter, and rcScalarWriter::reset().
Referenced by rcEngineMovieSaver::closeHdlr().
 {
   // Reset writer, remove all segments and reset start time
   if ( mSlidingEnergyPreviewWriter )
     mSlidingEnergyPreviewWriter->reset();
 }
bool rcEngineImpl::resumeTracking (void) virtual
Implements rcEngine.
Definition at line 359 of file rc_engineimpl.cpp.
References _isPausedToggle, and rcAtomicValue< T >::setValue().
 {
   bool tmp (false);
   _isPausedToggle.setValue (tmp);
   return tmp == false;
 }
int rcEngineImpl::saveFrames (std::string imageExportDir) const protected
Definition at line 459 of file rc_engineimplload.cpp.
References _exportImagesDir, _fileImages, endl(), rcTimestamp::now(), rfImageExport2JPG(), and rcTimestamp::secs().
Referenced by rcEngineImporter::run().
 {
     if (imageExportDir.empty()) return 0;
     vector<rcWindow>::const_iterator imgItr = _fileImages.begin ();
     rcTimestamp duration = rcTimestamp::now();
     int32 i = 0;
     for (; imgItr != _fileImages.end(); imgItr++, i++)
     {
         std::ostringstream oss;
         oss << _exportImagesDir << "/" << "image" << setfill ('0') << setw(4) << i << ".jpg";
         std::string fn (oss.str ());
         rfImageExport2JPG ( *imgItr, fn);
         fn = std::string ("chmod 644 ") + fn;
         system( fn.c_str() );
     }
     // Done. Report
     duration = rcTimestamp::now() - duration;
     cout <<  endl << i << " Images Exported in " << duration.secs() << "Seconds" << endl;
     return i;
 }
void rcEngineImpl::setCameraInfo (const rcMovieFileCamExt & info)
Definition at line 695 of file rc_engineimpl.cpp.
References _cameraInfo, _settingMutex, lock(), and rcMovieFileCamExt::log().
Referenced by rcEngineMovieSaver::closeHdlr(), and rcEngineMovieCapture::run().
 {
   rcLock lock( _settingMutex);
   strstream s;
   // Write log to stream
   info.log( s, false ); // Don't show undefined values
   s << ends;
   _cameraInfo = s.str();
   s.freeze();
 }
void rcEngineImpl::setCaptureInfo (const rcMovieFileOrgExt & info)
Definition at line 709 of file rc_engineimpl.cpp.
References _captureLog, _settingMutex, lock(), and rcMovieFileOrgExt::log().
Referenced by rcEngineMovieSaver::closeHdlr().
 {
   rcLock lock( _settingMutex);
   strstream s;
   // Write log to stream
   info.log( s );
   s << ends;
   _captureLog = s.str();
   s.freeze();
 }
void rcEngineImpl::setCaptureInfo (const rcMovieFileOrgExt & org, const rcMovieFileExpExt & exp)
Definition at line 723 of file rc_engineimpl.cpp.
References _captureLog, _settingMutex, endl(), lock(), rcMovieFileOrgExt::log(), and rcMovieFileExpExt::log().
 {
   rcLock lock( _settingMutex);
   strstream s;
   // Write log to stream
   org.log( s );
   s << endl << "Experiment:" << endl;
   exp.log( s );
   s << ends;
   _captureLog = s.str();
   s.freeze();
 }
void rcEngineImpl::setFrameSize (uint32 width, uint32 height, rcPixel depth)
Definition at line 672 of file rc_engineimpl.cpp.
References _frameDepth, _frameHeight, and _frameWidth.
Referenced by loadFrames(), rcEngineMovieCapture::run(), and unlockedReset().
 {
   _frameWidth = width;
   _frameHeight = height;
   _frameDepth = depth;
 }
bool rcEngineImpl::setFromArgs (int32 argc, char ** argv)
Definition at line 62 of file rc_engineimplcmdline.cpp.
References _batchMode, _cLineEndFrame, _cLineRectSize, _cLineRectTL, _cLineStartFrame, _exportImagesDir, _outputFileName, _saveFormat, _useMask, rcCmdLine::atoi(), cAnalysisACI, cAnalysisACIOptionSettingId, cAnalysisACISlidingWindow, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisCellGeneral, cAnalysisCellMuscle, cAnalysisCellTypeId, cAnalysisChannelSettingId, cAnalysisFirstFrameSettingId, cAnalysisLabeledFluorescence, cAnalysisModeSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisObjectSettingId, cAnalysisTemplateTracking, cExportBodyGraphicsSettingId, cExportMotionVectorsSettingId, cGlobalMotionEstId, cInputImageFilesSettingId, cInputModeSettingId, cInputMovieFileSettingId, rcSimilarator::eACI, eAnalyzerResultOriginCenter, eCmd, eExperimentAllFormat, eExperimentCSVFormat, eExperimentNativeFormat, eMacroDRGdiffusionProcessing, endl(), rcSimilarator::eVisualEntropy, rcCmdLine::getArgument(), rcCmdLine::getSafeArgument(), rcCmdLine::hasSwitch(), model2use(), NOP, rcVisibleBatchUsage(), rfGetDirEntries(), rmAssert, rmExceptionMacro, rmMax, rmMin, setSettingValue(), and rcCmdLine::splitLine().
Referenced by main().
 {
   _batchMode = true;
   rcCmdLine cmd;
   if (cmd.splitLine (argc, argv) < 1)
     {
       cerr << "Too Few Arguments" << endl;
       return false;
     }
   if (cmd.hasSwitch ("-h"))
     {
       rcVisibleBatchUsage (cerr);
       return 0;
     }
   string ACI ("aci"), VEN ("vis"), DIF ("dif"), CELL ("cell"), CARDIO ("myo");
   string EML ("eml"), CSV ("csv"), MCA ("mca"), SMOOTH ("smooth"), FLU ("flu");
   string BODY ("body"), MOTION ("motion"), ALL ("all"), EXPOSURE ("exp"), DRG ("drg");
   string DRGAUTOMASK ("drgautomask");
   string NOP (""), TEMPLATE ("target");
   string analysis, cell, report, graphics, movie, result, advanced, exportImages, tiffdir, model2use;
   // Get the required arguments
   try
     {
       analysis = cmd.getArgument ("-analysis", 0);
       result = cmd.getArgument ("-result", 0);
     }
   catch (...)
     {
       rmExceptionMacro (<< "-analysis -result options are required" << endl);
     }
   try
     {
       movie = cmd.getArgument ("-movie", 0);
     }
   catch (...)
     {
         cout << "Not a movie, is it a directory of tiffs \n";
       try
       {
         tiffdir = cmd.getArgument ("-dirOfTiffs", 0);
       }
       catch (...)
       {
           rmExceptionMacro (<< "either movie or tiff directory options are required" << endl);
       }
     }
   // Get the optional stuff
   // @note: some parameters are set using setSettingId and some directly in the engine
   // the choice largely mirrors what takes place in rc_engineimpl.cpp
   report = cmd.getSafeArgument ("-report", 0, "csv");
   cell = cmd.getSafeArgument ("-type", 0, "general");
   graphics = cmd.getSafeArgument ("-graphics", 0, "no");
   advanced = cmd.getSafeArgument ("-advanced", 0, "no");
   exportImages = cmd.getSafeArgument ("-exportImages", 0, "");
   _cLineStartFrame  = cmd.atoi(cmd.getSafeArgument("-Frame", 0, "-1"));
   _cLineEndFrame  = cmd.atoi(cmd.getSafeArgument("-Frame", 1, "-1"));
   _cLineStartFrame = rmMin (_cLineStartFrame, _cLineEndFrame);
   _cLineEndFrame = rmMax (_cLineStartFrame, _cLineEndFrame);
   _cLineRectTL = rcIPair (cmd.atoi(cmd.getSafeArgument("-TopLeft", 0, "-1")),
           cmd.atoi(cmd.getSafeArgument("-TopLeft", 1, "-1")));
   _cLineRectSize = rcIPair (cmd.atoi(cmd.getSafeArgument("-Size", 0, "-1")),
                 cmd.atoi(cmd.getSafeArgument("-Size", 1, "-1")));
   int32 maxDisp = cmd.atoi(cmd.getSafeArgument("-MaxDisplacement", 0, "2"));
   rcValue maxTrackDisp (maxDisp);
   int32 channel = cmd.atoi (cmd.getSafeArgument("-Channel", 0, "0"));
   rcValue channelVal (int(channel));
   // @note: First things first, we only accept movies and are in command mode
   rcValue cmdline (eCmd);
   setSettingValue( cInputModeSettingId, cmdline);
   setSettingValue ( cAnalysisChannelSettingId, channelVal);
   setSettingValue (cAnalysisMotionTrackingSpeedSettingId, maxTrackDisp);
   setSettingValue (cGlobalMotionEstId, maxTrackDisp);
   int32 halfWindowSize = cmd.atoi(cmd.getSafeArgument("-halfWindow", 0, "0"));
   int32 windowSize = halfWindowSize * 2 + 1;
   setSettingValue (cAnalysisACISlidingWindowSizeSettingId, windowSize);
   int32 sformat = (int) eExperimentNativeFormat;
   sformat = (int) eExperimentNativeFormat;
   if (report == CSV)
    {
       sformat = (int) eExperimentCSVFormat;
     }
   else if (report == ALL)
     {
       sformat = (int) eExperimentAllFormat;
     }
   _saveFormat = (rcExperimentFileFormat) sformat;
   if (advanced == DRG)
     {
       setSettingValue (cAnalysisObjectSettingId, eMacroDRGdiffusionProcessing);
       _useMask = 0;
     }
   //  Set to the default
  if (halfWindowSize < 1)
    {
      setSettingValue( cAnalysisModeSettingId, cAnalysisACI);
    }
  else
    {
      setSettingValue( cAnalysisModeSettingId, cAnalysisACISlidingWindow);
      setSettingValue (cAnalysisACISlidingWindowOriginSettingId, eAnalyzerResultOriginCenter);
    }
  setSettingValue( cAnalysisACIOptionSettingId, rcSimilarator::eACI);
  setSettingValue( cAnalysisFirstFrameSettingId, 0);
  setSettingValue (cAnalysisCellTypeId, cAnalysisCellGeneral);
   // Set Rect if passed and valid
   if (cell == CARDIO)
     {
       setSettingValue (cAnalysisCellTypeId, cAnalysisCellMuscle);
     }
   if (cell == FLU)
     {
       setSettingValue (cAnalysisCellTypeId, cAnalysisLabeledFluorescence);
     }
   if (analysis == VEN)
     {
       cerr << "analysis: " << VEN << endl;
       setSettingValue( cAnalysisACIOptionSettingId, rcSimilarator::eVisualEntropy);
       //      _aciOptions = rcSimilarator::eVisualEntropy;
     }
     else if (analysis == TEMPLATE)
     {
       setSettingValue( cAnalysisModeSettingId,cAnalysisTemplateTracking);
     }
   else
     {
       cerr << "Default ACI Option Selected" << endl;
     }
   if (graphics == MOTION)
     {
       setSettingValue (cExportMotionVectorsSettingId, true);
     }
   else if (graphics == BODY)
     {
       setSettingValue (cExportBodyGraphicsSettingId, true);
     }
   if (movie != NOP)
   {
     rcValue inputFile(movie);
     setSettingValue( cInputMovieFileSettingId, inputFile);
     _outputFileName = result;
     _exportImagesDir = exportImages;
    return true;
   }
   else
   {
       rmAssert (tiffdir != NOP);
       vector<std::string> files;
       //@note gets tiff files: .tif or .TIF
       rfGetDirEntries (tiffdir, files);
       if (files.size())
       {
           // Iterate all selected files
           string selectedFiles;
           vector<std::string>::iterator it = files.begin();
           while (it != files.end())
           {
               string sg (it->c_str ());
               if (sg != NOP)
               {
                   // Create a list of semicolon separated file names
                   selectedFiles += sg;
                   selectedFiles +=";";
               }
               ++it;
           }
           if (!selectedFiles.empty())
           {
               rcValue inputDir (selectedFiles);
               setSettingValue( cInputImageFilesSettingId, inputDir);
               _outputFileName = result;
               return true;
           }
       }
   }
   rmExceptionMacro (<< "Visible Command Line Error " << endl);
 }
void rcEngineImpl::setInternalState (rcEngineState newState) protected
Definition at line 1213 of file rc_engineimpl.cpp.
References _isPausedToggle, _observer, eEnginePlayback, eEngineProcessing, eEngineRunning, eEngineShuttingDown, eEngineStopped, eEngineUninitialized, getState(), rcEngineObserver::notifyState(), PRINT_STATE_CHANGE, setState(), and rcAtomicValue< T >::setValue().
Referenced by analyze(), engineAbort(), initialize(), loadFrames(), start(), and stop().
 {
   // ignore setting to current state
   if (newState == getState())
     return;
   // validate state transition
   rcEngineState foo;
   switch (foo = getState())
     {
     case eEngineUninitialized:  // engine has not been initialized
       if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eUninitialized" );
       break;
     case eEngineStopped:            // engine is stopped and not generating data
       if (newState != eEngineRunning && newState != eEnginePlayback
                     && newState != eEngineProcessing )
                 throw general_exception( "illegal state transition from eEngineStopped" );
       break;
     case eEngineRunning:            // engine is running and generating data
       if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eEngineRunning" );
       _isPausedToggle.setValue (false);     // set pause default off setting
       break;
     case eEnginePlayback:           // engine is in playback mode
       if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eEnginePlayback" );
       break;
     case eEngineProcessing:            // engine is processing a focus area
       if (newState != eEngineStopped)
                 throw general_exception( "illegal state transition from eEngineProcessing" );
       _isPausedToggle.setValue (false);     // set pause default off setting
       break;
     case eEngineShuttingDown:       // engine is in the process of shutting down
       throw general_exception( "illegal state transition from eEngineShuttingDown" );
       break;
     }
   PRINT_STATE_CHANGE("setInternalState", getState(), newState);
   setState(newState);
   if ( _observer ) {
     _observer->notifyState( newState );
   }
 }
void rcEngineImpl::setPathNameToTemplate (std::string argv0)
void rcEngineImpl::setSettingValue (int settingId, const rcValue & value) virtual
Implements rcSettingSource.
Definition at line 247 of file rc_engineimplsettings.cpp.
References _aciOptions, _aciTemporalSampling, _analysisAffine, _analysisFirstFrame, _analysisLastFrame, _analysisMode, _analysisRect, _analysisTreatmentObject, _batchMode, _bodyVectorWriter, _cameraInfo, _captureCtrl, _captureThread, _cellType, _channelConversion, _developmentGraphicsEnabled, _developmentVideoEnabled, _enableGlobalMotionEst, _exportBodyGraphics, _exportMotionVectors, _fpsCalculator, _frameRate, _imageFileNames, _importThread, _inputMode, _inputSource, _ippMode, _model2useAbsPathFileName, _motionTrackingBodyHistoryVectorDisplay, _motionTrackingBodyVectorDisplay, _motionTrackingFrameSampling, _motionTrackingMaxSpeed, _motionTrackingMotionVectorDisplay, _motionTrackingTargetSize, _motionTrackingTargetSizeMultiplier, _motionVectorWriter, _movieCapture, _movieFile, _msPerContraction, _observer, _playbackCtrl, _playbackThread, _player, _saveCtrl, _segmentationVectorDisplay, _settingMutex, _showCellPath, _showCellPosition, _showCellText, _slidingWindowOrigin, _slidingWindowSize, _statType, _useMask, _videoCacheP, _visualizeDevelopment, assertInitialized(), rcVideoCaptureCtrl::binning(), cAnalysisACIMaskSettingId, cAnalysisACIOptionSettingId, cAnalysisACISlidingWindow, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisACIStepSettingId, cAnalysisCellGeneral, cAnalysisCellMuscle, cAnalysisCellMuscleSelected, cAnalysisCellTracking, cAnalysisCellTypeId, cAnalysisChannelSettingId, cAnalysisDevelopmentGraphicsDisplaySettingId, cAnalysisDevelopmentVideoDisplaySettingId, cAnalysisFirstFrameSettingId, cAnalysisLastFrameSettingId, cAnalysisModeSettingId, cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId, cAnalysisMotionTrackingBodyVectorDisplaySettingId, cAnalysisMotionTrackingFrameSampleSettingId, cAnalysisMotionTrackingMotionVectorDisplaySettingId, cAnalysisMotionTrackingMultiplierSettingId, cAnalysisMotionTrackingSampleSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisMotionTrackingTargetSettingId, cAnalysisMuscleAutoGenPeriodId, cAnalysisMuscleMsPerContractionDefault, cAnalysisMuscleSegmentationVectorDisplaySettingId, cAnalysisObjectSettingId, cAnalysisRectSettingId, cAnalysisStatTypeId, rcEngineMovieCapture::captureStatus(), cCameraAcquireDelayTimeSettingId, cCameraAcquireTimeSettingId, cCameraFrameRateSettingId, cExportBodyGraphicsSettingId, cExportMotionVectorsSettingId, cFrameRateSettingId, cGlobalMotionEstId, cImagePreMappingSettingId, cInputBinningSettingId, cInputGainSettingId, cInputImageFilesSettingId, cInputModeSettingId, cInputMovieFileSettingId, cInputShutterSettingId, cMaxSaveFrameCount, cOutputMovieFileSettingId, cPlaybackCtrlSettingId, cTemplateFileNameId, rcMoviePlaybackCtrl::ctrlInfo(), cVisualizeCellPathSettingId, cVisualizeCellPositionSettingId, cVisualizeCellTextSettingId, cVisualizeDevelopmentSettingId, cVisualizeFocusRotationSettingId, rcVideoCaptureCtrl::decimationRate(), eCamera, eCmd, rcSettingInfo::eCurrentSpeedMask, rcSettingInfo::eCurrentStateMask, rcSettingInfo::eCurrentStateRev, rcSettingInfo::eCurrentStateStopped, eFile, eImages, eMovie, eMoviePlaybackState_Initialized, endl(), rcMovieSaveCtrl::frameCaptureDelayTime(), rcMovieSaveCtrl::frameCaptureTime(), framesLoaded(), rcVideoCaptureCtrl::gain(), rcMoviePlaybackCtrlReader::getCtrlInfo(), rcEngineObserver::getCursorTime(), rcVideoCaptureCtrlReader::getDecimationRate(), rcVideoCaptureStatusReader::getMaxFramesPerSecond(), rcMoviePlaybackStatusReader::getState(), rcThread::isRunning(), rcThread::join(), lock(), rcMovieSaveCtrl::movieFileName(), rcEngineObserver::notifyStatus(), rcMovieSaveCtrl::outputFileName(), rcEngineMoviePlayback::playbackStatus(), rcDEFAULT_FRAMES_PER_SEC, rcFpsCalculator::reset(), rmAssert, rcTimestamp::secs(), rcWriter::setExportable(), setTimeLineRange(), rcEngineMoviePlayback::setupTimeCtrlPlayback(), rcVideoCaptureCtrl::shutter(), rcVideoCaptureCtrl::slidingWindowOrigin(), rcVideoCaptureCtrl::slidingWindowSize(), rcThread::start(), and updateHeaderLogs().
Referenced by analyze(), loadFrames(), setFromArgs(), and start().
 {
     bool captureThreadStart = false;
     bool importThreadStart = false;
     bool playbackThreadStart = false;
     bool captureThreadStop = false;
     bool importThreadStop = false;
     bool playbackThreadStop = false;
     { // Locked block
         rcLock lock( _settingMutex);
         assertInitialized();
         switch (settingId)
         {
             case cInputModeSettingId:
                 _observer->notifyStatus(""); // Clear status bar
                 _inputMode = (rcInputMode)(int)value;
                 switch (_inputMode) {
                     case eCamera:
                     {
                         _fpsCalculator.reset();
                         _cameraInfo = "";
                         _frameRate = rcDEFAULT_FRAMES_PER_SEC;
                         captureThreadStart = true;
                         importThreadStop = true;
                         playbackThreadStop = true;
                         _analysisMode = cAnalysisACISlidingWindow;
                         _aciOptions = static_cast<rcSimilarator::rcEntropyDefinition> (static_cast<int> (value));
                         break;
                     }
                     case eFile:
                     {
                         _frameRate = 0;
                         captureThreadStop = true;
                         break;
                     }
                     case eCmd:
                     {
                         _frameRate = 1; // @todo Frame rate should be read from image files.
                         captureThreadStop = true;
                         break;
                     }
                         // Note: no default case to force a compiler warning if a
                         // new enum value is defined without adding a corresponding
                         // case statement here.
                 }
                 updateHeaderLogs();
                 break;
             case cFrameRateSettingId:
                 _frameRate = value;
                 break;
             case cCameraFrameRateSettingId:
             {
                 int inputValue = (int)value;
                 if (inputValue >= 1) {
                     _captureCtrl.decimationRate((uint32)(int)value);
                     // Update timeline range in camera mode when
                     // frame rate changes
                     if ( _inputMode != eFile )
                         setTimeLineRange();
                 }
             }
                 break;
             case cCameraAcquireTimeSettingId:
             {
                 int inputValue = (int)value;
                 if (inputValue >= 0) {
                     // Throttle max capture time based on max number of frames that can be
                     // captured
                     const double maxRate = _movieCapture->captureStatus().getMaxFramesPerSecond();
                     const int maxSeconds = (uint32)(cMaxSaveFrameCount/(1.0*maxRate/_captureCtrl.getDecimationRate())) -1;
                     int maxTime = maxSeconds/60;
                     if ( inputValue > maxTime )
                         inputValue = maxTime;
                     _saveCtrl.frameCaptureTime((uint32)inputValue);
                 }
             }
                 break;
             case cCameraAcquireDelayTimeSettingId:
             {
                 int inputValue = (int)value;
                 if (inputValue >= 0)
                     _saveCtrl.frameCaptureDelayTime((uint32)inputValue);
             }
                 break;
             case cInputMovieFileSettingId:
                 _movieFile = (std::string) value;
                 _inputMode = (_batchMode) ? eCmd : eFile;
                 _inputSource = eMovie;
                 importThreadStart = true;
                 importThreadStop = true; // (_inputMode == eCmd) ? false : true;
                 captureThreadStop = true;
                 playbackThreadStop = true;
                 break;
             case cInputImageFilesSettingId:
                 _imageFileNames = (std::string) value;
                 _inputMode = (_batchMode) ? eCmd : eFile;
                 _inputSource = eImages;
                 importThreadStart = true;
                 importThreadStop = true;
                 captureThreadStop = true;
                 playbackThreadStop = true;
                 break;
             case cOutputMovieFileSettingId:
                 // Set capture output file name as movie input file name
                 _movieFile = (std::string) value;
                 _saveCtrl.outputFileName(_movieFile);
                 _saveCtrl.movieFileName(_movieFile);
                 break;
             case cAnalysisRectSettingId:
                 if (_inputMode == eFile || _inputMode == eCmd)
                     _analysisRect = value;
                 break;
             case cAnalysisACIOptionSettingId:
                 _aciOptions = static_cast<rcSimilarator::rcEntropyDefinition> (static_cast<int> (value));
                 break;
             case cAnalysisACISlidingWindowSizeSettingId:
             {
                 int newSize = value;
                 // Zero size window is not allowed
                 if ( newSize < 2 )
                     newSize = 2;
                 if (_inputMode == eCamera)
                     _captureCtrl.slidingWindowSize(value);
                 else
                     _slidingWindowSize = value;
             }
                 break;
             case cAnalysisACISlidingWindowOriginSettingId:
             {
                 int val = value;
                 if (_inputMode == eCamera)
                     _captureCtrl.slidingWindowOrigin((rcAnalyzerResultOrigin)val);
                 else
                     _slidingWindowOrigin = rcAnalyzerResultOrigin(val);
             }
                 break;
             case cAnalysisACIStepSettingId:
             {
                 int val = value;
                 _aciTemporalSampling = val;
                 break;
             }
             case cAnalysisACIMaskSettingId:
             {
                 int val = value;
                 _useMask = val;
                 break;
             }
             case cAnalysisMotionTrackingTargetSettingId:
                 _motionTrackingTargetSize = value;
                 break;
             case  cAnalysisMotionTrackingMultiplierSettingId:
                 _motionTrackingTargetSizeMultiplier = value;
                 break;
             case cAnalysisMotionTrackingSampleSettingId:
           _aciTemporalSampling = value;
                 break;
             case cAnalysisMotionTrackingSpeedSettingId:
                 _motionTrackingMaxSpeed = value;
                 break;
             case cAnalysisMotionTrackingMotionVectorDisplaySettingId:
                 _motionTrackingMotionVectorDisplay = value;
                 break;
             case cAnalysisMuscleSegmentationVectorDisplaySettingId:
                 _segmentationVectorDisplay = value;
                 break;
             case cAnalysisMotionTrackingBodyVectorDisplaySettingId:
                 _motionTrackingBodyVectorDisplay = value;
                 break;
             case cAnalysisMotionTrackingBodyHistoryVectorDisplaySettingId:
                 _motionTrackingBodyHistoryVectorDisplay = value;
                 break;
             case cAnalysisMotionTrackingFrameSampleSettingId:
                 _motionTrackingFrameSampling = value;
                 break;
                 // Use same control for temporal sampling
                 //            case cAnalysisMotionTrackingStepSettingId:
                 //                _motionTrackingStep = value;
                 //                break;
             case cPlaybackCtrlSettingId:
             {
                 int newCtrlInfo = value;
                 int playbackCtrlInfo = _playbackCtrl.getCtrlInfo();
                 int chgdCtrlInfo = newCtrlInfo ^ playbackCtrlInfo;
                 if (chgdCtrlInfo & rcSettingInfo::eCurrentStateStopped) {
                     if (newCtrlInfo & rcSettingInfo::eCurrentStateStopped)
                         playbackThreadStop = true;
                     else {
                         importThreadStop = true;
                         playbackThreadStart = true;
                         playbackThreadStop = true;
                     }
                 }
                 const int32 maxPlaybackSpeed = 1000000;
                 int32 speed = newCtrlInfo & rcSettingInfo::eCurrentSpeedMask;
                 if (speed > maxPlaybackSpeed) {
                     speed = maxPlaybackSpeed;
                     newCtrlInfo =
               (newCtrlInfo & rcSettingInfo::eCurrentStateMask) |
               maxPlaybackSpeed;
                 }
                 _playbackCtrl.ctrlInfo(newCtrlInfo);
                 if (playbackThreadStart) {
                     rmAssert(_player);
                     rmAssert(_videoCacheP);
                     if (newCtrlInfo & rcSettingInfo::eCurrentStateRev)
                         speed = -speed;
                     fprintf(stderr, "time %f speed %d\n",
                                     _observer->getCursorTime().secs(), speed);
                     _player->setupTimeCtrlPlayback(*_videoCacheP,
                                                                                  _observer->getCursorTime(),
                                                                                  speed,
                                                                                  5);
                     rmAssert(_player->playbackStatus().getState() ==
                                      eMoviePlaybackState_Initialized);
                 }
             }
                 break;
             case cImagePreMappingSettingId:
             {
                 int val = value;
                 _ippMode = (rcIPPMode) val;
             }
           break;
             case cTemplateFileNameId:
                             _model2useAbsPathFileName = (std::string) value;
                           break;
             case cAnalysisModeSettingId:
                 _analysisMode = value;
                 if (_analysisMode != cAnalysisCellTracking) {
                     _cellType = cAnalysisCellGeneral;
                     _msPerContraction = cAnalysisMuscleMsPerContractionDefault;
                 }
                 break;
             case cAnalysisCellTypeId:
                 _cellType = value;
                 if (! (_cellType == cAnalysisCellMuscle || _cellType == cAnalysisCellMuscleSelected) )
                     {
                         _msPerContraction = cAnalysisMuscleMsPerContractionDefault;
                     }
                 _motionTrackingTargetSize = 5;
                 break;
             case cAnalysisMuscleAutoGenPeriodId:
           _msPerContraction = value;
           break;
             case cVisualizeCellTextSettingId:
                 _showCellText = value;
                 break;
             case cVisualizeCellPositionSettingId:
                 _showCellPosition = value;
                 break;
             case cVisualizeCellPathSettingId:
                 _showCellPath = value;
                 break;
             case cExportMotionVectorsSettingId:
                 _exportMotionVectors = value;
                 if ( _motionVectorWriter ) {
                     // Set track exportability
                     rcWriter* writer = dynamic_cast<rcWriter*>(_motionVectorWriter);
                     if ( writer )
                         writer->setExportable( _exportMotionVectors );
                 }
                 break;
             case cExportBodyGraphicsSettingId:
                 _exportBodyGraphics = value;
                 if ( _bodyVectorWriter ) {
                     // Set track exportability
                     rcWriter* writer = dynamic_cast<rcWriter*>(_bodyVectorWriter);
                     if ( writer ) {
                         writer->setExportable( _exportBodyGraphics );
                     }
                 }
                 break;
             case cVisualizeFocusRotationSettingId:
           _analysisAffine = value;
                 break;
             case cAnalysisFirstFrameSettingId:
                 _analysisFirstFrame = value;
                 if ( _analysisFirstFrame > int(framesLoaded())-1 )
                     _analysisFirstFrame = framesLoaded()-1;
                 if ( _analysisFirstFrame > _analysisLastFrame )
                     _analysisFirstFrame = _analysisLastFrame;
                 break;
             case cAnalysisLastFrameSettingId:
                 _analysisLastFrame = value;
                 if ( _analysisLastFrame > int(framesLoaded())-1 )
                     _analysisLastFrame = framesLoaded()-1;
                 if ( _analysisLastFrame < _analysisFirstFrame )
                     _analysisLastFrame = _analysisFirstFrame;
                 break;
             case cAnalysisChannelSettingId:
                 _channelConversion = static_cast<rcChannelConversion>(int(value));
                 break;
             case cAnalysisObjectSettingId:
                 _analysisTreatmentObject = value;
                 break;
                 //            case cAnalysisTreatmentObjectSizeSettingId:
                 //                _analysisTreatmentObjectSize = value;
                 //                break;
             case cAnalysisDevelopmentVideoDisplaySettingId:
                 _developmentVideoEnabled = value;
                 break;
             case cAnalysisDevelopmentGraphicsDisplaySettingId:
                 _developmentGraphicsEnabled = value;
                 break;
             case cVisualizeDevelopmentSettingId:
                 _visualizeDevelopment = value;
                 break;
             case cAnalysisStatTypeId:
           _statType = value;
           break;
             case   cGlobalMotionEstId:
                 _enableGlobalMotionEst = value;
                 break;
             case cInputGainSettingId:
                 _captureCtrl.gain(int(value));
                 break;
             case cInputShutterSettingId:
                 _captureCtrl.shutter(int(value));
                 break;
             case cInputBinningSettingId:
           _captureCtrl.binning(int(value));
                 break;
         } // End of: switch (settingId)
     } // End of: Locked block
     /* Done setting new values. Start and stop any threads based on
      * these new settings. Do here both to combine logic and to
      * guarantee capture thread can grab _settingMutex.
      */
     if (importThreadStop && _importThread && _importThread->isRunning()) {
         cout << "    import thread shutdown ";
         int status = _importThread->join();
         if (status)
             cout << "error " << status << endl;
         else
             cout << "OK" << endl;
     }
     if (captureThreadStop && _captureThread && _captureThread->isRunning()) {
         cout << "    capture thread shutdown ";
         int status = _captureThread->join();
         if (status)
             cout << "error " << status << endl;
         else
             cout << "OK" << endl;
         _observer->notifyStatus("Ready"); // Clear status bar
     }
     if (playbackThreadStop && _playbackThread && _playbackThread->isRunning()) {
         cout << "    playback thread shutdown ";
         int status = _playbackThread->join();
         if (status)
             cout << "error " << status << endl;
         else
             cout << "OK" << endl;
         _observer->notifyStatus("Ready"); // Clear status bar
     }
     if (importThreadStart && _importThread)
         {
             _importThread->start();
         }
     if (captureThreadStart && _captureThread) {
         _captureThread->start();
     }
     if (playbackThreadStart && _playbackThread) {
         _playbackThread->start();
     }
     uint32 activeThreads = 0;
     activeThreads += (_captureThread && _captureThread->isRunning()) ? 1 : 0;
     activeThreads += (_importThread && _importThread->isRunning()) ? 1 : 0;
     activeThreads += (_playbackThread && _playbackThread->isRunning()) ? 1 : 0;
     rmAssert(activeThreads < 2);
 }
void rcEngineImpl::setState (rcEngineState newState) protected
Definition at line 328 of file rc_engineimpl.cpp.
References _state, and rcAtomicValue< T >::setValue().
Referenced by internalReset(), setInternalState(), shutdown(), and unlockedReset().
 {
   return _state.setValue(newState);
 }
void rcEngineImpl::setTimeLineRange ()
Definition at line 740 of file rc_engineimpl.cpp.
References _captureCtrl, _observer, rcVideoCaptureCtrlReader::getDecimationRate(), getElapsedTime(), rcEngineObserver::notifyTimelineRange(), and rcDEFAULT_FRAMES_PER_SEC.
Referenced by setSettingValue(), and startPreview().
 {
   // Set preview timeline range to 200 frames at current speed
   int rate = (int)_captureCtrl.getDecimationRate();
   double rangeLen =  100 * (1/rcDEFAULT_FRAMES_PER_SEC) * rate;
   rcTimestamp elapsed = getElapsedTime();
   _observer->notifyTimelineRange( elapsed-rangeLen, elapsed );
 }
void rcEngineImpl::shutdown (void) virtual
Implements rcEngine.
Definition at line 216 of file rc_engineimpl.cpp.
References _analyzer, _analyzerThread, _captureThread, _importer, _importThread, _movieCapture, _playbackThread, _player, eEngineShuttingDown, endl(), getState(), rcThread::isRunning(), rcThread::join(), PRINT_STATE_CHANGE, and setState().
 {
   PRINT_STATE_CHANGE("shutdown", getState(), eEngineShuttingDown);
   setState(eEngineShuttingDown);
   cout << "\nEngine shutdown sequence started\n";
   if ((_captureThread != 0) && (_captureThread->isRunning()))
     {
       cout << "    capture thread shutdown ";
       int status = _captureThread->join();
       if ( status )
                 cout << "error " << status << endl;
       else
                 cout << "OK" << endl;
     }
   if ((_importThread != 0) && (_importThread->isRunning()))
     {
       cout << "    import thread shutdown ";
       int status = _importThread->join();
       if ( status )
                 cout << "error " << status << endl;
       else
                 cout << "OK" << endl;
     }
   if ((_analyzerThread != 0) && (_analyzerThread->isRunning()))
     {
       cout << "    analyzer thread shutdown ";
       int status = _analyzerThread->join();
       if ( status )
                 cout << "error " << status << endl;
       else
                 cout << "OK" << endl;
     }
   if ((_playbackThread != 0) && (_playbackThread->isRunning()))
     {
       cout << "    playback thread shutdown ";
       int status = _playbackThread->join();
       if ( status )
                 cout << "error " << status << endl;
       else
                 cout << "OK" << endl;
     }
   // Delete all data
   delete _captureThread;
   _captureThread= 0;
   delete _importThread;
   _importThread = 0;
   delete _importer;
   _importer = 0;
   delete _movieCapture;
   _movieCapture = 0;
   delete _analyzer;
   _analyzer = 0;
   delete _playbackThread;
   _playbackThread = 0;
   delete _player;
   _player = 0;
   cout << "Engine shutdown sequence finished\n";
 }
void rcEngineImpl::start (void) virtual
Implements rcEngine.
Definition at line 420 of file rc_engineimpl.cpp.
References _analysisFirstFrame, _analysisRect, _cLineEndFrame, _cLineRectSize, _cLineRectTL, _cLineStartFrame, _firstFrameSaved, _frameFocus, _frameHeight, _frameWidth, _groupCount, _importThread, _inputMode, _isPausedToggle, _movieFile, _observer, _outputFileName, _processCount, _resourceFolderPath, _startTime, _writerManager, _writerSizeLimit, cAnalysisACISlidingWindowOriginSettingId, cAnalysisACISlidingWindowSizeSettingId, cAnalysisCellTypeId, cAnalysisFirstFrameSettingId, cAnalysisLastFrameSettingId, cAnalysisModeSettingId, cAnalysisMotionTrackingSpeedSettingId, cAnalysisObjectSettingId, cAnalysisRectSettingId, rcRectangle< T >::contains(), cPlaybackCtrlSettingId, create_filespec(), createSharedWriters(), cTemplateFileNameId, eCamera, eCmd, rcSettingInfo::eCurrentStateStopped, eEnginePlayback, eEngineRunning, eFile, endl(), framesLoaded(), getSettingValue(), rcThread::isRunning(), rcThread::join(), rcEngineObserver::notifyStatus(), rmAssert, setInternalState(), setSettingValue(), rcAtomicValue< T >::setValue(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcEngineMoviePlayback::run(), rcEngineMovieCapture::run(), and rcEngineMovieSaver::waitHdlr().
 {
 #ifdef STATE_CHG_DEBUG
   fprintf(stderr, "rcEngineImpl::start called\n");
 #endif
   //_writerSizeLimit = 10;
   createSharedWriters();
   switch (_inputMode)
     {
     case eFile:
         {
             _isPausedToggle.setValue (false);
             int pCtrl = getSettingValue(cPlaybackCtrlSettingId);
             if ((pCtrl & rcSettingInfo::eCurrentStateStopped) == 0) {
                 setInternalState( eEnginePlayback );
 #if 0
                 std::string modelFile = create_filespec (_resourceFolderPath,
                                                                                                          std::string ("tip"),
                                                                                                          std::string ("tif"));
                 setSettingValue ( cTemplateFileNameId, rcValue(modelFile));
 #endif
             }
         }
       break;
     case eCamera:
         {
             // Reset start time
             _startTime = 0.0;
             _isPausedToggle.setValue (false);
             _firstFrameSaved.setValue(true);
             _processCount++;
             rcRect iRect( 0, 0, _frameWidth, _frameHeight );
             rcEngineFocusData* temp =
             new rcEngineFocusData( _writerManager,
                                                         getSettingValue( cAnalysisRectSettingId ),
                                                         iRect,
                                                         1,
                                                         static_cast<rcAnalysisMode>(int(getSettingValue( cAnalysisModeSettingId ))),
                                                         _writerSizeLimit,
                                                         int(getSettingValue( cAnalysisACISlidingWindowSizeSettingId )),
                                                         rcAnalyzerResultOrigin(int(getSettingValue( cAnalysisACISlidingWindowOriginSettingId ))),
                                                         _groupCount,
                                                         static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisMotionTrackingSpeedSettingId))),
                                                         static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisObjectSettingId))),
                                                         static_cast<unsigned>(static_cast<int>(getSettingValue( cAnalysisCellTypeId))));
             _frameFocus.setValue(temp);
             setInternalState( eEngineRunning );
         }
       break;
     case eCmd:
         {
             if (_inputMode == eCmd && _importThread ) {
                 if (_importThread->isRunning()) {
                     int status = _importThread->join();
                     if (status)
                         cout << "error " << status << endl;
                 }
                 // Now using movie file information interprete first frame last frame
                 // TBD: another cmdline function
                 setSettingValue (cAnalysisFirstFrameSettingId, 0);
                 setSettingValue (cAnalysisLastFrameSettingId, framesLoaded() - 1);
                 if (_cLineStartFrame >= 0 && _cLineStartFrame < framesLoaded())
                     setSettingValue (cAnalysisFirstFrameSettingId, _cLineStartFrame);
                 if (_cLineEndFrame >= 0 && _cLineEndFrame < framesLoaded() &&
                         _cLineEndFrame > _analysisFirstFrame)
                     setSettingValue (cAnalysisLastFrameSettingId, _cLineEndFrame);
                 rcIRect cmdRect (_cLineRectTL.x(), _cLineRectTL.y(), _cLineRectSize.x(), _cLineRectSize.y());
                 if (_analysisRect.contains (cmdRect))
                     setSettingValue (cAnalysisRectSettingId, rcValue (cmdRect));
             }
             ostringstream buf;
             buf << "Analyzing " << _movieFile.c_str() <<
             " saving results to " << _outputFileName.c_str();
             _observer->notifyStatus( buf.str().c_str() );
             setInternalState( eEngineRunning);
         }
       break;
     default:
       rmAssert (0);
     }
 }
void rcEngineImpl::startPreview ()
Definition at line 680 of file rc_engineimpl.cpp.
References createCameraPreviewWriters(), and setTimeLineRange().
Referenced by rcEngineMovieCapture::run().
 {
   createCameraPreviewWriters();
   setTimeLineRange();
 }
void rcEngineImpl::stop (void) virtual
Implements rcEngine.
Definition at line 513 of file rc_engineimpl.cpp.
References _observer, eEngineStopped, rcEngineObserver::notifyStatus(), and setInternalState().
Referenced by rcEngineMovieSaver::closeHdlr(), rcEngineMovieSaver::doneHdlr(), muscleTracker(), rcEngineMoviePlayback::playbackCleanup(), and rcEngineMovieCapture::run().
 {
 #ifdef STATE_CHG_DEBUG
   fprintf(stderr, "rcEngineImpl::stop called\n");
 #endif
   setInternalState( eEngineStopped );
   _observer->notifyStatus( "Stopping..." );
 }
bool rcEngineImpl::storingLiveInput (void) virtual
Implements rcEngine.
Definition at line 347 of file rc_engineimpl.cpp.
References _movieCapture, eMovieFileState_Save, and rcEngineMovieCapture::saveState().
 {
   return ( _movieCapture->saveState() == eMovieFileState_Save );
 }
void rcEngineImpl::unlock () virtual
Implements rcCarbonLock.
Definition at line 763 of file rc_engineimpl.cpp.
References _observer, and rcEngineObserver::notifyLockApp().
 {
   if ( _observer )
     _observer->notifyLockApp( false );
 }
void rcEngineImpl::unlockedReset () virtual
Definition at line 579 of file rc_engineimpl.cpp.
References _analysisRect, _bodyHistoryVectorWriter, _bodyVectorWriter, _currentTime, _energyPlotWriter, _fileImages, _fpsCalculator, _graphicsWriterGroup, _groupCount, _motionVectorWriter, _movieCapture, _movieFile, _processCount, _saveCtrl, _segmentVectorWriter, _startTime, _videoCacheP, _videoWriter, _writerGroup, eEngineStopped, getState(), mPreviewWriterGroup, mSlidingEnergyPreviewWriter, rcMovieSaveCtrl::outputFileName(), PRINT_STATE_CHANGE, rcPixelUnknown, rcVideoCache::rcVideoCacheDtor(), rcFpsCalculator::reset(), rcEngineMovieCapture::saveReset(), setFrameSize(), setState(), and updateHeaderLogs().
Referenced by internalReset(), and reset().
 {
   //_observer; // Retain old value
   //_captureThread; // TODO: do the right thing
   _startTime = 0.0;
   _currentTime = 0.0;
   _fileImages.clear();
   _movieFile = "";
   _saveCtrl.outputFileName("");
   if (_movieCapture)
     _movieCapture->saveReset();
   _analysisRect = rcRect(0, 0, 0, 0);
   _motionVectorWriter = 0;
   _bodyVectorWriter = 0;
   _bodyHistoryVectorWriter = 0;
   _segmentVectorWriter = 0;
   _energyPlotWriter = 0;
   _videoWriter = (rcVideoWriter*) (0); // The old one should have been freed by observer
   //    _selectedPolys.setValue (0); // as above
   _writerGroup = 0;
   _graphicsWriterGroup = 0;
   mPreviewWriterGroup = 0;
   mSlidingEnergyPreviewWriter = 0;
   _processCount = 0;
   _groupCount = 0;
   if (_videoCacheP) {
     rcVideoCache::rcVideoCacheDtor(_videoCacheP);
     _videoCacheP = 0;
   }
   _fpsCalculator.reset();
   // set default attributes
   setFrameSize( 640, 480, rcPixelUnknown );
   updateHeaderLogs();
   PRINT_STATE_CHANGE("unlockedReset", getState(), eEngineStopped);
   setState(eEngineStopped); // Do not send a notification
 }
void rcEngineImpl::updateCameraLog () protected
Definition at line 1800 of file rc_engineimpl.cpp.
References _cameraInfo, _inputMode, _videoCacheP, eFile, endl(), rcMovieFileCamExt::log(), and rcVideoCache::movieFileCameras().
Referenced by updateHeaderLogs().
 {
   if (_inputMode == eFile) {
     if ( _videoCacheP ) {
       // Camera headers
       const vector<rcMovieFileCamExt>& camExts = _videoCacheP->movieFileCameras();
       if ( !camExts.empty() ) {
                 strstream s;
                 for ( uint32 i = 0; i < camExts.size(); ++i ) {
                     rcMovieFileCamExt cam = camExts[i];
                     // Write log to stream
                     cam.log( s, false ); // Don't show undefined values
                     if ( i < (camExts.size()-1))
                         s << endl;
                 }
                 s << ends;
                 s.freeze();
                 _cameraInfo = s.str();
       } else
                 _cameraInfo = "Unspecified";
     } else
       _cameraInfo = " ";
   } else
     _cameraInfo = " ";
 }
void rcEngineImpl::updateCaptureLog () protected
Definition at line 1759 of file rc_engineimpl.cpp.
References _captureLog, _inputMode, _videoCacheP, rcVideoCache::averageFrameRate(), eFile, endl(), rcVideoCache::movieFileExperiments(), and rcVideoCache::movieFileOrigins().
Referenced by updateHeaderLogs().
 {
   if (_inputMode == eFile) {
     if ( _videoCacheP ) {
       strstream s;
       // Origin headers
       const vector<rcMovieFileOrgExt>& orgExts = _videoCacheP->movieFileOrigins();
       if ( !orgExts.empty() ) {
                 for ( uint32 i = 0; i < orgExts.size(); ++i ) {
                     // Write log to stream
                     orgExts[i].log( s );
                     if ( i < (orgExts.size()-1) )
                         s << endl;
                 }
       }
       // Add Avg frame rate
       s << " AvgFrameRate " << _videoCacheP->averageFrameRate() << " fps";
       // Experiment headers
       const vector<rcMovieFileExpExt>& expExts = _videoCacheP->movieFileExperiments();
       if ( !expExts.empty() ) {
                 s << endl << endl;
                 for ( uint32 i = 0; i < expExts.size(); ++i ) {
                     s << "Experiment:" << endl;
                     // Write log to stream
                     expExts[i].log( s );
                     if ( i < (expExts.size()-1) )
                         s << endl;
                 }
       }
       s << ends;
       s.freeze();
       _captureLog = s.str();
     } else
       _captureLog = " ";
   } else
     _captureLog = " ";
 }
void rcEngineImpl::updateConversionLog () protected
Definition at line 1828 of file rc_engineimpl.cpp.
References _conversionInfo, _inputMode, _videoCacheP, eFile, endl(), rcMovieFileConvExt::log(), and rcVideoCache::movieFileConversions().
Referenced by updateHeaderLogs().
 {
   if (_inputMode == eFile) {
     if ( _videoCacheP ) {
       strstream s;
       // Conversion headers
       const vector<rcMovieFileConvExt>& cnvExts = _videoCacheP->movieFileConversions();
       if ( !cnvExts.empty() ) {
                 s  << "Applied Conversions ["<< cnvExts.size() << "]"
                 << endl;
                 for ( uint32 i = 0; i < cnvExts.size(); ++i ) {
                     s << endl;
                     rcMovieFileConvExt cnv = cnvExts[i];
                     // Write log to stream
                     cnv.log( s );
                 }
                 s << ends;
                 s.freeze(); // Without freeze(), strstream::str() leaks the string it returns
                 _conversionInfo = s.str();
       }
       else
                 _conversionInfo = "No conversions";
     } else
       _conversionInfo = " ";
   } else
     _conversionInfo = " ";
 }
void rcEngineImpl::updateHeaderLogs () protected
Definition at line 1751 of file rc_engineimpl.cpp.
References updateCameraLog(), updateCaptureLog(), and updateConversionLog().
Referenced by loadFrames(), setSettingValue(), and unlockedReset().
 {
   updateCameraLog();
   updateCaptureLog();
   updateConversionLog();
 }
void rcEngineImpl::writeEntropyData (rcEngineFocusData * focus, const vector< rcWindow > & images, const vector< double > & signal) protected
Definition at line 1660 of file rc_engineimpl.cpp.
References count(), rcEngineFocusData::energyWriter(), rcEngineFocusData::focusRect(), rcRectangle< T >::height(), rcEngineFocusData::plotterWriter(), rfPlot1Dsignal(), rfRgb, rmAssert, rcVisualGraphicsCollection::segments(), rcRectangle< T >::width(), writeTimedScalar(), rcGraphicsWriter::writeValue(), rcRect::x(), and rcRect::y().
Referenced by entropyTracker().
 {
   rmAssert( signal.size() == images.size() );
   rcScalarWriter* sWriter = focus->energyWriter();
   rcGraphicsWriter* plotter = focus->plotterWriter();
   rcVisualGraphicsCollection graphics;
   if ( plotter) {
     rcVisualSegmentCollection& segments = graphics.segments();
     // Green color, line width of 1 display pixel, 0.0 pixel origin
     rcVisualStyle style( rfRgb( 10, 140, 220 ), 1, rc2Fvector( 0.0f, 0.0f ) );
     rcVisualStyle laststyle( rfRgb( 220, 140, 10 ), 1, rc2Fvector( 0.0f, 0.0f ) );
 #if 0
     rcFRect frame ((float) focus->focusRect().x(),
                                      (float) focus->focusRect().y(),
                                      (float) focus->focusRect().width(),
                                      (float) focus->focusRect().height());
     rfPlot1Dsignal (signal.begin(), signal.end(), frame, segments);
 #endif
     for ( uint32 i = 0; i < images.size(); ++i )
       {
                 segments.push_back( (i == images.size () - 1) ? laststyle : style );
                 segments.push_back(rcVisualRect (images[i].rectangle ()));
                 plotter->writeValue( images[i].frameBuf()->timestamp(), focus->focusRect(), graphics );
       }
   }
   int32 count = writeTimedScalar (focus, signal, images, sWriter);
   rmAssert (count != 0);
 }
int rcEngineImpl::writeTimedFloats (const rcEngineFocusData * focus, const vector< float > & signal, const vector< rcWindow > & focusImages, rcScalarWriter * writer) protected
Definition at line 1495 of file rc_engineimpl.cpp.
References count(), rcEngineFocusData::focusRect(), and rcScalarWriter::writeValue().
 {
   int32 count (0);
   if (signal.size())
     {
       for ( int32 i = 0; i < focusImages.size() ; i++ )
                 {
                     // Write all data
                     writer->writeValue( focusImages[i].frameBuf()->timestamp(), focus->focusRect(), (double) signal[i]);
                     count++;
                 }
     }
   return count;
 }
int rcEngineImpl::writeTimedScalar (const rcEngineFocusData * focus, const vector< double > & signal, const vector< rcWindow > & focusImages, rcScalarWriter * writer) protected
Definition at line 1477 of file rc_engineimpl.cpp.
References count(), rcEngineFocusData::focusRect(), and rcScalarWriter::writeValue().
Referenced by entropyTrackerWindow(), and writeEntropyData().
 {
   int32 count (0);
   if (signal.size())
     {
       for ( uint32 i = 0; i < focusImages.size(); ++i )
                 {
                     // Write all data
                     writer->writeValue( focusImages[i].frameBuf()->timestamp(), focus->focusRect(), signal[i]);
                     count++;
                 }
     }
   return count;
 }
Friends And Related Function Documentation
friend class rcEngineImporter friend
Definition at line 270 of file rc_engineimpl.h.
Referenced by initialize().
Member Data Documentation
rcSimilarator::rcEntropyDefinition rcEngineImpl::_aciOptions protected
Definition at line 451 of file rc_engineimpl.h.
Referenced by entropyTracker(), entropyTrackerWindow(), getSettingValue(), internalReset(), and setSettingValue().
int32 rcEngineImpl::_aciTemporalSampling protected
Definition at line 458 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcAffineRectangle rcEngineImpl::_analysisAffine protected
Definition at line 450 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
int32 rcEngineImpl::_analysisFirstFrame protected
Definition at line 471 of file rc_engineimpl.h.
Referenced by analyze(), analyzeFocusArea(), framesToAnalyze(), getSettingValue(), internalReset(), loadFrames(), setSettingValue(), and start().
int32 rcEngineImpl::_analysisLastFrame protected
Definition at line 472 of file rc_engineimpl.h.
Referenced by analyze(), analyzeFocusArea(), framesToAnalyze(), getSettingValue(), internalReset(), loadFrames(), and setSettingValue().
int rcEngineImpl::_analysisMode protected
Definition at line 449 of file rc_engineimpl.h.
Referenced by analyze(), analyzeFocusArea(), getSettingValue(), internalReset(), isSettingEnabled(), and setSettingValue().
rcRect rcEngineImpl::_analysisRect protected
Definition at line 448 of file rc_engineimpl.h.
Referenced by createCameraPreviewWriters(), createGraphicsWriters(), createSharedWriters(), getSettingValue(), setSettingValue(), start(), and unlockedReset().
int rcEngineImpl::_analysisTreatmentObject protected
Definition at line 477 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), isSettingEnabled(), and setSettingValue().
int rcEngineImpl::_analysisTreatmentObjectSize protected
Definition at line 478 of file rc_engineimpl.h.
rcEngineAnalyzer* rcEngineImpl::_analyzer protected
Definition at line 525 of file rc_engineimpl.h.
Referenced by initialize(), and shutdown().
rcThread* rcEngineImpl::_analyzerThread protected
Definition at line 526 of file rc_engineimpl.h.
Referenced by initialize(), process(), rcEngineImpl(), shutdown(), and ~rcEngineImpl().
bool rcEngineImpl::_batchMode protected
Definition at line 441 of file rc_engineimpl.h.
Referenced by isSettingEnabled(), setFromArgs(), and setSettingValue().
rcGraphicsWriter* rcEngineImpl::_bodyHistoryVectorWriter protected
Definition at line 505 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), flushGraphicsWriters(), and unlockedReset().
rcGraphicsWriter* rcEngineImpl::_bodyVectorWriter protected
Definition at line 504 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), flushGraphicsWriters(), postTrackingResults(), setSettingValue(), and unlockedReset().
std::string rcEngineImpl::_cameraInfo protected
Definition at line 475 of file rc_engineimpl.h.
Referenced by getSettingValue(), setCameraInfo(), setSettingValue(), and updateCameraLog().
rcVideoCaptureCtrl rcEngineImpl::_captureCtrl protected
Definition at line 518 of file rc_engineimpl.h.
Referenced by getSettingValue(), initialize(), isSettingEnabled(), setSettingValue(), and setTimeLineRange().
std::string rcEngineImpl::_captureLog protected
Definition at line 474 of file rc_engineimpl.h.
Referenced by getSettingValue(), setCaptureInfo(), and updateCaptureLog().
rcThread* rcEngineImpl::_captureThread protected
Definition at line 516 of file rc_engineimpl.h.
Referenced by initialize(), rcEngineImpl(), reset(), setSettingValue(), shutdown(), and ~rcEngineImpl().
int rcEngineImpl::_cellType protected
Definition at line 482 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), isSettingEnabled(), and setSettingValue().
rcChannelConversion rcEngineImpl::_channelConversion protected
Definition at line 473 of file rc_engineimpl.h.
Referenced by analyzeFocusArea(), entropyTracker(), entropyTrackerWindow(), getSettingValue(), internalReset(), ipp(), and setSettingValue().
int32 rcEngineImpl::_cLineEndFrame protected
Definition at line 556 of file rc_engineimpl.h.
Referenced by internalReset(), setFromArgs(), and start().
rcIPair rcEngineImpl::_cLineRectSize protected
Definition at line 554 of file rc_engineimpl.h.
Referenced by internalReset(), setFromArgs(), and start().
rcIPair rcEngineImpl::_cLineRectTL protected
Definition at line 553 of file rc_engineimpl.h.
Referenced by internalReset(), setFromArgs(), and start().
int32 rcEngineImpl::_cLineStartFrame protected
Definition at line 555 of file rc_engineimpl.h.
Referenced by internalReset(), setFromArgs(), and start().
std::string rcEngineImpl::_conversionInfo protected
Definition at line 476 of file rc_engineimpl.h.
Referenced by getSettingValue(), and updateConversionLog().
rcTimestamp rcEngineImpl::_currentTime protected
Definition at line 500 of file rc_engineimpl.h.
Referenced by frameInterrupt(), getElapsedTime(), loadFrames(), and unlockedReset().
bool rcEngineImpl::_developmentGraphicsEnabled protected
Definition at line 480 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
bool rcEngineImpl::_developmentVideoEnabled protected
Definition at line 479 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
int rcEngineImpl::_enableGlobalMotionEst protected
Definition at line 487 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
bool rcEngineImpl::_energyGraphicsEnabled protected
Definition at line 485 of file rc_engineimpl.h.
Referenced by internalReset().
rcGraphicsWriter* rcEngineImpl::_energyPlotWriter protected
Definition at line 507 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), flushGraphicsWriters(), and unlockedReset().
bool rcEngineImpl::_exportBodyGraphics protected
Definition at line 469 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), getSettingValue(), internalReset(), and setSettingValue().
bool rcEngineImpl::_exportEnergyGraphics protected
Definition at line 486 of file rc_engineimpl.h.
Referenced by internalReset().
std::string rcEngineImpl::_exportImagesDir protected
Definition at line 559 of file rc_engineimpl.h.
Referenced by rcEngineImporter::run(), saveFrames(), and setFromArgs().
bool rcEngineImpl::_exportMotionVectors protected
Definition at line 468 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), getSettingValue(), internalReset(), and setSettingValue().
vector<rcWindow> rcEngineImpl::_fileImages protected
Definition at line 530 of file rc_engineimpl.h.
Referenced by analyzeFocusArea(), framesLoaded(), loadFrames(), saveFrames(), and unlockedReset().
rcAtomicValue<bool> rcEngineImpl::_firstFrameSaved protected
Definition at line 520 of file rc_engineimpl.h.
Referenced by frameInterrupt(), and start().
rcFpsCalculator rcEngineImpl::_fpsCalculator protected
Definition at line 512 of file rc_engineimpl.h.
Referenced by frameInterrupt(), processCapturedData(), setSettingValue(), and unlockedReset().
int rcEngineImpl::_frameDepth protected
Definition at line 492 of file rc_engineimpl.h.
Referenced by entropyTracker(), entropyTrackerWindow(), getAttributes(), isSettingEnabled(), and setFrameSize().
rcAtomicValue<rcEngineFocusData*> rcEngineImpl::_frameFocus protected
Definition at line 511 of file rc_engineimpl.h.
Referenced by frameFlush(), frameInterrupt(), start(), and ~rcEngineImpl().
int rcEngineImpl::_frameHeight protected
Definition at line 491 of file rc_engineimpl.h.
Referenced by analyze(), getAttributes(), isEntire(), loadFrames(), setFrameSize(), and start().
float rcEngineImpl::_frameRate protected
Definition at line 445 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), loadImages(), loadMovie(), and setSettingValue().
int rcEngineImpl::_frameWidth protected
Definition at line 490 of file rc_engineimpl.h.
Referenced by analyze(), getAttributes(), isEntire(), loadFrames(), setFrameSize(), and start().
rcWriterGroup* rcEngineImpl::_graphicsWriterGroup protected
Definition at line 502 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), createSharedWriters(), and unlockedReset().
uint32 rcEngineImpl::_groupCount protected
Definition at line 510 of file rc_engineimpl.h.
Referenced by analyze(), start(), and unlockedReset().
std::string rcEngineImpl::_imageFileNames protected
Definition at line 447 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), loadImages(), and setSettingValue().
rcEngineImporter* rcEngineImpl::_importer protected
Definition at line 533 of file rc_engineimpl.h.
Referenced by initialize(), shutdown(), and ~rcEngineImpl().
rcThread* rcEngineImpl::_importThread protected
Definition at line 532 of file rc_engineimpl.h.
Referenced by initialize(), rcEngineImpl(), reset(), setSettingValue(), shutdown(), start(), and ~rcEngineImpl().
rcInputMode rcEngineImpl::_inputMode protected
Definition at line 443 of file rc_engineimpl.h.
Referenced by analyze(), createSharedWriters(), getSettingValue(), internalReset(), isSettingEditable(), isSettingEnabled(), isSettingPersistable(), loadFrames(), makeTmpName(), process(), reset(), setSettingValue(), start(), updateCameraLog(), updateCaptureLog(), and updateConversionLog().
rcInputSource rcEngineImpl::_inputSource protected
Definition at line 442 of file rc_engineimpl.h.
Referenced by internalReset(), isSettingEnabled(), rcEngineImporter::run(), and setSettingValue().
std::string rcEngineImpl::_installPath protected
Definition at line 565 of file rc_engineimpl.h.
rcIPPMode rcEngineImpl::_ippMode protected
Definition at line 444 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcAtomicValue<bool> rcEngineImpl::_isPausedToggle protected
Definition at line 568 of file rc_engineimpl.h.
Referenced by pauseTracking(), resumeTracking(), setInternalState(), and start().
rcWindow rcEngineImpl::_model2use protected
Definition at line 563 of file rc_engineimpl.h.
Referenced by model2use(), modelTracker(), and postTrackingResults().
std::string rcEngineImpl::_model2useAbsPathFileName protected
Definition at line 562 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
bool rcEngineImpl::_motionTrackingBodyHistoryVectorDisplay protected
Definition at line 465 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
bool rcEngineImpl::_motionTrackingBodyVectorDisplay protected
Definition at line 464 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
int32 rcEngineImpl::_motionTrackingFrameSampling protected
Definition at line 466 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
int32 rcEngineImpl::_motionTrackingMaxSpeed protected
Definition at line 462 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
bool rcEngineImpl::_motionTrackingMotionVectorDisplay protected
Definition at line 463 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
int32 rcEngineImpl::_motionTrackingSampleSize protected
Definition at line 461 of file rc_engineimpl.h.
int32 rcEngineImpl::_motionTrackingStep protected
Definition at line 467 of file rc_engineimpl.h.
int32 rcEngineImpl::_motionTrackingTargetSize protected
Definition at line 459 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
int32 rcEngineImpl::_motionTrackingTargetSizeMultiplier protected
Definition at line 460 of file rc_engineimpl.h.
Referenced by getSettingValue(), and setSettingValue().
rcGraphicsWriter* rcEngineImpl::_motionVectorWriter protected
Definition at line 503 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), flushGraphicsWriters(), setSettingValue(), and unlockedReset().
rcEngineMovieCapture* rcEngineImpl::_movieCapture protected
Definition at line 517 of file rc_engineimpl.h.
Referenced by frameInterrupt(), getAttributes(), getSettingValue(), initialize(), isSettingEditable(), processCapturedData(), rcEngineImpl(), setSettingValue(), shutdown(), storingLiveInput(), unlockedReset(), and ~rcEngineImpl().
std::string rcEngineImpl::_movieFile protected
Definition at line 446 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), loadMovie(), makeTmpName(), muscleTracker(), setSettingValue(), start(), and unlockedReset().
int rcEngineImpl::_msPerContraction protected
Definition at line 484 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcEngineObserver* rcEngineImpl::_observer protected
Definition at line 496 of file rc_engineimpl.h.
Referenced by analyze(), analyzeFocusArea(), engineAbort(), entropyTracker(), entropyTrackerWindow(), initialize(), loadFrames(), loadImages(), loadMovie(), lock(), modelTracker(), muscleTracker(), processCapturedData(), rcEngineImpl(), reportOnBadGrabber(), setInternalState(), setSettingValue(), setTimeLineRange(), start(), stop(), and unlock().
vector<rc2Fvector> rcEngineImpl::_offsetsToFirst protected
Definition at line 531 of file rc_engineimpl.h.
Referenced by isSettingEditable().
std::string rcEngineImpl::_outputFileName protected
Definition at line 550 of file rc_engineimpl.h.
Referenced by setFromArgs(), and start().
rcMoviePlaybackCtrl rcEngineImpl::_playbackCtrl protected
Definition at line 539 of file rc_engineimpl.h.
Referenced by getSettingValue(), initialize(), internalReset(), and setSettingValue().
rcThread* rcEngineImpl::_playbackThread protected
Definition at line 540 of file rc_engineimpl.h.
Referenced by initialize(), rcEngineImpl(), setSettingValue(), shutdown(), and ~rcEngineImpl().
rcEngineMoviePlayback* rcEngineImpl::_player protected
Definition at line 541 of file rc_engineimpl.h.
Referenced by getSettingValue(), initialize(), rcEngineImpl(), setSettingValue(), shutdown(), and ~rcEngineImpl().
uint32 rcEngineImpl::_previewWriterSizeLimit protected
Definition at line 453 of file rc_engineimpl.h.
Referenced by createCameraPreviewWriters(), and internalReset().
uint32 rcEngineImpl::_processCount protected
Definition at line 527 of file rc_engineimpl.h.
Referenced by analyze(), isSettingEditable(), loadFrames(), start(), and unlockedReset().
std::string rcEngineImpl::_resourceFolderPath protected
Definition at line 564 of file rc_engineimpl.h.
Referenced by analyze(), initialize(), and start().
rcMovieSaveCtrl rcEngineImpl::_saveCtrl protected
Definition at line 519 of file rc_engineimpl.h.
Referenced by getSettingValue(), initialize(), internalReset(), setSettingValue(), and unlockedReset().
rcExperimentFileFormat rcEngineImpl::_saveFormat protected
Definition at line 549 of file rc_engineimpl.h.
Referenced by setFromArgs().
bool rcEngineImpl::_segmentationVectorDisplay protected
Definition at line 470 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcGraphicsWriter* rcEngineImpl::_segmentVectorWriter protected
Definition at line 506 of file rc_engineimpl.h.
Referenced by createGraphicsWriters(), flushGraphicsWriters(), muscleTracker(), and unlockedReset().
rcPolygonGroupRef rcEngineImpl::_selectedPolys protected
Definition at line 569 of file rc_engineimpl.h.
Referenced by muscleTracker(), and notifyEngineOfPolys().
rcMutex rcEngineImpl::_settingMutex protected
Definition at line 456 of file rc_engineimpl.h.
Referenced by getSettingValue(), isSettingEditable(), isSettingEnabled(), isSettingPersistable(), reset(), setCameraInfo(), setCaptureInfo(), and setSettingValue().
vector<rcSettingCategory> rcEngineImpl::_settings protected
Definition at line 493 of file rc_engineimpl.h.
Referenced by getNSettingCategories(), getSettingCategory(), and initialize().
bool rcEngineImpl::_showCellPath protected
Definition at line 546 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
bool rcEngineImpl::_showCellPosition protected
Definition at line 545 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
bool rcEngineImpl::_showCellText protected
Definition at line 544 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcAnalyzerResultOrigin rcEngineImpl::_slidingWindowOrigin protected
Definition at line 455 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
int rcEngineImpl::_slidingWindowSize protected
Definition at line 454 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcTimestamp rcEngineImpl::_startTime protected
Definition at line 499 of file rc_engineimpl.h.
Referenced by frameInterrupt(), getElapsedTime(), getStartTime(), loadFrames(), start(), and unlockedReset().
rcAtomicValue<rcEngineState> rcEngineImpl::_state protected
Definition at line 489 of file rc_engineimpl.h.
Referenced by getState(), and setState().
int rcEngineImpl::_statType protected
Definition at line 483 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
int32 rcEngineImpl::_useMask protected
Definition at line 457 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), setFromArgs(), and setSettingValue().
rcVideoCache* rcEngineImpl::_videoCacheP protected
Definition at line 534 of file rc_engineimpl.h.
Referenced by analyze(), analyzeFocusArea(), ipp(), isSettingEditable(), loadFrames(), loadMovie(), muscleTracker(), rcEngineImpl(), setSettingValue(), unlockedReset(), updateCameraLog(), updateCaptureLog(), and updateConversionLog().
rcEngineProgress* rcEngineImpl::_videoCacheProgress protected
Definition at line 535 of file rc_engineimpl.h.
Referenced by initialize(), loadMovie(), and ~rcEngineImpl().
rcAtomicValue<rcVideoWriter*> rcEngineImpl::_videoWriter protected
Definition at line 509 of file rc_engineimpl.h.
Referenced by createSharedWriters(), flushSharedWriters(), loadFrames(), processCapturedData(), and unlockedReset().
bool rcEngineImpl::_visualizeDevelopment protected
Definition at line 481 of file rc_engineimpl.h.
Referenced by getSettingValue(), internalReset(), and setSettingValue().
rcWriterGroup* rcEngineImpl::_writerGroup protected
Definition at line 501 of file rc_engineimpl.h.
Referenced by createSharedWriters(), and unlockedReset().
rcWriterManager* rcEngineImpl::_writerManager protected
Definition at line 513 of file rc_engineimpl.h.
Referenced by analyze(), createCameraPreviewWriters(), createGraphicsWriters(), createSharedWriters(), initialize(), rcEngineImpl(), start(), and ~rcEngineImpl().
uint32 rcEngineImpl::_writerSizeLimit protected
Definition at line 452 of file rc_engineimpl.h.
Referenced by analyze(), createGraphicsWriters(), createSharedWriters(), internalReset(), and start().
rcMovieFileOrgExt rcEngineImpl::mOrgExt protected
Definition at line 536 of file rc_engineimpl.h.
Referenced by analyzeFocusArea().
rcWriterGroup* rcEngineImpl::mPreviewWriterGroup protected
Definition at line 521 of file rc_engineimpl.h.
Referenced by createCameraPreviewWriters(), and unlockedReset().
rcScalarWriter* rcEngineImpl::mSlidingEnergyPreviewWriter protected
Definition at line 522 of file rc_engineimpl.h.
Referenced by createCameraPreviewWriters(), processCapturedData(), resumePreview(), and unlockedReset().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimpl.h
src/visible/src/rc_engineimpl.cpp
src/visible/src/rc_engineimpl_modeltracker.cpp
src/visible/src/rc_engineimplcmdline.cpp
src/visible/src/rc_engineimplload.cpp
src/visible/src/rc_engineimplmuscle.cpp
src/visible/src/rc_engineimplsettings.cpp