Visible: rcCorrelationWindow< T > Class Template Reference
rcCorrelationWindow< T > Class Template Reference
#include <include/analysis/rc_correlationwindow.h>
Public Member Functions
rcCorrelationWindow ()
rcCorrelationWindow (const rcWindow &w)
const rcWindow & window () const
bool sumValid () const
double sum () const
double sumSquares () const
int32 x () const
int32 y () const
int32 width () const
int32 height () const
rcPixel depth () const
const uint8 * rowPointer (uint32 y) const
int32 rowUpdate () const
int32 rowPelUpdate () const
const T * rowPelPointer (uint32 y) const
const T * pelPointer (uint32 x, uint32 y) const
const rcSharedFrameBufPtr & frameBuf () const
rcSharedFrameBufPtr & frameBuf ()
void sum (double s)
void sumSquares (double s)
void invalidate ()
bool translate (const rcIPair &o)
Private Attributes
rcWindow mWindow
double mSum
double mSumSquares
bool mSumValid
Detailed Description
template<class T>
class rcCorrelationWindow< T >
Definition at line 17 of file rc_correlationwindow.h.
Constructor & Destructor Documentation
template<class T> rcCorrelationWindow< T >::rcCorrelationWindow () inline
Definition at line 23 of file rc_correlationwindow.h.
                           :
         mWindow(),
         mSum( 0.0 ),
         mSumSquares( 0.0 ),
mSumValid(false) {}
template<class T> rcCorrelationWindow< T >::rcCorrelationWindow (const rcWindow & w) inline
Definition at line 29 of file rc_correlationwindow.h.
                                              :
         mWindow( w ),
         mSum( 0.0 ),
         mSumSquares( 0.0 ),
         mSumValid( false ) {
             // Verify that depths match
             if ( sizeof(T) != static_cast<int>(w.depth()) )
                 throw general_exception( "rcCorrelationWindow ctor: invalid rcWindow depth" );
}
Member Function Documentation
template<class T> rcPixel rcCorrelationWindow< T >::depth () const inline
Definition at line 53 of file rc_correlationwindow.h.
Referenced by rcSimilarator::correlate(), and rfCorrelateWindow().
 { return mWindow.depth(); }
template<class T> const rcSharedFrameBufPtr& rcCorrelationWindow< T >::frameBuf () const inline
Definition at line 63 of file rc_correlationwindow.h.
 { return mWindow.frameBuf(); }
template<class T> rcSharedFrameBufPtr& rcCorrelationWindow< T >::frameBuf () inline
Definition at line 64 of file rc_correlationwindow.h.
 { return mWindow.frameBuf(); }
template<class T> int32 rcCorrelationWindow< T >::height () const inline
Definition at line 51 of file rc_correlationwindow.h.
Referenced by rcSimilarator::correlate(), rcVisualFunction::dividingProcess(), and rfCorrelateWindow().
 { return mWindow.height(); }
template<class T> void rcCorrelationWindow< T >::invalidate () inline
Definition at line 71 of file rc_correlationwindow.h.
Referenced by rcCorrelationWindow< uint8 >::translate().
 { mSumValid = false; };
template<class T> const T* rcCorrelationWindow< T >::pelPointer (uint32 x, uint32 y) const inline
Definition at line 61 of file rc_correlationwindow.h.
 { return (const T*)(mWindow.pelPointer( x, y )); };
template<class T> const T* rcCorrelationWindow< T >::rowPelPointer (uint32 y) const inline
Definition at line 60 of file rc_correlationwindow.h.
 { return (const T*)(mWindow.rowPointer( y )); }
template<class T> int32 rcCorrelationWindow< T >::rowPelUpdate () const inline
Definition at line 58 of file rc_correlationwindow.h.
 { return mWindow.rowUpdate()/sizeof(T); }
template<class T> const uint8* rcCorrelationWindow< T >::rowPointer (uint32 y) const inline
Definition at line 54 of file rc_correlationwindow.h.
Referenced by rfCorrelateWindow().
 { return mWindow.rowPointer( y ); }
template<class T> int32 rcCorrelationWindow< T >::rowUpdate () const inline
Definition at line 55 of file rc_correlationwindow.h.
Referenced by rfCorrelateWindow().
 { return mWindow.rowUpdate(); }
template<class T> double rcCorrelationWindow< T >::sum () const inline
Definition at line 45 of file rc_correlationwindow.h.
Referenced by rfCorrelateWindow(), and rcBasicCorrRowFunc< T >::setCache().
 { rmAssertDebug( mSumValid ); return mSum; }
template<class T> void rcCorrelationWindow< T >::sum (double s) inline
Definition at line 69 of file rc_correlationwindow.h.
 { mSum = s; mSumValid = true; };
template<class T> double rcCorrelationWindow< T >::sumSquares () const inline
Definition at line 46 of file rc_correlationwindow.h.
Referenced by rfCorrelateWindow(), and rcBasicCorrRowFunc< T >::setCache().
 { rmAssertDebug( mSumValid ); return mSumSquares; }
template<class T> void rcCorrelationWindow< T >::sumSquares (double s) inline
Definition at line 70 of file rc_correlationwindow.h.
 { mSumSquares = s; rmAssertDebug( mSumValid ); };
template<class T> bool rcCorrelationWindow< T >::sumValid () const inline
Definition at line 44 of file rc_correlationwindow.h.
Referenced by rfCorrelateWindow(), and rcBasicCorrRowFunc< T >::setCache().
 { return mSumValid; }
template<class T> bool rcCorrelationWindow< T >::translate (const rcIPair & o) inline
Definition at line 73 of file rc_correlationwindow.h.
{
         bool mutated = mWindow.translate( o );
         if ( mutated )
             invalidate();
         return mutated; }
template<class T> int32 rcCorrelationWindow< T >::width () const inline
Definition at line 50 of file rc_correlationwindow.h.
Referenced by rcSimilarator::correlate(), rcVisualFunction::dividingProcess(), and rfCorrelateWindow().
 { return mWindow.width(); }
template<class T> const rcWindow& rcCorrelationWindow< T >::window () const inline
Definition at line 43 of file rc_correlationwindow.h.
Referenced by rcSimilarator::correlate(), rcVisualFunction::dividingProcess(), rcVisualFunction::match(), rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc(), and rcSimilarator::relativeCorrelate().
 { return mWindow; };
template<class T> int32 rcCorrelationWindow< T >::x () const inline
Definition at line 48 of file rc_correlationwindow.h.
 { return mWindow.x(); }
template<class T> int32 rcCorrelationWindow< T >::y () const inline
Definition at line 49 of file rc_correlationwindow.h.
 { return mWindow.y(); }
Member Data Documentation
template<class T> double rcCorrelationWindow< T >::mSum private
Definition at line 81 of file rc_correlationwindow.h.
Referenced by rcCorrelationWindow< uint8 >::sum().
template<class T> double rcCorrelationWindow< T >::mSumSquares private
Definition at line 82 of file rc_correlationwindow.h.
Referenced by rcCorrelationWindow< uint8 >::sumSquares().
template<class T> bool rcCorrelationWindow< T >::mSumValid private
Definition at line 83 of file rc_correlationwindow.h.
Referenced by rcCorrelationWindow< uint8 >::invalidate(), rcCorrelationWindow< uint8 >::sum(), rcCorrelationWindow< uint8 >::sumSquares(), and rcCorrelationWindow< uint8 >::sumValid().
template<class T> rcWindow rcCorrelationWindow< T >::mWindow private
Definition at line 80 of file rc_correlationwindow.h.
Referenced by rcCorrelationWindow< uint8 >::depth(), rcCorrelationWindow< uint8 >::frameBuf(), rcCorrelationWindow< uint8 >::height(), rcCorrelationWindow< uint8 >::pelPointer(), rcCorrelationWindow< uint8 >::rowPelPointer(), rcCorrelationWindow< uint8 >::rowPelUpdate(), rcCorrelationWindow< uint8 >::rowPointer(), rcCorrelationWindow< uint8 >::rowUpdate(), rcCorrelationWindow< uint8 >::translate(), rcCorrelationWindow< uint8 >::width(), rcCorrelationWindow< uint8 >::window(), rcCorrelationWindow< uint8 >::x(), and rcCorrelationWindow< uint8 >::y().
The documentation for this class was generated from the following file:
include/analysis/rc_correlationwindow.h