Visible: TCP_server_data Class Reference
TCP_server_data Class Reference
Public Member Functions
TCP_server_data (void)
~TCP_server_data (void)
TCP_server_data (const TCP_server_data &server)
TCP_server_data & operator= (const TCP_server_data &server)
void set_error (int error)
int error (void) const
std::string message (void) const
bool initialise (unsigned short port, unsigned short queue)
bool initialised (void) const
bool close (void)
bool connection_ready (unsigned wait)
TCP_connection connection (void)
Private Attributes
TCP_socket m_socket
Detailed Description
Definition at line 526 of file tcp.cpp.
Constructor & Destructor Documentation
TCP_server_data::TCP_server_data (void) inline
Definition at line 533 of file tcp.cpp.
     {
     }
TCP_server_data::~TCP_server_data (void) inline
Definition at line 537 of file tcp.cpp.
     {
     }
TCP_server_data::TCP_server_data (const TCP_server_data & server) inline
Definition at line 541 of file tcp.cpp.
     {
       *this = server;
     }
Member Function Documentation
bool TCP_server_data::close (void) inline
Definition at line 600 of file tcp.cpp.
References TCP_socket::close(), and m_socket.
Referenced by TCP_server::close(), and initialise().
     {
       return m_socket.close();
     }
TCP_connection TCP_server_data::connection (void) inline
Definition at line 610 of file tcp.cpp.
References ERRNO, TCP_connection_data::initialise(), INVALID_SOCKET, TCP_connection::m_data, m_socket, set_error(), SOCKET, TCP_socket::socket(), and SOCKLEN_T.
Referenced by TCP_server::connection(), and TCP_connection::TCP_connection().
     {
       TCP_connection connection;
       // accept a connection: the return value is the socket and the address is filled in with the connection details in network order
       sockaddr address;
       SOCKLEN_T address_length = sizeof(address);
       SOCKET connection_socket = accept(m_socket.socket(), &address, &address_length);
       if (connection_socket == INVALID_SOCKET)
         set_error(ERRNO);
       else
       {
         // extract the contents of the address the hard way
         unsigned short network_port = 0;
         memcpy(&network_port, &address.sa_data[0], sizeof(network_port));
         unsigned long network_address = 0;
         memcpy(&network_address, &address.sa_data[2], sizeof(network_address));
         connection.m_data->initialise(connection_socket, ntohl(network_address), ntohs(network_port));
       }
       return connection;
     }
bool TCP_server_data::connection_ready (unsigned wait) inline
Definition at line 605 of file tcp.cpp.
References m_socket, and TCP_socket::receive_ready().
Referenced by TCP_server::connection_ready().
     {
       return m_socket.receive_ready(wait);
     }
int TCP_server_data::error (void) const inline
Definition at line 557 of file tcp.cpp.
References TCP_socket::error(), and m_socket.
Referenced by TCP_server::error().
     {
       return m_socket.error();
     }
bool TCP_server_data::initialise (unsigned short port, unsigned short queue) inline
Definition at line 567 of file tcp.cpp.
References close(), ERRNO, TCP_socket::initialise(), m_socket, set_error(), TCP_socket::socket(), and SOCKET_ERROR.
Referenced by TCP_server::initialise().
     {
       close();
       if (!m_socket.initialise())
         return false;
       // name the socket and bind it to a port - this is a requirement for a server
       unsigned short network_port = htons((unsigned short)port);
       unsigned long network_address = htonl(INADDR_ANY);
       sockaddr server;
       server.sa_family = AF_INET;
       memcpy(&server.sa_data[0], &network_port, sizeof(network_port));
       memcpy(&server.sa_data[2], &network_address, sizeof(network_address));
       if (bind(m_socket.socket(), &server, sizeof(server)) == SOCKET_ERROR)
       {
         set_error(ERRNO);
         close();
         return false;
       }
       // now set the port to listen for incoming connections
       if (listen(m_socket.socket(), (int)queue) == SOCKET_ERROR)
       {
         set_error(ERRNO);
         close();
         return false;
       }
       return true;
     }
bool TCP_server_data::initialised (void) const inline
Definition at line 595 of file tcp.cpp.
References TCP_socket::initialised(), and m_socket.
Referenced by TCP_server::initialised().
     {
       return m_socket.initialised();
     }
std::string TCP_server_data::message (void) const inline
Definition at line 562 of file tcp.cpp.
References m_socket, and TCP_socket::message().
Referenced by TCP_server::message().
     {
       return m_socket.message();
     }
TCP_server_data& TCP_server_data::operator= (const TCP_server_data & server) inline
Definition at line 546 of file tcp.cpp.
References m_socket.
     {
       m_socket = server.m_socket;
       return *this;
     }
void TCP_server_data::set_error (int error) inline
Definition at line 552 of file tcp.cpp.
References m_socket, and TCP_socket::set_error().
Referenced by connection(), and initialise().
     {
       m_socket.set_error(error);
     }
Member Data Documentation
TCP_socket TCP_server_data::m_socket private
Definition at line 529 of file tcp.cpp.
Referenced by close(), connection(), connection_ready(), error(), initialise(), initialised(), message(), operator=(), and set_error().
The documentation for this class was generated from the following file:
include/stlplus/tcp.cpp