Visible: rcAnalyzer Class Reference
rcAnalyzer Class Reference
#include <include/analysis/rc_analyzer.h>
Public Member Functions
rcAnalyzer (const rcAnalyzerOptions &options, rcFrameGrabber &inputSource, bool longTerm=false)
~rcAnalyzer ()
const rcAnalyzerOptions & getOptions () const
rcFrameGrabberError getLastError () const
const vector< float > & longTermEntropies () const
const vector< rc2Fvector > & offsets () const
rcFrameGrabberStatus getNextResult (rcAnalyzerResult &result, bool isBlocking)
rcFrameGrabberStatus reset ()
rcFrameGrabberStatus setOptions (const rcAnalyzerOptions &options)
void setOffsets (vector< rc2Fvector > &offs)
Private Member Functions
bool start ()
bool stop ()
rcFrameGrabberStatus popResult (rcAnalyzerResult &result)
void pushResult (const vector< double > &results)
void pushUndefinedResult ()
bool isValid (const rcAnalyzerOptions &options) const
Private Attributes
rcAnalyzerOptions mOptions
rcFrameGrabber & mInputSource
rcFrameGrabberError mLastError
rcAnalyzerState mState
deque< rcSharedFrameBufPtr > mFrames
deque< double > mResults
rcSimilaratorRef mEnergyCalc
bool mFilled
vector< rcWindow > mImages
vector< rc2Fvector > mOffsets
Detailed Description
Definition at line 163 of file rc_analyzer.h.
Constructor & Destructor Documentation
rcAnalyzer::rcAnalyzer (const rcAnalyzerOptions & options, rcFrameGrabber & inputSource, bool longTerm = false)
Definition at line 13 of file rc_analyzer.cpp.
References rcFrameGrabber::cacheSize(), rcAnalyzerOptions::depth(), eAnalyzerApproximation, eAnalyzerError, rcSimilarator::eApproximate, rcSimilarator::eExhaustive, eFrameErrorInit, rcFrameGrabber::getLastError(), rcFrameGrabber::isValid(), isValid(), mEnergyCalc, mInputSource, mLastError, rcAnalyzerOptions::mode(), mOptions, mState, rmAssert, and rcAnalyzerOptions::windowSize().
                                                                                                      :
   mOptions( options ), mInputSource( inputSource ),
   mLastError( eFrameErrorOK ), mState( eAnalyzerInitialized ), mEnergyCalc( new rcSimilarator () ), mFilled (false)
 {
   if ( !inputSource.isValid() ) {
     mLastError = inputSource.getLastError();
     mState = eAnalyzerError;
   }
   else if ( !isValid( options ) ) {
     // Window size smaller than 1 is absurd, we cannot allow it
     mState = eAnalyzerError;
     mLastError = eFrameErrorInit;
   }
   if (mOptions.windowSize() > 1) {
     rcSimilarator::rcMatrixGeneration genType = rcSimilarator::eExhaustive;
     if (mOptions.mode() == eAnalyzerApproximation)
       genType = rcSimilarator::eApproximate;
     mEnergyCalc = boost::shared_ptr<rcSimilarator> (new rcSimilarator(genType,mOptions.depth(),mOptions.windowSize(), mInputSource.cacheSize()*90/100));
     mEnergyCalc->longTermCache (longTerm);
     rmAssert(mEnergyCalc);
   }
}
rcAnalyzer::~rcAnalyzer ()
Definition at line 38 of file rc_analyzer.cpp.
References eAnalyzerStarted, mState, and stop().
 {
   if ( mState == eAnalyzerStarted )
     stop();
 }
Member Function Documentation
rcFrameGrabberError rcAnalyzer::getLastError () const
Definition at line 240 of file rc_analyzer.cpp.
References mLastError.
Referenced by rcEngineImpl::entropyTrackerWindow().
 {
   return mLastError;
 }
rcFrameGrabberStatus rcAnalyzer::getNextResult (rcAnalyzerResult & result, bool isBlocking)
Definition at line 55 of file rc_analyzer.cpp.
References rcAnalyzerOptions::bound(), cUndefinedEntropy, eAnalyzerCached, eAnalyzerError, eAnalyzerInitialized, eAnalyzerStarted, eAnalyzerStopped, eFrameErrorNotImplemented, eFrameErrorOK, eFrameStatusEOF, eFrameStatusError, eFrameStatusOK, rcRect::empty(), rcAnalyzerOptions::entropyDefinition(), rcFrameGrabber::getLastError(), rcFrameGrabber::getNextFrame(), isValid(), mEnergyCalc, mFilled, mFrames, mImages, mInputSource, mLastError, mOffsets, mOptions, mResults, mState, popResult(), pushResult(), pushUndefinedResult(), rfRound(), rmAssert, rcAnalyzerResult::setEntropy(), rcAnalyzerResult::setFrameBuf(), start(), rcRectangle< T >::translate(), and rcAnalyzerOptions::windowSize().
Referenced by rcEngineImpl::entropyTrackerWindow().
 {
   result.setEntropy( cUndefinedEntropy );
   result.setFrameBuf( 0 );
   rcRect clipRect;
   static double zd (0.0);
   deque <double> results (mOptions.windowSize(), zd);
   vector <double> vresults (results.size(), zd);
   // Error checks
   if ( !isValid( mOptions ) )
     return eFrameStatusError;
   if ( mState == eAnalyzerStopped )
     return eFrameStatusEOF;
   if ( mState == eAnalyzerError )
     return eFrameStatusError;
   if ( mState == eAnalyzerInitialized )
     start();
   if ( mState == eAnalyzerCached ) {
     rmAssert( mFrames.size() == mResults.size() );
     if ( mFrames.empty() )
       return eFrameStatusEOF;
     else
       return popResult( result );
   }
   int32 i = 0;
   if ( mState == eAnalyzerStarted ) {
     rcSharedFrameBufPtr framePtr;
     rcFrameGrabberStatus status = eFrameStatusError;
     if ( isBlocking ) {
       for( ;; ) {
     status = mInputSource.getNextFrame( framePtr, isBlocking );
     if ( status == eFrameStatusOK ) {
       mLastError = eFrameErrorOK;
       // Add new frame to queue
       mFrames.push_back( framePtr );
       if ( mOptions.bound().empty() ) {
         // If bounding rect is empty, analyze whole image
         // Use the size of the first frame
         clipRect = rcRect( 0, 0, mFrames.front()->width(), mFrames.front()->height() );
       }
       else
         {
           clipRect = mOptions.bound();
           if (mOffsets.size())
         {
           static const int32 dummy (0);
           clipRect.translate (rcIPair (rfRound (mOffsets[i].x(), dummy), rfRound (mOffsets[i].y(), dummy)));
         }
         }
       rcWindow w(framePtr, clipRect );
       i++;
       // mImages is only used for initial images to fill the pipe
       if (!mFilled)
         mImages.push_back( w );
       if (mImages.size() <  mOptions.windowSize() )
         {
           pushUndefinedResult();
         }
       else if (!mFilled && mImages.size() == mOptions.windowSize() )
         {
           if (mImages.size() > 1)
         {
           mEnergyCalc->fill (mImages);
           mFilled = mEnergyCalc->entropies (results, mOptions.entropyDefinition());
           rmAssert(mFilled);
           vresults.assign (results.begin(), results.end());
         }
           // Push the appropriate result(s)
           pushResult( vresults );
           // Pop a result
           popResult( result );
           break;
         }
       else
         {
           // Queue is full enough for popping
           rmAssert(mEnergyCalc);
           mEnergyCalc->update (w);
           bool gotSignal = mEnergyCalc->entropies (results, mOptions.entropyDefinition());
           rmAssert(gotSignal);
           vresults.assign (results.begin(), results.end());
           // Push the appropriate result(s)
           pushResult( vresults );
           // Pop a result
           popResult( result );
           break;
         }
     } else if ( status == eFrameStatusEOF )
       {
         // No more frames are available.
         // Compute results and cache them. Subsequent calls will
         // pull results from the cache.
         if ( !mFrames.empty() )
           {
         mState = eAnalyzerCached;
         // Produce the necessary undefined values
         while ( mResults.size() < mFrames.size())
           {
             mResults.push_back( cUndefinedEntropy );
           }
         status = popResult( result );
         }
         else
           {
         // Never got any frames
         mLastError = eFrameErrorOK;
           }
         break;
       }
     else {
       // getNextFrame() failed, bail out
       mLastError = mInputSource.getLastError();
       break;
     }
       }
     } else {
       // Non-blocking operation not implemented yet
       mLastError = eFrameErrorNotImplemented;
       status = eFrameStatusError;
     }
     return status;
   } else {
     // Frame grabber never started!
   }
   return eFrameStatusError;
 }
const rcAnalyzerOptions & rcAnalyzer::getOptions () const
Definition at line 218 of file rc_analyzer.cpp.
References mOptions.
 {
   return mOptions;
 }
bool rcAnalyzer::isValid (const rcAnalyzerOptions & options) const private
Definition at line 356 of file rc_analyzer.cpp.
References rcAnalyzerOptions::windowSize().
Referenced by getNextResult(), rcAnalyzer(), and setOptions().
 {
   if ( options.windowSize() < 1 )
     return false;
   return true;
 }
const vector< float > & rcAnalyzer::longTermEntropies () const
Definition at line 44 of file rc_analyzer.cpp.
References mEnergyCalc.
 {
   return mEnergyCalc->longTermEntropy ();
 }
const vector< rc2Fvector > & rcAnalyzer::offsets () const
Definition at line 49 of file rc_analyzer.cpp.
References mOffsets.
 {
   return mOffsets;
 }
rcFrameGrabberStatus rcAnalyzer::popResult (rcAnalyzerResult & result) private
Definition at line 284 of file rc_analyzer.cpp.
References eFrameErrorInternal, eFrameErrorOK, eFrameStatusError, eFrameStatusOK, mFrames, mLastError, mResults, rmAssert, rcAnalyzerResult::setEntropy(), and rcAnalyzerResult::setFrameBuf().
Referenced by getNextResult().
 {
   rmAssert( !mFrames.empty() );
   rmAssert( !mResults.empty() );
   rcFrameGrabberStatus status = eFrameStatusError;
   if ( !mFrames.empty() && !mResults.empty() ) {
     // Get first available result
     result.setEntropy( mResults.front() );
     result.setFrameBuf( mFrames.front() );
     //    Remove front elements
     mFrames.pop_front();
     deque<rcSharedFrameBufPtr>(mFrames).swap(mFrames);
     mResults.pop_front();
     deque<double>(mResults).swap(mResults);
     mLastError = eFrameErrorOK;
     status = eFrameStatusOK;
   }
   else {
     mLastError = eFrameErrorInternal;
   }
   return status;
 }
void rcAnalyzer::pushResult (const vector< double > & results) private
Definition at line 313 of file rc_analyzer.cpp.
References cUndefinedEntropy, eAnalyzerResultOriginCenter, eAnalyzerResultOriginLeft, eAnalyzerResultOriginRight, mOptions, mResults, rcAnalyzerOptions::origin(), rmAssert, and rcAnalyzerOptions::windowSize().
Referenced by getNextResult().
 {
   if ( results.empty() ) {
     mResults.push_back( cUndefinedEntropy );
   } else {
     // Choose result based on origin
     switch ( mOptions.origin() ) {
     case eAnalyzerResultOriginLeft:
       mResults.push_back( results.front() );
       break;
     case eAnalyzerResultOriginCenter:
       mResults.push_back( results[ mOptions.windowSize()/2] );
       break;
     case eAnalyzerResultOriginRight:
       mResults.push_back( results.back() );
       break;
     default:
       rmAssert( 0 );
       break;
     }
   }
 }
void rcAnalyzer::pushUndefinedResult () private
Definition at line 337 of file rc_analyzer.cpp.
References cUndefinedEntropy, eAnalyzerResultOriginCenter, eAnalyzerResultOriginLeft, eAnalyzerResultOriginRight, mFrames, mOptions, mResults, rcAnalyzerOptions::origin(), rmAssert, and rcAnalyzerOptions::windowSize().
Referenced by getNextResult().
 {
   switch ( mOptions.origin() ) {
   case eAnalyzerResultOriginLeft:
     break;
   case eAnalyzerResultOriginCenter:
     if ( mFrames.size() <=  mOptions.windowSize()/2 )
       mResults.push_back( cUndefinedEntropy );
     break;
   case eAnalyzerResultOriginRight:
     mResults.push_back( cUndefinedEntropy );
     break;
   default:
     rmAssert( 0 );
     break;
   }
 }
rcFrameGrabberStatus rcAnalyzer::reset ()
Definition at line 202 of file rc_analyzer.cpp.
References eAnalyzerInitialized, eFrameErrorOK, eFrameStatusOK, mFrames, mImages, mLastError, mResults, mState, and rmAssert.
Referenced by setOptions().
 {
   mLastError = eFrameErrorOK;
   mState = eAnalyzerInitialized;
   mResults.clear();
   mFrames.clear();
   mImages.clear ();
   rmAssert( mResults.empty() );
   rmAssert( mFrames.empty() );
   return eFrameStatusOK;
 }
void rcAnalyzer::setOffsets (vector< rc2Fvector > & offs) inline
Definition at line 200 of file rc_analyzer.h.
References mOffsets.
 { mOffsets = offs; }
rcFrameGrabberStatus rcAnalyzer::setOptions (const rcAnalyzerOptions & options)
Definition at line 224 of file rc_analyzer.cpp.
References eFrameErrorInvalidOptions, eFrameStatusError, isValid(), mLastError, mOptions, and reset().
 {
   rcFrameGrabberStatus status = eFrameStatusError;
   mLastError = eFrameErrorInvalidOptions;
   if ( isValid( options ) ) {
     mOptions = options;
     // Take no chances, flush everything
     status = reset();
   }
   return status;
 }
bool rcAnalyzer::start () private
Definition at line 251 of file rc_analyzer.cpp.
References eAnalyzerError, eAnalyzerStarted, rcFrameGrabber::getLastError(), mInputSource, mLastError, mState, and rcFrameGrabber::start().
Referenced by getNextResult().
 {
   if ( mInputSource.start() ) {
     mLastError = mInputSource.getLastError();
     mState = eAnalyzerStarted;
     return true;
   }
   else {
     mLastError = mInputSource.getLastError();
     mState = eAnalyzerError;
     return false;
   }
 }
bool rcAnalyzer::stop () private
Definition at line 269 of file rc_analyzer.cpp.
References eAnalyzerError, eAnalyzerStopped, rcFrameGrabber::getLastError(), mInputSource, mLastError, mState, and rcFrameGrabber::stop().
Referenced by ~rcAnalyzer().
 {
   if ( mInputSource.stop() ) {
     mLastError = mInputSource.getLastError();
     mState = eAnalyzerStopped;
     return true;
   }
   else {
     mLastError = mInputSource.getLastError();
     mState = eAnalyzerError;
     return false;
   }
 }
Member Data Documentation
rcSimilaratorRef rcAnalyzer::mEnergyCalc private
Definition at line 221 of file rc_analyzer.h.
Referenced by getNextResult(), longTermEntropies(), and rcAnalyzer().
bool rcAnalyzer::mFilled private
Definition at line 222 of file rc_analyzer.h.
Referenced by getNextResult().
deque<rcSharedFrameBufPtr> rcAnalyzer::mFrames private
Definition at line 219 of file rc_analyzer.h.
Referenced by getNextResult(), popResult(), pushUndefinedResult(), and reset().
vector<rcWindow> rcAnalyzer::mImages private
Definition at line 223 of file rc_analyzer.h.
Referenced by getNextResult(), and reset().
rcFrameGrabber& rcAnalyzer::mInputSource private
Definition at line 216 of file rc_analyzer.h.
Referenced by getNextResult(), rcAnalyzer(), start(), and stop().
rcFrameGrabberError rcAnalyzer::mLastError private
Definition at line 217 of file rc_analyzer.h.
Referenced by getLastError(), getNextResult(), popResult(), rcAnalyzer(), reset(), setOptions(), start(), and stop().
vector<rc2Fvector> rcAnalyzer::mOffsets private
Definition at line 224 of file rc_analyzer.h.
Referenced by getNextResult(), offsets(), and setOffsets().
rcAnalyzerOptions rcAnalyzer::mOptions private
Definition at line 215 of file rc_analyzer.h.
Referenced by getNextResult(), getOptions(), pushResult(), pushUndefinedResult(), rcAnalyzer(), and setOptions().
deque<double> rcAnalyzer::mResults private
Definition at line 220 of file rc_analyzer.h.
Referenced by getNextResult(), popResult(), pushResult(), pushUndefinedResult(), and reset().
rcAnalyzerState rcAnalyzer::mState private
Definition at line 218 of file rc_analyzer.h.
Referenced by getNextResult(), rcAnalyzer(), reset(), start(), stop(), and ~rcAnalyzer().
The documentation for this class was generated from the following files:
include/analysis/rc_analyzer.h
src/analysis/code/rc_analyzer.cpp