Visible: error_position Class Reference
error_position Class Reference
#include <include/stlplus/error_handler.hpp>
Public Member Functions
error_position (void)
error_position (const std::string &filename, unsigned line, unsigned column)
~error_position (void)
const std::string & filename (void) const
unsigned line (void) const
unsigned column (void) const
error_position operator+ (unsigned) const
error_position & operator+= (unsigned)
bool empty (void) const
bool valid (void) const
std::vector< std::string > show (void) const
Private Attributes
std::string m_filename
unsigned m_line
unsigned m_column
Friends
std::string to_string (const error_position &where)
otext & operator<< (otext &output, const error_position &where)
Detailed Description
Definition at line 31 of file error_handler.hpp.
Constructor & Destructor Documentation
error_position::error_position (void)
Definition at line 36 of file error_handler.cpp.
                                    :
   m_filename(std::string()), m_line(0), m_column(0)
 {
 }
error_position::error_position (const std::string & filename, unsigned line, unsigned column)
Definition at line 41 of file error_handler.cpp.
                                                                                         :
   m_filename(filename), m_line(line), m_column(column)
 {
 }
error_position::~error_position (void)
Definition at line 46 of file error_handler.cpp.
 {
 }
Member Function Documentation
unsigned error_position::column (void) const
Definition at line 60 of file error_handler.cpp.
References m_column.
Referenced by show(), and to_string().
 {
   return m_column;
 }
bool error_position::empty (void) const
Definition at line 78 of file error_handler.cpp.
References m_filename.
Referenced by valid().
 {
   return m_filename.empty();
 }
const std::string & error_position::filename (void) const
Definition at line 50 of file error_handler.cpp.
References m_filename.
Referenced by show(), and to_string().
 {
   return m_filename;
 }
unsigned error_position::line (void) const
Definition at line 55 of file error_handler.cpp.
References m_line.
Referenced by show(), and to_string().
 {
   return m_line;
 }
error_position error_position::operator+ (unsigned offset) const
Definition at line 65 of file error_handler.cpp.
 {
   error_position result(*this);
   result += offset;
   return result;
 }
error_position & error_position::operator+= (unsigned offset)
Definition at line 72 of file error_handler.cpp.
References m_column.
 {
   m_column += offset;
   return *this;
 }
std::vector< std::string > error_position::show (void) const
Definition at line 88 of file error_handler.cpp.
References column(), itext::error(), filename(), itext::getline(), line(), and valid().
 {
   std::vector<std::string> result;
   if (valid())
   {
     // skip row-1 lines of the file and print out the resultant line
     iftext source(filename());
     std::string current_line;
     for (unsigned i = 0; i < line(); i++)
       if (source.error() || !source.getline(current_line))
         break;
     result.push_back(current_line);
     // now put an up-arrow at the appropriate column
     // preserve any tabs in the original line
     result.push_back(std::string());
     for (unsigned j = 0; j < column(); j++)
     {
       if (j < current_line.size() && current_line[j] == '\t')
         result.back() += '\t';
       else
         result.back() += ' ';
     }
     result.back() += '^';
   }
   return result;
 }
bool error_position::valid (void) const
Definition at line 83 of file error_handler.cpp.
References empty().
Referenced by show().
 {
   return !empty();
 }
Friends And Related Function Documentation
otext& operator<< (otext & output, const error_position & where) friend
Definition at line 120 of file error_handler.cpp.
 {
   return output << to_string(where);
 }
std::string to_string (const error_position & where) friend
Definition at line 115 of file error_handler.cpp.
 {
   return "{" + filespec_to_relative_path(where.filename()) + ":" + to_string(where.line()) + ":" + to_string(where.column()) + "}";
 }
Member Data Documentation
unsigned error_position::m_column private
Definition at line 63 of file error_handler.hpp.
Referenced by column(), and operator+=().
std::string error_position::m_filename private
Definition at line 61 of file error_handler.hpp.
Referenced by empty(), and filename().
unsigned error_position::m_line private
Definition at line 62 of file error_handler.hpp.
Referenced by line().
The documentation for this class was generated from the following files:
include/stlplus/error_handler.hpp
include/stlplus/error_handler.cpp