Visible: rcMotionPath Class Reference
rcMotionPath Class Reference
#include <include/analysis/rc_dbdt.h>
Public Types
enum state { eUnInitialized, eTracking, eNoFeature }
enum mode { eLean, eKeepFeatures }
Public Member Functions
rcMotionPath (mode m=eLean)
rcMotionPath (const rcFeature &sp, mode m=eLean)
void add (const rcFeature &feature)
void add ()
int32 & n ()
const int32 & n () const
int32 & numTracked ()
const int32 & numTracked () const
rc2Dvector & sumPos ()
const rc2Dvector & sumPos () const
rcDPair startPosition () const
enum mode mode ()
state state ()
rcFeature & lastFeature ()
const rcFeature & lastFeature () const
void state (enum state st)
double & sumAngle ()
double & sumAngledT ()
double & sumSqAngle ()
double & sumSqAngledT ()
double & sumQuality ()
double & sumSqQuality ()
bool operator< (const rcMotionPath &r) const
Private Member Functions
void init ()
Private Attributes
enum state mState
enum mode mMode
int32 mNtracked
int32 mNstarted
rcFeature mLastFeature
double mLastAngle
rc2Dvector mSumPos
rcDPair mStartPosition
double mSumAngle
double mSumSqAngle
double mSumAngledT
double mSumSqAngledT
double mSumQuality
double mSumSqQuality
deque< rcFeature > features
Friends
ostream & operator<< (ostream &, const rcMotionPath &)
Detailed Description
Definition at line 247 of file rc_dbdt.h.
Member Enumeration Documentation
enum rcMotionPath::mode
Enumerator
eLean
eKeepFeatures
Definition at line 258 of file rc_dbdt.h.
     {
       eLean,
       eKeepFeatures
     };
enum rcMotionPath::state
Enumerator
eUnInitialized
eTracking
eNoFeature
Definition at line 251 of file rc_dbdt.h.
     {
       eUnInitialized,
       eTracking,
       eNoFeature
     };
Constructor & Destructor Documentation
rcMotionPath::rcMotionPath (mode m = eLean) inline
Definition at line 264 of file rc_dbdt.h.
References init().
                                : mMode (m)
   {
     init ();
   }
rcMotionPath::rcMotionPath (const rcFeature & sp, mode m = eLean) inline
Definition at line 269 of file rc_dbdt.h.
References add(), and init().
     : mMode (m), mStartPosition (sp.origin ())
   {
     init ();
     add (sp);
   }
Member Function Documentation
void rcMotionPath::add (const rcFeature & feature) inline
Definition at line 280 of file rc_dbdt.h.
References rc2dVector< T >::angle(), rcRadian::Double(), eKeepFeatures, eTracking, features, mLastAngle, mLastFeature, mNstarted, mNtracked, mode(), mSumAngle, mSumAngledT, mSumPos, mSumSqAngle, mSumSqAngledT, mSumSqQuality, rcFeature::pos(), rcFeature::quality(), state(), rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     mNstarted++;
     mNtracked++;
     const rc2Dvector& pos = feature.pos();
   // If the motion vector indicates no motion, the current decision is to add them
   // but not add to the statistics (TBD)
     if (pos.x() < 0.0001 && pos.y() < 0.0001)
       return;
     double angle = pos.angle().Double();
     mSumPos += pos;
     mSumAngle += angle;
     mSumSqAngle += angle * angle;
     mSumAngle += feature.quality();
     mSumSqQuality += feature.quality() * feature.quality();
     if (mNtracked)
       {
     double bsd = angle - mLastAngle;
     mSumAngledT += bsd;
     mSumSqAngledT += bsd*bsd;
     mLastAngle = angle;
       }
     // Finally if mode is not zero, add this feature to the features list
     // Note: a copy will made
     if (mode() == eKeepFeatures) features.push_front (feature);
     state (eTracking);
     mLastFeature = feature;
   }
void rcMotionPath::add () inline
Definition at line 314 of file rc_dbdt.h.
References eNoFeature, mNstarted, mNtracked, and state().
Referenced by rcMotionPath().
   {
     mNstarted++;
     mNtracked = 0;
     state (eNoFeature);
   }
void rcMotionPath::init () inline private
Definition at line 373 of file rc_dbdt.h.
References eUnInitialized, mNstarted, mNtracked, mState, mSumAngle, mSumAngledT, mSumPos, mSumSqAngle, and mSumSqAngledT.
Referenced by rcMotionPath().
   {
     mNtracked = mNstarted = 0;
     mSumPos = rc2Dvector (0,0);
     mSumAngle = 0;
     mSumSqAngle = 0;
     mSumAngledT = 0;
     mSumSqAngledT = 0;
     mState = eUnInitialized;
   }
rcFeature& rcMotionPath::lastFeature () inline
Definition at line 334 of file rc_dbdt.h.
References mLastFeature.
 { return mLastFeature; };
const rcFeature& rcMotionPath::lastFeature () const inline
Definition at line 335 of file rc_dbdt.h.
References mLastFeature.
 { return mLastFeature; };
enum mode rcMotionPath::mode () inline
Definition at line 332 of file rc_dbdt.h.
References mMode.
Referenced by add().
 { return mMode; };
int32& rcMotionPath::n () inline
Definition at line 321 of file rc_dbdt.h.
References mNstarted.
 { return mNstarted; };
const int32& rcMotionPath::n () const inline
Definition at line 322 of file rc_dbdt.h.
References mNstarted.
 { return mNstarted; };
int32& rcMotionPath::numTracked () inline
Definition at line 323 of file rc_dbdt.h.
References mNtracked.
 { return mNtracked; };
const int32& rcMotionPath::numTracked () const inline
Definition at line 324 of file rc_dbdt.h.
References mNtracked.
 { return mNtracked; };
bool rcMotionPath::operator< (const rcMotionPath & r) const inline
Definition at line 350 of file rc_dbdt.h.
References startPosition().
   {
     return (startPosition () < r.startPosition());
   }
rcDPair rcMotionPath::startPosition () const inline
Definition at line 328 of file rc_dbdt.h.
References mStartPosition.
Referenced by operator<().
 { return mStartPosition; }
state rcMotionPath::state () inline
Definition at line 333 of file rc_dbdt.h.
References mState.
Referenced by add().
 {return mState;};
void rcMotionPath::state (enum state st) inline
Definition at line 337 of file rc_dbdt.h.
References mState.
 {mState = st;}
double& rcMotionPath::sumAngle () inline
Definition at line 341 of file rc_dbdt.h.
References mSumAngle.
 { return mSumAngle; };
double& rcMotionPath::sumAngledT () inline
Definition at line 342 of file rc_dbdt.h.
References mSumAngledT.
 { return mSumAngledT; };
rc2Dvector& rcMotionPath::sumPos () inline
Definition at line 325 of file rc_dbdt.h.
References mSumPos.
 { return mSumPos; };
const rc2Dvector& rcMotionPath::sumPos () const inline
Definition at line 326 of file rc_dbdt.h.
References mSumPos.
 { return mSumPos; };
double& rcMotionPath::sumQuality () inline
Definition at line 345 of file rc_dbdt.h.
References mSumQuality.
 { return mSumQuality; };
double& rcMotionPath::sumSqAngle () inline
Definition at line 343 of file rc_dbdt.h.
References mSumSqAngle.
 { return mSumSqAngle; };
double& rcMotionPath::sumSqAngledT () inline
Definition at line 344 of file rc_dbdt.h.
References mSumSqAngledT.
 { return mSumSqAngledT; };
double& rcMotionPath::sumSqQuality () inline
Definition at line 346 of file rc_dbdt.h.
References mSumSqQuality.
 { return mSumSqQuality; };
Friends And Related Function Documentation
ostream& operator<< (ostream & , const rcMotionPath &) friend
Member Data Documentation
deque<rcFeature> rcMotionPath::features private
Definition at line 384 of file rc_dbdt.h.
Referenced by add().
double rcMotionPath::mLastAngle private
Definition at line 363 of file rc_dbdt.h.
Referenced by add().
rcFeature rcMotionPath::mLastFeature private
Definition at line 362 of file rc_dbdt.h.
Referenced by add(), and lastFeature().
enum mode rcMotionPath::mMode private
Definition at line 359 of file rc_dbdt.h.
Referenced by mode().
int32 rcMotionPath::mNstarted private
Definition at line 361 of file rc_dbdt.h.
Referenced by add(), init(), and n().
int32 rcMotionPath::mNtracked private
Definition at line 360 of file rc_dbdt.h.
Referenced by add(), init(), and numTracked().
rcDPair rcMotionPath::mStartPosition private
Definition at line 365 of file rc_dbdt.h.
Referenced by startPosition().
enum state rcMotionPath::mState private
Definition at line 356 of file rc_dbdt.h.
Referenced by init(), and state().
double rcMotionPath::mSumAngle private
Definition at line 366 of file rc_dbdt.h.
Referenced by add(), init(), and sumAngle().
double rcMotionPath::mSumAngledT private
Definition at line 368 of file rc_dbdt.h.
Referenced by add(), init(), and sumAngledT().
rc2Dvector rcMotionPath::mSumPos private
Definition at line 364 of file rc_dbdt.h.
Referenced by add(), init(), and sumPos().
double rcMotionPath::mSumQuality private
Definition at line 370 of file rc_dbdt.h.
Referenced by sumQuality().
double rcMotionPath::mSumSqAngle private
Definition at line 367 of file rc_dbdt.h.
Referenced by add(), init(), and sumSqAngle().
double rcMotionPath::mSumSqAngledT private
Definition at line 369 of file rc_dbdt.h.
Referenced by add(), init(), and sumSqAngledT().
double rcMotionPath::mSumSqQuality private
Definition at line 371 of file rc_dbdt.h.
Referenced by add(), and sumSqQuality().
The documentation for this class was generated from the following file:
include/analysis/rc_dbdt.h