Visible: itext Class Reference
itext Class Reference
#include <include/stlplus/textio.hpp>
Public Types
enum newline_t { binary_mode, convert_mode }
typedef void(* manipulator_function)(itext &)
Public Member Functions
itext (void)
itext (ibuff *)
virtual ~itext (void)
bool initialised (void) const
void open (ibuff *)
void close (void)
itext (const itext &)
itext & operator= (const itext &)
bool error (void) const
int error_number (void) const
std::string error_string (void) const
void set_error (int error)
void clear_error (void)
void set_newline_mode (newline_t newline=convert_mode)
void set_convert_mode (void)
void set_binary_mode (void)
newline_t newline_mode (void) const
bool is_convert_mode (void)
bool is_binary_mode (void)
bool eof (void)
bool eoln (void)
int peek (void)
int get (void)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
bool good (void)
operator bool (void)
bool operator! (void)
itext & operator>> (char &)
itext & operator>> (signed char &)
itext & operator>> (unsigned char &)
itext & operator>> (std::string &)
bool getline (std::string &line)
itext & operator>> (std::vector< std::string > &)
itext & operator>> (bool &)
itext & operator>> (short &)
itext & operator>> (unsigned short &)
itext & operator>> (int &)
itext & operator>> (unsigned int &)
itext & operator>> (long &)
itext & operator>> (unsigned long &)
itext & operator>> (float &)
itext & operator>> (double &)
itext & operator>> (void *&)
itext & operator>> (manipulator_function)
itext & operator>> (otext &)
Protected Attributes
ibuff * m_buffer
Friends
class otext
class ibuff
std::string to_string (newline_t)
Detailed Description
Definition at line 241 of file textio.hpp.
Member Typedef Documentation
typedef void(* itext::manipulator_function)(itext &)
Definition at line 260 of file textio.hpp.
Member Enumeration Documentation
enum itext::newline_t
Enumerator
binary_mode
convert_mode
Definition at line 253 of file textio.hpp.
   {
     binary_mode,      // no end of line conversion
     convert_mode      // recognise and convert all end-of-line conventions
   };
Constructor & Destructor Documentation
itext::itext (void)
Definition at line 629 of file textio.cpp.
                   : m_buffer(0)
 {
 }
itext::itext (ibuff * b)
Definition at line 633 of file textio.cpp.
References open().
                       : m_buffer(0)
 {
   open(b);
 }
itext::~itext (void) virtual
Definition at line 638 of file textio.cpp.
References close().
 {
   close();
 }
itext::itext (const itext & source)
Definition at line 665 of file textio.cpp.
References m_buffer, and open().
                                  : m_buffer(0)
 {
   if (m_buffer != source.m_buffer)
     open(source.m_buffer);
 }
Member Function Documentation
unsigned long itext::bytes (void) const
Definition at line 796 of file textio.cpp.
References ibuff::bytes(), and m_buffer.
Referenced by subprocess::read_stderr(), async_subprocess::read_stderr(), subprocess::read_stdout(), async_subprocess::read_stdout(), subprocess::write_stdin(), and async_subprocess::write_stdin().
 {
   return m_buffer ? m_buffer->bytes() : 0;
 }
void itext::clear_error (void)
Definition at line 699 of file textio.cpp.
References ibuff::clear_error(), and m_buffer.
 {
   if (m_buffer) m_buffer->clear_error();
 }
void itext::close (void)
Definition at line 655 of file textio.cpp.
References ibuff::m_aliases, and m_buffer.
Referenced by close(), open(), and ~itext().
 {
   if (m_buffer)
   {
     if (--m_buffer->m_aliases == 0)
       delete m_buffer;
     m_buffer = 0;
   }
 }
unsigned itext::column (void) const
Definition at line 806 of file textio.cpp.
References ibuff::column(), and m_buffer.
 {
   return m_buffer ? m_buffer->column() : 0;
 }
bool itext::eof (void)
Definition at line 734 of file textio.cpp.
References peek().
Referenced by good().
 {
   return peek() == -1;
 }
bool itext::eoln (void)
Definition at line 739 of file textio.cpp.
References newline, and peek().
 {
   return peek() == newline;
 }
bool itext::error (void) const
Definition at line 678 of file textio.cpp.
References error_number().
Referenced by error_string(), restore_context_body::get(), good(), library_manager::load_mappings(), lm_unit::read(), and error_position::show().
 {
   return error_number() != 0;
 }
int itext::error_number (void) const
Definition at line 683 of file textio.cpp.
References ibuff::error_number(), m_buffer, and textio_uninitialised.
Referenced by error(), and lm_unit::read().
 {
   return m_buffer ? m_buffer->error_number() : textio_uninitialised;
 }
std::string itext::error_string (void) const
Definition at line 688 of file textio.cpp.
References error(), ibuff::error_string(), m_buffer, textio_error_string(), and textio_uninitialised.
Referenced by restore_context_body::get(), and lm_unit::read().
 {
   if (!error()) return std::string();
   return m_buffer ? m_buffer->error_string() : textio_error_string(textio_uninitialised);
 }
int itext::get (void)
Definition at line 763 of file textio.cpp.
References convert_mode, ibuff::get(), ibuff::increment(), m_buffer, newline, ibuff::newline_mode(), and ibuff::peek().
Referenced by restore_context_body::get(), get_token(), otext::operator<<(), skipendl(), skipline(), skiponewhite(), skipspaces(), and skipwhite().
 {
   if (!m_buffer) return -1;
   // get a raw character from the input buffer
   int ch = m_buffer->get();
   // Note: it used to be an error to get an eof
   //       However, this seems unnecessary - input buffers should be designed to just return -1 repeatedly
   //       It is then legal to get an eof any number of times
   if (ch == -1) return -1;
   // optionally do line-end conversion if this cg=haracter is a line-end character
   if (m_buffer->newline_mode() == itext::convert_mode)
   {
     switch(ch)
     {
     case '\xd': // carriage-return - optionally followed by linefeed
       ch = newline;
       if (m_buffer->peek() == '\xa')
       {
         m_buffer->get();
         m_buffer->increment();
       }
       break;
     case '\xa': // linefeed
       ch = newline;
       break;
     default:
       break;
     }
   }
   m_buffer->increment(ch == newline);
   return ch;
 }
bool itext::getline (std::string & line)
Definition at line 867 of file textio.cpp.
References newline, and peek().
Referenced by error_handler_base_body::add_message_file(), library_manager::load_mappings(), operator>>(), ini_file::read_file(), and error_position::show().
 {
   line.erase();
   bool result = false;
   for (;;)
   {
     int ch = peek();
     if (ch == -1) break;
     result = true;
     ch = get();
     if (ch == newline) break;
     line += (char)ch;
   }
   return result;
 }
bool itext::good (void)
Definition at line 811 of file textio.cpp.
References eof(), and error().
Referenced by operator!(), and operator>>().
 {
   return !error() && !eof();
 }
bool itext::initialised (void) const
Definition at line 643 of file textio.cpp.
References m_buffer.
 {
   return m_buffer != 0;
 }
bool itext::is_binary_mode (void)
Definition at line 729 of file textio.cpp.
References binary_mode, and newline_mode().
 {
   return newline_mode() == itext::binary_mode;
 }
bool itext::is_convert_mode (void)
Definition at line 724 of file textio.cpp.
References convert_mode, and newline_mode().
 {
   return newline_mode() == itext::convert_mode;
 }
unsigned itext::line (void) const
Definition at line 801 of file textio.cpp.
References ibuff::line(), and m_buffer.
Referenced by library_manager::load_mappings(), and operator>>().
 {
   return m_buffer ? m_buffer->line() : 0;
 }
itext::newline_t itext::newline_mode (void) const
Definition at line 719 of file textio.cpp.
References convert_mode, m_buffer, and ibuff::newline_mode().
Referenced by is_binary_mode(), and is_convert_mode().
 {
   return m_buffer ? m_buffer->newline_mode() : itext::convert_mode;
 }
void itext::open (ibuff * b)
Definition at line 648 of file textio.cpp.
References close(), ibuff::m_aliases, and m_buffer.
Referenced by itext(), iiotext::open(), imtext::open(), iftext::open(), and operator=().
 {
   close();
   m_buffer = b;
   if (m_buffer) m_buffer->m_aliases++;
 }
itext::operator bool (void)
Definition at line 816 of file textio.cpp.
 {
   return good();
 }
bool itext::operator! (void)
Definition at line 821 of file textio.cpp.
References good().
 {
   return !good();
 }
itext & itext::operator= (const itext & source)
Definition at line 671 of file textio.cpp.
References m_buffer, and open().
 {
   if (m_buffer != source.m_buffer)
     open(source.m_buffer);
   return *this;
 }
itext & itext::operator>> (char & c)
Definition at line 826 of file textio.cpp.
 {
   // TODO - test for out of range or eof value
   c = (char)get();
   return *this;
 }
itext & itext::operator>> (signed char & c)
Definition at line 833 of file textio.cpp.
 {
   // TODO - test for out of range or eof value
   c = (signed char)get();
   return *this;
 }
itext & itext::operator>> (unsigned char & c)
Definition at line 840 of file textio.cpp.
 {
   // TODO - test for out of range or eof value
   c = (unsigned char)get();
   return *this;
 }
itext & itext::operator>> (std::string & s)
Definition at line 861 of file textio.cpp.
References get_token().
 {
   s = get_token(*this);
   return *this;
 }
itext & itext::operator>> (std::vector< std::string > & d)
Definition at line 883 of file textio.cpp.
References getline(), and line().
 {
   d.clear();
   std::string line;
   while(getline(line))
     d.push_back(line);
   return *this;
 }
itext & itext::operator>> (bool & b)
Definition at line 892 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_bool().
 {
   try
   {
     b = to_bool(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (short & s)
Definition at line 905 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_short().
 {
   try
   {
     s = to_short(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (unsigned short & us)
Definition at line 918 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_ushort().
 {
   try
   {
     us = to_ushort(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (int & i)
Definition at line 931 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_int().
 {
   try
   {
     i = to_int(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (unsigned int & u)
Definition at line 944 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_uint().
 {
   try
   {
     u = to_uint(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (long & l)
Definition at line 957 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_long().
 {
   try
   {
     l = to_long(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (unsigned long & ul)
Definition at line 970 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_ulong().
 {
   try
   {
     ul = to_ulong(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (float & f)
Definition at line 983 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_float().
 {
   try
   {
     f = to_float(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (double & d)
Definition at line 996 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_double().
 {
   try
   {
     d = to_double(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (void *& p)
Definition at line 1009 of file textio.cpp.
References get_token(), set_error(), textio_format_error, and to_void_star().
 {
   try
   {
     p = to_void_star(get_token(*this));
   }
   catch(const std::invalid_argument)
   {
     set_error(textio_format_error);
   }
   return *this;
 }
itext & itext::operator>> (itext::manipulator_function fn)
Definition at line 1022 of file textio.cpp.
 {
   if (fn) fn(*this);
   return *this;
 }
itext & itext::operator>> (otext & out)
Definition at line 1028 of file textio.cpp.
References good(), and otext::put().
 {
   while (good())
     out.put(get());
   return *this;
 }
int itext::peek (void)
Definition at line 744 of file textio.cpp.
References convert_mode, m_buffer, newline, ibuff::newline_mode(), and ibuff::peek().
Referenced by eof(), eoln(), get_token(), getline(), skipendl(), skipline(), skiponewhite(), skipspaces(), and skipwhite().
 {
   if (!m_buffer) return -1;
   int ch = m_buffer->peek();
   if (m_buffer->newline_mode() == itext::convert_mode)
   {
     switch(ch)
     {
     case '\xd': // carriage-return
     case '\xa': // line-feed
       ch = newline;
       break;
     default:
       break;
     }
   }
   return ch;
 }
void itext::set_binary_mode (void)
Definition at line 714 of file textio.cpp.
References binary_mode, and set_newline_mode().
Referenced by restore_context_body::restore_context_body().
 {
   set_newline_mode(itext::binary_mode);
 }
void itext::set_convert_mode (void)
Definition at line 709 of file textio.cpp.
References convert_mode, and set_newline_mode().
 {
   set_newline_mode(itext::convert_mode);
 }
void itext::set_error (int error)
Definition at line 694 of file textio.cpp.
References m_buffer, and ibuff::set_error().
Referenced by operator>>(), and operator>>().
 {
   if (m_buffer) m_buffer->set_error(error);
 }
void itext::set_newline_mode (itext::newline_t nl = convert_mode)
Definition at line 704 of file textio.cpp.
References m_buffer, and ibuff::set_newline_mode().
Referenced by set_binary_mode(), and set_convert_mode().
 {
   if (m_buffer) m_buffer->set_newline_mode(nl);
 }
Friends And Related Function Documentation
friend class ibuff friend
Definition at line 245 of file textio.hpp.
friend class otext friend
Definition at line 244 of file textio.hpp.
std::string to_string (newline_t) friend
Definition at line 617 of file textio.cpp.
 {
   switch(mode)
   {
   case itext::binary_mode: return std::string("binary");
   case itext::convert_mode: return std::string("convert");
   }
   return std::string("*unknown mode*");
 }
Member Data Documentation
ibuff* itext::m_buffer protected
Definition at line 246 of file textio.hpp.
Referenced by imtext::add(), bytes(), clear_error(), close(), column(), imtext::device_count(), imtext::device_get(), error_number(), error_string(), get(), iiotext::get_stream(), istext::get_string(), isvtext::get_vector(), initialised(), itext(), line(), newline_mode(), open(), operator=(), peek(), imtext::remove(), set_error(), and set_newline_mode().
The documentation for this class was generated from the following files:
include/stlplus/textio.hpp
include/stlplus/textio.cpp