Visible: rcSimilarator::progressNotification Class Reference
rcSimilarator::progressNotification Class Reference
Public Member Functions
progressNotification (int32 totCorr, rcProgressIndicator *guiUpdate)
bool update ()
Private Attributes
int32 _totCorr
int32 _curCorr
int32 _nextPct
int32 _pctUpdate
rcProgressIndicator * _guiUpdate
bool _abort
Detailed Description
Definition at line 411 of file rc_similarity.h.
Constructor & Destructor Documentation
rcSimilarator::progressNotification::progressNotification (int32 totCorr, rcProgressIndicator * guiUpdate) inline
Definition at line 414 of file rc_similarity.h.
References _abort, _guiUpdate, _nextPct, _pctUpdate, and rcProgressIndicator::progress().
Member Function Documentation
bool rcSimilarator::progressNotification::update () inline
Definition at line 432 of file rc_similarity.h.
References _abort, _curCorr, _guiUpdate, _nextPct, _pctUpdate, _totCorr, and rcProgressIndicator::progress().
Referenced by rcSimilarator::ssListFill(), rcSimilarator::ssMatrixFill(), and rcSimilarator::ssMatrixUpdate().
Member Data Documentation
bool rcSimilarator::progressNotification::_abort private
Definition at line 452 of file rc_similarity.h.
Referenced by progressNotification(), and update().
int32 rcSimilarator::progressNotification::_curCorr private
Definition at line 450 of file rc_similarity.h.
Referenced by update().
rcProgressIndicator* rcSimilarator::progressNotification::_guiUpdate private
Definition at line 451 of file rc_similarity.h.
Referenced by progressNotification(), and update().
int32 rcSimilarator::progressNotification::_nextPct private
Definition at line 450 of file rc_similarity.h.
Referenced by progressNotification(), and update().
int32 rcSimilarator::progressNotification::_pctUpdate private
Definition at line 450 of file rc_similarity.h.
Referenced by progressNotification(), and update().
int32 rcSimilarator::progressNotification::_totCorr private
Definition at line 450 of file rc_similarity.h.
Referenced by update().
The documentation for this class was generated from the following file:
include/analysis/rc_similarity.h