Visible: rcOptoKineticImage Class Reference
rcOptoKineticImage Class Reference
#include <include/analysis/rc_kineticimage.h>
Public Types
enum kineType {
eKineTypeDummy = 0, eKineTypeVariance, eKineTypeStdDev, eKineTypeVelEntropy,
eKineTypeAccelEntropy, eKineTypeThetaEntropy, eKineTypeLogRMS, eKineTypeInvalid
}
Public Member Functions
rcOptoKineticImage (kineType type)
void push (rcWindow img)
void push (vector< rcWindow > &sequence)
void push (deque< rcWindow > &sequence)
uint32 pop (uint32 cnt=1)
void update (rcWindow img)
void update (vector< rcWindow > &sequence)
void update (deque< rcWindow > &sequence)
void genKineticImg (rcWindow kineticImg)
void genKineticStats (const rcWindow &kineticImg, float &minVal, float &maxVal, float &mean, float &stdDev)
void genDFT (rcWindow freqImg, rcWindow phaseImg, rcWindow amplitudeImg)
void genEightBitDFT (rcWindow freqImg, rcWindow freqEBImg, rcWindow phaseImg, rcWindow phaseEBImg, rcWindow amplitudeImg, rcWindow amplitudeEBImg, uint32 expectedFreq)
void genFreqImg (rcWindow freqImg, float fpp, const rcWindow *maskImg=0)
void gen1DCorrKineticImgs (uint32 period, uint32 pulseWidth, rcWindow ampImg, rcWindow phaseImg, rcWindow corrPeaks, rcWindow phasePeaks)
void genEightBitFreq (rcWindow freqImg, rcWindow freqEBImg, const float expectedFreq)
void genEightBitImg (const rcWindow &kineticImg, rcWindow ebImg, float sdClamp, const vector< uint8 > *map)
void genEightBitImg (const rcWindow &kineticImg, rcWindow ebImg, vector< float > &map)
void genEightBitImg (const rcWindow &kineticImg, rcWindow &ebImg)
uint32 underflow () const
uint32 overflow () const
Private Types
typedef void(rcOptoKineticImage::* IMGHDLR)(const rcWindow &img)
typedef void(rcOptoKineticImage::* GENHDLR)(rcWindow kineticImg)
Private Member Functions
void genVarImg (rcWindow stdDevImg)
void genStdDevImg (rcWindow stdDevImg)
void genVelEntropyImg (rcWindow entropyImg)
void genAccelEntropyImg (rcWindow entropyImg)
void genThetaEntropyImg (rcWindow entropyImg)
void genLogRMS (rcWindow)
void genDummyImg (rcWindow)
void decrementU8 (const rcWindow &img)
void incrementU8 (const rcWindow &img)
void decVarImg (const rcWindow &img)
void incVarImg (const rcWindow &img)
void decStdDevImg (const rcWindow &img)
void incStdDevImg (const rcWindow &img)
void decVelEntropyImg (const rcWindow &img)
void incVelEntropyImg (const rcWindow &img)
void decLogRMSImg (const rcWindow &img)
void incLogRMSImg (const rcWindow &img)
void decAccelEntropyImg (const rcWindow &)
void incAccelEntropyImg (const rcWindow &)
void decThetaEntropyImg (const rcWindow &)
void incThetaEntropyImg (const rcWindow &)
void decDummyImg (const rcWindow &)
void incDummyImg (const rcWindow &)
void initTheta ()
Private Attributes
kineType _kType
IMGHDLR _incHdlr
IMGHDLR _decHdlr
GENHDLR _genHdlr
deque< rcWindow > _movie
rcWindow _sum
rcWindow _sumSq
uint32 _uCnt
uint32 _oCnt
vector< float > _theta
Detailed Description
Definition at line 44 of file rc_kineticimage.h.
Member Typedef Documentation
typedef void(rcOptoKineticImage::* rcOptoKineticImage::GENHDLR)(rcWindow kineticImg) private
Definition at line 138 of file rc_kineticimage.h.
typedef void(rcOptoKineticImage::* rcOptoKineticImage::IMGHDLR)(const rcWindow &img) private
Definition at line 137 of file rc_kineticimage.h.
Member Enumeration Documentation
enum rcOptoKineticImage::kineType
Enumerator
eKineTypeDummy
eKineTypeVariance
eKineTypeStdDev
eKineTypeVelEntropy
eKineTypeAccelEntropy
eKineTypeThetaEntropy
eKineTypeLogRMS
eKineTypeInvalid
Definition at line 48 of file rc_kineticimage.h.
                 {
     eKineTypeDummy = 0,
     eKineTypeVariance,
     eKineTypeStdDev,
     eKineTypeVelEntropy,
     eKineTypeAccelEntropy,
     eKineTypeThetaEntropy,
     eKineTypeLogRMS,
     eKineTypeInvalid
   };
Constructor & Destructor Documentation
rcOptoKineticImage::rcOptoKineticImage (kineType type)
Definition at line 852 of file rc_kineticimage.cpp.
References _decHdlr, _genHdlr, _incHdlr, _kType, decAccelEntropyImg(), decDummyImg(), decLogRMSImg(), decStdDevImg(), decThetaEntropyImg(), decVarImg(), decVelEntropyImg(), eKineTypeAccelEntropy, eKineTypeDummy, eKineTypeLogRMS, eKineTypeStdDev, eKineTypeThetaEntropy, eKineTypeVariance, eKineTypeVelEntropy, genAccelEntropyImg(), genDummyImg(), genLogRMS(), genStdDevImg(), genThetaEntropyImg(), genVarImg(), genVelEntropyImg(), incAccelEntropyImg(), incDummyImg(), incLogRMSImg(), incStdDevImg(), incThetaEntropyImg(), incVarImg(), incVelEntropyImg(), and rmAssert.
                                                     : _kType(type)
 {
   switch (_kType)
   {
   case eKineTypeDummy:
     _incHdlr = &rcOptoKineticImage::incDummyImg;
     _decHdlr = &rcOptoKineticImage::decDummyImg;
     _genHdlr = &rcOptoKineticImage::genDummyImg;
     break;
   case eKineTypeVariance:
     _incHdlr = &rcOptoKineticImage::incVarImg;
     _decHdlr = &rcOptoKineticImage::decVarImg;
     _genHdlr = &rcOptoKineticImage::genVarImg;
     break;
   case eKineTypeStdDev:
     _incHdlr = &rcOptoKineticImage::incStdDevImg;
     _decHdlr = &rcOptoKineticImage::decStdDevImg;
     _genHdlr = &rcOptoKineticImage::genStdDevImg;
     break;
   case eKineTypeVelEntropy:
     _incHdlr = &rcOptoKineticImage::incVelEntropyImg;
     _decHdlr = &rcOptoKineticImage::decVelEntropyImg;
     _genHdlr = &rcOptoKineticImage::genVelEntropyImg;
     break;
   case eKineTypeAccelEntropy:
     _incHdlr = &rcOptoKineticImage::incAccelEntropyImg;
     _decHdlr = &rcOptoKineticImage::decAccelEntropyImg;
     _genHdlr = &rcOptoKineticImage::genAccelEntropyImg;
     break;
   case eKineTypeThetaEntropy:
     _incHdlr = &rcOptoKineticImage::incThetaEntropyImg;
     _decHdlr = &rcOptoKineticImage::decThetaEntropyImg;
     _genHdlr = &rcOptoKineticImage::genThetaEntropyImg;
     break;
   case eKineTypeLogRMS:
     _incHdlr = &rcOptoKineticImage::incLogRMSImg;
     _decHdlr = &rcOptoKineticImage::decLogRMSImg;
     _genHdlr = &rcOptoKineticImage::genLogRMS;
     break;
   default:
     rmAssert(0);
     break;
   }
 }
Member Function Documentation
void rcOptoKineticImage::decAccelEntropyImg (const rcWindow &) inline private
Definition at line 169 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::decDummyImg (const rcWindow &) inline private
Definition at line 178 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::decLogRMSImg (const rcWindow & img) inline private
Definition at line 164 of file rc_kineticimage.h.
References decrementU8().
Referenced by rcOptoKineticImage().
   { decrementU8(img); }
void rcOptoKineticImage::decrementU8 (const rcWindow & img) private
Definition at line 1979 of file rc_kineticimage.cpp.
References _sum, _sumSq, rcWindow::depth(), rcWindow::height(), rcPixel16, rcPixel32, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by decLogRMSImg(), decStdDevImg(), decVarImg(), and decVelEntropyImg().
 {
   const int32 width = img.width(), height = img.height();
   rmAssert(width == _sum.width());
   rmAssert(height == _sum.height());
   if (_sum.depth() == rcPixel16) {
     for (int32 y = 0; y < height; y++) {
       const uint8* pelRow = (const uint8*)img.rowPointer(y);
       uint16* sumRow = (uint16*)_sum.rowPointer(y);
       uint32* sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const uint16 pel = *pelRow++;
     *sumRow++ -= pel;
     *sumSqRow++ -= pel*pel;
       }
     }
   }
   else if (_sum.depth() == rcPixel32) {
     for (int32 y = 0; y < height; y++) {
       const uint8* pelRow = (const uint8*)img.rowPointer(y);
       uint32* sumRow = (uint32*)_sum.rowPointer(y);
       uint32* sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const uint16 pel = *pelRow++;
     *sumRow++ -= pel;
     *sumSqRow++ -= pel*pel;
       }
     }
   }
   else
     rmAssert(0);
 }
void rcOptoKineticImage::decStdDevImg (const rcWindow & img) inline private
Definition at line 156 of file rc_kineticimage.h.
References decrementU8().
Referenced by rcOptoKineticImage().
   { decrementU8(img); }
void rcOptoKineticImage::decThetaEntropyImg (const rcWindow &) inline private
Definition at line 173 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::decVarImg (const rcWindow & img) inline private
Definition at line 152 of file rc_kineticimage.h.
References decrementU8().
Referenced by rcOptoKineticImage().
   { decrementU8(img); }
void rcOptoKineticImage::decVelEntropyImg (const rcWindow & img) inline private
Definition at line 160 of file rc_kineticimage.h.
References decrementU8().
Referenced by rcOptoKineticImage().
   { decrementU8(img);}
void rcOptoKineticImage::gen1DCorrKineticImgs (uint32 period, uint32 pulseWidth, rcWindow ampImg, rcWindow phaseImg, rcWindow corrPeaks, rcWindow phasePeaks)
Definition at line 1273 of file rc_kineticimage.cpp.
References _movie, rcWindow::depth(), genSynthSignal(), rcWindow::height(), parabolicFit(), NR::period(), rcPixel32, rcPixel8, rf1DNormalizedCorr(), rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
   rmAssert(pulseWidth > 0);
   rmAssert(pulseWidth <= period);
   const uint32 movieLth = _movie.size();
   const uint32 mdlLth = period;
   rmAssert(mdlLth > 1);
   rmAssert(movieLth >= mdlLth);
   rmAssert(rcPixel8 == _movie[0].depth());
   const int32 width = _movie[0].width(), height = _movie[0].height();
   rmAssert(ampImg.width() == width);
   rmAssert(ampImg.height() == height);
   rmAssert(ampImg.depth() == rcPixel8);
   rmAssert(phaseImg.width() == width);
   rmAssert(phaseImg.height() == height);
   rmAssert(phaseImg.depth() == rcPixel8);
   rmAssert(corrPeaks.width() == width);
   rmAssert(corrPeaks.height() == height);
   rmAssert(corrPeaks.depth() == rcPixel32);
   rmAssert(phasePeaks.width() == width);
   rmAssert(phasePeaks.height() == height);
   rmAssert(phasePeaks.depth() == rcPixel32);
   if (0) printf("xyzzy period %d pulse width %d movie lth %d\n",
         period, pulseWidth, movieLth);
   vector<uint8> mdl;
   genSynthSignal(period, pulseWidth, 255, 0, 1, mdl);
   const uint32 resultSpcSz = movieLth - mdlLth + 1;
   vector<double> tempCorrSpc(resultSpcSz), cumCorrSpcLow(resultSpcSz),
     cumCorrSpcHigh(resultSpcSz);
   for (uint32 i = 0; i < resultSpcSz; i++)
     cumCorrSpcLow[i] = cumCorrSpcHigh[i] = 0;
   vector<uint8> img(movieLth);
   double globalMinCorrScore = 2.0, globalMaxCorrScore = -1.0;
   for (int32 y = 0; y < height; y++) {
     float* corrP = (float*)corrPeaks.rowPointer(y);
     float* phaseP = (float*)phasePeaks.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       for (uint32 i = 0; i < movieLth; i++)
     img[i] = _movie[i].getPixel(x, y);
       double maxVal = -1.0;
       uint32 maxValLoc = 0;
       vector<uint8>::iterator iStart = img.begin(), iEnd = iStart + mdlLth;
       for (uint32 i = 0; i < resultSpcSz; i++) {
     tempCorrSpc[i] = rf1DNormalizedCorr(iStart + i, iEnd + i,
                         mdl.begin(), mdl.end());
     if (tempCorrSpc[i] > maxVal) {
       maxValLoc = i;
       maxVal = tempCorrSpc[i];
     }
     if (tempCorrSpc[i] > 1e-6)
       cumCorrSpcHigh[i] += tempCorrSpc[i]*tempCorrSpc[i];
     else
       cumCorrSpcLow[i] += tempCorrSpc[i]*tempCorrSpc[i];
       }
       if (0) {
     printf("xyzzy space (%d,%d):", x, y);
     for (uint32 i = 0; i < tempCorrSpc.size(); i++)
       printf(" %f", tempCorrSpc[i]);
     printf("\n");
       }
       double delta, maxScore;
       if (maxValLoc == (resultSpcSz-1))  { // Peak is pegged at end
     delta = parabolicFit(tempCorrSpc[maxValLoc-1], tempCorrSpc[maxValLoc],
                  (double)0.0, &maxScore);
     rmAssert(delta <= 0.0);
       }
       else if (maxValLoc == 0) { // Peak is pegged at start
     delta = parabolicFit((double)0.0, tempCorrSpc[0], tempCorrSpc[1],
                  &maxScore);
     rmAssert(delta >= 0.0);
       }
       else { // Interpolate peak location
     delta = parabolicFit(tempCorrSpc[maxValLoc-1],tempCorrSpc[maxValLoc],
                  tempCorrSpc[maxValLoc+1], &maxScore);
       }
       if (maxScore < globalMinCorrScore)
     globalMinCorrScore = maxScore;
       if (maxScore > globalMaxCorrScore)
     globalMaxCorrScore = maxScore;
       *phaseP++ = (float)(maxValLoc + delta);
       *corrP++ = (float)maxScore;
     }
   } // End of: for (int32 y = 0; y < height; y++) {
   double maxVal = -1.0;
   uint32 maxValLoc = 0;
   for (uint32 i = 0; i < resultSpcSz; i++) {
     cumCorrSpcHigh[i] += cumCorrSpcLow[i];
     if (maxVal < cumCorrSpcHigh[i]) {
       maxVal = cumCorrSpcHigh[i];
       maxValLoc = i;
     }
   }
   if (0) printf("xyzzy maxVal %f maxValLoc %d\n", maxVal, maxValLoc);
   double delta;
   if (maxValLoc == (resultSpcSz-1))  { // Peak is pegged at end
     delta = parabolicFit(cumCorrSpcHigh[maxValLoc-1], cumCorrSpcHigh[maxValLoc],
              (double)0.0, (double*)0);
     rmAssert(delta <= 0.0);
   }
   else if (maxValLoc == 0) { // Peak is pegged at start
     delta = parabolicFit((double)0.0, cumCorrSpcHigh[0], cumCorrSpcHigh[1],
              (double*)0);
     rmAssert(delta >= 0.0);
   }
   else { // Interpolate peak location
     delta = parabolicFit(cumCorrSpcHigh[maxValLoc-1],cumCorrSpcHigh[maxValLoc],
              cumCorrSpcHigh[maxValLoc+1], (double*)0);
   }
   float phaseSpcSz = mdlLth;
   float phasePeak = (float)fmod((maxValLoc + delta), (double)mdlLth);
   float phaseMod = phaseSpcSz/2.0;
   float phaseScale = 255.0/phaseMod;
   float corrMin = (float)globalMinCorrScore;
   float corrScale = 255.0/(float)(globalMaxCorrScore - globalMinCorrScore);
   if (0) printf("xyzzy corr min %f max %f scale %f\n", corrMin,
         globalMaxCorrScore, corrScale);
   for (int32 y = 0; y < height; y++) {
       float* corrP = (float*)corrPeaks.rowPointer(y);
       float* phaseP = (float*)phasePeaks.rowPointer(y);
       uint8* ampImgP = (uint8*)ampImg.rowPointer(y);
       uint8* phaseImgP = (uint8*)phaseImg.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       float phaseDelta
     = fabs(phaseMod - fabs(fmod(*phaseP++, phaseSpcSz) - phasePeak));
       uint32 pVal = (uint32)(phaseDelta*phaseScale);
       rmAssert(pVal <= 255);
       *phaseImgP++ = (uint8)pVal;
       pVal = (uint32)((*corrP++ - corrMin)*corrScale);
       rmAssert(pVal <= 255);
       *ampImgP++ = (uint8)pVal;
     }
   }
   if (1)
     printf("xyzzy phase space sz %f peak %f mod %f scale %f\n",
        phaseSpcSz, phasePeak, phaseMod, phaseScale);
   if (0) {
     for (int32 y = 0; y < phasePeaks.height(); y++) {
       float* pP = (float*)phasePeaks.rowPointer(y);
       printf("%02d:", y);
       for (int32 x = 0; x < phasePeaks.width(); x++)
     printf(" %f", *pP++);
       printf("\n");
     }
     printf("\n");
     for (int32 y = 0; y < phaseImg.height(); y++) {
       uint8* pP = (uint8*)phaseImg.rowPointer(y);
       printf("%02d:", y);
       for (int32 x = 0; x < phaseImg.width(); x++)
     printf(" %03d", *pP++);
       printf("\n");
     }
   }
 }
void rcOptoKineticImage::genAccelEntropyImg (rcWindow entropyImg) private
Definition at line 1894 of file rc_kineticimage.cpp.
References _movie, rcWindow::depth(), rcWindow::height(), N, rcPixel32, rmAssert, rcWindow::rowPointer(), SHANNON, and rcWindow::width().
Referenced by rcOptoKineticImage().
 {
   const uint32 n = _movie.size() - 1;
   rmAssert(_movie.size() > 1);
   const int32 width = entropyImg.width(), height = entropyImg.height();
   rmAssert(width == _movie[0].width());
   rmAssert(height == _movie[0].height());
   rmAssert(entropyImg.depth() == rcPixel32);
   vector<float> vel(n);
   const float N = n;
   const float log2Sz = log2(N);
   for (int32 y = 0; y < height; y++) {
     float* entRow = (float*)entropyImg.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       /* Step 1 - Calculate the change in adjacent pixels (velocity).
        * At the same time, calculate the sum of these velocities.
        */
       float velSum = 0.0;
       int32 p0 = (int32)_movie[0].getPixel(x, y);
       for (uint32 i = 0; i < n; i++) {
     int32 p1 = (int32)_movie[i+1].getPixel(x, y);
     vel[i] = p0 - p1 + 256;
     velSum += vel[i];
     p0 = p1;
       }
       /* Step 2 - Generate shannon's entropy for this pixel
        * location.
        */
       float entropies = 0.0;
       for (uint32 i = 0; i < n; i++) {
     const float r = vel[i]/velSum;
     entropies += SHANNON(r);
       }
       *entRow++ = entropies/log2Sz;
     }
   }
 }
void rcOptoKineticImage::genDFT (rcWindow freqImg, rcWindow phaseImg, rcWindow amplitudeImg)
Definition at line 1008 of file rc_kineticimage.cpp.
References _movie, atan2(), rcWindow::depth(), FFTRealForward(), rcWindow::height(), rcPixel32, rf1Ddft(), rf1Dfft(), rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
   const uint32 movieLth = _movie.size();
   rmAssert(movieLth);
   const int32 width = _movie[0].width(), height = _movie[0].height();
   rmAssert(width == freqImg.width());
   rmAssert(height == freqImg.height());
   rmAssert(rcPixel32 == freqImg.depth());
   rmAssert(width == phaseImg.width());
   rmAssert(height == phaseImg.height());
   rmAssert(rcPixel32 == phaseImg.depth());
   rmAssert(width == amplitudeImg.width());
   rmAssert(height == amplitudeImg.height());
   rmAssert(rcPixel32 == amplitudeImg.depth());
   vector<float> imag(movieLth);
   vector<float> real(movieLth);
   for (int32 y = 0; y < height; y++) {
     if (0) printf("Processing line %d\n", y);
     uint32* fp = (uint32*)freqImg.rowPointer(y);
     float* pp = (float*)phaseImg.rowPointer(y);
     float* ap = (float*)amplitudeImg.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       /* At each location, perform the following steps:
        *
        *   1) Store 1D signal in real and imag vectors.
        *
        *   2) Run dft on signal.
        *
        *   3) Search for peak amplitude.
        *
        *   4) Store peak amplitude, corresponding phase and magnitude
        *      in frqImg, phaseImg and magImg.
        */
       for (uint32 frmNum = 0; frmNum < movieLth; frmNum++) {
     real[frmNum] = (float)_movie[frmNum].getPixel(x,y);
     imag[frmNum] = 0.0;
       }
 #if 0
       printf("%d %d:", x, y);
       for (uint32 g = 0; g < real.size(); g++)
     printf(" (%f %f)", real[g], imag[g]);
       printf("\n     :");
       if (xyzzy_cnt) {
     float* temp = (float*)malloc(movieLth*sizeof(float));
     rmAssert(temp);
     for (uint32 i = 0; i < movieLth; i++)
       temp[i] = real[i];
     rf1Ddft(real, imag, 1);
     int32 retval = FFTRealForward(temp, (int32)movieLth);
     if (retval != 0)
       fprintf(stderr, "Retval %d != 0\n", retval);
     rmAssert(retval == 0);
     for (uint32 i = 0; i < movieLth; i++) {
       float dftval = sqrt(real[i]*real[i] + imag[i]*imag[i]);
       if (fabs(temp[i]-dftval) > 0.0001)
         printf("Cnt %d: pos %d: dft %f fft %f diff %f\n",
            xyzzy_cnt, i, dftval, temp[i], fabs(temp[i]-dftval));
     }
     xyzzy_cnt--;
       }
       else
 #endif
 #if 0
     rf1Ddft(real, imag, 1);
 #else
     rf1Dfft(real, imag, 1);
 #endif
       float maxVal = -1.0;
       uint32 maxIndex = 1;
       for (uint32 i = 1; i < movieLth/2; i++) {
     float val = sqrt(real[i]*real[i] + imag[i]*imag[i]);
     //  printf(" (%f)", val);
     if (val > maxVal) {
       maxVal = val;
       maxIndex = i;
     }
       }
       //      printf("\n");
       float phase = atan2(imag[maxIndex], real[maxIndex]);
       *fp++ = maxIndex;
       *pp++ = phase;
       *ap++ = maxVal;
     }
   }
 }
void rcOptoKineticImage::genDummyImg (rcWindow) inline private
Definition at line 146 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::genEightBitDFT (rcWindow freqImg, rcWindow freqEBImg, rcWindow phaseImg, rcWindow phaseEBImg, rcWindow amplitudeImg, rcWindow amplitudeEBImg, uint32 expectedFreq)
Definition at line 1108 of file rc_kineticimage.cpp.
References _movie, rcWindow::depth(), genKineticStats(), rcWindow::height(), rcPixel32, rcPixel8, rkPI, rmAssert, rcWindow::rowPointer(), rcWindow::setPixel(), and rcWindow::width().
 {
   const int32 width = freqImg.width(), height = freqImg.height();
   rmAssert(rcPixel32 == freqImg.depth());
   rmAssert(width == phaseImg.width());
   rmAssert(height == phaseImg.height());
   rmAssert(rcPixel32 == phaseImg.depth());
   rmAssert(width == amplitudeImg.width());
   rmAssert(height == amplitudeImg.height());
   rmAssert(rcPixel32 == amplitudeImg.depth());
   rmAssert(width == freqEBImg.width());
   rmAssert(height == freqEBImg.height());
   rmAssert(rcPixel8 == freqEBImg.depth());
   rmAssert(width == phaseEBImg.width());
   rmAssert(height == phaseEBImg.height());
   rmAssert(rcPixel8 == phaseEBImg.depth());
   rmAssert(width == amplitudeEBImg.width());
   rmAssert(height == amplitudeEBImg.height());
   rmAssert(rcPixel8 == amplitudeEBImg.depth());
   vector<uint8> freqMap(_movie.size()/2);
   for (uint32 i = 0; i < freqMap.size(); i++)
     freqMap[i] = 0;
   rmAssert(expectedFreq != 0 && expectedFreq < freqMap.size());
   freqMap[expectedFreq] = 255;
   if (expectedFreq > 1)
     freqMap[expectedFreq-1] = 160;
   if (expectedFreq > 2)
     freqMap[expectedFreq-2] = 96;
   if (expectedFreq < freqMap.size() - 1)
     freqMap[expectedFreq+1] = 160;
   if (expectedFreq < freqMap.size() - 2)
     freqMap[expectedFreq+2] = 96;
   for (int32 y = 0; y < height; y++) {
     uint32* xp = (uint32*)freqImg.rowPointer(y);
     for (int32 x = 0; x <width; x++, xp++) {
       rmAssert(*xp < freqMap.size());
       freqEBImg.setPixel(x, y, freqMap[*xp]);
     }
   }
   for (int32 y = 0; y < height; y++) {
     float* xp = (float*)phaseImg.rowPointer(y);
     for (int32 x = 0; x <width; x++, xp++) {
       uint32 phase = (uint32)((*xp * 180)/rkPI);
       phaseEBImg.setPixel(x, y, (phase % 360)/2);
     }
   }
   float minVal, maxVal, mean, stdDev;
   genKineticStats(amplitudeImg, minVal, maxVal, mean, stdDev);
   float scale = (maxVal-minVal) ? 255/(maxVal-minVal) : 0;
   if (scale == 0)
     printf("WARNING: Scale == 0\n");
   printf("minVal %f maxVal %f mean %f stdDev %f\n", minVal, maxVal, mean, stdDev);
   for (int32 y = 0; y < height; y++) {
     float* xp = (float*)amplitudeImg.rowPointer(y);
     for (int32 x = 0; x <width; x++, xp++) {
       uint32 val = (uint32)((*xp - minVal)*scale);
       rmAssert(val < 256);
       amplitudeEBImg.setPixel(x, y, val);
     }
   }
 }
void rcOptoKineticImage::genEightBitFreq (rcWindow freqImg, rcWindow freqEBImg, const float expectedFreq)
Definition at line 1462 of file rc_kineticimage.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), rcWindow::setPixel(), and rcWindow::width().
 {
   const int32 width = freqImg.width(), height = freqImg.height();
   rmAssert(rcPixel32 == freqImg.depth());
   rmAssert(width == freqEBImg.width());
   rmAssert(height == freqEBImg.height());
   rmAssert(rcPixel8 == freqEBImg.depth());
   for (int32 y = 0; y < height; y++) {
     float* xp = (float*)freqImg.rowPointer(y);
     for (int32 x = 0; x < width; x++, xp++) {
       float fdiff = fabs((float)(expectedFreq - *xp));
       if (fdiff <= 0.5)
     freqEBImg.setPixel(x, y, 255);
       else if (fdiff <= 1.0)
     freqEBImg.setPixel(x, y, 128);
       else
     freqEBImg.setPixel(x, y, 0);
     }
   }
 }
void rcOptoKineticImage::genEightBitImg (const rcWindow & kineticImg, rcWindow ebImg, float sdClamp, const vector< uint8 > * map)
Definition at line 1578 of file rc_kineticimage.cpp.
References rcWindow::depth(), genKineticStats(), rcWindow::height(), rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
   const int32 width = kineticImg.width(), height = kineticImg.height();
   rmAssert(width == ebImg.width());
   rmAssert(height == ebImg.height());
   rmAssert(ebImg.depth() == rcPixel8);
   /* Step 1 - Calculate min, max, mean, and std dev.
    */
   float minVal, maxVal, stdDev, mean;
   genKineticStats(kineticImg, minVal, maxVal, mean, stdDev);
   if (0) printf("gebi: clamp %f map 0x%X min %f max %f sd %f mean %f\n",
         sdClamp, (int)map, minVal, maxVal, stdDev, mean);
   /* Step 2 - Figure out minLimit, maxLimit, center, delta, and binSzInv values.
    */
   float minLimit, maxLimit, center, delta, binSzInv;
   /* If clamp value was specified, center the translation around the
    * mean and extend out to sdClamp number of std dev.
    *
    * If not, use the entire dynamic range.
    */
   if (sdClamp > 0) {
     center = mean;
     delta = stdDev*sdClamp;
     minLimit = center - delta;
     maxLimit = center + delta;
     rmAssert(maxLimit - minLimit);
     binSzInv = 256/(maxLimit - minLimit);
   }
   else {
     center = (float)((maxVal - minVal)/2);
     delta = (float)(center - minVal);
     minLimit = (float)minVal;
     maxLimit = (float)maxVal;
     rmAssert(maxLimit - minLimit);
     binSzInv = (float)(256/(maxLimit - minLimit));
   }
   /* Step 3 - Map pixels.
    */
   if (map) {
     const vector<uint8>& mapR(*map);
     rmAssert(mapR.size() >= 256);
     for (int32 y = 0; y < height; y++) {
       const float* srcRow = (const float*)kineticImg.rowPointer(y);
       uint8* destRow = (uint8*)ebImg.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const float val = *srcRow++;
     if (val <= minLimit)
       *destRow++ = mapR[0];
     else if (val >= maxLimit)
       *destRow++ = mapR[255];
     else {
       const uint32 index = (uint32)((val - center + delta) * binSzInv);
       if (index >= 256) { // xyzzy
         printf("minVal %f maxVal %f\n", minVal, maxVal);
         printf("index %d val %f center %f delta %f sdClamp %f stdDev %f\n",
            index, val, center, delta, sdClamp, stdDev);
         printf("minLimit %f maxLimit %f binSzInv %f\n",
            minLimit, maxLimit, binSzInv);
       }
       rmAssert(index < 256);
       *destRow++ = mapR[index];
     }
       }
     }
   }
   else {
      for (int32 y = 0; y < height; y++) {
       const float* srcRow = (const float*)kineticImg.rowPointer(y);
       uint8* destRow = (uint8*)ebImg.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const float val = *srcRow++;
     if (val <= minLimit)
       *destRow++ = 0;
     else if (val >= maxLimit)
       *destRow++ = 255;
     else {
       const uint8 pVal = (uint8)((val - center + delta) * binSzInv);
       //      rmAssert(pVal < 256); True by definition
       *destRow++ = pVal;
     }
       }
     }
   }
 }
void rcOptoKineticImage::genEightBitImg (const rcWindow & kineticImg, rcWindow ebImg, vector< float > & map)
Definition at line 1670 of file rc_kineticimage.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
   const int32 width = kineticImg.width(), height = kineticImg.height();
   rmAssert(width == ebImg.width());
   rmAssert(height == ebImg.height());
   rmAssert(kineticImg.depth() == rcPixel32);
   rmAssert(ebImg.depth() == rcPixel8);
   const uint32 mapSz = map.size() > 255 ? 255 : map.size();
   for (int32 y = 0; y < height; y++) {
     const float* srcRow = (const float*)kineticImg.rowPointer(y);
     uint8* destRow = (uint8*)ebImg.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       float sVal = *srcRow++;
       uint32 pVal;
       for (pVal = 0; pVal < mapSz; pVal++)
     if (sVal < map[pVal])
       break;
       *destRow++ = pVal;
     }
   }
 }
void rcOptoKineticImage::genEightBitImg (const rcWindow & kineticImg, rcWindow & ebImg)
Definition at line 1486 of file rc_kineticimage.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel32, rcPixel8, rfRgb, rmAssert, rmMax, rmMin, rcWindow::rowPointer(), and rcWindow::width().
 {
   const int32 width = freqImg.width(), height = freqImg.height();
   rmAssert(rcPixel32 == freqImg.depth());
   rmAssert(width == freqEBImg.width());
   rmAssert(height == freqEBImg.height());
   rmAssert(rcPixel8 == freqEBImg.depth() || rcPixel32 == freqEBImg.depth ());
   if (freqEBImg.depth() == rcPixel8)
     {
       float pmax (0.0f), pmin (1.0f);
       for (int32 y = 0; y < height; y++)
     {
       float* xp = (float*)freqImg.rowPointer(y);
       for (int32 x = 0; x < width; x++, xp++)
         {
           float p (*xp);
           if (p >= 1.0f) continue;
           pmin = rmMin (p, pmin);
           pmax = rmMax (p, pmax);
         }
     }
       for (int32 y = 0; y < height; y++)
     {
       float* xp = (float*)freqImg.rowPointer(y);
       uint8* destRow = (uint8*)freqEBImg.rowPointer(y);
       for (int32 x = 0; x < width; x++, xp++, destRow++)
         {
           float p (*xp);
           if (p >= 1.0f) continue;
           if (p <= 0.0)
         p = 128 - (p * 127.0) / pmin;
           else
         p = 128 + (p * 127.0) / pmax;
           int32 pv ((int32) p);
           *destRow = (uint8) pv;
         }
     }
     }
   else if (freqEBImg.depth() == rcPixel32)
     {
       float pmax (0.0f), pmin (1.0f);
       for (int32 y = 0; y < height; y++)
     {
       float* xp = (float*)freqImg.rowPointer(y);
       for (int32 x = 0; x < width; x++, xp++)
         {
           float p (*xp);
           if (p >= 1.0f) continue;
           pmin = rmMin (p, pmin);
           pmax = rmMax (p, pmax);
         }
     }
       for (int32 y = 0; y < height; y++)
     {
       float* xp = (float*)freqImg.rowPointer(y);
       uint32* destRow = (uint32 *)freqEBImg.rowPointer(y);
       for (int32 x = 0; x < width; x++, xp++, destRow++)
         {
           float p (*xp);
           uint32 r, g, b;
           g = (uint32) (p * 255);
           r = b = g;
           if (p == 0.0f)
         *destRow = rfRgb (r, g, b);
           else
         {
           if (p < 0.0)
             {
               r = 255;
               b = 0;
             }
           else
             {
               b = 255;
               r = 0;
             }
           uint32 pv = rfRgb (r, g, b);
           *destRow = pv;
         }
         }
     }
     }
 }
void rcOptoKineticImage::genFreqImg (rcWindow freqImg, float fpp, const rcWindow * maskImg = 0)
Definition at line 1182 of file rc_kineticimage.cpp.
References _movie, rs1DFourierResult::amplitude, rcWindow::depth(), rcWindow::height(), rc1DFourierForceFFT, rc1DFourierRaisedCosine, rcFLT_MAX, rcPixel32, rcPixel8, rf1DFourierAnalysis(), rf1DFourierAnalysisVoxels(), rf1DPeakDetect(), rmAssert, rcWindow::rowPointer(), rsAnalysisVoxels::weights, rsAnalysisVoxels::weightsSz, rcWindow::width(), rs1DFourierResult::workingSz, rsAnalysisVoxels::workSig, rsAnalysisVoxels::workSigBase, and rsAnalysisVoxels::workSigSz.
Referenced by rcMuscleSegmenter::genFrequencySegmentation().
 {
   const uint32 movieLth = _movie.size();
   rmAssert(movieLth);
   rmAssert(fpp > 0.0);
   const int32 width = _movie[0].width(), height = _movie[0].height();
   rmAssert(width == freqImg.width());
   rmAssert(height == freqImg.height());
   rmAssert(rcPixel32 == freqImg.depth());
   if (maskImg) {
     rmAssert(width == maskImg->width());
     rmAssert(height == maskImg->height());
     rmAssert(rcPixel8 == maskImg->depth());
   }
   vector<uint32> dummy;
   vector<float> peakLoc, peakVal;
   rs1DFourierResult result;
   float nomOffset = -1.0;
 #ifdef FAST_PROCESSING
   rsAnalysisVoxels info;
   info.weightsSz = 0;
   info.weights = 0;
   info.workSigSz = 0;
   info.workSig = 0;
   info.workSigBase = 0;
   uint8* signal = (uint8*)malloc(movieLth);
   rmAssert(signal);
 #else
   deque<double> signal(movieLth);
 #endif
   for (int32 y = 0; y < height; y++) {
     if (0) printf("Processing line %d\n", y);
     float* fp = (float*)freqImg.rowPointer(y);
     uint8* mip = maskImg ? (uint8*)maskImg->rowPointer(y) : 0;
     for (int32 x = 0; x < width; x++) {
       if (mip && (*mip++ == 0)) {
     *fp++ = 0;
     continue;
       }
       for (uint32 f = 0; f < movieLth; f++)
     signal[f] = _movie[f].getPixel(x, y);
 #ifdef FAST_PROCESSING
       rf1DFourierAnalysisVoxels(signal, movieLth, info, result,
                 rc1DFourierForceFFT | rc1DFourierRaisedCosine);
 #else
       rf1DFourierAnalysis(signal, result,
               rc1DFourierForceFFT | rc1DFourierRaisedCosine);
 #endif
       if (nomOffset == -1.0)
     nomOffset = result.workingSz/fpp;
       rf1DPeakDetect(result.amplitude, dummy, peakLoc, peakVal, 0.10f);
       float maxVal = rcFLT_MAX;
       float sigSum = 0.0, freqSum = 0.0;
       float expLoc = nomOffset;
       for (uint32 p = 0; p < peakLoc.size(); p++) {
     sigSum += peakVal[p];
     if (fabs(peakLoc[p] - expLoc) <= 0.5) {
       maxVal = peakVal[p] < maxVal ? peakVal[p] : maxVal;
       freqSum += maxVal;
       expLoc = peakLoc[p] + nomOffset; // maybe += nomOffset??? xyzzy
     }
     else if (peakLoc[p] > expLoc)
       maxVal = 0;
       }
       *fp++ = (sigSum != 0.0) ? freqSum/sigSum : 0.0;
     }
   }
 #ifdef FAST_PROCESSING
   free(signal);
   if (info.weights)
     free(info.weights);
   if (info.workSigBase)
     free(info.workSigBase);
 #endif
 }
void rcOptoKineticImage::genKineticImg (rcWindow kineticImg)
Definition at line 998 of file rc_kineticimage.cpp.
References _genHdlr.
 {
   (this->*_genHdlr)(kineticImg);
 }
void rcOptoKineticImage::genKineticStats (const rcWindow & kineticImg, float & minVal, float & maxVal, float & mean, float & stdDev)
Definition at line 967 of file rc_kineticimage.cpp.
References rcWindow::depth(), rcWindow::height(), N, rcFLT_MAX, rcFLT_MIN, rcPixel32, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by genEightBitDFT(), and genEightBitImg().
 {
   rmAssert(kineticImg.depth() == rcPixel32);
   const int32 width = kineticImg.width(), height = kineticImg.height();
   const double N = width*height;
   rmAssert(N > 1);
   double sum = 0.0, sumSq = 0.0;
   minVal = rcFLT_MAX;
   maxVal = rcFLT_MIN;
   for (int32 y = 0; y < height; y++) {
     const float* srcRow = (const float*)kineticImg.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       const float val = *srcRow++;
       if (val < minVal)
     minVal = val;
       if (val > maxVal)
     maxVal = val;
       sum += val;
       sumSq += ((double)val)*val;
     }
   }
   mean = (float)(sum/N);
   stdDev = (float)sqrt((sumSq*N - sum*sum)/(N*N - N));
   rmAssert(stdDev > 0.0);
 }
void rcOptoKineticImage::genLogRMS (rcWindow freqImg) private
Definition at line 2102 of file rc_kineticimage.cpp.
References _movie, rcLineSegment< T >::angle(), cos(), rcWindow::depth(), rcLsFit< T >::fit(), rcWindow::height(), rcPixel32, rmAssert, rmSquare, rcWindow::rowPointer(), rcLsFit< T >::update(), and rcWindow::width().
Referenced by rcOptoKineticImage().
 {
   const uint32 movieLth = _movie.size();
   rmAssert(movieLth);
   const int32 width = _movie[0].width(), height = _movie[0].height();
   rmAssert(width == freqImg.width());
   rmAssert(height == freqImg.height());
   rmAssert(rcPixel32 == freqImg.depth());
   deque<float> signal(movieLth);
   for (int32 y = 0; y < height; y++)
     {
       float* fp = (float*)freqImg.rowPointer(y);
       for (int32 x = 0; x < width; x++)
     {
       rcLsFit<float> ls;
       // Basic: fit a line to I(t).
       // RMS: fit a line to <I(t)>
       // LogRMS: fit a line to Log (<I(t)>)
       // Change this to call rfRMS
       float pv = (float) _movie[0].getPixel(x, y);
       float sumsq (rmSquare (pv));
       for (uint32 f = 1; f < movieLth; f++)
         {
           signal[f-1] = sqrt (sumsq / (float) f);
           float pv = (float) _movie[f].getPixel(x, y);
           sumsq += rmSquare (pv);
         }
       for (uint32 f = 0; f < movieLth; f++)
         {
           rc2Fvector it ((float) f / (float) movieLth,
                  signal[f] / 255.0f);
           ls.update (it);
         }
       rcLineSegment<float> l = ls.fit ();
       *fp++ = cos (l.angle());
     }
     }
 }
void rcOptoKineticImage::genStdDevImg (rcWindow stdDevImg) private
Definition at line 1736 of file rc_kineticimage.cpp.
References _movie, _sum, _sumSq, rcWindow::depth(), rcWindow::height(), N, rcPixel16, rcPixel32, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rcOptoKineticImage().
 {
   const uint32 n = _movie.size();
   rmAssert(n > 1);
   const float N = n;
   const int32 width = stdDevImg.width(), height = stdDevImg.height();
   rmAssert(width == _sum.width());
   rmAssert(height == _sum.height());
   rmAssert(stdDevImg.depth() == rcPixel32);
   if (_sum.depth() == rcPixel16) {
     for (int32 y = 0; y < height; y++) {
       float *sdRow = (float*)stdDevImg.rowPointer(y);
       uint16 *sumRow = (uint16*)_sum.rowPointer(y);
       uint32 *sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const float sumSq = *sumSqRow++;
     const float sum = *sumRow++;
     *sdRow++ = sqrt((N*sumSq - sum*sum)/(N*N - N));
       }
     }
   }
   else if (_sum.depth() == rcPixel32) {
     for (int32 y = 0; y < height; y++) {
       float *sdRow = (float*)stdDevImg.rowPointer(y);
       uint32 *sumRow = (uint32*)_sum.rowPointer(y);
       uint32 *sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const float sumSq = *sumSqRow++;
     const float sum = *sumRow++;
     *sdRow++ = sqrt((N*sumSq - sum*sum)/(N*N - N));
       }
     }
   }
   else
     rmAssert(0);
 }
void rcOptoKineticImage::genThetaEntropyImg (rcWindow entropyImg) private
Definition at line 1936 of file rc_kineticimage.cpp.
References _movie, _theta, rcWindow::depth(), rcWindow::height(), initTheta(), N, rcPixel32, rmAssert, rcWindow::rowPointer(), SHANNON, and rcWindow::width().
Referenced by rcOptoKineticImage().
 {
   const uint32 n = _movie.size() - 1;
   rmAssert(_movie.size() > 1);
   const int32 width = entropyImg.width(), height = entropyImg.height();
   rmAssert(width == _movie[0].width());
   rmAssert(height == _movie[0].height());
   rmAssert(entropyImg.depth() == rcPixel32);
   vector<float> theta(n);
   const float N = n;
   const float log2Sz = log2(N);
   initTheta();
   for (int32 y = 0; y < height; y++) {
     float* entRow = (float*)entropyImg.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       /* Step 1 - Calculate the thetas of adjacent pixels. At the same
        * time, calculate the sum of these thetas.
        */
       float thetaSum = 0.0;
       int32 p0 = (int32)_movie[0].getPixel(x, y);
       for (uint32 i = 0; i < n; i++) {
     int32 p1 = (int32)_movie[i+1].getPixel(x, y);
     theta[i] = _theta[p0 - p1 + 255];
     thetaSum += theta[i];
     p0 = p1;
       }
       /* Step 2 - Generate shannon's entropy for this pixel
        * location.
        */
       float entropies = 0.0;
       for (uint32 i = 0; i < n; i++) {
     const float r = theta[i]/thetaSum;
     entropies += SHANNON(r);
       }
       *entRow++ = entropies/log2Sz;
     }
   }
 }
void rcOptoKineticImage::genVarImg (rcWindow stdDevImg) private
Definition at line 1696 of file rc_kineticimage.cpp.
References _movie, _sum, _sumSq, rcWindow::depth(), rcWindow::height(), N, rcPixel16, rcPixel32, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rcOptoKineticImage().
 {
   const uint32 n = _movie.size();
   rmAssert(n > 1);
   const float N = n;
   const int32 width = stdDevImg.width(), height = stdDevImg.height();
   rmAssert(width == _sum.width());
   rmAssert(height == _sum.height());
   rmAssert(stdDevImg.depth() == rcPixel32);
   if (_sum.depth() == rcPixel16) {
     for (int32 y = 0; y < height; y++) {
       float *varRow = (float*)stdDevImg.rowPointer(y);
       uint16 *sumRow = (uint16*)_sum.rowPointer(y);
       uint32 *sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const float sumSq = *sumSqRow++;
     const float sum = *sumRow++;
     *varRow++ = (N*sumSq - sum*sum)/(N*N - N);
       }
     }
   }
   else if (_sum.depth() == rcPixel32) {
     for (int32 y = 0; y < height; y++) {
       float *varRow = (float*)stdDevImg.rowPointer(y);
       uint32 *sumRow = (uint32*)_sum.rowPointer(y);
       uint32 *sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const float sumSq = *sumSqRow++;
     const float sum = *sumRow++;
     *varRow++ = (N*sumSq - sum*sum)/(N*N - N);
       }
     }
   }
   else
     rmAssert(0);
 }
void rcOptoKineticImage::genVelEntropyImg (rcWindow entropyImg) private
Definition at line 1778 of file rc_kineticimage.cpp.
References _movie, _oCnt, _sum, _sumSq, _uCnt, rcWindow::depth(), rcWindow::height(), N, rcFLT_MIN, rcPixel16, rcPixel32, rmAssert, rcWindow::rowPointer(), SHANNON, and rcWindow::width().
Referenced by rcOptoKineticImage().
 {
   const uint32 n = _movie.size();
   rmAssert(n);
   const int32 width = entropyImg.width(), height = entropyImg.height();
   rmAssert(width == _sum.width());
   rmAssert(height == _sum.height());
   rmAssert(entropyImg.depth() == rcPixel32);
   vector<float> vel(n);
   const float N = n;
   const float log2Sz = log2(N);
   _uCnt = _oCnt = 0;
   if (_sum.depth() == rcPixel16) {
     for (int32 y = 0; y < height; y++) {
       float* entRow = (float*)entropyImg.rowPointer(y);
       uint16* sumRow = (uint16*)_sum.rowPointer(y);
       uint32* sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     /* Step 1 - Calculate the std dev and mean for this pixel
      * location from the sum and sum square images.
      */
     const float sumSq = *sumSqRow++;
     const float sum = *sumRow++;
     const float sd = sqrt((sumSq*N - sum*sum)/(N*N - N));
     const float mean = sum/N;
     const float maxSd = sd*4;
     const float minVal = rcFLT_MIN, maxVal = maxSd*2;
     /* Step 2 - Calculate the normalized "velocity" values. At the
      * same time, calculate the sum of these normalized values.
      */
     float velSum = 0.0;
     for (uint32 i = 0; i < n; i++) {
       float val = _movie[i].getPixel(x, y) - mean + maxSd;
       if (val < minVal) {
         val = minVal;
         _uCnt++;
       }
       else if (val > maxVal) {
         val = maxVal;
         _oCnt++;
       }
       velSum += val;
       vel[i] = val;
     }
     /* Step 3 - Generate shannon's entropy for this pixel
      * location.
      */
     float entropies = 0.0;
     for (uint32 i = 0; i < n; i++) {
       const float r = vel[i]/velSum;
       entropies += SHANNON(r);
     }
     float entropy = entropies/log2Sz;
     *entRow++ = entropy > 1.0 ? 1.0 : entropy;
       }
     }
   }
   else if (_sum.depth() == rcPixel32) {
     for (int32 y = 0; y < height; y++) {
       float* entRow = (float*)entropyImg.rowPointer(y);
       uint32* sumRow = (uint32*)_sum.rowPointer(y);
       uint32* sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     /* Step 1 - Calculate the std dev and mean for this pixel
      * location from the sum and sum square images.
      */
     const float sumSq = *sumSqRow++;
     const float sum = *sumRow++;
     const float sd = sqrt((sumSq*N - sum*sum)/(N*N - N));
     const float mean = sum/N;
     const float maxSd = sd*4;
     const float minVal = rcFLT_MIN, maxVal = maxSd*2;
     /* Step 2 - Calculate the normalized "velocity" values. At the
      * same time, calculate the sum of these normalized values.
      */
     float velSum = 0.0;
     for (uint32 i = 0; i < n; i++) {
       float val = _movie[i].getPixel(x, y) - mean + maxSd;
       if (val < minVal) {
         val = minVal;
         _uCnt++;
       }
       else if (val > maxVal) {
         val = maxVal;
         _oCnt++;
       }
       velSum += val;
       vel[i] = val;
     }
     /* Step 3 - Generate shannon's entropy for this pixel
      * location.
      */
     float entropies = 0.0;
     for (uint32 i = 0; i < n; i++) {
       const float r = vel[i]/velSum;
       entropies += SHANNON(r);
     }
     float entropy = entropies/log2Sz;
     *entRow++ = entropy > 1.0 ? 1.0 : entropy;
       }
     }
   }
   else
     rmAssert(0);
 }
void rcOptoKineticImage::incAccelEntropyImg (const rcWindow &) inline private
Definition at line 171 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::incDummyImg (const rcWindow &) inline private
Definition at line 180 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::incLogRMSImg (const rcWindow & img) inline private
Definition at line 166 of file rc_kineticimage.h.
References incrementU8().
Referenced by rcOptoKineticImage().
   { incrementU8(img); }
void rcOptoKineticImage::incrementU8 (const rcWindow & img) private
Definition at line 2016 of file rc_kineticimage.cpp.
References _movie, _sum, _sumSq, rcWindow::depth(), rcWindow::height(), rcPixel16, rcPixel32, rmAssert, rcWindow::rowPointer(), rcWindow::setAllPixels(), and rcWindow::width().
Referenced by incLogRMSImg(), incStdDevImg(), incVarImg(), and incVelEntropyImg().
 {
   const int32 width = img.width(), height = img.height();
   if ((width != _sum.width()) || (height != _sum.height())) {
     rmAssert(_movie.size() == 0);
     _sum = rcWindow(width, height, rcPixel16);
     _sumSq= rcWindow(width, height, rcPixel32);
     _sum.setAllPixels(0);
     _sumSq.setAllPixels(0);
   }
   /* Prevent counter overflows.
    */
   if ((_sum.depth() == rcPixel16) && (_movie.size() > 257)) {
     rcWindow newSum(_sum.width(), _sum.height(), rcPixel32);
     for (int32 y = 0; y < height; y++) {
       uint16* oldSumRow = (uint16*)_sum.rowPointer(y);
       uint32* newSumRow = (uint32*)newSum.rowPointer(y);
       for (int32 x = 0; x < width; x++)
     *newSumRow++ = *oldSumRow++;
     }
     _sum = newSum;
   }
   if (_sum.depth() == rcPixel16) {
     for (int32 y = 0; y < height; y++) {
       const uint8* pelRow = (const uint8*)img.rowPointer(y);
       uint16* sumRow = (uint16*)_sum.rowPointer(y);
       uint32* sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const uint16 pel = *pelRow++;
     *sumRow++ += pel;
     *sumSqRow++ += pel*pel;
       }
     }
   }
   else if (_sum.depth() == rcPixel32) {
     for (int32 y = 0; y < height; y++) {
       const uint8* pelRow = (const uint8*)img.rowPointer(y);
       uint32* sumRow = (uint32*)_sum.rowPointer(y);
       uint32* sumSqRow = (uint32*)_sumSq.rowPointer(y);
       for (int32 x = 0; x < width; x++) {
     const uint16 pel = *pelRow++;
     *sumRow++ += pel;
     *sumSqRow++ += pel*pel;
       }
     }
   }
   else
     rmAssert(0);
 }
void rcOptoKineticImage::incStdDevImg (const rcWindow & img) inline private
Definition at line 158 of file rc_kineticimage.h.
References incrementU8().
Referenced by rcOptoKineticImage().
   { incrementU8(img); }
void rcOptoKineticImage::incThetaEntropyImg (const rcWindow &) inline private
Definition at line 175 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
   { }
void rcOptoKineticImage::incVarImg (const rcWindow & img) inline private
Definition at line 154 of file rc_kineticimage.h.
References incrementU8().
Referenced by rcOptoKineticImage().
   { incrementU8(img); }
void rcOptoKineticImage::incVelEntropyImg (const rcWindow & img) inline private
Definition at line 162 of file rc_kineticimage.h.
References incrementU8().
Referenced by rcOptoKineticImage().
   { incrementU8(img);}
void rcOptoKineticImage::initTheta () private
Definition at line 2072 of file rc_kineticimage.cpp.
References _theta.
Referenced by genThetaEntropyImg().
 {
   if (!_theta.empty())
     return;
   _theta.resize(511);
 #if 1
   float offset = -atan((float)-255) + 0.1;
   for (int32 i = -255; i < 256; i++)
     _theta[255 + i] = atan((float)i) + offset;
 #else
   for (int32 i = 0; i < 252; i++)
     _theta[i] = i*4;
   for (int32 i = 252; i < 259; i++)
     _theta[i] = 252*4 + i - 252;
   for (int32 i = 259; i < 511; i++)
     _theta[i] = 252*4 + 258 - 252 + (i-258)*4;
   for (int32 i = 0; i < 511; i++)
     printf("%d: %f\n", i, _theta[i]);
 #endif
 }
uint32 rcOptoKineticImage::overflow () const inline
Definition at line 133 of file rc_kineticimage.h.
References _oCnt.
 { return _oCnt; }
uint32 rcOptoKineticImage::pop (uint32 cnt = 1)
Definition at line 948 of file rc_kineticimage.cpp.
References _decHdlr, and _movie.
Referenced by update().
 {
   uint32 popCnt = _movie.size();
   uint32 retVal = 0;
   if (popCnt > cnt) {
     retVal = popCnt - cnt;
     popCnt = cnt;
   }
   while (popCnt--) {
     (this->*_decHdlr)(_movie.front());
     _movie.pop_front();
   }
   return retVal;
 }
void rcOptoKineticImage::push (rcWindow img)
Definition at line 904 of file rc_kineticimage.cpp.
References _incHdlr, _movie, rcWindow::depth(), rcWindow::height(), rcPixel8, rmAssert, and rcWindow::width().
Referenced by rcMuscleSegmenter::genFrequencySegmentation(), and update().
 {
   rmAssert(img.depth() == rcPixel8);
   if (!_movie.empty()) {
     rmAssert(img.width() == _movie[0].width());
     rmAssert(img.height() == _movie[0].height());
   }
   else
     rmAssert(img.width()*img.height() > 1);
   (this->*_incHdlr)(img);
   _movie.push_back(img);
 }
void rcOptoKineticImage::push (vector< rcWindow > & sequence)
Definition at line 918 of file rc_kineticimage.cpp.
References _incHdlr, _movie, rcPixel8, and rmAssert.
 {
   for (uint32 i = 0; i < sequence.size(); i++) {
     rmAssert(sequence[i].depth() == rcPixel8);
     if (!_movie.empty()) {
       rmAssert(sequence[i].width() == _movie[0].width());
       rmAssert(sequence[i].height() == _movie[0].height());
     }
     else
       rmAssert(sequence[i].width()*sequence[i].height() > 1);
     (this->*_incHdlr)(sequence[i]);
     _movie.push_back(sequence[i]);
   }
 }
void rcOptoKineticImage::push (deque< rcWindow > & sequence)
Definition at line 933 of file rc_kineticimage.cpp.
References _incHdlr, _movie, rcPixel8, and rmAssert.
 {
   for (uint32 i = 0; i < sequence.size(); i++) {
     rmAssert(sequence[i].depth() == rcPixel8);
     if (!_movie.empty()) {
       rmAssert(sequence[i].width() == _movie[0].width());
       rmAssert(sequence[i].height() == _movie[0].height());
     }
     else
       rmAssert(sequence[i].width()*sequence[i].height() > 1);
     (this->*_incHdlr)(sequence[i]);
     _movie.push_back(sequence[i]);
   }
 }
uint32 rcOptoKineticImage::underflow () const inline
Definition at line 132 of file rc_kineticimage.h.
References _uCnt.
 { return _uCnt; }
void rcOptoKineticImage::update (rcWindow img) inline
Definition at line 73 of file rc_kineticimage.h.
References pop(), and push().
   { pop(); push(img); }
void rcOptoKineticImage::update (vector< rcWindow > & sequence) inline
Definition at line 76 of file rc_kineticimage.h.
References pop(), and push().
   { pop(sequence.size()); push(sequence); }
void rcOptoKineticImage::update (deque< rcWindow > & sequence) inline
Definition at line 79 of file rc_kineticimage.h.
References pop(), and push().
   { pop(sequence.size()); push(sequence); }
Member Data Documentation
IMGHDLR rcOptoKineticImage::_decHdlr private
Definition at line 186 of file rc_kineticimage.h.
Referenced by pop(), and rcOptoKineticImage().
GENHDLR rcOptoKineticImage::_genHdlr private
Definition at line 187 of file rc_kineticimage.h.
Referenced by genKineticImg(), and rcOptoKineticImage().
IMGHDLR rcOptoKineticImage::_incHdlr private
Definition at line 186 of file rc_kineticimage.h.
Referenced by push(), and rcOptoKineticImage().
kineType rcOptoKineticImage::_kType private
Definition at line 185 of file rc_kineticimage.h.
Referenced by rcOptoKineticImage().
deque<rcWindow> rcOptoKineticImage::_movie private
Definition at line 188 of file rc_kineticimage.h.
Referenced by gen1DCorrKineticImgs(), genAccelEntropyImg(), genDFT(), genEightBitDFT(), genFreqImg(), genLogRMS(), genStdDevImg(), genThetaEntropyImg(), genVarImg(), genVelEntropyImg(), incrementU8(), pop(), and push().
uint32 rcOptoKineticImage::_oCnt private
Definition at line 190 of file rc_kineticimage.h.
Referenced by genVelEntropyImg(), and overflow().
rcWindow rcOptoKineticImage::_sum private
Definition at line 189 of file rc_kineticimage.h.
Referenced by decrementU8(), genStdDevImg(), genVarImg(), genVelEntropyImg(), and incrementU8().
rcWindow rcOptoKineticImage::_sumSq private
Definition at line 189 of file rc_kineticimage.h.
Referenced by decrementU8(), genStdDevImg(), genVarImg(), genVelEntropyImg(), and incrementU8().
vector<float> rcOptoKineticImage::_theta private
Definition at line 191 of file rc_kineticimage.h.
Referenced by genThetaEntropyImg(), and initTheta().
uint32 rcOptoKineticImage::_uCnt private
Definition at line 190 of file rc_kineticimage.h.
Referenced by genVelEntropyImg(), and underflow().
The documentation for this class was generated from the following files:
include/analysis/rc_kineticimage.h
src/analysis/code/rc_kineticimage.cpp