Visible: ofbuff Class Reference
ofbuff Class Reference
#include <include/stlplus/fileio.hpp>
Public Member Functions
ofbuff (FILE *handle, bool line_buffer)
ofbuff (const char *filename, size_t bufsize, otext::open_t mode, bool line_buffer)
ofbuff (const std::string &filename, size_t bufsize, otext::open_t mode, bool line_buffer)
virtual ~ofbuff (void)
void open (const std::string &fname, size_t bufsize, otext::open_t mode, bool line_buffer)
virtual void flush (void)
virtual unsigned put (unsigned char)
virtual std::string error_string (void) const
Public Member Functions inherited from obuff
obuff (bool line_buffer=false, otext::newline_t newline=otext::native_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_line_buffer (bool mode)
bool line_buffer (void) const
void set_newline_mode (otext::newline_t newline)
otext::newline_t newline_mode (void) const
unsigned integer_width (void) const
void set_integer_width (unsigned)
unsigned integer_radix (void) const
void set_integer_radix (unsigned)
radix_display_t integer_display (void) const
void set_integer_display (radix_display_t)
unsigned real_width (void) const
void set_real_width (unsigned)
unsigned real_precision (void) const
void set_real_precision (unsigned)
real_display_t real_display (void) const
void set_real_display (real_display_t)
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual ~obuff (void)
Private Member Functions
ofbuff (const ofbuff &)
ofbuff & operator= (const ofbuff &)
Private Attributes
bool m_managed
FILE * m_handle
Friends
class oftext
Additional Inherited Members
Protected Attributes inherited from obuff
bool m_line_buffer
otext::newline_t m_newline
unsigned long m_bytes
unsigned m_line
unsigned m_column
unsigned m_integer_width
unsigned m_integer_radix
radix_display_t m_integer_display
unsigned m_real_width
unsigned m_real_precision
real_display_t m_real_display
int m_error_number
int m_aliases
Detailed Description
Definition at line 95 of file fileio.hpp.
Constructor & Destructor Documentation
ofbuff::ofbuff (FILE * handle, bool line_buffer)
Definition at line 16 of file fileio.cpp.
                                           :
   // for unmanaged files, just pump raw bytes to the file - it is not TextIO's job to do line-endings
   obuff(line_buffer,otext::binary_mode),
   m_managed(false),
   m_handle(fh)
 {
 }
ofbuff::ofbuff (const char * filename, size_t bufsize, otext::open_t mode, bool line_buffer)
Definition at line 24 of file fileio.cpp.
References open().
                                                                                      :
   m_managed(false),
   m_handle(0)
 {
   open(std::string(fname ? fname : ""), bufsize, mode, line_buffer);
 }
ofbuff::ofbuff (const std::string & filename, size_t bufsize, otext::open_t mode, bool line_buffer)
Definition at line 31 of file fileio.cpp.
References open().
                                                                                           :
   m_managed(false),
   m_handle(0)
 {
   open(fname, bufsize, mode, line_buffer);
 }
ofbuff::~ofbuff (void) virtual
Definition at line 92 of file fileio.cpp.
References flush(), m_handle, and m_managed.
 {
   flush();
   if (m_managed && m_handle)
     fclose(m_handle);
 }
ofbuff::ofbuff (const ofbuff &) private
Member Function Documentation
std::string ofbuff::error_string (void) const virtual
Reimplemented from obuff.
Definition at line 38 of file fileio.cpp.
References obuff::error_number(), and obuff::error_string().
 {
   // if the number is positive, it is an errno, otherwise it is a built-in and can be handled by the baseclass
   if (error_number() > 0)
     return std::string(strerror(error_number()));
   else
     return obuff::error_string();
 }
void ofbuff::flush (void) virtual
Reimplemented from obuff.
Definition at line 80 of file fileio.cpp.
References m_handle, obuff::set_error(), and textio_put_failed.
Referenced by ~ofbuff().
 {
   if (m_handle && fflush(m_handle) == EOF)
   {
     int error = ferror(m_handle);
     if (error)
       set_error(error);
     else
       set_error(textio_put_failed);
   }
 }
void ofbuff::open (const std::string & fname, size_t bufsize, otext::open_t mode, bool line_buffer)
Definition at line 47 of file fileio.cpp.
References m_handle, m_managed, otext::overwrite, obuff::set_error(), obuff::set_line_buffer(), and textio_open_failed.
Referenced by ofbuff().
 {
   // open a managed file
   if (fname.empty())
   {
     // an empty filename is an error without even trying to open the file
     // on Windows fopen raises an assertion failure in this case which is unacceptable so I trap it first
     set_error(textio_open_failed);
   }
   else
   {
     m_managed = true;
     // open in binary mode so that *I* have control over newline conventions
     m_handle = fopen(fname.c_str(),(mode==otext::overwrite ? "wb" : "ab"));
     if (!m_handle)
     {
       if (errno)
         set_error(errno);
       else
         set_error(textio_open_failed);
     }
     else if (setvbuf(m_handle,0,(bufsize ? _IOFBF : _IONBF),bufsize) != 0)
     {
       int error = ferror(m_handle);
       if (error)
         set_error(error);
       else
         set_error(textio_open_failed);
     }
   }
   set_line_buffer(line_buffer);
 }
ofbuff& ofbuff::operator= (const ofbuff &) private
unsigned ofbuff::put (unsigned char ch) virtual
Implements obuff.
Definition at line 99 of file fileio.cpp.
References m_handle, and obuff::set_error().
 {
   if (!m_handle) return 0;
   if (fputc(ch, m_handle) == EOF)
   {
     int error = ferror(m_handle);
     if (error)
       set_error(error);
     return 0;
   }
   return 1;
 }
Friends And Related Function Documentation
friend class oftext friend
Definition at line 97 of file fileio.hpp.
Member Data Documentation
FILE* ofbuff::m_handle private
Definition at line 118 of file fileio.hpp.
Referenced by flush(), open(), oftext::operator FILE *(), put(), and ~ofbuff().
bool ofbuff::m_managed private
Definition at line 117 of file fileio.hpp.
Referenced by open(), and ~ofbuff().
The documentation for this class was generated from the following files:
include/stlplus/fileio.hpp
include/stlplus/fileio.cpp