Visible: rcWriterMapper Class Reference
rcWriterMapper Class Reference
#include <include/visiCore/rc_writermanagerimpl.h>
Public Member Functions
rcWriterMapper (const rcWriterInfo *writerArray, uint32 size)
const rcWriterInfo info (rcWriterSemantics type) const
rcWriterSemantics typeTag (const std::string &name) const
const rcWriterSemantics type (const std::string &name) const
Private Attributes
rcWriterNameMap mNameMap
rcWriterTypeMap mTypeMap
rcWriterTagMap mTagMap
Detailed Description
Definition at line 52 of file rc_writermanagerimpl.h.
Constructor & Destructor Documentation
rcWriterMapper::rcWriterMapper (const rcWriterInfo * writerArray, uint32 size) inline
Definition at line 55 of file rc_writermanagerimpl.h.
References eWriterUnknown, info(), mNameMap, mTagMap, mTypeMap, rmAssert, type(), and typeTag().
     {
         // Populate all maps
         for ( uint32 i = 0; i < size; ++i ) {
             rmAssert( writerArray[i].type() != eWriterUnknown );
             // Fill name map
             mNameMap.insert( make_pair( writerArray[i].type(), writerArray[i] ) );
             // Immediate self-test, it can catch duplicates
             rmAssert( info( writerArray[i].type() ).type() == writerArray[i].type() );
             // Fill type map
             mTypeMap.insert( make_pair( writerArray[i].name(), writerArray[i].type() ) );
             // Immediate self-test, it can catch duplicates
             rmAssert( type( writerArray[i].name() ) == writerArray[i].type() );
             // Fill tag map
             mTagMap.insert( make_pair( writerArray[i].tag(), writerArray[i].type() ) );
             // Immediate self-test, it can catch duplicates
             rmAssert( typeTag( writerArray[i].tag() ) == writerArray[i].type() );
         }
         // Check for duplicate types in the list
         rmAssert( mNameMap.size() == size );
         // Check for duplicate display names in the list
         rmAssert( mTypeMap.size() == size );
         // Check for duplicate tag names in the list
         rmAssert( mTagMap.size() == size );
     }
Member Function Documentation
const rcWriterInfo rcWriterMapper::info (rcWriterSemantics type) const inline
Definition at line 87 of file rc_writermanagerimpl.h.
References eScalarWriter, eWriterUnknown, and mNameMap.
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), rcWriterManager::createWriter(), rcWriterMapper(), rcWriterManager::writerName(), and rcWriterManager::writerTag().
{
         rcWriterNameMap::const_iterator pos = mNameMap.find( type );
         if ( pos != mNameMap.end() )
             return pos->second;
         else
             return rcWriterInfo( eWriterUnknown, eScalarWriter, "Unknown", "Unknown", "Unknown", "" );
     }
const rcWriterSemantics rcWriterMapper::type (const std::string & name) const inline
Definition at line 105 of file rc_writermanagerimpl.h.
References eWriterUnknown, and mTypeMap.
Referenced by rcWriterManager::nameType(), and rcWriterMapper().
{
         rcWriterTypeMap::const_iterator pos = mTypeMap.find( name );
         if ( pos != mTypeMap.end() )
             return pos->second;
         else
             return eWriterUnknown;
     }
rcWriterSemantics rcWriterMapper::typeTag (const std::string & name) const inline
Definition at line 96 of file rc_writermanagerimpl.h.
References eWriterUnknown, and mTagMap.
Referenced by rcWriterMapper(), and rcWriterManager::tagType().
{
         rcWriterTagMap::const_iterator pos = mTagMap.find( name );
         if ( pos != mTagMap.end() )
             return pos->second;
         else
             return eWriterUnknown;
     }
Member Data Documentation
rcWriterNameMap rcWriterMapper::mNameMap private
Definition at line 114 of file rc_writermanagerimpl.h.
Referenced by info(), and rcWriterMapper().
rcWriterTagMap rcWriterMapper::mTagMap private
Definition at line 116 of file rc_writermanagerimpl.h.
Referenced by rcWriterMapper(), and typeTag().
rcWriterTypeMap rcWriterMapper::mTypeMap private
Definition at line 115 of file rc_writermanagerimpl.h.
Referenced by rcWriterMapper(), and type().
The documentation for this class was generated from the following file:
include/visiCore/rc_writermanagerimpl.h