Visible: rcScalarTrackImpl Class Reference
rcScalarTrackImpl Class Reference
#include <include/visiCore/rc_scalartrackimpl.h>
Public Member Functions
rcScalarTrackImpl (const char *tag, const char *name, const char *description, const char *displayFormat, uint32 sizeLimit)
virtual ~rcScalarTrackImpl ()
virtual uint32 segments ()
virtual rcSegmentImpl segment (uint32 index)
virtual void popSegment ()
virtual double getExpectedMinimumValue (void)
virtual double getExpectedMaximumValue (void)
virtual double getCurrentMinimumValue (void)
virtual double getCurrentMaximumValue (void)
virtual rcScalarSegmentIterator * getDataSegmentIterator (const rcTimestamp &pos)
virtual uint32 getSegmentCount (void)
virtual void setExpectedMinValue (const double &minValue)
virtual void setExpectedMaxValue (const double &maxValue)
virtual void writeValue (const rcTimestamp &timestamp, const rcRect &focus, const double &value)
virtual void flush (void)
virtual void reset ()
virtual rcWriter * down_cast ()
Public Member Functions inherited from rcTrackImpl
rcTrackImpl (rcTrackType trackType, rcWriterType writerType, const char *tag, const char *name, const char *description, const char *displayFormat, uint32 limit, rcTimestamp firstTime=-1.0)
virtual ~rcTrackImpl ()
virtual rcTrackType getTrackType (void)
virtual rcWriterType getWriterType (void)
virtual const char * getTag (void)
virtual const char * getName (void)
virtual const char * getDescription (void)
virtual uint32 getSizeLimit () const
virtual const char * getDisplayFormatString (void)
virtual rcTimestamp getTrackStart (void)
virtual void setTrackStart (const rcTimestamp &time)
virtual void setExportable (bool e)
virtual void setDescription (const char *text)
virtual void setName (const char *text)
virtual bool isExportable (void)
virtual rcTrackSemantics getSemantics (void)
virtual void setSemantics (const rcTrackSemantics &s)
virtual rcRect getAnalysisRect (void)
virtual void setAnalysisRect (const rcRect &f)
Public Member Functions inherited from rcTrack
virtual ~rcTrack ()
Public Member Functions inherited from rcWriter
virtual ~rcWriter ()
Public Member Functions inherited from rcScalarTrack
virtual ~rcScalarTrack ()
Public Member Functions inherited from rcScalarWriter
virtual ~rcScalarWriter ()
Private Member Functions
void setMinMaxValues (double value)
void setWriterState (const rcTimestamp &time, rcRect focus, double value)
void addSegment (const rcTimestamp &segmentLength)
Private Attributes
double _expectedMinimumValue
double _expectedMaximumValue
double _currentMinimumValue
double _currentMaximumValue
deque< rcScalarSegment > _segments
double _currentValue
Friends
class rcScalarSegmentIteratorImpl
Additional Inherited Members
Public Types inherited from rcScalarTrack
enum { ePersistenceVersion = 1 }
Static Public Member Functions inherited from rcTrack
static rcTrackType type (const std::string &name)
static const std::string & name (rcTrackType type)
Protected Member Functions inherited from rcTrackImpl
rcTimestamp lastSegmentLength ()
rcTimestamp nextSegmentLength (const rcTimestamp &timestamp)
rcTimestamp nextSegmentStart ()
virtual void setWriterState (const rcTimestamp &time, rcRect focus)
void updateFirstTime (const rcTimestamp &timestamp)
Protected Attributes inherited from rcTrackImpl
rcMutex _mutex
rcTimestamp _currentLength
rcRect _currentFocus
uint32 _sizeLimit
rcTimestamp _firstTime
rcTimestamp _expStartTime
bool _isExportable
rcTrackSemantics _dataSemantics
rcRect _analysisFocus
Detailed Description
Definition at line 46 of file rc_scalartrackimpl.h.
Constructor & Destructor Documentation
rcScalarTrackImpl::rcScalarTrackImpl (const char * tag, const char * name, const char * description, const char * displayFormat, uint32 sizeLimit)
Definition at line 168 of file rc_scalartrackimpl.cpp.
References _currentMaximumValue, _currentMinimumValue, _currentValue, _expectedMaximumValue, _expectedMinimumValue, and rcTrackImpl::_isExportable.
         : rcTrackImpl( eScalarTrack , eScalarWriter , tag , name , description, displayFormat, sizeLimit )
 {
     _expectedMinimumValue = 0.0;
     _expectedMaximumValue = 0.0;
     _currentMinimumValue = 1.0;
     _currentMaximumValue = 0.0;
     _currentValue = 0.0;
     _isExportable = true;
 }
virtual rcScalarTrackImpl::~rcScalarTrackImpl () inline virtual
Definition at line 55 of file rc_scalartrackimpl.h.
 { };
Member Function Documentation
void rcScalarTrackImpl::addSegment (const rcTimestamp & segmentLength) private
Definition at line 337 of file rc_scalartrackimpl.cpp.
References rcTrackImpl::_currentFocus, _currentValue, _segments, cZeroTime, and rcTrackImpl::nextSegmentStart().
Referenced by flush(), and writeValue().
 {
     // Zero segment length is not allowed
     if ( segmentLength > cZeroTime ) {
          // Push new segment
         _segments.push_back( rcScalarSegment( nextSegmentStart(), segmentLength, _currentFocus, _currentValue ) );
     }
 }
rcWriter * rcScalarTrackImpl::down_cast () virtual
Implements rcScalarWriter.
Definition at line 307 of file rc_scalartrackimpl.cpp.
 {
     return dynamic_cast<rcWriter*>( this );
 }
void rcScalarTrackImpl::flush (void) virtual
Implements rcScalarWriter.
Definition at line 283 of file rc_scalartrackimpl.cpp.
References rcTrackImpl::_currentFocus, rcTrackImpl::_currentLength, _currentValue, rcTrackImpl::_mutex, addSegment(), rcTrackImpl::lastSegmentLength(), and setWriterState().
 {
     rcLock lock (_mutex);
     // Add final segment
     addSegment( lastSegmentLength() );
     // Update writer state
     setWriterState( _currentLength, _currentFocus, _currentValue );
 }
double rcScalarTrackImpl::getCurrentMaximumValue (void) virtual
Implements rcScalarTrack.
Definition at line 232 of file rc_scalartrackimpl.cpp.
References _currentMaximumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _currentMaximumValue;
 }
double rcScalarTrackImpl::getCurrentMinimumValue (void) virtual
Implements rcScalarTrack.
Definition at line 225 of file rc_scalartrackimpl.cpp.
References _currentMinimumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _currentMinimumValue;
 }
rcScalarSegmentIterator * rcScalarTrackImpl::getDataSegmentIterator (const rcTimestamp & pos) virtual
Implements rcScalarTrack.
Definition at line 241 of file rc_scalartrackimpl.cpp.
References rcTrackImpl::_mutex, and rcScalarSegmentIteratorImpl.
 {
     return new rcScalarSegmentIteratorImpl( this , pos, _mutex );
 }
double rcScalarTrackImpl::getExpectedMaximumValue (void) virtual
Implements rcScalarTrack.
Definition at line 218 of file rc_scalartrackimpl.cpp.
References _expectedMaximumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _expectedMaximumValue;
 }
double rcScalarTrackImpl::getExpectedMinimumValue (void) virtual
Implements rcScalarTrack.
Definition at line 210 of file rc_scalartrackimpl.cpp.
References _expectedMinimumValue, and rcTrackImpl::_mutex.
 {
     rcLock lock (_mutex);
     return _expectedMinimumValue;
 }
uint32 rcScalarTrackImpl::getSegmentCount (void) virtual
Implements rcScalarTrack.
Definition at line 247 of file rc_scalartrackimpl.cpp.
References rcTrackImpl::_mutex, and _segments.
 {
     rcLock lock (_mutex);
     return _segments.size();
 }
void rcScalarTrackImpl::popSegment () virtual
Reimplemented from rcTrackImpl.
Definition at line 198 of file rc_scalartrackimpl.cpp.
References _segments.
 {
     // We have hit the maximum size limit, we must prune oldest value
     _segments.pop_front();
     // Try to compact container
     deque<rcScalarSegment>(_segments).swap(_segments);
 }
void rcScalarTrackImpl::reset (void) virtual
Implements rcScalarWriter.
Definition at line 293 of file rc_scalartrackimpl.cpp.
References rcTrackImpl::_currentLength, _currentMaximumValue, _currentMinimumValue, _currentValue, rcTrackImpl::_firstTime, rcTrackImpl::_mutex, _segments, and cZeroTime.
 {
     rcLock lock (_mutex);
     _segments.clear();
     _currentLength = cZeroTime;
     _firstTime = -1.0;
     _currentMinimumValue = 1.0;
     _currentMaximumValue = 0.0;
     _currentValue = 0.0;
 }
rcSegmentImpl rcScalarTrackImpl::segment (uint32 index) virtual
Reimplemented from rcTrackImpl.
Definition at line 189 of file rc_scalartrackimpl.cpp.
References _segments, and cZeroTime.
 {
     if ( index < _segments.size() )
         return _segments[index];
     else
         return rcSegmentImpl( cZeroTime, cZeroTime, rcRect() );
 }
uint32 rcScalarTrackImpl::segments (void) virtual
Reimplemented from rcTrackImpl.
Definition at line 183 of file rc_scalartrackimpl.cpp.
References _segments.
Referenced by rcScalarSegmentIteratorImpl::setCurrentValue().
 {
     return _segments.size();
 }
void rcScalarTrackImpl::setExpectedMaxValue (const double & maxValue) virtual
Implements rcScalarWriter.
Definition at line 262 of file rc_scalartrackimpl.cpp.
References _expectedMaximumValue.
 {
     _expectedMaximumValue = maxValue;
 }
void rcScalarTrackImpl::setExpectedMinValue (const double & minValue) virtual
Implements rcScalarWriter.
Definition at line 256 of file rc_scalartrackimpl.cpp.
References _expectedMinimumValue.
 {
     _expectedMinimumValue = minValue;
 }
void rcScalarTrackImpl::setMinMaxValues (double value) private
Definition at line 313 of file rc_scalartrackimpl.cpp.
References _currentMaximumValue, and _currentMinimumValue.
Referenced by writeValue().
 {
     // First time through, set current min and max values
     if ( _currentMinimumValue > _currentMaximumValue )
     {
         _currentMinimumValue = value;
         _currentMaximumValue = value;
     }
     // Update min and max current values
     if ( value < _currentMinimumValue )
         _currentMinimumValue = value;
     if ( value > _currentMaximumValue )
         _currentMaximumValue = value;
 }
void rcScalarTrackImpl::setWriterState (const rcTimestamp & time, rcRect focus, double value) private
Definition at line 330 of file rc_scalartrackimpl.cpp.
References _currentValue, and rcTrackImpl::setWriterState().
Referenced by flush(), and writeValue().
 {
     rcTrackImpl::setWriterState( time, focus );
     _currentValue = value;
 }
void rcScalarTrackImpl::writeValue (const rcTimestamp & timestamp, const rcRect & focus, const double & value) virtual
Implements rcScalarWriter.
Definition at line 268 of file rc_scalartrackimpl.cpp.
References rcTrackImpl::_mutex, addSegment(), rcTrackImpl::nextSegmentLength(), setMinMaxValues(), setWriterState(), and rcTrackImpl::updateFirstTime().
 {
     rcLock lock (_mutex);
     // Update first value time
     updateFirstTime( timestamp );
     // Update historical min/max values
     setMinMaxValues( value );
     // Add new segment
     rcTimestamp length = nextSegmentLength( timestamp );
     addSegment( length );
     // Update writer state
     setWriterState( timestamp, focus, value );
 }
Friends And Related Function Documentation
friend class rcScalarSegmentIteratorImpl friend
Definition at line 109 of file rc_scalartrackimpl.h.
Referenced by getDataSegmentIterator().
Member Data Documentation
double rcScalarTrackImpl::_currentMaximumValue private
Definition at line 122 of file rc_scalartrackimpl.h.
Referenced by getCurrentMaximumValue(), rcScalarTrackImpl(), reset(), and setMinMaxValues().
double rcScalarTrackImpl::_currentMinimumValue private
Definition at line 121 of file rc_scalartrackimpl.h.
Referenced by getCurrentMinimumValue(), rcScalarTrackImpl(), reset(), and setMinMaxValues().
double rcScalarTrackImpl::_currentValue private
Definition at line 124 of file rc_scalartrackimpl.h.
Referenced by addSegment(), flush(), rcScalarTrackImpl(), reset(), and setWriterState().
double rcScalarTrackImpl::_expectedMaximumValue private
Definition at line 120 of file rc_scalartrackimpl.h.
Referenced by getExpectedMaximumValue(), rcScalarTrackImpl(), and setExpectedMaxValue().
double rcScalarTrackImpl::_expectedMinimumValue private
Definition at line 119 of file rc_scalartrackimpl.h.
Referenced by getExpectedMinimumValue(), rcScalarTrackImpl(), and setExpectedMinValue().
deque<rcScalarSegment> rcScalarTrackImpl::_segments private
Definition at line 123 of file rc_scalartrackimpl.h.
Referenced by addSegment(), getSegmentCount(), popSegment(), reset(), segment(), segments(), and rcScalarSegmentIteratorImpl::setCurrentValue().
The documentation for this class was generated from the following files:
include/visiCore/rc_scalartrackimpl.h
src/visible/src/rc_scalartrackimpl.cpp