Visible: lm_library Class Reference
lm_library Class Reference
#include <include/stlplus/library_manager.hpp>
Public Types
typedef std::map< lm_unit_name,
lm_unit_ptr > unit_map
Public Member Functions
lm_library (library_manager *manager)
~lm_library (void)
lm_library (const lm_library &)
lm_library & operator= (const lm_library &)
const library_manager * manager (void) const
library_manager * manager (void)
bool create (const std::string &name, const std::string &path, bool writable)
bool open (const std::string &path)
bool load_type (const std::string &type)
bool load_types (void)
bool remove_type (const std::string &type)
bool load (void)
bool save (void)
bool purge (void)
bool close (void)
bool erase (void)
const std::string & name (void) const
const std::string & path (void) const
bool set_read_write (bool writable)
bool set_writable (void)
bool set_read_only (void)
bool writable (void) const
bool read_only (void) const
bool os_writable (void) const
bool os_read_only (void) const
bool lm_writable (void) const
bool lm_read_only (void) const
bool exists (const lm_unit_name &name) const
lm_unit_ptr create (const lm_unit_name &)
bool loaded (const lm_unit_name &name) const
bool load (const lm_unit_name &unit)
bool purge (const lm_unit_name &unit)
bool save (const lm_unit_name &unit)
bool erase (const lm_unit_name &name)
bool mark (const lm_unit_name &name)
time_t modified (const lm_unit_name &name) const
bool erase_by_source (const std::string &source_file)
const lm_unit_ptr find (const lm_unit_name &name) const
lm_unit_ptr find (const lm_unit_name &name)
std::vector< lm_unit_name > names (void) const
std::vector< std::string > names (const std::string &type) const
std::vector< lm_unit_ptr > handles (void) const
std::vector< lm_unit_ptr > handles (const std::string &type) const
bool out_of_date (const lm_unit_name &name) const
bool up_to_date (const lm_unit_name &name) const
lm_dependencies out_of_date_reason (const lm_unit_name &name) const
lm_tidy_result tidy (void)
bool pretty_print (otext &str, unsigned indent, bool print_units, const std::string &type) const
otext & print (otext &str, unsigned indent=0) const
otext & print_long (otext &str, unsigned indent=0) const
Private Member Functions
unit_map::iterator local_find (const lm_unit_name &name)
unit_map::const_iterator local_find (const lm_unit_name &name) const
Private Attributes
std::string m_name
std::string m_path
bool m_writable
unit_map m_units
library_manager * m_manager
Friends
class library_manager
class lm_unit
otext & print (otext &str, const lm_library &lib, unsigned indent=0)
otext & print_long (otext &str, const lm_library &lib, unsigned indent=0)
otext & operator<< (otext &str, const lm_library &lib)
Detailed Description
Definition at line 401 of file library_manager.hpp.
Member Typedef Documentation
typedef std::map<lm_unit_name,lm_unit_ptr> lm_library::unit_map
Definition at line 407 of file library_manager.hpp.
Constructor & Destructor Documentation
lm_library::lm_library (library_manager * manager)
Definition at line 949 of file library_manager.cpp.
                                            : m_writable(false), m_manager(lib)
 {
 }
lm_library::~lm_library (void)
Definition at line 953 of file library_manager.cpp.
References close().
 {
   close();
 }
lm_library::lm_library (const lm_library & r)
Definition at line 958 of file library_manager.cpp.
 {
   *this = r;
 }
Member Function Documentation
bool lm_library::close (void)
Definition at line 1081 of file library_manager.cpp.
References m_path, m_units, m_writable, and save().
Referenced by create(), erase(), open(), and ~lm_library().
 {
   bool result = save();
   m_units.clear();
   m_path = "";
   m_writable = false;
   return result;
 }
bool lm_library::create (const std::string & name, const std::string & path, bool writable)
Definition at line 987 of file library_manager.cpp.
References close(), create_library(), m_manager, library_manager::m_owner, and open().
 {
   close();
   return create_library(path, m_manager->m_owner, name, writable) && open(path);
 }
lm_unit_ptr lm_library::create (const lm_unit_name & name)
Definition at line 1184 of file library_manager.cpp.
References DEBUG_ASSERT, erase(), lm_unit_name::lowercase(), library_manager::m_callbacks, m_manager, library_manager::m_unit_case, m_units, name(), read_only(), smart_ptr_nocopy< T >::set(), and lm_unit_name::type().
 {
   DEBUG_ASSERT(m_manager);
   if (read_only()) return lm_unit_ptr();
   // preserve the unit's name, but use a lowercase key in case-insensitive mode
   lm_unit_name uname = name;
   if (!m_manager->m_unit_case) uname.lowercase();
   // remove any existing unit with the same name
   erase(uname);
   // use the callbacks to create a new unit
   lm_callback_map::iterator callback = m_manager->m_callbacks.find(name.type());
   if (callback == m_manager->m_callbacks.end()) return lm_unit_ptr();
   lm_unit_ptr new_unit;
   new_unit.set(callback->second.m_callback(name,this,callback->second.m_type_data));
   new_unit->m_loaded = true;
   // add it to the library manager
   m_units[uname] = new_unit;
   return m_units[uname];
 }
bool lm_library::erase (void)
Definition at line 1090 of file library_manager.cpp.
References close(), erase_library(), m_manager, library_manager::m_owner, m_path, and path().
Referenced by create(), erase_by_source(), and tidy().
 {
   // preserve the path because close destroys it
   std::string path = m_path;
   return close() && erase_library(path, m_manager->m_owner);
 }
bool lm_library::erase (const lm_unit_name & name)
Definition at line 1235 of file library_manager.cpp.
References file_delete(), local_find(), m_units, and read_only().
 {
   if (read_only()) return false;
   lm_library::unit_map::iterator i = local_find(name);
   if (i == m_units.end()) return false;
   std::string spec = i->second->filename();
   std::string header_spec = i->second->header_filename();
   m_units.erase(i);
   file_delete(spec);
   file_delete(header_spec);
   return true;
 }
bool lm_library::erase_by_source (const std::string & source_file)
Definition at line 1263 of file library_manager.cpp.
References erase(), filespec_to_path(), find(), names(), and read_only().
 {
   if (read_only()) return false;
   if (source_file.empty()) return false;
   bool result = false;
   std::string source_file_full = filespec_to_path(source_file);
   // erase by unit name so that I don't have to deal with an iterator to a changing map
   std::vector<lm_unit_name> units = names();
   for (std::vector<lm_unit_name>::iterator i = units.begin(); i != units.end(); i++)
   {
     lm_unit_ptr unit = find(*i);
     if (unit && unit->source_file_present())
     {
       std::string file_full = unit->source_file().path_full(unit->library_path());
       if (file_full == source_file_full)
       {
         erase(*i);
         result = true;
       }
     }
   }
   return result;
 }
bool lm_library::exists (const lm_unit_name & name) const
Definition at line 1179 of file library_manager.cpp.
References find(), and smart_ptr_nocopy< T >::present().
 {
   return find(name).present();
 }
const lm_unit_ptr lm_library::find (const lm_unit_name & name) const
Definition at line 1287 of file library_manager.cpp.
References DEBUG_ASSERT, local_find(), and m_units.
Referenced by erase_by_source(), exists(), load(), loaded(), mark(), modified(), purge(), and save().
 {
   lm_library::unit_map::const_iterator i = local_find(name);
   if (i == m_units.end()) return lm_unit_ptr();
   DEBUG_ASSERT(i->second->library() == this);
   return i->second;
 }
lm_unit_ptr lm_library::find (const lm_unit_name & name)
Definition at line 1295 of file library_manager.cpp.
References DEBUG_ASSERT, local_find(), and m_units.
 {
   lm_library::unit_map::iterator i = local_find(name);
   if (i == m_units.end()) return lm_unit_ptr();
   DEBUG_ASSERT(i->second->library() == this);
   return i->second;
 }
std::vector< lm_unit_ptr > lm_library::handles (void) const
Definition at line 1320 of file library_manager.cpp.
References m_units.
 {
   std::vector<lm_unit_ptr> result;
   for (lm_library::unit_map::const_iterator i = m_units.begin(); i != m_units.end(); i++)
     result.push_back(i->second);
   return result;
 }
std::vector< lm_unit_ptr > lm_library::handles (const std::string & type) const
Definition at line 1328 of file library_manager.cpp.
References m_units.
 {
   std::vector<lm_unit_ptr> result;
   for (lm_library::unit_map::const_iterator i = m_units.begin(); i != m_units.end(); i++)
     if (i->first.type() == type)
       result.push_back(i->second);
   return result;
 }
bool lm_library::lm_read_only (void) const
Definition at line 1155 of file library_manager.cpp.
References m_writable.
Referenced by read_only().
 {
   return !m_writable;
 }
bool lm_library::lm_writable (void) const
Definition at line 1150 of file library_manager.cpp.
References m_writable.
Referenced by writable().
 {
   return m_writable;
 }
bool lm_library::load (void)
Definition at line 1057 of file library_manager.cpp.
References m_units.
 {
   bool result = true;
   for (unit_map::iterator i = m_units.begin(); i != m_units.end(); i++)
     result &= i->second->load();
   return result;
 }
bool lm_library::load (const lm_unit_name & unit)
Definition at line 1210 of file library_manager.cpp.
References find().
 {
   lm_unit_ptr unit = find(name);
   if (!unit) return false;
   return unit->load();
 }
bool lm_library::load_type (const std::string & type)
Definition at line 1005 of file library_manager.cpp.
References basename_part(), create_filename(), DEBUG_ASSERT, folder_wildcard(), lm_unit, lm_unit_name::lowercase(), library_manager::m_callbacks, m_manager, m_path, library_manager::m_unit_case, m_units, and smart_ptr_nocopy< T >::set().
Referenced by load_types().
 {
   DEBUG_ASSERT(m_manager);
   lm_callback_map::iterator callback = m_manager->m_callbacks.find(type);
   if (callback == m_manager->m_callbacks.end()) return false;
   // a null callback means create a dummy unit from the baseclass only
   lm_create_callback fn = callback->second.m_callback;
   void* data = callback->second.m_type_data;
   // for each file in the library folder that matches the type of the create callback, create an unloaded unit
   std::vector<std::string> files = folder_wildcard(m_path, create_filename("*", type), false, true);
   for (unsigned i = 0; i < files.size(); i++)
   {
     // key by unit name - lowercase name if case-insensitive
     lm_unit_name uname(basename_part(files[i]),type);
     if (!m_manager->m_unit_case) uname.lowercase();
     lm_unit_ptr unit;
     // if there's a callback, use it to create the subclass, else create the superclass which only contains header information
     if (fn)
       unit.set(fn(uname,this,data));
     else
       unit.set(new lm_unit(uname,this));
     m_units[uname] = unit;
   }
   return true;
 }
bool lm_library::load_types (void)
Definition at line 1031 of file library_manager.cpp.
References DEBUG_ASSERT, load_type(), library_manager::m_callbacks, and m_manager.
Referenced by open().
 {
   DEBUG_ASSERT(m_manager);
   bool result = true;
   for (lm_callback_map::const_iterator i = m_manager->m_callbacks.begin(); i != m_manager->m_callbacks.end(); i++)
     result &= load_type(i->first);
   return result;
 }
bool lm_library::loaded (const lm_unit_name & name) const
Definition at line 1204 of file library_manager.cpp.
References find().
 {
   lm_unit_ptr unit = find(name);
   return unit && unit->loaded();
 }
lm_library::unit_map::iterator lm_library::local_find (const lm_unit_name & name) private
Definition at line 1163 of file library_manager.cpp.
References lm_unit_name::lowercase(), m_manager, library_manager::m_unit_case, m_units, and name().
Referenced by erase(), find(), and remove_type().
 {
   // implement the case-sensitivity
   lm_unit_name local = name;
   if (!m_manager->m_unit_case) local.lowercase();
   return m_units.find(local);
 }
lm_library::unit_map::const_iterator lm_library::local_find (const lm_unit_name & name) const private
Definition at line 1171 of file library_manager.cpp.
References lowercase(), m_manager, library_manager::m_unit_case, m_units, lm_unit_name::name(), name(), and lm_unit_name::set_name().
 {
   // implement the case-sensitivity
   lm_unit_name local = name;
   if (!m_manager->m_unit_case) local.set_name(lowercase(local.name()));
   return m_units.find(local);
 }
const library_manager * lm_library::manager (void) const
Definition at line 974 of file library_manager.cpp.
References m_manager.
Referenced by lm_unit::print_long().
 {
   return m_manager;
 }
library_manager * lm_library::manager (void)
Definition at line 979 of file library_manager.cpp.
References m_manager.
 {
   return m_manager;
 }
bool lm_library::mark (const lm_unit_name & name)
Definition at line 1248 of file library_manager.cpp.
References find(), and read_only().
 {
   if (read_only()) return false;
   lm_unit_ptr unit = find(name);
   if (!unit) return false;
   unit->mark();
   return true;
 }
time_t lm_library::modified (const lm_unit_name & name) const
Definition at line 1257 of file library_manager.cpp.
References find().
Referenced by out_of_date_chk().
 {
   lm_unit_ptr unit = find(name);
   return unit ? unit->modified() : 0;
 }
const std::string & lm_library::name (void) const
Definition at line 1097 of file library_manager.cpp.
References m_name.
Referenced by create(), lm_unit::library_name(), library_manager::load_mappings(), local_find(), pretty_print(), print(), print_long(), and remove_type().
 {
   return m_name;
 }
std::vector< lm_unit_name > lm_library::names (void) const
Definition at line 1303 of file library_manager.cpp.
References m_units.
Referenced by erase_by_source(), pretty_print(), remove_type(), and tidy().
 {
   std::vector<lm_unit_name> result;
   for (lm_library::unit_map::const_iterator i = m_units.begin(); i != m_units.end(); i++)
     result.push_back(i->second->unit_name());
   return result;
 }
std::vector< std::string > lm_library::names (const std::string & type) const
Definition at line 1311 of file library_manager.cpp.
References m_units.
 {
   std::vector<std::string> result;
   for (lm_library::unit_map::const_iterator i = m_units.begin(); i != m_units.end(); i++)
     if (i->first.type() == type)
       result.push_back(i->second->name());
   return result;
 }
bool lm_library::open (const std::string & path)
Definition at line 993 of file library_manager.cpp.
References close(), folder_to_path(), load_types(), m_manager, m_name, library_manager::m_owner, m_path, m_writable, and read_context().
Referenced by create().
 {
   close();
   if (!read_context(path, m_manager->m_owner, m_name, m_writable)) return false;
   // convert path to full path on load
   m_path = folder_to_path(path);
   return load_types();
 }
lm_library & lm_library::operator= (const lm_library & r)
Definition at line 963 of file library_manager.cpp.
References DEBUG_ASSERT, m_manager, m_name, m_path, m_units, and m_writable.
 {
   // only legal to copy an empty library - i.e. prior to loading any units
   DEBUG_ASSERT(m_units.empty());
   m_name = r.m_name;
   m_path = r.m_path;
   m_writable = r.m_writable;
   m_manager = r.m_manager;
   return *this;
 }
bool lm_library::os_read_only (void) const
Definition at line 1145 of file library_manager.cpp.
References folder_writable(), and path().
Referenced by read_only(), and set_read_write().
 {
   return !folder_writable(path());
 }
bool lm_library::os_writable (void) const
Definition at line 1140 of file library_manager.cpp.
References folder_writable(), and path().
Referenced by writable().
 {
   return folder_writable(path());
 }
bool lm_library::out_of_date (const lm_unit_name & name) const
Definition at line 1340 of file library_manager.cpp.
References m_manager, m_name, and library_manager::out_of_date().
Referenced by lm_unit::out_of_date(), and tidy().
 {
   return m_manager->out_of_date(m_name, name);
 }
lm_dependencies lm_library::out_of_date_reason (const lm_unit_name & name) const
Definition at line 1350 of file library_manager.cpp.
References m_manager, m_name, and library_manager::out_of_date_reason().
Referenced by lm_unit::out_of_date_reason(), and pretty_print().
 {
   return m_manager->out_of_date_reason(m_name, unit);
 }
const std::string & lm_library::path (void) const
Definition at line 1102 of file library_manager.cpp.
References m_path.
Referenced by erase(), lm_unit::library_path(), os_read_only(), os_writable(), pretty_print(), print(), and print_long().
 {
   return m_path;
 }
bool lm_library::pretty_print (otext & str, unsigned indent, bool print_units, const std::string & type) const
Definition at line 1383 of file library_manager.cpp.
References DEBUG_ASSERT, lm_dependencies::empty(), endl(), lm_dependencies::file_dependency(), lm_dependencies::file_size(), filespec_to_relative_path(), folder_to_relative_path(), lm_unit_dependency::library(), library_manager::m_callbacks, m_manager, lm_unit_dependency::name(), name(), names(), out_of_date_reason(), path(), lm_file_dependency::path_full(), print_indent(), read_only(), lm_dependencies::source_file(), lm_dependencies::source_file_present(), lm_unit_dependency::type(), lm_dependencies::unit_dependency(), lm_dependencies::unit_size(), and library_manager::work().
 {
   DEBUG_ASSERT(m_manager);
   // print the library information
   print_indent(str, indent);
   if (this == m_manager->work())
     str << "->> ";
   else
     str << "    ";
   str << "Library " << name() << " in directory " << folder_to_relative_path(path());
   if (read_only()) str << " (locked)";
   str << endl;
   // select the units
   if (print_units)
   {
     // separate into a block per unit kind
     for (lm_callback_map::const_iterator j = m_manager->m_callbacks.begin(); j != m_manager->m_callbacks.end(); j++)
     {
       // select the requested unit kind
       if (type.empty() || type == j->first)
       {
         // get all the units of this kind
         std::vector<std::string> unit_names = names(j->first);
         if (!unit_names.empty())
         {
           print_indent(str, indent+1);
           str << "    " << j->second.m_description << endl;
           for (unsigned k = 0; k < unit_names.size(); k++)
           {
             lm_dependencies reason = out_of_date_reason(lm_unit_name(unit_names[k],j->first));
             print_indent(str, indent+2);
             str << "    - " << unit_names[k];
             if (!reason.empty()) str << " (out of date)";
             str << endl;
             if (!reason.empty())
             {
               if (reason.source_file_present())
               {
                 const lm_file_dependency& file = reason.source_file();
                 print_indent(str, indent+3);
                 str << "    * source file " << filespec_to_relative_path(file.path_full(path())) << " has changed" << endl;
               }
               for (unsigned i1 = 0; i1 < reason.file_size(); i1++)
               {
                 const lm_file_dependency& file = reason.file_dependency(i1);
                 print_indent(str, indent+3);
                 str << "    * file " << filespec_to_relative_path(file.path_full(path())) << " has changed" << endl;
               }
               for (unsigned i2 = 0; i2 < reason.unit_size(); i2++)
               {
                 const lm_unit_dependency& file = reason.unit_dependency(i2);
                 lm_callback_map::const_iterator entry = m_manager->m_callbacks.find(file.type());
                 print_indent(str, indent+3);
                 str << "    * " << entry->second.m_description << " " << file.library() << "." << file.name() << " has changed" << endl;
               }
             }
           }
         }
       }
     }
   }
   return true;
 }
otext & lm_library::print (otext & str, unsigned indent = 0) const
Definition at line 1453 of file library_manager.cpp.
References endl(), m_units, name(), path(), and print_indent().
Referenced by print().
 {
   print_indent(str, indent);
   str << name() << " in " << path() << endl;
   for (lm_library::unit_map::const_iterator i = m_units.begin(); i != m_units.end(); i++)
   {
     print_indent(str, indent+1);
     i->second->print(str);
     str << endl;
   }
   return str;
 }
otext & lm_library::print_long (otext & str, unsigned indent = 0) const
Definition at line 1466 of file library_manager.cpp.
References endl(), m_units, name(), path(), print_indent(), and writable().
Referenced by print_long().
 {
   print_indent(str, indent);
   str << name() << " in " << path() << " " << (writable() ? "writable" : "read-only") << endl;
   for (lm_library::unit_map::const_iterator i = m_units.begin(); i != m_units.end(); i++)
     i->second->print_long(str, indent+1);
   return str;
 }
bool lm_library::purge (void)
Definition at line 1073 of file library_manager.cpp.
References m_units.
 {
   bool result = true;
   for (unit_map::iterator i = m_units.begin(); i != m_units.end(); i++)
     result &= i->second->purge();
   return result;
 }
bool lm_library::purge (const lm_unit_name & unit)
Definition at line 1217 of file library_manager.cpp.
References find(), and save().
 {
   lm_unit_ptr unit = find(name);
   if (!unit) return false;
   bool result = save(name);
   result &= unit->purge();
   unit->m_loaded = false;
   return result;
 }
bool lm_library::read_only (void) const
Definition at line 1135 of file library_manager.cpp.
References lm_read_only(), and os_read_only().
Referenced by create(), erase(), erase_by_source(), mark(), pretty_print(), and save().
 {
   return os_read_only() || lm_read_only();
 }
bool lm_library::remove_type (const std::string & type)
Definition at line 1040 of file library_manager.cpp.
References local_find(), m_units, name(), and names().
 {
   bool result = true;
   std::vector<std::string> units = names(type);
   for (std::vector<std::string>::iterator i = units.begin(); i != units.end(); i++)
   {
     lm_unit_name name(*i, type);
     lm_library::unit_map::iterator ni = local_find(name);
     if (ni != m_units.end())
       m_units.erase(ni);
   }
   return result;
 }
bool lm_library::save (void)
Definition at line 1065 of file library_manager.cpp.
References m_units.
Referenced by close(), and purge().
 {
   bool result = true;
   for (unit_map::iterator i = m_units.begin(); i != m_units.end(); i++)
     result &= i->second->save();
   return result;
 }
bool lm_library::save (const lm_unit_name & unit)
Definition at line 1227 of file library_manager.cpp.
References find(), and read_only().
 {
   if (read_only()) return false;
   lm_unit_ptr unit = find(name);
   if (!unit) return false;
   return unit->save();
 }
bool lm_library::set_read_only (void)
Definition at line 1125 of file library_manager.cpp.
References set_read_write().
 {
   return set_read_write(false);
 }
bool lm_library::set_read_write (bool writable)
Definition at line 1110 of file library_manager.cpp.
References m_manager, m_name, library_manager::m_owner, m_path, m_writable, os_read_only(), read_context(), writable(), and write_context().
Referenced by set_read_only(), and set_writable().
 {
   if (m_writable == writable) return true;
   if (os_read_only()) return false;
   m_writable = writable;
   if (!write_context(m_path, m_manager->m_owner, m_name, m_writable))
     read_context(m_path, m_manager->m_owner, m_name, m_writable);
   return m_writable == writable;
 }
bool lm_library::set_writable (void)
Definition at line 1120 of file library_manager.cpp.
References set_read_write().
 {
   return set_read_write(true);
 }
lm_tidy_result lm_library::tidy (void)
Definition at line 1355 of file library_manager.cpp.
References erase(), names(), and out_of_date().
 {
   lm_tidy_result result = std::make_pair(true,0);
   // erase every unit that is out of date
   // this will potentially make other units out of date, so keep erasing until everything is up to date or an error occurs
   for (;;)
   {
     std::vector<lm_unit_name> units = names();
     unsigned initial_count = result.second;
     for (std::vector<lm_unit_name>::iterator i = units.begin(); i != units.end(); i++)
     {
       if (out_of_date(*i))
       {
         if (!erase(*i))
           result.first = false;
         else
           result.second++;
       }
     }
     if (!result.first) break;
     if (result.second == initial_count) break;
   }
   return result;
 }
bool lm_library::up_to_date (const lm_unit_name & name) const
Definition at line 1345 of file library_manager.cpp.
References m_manager, m_name, and library_manager::up_to_date().
Referenced by lm_unit::up_to_date().
 {
   return m_manager->up_to_date(m_name, name);
 }
bool lm_library::writable (void) const
Definition at line 1130 of file library_manager.cpp.
References lm_writable(), and os_writable().
Referenced by print_long(), and set_read_write().
 {
   return os_writable() && lm_writable();
 }
Friends And Related Function Documentation
friend class library_manager friend
Definition at line 405 of file library_manager.hpp.
friend class lm_unit friend
Definition at line 406 of file library_manager.hpp.
Referenced by load_type().
otext& operator<< (otext & str, const lm_library & lib) friend
Definition at line 1485 of file library_manager.cpp.
 {
   return print(str,lib);
 }
otext& print (otext & str, const lm_library & lib, unsigned indent = 0) friend
Definition at line 1475 of file library_manager.cpp.
 {
   return lib.print(str, indent);
 }
otext& print_long (otext & str, const lm_library & lib, unsigned indent = 0) friend
Definition at line 1480 of file library_manager.cpp.
 {
   return lib.print_long(str, indent);
 }
Member Data Documentation
library_manager* lm_library::m_manager private
Definition at line 515 of file library_manager.hpp.
Referenced by create(), erase(), lm_unit::load(), library_manager::load_mappings(), load_type(), load_types(), local_find(), manager(), open(), operator=(), out_of_date(), out_of_date_reason(), pretty_print(), lm_unit::save(), set_read_write(), and up_to_date().
std::string lm_library::m_name private
Definition at line 511 of file library_manager.hpp.
Referenced by name(), open(), operator=(), out_of_date(), out_of_date_reason(), set_read_write(), and up_to_date().
std::string lm_library::m_path private
Definition at line 512 of file library_manager.hpp.
Referenced by close(), erase(), load_type(), open(), operator=(), path(), and set_read_write().
unit_map lm_library::m_units private
Definition at line 514 of file library_manager.hpp.
Referenced by close(), create(), erase(), find(), handles(), load(), load_type(), local_find(), names(), operator=(), print(), print_long(), purge(), remove_type(), and save().
bool lm_library::m_writable private
Definition at line 513 of file library_manager.hpp.
Referenced by close(), lm_read_only(), lm_writable(), open(), operator=(), and set_read_write().
The documentation for this class was generated from the following files:
include/stlplus/library_manager.hpp
include/stlplus/library_manager.cpp