Visible: rcConditionVariable Class Reference
rcConditionVariable Class Reference
#include <include/util/rc_thread.h>
Public Member Functions
rcConditionVariable (int32 initValue=0)
virtual ~rcConditionVariable ()
int32 incrementVariable (int32 value, int32 goal)
int32 decrementVariable (int32 value, int32 goal)
int32 waitUntilLessThan (int32 goal)
int32 waitUntilGreaterThan (int32 goal)
Private Member Functions
int32 mutateFct (const int32 value, const int32 goal, const bool increment)
int32 waitFct (const int32 goal, const bool lessThan)
rcConditionVariable (const rcConditionVariable &)
rcConditionVariable & operator= (const rcConditionVariable &)
Private Attributes
rcMutex _mutex
void * _cond
int32 _var
Detailed Description
Definition at line 177 of file rc_thread.h.
Constructor & Destructor Documentation
rcConditionVariable::rcConditionVariable (int32 initValue = 0)
Definition at line 512 of file rc_thread_mac.cpp.
References _cond, NULL, and rmDim.
   : _mutex(), _cond((void*) new pthread_cond_t), _var(initValue)
 {
   int error;
   if ((error = pthread_cond_init((pthread_cond_t*)_cond, NULL)))
   {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg),
          "CV: condition variable init failed %d", error);
     throw general_exception(errMsg);
   }
 }
rcConditionVariable::~rcConditionVariable () virtual
Definition at line 526 of file rc_thread_mac.cpp.
References _cond, and rmDim.
 {
   int error;
   if (!_cond) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "CV: Invalid condition variable");
     throw general_exception(errMsg);
   }
   if ((error = pthread_cond_destroy((pthread_cond_t*)_cond)))
   {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg),
          "CV: condition variable destroy failed %d", error);
     throw general_exception(errMsg);
   }
 }
rcConditionVariable::rcConditionVariable (const rcConditionVariable &) private
Member Function Documentation
int32 rcConditionVariable::decrementVariable (int32 value, int32 goal)
Definition at line 550 of file rc_thread_mac.cpp.
References mutateFct().
Referenced by rcEngineMovieSaver::error_cleanup(), rcEngineMovieCapture::saveComplete(), rcEngineMovieSaver::saveHdlr(), and rcEngineMovieCapture::startSaveThread().
 {
   return mutateFct(value, goal, false);
 }
int32 rcConditionVariable::incrementVariable (int32 value, int32 goal)
Definition at line 545 of file rc_thread_mac.cpp.
References mutateFct().
Referenced by rcEngineMovieCapture::closeSaveFile(), and rcEngineMovieCapture::run().
 {
   return mutateFct(value, goal, true);
 }
int32 rcConditionVariable::mutateFct (const int32 value, const int32 goal, const bool increment) private
Definition at line 565 of file rc_thread_mac.cpp.
References _cond, _mutex, _var, and rmDim.
Referenced by decrementVariable(), and incrementVariable().
 {
   int error;
   if (!_cond) {
     char errMsg[100];
     snprintf(errMsg, rmDim(errMsg), "Invalid condition variable");
     throw general_exception(errMsg);
   }
   rcLock lock(_mutex);
   if (increment)
     _var += value;
   else
     _var -= value;
   /* Why bother with retVal? Playing it safe. Not clear if unlock of
    * mutex occurs before or after return value is calculated.
    */
   int32 retVal = _var;
   if ((increment && (_var > goal)) || (!increment && (_var < goal))) {
     if ((error = pthread_cond_signal((pthread_cond_t *)_cond))) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg),
            "CV: condition variable signal failed %d", error);
       throw general_exception(errMsg);
     }
   }
   return retVal;
 }
rcConditionVariable& rcConditionVariable::operator= (const rcConditionVariable &) private
int32 rcConditionVariable::waitFct (const int32 goal, const bool lessThan) private
Definition at line 600 of file rc_thread_mac.cpp.
References _cond, rcMutex::_mutex, _mutex, _var, and rmDim.
Referenced by waitUntilGreaterThan(), and waitUntilLessThan().
 {
   int error;
   if (!_cond) {
     char errMsg[100];
     snprintf(errMsg, rmDim( errMsg ), "Invalid condition variable");
     throw general_exception( errMsg );
   }
   rcLock lock(_mutex);
   while ((lessThan && (_var >= goal)) || (!lessThan && (_var <= goal))) {
     if ((error = pthread_cond_wait((pthread_cond_t *)_cond,
                    (pthread_mutex_t *)(_mutex._mutex)))) {
       char errMsg[100];
       snprintf(errMsg, rmDim(errMsg), "condition variable signal failed %d", error);
       throw general_exception(errMsg);
     }
   }
   /* Why bother with retVal? Playing it safe. Not clear if unlock of
    * mutex occurs before or after return value is calculated.
    */
   int32 retVal = _var;
   return retVal;
 }
int32 rcConditionVariable::waitUntilGreaterThan (int32 goal)
Definition at line 560 of file rc_thread_mac.cpp.
References waitFct().
Referenced by rcEngineMovieSaver::saveHdlr().
 {
   return waitFct(goal, false);
 }
int32 rcConditionVariable::waitUntilLessThan (int32 goal)
Definition at line 555 of file rc_thread_mac.cpp.
References waitFct().
Referenced by rcEngineMovieCapture::closeSaveFile().
 {
   return waitFct(goal, true);
 }
Member Data Documentation
void* rcConditionVariable::_cond private
Definition at line 220 of file rc_thread.h.
Referenced by mutateFct(), rcConditionVariable(), waitFct(), and ~rcConditionVariable().
rcMutex rcConditionVariable::_mutex private
Definition at line 219 of file rc_thread.h.
Referenced by mutateFct(), and waitFct().
int32 rcConditionVariable::_var private
Definition at line 221 of file rc_thread.h.
Referenced by mutateFct(), and waitFct().
The documentation for this class was generated from the following files:
include/util/rc_thread.h
src/util/code/rc_thread_mac.cpp