Visible: rcLabelRLE Class Reference
rcLabelRLE Class Reference
RLE with an associated runs and a lot less code !! Runs can have up to 31 bit length and an associated label.
#include <include/analysis/rc_labelRLE.h>
Classes
struct Run
Public Member Functions
rcLabelRLE (const rcWindow &)
~rcLabelRLE ()
Run * pointToRow (int32 y) const
int32 numRuns () const
pointToRow takes one arguments and returns Run*
template<class T >
rcLabelRLE::Run * image2runs (const rcWindow &img, T *pelPtr)
Private Member Functions
template<class T >
Run * image2runs (const rcWindow &, T *)
rcWindow image () const
void image (rcWindow &) const
Private Attributes
Run ** rat_
Run * alloc_
int32 numRuns_
Detailed Description
RLE with an associated runs and a lot less code !! Runs can have up to 31 bit length and an associated label.
Definition at line 21 of file rc_labelRLE.h.
Constructor & Destructor Documentation
rcLabelRLE::rcLabelRLE (const rcWindow & img)
Definition at line 14 of file rc_labelRLE.cpp.
References alloc_, rcWindow::depth(), rcWindow::height(), rcLabelRLE::Run::label, rcLabelRLE::Run::length, NULL, numRuns_, rcWindow::pelPointer(), rat_, rcPixel16, rcPixel32, rcPixel8, rfRLEstimate(), rmExceptionMacro, and rcLabelRLE::Run::value.
 {
   const int32 height(img.height());
   numRuns_ = rfRLEstimate (img);
   alloc_ = new Run[ numRuns_ + height ];
   rat_ = new Run *[ height];
   Run * runs = NULL;
   switch (img.depth ())
     {
     case rcPixel8:
       runs = image2runs<uint8> (img, (uint8 *) img.pelPointer (0,0));
       break;
     case rcPixel16:
       runs = image2runs<uint16> (img, (uint16 *) img.pelPointer (0,0));
       break;
     case rcPixel32:
       runs = image2runs<uint32> (img, (uint32 *) img.pelPointer (0,0));
       break;
     default:
       rmExceptionMacro(<< "rcWindow::notImplemented");
     }
   runs->value = 0;
   runs->label = 0;
   runs++->length = 0;
 }
rcLabelRLE::~rcLabelRLE ()
Definition at line 98 of file rc_labelRLE.cpp.
References alloc_, and rat_.
 {
   delete[] alloc_;
   delete[] rat_;
 }
Member Function Documentation
rcWindow rcLabelRLE::image () const private
void rcLabelRLE::image (rcWindow &) const private
template<class T > rcLabelRLE::Run* rcLabelRLE::image2runs (const rcWindow & img, T * pelPtr)
Definition at line 43 of file rc_labelRLE.cpp.
References alloc_, rcWindow::height(), rcLabelRLE::Run::label, numRuns(), rat_, rcWindow::rowPointer(), rcLabelRLE::Run::value, and rcWindow::width().
 {
   const int32 height(img.height());
   const int32 width(img.width());
   Run* runs = alloc_;
   int32 lastLength;
   uint32 lastValue;
   int32 runsleft = numRuns ();
   for (int y = 0 ; y < height; y++)
   {
     const T *pels = (T *) img.rowPointer(y);
     rat_[y] = runs;
     int32 w = width;
     const T *runStart = pels; //@note pointer size
     lastValue = pels[0];
     while(w--)
     {
       if(*pels != lastValue)
       {
     lastLength = pels - runStart;
     if (lastLength > 0)
       {
         runs->label = 0;
         runs->value = lastValue;
         runs++->length = lastLength;
       }
     lastValue = *pels;
     runStart = pels;
       }
       ++pels;
     }
     lastLength = pels - runStart;
     if (lastLength > 0)
       {
     runs->label = 0;
     runs->value = lastValue;
     runs++->length = lastLength;
       }
     const int32 runsUsed = runs - rat_[y];
     runsleft -= runsUsed;
     // make EOR marker
     runs->value = 0;
     runs->length = 0;
     ++runs;
   }
   return runs;
 }
template<class T > Run* rcLabelRLE::image2runs (const rcWindow & , T *) private
int32 rcLabelRLE::numRuns () const inline
pointToRow takes one arguments and returns Run*
Parameters
y is row coordinate
Returns
Run*
Definition at line 50 of file rc_labelRLE.h.
References numRuns_.
Referenced by image2runs().
 {return numRuns_;}
Run* rcLabelRLE::pointToRow (int32 y) const inline
Definition at line 32 of file rc_labelRLE.h.
References rat_.
 {return rat_[y];}
Member Data Documentation
Run* rcLabelRLE::alloc_ private
Definition at line 59 of file rc_labelRLE.h.
Referenced by image2runs(), rcLabelRLE(), and ~rcLabelRLE().
int32 rcLabelRLE::numRuns_ private
Definition at line 60 of file rc_labelRLE.h.
Referenced by numRuns(), and rcLabelRLE().
Run** rcLabelRLE::rat_ private
Definition at line 58 of file rc_labelRLE.h.
Referenced by image2runs(), pointToRow(), rcLabelRLE(), and ~rcLabelRLE().
The documentation for this class was generated from the following files:
include/analysis/rc_labelRLE.h
src/analysis/code/rc_labelRLE.cpp