Visible: rcFrame Class Reference
rcFrame Class Reference
#include <include/visual/rc_framebuf.h>
Public Types
enum { ROW_ALIGNMENT_MODULUS = 16 }
Public Member Functions
rcFrame ()
rcFrame (int32 width, int32 height, rcPixel depth, int32 alignMod=ROW_ALIGNMENT_MODULUS)
rcFrame (char *rawPixels, int32 rawPixelsRowUpdate, int32 width, int32 height, rcPixel pixelDepth, bool isGray)
virtual ~rcFrame ()
const uint8 * rawData () const
uint8 * rawData ()
const uint8 * alignedRawData () const
uint8 * alignedRawData ()
const uint8 * rowPointer (int32 y) const
uint8 * rowPointer (int32 y)
const uint8 * pelPointer (int32 x, int32 y) const
uint8 * pelPointer (int32 x, int32 y)
const uint32 * colorMap () const
uint32 colorMapSize () const
void setColor (uint32 index, uint32 value)
uint32 getColor (uint32 index) const
void initGrayColorMap ()
int32 rowUpdate () const
int32 rowPixelUpdate () const
int32 rowPad () const
int32 width () const
int32 height () const
rcPixel depth () const
uint32 pixelCount () const
bool isGray () const
bool isD32Float () const
int32 alignment () const
uint32 getPixel (int32 x, int32 y) const
double getDoublePixel (int32 x, int32 y) const
rcTimestamp timestamp () const
double zVal () const
int32 bits () const
int32 bytes () const
double operator() (double, double) const
uint32 setPixel (int32 x, int32 y, uint32 value)
double setDoublePixel (int32 x, int32 y, double value)
bool setIsGray (bool isGray)
bool markD32Float (bool m)
void setTimestamp (rcTimestamp time)
void zVal (double dv)
void loadImage (char *rawPixels, int32 rawPixelsRowUpdate, int32 width, int32 height, rcPixel pixelDepth, bool isGray)
uint32 cacheCtrl () const
uint32 frameIndex () const
void addRef () const
void remRef () const
int refCount () const
Protected Member Functions
void cacheCtrl (uint32 cacheCtrl)
void frameIndex (uint32 frameIndex)
Protected Attributes
uint8 * mRawData
uint8 * mStartPtr
int32 mWidth
int32 mHeight
int32 mPad
int32 mAlignMod
rcPixel mPixelDepth
int32 mRowUpdate
rcTimestamp mTimestamp
uint32 * mColorMap
uint32 mColorMapSize
bool mIsGray
bool mOwnPixels
uint32 mCacheCtrl
uint32 mFrameIndex
bool mD32IsFloat
double mZvalue
Private Member Functions
rcFrame (const rcFrame &)
rcFrame & operator= (const rcFrame &)
Private Attributes
boost::atomic< int > refcount_
Friends
class rcVideoCache
void intrusive_ptr_add_ref (const rcFrame *x)
void intrusive_ptr_release (const rcFrame *x)
Detailed Description
Definition at line 61 of file rc_framebuf.h.
Member Enumeration Documentation
anonymous enum
Enumerator
ROW_ALIGNMENT_MODULUS
Definition at line 66 of file rc_framebuf.h.
 { ROW_ALIGNMENT_MODULUS = 16 }; // Mod for row alignment. Default for AltiVec
Constructor & Destructor Documentation
rcFrame::rcFrame ()
Definition at line 24 of file rc_framebuf.cpp.
                  :
     refcount_(0),
     mRawData( 0 ),
     mStartPtr( 0 ),
     mWidth( 0 ),
     mHeight( 0 ),
     mPad( 0 ),
     mAlignMod ( 0 ),
     mPixelDepth( rcPixelUnknown ),
     mRowUpdate( 0 ),
     mTimestamp( 0.0 ),
     mColorMap( 0 ),
     mColorMapSize( 0 ),
     mIsGray( 0 ),
     mOwnPixels (FALSE),
     mCacheCtrl( 0 ),
     mFrameIndex( 0 ),
     mD32IsFloat (false)
 {
}
rcFrame::rcFrame (int32 width, int32 height, rcPixel depth, int32 alignMod = ROW_ALIGNMENT_MODULUS)
Definition at line 45 of file rc_framebuf.cpp.
References mAlignMod, mHeight, mPad, mPixelDepth, mRawData, mRowUpdate, mStartPtr, mWidth, rcPixelUnknown, and rmAssert.
                                                                           :
     refcount_(0),
     mWidth( width ),
     mHeight( height ),
     mAlignMod ( alignMod),
     mPixelDepth( depth ),
     mTimestamp( 0.0 ),
     mColorMap( 0 ),
     mColorMapSize( 0 ),
     mIsGray( FALSE ),
     mOwnPixels (TRUE),
     mCacheCtrl( 0 ),
     mFrameIndex( 0 ),
     mD32IsFloat (false)
 {
     uint8 * startPtr;
     int32 n;
     rmAssert( depth != rcPixelUnknown );
     rmAssert( height > 0 );
     rmAssert( width > 0 );
     // Make sure starting addresses are at the correct alignment boundary
     // Start of each row pointer is mAlignMod aligned
     int32 rowBytes = mWidth * mPixelDepth;
     mPad = rowBytes % mAlignMod;
     int32 size;
     if (mPad) mPad = mAlignMod - mPad;
     // Total storage need
     mRowUpdate = rowBytes + mPad;
     size = mRowUpdate * mHeight + alignMod - 1;
     // Allocate raw data buffer
     mRawData = new uint8[size];
     // Find an Aligned Start Ptr
     startPtr = (uint8 *) mRawData;
     while ((uint32) startPtr % mAlignMod) startPtr ++;
     n = startPtr - (uint8 *) mRawData;
     assert ((n < mAlignMod) && (n >=0));
     // Now have to setup the row pointer logic
     mStartPtr = startPtr;
}
rcFrame::rcFrame (char * rawPixels, int32 rawPixelsRowUpdate, int32 width, int32 height, rcPixel pixelDepth, bool isGray)
Definition at line 94 of file rc_framebuf.cpp.
References mAlignMod, mHeight, mPad, mPixelDepth, mRawData, mRowUpdate, mStartPtr, mWidth, rcPixelUnknown, rmAssert, and rowPointer().
         : refcount_(0), mWidth( width ), mHeight( height ), mAlignMod (ROW_ALIGNMENT_MODULUS),
           mPixelDepth( pixelDepth ), mTimestamp( 0.0 ), mIsGray( isGray ), mOwnPixels (TRUE), mCacheCtrl( 0 ), mFrameIndex( 0 ),
     mD32IsFloat (false)
 {
     uint8 * startPtr;
     int32 n;
     rmAssert( pixelDepth != rcPixelUnknown );
     rmAssert( height > 0 );
     rmAssert( width > 0 );
     rmAssert( rawPixels );
     // Make sure starting addresses are at the correct alignment boundary
     // Start of each row pointer is mAlignMod aligned
     int32 rowBytes = mWidth * mPixelDepth;
     mPad = rowBytes % mAlignMod;
     if (mPad) mPad = mAlignMod - mPad;
     // Total storage need
     mRowUpdate = rowBytes + mPad;
     int32 size = mRowUpdate * mHeight + mAlignMod - 1;
     // Allocate raw data buffer
     mRawData = new uint8[size];
     // Find an Aligned Start Ptr
     startPtr = (uint8 *) mRawData;
     while ((uint32) startPtr % mAlignMod) startPtr ++;
     n = startPtr - (uint8 *) mRawData;
     assert ((n < mAlignMod) && (n >=0));
     // Now have to setup the row pointer logic
     mStartPtr = startPtr;
     // Now copy pixels into image
     for (int32 y = 0; y < mHeight; y++)
     {
       bcopy(rawPixels, rowPointer(y), mWidth);
       rawPixels += rawPixelsRowUpdate;
     }
 }
rcFrame::~rcFrame () virtual
Definition at line 169 of file rc_framebuf.cpp.
References mColorMap, mOwnPixels, mRawData, and TRUE.
 {
   if (mOwnPixels == TRUE)
     delete [] mRawData;
   delete [] mColorMap;
   mColorMap = 0;
 }
rcFrame::rcFrame (const rcFrame &) private
Member Function Documentation
void rcFrame::addRef () const inline
Definition at line 191 of file rc_framebuf.h.
References intrusive_ptr_add_ref.
Referenced by rcSharedFrameBufPtr::operator=(), rcSharedFrameBufPtr::rcSharedFrameBufPtr(), and rcSharedFrameBufPtr::setCachedFrame().
     {
         intrusive_ptr_add_ref (this);
     }
const uint8* rcFrame::alignedRawData () const inline
Definition at line 85 of file rc_framebuf.h.
References mStartPtr.
Referenced by rcImageCanvasGL::buildImageDlist().
 { return mStartPtr; }
uint8* rcFrame::alignedRawData () inline
Definition at line 86 of file rc_framebuf.h.
References mStartPtr.
 { return mStartPtr; }
int32 rcFrame::alignment () const inline
Definition at line 146 of file rc_framebuf.h.
References mAlignMod.
 { return mAlignMod; }
int32 rcFrame::bits (void) const inline
Definition at line 177 of file rc_framebuf.cpp.
References bytes().
 {
   return bytes() * 8;
 }
int32 rcFrame::bytes (void) const inline
Definition at line 182 of file rc_framebuf.cpp.
References mPixelDepth.
Referenced by bits().
 {
   return ((int32)mPixelDepth);
 }
uint32 rcFrame::cacheCtrl () const inline
Definition at line 186 of file rc_framebuf.h.
References mCacheCtrl.
Referenced by rcSharedFrameBufPtr::operator=(), rcSharedFrameBufPtr::operator==(), and rcSharedFrameBufPtr::rcSharedFrameBufPtr().
 { return mCacheCtrl; }
void rcFrame::cacheCtrl (uint32 cacheCtrl) inline protected
Definition at line 226 of file rc_framebuf.h.
References cacheCtrl(), and mCacheCtrl.
Referenced by cacheCtrl().
 { mCacheCtrl = cacheCtrl; }
const uint32* rcFrame::colorMap () const inline
Definition at line 113 of file rc_framebuf.h.
References mColorMap.
Referenced by rfFillColorMap(), and rfIsWhiteReversed().
 { return mColorMap; };
uint32 rcFrame::colorMapSize () const inline
Definition at line 115 of file rc_framebuf.h.
References mColorMapSize.
Referenced by rcImageCanvasGL::buildImageDlist(), copyImage(), rfFillColorMap(), rfIsWhiteReversed(), and rcImageCanvasGL::statusString().
 { return mColorMapSize; };
rcPixel rcFrame::depth () const inline
Definition at line 136 of file rc_framebuf.h.
References mPixelDepth.
Referenced by rcMovieConverter::clippedFrame(), rcKinetoscope::frame(), isD32Float(), markD32Float(), pelPointer(), rfCompareFrames(), rfCompareMovies(), and rcWindow::rowPointer().
 { return mPixelDepth; }
uint32 rcFrame::frameIndex () const inline
Definition at line 187 of file rc_framebuf.h.
References mFrameIndex.
Referenced by rcVideoCache::cacheInsert(), rcKinetoscope::connectedFunctions(), rcVideoCache::internalGetFrame(), rcSharedFrameBufPtr::operator=(), rcSharedFrameBufPtr::operator==(), and rcSharedFrameBufPtr::rcSharedFrameBufPtr().
 {return mFrameIndex; }
void rcFrame::frameIndex (uint32 frameIndex) inline protected
Definition at line 227 of file rc_framebuf.h.
References frameIndex(), and mFrameIndex.
Referenced by frameIndex().
 { mFrameIndex=frameIndex; }
uint32 rcFrame::getColor (uint32 index) const
Definition at line 246 of file rc_framebuf.cpp.
References mColorMap, mColorMapSize, and rmAssert.
Referenced by rcImageCanvasGL::buildImageDlist(), copyImage(), rfFillColorMap(), rfImageConvert8to32(), rfIsWhiteReversed(), rfRcWindow8to32(), and rcImageCanvasGL::statusString().
 {
     rmAssert( index < mColorMapSize );
     if ( mColorMap )
         return mColorMap[ index ];
     else
         return 0;
 }
double rcFrame::getDoublePixel (int32 x, int32 y) const
Definition at line 276 of file rc_framebuf.cpp.
References mHeight, mPixelDepth, mRowUpdate, mStartPtr, mWidth, rcPixelDouble, rmAssert, and rmAssertDebug.
Referenced by rcWindow::getDoublePixel(), and operator()().
 {
    double val;
    rmAssert (mPixelDepth == rcPixelDouble);
    rmAssertDebug (y >= 0);
    rmAssertDebug (y < mHeight);
    rmAssertDebug (x >= 0);
    rmAssertDebug (x < mWidth);
    val = *((double *) (mStartPtr + y * mRowUpdate + x * mPixelDepth));
    return val;
 }
uint32 rcFrame::getPixel (int32 x, int32 y) const
Definition at line 188 of file rc_framebuf.cpp.
References mHeight, mPixelDepth, mRowUpdate, mStartPtr, mWidth, rcPixel16, rcPixel32, rcPixel8, and rmAssertDebug.
Referenced by rcWindow::getPixel(), operator()(), and rfCompareFrames().
 {
         uint32 val;
         rmAssertDebug (y >= 0);
         rmAssertDebug (y < mHeight);
         rmAssertDebug (x >= 0);
         rmAssertDebug (x < mWidth);
         switch (mPixelDepth)
         {
        case rcPixel8:
            val = *((uint8 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth));
            return val;
        case rcPixel16:
            val = *((uint16 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth));
            return val;
        case rcPixel32:
           val = *((uint32 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth));
            return val;
         default:
            assert (1);
     }
         return 0;
 }
int32 rcFrame::height () const inline
Definition at line 134 of file rc_framebuf.h.
References mHeight.
Referenced by rcWindow::canTrim(), rcMovieConverterToQT::copyFrame(), rcWindow::entire(), rcKinetoscope::frame(), rcWindow::init(), rcEngineImpl::loadFrames(), main(), rfCompareFrames(), rcWindow::translate(), and rcWindow::trim().
 { return mHeight; }
void rcFrame::initGrayColorMap ()
Definition at line 266 of file rc_framebuf.cpp.
References mColorMap, mColorMapSize, and rfRgb.
Referenced by rcQVideoGrabber::getNextFrame(), rcEngineMovieCapture::initializeCamera(), rfReversePixels16(), and rfReversePixels8().
 {
     const double incr = 256.0/mColorMapSize;
     for (uint32 i = 0; i < mColorMapSize; ++i) {
         const uint32 c = uint32(i*incr);
         mColorMap[i] = rfRgb(c, c, c);
     }
 }
bool rcFrame::isD32Float () const inline
Definition at line 142 of file rc_framebuf.h.
References depth(), mD32IsFloat, and rcPixel32.
Referenced by rcRowFuncTwoSource< T >::checkAssigned(), markD32Float(), operator()(), and rfImageACfield().
                                  { return (mD32IsFloat &&
                          depth() == rcPixel32); }
bool rcFrame::isGray () const inline
Definition at line 140 of file rc_framebuf.h.
References mIsGray.
Referenced by loadImage(), rfIsWhiteReversed(), and setIsGray().
 { return mIsGray; }
void rcFrame::loadImage (char * rawPixels, int32 rawPixelsRowUpdate, int32 width, int32 height, rcPixel pixelDepth, bool isGray)
Definition at line 142 of file rc_framebuf.cpp.
References isGray(), mHeight, mIsGray, mPad, mPixelDepth, mStartPtr, mWidth, rmAssert, and rowPointer().
Referenced by rcQVideoGrabber::getNextFrame().
 {
   rmAssert(rawPixels);
   rmAssert(mWidth == width);
   rmAssert(mHeight == height);
   rmAssert(mPixelDepth == pixelDepth);
   int32 bytesInRow = mWidth * mPixelDepth;
   if ((mPad == 0) && (rawPixelsRowUpdate == bytesInRow)) {
       int32 bytesInImage = bytesInRow * mHeight;
       bcopy(rawPixels, mStartPtr, bytesInImage);
   }
   else {
       for (int32 y = 0; y < mHeight; ++y)
       {
           bcopy(rawPixels, rowPointer(y), mWidth);
           rawPixels += rawPixelsRowUpdate;
       }
   }
   mIsGray = isGray;
 }
bool rcFrame::markD32Float (bool m) inline
Definition at line 171 of file rc_framebuf.h.
References depth(), isD32Float(), mD32IsFloat, and rcPixel32.
Referenced by rfImageACfield().
   {
     if (depth() == rcPixel32)
       mD32IsFloat = m;
     return isD32Float();
   }
double rcFrame::operator() (double xDb, double yDb) const
Definition at line 304 of file rc_framebuf.cpp.
References getDoublePixel(), getPixel(), isD32Float(), mPixelDepth, mRowUpdate, mStartPtr, rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, and rmAssert.
 {
   int32 x = (int32) xDb;
   int32 y = (int32) yDb;
   switch (mPixelDepth)
     {
     case rcPixel8:
     case rcPixel16:
       return (double) getPixel (x, y);
     case rcPixel32:
       if (isD32Float())
     return (double) (*((float *) (mStartPtr + y * mRowUpdate + x * mPixelDepth)));
       else
     return (double) (*((uint32 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth)));
     case rcPixelDouble:
       return (double) getDoublePixel (x, y);
     default:
       rmAssert (0);
     }
   rmAssert (0);
 }
rcFrame& rcFrame::operator= (const rcFrame &) private
const uint8* rcFrame::pelPointer (int32 x, int32 y) const inline
Definition at line 100 of file rc_framebuf.h.
References depth(), mHeight, mRowUpdate, mStartPtr, mWidth, and rmAssertDebug.
Referenced by rcWindow::pelPointer().
{
     rmAssertDebug (y >= 0 && y < mHeight);
     rmAssertDebug (x >= 0 && x < mWidth);
     return (mStartPtr + y * mRowUpdate + x * depth());
   }
uint8* rcFrame::pelPointer (int32 x, int32 y) inline
Definition at line 106 of file rc_framebuf.h.
References depth(), mHeight, mRowUpdate, mStartPtr, mWidth, and rmAssertDebug.
{
     rmAssertDebug (y >= 0 && y < mHeight);
     rmAssertDebug (x >= 0 && x < mWidth);
     return (mStartPtr + y * mRowUpdate + x * depth());
   }
uint32 rcFrame::pixelCount () const inline
Definition at line 138 of file rc_framebuf.h.
References mHeight, and mWidth.
 { return mWidth * mHeight; }
const uint8* rcFrame::rawData () const inline
Definition at line 82 of file rc_framebuf.h.
References mRawData.
 { return mRawData; }
uint8* rcFrame::rawData () inline
Definition at line 83 of file rc_framebuf.h.
References mRawData.
 { return mRawData; }
int rcFrame::refCount () const inline
Definition at line 203 of file rc_framebuf.h.
References refcount_.
Referenced by rcVideoCache::cacheAlloc(), rcVideoCache::internalGetFrame(), rcSharedFrameBufPtr::internalLock(), rcSharedFrameBufPtr::internalUnlock(), rcSharedFrameBufPtr::operator=(), rcSharedFrameBufPtr::rcSharedFrameBufPtr(), rcSharedFrameBufPtr::refCount(), and rcVideoCache::unlockFrame().
 { return refcount_.load (); }
void rcFrame::remRef () const inline
Definition at line 198 of file rc_framebuf.h.
References intrusive_ptr_release.
Referenced by rcSharedFrameBufPtr::internalUnlock().
     {
         intrusive_ptr_release (this);
     }
int32 rcFrame::rowPad () const inline
Definition at line 130 of file rc_framebuf.h.
References mPad.
 { return mPad; };
int32 rcFrame::rowPixelUpdate () const inline
Definition at line 127 of file rc_framebuf.h.
References mPixelDepth, and mRowUpdate.
 { return mRowUpdate / ((int32) mPixelDepth) ; };
const uint8* rcFrame::rowPointer (int32 y) const inline
Definition at line 89 of file rc_framebuf.h.
References mHeight, mRowUpdate, mStartPtr, and rmAssertDebug.
Referenced by rcMovieConverterToQT::copyFrame(), loadImage(), rcFrame(), rcWindow::rowPointer(), and yourDisplayCallback().
{
     rmAssertDebug (y >= 0 && y < mHeight);
     return (mStartPtr + y * mRowUpdate);
   }
uint8* rcFrame::rowPointer (int32 y) inline
Definition at line 94 of file rc_framebuf.h.
References mHeight, mRowUpdate, mStartPtr, and rmAssertDebug.
{
     rmAssertDebug (y >= 0 && y < mHeight);
     return (mStartPtr + y * mRowUpdate);
   }
int32 rcFrame::rowUpdate () const inline
Definition at line 124 of file rc_framebuf.h.
References mRowUpdate.
Referenced by yourDisplayCallback().
 { return mRowUpdate; };
void rcFrame::setColor (uint32 index, uint32 value)
Definition at line 257 of file rc_framebuf.cpp.
References mColorMap, mColorMapSize, and rmAssert.
Referenced by copyImage(), and rfFillColorMap().
 {
     rmAssert( index < mColorMapSize );
     if ( mColorMap )
         mColorMap[ index ] = value;
 }
double rcFrame::setDoublePixel (int32 x, int32 y, double value)
Definition at line 291 of file rc_framebuf.cpp.
References mHeight, mPixelDepth, mRowUpdate, mStartPtr, mWidth, rcDBL_MAX, rcPixelDouble, rmAssert, and rmAssertDebug.
Referenced by rcWindow::setDoublePixel().
 {
    rmAssert (mPixelDepth == rcPixelDouble && val <= rcDBL_MAX);
    rmAssertDebug (y >= 0);
    rmAssertDebug (y < mHeight);
    rmAssertDebug (x >= 0);
    rmAssertDebug (x < mWidth);
    *((double *) (mStartPtr + y * mRowUpdate + x * mPixelDepth)) = val;
    return val;
 }
bool rcFrame::setIsGray (bool isGray) inline
Definition at line 168 of file rc_framebuf.h.
References isGray(), and mIsGray.
Referenced by copyImage(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), and rfImageFileToRcWindow().
 { return mIsGray = isGray; }
uint32 rcFrame::setPixel (int32 x, int32 y, uint32 value)
Definition at line 218 of file rc_framebuf.cpp.
References mHeight, mPixelDepth, mRowUpdate, mStartPtr, mWidth, rcPixel16, rcPixel32, rcPixel8, and rmAssertDebug.
Referenced by rcWindow::setPixel().
 {
     rmAssertDebug (y >= 0);
     rmAssertDebug (y < mHeight);
     rmAssertDebug (x >= 0);
     rmAssertDebug (x < mWidth);
     switch (mPixelDepth)
       {
       case rcPixel8:
     * ((uint8 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth)) = (uint8) val;
     break;
       case rcPixel16:
     *((uint16 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth)) = (uint16) val;
     break;
       case rcPixel32:
     *((uint32 *) (mStartPtr + y * mRowUpdate + x * mPixelDepth)) = val;
     break;
       default:
     assert (1);
       }
     return val;
 }
void rcFrame::setTimestamp (rcTimestamp time) inline
Definition at line 179 of file rc_framebuf.h.
References mTimestamp.
Referenced by rcMovieConverter::clippedFrame(), rcImageGrabber::getNextFrame(), rcMovieGrabber::getNextFrame(), rcQVideoGrabber::getNextFrame(), rcEngineImpl::ipp(), and main().
 { mTimestamp = time; }
rcTimestamp rcFrame::timestamp () const inline
Definition at line 152 of file rc_framebuf.h.
References mTimestamp.
Referenced by rcGenMovieFile::addFrame(), rcEngineImpl::analyzeFocusArea(), rcWindow::atTime(), rcMovieConverter::clippedFrame(), rcMovieConverterToRfy::createRfyMovie(), rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::frameInterrupt(), rcEngineImpl::muscleTracker(), rcEngineImpl::processCapturedData(), rcKinetoscope::resultTime(), rcEngineMoviePlayback::run(), and rcWindow::sameTime().
 { return mTimestamp; };
int32 rcFrame::width () const inline
Definition at line 132 of file rc_framebuf.h.
References mWidth.
Referenced by rcWindow::canTrim(), rcMovieConverterToQT::copyFrame(), rcWindow::entire(), rcKinetoscope::frame(), rcWindow::init(), rcEngineImpl::loadFrames(), main(), rfCompareFrames(), rcWindow::translate(), and rcWindow::trim().
 { return mWidth; }
double rcFrame::zVal () const inline
Definition at line 154 of file rc_framebuf.h.
References mZvalue.
 { return mZvalue; };
void rcFrame::zVal (double dv) inline
Definition at line 180 of file rc_framebuf.h.
References mZvalue.
 { mZvalue = dv; }
Friends And Related Function Documentation
void intrusive_ptr_add_ref (const rcFrame * x) friend
Definition at line 231 of file rc_framebuf.h.
Referenced by addRef().
     {
         x->refcount_.fetch_add(1, boost::memory_order_relaxed);
     }
void intrusive_ptr_release (const rcFrame * x) friend
Definition at line 235 of file rc_framebuf.h.
Referenced by remRef().
     {
         if (x->refcount_.fetch_sub(1, boost::memory_order_release)==1)
         {
             boost::atomic_thread_fence(boost::memory_order_acquire);
             delete x;
         }
     }
friend class rcVideoCache friend
Definition at line 63 of file rc_framebuf.h.
Member Data Documentation
int32 rcFrame::mAlignMod protected
Definition at line 212 of file rc_framebuf.h.
Referenced by alignment(), and rcFrame().
uint32 rcFrame::mCacheCtrl protected
Definition at line 220 of file rc_framebuf.h.
Referenced by rcVideoCache::cacheAlloc(), and cacheCtrl().
uint32* rcFrame::mColorMap protected
Definition at line 216 of file rc_framebuf.h.
Referenced by colorMap(), getColor(), initGrayColorMap(), setColor(), and ~rcFrame().
uint32 rcFrame::mColorMapSize protected
Definition at line 217 of file rc_framebuf.h.
Referenced by colorMapSize(), getColor(), initGrayColorMap(), and setColor().
bool rcFrame::mD32IsFloat protected
Definition at line 222 of file rc_framebuf.h.
Referenced by isD32Float(), and markD32Float().
uint32 rcFrame::mFrameIndex protected
Definition at line 221 of file rc_framebuf.h.
Referenced by frameIndex().
int32 rcFrame::mHeight protected
Definition at line 210 of file rc_framebuf.h.
Referenced by getDoublePixel(), getPixel(), height(), loadImage(), pelPointer(), pixelCount(), rcFrame(), rowPointer(), setDoublePixel(), and setPixel().
bool rcFrame::mIsGray protected
Definition at line 218 of file rc_framebuf.h.
Referenced by isGray(), loadImage(), and setIsGray().
bool rcFrame::mOwnPixels protected
Definition at line 219 of file rc_framebuf.h.
Referenced by ~rcFrame().
int32 rcFrame::mPad protected
Definition at line 211 of file rc_framebuf.h.
Referenced by loadImage(), rcFrame(), and rowPad().
rcPixel rcFrame::mPixelDepth protected
Definition at line 213 of file rc_framebuf.h.
Referenced by bytes(), depth(), getDoublePixel(), getPixel(), loadImage(), operator()(), rcFrame(), rowPixelUpdate(), setDoublePixel(), and setPixel().
uint8* rcFrame::mRawData protected
Definition at line 207 of file rc_framebuf.h.
Referenced by rawData(), rcFrame(), and ~rcFrame().
int32 rcFrame::mRowUpdate protected
Definition at line 214 of file rc_framebuf.h.
Referenced by getDoublePixel(), getPixel(), operator()(), pelPointer(), rcFrame(), rowPixelUpdate(), rowPointer(), rowUpdate(), setDoublePixel(), and setPixel().
uint8* rcFrame::mStartPtr protected
Definition at line 208 of file rc_framebuf.h.
Referenced by alignedRawData(), getDoublePixel(), getPixel(), loadImage(), operator()(), pelPointer(), rcFrame(), rowPointer(), setDoublePixel(), and setPixel().
rcTimestamp rcFrame::mTimestamp protected
Definition at line 215 of file rc_framebuf.h.
Referenced by setTimestamp(), and timestamp().
int32 rcFrame::mWidth protected
Definition at line 209 of file rc_framebuf.h.
Referenced by getDoublePixel(), getPixel(), loadImage(), pelPointer(), pixelCount(), rcFrame(), setDoublePixel(), setPixel(), and width().
double rcFrame::mZvalue protected
Definition at line 223 of file rc_framebuf.h.
Referenced by zVal().
boost::atomic<int> rcFrame::refcount_ mutable private
Definition at line 230 of file rc_framebuf.h.
Referenced by refCount().
The documentation for this class was generated from the following files:
include/visual/rc_framebuf.h
src/visual/code/rc_framebuf.cpp