Visible: ifbuff Class Reference
ifbuff Class Reference
#include <include/stlplus/fileio.hpp>
Public Member Functions
ifbuff (FILE *)
ifbuff (const char *, size_t bufsize=iftext::preferred_buffer)
ifbuff (const std::string &, size_t bufsize=iftext::preferred_buffer)
virtual ~ifbuff (void)
void open (const std::string &filename, size_t bufsize)
virtual int peek (void)
virtual int get (void)
virtual std::string error_string (void) const
Public Member Functions inherited from ibuff
ibuff (itext::newline_t newline=itext::convert_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_newline_mode (itext::newline_t newline)
itext::newline_t newline_mode (void) const
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual ~ibuff (void)
Private Member Functions
ifbuff (const ifbuff &)
ifbuff & operator= (const ifbuff &)
Private Attributes
bool m_managed
FILE * m_handle
Friends
class iftext
Additional Inherited Members
Protected Attributes inherited from ibuff
itext::newline_t m_newline_mode
unsigned long m_bytes
unsigned m_line
unsigned m_column
int m_error_number
int m_aliases
Detailed Description
Definition at line 125 of file fileio.hpp.
Constructor & Destructor Documentation
ifbuff::ifbuff (FILE * fp)
Definition at line 160 of file fileio.cpp.
                         :
   m_managed(false),
   m_handle(fp)
 {
 }
ifbuff::ifbuff (const char * fname, size_t bufsize = iftext::preferred_buffer)
Definition at line 166 of file fileio.cpp.
References open().
                                                  :
   m_managed(false),
   m_handle(0)
 {
   open(std::string(fname ? fname : ""), bufsize);
 }
ifbuff::ifbuff (const std::string & fname, size_t bufsize = iftext::preferred_buffer)
Definition at line 173 of file fileio.cpp.
References open().
                                                       :
   m_managed(false),
   m_handle(0)
 {
   open(fname, bufsize);
 }
ifbuff::~ifbuff (void) virtual
Definition at line 180 of file fileio.cpp.
References m_handle, and m_managed.
 {
   if (m_managed && m_handle)
     fclose(m_handle);
 }
ifbuff::ifbuff (const ifbuff &) private
Member Function Documentation
std::string ifbuff::error_string (void) const virtual
Reimplemented from ibuff.
Definition at line 246 of file fileio.cpp.
References ibuff::error_number(), and ibuff::error_string().
 {
   // if the number is positiove, it is an errno, otherwise it is a built-in and can be handled by the baseclass
   if (error_number() > 0)
     return std::string(strerror(error_number()));
   else
     return ibuff::error_string();
 }
int ifbuff::get (void) virtual
Implements ibuff.
Definition at line 231 of file fileio.cpp.
References m_handle, and ibuff::set_error().
 {
   if (!m_handle) return -1;
   int ch = getc(m_handle);
   if (ch == EOF)
   {
     // may be a stdio error or the user may be trying to read past the last valid character
     // in the latter case it is not actually an error - it is perfectly legal to read the EOF
     int error = ferror(m_handle);
     if (error)
       set_error(error);
   }
   return ch;
 }
void ifbuff::open (const std::string & filename, size_t bufsize)
Definition at line 188 of file fileio.cpp.
References m_handle, m_managed, ibuff::set_error(), and textio_open_failed.
Referenced by ifbuff().
 {
   if (fname.empty())
   {
     // an empty filename is an error without even trying to open the file
     // on Windows fopen raises an assertion failure in this case which is unacceptable so I trap it first
     set_error(textio_open_failed);
   }
   else
   {
     m_managed = true;
     m_handle = fopen(fname.c_str(), "rb");
     if (!m_handle)
     {
       if (errno)
         set_error(errno);
       else
         set_error(textio_open_failed);
     }
     else if (setvbuf(m_handle, 0, (bufsize ? _IOFBF : _IONBF), bufsize) != 0)
     {
       int error = ferror(m_handle);
       if (error)
         set_error(error);
       else
         set_error(textio_open_failed);
     }
   }
 }
ifbuff& ifbuff::operator= (const ifbuff &) private
int ifbuff::peek (void) virtual
Implements ibuff.
Definition at line 218 of file fileio.cpp.
References m_handle, and ibuff::set_error().
 {
   if (!m_handle) return -1;
   int ch = getc(m_handle);
   if (ch != EOF && ungetc(ch,m_handle) == EOF)
   {
     int error = ferror(m_handle);
     if (error)
       set_error(error);
   }
   return ch;
 }
Friends And Related Function Documentation
friend class iftext friend
Definition at line 127 of file fileio.hpp.
Member Data Documentation
FILE* ifbuff::m_handle private
Definition at line 141 of file fileio.hpp.
Referenced by get(), open(), iftext::operator FILE *(), peek(), and ~ifbuff().
bool ifbuff::m_managed private
Definition at line 140 of file fileio.hpp.
Referenced by open(), and ~ifbuff().
The documentation for this class was generated from the following files:
include/stlplus/fileio.hpp
include/stlplus/fileio.cpp