Visible: rcExperimentDomainImpl Class Reference
rcExperimentDomainImpl Class Reference
#include <include/visiCore/rc_experimentdomainimpl.h>
Public Member Functions
rcExperimentDomainImpl (void)
virtual void initialize (rcExperimentObserver *observer)
virtual void shutdown (void)
virtual rcExperiment * getExperiment (void)
virtual void newExperiment (void)
virtual int loadExperiment (const char *fileName, const rcXMLElementTree &tree, rcExperimentImportMode mode, rcProgressIndicator *progress=NULL)
virtual int saveExperiment (const char *fileName, rcExperimentFileFormat format, rcProgressIndicator *progress=NULL)
virtual rcExperimentState getExperimentState (void)
virtual const
rcExperimentAttributes getExperimentAttributes (void)
virtual bool operatingOnLiveInput (void)
virtual bool storingLiveInput (void)
virtual void setExperimentAttributes (const rcExperimentAttributes &attr)
virtual rcTimestamp getExperimentLength (void)
virtual rcTimestamp getCursorTime (void)
virtual void notifyCursorTime (const rcTimestamp &time)
virtual void notifyMovieImport ()
virtual rcTimestamp getExperimentStart (void)
virtual void startExperiment (void)
virtual void stopExperiment (void)
virtual void processExperiment (void)
virtual bool pauseTrackingExperiment (void)
virtual bool doneSelecting (void)
virtual rcWriterGroup * createWriterGroup (const char *tag, const char *name, const char *description, rcGroupSemantics type)
virtual void notifyError (const char *errorString)
virtual void notifyWarning (const char *warnString)
virtual void notifyStatus (const char *statusString)
virtual void notifyState (rcEngineState newState)
virtual void notifyTime (const rcTimestamp &timestamp)
virtual int32 timeEventCount () const
virtual void notifyTimelineRange (const rcTimestamp &start, const rcTimestamp &end)
virtual void notifyAnalysisRect (const rcRect &rect)
virtual void notifyAnalysisRectRotation (const rcAffineRectangle &affine)
virtual void notifyMultiplier (const double &multiplier)
virtual bool acceptingImageBlits (void)
virtual void notifyBlitData (const rcWindow *image)
virtual void notifyBlitGraphics (const rcVisualGraphicsCollection *graphics)
virtual void notifyLockApp (bool lock)
virtual int notifyRequestSave (const char *fileName, rcExperimentFileFormat format)
virtual void notifyVideoRect (const rcRect &rect)
virtual void notifyExperimentChange (void)
virtual bool acceptingPolys (void)
virtual void notifyPolys (const rcPolygonGroupRef *polys)
virtual void getPolys (rcPolygonGroupRef &polys)
virtual void lock ()
virtual void unlock ()
Public Member Functions inherited from rcExperimentDomain
virtual ~rcExperimentDomain ()
Public Member Functions inherited from rcEngineObserver
virtual ~rcEngineObserver ()
Public Member Functions inherited from rcCarbonLock
virtual ~rcCarbonLock ()
Private Member Functions
void setInternalState (rcExperimentState newState)
Private Attributes
rcEngine * _engine
rcExperimentObserver * _observer
rcExperimentImpl * _experiment
rcExperimentState _state
rcTimestamp _length
rcAtomicValue< rcTimestamp > _cursorTime
rcTimestamp _start
Detailed Description
Definition at line 19 of file rc_experimentdomainimpl.h.
Constructor & Destructor Documentation
rcExperimentDomainImpl::rcExperimentDomainImpl (void)
Definition at line 14 of file rc_experimentdomainimpl.cpp.
References _engine, _experiment, _length, _observer, _state, cZeroTime, and eExperimentEmpty.
   : _cursorTime(0.0)
 {
     _observer = 0;
     _experiment = 0;
     _engine = 0;
     _state = eExperimentEmpty;
     _length = cZeroTime;
 }
Member Function Documentation
bool rcExperimentDomainImpl::acceptingImageBlits (void) virtual
Implements rcEngineObserver.
Definition at line 428 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::acceptingImageBlits().
 {
     return _observer->acceptingImageBlits();
 }
bool rcExperimentDomainImpl::acceptingPolys (void) virtual
Implements rcEngineObserver.
Definition at line 435 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::acceptingPolys().
 {
   return _observer->acceptingPolys ();
 }
rcWriterGroup * rcExperimentDomainImpl::createWriterGroup (const char * tag, const char * name, const char * description, rcGroupSemantics type) virtual
Implements rcEngineObserver.
Definition at line 303 of file rc_experimentdomainimpl.cpp.
References _experiment, and rcExperimentImpl::createTrackGroup().
 {
     rcTrackGroupImpl* trackGroup = _experiment->createTrackGroup( tag , name , description, type );
     rcWriterGroup* writerGroup = dynamic_cast<rcWriterGroup*>( trackGroup );
     return writerGroup;
 }
bool rcExperimentDomainImpl::doneSelecting (void) virtual
Implements rcExperimentDomain.
Definition at line 291 of file rc_experimentdomainimpl.cpp.
References _engine, _state, eExperimentLocked, rcEngine::resumeTracking(), and rmExceptionMacro.
 {
     if (_state == eExperimentLocked)
       rmExceptionMacro (<< "Experiment is locked");
     return _engine->resumeTracking ();
 }
rcTimestamp rcExperimentDomainImpl::getCursorTime (void) virtual
Implements rcEngineObserver.
Definition at line 213 of file rc_experimentdomainimpl.cpp.
References _cursorTime, and rcAtomicValue< T >::getValue().
 {
   rcTimestamp x;
   return _cursorTime.getValue(x);
 }
rcExperiment * rcExperimentDomainImpl::getExperiment (void) virtual
Implements rcExperimentDomain.
Definition at line 44 of file rc_experimentdomainimpl.cpp.
References _experiment.
 {
     return _experiment;
 }
const rcExperimentAttributes rcExperimentDomainImpl::getExperimentAttributes (void) virtual
Implements rcEngineObserver.
Definition at line 160 of file rc_experimentdomainimpl.cpp.
References _engine, _experiment, cCellCO2SettingId, cCellO2SettingId, cCellTemperatureSettingId, cCellTreatment2SettingId, cCellTreatmentSettingId, cCellTypeSettingId, cCommentsSettingId, rcExperimentAttributes::cellType, cFileNameSettingId, cImagingModeSettingId, cMicroscopeMagnificationSettingId, rcExperimentAttributes::CO2, rcExperimentAttributes::comments, cOtherMagnificationSettingId, cTitleSettingId, cUserNameSettingId, rcExperimentAttributes::fileName, rcExperimentAttributes::frameDepth, rcEngineAttributes::frameDepth, rcExperimentAttributes::frameHeight, rcEngineAttributes::frameHeight, rcExperimentAttributes::frameWidth, rcEngineAttributes::frameWidth, rcEngine::getAttributes(), rcExperimentImpl::getSettingValue(), rcExperimentAttributes::imagingMode, rcExperimentAttributes::inputName, rcEngineAttributes::inputName, rcExperimentAttributes::lensMag, rcExperimentAttributes::liveInput, rcEngineAttributes::liveInput, rcExperimentAttributes::liveStorage, rcEngineAttributes::liveStorage, rcExperimentAttributes::O2, rcExperimentAttributes::otherMag, rcExperimentAttributes::temperature, rcExperimentAttributes::title, rcExperimentAttributes::treatment1, rcExperimentAttributes::treatment2, and rcExperimentAttributes::userName.
 {
     rcExperimentAttributes attrs;
     rcEngineAttributes engineAttrs = _engine->getAttributes();
     attrs.frameWidth    = engineAttrs.frameWidth;
     attrs.frameHeight   = engineAttrs.frameHeight;
     attrs.frameDepth    = engineAttrs.frameDepth;
     attrs.liveInput     = engineAttrs.liveInput;
     attrs.liveStorage   = engineAttrs.liveStorage;
     attrs.inputName     = engineAttrs.inputName;
     attrs.title         = (std::string) _experiment->getSettingValue(cTitleSettingId);
     attrs.fileName      = (std::string) _experiment->getSettingValue(cFileNameSettingId);
     attrs.userName      = (std::string) _experiment->getSettingValue(cUserNameSettingId);
     attrs.comments      =(std::string) _experiment->getSettingValue(cCommentsSettingId);
     attrs.lensMag       = (std::string)_experiment->getSettingValue(cMicroscopeMagnificationSettingId);
     attrs.otherMag      = (std::string)_experiment->getSettingValue(cOtherMagnificationSettingId);
     attrs.imagingMode   = (std::string)_experiment->getSettingValue(cImagingModeSettingId);
     attrs.cellType      = (std::string)_experiment->getSettingValue(cCellTypeSettingId);
     attrs.treatment1    = (std::string)_experiment->getSettingValue(cCellTreatmentSettingId);
     attrs.treatment2    = (std::string)_experiment->getSettingValue(cCellTreatment2SettingId);
     attrs.temperature   = (std::string)_experiment->getSettingValue(cCellTemperatureSettingId);
     attrs.CO2           = (std::string)_experiment->getSettingValue(cCellCO2SettingId);
     attrs.O2            = (std::string)_experiment->getSettingValue(cCellO2SettingId);
     return attrs;
 }
rcTimestamp rcExperimentDomainImpl::getExperimentLength (void) virtual
Implements rcExperimentDomain.
Definition at line 207 of file rc_experimentdomainimpl.cpp.
References _engine, and rcEngine::getElapsedTime().
 {
     return _engine->getElapsedTime();
 }
rcTimestamp rcExperimentDomainImpl::getExperimentStart (void) virtual
Implements rcExperimentDomain.
Definition at line 241 of file rc_experimentdomainimpl.cpp.
References _engine, and rcEngine::getStartTime().
 {
     return _engine->getStartTime();
 }
rcExperimentState rcExperimentDomainImpl::getExperimentState (void) virtual
Implements rcExperimentDomain.
Definition at line 141 of file rc_experimentdomainimpl.cpp.
References _state.
 {
     return _state;
 }
void rcExperimentDomainImpl::getPolys (rcPolygonGroupRef & polys) virtual
Implements rcEngineObserver.
Definition at line 456 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::getPolys().
 {
   _observer->getPolys ( polys );
 }
void rcExperimentDomainImpl::initialize (rcExperimentObserver * observer) virtual
Implements rcExperimentDomain.
Definition at line 27 of file rc_experimentdomainimpl.cpp.
References _engine, _experiment, _observer, rcEngineFactory::getEngine(), and rcEngine::initialize().
Referenced by main().
 {
     _engine = rcEngineFactory::getEngine();
     _observer = observer;
     _engine->initialize( this );
     _experiment = new rcExperimentImpl();
 }
int rcExperimentDomainImpl::loadExperiment (const char * fileName, const rcXMLElementTree & tree, rcExperimentImportMode mode, rcProgressIndicator * progress = NULL) virtual
Implements rcExperimentDomain.
Definition at line 67 of file rc_experimentdomainimpl.cpp.
References _experiment, _observer, _state, cFileNameSettingId, eExperimentLocked, rcExperimentImpl::loadExperiment(), newExperiment(), rcExperimentObserver::notifyState(), and rcExperimentImpl::setSettingValue().
 {
     int errors = 1;
     // Reset everything
     newExperiment();
     if ( _experiment ) {
         // Import XML tree into experiment
         errors = _experiment->loadExperiment( tree, mode, this, progress );
         if ( errors > 0 ) {
             // We may be in an inconsistent state
             // Reset everything
             newExperiment();
         } else {
             rcValue value( fileName );
             // Set actual XML file name that was loaded
             _experiment->setSettingValue( cFileNameSettingId, value );
             _state = eExperimentLocked;
             _observer->notifyState( _state );
         }
     }
     return errors;
 }
void rcExperimentDomainImpl::lock () virtual
Implements rcCarbonLock.
Definition at line 501 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyLockApp().
Referenced by notifyLockApp().
 {
     _observer->notifyLockApp( true );
 }
void rcExperimentDomainImpl::newExperiment (void) virtual
Implements rcExperimentDomain.
Definition at line 50 of file rc_experimentdomainimpl.cpp.
References _engine, _experiment, _length, _observer, _state, cZeroTime, eExperimentEmpty, rcExperimentObserver::notifyState(), rcExperimentObserver::notifyTime(), and rcEngine::reset().
Referenced by loadExperiment(), and main().
 {
     rcExperimentImpl* oldExperiment = _experiment;
     _experiment = new rcExperimentImpl();
     _state = eExperimentEmpty;
     _length = cZeroTime;
     _engine->reset();
     _observer->notifyState( _state, true ); // Immediate signal dispatch
     _observer->notifyTime( _length );
     // Delete old experiment last so that GUI notifications
     // do no access deleted settings
     if ( oldExperiment )
         delete oldExperiment;
 }
void rcExperimentDomainImpl::notifyAnalysisRect (const rcRect & rect) virtual
Implements rcEngineObserver.
Definition at line 408 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyAnalysisRect().
 {
     _observer->notifyAnalysisRect( rect );
 }
void rcExperimentDomainImpl::notifyAnalysisRectRotation (const rcAffineRectangle & affine) virtual
Implements rcEngineObserver.
Definition at line 421 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyAnalysisRectRotation().
 {
     _observer->notifyAnalysisRectRotation( affine );
 }
void rcExperimentDomainImpl::notifyBlitData (const rcWindow * image) virtual
Implements rcEngineObserver.
Definition at line 442 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyBlitData().
 {
     _observer->notifyBlitData( image );
 }
void rcExperimentDomainImpl::notifyBlitGraphics (const rcVisualGraphicsCollection * graphics) virtual
Implements rcEngineObserver.
Definition at line 463 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyBlitGraphics().
 {
     _observer->notifyBlitGraphics( graphics );
 }
void rcExperimentDomainImpl::notifyCursorTime (const rcTimestamp & time) virtual
Implements rcExperimentDomain.
Definition at line 221 of file rc_experimentdomainimpl.cpp.
References _cursorTime, and rcAtomicValue< T >::setValue().
Referenced by notifyTime().
 {
   _cursorTime.setValue(time);
 }
void rcExperimentDomainImpl::notifyError (const char * errorString) virtual
Implements rcEngineObserver.
Definition at line 314 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyError().
 {
     _observer->notifyError( errorString );
 }
void rcExperimentDomainImpl::notifyExperimentChange (void) virtual
Implements rcEngineObserver.
Definition at line 494 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyExperimentChange().
 {
     _observer->notifyExperimentChange();
 }
void rcExperimentDomainImpl::notifyLockApp (bool lock) virtual
Implements rcEngineObserver.
Definition at line 469 of file rc_experimentdomainimpl.cpp.
References lock(), and unlock().
 {
     if ( l )
         lock();
     else
         unlock();
 }
void rcExperimentDomainImpl::notifyMovieImport () virtual
Implements rcExperimentDomain.
Definition at line 227 of file rc_experimentdomainimpl.cpp.
References _engine, _experiment, cTitleSettingId, rcEngine::getAttributes(), rcEngineAttributes::inputName, rfStripExtension(), rfStripPath(), and rcExperimentImpl::setSettingValue().
 {
     if ( _experiment ) {
         std::string fileName = _engine->getAttributes().inputName;
         // Get file name without preceding path
         std::string rawFileName = rfStripPath( fileName );
         std::string strippedName = rfStripExtension( rawFileName );
         // Use file name as default title
         _experiment->setSettingValue( cTitleSettingId, rcValue( strippedName ) );
     }
 }
void rcExperimentDomainImpl::notifyMultiplier (const double & multiplier) virtual
Implements rcEngineObserver.
Definition at line 414 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyMultiplier().
 {
     _observer->notifyMultiplier( multiplier );
 }
void rcExperimentDomainImpl::notifyPolys (const rcPolygonGroupRef * polys) virtual
Implements rcEngineObserver.
Definition at line 449 of file rc_experimentdomainimpl.cpp.
References _engine, and rcEngine::notifyEngineOfPolys().
 {
   _engine->notifyEngineOfPolys (polys);
 }
int rcExperimentDomainImpl::notifyRequestSave (const char * fileName, rcExperimentFileFormat format) virtual
Implements rcEngineObserver.
Definition at line 478 of file rc_experimentdomainimpl.cpp.
References _observer, rcExperimentObserver::notifyExperimentChange(), NULL, and saveExperiment().
 {
     int status = saveExperiment( fileName, format, NULL );
     // Update widgets
     _observer->notifyExperimentChange();
     return status;
 }
void rcExperimentDomainImpl::notifyState (rcEngineState newState) virtual
Implements rcEngineObserver.
Definition at line 332 of file rc_experimentdomainimpl.cpp.
References _engine, _experiment, _state, cInputImageSourceNameSettingId, rcExperimentImpl::editableSettings(), eEnginePlayback, eEngineRunning, eEngineShuttingDown, eEngineStopped, eEngineUninitialized, eExperimentEnded, eExperimentLocked, eExperimentPlayback, eExperimentRunning, rcEngine::getAttributes(), rcEngineAttributes::inputName, setInternalState(), and rcExperimentImpl::setSettingValue().
 {
     rcExperimentState newState = _state;
     switch (engineState)
     {
         case eEngineUninitialized:
             if ( _experiment )
                 _experiment->editableSettings( true );
             break;
         case eEngineRunning:        // engine is running and generating data
             newState = eExperimentRunning;
             if ( _experiment )
                 _experiment->editableSettings( false );
             break;
         case eEnginePlayback:
             newState = eExperimentPlayback;
             break;
         case eEngineStopped:        // engine is stopped and not generating data
             // If it's locked already, keep it locked
             if ( _state == eExperimentLocked )
                 newState = eExperimentLocked;
             else
                 newState = eExperimentEnded;
             if ( _experiment )
                 _experiment->editableSettings( false );
             break;
         case eEngineShuttingDown:   // engine is in the process of shutting down
             _experiment->editableSettings( false );
             break;
         default:
             return;     // ignore.
     }
     if ( _experiment ) {
         // Set experiment image input source name
         std::string inputName = _engine->getAttributes().inputName;
         rcValue value( inputName );
         _experiment->setSettingValue( cInputImageSourceNameSettingId, value );
     }
     setInternalState( newState );
 }
void rcExperimentDomainImpl::notifyStatus (const char * statusString) virtual
Implements rcEngineObserver.
Definition at line 326 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyStatus().
 {
     _observer->notifyStatus( statusString );
 }
void rcExperimentDomainImpl::notifyTime (const rcTimestamp & timestamp) virtual
Implements rcEngineObserver.
Definition at line 383 of file rc_experimentdomainimpl.cpp.
References _length, _observer, _state, eExperimentPlayback, notifyCursorTime(), rcExperimentObserver::notifyProgCursorTime(), and rcExperimentObserver::notifyTime().
 {
   if (_state == eExperimentPlayback) {
     notifyCursorTime( timestamp );
     _observer->notifyProgCursorTime( timestamp );
   }
   else {
     _length = timestamp;
     _observer->notifyTime( timestamp );
   }
 }
void rcExperimentDomainImpl::notifyTimelineRange (const rcTimestamp & start, const rcTimestamp & end) virtual
Implements rcEngineObserver.
Definition at line 401 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyEngineTimelineRange().
 {
     _observer->notifyEngineTimelineRange( start, end );
 }
void rcExperimentDomainImpl::notifyVideoRect (const rcRect & rect) virtual
Implements rcEngineObserver.
Definition at line 488 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyVideoRect().
 {
     _observer->notifyVideoRect( rect );
 }
void rcExperimentDomainImpl::notifyWarning (const char * warnString) virtual
Implements rcEngineObserver.
Definition at line 320 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyWarning().
 {
     _observer->notifyWarning( warnString );
 }
bool rcExperimentDomainImpl::operatingOnLiveInput (void) virtual
Implements rcExperimentDomain.
Definition at line 147 of file rc_experimentdomainimpl.cpp.
References _engine, and rcEngine::operatingOnLiveInput().
 {
   return _engine->operatingOnLiveInput ();
 }
bool rcExperimentDomainImpl::pauseTrackingExperiment (void) virtual
Implements rcExperimentDomain.
Definition at line 282 of file rc_experimentdomainimpl.cpp.
References _engine, _state, eExperimentLocked, rcEngine::pauseTracking(), and rmExceptionMacro.
 {
     if (_state == eExperimentLocked)
       rmExceptionMacro (<< "Experiment is locked");
     return _engine->pauseTracking ();
 }
void rcExperimentDomainImpl::processExperiment (void) virtual
Implements rcExperimentDomain.
Definition at line 269 of file rc_experimentdomainimpl.cpp.
References _engine, _state, eExperimentEmpty, rcEngine::process(), and rmExceptionMacro.
Referenced by main().
 {
     if (_state == eExperimentEmpty) {
         _engine->process();
     }
     else {
         if (_state == eExperimentEmpty)
       rmExceptionMacro ( << "experiment has not started yet" );
         _engine->process();
     }
 }
int rcExperimentDomainImpl::saveExperiment (const char * fileName, rcExperimentFileFormat format, rcProgressIndicator * progress = NULL) virtual
Implements rcExperimentDomain.
Definition at line 98 of file rc_experimentdomainimpl.cpp.
References _experiment, _state, rcMovieConverterOptions::clipRect(), rcMovieConverterOptions::creator(), eExperimentEmpty, eExperimentLocked, rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcPersistenceManager::generatorComment(), rcExperimentImpl::getNSettingCategories(), rcPersistenceManagerFactory::getPersistenceManager(), rcExperimentImpl::getSettingCategory(), rcSettingCategory::getSettingInfo(), rcSettingCategory::getTag(), rcSettingInfo::getValue(), rcRectangle< T >::height(), rmExceptionMacro, rcExperimentImpl::saveTo(), and rcRectangle< T >::width().
Referenced by main(), and notifyRequestSave().
 {
     if (_state == eExperimentEmpty)
       rmExceptionMacro (<< "experiment not running, there is nothing to save" );
     rcPersistenceManager* persistenceManager = rcPersistenceManagerFactory::getPersistenceManager();
     const std::string creator = persistenceManager->generatorComment();
     rcMovieConverterOptions opt;
     opt.creator( creator );
     int nPages = _experiment->getNSettingCategories();
     for (int i = 0; i < nPages; i++)
     {
         rcSettingCategory category = _experiment->getSettingCategory( i );
         // Look for analysis settings
         if ( !strcmp( category.getTag(), "analysis-settings" ) ) {
             const rcSettingInfo rect = category.getSettingInfo( "analysis-rect" );
             const rcSettingInfo firstFrame = category.getSettingInfo( "analysis-first-frame" );
             const rcSettingInfo lastFrame = category.getSettingInfo( "analysis-last-frame" );
             rcRect analysisRect = rect.getValue();
             // Hack: use analysis first and last frame to specify whoch frames to export
             int32 first = firstFrame.getValue();
             int32 last = lastFrame.getValue();
             opt.frameCount( last - first + 1 );
             opt.firstFrameIndex( first );
             if ( analysisRect.width() > 0 && analysisRect.height() > 0 )
                 opt.clipRect( analysisRect );
         }
     }
     int err = _experiment->saveTo( fileName, format, opt, this, progress );
     _state = eExperimentLocked;
     return err;
 }
void rcExperimentDomainImpl::setExperimentAttributes (const rcExperimentAttributes & attr) virtual
Implements rcEngineObserver.
Definition at line 189 of file rc_experimentdomainimpl.cpp.
References _experiment, cCellCO2SettingId, cCellO2SettingId, cCellTemperatureSettingId, cCellTreatment2SettingId, cCellTreatmentSettingId, cCellTypeSettingId, cCommentsSettingId, rcExperimentAttributes::cellType, cImagingModeSettingId, cMicroscopeMagnificationSettingId, rcExperimentAttributes::CO2, rcExperimentAttributes::comments, cOtherMagnificationSettingId, cTitleSettingId, cUserNameSettingId, rcExperimentAttributes::imagingMode, rcExperimentAttributes::lensMag, rcExperimentAttributes::O2, rcExperimentAttributes::otherMag, rcExperimentImpl::setSettingValue(), rcExperimentAttributes::temperature, rcExperimentAttributes::title, rcExperimentAttributes::treatment1, rcExperimentAttributes::treatment2, and rcExperimentAttributes::userName.
 {
     _experiment->setSettingValue( cTitleSettingId, rcValue(attrs.title) );
     _experiment->setSettingValue( cUserNameSettingId, rcValue(attrs.userName) );
     _experiment->setSettingValue( cCommentsSettingId, rcValue(attrs.comments) );
     _experiment->setSettingValue( cMicroscopeMagnificationSettingId, rcValue(attrs.lensMag) );
     _experiment->setSettingValue( cOtherMagnificationSettingId, rcValue(attrs.otherMag) );
     _experiment->setSettingValue( cImagingModeSettingId, rcValue(attrs.imagingMode) );
     _experiment->setSettingValue( cCellTypeSettingId, rcValue(attrs.cellType) );
     _experiment->setSettingValue( cCellTreatmentSettingId, rcValue(attrs.treatment1) );
     _experiment->setSettingValue( cCellTreatment2SettingId, rcValue(attrs.treatment2) );
     _experiment->setSettingValue( cCellTemperatureSettingId, rcValue(attrs.temperature) );
     _experiment->setSettingValue( cCellCO2SettingId, rcValue(attrs.CO2) );
     _experiment->setSettingValue( cCellO2SettingId, rcValue(attrs.O2) );
 }
void rcExperimentDomainImpl::setInternalState (rcExperimentState newState) private
Definition at line 514 of file rc_experimentdomainimpl.cpp.
References _observer, _state, endl(), and rcExperimentObserver::notifyState().
Referenced by notifyState().
 {
     if (newState != _state)
     {
         _state = newState;
         _observer->notifyState( newState );
     } else {
         cerr << "rcExperimentDomainImpl::setInternalState already in state " << newState << endl;
     }
 }
void rcExperimentDomainImpl::shutdown (void) virtual
Implements rcExperimentDomain.
Definition at line 38 of file rc_experimentdomainimpl.cpp.
References _engine, and rcEngine::shutdown().
Referenced by main().
 {
     _engine->shutdown();
 }
void rcExperimentDomainImpl::startExperiment (void) virtual
Implements rcExperimentDomain.
Definition at line 247 of file rc_experimentdomainimpl.cpp.
References _engine, _state, eExperimentEmpty, eExperimentLocked, rmExceptionMacro, and rcEngine::start().
Referenced by main().
 {
     if (_state == eExperimentLocked)
       rmExceptionMacro (<< "Experiment is locked");
     if (_state != eExperimentEmpty)
       rmExceptionMacro (<< "Experiment is not empty");
     _engine->start();
 }
void rcExperimentDomainImpl::stopExperiment (void) virtual
Implements rcExperimentDomain.
Definition at line 259 of file rc_experimentdomainimpl.cpp.
References _engine, _state, eExperimentEmpty, eExperimentRunning, rmExceptionMacro, and rcEngine::stop().
Referenced by main().
 {
     if (_state == eExperimentEmpty)
       rmExceptionMacro ( << "experiment has not run yet" );
     if (_state != eExperimentRunning)
       rmExceptionMacro ( << "experiment has already stopped" );
     _engine->stop();
 }
bool rcExperimentDomainImpl::storingLiveInput (void) virtual
Implements rcExperimentDomain.
Definition at line 152 of file rc_experimentdomainimpl.cpp.
References _engine, and rcEngine::storingLiveInput().
 {
   return _engine->storingLiveInput ();
 }
int32 rcExperimentDomainImpl::timeEventCount () const virtual
Implements rcEngineObserver.
Definition at line 395 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::progCursorTimeEventCount().
 {
   return _observer->progCursorTimeEventCount();
 }
void rcExperimentDomainImpl::unlock () virtual
Implements rcCarbonLock.
Definition at line 506 of file rc_experimentdomainimpl.cpp.
References _observer, and rcExperimentObserver::notifyLockApp().
Referenced by notifyLockApp().
 {
     _observer->notifyLockApp( false );
 }
Member Data Documentation
rcAtomicValue<rcTimestamp> rcExperimentDomainImpl::_cursorTime private
Definition at line 192 of file rc_experimentdomainimpl.h.
Referenced by getCursorTime(), and notifyCursorTime().
rcEngine* rcExperimentDomainImpl::_engine private
Definition at line 187 of file rc_experimentdomainimpl.h.
Referenced by doneSelecting(), getExperimentAttributes(), getExperimentLength(), getExperimentStart(), initialize(), newExperiment(), notifyMovieImport(), notifyPolys(), notifyState(), operatingOnLiveInput(), pauseTrackingExperiment(), processExperiment(), rcExperimentDomainImpl(), shutdown(), startExperiment(), stopExperiment(), and storingLiveInput().
rcExperimentImpl* rcExperimentDomainImpl::_experiment private
Definition at line 189 of file rc_experimentdomainimpl.h.
Referenced by createWriterGroup(), getExperiment(), getExperimentAttributes(), initialize(), loadExperiment(), newExperiment(), notifyMovieImport(), notifyState(), rcExperimentDomainImpl(), saveExperiment(), and setExperimentAttributes().
rcTimestamp rcExperimentDomainImpl::_length private
Definition at line 191 of file rc_experimentdomainimpl.h.
Referenced by newExperiment(), notifyTime(), and rcExperimentDomainImpl().
rcExperimentObserver* rcExperimentDomainImpl::_observer private
Definition at line 188 of file rc_experimentdomainimpl.h.
Referenced by acceptingImageBlits(), acceptingPolys(), getPolys(), initialize(), loadExperiment(), lock(), newExperiment(), notifyAnalysisRect(), notifyAnalysisRectRotation(), notifyBlitData(), notifyBlitGraphics(), notifyError(), notifyExperimentChange(), notifyMultiplier(), notifyRequestSave(), notifyStatus(), notifyTime(), notifyTimelineRange(), notifyVideoRect(), notifyWarning(), rcExperimentDomainImpl(), setInternalState(), timeEventCount(), and unlock().
rcTimestamp rcExperimentDomainImpl::_start private
Definition at line 193 of file rc_experimentdomainimpl.h.
rcExperimentState rcExperimentDomainImpl::_state private
Definition at line 190 of file rc_experimentdomainimpl.h.
Referenced by doneSelecting(), getExperimentState(), loadExperiment(), newExperiment(), notifyState(), notifyTime(), pauseTrackingExperiment(), processExperiment(), rcExperimentDomainImpl(), saveExperiment(), setInternalState(), startExperiment(), and stopExperiment().
The documentation for this class was generated from the following files:
include/visiCore/rc_experimentdomainimpl.h
src/visible/src/rc_experimentdomainimpl.cpp