Visible: rcTimingInfo Class Reference
rcTimingInfo Class Reference
#include <include/util/rc_timinginfo.h>
Public Member Functions
rcTimingInfo (uint32 locations, uint32 passes)
void touch (uint32 location)
void touch (uint32 location, std::string label)
void nextPass (bool reset)
void printInfo (uint32 passes, vector< std::string > &labels)
void printInfo (uint32 passes)
Static Public Member Functions
static bool turnOffPrint ()
static bool turnOnPrint ()
Static Public Attributes
static bool mPrintOff = false
Private Attributes
vector< rcTimestamp > _times
vector< std::string > _labels
rcTimestamp _resetTime
vector< vector< double > > _deltas
vector< vector< double >
>::iterator _firstValidPass
vector< vector< double >
>::iterator _curPass
uint32 _curPassLoc
Detailed Description
Definition at line 11 of file rc_timinginfo.h.
Constructor & Destructor Documentation
rcTimingInfo::rcTimingInfo (uint32 locations, uint32 passes)
Definition at line 10 of file rc_timinginfo.cpp.
References _curPass, _deltas, _firstValidPass, _labels, _resetTime, _times, rcTimestamp::now(), and rmAssert.
   : _curPassLoc(0)
 {
   rmAssert(locations > 1);
   rmAssert(passes);
   _times.resize(locations);
   _labels.resize(locations);
   _deltas.resize(passes);
   for (vector<vector<double> >::iterator i = _deltas.begin(); i != _deltas.end(); i++) {
     i->resize(locations);
     for (uint32 j = 0; j < i->size(); j++)
       (*i)[j] = -1;
   }
   for (uint32 i = 0; i < locations; i++)
     _labels[i] = std::string ("");
   _firstValidPass = _curPass = _deltas.begin();
   _resetTime = rcTimestamp::now();
 }
Member Function Documentation
void rcTimingInfo::nextPass (bool reset)
Definition at line 58 of file rc_timinginfo.cpp.
References _curPass, _curPassLoc, _deltas, _firstValidPass, _resetTime, and rcTimestamp::now().
Referenced by _exhaustiveImageFind(), rcKinetoscope::advance(), rcKinetoscope::measure(), rcVisualFunction::measure(), rcEngineMoviePlayback::run(), rcKinetoscope::stepEpi(), and rcKinetoscope::update().
 {
   _curPassLoc = 0;
   if (++_curPass == _deltas.end())
     _curPass = _deltas.begin();
   /* Note: Its not necessary to set the iterators back to _deltas.begin() in
    * the reset case, but it makes for less testing.
    */
   if (reset)
     _firstValidPass = _curPass = _deltas.begin();
   else if (_curPass == _firstValidPass) {
     if (++_firstValidPass == _deltas.end())
       _firstValidPass = _deltas.begin();
   }
   _resetTime = rcTimestamp::now();
 }
void rcTimingInfo::printInfo (uint32 passes, vector< std::string > & labels)
Definition at line 84 of file rc_timinginfo.cpp.
References _curPass, _curPassLoc, _deltas, _firstValidPass, _labels, and mPrintOff.
Referenced by rcKinetoscope::advance(), rcVisualFunction::match(), rcKinetoscope::measure(), rcVisualFunction::measure(), printInfo(), rcKinetoscope::stepEpi(), and rcKinetoscope::update().
 {
   if (!mPrintOff)
     {
   fprintf(stderr, "Timing Info Dump\nRequested passes: %d\n\n", passes);
   vector<vector<double> >::iterator prtPass = _firstValidPass;
   for (uint32 i = 0; i < passes; i++) {
     uint32 endLoc = (*prtPass).size();
     if (prtPass == _curPass)
       endLoc = _curPassLoc;
     fprintf(stderr, " Pass %02d Index   Time\n", i);
     for (uint32 j = 0; j < endLoc; j++) {
       const char* label;
       if (labels.size() > j)
     label = labels[j].c_str();
       else
     label = _labels[j].c_str();
       if ((*prtPass)[j] < 0)
     fprintf(stderr,"         %02d       ------ %s\n", j, label);
       else if ((*prtPass)[j] < 1e-3)
     fprintf(stderr,"         %02d       %3.0f us %s\n", j, (*prtPass)[j]*(1e6), label);
       else if ((*prtPass)[j] < 1)
     fprintf(stderr,"         %02d       %3.0f ms %s *\n", j, (*prtPass)[j]*(1e3), label);
       else
     fprintf(stderr,"         %02d       %3.0f s %s **\n", j, (*prtPass)[j], label);
     }
     fprintf(stderr, "\n");
     if (prtPass == _curPass)
       break;
     if (++prtPass == _deltas.end())
       prtPass = _deltas.begin();
   }
     }
 }
void rcTimingInfo::printInfo (uint32 passes)
Definition at line 77 of file rc_timinginfo.cpp.
References printInfo().
 {
   vector<std::string> dummy;
   printInfo(passes, dummy);
 }
void rcTimingInfo::touch (uint32 location)
Definition at line 38 of file rc_timinginfo.cpp.
References _curPass, _curPassLoc, _resetTime, _times, rcTimestamp::now(), rmAssert, and rcTimestamp::secs().
Referenced by _exhaustiveImageFind(), rcKinetoscope::advance(), rcVisualFunction::match(), rcKinetoscope::measure(), rcVisualFunction::measure(), rcKinetoscope::stepEpi(), touch(), and rcKinetoscope::update().
 {
   rmAssert(location < _times.size());
   if (location < _curPassLoc)
     return;
   _times[location] = rcTimestamp::now();
   if (location)
     (*_curPass)[location] = _times[location].secs() - _times[_curPassLoc-1].secs();
   else
     (*_curPass)[0] = _times[location].secs() - _resetTime.secs();
   for ( ; _curPassLoc < location; _curPassLoc++) {
     (*_curPass)[_curPassLoc] = -1;
   }
   _curPassLoc++;
 }
void rcTimingInfo::touch (uint32 location, std::string label)
Definition at line 32 of file rc_timinginfo.cpp.
References _labels, and touch().
 {
   touch (location);
   _labels[location] = label;
 }
static bool rcTimingInfo::turnOffPrint () inline static
Definition at line 43 of file rc_timinginfo.h.
References mPrintOff.
Referenced by rcKinetoscope::rcKinetoscope().
 { mPrintOff = true; return mPrintOff; }
static bool rcTimingInfo::turnOnPrint () inline static
Definition at line 44 of file rc_timinginfo.h.
References mPrintOff.
 { mPrintOff = false; return mPrintOff;}
Member Data Documentation
vector<vector<double> >::iterator rcTimingInfo::_curPass private
Definition at line 53 of file rc_timinginfo.h.
Referenced by nextPass(), printInfo(), rcTimingInfo(), and touch().
uint32 rcTimingInfo::_curPassLoc private
Definition at line 54 of file rc_timinginfo.h.
Referenced by nextPass(), printInfo(), and touch().
vector<vector<double> > rcTimingInfo::_deltas private
Definition at line 51 of file rc_timinginfo.h.
Referenced by nextPass(), printInfo(), and rcTimingInfo().
vector<vector<double> >::iterator rcTimingInfo::_firstValidPass private
Definition at line 52 of file rc_timinginfo.h.
Referenced by nextPass(), printInfo(), and rcTimingInfo().
vector<std::string> rcTimingInfo::_labels private
Definition at line 49 of file rc_timinginfo.h.
Referenced by printInfo(), rcTimingInfo(), and touch().
rcTimestamp rcTimingInfo::_resetTime private
Definition at line 50 of file rc_timinginfo.h.
Referenced by nextPass(), rcTimingInfo(), and touch().
vector<rcTimestamp> rcTimingInfo::_times private
Definition at line 48 of file rc_timinginfo.h.
Referenced by rcTimingInfo(), and touch().
bool rcTimingInfo::mPrintOff = false static
Definition at line 45 of file rc_timinginfo.h.
Referenced by printInfo(), turnOffPrint(), and turnOnPrint().
The documentation for this class was generated from the following files:
include/util/rc_timinginfo.h
src/util/code/rc_timinginfo.cpp