Visible: rcMathematicalImage Class Reference
rcMathematicalImage Class Reference
#include <include/analysis/rc_mathmodel.h>
Public Types
enum distribution {
eGauss, eGabor, eDoGauss, eLoGauss,
eCone, eFrustum
}
enum polarity { eHiPeak, eLowPeak, eField }
Public Member Functions
rcMathematicalImage (rcRadian o, rcRadian p, double f, double a, double std)
rcMathematicalImage (double std=1.0)
rcMathematicalImage (double std, double ratio)
void gauss (rcWindow &i, polarity p=eLowPeak)
void gabor (rcWindow &i, polarity p=eLowPeak)
void dOg (rcWindow &i, polarity p=eLowPeak)
void lOg (rcWindow &i, polarity p=eLowPeak)
void cone (rcWindow &i, polarity p=eLowPeak)
void frustum (rcWindow &i, float dr=0.0f)
Private Member Functions
void mMakeImage (rcWindow &, distribution, polarity)
void mMakeField (rcWindow &, distribution, float dr=0.0f)
Private Attributes
rcRadian mOrientation
rcRadian mPhase
double mFrequency
double mAmplitude
double mStd
double mRatio
Detailed Description
Definition at line 45 of file rc_mathmodel.h.
Member Enumeration Documentation
enum rcMathematicalImage::distribution
Enumerator
eGauss
eGabor
eDoGauss
eLoGauss
eCone
eFrustum
Definition at line 49 of file rc_mathmodel.h.
     {
       eGauss,
       eGabor,
       eDoGauss,
       eLoGauss,
       eCone,
       eFrustum
     };
enum rcMathematicalImage::polarity
Enumerator
eHiPeak
eLowPeak
eField
Definition at line 59 of file rc_mathmodel.h.
     {
       eHiPeak,
       eLowPeak,
       eField
     };
Constructor & Destructor Documentation
rcMathematicalImage::rcMathematicalImage (rcRadian o, rcRadian p, double f, double a, double std) inline
Definition at line 67 of file rc_mathmodel.h.
     :mOrientation (o), mPhase (p), mFrequency (f), mAmplitude (a), mStd (std), mRatio (0.0)
   {}
rcMathematicalImage::rcMathematicalImage (double std = 1.0) inline
Definition at line 71 of file rc_mathmodel.h.
     :mOrientation (rcRadian (0.0)), mPhase (rcRadian (0.0)), mFrequency (1.0), mAmplitude (1.0), mStd (std), mRatio (0.0)
   {}
rcMathematicalImage::rcMathematicalImage (double std, double ratio) inline
Definition at line 75 of file rc_mathmodel.h.
     :mOrientation (rcRadian (0.0)), mPhase (rcRadian (0.0)), mFrequency (1.0), mAmplitude (1.0), mStd (std), mRatio (ratio)
   {}
Member Function Documentation
void rcMathematicalImage::cone (rcWindow & i, polarity p = eLowPeak) inline
Definition at line 99 of file rc_mathmodel.h.
References eCone, and mMakeImage().
   {
     mMakeImage (i, eCone, p);
   }
void rcMathematicalImage::dOg (rcWindow & i, polarity p = eLowPeak) inline
Definition at line 89 of file rc_mathmodel.h.
References eDoGauss, and mMakeImage().
   {
     mMakeImage (i, eDoGauss, p);
   }
void rcMathematicalImage::frustum (rcWindow & i, float dr = 0.0f) inline
Definition at line 104 of file rc_mathmodel.h.
References eFrustum, and mMakeField().
   {
     mMakeField (i, eFrustum, dr);
   }
void rcMathematicalImage::gabor (rcWindow & i, polarity p = eLowPeak) inline
Definition at line 84 of file rc_mathmodel.h.
References eGabor, and mMakeImage().
   {
     mMakeImage (i, eGabor, p);
   }
void rcMathematicalImage::gauss (rcWindow & i, polarity p = eLowPeak) inline
Definition at line 79 of file rc_mathmodel.h.
References eGauss, and mMakeImage().
Referenced by rcVisualFunction::createIrradianceModel(), and rcGaussKernel2D< T, ksize >::rcGaussKernel2D().
   {
     mMakeImage (i, eGauss, p);
   }
void rcMathematicalImage::lOg (rcWindow & i, polarity p = eLowPeak) inline
Definition at line 94 of file rc_mathmodel.h.
References eLoGauss, and mMakeImage().
   {
     mMakeImage (i, eLoGauss, p);
   }
void rcMathematicalImage::mMakeField (rcWindow & frame, distribution d, float dr = 0.0f) private
Definition at line 137 of file rc_mathmodel.cpp.
References arctan(), rcRadian::basic(), rcAngle8::basic(), rcAngle16::basic(), rcWindow::depth(), rcWindow::height(), rcWindow::isD32Float(), rc2dVector< T >::isNull(), rc2dVector< T >::l2(), rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, rmAssert, rcWindow::setPixel(), rcWindow::width(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by frustum().
 {
   int32 cX = frame.width() / 2;
   int32 cY = frame.height() / 2;
   rcPixel depth = frame.depth();
   rc2Fvector center ((float) cX, (float) cY);
   for (int32 j = 0; j < frame.height(); j++)
     for (int32 i = 0; i < frame.width(); i++)
       {
     rc2Fvector p ((float) i, (float) j);
     p = p - center;
     if (p.isNull() || p.l2() < dr)
       {
         frame.setPixel (i, j, 0);
         continue;
       }
     rcRadian rd = arctan ((double) p.y(), (double) -p.x());
     switch (depth)
       {
       case rcPixel8:
         {
         rcAngle8 d (rd);
         frame.setPixel (i, j, 255 - d.basic());
         }
         break;
       case rcPixel16:
         {
         rcAngle16 d (rd);
         frame.setPixel (i, j, d.basic());
         }
         break;
       case rcPixel32:
         if (!frame.isD32Float())
           {
         rcAngle16 d (rd);
         frame.setPixel (i, j, d.basic());
           }
         else
           frame.setPixel (i, j, (float) rd.basic());
         break;
       case rcPixelDouble:
         frame.setPixel (i, j, rd.basic());
         break;
       default:
         rmAssert (0);
       }
       }
 }
void rcMathematicalImage::mMakeImage (rcWindow & frame, distribution d, polarity p) private
Definition at line 77 of file rc_mathmodel.cpp.
References rcWindow::depth(), eLowPeak, rcWindow::height(), MAIN, mFrequency, mRatio, mStd, pow(), rcDBL_MAX, rcDBL_MIN, rcPixel16, rcPixel32, rcPixel8, rcUINT16_MAX, rcUINT32_MAX, rcUINT8_MAX, rk2PI, rkPI, rmAssert, rmSquare, rcWindow::setPixel(), and rcWindow::width().
Referenced by cone(), dOg(), gabor(), gauss(), and lOg().
 {
   int32    v, h;
   double  x, y;
   double  f, st, sp, sl, rst (-1.0), rsp (-1.0);
   double  E, S, G, G2, L, R;
   int32 nw = frame.width() / 2;
   int32 nh = frame.height() / 2;
   double minV (rcDBL_MAX);
   double maxV (rcDBL_MIN);
   /* pre-calculation */
   f = frame.width() / mFrequency;
   st = 1.0 / (2.0 * rmSquare (mStd));
   sp = 1.0 / (sqrt (rk2PI) * mStd);
   sl = -1.0 / (rkPI * pow (mStd, 4));
   if (mRatio > 0.001)
     {
       rst = 1.0 / (2.0 * rmSquare (mStd * mRatio));
       rsp = 1.0 / (sqrt (rk2PI) * mStd * mRatio);
     }
   for (h = 0; h < frame.width(); h++)
     {
       for (v = 0; v < frame.height(); v++)
     {
       MAIN;
       if (L < minV) minV = L;
       if (L > maxV) maxV = L;
     }
     }
   uint32 umax = (frame.depth() == rcPixel8) ? rcUINT8_MAX :
     (frame.depth() == rcPixel16) ? rcUINT16_MAX :
     (frame.depth() == rcPixel32) ? rcUINT32_MAX : 0;
   rmAssert (umax);
   double scale = ((double) umax) / (maxV - minV);
   // Now we know the min and Max and map it for the integer types and copy directly for the double
   for (h = 0; h < frame.width(); h++)
     {
       for (v = 0; v < frame.height(); v++)
     {
       MAIN;
       L -= minV;
       L *= scale;
       uint32 pel = (p == eLowPeak) ? (umax - (uint32) L) : ((uint32) L);
       frame.setPixel (h, v, pel);
     }
     }
 }
Member Data Documentation
double rcMathematicalImage::mAmplitude private
Definition at line 113 of file rc_mathmodel.h.
double rcMathematicalImage::mFrequency private
Definition at line 112 of file rc_mathmodel.h.
Referenced by mMakeImage().
rcRadian rcMathematicalImage::mOrientation private
Definition at line 110 of file rc_mathmodel.h.
rcRadian rcMathematicalImage::mPhase private
Definition at line 111 of file rc_mathmodel.h.
double rcMathematicalImage::mRatio private
Definition at line 115 of file rc_mathmodel.h.
Referenced by mMakeImage().
double rcMathematicalImage::mStd private
Definition at line 114 of file rc_mathmodel.h.
Referenced by mMakeImage().
The documentation for this class was generated from the following files:
include/analysis/rc_mathmodel.h
src/analysis/code/rc_mathmodel.cpp