Visible: rcTails Class Reference
rcTails Class Reference
#include <include/analysis/rc_level.h>
Public Member Functions
rcTails (const vector< uint32 > &histogram, uint32 leftCutoffCount, uint32 rightCutoffCount)
vector< uint32 >::const_iterator leftTail () const
vector< uint32 >::const_iterator rightTail () const
uint32 offset () const
uint32 cumulativeOffset () const
Private Attributes
vector< uint32 >::const_iterator mLeftTail
vector< uint32 >::const_iterator mRightTail
uint32 mOffset
uint32 mCumulativeOffset
Detailed Description
Definition at line 64 of file rc_level.h.
Constructor & Destructor Documentation
rcTails::rcTails (const vector< uint32 > & histogram, uint32 leftCutoffCount, uint32 rightCutoffCount)
Definition at line 42 of file rc_seglevel.cpp.
References count(), mCumulativeOffset, mLeftTail, mRightTail, and rmAssert.
   : mOffset(0), mCumulativeOffset(0)
 {
   uint32 count = 0;
   // go up from the left end
   if(leftCutoff == 0) {
     mLeftTail = histogram.begin();
   }
   else {
      vector<uint32>::const_iterator p = histogram.begin();
     for(count = 0; (count += *p) < leftCutoff; p++);
     mLeftTail = ++p;
     mCumulativeOffset = count;
   }
   // down from the right end
   if(rightCutoff == 0) {
     mRightTail = histogram.end() - 1;
   }
   else {
      vector<uint32>::const_iterator p = histogram.end() - 1;
     for(count = 0; (count += *p) < rightCutoff; p--);
     mRightTail = --p;
   }
   rmAssert (distance (histogram.begin(), mLeftTail) < distance (histogram.begin(), mRightTail));
 }
Member Function Documentation
uint32 rcTails::cumulativeOffset () const inline
Definition at line 84 of file rc_level.h.
References mCumulativeOffset.
Referenced by rcWithinGroupInv::rcWithinGroupInv().
 {return mCumulativeOffset;}
vector<uint32>::const_iterator rcTails::leftTail () const inline
Definition at line 73 of file rc_level.h.
References mLeftTail.
Referenced by rcWithinGroupInv::rcWithinGroupInv().
   {return mLeftTail;}
uint32 rcTails::offset () const inline
Definition at line 81 of file rc_level.h.
References mOffset.
Referenced by rcWithinGroupInv::rcWithinGroupInv().
 {return mOffset;}
vector<uint32>::const_iterator rcTails::rightTail () const inline
Definition at line 77 of file rc_level.h.
References mRightTail.
Referenced by rcWithinGroupInv::rcWithinGroupInv().
     {return mRightTail;}
Member Data Documentation
uint32 rcTails::mCumulativeOffset private
Definition at line 90 of file rc_level.h.
Referenced by cumulativeOffset(), and rcTails().
vector<uint32>::const_iterator rcTails::mLeftTail private
Definition at line 87 of file rc_level.h.
Referenced by leftTail(), and rcTails().
uint32 rcTails::mOffset private
Definition at line 89 of file rc_level.h.
Referenced by offset().
vector<uint32>::const_iterator rcTails::mRightTail private
Definition at line 88 of file rc_level.h.
Referenced by rcTails(), and rightTail().
The documentation for this class was generated from the following files:
include/analysis/rc_level.h
src/analysis/code/rc_seglevel.cpp