Visible: rcSecurityKey Class Reference
rcSecurityKey Class Reference
#include <include/util/rc_security.h>
Public Types
enum { eTextKeyLength = 8, eBinaryKeyLength = eTextKeyLength*8 }
Public Member Functions
rcSecurityKey (const char *key)
rcSecurityKey (const std::string &key)
const std::string & key () const
const std::string & binaryKey () const
bool operator== (const rcSecurityKey &k) const
bool operator!= (const rcSecurityKey &k) const
Static Public Member Functions
static std::string binaryKey (const std::string &textKey)
static std::string textKey (const std::string &binaryKey)
Private Attributes
std::string mKey
std::string mBinaryKey
Friends
class rcEncryptionEngine
Detailed Description
Definition at line 52 of file rc_security.h.
Member Enumeration Documentation
anonymous enum
Enumerator
eTextKeyLength
eBinaryKeyLength
Definition at line 56 of file rc_security.h.
          {
         eTextKeyLength = 8,
         eBinaryKeyLength = eTextKeyLength*8
     };
Constructor & Destructor Documentation
rcSecurityKey::rcSecurityKey (const char * key) inline
Definition at line 62 of file rc_security.h.
References rmAssert.
                                      : mKey( key ), mBinaryKey( binaryKey( mKey ) ) {
         rmAssert( mKey.length() == eTextKeyLength );
         rmAssert( mBinaryKey.length() == eBinaryKeyLength );
     };
rcSecurityKey::rcSecurityKey (const std::string & key) inline
Definition at line 67 of file rc_security.h.
References rmAssert.
                                           : mKey( key ), mBinaryKey(  binaryKey( mKey ) ) {
         rmAssert( mKey.length() == eTextKeyLength );
         rmAssert( mBinaryKey.length() == eBinaryKeyLength );
     };
Member Function Documentation
const std::string& rcSecurityKey::binaryKey () const inline
Definition at line 75 of file rc_security.h.
Referenced by rcEncryptionEngine::decrypt(), and rcEncryptionEngine::encrypt().
 { return mBinaryKey; };
std::string rcSecurityKey::binaryKey (const std::string & textKey) static
Definition at line 123 of file rc_security.cpp.
References eBinaryKeyLength, eTextKeyLength, and rmAssert.
{
     // Support for 8-byte keys only
     rmAssert( textKey.length() == eTextKeyLength );
     std::string binKey;
     // Produce a 64-byte binary array from 8 bytes
     for ( int byte = 0; byte < eTextKeyLength; byte++ ) {
         for ( int bit = 0; bit < 8; bit++ ) {
             binKey += (textKey[byte] & (1 << bit)) > 0 ? 1 : 0;
         }
     }
     rmAssert( binKey.length() == eBinaryKeyLength );
     return binKey;
 }
const std::string& rcSecurityKey::key () const inline
Definition at line 74 of file rc_security.h.
 { return mKey; };
bool rcSecurityKey::operator!= (const rcSecurityKey & k) const inline
Definition at line 87 of file rc_security.h.
{
         return ! (*this == k );
     };
bool rcSecurityKey::operator== (const rcSecurityKey & k) const inline
Definition at line 84 of file rc_security.h.
References mBinaryKey, and mKey.
{
         return ( mKey == k.mKey && mBinaryKey == k.mBinaryKey );
     };
std::string rcSecurityKey::textKey (const std::string & binaryKey) static
Definition at line 141 of file rc_security.cpp.
References eBinaryKeyLength, eTextKeyLength, and rmAssert.
Referenced by rcEncryptionEngine::decrypt(), and rcEncryptionEngine::encrypt().
{
     // Support for 64-byte keys only
     rmAssert( binaryKey.length() == eBinaryKeyLength );
     std::string textKey;
     // Produce a 8-byte array from a 64-byte binary array
     for ( int byte = 0; byte < eTextKeyLength; byte++ ) {
         char b = 0;
         for ( int bit = 0; bit < 8; bit++ ) {
             if ( binaryKey[byte*8+bit] )
                 b += (1 << bit);
         }
         textKey += b;
     }
     rmAssert( textKey.length() == eTextKeyLength );
     return textKey;
 }
Friends And Related Function Documentation
friend class rcEncryptionEngine friend
Definition at line 89 of file rc_security.h.
Member Data Documentation
std::string rcSecurityKey::mBinaryKey private
Definition at line 95 of file rc_security.h.
Referenced by operator==().
std::string rcSecurityKey::mKey private
Definition at line 94 of file rc_security.h.
Referenced by operator==().
The documentation for this class was generated from the following files:
include/util/rc_security.h
src/util/code/rc_security.cpp