Visible: omtext Class Reference
omtext Class Reference
#include <include/stlplus/multiio.hpp>
Public Member Functions
omtext (void)
omtext (const otext &)
omtext (const otext &, const otext &)
void open (const otext &)
void open (const otext &, const otext &)
unsigned add (const otext &)
void remove (unsigned)
unsigned device_count (void) const
otext & device_get (unsigned)
const otext & device_get (unsigned) const
Public Member Functions inherited from otext
otext (void)
otext (obuff *)
virtual ~otext (void)
bool initialised (void) const
void open (obuff *)
void close (void)
otext (const otext &)
otext & operator= (const otext &)
bool error (void) const
int error_number (void) const
std::string error_string (void) const
void set_error (int error)
void clear_error (void)
void set_newline_mode (newline_t newline=native_mode)
void set_unix_mode (void)
void set_msdos_mode (void)
void set_macos_mode (void)
void set_native_mode (void)
void set_binary_mode (void)
newline_t newline_mode (void) const
bool is_unix_mode (void) const
bool is_msdos_mode (void) const
bool is_macos_mode (void) const
bool is_native_mode (void) const
bool is_binary_mode (void) const
void set_integer_width (unsigned width=0)
unsigned integer_width (void) const
void set_integer_radix (unsigned radix=10)
unsigned integer_radix (void) const
void set_integer_display (radix_display_t display=radix_c_style_or_hash)
radix_display_t integer_display (void) const
void set_real_width (unsigned width=0)
unsigned real_width (void) const
void set_real_precision (unsigned width=6)
unsigned real_precision (void) const
void set_real_display (real_display_t display=display_mixed)
real_display_t real_display (void) const
bool put (int ch)
bool put (const char *)
bool put (const std::string &)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void flush (void)
operator bool (void) const
bool operator! (void) const
otext & operator<< (char)
otext & operator<< (signed char)
otext & operator<< (unsigned char)
otext & operator<< (const char *)
otext & operator<< (const std::string &)
otext & operator<< (const std::vector< std::string > &)
otext & operator<< (bool)
otext & operator<< (short)
otext & operator<< (unsigned short)
otext & operator<< (int)
otext & operator<< (unsigned int)
otext & operator<< (long)
otext & operator<< (unsigned long)
otext & operator<< (float)
otext & operator<< (double)
otext & operator<< (const void *)
otext & operator<< (manipulator_function)
otext & operator<< (itext &)
Additional Inherited Members
Public Types inherited from otext
enum newline_t {
binary_mode, unix_mode, msdos_mode, macos_mode,
native_mode = unix_mode
}
enum open_t { overwrite, append }
typedef void(* manipulator_function)(otext &)
Protected Attributes inherited from otext
obuff * m_buffer
Detailed Description
Definition at line 18 of file multiio.hpp.
Constructor & Destructor Documentation
omtext::omtext (void)
Definition at line 15 of file multiio.cpp.
                    :
   otext(new ombuff())
 {
 }
omtext::omtext (const otext & str)
Definition at line 20 of file multiio.cpp.
References add().
                                :
   otext(new ombuff())
 {
   add(str);
 }
omtext::omtext (const otext & str1, const otext & str2)
Definition at line 26 of file multiio.cpp.
References add().
                                                    :
   otext(new ombuff())
 {
   add(str1);
   add(str2);
 }
Member Function Documentation
unsigned omtext::add (const otext & str)
Definition at line 46 of file multiio.cpp.
References ombuff::add(), DEBUG_ASSERT, and otext::m_buffer.
Referenced by omtext(), and open().
 {
   ombuff* buf = dynamic_cast<ombuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf ? buf->add(str) : (unsigned)-1;
 }
unsigned omtext::device_count (void) const
Definition at line 60 of file multiio.cpp.
References ombuff::count(), DEBUG_ASSERT, and otext::m_buffer.
 {
   const ombuff* buf = dynamic_cast<const ombuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf ? buf->count() : 0;
 }
otext & omtext::device_get (unsigned i)
Definition at line 67 of file multiio.cpp.
References DEBUG_ASSERT, ombuff::device(), and otext::m_buffer.
 {
   ombuff* buf = dynamic_cast<ombuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf->device(i);
 }
const otext & omtext::device_get (unsigned i) const
Definition at line 74 of file multiio.cpp.
References DEBUG_ASSERT, ombuff::device(), and otext::m_buffer.
 {
   const ombuff* buf = dynamic_cast<const ombuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf->device(i);
 }
void omtext::open (const otext & str)
Definition at line 33 of file multiio.cpp.
References add(), and otext::open().
 {
   otext::open(new ombuff());
   add(str);
 }
void omtext::open (const otext & str1, const otext & str2)
Definition at line 39 of file multiio.cpp.
References add(), and otext::open().
 {
   otext::open(new ombuff());
   add(str1);
   add(str2);
 }
void omtext::remove (unsigned offset)
Definition at line 53 of file multiio.cpp.
References DEBUG_ASSERT, otext::m_buffer, and ombuff::remove().
 {
   ombuff* buf = dynamic_cast<ombuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   if (buf) buf->remove(offset);
 }
The documentation for this class was generated from the following files:
include/stlplus/multiio.hpp
include/stlplus/multiio.cpp