Visible: rcVideoTrackImpl Class Reference
rcVideoTrackImpl Class Reference
#include <include/visiCore/rc_videotrackimpl.h>
Public Member Functions
rcVideoTrackImpl (const char *tag, const char *name, const char *description, const char *displayFormat, uint32 sizeLimit)
virtual ~rcVideoTrackImpl ()
virtual uint32 segments ()
virtual rcSegmentImpl segment (uint32 index)
virtual void popSegment ()
virtual rcVideoSegmentIterator * getDataSegmentIterator (const rcTimestamp &pos)
virtual uint32 getSegmentCount (void)
virtual void writeValue (const rcTimestamp &timestamp, const rcRect &focus, const rcWindow *frame)
virtual void flush (void)
virtual rcWriter * down_cast ()
Public Member Functions inherited from rcVideoTrack
virtual ~rcVideoTrack ()
Public Member Functions inherited from rcVideoWriter
virtual ~rcVideoWriter ()
Public Member Functions inherited from rcTrackImpl
rcTrackImpl (rcTrackType trackType, rcWriterType writerType, const char *tag, const char *name, const char *description, const char *displayFormat, uint32 limit, rcTimestamp firstTime=-1.0)
virtual ~rcTrackImpl ()
virtual rcTrackType getTrackType (void)
virtual rcWriterType getWriterType (void)
virtual const char * getTag (void)
virtual const char * getName (void)
virtual const char * getDescription (void)
virtual uint32 getSizeLimit () const
virtual const char * getDisplayFormatString (void)
virtual rcTimestamp getTrackStart (void)
virtual void setTrackStart (const rcTimestamp &time)
virtual void setExportable (bool e)
virtual void setDescription (const char *text)
virtual void setName (const char *text)
virtual bool isExportable (void)
virtual rcTrackSemantics getSemantics (void)
virtual void setSemantics (const rcTrackSemantics &s)
virtual rcRect getAnalysisRect (void)
virtual void setAnalysisRect (const rcRect &f)
Public Member Functions inherited from rcTrack
virtual ~rcTrack ()
Public Member Functions inherited from rcWriter
virtual ~rcWriter ()
Private Member Functions
virtual void setWriterState (const rcTimestamp &time, rcRect focus, const rcWindow &frame)
void addSegment (const rcTimestamp &segmentLength)
Private Attributes
deque< rcVideoSegment > _segments
rcWindow _currentValue
Friends
class rcVideoSegmentIteratorImpl
Additional Inherited Members
Static Public Member Functions inherited from rcTrack
static rcTrackType type (const std::string &name)
static const std::string & name (rcTrackType type)
Protected Member Functions inherited from rcTrackImpl
rcTimestamp lastSegmentLength ()
rcTimestamp nextSegmentLength (const rcTimestamp &timestamp)
rcTimestamp nextSegmentStart ()
virtual void setWriterState (const rcTimestamp &time, rcRect focus)
void updateFirstTime (const rcTimestamp &timestamp)
Protected Attributes inherited from rcTrackImpl
rcMutex _mutex
rcTimestamp _currentLength
rcRect _currentFocus
uint32 _sizeLimit
rcTimestamp _firstTime
rcTimestamp _expStartTime
bool _isExportable
rcTrackSemantics _dataSemantics
rcRect _analysisFocus
Detailed Description
Definition at line 45 of file rc_videotrackimpl.h.
Constructor & Destructor Documentation
rcVideoTrackImpl::rcVideoTrackImpl (const char * tag, const char * name, const char * description, const char * displayFormat, uint32 sizeLimit)
Definition at line 170 of file rc_videotrackimpl.cpp.
References rcTrackImpl::_isExportable.
         : rcTrackImpl( eVideoTrack , eVideoWriter , tag , name , description, displayFormat, sizeLimit ),
           _currentValue( rcWindow() )
 {
     _isExportable = false;
 }
rcVideoTrackImpl::~rcVideoTrackImpl () virtual
Definition at line 178 of file rc_videotrackimpl.cpp.
 {
 }
Member Function Documentation
void rcVideoTrackImpl::addSegment (const rcTimestamp & segmentLength) private
Definition at line 262 of file rc_videotrackimpl.cpp.
References rcTrackImpl::_currentFocus, _currentValue, _segments, cZeroTime, endl(), rcSegmentImpl::length(), rcTrackImpl::nextSegmentStart(), rcTimestamp::secs(), segment(), and segments().
Referenced by flush(), and writeValue().
 {
     // Zero segment length is not allowed
     if ( segmentLength > cZeroTime ) {
         rcTimestamp startTime = nextSegmentStart();
 #ifdef DEBUG_LOG
         rcTimestamp cumLength = cZeroTime;
         for ( int32 i = segments() - 1; i >= 0; i-- )
             cumLength += segment( i ).length();
         if ( cumLength != startTime ) {
             rcTimestamp diff = cumLength - startTime;
             cerr << "Video addSegment mismatch: cumLength ";
             cerr << cumLength.secs() << " segStart " << startTime.secs() << " diff " << diff.secs() << endl;
         }
 #endif
         _segments.push_back( rcVideoSegment( startTime, segmentLength, _currentFocus, _currentValue ) );
     }
 }
rcWriter * rcVideoTrackImpl::down_cast () virtual
Implements rcVideoWriter.
Definition at line 249 of file rc_videotrackimpl.cpp.
 {
     return dynamic_cast<rcWriter*>( this );
 }
void rcVideoTrackImpl::flush (void) virtual
Implements rcVideoWriter.
Definition at line 238 of file rc_videotrackimpl.cpp.
References rcTrackImpl::_currentFocus, rcTrackImpl::_currentLength, _currentValue, rcTrackImpl::_mutex, addSegment(), rcTrackImpl::lastSegmentLength(), and setWriterState().
 {
     rcLock lock (_mutex);
     rcTimestamp lastLength = lastSegmentLength();
     // Add final segment with length equal to previous segment length
     addSegment( lastLength );
     // Update writer state
     setWriterState( _currentLength, _currentFocus, _currentValue );
 }
rcVideoSegmentIterator * rcVideoTrackImpl::getDataSegmentIterator (const rcTimestamp & pos) virtual
Implements rcVideoTrack.
Definition at line 211 of file rc_videotrackimpl.cpp.
References rcTrackImpl::_mutex, and rcVideoSegmentIteratorImpl.
 {
     return new rcVideoSegmentIteratorImpl( this , pos, _mutex );
 }
uint32 rcVideoTrackImpl::getSegmentCount (void) virtual
Implements rcVideoTrack.
Definition at line 217 of file rc_videotrackimpl.cpp.
References rcTrackImpl::_mutex, and _segments.
 {
     rcLock lock (_mutex);
     return _segments.size();
 }
void rcVideoTrackImpl::popSegment () virtual
Reimplemented from rcTrackImpl.
Definition at line 200 of file rc_videotrackimpl.cpp.
References _segments.
 {
     // We have hit the maximum size limit, we must prune oldest value
     // TODO: this wont work right until we use absolute timestamps instead of relative timestamps
     _segments.pop_front();
     // Try to compact container
     deque<rcVideoSegment>(_segments).swap(_segments);
 }
rcSegmentImpl rcVideoTrackImpl::segment (uint32 index) virtual
Reimplemented from rcTrackImpl.
Definition at line 191 of file rc_videotrackimpl.cpp.
References _segments, and cZeroTime.
Referenced by addSegment().
 {
     if ( index < _segments.size() )
         return _segments[index];
     else
         return rcSegmentImpl( cZeroTime, cZeroTime, rcRect() );
 }
uint32 rcVideoTrackImpl::segments (void) virtual
Reimplemented from rcTrackImpl.
Definition at line 185 of file rc_videotrackimpl.cpp.
References _segments.
Referenced by addSegment(), and rcVideoSegmentIteratorImpl::setCurrentValue().
 {
     return _segments.size();
 }
void rcVideoTrackImpl::setWriterState (const rcTimestamp & time, rcRect focus, const rcWindow & frame) private virtual
Definition at line 255 of file rc_videotrackimpl.cpp.
References _currentValue, and rcTrackImpl::setWriterState().
Referenced by flush(), and writeValue().
 {
     rcTrackImpl::setWriterState( time, focus );
     _currentValue = frame;
 }
void rcVideoTrackImpl::writeValue (const rcTimestamp & timestamp, const rcRect & focus, const rcWindow * frame) virtual
Implements rcVideoWriter.
Definition at line 225 of file rc_videotrackimpl.cpp.
References rcTrackImpl::_mutex, addSegment(), rcTrackImpl::nextSegmentLength(), setWriterState(), and rcTrackImpl::updateFirstTime().
 {
     if ( value ) {
         rcLock lock (_mutex);
         // Update first value time
         updateFirstTime( timestamp );
         // Add new segment
         addSegment( nextSegmentLength( timestamp ) );
         // Update write state
         setWriterState( timestamp, focus, *value );
     }
 }
Friends And Related Function Documentation
friend class rcVideoSegmentIteratorImpl friend
Definition at line 73 of file rc_videotrackimpl.h.
Referenced by getDataSegmentIterator().
Member Data Documentation
rcWindow rcVideoTrackImpl::_currentValue private
Definition at line 82 of file rc_videotrackimpl.h.
Referenced by addSegment(), flush(), and setWriterState().
deque<rcVideoSegment> rcVideoTrackImpl::_segments private
Definition at line 81 of file rc_videotrackimpl.h.
Referenced by addSegment(), getSegmentCount(), popSegment(), segment(), segments(), and rcVideoSegmentIteratorImpl::setCurrentValue().
The documentation for this class was generated from the following files:
include/visiCore/rc_videotrackimpl.h
src/visible/src/rc_videotrackimpl.cpp