Visible: rcVideoCaptureCtrlReader Class Reference
rcVideoCaptureCtrlReader Class Reference
#include <include/visiCore/rc_captureregs.h>
Public Member Functions
rcVideoCaptureCtrlReader ()
virtual ~rcVideoCaptureCtrlReader ()
uint32 getDecimationRate (void) const
int getSlidingWindowSize () const
rcAnalyzerResultOrigin getSlidingWindowOrigin () const
bool getSlidingWindowEnabled () const
bool getACIEnabled () const
rcSimilarator::rcEntropyDefinition getEntropyDefinition () const
int32 getGain (void) const
int32 getShutter (void) const
int32 getBinning (void) const
Protected Attributes
rcAtomicValue< uint32 > _decRate
rcAtomicValue< int > _slidingWindowSize
rcAtomicValue
< rcAnalyzerResultOrigin > _slidingWindowOrigin
rcAtomicValue< bool > _slidingWindowEnabled
rcAtomicValue< bool > _ACIEnabled
rcAtomicValue
< rcSimilarator::rcEntropyDefinition > _entropyDefinition
rcAtomicValue< int32 > _gain
rcAtomicValue< int32 > _shutter
rcAtomicValue< int32 > _binning
Detailed Description
Definition at line 24 of file rc_captureregs.h.
Constructor & Destructor Documentation
rcVideoCaptureCtrlReader::rcVideoCaptureCtrlReader () inline
Definition at line 27 of file rc_captureregs.h.
                              : _decRate(1), _slidingWindowSize(3),
     _slidingWindowOrigin(eAnalyzerResultOriginCenter),
         _slidingWindowEnabled(true), _ACIEnabled(false), _entropyDefinition(rcSimilarator::eACI),
                    _gain(0), _shutter(0), _binning (1)
   { }
virtual rcVideoCaptureCtrlReader::~rcVideoCaptureCtrlReader () inline virtual
Definition at line 33 of file rc_captureregs.h.
   { }
Member Function Documentation
bool rcVideoCaptureCtrlReader::getACIEnabled () const inline
Definition at line 48 of file rc_captureregs.h.
References _ACIEnabled, and rcAtomicValue< T >::getValue().
Referenced by operator<<().
   { bool x; return _ACIEnabled.getValue(x); }
int32 rcVideoCaptureCtrlReader::getBinning (void) const inline
Definition at line 60 of file rc_captureregs.h.
References _binning, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), operator<<(), and updateControl().
   { int32 x; return _binning.getValue(x); }
uint32 rcVideoCaptureCtrlReader::getDecimationRate (void) const inline
Definition at line 36 of file rc_captureregs.h.
References _decRate, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), operator<<(), rcEngineImpl::setSettingValue(), rcEngineImpl::setTimeLineRange(), and updateControl().
   { uint32 x; return _decRate.getValue(x); }
rcSimilarator::rcEntropyDefinition rcVideoCaptureCtrlReader::getEntropyDefinition () const inline
Definition at line 51 of file rc_captureregs.h.
References _entropyDefinition, and rcAtomicValue< T >::getValue().
Referenced by operator<<(), and rcEngineMovieCapture::run().
   { rcSimilarator::rcEntropyDefinition x;  return _entropyDefinition.getValue(x); }
int32 rcVideoCaptureCtrlReader::getGain (void) const inline
Definition at line 54 of file rc_captureregs.h.
References _gain, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), operator<<(), and updateControl().
   { int32 x; return _gain.getValue(x); }
int32 rcVideoCaptureCtrlReader::getShutter (void) const inline
Definition at line 57 of file rc_captureregs.h.
References _shutter, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), operator<<(), and updateControl().
   { int32 x; return _shutter.getValue(x); }
bool rcVideoCaptureCtrlReader::getSlidingWindowEnabled () const inline
Definition at line 45 of file rc_captureregs.h.
References _slidingWindowEnabled, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::isSettingEnabled(), and operator<<().
   { bool x; return _slidingWindowEnabled.getValue(x); }
rcAnalyzerResultOrigin rcVideoCaptureCtrlReader::getSlidingWindowOrigin () const inline
Definition at line 42 of file rc_captureregs.h.
References _slidingWindowOrigin, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), operator<<(), and rcEngineMovieCapture::run().
   { rcAnalyzerResultOrigin x; return _slidingWindowOrigin.getValue(x); }
int rcVideoCaptureCtrlReader::getSlidingWindowSize () const inline
Definition at line 39 of file rc_captureregs.h.
References _slidingWindowSize, and rcAtomicValue< T >::getValue().
Referenced by rcEngineImpl::getSettingValue(), operator<<(), and rcEngineMovieCapture::run().
   { int x; return _slidingWindowSize.getValue(x); }
Member Data Documentation
rcAtomicValue<bool> rcVideoCaptureCtrlReader::_ACIEnabled protected
Definition at line 69 of file rc_captureregs.h.
Referenced by rcVideoCaptureCtrl::ACIEnabled(), and getACIEnabled().
rcAtomicValue<int32> rcVideoCaptureCtrlReader::_binning protected
Definition at line 73 of file rc_captureregs.h.
Referenced by rcVideoCaptureCtrl::binning(), and getBinning().
rcAtomicValue<uint32> rcVideoCaptureCtrlReader::_decRate protected
Definition at line 65 of file rc_captureregs.h.
Referenced by rcVideoCaptureCtrl::decimationRate(), and getDecimationRate().
rcAtomicValue<rcSimilarator::rcEntropyDefinition> rcVideoCaptureCtrlReader::_entropyDefinition protected
Definition at line 70 of file rc_captureregs.h.
Referenced by rcVideoCaptureCtrl::entropyDefinition(), and getEntropyDefinition().
rcAtomicValue<int32> rcVideoCaptureCtrlReader::_gain protected
Definition at line 71 of file rc_captureregs.h.
Referenced by rcVideoCaptureCtrl::gain(), and getGain().
rcAtomicValue<int32> rcVideoCaptureCtrlReader::_shutter protected
Definition at line 72 of file rc_captureregs.h.
Referenced by getShutter(), and rcVideoCaptureCtrl::shutter().
rcAtomicValue<bool> rcVideoCaptureCtrlReader::_slidingWindowEnabled protected
Definition at line 68 of file rc_captureregs.h.
Referenced by getSlidingWindowEnabled(), and rcVideoCaptureCtrl::slidingWindowEnabled().
rcAtomicValue<rcAnalyzerResultOrigin> rcVideoCaptureCtrlReader::_slidingWindowOrigin protected
Definition at line 67 of file rc_captureregs.h.
Referenced by getSlidingWindowOrigin(), and rcVideoCaptureCtrl::slidingWindowOrigin().
rcAtomicValue<int> rcVideoCaptureCtrlReader::_slidingWindowSize protected
Definition at line 66 of file rc_captureregs.h.
Referenced by getSlidingWindowSize(), and rcVideoCaptureCtrl::slidingWindowSize().
The documentation for this class was generated from the following file:
include/visiCore/rc_captureregs.h