Visible: rcTimestamp Class Reference
rcTimestamp Class Reference
#include <include/util/rc_timestamp.h>
Public Member Functions
rcTimestamp (void)
rcTimestamp (const rcTimestamp &other)
rcTimestamp (double secs)
rcTimestamp (int64 timestamp)
double secs (void) const
rcTimestamp & operator+= (const rcTimestamp &other)
rcTimestamp & operator-= (const rcTimestamp &other)
bool operator== (const rcTimestamp &other) const
bool operator!= (const rcTimestamp &other) const
bool operator< (const rcTimestamp &other) const
bool operator<= (const rcTimestamp &other) const
bool operator> (const rcTimestamp &other) const
bool operator>= (const rcTimestamp &other) const
rcTimestamp operator- (void) const
std::string localtime () const
Static Public Member Functions
static rcTimestamp now (void)
Private Attributes
int64 _timestamp
Friends
class rcMovieFileFormat
class rcMovieFileFormat2
class rcEngineMovieSaver
class rcVideoCache
class rcGenMovieFile
bool rfCreateReifyMovie (rcVideoCache *cache, char *destFile, uint32 firstIndex, uint32 frameCount, uint32 offset, uint32 period, uint32 newFormat)
Detailed Description
Definition at line 59 of file rc_timestamp.h.
Constructor & Destructor Documentation
rcTimestamp::rcTimestamp (void) inline
Definition at line 63 of file rc_timestamp.h.
 : _timestamp (0) {}
rcTimestamp::rcTimestamp (const rcTimestamp & other) inline
Definition at line 66 of file rc_timestamp.h.
References _timestamp.
     {
         _timestamp = other._timestamp;
     }
rcTimestamp::rcTimestamp (double secs) inline
Definition at line 72 of file rc_timestamp.h.
 :  _timestamp (convertSecondsToTimestamp( secs )) {}
rcTimestamp::rcTimestamp (int64 timestamp) inline
Definition at line 75 of file rc_timestamp.h.
 : _timestamp (timestamp) {}
Member Function Documentation
std::string rcTimestamp::localtime () const
Definition at line 66 of file rc_timestamp.cpp.
References secs().
Referenced by rcCSVExporter::exportExperiment(), rcMovieFileOrgExt::log(), rcMovieFileConvExt::log(), rcBatchExperimentObserver::notifyError(), rcBatchExperimentObserver::notifyStatus(), rcBatchExperimentObserver::notifyWarning(), rcEngineMovieCapture::run(), and yourDisplayCallback().
 {
     std::string localTime;
     time_t seconds = static_cast<time_t>(secs() + 0.5);
     char buf[64];
     if ( ctime_r( &seconds, buf ) ) {
         localTime = buf;
         // Remove trailing NL
         if ( !localTime.empty() )
             if ( localTime[localTime.size()-1] == '\n' )
                 localTime[localTime.size()-1] = ' ';
     }
     return localTime;
 }
static rcTimestamp rcTimestamp::now (void) inline static
Definition at line 78 of file rc_timestamp.h.
References getCurrentTimestamp().
Referenced by rcEngineImpl::analyzeFocusArea(), rcXMLParser::endDocument(), rcCSVExporter::exportExperiment(), rcNativeExporter::exportExperiment(), rcEngineImpl::frameInterrupt(), rcNativeImporter::importExperiment(), rcEngineImpl::loadFrames(), main(), rcUnitTest::makeTmpName(), rcEngineImpl::makeTmpName(), MungGrabDataProc(), rcTimingInfo::nextPass(), rcBatchExperimentObserver::notifyError(), rcBatchExperimentObserver::notifyStatus(), rcBatchExperimentObserver::notifyWarning(), rcEngineImpl::processCapturedData(), processControlRequests(), rcConversionProgress::progress(), rcEngineProgress::progress(), rcModelProgress::progress(), rcWindow::randomFill(), rcUnitTest::randomSeed(), rcTimingInfo::rcTimingInfo(), rfMakeTmpFileName(), rcEngineMovieCapture::run(), rcEngineImpl::saveFrames(), rcXMLParser::startDocument(), rcTimingInfo::touch(), rcMonitor::updateCachedImage(), rcTimeline::updateDisplay(), and yourDisplayCallback().
 {  return (rcTimestamp( getCurrentTimestamp() ) ); }
bool rcTimestamp::operator!= (const rcTimestamp & other) const inline
Definition at line 107 of file rc_timestamp.h.
References _timestamp.
     {
         return _timestamp != other._timestamp;
     }
rcTimestamp& rcTimestamp::operator+= (const rcTimestamp & other) inline
Definition at line 87 of file rc_timestamp.h.
References _timestamp.
     {
         _timestamp += other._timestamp;
         return *this;
     }
rcTimestamp rcTimestamp::operator- (void) const inline
Definition at line 137 of file rc_timestamp.h.
     {
         return rcTimestamp( -_timestamp );
     }
rcTimestamp& rcTimestamp::operator-= (const rcTimestamp & other) inline
Definition at line 94 of file rc_timestamp.h.
References _timestamp.
     {
         _timestamp -= other._timestamp;
         return *this;
     }
bool rcTimestamp::operator< (const rcTimestamp & other) const inline
Definition at line 113 of file rc_timestamp.h.
References _timestamp.
     {
         return _timestamp < other._timestamp;
     }
bool rcTimestamp::operator<= (const rcTimestamp & other) const inline
Definition at line 119 of file rc_timestamp.h.
References _timestamp.
     {
         return _timestamp <= other._timestamp;
     }
bool rcTimestamp::operator== (const rcTimestamp & other) const inline
Definition at line 101 of file rc_timestamp.h.
References _timestamp.
     {
         return _timestamp == other._timestamp;
     }
bool rcTimestamp::operator> (const rcTimestamp & other) const inline
Definition at line 125 of file rc_timestamp.h.
References _timestamp.
     {
         return _timestamp > other._timestamp;
     }
bool rcTimestamp::operator>= (const rcTimestamp & other) const inline
Definition at line 131 of file rc_timestamp.h.
References _timestamp.
     {
         return _timestamp >= other._timestamp;
     }
double rcTimestamp::secs (void) const inline
Definition at line 81 of file rc_timestamp.h.
References convertTimestampToSeconds().
Referenced by rcVideoTrackImpl::addSegment(), rcFpsCalculator::addTime(), rcMovieConverterToQT::addVideoSamplesToMedia(), rcEngineImpl::analyzeFocusArea(), rcEngineMovieSaver::closeHdlr(), rcMovieConverterToRfy::createRfyMovie(), rcKinetoscope::currentTime(), rcXMLParser::endDocument(), rcCSVExporter::exportExperiment(), rcNativeExporter::exportExperiment(), rcKinetoscope::frame(), rcMonitor::gatherDevelopmentTrackData(), rcNativeImporter::importExperiment(), rcTimeline::keyRangeScaleEvent(), rcEngineImpl::loadFrames(), localtime(), main(), rcUnitTest::makeTmpName(), rcEngineImpl::makeTmpName(), rcTimeline::mouseMoveEvent(), MungGrabDataProc(), rcEngineImpl::muscleTracker(), rcTimeline::paintScalarTrack(), rcTimeline::paintTimeline(), rcTimeline::pixelToTime(), rcEngineImpl::processCapturedData(), rcModelProgress::progress(), rcWindow::randomFill(), rcUnitTest::randomSeed(), rcVisualFunction::rcVisualFunction(), rfGenerateTimeline(), rfMakeTmpFileName(), rcEngineImpl::saveFrames(), rcEngineMovieSaver::saveHdlr(), rcEngineImpl::setSettingValue(), rcEngineMoviePlayback::setupTimeCtrlPlayback(), rcModelDomain::timerTick(), rcControlPanel::timestampToString(), rcTimingInfo::touch(), rcControlPanel::updateCursorTime(), rcKinetoscope::updateProcessingTime(), and yourDisplayCallback().
     {
         return convertTimestampToSeconds( _timestamp );
     }
Friends And Related Function Documentation
friend class rcEngineMovieSaver friend
Definition at line 148 of file rc_timestamp.h.
friend class rcGenMovieFile friend
Definition at line 150 of file rc_timestamp.h.
friend class rcMovieFileFormat friend
Definition at line 146 of file rc_timestamp.h.
friend class rcMovieFileFormat2 friend
Definition at line 147 of file rc_timestamp.h.
friend class rcVideoCache friend
Definition at line 149 of file rc_timestamp.h.
bool rfCreateReifyMovie (rcVideoCache * cache, char * destFile, uint32 firstIndex, uint32 frameCount, uint32 offset, uint32 period, uint32 newFormat) friend
Member Data Documentation
int64 rcTimestamp::_timestamp private
Definition at line 157 of file rc_timestamp.h.
Referenced by rcGenMovieFile::addFrame(), operator!=(), operator+=(), operator-=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and rcTimestamp().
The documentation for this class was generated from the following files:
include/util/rc_timestamp.h
src/util/code/rc_timestamp.cpp