Visible: rcRunnable Class Reference
rcRunnable Class Reference abstract
#include <include/util/rc_thread.h>
Public Member Functions
rcRunnable ()
virtual ~rcRunnable ()
virtual void run (void)=0
void requestSeppuku ()
void clearSeppuku ()
Protected Member Functions
bool seppukuRequested ()
Private Attributes
atomic< bool > _seppuku
Detailed Description
Definition at line 37 of file rc_thread.h.
Constructor & Destructor Documentation
rcRunnable::rcRunnable () inline
Definition at line 40 of file rc_thread.h.
 : _seppuku(false) { }
virtual rcRunnable::~rcRunnable () inline virtual
Definition at line 42 of file rc_thread.h.
 {}
Member Function Documentation
void rcRunnable::clearSeppuku () inline
Definition at line 51 of file rc_thread.h.
 { _seppuku = false; }
void rcRunnable::requestSeppuku () inline
Definition at line 48 of file rc_thread.h.
Referenced by rcVideoCache::~rcVideoCache().
 { _seppuku = true; }
virtual void rcRunnable::run (void) pure virtual
Implemented in rcVideoCache::rcVideoCachePrefetchUnit, rcEngineAnalyzer, rcEngineImporter, rcThread, rcEngineMovieCapture, rcEngineMoviePlayback, and rcEngineMovieSaver.
bool rcRunnable::seppukuRequested () inline protected
Definition at line 55 of file rc_thread.h.
Referenced by rcEngineMovieSaver::delayHdlr(), rcEngineMovieSaver::doneHdlr(), rcEngineMoviePlayback::run(), rcEngineMovieCapture::run(), and rcEngineMovieSaver::waitHdlr().
 { return _seppuku; }
Member Data Documentation
atomic<bool> rcRunnable::_seppuku private
Definition at line 58 of file rc_thread.h.
The documentation for this class was generated from the following file:
include/util/rc_thread.h