Visible: rcDefGeneratePixel Class Reference
rcDefGeneratePixel Class Reference
#include <include/visual/rc_def_generators.h>
Public Member Functions
rcDefGeneratePixel ()
virtual ~rcDefGeneratePixel ()
double genPixel (const rcAffineWindow *src, double x, double y)
Public Member Functions inherited from rcGeneratePixel
rcGeneratePixel ()
virtual ~rcGeneratePixel ()
Detailed Description
Definition at line 22 of file rc_def_generators.h.
Constructor & Destructor Documentation
rcDefGeneratePixel::rcDefGeneratePixel () inline
Definition at line 26 of file rc_def_generators.h.
 {}
virtual rcDefGeneratePixel::~rcDefGeneratePixel () inline virtual
Definition at line 28 of file rc_def_generators.h.
 {}
Member Function Documentation
double rcDefGeneratePixel::genPixel (const rcAffineWindow * src, double x, double y) inline virtual
Implements rcGeneratePixel.
Definition at line 30 of file rc_def_generators.h.
References rcWindow::depth(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcPixelDouble, and rmAssert.
   {
     rmAssert(src && (src->depth() <= rcPixelDouble));
     if (src->depth() == rcPixelDouble)
       return src->getDoublePixel((int32)(x + 0.5), (int32)(y + 0.5));
     return (double)(src->getPixel((int32)(x + 0.5), (int32)(y + 0.5)));
   }
The documentation for this class was generated from the following file:
include/visual/rc_def_generators.h