Visible: rcSettingInfo Class Reference
rcSettingInfo Class Reference
#include <include/baseUI/rc_setting.h>
Public Types
enum {
eCurrentSpeedMask = 0x00FFFFFF, eCurrentStateMask = 0xE0000000, eCurrentStateRev = 0x80000000, eCurrentStateFwd = 0x40000000,
eCurrentStateStopped = 0x20000000
}
Public Member Functions
rcSettingInfo (void)
rcSettingInfo (rcSettingSource *source, const rcSettingInfoSpec *spec)
const char * getTag (void) const
const char * getDisplayName (void) const
const char * getDescription (void) const
const void * getXArgs (void) const
const bool isEnabled (void) const
const bool isEditable (void) const
const bool isPersistable (void) const
const int getDisplayType (void) const
const int getGroupId (void) const
const int getNChoices (void) const
const rcSettingChoice getChoice (int choiceNo) const
const rcValue getValue (void) const
void setValue (const rcValue &value) const
const rcSettingInfo & operator= (const rcValue &value) const
operator const rcValue () const
operator int () const
operator float () const
operator bool () const
operator std::string () const
Private Member Functions
void assertInitialized (void) const
Private Attributes
rcSettingSource * _source
const rcSettingInfoSpec * _spec
int _nChoices
Detailed Description
Definition at line 106 of file rc_setting.h.
Member Enumeration Documentation
anonymous enum
Enumerator
eCurrentSpeedMask
eCurrentStateMask
eCurrentStateRev
eCurrentStateFwd
eCurrentStateStopped
Definition at line 172 of file rc_setting.h.
        {
     eCurrentSpeedMask     = 0x00FFFFFF,
     eCurrentStateMask     = 0xE0000000,
     eCurrentStateRev      = 0x80000000,
     eCurrentStateFwd      = 0x40000000,
     eCurrentStateStopped  = 0x20000000
   };
Constructor & Destructor Documentation
rcSettingInfo::rcSettingInfo (void)
Definition at line 126 of file rc_setting.cpp.
 {
   _source = 0;
   _spec = 0;
 }
rcSettingInfo::rcSettingInfo (rcSettingSource * source, const rcSettingInfoSpec * spec)
Definition at line 133 of file rc_setting.cpp.
References rcSettingInfoSpec::_choices, and rcSettingChoice::_text.
 {
   _source = source;
   _spec = spec;
   _nChoices = 0;
   if (spec->_choices != 0)
     {
       for ( ; ; _nChoices++)
     {
       const rcSettingChoice* choice = &(spec->_choices[ _nChoices ]);
       if (choice->_text == 0)
         break;
     }
     }
 }
Member Function Documentation
void rcSettingInfo::assertInitialized (void) const private
Definition at line 232 of file rc_setting.cpp.
 {
   if ((_source == 0) || (_spec == 0))
     throw general_exception( "rcSettingInfo::assertInitialized failed" );
 }
const rcSettingChoice rcSettingInfo::getChoice (int choiceNo) const
Definition at line 211 of file rc_setting.cpp.
Referenced by rcFramerateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::choiceSelected(), rcNumericChoiceSettingWidget::choiceSelected(), rcTextChoiceSettingWidget::choiceSelected(), rcRateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::findChoice(), rcFramerateChoiceSettingWidget::findChoice(), rcTextChoiceSettingWidget::findChoice(), rcNumericChoiceSettingWidget::findChoice(), rcRateChoiceSettingWidget::findChoice(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcRadioChoiceSettingWidget::rcRadioChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), and rcTextChoiceSettingWidget::settingChanged().
 {
   if ((choiceNo < 0) || (choiceNo >= _nChoices))
     throw general_exception( "rcSettingInfo::getChoice: index out-of-bounds" );
   return _spec->_choices[ choiceNo ];
 }
const char * rcSettingInfo::getDescription (void) const
Definition at line 163 of file rc_setting.cpp.
Referenced by rcCheckboxSettingWidget::rcCheckboxSettingWidget(), rcFileChoiceSettingWidget::rcFileChoiceSettingWidget(), rcFileSaveSettingWidget::rcFileSaveSettingWidget(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcPlaybackSettingWidget::rcPlaybackSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcRectSettingWidget::rcRectSettingWidget(), rcSpinboxSettingWidget::rcSpinboxSettingWidget(), rcTextAreaSettingWidget::rcTextAreaSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), rcTextLineSettingWidget::rcTextLineSettingWidget(), and rcThumbWheelSettingWidget::rcThumbWheelSettingWidget().
 {
   return _spec->_description;
 }
const char * rcSettingInfo::getDisplayName (void) const
Definition at line 157 of file rc_setting.cpp.
Referenced by rcFileChoiceSettingWidget::directoryBrowse(), rcSettingCategory::dump(), rcCSVExporter::exportExperiment(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcSettingWidget::rcSettingWidget(), and rcTextChoiceSettingWidget::rcTextChoiceSettingWidget().
 {
   return _spec->_name;
 }
const int rcSettingInfo::getDisplayType (void) const
Definition at line 193 of file rc_setting.cpp.
Referenced by rcFileChoiceSettingWidget::browseRequest(), rcFileChoiceSettingWidget::imageImport(), rcFileChoiceSettingWidget::movieImport(), rcSettingPage::rcSettingPage(), rcFileChoiceSettingWidget::stkImport(), and rcFileChoiceSettingWidget::tifDirImport().
 {
   return _spec->_displayType;
 }
const int rcSettingInfo::getGroupId (void) const
Definition at line 199 of file rc_setting.cpp.
Referenced by rcSettingPage::rcSettingPage().
 {
   return _spec->_gid;
 }
const int rcSettingInfo::getNChoices (void) const
Definition at line 205 of file rc_setting.cpp.
Referenced by rcFramerateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::choiceSelected(), rcTextChoiceSettingWidget::choiceSelected(), rcNumericChoiceSettingWidget::choiceSelected(), rcRateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::findChoice(), rcFramerateChoiceSettingWidget::findChoice(), rcNumericChoiceSettingWidget::findChoice(), rcTextChoiceSettingWidget::findChoice(), rcRateChoiceSettingWidget::findChoice(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcRadioChoiceSettingWidget::rcRadioChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), rcFramerateChoiceSettingWidget::settingChanged(), rcMenuChoiceSettingWidget::settingChanged(), rcNumericChoiceSettingWidget::settingChanged(), rcTextChoiceSettingWidget::settingChanged(), and rcRateChoiceSettingWidget::settingChanged().
 {
   return _nChoices;
 }
const char * rcSettingInfo::getTag (void) const
Definition at line 151 of file rc_setting.cpp.
Referenced by rcFileSaveSettingWidget::browseRequest(), rcEngineBaseImpl::checkSettings(), rcFileChoiceSettingWidget::directoryBrowse(), rcNativeImporter::findSetting(), rcNativeExporter::produceSettings(), rcCheckboxSettingWidget::rcCheckboxSettingWidget(), rcFileChoiceSettingWidget::rcFileChoiceSettingWidget(), rcFileSaveSettingWidget::rcFileSaveSettingWidget(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcTextAreaSettingWidget::rcTextAreaSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), rcTextLineSettingWidget::rcTextLineSettingWidget(), rcRadioChoiceSettingWidget::settingChanged(), and rcMenuChoiceSettingWidget::settingChanged().
 {
   return _spec->_tag;
 }
const rcValue rcSettingInfo::getValue (void) const
Definition at line 220 of file rc_setting.cpp.
Referenced by rcFileSaveSettingWidget::browseRequest(), rcFileChoiceSettingWidget::directoryBrowse(), rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcSettingCategory::dump(), rcCSVExporter::exportExperiment(), rcNativeExporter::produceSettings(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), rcExperimentDomainImpl::saveExperiment(), rcRadioChoiceSettingWidget::settingChanged(), rcTextAreaSettingWidget::settingChanged(), rcCheckboxSettingWidget::settingChanged(), rcTextLineSettingWidget::settingChanged(), rcFramerateChoiceSettingWidget::settingChanged(), rcMenuChoiceSettingWidget::settingChanged(), rcRectSettingWidget::settingChanged(), rcPlaybackSettingWidget::settingChanged(), rcFileSaveSettingWidget::settingChanged(), rcFileChoiceSettingWidget::settingChanged(), rcNumericChoiceSettingWidget::settingChanged(), rcTextChoiceSettingWidget::settingChanged(), rcThumbWheelSettingWidget::settingChanged(), rcSpinboxSettingWidget::settingChanged(), rcRateChoiceSettingWidget::settingChanged(), rcMonitor::settingChanged(), rcFileChoiceSettingWidget::singleFileBrowse(), rcCheckboxSettingWidget::valueChanged(), and rcThumbWheelSettingWidget::valueChanged().
 {
   return _source->getSettingValue( _spec->_id );
 }
const void * rcSettingInfo::getXArgs (void) const
Definition at line 169 of file rc_setting.cpp.
Referenced by rcSpinboxSettingWidget::rcSpinboxSettingWidget(), rcTextAreaSettingWidget::rcTextAreaSettingWidget(), and rcThumbWheelSettingWidget::rcThumbWheelSettingWidget().
 {
   return _spec->_xArgs;
 }
const bool rcSettingInfo::isEditable (void) const
Definition at line 181 of file rc_setting.cpp.
Referenced by rcPlaybackSettingWidget::settingChanged(), and rcSettingWidget::updateWidgetState().
 {
   return _source->isSettingEditable( _spec->_id );
 }
const bool rcSettingInfo::isEnabled (void) const
Definition at line 175 of file rc_setting.cpp.
Referenced by rcPlaybackSettingWidget::settingChanged(), and rcSettingWidget::updateWidgetState().
 {
   return _source->isSettingEnabled( _spec->_id );
 }
const bool rcSettingInfo::isPersistable (void) const
Definition at line 187 of file rc_setting.cpp.
Referenced by rcCSVExporter::exportExperiment(), and rcNativeExporter::produceSettings().
 {
   return _source->isSettingPersistable( _spec->_id );
 }
rcSettingInfo::operator bool () const inline
Definition at line 167 of file rc_setting.h.
 { return getValue(); }
rcSettingInfo::operator const rcValue () const inline
Definition at line 158 of file rc_setting.h.
 { return getValue(); }
rcSettingInfo::operator float () const inline
Definition at line 164 of file rc_setting.h.
 { return getValue(); }
rcSettingInfo::operator int () const inline
Definition at line 161 of file rc_setting.h.
 { return getValue(); }
rcSettingInfo::operator std::string () const inline
Definition at line 170 of file rc_setting.h.
 { return getValue(); }
const rcSettingInfo& rcSettingInfo::operator= (const rcValue & value) const inline
Definition at line 155 of file rc_setting.h.
 { setValue( value ); return *this; }
void rcSettingInfo::setValue (const rcValue & value) const
Definition at line 226 of file rc_setting.cpp.
Referenced by rcFileSaveSettingWidget::browseRequest(), rcRadioChoiceSettingWidget::choiceSelected(), rcFramerateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::choiceSelected(), rcTextChoiceSettingWidget::choiceSelected(), rcNumericChoiceSettingWidget::choiceSelected(), rcRateChoiceSettingWidget::choiceSelected(), rcFileChoiceSettingWidget::directoryBrowse(), rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), rcPlaybackSettingWidget::fwdVideo(), rcFramerateChoiceSettingWidget::intervalChanged(), rcTimeline::keyPressEvent(), rcFileChoiceSettingWidget::multiFileBrowse(), rcPlaybackSettingWidget::revVideo(), rcNativeImporter::setSettingValue(), rcFramerateChoiceSettingWidget::settingChanged(), rcRectSettingWidget::settingChanged(), rcNumericChoiceSettingWidget::settingChanged(), rcTextChoiceSettingWidget::settingChanged(), rcRateChoiceSettingWidget::settingChanged(), rcFileChoiceSettingWidget::singleFileBrowse(), rcPlaybackSettingWidget::stopVideo(), rcTextAreaSettingWidget::valueChanged(), rcTextLineSettingWidget::valueChanged(), rcCheckboxSettingWidget::valueChanged(), rcRectSettingWidget::valueChanged(), rcFileSaveSettingWidget::valueChanged(), rcFileChoiceSettingWidget::valueChanged(), rcPlaybackSettingWidget::valueChanged(), rcThumbWheelSettingWidget::valueChanged(), and rcSpinboxSettingWidget::valueChanged().
 {
   _source->setSettingValue( _spec->_id , value );
 }
Member Data Documentation
int rcSettingInfo::_nChoices private
Definition at line 186 of file rc_setting.h.
rcSettingSource* rcSettingInfo::_source private
Definition at line 184 of file rc_setting.h.
const rcSettingInfoSpec* rcSettingInfo::_spec private
Definition at line 185 of file rc_setting.h.
The documentation for this class was generated from the following files:
include/baseUI/rc_setting.h
src/baseUI/rc_setting.cpp