Visible: rcFramerateChoiceSettingWidget Class Reference
rcFramerateChoiceSettingWidget Class Reference
#include <include/visUI/rc_frameratechoicesettingwidget.h>
Public Slots
void choiceSelected (int choiceValue)
void settingChanged (void)
void settingChanged (const QString &value)
void intervalChanged (const QString &value)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcFramerateChoiceSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcFramerateChoiceSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Member Functions
int findChoice (float value)
Private Attributes
QComboBox * _widget
rcLineEdit * _framerateWidget
rcLineEdit * _intervalWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 9 of file rc_frameratechoicesettingwidget.h.
Constructor & Destructor Documentation
rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 24 of file rc_frameratechoicesettingwidget.cpp.
References _framerateWidget, _intervalWidget, _widget, cFrameRateWidth, choiceSelected(), cUIsettingLabelSpacing, cUIsettingLabelWidth, cUIWordBreakAlignment, rcSettingInfo::getChoice(), rcSettingInfo::getDescription(), rcSettingInfo::getDisplayName(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingInfo::getTag(), rcSettingChoice::getText(), rcSettingInfo::getValue(), intervalChanged(), rcSettingWidget::mSetting, and settingChanged().
                                                                                                :
         rcSettingWidget( parent, setting, false )
 {
     // We create our own laytout without using base class layout
     Q3BoxLayout* vLayout = new Q3VBoxLayout( this );
     Q3BoxLayout* layout = new Q3HBoxLayout( vLayout );
     QLabel* label = new QLabel( setting.getDisplayName() , this );
     label->setFixedWidth( cUIsettingLabelWidth );
     label->setAlignment( cUIWordBreakAlignment );
     layout->addWidget( label );
     layout->addSpacing( cUIsettingLabelSpacing );
     _widget = new QComboBox(false,  this , setting.getTag() );
     int nChoices = setting.getNChoices();
     for (int i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = setting.getChoice( i );
         QString text( choice.getText() );
         // Add one space before text for better layout
         _widget->insertItem( QString( " %1" )
                              .arg( text ) );
     }
     layout->addWidget( _widget );
     layout->addSpacing( 10 );
     QToolTip::add( _widget , setting.getDescription() );
     // A text widget for arbitrary frame rates
     _framerateWidget = new rcLineEdit( this , setting.getTag() );
     _framerateWidget->setFixedWidth( cFrameRateWidth );
     QToolTip::add( _framerateWidget , setting.getDescription() );
     float value = mSetting.getValue();
     _framerateWidget->setText( QString( "%1" )
                                .arg( value ) );
     layout->addWidget( _framerateWidget );
     layout->addStretch();
     vLayout->addSpacing( 10 );
     // A text widget for arbitrary frame intervals
     // Frame interval in seconds is 1/framerate
     layout = new Q3HBoxLayout( vLayout );
     label = new QLabel( "Frame interval (seconds)" , this );
     label->setFixedWidth( cUIsettingLabelWidth );
     label->setAlignment( Qt::AlignRight | Qt::AlignVCenter | cUIWordBreakAlignment );
     layout->addWidget( label );
     layout->addSpacing( cUIsettingLabelSpacing );
     _intervalWidget = new rcLineEdit( this , "frame interval" );
     _intervalWidget->setFixedWidth( cFrameRateWidth );
     QToolTip::add( _intervalWidget , "Sets the input frame interval" );
     value = mSetting.getValue();
     value = 1 / value;
     _intervalWidget->setText( QString( "%1" )
                               .arg( value ) );
     layout->addWidget( _intervalWidget );
     layout->addStretch();
     // update the combo box with the current value of the setting.
     settingChanged();
     connect( _widget , SIGNAL( activated( int ) ) , this , SLOT( choiceSelected( int ) ) );
     connect( _intervalWidget , SIGNAL( textCommited( const QString& ) ) ,
              this    , SLOT( intervalChanged( const QString& ) ) );
     connect( _framerateWidget , SIGNAL( textCommited( const QString& ) ) ,
              this    , SLOT( settingChanged( const QString& ) ) );
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
}
rcFramerateChoiceSettingWidget::~rcFramerateChoiceSettingWidget ()
Definition at line 103 of file rc_frameratechoicesettingwidget.cpp.
References _framerateWidget, _intervalWidget, and _widget.
 {
     QToolTip::remove( _widget );
     QToolTip::remove( _framerateWidget );
     QToolTip::remove( _intervalWidget );
 }
Member Function Documentation
void rcFramerateChoiceSettingWidget::choiceSelected (int choiceValue) slot
Definition at line 114 of file rc_frameratechoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcSettingChoice::getFloatValue(), rcModelDomain::getModelDomain(), rcSettingInfo::getNChoices(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcFramerateChoiceSettingWidget().
 {
     int nChoices = mSetting.getNChoices();
     if ((choiceIndex >= 0) && (choiceIndex < nChoices))
     {
         rcSettingChoice choice = mSetting.getChoice( choiceIndex );
         mSetting.setValue( choice.getFloatValue() );
     }
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
int rcFramerateChoiceSettingWidget::findChoice (float value) private
Definition at line 189 of file rc_frameratechoicesettingwidget.cpp.
References rcSettingInfo::getChoice(), rcSettingChoice::getFloatValue(), rcSettingInfo::getNChoices(), and rcSettingWidget::mSetting.
Referenced by settingChanged().
 {
     int nChoices = mSetting.getNChoices();
     int i;
     for (i = 0; i < nChoices; i++)
     {
         rcSettingChoice choice = mSetting.getChoice( i );
         if (choice.getFloatValue() == value)
             break;
     }
     return i;
 }
void rcFramerateChoiceSettingWidget::intervalChanged (const QString & value) slot
Definition at line 169 of file rc_frameratechoicesettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcFramerateChoiceSettingWidget().
 {
     bool ok = false;
     float currentValue = value.toFloat( &ok );
     if ( ok && currentValue > 0 ) {
         // Use interval value to set frame rate
         // TODO: frame rate does not remain accurate if frame interval is
         // several minutes. Higher accuracy needed.
         currentValue = 1.0 / currentValue;
         mSetting.setValue( currentValue );
     } else {
         // Illegal value, revert to previous value
     }
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
void rcFramerateChoiceSettingWidget::settingChanged (void) slot
Definition at line 129 of file rc_frameratechoicesettingwidget.cpp.
References _framerateWidget, _intervalWidget, _widget, findChoice(), rcSettingInfo::getNChoices(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, and rcSettingWidget::updateWidgetState().
Referenced by rcFramerateChoiceSettingWidget().
 {
     float currentValue = mSetting.getValue();
     int nChoices = mSetting.getNChoices();
     int i = findChoice( currentValue );
     if ( i >= nChoices ) {
         // find "custom" value 0
         i = findChoice( 0 );
     }
     if (i < nChoices)
         _widget->setCurrentItem( i );
     _framerateWidget->setText( QString( "%1" )
                           .arg( currentValue ) );
     _intervalWidget->setText( QString( "%1" )
                               .arg( 1.0/currentValue ) );
     // Update visibility/editability
     updateWidgetState();
 }
void rcFramerateChoiceSettingWidget::settingChanged (const QString & value) slot
Definition at line 153 of file rc_frameratechoicesettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
 {
     bool ok = false;
     float currentValue = value.toFloat( &ok );
     if ( ok && currentValue > 0 ) {
         mSetting.setValue( currentValue );
     } else {
         // Illegal value, revert to previous value
     }
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
rcLineEdit* rcFramerateChoiceSettingWidget::_framerateWidget private
Definition at line 32 of file rc_frameratechoicesettingwidget.h.
Referenced by rcFramerateChoiceSettingWidget(), settingChanged(), and ~rcFramerateChoiceSettingWidget().
rcLineEdit* rcFramerateChoiceSettingWidget::_intervalWidget private
Definition at line 33 of file rc_frameratechoicesettingwidget.h.
Referenced by rcFramerateChoiceSettingWidget(), settingChanged(), and ~rcFramerateChoiceSettingWidget().
QComboBox* rcFramerateChoiceSettingWidget::_widget private
Definition at line 31 of file rc_frameratechoicesettingwidget.h.
Referenced by rcFramerateChoiceSettingWidget(), settingChanged(), and ~rcFramerateChoiceSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_frameratechoicesettingwidget.h
src/visible/qt/rc_frameratechoicesettingwidget.cpp