Visible: rcControlPanel Class Reference
rcControlPanel Class Reference
#include <include/visUI/rc_controlpanel.h>
Public Slots
void updateElapsedTime (const rcTimestamp &time)
void updateCursorTime (const rcTimestamp &time)
void updateState (rcExperimentState state)
void updateAnalysisRect (const rcRect &rect)
void settingChanged ()
void inputSource (int i)
void updateCursorTime ()
void updateSelectionState (bool trueIsSelect)
Public Member Functions
rcControlPanel (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
~rcControlPanel ()
Private Member Functions
QString timestampToString (const rcTimestamp &time)
Private Attributes
QLabel * _elapsedTime
QLabel * _cursorTime
QPushButton * _startButton
QPushButton * _stopButton
QPushButton * _processButton
QPushButton * _stopAnalysisButton
rcRect _analysisRect
rcExperimentState _lastState
bool _selectionState
Detailed Description
Definition at line 14 of file rc_controlpanel.h.
Constructor & Destructor Documentation
rcControlPanel::rcControlPanel (QWidget * parent = 0, const char * name = 0, Qt::WFlags f = 0)
Definition at line 150 of file rc_controlpanel.cpp.
References _cursorTime, _elapsedTime, _lastState, _processButton, _selectionState, _startButton, _stopAnalysisButton, _stopButton, eExperimentEmpty, rcModelDomain::getModelDomain(), inputSource(), rcUNUSED, settingChanged(), timestampToString(), updateAnalysisRect(), updateCursorTime(), updateElapsedTime(), updateSelectionState(), and updateState().
     : Q3Frame( parent, name )
 {
     rcUNUSED( f );
     _lastState = eExperimentEmpty;
     _selectionState = false;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     // Make the top-level layout; a vertical box to contain all widgets
     // and sub-layouts.
     Q3BoxLayout *topLayout = new Q3VBoxLayout( this , 0, 0 );
     Q3BoxLayout* layout = new Q3HBoxLayout( topLayout, 0, 0 );
     QPushButton* button;
     button = new QPushButton( "Analyze" , this , "analyzeButton"  );
     QToolTip::add( button, "Analyze focus area" );
     layout->addWidget( button );
     connect( button , SIGNAL( clicked( void ) ) ,
              domain , SLOT( requestProcess( void ) ) );
     // TODO: button should activate only after succesful data import
     button->setEnabled( false );
     _processButton = button;
     button = new QPushButton( "Start Capture" , this , "startButton" );
     QToolTip::add( button, "Specify file name and start video capture" );
     layout->addWidget( button );
     connect( button , SIGNAL( clicked( void ) ) ,
              domain , SLOT( requestMovieSave( void ) ) );
     button->setEnabled( false );
     button->hide();
     _startButton = button;
     button->hide();
     button = new QPushButton( "Stop Capture" , this , "stopButton"  );
     QToolTip::add( button, "Stop video capture" );
     layout->addWidget( button );
     connect( button , SIGNAL( clicked( void ) ) ,
              domain , SLOT( requestStop( void ) ) );
     button->setEnabled( false );
     button->hide();
     _stopButton = button;
     button = new QPushButton( "Stop Analysis" , this , "stopAnalysisButton"  );
     QToolTip::add( button, "Stop analysis" );
     layout->addWidget( button );
     connect( button , SIGNAL( clicked( void ) ) ,
              domain , SLOT( requestStop( void ) ) );
     button->setEnabled( false );
     button->hide();
     _stopAnalysisButton = button;
     // Selection cursor time
     _cursorTime = new QLabel( this );
     _cursorTime->setTextFormat( Qt::PlainText );
     _cursorTime->setAlignment(Qt::AlignCenter);
     _cursorTime->setFrameStyle( Panel );
     _cursorTime->setFrameShadow( Sunken );
     _cursorTime->setText( timestampToString( 0.0 ) );
     QToolTip::add( _cursorTime, "Current selection time" );
     layout->addWidget( _cursorTime );
     // Total elapsed time
     _elapsedTime = new QLabel( this );
     _elapsedTime->setTextFormat( Qt::PlainText );
     _elapsedTime->setAlignment(Qt::AlignCenter );
     _elapsedTime->setFrameStyle( Panel );
     _elapsedTime->setFrameShadow( Sunken );
     _elapsedTime->setText( timestampToString( 0.0 ) );
     QToolTip::add( _elapsedTime, "Total elapsed time" );
     layout->addWidget( _elapsedTime );
     // Model connections
     connect( domain , SIGNAL( elapsedTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateElapsedTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( cursorTime( const rcTimestamp& ) ) ,
              this   , SLOT( updateCursorTime( const rcTimestamp& ) ) );
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateAnalysisRect( const rcRect& ) ) ,
              this   , SLOT( updateAnalysisRect( const rcRect& ) ) );
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     connect( domain , SIGNAL( updateInputSource( int ) ) ,
              this   , SLOT( inputSource( int ) ) );
     connect( domain , SIGNAL( updateSelectionState( bool ) ) ,
              this   , SLOT( updateSelectionState ( bool ) ) );
 }
rcControlPanel::~rcControlPanel ()
Definition at line 244 of file rc_controlpanel.cpp.
References _elapsedTime, _processButton, _startButton, and _stopButton.
 {
     QToolTip::remove( _processButton );
     QToolTip::remove( _startButton );
     QToolTip::remove( _stopButton );
     QToolTip::remove( _elapsedTime );
 }
Member Function Documentation
void rcControlPanel::inputSource (int i) slot
Definition at line 371 of file rc_controlpanel.cpp.
References _analysisRect, _processButton, _startButton, _stopAnalysisButton, _stopButton, rcModelDomain::getExperimentState(), rcModelDomain::getModelDomain(), updateAnalysisRect(), updateCursorTime(), and updateState().
Referenced by rcControlPanel().
 {
     // Hack alert: value 0 is file, greater than 0 camera
     if ( i > 0 ) {
         // Camera input
         _processButton->setEnabled( false );
         _processButton->hide();
         _stopAnalysisButton->setEnabled( false );
         _stopAnalysisButton->hide();
         _startButton->setEnabled( true );
         _startButton->show();
         _stopButton->setEnabled( false );
         _stopButton->hide();
     } else {
         // File input
          _processButton->setEnabled( true );
          _processButton->show();
          _stopAnalysisButton->setEnabled( false );
          _stopAnalysisButton->hide();
          _stopButton->setEnabled( false );
          _stopButton->hide();
          _startButton->setEnabled( false );
          _startButton->hide();
     }
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperimentState state = domain->getExperimentState();
     updateState( state );
     updateAnalysisRect( _analysisRect );
     updateCursorTime();
 }
void rcControlPanel::settingChanged (void) slot
Definition at line 359 of file rc_controlpanel.cpp.
Referenced by rcControlPanel().
 {
 }
QString rcControlPanel::timestampToString (const rcTimestamp & time) private
Definition at line 433 of file rc_controlpanel.cpp.
References cMilliSecsPerSec, cSecsPerDay, cSecsPerHour, cSecsPerMinute, and rcTimestamp::secs().
Referenced by rcControlPanel(), updateCursorTime(), and updateElapsedTime().
 {
     double dSecs = time.secs();
     int nDays = int(dSecs / cSecsPerDay);
     dSecs -= cSecsPerDay * nDays;
     int nHours = int(dSecs / cSecsPerHour);
     dSecs -= cSecsPerHour * nHours;
     int nMinutes = int(dSecs / cSecsPerMinute);
     dSecs -= cSecsPerMinute * nMinutes;
     int nSecs = int(dSecs);
     dSecs -= nSecs;
     int nMillis = int(dSecs * cMilliSecsPerSec);
     QString string;
     if (nDays == 0)
         string.sprintf( "%02d:%02d:%02d.%03d" , nHours , nMinutes , nSecs , nMillis );
     else
         string.sprintf( "%dd %02d:%02d:%02d.%03d" , nDays , nHours , nMinutes , nSecs , nMillis );
     return string;
 }
void rcControlPanel::updateAnalysisRect (const rcRect & rect) slot
Definition at line 350 of file rc_controlpanel.cpp.
References _analysisRect, _lastState, _processButton, _selectionState, eExperimentRunning, rcRectangle< T >::height(), and rcRectangle< T >::width().
Referenced by inputSource(), rcControlPanel(), and updateState().
 {
     _analysisRect = rect;
     // Enable/disable process button based on focus area size
     _processButton->setEnabled( _analysisRect.width() > 0 && _analysisRect.height() > 0 && _lastState != eExperimentRunning
                 && _selectionState == false);
 }
void rcControlPanel::updateCursorTime (const rcTimestamp & time) slot
Definition at line 262 of file rc_controlpanel.cpp.
References _cursorTime, rcTimestamp::secs(), timestampToString(), and updateCursorTime().
 {
     if (time.secs() >= 0.0) {
         // Historical time
         _cursorTime->setText( timestampToString( time ) );
     } else {
         updateCursorTime();
     }
 }
void rcControlPanel::updateCursorTime () slot
Definition at line 407 of file rc_controlpanel.cpp.
References _cursorTime, rcModelDomain::getModelDomain(), rcModelDomain::operatingOnLiveInput(), and rcModelDomain::storingLiveInput().
Referenced by inputSource(), rcControlPanel(), updateCursorTime(), and updateElapsedTime().
 {
     // Current time
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     //    rcExperimentAttributes attr = domain->getExperimentAttributes();
     if ( domain->operatingOnLiveInput ()) {
         // Camera source
       if ( domain->storingLiveInput() )
             _cursorTime->setText( "video capture" );
         else
             _cursorTime->setText( "video preview" );
     } else {
         // File source
         _cursorTime->setText( " " );
     }
 }
void rcControlPanel::updateElapsedTime (const rcTimestamp & time) slot
Definition at line 253 of file rc_controlpanel.cpp.
References _elapsedTime, rcModelDomain::getModelDomain(), rcModelDomain::operatingOnLiveInput(), timestampToString(), and updateCursorTime().
Referenced by rcControlPanel().
 {
     _elapsedTime->setText( timestampToString( time ) );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     //    rcExperimentAttributes attr = domain->getExperimentAttributes();
     //    if ( attr.liveInput )
     if (domain->operatingOnLiveInput ()) updateCursorTime();
 }
void rcControlPanel::updateSelectionState (bool trueIsSelect) slot
Definition at line 363 of file rc_controlpanel.cpp.
References _selectionState, and endl().
Referenced by rcControlPanel().
 {
   cerr << "Slot Called" << endl;
   _selectionState = v;
 }
void rcControlPanel::updateState (rcExperimentState state) slot
Definition at line 272 of file rc_controlpanel.cpp.
References _analysisRect, _lastState, _processButton, _startButton, _stopAnalysisButton, _stopButton, eExperimentEmpty, eExperimentEnded, eExperimentLocked, eExperimentPlayback, eExperimentRunning, rcModelDomain::getModelDomain(), rcModelDomain::operatingOnLiveInput(), and updateAnalysisRect().
Referenced by inputSource(), and rcControlPanel().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
 //    rcExperimentAttributes attr = domain->getExperimentAttributes();
     if ( domain->operatingOnLiveInput () ) {
         // Camera input
         switch( state ) {
             case eExperimentEmpty:
                 // Enable start button
                 _stopButton->setEnabled( false );
                 _stopButton->hide();
                 _startButton->setEnabled( true );
                 _startButton->show();
                 break;
             case eExperimentEnded:
             case eExperimentLocked:
                 // Disable stop button
                 _stopButton->setEnabled( false );
                 _stopButton->hide();
                 _startButton->setEnabled( false );
                 _startButton->show();
                 break;
             case eExperimentRunning:
             case eExperimentPlayback:
                 _startButton->setEnabled( false );
                 _startButton->hide();
                 _stopButton->setEnabled( true );
                 _stopButton->show();
                 break;
         }
     } else {
         // File input
         switch( state ) {
             case eExperimentEmpty:
                 _processButton->setEnabled( true );
                 _processButton->show();
                 // Disable start + stop button
                 _startButton->setEnabled( false );
                 _startButton->hide();
                 _stopButton->setEnabled( false );
                 _stopButton->hide();
                 _stopAnalysisButton->setEnabled( false );
                 _stopAnalysisButton->hide();
                 break;
             case eExperimentEnded:
             case eExperimentLocked:
                 _processButton->setEnabled( true );
                 _processButton->show();
                 // Disable start + stop button
                 _startButton->setEnabled( false );
                 _startButton->hide();
                 _stopButton->setEnabled( false );
                 _stopButton->hide();
                 _stopAnalysisButton->setEnabled( false );
                 _stopAnalysisButton->hide();
                 break;
             case eExperimentRunning:
             case eExperimentPlayback:
                 _processButton->setEnabled( false );
                 _processButton->hide();
                 // Enable stop button
                 _startButton->setEnabled( false );
                 _startButton->hide();
                 _stopButton->setEnabled( false );
                 _stopButton->hide();
                 _stopAnalysisButton->setEnabled( true );
                 _stopAnalysisButton->show();
                 break;
         }
     }
     _lastState = state;
     updateAnalysisRect( _analysisRect );
 }
Member Data Documentation
rcRect rcControlPanel::_analysisRect private
Definition at line 45 of file rc_controlpanel.h.
Referenced by inputSource(), updateAnalysisRect(), and updateState().
QLabel* rcControlPanel::_cursorTime private
Definition at line 40 of file rc_controlpanel.h.
Referenced by rcControlPanel(), and updateCursorTime().
QLabel* rcControlPanel::_elapsedTime private
Definition at line 39 of file rc_controlpanel.h.
Referenced by rcControlPanel(), updateElapsedTime(), and ~rcControlPanel().
rcExperimentState rcControlPanel::_lastState private
Definition at line 46 of file rc_controlpanel.h.
Referenced by rcControlPanel(), updateAnalysisRect(), and updateState().
QPushButton* rcControlPanel::_processButton private
Definition at line 43 of file rc_controlpanel.h.
Referenced by inputSource(), rcControlPanel(), updateAnalysisRect(), updateState(), and ~rcControlPanel().
bool rcControlPanel::_selectionState private
Definition at line 47 of file rc_controlpanel.h.
Referenced by rcControlPanel(), updateAnalysisRect(), and updateSelectionState().
QPushButton* rcControlPanel::_startButton private
Definition at line 41 of file rc_controlpanel.h.
Referenced by inputSource(), rcControlPanel(), updateState(), and ~rcControlPanel().
QPushButton* rcControlPanel::_stopAnalysisButton private
Definition at line 44 of file rc_controlpanel.h.
Referenced by inputSource(), rcControlPanel(), and updateState().
QPushButton* rcControlPanel::_stopButton private
Definition at line 42 of file rc_controlpanel.h.
Referenced by inputSource(), rcControlPanel(), updateState(), and ~rcControlPanel().
The documentation for this class was generated from the following files:
include/visUI/rc_controlpanel.h
src/visible/qt/rc_controlpanel.cpp