Visible: rcShape Class Reference
rcShape Class Reference
Geometric Shape Measurements
#include <include/analysis/rc_shape.h>
Public Types
enum geometry { eAffine, eBoundingBox, eImage, eDefault = eImage }
Constructor Creates a rcShape from A Polygon or A Polygon and an Image or an image.
enum Valid {
eIsValid = 0, eValidFrame, eValidPoly, eValidArea,
eValidPerimeter, eValidCircularity, eValidEllipseRatio, eValidMinor,
eValidMajor, eValidMajorProfile, eValidMinorProfile, eValidCom,
eValidMoments, eValidAffineRect, eValidAffineWindow, eValidAffineCom,
eValidAffinedImage, eValidDimensionConstraints, eNumValids
}
Public Member Functions
bool isValid (enum Valid what) const
bool validate (enum Valid what)
bool inValidate (enum Valid what)
rcShape ()
rcShape (const rcPolygon &poly)
rcShape (const rcWindow &frame, const rcPolygon &poly)
rcShape (const rcWindow &frame)
virtual ~rcShape ()
void setMask ()
bool isBound (geometry=eAffine)
rcIRect orthogonalBoundingBox () const
rc2Fvector orthogonalBoundingBoxCenter () const
float orthogonalBoundingBoxAspect () const
const rcPolygon & shape () const
double area () const
double mass () const
double perimeter () const
rc2Fvector centerOfmass (geometry g=eDefault) const
rc2Fvector median (geometry g=eDefault) const
rcDPair inertia () const
rcDPair inertiaPrincipal () const
double elongation () const
rcRadian angle () const
double circularity () const
double ellipseRatio () const
const vector< float > & majorProfile () const
const vector< float > & minorProfile () const
const rcAffineRectangle & affineRect () const
const rcAffineWindow & affineWindow () const
const rcWindow & affineImage () const
float majorDimension () const
float minorDimension () const
rcDPair majorEnds () const
rcDPair minorEnds () const
bool majorEndConstraints (rcDPair &oneEnd, rcDPair &otherEnd)
bool clearMajorEndConstrainsts ()
bool haveMajorEndConstrainsts () const
int32 extendProfile (int32)
const int32 extendProfile () const
bool operator< (const rcShape &rhs) const
bool operator== (const rcShape &rhs) const
double tiny ()
void printCache ()
bool testPeak ()
void copyFrom (const rcShape &)
Private Member Functions
rcShape (const rcShape &rhs)
rcShape & operator= (const rcShape &rhs)
void project (const rcWindow &src, const rcWindow &mask, vector< float > &widthProj, vector< float > &heightProj)
void projectMI (const rcWindow &src, const rcWindow &mask, vector< float > &widthProj, vector< float > &heightProj)
float dimension ()
void profiles ()
void reset (geometry)
double needArea ()
double needMass ()
double needPerimeter ()
rcRadian needAngle ()
rc2Fvector needCenterOfmass (geometry g=eDefault)
rc2Fvector needMedian (geometry g=eDefault)
const rcAffineRectangle & needAffineRect ()
const rcAffineWindow & needAffineWindow ()
bool peakDetect1d (const vector< float > &signal, rcDPair &extendPeaks)
double needCircularity ()
double needEllipseRatio ()
float needMajorDimension ()
float needMinorDimension ()
Private Attributes
bitset< eNumValids > mValidSet
double mArea
double mMass
double mPerimeter
double mElongation
double mCircularity
double mEllipseRatio
rcDPair mInertia
rcRadian mAngle
rc2Dvector mMedian
rc2Dvector mCom
rc2Dvector mAffineCom
rc2Dvector mAffineMedian
rc2Fvector mAffineSize
rcDPair mMajorEnds
rcDPair mMinorEnds
rcDPair mMajorOneEndConstraints
rcDPair mMajorOtherEndConstraints
float mMajord
float mMinord
float mX
float mY
float mXX
float mYY
int32 mExtendSize
rcWindow mFrame
rcWindow mMask
rcPolygon mPoly
rcAffineRectangle mAffineRect
rcAffineWindow mAffineWindow
vector< float > mMajorD
vector< float > mMinorD
rcWindow mAffinedImage
uint8 mBg
uint8 mFg
Friends
ostream & operator<< (ostream &o, const rcShape &s)
Detailed Description
Geometric Shape Measurements
Exceptions
exception when not initialized
bar_exception
Definition at line 109 of file rc_shape.h.
Member Enumeration Documentation
enum rcShape::geometry
Constructor Creates a rcShape from A Polygon or A Polygon and an Image or an image.
Enumerator
eAffine
eBoundingBox
eImage
eDefault
Definition at line 118 of file rc_shape.h.
   {
     eAffine,
     eBoundingBox,
     eImage,
     eDefault = eImage
   };
enum rcShape::Valid
Enumerator
eIsValid
eValidFrame
eValidPoly
eValidArea
eValidPerimeter
eValidCircularity
eValidEllipseRatio
eValidMinor
eValidMajor
eValidMajorProfile
eValidMinorProfile
eValidCom
eValidMoments
eValidAffineRect
eValidAffineWindow
eValidAffineCom
eValidAffinedImage
eValidDimensionConstraints
eNumValids
Definition at line 126 of file rc_shape.h.
     {
       eIsValid = 0,
       eValidFrame,
       eValidPoly,
       eValidArea,
       eValidPerimeter,
       eValidCircularity,
       eValidEllipseRatio,
       eValidMinor,
       eValidMajor,
       eValidMajorProfile,
       eValidMinorProfile,
       eValidCom,
       eValidMoments,
       eValidAffineRect,
       eValidAffineWindow,
       eValidAffineCom,
       eValidAffinedImage,
       eValidDimensionConstraints,
       eNumValids
     };
Constructor & Destructor Documentation
rcShape::rcShape ()
Definition at line 257 of file rc_shape.cpp.
 : mExtendSize (0) {}
rcShape::rcShape (const rcPolygon & poly)
Definition at line 309 of file rc_shape.cpp.
References eAffine, eImage, eIsValid, eValidFrame, eValidPoly, inValidate(), rcPolygon::isValid(), mPoly, reset(), rmExceptionMacro, and validate().
 {
   reset (eAffine);
   reset (eImage);
   if (poly.isValid())
     {
       mPoly = poly;
       inValidate (eValidFrame);
       validate (eValidPoly);
       validate (eIsValid);
     }
   else
     {
       rmExceptionMacro (<<" rcShape Ctor " << poly.isValid());
     }
 }
rcShape::rcShape (const rcWindow & frame, const rcPolygon & poly)
Definition at line 328 of file rc_shape.cpp.
References eAffine, eImage, eIsValid, eValidFrame, eValidPoly, rcWindow::isBound(), rcPolygon::isValid(), mFrame, mMask, mPoly, reset(), rmExceptionMacro, and validate().
 {
   reset (eAffine);
   reset (eImage);
   if (poly.isValid() && frame.isBound())
     {
       mPoly = poly;
       mFrame = frame;
       mMask = rcWindow ();
       validate (eValidFrame);
       validate (eValidPoly);
       validate (eIsValid);
     }
   else
     {
       rmExceptionMacro (<<" rcShape Ctor " << poly.isValid() << frame.isBound());
     }
 }
rcShape::rcShape (const rcWindow & frame)
Definition at line 288 of file rc_shape.cpp.
References eAffine, eImage, eIsValid, eValidFrame, eValidPoly, inValidate(), rcWindow::isBound(), mFrame, mMask, reset(), rmExceptionMacro, and validate().
 {
   reset (eAffine);
   reset (eImage);
   if (frame.isBound())
     {
       mFrame = frame;
       mMask = rcWindow ();
       validate (eValidFrame);
       inValidate (eValidPoly);
       validate (eIsValid);
     }
   else
     {
       rmExceptionMacro (<<" rcShape Ctor " << frame.isBound());
     }
 }
rcShape::~rcShape () virtual
Definition at line 261 of file rc_shape.cpp.
 {}
rcShape::rcShape (const rcShape & rhs) private
Member Function Documentation
const rcWindow & rcShape::affineImage () const
Definition at line 572 of file rc_shape.cpp.
References mAffinedImage.
  {
    return mAffinedImage;
  }
const rcAffineRectangle & rcShape::affineRect () const
Definition at line 513 of file rc_shape.cpp.
References needAffineRect().
Referenced by angle(), needAffineWindow(), orthogonalBoundingBox(), and profiles().
 {
   return const_cast<rcShape *>(this)->needAffineRect ();
 }
const rcAffineWindow & rcShape::affineWindow () const
Definition at line 567 of file rc_shape.cpp.
References needAffineWindow().
Referenced by needCenterOfmass(), needMedian(), printCache(), and profiles().
  {
   return const_cast<rcShape *>(this)->needAffineWindow ();
  }
rcRadian rcShape::angle () const
Definition at line 722 of file rc_shape.cpp.
References affineRect(), and rcAffineRectangle::angle().
  {
    const rcAffineRectangle& ar = affineRect ();
    return  ar.angle();
  }
double rcShape::area () const
Definition at line 432 of file rc_shape.cpp.
References needArea().
 {
   return const_cast<rcShape *>(this)->needArea ();
 }
rc2Fvector rcShape::centerOfmass (geometry g = eDefault) const
Definition at line 775 of file rc_shape.cpp.
References needCenterOfmass().
 {
   return const_cast<rcShape *>(this)->needCenterOfmass (g);
 }
double rcShape::circularity () const
Definition at line 473 of file rc_shape.cpp.
References needCircularity().
 {
   return const_cast<rcShape *>(this)->needCircularity ();
 }
bool rcShape::clearMajorEndConstrainsts ()
void rcShape::copyFrom (const rcShape & other)
Definition at line 1136 of file rc_shape.cpp.
References mAffineCom, mAffineMedian, mAffineRect, mAffineSize, mAffineWindow, mAngle, mArea, mCircularity, mCom, mEllipseRatio, mElongation, mExtendSize, mFrame, mInertia, mMajord, mMajorD, mMajorEnds, mMass, mMedian, mMinord, mMinorD, mMinorEnds, mPerimeter, mPoly, mValidSet, mX, mXX, mY, and mYY.
 {
   mValidSet = other.mValidSet;
   mArea = other.mArea;
   mMass = other.mMass;
   mPerimeter = other.mPerimeter;
   mInertia = other.mInertia;
   mAngle = other.mAngle;
   mElongation = other.mElongation;
   mCircularity = other.mCircularity;
   mEllipseRatio = other.mEllipseRatio;
   mMedian = other.mMedian;
   mCom = other.mCom;
   mAffineCom = other.mAffineCom;
   mAffineMedian = other.mAffineMedian;
   mAffineSize = other.mAffineSize;
   mMajorEnds = other.mMajorEnds;
   mMinorEnds = other.mMinorEnds;
   mMajord = other.mMajord;
   mMinord = other.mMinord;
   mX = other.mX;
   mY = other.mY;
   mXX = other.mXX;
   mYY = other.mYY;
   mFrame = other.mFrame;
   mPoly = other.mPoly;
 //  mRegion = other.mRegion;
   mAffineRect = other.mAffineRect;
   mAffineWindow = other.mAffineWindow;
   mMajorD = other.mMajorD;
   mMinorD = other.mMinorD;
   mExtendSize = other.mExtendSize;
 }
float rcShape::dimension () private
double rcShape::ellipseRatio () const
Definition at line 493 of file rc_shape.cpp.
References needEllipseRatio().
  {
   return const_cast<rcShape *>(this)->needEllipseRatio ();
  }
double rcShape::elongation () const
int32 rcShape::extendProfile (int32 s)
Definition at line 385 of file rc_shape.cpp.
References mExtendSize.
 {
   mExtendSize = s;return mExtendSize;
 }
const int32 rcShape::extendProfile () const
Definition at line 390 of file rc_shape.cpp.
References mExtendSize.
 {
   return mExtendSize;
 }
bool rcShape::haveMajorEndConstrainsts () const
rcDPair rcShape::inertia () const
rcDPair rcShape::inertiaPrincipal () const
bool rcShape::inValidate (enum Valid what)
Definition at line 274 of file rc_shape.cpp.
References mValidSet.
Referenced by rcShape(), and reset().
 {
   mValidSet[what] = false;
   return mValidSet[what];
 }
bool rcShape::isBound (geometry g = eAffine)
Definition at line 280 of file rc_shape.cpp.
References eAffine, eImage, eIsValid, eValidFrame, and isValid().
 {
   if (g == eAffine) return isValid(eIsValid);
   if (g == eImage) return (isValid(eIsValid) && isValid (eValidFrame));
   return false;
 }
bool rcShape::isValid (enum Valid what) const
Definition at line 263 of file rc_shape.cpp.
References mValidSet.
Referenced by isBound(), majorEndConstraints(), needAffineRect(), needAffineWindow(), needArea(), needCenterOfmass(), needCircularity(), needEllipseRatio(), needMajorDimension(), needMass(), needMedian(), needMinorDimension(), needPerimeter(), orthogonalBoundingBox(), printCache(), and profiles().
 {
   return mValidSet[what];
 }
float rcShape::majorDimension () const
Definition at line 899 of file rc_shape.cpp.
References needMajorDimension().
 {
   return const_cast<rcShape *>(this)->needMajorDimension ();
  }
bool rcShape::majorEndConstraints (rcDPair & oneEnd, rcDPair & otherEnd)
Definition at line 395 of file rc_shape.cpp.
References eValidDimensionConstraints, isValid(), mMajorD, mMajorOneEndConstraints, mMajorOtherEndConstraints, validate(), rcPair< T >::x(), and rcPair< T >::y().
 {
   // One Size: from 0 on
   if (oneEnd.x() < 0 || oneEnd.y() < 0 ||
       (oneEnd.x()+oneEnd.y()) > (mMajorD.size() - 1))
     return false;
   // Other Size: from End (1/2 step) inward.
   if (otherEnd.x() < 0 || otherEnd.y() < 0 ||
       (otherEnd.x() >  (mMajorD.size() - 1)) ||
       ((otherEnd.x() - otherEnd.y())) > (mMajorD.size() - 1))
     return false;
   mMajorOneEndConstraints = oneEnd;
   mMajorOtherEndConstraints = otherEnd;
   validate (eValidDimensionConstraints);
   return   isValid (eValidDimensionConstraints);
 }
rcDPair rcShape::majorEnds () const
Definition at line 967 of file rc_shape.cpp.
References mMajorEnds, and needMajorDimension().
 {
   const_cast<rcShape *>(this)->needMajorDimension ();
   return mMajorEnds;
 }
const vector< float > & rcShape::majorProfile () const
Definition at line 954 of file rc_shape.cpp.
References mMajorD, and needMajorDimension().
 {
   const_cast<rcShape *>(this)->needMajorDimension ();
   return mMajorD;
 }
double rcShape::mass () const
Definition at line 717 of file rc_shape.cpp.
References needMass().
Referenced by needCenterOfmass(), and needMedian().
  {
    return const_cast<rcShape *>(this)->needMass ();
  }
rc2Fvector rcShape::median (geometry g = eDefault) const
Definition at line 840 of file rc_shape.cpp.
References needMedian().
 {
   return const_cast<rcShape *>(this)->needMedian (g);
 }
float rcShape::minorDimension () const
Definition at line 930 of file rc_shape.cpp.
References needMinorDimension().
 {
   return const_cast<rcShape *>(this)->needMinorDimension ();
 }
rcDPair rcShape::minorEnds () const
Definition at line 973 of file rc_shape.cpp.
References mMinorEnds, and needMinorDimension().
 {
   const_cast<rcShape *>(this)->needMinorDimension ();
   return mMinorEnds;
 }
const vector< float > & rcShape::minorProfile () const
Definition at line 961 of file rc_shape.cpp.
References mMinorD, and needMinorDimension().
 {
   const_cast<rcShape *>(this)->needMinorDimension ();
   return mMinorD;
 }
const rcAffineRectangle & rcShape::needAffineRect () private
Definition at line 519 of file rc_shape.cpp.
References rcAffineRectangle::cannonicalSize(), eIsValid, eValidAffineRect, eValidPoly, rcAffineRectangle::expand(), isValid(), mAffineRect, mAffineSize, mExtendSize, rcPolygon::minimumAreaEnclosingRect(), mPoly, rmExceptionMacro, rmMax, rmMin, validate(), rcPair< T >::x(), rc2dVector< T >::x(), rcAffineRectangle::xyScale(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by affineRect().
  {
    if (isValid (eIsValid) && isValid (eValidPoly) &&  !isValid (eValidAffineRect))
     {
       rcAffineRectangle ar = mPoly.minimumAreaEnclosingRect ();
       bool cOr = (ar.cannonicalSize().x() >= ar.cannonicalSize().y()) ? true : false;
       rcIPair steps (0, 0);
       steps.x() = cOr ? mExtendSize : 0;
       steps.y() = cOr ? 0 : mExtendSize;
       mAffineRect = ar.expand (steps);
       mAffineSize.x(rmMax (mAffineRect.xyScale().x(), mAffineRect.xyScale().y()));
       mAffineSize.y(rmMin (mAffineRect.xyScale().x(), mAffineRect.xyScale().y()));
       validate (eValidAffineRect);
       return mAffineRect;
     }
    if (isValid (eIsValid) && isValid (eValidPoly) && isValid (eValidAffineRect))
     return mAffineRect;
   rmExceptionMacro (<< "rcShape::NotValid");
  }
const rcAffineWindow & rcShape::needAffineWindow () private
Definition at line 577 of file rc_shape.cpp.
References affineRect(), eIsValid, eValidAffineRect, eValidAffineWindow, eValidFrame, isValid(), mAffineWindow, mFrame, rmExceptionMacro, and validate().
Referenced by affineWindow().
 {
    if (isValid (eIsValid) && isValid (eValidAffineRect) &&  isValid (eValidFrame))
      {
        mAffineWindow = rcAffineWindow (mFrame, affineRect ());
        validate (eValidAffineWindow);
        return mAffineWindow;
      }
    if (isValid (eValidAffineWindow))
      return mAffineWindow;
   rmExceptionMacro (<< "rcShape::NotValid");
 }
rcRadian rcShape::needAngle () private
double rcShape::needArea () private
Definition at line 437 of file rc_shape.cpp.
References rcPolygon::area(), eIsValid, eValidArea, isValid(), mArea, mPoly, rmExceptionMacro, and validate().
Referenced by area().
 {
   if (isValid (eIsValid) && !isValid (eValidArea))
     {
       mArea = mPoly.area ();
       validate (eValidArea);
       return mArea;
     }
   if (isValid (eIsValid) && isValid (eValidArea))
     return mArea;
   rmExceptionMacro (<< "rcShape::NotValid");
 }
rc2Fvector rcShape::needCenterOfmass (geometry g = eDefault) private
Definition at line 780 of file rc_shape.cpp.
References rcAffineRectangle::affineToImage(), affineWindow(), rcAffineWindow::ar(), rcPolygon::centerOf(), eAffine, eImage, eIsValid, eValidAffineCom, eValidCom, eValidFrame, eValidPoly, rcWindow::isBound(), isValid(), mAffineCom, mAffineSize, mass(), mCom, mMask, mPoly, mX, mY, rmAssert, rmExceptionMacro, validate(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by centerOfmass().
 {
   if (!isValid (eIsValid))
     rmExceptionMacro (<< "rcShape::NotValid");
   if (g == eAffine && isValid (eValidAffineCom))
     {
       return rc2Fvector ((float) mAffineCom.x(), (float) mAffineCom.y());
     }
   if (!isValid (eValidAffineCom) && g == eAffine)
     {
       rc2Dvector pctr;
       mPoly.centerOf (pctr);
       mAffineCom.x((float) pctr.x() );
       mAffineCom.y((float) pctr.y() );
       validate (eValidAffineCom);
       return rc2Fvector ((float) mAffineCom.x(), (float) mAffineCom.y());
     }
   if (isValid (eValidCom) && isValid (eValidFrame) && g == eImage)
     return rc2Fvector ((float) mCom.x(),
                (float) mCom.y());
   // Need moments
   double mas = mass ();
   // Calculate in pixels and in the affineWindow
   mCom.x((float) mX / mas);
   mCom.y((float) mY / mas);
   if (isValid (eIsValid) && isValid (eValidPoly) &&  isValid (eValidFrame)  &&
       !mMask.isBound())
     {
       // Normalize to affine size in pixels
       mCom.x(mCom.x() / mAffineSize.x());
       mCom.y(mCom.y() / mAffineSize.y());
       rmAssert (mCom.x() >= 0.0 && mCom.x() <= 1.0);
       rmAssert (mCom.y() >= 0.0 && mCom.y() <= 1.0);
       // Now map it to image coordinates
       mCom = affineWindow().ar().affineToImage (mCom);
       validate (eValidCom);
       return rc2Fvector ((float) mCom.x(), (float) mCom.y());
     }
   else if (isValid (eIsValid) && isValid (eValidFrame))
     {
       validate (eValidCom);
       return rc2Fvector ((float) mCom.x(), (float) mCom.y());
     }
   else
     {
       rmExceptionMacro (<< "rcShape::NotValid" << isValid (eIsValid) << " " << isValid (eValidPoly) << " " << isValid (eValidFrame));
     }
 }
double rcShape::needCircularity () private
Definition at line 478 of file rc_shape.cpp.
References rcPolygon::circularity(), eIsValid, eValidCircularity, isValid(), mCircularity, mPoly, rmExceptionMacro, and validate().
Referenced by circularity().
 {
   if (isValid (eIsValid) && !isValid (eValidCircularity))
     {
       mCircularity = mPoly.circularity ();
       validate (eValidCircularity);
       return mCircularity;
     }
   if (isValid (eIsValid) && isValid (eValidCircularity))
     return mCircularity;
   rmExceptionMacro (<< "rcShape::NotValid");
 }
double rcShape::needEllipseRatio () private
Definition at line 498 of file rc_shape.cpp.
References eIsValid, rcPolygon::ellipseRatio(), eValidEllipseRatio, isValid(), mEllipseRatio, mPoly, rmExceptionMacro, and validate().
Referenced by ellipseRatio().
 {
   if (isValid (eIsValid) && !isValid (eValidEllipseRatio))
     {
       mEllipseRatio = mPoly.ellipseRatio ();
       validate (eValidEllipseRatio);
       return mEllipseRatio;
     }
   if (isValid (eIsValid) && isValid (eValidEllipseRatio))
     return mEllipseRatio;
   rmExceptionMacro (<< "rcShape::NotValid");
 }
float rcShape::needMajorDimension () private
Definition at line 905 of file rc_shape.cpp.
References eIsValid, eValidMajor, isValid(), mMajord, mMajorD, mMajorEnds, peakDetect1d(), profiles(), rmExceptionMacro, validate(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by majorDimension(), majorEnds(), and majorProfile().
 {
   if (!isValid (eIsValid))
     {
       rmExceptionMacro (<< "rcShape::NotValid");
     }
   if (isValid (eValidMajor))
     {
       return mMajord;
     }
   // Need Projections
   profiles ();
   // detect the ends
   peakDetect1d (mMajorD, mMajorEnds);
   mMajord = mMajorEnds.y() - mMajorEnds.x();
   validate (eValidMajor);
   return mMajord;
 }
double rcShape::needMass () private
Definition at line 753 of file rc_shape.cpp.
References eIsValid, eValidFrame, eValidMoments, hornMoments(), isValid(), mMajorD, mMass, mMinorD, mX, mXX, mY, mYY, profiles(), rmExceptionMacro, and validate().
Referenced by mass().
 {
   if (!isValid (eIsValid) &&  !isValid (eValidFrame))
     rmExceptionMacro (<< "rcShape::NotValid");
   if (isValid (eValidMoments))
     return mMass;
   profiles ();
   // get Center of Mass, need moments
   float massX (0.0f), massY (0.0f);
   mX = mXX = mY = mYY = 0.0f;
   hornMoments (mMajorD, massX, mX, mXX);
   hornMoments (mMinorD, massY, mY, mYY);
   // record mass
   mMass = (massX + massY) / 2.0;
   validate (eValidMoments);
   return mMass;
 }
rc2Fvector rcShape::needMedian (geometry g = eDefault) private
Definition at line 845 of file rc_shape.cpp.
References rcAffineRectangle::affineToImage(), affineWindow(), rcAffineWindow::ar(), eImage, eIsValid, isValid(), mAffineMedian, mass(), mMajorD, mMedian, mMinorD, profiles(), rmAssertDebug, rmExceptionMacro, rmUnused, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by median().
 {
   if (!isValid (eIsValid))
     rmExceptionMacro(<< "rcShape::NotValid");
   double mas = mass ();
   rmUnused (mas);
   profiles ();
   // The assumption is that the projection is done in a most straight and unbiased way
   // hence no correction for aspect, bin size etc.
   rc2Fvector majMed;
   double soFar(0.0);
   const double majority (0.5 * mass ());
   for(uint32 i = 0; i < mMajorD.size(); i++, soFar += mMajorD[i])
   {
     if (!i) rmAssertDebug (soFar == 0.0);
     if (soFar >= majority)
     {
       majMed.x((i - (majority - soFar) / mMajorD[i]));
       break;
     }
   }
   soFar = 0.0;
   for(uint32 i = 0; i < mMinorD.size(); i++, soFar += mMinorD[i])
   {
     if (!i) rmAssertDebug (soFar == 0.0);
     if (soFar >= majority)
     {
       majMed.y((i - (majority - soFar) / mMinorD[i]));
       break;
     }
   }
   mMedian = rc2Dvector (majMed.x() , majMed.y());
   if (g == eImage)
     return rc2Fvector ((float) mMedian.x(), (float) mMedian.y());
   rc2Dvector mm = rc2Dvector (majMed.x() / mMajorD.size(), majMed.y() / mMinorD.size());
   // Now map it to image coordinates
   mAffineMedian = affineWindow().ar().affineToImage (mm);
   return rc2Fvector ((float) mAffineMedian.x(), (float) mAffineMedian.y());
 }
float rcShape::needMinorDimension () private
Definition at line 935 of file rc_shape.cpp.
References eIsValid, eValidMinor, isValid(), mMinord, mMinorD, mMinorEnds, peakDetect1d(), profiles(), rmExceptionMacro, validate(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by minorDimension(), minorEnds(), and minorProfile().
 {
   if (!isValid (eIsValid))
     rmExceptionMacro (<< "rcShape::NotValid");
   if (isValid (eValidMinor))
     return mMinord;
   // Need Projections
   profiles ();
   // detect the ends
   peakDetect1d (mMinorD, mMinorEnds);
   mMinord = mMinorEnds.y() - mMinorEnds.x();
   validate (eValidMinor);
   return mMinord;
 }
double rcShape::needPerimeter () private
Definition at line 458 of file rc_shape.cpp.
References eIsValid, eValidPerimeter, isValid(), mPerimeter, mPoly, rcPolygon::perimeter(), rmExceptionMacro, and validate().
Referenced by perimeter().
 {
   if (isValid (eIsValid) && !isValid (eValidPerimeter))
     {
       mPerimeter = mPoly.perimeter ();
       validate (eValidPerimeter);
       return mPerimeter;
     }
   if (isValid (eIsValid) && isValid (eValidPerimeter))
     return mPerimeter;
   rmExceptionMacro (<< "rcShape::NotValid");
 }
bool rcShape::operator< (const rcShape & rhs) const
rcShape& rcShape::operator= (const rcShape & rhs) private
bool rcShape::operator== (const rcShape & rhs) const
Definition at line 1173 of file rc_shape.cpp.
References rcWindow::frameBuf(), mExtendSize, mFrame, mMajorD, mMinord, mMinorD, mPoly, mValidSet, mX, mXX, mY, mYY, rcWindow::position(), and rcWindow::size().
 {
   bool pieces = false;
   pieces = mValidSet == other.mValidSet &&
   mMinord == other.mMinord &&
   mX == other.mX &&
   mY == other.mY &&
   mXX == other.mXX &&
   mYY == other.mYY &&
     mFrame.position() == other.mFrame.position() &&
     mFrame.size() == other.mFrame.size() &&
     mFrame.frameBuf() == other.mFrame.frameBuf() &&
     mPoly == other.mPoly &&
     mMajorD.size() == other.mMajorD.size() &&
     mMinorD.size() == other.mMinorD.size() &&
     mExtendSize == other.mExtendSize;
   return pieces;
 }
rcIRect rcShape::orthogonalBoundingBox () const
Definition at line 543 of file rc_shape.cpp.
References affineRect(), rcAffineRectangle::boundingBox(), eValidFrame, eValidPoly, isValid(), mFrame, and rcWindow::rectangle().
Referenced by orthogonalBoundingBoxAspect(), and orthogonalBoundingBoxCenter().
 {
   if ( isValid (eValidPoly))
     return affineRect().boundingBox ();
   else if ( isValid (eValidFrame))
     return mFrame.rectangle ();
   else return rcIRect ();
 }
float rcShape::orthogonalBoundingBoxAspect () const
Definition at line 559 of file rc_shape.cpp.
References rcRectangle< T >::height(), orthogonalBoundingBox(), rmAssert, and rcRectangle< T >::width().
 {
   rcIRect bb = orthogonalBoundingBox ();
   rmAssert (bb.height());
   return ((float) bb.width()) / ((float) bb.height());
 }
rc2Fvector rcShape::orthogonalBoundingBoxCenter () const
Definition at line 552 of file rc_shape.cpp.
References rcRectangle< T >::height(), orthogonalBoundingBox(), rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
 {
   rcIRect bb = orthogonalBoundingBox ();
   return rc2Fvector ((float) bb.ul().x() + bb.width () / 2.0f,
           (float) bb.ul().y() + bb.height () / 2.0f);
 }
bool rcShape::peakDetect1d (const vector< float > & signal, rcDPair & extendPeaks) private
Definition at line 981 of file rc_shape.cpp.
References rcEdgeFilter1DPeak::_location, rcEdgeFilter1DPeak::_value, dec(), endl(), rcEdgeFilter1D::filter(), rcEdgeFilter1D::genFilter(), rcEdgeFilter1D::genPeaks(), rfInterpolatePeak(), rmABS, rmAssert, rmMax, rmMin, rcPair< T >::x(), and rcPair< T >::y().
Referenced by needMajorDimension(), needMinorDimension(), and testPeak().
 {
   // assume nothing.
   extendPeaks.x() = 0.0; extendPeaks.y() = 0;
   // Take the highest positive and the highest negative.
   rcEdgeFilter1DPeak posMax, negMax;
   posMax._value = 0, posMax._location = -1, negMax._value = 0, negMax._location = -1;
   vector<rcEdgeFilter1DPeak>peaks, posPeaks, negPeaks;
   rcEdgeFilter1D pfinder;
   vector<int32> efilter, filtered;
   pfinder.genFilter (efilter, 2, 1);
   pfinder.filter (efilter);
   pfinder.genPeaks (signal, &filtered, peaks, 0, 1.0, 0.5);
   for (uint32 i = 0; i < peaks.size(); i++)
     {
       int32 left = (i == 0) ? 0 : peaks[i-1]._value;
       int32 right = (i == (peaks.size() -1) ) ? 0 : peaks[i+1]._value;
       int32 val = peaks[i]._value;
       if (val <= 0)
     {
       if (val <= left && val <= right)
         {
           negPeaks.push_back (peaks[i]);
           if (val < negMax._value)
         {
           negMax._value = val;
           negMax._location = peaks[i]._location;
         }
         }
     }
       else
     {
       rmAssert (val > 0);
       if (val >= left && val >= right)
         {
           posPeaks.push_back (peaks[i]);
           if (val > posMax._value)
         {
           posMax._value = val;
           posMax._location = peaks[i]._location;
         }
         }
     }
     }
   if (posMax._location < 0 || negMax._location < 0) return false;
   // In case we needed space for all the score vector <float> scores (posPeaks.size() * negPeaks.size(), zf);
   // Score every pos/neg pair based on spatial distance and peak strength.
   float dMax (signal.size());
   float pnMax = posMax._value - negMax._value;
   float sdMax (0.0f);
   rcIPair sMax;
   for (uint32 i = 0; i < negPeaks.size(); i++)
     {
       for (uint32 j = 0; j < posPeaks.size(); j++)
     {
       float d = rmABS (posPeaks[j]._location - negPeaks[i]._location) / dMax;
       float s = (posPeaks[j]._value - negPeaks[i]._value) / pnMax;
       s *= d;
       if (s > sdMax)
         {
           sMax = rcIPair ((int32) i, (int32) j);
           sdMax = s;
         }
     }
     }
   // First things first
   // Given the filtering, peaks will never be the ends but right now be paranoid
   rcDPair extends;
   extends.x() = rfInterpolatePeak (filtered, negPeaks[sMax.x()]._location);
   extends.y() = rfInterpolatePeak (filtered, posPeaks[sMax.y()]._location);
   extendPeaks.x() = rmMin (extends.x(), extends.y());
   extendPeaks.y() = rmMax (extends.x(), extends.y());
 // Debugging Print
 #ifdef SHAPEDEBUG
   cerr << dec << "+++++++++++++++++++++++++" << endl;
   cerr << signal << endl;
   cerr << filtered << endl;
   cerr << efilter << endl;
   for (uint32 i = 0; i < peaks.size(); i++) cerr << "[" << i << "]" << peaks[i]._location << ":\t" << peaks[i]._value << endl;
   cerr << negPeaks[sMax.x()]._location << " ---- " << posPeaks[sMax.y()]._location  << endl;
   cerr << extendPeaks << endl;
   cerr << "+++++++++++++++++++++++++" << endl;
 #endif
   return true;
 }
double rcShape::perimeter () const
Definition at line 453 of file rc_shape.cpp.
References needPerimeter().
 {
   return const_cast<rcShape *>(this)->needPerimeter ();
 }
void rcShape::printCache ()
Definition at line 1103 of file rc_shape.cpp.
References affineWindow(), eIsValid, endl(), eValidAffineCom, eValidAffineRect, eValidAffineWindow, eValidArea, eValidCircularity, eValidCom, eValidEllipseRatio, eValidFrame, eValidMajor, eValidMajorProfile, eValidMinor, eValidMinorProfile, eValidMoments, eValidPerimeter, isValid(), mMajorD, and mMinorD.
 {
   cerr << "mIsValid : "          << boolalpha <<  isValid(eIsValid) << endl;
   cerr << "mValidArea : "            << boolalpha <<  isValid(eValidArea  ) << endl;
   cerr << "mValidPerimeter : "      << boolalpha <<  isValid(eValidPerimeter   ) << endl;
   cerr << "mValidCircularity : "    << boolalpha <<  isValid(eValidCircularity ) << endl;
   cerr << "mValidEllipseRatio : "   << boolalpha <<  isValid(eValidEllipseRatio) << endl;
   cerr << "mValidFrame : "           << boolalpha <<  isValid(eValidFrame ) << endl;
   cerr << "mValidMinor : "           << boolalpha <<  isValid(eValidMinor ) << endl;
   cerr << "mValidMajor : "           << boolalpha <<  isValid(eValidMajor  ) << endl;
   cerr << "mValidMajorProfile : "   << boolalpha <<  isValid(eValidMajorProfile) << endl;
   cerr << "mValidMinorProfile : "   << boolalpha <<  isValid(eValidMinorProfile) << endl;
   cerr << "mValidCom : "             << boolalpha <<  isValid(eValidCom      ) << endl;
   cerr << "mValidAffineCom : "      << boolalpha <<  isValid(eValidAffineCom   ) << endl;
   cerr << "mValidMoments : "        << boolalpha <<  isValid(eValidMoments     ) << endl;
   cerr << "mValidAffineRect : "     << boolalpha <<  isValid(eValidAffineRect  ) << endl;
   cerr << "mValidAffineWindow : "   << boolalpha <<  isValid(eValidAffineWindow ) << endl;
   cerr << "{" << endl;
   uint32 i(0);
   for (i = 0; i < mMajorD.size()-1; i++) cerr << "{" << i << "," << mMajorD[i] << "},";
   cerr << "{" << i << "," << mMajorD[i] << "}};";
   cerr << endl;
   for (uint32 i = 0; i < mMinorD.size(); i++) cerr << "[" << mMinorD[i] << "]";
   cerr << endl;
   cerr << affineWindow () << endl;
 }
void rcShape::profiles () private
Definition at line 592 of file rc_shape.cpp.
References affineRect(), affineWindow(), rcAffineRectangle::cannonicalSize(), eIsValid, eValidFrame, eValidMajorProfile, eValidMinorProfile, eValidPoly, rcAffineWindow::genImage(), rcWindow::isBound(), isValid(), mAffinedImage, mFrame, mMajorD, mMask, mMinorD, project(), rcWindow::rectangle(), rmExceptionMacro, rmWarningMacro, validate(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by needMajorDimension(), needMass(), needMedian(), and needMinorDimension().
 {
   if (!isValid (eIsValid))
     rmExceptionMacro (<< "rcShape::NotValid");
   if (isValid (eValidMinorProfile) && isValid (eValidMajorProfile))
     return;
   // For now use mask as an indication.
   if (isValid (eIsValid) && isValid (eValidPoly) &&  isValid (eValidFrame) &&
        !mMask.isBound())
     {
       rmWarningMacro ("Profile Generated\n");
       const rcAffineRectangle& ar = affineRect ();
       const rcAffineWindow& af = affineWindow ();
       bool cOr = (ar.cannonicalSize().x() >= ar.cannonicalSize().y()) ? true : false;
       mAffinedImage = rcWindow (ar.cannonicalSize());
       af.genImage (mAffinedImage, mAffinedImage.rectangle());
       if (cOr)
     project (mAffinedImage, mMask, mMajorD, mMinorD);
       else
     project (mAffinedImage, mMask, mMinorD, mMajorD);
     }
   else if (isValid (eIsValid) && isValid (eValidFrame) )
     {
       project (mFrame, mMask, mMajorD, mMinorD);
     }
   else
     {
       rmExceptionMacro (<< "rcShape::NotValid" << isValid (eIsValid) << " " << isValid (eValidPoly) << " " << isValid (eValidFrame));
     }
   validate (eValidMinorProfile);
   validate (eValidMajorProfile);
 }
void rcShape::project (const rcWindow & src, const rcWindow & mask, vector< float > & widthProj, vector< float > & heightProj) private
Definition at line 633 of file rc_shape.cpp.
References rcMomentGenerator::eMoment2D, rcWindow::height(), rcMomentGenerator::hProject(), rcWindow::isBound(), rcPixel32, rfAndImage(), rcMomentGenerator::update(), rcMomentGenerator::vProject(), and rcWindow::width().
Referenced by profiles().
 {
   rcWindow vproj (src.width(), 1, rcPixel32);
   rcWindow hproj (src.height(), 1, rcPixel32);
   rcIRect rectangle (0, 0, src.width(), src.height());
   if (!mask.isBound())
     {
       rcMomentGenerator mg (rcMomentGenerator::eMoment2D);
       mg.update (src);
       mg.vProject (rectangle, vproj);
       mg.hProject (rectangle, hproj);
     }
   else
     {
       rcWindow newFrame (src.width(), src.height());
       rfAndImage (src, mask, newFrame);
       rcMomentGenerator mg (rcMomentGenerator::eMoment2D);
       mg.update (newFrame);
       mg.vProject (newFrame.rectangle(), vproj);
       mg.hProject (newFrame.rectangle(), hproj);
     }
   // Copy in to the float vectors (this is a bit silly!)
   widthProj.resize (vproj.width());
   uint32 *projPtr = (uint32 *) vproj.rowPointer (0);
   vector<float>::iterator mItr = widthProj.begin();
   for (int32 i = 0; i < vproj.width(); i++) *mItr++ = *projPtr++;
   heightProj.resize (hproj.width());
   projPtr = (uint32 *) hproj.rowPointer (0);
   mItr = heightProj.begin();
   for (int32 i = 0; i < hproj.width(); i++) *mItr++ = *projPtr++;
 }
void rcShape::projectMI (const rcWindow & src, const rcWindow & mask, vector< float > & widthProj, vector< float > & heightProj) private
Definition at line 671 of file rc_shape.cpp.
References rcSimilarator::eExhaustive, rcSimilarator::eNorm, rcSimilarator::fill(), rcWindow::height(), rcPixel8, rmAssert, tiny(), and rcWindow::width().
 {
   static double tiny = 1e-10;
   rcSimilarator sm(rcSimilarator::eExhaustive,
              rcPixel8,
              src.width(),
              0, rcSimilarator::eNorm, false, 0, tiny);
   rcSimilarator zm(rcSimilarator::eExhaustive,
            rcPixel8,
            src.height(),
            0, rcSimilarator::eNorm, false, 0, tiny);
   bool havez = zm.fill (src, false);
   bool haves = sm.fill (src);
   deque<double> sig;
   deque<double> zig;
   if (havez) havez = zm.entropies (zig);
   if (haves) haves = sm.entropies (sig);
   rmAssert (havez && haves);
   if (sig.size() == src.width() && zig.size() == src.height())
     {
       widthProj.resize (sig.size ());
       for (uint32 i = 0; i < sig.size(); i++)
     widthProj[i] = sig[i];
       heightProj.resize (zig.size ());
       for (uint32 i = 0; i < zig.size(); i++)
         heightProj[i] = zig[i];
     }
   else
     {
       widthProj.resize (zig.size ());
       for (uint32 i = 0; i < zig.size(); i++)
     widthProj[i] = zig[i];
       heightProj.resize (sig.size ());
       for (uint32 i = 0; i < sig.size(); i++)
         heightProj[i] = sig[i];
     }
 }
void rcShape::reset (geometry g) private
Definition at line 349 of file rc_shape.cpp.
References eAffine, eImage, eIsValid, eValidAffineCom, eValidAffineRect, eValidAffineWindow, eValidArea, eValidCircularity, eValidCom, eValidDimensionConstraints, eValidEllipseRatio, eValidFrame, eValidMajor, eValidMajorProfile, eValidMinor, eValidMinorProfile, eValidMoments, eValidPerimeter, inValidate(), mBg, mExtendSize, mFg, mMajorD, and mMinorD.
Referenced by rcShape().
 {
   inValidate (eIsValid);
   mExtendSize = 0;
   mBg = uint8 (0);
   mFg = uint8 (0xff);
   inValidate (eValidDimensionConstraints);
   if (g == eAffine)
     {
       inValidate (eValidArea);
       inValidate (eValidPerimeter);
       inValidate (eValidCircularity);
       inValidate (eValidEllipseRatio);
     }
   if (g == eImage)
     {
       inValidate (eValidFrame );
       inValidate (eValidMinor );
       inValidate (eValidMajor );
       inValidate (eValidMajorProfile );
       inValidate (eValidMinorProfile );
       inValidate (eValidCom );
       inValidate (eValidAffineCom );
       inValidate (eValidMoments );
       inValidate (eValidAffineRect );
       inValidate (eValidAffineWindow );
     }
   mMajorD.reserve (1024);
   mMinorD.reserve (1024);
 }
void rcShape::setMask ()
Definition at line 414 of file rc_shape.cpp.
References rcWindow::height(), mBg, mFg, mFrame, mMask, mPoly, rcFillPolygon(), rmExceptionMacro, rcWindow::setAllPixels(), and rcWindow::width().
 {
   rcWindow mask(mFrame.width(), mFrame.height());
   mask.setAllPixels(mBg);
   rcFillPolygon(mPoly, mask, mFg);
   if (mask.isBound())
     {
       mMask = mask;
     }
   else
     {
       rmExceptionMacro (<<" rcShape setMask " << mask.isBound());
     }
 }
const rcPolygon& rcShape::shape () const inline
Definition at line 184 of file rc_shape.h.
References mPoly.
 {return mPoly;}
bool rcShape::testPeak ()
Definition at line 1084 of file rc_shape.cpp.
References peakDetect1d().
 {
   vector<float> tst (11);
   tst[0] = 4450.0f;
   tst[1] = 4451.0f;
   tst[2] = 4452.0f;
   tst[3] = 4453.0f;
   tst[4] = 4100.0f;
   tst[5] = 4212.0f;
   tst[6] = 4230.0f;
   tst[7] = 4449.0f;
   tst[8] = 4450.0f;
   tst[9] = 4449.0f;
   tst[10] = 4450.0f;
   rcDPair dp;
   peakDetect1d (tst, dp);
 }
double rcShape::tiny () inline
Definition at line 322 of file rc_shape.h.
Referenced by projectMI().
   {
     return 1e-10;
   }
bool rcShape::validate (enum Valid what)
Definition at line 268 of file rc_shape.cpp.
References mValidSet.
Referenced by majorEndConstraints(), needAffineRect(), needAffineWindow(), needArea(), needCenterOfmass(), needCircularity(), needEllipseRatio(), needMajorDimension(), needMass(), needMinorDimension(), needPerimeter(), profiles(), and rcShape().
 {
   mValidSet[what] = true;
   return mValidSet[what];
 }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcShape & s) friend
Definition at line 300 of file rc_shape.h.
   {
     o << "Com:    " << s.centerOfmass (eAffine) << endl;
     o << "Per:    " << s.perimeter () << endl;
     o << "area:   " << s.area () << endl;
     o << "Mass:   " << s.mass () << endl;
     o << "Affine:  " << s.affineRect() << endl;
     o << "Angle:  " << s.angle ().Double() << endl;
     o << "Major:  " << s.majorDimension () << endl;
     o << "Minor:  " << s.minorDimension () << endl;
     cout << "{" << endl;
     uint32 i(0);
     const vector<float>& mp = s.majorProfile();
     for (i = 0; i < mp.size()-1; i++) cout << "{" << i << "," << mp[i] << "},";
     cout << "{" << i << "," << mp[i] << "}};";
     cout << endl;
     return o;
   }
Member Data Documentation
rc2Dvector rcShape::mAffineCom private
Definition at line 343 of file rc_shape.h.
Referenced by copyFrom(), and needCenterOfmass().
rcWindow rcShape::mAffinedImage private
Definition at line 361 of file rc_shape.h.
Referenced by affineImage(), and profiles().
rc2Dvector rcShape::mAffineMedian private
Definition at line 343 of file rc_shape.h.
Referenced by copyFrom(), and needMedian().
rcAffineRectangle rcShape::mAffineRect private
Definition at line 357 of file rc_shape.h.
Referenced by copyFrom(), and needAffineRect().
rc2Fvector rcShape::mAffineSize private
Definition at line 344 of file rc_shape.h.
Referenced by copyFrom(), needAffineRect(), and needCenterOfmass().
rcAffineWindow rcShape::mAffineWindow private
Definition at line 358 of file rc_shape.h.
Referenced by copyFrom(), and needAffineWindow().
rcRadian rcShape::mAngle private
Definition at line 342 of file rc_shape.h.
Referenced by copyFrom().
double rcShape::mArea private
Definition at line 340 of file rc_shape.h.
Referenced by copyFrom(), and needArea().
uint8 rcShape::mBg private
Definition at line 388 of file rc_shape.h.
Referenced by reset(), and setMask().
double rcShape::mCircularity private
Definition at line 340 of file rc_shape.h.
Referenced by copyFrom(), and needCircularity().
rc2Dvector rcShape::mCom private
Definition at line 343 of file rc_shape.h.
Referenced by copyFrom(), and needCenterOfmass().
double rcShape::mEllipseRatio private
Definition at line 340 of file rc_shape.h.
Referenced by copyFrom(), and needEllipseRatio().
double rcShape::mElongation private
Definition at line 340 of file rc_shape.h.
Referenced by copyFrom().
int32 rcShape::mExtendSize private
Definition at line 351 of file rc_shape.h.
Referenced by copyFrom(), extendProfile(), needAffineRect(), operator==(), and reset().
uint8 rcShape::mFg private
Definition at line 389 of file rc_shape.h.
Referenced by reset(), and setMask().
rcWindow rcShape::mFrame private
Definition at line 353 of file rc_shape.h.
Referenced by copyFrom(), needAffineWindow(), operator==(), orthogonalBoundingBox(), profiles(), rcShape(), and setMask().
rcDPair rcShape::mInertia private
Definition at line 341 of file rc_shape.h.
Referenced by copyFrom().
float rcShape::mMajord private
Definition at line 349 of file rc_shape.h.
Referenced by copyFrom(), and needMajorDimension().
vector<float> rcShape::mMajorD private
Definition at line 359 of file rc_shape.h.
Referenced by copyFrom(), majorEndConstraints(), majorProfile(), needMajorDimension(), needMass(), needMedian(), operator==(), printCache(), profiles(), and reset().
rcDPair rcShape::mMajorEnds private
Definition at line 345 of file rc_shape.h.
Referenced by copyFrom(), majorEnds(), and needMajorDimension().
rcDPair rcShape::mMajorOneEndConstraints private
Definition at line 347 of file rc_shape.h.
Referenced by majorEndConstraints().
rcDPair rcShape::mMajorOtherEndConstraints private
Definition at line 348 of file rc_shape.h.
Referenced by majorEndConstraints().
rcWindow rcShape::mMask private
Definition at line 354 of file rc_shape.h.
Referenced by needCenterOfmass(), profiles(), rcShape(), and setMask().
double rcShape::mMass private
Definition at line 340 of file rc_shape.h.
Referenced by copyFrom(), and needMass().
rc2Dvector rcShape::mMedian private
Definition at line 343 of file rc_shape.h.
Referenced by copyFrom(), and needMedian().
float rcShape::mMinord private
Definition at line 349 of file rc_shape.h.
Referenced by copyFrom(), needMinorDimension(), and operator==().
vector<float> rcShape::mMinorD private
Definition at line 360 of file rc_shape.h.
Referenced by copyFrom(), minorProfile(), needMass(), needMedian(), needMinorDimension(), operator==(), printCache(), profiles(), and reset().
rcDPair rcShape::mMinorEnds private
Definition at line 346 of file rc_shape.h.
Referenced by copyFrom(), minorEnds(), and needMinorDimension().
double rcShape::mPerimeter private
Definition at line 340 of file rc_shape.h.
Referenced by copyFrom(), and needPerimeter().
rcPolygon rcShape::mPoly private
Definition at line 355 of file rc_shape.h.
Referenced by copyFrom(), needAffineRect(), needArea(), needCenterOfmass(), needCircularity(), needEllipseRatio(), needPerimeter(), operator==(), rcShape(), setMask(), and shape().
bitset<eNumValids> rcShape::mValidSet private
Definition at line 338 of file rc_shape.h.
Referenced by copyFrom(), inValidate(), isValid(), operator==(), and validate().
float rcShape::mX private
Definition at line 350 of file rc_shape.h.
Referenced by copyFrom(), needCenterOfmass(), needMass(), and operator==().
float rcShape::mXX private
Definition at line 350 of file rc_shape.h.
Referenced by copyFrom(), needMass(), and operator==().
float rcShape::mY private
Definition at line 350 of file rc_shape.h.
Referenced by copyFrom(), needCenterOfmass(), needMass(), and operator==().
float rcShape::mYY private
Definition at line 350 of file rc_shape.h.
Referenced by copyFrom(), needMass(), and operator==().
The documentation for this class was generated from the following files:
include/analysis/rc_shape.h
src/analysis/code/rc_shape.cpp