Visible: TIFFImageIO Class Reference
TIFFImageIO Class Reference
#include <include/visual/rc_tiff.h>
Public Types
enum IOComponentType {
UNKNOWNCOMPONENTTYPE, UCHAR, CHAR, USHORT,
SHORT, UINT, INT, ULONG,
LONG, FLOAT, DOUBLE
}
enum IOPixelType {
UNKNOWNPIXELTYPE, SCALAR, RGB, RGBA,
OFFSET, VECTOR, POINT, COVARIANTVECTOR
}
enum {
NOFORMAT, RGB_, GRAYSCALE, PALETTE_RGB,
PALETTE_GRAYSCALE, OTHER
}
enum {
NoCompression, PackBits, JPEG, Deflate,
LZW
}
Public Member Functions
TIFFImageIO ()
~TIFFImageIO ()
TIFFImageIO (const TIFFImageIO &)
void operator= (const TIFFImageIO &)
rmSetStringMacro (FileName)
rmGetStringMacro (FileName)
bool CanReadFile (const char *)
void ReadImageInformation ()
bool isSTKfile () const
int32 width () const
int32 height () const
rcPixel rcDepth () const
rcWindow Read ()
vector< rcWindow > ReadPages ()
rcWindow ReadSinglePage ()
int32 numberOfPages () const
reByteOrder byteOrder () const
void SetNumberOfDimensions (unsigned int dim)
void SetNumberOfComponents (unsigned int c)
unsigned int GetNumberOfComponents () const
void SetPixelType (IOPixelType pt)
IOComponentType GetComponentType ()
void SetIORegion (const ImageIORegion _arg)
const ImageIORegion & GetIORegion ()
Protected Member Functions
void WriteSlice (std::string &fileName, const void *buffer)
void WriteVolume (std::string &fileName, const void *buffer)
void InitializeColors ()
rcWindow ReadGenericImage ()
int EvaluateImageAt (void *out, void *in)
unsigned int GetFormat ()
void GetColor (int index, unsigned short *red, unsigned short *green, unsigned short *blue)
Private Attributes
bool m_Initialized
bool mIsTiled
std::string mFileName
unsigned int m_NumberOfComponents
unsigned int m_NumberOfDimensions
unsigned short * ColorRed
unsigned short * ColorGreen
unsigned short * ColorBlue
int TotalColors
unsigned int ImageFormat
TIFFReaderInternal * mInternalImage
int m_Compression
int mImageCount
ImageIORegion m_IORegion
std::vector< double > m_Origin
std::vector< double > m_Spacing
std::vector< unsigned int > m_Strides
vector< uint32 > mStripoffsets
vector< uint32 > mStripbytecounts
uint32 mStripperimage
int32 mRootHeight
int32 mRowperstrip
std::vector< unsigned int > m_Dimensions
IOComponentType m_ComponentType
IOPixelType m_PixelType
bool m_UseCompression
rcPixel mRCdepth
reByteOrder mFileBO
Detailed Description
Definition at line 233 of file rc_tiff.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NOFORMAT
RGB_
GRAYSCALE
PALETTE_RGB
PALETTE_GRAYSCALE
OTHER
Definition at line 275 of file rc_tiff.h.
 { NOFORMAT, RGB_, GRAYSCALE, PALETTE_RGB, PALETTE_GRAYSCALE, OTHER };
anonymous enum
Enumerator
NoCompression
PackBits
JPEG
Deflate
LZW
Definition at line 276 of file rc_tiff.h.
 { NoCompression, PackBits, JPEG, Deflate, LZW};
enum TIFFImageIO::IOComponentType
Enumerator
UNKNOWNCOMPONENTTYPE
UCHAR
CHAR
USHORT
SHORT
UINT
INT
ULONG
LONG
FLOAT
DOUBLE
Definition at line 245 of file rc_tiff.h.
                 {UNKNOWNCOMPONENTTYPE,UCHAR,CHAR,USHORT,
          SHORT,UINT,INT, ULONG,LONG, FLOAT,DOUBLE}
enum TIFFImageIO::IOPixelType
Enumerator
UNKNOWNPIXELTYPE
SCALAR
RGB
RGBA
OFFSET
VECTOR
POINT
COVARIANTVECTOR
Definition at line 248 of file rc_tiff.h.
                 {UNKNOWNPIXELTYPE,SCALAR,RGB,RGBA,OFFSET,VECTOR,
                  POINT,COVARIANTVECTOR}
Constructor & Destructor Documentation
TIFFImageIO::TIFFImageIO ()
Definition at line 312 of file rc_tiff.cpp.
References eByteOrderUnknown, InitializeColors(), m_ComponentType, m_Compression, m_Origin, m_PixelType, m_Spacing, m_UseCompression, mFileBO, mInternalImage, mRCdepth, PackBits, rcPixelUnknown, SCALAR, SetNumberOfDimensions(), and UCHAR.
 {
     SetNumberOfDimensions(2);
     m_PixelType = SCALAR;
     m_ComponentType = UCHAR;
     InitializeColors();
     mInternalImage = new TIFFReaderInternal;
     m_Spacing[0] = 1.0;
     m_Spacing[1] = 1.0;
     m_Origin[0] = 0.0;
     m_Origin[1] = 0.0;
     m_Compression = TIFFImageIO::PackBits;
     m_UseCompression = true;
     mRCdepth =  rcPixelUnknown;
     mFileBO = eByteOrderUnknown;
 }
TIFFImageIO::~TIFFImageIO ()
Definition at line 504 of file rc_tiff.cpp.
References TIFFReaderInternal::Clean(), and mInternalImage.
 {
     mInternalImage->Clean();
     delete mInternalImage;
 }
TIFFImageIO::TIFFImageIO (const TIFFImageIO &)
Member Function Documentation
reByteOrder TIFFImageIO::byteOrder () const
Definition at line 358 of file rc_tiff.cpp.
References mFileBO.
Referenced by Read(), and ReadGenericImage().
 {
     return mFileBO;
 }
bool TIFFImageIO::CanReadFile (const char * file)
Definition at line 510 of file rc_tiff.cpp.
References TIFFReaderInternal::Clean(), mInternalImage, TIFFReaderInternal::Open(), ReadImageInformation(), and TIFFSetErrorHandler().
Referenced by rcEngineImpl::loadMovie(), and rcWindow::rcWindow().
 {
 // First check the extension
     std::string filename = file;
     if(  filename == "" )
     {
 //  rmWarningMacro(<<"No filename specified.");
         return false;
     }
 // Now check if this is a valid TIFF image
     TIFFErrorHandler save = TIFFSetErrorHandler(0);
     int res = mInternalImage->Open(file);
     if (res)
     {
         ReadImageInformation ();
         TIFFSetErrorHandler(save);
         return true;
     }
     mInternalImage->Clean();
     TIFFSetErrorHandler(save);
     return false;
 }
int TIFFImageIO::EvaluateImageAt (void * out, void * in) protected
Definition at line 597 of file rc_tiff.cpp.
References GetColor(), GetFormat(), GRAYSCALE, green, m_ComponentType, mInternalImage, PALETTE_GRAYSCALE, PALETTE_RGB, PHOTOMETRIC_MINISBLACK, TIFFReaderInternal::Photometrics, red, RGB_, TIFFReaderInternal::spp, and USHORT.
 {
     unsigned char *image = (unsigned char*)out;
     unsigned char *source = (unsigned char*)in;
     int increment;
     unsigned short red, green, blue, alpha;
     switch ( GetFormat() )
     {
         case TIFFImageIO::GRAYSCALE:
         if ( mInternalImage->Photometrics ==
             PHOTOMETRIC_MINISBLACK )
         {
             if(m_ComponentType == USHORT)
             {
                 unsigned short *image = (unsigned short*)out;
                 unsigned short *source = (unsigned short*)in;
                 *image = *source;
             }
             else
             {
                 *image = *source;
             }
         }
         else
         {
             *image = ~( *source );
         }
         increment = 1;
         break;
         case TIFFImageIO::PALETTE_GRAYSCALE:
         GetColor(*source, &red, &green, &blue);
         *image = static_cast<unsigned char>(red >> 8);
         increment = 1;
         break;
         case TIFFImageIO::RGB_:
         red   = *(source);
         green = *(source+1);
         blue  = *(source+2);
         *(image)   = red;
         *(image+1) = green;
         *(image+2) = blue;
         if ( mInternalImage->spp == 4 )
         {
             alpha = *(source+3);
             *(image+3) = 255-alpha;
         }
         increment = mInternalImage->spp;
         break;
         case TIFFImageIO::PALETTE_RGB:
         GetColor(*source, &red, &green, &blue);
         *(image)   = static_cast<unsigned char>(red >> 8);
         *(image+1) = static_cast<unsigned char>(green >> 8);
         *(image+2) = static_cast<unsigned char>(blue >> 8);
         increment = 3;
         break;
         default:
         return 0;
     }
     return increment;
 }
void TIFFImageIO::GetColor (int index, unsigned short * red, unsigned short * green, unsigned short * blue) protected
Definition at line 661 of file rc_tiff.cpp.
References TIFFReaderInternal::bps, ColorBlue, ColorGreen, ColorRed, endl(), TIFFReaderInternal::Image, mInternalImage, PHOTOMETRIC_PALETTE, TIFFReaderInternal::Photometrics, TIFFGetField(), TIFFTAG_COLORMAP, TIFFTAG_PHOTOMETRIC, and TotalColors.
Referenced by EvaluateImageAt(), and GetFormat().
 {
     *red   = 0;
     *green = 0;
     *blue  = 0;
     if ( index < 0 )
     {
         std::cout << "Color index has to be greater than 0" << std::endl;
         return;
     }
     if ( TotalColors > 0 &&
         ColorRed && ColorGreen && ColorBlue )
     {
         if ( index >= TotalColors )
         {
             std::cout << "Color index has to be less than number of colors ("
                 << TotalColors << ")" << std::endl;
             return;
         }
         *red   = *(ColorRed   + index);
         *green = *(ColorGreen + index);
         *blue  = *(ColorBlue  + index);
         return;
     }
     unsigned short photometric;
     if (!TIFFGetField(mInternalImage->Image, TIFFTAG_PHOTOMETRIC, &photometric))
     {
         if ( mInternalImage->Photometrics != PHOTOMETRIC_PALETTE )
         {
             std::cout << "You can only access colors for palette images" << std::endl;
             return;
         }
     }
     unsigned short *red_orig, *green_orig, *blue_orig;
     switch (mInternalImage->bps)
     {
         case 1: case 2: case 4:
         case 8: case 16:
         break;
         default:
         std::cout <<  "Sorry, can not image with "
             << mInternalImage->bps
             << "-bit samples" << std::endl;
         return;
     }
     if (!TIFFGetField(mInternalImage->Image, TIFFTAG_COLORMAP,
         &red_orig, &green_orig, &blue_orig))
     {
         std::cout << "Missing required \"Colormap\" tag" << std::endl;
         return;
     }
     TotalColors = (1L << mInternalImage->bps);
     if ( index >= TotalColors )
     {
         std::cout << "Color index has to be less than number of colors ("
             << TotalColors << ")" << std::endl;
         return;
     }
     ColorRed   =   red_orig;
     ColorGreen = green_orig;
     ColorBlue  =  blue_orig;
     *red   = *(red_orig   + index);
     *green = *(green_orig + index);
     *blue  = *(blue_orig  + index);
 }
TIFFImageIO::IOComponentType TIFFImageIO::GetComponentType ()
Definition at line 380 of file rc_tiff.cpp.
References m_ComponentType.
Referenced by Read().
 {
   return m_ComponentType;
 }
unsigned int TIFFImageIO::GetFormat () protected
Definition at line 735 of file rc_tiff.cpp.
References GetColor(), GRAYSCALE, green, ImageFormat, mInternalImage, NOFORMAT, OTHER, PALETTE_GRAYSCALE, PALETTE_RGB, PHOTOMETRIC_MINISBLACK, PHOTOMETRIC_MINISWHITE, PHOTOMETRIC_PALETTE, PHOTOMETRIC_RGB, PHOTOMETRIC_YCBCR, TIFFReaderInternal::Photometrics, red, and RGB_.
Referenced by EvaluateImageAt(), and ReadImageInformation().
 {
     unsigned int cc;
     if ( ImageFormat != TIFFImageIO::NOFORMAT )
     {
         return ImageFormat;
     }
     switch ( mInternalImage->Photometrics )
     {
         case PHOTOMETRIC_RGB:
         case PHOTOMETRIC_YCBCR:
         ImageFormat = TIFFImageIO::RGB_;
         return ImageFormat;
         case PHOTOMETRIC_MINISWHITE:
         case PHOTOMETRIC_MINISBLACK:
         ImageFormat = TIFFImageIO::GRAYSCALE;
         return ImageFormat;
         case PHOTOMETRIC_PALETTE:
         for( cc=0; cc<256; cc++ )
         {
             unsigned short red, green, blue;
             GetColor( cc, &red, &green, &blue );
             if ( red != green || red != blue )
             {
                 ImageFormat = TIFFImageIO::PALETTE_RGB;
                 return ImageFormat;
             }
         }
         ImageFormat = TIFFImageIO::PALETTE_GRAYSCALE;
         return ImageFormat;
     }
     ImageFormat = TIFFImageIO::OTHER;
     return ImageFormat;
 }
const ImageIORegion & TIFFImageIO::GetIORegion ()
Definition at line 391 of file rc_tiff.cpp.
References m_IORegion.
 {
   return m_IORegion;
 }
unsigned int TIFFImageIO::GetNumberOfComponents () const
Definition at line 368 of file rc_tiff.cpp.
References m_NumberOfComponents.
 {
   return m_NumberOfComponents;
 }
int32 TIFFImageIO::height () const
Definition at line 348 of file rc_tiff.cpp.
References TIFFReaderInternal::Height, and mInternalImage.
Referenced by Read(), ReadGenericImage(), and ReadImageInformation().
 {
     return (int32) mInternalImage->Height;
 }
void TIFFImageIO::InitializeColors () protected
Definition at line 334 of file rc_tiff.cpp.
References ColorBlue, ColorGreen, ColorRed, ImageFormat, NOFORMAT, and TotalColors.
Referenced by TIFFImageIO().
 {
     ColorRed    = 0;
     ColorGreen  = 0;
     ColorBlue   = 0;
     TotalColors = -1;
     ImageFormat = TIFFImageIO::NOFORMAT;
 }
bool TIFFImageIO::isSTKfile () const
Definition at line 499 of file rc_tiff.cpp.
References mInternalImage, and TIFFReaderInternal::mIsSTKfile.
Referenced by numberOfPages().
 {
     return mInternalImage->mIsSTKfile;
 }
int32 TIFFImageIO::numberOfPages () const
Definition at line 492 of file rc_tiff.cpp.
References isSTKfile(), mInternalImage, and TIFFReaderInternal::NumberOfPages.
Referenced by ReadPages().
 {
    if(mInternalImage && isSTKfile ())
     return mInternalImage->NumberOfPages;
 }
void TIFFImageIO::operator= (const TIFFImageIO &)
rcPixel TIFFImageIO::rcDepth () const
Definition at line 353 of file rc_tiff.cpp.
References mRCdepth.
Referenced by ReadGenericImage().
 {
     return mRCdepth;
 }
rcWindow TIFFImageIO::Read ()
Definition at line 857 of file rc_tiff.cpp.
References byteOrder(), TIFFReaderInternal::CanRead(), TIFFReaderInternal::Compression, COMPRESSION_OJPEG, endl(), GetComponentType(), height(), TIFFReaderInternal::Image, mInternalImage, ORIENTATION_TOPLEFT, rcPixel32, ReadGenericImage(), rfPlatformByteOrder(), rmAssert, rmExceptionMacro, rcWindow::rowPointer(), SwabLongTriple(), TIFFReadRGBAImageOriented(), UCHAR, USHORT, rcWindow::width(), and width().
Referenced by ReadPages(), and ReadSinglePage().
 {
     if ( mInternalImage->Compression == COMPRESSION_OJPEG )
     {
         rmExceptionMacro (<< "This reader cannot read old JPEG compression");
     }
     //@note if we can not read it try the do all ReadRGBA
         //The problem is that this only supports 32 bit images
     if ( !mInternalImage->CanRead() )
     {
         //@note using rcWindow since it is ref counted and will be deleted upon dtor
         rcWindow tempImage (width (), height (), rcPixel32);
         if (TIFFReadRGBAImageOriented(mInternalImage->Image,
             width(), height(), (uint32*) tempImage.rowPointer (0), ORIENTATION_TOPLEFT))
         {
         //@note rcWindow assues that the start of every row is (currently 16byte) aligned
         //there for we copy from the contigious space to the all-rows-aligned space
             if( GetComponentType () == USHORT)
             {
                 rmExceptionMacro (<< " multibyte components not supported ");
             }
             else if ( GetComponentType () == UCHAR)
             {
             bool badindians = rfPlatformByteOrder() != byteOrder ();
             for (uint32 j = 0; j < height (); j++)
                     {
                     if (badindians)
                             SwabLongTriple ((uint32 *) tempImage.rowPointer (j), tempImage.width () );
                     }
 //              rcSharedFrameBufPtr buf(new rcFrame ((char *) (tempImage.rowPointer (0)), tempImage.rowUpdate (),
 //                  width (), height (), rcPixel32, false));
 //              return rcWindow (buf);
                 return tempImage;
             }
             else
             {
                 rmAssert (0);
             }
         }
         else
         {
             std::cout << "Problem reading RGB image" << std::endl;
             return rcWindow ();
         }
     }
     else
     {
         return ReadGenericImage();
     }
 }
rcWindow TIFFImageIO::ReadGenericImage () protected
Definition at line 537 of file rc_tiff.cpp.
References TIFFReaderInternal::bps, byteOrder(), height(), TIFFReaderInternal::Image, mImageCount, mInternalImage, mRowperstrip, mStripbytecounts, mStripoffsets, mStripperimage, TIFFReaderInternal::PlanarConfig, PLANARCONFIG_CONTIG, rcDepth(), rcPixel16, rcPixel32, rcPixelUnknown, rfPlatformByteOrder(), rmExceptionMacro, rcWindow::rowPointer(), TIFFReaderInternal::spp, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripoffset, tiff::tif_dir, TIFFReadRawStrip(), TIFFSwabArrayOfShort(), rcWindow::width(), and width().
Referenced by Read().
 {
     if ( mInternalImage->PlanarConfig != PLANARCONFIG_CONTIG  ||  rcDepth () == rcPixelUnknown)
 //      GetFormat () == TIFFImageIO::PALETTE_RGB ||
     {
         rmExceptionMacro (<< "This reader can only do PLANARCONFIG_CONTIG");
     }
     bool success = true; // start believing
     rcWindow thisImage (width (), height (), rcDepth ());
     uint32 planeOffset = mImageCount * (mStripoffsets[mStripperimage-1]+mStripbytecounts[mStripperimage-1] - mStripoffsets [0]);
     planeOffset += mStripoffsets[0];
     mInternalImage->Image->tif_dir.td_stripoffset[0] = planeOffset;
     for (uint32 i = 1; i < mStripperimage; i++)
         mInternalImage->Image->tif_dir.td_stripoffset[i] = mInternalImage->Image->tif_dir.td_stripoffset[i-1] +
         mInternalImage->Image->tif_dir.td_stripbytecount[i-1];
     if (rcDepth() == rcPixel32 && mInternalImage->spp == 3 && mInternalImage->bps == 8)
     {
         rcWindow tmpStore (width(), mRowperstrip, rcDepth () );
         for(uint y=0; success && (y< mStripperimage ); ++y)
         {
             success &= ( TIFFReadRawStrip(mInternalImage->Image, (tstrip_t) ( y ) ,
                 tmpStore.rowPointer (0), -1) > 0);
             if( !success ) break;
             // for each row in the strip
             for (uint32 rows = 0; rows < mRowperstrip; rows++)
             {
                     // Get the right row in the dest
                     // unpack the row in 24bit source in to 32 bit dest
             }
         }
     }
     else
     {
         for(uint y=0; success && (y< mStripperimage ); ++y)
         {
             success &= ( TIFFReadRawStrip(mInternalImage->Image, (tstrip_t) ( y ) ,
                 thisImage.rowPointer (y * mRowperstrip), -1) > 0);
             if( !success ) break;
         }
         if (rcDepth() == rcPixel16 && (rfPlatformByteOrder() != byteOrder ()))
         {
             for (uint32 rows = 0; rows < height (); rows++)
                 TIFFSwabArrayOfShort ((uint16*) thisImage.rowPointer (rows), thisImage.width () );
         }
     }
     if (success)
         return thisImage;
     else
         return rcWindow ();
 }
void TIFFImageIO::ReadImageInformation ()
Definition at line 396 of file rc_tiff.cpp.
References TIFFReaderInternal::bps, TIFFReaderInternal::CanRead(), eByteOrderBigEndian, eByteOrderLittleEndian, GetFormat(), GRAYSCALE, height(), TIFFReaderInternal::Image, m_ComponentType, m_Dimensions, m_Origin, m_Spacing, mFileBO, mInternalImage, mIsTiled, mRCdepth, mRootHeight, mRowperstrip, mStripbytecounts, mStripoffsets, mStripperimage, TIFFReaderInternal::NumberOfPages, TIFFReaderInternal::NumberOfTiles, PALETTE_GRAYSCALE, PALETTE_RGB, rcPixel16, rcPixel32, rcPixel8, rcPixelUnknown, RGB, RGB_, RGBA, SCALAR, SetNumberOfComponents(), SetNumberOfDimensions(), SetPixelType(), TIFFReaderInternal::spp, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripoffset, TIFFDirectory::td_stripsperimage, tiff::tif_dir, TIFFIsBigEndian(), TIFFReaderInternal::TileHeight, TIFFReaderInternal::TileWidth, UCHAR, USHORT, and width().
Referenced by CanReadFile(), rcEngineImpl::loadMovie(), and rcWindow::rcWindow().
 {
     m_Spacing[0] = 1.0;  // We'll look for TIFF pixel size information later,
     m_Spacing[1] = 1.0;  // but set the defaults now
     m_Origin[0] = 0.0;
     m_Origin[1] = 0.0;
     m_Dimensions[0] = width ();
     m_Dimensions[1] = height ();
     switch ( GetFormat() )
     {
         case TIFFImageIO::GRAYSCALE:
         case TIFFImageIO::PALETTE_GRAYSCALE:
         SetNumberOfComponents( 1 );
         SetPixelType(SCALAR);
         break;
         case TIFFImageIO::RGB_:
         SetNumberOfComponents( mInternalImage->spp );
         SetPixelType(RGB);
         break;
         case TIFFImageIO::PALETTE_RGB:
         SetNumberOfComponents( 3 );
         SetPixelType(RGB);
         break;
         default:
         SetNumberOfComponents( 4 );
         SetPixelType(RGBA);
     }
     if ( !mInternalImage->CanRead() )
     {
         SetNumberOfComponents( 4 );
         SetPixelType(RGBA);
     }
     m_ComponentType = (mInternalImage->bps <= 8) ? UCHAR : USHORT;
 // if the tiff file is multi-pages
     if(mInternalImage->NumberOfPages>0)
     {
         SetNumberOfDimensions(3);
         m_Dimensions[2] = mInternalImage->NumberOfPages;
         m_Spacing[2] = 1.0;
         m_Origin[2] = 0.0;
     }
 // if the tiff is tiled
     if(mInternalImage->NumberOfTiles>0)
     {
         SetNumberOfDimensions(3);
         m_Dimensions[0] = mInternalImage->TileWidth;
         m_Dimensions[1] = mInternalImage->TileHeight;
         m_Dimensions[2] = mInternalImage->NumberOfTiles;
         m_Spacing[2] = 1.0;
         m_Origin[2] = 0.0;
         mIsTiled = true;
     }
     //@note set the rcPixel size that matched our reading
     mRCdepth = (mInternalImage->bps == 8 && mInternalImage->spp == 1) ?
         rcPixel8 : (mInternalImage->bps == 16 && mInternalImage->spp == 1) ?
         rcPixel16 : (mInternalImage->bps == 8 && mInternalImage->spp == 3) ?
         rcPixel32 : (mInternalImage->bps == 8 && mInternalImage->spp == 4) ?
         rcPixel32 : rcPixelUnknown;
     mStripperimage = (uint32) mInternalImage->Image->tif_dir.td_stripsperimage;
     mStripoffsets.resize (mStripperimage);
     for (uint32 ii = 0; ii < mStripoffsets.size (); ii++) mStripoffsets[ii] = mInternalImage->Image->tif_dir.td_stripoffset[ii];
     mStripbytecounts.resize (mStripperimage);
     for (uint32 ii = 0; ii < mStripbytecounts.size (); ii++) mStripbytecounts[ii] = mInternalImage->Image->tif_dir.td_stripbytecount[ii];
     mRootHeight = mStripperimage * height ();
     mRowperstrip = mInternalImage->Image->tif_dir.td_rowsperstrip;
     mFileBO = TIFFIsBigEndian(mInternalImage->Image) == 0 ? eByteOrderLittleEndian : eByteOrderBigEndian;
     return;
 }
vector< rcWindow > TIFFImageIO::ReadPages ()
Read a multipage tiff
Definition at line 815 of file rc_tiff.cpp.
References mImageCount, numberOfPages(), and Read().
Referenced by rcEngineImpl::loadMovie().
 {
     vector<rcWindow> pages (numberOfPages ());
     mImageCount = 0;
     for(unsigned int page = 0;page<pages.size ();page++)
     {
         //@note if we can not read it try the do all ReadRGBA
         //The problem is that this only supports 32 bit images
         //@note change when time and z are properly incorported
         pages[page] = Read ();
         pages[page].frameBuf()->setTimestamp( rcTimestamp((double) page) );
         mImageCount++;
 //      TIFFReadDirectory(mInternalImage->Image);
     }
     return pages;
 }
rcWindow TIFFImageIO::ReadSinglePage ()
Read a multipage tiff
Definition at line 833 of file rc_tiff.cpp.
References mImageCount, and Read().
Referenced by rcWindow::rcWindow().
 {
     rcWindow page;
     mImageCount = 1;
     page = Read ();
     return page;
 }
TIFFImageIO::rmGetStringMacro (FileName)
TIFFImageIO::rmSetStringMacro (FileName)
Set/Get the name of the file to be read.
void TIFFImageIO::SetIORegion (const ImageIORegion _arg)
Definition at line 385 of file rc_tiff.cpp.
References m_IORegion.
 {
   if (this->m_IORegion != _arg)
     this->m_IORegion = _arg;
 }
void TIFFImageIO::SetNumberOfComponents (unsigned int c)
Definition at line 363 of file rc_tiff.cpp.
References m_NumberOfComponents.
Referenced by ReadImageInformation().
 {
   m_NumberOfComponents = c;
 }
void TIFFImageIO::SetNumberOfDimensions (unsigned int dim)
Definition at line 479 of file rc_tiff.cpp.
References m_Dimensions, m_NumberOfDimensions, m_Origin, m_Spacing, and m_Strides.
Referenced by ReadImageInformation(), and TIFFImageIO().
  {
    if(dim != m_NumberOfDimensions)
      {
     m_Dimensions.resize( dim );
     m_Origin.resize( dim );
     m_Spacing.resize( dim );
     m_Strides.resize( dim+2 );
     m_NumberOfDimensions = dim;
      }
  }
void TIFFImageIO::SetPixelType (IOPixelType pt)
Definition at line 374 of file rc_tiff.cpp.
References m_PixelType.
Referenced by ReadImageInformation().
 {
   m_PixelType = pt;
 }
int32 TIFFImageIO::width () const
Definition at line 343 of file rc_tiff.cpp.
References mInternalImage, and TIFFReaderInternal::Width.
Referenced by Read(), ReadGenericImage(), and ReadImageInformation().
 {
     return (int32) mInternalImage->Width;
 }
void TIFFImageIO::WriteSlice (std::string & fileName, const void * buffer) protected
void TIFFImageIO::WriteVolume (std::string & fileName, const void * buffer) protected
Member Data Documentation
unsigned short* TIFFImageIO::ColorBlue private
Definition at line 304 of file rc_tiff.h.
Referenced by GetColor(), and InitializeColors().
unsigned short* TIFFImageIO::ColorGreen private
Definition at line 303 of file rc_tiff.h.
Referenced by GetColor(), and InitializeColors().
unsigned short* TIFFImageIO::ColorRed private
Definition at line 302 of file rc_tiff.h.
Referenced by GetColor(), and InitializeColors().
unsigned int TIFFImageIO::ImageFormat private
Definition at line 306 of file rc_tiff.h.
Referenced by GetFormat(), and InitializeColors().
IOComponentType TIFFImageIO::m_ComponentType private
Definition at line 324 of file rc_tiff.h.
Referenced by EvaluateImageAt(), GetComponentType(), ReadImageInformation(), and TIFFImageIO().
int TIFFImageIO::m_Compression private
Definition at line 308 of file rc_tiff.h.
Referenced by TIFFImageIO().
std::vector<unsigned int> TIFFImageIO::m_Dimensions private
The array which stores the number of pixels in the x, y, z directions.
Definition at line 323 of file rc_tiff.h.
Referenced by ReadImageInformation(), and SetNumberOfDimensions().
bool TIFFImageIO::m_Initialized private
Definition at line 297 of file rc_tiff.h.
ImageIORegion TIFFImageIO::m_IORegion private
Definition at line 311 of file rc_tiff.h.
Referenced by GetIORegion(), and SetIORegion().
unsigned int TIFFImageIO::m_NumberOfComponents private
Definition at line 300 of file rc_tiff.h.
Referenced by GetNumberOfComponents(), and SetNumberOfComponents().
unsigned int TIFFImageIO::m_NumberOfDimensions private
Definition at line 301 of file rc_tiff.h.
Referenced by SetNumberOfDimensions().
std::vector<double> TIFFImageIO::m_Origin private
Definition at line 312 of file rc_tiff.h.
Referenced by ReadImageInformation(), SetNumberOfDimensions(), and TIFFImageIO().
IOPixelType TIFFImageIO::m_PixelType private
Definition at line 325 of file rc_tiff.h.
Referenced by SetPixelType(), and TIFFImageIO().
std::vector<double> TIFFImageIO::m_Spacing private
Definition at line 313 of file rc_tiff.h.
Referenced by ReadImageInformation(), SetNumberOfDimensions(), and TIFFImageIO().
std::vector<unsigned int> TIFFImageIO::m_Strides private
Definition at line 314 of file rc_tiff.h.
Referenced by SetNumberOfDimensions().
bool TIFFImageIO::m_UseCompression private
Definition at line 326 of file rc_tiff.h.
Referenced by TIFFImageIO().
reByteOrder TIFFImageIO::mFileBO private
Definition at line 328 of file rc_tiff.h.
Referenced by byteOrder(), ReadImageInformation(), and TIFFImageIO().
std::string TIFFImageIO::mFileName private
Definition at line 299 of file rc_tiff.h.
int TIFFImageIO::mImageCount private
Definition at line 309 of file rc_tiff.h.
Referenced by ReadGenericImage(), ReadPages(), and ReadSinglePage().
TIFFReaderInternal* TIFFImageIO::mInternalImage private
Definition at line 307 of file rc_tiff.h.
Referenced by CanReadFile(), EvaluateImageAt(), GetColor(), GetFormat(), height(), isSTKfile(), numberOfPages(), Read(), ReadGenericImage(), ReadImageInformation(), TIFFImageIO(), width(), and ~TIFFImageIO().
bool TIFFImageIO::mIsTiled private
Definition at line 298 of file rc_tiff.h.
Referenced by ReadImageInformation().
rcPixel TIFFImageIO::mRCdepth private
Definition at line 327 of file rc_tiff.h.
Referenced by rcDepth(), ReadImageInformation(), and TIFFImageIO().
int32 TIFFImageIO::mRootHeight private
Definition at line 319 of file rc_tiff.h.
Referenced by ReadImageInformation().
int32 TIFFImageIO::mRowperstrip private
Definition at line 320 of file rc_tiff.h.
Referenced by ReadGenericImage(), and ReadImageInformation().
vector<uint32> TIFFImageIO::mStripbytecounts private
Definition at line 317 of file rc_tiff.h.
Referenced by ReadGenericImage(), and ReadImageInformation().
vector<uint32> TIFFImageIO::mStripoffsets private
Definition at line 316 of file rc_tiff.h.
Referenced by ReadGenericImage(), and ReadImageInformation().
uint32 TIFFImageIO::mStripperimage private
Definition at line 318 of file rc_tiff.h.
Referenced by ReadGenericImage(), and ReadImageInformation().
int TIFFImageIO::TotalColors private
Definition at line 305 of file rc_tiff.h.
Referenced by GetColor(), and InitializeColors().
The documentation for this class was generated from the following files:
include/visual/rc_tiff.h
src/visual/code/rc_tiff.cpp