Visible: error_handler_body Class Reference
error_handler_body Class Reference
Public Member Functions
error_handler_body (otext &device, unsigned limit)
~error_handler_body (void)
otext & device (void)
unsigned limit (void) const
void set_limit (unsigned limit)
unsigned count (void) const
void set_count (unsigned count)
void increment (void)
bool limit_reached (void) const
Private Attributes
otext m_device
unsigned m_limit
unsigned m_count
Detailed Description
Definition at line 1378 of file error_handler.cpp.
Constructor & Destructor Documentation
error_handler_body::error_handler_body (otext & device, unsigned limit) inline
Definition at line 1385 of file error_handler.cpp.
                                                     :
     m_device(device), m_limit(limit), m_count(0)
     {
     }
error_handler_body::~error_handler_body (void) inline
Definition at line 1389 of file error_handler.cpp.
 {}
Member Function Documentation
unsigned error_handler_body::count (void) const inline
Definition at line 1394 of file error_handler.cpp.
References m_count.
Referenced by error_handler::error_count(), and set_count().
 {return m_count;}
otext& error_handler_body::device (void) inline
Definition at line 1391 of file error_handler.cpp.
References m_device.
Referenced by error_handler::device(), and error_handler::~error_handler().
 {return m_device;}
void error_handler_body::increment (void) inline
Definition at line 1396 of file error_handler.cpp.
References m_count.
 {++m_count;}
unsigned error_handler_body::limit (void) const inline
Definition at line 1392 of file error_handler.cpp.
References m_limit.
Referenced by error_handler::error_limit(), and set_limit().
 {return m_limit;}
bool error_handler_body::limit_reached (void) const inline
Definition at line 1397 of file error_handler.cpp.
References m_count, and m_limit.
 {return m_limit > 0 && m_count >= m_limit;}
void error_handler_body::set_count (unsigned count) inline
Definition at line 1395 of file error_handler.cpp.
References count(), and m_count.
Referenced by error_handler::reset_error_count().
 {m_count = count;}
void error_handler_body::set_limit (unsigned limit) inline
Definition at line 1393 of file error_handler.cpp.
References limit(), and m_limit.
 {m_limit = limit;}
Member Data Documentation
unsigned error_handler_body::m_count private
Definition at line 1383 of file error_handler.cpp.
Referenced by count(), increment(), limit_reached(), and set_count().
otext error_handler_body::m_device private
Definition at line 1381 of file error_handler.cpp.
Referenced by device().
unsigned error_handler_body::m_limit private
Definition at line 1382 of file error_handler.cpp.
Referenced by limit(), limit_reached(), and set_limit().
The documentation for this class was generated from the following file:
include/stlplus/error_handler.cpp