Visible: rcAnalyzerOptions Class Reference
rcAnalyzerOptions Class Reference
#include <include/analysis/rc_analyzer.h>
Public Member Functions
rcAnalyzerOptions ()
rcAnalyzerOptions (const rsCorrParams &corrParams, rcAnalyzerMode mode, rcAnalyzerResultOrigin origin, const rcRect &rect, uint32 windowSize, rcSimilarator::rcEntropyDefinition eDef, const rcPixel &depth)
rcAnalyzerOptions (const rcAnalyzerOptions &o)
bool operator== (const rcAnalyzerOptions &o) const
bool operator!= (const rcAnalyzerOptions &o) const
const rsCorrParams & corrParams () const
rcAnalyzerMode mode () const
rcAnalyzerResultOrigin origin () const
const rcRect & bound () const
uint32 windowSize () const
rcSimilarator::rcEntropyDefinition entropyDefinition () const
const rcPixel & depth () const
void setCorrParams (rsCorrParams p)
void setMode (rcAnalyzerMode m)
void setOrigin (rcAnalyzerResultOrigin o)
void setBound (const rcRect &r)
void setWindowSize (uint32 s)
void setEntropyDefinition (rcSimilarator::rcEntropyDefinition e)
void setDepth (rcPixel depth)
Private Attributes
rsCorrParams mCorrParams
rcAnalyzerMode mMode
rcAnalyzerResultOrigin mOrigin
rcRect mBoundRect
uint32 mWindowSize
rcSimilarator::rcEntropyDefinition mEntropyDefinition
rcPixel mDepth
Detailed Description
Definition at line 43 of file rc_analyzer.h.
Constructor & Destructor Documentation
rcAnalyzerOptions::rcAnalyzerOptions () inline
Definition at line 46 of file rc_analyzer.h.
                       :
     mCorrParams( rsCorrParams() ),
     mMode( eAnalyzerFullCorrelation ),
     mOrigin( eAnalyzerResultOriginRight ),
     mBoundRect( rcRect() ),
     mWindowSize( 3 ),
     mEntropyDefinition (rcSimilarator::eACI),
     mDepth( rcPixel8 ) {
};
rcAnalyzerOptions::rcAnalyzerOptions (const rsCorrParams & corrParams, rcAnalyzerMode mode, rcAnalyzerResultOrigin origin, const rcRect & rect, uint32 windowSize, rcSimilarator::rcEntropyDefinition eDef, const rcPixel & depth) inline
Definition at line 56 of file rc_analyzer.h.
References mWindowSize.
                                     :
     mCorrParams( corrParams ),
     mMode( mode ),
     mOrigin( origin ),
     mBoundRect( rect ),
     mWindowSize( windowSize ),
     mEntropyDefinition( eDef ),
     mDepth( depth ){
       if ( mWindowSize < 1 )
     mWindowSize = 1;
};
rcAnalyzerOptions::rcAnalyzerOptions (const rcAnalyzerOptions & o) inline
Definition at line 74 of file rc_analyzer.h.
                                                   :
     mCorrParams( o.corrParams() ),
     mMode( o.mode() ),
     mOrigin( o.origin() ),
     mBoundRect( o.bound() ),
     mWindowSize( o.windowSize() ),
     mEntropyDefinition( o.entropyDefinition() ),
     mDepth( o.depth() ) {
};
Member Function Documentation
const rcRect& rcAnalyzerOptions::bound () const inline
Definition at line 106 of file rc_analyzer.h.
References mBoundRect.
Referenced by rcAnalyzer::getNextResult(), operator<<(), and operator==().
 { return mBoundRect; };
const rsCorrParams& rcAnalyzerOptions::corrParams () const inline
Definition at line 103 of file rc_analyzer.h.
References mCorrParams.
 { return mCorrParams; };
const rcPixel& rcAnalyzerOptions::depth () const inline
Definition at line 109 of file rc_analyzer.h.
References mDepth.
Referenced by operator==(), rcAnalyzer::rcAnalyzer(), and setDepth().
 { return mDepth; };
rcSimilarator::rcEntropyDefinition rcAnalyzerOptions::entropyDefinition () const inline
Definition at line 108 of file rc_analyzer.h.
References mEntropyDefinition.
Referenced by rcEngineImpl::entropyTrackerWindow(), rcAnalyzer::getNextResult(), and operator==().
 { return mEntropyDefinition; };
rcAnalyzerMode rcAnalyzerOptions::mode () const inline
Definition at line 104 of file rc_analyzer.h.
References mMode.
Referenced by operator<<(), operator==(), and rcAnalyzer::rcAnalyzer().
 { return mMode; };
bool rcAnalyzerOptions::operator!= (const rcAnalyzerOptions & o) const inline
Definition at line 98 of file rc_analyzer.h.
{
     return !( o == *this );
   }
bool rcAnalyzerOptions::operator== (const rcAnalyzerOptions & o) const inline
Definition at line 88 of file rc_analyzer.h.
References bound(), depth(), entropyDefinition(), mBoundRect, mDepth, mEntropyDefinition, mMode, mode(), mOrigin, mWindowSize, origin(), and windowSize().
{
     // TODO: we must implement rsCorrParams equality operator
     return ( /*mCorrParams == o.corrParams() && */
         mMode == o.mode() &&
         mOrigin == o.origin() &&
         mBoundRect == o.bound() &&
         mWindowSize == o.windowSize() &&
         mEntropyDefinition == o.entropyDefinition() &&
         mDepth == o.depth());
   }
rcAnalyzerResultOrigin rcAnalyzerOptions::origin () const inline
Definition at line 105 of file rc_analyzer.h.
References mOrigin.
Referenced by rcEngineImpl::entropyTrackerWindow(), operator<<(), operator==(), rcAnalyzer::pushResult(), and rcAnalyzer::pushUndefinedResult().
 { return mOrigin; };
void rcAnalyzerOptions::setBound (const rcRect & r) inline
Definition at line 115 of file rc_analyzer.h.
References mBoundRect.
Referenced by rcEngineImpl::entropyTrackerWindow().
 { mBoundRect = r; };
void rcAnalyzerOptions::setCorrParams (rsCorrParams p) inline
Definition at line 112 of file rc_analyzer.h.
References mCorrParams.
 { mCorrParams = p; };
void rcAnalyzerOptions::setDepth (rcPixel depth) inline
Definition at line 124 of file rc_analyzer.h.
References depth(), and mDepth.
Referenced by rcEngineImpl::entropyTrackerWindow().
 { mDepth = depth; }
void rcAnalyzerOptions::setEntropyDefinition (rcSimilarator::rcEntropyDefinition e) inline
Definition at line 121 of file rc_analyzer.h.
References mEntropyDefinition.
Referenced by rcEngineImpl::entropyTrackerWindow().
{
     mEntropyDefinition = e;
   }
void rcAnalyzerOptions::setMode (rcAnalyzerMode m) inline
Definition at line 113 of file rc_analyzer.h.
References mMode.
 { mMode = m; };
void rcAnalyzerOptions::setOrigin (rcAnalyzerResultOrigin o) inline
Definition at line 114 of file rc_analyzer.h.
References mOrigin.
Referenced by rcEngineImpl::entropyTrackerWindow().
 { mOrigin = o; };
void rcAnalyzerOptions::setWindowSize (uint32 s) inline
Definition at line 116 of file rc_analyzer.h.
References mWindowSize.
Referenced by rcEngineImpl::entropyTrackerWindow().
{
     if ( s < 1 )
       s = 1;
     mWindowSize = s;
   };
uint32 rcAnalyzerOptions::windowSize () const inline
Definition at line 107 of file rc_analyzer.h.
References mWindowSize.
Referenced by rcEngineImpl::entropyTrackerWindow(), rcAnalyzer::getNextResult(), rcAnalyzer::isValid(), operator<<(), operator==(), rcAnalyzer::pushResult(), rcAnalyzer::pushUndefinedResult(), and rcAnalyzer::rcAnalyzer().
 { return mWindowSize; };
Member Data Documentation
rcRect rcAnalyzerOptions::mBoundRect private
Definition at line 131 of file rc_analyzer.h.
Referenced by bound(), operator==(), and setBound().
rsCorrParams rcAnalyzerOptions::mCorrParams private
Definition at line 128 of file rc_analyzer.h.
Referenced by corrParams(), and setCorrParams().
rcPixel rcAnalyzerOptions::mDepth private
Definition at line 134 of file rc_analyzer.h.
Referenced by depth(), operator==(), and setDepth().
rcSimilarator::rcEntropyDefinition rcAnalyzerOptions::mEntropyDefinition private
Definition at line 133 of file rc_analyzer.h.
Referenced by entropyDefinition(), operator==(), and setEntropyDefinition().
rcAnalyzerMode rcAnalyzerOptions::mMode private
Definition at line 129 of file rc_analyzer.h.
Referenced by mode(), operator==(), and setMode().
rcAnalyzerResultOrigin rcAnalyzerOptions::mOrigin private
Definition at line 130 of file rc_analyzer.h.
Referenced by operator==(), origin(), and setOrigin().
uint32 rcAnalyzerOptions::mWindowSize private
Definition at line 132 of file rc_analyzer.h.
Referenced by operator==(), rcAnalyzerOptions(), setWindowSize(), and windowSize().
The documentation for this class was generated from the following file:
include/analysis/rc_analyzer.h