Visible: rcVisualRect Class Reference
rcVisualRect Class Reference
#include <include/visual/rc_graphics.h>
Public Member Functions
rcVisualRect (const rc2Fvector &ul, const rc2Fvector &lr)
rcVisualRect (const rcIRect &ir)
rcVisualRect (const rcFRect &ir)
rcVisualRect (const rcRect &ir)
rcVisualRect (const float &x, const float &y, const float &w, const float &h)
~rcVisualRect ()
const rc2Fvector & ul () const
const rc2Fvector & lr () const
float x () const
float y () const
float width () const
float height () const
Public Member Functions inherited from rcVisualSegment
rcVisualSegment ()
rcVisualSegment (rcVisualSegmentType type, const rc2Fvector &p1, const rc2Fvector &p2)
~rcVisualSegment ()
const rc2Fvector & p1 () const
const rc2Fvector & p2 () const
rcVisualSegmentType type () const
void p1 (const rc2Fvector &p)
void p2 (const rc2Fvector &p)
void type (rcVisualSegmentType t)
rcVisualSegment & operator+= (const rc2Fvector &_t_)
bool operator== (const rcVisualSegment &o) const
bool operator!= (const rcVisualSegment &o) const
Additional Inherited Members
Public Types inherited from rcVisualSegment
enum { ePersistenceVersion = 1 }
enum rcVisualSegmentType {
eUnknown = 0, eEmpty, ePoints, eLine,
eLineStrip, eLineLoop, eArrow, eRect,
eEllipse, eCross, eStyle, eLast
}
Protected Attributes inherited from rcVisualSegment
rc2Fvector mP1
rc2Fvector mP2
uint8 mType
Detailed Description
Definition at line 158 of file rc_graphics.h.
Constructor & Destructor Documentation
rcVisualRect::rcVisualRect (const rc2Fvector & ul, const rc2Fvector & lr) inline
Definition at line 160 of file rc_graphics.h.
                                                                :
rcVisualSegment(eRect, ul, lr) {};
rcVisualRect::rcVisualRect (const rcIRect & ir) inline
Definition at line 163 of file rc_graphics.h.
                                    :
     rcVisualSegment( eRect, rc2Fvector (ir.ul()), rc2Fvector (ir.lr())) {};
rcVisualRect::rcVisualRect (const rcFRect & ir) inline
Definition at line 166 of file rc_graphics.h.
                                    :
rcVisualSegment(eRect, rc2Fvector (ir.ul()), rc2Fvector (ir.lr())) {};
rcVisualRect::rcVisualRect (const rcRect & ir) inline
Definition at line 169 of file rc_graphics.h.
                                   :
rcVisualSegment(eRect, rc2Fvector (ir.ul()), rc2Fvector (ir.lr())) {};
rcVisualRect::rcVisualRect (const float & x, const float & y, const float & w, const float & h) inline
Definition at line 172 of file rc_graphics.h.
                                                                                    :
rcVisualSegment(eRect, rc2Fvector(x, y), rc2Fvector(x+w, y+h)) {};
rcVisualRect::~rcVisualRect () inline
Definition at line 175 of file rc_graphics.h.
 {};
Member Function Documentation
float rcVisualRect::height () const inline
Definition at line 183 of file rc_graphics.h.
References rcVisualSegment::mP1, rcVisualSegment::mP2, and rc2dVector< T >::y().
 { return mP2.y() - mP1.y(); }
const rc2Fvector& rcVisualRect::lr () const inline
Definition at line 179 of file rc_graphics.h.
References rcVisualSegment::mP2.
 { return mP2;}
const rc2Fvector& rcVisualRect::ul () const inline
Definition at line 178 of file rc_graphics.h.
References rcVisualSegment::mP1.
 { return mP1;}
float rcVisualRect::width () const inline
Definition at line 182 of file rc_graphics.h.
References rcVisualSegment::mP1, rcVisualSegment::mP2, and rc2dVector< T >::x().
 { return mP2.x() - mP1.x(); }
float rcVisualRect::x () const inline
Definition at line 180 of file rc_graphics.h.
References rcVisualSegment::mP1, and rc2dVector< T >::x().
 { return mP1.x(); }
float rcVisualRect::y () const inline
Definition at line 181 of file rc_graphics.h.
References rcVisualSegment::mP1, and rc2dVector< T >::y().
 { return mP1.y(); }
The documentation for this class was generated from the following file:
include/visual/rc_graphics.h