Visible: rcValue Class Reference
rcValue Class Reference
#include <include/baseUI/rc_value.h>
Public Types
enum Type {
eIntValue = 0, eBoolValue, eFloatValue, eDoubleValue,
eStringValue, eRectValue, eAffineRectValue, ePositionValue,
eiPairValue, eNullValue
}
Public Member Functions
rcValue ()
rcValue (int intValue)
rcValue (bool boolValue)
rcValue (float floatValue)
rcValue (double doubleValue)
rcValue (const std::string &stringValue)
rcValue (const char *stringValue)
rcValue (const rcRect &rectValue)
rcValue (const rcAffineRectangle &rectValue)
rcValue (const rcFPair &posValue)
rcValue (const rcIPair &posValue)
int intValue (void) const
float floatValue (void) const
double doubleValue (void) const
bool boolValue (void) const
std::string stringValue (void) const
rcRect rectValue (void) const
rcAffineRectangle affineValue (void) const
rcFPair positionValue (void) const
rcIPair ipairValue (void) const
bool isNull (void) const
Type getType (void) const
bool equals (const rcValue &otherValue) const
operator int () const
operator float () const
operator double () const
operator bool () const
operator std::string () const
operator rcRect () const
operator rcAffineRectangle () const
operator rcFPair () const
operator rcIPair () const
bool operator== (const rcValue &value) const
bool operator!= (const rcValue &value) const
Private Attributes
union {
int intValue
bool boolValue
float floatValue
double doubleValue
float positionValue [2]
int ipairValue [2]
int rectValue [4]
float affineValue [5]
} _val
std::string _stringValue
Type _type
Detailed Description
Definition at line 49 of file rc_value.h.
Member Enumeration Documentation
enum rcValue::Type
Enumerator
eIntValue
eBoolValue
eFloatValue
eDoubleValue
eStringValue
eRectValue
eAffineRectValue
ePositionValue
eiPairValue
eNullValue
Definition at line 53 of file rc_value.h.
             { eIntValue = 0,
           eBoolValue,
           eFloatValue,
           eDoubleValue,
           eStringValue,
           eRectValue,
           eAffineRectValue,
           ePositionValue,
           eiPairValue,
           eNullValue };
Constructor & Destructor Documentation
rcValue::rcValue ()
Definition at line 24 of file rc_value.cpp.
 {
     _type = eNullValue;
     _val.intValue = 0;
 }
rcValue::rcValue (int intValue)
Definition at line 31 of file rc_value.cpp.
 {
     _type = eIntValue;
     _val.intValue = intValue;
 }
rcValue::rcValue (bool boolValue)
Definition at line 38 of file rc_value.cpp.
 {
     _type = eBoolValue;
     _val.boolValue = boolValue;
 }
rcValue::rcValue (float floatValue)
Definition at line 45 of file rc_value.cpp.
 {
     _type = eFloatValue;
     _val.floatValue = floatValue;
 }
rcValue::rcValue (double doubleValue)
Definition at line 52 of file rc_value.cpp.
 {
     _type = eDoubleValue;
     _val.doubleValue = doubleValue;
 }
rcValue::rcValue (const std::string & stringValue)
Definition at line 59 of file rc_value.cpp.
 {
     _type = eStringValue;
     _stringValue = stringValue;
 }
rcValue::rcValue (const char * stringValue)
Definition at line 66 of file rc_value.cpp.
 {
     _type = eStringValue;
     _stringValue = stringValue;
 }
rcValue::rcValue (const rcRect & rectValue)
Definition at line 73 of file rc_value.cpp.
References rcRectangle< T >::height(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
 {
     _type = eRectValue;
     _val.rectValue[0] = rectValue.x(), _val.rectValue[1] = rectValue.y(), _val.rectValue[2] = rectValue.width(),
       _val.rectValue[3] = rectValue.height();
 }
rcValue::rcValue (const rcAffineRectangle & rectValue)
Definition at line 81 of file rc_value.cpp.
References rcAffineRectangle::angle(), rcRadian::basic(), rcAffineRectangle::cannonicalSize(), rcAffineRectangle::origin(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
 {
   _type = eAffineRectValue;
   _val.affineValue[0] = (float) affValue.origin().x(), _val.affineValue[1] = (float) affValue.origin().y(),
     _val.affineValue[2] = (float) affValue.cannonicalSize().x(),     _val.affineValue[3] = (float) affValue.cannonicalSize().y(),
     _val.affineValue[4] = (float) affValue.angle().basic ();
 }
rcValue::rcValue (const rcFPair & posValue)
Definition at line 90 of file rc_value.cpp.
References rcPair< T >::x(), and rcPair< T >::y().
 {
     _type = ePositionValue;
     _val.positionValue[0] = posValue.x();
     _val.positionValue[1] = posValue.y();
 }
rcValue::rcValue (const rcIPair & posValue)
Definition at line 98 of file rc_value.cpp.
References rcPair< T >::x(), and rcPair< T >::y().
 {
     _type = eiPairValue;
     _val.ipairValue[0] = ipairValue.x();
     _val.ipairValue[1] = ipairValue.y();
 }
Member Function Documentation
rcAffineRectangle rcValue::affineValue (void) const
bool rcValue::boolValue (void) const
double rcValue::doubleValue (void) const
bool rcValue::equals (const rcValue & otherValue) const
Definition at line 435 of file rc_value.cpp.
References _stringValue, _type, _val, affineValue, boolValue, doubleValue, floatValue, intValue, ipairValue, positionValue, and rectValue.
 {
     if (otherValue._type != _type)
         return false;
     switch (_type)
     {
     case eIntValue:
         return _val.intValue == otherValue._val.intValue;
     case eFloatValue:
         return _val.floatValue == otherValue._val.floatValue;
     case eDoubleValue:
         return _val.doubleValue == otherValue._val.doubleValue;
     case eBoolValue:
         return _val.boolValue == otherValue._val.boolValue;
     case eStringValue:
         return _stringValue == otherValue._stringValue;
     case eRectValue:
         return _val.rectValue[0] == otherValue._val.rectValue[0] &&
       _val.rectValue[1] == otherValue._val.rectValue[1] &&
       _val.rectValue[2] == otherValue._val.rectValue[2] &&
       _val.rectValue[3] == otherValue._val.rectValue[3];
     case eAffineRectValue:
         return _val.affineValue[0] == otherValue._val.affineValue[0] &&
       _val.affineValue[1] == otherValue._val.affineValue[1] &&
       _val.affineValue[2] == otherValue._val.affineValue[2] &&
       _val.affineValue[3] == otherValue._val.affineValue[3] &&
       _val.affineValue[4] == otherValue._val.affineValue[4];
     case ePositionValue:
       return _val.positionValue[0] == otherValue._val.positionValue[0] &&
     _val.positionValue[1] == otherValue._val.positionValue[1];
     case eiPairValue:
       return _val.ipairValue[0] == otherValue._val.ipairValue[0] &&
     _val.ipairValue[1] == otherValue._val.ipairValue[1];
     case eNullValue:
         return true;
     }
     throw rcConvertValueException( "rcValue::equals() unknown types");
 }
float rcValue::floatValue (void) const
rcValue::Type rcValue::getType (void) const
Definition at line 492 of file rc_value.cpp.
 {
     return _type;
 }
int rcValue::intValue (void) const
rcIPair rcValue::ipairValue (void) const
bool rcValue::isNull (void) const
Definition at line 486 of file rc_value.cpp.
 {
     return _type == eNullValue;
 }
rcValue::operator bool () const inline
Definition at line 143 of file rc_value.h.
 { return boolValue(); }
rcValue::operator double () const inline
Definition at line 140 of file rc_value.h.
 { return doubleValue(); }
rcValue::operator float () const inline
Definition at line 137 of file rc_value.h.
 { return floatValue(); }
rcValue::operator int () const inline
Definition at line 134 of file rc_value.h.
 { return intValue(); }
rcValue::operator rcAffineRectangle () const inline
Definition at line 152 of file rc_value.h.
 { return affineValue(); }
rcValue::operator rcFPair () const inline
Definition at line 155 of file rc_value.h.
 { return positionValue(); }
rcValue::operator rcIPair () const inline
Definition at line 158 of file rc_value.h.
 { return ipairValue(); }
rcValue::operator rcRect () const inline
Definition at line 149 of file rc_value.h.
 { return rectValue(); }
rcValue::operator std::string () const inline
Definition at line 146 of file rc_value.h.
 { return stringValue(); }
bool rcValue::operator!= (const rcValue & value) const inline
Definition at line 164 of file rc_value.h.
 { return !equals( value ); }
bool rcValue::operator== (const rcValue & value) const inline
Definition at line 161 of file rc_value.h.
 { return equals( value ); }
rcFPair rcValue::positionValue (void) const
rcRect rcValue::rectValue (void) const
std::string rcValue::stringValue (void) const
Definition at line 274 of file rc_value.cpp.
Referenced by rcFileSaveSettingWidget::browseRequest(), operator<<(), rcNativeExporter::produceTracks(), and rcNativeExporter::produceVersion().
 {
     strstream buf;
     switch (_type)
     {
     case eIntValue:
         buf << _val.intValue;
         break;
     case eFloatValue:
         buf.precision(12);
         buf << _val.floatValue;
         break;
     case eDoubleValue:
         buf.precision(12);
         buf << _val.doubleValue;
         break;
     case eBoolValue:
         buf << (_val.boolValue ? "true" : "false");
         break;
     case eStringValue:
         buf << _stringValue;
         break;
     case eRectValue:
         buf << "[";
         buf << _val.rectValue[0] << " ";
         buf << _val.rectValue[1] << " ";
         buf << _val.rectValue[2] << " ";
         buf << _val.rectValue[3] << "]";
         break;
     case eAffineRectValue:
       buf << "{";
         buf << _val.affineValue[0] << " ";
         buf << _val.affineValue[1] << " ";
         buf << _val.affineValue[2] << " ";
         buf << _val.affineValue[3] << "]";
         buf << _val.affineValue[4] << "]";
     break;
    case ePositionValue:
        buf.precision(12);
        buf << _val.positionValue[0] << "," << _val.positionValue[1];
        break;
    case eiPairValue:
        buf.precision(12);
        buf << _val.ipairValue[0] << "," << _val.ipairValue[1];
        break;
     case eNullValue:
         throw rcNullValueException();
     }
     buf << ends;
     std::string value( buf.str() );
     buf.freeze( false ); // Without freeze(), strstream::str() leaks the string it returns
     return value;
 }
Member Data Documentation
std::string rcValue::_stringValue private
Definition at line 181 of file rc_value.h.
Referenced by equals().
Type rcValue::_type private
Definition at line 182 of file rc_value.h.
Referenced by equals().
union { ... } rcValue::_val
Referenced by equals().
rcAffineRectangle rcValue::affineValue
Definition at line 178 of file rc_value.h.
Referenced by equals().
bool rcValue::boolValue
Definition at line 172 of file rc_value.h.
Referenced by equals().
double rcValue::doubleValue
Definition at line 174 of file rc_value.h.
Referenced by equals(), rcNativeImporter::parseTrack(), and rcNativeImporter::parseValue().
float rcValue::floatValue
Definition at line 173 of file rc_value.h.
Referenced by equals().
int rcValue::intValue
Definition at line 171 of file rc_value.h.
Referenced by equals(), and rcNativeImporter::parseTrack().
rcIPair rcValue::ipairValue
Definition at line 176 of file rc_value.h.
Referenced by equals().
rcFPair rcValue::positionValue
Definition at line 175 of file rc_value.h.
Referenced by equals(), rcNativeImporter::parseTrack(), and rcNativeImporter::parseValue().
rcRect rcValue::rectValue
Definition at line 177 of file rc_value.h.
Referenced by equals(), and rcNativeImporter::parseTrack().
The documentation for this class was generated from the following files:
include/baseUI/rc_value.h
src/baseUI/rc_value.cpp