Visible: rcVisualFunction Class Reference
rcVisualFunction Class Reference
#include <include/analysis/rc_visualcell.h>
Public Types
enum Haves {
eMotion = 0, eCorrespondence, eScale, eRLEs,
eDispersion, eDimensions, eTemporal, eVelocity,
eSpeed, eAcceleration, ePersistence, eBeatInfo,
ePacingInfo, eCoarseSS, ePeriodicity, eGeometry,
eContraction, eDistance, eNumHaves
}
enum State {
eIsInitialized =0, eIsUnInitialized, eIsUnknown, eIsMoving,
eIsDirected, eIsJustDivided, eIsGeneralModel, eIsDividing,
eIsDivided, eIsFragmented, eIsOutSide, eIsBeating,
eIsParent, eIsChild, eIsRounding, eIsRounded,
eIsPeriodic, eHasFullyExtended, eHasSimilarator, eIsAffineXdirected,
eNumStates
}
enum DOF { eMotionCenter, eMotionCenterANDTP, eNone }
enum parameters { eMinFramesPerPeriod4Stat = 12, eMaxHalfShorteningPct = 10, eMinMyoOtherDimensionInPixels = 6 }
enum Lines {
eVectors, eBoundingBox, eBoundingPoly, eCurl,
eRelief
}
Public Member Functions
rcVisualFunction ()
virtual ~rcVisualFunction ()
Constructor :Return date of birth relative to kinetoscope start : Attaches this visualFunction to this kinetoscope : Registers this visual function in time.
bool isState (const State st) const
bool isNotState (const State st) const
bool setState (const State st)
bool setState (const State st, const bool b)
bool clearState (const State st)
uint32 id () const
uint32 parentId () const
uint32 generation () const
rcOrganismInfo::OrganismType organism () const
rcOrganismInfo::OrganismName organismName () const
bool isOfOrganismType (rcOrganismInfo::OrganismType ot) const
bool isOfOrganismName (rcOrganismInfo::OrganismName onm) const
bool isOfOrganismTypeAndName (rcOrganismInfo::OrganismType ot, rcOrganismInfo::OrganismName onm) const
bool isCardiacCell () const
bool isLabelProtein () const
float time () const
float age () const
float area () const
float mass () const
float perimeter () const
float circularity () const
float ellipseRatio () const
float rmsQuality () const
float distance () const
const rc2Fvector & position () const
const rc2Fvector velocity () const
const rc2Fvector instantVelocity () const
const rc2Xform instantTransformation () const
const rc2Fvector translation () const
const rcFPair scale () const
const float shortenning () const
const rcFPair dimensions () const
const rcFPair & majorEnds () const
const vector< rc2Fvector > & majorEndPoints () const
const deque< rc2Fvector > & majorEndPoses () const
float acceleration () const
float persistence () const
float framesPerPeriod () const
int32 integralFramesPerPeriod () const
int32 framesPerPeriodPowerOf2 () const
float contractionFrequency () const
float pacingFrequency () const
float minSqDisplacement () const
float directedCellPersistence () const
const vector< float > & similarity () const
int32 label () const
int32 startFrameIndex () const
int32 dividedFrameIndex () const
void frameIndex (int32 fi)
int32 label (int32 l)
float cQuality () const
void cQuality (const float _arg)
const int32 history () const
const deque
< rcCorrelationWindow< uint8 > > & snaps () const
const deque< rcFRect > & rectSnaps () const
const deque< rcFRect > & rectTemplates () const
const deque< rcIRect > & rectSearches () const
const vector< rcPolygon > & polygons () const
const vector< rcAffineRectangle > & affys () const
const rcIRect & minTemporalEnclosingRect () const
const rcIRect & minTemporalIntersectingRect () const
const rcShapeRef & shape () const
virtual void measure ()
virtual void update ()
virtual void reconcile ()
const boost::shared_ptr
< rcKinetoscope > sharedKin () const
const rc2Fvector & cop () const
const rcFRect & moving () const
void moving (const rcFRect &fm)
const deque< rcFPair > & interpolatedMin () const
const deque< rcPair< rcRadian > > & peakAngles () const
const vector< rc2Fvector > & children () const
const rcIRect & dividingArea () const
const rcFRect & similarityArea () const
template<class P >
rcIRect roundRectangle (const rcRectangle< P > &fr, bool makeVecMultiple=false) const
const rcStatistics & stats () const
bool operator< (const rcVisualFunction &rhs) const
bool operator== (const rcVisualFunction &rhs) const
Public Member Functions inherited from rcBaseMotionPath
rcBaseMotionPath ()
virtual ~rcBaseMotionPath ()
bool isWithin (rcFPair &) const
const float & dob () const
const rc2Fvector position () const
dob :Return date of birth relative to kinetoscope start
rcIPair iAnchor () const
position Position with respect to the image from it was created from
const rc2Fvector & travelled () const
const rc2Fvector & motion () const
const rc2Fvector & anchor () const
void move (const rc2Fvector &t)
void move (const rc2Xform &xm)
move (vector) Move assuming the (t) -> (t+1) for motion vectors we assume translation
const rc2Fvector & anchor (const rc2Fvector &a)
move (xform) Move assuming the (t) -> (t+1) for motion vectors we assume translation
void step ()
uint32 steps () const
bool isAtStep (uint32 step) const
Private Member Functions
void direct (const rc2Fvector &)
void correspond (const rc2Fvector &, const rcFPair &)
void correspondMutualChannel (const rc2Fvector &, const rcFPair &)
bool vXform (DOF, rc2Xform &)
rc2Fvector & motionCenter ()
const int32 ssWindowSize () const
const float adaptBias () const
const rcFPair predictedTolerance (rc2Fvector &) const
void populationMigration ()
void cardiacUpdate ()
void cardiacMeasure (vector< rcPolygon >::const_iterator &)
void beatProcess ()
float sideShorteningEstimate () const
float sideShorteningActual () const
deque< rc2Fvector > & ends () const
void dividingMeasure (vector< rcPolygon >::const_iterator &)
bool dividingProcess ()
bool dividedProcess ()
bool grow (const vector< rcIRect > &)
bool grow (vector< rcPolygon > groupIntersects, list< rcVisualFunction > &functionList)
uint32 intersectSet (vector< rcPolygon * > &)
bool isIsoMorphic ()
void updateRects (const rcFRect &, const rcFPair &, rcFRect &, rcIRect &) const
double match (rcWindow &image, rcWindow &model, rc2Fvector &trans)
double match (rcWindow &image, rcCorrelationWindow< uint8 > &model, rc2Fvector &trans)
Private Attributes
rcDPair gNotAvailablePair
rcOrganismInfo::OrganismType mOtype
rcOrganismInfo::OrganismName mOname
bitset< eNumHaves > mHaves
bitset< eNumStates > mState
uint32 mId
uint32 mParentId
uint32 mGeneration
int32 mSize
int32 mNsQ
int32 mEllipseIndex
int32 mLabel
int32 mRad
int32 mIntegralFramesPerPeriod
int32 mFramesPerPeriodPowerOf2
float mArea
float mMass
float mPerimeter
float mCircularity
float mEllipseRatio
float mRdiffuse
float mCosSums
float mMotionPattern
float mCorrespondenceQuality
float mAcceleration
rc2Fvector mV
rc2Fvector mVt
rc2Fvector mMotionCtr
rc2Fvector mAffineSize
rc2Fvector mCurrentPosition
rcIRect mMinTemporalEncRect
rcIRect mMinTemporalIntRect
rc2Xform mXform
rc2Xform mMotionXform
rcFRect mMoving
rcFRect mCurrentSimRect
rcStatistics mSumQuality
rcRadian mLastAngle
double mDistance
boost::shared_ptr< rcKinetoscope > mKine
int32 mExpStartFrameIndex
int32 mExpDividedFrameIndex
rcInfLine mCardiacAxis
rc2Fvector mMidPoint
vector< rc2Fvector > mMajorEndPoints
rcFPair mMajorEnds
float mFirstBeatLength
float mBeatMedian
float mBeatShortenning
float mBeatNumber
float mContractionFrequency
float mEstimatedShortening
float mActualShortening
float mFramesPerPeriod
vector< vector< double > > mSpace
rcShapeRef mShapeRef
rcSimilaratorRef mCoarseSimRef
deque< rcCorrelationWindow
< uint8 > > mSnaps
deque< rcCorrelationWindow
< uint8 > > mTemplates
deque< rcFRect > mTemplateRects
deque< rcIRect > mSearchRects
deque< rc2Fvector > mTemplateOrigins
deque< rc2Fvector > mTemplatePoses
rcDPair mTemplateOriginEnds
deque< rcFRect > mRectSnaps
vector< rcPolygon > mPOLYs
vector< rcAffineRectangle > mAffys
vector< float > mSS
vector< float > mAcl
rcCorrelationWindow< uint8 > mGaussModel
vector< rc2Fvector > mChildren
vector< float > mChildrenL2
vector< float > mDimensions
vector< float > mDimensionTs
deque< double > mBeatAC
deque< rcFPair > mInterpolatedMin
deque< rcPair< rcRadian > > mPeakAngles
int32 mSSwindowSize
int32 mDividingTicks
int32 mAnaphase
rcIRect mDividingWatchWindow
rcMathematicalImage mIradModel
Static Private Attributes
static const float gInValidOrigin =rcFLT_MIN
static const float gInValidDispersion =rcFLT_MIN
static const float gNotAvailable = -1.0f
static const float gMinAdaptBias = 2.0f
static const float gEstSideShortening = 0.08f
static const int32 gAffineExtend = 5
static const float gGoodFit = 500.0f
static const double gInValidAcceleration =rcDBL_MIN
static const uint32 gPreHistoric = rcUINT32_MAX
Friends
class rcKinetoscope
ostream & operator<< (ostream &, const rcVisualFunction::State &)
ostream & operator<< (ostream &, const rcVisualFunction &)
rcVisualFunction (rcKinetoscope *kin, const rc2Fvector &anchor, const rcPolygon &poly, bool isChild=false)
rcVisualFunction (rcKinetoscope *kin, const rcPolygon &poly, const vector< rc2Fvector > &ends, const float rad)
bool have (enum Haves what) const
bool mark (enum Haves what)
bool clear (enum Haves what)
void reset ()
State state () const
State fineState () const
void info (rcOrganismInfo::OrganismType c=rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n=rcOrganismInfo::eUnknown)
float speed () const
void initFunction ()
float framesPerPeriod (float p)
void createIrradianceModel ()
bool updateSims (const rcWindow &, const rcFRect &)
int32 ssWindowSize (int32 ws)
double computeAcceleration ()
void initializeSimilarator (const rcFRect &simRect)
const rcWindow & use4moving () const
const rcWindow & use4fixed () const
Additional Inherited Members
Protected Attributes inherited from rcBaseMotionPath
float mGenesis
rc2Fvector mStartPosition
rc2Fvector mDxDt
rc2Fvector mSumPos
uint32 mSteps
Detailed Description
///
@function makeVecMultiple
Returns
rcIRect
Definition at line 50 of file rc_visualcell.h.
Member Enumeration Documentation
enum rcVisualFunction::DOF
Enumerator
eMotionCenter
eMotionCenterANDTP
eNone
Definition at line 162 of file rc_visualcell.h.
   {
     eMotionCenter,
     eMotionCenterANDTP,
     eNone
   };
enum rcVisualFunction::Haves
Enumerator
eMotion
eCorrespondence
eScale
eRLEs
eDispersion
eDimensions
eTemporal
eVelocity
eSpeed
eAcceleration
ePersistence
eBeatInfo
ePacingInfo
eCoarseSS
ePeriodicity
eGeometry
eContraction
eDistance
eNumHaves
Definition at line 95 of file rc_visualcell.h.
   {
     eMotion = 0,
     eCorrespondence,
     eScale,
     eRLEs,
     eDispersion,
     eDimensions,
     eTemporal,
     eVelocity,
     eSpeed,
     eAcceleration,
     ePersistence,
     eBeatInfo,
     ePacingInfo,
     eCoarseSS,
     ePeriodicity,
     eGeometry,
     eContraction,
     eDistance,
     eNumHaves
   };
enum rcVisualFunction::Lines
Enumerator
eVectors
eBoundingBox
eBoundingPoly
eCurl
eRelief
Definition at line 575 of file rc_visualcell.h.
   {
     eVectors,
     eBoundingBox,
     eBoundingPoly,
     eCurl,
     eRelief
   };
enum rcVisualFunction::parameters
Enumerator
eMinFramesPerPeriod4Stat
eMaxHalfShorteningPct
eMinMyoOtherDimensionInPixels
Definition at line 169 of file rc_visualcell.h.
   {
     eMinFramesPerPeriod4Stat = 12,
     eMaxHalfShorteningPct = 10,
     eMinMyoOtherDimensionInPixels = 6
   };
enum rcVisualFunction::State
Enumerator
eIsInitialized
eIsUnInitialized
eIsUnknown
eIsMoving
eIsDirected
eIsJustDivided
eIsGeneralModel
eIsDividing
eIsDivided
eIsFragmented
eIsOutSide
eIsBeating
eIsParent
eIsChild
eIsRounding
eIsRounded
eIsPeriodic
eHasFullyExtended
eHasSimilarator
eIsAffineXdirected
eNumStates
Definition at line 127 of file rc_visualcell.h.
   {
     eIsInitialized=0,
     eIsUnInitialized,
     eIsUnknown,
     eIsMoving,
     eIsDirected,
     eIsJustDivided,
     eIsGeneralModel,
     eIsDividing,
     eIsDivided,
     eIsFragmented,
     eIsOutSide,
     eIsBeating,
     eIsParent,
     eIsChild,
     eIsRounding,
     eIsRounded,
     eIsPeriodic,
     eHasFullyExtended,
     eHasSimilarator,
     eIsAffineXdirected,
     eNumStates
   };
Constructor & Destructor Documentation
rcVisualFunction::rcVisualFunction ()
rcVisualFunction::rcVisualFunction (rcKinetoscope * kin, const rc2Fvector & anchor, const rcPolygon & poly, bool isChild = false)
Definition at line 138 of file rc_visualfunction.cpp.
References rcBaseMotionPath::anchor(), createIrradianceModel(), eIsChild, eIsInitialized, rcKinetoscope::eLineage, framesPerPeriod(), gEstSideShortening, have(), info(), initFunction(), initializeSimilarator(), isLabelProtein(), rc2Xform::mapPoint(), mCurrentPosition, mEstimatedShortening, rcBaseMotionPath::mGenesis, mHaves, mMotionCtr, mPOLYs, mRectSnaps, mState, organism(), organismName(), rcPolygon::orthogonalEnclosingRect(), rcKinetoscope::periodicMotion(), rmAssert, rcTimestamp::secs(), setState(), sharedKin(), and rcKinetoscope::startingAbsoluteTime().
   : mKine (kin)
 {
   rmAssert (!mHaves.any());
   rmAssert (!mState.any());
   initFunction ();
   // Motion is detected using this frame and the previous frame
   // Map using kinetoscopes time unit mapper
   mGenesis = sharedKin()->secondsToUnits().mapVector (kin->startingAbsoluteTime().secs());
   info (sharedKin()->organism(), sharedKin()->organismName ());
   mEstimatedShortening = gEstSideShortening; // an estimate to start things off
   framesPerPeriod (kin->periodicMotion());
   // Cell's registration point is with respect to the orthogonal rect
   // Initial position
   rcFRect fr;
   poly.orthogonalEnclosingRect(fr);
   mMotionCtr = anch;
   anchor (mMotionCtr);
   mRectSnaps.push_back (fr);
   const rc2Xform& xform = sharedKin()->xform();
   mCurrentPosition = xform.mapPoint (anch);
   // Keep a copy of the polygon
   mPOLYs.push_back (poly);
   if (isLabelProtein ())
     createIrradianceModel ();
   setState(eIsChild, isChild);
   // In production sharedKin is ready. In testing this may not be true
   if (sharedKin()->canStep () && (sharedKin()->have (rcKinetoscope::eLineage)))
     {
       initializeSimilarator (mRectSnaps.back());
     }
   setState (rcVisualFunction::eIsInitialized);
 }
rcVisualFunction::rcVisualFunction (rcKinetoscope * kin, const rcPolygon & poly, const vector< rc2Fvector > & ends, const float rad)
Definition at line 182 of file rc_visualfunction.cpp.
References rcBaseMotionPath::anchor(), rc2dVector< T >::angle(), eHasFullyExtended, eIsInitialized, rcKinetoscope::eLineage, framesPerPeriod(), gEstSideShortening, info(), initFunction(), initializeSimilarator(), rc2dVector< T >::isNull(), rc2dVector< T >::len(), mAffys, rc2Xform::mapPoint(), rc2Xform::matrix(), mCurrentPosition, mEstimatedShortening, rcBaseMotionPath::mGenesis, mHaves, rcPolygon::minimumPerimeterEnclosingRect(), mMajorEndPoints, mMajorEnds, mMidPoint, mMotionCtr, mPOLYs, mRad, mRectSnaps, mState, rcKinetoscope::organism(), rcKinetoscope::organismName(), rcPolygon::orthogonalEnclosingRect(), rcKinetoscope::periodicMotion(), rmAssert, rmExceptionMacro, rcTimestamp::secs(), setState(), sharedKin(), rcKinetoscope::startingAbsoluteTime(), rc2Xform::trans(), and rcPolygon::transform().
   : mKine (kin)
 {
   rmAssert (!mHaves.any());
   rmAssert (!mState.any());
   rmAssert (ends.size() == 2);
   mRad = (int32) rad;
   initFunction ();
   // Motion is detected using this frame and the previous frame
   // Map using kinetoscopes time unit mapper
   mGenesis = sharedKin()->secondsToUnits().mapVector (kin->startingAbsoluteTime().secs());
   info (kin->organism(), kin->organismName ());
   mEstimatedShortening = gEstSideShortening; // an estimate to start things off
   framesPerPeriod (kin->periodicMotion());
   // Create a polygon using the ellipse formed by the ends.
   // Rotate and move it to the center of the line contecting the ends.
   rc2Fvector m = (ends[0] + ends[1]) / 2.0f;
   rc2Fvector d = ends[1] - ends[0];
   if (d.isNull ())
     {
       rmExceptionMacro(<<"Length too short");
     }
   rc2Xform xf;
   static const rcDPair noScale (1.0, 1.0);
   rcMatrix_2d mx (d.angle(), noScale);
   xf.matrix (mx);
   xf.trans (m);
   float a =d.len (); a = a / 2.0f;
   rcPolygon elip (a, mRad, 12);
   elip.transform (xf);
   mMajorEnds = rcFPair (0.0f, a + a);
   for (uint32 i = 0; i < 2; i++) mMajorEndPoints[i] = ends[i];
   setState (eHasFullyExtended);
   mMidPoint = m;
   // Now find the union poly of the two
   // Cell's registration point is with respect to the orthogonal rect
   // Initial position
   rcFRect fr;
   elip.orthogonalEnclosingRect(fr);
   mMotionCtr = m;
   anchor (mMotionCtr);
   mRectSnaps.push_back (fr);
   const rc2Xform& xform = sharedKin()->xform();
   mCurrentPosition = xform.mapPoint (m);
   // Keep a copy of the polygon
   mPOLYs.push_back (elip);
   mAffys.push_back (elip.minimumPerimeterEnclosingRect());
   // In production sharedKin is ready. In testing this may not be true
   // @note: should this be on for cardiac ?
   if (sharedKin()->canStep () && (sharedKin()->have (rcKinetoscope::eLineage)))
     {
       initializeSimilarator (mRectSnaps.back());
     }
   setState (rcVisualFunction::eIsInitialized);
 }
virtual rcVisualFunction::~rcVisualFunction () inline virtual
Constructor :Return date of birth relative to kinetoscope start : Attaches this visualFunction to this kinetoscope : Registers this visual function in time.
This time is a : relative time from the start of the kinestosope : minIntersecting and minEnclosng rectangles are initialized : to the Kinetoscopes frame : Anchor positions are with respect to the kintoscope. : Default assignment, copy constructor, destructor are OK : Second form is for construction from user input for cardiomyocytes
Definition at line 87 of file rc_visualcell.h.
 {}
Member Function Documentation
float rcVisualFunction::acceleration () const inline
Definition at line 425 of file rc_visualcell.h.
References mAcceleration.
Referenced by computeAcceleration(), and update().
   {
     return mAcceleration;
   }
const float rcVisualFunction::adaptBias () const inline private
Definition at line 750 of file rc_visualcell.h.
References sharedKin().
Referenced by measure(), and predictedTolerance().
 {return sharedKin()->maxRadialSpeed(); }
const vector<rcAffineRectangle>& rcVisualFunction::affys () const inline
Definition at line 614 of file rc_visualcell.h.
References mAffys.
Referenced by cardiacMeasure(), and cardiacUpdate().
 {return mAffys; }
float rcVisualFunction::age () const inline
Definition at line 238 of file rc_visualcell.h.
References rcBaseMotionPath::dob(), and time().
Referenced by beatProcess(), operator<<(), and update().
   {
     return (time() - dob());
   }
float rcVisualFunction::area () const inline
Definition at line 247 of file rc_visualcell.h.
References mArea.
Referenced by measure(), and operator<<().
   {
     return mArea;
     //    TODO: map through transformation
   }
void rcVisualFunction::beatProcess () private
Definition at line 294 of file rc_visualcardiomyo.cpp.
References age(), rcLineSegment< T >::angle(), clear(), eBeatInfo, eMinFramesPerPeriod4Stat, ePacingInfo, framesPerPeriod(), integralFramesPerPeriod(), mAffineSize, mark(), mBeatAC, mBeatMedian, mBeatNumber, mBeatShortenning, mContractionFrequency, mDimensions, mDimensionTs, mFirstBeatLength, mInterpolatedMin, mPeakAngles, rcRadian::normSigned(), parabolicFit(), rs1DFourierResult::peakFrequency, rc1DFourierForceFFT, rf1DAutoCorr(), rf1DFourierAnalysis(), rfMedian(), rfRealEq(), rkPI, rmAssert, similarity(), and rc2dVector< T >::x().
Referenced by reconcile().
  {
    // As long as the size is less than frames per period
    // built up the time series
    if ((int32) mDimensionTs.size() < ((int32)framesPerPeriod ()))
      {
        mDimensionTs.push_back (age());
        mDimensions.push_back (mAffineSize.x());
        rmAssert (mDimensionTs.size() == mDimensions.size());
      }
    if (mDimensionTs.size() >= (uint32) integralFramesPerPeriod ())
      {
        rmAssert (mDimensionTs.size() == mDimensions.size());
        clear (eBeatInfo);
        // What is the median dimension
        // Must be after the first length measurement.
        // @note: if we have less than 12 frames per
        if (mDimensionTs.size() < ((uint32)eMinFramesPerPeriod4Stat))
      mBeatMedian = mFirstBeatLength;
        else
      mBeatMedian = rfMedian (mDimensions);
        // What is the minimum and when is it reached
        vector<float>::iterator minL = min_element (mDimensions.begin(),
                            mDimensions.end());
        uint32 index = minL - mDimensions.begin();
        // interpolate and get min length and time
        // Report
        // Interpolation is on Median - Length (t - 1),
        //                     Median - Length (t),
        //                     Median - Length (t + 1)
        float minIntL (0), minIntT (0), minIntNormT (0);
        if (index > 0 && index < (mDimensions.size() - 1))
      {
        minIntNormT = minIntT = parabolicFit (mBeatMedian - mDimensions[index-1],
                          mBeatMedian - *minL,
                          mBeatMedian - mDimensions[index+1],
                          &minIntL);
      }
        // Peak return is mBeatMedian - minimumLength.
        // Scale Time according to the actual
        if (minIntT > 0.0) minIntT *= (mDimensionTs[index+1] - mDimensionTs[index]);
        if (minIntT < 0.0) minIntT *= (mDimensionTs[index] - mDimensionTs[index-1]);
        minIntL = mBeatMedian - minIntL;
        // If Interpolated is too close or inconclusive/degenerate use the measured minimum
        if (rfRealEq (minIntL, 0.0f) || rfRealEq (minIntT, 0.0f) || rfRealEq (*minL, minIntL, 1.0f))
      minIntL = *minL;
        mBeatShortenning = 1.0f - minIntL / mBeatMedian;
        // Construct Contraction and Relaxation immediate angles
        // Actual time stamp at the minimum is sub-frame time + time at the center.
        minIntT += mDimensionTs[index];
        rcLineSegment<float> cLine (rc2Fvector (minIntNormT , minIntL), rc2Fvector(-1.0f,
                                           mDimensions[index-1]));
        rcLineSegment<float> rLine (rc2Fvector (minIntNormT , minIntL), rc2Fvector(+1.0f,
                                           mDimensions[index+1]));
        // Put all the LTs out including the interpolated value, in order of increasing time.
        // A little inefficient for now
        uint32 fi;
        for (fi = 0; fi <= index; fi++)
      {
        mInterpolatedMin.push_back (rcFPair (mDimensionTs[fi], mDimensions[fi]));
      }
        if (minIntL != *minL)
      mInterpolatedMin.push_back (rcFPair (minIntT , minIntL ));
        // Assert that iL is within +/- 1 from minL
        for (; fi < mDimensions.size(); fi++)
      {
        mInterpolatedMin.push_back (rcFPair (mDimensionTs[fi], mDimensions[fi]));
      }
        // Transform Angles to our definition:
        // ContractionAngle = - (90 + (- cLine.angle())
        // RelaxationAngle = 90 - rLine.angle()
        rcRadian contraction (cLine.angle());
        rcRadian relaxation (rLine.angle());
        contraction.normSigned();
        relaxation.normSigned ();
        contraction = - (rkPI/2.0 + (- contraction.Double()));
        relaxation = rkPI/2.0 - relaxation.Double();
        mPeakAngles.push_back (rcPair<rcRadian> (contraction, relaxation));
        // Clear temporal buffer
        mDimensionTs.clear ();
        mDimensions.clear ();
        mark (eBeatInfo);
        mBeatNumber += 1;
      }
    // If we have at least 2 beats worth of frames
    if (mBeatNumber > 1 && similarity().size() > mBeatAC.size())
      {
        clear (ePacingInfo);
        vector<float>::const_iterator Begin = similarity().end();
        advance (Begin, - (int32) mBeatAC.size());
        rf1DAutoCorr (Begin, similarity().end(), mBeatAC);
        rs1DFourierResult rslt;
        rf1DFourierAnalysis(mBeatAC, rslt, rc1DFourierForceFFT);
        mContractionFrequency = (float) mBeatAC.size() / rslt.peakFrequency;
        mark (ePacingInfo);
      }
  }
void rcVisualFunction::cardiacMeasure (vector< rcPolygon >::const_iterator & vc) private
Definition at line 59 of file rc_visualcardiomyo.cpp.
References affys(), rcAffineRectangle::cannonicalSize(), cardiacUpdate(), distance(), eContraction, eDimensions, eHasFullyExtended, eIsAffineXdirected, eMotion, ends(), rcAffineRectangle::imageToAffine(), rcBaseMotionPath::isAtStep(), isState(), rcRectangle< T >::lr(), mAffineSize, mAffys, mark(), match(), mFirstBeatLength, mMajorEndPoints, mMajorEnds, mMidPoint, moving(), mRad, mRectSnaps, mSearchRects, mShapeRef, mTemplateOrigins, mTemplatePoses, mTemplateRects, mTemplates, mV, mXform, rcWindow::position(), rcWindow::rectangle(), rfRound(), rmAssert, rmMax, rmUnused, roundRectangle(), sDummy(), setState(), sideShorteningEstimate(), rcWindow::tiff(), rc2Xform::trans(), rcWindow::trim(), rcRectangle< T >::ul(), use4fixed(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by measure().
 {
   // @note Construction of a shape calculator is almost zero cost (everything is calculated when you need it and cached).
   //
   mXform = rc2Xform ();
   rc2Fvector current;
   // First Frame: use pre-segmented information and use profiles to generate first Ends detection
   if (isAtStep (1) &&  !isState (eHasFullyExtended)) // Run end detector to determine the ends
     {
       rcPolygon refined (*vc);
       mShapeRef = boost::shared_ptr<rcShape> (new rcShape (use4fixed(), *vc) );
       rcAffineRectangle ar = mShapeRef->affineRect ();
       // @note not sure this belongs here
       mAffys.push_back (mShapeRef->affineRect ());
       bool side = ar.cannonicalSize().x() >  ar.cannonicalSize().y();
       setState (eIsAffineXdirected, side);
       int32 d = side ? ar.cannonicalSize().x() : ar.cannonicalSize().y();
       //@note todo: use projection on the other end to get a better than halfway placement
       //@note remove redundant calculations
       rcDPair endpair = mShapeRef->majorEnds ();
       mMajorEnds.x() =  (float) endpair.x();
       mMajorEnds.y() =  (float) endpair.y();
       rcFPair maj (mMajorEnds.x() / (double) d, mMajorEnds.y() / (double) d);
       mRad= d / 5;
       rmAssert (mRad >= 8);
       for (uint32 i = 0; i < 2; i++)
     {
       mMajorEndPoints[i] = ar.affineToImage (rc2Fvector (side ? maj[i]: 0.5f, side ? 0.5f: maj[i]));
     }
       cardiacUpdate ();
     }
   else if (isAtStep (1) && isState (eHasFullyExtended))
     {
       //@note setup from the end points provided.
       cardiacUpdate ();
     }
   else
     {
       rmAssert (!isAtStep (1) &&  isState (eHasFullyExtended));
       rcAffineRectangle ar = affys().back();
       int32 sEst = rmMax (1, rfRound (sideShorteningEstimate () * mFirstBeatLength, sDummy));
       rmAssert(sEst > 0);
       mTemplatePoses.clear();
       mTemplatePoses.resize (2);
       mSearchRects.clear();
       mSearchRects.resize (2);
       vector<rc2Fvector> ends (2);
       rcDPair newEnds;
       // First Locate the ends in this frame
       for (uint32 i = 0; i < mTemplates.size(); i++)
     {
       // Get the template box and widen it according to the estimate
       rcFRect fr = mTemplateRects[i];
       int32 play (sEst);
       rcIRect fixed = roundRectangle (fr);
       rcWindow fixedw (use4fixed(), fixed, true);
       while (play && !fixedw.trim (-play)) play--;
       mSearchRects[i] = rcIRect (fixedw.rectangle().ul(), fixedw.rectangle().lr());
 #if 0
       std::string f ("/Users/arman/Desktop/fixed.tif");
       fixedw.tiff (f);
       std::string m  ("/Users/arman/Desktop/template.tif");
       mTemplates[i].window().tiff (m);
 #endif
       double q = match (fixedw, mTemplates[i], mTemplatePoses[i]);
       rmUnused (q);
       //      cerr << hex <<  (int32) use4fixed().frameBuf()->rowPointer (0) << " [" << i << "]: " <<
       //        mTemplatePoses[i] << "  " << int32 (q * 1000) << " (p: " << play << " )";
       // End template wrt frame = position of template TL wrt fixedw + position fixedw in frame
       mTemplatePoses[i] += rc2Fvector (fixedw.position ());
       //      cerr << "[" << i << "]: " << mTemplatePoses[i] << endl;
     }
       // Update TemplateRects: we start where we found the end the last time:
       for (uint32 rr = 0; rr < mTemplates.size(); rr++)
     {
       mTemplateRects[rr] = rcFRect (mTemplatePoses[rr].x(), mTemplatePoses[rr].y(), mTemplateRects[rr].width(),
                        mTemplateRects[rr].height());
     }
       // Add Template2end to Poses
       for (uint32 tp = 0; tp < mTemplates.size(); tp++)
     {
       mTemplatePoses[tp] = mTemplatePoses[tp] + mTemplateOrigins[tp];
     }
       // Using Center Position Translation, find out how much the cell has moved
       rc2Fvector newMidPoint ((mTemplatePoses[0] + mTemplatePoses[1]) / 2.0);
       mXform.trans (mMidPoint - newMidPoint);
       mMidPoint = newMidPoint;
       //      rcPolygon refined (*vc);
       //      refined.transform (mXform);
       //      mShapeRef = new rcShape (use4fixed(), refined);
       // How much has it moved from the origin (along the cardiac axis)
       for (uint32 ff = 0; ff < mTemplates.size(); ff++)
     {
       rc2Dvector tmp ((double) mTemplatePoses[ff].x(), (double) mTemplatePoses[ff].y());
       //      tmp = mCardiacAxis.project (tmp);
       tmp = ar.imageToAffine (tmp);
       newEnds[ff] = isState (eIsAffineXdirected) ? tmp.x() : tmp.y();
     }
       // Get the affine dimension used as major
       int32 d = isState (eIsAffineXdirected)  ? ar.cannonicalSize().x() : ar.cannonicalSize().y();
       mMajorEnds.x() = newEnds.x() * d;
       mMajorEnds.y() = newEnds.y() * d;
       current = rc2Fvector (mTemplatePoses[0].distance (mTemplatePoses[1]), 0.0f);
       // We can now mark that we have had a contraction
       mV = current - mAffineSize;
       mAffineSize = current;
       moving (mRectSnaps.back());
       mark(eMotion);
       mark(eContraction);
       mark(eDimensions);
     }
 }
void rcVisualFunction::cardiacUpdate () private
Definition at line 219 of file rc_visualcardiomyo.cpp.
References affys(), rcAffineRectangle::cannonicalSize(), clearState(), rcWindow::copyPixelsFromWindow(), distance(), eHasFullyExtended, eIsAffineXdirected, eMinMyoOtherDimensionInPixels, rcWindow::height(), rcBaseMotionPath::isAtStep(), mAffineSize, mFirstBeatLength, mMajorEndPoints, mMidPoint, mRad, mTemplateOrigins, mTemplateRects, mTemplates, rcPolygon::orthogonalEnclosingRect(), rmAssert, rmMin, roundRectangle(), setState(), rcRectangle< T >::size(), rc2Xform::trans(), rcPolygon::transform(), rcRectangle< T >::ul(), use4fixed(), rcWindow::width(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by cardiacMeasure().
 {
   if (isAtStep (1))
     {
       mTemplates.clear ();
       mTemplateRects.clear ();
       mTemplateOrigins.clear ();
       rcAffineRectangle ar = affys().back();
       bool side = ar.cannonicalSize().x() >  ar.cannonicalSize().y();
       setState (eIsAffineXdirected, side);
       int32 d = side ? ar.cannonicalSize().x() : ar.cannonicalSize().y();
       clearState (eHasFullyExtended);
       rc2Fvector csum;
       for (uint32 i = 0; i < 2; i++)
     {
       rcIPair ic ((int32) mMajorEndPoints[i].x(), (int32) mMajorEndPoints[i].y());
       csum += mMajorEndPoints[i];
       int32 umin =  rmMin (ic.x(), ic.y());
       if (umin < mRad) mRad =umin - 1;
       rmAssert (mRad >= (int32)  eMinMyoOtherDimensionInPixels);
       umin = use4fixed().width() - (1 + ic.x()+mRad); // -1 moved to - side
       umin -= 1; // border of 1 from the edge of the image
       if (umin < 0) mRad += umin; // reduce to fit
       rmAssert (mRad >= (int32)  eMinMyoOtherDimensionInPixels);
       umin = use4fixed().height() - (1 + ic.y()+mRad); // -1 moved to - side
       umin -= 1; // border of 1 from the edge of the image
       if (umin < 0) mRad += umin; // reduce to fit
       rmAssert (mRad >= (int32)  eMinMyoOtherDimensionInPixels);
       rcPolygon pg (mRad /2.0f, 8);
       rc2Xform xt;
       xt.trans (mMajorEndPoints[i]);
       pg.transform (xt);
       rcFRect fr;      rcIRect ir;
       pg.orthogonalEnclosingRect (fr);
       ir = roundRectangle (fr);
       rcWindow tmp (use4fixed (), ir, true);
       rcWindow fixedCopy (ir.size());
       fixedCopy.copyPixelsFromWindow (tmp);
       rcCorrelationWindow<uint8> fixedw (fixedCopy);
       mTemplates.push_back (fixedw);
       mTemplateRects.push_back (fr);
       mTemplateOrigins.push_back (rc2Fvector(mMajorEndPoints[i].x() - fr.ul().x(), mMajorEndPoints[i].y() - fr.ul().y()));
       //      cerr << hex << (int32) use4fixed().frameBuf()->rowPointer (0) << " [" << i << "]: " <<
       //        "Template [" << mTemplates.size() << "] made: " << fr << " i " << ir << endl;
     }
       // Construct a line from one end to the other end
       csum /= 2.0; // center in affine coordinates
       mMidPoint = rc2Fvector ((float) csum.x(), (float) csum.y());
       mAffineSize = rc2Fvector (mMajorEndPoints[0].distance (mMajorEndPoints[1]), 0.0f);
       mFirstBeatLength = mAffineSize.x();
       setState (eHasFullyExtended);
     }
 }
const vector<rc2Fvector>& rcVisualFunction::children () const inline
Definition at line 686 of file rc_visualcell.h.
References mChildren.
   {
     return mChildren;
   }
float rcVisualFunction::circularity () const inline
Definition at line 277 of file rc_visualcell.h.
References mCircularity.
Referenced by measure(), operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mCircularity;
   }
bool rcVisualFunction::clear (enum Haves what)
Definition at line 375 of file rc_visualfunction.cpp.
References have(), and mHaves.
Referenced by beatProcess(), computeAcceleration(), correspond(), correspondMutualChannel(), populationMigration(), reconcile(), and updateSims().
 {
   mHaves.reset(what);
   return have (what);
 }
bool rcVisualFunction::clearState (const State st) inline
Definition at line 158 of file rc_visualcell.h.
References isState(), and mState.
Referenced by cardiacUpdate(), and framesPerPeriod().
 {mState.reset (st);return isState (st); }
double rcVisualFunction::computeAcceleration () private
Definition at line 396 of file rc_visualfunction.cpp.
References acceleration(), clear(), eAcceleration, eCoarseSS, have(), mAcceleration, mAcl, mark(), mCoarseSimRef, mSS, rmAssert, and ssWindowSize().
Referenced by update().
 {
     mAcceleration = 0.0; //gInValidAcceleration;
   clear (eAcceleration);
   if (have (eCoarseSS))
     {
       deque<double> signal;
       bool hasSignal = mCoarseSimRef->entropies (signal);
       if (hasSignal && signal.size())
     {
       rmAssert (signal.size () == mCoarseSimRef->matrixSz ());
       mSS.push_back (signal[mCoarseSimRef->matrixSz () / 2]);
       if (mSS.size() > (uint32) ssWindowSize ())
         {
           mAcceleration = log10(mSS[mSS.size() - 1] / mSS[mSS.size() - 2]);
           mAcl.push_back ((float) acceleration ());
           mark (eAcceleration);
         }
     }
     }
   return mAcceleration;
 }
float rcVisualFunction::contractionFrequency () const inline
Definition at line 473 of file rc_visualcell.h.
References ePacingInfo, gNotAvailable, have(), mContractionFrequency, and mFramesPerPeriod.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     if (have (ePacingInfo) && mFramesPerPeriod >= 0.0)
       return mContractionFrequency;
     else
       return gNotAvailable;
   }
const rc2Fvector& rcVisualFunction::cop () const inline
Definition at line 660 of file rc_visualcell.h.
References mMotionCtr.
   {
     return mMotionCtr;
   }
void rcVisualFunction::correspond (const rc2Fvector & pose, const rcFPair & tolerance) private
Definition at line 698 of file rc_visualcell.cpp.
References rcStatistics::add(), clear(), rcWindow::copyPixelsFromWindow(), eIsOutSide, eMotion, isState(), mark(), match(), moving(), mRectSnaps, mSumQuality, mXform, rmAssert, rmUnused, roundRectangle(), setState(), rcRectangle< T >::size(), rc2Xform::trans(), rcRectangle< T >::translate(), rcRectangle< T >::ul(), updateRects(), use4fixed(), use4moving(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by measure().
  {
    rmUnused (pose);
    int32 dummy;
    // Declare no translation
    rc2Fvector tr;
    // Are we registring to the immediate past
    rcFRect registerTo = mRectSnaps.back ();
    // Set up moving: fixed plus tolerances
    rcFRect fMoving;
    rcIRect iMoving;
    rcIRect fixed = roundRectangle (registerTo);
    if (!use4fixed().contains (fixed))
      {
        mXform.trans (tr); // default ctor of vector is 0,0
        clear (eMotion);
        return;
      }
    updateRects (registerTo, tolerance, fMoving, iMoving);
    if (isState (eIsOutSide))
      {
        mXform.trans (tr); // default ctor of vector is 0,0
        clear (eMotion);
        return;
      }
    // If after triming we have not really expanded. Assume nothing.
    rcIPair play = iMoving.size () - fixed.size ();
    if (play.x() < 2 || play.y() < 2)
      {
        mXform.trans (tr); // default ctor of vector is 0,0
        clear (eMotion);
        rmAssert (setState (eIsOutSide));
        return;
      }
    // Note using the fixedRaw(), moving() pair
    // @note moving and fixed buffers belong to a ring buffer that
    // @note is rotated every acquisition. Beware of rcWindows in to these
    // @note buffers. They will not contain original content after a ring
    // @note rotation. I believe this is handled by rcWindow mutex implementation
    // @note so this copy is unnecessary but it does relax requiring framebuf it
    // belongs to stay around
    // Create a model at the last frame.
    // @note For Functions that are shape perseving we used a model from the first one
    rcWindow movingWin (use4moving(), iMoving, dummy);
    rcWindow fixedw (use4fixed(), fixed, true);
    rcWindow fixedCopy (fixed.size());
    fixedCopy.copyPixelsFromWindow (fixedw);
    rcCorrelationWindow<uint8> fixedWin (fixedCopy);
    // This is the translation of fixed in moving.
    // @note registrating to the previous frame
    mSumQuality.add (match (movingWin, fixedw, tr));
    /* Motion of fixed wrt moving:
     * Moving + fixed_location (integer+interpolated offset) @ now
     *          - fixed_location @ last
     */
    fMoving.translate (rcFPair (tr.x(), tr.y()));
    fMoving.size (registerTo.size());
    tr = rc2Fvector (fMoving.ul().x(), fMoving.ul().y()) -
      rc2Fvector (registerTo.ul().x(), registerTo.ul().y());
    moving (fMoving);
    mXform.trans (tr);
    mark (eMotion);
 }
void rcVisualFunction::correspondMutualChannel (const rc2Fvector & pose, const rcFPair & tolerance) private
Definition at line 781 of file rc_visualcell.cpp.
References rcStatistics::add(), clear(), rcWindow::copyPixelsFromWindow(), eIsOutSide, eMotion, rcBaseMotionPath::isAtStep(), mark(), match(), moving(), mRectSnaps, mSnaps, mSumQuality, mXform, rfGaussianConv(), rmAssert, rmAssertDebug, rmUnused, roundRectangle(), setState(), sharedKin(), rcRectangle< T >::size(), rc2Xform::trans(), rcRectangle< T >::translate(), rcRectangle< T >::ul(), updateRects(), use4fixed(), use4moving(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by measure().
  {
    rmUnused (pose);
    int32 dummy;
    // Declare no translation
    rc2Fvector tr, cr;
    // Are we registring to the immediate past or to the first frame?
    rcFRect registerTo = mRectSnaps.back ();
    // Set up moving: fixed plus tolerances
    rcFRect fMoving;
    rcIRect iMoving;
    rcIRect fixed = roundRectangle (registerTo);
    updateRects (registerTo, tolerance, fMoving, iMoving);
    // If after triming we have not really expanded. Assume nothing.
    rcIPair play = iMoving.size () - fixed.size ();
    if (play.x() < 2 || play.y() < 2)
      {
        rmAssertDebug (tr.x() == 0.0f && tr.y() == 0.0f);
        mXform.trans (tr); // default ctor of vector is 0,0
        clear (eMotion);
        rmAssert (setState (eIsOutSide));
        return;
      }
    if (isAtStep (1))
      {
        {
      rcIRect fixed = roundRectangle (mRectSnaps.back ());
      rcWindow fixedw (use4fixed (), fixed, true);
      rcWindow fixedCopy (fixed.size());
      rfGaussianConv (fixedw, fixedCopy, 5);
      rcCorrelationWindow<uint8> fixedWin (fixedCopy);
      mSnaps.push_back (fixedWin);
        }
        {
      rcIRect fixed = roundRectangle (mRectSnaps.back ());
      rcWindow fixedw (sharedKin()->fixed (), fixed, true);
      rcWindow fixedCopy (fixed.size());
      rfGaussianConv (fixedw, fixedCopy, 5);
      rcCorrelationWindow<uint8> fixedWin (fixedCopy);
      mSnaps.push_back (fixedWin);
        }
      }
    /* @note See note in corresponde about ring buffers
     * Window in moving and fixed in channel
     * match in both channels keep the best.
     * note: we are not conductng 2 different tracking
     */
    double tq (-1.0); // , cq (-1.0);
    {
      rcWindow movingWin (use4moving(), iMoving, dummy);
      rcWindow fixedw (use4fixed(), fixed, true);
      rcWindow fixedCopy (fixed.size());
      fixedCopy.copyPixelsFromWindow (fixedw);
      rcCorrelationWindow<uint8> fixedWin (fixedCopy);
      // This is the translation of fixed in moving.
      // @note registrating to the previous frame
      tq = match (movingWin, mSnaps[0], tr);
    }
 #if 0
    {
      rcWindow movingWin (sharedKin()->moving(), iMoving, dummy);
      rcWindow fixedw (sharedKin()->fixed (), fixed, true);
      rcWindow fixedCopy (fixed.size());
      fixedCopy.copyPixelsFromWindow (fixedw);
      rcCorrelationWindow<uint8> fixedWin (fixedCopy);
      // This is the translation of fixed in moving.
      // @note registrating to the previous frame
      cq = match (movingWin, mSnaps[1], cr);
    }
    if (cq > 0.0 && cq > tq)
      {
        tq = cq; tr = cr;
      }
 #endif
    /* Motion of fixed wrt moving:
     * Moving + fixed_location (integer+interpolated offset) @ now
     *          - fixed_location @ last
     */
    fMoving.translate (rcFPair (tr.x(), tr.y()));
    fMoving.size (registerTo.size());
    tr = rc2Fvector (fMoving.ul().x(), fMoving.ul().y()) -
      rc2Fvector (registerTo.ul().x(), registerTo.ul().y());
    moving (fMoving);
    mXform.trans (tr);
    mark (eMotion);
    mSumQuality.add (tq);
    //@todo work out model allocations
    //@todo we failed to match to the next frame using the oldest model
    //@todo Time to update the model
    //@todo Where is the current position?
    //@todo Get the enclosing box of the current poly
    //@todo remember the offset between enclosing box and position
    //@todo add vector overloads for rcRectangle
    //@todo how do we index to the rect that model was made from ?
 }
float rcVisualFunction::cQuality () const inline
Definition at line 562 of file rc_visualcell.h.
References mCorrespondenceQuality.
Referenced by measure(), and predictedTolerance().
   {
     return mCorrespondenceQuality;
   }
void rcVisualFunction::cQuality (const float _arg) inline
Definition at line 567 of file rc_visualcell.h.
References mCorrespondenceQuality.
   {
     if (mCorrespondenceQuality != _arg)
       {
     mCorrespondenceQuality = _arg;
       }
   }
void rcVisualFunction::createIrradianceModel () private
Definition at line 249 of file rc_visualfunction.cpp.
References rcMathematicalImage::eHiPeak, rcMathematicalImage::gauss(), mGaussModel, mIradModel, mRectSnaps, rcPixel8, rfRound(), rkPI, and rmMax.
Referenced by rcVisualFunction().
 {
   // Create a Gauss Model. Currently only for catching daughters after mitosis
   // Default is a gaussian with std of 1.0
   static const int32 dummy (0);
   int32 d = rfRound (sqrt (mRectSnaps.back().area() / rkPI), dummy);
   d = rmMax (16, d);
   rcPixel depth (rcPixel8);
   rcWindow tmp (d, d, depth);
   mIradModel.gauss (tmp, rcMathematicalImage::eHiPeak);
   mGaussModel = rcCorrelationWindow<uint8> (tmp);
 }
const rcFPair rcVisualFunction::dimensions () const inline
Definition at line 381 of file rc_visualcell.h.
References eDimensions, have(), isCardiacCell(), mAffineSize, mRectSnaps, rmExceptionMacro, rc2Xform::scale(), sharedKin(), rc2dVector< T >::x(), rcKinetoscope::xform(), and rc2dVector< T >::y().
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     if (!have (eDimensions))
       rmExceptionMacro (<<"Does not have dimensional information");
     const rc2Xform& xform = sharedKin()->xform();
     if (isCardiacCell ())
       {
     return rcFPair (mAffineSize.x() * xform.scale(),
             mAffineSize.y() * xform.scale ());
       }
     else
       {
     return rcFPair (mRectSnaps.back().size().x() * xform.scale(),
             mRectSnaps.back().size().y() * xform.scale());
       }
   }
void rcVisualFunction::direct (const rc2Fvector & pose) private
Definition at line 653 of file rc_visualcell.cpp.
References rcStatistics::add(), eMotion, rcRectangle< T >::lr(), mark(), mCurrentPosition, moving(), mRectSnaps, mSumQuality, mXform, rmMax, rmMin, sharedKin(), rc2Xform::trans(), rcRectangle< T >::translate(), rcRectangle< T >::ul(), rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by measure().
  {
    const rcFRect& fpframe = sharedKin()->fpframe ();
    // Declare no translation
    rc2Fvector tr = pose - mCurrentPosition;
    // Are we registring to the immediate past
    rcFRect fMoving, fFixed = mRectSnaps.back ();
    fMoving = fFixed;
    // Direct is perfect!
    mSumQuality.add (1.0);
    /* Motion of fixed wrt moving:
     * Moving + fixed_location (integer+interpolated offset) @ now
     *          - fixed_location @ last
     * Adjust pose if the rect is positioned outside
     */
    fMoving.translate (rcFPair (tr.x(), tr.y()));
    // @todo move only in the direction needed
    rcFPair ud, d;
    ud.x() = rmMax (fpframe.ul().x(), fMoving.ul().x());
    ud.y() = rmMax (fpframe.ul().y(), fMoving.ul().y());
    // @todo adjust size only in the direction needed
    // @note trim is move out the ul and move in the lr
    d.x() = rmMin (fpframe.lr().x(), fMoving.lr().x());
    d.y() = rmMin (fpframe.lr().y(), fMoving.lr().y());
    fMoving = rcFRect (ud, d);
    tr = rc2Fvector (ud - fFixed.ul());
    moving (fMoving);
    mXform.trans (tr);
    mark (eMotion);
  }
float rcVisualFunction::directedCellPersistence () const inline
Definition at line 506 of file rc_visualcell.h.
References mMotionPattern.
   {
     return mMotionPattern;
   }
float rcVisualFunction::distance () const inline
Definition at line 303 of file rc_visualcell.h.
References rcMatrix_2d::isSingular(), rc2Xform::matrix(), mDistance, rc2Xform::scale(), sharedKin(), and rcKinetoscope::xform().
Referenced by cardiacMeasure(), cardiacUpdate(), measure(), operator<<(), and rcCellWriterGroup::writeValues().
   {
     const rc2Xform& xform = sharedKin()->xform();
     if (xform.matrix().isSingular())
       return mDistance;
     else
       return mDistance * xform.scale ();
   }
int32 rcVisualFunction::dividedFrameIndex () const inline
Definition at line 531 of file rc_visualcell.h.
References mExpDividedFrameIndex.
   {
     return mExpDividedFrameIndex;
   }
bool rcVisualFunction::dividedProcess () private
const rcIRect& rcVisualFunction::dividingArea () const inline
Definition at line 691 of file rc_visualcell.h.
References mDividingWatchWindow.
   {
     return mDividingWatchWindow;
   }
void rcVisualFunction::dividingMeasure (vector< rcPolygon >::const_iterator &) private
bool rcVisualFunction::dividingProcess () private
Definition at line 196 of file rc_visualdivision.cpp.
References ends(), gGoodFit, grow(), rcCorrelationWindow< T >::height(), rcWindow::height(), rcRectangle< T >::height(), mAnaphase, mChildren, mDividingWatchWindow, mGaussModel, mRectSnaps, rfImageFind(), rfRealEq(), rkPI, rmMin, space, rcRectangle< T >::ul(), updateRects(), use4fixed(), use4moving(), rcCorrelationWindow< T >::width(), rcWindow::width(), rcRectangle< T >::width(), rcCorrelationWindow< T >::window(), rcPair< T >::x(), and rcPair< T >::y().
 {
 #if 0
   rcFRect fixed = mRectSnaps.back();
   mAnaphase--;
   // make one 3 time as wide and high
   rcFRect fMoving;
   rcFPair tol (0.67f, 0.67f);
   updateRects (fixed, tol, fMoving, mDividingWatchWindow);
   if (!(mDividingWatchWindow.width() > mGaussModel.width() &&
     mDividingWatchWindow.height() > mGaussModel.height()))
     return false;
  // make a window in fixed and moving and look for daughters
   vector<rcWindow> zone;
   zone.push_back (rcWindow (use4moving(), mDividingWatchWindow, true));
   zone.push_back (rcWindow (use4fixed(), mDividingWatchWindow, true));
   vector<rcIRect> bRects;
   vector<rc2Fvector> links;
   rcWindow gaussm = mGaussModel.window ();
   double mind (gaussm.width() * 0.90);
   for (uint32 i = 0; i < 2; i++)
     {
       bRects.clear ();
       list<rcPeak<int16> > locs;
       rcWindow space;
       rfImageFind (zone[i], gaussm, locs, space);
       // If we have two far away peaks better than 500
       // Peaks are in decreasing scores.
       list<rcPeak<int16> >::iterator rTr = locs.begin();
       if (locs.size() < 2) return false;
       float minScore (rTr->value);
       vector<rc2Fvector> ends;
       for (uint32 i = 0; i < 2; i++, rTr++)
     {
       rcIRect tmp (rTr->_location.x() + mDividingWatchWindow.ul().x(),
                rTr->_location.y() + mDividingWatchWindow.ul().y(),
                gaussm.width(), gaussm.height());
       bRects.push_back (tmp);
       minScore = rmMin (minScore, rTr->value);
       ends.push_back (rTr->interp);
       rc2Fvector vtmp (fMoving.ul()); vtmp += rTr->interp;
       mChildren.push_back (vtmp);
     }
       if (minScore < gGoodFit) return false;
       ends[0] -= ends[1];
       if (ends[0].isLenNull() || ends[0].len () < mind) return false;
       links.push_back (ends[0]);
     }
   rcRadian play (rkPI / 4.0);
   if (!rfRealEq (links[0].angle(), links[1].angle(), play)) return false;
    // go ahead an multiply
   return grow (bRects);
 #endif
   return false;
 }
float rcVisualFunction::ellipseRatio () const inline
Definition at line 286 of file rc_visualcell.h.
References mEllipseRatio.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mEllipseRatio;
   }
deque<rc2Fvector>& rcVisualFunction::ends () const private
Referenced by cardiacMeasure(), and dividingProcess().
rcVisualFunction::State rcVisualFunction::fineState () const
Definition at line 440 of file rc_visualfunction.cpp.
References eIsChild, eIsDirected, eIsFragmented, eIsJustDivided, eIsParent, eIsRounded, eIsRounding, and isState().
 {
   if(isState(eIsDirected)) return   eIsDirected;
   if(isState(eIsJustDivided)) return   eIsJustDivided;
   if(isState(eIsFragmented)) return   eIsFragmented;
   if(isState(eIsParent)) return   eIsParent;
   if(isState(eIsChild)) return   eIsChild;
   if(isState(eIsRounding)) return   eIsRounding;
   if(isState(eIsRounded)) return   eIsRounded;
 }
void rcVisualFunction::frameIndex (int32 fi) inline
Definition at line 537 of file rc_visualcell.h.
References mExpStartFrameIndex, and rmAssert.
Referenced by grow().
   {
     rmAssert (fi >= 0);
     mExpStartFrameIndex = fi;
   }
float rcVisualFunction::framesPerPeriod () const inline
Definition at line 443 of file rc_visualcell.h.
References eIsPeriodic, gNotAvailable, isState(), and mFramesPerPeriod.
Referenced by beatProcess(), framesPerPeriod(), pacingFrequency(), rcVisualFunction(), and sideShorteningEstimate().
   {
     if (isState (eIsPeriodic) && mFramesPerPeriod >= 0.0)
       return mFramesPerPeriod;
     else
     return gNotAvailable;
   }
float rcVisualFunction::framesPerPeriod (float p) private
Definition at line 350 of file rc_visualfunction.cpp.
References clearState(), eIsPeriodic, framesPerPeriod(), mBeatAC, mFramesPerPeriod, mFramesPerPeriodPowerOf2, mIntegralFramesPerPeriod, rfRoundPlus(), sDummy(), and setState().
 {
   clearState (eIsPeriodic);
   mFramesPerPeriod = p;
   if (p > 0.0) setState (eIsPeriodic);
   mIntegralFramesPerPeriod = rfRoundPlus (framesPerPeriod (), sDummy);
   // Use a window (up adjusted to power of 2) of two periods to estimate contraction frequency
   frexp (p+p, &mFramesPerPeriodPowerOf2);
   mFramesPerPeriodPowerOf2 = (int32) ldexp (1.0f, mFramesPerPeriodPowerOf2);
   mBeatAC.resize (mFramesPerPeriodPowerOf2);
   return p;
 }
int32 rcVisualFunction::framesPerPeriodPowerOf2 () const inline
Definition at line 459 of file rc_visualcell.h.
References eIsPeriodic, gNotAvailable, isState(), mFramesPerPeriod, and mFramesPerPeriodPowerOf2.
   {
     if (isState (eIsPeriodic) && mFramesPerPeriod >= 0.0)
       return mFramesPerPeriodPowerOf2;
     else
       return (int32) gNotAvailable;
   }
uint32 rcVisualFunction::generation () const inline
Definition at line 186 of file rc_visualcell.h.
References mGeneration.
Referenced by grow().
 {return mGeneration; }
bool rcVisualFunction::grow (const vector< rcIRect > & bRects) private
Definition at line 264 of file rc_visualdivision.cpp.
References eIsChild, eIsGeneralModel, frameIndex(), generation(), id(), info(), mGeneration, mId, mMinTemporalEncRect, mMinTemporalIntRect, moving(), mParentId, organism(), organismName(), setState(), and sharedKin().
Referenced by dividingProcess().
 {
   vector<rcIRect>::const_iterator cItr = bRects.begin();
   vector<rcVisualFunction> two;
 // Find which one of the RLEs in connect() correspond to the Daughters
   for (int32 i = 0; i < (int32) bRects.size(); i++, cItr++)
     {
       rcPolygon poly (cItr->width() / 2.0f, 8);
       rc2Fvector motionCtr;
       poly.translate (rc2Dvector (cItr->ul().x(), cItr->ul().y()));
       poly.centerOf (motionCtr);
       rcVisualFunction vf (sharedKin ().get() , motionCtr, poly, true);
       vf.mMinTemporalIntRect = *cItr;
       vf.mMinTemporalEncRect = *cItr;
       vf.mId = (uint32) i;
       vf.mParentId = id();
       vf.mGeneration = generation() + 1;
       vf.info (organism(), organismName ());
       vf.setState(eIsChild);
       vf.setState(eIsGeneralModel);
       vf.frameIndex(sharedKin()->moving().frameBuf()->frameIndex ());
       two.push_back (vf);
     }
   // Only add the children if both could be created
   if (two.size() == 2)
     {
       for (uint32 i = 0; i < 2; i++)
     {
       sharedKin()->mDaughterFunctionMap.push_back (two[i]);
     }
     }
   return (two.size() == 2);
 }
bool rcVisualFunction::grow (vector< rcPolygon > groupIntersects, list< rcVisualFunction > & functionList) private
Definition at line 149 of file rc_visualdivision.cpp.
References rcShape::eImage, eIsChild, frameIndex(), generation(), id(), moving(), organism(), organismName(), sharedKin(), and rcRectangle< T >::ul().
 {
   if (groupIntersects.size() != 2) return false;
   vector<rcPolygon>::iterator gp = groupIntersects.begin();
   vector<rcVisualFunction> two;
 // Find which one of the RLEs in connect() correspond to the Daughters
   for (int32 i = 0; i < (int32) groupIntersects.size(); i++, gp++)
     {
       rc2Fvector motionCtr;
       rcIRect ir =   gp->orthogonalEnclosingRect();
       // Compute Center Of Mass Using Moving Time (by definition for growing)
       rcWindow src =sharedKin()->moving();
       if (sharedKin()->channelAvailable())
     {
       src = sharedKin()->channelMoving();
     }
       rcWindow tmp (src, ir);
       rcShapeRef shaper = boost::shared_ptr<rcShape> (new rcShape (tmp));
       motionCtr = shaper->centerOfmass (rcShape::eImage);
       motionCtr += rc2Fvector (ir.ul());
       rcVisualFunction vf (sharedKin ().get (), motionCtr, *gp, true);
       vf.mMinTemporalIntRect = ir;
       vf.mMinTemporalEncRect = ir;
       vf.mId = (uint32) i;
       vf.mParentId = id();
       vf.mGeneration = generation() + 1;
       vf.info (organism(), organismName ());
       vf.setState(eIsChild);
       vf.frameIndex(sharedKin()->moving().frameBuf()->frameIndex ());
       functionList.push_back (vf);
     }
 }
bool rcVisualFunction::have (enum Haves what) const
Definition at line 364 of file rc_visualfunction.cpp.
References mHaves.
Referenced by clear(), computeAcceleration(), contractionFrequency(), dimensions(), mark(), operator<<(), pacingFrequency(), rcVisualFunction(), reconcile(), and update().
 {
   return mHaves[what];
 }
const int32 rcVisualFunction::history () const inline
Definition at line 584 of file rc_visualcell.h.
References mSize.
 {return mSize; }
uint32 rcVisualFunction::id () const inline
Definition at line 176 of file rc_visualcell.h.
References mId.
Referenced by rcCellWriterGroupCollection::addCell(), grow(), isIsoMorphic(), operator<<(), and populationMigration().
 {return mId; }
void rcVisualFunction::info (rcOrganismInfo::OrganismType c = rcOrganismInfo::eDefault, rcOrganismInfo::OrganismName n = rcOrganismInfo::eUnknown)
Definition at line 344 of file rc_visualfunction.cpp.
References mOname, and mOtype.
Referenced by grow(), and rcVisualFunction().
 {
   mOtype = c;
   mOname = n;
 }
void rcVisualFunction::initFunction () private
Definition at line 115 of file rc_visualfunction.cpp.
References mAffineSize, mAnaphase, mArea, mBeatNumber, mBeatShortenning, mCircularity, mCosSums, mDistance, mDividingTicks, mEllipseIndex, mEllipseRatio, mExpDividedFrameIndex, mHaves, mId, mLabel, mLastAngle, mMajorEndPoints, mMotionPattern, mNsQ, mPerimeter, mRdiffuse, mSize, mState, mSumQuality, rcStatistics::reset(), and rmAssert.
Referenced by rcVisualFunction().
 {
   rmAssert (!mHaves.any());
   rmAssert (!mState.any());
   mLastAngle = rcRadian (0.0);
   mId = 0;
   mSize = 0;
   mArea = 0;
   mLabel =  mExpDividedFrameIndex = mEllipseIndex = 0;
   mAffineSize = rcFPair (0.0f, 0.0f);
   mCosSums = 0.0f;
   mSumQuality.reset ();
   mRdiffuse = mPerimeter = mEllipseRatio = mCircularity = 0.0f;
   mDistance = 0.0f;
   mMotionPattern = 0.0f;
   mBeatNumber = 0.0f;
   mDividingTicks = mAnaphase = mNsQ = 0;
 //  gNotAvailablePair = rcDPair (gNotAvailable, gNotAvailable);
   mBeatShortenning = 0.0f;
   mMajorEndPoints.resize (2);
 }
void rcVisualFunction::initializeSimilarator (const rcFRect & simRect) private
Definition at line 262 of file rc_visualfunction.cpp.
References rcSimilarator::eExhaustive, eHasSimilarator, isCardiacCell(), mCoarseSimRef, mCurrentSimRect, rcPixel8, setState(), sharedKin(), ssWindowSize(), updateSims(), and use4fixed().
Referenced by rcVisualFunction().
 {
   uint32 temporalSimilarityWindowSize (3);
   if (isCardiacCell ())
     (uint32) (sharedKin()->periodicMotion() / 2.0f);
   ssWindowSize ( temporalSimilarityWindowSize);
   mCoarseSimRef = boost::shared_ptr<rcSimilarator> (new rcSimilarator (rcSimilarator::eExhaustive,
                                                                                                                                              rcPixel8, temporalSimilarityWindowSize , 0));
   mCurrentSimRect = rect;
   setState (eHasSimilarator);
   updateSims (use4fixed(), mCurrentSimRect);
 }
const rc2Xform rcVisualFunction::instantTransformation () const inline
Definition at line 353 of file rc_visualcell.h.
References mXform.
   {
     return mXform;
   }
const rc2Fvector rcVisualFunction::instantVelocity () const inline
Definition at line 343 of file rc_visualcell.h.
References mV, and sharedKin().
   {
     return sharedKin()->xform().mapPoint (mV);
   }
int32 rcVisualFunction::integralFramesPerPeriod () const inline
Definition at line 451 of file rc_visualcell.h.
References eIsPeriodic, gNotAvailable, isState(), mFramesPerPeriod, and mIntegralFramesPerPeriod.
Referenced by beatProcess().
   {
     if (isState (eIsPeriodic) && mFramesPerPeriod >= 0.0)
       return mIntegralFramesPerPeriod;
     else
      return (int32) gNotAvailable;
   }
const deque<rcFPair>& rcVisualFunction::interpolatedMin () const inline
Definition at line 676 of file rc_visualcell.h.
References mInterpolatedMin.
   {
     return mInterpolatedMin;
   }
uint32 rcVisualFunction::intersectSet (vector< rcPolygon * > & corrs) private
Definition at line 93 of file rc_visualdivision.cpp.
References polygons(), and sharedKin().
Referenced by isIsoMorphic().
 {
   if (!corrs.empty())
     corrs.clear ();
   vector<rcPolygon>::iterator polys = sharedKin()->mPOLYs.begin();
   vector<rcPolygon>::iterator polyend = sharedKin()->mPOLYs.end();
   rcPolygon dispoly (polygons().back());
    for (; polys != polyend; polys++)
      {
        if (polys->intersects (dispoly))
          {
            corrs.push_back (&(*polys));
          }
      }
    return corrs.size();
 }
bool rcVisualFunction::isCardiacCell () const inline
Definition at line 209 of file rc_visualcell.h.
References rcOrganismInfo::eCardioMyocyte, rcOrganismInfo::eCardioMyocyteCalcium, rcOrganismInfo::eCardioMyocyteSelected, rcOrganismInfo::eCell, organism(), and organismName().
Referenced by dimensions(), initializeSimilarator(), measure(), operator<<(), rcCellWriterGroup::rcCellWriterGroup(), reconcile(), and update().
   {
     return (organism() == rcOrganismInfo::eCell &&
         (organismName() == rcOrganismInfo::eCardioMyocyte ||
          organismName() == rcOrganismInfo::eCardioMyocyteSelected ||
          organismName() == rcOrganismInfo::eCardioMyocyteCalcium));
   }
bool rcVisualFunction::isIsoMorphic () private
Definition at line 111 of file rc_visualdivision.cpp.
References eIsDivided, eIsOutSide, id(), intersectSet(), and sharedKin().
 {
   vector<rcPolygon*>corr;
   // How many region polys intersect with me?
   intersectSet (corr);
   if (!corr.size() == 1)
     {
       return false;
     }
   // So only one region poly  intersects with this cell.
   // How many cells intersect with this region poly.
   list<rcVisualFunction>::const_iterator  cell = sharedKin()->visualBodies ().begin();
   list<rcVisualFunction>::const_iterator  cellend = sharedKin()->visualBodies ().end();
   for (; cell != cellend; cell++)
     {
       if (cell->isState(eIsOutSide)) continue;
       if (cell->isState(eIsDivided)) continue;
       if (cell->id() == id()) continue; // skip me
       rcPolygon dispoly (cell->polygons().back());
       if (corr[0]->intersects (dispoly))
     {
       return false;
     }
     }
   return true;
 }
bool rcVisualFunction::isLabelProtein () const inline
Definition at line 217 of file rc_visualcell.h.
References rcOrganismInfo::eFluorescenceCluster, rcOrganismInfo::eProtein, rcOrganismInfo::eProteinP53, organism(), and organismName().
Referenced by measure(), operator<<(), rcVisualFunction(), and update().
   {
     return (organism() == rcOrganismInfo::eFluorescenceCluster &&
         (organismName() == rcOrganismInfo::eProtein || organismName() == rcOrganismInfo::eProteinP53));
   }
bool rcVisualFunction::isNotState (const State st) const inline
Definition at line 155 of file rc_visualcell.h.
References mState.
 {return !mState[st]; }
bool rcVisualFunction::isOfOrganismName (rcOrganismInfo::OrganismName onm) const inline
Definition at line 203 of file rc_visualcell.h.
References mOname.
   { return mOname == onm; }
bool rcVisualFunction::isOfOrganismType (rcOrganismInfo::OrganismType ot) const inline
Definition at line 200 of file rc_visualcell.h.
References mOtype.
   { return mOtype == ot; }
bool rcVisualFunction::isOfOrganismTypeAndName (rcOrganismInfo::OrganismType ot, rcOrganismInfo::OrganismName onm) const inline
Definition at line 206 of file rc_visualcell.h.
References mOname, and mOtype.
   { return (mOtype == ot && mOname == onm); }
bool rcVisualFunction::isState (const State st) const inline
Definition at line 154 of file rc_visualcell.h.
References mState.
Referenced by cardiacMeasure(), clearState(), correspond(), fineState(), framesPerPeriod(), framesPerPeriodPowerOf2(), integralFramesPerPeriod(), operator<<(), reconcile(), rfCellNotViable(), setState(), state(), update(), and updateSims().
 {return mState[st]; }
int32 rcVisualFunction::label () const inline
Definition at line 521 of file rc_visualcell.h.
References mLabel.
Referenced by measure().
   {
     return mLabel;
   }
int32 rcVisualFunction::label (int32 l) inline
Definition at line 548 of file rc_visualcell.h.
References eCorrespondence, mark(), mLabel, and rmAssert.
   {
     rmAssert (l >= 0);
     mLabel = l;
     mark (eCorrespondence);
     return mLabel;
   }
const vector<rc2Fvector>& rcVisualFunction::majorEndPoints () const inline
Definition at line 409 of file rc_visualcell.h.
References mMajorEndPoints.
 { return mMajorEndPoints; }
const deque<rc2Fvector>& rcVisualFunction::majorEndPoses () const inline
Definition at line 410 of file rc_visualcell.h.
References mTemplatePoses.
 {return mTemplatePoses;}
const rcFPair& rcVisualFunction::majorEnds () const inline
Definition at line 408 of file rc_visualcell.h.
References mMajorEnds.
 { return mMajorEnds; }
bool rcVisualFunction::mark (enum Haves what)
Definition at line 369 of file rc_visualfunction.cpp.
References have(), and mHaves.
Referenced by beatProcess(), cardiacMeasure(), computeAcceleration(), correspond(), correspondMutualChannel(), direct(), label(), measure(), populationMigration(), update(), updateSims(), and vXform().
 {
   mHaves.set(what);
   return have (what);
 }
float rcVisualFunction::mass () const inline
Definition at line 257 of file rc_visualcell.h.
References mMass.
   {
     return mMass;
   }
double rcVisualFunction::match (rcWindow & image, rcWindow & model, rc2Fvector & trans) private
Definition at line 913 of file rc_visualcell.cpp.
References rcTimingInfo::printInfo(), rfImageFind(), and rcTimingInfo::touch().
Referenced by cardiacMeasure(), correspond(), correspondMutualChannel(), and match().
 {
   rcFindList locs;
   rcWindow cspace;
   rcTimingInfo profile (2, 10);
   // We are looking for the top score
   locs.resize (1);
   profile.touch (0);
   rfImageFind (moving, fixed, locs, cspace);
   profile.touch (1);
   vector<std::string> lables;
   lables.push_back (std::string ("match"));
   lables.push_back (std::string ("Image Find"));
   profile.printInfo (10, lables);
   rcFindList::iterator tmp = locs.begin();
   //  trans = tmp->_interp;
   //return (tmp->value / 1000.0);
   return 0.0;
 }
double rcVisualFunction::match (rcWindow & image, rcCorrelationWindow< uint8 > & model, rc2Fvector & trans) private
Definition at line 904 of file rc_visualcell.cpp.
References match(), and rcCorrelationWindow< T >::window().
 {
   rcWindow fixedw = fixed.window ();
   return match (moving, fixedw, trans);
 }
void rcVisualFunction::measure () virtual
Implements rcBaseMotionPath.
Definition at line 365 of file rc_visualcell.cpp.
References adaptBias(), area(), cardiacMeasure(), circularity(), correspond(), correspondMutualChannel(), cQuality(), direct(), distance(), eDimensions, rcShape::eImage, eMotion, eMotionCenterANDTP, isCardiacCell(), isLabelProtein(), label(), mark(), mCurrentPosition, mMass, mMotionXform, mPOLYs, rcTimingInfo::nextPass(), polygons(), predictedTolerance(), rcTimingInfo::printInfo(), reset(), rfCellNotViable(), rfRealEq(), rkPI, rmAssert, roundRectangle(), sharedKin(), rcBaseMotionPath::step(), rcTimingInfo::touch(), rc2Xform::transf(), rcRectangle< T >::ul(), use4moving(), and vXform().
 {
   step();
   // Invalidate all measurements before we begin
   reset ();
   if (sharedKin()->movingPolygons().size() < 1) return;
   //  sharedKin()->dumpPolys (cerr);
   //@note allow unknown.
   if (rfCellNotViable (*this)) return;
   static const rc2Fvector tinyMove (2.0f, 2.0f);
   // Get the associated Segmented Poly and most recent poly. Use wc as variable
   vector<rcPolygon>::const_iterator pc = polygons().end(); std::advance (pc, -1);
   vector<rcPolygon>::const_iterator vc = sharedKin()->movingPolygons().begin() + label();
   vector<rcPolygon>::const_iterator wc;
   // If we have a reasonable correspondence use it
   // Otherwise use the updated rect from last time
   rcTimingInfo profile (10, sharedKin()->frameCount() + 1);
   profile.nextPass (true);
   if (vc != sharedKin()->movingPolygons().end() && vc->isValid())
     {
       // We do not need this one around
       //@note we use two different ShapeRefs here. For calculating center of mass we use the
       //  the orthogonal window. For shape we use the segmented polygon.
       rcFRect fr;rcIRect ir;
       vc->orthogonalEnclosingRect(fr);
       ir = roundRectangle (fr);
       rcWindow frame (use4moving(), ir);
       rcShapeRef frameRef = boost::shared_ptr<rcShape> (new rcShape (frame));
       rc2Fvector dD = frameRef->centerOfmass (rcShape::eImage);
       //@note this is poorely placed here. Change.
       mMass = (float) frameRef->mass ();
       dD += rc2Fvector (fr.ul());
       profile.touch (1);
       if (!isCardiacCell () && !isLabelProtein ())
     {
       // @note: if we have motion vectors, compute transformation
       if (vXform (eMotionCenterANDTP, mMotionXform))
         {
           dD = mMotionXform.transf ();
         }
       rcFPair tolerance = predictedTolerance (dD);
       correspond (dD, tolerance);
       mPOLYs.push_back (*vc);
       mark (eMotion);
       mark (eDimensions);
     }
       else if (isCardiacCell ())
     {
       cardiacMeasure (vc);
     }
       else if (isLabelProtein ())
     {
       // @note
       // dD is com of the most correponding region.
       // mCurrentPosition is known position before this measure.
       // Immediately after division, there might not be separate
       // regions corresponding to each child.
       // So a gaussian model is used to track the daughters until
       // they form a isomorphic (one to one) correspondence with a region.
       // The first time they do, daughters are updated to the
       // region and  the cell is moved  to the com  of the region.
       float distance = dD.distance (mCurrentPosition);
       float radius = sqrt (area() / rkPI) * 1.5f;
       if (rfRealEq (cQuality (), 1.0f, 0.001f) &&
           rfRealEq (circularity (), (float) vc->circularity(), 0.067f) &&
           distance < radius)
         {
           direct (dD);
           // @note we are accepting the perfect correspondence
           wc = vc;
         }
       else
         {
           dD = rc2Fvector (adaptBias (), adaptBias ());
           rcFPair tolerance = predictedTolerance (dD);
           profile.touch (0);
           if (sharedKin ()->channelAvailable ())
         correspondMutualChannel (dD, tolerance);
           else
         correspond (dD, tolerance);
           // @note we are moving the last poly forward
     //          pc->transform (instantTransformation ());
           wc = pc;
           profile.touch(1);
         }
       mPOLYs.push_back (*wc);
       mark (eMotion);
       mark (eDimensions);
     }
       else
     {
       rmAssert (0);
     }
     }
   vector<std::string> lables;
   lables.push_back (std::string ("Correspondence"));
   profile.printInfo (2, lables);
 }
float rcVisualFunction::minSqDisplacement () const inline
Definition at line 495 of file rc_visualcell.h.
References mRdiffuse, and rcBaseMotionPath::steps().
   {
     if (steps())
       return mRdiffuse;
   }
const rcIRect& rcVisualFunction::minTemporalEnclosingRect () const inline
Definition at line 621 of file rc_visualcell.h.
References mMinTemporalEncRect.
 {return mMinTemporalEncRect; }
const rcIRect& rcVisualFunction::minTemporalIntersectingRect () const inline
Definition at line 628 of file rc_visualcell.h.
References mMinTemporalIntRect.
 {return mMinTemporalIntRect; }
rc2Fvector& rcVisualFunction::motionCenter () inline private
Definition at line 743 of file rc_visualcell.h.
References mMotionCtr.
   {
     return mMotionCtr;
   }
const rcFRect& rcVisualFunction::moving () const inline
Definition at line 665 of file rc_visualcell.h.
References mMoving.
Referenced by cardiacMeasure(), correspond(), correspondMutualChannel(), direct(), grow(), and update().
   {
     return mMoving;
   }
void rcVisualFunction::moving (const rcFRect & fm) inline
Definition at line 670 of file rc_visualcell.h.
References mMoving.
   {
     mMoving = fm;
   }
bool rcVisualFunction::operator< (const rcVisualFunction & rhs) const inline
Definition at line 721 of file rc_visualcell.h.
References mId.
 { return mId < rhs.mId; };
bool rcVisualFunction::operator== (const rcVisualFunction & rhs) const inline
Definition at line 722 of file rc_visualcell.h.
References mId.
 { return mId == rhs.mId; };
rcOrganismInfo::OrganismType rcVisualFunction::organism () const inline
Definition at line 194 of file rc_visualcell.h.
References mOtype.
Referenced by grow(), isCardiacCell(), isLabelProtein(), and rcVisualFunction().
   { return mOtype;}
rcOrganismInfo::OrganismName rcVisualFunction::organismName () const inline
Definition at line 197 of file rc_visualcell.h.
References mOname.
Referenced by grow(), isCardiacCell(), isLabelProtein(), and rcVisualFunction().
   { return mOname;}
float rcVisualFunction::pacingFrequency () const inline
Definition at line 481 of file rc_visualcell.h.
References ePacingInfo, framesPerPeriod(), gNotAvailable, have(), mFramesPerPeriod, and sharedKin().
   {
     if (have (ePacingInfo) && mFramesPerPeriod >= 0.0)
       return sharedKin()->averageFramesPerSecond () / framesPerPeriod();
     else
       return gNotAvailable;
   }
uint32 rcVisualFunction::parentId () const inline
Definition at line 181 of file rc_visualcell.h.
References mParentId.
Referenced by operator<<().
 {return mParentId; }
const deque<rcPair<rcRadian> >& rcVisualFunction::peakAngles () const inline
Definition at line 681 of file rc_visualcell.h.
References mPeakAngles.
   {
     return mPeakAngles;
   }
float rcVisualFunction::perimeter () const inline
Definition at line 266 of file rc_visualcell.h.
References mPerimeter, rc2Xform::scale(), sharedKin(), and rcKinetoscope::xform().
Referenced by operator<<().
   {
     const rc2Xform& xform = sharedKin()->xform();
     return mPerimeter * xform.scale ();
   }
float rcVisualFunction::persistence () const
Definition at line 263 of file rc_visualcell.cpp.
References mCosSums, rmMax, and rcBaseMotionPath::steps().
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
 {
   double p = mCosSums / ((float) (rmMax (1, steps())));
   return (p);
 }
const vector<rcPolygon>& rcVisualFunction::polygons () const inline
Definition at line 607 of file rc_visualcell.h.
References mPOLYs.
Referenced by intersectSet(), and measure().
 {return mPOLYs; }
void rcVisualFunction::populationMigration () private
Definition at line 204 of file rc_visualcell.cpp.
References clear(), rc2dVector< T >::distance(), eDispersion, id(), mark(), mMotionPattern, position(), rfRealEq(), scale(), sharedKin(), velocity(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by reconcile().
 {
   clear (eDispersion);
   if (sharedKin()->mFunctionMap.size() < 2) return;
   // else measure population migration
   list<rcVisualFunction>::const_iterator cell;
   vector<float> cellDiffusion;
   vector<float> distances;
   distances.reserve (sharedKin()->mFunctionMap.size() - 1);
   cellDiffusion.reserve (sharedKin()->mFunctionMap.size() - 1);
   for(cell = sharedKin()->mFunctionMap.begin(); cell != sharedKin()->mFunctionMap.end(); cell++)
     {
       // Skip me
       if (cell->id() == id()) continue;
       // Vector from me to another cell
       rc2Dvector c2c (position().x() - cell->position().x(),
               position().y() - cell->position().y());
       // Distance from me to another cell
       float f = position().distance (cell->position());
       distances.push_back (f);
       // My velocity towards the other cell (dot product)
       rc2Dvector vd (velocity().x(), velocity().y());
       cellDiffusion.push_back (c2c * vd);
     }
   // Now get min and max distances
   vector<float>::const_iterator mind = min_element (distances.begin(),
                             distances.end());
   vector<float>::const_iterator maxd = max_element (distances.begin(),
                             distances.end());
   // If all cells are attached to me, we are undetermined
   if (rfRealEq (*maxd, 0.0f)) return;
   // Find min and max distances; if there is no range, pick max
   float scale (*maxd - *mind);
   if (rfRealEq (scale, 0.0f)) scale = *maxd;
   // Sum persistence towards me or away from me scale pro closest to me.
   // Use a linear map to use distance
   float dispersion (0.0f);
   for (uint32 i = 0; i < distances.size(); i++)
     dispersion += (distances[i] * cellDiffusion[i]) / scale;
   mMotionPattern = dispersion;
   mark (eDispersion);
 }
const rc2Fvector& rcVisualFunction::position () const inline
Definition at line 317 of file rc_visualcell.h.
References mCurrentPosition.
Referenced by operator<<(), populationMigration(), and rcCellWriterGroup::writeValues().
   {
     //@todo figure something cleaner about this
     //    if (steps () && !have (eMotion) && !isState(eIsDivided))
     //      rmExceptionMacro(<<"Does not have motion info");
     return mCurrentPosition;
   }
const rcFPair rcVisualFunction::predictedTolerance (rc2Fvector & dD) const inline private
Definition at line 144 of file rc_visualcell.cpp.
References adaptBias(), cQuality(), rcBaseMotionPath::isAtStep(), mRectSnaps, quality, rmABS, rmMax, rcPair< T >::x(), rc2dVector< T >::x(), rcPair< T >::y(), and rc2dVector< T >::y().
Referenced by measure().
 {
   float quality = cQuality ();
  // quality = (quality == gNotAvailable) ? 0.5f : quality;
   float ab = adaptBias ();
   const rcFPair minTolerance (ab / mRectSnaps.back().width(), ab / mRectSnaps.back().height());
   // Do not use below 0.5 quality (unlikely from correspondence)
   float adapt rmMax ((1.0f / quality ), 1.0f);
   rcFPair tolerance = isAtStep (1) ? minTolerance :  rcFPair (adapt, adapt) * minTolerance;
   tolerance.x() = rmMax (rmABS(dD.x()) / mRectSnaps.back().width(), tolerance.x());
   tolerance.y() = rmMax (rmABS(dD.y()) / mRectSnaps.back().height(), tolerance.y());
   return minTolerance;
 }
void rcVisualFunction::reconcile () virtual
R e c o n c i l e
Implements rcBaseMotionPath.
Definition at line 165 of file rc_visualcell.cpp.
References beatProcess(), clear(), eDimensions, eDispersion, eIsDivided, eIsDividing, eIsJustDivided, rcKinetoscope::eLineage, have(), isCardiacCell(), isState(), mDividingTicks, mExpDividedFrameIndex, mMotionPattern, populationMigration(), rfCellNotViable(), setState(), and sharedKin().
 {
     mMotionPattern = 0.0; // gInValidDispersion;
   clear (eDispersion);
   if (rfCellNotViable (*this)) return;
   // Beat Processing For CardioMyocytes
   // starts after phase # of frames
   if (isCardiacCell () && have (eDimensions))
     {
       beatProcess ();
     }
   else if (sharedKin()->have (rcKinetoscope::eLineage))
     {
      if (isState(eIsDividing))
        {
      bool divided = isState(eIsJustDivided);
      setState (eIsDivided, divided);
      setState (eIsDividing, !divided);
      if (!divided)
        {
          mDividingTicks--;
          setState (eIsDividing, mDividingTicks > 0);
        }
      if(divided)
        {
          mExpDividedFrameIndex = sharedKin()->moving().frameBuf()->frameIndex();
        }
        }
     }
   else
     {
       populationMigration ();
     }
 }
const deque<rcIRect>& rcVisualFunction::rectSearches () const inline
Definition at line 600 of file rc_visualcell.h.
References mSearchRects.
 {return mSearchRects; }
const deque<rcFRect>& rcVisualFunction::rectSnaps () const inline
Definition at line 598 of file rc_visualcell.h.
References mRectSnaps.
 {return mRectSnaps; }
const deque<rcFRect>& rcVisualFunction::rectTemplates () const inline
Definition at line 599 of file rc_visualcell.h.
References mTemplateRects.
 {return mTemplateRects; }
void rcVisualFunction::reset ()
Definition at line 381 of file rc_visualfunction.cpp.
References mHaves.
Referenced by measure().
 {
   mHaves.reset ();
 }
float rcVisualFunction::rmsQuality () const inline
Definition at line 291 of file rc_visualcell.h.
References gNotAvailable, mSumQuality, rcStatistics::n(), and rcStatistics::rms().
Referenced by rcCellWriterGroup::writeValues().
   {
     if (mSumQuality.n())
       return mSumQuality.rms ();
     else
       return gNotAvailable;
   }
template<class P > rcIRect rcVisualFunction::roundRectangle (const rcRectangle< P > & fr, bool makeVecMultiple = false) const
Definition at line 882 of file rc_visualcell.h.
References rcRectangle< T >::height(), rcRectangle< T >::origin(), rfRound(), sDummy(), rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by cardiacMeasure(), cardiacUpdate(), correspond(), correspondMutualChannel(), measure(), and updateRects().
 {
   static const int32 sDummy (0);
   rcIPair ul (rfRound (fr.origin().x(), sDummy),
           rfRound (fr.origin().y(), sDummy));
   rcIPair lr (rfRound (fr.origin().x() + fr.width(), sDummy),
           rfRound (fr.origin().y() + fr.height(), sDummy));
   if (!makeVecMultiple)
     return rcIRect (ul, lr);
   rcIRect ir (ul, lr);
   int32 p16 = ir.width() % 16;
   p16 = p16 ? 16 - p16 : p16; // how much to grow
   return rcIRect (ir.ul().x(), ir.ul().y(), ir.width() + p16, ir.height());
 }
const rcFPair rcVisualFunction::scale () const inline
Definition at line 370 of file rc_visualcell.h.
References rc2Xform::matrix(), mXform, rcMatrix_2d::xScale(), and rcMatrix_2d::yScale().
Referenced by populationMigration(), and rcCellWriterGroup::writeValues().
   {
     return rcFPair (100.0f * mXform.matrix().xScale(),
             100.0f * mXform.matrix().yScale());
   }
bool rcVisualFunction::setState (const State st) inline
Definition at line 156 of file rc_visualcell.h.
References isState(), and mState.
Referenced by cardiacMeasure(), cardiacUpdate(), correspond(), correspondMutualChannel(), framesPerPeriod(), grow(), initializeSimilarator(), rcVisualFunction(), reconcile(), and update().
 {mState.set(st); return isState (st); }
bool rcVisualFunction::setState (const State st, const bool b) inline
Definition at line 157 of file rc_visualcell.h.
References isState(), and mState.
 {mState[st]=b; return isState (st); }
const rcShapeRef& rcVisualFunction::shape () const inline
Definition at line 634 of file rc_visualcell.h.
References mShapeRef.
 {return mShapeRef; }
const boost::shared_ptr<rcKinetoscope> rcVisualFunction::sharedKin () const inline
Definition at line 655 of file rc_visualcell.h.
References mKine.
Referenced by adaptBias(), correspondMutualChannel(), dimensions(), direct(), distance(), grow(), initializeSimilarator(), instantVelocity(), intersectSet(), isIsoMorphic(), measure(), pacingFrequency(), perimeter(), populationMigration(), rcVisualFunction(), reconcile(), speed(), time(), update(), updateRects(), use4fixed(), use4moving(), velocity(), and vXform().
   {
     return mKine;
   }
const float rcVisualFunction::shortenning () const inline
Definition at line 376 of file rc_visualcell.h.
References mBeatShortenning.
Referenced by operator<<(), and rcCellWriterGroup::writeValues().
   {
     return mBeatShortenning;
   }
float rcVisualFunction::sideShorteningActual () const private
float rcVisualFunction::sideShorteningEstimate () const private
Definition at line 283 of file rc_visualcardiomyo.cpp.
References framesPerPeriod(), and rcBaseMotionPath::steps().
Referenced by cardiacMeasure().
  {
    float f = fmod ((double) steps(), (double) framesPerPeriod()) / framesPerPeriod();
      f = -4*f*(f - 1); // gEstSideShortening;
    return f;
  }
const vector<float>& rcVisualFunction::similarity () const inline
Definition at line 515 of file rc_visualcell.h.
References mSS.
Referenced by beatProcess().
   {
     return mSS;
   }
const rcFRect& rcVisualFunction::similarityArea () const inline
Definition at line 696 of file rc_visualcell.h.
References mCurrentSimRect.
   {
     return mCurrentSimRect;
   }
const deque<rcCorrelationWindow<uint8> >& rcVisualFunction::snaps () const inline
Definition at line 590 of file rc_visualcell.h.
References mSnaps.
 {return mSnaps; }
float rcVisualFunction::speed () const
Definition at line 422 of file rc_visualfunction.cpp.
References rc2dVector< T >::isNull(), rc2dVector< T >::len(), rc2Xform::mapPoint(), mVt, and sharedKin().
Referenced by operator<<().
 {
   const rc2Xform& xform = sharedKin()->xform();
   rc2Fvector s = xform.mapPoint (mVt);
   if (!s.isNull ()) return s.len ();
 }
const int32 rcVisualFunction::ssWindowSize () const inline private
Definition at line 749 of file rc_visualcell.h.
References mSSwindowSize.
Referenced by computeAcceleration(), and initializeSimilarator().
 {return mSSwindowSize; }
int32 rcVisualFunction::ssWindowSize (int32 ws) private
Definition at line 338 of file rc_visualfunction.cpp.
References mSSwindowSize.
 {
   mSSwindowSize = ws;
   return mSSwindowSize;
 }
int32 rcVisualFunction::startFrameIndex () const inline
Definition at line 526 of file rc_visualcell.h.
References mExpStartFrameIndex.
   {
     return mExpStartFrameIndex;
   }
rcVisualFunction::State rcVisualFunction::state () const
Definition at line 429 of file rc_visualfunction.cpp.
References eIsBeating, eIsDivided, eIsDividing, eIsMoving, eIsOutSide, eIsUnInitialized, eIsUnknown, and isState().
Referenced by rcCellWriterGroup::writeValues().
 {
   if(isState(eIsUnInitialized)) return   eIsUnInitialized;
   if(isState(eIsUnknown)) return   eIsUnknown;
   if(isState(eIsOutSide)) return   eIsOutSide;
   if(isState(eIsBeating)) return   eIsBeating;
   if(isState(eIsMoving)) return   eIsMoving;
   if(isState(eIsDividing)) return   eIsDividing;
   if(isState(eIsDivided)) return   eIsDivided;
 }
const rcStatistics& rcVisualFunction::stats () const inline
Definition at line 708 of file rc_visualcell.h.
References mSumQuality.
   {
     return mSumQuality;
   }
float rcVisualFunction::time () const inline
Definition at line 228 of file rc_visualcell.h.
References sharedKin().
Referenced by age().
   {
     return sharedKin()->elapsedTime();
   }
const rc2Fvector rcVisualFunction::translation () const inline
Definition at line 364 of file rc_visualcell.h.
References mXform, rc2Xform::trans(), and rc2dVector< T >::x().
   {
     return rc2Fvector ((float) mXform.trans().x(),
                (float) mXform.trans().x());
   }
void rcVisualFunction::update () virtual
Implements rcBaseMotionPath.
Definition at line 490 of file rc_visualcell.cpp.
References acceleration(), age(), rcBaseMotionPath::anchor(), rc2dVector< T >::angle(), rcPolygon::area(), rcPolygon::circularity(), computeAcceleration(), rcRectangle< T >::contains(), cos(), rcBaseMotionPath::dob(), eDimensions, eDistance, eGeometry, eHasSimilarator, eIsDividing, eIsMoving, rcKinetoscope::eLineage, rcPolygon::ellipseRatio(), eMotion, endl(), ePersistence, eSpeed, eVelocity, have(), rcBaseMotionPath::isAtStep(), isCardiacCell(), isLabelProtein(), rc2dVector< T >::isNull(), isState(), rc2dVector< T >::len(), rc2Xform::mapPoint(), mArea, mark(), mCircularity, mCosSums, mCurrentPosition, mDistance, mDividingTicks, mEllipseRatio, mLastAngle, mNsQ, rcBaseMotionPath::motion(), rcBaseMotionPath::move(), moving(), mPerimeter, mPOLYs, mRdiffuse, mRectSnaps, mV, mVt, mXform, rcPolygon::orthogonalEnclosingRect(), rcPolygon::perimeter(), rfCellNotViable(), rmSquare, setState(), sharedKin(), rcBaseMotionPath::steps(), rc2Xform::transf(), rcBaseMotionPath::travelled(), updateSims(), use4fixed(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   const rcFRect& fpframe = sharedKin()->fpframe ();
   // If we are dead or mostly dead skip
   if (rfCellNotViable (*this)) return;
   if (! have (eDimensions) || ! have (eMotion) ) return;
   // Check on what measure left us with
   rcFRect lastPolyRect, last = mRectSnaps.back();
   if (isState (eHasSimilarator) && ! fpframe.contains (last)) return;
   rcPolygon lastPoly = mPOLYs.back ();
   lastPoly.orthogonalEnclosingRect(lastPolyRect);
   if (! fpframe.contains (lastPolyRect)) return;
  // Set our state based of what we have been through
   setState (eIsMoving, have (eMotion) && have(eDimensions));
   // 1. Update Similarators
   if ((isCardiacCell () || isLabelProtein ()) && (isState (eHasSimilarator)))
     {
       updateSims (use4fixed(), last);
     }
   if (isState (eHasSimilarator) && sharedKin()->have (rcKinetoscope::eLineage))
     {
       computeAcceleration ();
       if (acceleration () > 1.0)
     {
       setState (eIsDividing);
       // @note: do we need a limit of how long we wait for mitosis.
       // Also, how does this interact with checking for apoptosis
       mDividingTicks =10;
     }
     }
   // Update Work on where we are
   // @note: redesign. also expensive polygon copy
   mArea = lastPoly.area ();
   mPerimeter = lastPoly.perimeter ();
   mCircularity = lastPoly.circularity ();
   mEllipseRatio = lastPoly.ellipseRatio ();
   mark (eGeometry);
   // @todo centralize and use time
   mNsQ += rmSquare (steps());
   mRectSnaps.push_back (moving());
   // Get the just moved to pose (translation only for now)
   // @description: This is how much fixed is moved to match moving
   rc2Fvector pos = mXform.transf();
   /*
    * If we have moved in space and time
    * -> make sure we have moved a minimum since last frame
    *    and that we are at least a minim passed dob.
    */
   const double minTimeDelta = sharedKin()->secondsToUnits().invMapPoint (1.0f);
   if (have (eMotion) && sharedKin()->deltaTime () >= minTimeDelta &&
       (sharedKin()->currentTime() - dob()) >= minTimeDelta)
     {
       rcRadian angle (mLastAngle);
       double len (0.0);
       move (pos); // now move to where we are.
       mRdiffuse += (pos.x() * pos.x() + pos.y() * pos.y());
       if (!motion().isNull ())
     {
       len = motion().len ();
       angle = motion().angle();
     }
       mDistance += len;
       // Measure rms of direction changes
       rcRadian bsd = angle - mLastAngle;
       mCosSums += cos (bsd);
       mLastAngle = angle;
       // Velocity is instant velocity
       mV = motion() / age ();
       mVt = travelled() / (float) sharedKin()->elapsedTime();
       // Compute current position
       const rc2Xform& xform = sharedKin()->xform();
       mCurrentPosition = xform.mapPoint (anchor() + travelled ());
       if (!isAtStep (1))
     {
       mLastAngle = angle;
       mark (ePersistence);
     }
       mark (eSpeed);
       mark (eVelocity);
       mark (eDistance);
     }
 #ifdef MINDEBUG
   cout << *this << endl;
 #endif
 }
void rcVisualFunction::updateRects (const rcFRect & fixed, const rcFPair & tol, rcFRect & movingf, rcIRect & moving) const private
Definition at line 603 of file rc_visualcell.cpp.
References rcRectangle< T >::contains(), rcRectangle< T >::height(), rcRectangle< T >::lr(), rmAssert, rmMax, rmMin, roundRectangle(), sharedKin(), rcRectangle< T >::trim(), rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by correspond(), correspondMutualChannel(), dividingProcess(), and updateSims().
 {
    rcFRect fMoving (fixed);
    fMoving = fMoving.trim (-tol.x() * fMoving.width(),
          -tol.x() * fMoving.width(),
          -tol.y() * fMoving.height(),
          -tol.y() * fMoving.height());
    // Adjust to make sure it fits in the processing frame
    // @todo accessor to a float rect for the kinetoscope rects
    // @todo multi-resolution implementation needs to project rects
    // @todo from low res to high res
    const rcIRect& pframe = sharedKin()->iframe ();
    const rcFRect& fpframe = sharedKin()->fpframe ();
    // @todo move only in the direction needed
    rcFPair ud, d;
    ud.x() = rmMax (fpframe.ul().x(), fMoving.ul().x());
    ud.y() = rmMax (fpframe.ul().y(), fMoving.ul().y());
    // @todo adjust size only in the direction needed
    // @note trim is move out the ul and move in the lr
    d.x() = rmMin (fpframe.lr().x(), fMoving.lr().x());
    d.y() = rmMin (fpframe.lr().y(), fMoving.lr().y());
    movingf = rcFRect (ud, d);
    // Check if we are within.
    if (!fpframe.contains (movingf))
      {
     //   setState (eIsOutSide);
        return;
        //       rmExceptionMacro (<<"VisualFunction Correspondence");
      }
    // Produce the rounded one
    moving = roundRectangle (movingf);
    rmAssert (pframe.contains (moving));
 }
bool rcVisualFunction::updateSims (const rcWindow & win, const rcFRect & rect) private
Definition at line 282 of file rc_visualfunction.cpp.
References clear(), rcWindow::copyPixelsFromWindow(), eCoarseSS, eHasSimilarator, rcWindow::height(), rcRectangle< T >::height(), isState(), mark(), mCoarseSimRef, mCurrentSimRect, rmAssert, rmMin, rcWindow::setAllPixels(), rcWindow::size(), rcRectangle< T >::size(), rcBaseMotionPath::steps(), rcRectangle< T >::ul(), updateRects(), rcWindow::width(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by initializeSimilarator(), and update().
 {
   rmAssert (isState (eHasSimilarator));
   clear (eCoarseSS);
   rcFRect pm, fm; rcIRect bm, im;
   static const rcFPair stationary (0.0f, 0.0f);
   static const bool doClip (true);
   // Get the current and estimated rect positons, window the est and setup mask if size has changed
   // Note that the current rect might have been outside itself. We check the inteded size with estiamted
   // window size, and act on clipping done or not.
   // rcFPair ds = rect.size() - mCurrentSimRect.size();
   //rcFPair dp = rect.ul() - mCurrentSimRect.ul();
   updateRects (rect, stationary, fm, im);
   updateRects (mCurrentSimRect, stationary, pm, bm);
   rcWindow tmp (win, im, doClip);
   if (tmp.size () == bm.size() && tmp.size() == im.size() && im.size() == mCoarseSimRef->fillImageSize() &&
       (mCoarseSimRef->update (tmp) || steps() < mCoarseSimRef->matrixSz()))
     {
       mark(eCoarseSS);
       mCurrentSimRect = fm;
       return true;
     }
   else
     {
       rcWindow content (win, im.ul().x(), im.ul().y(), rmMin (tmp.width(), bm.width()),  rmMin (tmp.height(), bm.height()));
       rcWindow extended (bm.width(), bm.height());
       rcWindow masked (bm.width(), bm.height());
       extended.setAllPixels (0);
       masked.setAllPixels (255);
       rcWindow exw (extended, content.width(), content.height());
       rcWindow mw (extended, content.width(), content.height());
       exw.copyPixelsFromWindow (content);
       mw.setAllPixels (0);
       if (extended.size() == bm.size() && masked.size() == bm.size())
     {
       mCoarseSimRef->clearMask ();
       mCoarseSimRef->setMask (masked);
       if (mCoarseSimRef->update (extended) || steps() < mCoarseSimRef->matrixSz())
         {
           mark(eCoarseSS);
           mCurrentSimRect = fm;
           return true;
         }
     }
     }
   // @note for now only one similarator
   return false;
 }
const rcWindow & rcVisualFunction::use4fixed () const private
Definition at line 391 of file rc_visualfunction.cpp.
References sharedKin().
Referenced by cardiacMeasure(), cardiacUpdate(), correspond(), correspondMutualChannel(), dividingProcess(), initializeSimilarator(), and update().
 {
   return sharedKin()->use4fixed();
 }
const rcWindow & rcVisualFunction::use4moving () const private
Definition at line 386 of file rc_visualfunction.cpp.
References sharedKin().
Referenced by correspond(), correspondMutualChannel(), dividingProcess(), and measure().
 {
   return sharedKin()->use4moving();
 }
const rc2Fvector rcVisualFunction::velocity () const inline
Definition at line 331 of file rc_visualcell.h.
References mVt, and sharedKin().
Referenced by operator<<(), populationMigration(), and rcCellWriterGroup::writeValues().
   {
     return sharedKin()->xform().mapPoint (mVt);
   }
bool rcVisualFunction::vXform (DOF dofoptions, rc2Xform & xform) private
Definition at line 286 of file rc_visualcell.cpp.
References rcMotionCenter::add(), rcMotionCenter::center(), eMotion, eMotionCenter, eMotionCenterANDTP, eNone, eScale, rc2Xform::inverse(), mark(), mLabel, mMotionCtr, mRectSnaps, sharedKin(), rcLsFit< T >::solvetp(), and rcLsFit< T >::update().
Referenced by measure().
 {
   // return identity if anything goes wron
   xform = rc2Xform ();
   if (dofoptions == eNone)
     return true;
   int32 i (0);
   rcLsFit<float> lsm;
   rcMotionCenter rcm;
   vector<rc2Fvector>::const_iterator anc = sharedKin()->mVanchor[mLabel].begin();
   vector<rc2Fvector>::const_iterator mov = sharedKin()->mVmoved[mLabel].begin();
   vector<rc2Fvector>::const_iterator ancend = sharedKin()->mVanchor[mLabel].end();
   vector<rc2Fvector>::const_iterator movend = sharedKin()->mVmoved[mLabel].end();
   const rc2Fvector vfix = rc2Fvector (mRectSnaps.back().ul().x(), mRectSnaps.back().ul().y());
   // Motion Vector are wrt kinetoscope frames. translate to the ul of fixed
   for (i = 0; anc != ancend && mov != movend; anc++, mov++, i++)
     {
       rc2Fvector dM = *mov - *anc;
       rc2Fvector af = *anc - vfix;
       rcm.add (af, dM);
       if (dofoptions == eMotionCenterANDTP)
     {
       rc2Fvector mf = *mov - vfix;
       lsm.update (af, mf);
     }
     }
   // Computer Motion Center
   bool mHaveMotionCenter = rcm.center (mMotionCtr);
   if (dofoptions == eMotionCenter)
     {
       if (mHaveMotionCenter)
     {
       mark (eMotion);
       return true;
     }
     }
   // Update lsfit api directly to xform
   bool success;
   rc2Xform xf;
   success = lsm.solvetp (xf);
   success = mHaveMotionCenter && success;
   if (success)
     {
       xform = xf.inverse (); // see note above
       mark (eMotion);
       mark (eScale);
     }
   return success;
 }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcVisualFunction::State & st) friend
Definition at line 505 of file rc_visualfunction.cpp.
 {
   char buf[64];
   rfVisualFunctionStateName(st, buf, 64);
   o << buf;
   return o;
 }
ostream& operator<< (ostream & o, const rcVisualFunction & p) friend
Definition at line 514 of file rc_visualfunction.cpp.
 {
   string s (" States: \n");
   if(p.isState(rcVisualFunction::eIsUnInitialized)) s +=  string ("+eUnInitialized\n");
   if(p.isState(rcVisualFunction::eIsUnknown)) s +=  string ("+eIsUnknown\n");
   if(p.isState(rcVisualFunction::eIsMoving)) s +=  string ("+eIsMoving\n");
   if(p.isState(rcVisualFunction::eIsDirected)) s +=  string ("+eIsDirected\n");
   if(p.isState(rcVisualFunction::eIsJustDivided)) s +=  string ("+eIsJustDivided\n");
   if(p.isState(rcVisualFunction::eIsDividing)) s +=  string ("+eIsDividing\n");
   if(p.isState(rcVisualFunction::eIsDivided)) s +=  string ("+eIsDivided\n");
   if(p.isState(rcVisualFunction::eIsFragmented)) s +=  string ("+eIsFragmented\n");
   if(p.isState(rcVisualFunction::eIsOutSide)) s +=  string ("+eIsOutSide\n");
   if(p.isState(rcVisualFunction::eIsBeating)) s +=  string ("+eIsBeating\n");
   if(p.isState(rcVisualFunction::eIsParent)) s +=  string ("+eIsParent\n");
   if(p.isState(rcVisualFunction::eIsChild)) s +=  string ("+eIsChild\n");
   if(p.isState(rcVisualFunction::eIsRounding)) s +=  string ("+eIsRounding\n");
   if(p.isState(rcVisualFunction::eIsRounded)) s +=  string ("+eIsRounded\n");
   string c (" Type: \n");
   if (p.isCardiacCell()) c += string (" Cardiac \n");
   else if (p.isLabelProtein ()) c += string (" Label Protein \n");
   else c += string (" General \n");
   o << endl;
   o << c << " Id: " << p.id() << " Parent: " << p.parentId() << endl;
   o << s << "[" << p.mSteps << "]: ";
   o << "Trace: " << p.motion() << "Area: " << p.area() << endl;
   o << "Dist:  " << p.distance() << "Persistance  : " << p.persistence() << "CEP : " <<
     p.circularity () <<  "," << p.ellipseRatio() << "," << p.perimeter () << endl;
   o << "Age :" << p.age() << "Anchor: " << p.anchor() << "Position: " << p.position () << endl;
   o << "Velocity: " << p.velocity() << "Speed: " << p.speed() << endl;
   if (p.isCardiacCell ())
     {
       if ( p.have( rcVisualFunction::eContraction ) )
     o << "Length: " << p.dimensions().x();
       if ( p.have( rcVisualFunction::ePacingInfo) )
     o << "Pacing Freq: " << p.contractionFrequency ();
       if ( p.have( rcVisualFunction::eBeatInfo) )
     o << "Shortening: " << p.shortenning();
     }
   if (p.mSS.size())
     {
  //     o << p.mSS << endl;
     }
   return o;
 }
friend class rcKinetoscope friend
Definition at line 52 of file rc_visualcell.h.
Member Data Documentation
const int32 rcVisualFunction::gAffineExtend = 5 static private
Definition at line 58 of file rc_visualcell.h.
const float rcVisualFunction::gEstSideShortening = 0.08f static private
Definition at line 57 of file rc_visualcell.h.
Referenced by rcVisualFunction().
const float rcVisualFunction::gGoodFit = 500.0f static private
Definition at line 59 of file rc_visualcell.h.
Referenced by dividingProcess().
const double rcVisualFunction::gInValidAcceleration =rcDBL_MIN static private
Definition at line 61 of file rc_visualcell.h.
const float rcVisualFunction::gInValidDispersion =rcFLT_MIN static private
Definition at line 54 of file rc_visualcell.h.
const float rcVisualFunction::gInValidOrigin =rcFLT_MIN static private
Definition at line 53 of file rc_visualcell.h.
const float rcVisualFunction::gMinAdaptBias = 2.0f static private
Definition at line 56 of file rc_visualcell.h.
const float rcVisualFunction::gNotAvailable = -1.0f static private
Definition at line 55 of file rc_visualcell.h.
Referenced by contractionFrequency(), framesPerPeriod(), framesPerPeriodPowerOf2(), integralFramesPerPeriod(), pacingFrequency(), and rmsQuality().
rcDPair rcVisualFunction::gNotAvailablePair private
Definition at line 60 of file rc_visualcell.h.
const uint32 rcVisualFunction::gPreHistoric = rcUINT32_MAX static private
Definition at line 62 of file rc_visualcell.h.
float rcVisualFunction::mAcceleration private
Definition at line 811 of file rc_visualcell.h.
Referenced by acceleration(), and computeAcceleration().
vector<float> rcVisualFunction::mAcl private
Definition at line 856 of file rc_visualcell.h.
Referenced by computeAcceleration().
float rcVisualFunction::mActualShortening private
Definition at line 831 of file rc_visualcell.h.
rc2Fvector rcVisualFunction::mAffineSize private
Definition at line 812 of file rc_visualcell.h.
Referenced by beatProcess(), cardiacMeasure(), cardiacUpdate(), dimensions(), and initFunction().
vector<rcAffineRectangle> rcVisualFunction::mAffys private
Definition at line 854 of file rc_visualcell.h.
Referenced by affys(), cardiacMeasure(), and rcVisualFunction().
int32 rcVisualFunction::mAnaphase private
Definition at line 870 of file rc_visualcell.h.
Referenced by dividingProcess(), and initFunction().
float rcVisualFunction::mArea private
Definition at line 811 of file rc_visualcell.h.
Referenced by area(), initFunction(), and update().
deque<double> rcVisualFunction::mBeatAC private
Definition at line 864 of file rc_visualcell.h.
Referenced by beatProcess(), and framesPerPeriod().
float rcVisualFunction::mBeatMedian private
Definition at line 830 of file rc_visualcell.h.
Referenced by beatProcess().
float rcVisualFunction::mBeatNumber private
Definition at line 830 of file rc_visualcell.h.
Referenced by beatProcess(), and initFunction().
float rcVisualFunction::mBeatShortenning private
Definition at line 830 of file rc_visualcell.h.
Referenced by beatProcess(), initFunction(), and shortenning().
rcInfLine rcVisualFunction::mCardiacAxis private
Definition at line 826 of file rc_visualcell.h.
vector<rc2Fvector> rcVisualFunction::mChildren private
Definition at line 858 of file rc_visualcell.h.
Referenced by children(), and dividingProcess().
vector<float> rcVisualFunction::mChildrenL2 private
Definition at line 859 of file rc_visualcell.h.
float rcVisualFunction::mCircularity private
Definition at line 811 of file rc_visualcell.h.
Referenced by circularity(), initFunction(), and update().
rcSimilaratorRef rcVisualFunction::mCoarseSimRef private
Definition at line 840 of file rc_visualcell.h.
Referenced by computeAcceleration(), initializeSimilarator(), and updateSims().
float rcVisualFunction::mContractionFrequency private
Definition at line 830 of file rc_visualcell.h.
Referenced by beatProcess(), and contractionFrequency().
float rcVisualFunction::mCorrespondenceQuality private
Definition at line 811 of file rc_visualcell.h.
Referenced by cQuality().
float rcVisualFunction::mCosSums private
Definition at line 811 of file rc_visualcell.h.
Referenced by initFunction(), persistence(), and update().
rc2Fvector rcVisualFunction::mCurrentPosition private
Definition at line 812 of file rc_visualcell.h.
Referenced by direct(), measure(), position(), rcVisualFunction(), and update().
rcFRect rcVisualFunction::mCurrentSimRect private
Definition at line 815 of file rc_visualcell.h.
Referenced by initializeSimilarator(), similarityArea(), and updateSims().
vector<float> rcVisualFunction::mDimensions private
Definition at line 862 of file rc_visualcell.h.
Referenced by beatProcess().
vector<float> rcVisualFunction::mDimensionTs private
Definition at line 863 of file rc_visualcell.h.
Referenced by beatProcess().
double rcVisualFunction::mDistance private
Definition at line 818 of file rc_visualcell.h.
Referenced by distance(), initFunction(), and update().
int32 rcVisualFunction::mDividingTicks private
Definition at line 870 of file rc_visualcell.h.
Referenced by initFunction(), reconcile(), and update().
rcIRect rcVisualFunction::mDividingWatchWindow private
Definition at line 871 of file rc_visualcell.h.
Referenced by dividingArea(), and dividingProcess().
int32 rcVisualFunction::mEllipseIndex private
Definition at line 809 of file rc_visualcell.h.
Referenced by initFunction().
float rcVisualFunction::mEllipseRatio private
Definition at line 811 of file rc_visualcell.h.
Referenced by ellipseRatio(), initFunction(), and update().
float rcVisualFunction::mEstimatedShortening private
Definition at line 831 of file rc_visualcell.h.
Referenced by rcVisualFunction().
int32 rcVisualFunction::mExpDividedFrameIndex private
Definition at line 823 of file rc_visualcell.h.
Referenced by dividedFrameIndex(), initFunction(), and reconcile().
int32 rcVisualFunction::mExpStartFrameIndex private
Definition at line 822 of file rc_visualcell.h.
Referenced by frameIndex(), and startFrameIndex().
float rcVisualFunction::mFirstBeatLength private
Definition at line 830 of file rc_visualcell.h.
Referenced by beatProcess(), cardiacMeasure(), and cardiacUpdate().
float rcVisualFunction::mFramesPerPeriod private
Definition at line 831 of file rc_visualcell.h.
Referenced by contractionFrequency(), framesPerPeriod(), framesPerPeriodPowerOf2(), integralFramesPerPeriod(), and pacingFrequency().
int32 rcVisualFunction::mFramesPerPeriodPowerOf2 private
Definition at line 810 of file rc_visualcell.h.
Referenced by framesPerPeriod(), and framesPerPeriodPowerOf2().
rcCorrelationWindow<uint8> rcVisualFunction::mGaussModel private
Definition at line 857 of file rc_visualcell.h.
Referenced by createIrradianceModel(), and dividingProcess().
uint32 rcVisualFunction::mGeneration private
Definition at line 808 of file rc_visualcell.h.
Referenced by generation(), and grow().
bitset<eNumHaves> rcVisualFunction::mHaves private
Definition at line 732 of file rc_visualcell.h.
Referenced by clear(), have(), initFunction(), mark(), rcVisualFunction(), and reset().
uint32 rcVisualFunction::mId private
Definition at line 808 of file rc_visualcell.h.
Referenced by grow(), id(), initFunction(), operator<(), and operator==().
int32 rcVisualFunction::mIntegralFramesPerPeriod private
Definition at line 810 of file rc_visualcell.h.
Referenced by framesPerPeriod(), and integralFramesPerPeriod().
deque<rcFPair> rcVisualFunction::mInterpolatedMin private
Definition at line 865 of file rc_visualcell.h.
Referenced by beatProcess(), and interpolatedMin().
rcMathematicalImage rcVisualFunction::mIradModel private
Definition at line 872 of file rc_visualcell.h.
Referenced by createIrradianceModel().
boost::shared_ptr<rcKinetoscope> rcVisualFunction::mKine private
Definition at line 821 of file rc_visualcell.h.
Referenced by sharedKin().
int32 rcVisualFunction::mLabel private
Definition at line 809 of file rc_visualcell.h.
Referenced by initFunction(), label(), and vXform().
rcRadian rcVisualFunction::mLastAngle private
Definition at line 817 of file rc_visualcell.h.
Referenced by initFunction(), and update().
vector<rc2Fvector> rcVisualFunction::mMajorEndPoints private
Definition at line 828 of file rc_visualcell.h.
Referenced by cardiacMeasure(), cardiacUpdate(), initFunction(), majorEndPoints(), and rcVisualFunction().
rcFPair rcVisualFunction::mMajorEnds private
Definition at line 829 of file rc_visualcell.h.
Referenced by cardiacMeasure(), majorEnds(), and rcVisualFunction().
float rcVisualFunction::mMass private
Definition at line 811 of file rc_visualcell.h.
Referenced by mass(), and measure().
rc2Fvector rcVisualFunction::mMidPoint private
Definition at line 827 of file rc_visualcell.h.
Referenced by cardiacMeasure(), cardiacUpdate(), and rcVisualFunction().
rcIRect rcVisualFunction::mMinTemporalEncRect private
Definition at line 813 of file rc_visualcell.h.
Referenced by grow(), and minTemporalEnclosingRect().
rcIRect rcVisualFunction::mMinTemporalIntRect private
Definition at line 813 of file rc_visualcell.h.
Referenced by grow(), and minTemporalIntersectingRect().
rc2Fvector rcVisualFunction::mMotionCtr private
Definition at line 812 of file rc_visualcell.h.
Referenced by cop(), motionCenter(), rcVisualFunction(), and vXform().
float rcVisualFunction::mMotionPattern private
Definition at line 811 of file rc_visualcell.h.
Referenced by directedCellPersistence(), initFunction(), populationMigration(), and reconcile().
rc2Xform rcVisualFunction::mMotionXform private
Definition at line 814 of file rc_visualcell.h.
Referenced by measure().
rcFRect rcVisualFunction::mMoving private
Definition at line 815 of file rc_visualcell.h.
Referenced by moving().
int32 rcVisualFunction::mNsQ private
Definition at line 809 of file rc_visualcell.h.
Referenced by initFunction(), and update().
rcOrganismInfo::OrganismName rcVisualFunction::mOname private
Definition at line 728 of file rc_visualcell.h.
Referenced by info(), isOfOrganismName(), isOfOrganismTypeAndName(), and organismName().
rcOrganismInfo::OrganismType rcVisualFunction::mOtype private
Definition at line 722 of file rc_visualcell.h.
Referenced by info(), isOfOrganismType(), isOfOrganismTypeAndName(), and organism().
uint32 rcVisualFunction::mParentId private
Definition at line 808 of file rc_visualcell.h.
Referenced by grow(), and parentId().
deque<rcPair<rcRadian> > rcVisualFunction::mPeakAngles private
Definition at line 866 of file rc_visualcell.h.
Referenced by beatProcess(), and peakAngles().
float rcVisualFunction::mPerimeter private
Definition at line 811 of file rc_visualcell.h.
Referenced by initFunction(), perimeter(), and update().
vector<rcPolygon> rcVisualFunction::mPOLYs private
Definition at line 853 of file rc_visualcell.h.
Referenced by measure(), polygons(), rcVisualFunction(), and update().
int32 rcVisualFunction::mRad private
Definition at line 809 of file rc_visualcell.h.
Referenced by cardiacMeasure(), cardiacUpdate(), and rcVisualFunction().
float rcVisualFunction::mRdiffuse private
Definition at line 811 of file rc_visualcell.h.
Referenced by initFunction(), minSqDisplacement(), and update().
deque<rcFRect> rcVisualFunction::mRectSnaps private
Definition at line 852 of file rc_visualcell.h.
Referenced by cardiacMeasure(), correspond(), correspondMutualChannel(), createIrradianceModel(), dimensions(), direct(), dividingProcess(), predictedTolerance(), rcVisualFunction(), rectSnaps(), update(), and vXform().
deque<rcIRect> rcVisualFunction::mSearchRects private
Definition at line 847 of file rc_visualcell.h.
Referenced by cardiacMeasure(), and rectSearches().
rcShapeRef rcVisualFunction::mShapeRef private
Definition at line 837 of file rc_visualcell.h.
Referenced by cardiacMeasure(), and shape().
int32 rcVisualFunction::mSize private
Definition at line 809 of file rc_visualcell.h.
Referenced by history(), and initFunction().
deque<rcCorrelationWindow<uint8> > rcVisualFunction::mSnaps private
Definition at line 844 of file rc_visualcell.h.
Referenced by correspondMutualChannel(), and snaps().
vector<vector<double> > rcVisualFunction::mSpace private
Definition at line 834 of file rc_visualcell.h.
vector<float> rcVisualFunction::mSS private
Definition at line 855 of file rc_visualcell.h.
Referenced by computeAcceleration(), operator<<(), and similarity().
int32 rcVisualFunction::mSSwindowSize private
Definition at line 869 of file rc_visualcell.h.
Referenced by ssWindowSize().
bitset<eNumStates> rcVisualFunction::mState private
Definition at line 733 of file rc_visualcell.h.
Referenced by clearState(), initFunction(), isNotState(), isState(), rcVisualFunction(), and setState().
rcStatistics rcVisualFunction::mSumQuality private
Definition at line 816 of file rc_visualcell.h.
Referenced by correspond(), correspondMutualChannel(), direct(), initFunction(), rmsQuality(), and stats().
rcDPair rcVisualFunction::mTemplateOriginEnds private
Definition at line 851 of file rc_visualcell.h.
deque<rc2Fvector> rcVisualFunction::mTemplateOrigins private
Definition at line 848 of file rc_visualcell.h.
Referenced by cardiacMeasure(), and cardiacUpdate().
deque<rc2Fvector> rcVisualFunction::mTemplatePoses private
Definition at line 849 of file rc_visualcell.h.
Referenced by cardiacMeasure(), and majorEndPoses().
deque<rcFRect> rcVisualFunction::mTemplateRects private
Definition at line 846 of file rc_visualcell.h.
Referenced by cardiacMeasure(), cardiacUpdate(), and rectTemplates().
deque<rcCorrelationWindow<uint8> > rcVisualFunction::mTemplates private
Definition at line 845 of file rc_visualcell.h.
Referenced by cardiacMeasure(), and cardiacUpdate().
rc2Fvector rcVisualFunction::mV private
Definition at line 812 of file rc_visualcell.h.
Referenced by cardiacMeasure(), instantVelocity(), and update().
rc2Fvector rcVisualFunction::mVt private
Definition at line 812 of file rc_visualcell.h.
Referenced by speed(), update(), and velocity().
rc2Xform rcVisualFunction::mXform private
Definition at line 814 of file rc_visualcell.h.
Referenced by cardiacMeasure(), correspond(), correspondMutualChannel(), direct(), instantTransformation(), scale(), translation(), and update().
The documentation for this class was generated from the following files:
include/analysis/rc_visualcell.h
src/analysis/code/rc_visualcardiomyo.cpp
src/analysis/code/rc_visualcell.cpp
src/analysis/code/rc_visualdivision.cpp
src/analysis/code/rc_visualfunction.cpp
src/analysis/code/rc_visualinstance.cpp