Visible: rcSignalFold Class Reference
rcSignalFold Class Reference
Signal Recognition Class
#include <include/analysis/rc_signalfold.h>
Public Types
enum unit { eIndex, eLength, eDefault = eIndex }
typedef rcListSample
< rc2Fmeasurement > samples
typedef float binType
typedef
rcListSampleToHistogramGenerator
< samples, binType > histo
Public Member Functions
rcSignalFold ()
Constructor
rcSignalFold ()
Constructor Initializes from a vector of values.
template<class M >
rcSignalFold (vector< M > &)
rcSignalFold (vector< M > &, vector< M > &)
rcSignalFold (deque< M > &)
rcSignalFold (deque< M > &, deque< M > &)
double period (unit) const
periodicity Returns periodicity of the signal in two forms: one is fraction of the signal length ("duration"), and length or duration of the period
double periodicity (unit) const
double phase (unit) const
phase Returns phase of the periodic signal in length
Private Member Functions
void size (uint32)
Private Attributes
samples::Pointer mSamplesPtr
Detailed Description
Signal Recognition Class
Exceptions
exception when not initialized
Definition at line 27 of file rc_signalfold.h.
Member Typedef Documentation
typedef float rcSignalFold::binType
Definition at line 32 of file rc_signalfold.h.
typedef rcListSampleToHistogramGenerator< samples, binType> rcSignalFold::histo
Definition at line 33 of file rc_signalfold.h.
typedef rcListSample<rc2Fmeasurement> rcSignalFold::samples
Definition at line 31 of file rc_signalfold.h.
Member Enumeration Documentation
enum rcSignalFold::unit
Enumerator
eIndex
eLength
eDefault
Definition at line 35 of file rc_signalfold.h.
   {
     eIndex,
     eLength,
     eDefault = eIndex
   };
Constructor & Destructor Documentation
rcSignalFold::rcSignalFold ()
Constructor
rcSignalFold::rcSignalFold ()
Constructor Initializes from a vector of values.
Default "x-axis" is array indices. : The 2nd form supplies "x-axis" of time stamps, etc.
template<class M > rcSignalFold::rcSignalFold (vector< M > & signal)
Definition at line 87 of file rc_signalfold.h.
References mSamplesPtr, rmAssert, and size().
 {
   rmAssert (signal.size());
   size (signal.size());
   for (rcUInt32 i = 0; i < signal.size(); i++)
     {
       rc2Fmeasurement mv;
       mv[0] = (float) i; mv[1] = (float) signal[i];
       mSamplesPtr->PushBack (mv);
     }
 }
rcSignalFold::rcSignalFold (vector< M > & signal, vector< M > & stamp)
Definition at line 115 of file rc_signalfold.h.
References mSamplesPtr, rmAssert, and size().
 {
   rmAssert (signal.size());
   rmAssert (signal.size() == stamp.size());
   size (signal.size());
   for (rcUInt32 i = 0; i < signal.size(); i++)
     {
       rc2Fmeasurement mv;
       mv[0] = (float) stamp[i]; mv[1] = (float) signal[i];
       mSamplesPtr->PushBack (mv);
     }
 }
rcSignalFold::rcSignalFold (deque< M > & signal)
Definition at line 101 of file rc_signalfold.h.
References mSamplesPtr, rmAssert, and size().
 {
   rmAssert (signal.size());
   size (signal.size());
   for (rcUInt32 i = 0; i < signal.size(); i++)
     {
       rc2Fmeasurement mv;
       mv[0] = (float) i; mv[1] = (float) signal[i];
       mSamplesPtr->PushBack (mv);
     }
 }
rcSignalFold::rcSignalFold (deque< M > & signal, deque< M > & stamp)
Definition at line 130 of file rc_signalfold.h.
References mSamplesPtr, rmAssert, and size().
 {
   rmAssert (signal.size());
   rmAssert (signal.size() == stamp.size());
   size (signal.size());
   for (rcUInt32 i = 0; i < signal.size(); i++)
     {
       rc2Fmeasurement mv;
       mv[0] = (float) stamp[i]; mv[1] = (float) signal[i];
       mSamplesPtr->PushBack (mv);
     }
 }
Member Function Documentation
double rcSignalFold::period (unit) const
periodicity Returns periodicity of the signal in two forms: one is fraction of the signal length ("duration"), and length or duration of the period
double rcSignalFold::periodicity (unit) const
double rcSignalFold::phase (unit) const
phase Returns phase of the periodic signal in length
rcSignalFold::size (uint32) private
Definition at line 80 of file rc_signalfold.h.
References mSamplesPtr.
Referenced by rcSignalFold().
 {
   mSamplesPtr = samples::New ();
   mSamplesPtr->Resize (sz);
 }
Member Data Documentation
samples::Pointer rcSignalFold::mSamplesPtr private
Definition at line 76 of file rc_signalfold.h.
Referenced by rcSignalFold(), and size().
The documentation for this class was generated from the following file:
include/analysis/rc_signalfold.h