Visible: rcEngineProgress Class Reference
rcEngineProgress Class Reference
#include <include/visiCore/rc_engineimplbase.h>
Public Member Functions
rcEngineProgress (rcEngine *engine, rcEngineObserver *observer, const std::string &message)
rcEngineProgress (rcEngine *engine, rcEngineObserver *observer, const std::string &message, const rcTimestamp &updateInterval)
virtual ~rcEngineProgress ()
virtual bool progress (uint32 percentComplete)
virtual bool progress (double percentComplete)
Public Member Functions inherited from rcProgressIndicator
virtual ~rcProgressIndicator ()
Private Attributes
rcEngine * mEngine
rcEngineObserver * mObserver
const std::string mFormatMessage
char mMessageBuf [1024]
rcTimestamp mUpdateInterval
rcTimestamp mLastUpdate
Detailed Description
Definition at line 87 of file rc_engineimplbase.h.
Constructor & Destructor Documentation
rcEngineProgress::rcEngineProgress (rcEngine * engine, rcEngineObserver * observer, const std::string & message)
Definition at line 72 of file rc_engineimplbase.cpp.
References mEngine, mFormatMessage, mMessageBuf, and rmAssert.
                                                                :
         mEngine( engine ), mObserver( observer ), mFormatMessage( message ),
         mUpdateInterval( cZeroTime ), // Update with every call
         mLastUpdate( cZeroTime )
 {
     rmAssert( mEngine );
     rmAssert( mFormatMessage.size() );
     rmAssert( mFormatMessage.size() < sizeof( mMessageBuf ) );
}
rcEngineProgress::rcEngineProgress (rcEngine * engine, rcEngineObserver * observer, const std::string & message, const rcTimestamp & updateInterval)
Definition at line 85 of file rc_engineimplbase.cpp.
References mEngine, mFormatMessage, mMessageBuf, and rmAssert.
                                                                         :
         mEngine( engine ), mObserver( observer ), mFormatMessage( message ),
         mUpdateInterval( updateInterval ), // Minimum time between updates
         mLastUpdate( cZeroTime )
 {
     rmAssert( mEngine );
     rmAssert( mFormatMessage.size() );
     rmAssert( mFormatMessage.size() < sizeof( mMessageBuf ) );
}
rcEngineProgress::~rcEngineProgress () virtual
Definition at line 101 of file rc_engineimplbase.cpp.
 {
 }
Member Function Documentation
bool rcEngineProgress::progress (uint32 percentComplete) virtual
Implements rcProgressIndicator.
Definition at line 106 of file rc_engineimplbase.cpp.
Referenced by rcEngineImpl::entropyTracker(), rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::modelTracker(), and rcEngineImpl::muscleTracker().
 {
     return progress( static_cast<double>(percentComplete) );
 }
bool rcEngineProgress::progress (double percentComplete) virtual
Implements rcProgressIndicator.
Definition at line 112 of file rc_engineimplbase.cpp.
References cZeroTime, eEngineShuttingDown, eEngineStopped, rcEngine::getElapsedTime(), rcEngine::getState(), mEngine, mFormatMessage, mLastUpdate, mMessageBuf, mObserver, mUpdateInterval, rcEngineObserver::notifyStatus(), rcEngineObserver::notifyTime(), rcTimestamp::now(), and rmDim.
 {
     bool ret = true;
     if ( mEngine ) {
         if ( mObserver ) {
             rcTimestamp now = rcTimestamp::now();
             // If interval is zero, update with every call
             // Otherwise update after mUpdateInterval seconds have passd since last update
             if ( mUpdateInterval == cZeroTime ||
                  ( (now - mLastUpdate) > mUpdateInterval ) ) {
                 mLastUpdate = now;
                 snprintf( mMessageBuf, rmDim( mMessageBuf ), mFormatMessage.c_str(), percentComplete );
                 // Update status bar
                 mObserver->notifyStatus( mMessageBuf );
                 // Update elapsed time to refresh display
                 mObserver->notifyTime( mEngine->getElapsedTime() );
             }
         }
         if ( mEngine->getState() == eEngineShuttingDown ||
              mEngine->getState() == eEngineStopped )
             ret = true; // Abort analysis
         else
             ret = false;
     }
     return ret;
 }
Member Data Documentation
rcEngine* rcEngineProgress::mEngine private
Definition at line 112 of file rc_engineimplbase.h.
Referenced by progress(), and rcEngineProgress().
const std::string rcEngineProgress::mFormatMessage private
Definition at line 114 of file rc_engineimplbase.h.
Referenced by progress(), and rcEngineProgress().
rcTimestamp rcEngineProgress::mLastUpdate private
Definition at line 117 of file rc_engineimplbase.h.
Referenced by progress().
char rcEngineProgress::mMessageBuf[1024] private
Definition at line 115 of file rc_engineimplbase.h.
Referenced by progress(), and rcEngineProgress().
rcEngineObserver* rcEngineProgress::mObserver private
Definition at line 113 of file rc_engineimplbase.h.
Referenced by progress().
rcTimestamp rcEngineProgress::mUpdateInterval private
Definition at line 116 of file rc_engineimplbase.h.
Referenced by progress().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplbase.h
src/visible/src/rc_engineimplbase.cpp