Visible: general_exception Class Reference
general_exception Class Reference
#include <include/util/rc_exception.h>
Public Types
typedef std::exception Superclass
Public Member Functions
general_exception (const std::string &msg) throw ()
general_exception (const char *file="Unknown", unsigned int lineNumber=0, const char *desc="None", const char *loc="Unknown")
general_exception (const std::string &file, unsigned int lineNumber, const std::string &desc="None", const std::string &loc="Unknown")
general_exception (const general_exception &orig)
virtual ~general_exception () throw ()
general_exception & operator= (const general_exception &orig)
virtual bool operator== (const general_exception &orig)
virtual void SetLocation (const std::string &s)
virtual void SetDescription (const std::string &s)
virtual void SetLocation (const char *s)
virtual void SetDescription (const char *s)
virtual const char * GetLocation () const
virtual const char * GetDescription () const
virtual const char * GetFile () const
virtual unsigned int GetLine () const
virtual const char * what () const throw ()
Private Attributes
std::string _location
std::string _description
std::string _file
unsigned int _line
Detailed Description
Definition at line 19 of file rc_exception.h.
Member Typedef Documentation
typedef std::exception general_exception::Superclass
Definition at line 22 of file rc_exception.h.
Constructor & Destructor Documentation
general_exception::general_exception (const std::string & msg) throw () inline
Definition at line 24 of file rc_exception.h.
                                                       :
     _location (""), _file (__FILE__), _line (__LINE__), _description( msg )
{ }
general_exception::general_exception (const char * file = "Unknown", unsigned int lineNumber = 0, const char * desc = "None", const char * loc = "Unknown") inline
Definition at line 28 of file rc_exception.h.
                                                                           : _location (loc), _description (desc), _file (file), _line (lineNumber) {}
general_exception::general_exception (const std::string & file, unsigned int lineNumber, const std::string & desc = "None", const std::string & loc = "Unknown") inline
Definition at line 31 of file rc_exception.h.
References endl().
                                                                             : std::exception (), _location (loc), _description (desc), _file (file), _line (lineNumber)
     {
         std::cerr << file << lineNumber << std::endl;
     };
general_exception::general_exception (const general_exception & orig) inline
Definition at line 38 of file rc_exception.h.
References _location.
                                                       : _location (orig._location),_description (orig._description), _file (orig._file), _line (orig._line)
     {
         _location    = orig._location;
     }
virtual general_exception::~general_exception () throw () inline virtual
Virtual destructor needed for subclasses. Has to have empty throw().
Definition at line 45 of file rc_exception.h.
 {}
Member Function Documentation
virtual const char* general_exception::GetDescription () const inline virtual
Definition at line 87 of file rc_exception.h.
     { return _description.c_str(); }
virtual const char* general_exception::GetFile () const inline virtual
What file did the exception occur in?
Definition at line 91 of file rc_exception.h.
Referenced by main(), rcKinetoscope::measure(), rcKinetoscope::reconcile(), and rcKinetoscope::update().
     { return _file.c_str(); }
virtual unsigned int general_exception::GetLine () const inline virtual
What line did the exception occur in?
Definition at line 95 of file rc_exception.h.
Referenced by main(), rcKinetoscope::measure(), rcKinetoscope::reconcile(), and rcKinetoscope::update().
     { return _line; }
virtual const char* general_exception::GetLocation () const inline virtual
Definition at line 85 of file rc_exception.h.
     { return _location.c_str();    }
general_exception& general_exception::operator= (const general_exception & orig) inline
Assignment operator.
Definition at line 48 of file rc_exception.h.
References _description, _file, _line, and _location.
     {
         _location    = orig._location;
         _description = orig._description;
         _file = orig._file;
         _line = orig._line;
         return *this;
     }
virtual bool general_exception::operator== (const general_exception & orig) inline virtual
Equivalence operator.
Definition at line 58 of file rc_exception.h.
References _description, _file, _line, and _location.
     {
         if ( _location    == orig._location &&
             _description == orig._description &&
             _file == orig._file &&
             _line == orig._line)
         {
             return true;
         }
         else
         {
             return false;
         }
     }
virtual void general_exception::SetDescription (const std::string & s) inline virtual
Definition at line 79 of file rc_exception.h.
     { _description = s; }
virtual void general_exception::SetDescription (const char * s) inline virtual
Definition at line 83 of file rc_exception.h.
     { _description = s; }
virtual void general_exception::SetLocation (const std::string & s) inline virtual
Methods to get and set the Location and Description fields. The Set methods are overloaded to support both std::string and const char array types. Get methods return const char arrays.
Definition at line 77 of file rc_exception.h.
     { _location = s;    }
virtual void general_exception::SetLocation (const char * s) inline virtual
Definition at line 81 of file rc_exception.h.
     { _location = s;    }
virtual const char* general_exception::what () const throw () inline virtual
Provide std::exception::what() implementation.
Definition at line 99 of file rc_exception.h.
Referenced by rcEngineImpl::analyzeFocusArea(), rcEngineMovieSaver::closeHdlr(), rcEngineImpl::frameInterrupt(), main(), rcKinetoscope::measure(), rcKinetoscope::reconcile(), rcModelDomain::requestClose(), rcModelDomain::requestNew(), rcModelDomain::requestOpen(), rcModelDomain::requestProcess(), rcModelDomain::requestSave(), rcModelDomain::requestStart(), rcModelDomain::requestStop(), rcModelDomain::requestTrackingPause(), rcModelDomain::stopTrackingPause(), threadEntry(), and rcKinetoscope::update().
     { return _description.c_str(); }
Member Data Documentation
std::string general_exception::_description private
Definition at line 105 of file rc_exception.h.
Referenced by operator=(), and operator==().
std::string general_exception::_file private
Definition at line 106 of file rc_exception.h.
Referenced by operator=(), and operator==().
unsigned int general_exception::_line private
Definition at line 107 of file rc_exception.h.
Referenced by operator=(), and operator==().
std::string general_exception::_location private
Exception data. Location of the error and description of the error.
Definition at line 104 of file rc_exception.h.
Referenced by general_exception(), operator=(), and operator==().
The documentation for this class was generated from the following file:
include/util/rc_exception.h