Visible: rcLinGeneratePixel Class Reference
rcLinGeneratePixel Class Reference
#include <include/visual/rc_lin_generators.h>
Public Member Functions
rcLinGeneratePixel ()
virtual ~rcLinGeneratePixel ()
double genPixel (const rcAffineWindow *src, double x, double y)
Public Member Functions inherited from rcGeneratePixel
rcGeneratePixel ()
virtual ~rcGeneratePixel ()
Detailed Description
Definition at line 21 of file rc_lin_generators.h.
Constructor & Destructor Documentation
rcLinGeneratePixel::rcLinGeneratePixel () inline
Definition at line 25 of file rc_lin_generators.h.
 {}
virtual rcLinGeneratePixel::~rcLinGeneratePixel () inline virtual
Definition at line 27 of file rc_lin_generators.h.
 {}
Member Function Documentation
double rcLinGeneratePixel::genPixel (const rcAffineWindow * src, double x, double y) inline virtual
Implements rcGeneratePixel.
Definition at line 29 of file rc_lin_generators.h.
References rcWindow::depth(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcWindow::height(), rcPixelDouble, rmAssert, and rcWindow::width().
   {
     rmAssert(src && (src->depth() <= rcPixelDouble));
     int32 ix((uint32)x), iy((uint32)y);
     double bx = x - ix, by = y - iy;
     double ax = 1.0 - bx, ay = 1.0 - by;
     double p00, p10 = 0.0, p01 = 0.0, p11 = 0.0;
     const bool getXPlus1 = bx != 0.0;
     const bool getYPlus1 = by != 0.0;
     if (getXPlus1)
       rmAssert(ix+1 < src->width());
     else
       rmAssert(ix < src->width());
     if (getYPlus1)
       rmAssert(iy+1 < src->height());
     else
       rmAssert(iy < src->height());
     if (src->depth() == rcPixelDouble) {
       p00 = src->getDoublePixel(ix, iy);
       if (getXPlus1) p10 = src->getDoublePixel(ix+1, iy);
       if (getYPlus1) p01 = src->getDoublePixel(ix, iy+1);
       if (getXPlus1 & getYPlus1) p11 = src->getDoublePixel(ix+1, iy+1);
     }
     else {
       p00 = src->getPixel(ix, iy);
       if (getXPlus1) p10 = src->getPixel(ix+1, iy);
       if (getYPlus1) p01 = src->getPixel(ix, iy+1);
       if (getXPlus1 & getYPlus1) p11 = src->getPixel(ix+1, iy+1);
     }
     double v0 = p00*ax + p10*bx;
     double v1 = p01*ax + p11*bx;
     return v0*ay + v1*by;
   }
The documentation for this class was generated from the following file:
include/visual/rc_lin_generators.h