Visible: rcMovieFileTocExt Class Reference
rcMovieFileTocExt Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileTocExt ()
rcMovieFileTocExt (uint32 size)
bool write (FILE *saveStream, const vector< int64 > &tocTimes) const
void fixEndian (const reByteOrder &fileByteOrder)
const uint32 & count () const
Public Member Functions inherited from rcMovieFileExt
rcMovieFileExt ()
rcMovieFileExt (movieExtensionType t)
rcMovieFileExt (movieExtensionType t, int64 o)
const movieExtensionType & type () const
const int64 & offset () const
bool write (FILE *saveStream) const
void fixEndian (const reByteOrder &fileByteOrder)
Private Attributes
uint32 mCount
Detailed Description
Definition at line 251 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileTocExt::rcMovieFileTocExt ()
Definition at line 269 of file rc_moviefileformat.cpp.
                                      :
         rcMovieFileExt(movieExtensionTOC, sizeof(rcMovieFileTocExt)),
         mCount(0)
 {
}
rcMovieFileTocExt::rcMovieFileTocExt (uint32 size)
Definition at line 275 of file rc_moviefileformat.cpp.
                                                   :
         rcMovieFileExt(movieExtensionTOC, sizeof(rcMovieFileTocExt)+size*sizeof(int64)),
         mCount( size )
 {
}
Member Function Documentation
const uint32& rcMovieFileTocExt::count (void) const inline
Definition at line 264 of file rc_moviefileformat.h.
Referenced by operator<<(), and rcVideoCache::tocLoadFromTOC().
 { return mCount; };
void rcMovieFileTocExt::fixEndian (const reByteOrder & fileByteOrder)
Definition at line 312 of file rc_moviefileformat.cpp.
References ByteSwapN, rcMovieFileExt::fixEndian(), mCount, and rfPlatformByteOrder().
Referenced by rcVideoCache::tocLoadFromTOC(), and write().
 {
     if ( rfPlatformByteOrder() != fileByteOrder )
 {
     rcMovieFileExt::fixEndian (fileByteOrder);
     ByteSwapN (mCount);
 }
 }
bool rcMovieFileTocExt::write (FILE * saveStream, const vector< int64 > & tocTimes) const
Definition at line 283 of file rc_moviefileformat.cpp.
References ByteSwapN, eByteOrderBigEndian, fixEndian(), rfPlatformByteOrder(), and rfPlatformByteOrderMark().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileTocExt *>(this)->fixEndian (rfPlatformByteOrder(rfPlatformByteOrderMark()) );
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("TOC hdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     for (uint32 i = 0; i < tocTimes.size(); i++) {
         int64 timestamp = tocTimes[i];
         if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
             ByteSwapN (timestamp);
         }
         if (fwrite(&timestamp, sizeof(int64), 1, saveStream) != 1) {
             perror("fwrite of TOC timestamp failed");
             if (fclose(saveStream))
                 perror("fclose failed");
             return true;
         }
     }
     return false;
 }
Member Data Documentation
uint32 rcMovieFileTocExt::mCount private
Definition at line 264 of file rc_moviefileformat.h.
Referenced by fixEndian().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp