Visible: rcEllipse Class Reference
rcEllipse Class Reference
#include <include/util/rc_ellipse.h>
Classes
struct rcEllipseNormUnit
Public Member Functions
rcEllipse ()
rcEllipse (const rc2Dvector &c, const rc2Dvector &r, rcRadian o)
bool degenerate () const
const rc2Dvector & center () const
rcEllipseNormUnit unit () const
bool contains (const rc2Dvector &p) const
rcDRect boundingOrthRectangle () const
bool operator== (const rcEllipse &e) const
bool operator!= (const rcEllipse &e) const
Private Attributes
rc2Dvector mCenter
rc2Dvector mRadii
rcRadian mOrient
Detailed Description
Definition at line 35 of file rc_ellipse.h.
Constructor & Destructor Documentation
rcEllipse::rcEllipse () inline
Definition at line 38 of file rc_ellipse.h.
 {}
rcEllipse::rcEllipse (const rc2Dvector & c, const rc2Dvector & r, rcRadian o) inline
Definition at line 39 of file rc_ellipse.h.
     : mCenter (c), mRadii(r), mOrient(o) {}
Member Function Documentation
rcDRect rcEllipse::boundingOrthRectangle () const inline
Definition at line 88 of file rc_ellipse.h.
References center(), cos(), mOrient, mRadii, rmSquare, sin(), rc2dVector< T >::x(), and rc2dVector< T >::y().
   {
     double c, s, x2, y2;
     c = rmSquare (cos (mOrient));
     s = rmSquare (sin (mOrient));
     x2 = rmSquare (mRadii.x());
     y2 = rmSquare (mRadii.y());
     rc2Dvector r (sqrt (y2 * s + x2 * c), sqrt (x2 * s + y2 * c));
     rc2Dvector tl = center() - r;
     rc2Dvector size = r * 2.;
     return rcDRect (tl.x(), tl.y(), size.x(), size.y());
   }
const rc2Dvector& rcEllipse::center () const inline
Definition at line 47 of file rc_ellipse.h.
References mCenter.
Referenced by boundingOrthRectangle(), and contains().
   {
     return mCenter;
   }
bool rcEllipse::contains (const rc2Dvector & p) const inline
Definition at line 81 of file rc_ellipse.h.
References center(), degenerate(), rcEllipse::rcEllipseNormUnit::mCtr, rcEllipse::rcEllipseNormUnit::mUnit, and unit().
   {
     if (degenerate ()) return (p - center()).len() == 0.;
     rcEllipseNormUnit u = unit ();
     return (u.mUnit* (p - u.mCtr)).len() <= 1.;
   }
bool rcEllipse::degenerate () const inline
Definition at line 42 of file rc_ellipse.h.
References mRadii, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by contains(), and unit().
   { return mRadii.x() <= 0.
       || mRadii.y() <= 0.;
   }
bool rcEllipse::operator!= (const rcEllipse & e) const inline
Definition at line 118 of file rc_ellipse.h.
 { return !(*this == e);}
bool rcEllipse::operator== (const rcEllipse & e) const inline
Definition at line 112 of file rc_ellipse.h.
References mCenter, mOrient, and mRadii.
 { return (mCenter == e.mCenter &&
       mRadii == e.mRadii &&
       mOrient == e.mOrient);}
rcEllipseNormUnit rcEllipse::unit () const inline
Definition at line 61 of file rc_ellipse.h.
References cos(), degenerate(), mCenter, mOrient, mRadii, rcRadian::norm(), sin(), tan(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by contains().
   {
     if (degenerate())
       return rcEllipseNormUnit (mCenter, rcMatrix_2d());
     mOrient.norm();
     double sn = sin (mOrient) / mRadii.x();
     double cs = cos (mOrient) / mRadii.x();
     double tg = tan (rcRadian (0.0));
     rcMatrix_2d mm (cs + sn * tg,
           sn - cs * tg,
           -sn / (mRadii.y() / mRadii.x()), // y / x is aspect ratio
           cs / (mRadii.y() / mRadii.x()));
     return rcEllipseNormUnit (mCenter, mm );
   }
Member Data Documentation
rc2Dvector rcEllipse::mCenter private
Definition at line 106 of file rc_ellipse.h.
Referenced by center(), operator==(), and unit().
rcRadian rcEllipse::mOrient private
Definition at line 108 of file rc_ellipse.h.
Referenced by boundingOrthRectangle(), operator==(), and unit().
rc2Dvector rcEllipse::mRadii private
Definition at line 107 of file rc_ellipse.h.
Referenced by boundingOrthRectangle(), degenerate(), operator==(), and unit().
The documentation for this class was generated from the following file:
include/util/rc_ellipse.h