Visible: rcEncryptionEngine Class Reference
rcEncryptionEngine Class Reference
#include <include/util/rc_security.h>
Public Member Functions
rcEncryptionEngine (const rcSecurityKey &key)
std::string encrypt (const std::string &clearText)
std::string decrypt (const std::string &cipherText)
Private Attributes
rcSecurityKey mKey
Detailed Description
Definition at line 104 of file rc_security.h.
Constructor & Destructor Documentation
rcEncryptionEngine::rcEncryptionEngine (const rcSecurityKey & key) inline
Definition at line 107 of file rc_security.h.
 : mKey( key ) { };
Member Function Documentation
std::string rcEncryptionEngine::decrypt (const std::string & cipherText)
Definition at line 190 of file rc_security.cpp.
References rcSecurityKey::binaryKey(), rcSecurityKey::eBinaryKeyLength, encrypt(), rcSecurityKey::eTextKeyLength, mKey, rmAssert, rmDim, and rcSecurityKey::textKey().
Referenced by rcLicenseManager::licenseHostHasValidFormat(), and rcLicenseManager::licenseTimeHasValidFormat().
 {
     rmAssert( cipherText.length() == rcSecurityKey::eTextKeyLength );
     std::string clearText;
     rcLock lock( mDESMutex );
     setkey( mKey.binaryKey().c_str());
     {
         rcSecurityKey binaryTextKey( cipherText );
         char binaryText[rcSecurityKey::eBinaryKeyLength];
         memcpy( binaryText, binaryTextKey.binaryKey().c_str(), rmDim( binaryText ) );
         // Decrypt
         ::encrypt( binaryText, 1);
         clearText = rcSecurityKey::textKey( std::string( binaryText, rmDim( binaryText ) ) );
         rmAssert( clearText.length() == cipherText.length() );
     }
     return clearText;
 }
std::string rcEncryptionEngine::encrypt (const std::string & clearText)
Definition at line 167 of file rc_security.cpp.
References rcSecurityKey::binaryKey(), rcSecurityKey::eBinaryKeyLength, rcSecurityKey::eTextKeyLength, mKey, rmAssert, rmDim, and rcSecurityKey::textKey().
Referenced by decrypt(), rcLicenseManager::licenseHostHasValidFormat(), and rcLicenseManager::licenseTimeHasValidFormat().
 {
     rmAssert( clearText.length() == rcSecurityKey::eTextKeyLength );
     std::string cipherText;
     rcLock lock( mDESMutex );
     setkey( mKey.binaryKey().c_str());
     {
         rcSecurityKey binaryTextKey( clearText );
         char binaryText[rcSecurityKey::eBinaryKeyLength];
         memcpy( binaryText, binaryTextKey.binaryKey().c_str(), rmDim( binaryText ) );
         // Encrypt DARWIN_UNIX03 mods
         ::encrypt( binaryText, 0);
         cipherText = rcSecurityKey::textKey( std::string( binaryText, rmDim( binaryText ) ) );
         rmAssert( clearText.length() == cipherText.length() );
     }
     return cipherText;
 }
Member Data Documentation
rcSecurityKey rcEncryptionEngine::mKey private
Definition at line 115 of file rc_security.h.
Referenced by decrypt(), and encrypt().
The documentation for this class was generated from the following files:
include/util/rc_security.h
src/util/code/rc_security.cpp