Visible: rcExperiment Class Reference
rcExperiment Class Reference abstract
#include <include/visiCore/rc_model.h>
Public Member Functions
virtual ~rcExperiment ()
virtual int getNSettingCategories (void)=0
virtual rcSettingCategory getSettingCategory (int categoryNo)=0
virtual int getNTrackGroups (void)=0
virtual rcTrackGroup * getTrackGroup (int trackGroupNo)=0
virtual rcTimestamp getLength (void)=0
Detailed Description
Definition at line 288 of file rc_model.h.
Constructor & Destructor Documentation
virtual rcExperiment::~rcExperiment () inline virtual
Definition at line 292 of file rc_model.h.
 { };
Member Function Documentation
virtual rcTimestamp rcExperiment::getLength (void) pure virtual
Implemented in rcExperimentImpl.
virtual int rcExperiment::getNSettingCategories (void) pure virtual
Implemented in rcExperimentImpl.
Referenced by rcCSVExporter::exportExperiment(), rcTimeline::keyPressEvent(), rcNativeExporter::produceSettings(), rcMonitor::settingChanged(), and rcSettingPanel::updatePages().
virtual int rcExperiment::getNTrackGroups (void) pure virtual
Implemented in rcExperimentImpl.
Referenced by rcTrackManager::addTracks(), rcTimeline::checkScalarTrackScales(), countDisplayableGroups(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), rcExporter::init(), rcTimeline::paintTimeline(), rcScalarTrackWidget::updateSettings(), rcCellInfoWidget::updateTrackDisplay(), rcScalarTrackWidget::updateTrackDisplay(), and rcTrackPanel::updateTrackGroups().
virtual rcSettingCategory rcExperiment::getSettingCategory (int categoryNo) pure virtual
Implemented in rcExperimentImpl.
Referenced by rcCSVExporter::exportExperiment(), rcTimeline::keyPressEvent(), rcNativeExporter::produceSettings(), rcMonitor::settingChanged(), and rcSettingPanel::updatePages().
virtual rcTrackGroup* rcExperiment::getTrackGroup (int trackGroupNo) pure virtual
Implemented in rcExperimentImpl.
Referenced by rcTrackManager::addTracks(), rcTimeline::checkScalarTrackScales(), countDisplayableGroups(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::enableCellGroup(), rcCSVExporter::exportTracks(), rcImageCanvasGL::findCellPositionTracks(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcTimeline::getEnabledScalarTrack(), rcTimeline::getEnabledVideoTrack(), rcTrackManager::getHiliteTrack(), rcImageCanvasGL::getToolTipText(), rcTrackManager::groupType(), rcTrackManager::hasManageableTracks(), rcExporter::init(), rcScalarTrackWidget::mousePressEvent(), rcTimeline::paintTimeline(), rcNativeExporter::produceGroups(), rcScalarTrackWidget::rcScalarTrackWidget(), rcTrackGroupWidget::rcTrackGroupWidget(), rcTrackGroupWidget::setEnabled(), rcCellInfoWidget::updateTrackDisplay(), and rcScalarTrackWidget::updateTrackDisplay().
The documentation for this class was generated from the following file:
include/visiCore/rc_model.h