Visible: rcSpinboxSettingWidget Class Reference
rcSpinboxSettingWidget Class Reference
#include <include/visUI/rc_spinboxsettingwidget.h>
Public Slots
void valueChanged (void)
void settingChanged (void)
void settingChanged (double multiplier)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcSpinboxSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcSpinboxSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
QSpinBox * _spinboxWidget
rcSpinBox * _rcSpinboxWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 31 of file rc_spinboxsettingwidget.h.
Constructor & Destructor Documentation
rcSpinboxSettingWidget::rcSpinboxSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 80 of file rc_spinboxsettingwidget.cpp.
References _rcSpinboxWidget, _spinboxWidget, rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getXArgs(), rcSpinBoxArgs::maxValue, rcSpinBoxArgs::minValue, rcSettingWidget::mTopLayout, rcSpinBoxArgs::multiplier, settingChanged(), rcSpinBoxArgs::updateMultiplier, valueChanged(), and rcSpinBoxArgs::valueDivisor.
   : rcSettingWidget( parent, setting ), _rcSpinboxWidget(0)
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcSpinBoxArgs* argsP = (rcSpinBoxArgs*)setting.getXArgs();
     if (argsP)
     {
       _spinboxWidget = _rcSpinboxWidget =
         new rcSpinBox(argsP->multiplier, argsP->valueDivisor, argsP->minValue,
               argsP->maxValue, 1 , this , "val" );
       _spinboxWidget->setFixedWidth( 90 );
       if ( !argsP->updateMultiplier )
           _rcSpinboxWidget = 0;
     }
     else
     {
       _spinboxWidget = new QSpinBox( INT_MIN, INT_MAX , 1 , this , "val" );
       _spinboxWidget->setFixedWidth( 70 );
     }
     mTopLayout->addWidget( _spinboxWidget );
     // Dummy label to force left-justified layout
     QLabel* label = new QLabel( "" , this );
     mTopLayout->addWidget( label );
     // use the setting description as a tool tip
     QToolTip::add( this , setting.getDescription() );
     // update the text widget with the current value of the setting.
     settingChanged();
     // route all spinbox's valueChanged signal to our single
     //  'valueChanged' slot
     connect( _spinboxWidget , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( void ) ) );
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     if (_rcSpinboxWidget) {
         // This is an rcSpinBox needing multiplier updates.
         // Hook up its special signal
         connect( domain, SIGNAL( updateMultiplier(double) ),
                  this, SLOT( settingChanged(double) ) );
     }
 }
rcSpinboxSettingWidget::~rcSpinboxSettingWidget ()
Definition at line 130 of file rc_spinboxsettingwidget.cpp.
 {
     QToolTip::remove( this );
 }
Member Function Documentation
void rcSpinboxSettingWidget::settingChanged (void) slot
Definition at line 150 of file rc_spinboxsettingwidget.cpp.
References _spinboxWidget, rcSettingInfo::getValue(), rcSettingWidget::mSetting, and rcSettingWidget::updateWidgetState().
Referenced by rcSpinboxSettingWidget().
 {
     int currentValue = mSetting.getValue();
     _spinboxWidget->setValue( currentValue );
     // Update visibility/editability
     updateWidgetState();
 }
void rcSpinboxSettingWidget::settingChanged (double multiplier) slot
Definition at line 162 of file rc_spinboxsettingwidget.cpp.
References _rcSpinboxWidget, rcSettingInfo::getValue(), rcSettingWidget::mSetting, rmAssert, and rcSpinBox::setMultiplier().
 {
   rmAssert(_rcSpinboxWidget);
   _rcSpinboxWidget->setMultiplier(multiplier);
   /* Do stupid trick to convince QT to display setting value based
    * upon the new multiplier.
    */
   int currentValue = mSetting.getValue();
   int stupidValue = (currentValue) != 1 ? 1 : 2;
   _rcSpinboxWidget->setValue( stupidValue );
   _rcSpinboxWidget->setValue( currentValue );
 }
void rcSpinboxSettingWidget::valueChanged (void) slot
Definition at line 139 of file rc_spinboxsettingwidget.cpp.
References _spinboxWidget, rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcSpinboxSettingWidget().
 {
     int value = _spinboxWidget->value();
     mSetting.setValue( value );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
rcSpinBox* rcSpinboxSettingWidget::_rcSpinboxWidget private
Definition at line 49 of file rc_spinboxsettingwidget.h.
Referenced by rcSpinboxSettingWidget(), and settingChanged().
QSpinBox* rcSpinboxSettingWidget::_spinboxWidget private
Definition at line 48 of file rc_spinboxsettingwidget.h.
Referenced by rcSpinboxSettingWidget(), settingChanged(), and valueChanged().
The documentation for this class was generated from the following files:
include/visUI/rc_spinboxsettingwidget.h
src/visible/qt/rc_spinboxsettingwidget.cpp