Visible: rcRectangle< T > Class Template Reference
rcRectangle< T > Class Template Reference
#include <include/util/rc_rectangle.h>
Public Member Functions
rcRectangle ()
rcRectangle (T w, T h)
rcRectangle (T x, T y, T w, T h)
rcRectangle (const rcPair< T > &v1, const rcPair< T > &v2)
bool operator== (const rcRectangle< T > &) const
bool operator!= (const rcRectangle< T > &rhs) const
const rcPair< T > & origin () const
void origin (const rcPair< T > &)
void translate (const rcPair< T > &)
const rcPair< T > & ul () const
rcPair< T > ur () const
rcPair< T > ll () const
const rcPair< T > & lr () const
rcPair< T > center () const
T width () const
void width (T w)
T height () const
void height (T h)
T area () const
rcPair< T > size () const
void size (const rcPair< T > &)
bool isNull (void) const
bool overlaps (const rcRectangle< T > &, bool touching=false) const
bool contains (const rcRectangle< T > &) const
bool contains (const rcPair< T > &) const
rcRectangle< T > intersect (const rcRectangle< T > &other, bool throwIfNoOverlap=false) const
rcRectangle operator& (const rcRectangle< T > &other) const
rcRectangle< T > & operator&= (const rcRectangle< T > &other)
rcRectangle< T > enclose (const rcRectangle< T > &) const
rcRectangle< T > operator| (const rcRectangle< T > &) const
rcRectangle< T > & operator|= (const rcRectangle< T > &)
rcRectangle< T > trim (T left, T right, T top, T bottom, bool throwIfNegativeSize=false) const
rcRectangle< T > trim (T pad, bool throwIfNegativeSize=false) const
rcRectangle< T > transpose () const
template<>
rcRectangle< uint32 > trim (uint32 left, uint32 right, uint32 top, uint32 bottom, bool throwIfNegativeSize) const
template<>
rcRectangle< uint16 > trim (uint16 left, uint16 right, uint16 top, uint16 bottom, bool throwIfNegativeSize) const
template<>
rcRectangle< uint8 > trim (uint8 left, uint8 right, uint8 top, uint8 bottom, bool throwIfNegativeSize) const
template<>
rcRectangle< uint32 > trim (uint32 left, uint32 right, uint32 top, uint32 bottom, bool throwIfNegativeSize) const
template<>
rcRectangle< uint16 > trim (uint16 left, uint16 right, uint16 top, uint16 bottom, bool throwIfNegativeSize) const
template<>
rcRectangle< uint8 > trim (uint8 left, uint8 right, uint8 top, uint8 bottom, bool throwIfNegativeSize) const
Protected Member Functions
void normalize ()
template<>
void normalize ()
template<>
void normalize ()
template<>
void normalize ()
template<>
void normalize ()
template<>
void normalize ()
template<>
void normalize ()
Protected Attributes
rcPair< T > mUpperLeft
rcPair< T > mLowerRight
Friends
ostream & operator<< (ostream &ous, const rcRectangle< T > &dis)
Detailed Description
template<class T>
class rcRectangle< T >
Definition at line 72 of file rc_rectangle.h.
Constructor & Destructor Documentation
template<class T > rcRectangle< T >::rcRectangle ()
Definition at line 381 of file rc_rectangle.h.
   : mUpperLeft(0, 0), mLowerRight(0, 0)
 {
 }
template<class T> rcRectangle< T >::rcRectangle (T w, T h)
Definition at line 389 of file rc_rectangle.h.
References rcRectangle< T >::normalize().
   : mUpperLeft(0, 0), mLowerRight(w, h)
 {
     normalize();
 }
template<class T> rcRectangle< T >::rcRectangle (T x, T y, T w, T h)
Definition at line 397 of file rc_rectangle.h.
References rcRectangle< T >::normalize().
   : mUpperLeft(x, y), mLowerRight(x+w, y+h)
 {
     normalize();
 }
template<class T> rcRectangle< T >::rcRectangle (const rcPair< T > & v1, const rcPair< T > & v2)
Definition at line 404 of file rc_rectangle.h.
   : mUpperLeft(rmMin(v1.x(),v2.x()), rmMin(v1.y(),v2.y()) ),
     mLowerRight(rmMax(v1.x(),v2.x()), rmMax(v1.y(),v2.y()))
 {
 }
Member Function Documentation
template<class T > T rcRectangle< T >::area () const inline
Definition at line 351 of file rc_rectangle.h.
Referenced by rcMuscleSegmenter::mergePolygons(), and rfGetRects().
 {
   return width() * height();
 }
template<class T> rcPair<T> rcRectangle< T >::center () const inline
Definition at line 143 of file rc_rectangle.h.
 {return ((ul() + lr()) / (T) 2); }
template<class T> bool rcRectangle< T >::contains (const rcRectangle< T > & other) const
Definition at line 506 of file rc_rectangle.h.
References rcRectangle< T >::lr(), and rcRectangle< T >::ul().
Referenced by rcWindow::contains(), rcKinetoscope::frame(), rcKinetoscope::isWithin(), rfGetRects(), rcEngineImpl::start(), rcVisualFunction::update(), rcVisualFunction::updateRects(), rcDbDtParams::validate(), and rcWindow::window().
 {
   return (other.ul().x() >= ul().x()) &&
       (other.lr().x() <= lr().x()) &&
       (other.ul().y() >= ul().y()) &&
       (other.lr().y() <= lr().y());
 }
template<class T> bool rcRectangle< T >::contains (const rcPair< T > & point) const
Definition at line 515 of file rc_rectangle.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return ul().x() <= point.x() && point.x() < lr().x() &&
          ul().y() <= point.y() && point.y() < lr().y();
 }
template<class T> rcRectangle< T > rcRectangle< T >::enclose (const rcRectangle< T > & other) const
Definition at line 555 of file rc_rectangle.h.
References rcRectangle< T >::isNull(), rcRectangle< T >::mLowerRight, rcRectangle< T >::mUpperLeft, rmMax, and rmMin.
 {
   if (other.isNull())
       return *this;
   if (isNull())
       return other;
   rcPair<T> tempMin(rmMin(mUpperLeft.x(),other.mUpperLeft.x()),
                   rmMin(mUpperLeft.y(),other.mUpperLeft.y()));
   rcPair<T> tempMax(rmMax(mLowerRight.x(),other.mLowerRight.x()),
                   rmMax(mLowerRight.y(),other.mLowerRight.y()));
   return rcRectangle<T>( tempMin, tempMax );
 }
template<class T > T rcRectangle< T >::height () const inline
Definition at line 339 of file rc_rectangle.h.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcEngineImpl::analyze(), rcEngineImpl::analyzeFocusArea(), rcMonitor::buildCellBoundary(), rcMuscleTracker::calculateCellLocation(), rcWindow::canTrim(), rcMovieConverter::clippedFrame(), rcKinetoscope::createFunctionSpecificObjects(), rcMovieConverterToQT::createQTMovie(), rcMonitor::displayScalarFocusArea(), rcVisualFunction::dividingProcess(), rcImageCanvasGL::drawCurrentFocus(), rcCell::enclosingBox(), rcEngineImpl::focusMyocyteSelection(), rcEngineImpl::focusScript(), rcKinetoscope::frame(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcMuscleTracker::genEdgePoints(), rcAutoCorrelation::genPoint(), rcMuscleSegmenter::genPolygons(), rcPointCorrelation::genSpace(), rcMomentGenerator::genSumSumSq1D(), rcMomentGenerator::genSumSumSq2D(), rcMomentGenerator::genSumSumSq2DFast(), rcEngineImpl::getAttributes(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcEngineImpl::loadFrames(), main(), rcScalarTrackWidget::mousePressEvent(), rcEngineImpl::muscleTracker(), rcShape::orthogonalBoundingBoxAspect(), rcShape::orthogonalBoundingBoxCenter(), rcPolygon::orthogonalEnclosingRect(), rcMotionVectorPath::parabolicDisparity(), rcNativeExporter::produceTracks(), rcCellWriterGroup::rcCellWriterGroup(), rcEngineFocusData::rcEngineFocusData(), rcValue::rcValue(), rcVisualTarget::rcVisualTarget(), rcWindow::rcWindow(), rfComponentPolygons(), rfGetRects(), rfImageACfield(), rfPixelExpand(), rfPixelSample(), rfPlot1Dsignal(), rfPolygonToSegmentsCollection(), rfRoundRectangle(), rcVisualFunction::roundRectangle(), rcEngineMovieCapture::run(), rcExperimentDomainImpl::saveExperiment(), rcRectSettingWidget::settingChanged(), rcKinetoscope::start(), rcImageCanvasGL::statusString(), rcWindow::trim(), rcVisualTarget::update(), rcControlPanel::updateAnalysisRect(), rcMenuBar::updateAnalysisRect(), rcImageCanvasGL::updateAnalysisRect(), rcVisualFunction::updateRects(), rcVisualFunction::updateSims(), rcDbDtParams::validate(), rcRectSettingWidget::valueChanged(), rcKinetoscope::visualFunctionHistory(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), and rcEngineImpl::writeEntropyData().
 {
   return mLowerRight.y() - mUpperLeft.y();
 }
template<class T> void rcRectangle< T >::height (T h)
Definition at line 470 of file rc_rectangle.h.
 {
   mLowerRight.y() = mUpperLeft.y() + newHeight;
   normalize();
 }
template<class T> rcRectangle< T > rcRectangle< T >::intersect (const rcRectangle< T > & other, bool throwIfNoOverlap = false) const
Definition at line 522 of file rc_rectangle.h.
References rcRectangle< T >::mLowerRight, rcRectangle< T >::mUpperLeft, rmMax, rmMin, rcPair< T >::x(), and rcPair< T >::y().
 {
   rcPair<T> overlapUpperLeft(rmMax(mUpperLeft.x(),other.mUpperLeft.x()),
                            rmMax(mUpperLeft.y(),other.mUpperLeft.y()));
   rcPair<T> overlapLowerRight(rmMin(mLowerRight.x(),other.mLowerRight.x()),
                            rmMin(mLowerRight.y(),other.mLowerRight.y()));
   if ((overlapUpperLeft.x() > overlapLowerRight.x()) ||
      (overlapUpperLeft.y() > overlapLowerRight.y()))
       if (throwIfNoOverlap)
     throw general_exception("rcRectErrors::NoOverlap");
       else
           overlapLowerRight = overlapUpperLeft; // Force a null rectangle
   return rcRectangle<T>(overlapUpperLeft, overlapLowerRight);
 }
template<class T > bool rcRectangle< T >::isNull (void) const inline
Definition at line 357 of file rc_rectangle.h.
Referenced by rcRectangle< T >::enclose(), main(), and rcRectangle< T >::operator|=().
 {
   return (width()==0 || height()==0);
 }
template<class T > rcPair< T > rcRectangle< T >::ll () const inline
Definition at line 327 of file rc_rectangle.h.
Referenced by rcKinetoscope::connectFunction(), rcDrawIRect(), and rfPlot1Dsignal().
 {
   return rcPair<T>(mUpperLeft.x(), mLowerRight.y());
 }
template<class T> const rcPair<T>& rcRectangle< T >::lr () const inline
Definition at line 137 of file rc_rectangle.h.
Referenced by rcVisualFunction::cardiacMeasure(), rcRectangle< T >::contains(), rcVisualFunction::direct(), rcMuscleSegmenter::filterAtEdge(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcDefGenerateImage::genImage(), rcImageCanvasGL::keyPressEvent(), rcDrawIRect(), rfPlot1Dsignal(), rfRoundRectangle(), rcVisualFunction::updateRects(), and withinPreSegmentedBodies().
 {return mLowerRight;}
template<> void rcRectangle< uint32 >::normalize () protected
Definition at line 25 of file rc_rectspec.cpp.
 {
   // No normalization needed for unsigned types
 }
template<> void rcRectangle< uint16 >::normalize () protected
Definition at line 30 of file rc_rectspec.cpp.
 {
   // No normalization needed for unsigned types
 }
template<> void rcRectangle< uint8 >::normalize () protected
Definition at line 35 of file rc_rectspec.cpp.
 {
   // No normalization needed for unsigned types
 }
template<class T > void rcRectangle< T >::normalize () protected
Definition at line 411 of file rc_rectangle.h.
Referenced by rcRectangle< T >::rcRectangle().
 {
   T w = width();
   T h = height();
   if (w<0 || h<0) {
     T x = mUpperLeft.x();
     T y = mUpperLeft.y();
     if (w < 0)
     {
       x += w;
       w = -w;
     }
     if (h < 0)
     {
       y += h;
       h = -h;
     }
     mUpperLeft = rcPair<T>(x, y);
     mLowerRight = rcPair<T>(x+w, y+h);
   }
 }
template<> void rcRectangle< uint32 >::normalize () protected
template<> void rcRectangle< uint16 >::normalize () protected
template<> void rcRectangle< uint8 >::normalize () protected
template<class T> bool rcRectangle< T >::operator!= (const rcRectangle< T > & rhs) const inline
Definition at line 111 of file rc_rectangle.h.
 { return !(*this == rhs); }
template<class T> rcRectangle< T > rcRectangle< T >::operator& (const rcRectangle< T > & other) const inline
Definition at line 363 of file rc_rectangle.h.
 {
   return intersect(other, false);
 }
template<class T> rcRectangle< T > & rcRectangle< T >::operator&= (const rcRectangle< T > & other)
Definition at line 541 of file rc_rectangle.h.
References rcRectangle< T >::mLowerRight, rcRectangle< T >::mUpperLeft, rmMax, and rmMin.
 {
   mUpperLeft.x() = rmMax(mUpperLeft.x(), other.mUpperLeft.x());
   mUpperLeft.y() = rmMax(mUpperLeft.y(), other.mUpperLeft.y());
   mLowerRight.x() = rmMin(mLowerRight.x(),other.mLowerRight.x());
   mLowerRight.y() = rmMin(mLowerRight.y(),other.mLowerRight.y());
   if ((mUpperLeft.x() > mLowerRight.x()) ||
      (mUpperLeft.y() > mLowerRight.y()))
       mLowerRight = mUpperLeft; // Force a null rectangle
   return *this;
 }
template<class T> bool rcRectangle< T >::operator== (const rcRectangle< T > & rhs) const
Definition at line 436 of file rc_rectangle.h.
References rcRectangle< T >::mLowerRight, and rcRectangle< T >::mUpperLeft.
 {
   return (mUpperLeft.x() == rhs.mUpperLeft.x()) &&
          (mUpperLeft.y() == rhs.mUpperLeft.y()) &&
          (mLowerRight.x() == rhs.mLowerRight.x()) &&
          (mLowerRight.y() == rhs.mLowerRight.y());
 }
template<class T> rcRectangle< T > rcRectangle< T >::operator| (const rcRectangle< T > & other) const inline
Definition at line 369 of file rc_rectangle.h.
 {
   return enclose(other);
 }
template<class T> rcRectangle< T > & rcRectangle< T >::operator|= (const rcRectangle< T > & other)
Definition at line 570 of file rc_rectangle.h.
References rcRectangle< T >::isNull(), rcRectangle< T >::mLowerRight, rcRectangle< T >::mUpperLeft, rmMax, and rmMin.
 {
   if (!other.isNull())
   {
     if (isNull())
         *this = other;
     else {
         mUpperLeft.x() = rmMin(mUpperLeft.x(), other.mUpperLeft.x());
         mUpperLeft.y() = rmMin(mUpperLeft.y(), other.mUpperLeft.y());
         mLowerRight.x() = rmMax(mLowerRight.x(), other.mLowerRight.x());
         mLowerRight.y() = rmMax(mLowerRight.y(), other.mLowerRight.y());
     }
   }
   return *this;
 }
template<class T> const rcPair<T>& rcRectangle< T >::origin () const inline
Definition at line 117 of file rc_rectangle.h.
Referenced by rcEngineImpl::focusScript(), rcDefGenerateImage::genImage(), main(), rcWindow::rcWindow(), rfRoundRectangle(), rcVisualFunction::roundRectangle(), rcWindow::translate(), rcWindow::trim(), rcVisualTarget::update(), rcKinetoscope::visualFunctionHistory(), and rcWindow::window().
 {return mUpperLeft;}
template<class T> void rcRectangle< T >::origin (const rcPair< T > & newOrigin)
Definition at line 445 of file rc_rectangle.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   rcPair<T> temp(newOrigin.x()-mUpperLeft.x(),
                  newOrigin.y()-mUpperLeft.y());
   mUpperLeft = newOrigin;
   mLowerRight.x() += temp.x();
   mLowerRight.y() += temp.y();
 }
template<class T> bool rcRectangle< T >::overlaps (const rcRectangle< T > & other, bool touching = false) const
Definition at line 485 of file rc_rectangle.h.
References rcRectangle< T >::mLowerRight, rcRectangle< T >::mUpperLeft, rmMax, rmMin, rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcPolygon::intersects(), and rfGetRects().
 {
   rcPair<T> overlapUpperLeft(rmMax(mUpperLeft.x(),other.mUpperLeft.x()),
                            rmMax(mUpperLeft.y(),other.mUpperLeft.y()));
   rcPair<T> overlapLowerRight(rmMin(mLowerRight.x(),other.mLowerRight.x()),
                            rmMin(mLowerRight.y(),other.mLowerRight.y()));
   if (touching)
   {
     return (overlapUpperLeft.x() <= overlapLowerRight.x()) &&
     (overlapUpperLeft.y() <= overlapLowerRight.y());
   }
   else
   {
     /* must actually overlap */
     return (overlapUpperLeft.x() < overlapLowerRight.x()) &&
     (overlapUpperLeft.y() < overlapLowerRight.y());
   }
 }
template<class T > rcPair< T > rcRectangle< T >::size (void) const inline
Definition at line 345 of file rc_rectangle.h.
Referenced by rcKinetoscope::canonicalMotionField(), rcVisualFunction::cardiacUpdate(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcKinetoscope::epiMotionField(), rcWindow::maxTrim(), rcWindow::trim(), and rcVisualFunction::updateSims().
 {
   return rcPair<T>(width(), height());
 }
template<class T> void rcRectangle< T >::size (const rcPair< T > & newSize)
Definition at line 477 of file rc_rectangle.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   mLowerRight.x() = mUpperLeft.x() + newSize.x();
   mLowerRight.y() = mUpperLeft.y() + newSize.y();
   normalize();
 }
template<class T> void rcRectangle< T >::translate (const rcPair< T > & disp)
Definition at line 454 of file rc_rectangle.h.
References rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcVisualFunction::direct(), rcAnalyzer::getNextResult(), rcKinetoscope::isWithin(), and rcVisualTarget::update().
 {
   mUpperLeft.x() += disp.x();
   mUpperLeft.y() += disp.y();
   mLowerRight.x() += disp.x();
   mLowerRight.y() += disp.y();
 }
template<class T > rcRectangle< T > rcRectangle< T >::transpose (void) const
Definition at line 609 of file rc_rectangle.h.
 {
     rcPair<T> transposeUpperLeft(mUpperLeft.y(), mUpperLeft.x());
     rcPair<T> transposeLowerRight(mLowerRight.y(), mLowerRight.x());
     return rcRectangle<T>(transposeUpperLeft, transposeLowerRight);
 }
template<> rcRectangle< uint32 > rcRectangle< uint32 >::trim (uint32 left, uint32 right, uint32 top, uint32 bottom, bool throwIfNegativeSize) const
Definition at line 42 of file rc_rectspec.cpp.
 {
   uint32 newWidth = width() - (left + right);
   uint32 newHeight = height() - (top + bottom);
   if (newWidth < 1 || newHeight < 1)
       if (throwIfNegativeSize)
     throw general_exception("rcRectErrors::NegativeSize");
   return rcRectangle<uint32>(mUpperLeft + rcPair<uint32>(left, top),
                    mLowerRight - rcPair<uint32>(right, bottom));
 }
template<> rcRectangle< uint16 > rcRectangle< uint16 >::trim (uint16 left, uint16 right, uint16 top, uint16 bottom, bool throwIfNegativeSize) const
Definition at line 57 of file rc_rectspec.cpp.
 {
   uint16 newWidth = width() - (left + right);
   uint16 newHeight = height() - (top + bottom);
   if (newWidth < 1 || newHeight < 1)
       if (throwIfNegativeSize)
     throw general_exception("rcRectErrors::NegativeSize");
   return rcRectangle<uint16>(mUpperLeft + rcPair<uint16>(left, top),
                    mLowerRight - rcPair<uint16>(right, bottom));
 }
template<> rcRectangle< uint8 > rcRectangle< uint8 >::trim (uint8 left, uint8 right, uint8 top, uint8 bottom, bool throwIfNegativeSize) const
Definition at line 72 of file rc_rectspec.cpp.
 {
   uint8 newWidth = width() - (left + right);
   uint8 newHeight = height() - (top + bottom);
   if (newWidth < 1 || newHeight < 1)
       if (throwIfNegativeSize)
     throw general_exception("rcRectErrors::NegativeSize");
   return rcRectangle<uint8>(mUpperLeft + rcPair<uint8>(left, top),
                    mLowerRight - rcPair<uint8>(right, bottom));
 }
template<class T> rcRectangle< T > rcRectangle< T >::trim (T left, T right, T top, T bottom, bool throwIfNegativeSize = false) const
Definition at line 595 of file rc_rectangle.h.
Referenced by rcWindow::canPeekOutSide(), rcKinetoscope::selfSimilarMotionField(), and rcVisualFunction::updateRects().
 {
   T newWidth = width() - (left + right);
   T newHeight = height() - (top + bottom);
   if (newWidth < 0 || newHeight < 0)
       if (throwIfNegativeSize)
     throw general_exception("rcRectErrors::NegativeSize");
   return rcRectangle<T>(mUpperLeft + rcPair<T>(left, top),
                    mLowerRight - rcPair<T>(right, bottom));
 }
template<class T> rcRectangle< T > rcRectangle< T >::trim (T pad, bool throwIfNegativeSize = false) const
Definition at line 589 of file rc_rectangle.h.
References trim().
 {
   return trim (pad, pad, pad, pad, throwIfNegativeSize);
 }
template<> rcRectangle< uint32 > rcRectangle< uint32 >::trim (uint32 left, uint32 right, uint32 top, uint32 bottom, bool throwIfNegativeSize) const
template<> rcRectangle< uint16 > rcRectangle< uint16 >::trim (uint16 left, uint16 right, uint16 top, uint16 bottom, bool throwIfNegativeSize) const
template<> rcRectangle< uint8 > rcRectangle< uint8 >::trim (uint8 left, uint8 right, uint8 top, uint8 bottom, bool throwIfNegativeSize) const
template<class T> const rcPair<T>& rcRectangle< T >::ul () const inline
Definition at line 134 of file rc_rectangle.h.
Referenced by rcVisualFunction::cardiacMeasure(), rcVisualFunction::cardiacUpdate(), rcKinetoscope::connectFunction(), rcRectangle< T >::contains(), rcVisualFunction::correspond(), rcVisualFunction::correspondMutualChannel(), rcVisualFunction::direct(), rcVisualFunction::dividingProcess(), rcMuscleSegmenter::filterAtEdge(), rcKinetoscope::frame(), rcMuscleSegmenter::genPolygons(), rcMonitor::getPosition(), rcVisualFunction::grow(), rcKinetoscope::isWithin(), rcImageCanvasGL::keyPressEvent(), rcVisualFunction::measure(), rcShape::orthogonalBoundingBoxCenter(), rcPolygon::orthogonalEnclosingRect(), rcDrawIRect(), rcVisualTarget::rcVisualTarget(), rfComponentPolygons(), rfImageACfield(), rfPlot1Dsignal(), rfRoundRectangle(), rcVisualFunction::roundRectangle(), rcVisualFunction::updateRects(), rcVisualFunction::updateSims(), and withinPreSegmentedBodies().
 {return mUpperLeft;} /* same as origin() */
template<class T > rcPair< T > rcRectangle< T >::ur () const inline
Definition at line 321 of file rc_rectangle.h.
Referenced by rcKinetoscope::connectFunction(), and rcDrawIRect().
 {
   return rcPair<T>(mLowerRight.x(), mUpperLeft.y());
 }
template<class T > T rcRectangle< T >::width () const inline
Definition at line 333 of file rc_rectangle.h.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcEngineImpl::analyze(), rcEngineImpl::analyzeFocusArea(), rcMonitor::buildCellBoundary(), rcMuscleTracker::calculateCellLocation(), rcWindow::canTrim(), rcMovieConverter::clippedFrame(), rcKinetoscope::createFunctionSpecificObjects(), rcMovieConverterToQT::createQTMovie(), rcMonitor::displayScalarFocusArea(), rcVisualFunction::dividingProcess(), rcImageCanvasGL::drawCurrentFocus(), rcCell::enclosingBox(), rcEngineImpl::focusMyocyteSelection(), rcEngineImpl::focusScript(), rcKinetoscope::frame(), rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcMuscleTracker::genEdgePoints(), rcAutoCorrelation::genPoint(), rcMuscleSegmenter::genPolygons(), rcPointCorrelation::genSpace(), rcMomentGenerator::genSumSumSq1D(), rcMomentGenerator::genSumSumSq2D(), rcMomentGenerator::genSumSumSq2DFast(), rcEngineImpl::getAttributes(), rcMomentGenerator::hProject2D(), rcMomentGenerator::hProject2DFast(), rcEngineImpl::loadFrames(), main(), rcScalarTrackWidget::mousePressEvent(), rcEngineImpl::muscleTracker(), rcShape::orthogonalBoundingBoxAspect(), rcShape::orthogonalBoundingBoxCenter(), rcPolygon::orthogonalEnclosingRect(), rcMotionVectorPath::parabolicDisparity(), rcNativeExporter::produceTracks(), rcCellWriterGroup::rcCellWriterGroup(), rcEngineFocusData::rcEngineFocusData(), rcValue::rcValue(), rcVisualTarget::rcVisualTarget(), rcWindow::rcWindow(), rfComponentPolygons(), rfGetRects(), rfImageACfield(), rfPixelExpand(), rfPixelSample(), rfPlot1Dsignal(), rfPolygonToSegmentsCollection(), rfRoundRectangle(), rcVisualFunction::roundRectangle(), rcEngineMovieCapture::run(), rcExperimentDomainImpl::saveExperiment(), rcRectSettingWidget::settingChanged(), rcKinetoscope::start(), rcImageCanvasGL::statusString(), rcWindow::trim(), rcVisualTarget::update(), rcControlPanel::updateAnalysisRect(), rcMenuBar::updateAnalysisRect(), rcImageCanvasGL::updateAnalysisRect(), rcVisualFunction::updateRects(), rcVisualFunction::updateSims(), rcDbDtParams::validate(), rcRectSettingWidget::valueChanged(), rcKinetoscope::visualFunctionHistory(), rcMomentGenerator::vProject1D(), rcMomentGenerator::vProject2D(), rcMomentGenerator::vProject2DFast(), withinPreSegmentedBodies(), and rcEngineImpl::writeEntropyData().
 {
   return mLowerRight.x() - mUpperLeft.x();
 }
template<class T> void rcRectangle< T >::width (T w)
Definition at line 463 of file rc_rectangle.h.
 {
   mLowerRight.x() = mUpperLeft.x() + newWidth;
   normalize();
 }
Friends And Related Function Documentation
template<class T> ostream& operator<< (ostream & ous, const rcRectangle< T > & dis) friend
Definition at line 306 of file rc_rectangle.h.
   {
     ous << dis.ul() << "," << dis.lr();
     return ous;
   }
Member Data Documentation
template<class T> rcPair<T> rcRectangle< T >::mLowerRight protected
Definition at line 317 of file rc_rectangle.h.
Referenced by rcRectangle< T >::enclose(), rcRectangle< T >::intersect(), rcRectangle< T >::operator&=(), rcRectangle< T >::operator==(), rcRectangle< T >::operator|=(), and rcRectangle< T >::overlaps().
template<class T> rcPair<T> rcRectangle< T >::mUpperLeft protected
Definition at line 316 of file rc_rectangle.h.
Referenced by rcRectangle< T >::enclose(), rcRectangle< T >::intersect(), rcRectangle< T >::operator&=(), rcRectangle< T >::operator==(), rcRectangle< T >::operator|=(), and rcRectangle< T >::overlaps().
The documentation for this class was generated from the following file:
include/util/rc_rectangle.h