Visible: rcMovieFileOrgExt Class Reference
rcMovieFileOrgExt Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileOrgExt ()
rcMovieFileOrgExt (movieOriginType o, int64 bt, uint32 fc, int32 w, int32 h, rcPixel depth, movieFormatRev r, const char *c)
bool write (FILE *saveStream) const
ostream & log (ostream &os) const
void fixEndian (const reByteOrder &fileByteOrder)
const movieOriginType & origin () const
const int64 & baseTime () const
const uint32 & frameCount () const
const int32 & width () const
const int32 & height () const
const rcPixel & depth () const
const movieFormatRev & rev () const
const char * creatorName () const
const int32 & id () const
void id (const int32 &i)
Public Member Functions inherited from rcMovieFileExt
rcMovieFileExt ()
rcMovieFileExt (movieExtensionType t)
rcMovieFileExt (movieExtensionType t, int64 o)
const movieExtensionType & type () const
const int64 & offset () const
bool write (FILE *saveStream) const
void fixEndian (const reByteOrder &fileByteOrder)
Private Attributes
movieOriginType mOrigin
int64 mOriginalBaseTime
uint32 mOriginalFrameCount
int32 mOriginalWidth
int32 mOriginalHeight
rcPixel mOriginalDepth
movieFormatRev mRev
int32 mId
char mComment [64]
Detailed Description
Definition at line 275 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileOrgExt::rcMovieFileOrgExt ()
Definition at line 327 of file rc_moviefileformat.cpp.
References mComment, and rmDim.
                                      :
         rcMovieFileExt(movieExtensionORG, sizeof(rcMovieFileOrgExt)), mOrigin( movieOriginUnknown ),
         mOriginalBaseTime( 0 ), mOriginalFrameCount( 0 ), mOriginalWidth( 0 ), mOriginalHeight( 0 ),
         mOriginalDepth(rcPixelUnknown), mRev( movieFormatInvalid ), mId( 0 )
 {
     memset( mComment, 0, rmDim(mComment) );
     snprintf( mComment, rmDim(mComment), "Unknown" );
}
rcMovieFileOrgExt::rcMovieFileOrgExt (movieOriginType o, int64 bt, uint32 fc, int32 w, int32 h, rcPixel depth, movieFormatRev r, const char * c)
Definition at line 336 of file rc_moviefileformat.cpp.
References mComment, and rmDim.
                                                                         :
         rcMovieFileExt(movieExtensionORG, sizeof(rcMovieFileOrgExt)),
         mOrigin( o ), mOriginalBaseTime( bt ), mOriginalFrameCount( fc ),
         mOriginalWidth( w ), mOriginalHeight( h ), mOriginalDepth(depth),
         mRev( r ), mId( 0 )
 {
     memset( mComment, 0, rmDim(mComment) );
     if ( c )
         snprintf( mComment, rmDim(mComment), "%s", c );
     else
         snprintf( mComment, rmDim(mComment), "Unknown" );
}
Member Function Documentation
const int64& rcMovieFileOrgExt::baseTime () const inline
Definition at line 293 of file rc_moviefileformat.h.
References mOriginalBaseTime.
Referenced by log(), and operator<<().
 { return mOriginalBaseTime; }
const char* rcMovieFileOrgExt::creatorName () const inline
Definition at line 299 of file rc_moviefileformat.h.
References mComment.
Referenced by log(), and operator<<().
 { return mComment; }
const rcPixel& rcMovieFileOrgExt::depth () const inline
Definition at line 297 of file rc_moviefileformat.h.
References mOriginalDepth.
Referenced by log(), and operator<<().
 { return mOriginalDepth; }
void rcMovieFileOrgExt::fixEndian (const reByteOrder & fileByteOrder)
Definition at line 367 of file rc_moviefileformat.cpp.
References ByteSwapN, rcMovieFileExt::fixEndian(), mId, mOrigin, mOriginalBaseTime, mOriginalDepth, mOriginalFrameCount, mOriginalHeight, mOriginalWidth, mRev, and rfPlatformByteOrder().
Referenced by rcVideoCache::orgLoad(), and write().
 {
     if ( rfPlatformByteOrder() != fileByteOrder )
     {
         rcMovieFileExt::fixEndian (fileByteOrder);
         ByteSwapN (mOriginalFrameCount);                // First frame from input movie
         ByteSwapN (mOriginalWidth);
         ByteSwapN (mOriginalHeight);
         ByteSwapN ( mOriginalDepth);
         ByteSwapN (mOriginalBaseTime);                       // Conversion date
         ByteSwapN ( mOrigin);
         ByteSwapN ( mRev);
         ByteSwapN (mId);                         // Unique id, reserved for future use
     }
 }
const uint32& rcMovieFileOrgExt::frameCount () const inline
Definition at line 294 of file rc_moviefileformat.h.
References mOriginalFrameCount.
Referenced by log(), and operator<<().
 { return mOriginalFrameCount; }
const int32& rcMovieFileOrgExt::height () const inline
Definition at line 296 of file rc_moviefileformat.h.
References mOriginalHeight.
Referenced by log(), and operator<<().
 { return mOriginalHeight; }
const int32& rcMovieFileOrgExt::id (void) const inline
Definition at line 300 of file rc_moviefileformat.h.
References mId.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), and operator<<().
 { return mId; }
void rcMovieFileOrgExt::id (const int32 & i) inline
Definition at line 303 of file rc_moviefileformat.h.
References mId.
 { mId = i; }
ostream & rcMovieFileOrgExt::log (ostream & os) const
Definition at line 385 of file rc_moviefileformat.cpp.
References baseTime(), convertSecondsToTimestamp(), creatorName(), depth(), endl(), frameCount(), height(), rcTimestamp::localtime(), movieOriginCaptureCertified, movieOriginCaptureUncertified, movieOriginUnknown, origin(), rev(), and width().
Referenced by rcEngineImpl::setCaptureInfo().
 {
     os << "Origin: " << origin() << endl;
     os << " Creator: " << creatorName() << endl;
     os << " Capture date: ";
     // Capture dates are in absolute epoch time
     if ( baseTime() > convertSecondsToTimestamp(3600*24) ) {
         // Anything later than one day after start of epoch is
         // considered a valid date
         rcTimestamp creationDate = rcTimestamp( baseTime() );
         os << creationDate.localtime() << endl;
     } else {
         os << "Unknown" << endl;
     }
     if ( origin() != movieOriginUnknown ) {
         os << " FrameCount: " << frameCount()
            << " FrameDepth: " << depth()*8 << endl;
         os << " FrameSize: " << width() << "x" << height();
         if ( origin() == movieOriginCaptureCertified ||
              origin() == movieOriginCaptureUncertified )
             os << " FileRev: " << rev() << endl;
         else
             os << endl;
     }
     return os;
 }
const movieOriginType& rcMovieFileOrgExt::origin () const inline
Definition at line 292 of file rc_moviefileformat.h.
References mOrigin.
Referenced by rcKinetoscope::frame(), log(), and operator<<().
 { return mOrigin; }
const movieFormatRev& rcMovieFileOrgExt::rev () const inline
Definition at line 298 of file rc_moviefileformat.h.
References mRev.
Referenced by log(), and operator<<().
 { return mRev; }
const int32& rcMovieFileOrgExt::width () const inline
Definition at line 295 of file rc_moviefileformat.h.
References mOriginalWidth.
Referenced by log(), and operator<<().
 { return mOriginalWidth; }
bool rcMovieFileOrgExt::write (FILE * saveStream) const
Definition at line 352 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), rfPlatformByteOrder(), and rfPlatformByteOrderMark().
Referenced by rcGenMovieFile::flush().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileOrgExt *>(this)->fixEndian (rfPlatformByteOrder(rfPlatformByteOrderMark()) );
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("ORG hdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
Member Data Documentation
char rcMovieFileOrgExt::mComment[64] private
Definition at line 314 of file rc_moviefileformat.h.
Referenced by creatorName(), and rcMovieFileOrgExt().
int32 rcMovieFileOrgExt::mId private
Definition at line 313 of file rc_moviefileformat.h.
Referenced by fixEndian(), and id().
movieOriginType rcMovieFileOrgExt::mOrigin private
Definition at line 306 of file rc_moviefileformat.h.
Referenced by fixEndian(), and origin().
int64 rcMovieFileOrgExt::mOriginalBaseTime private
Definition at line 307 of file rc_moviefileformat.h.
Referenced by baseTime(), and fixEndian().
rcPixel rcMovieFileOrgExt::mOriginalDepth private
Definition at line 311 of file rc_moviefileformat.h.
Referenced by depth(), and fixEndian().
uint32 rcMovieFileOrgExt::mOriginalFrameCount private
Definition at line 308 of file rc_moviefileformat.h.
Referenced by fixEndian(), and frameCount().
int32 rcMovieFileOrgExt::mOriginalHeight private
Definition at line 310 of file rc_moviefileformat.h.
Referenced by fixEndian(), and height().
int32 rcMovieFileOrgExt::mOriginalWidth private
Definition at line 309 of file rc_moviefileformat.h.
Referenced by fixEndian(), and width().
movieFormatRev rcMovieFileOrgExt::mRev private
Definition at line 312 of file rc_moviefileformat.h.
Referenced by fixEndian(), and rev().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp