Visible: rcTextLineSettingWidget Class Reference
rcTextLineSettingWidget Class Reference
#include <include/visUI/rc_textlinesettingwidget.h>
Public Slots
void valueChanged (const QString &text)
void settingChanged (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcTextLineSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcTextLineSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
QLineEdit * mWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 8 of file rc_textlinesettingwidget.h.
Constructor & Destructor Documentation
rcTextLineSettingWidget::rcTextLineSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 17 of file rc_textlinesettingwidget.cpp.
References rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), rcSettingWidget::mTopLayout, mWidget, settingChanged(), and valueChanged().
     : rcSettingWidget( parent, setting )
 {
     mWidget = new rcLineEdit( this , setting.getTag() );
     mTopLayout->addWidget( mWidget );
     QToolTip::add( mWidget , setting.getDescription() );
     // update the text widget with the current value of the setting.
     settingChanged();
     connect( mWidget , SIGNAL( textCommited( const QString& ) ) ,
              this    , SLOT( valueChanged( const QString& ) ) );
     // connect this widget to be notified by the updateSettings()
     //  signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
 }
rcTextLineSettingWidget::~rcTextLineSettingWidget ()
Definition at line 38 of file rc_textlinesettingwidget.cpp.
References mWidget.
 {
     QToolTip::remove( mWidget );
 }
Member Function Documentation
void rcTextLineSettingWidget::settingChanged (void) slot
Definition at line 55 of file rc_textlinesettingwidget.cpp.
References rcSettingInfo::getValue(), rcSettingWidget::mSetting, mWidget, and rcSettingWidget::updateWidgetState().
Referenced by rcTextLineSettingWidget().
 {
     string currentValue = mSetting.getValue();
     mWidget->setText( currentValue.c_str() );
     // Update visibility/editability
     updateWidgetState();
 }
void rcTextLineSettingWidget::valueChanged (const QString & text) slot
Definition at line 45 of file rc_textlinesettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcTextLineSettingWidget().
 {
     mSetting.setValue( text.latin1() );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
QLineEdit* rcTextLineSettingWidget::mWidget private
Definition at line 25 of file rc_textlinesettingwidget.h.
Referenced by rcTextLineSettingWidget(), settingChanged(), and ~rcTextLineSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_textlinesettingwidget.h
src/visible/qt/rc_textlinesettingwidget.cpp