Visible: rcSegmentIteratorImpl Class Reference
rcSegmentIteratorImpl Class Reference
#include <include/visiCore/rc_segmentimpl.h>
Public Member Functions
rcSegmentIteratorImpl (rcTrackImpl *track, const rcTimestamp &position, rcMutex &mutex)
virtual ~rcSegmentIteratorImpl ()
virtual rcTimestamp getSegmentLength (void)
virtual rcTimestamp getSegmentOffset (void)
virtual int32 getSegmentIndex (void)
virtual rcTimestamp getSegmentStartAbsolute (void)
virtual rcTimestamp getSegmentStart (void)
virtual rcTimestamp getTrackOffset (void)
virtual bool hasNextSegment (bool lock=true)
virtual uint32 getSegmentCount (void)
virtual bool contains (const rcTimestamp &time)
virtual rcRect getFocus (void)
virtual void advance (const rcTimestamp &amount, bool lock=true)
virtual void advanceNoLock (const rcTimestamp &amount)
virtual bool advance (int32 offset, bool lock=true)
virtual bool advanceNoLock (int32 offset)
virtual void lock ()
virtual void unlock ()
virtual void reset (bool lock=true)
virtual void release (void)
rcMutex & mutex (void)
Public Member Functions inherited from rcSegmentIterator
virtual ~rcSegmentIterator ()
Protected Attributes
rcTimestamp _position
rcSegmentImpl _currentSegment
int32 _segmentIndex
rcTimestamp _segmentOffset
rcMutex & _mutex
rcTrackImpl * _track
rcTimestamp _experimentOffset
Private Member Functions
rcSegmentImpl findClosestSegment (const rcTimestamp &time, int32 &index)
Detailed Description
Definition at line 58 of file rc_segmentimpl.h.
Constructor & Destructor Documentation
rcSegmentIteratorImpl::rcSegmentIteratorImpl (rcTrackImpl * track, const rcTimestamp & position, rcMutex & mutex)
Definition at line 12 of file rc_segmentimpl.cpp.
References _currentSegment, _experimentOffset, _position, _segmentIndex, _segmentOffset, _track, advance(), cZeroTime, rcExperimentDomainFactory::getExperimentDomain(), rcExperimentDomain::getExperimentStart(), rcTrackImpl::getTrackStart(), rmAssert, and rcSegmentImpl::setLength().
                                                                :
         _currentSegment( cZeroTime, cZeroTime, rcRect() ), _mutex( mutex )
 {
     rmAssert( track );
     // Position is a timestamp relative to start of experiment
     // We need to compute what it is in relation to track start time
     rcExperimentDomain* domain = rcExperimentDomainFactory::getExperimentDomain();
     const rcTimestamp expStart = domain->getExperimentStart();
     rcTimestamp trackStart = track->getTrackStart();
     const rcTimestamp pos = (expStart + position) - trackStart;
     if ( trackStart >= cZeroTime ) {
         // Track cannot start before experiment starts...
         if ( trackStart < expStart )
             trackStart = expStart;
         _experimentOffset = trackStart - expStart;
     } else
         _experimentOffset = cZeroTime;
     _track = track;
     _segmentIndex = -1;
     // handle case where position is negative - act like there's
     //  a dummy segment before the first real data segment
     if ( pos < cZeroTime ) {
         _position = pos;
         _currentSegment.setLength( _position );
         _segmentOffset = cZeroTime;
     }
     else
     {
         _position = cZeroTime;
         _segmentOffset = cZeroTime;
         advance( pos );
     }
 }
virtual rcSegmentIteratorImpl::~rcSegmentIteratorImpl () inline virtual
Definition at line 64 of file rc_segmentimpl.h.
 {};
Member Function Documentation
void rcSegmentIteratorImpl::advance (const rcTimestamp & amount, bool lock = true) virtual
Implements rcSegmentIterator.
Definition at line 127 of file rc_segmentimpl.cpp.
References _mutex, advanceNoLock(), and lock().
Referenced by rcSegmentIteratorImpl().
 {
     if ( lock ) {
         rcLock lock (_mutex);
         advanceNoLock( amount );
     } else {
         advanceNoLock( amount );
     }
 }
bool rcSegmentIteratorImpl::advance (int32 offset, bool lock = true) virtual
Implements rcSegmentIterator.
Definition at line 187 of file rc_segmentimpl.cpp.
References _mutex, advanceNoLock(), and lock().
 {
     if ( lock ) {
         rcLock lock (_mutex);
         return advanceNoLock( count );
     } else {
         return advanceNoLock( count );
     }
 }
void rcSegmentIteratorImpl::advanceNoLock (const rcTimestamp & amount) virtual
Definition at line 138 of file rc_segmentimpl.cpp.
References _currentSegment, _position, _segmentIndex, _segmentOffset, _track, cZeroTime, findClosestSegment(), rcSegmentImpl::length(), rcTrackImpl::segment(), rcTrackImpl::segments(), and rcSegmentImpl::start().
Referenced by advance(), rcGraphicsSegmentIteratorImpl::advance(), rcScalarSegmentIteratorImpl::advance(), rcPositionSegmentIteratorImpl::advance(), rcVideoSegmentIteratorImpl::advance(), and reset().
 {
     const int nSegments = _track->segments();
     if ( nSegments > 0 ) {
         // First advance call
         if ( _segmentIndex < 0 ) {
             _position = cZeroTime;
             _segmentOffset = cZeroTime;
             _segmentIndex = 0;
             _currentSegment = _track->segment( _segmentIndex );
         }
         // Sequential advance call
         if ( amount > cZeroTime ) {
             rcTimestamp start = _currentSegment.start();
             rcTimestamp target = _segmentOffset + amount;
             if ( _position >= start )
                 target += start;
             // Find closest segment
             _currentSegment = findClosestSegment( target, _segmentIndex );
             start = _currentSegment.start();
             const rcTimestamp end = start + _currentSegment.length();
             if ( target < start ) {
                 // Requested time is before start of track
                 _position = target;
                 _segmentOffset = target;
             } else {
                 if ( target < end ) {
                     // Requested time is within a segment
                     _position = target;
                     _segmentOffset = _position - start;
                 }
                 else if ( target > end ) {
                     // Requested time is after end of track
                     _position = end;
                     _segmentOffset = cZeroTime;
                 } else {
                     // Requested time is on a segment boundary
                     _position = target;
                     _segmentOffset = cZeroTime;
                 }
             }
         }
     }
 }
bool rcSegmentIteratorImpl::advanceNoLock (int32 offset) virtual
Definition at line 198 of file rc_segmentimpl.cpp.
References _currentSegment, _position, _segmentIndex, _segmentOffset, _track, count(), cZeroTime, rcTrackImpl::segment(), rcTrackImpl::segments(), and rcSegmentImpl::start().
 {
     int32 nSegments = _track->segments();
     int32 newIndex = _segmentIndex + count;
     if ( newIndex >= nSegments ) {
         // Can't advance forward any more
         return false;
     }
     else if ( newIndex < 0 ) {
         // Can't advance backwards any more
         return false;
     }
     _currentSegment = _track->segment( newIndex );
     _segmentOffset = cZeroTime;
     _position = _currentSegment.start();
     _segmentIndex = newIndex;
     return true;
 }
bool rcSegmentIteratorImpl::contains (const rcTimestamp & time) virtual
Implements rcSegmentIterator.
Definition at line 110 of file rc_segmentimpl.cpp.
References _currentSegment, _experimentOffset, rcSegmentImpl::length(), and rcSegmentImpl::start().
Referenced by rcGraphicsSegmentIteratorImpl::contains(), rcScalarSegmentIteratorImpl::contains(), rcPositionSegmentIteratorImpl::contains(), and rcVideoSegmentIteratorImpl::contains().
 {
     rcTimestamp startSeg = _experimentOffset + _currentSegment.start();
     rcTimestamp endSeg = startSeg + _currentSegment.length();
     if ( time >= startSeg && time <= endSeg )
         return true;
     else
         return false;
 }
rcSegmentImpl rcSegmentIteratorImpl::findClosestSegment (const rcTimestamp & time, int32 & index) private
Definition at line 277 of file rc_segmentimpl.cpp.
References _currentSegment, _track, rcSegmentImpl::length(), rmAssert, rcTrackImpl::segment(), rcTrackImpl::segments(), and rcSegmentImpl::start().
Referenced by advanceNoLock().
 {
     index = -1;
     const int32 nSegments = _track->segments();
     if ( nSegments > 0 ) {
         int32 first = 0;
         int32 last = nSegments - 1;
         // Binary search the segments
         while ( first <= last ) {
             int32 mid = (first + last) / 2;
             rcSegmentImpl currentSegment = _track->segment( mid );
             rcTimestamp start = currentSegment.start();
             if ( time < start ) {
                 last = mid - 1;
             }
             else if ( time > start ) {
                 rcTimestamp end = start + currentSegment.length();
                 if ( time < end ) {
                     index = mid;
                     return currentSegment;
                 }
                 first = mid + 1;
             }
             else {
                 index = mid;
                 return currentSegment;
             }
         }
         if ( last < 0 )
             index = 0;    // Time is before start of track
         else
             index = last; // Time is after end of track
         return _track->segment( index );
     }
     rmAssert( nSegments > 0 );
     // Error, this should never happen
     return _currentSegment;
 }
rcRect rcSegmentIteratorImpl::getFocus (void) virtual
Implements rcSegmentIterator.
Definition at line 121 of file rc_segmentimpl.cpp.
References _currentSegment, and rcSegmentImpl::focus().
Referenced by rcGraphicsSegmentIteratorImpl::getFocus(), rcScalarSegmentIteratorImpl::getFocus(), rcPositionSegmentIteratorImpl::getFocus(), and rcVideoSegmentIteratorImpl::getFocus().
 {
     return _currentSegment.focus();
 }
uint32 rcSegmentIteratorImpl::getSegmentCount (void) virtual
Implements rcSegmentIterator.
Definition at line 103 of file rc_segmentimpl.cpp.
References _mutex, _track, lock(), and rcTrackImpl::segments().
Referenced by rcGraphicsSegmentIteratorImpl::getSegmentCount(), rcScalarSegmentIteratorImpl::getSegmentCount(), rcPositionSegmentIteratorImpl::getSegmentCount(), and rcVideoSegmentIteratorImpl::getSegmentCount().
 {
     rcLock lock (_mutex);
     return _track->segments();
 }
int32 rcSegmentIteratorImpl::getSegmentIndex (void) virtual
Implements rcSegmentIterator.
Definition at line 78 of file rc_segmentimpl.cpp.
References _segmentIndex.
Referenced by rcGraphicsSegmentIteratorImpl::getSegmentIndex(), rcScalarSegmentIteratorImpl::getSegmentIndex(), rcPositionSegmentIteratorImpl::getSegmentIndex(), rcVideoSegmentIteratorImpl::getSegmentIndex(), rcScalarSegmentIteratorImpl::setCurrentValue(), rcPositionSegmentIteratorImpl::setCurrentValue(), rcVideoSegmentIteratorImpl::setCurrentValue(), and rcGraphicsSegmentIteratorImpl::setCurrentValue().
 {
     return _segmentIndex;
 }
rcTimestamp rcSegmentIteratorImpl::getSegmentLength (void) virtual
Implements rcSegmentIterator.
Definition at line 54 of file rc_segmentimpl.cpp.
References _currentSegment, and rcSegmentImpl::length().
Referenced by rcGraphicsSegmentIteratorImpl::getSegmentLength(), rcScalarSegmentIteratorImpl::getSegmentLength(), rcPositionSegmentIteratorImpl::getSegmentLength(), and rcVideoSegmentIteratorImpl::getSegmentLength().
 {
     return _currentSegment.length();
 }
rcTimestamp rcSegmentIteratorImpl::getSegmentOffset (void) virtual
Implements rcSegmentIterator.
Definition at line 72 of file rc_segmentimpl.cpp.
References _segmentOffset.
Referenced by rcGraphicsSegmentIteratorImpl::getSegmentOffset(), rcScalarSegmentIteratorImpl::getSegmentOffset(), rcPositionSegmentIteratorImpl::getSegmentOffset(), and rcVideoSegmentIteratorImpl::getSegmentOffset().
 {
     return _segmentOffset;
 }
rcTimestamp rcSegmentIteratorImpl::getSegmentStart (void) virtual
Implements rcSegmentIterator.
Definition at line 60 of file rc_segmentimpl.cpp.
References _currentSegment, and rcSegmentImpl::start().
Referenced by rcGraphicsSegmentIteratorImpl::getSegmentStart(), rcScalarSegmentIteratorImpl::getSegmentStart(), rcPositionSegmentIteratorImpl::getSegmentStart(), and rcVideoSegmentIteratorImpl::getSegmentStart().
 {
     return _currentSegment.start();
 }
rcTimestamp rcSegmentIteratorImpl::getSegmentStartAbsolute (void) virtual
Implements rcSegmentIterator.
Definition at line 66 of file rc_segmentimpl.cpp.
References _currentSegment, _experimentOffset, and rcSegmentImpl::start().
Referenced by rcGraphicsSegmentIteratorImpl::getSegmentStartAbsolute(), rcScalarSegmentIteratorImpl::getSegmentStartAbsolute(), rcPositionSegmentIteratorImpl::getSegmentStartAbsolute(), and rcVideoSegmentIteratorImpl::getSegmentStartAbsolute().
 {
     return _experimentOffset + _currentSegment.start();
 }
rcTimestamp rcSegmentIteratorImpl::getTrackOffset (void) virtual
Implements rcSegmentIterator.
Definition at line 84 of file rc_segmentimpl.cpp.
References _position.
Referenced by rcGraphicsSegmentIteratorImpl::getTrackOffset(), rcScalarSegmentIteratorImpl::getTrackOffset(), rcPositionSegmentIteratorImpl::getTrackOffset(), and rcVideoSegmentIteratorImpl::getTrackOffset().
 {
     return _position;
 }
bool rcSegmentIteratorImpl::hasNextSegment (bool lock = true) virtual
Implements rcSegmentIterator.
Definition at line 90 of file rc_segmentimpl.cpp.
References _mutex, _segmentIndex, _track, lock(), and rcTrackImpl::segments().
Referenced by rcGraphicsSegmentIteratorImpl::hasNextSegment(), rcScalarSegmentIteratorImpl::hasNextSegment(), rcPositionSegmentIteratorImpl::hasNextSegment(), and rcVideoSegmentIteratorImpl::hasNextSegment().
 {
     if ( lock ) {
         rcLock lock (_mutex);
         int nSegments = _track->segments();
         return _segmentIndex < (nSegments - 1);
     } else {
         int nSegments = _track->segments();
         return _segmentIndex < (nSegments - 1);
     }
 }
void rcSegmentIteratorImpl::lock () virtual
Implements rcSegmentIterator.
Definition at line 220 of file rc_segmentimpl.cpp.
References _mutex, and rcMutex::lock().
Referenced by advance(), getSegmentCount(), hasNextSegment(), rcGraphicsSegmentIteratorImpl::lock(), rcScalarSegmentIteratorImpl::lock(), rcPositionSegmentIteratorImpl::lock(), rcVideoSegmentIteratorImpl::lock(), rcGraphicsSegmentIteratorImpl::reset(), rcScalarSegmentIteratorImpl::reset(), rcPositionSegmentIteratorImpl::reset(), and rcVideoSegmentIteratorImpl::reset().
 {
     _mutex.lock();
 }
rcMutex & rcSegmentIteratorImpl::mutex (void)
Definition at line 268 of file rc_segmentimpl.cpp.
References _mutex.
Referenced by rcGraphicsSegmentIteratorImpl::advance(), rcScalarSegmentIteratorImpl::advance(), rcPositionSegmentIteratorImpl::advance(), rcVideoSegmentIteratorImpl::advance(), rcGraphicsSegmentIteratorImpl::rcGraphicsSegmentIteratorImpl(), rcPositionSegmentIteratorImpl::rcPositionSegmentIteratorImpl(), rcScalarSegmentIteratorImpl::rcScalarSegmentIteratorImpl(), and rcVideoSegmentIteratorImpl::rcVideoSegmentIteratorImpl().
 {
     return _mutex;
 }
void rcSegmentIteratorImpl::release (void) virtual
Implements rcSegmentIterator.
Definition at line 260 of file rc_segmentimpl.cpp.
 {
     delete this;
 }
void rcSegmentIteratorImpl::reset (bool lock = true) virtual
Implements rcSegmentIterator.
Definition at line 232 of file rc_segmentimpl.cpp.
References _currentSegment, _mutex, _position, _segmentIndex, _segmentOffset, _track, advanceNoLock(), cZeroTime, rcExperimentDomainFactory::getExperimentDomain(), rcExperimentDomain::getExperimentStart(), rcTrackImpl::getTrackStart(), rcMutex::lock(), rcSegmentImpl::setLength(), and rcMutex::unlock().
Referenced by rcGraphicsSegmentIteratorImpl::reset(), rcScalarSegmentIteratorImpl::reset(), rcPositionSegmentIteratorImpl::reset(), and rcVideoSegmentIteratorImpl::reset().
 {
     rcExperimentDomain* domain = rcExperimentDomainFactory::getExperimentDomain();
     const rcTimestamp expStart = domain->getExperimentStart();
     rcTimestamp trackStart = _track->getTrackStart();
     rcTimestamp position = expStart - trackStart;
     if ( lock )
         _mutex.lock();
     _segmentIndex = -1;
     _currentSegment = rcSegmentImpl( cZeroTime, cZeroTime, rcRect() );
     _segmentOffset = cZeroTime;
     // handle case where position is negative - act like there's
     // a dummy segment before the first real data segment
     if ( position < cZeroTime ) {
         _position = position;
         _currentSegment.setLength( position );
     } else {
         _position = cZeroTime;
         advanceNoLock( position );
     }
     if ( lock )
         _mutex.unlock();
 }
void rcSegmentIteratorImpl::unlock () virtual
Implements rcSegmentIterator.
Definition at line 226 of file rc_segmentimpl.cpp.
References _mutex, and rcMutex::unlock().
Referenced by rcGraphicsSegmentIteratorImpl::reset(), rcScalarSegmentIteratorImpl::reset(), rcPositionSegmentIteratorImpl::reset(), rcVideoSegmentIteratorImpl::reset(), rcGraphicsSegmentIteratorImpl::unlock(), rcScalarSegmentIteratorImpl::unlock(), rcPositionSegmentIteratorImpl::unlock(), and rcVideoSegmentIteratorImpl::unlock().
 {
     _mutex.unlock();
 }
Member Data Documentation
rcSegmentImpl rcSegmentIteratorImpl::_currentSegment protected
Definition at line 131 of file rc_segmentimpl.h.
Referenced by advanceNoLock(), contains(), findClosestSegment(), getFocus(), getSegmentLength(), getSegmentStart(), getSegmentStartAbsolute(), rcSegmentIteratorImpl(), and reset().
rcTimestamp rcSegmentIteratorImpl::_experimentOffset protected
Definition at line 136 of file rc_segmentimpl.h.
Referenced by contains(), getSegmentStartAbsolute(), and rcSegmentIteratorImpl().
rcMutex& rcSegmentIteratorImpl::_mutex protected
Definition at line 134 of file rc_segmentimpl.h.
Referenced by advance(), getSegmentCount(), hasNextSegment(), lock(), mutex(), reset(), and unlock().
rcTimestamp rcSegmentIteratorImpl::_position protected
Definition at line 130 of file rc_segmentimpl.h.
Referenced by advanceNoLock(), getTrackOffset(), rcSegmentIteratorImpl(), and reset().
int32 rcSegmentIteratorImpl::_segmentIndex protected
Definition at line 132 of file rc_segmentimpl.h.
Referenced by advanceNoLock(), getSegmentIndex(), hasNextSegment(), rcSegmentIteratorImpl(), and reset().
rcTimestamp rcSegmentIteratorImpl::_segmentOffset protected
Definition at line 133 of file rc_segmentimpl.h.
Referenced by advanceNoLock(), getSegmentOffset(), rcSegmentIteratorImpl(), and reset().
rcTrackImpl* rcSegmentIteratorImpl::_track protected
Definition at line 135 of file rc_segmentimpl.h.
Referenced by advanceNoLock(), findClosestSegment(), getSegmentCount(), hasNextSegment(), rcSegmentIteratorImpl(), and reset().
The documentation for this class was generated from the following files:
include/visiCore/rc_segmentimpl.h
src/visible/src/rc_segmentimpl.cpp