Visible: rcInfLine Class Reference
rcInfLine Class Reference
#include <include/util/rc_line.h>
Public Member Functions
rcInfLine ()
rcInfLine (const rc2Dvector &dir, const rc2Dvector &pos)
rcInfLine (const rcRadian &t, const rc2Dvector &pos)
rcInfLine (const rc2Dvector &v)
const rc2Dvector & dir () const
const rc2Dvector & pos () const
rc2Dvector & dir ()
rc2Dvector & pos ()
rcInfLine transform (const rc2Xform &c) const
void transform (const rc2Xform &c, rcInfLine &result) const
double toPoint (const rc2Dvector &v) const
rcRadian angle () const
void angle (rcRadian a)
rcInfLine parallel (const rc2Dvector &) const
bool isParallel (const rcInfLine &l) const
rcRadian angle (const rcInfLine &) const
rc2Dvector intersect (const rcInfLine &, bool isPar) const
rcInfLine normal (const rc2Dvector &) const
rc2Dvector project (const rc2Dvector &) const
double offset (const rc2Dvector &) const
bool operator== (const rcInfLine &) const
bool operator!= (const rcInfLine &) const
Private Attributes
rc2Dvector mDir
rc2Dvector mPos
Detailed Description
Definition at line 169 of file rc_line.h.
Constructor & Destructor Documentation
rcInfLine::rcInfLine () inline
Definition at line 172 of file rc_line.h.
Referenced by normal(), parallel(), and transform().
 : mDir(1.,0.), mPos(0.,0.) {}
rcInfLine::rcInfLine (const rc2Dvector & dir, const rc2Dvector & pos)
Definition at line 33 of file rc_line.cpp.
References mDir, rc2dVector< T >::x(), and rc2dVector< T >::y().
   : mDir(dir),  mPos(pos)
 {
   if (mDir.x() == 0 && mDir.y() == 0)
     throw general_exception ("bad rcInfLine ctor");
 }
rcInfLine::rcInfLine (const rcRadian & t, const rc2Dvector & pos)
Definition at line 40 of file rc_line.cpp.
   : mDir(cos(t),sin(t)),  mPos(pos)
 {
 }
rcInfLine::rcInfLine (const rc2Dvector & v)
Definition at line 45 of file rc_line.cpp.
References mDir, rc2dVector< T >::x(), and rc2dVector< T >::y().
   : mDir(v.unit()), mPos(v)
 {
   if (mDir.x() == 0 && mDir.y() == 0)
     throw general_exception ("bad rcInfLine ctor");
 }
Member Function Documentation
rcRadian rcInfLine::angle () const inline
Definition at line 203 of file rc_line.h.
References rc2dVector< T >::angle(), and dir().
Referenced by angle().
 { return dir().angle(); }
void rcInfLine::angle (rcRadian a) inline
Definition at line 206 of file rc_line.h.
References cos(), mDir, sin(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 { mDir.x(cos(a)); mDir.y(sin(a)); }
rcRadian rcInfLine::angle (const rcInfLine & l) const
Definition at line 69 of file rc_line.cpp.
References angle().
 {
   return (l.angle() - angle()).normSigned();
 }
const rc2Dvector& rcInfLine::dir () const inline
Definition at line 191 of file rc_line.h.
References mDir.
Referenced by angle(), intersect(), isParallel(), normal(), offset(), parallel(), project(), toPoint(), and transform().
 { return mDir; }
rc2Dvector& rcInfLine::dir () inline
Definition at line 193 of file rc_line.h.
References mDir.
 { return mDir; }
rc2Dvector rcInfLine::intersect (const rcInfLine & l, bool isPar) const
Definition at line 74 of file rc_line.cpp.
References dir(), pos(), rfRealEq(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   isPar = false;
   double d = dir().x() * l.dir().y() - dir().y() * l.dir().x();
   isPar = rfRealEq (d, 0.0);
   if (isPar) return rc2Dvector ();
   double s = ((l.pos().x() - pos().x()) * l.dir().y() -
           (l.pos().y() - pos().y()) * l.dir().x()) / d;
   return rc2Dvector((dir() * s) + pos());
 }
bool rcInfLine::isParallel (const rcInfLine & l) const
Definition at line 88 of file rc_line.cpp.
References dir(), rmABS, rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   double d = dir().x() * l.dir().y() - dir().y() * l.dir().x();
   return rmABS (d) < 1e-12;
 }
rcInfLine rcInfLine::normal (const rc2Dvector & p) const inline
Definition at line 23 of file rc_line.cpp.
References dir(), and rcInfLine().
 { return rcInfLine(rc2Dvector(-dir().y(), dir().x()), p); }
double rcInfLine::offset (const rc2Dvector & p) const
Definition at line 99 of file rc_line.cpp.
References dir(), and pos().
 {
   return (p - pos()) * dir();
 }
bool rcInfLine::operator!= (const rcInfLine & l) const inline
Definition at line 29 of file rc_line.cpp.
 { return !(*this == l); }
bool rcInfLine::operator== (const rcInfLine & l) const inline
Definition at line 26 of file rc_line.cpp.
References mDir, and mPos.
 { return mDir == l.mDir && mPos == l.mPos; }
rcInfLine rcInfLine::parallel (const rc2Dvector & p) const inline
Definition at line 20 of file rc_line.cpp.
References dir(), and rcInfLine().
 { return rcInfLine(dir(), p); }
const rc2Dvector& rcInfLine::pos () const inline
Definition at line 192 of file rc_line.h.
References mPos.
Referenced by intersect(), offset(), project(), toPoint(), and transform().
 { return mPos; }
rc2Dvector& rcInfLine::pos () inline
Definition at line 194 of file rc_line.h.
References mPos.
 { return mPos; }
rc2Dvector rcInfLine::project (const rc2Dvector & p) const
Definition at line 94 of file rc_line.cpp.
References dir(), and pos().
 {
   return (dir() * ((p - pos()) * dir())) + pos();
 }
double rcInfLine::toPoint (const rc2Dvector & v) const
Definition at line 63 of file rc_line.cpp.
References dir(), pos(), rmABS, rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   return rmABS ((p.x()-pos().x()) * -dir().y() +
          (p.y()-pos().y()) *  dir().x());
 }
rcInfLine rcInfLine::transform (const rc2Xform & c) const
Definition at line 52 of file rc_line.cpp.
References dir(), rc2Xform::mapPoint(), rc2Xform::mapVector(), pos(), rcInfLine(), and rc2dVector< T >::unit().
 {
   return rcInfLine(c.mapVector(dir()).unit(), c.mapPoint(pos()));
 }
void rcInfLine::transform (const rc2Xform & c, rcInfLine & result) const
Definition at line 57 of file rc_line.cpp.
References dir(), rc2Xform::mapPoint(), rc2Xform::mapVector(), pos(), and rc2dVector< T >::unit().
 {
   result.dir() = c.mapVector(dir()).unit();
   result.pos() = c.mapPoint(pos());
 }
Member Data Documentation
rc2Dvector rcInfLine::mDir private
Definition at line 235 of file rc_line.h.
Referenced by angle(), dir(), operator==(), and rcInfLine().
rc2Dvector rcInfLine::mPos private
Definition at line 235 of file rc_line.h.
Referenced by operator==(), and pos().
The documentation for this class was generated from the following files:
include/util/rc_line.h
src/util/code/rc_line.cpp