Visible: imtext Class Reference
imtext Class Reference
#include <include/stlplus/multiio.hpp>
Public Member Functions
imtext (void)
imtext (const itext &)
imtext (const itext &, const itext &)
void open (const itext &)
void open (const itext &, const itext &)
unsigned add (const itext &)
void remove (unsigned)
unsigned device_count (void) const
itext & device_get (unsigned)
const itext & device_get (unsigned) const
Public Member Functions inherited from itext
itext (void)
itext (ibuff *)
virtual ~itext (void)
bool initialised (void) const
void open (ibuff *)
void close (void)
itext (const itext &)
itext & operator= (const itext &)
bool error (void) const
int error_number (void) const
std::string error_string (void) const
void set_error (int error)
void clear_error (void)
void set_newline_mode (newline_t newline=convert_mode)
void set_convert_mode (void)
void set_binary_mode (void)
newline_t newline_mode (void) const
bool is_convert_mode (void)
bool is_binary_mode (void)
bool eof (void)
bool eoln (void)
int peek (void)
int get (void)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
bool good (void)
operator bool (void)
bool operator! (void)
itext & operator>> (char &)
itext & operator>> (signed char &)
itext & operator>> (unsigned char &)
itext & operator>> (std::string &)
bool getline (std::string &line)
itext & operator>> (std::vector< std::string > &)
itext & operator>> (bool &)
itext & operator>> (short &)
itext & operator>> (unsigned short &)
itext & operator>> (int &)
itext & operator>> (unsigned int &)
itext & operator>> (long &)
itext & operator>> (unsigned long &)
itext & operator>> (float &)
itext & operator>> (double &)
itext & operator>> (void *&)
itext & operator>> (manipulator_function)
itext & operator>> (otext &)
Additional Inherited Members
Public Types inherited from itext
enum newline_t { binary_mode, convert_mode }
typedef void(* manipulator_function)(itext &)
Protected Attributes inherited from itext
ibuff * m_buffer
Detailed Description
Definition at line 37 of file multiio.hpp.
Constructor & Destructor Documentation
imtext::imtext (void)
Definition at line 84 of file multiio.cpp.
                    : itext(new imbuff())
 {
 }
imtext::imtext (const itext & str)
Definition at line 88 of file multiio.cpp.
References add().
                                : itext(new imbuff())
 {
   add(str);
 }
imtext::imtext (const itext & str1, const itext & str2)
Definition at line 93 of file multiio.cpp.
References add().
                                                    : itext(new imbuff())
 {
   add(str1);
   add(str2);
 }
Member Function Documentation
unsigned imtext::add (const itext & str)
Definition at line 112 of file multiio.cpp.
References imbuff::add(), DEBUG_ASSERT, and itext::m_buffer.
Referenced by imtext(), and open().
 {
   imbuff* buf = dynamic_cast<imbuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf ? buf->add(str) : (unsigned)-1;
 }
unsigned imtext::device_count (void) const
Definition at line 126 of file multiio.cpp.
References imbuff::count(), DEBUG_ASSERT, and itext::m_buffer.
 {
   const imbuff* buf = dynamic_cast<const imbuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf ? buf->count() : 0;
 }
itext & imtext::device_get (unsigned i)
Definition at line 133 of file multiio.cpp.
References DEBUG_ASSERT, imbuff::device(), and itext::m_buffer.
 {
   imbuff* buf = dynamic_cast<imbuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf->device(i);
 }
const itext & imtext::device_get (unsigned i) const
Definition at line 140 of file multiio.cpp.
References DEBUG_ASSERT, imbuff::device(), and itext::m_buffer.
 {
   const imbuff* buf = dynamic_cast<const imbuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   return buf->device(i);
 }
void imtext::open (const itext & str)
Definition at line 99 of file multiio.cpp.
References add(), and itext::open().
 {
   itext::open(new imbuff());
   add(str);
 }
void imtext::open (const itext & str1, const itext & str2)
Definition at line 105 of file multiio.cpp.
References add(), and itext::open().
 {
   itext::open(new imbuff());
   add(str1);
   add(str2);
 }
void imtext::remove (unsigned offset)
Definition at line 119 of file multiio.cpp.
References DEBUG_ASSERT, itext::m_buffer, and imbuff::remove().
 {
   imbuff* buf = dynamic_cast<imbuff*>(m_buffer);
   DEBUG_ASSERT(buf);
   if (buf) buf->remove(offset);
 }
The documentation for this class was generated from the following files:
include/stlplus/multiio.hpp
include/stlplus/multiio.cpp