Visible: rcRadian Class Reference
rcRadian Class Reference
#include <include/util/rc_math.h>
Public Member Functions
rcRadian ()
rcRadian (double a)
rcRadian operator+ (rcRadian a) const
rcRadian operator- (rcRadian a) const
rcRadian operator* (double a) const
rcRadian operator/ (double a) const
rcRadian operator- () const
double operator* (rcRadian a) const
double operator/ (rcRadian a) const
double Double () const
double basic () const
rcRadian & operator= (double a)
rcRadian & operator*= (double a)
rcRadian & operator/= (double a)
rcRadian & operator*= (rcRadian a)
rcRadian & operator/= (rcRadian a)
rcRadian & operator+= (rcRadian a)
rcRadian & operator-= (rcRadian a)
bool operator== (rcRadian a) const
bool operator!= (rcRadian a) const
bool operator< (rcRadian a) const
bool operator<= (rcRadian a) const
bool operator> (rcRadian a) const
bool operator>= (rcRadian a) const
rcRadian (rcDegree)
rcRadian (rcAngle8)
rcRadian (rcAngle16)
rcRadian norm () const
rcRadian normSigned () const
Private Attributes
double val
Friends
rcRadian operator* (double a, rcRadian b)
Detailed Description
Definition at line 247 of file rc_math.h.
Constructor & Destructor Documentation
rcRadian::rcRadian () inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian::rcRadian (double a) inline explicit
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian::rcRadian (rcDegree x) inline
Definition at line 358 of file rc_math.h.
 { return rcRadian (acos (x));}
rcRadian::rcRadian (rcAngle8 x) inline
Definition at line 360 of file rc_math.h.
 { return rcRadian (acos (x));}
rcRadian::rcRadian (rcAngle16 x) inline
Definition at line 361 of file rc_math.h.
 { return rcRadian (acos (x));}
Member Function Documentation
double rcRadian::basic () const inline
Definition at line 249 of file rc_math.h.
Referenced by rcMathematicalImage::mMakeField(), rcValue::rcValue(), and rcAffineWindow::vImageTransform().
 :
inline rcRadian (rcDegree);
double rcRadian::Double () const inline
Definition at line 249 of file rc_math.h.
Referenced by abs(), rcMotionPath::add(), cos(), rcPolygon::genMinEnclosingRect(), sin(), and tan().
 :
inline rcRadian (rcDegree);
rcRadian rcRadian::norm () const
Definition at line 70 of file rc_units.cpp.
References rkPI, and val.
Referenced by rcPolygon::genMinEnclosingRect(), normSigned(), and rcEllipse::unit().
 {
   rcRadian r;
   r.val = fmod (val, 2 * rkPI);
   if (r.val < 0.) r.val += 2 * rkPI;
   return r;
 }
rcRadian rcRadian::normSigned () const
Definition at line 93 of file rc_units.cpp.
References norm(), rkPI, and val.
Referenced by rcVisualFunction::beatProcess().
 {
   rcRadian r;
   r = norm();
   if (r.val < 2 * rkPI - r.val)
     return r;
   r.val = r.val - 2 * rkPI;
   return r;
 }
bool rcRadian::operator!= (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian rcRadian::operator* (double a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
double rcRadian::operator* (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator*= (double a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator*= (rcRadian a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian rcRadian::operator+ (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator+= (rcRadian a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian rcRadian::operator- (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian rcRadian::operator- () const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator-= (rcRadian a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian rcRadian::operator/ (double a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
double rcRadian::operator/ (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator/= (double a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator/= (rcRadian a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
bool rcRadian::operator< (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
bool rcRadian::operator<= (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
rcRadian& rcRadian::operator= (double a) inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
bool rcRadian::operator== (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
bool rcRadian::operator> (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
bool rcRadian::operator>= (rcRadian a) const inline
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
Friends And Related Function Documentation
rcRadian operator* (double a, rcRadian b) friend
Definition at line 249 of file rc_math.h.
 :
inline rcRadian (rcDegree);
Member Data Documentation
double rcRadian::val private
Definition at line 249 of file rc_math.h.
Referenced by norm(), and normSigned().
The documentation for this class was generated from the following files:
include/util/rc_math.h
src/util/code/rc_units.cpp