Visible: rcTrackManager Class Reference
rcTrackManager Class Reference
#include <include/visUI/rc_trackmanager.h>
Classes
class rcTrackInfoVector
Public Types
enum rcCutFormat { eBasic, eMathematica, eTrackScript }
Public Slots
void updateState (rcExperimentState state)
void addTracks (void)
void setColors ()
void rebuildTracks ()
Signals
void trackhighlighted (void)
Public Member Functions
rcTrackInfo getTrackInfo (int trackGroupNo, int trackNo)
bool isHiliteTrack (int trackGroupNo, int trackNo)
void setHiliteTrack (int trackGroupNo, int trackNo, bool update=true)
QPen getTrackPen (int trackGroupNo, int trackNo)
void setTrackPen (int trackGroupNo, int trackNo, const QPen &pen)
bool isTrackEnabled (int trackGroupNo, int trackNo)
void setTrackEnabled (int trackGroupNo, int trackNo, bool isEnabled)
void setTrackEnabled (rcTrackType type, bool isEnabled)
void setTrackEnabled (rcWriterSemantics type, bool isEnabled)
bool isTrackGroupEnabled (int trackGroupNo)
void setTrackGroupEnabled (int trackGroupNo, bool isEnabled)
rcGroupSemantics groupType (int trackGroupNo)
void setTrackColor (rcTrackInfo &trackInfo)
rcTrack * getHiliteTrack () const
void copyTrackToClipboard (rcTrack *track, rcCutFormat cf=eBasic)
void reportTrackHighLighted (void) const
Static Public Member Functions
static rcTrackManager * getTrackManager (void)
static bool displayableTrack (rcTrack *track)
static bool monitorableTrack (rcTrack *track)
static bool hasManageableTracks (int group)
static bool hasManageableTracks (int group, bool cameraInput, bool cameraStorage)
Private Member Functions
rcTrackManager (QObject *parent=0, const char *name=0)
void setTrackInfo (int trackGroupNo, int trackNo, const rcTrackInfo &info)
void hiliteTracks (void)
Private Attributes
deque< rcTrackInfoVector > _trackInfo
deque< bool > _groupEnabled
deque< QPen > _defaultPens
int _hiliteTrackGroup
int _hiliteTrack
Friends
class rcTrackInfo
Detailed Description
Definition at line 62 of file rc_trackmanager.h.
Member Enumeration Documentation
enum rcTrackManager::rcCutFormat
Enumerator
eBasic
eMathematica
eTrackScript
Definition at line 70 of file rc_trackmanager.h.
   {
     eBasic,
     eMathematica,
     eTrackScript
   };
Constructor & Destructor Documentation
rcTrackManager::rcTrackManager (QObject * parent = 0, const char * name = 0) private
Definition at line 35 of file rc_trackmanager.cpp.
References _defaultPens, addTracks(), rcModelDomain::getModelDomain(), rebuildTracks(), rmAssert, and updateState().
Referenced by getTrackManager().
         : QObject( parent , name ),  _hiliteTrackGroup( -1 ), _hiliteTrack( -1 )
 {
     // Default pens for tracks
     _defaultPens.push_back( QPen( QColor("black") ) );
     _defaultPens.push_back( QPen( QColor("magenta") ) );
     _defaultPens.push_back( QPen( QColor("darkRed") ) );
     _defaultPens.push_back( QPen( QColor("darkBlue") ) );
     _defaultPens.push_back( QPen( QColor("darkGreen") ) );
     _defaultPens.push_back( QPen( QColor("darkCyan") ) );
     _defaultPens.push_back( QPen( QColor("darkMagenta") ) );
     _defaultPens.push_back( QPen( QColor("darkGray") ) );
     rmAssert( !_defaultPens.empty() );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( elapsedTime( const rcTimestamp& ) ) ,
              this   , SLOT( addTracks( void ) ) );
     connect( domain , SIGNAL( cursorTime( const rcTimestamp& ) ) ,
              this   , SLOT( addTracks( void  ) ) );
     connect( domain , SIGNAL( updateTimelineRange( const rcTimestamp&, const rcTimestamp& ) ) ,
              this   , SLOT( addTracks( void  ) ) );
     connect( domain , SIGNAL( updateSettings( void ) ) ,
              this   , SLOT( addTracks( void ) ) );
     connect( domain , SIGNAL( updateDebugging( void ) ) ,
              this   , SLOT( rebuildTracks( void ) ) );
 }
Member Function Documentation
void rcTrackManager::addTracks (void) slot
Definition at line 286 of file rc_trackmanager.cpp.
References _defaultPens, _groupEnabled, _trackInfo, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getNTrackGroups(), rcTrackGroup::getNTracks(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrack::getTrackType(), and setTrackColor().
Referenced by getTrackInfo(), rcTrackManager(), rebuildTracks(), setTrackInfo(), and updateState().
 {
     int i;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     // first see if we need to add track groups
     const int nTrackGroups = experiment->getNTrackGroups();
     const int nManagedTrackGroups = _trackInfo.size();
     for (i = nManagedTrackGroups; i < nTrackGroups; ++i)
     {
         rcTrackInfoVector newVector;
         _trackInfo.push_back( newVector );
         _groupEnabled.push_back( true );
     }
     // now go through each group and see if new tracks were added
     for (i = 0; i < nTrackGroups; ++i)
     {
         rcTrackGroup* trackGroup = experiment->getTrackGroup( i );
         const int nTracks = trackGroup->getNTracks();
         const rcTrackInfoVector& ti = _trackInfo[ i ];
         const int nManagedTracks = ti.size();
         for (int j = nManagedTracks; j < nTracks; ++j)
         {
             rcTrack* track = trackGroup->getTrack( j );
             QPen pen( _defaultPens[ j % _defaultPens.size() ] );
             pen.setJoinStyle( Qt::RoundJoin );
             rcTrackInfo newInfo( true, pen, track->getTrackType(), track );
             setTrackColor( newInfo );
             _trackInfo[ i ].push_back( newInfo );
         }
     }
 }
void rcTrackManager::copyTrackToClipboard (rcTrack * track, rcCutFormat cf = eBasic)
Definition at line 482 of file rc_trackmanager.cpp.
References rcSegmentIterator::advance(), eMathematica, endl(), eScalarTrack, rcScalarTrack::getDataSegmentIterator(), rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcTrack::getName(), rcSegmentIterator::getSegmentIndex(), rcTrack::getTrackType(), rcScalarSegmentIterator::getValue(), rcSegmentIterator::hasNextSegment(), rcExperimentAttributes::inputName, rcSegmentIterator::lock(), rcExperimentAttributes::title, and rcSegmentIterator::unlock().
Referenced by rcScalarTrackWidget::keyPressEvent(), and rcTimeline::keyPressEvent().
 {
     if ( track && track->getTrackType() == eScalarTrack ) {
         rcModelDomain* domain = rcModelDomain::getModelDomain();
         std::string experimentName = domain->getExperimentAttributes().title;
         // Copy to clipboard
         rcScalarTrack* scalarTrack = dynamic_cast<rcScalarTrack*>( track );
         if (scalarTrack == 0)
             return;
         strstream s;
         rcScalarSegmentIterator* iter = scalarTrack->getDataSegmentIterator( 0.0 );
         bool nextSegment = true;
         uint32 values = 0;
         // Output with high accuracy
         s.precision( 12 );
     s.setf (ios::fixed);
     //@note create util function or use boost
     if (cf == eMathematica)
       {
         std::string iname = domain->getExperimentAttributes().inputName;
         std::string slash( "/" );
         uint32 sl = iname.find_last_of( slash );
         uint32 len (0);
         if ( sl != std::string::npos )
           len = iname.size() - sl - 1;
         if ( len > 0 )
           s << "{" << iname.substr( sl+1, len ) << "}" << endl;
         else
           s << "{" << experimentName << "}" << endl;
       }
     else
       s << experimentName << endl << track->getName() << endl;
         if ( iter->getSegmentIndex() == -1 ) {
             // No valid value at curPos, advance one
             nextSegment = iter->advance( 1 );
         }
         if ( nextSegment ) {
             ++values;
     if (cf == eMathematica)
       s << "{" << iter->getValue() << "," << endl;
     else
       s << iter->getValue() << endl;
             // Lock iterator for the total duration of value access
             iter->lock();
             // Copy all values separated by a newline
             while ( nextSegment ) {
                 // Get next segment
                 nextSegment = iter->advance( 1, false ); // Unlocked advance for speed
                 if ( nextSegment ) {
                     ++values;
             if (cf == eMathematica && iter->hasNextSegment (false))
               s << iter->getValue() << "," << endl;
             else
               s << iter->getValue() << endl;
                 }
             }
         if (cf == eMathematica)
           s << "};" << endl;
             iter->unlock();
         }
         delete iter;
         s << ends;
         s.freeze(); // Without freeze(), strstream::str() leaks the string it returns
         QClipboard *cb = QApplication::clipboard();
         cb->setText( s.str() );
         cerr << "Copied " << values << " values from experiment \"" << experimentName << "\" track \"" << track->getName()
              << "\" to clipboard";
     if (cf == eMathematica) cerr << " (Mathematica Format) " << endl;
     else cerr << endl;
     }
 }
bool rcTrackManager::displayableTrack (rcTrack * track) static
Definition at line 568 of file rc_trackmanager.cpp.
References eGraphicsTrack, eScalarTrack, eVideoTrack, eWriterGraphicsDevelopment, eWriterUnknown, eWriterVideoDevelopment, gDeveloperDebugging, rcTrack::getTag(), rcTrack::getTrackType(), and rcWriterManager::tagType().
Referenced by hasManageableTracks(), monitorableTrack(), and rcTrackGroupWidget::rcTrackGroupWidget().
 {
     bool managed = false;
     rcWriterSemantics blockedVideoTrack = eWriterVideoDevelopment;
     rcWriterSemantics blockedGraphicsTrack = eWriterGraphicsDevelopment;
     if ( gDeveloperDebugging ) {
         blockedVideoTrack = eWriterUnknown;
         blockedGraphicsTrack = eWriterUnknown;
     }
     switch ( track->getTrackType() ) {
         case eScalarTrack:
             managed = true;
             break;
         case eVideoTrack:
             if ( rcWriterManager::tagType( track->getTag() ) != blockedVideoTrack ) {
                 managed = true;
             }
             break;
         case eGraphicsTrack:
             if ( rcWriterManager::tagType( track->getTag() ) != blockedGraphicsTrack ) {
                 managed = true;
             }
             break;
         default:
             break;
     }
     return managed;
 }
rcTrack * rcTrackManager::getHiliteTrack () const
Definition at line 467 of file rc_trackmanager.cpp.
References _hiliteTrack, _hiliteTrackGroup, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getTrack(), and rcExperiment::getTrackGroup().
Referenced by rcScalarTrackWidget::keyPressEvent(), and rcTimeline::keyPressEvent().
 {
     if ( _hiliteTrackGroup >= 0 && _hiliteTrack >= 0 ) {
         rcModelDomain* domain = rcModelDomain::getModelDomain();
         rcExperiment* experiment = domain->getExperiment();
         rcTrackGroup* trackGroup = experiment->getTrackGroup( _hiliteTrackGroup );
         return trackGroup->getTrack( _hiliteTrack );
     }
     return 0;
 }
rcTrackInfo rcTrackManager::getTrackInfo (int trackGroupNo, int trackNo)
Definition at line 68 of file rc_trackmanager.cpp.
References rcTrackInfo::_isEnabled, _trackInfo, addTracks(), and endl().
Referenced by rcMonitor::displayTrackFocus(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), getTrackPen(), isTrackEnabled(), rcTrackRenderInfo::rcTrackRenderInfo(), rcScalarTrackWidget::setEnabled(), setHiliteTrack(), setTrackEnabled(), and setTrackPen().
 {
     if ( static_cast<unsigned>(trackGroupNo) < _trackInfo.size() ) {
         const rcTrackInfoVector& ti = _trackInfo[ trackGroupNo ];
         if ( static_cast<unsigned>(trackNo) < ti.size() ) {
             return ti[ trackNo ];
         }
     }
     // Someone is requesting a non-existent track, maybe this will add it
     addTracks();
     // Try again
     if ( static_cast<unsigned>(trackGroupNo) < _trackInfo.size() ) {
         const rcTrackInfoVector& ti = _trackInfo[ trackGroupNo ];
         if ( static_cast<unsigned>(trackNo) < ti.size() ) {
             return ti[ trackNo ];
         }
     }
     // Requesting a track that doesn't exist, return a dummy
     cerr << "rcTrackManager::getTrackInfo error: element [" << trackGroupNo << "," << trackNo << "] ";
     cerr << "requested, array size is [" << _trackInfo.size() << "," << (_trackInfo.size() ? _trackInfo[ trackGroupNo ].size() : 0) << "]";
     cerr << endl;
     rcTrackInfo empty;
     empty._isEnabled = false;
     return empty;
 }
rcTrackManager * rcTrackManager::getTrackManager (void) static
Definition at line 24 of file rc_trackmanager.cpp.
References _trackManager, and rcTrackManager().
Referenced by countDisplayableGroups(), rcMonitor::displayTrackFocus(), rcImageCanvasGL::enableCellGroup(), rcMonitor::gatherDevelopmentTrackData(), rcMonitor::gatherTrackData(), rcScalarTrackWidget::keyPressEvent(), rcTimeline::keyPressEvent(), rcScalarTrackWidget::mousePressEvent(), rcMonitor::mouseReleaseEvent(), rcScalarTrackWidget::rcScalarTrackWidget(), rcTrackGroupWidget::rcTrackGroupWidget(), rcTrackRenderInfo::rcTrackRenderInfo(), rcScalarTrackWidget::setEnabled(), rcTrackGroupWidget::setEnabled(), rcScalarTrackWidget::updateSettings(), rcTrackGroupWidget::updateSettings(), rcCellInfoWidget::updateTrackDisplay(), and rcScalarTrackWidget::updateTrackDisplay().
 {
     if (_trackManager == 0) {
         _trackManager = new rcTrackManager();
     }
     return _trackManager;
 }
QPen rcTrackManager::getTrackPen (int trackGroupNo, int trackNo)
Definition at line 135 of file rc_trackmanager.cpp.
References rcTrackInfo::_pen, and getTrackInfo().
Referenced by rcScalarTrackWidget::rcScalarTrackWidget().
 {
     rcTrackInfo info = getTrackInfo( trackGroupNo , trackNo );
     return info._pen;
 }
rcGroupSemantics rcTrackManager::groupType (int trackGroupNo)
Definition at line 436 of file rc_trackmanager.cpp.
References eGroupSemanticsUnknown, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcExperiment::getTrackGroup(), and rcTrackGroup::getType().
Referenced by rcScalarTrackWidget::setEnabled().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackGroup* trackGroup = experiment->getTrackGroup( trackGroupNo );
     if ( trackGroup )
         return trackGroup->getType();
     return eGroupSemanticsUnknown;
 }
bool rcTrackManager::hasManageableTracks (int group) static
Definition at line 387 of file rc_trackmanager.cpp.
References rcModelDomain::getExperimentAttributes(), rcModelDomain::getModelDomain(), rcExperimentAttributes::liveInput, and rcExperimentAttributes::liveStorage.
Referenced by rcTrackPanel::updateTrackGroups().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     bool cameraInput = domain->getExperimentAttributes().liveInput;
     bool cameraStorage = domain->getExperimentAttributes().liveStorage;
     return hasManageableTracks( group, cameraInput, cameraStorage );
 }
bool rcTrackManager::hasManageableTracks (int group, bool cameraInput, bool cameraStorage) static
Definition at line 397 of file rc_trackmanager.cpp.
References displayableTrack(), eGroupSemanticsBodyMeasurements, eGroupSemanticsCameraPreview, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getNTracks(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), and rcTrackGroup::getType().
 {
     bool managed = false;
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackGroup* trackGroup = experiment->getTrackGroup( group );
     if ( cameraInput && !cameraStorage ) {
         // Camera input preview
         if ( trackGroup->getType() == eGroupSemanticsCameraPreview ) {
             const int nTracks = trackGroup->getNTracks();
             for ( int j = 0; j < nTracks; ++j) {
                 rcTrack* track = trackGroup->getTrack( j );
                 managed = displayableTrack( track );
                 if ( managed )
                     goto stop;
             }
         }
     } else {
         // File input or camera input save
         // Don't show cell group tracks in this widget
         if ( trackGroup->getType() != eGroupSemanticsBodyMeasurements &&
              trackGroup->getType() != eGroupSemanticsCameraPreview )
         {
             const int nTracks = trackGroup->getNTracks();
             for ( int j = 0; j < nTracks; ++j) {
                 rcTrack* track = trackGroup->getTrack( j );
                 managed = displayableTrack( track );
                 if ( managed )
                     goto stop;
             }
         }
     }
   stop:
     return managed;
 }
void rcTrackManager::hiliteTracks (void) private
Definition at line 350 of file rc_trackmanager.cpp.
References _trackInfo, eScalarTrack, rcModelDomain::getModelDomain(), rcTrackInfo::isEnabled(), rcModelDomain::notifyUpdateDisplay(), setHiliteTrack(), and rcTrackInfo::type().
Referenced by setTrackEnabled().
 {
 #if 0
     int enabledScalarTracks = 0;
     int lastEnabledGroup = -1;
     int lastEnabledScalarTrack = -1;
     // Count the number of enabled scalar tracks
     int nTrackGroups = _trackInfo.size();
     for (int i = 0; i < nTrackGroups; i++)
     {
         int nTracks = _trackInfo[ i ].size();
         for (int j = 0; j < nTracks; j++)
         {
             rcTrackInfo info = _trackInfo[ i ][ j ];
             if (info.isEnabled() && info.type() == eScalarTrack )
             {
                 ++enabledScalarTracks;
                 lastEnabledGroup = i;
                 lastEnabledScalarTrack = j;
             }
         }
     }
     if ( enabledScalarTracks == 1 ) {
         // Only one scalar track enabled, hilite it!
         setHiliteTrack( lastEnabledGroup , lastEnabledScalarTrack, false );
     } else {
         // Unhilite all
         setHiliteTrack( lastEnabledGroup , -1, false );
     }
     rcModelDomain::getModelDomain()->notifyUpdateDisplay();
 #endif
 }
bool rcTrackManager::isHiliteTrack (int trackGroupNo, int trackNo)
Definition at line 99 of file rc_trackmanager.cpp.
References _hiliteTrack, and _hiliteTrackGroup.
Referenced by rcScalarTrackWidget::rcScalarTrackWidget(), rcTrackRenderInfo::rcTrackRenderInfo(), setHiliteTrack(), setTrackEnabled(), and rcScalarTrackWidget::updateTrackDisplay().
 {
     return (_hiliteTrackGroup == trackGroupNo) && (_hiliteTrack == trackNo);
 }
bool rcTrackManager::isTrackEnabled (int trackGroupNo, int trackNo)
Definition at line 153 of file rc_trackmanager.cpp.
References rcTrackInfo::_isEnabled, and getTrackInfo().
Referenced by rcScalarTrackWidget::mousePressEvent(), rcScalarTrackWidget::rcScalarTrackWidget(), rcScalarTrackWidget::updateSettings(), and rcScalarTrackWidget::updateTrackDisplay().
 {
     rcTrackInfo info = getTrackInfo( trackGroupNo , trackNo );
     return info._isEnabled;
 }
bool rcTrackManager::isTrackGroupEnabled (int trackGroupNo)
Definition at line 236 of file rc_trackmanager.cpp.
References _groupEnabled.
Referenced by countDisplayableGroups(), rcTrackGroupWidget::rcTrackGroupWidget(), rcTrackRenderInfo::rcTrackRenderInfo(), rcTrackGroupWidget::updateSettings(), and rcCellInfoWidget::updateTrackDisplay().
 {
     return _groupEnabled[ trackGroupNo ];
 }
bool rcTrackManager::monitorableTrack (rcTrack * track) static
Definition at line 601 of file rc_trackmanager.cpp.
References displayableTrack(), eGraphicsTrack, eVideoTrack, and rcTrack::getTrackType().
Referenced by rcScalarTrackWidget::setEnabled().
 {
     if ( track->getTrackType() == eVideoTrack || track->getTrackType() == eGraphicsTrack )
         return displayableTrack( track );
     return false;
 }
void rcTrackManager::rebuildTracks (void) slot
Definition at line 343 of file rc_trackmanager.cpp.
References _trackInfo, addTracks(), and setColors().
Referenced by rcTrackManager().
 {
     _trackInfo.clear();
     addTracks();
     setColors();
 }
void rcTrackManager::reportTrackHighLighted (void) const
Definition at line 104 of file rc_trackmanager.cpp.
References trackhighlighted().
Referenced by setHiliteTrack().
 {
   emit const_cast<rcTrackManager *>(this)->trackhighlighted ();
 }
void rcTrackManager::setColors (void) slot
Definition at line 326 of file rc_trackmanager.cpp.
References _trackInfo, and setTrackColor().
Referenced by rebuildTracks(), and updateState().
 {
     // scan all tracks to update color
     for (uint32 i = 0; i < _trackInfo.size(); i++)
     {
         int nTracks = _trackInfo[ i ].size();
         rcTrackInfoVector& ti = _trackInfo[ i ];
         for (int j = 0; j < nTracks; j++)
         {
             rcTrackInfo& t = ti[j];
             setTrackColor( t );
         }
     }
 }
void rcTrackManager::setHiliteTrack (int trackGroupNo, int trackNo, bool update = true)
Definition at line 110 of file rc_trackmanager.cpp.
References _hiliteTrack, _hiliteTrackGroup, rcTrackInfo::_pen, _trackInfo, rcModelDomain::getModelDomain(), getTrackInfo(), isHiliteTrack(), rcModelDomain::notifyUpdateDisplay(), reportTrackHighLighted(), and setTrackInfo().
Referenced by hiliteTracks(), rcScalarTrackWidget::keyPressEvent(), rcScalarTrackWidget::mousePressEvent(), rcMonitor::mouseReleaseEvent(), and setTrackEnabled().
 {
     _hiliteTrackGroup = trackGroupNo;
     _hiliteTrack = trackNo;
     int nTrackGroups = _trackInfo.size();
     for (int i = 0; i < nTrackGroups; i++)
     {
         int nTracks = _trackInfo[ i ].size();
         for (int j = 0; j < nTracks; j++)
         {
             rcTrackInfo info = getTrackInfo( i , j );
             QPen pen = info._pen;
             pen.setWidth( isHiliteTrack( i, j ) ? 2 : 1 );
             info._pen = pen;
             setTrackInfo( i , j , info );
         }
     }
     reportTrackHighLighted ();
     if ( update )
         rcModelDomain::getModelDomain()->notifyUpdateDisplay();
 }
void rcTrackManager::setTrackColor (rcTrackInfo & trackInfo)
Definition at line 448 of file rc_trackmanager.cpp.
References rcTrackInfo::_pen, rcTrackInfo::_track, and rcTrack::getName().
Referenced by addTracks(), and setColors().
 {
     const char* name = trackInfo._track->getName();
     // FIXME: horrible hack, use semantic type or some track attribute or
     // at least STL string map
     if ( strstr( name, "[Red]" ) ) {
         trackInfo._pen.setColor( QColor("red") );
         //cerr << "setTrackColor red" << endl;
     } else if ( strstr( name, "[Green]" ) ) {
         trackInfo._pen.setColor( QColor("green") );
         //cerr << "setTrackColor green" << endl;
     } else if ( strstr( name, "[Blue]" ) ) {
         trackInfo._pen.setColor( QColor("blue") );
         //cerr << "setTrackColor blue" << endl;
     }
 }
void rcTrackManager::setTrackEnabled (int trackGroupNo, int trackNo, bool isEnabled)
Definition at line 161 of file rc_trackmanager.cpp.
References rcTrackInfo::_isEnabled, _trackInfo, getTrackInfo(), hiliteTracks(), isHiliteTrack(), setHiliteTrack(), and setTrackInfo().
Referenced by rcImageCanvasGL::enableCellGroup(), rcScalarTrackWidget::setEnabled(), rcTrackGroupWidget::setEnabled(), and setTrackEnabled().
 {
     if ( trackNo == -1 )
     {
         // Do all tracks
         int nTracks = _trackInfo[ trackGroupNo ].size();
         for (int i = 0; i < nTracks; i++)
         {
             rcTrackInfo info = getTrackInfo( trackGroupNo , i );
             info._isEnabled = isEnabled;
             setTrackInfo( trackGroupNo , i , info );
         }
     }
     else
     {
         // Do one track
         rcTrackInfo info = getTrackInfo( trackGroupNo , trackNo );
         info._isEnabled = isEnabled;
         setTrackInfo( trackGroupNo , trackNo , info );
         // If disabling a track, unhilite it, too
         if ( !isEnabled && isHiliteTrack( trackGroupNo , trackNo ) )
             setHiliteTrack( -1, false );
     }
     hiliteTracks();
 }
void rcTrackManager::setTrackEnabled (rcTrackType type, bool isEnabled)
Definition at line 188 of file rc_trackmanager.cpp.
References rcTrackInfo::_isEnabled, _trackInfo, getTrackInfo(), hiliteTracks(), setTrackInfo(), and rcTrackInfo::type().
 {
     // scan all tracks
     int nTrackGroups = _trackInfo.size();
     for (int i = 0; i < nTrackGroups; i++)
     {
         int nTracks = _trackInfo[ i ].size();
         for (int j = 0; j < nTracks; j++)
         {
             rcTrackInfo info = getTrackInfo( i , j );
             if (info.type() == type)
                 info._isEnabled = isEnabled;
             setTrackInfo( i , j , info );
         }
     }
     hiliteTracks();
 }
void rcTrackManager::setTrackEnabled (rcWriterSemantics type, bool isEnabled)
Definition at line 207 of file rc_trackmanager.cpp.
References _trackInfo, rcTrack::getTag(), getTrackInfo(), setTrackEnabled(), setTrackGroupEnabled(), rcWriterManager::tagType(), and rcTrackInfo::track().
 {
     // scan all tracks
     int nTrackGroups = _trackInfo.size();
     for (int i = 0; i < nTrackGroups; i++)
     {
         int nTracks = _trackInfo[ i ].size();
         for (int j = 0; j < nTracks; j++)
         {
             rcTrackInfo info = getTrackInfo( i , j );
             rcTrack* track = info.track();
             if ( track ) {
                 if ( rcWriterManager::tagType( track->getTag() ) == type ) {
                     // Enable group
                     setTrackGroupEnabled( i, isEnabled );
                     // enable/disable all tracks in a group
                     setTrackEnabled( i, -1, isEnabled );
                     // Break out
                     goto end;
                 }
             }
         }
       end:
         void(0);
     }
 }
void rcTrackManager::setTrackGroupEnabled (int trackGroupNo, bool isEnabled)
Definition at line 242 of file rc_trackmanager.cpp.
References _groupEnabled.
Referenced by rcImageCanvasGL::enableCellGroup(), rcScalarTrackWidget::setEnabled(), rcTrackGroupWidget::setEnabled(), and setTrackEnabled().
 {
     _groupEnabled[ trackGroupNo ] = isEnabled;
 }
void rcTrackManager::setTrackInfo (int trackGroupNo, int trackNo, const rcTrackInfo & info) private
Definition at line 264 of file rc_trackmanager.cpp.
References _trackInfo, addTracks(), and endl().
Referenced by setHiliteTrack(), setTrackEnabled(), and setTrackPen().
 {
      if ( static_cast<unsigned>(trackGroupNo) < _trackInfo.size() &&
          static_cast<unsigned>(trackNo) < _trackInfo[ trackGroupNo ].size() ) {
          _trackInfo[ trackGroupNo ][ trackNo ] = info;
      }
      // Someone is requesting a non-existent track, maybe this will add it
      addTracks();
      // Try again
      if ( static_cast<unsigned>(trackGroupNo) < _trackInfo.size() &&
           static_cast<unsigned>(trackNo) < _trackInfo[ trackGroupNo ].size() ) {
          _trackInfo[ trackGroupNo ][ trackNo ] = info;
      }
      else {
          cerr << "rcTrackManager::setTrackInfo error: element [" << trackGroupNo << "," << trackNo << "] ";
          cerr << "requested, array size is [" << _trackInfo.size() << "," << (_trackInfo.size() ? _trackInfo[ trackGroupNo ].size() : 0) << "]";
          cerr << endl;
      }
 }
void rcTrackManager::setTrackPen (int trackGroupNo, int trackNo, const QPen & pen)
Definition at line 142 of file rc_trackmanager.cpp.
References rcTrackInfo::_pen, rcModelDomain::getModelDomain(), getTrackInfo(), rcModelDomain::notifyUpdateDisplay(), and setTrackInfo().
 {
     rcTrackInfo info = getTrackInfo( trackGroupNo , trackNo );
     QPen newPen = pen;
     newPen.setWidth( 1 );
     info._pen = newPen;
     setTrackInfo( trackGroupNo , trackNo , info );
     rcModelDomain::getModelDomain()->notifyUpdateDisplay();
 }
void rcTrackManager::trackhighlighted (void) signal
Definition at line 85 of file moc_rc_trackmanager.cpp.
Referenced by reportTrackHighLighted().
 {
     QMetaObject::activate(this, &staticMetaObject, 0, 0);
 }
void rcTrackManager::updateState (rcExperimentState state) slot
Definition at line 250 of file rc_trackmanager.cpp.
References _trackInfo, addTracks(), eExperimentEmpty, and setColors().
Referenced by rcTrackManager().
 {
     switch( state ) {
         case eExperimentEmpty:
             _trackInfo.clear();
             break;
         default:
             addTracks();
             setColors();
             break;
     }
 }
Friends And Related Function Documentation
friend class rcTrackInfo friend
Definition at line 66 of file rc_trackmanager.h.
Member Data Documentation
deque<QPen> rcTrackManager::_defaultPens private
Definition at line 166 of file rc_trackmanager.h.
Referenced by addTracks(), and rcTrackManager().
deque<bool> rcTrackManager::_groupEnabled private
Definition at line 165 of file rc_trackmanager.h.
Referenced by addTracks(), isTrackGroupEnabled(), and setTrackGroupEnabled().
int rcTrackManager::_hiliteTrack private
Definition at line 168 of file rc_trackmanager.h.
Referenced by getHiliteTrack(), isHiliteTrack(), and setHiliteTrack().
int rcTrackManager::_hiliteTrackGroup private
Definition at line 167 of file rc_trackmanager.h.
Referenced by getHiliteTrack(), isHiliteTrack(), and setHiliteTrack().
deque<rcTrackInfoVector> rcTrackManager::_trackInfo private
Definition at line 164 of file rc_trackmanager.h.
Referenced by addTracks(), getTrackInfo(), hiliteTracks(), rebuildTracks(), setColors(), setHiliteTrack(), setTrackEnabled(), setTrackInfo(), and updateState().
The documentation for this class was generated from the following files:
include/visUI/rc_trackmanager.h
src/visible/moc/moc_rc_trackmanager.cpp
src/visible/qt/rc_trackmanager.cpp