Visible: rcMovieFileCamExt Class Reference
rcMovieFileCamExt Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileCamExt ()
bool write (FILE *saveStream) const
ostream & log (ostream &os, bool showUndefined=true) const
void fixEndian (const reByteOrder &fileByteOrder)
const uint32 & mid () const
const uint32 & uid () const
const uint32 & format () const
const uint32 & mode () const
const double & frameRate () const
const uint32 & brightness () const
const uint32 & exposure () const
const uint32 & sharpness () const
const uint32 & whiteBalanceUB () const
const uint32 & whiteBalanceVR () const
const uint32 & hue () const
const uint32 & saturation () const
const uint32 & gamma () const
const uint32 & shutter () const
const int32 & gain () const
const uint32 & iris () const
const uint32 & focus () const
const uint32 & temperature () const
const uint32 & zoom () const
const uint32 & pan () const
const uint32 & tilt () const
const uint32 & filter () const
const rcRect & cropRect () const
const char * name () const
const int32 & id () const
rc2Fvector pixelGeometry () const
void mid (const int32 &v)
void uid (const int32 &v)
void format (const int32 &v)
void mode (const int32 &v)
void frameRate (const double &v)
void brightness (const int32 &v)
void exposure (const int32 &v)
void sharpness (const int32 &v)
void whiteBalanceUB (const int32 &v)
void whiteBalanceVR (const int32 &v)
void hue (const int32 &v)
void saturation (const int32 &v)
void gamma (const int32 &v)
void shutter (const int32 &v)
void gain (const int32 &v)
void iris (const int32 &v)
void focus (const int32 &v)
void temperature (const int32 &v)
void zoom (const int32 &v)
void pan (const int32 &v)
void tilt (const int32 &v)
void filter (const int32 &v)
void cropRect (const rcRect &v)
void name (const char *n)
void id (const int32 &i)
Public Member Functions inherited from rcMovieFileExt
rcMovieFileExt ()
rcMovieFileExt (movieExtensionType t)
rcMovieFileExt (movieExtensionType t, int64 o)
const movieExtensionType & type () const
const int64 & offset () const
bool write (FILE *saveStream) const
void fixEndian (const reByteOrder &fileByteOrder)
Private Attributes
uint32 mMfgId
uint32 mUniqueId
uint32 mFormat
uint32 mMode
double mFrameRate
uint32 mBrightness
uint32 mExposure
uint32 mSharpness
uint32 mWhiteBalUB
uint32 mWhiteBalVR
uint32 mHue
uint32 mSaturation
uint32 mGamma
uint32 mShutter
int32 mGain
uint32 mIris
uint32 mFocus
uint32 mTemperature
uint32 mZoom
uint32 mPan
uint32 mTilt
uint32 mFilter
rcRect mCropRect
char mName [80]
int32 mId
Detailed Description
Definition at line 369 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileCamExt::rcMovieFileCamExt ()
Definition at line 508 of file rc_moviefileformat.cpp.
References mName, and rmDim.
                                      :
         rcMovieFileExt(movieExtensionCAM, sizeof(rcMovieFileCamExt)),
         mMfgId(rcUINT32_MAX), mUniqueId(rcUINT32_MAX), mFormat(rcUINT32_MAX), mMode(rcUINT32_MAX),
         mFrameRate(-1.0),
         mBrightness(rcUINT32_MAX), mExposure(rcUINT32_MAX), mSharpness(rcUINT32_MAX),
         mWhiteBalUB(rcUINT32_MAX), mWhiteBalVR(rcUINT32_MAX), mHue(rcUINT32_MAX),
         mSaturation(rcUINT32_MAX), mGamma(rcUINT32_MAX), mShutter(rcUINT32_MAX),
         mGain(rcINT32_MAX), mIris(rcUINT32_MAX), mFocus(rcUINT32_MAX),
         mTemperature(rcUINT32_MAX), mZoom(rcUINT32_MAX), mPan(rcUINT32_MAX),
         mTilt(rcUINT32_MAX), mFilter(rcUINT32_MAX),
         mId( 0 )
 {
     memset( mName, 0, rmDim(mName) );
     snprintf( mName, rmDim(mName), "Unknown" );
}
Member Function Documentation
const uint32& rcMovieFileCamExt::brightness () const inline
Definition at line 389 of file rc_moviefileformat.h.
References mBrightness.
Referenced by log(), operator<<(), and setProperty().
 { return mBrightness; };
void rcMovieFileCamExt::brightness (const int32 & v) inline
Definition at line 419 of file rc_moviefileformat.h.
References mBrightness.
 { mBrightness = v; }
const rcRect& rcMovieFileCamExt::cropRect () const inline
Definition at line 406 of file rc_moviefileformat.h.
References mCropRect.
Referenced by log(), and operator<<().
 { return mCropRect; };
void rcMovieFileCamExt::cropRect (const rcRect & v) inline
Definition at line 436 of file rc_moviefileformat.h.
References mCropRect.
 { mCropRect = v; }
const uint32& rcMovieFileCamExt::exposure () const inline
Definition at line 390 of file rc_moviefileformat.h.
References mExposure.
Referenced by log(), operator<<(), and setProperty().
 { return mExposure; };
void rcMovieFileCamExt::exposure (const int32 & v) inline
Definition at line 420 of file rc_moviefileformat.h.
References mExposure.
 { mExposure = v; }
const uint32& rcMovieFileCamExt::filter () const inline
Definition at line 405 of file rc_moviefileformat.h.
References mFilter.
Referenced by log(), operator<<(), and setProperty().
 { return mFilter; };
void rcMovieFileCamExt::filter (const int32 & v) inline
Definition at line 435 of file rc_moviefileformat.h.
References mFilter.
 { mFilter = v; }
void rcMovieFileCamExt::fixEndian (const reByteOrder & fileByteOrder)
Definition at line 540 of file rc_moviefileformat.cpp.
References ByteSwapN, rcMovieFileExt::fixEndian(), rcRectangle< T >::lr(), mBrightness, mCropRect, mExposure, mFilter, mFocus, mFormat, mFrameRate, mGain, mGamma, mHue, mId, mIris, mMfgId, mMode, mPan, mSaturation, mSharpness, mShutter, mTemperature, mTilt, mUniqueId, mWhiteBalUB, mWhiteBalVR, mZoom, rfPlatformByteOrder(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
Referenced by rcVideoCache::camLoad(), and write().
 {
     if ( rfPlatformByteOrder() != fileByteOrder )
 {
     rcMovieFileExt::fixEndian (fileByteOrder);
     ByteSwapN (mMfgId) ;                       // Manufacturer ID
     ByteSwapN (  mUniqueId) ;                   // Unique hardware ID
     ByteSwapN ( mFormat);                      // IIDC format
     ByteSwapN (mMode );                        // IIDC mode
     ByteSwapN (mFrameRate);
     ByteSwapN( mBrightness);                  // Brightness setting
     ByteSwapN (mExposure );                    // Exposure setting
     ByteSwapN (mSharpness );                   // Sharpness setting
     ByteSwapN (mWhiteBalUB );                  // White balance U/B
     ByteSwapN (mWhiteBalVR );                  // White balance V/R
     ByteSwapN (mHue );                         // Hue setting
     ByteSwapN (mSaturation );                  // Saturation setting
     ByteSwapN ( mGamma);                       // Gamma setting
     ByteSwapN (mShutter );                     // Shutter setting
     ByteSwapN ( mGain);                        // gain setting
     ByteSwapN (mIris );                        // Iris setting
     ByteSwapN ( mFocus);                       // Focus setting
     ByteSwapN (mTemperature );                 // Temperature setting
     ByteSwapN (mZoom );                        // Zoom setting
     ByteSwapN (mPan );                         // Pan setting
     ByteSwapN (mTilt );                        // Tilt setting
     ByteSwapN (mFilter );                      // Optical filter setting
     int32 x = mCropRect.x(), y = mCropRect.y();
     int32 lrx = mCropRect.lr().x(), lry = mCropRect.lr().y();
     ByteSwapN (x), ByteSwapN (y), ByteSwapN (lrx), ByteSwapN (lry);
     mCropRect = rcIRect (rcIPair (x, y), rcIPair (lrx, lry));
     ByteSwapN ( mId);                          // Unique id, reserved for future use
 }
 }
const uint32& rcMovieFileCamExt::focus (void) const inline
Definition at line 400 of file rc_moviefileformat.h.
References mFocus.
Referenced by log(), operator<<(), and setProperty().
 { return mFocus; };
void rcMovieFileCamExt::focus (const int32 & v) inline
Definition at line 430 of file rc_moviefileformat.h.
References mFocus.
 { mFocus = v; }
const uint32& rcMovieFileCamExt::format (void) const inline
Definition at line 386 of file rc_moviefileformat.h.
References mFormat.
Referenced by InitializeMungData2(), log(), and operator<<().
 { return mFormat; };
void rcMovieFileCamExt::format (const int32 & v) inline
Definition at line 416 of file rc_moviefileformat.h.
References mFormat.
 { mFormat = v; }
const double& rcMovieFileCamExt::frameRate () const inline
Definition at line 388 of file rc_moviefileformat.h.
References mFrameRate.
Referenced by InitializeMungData2(), log(), and operator<<().
 { return mFrameRate; };
void rcMovieFileCamExt::frameRate (const double & v) inline
Definition at line 418 of file rc_moviefileformat.h.
References mFrameRate.
 { mFrameRate = v; }
const int32& rcMovieFileCamExt::gain () const inline
Definition at line 398 of file rc_moviefileformat.h.
References mGain.
Referenced by log(), operator<<(), processControlRequests(), and setProperty().
 { return mGain; };
void rcMovieFileCamExt::gain (const int32 & v) inline
Definition at line 428 of file rc_moviefileformat.h.
References mGain.
 { mGain = v; }
const uint32& rcMovieFileCamExt::gamma () const inline
Definition at line 396 of file rc_moviefileformat.h.
References mGamma.
Referenced by log(), operator<<(), and setProperty().
 { return mGamma; };
void rcMovieFileCamExt::gamma (const int32 & v) inline
Definition at line 426 of file rc_moviefileformat.h.
References mGamma.
 { mGamma = v; }
const uint32& rcMovieFileCamExt::hue () const inline
Definition at line 394 of file rc_moviefileformat.h.
References mHue.
Referenced by log(), operator<<(), and setProperty().
 { return mHue; };
void rcMovieFileCamExt::hue (const int32 & v) inline
Definition at line 424 of file rc_moviefileformat.h.
References mHue.
 { mHue = v; }
const int32& rcMovieFileCamExt::id (void) const inline
Definition at line 409 of file rc_moviefileformat.h.
References mId.
Referenced by rcEngineMovieSaver::closeHdlr(), rcGenMovieFile::flush(), and operator<<().
 { return mId; }
void rcMovieFileCamExt::id (const int32 & i) inline
Definition at line 448 of file rc_moviefileformat.h.
References mId.
 { mId = i; }
const uint32& rcMovieFileCamExt::iris () const inline
Definition at line 399 of file rc_moviefileformat.h.
References mIris.
Referenced by log(), operator<<(), and setProperty().
 { return mIris; };
void rcMovieFileCamExt::iris (const int32 & v) inline
Definition at line 429 of file rc_moviefileformat.h.
References mIris.
 { mIris = v; }
ostream & rcMovieFileCamExt::log (ostream & os, bool showUndefined = true) const
Definition at line 577 of file rc_moviefileformat.cpp.
References brightness(), cropRect(), endl(), exposure(), filter(), focus(), format(), frameRate(), gain(), gamma(), hue(), iris(), mid(), mode(), name(), pan(), pixelGeometry(), rcINT32_MAX, rcUINT32_MAX, saturation(), sharpness(), shutter(), temperature(), tilt(), uid(), whiteBalanceUB(), whiteBalanceVR(), and zoom().
Referenced by rcEngineImpl::setCameraInfo(), and rcEngineImpl::updateCameraLog().
 {
     bool shown = false;
     if ( showUndefined || (!showUndefined && strcmp( name(), "Unknown" )) )
         os << " Name: " << name(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && mid() != rcUINT32_MAX))
         os << " MfgID: " << mid(), shown = true;
     if ( showUndefined || (!showUndefined && uid() != rcUINT32_MAX))
         os << " UID: " << uid(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && format() != rcUINT32_MAX))
         os << " Format: " << format(), shown = true;
     if ( showUndefined || (!showUndefined && mode() != rcUINT32_MAX))
         os << " Mode: " << mode(), shown = true;
     if ( showUndefined || (!showUndefined && frameRate() >= 0.0))
         os << " MaxFrameRate: " << frameRate(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && brightness() != rcUINT32_MAX))
         os << " Brightness: " << brightness(), shown = true;
     if ( showUndefined || (!showUndefined && exposure() != rcUINT32_MAX))
         os << " Exposure: " << exposure(), shown = true;
     if ( showUndefined || (!showUndefined && sharpness() != rcUINT32_MAX))
         os << " Sharpness: " << sharpness(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && whiteBalanceUB() != rcUINT32_MAX))
         os << " WhiteBalanceUB: " << whiteBalanceUB(), shown = true;
     if ( showUndefined || (!showUndefined && whiteBalanceVR() != rcUINT32_MAX))
         os << " WhiteBalanceVR: " << whiteBalanceVR(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && hue() != rcUINT32_MAX))
         os << " Hue: " << hue(), shown = true;
     if ( showUndefined || (!showUndefined && saturation() != rcUINT32_MAX))
         os << " Saturation: " << saturation(), shown = true;
     if ( showUndefined || (!showUndefined && gamma() != rcUINT32_MAX))
         os << " Gamma: " << gamma(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && shutter() != rcUINT32_MAX))
         os << " Shutter: " << shutter(), shown = true;
     if ( showUndefined || (!showUndefined && gain() != rcINT32_MAX))
         os << " Gain: " << gain(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && iris() != rcUINT32_MAX))
         os << " Iris: " << iris(), shown = true;
     if ( showUndefined || (!showUndefined && focus() != rcUINT32_MAX))
         os << " Focus: " << focus(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && temperature() != rcUINT32_MAX))
         os << " Temperature: " << temperature(), shown = true;
     if ( showUndefined || (!showUndefined && filter() != rcUINT32_MAX))
         os << " Filter: " << filter(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && zoom() != rcUINT32_MAX))
         os << " Zoom: " << zoom(), shown = true;
     if ( showUndefined || (!showUndefined && pan() != rcUINT32_MAX))
         os << " Pan: " << pan(), shown = true;
     if ( showUndefined || (!showUndefined && tilt() != rcUINT32_MAX))
         os << " Tilt: " << tilt(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     const rc2Fvector pg = pixelGeometry();
     if ( showUndefined || (!showUndefined && pg != rc2Fvector(-1.0f,-1.0f)))
         os << " SensorElementSize: " << pg << " um", shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     if ( showUndefined || (!showUndefined && cropRect().width() != 0))
            os << " CropRect: " << cropRect(), shown = true;
     if ( shown ) {
         os << endl;
         shown = false;
     }
     return os;
 }
const uint32& rcMovieFileCamExt::mid () const inline
Definition at line 384 of file rc_moviefileformat.h.
References mMfgId.
Referenced by log(), operator<<(), and rfDCAMVideoCapture().
 { return mMfgId; };
void rcMovieFileCamExt::mid (const int32 & v) inline
Definition at line 414 of file rc_moviefileformat.h.
References mMfgId.
 { mMfgId = v; }
const uint32& rcMovieFileCamExt::mode (void) const inline
Definition at line 387 of file rc_moviefileformat.h.
References mMode.
Referenced by InitializeMungData2(), log(), and operator<<().
 { return mMode; };
void rcMovieFileCamExt::mode (const int32 & v) inline
Definition at line 417 of file rc_moviefileformat.h.
References mMode.
 { mMode = v; }
const char* rcMovieFileCamExt::name (void) const inline
Definition at line 407 of file rc_moviefileformat.h.
References mName.
Referenced by log(), operator<<(), rcEngineMovieCapture::run(), and setProperties().
 { return mName; };
void rcMovieFileCamExt::name (const char * n) inline
Definition at line 437 of file rc_moviefileformat.h.
References mName, and rmDim.
{
         if ( n ) {
             // Truncate if necessary
             uint32 len = strlen( n );
             if ( len >= rmDim(mName) )
                 len = rmDim(mName)-1;
             strncpy( mName, n, len );
             // Null-terminate
             mName[len] = 0;
         }
     }
const uint32& rcMovieFileCamExt::pan () const inline
Definition at line 403 of file rc_moviefileformat.h.
References mPan.
Referenced by log(), operator<<(), and setProperty().
 { return mPan; };
void rcMovieFileCamExt::pan (const int32 & v) inline
Definition at line 433 of file rc_moviefileformat.h.
References mPan.
 { mPan = v; }
rc2Fvector rcMovieFileCamExt::pixelGeometry () const
Definition at line 693 of file rc_moviefileformat.cpp.
Referenced by log().
 {
     return rc2Fvector ();
 }
const uint32& rcMovieFileCamExt::saturation () const inline
Definition at line 395 of file rc_moviefileformat.h.
References mSaturation.
Referenced by log(), operator<<(), and setProperty().
 { return mSaturation; };
void rcMovieFileCamExt::saturation (const int32 & v) inline
Definition at line 425 of file rc_moviefileformat.h.
References mSaturation.
 { mSaturation = v; }
const uint32& rcMovieFileCamExt::sharpness () const inline
Definition at line 391 of file rc_moviefileformat.h.
References mSharpness.
Referenced by log(), operator<<(), and setProperty().
 { return mSharpness; };
void rcMovieFileCamExt::sharpness (const int32 & v) inline
Definition at line 421 of file rc_moviefileformat.h.
References mSharpness.
 { mSharpness = v; }
const uint32& rcMovieFileCamExt::shutter () const inline
Definition at line 397 of file rc_moviefileformat.h.
References mShutter.
Referenced by log(), operator<<(), processControlRequests(), and setProperty().
 { return mShutter; };
void rcMovieFileCamExt::shutter (const int32 & v) inline
Definition at line 427 of file rc_moviefileformat.h.
References mShutter.
 { mShutter = v; }
const uint32& rcMovieFileCamExt::temperature () const inline
Definition at line 401 of file rc_moviefileformat.h.
References mTemperature.
Referenced by log(), operator<<(), and setProperty().
 { return mTemperature; };
void rcMovieFileCamExt::temperature (const int32 & v) inline
Definition at line 431 of file rc_moviefileformat.h.
References mTemperature.
 { mTemperature = v; }
const uint32& rcMovieFileCamExt::tilt () const inline
Definition at line 404 of file rc_moviefileformat.h.
References mTilt.
Referenced by log(), and setProperty().
 { return mTilt; };
void rcMovieFileCamExt::tilt (const int32 & v) inline
Definition at line 434 of file rc_moviefileformat.h.
References mTilt.
 { mTilt = v; }
const uint32& rcMovieFileCamExt::uid () const inline
Definition at line 385 of file rc_moviefileformat.h.
References mUniqueId.
Referenced by log(), operator<<(), and setProperties().
 { return mUniqueId; };
void rcMovieFileCamExt::uid (const int32 & v) inline
Definition at line 415 of file rc_moviefileformat.h.
References mUniqueId.
 { mUniqueId = v; }
const uint32& rcMovieFileCamExt::whiteBalanceUB () const inline
Definition at line 392 of file rc_moviefileformat.h.
References mWhiteBalUB.
Referenced by log(), operator<<(), and setProperty().
 { return mWhiteBalUB; };
void rcMovieFileCamExt::whiteBalanceUB (const int32 & v) inline
Definition at line 422 of file rc_moviefileformat.h.
References mWhiteBalUB.
 { mWhiteBalUB = v; }
const uint32& rcMovieFileCamExt::whiteBalanceVR () const inline
Definition at line 393 of file rc_moviefileformat.h.
References mWhiteBalVR.
Referenced by log(), operator<<(), and setProperty().
 { return mWhiteBalVR; };
void rcMovieFileCamExt::whiteBalanceVR (const int32 & v) inline
Definition at line 423 of file rc_moviefileformat.h.
References mWhiteBalVR.
 { mWhiteBalVR = v; }
bool rcMovieFileCamExt::write (FILE * saveStream) const
Definition at line 525 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), rfPlatformByteOrder(), and rfPlatformByteOrderMark().
Referenced by rcEngineMovieSaver::closeHdlr(), and rcGenMovieFile::flush().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileCamExt *>(this)->fixEndian (rfPlatformByteOrder(rfPlatformByteOrderMark()) );
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("CAM hdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
const uint32& rcMovieFileCamExt::zoom () const inline
Definition at line 402 of file rc_moviefileformat.h.
References mZoom.
Referenced by log(), operator<<(), and setProperty().
 { return mZoom; };
void rcMovieFileCamExt::zoom (const int32 & v) inline
Definition at line 432 of file rc_moviefileformat.h.
References mZoom.
 { mZoom = v; }
Member Data Documentation
uint32 rcMovieFileCamExt::mBrightness private
Definition at line 458 of file rc_moviefileformat.h.
Referenced by brightness(), and fixEndian().
rcRect rcMovieFileCamExt::mCropRect private
Definition at line 475 of file rc_moviefileformat.h.
Referenced by cropRect(), and fixEndian().
uint32 rcMovieFileCamExt::mExposure private
Definition at line 459 of file rc_moviefileformat.h.
Referenced by exposure(), and fixEndian().
uint32 rcMovieFileCamExt::mFilter private
Definition at line 474 of file rc_moviefileformat.h.
Referenced by filter(), and fixEndian().
uint32 rcMovieFileCamExt::mFocus private
Definition at line 469 of file rc_moviefileformat.h.
Referenced by fixEndian(), and focus().
uint32 rcMovieFileCamExt::mFormat private
Definition at line 454 of file rc_moviefileformat.h.
Referenced by fixEndian(), and format().
double rcMovieFileCamExt::mFrameRate private
Definition at line 456 of file rc_moviefileformat.h.
Referenced by fixEndian(), and frameRate().
int32 rcMovieFileCamExt::mGain private
Definition at line 467 of file rc_moviefileformat.h.
Referenced by fixEndian(), and gain().
uint32 rcMovieFileCamExt::mGamma private
Definition at line 465 of file rc_moviefileformat.h.
Referenced by fixEndian(), and gamma().
uint32 rcMovieFileCamExt::mHue private
Definition at line 463 of file rc_moviefileformat.h.
Referenced by fixEndian(), and hue().
int32 rcMovieFileCamExt::mId private
Definition at line 478 of file rc_moviefileformat.h.
Referenced by fixEndian(), and id().
uint32 rcMovieFileCamExt::mIris private
Definition at line 468 of file rc_moviefileformat.h.
Referenced by fixEndian(), and iris().
uint32 rcMovieFileCamExt::mMfgId private
Definition at line 452 of file rc_moviefileformat.h.
Referenced by fixEndian(), and mid().
uint32 rcMovieFileCamExt::mMode private
Definition at line 455 of file rc_moviefileformat.h.
Referenced by fixEndian(), and mode().
char rcMovieFileCamExt::mName[80] private
Definition at line 477 of file rc_moviefileformat.h.
Referenced by name(), and rcMovieFileCamExt().
uint32 rcMovieFileCamExt::mPan private
Definition at line 472 of file rc_moviefileformat.h.
Referenced by fixEndian(), and pan().
uint32 rcMovieFileCamExt::mSaturation private
Definition at line 464 of file rc_moviefileformat.h.
Referenced by fixEndian(), and saturation().
uint32 rcMovieFileCamExt::mSharpness private
Definition at line 460 of file rc_moviefileformat.h.
Referenced by fixEndian(), and sharpness().
uint32 rcMovieFileCamExt::mShutter private
Definition at line 466 of file rc_moviefileformat.h.
Referenced by fixEndian(), and shutter().
uint32 rcMovieFileCamExt::mTemperature private
Definition at line 470 of file rc_moviefileformat.h.
Referenced by fixEndian(), and temperature().
uint32 rcMovieFileCamExt::mTilt private
Definition at line 473 of file rc_moviefileformat.h.
Referenced by fixEndian(), and tilt().
uint32 rcMovieFileCamExt::mUniqueId private
Definition at line 453 of file rc_moviefileformat.h.
Referenced by fixEndian(), and uid().
uint32 rcMovieFileCamExt::mWhiteBalUB private
Definition at line 461 of file rc_moviefileformat.h.
Referenced by fixEndian(), and whiteBalanceUB().
uint32 rcMovieFileCamExt::mWhiteBalVR private
Definition at line 462 of file rc_moviefileformat.h.
Referenced by fixEndian(), and whiteBalanceVR().
uint32 rcMovieFileCamExt::mZoom private
Definition at line 471 of file rc_moviefileformat.h.
Referenced by fixEndian(), and zoom().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp