Visible: rcMatrix< 2 > Class Template Reference
rcMatrix< 2 > Class Template Reference
#include <include/util/rc_matrix.h>
Public Member Functions
rcMatrix ()
rcMatrix (double m11, double m12, double m21, double m22)
rcMatrix (const rcDPair &rot, const rcDPair &scale)
rcMatrix (const rcRadian &rot, const rcDPair &scale)
rcMatrix (double scale, double aspect, const double &shear, const rcRadian &rotation)
double determinant () const
rcMatrix< 2 > inverse () const
rcMatrix< 2 > transpose () const
bool isSingular () const
bool isIdentity () const
double element (int32 row, int32 column) const
void element (int32 row, int32 column, double value)
double xRot () const
double yRot () const
double xScale () const
double yScale () const
double scale () const
double aspect () const
double shear () const
rcRadian rotation () const
rcMatrix< 2 > operator+ (const rcMatrix< 2 > &) const
rcMatrix< 2 > & operator+= (const rcMatrix< 2 > &)
rcMatrix< 2 > operator- () const
rcMatrix< 2 > operator- (const rcMatrix< 2 > &) const
rcMatrix< 2 > & operator-= (const rcMatrix< 2 > &)
rcMatrix< 2 > operator* (double) const
rcMatrix< 2 > & operator*= (double)
rcMatrix< 2 > operator* (const rcMatrix< 2 > &) const
rcMatrix< 2 > & operator*= (const rcMatrix< 2 > &)
rcMatrix< 2 > operator/ (double) const
rcMatrix< 2 > & operator/= (double)
rcMatrix< 2 > operator/ (const rcMatrix< 2 > &) const
rcMatrix< 2 > & operator/= (const rcMatrix< 2 > &)
bool operator== (const rcMatrix< 2 > &) const
bool operator!= (const rcMatrix< 2 > &) const
rc2Dvector operator* (const rc2Dvector &) const
rc2Fvector operator* (const rc2Fvector &) const
Static Public Attributes
static const rcMatrix< 2 > I
Private Member Functions
void setdt ()
Private Attributes
double me [2][2]
double mDt
Friends
rc2Dvector operator* (const rc2Dvector &, const rcMatrix< 2 > &)
rc2Fvector operator* (const rc2Fvector &, const rcMatrix< 2 > &)
ostream & operator<< (ostream &ous, const rcMatrix< 2 > &dis)
Detailed Description
template<>
class rcMatrix< 2 >
Definition at line 56 of file rc_matrix.h.
Constructor & Destructor Documentation
rcMatrix< 2 >::rcMatrix () inline
Definition at line 102 of file rc_matrix.h.
              { me[0][0] = 1.; me[0][1] = 0.;
                me[1][0] = 0.; me[1][1] = 1.; mDt = 1.;}
rcMatrix< 2 >::rcMatrix (double m11, double m12, double m21, double m22) inline
Definition at line 105 of file rc_matrix.h.
   {
     me[0][0] = m11; me[0][1] = m12;
     me[1][0] = m21; me[1][1] = m22; setdt();
   }
rcMatrix< 2 >::rcMatrix (const rcDPair & rot, const rcDPair & scale) inline
Definition at line 111 of file rc_matrix.h.
References cos(), sin(), rcPair< T >::x(), and rcPair< T >::y().
     {
       me[0][0] = scale.x() * std::cos(rot.x());
       me[1][0] = scale.y() * std::sin(rot.y());
       me[0][1] = scale.x() * std::sin(rot.x());
       me[1][1] = scale.y() * std::cos(rot.y());
       setdt();
     }
rcMatrix< 2 >::rcMatrix (const rcRadian & rot, const rcDPair & scale) inline
Definition at line 121 of file rc_matrix.h.
References cos(), sin(), rcPair< T >::x(), and rcPair< T >::y().
     {
       double cosR = cos(rot);
       double sinR = sin(rot);
       me[0][0] =  scale.x() * cosR;
       me[1][0] = -scale.y() * sinR;
       me[0][1] = scale.x() * sinR;
       me[1][1] = scale.y() * cosR;
       setdt ();
     }
rcMatrix< 2 >::rcMatrix (double scale, double aspect, const double & shear, const rcRadian & rotation)
Member Function Documentation
double rcMatrix< 2 >::aspect () const inline
Definition at line 201 of file rc_matrix.h.
References e11, e21, and rmSquare.
   {
     if (isSingular()) throw general_exception ("Singular");
     return determinant() / (rmSquare(e11) + rmSquare(e21));
   }
double rcMatrix< 2 >::determinant () const inline
Definition at line 137 of file rc_matrix.h.
 { return mDt;}
double rcMatrix< 2 >::element (int32 row, int32 column) const inline
Definition at line 272 of file rc_matrix.h.
 { assert((row == 0 || row == 1) && (column == 0 || column == 1));
   return me[row][column];
 }
void rcMatrix< 2 >::element (int32 row, int32 column, double value)
rcMatrix<2> rcMatrix< 2 >::inverse () const inline
Definition at line 139 of file rc_matrix.h.
References e11, e12, e21, and e22.
Referenced by operator/(), operator/(), operator/=(), and operator/=().
   {
     if (isSingular()) throw general_exception ("is Singular");
     double idt = 1. / mDt; // do division once
     return rcMatrix<2> ( e22 * idt, -e12 * idt,
                -e21 * idt,  e11 * idt);
    }
bool rcMatrix< 2 >::isIdentity () const inline
Definition at line 280 of file rc_matrix.h.
 {return (me[0][0] == 1. && me[0][1] == 0. &&
      me[1][0] == 0. && me[1][1] == 1.);
 }
bool rcMatrix< 2 >::isSingular () const inline
Definition at line 277 of file rc_matrix.h.
  {return (mDt == 0.); }
bool rcMatrix< 2 >::operator!= (const rcMatrix< 2 > & m) const inline
Definition at line 344 of file rc_matrix.h.
 { return (!(*this==m)); }
rcMatrix< 2 > rcMatrix< 2 >::operator* (double s) const inline
Definition at line 357 of file rc_matrix.h.
 { return rcMatrix<2>(me[0][0] * s, me[0][1] * s, me[1][0] * s, me[1][1] * s); }
rcMatrix< 2 > rcMatrix< 2 >::operator* (const rcMatrix< 2 > & m) const inline
Definition at line 360 of file rc_matrix.h.
References me.
 { return rcMatrix<2>(me[0][0]*m.me[0][0] + me[0][1]*m.me[1][0],
              me[0][0]*m.me[0][1] + me[0][1]*m.me[1][1],
              me[1][0]*m.me[0][0] + me[1][1]*m.me[1][0],
              me[1][0]*m.me[0][1] + me[1][1]*m.me[1][1]);
 }
rc2Dvector rcMatrix< 2 >::operator* (const rc2Dvector & v) const inline
Definition at line 367 of file rc_matrix.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
 { return rc2Dvector(me[0][0] * v.x() + me[0][1] * v.y(),
              me[1][0] * v.x() + me[1][1] * v.y());
 }
rc2Fvector rcMatrix< 2 >::operator* (const rc2Fvector & v) const inline
Definition at line 377 of file rc_matrix.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
 { return rc2Fvector((float) (me[0][0] * v.x() + me[0][1] * v.y()),
             (float) (me[1][0] * v.x() + me[1][1] * v.y()));
 }
rcMatrix< 2 > & rcMatrix< 2 >::operator*= (double s) inline
Definition at line 299 of file rc_matrix.h.
 { return *this = *this * s; }
rcMatrix< 2 > & rcMatrix< 2 >::operator*= (const rcMatrix< 2 > & m) inline
Definition at line 302 of file rc_matrix.h.
 { return *this = *this * m; }
rcMatrix< 2 > rcMatrix< 2 >::operator+ (const rcMatrix< 2 > & m) const inline
Definition at line 347 of file rc_matrix.h.
References me.
 { return rcMatrix<2>(me[0][0] + m.me[0][0], me[0][1] + m.me[0][1],
                      me[1][0] + m.me[1][0], me[1][1] + m.me[1][1]);
 }
rcMatrix< 2 > & rcMatrix< 2 >::operator+= (const rcMatrix< 2 > & m) inline
Definition at line 288 of file rc_matrix.h.
 { return *this = *this + m; }
rcMatrix< 2 > rcMatrix< 2 >::operator- () const inline
Definition at line 291 of file rc_matrix.h.
 { return rcMatrix<2>(-me[0][0], -me[0][1],
              -me[1][0], -me[1][1]);
 }
rcMatrix< 2 > rcMatrix< 2 >::operator- (const rcMatrix< 2 > & m) const inline
Definition at line 352 of file rc_matrix.h.
References me.
 { return rcMatrix<2>(me[0][0] - m.me[0][0], me[0][1] - m.me[0][1],
                      me[1][0] - m.me[1][0], me[1][1] - m.me[1][1]);
 }
rcMatrix< 2 > & rcMatrix< 2 >::operator-= (const rcMatrix< 2 > & m) inline
Definition at line 296 of file rc_matrix.h.
 { return *this = *this - m; }
rcMatrix< 2 > rcMatrix< 2 >::operator/ (double s) const inline
Definition at line 311 of file rc_matrix.h.
 { return *this * (1. / s); }  // Do division once
rcMatrix< 2 > rcMatrix< 2 >::operator/ (const rcMatrix< 2 > & m) const inline
Definition at line 305 of file rc_matrix.h.
References inverse().
 { return (*this) * m.inverse(); }
rcMatrix< 2 > & rcMatrix< 2 >::operator/= (double s) inline
Definition at line 314 of file rc_matrix.h.
 { return *this = *this / s; }
rcMatrix< 2 > & rcMatrix< 2 >::operator/= (const rcMatrix< 2 > & m) inline
Definition at line 308 of file rc_matrix.h.
References inverse().
 { return *this *= m.inverse(); }
bool rcMatrix< 2 >::operator== (const rcMatrix< 2 > & m) const inline
Definition at line 339 of file rc_matrix.h.
References me.
 { return (me[0][0] == m.me[0][0] && me[0][1] == m.me[0][1] &&
       me[1][0] == m.me[1][0] && me[1][1] == m.me[1][1]);
 }
rcRadian rcMatrix< 2 >::rotation () const inline
Definition at line 214 of file rc_matrix.h.
References arctan(), e11, and e21.
   {
     if (isSingular()) throw general_exception ("Singular");
     return arctan (e21, e11);
   }
double rcMatrix< 2 >::scale () const inline
Definition at line 195 of file rc_matrix.h.
References e11, e21, and rmSquare.
   {
     if (isSingular()) throw general_exception ("Singular");
     return sqrt(rmSquare(e11) + rmSquare(e21));
   }
void rcMatrix< 2 >::setdt () inline private
Definition at line 269 of file rc_matrix.h.
 { mDt = me[0][0] * me[1][1] - me[0][1] * me[1][0];}
double rcMatrix< 2 >::shear () const inline
Definition at line 207 of file rc_matrix.h.
References e11, e12, e21, and e22.
   {
     if (isSingular()) throw general_exception ("Singular");
     // Shear is limited to (-PI/2, PI/2) so use arctan(x) = atan(x)
     return ( -atan((e11 * e12 + e21 * e22) / determinant()) );
   }
rcMatrix< 2 > rcMatrix< 2 >::transpose (void) const inline
Definition at line 285 of file rc_matrix.h.
 { return rcMatrix<2>(me[0][0], me[1][0], me[0][1], me[1][1]); }
double rcMatrix< 2 >::xRot () const inline
Definition at line 164 of file rc_matrix.h.
References atan2(), e11, and e21.
   {
     if (isSingular()) throw general_exception ("Singular");
     // Full angle so use arctan(y,x) = atan2(y,x)
     return atan2(e21, e11);
   }
double rcMatrix< 2 >::xScale () const inline
Definition at line 178 of file rc_matrix.h.
References e11, e21, and rmSquare.
   {
     if (isSingular()) throw general_exception ("Singular");
     return sqrt(rmSquare(e11) + rmSquare(e21));
   }
double rcMatrix< 2 >::yRot () const inline
Definition at line 171 of file rc_matrix.h.
References atan2(), e12, and e22.
   {
     if (isSingular()) throw general_exception ("Singular");
     // Full angle so use arctan(y,x) = atan2(y,x)
     return atan2(-e12, e22);
   }
double rcMatrix< 2 >::yScale () const inline
Definition at line 184 of file rc_matrix.h.
References e12, e22, and rmSquare.
   {
     if (isSingular()) throw general_exception ("Singular");
     return sqrt(rmSquare(e12) + rmSquare(e22));
   }
Friends And Related Function Documentation
rc2Dvector operator* (const rc2Dvector & v, const rcMatrix< 2 > & m) friend
Definition at line 372 of file rc_matrix.h.
 { return rc2Dvector(m.me[0][0] * v.x() + m.me[1][0] * v.y(),
              m.me[0][1] * v.x() + m.me[1][1] * v.y());
 }
rc2Fvector operator* (const rc2Fvector & v, const rcMatrix< 2 > & m) friend
Definition at line 382 of file rc_matrix.h.
 { return rc2Fvector((float) (m.me[0][0] * v.x() + m.me[1][0] * v.y()),
             (float) (m.me[0][1] * v.x() + m.me[1][1] * v.y()));
 }
ostream& operator<< (ostream & ous, const rcMatrix< 2 > & dis) friend
Definition at line 260 of file rc_matrix.h.
   {
     ous << "[" << dis.element (0,0) << " " << dis.element(0,1) << endl << dis.element(1,0) << " " << dis.element(1,1) << "]" << endl;
     return ous;
   }
Member Data Documentation
const rcMatrix<2> rcMatrix< 2 >::I static
Definition at line 225 of file rc_matrix.h.
double rcMatrix< 2 >::mDt private
Definition at line 268 of file rc_matrix.h.
double rcMatrix< 2 >::me[2][2] private
Definition at line 267 of file rc_matrix.h.
Referenced by operator*(), operator*(), operator+(), operator-(), and operator==().
The documentation for this class was generated from the following file:
include/util/rc_matrix.h