Visible: rcTrackGroupWidget Class Reference
rcTrackGroupWidget Class Reference
#include <include/visUI/rc_trackgroupwidget.h>
Public Slots
void setEnabled (bool isEnabled)
void updateState (rcExperimentState state)
void updateSettings ()
Public Member Functions
rcTrackGroupWidget (QWidget *parent, int trackGroupNo)
~rcTrackGroupWidget ()
Private Member Functions
void updateTrackGroupDisplay (void)
Private Attributes
int _trackGroupNo
QString _trackGroupName
QPushButton * _enableButton
Q3VBox * _trackWidgets
Detailed Description
Definition at line 30 of file rc_trackgroupwidget.h.
Constructor & Destructor Documentation
rcTrackGroupWidget::rcTrackGroupWidget (QWidget * parent, int trackGroupNo)
Definition at line 26 of file rc_trackgroupwidget.cpp.
References _enableButton, _trackGroupName, _trackGroupNo, _trackWidgets, rcTrackManager::displayableTrack(), eGraphicsTrack, ePositionTrack, eScalarTrack, eVideoTrack, rcTrackGroup::getDescription(), rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getName(), rcTrackGroup::getNTracks(), rcTrackGroup::getTrack(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), rcTrack::getTrackType(), rcTrackManager::isTrackGroupEnabled(), setEnabled(), updateSettings(), and updateState().
     : QWidget( parent , "trackWidget" )
 {
     _trackGroupNo = trackGroupNo;
     //setSizePolicy( QSizePolicy( QSizePolicy::Fixed , QSizePolicy::Fixed ) );
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackGroup* trackGroup = experiment->getTrackGroup( _trackGroupNo );
     _trackGroupName = trackGroup->getName();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     Q3BoxLayout* layout = new Q3HBoxLayout( this );
     // add the group enable toggle pushbutton
     _enableButton = new rcTrackGroupEnableButton( this );
     _enableButton->setToggleButton( true );
     _enableButton->setMinimumWidth( 20 );
     _enableButton->setSizePolicy( QSizePolicy( QSizePolicy::Minimum , QSizePolicy::Minimum ) );
     if (tmp->isTrackGroupEnabled( _trackGroupNo ))
     {
         _enableButton->setOn( true );
         _enableButton->setText( "" );
     }
     else
     {
         _enableButton->setOn( false );
         _enableButton->setText( _trackGroupName );
     }
     QToolTip::add( _enableButton , trackGroup->getDescription() );
     layout->addWidget( _enableButton , 1 );
     // add a vertical box with the track widgets
     _trackWidgets = new Q3VBox( this );
     int nTracks = trackGroup->getNTracks();
     for (int i = 0; i < nTracks; i++)
     {
         rcTrack* track = trackGroup->getTrack( i );
         if ( rcTrackManager::displayableTrack( track ) ) {
             switch (track->getTrackType())
             {
                 case eScalarTrack:
                     new rcScalarTrackWidget( _trackWidgets , _trackGroupNo , i );
                     break;
                 case eVideoTrack:
                     new rcScalarTrackWidget( _trackWidgets , _trackGroupNo , i );
                     break;
                 case eGraphicsTrack:
                     new rcScalarTrackWidget( _trackWidgets , _trackGroupNo , i );
                     break;
 #ifdef notyet
                 case ePositionTrack:
                     new rcScalarTrackWidget( _trackWidgets , _trackGroupNo , i );
                     break;
 #endif
                 default:
                     // unsupported track types don't get an entry.
                     break;
             }
         }
     }
     layout->addWidget( _trackWidgets , 10 );
     // connect the checkbox signal
     connect( _enableButton , SIGNAL( toggled( bool ) ) ,
              this          , SLOT( setEnabled( bool ) ) );
     // connect to some domain signals
     connect( domain , SIGNAL( newState( rcExperimentState ) ) ,
              this   , SLOT( updateState( rcExperimentState ) ) );
     connect( domain , SIGNAL( updateSettings( void ) ) ,
              this   , SLOT( updateSettings( void ) ) );
 }
rcTrackGroupWidget::~rcTrackGroupWidget ()
Definition at line 102 of file rc_trackgroupwidget.cpp.
References _enableButton.
 {
     QToolTip::remove( _enableButton );
 }
Member Function Documentation
void rcTrackGroupWidget::setEnabled (bool isEnabled) slot
Definition at line 108 of file rc_trackgroupwidget.cpp.
References _trackGroupNo, eGroupSemanticsGlobalGraphics, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getNTracks(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), rcTrackGroup::getType(), rcModelDomain::notifySettingChange(), rcModelDomain::notifyUpdateMonitor(), rcTrackManager::setTrackEnabled(), and rcTrackManager::setTrackGroupEnabled().
Referenced by rcTrackGroupWidget(), and updateSettings().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     tmp->setTrackGroupEnabled( _trackGroupNo , isEnabled );
 #ifndef rcHIDE_TRACKS
     // Enable/disable all group members, too
     rcExperiment* experiment = domain->getExperiment();
     rcTrackGroup* trackGroup = experiment->getTrackGroup( _trackGroupNo );
     int nTracks = trackGroup->getNTracks();
     for (int i = 0; i < nTracks; i++)
     {
         tmp->setTrackEnabled( _trackGroupNo, i, isEnabled );
     }
 #endif
     domain->notifySettingChange();
     // Enabling graphics groups can affect video monitor
     if ( trackGroup->getType() == eGroupSemanticsGlobalGraphics )
         domain->notifyUpdateMonitor();
 }
void rcTrackGroupWidget::updateSettings (void) slot
Definition at line 137 of file rc_trackgroupwidget.cpp.
References _enableButton, _trackGroupName, _trackGroupNo, _trackWidgets, rcTrackManager::getTrackManager(), rcTrackManager::isTrackGroupEnabled(), and setEnabled().
Referenced by rcTrackGroupWidget().
 {
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     // disconnect the checkbox signal to avoid recursion
     disconnect( _enableButton , SIGNAL( toggled( bool ) ) ,
                 this          , SLOT( setEnabled( bool ) ) );
     if (tmp->isTrackGroupEnabled( _trackGroupNo ))
     {
         _enableButton->setOn( true );
         _enableButton->setText( "" );
         _enableButton->setSizePolicy( QSizePolicy( QSizePolicy::Minimum , QSizePolicy::Minimum ) );
         _trackWidgets->show();
     }
     else
     {
 #ifdef rcHIDE_TRACKS
         _enableButton->setText( _trackGroupName );
         _enableButton->setSizePolicy( QSizePolicy( QSizePolicy::Minimum , QSizePolicy::Maximum ) );
         _trackWidgets->hide();
 #else
         _enableButton->setOn( false );
         _enableButton->setText( "" );
         _enableButton->setSizePolicy( QSizePolicy( QSizePolicy::Minimum , QSizePolicy::Minimum ) );
 #endif
     }
     // connect the checkbox signal
     connect( _enableButton , SIGNAL( toggled( bool ) ) ,
              this          , SLOT( setEnabled( bool ) ) );
 }
void rcTrackGroupWidget::updateState (rcExperimentState state) slot
Definition at line 132 of file rc_trackgroupwidget.cpp.
References rmUnused.
Referenced by rcTrackGroupWidget().
 {
     rmUnused( state );
 }
void rcTrackGroupWidget::updateTrackGroupDisplay (void) private
Member Data Documentation
QPushButton* rcTrackGroupWidget::_enableButton private
Definition at line 53 of file rc_trackgroupwidget.h.
Referenced by rcTrackGroupWidget(), updateSettings(), and ~rcTrackGroupWidget().
QString rcTrackGroupWidget::_trackGroupName private
Definition at line 52 of file rc_trackgroupwidget.h.
Referenced by rcTrackGroupWidget(), and updateSettings().
int rcTrackGroupWidget::_trackGroupNo private
Definition at line 51 of file rc_trackgroupwidget.h.
Referenced by rcTrackGroupWidget(), setEnabled(), and updateSettings().
Q3VBox* rcTrackGroupWidget::_trackWidgets private
Definition at line 54 of file rc_trackgroupwidget.h.
Referenced by rcTrackGroupWidget(), and updateSettings().
The documentation for this class was generated from the following files:
include/visUI/rc_trackgroupwidget.h
src/visible/qt/rc_trackgroupwidget.cpp