Visible: LogStream Class Reference
LogStream Class Reference
#include <include/util/rc_logger.h>
Public Member Functions
LogStream ()
buffer (this)
unsigned get_level ()
Public Attributes
__pad0__: std::ostream(&buffer)
Static Public Attributes
static const int level_index = std::ios::xalloc()
Private Attributes
LogBuffer buffer
Detailed Description
Definition at line 71 of file rc_logger.h.
Constructor & Destructor Documentation
LogStream::LogStream () inline
Definition at line 77 of file rc_logger.h.
                :   stream_ptr(s)
     { }
Member Function Documentation
LogStream::buffer (this) inline
Definition at line 80 of file rc_logger.h.
     :   std::ostream(&buffer), buffer(this)
     { }
unsigned LogStream::get_level () inline
Definition at line 82 of file rc_logger.h.
References level_index.
Referenced by LogBuffer::flush().
     { return iword(level_index); }
Member Data Documentation
LogStream::__pad0__
Definition at line 80 of file rc_logger.h.
LogBuffer LogStream::buffer private
Definition at line 73 of file rc_logger.h.
const int LogStream::level_index = std::ios::xalloc() static
Definition at line 76 of file rc_logger.h.
Referenced by get_level(), and operator<<().
The documentation for this class was generated from the following file:
include/util/rc_logger.h