Visible: rcEngineFocusData Class Reference
rcEngineFocusData Class Reference
#include <include/visiCore/rc_engineimplbase.h>
Public Member Functions
rcEngineFocusData (rcWriterManager *writerManager, const rcRect &analysisRect, const rcRect &imageRect, uint32 imageCount, rcAnalysisMode analysisMode, uint32 sizeLimit, uint32 slidingWindowSize, rcAnalyzerResultOrigin slidingWindowOrigin, uint32 &groupCount, uint32 maxSpeed, int treatmentObjectType, int32 cellType)
~rcEngineFocusData ()
rcScalarWriter * cFreqWriter ()
rcScalarWriter * cMeanFreqWriter ()
rcScalarWriter * cShortnWriter ()
rcScalarWriter * cMeanShortnWriter ()
rcScalarWriter * energyWriter ()
rcScalarWriter * slidingEnergyWriter ()
rcScalarWriter * energyPeriodWriter ()
rcScalarWriter * cellCountWriter ()
rcScalarWriter * cellSpeedMeanWriter ()
rcScalarWriter * cellMeanSquareDisplacement ()
rcScalarWriter * cellPersistenceMeanWriter ()
rcScalarWriter * cellObjectPersistenceMeanWriter ()
rcScalarWriter * cellCellPersistenceMeanWriter ()
rcScalarWriter * cellAxisXMeanWriter ()
rcScalarWriter * cellAxisYMeanWriter ()
rcScalarWriter * cellMajorMeanWriter ()
rcScalarWriter * cellMinorMeanWriter ()
rcScalarWriter * cellCircMeanWriter ()
rcScalarWriter * cellEllipseMeanWriter ()
rcScalarWriter * tipDistanceWriter ()
rcGraphicsWriter * plotterWriter ()
rcVideoWriter * developmentVideoWriter ()
rcGraphicsWriter * developmentGraphicsWriter ()
const rcRect & focusRect () const
rcRect & focusRect ()
const vector< double > & cellCountResults () const
vector< double > & cellCountResults ()
const vector< rcTimestamp > & timeStamps () const
vector< rcTimestamp > & timeStamps ()
void createCellWriters ()
void writeFocusData (rcTimestamp currentTime, int32 i)
void flushFocusData ()
void clearFocusData ()
void setTrackStartTimes (rcTimestamp start)
void setCellTrackStartTimes (rcTimestamp start)
Private Attributes
rcWriterManager * mWriterManager
rcScalarWriter * mcShortnWriter
rcScalarWriter * mcMeanShortnWriter
rcScalarWriter * mCfreqWriter
rcScalarWriter * mcMeanFreqWriter
rcScalarWriter * mEnergyWriter
rcScalarWriter * mSlidingEnergyWriter
rcScalarWriter * mPeriodEnergyWriter
rcScalarWriter * mCellCountWriter
rcScalarWriter * mCellSpeedMeanWriter
rcScalarWriter * mCellPersistenceMeanWriter
rcScalarWriter * mCellObjectPersistenceMeanWriter
rcScalarWriter * mCellCellPersistenceMeanWriter
rcScalarWriter * mCellMeanSquareDisplacementWriter
rcScalarWriter * mCellAxisXMeanWriter
rcScalarWriter * mCellAxisYMeanWriter
rcScalarWriter * mCellMajorMeanWriter
rcScalarWriter * mCellMinorMeanWriter
rcScalarWriter * mCellCircMeanWriter
rcScalarWriter * mCellEllipseMeanWriter
rcScalarWriter * mTipDistanceWriter
rcGraphicsWriter * mPlotterWriter
rcVideoWriter * mDevelopmentVideoWriter
rcGraphicsWriter * mDevelopmentGraphicsWriter
rcCellWriterGroupCollection * mCellWriters
rcScalarWriter * mCellLengthWriter
rcPositionWriter * mCellBoundsWriter
rcRect mAnalysisRect
rcRect mImageRect
rcWriterGroup * mWriterGroup
vector< double > mCellCountResults
vector< rcTimestamp > mTimeStamps
uint32 mMaxSpeed
vector< rcWriter * > mGlobalWriters
vector< rcWriter * > mGlobalCellWriters
Detailed Description
Definition at line 193 of file rc_engineimplbase.h.
Constructor & Destructor Documentation
rcEngineFocusData::rcEngineFocusData (rcWriterManager * writerManager, const rcRect & analysisRect, const rcRect & imageRect, uint32 imageCount, rcAnalysisMode analysisMode, uint32 sizeLimit, uint32 slidingWindowSize, rcAnalyzerResultOrigin slidingWindowOrigin, uint32 & groupCount, uint32 maxSpeed, int treatmentObjectType, int32 cellType)
Definition at line 25 of file rc_engineimplfocus.cpp.
References cAnalysisCellGeneral, cAnalysisCellMuscle, cAnalysisCellMuscleCalcium, cAnalysisCellMuscleSelected, cAnalysisLabeledFluorescence, cAnalysisOrganismFluCluster, cMeasurementWriterGroupStrings, createCellWriters(), rcWriterManager::createGraphicsWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), rcWriterManager::createWriterGroup(), rcVideoWriter::down_cast(), rcScalarWriter::down_cast(), rcGraphicsWriter::down_cast(), eAnalysisACI, eAnalysisACISlidingWindow, eAnalysisCellTracking, eAnalysisTemplateTracking, eAnalyzerResultOriginCenter, eAnalyzerResultOriginLeft, eAnalyzerResultOriginRight, eGroupSemanticsGlobalMeasurements, eWindowOriginCenter, eWindowOriginLeft, eWindowOriginRight, eWriterACI, eWriterACIPeriod, eWriterACIWindow, eWriterBodyBodyPersistenceMean, eWriterBodyCircularityMean, eWriterBodyEllipseRatioMean, eWriterBodyMajorMean, eWriterBodyMeanSquareDisplacements, eWriterBodyPersistenceMean, eWriterBodyScaleXMean, eWriterBodyScaleYMean, eWriterBodySpeedMean, eWriterCardiacShorteningMean, eWriterCellCount, eWriterContractionFreqMean, eWriterGraphicsDevelopment, eWriterPlotter, eWriterTipDistance, eWriterVideoDevelopment, rcWriter::getDescription(), rcWriter::getName(), rcRectangle< T >::height(), mCellAxisXMeanWriter, mCellAxisYMeanWriter, mCellCellPersistenceMeanWriter, mCellCircMeanWriter, mCellCountWriter, mCellEllipseMeanWriter, mCellMajorMeanWriter, mCellMeanSquareDisplacementWriter, mCellPersistenceMeanWriter, mCellSpeedMeanWriter, mcMeanFreqWriter, mcMeanShortnWriter, mDevelopmentGraphicsWriter, mDevelopmentVideoWriter, mEnergyWriter, mGlobalCellWriters, mGlobalWriters, mPeriodEnergyWriter, mPlotterWriter, mSlidingEnergyWriter, mTipDistanceWriter, mWriterGroup, mWriterManager, rcWriterManager::optionString(), rmAssert, rmDim, rmUnused, rcWriter::setDescription(), rcWriter::setName(), rcRectangle< T >::width(), rcRect::x(), and rcRect::y().
                                                                                               :
         mWriterManager( writerManager ),
     mcShortnWriter (0),
     mcMeanShortnWriter (0),
         mCfreqWriter (0),
         mcMeanFreqWriter (0),
         mEnergyWriter( 0 ),
         mSlidingEnergyWriter( 0 ),
         mPeriodEnergyWriter( 0 ),
         mCellCountWriter( 0 ),
         mCellSpeedMeanWriter( 0 ),
         mCellPersistenceMeanWriter( 0 ),
         mCellObjectPersistenceMeanWriter( 0 ),
         mCellCellPersistenceMeanWriter( 0 ),
         mCellMeanSquareDisplacementWriter( 0 ),
         mCellAxisXMeanWriter( 0 ),
         mCellAxisYMeanWriter( 0 ),
         mCellMajorMeanWriter( 0 ),
         mCellMinorMeanWriter( 0 ),
         mTipDistanceWriter( 0 ),
         mDevelopmentVideoWriter( 0 ),
         mDevelopmentGraphicsWriter( 0 ),
         mCellWriters( 0 ),
         mCellLengthWriter( 0 ),
         mCellBoundsWriter( 0 ),
         mAnalysisRect( analysisRect ),
         mImageRect( imageRect ),
         mWriterGroup( 0 ),
         mMaxSpeed( maxSpeed )
 {
     rmAssert( mWriterManager );
     rmUnused( imageCount );
     // Create default writer group
     std::string name = cMeasurementWriterGroupStrings[0];
     std::string descr = cMeasurementWriterGroupStrings[1];
     char buf[128];
     snprintf( buf, rmDim( buf ), " %i", ++groupCount );
     name += buf;
     snprintf( buf, rmDim( buf ), " area [%i %i %i %i]",
               analysisRect.x(), analysisRect.y(), analysisRect.width(), analysisRect.height() );
     descr += buf;
     mWriterGroup = mWriterManager->createWriterGroup( name.c_str(),
                                                       descr.c_str(),
                                                       eGroupSemanticsGlobalMeasurements );
 // @note ADD_Track
     switch ( analysisMode ) {
         case eAnalysisACISlidingWindow:
         {
             rcWriterWindowOrigin origin = eWindowOriginLeft;
             switch ( slidingWindowOrigin ) {
                 case eAnalyzerResultOriginLeft:
                     origin = eWindowOriginLeft;
                     break;
                 case eAnalyzerResultOriginCenter:
                     origin = eWindowOriginCenter;
                     break;
                 case eAnalyzerResultOriginRight:
                     origin = eWindowOriginRight;
                     break;
             }
             mSlidingEnergyWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                                                        eWriterACIWindow,
                                                                        sizeLimit,
                                                                        analysisRect,
                                                                        0.0,   // expected min
                                                                        1.0 ); // expected max
             rcWriter* writer =  mSlidingEnergyWriter->down_cast();
             mGlobalWriters.push_back( writer );
             // Add a human-readable string listing window options to track name and description
             std::string optionString = rcWriterManager::optionString( eWriterACIWindow, origin, slidingWindowSize );
             std::string nameWithOptions = writer->getName() + optionString;
             std::string descrWithOptions = writer->getDescription() + optionString;
             writer->setName( nameWithOptions.c_str() );
             writer->setDescription( descrWithOptions.c_str() );
             mPeriodEnergyWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                                                        eWriterACIPeriod,
                                                                        sizeLimit,
                                                                        analysisRect,
                                                                        0.0,   // expected min
                                                                        1.0 ); // expected max
             writer =  mPeriodEnergyWriter->down_cast();
             mGlobalWriters.push_back( writer );
             // Add a human-readable string listing window options to track name and description
         optionString = rcWriterManager::optionString( eWriterACIPeriod, origin, slidingWindowSize );
             nameWithOptions = writer->getName() + optionString;
             descrWithOptions = writer->getDescription() + optionString;
             writer->setName( nameWithOptions.c_str() );
             writer->setDescription( descrWithOptions.c_str() );
         }
         break;
             case eAnalysisTemplateTracking:
         {
             mTipDistanceWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                                                 eWriterTipDistance,
                                                                 sizeLimit,
                                                                 analysisRect,
                                                                 0.0,   // expected min
                                                                 256.0 ); // expected max
             rcWriter* writer =  mTipDistanceWriter->down_cast();
             mGlobalWriters.push_back(writer);
             // Add a human-readable string listing window options to track name and description
             std::string nameWithOptions = writer->getName();
             std::string descrWithOptions = writer->getDescription();
             writer->setName( nameWithOptions.c_str() );
             writer->setDescription( descrWithOptions.c_str() );
             // TODO: add a human-readable string listing analysis options to track name and description
         }
         case eAnalysisACI:
         {
             mEnergyWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                                                 eWriterACI,
                                                                 sizeLimit,
                                                                 analysisRect,
                                                                 0.0,   // expected min
                                                                 1.0 ); // expected max
             rcWriter* writer =  mEnergyWriter->down_cast();
             mGlobalWriters.push_back(writer);
             mPeriodEnergyWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                                                        eWriterACIPeriod,
                                                                        sizeLimit,
                                                                        analysisRect,
                                                                        0.0,   // expected min
                                                                        1.0 ); // expected max
             writer =  mPeriodEnergyWriter->down_cast();
             mGlobalWriters.push_back( writer );
             // Add a human-readable string listing window options to track name and description
             std::string nameWithOptions = writer->getName();
             std::string descrWithOptions = writer->getDescription();
             writer->setName( nameWithOptions.c_str() );
             writer->setDescription( descrWithOptions.c_str() );
             // TODO: add a human-readable string listing analysis options to track name and description
         }
         break;
             default:
             break;
 #if 0
         case eAnalysisCellTracking:
         {
             // Writer for total cell count
             mCellCountWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                                                    eWriterCellCount,
                                                                    sizeLimit,
                                                                    analysisRect,
                                                                    0.0,     // expected min
                                                                    300.0 ); // expected max
             mGlobalCellWriters.push_back( mCellCountWriter->down_cast() );
         switch (cellType)
           {
           case cAnalysisCellGeneral:
           case cAnalysisOrganismFluCluster:
           case cAnalysisLabeledFluorescence:
         // Writer for square of cell displacements
         mCellMeanSquareDisplacementWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                             eWriterBodyMeanSquareDisplacements,
                                             sizeLimit,
                                             analysisRect,
                                             0.0,
                                             20.0 );
         mGlobalCellWriters.push_back( mCellMeanSquareDisplacementWriter->down_cast() );
         // Writer for mean cell speed
         // TODO: get better min/max values from kinetoscope params
         mCellSpeedMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                        eWriterBodySpeedMean,
                                        sizeLimit,
                                        analysisRect,
                                        0.0,    // expected min
                                        10.0 ); // expected max
         mGlobalCellWriters.push_back( mCellSpeedMeanWriter->down_cast() );
         mCellPersistenceMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                          eWriterBodyPersistenceMean,
                                          sizeLimit,
                                          analysisRect,
                                          -1.0,     // expected min
                                          1.0 );    // expected max
         mGlobalCellWriters.push_back( mCellPersistenceMeanWriter->down_cast() );
         // Cell-to-cell persistence
         mCellCellPersistenceMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                              eWriterBodyBodyPersistenceMean,
                                              sizeLimit,
                                              analysisRect,
                                              -1.0,     // expected min
                                              1.0 );    // expected max
         mGlobalCellWriters.push_back( mCellCellPersistenceMeanWriter->down_cast() );
         // Writer for mean X axis scale percentage
         // TODO: get better min/max values from kinetoscope params
         mCellAxisXMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                        eWriterBodyScaleXMean,
                                        sizeLimit,
                                        analysisRect,
                                        50.0,    // expected min
                                        200.0 ); // expected max
         mGlobalCellWriters.push_back( mCellAxisXMeanWriter->down_cast() );
         // Writer for mean Y axis scale percentage
         // TODO: get better min/max values from kinetoscope params
         mCellAxisYMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                        eWriterBodyScaleYMean,
                                        sizeLimit,
                                        analysisRect,
                                        50.0,    // expected min
                                        200.0 ); // expected max
         mGlobalCellWriters.push_back( mCellAxisYMeanWriter->down_cast() );
         // Circularity Ratio
         mCellCircMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                       eWriterBodyCircularityMean,
                                       sizeLimit,
                                       analysisRect,
                                       0.0,    // expected min
                                       1.0 ); // expected max
         mGlobalCellWriters.push_back( mCellCircMeanWriter->down_cast() );
         // Ellipse Ratio
         mCellEllipseMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                          eWriterBodyEllipseRatioMean,
                                          sizeLimit,
                                          analysisRect,
                                          0.1,    // expected min
                                          10.0 ); // expected max
         mGlobalCellWriters.push_back( mCellEllipseMeanWriter->down_cast() );
         break;
           case cAnalysisCellMuscle:
           case cAnalysisCellMuscleSelected:
           case cAnalysisCellMuscleCalcium:
         {
           // TODO: get better min/max values from kinetoscope params
           mCellMajorMeanWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                          eWriterBodyMajorMean,
                                          sizeLimit,
                                          analysisRect,
                                          10.0,    // expected min
                                          200.0 ); // expected max
           mGlobalCellWriters.push_back( mCellMajorMeanWriter->down_cast() );
           mcMeanShortnWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                          eWriterCardiacShorteningMean,
                                          sizeLimit,
                                          analysisRect,
                                          0.01,    // expected min
                                          1.0 ); // expected max
           mGlobalCellWriters.push_back( mcMeanShortnWriter->down_cast() );
           // TODO: get better min/max values from kinetoscope params
           mcMeanFreqWriter = mWriterManager->createScalarWriter( mWriterGroup,
                                          eWriterContractionFreqMean,
                                          sizeLimit,
                                          analysisRect,
                                          0.1,    // expected min
                                          10.0 ); // expected max
           mGlobalCellWriters.push_back( mcMeanFreqWriter->down_cast() );
           break;
         }
           }
             createCellWriters();
         }
         break;
 #endif
     }
     // Developement/debugging writers
     mDevelopmentVideoWriter = mWriterManager->createVideoWriter( mWriterGroup,
                                                                  eWriterVideoDevelopment,
                                                                  sizeLimit,
                                                                  analysisRect );
     mGlobalWriters.push_back( mDevelopmentVideoWriter->down_cast() );
     mDevelopmentGraphicsWriter = mWriterManager->createGraphicsWriter( mWriterGroup,
                                                                        eWriterGraphicsDevelopment,
                                                                        sizeLimit,
                                                                        analysisRect );
     mGlobalWriters.push_back( mDevelopmentGraphicsWriter->down_cast() );
     // Plotting Graphics
     mPlotterWriter = mWriterManager->createGraphicsWriter( mWriterGroup,
                                eWriterPlotter,
                                sizeLimit,
                                analysisRect );
     mGlobalWriters.push_back( mPlotterWriter->down_cast() );
}
rcEngineFocusData::~rcEngineFocusData ()
Definition at line 359 of file rc_engineimplfocus.cpp.
References mCellAxisXMeanWriter, mCellAxisYMeanWriter, mCellBoundsWriter, mCellCellPersistenceMeanWriter, mCellCircMeanWriter, mCellCountWriter, mCellEllipseMeanWriter, mCellLengthWriter, mCellMeanSquareDisplacementWriter, mCellObjectPersistenceMeanWriter, mCellPersistenceMeanWriter, mCellSpeedMeanWriter, mDevelopmentGraphicsWriter, mDevelopmentVideoWriter, mEnergyWriter, mGlobalCellWriters, mGlobalWriters, mPeriodEnergyWriter, mSlidingEnergyWriter, and mWriterGroup.
 {
     // The writers will be freed by observer, just reset the pointers
     mWriterGroup = 0;
     mEnergyWriter = 0;
     mSlidingEnergyWriter = 0;
     mPeriodEnergyWriter = 0;
     mCellCountWriter = 0;
     mCellSpeedMeanWriter = 0;
     mCellPersistenceMeanWriter = 0;
     mCellObjectPersistenceMeanWriter = 0;
     mCellCellPersistenceMeanWriter = 0;
     mCellMeanSquareDisplacementWriter = 0;
     mCellBoundsWriter = 0;
     mCellLengthWriter = 0;
     mDevelopmentVideoWriter = 0;
     mDevelopmentGraphicsWriter = 0;
     mCellCircMeanWriter = 0;
     mCellEllipseMeanWriter = 0;
     mCellAxisYMeanWriter = 0;
     mCellAxisXMeanWriter = 0;
     mGlobalWriters.clear();
     mGlobalCellWriters.clear();
 }
Member Function Documentation
rcScalarWriter* rcEngineFocusData::cellAxisXMeanWriter () inline
Definition at line 221 of file rc_engineimplbase.h.
 { return mCellAxisXMeanWriter; }
rcScalarWriter* rcEngineFocusData::cellAxisYMeanWriter () inline
Definition at line 222 of file rc_engineimplbase.h.
 { return mCellAxisYMeanWriter; }
rcScalarWriter* rcEngineFocusData::cellCellPersistenceMeanWriter () inline
Definition at line 220 of file rc_engineimplbase.h.
 { return mCellCellPersistenceMeanWriter; }
rcScalarWriter* rcEngineFocusData::cellCircMeanWriter () inline
Definition at line 225 of file rc_engineimplbase.h.
 { return mCellCircMeanWriter; }
const vector<double>& rcEngineFocusData::cellCountResults () const inline
Definition at line 237 of file rc_engineimplbase.h.
 { return mCellCountResults; }
vector<double>& rcEngineFocusData::cellCountResults () inline
Definition at line 238 of file rc_engineimplbase.h.
 { return mCellCountResults; }
rcScalarWriter* rcEngineFocusData::cellCountWriter () inline
Definition at line 215 of file rc_engineimplbase.h.
 { return mCellCountWriter; }
rcScalarWriter* rcEngineFocusData::cellEllipseMeanWriter () inline
Definition at line 226 of file rc_engineimplbase.h.
 { return mCellEllipseMeanWriter; }
rcScalarWriter* rcEngineFocusData::cellMajorMeanWriter () inline
Definition at line 223 of file rc_engineimplbase.h.
 {return mCellMajorMeanWriter;}
rcScalarWriter* rcEngineFocusData::cellMeanSquareDisplacement () inline
Definition at line 217 of file rc_engineimplbase.h.
 { return mCellMeanSquareDisplacementWriter; }
rcScalarWriter* rcEngineFocusData::cellMinorMeanWriter () inline
Definition at line 224 of file rc_engineimplbase.h.
 {return mCellMinorMeanWriter;}
rcScalarWriter* rcEngineFocusData::cellObjectPersistenceMeanWriter () inline
Definition at line 219 of file rc_engineimplbase.h.
 { return mCellObjectPersistenceMeanWriter; }
rcScalarWriter* rcEngineFocusData::cellPersistenceMeanWriter () inline
Definition at line 218 of file rc_engineimplbase.h.
 { return mCellPersistenceMeanWriter; }
rcScalarWriter* rcEngineFocusData::cellSpeedMeanWriter () inline
Definition at line 216 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::muscleTracker().
 { return mCellSpeedMeanWriter; }
rcScalarWriter* rcEngineFocusData::cFreqWriter () inline
Definition at line 207 of file rc_engineimplbase.h.
 { return mCfreqWriter; }
void rcEngineFocusData::clearFocusData ()
Definition at line 388 of file rc_engineimplfocus.cpp.
References mCellCountResults, and mTimeStamps.
 {
     mCellCountResults.clear();
     mTimeStamps.clear();
 }
rcScalarWriter* rcEngineFocusData::cMeanFreqWriter () inline
Definition at line 208 of file rc_engineimplbase.h.
 { return mcMeanFreqWriter; }
rcScalarWriter* rcEngineFocusData::cMeanShortnWriter () inline
Definition at line 210 of file rc_engineimplbase.h.
 { return mcMeanShortnWriter;  }
void rcEngineFocusData::createCellWriters ()
Referenced by rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::cShortnWriter () inline
Definition at line 209 of file rc_engineimplbase.h.
 { return mcShortnWriter;  }
rcGraphicsWriter* rcEngineFocusData::developmentGraphicsWriter () inline
Definition at line 230 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::produceDebugResults().
 { return mDevelopmentGraphicsWriter; }
rcVideoWriter* rcEngineFocusData::developmentVideoWriter () inline
Definition at line 229 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::produceDebugResults().
 { return mDevelopmentVideoWriter; }
rcScalarWriter* rcEngineFocusData::energyPeriodWriter () inline
Definition at line 214 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::entropyTrackerWindow().
 { return mPeriodEnergyWriter; }
rcScalarWriter* rcEngineFocusData::energyWriter () inline
Definition at line 212 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::entropyTracker(), and rcEngineImpl::writeEntropyData().
 { return mEnergyWriter; }
void rcEngineFocusData::flushFocusData ()
Definition at line 410 of file rc_engineimplfocus.cpp.
References flush(), mGlobalCellWriters, and mGlobalWriters.
Referenced by rcEngineImpl::analyzeFocusArea(), rcEngineImpl::frameFlush(), rcEngineBaseImpl::writeData(), and writeFocusData().
 {
     for ( uint32 i = 0; i < mGlobalWriters.size(); ++i )
         mGlobalWriters[i]->flush();
     for ( uint32 i = 0; i < mGlobalCellWriters.size(); ++i )
         mGlobalCellWriters[i]->flush();
         //    if ( mCellWriters != 0 ) mCellWriters->flush();
 }
const rcRect& rcEngineFocusData::focusRect () const inline
Definition at line 234 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::analyzeFocusArea(), rcEngineImpl::entropyTrackerWindow(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcEngineImpl::processCapturedData(), rcEngineImpl::produceDebugResults(), rcEngineImpl::writeEntropyData(), writeFocusData(), rcEngineImpl::writeTimedFloats(), and rcEngineImpl::writeTimedScalar().
 { return mAnalysisRect; }
rcRect& rcEngineFocusData::focusRect () inline
Definition at line 235 of file rc_engineimplbase.h.
 { return mAnalysisRect; }
rcGraphicsWriter* rcEngineFocusData::plotterWriter () inline
Definition at line 228 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::writeEntropyData().
 { return mPlotterWriter; }
void rcEngineFocusData::setCellTrackStartTimes (rcTimestamp start)
Definition at line 344 of file rc_engineimplfocus.cpp.
References mGlobalCellWriters.
 {
      for ( uint32 i = 0; i < mGlobalCellWriters.size(); ++i ) {
         mGlobalCellWriters[i]->setTrackStart( start );
     }
 }
void rcEngineFocusData::setTrackStartTimes (rcTimestamp start)
Definition at line 336 of file rc_engineimplfocus.cpp.
References mGlobalWriters.
Referenced by rcEngineImpl::modelTracker(), and rcEngineImpl::muscleTracker().
 {
     for ( uint32 i = 0; i < mGlobalWriters.size(); ++i ) {
         mGlobalWriters[i]->setTrackStart( start );
     }
 }
rcScalarWriter* rcEngineFocusData::slidingEnergyWriter () inline
Definition at line 213 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::entropyTrackerWindow(), and rcEngineImpl::processCapturedData().
 { return mSlidingEnergyWriter; }
const vector<rcTimestamp>& rcEngineFocusData::timeStamps () const inline
Definition at line 240 of file rc_engineimplbase.h.
Referenced by rcEngineBaseImpl::writeData().
 { return mTimeStamps; }
vector<rcTimestamp>& rcEngineFocusData::timeStamps () inline
Definition at line 241 of file rc_engineimplbase.h.
 { return mTimeStamps; }
rcScalarWriter* rcEngineFocusData::tipDistanceWriter () inline
Definition at line 227 of file rc_engineimplbase.h.
Referenced by rcEngineImpl::modelTracker().
 { return mTipDistanceWriter;}
void rcEngineFocusData::writeFocusData (rcTimestamp currentTime, int32 i)
Definition at line 395 of file rc_engineimplfocus.cpp.
References flushFocusData(), focusRect(), mCellCountResults, mCellCountWriter, and rcScalarWriter::writeValue().
Referenced by rcEngineBaseImpl::writeData().
 {
     if ( i >= 0 ) {
         // Locomotive Body count
         if ( mCellCountWriter != 0 ) {
             if ( uint32(i) < mCellCountResults.size() ) {
                 mCellCountWriter->writeValue( currentTime, focusRect(), mCellCountResults[i] );
             }
         }
     } else {
         flushFocusData();
     }
 }
Member Data Documentation
rcRect rcEngineFocusData::mAnalysisRect private
Definition at line 290 of file rc_engineimplbase.h.
rcScalarWriter* rcEngineFocusData::mCellAxisXMeanWriter private
Definition at line 275 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellAxisYMeanWriter private
Definition at line 276 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcPositionWriter* rcEngineFocusData::mCellBoundsWriter private
Definition at line 288 of file rc_engineimplbase.h.
Referenced by ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellCellPersistenceMeanWriter private
Definition at line 273 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellCircMeanWriter private
Definition at line 279 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
vector<double> rcEngineFocusData::mCellCountResults private
Definition at line 295 of file rc_engineimplbase.h.
Referenced by clearFocusData(), and writeFocusData().
rcScalarWriter* rcEngineFocusData::mCellCountWriter private
Definition at line 269 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), writeFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellEllipseMeanWriter private
Definition at line 280 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellLengthWriter private
Definition at line 287 of file rc_engineimplbase.h.
Referenced by ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellMajorMeanWriter private
Definition at line 277 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellMeanSquareDisplacementWriter private
Definition at line 274 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellMinorMeanWriter private
Definition at line 278 of file rc_engineimplbase.h.
rcScalarWriter* rcEngineFocusData::mCellObjectPersistenceMeanWriter private
Definition at line 272 of file rc_engineimplbase.h.
Referenced by ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellPersistenceMeanWriter private
Definition at line 271 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mCellSpeedMeanWriter private
Definition at line 270 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcCellWriterGroupCollection* rcEngineFocusData::mCellWriters private
Definition at line 285 of file rc_engineimplbase.h.
rcScalarWriter* rcEngineFocusData::mCfreqWriter private
Definition at line 264 of file rc_engineimplbase.h.
rcScalarWriter* rcEngineFocusData::mcMeanFreqWriter private
Definition at line 265 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mcMeanShortnWriter private
Definition at line 263 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mcShortnWriter private
Definition at line 262 of file rc_engineimplbase.h.
rcGraphicsWriter* rcEngineFocusData::mDevelopmentGraphicsWriter private
Definition at line 284 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcVideoWriter* rcEngineFocusData::mDevelopmentVideoWriter private
Definition at line 283 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mEnergyWriter private
Definition at line 266 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
vector<rcWriter*> rcEngineFocusData::mGlobalCellWriters private
Definition at line 299 of file rc_engineimplbase.h.
Referenced by flushFocusData(), rcEngineFocusData(), setCellTrackStartTimes(), and ~rcEngineFocusData().
vector<rcWriter*> rcEngineFocusData::mGlobalWriters private
Definition at line 298 of file rc_engineimplbase.h.
Referenced by flushFocusData(), rcEngineFocusData(), setTrackStartTimes(), and ~rcEngineFocusData().
rcRect rcEngineFocusData::mImageRect private
Definition at line 291 of file rc_engineimplbase.h.
uint32 rcEngineFocusData::mMaxSpeed private
Definition at line 297 of file rc_engineimplbase.h.
rcScalarWriter* rcEngineFocusData::mPeriodEnergyWriter private
Definition at line 268 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcGraphicsWriter* rcEngineFocusData::mPlotterWriter private
Definition at line 282 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData().
rcScalarWriter* rcEngineFocusData::mSlidingEnergyWriter private
Definition at line 267 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
vector<rcTimestamp> rcEngineFocusData::mTimeStamps private
Definition at line 296 of file rc_engineimplbase.h.
Referenced by clearFocusData().
rcScalarWriter* rcEngineFocusData::mTipDistanceWriter private
Definition at line 281 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData().
rcWriterGroup* rcEngineFocusData::mWriterGroup private
Definition at line 292 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData(), and ~rcEngineFocusData().
rcWriterManager* rcEngineFocusData::mWriterManager private
Definition at line 261 of file rc_engineimplbase.h.
Referenced by rcEngineFocusData().
The documentation for this class was generated from the following files:
include/visiCore/rc_engineimplbase.h
src/visible/src/rc_engineimplfocus.cpp