Visible: rcSharedMemoryUser Class Reference
rcSharedMemoryUser Class Reference
#include <include/util/rc_resource_ctrl.h>
Public Member Functions
void * acquireSharedMemory (rcSharedMemError &err, bool wait=TRUE)
rcSharedMemError releaseSharedMemory ()
Private Member Functions
rcSharedMemoryUser (const rcSharedMemoryUser &)
rcSharedMemoryUser & operator= (const rcSharedMemoryUser &)
rcSharedMemoryUser (const struct sembuf &bufAvailSem, const struct sembuf &returnBufSem, int semSetId, void *shmemP, uint8 ownSharedMem, const rcAtomicValue< uint8 > &peerDead)
rcSharedMemError forceRelease ()
Private Attributes
struct sembuf _bufAvailSem
struct sembuf _returnBufSem
int _semSetId
void * _shmemP
uint8 _ownSharedMem
const rcAtomicValue< uint8 > & _peerDead
Friends
class rcExecWithShmem
class rcCreateChildShmem
void * rcResCtrlWatchdog (void *shMemAddr)
Detailed Description
Definition at line 30 of file rc_resource_ctrl.h.
Constructor & Destructor Documentation
rcSharedMemoryUser::rcSharedMemoryUser (const rcSharedMemoryUser &) private
rcSharedMemoryUser::rcSharedMemoryUser (const struct sembuf & bufAvailSem, const struct sembuf & returnBufSem, int semSetId, void * shmemP, uint8 ownSharedMem, const rcAtomicValue< uint8 > & peerDead) private
Definition at line 89 of file rc_resource_ctrl.cpp.
References _shmemP.
   : _bufAvailSem(bufAvailSem), _returnBufSem(returnBufSem), _semSetId(semSetId),
     _shmemP(shmemP), _ownSharedMem(ownSharedMem), _peerDead(peerDead)
 {
   assert(_shmemP);
 }
Member Function Documentation
void * rcSharedMemoryUser::acquireSharedMemory (rcSharedMemError & err, bool wait = TRUE)
Definition at line 100 of file rc_resource_ctrl.cpp.
References _bufAvailSem, _ownSharedMem, _peerDead, _semSetId, _shmemP, rcAtomicValue< T >::getValue(), NULL, rcSharedMemNoError, rcSharedMemNotAvailable, rcSharedMemPeerDead, rcSharedMemSemopError, and TRUE.
Referenced by rcQVideoGrabber::getAcqInfo(), getCtrlInfo(), rcQVideoGrabber::getNextFrame(), rcQVideoGrabber::setAcqControl(), writeAcqInfo(), and yourDisplayCallback().
 {
   err = rcSharedMemNoError;
   //printf("acquireSharedMemory\n");
   uint8 pDead = 0;
   if (_peerDead.getValue(pDead)) // Check that peer is alive
   {
     err = rcSharedMemPeerDead;
     return NULL;
   }
   if (_ownSharedMem)
     return _shmemP;
   _bufAvailSem.sem_op = -1;
   _bufAvailSem.sem_flg = wait ? 0 : IPC_NOWAIT;
   /* Try to decrement the semaphore to zero.
    */
   if (semop(_semSetId, &_bufAvailSem, 1) == 0) // Command succeeded
   {
     /* Verify that peer didn't die while acquiring buffer
      */
     if (_peerDead.getValue(pDead))
     {
       err = rcSharedMemPeerDead;
       return NULL;
     }
     _ownSharedMem = TRUE;
     return _shmemP;
   }
   /* If we're here the operation failed. If wait is true and errno is
    * EAGAIN, the current value of the semaphore is zero.
    */
   if (!wait && (errno == EAGAIN))
     err = rcSharedMemNotAvailable;
   else
     err = rcSharedMemSemopError;
   return NULL;
 }
rcSharedMemError rcSharedMemoryUser::forceRelease () private
Definition at line 170 of file rc_resource_ctrl.cpp.
References _bufAvailSem, _semSetId, rcSharedMemNoError, and rcSharedMemSemopError.
Referenced by rcResCtrlWatchdog().
 {
   _bufAvailSem.sem_op = 1;
   _bufAvailSem.sem_flg = 0;
   /* Try to increment the semaphore to one.
    */
   if (semop(_semSetId, &_bufAvailSem, 1) == 0) // Command succeeded
     return rcSharedMemNoError;
   return rcSharedMemSemopError;
 }
rcSharedMemoryUser& rcSharedMemoryUser::operator= (const rcSharedMemoryUser &) private
rcSharedMemError rcSharedMemoryUser::releaseSharedMemory ()
Definition at line 147 of file rc_resource_ctrl.cpp.
References _ownSharedMem, _returnBufSem, _semSetId, FALSE, rcSharedMemNoError, rcSharedMemNotLocked, and rcSharedMemSemopError.
Referenced by rcQVideoGrabber::getAcqInfo(), rcQVideoGrabber::getNextFrame(), releaseMemory(), and rcQVideoGrabber::setAcqControl().
 {
     //printf("releaseSharedMemory\n");
   if (!_ownSharedMem)
     return rcSharedMemNotLocked;
   _returnBufSem.sem_op = 1;
   _returnBufSem.sem_flg = 0;
   /* Try to increment the semaphore to one.
    */
   if (semop(_semSetId, &_returnBufSem, 1) == 0) // Command succeeded
   {
     _ownSharedMem = FALSE;
     return rcSharedMemNoError;
   }
   return rcSharedMemSemopError;
 }
Friends And Related Function Documentation
friend class rcCreateChildShmem friend
Definition at line 32 of file rc_resource_ctrl.h.
friend class rcExecWithShmem friend
Definition at line 31 of file rc_resource_ctrl.h.
void* rcResCtrlWatchdog (void * shMemAddr) friend
Definition at line 30 of file rc_resource_ctrl.cpp.
 {
   assert(watchInfoAddr);
   watchdogInfo& wdInfo = *(watchdogInfo*)watchInfoAddr;
   assert(wdInfo.shMemUser);
   assert(wdInfo.readP);
   assert(wdInfo.writeP);
   fprintf(stderr, "Watchdog starting up ra 0x%X wa 0x%X\n",
      (unsigned int)(wdInfo.readP), (unsigned int)(wdInfo.writeP));
   uint16 lastValueRead = 0;    // Last value read from peer
   uint16 checkCount = 0;       // # of times read has occurred without change
   uint16 lastValueWritten = 0; // Last value written to peer
   uint8  shutdown;
   for (; wdInfo.shutdown.getValue(shutdown) == 0;)
   {
     /* First, check to see that peer is alive.
      */
     uint16 curRead;
     if (wdInfo.readP->getValue(curRead) == lastValueRead)
     {
       if (!mpDebugging && (checkCount++ >= WD_MAX_REPEATS))
       {
     fprintf(stderr, "peer dead\n");
     /* Peer appears dead. Notify the rest of the process and quit thread.
      */
     wdInfo.peerDead.setValue(1);
     /* Make sure processing thread awakens.
      */
     rcSharedMemError err;
     if ((err = wdInfo.shMemUser->forceRelease()) != rcSharedMemNoError)
       fprintf(stderr, "Error on call to forceRelease %d\n", err);
     fprintf(stderr, "returning from watchdog on death\n");
     return 0;
       }
     }
     else
     {
       lastValueRead = curRead;
       checkCount = 0;
     }
     /* Next, let peer know we are still alive.
      */
     wdInfo.writeP->setValue(++lastValueWritten);
     /* Finally, sleep for a while before repeating.
      */
     usleep(WD_US_TO_SLEEP);
   }
   fprintf(stderr, "returning from watchdog on shutdown\n");
   return 0;
 }
Member Data Documentation
struct sembuf rcSharedMemoryUser::_bufAvailSem private
Definition at line 89 of file rc_resource_ctrl.h.
Referenced by acquireSharedMemory(), and forceRelease().
uint8 rcSharedMemoryUser::_ownSharedMem private
Definition at line 93 of file rc_resource_ctrl.h.
Referenced by acquireSharedMemory(), and releaseSharedMemory().
const rcAtomicValue<uint8>& rcSharedMemoryUser::_peerDead private
Definition at line 94 of file rc_resource_ctrl.h.
Referenced by acquireSharedMemory().
struct sembuf rcSharedMemoryUser::_returnBufSem private
Definition at line 90 of file rc_resource_ctrl.h.
Referenced by releaseSharedMemory().
int rcSharedMemoryUser::_semSetId private
Definition at line 91 of file rc_resource_ctrl.h.
Referenced by acquireSharedMemory(), forceRelease(), and releaseSharedMemory().
void* rcSharedMemoryUser::_shmemP private
Definition at line 92 of file rc_resource_ctrl.h.
Referenced by acquireSharedMemory(), and rcSharedMemoryUser().
The documentation for this class was generated from the following files:
include/util/rc_resource_ctrl.h
src/util/code/rc_resource_ctrl.cpp