Visible: rcMoviePlaybackStatus Class Reference
rcMoviePlaybackStatus Class Reference
#include <include/visiCore/rc_playbackregs.h>
Public Member Functions
rcMoviePlaybackStatus ()
void state (rcMoviePlaybackState playbackState)
Public Member Functions inherited from rcMoviePlaybackStatusReader
rcMoviePlaybackStatusReader ()
virtual ~rcMoviePlaybackStatusReader ()
rcMoviePlaybackState getState () const
Additional Inherited Members
Protected Attributes inherited from rcMoviePlaybackStatusReader
rcAtomicValue
< rcMoviePlaybackState > _playbackState
Detailed Description
Definition at line 76 of file rc_playbackregs.h.
Constructor & Destructor Documentation
rcMoviePlaybackStatus::rcMoviePlaybackStatus () inline
Definition at line 79 of file rc_playbackregs.h.
                           : rcMoviePlaybackStatusReader()
   { }
Member Function Documentation
void rcMoviePlaybackStatus::state (rcMoviePlaybackState playbackState) inline
Definition at line 82 of file rc_playbackregs.h.
References rcMoviePlaybackStatusReader::_playbackState, and rcAtomicValue< T >::setValue().
Referenced by rcEngineMoviePlayback::playbackCleanup(), rcEngineMoviePlayback::reset(), rcEngineMoviePlayback::run(), and rcEngineMoviePlayback::setupTimeCtrlPlayback().
   { _playbackState.setValue(playbackState); }
The documentation for this class was generated from the following file:
include/visiCore/rc_playbackregs.h