Visible: TCP_server Class Reference
TCP_server Class Reference
#include <include/stlplus/tcp.hpp>
Public Member Functions
TCP_server (void)
TCP_server (unsigned short port, unsigned short queue)
~TCP_server (void)
TCP_server (const TCP_server &)
TCP_server & operator= (const TCP_server &)
bool initialise (unsigned short port, unsigned short queue)
bool initialised (void) const
int error (void) const
std::string message (void) const
bool close (void)
bool connection_ready (unsigned wait)
TCP_connection connection (void)
Private Attributes
smart_ptr< TCP_server_data > m_data
Friends
class TCP_server_data
Detailed Description
Definition at line 63 of file tcp.hpp.
Constructor & Destructor Documentation
TCP_server::TCP_server (void)
Definition at line 635 of file tcp.cpp.
                            : m_data(TCP_server_data())
 {
 }
TCP_server::TCP_server (unsigned short port, unsigned short queue)
Definition at line 639 of file tcp.cpp.
References initialise().
                                                                 : m_data(TCP_server_data())
 {
   initialise(port,queue);
 }
TCP_server::~TCP_server (void)
Definition at line 644 of file tcp.cpp.
 {
 }
TCP_server::TCP_server (const TCP_server & server)
Definition at line 648 of file tcp.cpp.
 {
   *this = server;
 }
Member Function Documentation
bool TCP_server::close (void)
Definition at line 679 of file tcp.cpp.
References TCP_server_data::close(), and m_data.
 {
   return m_data->close();
 }
TCP_connection TCP_server::connection (void)
Definition at line 689 of file tcp.cpp.
References TCP_server_data::connection(), and m_data.
 {
   return m_data->connection();
 }
bool TCP_server::connection_ready (unsigned wait)
Definition at line 684 of file tcp.cpp.
References TCP_server_data::connection_ready(), and m_data.
 {
   return m_data->connection_ready(wait);
 }
int TCP_server::error (void) const
Definition at line 669 of file tcp.cpp.
References TCP_server_data::error(), and m_data.
 {
   return m_data->error();
 }
bool TCP_server::initialise (unsigned short port, unsigned short queue)
Definition at line 659 of file tcp.cpp.
References TCP_server_data::initialise(), and m_data.
Referenced by TCP_server().
 {
   return m_data->initialise(port,queue);
 }
bool TCP_server::initialised (void) const
Definition at line 664 of file tcp.cpp.
References TCP_server_data::initialised(), and m_data.
 {
   return m_data->initialised();
 }
std::string TCP_server::message (void) const
Definition at line 674 of file tcp.cpp.
References m_data, and TCP_server_data::message().
 {
   return m_data->message();
 }
TCP_server & TCP_server::operator= (const TCP_server & server)
Definition at line 653 of file tcp.cpp.
References m_data.
 {
   m_data = server.m_data;
   return *this;
 }
Friends And Related Function Documentation
friend class TCP_server_data friend
Definition at line 83 of file tcp.hpp.
Member Data Documentation
smart_ptr<TCP_server_data> TCP_server::m_data private
Definition at line 84 of file tcp.hpp.
Referenced by close(), connection(), connection_ready(), error(), initialise(), initialised(), message(), and operator=().
The documentation for this class was generated from the following files:
include/stlplus/tcp.hpp
include/stlplus/tcp.cpp