Visible: rcModifierKeys Class Reference
rcModifierKeys Class Reference
#include <include/visUI/rc_modifierkeys.h>
Static Public Member Functions
static bool isShiftDown (QMouseEvent *mouseEvent)
static bool isShiftDown (QKeyEvent *keyEvent)
static bool isCtrlDown (QMouseEvent *mouseEvent)
static bool isCtrlDown (QKeyEvent *keyEvent)
static bool isAltDown (QMouseEvent *mouseEvent)
static bool isAltDown (QKeyEvent *keyEvent)
Detailed Description
Definition at line 14 of file rc_modifierkeys.h.
Member Function Documentation
bool rcModifierKeys::isAltDown (QMouseEvent * mouseEvent) static
Definition at line 53 of file rc_modifierkeys.cpp.
Referenced by rcTimeline::keyPressEvent().
 {
     if ( mouseEvent ) {
         if ( mouseEvent->state() & Qt::AltModifier )
             return true;
     }
     return false;
 }
bool rcModifierKeys::isAltDown (QKeyEvent * keyEvent) static
Definition at line 63 of file rc_modifierkeys.cpp.
 {
     if ( keyEvent ) {
         if ( keyEvent->state() & Qt::AltButton )
             return true;
     }
     return false;
 }
bool rcModifierKeys::isCtrlDown (QMouseEvent * mouseEvent) static
Definition at line 32 of file rc_modifierkeys.cpp.
Referenced by rcScalarTrackWidget::keyPressEvent(), rcTimeline::keyPressEvent(), rcTimeline::mouseMoveEvent(), and rcTimeline::mouseReleaseEvent().
 {
     if ( mouseEvent ) {
         if ( mouseEvent->state() & Qt::ControlModifier )
             return true;
     }
     return false;
 }
bool rcModifierKeys::isCtrlDown (QKeyEvent * keyEvent) static
Definition at line 42 of file rc_modifierkeys.cpp.
 {
     if ( keyEvent ) {
         if ( keyEvent->state() & Qt::ControlButton )
             return true;
     }
     return false;
 }
bool rcModifierKeys::isShiftDown (QMouseEvent * mouseEvent) static
Definition at line 11 of file rc_modifierkeys.cpp.
Referenced by rcTimeline::keyPressEvent(), rcTimeline::mouseMoveEvent(), and rcTimeline::mouseReleaseEvent().
 {
     if ( mouseEvent ) {
         if ( mouseEvent->state() & Qt::ShiftModifier )
             return true;
     }
     return false;
 }
bool rcModifierKeys::isShiftDown (QKeyEvent * keyEvent) static
Definition at line 21 of file rc_modifierkeys.cpp.
 {
     if ( keyEvent ) {
         if ( keyEvent->state() & Qt::ShiftButton )
             return true;
     }
     return false;
 }
The documentation for this class was generated from the following files:
include/visUI/rc_modifierkeys.h
src/visible/qt/rc_modifierkeys.cpp