Visible: rcMotionVectorPath Class Reference
rcMotionVectorPath Class Reference
#include <include/analysis/rc_motionpath.h>
Public Member Functions
rcMotionVectorPath ()
virtual ~rcMotionVectorPath ()
rcMotionVectorPath (rcKinetoscope *kin, const rc2Fvector &anchor)
rcMotionVectorPath (rcKinetoscope *kin, const rc2Fvector &anchor, const rc2Fvector &displacement)
const rc2Fvector position () const
const rc2Fvector & anchor () const
position Position with respect to the image from it was created from
const rc2Fvector & anchor (const rc2Fvector &a)
rcIPair iAnchor () const
const rc2Fvector & motion () const
void move (const rc2Fvector &t)
virtual void measure ()
virtual void update ()
virtual void reconcile ()
const boost::shared_ptr
< rcKinetoscope > sharedKin () const
bool operator< (const rcMotionVectorPath &r) const
Private Member Functions
void parabolicDisparity (const rcRect &, const rcRect &)
float match (const rcWindow &fixed, rcWindow &moving, const rcIPair &searchSpace, rcCorr &maxCorr, rcIPair &maxPos, vector< vector< float > > &mSpace)
float _match_u8 (const rcWindow &fixed, rcWindow &moving, const rcIPair &searchSpace, rcCorr &maxCorr, rcIPair &maxPos, vector< vector< float > > &mSpace)
float _match_u16 (const rcWindow &fixed, rcWindow &moving, const rcIPair &searchSpace, rcCorr &maxCorr, rcIPair &maxPos, vector< vector< float > > &mSpace)
float _match_u32 (const rcWindow &fixed, rcWindow &moving, const rcIPair &searchSpace, rcCorr &maxCorr, rcIPair &maxPos, vector< vector< float > > &mSpace)
Private Attributes
boost::shared_ptr< rcKinetoscope > mKine
rc2Fvector mStartPosition
rc2Fvector mDxDt
rc2Fvector mACF
vector< uint8 > mSplat
Friends
ostream & operator<< (ostream &, const rcMotionVectorPath &)
Detailed Description
Definition at line 521 of file rc_motionpath.h.
Constructor & Destructor Documentation
rcMotionVectorPath::rcMotionVectorPath ()
Definition at line 235 of file rc_motionpath.cpp.
References rcKinetoscope::eSplatArea, and mSplat.
 {
     mSplat.resize (rcKinetoscope::eSplatArea);
 }
virtual rcMotionVectorPath::~rcMotionVectorPath () inline virtual
Definition at line 526 of file rc_motionpath.h.
 {}
rcMotionVectorPath::rcMotionVectorPath (rcKinetoscope * kin, const rc2Fvector & anchor)
Definition at line 240 of file rc_motionpath.cpp.
References anchor(), rcKinetoscope::eSplatArea, and mSplat.
                                                                                  :
 mKine ( kin )
 {
     anchor (anch);
     mSplat.resize (rcKinetoscope::eSplatArea);
}
rcMotionVectorPath::rcMotionVectorPath (rcKinetoscope * kin, const rc2Fvector & anchor, const rc2Fvector & displacement)
Definition at line 247 of file rc_motionpath.cpp.
References anchor(), rcKinetoscope::eSplatArea, mACF, and mSplat.
 : mKine ( kin )
 {
     anchor(anch);
     mSplat.resize (rcKinetoscope::eSplatArea);
     mACF = disp;
 }
Member Function Documentation
float rcMotionVectorPath::_match_u16 (const rcWindow & fixed, rcWindow & moving, const rcIPair & searchSpace, rcCorr & maxCorr, rcIPair & maxPos, vector< vector< float > > & mSpace) private
Definition at line 491 of file rc_motionpath.cpp.
Referenced by match().
float rcMotionVectorPath::_match_u32 (const rcWindow & fixed, rcWindow & moving, const rcIPair & searchSpace, rcCorr & maxCorr, rcIPair & maxPos, vector< vector< float > > & mSpace) private
Definition at line 492 of file rc_motionpath.cpp.
Referenced by match().
float rcMotionVectorPath::_match_u8 (const rcWindow & fixed, rcWindow & moving, const rcIPair & searchSpace, rcCorr & maxCorr, rcIPair & maxPos, vector< vector< float > > & mSpace) private
Definition at line 490 of file rc_motionpath.cpp.
Referenced by match().
const rc2Fvector& rcMotionVectorPath::anchor () const inline
position Position with respect to the image from it was created from
Definition at line 546 of file rc_motionpath.h.
References mStartPosition.
Referenced by operator<<(), rcMotionVectorPath(), and reconcile().
 { return mStartPosition; }
const rc2Fvector& rcMotionVectorPath::anchor (const rc2Fvector & a) inline
Definition at line 548 of file rc_motionpath.h.
References mStartPosition.
   {
     mStartPosition = a;
     return mStartPosition;
   }
rcIPair rcMotionVectorPath::iAnchor () const inline
Definition at line 554 of file rc_motionpath.h.
References mStartPosition, rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by measure().
   {
     return rcIPair (int32 (mStartPosition.x()),
             int32 (mStartPosition.y()));
   }
float rcMotionVectorPath::match (const rcWindow & fixed, rcWindow & moving, const rcIPair & searchSpace, rcCorr & maxCorr, rcIPair & maxPos, vector< vector< float > > & mSpace) inline private
Definition at line 611 of file rc_motionpath.h.
References _match_u16(), _match_u32(), _match_u8(), rcWindow::depth(), rcPixel16, rcPixel32, rcPixel8, and rmAssert.
Referenced by parabolicDisparity().
   {
     if (fixed.depth() == rcPixel8)
       return _match_u8(fixed, moving, searchSpace, maxCorr, maxPos, mSpace);
     if (fixed.depth() == rcPixel32)
       return _match_u32(fixed, moving, searchSpace, maxCorr, maxPos, mSpace);
     if (fixed.depth() == rcPixel16)
       return _match_u16(fixed, moving, searchSpace, maxCorr, maxPos, mSpace);
     rmAssert (0);
   }
void rcMotionVectorPath::measure () virtual
Definition at line 278 of file rc_motionpath.cpp.
References iAnchor(), parabolicDisparity(), sharedKin(), rcPair< T >::x(), and rcPair< T >::y().
 {
     // Anchor is the center of the origin pixel. This is
     // Independent of target sizes and gradient filter sizes
     // MovingSize is 1 + radius * 2 of the search area -- hence divide by 2
     //
     rcIPair anc (iAnchor ());
     rcIPair span = sharedKin()->movingSize ();
     rcIPair target = sharedKin()->target ();
     rcIRect fixed (anc.x() - target.x(), anc.y() - target.y(),
                    target.x()+target.x()+1, target.y()+target.y()+1);
     rcIRect moving (anc.x() - span.x(), anc.y() - span.y(),
                     span.x()+span.x()+1, span.y()+span.y()+1);
     if (sharedKin()->isWithin(fixed) &&  sharedKin()->isWithin(moving))
         parabolicDisparity (fixed, moving);
 }
const rc2Fvector& rcMotionVectorPath::motion () const inline
Definition at line 560 of file rc_motionpath.h.
References mDxDt.
Referenced by operator<<(), and reconcile().
 { return mDxDt; }
void rcMotionVectorPath::move (const rc2Fvector & t) inline
Definition at line 562 of file rc_motionpath.h.
References mDxDt.
Referenced by parabolicDisparity().
   {
     mDxDt = t;
   }
bool rcMotionVectorPath::operator< (const rcMotionVectorPath & r) const
void rcMotionVectorPath::parabolicDisparity (const rcRect & fixed, const rcRect & moving) private
Definition at line 308 of file rc_motionpath.cpp.
References rcWindow::depth(), rcKinetoscope::eSplatArea, rcRectangle< T >::height(), match(), move(), mSplat, parabolicFit(), rcPixel8, rmAssert, sharedKin(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by measure().
 {
     float maxScore (0.0);
     rcPair<bool> edge;
     rc2Fvector interp;
     rcCorr maxCorr;
     vector<vector<float> > mSpace;
     // Size and create search space
     const rcIPair searchSpace (moving.width() - fixed.width() + 1,
                                moving.height() - fixed.height() + 1);
     rc2Fvector origin (searchSpace);
     rcIPair maxPos = searchSpace;
     vector<float> score (rcKinetoscope::eSplatArea);
     origin /= 2.0f;
     bool fastCorr = sharedKin()->use4fixed().depth() == rcPixel8 &&
     searchSpace.y() == 5 && searchSpace.x() == 5 &&
     sharedKin()->isPointCorrOptimizationAvailable ();
         {
         rcWindow fixedw (sharedKin()->use4fixed(), fixed);
         rcWindow movingw (sharedKin()->use4moving(), moving);
         rmAssert (fixedw.depth() == movingw.depth());
         maxScore = match (fixedw, movingw, searchSpace, maxCorr, maxPos, mSpace);
         edge.y() = !(maxPos.y() > 0 && maxPos.y() < (searchSpace.y() - 1));
         edge.x() = !(maxPos.x() > 0 && maxPos.x() < (searchSpace.x() - 1));
         if (!edge.x() && !edge.y())
         {
             score[0] = mSpace[maxPos.y()-1][maxPos.x()-1];
             score[1] = mSpace[maxPos.y()-1][maxPos.x()];
             score[2] = mSpace[maxPos.y()-1][maxPos.x()+1];
             score[3] = mSpace[maxPos.y()][maxPos.x()-1];
             score[4] = mSpace[maxPos.y()][maxPos.x()];
             score[5] = mSpace[maxPos.y()][maxPos.x()+1];
             score[6] = mSpace[maxPos.y()+1][maxPos.x()-1];
             score[7] = mSpace[maxPos.y()+1][maxPos.x()];
             score[8] = mSpace[maxPos.y()+1][maxPos.x()+1];
         }
     if (!edge.x() && !edge.y())
     {
         static float * dnull (0);
         interp = rc2Fvector (parabolicFit (score [3], score [4], score [5], dnull),
                              parabolicFit (score[1], score [4], score [7], dnull));
         for (uint32 i = 0; i < score.size();i++)
         {
             mSplat[i] = uint8 (255 * score[i]);
         }
         interp += rc2Fvector (maxPos.x()+0.5f, maxPos.y()+0.5f);
         interp -= origin;
     }
     // @note We do this here to avoid calling update
     move (interp);
         }
 }
const rc2Fvector rcMotionVectorPath::position () const inline
Definition at line 537 of file rc_motionpath.h.
References mDxDt, and mStartPosition.
   {
     return mDxDt + mStartPosition;
   }
void rcMotionVectorPath::reconcile () virtual
Definition at line 403 of file rc_motionpath.cpp.
References anchor(), rcKinetoscope::eSplatSize, rcWindow::isWithin(), rc2dVector< T >::l2(), mKine, motion(), mSplat, rcWindow::pelPointer(), rmAssertDebug, rcPair< T >::x(), and rcPair< T >::y().
 {
     // When we implement pyramid processing, this
     // will be added the logic to take the low resolution
     // motion vectors and check them at a higher
     // resolution
     // For now it is assumed that we only have one
     // level pyramid
     // See how prependicular are ACF and motion. We want them as prependicular as possible
     // Which means we want to dot product between the two vectors to be as close to 0 as possible
     // Adding Velocity Fields
     //  rcFeature d16 (motion ());
     //   rcIPair ip = iAnchor ();
     //   mKine->velocityXfield().setPixel (ip.x(), ip.y(), (uint32) (d16.pos16().x().real()));
     //   mKine->velocityYfield().setPixel (ip.x(), ip.y(), (uint32) (d16.pos16().y().real()));
     if (motion() == rc2Fvector()) return;
     float l2 = motion().l2();
     // @note default setting
     if (l2 < 0.0025) return;
     rcWindow& connect = mKine->connect();
     const rcWindow& moving = mKine->use4moving();
     rcIPair pt2 ((int32) (anchor().x() + motion().x()),
                  (int32) (anchor().y() + motion().y()));
     rcIPair target (rcKinetoscope::eSplatSize / 2);
     vector<uint8>::const_iterator sp = mSplat.begin();
     for (int32 j =  - target.y(); j <= target.y(); j++)
         for (int32 i =  - target.x(); i <= target.x(); i++)
         {
             rcIPair pt = pt2 + rcIPair (i, j);
             rmAssertDebug (connect.isWithin(pt));
             uint8 *pp = (uint8 *) connect.pelPointer (pt.x(), pt.y());
             uint8 *mm = (uint8 *) moving.pelPointer (pt.x(), pt.y());
             *pp = (*sp++ * *mm++) >> 8;
         }
 }
const boost::shared_ptr<rcKinetoscope> rcMotionVectorPath::sharedKin () const inline
Definition at line 588 of file rc_motionpath.h.
References mKine.
Referenced by measure(), and parabolicDisparity().
   {
     return mKine;
   }
void rcMotionVectorPath::update () virtual
Definition at line 303 of file rc_motionpath.cpp.
 {
     //  move (mNewFeature.pos());
 }
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const rcMotionVectorPath & p) friend
Definition at line 374 of file rc_motionpath.cpp.
 {
     o << "--------------------------" << endl;
     o << "Trace    :" << p.motion() << endl;
     o << "Anchor   :" << p.anchor() << endl;
     //  o << "Siblings :" << p.sharedKin()->refCount () << endl;
     o << "--------------------------" << endl;
     return o;
 }
Member Data Documentation
rc2Fvector rcMotionVectorPath::mACF private
Definition at line 607 of file rc_motionpath.h.
Referenced by rcMotionVectorPath().
rc2Fvector rcMotionVectorPath::mDxDt private
Definition at line 606 of file rc_motionpath.h.
Referenced by motion(), move(), and position().
boost::shared_ptr<rcKinetoscope> rcMotionVectorPath::mKine private
Definition at line 604 of file rc_motionpath.h.
Referenced by reconcile(), and sharedKin().
vector<uint8> rcMotionVectorPath::mSplat private
Definition at line 608 of file rc_motionpath.h.
Referenced by parabolicDisparity(), rcMotionVectorPath(), and reconcile().
rc2Fvector rcMotionVectorPath::mStartPosition private
Definition at line 605 of file rc_motionpath.h.
Referenced by anchor(), iAnchor(), and position().
The documentation for this class was generated from the following files:
include/analysis/rc_motionpath.h
src/analysis/code/rc_motionpath.cpp