Visible: rcMovieFileConvExt Class Reference
rcMovieFileConvExt Class Reference
#include <include/visual/rc_moviefileformat.h>
Public Member Functions
rcMovieFileConvExt ()
rcMovieFileConvExt (uint32 so, uint32 fc, uint32 sm, const rcRect &r, movieChannelType ch, float frameInterval, bool pixelsRev, const char *c)
bool write (FILE *saveStream) const
ostream & log (ostream &os) const
void fixEndian (const reByteOrder &fileByteOrder)
const uint32 & startOffset () const
const uint32 & frameCount () const
const uint32 & sample () const
const rcRect & cropRect () const
const int64 & date () const
const movieChannelType & channel () const
const float & frameInterval () const
const movieFormatRev & rev () const
const char * creatorName () const
const uint16 & pixelsReversed () const
const int32 & id () const
void id (const int32 &i)
Public Member Functions inherited from rcMovieFileExt
rcMovieFileExt ()
rcMovieFileExt (movieExtensionType t)
rcMovieFileExt (movieExtensionType t, int64 o)
const movieExtensionType & type () const
const int64 & offset () const
bool write (FILE *saveStream) const
void fixEndian (const reByteOrder &fileByteOrder)
Private Attributes
uint32 mStartOffset
uint32 mFrameCount
uint32 mSample
rcRect mCropRect
int64 mDate
movieChannelType mChannel
float mFrameInterval
movieFormatRev mRev
char mComment [64]
int32 mId
uint16 mPixelsReversed
Detailed Description
Definition at line 319 of file rc_moviefileformat.h.
Constructor & Destructor Documentation
rcMovieFileConvExt::rcMovieFileConvExt ()
Definition at line 418 of file rc_moviefileformat.cpp.
References mComment, and rmDim.
                                        :
         rcMovieFileExt(movieExtensionCNV, sizeof(rcMovieFileConvExt)),
         mStartOffset(0), mFrameCount(0), mSample(1), mDate( getCurrentTimestamp() ),
         mChannel( movieChannelUnknown ), mFrameInterval(0.0),
         mRev(movieFormatRevLatest), mId( 0 ), mPixelsReversed(false)
 {
     memset( mComment, 0, rmDim(mComment) );
     snprintf( mComment, rmDim(mComment), "Unknown" );
}
rcMovieFileConvExt::rcMovieFileConvExt (uint32 so, uint32 fc, uint32 sm, const rcRect & r, movieChannelType ch, float frameInterval, bool pixelsRev, const char * c)
Definition at line 428 of file rc_moviefileformat.cpp.
References mComment, and rmDim.
                                                                      :
         rcMovieFileExt(movieExtensionCNV, sizeof(rcMovieFileConvExt)),
         mStartOffset(so), mFrameCount(fc), mSample(sm), mCropRect(r),
         mDate(getCurrentTimestamp()), mChannel(ch), mFrameInterval(frameInt),
         mRev(movieFormatRevLatest), mId( 0 ), mPixelsReversed(pixRev)
 {
     memset( mComment, 0, rmDim(mComment) );
     if ( c )
         snprintf( mComment, rmDim(mComment), "%s", c );
     else
         snprintf( mComment, rmDim(mComment), "Unknown" );
}
Member Function Documentation
const movieChannelType& rcMovieFileConvExt::channel () const inline
Definition at line 341 of file rc_moviefileformat.h.
References mChannel.
Referenced by rcGenMovieFile::flush(), log(), and operator<<().
 { return mChannel; };
const char* rcMovieFileConvExt::creatorName () const inline
Definition at line 344 of file rc_moviefileformat.h.
References mComment.
Referenced by log(), and operator<<().
 { return mComment; };
const rcRect& rcMovieFileConvExt::cropRect () const inline
Definition at line 339 of file rc_moviefileformat.h.
References mCropRect.
Referenced by log(), and operator<<().
 { return mCropRect; };
const int64& rcMovieFileConvExt::date () const inline
Definition at line 340 of file rc_moviefileformat.h.
References mDate.
Referenced by log(), and operator<<().
 { return mDate; };
void rcMovieFileConvExt::fixEndian (const reByteOrder & fileByteOrder)
Definition at line 461 of file rc_moviefileformat.cpp.
References ByteSwapN, rcMovieFileExt::fixEndian(), rcRectangle< T >::lr(), mChannel, mCropRect, mDate, mFrameCount, mFrameInterval, mId, mPixelsReversed, mRev, mSample, mStartOffset, rfPlatformByteOrder(), rcRect::x(), rcPair< T >::x(), rcRect::y(), and rcPair< T >::y().
Referenced by rcVideoCache::cnvLoad(), and write().
 {
     if ( rfPlatformByteOrder() != fileByteOrder )
     {
         rcMovieFileExt::fixEndian (fileByteOrder);
         ByteSwapN (mStartOffset);                // First frame from input movie
         ByteSwapN (mFrameCount);                 // Number of frames
         ByteSwapN (mSample);                     // Sample interval
         int32 x = mCropRect.x(), y = mCropRect.y();
         int32 lrx = mCropRect.lr().x(), lry = mCropRect.lr().y();
         ByteSwapN (x), ByteSwapN (y), ByteSwapN (lrx), ByteSwapN (lry);
         mCropRect = rcIRect (rcIPair (x, y), rcIPair (lrx, lry));
         ByteSwapN (mDate);                       // Conversion date
         ByteSwapN ( mChannel);
         ByteSwapN (mFrameInterval);              // Frame interval in seconds
         ByteSwapN ( mRev);
         ByteSwapN (mId);                         // Unique id, reserved for future use
         ByteSwapN (mPixelsReversed);
     }
 }
const uint32& rcMovieFileConvExt::frameCount () const inline
Definition at line 337 of file rc_moviefileformat.h.
References mFrameCount.
Referenced by log(), and operator<<().
 { return mFrameCount; };
const float& rcMovieFileConvExt::frameInterval () const inline
Definition at line 342 of file rc_moviefileformat.h.
References mFrameInterval.
Referenced by log(), and operator<<().
 { return mFrameInterval; };
const int32& rcMovieFileConvExt::id (void) const inline
Definition at line 346 of file rc_moviefileformat.h.
References mId.
Referenced by rcGenMovieFile::flush(), and operator<<().
 { return mId; }
void rcMovieFileConvExt::id (const int32 & i) inline
Definition at line 349 of file rc_moviefileformat.h.
References mId.
 { mId = i; }
ostream & rcMovieFileConvExt::log (ostream & os) const
Definition at line 485 of file rc_moviefileformat.cpp.
References channel(), creatorName(), cropRect(), date(), endl(), frameCount(), frameInterval(), rcTimestamp::localtime(), pixelsReversed(), rev(), sample(), and startOffset().
Referenced by rcEngineImpl::updateConversionLog().
 {
     os << "Conversion date: " << rcTimestamp(date()).localtime() << endl;
     os << " FileRev " << rev() << " FrameOffset: " << startOffset()
        << " FrameCount: " << frameCount() << endl;
     os << " FrameInterval " << frameInterval()
        << " Sample: " << sample() << endl;
     os << " CropRect: " << cropRect()
        << " Channel: " << channel() << endl;
     os << " PixelsReversed: ";
     if ( pixelsReversed() )
         os << "yes" << endl;
     else
         os << "no" << endl;
     os << " Converter: " << creatorName() << endl;
     return os;
 }
const uint16& rcMovieFileConvExt::pixelsReversed () const inline
Definition at line 345 of file rc_moviefileformat.h.
References mPixelsReversed.
Referenced by log(), and operator<<().
 { return mPixelsReversed; };
const movieFormatRev& rcMovieFileConvExt::rev () const inline
Definition at line 343 of file rc_moviefileformat.h.
References mRev.
Referenced by log(), and operator<<().
 { return mRev; };
const uint32& rcMovieFileConvExt::sample () const inline
Definition at line 338 of file rc_moviefileformat.h.
References mSample.
Referenced by log(), and operator<<().
 { return mSample; };
const uint32& rcMovieFileConvExt::startOffset () const inline
Definition at line 336 of file rc_moviefileformat.h.
References mStartOffset.
Referenced by log(), and operator<<().
 { return mStartOffset; };
bool rcMovieFileConvExt::write (FILE * saveStream) const
Definition at line 446 of file rc_moviefileformat.cpp.
References eByteOrderBigEndian, fixEndian(), rfPlatformByteOrder(), and rfPlatformByteOrderMark().
Referenced by rcGenMovieFile::flush().
 {
     if ( rfPlatformByteOrder() != eByteOrderBigEndian ) {
         const_cast<rcMovieFileConvExt *>(this)->fixEndian (rfPlatformByteOrder(rfPlatformByteOrderMark()) );
     }
     if (fwrite(this, sizeof(*this), 1, saveStream) != 1) {
         perror("CNV hdr fwrite failed");
         if (fclose(saveStream))
             perror("fclose failed");
         return true;
     }
     return false;
 }
Member Data Documentation
movieChannelType rcMovieFileConvExt::mChannel private
Definition at line 358 of file rc_moviefileformat.h.
Referenced by channel(), and fixEndian().
char rcMovieFileConvExt::mComment[64] private
Definition at line 362 of file rc_moviefileformat.h.
Referenced by creatorName(), and rcMovieFileConvExt().
rcRect rcMovieFileConvExt::mCropRect private
Definition at line 356 of file rc_moviefileformat.h.
Referenced by cropRect(), and fixEndian().
int64 rcMovieFileConvExt::mDate private
Definition at line 357 of file rc_moviefileformat.h.
Referenced by date(), and fixEndian().
uint32 rcMovieFileConvExt::mFrameCount private
Definition at line 353 of file rc_moviefileformat.h.
Referenced by fixEndian(), and frameCount().
float rcMovieFileConvExt::mFrameInterval private
Definition at line 359 of file rc_moviefileformat.h.
Referenced by fixEndian(), and frameInterval().
int32 rcMovieFileConvExt::mId private
Definition at line 363 of file rc_moviefileformat.h.
Referenced by fixEndian(), and id().
uint16 rcMovieFileConvExt::mPixelsReversed private
Definition at line 364 of file rc_moviefileformat.h.
Referenced by fixEndian(), and pixelsReversed().
movieFormatRev rcMovieFileConvExt::mRev private
Definition at line 361 of file rc_moviefileformat.h.
Referenced by fixEndian(), and rev().
uint32 rcMovieFileConvExt::mSample private
Definition at line 354 of file rc_moviefileformat.h.
Referenced by fixEndian(), and sample().
uint32 rcMovieFileConvExt::mStartOffset private
Definition at line 352 of file rc_moviefileformat.h.
Referenced by fixEndian(), and startOffset().
The documentation for this class was generated from the following files:
include/visual/rc_moviefileformat.h
src/visual/code/rc_moviefileformat.cpp