Visible: rcSharedFrameBufPtr Class Reference
rcSharedFrameBufPtr Class Reference
#include <include/visual/rc_framebuf.h>
Public Member Functions
rcSharedFrameBufPtr ()
rcSharedFrameBufPtr (rcFrame *p)
rcSharedFrameBufPtr (const rcSharedFrameBufPtr &p)
~rcSharedFrameBufPtr ()
rcSharedFrameBufPtr & operator= (const rcSharedFrameBufPtr &p)
rcSharedFrameBufPtr & operator= (rcFrame *p)
void lock () const
void unlock () const
void prefetch () const
uint32 frameIndex () const
bool operator== (const rcSharedFrameBufPtr &p) const
bool operator!= (const rcSharedFrameBufPtr &p) const
bool operator== (const rcFrame *p) const
bool operator!= (const rcFrame *p) const
bool operator! () const
operator rcFrame * () const
const rcFrame & operator* () const
rcFrame & operator* ()
const rcFrame * operator-> () const
rcFrame * operator-> ()
int refCount () const
void printState () const
Private Member Functions
void setCachedFrame (rcSharedFrameBufPtr &p, uint32 cacheID, uint32 frameIndex)
void setCachedFrameIndex (uint32 cacheID, uint32 frameIndex)
void internalLock ()
void internalUnlock (bool force)
Static Private Member Functions
static rcMutex & getMutex ()
Private Attributes
uint32 mCacheCtrl
uint32 mFrameIndex
rcFrame * mFrameBuf
Static Private Attributes
static rcMutex * frameMutexP = 0
Friends
class rcVideoCache
Detailed Description
Definition at line 255 of file rc_framebuf.h.
Constructor & Destructor Documentation
rcSharedFrameBufPtr::rcSharedFrameBufPtr () inline
Definition at line 261 of file rc_framebuf.h.
       : mCacheCtrl ( 0 ), mFrameIndex ( 0 ), mFrameBuf( 0 ) { }
rcSharedFrameBufPtr::rcSharedFrameBufPtr (rcFrame * p) inline
Definition at line 263 of file rc_framebuf.h.
References rcFrame::addRef(), rcFrame::cacheCtrl(), endl(), rcFrame::frameIndex(), getMutex(), mCacheCtrl, mFrameBuf, mFrameIndex, and rcFrame::refCount().
       : mCacheCtrl ( 0 ), mFrameIndex ( 0 ), mFrameBuf( p ) {
         if (p) {
         mCacheCtrl = p->cacheCtrl();
         mFrameIndex = p->frameIndex();
     }
         if ( mFrameBuf ) {
         rcLock frmLock(getMutex());
 #ifdef DEBUG_MEM
         cerr << "rcSharedFrameBufPtr ctor " << mFrameBuf
          << " refCount " << mFrameBuf->refCount() << endl;
 #endif
             mFrameBuf->addRef();
     }
     }
rcSharedFrameBufPtr::rcSharedFrameBufPtr (const rcSharedFrameBufPtr & p) inline
Definition at line 278 of file rc_framebuf.h.
References rcFrame::addRef(), endl(), getMutex(), mFrameBuf, and rcFrame::refCount().
       : mCacheCtrl ( p.mCacheCtrl ), mFrameIndex ( p.mFrameIndex ),
         mFrameBuf( p.mFrameBuf ) {
     if ( mFrameBuf ) {
         rcLock frmLock(getMutex());
 #ifdef DEBUG_MEM
         cerr << "rcSharedFrameBufPtr ctor " << mFrameBuf
          << " refCount " << mFrameBuf->refCount() << endl;
 #endif
         mFrameBuf->addRef();
     }
     };
rcSharedFrameBufPtr::~rcSharedFrameBufPtr () inline
Definition at line 292 of file rc_framebuf.h.
References endl(), and internalUnlock().
{
 #ifdef DEBUG_MEM
         cerr << "rcSharedFrameBufPtr dtor " << endl;
 #endif
         internalUnlock(true);
     };
Member Function Documentation
uint32 rcSharedFrameBufPtr::frameIndex () const inline
Definition at line 391 of file rc_framebuf.h.
References mFrameIndex.
Referenced by setCachedFrame(), and setCachedFrameIndex().
{
         return mFrameIndex;
     }
rcMutex & rcSharedFrameBufPtr::getMutex () static private
Definition at line 16 of file rc_framebuf.cpp.
References frameMutexP.
Referenced by internalLock(), internalUnlock(), operator=(), rcSharedFrameBufPtr(), refCount(), and setCachedFrame().
 {
   if (!frameMutexP)
     frameMutexP = new rcMutex();
   return *frameMutexP;
 }
void rcSharedFrameBufPtr::internalLock () private
Definition at line 336 of file rc_framebuf.cpp.
References rcVideoCache::cacheLock(), endl(), getMutex(), mCacheCtrl, mFrameBuf, mFrameIndex, and rcFrame::refCount().
Referenced by lock().
 {
 #ifdef DEBUG_MEM
     cerr << "rcSharedFrameBufPtr lock: " << mFrameBuf << endl;
 #endif
     if ( !mFrameBuf && mCacheCtrl ) {
         rcVideoCacheStatus status;
     rcVideoCacheError error;
     status = rcVideoCache::cacheLock(mCacheCtrl, mFrameIndex, *this,
                      &error);
 #ifdef DEBUG_MEM
     cerr << "   Cached rcSharedFrameBufPtr " << mFrameBuf
          << " Status " << status << " refCount ";
     rcLock frmLock(getMutex());
     if ( mFrameBuf )
         cerr << mFrameBuf->refCount() << endl;
     else
         cerr << "UNDEFINED" << endl;
 #endif
     }
 }
void rcSharedFrameBufPtr::internalUnlock (bool force) private
Definition at line 358 of file rc_framebuf.cpp.
References rcVideoCache::cacheUnlock(), endl(), getMutex(), mCacheCtrl, mFrameBuf, mFrameIndex, rcFrame::refCount(), and rcFrame::remRef().
Referenced by operator=(), unlock(), and ~rcSharedFrameBufPtr().
 {
 #ifdef DEBUG_MEM
     cerr << "rcSharedFrameBufPtr unlock: " << mFrameBuf << endl;
 #endif
     if ( mFrameBuf && (mCacheCtrl || force)) {
         bool cacheUnlock = false;
         {
             rcLock frmLock(getMutex());
             mFrameBuf->remRef();
             if ((mFrameBuf->refCount() == 1) && mCacheCtrl)
                 cacheUnlock = true;
 #ifdef DEBUG_MEM
             cerr << "   refCount " << mFrameBuf->refCount()
                  << " cache unlock " << cacheUnlock << endl;
 #endif
             mFrameBuf = 0;
         }
         if (cacheUnlock)
             rcVideoCache::cacheUnlock(mCacheCtrl, mFrameIndex);
     }
 }
void rcSharedFrameBufPtr::lock () const inline
Definition at line 364 of file rc_framebuf.h.
References internalLock().
Referenced by operator rcFrame *(), operator*(), operator->(), and refCount().
                       {
       const_cast<rcSharedFrameBufPtr*>(this)->internalLock();
     }
rcSharedFrameBufPtr::operator rcFrame * () const inline
Definition at line 419 of file rc_framebuf.h.
References lock(), mCacheCtrl, and mFrameBuf.
{
       if ( !mFrameBuf && mCacheCtrl ) lock();
       return mFrameBuf;
     }
bool rcSharedFrameBufPtr::operator! (void) const inline
Definition at line 414 of file rc_framebuf.h.
References mCacheCtrl, and mFrameBuf.
{
         return ( ( mFrameBuf == 0 ) && (mCacheCtrl == 0));
     }
bool rcSharedFrameBufPtr::operator!= (const rcSharedFrameBufPtr & p) const inline
Definition at line 402 of file rc_framebuf.h.
References operator==().
{
         return !(this->operator==( p ));
     }
bool rcSharedFrameBufPtr::operator!= (const rcFrame * p) const inline
Definition at line 411 of file rc_framebuf.h.
References operator==().
{
       return !(this->operator==( p ));
     }
const rcFrame& rcSharedFrameBufPtr::operator* (void) const inline
Definition at line 423 of file rc_framebuf.h.
References lock(), mCacheCtrl, mFrameBuf, and rmAssertDebug.
{
       if ( !mFrameBuf && mCacheCtrl ) lock();
       rmAssertDebug( mFrameBuf );
       return *mFrameBuf;
     }
rcFrame& rcSharedFrameBufPtr::operator* (void) inline
Definition at line 428 of file rc_framebuf.h.
References lock(), mCacheCtrl, mFrameBuf, and rmAssertDebug.
{
       if ( !mFrameBuf && mCacheCtrl ) lock();
       rmAssertDebug( mFrameBuf );
       return *mFrameBuf;
     }
const rcFrame* rcSharedFrameBufPtr::operator-> (void) const inline
Definition at line 433 of file rc_framebuf.h.
References lock(), mCacheCtrl, and mFrameBuf.
{
       if ( !mFrameBuf && mCacheCtrl ) lock();
       return mFrameBuf;
     }
rcFrame* rcSharedFrameBufPtr::operator-> (void) inline
Definition at line 437 of file rc_framebuf.h.
References lock(), mCacheCtrl, and mFrameBuf.
{
       if ( !mFrameBuf && mCacheCtrl ) lock();
       return mFrameBuf;
     }
rcSharedFrameBufPtr& rcSharedFrameBufPtr::operator= (const rcSharedFrameBufPtr & p) inline
Definition at line 300 of file rc_framebuf.h.
References rcFrame::addRef(), endl(), getMutex(), internalUnlock(), mCacheCtrl, mFrameBuf, mFrameIndex, and rcFrame::refCount().
{
       if ( (mFrameBuf == p.mFrameBuf) && (mCacheCtrl == p.mCacheCtrl) &&
        (mFrameIndex == p.mFrameIndex) )
             return *this;
 #ifdef DEBUG_MEM
     {
         rcLock frmLock(getMutex());
         cerr << "rcSharedFrameBufPtr asss " << mFrameBuf;
         if ( mFrameBuf )
             cerr << " refCount " << mFrameBuf->refCount();
         cerr << " = " << p.mFrameBuf;
         if ( p.mFrameBuf )
             cerr << " refCount " << p.mFrameBuf->refCount();
         cerr << endl;
     }
 #endif
     internalUnlock(true);
     mCacheCtrl = p.mCacheCtrl;
     mFrameIndex = p.mFrameIndex;
         mFrameBuf = p.mFrameBuf;
         if ( mFrameBuf ) {
         rcLock frmLock(getMutex());
             mFrameBuf->addRef();
     }
         return *this;
     }
rcSharedFrameBufPtr& rcSharedFrameBufPtr::operator= (rcFrame * p) inline
Definition at line 327 of file rc_framebuf.h.
References rcFrame::addRef(), rcFrame::cacheCtrl(), endl(), rcFrame::frameIndex(), getMutex(), internalUnlock(), mCacheCtrl, mFrameBuf, mFrameIndex, and rcFrame::refCount().
{
       if ( (mFrameBuf == p) && (mFrameBuf || !mCacheCtrl) )
       return *this;
 #ifdef DEBUG_MEM
     {
         rcLock frmLock(getMutex());
         cerr << "rcSharedFrameBufPtr assp " << mFrameBuf;
         if ( mFrameBuf )
             cerr << " refCount " << mFrameBuf->refCount();
         cerr << " = " << p;
         if ( p )
             cerr << " refCount " << p->refCount();
         cerr << endl;
     }
 #endif
     internalUnlock(true);
         mFrameBuf = p;
         if ( mFrameBuf ) {
         mCacheCtrl = p->cacheCtrl();
         mFrameIndex = p->frameIndex();
         rcLock frmLock(getMutex());
             mFrameBuf->addRef();
     }
     else {
       mCacheCtrl = 0;
       mFrameIndex = 0;
     }
         return *this;
     }
bool rcSharedFrameBufPtr::operator== (const rcSharedFrameBufPtr & p) const inline
Definition at line 396 of file rc_framebuf.h.
References mCacheCtrl, mFrameBuf, and mFrameIndex.
Referenced by operator!=().
{
         if ( mCacheCtrl || p.mCacheCtrl )
         return ((mCacheCtrl == p.mCacheCtrl) &&
             (mFrameIndex == p.mFrameIndex));
     return ( mFrameBuf == p.mFrameBuf );
     }
bool rcSharedFrameBufPtr::operator== (const rcFrame * p) const inline
Definition at line 405 of file rc_framebuf.h.
References rcFrame::cacheCtrl(), rcFrame::frameIndex(), mCacheCtrl, mFrameBuf, and mFrameIndex.
{
         if ( mCacheCtrl )
         return (p && (mCacheCtrl == p->cacheCtrl()) &&
             (mFrameIndex == p->frameIndex()));
     return ( mFrameBuf == p );
     }
void rcSharedFrameBufPtr::prefetch () const
Definition at line 330 of file rc_framebuf.cpp.
References rcVideoCache::cachePrefetch(), mCacheCtrl, mFrameBuf, and mFrameIndex.
Referenced by rcEngineMoviePlayback::run().
 {
   if ((mFrameBuf == 0) && mCacheCtrl)
     rcVideoCache::cachePrefetch(mCacheCtrl, mFrameIndex);
 }
void rcSharedFrameBufPtr::printState () const inline
Definition at line 452 of file rc_framebuf.h.
References endl(), mCacheCtrl, mFrameBuf, and mFrameIndex.
{
       cerr << "fb c, i, b [" << mCacheCtrl << ", " << mFrameIndex << ", " << mFrameBuf << "]" << endl;
     }
int rcSharedFrameBufPtr::refCount () const inline
Definition at line 442 of file rc_framebuf.h.
References getMutex(), lock(), mCacheCtrl, mFrameBuf, and rcFrame::refCount().
Referenced by rcVideoCache::cacheInsert().
{
       int retVal = 0;
       if ( !mFrameBuf && mCacheCtrl ) lock();
       if ( mFrameBuf ) {
     rcLock frmLock(getMutex());
     retVal = mFrameBuf->refCount();
       }
       return retVal;
     }
void rcSharedFrameBufPtr::setCachedFrame (rcSharedFrameBufPtr & p, uint32 cacheID, uint32 frameIndex) inline private
Definition at line 461 of file rc_framebuf.h.
References rcFrame::addRef(), frameIndex(), getMutex(), mCacheCtrl, mFrameBuf, mFrameIndex, and rmAssert.
Referenced by rcVideoCache::cacheAlloc().
     {
         rmAssert(p.mFrameBuf);
     rmAssert(!mFrameBuf);
     rmAssert(cacheID);
     mFrameBuf = p.mFrameBuf;
     mCacheCtrl = cacheID;
     mFrameIndex = frameIndex;
     rcLock frmLock(getMutex());
     mFrameBuf->addRef();
     }
void rcSharedFrameBufPtr::setCachedFrameIndex (uint32 cacheID, uint32 frameIndex) inline private
Definition at line 479 of file rc_framebuf.h.
References frameIndex(), mCacheCtrl, mFrameBuf, mFrameIndex, and rmAssert.
Referenced by rcVideoCache::getFrame().
     {
     rmAssert(!mFrameBuf);
     rmAssert(cacheID);
     mCacheCtrl = cacheID;
     mFrameIndex = frameIndex;
     }
void rcSharedFrameBufPtr::unlock () const inline
Definition at line 382 of file rc_framebuf.h.
References internalUnlock().
Referenced by rcSimilarator::internalUpdate().
{
       const_cast<rcSharedFrameBufPtr*>(this)->internalUnlock(false);
     }
Friends And Related Function Documentation
friend class rcVideoCache friend
Definition at line 257 of file rc_framebuf.h.
Member Data Documentation
rcMutex * rcSharedFrameBufPtr::frameMutexP = 0 static private
Definition at line 495 of file rc_framebuf.h.
Referenced by getMutex().
uint32 rcSharedFrameBufPtr::mCacheCtrl private
Definition at line 490 of file rc_framebuf.h.
Referenced by rcVideoCache::cacheInsert(), rcVideoCache::internalGetFrame(), internalLock(), internalUnlock(), operator rcFrame *(), operator!(), operator*(), operator->(), operator=(), operator==(), prefetch(), printState(), rcSharedFrameBufPtr(), refCount(), setCachedFrame(), and setCachedFrameIndex().
rcFrame* rcSharedFrameBufPtr::mFrameBuf private
Definition at line 493 of file rc_framebuf.h.
Referenced by rcVideoCache::cacheAlloc(), rcVideoCache::getFrame(), rcVideoCache::internalGetFrame(), internalLock(), internalUnlock(), operator rcFrame *(), operator!(), operator*(), operator->(), operator=(), operator==(), prefetch(), printState(), rcSharedFrameBufPtr(), refCount(), setCachedFrame(), and setCachedFrameIndex().
uint32 rcSharedFrameBufPtr::mFrameIndex private
Definition at line 491 of file rc_framebuf.h.
Referenced by frameIndex(), rcVideoCache::internalGetFrame(), internalLock(), internalUnlock(), operator=(), operator==(), prefetch(), printState(), rcSharedFrameBufPtr(), setCachedFrame(), and setCachedFrameIndex().
The documentation for this class was generated from the following files:
include/visual/rc_framebuf.h
src/visual/code/rc_framebuf.cpp