Visible: rcMovieSaveCtrl Class Reference
rcMovieSaveCtrl Class Reference
#include <include/visiCore/rc_saveregs.h>
Public Member Functions
rcMovieSaveCtrl ()
void frameCaptureTime (uint32 frameCaptureTime)
void frameCaptureDelayTime (uint32 frameCaptureDelayTime)
void outputFileName (const std::string &outputFileName)
void movieFileName (const std::string &movieFileName)
Public Member Functions inherited from rcMovieSaveCtrlReader
rcMovieSaveCtrlReader ()
virtual ~rcMovieSaveCtrlReader ()
uint32 getFrameCaptureTime () const
uint32 getFrameCaptureDelayTime () const
std::string getOutputFileName () const
std::string getMovieFileName () const
Additional Inherited Members
Protected Attributes inherited from rcMovieSaveCtrlReader
rcAtomicValue< uint32 > _frameCaptureTime
rcAtomicValue< uint32 > _frameCaptureDelayTime
rcMutex _mutex
std::string _outputFileName
std::string _movieFileName
Detailed Description
Definition at line 110 of file rc_saveregs.h.
Constructor & Destructor Documentation
rcMovieSaveCtrl::rcMovieSaveCtrl () inline
Definition at line 113 of file rc_saveregs.h.
                     : rcMovieSaveCtrlReader()
   { }
Member Function Documentation
void rcMovieSaveCtrl::frameCaptureDelayTime (uint32 frameCaptureDelayTime) inline
Definition at line 121 of file rc_saveregs.h.
References rcMovieSaveCtrlReader::_frameCaptureDelayTime, and rcAtomicValue< T >::setValue().
Referenced by rcEngineImpl::setSettingValue().
   {
     _frameCaptureDelayTime.setValue(frameCaptureDelayTime);
   }
void rcMovieSaveCtrl::frameCaptureTime (uint32 frameCaptureTime) inline
Definition at line 116 of file rc_saveregs.h.
References rcMovieSaveCtrlReader::_frameCaptureTime, and rcAtomicValue< T >::setValue().
Referenced by rcEngineImpl::setSettingValue().
   {
     _frameCaptureTime.setValue(frameCaptureTime);
   }
void rcMovieSaveCtrl::movieFileName (const std::string & movieFileName) inline
Definition at line 132 of file rc_saveregs.h.
References rcMovieSaveCtrlReader::_movieFileName, and rcMovieSaveCtrlReader::_mutex.
Referenced by rcEngineImpl::internalReset(), and rcEngineImpl::setSettingValue().
   {
     rcLock lock(_mutex);
     _movieFileName = movieFileName;
   }
void rcMovieSaveCtrl::outputFileName (const std::string & outputFileName) inline
Definition at line 126 of file rc_saveregs.h.
References rcMovieSaveCtrlReader::_mutex, and rcMovieSaveCtrlReader::_outputFileName.
Referenced by rcEngineImpl::internalReset(), rcEngineImpl::setSettingValue(), and rcEngineImpl::unlockedReset().
   {
     rcLock lock(_mutex);
     _outputFileName = outputFileName;
   }
The documentation for this class was generated from the following file:
include/visiCore/rc_saveregs.h