Visible: rcRowFuncTwoSource< T > Class Template Reference
rcRowFuncTwoSource< T > Class Template Reference abstract
#include <include/analysis/rc_rowfunc.h>
Public Member Functions
rcRowFuncTwoSource ()
virtual ~rcRowFuncTwoSource ()
virtual void prolog ()=0
virtual void rowFunc ()=0
virtual void areaFunc ()=0
Protected Member Functions
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
template<>
bool checkAssigned (const rcWindow &srcA, const rcWindow &srcB)
Static Protected Member Functions
static bool checkAssigned (const rcWindow &, const rcWindow &)
Protected Attributes
const T * mFirst
const T * mSecond
uint32 mWidth
uint32 mHeight
Detailed Description
template<class T>
class rcRowFuncTwoSource< T >
Definition at line 57 of file rc_rowfunc.h.
Constructor & Destructor Documentation
template<class T> rcRowFuncTwoSource< T >::rcRowFuncTwoSource () inline
Definition at line 61 of file rc_rowfunc.h.
 {}
template<class T> virtual rcRowFuncTwoSource< T >::~rcRowFuncTwoSource () inline virtual
Definition at line 62 of file rc_rowfunc.h.
 {}
Member Function Documentation
template<class T> virtual void rcRowFuncTwoSource< T >::areaFunc () pure virtual
Implemented in rcBasicCorrRowFunc< T >.
template<> bool rcRowFuncTwoSource< uint8 >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 57 of file rc_rowfuncs.cpp.
References rcWindow::depth(), and rcPixel8.
 {
   return (srcA.depth() == rcPixel8 && srcB.depth() == rcPixel8);
 }
template<> bool rcRowFuncTwoSource< uint16 >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 63 of file rc_rowfuncs.cpp.
References rcWindow::depth(), rcPixel16, and rcPixel8.
 {
   return (srcA.depth() == rcPixel8 && srcB.depth() == rcPixel16);
 }
template<class T> static bool rcRowFuncTwoSource< T >::checkAssigned (const rcWindow & , const rcWindow &) static protected
Referenced by rcBasicCorrRowFunc< T >::rcBasicCorrRowFunc().
template<> bool rcRowFuncTwoSource< uint32 >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 69 of file rc_rowfuncs.cpp.
References rcWindow::depth(), rcPixel32, and rcPixel8.
 {
   return (srcA.depth() == rcPixel8 && srcB.depth() == rcPixel32);
 }
template<> bool rcRowFuncTwoSource< double >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 75 of file rc_rowfuncs.cpp.
References rcWindow::depth(), and rcPixelDouble.
 {
   return (srcA.depth() == rcPixelDouble && srcB.depth() == rcPixelDouble);
 }
template<> bool rcRowFuncTwoSource< float >::checkAssigned (const rcWindow & srcA, const rcWindow & srcB) protected
Definition at line 81 of file rc_rowfuncs.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcFrame::isD32Float(), and rcPixelFloat.
 {
   return (srcA.depth() == rcPixelFloat && srcB.depth() == rcPixelFloat &&
                     srcA.frameBuf()->isD32Float() &&      srcB.frameBuf()->isD32Float() );
 }
template<class T> virtual void rcRowFuncTwoSource< T >::prolog () pure virtual
Implemented in rcBasicCorrRowFunc< T >.
template<class T> virtual void rcRowFuncTwoSource< T >::rowFunc () pure virtual
Implemented in rcBasicCorrRowFunc< T >, and rcBasicCorrRowFunc< T >.
Member Data Documentation
template<class T> const T* rcRowFuncTwoSource< T >::mFirst protected
Definition at line 70 of file rc_rowfunc.h.
template<class T> uint32 rcRowFuncTwoSource< T >::mHeight protected
Definition at line 73 of file rc_rowfunc.h.
template<class T> const T* rcRowFuncTwoSource< T >::mSecond protected
Definition at line 71 of file rc_rowfunc.h.
template<class T> uint32 rcRowFuncTwoSource< T >::mWidth protected
Definition at line 72 of file rc_rowfunc.h.
The documentation for this class was generated from the following file:
include/analysis/rc_rowfunc.h