Visible: rcMutualInfoGrouping Class Reference
rcMutualInfoGrouping Class Reference
#include <include/analysis/rc_level.h>
Public Member Functions
rcMutualInfoGrouping (const rcWindow &image)
Public Member Functions inherited from rcSegmentationLevel
virtual ~rcSegmentationLevel ()
rcWindow binaryImage (const rcWindow &src, uint8 toGrayValue)
rcWindow binaryImage (const rcWindow &src, uint8 toGrayValue, uint8 setVal)
virtual rcLevelSets & results ()
Private Attributes
bool mIsValid
Detailed Description
Definition at line 162 of file rc_level.h.
Constructor & Destructor Documentation
rcMutualInfoGrouping::rcMutualInfoGrouping (const rcWindow & image)
Definition at line 198 of file rc_seglevel.cpp.
References rcSegmentationLevel::binaryImage(), rcSimilarator::eExhaustive, endl(), rcHistoStats::histogram(), rcPixel8, rcSegmentationLevel::results(), rfMedian(), rcLevelSets::threshold(), and rcLevelSets::update().
                                                                  : mIsValid (false)
 {
  rcHistoStats h (image);
  vector<rcWindow> slices;
  deque<double> entf;
  // Default sorting criteria is less<double>.
  multimap<double, uint32, less<double> > aciToIndex;
  for (uint32 i =1; i < h.histogram().size() - 1; i++)
    {
      if (!h.histogram()[i]) continue;
      slices.push_back (binaryImage (image, i));
    }
  // @todo correlation of binary templates can be substantially sped up (not a binary packing scheme)
     rcSimilaratorRef sim = boost::shared_ptr<rcSimilarator> (new rcSimilarator (rcSimilarator::eExhaustive,
                                                                                                                                                             rcPixel8, slices.size(), 0) );
  sim->fill (slices);
  sim->entropies(entf);
  deque<double>::iterator mi = entf.begin();
  for (uint32 i = 1; i < h.histogram().size() - 1; i++)
    {
      if (!h.histogram()[i]) continue;
      double aci = *mi++;
      aciToIndex.insert(pair<double, uint32>(aci,i));
    }
  // Compute the median value
  // Median does not actually compute index in the original list.
  double med = rfMedian (entf);
  multimap<double, uint32>::iterator si = aciToIndex.lower_bound (med);
  results().update (si->second, 1.0, 0);
 #if 0
  cerr << "Median: " << med << "Level: " << results().threshold () << endl;
  cerr.setf (ios::fixed);
  cerr << setprecision (7);
  cerr << "{";
  si = aciToIndex.begin();
  for (; si != aciToIndex.end(); si++)
    {
      cerr << "{" << si->second <<  "," << si->first << "},";
    }
  cerr << "}";
 #endif
 }
Member Data Documentation
bool rcMutualInfoGrouping::mIsValid private
Definition at line 169 of file rc_level.h.
The documentation for this class was generated from the following files:
include/analysis/rc_level.h
src/analysis/code/rc_seglevel.cpp