Visible: ini_manager Class Reference
ini_manager Class Reference
#include <include/stlplus/ini_manager.hpp>
Public Member Functions
ini_manager (void)
ini_manager (const std::vector< std::string > &filenames)
~ini_manager (void)
bool add_file (const std::string &filename)
bool add_files (const std::vector< std::string > &filenames)
bool save (void)
unsigned size (void) const
std::string filename (unsigned depth=0) const
bool writable (unsigned depth=0) const
bool empty (unsigned depth=0) const
bool erase (unsigned depth=0)
bool remove (unsigned depth=0)
std::vector< std::string > section_names (void) const
std::vector< std::string > section_names (unsigned depth) const
bool section_exists (const std::string &title) const
bool section_exists (const std::string &title, unsigned depth) const
bool add_section (const std::string &section, unsigned depth=0)
bool empty_section (const std::string &section, unsigned depth=0)
bool erase_section (const std::string &section, unsigned depth=0)
bool clear_section (const std::string &section, unsigned depth=0)
bool variable_exists (const std::string &section, const std::string variable) const
bool variable_exists (const std::string &section, const std::string variable, unsigned depth) const
std::vector< std::string > variable_names (const std::string &section) const
std::vector< std::string > variable_names (const std::string &section, unsigned depth) const
unsigned variable_depth (const std::string &section, const std::string variable) const
std::string variable_filename (const std::string &section, const std::string variable) const
unsigned variable_linenumber (const std::string &section, const std::string variable) const
std::string variable_value (const std::string &section, const std::string variable) const
std::string variable_value (const std::string &section, const std::string variable, unsigned depth) const
std::vector< std::string > variable_values (const std::string &section, const std::string variable) const
std::vector< std::string > variable_values (const std::string &section, const std::string variable, unsigned depth) const
bool add_variable (const std::string &section, const std::string &variable, const std::string &value, unsigned depth=0)
bool add_variable (const std::string &section, const std::string &variable, const std::vector< std::string > &values, unsigned depth=0)
bool erase_variable (const std::string &section, const std::string &variable, unsigned depth=0)
bool add_comment (const std::string &section, const std::string &comment, unsigned depth=0)
bool add_blank (const std::string &section, unsigned depth=0)
Private Member Functions
ini_manager (const ini_manager &)
ini_manager & operator= (const ini_manager &)
Private Attributes
std::vector< smart_ptr
< ini_file > > m_files
Friends
class ini_file
otext & print (otext &, const ini_manager &, unsigned indent=0)
otext & operator<< (otext &, const ini_manager &)
Detailed Description
Definition at line 42 of file ini_manager.hpp.
Constructor & Destructor Documentation
ini_manager::ini_manager (void)
Definition at line 563 of file ini_manager.cpp.
 {
 }
ini_manager::ini_manager (const std::vector< std::string > & filenames) explicit
Definition at line 567 of file ini_manager.cpp.
References add_files().
 {
   add_files(filenames);
 }
ini_manager::~ini_manager (void)
Definition at line 572 of file ini_manager.cpp.
 {
 }
ini_manager::ini_manager (const ini_manager &) private
Member Function Documentation
bool ini_manager::add_blank (const std::string & section, unsigned depth = 0)
Definition at line 922 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings().
 {
   if (m_files.empty()) return false;
   return m_files[depth]->add_blank(section);
 }
bool ini_manager::add_comment (const std::string & section, const std::string & comment, unsigned depth = 0)
Definition at line 916 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings().
 {
   if (m_files.empty()) return false;
   return m_files[depth]->add_comment(section, comment);
 }
bool ini_manager::add_file (const std::string & filename)
Definition at line 579 of file ini_manager.cpp.
References filename(), filespec_to_path(), ini_file, and m_files.
Referenced by add_files().
 {
   // if this file has been loaded, don't load it again
   // this is not an error
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (filespec_to_path(filename) == filespec_to_path(m_files[i]->filename()))
       return true;
   }
   // add a new file to the back of the list and then load it
   // I do it in two steps rather than passing the filename to the constructor in order to return the load status
   m_files.push_back(ini_file());
   return m_files.back()->read_file(filename);
 }
bool ini_manager::add_files (const std::vector< std::string > & filenames)
Definition at line 594 of file ini_manager.cpp.
References add_file().
Referenced by ini_manager().
 {
   bool result = true;
   for (unsigned i = 0; i < filenames.size(); i++)
     result &= add_file(filenames[i]);
   return result;
 }
bool ini_manager::add_section (const std::string & section, unsigned depth = 0)
Definition at line 683 of file ini_manager.cpp.
References m_files.
 {
   if (m_files.empty()) return false;
   return m_files[depth]->add_section(section);
 }
bool ini_manager::add_variable (const std::string & section, const std::string & variable, const std::string & value, unsigned depth = 0)
Definition at line 876 of file ini_manager.cpp.
References m_files.
Referenced by add_variable(), and library_manager::save_mappings().
 {
   if (m_files.empty()) return false;
   return m_files[depth]->add_variable(section, variable, value);
 }
bool ini_manager::add_variable (const std::string & section, const std::string & variable, const std::vector< std::string > & values, unsigned depth = 0)
Definition at line 882 of file ini_manager.cpp.
References add_variable(), and element().
 {
   // convert the values vector into a comma-separated string with each value escaped so that special characters do not confuse the reader
   // the characters escaped are: '\', ',', '"'
   std::string value;
   for (unsigned v = 0; v < values.size(); v++)
   {
     const std::string& element = values[v];
     // add the comma between values === add a comma before all but the first value
     if (v > 0) value += ',';
     for (unsigned i = 0; i < element.size(); i++)
     {
       // add a character at a time, escaping special characters
       if (element[i] == '"' || element[i] == ',' || element[i] == '\\')
       {
         // escape the character
         value += '\\';
       }
       value += element[i];
     }
   }
   return add_variable(section, variable, value, depth);
 }
bool ini_manager::clear_section (const std::string & section, unsigned depth = 0)
Definition at line 701 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings().
 {
   if (m_files.empty()) return false;
   return m_files[depth]->clear_section(section);
 }
bool ini_manager::empty (unsigned depth = 0) const
Definition at line 625 of file ini_manager.cpp.
References m_files.
 {
   return m_files[depth]->empty();
 }
bool ini_manager::empty_section (const std::string & section, unsigned depth = 0)
Definition at line 689 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings().
 {
   if (m_files.empty()) return false;
   return m_files[depth]->empty_section(section);
 }
bool ini_manager::erase (unsigned depth = 0)
Definition at line 630 of file ini_manager.cpp.
References file_delete(), and filename().
 {
   std::string file = filename(depth);
   remove(depth);
   return file_delete(file);
 }
bool ini_manager::erase_section (const std::string & section, unsigned depth = 0)
Definition at line 695 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings().
 {
   if (m_files.empty()) return false;
   return m_files[depth]->erase_section(section);
 }
bool ini_manager::erase_variable (const std::string & section, const std::string & variable, unsigned depth = 0)
Definition at line 906 of file ini_manager.cpp.
References m_files.
 {
   if (m_files.empty()) return false;
   return m_files[depth]->erase_variable(section, variable);
 }
std::string ini_manager::filename (unsigned depth = 0) const
Definition at line 615 of file ini_manager.cpp.
References m_files.
Referenced by add_file(), erase(), and variable_filename().
 {
   return m_files[depth]->filename();
 }
ini_manager& ini_manager::operator= (const ini_manager &) private
bool ini_manager::remove (unsigned depth = 0)
Definition at line 637 of file ini_manager.cpp.
References m_files, and writable().
 {
   if (m_files[depth]->writable())
     m_files[depth]->save_file();
   m_files.erase(m_files.begin() + depth);
   return true;
 }
bool ini_manager::save (void)
Definition at line 602 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings().
 {
   bool result = true;
   for (unsigned i = 0; i < m_files.size(); i++)
     result &= m_files[i]->save_file();
   return result;
 }
bool ini_manager::section_exists (const std::string & title) const
Definition at line 668 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::set_ini_manager().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (section_exists(title, i))
       return true;
   }
   return false;
 }
bool ini_manager::section_exists (const std::string & title, unsigned depth) const
Definition at line 678 of file ini_manager.cpp.
References m_files.
 {
   return m_files[depth]->section_exists(title);
 }
std::vector< std::string > ini_manager::section_names (void) const
Definition at line 648 of file ini_manager.cpp.
References m_files.
 {
   std::vector<std::string> result;
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     std::vector<std::string> file_result = section_names(i);
     for (unsigned j = 0; j < file_result.size(); j++)
     {
       if (std::find(result.begin(), result.end(), file_result[j]) == result.end())
         result.push_back(file_result[j]);
     }
   }
   return result;
 }
std::vector< std::string > ini_manager::section_names (unsigned depth) const
Definition at line 663 of file ini_manager.cpp.
References m_files.
 {
   return m_files[depth]->section_names();
 }
unsigned ini_manager::size (void) const
Definition at line 610 of file ini_manager.cpp.
References m_files.
Referenced by print().
 {
   return m_files.size();
 }
unsigned ini_manager::variable_depth (const std::string & section, const std::string variable) const
Definition at line 745 of file ini_manager.cpp.
References m_files, and variable_exists().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (variable_exists(section, variable, i))
       return i;
   }
   return (unsigned)-1;
 }
bool ini_manager::variable_exists (const std::string & section, const std::string variable) const
Definition at line 710 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings(), variable_depth(), variable_filename(), variable_linenumber(), variable_value(), and variable_values().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (variable_exists(section, variable, i))
       return true;
   }
   return false;
 }
bool ini_manager::variable_exists (const std::string & section, const std::string variable, unsigned depth) const
Definition at line 720 of file ini_manager.cpp.
References m_files.
 {
   return m_files[depth]->variable_exists(section, variable);
 }
std::string ini_manager::variable_filename (const std::string & section, const std::string variable) const
Definition at line 755 of file ini_manager.cpp.
References filename(), m_files, and variable_exists().
Referenced by library_manager::save_mappings(), and library_manager::set_ini_manager().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (variable_exists(section, variable, i))
       return filename(i);
   }
   return std::string();
 }
unsigned ini_manager::variable_linenumber (const std::string & section, const std::string variable) const
Definition at line 765 of file ini_manager.cpp.
References m_files, variable_exists(), and ini_section::variable_line().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (variable_exists(section, variable, i))
       return m_files[i]->variable_line(section,variable);
   }
   return 0;
 }
std::vector< std::string > ini_manager::variable_names (const std::string & section) const
Definition at line 725 of file ini_manager.cpp.
References m_files.
Referenced by library_manager::save_mappings(), and library_manager::set_ini_manager().
 {
   std::vector<std::string> result;
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     std::vector<std::string> file_result = variable_names(section, i);
     for (unsigned j = 0; j < file_result.size(); j++)
     {
       if (std::find(result.begin(), result.end(), file_result[j]) == result.end())
         result.push_back(file_result[j]);
     }
   }
   return result;
 }
std::vector< std::string > ini_manager::variable_names (const std::string & section, unsigned depth) const
Definition at line 740 of file ini_manager.cpp.
References m_files.
 {
   return m_files[depth]->variable_names(section);
 }
std::string ini_manager::variable_value (const std::string & section, const std::string variable) const
Definition at line 775 of file ini_manager.cpp.
References m_files, and variable_exists().
Referenced by library_manager::save_mappings(), library_manager::set_ini_manager(), and variable_values().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (variable_exists(section, variable, i))
       return variable_value(section, variable, i);
   }
   return std::string();
 }
std::string ini_manager::variable_value (const std::string & section, const std::string variable, unsigned depth) const
Definition at line 785 of file ini_manager.cpp.
References m_files.
 {
   return m_files[depth]->variable_value(section, variable);
 }
std::vector< std::string > ini_manager::variable_values (const std::string & section, const std::string variable) const
Definition at line 790 of file ini_manager.cpp.
References m_files, and variable_exists().
 {
   for (unsigned i = 0; i < m_files.size(); i++)
   {
     if (variable_exists(section, variable, i))
       return variable_values(section, variable, i);
   }
   return std::vector<std::string>();
 }
std::vector< std::string > ini_manager::variable_values (const std::string & section, const std::string variable, unsigned depth) const
Definition at line 800 of file ini_manager.cpp.
References variable_value().
 {
   // get the unprocessed value and then do the processing into processed separate values
   std::string value = variable_value(section, variable, depth);
   std::vector<std::string> result;
   if (!value.empty())
   {
     result.push_back(std::string());
     unsigned i = 0;
     // loop which is repeated for each element in the comma-separated list
     while(i < value.size())
     {
       // skip leading whitespace
       while (i < value.size() && isspace(value[i])) i++;
       // get the value - this means all text up to the next comma or end of line
       // also allow escaped characters
       while (i < value.size())
       {
         if (value[i] == ',') break;
         if (value[i] == '\\')
         {
           // found an escaped character - de-escape it by only getting the next character
           // beware of an escape character at the end of the line which just gets ignored
           i++;
           if (i < value.size()) result.back() += value[i++];
         }
         else if (value[i] == '"')
         {
           // get a quoted substring
           // first skip the opening quote
           i++;
           // keep getting characters until a close-quote, but allow the quote character to be escaped by itself
           while (i < value.size())
           {
             if (value[i] == '"')
             {
               // found a quote skip it
               i++;
               // now establish whether its an escaped quote
               // if it is, keep it, but de-escape it by only getting the next character
               // it it isn't, break out and continue processing the value as a non-quoted string
               if (i < value.size() && value[i] != '"') break;
               if (i < value.size()) result.back() += value[i++];
             }
             else
             {
               // non-quote and non-escape so just get the character
               result.back() += value[i++];
             }
           }
         }
         else
         {
           // non-escape so just get the character
           result.back() += value[i++];
         }
       }
       // trim trailing whitespace off the value
       while (!result.back().empty() && isspace(result.back()[result.back().size()-1])) result.back().erase(result.back().size()-1,1);
       // now chk for whether there is a comma or end of line
       if (i <= value.size() && value[i] == ',')
       {
         // skip the comma and add a new string to the result ready for the next iteration
         i++;
         result.push_back(std::string());
       }
       else
       {
         // end of line found so break out
         break;
       }
     }
   }
   return result;
 }
bool ini_manager::writable (unsigned depth = 0) const
Definition at line 620 of file ini_manager.cpp.
References m_files.
Referenced by remove().
 {
   return m_files[depth]->writable();
 }
Friends And Related Function Documentation
friend class ini_file friend
Definition at line 186 of file ini_manager.hpp.
Referenced by add_file().
otext& operator<< (otext & , const ini_manager &) friend
Definition at line 944 of file ini_manager.cpp.
 {
   return print(str, manager);
 }
otext& print (otext & , const ini_manager & , unsigned indent = 0) friend
Definition at line 931 of file ini_manager.cpp.
 {
   print_indent(str, indent);
   str << "----------------------------------------" << endl;
   for (unsigned depth = 0; depth < manager.size(); depth++)
   {
     print(str, *manager.m_files[depth], indent);
     print_indent(str, indent);
     str << "----------------------------------------" << endl;
   }
   return str;
 }
Member Data Documentation
std::vector<smart_ptr<ini_file> > ini_manager::m_files private
Definition at line 187 of file ini_manager.hpp.
Referenced by add_blank(), add_comment(), add_file(), add_section(), add_variable(), clear_section(), empty(), empty_section(), erase_section(), erase_variable(), filename(), print(), remove(), save(), section_exists(), section_names(), size(), variable_depth(), variable_exists(), variable_filename(), variable_linenumber(), variable_names(), variable_value(), variable_values(), and writable().
The documentation for this class was generated from the following files:
include/stlplus/ini_manager.hpp
include/stlplus/ini_manager.cpp