Visible: dump_context_body Class Reference
dump_context_body Class Reference
Public Types
typedef std::map< const void
*, unsigned > magic_map
typedef std::map< std::string,
dump_context::callback_data > callback_map
typedef std::map< std::string,
unsigned short > interface_map
Public Member Functions
dump_context_body (const otext &device, unsigned char version) throw (persistent_dump_failed)
void put (unsigned char data) throw (persistent_dump_failed)
const otext & device (void) const
unsigned char version (void) const
bool little_endian (void) const
std::pair< bool, unsigned > pointer_map (const void *const pointer)
unsigned short register_type (const std::type_info &info, dump_context::dump_callback callback)
bool is_callback (const std::type_info &info) const
dump_context::callback_data lookup_type (const std::type_info &info) const throw (persistent_illegal_type)
unsigned short register_interface (const std::type_info &info)
bool is_interface (const std::type_info &info) const
unsigned short lookup_interface (const std::type_info &info) const throw (persistent_illegal_type)
Public Attributes
unsigned short m_max_key
unsigned char m_version
bool m_little_endian
otext m_device
magic_map m_pointers
callback_map m_callbacks
interface_map m_interfaces
Detailed Description
Definition at line 65 of file persistent.cpp.
Member Typedef Documentation
typedef std::map<std::string,dump_context::callback_data> dump_context_body::callback_map
Definition at line 69 of file persistent.cpp.
typedef std::map<std::string,unsigned short> dump_context_body::interface_map
Definition at line 70 of file persistent.cpp.
typedef std::map<const void*,unsigned> dump_context_body::magic_map
Definition at line 68 of file persistent.cpp.
Constructor & Destructor Documentation
dump_context_body::dump_context_body (const otext & device, unsigned char version) throw (persistent_dump_failed) inline
Definition at line 80 of file persistent.cpp.
References m_device, m_pointers, m_version, put(), otext::set_binary_mode(), to_string(), and version().
                                                                                               :
     m_max_key(0), m_version(version), m_little_endian(::little_endian()), m_device(device)
     {
       m_device.set_binary_mode();
       put(version);
       // map a null pointer onto magic number zero
       m_pointers[0] = 0;
       if (m_version != 1 && m_version != 2)
         throw persistent_dump_failed(std::string("wrong version: ") + to_string(m_version));
     }
Member Function Documentation
const otext& dump_context_body::device (void) const inline
Definition at line 102 of file persistent.cpp.
References m_device.
Referenced by dump_context::device().
     {
       return m_device;
     }
bool dump_context_body::is_callback (const std::type_info & info) const inline
Definition at line 139 of file persistent.cpp.
References m_callbacks.
Referenced by dump_context::is_callback().
     {
       return m_callbacks.find(info.name()) != m_callbacks.end();
     }
bool dump_context_body::is_interface (const std::type_info & info) const inline
Definition at line 161 of file persistent.cpp.
References m_interfaces.
Referenced by dump_context::is_interface().
     {
       return m_interfaces.find(info.name()) != m_interfaces.end();
     }
bool dump_context_body::little_endian (void) const inline
Definition at line 112 of file persistent.cpp.
References m_little_endian.
Referenced by dump_context::little_endian().
     {
       return m_little_endian;
     }
unsigned short dump_context_body::lookup_interface (const std::type_info & info) const throw (persistent_illegal_type) inline
Definition at line 166 of file persistent.cpp.
References m_interfaces.
     {
       std::string key = info.name();
       interface_map::const_iterator found = m_interfaces.find(key);
       if (found == m_interfaces.end())
         throw persistent_illegal_type(key);
       return found->second;
     }
dump_context::callback_data dump_context_body::lookup_type (const std::type_info & info) const throw (persistent_illegal_type) inline
Definition at line 144 of file persistent.cpp.
References m_callbacks.
     {
       std::string key = info.name();
       callback_map::const_iterator found = m_callbacks.find(key);
       if (found == m_callbacks.end())
         throw persistent_illegal_type(key);
       return found->second;
     }
std::pair<bool,unsigned> dump_context_body::pointer_map (const void *const pointer) inline
Definition at line 117 of file persistent.cpp.
References m_pointers.
Referenced by dump_context::pointer_map().
     {
       magic_map::iterator found = m_pointers.find(pointer);
       if (found == m_pointers.end())
       {
         // add a new mapping
         unsigned magic = m_pointers.size();
         m_pointers[pointer] = magic;
         return std::pair<bool,unsigned>(false,magic);
       }
       // return the old mapping
       return std::pair<bool,unsigned>(true,found->second);
     }
void dump_context_body::put (unsigned char data) throw (persistent_dump_failed) inline
Definition at line 91 of file persistent.cpp.
References otext::error(), otext::error_string(), m_device, and otext::put().
Referenced by dump_context_body().
     {
       if (!m_device.put(data))
       {
         if (m_device.error())
           throw persistent_dump_failed(std::string("output device error: ") + m_device.error_string());
         else
           throw persistent_dump_failed(std::string("output device error: unknown"));
       }
     }
unsigned short dump_context_body::register_interface (const std::type_info & info) inline
Definition at line 153 of file persistent.cpp.
References m_interfaces, and m_max_key.
Referenced by dump_context::register_interface().
     {
       std::string key = info.name();
       unsigned short data = ++m_max_key;
       m_interfaces[key] = data;
       return data;
     }
unsigned short dump_context_body::register_type (const std::type_info & info, dump_context::dump_callback callback) inline
Definition at line 131 of file persistent.cpp.
References m_callbacks, and m_max_key.
Referenced by dump_context::register_type().
     {
       std::string key = info.name();
       unsigned short data = ++m_max_key;
       m_callbacks[key] = std::make_pair(data,callback);
       return data;
     }
unsigned char dump_context_body::version (void) const inline
Definition at line 107 of file persistent.cpp.
References m_version.
Referenced by dump_context_body(), and dump_context::version().
     {
       return m_version;
     }
Member Data Documentation
callback_map dump_context_body::m_callbacks
Definition at line 77 of file persistent.cpp.
Referenced by is_callback(), lookup_type(), and register_type().
otext dump_context_body::m_device
Definition at line 75 of file persistent.cpp.
Referenced by device(), dump_context_body(), and put().
interface_map dump_context_body::m_interfaces
Definition at line 78 of file persistent.cpp.
Referenced by is_interface(), lookup_interface(), and register_interface().
bool dump_context_body::m_little_endian
Definition at line 74 of file persistent.cpp.
Referenced by little_endian().
unsigned short dump_context_body::m_max_key
Definition at line 72 of file persistent.cpp.
Referenced by register_interface(), and register_type().
magic_map dump_context_body::m_pointers
Definition at line 76 of file persistent.cpp.
Referenced by dump_context_body(), and pointer_map().
unsigned char dump_context_body::m_version
Definition at line 73 of file persistent.cpp.
Referenced by dump_context_body(), and version().
The documentation for this class was generated from the following file:
include/stlplus/persistent.cpp