Visible: ombuff Class Reference
ombuff Class Reference
#include <include/stlplus/multiio.hpp>
Public Member Functions
ombuff (void)
unsigned add (const otext &)
void remove (unsigned)
virtual unsigned put (unsigned char)
unsigned count (void) const
otext & device (unsigned)
const otext & device (unsigned) const
Public Member Functions inherited from obuff
obuff (bool line_buffer=false, otext::newline_t newline=otext::native_mode)
void increment (bool newline=false)
unsigned long bytes (void) const
unsigned line (void) const
unsigned column (void) const
void set_line_buffer (bool mode)
bool line_buffer (void) const
void set_newline_mode (otext::newline_t newline)
otext::newline_t newline_mode (void) const
unsigned integer_width (void) const
void set_integer_width (unsigned)
unsigned integer_radix (void) const
void set_integer_radix (unsigned)
radix_display_t integer_display (void) const
void set_integer_display (radix_display_t)
unsigned real_width (void) const
void set_real_width (unsigned)
unsigned real_precision (void) const
void set_real_precision (unsigned)
real_display_t real_display (void) const
void set_real_display (real_display_t)
void set_error (int error)
void clear_error (void)
int error_number (void) const
virtual std::string error_string (void) const
virtual void flush (void)
virtual ~obuff (void)
Private Member Functions
ombuff (const ombuff &)
ombuff & operator= (const ombuff &)
Private Attributes
std::vector< otext > m_devices
Friends
class omtext
Additional Inherited Members
Protected Attributes inherited from obuff
bool m_line_buffer
otext::newline_t m_newline
unsigned long m_bytes
unsigned m_line
unsigned m_column
unsigned m_integer_width
unsigned m_integer_radix
radix_display_t m_integer_display
unsigned m_real_width
unsigned m_real_precision
real_display_t m_real_display
int m_error_number
int m_aliases
Detailed Description
Definition at line 56 of file multiio.hpp.
Constructor & Destructor Documentation
ombuff::ombuff (void)
Definition at line 150 of file multiio.cpp.
                    :
   // each sub-device should define its own line-buffer and newline modes
   obuff(false,otext::binary_mode)
 {
 }
ombuff::ombuff (const ombuff &) private
Member Function Documentation
unsigned ombuff::add (const otext & str)
Definition at line 156 of file multiio.cpp.
References m_devices.
Referenced by omtext::add().
 {
   m_devices.push_back(str);
   return m_devices.size()-1;
 }
unsigned ombuff::count (void) const
Definition at line 176 of file multiio.cpp.
References m_devices.
Referenced by omtext::device_count().
 {
   return m_devices.size();
 }
otext & ombuff::device (unsigned i)
Definition at line 181 of file multiio.cpp.
References m_devices.
Referenced by omtext::device_get().
 {
   return m_devices[i];
 }
const otext & ombuff::device (unsigned i) const
Definition at line 186 of file multiio.cpp.
References m_devices.
 {
   return m_devices[i];
 }
ombuff& ombuff::operator= (const ombuff &) private
unsigned ombuff::put (unsigned char ch) virtual
Implements obuff.
Definition at line 168 of file multiio.cpp.
References m_devices.
 {
   unsigned result = 0;
   for (unsigned i = 0; i < m_devices.size(); i++)
     result = std::max(result,m_devices[i].put(ch)?1u:0u);
   return result;
 }
void ombuff::remove (unsigned offset)
Definition at line 162 of file multiio.cpp.
References DEBUG_ASSERT, and m_devices.
Referenced by omtext::remove().
 {
   DEBUG_ASSERT(offset < m_devices.size());
   m_devices.erase(m_devices.begin()+offset);
 }
Friends And Related Function Documentation
friend class omtext friend
Definition at line 58 of file multiio.hpp.
Member Data Documentation
std::vector<otext> ombuff::m_devices private
Definition at line 71 of file multiio.hpp.
Referenced by add(), count(), device(), put(), and remove().
The documentation for this class was generated from the following files:
include/stlplus/multiio.hpp
include/stlplus/multiio.cpp