Visible: rcTextEdit Class Reference
rcTextEdit Class Reference
#include <include/visUI/rc_textedit.h>
Public Slots
void relayTextCommited (void)
Signals
void textCommited (const QString &text)
Public Member Functions
rcTextEdit (QWidget *parent, int lines, const char *name)
rcTextEdit (const QString &text, int lines, const QString &context=QString::null, QWidget *parent=0, const char *name=0)
virtual QSize sizeHint () const
Protected Member Functions
virtual void focusOutEvent (QFocusEvent *event)
Private Attributes
int mLines
Detailed Description
Definition at line 8 of file rc_textedit.h.
Constructor & Destructor Documentation
rcTextEdit::rcTextEdit (QWidget * parent, int lines, const char * name) inline
Definition at line 13 of file rc_textedit.h.
References relayTextCommited().
         : Q3TextEdit( parent , name ), mLines(lines)
     {
         connect( this , SIGNAL( returnPressed( void ) ) ,
                  this , SLOT( relayTextCommited( void ) ) );
     }
rcTextEdit::rcTextEdit (const QString & text, int lines, const QString & context = QString::null, QWidget * parent = 0, const char * name = 0) inline
Definition at line 20 of file rc_textedit.h.
References relayTextCommited().
         : Q3TextEdit( text , context , parent , name ), mLines(lines)
     {
         connect( this , SIGNAL( returnPressed( void ) ) ,
                  this , SLOT( relayTextCommited( void ) ) );
     }
Member Function Documentation
virtual void rcTextEdit::focusOutEvent (QFocusEvent * event) inline protected virtual
Definition at line 38 of file rc_textedit.h.
References textCommited().
     {
         Q3TextEdit::focusOutEvent( event );
         emit textCommited( text() );
     }
void rcTextEdit::relayTextCommited (void) inline slot
Definition at line 45 of file rc_textedit.h.
References textCommited().
Referenced by rcTextEdit().
     {
         emit textCommited( text() );
     }
virtual QSize rcTextEdit::sizeHint () const inline virtual
Definition at line 28 of file rc_textedit.h.
References mLines.
     {
         constPolish();
         int f = 2 * frameWidth();
         int h = fontMetrics().height();
         QSize sz( f, f );
         return sz.expandedTo( QSize(12 * h, mLines * h) );
     }
void rcTextEdit::textCommited (const QString & text) signal
Definition at line 78 of file moc_rc_textedit.cpp.
Referenced by focusOutEvent(), and relayTextCommited().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
     QMetaObject::activate(this, &staticMetaObject, 0, _a);
 }
Member Data Documentation
int rcTextEdit::mLines private
Definition at line 54 of file rc_textedit.h.
Referenced by sizeHint().
The documentation for this class was generated from the following files:
include/visUI/rc_textedit.h
src/visible/moc/moc_rc_textedit.cpp