Visible: rcCheckboxSettingWidget Class Reference
rcCheckboxSettingWidget Class Reference
#include <include/visUI/rc_checkboxsettingwidget.h>
Public Slots
void valueChanged (bool newValue)
void settingChanged (void)
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcCheckboxSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcCheckboxSettingWidget ()
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Attributes
QCheckBox * mWidget
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 8 of file rc_checkboxsettingwidget.h.
Constructor & Destructor Documentation
rcCheckboxSettingWidget::rcCheckboxSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 16 of file rc_checkboxsettingwidget.cpp.
References rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getTag(), rcSettingWidget::mTopLayout, mWidget, settingChanged(), and valueChanged().
     : rcSettingWidget( parent, setting )
 {
     mWidget = new QCheckBox( 0, this , setting.getTag() );
     mTopLayout->addWidget( mWidget );
     mTopLayout->addStretch();
     QToolTip::add( mWidget, setting.getDescription() );
     // update the combo box with the current value of the setting.
     settingChanged();
     connect( mWidget , SIGNAL( toggled( bool ) ) , this , SLOT( valueChanged( bool ) ) );
     // connect this widget to be notified by the updateSettings()
     // signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
 }
rcCheckboxSettingWidget::~rcCheckboxSettingWidget ()
Definition at line 38 of file rc_checkboxsettingwidget.cpp.
References mWidget.
 {
     QToolTip::remove( mWidget );
 }
Member Function Documentation
void rcCheckboxSettingWidget::settingChanged (void) slot
Definition at line 58 of file rc_checkboxsettingwidget.cpp.
References rcSettingInfo::getValue(), rcSettingWidget::mSetting, mWidget, and rcSettingWidget::updateWidgetState().
Referenced by rcCheckboxSettingWidget().
 {
     bool currentValue = mSetting.getValue();
     if ( mWidget->isChecked() != currentValue )
         mWidget->setChecked( currentValue );
     // Update visibility/editability
     updateWidgetState();
 }
void rcCheckboxSettingWidget::valueChanged (bool newValue) slot
Definition at line 46 of file rc_checkboxsettingwidget.cpp.
References rcModelDomain::getModelDomain(), rcSettingInfo::getValue(), rcSettingWidget::mSetting, rcModelDomain::notifySettingChange(), and rcSettingInfo::setValue().
Referenced by rcCheckboxSettingWidget().
 {
     bool currentValue = mSetting.getValue();
     if ( newValue != currentValue )
         mSetting.setValue( newValue );
     // notify everybody about the change
     rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
QCheckBox* rcCheckboxSettingWidget::mWidget private
Definition at line 25 of file rc_checkboxsettingwidget.h.
Referenced by rcCheckboxSettingWidget(), settingChanged(), and ~rcCheckboxSettingWidget().
The documentation for this class was generated from the following files:
include/visUI/rc_checkboxsettingwidget.h
src/visible/qt/rc_checkboxsettingwidget.cpp