Visible: rcThumbWheelSettingWidget Class Reference
rcThumbWheelSettingWidget Class Reference
#include <include/visUI/rc_thumbwheelsettingwidget.h>
Public Slots
virtual void valueChanged (int)
Makes valueChanged() available as a slot.
void settingChanged ()
Setting has changed, update widget.
void updateRotation (float angle)
Setting has been changed, update widget.
Public Slots inherited from rcSettingWidget
void updateWidgetState ()
Update widget visibility/editability state based on setting state.
Public Member Functions
rcThumbWheelSettingWidget (QWidget *parent, const rcSettingInfo &setting)
~rcThumbWheelSettingWidget ()
Destructs the wheel.
Public Member Functions inherited from rcSettingWidget
rcSettingWidget (QWidget *parent, const rcSettingInfo &setting, bool createTopLayout=true)
virtual ~rcSettingWidget ()
Private Member Functions
void updateLabel ()
Update value display label.
Private Attributes
QSlider * mWheel
QLabel * mValueLabel
Additional Inherited Members
Protected Attributes inherited from rcSettingWidget
rcSettingInfo mSetting
Q3BoxLayout * mTopLayout
QLabel * mDisplayLabel
Detailed Description
Definition at line 23 of file rc_thumbwheelsettingwidget.h.
Constructor & Destructor Documentation
rcThumbWheelSettingWidget::rcThumbWheelSettingWidget (QWidget * parent, const rcSettingInfo & setting)
Definition at line 23 of file rc_thumbwheelsettingwidget.cpp.
References cUIsettingLabelSpacing, rcSettingInfo::getDescription(), rcModelDomain::getModelDomain(), rcSettingInfo::getXArgs(), rcThumbWheelArgs::maxValue, rcThumbWheelArgs::minValue, rcSettingWidget::mTopLayout, mValueLabel, mWheel, rcThumbWheelArgs::orientation, settingChanged(), updateLabel(), and valueChanged().
         : rcSettingWidget( parent, setting )
 {
     mWheel = new QSlider (0, 360, 1, 0 , Qt::Horizontal,  this );
     mTopLayout->addWidget( mWheel );
     mTopLayout->addSpacing( cUIsettingLabelSpacing );
     // Label to display setting value
     mValueLabel = new QLabel( " " , this );
     mTopLayout->addWidget( mValueLabel );
     //    mWheel->setMinimumHeight( 10 );
     //    mWheel->setMaximumWidth( 180 );
     const rcThumbWheelArgs* argsP = static_cast<const rcThumbWheelArgs*>(setting.getXArgs());
     if ( argsP )
       {
       mWheel->setMinValue ( argsP->minValue);
       mWheel->setMaxValue (argsP->maxValue );
       mWheel->setOrientation( (argsP->orientation ? Qt::Vertical : Qt::Horizontal ) );
     }
     // use the setting description as a tool tip
     QToolTip::add( this , setting.getDescription() );
     // route thumbwheel's valueChanged signal to our single
     // valueChanged slot
     connect( mWheel , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( int ) ) );
     // connect this widget to be notified by the updateSettings()
     // signal from the model domain
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     connect( domain , SIGNAL( updateSettings() ) ,
              this   , SLOT( settingChanged() ) );
     //  connect( domain , SIGNAL( updateAnalysisRectRotation( float ) ) ,
     //           this   , SLOT( updateRotation( float ) ) );
     updateLabel();
 }
rcThumbWheelSettingWidget::~rcThumbWheelSettingWidget ()
Destructs the wheel.
Definition at line 71 of file rc_thumbwheelsettingwidget.cpp.
 {
     QToolTip::remove( this );
 }
Member Function Documentation
void rcThumbWheelSettingWidget::settingChanged (void) slot
Setting has changed, update widget.
Available as a slot.
Definition at line 99 of file rc_thumbwheelsettingwidget.cpp.
References rcSettingInfo::getValue(), rcSettingWidget::mSetting, mWheel, updateLabel(), rcSettingWidget::updateWidgetState(), and valueChanged().
Referenced by rcThumbWheelSettingWidget().
 {
     disconnect( mWheel , SIGNAL( valueChanged( int ) )  ,
                 this , SLOT( valueChanged( int ) ) );
     int32 currentValue = mSetting.getValue();
     if ( mWheel->value() != currentValue ) {
         mWheel->setValue( currentValue );
         updateLabel();
     }
     // Update visibility/editability
     updateWidgetState();
     connect( mWheel , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( int ) ) );
 }
void rcThumbWheelSettingWidget::updateLabel () private
Update value display label.
Definition at line 138 of file rc_thumbwheelsettingwidget.cpp.
References mValueLabel, and mWheel.
Referenced by rcThumbWheelSettingWidget(), settingChanged(), updateRotation(), and valueChanged().
 {
     QString str;
     // Update value display
     str.sprintf( "%i", mWheel->value() );
     mValueLabel->setText( str );
 }
void rcThumbWheelSettingWidget::updateRotation (float angle) slot
Setting has been changed, update widget.
Available as a slot.
Definition at line 121 of file rc_thumbwheelsettingwidget.cpp.
References mWheel, updateLabel(), and valueChanged().
 {
     disconnect( mWheel , SIGNAL( valueChanged( int ) )  ,
                 this , SLOT( valueChanged( int ) ) );
     mWheel->setValue( static_cast<int32>(angle) );
     updateLabel();
     connect( mWheel , SIGNAL( valueChanged( int ) )  ,
              this , SLOT( valueChanged( int ) ) );
 }
void rcThumbWheelSettingWidget::valueChanged (int v) virtual slot
Makes valueChanged() available as a slot.
Definition at line 82 of file rc_thumbwheelsettingwidget.cpp.
References rcSettingInfo::getValue(), rcSettingWidget::mSetting, rcSettingInfo::setValue(), and updateLabel().
Referenced by rcThumbWheelSettingWidget(), settingChanged(), and updateRotation().
 {
     bool currentValue = mSetting.getValue();
     if ( v != currentValue ) {
         mSetting.setValue( v );
         updateLabel();
     }
     // Do not notify, this is a "real-time" operation and sepcial signal is used
     //rcModelDomain::getModelDomain()->notifySettingChange();
 }
Member Data Documentation
QLabel* rcThumbWheelSettingWidget::mValueLabel private
Definition at line 45 of file rc_thumbwheelsettingwidget.h.
Referenced by rcThumbWheelSettingWidget(), and updateLabel().
QSlider* rcThumbWheelSettingWidget::mWheel private
Definition at line 44 of file rc_thumbwheelsettingwidget.h.
Referenced by rcThumbWheelSettingWidget(), settingChanged(), updateLabel(), and updateRotation().
The documentation for this class was generated from the following files:
include/visUI/rc_thumbwheelsettingwidget.h
src/visible/qt/rc_thumbwheelsettingwidget.cpp