Visible: cli_parser Class Reference
cli_parser Class Reference
#include <include/stlplus/cli_parser.hpp>
Public Types
typedef cli_kind_t kind_t
typedef cli_mode_t mode_t
typedef cli_definition_t definition_t
typedef cli_definitions_t definitions_t
typedef cli_definition definition
typedef cli_definitions definitions
Public Member Functions
cli_parser (error_handler &errors) throw ()
cli_parser (cli_definitions_t, error_handler &errors) throw (cli_mode_error)
cli_parser (cli_definitions_t, const ini_manager &defaults, const std::string &ini_section, error_handler &errors) throw (cli_mode_error)
cli_parser (char *argv[], cli_definitions_t, error_handler &errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
cli_parser (char *argv[], cli_definitions_t, const ini_manager &defaults, const std::string &ini_section, error_handler &errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
cli_parser (cli_definitions, error_handler &errors) throw (cli_mode_error)
cli_parser (cli_definitions, const ini_manager &defaults, const std::string &ini_section, error_handler &errors) throw (cli_mode_error)
cli_parser (char *argv[], cli_definitions, error_handler &errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
cli_parser (char *argv[], cli_definitions, const ini_manager &defaults, const std::string &ini_section, error_handler &errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
~cli_parser (void) throw ()
void add_definitions (cli_definitions_t) throw (cli_mode_error)
unsigned add_definition (const definition_t &) throw (cli_mode_error,cli_argument_error)
void add_definitions (cli_definitions) throw (cli_mode_error)
unsigned add_definition (const definition &) throw (cli_mode_error)
void set_defaults (const ini_manager &defaults, const std::string &ini_section) throw ()
bool parse (char *argv[]) throw (cli_argument_error,error_handler_id_error,error_handler_format_error)
bool valid (void) throw ()
unsigned size (void) const throw ()
std::string name (unsigned i) const throw (cli_index_error)
unsigned id (unsigned i) const throw (cli_index_error)
cli_kind_t kind (unsigned i) const throw (cli_index_error)
bool switch_kind (unsigned i) const throw (cli_index_error)
bool value_kind (unsigned i) const throw (cli_index_error)
cli_mode_t mode (unsigned i) const throw (cli_index_error)
bool single_mode (unsigned i) const throw (cli_index_error)
bool multiple_mode (unsigned i) const throw (cli_index_error)
bool cumulative_mode (unsigned i) const throw (cli_index_error)
bool switch_value (unsigned i) const throw (cli_mode_error,cli_index_error)
std::string string_value (unsigned i) const throw (cli_mode_error,cli_index_error)
void usage (void) const throw (std::runtime_error)
Private Attributes
smart_ptr< cli_parser_data > m_data
Friends
class cli_parser_data
Detailed Description
Definition at line 130 of file cli_parser.hpp.
Member Typedef Documentation
typedef cli_definition cli_parser::definition
Definition at line 139 of file cli_parser.hpp.
typedef cli_definition_t cli_parser::definition_t
Definition at line 137 of file cli_parser.hpp.
typedef cli_definitions cli_parser::definitions
Definition at line 140 of file cli_parser.hpp.
typedef cli_definitions_t cli_parser::definitions_t
Definition at line 138 of file cli_parser.hpp.
typedef cli_kind_t cli_parser::kind_t
Definition at line 135 of file cli_parser.hpp.
typedef cli_mode_t cli_parser::mode_t
Definition at line 136 of file cli_parser.hpp.
Constructor & Destructor Documentation
cli_parser::cli_parser (error_handler & errors) throw ()
Definition at line 218 of file cli_parser.cpp.
                                                     :
   m_data(new cli_parser_data(errors))
 {
 }
cli_parser::cli_parser (cli_definitions_t definitions, error_handler & errors) throw (cli_mode_error)
Definition at line 223 of file cli_parser.cpp.
                                                                                                        :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
 }
cli_parser::cli_parser (cli_definitions_t definitions, const ini_manager & defaults, const std::string & ini_section, error_handler & errors) throw (cli_mode_error)
Definition at line 229 of file cli_parser.cpp.
                                                                                                                                                                    :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
   set_defaults(defaults, ini_section);
 }
cli_parser::cli_parser (char * argv[], cli_definitions_t definitions, error_handler & errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
Definition at line 236 of file cli_parser.cpp.
                                                                                                                                                                         :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
   parse(argv);
 }
cli_parser::cli_parser (char * argv[], cli_definitions_t definitions, const ini_manager & defaults, const std::string & ini_section, error_handler & errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
Definition at line 243 of file cli_parser.cpp.
                                                                                                                                                                                                                                    :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
   set_defaults(defaults, ini_section);
   parse(argv);
 }
cli_parser::cli_parser (cli_definitions definitions, error_handler & errors) throw (cli_mode_error)
Definition at line 251 of file cli_parser.cpp.
                                                                                                      :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
 }
cli_parser::cli_parser (cli_definitions definitions, const ini_manager & defaults, const std::string & ini_section, error_handler & errors) throw (cli_mode_error)
Definition at line 257 of file cli_parser.cpp.
                                                                                                                                                                  :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
   set_defaults(defaults, ini_section);
 }
cli_parser::cli_parser (char * argv[], cli_definitions definitions, error_handler & errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
Definition at line 264 of file cli_parser.cpp.
                                                                                                                                                                       :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
   parse(argv);
 }
cli_parser::cli_parser (char * argv[], cli_definitions definitions, const ini_manager & defaults, const std::string & ini_section, error_handler & errors) throw (cli_mode_error,error_handler_id_error,error_handler_format_error)
Definition at line 271 of file cli_parser.cpp.
                                                                                                                                                                                                                                  :
   m_data(new cli_parser_data(errors))
 {
   add_definitions(definitions);
   set_defaults(defaults, ini_section);
   parse(argv);
 }
cli_parser::~cli_parser (void) throw ()
Definition at line 279 of file cli_parser.cpp.
 {
 }
Member Function Documentation
unsigned cli_parser::add_definition (const definition_t & definition) throw (cli_mode_error,cli_argument_error)
Definition at line 291 of file cli_parser.cpp.
References cli_switch_kind, cli_definition::m_default, cli_definition::m_kind, cli_definition::m_message, cli_definition::m_mode, and cli_definition::m_name.
 {
   if (!definition.m_name) throw cli_argument_error("Definition must have a valid name");
   // chk for stupid combinations
   // at this stage the only really stupid one is to declare command line arguments to be switch mode
   if (definition.m_name[0] == '\0' && definition.m_kind == cli_switch_kind)
   {
     m_data->set_invalid();
     throw cli_mode_error("CLI arguments cannot be switch kind");
   }
   // add the definition to the set of all definitions
   unsigned i = m_data->add_definition(definition.m_name, definition.m_kind, definition.m_mode, definition.m_message);
   // also add it to the list of values, but only if it has a default value
   if (definition.m_default) m_data->add_value(i, definition.m_default, "builtin default");
   return i;
 }
unsigned cli_parser::add_definition (const definition & definition) throw (cli_mode_error)
Definition at line 315 of file cli_parser.cpp.
References cli_switch_kind, cli_definition::m_default, cli_definition::m_kind, cli_definition::m_message, cli_definition::m_mode, and cli_definition::m_name.
 {
   // chk for stupid combinations
   // at this stage the only really stupid one is to declare command line arguments to be switch mode
   if (definition.m_name.empty() && definition.m_kind == cli_switch_kind)
   {
     m_data->set_invalid();
     throw cli_mode_error("CLI arguments cannot be switch kind");
   }
   // add the definition to the set of all definitions
   unsigned i = m_data->add_definition(definition.m_name, definition.m_kind, definition.m_mode, definition.m_message);
   // also add it to the list of values, but only if it has a default value
   if (!definition.m_default.empty()) m_data->add_value(i, definition.m_default, "builtin default");
   return i;
 }
void cli_parser::add_definitions (cli_definitions_t definitions) throw (cli_mode_error)
Definition at line 283 of file cli_parser.cpp.
 {
   m_data->clear_definitions();
   // the definitions array is terminated by a definition with a null name pointer
   for (unsigned i = 0; definitions[i].m_name; i++)
     add_definition(definitions[i]);
 }
void cli_parser::add_definitions (cli_definitions definitions) throw (cli_mode_error)
Definition at line 308 of file cli_parser.cpp.
 {
   m_data->clear_definitions();
   for (unsigned i = 0; i < definitions.size(); i++)
     add_definition(definitions[i]);
 }
bool cli_parser::cumulative_mode (unsigned i) const throw (cli_index_error)
Definition at line 500 of file cli_parser.cpp.
References cli_cumulative_mode.
 {
   return mode(i) == cli_cumulative_mode;
 }
unsigned cli_parser::id (unsigned i) const throw (cli_index_error)
Definition at line 462 of file cli_parser.cpp.
References to_string().
 {
   if (i >= size()) throw cli_index_error("Index " + to_string(i) + " out of range");
   return m_data->m_values[i].m_definition;
 }
cli_parser::kind_t cli_parser::kind (unsigned i) const throw (cli_index_error)
Definition at line 468 of file cli_parser.cpp.
References to_string().
Referenced by usage().
 {
   if (i >= size()) throw cli_index_error("Index " + to_string(i) + " out of range");
   return m_data->m_definitions[m_data->m_values[i].m_definition].m_kind;
 }
cli_parser::mode_t cli_parser::mode (unsigned i) const throw (cli_index_error)
Definition at line 484 of file cli_parser.cpp.
References to_string().
 {
   if (i >= size()) throw cli_index_error("Index " + to_string(i) + " out of range");
   return m_data->m_definitions[m_data->m_values[i].m_definition].m_mode;
 }
bool cli_parser::multiple_mode (unsigned i) const throw (cli_index_error)
Definition at line 495 of file cli_parser.cpp.
References cli_multiple_mode.
 {
   return mode(i) == cli_multiple_mode;
 }
std::string cli_parser::name (unsigned i) const throw (cli_index_error)
Definition at line 456 of file cli_parser.cpp.
References to_string().
Referenced by color(), contentFile(), count(), help(), percent(), repFile(), sample(), searchDir(), startframe(), tmpDir(), usage(), verbose(), and version().
 {
   if (i >= size()) throw cli_index_error("Index " + to_string(i) + " out of range");
   return m_data->m_definitions[m_data->m_values[i].m_definition].m_name;
 }
bool cli_parser::parse (char * argv[]) throw (cli_argument_error,error_handler_id_error,error_handler_format_error)
Definition at line 371 of file cli_parser.cpp.
References cli_switch_kind, and cli_value_kind.
 {
   bool result = true;
   if (!argv) throw cli_argument_error("Argument vector cannot be null");
   m_data->increase_level();
   if (argv[0])
     m_data->m_executable = argv[0];
   for (unsigned i = 1; argv[i]; i++)
   {
     std::string name = argv[i];
     if (!name.empty() && name[0] == '-')
     {
       // we have a command line option
       unsigned found = m_data->find_definition(name.substr(1, name.size()-1));
       if (found < m_data->m_definitions.size())
       {
         // found it in its positive form
         switch (m_data->m_definitions[found].m_kind)
         {
         case cli_switch_kind:
           m_data->add_switch(found, true, "command line");
           break;
         case cli_value_kind:
           // get the next argument in argv as the value of this option
           // first chk that there is a next value
           if (!argv[i+1])
             result &= m_data->m_errors.error("CLI_VALUE_MISSING", name);
           else
             m_data->add_value(found, argv[++i], "command line");
           break;
         }
       }
       else if (name.size() > 3 && name.substr(1,2) == "no")
       {
         found = m_data->find_definition(name.substr(3, name.size()-3));
         if (found < m_data->m_definitions.size())
         {
           // found it in its negated form
           switch (m_data->m_definitions[found].m_kind)
           {
           case cli_switch_kind:
             m_data->add_switch(found, false, "command line");
             break;
           case cli_value_kind:
             m_data->erase_value(found);
             break;
           }
         }
         else
         {
           // could not find this option in either its true or negated form
           result &= m_data->m_errors.error("CLI_UNRECOGNISED_OPTION", name);
         }
       }
       else
       {
         // could not find this option and it could not be negated
         result &= m_data->m_errors.error("CLI_UNRECOGNISED_OPTION", name);
       }
     }
     else
     {
       // we have a command-line value which is represented internally as an option with an empty string as its name
       // some very obscure commands do not have values - only options, so allow for that case too
       unsigned found = m_data->find_definition("");
       if (found < m_data->m_definitions.size())
         m_data->add_value(found, name, "command line");
       else
         result &= m_data->m_errors.error("CLI_NO_VALUES", name);
     }
   }
   if (!result) m_data->set_invalid();
   return result;
 }
void cli_parser::set_defaults (const ini_manager & defaults, const std::string & ini_section) throw ()
Definition at line 331 of file cli_parser.cpp.
References filespec_to_relative_path().
 {
   // import default values from the Ini Manager
   m_data->increase_level();
   // get the set of all names from the Ini manager so that illegal names generate meaningful error messages
   std::vector<std::string> names = defaults.variable_names(ini_section);
   for (unsigned i = 0; i < names.size(); i++)
   {
     std::string name = names[i];
     unsigned definition = m_data->find_definition(name);
     if (definition == m_data->m_definitions.size())
     {
       // not found - give an error report
       error_position position(defaults.variable_filename(ini_section,name),
                               defaults.variable_linenumber(ini_section,name),
                               0);
       m_data->m_errors.error(position,"CLI_INI_VARIABLE", name);
     }
     else
     {
       // found - so add the value
       // multi-valued variables are entered as a comma-separated list and this is then turned into a vector
       // the vector is empty if the value was empty
       std::vector<std::string> values = defaults.variable_values(ini_section, name);
       // an empty string is used to negate the value
       if (values.empty())
         m_data->erase_value(definition);
       else
       {
         std::string source = filespec_to_relative_path(defaults.variable_filename(ini_section, name));
         for (unsigned j = 0; j < values.size(); j++)
           m_data->add_value(definition, values[j], source);
       }
     }
   }
   // add the set of ini files to the list for usage reports
   for (unsigned j = 0; j < defaults.size(); j++)
     m_data->add_ini_file(defaults.filename(j));
 }
bool cli_parser::single_mode (unsigned i) const throw (cli_index_error)
Definition at line 490 of file cli_parser.cpp.
References cli_single_mode.
 {
   return mode(i) == cli_single_mode;
 }
unsigned cli_parser::size (void) const throw ()
Definition at line 451 of file cli_parser.cpp.
References m_data, and cli_parser_data::m_values.
Referenced by color(), contentFile(), count(), help(), main(), percent(), repFile(), sample(), searchDir(), startframe(), tmpDir(), usage(), verbose(), and version().
 {
   return m_data->m_values.size();
 }
std::string cli_parser::string_value (unsigned i) const throw (cli_mode_error,cli_index_error)
Definition at line 513 of file cli_parser.cpp.
References cli_value_kind, and to_string().
Referenced by contentFile(), count(), percent(), repFile(), sample(), searchDir(), startframe(), tmpDir(), and usage().
 {
   if (i >= size()) throw cli_index_error("Index " + to_string(i) + " out of range");
   if (kind(i) != cli_value_kind) throw cli_mode_error(name(i) + " is not a value kind");
   return m_data->m_values[i].m_value;
 }
bool cli_parser::switch_kind (unsigned i) const throw (cli_index_error)
Definition at line 474 of file cli_parser.cpp.
References cli_switch_kind.
 {
   return kind(i) == cli_switch_kind;
 }
bool cli_parser::switch_value (unsigned i) const throw (cli_mode_error,cli_index_error)
Definition at line 505 of file cli_parser.cpp.
References cli_switch_kind, lowercase(), and to_string().
Referenced by color(), help(), usage(), verbose(), and version().
 {
   if (i >= size()) throw cli_index_error("Index " + to_string(i) + " out of range");
   if (kind(i) != cli_switch_kind) throw cli_mode_error(name(i) + " is not a switch kind");
   std::string value = lowercase(m_data->m_values[i].m_value);
   return value == "on" || value == "true" || value == "1";
 }
void cli_parser::usage (void) const throw (std::runtime_error)
Definition at line 522 of file cli_parser.cpp.
References cli_switch_kind, file_exists(), filespec_to_relative_path(), error_handler::information(), cli_parser_data::ini_file(), cli_parser_data::ini_file_size(), kind(), m_data, cli_parser_data::m_definitions, cli_parser_data::m_errors, cli_parser_data::m_executable, cli_parser_data::m_values, name(), size(), string_value(), and switch_value().
 {
   m_data->m_errors.information("CLI_USAGE_PROGRAM", m_data->m_executable);
   m_data->m_errors.information("CLI_USAGE_DEFINITIONS");
   for (unsigned d = 0; d < m_data->m_definitions.size(); d++)
   {
     m_data->m_errors.information(m_data->m_definitions[d].m_message);
   }
   if (size() != 0)
   {
     m_data->m_errors.information("CLI_USAGE_VALUES");
     for (unsigned v = 0; v < size(); v++)
     {
       std::string source = m_data->m_values[v].m_source;
       std::string key = name(v);
       if (key.empty())
       {
         // command-line values
         m_data->m_errors.information("CLI_USAGE_VALUE_RESULT", string_value(v), source);
       }
       else if (kind(v) == cli_switch_kind)
       {
         // a switch
         m_data->m_errors.information("CLI_USAGE_SWITCH_RESULT", (switch_value(v) ? name(v) : "no" + name(v)), source);
       }
       else
       {
         // other values
         std::vector<std::string> args;
         args.push_back(name(v));
         args.push_back(string_value(v));
         args.push_back(source);
         m_data->m_errors.information("CLI_USAGE_OPTION_RESULT", args);
       }
     }
   }
   if (m_data->ini_file_size() > 0)
   {
     m_data->m_errors.information("CLI_INI_HEADER");
     for (unsigned i = 0; i < m_data->ini_file_size(); i++)
     {
       if (file_exists(m_data->ini_file(i)))
         m_data->m_errors.information("CLI_INI_FILE_PRESENT", filespec_to_relative_path(m_data->ini_file(i)));
       else
         m_data->m_errors.information("CLI_INI_FILE_ABSENT", filespec_to_relative_path(m_data->ini_file(i)));
     }
   }
 }
bool cli_parser::valid (void) throw ()
Definition at line 446 of file cli_parser.cpp.
References m_data, and cli_parser_data::valid().
 {
   return m_data->valid();
 }
bool cli_parser::value_kind (unsigned i) const throw (cli_index_error)
Definition at line 479 of file cli_parser.cpp.
References cli_value_kind.
 {
   return kind(i) == cli_value_kind;
 }
Friends And Related Function Documentation
friend class cli_parser_data friend
Definition at line 285 of file cli_parser.hpp.
Member Data Documentation
smart_ptr<cli_parser_data> cli_parser::m_data private
Definition at line 286 of file cli_parser.hpp.
Referenced by size(), usage(), and valid().
The documentation for this class was generated from the following files:
include/stlplus/cli_parser.hpp
include/stlplus/cli_parser.cpp