Visible: include/stlplus/dprintf.cpp File Reference
dprintf.cpp File Reference
#include "dprintf.hpp"
#include "debug.hpp"
#include "string_utilities.hpp"
#include <stdio.h>
#include <limits.h>
#include <float.h>
#include <ctype.h>
Functions
int vdprintf (std::string &formatted, const char *format, va_list args)
int dprintf (std::string &formatted, const char *format,...)
std::string vdformat (const char *format, va_list args) throw (std::invalid_argument)
std::string dformat (const char *format,...) throw (std::invalid_argument)
Function Documentation
std::string dformat (const char * format, ...) throw (std::invalid_argument)
Definition at line 79 of file dprintf.cpp.
References vdprintf().
Referenced by display_bytes(), timer::text(), and to_string().
 {
   std::string formatted;
   va_list args;
   va_start(args, format);
   int length = vdprintf(formatted, format, args);
   va_end(args);
   if (length < 0) throw std::invalid_argument("dprintf");
   return formatted;
 }
int dprintf (std::string & formatted, const char * format, ...)
Definition at line 62 of file dprintf.cpp.
References vdprintf().
 {
   va_list args;
   va_start(args, format);
   int result = vdprintf(formatted, format, args);
   va_end(args);
   return result;
 }
std::string vdformat (const char * format, va_list args) throw (std::invalid_argument)
Definition at line 71 of file dprintf.cpp.
References vdprintf().
 {
   std::string formatted;
   int length = vdprintf(formatted, format, args);
   if (length < 0) throw std::invalid_argument("dprintf");
   return formatted;
 }
int vdprintf (std::string & formatted, const char * format, va_list args)
Definition at line 29 of file dprintf.cpp.
Referenced by dformat(), dprintf(), and vdformat().
 {
 #ifdef MSWINDOWS
   int length = 0;
   char* buffer = 0;
   for(int buffer_length = 256; ; buffer_length*=2)
   {
     buffer = (char*)malloc(buffer_length);
     if (!buffer) return -1;
     length = _vsnprintf(buffer, buffer_length-1, format, args);
     if (length >= 0)
     {
       buffer[length] = 0;
       formatted += std::string(buffer);
       free(buffer);
       break;
     }
     free(buffer);
   }
   return length;
 #else
   char* buffer = 0;
   int length = vasprintf(&buffer, format, args);
   if (!buffer) return -1;
   if (length >= 0)
   {
     formatted += std::string(buffer);
   }
   free(buffer);
   return length;
 #endif
 }