Visible: include/stlplus/error_handler.cpp File Reference
error_handler.cpp File Reference
#include "error_handler.hpp"
#include "fileio.hpp"
#include "file_system.hpp"
#include "string_utilities.hpp"
#include "debug.hpp"
#include <ctype.h>
Classes
class message
class pending_message
class error_handler_base_body
class error_handler_body
Functions
std::string to_string (const error_position &where)
otext & operator<< (otext &output, const error_position &where)
Variables
static char * information_id = "INFORMATION"
static char * context_id = "CONTEXT"
static char * supplement_id = "SUPPLEMENT"
static char * warning_id = "WARNING"
static char * error_id = "ERROR"
static char * fatal_id = "FATAL"
static char * position_id = "POSITION"
static char * default_information_format = "@0"
static char * default_context_format = "context: @0"
static char * default_supplement_format = "supplement: @0"
static char * default_warning_format = "warning: @0"
static char * default_error_format = "error: @0"
static char * default_fatal_format = "FATAL: @0"
static char * default_position_format = "\"@1\" (@2,@3) : @0"
Function Documentation
otext& operator<< (otext & output, const error_position & where)
Definition at line 120 of file error_handler.cpp.
References to_string().
 {
   return output << to_string(where);
 }
std::string to_string (const error_position & where)
Definition at line 115 of file error_handler.cpp.
References error_position::column(), error_position::filename(), filespec_to_relative_path(), error_position::line(), and to_string().
Referenced by _sm2out(), inf::bit(), inf::clear(), display_time(), divide(), inf::dump(), dump_context_body::dump_context_body(), error_string(), subprocess::error_text(), async_subprocess::error_text(), error_handler_base_body::format_id(), cli_parser::id(), cli_parser::kind(), cli_parser::mode(), cli_parser::name(), operator<<(), print(), inf::restore(), restore_context_body::restore_context_body(), restore_float(), restore_signed(), restore_unsigned(), inf::set(), simage(), inf::slice(), cli_parser::string_value(), svalue(), cli_parser::switch_value(), textio_error_string(), to_inf(), to_string(), inf::to_string(), uimage(), and uvalue().
 {
   return "{" + filespec_to_relative_path(where.filename()) + ":" + to_string(where.line()) + ":" + to_string(where.column()) + "}";
 }
Variable Documentation
char* context_id = "CONTEXT" static
Definition at line 18 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base_body::format_report(), and error_handler_base::set_context_format().
char* default_context_format = "context: @0" static
Definition at line 26 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* default_error_format = "error: @0" static
Definition at line 29 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* default_fatal_format = "FATAL: @0" static
Definition at line 30 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* default_information_format = "@0" static
Definition at line 25 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* default_position_format = "\"@1\" (@2,@3) : @0" static
Definition at line 31 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* default_supplement_format = "supplement: @0" static
Definition at line 27 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* default_warning_format = "warning: @0" static
Definition at line 28 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body().
char* error_id = "ERROR" static
Definition at line 21 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base::error_message(), and error_handler_base::set_error_format().
char* fatal_id = "FATAL" static
Definition at line 22 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base::fatal_message(), and error_handler_base::set_fatal_format().
char* information_id = "INFORMATION" static
Definition at line 17 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base::information_message(), and error_handler_base::set_information_format().
char* position_id = "POSITION" static
Definition at line 23 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base_body::format_id(), and error_handler_base::set_position_format().
char* supplement_id = "SUPPLEMENT" static
Definition at line 19 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base_body::format_report(), and error_handler_base::set_supplement_format().
char* warning_id = "WARNING" static
Definition at line 20 of file error_handler.cpp.
Referenced by error_handler_base_body::error_handler_base_body(), error_handler_base::set_warning_format(), and error_handler_base::warning_message().