Visible: include/stlplus/error_handler.hpp File Reference
error_handler.hpp File Reference
#include "os_fixes.hpp"
#include "textio.hpp"
#include "smart_ptr.hpp"
#include <string>
#include <map>
#include <list>
#include <vector>
#include <stdexcept>
Classes
class error_position
class error_context_body
class error_handler_read_error
class error_handler_format_error
class error_handler_id_error
class error_handler_limit_error
class error_handler_fatal_error
class error_handler_base
class error_handler
Typedefs
typedef error_position error_handler_position
typedef smart_ptr_nocopy
< error_context_body > error_context
Functions
std::string to_string (const error_position &where)
otext & operator<< (otext &output, const error_position &where)
Typedef Documentation
typedef smart_ptr_nocopy<error_context_body> error_context
Definition at line 98 of file error_handler.hpp.
typedef error_position error_handler_position
Definition at line 67 of file error_handler.hpp.
Function Documentation
otext& operator<< (otext & output, const error_position & where)
Definition at line 120 of file error_handler.cpp.
References to_string().
 {
   return output << to_string(where);
 }
std::string to_string (const error_position & where)
Definition at line 115 of file error_handler.cpp.
References error_position::column(), error_position::filename(), filespec_to_relative_path(), error_position::line(), and to_string().
Referenced by _sm2out(), inf::bit(), inf::clear(), display_time(), divide(), inf::dump(), dump_context_body::dump_context_body(), error_string(), subprocess::error_text(), async_subprocess::error_text(), error_handler_base_body::format_id(), cli_parser::id(), cli_parser::kind(), cli_parser::mode(), cli_parser::name(), operator<<(), print(), inf::restore(), restore_context_body::restore_context_body(), restore_float(), restore_signed(), restore_unsigned(), inf::set(), simage(), inf::slice(), cli_parser::string_value(), svalue(), cli_parser::switch_value(), textio_error_string(), to_inf(), to_string(), inf::to_string(), uimage(), and uvalue().
 {
   return "{" + filespec_to_relative_path(where.filename()) + ":" + to_string(where.line()) + ":" + to_string(where.column()) + "}";
 }