Visible: include/stlplus/file_system.hpp File Reference
file_system.hpp File Reference
#include "os_fixes.hpp"
#include <string>
#include <vector>
#include <time.h>
Macros
#define PATH_SPLITTER ":"
Functions
bool path_compare (const std::string &l, const std::string &r)
bool is_present (const std::string &thing)
bool is_folder (const std::string &thing)
bool is_file (const std::string &thing)
bool file_exists (const std::string &filespec)
bool file_readable (const std::string &filespec)
bool file_writable (const std::string &filespec)
size_t file_size (const std::string &filespec)
bool file_delete (const std::string &filespec)
bool file_rename (const std::string &old_filespec, const std::string &new_filespec)
bool file_move (const std::string &old_filespec, const std::string &new_filespec)
bool file_copy (const std::string &old_filespec, const std::string &new_filespec)
bool file_set_mode (const std::string &filespec, int mode)
time_t file_created (const std::string &filespec)
time_t file_modified (const std::string &filespec)
time_t file_accessed (const std::string &filespec)
std::string create_filespec (const std::string &folder, const std::string &filename)
std::string create_filespec (const std::string &folder, const std::string &basename, const std::string &extension)
std::string create_filename (const std::string &basename, const std::string &extension)
bool folder_create (const std::string &folder)
bool folder_exists (const std::string &folder)
bool folder_readable (const std::string &folder)
bool folder_writable (const std::string &folder)
bool folder_delete (const std::string &folder, bool recurse=false)
bool folder_rename (const std::string &old_directory, const std::string &new_directory)
bool folder_empty (const std::string &folder)
bool folder_set_current (const std::string &folder)
std::string folder_current (void)
std::string folder_current_full (void)
std::string folder_home (void)
std::string folder_down (const std::string &folder, const std::string &subfolder)
std::string folder_up (const std::string &folder, unsigned levels=1)
std::vector< std::string > folder_subdirectories (const std::string &folder)
std::vector< std::string > folder_files (const std::string &folder)
std::vector< std::string > folder_all (const std::string &folder)
std::vector< std::string > folder_wildcard (const std::string &folder, const std::string &wildcard, bool subdirs=true, bool files=true)
bool is_full_path (const std::string &path)
bool is_relative_path (const std::string &path)
std::string folder_to_path (const std::string &root, const std::string &folder)
std::string filespec_to_path (const std::string &root, const std::string &filespec)
std::string folder_to_path (const std::string &folder)
std::string filespec_to_path (const std::string &filespec)
std::string folder_to_relative_path (const std::string &root, const std::string &folder)
std::string filespec_to_relative_path (const std::string &root, const std::string &filespec)
std::string folder_to_relative_path (const std::string &folder)
std::string filespec_to_relative_path (const std::string &filespec)
std::string folder_append_separator (const std::string &folder)
std::string basename_part (const std::string &filespec)
std::string filename_part (const std::string &filespec)
std::string extension_part (const std::string &filespec)
std::string folder_part (const std::string &filespec)
std::vector< std::string > folder_elements (const std::string &folder)
std::vector< std::string > filespec_elements (const std::string &filespec)
std::string path_lookup (const std::string &command)
std::string lookup (const std::string &file, const std::string &path, const std::string &splitter=":")
std::string install_path (const std::string &argv0)
Variables
const int read_mode
const int write_mode
const int execute_mode
const int none_mode
const int read_write_mode
const int all_mode
const int owner_mask
const int group_mask
const int other_mask
const int non_owner_mask
const int all_mask
const int read_mode_all
const int read_write_mode_owner_read_mode_all
const int read_mode_owner_only
const int read_write_mode_owner_only
Macro Definition Documentation
#define PATH_SPLITTER ":"
Definition at line 157 of file file_system.hpp.
Referenced by path_lookup().
Function Documentation
std::string basename_part (const std::string & filespec)
Definition at line 880 of file file_system.cpp.
References filename_part().
Referenced by rcMovieConverterToQT::createQTMovie(), lm_library::load_type(), lookup(), and repFile().
 {
   std::string fname = filename_part(spec);
   // scan back through filename until a '.' is found and remove suffix
   // the whole filename is the basename if there is no '.'
   std::string::size_type i = fname.find_last_of('.');
   // observe Unix convention that a dot at the start of a filename is part of the basename, not the extension
   if (i != 0 && i != std::string::npos)
     fname.erase(i, fname.size()-i);
   return fname;
 }
std::string create_filename (const std::string & basename, const std::string & extension)
Definition at line 548 of file file_system.cpp.
Referenced by create_filespec(), and lm_library::load_type().
 {
   std::string name = basename;
   // extension is optional - so the dot is also optional
   if (!extension.empty())
   {
     if (extension[0] != '.') name += '.';
     name += extension;
   }
   return name;
 }
std::string create_filespec (const std::string & folder, const std::string & filename)
Definition at line 531 of file file_system.cpp.
References is_separator(), and preferred_separator.
Referenced by _sm2out(), rcEngineImpl::analyze(), create_filespec(), create_library(), erase_library(), lm_unit::filename(), filespec_to_path(), filespec_to_relative_path(), folder_delete(), folder_empty(), folder_wildcard(), genRFYmov(), lm_unit::header_filename(), library_manager::is_library(), lookup(), read_context(), repFile(), rcEngineImpl::start(), and write_context().
 {
   std::string result = directory;
   // if directory is empty then no directory part will be added
   // add trailing slash if the directory was specified and does not have a trailing slash
   if (!result.empty() && !is_separator(result[result.size()-1]))
     result += preferred_separator;
   // if filename is null or empty, nothing will be added so the path is then a directory path
   result += filename;
   return result;
 }
std::string create_filespec (const std::string & folder, const std::string & basename, const std::string & extension)
Definition at line 543 of file file_system.cpp.
References create_filename(), and create_filespec().
 {
   return create_filespec(directory, create_filename(basename, extension));
 }
std::string extension_part (const std::string & filespec)
Definition at line 905 of file file_system.cpp.
References filename_part().
Referenced by lookup(), and main().
 {
   std::string fname = filename_part(spec);
   // scan back through filename until a '.' is found and remove prefix;
   std::string::size_type i = fname.find_last_of('.');
   // observe Unix convention that a dot at the start of a filename is part of the name, not the extension;
   if (i != 0 && i != std::string::npos)
     fname.erase(0, i+1);
   else
     fname.erase();
   return fname;
 }
time_t file_accessed (const std::string & filespec)
Definition at line 524 of file file_system.cpp.
 {
   struct stat buf;
   if (!(stat(filespec.c_str(), &buf) == 0)) return 0;
   return buf.st_atime;
 }
bool file_copy (const std::string & old_filespec, const std::string & new_filespec)
Definition at line 452 of file file_system.cpp.
References is_file().
Referenced by file_move().
 {
   if (!is_file(old_filespec)) return false;
   // do an exact copy - to do this, use binary mode
   bool result = true;
   FILE* old_file = fopen(old_filespec.c_str(),"rb");
   FILE* new_file = fopen(new_filespec.c_str(),"wb");
   if (!old_file)
     result = false;
   else if (!new_file)
     result = false;
   else
   {
     for (int byte = getc(old_file); byte != EOF; byte = getc(old_file))
       putc(byte,new_file);
   }
   if (old_file) fclose(old_file);
   if (new_file) fclose(new_file);
   return result;
 }
time_t file_created (const std::string & filespec)
Definition at line 510 of file file_system.cpp.
 {
   struct stat buf;
   if (!(stat(filespec.c_str(), &buf) == 0)) return 0;
   return buf.st_ctime;
 }
bool file_delete (const std::string & filespec)
Definition at line 440 of file file_system.cpp.
References is_file().
Referenced by ini_manager::erase(), lm_library::erase(), file_move(), folder_delete(), genRFYmov(), and library_manager::save_mappings().
 {
   if (!is_file(filespec)) return false;
   return remove(filespec.c_str())==0;
 }
bool file_exists (const std::string & filespec)
Definition at line 408 of file file_system.cpp.
References is_file().
Referenced by error_handler_base_body::add_message_file(), erase_library(), file_readable(), library_manager::is_library(), library_manager::load_mappings(), lookup(), read_context(), ini_file::read_file(), lm_unit::restore_header(), and cli_parser::usage().
 {
   return is_file(filespec);
 }
time_t file_modified (const std::string & filespec)
Definition at line 517 of file file_system.cpp.
Referenced by lm_unit::modified(), and out_of_date_chk().
 {
   struct stat buf;
   if (!(stat(filespec.c_str(), &buf) == 0)) return 0;
   return buf.st_mtime;
 }
bool file_move (const std::string & old_filespec, const std::string & new_filespec)
Definition at line 473 of file file_system.cpp.
References file_copy(), file_delete(), and file_rename().
 {
   // try to move the file by renaming - if that fails then do a copy and delete the original
   if (file_rename(old_filespec, new_filespec))
     return true;
   if (!file_copy(old_filespec, new_filespec))
     return false;
   // I'm not sure what to do if the delete fails - is that an error?
   // I've made it an error and then delete the copy so that the original state is recovered
   if (file_delete(old_filespec))
     return true;
   file_delete(new_filespec);
   return false;
 }
bool file_readable (const std::string & filespec)
Definition at line 413 of file file_system.cpp.
References file_exists().
 {
   // a file is readable if it exists and can be read
   if (!file_exists(filespec)) return false;
   return access(filespec.c_str(),R_OK)==0;
 }
bool file_rename (const std::string & old_filespec, const std::string & new_filespec)
Definition at line 446 of file file_system.cpp.
References is_file().
Referenced by file_move().
 {
   if (!is_file(old_filespec)) return false;
   return rename(old_filespec.c_str(), new_filespec.c_str())==0;
 }
bool file_set_mode (const std::string & filespec, int mode)
Definition at line 504 of file file_system.cpp.
References is_file().
 {
   if (!is_file(filespec)) return false;
   return chmod(filespec.c_str(), mode)==0;
 }
size_t file_size (const std::string & filespec)
Definition at line 433 of file file_system.cpp.
Referenced by genRFYmov().
 {
   struct stat buf;
   if (!(stat(filespec.c_str(), &buf) == 0)) return 0;
   return buf.st_size;
 }
bool file_writable (const std::string & filespec)
Definition at line 420 of file file_system.cpp.
References folder_part(), folder_writable(), is_file(), and is_present().
Referenced by ini_file::read_file().
 {
   // a file is writable if it exists as a file and is writable or if it doesn't exist but could be created and would be writable
   if (is_present(filespec))
   {
     if (!is_file(filespec)) return false;
     return access(filespec.c_str(),W_OK)==0;
   }
   std::string dir = folder_part(filespec);
   if (dir.empty()) dir = ".";
   return folder_writable(dir);
 }
std::string filename_part (const std::string & filespec)
Definition at line 892 of file file_system.cpp.
References is_separator().
Referenced by _debug_assert_fail(), _debug_global(), _debug_trace::_debug_trace(), basename_part(), extension_part(), filespec_to_path(), filespec_to_relative_path(), genRFYmov(), and _debug_trace::prefix().
 {
   // scan back through filename until a preferred_separator is found and remove prefix;
   // if there is no preferred_separator then remove nothing, i.e. the whole filespec is filename
   unsigned i = spec.size();
   while (i--)
   {
     if (is_separator(spec[i]))
       return spec.substr(i+1,spec.size()-i-1);
   }
   return spec;
 }
std::vector<std::string> filespec_elements (const std::string & filespec)
Definition at line 931 of file file_system.cpp.
References file_specification::drive(), file_specification::file(), file_specification::initialise_file(), and file_specification::path().
 {
   file_specification spec;
   spec.initialise_file(filespec);
   std::vector<std::string> result = spec.path();
   if (!spec.drive().empty()) result.insert(result.begin(),spec.drive());
   if (!spec.file().empty()) result.push_back(spec.file());
   return result;
 }
std::string filespec_to_path (const std::string & root, const std::string & filespec)
Definition at line 835 of file file_system.cpp.
References create_filespec(), filename_part(), folder_part(), and folder_to_path().
Referenced by ini_manager::add_file(), lm_library::erase_by_source(), filespec_to_path(), and lm_file_dependency::path_full().
 {
   return create_filespec(folder_to_path(path, folder_part(spec)),filename_part(spec));
 }
std::string filespec_to_path (const std::string & filespec)
Definition at line 845 of file file_system.cpp.
References filespec_to_path(), and folder_current().
 {
   return filespec_to_path(folder_current(), filespec);
 }
std::string filespec_to_relative_path (const std::string & root, const std::string & filespec)
Definition at line 855 of file file_system.cpp.
References create_filespec(), filename_part(), folder_part(), and folder_to_relative_path().
Referenced by filespec_to_relative_path(), error_handler_base_body::format_id(), lm_library::pretty_print(), lm_unit::print_long(), cli_parser::set_defaults(), lm_file_dependency::set_path(), to_string(), and cli_parser::usage().
 {
   return create_filespec(folder_to_relative_path(root, folder_part(spec)),filename_part(spec));
 }
std::string filespec_to_relative_path (const std::string & filespec)
Definition at line 865 of file file_system.cpp.
References filespec_to_relative_path(), and folder_current().
 {
   return filespec_to_relative_path(folder_current(), filespec);
 }
std::vector<std::string> folder_all (const std::string & folder)
Definition at line 720 of file file_system.cpp.
References folder_wildcard().
 {
   return folder_wildcard(directory, "*", true, true);
 }
std::string folder_append_separator (const std::string & folder)
Definition at line 870 of file file_system.cpp.
References is_separator(), and preferred_separator.
 {
   std::string result = folder;
   if (result.empty() || !is_separator(result[result.size()-1]))
     result += preferred_separator;
   return result;
 }
bool folder_create (const std::string & folder)
Definition at line 563 of file file_system.cpp.
Referenced by create_library().
 {
 #ifdef MSWINDOWS
   return mkdir(directory.c_str()) == 0;
 #else
   return mkdir(directory.c_str(), 0777) == 0;
 #endif
 }
std::string folder_current (void)
Definition at line 673 of file file_system.cpp.
Referenced by filespec_to_path(), filespec_to_relative_path(), folder_to_path(), and folder_to_relative_path().
 {
   return ".";
 }
std::string folder_current_full (void)
Definition at line 678 of file file_system.cpp.
 {
   // It's not clear from the documentation whether the buffer for a path should be one byte longer
   // than the maximum path length to allow for the null termination, so I have made it so anyway
 #ifdef MSWINDOWS
   char abspath [MAX_PATH+1];
   return std::string(_fullpath(abspath, ".", MAX_PATH+1));
 #else
   char pathname [MAXPATHLEN+1];
   getcwd(pathname,MAXPATHLEN+1);
   return std::string(pathname);
 #endif
 }
bool folder_delete (const std::string & folder, bool recurse = false)
Definition at line 595 of file file_system.cpp.
References create_filespec(), file_delete(), folder_delete(), folder_down(), folder_exists(), folder_files(), and folder_subdirectories().
Referenced by erase_library(), and folder_delete().
 {
   std::string dir = directory;
   if (dir.empty()) dir = ".";
   if (!folder_exists(dir)) return false;
   bool result = true;
   // depth-first traversal ensures that directory contents are deleted before trying to delete the directory itself
   if (recurse)
   {
     std::vector<std::string> subdirectories = folder_subdirectories(dir);
     for (std::vector<std::string>::size_type d = 0; d < subdirectories.size(); ++d)
       if (!folder_delete(folder_down(dir,subdirectories[d]),true))
     result = false;
     std::vector<std::string> files = folder_files(dir);
     for (std::vector<std::string>::size_type f = 0; f < files.size(); ++f)
       if (!file_delete(create_filespec(dir, files[f])))
     result = false;
   }
   if (rmdir(dir.c_str())!=0) result = false;
   return result;
 }
std::string folder_down (const std::string & folder, const std::string & subfolder)
Definition at line 692 of file file_system.cpp.
References file_specification::add_subpath(), file_specification::image(), and file_specification::initialise_folder().
Referenced by rcEngineImpl::analyze(), folder_delete(), and folder_home().
 {
   file_specification spec;
   spec.initialise_folder(directory);
   spec.add_subpath(subdirectory);
   return spec.image();
 }
std::vector<std::string> folder_elements (const std::string & folder)
Definition at line 941 of file file_system.cpp.
References file_specification::drive(), file_specification::initialise_folder(), and file_specification::path().
 {
   file_specification spec;
   spec.initialise_folder(folder);
   std::vector<std::string> result = spec.path();
   if (!spec.drive().empty()) result.insert(result.begin(),spec.drive());
   return result;
 }
bool folder_empty (const std::string & folder)
Definition at line 623 of file file_system.cpp.
References create_filespec().
 {
   std::string dir = directory.empty() ? std::string(".") : directory;
   bool result = true;
 #ifdef MSWINDOWS
   std::string wildcard = create_filespec(dir, "*.*");
   long handle = -1;
   _finddata_t fileinfo;
   for (bool OK = (handle = _findfirst((char*)wildcard.c_str(), &fileinfo)) != -1; OK; OK = (_findnext(handle, &fileinfo)==0))
   {
     std::string strentry = fileinfo.name;
     if (strentry.compare(".")!=0 && strentry.compare("..")!=0)
     {
       result = false;
       break;
     }
   }
   _findclose(handle);
 #else
   DIR* d = opendir(dir.c_str());
   if (d)
   {
     for (dirent* entry = readdir(d); entry; entry = readdir(d))
     {
       std::string strentry = entry->d_name;
       if (strentry.compare(".")!=0 && strentry.compare("..")!=0)
       {
         result = false;
         break;
       }
     }
     closedir(d);
   }
 #endif
   return result;
 }
bool folder_exists (const std::string & folder)
Definition at line 572 of file file_system.cpp.
References is_folder().
Referenced by create_library(), folder_delete(), folder_readable(), folder_rename(), folder_set_current(), and folder_writable().
 {
   return is_folder(directory);
 }
std::vector<std::string> folder_files (const std::string & folder)
Definition at line 715 of file file_system.cpp.
References folder_wildcard().
Referenced by folder_delete().
 {
   return folder_wildcard(directory, "*", false, true);
 }
std::string folder_home (void)
Definition at line 761 of file file_system.cpp.
References folder_down().
 {
   if (getenv("HOME"))
     return std::string(getenv("HOME"));
 #ifdef MSWINDOWS
   if (getenv("HOMEDRIVE") || getenv("HOMEPATH"))
     return std::string(getenv("HOMEDRIVE")) + std::string(getenv("HOMEPATH"));
   return "C:\\";
 #else
   if (getenv("USER"))
     return folder_down("/home", std::string(getenv("USER")));
   if (getenv("USERNAME"))
     return folder_down("/home", std::string(getenv("USERNAME")));
   return "";
 #endif
 }
std::string folder_part (const std::string & filespec)
Definition at line 918 of file file_system.cpp.
References is_separator().
Referenced by rcMovieConverterToQT::createQTMovie(), enclosingDirOk(), file_writable(), filespec_to_path(), filespec_to_relative_path(), install_path(), library_manager::load_mappings(), lookup(), repFile(), library_manager::save_mappings(), and library_manager::set_ini_manager().
 {
   // scan back through filename until a separator is found and remove prefix
   // if there is no separator, remove the whole
   unsigned i = spec.size();
   while (i--)
   {
     if (is_separator(spec[i]))
       return spec.substr(0,i);
   }
   return std::string();
 }
bool folder_readable (const std::string & folder)
Definition at line 577 of file file_system.cpp.
References folder_exists().
 {
   // a folder is readable if it exists and has read access
   std::string dir = directory;
   if (dir.empty()) dir = ".";
   if (!folder_exists(dir)) return false;
   return access(dir.c_str(),R_OK)==0;
 }
bool folder_rename (const std::string & old_directory, const std::string & new_directory)
Definition at line 617 of file file_system.cpp.
References folder_exists().
 {
   if (!folder_exists(old_directory)) return false;
   return rename(old_directory.c_str(), new_directory.c_str())==0;
 }
bool folder_set_current (const std::string & folder)
Definition at line 660 of file file_system.cpp.
References folder_exists().
 {
   if (!folder_exists(folder))
     return false;
 #ifdef MSWINDOWS
   // Windose implementation - this returns non-zero for success
   return (SetCurrentDirectory(folder.c_str()) != 0);
 #else
   // Unix implementation - this returns zero for success
   return (chdir(folder.c_str()) == 0);
 #endif
 }
std::vector<std::string> folder_subdirectories (const std::string & folder)
Definition at line 710 of file file_system.cpp.
References folder_wildcard().
Referenced by folder_delete().
 {
   return folder_wildcard(directory, "*", true, false);
 }
std::string folder_to_path (const std::string & root, const std::string & folder)
Definition at line 830 of file file_system.cpp.
References full_path().
Referenced by filespec_to_path(), folder_to_path(), library_manager::load_mappings(), lm_library::open(), library_manager::open(), library_manager::save_mappings(), and library_manager::set_ini_manager().
 {
   return full_path(path, directory);
 }
std::string folder_to_path (const std::string & folder)
Definition at line 840 of file file_system.cpp.
References folder_current(), and folder_to_path().
 {
   return folder_to_path(folder_current(), folder);
 }
std::string folder_to_relative_path (const std::string & root, const std::string & folder)
Definition at line 850 of file file_system.cpp.
References relative_path().
Referenced by filespec_to_relative_path(), folder_to_relative_path(), lm_library::pretty_print(), and library_manager::save_mappings().
 {
   return relative_path(root, folder);
 }
std::string folder_to_relative_path (const std::string & folder)
Definition at line 860 of file file_system.cpp.
References folder_current(), and folder_to_relative_path().
 {
   return folder_to_relative_path(folder_current(), folder);
 }
std::string folder_up (const std::string & folder, unsigned levels = 1)
Definition at line 700 of file file_system.cpp.
References file_specification::add_subpath(), file_specification::image(), file_specification::initialise_folder(), and file_specification::simplify().
Referenced by rcEngineImpl::analyze().
 {
   file_specification spec;
   spec.initialise_folder(directory);
   for (unsigned i = 0; i < levels; i++)
     spec.add_subpath("..");
   spec.simplify();
   return spec.image();
 }
std::vector<std::string> folder_wildcard (const std::string & folder, const std::string & wildcard, bool subdirs = true, bool files = true)
Definition at line 725 of file file_system.cpp.
References create_filespec(), is_file(), is_folder(), and match_wildcard().
Referenced by folder_all(), folder_files(), folder_subdirectories(), and lm_library::load_type().
 {
   std::string dir = directory.empty() ? std::string(".") : directory;
   std::vector<std::string> results;
 #ifdef MSWINDOWS
   std::string wildcard = create_filespec(dir, wild);
   long handle = -1;
   _finddata_t fileinfo;
   for (bool OK = (handle = _findfirst((char*)wildcard.c_str(), &fileinfo)) != -1; OK; OK = (_findnext(handle, &fileinfo)==0))
   {
     std::string strentry = fileinfo.name;
     if (strentry.compare(".")!=0 && strentry.compare("..")!=0)
       if ((subdirs && (fileinfo.attrib & _A_SUBDIR)) || (files && !(fileinfo.attrib & _A_SUBDIR)))
         results.push_back(strentry);
   }
   _findclose(handle);
 #else
   DIR* d = opendir(dir.c_str());
   if (d)
   {
     for (dirent* entry = readdir(d); entry; entry = readdir(d))
     {
       std::string strentry = entry->d_name;
       if (strentry.compare(".")!=0 && strentry.compare("..")!=0)
       {
         std::string subpath = create_filespec(dir, strentry);
         if (((subdirs && is_folder(subpath)) || (files && is_file(subpath))) && (match_wildcard(wild, strentry)))
           results.push_back(strentry);
       }
     }
     closedir(d);
   }
 #endif
   return results;
 }
bool folder_writable (const std::string & folder)
Definition at line 586 of file file_system.cpp.
References folder_exists().
Referenced by file_writable(), lm_library::os_read_only(), and lm_library::os_writable().
 {
   // a folder is writable if it exists and has write access
   std::string dir = directory;
   if (dir.empty()) dir = ".";
   if (!folder_exists(dir)) return false;
   return access(dir.c_str(),W_OK)==0;
 }
std::string install_path (const std::string & argv0)
Definition at line 1003 of file file_system.cpp.
References folder_part(), and path_lookup().
Referenced by main().
 {
   std::string bin_directory = folder_part(argv0);
   if (bin_directory.empty())
   {
     // do path lookup to find the executable path
     bin_directory = folder_part(path_lookup(argv0));
   }
   return bin_directory;
 }
bool is_file (const std::string & thing)
Definition at line 393 of file file_system.cpp.
References is_separator().
Referenced by file_copy(), file_delete(), file_exists(), file_rename(), file_set_mode(), file_writable(), and folder_wildcard().
 {
   // strip off any trailing separator because that will cause the stat function to fail
   std::string path = thing;
   if (!path.empty() && is_separator(path[path.size()-1]))
     path.erase(path.size()-1,1);
   // now test if this thing exists using the built-in stat function and if so, is it a file
   struct stat buf;
   if (!(stat(path.c_str(), &buf) == 0)) {return false;}
   return (buf.st_mode & S_IFREG) != 0;
 }
bool is_folder (const std::string & thing)
Definition at line 381 of file file_system.cpp.
References is_separator().
Referenced by create_library(), folder_exists(), and folder_wildcard().
 {
   // strip off any trailing separator because that will cause the stat function to fail
   std::string path = thing;
   if (!path.empty() && is_separator(path[path.size()-1]))
     path.erase(path.size()-1,1);
   // now test if this thing exists using the built-in stat function and if so, is it a folder
   struct stat buf;
   if (!(stat(path.c_str(), &buf) == 0)) {return false;}
   return (buf.st_mode & S_IFDIR) != 0;
 }
bool is_full_path (const std::string & path)
Definition at line 781 of file file_system.cpp.
References file_specification::absolute(), and file_specification::initialise_folder().
 {
   file_specification spec;
   spec.initialise_folder(path.empty() ? std::string(".") : path);
   return spec.absolute();
 }
bool is_present (const std::string & thing)
Definition at line 370 of file file_system.cpp.
References is_separator().
Referenced by create_library(), and file_writable().
 {
   // strip off any trailing separator because that will cause the stat function to fail
   std::string path = thing;
   if (!path.empty() && is_separator(path[path.size()-1]))
     path.erase(path.size()-1,1);
   // now test if this thing exists using the built-in stat function
   struct stat buf;
   return stat(path.c_str(), &buf) == 0;
 }
bool is_relative_path (const std::string & path)
Definition at line 788 of file file_system.cpp.
References file_specification::initialise_folder(), and file_specification::relative().
 {
   file_specification spec;
   spec.initialise_folder(path.empty() ? std::string(".") : path);
   return spec.relative();
 }
std::string lookup (const std::string & file, const std::string & path, const std::string & splitter = ":")
Definition at line 970 of file file_system.cpp.
References basename_part(), create_filespec(), extension_part(), file_exists(), folder_part(), lookup(), and split().
Referenced by lookup(), and path_lookup().
 {
   // first chk whether the command is already a path and chk whether it exists
   if (!folder_part(command).empty())
   {
     if (file_exists(command))
       return command;
   }
   else
   {
     // command is just a name - so do path lookup
     std::vector<std::string> paths = split(path, splitter);
     for (unsigned i = 0; i < paths.size(); i++)
     {
       std::string spec = create_filespec(paths[i], command);
       if (file_exists(spec))
       {
         return spec;
       }
     }
   }
 #ifdef MSWINDOWS
   // if there is no extension, try recursing on each possible extension
   // TODO iterate through PATHEXT
   if (extension_part(command).empty())
     return lookup(create_filespec(folder_part(command), basename_part(command), "exe"), path, splitter);
 #endif
   // if path lookup failed, return empty string to indicate error
   return std::string();
 }
bool path_compare (const std::string & l, const std::string & r)
Definition at line 69 of file file_system.cpp.
References lowercase().
Referenced by file_specification::make_relative().
 {
 #ifdef MSWINDOWS
   return lowercase(l) == lowercase(r);
 #else
   return l == r;
 #endif
 }
std::string path_lookup (const std::string & command)
Definition at line 964 of file file_system.cpp.
References lookup(), and PATH_SPLITTER.
Referenced by install_path(), subprocess::spawn(), and async_subprocess::spawn().
 {
   std::string path = std::string(".") + PATH_SPLITTER + getenv("PATH");
   return lookup(command, path);
 }
Variable Documentation
const int all_mask
Definition at line 498 of file file_system.cpp.
const int all_mode
Definition at line 493 of file file_system.cpp.
const int execute_mode
Definition at line 490 of file file_system.cpp.
const int group_mask
Definition at line 495 of file file_system.cpp.
const int non_owner_mask
Definition at line 497 of file file_system.cpp.
const int none_mode
Definition at line 491 of file file_system.cpp.
const int other_mask
Definition at line 496 of file file_system.cpp.
const int owner_mask
Definition at line 494 of file file_system.cpp.
const int read_mode
Definition at line 488 of file file_system.cpp.
const int read_mode_all
Definition at line 499 of file file_system.cpp.
const int read_mode_owner_only
Definition at line 501 of file file_system.cpp.
const int read_write_mode
Definition at line 492 of file file_system.cpp.
const int read_write_mode_owner_only
Definition at line 502 of file file_system.cpp.
const int read_write_mode_owner_read_mode_all
Definition at line 500 of file file_system.cpp.
const int write_mode
Definition at line 489 of file file_system.cpp.