Visible: include/stlplus/inf.hpp File Reference
inf.hpp File Reference
#include "os_fixes.hpp"
#include <string>
#include <stdexcept>
#include "textio.hpp"
#include "string_utilities.hpp"
#include "persistent.hpp"
Classes
class inf
class inf::divide_by_zero
Functions
bool operator== (const inf &, const inf &)
bool operator!= (const inf &, const inf &)
bool operator< (const inf &, const inf &)
bool operator<= (const inf &, const inf &)
bool operator> (const inf &, const inf &)
bool operator>= (const inf &, const inf &)
inf operator~ (const inf &)
inf operator& (const inf &, const inf &)
inf operator| (const inf &, const inf &)
inf operator^ (const inf &, const inf &)
inf operator<< (const inf &, unsigned shift)
inf operator>> (const inf &, unsigned shift)
inf operator- (const inf &)
inf abs (const inf &)
inf operator+ (const inf &, const inf &)
inf operator- (const inf &, const inf &)
inf operator* (const inf &, const inf &)
inf operator/ (const inf &, const inf &) throw (inf::divide_by_zero)
inf operator% (const inf &, const inf &) throw (inf::divide_by_zero)
std::pair< inf, inf > divide (const inf &, const inf &) throw (inf::divide_by_zero)
std::string to_string (const inf &i, unsigned radix, radix_display_t display, unsigned width) throw (std::invalid_argument)
inf to_inf (const std::string &, unsigned radix) throw (std::invalid_argument)
otext & operator<< (otext &, const inf &)
itext & operator>> (itext &, inf &)
void dump (dump_context &str, const inf &data) throw (persistent_dump_failed)
void restore (restore_context &str, inf &data) throw (persistent_restore_failed)
Function Documentation
inf abs (const inf &)
Definition at line 704 of file inf.cpp.
References inf::abs().
Referenced by rcEngineImpl::modelTracker(), rcNearbyint(), rfCubicShiftImage(), rfiCeil(), rfiDiv(), rfRealEq(), rcEngineMoviePlayback::run(), and simage().
 {
   inf result = i;
   result.abs();
   return result;
 }
std::pair<inf,inf> divide (const inf & , const inf &) throw (inf::divide_by_zero)
Definition at line 832 of file inf.cpp.
References inf::abs(), inf::bits(), inf::negate(), inf::negative(), inf::resize(), inf::set(), and to_string().
Referenced by inf::operator%=(), inf::operator/=(), and to_string().
 {
   if(right.zero()) throw inf::divide_by_zero("divide by zero in divide: " + ::to_string(left) + "/" + ::to_string(right));
   inf numerator = left;
   inf denominator = right;
   // make the numerator natural but preserve the sign for later
   bool numerator_negative = numerator.negative();
   numerator.abs();
   // same with the denominator
   bool denominator_negative = denominator.negative();
   denominator.abs();
   // the quotient and remainder will form the result
   // start with the quotiont zero and the remainder equal to the whole of the numerator, then do trial subtraction from this
   inf quotient;
   inf remainder = numerator;
   // there's nothing more to do if the numerator is smaller than the denominator
   // but otherwise do the division
   if (numerator.bits() >= denominator.bits())
   {
     // make the quotient big enough to take the result
     quotient.resize(numerator.bits());
     // start with the numerator shifted to the far left
     unsigned shift = numerator.bits() - denominator.bits();
     denominator <<= shift;
     // do the division by repeated subtraction,
     for (unsigned i = shift+1; i--; )
     {
       if (remainder >= denominator)
       {
         remainder -= denominator;
         quotient.set(i);
       }
       denominator >>= 1;
     }
   }
   // now adjust the signs
   // x/(-y) == (-x)/y == -(x/y)
   if (numerator_negative != denominator_negative)
   {
     quotient.negate();
   }
   // x%(-y) == x%y and (-x)%y == -(x%y)
   if (numerator_negative)
   {
     remainder.negate();
   }
   return std::pair<inf,inf>(quotient,remainder);
 }
void dump (dump_context & str, const inf & data) throw (persistent_dump_failed)
Definition at line 1452 of file inf.cpp.
 {
   data.dump(str);
 }
bool operator!= (const inf & , const inf &)
Definition at line 436 of file inf.cpp.
 {
   return !(l == r);
 }
inf operator% (const inf & , const inf &) throw (inf::divide_by_zero)
Definition at line 825 of file inf.cpp.
 {
   inf result = l;
   result %= r;
   return result;
 }
inf operator& (const inf & , const inf &)
Definition at line 542 of file inf.cpp.
 {
   inf result = l;
   result &= r;
   return result;
 }
inf operator* (const inf & , const inf &)
Definition at line 794 of file inf.cpp.
 {
   inf result = l;
   result *= r;
   return result;
 }
inf operator+ (const inf & , const inf &)
Definition at line 743 of file inf.cpp.
 {
   inf result = l;
   result += r;
   return result;
 }
inf operator- (const inf &)
Definition at line 691 of file inf.cpp.
References inf::negate().
 {
   inf result = r;
   result.negate();
   return result;
 }
inf operator- (const inf & , const inf &)
Definition at line 760 of file inf.cpp.
 {
   inf result = l;
   result -= r;
   return result;
 }
inf operator/ (const inf & , const inf &) throw (inf::divide_by_zero)
Definition at line 811 of file inf.cpp.
 {
   inf result = l;
   result /= r;
   return result;
 }
bool operator< (const inf & , const inf &)
Definition at line 441 of file inf.cpp.
References inf::m_data, maximum(), and inf::negative().
 {
   // This was originally implemented in terms of subtraction. However, it can
   // be simplified since there is no need to calculate the accurate
   // difference, just the direction of the difference. I compare from msB down
   // and as soon as a byte difference is found, that defines the ordering. The
   // problem is that in 2's-complement, all negative values are greater than
   // all natural values if you just do a straight unsigned comparison. I
   // handle this by doing a preliminary test for different signs.
   // For example, a 3-bit signed type has the coding:
   // 000 = 0
   // ...
   // 011 = 3
   // 100 = -4
   // ...
   // 111 = -1
   // So, for natural values, the ordering of the integer values is the ordering of the bit patterns
   // Similarly, for negative values, the ordering of the integer values is the ordering of the bit patterns
   // However, the bit patterns for the negative values are *greater than* the natural values
   // This is a side-effect of the naffness of 2's-complement representation
   // first handle the case of comparing two values with different signs
   bool l_sign = l.negative();
   bool r_sign = r.negative();
   if (l_sign != r_sign)
   {
     // one argument must be negative and the other natural
     // the left is less if it is the negative one
     return l_sign;
   }
   // the arguments are the same sign
   // so the ordering is a simple unsigned byte-by-byte comparison
   // However, this is complicated by the possibility that the values could be different lengths
   byte l_extend = l_sign ? byte(255) : byte (0);
   byte r_extend = r_sign ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(l.m_data.size(),r.m_data.size());
   for (std::string::size_type i = bytes; i--; )
   {
     byte l_byte = (i < l.m_data.size() ? byte(l.m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     if (l_byte != r_byte)
     {
       return l_byte < r_byte;
     }
   }
   // if I get here, the two are equal, so that is not less-than
   return false;
 }
inf operator<< (const inf & , unsigned shift)
Definition at line 636 of file inf.cpp.
 {
   inf result = l;
   result <<= shift;
   return result;
 }
otext& operator<< (otext & , const inf &)
Definition at line 1332 of file inf.cpp.
References otext::integer_display(), otext::integer_radix(), otext::integer_width(), otext::set_error(), textio_format_error, and to_string().
 {
   try
   {
     str << to_string(i, str.integer_radix(), str.integer_display(), str.integer_width());
   }
   catch(const std::invalid_argument)
   {
     str.set_error(textio_format_error);
   }
   return str;
 }
bool operator<= (const inf & , const inf &)
Definition at line 491 of file inf.cpp.
 {
   return !(r < l);
 }
bool operator== (const inf & , const inf &)
Definition at line 418 of file inf.cpp.
References inf::m_data, maximum(), and inf::negative().
 {
   // Two infs are equal if they are numerically equal, even if they are different sizes (i.e. they could be non-reduced values).
   // This makes life a little more complicated than if I could assume that values were reduced.
   // In the first version I defined equality in terms of subtraction but I'd like to use a more direct approach here.
   byte l_extend = l.negative() ? byte(255) : byte (0);
   byte r_extend = r.negative() ? byte(255) : byte (0);
   std::string::size_type bytes = maximum(l.m_data.size(),r.m_data.size());
   for (std::string::size_type i = bytes; i--; )
   {
     byte l_byte = (i < l.m_data.size() ? byte(l.m_data[i]) : l_extend);
     byte r_byte = (i < r.m_data.size() ? byte(r.m_data[i]) : r_extend);
     if (l_byte != r_byte)
       return false;
   }
   return true;
 }
bool operator> (const inf & , const inf &)
Definition at line 496 of file inf.cpp.
 {
   return r < l;
 }
bool operator>= (const inf & , const inf &)
Definition at line 501 of file inf.cpp.
 {
   return !(l < r);
 }
inf operator>> (const inf & , unsigned shift)
Definition at line 672 of file inf.cpp.
 {
   inf result = l;
   result >>= shift;
   return result;
 }
itext& operator>> (itext & , inf &)
Definition at line 1345 of file inf.cpp.
References itext::set_error(), textio_format_error, and to_inf().
 {
   try
   {
     std::string image;
     str >> image;
     i = to_inf(image);
   }
   catch(const std::invalid_argument)
   {
     str.set_error(textio_format_error);
   }
   return str;
 }
inf operator^ (const inf & , const inf &)
Definition at line 594 of file inf.cpp.
 {
   inf result = l;
   result ^= r;
   return result;
 }
inf operator| (const inf & , const inf &)
Definition at line 568 of file inf.cpp.
 {
   inf result = l;
   result |= r;
   return result;
 }
inf operator~ (const inf &)
Definition at line 516 of file inf.cpp.
References inf::invert().
 {
   inf result = r;
   result.invert();
   return result;
 }
void restore (restore_context & str, inf & data) throw (persistent_restore_failed)
Definition at line 1458 of file inf.cpp.
 {
   data.restore(str);
 }
inf to_inf (const std::string & , unsigned radix) throw (std::invalid_argument)
Definition at line 1111 of file inf.cpp.
References DEBUG_ASSERT, inf::negate(), inf::preset(), inf::resize(), to_string(), and to_uint().
Referenced by inf::operator=(), and operator>>().
 {
   if (radix != 0 && (radix < 2 || radix > 36))
     throw std::invalid_argument("invalid radix value " + to_string(radix));
   unsigned i = 0;
   // the radix passed as a parameter is just the default - it can be overridden by either the C prefix or the hash prefix
   // Note: a leading zero is the C-style prefix for octal - I only make this override the default when the default prefix is not specified
   // first chk for a C-style prefix
   bool c_style = false;
   if (i < str.size() && str[i] == '0')
   {
     // binary or hex
     if (i+1 < str.size() && tolower(str[i+1]) == 'x')
     {
       radix = 16;
       i += 2;
       c_style = true;
     }
     else if (i+1 < str.size() && tolower(str[i+1]) == 'b')
     {
       radix = 2;
       i += 2;
       c_style = true;
     }
     else if (radix == 0)
     {
       radix = 8;
       i += 1;
       c_style = true;
     }
   }
   // now chk for a hash-style prefix if a C-style prefix was not found
   if (i == 0)
   {
     // scan for the sequence {digits}#
     bool hash_found = false;
     unsigned j = i;
     for (; j < str.size(); j++)
     {
       if (!isdigit(str[j]))
       {
         if (str[j] == '#')
           hash_found = true;
         break;
       }
     }
     if (hash_found)
     {
       // use the hash prefix to define the radix
       // i points to the start of the radix and j points to the # character
       std::string slice = str.substr(i, j-i);
       radix = to_uint(slice);
       i = j+1;
     }
   }
   if (radix == 0)
     radix = 10;
   if (radix < 2 || radix > 36)
     throw std::invalid_argument("invalid radix value " + to_string(radix));
   inf val;
   if (c_style)
   {
     // the C style formats are bit patterns not integer values - these need to be sign-extended to get the right value
     std::string binary;
     DEBUG_ASSERT(radix == 2 || radix == 8 || radix == 16);
     if (radix == 2)
     {
       for (unsigned j = i; j < str.size(); j++)
       {
         switch(str[j])
         {
         case '0':
           binary += '0';
           break;
         case '1':
           binary += '1';
           break;
         default:
           throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
           break;
         }
       }
     }
     else if (radix == 8)
     {
       for (unsigned j = i; j < str.size(); j++)
       {
         switch(str[j])
         {
         case '0':
           binary += "000";
           break;
         case '1':
           binary += "001";
           break;
         case '2':
           binary += "010";
           break;
         case '3':
           binary += "011";
           break;
         case '4':
           binary += "100";
           break;
         case '5':
           binary += "101";
           break;
         case '6':
           binary += "110";
           break;
         case '7':
           binary += "111";
           break;
         default:
           throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
           break;
         }
       }
     }
     else
     {
       for (unsigned j = i; j < str.size(); j++)
       {
         switch(tolower(str[j]))
         {
         case '0':
           binary += "0000";
           break;
         case '1':
           binary += "0001";
           break;
         case '2':
           binary += "0010";
           break;
         case '3':
           binary += "0011";
           break;
         case '4':
           binary += "0100";
           break;
         case '5':
           binary += "0101";
           break;
         case '6':
           binary += "0110";
           break;
         case '7':
           binary += "0111";
           break;
         case '8':
           binary += "1000";
           break;
         case '9':
           binary += "1001";
           break;
         case 'a':
           binary += "1010";
           break;
         case 'b':
           binary += "1011";
           break;
         case 'c':
           binary += "1100";
           break;
         case 'd':
           binary += "1101";
           break;
         case 'e':
           binary += "1110";
           break;
         case 'f':
           binary += "1111";
           break;
         default:
           throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
           break;
         }
       }
     }
     // now convert the value
     val.resize(binary.size());
     for (unsigned j = 0; j < binary.size(); j++)
     {
       DEBUG_ASSERT(from_char[(unsigned char)binary[j]] != -1);
       val.preset(binary.size() - j - 1, binary[j] == '1');
     }
   }
   else
   {
     // now scan for a sign and find whether this is a negative number
     bool negative = false;
     if (i < str.size())
     {
       switch (str[i])
       {
       case '-':
         negative = true;
         i++;
         break;
       case '+':
         i++;
         break;
       }
     }
     for (; i < str.size(); i++)
     {
       val *= inf(radix);
       int ch = from_char[(unsigned char)str[i]] ;
       if (ch == -1)
       {
         throw std::invalid_argument("invalid character in string " + str + " for radix " + to_string(radix));
       }
       val += inf(ch);
     }
     if (negative)
       val.negate();
   }
   return val;
 }
std::string to_string (const inf & i, unsigned radix, radix_display_t display, unsigned width) throw (std::invalid_argument)
Definition at line 944 of file inf.cpp.
References inf::abs(), DEBUG_ASSERT, divide(), hex(), inf::negative(), radix_c_style, radix_c_style_or_hash, radix_hash_style, radix_hash_style_all, radix_none, to_string(), to_uint(), and inf::zero().
 {
   if (radix < 2 || radix > 36)
     throw std::invalid_argument("invalid radix value " + to_string(radix));
   inf local_i = i;
   // untangle all the options
   bool hashed = false;
   bool binary = false;
   bool octal = false;
   bool hex = false;
   switch(display)
   {
   case radix_none:
     break;
   case radix_hash_style:
     hashed = radix != 10;
     break;
   case radix_hash_style_all:
     hashed = true;
     break;
   case radix_c_style:
     if (radix == 16)
       hex = true;
     else if (radix == 8)
       octal = true;
     else if (radix == 2)
       binary = true;
     break;
   case radix_c_style_or_hash:
     if (radix == 16)
       hex = true;
     else if (radix == 8)
       octal = true;
     else if (radix == 2)
       binary = true;
     else if (radix != 10)
       hashed = true;
     break;
   default:
     throw std::invalid_argument("invalid radix display value");
   }
   // create constants of the same type as the template parameter to avoid type mismatches
   const inf t_zero(0);
   const inf t_radix(radix);
   // the C representations for binary, octal and hex use 2's-complement representation
   // all other represenations use sign-magnitude
   std::string result;
   if (hex || octal || binary)
   {
     // bit-pattern representation
     // this is the binary representation optionally shown in octal or hex
     // first generate the binary by masking the bits
     for (unsigned j = i.bits(); j--; )
       result += (i.bit(j) ? '1' : '0');
     // the result is now the full width of the type - e.g. int will give a 32-bit result
     // now interpret this as either binary, octal or hex and add the prefix
     if (binary)
     {
       // the result is already binary - but the width may be wrong
       // if this is still smaller than the width field, sign extend
       // otherwise trim down to either the width or the smallest string that preserves the value
       while (result.size() < width)
         result.insert((std::string::size_type)0, 1, result[0]);
       while (result.size() > width)
       {
         // do not trim to less than 1 bit (sign only)
         if (result.size() <= 1) break;
         // only trim if it doesn't change the sign and therefore the value
         if (result[0] != result[1]) break;
         result.erase(0,1);
       }
       // add the prefix
       result.insert((std::string::size_type)0, "0b");
     }
     else if (octal)
     {
       // the result is currently binary - but before converting get the width right
       // the width is expressed in octal digits so make the binary 3 times this
       // if this is still smaller than the width field, sign extend
       // otherwise trim down to either the width or the smallest string that preserves the value
       // also ensure that the binary is a multiple of 3 bits to make the conversion to octal easier
       while (result.size() < 3*width)
         result.insert((std::string::size_type)0, 1, result[0]);
       while (result.size() > 3*width)
       {
         // do not trim to less than 2 bits (sign plus 1-bit magnitude)
         if (result.size() <= 2) break;
         // only trim if it doesn't change the sign and therefore the value
         if (result[0] != result[1]) break;
         result.erase(0,1);
       }
       while (result.size() % 3 != 0)
         result.insert((std::string::size_type)0, 1, result[0]);
       // now convert to octal
       std::string octal_result;
       for (unsigned i = 0; i < result.size()/3; i++)
       {
         std::string slice = result.substr(i*3, 3);
         unsigned value = to_uint(slice, 2);
         octal_result += to_char[value];
       }
       result = octal_result;
       // add the prefix
       result.insert((std::string::size_type)0, "0");
     }
     else
     {
       // similar to octal
       while (result.size() < 4*width)
         result.insert((std::string::size_type)0, 1, result[0]);
       while (result.size() > 4*width)
       {
         // do not trim to less than 2 bits (sign plus 1-bit magnitude)
         if (result.size() <= 2) break;
         // only trim if it doesn't change the sign and therefore the value
         if (result[0] != result[1]) break;
         result.erase(0,1);
       }
       while (result.size() % 4 != 0)
         result.insert((std::string::size_type)0, 1, result[0]);
       // now convert to hex
       std::string hex_result;
       for (unsigned i = 0; i < result.size()/4; i++)
       {
         std::string slice = result.substr(i*4, 4);
         unsigned value = to_uint(slice, 2);
         hex_result += to_char[value];
       }
       result = hex_result;
       // add the prefix
       result.insert((std::string::size_type)0, "0x");
     }
   }
   else
   {
     // convert to sign-magnitude
     // the representation is:
     // [radix#][sign]magnitude
     bool negative = local_i.negative();
     local_i.abs();
     // create a representation of the magnitude by successive division
     do
     {
       std::pair<inf,inf> divided = divide(local_i, t_radix);
       unsigned remainder = divided.second.to_unsigned();
       DEBUG_ASSERT(remainder < radix);
       char digit = to_char[remainder];
       result.insert((std::string::size_type)0, 1, digit);
       local_i = divided.first;
     }
     while(!local_i.zero() || result.size() < width);
     // add the prefixes
     // add a sign only for negative values
     if (negative)
       result.insert((std::string::size_type)0, 1, '-');
     // then prefix everything with the radix if the hashed representation was requested
     if (hashed)
       result.insert((std::string::size_type)0, to_string(radix) + "#");
   }
   return result;
 }