Visible: include/stlplus/ini_manager.cpp File Reference
ini_manager.cpp File Reference
#include "ini_manager.hpp"
#include "fileio.hpp"
#include "file_system.hpp"
#include "string_utilities.hpp"
#include "debug.hpp"
#include <algorithm>
#include <ctype.h>
Classes
class ini_entry
class ini_section
class ini_file
Functions
otext & print (otext &str, const ini_manager &manager, unsigned indent)
otext & operator<< (otext &str, const ini_manager &manager)
Function Documentation
otext& operator<< (otext & str, const ini_manager & manager)
Definition at line 944 of file ini_manager.cpp.
References print().
 {
   return print(str, manager);
 }
otext& print (otext & str, const ini_manager & manager, unsigned indent = 0)
Definition at line 931 of file ini_manager.cpp.
References endl(), ini_manager::m_files, print(), print_indent(), and ini_manager::size().
 {
   print_indent(str, indent);
   str << "----------------------------------------" << endl;
   for (unsigned depth = 0; depth < manager.size(); depth++)
   {
     print(str, *manager.m_files[depth], indent);
     print_indent(str, indent);
     str << "----------------------------------------" << endl;
   }
   return str;
 }