Visible: include/stlplus/library_manager.hpp File Reference
library_manager.hpp File Reference
#include "os_fixes.hpp"
#include "smart_ptr.hpp"
#include "textio.hpp"
#include "persistent.hpp"
#include "ini_manager.hpp"
#include <string>
#include <vector>
#include <list>
#include <map>
#include <time.h>
Classes
class lm_unit_name
class lm_file_dependency
class lm_unit_dependency
class lm_dependencies
class lm_unit
struct lm_callback_entry
class lm_library
class library_manager
Typedefs
typedef smart_ptr_nocopy< lm_unit > lm_unit_ptr
typedef lm_unit *(* lm_create_callback)(const lm_unit_name &unit_name, lm_library *parent_library, void *type_data)
typedef std::map< std::string,
lm_callback_entry > lm_callback_map
typedef std::pair< bool, unsigned > lm_tidy_result
Functions
void dump (dump_context &context, const lm_unit_name &name) throw (persistent_dump_failed)
void restore (restore_context &context, lm_unit_name &name) throw (persistent_restore_failed)
std::string to_string (const lm_unit_name &name)
otext & print (otext &, const lm_unit_name &)
otext & operator<< (otext &, const lm_unit_name &)
bool operator== (const lm_unit_name &l, const lm_unit_name &r)
bool operator< (const lm_unit_name &l, const lm_unit_name &r)
void dump (dump_context &context, const lm_file_dependency &) throw (persistent_dump_failed)
void restore (restore_context &context, lm_file_dependency &) throw (persistent_restore_failed)
otext & print (otext &, const lm_file_dependency &)
otext & print (otext &, const lm_file_dependency &, unsigned indent)
otext & operator<< (otext &, const lm_file_dependency &)
void dump (dump_context &context, const lm_unit_dependency &) throw (persistent_dump_failed)
void restore (restore_context &context, lm_unit_dependency &) throw (persistent_restore_failed)
otext & print (otext &, const lm_unit_dependency &)
otext & print (otext &, const lm_unit_dependency &, unsigned indent)
otext & operator<< (otext &, const lm_unit_dependency &)
void dump (dump_context &context, const lm_dependencies &) throw (persistent_dump_failed)
void restore (restore_context &context, lm_dependencies &) throw (persistent_restore_failed)
otext & print (otext &, const lm_dependencies &, unsigned indent)
otext & operator<< (otext &, const lm_dependencies &)
otext & print (otext &str, const lm_unit &u)
otext & print_long (otext &str, const lm_unit &u, unsigned indent)
otext & operator<< (otext &str, const lm_unit &u)
otext & print (otext &str, const lm_library &lib, unsigned indent)
otext & print_long (otext &str, const lm_library &lib, unsigned indent)
otext & operator<< (otext &str, const lm_library &lib)
otext & print (otext &str, const library_manager &manager, unsigned indent)
otext & print_long (otext &str, const library_manager &manager, unsigned indent)
otext & operator<< (otext &str, const library_manager &libraries)
Typedef Documentation
typedef std::map<std::string,lm_callback_entry> lm_callback_map
Definition at line 391 of file library_manager.hpp.
typedef lm_unit*(* lm_create_callback)(const lm_unit_name &unit_name, lm_library *parent_library, void *type_data)
Definition at line 377 of file library_manager.hpp.
typedef std::pair<bool,unsigned> lm_tidy_result
Definition at line 393 of file library_manager.hpp.
typedef smart_ptr_nocopy<lm_unit> lm_unit_ptr
Definition at line 376 of file library_manager.hpp.
Function Documentation
void dump (dump_context & context, const lm_unit_name & name) throw (persistent_dump_failed)
Definition at line 208 of file library_manager.cpp.
References dump().
 {
   dump(context, name.m_name);
   dump(context, name.m_type);
 }
void dump (dump_context & context, const lm_file_dependency &) throw (persistent_dump_failed)
Definition at line 301 of file library_manager.cpp.
References dump().
 {
   dump(context, dependency.m_path);
   dump(context, dependency.m_line);
   dump(context, dependency.m_column);
 }
void dump (dump_context & context, const lm_unit_dependency &) throw (persistent_dump_failed)
Definition at line 389 of file library_manager.cpp.
References dump().
 {
   dump(context, dependency.m_library);
   dump(context, dependency.m_name);
 }
void dump (dump_context & context, const lm_dependencies &) throw (persistent_dump_failed)
Definition at line 497 of file library_manager.cpp.
References dump_smart_ptr(), and dump_vector().
 {
   dump_smart_ptr(context, dependencies.m_source);
   dump_vector(context, dependencies.m_files);
   dump_vector(context, dependencies.m_units);
 }
bool operator< (const lm_unit_name & l, const lm_unit_name & r)
Definition at line 240 of file library_manager.cpp.
References lm_unit_name::m_name, and lm_unit_name::m_type.
 {
   // sort by name then type
   return (l.m_name != r.m_name) ? l.m_name < r.m_name : l.m_type < r.m_type;
 }
otext& operator<< (otext & , const lm_unit_name &)
Definition at line 230 of file library_manager.cpp.
References print().
 {
   return print(str, name);
 }
otext& operator<< (otext & , const lm_file_dependency &)
Definition at line 330 of file library_manager.cpp.
References print().
 {
   return print(str, dependency);
 }
otext& operator<< (otext & , const lm_unit_dependency &)
Definition at line 413 of file library_manager.cpp.
References print().
 {
   return print(str, dependency);
 }
otext& operator<< (otext & , const lm_dependencies &)
Definition at line 519 of file library_manager.cpp.
References print().
 {
   return print(str, dependencies, 0);
 }
otext& operator<< (otext & str, const lm_unit & u)
Definition at line 827 of file library_manager.cpp.
References lm_unit::print.
 {
   return u.print(str);
 }
otext& operator<< (otext & str, const lm_library & lib)
Definition at line 1485 of file library_manager.cpp.
References print().
 {
   return print(str,lib);
 }
otext& operator<< (otext & str, const library_manager & libraries)
Definition at line 2418 of file library_manager.cpp.
References library_manager::print().
 {
   return manager.print(str);
 }
bool operator== (const lm_unit_name & l, const lm_unit_name & r)
Definition at line 235 of file library_manager.cpp.
References lm_unit_name::m_name, and lm_unit_name::m_type.
 {
   return l.m_name == r.m_name && l.m_type == r.m_type;
 }
otext& print (otext & , const lm_unit_name &)
Definition at line 225 of file library_manager.cpp.
References print(), and to_string().
 {
   return print(str, to_string(name));
 }
otext& print (otext & , const lm_file_dependency &)
Definition at line 315 of file library_manager.cpp.
References lm_file_dependency::m_column, lm_file_dependency::m_line, and lm_file_dependency::m_path.
 {
   str << "file: " << dependency.m_path;
   if (dependency.m_line != 0)
     str << ":" << dependency.m_line << ":" << dependency.m_column;
   return str;
 }
otext& print (otext & , const lm_file_dependency & , unsigned indent)
Definition at line 323 of file library_manager.cpp.
References endl(), print(), and print_indent().
 {
   print_indent(str, indent);
   print(str, dependency);
   return str << endl;
 }
otext& print (otext & , const lm_unit_dependency &)
Definition at line 401 of file library_manager.cpp.
References lm_unit_dependency::m_library, and lm_unit_dependency::m_name.
 {
   return str << "unit: " << dependency.m_library << "." << dependency.m_name;
 }
otext& print (otext & , const lm_unit_dependency & , unsigned indent)
Definition at line 406 of file library_manager.cpp.
References endl(), print(), and print_indent().
 {
   print_indent(str, indent);
   print(str, dependency);
   return str << endl;
 }
otext& print (otext & , const lm_dependencies & , unsigned indent)
Definition at line 511 of file library_manager.cpp.
References endl(), lm_dependencies::m_files, lm_dependencies::m_source, lm_dependencies::m_units, print_indent(), print_smart_ptr(), and print_vector().
 {
   print_indent(str, indent); str << "source file: "; print_smart_ptr(str, dependencies.m_source, "<null>"); str << endl;
   print_vector(str, dependencies.m_files, indent);
   print_vector(str, dependencies.m_units, indent);
   return str;
 }
otext& print (otext & str, const lm_unit & u)
Definition at line 817 of file library_manager.cpp.
References lm_unit::print.
 {
   return u.print(str);
 }
otext& print (otext & str, const lm_library & lib, unsigned indent)
Definition at line 1475 of file library_manager.cpp.
References lm_library::print().
 {
   return lib.print(str, indent);
 }
otext& print (otext & str, const library_manager & manager, unsigned indent)
Definition at line 2408 of file library_manager.cpp.
References library_manager::print().
 {
   return manager.print(str, indent);
 }
otext& print_long (otext & str, const lm_unit & u, unsigned indent)
Definition at line 822 of file library_manager.cpp.
References lm_unit::print_long.
 {
   return u.print_long(str, indent);
 }
otext& print_long (otext & str, const lm_library & lib, unsigned indent)
Definition at line 1480 of file library_manager.cpp.
References lm_library::print_long().
 {
   return lib.print_long(str, indent);
 }
otext& print_long (otext & str, const library_manager & manager, unsigned indent)
Definition at line 2413 of file library_manager.cpp.
References library_manager::print_long().
 {
   return manager.print_long(str, indent);
 }
void restore (restore_context & context, lm_unit_name & name) throw (persistent_restore_failed)
Definition at line 214 of file library_manager.cpp.
References restore().
 {
   restore(context, name.m_name);
   restore(context, name.m_type);
 }
void restore (restore_context & context, lm_file_dependency &) throw (persistent_restore_failed)
Definition at line 308 of file library_manager.cpp.
References restore().
 {
   restore(context, dependency.m_path);
   restore(context, dependency.m_line);
   restore(context, dependency.m_column);
 }
void restore (restore_context & context, lm_unit_dependency &) throw (persistent_restore_failed)
Definition at line 395 of file library_manager.cpp.
References restore().
 {
   restore(context, dependency.m_library);
   restore(context, dependency.m_name);
 }
void restore (restore_context & context, lm_dependencies &) throw (persistent_restore_failed)
Definition at line 504 of file library_manager.cpp.
References restore_smart_ptr(), and restore_vector().
 {
   restore_smart_ptr(context, dependencies.m_source);
   restore_vector(context, dependencies.m_files);
   restore_vector(context, dependencies.m_units);
 }
std::string to_string (const lm_unit_name & name)
Definition at line 220 of file library_manager.cpp.
References lm_unit_name::m_name, and lm_unit_name::m_type.
 {
   return name.m_name + ":" + name.m_type;
 }