Visible: include/stlplus/library_manager.cpp File Reference
library_manager.cpp File Reference
#include "os_fixes.hpp"
#include "library_manager.hpp"
#include "file_system.hpp"
#include "fileio.hpp"
#include "debug.hpp"
#include "persistent.hpp"
#include "string_utilities.hpp"
#include <algorithm>
Functions
static bool read_context (const std::string &path, const std::string &owner, std::string &name, bool &writable)
static bool write_context (const std::string &path, const std::string &owner, const std::string &name, bool writable)
static bool create_library (const std::string &path, const std::string &owner, const std::string &name, bool writable)
static bool erase_library (const std::string &path, const std::string &owner)
static lm_dependencies & out_of_date_chk (std::map< std::pair< std::string, lm_unit_name >, lm_dependencies > &visited, const library_manager *manager, const std::string &library, const lm_unit_name &name)
void dump (dump_context &context, const lm_unit_name &name) throw (persistent_dump_failed)
void restore (restore_context &context, lm_unit_name &name) throw (persistent_restore_failed)
std::string to_string (const lm_unit_name &name)
otext & print (otext &str, const lm_unit_name &name)
otext & operator<< (otext &str, const lm_unit_name &name)
bool operator== (const lm_unit_name &l, const lm_unit_name &r)
bool operator< (const lm_unit_name &l, const lm_unit_name &r)
void dump (dump_context &context, const lm_file_dependency &dependency) throw (persistent_dump_failed)
void restore (restore_context &context, lm_file_dependency &dependency) throw (persistent_restore_failed)
otext & print (otext &str, const lm_file_dependency &dependency)
otext & print (otext &str, const lm_file_dependency &dependency, unsigned indent)
otext & operator<< (otext &str, const lm_file_dependency &dependency)
void dump (dump_context &context, const lm_unit_dependency &dependency) throw (persistent_dump_failed)
void restore (restore_context &context, lm_unit_dependency &dependency) throw (persistent_restore_failed)
otext & print (otext &str, const lm_unit_dependency &dependency)
otext & print (otext &str, const lm_unit_dependency &dependency, unsigned indent)
otext & operator<< (otext &str, const lm_unit_dependency &dependency)
void dump (dump_context &context, const lm_dependencies &dependencies) throw (persistent_dump_failed)
void restore (restore_context &context, lm_dependencies &dependencies) throw (persistent_restore_failed)
otext & print (otext &str, const lm_dependencies &dependencies, unsigned indent)
otext & operator<< (otext &str, const lm_dependencies &dependencies)
otext & print (otext &str, const lm_unit &u)
otext & print_long (otext &str, const lm_unit &u, unsigned indent)
otext & operator<< (otext &str, const lm_unit &u)
otext & print (otext &str, const lm_library &lib, unsigned indent)
otext & print_long (otext &str, const lm_library &lib, unsigned indent)
otext & operator<< (otext &str, const lm_library &lib)
otext & print (otext &str, const library_manager &manager, unsigned indent)
otext & print_long (otext &str, const library_manager &manager, unsigned indent)
otext & operator<< (otext &str, const library_manager &manager)
Variables
static const char * LibraryNameExtension = "lmn"
static const char * HeaderExtension = "lmh"
Function Documentation
static bool create_library (const std::string & path, const std::string & owner, const std::string & name, bool writable) static
Definition at line 53 of file library_manager.cpp.
References create_filespec(), folder_create(), folder_exists(), is_folder(), is_present(), LibraryNameExtension, and write_context().
Referenced by lm_library::create(), and library_manager::create().
 {
   std::string spec = create_filespec(path, owner, LibraryNameExtension);
   if (is_present(path) && !is_folder(path)) return false;
   if (!folder_exists(path) && !folder_create(path)) return false;
   return write_context(path, owner, name, writable);
 }
void dump (dump_context & context, const lm_unit_name & name) throw (persistent_dump_failed)
Definition at line 208 of file library_manager.cpp.
References dump().
 {
   dump(context, name.m_name);
   dump(context, name.m_type);
 }
void dump (dump_context & context, const lm_file_dependency & dependency) throw (persistent_dump_failed)
Definition at line 301 of file library_manager.cpp.
References dump().
 {
   dump(context, dependency.m_path);
   dump(context, dependency.m_line);
   dump(context, dependency.m_column);
 }
void dump (dump_context & context, const lm_unit_dependency & dependency) throw (persistent_dump_failed)
Definition at line 389 of file library_manager.cpp.
References dump().
 {
   dump(context, dependency.m_library);
   dump(context, dependency.m_name);
 }
void dump (dump_context & context, const lm_dependencies & dependencies) throw (persistent_dump_failed)
Definition at line 497 of file library_manager.cpp.
References dump_smart_ptr(), and dump_vector().
 {
   dump_smart_ptr(context, dependencies.m_source);
   dump_vector(context, dependencies.m_files);
   dump_vector(context, dependencies.m_units);
 }
static bool erase_library (const std::string & path, const std::string & owner) static
Definition at line 61 of file library_manager.cpp.
References create_filespec(), file_exists(), folder_delete(), and LibraryNameExtension.
Referenced by lm_library::erase().
 {
   // chk that it is a library before deleting it!
   std::string spec = create_filespec(path, owner, LibraryNameExtension);
   if (!file_exists(spec)) return false;
   return folder_delete(path, true);
 }
bool operator< (const lm_unit_name & l, const lm_unit_name & r)
Definition at line 240 of file library_manager.cpp.
References lm_unit_name::m_name, and lm_unit_name::m_type.
 {
   // sort by name then type
   return (l.m_name != r.m_name) ? l.m_name < r.m_name : l.m_type < r.m_type;
 }
otext& operator<< (otext & str, const lm_unit_name & name)
Definition at line 230 of file library_manager.cpp.
References print().
 {
   return print(str, name);
 }
otext& operator<< (otext & str, const lm_file_dependency & dependency)
Definition at line 330 of file library_manager.cpp.
References print().
 {
   return print(str, dependency);
 }
otext& operator<< (otext & str, const lm_unit_dependency & dependency)
Definition at line 413 of file library_manager.cpp.
References print().
 {
   return print(str, dependency);
 }
otext& operator<< (otext & str, const lm_dependencies & dependencies)
Definition at line 519 of file library_manager.cpp.
References print().
 {
   return print(str, dependencies, 0);
 }
otext& operator<< (otext & str, const lm_unit & u)
Definition at line 827 of file library_manager.cpp.
References lm_unit::print.
 {
   return u.print(str);
 }
otext& operator<< (otext & str, const lm_library & lib)
Definition at line 1485 of file library_manager.cpp.
References print().
 {
   return print(str,lib);
 }
otext& operator<< (otext & str, const library_manager & manager)
Definition at line 2418 of file library_manager.cpp.
References library_manager::print().
 {
   return manager.print(str);
 }
bool operator== (const lm_unit_name & l, const lm_unit_name & r)
Definition at line 235 of file library_manager.cpp.
References lm_unit_name::m_name, and lm_unit_name::m_type.
 {
   return l.m_name == r.m_name && l.m_type == r.m_type;
 }
static lm_dependencies& out_of_date_chk (std::map< std::pair< std::string, lm_unit_name >, lm_dependencies > & visited, const library_manager * manager, const std::string & library, const lm_unit_name & name) static
Definition at line 71 of file library_manager.cpp.
References lm_dependencies::empty(), file_modified(), library_manager::find(), lm_unit_dependency::library(), lm_library::modified(), lm_file_dependency::path_full(), lm_dependencies::unit_add(), and lm_unit_dependency::unit_name().
Referenced by library_manager::out_of_date_reason().
 {
   // the visited field contains an entry if a unit has been visited - it also contains the reason for out-of-date-ness
   // this is initially set empty (up to date) since the unit has to be added before it is chked just in case there is a recursive loop
   // the dependencies field is filled in if the unit is subsequently found to be out of date
   std::pair<std::string,lm_unit_name> full_name = std::make_pair(library,name);
   // first chk whether this unit has already been visited - this should in
   // principle never happen because the same test is performed before trying
   // to recursion, so consider this to be paranoid-mode programming
   std::map<std::pair<std::string,lm_unit_name>,lm_dependencies>::iterator found = visited.find(full_name);
   if (found != visited.end())
     return found->second;
   // now add this unit to prevent recursion loops later. This entry is added
   // to when out-of-date dependencies are found and is also the return value
   // of the function
   visited[full_name] = lm_dependencies();
   // now find the unit
   const lm_unit_ptr unit = manager->find(library,name);
   if (!unit)
   {
     // if a unit is missing it fails with a dependency on itself - this is a
     // bit of a work-around, but this again is paranoid-mode programming since
     // the calling function (this function calling itself recursively) should
     // chk the unit's existence before recursing
     visited[full_name].unit_add(lm_unit_dependency(library,name));
   }
   else
   {
     // we're onto the real chks now - first get the datestamp of this unit:
     // all dependencies must be older than this
     time_t unit_modified = unit->modified();
     // chk dependency on source file if there is one
     if (unit->source_file_present())
     {
       std::string source_file = unit->source_file().path_full(unit->library_path());
       time_t source_modified = file_modified(source_file);
       if (source_modified == 0 || source_modified > unit_modified)
       {
         visited[full_name].set_source_file(unit->source_file());
       }
     }
     // now chk the other file dependencies
     for (unsigned i = 0; i < unit->file_size(); i++)
     {
       // a file dependency is a dependency on a file outside of the library system
       const lm_file_dependency& dependency = unit->file_dependency(i);
       std::string file_full = dependency.path_full(unit->library_path());
       time_t source_modified = file_modified(file_full);
       if (source_modified == 0 || source_modified > unit_modified)
       {
         visited[full_name].file_add(dependency);
       }
     }
     // now chk and recurse on unit dependencies
     for (unsigned j = 0; j < unit->unit_size(); j++)
     {
       const lm_unit_dependency& dependency = unit->unit_dependency(j);
       std::pair<std::string,lm_unit_name> other_name = std::make_pair(dependency.library(), dependency.unit_name());
       // perform the datestamp chking at this level and only recurse if this does not detect an error
       const lm_unit_ptr other_unit = manager->find(other_name.first, other_name.second);
       if (!other_unit)
       {
         visited[full_name].unit_add(dependency);
       }
       else
       {
         time_t other_modified = other_unit->modified();
         if (other_modified == 0 || other_modified > unit_modified)
         {
           visited[full_name].unit_add(dependency);
         }
         else
         {
           // prevent recursion before doing it
           std::map<std::pair<std::string,lm_unit_name>,lm_dependencies>::iterator other_found = visited.find(other_name);
           if (other_found != visited.end())
           {
             // if the unit was found to be out of date on the previous visit, add it to the failed dependencies
             if (!other_found->second.empty())
             {
               visited[full_name].unit_add(dependency);
             }
           }
           else
           {
             // the unit hasn't been visited before, so recurse on it now
             lm_dependencies other_dependencies = out_of_date_chk(visited, manager, other_name.first, other_name.second);
             if (!other_dependencies.empty())
             {
               visited[full_name].unit_add(dependency);
             }
           }
         }
       }
     }
   }
   return visited[full_name];
 }
otext& print (otext & str, const lm_unit_name & name)
Definition at line 225 of file library_manager.cpp.
References print(), and to_string().
 {
   return print(str, to_string(name));
 }
otext& print (otext & str, const lm_file_dependency & dependency)
Definition at line 315 of file library_manager.cpp.
References lm_file_dependency::m_column, lm_file_dependency::m_line, and lm_file_dependency::m_path.
 {
   str << "file: " << dependency.m_path;
   if (dependency.m_line != 0)
     str << ":" << dependency.m_line << ":" << dependency.m_column;
   return str;
 }
otext& print (otext & str, const lm_file_dependency & dependency, unsigned indent)
Definition at line 323 of file library_manager.cpp.
References endl(), print(), and print_indent().
 {
   print_indent(str, indent);
   print(str, dependency);
   return str << endl;
 }
otext& print (otext & str, const lm_unit_dependency & dependency)
Definition at line 401 of file library_manager.cpp.
References lm_unit_dependency::m_library, and lm_unit_dependency::m_name.
 {
   return str << "unit: " << dependency.m_library << "." << dependency.m_name;
 }
otext& print (otext & str, const lm_unit_dependency & dependency, unsigned indent)
Definition at line 406 of file library_manager.cpp.
References endl(), print(), and print_indent().
 {
   print_indent(str, indent);
   print(str, dependency);
   return str << endl;
 }
otext& print (otext & str, const lm_dependencies & dependencies, unsigned indent = 0)
Definition at line 511 of file library_manager.cpp.
References endl(), lm_dependencies::m_files, lm_dependencies::m_source, lm_dependencies::m_units, print_indent(), print_smart_ptr(), and print_vector().
 {
   print_indent(str, indent); str << "source file: "; print_smart_ptr(str, dependencies.m_source, "<null>"); str << endl;
   print_vector(str, dependencies.m_files, indent);
   print_vector(str, dependencies.m_units, indent);
   return str;
 }
otext& print (otext & str, const lm_unit & u)
Definition at line 817 of file library_manager.cpp.
References lm_unit::print.
 {
   return u.print(str);
 }
otext& print (otext & str, const lm_library & lib, unsigned indent = 0)
Definition at line 1475 of file library_manager.cpp.
References lm_library::print().
 {
   return lib.print(str, indent);
 }
otext& print (otext & str, const library_manager & manager, unsigned indent = 0)
Definition at line 2408 of file library_manager.cpp.
References library_manager::print().
 {
   return manager.print(str, indent);
 }
otext& print_long (otext & str, const lm_unit & u, unsigned indent)
Definition at line 822 of file library_manager.cpp.
References lm_unit::print_long.
 {
   return u.print_long(str, indent);
 }
otext& print_long (otext & str, const lm_library & lib, unsigned indent = 0)
Definition at line 1480 of file library_manager.cpp.
References lm_library::print_long().
 {
   return lib.print_long(str, indent);
 }
otext& print_long (otext & str, const library_manager & manager, unsigned indent = 0)
Definition at line 2413 of file library_manager.cpp.
References library_manager::print_long().
 {
   return manager.print_long(str, indent);
 }
static bool read_context (const std::string & path, const std::string & owner, std::string & name, bool & writable) static
Definition at line 30 of file library_manager.cpp.
References create_filespec(), file_exists(), LibraryNameExtension, and restore().
Referenced by library_manager::library_name(), lm_library::open(), library_manager::open(), and lm_library::set_read_write().
 {
   std::string spec = create_filespec(path, owner, LibraryNameExtension);
   name = "";
   writable = false;
   if (!file_exists(spec)) return false;
   iftext input(spec);
   restore_context context(input);
   restore(context, name);
   restore(context, writable);
   return true;
 }
void restore (restore_context & context, lm_unit_name & name) throw (persistent_restore_failed)
Definition at line 214 of file library_manager.cpp.
References restore().
 {
   restore(context, name.m_name);
   restore(context, name.m_type);
 }
void restore (restore_context & context, lm_file_dependency & dependency) throw (persistent_restore_failed)
Definition at line 308 of file library_manager.cpp.
References restore().
 {
   restore(context, dependency.m_path);
   restore(context, dependency.m_line);
   restore(context, dependency.m_column);
 }
void restore (restore_context & context, lm_unit_dependency & dependency) throw (persistent_restore_failed)
Definition at line 395 of file library_manager.cpp.
References restore().
 {
   restore(context, dependency.m_library);
   restore(context, dependency.m_name);
 }
void restore (restore_context & context, lm_dependencies & dependencies) throw (persistent_restore_failed)
Definition at line 504 of file library_manager.cpp.
References restore_smart_ptr(), and restore_vector().
 {
   restore_smart_ptr(context, dependencies.m_source);
   restore_vector(context, dependencies.m_files);
   restore_vector(context, dependencies.m_units);
 }
std::string to_string (const lm_unit_name & name)
Definition at line 220 of file library_manager.cpp.
References lm_unit_name::m_name, and lm_unit_name::m_type.
 {
   return name.m_name + ":" + name.m_type;
 }
static bool write_context (const std::string & path, const std::string & owner, const std::string & name, bool writable) static
Definition at line 43 of file library_manager.cpp.
References create_filespec(), dump(), LibraryNameExtension, and output().
Referenced by create_library(), and lm_library::set_read_write().
 {
   std::string spec = create_filespec(path, owner, LibraryNameExtension);
   oftext output(spec);
   dump_context context(output);
   dump(context, name);
   dump(context,writable);
   return true;
 }
Variable Documentation
const char* HeaderExtension = "lmh" static
Definition at line 20 of file library_manager.cpp.
Referenced by lm_unit::header_filename().
const char* LibraryNameExtension = "lmn" static
Definition at line 19 of file library_manager.cpp.
Referenced by create_library(), erase_library(), library_manager::is_library(), read_context(), and write_context().