Visible: include/util/linlsq.h File Reference
linlsq.h File Reference
#include <rc_vector2d.h>
#include <vector>
Classes
class LLSQ
Functions
template<typename T >
T MedianOfCircularValues (T modulus, std::vector< T > *v)
Function Documentation
template<typename T > T MedianOfCircularValues (T modulus, std::vector< T > * v)
Definition at line 98 of file linlsq.h.
References LLSQ::add(), LLSQ::x_variance(), and LLSQ::y_variance().
{
   LLSQ stats;
   T halfrange = static_cast<T>(modulus / 2);
   int num_elements = v->size();
   for (int i = 0; i < num_elements; ++i) {
     stats.add((*v)[i], (*v)[i] + halfrange);
   }
   bool offset_needed = stats.y_variance() < stats.x_variance();
   if (offset_needed) {
     for (int i = 0; i < num_elements; ++i) {
       (*v)[i] += halfrange;
     }
   }
   int median_index = v->choose_nth_item(num_elements / 2);
   if (offset_needed) {
     for (int i = 0; i < num_elements; ++i) {
       (*v)[i] -= halfrange;
     }
   }
   return (*v)[median_index];
 }