Visible: src/visual/code/model.cpp File Reference
model.cpp File Reference
#include "_highgui.h"
#include "cv.h"
#include <cstdio>
#include <cassert>
#include <Carbon/Carbon.h>
#include <CoreFoundation/CoreFoundation.h>
#include <QuickTime/QuickTime.h>
Classes
struct CvCapture_QT_Movie
Movie state structure for QuickTime movies.
struct CvCapture_QT_Cam_barg
struct CvVideoWriter_QT
Typedefs
typedef struct CvCapture_QT_Movie CvCapture_QT_Movie
Movie state structure for QuickTime movies.
typedef struct
CvCapture_QT_Cam_barg CvCapture_QT_Cam
typedef struct CvVideoWriter_QT CvVideoWriter_QT
Functions
static int icvOpenFile_QT_Movie (CvCapture_QT_Movie *capture, const char *filename)
static int icvClose_QT_Movie (CvCapture_QT_Movie *capture)
static double icvGetProperty_QT_Movie (CvCapture_QT_Movie *capture, int property_id)
static int icvSetProperty_QT_Movie (CvCapture_QT_Movie *capture, int property_id, double value)
static int icvGrabFrame_QT_Movie (CvCapture_QT_Movie *capture)
static const void * icvRetrieveFrame_QT_Movie (CvCapture_QT_Movie *capture)
CvCapture * cvCaptureFromFile_QT (const char *filename)
static int icvOpenCamera_QT (CvCapture_QT_Cam *capture, const int index)
static int icvClose_QT_Cam (CvCapture_QT_Cam *capture)
static double icvGetProperty_QT_Cam (CvCapture_QT_Cam *capture, int property_id)
capture properties currently unimplemented for QuickTime camera interface
static int icvSetProperty_QT_Cam (CvCapture_QT_Cam *capture, int property_id, double value)
capture properties currently unimplemented for QuickTime camera interface
static int icvGrabFrame_QT_Cam (CvCapture_QT_Cam *capture)
static const void * icvRetrieveFrame_QT_Cam (CvCapture_QT_Cam *capture)
CvCapture * cvCaptureFromCAM_QT (const int index)
static OSErr icvDataProc_QT_Cam (SGChannel channel, Ptr raw_data, long len, long *, long, TimeValue, short, long refCon)
OSStatus icvEncodedFrameOutputCallback (void *writer, ICMCompressionSessionRef compression_session_ref, OSStatus error, ICMEncodedFrameRef encoded_frame_ref, void *reserved)
void icvSourceTrackingCallback (void *source_tracking_ref_con, ICMSourceTrackingFlags source_tracking_flags, void *source_frame_ref_con, void *reserved)
CV_IMPL CvVideoWriter * cvCreateVideoWriter (const char *filename, int fourcc, double fps, CvSize frame_size, int is_color)
CV_IMPL int cvWriteFrame (CvVideoWriter *writer, const IplImage *image)
CV_IMPL void cvReleaseVideoWriter (CvVideoWriter **writer)
Variables
static int did_enter_movies = 0
static CvCaptureVTable capture_QT_Movie_vtable
static CvCaptureVTable capture_QT_Cam_vtable
static TimeScale const TIME_SCALE = 600
Typedef Documentation
typedef struct CvCapture_QT_Cam_barg CvCapture_QT_Cam
typedef struct CvCapture_QT_Movie CvCapture_QT_Movie
Movie state structure for QuickTime movies.
typedef struct CvVideoWriter_QT CvVideoWriter_QT
Function Documentation
CvCapture* cvCaptureFromCAM_QT (const int index)
Initialize memory structure and call method to open camera
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2006-01-29
Definition at line 618 of file model.cpp.
References capture_QT_Cam_vtable, did_enter_movies, icvOpenCamera_QT(), and CvCapture_QT_Cam_barg::vtable.
  {
        if (! did_enter_movies)
        {
              EnterMovies();
              did_enter_movies = 1;
        }
      CvCapture_QT_Cam * capture = 0;
      if (index >= 0)
      {
          capture = (CvCapture_QT_Cam *) cvAlloc (sizeof (*capture));
          memset (capture, 0, sizeof(*capture));
          capture->vtable = &capture_QT_Cam_vtable;
          if (!icvOpenCamera_QT (capture, index))
              cvReleaseCapture ((CvCapture**) & capture);
      }
      return (CvCapture *) capture;
  }
CvCapture* cvCaptureFromFile_QT (const char * filename)
Definition at line 114 of file model.cpp.
References capture_QT_Movie_vtable, did_enter_movies, icvOpenFile_QT_Movie(), and CvCapture_QT_Movie::vtable.
  {
        static int did_enter_movies = 0;
        if (! did_enter_movies)
        {
              EnterMovies();
              did_enter_movies = 1;
        }
      CvCapture_QT_Movie * capture = 0;
      if (filename)
      {
          capture = (CvCapture_QT_Movie *) cvAlloc (sizeof (*capture));
          memset (capture, 0, sizeof(*capture));
          capture->vtable = &capture_QT_Movie_vtable;
          if (!icvOpenFile_QT_Movie (capture, filename))
              cvReleaseCapture ((CvCapture**) & capture);
      }
      return (CvCapture*)capture;
  }
CV_IMPL CvVideoWriter* cvCreateVideoWriter (const char * filename, int fourcc, double fps, CvSize frame_size, int is_color)
Definition at line 1138 of file model.cpp.
References CvVideoWriter_QT::compression_session_ref, CvVideoWriter_QT::data_handler, did_enter_movies, CvVideoWriter_QT::duration_per_sample, icvEncodedFrameOutputCallback(), CvVideoWriter_QT::movie, NULL, TIME_SCALE, CvVideoWriter_QT::track, and CvVideoWriter_QT::video.
    {
      CV_FUNCNAME( "cvCreateVideoWriter" );
      CvVideoWriter_QT* video_writer =
          static_cast<CvVideoWriter_QT*>( cvAlloc( sizeof( CvVideoWriter_QT ) ) );
      memset( video_writer, 0, sizeof( CvVideoWriter_QT ) );
      Handle data_ref = NULL;
      OSType data_ref_type;
      DataHandler data_handler = NULL;
      Movie movie = NULL;
      ICMCompressionSessionOptionsRef options_ref = NULL;
      ICMCompressionSessionRef compression_session_ref = NULL;
      OSErr err = noErr;
      __BEGIN__
      // validate input arguments
      if ( filename == NULL ) {
          CV_ERROR( CV_StsBadArg, "Video file name must not be NULL" );
      }
      if ( fps <= 0.0 ) {
          CV_ERROR( CV_StsBadArg, "FPS must be larger than 0.0" );
      }
      if ( ( frame_size.width <= 0 ) || ( frame_size.height <= 0 ) ) {
          CV_ERROR( CV_StsBadArg,
              "Frame width and height must be larger than 0" );
      }
      // initialize QuickTime
      if ( !did_enter_movies ) {
          err = EnterMovies();
          if ( err != noErr ) {
              CV_ERROR( CV_StsInternal, "Unable to initialize QuickTime" );
          }
          did_enter_movies = 1;
      }
      // convert the file name into a data reference
      CFStringRef out_path = CFStringCreateWithCString( kCFAllocatorDefault,
          filename, kCFStringEncodingISOLatin1 );
      CV_ASSERT( out_path != nil );
      err = QTNewDataReferenceFromFullPathCFString( out_path, kQTPOSIXPathStyle,
          0, &data_ref, &data_ref_type );
      CFRelease( out_path );
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal,
              "Cannot create data reference from file name" );
      }
      // create a new movie on disk
      err = CreateMovieStorage( data_ref, data_ref_type, 'TVOD',
          smCurrentScript, newMovieActive, &data_handler, &movie );
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal, "Cannot create movie storage" );
      }
      // create a track with video
      Track video_track =
          NewMovieTrack(
              movie,
              FixRatio( frame_size.width, 1 ),
              FixRatio( frame_size.height, 1 ),
              kNoVolume
          );
      err = GetMoviesError();
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal, "Cannot create video track" );
      }
      Media video =
          NewTrackMedia( video_track, VideoMediaType, TIME_SCALE, nil, 0 );
      err = GetMoviesError();
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal, "Cannot create video media" );
      }
      CodecType codecType;
      switch ( fourcc ) {
          case CV_FOURCC( 'D', 'I', 'B', ' ' ):
              codecType = kRawCodecType;
              break;
          default:
              codecType = kRawCodecType;
              break;
      }
      // start a compression session
      err = ICMCompressionSessionOptionsCreate( kCFAllocatorDefault,
          &options_ref );
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal, "Cannot create compression session options" );
      }
      err = ICMCompressionSessionOptionsSetAllowTemporalCompression( options_ref,
          true );
      if ( err != noErr) {
          CV_ERROR( CV_StsInternal, "Cannot enable temporal compression" );
      }
      err = ICMCompressionSessionOptionsSetAllowFrameReordering( options_ref,
          true );
      if ( err != noErr) {
          CV_ERROR( CV_StsInternal, "Cannot enable frame reordering" );
      }
      ICMEncodedFrameOutputRecord encoded_frame_output_record;
      encoded_frame_output_record.encodedFrameOutputCallback =
          icvEncodedFrameOutputCallback;
      encoded_frame_output_record.encodedFrameOutputRefCon =
          static_cast<void*>( video_writer );
      encoded_frame_output_record.frameDataAllocator = NULL;
      err = ICMCompressionSessionCreate( kCFAllocatorDefault, frame_size.width,
          frame_size.height, codecType, TIME_SCALE, options_ref,
          NULL /*source_pixel_buffer_attributes*/, &encoded_frame_output_record,
          &compression_session_ref );
      ICMCompressionSessionOptionsRelease( options_ref );
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal, "Cannot create compression session" );
      }
      err = BeginMediaEdits( video );
      if ( err != noErr ) {
          CV_ERROR( CV_StsInternal, "Cannot begin media edits" );
      }
      // fill in the video writer structure
      video_writer->data_handler = data_handler;
      video_writer->movie = movie;
      video_writer->track = video_track;
      video_writer->video = video;
      video_writer->compression_session_ref = compression_session_ref;
      video_writer->duration_per_sample =
          static_cast<TimeValue>( static_cast<double>( TIME_SCALE ) / fps );
      __END__
      // clean up in case of error (unless error processing mode is
      // CV_ErrModeLeaf)
      if ( err != noErr ) {
          if ( options_ref != NULL ) {
              ICMCompressionSessionOptionsRelease( options_ref );
          }
          if ( compression_session_ref != NULL ) {
              ICMCompressionSessionRelease( compression_session_ref );
          }
          if ( data_handler != NULL ) {
              CloseMovieStorage( data_handler );
          }
          if ( movie != NULL ) {
              DisposeMovie( movie );
          }
          if ( data_ref != NULL ) {
              DeleteMovieStorage( data_ref, data_ref_type );
              DisposeHandle( data_ref );
          }
          cvFree( reinterpret_cast<void**>( &video_writer ) );
          video_writer = NULL;
      }
      return reinterpret_cast<CvVideoWriter*>( video_writer );
  }
CV_IMPL void cvReleaseVideoWriter (CvVideoWriter ** writer)
Definition at line 1363 of file model.cpp.
References CvVideoWriter_QT::compression_session_ref, CvVideoWriter_QT::data_handler, CvVideoWriter_QT::movie, NULL, CvVideoWriter_QT::track, TRUE, and CvVideoWriter_QT::video.
{
      if ( ( writer != NULL ) && ( *writer != NULL ) ) {
          CvVideoWriter_QT* video_writer =
              reinterpret_cast<CvVideoWriter_QT*>( *writer );
          // force compression session to complete encoding of outstanding source
          // frames
          ICMCompressionSessionCompleteFrames(
              video_writer->compression_session_ref, TRUE, 0, 0
          );
          EndMediaEdits( video_writer->video );
          ICMCompressionSessionRelease( video_writer->compression_session_ref );
          InsertMediaIntoTrack(
              video_writer->track,
              0,
              0,
              GetMediaDuration( video_writer->video ),
              FixRatio( 1, 1 )
          );
          UpdateMovieInStorage( video_writer->movie, video_writer->data_handler );
          CloseMovieStorage( video_writer->data_handler );
  /*
          // export to AVI
          Handle data_ref;
          OSType data_ref_type;
          QTNewDataReferenceFromFullPathCFString(
              CFSTR( "/Users/seibert/Desktop/test.avi" ), kQTPOSIXPathStyle, 0,
              &data_ref, &data_ref_type
          );
          ConvertMovieToDataRef( video_writer->movie, NULL, data_ref,
              data_ref_type, kQTFileTypeAVI, 'TVOD', 0, NULL );
          DisposeHandle( data_ref );
  */
          DisposeMovie( video_writer->movie );
          cvFree( reinterpret_cast<void**>( &video_writer ) );
          *writer = NULL;
      }
  }
CV_IMPL int cvWriteFrame (CvVideoWriter * writer, const IplImage * image)
Definition at line 1307 of file model.cpp.
References CvVideoWriter_QT::compression_session_ref, CvVideoWriter_QT::duration_per_sample, icvSourceTrackingCallback(), and NULL.
    {
      CvVideoWriter_QT* video_writer =
          reinterpret_cast<CvVideoWriter_QT*>( writer );
      CVPixelBufferRef pixel_buffer_ref = NULL;
      CVReturn retval =
          CVPixelBufferCreate(
              kCFAllocatorDefault,
              image->width, image->height, k24RGBPixelFormat,
              NULL /* pixel_buffer_attributes */,
              &pixel_buffer_ref
          );
      // convert BGR IPL image to RGB pixel buffer
      IplImage* image_rgb =
          cvCreateImageHeader(
              cvSize( image->width, image->height ),
              IPL_DEPTH_8U,
              3
          );
      retval = CVPixelBufferLockBaseAddress( pixel_buffer_ref, 0 );
      void* base_address = CVPixelBufferGetBaseAddress( pixel_buffer_ref );
      size_t bytes_per_row = CVPixelBufferGetBytesPerRow( pixel_buffer_ref );
      cvSetData( image_rgb, base_address, bytes_per_row );
      cvConvertImage( image, image_rgb, CV_CVTIMG_SWAP_RB );
      retval = CVPixelBufferUnlockBaseAddress( pixel_buffer_ref, 0 );
      cvReleaseImageHeader( &image_rgb );
      ICMSourceTrackingCallbackRecord source_tracking_callback_record;
      source_tracking_callback_record.sourceTrackingCallback =
          icvSourceTrackingCallback;
      source_tracking_callback_record.sourceTrackingRefCon = NULL;
      OSStatus status =
          ICMCompressionSessionEncodeFrame(
              video_writer->compression_session_ref,
              pixel_buffer_ref,
              0,
              video_writer->duration_per_sample,
              kICMValidTime_DisplayDurationIsValid,
              NULL,
              &source_tracking_callback_record,
              static_cast<void*>( &pixel_buffer_ref )
          );
      return 0;
  }
static int icvClose_QT_Cam (CvCapture_QT_Cam * capture) static
Definition at line 1030 of file model.cpp.
References CvCapture_QT_Cam_barg::grabber, CvCapture_QT_Cam_barg::gworld, CvCapture_QT_Cam_barg::image_bgr, CvCapture_QT_Cam_barg::image_rgb, and CvCapture_QT_Cam_barg::sequence.
  {
        OPENCV_ASSERT (capture, "icvClose_QT_Cam", "'capture' is a NULL-pointer");
        OSErr  result = noErr;
        // stop recording
        result = SGStop (capture->grabber);
        OPENCV_ASSERT (result == noErr, "icveClose_QT_Cam", "couldnt stop recording");
        // close sequence grabber component
        result = CloseComponent (capture->grabber);
        OPENCV_ASSERT (result == noErr, "icveClose_QT_Cam", "couldnt close sequence grabber component");
        // end decompression sequence
        CDSequenceEnd (capture->sequence);
        // free memory
        cvReleaseImage (& capture->image_bgr);
        cvReleaseImageHeader (& capture->image_rgb);
        DisposeGWorld (capture->gworld);
        // sucessful
        return 1;
  }
static int icvClose_QT_Movie (CvCapture_QT_Movie * capture) static
dispose of QuickTime Movie and free memory buffers
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2005-11-04
Definition at line 256 of file model.cpp.
References CvCapture_QT_Movie::image_bgr, CvCapture_QT_Movie::image_rgb, CvCapture_QT_Movie::myGWorld, and CvCapture_QT_Movie::myMovie.
  {
        OPENCV_ASSERT (capture,          "icvClose_QT_Movie", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->myMovie, "icvClose_QT_Movie", "invalid Movie handle");
        // deallocate and free resources
        cvReleaseImage       (& capture->image_bgr);
        cvReleaseImageHeader (& capture->image_rgb);
        DisposeGWorld        (capture->myGWorld);
        DisposeMovie         (capture->myMovie);
        // okay, that's it
        return 1;
  }
static OSErr icvDataProc_QT_Cam (SGChannel channel, Ptr raw_data, long len, long * , long , TimeValue , short , long refCon) static
Definition at line 887 of file model.cpp.
References CvCapture_QT_Cam_barg::bounds, CvCapture_QT_Cam_barg::got_frame, CvCapture_QT_Cam_barg::gworld, and CvCapture_QT_Cam_barg::sequence.
Referenced by icvOpenCamera_QT().
  {
        CvCapture_QT_Cam  * capture = (CvCapture_QT_Cam *) refCon;
        CodecFlags          ignore;
        ComponentResult     err     = noErr;
        // we need valid pointers
        OPENCV_ASSERT (capture,          "icvDataProc_QT_Cam", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->gworld,  "icvDataProc_QT_Cam", "'gworld' is a NULL-pointer");
        OPENCV_ASSERT (raw_data,         "icvDataProc_QT_Cam", "'raw_data' is a NULL-pointer");
        // create a decompression sequence the first time
        if (capture->sequence == 0)
        {
              ImageDescriptionHandle   description = (ImageDescriptionHandle) NewHandle(0);
              // we need a decompression sequence that fits the raw data coming from the camera
              err = SGGetChannelSampleDescription (channel, (Handle) description);
              OPENCV_ASSERT (err == noErr, "icvDataProc_QT_Cam", "couldnt get channel sample description");
              err = DecompressSequenceBegin (&capture->sequence, description, capture->gworld, 0, &capture->bounds,
                                               nil, srcCopy, nil, 0, codecNormalQuality, bestSpeedCodec);
              OPENCV_ASSERT (err == noErr, "icvDataProc_QT_Cam", "couldnt begin decompression sequence");
              DisposeHandle ((Handle) description);
        }
        // okay, we have a decompression sequence -> decompress!
        err = DecompressSequenceFrameS (capture->sequence, raw_data, len, 0, &ignore, nil);
        if (err != noErr)
        {
              fprintf (stderr, "icvDataProc_QT_Cam: couldn't decompress frame - %d\n", (int) err);
              return err;
        }
        // check if we dropped a frame
        #ifndef NDEBUG
              if (capture->got_frame)
                    fprintf (stderr, "icvDataProc_QT_Cam: frame was dropped\n");
        #endif
        // everything worked as expected
        capture->got_frame = true;
        return noErr;
  }
OSStatus icvEncodedFrameOutputCallback (void * writer, ICMCompressionSessionRef compression_session_ref, OSStatus error, ICMEncodedFrameRef encoded_frame_ref, void * reserved)
Definition at line 1412 of file model.cpp.
References NULL, and CvVideoWriter_QT::video.
Referenced by cvCreateVideoWriter().
    {
      CvVideoWriter_QT* video_writer = static_cast<CvVideoWriter_QT*>( writer );
      OSStatus err = AddMediaSampleFromEncodedFrame( video_writer->video,
          encoded_frame_ref, NULL );
      return err;
  }
static double icvGetProperty_QT_Cam (CvCapture_QT_Cam * capture, int property_id) static
capture properties currently unimplemented for QuickTime camera interface
Definition at line 643 of file model.cpp.
  {
        assert (0);
        return 0;
  }
static double icvGetProperty_QT_Movie (CvCapture_QT_Movie * capture, int property_id) static
get a capture property
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2005-11-05
Definition at line 277 of file model.cpp.
References CvCapture_QT_Movie::movie_start_time, CvCapture_QT_Movie::myMovie, CvCapture_QT_Movie::next_frame_number, CvCapture_QT_Movie::next_frame_time, CvCapture_QT_Movie::number_of_frames, and CvCapture_QT_Movie::size.
  {
        OPENCV_ASSERT (capture,                        "icvGetProperty_QT_Movie", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->myMovie,               "icvGetProperty_QT_Movie", "invalid Movie handle");
        OPENCV_ASSERT (capture->number_of_frames >  0, "icvGetProperty_QT_Movie", "movie has invalid number of frames");
        OPENCV_ASSERT (capture->movie_start_time >= 0, "icvGetProperty_QT_Movie", "movie has invalid start time");
      // inquire desired property
      switch (property_id)
      {
              case CV_CAP_PROP_POS_FRAMES:
                    return (capture->next_frame_number);
              case CV_CAP_PROP_POS_MSEC:
              case CV_CAP_PROP_POS_AVI_RATIO:
                    {
                          TimeValue   position  = capture->next_frame_time - capture->movie_start_time;
                          if (property_id == CV_CAP_PROP_POS_MSEC)
{
                                TimeScale   timescale = GetMovieTimeScale (capture->myMovie);
                                return (static_cast<double> (position) * 1000.0 / timescale);
                          }
                          else
{
                                TimeValue   duration  = GetMovieDuration  (capture->myMovie);
                                return (static_cast<double> (position) / duration);
                          }
                    }
                    break; // never reached
              case CV_CAP_PROP_FRAME_WIDTH:
                    return static_cast<double> (capture->size.width);
              case CV_CAP_PROP_FRAME_HEIGHT:
                    return static_cast<double> (capture->size.height);
              case CV_CAP_PROP_FPS:
                    {
                          TimeValue   duration  = GetMovieDuration  (capture->myMovie);
                          TimeScale   timescale = GetMovieTimeScale (capture->myMovie);
                          return (capture->number_of_frames / (static_cast<double> (duration) / timescale));
                    }
              case CV_CAP_PROP_FRAME_COUNT:
                    return static_cast<double> (capture->number_of_frames);
              case CV_CAP_PROP_FOURCC:  // not implemented
              case CV_CAP_PROP_FORMAT:  // not implemented
              case CV_CAP_PROP_MODE:    // not implemented
              default:
                    // unhandled or unknown capture property
                    OPENCV_ERROR (CV_StsBadArg, "icvSetProperty_QT_Movie", "unknown or unhandled property_id");
                    return CV_StsBadArg;
      }
      return 0;
  }
static int icvGrabFrame_QT_Cam (CvCapture_QT_Cam * capture) static
Definition at line 1057 of file model.cpp.
References CvCapture_QT_Cam_barg::grabber.
  {
        OPENCV_ASSERT (capture,          "icvGrabFrame_QT_Cam", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->grabber, "icvGrabFrame_QT_Cam", "'grabber' is a NULL-pointer");
        ComponentResult   result = noErr;
        // grab one frame
        result = SGIdle (capture->grabber);
        if (result != noErr)
        {
              fprintf (stderr, "SGIdle failed in icvGrabFrame_QT_Cam with error %d\n", (int) result);
              return 0;
        }
        // successful
        return 1;
  }
static int icvGrabFrame_QT_Movie (CvCapture_QT_Movie * capture) static
the original meaning of this method is to acquire raw frame data for the next video frame but not decompress it. With the QuickTime video reader, this is reduced to advance to the current frame time.
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2005-11-06
Definition at line 454 of file model.cpp.
References CvCapture_QT_Movie::myMovie, CvCapture_QT_Movie::next_frame_number, CvCapture_QT_Movie::next_frame_time, and NULL.
  {
        OPENCV_ASSERT (capture,          "icvGrabFrame_QT_Movie", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->myMovie, "icvGrabFrame_QT_Movie", "invalid Movie handle");
        TimeValue    myCurrTime;
        OSType       myType     = VisualMediaCharacteristic;
        OSErr        myErr      = noErr;
        // jump to current video sample
        SetMovieTimeValue (capture->myMovie, capture->next_frame_time);
        myErr = GetMoviesError();
        if (myErr != noErr)
        {
              fprintf (stderr, "Couldn't SetMovieTimeValue() in icvGrabFrame_QT_Movie.\n");
              return  0;
        }
        // where are we now?
        myCurrTime = GetMovieTime (capture->myMovie, NULL);
        // increment counters
        capture->next_frame_number++;
        GetMovieNextInterestingTime (capture->myMovie, nextTimeStep, 1, & myType, myCurrTime, 1, & capture->next_frame_time, NULL);
        myErr = GetMoviesError();
        if (myErr != noErr)
        {
              fprintf (stderr, "Couldn't GetMovieNextInterestingTime() in icvGrabFrame_QT_Movie.\n");
              return 0;
        }
        // that's it
      return 1;
  }
static int icvOpenCamera_QT (CvCapture_QT_Cam * capture, const int index) static
Definition at line 934 of file model.cpp.
References CvCapture_QT_Cam_barg::bounds, CvCapture_QT_Cam_barg::channel, CvCapture_QT_Cam_barg::grabber, CvCapture_QT_Cam_barg::gworld, icvDataProc_QT_Cam(), CvCapture_QT_Cam_barg::image_bgr, CvCapture_QT_Cam_barg::image_rgb, and CvCapture_QT_Cam_barg::size.
Referenced by cvCaptureFromCAM_QT().
  {
        OPENCV_ASSERT (capture,    "icvOpenCamera_QT", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (index >= 0, "icvOpenCamera_QT", "camera index is negative");
        PixMapHandle  pixmap       = nil;
        OSErr         result       = noErr;
        // open sequence grabber component
        capture->grabber = OpenDefaultComponent (SeqGrabComponentType, 0);
        OPENCV_ASSERT (capture->grabber, "icvOpenCamera_QT", "couldnt create image");
        // initialize sequence grabber component
        result = SGInitialize (capture->grabber);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt initialize sequence grabber");
        result = SGSetDataRef (capture->grabber, 0, 0, seqGrabDontMakeMovie);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set data reference of sequence grabber");
        // set up video channel
        result = SGNewChannel (capture->grabber, VideoMediaType, & (capture->channel));
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt create new video channel");
        // query natural camera resolution -- this will be wrong, but will be an upper
        // bound on the actual resolution -- the actual resolution is set below
        // after starting the frame grabber
        result = SGGetSrcVideoBounds (capture->channel, & (capture->bounds));
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set video channel bounds");
        // create offscreen GWorld
        result = QTNewGWorld (& (capture->gworld), k32ARGBPixelFormat, & (capture->bounds), 0, 0, 0);
        result = SGSetGWorld (capture->grabber, capture->gworld, 0);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set GWorld for sequence grabber");
        result = SGSetChannelBounds (capture->channel, & (capture->bounds));
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set video channel bounds");
        result = SGSetChannelUsage (capture->channel, seqGrabRecord);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set channel usage");
      // start recording so we can size
        result = SGStartRecord (capture->grabber);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt start recording");
        // don't know *actual* resolution until now
        ImageDescriptionHandle imageDesc = (ImageDescriptionHandle)NewHandle(0);
        result = SGGetChannelSampleDescription(capture->channel, (Handle)imageDesc);
        OPENCV_ASSERT( result == noErr, "icvOpenCamera_QT", "couldn't get image size");
        capture->bounds.right = (**imageDesc).width;
        capture->bounds.bottom = (**imageDesc).height;
        DisposeHandle ((Handle) imageDesc);
        // stop grabber so that we can reset the parameters to the right size
        result = SGStop (capture->grabber);
        OPENCV_ASSERT (result == noErr, "icveClose_QT_Cam", "couldnt stop recording");
        // reset GWorld to correct image size
        GWorldPtr tmpgworld;
        result = QTNewGWorld( &tmpgworld, k32ARGBPixelFormat, &(capture->bounds), 0, 0, 0);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt create offscreen GWorld");
        result = SGSetGWorld( capture->grabber, tmpgworld, 0);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set GWorld for sequence grabber");
        DisposeGWorld( capture->gworld );
        capture->gworld = tmpgworld;
        result = SGSetChannelBounds (capture->channel, & (capture->bounds));
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set video channel bounds");
        // allocate images
        capture->size = cvSize (capture->bounds.right - capture->bounds.left, capture->bounds.bottom - capture->bounds.top);
        // build IplImage header that points to the PixMap of the Movie's GWorld.
        // unfortunately, cvCvtColor doesn't know ARGB, the QuickTime pixel format,
        // so we shift the base address by one byte.
        // ATTENTION: don't access the last pixel's alpha entry, it's inexistant
        capture->image_rgb = cvCreateImageHeader (capture->size, IPL_DEPTH_8U, 4);
        OPENCV_ASSERT (capture->image_rgb, "icvOpenCamera_QT", "couldnt create image header");
        pixmap = GetGWorldPixMap (capture->gworld);
        OPENCV_ASSERT (pixmap, "icvOpenCamera_QT", "didn't get GWorld PixMap handle");
        LockPixels (pixmap);
        cvSetData (capture->image_rgb, GetPixBaseAddr (pixmap) + 1, GetPixRowBytes (pixmap));
        // create IplImage that hold correctly formatted result
        capture->image_bgr = cvCreateImage (capture->size, IPL_DEPTH_8U, 3);
        OPENCV_ASSERT (capture->image_bgr, "icvOpenCamera_QT", "couldnt create image");
        // tell the sequence grabber to invoke our data proc
        result = SGSetDataProc (capture->grabber, NewSGDataUPP (icvDataProc_QT_Cam), (long) capture);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt set data proc");
        // start recording
        result = SGStartRecord (capture->grabber);
        OPENCV_ASSERT (result == noErr, "icvOpenCamera_QT", "couldnt start recording");
        return 1;
  }
static int icvOpenFile_QT_Movie (CvCapture_QT_Movie * capture, const char * filename) static
convert full path to CFStringRef and open corresponding Movie. Then step over 'interesting frame times' to count total number of frames for video material with varying frame durations and create offscreen GWorld for rendering the movie frames.
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2005-11-04
Definition at line 150 of file model.cpp.
References CvCapture_QT_Movie::image_bgr, CvCapture_QT_Movie::image_rgb, CvCapture_QT_Movie::movie_start_time, CvCapture_QT_Movie::myGWorld, CvCapture_QT_Movie::myMovie, CvCapture_QT_Movie::next_frame_number, CvCapture_QT_Movie::next_frame_time, NULL, CvCapture_QT_Movie::number_of_frames, and CvCapture_QT_Movie::size.
Referenced by cvCaptureFromFile_QT().
  {
        Rect          myRect;
        short         myResID        = 0;
        Handle        myDataRef      = nil;
        OSType        myDataRefType  = 0;
        OSErr         myErr          = noErr;
        // no old errors please
        ClearMoviesStickyError ();
        // initialize pointers to zero
        capture->myMovie  = 0;
        capture->myGWorld = nil;
        // initialize numbers with invalid values
        capture->next_frame_time   = -1;
        capture->next_frame_number = -1;
        capture->number_of_frames  = -1;
        capture->movie_start_time  = -1;
        capture->size              = cvSize (-1,-1);
        // we would use CFStringCreateWithFileSystemRepresentation (kCFAllocatorDefault, filename) on Mac OS X 10.4
        CFStringRef   inPath = CFStringCreateWithCString (kCFAllocatorDefault, filename, kCFStringEncodingISOLatin1);
        OPENCV_ASSERT ((inPath != nil), "icvOpenFile_QT_Movie", "couldnt create CFString from a string");
        // create the data reference
        myErr = QTNewDataReferenceFromFullPathCFString (inPath, kQTPOSIXPathStyle, 0, & myDataRef, & myDataRefType);
        if (myErr != noErr)
        {
              fprintf (stderr, "Couldn't create QTNewDataReferenceFromFullPathCFString().\n");
              return 0;
        }
        // get the Movie
        myErr = NewMovieFromDataRef(& capture->myMovie, newMovieActive | newMovieAsyncOK /* | newMovieIdleImportOK */,
                                                  & myResID, myDataRef, myDataRefType);
        // dispose of the data reference handle - we no longer need it
        DisposeHandle (myDataRef);
        // if NewMovieFromDataRef failed, we already disposed the DataRef, so just return with an error
        if (myErr != noErr)
        {
              fprintf (stderr, "Couldn't create a NewMovieFromDataRef() - error is %d.\n",  myErr);
              return 0;
        }
        // count the number of video 'frames' in the movie by stepping through all of the
        // video 'interesting times', or in other words, the places where the movie displays
        // a new video sample. The time between these interesting times is not necessarily constant.
        {
              OSType      whichMediaType = VisualMediaCharacteristic;
              TimeValue   theTime        = -1;
              // find out movie start time
              GetMovieNextInterestingTime (capture->myMovie, short (nextTimeMediaSample + nextTimeEdgeOK),
                                           1, & whichMediaType, TimeValue (0), 0, & theTime, NULL);
              if (theTime == -1)
              {
                    fprintf (stderr, "Couldn't inquire first frame time\n");
                    return 0;
              }
              capture->movie_start_time  = theTime;
              capture->next_frame_time   = theTime;
              capture->next_frame_number = 0;
              // count all 'interesting times' of the movie
              capture->number_of_frames  = 0;
              while (theTime >= 0)
              {
                    GetMovieNextInterestingTime (capture->myMovie, short (nextTimeMediaSample),
                                                 1, & whichMediaType, theTime, 0, & theTime, NULL);
                    capture->number_of_frames++;
              }
        }
        // get the bounding rectangle of the movie
        GetMoviesError ();
        GetMovieBox (capture->myMovie, & myRect);
        capture->size = cvSize (myRect.right - myRect.left, myRect.bottom - myRect.top);
        // create gworld for decompressed image
        myErr = QTNewGWorld (& capture->myGWorld, k32ARGBPixelFormat /* k24BGRPixelFormat geht leider nicht */,
                             & myRect, nil, nil, 0);
        OPENCV_ASSERT (myErr == noErr, "icvOpenFile_QT_Movie", "couldnt create QTNewGWorld() for output image");
        SetMovieGWorld (capture->myMovie, capture->myGWorld, nil);
        // build IplImage header that will point to the PixMap of the Movie's GWorld later on
        capture->image_rgb = cvCreateImageHeader (capture->size, IPL_DEPTH_8U, 4);
        // create IplImage that hold correctly formatted result
        capture->image_bgr = cvCreateImage (capture->size, IPL_DEPTH_8U, 3);
        // okay, that's it - should we wait until the Movie is playable?
        return 1;
  }
static const void * icvRetrieveFrame_QT_Cam (CvCapture_QT_Cam * capture) static
Definition at line 1077 of file model.cpp.
References CvCapture_QT_Cam_barg::got_frame, CvCapture_QT_Cam_barg::grabber, CvCapture_QT_Cam_barg::image_bgr, and CvCapture_QT_Cam_barg::image_rgb.
  {
        OPENCV_ASSERT (capture,            "icvRetrieveFrame_QT_Cam", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->image_rgb, "icvRetrieveFrame_QT_Cam", "invalid source image");
        OPENCV_ASSERT (capture->image_bgr, "icvRetrieveFrame_QT_Cam", "invalid destination image");
        OSErr         myErr          = noErr;
        // service active sequence grabbers (= redraw immediately)
        while (! capture->got_frame)
        {
              myErr = SGIdle (capture->grabber);
              if (myErr != noErr)
              {
                    fprintf (stderr, "SGIdle() didn't succeed in icvRetrieveFrame_QT_Cam().\n");
                    return 0;
              }
        }
        // covert RGB of GWorld to BGR
        cvCvtColor (capture->image_rgb, capture->image_bgr, CV_RGBA2BGR);
        // reset grabbing status
        capture->got_frame = false;
      // always return the same image pointer
        return capture->image_bgr;
  }
static const void * icvRetrieveFrame_QT_Movie (CvCapture_QT_Movie * capture) static
render the current frame into an image buffer and convert to OpenCV IplImage buffer layout (BGR sampling)
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2005-11-06
Definition at line 497 of file model.cpp.
References CvCapture_QT_Movie::image_bgr, CvCapture_QT_Movie::image_rgb, CvCapture_QT_Movie::myGWorld, and CvCapture_QT_Movie::myMovie.
  {
        OPENCV_ASSERT (capture,            "icvRetrieveFrame_QT_Movie", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->myMovie,   "icvRetrieveFrame_QT_Movie", "invalid Movie handle");
        OPENCV_ASSERT (capture->image_rgb, "icvRetrieveFrame_QT_Movie", "invalid source image");
        OPENCV_ASSERT (capture->image_bgr, "icvRetrieveFrame_QT_Movie", "invalid destination image");
        PixMapHandle  myPixMapHandle = nil;
        OSErr         myErr          = noErr;
        // invalidates the movie's display state so that the Movie Toolbox
        // redraws the movie the next time we call MoviesTask
        UpdateMovie (capture->myMovie);
        myErr = GetMoviesError ();
        if (myErr != noErr)
        {
              fprintf (stderr, "Couldn't UpdateMovie() in icvRetrieveFrame_QT_Movie().\n");
              return 0;
        }
        // service active movie (= redraw immediately)
        MoviesTask (capture->myMovie, 0L);
        myErr = GetMoviesError ();
        if (myErr != noErr)
        {
              fprintf (stderr, "MoviesTask() didn't succeed in icvRetrieveFrame_QT_Movie().\n");
              return 0;
        }
        // update IplImage header that points to PixMap of the Movie's GWorld.
        // unfortunately, cvCvtColor doesn't know ARGB, the QuickTime pixel format,
        // so we pass a modfied address.
        // ATTENTION: don't access the last pixel's alpha entry, it's inexistant
        myPixMapHandle = GetGWorldPixMap (capture->myGWorld);
        LockPixels (myPixMapHandle);
        cvSetData (capture->image_rgb, GetPixBaseAddr (myPixMapHandle) + 1, GetPixRowBytes (myPixMapHandle));
        // covert RGB of GWorld to BGR
        cvCvtColor (capture->image_rgb, capture->image_bgr, CV_RGBA2BGR);
        // allow QuickTime to access the buffer again
        UnlockPixels (myPixMapHandle);
      // always return the same image pointer
        return capture->image_bgr;
  }
static int icvSetProperty_QT_Cam (CvCapture_QT_Cam * capture, int property_id, double value) static
capture properties currently unimplemented for QuickTime camera interface
Definition at line 650 of file model.cpp.
  {
        assert (0);
        return 0;
  }
static int icvSetProperty_QT_Movie (CvCapture_QT_Movie * capture, int property_id, double value) static
set a capture property. With movie files, it is only possible to set the position (i.e. jump to a given time or frame number)
Author
Mark Asbach asbac.nosp@m.h@ie.nosp@m.nt.rw.nosp@m.th-a.nosp@m.achen.nosp@m..de
Date
2005-11-05
Definition at line 344 of file model.cpp.
References CvCapture_QT_Movie::movie_start_time, CvCapture_QT_Movie::myMovie, CvCapture_QT_Movie::next_frame_number, CvCapture_QT_Movie::next_frame_time, NULL, and CvCapture_QT_Movie::number_of_frames.
  {
        OPENCV_ASSERT (capture,                        "icvSetProperty_QT_Movie", "'capture' is a NULL-pointer");
        OPENCV_ASSERT (capture->myMovie,               "icvSetProperty_QT_Movie", "invalid Movie handle");
        OPENCV_ASSERT (capture->number_of_frames >  0, "icvSetProperty_QT_Movie", "movie has invalid number of frames");
        OPENCV_ASSERT (capture->movie_start_time >= 0, "icvSetProperty_QT_Movie", "movie has invalid start time");
      // inquire desired property
        //
        // rework these three points to really work through 'interesting times'.
        // with the current implementation, they result in wrong times or wrong frame numbers with content that
        // features varying frame durations
      switch (property_id)
      {
              case CV_CAP_PROP_POS_MSEC:
              case CV_CAP_PROP_POS_AVI_RATIO:
                    {
                          TimeValue    destination;
                          OSType       myType     = VisualMediaCharacteristic;
                          OSErr        myErr      = noErr;
                          if (property_id == CV_CAP_PROP_POS_MSEC)
{
                                TimeScale  timescale   = GetMovieTimeScale      (capture->myMovie);
                                           destination = static_cast<TimeValue> (value / 1000.0 * timescale + capture->movie_start_time);
                          }
                          else
{
                                TimeValue  duration    = GetMovieDuration       (capture->myMovie);
                                           destination = static_cast<TimeValue> (value * duration + capture->movie_start_time);
                          }
                          // really seek?
                          if (capture->next_frame_time == destination)
                                break;
                          // seek into which direction?
                          if (capture->next_frame_time < destination)
{
                                while (capture->next_frame_time < destination)
{
                                      capture->next_frame_number++;
                                      GetMovieNextInterestingTime (capture->myMovie, nextTimeStep, 1, & myType, capture->next_frame_time,
                                                                   1, & capture->next_frame_time, NULL);
                                      myErr = GetMoviesError();
                                      if (myErr != noErr)
{
                                            fprintf (stderr, "Couldn't go on to GetMovieNextInterestingTime() in icvGrabFrame_QT.\n");
                                            return 0;
                                      }
                                }
                          }
                          else
{
                                while (capture->next_frame_time > destination)
{
                                      capture->next_frame_number--;
                                      GetMovieNextInterestingTime (capture->myMovie, nextTimeStep, 1, & myType, capture->next_frame_time,
                                                                   -1, & capture->next_frame_time, NULL);
                                      myErr = GetMoviesError();
                                      if (myErr != noErr)
{
                                            fprintf (stderr, "Couldn't go back to GetMovieNextInterestingTime() in icvGrabFrame_QT.\n");
                                            return 0;
                                      }
                                }
                          }
                    }
                    break;
              case CV_CAP_PROP_POS_FRAMES:
                    {
                          TimeValue    destination = static_cast<TimeValue> (value);
                          short        direction   = (destination > capture->next_frame_number) ? 1 : -1;
                          OSType       myType      = VisualMediaCharacteristic;
                          OSErr        myErr       = noErr;
                          while (destination != capture->next_frame_number)
{
                                capture->next_frame_number += direction;
                                GetMovieNextInterestingTime (capture->myMovie, nextTimeStep, 1, & myType, capture->next_frame_time,
                                                                           direction, & capture->next_frame_time, NULL);
                                myErr = GetMoviesError();
                                if (myErr != noErr)
{
                                      fprintf (stderr, "Couldn't step to desired frame number in icvGrabFrame_QT.\n");
                                      return 0;
                                }
                          }
                    }
                    break;
              default:
                    // unhandled or unknown capture property
                    OPENCV_ERROR (CV_StsBadArg, "icvSetProperty_QT_Movie", "unknown or unhandled property_id");
                    return 0;
        }
        // positive result means success
        return 1;
  }
void icvSourceTrackingCallback (void * source_tracking_ref_con, ICMSourceTrackingFlags source_tracking_flags, void * source_frame_ref_con, void * reserved)
Definition at line 1427 of file model.cpp.
Referenced by cvWriteFrame().
    {
      if ( source_tracking_flags & kICMSourceTracking_ReleasedPixelBuffer ) {
          CVPixelBufferRelease(
              *static_cast<CVPixelBufferRef*>( source_frame_ref_con )
          );
      }
  }
Variable Documentation
CvCaptureVTable capture_QT_Cam_vtable static
Initial value:
=
 {
     6,
     (CvCaptureCloseFunc)           icvClose_QT_Cam,
     (CvCaptureGrabFrameFunc)       icvGrabFrame_QT_Cam,
     (CvCaptureRetrieveFrameFunc)   icvRetrieveFrame_QT_Cam,
     (CvCaptureGetPropertyFunc)     icvGetProperty_QT_Cam,
     (CvCaptureSetPropertyFunc)     icvSetProperty_QT_Cam,
     (CvCaptureGetDescriptionFunc)  0
 }
Definition at line 600 of file model.cpp.
Referenced by cvCaptureFromCAM_QT().
CvCaptureVTable capture_QT_Movie_vtable static
Initial value:
=
 {
     6,
     (CvCaptureCloseFunc)           icvClose_QT_Movie,
     (CvCaptureGrabFrameFunc)       icvGrabFrame_QT_Movie,
     (CvCaptureRetrieveFrameFunc)   icvRetrieveFrame_QT_Movie,
     (CvCaptureGetPropertyFunc)     icvGetProperty_QT_Movie,
     (CvCaptureSetPropertyFunc)     icvSetProperty_QT_Movie,
     (CvCaptureGetDescriptionFunc)  0
 }
Definition at line 102 of file model.cpp.
Referenced by cvCaptureFromFile_QT().
int did_enter_movies = 0 static
Definition at line 68 of file model.cpp.
Referenced by cvCaptureFromCAM_QT(), cvCaptureFromFile_QT(), and cvCreateVideoWriter().
TimeScale const TIME_SCALE = 600 static
Definition at line 1121 of file model.cpp.
Referenced by cvCreateVideoWriter().