Visible: include/analysis/nrutil_nr.h File Reference
nrutil_nr.h File Reference
#include <string>
#include <cmath>
#include <complex>
#include <iostream>
Classes
class NRVec< T >
class NRMat< T >
class NRMat3d< T >
class arithcode
class huffcode
class wavefilt
Namespaces
namespace NR
Typedefs
typedef double DP
Functions
template<class T >
const T SQR (const T a)
template<class T >
const T MAX (const T &a, const T &b)
float MAX (const double &a, const float &b)
float MAX (const float &a, const double &b)
template<class T >
const T MIN (const T &a, const T &b)
float MIN (const double &a, const float &b)
float MIN (const float &a, const double &b)
template<class T >
const T SIGN (const T &a, const T &b)
float SIGN (const float &a, const double &b)
float SIGN (const double &a, const float &b)
template<class T >
void SWAP (T &a, T &b)
void NR::nrerror (const string error_text)
const complex< float > operator+ (const double &a, const complex< float > &b)
const complex< float > operator+ (const complex< float > &a, const double &b)
const complex< float > operator- (const double &a, const complex< float > &b)
const complex< float > operator- (const complex< float > &a, const double &b)
const complex< float > operator* (const double &a, const complex< float > &b)
const complex< float > operator* (const complex< float > &a, const double &b)
const complex< float > operator/ (const double &a, const complex< float > &b)
const complex< float > operator/ (const complex< float > &a, const double &b)
float pow (float x, double y)
float pow (double x, float y)
float atan2 (float x, double y)
float atan2 (double x, float y)
Typedef Documentation
typedef double DP
Definition at line 10 of file nrutil_nr.h.
Function Documentation
float atan2 (float x, double y) inline
Definition at line 487 of file nrutil_nr.h.
Referenced by rc2dVector< T >::angle(), arctan(), atan2(), rcLsFit< T >::fit(), rcOptoKineticImage::genDFT(), rc2Xform::mapAngle(), rcDrawLine(), rf1DFourierAnalysis(), rf1DFourierAnalysisVoxels(), rcLsFit< T >::solve3p(), LLSQ::vector_fit_angle(), rcMatrix< 2 >::xRot(), rcMatrix_2d::xRot(), rcMatrix< 2 >::yRot(), and rcMatrix_2d::yRot().
float atan2 (double x, float y) inline
Definition at line 488 of file nrutil_nr.h.
References atan2().
template<class T > const T MAX (const T & a, const T & b) inline
Definition at line 16 of file nrutil_nr.h.
float MAX (const double & a, const float & b) inline
Definition at line 19 of file nrutil_nr.h.
float MAX (const float & a, const double & b) inline
Definition at line 22 of file nrutil_nr.h.
template<class T > const T MIN (const T & a, const T & b) inline
Definition at line 26 of file nrutil_nr.h.
float MIN (const double & a, const float & b) inline
Definition at line 29 of file nrutil_nr.h.
float MIN (const float & a, const double & b) inline
Definition at line 32 of file nrutil_nr.h.
const complex<float> operator* (const double & a, const complex< float > & b) inline
Definition at line 471 of file nrutil_nr.h.
const complex<float> operator* (const complex< float > & a, const double & b) inline
Definition at line 474 of file nrutil_nr.h.
const complex<float> operator+ (const double & a, const complex< float > & b) inline
Definition at line 459 of file nrutil_nr.h.
const complex<float> operator+ (const complex< float > & a, const double & b) inline
Definition at line 462 of file nrutil_nr.h.
const complex<float> operator- (const double & a, const complex< float > & b) inline
Definition at line 465 of file nrutil_nr.h.
const complex<float> operator- (const complex< float > & a, const double & b) inline
Definition at line 468 of file nrutil_nr.h.
const complex<float> operator/ (const double & a, const complex< float > & b) inline
Definition at line 477 of file nrutil_nr.h.
const complex<float> operator/ (const complex< float > & a, const double & b) inline
Definition at line 480 of file nrutil_nr.h.
float pow (float x, double y) inline
Definition at line 485 of file nrutil_nr.h.
Referenced by fft_scalar(), rcMathematicalImage::mMakeImage(), pow(), TIFFCIELabToRGBInit(), and TIFFDefaultTransferFunction().
float pow (double x, float y) inline
Definition at line 486 of file nrutil_nr.h.
References pow().
template<class T > const T SIGN (const T & a, const T & b) inline
Definition at line 36 of file nrutil_nr.h.
Referenced by NR::svdcmp().
float SIGN (const float & a, const double & b) inline
Definition at line 39 of file nrutil_nr.h.
float SIGN (const double & a, const float & b) inline
Definition at line 42 of file nrutil_nr.h.
template<class T > const T SQR (const T a) inline
Definition at line 13 of file nrutil_nr.h.
template<class T > void SWAP (T & a, T & b) inline
Definition at line 46 of file nrutil_nr.h.