Visible: include/stlplus/os_fixes.hpp File Reference
os_fixes.hpp File Reference
#include <unistd.h>
Macros
#define TYPEDEF_TYPENAME typename
#define PARAMETER_TYPENAME typename
#define TEMPLATE_TYPENAME typename
#define RETURN_TYPENAME typename
#define TEMPORARY_TYPENAME typename
Functions
template<typename T >
const T & maximum (const T &l, const T &r)
template<typename T >
const T & minimum (const T &l, const T &r)
bool little_endian (void)
Macro Definition Documentation
#define PARAMETER_TYPENAME typename
Definition at line 180 of file os_fixes.hpp.
#define RETURN_TYPENAME typename
Definition at line 182 of file os_fixes.hpp.
#define TEMPLATE_TYPENAME typename
Definition at line 181 of file os_fixes.hpp.
#define TEMPORARY_TYPENAME typename
Definition at line 183 of file os_fixes.hpp.
#define TYPEDEF_TYPENAME typename
Definition at line 179 of file os_fixes.hpp.
Function Documentation
bool little_endian (void)
Definition at line 32 of file os_fixes.cpp.
References sample().
Referenced by inf::operator=(), inf::to_int(), inf::to_long(), inf::to_short(), inf::to_ulong(), inf::to_unsigned(), and inf::to_ushort().
 {
   int sample = 1;
   char* sample_bytes = (char*)&sample;
   char byte0 = sample_bytes[0];
   bool result = byte0 != 0;
   return result;
 }
template<typename T > const T& maximum (const T & l, const T & r)
Definition at line 97 of file os_fixes.hpp.
Referenced by inf::operator&=(), inf::operator+=(), operator<(), operator==(), inf::operator^=(), and inf::operator|=().
 {return l > r ? l : r;}
template<typename T > const T& minimum (const T & l, const T & r)
Definition at line 98 of file os_fixes.hpp.
 {return l < r ? l : r;}