Visible: include/stlplus/persistent.hpp File Reference
persistent.hpp File Reference
#include "os_fixes.hpp"
#include "textio.hpp"
#include "clonable.hpp"
#include <stdlib.h>
#include <complex>
#include <deque>
#include <bitset>
#include <set>
#include <map>
#include <list>
#include <vector>
#include <string>
#include <typeinfo>
#include <stdexcept>
#include "persistent.tpp"
Classes
class persistent_illegal_type
class persistent_dump_failed
class persistent_restore_failed
class dump_context
class restore_context
class persistent
Functions
void dump (dump_context &, const bool &data) throw (persistent_dump_failed)
void restore (restore_context &, bool &data) throw (persistent_restore_failed)
void dump (dump_context &, const char &data) throw (persistent_dump_failed)
void restore (restore_context &, char &data) throw (persistent_restore_failed)
void dump (dump_context &, const signed char &data) throw (persistent_dump_failed)
void restore (restore_context &, signed char &data) throw (persistent_restore_failed)
void dump (dump_context &, const unsigned char &data) throw (persistent_dump_failed)
void restore (restore_context &, unsigned char &data) throw (persistent_restore_failed)
void dump (dump_context &, const short &data) throw (persistent_dump_failed)
void restore (restore_context &, short &data) throw (persistent_restore_failed)
void dump (dump_context &, const unsigned short &data) throw (persistent_dump_failed)
void restore (restore_context &, unsigned short &data) throw (persistent_restore_failed)
void dump (dump_context &, const int &data) throw (persistent_dump_failed)
void restore (restore_context &, int &data) throw (persistent_restore_failed)
void dump (dump_context &, const unsigned &data) throw (persistent_dump_failed)
void restore (restore_context &, unsigned &data) throw (persistent_restore_failed)
void dump (dump_context &, const long &data) throw (persistent_dump_failed)
void restore (restore_context &, long &data) throw (persistent_restore_failed)
void dump (dump_context &, const unsigned long &data) throw (persistent_dump_failed)
void restore (restore_context &, unsigned long &data) throw (persistent_restore_failed)
void dump (dump_context &, const float &data) throw (persistent_dump_failed)
void restore (restore_context &, float &data) throw (persistent_restore_failed)
void dump (dump_context &, const double &data) throw (persistent_dump_failed)
void restore (restore_context &, double &data) throw (persistent_restore_failed)
template<typename T >
void dump_enum (dump_context &, const T &data) throw (persistent_dump_failed)
template<typename T >
void restore_enum (restore_context &, T &data) throw (persistent_restore_failed)
void dump (dump_context &, char *&data) throw (persistent_dump_failed)
void restore (restore_context &, char *&data) throw (persistent_restore_failed)
template<typename charT , typename traits , typename allocator >
void dump_basic_string (dump_context &, const std::basic_string< charT, traits, allocator > &data) throw (persistent_dump_failed)
template<typename charT , typename traits , typename allocator >
void restore_basic_string (restore_context &, std::basic_string< charT, traits, allocator > &data) throw (persistent_restore_failed)
void dump (dump_context &, const std::string &data) throw (persistent_dump_failed)
void restore (restore_context &, std::string &data) throw (persistent_restore_failed)
template<typename T >
void dump_pointer (dump_context &, const T *const data) throw (persistent_dump_failed)
template<typename T >
void restore_pointer (restore_context &, T *&data) throw (persistent_restore_failed)
template<typename T >
void dump_xref (dump_context &, const T *const data) throw (persistent_dump_failed)
template<typename T >
void restore_xref (restore_context &, T *&data) throw (persistent_restore_failed)
template<typename T >
void dump_polymorph (dump_context &, const T *const data) throw (persistent_dump_failed)
template<typename T >
void restore_polymorph (restore_context &, T *&data) throw (persistent_restore_failed)
template<typename T >
void dump_interface (dump_context &, const T *const data) throw (persistent_dump_failed)
template<typename T >
void restore_interface (restore_context &, T *&data) throw (persistent_restore_failed)
template<size_t N>
void dump_bitset (dump_context &, const std::bitset< N > &data) throw (persistent_dump_failed)
template<size_t N>
void restore_bitset (restore_context &, std::bitset< N > &data) throw (persistent_restore_failed)
template<typename T >
void dump_complex (dump_context &, const std::complex< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_complex (restore_context &, std::complex< T > &data) throw (persistent_restore_failed)
template<typename T >
void dump_deque (dump_context &, const std::deque< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_deque (restore_context &, std::deque< T > &data) throw (persistent_restore_failed)
template<typename T >
void dump_list (dump_context &, const std::list< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_list (restore_context &, std::list< T > &data) throw (persistent_restore_failed)
template<typename K , typename T >
void dump_pair (dump_context &, const std::pair< K, T > &data) throw (persistent_dump_failed)
template<typename K , typename T >
void restore_pair (restore_context &, std::pair< K, T > &data) throw (persistent_restore_failed)
template<typename K , typename T , typename P >
void dump_map (dump_context &, const std::map< K, T, P > &data) throw (persistent_dump_failed)
template<typename K , typename T , typename P >
void restore_map (restore_context &, std::map< K, T, P > &data) throw (persistent_restore_failed)
template<typename K , typename T , typename P >
void dump_multimap (dump_context &, const std::multimap< K, T, P > &data) throw (persistent_dump_failed)
template<typename K , typename T , typename P >
void restore_multimap (restore_context &, std::multimap< K, T, P > &data) throw (persistent_restore_failed)
template<typename K , typename P >
void dump_set (dump_context &, const std::set< K, P > &data) throw (persistent_dump_failed)
template<typename K , typename P >
void restore_set (restore_context &, std::set< K, P > &data) throw (persistent_restore_failed)
template<typename K , typename P >
void dump_multiset (dump_context &, const std::multiset< K, P > &data) throw (persistent_dump_failed)
template<typename K , typename P >
void restore_multiset (restore_context &, std::multiset< K, P > &data) throw (persistent_restore_failed)
template<typename T >
void dump_vector (dump_context &, const std::vector< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_vector (restore_context &, std::vector< T > &data) throw (persistent_restore_failed)
void dump (dump_context &, const std::vector< bool > &data) throw (persistent_dump_failed)
void restore (restore_context &, std::vector< bool > &data) throw (persistent_restore_failed)
template<typename T >
void dump_to_device (const T &source, otext &result, dump_context::installer installer) throw (persistent_dump_failed)
template<typename T >
void restore_from_device (itext &source, T &result, restore_context::installer installer) throw (persistent_restore_failed)
template<typename T >
void dump_to_string (const T &source, std::string &result, dump_context::installer installer) throw (persistent_dump_failed)
template<typename T >
void restore_from_string (const std::string &source, T &result, restore_context::installer installer) throw (persistent_restore_failed)
template<typename T >
void dump_to_file (const T &source, const std::string &filename, dump_context::installer installer) throw (persistent_dump_failed)
template<typename T >
void restore_from_file (const std::string &filename, T &result, restore_context::installer installer) throw (persistent_restore_failed)
Variables
unsigned char PersistentVersion
Function Documentation
void dump (dump_context & , const bool & data) throw (persistent_dump_failed)
Definition at line 591 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & , const char & data) throw (persistent_dump_failed)
Definition at line 602 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & , const signed char & data) throw (persistent_dump_failed)
Definition at line 612 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & , const unsigned char & data) throw (persistent_dump_failed)
Definition at line 622 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & , const short & data) throw (persistent_dump_failed)
Definition at line 632 of file persistent.cpp.
References dump_signed().
 {
   dump_signed(context, sizeof(short), (unsigned char*)&data);
 }
void dump (dump_context & , const unsigned short & data) throw (persistent_dump_failed)
Definition at line 642 of file persistent.cpp.
References dump_unsigned().
 {
   dump_unsigned(context, sizeof(unsigned short), (unsigned char*)&data);
 }
void dump (dump_context & , const int & data) throw (persistent_dump_failed)
Definition at line 652 of file persistent.cpp.
References dump_signed().
 {
   dump_signed(context, sizeof(int), (unsigned char*)&data);
 }
void dump (dump_context & , const unsigned & data) throw (persistent_dump_failed)
Definition at line 662 of file persistent.cpp.
References dump_unsigned().
 {
   dump_unsigned(context, sizeof(unsigned), (unsigned char*)&data);
 }
void dump (dump_context & , const long & data) throw (persistent_dump_failed)
Definition at line 672 of file persistent.cpp.
References dump_signed().
 {
   dump_signed(context, sizeof(long), (unsigned char*)&data);
 }
void dump (dump_context & , const unsigned long & data) throw (persistent_dump_failed)
Definition at line 682 of file persistent.cpp.
References dump_unsigned().
 {
   dump_unsigned(context, sizeof(unsigned long), (unsigned char*)&data);
 }
void dump (dump_context & , const float & data) throw (persistent_dump_failed)
Definition at line 732 of file persistent.cpp.
References dump_float().
 {
   dump_float(context, sizeof(float), (unsigned char*)&data);
 }
void dump (dump_context & , const double & data) throw (persistent_dump_failed)
Definition at line 742 of file persistent.cpp.
References dump_float().
 {
   dump_float(context, sizeof(double), (unsigned char*)&data);
 }
void dump (dump_context & , char *& data) throw (persistent_dump_failed)
Definition at line 756 of file persistent.cpp.
References dump().
 {
   // register the address and get the magic key for it
   std::pair<bool,unsigned> mapping = context.pointer_map(data);
   dump(context,mapping.second);
   // if the address is null, then that is all that we need to do
   // however, if it is non-null and this is the first sight of the address, dump the contents
   if (data && !mapping.first)
   {
     unsigned size = strlen(data);
     dump(context,size);
     for (unsigned i = 0; i < size; i++)
       dump(context,data[i]);
   }
 }
void dump (dump_context & , const std::string & data) throw (persistent_dump_failed)
Definition at line 803 of file persistent.cpp.
References dump_basic_string().
 {
   dump_basic_string(context, data);
 }
void dump (dump_context & , const std::vector< bool > & data) throw (persistent_dump_failed)
Definition at line 816 of file persistent.cpp.
References dump().
 {
   dump(context,data.size());
   size_t size = data.size();
   size_t bytes = ((size + 7) / 8);
   for (size_t b = 0; b < bytes; b++)
   {
     unsigned char byte = 0;
     unsigned char mask = 1;
     for (size_t e = 0; e < 8; e++)
     {
       size_t i = b*8 + e;
       if (i >= size) break;
       if (data[i]) byte |= mask;
       mask <<= 1;
     }
     dump(context,byte);
   }
 }
template<typename charT , typename traits , typename allocator > void dump_basic_string (dump_context & , const std::basic_string< charT, traits, allocator > & data) throw (persistent_dump_failed)
Referenced by dump().
template<size_t N> void dump_bitset (dump_context & , const std::bitset< N > & data) throw (persistent_dump_failed)
template<typename T > void dump_complex (dump_context & , const std::complex< T > & data) throw (persistent_dump_failed)
template<typename T > void dump_deque (dump_context & , const std::deque< T > & data) throw (persistent_dump_failed)
Referenced by dump().
template<typename T > void dump_enum (dump_context & , const T & data) throw (persistent_dump_failed)
template<typename T > void dump_interface (dump_context & , const T *const data) throw (persistent_dump_failed)
template<typename T > void dump_list (dump_context & , const std::list< T > & data) throw (persistent_dump_failed)
template<typename K , typename T , typename P > void dump_map (dump_context & , const std::map< K, T, P > & data) throw (persistent_dump_failed)
template<typename K , typename T , typename P > void dump_multimap (dump_context & , const std::multimap< K, T, P > & data) throw (persistent_dump_failed)
template<typename K , typename P > void dump_multiset (dump_context & , const std::multiset< K, P > & data) throw (persistent_dump_failed)
template<typename K , typename T > void dump_pair (dump_context & , const std::pair< K, T > & data) throw (persistent_dump_failed)
template<typename T > void dump_pointer (dump_context & , const T *const data) throw (persistent_dump_failed)
template<typename T > void dump_polymorph (dump_context & , const T *const data) throw (persistent_dump_failed)
template<typename K , typename P > void dump_set (dump_context & , const std::set< K, P > & data) throw (persistent_dump_failed)
template<typename T > void dump_to_device (const T & source, otext & result, dump_context::installer installer) throw (persistent_dump_failed)
template<typename T > void dump_to_file (const T & source, const std::string & filename, dump_context::installer installer) throw (persistent_dump_failed)
Referenced by saveSig().
template<typename T > void dump_to_string (const T & source, std::string & result, dump_context::installer installer) throw (persistent_dump_failed)
template<typename T > void dump_vector (dump_context & , const std::vector< T > & data) throw (persistent_dump_failed)
Referenced by dump().
template<typename T > void dump_xref (dump_context & , const T *const data) throw (persistent_dump_failed)
void restore (restore_context & , bool & data) throw (persistent_restore_failed)
Definition at line 596 of file persistent.cpp.
 {
   data = context.get() != 0;
 }
void restore (restore_context & , char & data) throw (persistent_restore_failed)
Definition at line 607 of file persistent.cpp.
 {
   data = (char)(unsigned char)context.get();
 }
void restore (restore_context & , signed char & data) throw (persistent_restore_failed)
Definition at line 617 of file persistent.cpp.
 {
   data = (signed char)(unsigned char)context.get();
 }
void restore (restore_context & , unsigned char & data) throw (persistent_restore_failed)
Definition at line 627 of file persistent.cpp.
 {
   data = (signed char)(unsigned char)context.get();
 }
void restore (restore_context & , short & data) throw (persistent_restore_failed)
Definition at line 637 of file persistent.cpp.
References restore_signed().
 {
   restore_signed(context, sizeof(short),(unsigned char*)&data);
 }
void restore (restore_context & , unsigned short & data) throw (persistent_restore_failed)
Definition at line 647 of file persistent.cpp.
References restore_unsigned().
 {
   restore_unsigned(context, sizeof(unsigned short),(unsigned char*)&data);
 }
void restore (restore_context & , int & data) throw (persistent_restore_failed)
Definition at line 657 of file persistent.cpp.
References restore_signed().
 {
   restore_signed(context, sizeof(int),(unsigned char*)&data);
 }
void restore (restore_context & , unsigned & data) throw (persistent_restore_failed)
Definition at line 667 of file persistent.cpp.
References restore_unsigned().
 {
   restore_unsigned(context, sizeof(unsigned),(unsigned char*)&data);
 }
void restore (restore_context & , long & data) throw (persistent_restore_failed)
Definition at line 677 of file persistent.cpp.
References restore_signed().
 {
   restore_signed(context, sizeof(long),(unsigned char*)&data);
 }
void restore (restore_context & , unsigned long & data) throw (persistent_restore_failed)
Definition at line 687 of file persistent.cpp.
References restore_unsigned().
 {
   restore_unsigned(context, sizeof(unsigned long),(unsigned char*)&data);
 }
void restore (restore_context & , float & data) throw (persistent_restore_failed)
Definition at line 737 of file persistent.cpp.
References restore_float().
 {
   restore_float(context, sizeof(float), (unsigned char*)&data);
 }
void restore (restore_context & , double & data) throw (persistent_restore_failed)
Definition at line 747 of file persistent.cpp.
References restore_float().
 {
   restore_float(context, sizeof(double), (unsigned char*)&data);
 }
void restore (restore_context & , char *& data) throw (persistent_restore_failed)
Definition at line 772 of file persistent.cpp.
References restore().
 {
   // destroy any previous contents
   if (data)
   {
     delete[] data;
     data = 0;
   }
   // get the magic key
   unsigned magic = 0;
   restore(context,magic);
   // now lookup the magic key to see if this pointer has already been restored
   // null pointers are always flagged as already restored
   std::pair<bool,void*> address = context.pointer_map(magic);
   if (!address.first)
   {
     // this pointer has never been seen before and is non-null
     // restore the string
     size_t size = 0;
     restore(context,size);
     data = new char[size+1];
     for (size_t i = 0; i < size; i++)
       restore(context,data[i]);
     data[size] = '\0';
     // add this pointer to the set of already seen objects
     context.pointer_add(magic,data);
   }
 }
void restore (restore_context & , std::string & data) throw (persistent_restore_failed)
Definition at line 808 of file persistent.cpp.
References restore_basic_string().
 {
   restore_basic_string(context, data);
 }
void restore (restore_context & , std::vector< bool > & data) throw (persistent_restore_failed)
Definition at line 836 of file persistent.cpp.
References restore().
 {
   size_t size = 0;
   restore(context,size);
   data.resize(size);
   size_t bytes = ((size + 7) / 8);
   for (size_t b = 0; b < bytes; b++)
   {
     unsigned char byte = 0;
     restore(context,byte);
     unsigned char mask = 1;
     for (size_t e = 0; e < 8; e++)
     {
       size_t i = b*8 + e;
       if (i >= size) break;
       data[i] = ((byte & mask) != 0);
       mask <<= 1;
     }
   }
 }
template<typename charT , typename traits , typename allocator > void restore_basic_string (restore_context & , std::basic_string< charT, traits, allocator > & data) throw (persistent_restore_failed)
Referenced by restore().
template<size_t N> void restore_bitset (restore_context & , std::bitset< N > & data) throw (persistent_restore_failed)
template<typename T > void restore_complex (restore_context & , std::complex< T > & data) throw (persistent_restore_failed)
template<typename T > void restore_deque (restore_context & , std::deque< T > & data) throw (persistent_restore_failed)
Referenced by restore().
template<typename T > void restore_enum (restore_context & , T & data) throw (persistent_restore_failed)
template<typename T > void restore_from_device (itext & source, T & result, restore_context::installer installer) throw (persistent_restore_failed)
template<typename T > void restore_from_file (const std::string & filename, T & result, restore_context::installer installer) throw (persistent_restore_failed)
Referenced by loadSig(), and main().
template<typename T > void restore_from_string (const std::string & source, T & result, restore_context::installer installer) throw (persistent_restore_failed)
template<typename T > void restore_interface (restore_context & , T *& data) throw (persistent_restore_failed)
template<typename T > void restore_list (restore_context & , std::list< T > & data) throw (persistent_restore_failed)
template<typename K , typename T , typename P > void restore_map (restore_context & , std::map< K, T, P > & data) throw (persistent_restore_failed)
template<typename K , typename T , typename P > void restore_multimap (restore_context & , std::multimap< K, T, P > & data) throw (persistent_restore_failed)
template<typename K , typename P > void restore_multiset (restore_context & , std::multiset< K, P > & data) throw (persistent_restore_failed)
template<typename K , typename T > void restore_pair (restore_context & , std::pair< K, T > & data) throw (persistent_restore_failed)
template<typename T > void restore_pointer (restore_context & , T *& data) throw (persistent_restore_failed)
template<typename T > void restore_polymorph (restore_context & , T *& data) throw (persistent_restore_failed)
template<typename K , typename P > void restore_set (restore_context & , std::set< K, P > & data) throw (persistent_restore_failed)
template<typename T > void restore_vector (restore_context & , std::vector< T > & data) throw (persistent_restore_failed)
Referenced by restore().
template<typename T > void restore_xref (restore_context & , T *& data) throw (persistent_restore_failed)
Variable Documentation
unsigned char PersistentVersion
Definition at line 20 of file persistent.cpp.