Visible: include/stlplus/persistent.cpp File Reference
persistent.cpp File Reference
#include "os_fixes.hpp"
#include "persistent.hpp"
#include "textio.hpp"
#include "string_utilities.hpp"
#include "smart_ptr.hpp"
Classes
class dump_context_body
class restore_context_body
Macros
#define INDEX(index) ((context.little_endian()) ? (index) : ((bytes) - (index) - 1))
Functions
static void dump_unsigned (dump_context &context, size_t bytes, unsigned char *data) throw (persistent_dump_failed)
static void dump_signed (dump_context &context, size_t bytes, unsigned char *data) throw (persistent_dump_failed)
static void restore_unsigned (restore_context &context, size_t bytes, unsigned char *data) throw (persistent_restore_failed)
static void restore_signed (restore_context &context, size_t bytes, unsigned char *data) throw (persistent_restore_failed)
void dump (dump_context &context, const bool &data) throw (persistent_dump_failed)
void restore (restore_context &context, bool &data) throw (persistent_restore_failed)
void dump (dump_context &context, const char &data) throw (persistent_dump_failed)
void restore (restore_context &context, char &data) throw (persistent_restore_failed)
void dump (dump_context &context, const signed char &data) throw (persistent_dump_failed)
void restore (restore_context &context, signed char &data) throw (persistent_restore_failed)
void dump (dump_context &context, const unsigned char &data) throw (persistent_dump_failed)
void restore (restore_context &context, unsigned char &data) throw (persistent_restore_failed)
void dump (dump_context &context, const short &data) throw (persistent_dump_failed)
void restore (restore_context &context, short &data) throw (persistent_restore_failed)
void dump (dump_context &context, const unsigned short &data) throw (persistent_dump_failed)
void restore (restore_context &context, unsigned short &data) throw (persistent_restore_failed)
void dump (dump_context &context, const int &data) throw (persistent_dump_failed)
void restore (restore_context &context, int &data) throw (persistent_restore_failed)
void dump (dump_context &context, const unsigned &data) throw (persistent_dump_failed)
void restore (restore_context &context, unsigned &data) throw (persistent_restore_failed)
void dump (dump_context &context, const long &data) throw (persistent_dump_failed)
void restore (restore_context &context, long &data) throw (persistent_restore_failed)
void dump (dump_context &context, const unsigned long &data) throw (persistent_dump_failed)
void restore (restore_context &context, unsigned long &data) throw (persistent_restore_failed)
static void dump_float (dump_context &context, size_t bytes, unsigned char *data) throw (persistent_dump_failed)
static void restore_float (restore_context &context, size_t bytes, unsigned char *data) throw (persistent_restore_failed)
void dump (dump_context &context, const float &data) throw (persistent_dump_failed)
void restore (restore_context &context, float &data) throw (persistent_restore_failed)
void dump (dump_context &context, const double &data) throw (persistent_dump_failed)
void restore (restore_context &context, double &data) throw (persistent_restore_failed)
void dump (dump_context &context, char *&data) throw (persistent_dump_failed)
void restore (restore_context &context, char *&data) throw (persistent_restore_failed)
void dump (dump_context &context, const std::string &data) throw (persistent_dump_failed)
void restore (restore_context &context, std::string &data) throw (persistent_restore_failed)
void dump (dump_context &context, const std::vector< bool > &data) throw (persistent_dump_failed)
void restore (restore_context &context, std::vector< bool > &data) throw (persistent_restore_failed)
Variables
unsigned char PersistentVersion = 2
Macro Definition Documentation
#define INDEX (index) ((context.little_endian()) ? (index) : ((bytes) - (index) - 1))
Definition at line 477 of file persistent.cpp.
Referenced by dump_float(), dump_signed(), dump_unsigned(), restore_float(), restore_signed(), and restore_unsigned().
Function Documentation
void dump (dump_context & context, const bool & data) throw (persistent_dump_failed)
Definition at line 591 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & context, const char & data) throw (persistent_dump_failed)
Definition at line 602 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & context, const signed char & data) throw (persistent_dump_failed)
Definition at line 612 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & context, const unsigned char & data) throw (persistent_dump_failed)
Definition at line 622 of file persistent.cpp.
 {
   context.put((unsigned char)data);
 }
void dump (dump_context & context, const short & data) throw (persistent_dump_failed)
Definition at line 632 of file persistent.cpp.
References dump_signed().
 {
   dump_signed(context, sizeof(short), (unsigned char*)&data);
 }
void dump (dump_context & context, const unsigned short & data) throw (persistent_dump_failed)
Definition at line 642 of file persistent.cpp.
References dump_unsigned().
 {
   dump_unsigned(context, sizeof(unsigned short), (unsigned char*)&data);
 }
void dump (dump_context & context, const int & data) throw (persistent_dump_failed)
Definition at line 652 of file persistent.cpp.
References dump_signed().
 {
   dump_signed(context, sizeof(int), (unsigned char*)&data);
 }
void dump (dump_context & context, const unsigned & data) throw (persistent_dump_failed)
Definition at line 662 of file persistent.cpp.
References dump_unsigned().
 {
   dump_unsigned(context, sizeof(unsigned), (unsigned char*)&data);
 }
void dump (dump_context & context, const long & data) throw (persistent_dump_failed)
Definition at line 672 of file persistent.cpp.
References dump_signed().
 {
   dump_signed(context, sizeof(long), (unsigned char*)&data);
 }
void dump (dump_context & context, const unsigned long & data) throw (persistent_dump_failed)
Definition at line 682 of file persistent.cpp.
References dump_unsigned().
 {
   dump_unsigned(context, sizeof(unsigned long), (unsigned char*)&data);
 }
void dump (dump_context & context, const float & data) throw (persistent_dump_failed)
Definition at line 732 of file persistent.cpp.
References dump_float().
 {
   dump_float(context, sizeof(float), (unsigned char*)&data);
 }
void dump (dump_context & context, const double & data) throw (persistent_dump_failed)
Definition at line 742 of file persistent.cpp.
References dump_float().
 {
   dump_float(context, sizeof(double), (unsigned char*)&data);
 }
void dump (dump_context & context, char *& data) throw (persistent_dump_failed)
Definition at line 756 of file persistent.cpp.
References dump().
 {
   // register the address and get the magic key for it
   std::pair<bool,unsigned> mapping = context.pointer_map(data);
   dump(context,mapping.second);
   // if the address is null, then that is all that we need to do
   // however, if it is non-null and this is the first sight of the address, dump the contents
   if (data && !mapping.first)
   {
     unsigned size = strlen(data);
     dump(context,size);
     for (unsigned i = 0; i < size; i++)
       dump(context,data[i]);
   }
 }
void dump (dump_context & context, const std::string & data) throw (persistent_dump_failed)
Definition at line 803 of file persistent.cpp.
References dump_basic_string().
 {
   dump_basic_string(context, data);
 }
void dump (dump_context & context, const std::vector< bool > & data) throw (persistent_dump_failed)
Definition at line 816 of file persistent.cpp.
References dump().
 {
   dump(context,data.size());
   size_t size = data.size();
   size_t bytes = ((size + 7) / 8);
   for (size_t b = 0; b < bytes; b++)
   {
     unsigned char byte = 0;
     unsigned char mask = 1;
     for (size_t e = 0; e < 8; e++)
     {
       size_t i = b*8 + e;
       if (i >= size) break;
       if (data[i]) byte |= mask;
       mask <<= 1;
     }
     dump(context,byte);
   }
 }
static void dump_float (dump_context & context, size_t bytes, unsigned char * data) throw (persistent_dump_failed) static
Definition at line 701 of file persistent.cpp.
References INDEX.
Referenced by dump().
 {
   size_t i = bytes;
   // put the size
   context.put((unsigned char)i);
   // and put the bytes
   while(i--)
     context.put(data[INDEX(i)]);
 }
static void dump_signed (dump_context & context, size_t bytes, unsigned char * data) throw (persistent_dump_failed) static
Definition at line 512 of file persistent.cpp.
References INDEX.
Referenced by dump().
 {
   // first skip all-zero or all-one bytes but only if doing so does not change the sign
   size_t i = bytes;
   if (data[INDEX(i-1)] < 128)
   {
     // positive number so discard leading zeros but only if the following byte is positive
     while(i >= 2 && data[INDEX(i-1)] == 0 && data[INDEX(i-2)] < 128)
       i--;
   }
   else
   {
     // negative number so discard leading ones but only if the following byte is negative
     while(i >= 2 && data[INDEX(i-1)] == 255 && data[INDEX(i-2)] >= 128)
       i--;
   }
   // put the remaining size
   context.put((unsigned char)i);
   // and put the bytes
   while(i--)
     context.put(data[INDEX(i)]);
 }
static void dump_unsigned (dump_context & context, size_t bytes, unsigned char * data) throw (persistent_dump_failed) static
Definition at line 499 of file persistent.cpp.
References INDEX.
Referenced by dump().
 {
   // first skip zero bytes - this may reduce the data to zero bytes long
   size_t i = bytes;
   while(i >= 1 && data[INDEX(i-1)] == 0)
     i--;
   // put the remaining size
   context.put((unsigned char)i);
   // and put the bytes
   while(i--)
     context.put(data[INDEX(i)]);
 }
void restore (restore_context & context, bool & data) throw (persistent_restore_failed)
Definition at line 596 of file persistent.cpp.
 {
   data = context.get() != 0;
 }
void restore (restore_context & context, char & data) throw (persistent_restore_failed)
Definition at line 607 of file persistent.cpp.
 {
   data = (char)(unsigned char)context.get();
 }
void restore (restore_context & context, signed char & data) throw (persistent_restore_failed)
Definition at line 617 of file persistent.cpp.
 {
   data = (signed char)(unsigned char)context.get();
 }
void restore (restore_context & context, unsigned char & data) throw (persistent_restore_failed)
Definition at line 627 of file persistent.cpp.
 {
   data = (signed char)(unsigned char)context.get();
 }
void restore (restore_context & context, short & data) throw (persistent_restore_failed)
Definition at line 637 of file persistent.cpp.
References restore_signed().
 {
   restore_signed(context, sizeof(short),(unsigned char*)&data);
 }
void restore (restore_context & context, unsigned short & data) throw (persistent_restore_failed)
Definition at line 647 of file persistent.cpp.
References restore_unsigned().
 {
   restore_unsigned(context, sizeof(unsigned short),(unsigned char*)&data);
 }
void restore (restore_context & context, int & data) throw (persistent_restore_failed)
Definition at line 657 of file persistent.cpp.
References restore_signed().
 {
   restore_signed(context, sizeof(int),(unsigned char*)&data);
 }
void restore (restore_context & context, unsigned & data) throw (persistent_restore_failed)
Definition at line 667 of file persistent.cpp.
References restore_unsigned().
 {
   restore_unsigned(context, sizeof(unsigned),(unsigned char*)&data);
 }
void restore (restore_context & context, long & data) throw (persistent_restore_failed)
Definition at line 677 of file persistent.cpp.
References restore_signed().
 {
   restore_signed(context, sizeof(long),(unsigned char*)&data);
 }
void restore (restore_context & context, unsigned long & data) throw (persistent_restore_failed)
Definition at line 687 of file persistent.cpp.
References restore_unsigned().
 {
   restore_unsigned(context, sizeof(unsigned long),(unsigned char*)&data);
 }
void restore (restore_context & context, float & data) throw (persistent_restore_failed)
Definition at line 737 of file persistent.cpp.
References restore_float().
 {
   restore_float(context, sizeof(float), (unsigned char*)&data);
 }
void restore (restore_context & context, double & data) throw (persistent_restore_failed)
Definition at line 747 of file persistent.cpp.
References restore_float().
 {
   restore_float(context, sizeof(double), (unsigned char*)&data);
 }
void restore (restore_context & context, char *& data) throw (persistent_restore_failed)
Definition at line 772 of file persistent.cpp.
References restore().
 {
   // destroy any previous contents
   if (data)
   {
     delete[] data;
     data = 0;
   }
   // get the magic key
   unsigned magic = 0;
   restore(context,magic);
   // now lookup the magic key to see if this pointer has already been restored
   // null pointers are always flagged as already restored
   std::pair<bool,void*> address = context.pointer_map(magic);
   if (!address.first)
   {
     // this pointer has never been seen before and is non-null
     // restore the string
     size_t size = 0;
     restore(context,size);
     data = new char[size+1];
     for (size_t i = 0; i < size; i++)
       restore(context,data[i]);
     data[size] = '\0';
     // add this pointer to the set of already seen objects
     context.pointer_add(magic,data);
   }
 }
void restore (restore_context & context, std::string & data) throw (persistent_restore_failed)
Definition at line 808 of file persistent.cpp.
References restore_basic_string().
 {
   restore_basic_string(context, data);
 }
void restore (restore_context & context, std::vector< bool > & data) throw (persistent_restore_failed)
Definition at line 836 of file persistent.cpp.
References restore().
 {
   size_t size = 0;
   restore(context,size);
   data.resize(size);
   size_t bytes = ((size + 7) / 8);
   for (size_t b = 0; b < bytes; b++)
   {
     unsigned char byte = 0;
     restore(context,byte);
     unsigned char mask = 1;
     for (size_t e = 0; e < 8; e++)
     {
       size_t i = b*8 + e;
       if (i >= size) break;
       data[i] = ((byte & mask) != 0);
       mask <<= 1;
     }
   }
 }
static void restore_float (restore_context & context, size_t bytes, unsigned char * data) throw (persistent_restore_failed) static
Definition at line 711 of file persistent.cpp.
References INDEX, and to_string().
Referenced by restore().
 {
   // get the dumped size from the file
   size_t dumped_bytes = (size_t)context.get();
   // get the bytes from the file
   size_t i = dumped_bytes;
   while(i--)
   {
     int ch = context.get();
     if (i < bytes)
       data[INDEX(i)] = (unsigned char)ch;
   }
   // however, if the dumped size was different I don't know how to map the formats, so give an error
   if (dumped_bytes != bytes)
     throw persistent_restore_failed(std::string("size mismatch: dumped ") + to_string(dumped_bytes) + std::string(" bytes, restored ") +
                                     to_string(bytes) + std::string(" bytes"));
 }
static void restore_signed (restore_context & context, size_t bytes, unsigned char * data) throw (persistent_restore_failed) static
Definition at line 555 of file persistent.cpp.
References INDEX, and to_string().
Referenced by restore().
 {
   // get the dumped size from the file
   size_t dumped_bytes = (size_t)context.get();
   // restore the dumped bytes but discard any that don't fit
   size_t i = dumped_bytes;
   while(i--)
   {
     int ch = context.get();
     if (i < bytes)
       data[INDEX(i)] = (unsigned char)ch;
     else
       throw persistent_restore_failed(std::string("integer overflow: restoring byte ") + to_string(i) + " of " + to_string(bytes));
   }
   // sign extend if the dumped integer was smaller
   if (dumped_bytes < bytes)
   {
     if (data[INDEX(dumped_bytes-1)] < 128)
     {
       // positive so zero fill
       for (i = dumped_bytes; i < bytes; i++)
         data[INDEX(i)] = 0;
     }
     else
     {
       // negative so one fill
       for (i = dumped_bytes; i < bytes; i++)
         data[INDEX(i)] = 0xff;
     }
   }
 }
static void restore_unsigned (restore_context & context, size_t bytes, unsigned char * data) throw (persistent_restore_failed) static
Definition at line 535 of file persistent.cpp.
References INDEX, and to_string().
Referenced by restore().
 {
   // get the dumped size from the file
   size_t dumped_bytes = (size_t)context.get();
   // zero fill any empty space
   size_t i = bytes;
   for (; i > dumped_bytes; i--)
     data[INDEX(i-1)] = 0;
   // restore the dumped bytes but discard any that don't fit
   // TODO - could detect overflow and throw an exception here
   while(i--)
   {
     int ch = context.get();
     if (i < bytes)
       data[INDEX(i)] = (unsigned char)ch;
     else
       throw persistent_restore_failed(std::string("integer overflow: restoring byte ") + to_string(i) + " of " + to_string(bytes));
   }
 }
Variable Documentation
unsigned char PersistentVersion = 2
Definition at line 20 of file persistent.cpp.