Visible: src/visual/code/rc_edge.cpp File Reference
rc_edge.cpp File Reference
#include <rc_types.h>
#include <rc_window.h>
#include <rc_edge.h>
#include <rc_stats.h>
#include <rc_fileutils.h>
#include <rc_ipconvert.h>
Classes
class rcEdgeTables
Functions
template<class A , class L >
void sobelEdgeProcess (A *angle, const L *imagePtr, const rcWindow &image, rcWindow &magnitudes, rcWindow &angles)
static int32 getAxis (uint8 val)
static int32 getAngle16Axis (uint16 val)
uint32 rfSpatialEdge (rcWindow &magImage, rcWindow &angleImage, rcWindow &peaks, uint8 threshold, bool angleLabeled)
void rfSobelEdge (const rcWindow &image, rcWindow &magnitudes, rcWindow &angles)
void rfSobel (const rcWindow &image, rcWindow &magnitudes, rcWindow &angles, bool highPrecAngle)
void rfDirectionSignal (const rcWindow &image, const rcWindow &mask, vector< double > &signal)
Variables
rcEdgeTables sEdgeTables
Function Documentation
static int32 getAngle16Axis (uint16 val) inline static
Definition at line 234 of file rc_edge.cpp.
Referenced by rfSpatialEdge().
 {
   return ((val + (1 << (16 - 4))) >> (16 - 3)) % 8;
 }
static int32 getAxis (uint8 val) inline static
Definition at line 229 of file rc_edge.cpp.
Referenced by rfSpatialEdge().
 {
   return ((val + (1 << (8 - 4))) >> (8 - 3)) % 8;
 }
void rfDirectionSignal (const rcWindow & image, const rcWindow & mask, vector< double > & signal)
Definition at line 519 of file rc_edge.cpp.
References rcWindow::bits(), rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel8, rfImageAddMask(), rfMakeTmpFileName(), rfSobel(), rmAssert, rcWindow::rowPointer(), rcWindow::tiff(), and rcWindow::width().
 {
     rcWindow mag, ang;
     rfSobel (image, mag, ang, image.depth () == rcPixel16);
     if (mask.isBound ())
     {
 #ifdef _DEBUG
         static const char *defaultFormat = "/tmp/um%d_%s";
         static const char *baseName = "ih.tiff";
         rcWindow masked = rfImageAddMask (image, mask, 0);
         std::string mfile = rfMakeTmpFileName(defaultFormat, baseName);
         masked.tiff (mfile);
 #endif
     }
     static const double zd (0.0);
     rmAssert (image.depth () == ang.depth ());
     vector<double> histogram (1 << ang.bits(), zd);
     uint32 lastRow = ang.height() - 1, row = 0;
     const uint32 opsPerLoop = 8;
     uint32 unrollCnt = ang.width() / opsPerLoop;
     uint32 unrollRem = ang.width() % opsPerLoop;
     if (!mask.isBound ())
     {
         if (ang.depth () == rcPixel8)
         {
             for ( ; row <= lastRow; row++)
             {
                 const uint8* pixelPtr = ang.rowPointer(row);
                 const uint8* magPtr = mag.rowPointer(row);
                 for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
                 {
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                 }
                 for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++)
                     histogram[*pixelPtr++]+= *magPtr++;
             }
         }
         else if (ang.depth () == rcPixel16)
         {
             for ( ; row <= lastRow; row++)
             {
                 const uint16* pixelPtr = (uint16*) ang.rowPointer(row);
                 const uint8* magPtr = mag.rowPointer(row);
                 for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
                 {
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                     histogram[*pixelPtr++]+= *magPtr++;
                 }
                 for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++)
                     histogram[*pixelPtr++]+= *magPtr++;
             }
         }
         else
         {
             rmAssert (0);
         }
     }
     else
     {
         if (ang.depth () == rcPixel8)
         {
             for ( ; row <= lastRow; row++)
             {
                 const uint8* pixelPtr = ang.rowPointer(row);
                 const uint8* maskPtr = mask.rowPointer(row);
                 for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
                 {
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                 }
                 for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++)
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
             }
         }
         else if (ang.depth () == rcPixel16)
         {
             for ( ; row <= lastRow; row++)
             {
                 const uint16* pixelPtr = (uint16*) ang.rowPointer(row);
                 const uint8* maskPtr = mask.rowPointer(row);
                 for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
                 {
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
                 }
                 for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++)
                     histogram[*pixelPtr++]+= (!*maskPtr++) ? 1 : 0;
             }
         }
         else
         {
             rmAssert (0);
         }
     }
 //  double sumMag = rfSum (histogram);
 //  vector<double>::iterator dItr = histogram.begin ();
 //  for (; dItr != histogram.end(); dItr++) *dItr = *dItr / sumMag;
     signal.clear ();
     swap (signal, histogram);
 }
void rfSobel (const rcWindow & image, rcWindow & magnitudes, rcWindow & angles, bool highPrecAngle)
Definition at line 491 of file rc_edge.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel8, rfSetWindowBorder(), rfSobelEdge(), rmExceptionMacro, rcWindow::size(), and rcWindow::width().
Referenced by rfDirectionSignal(), and rfImageGradientToVisualSegment().
 {
   if (!(image.isBound() && image.width() > 3 && image.height() > 3))
     rmExceptionMacro(<< "rcWindow::badparams");
   if (! (angles.isBound() && angles.size() == image.size() && (angles.depth() == highPrecAngle ? rcPixel16 : rcPixel8)))
     angles = rcWindow (image.width(), image.height(),  highPrecAngle ? rcPixel16 : rcPixel8);
   // else angles is bound, right size and right depth
   if (! (magnitudes.isBound() && magnitudes.size () == image.size() && magnitudes.depth() != rcPixel8))
     magnitudes = rcWindow (image.width(), image.height(), rcPixel8);
   // else angles is bound, right size and right depth
   rfSetWindowBorder(magnitudes, 0.0);
   rfSetWindowBorder(angles, 0.0);
   rcWindow grad ((magnitudes), 1, 1, (magnitudes).width()-2, (magnitudes).height()-2);
   rcWindow angle ((angles), 1, 1, (angles).width()-2, (angles).height()-2);
   rfSobelEdge (image, grad, angle);
 }
void rfSobelEdge (const rcWindow & image, rcWindow & magnitudes, rcWindow & angles)
Definition at line 434 of file rc_edge.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel16, rcPixel8, rmExceptionMacro, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rcSimilarator::correlate(), rcSpatialPyramid< 2 >::gradientProcess(), and rfSobel().
 {
   assert(magnitudes.width() == angles.width());
   assert(image.width() == magnitudes.width() + 2);
   assert(magnitudes.height() == angles.height());
   assert(image.height() == magnitudes.height() + 2);
   switch (image.depth())
     {
     case rcPixel8:
       {
     switch (angles.depth())
       {
       case rcPixel16:
       {
         sobelEdgeProcess<uint16,uint8> ((uint16*) (angles.rowPointer (0)),
                     (const uint8*) (image.rowPointer (0)), image, magnitudes, angles);
         break;
       }
       case rcPixel8:
         {
           sobelEdgeProcess<uint8,uint8> ((uint8*) (angles.rowPointer (0)),
                          (const uint8*) (image.rowPointer (0)), image, magnitudes, angles);
           break;
         }
       default:
         rmExceptionMacro(<< "rcWindow::notImplemented");
       }
     break;
       }
     case rcPixel16:
       {
     switch (angles.depth())
       {
       case rcPixel16:
       {
         sobelEdgeProcess<uint16,uint16> ((uint16*) (angles.rowPointer (0)),
                     (const uint16*) (image.rowPointer (0)), image, magnitudes, angles);
         break;
       }
       case rcPixel8:
         {
           sobelEdgeProcess<uint8,uint16> ((uint8*) (angles.rowPointer (0)),
                           (const uint16*) (image.rowPointer (0)), image, magnitudes, angles);
           break;
         }
       default:
         rmExceptionMacro(<< "rcWindow::notImplemented");
       }
     break;
       }
     default:
       rmExceptionMacro(<< "rcWindow::notImplemented");
     }
 }
uint32 rfSpatialEdge (rcWindow & magImage, rcWindow & angleImage, rcWindow & peaks, uint8 threshold, bool angleLabeled)
Definition at line 240 of file rc_edge.cpp.
References rcWindow::depth(), getAngle16Axis(), getAxis(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel8, rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
Referenced by rcSpatialPyramid< 2 >::gradientProcess(), and rfImageGradientToVisualSegment().
 {
   assert(magImage.width () > 0);
   assert(angleImage.height () > 0);
   int32 width(magImage.width());
   int32 height(angleImage.height());
   int32 magUpdate (magImage.rowUpdate());
   // Peak detection is a 3x3 processing
   rcWindow zeroc;
   if (peaks.isBound() && (peaks.width() == width - 2) && (peaks.height() == height - 2))
     zeroc = peaks;
   else
     zeroc = rcWindow (width - 2, height - 2);
   zeroc.setAllPixels (uint32 (0));
   uint32 numPeaks = 0;
   int32 x,y;
   switch (angleImage.depth())
     {
     case rcPixel8:
   // Main part
   for(y = 0; y < zeroc.height(); y++)
   {
     const uint8 *mag = magImage.rowPointer(y+1);  // 3x3 processing
     const uint8 *ang = angleImage.rowPointer(y+1);
     mag+=1;
     ang+=1;
     uint8 *dest = zeroc.rowPointer(y);
     for(x = 0; x < zeroc.width(); x++,mag++,ang++,dest++)
     {
       if(*mag >= threshold)
       {
         uint8 m1,m2;
         int32 angle = getAxis(*ang);
         switch(angle)
         {
           case 0:
           m1 = *(mag - 1);
           m2 = *(mag + 1);
           break;
           case 1:
           m1 = *(mag - 1 - magUpdate);
           m2 = *(mag + 1 + magUpdate);
           break;
           case 2:
           m1 = *( mag - magUpdate);
           m2 = *( mag + magUpdate);
           break;
           case 3:
           m1 = *( mag + 1 - magUpdate);
           m2 = *( mag - 1 + magUpdate);
           break;
           case 4:
           m2 = *( mag - 1);
           m1 = *( mag + 1);
           break;
           case 5:
           m2 = *( mag - 1 - magUpdate);
           m1 = *( mag + 1 + magUpdate);
           break;
           case 6:
           m2 = *( mag - magUpdate);
           m1 = *( mag + magUpdate);
           break;
           case 7:
           m2 = *( mag + 1 - magUpdate);
           m1 = *( mag - 1 + magUpdate);
           break;
           default:
               m1 = m2 = 0;
               assert (1);
         }
         if((*mag > m1 && *mag >= m2))
         {
           numPeaks++;
           *dest = (angleLabeled) ? ((*ang >> 1) + 127) : *mag;
         }
         else
           *dest = 0;
       }
       else
         *dest = 0;
     }
   }
   break;
     case rcPixel16:
   // Main part
   for(y = 0; y < zeroc.height(); y++)
   {
     const uint8 *mag = magImage.rowPointer(y+1);  // 3x3 processing
     const uint16 *ang = (uint16*) angleImage.rowPointer(y+1);
     mag+=1;
     ang+=1;
     uint8 *dest = zeroc.rowPointer(y);
     for(x = 0; x < zeroc.width(); x++,mag++,ang++,dest++)
     {
       if(*mag >= threshold)
       {
         uint8 m1,m2;
         int32 angle = getAngle16Axis(*ang);
         switch(angle)
         {
           case 0:
           m1 = *(mag - 1);
           m2 = *(mag + 1);
           break;
           case 1:
           m1 = *(mag - 1 - magUpdate);
           m2 = *(mag + 1 + magUpdate);
           break;
           case 2:
           m1 = *( mag - magUpdate);
           m2 = *( mag + magUpdate);
           break;
           case 3:
           m1 = *( mag + 1 - magUpdate);
           m2 = *( mag - 1 + magUpdate);
           break;
           case 4:
           m2 = *( mag - 1);
           m1 = *( mag + 1);
           break;
           case 5:
           m2 = *( mag - 1 - magUpdate);
           m1 = *( mag + 1 + magUpdate);
           break;
           case 6:
           m2 = *( mag - magUpdate);
           m1 = *( mag + magUpdate);
           break;
           case 7:
           m2 = *( mag + 1 - magUpdate);
           m1 = *( mag - 1 + magUpdate);
           break;
           default:
               m1 = m2 = 0;
               assert (1);
         }
         if((*mag > m1 && *mag >= m2))
         {
           numPeaks++;
           *dest = *mag;
         }
         else
           *dest = 0;
       }
       else
         *dest = 0;
     }
   }
   break;
     default:
       rmAssert(0);
     }
   peaks = zeroc;
   return numPeaks;
 }
template<class A , class L > void sobelEdgeProcess (A * angle, const L * imagePtr, const rcWindow & image, rcWindow & magnitudes, rcWindow & angles)
Definition at line 48 of file rc_edge.cpp.
References rcEdgeTables::binAtan(), rcWindow::bits(), rcEdgeTables::eMagPrecision, rcEdgeTables::eMagTableSize, endl(), rcWindow::height(), rcEdgeTables::magnitudeTable(), rmABS, rmAssertDebug, rcWindow::rowPixelUpdate(), rcWindow::rowPointer(), sEdgeTables, and rcWindow::width().
 {
   int32 magUpdate = magnitudes.rowPixelUpdate();
   int32 angleUpdate = angles.rowPixelUpdate();
   int32 srcUpdate = image.rowPixelUpdate();
   L const *src0 = imagePtr;
   uint8 *mag = magnitudes.rowPointer(0);
   int32 h(angles.height());
   int32 width(angles.width());
   static const A dummy (0);
   // For 8 bit images, we divide by 8 (4+4). For 16 bit images, we further divide by 256
   // This could be parameterized as pixel depth is often 12 or 14 bits and not full 16 bits
 const int32 normBits = (image.bits() == 16) ? 6+3 : 3;
   const uint8 *magTable = sEdgeTables.magnitudeTable ();
   // Sobel kernels are symertic. We use a L C R roll over algorithm
   do
   {
     L const *src = src0;
     uint8 *m = mag;
     A*a = angle;
     int32 left (src[0] + 2*src[srcUpdate] + src[2*srcUpdate]);
     int32 yKernelLeft (-src[0] + src[2*srcUpdate]);
     src++;
     int32 center (src[0] + 2*src[srcUpdate] + src[2*srcUpdate]);
     int32 yKernelCenter (-src[0] + src[2*srcUpdate]);
     src++;
     int32 w(width);
     do
     {
       int32 right(src[0] + 2*src[srcUpdate] + src[2*srcUpdate]);
       int32 yKernelRight(-src[0] + src[2*srcUpdate]);
       // Calculate x and y magnitudes
       left = right - left;
       int32 product = yKernelLeft + 2*yKernelCenter + yKernelRight;
       uint8 x = (uint8) (rmABS (left) >> normBits);
       uint8 y = (uint8) (rmABS(product) >> normBits);
       uint32 index = (x << rcEdgeTables::eMagPrecision) | y;
       if (index >= rcEdgeTables::eMagTableSize)
     {
       cerr << index << (int32) x << "," << (int32) y << "," << w <<  "," << h << "," << right << "," << left << endl;
     }
       rmAssertDebug(index < rcEdgeTables::eMagTableSize);
       *m = magTable [index];
       m++;
       // Angle Table
       // if both x and y gradient are less than 5 (1 gray level edge)
       // then set the angle to zero.
       // @note add angle threshold
       //      if (rmABS(product) < 3 && rmABS(left) < 3)
       //    *a++ = dummy;
       //      else
     *a++ = sEdgeTables.binAtan (product, left, dummy);
       left = center;
       center = right;
       yKernelLeft = yKernelCenter;
       yKernelCenter = yKernelRight;
       src++;
     }while(--w);
     mag += magUpdate;
     angle += angleUpdate;
     src0 += srcUpdate;
   }while(--h);
 }
Variable Documentation
rcEdgeTables sEdgeTables
Definition at line 45 of file rc_edge.cpp.
Referenced by sobelEdgeProcess().