Visible: include/visual/rc_peak.h File Reference
rc_peak.h File Reference
#include <list>
#include <rc_window.h>
#include <rc_vector2d.h>
#include <bitset>
Classes
class rcPeak< T >
Functions
template<class T , class S >
void rfDetectPeaks (const rcWindow &pb, T accept, list< rcPeak< S > > &peaks)
void rfPeakDetectAsym8Bit (const rcWindow &win, uint32 accept, list< rcPeak< int16 > > &peaks)
void rfPeakDetect8Bit (const rcWindow &win, uint32 accept, list< rcPeak< int16 > > &peaks)
Function Documentation
template<class T , class S > void rfDetectPeaks (const rcWindow & pb, T accept, list< rcPeak< S > > & peaks)
Definition at line 70 of file rc_peak.h.
References rcWindow::depth(), rcWindow::height(), rcWindow::pelPointer(), rmAssert, rcWindow::rowUpdate(), and rcWindow::width().
Referenced by _exhaustiveImageFind().
 {
   if (!peaks.empty()) peaks.clear();
   const int32 height(pb.height());
   const int32 width(pb.width());
   const int32 rowUpdate(pb.rowUpdate() / sizeof (T));
   const int32 twoRowUpdate(rowUpdate+rowUpdate);
   rmAssert (sizeof(T) == pb.depth());
   for(int32 j = 2; j < (height-2); j++)
   {
     // Start on the 2, 2 pixel since we are testing both 3x3 and 5x5
     const T *pel = (T *) pb.pelPointer (2, j);
     for(int32 i = 2; i < width-2; pel++,i++)
     {
       T pv (*pel);
       if(pv < accept ||
          pv < *(pel - 1) ||
          pv < *(pel - rowUpdate - 1) ||
          pv < *(pel - rowUpdate) ||
          pv < *(pel - rowUpdate + 1) ||
          pv <= *(pel + 1) ||
          pv <= *(pel + rowUpdate + 1) ||
          pv <= *(pel + rowUpdate) ||
          pv <= *(pel + rowUpdate - 1))
     continue;
       if(pv < *(pel - 2) ||
          pv < *(pel - twoRowUpdate - 2) ||
          pv < *(pel - twoRowUpdate) ||
          pv < *(pel - twoRowUpdate + 2) ||
          pv <= *(pel + 2) ||
          pv <= *(pel + twoRowUpdate + 2) ||
          pv <= *(pel + twoRowUpdate) ||
          pv <= *(pel + twoRowUpdate - 2))
     continue;
       // We have a peak
       peaks.push_front(rcPeak<S>(pv,rcIPair(i,j)));
     }
   }
   // Sort and put the highest first
   peaks.sort();
   peaks.reverse();
 }
void rfPeakDetect8Bit (const rcWindow & win, uint32 accept, list< rcPeak< int16 > > & peaks)
void rfPeakDetectAsym8Bit (const rcWindow & win, uint32 accept, list< rcPeak< int16 > > & peaks)