Visible: include/analysis/rc_ip.h File Reference
rc_ip.h File Reference
#include <rc_window.h>
#include <rc_vector2d.h>
#include <rc_macro.h>
Classes
class rcGaussKernel2D< T, ksize >
class rcLNTable
Functions
void rfGaussianConv (const rcWindow &src, rcWindow &dest, int32 kernelSize)
void rfPixel8Map (const rcWindow &src, rcWindow &dst, const vector< uint8 > &lut)
void rfPixel16Map (const rcWindow &src, rcWindow &dst, const vector< uint16 > &lut)
void rfPixel8Invert (const rcWindow &src, rcWindow &dst)
void rfPixelExpand (const rcWindow &src, rcWindow &dest, int32 xmag, int32 ymag)
rcWindow rfPixelExpand (const rcWindow &src, int32 xmag, int32 ymag)
void rfPixelSample (const rcWindow &src, rcWindow &dest, int32 xskip, int32 yskip)
rcWindow rfPixelSample (const rcWindow &src, int32 xskip, int32 yskip)
rcWindow rfCubicShiftImage (rcWindow &src, double, double)
void rfPixelMin3By3 (const rcWindow &srcImg, rcWindow &dstImg)
rcWindow rfPixelMin3By3 (const rcWindow &image)
void rfPixelMax3By3 (const rcWindow &srcImg, rcWindow &dstImg)
rcWindow rfPixelMax3By3 (const rcWindow &image)
void rfPixel8Min3By3 (const rcWindow &srcImg, rcWindow &dstImg)
rcWindow rfPixel8Min3By3 (const rcWindow &image)
void rfPixel8Max3By3 (const rcWindow &srcImg, rcWindow &dstImg)
rcWindow rfPixel8Max3By3 (const rcWindow &image)
void rfMedian (const rcWindow &srcImg, rcWindow &dstImg)
rcWindow rfPixelMedian3x3 (const rcWindow &image)
void rfImageVerticalReflect (const rcWindow &src, rcWindow &dst)
float rfSurfaceHessian (rcWindow &src)
void rfHysteresisThreshold (const rcWindow &magImage, rcWindow &dst, uint8 magLowThreshold, uint8 magHighThreshold, int32 &nSurvivors, int32 nPels, uint8 outVal, uint8 inVal)
void rfCopyWindowBorder (rcWindow &win, const rcWindow &src)
template<class T >
int32 rfGradHist1d (const T *first, const T *last)
Function Documentation
void rfCopyWindowBorder (rcWindow & win, const rcWindow & src)
Definition at line 224 of file rc_moreip.cpp.
References rcWindow::copyPixelsFromWindow(), rcWindow::height(), and rcWindow::width().
 {
   const int32 width(win.width());
   const int32 height(win.height());
   rcWindow top (win, 0, 0, width, 1);
   rcWindow dtop (src, 0, 0, width, 1);
   top.copyPixelsFromWindow (dtop);
   rcWindow bot (win, 0, height-1, width, 1);
   rcWindow dbot (src, 0, height-1, width, 1);
   top.copyPixelsFromWindow (dbot);
   rcWindow left (win, 0, 0, 1, height);
   rcWindow dleft (src, 0, 0, 1, height);
   left.copyPixelsFromWindow (dleft);
   rcWindow right (win, width-1, 0, 1, height);
   rcWindow dright (src, width-1, 0, 1, height);
   right.copyPixelsFromWindow (dright);
 }
rcWindow rfCubicShiftImage (rcWindow & src, double , double)
Definition at line 61 of file rc_cubic.cpp.
References abs(), createKernelCC(), FALSE, rcWindow::height(), limits_t::Lower, NEW_PIXEL, rcWindow::pelPointer(), TRUE, rcWindow::width(), kernel_limits_t::XLimits, and kernel_limits_t::YLimits.
 {
     kernel_limits_t Limits;
     int32 SrcXLower, DstXLower;
     int32 SrcYLower, DstYLower;
     int32 OldXCorner, OldYCorner;
     int16 Width, Height;
     double kernel[16];
     uint8 * TargetRow;
     int32 x, y;
     rcWindow Shifted;
     register uint8 * PixelPtr0, *PixelPtr1, *PixelPtr2, *PixelPtr3;
     static uint8 ClipBuf[3 * 256];
     static uint8 * Clip = ClipBuf + 256;
     static int32 Initialized = FALSE;
     if ( !Initialized )
     {
     int32 i;
     /* Cubic convolution might return a pixel value as low as
        -71.72 or as high as 326.72 (I think).  Instead of using
        a two-part "if" statement, however, I'll use an
        array for speed.
        I'll also initialize a larger array, just in case. */
     for ( i = -255 ; i < 0 ; i++ )
         Clip[i] = 0;
     for ( i = 0 ; i < 256 ; i++ )
         Clip[i] = i;
     for ( i = 256 ; i < 512 ; i++ )
         Clip[i] = 255;
     Initialized = TRUE;
     }
     /*  Src         Dst
        Negative Shifts:
        (x0-xshift,y0-yshift)  --> (0,0)
        positive Shifts:
        (x0,y0)  --> (x0+xshift,y0+xshift)
        The dst x0,y0 is defined to be 0,0 in both pos and neg
        shift cases. The client coords is updated with the shifts.
     */
     if ( XShift >= 0 )
     {
       SrcXLower = 0;
       DstXLower = (int32) XShift;
     }
     else
     {
       SrcXLower = - (int32) XShift;
       DstXLower = 0;
     }
     if ( YShift >= 0 )
     {
       SrcYLower = 0;
       DstYLower = (int32) YShift;
     }
     else
     {
       SrcYLower = - (int32) YShift;
       DstYLower = 0;
     }
     Width  = Image.width() - abs((int32)XShift);
     Height = Image.height() - abs((int32)YShift);
     assert(Width > 0);
     assert(Height > 0);
     // If no shift is necessary just return the src
     if ( (XShift == (int32) XShift) && (YShift == (int32) YShift) )
     {
       return Image;
     }
     createKernelCC(kernel, XShift, YShift, &Limits );
     /*
       for ( xx = 0 ; xx < 4 ; xx++ )
       {
         for ( yy = 0 ; yy < 4 ; yy++ )
            printf("%f ", (double)kernel[xx *4 + yy]);
          putc('\n', stdout);
       }
     */
     /* Determine the region within the original image that will be iterated
        over to produce the shifted image.  There are two issues that need
        to be considered beyond those considered in the integer case.
        Get rid of the edges.  This means decreasing the
        boundaries based on the kernel.
        The cubic convolution kernel is 4x4, decreasing the size in each
        dimension by 3 (1 on one side, 2 on the far side)
        However, now to compute shifts that
        contain pixel fractions we need to do the above convolution.
        Customary erosion of the input image region by the 4x4 kernel.
        Src         Dst
        Negative Shifts:
        (x0-xshift+1,y0-yshift+1)  --> (1,1)
        src region is eroded by 1 to allow the kernel
        positive Shifts:
        (x0+1,y0+1)  --> (x0+xshift+1,y0+xshift+1)
     */
     Width  -= 3;
     Height -= 3;
     /* Adjust the limits based on kernel. Since the size of the resultant
        image is just the valid region
        */
     SrcXLower += abs(Limits.XLimits.Lower);
     SrcYLower += abs(Limits.YLimits.Lower);
     DstXLower += abs(Limits.XLimits.Lower);
     DstYLower += abs(Limits.YLimits.Lower);
     /* Create Dst image
      * Dst (0,0) is src (DstXLower,DstYLower)
      */
     Shifted = rcWindow (Width,Height);
     /* Determine value for each interpolated (destination) pixel */
     OldYCorner = SrcYLower + Limits.YLimits.Lower;
     for ( y = 0 ; y < Height ; y++, OldYCorner++ )
     {
       TargetRow = Shifted.pelPointer (DstXLower,y);
       OldXCorner = SrcXLower + Limits.XLimits.Lower;
       PixelPtr0 = Image.pelPointer(OldXCorner, OldYCorner);
       PixelPtr1 = Image.pelPointer(OldXCorner, OldYCorner+1);
       PixelPtr2 = Image.pelPointer(OldXCorner, OldYCorner+2);
       PixelPtr3 = Image.pelPointer(OldXCorner, OldYCorner+3);
       for ( x = 0 ;
        x < Width ;
        x++, PixelPtr0++, PixelPtr1++, PixelPtr2++, PixelPtr3++ )
     NEW_PIXEL(x);
     }
     return Shifted;
 }
void rfGaussianConv (const rcWindow & src, rcWindow & dest, int32 kernelSize)
Definition at line 223 of file rc_ip.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isD32Float(), LOOP4KERNEL, NULL, rcPixel16, rcPixel32, rcPixel8, rfGauss3(), rfHasSIMD(), rmAssert, sGaussFloatKernel5, sGaussKernel5, rcWindow::vImage(), and rcWindow::width().
Referenced by rcSimilarator::correlate(), rcVisualFunction::correspondMutualChannel(), generateExpansionMovie(), generateRandomMovie(), generateTranslationMovie(), genSpatialSDImg(), rcSpatialPyramid< 2 >::intensityProcess(), and rcEngineImpl::modelTracker().
 {
     assert(kernelSize >= 3);
     assert(kernelSize % 2 == 1);
     assert(dest.width() == src.width());
     assert(dest.height() == src.height());
     assert(dest.depth() == src.depth());
     bool Depth32IsFloat = src.isD32Float ();
     assert(&src != &dest);
     const uint32 width(src.width());
     const uint32 height(src.height());
     assert (width >= kernelSize && height >= kernelSize);
 #ifdef VIMAGE_LARGE_KERNEL_TEST_OK
     switch (kernelSize)
     {
         LOOP4KERNEL(7);
         LOOP4KERNEL(9);
         LOOP4KERNEL(11);
         LOOP4KERNEL(13);
         LOOP4KERNEL(15);
     }
 #endif
     if (rfHasSIMD () && kernelSize == 5)
     {
         if (src.depth() == rcPixel8)
         {
             vImage_Buffer vb, vd;
             src.vImage (vb);      dest.vImage (vd);
             vImage_Error ve;
             ve = vImageConvolve_Planar8(&vb, &vd, NULL,
                 0, 0, sGaussKernel5[0],
                 5, 5, 256, 0,
                 kvImageEdgeExtend);
             rmAssert (!ve);
             return;
         }
         else   if (src.depth() == rcPixel16)
         {
     // Convert 16 to float
             vImage_Buffer s16, sf, d16, df;
             src.vImage (s16);
             dest.vImage (d16);
             rcWindow f (src.width(), dest.height(), rcPixel32);
             f.vImage (sf);
             rcWindow ff (src.width(), dest.height(), rcPixel32);
             ff.vImage (df);
             vImage_Error ve;
             ve = vImageConvert_16UToF (&s16, &sf, 0.0f, 1.0f, kvImageNoFlags);
             rmAssert (!ve);
             ve = vImageConvolve_PlanarF( &sf, &df, NULL,
                 0, 0, sGaussFloatKernel5[0],
                 5, 5, 0, kvImageEdgeExtend);
             rmAssert (!ve);
             ve = vImageConvert_FTo16U (&df, &d16, 0.0f, 1.0f, kvImageNoFlags);
             rmAssert (!ve);
             return;
         }
         else if (src.depth() == rcPixel32 && Depth32IsFloat)
         {
             vImage_Buffer vb, vd;
             src.vImage (vb);      dest.vImage (vd);
             vImage_Error ve;
             ve = vImageConvolve_PlanarF(&vb, &vd, NULL,
                 0, 0, sGaussFloatKernel5[0],
                 5, 5, 0, kvImageEdgeExtend);
             rmAssert (!ve);
             return;
         }
         else if (src.depth() == rcPixel32)
         {
             unsigned char edgeFill[4] = { 0, 0, 0, 0 };
             vImage_Buffer vb, vd;
             src.vImage (vb);      dest.vImage (vd);
             vImage_Error ve;
             ve = vImageConvolve_ARGB8888(&vb, &vd, NULL,
                 0, 0, sGaussKernel5[0],
                 5, 5, 25, edgeFill, kvImageEdgeExtend);
             rmAssert (!ve);
             return;
         }
     }
     if(kernelSize == 3)
     {
         rfGauss3(src,dest, Depth32IsFloat);
         return;
     }
     rcWindow work(width,height, src.depth ());
 // Ping pong between dest and work but make sure you end up in dest
     rcWindow& dest1 =  (kernelSize % 4 == 1) ? work : dest;
     rcWindow& dest2 =  (kernelSize % 4 == 3) ? work : dest;
     rfGauss3 (src,dest1, Depth32IsFloat);
     while(1)
     {
         kernelSize -= 2;
         rfGauss3 (dest1, dest2, Depth32IsFloat);
         if(kernelSize == 3)
             return;
         kernelSize -= 2;
         rfGauss3 (dest2, dest1, Depth32IsFloat);
         if(kernelSize == 3)
             return;
     }
 }
template<class T > int32 rfGradHist1d (const T * first, const T * last)
Definition at line 133 of file rc_ip.h.
References rmAssert.
 {
   int32 length = last - first + 1; //@note pointer difference. We do one less
   rmAssert(length > 0);
   const uint32 opsPerLoop = 8;
   uint32 unrollCnt = length / opsPerLoop;
   uint32 unrollRem = length % opsPerLoop;
   int32 diffsum = 0;
   const T *pixelPtr = first;
   for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
     {
         diffsum += (pixelPtr[0] != pixelPtr[1]);
         diffsum += (pixelPtr[1] != pixelPtr[2]);
         diffsum += (pixelPtr[2] != pixelPtr[3]);
         diffsum += (pixelPtr[3] != pixelPtr[4]);
         diffsum += (pixelPtr[4] != pixelPtr[5]);
         diffsum += (pixelPtr[5] != pixelPtr[6]);
         diffsum += (pixelPtr[6] != pixelPtr[7]);
         diffsum += (pixelPtr[7] != pixelPtr[8]);
         pixelPtr += opsPerLoop;
     }
   for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++)
     { diffsum += (pixelPtr[0] != pixelPtr[1]); pixelPtr++;}
   return diffsum;
 }
void rfHysteresisThreshold (const rcWindow & magImage, rcWindow & dst, uint8 magLowThreshold, uint8 magHighThreshold, int32 & nSurvivors, int32 nPels, uint8 outVal, uint8 inVal)
Definition at line 67 of file rc_surface.cpp.
References rcWindow::height(), rcWindow::isBound(), rfPixel8Map(), rfSetWindowBorder(), rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), rcWindow::setAllPixels(), rcWindow::size(), and rcWindow::width().
Referenced by rcSpatialPyramid< 2 >::gradientProcess().
 {
   const uint8 noEdgeLabel = outVal;
   const uint8 edgeLabel = inVal;
   uint8 oscEdgeLabel;
   if (noEdgeLabel != 0 && edgeLabel != 0) oscEdgeLabel = 0;
   else if (noEdgeLabel != 1 && edgeLabel != 1) oscEdgeLabel = 1;
   else oscEdgeLabel = 2;
   if (!dst.isBound())
     {
       rcWindow dstRoot = rcWindow (magImage.width()+2, magImage.height()+2);
       dstRoot.setAllPixels (noEdgeLabel);
       dst = rcWindow(dstRoot, 1, 1, magImage.width(), magImage.height());
     }
   else
     {
       dst.setAllPixels (noEdgeLabel);
       rmAssert (dst.width() == magImage.width() &&
         dst.height() ==magImage.height());
     }
   const int32 width(dst.width()), height(dst.height());
   rcWindow work(width + 2,height + 2);
   rfSetWindowBorder (work, uint8(noEdgeLabel));
   rcWindow win(work, 1, 1, width, height);
   // Create the identity map for this set of thresholds
   vector<uint8> map(256);
   int32 i(0);
   for (; i < magLowThreshold; i++) map[i] = noEdgeLabel;
   for (i = 0; i < (magHighThreshold - magLowThreshold); i++)
     map[magLowThreshold + i] = oscEdgeLabel;
   for (i = 0; i < (256 - magHighThreshold); i++)
     map[magHighThreshold + i] = edgeLabel;
   rfPixel8Map(magImage, win, map);
   const int32 maxPeaks(nPels >= 0 ? nPels : width*height);
   vector<rsHystNode> stack(maxPeaks);
   rmAssert(win.size() == dst.size());
   int32 nPeaks(0);
   i = 0;
   const int32 workUpdate(win.rowUpdate()), dstUpdate(dst.rowUpdate());
   // Note:
   // -- and ++ are push and pop operations for the stack
   for(int32 y = 0; y < height; y++)
   {
     uint8 *p    = win.rowPointer(y);
     uint8 *dest = dst.rowPointer(y);
     for(int32 x = width; x--; p++,dest++)
     {
       if(*p == edgeLabel)
       {
         stack[i].workAddr = p;
         stack[(i++)].destAddr = dest;
         while(i)
         {
           uint8 *pp = stack[(--i)].workAddr;
           uint8 *dd = stack[i].destAddr;
       // If it is not marked, mark it an edge in dest
       // and mark it a no edge in mag
           if(!*dd)
           {
             *dd = edgeLabel;
             nPeaks++;
           }
           *pp = noEdgeLabel;
       // If any of our neighbors is a possible edge push their address in
           if(*(pp - workUpdate - 1) == oscEdgeLabel)
           {
             stack[i].workAddr = pp - workUpdate - 1;
             stack[(i++)].destAddr = dd - dstUpdate - 1;
           }
           if(*(pp - workUpdate) == oscEdgeLabel)
           {
             stack[i].workAddr = pp - workUpdate;
             stack[(i++)].destAddr = dd - dstUpdate;
           }
           if(*(pp - workUpdate + 1) == oscEdgeLabel)
           {
             stack[i].workAddr = pp - workUpdate + 1;
             stack[(i++)].destAddr = dd - dstUpdate + 1;
           }
           if(*(pp + 1) == oscEdgeLabel)
           {
             stack[i].workAddr = pp + 1;
             stack[(i++)].destAddr = dd + 1;
           }
           if(*(pp + workUpdate + 1) == oscEdgeLabel)
           {
             stack[i].workAddr = pp + workUpdate + 1;
             stack[(i++)].destAddr = dd + dstUpdate + 1;
           }
           if(*(pp + workUpdate) == oscEdgeLabel)
           {
             stack[i].workAddr = pp + workUpdate;
             stack[(i++)].destAddr = dd + dstUpdate;
           }
           if(*(pp + workUpdate - 1) == oscEdgeLabel)
           {
             stack[i].workAddr = pp + workUpdate - 1;
             stack[(i++)].destAddr = dd + dstUpdate - 1;
           }
           if(*(pp - 1) == oscEdgeLabel)
           {
             stack[i].workAddr = pp - 1;
             stack[(i++)].destAddr = dd - 1;
           }
         }
       }
     }
   }
   nSurvivors = nPeaks;
   return;
 }
void rfImageVerticalReflect (const rcWindow & src, rcWindow & dst)
Definition at line 163 of file rc_moreip.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcPixel32, rcPixel8, rmAssert, rmExceptionMacro, rcWindow::size(), rcWindow::vImage(), rcWindow::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by copyImage().
 {
   if (!dst.isBound())
     {
       dst = rcWindow (src.width(), src.height(), src.depth());
     }
   rcIPair delta = dst.size() - src.size();
   if (delta.x() < 0 || delta.y() < 0)
     rmExceptionMacro (<< "Size Mismatch");
   rcWindow dWin (dst, delta.x(), delta.y(),src.width(),src.height());
   vImage_Buffer vb, vd;
   src.vImage (vb);
   dWin.vImage (vd);
   vImage_Error ve;
   vImage_Flags vf (0);
   switch (src.depth ())
     {
     case rcPixel8:
       ve = vImageVerticalReflect_Planar8 (&vb, &vd, vf);
       rmAssert (ve == kvImageNoError);
       break;
     case rcPixel32:
       ve = vImageVerticalReflect_ARGB8888(&vb, &vd, vf);
       rmAssert (ve == kvImageNoError);
       break;
     default:
       rmExceptionMacro (<< "Not Implemented");
       break;
     }
 }
void rfMedian (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 37 of file rc_median.cpp.
References rcWindow::height(), rcWindow::isBound(), rfCopyWindowBorder(), rfMedian3By3Depth8(), and rcWindow::width().
Referenced by rcVisualFunction::beatProcess(), rcMuscleSegmenter::filterBySize(), rcEngineImpl::groupStatistics(), rcKinetoscope::keepPopulationMeasure(), and rcMutualInfoGrouping::rcMutualInfoGrouping().
 {
    assert (srcImg.isBound());
    assert (dstImg.isBound());
    assert (srcImg.width() == (dstImg.width()));
    assert (srcImg.height() == (dstImg.height()));
    rfCopyWindowBorder(dstImg, srcImg);
    rcWindow dwin (dstImg, 1, 1, dstImg.width() - 2, dstImg.height() - 2);
    rfMedian3By3Depth8(srcImg, dwin);
 }
void rfPixel16Map (const rcWindow & src, rcWindow & dst, const vector< uint16 > & lut)
Definition at line 693 of file rc_ip.cpp.
References rcBasicPixelMap< T >::areaFunc().
Referenced by rfPixel16Map().
 {
   rcBasicPixelMap<uint16> p16 (src, dst, lut);
   p16.areaFunc ();
 }
void rfPixel8Invert (const rcWindow & src, rcWindow & dst)
Definition at line 687 of file rc_ip.cpp.
References rfPixel8Map(), and sInvertTable.
 {
   rfPixel8Map (src, dst, sInvertTable.table ());
 }
void rfPixel8Map (const rcWindow & src, rcWindow & dst, const vector< uint8 > & lut)
Definition at line 660 of file rc_ip.cpp.
References rcBasicPixelMap< T >::areaFunc(), rcWindow::depth(), rcWindow::isBound(), rcPixel8, rfHasSIMD(), rmAssert, and rcWindow::vImage().
Referenced by rcSegmentationLevel::binaryImage(), rfHysteresisThreshold(), rfPixel8Invert(), and rcMuscleSegmenter::segment().
 {
   assert (lut.size() == 256);
   assert (src.isBound());
   assert (dst.isBound());
   assert (src.depth() == rcPixel8);
   assert (dst.depth() == rcPixel8);
   // Direct all unaligned src and destinations to the basic calculations
   if (rfHasSIMD ())
        {
      vImage_Buffer vb, vd;
      src.vImage (vb);     dst.vImage (vd);
      vImage_Error ve;
      ve = vImageTableLookUp_Planar8(&vb, &vd, &lut[0],kvImageEdgeExtend);
      rmAssert (!ve);
      return;
        }
     else
       {
     rcBasicPixelMap<uint8> p8 (src, dst, lut);
     p8.areaFunc ();
       }
 }
void rfPixel8Max3By3 (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 305 of file rc_moreip.cpp.
References rcWindow::height(), rcWindow::pelPointer(), rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
 {
   const uint8  *srcPtr1, *srcPtr2, *srcRowBase;
   uint8        *dstPtr, *dstRowBase;
   uint8         currMaxVal, pelVal;
   int       i, j, k, l;
   int       rowIter, colIter, srcRUC, dstRUC;
   colIter = srcImg.width() - 2;
   rowIter = srcImg.height() - 2;
   srcRUC = srcImg.rowUpdate();
   dstRUC = dstImg.rowUpdate();
   srcRowBase = srcImg.rowPointer(0);
   dstRowBase = dstImg.pelPointer (0,0);
   for(i = rowIter; i;
       i--, dstRowBase += dstRUC, srcRowBase += srcRUC)
   {
     dstPtr = dstRowBase;
     srcPtr1 = srcRowBase;
     for(j = colIter; j; j--, dstPtr++, srcPtr1++)
     {
       srcPtr2 = srcPtr1;
       currMaxVal = 0;
       for(k = 3; k; k--)
       {
         for(l = 3; l; l--, srcPtr2++)
         {
           pelVal = *srcPtr2;
       currMaxVal = (pelVal > currMaxVal) ?  pelVal : currMaxVal;
     }
     srcPtr2 += srcRUC - 3;
       }
       *dstPtr = currMaxVal;
     }
   }
 }
rcWindow rfPixel8Max3By3 (const rcWindow & image)
Definition at line 346 of file rc_moreip.cpp.
References rcWindow::height(), rcWindow::isBound(), rfPixel8Min3By3(), rmAssert, and rcWindow::width().
 {
   rmAssert (image.isBound());
   rcWindow newdest (image.width()-2, image.height()-2);
   rfPixel8Min3By3 (image, newdest);
   return newdest;
 }
void rfPixel8Min3By3 (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 253 of file rc_moreip.cpp.
References rcWindow::height(), rcWindow::pelPointer(), rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
 {
   const uint8  *srcPtr1, *srcPtr2, *srcRowBase;
   uint8        *dstPtr, *dstRowBase;
   uint8         currMinVal, pelVal;
   int       i, j, k, l;
   int       rowIter, colIter, srcRUC, dstRUC;
   colIter = srcImg.width() - 2;
   rowIter = srcImg.height() - 2;
   srcRUC = srcImg.rowUpdate();
   dstRUC = dstImg.rowUpdate();
   srcRowBase = srcImg.rowPointer(0);
   dstRowBase = dstImg.pelPointer (0,0);
   for(i = rowIter;
       i; i--, dstRowBase += dstRUC, srcRowBase += srcRUC)
   {
     dstPtr = dstRowBase;
     srcPtr1 = srcRowBase;
     for(j = colIter; j; j--, dstPtr++, srcPtr1++)
     {
       srcPtr2 = srcPtr1;
       currMinVal = 255;
       for(k = 3; k; k--)
       {
         for(l = 3; l; l--, srcPtr2++)
         {
           pelVal = *srcPtr2;
       currMinVal = (pelVal < currMinVal) ?  pelVal : currMinVal;
     }
     srcPtr2 += srcRUC - 3;
       }
       *dstPtr = (uint8)currMinVal;
     }
   }
 }
rcWindow rfPixel8Min3By3 (const rcWindow & image)
Definition at line 295 of file rc_moreip.cpp.
References rcWindow::height(), rcWindow::isBound(), rfPixel8Min3By3(), rmAssert, and rcWindow::width().
 {
   rmAssert (image.isBound());
   rcWindow newdest (image.width()-2, image.height()-2);
   rfPixel8Min3By3 (image, newdest);
   return newdest;
 }
void rfPixelExpand (const rcWindow & src, rcWindow & dest, int32 xmag, int32 ymag)
Definition at line 462 of file rc_moreip.cpp.
References rcWindow::height(), rcRectangle< T >::height(), rcWindow::isBound(), rcWindow::pelPointer(), rmAssert, rcWindow::rowUpdate(), rcWindow::width(), and rcRectangle< T >::width().
Referenced by rfPixelExpand().
 {
   rmAssert(xmag >= 1);
   rmAssert(ymag >= 1);
   if (!src.isBound())
     return;
   rcIRect dstgcr;
   dstgcr = rcIRect (rcIPair (0,0), rcIPair(src.width() * xmag, src.height() * ymag));
   if (!dest.isBound())
     {
       dest = rcWindow (int32 (src.width() * xmag),
                int32 (src.height() * ymag));
     }
   rmAssert (static_cast<int32>(dest.width()) >= dstgcr.width());
   rmAssert (static_cast<int32>(dest.height()) >= dstgcr.height());
   // Consider only whole blocks of src pixels
   int32 srcWidth  = src.width();
   int32 srcHeight = src.height();
   int32 srcRowUpdate = src.rowUpdate();
   int32 dstRowUpdate = dest.rowUpdate();
   int32 dstMagRowUpdate = dstRowUpdate * ymag;
   // Setup source and destination pointers according to magnification
   const uint8* srcPtr = src.pelPointer(0,0);
   uint8* dstPtr = dest.pelPointer(0,0);
   for (int32 y=0; y<srcHeight; y++)
     {
       uint8* pDest = dstPtr;
       const uint8* pSrc = srcPtr;
       for (int32 x=0; x<srcWidth; x++)
     {
       // read the val to be expanded
       uint8 destVal = (uint8) *pSrc;
       uint8* pDestTemp = pDest;
       // Write one block of xmag by ymag
       for (int32 ycopy = ymag; ycopy; --ycopy)
         {
           uint8* pDestRow = pDestTemp;
           for (int32 xcopy = xmag; xcopy; --xcopy)
         {
           //          rmAssert (dest.contains (pDestRow));
           *pDestRow++ = destVal;
         }
           // Next destination row
           pDestTemp += dstRowUpdate;
         }
       pSrc++;
       pDest += xmag;
     }
       // Source: next row, Destination: next ymag destination row
       srcPtr += srcRowUpdate;
       dstPtr += dstMagRowUpdate;
     }
 }
rcWindow rfPixelExpand (const rcWindow & src, int32 xmag, int32 ymag)
Definition at line 455 of file rc_moreip.cpp.
References rfPixelExpand().
 {
   rcWindow dest;
   rfPixelExpand(src, dest, xmag, ymag);
   return dest;
 }
void rfPixelMax3By3 (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 118 of file rc_moreip.cpp.
References rcWindow::depth(), rcWindow::height(), NULL, rcPixel16, rcPixel32, rcPixel8, rfPixel8Max3By3(), rmAssert, rmExceptionMacro, rcWindow::size(), rcWindow::vImage(), and rcWindow::width().
Referenced by rcKinetoscope::connectedFunctions(), and rfPixelMax3By3().
 {
   rmAssert (srcImg.depth() == dstImg.depth());
   rmAssert (srcImg.size() == dstImg.size());
   if (srcImg.depth() == rcPixel8)
     {
       rcWindow newdest (dstImg, 1, 1,
             srcImg.width()-2, srcImg.height()-2);
       rfPixel8Max3By3(srcImg, newdest);
     }
   else   if (srcImg.depth() == rcPixel16)
     {
       // Convert 16 to float
       vImage_Buffer s16, sf, d16, df;
       srcImg.vImage (s16);
       dstImg.vImage (d16);
       rcWindow f (srcImg.width(), dstImg.height(), rcPixel32);
       f.vImage (sf);
       rcWindow ff (srcImg.width(), dstImg.height(), rcPixel32);
       ff.vImage (df);
       vImage_Error ve;
       ve = vImageConvert_16UToF (&s16, &sf, 0.0f, 1.0f, kvImageNoFlags);
       rmAssert (!ve);
       ve = vImageMax_PlanarF( &sf, &df, NULL, 0, 0, 3, 3, kvImageNoFlags);
       rmAssert (!ve);
       ve = vImageConvert_FTo16U (&sf, &df, 0.0f, 1.0f, kvImageNoFlags);
       rmAssert (!ve);
     }
   else
     {
       rmExceptionMacro (<<"Unimplemented");
     }
 }
rcWindow rfPixelMax3By3 (const rcWindow & image)
Definition at line 153 of file rc_moreip.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rfPixelMax3By3(), rmAssert, and rcWindow::width().
 {
   rmAssert (image.isBound());
   rcWindow newdest (image.width(), image.height(), image.depth());
   rfPixelMax3By3 (image, newdest);
   return newdest;
 }
rcWindow rfPixelMedian3x3 (const rcWindow & image)
void rfPixelMin3By3 (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 71 of file rc_moreip.cpp.
References rcWindow::depth(), rcWindow::height(), NULL, rcPixel16, rcPixel32, rcPixel8, rfPixel8Min3By3(), rmAssert, rmExceptionMacro, rcWindow::size(), rcWindow::vImage(), and rcWindow::width().
Referenced by rcKinetoscope::connectedFunctions(), and rfPixelMin3By3().
 {
   rmAssert (srcImg.depth() == dstImg.depth());
   rmAssert (srcImg.size() == dstImg.size());
   if (srcImg.depth() == rcPixel8)
     {
       rcWindow newdest (dstImg, 1, 1,
             srcImg.width()-2, srcImg.height()-2);
       rfPixel8Min3By3(srcImg, newdest);
     }
   else   if (srcImg.depth() == rcPixel16)
     {
       // Convert 16 to float
       vImage_Buffer s16, sf, d16, df;
       srcImg.vImage (s16);
       dstImg.vImage (d16);
       rcWindow f (srcImg.width(), dstImg.height(), rcPixel32);
       f.vImage (sf);
       rcWindow ff (srcImg.width(), dstImg.height(), rcPixel32);
       ff.vImage (df);
       vImage_Error ve;
       ve = vImageConvert_16UToF (&s16, &sf, 0.0f, 1.0f, kvImageNoFlags);
       rmAssert (!ve);
       ve = vImageMin_PlanarF( &sf, &df, NULL, 0, 0, 3, 3, kvImageNoFlags);
       rmAssert (!ve);
       ve = vImageConvert_FTo16U (&sf, &df, 0.0f, 1.0f, kvImageNoFlags);
       rmAssert (!ve);
     }
   else
     {
       rmExceptionMacro (<<"Unimplemented");
     }
 }
rcWindow rfPixelMin3By3 (const rcWindow & image)
Definition at line 107 of file rc_moreip.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rfPixelMin3By3(), rmAssert, and rcWindow::width().
 {
   rmAssert (image.isBound());
   rcWindow newdest (image.width(), image.height(), image.depth());
   rfPixelMin3By3 (image, newdest);
   return newdest;
 }
void rfPixelSample (const rcWindow & src, rcWindow & dest, int32 xskip, int32 yskip)
Definition at line 547 of file rc_moreip.cpp.
References rcWindow::height(), rcRectangle< T >::height(), rcWindow::isBound(), rcWindow::pelPointer(), rmAssert, rcWindow::rowPointer(), rcWindow::width(), and rcRectangle< T >::width().
Referenced by generateExpansionMovie(), generateRandomMovie(), generateTranslationMovie(), rcSpatialPyramid< 2 >::intensityProcess(), rcEngineImpl::modelTracker(), and rfPixelSample().
 {
   rmAssert(xskip >= 1);
   rmAssert(yskip >= 1);
   // See the note above for Expand
   int32 ulx = 0; int32 uly = 0;
   int32 lrx = src.width() / xskip;  int32 lry = src.height()/ yskip;
   if (ulx >= lrx || uly >= lry)
     return;
   rcIRect redSrc (rcIPair(ulx, uly), rcIPair(lrx, lry));
   if (!dest.isBound())
     {
       dest = rcWindow (redSrc.width(), redSrc.height());
     }
   // Holds coords of the pixel in source image coordinate frame where <0,0> in
   // destination image coordinate frame maps to.
   int32 xOrigin = (xskip-1) / 2 ;
   int32 yOrigin = (yskip-1) / 2;
   for (int32 y = 0; y < dest.height(); y++)
     {
       uint8* pDest = dest.rowPointer(y);
       const uint8* pSrc = src.pelPointer(xOrigin, y*yskip + yOrigin);
       int32 x = dest.width();
       do
     {
       *pDest++ = uint8 (*pSrc);
       pSrc += xskip;
     }
       while (--x);
     }
 }
rcWindow rfPixelSample (const rcWindow & src, int32 xskip, int32 yskip)
Definition at line 539 of file rc_moreip.cpp.
References rfPixelSample().
 {
   rcWindow dest;
   rfPixelSample(src, dest, xskip, yskip);
   return dest;
 }
float rfSurfaceHessian (rcWindow & src)
Definition at line 34 of file rc_surface.cpp.
References rcWindow::height(), rcWindow::pixelCount(), rmSquare, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
Referenced by rcKinetoscope::validate().
 {
   float gxx(0.0), gyy(0.0), gxy(0.0);
   int32 rup (src.rowUpdate());
   float nn (src.pixelCount() * 2);
   for (int32 j = 1; j < src.height() - 1; j++)
     {
       uint8 * g = src.rowPointer (j);
       for (int32 i = 1; i < src.width() - 1; i++, g++)
     {
       float gp (g[0] );
       float gx (gp - g[1]);
       float gy (gp - g[rup]);
       gxx += (rmSquare (gx));
       gyy += (rmSquare (gy));
       gxy += (gx * gy);
     }
     }
   // Return the min eigenvalue
   return (gxx + gyy - sqrt((gxx - gyy)*(gxx - gyy) + 4*gxy*gxy))/ nn;
 }