Visible: src/util/code/rc_resource_ctrl.cpp File Reference
rc_resource_ctrl.cpp File Reference
#include <rc_types.h>
#include "rc_resource_ctrl.h"
#include <sys/shm.h>
#include <sys/sem.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <assert.h>
#include <rc_assemblyfcts.h>
#include <new.h>
#include <signal.h>
#include <iostream>
Macros
#define WD_MAX_REPEATS 150
#define WD_US_TO_SLEEP 100000
Functions
void * rcResCtrlWatchdog (void *watchInfoAddr)
Variables
int mpDebugging = 0
Macro Definition Documentation
#define WD_MAX_REPEATS 150
Definition at line 21 of file rc_resource_ctrl.cpp.
Referenced by rcResCtrlWatchdog().
#define WD_US_TO_SLEEP 100000
Definition at line 22 of file rc_resource_ctrl.cpp.
Referenced by rcResCtrlWatchdog().
Function Documentation
void* rcResCtrlWatchdog (void * watchInfoAddr)
Definition at line 30 of file rc_resource_ctrl.cpp.
References rcSharedMemoryUser::forceRelease(), rcAtomicValue< T >::getValue(), mpDebugging, watchdogInfo::peerDead, rcSharedMemNoError, watchdogInfo::readP, rcAtomicValue< T >::setValue(), watchdogInfo::shMemUser, watchdogInfo::shutdown, WD_MAX_REPEATS, WD_US_TO_SLEEP, and watchdogInfo::writeP.
Referenced by rcCreateChildShmem::rcCreateChildShmem(), and rcExecWithShmem::rcExecWithShmem().
 {
   assert(watchInfoAddr);
   watchdogInfo& wdInfo = *(watchdogInfo*)watchInfoAddr;
   assert(wdInfo.shMemUser);
   assert(wdInfo.readP);
   assert(wdInfo.writeP);
   fprintf(stderr, "Watchdog starting up ra 0x%X wa 0x%X\n",
      (unsigned int)(wdInfo.readP), (unsigned int)(wdInfo.writeP));
   uint16 lastValueRead = 0;    // Last value read from peer
   uint16 checkCount = 0;       // # of times read has occurred without change
   uint16 lastValueWritten = 0; // Last value written to peer
   uint8  shutdown;
   for (; wdInfo.shutdown.getValue(shutdown) == 0;)
   {
     /* First, check to see that peer is alive.
      */
     uint16 curRead;
     if (wdInfo.readP->getValue(curRead) == lastValueRead)
     {
       if (!mpDebugging && (checkCount++ >= WD_MAX_REPEATS))
       {
     fprintf(stderr, "peer dead\n");
     /* Peer appears dead. Notify the rest of the process and quit thread.
      */
     wdInfo.peerDead.setValue(1);
     /* Make sure processing thread awakens.
      */
     rcSharedMemError err;
     if ((err = wdInfo.shMemUser->forceRelease()) != rcSharedMemNoError)
       fprintf(stderr, "Error on call to forceRelease %d\n", err);
     fprintf(stderr, "returning from watchdog on death\n");
     return 0;
       }
     }
     else
     {
       lastValueRead = curRead;
       checkCount = 0;
     }
     /* Next, let peer know we are still alive.
      */
     wdInfo.writeP->setValue(++lastValueWritten);
     /* Finally, sleep for a while before repeating.
      */
     usleep(WD_US_TO_SLEEP);
   }
   fprintf(stderr, "returning from watchdog on shutdown\n");
   return 0;
 }
Variable Documentation
int mpDebugging = 0
Definition at line 27 of file rc_resource_ctrl.cpp.
Referenced by rcCreateChildShmem::rcCreateChildShmem(), and rcResCtrlWatchdog().