Visible: include/analysis/rc_dbdt.h File Reference
rc_dbdt.h File Reference
#include <rc_window.h>
#include <rc_vector2d.h>
#include <rc_math.h>
#include <deque>
#include <map>
Classes
class rcDbDtParams
class rcFeature
class rcMotionPath
Macros
#define rmMinTarget 5
#define rmStdSpeed 1
Typedefs
typedef multimap< int32,
rcMotionPath > rcMotionMap
Functions
int32 rf2key (const rcIPair &p)
void rfkey2xy (const int32 &key, rcIPair &p)
void rfACPeaks (const rcWindow &cur, rcMotionMap &mmap, const rcDbDtParams &params)
uint32 rfMotionField (const rcWindow &cur, const rcWindow &next, rcMotionMap &vectorMap, rcMotionMap &bodyMap, const rcDbDtParams &params)
Macro Definition Documentation
#define rmMinTarget 5
Definition at line 85 of file rc_dbdt.h.
#define rmStdSpeed 1
Definition at line 86 of file rc_dbdt.h.
Referenced by rcFeature::init().
Typedef Documentation
typedef multimap<int32, rcMotionPath> rcMotionMap
Definition at line 401 of file rc_dbdt.h.
Function Documentation
int32 rf2key (const rcIPair & p) inline
Definition at line 390 of file rc_dbdt.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   return (((p.x())<<16)+(p.y()));
 }
void rfACPeaks (const rcWindow & cur, rcMotionMap & mmap, const rcDbDtParams & params)
void rfkey2xy (const int32 & key, rcIPair & p) inline
Definition at line 395 of file rc_dbdt.h.
References rcPair< T >::x(), and rcPair< T >::y().
 {
   p.y() = key & 0x0000ffff;
   p.x() = key >> 16;
 }
uint32 rfMotionField (const rcWindow & cur, const rcWindow & next, rcMotionMap & vectorMap, rcMotionMap & bodyMap, const rcDbDtParams & params)