Visible: src/visible/src/rc_segmentimpl.cpp File Reference
rc_segmentimpl.cpp File Reference
#include "rc_segmentimpl.h"
#include "rc_trackimpl.h"
Functions
ostream & operator<< (ostream &os, rcSegmentIterator &i)
Function Documentation
ostream& operator<< (ostream & os, rcSegmentIterator & i)
Definition at line 323 of file rc_segmentimpl.cpp.
References endl(), rcSegmentIterator::getSegmentIndex(), rcSegmentIterator::getSegmentLength(), rcSegmentIterator::getSegmentOffset(), rcSegmentIterator::getSegmentStart(), rcSegmentIterator::getSegmentStartAbsolute(), and rcSegmentIterator::getTrackOffset().
 {
     os << "rcSegmentIterator";
     rcTimestamp segStart = i.getSegmentStart();
     rcTimestamp segAbsStart = i.getSegmentStartAbsolute();
     rcTimestamp segLen = i.getSegmentLength();
     os << " segRelStart " << segStart << " segAbsStart " << segAbsStart << " segLen " << segLen <<  " segRelEnd " << segStart + segLen;
     os << " position " << i.getTrackOffset() << " segIdx " << i.getSegmentIndex() << " segOffset " << i.getSegmentOffset() << endl;
     return os;
 }