Visible: include/visual/rc_polygon_edge.h File Reference
rc_polygon_edge.h File Reference
#include <iterator>
#include <rc_vector2d.h>
Classes
class rcPolygonSegment
class Polygon_2__Segment_ptr< Segment_ >
class Polygon_2_edge_iterator< Container_ >
Functions
template<class Container_ >
Container_::difference_type distance_type (const Polygon_2_edge_iterator< Container_ > &)
template<class Container_ >
rcPolygonSegment * value_type (const Polygon_2_edge_iterator< Container_ > &)
Function Documentation
template<class Container_ > Container_::difference_type distance_type (const Polygon_2_edge_iterator< Container_ > &)
Definition at line 173 of file rc_polygon_edge.h.
 { return Container_::difference_type(); }
template<class Container_ > rcPolygonSegment* value_type (const Polygon_2_edge_iterator< Container_ > &)
Definition at line 177 of file rc_polygon_edge.h.
Referenced by rcLatticeSimilarator::fill(), inf::inf(), inf::operator=(), rf1DAutoCorr(), rf1DCrossCorr(), rf1DNormalizedCorr(), rf1dPeaker(), rf1dSignalIntersection(), rf1dSignalNormEuclideanIntersection(), rfCellDensity(), rfPlot1Dsignal(), rcCmdLine::splitLine(), and rcLatticeSimilarator::update().
 { return (rcPolygonSegment *)(0); }