Visible: src/visible/qt/rc_imagecanvasgl.cpp File Reference
rc_imagecanvasgl.cpp File Reference
#include <rc_math.h>
#include <rc_vector2d.h>
#include <qapplication.h>
#include <qcursor.h>
#include <qtooltip.h>
#include <QMouseEvent>
#include <QKeyEvent>
#include <rc_writermanager.h>
#include <rc_ipconvert.h>
#include <rc_kinetoscope.h>
#include "rc_monitor.h"
#include "rc_modeldomain.h"
#include "rc_trackmanager.h"
Macros
#define QStrFrcStr(foo) QString ((foo).c_str())
#define rubberBandColor glColor3d(0.1,0.5,1.0)
#define GLerrorNUM(a) ourGlErrFun(__FILE__, __LINE__, (a))
#define ARGB_IMAGE_TYPE GL_UNSIGNED_INT_8_8_8_8
#define CORNER_MARKER 1
Functions
static const double sOtherDimension (10.0)
static int ourGlErrFun (char *Fname, int32 Lnumber, char *FuncName)
static bool focusCompare (const rcFocusTrack &lhs, const rcFocusTrack &rhs)
static bool copyImage (const rcWindow &src, const QSize &newSize, rcWindow &dst, bool mirror, bool equalize=false)
Copies analysis images with appropriate depth for display in OpenGL.
static void displayOpenGLInfo ()
static void displayOpenGLError (const char *prefix, GLenum error)
Variables
static const int cMinWidth = 240
static const int cMinHeight = 180
static const int cDefaultWidth = 320
static const int cDefaultHeight = 240
static const int cMaxPicWidth = 8192
static const int cMaxPicHeight = 8192
static double cMinScaleFactor = 0.25
static double cMaxScaleFactor = 600
static double cScaleUpFactor = 0.25
static const Qt::BackgroundMode cWidgetBackgroundMode = Qt::FixedColor
static const int cMouseMinL2 = 100
static const rcDPair sMidOrigin (0.0, 0.5)
static const uint32 cEllipseSegments =rcCosTable::eTableSize
static const rcCosTable cCosTable
static const rcSinTable cSinTable
const rcRadian cArrowTipAngle (rkPI-rkPI/6.)
static const int32 sSelectBufferSize = 1000
static GLuint sSelectBuffer [sSelectBufferSize]
static const int cQuickPanFactor = 10
Macro Definition Documentation
#define ARGB_IMAGE_TYPE GL_UNSIGNED_INT_8_8_8_8
Definition at line 1080 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::buildImageDlist().
#define CORNER_MARKER 1
Definition at line 1902 of file rc_imagecanvasgl.cpp.
#define GLerrorNUM (a) ourGlErrFun(__FILE__, __LINE__, (a))
Definition at line 56 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::drawAffineRect(), rcImageCanvasGL::drawCurrentFocus(), rcImageCanvasGL::drawRubberBandRect(), rcImageCanvasGL::keyPressEvent(), rcImageCanvasGL::loadrcWindow(), rcImageCanvasGL::mouseReleaseEvent(), rcImageCanvasGL::paintGL(), rcImageCanvasGL::scaleChanged(), rcImageCanvasGL::showSaturatedPixels(), rcImageCanvasGL::updateAnalysisRect(), and rcImageCanvasGL::updateAnalysisRectRotation().
#define QStrFrcStr (foo) QString ((foo).c_str())
Definition at line 27 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::draw().
#define rubberBandColor glColor3d(0.1,0.5,1.0)
Definition at line 53 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::drawAffineRect(), rcImageCanvasGL::drawCurrentFocus(), and rcImageCanvasGL::drawRubberBandRect().
Function Documentation
bool copyImage (const rcWindow & src, const QSize & newSize, rcWindow & dst, bool mirror, bool equalize = false) static
Copies analysis images with appropriate depth for display in OpenGL.
Parameters
src is the src analysis image 8 and 16 are displayed at 8, 32 is ARGB
dst is output image. Caching scheme avoid creating new images unless necessary
mirror VerticalReflect to adjust to camera centric openGL design.
equalize for 8 bit images uses image equalization
Definition at line 2514 of file rc_imagecanvasgl.cpp.
References rcFrame::colorMapSize(), rcWindow::copyPixelsFromWindow(), rcWindow::depth(), rcWindow::frameBuf(), rcFrame::getColor(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel8, rfImageConvert168(), rfImageVerticalReflect(), rmAssert, rcFrame::setColor(), rcFrame::setIsGray(), rcWindow::size(), rcWindow::width(), and rcPair< T >::y().
Referenced by rcImageCanvasGL::loadrcWindow().
 {
     bool copied = false;
     rcWindow tmp;
     // 16 bit but we are display its 8 bit range
     rcPixel dp = (src.depth() == rcPixel16) ? rcPixel8 : src.depth();
     if ( src.isBound() )
       {
     if (src.depth() == rcPixel16)
       {
         // 16 bit but we are display its 8 bit range
         tmp = rcWindow (src.width(), src.height());
         rfImageConvert168 (src, tmp);
       }
         if ( !dst.isBound() )
       {
             // No cached framebuf exists, create a new one
             rcWindow w( newSize.width(), newSize.height(), dp);
             dst = w;
         } else if ( static_cast<int>(dst.width()) < newSize.width() ||
                     static_cast<int>(dst.height()) < newSize.height() )
       {
             // Cached framebuf is too small, create a bigger one
             rcWindow w( newSize.width(), newSize.height(), dp );
             dst = w;
       } else if ( !(src.depth() == rcPixel16 && dst.depth() == rcPixel8) && src.depth() != dst.depth() )
       {
             // Cached framebuf has wrong depth, create a new one
             rcWindow w( newSize.width(), newSize.height(), dp );
             dst = w;
       }
     rmAssert (dst.depth() != rcPixel16);
         // Copy grayness property
         dst.frameBuf()->setIsGray(dp == rcPixel8 );
         // Copy pixel values, mirror vertically for OpenGL
     if (mirror)
       {
         rcIPair delta = dst.size() - src.size();
         rcWindow dWin (dst, 0, delta.y() < 0 ? 0 : delta.y(),
                src.width(),src.height());
         rfImageVerticalReflect (tmp.isBound() ? tmp : src, dWin);
       }
     else
       dst.copyPixelsFromWindow(tmp.isBound() ? tmp : src, mirror);
         // Copy color map values
         const rcFrame& srcFrame =  (tmp.isBound()) ? *tmp.frameBuf() : *src.frameBuf();
         uint32 cMapSize = srcFrame.colorMapSize();
     rcFrame& dstFrame =  *dst.frameBuf();
     uint32 csize = dstFrame.colorMapSize();
         rmAssert(csize == cMapSize );
         for ( uint32 i = 0; i < cMapSize; ++i ) {
             dstFrame.setColor( i, srcFrame.getColor( i ) );
         }
         copied = true;
     }
     return copied;
 }
static void displayOpenGLError (const char * prefix, GLenum error) static
Definition at line 105 of file rc_imagecanvasgl.cpp.
References endl().
Referenced by rcImageCanvasGL::buildImageDlist(), rcImageCanvasGL::draw(), rcImageCanvasGL::drawAffineRect(), rcImageCanvasGL::drawRubberBandRect(), rcImageCanvasGL::initializeGL(), rcImageCanvasGL::paintGL(), rcImageCanvasGL::resizeGL(), and rcImageCanvasGL::setStyle().
 {
     if ( error != GL_NO_ERROR ) {
         const GLubyte* errString = gluErrorString( error );
         cerr << prefix << " OpenGL error: ";
         if ( errString )
             cerr << errString;
         else
             cerr << error;
         cerr << endl;
     }
 }
static void displayOpenGLInfo () static
Definition at line 88 of file rc_imagecanvasgl.cpp.
References endl().
Referenced by rcImageCanvasGL::rcImageCanvasGL().
 {
     const GLubyte* v = glGetString( GL_VENDOR );
     if ( v )
         cerr << v << endl;
     const GLubyte* vr  = glGetString( GL_VERSION );
     if ( vr )
         cerr << vr << endl;
     const GLubyte* r = glGetString( GL_RENDERER );
      if ( r )
         cerr << r << endl;
     const GLubyte* e = glGetString( GL_EXTENSIONS );
     if ( e )
         cerr << e << endl;
 }
static bool focusCompare (const rcFocusTrack & lhs, const rcFocusTrack & rhs) static
Definition at line 71 of file rc_imagecanvasgl.cpp.
References rcFocusTrack::_centerDist.
Referenced by rcImageCanvasGL::enableCellGroup(), rcImageCanvasGL::findClosestCellGroup(), and rcMonitor::mouseReleaseEvent().
 {
     return (lhs._centerDist <= rhs._centerDist);
 }
static int ourGlErrFun (char * Fname, int32 Lnumber, char * FuncName) static
Definition at line 119 of file rc_imagecanvasgl.cpp.
 {
    GLenum err;
    err=glGetError();
    if (err  != GL_NO_ERROR)
      {
        printf("FileName:%s Line:%d Function Name:%s\nError:(%d)%s\n"
           ,Fname,Lnumber,FuncName,err, gluErrorString(err));
      }
    return(err);
 }
static const double sOtherDimension (10. 0) static
Referenced by rcImageCanvasGL::drawAffineRect(), and rcImageCanvasGL::mouseReleaseEvent().
Variable Documentation
const rcRadian cArrowTipAngle(rkPI-rkPI/6.)
Referenced by rcImageCanvasGL::draw().
const rcCosTable cCosTable static
Definition at line 64 of file rc_imagecanvasgl.cpp.
const int cDefaultHeight = 240 static
Definition at line 37 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::rcImageCanvasGL().
const int cDefaultWidth = 320 static
Definition at line 36 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::rcImageCanvasGL().
const uint32 cEllipseSegments =rcCosTable::eTableSize static
Definition at line 61 of file rc_imagecanvasgl.cpp.
const int cMaxPicHeight = 8192 static
Definition at line 40 of file rc_imagecanvasgl.cpp.
const int cMaxPicWidth = 8192 static
Definition at line 39 of file rc_imagecanvasgl.cpp.
double cMaxScaleFactor = 600 static
Definition at line 44 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::checkScale(), rcImageCanvasGL::rcImageCanvasGL(), and rcImageCanvasGL::reconvertImage().
const int cMinHeight = 180 static
Definition at line 35 of file rc_imagecanvasgl.cpp.
double cMinScaleFactor = 0.25 static
Definition at line 42 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::checkScale().
const int cMinWidth = 240 static
Definition at line 34 of file rc_imagecanvasgl.cpp.
const int cMouseMinL2 = 100 static
Definition at line 49 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::findCellPositionTracks().
const int cQuickPanFactor = 10 static
Definition at line 509 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::keyPressEvent().
double cScaleUpFactor = 0.25 static
Definition at line 46 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::keyPressEvent(), and rcImageCanvasGL::mouseScaleEvent().
const rcSinTable cSinTable static
Definition at line 65 of file rc_imagecanvasgl.cpp.
const Qt::BackgroundMode cWidgetBackgroundMode = Qt::FixedColor static
Definition at line 48 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::rcImageCanvasGL().
const rcDPair sMidOrigin(0.0, 0.5) static
Referenced by rcImageCanvasGL::drawAffineRect(), and rcImageCanvasGL::mouseReleaseEvent().
GLuint sSelectBuffer[sSelectBufferSize] static
Definition at line 136 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::select().
const int32 sSelectBufferSize = 1000 static
Definition at line 135 of file rc_imagecanvasgl.cpp.
Referenced by rcImageCanvasGL::rcImageCanvasGL(), and rcImageCanvasGL::select().