Visible: include/util/rc_math.h File Reference
rc_math.h File Reference
#include "rc_types.h"
#include "rc_limits.h"
#include <cmath>
Classes
class rcRadian
class rcDegree
class rcAngle8
class rcAngle16
class rcFixed16
Macros
#define rkPI (3.1415926535897932384626433832795)
#define rk2PI (2*rkPI)
#define rkRadian (rkPI / 180.0)
#define rmMin(a, b) ((a) < (b) ? (a) : (b))
#define rmMax(a, b) ((a) > (b) ? (a) : (b))
#define rmABS(a) ((a) < 0 ? (-(a)) : (a))
#define rmSquare(a) ((a) * (a))
#define rmMedOf3(a, b, c)
#define rmMaxOf3(a, b, c) (rmMax(rmMax(a, b), c))
#define rmMinOf3(a, b, c) (rmMin(rmMin(a, b), c))
#define rmSGN(a) (((a) < 0) ? -1 : 1)
#define rmLimit(a, b, c) (rmMin((rmMax((a),(c))),(b)))
#define rmMakeUnit(T, U)
#define rmAngularUnitIntRange(T) (2. * ((unsigned)1 << (8 * sizeof(T) - 1)))
#define rmAngularUnitFloatFromAny(dst, src, dstRange, srcRange)
#define rmAngularUnitIntFromFloat(dst, src, dstT, srcRange)
#define rmAngularUnitIntFromSmaller(dst, src, dstT, srcT)
#define rmAngularUnitIntFromBigger(dst, src, dstT, srcT)
#define rmAngularUnitFloatFloat(aType, bType, aRange, bRange)
#define rmAngularUnitFloatInt(fUnit, bUnit, fRange, bType)
#define rmAngularUnitIntInt(smallUnit, bigUnit, smallType, bigType)
Functions
template<typename T >
int interpol_left (const T *begin, int len, const T &val)
Returns an index to the left of two interpolation values.
template<typename T >
int interpol_nearest (const T *begin, int len, const T &val)
Returns an index to the nearest interpolation value.
bool rfIsPowerOf2 (uint32)
template<class T >
T rfSqr (T x)
bool rfRealEq (double x, double y, double epsilon=1.e-15)
bool rfRealEq (float x, float y, float epsilon=1.e-10)
template<class T >
T rfSigmoid (T x)
template<class T >
T rfNormPositiveSigmoid (T x)
template<class T >
bool rfQuadradic (T a, T b, T c, T &pos, T &neg)
int32 rfFxAtan2 (int32 x, int32 y)
void rfFxUnitVec (int32 *cos, int32 *sin, int32 theta)
void rfFxRotate (int32 *argx, int32 *argy, int32 theta)
void rfFxPolarize (int32 *argx, int32 *argy)
template<class S , class D >
D rfRoundPlus (S val, D)
template<class S , class D >
D rfRound (S val, D)
int32 rfRoundPlus (double val, int32)
int32 rfRoundPlus (float val, int32)
int32 rfRoundNeg (double val, int32)
int32 rfRoundNeg (float val, int32)
int32 rfRound (double val, int32 Dummy)
int32 rfRound (float val, int32 Dummy)
int32 rfiDiv (int32 x, int32 y)
int32 rfiFloor (int x, int y)
int32 rfiCeil (int x, int y)
bool rfRealEq (rcRadian x, rcRadian y, rcRadian epsilon=rcRadian(1.e-15))
rcRadian arccos (double x)
rcRadian arcsin (double x)
rcRadian arctan (double x)
rcRadian arctan (double y, double x)
double sin (rcRadian x)
double cos (rcRadian x)
double tan (rcRadian x)
rcRadian abs (rcRadian x)
rcDegree abs (rcDegree x)
int32 rfLog2max (int32 n)
int32 rfGCDeuclid (int32 a, int32 b)
template<typename T >
int32 rcNearbyint (const T &d)
Variables
const int32 rcFxPrecision = 16
const int32 rcFixed16Precision = 8
Macro Definition Documentation
#define rk2PI (2*rkPI)
Definition at line 59 of file rc_math.h.
#define rkPI (3.1415926535897932384626433832795)
Definition at line 58 of file rc_math.h.
#define rkRadian (rkPI / 180.0)
Definition at line 60 of file rc_math.h.
#define rmABS (a) ((a) < 0 ? (-(a)) : (a))
Definition at line 65 of file rc_math.h.
Referenced by abs(), rcImageCanvasGL::drawModelRect(), generateExpansionMovie(), generateRandomMovie(), generateTranslationMovie(), rc2Xform::invMapArea(), rcInfLine::isParallel(), rcImageCanvasGL::keyPressEvent(), rc2Xform::mapArea(), rcShape::peakDetect1d(), rcVisualFunction::predictedTolerance(), rfDrawLine(), rfGCDeuclid(), rfRealEq(), sobelEdgeProcess(), rcImageCanvasGL::statusString(), rcHistoStats::stretchMapUs(), rcInfLine::toPoint(), and rcVisualTarget::update().
#define rmAngularUnitFloatFloat (aType, bType, aRange, bRange)
Value:
rmAngularUnitFloatFromAny (aType, bType, aRange, bRange)                \
  rmAngularUnitFloatFromAny (bType, aType, bRange, aRange)
Definition at line 346 of file rc_math.h.
#define rmAngularUnitFloatFromAny (dst, src, dstRange, srcRange)
Value:
inline dst::dst (src x)                             \
{                                       \
  val = x.Double() * ((dstRange) / (srcRange));                 \
}
Definition at line 321 of file rc_math.h.
#define rmAngularUnitFloatInt (fUnit, bUnit, fRange, bType)
Value:
rmAngularUnitFloatFromAny (fUnit, bUnit, fRange, rmAngularUnitIntRange(bType))      \
  rmAngularUnitIntFromFloat (bUnit, fUnit, bType, fRange)
Definition at line 350 of file rc_math.h.
#define rmAngularUnitIntFromBigger (dst, src, dstT, srcT)
Value:
inline dst::dst (src x)                             \
{                                       \
  val = (dstT) ((x.basic() + (1 << (8 * (sizeof(srcT) - sizeof(dstT)) - 1)))    \
          >> (8 * (sizeof(srcT) - sizeof(dstT))));              \
}
Definition at line 339 of file rc_math.h.
#define rmAngularUnitIntFromFloat (dst, src, dstT, srcRange)
Value:
inline dst::dst (src x)                             \
{                                       \
  val = (dstT) (int) floor(x.Double() * (rmAngularUnitIntRange(dstT)/srcRange) + 0.5);\
}
Definition at line 327 of file rc_math.h.
#define rmAngularUnitIntFromSmaller (dst, src, dstT, srcT)
Value:
inline dst::dst (src x)                             \
{                                       \
  val = (dstT) (x.basic() << (8 * (sizeof(dstT) - sizeof(srcT))));      \
}
Definition at line 333 of file rc_math.h.
#define rmAngularUnitIntInt (smallUnit, bigUnit, smallType, bigType)
Value:
rmAngularUnitIntFromSmaller (bigUnit, smallUnit, bigType, smallType)        \
  rmAngularUnitIntFromBigger  (smallUnit, bigUnit, smallType, bigType)
Definition at line 354 of file rc_math.h.
#define rmAngularUnitIntRange (T) (2. * ((unsigned)1 << (8 * sizeof(T) - 1)))
Definition at line 319 of file rc_math.h.
#define rmLimit (a, b, c) (rmMin((rmMax((a),(c))),(b)))
Definition at line 79 of file rc_math.h.
#define rmMakeUnit (T, U)
Definition at line 200 of file rc_math.h.
#define rmMax (a, b) ((a) > (b) ? (a) : (b))
Definition at line 64 of file rc_math.h.
Referenced by rcVisualFunction::cardiacMeasure(), rcVisualFunction::createIrradianceModel(), rcVisualFunction::direct(), rcRectangle< T >::enclose(), rcOptoKineticImage::genEightBitImg(), rcSpatialPyramid< 2 >::gradientProcess(), rcRectangle< T >::intersect(), rcEngineImpl::modelTracker(), rcEngineImpl::muscleTracker(), rcShape::needAffineRect(), rcRectangle< T >::operator&=(), rcRectangle< T >::operator|=(), rcRectangle< T >::overlaps(), rcShape::peakDetect1d(), rcVisualTarget::persistence(), rcVisualFunction::persistence(), rcFeature::polar(), rcVisualFunction::predictedTolerance(), rcKinetoscope::reconcileNewGeneration(), rf1dPeaker(), rfDrawCylinder(), rfGCDeuclid(), rfImagePairMax(), rfPlot1Dsignal(), segment(), rcEngineImpl::setFromArgs(), rcHistoStats::stretchMapUs(), rcVisualTarget::update(), and rcVisualFunction::updateRects().
#define rmMaxOf3 (a, b, c) (rmMax(rmMax(a, b), c))
Definition at line 73 of file rc_math.h.
#define rmMedOf3 (a, b, c)
Value:
((a) > (b) ? ((a) < (c) ? (a) : ((b) < (c) ? (c) : (b))) :    \
 ((a) > (c) ? (a) : ((b) < (c) ? (b) : (c))))
Definition at line 69 of file rc_math.h.
#define rmMin (a, b) ((a) < (b) ? (a) : (b))
Definition at line 63 of file rc_math.h.
Referenced by rcVisualFunction::cardiacUpdate(), rcWindow::copyPixelsFromWindow(), rcVisualFunction::direct(), rcVisualFunction::dividingProcess(), rcRectangle< T >::enclose(), rcOptoKineticImage::genEightBitImg(), genSignatureFromMov(), rcRectangle< T >::intersect(), rcEngineImpl::loadMovie(), rcWindow::maxTrim(), rcShape::needAffineRect(), rcRectangle< T >::operator&=(), rcRectangle< T >::operator|=(), rcRectangle< T >::overlaps(), rcShape::peakDetect1d(), rcEdgeTables::rcEdgeTables(), rcSpatialPyramid< 2 >::rcSpatialPyramid(), rf1dPeaker(), rf1dSignalIntersection(), rfDrawCylinder(), rfGCDeuclid(), rfImagePairMin(), rfPlot1Dsignal(), segment(), rcEngineImpl::setFromArgs(), rcKinetoscope::temporalResults(), rcVisualFunction::updateRects(), rcVisualFunction::updateSims(), and rcImageCanvasGL::zoomToRect().
#define rmMinOf3 (a, b, c) (rmMin(rmMin(a, b), c))
Definition at line 75 of file rc_math.h.
#define rmSGN (a) (((a) < 0) ? -1 : 1)
Definition at line 77 of file rc_math.h.
Referenced by rfDrawLine().
#define rmSquare (a) ((a) * (a))
Definition at line 66 of file rc_math.h.
Referenced by rcMatrix< 2 >::aspect(), rcMatrix_2d::aspect(), rcEllipse::boundingOrthRectangle(), rcPolygon::circularity(), rcSimilarator::distance(), rc2dVector< T >::distanceSquared(), rcPolygon::ellipseRatio(), rcLsFit< T >::fit(), rcOptoKineticImage::genLogRMS(), rcMathematicalImage::mMakeImage(), rcEdgeTables::rcEdgeTables(), rf1DdistanceHistogram(), rf1dSignalNormEuclideanIntersection(), rfQuadradic(), rfRevRMS(), rfRMS(), rfSurfaceHessian(), rcMatrix< 2 >::scale(), rcMatrix_2d::scale(), segment(), rcVisualTarget::speed(), rcVisualFunction::update(), rcMatrix< 2 >::xScale(), rcMatrix_2d::xScale(), rcMatrix< 2 >::yScale(), and rcMatrix_2d::yScale().
Function Documentation
rcRadian abs (rcRadian x) inline
Definition at line 378 of file rc_math.h.
References rcRadian::Double(), and rmABS.
 { return rcRadian (rmABS (x.Double()));}
rcDegree abs (rcDegree x) inline
Definition at line 379 of file rc_math.h.
References rcDegree::Double(), and rmABS.
 { return rcDegree (rmABS (x.Double()));}
rcRadian arccos (double x) inline
Definition at line 369 of file rc_math.h.
 { return rcRadian (acos (x));}
rcRadian arcsin (double x) inline
Definition at line 370 of file rc_math.h.
 { return rcRadian (asin (x));}
rcRadian arctan (double x) inline
Definition at line 371 of file rc_math.h.
Referenced by rcMathematicalImage::mMakeField(), rcMatrix< 2 >::rotation(), rcMatrix_2d::rotation(), and rcAffineWindow::vImageTransform().
 { return rcRadian (atan (x));}
rcRadian arctan (double y, double x) inline
Definition at line 372 of file rc_math.h.
References atan2().
 { return rcRadian(atan2(y, x));}
double cos (rcRadian x) inline
Definition at line 375 of file rc_math.h.
References rcRadian::Double().
Referenced by rcInfLine::angle(), rcEllipse::boundingOrthRectangle(), rcLsFit< T >::error(), rcOptoKineticImage::genLogRMS(), InitFFTSinCos(), rc2Xform::mapAngle(), rc2dVector< float >::rc2dVector(), rcCosTable::rcCosTable(), rcDrawLine(), rcFeature::rcFeature(), rcLineSegment< T >::rcLineSegment(), rcMatrix< 2 >::rcMatrix(), rcMatrix_2d::rcMatrix_2d(), rcPolygon::rcPolygon(), rf1Ddft(), rf1DFourierAnalysis(), rf1DFourierAnalysisVoxels(), rcLsFit< T >::solve3p(), rcEllipse::unit(), rcVisualFunction::update(), LLSQ::vector_fit(), and rcAffineWindow::vImageTransform().
 { return cos (x.Double());}
template<typename T > int interpol_left (const T * begin, int len, const T & val) inline
Returns an index to the left of two interpolation values.
begin points to an array containing a sequence of values sorted in ascending order. The length of the array is len. If val is lower than the first element, 0 is returned. If val is higher than the last element, len-2 is returned. Else, the index of the largest element smaller than val is returned.
Definition at line 31 of file rc_math.h.
Referenced by interpol_nearest().
 {
   const T *end = begin+len;
   const T *iter = std::lower_bound (begin, end, val);
   if (iter==begin) return 0;
   if (iter==end) return len-2;
   return (iter-begin)-1;
 }
template<typename T > int interpol_nearest (const T * begin, int len, const T & val) inline
Returns an index to the nearest interpolation value.
begin points to an array containing a sequence of values sorted in ascending order. The length of the array is len. If val is lower than the first element, 0 is returned. If val is higher than the last element, len-1 is returned. Else, the index of the nearest element within the sequence of values is returned.
Definition at line 48 of file rc_math.h.
References interpol_left().
 {
   int left = interpol_left(begin, len, val);
   T delleft = val-(*(begin+left));
   T delright = (*(begin+left+1))-val;
   if (delright<0) return left+1;
   return (delright<delleft) ? (left+1) : left;
 }
template<typename T > int32 rcNearbyint (const T & d)
Definition at line 402 of file rc_math.h.
References abs(), and rmAssert.
 {
   int32 z = int32 (d);
   T frac = d - z;
   rmAssert (abs(frac) < T(1.0));
   if (frac > 0.5)
     ++z;
   else if (frac < -0.5)
     --z;
   else if (frac == 0.5 && (z&1) != 0) // NB: We also need the round-to-even rule.
     ++z;
   else if (frac == -0.5 && (z&1) != 0)
     --z;
   rmAssert (abs(T(z) - d) < T(0.5) ||
                  (abs(T(z) - d) == T(0.5) && ((z&1) == 0)));
   return z;
 }
int32 rfFxAtan2 (int32 x, int32 y)
Definition at line 307 of file rc_fixcord.cpp.
References FxPreNorm(), and PseudoPolarize().
 {
     if ((x == 0) && (y == 0))
         return(0);
 #ifndef FASTER
     FxPreNorm(&x, &y);  /* Prenormalize vector for maximum precision */
 #endif FASTER
     PseudoPolarize(&x, &y); /* Convert to polar coordinates */
     return(y);
 }
void rfFxPolarize (int32 * argx, int32 * argy)
Definition at line 319 of file rc_fixcord.cpp.
References COSCALE, FFracMul(), FxPreNorm(), and PseudoPolarize().
Referenced by rcFeature::octants(), and rcFeature::polar().
 {
 #ifndef FASTER
     int shiftexp;
 #endif FASTER
     if ((*argx == 0) && (*argy == 0)) {
         return;
     }
 #ifndef FASTER
     /* Prenormalize vector for maximum precision */
     shiftexp = FxPreNorm(argx, argy);
 #endif FASTER
     /* Perform CORDIC conversion to polar coordinates */
     PseudoPolarize(argx, argy);
     /* Scale radius to undo pseudorotation enlargement factor */
     *argx = FFracMul(*argx, COSCALE);
 #ifndef FASTER
     /* Denormalize radius */
     *argx = (shiftexp < 0) ? (*argx >> -shiftexp) : (*argx << shiftexp);
 #endif FASTER
 }
void rfFxRotate (int32 * argx, int32 * argy, int32 theta)
Definition at line 279 of file rc_fixcord.cpp.
References COSCALE, FFracMul(), FxPreNorm(), and PseudoRotate().
 {
 #ifndef FASTER
     int shiftexp;
 #endif FASTER
     if (((*argx == 0) && (*argy == 0)) || (theta == 0))
         return;
 #ifndef FASTER
     shiftexp = FxPreNorm(argx, argy);  /* Prenormalize vector */
 #endif FASTER
     PseudoRotate(argx, argy, theta);   /* Perform CORDIC pseudorotation */
     *argx = FFracMul(*argx, COSCALE);   /* Compensate for CORDIC enlargement */
     *argy = FFracMul(*argy, COSCALE);
 #ifndef FASTER
     if (shiftexp < 0) {     /* Denormalize vector */
         *argx >>= -shiftexp;
         *argy >>= -shiftexp;
     }
     else {
         *argx <<= shiftexp;
         *argy <<= shiftexp;
     }
 #endif FASTER
 }
void rfFxUnitVec (int32 * cos, int32 * sin, int32 theta)
Definition at line 270 of file rc_fixcord.cpp.
References COSCALE, and PseudoRotate().
 {
     *cos = COSCALE;
     *sin = 0;
     PseudoRotate(cos, sin, theta);
 }
int32 rfGCDeuclid (int32 a, int32 b)
Definition at line 169 of file rc_units.cpp.
References rmABS, rmMax, and rmMin.
  {
    /* Returns the greatest common divisor of u and v by Euclid's method.
     * I have experimented also with Stein's method, which involves only
     * subtraction and left/right shifting; Euclid is faster, both for
     * integers of size 0 - 1024 and also for random integers of a size
     * which fits in a long integer.  Stein's algorithm might be better
     * when the integers are HUGE, but for our purposes, Euclid is fine.
     *
     * Walter H. F. Smith, 25 Feb 1992, after D. E. Knuth, vol. II  */
    int32 u,v,r;
    u = rmMax (rmABS(a), rmABS(b));
    v = rmMin (rmABS(a), rmABS(b));
    while (v > 0) {
      r = u%v;    /* Knuth notes that u < 2v 40% of the time;  */
      u = v;      /* thus we could have tried a subtraction  */
      v = r;      /* followed by an if test to do r = u%v  */
    }
    return(u);
  }
int32 rfiCeil (int x, int y) inline
Definition at line 177 of file rc_math.h.
References abs().
 {
   return (x < 0 ? x : x + abs(y) - 1) / y * y;
 }
int32 rfiDiv (int32 x, int32 y) inline
Definition at line 167 of file rc_math.h.
References abs().
Referenced by rfiFloor().
 {
   return (x >= 0 ? x : x - abs(y) + 1) / y;
 }
int32 rfiFloor (int x, int y) inline
Definition at line 172 of file rc_math.h.
References rfiDiv().
 {
   return rfiDiv (x, y) * y;
 }
bool rfIsPowerOf2 (uint32)
int32 rfLog2max (int32 n)
Definition at line 48 of file rc_units.cpp.
 {
   int32 power = 1;
   int32 k = 1;
   if (n==1) {
     return 0;
   }
   while ((k <<= 1) < n) {
     power++;
   }
   return power;
 }
template<class T > T rfNormPositiveSigmoid (T x)
Definition at line 99 of file rc_math.h.
References rfSigmoid().
 {
   // Transform x [0 1] to [-1 1]
   T xp = x + x + (T) (-1);
   xp = rfSigmoid (xp);
   // Transform [-1 1] back to [0 1]
   xp = (xp + 1) / (T) 2;
   return xp;
 }
template<class T > bool rfQuadradic (T a, T b, T c, T & pos, T & neg)
Definition at line 113 of file rc_math.h.
References rmSquare.
 {
   T det = rmSquare (b) - (4 * a * c);
   if (a == T (0))
     {
       pos = -c / b;
       neg = -c / b;
       return true;
     }
   if (det >= 0)
     {
       pos = (-b + sqrt (det)) / (2*a);
       neg = (-b - sqrt (det)) / (2*a);
       return true;
     }
   return false;
 }
bool rfRealEq (double x, double y, double epsilon = 1.e-15) inline
Definition at line 86 of file rc_math.h.
References rmABS.
 {return rmABS (x - y) <= epsilon;}
bool rfRealEq (float x, float y, float epsilon = 1.e-10) inline
Definition at line 89 of file rc_math.h.
References rmABS.
 {return rmABS (x - y) <= epsilon;}
bool rfRealEq (rcRadian x, rcRadian y, rcRadian epsilon = rcRadian(1.e-15))
Definition at line 64 of file rc_units.cpp.
References abs().
Referenced by rcVisualFunction::beatProcess(), rcVisualFunction::dividingProcess(), rcInfLine::intersect(), rc2dVector< float >::isLenNull(), rc2dVector< float >::isNull(), rcVisualFunction::measure(), rcKinetoscope::newGeneration(), parabolicFit(), rcVisualFunction::populationMigration(), and rfRealEq().
 {
   return abs((x - y).normSigned()) <= epsilon;
 }
template<class S , class D > D rfRound (S val, D) inline
Definition at line 148 of file rc_math.h.
Referenced by rcVisualFunction::cardiacMeasure(), rcVisualFunction::createIrradianceModel(), rcImageCanvasGL::findCellPositionTracks(), rcAnalyzer::getNextResult(), rcImageCanvasGL::mouseReleaseEvent(), rcFeature::rcFeature(), rfCtfDiff1d(), rfRegisteredWindows(), rfRoundRectangle(), and rcVisualFunction::roundRectangle().
 { return D(val); }
int32 rfRound (double val, int32 Dummy) inline
Definition at line 156 of file rc_math.h.
References rfRoundPlus().
 {
   return val < 0 ? -rfRoundPlus(-val, Dummy) : rfRoundPlus(val, Dummy);
 }
int32 rfRound (float val, int32 Dummy) inline
Definition at line 161 of file rc_math.h.
References rfRoundPlus().
 {
   return val < 0 ? -rfRoundPlus(-val, Dummy) : rfRoundPlus(val, Dummy);
 }
int32 rfRoundNeg (double val, int32) inline
Definition at line 153 of file rc_math.h.
Referenced by rcVisualTarget::update().
 { return int32(val -  0.5); }
int32 rfRoundNeg (float val, int32) inline
Definition at line 154 of file rc_math.h.
 { return int32(val - 0.5); }
template<class S , class D > D rfRoundPlus (S val, D) inline
Definition at line 145 of file rc_math.h.
Referenced by rcVisualFunction::framesPerPeriod(), rcPolygon::genMinEnclosingRect(), rfRound(), and rcVisualTarget::update().
 { return D(val); }
int32 rfRoundPlus (double val, int32) inline
Definition at line 150 of file rc_math.h.
 { return int32(val + 0.5); }
int32 rfRoundPlus (float val, int32) inline
Definition at line 151 of file rc_math.h.
 { return int32(val + 0.5); }
template<class T > T rfSigmoid (T x)
Definition at line 93 of file rc_math.h.
Referenced by rfNormPositiveSigmoid().
 {
   return ((T) 1.0)/((T) 1.0 + exp(-x));
 }
template<class T > T rfSqr (T x) inline
Definition at line 84 of file rc_math.h.
 {return x*x;}
double sin (rcRadian x) inline
Definition at line 374 of file rc_math.h.
References rcRadian::Double().
Referenced by rcInfLine::angle(), rcEllipse::boundingOrthRectangle(), rcLsFit< T >::error(), fft_real_forward_scalar(), fft_real_inverse_scalar(), InitFFTSinCos(), MakeSineTab(), rc2Xform::mapAngle(), rc2dVector< float >::rc2dVector(), rcDrawLine(), rcFeature::rcFeature(), rcLineSegment< T >::rcLineSegment(), rcMatrix< 2 >::rcMatrix(), rcMatrix_2d::rcMatrix_2d(), rcPolygon::rcPolygon(), rcSinTable::rcSinTable(), rf1Ddft(), rcLsFit< T >::solve3p(), rcEllipse::unit(), LLSQ::vector_fit(), and rcAffineWindow::vImageTransform().
 { return sin (x.Double());}
double tan (rcRadian x) inline
Definition at line 376 of file rc_math.h.
References rcRadian::Double().
Referenced by rcMatrix_2d::rcMatrix_2d(), rfHSI2RGB(), and rcEllipse::unit().
 { return tan (x.Double());}
Variable Documentation
const int32 rcFixed16Precision = 8
Definition at line 300 of file rc_math.h.
Referenced by rcFeature::rcFeature(), and rcFixed16::real().
const int32 rcFxPrecision = 16
Definition at line 136 of file rc_math.h.