Visible: include/visual/rc_dcam.h File Reference
rc_dcam.h File Reference
#include <iostream>
#include <vector>
#include <ASC_DCAM_DEV/ASC_DCAM_API.h>
#include <rc_types.h>
#include <rc_framebuf.h>
#include <rc_vector2d.h>
#include <boost/tuple/tuple.hpp>
#include <boost/dynamic_bitset.hpp>
Classes
class rcCameraFormat
class rcCameraProperty
Enumerations
enum rcCameraColorFormat {
rcCameraColorFormatUnknown = 0, rcCameraColorFormatYUV444, rcCameraColorFormatYUV422, rcCameraColorFormatYUV411,
rcCameraColorFormatRGB24, rcCameraColorFormatGray8, rcCameraColorFormatGray16
}
Functions
std::string dcam_cntlName (int type)
static std::string dcam_propertyName (int type)
rcCameraProperty rfGetCameraProperty (void *cameraPtr, UInt32 type, UInt32 cntl)
int rfGetCameraProperties (void *cameraPtr, vector< rcCameraProperty > &properties)
double rfGetCameraMaxFrameRate (void *cameraPtr)
OSStatus rfGetCameraCapabilities (void *cameraPtr, CameraCapabilitiesStruct &capabilities)
OSStatus rfGetCameraInformation (void *cameraPtr, const CameraCapabilitiesStruct &capabilities, rcMovieFileCamExt &info)
ostream & operator<< (ostream &os, const dcamCameraListStruct &cam)
ostream & operator<< (ostream &os, const CameraCapabilitiesStruct &cap)
Enumeration Type Documentation
enum rcCameraColorFormat
Enumerator
rcCameraColorFormatUnknown
rcCameraColorFormatYUV444
rcCameraColorFormatYUV422
rcCameraColorFormatYUV411
rcCameraColorFormatRGB24
rcCameraColorFormatGray8
rcCameraColorFormatGray16
Definition at line 33 of file rc_dcam.h.
 {
     rcCameraColorFormatUnknown = 0,
     rcCameraColorFormatYUV444,
     rcCameraColorFormatYUV422,
     rcCameraColorFormatYUV411,
     rcCameraColorFormatRGB24,
     rcCameraColorFormatGray8,
     rcCameraColorFormatGray16
 };
Function Documentation
std::string dcam_cntlName (int type)
Definition at line 248 of file rc_dcam.cpp.
Referenced by operator<<(), and setProperty().
 {
     switch ( type ) {
         case MANUAL_CNTL:
             return "Manual";
         case AUTO_CNTL:
             return "Auto";
         case ON_OFF_CNTL:
             return "On-off";
         case ONE_PUSH_CNTL:
             return "One-push";
         case U_OR_B_CNTL:
             return "U-B";
         case V_OR_R_CNTL:
             return "V-R";
         case TARGET_TEMP_CNTL:
             return "Target";
         case CURR_TEMP_CNTL:
             return "Curr";
         case TRIG_POLARITY_CNTL:
             return "Polarity";
         case TRIG_MODE_CNTL:
             return "Mode";
         case TRIG_PARAM_CNTL:
             return "Param";
     }
     return "Unknown control";
 }
static std::string dcam_propertyName (int type) static
ostream& operator<< (ostream & os, const dcamCameraListStruct & cam)
Definition at line 427 of file rc_dcam.cpp.
References endl().
 {
     os << "Camera name: " << (char*)&cam.deviceName
     << " MFGID: " << cam.manufacturerID << " UID: " << cam.uniqueID
     << " InUse: " << (cam.isInUse? "1" : "0") << endl;
     return os;
 }
ostream& operator<< (ostream & os, const CameraCapabilitiesStruct & cap)
OSStatus rfGetCameraCapabilities (void * cameraPtr, CameraCapabilitiesStruct & capabilities)
Definition at line 222 of file rc_dcam.cpp.
References rcCameraProperty::active(), count(), rfGetCameraProperties(), rfSetCapability(), and rcCameraProperty::type().
Referenced by InitializeMungData2().
 {
     OSStatus err = ASCDCAMGetCameraProperties( cameraPtr, &capabilities );
     // Unfortunately these propertiers cannot be fully trusted:
     // some cameras offer capabilities not returned here.
     // Find capabilities by brute force search.
     vector<rcCameraProperty> props;
     int count = rfGetCameraProperties( cameraPtr, props );
     if ( count > 0 ) {
         for ( uint32 i = 0; i < props.size(); ++i ) {
             const rcCameraProperty& p = props[i];
             if ( p.active() ) {
                 rfSetCapability( capabilities, p.type() );
             }
         }
     }
     return err;
 }
OSStatus rfGetCameraInformation (void * cameraPtr, const CameraCapabilitiesStruct & capabilities, rcMovieFileCamExt & info)
Definition at line 402 of file rc_dcam.cpp.
References rcCameraProperty::active(), count(), rfGetCameraProperties(), setProperties(), and setProperty().
Referenced by InitializeMungData2().
 {
     setProperties( info, capabilities );
     // Find capabilities by brute force search.
     vector<rcCameraProperty> props;
     int count = rfGetCameraProperties( cameraPtr, props );
     if ( count > 0 ) {
         for ( uint32 i = 0; i < props.size(); ++i ) {
             const rcCameraProperty& p = props[i];
             if ( p.active() ) {
                 setProperty( info, p );
             }
         }
     }
     return noErr;
 }
double rfGetCameraMaxFrameRate (void * cameraPtr)
Definition at line 173 of file rc_dcam.cpp.
References endl().
Referenced by InitializeMungData2().
 {
     double maxFrameRate = 0.0;
     CameraCapabilitiesStruct cap;
     OSStatus err = ASCDCAMGetCameraProperties(cameraPtr, &cap);
     if ( err !=0 ) return -1.0;
     // Populate possible framerates for format0,1,2 according to Table in DCAM documentation
     for ( short mode = 0; mode < 3; ++mode )
     {
         const short start = mode * 6;
         double framerate = 1.875;
         double cur = 0.0;
         for ( short i = start; i < start+6; ++i )
         {
             if ( mode == 0 ) {
                 if ( cap.format0ModesFrameRates[i] == true )
                     cur = framerate;
             } else if ( mode == 1 )
             {
                 if ( cap.format1ModesFrameRates[i] == true )
                     cur = framerate;
             } else if ( mode == 2 )
             {
                 if ( cap.format2ModesFrameRates[i] == true )
                     cur = framerate;
             }
             framerate *= 2.0;
         }
         if ( cur > maxFrameRate )
             maxFrameRate = cur;
     }
     // If we have format 7. This is camera specific. So we need it from some place @todo
     if (cap.format7)
     {
         maxFrameRate = std::max (60.0, maxFrameRate);
     }
     else
     {
         cerr << "ASCDCAMGetCameraProperties error " << err << endl;
     }
     return maxFrameRate;
 }
int rfGetCameraProperties (void * cameraPtr, vector< rcCameraProperty > & properties)
Definition at line 139 of file rc_dcam.cpp.
References GetCameraProperty(), and rmAssert.
Referenced by rfGetCameraCapabilities(), and rfGetCameraInformation().
 {
     rmAssert( properties.empty() );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_BRIGHTNESS_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_EXPOSURE_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_SHARPNESS_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_WHITE_BAL_REG, U_OR_B_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_WHITE_BAL_REG, V_OR_R_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_HUE_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_SATURATION_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_GAIN_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_GAMMA_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_SHUTTER_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_IRIS_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_FOCUS_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_TEMPERATURE_REG, TARGET_TEMP_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_TEMPERATURE_REG, CURR_TEMP_CNTL ) );
 #ifdef notyet
     // TODO: Sony cameras return an error for this, investigate
     properties.push_back( GetCameraProperty( cameraPtr, ASC_TRIGGER_REG, TRIG_POLARITY_CNTL ) );
 #endif
     properties.push_back( GetCameraProperty( cameraPtr, ASC_TRIGGER_REG, TRIG_MODE_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_TRIGGER_REG, TRIG_PARAM_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_ZOOM_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_PAN_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_TILT_REG, MANUAL_CNTL ) );
     properties.push_back( GetCameraProperty( cameraPtr, ASC_OPTICAL_FILTER_REG, MANUAL_CNTL ) );
     return properties.size();
 }
rcCameraProperty rfGetCameraProperty (void * cameraPtr, UInt32 type, UInt32 cntl)