Visible: src/analysis/code/rc_visualtarget.cpp File Reference
rc_visualtarget.cpp File Reference
#include <rc_kinetoscope.h>
#include <rc_math.h>
#include <rc_fit.h>
#include <iomanip>
#include <rc_visualtarget.h>
Functions
ostream & operator<< (ostream &o, const rcVisualTarget &p)
Function Documentation
ostream& operator<< (ostream & o, const rcVisualTarget & p)
Definition at line 170 of file rc_visualtarget.cpp.
References rcBaseMotionPath::anchor(), rcVisualTarget::area(), rcVisualTarget::distance(), endl(), rcVisualTarget::mId, rcVisualTarget::persistence(), rcBaseMotionPath::position(), rcVisualTarget::rectSnaps(), rcVisualTarget::rmsQuality(), rcVisualTarget::speed(), and rcVisualTarget::velocity().
 {
   o << "====> Target   : " << p.mId << "<=======" << endl;
   o << "Trace        :" << p.anchor() << endl;
   o << "Area         :" << p.area() << endl;
   o << "Distance     :" << p.distance() << endl;
   o << "Persistance  :" << p.persistence() << endl;
   o << "Anchor       :" << p.anchor() << endl;
   o << "Position     :" << p.position () << endl;
   o << "Velocity     :" << p.velocity() << endl;
   o << "Speed        :" << p.speed() << endl;
   o << "Mean Quality : " << p.rmsQuality() << endl;
 #if 0
   deque<rcIRect>::const_iterator rq = p.rectSnaps().begin();
   int q = 0;
   for (; rq != p.rectSnaps().end(); rq++, q++)
     cout << "[" << q << ":" << *rq << "]";
 #endif
   return o;
 }