Visible: src/visual/code/rc_videocache.cpp File Reference
rc_videocache.cpp File Reference
#include <rc_systeminfo.h>
#include <rc_videocache.h>
#include <stdio.h>
Classes
struct traceInfo
Macros
#define VID_TRACE
#define ByteSwapN(x) ByteSwap((unsigned char *) &x,sizeof(x))
Typedefs
typedef struct traceInfo traceInfo
Enumerations
enum fctName {
fnGetFrameI = 0, fnGetFrameT, fnInternalGetFrame, fnCacheAlloc,
fnCacheInsert, fnUnlockFrame
}
Functions
static void ByteSwap (unsigned char *b, int n)
static void fixEndian (int64 &time)
void vcAddTrace (fctName name, bool enter, uint32 frameIndex, rcFrame *fp, uint32 dToken)
void vcDumpTrace ()
Variables
static const uint32 traceSz = 1000
static traceInfo traceBuf [traceSz]
static uint32 traceIndex = 0
static uint32 traceCount = 0
static rcMutex traceMutex
static uint32 tracePrint = 0
Macro Definition Documentation
#define ByteSwapN (x) ByteSwap((unsigned char *) &x,sizeof(x))
Definition at line 10 of file rc_videocache.cpp.
Referenced by fixEndian().
#define VID_TRACE
Definition at line 7 of file rc_videocache.cpp.
Typedef Documentation
typedef struct traceInfo traceInfo
Enumeration Type Documentation
enum fctName
Enumerator
fnGetFrameI
fnGetFrameT
fnInternalGetFrame
fnCacheAlloc
fnCacheInsert
fnUnlockFrame
Definition at line 33 of file rc_videocache.cpp.
              {
     fnGetFrameI = 0,
     fnGetFrameT,
     fnInternalGetFrame,
     fnCacheAlloc,
     fnCacheInsert,
     fnUnlockFrame
 };
Function Documentation
static void ByteSwap (unsigned char * b, int n) static
Definition at line 12 of file rc_videocache.cpp.
 {
    register int i = 0;
    register int j = n-1;
    while (i<j)
    {
       std::swap(b[i], b[j]);
       i++, j--;
    }
 }
static void fixEndian (int64 & time) static
Definition at line 24 of file rc_videocache.cpp.
References ByteSwapN, eByteOrderBigEndian, and rfPlatformByteOrder().
Referenced by rcVideoCache::internalGetFrame(), rcVideoCache::tocLoadFromFrames(), and rcVideoCache::tocLoadFromTOC().
 {
     if ( rfPlatformByteOrder() !=  eByteOrderBigEndian) {
         ByteSwapN (time);
     }
 }
void vcAddTrace (fctName name, bool enter, uint32 frameIndex, rcFrame * fp, uint32 dToken)
Definition at line 57 of file rc_videocache.cpp.
References traceInfo::dToken, traceInfo::enter, traceInfo::fp, traceInfo::frameIndex, traceInfo::name, traceCount, traceIndex, and traceSz.
 {
     rcLock lock(traceMutex);
     if (traceIndex == traceSz)
         traceIndex = 0;
     traceBuf[traceIndex].name = name;
     traceBuf[traceIndex].dToken = dToken;
     traceBuf[traceIndex].enter =enter;
     traceBuf[traceIndex].frameIndex = frameIndex;
     traceBuf[traceIndex].fp = fp;
     traceIndex++; traceCount++;
 }
void vcDumpTrace ()
Definition at line 74 of file rc_videocache.cpp.
References fnCacheAlloc, fnCacheInsert, fnGetFrameI, fnGetFrameT, fnInternalGetFrame, fnUnlockFrame, traceCount, traceIndex, tracePrint, and traceSz.
 {
     rcLock lock(traceMutex);
     if (tracePrint)
         return;
     tracePrint = 1;
     fprintf(stderr, "trace count %d\n", traceCount);
     uint32 printCount = traceCount < traceSz ? traceCount : traceSz;
     uint32 myIndex = traceCount == traceSz ? traceIndex : 0;
     if (printCount)
         fprintf(stderr,
                 "  Token    Name             Enter    frameIndex   frame ptr\n");
     for ( ; printCount; printCount--) {
         if (myIndex == traceSz)
             myIndex = 0;
         char* name = 0;
         switch (traceBuf[myIndex].name) {
             case fnGetFrameI:
                 name = "getFrameI       ";
                 break;
             case fnGetFrameT:
                 name = "getFrameT       ";
                 break;
             case fnInternalGetFrame:
                 name = "internalGetFrame";
                 break;
             case fnCacheAlloc:
                 name = "cacheAlloc      ";
                 break;
             case fnCacheInsert:
                 name = "cacheInsert     ";
                 break;
             case fnUnlockFrame:
                 name = "unlockFrame     ";
                 break;
             default:
                 name = "INVALID         ";
                 break;
         }
         char* enter = "yes";
         if (traceBuf[myIndex].enter == false)
             enter = "NO ";
         fprintf(stderr, " %06d %s     %s        %02d         0x%X\n",
                 traceBuf[myIndex].dToken, name, enter,
                 traceBuf[myIndex].frameIndex, (int)traceBuf[myIndex].fp);
         myIndex++;
     }
 }
Variable Documentation
traceInfo traceBuf[traceSz] static
Definition at line 51 of file rc_videocache.cpp.
uint32 traceCount = 0 static
Definition at line 53 of file rc_videocache.cpp.
Referenced by vcAddTrace(), and vcDumpTrace().
uint32 traceIndex = 0 static
Definition at line 52 of file rc_videocache.cpp.
Referenced by vcAddTrace(), and vcDumpTrace().
rcMutex traceMutex static
Definition at line 54 of file rc_videocache.cpp.
uint32 tracePrint = 0 static
Definition at line 55 of file rc_videocache.cpp.
Referenced by vcDumpTrace().
const uint32 traceSz = 1000 static
Definition at line 50 of file rc_videocache.cpp.
Referenced by vcAddTrace(), and vcDumpTrace().