Visible: src/visual/code/rc_imageprocessing.cpp File Reference
rc_imageprocessing.cpp File Reference
#include <rc_imageprocessing.h>
#include <rc_types.h>
#include <rc_platform.h>
#include <rc_ipconvert.h>
Macros
#define FAST_GEN_MODULUS 32
#define ALTIVEC_MODULUS 16
#define EVEN_MODULUS 2
#define ALT_UNROLL_MODULUS 8
#define ALT_BIG_UNROLL_MODULUS 16
#define CIMP_UNROLL_MODULUS 32
#define VALUE_MODULO(VALUE, MODULUS) (((int)VALUE) & (MODULUS-1))
#define FAST_VALUE_MODULO(VALUE) VALUE_MODULO(VALUE, FAST_GEN_MODULUS)
#define ALTIVEC_VALUE_MODULO(VALUE) VALUE_MODULO(VALUE, ALTIVEC_MODULUS)
#define EVEN_VALUE_MODULO(VALUE) VALUE_MODULO(VALUE, EVEN_MODULUS)
#define ALT_UNROLL_VALUE_MODULO(VALUE) VALUE_MODULO(VALUE, ALT_UNROLL_MODULUS)
#define ALT_BIG_UNROLL_VALUE_MODULO(VALUE) VALUE_MODULO(VALUE, ALT_BIG_UNROLL_MODULUS)
#define CIMP_UNROLL_VALUE_MODULO(VALUE) VALUE_MODULO(VALUE, CIMP_UNROLL_MODULUS)
#define COMPRESS2
#define rmMaxOf3(a, b, c) (rmMax(rmMax(a, b), c))
#define FETCHEXPAND(a, b, c)
Functions
void rcCverGenHalfRes (char *src, char *dest, const uint32 widthInPixels, const uint32 heightInLines, const uint32 rowUpdate, const bool invert)
void rcGenHalfRes (char *src, char *dest, uint32 widthInPixels, uint32 heightInLines, uint32 srcRowUpdate, bool invert)
void rfRcWindow32to8 (const rcWindow &rgbInput, rcWindow &channelOutput, rcChannelConversion opt)
void rfRcWindow32to8 (const vector< rcWindow > &rgb, vector< rcWindow > &channel, rcChannelConversion opt)
void rfWindow8to32 (const rcWindow &rgbInput, rcWindow &rgbOutput)
void rfRcWindow8to32 (const rcWindow &rgbInput, rcWindow &rgbOutput)
void rfReversePixels8 (rcWindow &image)
void rfReversePixels16 (rcWindow &image)
bool rfIsWhiteReversed (const rcWindow &image)
static void rfCverAndImages (const rcWindow &srcWin, const rcWindow &maskWin, rcWindow &destWin)
void rfAndImage (const rcWindow &srcWin, const rcWindow &maskWin, rcWindow &destWin)
static void rfTemporalMedianPixel8 (const vector< rcWindow > &srcWin, rcWindow &destWin)
static void rfTemporalMedianPixel16 (const vector< rcWindow > &srcWin, rcWindow &destWin)
void rfTemporalMedian (const vector< rcWindow > &srcWin, rcWindow &destWin)
void rfMutualChannel (const rcWindow &rgbInput, rcWindow &channelOutput)
Variables
int myfirsttime = 1
static const uint8 sInvertMap [256]
Macro Definition Documentation
#define ALT_BIG_UNROLL_MODULUS 16
Definition at line 12 of file rc_imageprocessing.cpp.
#define ALT_BIG_UNROLL_VALUE_MODULO (VALUE) VALUE_MODULO(VALUE, ALT_BIG_UNROLL_MODULUS)
Definition at line 20 of file rc_imageprocessing.cpp.
#define ALT_UNROLL_MODULUS 8
Definition at line 11 of file rc_imageprocessing.cpp.
#define ALT_UNROLL_VALUE_MODULO (VALUE) VALUE_MODULO(VALUE, ALT_UNROLL_MODULUS)
Definition at line 19 of file rc_imageprocessing.cpp.
#define ALTIVEC_MODULUS 16
Definition at line 9 of file rc_imageprocessing.cpp.
#define ALTIVEC_VALUE_MODULO (VALUE) VALUE_MODULO(VALUE, ALTIVEC_MODULUS)
Definition at line 17 of file rc_imageprocessing.cpp.
Referenced by rcGenHalfRes(), and rfAndImage().
#define CIMP_UNROLL_MODULUS 32
Definition at line 13 of file rc_imageprocessing.cpp.
Referenced by rcCverGenHalfRes().
#define CIMP_UNROLL_VALUE_MODULO (VALUE) VALUE_MODULO(VALUE, CIMP_UNROLL_MODULUS)
Definition at line 21 of file rc_imageprocessing.cpp.
Referenced by rcCverGenHalfRes().
#define COMPRESS2
Value:
{ \
  accum = (unsigned short)se[0] + (unsigned short)se[1] + \
      (unsigned short)so[0] + (unsigned short)so[1];      \
  *d++ = (unsigned char)((accum + 2) >> 2) ^ inv;         \
  se += 2; so += 2; }
Definition at line 59 of file rc_imageprocessing.cpp.
Referenced by rcCverGenHalfRes().
#define EVEN_MODULUS 2
Definition at line 10 of file rc_imageprocessing.cpp.
Referenced by rcCverGenHalfRes().
#define EVEN_VALUE_MODULO (VALUE) VALUE_MODULO(VALUE, EVEN_MODULUS)
Definition at line 18 of file rc_imageprocessing.cpp.
#define FAST_GEN_MODULUS 32
Definition at line 8 of file rc_imageprocessing.cpp.
#define FAST_VALUE_MODULO (VALUE) VALUE_MODULO(VALUE, FAST_GEN_MODULUS)
Definition at line 16 of file rc_imageprocessing.cpp.
Referenced by rcGenHalfRes().
#define FETCHEXPAND (a, b, c)
Value:
if (rmIsAlignedAddr ((a))) \
{\
tt = (vector unsigned char *) (a);\
t0 = tt[0];\
tt = (vector unsigned char *) (b);\
m0 = tt[0];\
tt = (vector unsigned char *) (c);\
b0 = tt[0];\
}\
else \
{\
perm1 = vec_lvsl(0, (a)); \
tt = (vector unsigned char *) (a);\
t0 = vec_perm(tt[0], tt[1], perm1);\
tt = (vector unsigned char *) (b);\
m0 = vec_perm(tt[0], tt[1], perm1);\
tt = (vector unsigned char *) (c);\
b0 = vec_perm(tt[0], tt[1], perm1);\
}\
st0Odd = vec_mulo (sOne, t0);\
st0Even = vec_mule (sOne, t0);\
sm0Odd = vec_mulo (sOne, m0);\
sm0Even = vec_mule (sOne, m0);\
sb0Odd = vec_mulo (sOne, b0);\
sb0Even = vec_mule (sOne, b0)
Definition at line 607 of file rc_imageprocessing.cpp.
#define rmMaxOf3 (a, b, c) (rmMax(rmMax(a, b), c))
Definition at line 311 of file rc_imageprocessing.cpp.
#define VALUE_MODULO (VALUE, MODULUS) (((int)VALUE) & (MODULUS-1))
Definition at line 15 of file rc_imageprocessing.cpp.
Function Documentation
void rcCverGenHalfRes (char * src, char * dest, const uint32 widthInPixels, const uint32 heightInLines, const uint32 rowUpdate, const bool invert)
Definition at line 65 of file rc_imageprocessing.cpp.
References CIMP_UNROLL_MODULUS, CIMP_UNROLL_VALUE_MODULO, COMPRESS2, and EVEN_MODULUS.
Referenced by rcGenHalfRes().
 {
   const uint32 constProcessBlkCnt = widthInPixels / EVEN_MODULUS;
   const int32 constFullBlkCnt = constProcessBlkCnt/CIMP_UNROLL_MODULUS;
   const int32 constBlkRemainder = CIMP_UNROLL_VALUE_MODULO(constProcessBlkCnt);
   const int32 constInitialIndex = constBlkRemainder ? -1 : 0;
   const uint32 constSkipPixelsCnt = 2*rowUpdate - widthInPixels;
   uint8* se = (uint8*)src;
   uint8* so = se + rowUpdate;
   uint8* d = (uint8*)dest;
   uint8 inv = 0; // Assume invert is false
   if (invert)
     inv = 0xFF;
   register uint16 accum;
   for (uint32 y = 0; y < heightInLines/EVEN_MODULUS; y++)
   {
     int32 index = constInitialIndex;
     if (0) // Make warnings about unreachable code go away
       goto compilerPlacebo;
     switch (constBlkRemainder)
     {
     compilerPlacebo:
       for ( ; index < constFullBlkCnt; index++)
       {
       case 0:  // 64 pixels
     COMPRESS2;
       case 31: // 62 pixels
     COMPRESS2;
       case 30: // 60 pixels
     COMPRESS2;
       case 29: // 58 pixels
     COMPRESS2;
       case 28: // 56 pixels
     COMPRESS2;
       case 27: // 54 pixels
     COMPRESS2;
       case 26: // 52 pixels
     COMPRESS2;
       case 25: // 50 pixels
     COMPRESS2;
       case 24: // 48 pixels
     COMPRESS2;
       case 23: // 46 pixels
     COMPRESS2;
       case 22: // 44 pixels
     COMPRESS2;
       case 21: // 42 pixels
     COMPRESS2;
       case 20: // 40 pixels
     COMPRESS2;
       case 19: // 38 pixels
     COMPRESS2;
       case 18: // 36 pixels
     COMPRESS2;
       case 17: // 34 pixels
     COMPRESS2;
       case 16: // 32 pixels
     COMPRESS2;
       case 15: // 30 pixels
     COMPRESS2;
       case 14: // 28 pixels
     COMPRESS2;
       case 13: // 26 pixels
     COMPRESS2;
       case 12: // 24 pixels
     COMPRESS2;
       case 11: // 22 pixels
     COMPRESS2;
       case 10: // 20 pixels
     COMPRESS2;
       case 9:  // 18 pixels
     COMPRESS2;
       case 8:  // 16 pixels
     COMPRESS2;
       case 7:  // 14 pixels
     COMPRESS2;
       case 6:  // 12 pixels
     COMPRESS2;
       case 5:  // 10 pixels
     COMPRESS2;
       case 4:  // 8 pixels
     COMPRESS2;
       case 3:  // 6 pixels
     COMPRESS2;
       case 2:  // 4 pixels
     COMPRESS2;
       case 1:  // 2 pixels
     COMPRESS2;
       } // End of: for ( ; index < constFullBlkCnt; index++)
     } // End of: switch (constBlkRemainder)
     se += constSkipPixelsCnt;
     so += constSkipPixelsCnt;
   } // End of: for (uint32 y = 0; y < heightInLines/EVEN_MODULUS; y++)
 }
void rcGenHalfRes (char * src, char * dest, uint32 widthInPixels, uint32 heightInLines, uint32 srcRowUpdate, bool invert)
Definition at line 40 of file rc_imageprocessing.cpp.
References ALTIVEC_VALUE_MODULO, FAST_VALUE_MODULO, and rcCverGenHalfRes().
Referenced by MungGrabDataProc(), and yourDisplayCallback().
 {
   assert(src);
   assert(dest);
   assert(widthInPixels <= srcRowUpdate);
   assert(widthInPixels > 1);
   assert(heightInLines > 1);
 #ifdef __ppc__
   if ((ALTIVEC_VALUE_MODULO(src) == 0) && (ALTIVEC_VALUE_MODULO(dest) == 0) &&
       (ALTIVEC_VALUE_MODULO(srcRowUpdate) == 0) && (FAST_VALUE_MODULO(widthInPixels) == 0))
     rcAltivecGenHalfRes(src, dest, widthInPixels, heightInLines, srcRowUpdate, invert);
   else
 #endif
     rcCverGenHalfRes(src, dest, widthInPixels, heightInLines, srcRowUpdate, invert);
 }
void rfAndImage (const rcWindow & srcWin, const rcWindow & maskWin, rcWindow & destWin)
Definition at line 558 of file rc_imageprocessing.cpp.
References ALTIVEC_VALUE_MODULO, rcWindow::depth(), rcWindow::height(), rcPixel16, rcPixel32, rcPixel8, rfCverAndImages(), rfHasSIMD(), rmExceptionMacro, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
Referenced by rcShape::project(), and rfCorrelate().
 {
   if ((srcWin.depth() != rcPixel8 &&
       srcWin.depth() != rcPixel16 &&
        srcWin.depth() != rcPixel32) ||
       srcWin.depth() != maskWin.depth() ||
       srcWin.depth() != destWin.depth() ||
       srcWin.width() != maskWin.width() ||
       srcWin.width() != destWin.width() ||
       srcWin.height() != maskWin.height() ||
       srcWin.height() != destWin.height())
     {
       rmExceptionMacro(<< "IP MisMatch");
     }
   uint8* src = (uint8*)srcWin.rowPointer(0);
   uint8* dest = (uint8*)destWin.rowPointer(0);
   uint8* mask = (uint8*)maskWin.rowPointer(0);
   int32 srcRowUpdate = srcWin.rowUpdate();
   int32 destRowUpdate = destWin.rowUpdate();
   int32 maskRowUpdate = maskWin.rowUpdate();
   int32 widthInPixels = srcWin.width()*((int32)srcWin.depth());
 #ifdef __ppc__
   if (rfHasSIMD () && (ALTIVEC_VALUE_MODULO(src) == 0) && (ALTIVEC_VALUE_MODULO(dest) == 0) &&
       (ALTIVEC_VALUE_MODULO(mask) == 0) &&
       (ALTIVEC_VALUE_MODULO(srcRowUpdate) == 0) &&
       (ALTIVEC_VALUE_MODULO(destRowUpdate) == 0) &&
       (ALTIVEC_VALUE_MODULO(maskRowUpdate) == 0) &&
       (ALTIVEC_VALUE_MODULO(widthInPixels) == 0))
     rfAltivecAndImages(src, mask, dest, widthInPixels, srcWin.height(),
                srcRowUpdate);
   else
 #endif
     rfCverAndImages(srcWin, maskWin, destWin);
 }
static void rfCverAndImages (const rcWindow & srcWin, const rcWindow & maskWin, rcWindow & destWin) static
Definition at line 476 of file rc_imageprocessing.cpp.
References rcWindow::getPixel(), rcWindow::height(), rcWindow::setPixel(), and rcWindow::width().
Referenced by rfAndImage().
 {
   const int32 width = srcWin.width(), height = srcWin.height();
   for (int32 y = 0; y < height; y++)
     for (int32 x = 0; x < width; x++)
       destWin.setPixel(x, y, (maskWin.getPixel(x, y) & srcWin.getPixel(x, y)));
 }
bool rfIsWhiteReversed (const rcWindow & image)
Definition at line 449 of file rc_imageprocessing.cpp.
References rcFrame::colorMap(), rcFrame::colorMapSize(), rcWindow::frameBuf(), rcFrame::getColor(), rcFrame::isGray(), and rfRed.
 {
     bool isWhiteReversed = false;
     const rcSharedFrameBufPtr& frame = image.frameBuf();
     if ( frame->colorMap() != 0 && frame->colorMapSize() > 0 &&
          frame->isGray() ) {
         uint32 cMapSize = frame->colorMapSize();
         // Test whether index 0 contains white
         isWhiteReversed = true;
         for (uint32 i = 1; i < cMapSize; ++i) {
             uint32 prev = rfRed(frame->getColor( i-1 ));
             uint32 cur = rfRed(frame->getColor( i ));
             // All RGB values must be in ascending order for white to
             // be considered reversed
             if ( prev < cur ) {
                 isWhiteReversed = false;
                 break;
             }
         }
     }
     return isWhiteReversed;
 }
void rfMutualChannel (const rcWindow & rgbInput, rcWindow & channelOutput)
Definition at line 871 of file rc_imageprocessing.cpp.
References rc2dVector< T >::angle(), rcWindow::depth(), green, rcWindow::height(), rcWindow::isBound(), rcWindow::isGray(), rc2dVector< T >::isLenNull(), rc2dVector< T >::len(), rcWindow::pelPointer(), rcPixel32, red, rfImageConvertFloat8(), rkPI, rmAssert, rcWindow::rowPointer(), rcWindow::setAllPixels(), and rcWindow::width().
 {
   if ( rgbInput.isGray() ) return;
   rmAssert (rgbInput.isBound ());
   rmAssert( rgbInput.depth() == rcPixel32 );
   const uint32 width = rgbInput.width();
   const uint32 height = rgbInput.height();
   rcWindow mu (256, 256, rcPixel32);
   mu.setAllPixels (0);
   float maxb (0.0f);
   rc2Fvector maxdv (256.0f, 256.0f);
   float maxd = maxdv.len ();
   for (uint32 j = 0; j < height; j++)
     {
       uint32 *rgbRow = (uint32 *) rgbInput.rowPointer (j);
       for (uint32 i = 0; i < width; i++, rgbRow++)
     {
       const uint8* rgbComponents = (uint8*) rgbRow;
       int32 red (rgbComponents[1]);
       int32 green (rgbComponents[2]);
       rmAssert (red >= 0);
       rmAssert (green >= 0);
       rc2Fvector v (red, green);
       if (v.isLenNull()) continue;
       float r = (v.angle() / rcRadian (rkPI/2.0)) * 255;
       float l = (v.len() * 255) / maxd;
       float *binPtr = (float *) mu.pelPointer ((int32) r,
                            (int32) l);
       *binPtr += 1;
       float bin (*binPtr);
       if (bin > maxb) maxb = bin;
     }
     }
   channelOutput = rfImageConvertFloat8 (mu, 0.0f, 255.0f);
 }
void rfRcWindow32to8 (const rcWindow & rgbInput, rcWindow & channelOutput, rcChannelConversion opt)
Definition at line 314 of file rc_imageprocessing.cpp.
References rfImageConvert32to8().
Referenced by getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rfCellDensity(), rfCompareMovies(), rfOptoKineticEnergy(), rfRcWindow32to8(), and yourDisplayCallback().
 {
   return rfImageConvert32to8 (rgbInput, channelOutput, opt);
 }
void rfRcWindow32to8 (const vector< rcWindow > & rgb, vector< rcWindow > & channel, rcChannelConversion opt)
Definition at line 320 of file rc_imageprocessing.cpp.
References count(), rcPixel8, and rfRcWindow32to8().
 {
    assert (rgb.size());
    channel.resize( rgb.size());
    assert (rgb.size() == channel.size());
    rcPixel pd = rcPixel8;
    for (vector<rcWindow>::const_iterator img = rgb.begin(); img != rgb.end(); img++)
    {
        rcWindow tmp (img->width(), img->height(), pd);
        rfRcWindow32to8( *img, tmp, opt );
        uint32 count = img - rgb.begin ();
        channel[count] = tmp;
    }
 #ifdef DEBUG_LOG
    fprintf (stderr, " Converted to single Channel depth %i\n", pd );
 #endif
 }
void rfRcWindow8to32 (const rcWindow & rgbInput, rcWindow & rgbOutput)
Definition at line 365 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcFrame::getColor(), rcWindow::height(), rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
     rmAssert( rgbInput.width() == rgbOutput.width() );
     rmAssert( rgbInput.height() == rgbOutput.height() );
     rmAssert( rgbInput.depth() == rcPixel8 );
     rmAssert( rgbOutput.depth() == rcPixel32 );
     const uint32 width = rgbInput.width();
     const uint32 height = rgbInput.height();
     const rcSharedFrameBufPtr& iFrame = rgbInput.frameBuf();
     // TODO: use AltiVec for this
     for (uint32 j = 0; j < height; j++)
     {
         uint32* oRow = (uint32*) rgbOutput.rowPointer (j);
         uint8* iRow = (uint8*) rgbInput.rowPointer (j);
         for (uint32 i = 0; i < width; i++, oRow++, iRow++)
         {
             const uint8 pix = *iRow;
             *oRow = iFrame->getColor( uint32(pix) );
         }
     }
 }
void rfReversePixels16 (rcWindow & image)
Definition at line 430 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcWindow::height(), rcFrame::initGrayColorMap(), rcPixel16, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
     rmAssert( image.depth() == rcPixel16);
     const int32 width = image.width();
     const int32 height = image.height();
     // Use default gray color map
     image.frameBuf()->initGrayColorMap();
     // TODO: use AltiVec for better speed
     for (int32 j = 0; j < height; j++) {
       uint16 *oneRow = (uint16 *) image.rowPointer (j);
         for (int32 i = 0; i < width; ++i, ++oneRow)
             *oneRow = ~*oneRow;
     }
 }
void rfReversePixels8 (rcWindow & image)
Definition at line 413 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcWindow::height(), rcFrame::initGrayColorMap(), rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcMovieConverterToRfy::createRfyMovie(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rfCompareMovies(), and rfImageFileToRcWindow().
 {
     rmAssert( image.depth() == rcPixel8 );
     const int32 width = image.width();
     const int32 height = image.height();
     // Use default gray color map
     image.frameBuf()->initGrayColorMap();
     for (int32 j = 0; j < height; j++) {
         uint8 *oneRow = image.rowPointer (j);
         for (int32 i = 0; i < width; ++i, ++oneRow)
             *oneRow = ~*oneRow;
     }
 }
void rfTemporalMedian (const vector< rcWindow > & srcWin, rcWindow & destWin)
Definition at line 648 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel8, rfTemporalMedianPixel16(), rfTemporalMedianPixel8(), rmAssert, and rcWindow::width().
Referenced by main().
 {
     rmAssert (srcWin.size() == 3);
     if (! destWin.isBound () )
     {
         destWin = rcWindow (srcWin[0].width(), srcWin[1].height (), srcWin[0].depth () );
     }
     for (uint32 i = 0; i < srcWin.size(); i++)
     {
         rmAssert(srcWin[i].depth() == destWin.depth());
         rmAssert(srcWin[i].width() == destWin.width());
         rmAssert(srcWin[i].height() == destWin.height());
     }
     switch (destWin.depth ())
     {
         case rcPixel8:
         rfTemporalMedianPixel8 (srcWin, destWin);
         break;
         case rcPixel16:
         rfTemporalMedianPixel16 (srcWin, destWin);
         break;
         default:
         rmAssert (1);
     }
 }
void rfTemporalMedianPixel16 (const vector< rcWindow > & srcWin, rcWindow & destWin) static
Definition at line 773 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel16, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rfTemporalMedian().
 {
     rmAssert (srcWin.size() == 3);
     uint16 median;
     for (uint32 i = 0; i < srcWin.size(); i++)
     {
         rmAssert((srcWin[i].depth() == rcPixel16));
         rmAssert(srcWin[i].depth() == destWin.depth());
         rmAssert(srcWin[i].width() == destWin.width());
         rmAssert(srcWin[i].height() == destWin.height());
     }
     vector<uint16*> src (3);
     vector<uint16*> srcUP (3);
     int32 widthInPixels = srcWin[0].width();
     const uint32 opsPerLoop = 8; // 16 / numBytes
     uint32 unrollCnt = widthInPixels / opsPerLoop;
     uint32 unrollRem = widthInPixels % opsPerLoop;
     uint32 lastRow = srcWin[0].height() - 1, row = 0;
     uint16 ab [8], ac[8], bc[8]; // same as opsPerLoop
     uint16 abc[3];
     for ( ; row <= lastRow; row++)
     {
         for (uint32 i = 0; i < srcWin.size(); i++)
         {
             src[i] = (uint16*)srcWin[i].rowPointer(row);
         }
         uint16* dest = (uint16*)destWin.rowPointer(row);
     // Process a chunk
     // for pixels in the loop
     // calculate ab, ac, and bc
         for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
         {
             for (uint32 i = 0; i < opsPerLoop; i++, src[0]++, src[1]++, src[2]++, dest++)
             {
                 abc[0] = *src[0]; abc[1] = *src[1]; abc[2] = *src[2];
                 ab[i] = abc[0] > abc[1];
                 ac[i] = abc[0] > abc[2];
                 bc[i] = abc[1] > abc[2];
                 int32 t0 = ab[i] + ac[i];
                 int32 t1 = bc[i] - ab[i];
                 int32 t2 = bc[i] + ac[i];
                 if (t1 == 0 && (t0 % 2) != 1 && (t2 % 2) != 1)
                     median = abc[1];
                 else if (t1 != 0 && t0 == 1 && (t2 % 2) != 1)
                     median = abc[0];
                 else if (t1 != 0 && t2 == 1 && (t0 % 2) != 1)
                     median = abc[2];
                 else
                     rmAssert (1);
                 *dest = median;
             }
         }
     // Left overs less than opsPerLoop. OpsPerLoop * numBytes
         memset(&ab[0], 0, 16);memset(&ac[0], 0, 16);memset(&bc[0], 0, 16);
         for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++, src[0]++, src[1]++, src[2]++, dest++)
         {
             abc[0] = *src[0]; abc[1] = *src[1]; abc[2] = *src[2];
             ab[touchCount] = abc[0] > abc[1];
             ac[touchCount] = abc[0] > abc[2];
             bc[touchCount] = abc[1] > abc[2];
             int32 t0 = ab[touchCount] + ac[touchCount];
             int32 t1 = bc[touchCount] - ab[touchCount];
             int32 t2 = bc[touchCount] + ac[touchCount];
             if (t1 == 0 && (t0 % 2) != 1 && (t2 % 2) != 1)
                 median = abc[1];
             else if (t1 != 0 && t0 == 1 && (t2 % 2) != 1)
                 median = abc[0];
             else if (t1 != 0 && t2 == 1 && (t0 % 2) != 1)
                 median = abc[2];
             else
                 rmAssert (1);
             *dest = median;
         }
     }
 }
void rfTemporalMedianPixel8 (const vector< rcWindow > & srcWin, rcWindow & destWin) static
Definition at line 677 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rfTemporalMedian().
 {
     rmAssert (srcWin.size() == 3);
     uint8 median;
     for (uint32 i = 0; i < srcWin.size(); i++)
     {
         rmAssert((srcWin[i].depth() == rcPixel8));
         rmAssert(srcWin[i].depth() == destWin.depth());
         rmAssert(srcWin[i].width() == destWin.width());
         rmAssert(srcWin[i].height() == destWin.height());
     }
     vector<uint8*> src (3);
     vector<uint8*> srcUP (3);
     int32 widthInPixels = srcWin[0].width();
     const uint32 opsPerLoop = 16;
     uint32 unrollCnt = widthInPixels / opsPerLoop;
     uint32 unrollRem = widthInPixels % opsPerLoop;
     uint32 lastRow = srcWin[0].height() - 1, row = 0;
     uint8 ab [16], ac[16], bc[16];
     uint8 abc[3];
     for ( ; row <= lastRow; row++)
     {
         for (uint32 i = 0; i < srcWin.size(); i++)
         {
             src[i] = (uint8*)srcWin[i].rowPointer(row);
         }
         uint8* dest = (uint8*)destWin.rowPointer(row);
     // Process a chunk
     // for pixels in the loop
     // calculate ab, ac, and bc
         for (uint32 touchCount = 0; touchCount < unrollCnt; touchCount++)
         {
             for (uint32 i = 0; i < opsPerLoop; i++, src[0]++, src[1]++, src[2]++, dest++)
             {
                 abc[0] = *src[0]; abc[1] = *src[1]; abc[2] = *src[2];
                 ab[i] = abc[0] > abc[1];
                 ac[i] = abc[0] > abc[2];
                 bc[i] = abc[1] > abc[2];
                 int32 t0 = ab[i] + ac[i];
                 int32 t1 = bc[i] - ab[i];
                 int32 t2 = bc[i] + ac[i];
                 if (t1 == 0 && (t0 % 2) != 1 && (t2 % 2) != 1)
                     median = abc[1];
                 else if (t1 != 0 && t0 == 1 && (t2 % 2) != 1)
                     median = abc[0];
                 else if (t1 != 0 && t2 == 1 && (t0 % 2) != 1)
                     median = abc[2];
                 else
                     rmAssert (1);
                 *dest = median;
             }
         }
     // Left overs less than opsPerLoop
         memset(&ab[0], 0, 16);memset(&ac[0], 0, 16);memset(&bc[0], 0, 16);
         for (uint32 touchCount = 0; touchCount < unrollRem; touchCount++, src[0]++, src[1]++, src[2]++, dest++)
         {
             abc[0] = *src[0]; abc[1] = *src[1]; abc[2] = *src[2];
             ab[touchCount] = abc[0] > abc[1];
             ac[touchCount] = abc[0] > abc[2];
             bc[touchCount] = abc[1] > abc[2];
             int32 t0 = ab[touchCount] + ac[touchCount];
             int32 t1 = bc[touchCount] - ab[touchCount];
             int32 t2 = bc[touchCount] + ac[touchCount];
             if (t1 == 0 && (t0 % 2) != 1 && (t2 % 2) != 1)
                 median = abc[1];
             else if (t1 != 0 && t0 == 1 && (t2 % 2) != 1)
                 median = abc[0];
             else if (t1 != 0 && t2 == 1 && (t0 % 2) != 1)
                 median = abc[2];
             else
                 rmAssert (1);
             *dest = median;
         }
     }
 }
void rfWindow8to32 (const rcWindow & rgbInput, rcWindow & rgbOutput)
Definition at line 341 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::height(), rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
     rmAssert( rgbInput.width() == rgbOutput.width() );
     rmAssert( rgbInput.height() == rgbOutput.height() );
     rmAssert( rgbInput.depth() == rcPixel8 );
     rmAssert( rgbOutput.depth() == rcPixel32 );
     const uint32 width = rgbInput.width();
     const uint32 height = rgbInput.height();
     // TODO: use AltiVec for this
     for (uint32 j = 0; j < height; j++)
     {
         uint32* oRow = (uint32*) rgbOutput.rowPointer (j);
         uint8* iRow = (uint8*) rgbInput.rowPointer (j);
         for (uint32 i = 0; i < width; i++)
         {
       *oRow++ = *iRow++;
         }
     }
 }
Variable Documentation
int myfirsttime = 1
Definition at line 32 of file rc_imageprocessing.cpp.
const uint8 sInvertMap[256] static
Initial value:
=
  {
    0,
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,
    17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,
    33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,
    49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,
    65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,
    81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,
    97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,
    113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,
    129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,
    145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,
    161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,
    177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,
    193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,
    209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,
    225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,
    241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,
  }
Definition at line 391 of file rc_imageprocessing.cpp.