Visible: src/analysis/code/rc_pmcorr.cpp File Reference
rc_pmcorr.cpp File Reference
#include <rc_analysis.h>
#include "rc_pmcorr.h"
#include <rc_rowfunc.h>
#include <rc_correlationwindow.h>
#include <rc_imageprocessing.h>
#include <vector>
Functions
static void correlate16a32 (const rcWindow &sourceA, const rcWindow &sourceB, rcCorr &res)
template void rfCorrelateWindow (rcCorrelationWindow< uint16 > &sourceA, rcCorrelationWindow< uint16 > &sourceB, const rsCorrParams &params, rcCorr &res)
template void rfCorrelateWindow (rcCorrelationWindow< uint32 > &sourceA, rcCorrelationWindow< uint32 > &sourceB, const rsCorrParams &params, rcCorr &res)
template void rfCorrelateWindow (rcCorrelationWindow< float > &sourceA, rcCorrelationWindow< float > &sourceB, const rsCorrParams &params, rcCorr &res)
void rfCorrelate (const uint8 *baseA, const uint8 *baseB, uint32 rupA, uint32 rupB, uint32 width, uint32 height, rcCorr &res)
void rfCorrelate (const rcWindow &img, const rcWindow &mdl, const rcWindow &mask, const rsCorrParams &params, rcCorr &res, int32 maskN)
void rfCorrelate (const rcWindow &sourceA, const rcWindow &sourceB, const rsCorrParams &params, rcCorr &res)
void rfCorrelate (const rcWindow &sourceA, const rcWindow &sourceB, rcCorr &res)
template<>
void rfCorrelateWindow (rcCorrelationWindow< uint8 > &sourceA, rcCorrelationWindow< uint8 > &sourceB, const rsCorrParams &params, rcCorr &res)
template<class T >
void rfCorrelateWindow (rcCorrelationWindow< T > &sourceA, rcCorrelationWindow< T > &sourceB, const rsCorrParams &params, rcCorr &res)
ostream & operator<< (ostream &os, const rcCorr &corr)
Variables
static const rsCorrParams sDefaultCorrParams
Function Documentation
static void correlate16a32 (const rcWindow & sourceA, const rcWindow & sourceB, rcCorr & res) static
Definition at line 98 of file rc_pmcorr.cpp.
References rcBasicCorrRowFunc< T >::areaFunc(), rcWindow::depth(), rcBasicCorrRowFunc< T >::epilog(), rcBasicCorrRowFunc< T >::prolog(), rcPixel16, and rcPixel32.
 {
     // rcBasicCorrRowFunc ctor checks the depth so we do not repeat it
     if (sourceA.depth() == rcPixel32)
     {
         uint32 dummy;
         rcBasicCorrRowFunc<uint32> bc (sourceA, sourceB, dummy);
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     }
     else if (sourceA.depth() == rcPixel16)
     {
         uint16 dummy;
         rcBasicCorrRowFunc<uint16> bc (sourceA, sourceB, dummy);
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     }
 }
ostream& operator<< (ostream & os, const rcCorr & corr)
Definition at line 972 of file rc_pmcorr.cpp.
References endl(), rcCorr::n(), rcCorr::r(), rcCorr::Si(), rcCorr::Sii(), rcCorr::Sim(), rcCorr::singular(), rcCorr::Sm(), and rcCorr::Smm().
 {
   os << "R " << corr.r() << " N " <<  corr.n() << " Rp " <<  corr.singular();
   os << " Si " <<  corr.Si() << " Sii " <<  corr.Sii() << " Sm " <<  corr.Sm() << " Smm " <<  corr.Smm() << " Sim " <<  corr.Sim() << endl;
   return os;
 }
void rfCorrelate (const uint8 * baseA, const uint8 * baseB, uint32 rupA, uint32 rupB, uint32 width, uint32 height, rcCorr & res)
Definition at line 122 of file rc_pmcorr.cpp.
References rcBasicCorrRowFunc< T >::areaFunc(), rcBasicCorrRowFunc< T >::epilog(), rcBasicCorrRowFunc< T >::prolog(), and rfHasSIMD().
Referenced by _exhaustiveImageFind(), calcMusclePeriod(), rcSimilarator::correlate(), rcAutoCorrelation::genPoint(), rcMuscleTracker::genSpace(), rcPointCorrelation::genSpace(), rcSimilarator::relativeCorrelate(), rfCorrelate(), and rfOptoKineticEnergy().
 {
 #ifdef __ppc__
     if (rfHasSIMD ())
     {
         // Use AltiVec for processing
         altiVecCorrelate (baseA, baseB, rupA, rupB, width, height, res);
     }
     else
 #endif
     {
         rcBasicCorrRowFunc<uint8> bc (baseA, baseB, rupA, rupB, width, height);
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     }
 }
void rfCorrelate (const rcWindow & img, const rcWindow & mdl, const rcWindow & mask, const rsCorrParams & params, rcCorr & res, int32 maskN)
Definition at line 147 of file rc_pmcorr.cpp.
References rcCorr::compute(), rcWindow::depth(), rcWindow::getPixel(), rcWindow::height(), rcCorr::n(), rcPixel16, rcPixel32, rcPixel8, rfAndImage(), rfCorrelate(), rmAssert, and rcWindow::width().
 {
   rcWindow iMasked(img.width(), img.height(), img.depth());
   rcWindow mMasked(img.width(), img.height(), img.depth());
   rfAndImage(img, mask, iMasked);
   rfAndImage(mdl, mask, mMasked);
   rfCorrelate(iMasked, mMasked, params, res);
   if (maskN < 0) {
     uint32 allOnes = 0xFF;
     if (img.depth() == rcPixel16)
       allOnes = 0xFFFF;
     else if (img.depth() == rcPixel32)
       allOnes = 0xFFFFFFFF;
     else
       rmAssert(img.depth() == rcPixel8);
     maskN = 0;
     for (int32 y = 0; y < mask.height(); y++)
       for (int32 x = 0; x < mask.width(); x++) {
                 uint32 val = mask.getPixel(x, y);
                 if (val == allOnes)
                     maskN++;
                 else
                     rmAssert(val == 0);
       }
   }
   res.n(maskN);
   res.compute();
 }
void rfCorrelate (const rcWindow & sourceA, const rcWindow & sourceB, const rsCorrParams & params, rcCorr & res)
Definition at line 185 of file rc_pmcorr.cpp.
References rcWindow::depth(), rcWindow::height(), rfCorrelate(), rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
 {
     rmAssert (sourceA.depth() == sourceB.depth());
         rfCorrelate (sourceA.rowPointer(0),sourceB.rowPointer(0),
                                  sourceA.rowUpdate(), sourceB.rowUpdate(),
                                  sourceA.width() * sourceA.depth(),
                                  sourceA.height(),
                                  res);
 }
void rfCorrelate (const rcWindow & sourceA, const rcWindow & sourceB, rcCorr & res)
Definition at line 195 of file rc_pmcorr.cpp.
References rfCorrelate(), and sDefaultCorrParams.
 {
   rfCorrelate(sourceA, sourceB, sDefaultCorrParams, res);
 }
template void rfCorrelateWindow (rcCorrelationWindow< uint16 > & sourceA, rcCorrelationWindow< uint16 > & sourceB, const rsCorrParams & params, rcCorr & res)
Referenced by rcSimilarator::correlate(), and rcSimilarator::relativeCorrelate().
template void rfCorrelateWindow (rcCorrelationWindow< uint32 > & sourceA, rcCorrelationWindow< uint32 > & sourceB, const rsCorrParams & params, rcCorr & res)
template void rfCorrelateWindow (rcCorrelationWindow< float > & sourceA, rcCorrelationWindow< float > & sourceB, const rsCorrParams & params, rcCorr & res)
template<> void rfCorrelateWindow (rcCorrelationWindow< uint8 > & sourceA, rcCorrelationWindow< uint8 > & sourceB, const rsCorrParams & params, rcCorr & res)
Definition at line 202 of file rc_pmcorr.cpp.
References rcBasicCorrRowFunc< T >::areaFunc(), rcCorrelationWindow< T >::depth(), rcBasicCorrRowFunc< T >::epilog(), rcBasicCorrRowFunc< T >::prolog(), rfHasSIMD(), rmAssert, rmUnused, rcCorr::Si(), rcCorr::Sii(), rcCorr::Sm(), rcCorr::Smm(), rcCorrelationWindow< T >::sum(), rcCorrelationWindow< T >::sumSquares(), and rcCorrelationWindow< T >::sumValid().
 {
     rmUnused( params );
     rmAssert (sourceA.depth() == sourceB.depth());
 #ifdef __ppc__
     if (rfHasSIMD ()) {
         // Altivec enabled
         rcAltiVecCorrRowFunc<uint8> bc( sourceA, sourceB );
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     } else
 #endif
     {
         // Altivec disabled
         rcBasicCorrRowFunc<uint8> bc( sourceA, sourceB );
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     }
     // Cache sums
     if ( !sourceA.sumValid() ) {
         sourceA.sum( res.Si() );
         sourceA.sumSquares( res.Sii() );
     }
     if ( !sourceB.sumValid() ) {
         sourceB.sum( res.Sm() );
         sourceB.sumSquares( res.Smm() );
     }
 }
template<class T > void rfCorrelateWindow (rcCorrelationWindow< T > & sourceA, rcCorrelationWindow< T > & sourceB, const rsCorrParams & params, rcCorr & res)
Definition at line 240 of file rc_pmcorr.cpp.
References rcCorrelationWindow< T >::depth(), rcCorrelationWindow< T >::height(), rcBasicCorrRowFunc< T >::prolog(), rmAssert, rcCorrelationWindow< T >::rowPointer(), rcCorrelationWindow< T >::rowUpdate(), rcCorr::Si(), rcCorr::Sii(), rcCorr::Sm(), rcCorr::Smm(), rcCorrelationWindow< T >::sum(), rcCorrelationWindow< T >::sumSquares(), rcCorrelationWindow< T >::sumValid(), and rcCorrelationWindow< T >::width().
 {
     rmAssert (sourceA.depth() == sourceB.depth());
         // Bytewise correlation
         // Note: cannot construct rcCorrelationWindow because of window depth difference
         rcBasicCorrRowFunc<uint8> bc( sourceA.rowPointer(0), sourceB.rowPointer(0),
                                                                      sourceA.rowUpdate(), sourceB.rowUpdate(),
                                                                      sourceA.width() * sourceA.depth(),
                                                                      sourceA.height() );
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     // Cache sums
     if ( !sourceA.sumValid() ) {
         sourceA.sum( res.Si() );
         sourceA.sumSquares( res.Sii() );
     }
     if ( !sourceB.sumValid() ) {
         sourceB.sum( res.Sm() );
         sourceB.sumSquares( res.Smm() );
     }
 }
Variable Documentation
const rsCorrParams sDefaultCorrParams static
Definition at line 42 of file rc_pmcorr.cpp.
Referenced by rfCorrelate().