Visible: src/visual/code/rc_graphics.cpp File Reference
rc_graphics.cpp File Reference
#include <rc_graphics.h>
#include <rc_edge.h>
#include <rc_histstats.h>
Functions
static int32 getAxis (uint8 val)
void rfGradientImageToVisualSegment (const rcWindow &peaks, const rcWindow &angle, rcVisualSegmentCollection &v)
void rfImageGradientToVisualSegment (const rcWindow &image, rcVisualSegmentCollection &v)
Variables
static rcGradientDir< float > sGr
Function Documentation
static int32 getAxis (uint8 val) inline static
Definition at line 39 of file rc_graphics.cpp.
 {
   return ((val + 16) / 32) % 8;
 }
void rfGradientImageToVisualSegment (const rcWindow & peaks, const rcWindow & angle, rcVisualSegmentCollection & v)
Definition at line 46 of file rc_graphics.cpp.
References rcWindow::height(), rcWindow::pelPointer(), rmAssert, rcWindow::size(), and rcWindow::width().
Referenced by rfImageGradientToVisualSegment().
 {
   rmAssert (peaks.size() == angle.size());
   for (int32 j = 2; j < angle.height () - 2; j++)
     {
       const uint8 *mag = peaks.pelPointer(2, j);  // 5x5 processing
       const uint8 *ang = angle.pelPointer(2, j);
       for (int32 i = 2; i < angle.width () - 2; i++, mag++, ang++)
     {
       if (! (*mag) ) continue;
       rcAngle8 d (*ang);
       rc2Fvector p1 ((float) i + 0.5f, (float) j + 0.5f);
       rc2Fvector p2 = p1 + rc2Fvector (1.0f, rcRadian (d));
       rcVisualArrow arrow( p1, p2);
       v.push_back( arrow );
     }
     }
 }
void rfImageGradientToVisualSegment (const rcWindow & image, rcVisualSegmentCollection & v)
Definition at line 66 of file rc_graphics.cpp.
References rcWindow::depth(), rcWindow::height(), rfGradientImageToVisualSegment(), rfSobel(), rfSpatialEdge(), and rcWindow::width().
Referenced by rcEngineImpl::modelTracker().
 {
     rcWindow mag (image.width(),image.height(), image.depth());
     rcWindow ang (image.width(),image.height(), image.depth());
     rcWindow peaks (image.width(),image.height(), image.depth());
     rfSobel (image, mag, ang, false);
     rcWindow pwin (peaks, 1, 1, image.width()-2, image.height()-2);
         rcHistoStats h (pwin);
     rfSpatialEdge (mag, ang, pwin, (int) h.mean(), false);
     rfGradientImageToVisualSegment (peaks, ang, v);
 }
Variable Documentation
rcGradientDir<float> sGr static
Definition at line 44 of file rc_graphics.cpp.