Visible: src/analysis/code/rc_kinetrack.cpp File Reference
rc_kinetrack.cpp File Reference
#include <rc_kinetoscope.h>
#include <rc_pmcorr.h>
#include <rc_ip.h>
#include <algorithm>
#include <functional>
#include <iomanip>
#include <rc_peak.h>
#include <rc_analysis.h>
#include <rc_lsfit.h>
#include <rc_associate.h>
#include <rc_similarity.h>
#include <rc_macro.h>
#include <rc_polygongroup.h>
Macros
#define rmPrintBinaryImageGTEV(a, v)
#define FILLFUNCTION
Functions
void rfOfCellsAndPolys (list< rcVisualFunction > &cells, vector< rcPolygon > &fixed, vector< rcPolygon > &moving)
Macro Definition Documentation
#define FILLFUNCTION
Value:
vf.mMinTemporalIntRect = *rectIter;\
  vf.mMinTemporalEncRect = *rectIter;\
  vf.mId = regionLabel;          \
  vf.frameIndex (videoFrameIndex);\
  vf.mParentId = rcVisualFunction::gPreHistoric;\
  vf.mGeneration = 0;\
  vf.label (regionLabel-1);\
  vf.mMass = mass;\
  mFunctionMap.push_back (vf)
Definition at line 415 of file rc_kinetrack.cpp.
Referenced by rcKinetoscope::connectedFunctions().
#define rmPrintBinaryImageGTEV (a, v)
Value:
{                   \
  for (int32 i__temp = 0; i__temp < (a).height(); i__temp++) {    \
    for (int32 j__temp = 0; j__temp < (a).width(); j__temp++)       \
      fprintf(stderr, "%1c", ((a).getPixel(j__temp,i__temp)>=(v)) ? '+' : '-'); \
    fprintf (stderr, "\n");                     \
  }}
Definition at line 346 of file rc_kinetrack.cpp.
Function Documentation
void rfOfCellsAndPolys (list< rcVisualFunction > & cells, vector< rcPolygon > & fixed, vector< rcPolygon > & moving)
Definition at line 652 of file rc_kinetrack.cpp.
References endl(), rcPolygon::intersects(), and rfCellNotViable().
Referenced by rcKinetoscope::connectedFunctions().
 {
   cerr << fixed.size () << " Fixed Poly(s),   " << cells.size() << " Cell(s),   " <<
     moving.size() << " Moving Cell(s) " << endl;
    list<rcVisualFunction>::iterator aliveCell = cells.begin();
    for (; aliveCell != cells.end(); aliveCell++)
      {
        cerr << "Cell " << aliveCell->id() << "\t";
        if (rfCellNotViable (*aliveCell))
      {
        cerr << aliveCell->state () << endl;
        continue;
      }
        rcPolygon cpg = aliveCell->polygons().back();
        vector<rcPolygon>::iterator fp = fixed.begin();
        vector<int32> fflags, mflags;
        for (;fp != fixed.end(); fp++)
      {
        int32 intersect = cpg.intersects (*fp);
        fflags.push_back (intersect);
      }
        fp = moving.begin();
        for (;fp != moving.end(); fp++)
      {
        int32 intersect = cpg.intersects (*fp);
        mflags.push_back (intersect);
      }
        for (uint32 fi = 0; fi < (fflags.size() + mflags.size()) ; fi++)
      {
        if (fi < fflags.size() && fflags[fi])
          cerr << "f+\t";
        else if (fi < fflags.size() && fflags[fi] == 0)
          cerr << "f-\t";
        if (fi >= fflags.size())
          {
            uint32 mi = fi - fflags.size();
            if (mi < mflags.size() && mflags[mi])
          cerr << "m+\t";
            else if (mi < mflags.size() && mflags[mi] == 0)
          cerr << "m-\t";
          }
      }
        cerr << endl;
      }
 }