Visible: src/analysis/code/rc_kinegraphics.cpp File Reference
rc_kinegraphics.cpp File Reference
#include <rc_kinetoscope.h>
#include <algorithm>
#include <functional>
#include <iomanip>
#include <rc_platform.h>
#include <rc_polygon.h>
#include <rc_draw.h>
Functions
uint32 rfRgbf (float r, float g, float b)
Variables
static const rcVisualStyle affy (rfRgbf(0.1f, 1.0f, 0.2f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle caliper (rfRgbf(0.82f, 0.26f, 0.0f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle caliper2 (rfRgbf(0.0f, 0.26f, 0.82f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle graph (rfRgbf(1.0f, 160.0f/255.0f, 80.0f/255.0f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle affylow (rfRgbf(0.05f, 0.5f, 0.1f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle fnd (rfRgbf(1.0f, 0.26f, 0.02f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle green (rfRgbf(0.58f, 0.82f, 0.18f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle yel (rfRgbf(0.8f, 1.0f, 0.60f), 2, rc2Fvector(0.0f, 0.0f))
static const rcVisualStyle red (rfRgbf(0.9f, 0.0f, 0.0f), 2, rc2Fvector(0.0f, 0.0f))
Function Documentation
uint32 rfRgbf (float r, float g, float b) inline
Definition at line 235 of file rc_kinegraphics.cpp.
 { return (0xff << 24) | ((((uint32) (r * 255)) & 0xff) << 16) | ((((uint32) (g * 255)) & 0xff) << 8) | (((uint32) (b * 255)) & 0xff); }
Variable Documentation
const rcVisualStyle affy(rfRgbf(0.1f, 1.0f, 0.2f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
const rcVisualStyle affylow(rfRgbf(0.05f, 0.5f, 0.1f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualFunctionMap().
const rcVisualStyle caliper(rfRgbf(0.82f, 0.26f, 0.0f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
const rcVisualStyle caliper2(rfRgbf(0.0f, 0.26f, 0.82f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
const rcVisualStyle fnd(rfRgbf(1.0f, 0.26f, 0.02f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualDebugGraphics().
const rcVisualStyle graph(rfRgbf(1.0f, 160.0f/255.0f, 80.0f/255.0f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
const rcVisualStyle green(rfRgbf(0.58f, 0.82f, 0.18f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by TIFFImageIO::EvaluateImageAt(), TIFFImageIO::GetFormat(), rfMutualChannel(), and rcImageCanvasGL::statusString().
const rcVisualStyle red(rfRgbf(0.9f, 0.0f, 0.0f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by TIFFImageIO::EvaluateImageAt(), TIFFImageIO::GetFormat(), rcMonitor::rcMonitor(), rfMutualChannel(), rcImageCanvasGL::statusString(), and rcKinetoscope::visualDebugGraphics().
const rcVisualStyle yel(rfRgbf(0.8f, 1.0f, 0.60f), 2, rc2Fvector(0.0f, 0.0f)) static
Referenced by rcKinetoscope::visualDebugGraphics().