Visible: include/visual/rc_ipconvert.h File Reference
rc_ipconvert.h File Reference
#include <rc_window.h>
#include <rc_imageprocessing.h>
Enumerations
enum rcChannelConversion {
rcSelectGreen = 0, rcSelectRed, rcSelectBlue, rcSelectAverage,
rcSelectMax, rcSelect12BitCamera, rcSelectAll
}
Functions
void rfImageConvert8888ToARGB (vector< rcWindow > &iargb, rcWindow &argb)
Convert 4 8bit images to ARGB.
void rfImageConvertARGBto8888 (rcWindow &argb, vector< rcWindow > &iargb)
void rfImageConvert8ToARGB (const rcWindow &byteImage, const rcWindow &alpha, rcWindow &argb)
rcWindow rfImageConvert8ToARGB (const rcWindow &byteImage, const rcWindow &alpha)
void rfImageConvertFloat8 (const rcWindow &floatImage, rcWindow &byteImage, float minVal=0.0f, float maxVal=1.0f)
rcWindow rfImageConvertFloat8 (const rcWindow &floatImage, float minVal=0.0f, float maxVal=1.0f)
void rfImageConvert816 (const rcWindow &byteImage, rcWindow &twobyteImage)
rcWindow rfImageConvert816 (const rcWindow &byteImage)
void rfImageConvert168 (const rcWindow &twobyteImage, rcWindow &byteImage, rcChannelConversion opt=rcSelectMax)
Convert 16 bit images to 8 bit ones.
rcWindow rfImageConvert168 (const rcWindow &twobyteImage, rcChannelConversion opt=rcSelectMax)
void rfImageConvert32to8 (const rcWindow &rgbInput, rcWindow &channelOutput, rcChannelConversion opt=rcSelectAverage)
rcWindow rfImageConvert32to8 (const rcWindow &rgbInput, rcChannelConversion opt=rcSelectAverage)
void rfImageConvert32to8 (const vector< rcWindow > &rgbInput, vector< rcWindow > &channelOutput, rcChannelConversion opt=rcSelectAverage)
void rfImageConvert8to32 (const rcWindow &rgbInput, rcWindow &rgbOutput)
rcWindow rfImage8Transpose (const rcWindow &image)
void rfRcWindow32to8 (const rcWindow &rgbInput, rcWindow &channelOutput, rcChannelConversion opt=rcSelectAverage)
void rfRcWindow32to8 (const vector< rcWindow > &rgbInput, vector< rcWindow > &channelOutput, rcChannelConversion opt=rcSelectAverage)
void rfRcWindow8to32 (const rcWindow &rgbInput, rcWindow &rgbOutput)
void rfRcWindow16to8 (const rcWindow &rgbInput, rcWindow &channelOutput)
void rfReversePixels8 (rcWindow &image)
void rfReversePixels16 (rcWindow &image)
bool rfIsWhiteReversed (const rcWindow &image)
void rfImageAddMask (const rcWindow &image, const rcWindow &mask, rcWindow &fourbyteImage, uint32 maskVal)
rcWindow rfImageAddMask (const rcWindow &image, const rcWindow &mask, uint32 maskVal)
Enumeration Type Documentation
enum rcChannelConversion
Conversion Options
Enumerator
rcSelectGreen
rcSelectRed
rcSelectBlue
rcSelectAverage
rcSelectMax
rcSelect12BitCamera
Selects 12 bit range for a 16 bit image
rcSelectAll
Definition at line 70 of file rc_ipconvert.h.
   {
     rcSelectGreen = 0,
     rcSelectRed,
     rcSelectBlue,
     rcSelectAverage,
     rcSelectMax,
     rcSelect12BitCamera,
     rcSelectAll   // Keep all channels
   };
Function Documentation
rcWindow rfImage8Transpose (const rcWindow & image)
Definition at line 528 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rcWindow::pelPointer(), rmAssert, rcWindow::rowUpdate(), and rcWindow::width().
Referenced by rcSimilarator::fill().
 {
   rmAssert (image.isBound());
   rcWindow dst (image.height(), image.width());
   int32 srup (image.rowUpdate());
   for (int32 y = 0; y < dst.height(); y++)
     {
       const uint8* sp = image.pelPointer(y, 0);
       uint8 * dp = dst.pelPointer (0, y);
       int32 x = dst.width();
       do
       {
     *dp++ = *sp;
     sp += srup;
       } while (--x);
     }
   return dst;
 }
void rfImageAddMask (const rcWindow & image, const rcWindow & mask, rcWindow & fourbyteImage, uint32 maskVal)
Definition at line 461 of file rc_ipconvert.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rfDirectionSignal(), and rfImageAddMask().
 {
     rmAssert (image.isBound());
     rmAssert (mask.isBound());
     rmAssert (fourbyteImage.isBound());
     rmAssert (mask.depth() == rcPixel8);
     rmAssert (image.width() == mask.width());
     rmAssert (image.height() == mask.height());
     if (image.depth() == rcPixel8)
     {
         for (int32 j = 0; j < image.height(); j++)
         {
             uint8 * p32 =  fourbyteImage.rowPointer (j);
             const uint8 * p8 = image.rowPointer (j);
             const uint8 * m8 = mask.rowPointer (j);
             for (int32 i = 0; i < fourbyteImage.width(); i++, p8++, m8++, p32++)
             {
                 uint8 gray = *p8;
                 if (*m8 == 255)     *p32 = 0;
                 else *p32 = gray;
             }
         }
     }
     else if (image.depth() == rcPixel16)
     {
         for (int32 j = 0; j < image.height(); j++)
         {
             uint16 * p32 = (uint16 *) fourbyteImage.rowPointer (j);
             const uint16 * p16 = (uint16 *) image.rowPointer (j);
             const uint8 * m8 = mask.rowPointer (j);
             for (int32 i = 0; i < fourbyteImage.width(); i++, p16++, m8++, p32++)
             {
                 uint16 gray = *p16;
                 if (*m8 == 255) *p32 = 0;
                 else *p32 = gray;
             }
         }
     }
     else if (image.depth() == rcPixel32)   // 32 bit case needs to be reworked
     {
         for (int32 j = 0; j < image.height(); j++)
         {
             uint32 * p32 = (uint32 *) fourbyteImage.rowPointer (j);
             const uint32 * i32 = (uint32 *) image.rowPointer (j);
             const uint8 * m8 = mask.rowPointer (j);
             for (int32 i = 0; i < fourbyteImage.width(); i++, i32++, m8++, p32++)
             {
                 uint32 pixel = *i32;
                 if (*m8 == 255) *p32 = 0;
                 else *p32 = pixel;
             }
         }
     }
         else
             rmAssert (0);
 }
rcWindow rfImageAddMask (const rcWindow & image, const rcWindow & mask, uint32 maskVal)
Definition at line 519 of file rc_ipconvert.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rfImageAddMask(), rmAssert, and rcWindow::width().
 {
     rmAssert (image.isBound());
     rmAssert (mask.isBound());
     rcWindow newdest (image.width(), image.height(), image.depth ());
     rfImageAddMask (image, mask, newdest, maskVal);
     return newdest;
 }
void rfImageConvert168 (const rcWindow & twobyteImage, rcWindow & byteImage, rcChannelConversion opt)
Convert 16 bit images to 8 bit ones.
Parameters
twoByteImage is a 16 bit rcWindow
byteImage is a single byte rcWindow
opt is an enum of type rcChannelConversion
Returns
void
Approach Convert to float with no offset and scaling Calculate a histogram using 12Bit range if possible Convert float to 8 setting the min and max as ends of a linear scale
Note
that Apple vImage API for converting float to 8 has max parameter before min :) Using direct 16 to 8 from vImage. vImage_Buffer vu16, vf, v8; twobyteImage.vImage (vu16); rcWindow e (twobyteImage.width(), twobyteImage.height(), rcPixel8); e.vImage (v8);
vImage_Error ve; ve = vImageConvert_16UToPlanar8(&vu16, &v8,kvImageNoFlags); rmAssert (!ve); byteImage = e;
Definition at line 231 of file rc_ipconvert.cpp.
References rcWindow::bits(), rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcHistoStats::max(), rcHistoStats::min(), rcPixel16, rcPixel32, rcPixel8, rcSelect12BitCamera, rcSelectAll, rmAssert, rcWindow::vImage(), and rcWindow::width().
Referenced by rcGenMovieFile::addFrame(), copyImage(), main(), and rfImageConvert168().
 {
   rmAssert (twobyteImage.isBound());
   rmAssert (twobyteImage.depth() == rcPixel16);
   if (opt == rcSelectAll)
       {
     byteImage = twobyteImage;
     return;
       }
   int32 range = (opt ==   rcSelect12BitCamera) ? (12+1) : twobyteImage.bits ();
   range = 1 << (range);
   rcHistoStats h16 (twobyteImage, range);
   float minFloat =  h16.min (5);
   float maxFloat = h16.max (5);
   vImage_Buffer vu16, vf, v8;
   twobyteImage.vImage (vu16);
   rcWindow f (twobyteImage.width(), twobyteImage.height(), rcPixel32);
   f.vImage (vf);
   rcWindow e (twobyteImage.width(), twobyteImage.height(), rcPixel8);
   e.vImage (v8);
   vImage_Error ve;
   ve = vImageConvert_16UToF (&vu16, &vf, 0.0f, 1.0f, kvImageNoFlags);
   rmAssert (!ve);
   ve = vImageConvert_PlanarFtoPlanar8 (&vf, &v8, maxFloat, minFloat, kvImageNoFlags);
   byteImage = e;
 }
rcWindow rfImageConvert168 (const rcWindow & twobyteImage, rcChannelConversion opt = rcSelectMax)
Definition at line 282 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rcPixel8, rcSelectAll, rfImageConvert168(), rmAssert, and rcWindow::width().
 {
   rmAssert (twobyteImage.isBound());
   if (opt == rcSelectAll)
       {
     return rcWindow (twobyteImage);
       }
   rcWindow newdest (twobyteImage.width(), twobyteImage.height(), rcPixel8);
   rfImageConvert168 (twobyteImage, newdest);
   return newdest;
 }
void rfImageConvert32to8 (const rcWindow & rgbInput, rcWindow & channelOutput, rcChannelConversion opt = rcSelectAverage)
Definition at line 300 of file rc_ipconvert.cpp.
References _rfRcWindow32to8(), rcWindow::depth(), rcWindow::height(), rcWindow::isGray(), rcPixel32, rcPixel8, rcSelectAll, rcSelectAverage, rcSelectBlue, rcSelectGreen, rcSelectMax, rcSelectRed, rmAssert, rcWindow::vImage(), and rcWindow::width().
Referenced by rcGenMovieFile::addFrame(), rcEngineImpl::analyzeFocusArea(), rcEngineImpl::ipp(), main(), rfImageConvert32to8(), and rfRcWindow32to8().
 {
     rmAssert( rgbInput.width() == channelOutput.width() );
     rmAssert( rgbInput.height() == channelOutput.height() );
     rmAssert( rgbInput.depth() == rcPixel32 );
     if (1)
       {
     return _rfRcWindow32to8 (rgbInput, channelOutput, opt);
       }
     if (opt == rcSelectAll)
       {
     channelOutput = rgbInput;
     return;
       }
     const uint32 width = rgbInput.width();
     const uint32 height = rgbInput.height();
     //@todo add hasSIMD
     vImage_Buffer v32, vr, vg, vb, va;
     rgbInput.vImage (v32);
     vector<rcWindow> channels(4);
     if ( rgbInput.isGray() )
       {
     channels[(int32) rcSelectGreen] = channelOutput;
       }
     else
       {
     switch (opt)
       {
       case rcSelectAverage:
         channels[(int32) rcSelectGreen] = channelOutput;
         break;
       case rcSelectRed:
         channels[(int32) rcSelectRed] = channelOutput;
         break;
       case rcSelectGreen:
         channels[(int32) rcSelectGreen] = channelOutput;
         break;
       case rcSelectBlue:
         channels[(int32) rcSelectBlue] = channelOutput;
         break;
       case rcSelectMax:
         channels[(int32) rcSelectBlue] = channelOutput;
         break;
       case rcSelectAll:
       default:
         // @todo API to support this.
         rmAssert( 0 );
       }
       }
     for (uint32 i = 0; i < channels.size(); i++)
       {
     if (!channels[i].isBound())
       {
         rcWindow f (width, height, rcPixel8);
         channels[i] = f;
       }
       }
     channels[(int32) rcSelectGreen].vImage (vg);
     channels[(int32) rcSelectRed].vImage (vr);
     channels[(int32) rcSelectBlue].vImage (vb);
     channels[channels.size() - 1].vImage (va);
     vImage_Error ve;
     ve = vImageConvert_ARGB8888toPlanar8 (&v32,
                       &va, &vr, &vg, &vb,
                       kvImageNoFlags);
 }
rcWindow rfImageConvert32to8 (const rcWindow & rgbInput, rcChannelConversion opt = rcSelectAverage)
Definition at line 377 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rcPixel8, rcSelectAll, rfImageConvert32to8(), rmAssert, and rcWindow::width().
 {
   rmAssert (rgbInput.isBound());
   if (opt == rcSelectAll)
     {
       return rcWindow (rgbInput);
     }
   rcWindow newdest (rgbInput.width(), rgbInput.height(), rcPixel8);
   rfImageConvert32to8 (rgbInput, newdest, opt);
   return newdest;
 }
void rfImageConvert32to8 (const vector< rcWindow > & rgbInput, vector< rcWindow > & channelOutput, rcChannelConversion opt = rcSelectAverage)
Definition at line 394 of file rc_ipconvert.cpp.
References count(), rcPixel8, and rfImageConvert32to8().
 {
    assert (rgb.size());
    channel.resize( rgb.size());
    assert (rgb.size() == channel.size());
    rcPixel pd = rcPixel8;
    for (vector<rcWindow>::const_iterator img = rgb.begin(); img != rgb.end(); img++)
    {
        rcWindow tmp (img->width(), img->height(), pd);
        rfImageConvert32to8( *img, tmp, opt );
        uint32 count = img - rgb.begin ();
        channel[count] = tmp;
    }
 }
void rfImageConvert816 (const rcWindow & byteImage, rcWindow & twobyteImage)
Definition at line 198 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rfImageConvert816().
 {
   rmAssert (byteImage.isBound());
   rmAssert (twobyteImage.isBound());
   for (int32 j = 0; j < twobyteImage.height(); j++)
      {
        uint16 * p16 = (uint16 *) twobyteImage.rowPointer (j);
        const uint8 * p8 = byteImage.rowPointer (j);
        for (int32 i = 0; i < twobyteImage.width(); i++, p8++, p16++)
      *p16 = uint16 (*p8);
      }
 }
rcWindow rfImageConvert816 (const rcWindow & byteImage)
Definition at line 214 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rcPixel16, rfImageConvert816(), rmAssert, and rcWindow::width().
 {
   rmAssert (byteImage.isBound());
   rcWindow newdest (byteImage.width(), byteImage.height(), rcPixel16);
   rfImageConvert816 (byteImage, newdest);
   return newdest;
 }
void rfImageConvert8888ToARGB (vector< rcWindow > & iargb, rcWindow & argb)
Convert 4 8bit images to ARGB.
Parameters
iargb a vector of rcWindows
argb is a 4 byte rcWindow
Returns
void
Definition at line 91 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rmAssert, rcWindow::vImage(), and rcWindow::width().
Referenced by rcKinetoscope::reichardt().
 {
   rmAssert (iargb.size() == 4);
   rmAssert (argb.isBound());
   int32 width (argb.width());
   int32 height (argb.height());
   //@todo add if has SIMD
   vImage_Buffer v[4], vargb;
   argb.vImage (vargb);
   for (uint32 i = 0; i < 4; i++)
     {
       rmAssert (iargb[i].isBound());
       rmAssert (width == iargb[i].width());
       rmAssert (height == iargb[i].height());
       iargb[i].vImage(v[i]);
     }
   vImage_Error ve;
   ve = vImageConvert_Planar8toARGB8888 (&v[0], &v[1], &v[2], &v[3], &vargb, kvImageNoFlags);
   rmAssert (!ve);
 }
void rfImageConvert8to32 (const rcWindow & rgbInput, rcWindow & rgbOutput)
Definition at line 413 of file rc_ipconvert.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcFrame::getColor(), rcWindow::height(), rcPixel32, rcPixel8, rfHasSIMD(), rmAssert, rcWindow::rowPointer(), rcWindow::setAllPixels(), rcWindow::vImage(), and rcWindow::width().
 {
     rmAssert( rgbInput.width() == rgbOutput.width() );
     rmAssert( rgbInput.height() == rgbOutput.height() );
     rmAssert( rgbInput.depth() == rcPixel8 );
     rmAssert( rgbOutput.depth() == rcPixel32 );
     const uint32 width = rgbInput.width();
     const uint32 height = rgbInput.height();
     //@todo add hasSIMD
     if (rfHasSIMD ())
       {
     vImage_Buffer v8, v32, va;
     rgbInput.vImage (v8);
     rgbOutput.vImage (v32);
     rcWindow f (width, height, rcPixel8);
     f.setAllPixels (0);
     f.vImage (va);
     vImage_Error ve;
     ve = vImageConvert_Planar8toARGB8888 (&va, &v8, &v8, &v8, &v32,
                       kvImageNoFlags);
     return;
       }
     const rcSharedFrameBufPtr& iFrame = rgbInput.frameBuf();
     // TODO: use AltiVec for this
     for (uint32 j = 0; j < height; j++)
     {
       uint32* oRow = (uint32*) rgbOutput.rowPointer (j);
       uint8* iRow = (uint8*) rgbInput.rowPointer (j);
       for (uint32 i = 0; i < width; i++, oRow++, iRow++)
         {
       const uint8 pix = *iRow;
       *oRow = iFrame->getColor( uint32(pix) );
         }
     }
 }
void rfImageConvert8ToARGB (const rcWindow & byteImage, const rcWindow & alpha, rcWindow & argb)
Definition at line 146 of file rc_ipconvert.cpp.
References rcWindow::depth(), rcWindow::isBound(), rcPixel32, rmAssert, and rcWindow::vImage().
Referenced by rcGenMovieFile::addFrame(), rcKinetoscope::reichardt(), and rfImageConvert8ToARGB().
 {
   rmAssert (alpha.isBound());
   rmAssert (byteImage.isBound());
   rmAssert (argb.isBound());
   rmAssert (argb.depth() == rcPixel32);
   //@todo add if has SIMD
   vImage_Buffer va, v8, vargb;
   alpha.vImage (va);
   byteImage.vImage (v8);
   argb.vImage (vargb);
   vImage_Error ve;
   ve = vImageConvert_Planar8toARGB8888 (&va, &v8, &v8, &v8, &vargb, kvImageNoFlags);
   rmAssert (!ve);
 }
rcWindow rfImageConvert8ToARGB (const rcWindow & byteImage, const rcWindow & alpha)
Definition at line 164 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rcPixel32, rfImageConvert8ToARGB(), rmAssert, and rcWindow::width().
 {
   rmAssert (byteImage.isBound());
   rcWindow newdest (byteImage.width(), byteImage.height(), rcPixel32);
   rfImageConvert8ToARGB (byteImage, alpha, newdest);
   return newdest;
 }
void rfImageConvertARGBto8888 (rcWindow & argb, vector< rcWindow > & iargb)
Definition at line 115 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rmAssert, rcWindow::vImage(), and rcWindow::width().
Referenced by rcKinetoscope::frame().
 {
   rmAssert (iargb.empty());
   rmAssert (argb.isBound());
   int32 width (argb.width());
   int32 height (argb.height());
   //@todo add if has SIMD
   vImage_Buffer v[4], vargb;
   argb.vImage (vargb);
   // Create 4 images and put them in the vector
   for (uint32 i = 0; i < 4; i++)
     {
       rcWindow tmp (width, height);
       iargb.push_back (tmp);
     }
   for (uint32 i = 0; i < 4; i++)
     {
       rmAssert (iargb[i].isBound());
       rmAssert (width == iargb[i].width());
       rmAssert (height == iargb[i].height());
       iargb[i].vImage(v[i]);
     }
   vImage_Error ve;
   ve = vImageConvert_ARGB8888toPlanar8 (&vargb, &v[0], &v[1], &v[2], &v[3], kvImageNoFlags);
   rmAssert (!ve);
 }
void rfImageConvertFloat8 (const rcWindow & floatImage, rcWindow & byteImage, float minVal = 0.0f, float maxVal = 1.0f)
Definition at line 173 of file rc_ipconvert.cpp.
References rcWindow::isBound(), rmAssert, and rcWindow::vImage().
Referenced by rfImageConvertFloat8(), and rfMutualChannel().
 {
   rmAssert (floatImage.isBound());
   rmAssert (byteImage.isBound());
   //@todo add if has SIMD
   vImage_Buffer vf, v8;
   floatImage.vImage (vf);
   byteImage.vImage (v8);
   vImage_Error ve;
   ve = vImageConvert_PlanarFtoPlanar8 (&vf, &v8, maxVal, minVal, kvImageNoFlags);
   rmAssert (!ve);
 }
rcWindow rfImageConvertFloat8 (const rcWindow & floatImage, float minVal = 0.0f, float maxVal = 1.0f)
Definition at line 189 of file rc_ipconvert.cpp.
References rcWindow::height(), rcWindow::isBound(), rcPixel8, rfImageConvertFloat8(), rmAssert, and rcWindow::width().
 {
   rmAssert (floatImage.isBound());
   rcWindow newdest (floatImage.width(), floatImage.height(), rcPixel8);
   rfImageConvertFloat8 (floatImage, newdest, minVal, maxVal);
   return newdest;
 }
bool rfIsWhiteReversed (const rcWindow & image)
Definition at line 449 of file rc_imageprocessing.cpp.
References rcFrame::colorMap(), rcFrame::colorMapSize(), rcWindow::frameBuf(), rcFrame::getColor(), rcFrame::isGray(), and rfRed.
 {
     bool isWhiteReversed = false;
     const rcSharedFrameBufPtr& frame = image.frameBuf();
     if ( frame->colorMap() != 0 && frame->colorMapSize() > 0 &&
          frame->isGray() ) {
         uint32 cMapSize = frame->colorMapSize();
         // Test whether index 0 contains white
         isWhiteReversed = true;
         for (uint32 i = 1; i < cMapSize; ++i) {
             uint32 prev = rfRed(frame->getColor( i-1 ));
             uint32 cur = rfRed(frame->getColor( i ));
             // All RGB values must be in ascending order for white to
             // be considered reversed
             if ( prev < cur ) {
                 isWhiteReversed = false;
                 break;
             }
         }
     }
     return isWhiteReversed;
 }
void rfRcWindow16to8 (const rcWindow & rgbInput, rcWindow & channelOutput)
void rfRcWindow32to8 (const rcWindow & rgbInput, rcWindow & channelOutput, rcChannelConversion opt = rcSelectAverage)
Definition at line 314 of file rc_imageprocessing.cpp.
References rfImageConvert32to8().
Referenced by getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rfCellDensity(), rfCompareMovies(), rfOptoKineticEnergy(), rfRcWindow32to8(), and yourDisplayCallback().
 {
   return rfImageConvert32to8 (rgbInput, channelOutput, opt);
 }
void rfRcWindow32to8 (const vector< rcWindow > & rgbInput, vector< rcWindow > & channelOutput, rcChannelConversion opt = rcSelectAverage)
Definition at line 320 of file rc_imageprocessing.cpp.
References count(), rcPixel8, and rfRcWindow32to8().
 {
    assert (rgb.size());
    channel.resize( rgb.size());
    assert (rgb.size() == channel.size());
    rcPixel pd = rcPixel8;
    for (vector<rcWindow>::const_iterator img = rgb.begin(); img != rgb.end(); img++)
    {
        rcWindow tmp (img->width(), img->height(), pd);
        rfRcWindow32to8( *img, tmp, opt );
        uint32 count = img - rgb.begin ();
        channel[count] = tmp;
    }
 #ifdef DEBUG_LOG
    fprintf (stderr, " Converted to single Channel depth %i\n", pd );
 #endif
 }
void rfRcWindow8to32 (const rcWindow & rgbInput, rcWindow & rgbOutput)
Definition at line 365 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcFrame::getColor(), rcWindow::height(), rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
     rmAssert( rgbInput.width() == rgbOutput.width() );
     rmAssert( rgbInput.height() == rgbOutput.height() );
     rmAssert( rgbInput.depth() == rcPixel8 );
     rmAssert( rgbOutput.depth() == rcPixel32 );
     const uint32 width = rgbInput.width();
     const uint32 height = rgbInput.height();
     const rcSharedFrameBufPtr& iFrame = rgbInput.frameBuf();
     // TODO: use AltiVec for this
     for (uint32 j = 0; j < height; j++)
     {
         uint32* oRow = (uint32*) rgbOutput.rowPointer (j);
         uint8* iRow = (uint8*) rgbInput.rowPointer (j);
         for (uint32 i = 0; i < width; i++, oRow++, iRow++)
         {
             const uint8 pix = *iRow;
             *oRow = iFrame->getColor( uint32(pix) );
         }
     }
 }
void rfReversePixels16 (rcWindow & image)
Definition at line 430 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcWindow::height(), rcFrame::initGrayColorMap(), rcPixel16, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
 {
     rmAssert( image.depth() == rcPixel16);
     const int32 width = image.width();
     const int32 height = image.height();
     // Use default gray color map
     image.frameBuf()->initGrayColorMap();
     // TODO: use AltiVec for better speed
     for (int32 j = 0; j < height; j++) {
       uint16 *oneRow = (uint16 *) image.rowPointer (j);
         for (int32 i = 0; i < width; ++i, ++oneRow)
             *oneRow = ~*oneRow;
     }
 }
void rfReversePixels8 (rcWindow & image)
Definition at line 413 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::frameBuf(), rcWindow::height(), rcFrame::initGrayColorMap(), rcPixel8, rmAssert, rcWindow::rowPointer(), and rcWindow::width().
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), rcMovieConverterToRfy::createRfyMovie(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rfCompareMovies(), and rfImageFileToRcWindow().
 {
     rmAssert( image.depth() == rcPixel8 );
     const int32 width = image.width();
     const int32 height = image.height();
     // Use default gray color map
     image.frameBuf()->initGrayColorMap();
     for (int32 j = 0; j < height; j++) {
         uint8 *oneRow = image.rowPointer (j);
         for (int32 i = 0; i < width; ++i, ++oneRow)
             *oneRow = ~*oneRow;
     }
 }