Visible: src/visual/code/rc_polygongroup.cpp File Reference
rc_polygongroup.cpp File Reference
#include <rc_polygongroup.h>
#include <rc_graphics.h>
Functions
void rfPolygonGroupToGraphicsCollection (rcPolygonGroupRef &pg, rcVisualGraphicsCollectionCollection &v, bool drawCOM)
bool operator== (rcPolygonGroupRef &cells, rcPolygonGroupRef &cells2)
void rfPolygonGroupMutualMerge (const vector< rcPolygon > &fixed, const vector< rcPolygon > &moving, vector< rcPolygon > &merged, double discDiameter, float areaRatio)
void rfPolygonGroupCenters (vector< rcPolygon > &polygons, vector< rc2Dvector > &centers)
Function Documentation
bool operator== (rcPolygonGroupRef & cells, rcPolygonGroupRef & cells2)
Definition at line 49 of file rc_polygongroup.cpp.
References endl(), rcPolygonGroupRef::polys(), and rcPolygonGroupRef::size().
 {
   if (cells2.size() != cells.size())
     {
       cerr << cells2.size() << " != " << cells.size() << endl;
       return 0;
     }
   for (uint32 i = 0; i < cells.size(); i++)
     {
       if (cells.polys()[i] != cells2.polys()[i])
     {
       cerr << cells.polys()[i] << " != " << cells2.polys()[i] << endl;
       return 0;
     }
     }
   return true;
 }
void rfPolygonGroupCenters (vector< rcPolygon > & polygons, vector< rc2Dvector > & centers)
Definition at line 172 of file rc_polygongroup.cpp.
References rmAssert.
Referenced by rcKinetoscope::associate().
 {
   vector<rcPolygon>::iterator polys = polygons.begin();
   centers.clear ();
   for (; polys != polygons.end(); polys++)
      {
        rc2Dvector cop;
        polys->centerOf (cop);
        centers.push_back (cop);
      }
   rmAssert (polygons.size() == centers.size());
 }
void rfPolygonGroupMutualMerge (const vector< rcPolygon > & fixed, const vector< rcPolygon > & moving, vector< rcPolygon > & merged, double discDiameter, float areaRatio)
Definition at line 123 of file rc_polygongroup.cpp.
References rcPolygon::convexUnion(), rcPolygon::discBuffer(), rcPolygon::intersects(), and rmAssert.
 {
    vector<rcPolygon>::const_iterator polys = fixed.begin();
    merged.clear ();
    for (; polys != fixed.end(); polys++)
      {
        rcPolygon buffer = polys->discBuffer (discDiameter);
        vector<rcPolygon > ipolPtrs, uniquePolPtrs;
        // The intersected list would include me
        buffer.intersects (moving, ipolPtrs, areaRatio);
        // Check if the intersect group intersects with any other polygon
        // @note Combinatorics of this could be improved
        bool intersects (false);
        for (uint32 pi = 0; pi < ipolPtrs.size(); pi++)
      {
        // Skip me. Since we know that it does and we want to get it out
        if (ipolPtrs[pi] == *polys) continue;
        vector<rcPolygon> tmpPtrs;
        intersects = ipolPtrs[pi].intersects (moving, tmpPtrs, areaRatio);
        if (intersects)
          {
            break;
          }
        uniquePolPtrs.push_back (ipolPtrs[pi]);
      }
        // Either we will have the original poly or a union of the merged.
        rcPolygon unionPoly = (uniquePolPtrs.size() > 1) ? uniquePolPtrs[0] : *polys;
        if (uniquePolPtrs.size() > 1)
      {
        rmAssert (!intersects);
        // There were more than one
        for (uint32 pi = 1; pi < uniquePolPtrs.size(); pi++)
          {
            rcPolygon tmpPoly;
            unionPoly .convexUnion(uniquePolPtrs[pi], tmpPoly);
            unionPoly = tmpPoly;
         }
      }
        merged.push_back (unionPoly);
      }
 }
void rfPolygonGroupToGraphicsCollection (rcPolygonGroupRef & pg, rcVisualGraphicsCollectionCollection & v, bool drawCOM)
Definition at line 31 of file rc_polygongroup.cpp.
References rcVisualGraphicsCollection::id(), rcPolygonGroupRef::polys(), rfPolygonToSegmentsCollection(), rcVisualGraphicsCollection::segments(), and rcPolygonGroupRef::size().
 {
   v.clear ();
   const vector<rcPolygon>& polys = pg.polys();
   for (uint32 i = 0; i < pg.size(); i++)
     {
       rcVisualGraphicsCollection graphics;
       rcVisualSegmentCollection& segments = graphics.segments();
       rfPolygonToSegmentsCollection(polys[i], segments, drawCOM);
       graphics.id ((int32) i);
       v.push_back (graphics);
     }
 }