Visible: src/util/code/rc_fileutils.cpp File Reference
rc_fileutils.cpp File Reference
#include <rc_timestamp.h>
#include "rc_fileutils.h"
#include <sys/stat.h>
#include <iomanip>
#include <fstream>
Typedefs
typedef struct direct ENTRY
Functions
static int alphasorthalf (const void *d1, const void *d2)
static int numericsort (const void *A, const void *B, int cs)
static int numericsort (const void *A, const void *B)
static int casenumericsort (const void *A, const void *B)
static int tiffilter (struct direct *dir)
static int jpgfilter (struct direct *dir)
static int pngfilter (struct direct *dir)
void rfGetDirEntries (const string &dirname, vector< std::string > &entries, const char *imageformat)
int32 rfGetFileSize (const char *sFileName)
bool rfIsDirectory (const char *inFullPath)
std::string rfStripPath (const std::string &fileName)
std::string rfStripExtension (const std::string &fileName)
std::string rfGetExtension (const std::string &fileName)
int rfFilename_match (const char *s, const char *p)
std::string rfMakeTmpFileName (const char *pathFormat, const char *baseName)
std::string rfMakeTmpFileName (const char *baseName)
std::string rfDumpMatrix (deque< deque< double > > &matrix, const char *pathFormat, const char *baseName)
bool rfFileExists (const std::string &filename)
Typedef Documentation
typedef struct direct ENTRY
Definition at line 27 of file rc_fileutils.cpp.
Function Documentation
static int alphasorthalf (const void * d1, const void * d2) static
Definition at line 175 of file rc_fileutils.cpp.
Referenced by rfGetDirEntries().
 {
   struct dirent *dir1 = *(struct dirent **)d1;
   struct dirent *dir2 = *(struct dirent **)d2;
   return strcmp(dir1->d_name,dir2->d_name);
 }
static int casenumericsort (const void * A, const void * B) static
Definition at line 277 of file rc_fileutils.cpp.
References numericsort().
{
   return numericsort(A, B, 0);
 }
static int jpgfilter (struct direct * dir) static
Definition at line 139 of file rc_fileutils.cpp.
Referenced by rfGetDirEntries().
 {
   char * s = dir->d_name;
   int cpplen = strlen(s) - 4;   // index of start of . in .cpp
   if (cpplen >= 0) {
     if (
     (strncmp(s+cpplen, ".jpg",4) == 0) ||
     (strncmp(s+cpplen, ".JPG",4) == 0))
       {
     return 1;
       }
   }
   return 0;
 }
static int numericsort (const void * A, const void * B, int cs) static
Definition at line 237 of file rc_fileutils.cpp.
Referenced by casenumericsort(), numericsort(), and rfGetDirEntries().
{
   struct dirent *dir1 = *(struct dirent **)A;
   struct dirent *dir2 = *(struct dirent **)B;
   const char* a = dir1->d_name;
   const char* b = dir2->d_name;
   int ret = 0;
   for (;;) {
     if (isdigit(*a & 255) && isdigit(*b & 255)) {
       int diff,magdiff;
       while (*a == '0') a++;
       while (*b == '0') b++;
       while (isdigit(*a & 255) && *a == *b) {a++; b++;}
       diff = (isdigit(*a & 255) && isdigit(*b & 255)) ? *a - *b : 0;
       magdiff = 0;
       while (isdigit(*a & 255)) {magdiff++; a++;}
       while (isdigit(*b & 255)) {magdiff--; b++;}
       if (magdiff) {ret = magdiff; break;} /* compare # of significant digits*/
       if (diff) {ret = diff; break;}    /* compare first non-zero digit */
     } else {
       if (cs) {
         /* compare case-sensitive */
     if ((ret = *a-*b)) break;
       } else {
     /* compare case-insensitve */
     if ((ret = tolower(*a & 255)-tolower(*b & 255))) break;
       }
       if (!*a) break;
       a++; b++;
     }
   }
   if (!ret) return 0;
   else return (ret < 0) ? -1 : 1;
 }
static int numericsort (const void * A, const void * B) static
Definition at line 285 of file rc_fileutils.cpp.
References numericsort().
{
   return numericsort(A, B, 1);
 }
static int pngfilter (struct direct * dir) static
Definition at line 157 of file rc_fileutils.cpp.
Referenced by rfGetDirEntries().
 {
     char * s = dir->d_name;
     int cpplen = strlen(s) - 4;   // index of start of . in .cpp
     if (cpplen >= 0) {
         if (
             (strncmp(s+cpplen, ".png",4) == 0) ||
             (strncmp(s+cpplen, ".png",4) == 0))
         {
             return 1;
         }
     }
     return 0;
 }
std::string rfDumpMatrix (deque< deque< double > > & matrix, const char * pathFormat, const char * baseName)
Definition at line 387 of file rc_fileutils.cpp.
References endl(), and rfMakeTmpFileName().
 {
   std::string fname = rfMakeTmpFileName (pathFormat, baseName) + std::string (".txt");
   ofstream file (fname.c_str ());
   if (! file)
     {
       return std::string ("");
     }
   deque<deque <double> >::iterator rowI = matrix.begin ();
   deque<deque <double> >::iterator rowend = matrix.end();
   ios::fmtflags oldflags = file.flags ();
   file.setf (ios::fixed);
   file << setprecision(12);
   for (; rowI < rowend; rowI++)
     {
       deque<double>::iterator cellI = (*rowI).begin ();
       deque<double>::iterator cellBend = (*rowI).end();
       advance (cellBend, -1);
       for (; cellI < cellBend; cellI++)
     file << *cellI << ",";
       file << *cellI << endl;
     }
   file.flags (oldflags);
   return fname;
 }
bool rfFileExists (const std::string & filename)
Definition at line 416 of file rc_fileutils.cpp.
 {
     struct stat buf;
     if (stat(filename.c_str(), &buf) != -1)
     {
         return true;
     }
     return false;
 }
int rfFilename_match (const char * s, const char * p)
Definition at line 290 of file rc_fileutils.cpp.
 {
   int matched;
   for (;;) {
     switch(*p++) {
     case '?' :  // match any single character
       if (!*s++) return 0;
       break;
     case '*' :  // match 0-n of any characters
       if (!*p) return 1; // do trailing * quickly
       while (!rfFilename_match(s, p)) if (!*s++) return 0;
       return 1;
     case '[': { // match one character in set of form [abc-d] or [^a-b]
       if (!*s) return 0;
       int reverse = (*p=='^' || *p=='!'); if (reverse) p++;
       matched = 0;
       char last = 0;
       while (*p) {
     if (*p=='-' && last) {
       if (*s <= *++p && *s >= last ) matched = 1;
       last = 0;
     } else {
       if (*s == *p) matched = 1;
     }
     last = *p++;
     if (*p==']') break;
       }
       if (matched == reverse) return 0;
       s++; p++;}
       break;
     case '{' : // {pattern1|pattern2|pattern3}
     NEXTCASE:
       if (rfFilename_match(s,p)) return 1;
     for (matched = 0;;) {
       switch (*p++) {
       case '\\': if (*p) p++; break;
       case '{': matched++; break;
       case '}': if (!matched--) return 0; break;
       case '|': case ',': if (matched==0) goto NEXTCASE;
       case 0: return 0;
       }
     }
     case '|':   // skip rest of |pattern|pattern} when called recursively
     case ',':
       for (matched = 0; *p && matched >= 0;) {
     switch (*p++) {
     case '\\': if (*p) p++; break;
     case '{': matched++; break;
     case '}': matched--; break;
     }
       }
       break;
     case '}':
       break;
     case 0: // end of pattern
       return !*s;
     case '\\':  // quote next character
       if (*p) p++;
     default:
       if (tolower(*s) != tolower(*(p-1))) return 0;
       s++;
       break;
     }
   }
 }
void rfGetDirEntries (const string & dirname, vector< std::string > & entries, const char * imageformat)
Definition at line 39 of file rc_fileutils.cpp.
References alphasorthalf(), jpgfilter(), numericsort(), pngfilter(), and tiffilter().
Referenced by rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), main(), and rcEngineImpl::setFromArgs().
 {
   direct ** darray;
   int entryCount (0);
   if (strncmp(imageformat, "tif", 3) == 0)
     {
       entryCount = scandir(
                const_cast<char *>(dirname.c_str()), &darray,
                tiffilter, numericsort);
     }
   if (strncmp(imageformat, "jpg", 3) == 0)
     {
       entryCount = scandir(
                const_cast<char *>(dirname.c_str()), &darray,
                jpgfilter, alphasorthalf);
     }
     if (strncmp(imageformat, "png", 3) == 0)
     {
         entryCount = scandir(
                              const_cast<char *>(dirname.c_str()), &darray,
                              pngfilter, alphasorthalf);
     }
   for(int k=0; k < entryCount; k++)
     {
       std::string name (darray[k]->d_name);
       name = dirname + std::string ("/") + name;
       entries.push_back(name);
     }
 }
std::string rfGetExtension (const std::string & fileName)
Definition at line 218 of file rc_fileutils.cpp.
Referenced by rcEngineImpl::loadMovie().
 {
   // Get file name without extension
   const std::string dot( "." );
   uint32 s = fileName.find_last_of( dot );
   if ( s != std::string::npos )
     return fileName.substr( s , std::string::npos );
   return fileName;
 }
int32 rfGetFileSize (const char * sFileName)
Definition at line 80 of file rc_fileutils.cpp.
 {
   std::ifstream f;
   f.open(sFileName, std::ios_base::binary | std::ios_base::in);
   if (!f.good() || f.eof() || !f.is_open()) { return 0; }
   f.seekg(0, std::ios_base::beg);
   std::ifstream::pos_type begin_pos = f.tellg();
   f.seekg(0, std::ios_base::end);
   return static_cast<int>(f.tellg() - begin_pos);
 }
bool rfIsDirectory (const char * inFullPath)
Definition at line 103 of file rc_fileutils.cpp.
Referenced by main().
 {
   struct stat dirstat;
   if (stat(inFullPath, &dirstat) == 0)
     {
       if ((dirstat.st_mode & S_IFDIR) == S_IFDIR)
     return true;
     }
   return false;
 }
std::string rfMakeTmpFileName (const char * pathFormat, const char * baseName)
Definition at line 365 of file rc_fileutils.cpp.
References rcTimestamp::now(), rmDim, and rcTimestamp::secs().
Referenced by rfDirectionSignal(), rfDumpMatrix(), and rfMakeTmpFileName().
 {
   char buf[2048];
   static const char *defaultFormat = "/tmp/um%d_%s";
   // Use current time in seconds as a pseudo-unique prefix
   double secs = rcTimestamp::now().secs();
   snprintf( buf, rmDim(buf), pathFormat ? pathFormat : defaultFormat,
         uint32(secs), baseName );
   return std::string( buf );
 }
std::string rfMakeTmpFileName (const char * baseName)
Definition at line 378 of file rc_fileutils.cpp.
References rfMakeTmpFileName().
 {
   return rfMakeTmpFileName (0, baseName);
 }
std::string rfStripExtension (const std::string & fileName)
Definition at line 205 of file rc_fileutils.cpp.
Referenced by rcExperimentDomainImpl::notifyMovieImport().
 {
   // Get file name without extension
   const std::string dot( "." );
   uint32 s = fileName.find_last_of( dot );
   if ( s != std::string::npos )
     return fileName.substr( 0, s );
   return fileName;
 }
std::string rfStripPath (const std::string & fileName)
Definition at line 189 of file rc_fileutils.cpp.
Referenced by rcEngineImpl::loadMovie(), rcEngineImpl::muscleTracker(), and rcExperimentDomainImpl::notifyMovieImport().
 {
   // Get file name without preceding path
   const std::string slash( "/" );
   uint32 s = fileName.find_last_of( slash );
   if ( s != std::string::npos ) {
     uint32 len = fileName.size() - s - 1;
     if ( len > 0 )
       return fileName.substr( s+1, len );
   }
   return fileName;
 }
static int tiffilter (struct direct * dir) static
Definition at line 114 of file rc_fileutils.cpp.
Referenced by rfGetDirEntries().
 {
   char * s = dir->d_name;
   int cpplen = strlen(s) - 4;   // index of start of . in .cpp
   if (cpplen >= 0) {
     if (
     (strncmp(s+cpplen, ".tif",4) == 0) ||
     (strncmp(s+cpplen, ".TIF",4) == 0))
       {
     return 1;
       }
   }
   if (cpplen >= 1) {
     if (
     (strncmp(s+cpplen-1, ".tiff",5) == 0) ||
     (strncmp(s+cpplen-1, ".TIFF",5) == 0))
       {
     return 1;
       }
   }
   return 0;
 }