Visible: include/visual/rc_polygongroup.h File Reference
rc_polygongroup.h File Reference
#include <rc_polygon.h>
#include <boost/shared_ptr.hpp>
Classes
class rcPolygonGroup
class rcPolygonGroupRef
Typedefs
typedef boost::shared_ptr
< rcPolygonGroup > rcSharedPolygonGroupPtr
Functions
void rfPolygonGroupToGraphicsCollection (const rcPolygonGroupRef &pg, rcVisualGraphicsCollectionCollection &v, bool drawCOM=false)
void rfPolygonGroupMutualMerge (const vector< rcPolygon > &fixed, const vector< rcPolygon > &moving, vector< rcPolygon > &merged, double discDiameter, float areaRatio=0.25f)
void rfPolygonGroupCenters (vector< rcPolygon > &polygons, vector< rc2Dvector > &centers)
bool operator!= (const rcPolygonGroupRef &a, const rcPolygonGroupRef &b)
Typedef Documentation
typedef boost::shared_ptr<rcPolygonGroup> rcSharedPolygonGroupPtr
Definition at line 27 of file rc_polygongroup.h.
Function Documentation
bool operator!= (const rcPolygonGroupRef & a, const rcPolygonGroupRef & b) inline
Definition at line 112 of file rc_polygongroup.h.
References operator==().
 {
   return !operator==(a, b);
 }
void rfPolygonGroupCenters (vector< rcPolygon > & polygons, vector< rc2Dvector > & centers)
Definition at line 172 of file rc_polygongroup.cpp.
References rmAssert.
Referenced by rcKinetoscope::associate().
 {
   vector<rcPolygon>::iterator polys = polygons.begin();
   centers.clear ();
   for (; polys != polygons.end(); polys++)
      {
        rc2Dvector cop;
        polys->centerOf (cop);
        centers.push_back (cop);
      }
   rmAssert (polygons.size() == centers.size());
 }
void rfPolygonGroupMutualMerge (const vector< rcPolygon > & fixed, const vector< rcPolygon > & moving, vector< rcPolygon > & merged, double discDiameter, float areaRatio = 0.25f)
Definition at line 123 of file rc_polygongroup.cpp.
References rcPolygon::convexUnion(), rcPolygon::discBuffer(), rcPolygon::intersects(), and rmAssert.
 {
    vector<rcPolygon>::const_iterator polys = fixed.begin();
    merged.clear ();
    for (; polys != fixed.end(); polys++)
      {
        rcPolygon buffer = polys->discBuffer (discDiameter);
        vector<rcPolygon > ipolPtrs, uniquePolPtrs;
        // The intersected list would include me
        buffer.intersects (moving, ipolPtrs, areaRatio);
        // Check if the intersect group intersects with any other polygon
        // @note Combinatorics of this could be improved
        bool intersects (false);
        for (uint32 pi = 0; pi < ipolPtrs.size(); pi++)
      {
        // Skip me. Since we know that it does and we want to get it out
        if (ipolPtrs[pi] == *polys) continue;
        vector<rcPolygon> tmpPtrs;
        intersects = ipolPtrs[pi].intersects (moving, tmpPtrs, areaRatio);
        if (intersects)
          {
            break;
          }
        uniquePolPtrs.push_back (ipolPtrs[pi]);
      }
        // Either we will have the original poly or a union of the merged.
        rcPolygon unionPoly = (uniquePolPtrs.size() > 1) ? uniquePolPtrs[0] : *polys;
        if (uniquePolPtrs.size() > 1)
      {
        rmAssert (!intersects);
        // There were more than one
        for (uint32 pi = 1; pi < uniquePolPtrs.size(); pi++)
          {
            rcPolygon tmpPoly;
            unionPoly .convexUnion(uniquePolPtrs[pi], tmpPoly);
            unionPoly = tmpPoly;
         }
      }
        merged.push_back (unionPoly);
      }
 }
void rfPolygonGroupToGraphicsCollection (const rcPolygonGroupRef & pg, rcVisualGraphicsCollectionCollection & v, bool drawCOM = false)