Visible: include/visual/rc_graphics.h File Reference
rc_graphics.h File Reference
#include <rc_style.h>
#include <rc_rect.h>
#include <rc_vector2d.h>
#include <rc_window.h>
Classes
class rcVisualSegment
class rcVisualEmpty
class rcVisualPoints
class rcVisualLine
class rcVisualLineStrip
class rcVisualLineLoop
class rcVisualRect
class rcVisualArrow
class rcVisualEllipse
class rcVisualCross
class rcVisualStyle
class rcVisualGraphicsCollection
class rcTextSegment
class rcTextCollection
Typedefs
typedef vector< rcVisualSegment > rcVisualSegmentCollection
typedef vector
< rcVisualGraphicsCollection > rcVisualGraphicsCollectionCollection
typedef vector< rcTextSegment > rcTextSegmentCollection
Functions
void rfGradientImageToVisualSegment (const rcWindow &mag, const rcWindow &angle, rcVisualSegmentCollection &v)
void rfImageGradientToVisualSegment (const rcWindow &image, rcVisualSegmentCollection &v)
Typedef Documentation
typedef vector<rcTextSegment> rcTextSegmentCollection
Definition at line 317 of file rc_graphics.h.
typedef vector<rcVisualGraphicsCollection> rcVisualGraphicsCollectionCollection
Definition at line 290 of file rc_graphics.h.
typedef vector<rcVisualSegment> rcVisualSegmentCollection
Definition at line 253 of file rc_graphics.h.
Function Documentation
void rfGradientImageToVisualSegment (const rcWindow & mag, const rcWindow & angle, rcVisualSegmentCollection & v)
Definition at line 46 of file rc_graphics.cpp.
References rcWindow::height(), rcWindow::pelPointer(), rmAssert, rcWindow::size(), and rcWindow::width().
Referenced by rfImageGradientToVisualSegment().
 {
   rmAssert (peaks.size() == angle.size());
   for (int32 j = 2; j < angle.height () - 2; j++)
     {
       const uint8 *mag = peaks.pelPointer(2, j);  // 5x5 processing
       const uint8 *ang = angle.pelPointer(2, j);
       for (int32 i = 2; i < angle.width () - 2; i++, mag++, ang++)
     {
       if (! (*mag) ) continue;
       rcAngle8 d (*ang);
       rc2Fvector p1 ((float) i + 0.5f, (float) j + 0.5f);
       rc2Fvector p2 = p1 + rc2Fvector (1.0f, rcRadian (d));
       rcVisualArrow arrow( p1, p2);
       v.push_back( arrow );
     }
     }
 }
void rfImageGradientToVisualSegment (const rcWindow & image, rcVisualSegmentCollection & v)
Definition at line 66 of file rc_graphics.cpp.
References rcWindow::depth(), rcWindow::height(), rfGradientImageToVisualSegment(), rfSobel(), rfSpatialEdge(), and rcWindow::width().
Referenced by rcEngineImpl::modelTracker().
 {
     rcWindow mag (image.width(),image.height(), image.depth());
     rcWindow ang (image.width(),image.height(), image.depth());
     rcWindow peaks (image.width(),image.height(), image.depth());
     rfSobel (image, mag, ang, false);
     rcWindow pwin (peaks, 1, 1, image.width()-2, image.height()-2);
         rcHistoStats h (pwin);
     rfSpatialEdge (mag, ang, pwin, (int) h.mean(), false);
     rfGradientImageToVisualSegment (peaks, ang, v);
 }