Visible: src/analysis/code/rc_analyzer.cpp File Reference
rc_analyzer.cpp File Reference
#include <algorithm>
#include <rc_analyzer.h>
#include <rc_similarity.h>
Functions
ostream & operator<< (ostream &os, const rcAnalyzerOptions &o)
Variables
const double cUndefinedEntropy = -1.0
Function Documentation
ostream& operator<< (ostream & os, const rcAnalyzerOptions & o)
Definition at line 365 of file rc_analyzer.cpp.
References rcAnalyzerOptions::bound(), rcAnalyzerOptions::mode(), rcAnalyzerOptions::origin(), and rcAnalyzerOptions::windowSize().
Referenced by otext::operator<<().
 {
   // Output basic options
   // TODO: display rsCorrParams
   os << "Mode " << o.mode();
   os << " origin " << o.origin();
   os << " rect " << o.bound();
   os << " window " << o.windowSize();
   return os;
 }
Variable Documentation
const double cUndefinedEntropy = -1.0
Definition at line 8 of file rc_analyzer.cpp.
Referenced by rcAnalyzer::getNextResult(), rcAnalyzer::pushResult(), and rcAnalyzer::pushUndefinedResult().