Visible: include/analysis/rc_diamondscan.h File Reference
rc_diamondscan.h File Reference
#include <vector>
#include <stdio.h>
#include <rc_analysis.h>
#include <rc_types.h>
#include <rc_pair.h>
#include <rc_window.h>
#include <rc_fit.h>
#include <rc_ip.h>
#include <rc_peak.h>
#include <rc_timinginfo.h>
Macros
#define mQuantz 65000
Functions
void rfImageFind (const rcWindow &moving, const rcWindow &fixed, rcFindList &locations, rcWindow &space, bool exhaustive=true)
void rfImageFind (const rcWindow &moving, const rcWindow &fixed, const rcWindow &mask, rcFindList &locations, rcWindow &space, bool exhaustive=true)
template<class T >
void rfPrintCorrSpace (rcWindow &space, T precision, float quantization)
void rfPrintFindList (const rcFindList &l, ostream &os)
Macro Definition Documentation
#define mQuantz 65000
Definition at line 32 of file rc_diamondscan.h.
Function Documentation
void rfImageFind (const rcWindow & moving, const rcWindow & fixed, rcFindList & locations, rcWindow & space, bool exhaustive = true)
void rfImageFind (const rcWindow & moving, const rcWindow & fixed, const rcWindow & mask, rcFindList & locations, rcWindow & space, bool exhaustive = true)
Definition at line 117 of file rc_lattice.cpp.
References _exhaustiveImageFind(), and rmAssert.
 {
     if (exhaustive)
         return _exhaustiveImageFind (moving, fixed, mask, locations, space);
     {
       rmAssert (0);
     }
 }
template<class T > void rfPrintCorrSpace (rcWindow & space, T precision, float quantization)
Definition at line 100 of file rc_diamondscan.h.
References endl(), rcWindow::height(), rcWindow::pelPointer(), and rcWindow::width().
 {
   int32 i;
   cerr << ">>>>>>>>>>>>>>>>>>>>>>>>>" << endl;
   cerr.setf (ios::fixed);
   cerr << setprecision (4);
   for (int32 j = 0; j < space.height(); j++)
     {
       for (i = 0; i < space.width() - 1; i++)
     cerr << setw(3) << ((*((T *) (space.pelPointer(i, j)))) * precision) / quantization  << "-";
       cerr << setw(3) << ((*((T *) (space.pelPointer(i, j)))) * precision) / quantization  << endl;
     }
   cerr << "<<<<<<<<<<<<<<<<<<<<<<<<<" << endl;
 }
void rfPrintFindList (const rcFindList & l, ostream & os)