Visible: src/visual/code/rc_affine.cpp File Reference
rc_affine.cpp File Reference
#include <rc_affine.h>
#include <iostream>
Functions
void rfAffineRectangleToSegmentsCollection (const rcAffineRectangle &p, rcVisualSegmentCollection &v)
Function Documentation
void rfAffineRectangleToSegmentsCollection (const rcAffineRectangle & p, rcVisualSegmentCollection & v)
Definition at line 45 of file rc_affine.cpp.
References rcAffineRectangle::affineToImage(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
 {
   const rc2Dvector ul = p.affineToImage(rc2Dvector(0, 0));
   const rc2Dvector ur = p.affineToImage(rc2Dvector(1, 0));
   const rc2Dvector ll = p.affineToImage(rc2Dvector(0, 1));
   const rc2Dvector lr = p.affineToImage(rc2Dvector(1, 1));
   v.push_back(rcVisualLine(rc2Fvector((float)ul.x(), (float)ul.y()),
                rc2Fvector((float)ur.x(), (float)ur.y())));
   v.push_back(rcVisualLine(rc2Fvector((float)ur.x(), (float)ur.y()),
                rc2Fvector((float)lr.x(), (float)lr.y())));
   v.push_back(rcVisualLine(rc2Fvector((float)lr.x(), (float)lr.y()),
                rc2Fvector((float)ll.x(), (float)ll.y())));
   v.push_back(rcVisualLine(rc2Fvector((float)ll.x(), (float)ll.y()),
                rc2Fvector((float)ul.x(), (float)ul.y())));
   v.push_back(rcVisualEmpty());
 }