Visible: include/util/rc_utdrawutils.h File Reference
rc_utdrawutils.h File Reference
#include <rc_window.h>
#include <iomanip>
Macros
#define rmPrintImage(a)
Functions
static void rfDrawShape (rcWindow &image, char **shape, int32 x=0, int32 y=0, int32 scale=1)
static void rfDrawCylinder (deque< rcWindow > &cylinder, rc2Dvector center, double ra, double rb)
static void rfDrawCircle (rc2Dvector center, int32 r, rcWindow &dst, uint8 circleColor, uint8 backgroundColor)
static void rfDrawCircle (rc2Dvector center, int32 r, rcWindow &dst, uint8 circleColor)
static int32 drawCells (rcWindow &w, int32 size, int32 spacing, uint8 circleColor, uint8 backgroundColor)
static void rfDrawLine (rcWindow &image, rcIPair &p1, rcIPair &p2, uint8 ink)
static void MakeSineTab (void)
static rcWindow rc_zonePlate (long width, long height, long scale)
Variables
static unsigned char sineTab [256]
Macro Definition Documentation
#define rmPrintImage (a)
Value:
{               \
  cout << (a).width() << "," << (a).height() << endl; \
  cout << "||--";                   \
  for (int32 i = 0; i < (a).width(); i++)   \
    cout << setw (4) << i;      \
  cout << endl;                     \
  for (int32 j = 0; j < (a).height(); j++)  \
    {                       \
      cout << "[" << setw (4) << j << "]";          \
      for (int32 i = 0; i < (a).width(); i++)   \
    {                       \
      if ((a).depth() != 8)             \
        cout <<  setw(4) << (int32) ((a).getPixel (i, j));       \
      else cout <<   setw(4) << setprecision(2) << (a).getDoublePixel (i, j);  \
    }                       \
      cout << endl;                 \
    }}
Definition at line 52 of file rc_utdrawutils.h.
Function Documentation
static int32 drawCells (rcWindow & w, int32 size, int32 spacing, uint8 circleColor, uint8 backgroundColor) static
Definition at line 177 of file rc_utdrawutils.h.
References rfDrawCircle(), rcWindow::setAllPixels(), rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
    int32 r = size / (spacing * 3);
    rcWindow dis (size, size);
    dis.setAllPixels (uint32 (backgroundColor));
    int32 n = (size -4*r) / (r+r+r);
    for (int32 i = 0; i < n; i++)
    {
       for (int32 j = 0; j < n; j++)
       {
           rc2Dvector center (static_cast<double>(r), static_cast<double>(r));
           rc2Dvector pos (static_cast<double>((i+1)*3*r), static_cast<double>((j+1)*3*r));
           rcWindow tmp (dis, static_cast<int32>(pos.x() - r), static_cast<int32>(pos.y()) - r, r+r, r+r);
           rfDrawCircle (center, r, tmp, circleColor, backgroundColor);
       }
    }
    w = dis;
    return n*n;
 }
static void MakeSineTab (void) static
Definition at line 251 of file rc_utdrawutils.h.
References rkPI, sin(), and sineTab.
 {
   long i;
   for (i = 0; i < 256; i++)
     {
       sineTab[i] = (uint8) (127.5 * sin(rkPI * (i - 127.5) / 127.5) + 127.5);
     }
 }
static rcWindow rc_zonePlate (long width, long height, long scale) static
Definition at line 261 of file rc_utdrawutils.h.
References rcWindow::setPixel(), and sineTab.
 {
   long cX, cY;
   long i, j;
   long x, y;
   long d;
   cX = width / 2;
   cY = height / 2;
   rcWindow rw (width, height);
   for (i = height, y = -cY; i--; y++)
     {
       for (j = width, x = -cX; j--; x++)
     {
       d = ((x * x + y * y) * scale) >> 8;
       rw.setPixel(j, i, sineTab[d & 0xFF]);
     }
     }
   return rw;
 }
static void rfDrawCircle (rc2Dvector center, int32 r, rcWindow & dst, uint8 circleColor, uint8 backgroundColor) static
Definition at line 148 of file rc_utdrawutils.h.
References rc2dVector< T >::distance(), rcWindow::height(), rcWindow::setAllPixels(), rcWindow::setPixel(), and rcWindow::width().
 {
    dst.setAllPixels (uint32 (backgroundColor));
    for(int32 i=0;i< dst.width();i++)
    {
       for(int32 j=0;j< dst.height(); j++)
       {
          rc2Dvector pos(i+0.5,j+0.5);
          if (center.distance (pos) <= r) dst.setPixel (i,j,circleColor);
       }
    }
 }
static void rfDrawCircle (rc2Dvector center, int32 r, rcWindow & dst, uint8 circleColor) static
Definition at line 163 of file rc_utdrawutils.h.
References rc2dVector< T >::distance(), rcWindow::height(), rcWindow::setPixel(), and rcWindow::width().
 {
    for(int32 i=0;i< dst.width();i++)
    {
       for(int32 j=0;j< dst.height(); j++)
       {
          rc2Dvector pos(i+0.5,j+0.5);
          if (center.distance (pos) <= r) dst.setPixel (i,j,circleColor);
       }
    }
 }
static void rfDrawCylinder (deque< rcWindow > & cylinder, rc2Dvector center, double ra, double rb) static
Definition at line 103 of file rc_utdrawutils.h.
References rc2dVector< T >::distance(), rmMax, and rmMin.
 {
   for (uint32 i = 0; i < cylinder.size(); i++)
     cylinder[i].setAllPixels (0);
   int32 width (cylinder[0].width());
   int32 height (cylinder[0].height());
   double dIdT = cylinder.size() / 255.0;
   double iDiDt (0.0);
   double minR = rmMin (ra, rb);
   double maxR = rmMax (ra, rb);
   // Basic Linear Model
   // TBD: Support power law models
   // Forward Diffusion
   for (uint32 tt = 0; tt < cylinder.size(); tt++)
     for(int32 i=0;i< width;i++)
       {
     for(int32 j=0;j< height; j++)
       {
         rc2Dvector pos(i+0.5,j+0.5);
         if (center.distance (pos) <= maxR)
           cylinder[tt].setPixel (i,j,uint32 (iDiDt));
         iDiDt += dIdT;
       }
       }
   // Reverse Diffusion
   iDiDt = 0.0;
   for (uint32 tt = 0; tt < cylinder.size(); tt++)
     for(int32 i=0;i< width;i++)
       {
     for(int32 j=0;j< height; j++)
       {
         rc2Dvector pos(i+0.5,j+0.5);
         if (center.distance (pos) <= minR)
           cylinder[tt].setPixel (i,j,255 - uint32 (iDiDt));
         iDiDt += dIdT;
       }
       }
 }
static void rfDrawLine (rcWindow & image, rcIPair & p1, rcIPair & p2, uint8 ink) static
Definition at line 203 of file rc_utdrawutils.h.
References rmABS, rmSGN, rcWindow::setPixel(), rcPair< T >::x(), and rcPair< T >::y().
 {
   int32& x1 = p1.x();
   int32& y1 = p1.y();
   int32& x2 = p2.x();
   int32& y2 = p2.y();
   int32 d, x, y, ax, ay, sx, sy, dx, dy;
   dx = x2-x1; ax = rmABS(dx)<<1; sx = rmSGN(dx);
   dy = y2-y1; ay = rmABS(dy)<<1; sy = rmSGN(dy);
   x = x1;
   y = y1;
   if (ax>ay) { /* x dominant */
     d = ay-(ax>>1);
     for (;;) {
       image.setPixel (x, y, ink);
       if (x==x2) return;
       if (d>=0) {
     y += sy;
     d -= ax;
       }
       x += sx;
       d += ay;
     }
   }
   else { /* y dominant */
     d = ax-(ay>>1);
     for (;;) {
       image.setPixel (x, y, ink);
       if (y==y2) return;
       if (d>=0) {
     x += sx;
     d -= ay;
       }
       y += sy;
       d += ax;
     }
   }
 }
static void rfDrawShape (rcWindow & image, char ** shape, int32 x = 0, int32 y = 0, int32 scale = 1) static
Definition at line 75 of file rc_utdrawutils.h.
References rcWindow::setAllPixels(), and rcWindow::setPixel().
 {
    char **s;
    int32 width = x;
    int32 height = y;
    for(s = shape; *s; s++,height += scale)
    {
       int32 this_width = strlen(*s)*scale + x;
       if(this_width > width)
          width = this_width;
    }
    rcWindow src(width,height);
    src.setAllPixels (int32(0));
    for( ; *shape; shape++)
    {
       for(char *valPtr = *shape; *valPtr; valPtr++)
          for(int32 xx = 0; xx < scale; xx++)
             for(int32 yy = 0; yy < scale; yy++)
                src.setPixel(x + (valPtr - *shape)*scale + xx,y + yy,
                        (uint32)(*valPtr - '0'));
       y += scale;
    }
    image = src;
 }
Variable Documentation
unsigned char sineTab[256] static
Definition at line 247 of file rc_utdrawutils.h.
Referenced by MakeSineTab(), and rc_zonePlate().