Visible: src/util/code/rc_timestamp_mac.cpp File Reference
rc_timestamp_mac.cpp File Reference
#include <rc_exception.h>
#include <sys/time.h>
#include <rc_timestamp.h>
Functions
int64 getCurrentTimestamp (void)
double getTimestampResolution (void)
Variables
static const int64 cMicrosPerSec = 1000000
static const double cResolution = 1.0/cMicrosPerSec
Function Documentation
int64 getCurrentTimestamp (void)
Definition at line 17 of file rc_timestamp_mac.cpp.
References cMicrosPerSec, and NULL.
Referenced by rcGenMovieFile::initHeader(), rcTimestamp::now(), and rcKinetoscope::updateProcessingTime().
 {
     // TODO: use high resolution clock
     struct timeval t;
 #if 1
     // Warning: gettimeofday values do not always monotonically increase
     if ( gettimeofday( &t, NULL ) != 0 )
         throw general_exception( "timestamp not available" );
 #else
     // Hack from Apple technical support
     // TODO: validate that this works, it seems that sometimes 0 is returned in t
 #include <sys/syscall.h>
     if ( syscall(SYS_gettimeofday, &t, NULL) < 0 )
         throw general_exception( "timestamp not available" );
 #endif
     int64 now = t.tv_sec * cMicrosPerSec + t.tv_usec;
     return now;
 }
double getTimestampResolution (void)
Definition at line 39 of file rc_timestamp_mac.cpp.
References cResolution.
Referenced by convertSecondsToTimestamp(), convertTimestampToSeconds(), rcWindow::randomFill(), and rcUnitTest::randomSeed().
 {
     return cResolution;
 }
Variable Documentation
const int64 cMicrosPerSec = 1000000 static
Definition at line 13 of file rc_timestamp_mac.cpp.
Referenced by getCurrentTimestamp().
const double cResolution = 1.0/cMicrosPerSec static
Definition at line 14 of file rc_timestamp_mac.cpp.
Referenced by getTimestampResolution().