Visible: include/analysis/rc_kineticimage.h File Reference
rc_kineticimage.h File Reference
#include <rc_types.h>
#include <rc_window.h>
Classes
class rcOptoKineticImage
Functions
float segPoint (const rcWindow &measured, float minBinVal, float binSz, int32 binCnt, bool getPeak)
void genSynthSignal (uint32 period, uint32 pulseWidth, uint8 fg, uint8 bg, uint8 smooth, vector< uint8 > &signal)
void genSpatialSDImg (const rcWindow &src, rcWindow &dest, int32 radius)
double genSpatialSDSum (const rcWindow &src, int32 radius)
void genLogRMS (rcWindow freqImg)
float segPointByEnergy (const rcWindow &measured, float minVal, float maxVal, float binSz, float threshPct, vector< rcWindow > &movie)
int32 calcExtendedMuscleCellFrame (const deque< double > &signal, const vector< rcWindow > &movie, int32 movieOffset)
float calcMusclePeriod (const vector< rcWindow > &movie, uint32 startFrame, uint32 endFrame, uint32 mdlIndex, float maxFramesPerPeriod)
Function Documentation
int32 calcExtendedMuscleCellFrame (const deque< double > & signal, const vector< rcWindow > & movie, int32 movieOffset)
Definition at line 499 of file rc_kineticimage.cpp.
References rcStatistics::add(), CEMCF_PRT1, CEMCF_PRT2, genSpatialSDSum(), and rmAssert.
Referenced by rcMuscleSegmenter::getEMI().
 {
   if (CEMCF_PRT1)
     printf("cEMCF: signal sz %d offset %d\n", (int)signal.size(), movieOffset);
   rmAssert(signal.size());
   rmAssert(movieOffset >= 0);
   rmAssert(((int32)movie.size() - movieOffset) >= (int32)signal.size());
   rcStatistics stats;
   for (uint32 ii = 0; ii < signal.size(); ii++)
     stats.add(signal[ii]);
   double hiThreshSD = stats.mean() + 2*stats.stdDev();
   double hiThreshMM =
     stats.max() - (stats.max() - stats.min())*0.05;
   double loThreshSD = stats.mean() - 2*stats.stdDev();
   double loThreshMM =
     stats.min() + (stats.max() - stats.min())*0.05;
   double hiThresh =
     hiThreshSD < hiThreshMM ? hiThreshSD : hiThreshMM;
   double loThresh =
     loThreshSD > loThreshMM ? loThreshSD : loThreshMM;
   if (CEMCF_PRT1) printf("cEMCF: hi %f lo %f mean %f sd %f min %f max %f\n",
              hiThresh, loThresh, stats.mean(),
              stats.stdDev(),  stats.min(), stats.max());
   deque<double> tempSig(signal.size());
   double peakVal = -1.0;
   int32 peakFrameIndex = -1;
   int32 curRunLth = 0, curRunIndex = -1;
   int32 peakRunLth = 0, peakRunIndex = -1;
   if (CEMCF_PRT2) printf("cEMCF: input signal:\n");
   for (uint32 ii = 0; ii < signal.size(); ii++) {
     uint32 val;
     if (signal[ii] > hiThresh) {
       val = 2;
       if (curRunIndex == -1) {
     curRunIndex = ii;
     curRunLth = 0;
       }
       curRunLth++;
     }
     else {
       val = (signal[ii] < loThresh) ? 0 : 1;
       if (curRunIndex != -1) {
     if (peakRunLth < curRunLth) {
       peakRunLth = curRunLth;
       peakRunIndex = curRunIndex;
     }
     curRunIndex = -1;
       }
     }
     if (CEMCF_PRT2) printf("  %03d: %d  %f\n", ii, val, signal[ii]);
     tempSig[ii] = val;
     if (signal[ii] > peakVal) {
       peakVal = signal[ii];
       peakFrameIndex = ii;
     }
   }
   if ((curRunIndex != -1) && (peakRunLth < curRunLth)) {
     peakRunLth = curRunLth;
     peakRunIndex = curRunIndex;
   }
   if (CEMCF_PRT2) printf("\n");
   /* Search for an extended muscle cell. The following strategy will
    * be used:
    *
    * 1 - See if any run of 3 or more frames was found that all exceed
    *     the high threshold. If so, pick the peak value from this set.
    *
    * 2 - If 1) fails the assumption will be that we are in the case
    *     where the extended resting phase never lasts more than 1
    *     frame. In this case, pick two consecutive peaks under the
    *     assumption that 1 will be a fully extended frame and the
    *     other is a fully contracted frame. The one that has the
    *     higher amount of edge information will be picked as the
    *     extended frame.
    */
   if (peakRunLth > 2) {
     peakVal = -1.0;
     peakFrameIndex = -1;
     for (int32 ii = peakRunIndex; ii < peakRunIndex + peakRunLth; ii++)
       if (signal[ii] > peakVal) {
     peakVal = signal[ii];
     peakFrameIndex = ii;
       }
     if (CEMCF_PRT1)
       printf("cEMCF: peakRunIndex %d peakRunLth (%d) > 2, peak @ %d\n",
          peakRunIndex, peakRunLth, peakFrameIndex);
   }
   else {
     if (CEMCF_PRT1)
       printf("cEMCF: peakRunLth (%d) < 3\n", peakRunLth);
     /* Search both forward and backward for a second peak. Use the
      * second peak that is closest. This is to try and limit the cases
      * where the second peak is actually from a different pulse of the
      * cell.
      *
      * Note: During search, the end of the current peak must be found
      * first. This is the purpose of foundEdge.
      */
     int32 peakFrameIndexFwd;
     bool foundEdge = false;
     for (peakFrameIndexFwd = peakFrameIndex + 1;
      peakFrameIndexFwd < (int32)tempSig.size();
      peakFrameIndexFwd++) {
       if (tempSig[peakFrameIndexFwd] == 2) {
     if (foundEdge)
       break;
       }
       else
     foundEdge = true;
     }
     int32 peakFrameIndexRev;
     foundEdge = false;
     for (peakFrameIndexRev = peakFrameIndex - 1;
      peakFrameIndexRev >= 0;
      peakFrameIndexRev--) {
       if (tempSig[peakFrameIndexRev] == 2) {
     if (foundEdge)
       break;
       }
       else
     foundEdge = true;
     }
     int32 peakFrameIndex2 = -1;
     if (peakFrameIndexFwd == (int32)tempSig.size())
       peakFrameIndex2 = peakFrameIndexRev; // Either valid or -1
     else if (peakFrameIndexRev == -1)
       peakFrameIndex2 = peakFrameIndexFwd;
     else if ((peakFrameIndex - peakFrameIndexRev) <
          (peakFrameIndexFwd - peakFrameIndex))
       peakFrameIndex2 = peakFrameIndexRev;
     else
       peakFrameIndex2 = peakFrameIndexFwd;
     if (peakFrameIndex2 != -1) {
       double sum = genSpatialSDSum(movie[movieOffset+peakFrameIndex], 1);
       double sum2 = genSpatialSDSum(movie[movieOffset+peakFrameIndex2], 1);
       if (CEMCF_PRT1)
     printf("cEMCF: Dual peaks, values %f @ %d and %f @ %d",
            sum, peakFrameIndex, sum2, peakFrameIndex2);
       if (sum2 > sum)
     peakFrameIndex = peakFrameIndex2;
       if (CEMCF_PRT1) printf(", peak @ %d\n", peakFrameIndex);
     }
     else if (CEMCF_PRT1)
       printf("cEMCF: Single peak @ %d\n", peakFrameIndex);
   }
   rmAssert(peakFrameIndex > -1);
   return peakFrameIndex;
 }
float calcMusclePeriod (const vector< rcWindow > & movie, uint32 startFrame, uint32 endFrame, uint32 mdlIndex, float maxFramesPerPeriod)
Definition at line 675 of file rc_kineticimage.cpp.
References rs1DFourierResult::amplitude, CMP_PRT1, CMP_PRT2, rcSimilarator::eACI, rcSimilarator::eExhaustive, rcSimilarator::entropies(), rcSimilarator::fill(), rcCorr::r(), rc1DFourierForceFFT, rc1DFourierRaisedCosine, rcPixel8, rf1DFourierAnalysis(), rf1DPeakDetect(), rfCorrelate(), rmAssert, rcSimilarator::update(), and rs1DFourierResult::workingSz.
Referenced by rcMuscleSegmenter::genFrequencySegmentation().
 {
   rmAssert(endFrame < movie.size());
   rmAssert(mdlIndex >= startFrame && mdlIndex < endFrame);
   rmAssert(maxFramesPerPeriod > 0.0);
   /* Calculate the average number of frames per muscle contraction
    * using the following method:
    *
    * - Calculate a 1D correlation signal based on comparing the image
    *   at mdlIndex with all the others in the sampling interval.
    *
    * - Perform an FFT analysis of this signal.
    *
    * - Peak detect the resulting frequency space.
    *
    * - Determine the dominant frequency from the list of peaks. The
    *   following special rules will be applied:
    *
    *   - Discount any frequencies below a minimum value as determined
    *     by maxFramesPerPeriod.
    *
    *   - Try to detect the true frequency of narrow peaked input
    *     signals by looking for the resultant flat frequency space.
    */
   const uint32 sigSz = endFrame-startFrame;
   deque<double> sig(sigSz);
   rsCorrParams params;
   rcCorr res;
   if (CMP_PRT1) fprintf(stderr, "Input signal\n");
 #if 0
   vector<rcWindow> fillers(3);
   rcSimilarator selfsim (rcSimilarator::eExhaustive,
              rcPixel8, 3, 0);
   uint32 i;
   for (i = startFrame; i < (startFrame+3); i++)
     {
       fillers[i - startFrame] = movie[i];
     }
   selfsim.fill (fillers);
   deque<double> tsig;
   bool rval = selfsim.entropies (tsig,rcSimilarator::eACI);
   sig[0] = tsig[1];
   for (uint32 j = 1; i < endFrame; i++, j++)
     {
       rval = selfsim.update (movie[i]);
       rmAssert (rval);
       selfsim.entropies(tsig, rcSimilarator::eACI);
       sig[j] = tsig[1];
   }
 #else
   uint32 curMdlIndex = mdlIndex, prevMdlIndex = mdlIndex;
   if (mdlIndex > startFrame) {
     uint32 i = mdlIndex;
     do {
       i--;
       rfCorrelate(movie[i], movie[curMdlIndex], params, res);
       sig[i-startFrame] = res.r();
       if (sig[i-startFrame] >= 0.95) {
     rfCorrelate(movie[i], movie[prevMdlIndex], params, res);
     if (res.r() >= 0.95) {
       prevMdlIndex = curMdlIndex;
       curMdlIndex = i;
       if (CMP_PRT2)
         fprintf(stderr, "Score %f (%f) New mdl index %d\n",
             sig[i-startFrame], res.r(), curMdlIndex);
     }
       }
     } while ( i != startFrame);
   }
   curMdlIndex = prevMdlIndex = mdlIndex;
   for (uint32 i = mdlIndex+1; i < endFrame; i++) {
     rfCorrelate(movie[i], movie[curMdlIndex], params, res);
     sig[i-startFrame] = res.r();
     if (sig[i-startFrame] >= 0.95) {
     rfCorrelate(movie[i], movie[prevMdlIndex], params, res);
     if (res.r() >= 0.95) {
       prevMdlIndex = curMdlIndex;
       curMdlIndex = i;
       if (CMP_PRT2)
         fprintf(stderr, "Score %f (%f) New mdl index %d\n",
             sig[i-startFrame], res.r(), curMdlIndex);
     }
     }
   }
   if (mdlIndex == startFrame) {
     if (sig[1] >= 0.95)
       sig[0] = sig[1];
     else
       sig[0] = 1.0;
   }
   else if (mdlIndex == (endFrame-1)) {
     if (sig[sigSz-2] >= 0.95)
       sig[sigSz-1] = sig[sigSz-2];
     else
       sig[sigSz-1] = 1.0;
   }
   else {
     double cand = sig[mdlIndex-1-startFrame];
     if (cand < sig[mdlIndex+1-startFrame])
       cand = sig[mdlIndex+1-startFrame];
     if (cand >= 0.95)
       sig[mdlIndex-startFrame] = cand;
     else
       sig[mdlIndex-startFrame] = 1.0;
   }
   if (CMP_PRT1) {
     for (uint32 i = 0; i < sigSz; i++)
       fprintf(stderr, "%d: %f\n", i, sig[i]);
   }
 #endif
   rs1DFourierResult rslt;
   rf1DFourierAnalysis(sig, rslt, rc1DFourierForceFFT |rc1DFourierRaisedCosine);
   vector<uint32> peakLocs;
   vector<float> interLocs, interVals;
   rf1DPeakDetect(rslt.amplitude, peakLocs, interLocs,
          interVals, 0.10f);
   float minFrequency = rslt.workingSz/maxFramesPerPeriod - 0.5;
   /* Find the the frequency, greater than minFrequency, with the
    * greatest amplitude.
    */
   uint32 maxFreqIndex = 0;
   float maxAmplitude = -1.0;
   for (uint32 ii = 0; ii < peakLocs.size(); ii++) {
     if ((interLocs[ii] > minFrequency) && (interVals[ii] > maxAmplitude)) {
       maxFreqIndex = ii;
       maxAmplitude = interVals[ii];
     }
     if (1)
       fprintf(stderr, " (%d %f) inter: (%f, %f)\n",
           peakLocs[ii], rslt.amplitude[peakLocs[ii]],
           interLocs[ii], interVals[ii]);
   }
   if (1)
     fprintf(stderr, "maxAmplitude %f maxFreqIndex %d minFrequency %f\n",
         maxAmplitude, maxFreqIndex, minFrequency);
   if (maxAmplitude == -1.0)
     return 0.0;
   /* Now check to see if the frequency space is "flat". My definition
    * will be frequencies within 10% of the peak amplitude
    */
   for (uint32 ii = 0; ii < maxFreqIndex; ii++) {
     if ((interLocs[ii] > minFrequency) &&
     (interVals[ii] > maxAmplitude*0.9)) {
       if (1)
     fprintf(stderr, "Flat peak detected - @ %d: loc %f amp %f\n",
         ii, interLocs[ii], interVals[ii]);
       return rslt.workingSz/interLocs[ii];
     }
   }
   if (1)
     fprintf(stderr, "Return max peak - @ %d: loc %f amp %f\n",
         maxFreqIndex, interLocs[maxFreqIndex],
         interVals[maxFreqIndex]);
   return rslt.workingSz/interLocs[maxFreqIndex];
 }
void genLogRMS (rcWindow freqImg)
void genSpatialSDImg (const rcWindow & src, rcWindow & dest, int32 radius)
Definition at line 288 of file rc_kineticimage.cpp.
References rsCorr3by3Line::count, rcWindow::depth(), rcAutoCorrelation::eFull, rcWindow::height(), rcPixel32, rcPixel8, rfGaussianConv(), rmAssert, rcWindow::rowPointer(), rsCorr3by3Line::score, rcAutoCorrelation::update(), rcWindow::width(), and rcPair< T >::x().
Referenced by rcMuscleSegmenter::genSpatialSegmentation().
 {
   rmAssert(radius >= 0);
   rmAssert(src.depth() == rcPixel8);
   rmAssert(dest.depth() == rcPixel32);
   rmAssert(src.width() == dest.width() + 2*(radius+1));
   rmAssert(src.height() == dest.height() + 2*(radius+1));
 #if 0
   rcAutoCorrelation ac;
   rsCorr3by3Line result;
   rcWindow smooth (src.width(), src.height());
   rfGaussianConv (src, smooth, uint32 (5));
   ac.update(smooth, 1, rcAutoCorrelation::eFull, rcAutoCorrelation::eLine);
   rcIPair searchSize((radius+1)*2 + 1, (radius+1)*2 + 1);
   const int32 height = dest.height();
   const int32 width = dest.width();
   // @note use vsqrtd () in Accelerate.framework/Frameworks/vecLib.framework/Headers/vfp.h
   double szNorm = searchSize.x()*(searchSize.x() - 1);
   for (int32 y = 0; y < height; y++) {
     ac.gen3by3Line(searchSize, y, result);
     rmAssert((int32)result.count == width);
     float* destP = (float*)dest.rowPointer(y);
     for (uint32 x = 0; x < result.count; x++)
       destP[x] = (float)sqrt(*(result.score[1][1] + x)/szNorm);
   }
 #endif
 }
double genSpatialSDSum (const rcWindow & src, int32 radius)
Definition at line 324 of file rc_kineticimage.cpp.
References rsCorr3by3Line::count, rcWindow::depth(), rcAutoCorrelation::eFull, rcWindow::height(), rcPixel8, rmAssert, rsCorr3by3Line::score, and rcWindow::width().
Referenced by calcExtendedMuscleCellFrame().
 {
   rmAssert(radius >= 0);
   rmAssert(src.depth() == rcPixel8);
   rcAutoCorrelation ac;
   rsCorr3by3Line result;
 #if 0
   ac.update(src, 1, rcAutoCorrelation::eFull, rcAutoCorrelation::eLine);
   rcIPair searchSize((radius+1)*2 + 1, (radius+1)*2 + 1);
   const int32 height = src.height() - 2*(radius+1);
   const int32 width = src.width() - 2*(radius+1);
   double retVal = 0.0;
   for (int32 y = 0; y < height; y++) {
     ac.gen3by3Line(searchSize, y, result);
     rmAssert((int32)result.count == width);
     for (uint32 x = 0; x < result.count; x++)
       retVal += *(result.score[1][1] + x);
   }
   return retVal;
 #endif
 }
void genSynthSignal (uint32 period, uint32 pulseWidth, uint8 fg, uint8 bg, uint8 smooth, vector< uint8 > & signal)
Definition at line 257 of file rc_kineticimage.cpp.
References gaussRing(), NR::period(), and rmAssert.
Referenced by rcOptoKineticImage::gen1DCorrKineticImgs().
 {
   rmAssert(pulseWidth <= period);
   signal.resize(period);
   if (!period)
     return;
   vector<uint8> signal2(period);
   for (uint32 i = 0; i < pulseWidth; i++)
     signal[i] = fg;
   for (uint32 i = pulseWidth; i < period; i++)
     signal[i] = bg;
   for (uint32 i = 0; i < smooth; i++) {
     if (i & 1)
       gaussRing(signal2, signal);
     else
       gaussRing(signal, signal2);
   }
   if (smooth & 1) {
     for (uint32 i = 0; i < period; i++)
       signal[i] = signal2[i];
   }
 }
float segPoint (const rcWindow & measured, float minBinVal, float binSz, int32 binCnt, bool getPeak)
Definition at line 34 of file rc_kineticimage.cpp.
References rcWindow::depth(), rcWindow::height(), N, rcPixel32, rmAssert, rcWindow::rowPointer(), shannon(), and rcWindow::width().
Referenced by rcMuscleSegmenter::genSpatialSegmentation().
 {
   rmAssert(binSz > 0);
   rmAssert(binCnt > 0);
   rmAssert(rcPixel32 == measured.depth());
   const int32 width = measured.width(), height = measured.height();
   /* Initialize histogram.
    */
   vector<int32> hist(binCnt);
   for (int32 i = 0; i < binCnt; i++)
     hist[i] = 0;
   int32 overflow = 0;
   /* Fill histogram.
    */
   const float cutoff = minBinVal - binSz + 0.0000001;
   const float binSzInv = 1/binSz;
   const double dBinCnt = binCnt;
   if (0) printf("cutoff %f binSzInv %f dBinCnt %f\n", cutoff, binSzInv, dBinCnt);
   for (int32 y = 0; y < height; y++) {
     float* valP = (float*)measured.rowPointer(y);
     for (int32 x = 0; x < width; x++) {
       int32 index = 0;
       float val = *valP++;
       if (val > cutoff) {
     double dIndex = (val - cutoff)*binSzInv; // Double avoids overflows
     if (dIndex >= dBinCnt) {
       overflow++;
       continue;
     }
     index = (int32)dIndex;
       }
       rmAssert(index >= 0 && index < binCnt);
       hist[index]++;
     }
   }
   /* Convert to cumulative histogram.
    */
   for (int32 si = 1; si < binCnt; si++)
     hist[si] += hist[si-1];
   /* Create the correlation matrix.
    */
   rmAssert(width*height == hist[binCnt-1]+overflow);
   double** corrMatrix;
   corrMatrix = (double**)malloc(binCnt*sizeof(double*));
   rmAssert(corrMatrix);
   double* matrixBase = (double*)malloc(binCnt*binCnt*sizeof(double));
   rmAssert(matrixBase);
   for (int32 i = 0; i < binCnt; i++)
     corrMatrix[i] = matrixBase + (i*binCnt);
   /* Fill in correlation matrix.
    */
   for (int32 i = 0; i < binCnt; i++)
     corrMatrix[i][i] = 1.0;
   const double N = width*height;
   for (int32 m = 0; m < binCnt; m++) {
     const double mCnt = N - hist[m];
     const double em = N*mCnt - mCnt*mCnt;
     if (em == 0) {
       for (int32 i = m+1; i < binCnt; i++)
     corrMatrix[i][m] = corrMatrix[m][i] = 1.0;
     }
     else {
       for (int32 i = m+1; i < binCnt; i++) {
     const double iCnt = N - hist[i];
     const double eiXem = (N - iCnt)*iCnt*em;
     if (eiXem == 0) {
       corrMatrix[i][m] = corrMatrix[m][i] = 1.0;
       continue;
     }
     rmAssert(mCnt >= iCnt);
     const double cross = (N - mCnt)*iCnt;
     const double corr = corrMatrix[m][i] = cross*cross/eiXem;
     corrMatrix[i][m] = (corr < 1.0) ? corr : 1.0;
       }
     }
   }
   /* Calculate entropy signal.
    */
   vector<double> sums(binCnt);
   vector<double> entropies(binCnt);
   for (int32 i = 0; i < binCnt; i++) {
     sums[i] = corrMatrix[i][i];
     entropies[i] = 0.0;
   }
   for (int32 i = 0; i < (binCnt-1); i++)
     for (int32 j = (i+1); j < binCnt; j++) {
       sums[i] += corrMatrix[i][j];
       sums[j] += corrMatrix[i][j];
     }
   const double log2N = log2(N);
   for (int32  i = 0; i < binCnt; i++) {
     for (int32 j = i; j < binCnt; j++) {
       double rr =
     corrMatrix[i][j]/sums[i]; // Normalize for total energy in samples
       entropies[i] += shannon(rr);
       if (i != j) {
     rr = corrMatrix[i][j]/sums[j]; //Normalize for total energy in samples
     entropies[j] += shannon(rr);
       }
     }
     entropies[i] = entropies[i]/log2N;// Normalize for count of samples
   }
   /* Done with correlation matrix - free it.
    */
   free(matrixBase);
   free(corrMatrix);
   if (0) {
     for (int32 i = 0; i < binCnt; i++)
       printf("%d: %f\n", i, entropies[i]);
   }
   /* Find segmentation point. If getPeak is true, just return the point
    * corresponding to the maximum entropy location.
    */
   if (getPeak) {
     int32 maxBin = 0;
     double maxVal = entropies[0];
     for (int32 bin = 1; bin < binCnt; bin++) {
       if (entropies[bin] > maxVal) {
     maxBin = bin;
     maxVal = entropies[bin];
       }
     }
     return minBinVal + maxBin*binSz;
   }
   /* Find segmentation point by breaking the source image into two
    * regions: inside and outside. In our case, this will typically
    * mean a cell, but that's not required. The two requirements are:
    *
    *   1) the measured quality is greater on the inside than the outside.
    *
    *   2) the measured quality becomes relatively stable within the inner
    *      region (at least up to the values represented in the last bin
    *      of the cumulative histogram).
    *
    * Given that these are true, then the entropy signal should take on
    * the following characteristics. At the high end (higher indices),
    * there should be a relatively flat parabola. This is the region of
    * values that indicate inside pixels. Past this there will be a
    * relatively quick drop off. Possibly some additional rises and
    * fall will occur as you move towards the low end, but these will
    * be ignored. All these values are considered to be outside pixels.
    *
    * The following finds the location of the first bin at the lower
    * end of the parabola that has a higher entropy signal value than
    * that at the high end. This bin index is then used to calculate
    * the segementation point.
    */
   double segCutOff = entropies[binCnt-1];
   int32 curBin = -1;
   double minVal = 1e99;
   for (int32 bin = 0; bin < binCnt; bin++) {
     if (entropies[bin] < minVal) {
       curBin = bin;
       minVal = entropies[bin];
     }
   }
   rmAssert(curBin >= 0);
   for ( ; curBin < binCnt; curBin++) {
     if (entropies[curBin] > segCutOff)
       break;
   }
   /* Low end has been found. Convert bin index to its corresponding
    * measurement value.
    */
   return minBinVal + curBin*binSz;
 }
float segPointByEnergy (const rcWindow & measured, float minVal, float maxVal, float binSz, float threshPct, vector< rcWindow > & movie)
Definition at line 379 of file rc_kineticimage.cpp.
References binarize(), rcWindow::depth(), rcSimilarator::eACI, rcSimilarator::eExhaustive, eMovie, rcSimilarator::entropies(), rcSimilarator::fill(), rcWindow::height(), rcPixel32, rcPixel8, rfPixel8Max3By3(), rfPixel8Min3By3(), rmAssert, rcSimilarator::setMask(), SPBE_PRT1, SPBE_PRT2, rcSimilarator::update(), and rcWindow::width().
 {
   rmAssert(measured.depth() == rcPixel32);
   rmAssert(maxVal > minVal);
   rmAssert(binSz > 0.0);
   rmAssert(threshPct >= 0.0);
   rmAssert(threshPct <= 1.0);
   uint32 mLth = movie.size();
   rmAssert(mLth > 4);
   double baseDelta;
   {
     rcSimilarator energy(rcSimilarator::eExhaustive,
              rcPixel8, 5, 0);
     vector<rcWindow> eMovie;
     eMovie.push_back(movie[0]);
     eMovie.push_back(movie[1]);
     eMovie.push_back(movie[2]);
     eMovie.push_back(movie[3]);
     eMovie.push_back(movie[4]);
     energy.fill(eMovie);
     deque<double> tempSig;
     bool rval = energy.entropies(tempSig, rcSimilarator::eACI);
     rmAssert(rval);
     double minSig = tempSig[2], maxSig = tempSig[2];
     for (uint32 i = 5; i < mLth; i++) {
       rval = energy.update(movie[i]);
       rmAssert(rval);
       energy.entropies(tempSig, rcSimilarator::eACI);
       if (tempSig[1] < minSig)
     minSig = tempSig[2];
       if (tempSig[1] > maxSig)
     maxSig = tempSig[2];
     }
     baseDelta = maxSig - minSig;
   }
   rcWindow mask(measured.width(), measured.height());
   if (SPBE_PRT1) printf("Init State: min %f max %f m sz %d bin sz %f"
             " base delta %f\n",
             minVal, maxVal, mLth, binSz, baseDelta);
   float curVal = minVal;
   float segVal = minVal, segDelta = 1e38;
   for (;;) {
     binarize(measured, mask, curVal, 0x00, 0xFF);
     rcWindow temp(mask.width()-2, mask.height()-2);
     rcWindow mWin(mask, 1, 1,
           mask.width()-2, mask.height()-2);
     rfPixel8Min3By3(mask, temp);
     mWin.copyPixelsFromWindow(temp);
     rfPixel8Max3By3(mask, temp);
     mWin.copyPixelsFromWindow(temp);
     rcSimilarator energy(rcSimilarator::eExhaustive,
              rcPixel8, 5, 0);
     energy.setMask(mask);
     vector<rcWindow> eMovie;
     eMovie.push_back(movie[0]);
     eMovie.push_back(movie[1]);
     eMovie.push_back(movie[2]);
     eMovie.push_back(movie[3]);
     eMovie.push_back(movie[4]);
     energy.fill(eMovie);
     deque<double> tempSig;
     bool rval = energy.entropies(tempSig, rcSimilarator::eACI);
     rmAssert(rval);
     double minSig = tempSig[2], maxSig = tempSig[2];
     for (uint32 i = 5; i < mLth; i++) {
       rval = energy.update(movie[i]);
       rmAssert(rval);
       energy.entropies(tempSig, rcSimilarator::eACI);
       if (tempSig[1] < minSig)
     minSig = tempSig[2];
       if (tempSig[1] > maxSig)
     maxSig = tempSig[2];
     }
     double curDelta = maxSig - minSig;
     if (curDelta < segDelta) {
      segDelta = curDelta;
      segVal = curVal;
     }
     if (SPBE_PRT2)
       printf("curVal %f curDelta %f segVal %f segDelta %f\n",
          curVal, curDelta, segVal, segDelta);
     if (curVal >= maxVal) {
       if (SPBE_PRT1) printf("Returning %f\n", segVal);
       return segVal;
     }
     curVal += 0.1;
   }
   rmAssert(0);
   return 1e38;
 }