Visible: src/visible/src/rc_engineimplcapture.cpp File Reference
rc_engineimplcapture.cpp File Reference
#include <strstream>
#include "rc_engineimpl.h"
#include "rc_engineimplcapture.h"
#include "rc_engineimplsave.h"
#include <rc_dcam.h>
Macros
#define DEBUG_LOG 1
Functions
bool updateControl (const rcVideoCaptureCtrlReader &captureCtrl, const rcAcqInfo &acqInfo, rcAcqControl &acqControl)
Macro Definition Documentation
#define DEBUG_LOG 1
Definition at line 16 of file rc_engineimplcapture.cpp.
Function Documentation
bool updateControl (const rcVideoCaptureCtrlReader & captureCtrl, const rcAcqInfo & acqInfo, rcAcqControl & acqControl)
Definition at line 409 of file rc_engineimplcapture.cpp.
References rcAcqInfo::acqCtrlUpdateID, rcAcqControl::acqCtrlUpdateID, rcAcqControl::binning, rcAcqControl::decimationRate, rcAcqControl::gain, rcVideoCaptureCtrlReader::getBinning(), rcVideoCaptureCtrlReader::getDecimationRate(), rcVideoCaptureCtrlReader::getGain(), rcVideoCaptureCtrlReader::getShutter(), and rcAcqControl::shutter.
Referenced by rcEngineMovieCapture::updateCameraSettings().
 {
     bool update = false;
     if ( acqInfo.acqCtrlUpdateID == acqControl.acqCtrlUpdateID ) {
         uint32 decimationRate = captureCtrl.getDecimationRate();
         if ( decimationRate != acqControl.decimationRate ) {
             acqControl.decimationRate = decimationRate;
             update = true;
         }
         int32 gain = captureCtrl.getGain();
         if ( gain != acqControl.gain ) {
             acqControl.gain = gain;
             update = true;
         }
         int32 shutter = captureCtrl.getShutter();
         if ( shutter != acqControl.shutter ) {
             acqControl.shutter = shutter;
             update = true;
         }
           int32 binning = captureCtrl.getBinning();
         if ( binning != acqControl.binning ) {
             acqControl.binning = binning;
             update = true;
         }
     }
     if ( update )
         acqControl.acqCtrlUpdateID++;
     return update;
 }