Visible: include/visiCore/rc_xmlelem.h File Reference
rc_xmlelem.h File Reference
#include <fstream>
#include <map>
#include <vector>
#include <rc_types.h>
#include <rc_tree.hh>
#include <rc_timestamp.h>
Classes
class rcXMLNameMapper
class rcXMLTimeMapper
class rcXMLOpenTag
class rcXMLCloseTag
class rcXMLEmptyTag
class rcXMLElement
Typedefs
typedef map< std::string,
rcXMLElementType > rcXMLElementNameMap
typedef map< std::string,
rcXMLAttributeType > rcXMLAttributeNameMap
typedef map< rcTimestamp, int32 > rcXMLTimeMap
typedef pair
< rcXMLAttributeType,
std::string > rcAttribute
typedef vector< rcAttribute > rcAttributeList
typedef tree< rcXMLElement > rcXMLElementTree
Functions
ostream & operator<< (ostream &os, const rcXMLOpenTag &e)
ostream & operator<< (ostream &os, const rcXMLCloseTag &e)
ostream & operator<< (ostream &os, const rcXMLEmptyTag &e)
ostream & operator<< (ostream &os, const rcXMLElement &e)
ostream & operator<< (ostream &os, const rcXMLElementTree &tree)
ostream & output (ostream &os, const rcXMLElementTree &tree, rcProgressIndicator *progress, double completedAlready)
Typedef Documentation
typedef pair<rcXMLAttributeType,std::string> rcAttribute
Definition at line 32 of file rc_xmlelem.h.
typedef vector<rcAttribute> rcAttributeList
Definition at line 33 of file rc_xmlelem.h.
typedef map<std::string,rcXMLAttributeType> rcXMLAttributeNameMap
Definition at line 28 of file rc_xmlelem.h.
typedef map<std::string,rcXMLElementType> rcXMLElementNameMap
Definition at line 27 of file rc_xmlelem.h.
typedef tree<rcXMLElement> rcXMLElementTree
Definition at line 36 of file rc_xmlelem.h.
typedef map<rcTimestamp,int32> rcXMLTimeMap
Definition at line 29 of file rc_xmlelem.h.
Function Documentation
ostream& operator<< (ostream & os, const rcXMLOpenTag & e)
Definition at line 69 of file rc_xml.cpp.
References rcXMLNameMapper::attributeName(), rcXMLOpenTag::attributes(), cCloseBracket, cDoubleQuote, cEquals, cOpenBracket, cSpace, rcXMLOpenTag::element(), rcXMLNameMapper::elementName(), eXMLElementComment, gXMLNameMapper, and sStartComment.
 {
     if ( e.element() == eXMLElementComment ) {
         // Special case for comment element
         os << sStartComment;
     } else {
         // Open bracket
         os << cOpenBracket;
         // Tag name
         os << gXMLNameMapper.elementName( e.element() );
         // Attributes
         const rcAttributeList& attributes = e.attributes();
         if ( !attributes.empty() ) {
             rcAttributeList::const_iterator a;
             for ( a = attributes.begin(); a < attributes.end(); a++ ) {
                 // Name
                 os << cSpace << gXMLNameMapper.attributeName( a->first );
                 // Value
                 os << cEquals << cDoubleQuote << a->second << cDoubleQuote;
             }
         }
         // End bracket
         os << cCloseBracket;
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLCloseTag & e)
Definition at line 100 of file rc_xml.cpp.
References cCloseBracket, cOpenBracketSlash, rcXMLCloseTag::element(), rcXMLNameMapper::elementName(), endl(), eXMLElementComment, eXMLElementTrackValue, gXMLNameMapper, and sEndComment.
 {
     const rcXMLElementType type = e.element();
     if ( type == eXMLElementComment ) {
         // Special case for comment element
         os << sEndComment << "\n";
     } else {
         //    </                   name                                  >
         os << cOpenBracketSlash << gXMLNameMapper.elementName( type ) << cCloseBracket;
         if ( type != eXMLElementTrackValue )
             os << endl;
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLEmptyTag & e)
Definition at line 119 of file rc_xml.cpp.
References cCloseBracket, cOpenBracket, cSlash, rcXMLEmptyTag::element(), rcXMLNameMapper::elementName(), eXMLElementComment, gXMLNameMapper, and sEndComment.
 {
     const rcXMLElementType type = e.element();
     if ( type == eXMLElementComment ) {
         // Special case for comment element
         os << sEndComment << "\n";
     } else {
         //    <               name                                  /         >
         os << cOpenBracket << gXMLNameMapper.elementName( type ) << cSlash << cCloseBracket << "\n";
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLElement & e)
Definition at line 136 of file rc_xml.cpp.
References rcXMLElement::attributes(), cAmpersand, cCloseBracket, rcXMLElement::content(), cOpenBracket, and rcXMLElement::type().
{
     // Open tag
     os << rcXMLOpenTag( e.type(), e.attributes() );
     // Content
     const std::string& content = e.content();
     // Character entity reference creation may be required
     for ( uint32 i = 0; i < content.size(); ++i ) {
         const char c = content[i];
         // We MUST use entity references for '<', '>' and '&'
         if ( c == cOpenBracket ) {
             os << "&lt;";
         } else if ( c == cCloseBracket ) {
             os << "&gt;";
         } else if ( c == cAmpersand ) {
             os << "&amp;";
         } else
             os << c;
     }
     // Add newline after an empty element
     if ( content.empty() )
         os << "\n";
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLElementTree & tree)
Definition at line 176 of file rc_xml.cpp.
References NULL, and output().
 {
     return output( os, tree, NULL, 0.0 );
 }
ostream& output (ostream & os, const rcXMLElementTree & tree, rcProgressIndicator * progress, double completedAlready)
Definition at line 182 of file rc_xml.cpp.
References rcProgressIndicator::progress(), and rcXMLElement::type().
Referenced by _sm2out(), lm_unit::dump_header(), rcNativeExporter::exportExperiment(), main(), operator<<(), ini_file::save_file(), library_manager::save_mappings(), lm_unit::write(), and write_context().
 {
     // Pre-order iterators
     rcXMLElementTree::iterator sibBegin = tree.begin();
     rcXMLElementTree::iterator sibEnd = tree.end();
     const uint32 totalElements = tree.size();
     uint32 processedElements = 0;
     // Stack for close tags
     stack<rcIndentedCloseTag> closeStack;
     while ( sibBegin != sibEnd ) {
         const rcXMLElement& e = *sibBegin;
         const rcXMLElementType type = e.type();
         const int32 depth = tree.depth( sibBegin );
         // Report progress
         if ( progress ) {
             if ( !(processedElements % 256) ) {
                 progress->progress( completedAlready + (100.0-completedAlready) * processedElements / totalElements );
             }
             ++processedElements;
         }
         // Pop close tags if necessary
         while ( !closeStack.empty() ) {
             const rcIndentedCloseTag& t = closeStack.top();
             if ( depth <= t.second ) {
                 os << t;
                 closeStack.pop();
             } else
                 break;
         }
         // Open tag with content
         os << e;
         // Optimization, produce close tag immediately if there are no children
         if ( ! tree.number_of_children( sibBegin ) ) {
             // Close tag
             os << rcXMLCloseTag( type );
         }
         else {
             closeStack.push( rcIndentedCloseTag( type, depth ) );
         }
         ++sibBegin;
     }
     while ( !closeStack.empty() ) {
         os << closeStack.top();
         closeStack.pop();
     }
     os << "\n";
     return os;
 }