Visible: include/analysis/rc_analysis.h File Reference
rc_analysis.h File Reference
#include <vector>
#include <deque>
#include <Carbon/Carbon.h>
#include <QuickTime/QuickTime.h>
#include <rc_types.h>
#include <rc_pair.h>
#include <rc_window.h>
#include <rc_vector2d.h>
#include <rc_correlationwindow.h>
#include <rc_peak.h>
#include <rc_polygon.h>
Classes
class rcSquareTable
class rcCorr
struct rsCorrParams
struct rsAnalysisVoxels
struct rs1DFourierResult
class rcPointScan
Macros
#define cmIntegerCorr 1000000
#define mQuantz 65000
Typedefs
typedef struct rsAnalysisVoxels rsAnalysisVoxels
typedef struct rs1DFourierResult rs1DFourierResult
typedef list< rcPeak< int16 > > rcFindList
Enumerations
enum RC_MatchMethod { RC_NormalizedCorr = 0, RC_IntFrequencyDist = 1 }
enum RC_PreProcessMethod { RC_PreNone = 0, RC_PreSharpen = 1, RC_PreSmooth = 2 }
enum RC_EnergyMethod { RC_SumSquare = 0, RC_SumPlogP = 1, RC_SumPlogPNorm = 2 }
enum RC_PixelInterp { RC_Whole = 0, RC_ByteWise = 1 }
enum RC_EnergyReport { RC_TimeDerivative = 0, RC_TimeIntegral = 1 }
enum RC_ColorMethod { RC_ColorReduceAll32to8 = 0, RC_ColorReduceGray32to8, RC_ColorUse32 }
enum rc1DFourierControl { rc1DFourierForceFFT = 1, rc1DFourierZeroFill = 2, rc1DFourierRaisedCosine = 4, rc1DFourierGenPhase = 8 }
Functions
ostream & operator<< (ostream &os, const rcCorr &corr)
void rfCorrelate (const rcWindow &sourceA, const rcWindow &sourceB, const rsCorrParams &params, rcCorr &res)
void rfCorrelate (const rcWindow &sourceA, const rcWindow &sourceB, rcCorr &res)
void rfCorrelate (const rcWindow &sourceA, const rcWindow &sourceB, const rcWindow &mask, const rsCorrParams &params, rcCorr &res, int32 maskN=-1)
void rfCorrelate (const uint8 *baseA, const uint8 *baseB, uint32 rupA, uint32 rupB, uint32 width, uint32 height, rcCorr &res)
template<class T >
void rfCorrelateWindow (rcCorrelationWindow< T > &sourceA, rcCorrelationWindow< T > &sourceB, const rsCorrParams &params, rcCorr &res)
bool rfOptoKineticEnergy (vector< rcWindow > &images, vector< double > &energy, const rsCorrParams &params, rcProgressIndicator *pIndicator=0)
Processing Function.
void rfOptoKineticVariance (vector< rcWindow > &sequence, rcWindow &varImage)
void rfOptoMoments (vector< rcWindow > &sequence, rcWindow &sumImage, rcWindow &sumSqImage)
void rfGetComponents (const rcWindow &src, uint32 &regions, rcWindow &lComponents)
void rfGetRects (const rcWindow &labels, uint32 nLabels, const rcIPair &minSize, bool combineRects, vector< rcIRect > &gRects, vector< uint32 > &gRectLabel)
void rfComponentPolygons (const rcWindow &, const int32, vector< rcPolygon > &, vector< rcIRect > &, bool doMerge=true)
void rfGrassFire (rcWindow &field, rcWindow &feature, rcWindow &distance)
void rfGrassFire (vector< rc2Dvector > &edges, rcWindow &featureImage, rcWindow &distanceImage)
void rfIntegrateEnergy (vector< double > &energy)
void rfGenLatticeDimensions (const rcRect &geom, const rcIPair &latticeOff, const rcIPair &tileDim, rcUIPair &scoresDim, rcUIPair &workSpaceDim)
void rfLatticeCorrelate (rcWindow &winI, rcWindow &winM, const rcIPair &latticeOff, const rcIPair &tileDim, vector< vector< double > > &scores, vector< vector< rcCorr > > *workSpaceP, const rsCorrParams &params)
void rf1Dfft (vector< float > &signal, vector< float > &imaginary, int32 dir)
void rf1Ddft (vector< float > &signal, vector< float > &imaginary, int32 dir)
void rf1DFourierAnalysis (const deque< double > &signal, rs1DFourierResult &rslt, uint32 ctrl)
void rf1DFourierAnalysisVoxels (const uint8 *sig, const uint32 sigSz, rsAnalysisVoxels &analysisInfo, rs1DFourierResult &rslt, const uint32 ctrl)
void rfImageFind (const rcWindow &moving, const rcWindow &fixed, rcFindList &locations, rcWindow &space)
template<class T >
void rfPrintCorrSpace (rcWindow &space, T precision)
void rfPrintFindList (const rcFindList &l, ostream &os)
void rfImageACF (const rcWindow &moving, rcIPair &range, rcWindow &space)
Macro Definition Documentation
#define cmIntegerCorr 1000000
Definition at line 42 of file rc_analysis.h.
#define mQuantz 65000
Definition at line 445 of file rc_analysis.h.
Referenced by _exhaustiveImageFind().
Typedef Documentation
typedef list<rcPeak<int16> > rcFindList
Definition at line 440 of file rc_analysis.h.
typedef struct rs1DFourierResult rs1DFourierResult
typedef struct rsAnalysisVoxels rsAnalysisVoxels
Enumeration Type Documentation
enum rc1DFourierControl
Enumerator
rc1DFourierForceFFT
rc1DFourierZeroFill
rc1DFourierRaisedCosine
rc1DFourierGenPhase
Definition at line 425 of file rc_analysis.h.
{
   rc1DFourierForceFFT = 1,
   rc1DFourierZeroFill = 2,
   rc1DFourierRaisedCosine = 4,
   rc1DFourierGenPhase = 8
 };
enum RC_ColorMethod
Enumerator
RC_ColorReduceAll32to8
RC_ColorReduceGray32to8
RC_ColorUse32
Definition at line 255 of file rc_analysis.h.
                     {
     RC_ColorReduceAll32to8 = 0, // Reduce all 32-bit images to 8-bit gray scale images
     RC_ColorReduceGray32to8,    // Reduce 32-bit gray scale images to 8-bit gray scale images, analyze all bytes of color images
     RC_ColorUse32               // Analyze all bytes in all 32-bit images
     // TODO: what to do with 8-bit color images?
 };
enum RC_EnergyMethod
Enumerator
RC_SumSquare
RC_SumPlogP
RC_SumPlogPNorm
Definition at line 239 of file rc_analysis.h.
                      {
     RC_SumSquare = 0,      // Square
     RC_SumPlogP = 1,       // Shannon's Entropy
     RC_SumPlogPNorm = 2    // Shannon's Entropy, fully normalized
 };
enum RC_EnergyReport
Enumerator
RC_TimeDerivative
RC_TimeIntegral
Definition at line 250 of file rc_analysis.h.
                      {
   RC_TimeDerivative = 0,  // Raw Energy is dE / dt
   RC_TimeIntegral = 1   // Intgral of E
 };
enum RC_MatchMethod
Enumerator
RC_NormalizedCorr
RC_IntFrequencyDist
Definition at line 228 of file rc_analysis.h.
                     {
     RC_NormalizedCorr = 0,           //One match position correlation
     RC_IntFrequencyDist = 1         // 3x3 match space, max - min
 };
enum RC_PixelInterp
Enumerator
RC_Whole
RC_ByteWise
Definition at line 245 of file rc_analysis.h.
                     {
     RC_Whole = 0,        // Use the whole 32 bit or 16. Width = number of pixels
     RC_ByteWise = 1      // Use Byte wise. Width = number of bytes
 };
enum RC_PreProcessMethod
Enumerator
RC_PreNone
RC_PreSharpen
RC_PreSmooth
Definition at line 233 of file rc_analysis.h.
{
     RC_PreNone = 0,           //One match position correlation
     RC_PreSharpen = 1,         // Highpass before matching
     RC_PreSmooth = 2          // Lowpass before matching
 };
Function Documentation
ostream& operator<< (ostream & os, const rcCorr & corr)
Definition at line 972 of file rc_pmcorr.cpp.
References endl(), rcCorr::n(), rcCorr::r(), rcCorr::Si(), rcCorr::Sii(), rcCorr::Sim(), rcCorr::singular(), rcCorr::Sm(), and rcCorr::Smm().
 {
   os << "R " << corr.r() << " N " <<  corr.n() << " Rp " <<  corr.singular();
   os << " Si " <<  corr.Si() << " Sii " <<  corr.Sii() << " Sm " <<  corr.Sm() << " Smm " <<  corr.Smm() << " Sim " <<  corr.Sim() << endl;
   return os;
 }
void rf1Ddft (vector< float > & signal, vector< float > & imaginary, int32 dir)
Definition at line 126 of file rc_frequency.cpp.
References cos(), rmAssert, and sin().
Referenced by rcOptoKineticImage::genDFT(), and rf1DFourierAnalysis().
 {
   uint32 m = signal.size();
   rmAssert(m == imaginary.size());
   float arg;
   float cosarg, sinarg;
   vector<float> sigSum(m), imagSum(m);
   vector<float>::iterator si = signal.begin();
   vector<float>::iterator ii = imaginary.begin();
   vector<float>::iterator ssi = sigSum.begin();
   vector<float>::iterator isi = imagSum.begin();
   for (uint32 i = 0; i < m; i++) {
     ssi[i] = 0;
     isi[i] = 0;
     arg = - dir * 2.0 * 3.141592654 * (float)i / (float)m;
     for (uint32 k = 0; k < m; k++) {
       cosarg = cos(k * arg);
       sinarg = sin(k * arg);
       ssi[i] += (si[k] * cosarg - ii[k] * sinarg);
       isi[i] += (si[k] * sinarg + ii[k] * cosarg);
     }
   }
   /* Copy the data back */
   if (dir == 1) {
     for (uint32 i = 0; i < m; i++) {
       si[i] = ssi[i] / (float)m;
       ii[i] = isi[i] / (float)m;
     }
   } else {
     for (uint32 i = 0; i < m; i++) {
       si[i] = ssi[i];
       ii[i] = isi[i];
     }
   }
 }
void rf1Dfft (vector< float > & signal, vector< float > & imaginary, int32 dir)
Definition at line 51 of file rc_frequency.cpp.
References rmAssert.
Referenced by rcOptoKineticImage::genDFT(), and rf1DFourierAnalysis().
 {
   int32 m, n,i,i1,j,k,i2,l,l1,l2;
   float c1,c2,tx,ty,t1,t2,u1,u2,z;
   n = signal.size();
   m = (int32) log2 ((double) signal.size());
   rmAssert (n == (1 << m));
   vector<float>::iterator x = signal.begin();
   vector<float>::iterator y = imaginary.begin();
   /* Do the bit reversal */
   i2 = n >> 1;
   j = 0;
   for (i=0;i<n-1;i++) {
     if (i < j) {
       tx = x[i];
       ty = y[i];
       x[i] = x[j];
       y[i] = y[j];
       x[j] = tx;
       y[j] = ty;
     }
     k = i2;
     while (k <= j) {
       j -= k;
       k >>= 1;
     }
     j += k;
   }
   /* Compute the FFT */
   c1 = -1.0;
   c2 = 0.0;
   l2 = 1;
   for (l=0;l<m;l++) {
     l1 = l2;
     l2 <<= 1;
     u1 = 1.0;
     u2 = 0.0;
     for (j=0;j<l1;j++) {
       for (i=j;i<n;i+=l2) {
     i1 = i + l1;
     t1 = u1 * x[i1] - u2 * y[i1];
     t2 = u1 * y[i1] + u2 * x[i1];
     x[i1] = x[i] - t1;
     y[i1] = y[i] - t2;
     x[i] += t1;
     y[i] += t2;
       }
       z =  u1 * c1 - u2 * c2;
       u2 = u1 * c2 + u2 * c1;
       u1 = z;
     }
     c2 = sqrt((1.0 - c1) / 2.0);
     if (dir == 1)
       c2 = -c2;
     c1 = sqrt((1.0 + c1) / 2.0);
   }
   /* Scaling for forward transform */
   if (dir == 1) {
     for (i=0;i<n;i++) {
       x[i] /= n;
       y[i] /= n;
     }
   }
 }
void rf1DFourierAnalysis (const deque< double > & signal, rs1DFourierResult & rslt, uint32 ctrl)
Definition at line 233 of file rc_frequency.cpp.
References rs1DFourierResult::amplitude, atan2(), cos(), rs1DFourierResult::imag, parabolicFit(), rs1DFourierResult::peakAmplitude, rs1DFourierResult::peakFrequency, rs1DFourierResult::peakPhase, rs1DFourierResult::phase, PRT_DEBUG1, PRT_DEBUG2, PRT_DEBUG3, rc1DFourierForceFFT, rc1DFourierRaisedCosine, rc1DFourierZeroFill, rs1DFourierResult::real, rf1Ddft(), rf1Dfft(), rk2PI, rkPI, rmAssert, and rs1DFourierResult::workingSz.
Referenced by rcVisualFunction::beatProcess(), calcMusclePeriod(), and rcOptoKineticImage::genFreqImg().
 {
   const uint32 sigSz = signal.size();
   if (PRT_DEBUG1) {
     fprintf(stderr, "Ctrl Flags: Force FFT %s Zero Fill %s "
         "Raised Cosine %s\nInput signal:\n",
         ((ctrl & rc1DFourierForceFFT) ? "TRUE" : "FALSE"),
         ((ctrl & rc1DFourierZeroFill) ? "TRUE" : "FALSE"),
         ((ctrl & rc1DFourierRaisedCosine) ? "TRUE" : "FALSE"));
     for (uint32 i = 0; i < sigSz; i++)
       fprintf(stderr, "%d: %0.25f\n", i, signal[i]);
   }
   if (sigSz == 0) {
     rslt.real.resize(0);
     rslt.imag.resize(0);
     rslt.phase.resize(0);
     rslt.amplitude.resize(0);
     rslt.peakFrequency = 0.0;
     rslt.peakPhase = 0.0;
     rslt.peakAmplitude = 0.0;
     rslt.workingSz = (int32)sigSz;
     return;
   }
   /* Step 1 - Calculate the working signal size.
    */
   uint32 workingSz = sigSz;
   uint32 index;
   for (index = 0; index < 31; index++)
     if ((uint32)(1 << index) >= sigSz)
       break;
   rmAssert(index != 31);
   if ((ctrl & rc1DFourierForceFFT) && (ctrl & rc1DFourierZeroFill)) {
     index++;
     rmAssert(index != 31);
     workingSz = (1 << index);
   }
   else if (ctrl & rc1DFourierForceFFT) {
     workingSz = (1 << index);
   }
   else if (ctrl & rc1DFourierZeroFill) {
     workingSz = workingSz * 2;
   }
   rslt.workingSz = (int32)workingSz;
   vector<double> workingSignal(workingSz);
   /* Step 2 -Figure out the signal's DC component.
    */
   double avg = 0.0;
   for (uint32 i = 0; i < sigSz; i++)
     avg += signal[i];
   avg = avg/sigSz;
   /* Step 3 - Create a modified version of the signal by: A)
    * subtracting out the DC component and (optionally) B) applying the
    * Hanning filter.
    */
   if ((ctrl & rc1DFourierRaisedCosine) && sigSz > 1) {
     const double invSz = 1.0/(sigSz-1);
     for (uint32 n = 0; n < sigSz; n++) {
       double wgt = (1.0 - cos(rk2PI*n*invSz))*0.5;
       workingSignal[n] = wgt*(signal[n] - avg);
     }
   }
   else {
     for (uint32 n = 0; n < sigSz; n++)
       workingSignal[n] = signal[n] - avg;
   }
   /* Step 4 - Do any required zero filling.
    */
   for (uint32 n = sigSz; n < workingSz; n++)
     workingSignal[n] = 0.0;
   if (rslt.real.size() != workingSz)
     rslt.real.resize(workingSz);
   if (rslt.imag.size() != workingSz)
     rslt.imag.resize(workingSz);
   for (uint32 ii = 0; ii < workingSz; ii++) {
     rslt.real[ii] = (float)workingSignal[ii];
     rslt.imag[ii] = 0.0;
   }
   if (PRT_DEBUG2) {
     fprintf(stderr, "\nWorking signal:\n");
     for (uint32 i = 0; i < workingSz; i++)
       fprintf(stderr, "%d: %0.25f\n", i, rslt.real[i]);
   }
   if (workingSz != (uint32)(1 << index)) // signal size is not a multiple of 2
     rf1Ddft(rslt.real, rslt.imag, 1);
   else
     rf1Dfft(rslt.real, rslt.imag, 1);
   uint32 rsltSz = (workingSz + 1)/2;
   if (rslt.phase.size() != rsltSz)
     rslt.phase.resize(rsltSz);
   if (rslt.amplitude.size() != rsltSz)
     rslt.amplitude.resize(rsltSz);
   rslt.amplitude[0] = sqrt(rslt.real[0]*rslt.real[0] + rslt.imag[0]*rslt.imag[0]);
   rslt.phase[0] = atan2(rslt.imag[0], rslt.real[0]);
   if (rslt.phase[0] < 0.0)
     rslt.phase[0] += rk2PI;
   if (rsltSz == 1) {
     rslt.peakFrequency = 0.0;
     rslt.peakPhase = 0.0;
     rslt.peakAmplitude = 0.0;
     return;
   }
   rslt.amplitude[1] = sqrt(rslt.real[1]*rslt.real[1] + rslt.imag[1]*rslt.imag[1]);
   rslt.phase[1] = atan2(rslt.imag[1], rslt.real[1]);
   if (rslt.phase[1] < 0.0)
     rslt.phase[1] += rk2PI;
   if (rsltSz == 2) {
     rslt.peakFrequency = 1;
     rslt.peakPhase = rslt.phase[1];
     rslt.peakAmplitude = rslt.amplitude[1];
     return;
   }
   uint32 maxFreq = 1;
   float maxAmplitude = rslt.amplitude[1];
   for (uint32 ii = 2; ii < rsltSz; ii++) {
     rslt.amplitude[ii] =
       sqrt(rslt.real[ii]*rslt.real[ii] + rslt.imag[ii]*rslt.imag[ii]);
     rslt.phase[ii] = atan2(rslt.imag[ii], rslt.real[ii]);
     if (rslt.phase[ii] < 0.0)
       rslt.phase[ii] += rk2PI;
     if (rslt.amplitude[ii] > maxAmplitude) {
       maxAmplitude = rslt.amplitude[ii];
       maxFreq = ii;
     }
   }
   if (PRT_DEBUG3) {
     const float rkDegree = 180/rkPI;
     fprintf(stderr, "\nResult signal (FREQ PHASE AMPLITUDE):\n");
     for (uint32 i = 0; i < rslt.phase.size(); i++)
       fprintf(stderr, " (%d  %f    %f)\n",
           i, rslt.phase[i]*rkDegree, rslt.amplitude[i]);
   }
   float frequencyDelta;
   if (maxFreq == (rsltSz-1))  { // Peak is pegged at end
     frequencyDelta = parabolicFit(rslt.amplitude[maxFreq-1],
                   rslt.amplitude[maxFreq],
                   (float)0.0,
                   &maxAmplitude);
     rmAssert(frequencyDelta <= 0.0);
   }
   else if (maxFreq == 1) { // Peak is pegged at start
     frequencyDelta = parabolicFit((float)0.0,
                   rslt.amplitude[1],
                   rslt.amplitude[2],
                   &maxAmplitude);
     rmAssert(frequencyDelta >= 0.0);
   }
   else { // Interpolate peak location
     frequencyDelta = parabolicFit(rslt.amplitude[maxFreq-1],
                   rslt.amplitude[maxFreq],
                   rslt.amplitude[maxFreq+1],
                   &maxAmplitude);
   }
   rslt.peakFrequency = maxFreq + frequencyDelta;
   rslt.peakAmplitude = maxAmplitude;
   if (frequencyDelta == 0.0) {
     rslt.peakPhase = rslt.phase[maxFreq];
     return;
   }
   float theta1, theta2;
   if (frequencyDelta > 0.0) {
     theta1 = rslt.phase[maxFreq];
     theta2 = rslt.phase[maxFreq + 1];
   }
   else {
     frequencyDelta += 1.0;
     theta1 = rslt.phase[maxFreq - 1];
     theta2 = rslt.phase[maxFreq];
   }
   float thetaDiff = theta2 - theta1;
   if (thetaDiff < 0)
     thetaDiff += rk2PI;
   rslt.peakPhase = theta1 + thetaDiff*frequencyDelta;
   if (rslt.peakPhase >= rk2PI)
     rslt.peakPhase -= rk2PI;
 }
void rf1DFourierAnalysisVoxels (const uint8 * sig, const uint32 sigSz, rsAnalysisVoxels & analysisInfo, rs1DFourierResult & rslt, const uint32 ctrl)
Definition at line 443 of file rc_frequency.cpp.
References rs1DFourierResult::amplitude, atan2(), cos(), FFTRealForward(), rs1DFourierResult::imag, parabolicFit(), rs1DFourierResult::peakAmplitude, rs1DFourierResult::peakFrequency, rs1DFourierResult::peakPhase, rs1DFourierResult::phase, PRT_DEBUG1, PRT_DEBUG2, PRT_DEBUG3, rc1DFourierForceFFT, rc1DFourierGenPhase, rc1DFourierRaisedCosine, rc1DFourierZeroFill, rs1DFourierResult::real, rk2PI, rkPI, rmAssert, rsAnalysisVoxels::weights, rsAnalysisVoxels::weightsSz, rs1DFourierResult::workingSz, rsAnalysisVoxels::workSig, rsAnalysisVoxels::workSigBase, and rsAnalysisVoxels::workSigSz.
Referenced by rcOptoKineticImage::genFreqImg().
 {
   rmAssert(voxel);
   if (PRT_DEBUG1) {
     fprintf(stderr, "Ctrl Flags: Force FFT %s Zero Fill %s "
         "Raised Cosine %s Generate Phase %s\nInput signal:\n",
         ((ctrl & rc1DFourierForceFFT) ? "TRUE" : "FALSE"),
         ((ctrl & rc1DFourierZeroFill) ? "TRUE" : "FALSE"),
         ((ctrl & rc1DFourierRaisedCosine) ? "TRUE" : "FALSE"),
         ((ctrl & rc1DFourierGenPhase) ? "TRUE" : "FALSE"));
     for (uint32 i = 0; i < voxelSz; i++)
       fprintf(stderr, "%d: %d\n", i, voxel[i]);
   }
   if (voxelSz == 0) {
     rslt.real.resize(0);
     rslt.imag.resize(0);
     rslt.phase.resize(0);
     rslt.amplitude.resize(0);
     rslt.peakFrequency = 0.0;
     rslt.peakPhase = 0.0;
     rslt.peakAmplitude = 0.0;
     rslt.workingSz = (int32)voxelSz;
     return;
   }
   /* Step 1 - Calculate the working signal size.
    */
   uint32 workingSz = voxelSz;
   uint32 index;
   for (index = 0; index < 31; index++)
     if ((uint32)(1 << index) >= voxelSz)
       break;
   rmAssert(index != 31);
   rmAssert(ctrl & rc1DFourierForceFFT);
   if (ctrl & rc1DFourierZeroFill) {
     index++;
     rmAssert(index != 31);
     workingSz = (1 << index);
   }
   else
     workingSz = (1 << index);
   rslt.workingSz = (int32)workingSz;
   if (analysisInfo.workSigSz < workingSz) {
     if (analysisInfo.workSigBase) {
       free(analysisInfo.workSigBase);
       analysisInfo.workSigBase = 0;
       analysisInfo.workSig = 0;
     }
     analysisInfo.workSigSz = workingSz;
   }
   if (!analysisInfo.workSigBase) {
     analysisInfo.workSigBase =
       (char*)malloc(analysisInfo.workSigSz*sizeof(float) + 16);
     rmAssert(analysisInfo.workSigBase);
     analysisInfo.workSig =
       (float*)(((int)analysisInfo.workSigBase+15) & 0xFFFFFFF0);
   }
   /* Step 2 -Figure out the voxel's DC component.
    */
   double avg = 0.0;
   for (uint32 i = 0; i < voxelSz; i++)
     avg += voxel[i];
   avg = avg/voxelSz;
   /* Step 3 - Create a modified version of the voxel by: A)
    * subtracting out the DC component and (optionally) B) applying the
    * Hanning filter.
    */
   if ((ctrl & rc1DFourierRaisedCosine) && voxelSz > 1) {
     if (analysisInfo.weightsSz != voxelSz) {
       if (analysisInfo.weights)
     free(analysisInfo.weights);
       analysisInfo.weights = (float*)malloc(voxelSz*sizeof(float));
       rmAssert(analysisInfo.weights);
       analysisInfo.weightsSz = voxelSz;
       const float invSz = 1.0/(voxelSz-1);
       for (uint32 n = 0; n < voxelSz; n++)
     analysisInfo.weights[n] = (1.0 - cos(rk2PI*n*invSz))*0.5;
     }
     else
       rmAssert(analysisInfo.weights);
     for (uint32 n = 0; n < voxelSz; n++)
       analysisInfo.workSig[n] = analysisInfo.weights[n]*(voxel[n] - avg);
   }
   else {
     for (uint32 n = 0; n < voxelSz; n++)
       analysisInfo.workSig[n] = voxel[n] - avg;
   }
   /* Step 4 - Do any required zero filling.
    */
   for (uint32 n = voxelSz; n < workingSz; n++)
     analysisInfo.workSig[n] = 0.0;
   if (PRT_DEBUG2) {
     fprintf(stderr, "\nWorking signal:\n");
     for (uint32 i = 0; i < workingSz; i++)
       fprintf(stderr, "%d: %0.25f\n", i, analysisInfo.workSig[i]);
   }
   rmAssert(analysisInfo.workSig);
   int32 retval = FFTRealForward(analysisInfo.workSig, workingSz);
   if (retval != 0)
     fprintf(stderr, "Retval %d != 0\n", retval);
   rmAssert(retval == 0);
   const uint32 rsltSz = workingSz/2;
   if (rslt.real.size() != rsltSz)
     rslt.real.resize(rsltSz);
   if (rslt.imag.size() != rsltSz)
     rslt.imag.resize(rsltSz);
   {
     uint32 ri = 0;
     for (uint32 wi = 0; wi < rsltSz; wi += 2, ri++) {
       rslt.real[ri] = analysisInfo.workSig[wi];
       rslt.imag[ri] = analysisInfo.workSig[wi+1];
     }
   }
   if ((ctrl & rc1DFourierGenPhase) && (rslt.phase.size() != rsltSz))
       rslt.phase.resize(rsltSz);
   if (rslt.amplitude.size() != rsltSz)
     rslt.amplitude.resize(rsltSz);
   rslt.amplitude[0] = sqrt(rslt.real[0]*rslt.real[0] + rslt.imag[0]*rslt.imag[0]);
   if (ctrl & rc1DFourierGenPhase) {
     rslt.phase[0] = atan2(rslt.imag[0], rslt.real[0]);
     if (rslt.phase[0] < 0.0)
       rslt.phase[0] += rk2PI;
   }
   if (rsltSz == 1) {
     rslt.peakFrequency = 0.0;
     rslt.peakPhase = 0.0;
     rslt.peakAmplitude = 0.0;
     return;
   }
   rslt.amplitude[1] = sqrt(rslt.real[1]*rslt.real[1] + rslt.imag[1]*rslt.imag[1]);
   if (ctrl & rc1DFourierGenPhase) {
     rslt.phase[1] = atan2(rslt.imag[1], rslt.real[1]);
     if (rslt.phase[1] < 0.0)
       rslt.phase[1] += rk2PI;
   }
   if (rsltSz == 2) {
     rslt.peakFrequency = 1;
     if (ctrl & rc1DFourierGenPhase) rslt.peakPhase = rslt.phase[1];
     rslt.peakAmplitude = rslt.amplitude[1];
     return;
   }
   uint32 maxFreq = 1;
   float maxAmplitude = rslt.amplitude[1];
   if (ctrl & rc1DFourierGenPhase) {
     for (uint32 ii = 2; ii < rsltSz; ii++) {
       rslt.amplitude[ii] =
     sqrt(rslt.real[ii]*rslt.real[ii] + rslt.imag[ii]*rslt.imag[ii]);
       rslt.phase[ii] = atan2(rslt.imag[ii], rslt.real[ii]);
       if (rslt.phase[ii] < 0.0)
     rslt.phase[ii] += rk2PI;
       if (rslt.amplitude[ii] > maxAmplitude) {
     maxAmplitude = rslt.amplitude[ii];
     maxFreq = ii;
       }
     }
   }
   else {
     for (uint32 ii = 2; ii < rsltSz; ii++) {
       rslt.amplitude[ii] =
     sqrt(rslt.real[ii]*rslt.real[ii] + rslt.imag[ii]*rslt.imag[ii]);
       if (rslt.amplitude[ii] > maxAmplitude) {
     maxAmplitude = rslt.amplitude[ii];
     maxFreq = ii;
       }
     }
   }
   if (PRT_DEBUG3) {
     const float rkDegree = 180/rkPI;
     fprintf(stderr, "\nResult signal (FREQ PHASE AMPLITUDE):\n");
     for (uint32 i = 0; i < rslt.phase.size(); i++)
       fprintf(stderr, " (%d  %f    %f)\n",
           i,
           ((ctrl & rc1DFourierGenPhase) ? rslt.phase[i]*rkDegree : 0.0),
           rslt.amplitude[i]);
   }
   float frequencyDelta;
   if (maxFreq == (rsltSz-1))  { // Peak is pegged at end
     frequencyDelta = parabolicFit(rslt.amplitude[maxFreq-1],
                   rslt.amplitude[maxFreq],
                   (float)0.0,
                   &maxAmplitude);
     rmAssert(frequencyDelta <= 0.0);
   }
   else if (maxFreq == 1) { // Peak is pegged at start
     frequencyDelta = parabolicFit((float)0.0,
                   rslt.amplitude[1],
                   rslt.amplitude[2],
                   &maxAmplitude);
     rmAssert(frequencyDelta >= 0.0);
   }
   else { // Interpolate peak location
     frequencyDelta = parabolicFit(rslt.amplitude[maxFreq-1],
                   rslt.amplitude[maxFreq],
                   rslt.amplitude[maxFreq+1],
                   &maxAmplitude);
   }
   rslt.peakFrequency = maxFreq + frequencyDelta;
   rslt.peakAmplitude = maxAmplitude;
   if ((ctrl & rc1DFourierGenPhase) == 0) {
     rslt.peakPhase = 0.0;
     return;
   }
   else if (frequencyDelta == 0.0) {
     rslt.peakPhase = rslt.phase[maxFreq];
     return;
   }
   float theta1, theta2;
   if (frequencyDelta > 0.0) {
     theta1 = rslt.phase[maxFreq];
     theta2 = rslt.phase[maxFreq + 1];
   }
   else {
     frequencyDelta += 1.0;
     theta1 = rslt.phase[maxFreq - 1];
     theta2 = rslt.phase[maxFreq];
   }
   float thetaDiff = theta2 - theta1;
   if (thetaDiff < 0)
     thetaDiff += rk2PI;
   rslt.peakPhase = theta1 + thetaDiff*frequencyDelta;
   if (rslt.peakPhase >= rk2PI)
     rslt.peakPhase -= rk2PI;
 }
void rfComponentPolygons (const rcWindow & , const int32 , vector< rcPolygon > & , vector< rcIRect > & , bool doMerge = true)
Definition at line 444 of file rc_connect.cpp.
References rcPolygon::area(), rcPolygon::convexIntersection(), rcPolygon::convexUnion(), rcRectangle< T >::height(), rcPolygon::orthogonalEnclosingRect(), rfGetComponents(), rfGetRects(), rmAssert, rcPolygon::translate(), rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcKinetoscope::connectedFunctions().
 {
   mergedCH.clear();
   mergedCHR.clear();
   uint32 blobCnt;
   rcWindow blobWin;
   rfGetComponents(segImg, blobCnt, blobWin);
   if (blobCnt == 0)
     return;
   vector<rcIRect> rects;
   vector<uint32> rectLabel;
   const rcIPair minPairSz(minDim, minDim);
   vector<rcPolygon> poly;
   // combineRects ?= false
   rfGetRects(blobWin, blobCnt, minPairSz, false, rects, rectLabel);
   // Get raw Polygons
   for (uint32 i = 0; i < rects.size(); i++)
     {
       const rcIRect r = rects[i];
       const rcWindow rw(blobWin, r.ul().x(), r.ul().y(), r.width(), r.height());
 #if 0
       rcRleWindow rle;
       rle.encode(rw, blobCnt, rectLabel[i]);
       rcPolygon p;
       rle.polygon(p);
       p.translate(rc2Dvector(r.ul().x(), r.ul().y()));
       poly.push_back(p);
 #endif
     }
   // Create ConvexHulls
   vector<rcPolygon> polyCH(poly.size());
   for (uint32 fi = 0; fi < poly.size(); fi++)
     poly[fi].convexHull(polyCH[fi]);
   rmAssert(poly.size() == polyCH.size());
   if (!doMerge)
     {
       mergedCH = polyCH;
       mergedCHR = rects;
       return;
     }
   // Merge (Initialy from MuscleSegmenter)
   // Cache area
   multimap<double, uint32> areaToIndex;
   for (uint32 si = 0; si < poly.size(); si++) {
     double area = poly[si].area();
     areaToIndex.insert(pair<double, uint32>(area,si));
   }
   vector<uint32> mergedToPoly(poly.size());
   /*
    * Iterative merging: if a more than X percent of a polygon's intersects with another, merge them
    */
   for (multimap<double, uint32>::reverse_iterator si = areaToIndex.rbegin();
        si != areaToIndex.rend(); si++)
     {
       rcPolygon& pCH = polyCH[si->second];
       rcIRect boxCH = pCH.orthogonalEnclosingRect();
       double sAreaCH = -1.0;
       uint32 mi;
       for (mi = 0; mi < mergedCH.size(); mi++) {
     if (mergedCHR[mi].overlaps(boxCH, true)) {
       if (sAreaCH < 0.0)
         sAreaCH = pCH.area()*0.5;
       uint32 mpi = mergedToPoly[mi];
       rcPolygon intPoly;
       polyCH[mpi].convexIntersection(pCH, intPoly);
       if (intPoly.area() > sAreaCH) {
         if (intPoly != pCH) {
           rcPolygon unionPoly;
           mergedCH[mi].convexUnion(pCH, unionPoly);
           mergedCH[mi] = unionPoly;
           mergedCHR[mi] = mergedCH[mi].orthogonalEnclosingRect();
         }
         break;
       }
     }
       }
       if (mi == mergedCH.size()) {
     mergedCH.push_back(pCH);
     mergedCHR.push_back(boxCH);
     mergedToPoly[mergedCH.size()-1] = si->second;
       }
     }
 }
void rfCorrelate (const rcWindow & sourceA, const rcWindow & sourceB, const rsCorrParams & params, rcCorr & res)
Definition at line 185 of file rc_pmcorr.cpp.
References rcWindow::depth(), rcWindow::height(), rfCorrelate(), rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
 {
     rmAssert (sourceA.depth() == sourceB.depth());
         rfCorrelate (sourceA.rowPointer(0),sourceB.rowPointer(0),
                                  sourceA.rowUpdate(), sourceB.rowUpdate(),
                                  sourceA.width() * sourceA.depth(),
                                  sourceA.height(),
                                  res);
 }
void rfCorrelate (const rcWindow & sourceA, const rcWindow & sourceB, rcCorr & res)
Definition at line 195 of file rc_pmcorr.cpp.
References rfCorrelate(), and sDefaultCorrParams.
 {
   rfCorrelate(sourceA, sourceB, sDefaultCorrParams, res);
 }
void rfCorrelate (const rcWindow & sourceA, const rcWindow & sourceB, const rcWindow & mask, const rsCorrParams & params, rcCorr & res, int32 maskN = -1)
Definition at line 147 of file rc_pmcorr.cpp.
References rcCorr::compute(), rcWindow::depth(), rcWindow::getPixel(), rcWindow::height(), rcCorr::n(), rcPixel16, rcPixel32, rcPixel8, rfAndImage(), rfCorrelate(), rmAssert, and rcWindow::width().
 {
   rcWindow iMasked(img.width(), img.height(), img.depth());
   rcWindow mMasked(img.width(), img.height(), img.depth());
   rfAndImage(img, mask, iMasked);
   rfAndImage(mdl, mask, mMasked);
   rfCorrelate(iMasked, mMasked, params, res);
   if (maskN < 0) {
     uint32 allOnes = 0xFF;
     if (img.depth() == rcPixel16)
       allOnes = 0xFFFF;
     else if (img.depth() == rcPixel32)
       allOnes = 0xFFFFFFFF;
     else
       rmAssert(img.depth() == rcPixel8);
     maskN = 0;
     for (int32 y = 0; y < mask.height(); y++)
       for (int32 x = 0; x < mask.width(); x++) {
                 uint32 val = mask.getPixel(x, y);
                 if (val == allOnes)
                     maskN++;
                 else
                     rmAssert(val == 0);
       }
   }
   res.n(maskN);
   res.compute();
 }
void rfCorrelate (const uint8 * baseA, const uint8 * baseB, uint32 rupA, uint32 rupB, uint32 width, uint32 height, rcCorr & res)
Definition at line 122 of file rc_pmcorr.cpp.
References rcBasicCorrRowFunc< T >::areaFunc(), rcBasicCorrRowFunc< T >::epilog(), rcBasicCorrRowFunc< T >::prolog(), and rfHasSIMD().
Referenced by _exhaustiveImageFind(), calcMusclePeriod(), rcSimilarator::correlate(), rcAutoCorrelation::genPoint(), rcMuscleTracker::genSpace(), rcPointCorrelation::genSpace(), rcSimilarator::relativeCorrelate(), rfCorrelate(), and rfOptoKineticEnergy().
 {
 #ifdef __ppc__
     if (rfHasSIMD ())
     {
         // Use AltiVec for processing
         altiVecCorrelate (baseA, baseB, rupA, rupB, width, height, res);
     }
     else
 #endif
     {
         rcBasicCorrRowFunc<uint8> bc (baseA, baseB, rupA, rupB, width, height);
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     }
 }
template<class T > void rfCorrelateWindow (rcCorrelationWindow< T > & sourceA, rcCorrelationWindow< T > & sourceB, const rsCorrParams & params, rcCorr & res)
Definition at line 240 of file rc_pmcorr.cpp.
References rcCorrelationWindow< T >::depth(), rcCorrelationWindow< T >::height(), rcBasicCorrRowFunc< T >::prolog(), rmAssert, rcCorrelationWindow< T >::rowPointer(), rcCorrelationWindow< T >::rowUpdate(), rcCorr::Si(), rcCorr::Sii(), rcCorr::Sm(), rcCorr::Smm(), rcCorrelationWindow< T >::sum(), rcCorrelationWindow< T >::sumSquares(), rcCorrelationWindow< T >::sumValid(), and rcCorrelationWindow< T >::width().
 {
     rmAssert (sourceA.depth() == sourceB.depth());
         // Bytewise correlation
         // Note: cannot construct rcCorrelationWindow because of window depth difference
         rcBasicCorrRowFunc<uint8> bc( sourceA.rowPointer(0), sourceB.rowPointer(0),
                                                                      sourceA.rowUpdate(), sourceB.rowUpdate(),
                                                                      sourceA.width() * sourceA.depth(),
                                                                      sourceA.height() );
         bc.prolog ();
         bc.areaFunc();
         bc.epilog (res);
     // Cache sums
     if ( !sourceA.sumValid() ) {
         sourceA.sum( res.Si() );
         sourceA.sumSquares( res.Sii() );
     }
     if ( !sourceB.sumValid() ) {
         sourceB.sum( res.Sm() );
         sourceB.sumSquares( res.Smm() );
     }
 }
void rfGenLatticeDimensions (const rcRect & geom, const rcIPair & latticeOff, const rcIPair & tileDim, rcUIPair & scoresDim, rcUIPair & workSpaceDim)
void rfGetComponents (const rcWindow & src, uint32 & regions, rcWindow & lComponents)
Definition at line 68 of file rc_connect.cpp.
References AddToAssociative(), rcWindow::depth(), rcWindow::height(), rcPixel16, rcPixel32, rcPixel8, rmAssert, rcWindow::rowPointer(), rcWindow::rowUpdate(), rcWindow::setAllPixels(), and rcWindow::width().
Referenced by rcMuscleSegmenter::genPolygons(), and rfComponentPolygons().
 {
    // Create a temporary copy of image to store intermediate information
    // during component labeling.  The original image is embedded in an
    // image with two more rows and two more columns so that the image
    // boundary pixels are properly handled.
    // To prevent duplicate clears, when src is 32 bit we are assuming that it is 2 pixels
    // larger already. This is a hack to be cleanly handled
   rcWindow buffer, label;
   int32 iX, iY;
   if (src.depth() == rcPixel8)
     {
       buffer = rcWindow (src.width()+2,src.height()+2, rcPixel32);  // initially zero
       buffer.setAllPixels(uint32(0));
       label = rcWindow (buffer, 1, 1, src.width(), src.height ());
       for (iY = 0; iY < src.height(); ++iY)
     {
       const uint8 *row = src.rowPointer (iY);
       uint32 *brow = (uint32 *) label.rowPointer (iY);
       for (iX = 0; iX < src.width(); ++iX, ++row,   ++brow)
         {
           if ( *row )
         *brow = 1;
         }
     }
     }
   else if (src.depth() == rcPixel16)
     {
       buffer = rcWindow (src.width()+2,src.height()+2, rcPixel32);  // initially zero
       buffer.setAllPixels(uint32(0));
       label = rcWindow (buffer, 1, 1, src.width(), src.height ());
       for (iY = 0; iY < src.height(); ++iY)
     {
       const uint16 *row = (uint16 *) src.rowPointer (iY);
       uint32 *brow = (uint32 *) label.rowPointer (iY);
       for (iX = 0; iX < src.width(); ++iX)
         {
           // Buffer was initialized with 0's so only set non-zero pixels
           if ( *row )
               *brow = 1; // Change to a map look up table with no conditional
           ++row;
           ++brow;
         }
     }
     }
   else if (src.depth() == rcPixel32)
     {
       buffer = src;
       label = rcWindow (buffer, 1, 1, src.width()-2, src.height ()-2);
     }
   else
     rmAssert (0);
    // label connected components in 1D array
    uint32 i, iComponent = 0;
    for (iY = 1; iY < buffer.height() - 1; ++iY)
    {
       // Next row, second column
       uint32 *brow = (uint32 *) buffer.rowPointer (iY);
       ++brow;
       // Label runs with an incrementing component number
       for (iX = 0; iX < buffer.width() - 1; ++iX)
       {
          if (brow[iX])
          {
             ++iComponent;
             while ((iX < (buffer.width() - 1)) && brow[iX])
             {
                brow[iX] = iComponent;
                ++iX;
             }
          }
       }
    }
    // If there are no non zero pels
    // Labled component image is not assigned a real one
    if ( iComponent == 0 )
    {
       regions = 0;
       return;
    }
    // associative memory for merging
    vector<uint32> amm (iComponent+1);
    for (i = 0; i < iComponent + 1; ++i)
       amm[i] = i;
    // Merge equivalent components.  Pixel (x,y) has previous neighbors
    // (x-1,y-1), (x,y-1), (x+1,y-1), and (x-1,y) [4 of 8 pixels visited
    // before (x,y) is visited, get component labels from them].
    const uint32 rup = buffer.rowUpdate () / rcPixel32;      // rup in ints;
    for (iY = 1; iY < buffer.height()-1; ++iY)
    {
       uint32 *brow = (uint32 *) buffer.rowPointer (iY);
       ++brow;
       for (iX = 1; iX < buffer.width()-1; ++iX)
       {
          const uint32 iValue = *brow++; // at +1 after this
          if ( iValue > 0 )
          {
             AddToAssociative(iValue, brow [-rup - 2], amm); // brow[-rup - 2]
             AddToAssociative(iValue, brow [-rup - 1], amm); // brow [-rup - 1]
             AddToAssociative(iValue, brow [-rup], amm); // brow [-rup]
             AddToAssociative(iValue, brow [rup - 2],amm); // brow [rup - 2]
          }
       }
    }
    // replace each cycle of equivalent labels by a single label
    regions = 0;
    for (i = 1; i <= iComponent; ++i)
    {
       if ( i <= amm[i] )
       {
          regions++;
          uint32 iCurrent = i;
          while ( amm[iCurrent] != i )
          {
             const uint32 iNext = amm[iCurrent];
             amm[iCurrent] = regions;
             iCurrent = iNext;
          }
          amm[iCurrent] = regions;
       }
    }
    // pack a relabeled image in smaller size output
    // create a rcWindow at 1,1 and label according to the associative memory TBD
    for (iY = 0; iY < label.height(); ++iY)
    {
       uint32* brow = (uint32 *) label.rowPointer (iY);
       for (iX = 0; iX < label.width(); ++iX, ++brow)
       {
          *brow = amm[*brow]; // *brow++ here appears to be a compiler bug
       }
    }
    // Out the label image
    lComponents = label;
 }
void rfGetRects (const rcWindow & labels, uint32 nLabels, const rcIPair & minSize, bool combineRects, vector< rcIRect > & gRects, vector< uint32 > & gRectLabel)
Definition at line 259 of file rc_connect.cpp.
References rcRectangle< T >::area(), rcRectangle< T >::contains(), rcWindow::depth(), rcWindow::height(), rcRectangle< T >::height(), rcWindow::isBound(), rcRectangle< T >::overlaps(), rcPixel32, rmAssert, rcWindow::rowPointer(), rcWindow::size(), rcWindow::width(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcMuscleSegmenter::genPolygons(), and rfComponentPolygons().
 {
     // Check that label is the right depth and that we have labels
     rmAssert (label.depth() == rcPixel32);
     rmAssert (label.isBound());
     rmAssert (nLabels);
     // Regardless of label is a window or not, lower right should be initialized to zero
     const int height = static_cast<int>( label.height() );
     const int width = static_cast<int>( label.width() );
     rcIPair zeropair (0,0);
     vector<rcIPair> lrp (nLabels+1,zeropair);
     vector<rcIPair> ulp (nLabels+1,label.size());
     /*
      * The following computes the min containing rectangle for
      * the connected region. That is for the integer top left position
      * of the most top left (lowest x and lowest y) pixel position in the runs and
      * the most bottom right (highest x and highest y) pixel position in
      * the runs.
      * The integer bounding box is at upper left x and y and has width and height
      * of lower - upper + 1.
      */
     for (int32 j = 0; j < height; ++j)
     {
         uint32* pSrc = (uint32*) label.rowPointer(j);
         for (int32 i=0; i < width; ++i, ++pSrc)
         {
             const uint32 l = *pSrc;
             // Note: first rect is at index 1 to avoid computing l-1 inside the inner loop
             if (l)
             {
                 // Update min enclosing rectangle
                 if (i < ulp[l].x())
                     ulp[l].x() = i;
                 if (j < ulp[l].y())
                     ulp[l].y() = j;
                 if (i > lrp[l].x())
                     lrp[l].x() = i;
                 if (j > lrp[l].y())
                     lrp[l].y() = j;
             }
         }
     }
     // Enclosed rects will be removed
     if ( !gRects.empty() )
       gRects.clear();
     gRectLabel.reserve( nLabels );
     if ( !gRectLabel.empty() )
       gRectLabel.clear();
     gRectLabel.reserve( nLabels );
     // Construct rects
     for (uint32 l = 1; l <= nLabels; ++l )
       {
     /* The integer bounding box is at upper left x and y and has width and height
      * of lower - upper + 1.
      * We use the rectangle ctor for passing the position and width and height
      */
     rcIRect r(ulp[l].x(), ulp[l].y(), lrp[l].x() - ulp[l].x() + 1, lrp[l].y() - ulp[l].y() + 1);
     //  cerr << "r[" << l << "]: " << r.ul() << "," << r.size() << endl;
     // Add only rects which meet minimum size requirement
     if ( r.width() >= minSize.x() && r.height() >= minSize.y() ) {
       gRects.push_back( r );
       gRectLabel.push_back( l );
     }
       }
     if ( combineRects ) {
       vector<bool> erasedRects( gRects.size(), false );
         uint32 erasedCount = 0;
         // Remove regions enclosed by another region
     // Erase rect of true == remove
         for ( uint32 i = 0; i <  gRects.size(); ++i ) {
       const rcIRect r = gRects[i];
       if (erasedRects[i]) continue;
       rmAssert (erasedRects[i] == false);
       for ( uint32 j = i+1; j < gRects.size(); ++j ) {
         if ( !erasedRects[j] ) {
           const rcIRect r2 =  gRects[j];
           if ( r.contains( r2 ) ) {
         ++erasedCount;
         erasedRects[j] = true;
           } else if ( r2.contains( r ) ) {
         ++erasedCount;
         erasedRects[i] = true;
           }
         }
       }
         }
         // Remove smaller regions intersecting with larger ones
         for ( uint32 i = 0; i <  gRects.size(); ++i ) {
       if (erasedRects[i]) continue;
       rmAssert (erasedRects[i] == false);
       const rcIRect r = gRects[i];
       for ( uint32 j = i+1; j < gRects.size(); ++j ) {
         if ( !erasedRects[j] ) {
           const rcIRect r2 =  gRects[j];
           if ( r.overlaps ( r2 )  &&  r.area() >= r2.area() ) {
         ++erasedCount;
         erasedRects[j] = true;
           } else if (r.overlaps ( r2 )  && r.area() >= r2.area()) {
         ++erasedCount;
         erasedRects[i] = true;
           }
         }
       }
         }
         if ( erasedCount ) {
       if ( erasedCount < gRects.size() ) {
         vector<rcIRect> combinedRects;
         vector<uint32> combinedRectLabel;
         combinedRects.reserve( gRects.size() - erasedCount );
         combinedRectLabel.reserve( gRects.size() - erasedCount );
         for ( uint32 i = 0; i <  gRects.size(); ++i ) {
           if ( !erasedRects[i] ) {
         combinedRects.push_back( gRects[i] );
         combinedRectLabel.push_back( gRectLabel[i] );
           }
         }
         gRects.clear();
         gRectLabel.clear();
         if (combinedRects.size() && combinedRectLabel.size())
           {
         gRects = combinedRects;
         gRectLabel = combinedRectLabel;
           }
       }
     }
     }
 }
void rfGrassFire (rcWindow & field, rcWindow & feature, rcWindow & distance)
void rfGrassFire (vector< rc2Dvector > & edges, rcWindow & featureImage, rcWindow & distanceImage)
void rfImageACF (const rcWindow & moving, rcIPair & range, rcWindow & space)
void rfImageFind (const rcWindow & moving, const rcWindow & fixed, rcFindList & locations, rcWindow & space)
Definition at line 107 of file rc_lattice.cpp.
References _exhaustiveImageFind().
Referenced by rcVisualFunction::dividingProcess(), rcVisualFunction::match(), and rcEngineImpl::modelTracker().
 {
     rcWindow noMask;
     _exhaustiveImageFind (moving, fixed, noMask, locations, space);
 }
void rfIntegrateEnergy (vector< double > & energy)
Definition at line 235 of file rc_optokinetic.cpp.
Referenced by rfOptoKineticEnergy().
 {
   assert (energy.size());
   double sum (0.0);
   for (unsigned int i = 0; i < energy.size(); i++)
     {
       sum += energy[i];
       energy[i] = sum;
     }
 }
void rfLatticeCorrelate (rcWindow & winI, rcWindow & winM, const rcIPair & latticeOff, const rcIPair & tileDim, vector< vector< double > > & scores, vector< vector< rcCorr > > * workSpaceP, const rsCorrParams & params)
bool rfOptoKineticEnergy (vector< rcWindow > & images, vector< double > & energy, const rsCorrParams & params, rcProgressIndicator * pIndicator = 0)
Processing Function.
Definition at line 54 of file rc_optokinetic.cpp.
References rsCorrParams::em, rsCorrParams::match, percent(), rsCorrParams::pp, rcProgressIndicator::progress(), rcCorr::r(), rsCorrParams::rc, rcPixel8, rfCorrelate(), rfIntegrateEnergy(), rfRcWindow32to8(), rmAssert, and rsCorrParams::rp.
 {
    assert (images.size () > 1);
    assert (images.size () == energy.size ());
    vector<rcWindow> locals(images.size());
    vector<double> scoreTotals (images.size());
    vector<vector<double> > scores(images.size());
    const double tinyNum = 1e-10; // When using rcSumPlogPNorm, added to every score to guarantee non-zero value
    bool finished = true;
    // O (n^2/2 - n)
    // Pre-initialize with unity for identity cross correlate
    for (unsigned int i = 0; i < images.size(); i++) energy[i] = 1.0;
    if (params.pp != rcPreNone)
    {
       rmAssert (1);  // Not implemented
    }
    else if (images[0].depth() > rcPixel8 ) {
        switch ( params.rc ) {
            case rcColorReduceAll32to8:
                // Reduce all color and gray 24/32-bit images to 8-bit gray images
                rfRcWindow32to8(images, locals);
                break;
            case rcColorReduceGray32to8:
                // Reduce depth of all gray 24/32-bit images to 8-bit gray images
                if ( images[0].isGray() )
                    rfRcWindow32to8(images, locals);
                else
          locals = images; // Analyze all bytes of color originals
                break;
            case rcColorUse32:
                // Analyze all bytes of all originals
            locals = images;
                break;
            default:
                rmAssert( 1 );
                break;
        }
    }
    else
       locals = images;
    if (params.em == rcSumPlogPNorm)
    {
      for (unsigned int i = 0; i < images.size(); i++)
      {
        scores[i].resize(scores.size());
        scores[i][i] = scoreTotals[i] = 1 + tinyNum;
        energy[i] = 0;
      }
    }
    else if (params.em == rcSumPlogP)
      // Pre-initialize with unity for identity cross correlate
      for (unsigned int i = 0; i < images.size(); i++) energy[i] = 0.0; // Because log2(1) == 0
    else
      // Pre-initialize with unity for identity cross correlate
      for (unsigned int i = 0; i < images.size(); i++) energy[i] = 1.0;
    // Progress update variables
    uint32 lastProgress = 0;
    const uint32 imageSize = images[0].width() * images[0].height();
    // Progress update after this many pixels have been processed
    const uint32 updateLimit = 2000000;
    uint32 processedPixels = 0;
    for (unsigned int i = 0; i < images.size (); i++)
    {
        for (unsigned int j = i + 1; j < images.size(); j++)
        {
            rcCorr res;
            switch (params.match)
            {
                default:
                case rcNormalizedCorr:
                    rfCorrelate (locals[i], locals[j], params, res);
                    break;
                case rcIntFrequencyDist:
                {
                    rcWindow iw (locals[j], 1, 1, locals[j].width() - 2, locals[j].height() - 2);
                    double minn (1.0), maxx (0.0);
                    for (uint32 p = 0; p < 3; p++)
                        for (uint32 q = 0; q < 3; q++)
{
                            rcWindow jw (locals[i], p, q, locals[i].width() - 2, locals[i].height() - 2);
                            rfCorrelate (iw, jw, params, res);
                            if (res.r() <= minn) minn = res.r();
                            if (res.r() >= maxx) maxx = res.r();
                        }
                    res.r(maxx - minn);
                    assert (res.r() >= 0 && res.r() <= 1.0);
                }
                break;
            }
            switch (params.em)
            {
                case rcSumSquare:
                    energy[i] += res.r();
                    energy[j] += res.r();
                    break;
                case rcSumPlogP:
          {
                        double rr = res.r() + 0.0000000000001;
                        energy[i] += -1.0 * rr * log2 (rr);
                        energy[j] += -1.0 * rr * log2 (rr);
          }
          break;
                default:
                case rcSumPlogPNorm:
                {
                    double rr = res.r() + tinyNum;
                    scoreTotals[i] += rr;
                    scoreTotals[j] += rr;
                    scores[i][j] = rr;
                    scores[j][i] = rr;
                }
                break;
            }
            if ( pIndicator ) {
                processedPixels += imageSize;
                // Update frequency depends on total number of processed pixels
                if ( processedPixels > updateLimit ) {
                    processedPixels -= updateLimit;
                    uint32 percent = uint32(double(i+1)/images.size() * 100.0);
                    // However, minimum progress increment is 1%
                    if ( percent > lastProgress ) {
                        bool abort = pIndicator->progress( percent );
                        lastProgress = percent;
                        if ( abort ) {
                            finished = false;
                            goto abort;
                        }
                    }
                }
            }
        }
    }
    if (params.em == rcSumPlogPNorm)
    {
        for (unsigned int i = 0; i < images.size(); i++)
        {
            for (unsigned int j = i; j < images.size(); j++)
            {
                double rr = scores[i][j]/scoreTotals[i]; // Normalize for total energy in samples
                energy[i] += -1.0 * rr * log2 (rr);
                if (i != j)
                {
                    rr = scores[i][j]/scoreTotals[j]; // Normalize for total energy in samples
                    energy[j] += -1.0 * rr * log2 (rr);
                }
            } // End of : for (unsigned int j = i; j < images.size(); j++)
            energy[i] = energy[i]/log2(images.size()); // Normalize for number of samples
        } // End of: for (unsigned int i = 0; i < images.size(); i++)
    }
    else
    {
        double n (images.size());
        for (unsigned int i = 0; i < energy.size(); i++) energy[i] = fabs(energy[i]) / n;
    }
    // Reporting: Derivative (raw) or cumulative
    if (params.rp == rcTimeIntegral)
    {
        rfIntegrateEnergy (energy);
    }
   abort:
    // Abort analysis, results are not guaranteed to be in a consistent state
    return finished;
 }
void rfOptoKineticVariance (vector< rcWindow > & sequence, rcWindow & varImage)
Definition at line 251 of file rc_optokinetic.cpp.
References rcPixel16, rcPixel32, rmAssert, rcWindow::rowPointer(), rcWindow::setAllPixels(), and squareTable.
 {
    rmAssert (sequence.size());
    rmAssert (sequence.size() <= 257); // guarantee no numerical overflow
    uint32 n (sequence.size());
    // Check the sizes
    uint32 width = sequence[0].width();
    uint32 height = sequence[0].height();
    rcWindow sum (width, height, rcPixel16);
    rcWindow sumsq (width, height, rcPixel32);
    sum.setAllPixels (0);
    sumsq.setAllPixels (0);
    // Produce Sum and Sum sq
    for (vector<rcWindow>::iterator img = sequence.begin(); img != sequence.end(); img++)
    {
       for (uint32 j = 0; j < height; j++)
       {
          uint8 *pelRow = img->rowPointer (j);
          uint16 *sumRow = (uint16 *) sum.rowPointer (j);
          uint32 *sumSqRow = (uint32 *) sumsq.rowPointer (j);
          for (uint32 i = 0; i < width; i++, pelRow++, sumRow++, sumSqRow++)
          {
             *sumRow += *pelRow;
             *sumSqRow += squareTable [*pelRow];
          }
       }
    }
    // Now produce variance using:  variance = n * sumSq - sum * sum
    for (uint32 j = 0; j < height; j++)
    {
       uint16 *sumRow = (uint16 *) sum.rowPointer (j);
       uint32 *sumSqRow = (uint32 *) sumsq.rowPointer (j);
       for (uint32 i = 0; i < width; i++, sumRow++, sumSqRow++)
       {
          uint32 var = *sumSqRow * n;
          uint32 tmp = *sumRow;
          var = var - tmp * tmp;
          *sumSqRow = var;
       }
    }
    varImage = sumsq;
 }
void rfOptoMoments (vector< rcWindow > & sequence, rcWindow & sumImage, rcWindow & sumSqImage)
template<class T > void rfPrintCorrSpace (rcWindow & space, T precision)
Definition at line 508 of file rc_analysis.h.
References endl(), rcWindow::height(), rcWindow::pelPointer(), and rcWindow::width().
 {
   int32 i;
   cerr << ">>>>>>>>>>>>>>>>>>>>>>>>>" << endl;
   for (int32 j = 0; j < space.height(); j++)
     {
       for (i = 0; i < space.width() - 1; i++)
     cerr << setw(3) << (*((T *) (space.pelPointer(i, j)))) * precision  << "-";
       cerr << setw(3) << (*((T *) (space.pelPointer(i, j)))) * precision  << endl;
     }
   cerr << "<<<<<<<<<<<<<<<<<<<<<<<<<" << endl;
 }
void rfPrintFindList (const rcFindList & l, ostream & os)