Visible: include/analysis/rc_1dcorr.h File Reference
rc_1dcorr.h File Reference
#include <rc_window.h>
#include <rc_vector2d.h>
#include <rc_pair.h>
#include <rc_analysis.h>
#include <rc_fit.h>
#include <rc_stats.h>
Functions
template<class Iterator >
double rf1DNormalizedCorr (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
template<class Iterator >
double rf1DCrossCorr (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
template<class Iterator >
void rf1DAutoCorr (Iterator Ib, Iterator Ie, Iterator acb, bool op=true)
template<class Iterator >
void rf1DAutoCorr (Iterator Ib, Iterator Ie, deque< double > &acb, bool op=true)
template<class Iterator >
double rf1DRegister (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me, uint32 slide, double &pose)
template<class Iterator >
double rf1DRegister (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me, uint32 slide, double &pose, double &acc)
template<class Iterator >
double rf1DRegister (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me, uint32 slideLeft, uint32 slideRight, double &pose)
template<class Iterator >
double rf1dSignalIntersection (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
template<class Iterator >
double rf1dSignalNormEuclideanIntersection (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
Function Documentation
template<class Iterator > void rf1DAutoCorr (Iterator Ib, Iterator Ie, Iterator acb, bool op = true)
Definition at line 135 of file rc_1dcorr.h.
References rf1DCrossCorr(), rf1DNormalizedCorr(), and value_type().
Referenced by rcVisualFunction::beatProcess(), and rcEngineImpl::entropyTrackerWindow().
 {
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   int32 n = distance (Ib, Ie);
   vector<value_type> ring (n + n);
   Iterator ip = Ib;
   int32 i;
   for (i = 0; i < n; i++) ring[i] = *ip++;
   ip = Ib;
   for (; i < (int32) ring.size(); i++) ring[i] = *ip++;
   ip = ring.begin();
   Iterator cp = acb;
   if (op)
     {
       for (int32 i = 0; i < n; i++, ip++)
     *cp++ = rf1DNormalizedCorr (Ib, Ie, ip, ip + n);
     }
   else
     {
       for (int32 i = 0; i < n; i++, ip++)
     *cp++ = rf1DCrossCorr (Ib, Ie, ip, ip + n);
     }
 }
template<class Iterator > void rf1DAutoCorr (Iterator Ib, Iterator Ie, deque< double > & acb, bool op = true)
Definition at line 164 of file rc_1dcorr.h.
References rf1DCrossCorr(), rf1DNormalizedCorr(), and value_type().
 {
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   int32 n = distance (Ib, Ie);
   vector<value_type> ring (n + n);
   Iterator ip = Ib;
   uint32 i;
   for (i = 0; i < (uint32) n; i++) ring[i] = *ip++;
   ip = Ib;
   for (; i < ring.size(); i++) ring[i] = *ip++;
   ip = ring.begin();
   acb.resize(n);
   deque<double>::iterator cp = acb.begin();
   if (op)
     {
       for (uint32 i = 0; i < (uint32) n; i++, ip++)
     *cp++ = rf1DNormalizedCorr (Ib, Ie, ip, ip + n);
     }
   else
     {
       for (uint32 i = 0; i < (uint32) n; i++, ip++)
     *cp++ = rf1DCrossCorr (Ib, Ie, ip, ip + n);
     }
 }
template<class Iterator > double rf1DCrossCorr (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
Definition at line 104 of file rc_1dcorr.h.
References rmAssert, and value_type().
Referenced by rf1DAutoCorr().
 {
   double sim (0.0);
   int32 n;
   n = Ie - Ib;
   rmAssert (n);
   rmAssert ((Me - Mb) == n);
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   Iterator ip = Ib;
   Iterator mp = Mb;
   while (ip < Ie)
     {
       value_type iv (*ip);
       value_type mv (*mp);
       sim += (iv * mv);
       ip++;
       mp++;
     }
   return sim;
 }
template<class Iterator > double rf1DNormalizedCorr (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
Definition at line 60 of file rc_1dcorr.h.
References rmAssert, and value_type().
Referenced by rcOptoKineticImage::gen1DCorrKineticImgs(), rf1DAutoCorr(), and rf1DRegister().
 {
   double sii(0.0), si(0.0), smm(0.0), sm(0.0), sim (0.0);
   int32 n;
   double rsq;
   n = Ie - Ib;
   rmAssert (n);
   rmAssert ((Me - Mb) == n);
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   Iterator ip = Ib;
   Iterator mp = Mb;
   while (ip < Ie)
     {
       double iv (*ip);
       double mv (*mp);
       si += iv;
       sm += mv;
       sii += (iv * iv);
       smm += (mv * mv);
       sim += (iv * mv);
       ip++;
       mp++;
     }
   double cross = ((n * sim) - (si * sm));
   double energyA = ((n * sii) - (si * si));
   double energyB = ((n * smm) - (sm * sm));
   energyA = energyA * energyB;
   rsq = 0.;
   if (energyA != 0.)
     rsq = (cross * cross) / energyA;
   return rsq;
 }
template<class Iterator > double rf1DRegister (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me, uint32 slide, double & pose)
Definition at line 202 of file rc_1dcorr.h.
References parabolicFit(), rf1DNormalizedCorr(), rmAssert, and space.
Referenced by rcLatticeSimilarator::ttc().
 {
   rmAssert (slide >= 1);
   vector<double> space (slide + slide + 1);
   vector<double>::iterator orgItr = space.begin() + slide;
   vector<double>::iterator slidItr;
   // Sliding I to the right
   slidItr = orgItr;
   for (uint32 i = 0; i < (slide + 1); i++)
     {
       *slidItr-- = rf1DNormalizedCorr (Ib + i, Ie, Mb, Me - i);
     }
   // Sliding I to the left (orgin already done)
   slidItr = orgItr+1;
   for (uint32 i = 1; i < (slide + 1); i++)
     {
       *slidItr++ = rf1DNormalizedCorr (Ib, Ie - i, Mb + i, Me);
     }
   vector<double>::iterator endd = space.end();
   advance (endd, -1); // The last guy
   vector<double>::iterator maxd = max_element (space.begin(), space.end());
   pose = *maxd;
   double alignment = (double) distance  (space.begin(), maxd);
   // If the middle is a peak, interpolate around it.
   if (!(space.size() == 1 || maxd == space.begin() || maxd == endd))
     {
       double left (*(maxd-1)), centre (*maxd), right (*(maxd+1));
       if (centre >= left && centre >= right)
     {
       alignment += parabolicFit (left, centre, right, &pose);
     }
     }
   else
     {
       //      cerr << "Edge Condition" << endl;
       //      rfPRINT_STL_ELEMENTS (space);
     }
   return alignment;
 }
template<class Iterator > double rf1DRegister (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me, uint32 slide, double & pose, double & acc)
Definition at line 252 of file rc_1dcorr.h.
References rcStatistics::add(), rcStatistics::mean(), parabolicFit(), rf1DNormalizedCorr(), rmAssert, and space.
 {
     rmAssert (slide >= 1);
     vector<double> space (slide + slide + 1);
     vector<double>::iterator orgItr = space.begin() + slide;
     vector<double>::iterator slidItr;
 // Sliding I to the right
     slidItr = orgItr;
     for (uint32 i = 0; i < (slide + 1); i++)
     {
         *slidItr-- = rf1DNormalizedCorr (Ib + i, Ie, Mb, Me - i);
     }
 // Sliding I to the left (orgin already done)
     slidItr = orgItr+1;
     for (uint32 i = 1; i < (slide + 1); i++)
     {
         *slidItr++ = rf1DNormalizedCorr (Ib, Ie - i, Mb + i, Me);
     }
     vector<double>::iterator endd = space.end();
     advance (endd, -1); // The last guy
     vector<double>::iterator maxd = max_element (space.begin(), space.end());
     pose = *maxd;
     double alignment = (double) distance  (space.begin(), maxd);
     rcStatistics stat;
     vector<double>::iterator tmpIt = space.begin ();
     for (;tmpIt < space.end (); tmpIt++)
     {
         if (tmpIt != maxd) stat.add (*tmpIt);
     }
 //  cerr << space << stat << endl;
 // If the middle is a peak, interpolate around it.
     if (!(space.size() == 1 || maxd == space.begin() || maxd == endd))
     {
         double left (*(maxd-1)), centre (*maxd), right (*(maxd+1));
         acc = stat.mean ();
         if (centre >= left && centre >= right)
         {
             alignment += parabolicFit (left, centre, right, &pose);
         }
     }
     else
     {
       //        cerr << "Edge Condition" << endl;
       //        rfPRINT_STL_ELEMENTS (space);
     }
     return alignment;
 }
template<class Iterator > double rf1DRegister (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me, uint32 slideLeft, uint32 slideRight, double & pose)
Definition at line 311 of file rc_1dcorr.h.
References parabolicFit(), rf1DNormalizedCorr(), rmAssert, and space.
 {
   uint32 slide = slideLeft + slideRight;
   rmAssert (slide >= 1);
   vector<double> space (slideLeft + slideRight + 1);
   vector<double>::iterator orgItr = space.begin() + slideRight;
   vector<double>::iterator slidItr;
   // Sliding I to the right
   slidItr = orgItr;
   for (uint32 i = 0; i < (slideRight + 1); i++)
     {
       *slidItr-- = rf1DNormalizedCorr (Ib + i, Ie, Mb, Me - i);
     }
   // Sliding I to the left (orgin already done)
   slidItr = orgItr+1;
   for (uint32 i = 1; i < (slideLeft + 1); i++)
     {
       *slidItr++ = rf1DNormalizedCorr (Ib, Ie - i, Mb + i, Me);
     }
   vector<double>::iterator endd = space.end();
   advance (endd, -1); // The last guy
   vector<double>::iterator maxd = max_element (space.begin(), space.end());
   pose = *maxd;
   double alignment = (double) distance  (space.begin(), maxd);
   // If the middle is a peak, interpolate around it.
   if (!(space.size() == 1 || maxd == space.begin() || maxd == endd))
     {
       double left (*(maxd-1)), centre (*maxd), right (*(maxd+1));
       if (centre >= left && centre >= right)
     {
       alignment += parabolicFit (left, centre, right, &pose);
     }
     }
   else
     {
       //      cerr << "Edge Condition" << endl;
       //      rfPRINT_STL_ELEMENTS (space);
     }
   return alignment;
 }
template<class Iterator > double rf1dSignalIntersection (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
Definition at line 365 of file rc_1dcorr.h.
References rmAssert, rmMin, and value_type().
Referenced by rcSimilarator::correlate().
 {
   double sm(0.0), sim (0.0);
   int32 n;
   n = Ie - Ib;
   rmAssert (n);
   rmAssert ((Me - Mb) == n);
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   Iterator ip = Ib;
   Iterator mp = Mb;
   while (ip < Ie)
     {
       value_type iv (*ip);
       value_type mv (*mp);
       sm += mv;
       sim += rmMin (iv, mv);
       ip++;
       mp++;
     }
   double cross = sim / sm;
   return cross;
 }
template<class Iterator > double rf1dSignalNormEuclideanIntersection (Iterator Ib, Iterator Ie, Iterator Mb, Iterator Me)
Definition at line 398 of file rc_1dcorr.h.
References rmAssert, rmSquare, and value_type().
 {
   double sm(0.0), sim (0.0);
   int32 n;
   n = Ie - Ib;
   rmAssert (n);
   rmAssert ((Me - Mb) == n);
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   Iterator ip = Ib;
   Iterator mp = Mb;
   while (ip < Ie)
     {
       value_type iv (*ip);
       value_type mv (*mp);
       sim += rmSquare (iv - mv);
       ip++;
       mp++;
     }
    return 1.0 - sim;
 }