Visible: include/util/rc_platform.h File Reference
rc_platform.h File Reference
#include "architecture/i386/alignment.h"
Macros
#define RFY_HELPER_DLL_IMPORT __attribute__ ((visibility("default")))
#define RFY_HELPER_DLL_EXPORT __attribute__ ((visibility("default")))
#define RFY_HELPER_DLL_LOCAL __attribute__ ((visibility("hidden")))
#define RFY_API
#define RFY_LOCAL
#define MAC_OS_X_VERSION_MIN_REQUIRED MAC_OS_X_VERSION_10_5
#define MAC_OS_X_VERSION_MAX_ALLOWED MAC_OS_X_VERSION_10_5
#define _PTHREADS 1
#define rcBOM_BE 0xFEFF
#define rcBOM_LE 0xFFFE
Enumerations
enum reByteOrder { eByteOrderUnknown = 0, eByteOrderBigEndian, eByteOrderLittleEndian }
Functions
bool rfHasSIMD ()
bool rfForceSIMD (bool v)
Macro Definition Documentation
#define _PTHREADS 1
Definition at line 47 of file rc_platform.h.
#define MAC_OS_X_VERSION_MAX_ALLOWED MAC_OS_X_VERSION_10_5
Definition at line 43 of file rc_platform.h.
#define MAC_OS_X_VERSION_MIN_REQUIRED MAC_OS_X_VERSION_10_5
Definition at line 39 of file rc_platform.h.
#define rcBOM_BE 0xFEFF
Definition at line 75 of file rc_platform.h.
Referenced by rfPlatformByteOrder(), and rfPlatformByteOrderMark().
#define rcBOM_LE 0xFFFE
Definition at line 76 of file rc_platform.h.
Referenced by rfPlatformByteOrder(), and rfPlatformByteOrderMark().
#define RFY_API
Definition at line 33 of file rc_platform.h.
#define RFY_HELPER_DLL_EXPORT __attribute__ ((visibility("default")))
Definition at line 18 of file rc_platform.h.
#define RFY_HELPER_DLL_IMPORT __attribute__ ((visibility("default")))
Definition at line 17 of file rc_platform.h.
#define RFY_HELPER_DLL_LOCAL __attribute__ ((visibility("hidden")))
Definition at line 19 of file rc_platform.h.
#define RFY_LOCAL
Definition at line 34 of file rc_platform.h.
Enumeration Type Documentation
enum reByteOrder
Enumerator
eByteOrderUnknown
eByteOrderBigEndian
eByteOrderLittleEndian
Definition at line 69 of file rc_platform.h.
                  {
     eByteOrderUnknown = 0,
     eByteOrderBigEndian,
     eByteOrderLittleEndian
 };
Function Documentation
bool rfForceSIMD (bool v)
Definition at line 57 of file rc_simd_mac.cpp.
References sForceAltiVec.
 {
    sForceAltiVec = v;
    return v;
 }
bool rfHasSIMD ()
Definition at line 33 of file rc_simd_mac.cpp.
References NULL, sForceAltiVec, and sHasAltivec.
Referenced by rcKinetoscope::epiMotionField(), rfAndImage(), rfCorrelate(), rfCorrelateWindow(), rfGauss3(), rfGaussianConv(), rfImageConvert8to32(), rfPixel8Map(), and rcKinetoscope::selfSimilarMotionField_AttentiveCapture().
 {
 #if defined (__ppc__)
     if ( sHasAltivec < 0 ) {
         // Detect Altivec only once
         int selectors[2] = { CTL_HW, HW_VECTORUNIT };
         int hasVectorUnit = 0;
         size_t length = sizeof(hasVectorUnit);
         int error = sysctl(selectors, 2, &hasVectorUnit, &length, NULL, 0);
         if( 0 == error) {
             sHasAltivec = hasVectorUnit;
         }
         else
             sHasAltivec = 0;
     }
     return (sHasAltivec != 0 && sForceAltiVec);
 #elseif
     return false;
 #endif
 }