Visible: src/visible/src/rc_xml.cpp File Reference
rc_xml.cpp File Reference
#include <iostream>
#include <stack>
#include "rc_xml.h"
Typedefs
typedef pair< rcXMLElementType,
int32 > rcIndentedCloseTag
Functions
const rcXMLNameMapper * rfGetXMLNameMapper (int32 version)
ostream & operator<< (ostream &os, const rcXMLOpenTag &e)
ostream & operator<< (ostream &os, const rcXMLCloseTag &e)
ostream & operator<< (ostream &os, const rcXMLEmptyTag &e)
ostream & operator<< (ostream &os, const rcXMLElement &e)
ostream & operator<< (ostream &os, const rcIndentedCloseTag &t)
ostream & operator<< (ostream &os, const rcXMLElementTree &tree)
ostream & output (ostream &os, const rcXMLElementTree &tree, rcProgressIndicator *progress, double completedAlready)
Variables
static const char cOpenBracket = '<'
static const char cCloseBracket = '>'
static const char cDoubleQuote = '\"'
static const char cEquals = '='
static const char cSlash = '/'
static const char cTab = '\t'
static const char cSpace = ' '
static const char cAmpersand = '&'
static const char * cOpenBracketSlash = "</"
static const char * sStartComment = "<!--"
static const char * sEndComment = "-->"
static const rcXMLNameMapper gXMLNameMapper (rcXMLElementNames, eXMLElementMax, rcXMLAttributeNames, eXMLAttributeMax)
static const rcXMLNameMapper gXMLNameMapperV0 (rcXMLElementNamesV0, eXMLElementMax, rcXMLAttributeNamesV0, eXMLAttributeMax)
Typedef Documentation
typedef pair<rcXMLElementType,int32> rcIndentedCloseTag
Definition at line 165 of file rc_xml.cpp.
Function Documentation
ostream& operator<< (ostream & os, const rcXMLOpenTag & e)
Definition at line 69 of file rc_xml.cpp.
References rcXMLNameMapper::attributeName(), rcXMLOpenTag::attributes(), cCloseBracket, cDoubleQuote, cEquals, cOpenBracket, cSpace, rcXMLOpenTag::element(), rcXMLNameMapper::elementName(), eXMLElementComment, gXMLNameMapper, and sStartComment.
 {
     if ( e.element() == eXMLElementComment ) {
         // Special case for comment element
         os << sStartComment;
     } else {
         // Open bracket
         os << cOpenBracket;
         // Tag name
         os << gXMLNameMapper.elementName( e.element() );
         // Attributes
         const rcAttributeList& attributes = e.attributes();
         if ( !attributes.empty() ) {
             rcAttributeList::const_iterator a;
             for ( a = attributes.begin(); a < attributes.end(); a++ ) {
                 // Name
                 os << cSpace << gXMLNameMapper.attributeName( a->first );
                 // Value
                 os << cEquals << cDoubleQuote << a->second << cDoubleQuote;
             }
         }
         // End bracket
         os << cCloseBracket;
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLCloseTag & e)
Definition at line 100 of file rc_xml.cpp.
References cCloseBracket, cOpenBracketSlash, rcXMLCloseTag::element(), rcXMLNameMapper::elementName(), endl(), eXMLElementComment, eXMLElementTrackValue, gXMLNameMapper, and sEndComment.
 {
     const rcXMLElementType type = e.element();
     if ( type == eXMLElementComment ) {
         // Special case for comment element
         os << sEndComment << "\n";
     } else {
         //    </                   name                                  >
         os << cOpenBracketSlash << gXMLNameMapper.elementName( type ) << cCloseBracket;
         if ( type != eXMLElementTrackValue )
             os << endl;
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLEmptyTag & e)
Definition at line 119 of file rc_xml.cpp.
References cCloseBracket, cOpenBracket, cSlash, rcXMLEmptyTag::element(), rcXMLNameMapper::elementName(), eXMLElementComment, gXMLNameMapper, and sEndComment.
 {
     const rcXMLElementType type = e.element();
     if ( type == eXMLElementComment ) {
         // Special case for comment element
         os << sEndComment << "\n";
     } else {
         //    <               name                                  /         >
         os << cOpenBracket << gXMLNameMapper.elementName( type ) << cSlash << cCloseBracket << "\n";
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcXMLElement & e)
Definition at line 136 of file rc_xml.cpp.
References rcXMLElement::attributes(), cAmpersand, cCloseBracket, rcXMLElement::content(), cOpenBracket, and rcXMLElement::type().
{
     // Open tag
     os << rcXMLOpenTag( e.type(), e.attributes() );
     // Content
     const std::string& content = e.content();
     // Character entity reference creation may be required
     for ( uint32 i = 0; i < content.size(); ++i ) {
         const char c = content[i];
         // We MUST use entity references for '<', '>' and '&'
         if ( c == cOpenBracket ) {
             os << "&lt;";
         } else if ( c == cCloseBracket ) {
             os << "&gt;";
         } else if ( c == cAmpersand ) {
             os << "&amp;";
         } else
             os << c;
     }
     // Add newline after an empty element
     if ( content.empty() )
         os << "\n";
     return os;
 }
ostream& operator<< (ostream & os, const rcIndentedCloseTag & t)
Definition at line 169 of file rc_xml.cpp.
 {
     return os << rcXMLCloseTag( t.first );
 }
ostream& operator<< (ostream & os, const rcXMLElementTree & tree)
Definition at line 176 of file rc_xml.cpp.
References NULL, and output().
 {
     return output( os, tree, NULL, 0.0 );
 }
ostream& output (ostream & os, const rcXMLElementTree & tree, rcProgressIndicator * progress, double completedAlready)
Definition at line 182 of file rc_xml.cpp.
References rcProgressIndicator::progress(), and rcXMLElement::type().
Referenced by _sm2out(), lm_unit::dump_header(), rcNativeExporter::exportExperiment(), main(), operator<<(), ini_file::save_file(), library_manager::save_mappings(), lm_unit::write(), and write_context().
 {
     // Pre-order iterators
     rcXMLElementTree::iterator sibBegin = tree.begin();
     rcXMLElementTree::iterator sibEnd = tree.end();
     const uint32 totalElements = tree.size();
     uint32 processedElements = 0;
     // Stack for close tags
     stack<rcIndentedCloseTag> closeStack;
     while ( sibBegin != sibEnd ) {
         const rcXMLElement& e = *sibBegin;
         const rcXMLElementType type = e.type();
         const int32 depth = tree.depth( sibBegin );
         // Report progress
         if ( progress ) {
             if ( !(processedElements % 256) ) {
                 progress->progress( completedAlready + (100.0-completedAlready) * processedElements / totalElements );
             }
             ++processedElements;
         }
         // Pop close tags if necessary
         while ( !closeStack.empty() ) {
             const rcIndentedCloseTag& t = closeStack.top();
             if ( depth <= t.second ) {
                 os << t;
                 closeStack.pop();
             } else
                 break;
         }
         // Open tag with content
         os << e;
         // Optimization, produce close tag immediately if there are no children
         if ( ! tree.number_of_children( sibBegin ) ) {
             // Close tag
             os << rcXMLCloseTag( type );
         }
         else {
             closeStack.push( rcIndentedCloseTag( type, depth ) );
         }
         ++sibBegin;
     }
     while ( !closeStack.empty() ) {
         os << closeStack.top();
         closeStack.pop();
     }
     os << "\n";
     return os;
 }
const rcXMLNameMapper* rfGetXMLNameMapper (int32 version)
Definition at line 40 of file rc_xml.cpp.
References gXMLNameMapper, gXMLNameMapperV0, NULL, and rcXMLFileVersion.
Referenced by rcWriterManager::createWriterGroup(), rcXMLParser::endElement(), and rcNativeImporter::importExperiment().
 {
     switch ( version ) {
         case 0:
         case 1:
             return &gXMLNameMapperV0;
         case 2:
         case rcXMLFileVersion:
             return &gXMLNameMapper;
         default:
             // Unknown version, return latest mapper
             // Loading will be aborted anyway so it doesn't matter
             return &gXMLNameMapper;
     }
     return NULL;
 }
Variable Documentation
const char cAmpersand = '&' static
Definition at line 26 of file rc_xml.cpp.
Referenced by operator<<().
const char cCloseBracket = '>' static
Definition at line 20 of file rc_xml.cpp.
Referenced by operator<<().
const char cDoubleQuote = '\"' static
Definition at line 21 of file rc_xml.cpp.
Referenced by operator<<().
const char cEquals = '=' static
Definition at line 22 of file rc_xml.cpp.
Referenced by operator<<().
const char cOpenBracket = '<' static
Definition at line 19 of file rc_xml.cpp.
Referenced by operator<<().
const char* cOpenBracketSlash = "</" static
Definition at line 28 of file rc_xml.cpp.
Referenced by operator<<().
const char cSlash = '/' static
Definition at line 23 of file rc_xml.cpp.
Referenced by operator<<().
const char cSpace = ' ' static
Definition at line 25 of file rc_xml.cpp.
Referenced by operator<<().
const char cTab = '\t' static
Definition at line 24 of file rc_xml.cpp.
const rcXMLNameMapper gXMLNameMapper(rcXMLElementNames, eXMLElementMax, rcXMLAttributeNames, eXMLAttributeMax) static
Referenced by operator<<(), and rfGetXMLNameMapper().
const rcXMLNameMapper gXMLNameMapperV0(rcXMLElementNamesV0, eXMLElementMax, rcXMLAttributeNamesV0, eXMLAttributeMax) static
Referenced by rfGetXMLNameMapper().
const char* sEndComment = "-->" static
Definition at line 30 of file rc_xml.cpp.
Referenced by operator<<().
const char* sStartComment = "<!--" static
Definition at line 29 of file rc_xml.cpp.
Referenced by operator<<().