Visible: include/visual/rc_polygon.h File Reference
rc_polygon.h File Reference
#include <rc_types.h>
#include <rc_vector2d.h>
#include <rc_affine.h>
#include <rc_graphics.h>
#include <rc_xforms.h>
#include <rc_polygon_edge.h>
#include <algorithm>
#include <iostream>
#include <string>
Classes
class rcPolygon
Functions
void rfPolygonToSegmentsCollection (const rcPolygon &p, rcVisualSegmentCollection &v, bool drawCOM=false)
void rfGenerateSmoothingPts (const rcPolygon &p, vector< rc2Dvector > &smoothedPts, double smoothingDistance)
bool operator!= (const rcPolygon &a, const rcPolygon &b)
Function Documentation
bool operator!= (const rcPolygon & a, const rcPolygon & b) inline
Definition at line 488 of file rc_polygon.h.
References operator==().
 {
   return !operator==(a, b);
 }
void rfGenerateSmoothingPts (const rcPolygon & p, vector< rc2Dvector > & smoothedPts, double smoothingDistance)
Definition at line 80 of file rc_polygon.cpp.
References rc2dVector< T >::distance(), rcPolygon::vertexAt(), and rcPolygon::vertexCnt().
 {
   smoothedPts.clear();
   const int32 vertexCnt = p.vertexCnt();
   if (vertexCnt == 0)
     return;
   rc2Dvector curPt = p.vertexAt(0);
   smoothedPts.push_back(p.vertexAt(0));
   if (vertexCnt == 1)
     return;
   double curDistance = 0.0;
   for (int32 pi = 1; pi < vertexCnt; pi++) {
     const rc2Dvector nextPt = p.vertexAt(pi);
     curDistance += curPt.distance(nextPt);
     if (curDistance >= smoothingDistance) {
       smoothedPts.push_back(nextPt);
       curDistance = 0.0;
     }
     curPt = nextPt;
   }
 }
void rfPolygonToSegmentsCollection (const rcPolygon & p, rcVisualSegmentCollection & v, bool drawCOM = false)
Definition at line 22 of file rc_polygon.cpp.
References rcPolygon::centerOf(), rcRectangle< T >::height(), rcPolygon::orthogonalEnclosingRect(), rcPolygon::vertexAt(), rcPolygon::vertexCnt(), rcRectangle< T >::width(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcImageCanvasGL::drawCurrentFocus(), rcEngineImpl::muscleTracker(), rcEngineImpl::produceMuscleDebugResults(), rfPolygonGroupToGraphicsCollection(), rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
 {
   rc2Dvector pt1, pt2;
   int32 vCnt = p.vertexCnt();
   if (vCnt == 0) {
     return;
   }
   else if (vCnt == 1) {
     pt1 = p.vertexAt(0);
     v.push_back(rcVisualCross(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                   rc2Fvector((float)3.0, (float)3.0)));
   }
   else if (vCnt == 2) {
     pt1 = p.vertexAt(0);
     pt2 = p.vertexAt(1);
     v.push_back(rcVisualLine(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                  rc2Fvector((float)pt2.x(), (float)pt2.y())));
   }
   else if (vCnt & 1) {
     const int32 segCnt = vCnt/2 + 1;
     for (int32 si = 0; si < segCnt-1; si++) {
       pt1 = p.vertexAt(si*2);
       pt2 = p.vertexAt(si*2+1);
       v.push_back(rcVisualLineStrip(rc2Fvector((float)pt1.x(),(float)pt1.y()),
                     rc2Fvector((float)pt2.x(),(float)pt2.y())));
     }
     pt1 = p.vertexAt(vCnt-1);
     pt2 = p.vertexAt(0);
     v.push_back(rcVisualLineStrip(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                   rc2Fvector((float)pt2.x(), (float)pt2.y())));
   }
   else {
     const int32 segCnt = vCnt/2;
     for (int32 si = 0; si < segCnt; si++) {
       pt1 = p.vertexAt(si*2);
       pt2 = p.vertexAt(si*2+1);
       v.push_back(rcVisualLineLoop(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                    rc2Fvector((float)pt2.x(), (float)pt2.y())));
     }
   }
   if (drawCOM)
     {
       rc2Fvector com;
       p.centerOf (com);
       rcIRect r = p.orthogonalEnclosingRect ();
       bool aspect = r.width() > r.height();
       v.push_back(rcVisualCross (com, rc2Fvector (aspect ? 7.0f : 5.0f, aspect ? 5.0f : 7.0f)));
     }
   v.push_back(rcVisualEmpty());
 }