Visible: include/visiCore/rc_engineimpl.h File Reference
rc_engineimpl.h File Reference
#include <math.h>
#include <stdio.h>
#include <errno.h>
#include <string>
#include <iostream>
#include <fstream>
#include <strstream>
#include <algorithm>
#include <set>
#include <signal.h>
#include <sys/wait.h>
#include <stlplus_lite.hpp>
#include <rc_imagegrabber.h>
#include <rc_moviegrabber.h>
#include <rc_reifymoviegrabber.h>
#include <rc_qvideograbber.h>
#include <rc_qtime.h>
#include <rc_dcam_capture.h>
#include <rc_framebuf.h>
#include <rc_moviefileformat.h>
#include <rc_imageprocessing.h>
#include <rc_gen_movie_file.h>
#include <rc_capture.hpp>
#include <rc_persistencemanager.h>
#include <rc_analysis.h>
#include <rc_histstats.h>
#include <rc_analyzer.h>
#include <rc_similarity.h>
#include <rc_musclesegment.h>
#include <rc_ip.h>
#include <rc_ipconvert.h>
#include <rc_1dcorr.h>
#include <rc_systeminfo.h>
#include <rc_setting.h>
#include <rc_thread.h>
#include <rc_engine.h>
#include <rc_atomic.h>
#include <rc_stlplus.h>
#include <rc_engineimplbase.h>
#include <rc_timinginfo.h>
#include "rc_engineimplcapture.h"
#include "rc_engineimplsave.h"
#include "rc_engineimplplayback.h"
#include "rc_featuredefs.h"
#include "rc_staticsettings.h"
Classes
class rcEngineImporter
class rcEngineAnalyzer
class rcEngineImpl
Functions
bool developerDebugging ()
bool developerDebugging (bool)
ostream & rcVisibleBatchUsage (ostream &)
Function Documentation
bool developerDebugging ()
Definition at line 43 of file rc_engineimpl.cpp.
References gDeveloperDebugging.
Referenced by developerDebugging(), rcEngineImpl::isSettingEnabled(), main(), rcEngineImpl::muscleTracker(), and rcEngineImpl::produceDebugResults().
 {
   return gDeveloperDebugging;
 }
bool developerDebugging (bool)
Definition at line 48 of file rc_engineimpl.cpp.
References developerDebugging(), and gDeveloperDebugging.
 {
   gDeveloperDebugging = b;
   return developerDebugging ();
 }
ostream& rcVisibleBatchUsage (ostream &)
Definition at line 278 of file rc_engineimplcmdline.cpp.
References endl().
Referenced by main(), and rcEngineImpl::setFromArgs().
 {
   o << endl;
   o << endl <<
     "       -movie [movieFile]                                                                  " << endl <<
     "       -dirOfTiffs [tiffdir]                                                               " << endl <<
     "       -result [resultFile]                                                                 " << endl <<
     "       -analysis aci|vis|dif|cell   Analysis mode:    aci  - Exhaustive aggregate change index" << endl <<
     "                                               vis  - Exhaustive visual entropy        " << endl <<
     "                                               dif  - Exhaustive diffusion index       " << endl <<
     "                                               cell - Cell tracking (default)          " << endl <<
     "                                               target - Target tracking (default)          " << endl <<
     "       -halfWindow (half window size:            applies to aci/vis/dif                         " << endl <<
     "       -type general|myo|smooth|Flu.    Cell Type: general (default) myocyte              " << endl <<
     "       -report csv|eml            Results format:   csv - Comma separated values            " << endl <<
     "                                               xml - Native Reify XML format           " << endl <<
     "                                               default: Native                         " << endl <<
     "       -graphics no|body|motion|all Graphics output:  no     - None                           " << endl <<
     "                                               body   - Locomotive body (default)      " << endl <<
     "                                               motion - Motion vector                  " << endl <<
     "                                               all    - All                            " << endl <<
     "       -Frame (2 numbers to indicate start/finish  (default: entire frame)             " << endl <<
     "       -TopLeft (2 numbers first indicates X, Second Y)                                " << endl <<
     "       -Size (2 numbers first indicates width, Second height                           " << endl <<
     "       -MaxDisplacement (in Pixels maximum change in position in between sequential frames " << endl <<
     "       -Channel (-1 all, 0, average, 1, 2, 3 (r & g & b or reverse)                    " << endl <<
     "       -advanced: (exp - LongExposure, drg - Dorsal Assay, drgautomask - Dorsal Assay AutoMask)              " << endl <<
     "       -exportImages [exportDirectory]                                         " << endl << endl <<
     "Example: Visible -analysis aci -type myo -graphics no -movie /Users/john/Desktop/foo.rfymov -result /Users/john/Desktop/foo " << endl;
   return o;
 }