Visible: src/analysis/code/rc_kinemotion.cpp File Reference
rc_kinemotion.cpp File Reference
#include <rc_latticesimilarity.h>
#include <rc_1dcorr.h>
#include <rc_line.h>
Functions
static int32 log2max (int32 n)
static void rfDrawCircle (rc2Dvector center, int32 r, rcWindow &dst, uint8 circleColor)
Function Documentation
static int32 log2max (int32 n) static
Definition at line 173 of file rc_kinemotion.cpp.
 {
   int32 power = 1;
   int32 k = 1;
   if (n==1) {
     return 0;
   }
   while ((k <<= 1) < n) {
     power++;
   }
   return power;
 }
static void rfDrawCircle (rc2Dvector center, int32 r, rcWindow & dst, uint8 circleColor) static
Definition at line 189 of file rc_kinemotion.cpp.
References rc2dVector< T >::distance(), rcWindow::height(), rcWindow::setPixel(), and rcWindow::width().
Referenced by drawCells(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), and generateTranslationMovie().
 {
    for(int32 i=0;i< dst.width();i++)
    {
       for(int32 j=0;j< dst.height(); j++)
       {
          rc2Dvector pos(i+0.5,j+0.5);
          if (center.distance (pos) <= r) dst.setPixel (i,j,circleColor);
       }
    }
 }