Visible: src/util/code/rc_systeminfo_mac.cpp File Reference
rc_systeminfo_mac.cpp File Reference
#include <rc_systeminfo.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include <mach-o/arch.h>
#include <mach/mach.h>
#include <mach/mach_host.h>
#include <mach/host_info.h>
#include <mach/machine.h>
#include <vector>
#include <strstream>
Functions
static double get_procspeed (void)
static std::string get_architecture (void)
int32 get_numproc (void)
std::string rfGetHostInfo ()
double rfSystemRam ()
reByteOrder rfPlatformByteOrder ()
uint16 rfPlatformByteOrderMark ()
reByteOrder rfPlatformByteOrder (const uint16 &bom)
Variables
static const int32 sHertzInGig = 1000000000
Function Documentation
static std::string get_architecture (void) static
Definition at line 98 of file rc_systeminfo_mac.cpp.
References NULL.
Referenced by rfGetHostInfo().
 {
   size_t len;
   int retcode;
     std::vector<char> buffer;
   retcode = sysctlbyname ("hw.machine",NULL,&len,NULL,0);
   if (retcode == -1) return std::string ("");
   buffer.resize (len);
   retcode = sysctlbyname ("hw.machine",&buffer[0],&len,NULL,0);
   return std::string (&buffer[0]);
 }
int32 get_numproc (void)
Definition at line 87 of file rc_systeminfo_mac.cpp.
References NULL.
Referenced by rfGetHostInfo().
 {
   size_t len;
   int32 ncpu;
   len = sizeof(ncpu);
   sysctlbyname ("hw.ncpu",&ncpu,&len,NULL,0);
   return ncpu;
 }
static double get_procspeed (void) static
Definition at line 111 of file rc_systeminfo_mac.cpp.
References NULL.
Referenced by rfGetHostInfo().
 {
   size_t len;
   uint64_t procspeed;
   int retcode;
   len = sizeof(procspeed);
   retcode = sysctlbyname ("hw.cpufrequency",&procspeed,&len,NULL,0);
   if (retcode == -1) return - 1.0;
   // procspeed is returned in hertz we should return Mhz
   return (double)procspeed;
 }
std::string rfGetHostInfo ()
Definition at line 28 of file rc_systeminfo_mac.cpp.
References endl(), get_architecture(), get_numproc(), get_procspeed(), rfSystemRam(), and sHertzInGig.
 {
     std::strstream s;
     s << "Architecture: " << get_architecture () << std::endl;
     s << "Number of Processors: " << get_numproc () << std::endl;
     s << "Speed: " << get_procspeed ()  / (sHertzInGig) << std::endl;
 #ifdef __ppc__
     s << "Byte Order: BigEndian " << std::endl;
 #else
     s << "Byte Order: LittleEndian " << std::endl;
 #endif
     s << "Physical Memory (GB) : " << rfSystemRam () / (sHertzInGig) << std::endl;
     s << std::ends;
   return std::string (s.str());
 }
reByteOrder rfPlatformByteOrder ()
Definition at line 56 of file rc_systeminfo_mac.cpp.
References eByteOrderBigEndian, and eByteOrderLittleEndian.
Referenced by fixEndian(), rcMovieFileIdentifier::fixEndian(), rcMovieFileFormat::fixEndian(), rcMovieFileFormat2::fixEndian(), rcMovieFileExt::fixEndian(), rcMovieFileTocExt::fixEndian(), rcMovieFileOrgExt::fixEndian(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcMovieFileExpExt::fixEndian(), rcVideoCache::headerLoadRev2(), TIFFImageIO::Read(), TIFFImageIO::ReadGenericImage(), rcMovieFileFormat::write(), rcMovieFileFormat2::write(), rcMovieFileExt::write(), rcMovieFileTocExt::write(), rcMovieFileOrgExt::write(), rcMovieFileConvExt::write(), rcMovieFileCamExt::write(), and rcMovieFileExpExt::write().
 {
 #if defined (__ppc__)
   return eByteOrderBigEndian;
 #endif
   return eByteOrderLittleEndian;
 }
reByteOrder rfPlatformByteOrder (const uint16 & bom)
Definition at line 74 of file rc_systeminfo_mac.cpp.
References eByteOrderBigEndian, eByteOrderLittleEndian, eByteOrderUnknown, rcBOM_BE, and rcBOM_LE.
 {
   switch ( bom ) {
   case rcBOM_BE:
     return eByteOrderBigEndian;
   case rcBOM_LE:
     return eByteOrderLittleEndian;
   default:
     return eByteOrderUnknown;
   }
 }
uint16 rfPlatformByteOrderMark ()
Definition at line 65 of file rc_systeminfo_mac.cpp.
References rcBOM_BE, and rcBOM_LE.
Referenced by rcMovieFileExt::write(), rcMovieFileTocExt::write(), rcMovieFileOrgExt::write(), rcMovieFileConvExt::write(), rcMovieFileCamExt::write(), and rcMovieFileExpExt::write().
 {
 #if defined (__ppc__)
   return rcBOM_BE;
 #endif
   return rcBOM_LE;
 }
double rfSystemRam ()
Definition at line 44 of file rc_systeminfo_mac.cpp.
References NULL.
Referenced by genSignatureFromMov(), rcEngineImpl::loadMovie(), and rfGetHostInfo().
 {
   uint64_t mem;
   size_t len = sizeof(mem);
   sysctlbyname("hw.memsize", &mem, &len, NULL, 0);
   return (double) mem;
 }
Variable Documentation
const int32 sHertzInGig = 1000000000 static
Definition at line 21 of file rc_systeminfo_mac.cpp.
Referenced by rfGetHostInfo().