Visible: include/analysis/rc_analyzer.h File Reference
rc_analyzer.h File Reference
#include <deque>
#include <rc_framebuf.h>
#include <rc_analysis.h>
#include <rc_similarity.h>
#include <rc_framegrabber.h>
Classes
class rcAnalyzerOptions
class rcAnalyzerResult
class rcAnalyzer
Enumerations
enum rcAnalyzerState {
eAnalyzerInitialized = 0, eAnalyzerStarted, eAnalyzerStopped, eAnalyzerCached,
eAnalyzerError
}
enum rcAnalyzerMode { eAnalyzerFullCorrelation = 0, eAnalyzerApproximation }
enum rcAnalyzerResultOrigin { eAnalyzerResultOriginLeft = 0, eAnalyzerResultOriginCenter, eAnalyzerResultOriginRight }
Functions
ostream & operator<< (ostream &os, const rcAnalyzerOptions &o)
Enumeration Type Documentation
enum rcAnalyzerMode
Enumerator
eAnalyzerFullCorrelation
eAnalyzerApproximation
Definition at line 23 of file rc_analyzer.h.
                     {
   // Full cross-correlation is computed between all frames within the temporal window.
   eAnalyzerFullCorrelation = 0,
   // Pairwise cross-correlation is computed for all adjacent frames within the temporal window.
   // Approximation is used for correlation of non-adjacent frames
   eAnalyzerApproximation
 };
enum rcAnalyzerResultOrigin
Enumerator
eAnalyzerResultOriginLeft
eAnalyzerResultOriginCenter
eAnalyzerResultOriginRight
Definition at line 32 of file rc_analyzer.h.
{
   // Computed metric for frames [N, N+1, N+2] will be returned as a value for frame N
   eAnalyzerResultOriginLeft = 0,
   // Computed metric for frames [N, N+1, N+2] will be returned as a value for frame N+1
   eAnalyzerResultOriginCenter,
   // Computed metric for frames [N, N+1, N+2] will be returned as a value for frame N+2
   eAnalyzerResultOriginRight
 };
enum rcAnalyzerState
Enumerator
eAnalyzerInitialized
eAnalyzerStarted
eAnalyzerStopped
eAnalyzerCached
eAnalyzerError
Definition at line 14 of file rc_analyzer.h.
                      {
   eAnalyzerInitialized = 0,
   eAnalyzerStarted,
   eAnalyzerStopped,
   eAnalyzerCached,
   eAnalyzerError
 };
Function Documentation
ostream& operator<< (ostream & os, const rcAnalyzerOptions & o)
Definition at line 365 of file rc_analyzer.cpp.
References rcAnalyzerOptions::bound(), rcAnalyzerOptions::mode(), rcAnalyzerOptions::origin(), and rcAnalyzerOptions::windowSize().
Referenced by otext::operator<<().
 {
   // Output basic options
   // TODO: display rsCorrParams
   os << "Mode " << o.mode();
   os << " origin " << o.origin();
   os << " rect " << o.bound();
   os << " window " << o.windowSize();
   return os;
 }