Visible: include/visual/rc_qtime.h File Reference
rc_qtime.h File Reference
#include <Carbon/Carbon.h>
#include <QuickTime/QuickTime.h>
#include <QuickTime/ImageCompression.h>
#include <QuickTime/QuickTimeComponents.h>
#include <ApplicationServices/ApplicationServices.h>
#include <rc_window.h>
#include <vector>
Functions
OSErr rfImageFileToRcWindow (vector< rcWindow > &images, vector< std::string > &fileNames)
OSErr rfMovieFileToRcWindow (vector< rcWindow > &images, const std::string &fileName)
void getPixelInfoFromImageDesc (ImageDescriptionHandle anImageDesc, rcPixel &pd, uint32 &pixelFormat, bool &isGray, bool &isWhiteReversed, CTabHandle *ctb)
OSErr getNextVideoSample (Movie theMovie, rcWindow &image, Media media, TimeValue fromTimePoint, bool reduceGrayTo8bit=FALSE)
void rfFillColorMap (const CTabHandle ctb, rcSharedFrameBufPtr &frame, bool reverse=false)
int rfImageFrameNum (char *const fileName)
void rfImageNameSort (vector< std::string > &fileNames)
OSErr ValidFSSpec (const FSSpec *spec)
FSSpec rfMakeFSSpecFromPosixPath (const char *file_name, bool isDirectory)
Function Documentation
OSErr getNextVideoSample (Movie theMovie, rcWindow & image, Media media, TimeValue fromTimePoint, bool reduceGrayTo8bit = FALSE)
Definition at line 681 of file rc_qtime.cpp.
References rcWindow::depth(), getPixelInfoFromImageDesc(), getVideoMediaImageDesc(), NULL, rcPixel32, rcPixel8, rfFillColorMap(), rfRcWindow32to8(), rfReversePixels8(), rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcFrame::setIsGray().
Referenced by rfMovieFileToRcWindow().
 {
    OSErr            anErr = noErr;
    GWorldPtr        gWorld = NULL;
    rcWindow         tmp, tmp2;
    PixMapHandle pixMap = NULL;
    CGrafPtr     aSavedPort, moviePort;
    GDHandle     aSavedGDevice, movieGDevice;
    Rect         movieRect;
    rcPixel  pd;
    uint32       pf;
    SampleDescriptionHandle imageDescH = NULL;
    CTabHandle   ctb;
    bool             isGray;
    bool             isWhiteReversed = false;
    assert(theMovie != NULL);
    //• Store away current portrect and Gdevice, get pixel sizes and color table for GWorld creation purposes.
    GetGWorld(&aSavedPort, &aSavedGDevice);
    GetMovieGWorld(theMovie, &moviePort, &movieGDevice);
    //• Adjust the movie box.
    GetMovieBox(theMovie, &movieRect);
    uint32 width = movieRect.right - movieRect.left;
    uint32 height = movieRect.bottom - movieRect.top;
     Rect boundsRect; boundsRect.left = boundsRect.top = 0; boundsRect.bottom =  height; boundsRect.right = width;
    // Get depth, format, and color table infomation for this movie
    // Get the image description for the movie
    // Allocate a handle for sample description
    imageDescH = (SampleDescriptionHandle)NewHandle(sizeof(Handle));
    getVideoMediaImageDesc (media, imageDescH);
    getPixelInfoFromImageDesc ((ImageDescriptionHandle) imageDescH, pd, pf, isGray,
                               isWhiteReversed, &ctb);
    // Create aGWorld for writing the movie in to
    // We will allocate GWorld memory ourselves as a framebuf ===> Dispose will not free this memory
    try
    {
        rcPixel depth = pd;
        rcSharedFrameBufPtr buf(new rcFrame (width, height, depth));
        buf->setIsGray(isGray);
        rcWindow rw (buf);
        tmp = rw;
        tmp2 = rw;
        assert (pf);
        anErr = NewGWorldFromPtr( &gWorld, pf, &boundsRect, ctb, NULL, 0, (char *) (tmp.rowPointer(0)), tmp.rowUpdate ());
        if (noErr != anErr)
        {
            goto Closure; // Should throw an exception ????
        }
        if ( reduceGrayTo8bit && isGray && depth > rcPixel8 ) {
            depth = rcPixel8;
            rcSharedFrameBufPtr buf8(new rcFrame (width, height, depth));
            buf8->setIsGray(isGray);
            // Produce color map
            rfFillColorMap( ctb, buf8 );
            rcWindow image8(buf8);
            // Reduce image depth
            rfRcWindow32to8( tmp, image8 );
            tmp2 = image8;
        } else {
            // Produce color map if necessary
            if ( depth < rcPixel32 && !isWhiteReversed) {
                rfFillColorMap( ctb, buf );
            }
        }
    }
    catch (...)
    {
        goto Closure;
    }
    pixMap = GetGWorldPixMap(gWorld);
    LockPixels(pixMap);
    //• Draw the next first video sample (frame) to GWorld number.
    SetMovieGWorld(theMovie, gWorld, GetGWorldDevice(gWorld));
    SetMovieTimeValue(theMovie, fromTimePoint);
    UpdateMovie(theMovie); MoviesTask(theMovie, 0);
    UnlockPixels(pixMap);
    if ( isWhiteReversed && tmp2.depth() == rcPixel8 ) {
        // Color map indicates that pixel value 0 is white
        // Reverse pixels and use default color map
        rfReversePixels8( tmp2 );
    }
    // Copy it to the vector
    image = tmp2;
    SetGWorld(aSavedPort, aSavedGDevice);
     //• Closure. Clean up if we have handles.
 Closure:
    if(gWorld != NULL)
        DisposeGWorld(gWorld);
    SetMovieGWorld(theMovie, moviePort, movieGDevice);
    SetGWorld(aSavedPort, aSavedGDevice);
    return anErr;
 }
void getPixelInfoFromImageDesc (ImageDescriptionHandle anImageDesc, rcPixel & pd, uint32 & pixelFormat, bool & isGray, bool & isWhiteReversed, CTabHandle * ctb)
Definition at line 601 of file rc_qtime.cpp.
References rcPixel32, rcPixel8, rcPixelUnknown, and rmAssert.
Referenced by getNextVideoSample(), rfImageFileToRcWindow(), and rfMovieFileToRcWindow().
 {
    rmAssert (ctb);
    int16 aPixelDepth = (*anImageDesc)->depth;
    // Get the color table
    GetImageDescriptionCTable (anImageDesc, ctb);
    int16 csize = (**ctb)->ctSize;
    isGray = false;
    isWhiteReversed = false;
    // Check grayness
    if ( csize > 0 ) {
        isGray = true;
        // Test each color table entry
        for ( int16 i = 0; i < csize + 1; ++i ) {
            const int r = (**ctb)->ctTable[i].rgb.red;
            const int g = (**ctb)->ctTable[i].rgb.green;
            const int b = (**ctb)->ctTable[i].rgb.blue;
            if ( r != g || g != b ) {
                isGray = false;
                break;
            }
        }
        if ( isGray ) {
            // Test whether index 0 contains white
            isWhiteReversed = true;
            for ( int16 i = 1; i < csize + 1; ++i ) {
                const int prev = (**ctb)->ctTable[i-1].rgb.red;
                const int cur = (**ctb)->ctTable[i].rgb.red;
                if ( prev < cur ) {
                    isWhiteReversed = false;
                    break;
                }
            }
        }
    }
    switch( aPixelDepth ) {
        case 8:
            pd = rcPixel8;
            pixelFormat = k8IndexedPixelFormat;
            break;
        case 16:
            pd = rcPixel32;
            pixelFormat = k32ARGBPixelFormat;
            break;
        case 24:
            pd = rcPixel32;
            pixelFormat = k32ARGBPixelFormat;
            break;
        case 32:
            pd = rcPixel32;
            pixelFormat = k32ARGBPixelFormat;
            break;
        case 40:
            pd = rcPixel8;
            pixelFormat = k8IndexedGrayPixelFormat;
            break;
        default:
            pd = rcPixelUnknown;
            pixelFormat = k32ARGBPixelFormat;
            break;
    }
 #ifdef DEBUG_LOG
    fprintf (stderr, "Pixel depth in movie file is %d ==> %d bytes in depth - %s - %s - %s - color table size %i\n",
             aPixelDepth, pd, isGray ? "is Gray" : "is not Gray",
             isWhiteReversed ? "0 is white" : "0 is black",
             pixelFormat == k8IndexedPixelFormat ? "k8IndexedPixelFormat" :
             (pixelFormat == k8IndexedGrayPixelFormat) ? "k8IndexedGrayPixelFormat" :
             (pixelFormat == k32ARGBPixelFormat) ? "k32ARGBPixelFormat" : "Other",
             csize );
 #endif
 }
void rfFillColorMap (const CTabHandle ctb, rcSharedFrameBufPtr & frame, bool reverse = false)
Definition at line 411 of file rc_qtime.cpp.
References color(), rcFrame::colorMap(), rcFrame::colorMapSize(), rcFrame::getColor(), rfRgb, rmAssert, and rcFrame::setColor().
Referenced by rcQVideoGrabber::getNextFrame(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rcEngineMovieCapture::initializeCamera(), and rfImageFileToRcWindow().
 {
     rmAssert( frame->colorMap() != 0 );
     rmAssert( frame->colorMapSize() > 0 );
     uint16 cMapSize = frame->colorMapSize();
     int16 csize = 0;
     if ( ctb )
         csize = (*ctb)->ctSize + 1; // Element 0 is always there
     if ( csize > 1 ) {
         rmAssert( csize <= cMapSize );
         if ( csize < cMapSize )
             cMapSize = csize;
         // Set color map values
         for (int i = 0; i < cMapSize; i++) {
             uint32 r = (*ctb)->ctTable[i].rgb.red;
             uint32 g = (*ctb)->ctTable[i].rgb.green;
             uint32 b = (*ctb)->ctTable[i].rgb.blue;
             // Reverse black and white
             if ( reverse ) {
                 r = 65535 - r;
                 g = 65535 - g;
                 b = 65535 - b;
             }
             // QuickTime uses 16-bit color component values, we must
             // scale them down to 8-bit component values
             uint32 color = rfRgb( r/256, g/256, b/256 );
             frame->setColor( i, color );
             rmAssert( frame->getColor( i ) == color );
 #ifdef DEBUG_LOG_TABLE
             fprintf (stderr, "[%d]: %d\t%d\t%d \t\t%d\t%d\t%d \t\t%u\n",
                      i, r, g, b, r/256, g/256, b/256, color );
 #endif
         }
     } else {
         // Set default linear gray scale values
         for (int i = 0; i < cMapSize; i++) {
             int c = cMapSize - i - 1;
             // Force 8-bit color component value range
             if ( c > 256 )
                 c /= 256;
             uint32 color = rfRgb( c, c, c );
             frame->setColor( i, color );
             rmAssert( frame->getColor( i ) == color );
 #ifdef DEBUG_LOG
             fprintf (stderr, "[%d]: %d\t%d\t%d\t\t%u\n",
                      i, c, c, c, color );
 #endif
         }
     }
 }
OSErr rfImageFileToRcWindow (vector< rcWindow > & images, vector< std::string > & fileNames)
Definition at line 186 of file rc_qtime.cpp.
References rfQuicktimeImporter::gi, rfImageFileToRcWindowGi(), rfMakeFSSpecFromPosixPath(), and ValidFSSpec().
 {
     rfQuicktimeImporter gi;
     vector<FSSpec*> fileHandles;
     vector<std::string>::iterator file;
     for( file = fileNames.begin(); file < fileNames.end(); ++file )
     {
         bool isvalid = false;
         FSSpec spec = rfMakeFSSpecFromPosixPath( (*file).c_str(), isvalid);
         if ( ValidFSSpec( &spec ) == noErr )
         {
             FSSpec* newSpec = new FSSpec(spec);
             fileHandles.push_back( newSpec );
         }
     }
     OSErr status = rfImageFileToRcWindowGi( images, fileHandles, gi.gi );
     // Delete specs
     for (vector<FSSpec*>::iterator f = fileHandles.begin(); f != fileHandles.end(); f++)
         delete *f;
     return status;
 }
int rfImageFrameNum (char *const fileName)
Definition at line 143 of file rc_qtime.cpp.
Referenced by fileCompare(), rcImageGrabber::rcImageGrabber(), and rfImageFileToRcWindowGi().
 {
    int i;
    int num = 0;
    char * s = fileName;
    // get to the .
    for(;*s != 0;++s)
        ; // get to the end of the string
    while (s != fileName &&  (*s < '0' || *s > '9'))
        s--;  // find last number
    for (i = 0; s != fileName; s--, i++) {
        const char c = *s;
        if (c >= '0' && c <= '9')
        {
            int j = i;
            int p = 1;
            while (j) p *= 10, j--;
            num += (i == 0) ? (c - '0') : p * (c - '0');
        }
        else if ( c != 0 )
            break; // Only consider the first continuous sequence of numbers
    }
    return num;
 }
void rfImageNameSort (vector< std::string > & fileNames)
Definition at line 178 of file rc_qtime.cpp.
References fileCompare().
Referenced by rcImageGrabber::rcImageGrabber().
 {
     // TODO: filecompare can be slow, we could precompute
     // frame index numbers
     stable_sort( names.begin(), names.end(), fileCompare );
 }
FSSpec rfMakeFSSpecFromPosixPath (const char * file_name, bool isDirectory)
Definition at line 473 of file rc_qtime.cpp.
References FSSpecFromPosixPath(), and NULL.
Referenced by rcMovieConverterToQT::createQTMovie(), rcImageGrabber::rcImageGrabber(), rcMovieGrabber::rcMovieGrabber(), rfImageFileToRcWindow(), and rfMovieFileToRcWindow().
 {
     FSSpec filespec;
     bool isDirectory;
     CFStringRef posixPathRef = CFStringCreateWithCString ( NULL, posixPath, kCFStringEncodingUTF8);
     bool err = FSSpecFromPosixPath (posixPathRef, filespec, isDirectory);
     isValid = err == true;
     return filespec;
 }
OSErr rfMovieFileToRcWindow (vector< rcWindow > & images, const std::string & fileName)
Definition at line 309 of file rc_qtime.cpp.
References countFrames(), getNextVideoSample(), getPixelInfoFromImageDesc(), getVideoMediaImageDesc(), NULL, rfMakeFSSpecFromPosixPath(), and ValidFSSpec().
 {
    FSSpec   theFSSpec;
    short    refnum = 0;
    TimeValue    duration;
    TimeValue    theTime = 0, nextTime = 0;
    int32 frameCount = -1;
    Movie    thisMovie;
    uint32 fc, width, height;
    Media media;
    Rect     aMovieRect;
    OSErr err = noErr;
    OSType       whichMediaType = VIDEO_TYPE;
    short        flags = nextTimeMediaSample + nextTimeEdgeOK;
    SampleDescriptionHandle anImageDesc = NULL;
    assert (frames.size() == 0);
     bool isDir = false;
    theFSSpec = rfMakeFSSpecFromPosixPath( fileName.c_str(), isDir );
    err = ValidFSSpec( &theFSSpec );
    if ( err != noErr )
        return err;
    // Initialize QuickTime
    err = EnterMovies();
    assert (err == noErr);
    if ( err != noErr )
        return err;
    // open a Movie file using the FSSpec and create a Movie from that file.
    err = OpenMovieFile(&theFSSpec, &refnum, fsRdPerm);
    assert (err == noErr);
    if ( err != noErr )
        return err;
    NewMovieFromFile(&thisMovie, refnum, NULL, NULL, newMovieActive, NULL);
    err = GetMoviesStickyError ();
    err = GetMoviesError();
    fc = countFrames (&thisMovie); // VideoMediaType
    assert (fc > 0);
    vector<rcWindow> images (fc);
    GetMovieBox(thisMovie, &aMovieRect);
    width = aMovieRect.right - aMovieRect.left;
    height = aMovieRect.bottom - aMovieRect.top;
    media = GetTrackMedia (GetMovieIndTrack (thisMovie, 1));
    // Allocate a handle for sample description
    anImageDesc = (SampleDescriptionHandle)NewHandle(sizeof(Handle));
    // Get the image description for the movie
    getVideoMediaImageDesc (media, anImageDesc);
    // From Image description to rcWindow Depth
    rcPixel dp;
    uint32 pf;
    CTabHandle ctb;
    bool isGray;
    bool isWhiteReversed;
    getPixelInfoFromImageDesc ((ImageDescriptionHandle) anImageDesc, dp, pf, isGray, isWhiteReversed, &ctb);
    // If it is a depth we like, create rcWindows and fill them up.
    assert (dp != 0);
    vector<rcWindow>::iterator img;
    for( img = images.begin(); img < images.end(); img++ )
    {
       frameCount++;
       GetMovieNextInterestingTime(thisMovie,
                                   flags,
                                   1,
                                   &whichMediaType,
                                   theTime,
                                   0,
                                   &nextTime,
                                   &duration);
       if ( theTime < 0 )
           break;
       // Store the frame
       err = getNextVideoSample(thisMovie, *img, media, theTime, true );
       flags = nextTimeMediaSample;
       theTime = nextTime;
    }
    frames = images;
 //bail:
      DisposeMovie (thisMovie);
       //    we're done with the file.
       if (refnum)
          CloseMovieFile(refnum);
       return err;
 }
OSErr ValidFSSpec (const FSSpec * spec)
Definition at line 525 of file rc_qtime.cpp.
Referenced by rcMovieConverterToQT::createQTMovie(), rcImageGrabber::rcImageGrabber(), rcMovieGrabber::rcMovieGrabber(), rfImageFileToRcWindow(), and rfMovieFileToRcWindow().
 {
     if (! spec->name[0] || (spec->name[0] + (sizeof(FSSpec) - sizeof(spec->name)) > sizeof(FSSpec)))
         return paramErr;
     FInfo fndrInfo;
     return FSpGetFInfo(spec, &fndrInfo);
 }