Visible: include/util/rc_systeminfo.h File Reference
rc_systeminfo.h File Reference
#include <rc_types.h>
Functions
std::string rfGetHostInfo ()
double rfSystemRam ()
reByteOrder rfPlatformByteOrder ()
uint16 rfPlatformByteOrderMark ()
reByteOrder rfPlatformByteOrder (const uint16 &bom)
Function Documentation
std::string rfGetHostInfo ()
Definition at line 28 of file rc_systeminfo_mac.cpp.
References endl(), get_architecture(), get_numproc(), get_procspeed(), rfSystemRam(), and sHertzInGig.
 {
     std::strstream s;
     s << "Architecture: " << get_architecture () << std::endl;
     s << "Number of Processors: " << get_numproc () << std::endl;
     s << "Speed: " << get_procspeed ()  / (sHertzInGig) << std::endl;
 #ifdef __ppc__
     s << "Byte Order: BigEndian " << std::endl;
 #else
     s << "Byte Order: LittleEndian " << std::endl;
 #endif
     s << "Physical Memory (GB) : " << rfSystemRam () / (sHertzInGig) << std::endl;
     s << std::ends;
   return std::string (s.str());
 }
reByteOrder rfPlatformByteOrder ()
Definition at line 56 of file rc_systeminfo_mac.cpp.
References eByteOrderBigEndian, and eByteOrderLittleEndian.
Referenced by fixEndian(), rcMovieFileIdentifier::fixEndian(), rcMovieFileFormat::fixEndian(), rcMovieFileFormat2::fixEndian(), rcMovieFileExt::fixEndian(), rcMovieFileTocExt::fixEndian(), rcMovieFileOrgExt::fixEndian(), rcMovieFileConvExt::fixEndian(), rcMovieFileCamExt::fixEndian(), rcMovieFileExpExt::fixEndian(), rcVideoCache::headerLoadRev2(), TIFFImageIO::Read(), TIFFImageIO::ReadGenericImage(), rcMovieFileFormat::write(), rcMovieFileFormat2::write(), rcMovieFileExt::write(), rcMovieFileTocExt::write(), rcMovieFileOrgExt::write(), rcMovieFileConvExt::write(), rcMovieFileCamExt::write(), and rcMovieFileExpExt::write().
 {
 #if defined (__ppc__)
   return eByteOrderBigEndian;
 #endif
   return eByteOrderLittleEndian;
 }
reByteOrder rfPlatformByteOrder (const uint16 & bom)
Definition at line 74 of file rc_systeminfo_mac.cpp.
References eByteOrderBigEndian, eByteOrderLittleEndian, eByteOrderUnknown, rcBOM_BE, and rcBOM_LE.
 {
   switch ( bom ) {
   case rcBOM_BE:
     return eByteOrderBigEndian;
   case rcBOM_LE:
     return eByteOrderLittleEndian;
   default:
     return eByteOrderUnknown;
   }
 }
uint16 rfPlatformByteOrderMark ()
Definition at line 65 of file rc_systeminfo_mac.cpp.
References rcBOM_BE, and rcBOM_LE.
Referenced by rcMovieFileExt::write(), rcMovieFileTocExt::write(), rcMovieFileOrgExt::write(), rcMovieFileConvExt::write(), rcMovieFileCamExt::write(), and rcMovieFileExpExt::write().
 {
 #if defined (__ppc__)
   return rcBOM_BE;
 #endif
   return rcBOM_LE;
 }
double rfSystemRam ()
Definition at line 44 of file rc_systeminfo_mac.cpp.
References NULL.
Referenced by genSignatureFromMov(), rcEngineImpl::loadMovie(), and rfGetHostInfo().
 {
   uint64_t mem;
   size_t len = sizeof(mem);
   sysctlbyname("hw.memsize", &mem, &len, NULL, 0);
   return (double) mem;
 }