Visible: src/visible/src/rc_captureregs.cpp File Reference
rc_captureregs.cpp File Reference
#include "rc_captureregs.h"
Functions
ostream & operator<< (ostream &os, const rcVideoCaptureCtrl &c)
Function Documentation
ostream& operator<< (ostream & os, const rcVideoCaptureCtrl & c)
Definition at line 12 of file rc_captureregs.cpp.
References endl(), rcVideoCaptureCtrlReader::getACIEnabled(), rcVideoCaptureCtrlReader::getBinning(), rcVideoCaptureCtrlReader::getDecimationRate(), rcVideoCaptureCtrlReader::getEntropyDefinition(), rcVideoCaptureCtrlReader::getGain(), rcVideoCaptureCtrlReader::getShutter(), rcVideoCaptureCtrlReader::getSlidingWindowEnabled(), rcVideoCaptureCtrlReader::getSlidingWindowOrigin(), and rcVideoCaptureCtrlReader::getSlidingWindowSize().
 {
     os << " decimationRate " << c.getDecimationRate()
        << " slidingWindowSize " << c.getSlidingWindowSize()
        << " slidingWindowOrigin " << c.getSlidingWindowOrigin()
        << " slidingWindowEnabled " << c.getSlidingWindowEnabled()
        << " aciEnabled " << c.getACIEnabled()
        << " entropyDef " << c.getEntropyDefinition()
        << " gain " << c.getGain()
        << " shutter " << c.getShutter()
        << " shutter " << c.getBinning()
        << endl;
     return os;
 }