Visible: src/visible/src/rc_nativeexporter.cpp File Reference
rc_nativeexporter.cpp File Reference
#include <strstream>
#include <vector>
#include <rc_setting.h>
#include <rc_model.h>
#include "rc_nativeexporter.h"
Functions
static const std::string cGroupComment (" Measurement group definitions ")
static const std::string cTrackComment (" Measurement track definitions ")
static const std::string cValueComment (" Measurement values ")
static const std::string cTimeComment (" Measurement times ")
static const std::string cSettingCategoryComment (" Application settings ")
Variables
static const std::string cXmlDeclaration = "<?xml version=\"1.0\" encoding=\"ISO-8859_1\" standalone=\"yes\"?>\n"
Function Documentation
static const std::string cGroupComment (" Measurement group definitions ") static
Referenced by rcNativeExporter::produceGroups().
static const std::string cSettingCategoryComment (" Application settings ") static
Referenced by rcNativeExporter::produceSettings().
static const std::string cTimeComment (" Measurement times ") static
Referenced by rcNativeExporter::produceTimes().
static const std::string cTrackComment (" Measurement track definitions ") static
Referenced by rcNativeExporter::produceTracks().
static const std::string cValueComment (" Measurement values ") static
Referenced by rcNativeExporter::produceResults().
Variable Documentation
const std::string cXmlDeclaration = "<?xml version=\"1.0\" encoding=\"ISO-8859_1\" standalone=\"yes\"?>\n" static
Definition at line 23 of file rc_nativeexporter.cpp.
Referenced by rcNativeExporter::xmlDeclaration().