Visible: include/util/rc_stats.h File Reference
rc_stats.h File Reference
#include <rc_types.h>
#include <rc_limits.h>
#include <algorithm>
#include <vector>
#include <deque>
#include <numeric>
Classes
class rcStatistics
Functions
template<class T >
double rfMedian (const vector< T > &a)
template<class T >
double rfMedian (const deque< T > &a)
template<class T >
double rfSum (const vector< T > &a)
template<class T >
double rfSum (const deque< T > &a)
template<class T >
double rfMean (const vector< T > &a)
template<class T >
T rfRMS (const vector< T > &a)
template<class T >
void rfRMS (const vector< T > &a, vector< T > &b)
template<class T >
void rfcSum (const deque< T > &a, deque< T > &b)
template<class T >
void rfProductOfrValues (const vector< T > &a, vector< T > &b)
template<class T >
void rfRevRMS (const vector< T > &a, vector< T > &b)
Function Documentation
template<class T > void rfcSum (const deque< T > & a, deque< T > & b)
Definition at line 140 of file rc_stats.h.
References rmAssert.
 {
     if (a.size() < 1) return;
     rmAssert (a.size() == b.size());
         // These typename definitions silence gcc compiler warnings
     typedef typename deque<T>::iterator iterator;
     typedef typename deque<T>::const_iterator const_iterator;
     iterator fs = b.begin();
     const_iterator accPtr = a.begin();
     T sofar ( (T) 0);
     int32 i (1);
     for (; accPtr < a.end(); fs++, accPtr++, i++)
     {
         sofar += (*accPtr);
         *fs = sofar;
     }
 }
template<class T > double rfMean (const vector< T > & a)
Definition at line 87 of file rc_stats.h.
References rfSum().
Referenced by rcEngineImpl::groupStatistics().
  {
    const int32 length =  a.size();
    if ( length == 0 )
        return 0.0;
    double s = rfSum (a);
    return s / (double) a.size();
  }
template<class T > double rfMedian (const vector< T > & a)
Definition at line 25 of file rc_stats.h.
  {
    const int32 length =  a.size();
    if ( length == 0 )
        return 0.0;
    const bool is_odd = length % 2;
    const int array_length = (length / 2) + 1;
    vector<T> array (array_length);
    partial_sort_copy(a.begin(), a.end(), array.begin(), array.end());
    if (is_odd)
      return double(array [array_length-1]);
    else
      return double( (array [array_length - 2] + array [array_length-1]) / T(2) );
 }
template<class T > double rfMedian (const deque< T > & a)
Definition at line 46 of file rc_stats.h.
  {
    const int32 length =  a.size();
    if ( length == 0 )
        return 0.0;
    const bool is_odd = length % 2;
    const int array_length = (length / 2) + 1;
    deque<T> array (array_length);
    partial_sort_copy(a.begin(), a.end(), array.begin(), array.end());
    if (is_odd)
      return double(array [array_length-1]);
    else
      return double( (array [array_length - 2] + array [array_length-1]) / T(2) );
 }
template<class T > void rfProductOfrValues (const vector< T > & a, vector< T > & b)
Definition at line 163 of file rc_stats.h.
References rmAssert.
 {
  if (a.size() < 1) return;
   rmAssert (a.size() == b.size());
   // These typename definitions silence gcc compiler warnings
   typedef typename vector<T>::iterator iterator;
   typedef typename vector<T>::const_iterator const_iterator;
   iterator fs = b.begin();
   const_iterator accPtr = a.begin();
   T sofar ( (T) 1);
   int32 i (1);
   for (; accPtr < a.end(); fs++, accPtr++, i++)
     {
       sofar *= (*accPtr);
       *fs = sofar;
     }
 }
template<class T > void rfRevRMS (const vector< T > & a, vector< T > & b)
Definition at line 186 of file rc_stats.h.
References rmAssert, and rmSquare.
 {
   if (a.size() < 1) return;
   rmAssert (a.size() == b.size());
   // These typename definitions silence gcc compiler warnings
   typedef typename vector<T>::iterator iterator;
   typedef typename vector<T>::const_reverse_iterator const_iterator;
   iterator fs = b.begin();
   const_iterator accPtr = a.rbegin();
   T sofar ( (T) 0);
   int32 i (1);
   for (; accPtr < a.rend(); fs++, accPtr++, i++)
     {
       sofar += rmSquare (*accPtr);
       *fs = sqrt (sofar / (T) i);
     }
 }
template<class T > T rfRMS (const vector< T > & a)
Definition at line 100 of file rc_stats.h.
References rmAssert, and rmSquare.
 {
   rmAssert (a.size() > 1);
   // These typename definitions silence gcc compiler warnings
   typedef typename vector<T>::iterator iterator;
   typedef typename vector<T>::const_iterator const_iterator;
   const_iterator accPtr = a.begin();
   T sofar ( (T) 0);
   int32 i (0);
   for (; accPtr < a.end(); accPtr++, i++)
     sofar += rmSquare (*accPtr);
   return (T) (sqrt (sofar / (T) i));
 }
template<class T > void rfRMS (const vector< T > & a, vector< T > & b)
Definition at line 118 of file rc_stats.h.
References rmAssert, and rmSquare.
 {
   if (a.size() < 1) return;
   rmAssert (a.size() == b.size());
   // These typename definitions silence gcc compiler warnings
   typedef typename vector<T>::iterator iterator;
   typedef typename vector<T>::const_iterator const_iterator;
   iterator fs = b.begin();
   const_iterator accPtr = a.begin();
   T sofar ( (T) 0);
   int32 i (1);
   for (; accPtr < a.end(); fs++, accPtr++, i++)
     {
       sofar += rmSquare (*accPtr);
       *fs = sqrt (sofar / (T) i);
     }
 }
template<class T > double rfSum (const vector< T > & a)
Definition at line 67 of file rc_stats.h.
Referenced by rcSpatialPyramid< 2 >::gradientProcess(), and rfMean().
  {
    const int32 length =  a.size();
    if ( length == 0 )
        return 0.0;
    return (double) accumulate (a.begin(), a.end(), T(0));
 }
template<class T > double rfSum (const deque< T > & a)
Definition at line 77 of file rc_stats.h.
 {
     const int32 length =  a.size();
     if ( length == 0 )
         return 0.0;
     return (double) accumulate (a.begin(), a.end(), T(0));
 }