Visible: include/util/rc_security.h File Reference
rc_security.h File Reference
#include <rc_types.h>
Classes
class rcSecurityKey
class rcEncryptionEngine
class rcLicenseManager
Enumerations
enum rcSecurityError {
eSecurityErrorOK = 0, eSecurityErrorUnknown, eSecurityErrorNoLicense, eSecurityErrorInvalidLicense,
eSecurityErrorInvalidHost, eSecurityErrorLicenseExpired, eSecurityErrorInternal
}
Variables
const char rcA [] = "r$fqy(3="
const char rcB [] = "45yi(j'="
const char rcC [] = "856#jdnb"
const char rcD [] = "yup9$#f,"
const char rcE [] = "5r0-fbny"
const char rcF [] = "@9irvb./"
const char rcG [] = "8qf$.v(3"
const char rcH [] = "y/fnr.8v"
const char rcI [] = "65yh(j'r"
const char rcJ [] = "%93rwb.9"
const char rcK [] = "*ei,vbbp"
Enumeration Type Documentation
enum rcSecurityError
Enumerator
eSecurityErrorOK
eSecurityErrorUnknown
eSecurityErrorNoLicense
eSecurityErrorInvalidLicense
eSecurityErrorInvalidHost
eSecurityErrorLicenseExpired
eSecurityErrorInternal
Definition at line 37 of file rc_security.h.
                      {
     eSecurityErrorOK = 0,         // No error
     eSecurityErrorUnknown,        // Unknown error
     eSecurityErrorNoLicense,      // No license file found
     eSecurityErrorInvalidLicense, // Invalid/corrupt license file
     eSecurityErrorInvalidHost,    // License not valid for host
     eSecurityErrorLicenseExpired, // License has expired
     eSecurityErrorInternal,       // Internal error
 };
Variable Documentation
const char rcA[] = "r$fqy(3="
Definition at line 20 of file rc_security.h.
Referenced by rcLicenseManager::rcLicenseManager().
const char rcB[] = "45yi(j'="
Definition at line 22 of file rc_security.h.
Referenced by rcLicenseManager::rcLicenseManager().
const char rcC[] = "856#jdnb"
Definition at line 23 of file rc_security.h.
Referenced by rcLicenseManager::rcLicenseManager().
const char rcD[] = "yup9$#f,"
Definition at line 24 of file rc_security.h.
const char rcE[] = "5r0-fbny"
Definition at line 25 of file rc_security.h.
const char rcF[] = "@9irvb./"
Definition at line 26 of file rc_security.h.
const char rcG[] = "8qf$.v(3"
Definition at line 27 of file rc_security.h.
const char rcH[] = "y/fnr.8v"
Definition at line 30 of file rc_security.h.
const char rcI[] = "65yh(j'r"
Definition at line 32 of file rc_security.h.
Referenced by rcLicenseManager::rcLicenseManager().
const char rcJ[] = "%93rwb.9"
Definition at line 33 of file rc_security.h.
const char rcK[] = "*ei,vbbp"
Definition at line 34 of file rc_security.h.
Referenced by rcLicenseManager::rcLicenseManager().