Visible: src/analysis/code/rc_kinefield.cpp File Reference
rc_kinefield.cpp File Reference
#include <rc_kinetoscope.h>
#include <rc_platform.h>
#include <rc_moments.h>
#include <rc_analysis.h>
#include <rc_fit.h>
#include <rc_histstats.h>
#include <rc_edge.h>
#include <iomanip>
#include <rc_ipconvert.h>
Functions
static bool withinPreSegmentedBodies (vector< rcPolygon > &sml, rcIPair &offset, rcIPair loc)
Variables
static const rcIPair sOne (1, 1)
static const rcIPair sTwo = sOne + sOne
Function Documentation
static bool withinPreSegmentedBodies (vector< rcPolygon > & sml, rcIPair & offset, rcIPair loc) static
Definition at line 34 of file rc_kinefield.cpp.
References rcRectangle< T >::lr(), rmAssert, rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
 {
   vector<rcPolygon>::iterator sit = sml.begin();
   rcRectangle<int32> reg (loc - offset, loc + offset);
   rmAssert (loc.x() >= offset.x());
   rmAssert (loc.y() >= offset.y());
   rcPolygon poly;
   // Push in the CCW
   rmAssert (poly.pushUniqueVertex (rc2Dvector (reg.ul())));
   rmAssert (poly.pushUniqueVertex (rc2Dvector (reg.ul() + rcIPair (reg.width(), 0))));
   rmAssert (poly.pushUniqueVertex (rc2Dvector (reg.lr())));
   rmAssert (poly.pushUniqueVertex (rc2Dvector (reg.lr() - rcIPair (reg.width(), 0))));
   rmAssert (poly.isValid());
   rmAssert (poly.isConvex());
   bool within (false);
   for (;sit != sml.end(); sit++)
     {
       if (sit->intersects (poly))
     {
       within = true;
       break;
     }
     }
   return within;
 }
Variable Documentation
const rcIPair sOne(1, 1) static
const rcIPair sTwo = sOne + sOne static
Definition at line 13 of file rc_kinefield.cpp.