Visible: include/util/rc_fileutils.h File Reference
rc_fileutils.h File Reference
#include <iostream>
#include <string.h>
#include <sys/stat.h>
#include <dirent.h>
#include <sys/dir.h>
#include <vector>
#include <deque>
#include <rc_types.h>
#include <rc_pair.h>
#include <cstdio>
#include <list>
#include <iterator>
#include <stdexcept>
#include <glob.h>
Classes
class rcGlobIterator
an STL-style iterator for the STLGlob class
class rcGlob
C++ wrapper around the glob() system call.
Macros
#define __rcFILEUTILS_H
Functions
int alphasort ()
void RFY_API rfGetDirEntries (const string &dirname, vector< std::string > &entries, const char *imageformat="tif")
bool RFY_API rfIsDirectory (const char *inFullPath)
int32 RFY_API rfGetFileSize (const char *inFullPath)
bool RFY_API rfFileExists (const std::string &filename)
std::string RFY_API rfStripPath (const std::string &fileName)
std::string RFY_API rfStripExtension (const std::string &fileName)
std::string RFY_API rfGetExtension (const std::string &fileName)
std::string RFY_API rfMakeTmpFileName (const char *pathFormat, const char *baseName)
std::string RFY_API rfMakeTmpFileName (const char *baseName)
std::string rfDumpMatrix (deque< deque< double > > &matrix, const char *pathFormat=0, const char *baseName=defaultBase)
Variables
static const char * defaultBase = "zoubin"
Macro Definition Documentation
#define __rcFILEUTILS_H
Definition at line 216 of file rc_fileutils.h.
Function Documentation
int alphasort ()
std::string rfDumpMatrix (deque< deque< double > > & matrix, const char * pathFormat = 0, const char * baseName = defaultBase)
Definition at line 387 of file rc_fileutils.cpp.
References endl(), and rfMakeTmpFileName().
 {
   std::string fname = rfMakeTmpFileName (pathFormat, baseName) + std::string (".txt");
   ofstream file (fname.c_str ());
   if (! file)
     {
       return std::string ("");
     }
   deque<deque <double> >::iterator rowI = matrix.begin ();
   deque<deque <double> >::iterator rowend = matrix.end();
   ios::fmtflags oldflags = file.flags ();
   file.setf (ios::fixed);
   file << setprecision(12);
   for (; rowI < rowend; rowI++)
     {
       deque<double>::iterator cellI = (*rowI).begin ();
       deque<double>::iterator cellBend = (*rowI).end();
       advance (cellBend, -1);
       for (; cellI < cellBend; cellI++)
     file << *cellI << ",";
       file << *cellI << endl;
     }
   file.flags (oldflags);
   return fname;
 }
bool RFY_API rfFileExists (const std::string & filename)
Definition at line 416 of file rc_fileutils.cpp.
 {
     struct stat buf;
     if (stat(filename.c_str(), &buf) != -1)
     {
         return true;
     }
     return false;
 }
void RFY_API rfGetDirEntries (const string & dirname, vector< std::string > & entries, const char * imageformat = "tif")
Definition at line 39 of file rc_fileutils.cpp.
References alphasorthalf(), jpgfilter(), numericsort(), pngfilter(), and tiffilter().
Referenced by rcFileChoiceSettingWidget::directoryBrowse4Tiffs(), main(), and rcEngineImpl::setFromArgs().
 {
   direct ** darray;
   int entryCount (0);
   if (strncmp(imageformat, "tif", 3) == 0)
     {
       entryCount = scandir(
                const_cast<char *>(dirname.c_str()), &darray,
                tiffilter, numericsort);
     }
   if (strncmp(imageformat, "jpg", 3) == 0)
     {
       entryCount = scandir(
                const_cast<char *>(dirname.c_str()), &darray,
                jpgfilter, alphasorthalf);
     }
     if (strncmp(imageformat, "png", 3) == 0)
     {
         entryCount = scandir(
                              const_cast<char *>(dirname.c_str()), &darray,
                              pngfilter, alphasorthalf);
     }
   for(int k=0; k < entryCount; k++)
     {
       std::string name (darray[k]->d_name);
       name = dirname + std::string ("/") + name;
       entries.push_back(name);
     }
 }
std::string RFY_API rfGetExtension (const std::string & fileName)
Definition at line 218 of file rc_fileutils.cpp.
Referenced by rcEngineImpl::loadMovie().
 {
   // Get file name without extension
   const std::string dot( "." );
   uint32 s = fileName.find_last_of( dot );
   if ( s != std::string::npos )
     return fileName.substr( s , std::string::npos );
   return fileName;
 }
int32 RFY_API rfGetFileSize (const char * inFullPath)
Definition at line 80 of file rc_fileutils.cpp.
 {
   std::ifstream f;
   f.open(sFileName, std::ios_base::binary | std::ios_base::in);
   if (!f.good() || f.eof() || !f.is_open()) { return 0; }
   f.seekg(0, std::ios_base::beg);
   std::ifstream::pos_type begin_pos = f.tellg();
   f.seekg(0, std::ios_base::end);
   return static_cast<int>(f.tellg() - begin_pos);
 }
bool RFY_API rfIsDirectory (const char * inFullPath)
Definition at line 103 of file rc_fileutils.cpp.
Referenced by main().
 {
   struct stat dirstat;
   if (stat(inFullPath, &dirstat) == 0)
     {
       if ((dirstat.st_mode & S_IFDIR) == S_IFDIR)
     return true;
     }
   return false;
 }
std::string RFY_API rfMakeTmpFileName (const char * pathFormat, const char * baseName)
Definition at line 365 of file rc_fileutils.cpp.
References rcTimestamp::now(), rmDim, and rcTimestamp::secs().
Referenced by rfDirectionSignal(), rfDumpMatrix(), and rfMakeTmpFileName().
 {
   char buf[2048];
   static const char *defaultFormat = "/tmp/um%d_%s";
   // Use current time in seconds as a pseudo-unique prefix
   double secs = rcTimestamp::now().secs();
   snprintf( buf, rmDim(buf), pathFormat ? pathFormat : defaultFormat,
         uint32(secs), baseName );
   return std::string( buf );
 }
std::string RFY_API rfMakeTmpFileName (const char * baseName)
Definition at line 378 of file rc_fileutils.cpp.
References rfMakeTmpFileName().
 {
   return rfMakeTmpFileName (0, baseName);
 }
std::string RFY_API rfStripExtension (const std::string & fileName)
Definition at line 205 of file rc_fileutils.cpp.
Referenced by rcExperimentDomainImpl::notifyMovieImport().
 {
   // Get file name without extension
   const std::string dot( "." );
   uint32 s = fileName.find_last_of( dot );
   if ( s != std::string::npos )
     return fileName.substr( 0, s );
   return fileName;
 }
std::string RFY_API rfStripPath (const std::string & fileName)
Definition at line 189 of file rc_fileutils.cpp.
Referenced by rcEngineImpl::loadMovie(), rcEngineImpl::muscleTracker(), and rcExperimentDomainImpl::notifyMovieImport().
 {
   // Get file name without preceding path
   const std::string slash( "/" );
   uint32 s = fileName.find_last_of( slash );
   if ( s != std::string::npos ) {
     uint32 len = fileName.size() - s - 1;
     if ( len > 0 )
       return fileName.substr( s+1, len );
   }
   return fileName;
 }
Variable Documentation
const char* defaultBase = "zoubin" static
Definition at line 211 of file rc_fileutils.h.