Visible: include/visiCore/rc_model.h File Reference
rc_model.h File Reference
#include <rc_value.h>
#include <rc_uitypes.h>
#include <rc_setting.h>
#include <rc_timestamp.h>
#include <rc_xml.h>
#include <rc_persistencemanager.h>
#include <rc_graphics.h>
#include <rc_affine.h>
#include <rc_polygongroup.h>
Classes
class rcModelException
class rcExperimentDomainFactory
class rcExperimentDomain
class rcExperimentObserver
class rcExperiment
class rcTrackGroup
class rcTrack
class rcScalarTrack
class rcVideoTrack
class rcGraphicsTrack
class rcPositionTrack
class rcSegmentIterator
class rcVideoSegmentIterator
class rcScalarSegmentIterator
class rcGraphicsSegmentIterator
class rcPositionSegmentIterator
Enumerations
enum rcExperimentState {
eExperimentEmpty = 0, eExperimentRunning, eExperimentPlayback, eExperimentEnded,
eExperimentLocked
}
enum rcTrackType {
eVideoTrack = 0, eScalarTrack, ePositionTrack, eGraphicsTrack,
eMaxTrack
}
Functions
ostream & operator<< (ostream &os, rcSegmentIterator &i)
Variables
const std::string cTrackTypeNames []
Enumeration Type Documentation
enum rcExperimentState
Enumerator
eExperimentEmpty
eExperimentRunning
eExperimentPlayback
eExperimentEnded
eExperimentLocked
Definition at line 47 of file rc_model.h.
 {
     eExperimentEmpty = 0    // experiment was created but not run
   , eExperimentRunning      // experiment is running
   , eExperimentPlayback     // experiment is being played back
   , eExperimentEnded        // experiment has ended
   , eExperimentLocked       // experiment has ended and been saved
 };
enum rcTrackType
Enumerator
eVideoTrack
eScalarTrack
ePositionTrack
eGraphicsTrack
eMaxTrack
Definition at line 57 of file rc_model.h.
 {
     eVideoTrack = 0     // track contains video frames
   , eScalarTrack        // track contains scalar data
   , ePositionTrack      // track contains <x,y> position data
   , eGraphicsTrack      // track contains graphical data for visualization
   , eMaxTrack           // synthetic sentinel
 };
Function Documentation
ostream& operator<< (ostream & os, rcSegmentIterator & i)
Definition at line 323 of file rc_segmentimpl.cpp.
References endl(), rcSegmentIterator::getSegmentIndex(), rcSegmentIterator::getSegmentLength(), rcSegmentIterator::getSegmentOffset(), rcSegmentIterator::getSegmentStart(), rcSegmentIterator::getSegmentStartAbsolute(), and rcSegmentIterator::getTrackOffset().
 {
     os << "rcSegmentIterator";
     rcTimestamp segStart = i.getSegmentStart();
     rcTimestamp segAbsStart = i.getSegmentStartAbsolute();
     rcTimestamp segLen = i.getSegmentLength();
     os << " segRelStart " << segStart << " segAbsStart " << segAbsStart << " segLen " << segLen <<  " segRelEnd " << segStart + segLen;
     os << " position " << i.getTrackOffset() << " segIdx " << i.getSegmentIndex() << " segOffset " << i.getSegmentOffset() << endl;
     return os;
 }
Variable Documentation
const std::string cTrackTypeNames[]
Initial value:
=
{
    "video",
    "scalar",
    "position",
    "graphics",
    "unknown"
}
Definition at line 68 of file rc_model.h.
Referenced by rcTrack::name(), and rcTrack::type().