Visible: include/visual/rc_window.h File Reference
rc_window.h File Reference
#include <rc_framebuf.h>
#include <rc_rect.h>
#include <iomanip>
#include <Accelerate/Accelerate.h>
#include <ApplicationServices/ApplicationServices.h>
#include <vector>
Classes
class rcWindow
Functions
void rfSetWindowBorder (rcWindow &win, double val)
Function Documentation
void rfSetWindowBorder (rcWindow & win, double val)
Definition at line 949 of file rc_window.cpp.
References rcWindow::depth(), rcWindow::isD32Float(), rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, rf_SetWindowBorder(), rmExceptionMacro, and SETPIXELBORDER.
 {
   switch (win.depth())
     {
       SETPIXELBORDER(rcPixel8,uint8);
       SETPIXELBORDER(rcPixel16,uint16);
       SETPIXELBORDER(rcPixelDouble,double);
     case rcPixel32:
       if (!win.isD32Float())
     rf_SetWindowBorder (win, (uint32) val);
       else
     rf_SetWindowBorder (win, (float) val);
       return;
     default:
       rmExceptionMacro(<< "IP Window::not implemented");
     }
 }