Visible: src/visual/code/rc_polygon.cpp File Reference
rc_polygon.cpp File Reference
#include <rc_polygon.h>
#include <map>
#include <set>
#include <iostream>
#include <rc_macro.h>
Classes
class uniqueOrder< T >
class thetaOrder< T >
Macros
#define DBGPRT 0
#define DBGPRT2 0
#define DBGPRT3 0
Functions
void rfPolygonToSegmentsCollection (const rcPolygon &p, rcVisualSegmentCollection &v, bool drawCOM)
void rfGenerateSmoothingPts (const rcPolygon &p, vector< rc2Dvector > &smoothedPts, double smoothingDistance)
ostream & operator<< (ostream &ous, const rcPolygon &p)
bool operator== (const rcPolygon &a, const rcPolygon &b)
Macro Definition Documentation
#define DBGPRT 0
Definition at line 17 of file rc_polygon.cpp.
Referenced by rcPolygon::contains(), rcPolygon::convexIntersection(), rcPolygon::isValid(), rcPolygon::parallelInter(), and rcPolygon::segmentInter().
#define DBGPRT2 0
Definition at line 18 of file rc_polygon.cpp.
Referenced by rcPolygon::findPeak(), rcPolygon::genMinEnclosingRect(), and rcPolygon::genMinRectBounds().
#define DBGPRT3 0
Definition at line 19 of file rc_polygon.cpp.
Referenced by rcPolygon::convexComparedToConvex().
Function Documentation
ostream& operator<< (ostream & ous, const rcPolygon & p)
Definition at line 1866 of file rc_polygon.cpp.
References rcPolygon::_isConvex, rcPolygon::_isValid, rcPolygon::_knownConvex, rcPolygon::_knownValid, rcPolygon::perimeter(), rcPolygon::vertexAt(), and rcPolygon::vertexCnt().
 {
   const int32 vertexCnt = p.vertexCnt();
   rc2Dvector cop;
   const_cast<rcPolygon *>(&p)->centerOf (cop);
   std::string yConvex("CY"), nConvex("CN"), uConvex("C?");
   std::string yValid("VY"), nValid("VN"), uValid("V?");
   ous << "{ " << vertexCnt << " ";
   ous << "Area: " << const_cast<rcPolygon *>(&p)->area () << " Perimeter: " << p.perimeter () << " Center Of Mass: " << cop << ", ";
   ous << (p._knownValid ? (p._isValid ? yValid.c_str() : nValid.c_str())
       : uValid.c_str());
   ous << (p._knownConvex ? (p._isConvex ? yConvex.c_str() : nConvex.c_str())
       : uConvex.c_str());
   ous << " |";
   for (int32 i = 0; i < vertexCnt; i++)
     ous << " " << i << " " << p.vertexAt(i);
   ous << " }";
   return ous;
 }
bool operator== (const rcPolygon & a, const rcPolygon & b)
Definition at line 1891 of file rc_polygon.cpp.
References rcPolygon::_isConvex, rcPolygon::_isValid, rcPolygon::_knownConvex, rcPolygon::_knownValid, count(), rcPolygon::isConvex(), rcPolygon::isValid(), rmAssert, rcPolygon::vertexAt(), and rcPolygon::vertexCnt().
Referenced by rcCorr::operator!=(), and operator!=().
 {
   int32 count = a.vertexCnt();
   if (count != b.vertexCnt())
     return false;
   else if (count == 0)
     return true;
   int32 base = 0;
   for ( ; base < count; base++)
     if (a.vertexAt(0) == b.vertexAt(base))
       break;
   if (base == count)
     return false;
   for (int32 i = 0; i < count; i++)
     if (a.vertexAt(i) != b.vertexAt(base+i))
       return false;
   if (a._knownValid && b._knownValid)
     rmAssert(a.isValid() == b.isValid());
   if (a._knownConvex && b._knownConvex)
     rmAssert(a.isConvex() == b.isConvex());
   if (a._knownValid && !b._knownValid) {
     (const_cast<rcPolygon&>(b))._knownValid = a._knownValid;
     (const_cast<rcPolygon&>(b))._isValid = a._isValid;
   }
   if (!a._knownValid && b._knownValid) {
     (const_cast<rcPolygon&>(a))._knownValid = b._knownValid;
     (const_cast<rcPolygon&>(a))._isValid = b._isValid;
   }
   if (a._knownConvex && !b._knownConvex) {
     (const_cast<rcPolygon&>(b))._knownConvex = a._knownConvex;
     (const_cast<rcPolygon&>(b))._isConvex = a._isConvex;
   }
   if (!a._knownConvex && b._knownConvex) {
     (const_cast<rcPolygon&>(a))._knownConvex = b._knownConvex;
     (const_cast<rcPolygon&>(a))._isConvex = b._isConvex;
   }
   return true;
 }
void rfGenerateSmoothingPts (const rcPolygon & p, vector< rc2Dvector > & smoothedPts, double smoothingDistance)
Definition at line 80 of file rc_polygon.cpp.
References rc2dVector< T >::distance(), rcPolygon::vertexAt(), and rcPolygon::vertexCnt().
 {
   smoothedPts.clear();
   const int32 vertexCnt = p.vertexCnt();
   if (vertexCnt == 0)
     return;
   rc2Dvector curPt = p.vertexAt(0);
   smoothedPts.push_back(p.vertexAt(0));
   if (vertexCnt == 1)
     return;
   double curDistance = 0.0;
   for (int32 pi = 1; pi < vertexCnt; pi++) {
     const rc2Dvector nextPt = p.vertexAt(pi);
     curDistance += curPt.distance(nextPt);
     if (curDistance >= smoothingDistance) {
       smoothedPts.push_back(nextPt);
       curDistance = 0.0;
     }
     curPt = nextPt;
   }
 }
void rfPolygonToSegmentsCollection (const rcPolygon & p, rcVisualSegmentCollection & v, bool drawCOM)
Definition at line 22 of file rc_polygon.cpp.
References rcPolygon::centerOf(), rcRectangle< T >::height(), rcPolygon::orthogonalEnclosingRect(), rcPolygon::vertexAt(), rcPolygon::vertexCnt(), rcRectangle< T >::width(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcImageCanvasGL::drawCurrentFocus(), rcEngineImpl::muscleTracker(), rcEngineImpl::produceMuscleDebugResults(), rfPolygonGroupToGraphicsCollection(), rcKinetoscope::visualDebugGraphics(), and rcKinetoscope::visualFunctionMap().
 {
   rc2Dvector pt1, pt2;
   int32 vCnt = p.vertexCnt();
   if (vCnt == 0) {
     return;
   }
   else if (vCnt == 1) {
     pt1 = p.vertexAt(0);
     v.push_back(rcVisualCross(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                   rc2Fvector((float)3.0, (float)3.0)));
   }
   else if (vCnt == 2) {
     pt1 = p.vertexAt(0);
     pt2 = p.vertexAt(1);
     v.push_back(rcVisualLine(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                  rc2Fvector((float)pt2.x(), (float)pt2.y())));
   }
   else if (vCnt & 1) {
     const int32 segCnt = vCnt/2 + 1;
     for (int32 si = 0; si < segCnt-1; si++) {
       pt1 = p.vertexAt(si*2);
       pt2 = p.vertexAt(si*2+1);
       v.push_back(rcVisualLineStrip(rc2Fvector((float)pt1.x(),(float)pt1.y()),
                     rc2Fvector((float)pt2.x(),(float)pt2.y())));
     }
     pt1 = p.vertexAt(vCnt-1);
     pt2 = p.vertexAt(0);
     v.push_back(rcVisualLineStrip(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                   rc2Fvector((float)pt2.x(), (float)pt2.y())));
   }
   else {
     const int32 segCnt = vCnt/2;
     for (int32 si = 0; si < segCnt; si++) {
       pt1 = p.vertexAt(si*2);
       pt2 = p.vertexAt(si*2+1);
       v.push_back(rcVisualLineLoop(rc2Fvector((float)pt1.x(), (float)pt1.y()),
                    rc2Fvector((float)pt2.x(), (float)pt2.y())));
     }
   }
   if (drawCOM)
     {
       rc2Fvector com;
       p.centerOf (com);
       rcIRect r = p.orthogonalEnclosingRect ();
       bool aspect = r.width() > r.height();
       v.push_back(rcVisualCross (com, rc2Fvector (aspect ? 7.0f : 5.0f, aspect ? 5.0f : 7.0f)));
     }
   v.push_back(rcVisualEmpty());
 }