Visible: src/util/code/rc_units.cpp File Reference
rc_units.cpp File Reference
#include <rc_math.h>
#include <iostream>
#include <vector>
Functions
bool rfIsPowerOf2 (int32 n)
int32 rfLog2max (int32 n)
bool rfRealEq (rcRadian x, rcRadian y, rcRadian epsilon)
double rfRanOne (int32 &idum)
double rfGasDev (int32 &idum)
int32 rfGCDeuclid (int32 a, int32 b)
Function Documentation
double rfGasDev (int32 & idum)
Definition at line 146 of file rc_units.cpp.
References rfRanOne().
 {
   static int32 iset=0;
   static double gset;
   double fac,rsq,v1,v2;
   if (idum < 0) iset=0;
   if (iset == 0) {
     do {
       v1=2.0*rfRanOne(idum)-1.0;
       v2=2.0*rfRanOne(idum)-1.0;
       rsq=v1*v1+v2*v2;
     } while (rsq >= 1.0 || rsq == 0.0);
     fac=sqrt(-2.0*log(rsq)/rsq);
     gset=v1*fac;
     iset=1;
     return v2*fac;
   } else {
     iset=0;
     return gset;
   }
 }
int32 rfGCDeuclid (int32 a, int32 b)
Definition at line 169 of file rc_units.cpp.
References rmABS, rmMax, and rmMin.
  {
    /* Returns the greatest common divisor of u and v by Euclid's method.
     * I have experimented also with Stein's method, which involves only
     * subtraction and left/right shifting; Euclid is faster, both for
     * integers of size 0 - 1024 and also for random integers of a size
     * which fits in a long integer.  Stein's algorithm might be better
     * when the integers are HUGE, but for our purposes, Euclid is fine.
     *
     * Walter H. F. Smith, 25 Feb 1992, after D. E. Knuth, vol. II  */
    int32 u,v,r;
    u = rmMax (rmABS(a), rmABS(b));
    v = rmMin (rmABS(a), rmABS(b));
    while (v > 0) {
      r = u%v;    /* Knuth notes that u < 2v 40% of the time;  */
      u = v;      /* thus we could have tried a subtraction  */
      v = r;      /* followed by an if test to do r = u%v  */
    }
    return(u);
  }
bool rfIsPowerOf2 (int32 n)
Definition at line 38 of file rc_units.cpp.
 {
   if ( n == 0 ) return false;
   while( (n % 2) == 0 )
     {
       n >>= 1;
     }
   return (n == 1);
 }
int32 rfLog2max (int32 n)
Definition at line 48 of file rc_units.cpp.
 {
   int32 power = 1;
   int32 k = 1;
   if (n==1) {
     return 0;
   }
   while ((k <<= 1) < n) {
     power++;
   }
   return power;
 }
double rfRanOne (int32 & idum)
Definition at line 115 of file rc_units.cpp.
Referenced by rfGasDev().
 {
   const int32 IA=16807,IM=2147483647,IQ=127773,IR=2836,NTAB=32;
   const int32 NDIV=(1+(IM-1)/NTAB);
   const double EPS=3.0e-16,AM=1.0/IM,RNMX=(1.0-EPS);
   static int32 iy=0;
     static std::vector<int32> iv(NTAB);
   int32 j,k;
   double temp;
   if (idum <= 0 || !iy) {
     if (-idum < 1) idum=1;
     else idum = -idum;
     for (j=NTAB+7;j>=0;j--) {
       k=idum/IQ;
       idum=IA*(idum-k*IQ)-IR*k;
       if (idum < 0) idum += IM;
       if (j < NTAB) iv[j] = idum;
     }
     iy=iv[0];
   }
   k=idum/IQ;
   idum=IA*(idum-k*IQ)-IR*k;
   if (idum < 0) idum += IM;
   j=iy/NDIV;
   iy=iv[j];
   iv[j] = idum;
   if ((temp=AM*iy) > RNMX) return RNMX;
   else return temp;
 }
bool rfRealEq (rcRadian x, rcRadian y, rcRadian epsilon)
Definition at line 64 of file rc_units.cpp.
References abs().
Referenced by rcVisualFunction::beatProcess(), rcVisualFunction::dividingProcess(), rcInfLine::intersect(), rc2dVector< float >::isLenNull(), rc2dVector< float >::isNull(), rcVisualFunction::measure(), rcKinetoscope::newGeneration(), parabolicFit(), rcVisualFunction::populationMigration(), and rfRealEq().
 {
   return abs((x - y).normSigned()) <= epsilon;
 }