Visible: include/util/rc_fit.h File Reference
rc_fit.h File Reference
#include <rc_vector2d.h>
#include <vector>
Macros
#define rmSigmoid(a) (1.0/(1.0+exp(-(double) a)))
Functions
template<class T >
T parabolicFit (const T left, const T center, const T right, T *maxp=NULL)
template<>
double parabolicFit (const double left, const double center, const double right, double *maxp)
template<>
float parabolicFit (const float left, const float center, const float right, float *maxp)
template<class T >
T rfParabolicFitNonPeak (const T left, const T center, const T right, T *maxp=NULL)
template<class T , class M >
void parfit2DR3 (const vector< T > &score, rc2dVector< M > &v)
template<class T , class M >
void parfit2DR3 (const T &score11, const T &score12, const T &score13, const T &score21, const T &score22, const T &score23, const T &score31, const T &score32, const T &score33, rc2dVector< M > &v)
void rfParfit2DR3 (const vector< double > &score, rc2Dvector &v)
void rfParfit2DR3 (const vector< float > &score, rc2Fvector &v)
void rfParfit2DR3 (const float &score11, const float &score12, const float &score13, const float &score21, const float &score22, const float &score23, const float &score31, const float &score32, const float &score33, rc2Fvector &v)
double rfParabolicFit (const vector< double > &space)
double rfParabolicFit (const vector< double > &space, double *dmax)
float rfParabolicFit (const vector< float > &space)
template<class T >
void rfMomentFit (const vector< T > &first, T &x, T &y)
template<class T >
void rfMomentFit (const vector< vector< T > > &space, T &x, T &y)
rcMomentFit :Return interpolated positions wrt center of :in the 1D case and top of the search space :in case of the 2D.
template<class P >
float rfInterpolatePeak (const vector< P > &signal, uint32 index, P *ampP=NULL)
double rfGasDev (int32 &idum)
double rfRanOne (int32 &idum)
Macro Definition Documentation
#define rmSigmoid (a) (1.0/(1.0+exp(-(double) a)))
Definition at line 7 of file rc_fit.h.
Function Documentation
template<class T > T parabolicFit (const T left, const T center, const T right, T * maxp = NULL) inline
Definition at line 13 of file rc_fit.h.
References rmExceptionMacro.
Referenced by rcVisualFunction::beatProcess(), rcOptoKineticImage::gen1DCorrKineticImgs(), rcMuscleTracker::genEdgePoints(), interPeak(), rcMotionVectorPath::parabolicDisparity(), rf1DFourierAnalysis(), rf1DFourierAnalysisVoxels(), rf1DRegister(), rfInterpolatePeak(), and rfParabolicFit().
 {
   const bool cl (center == left);
   const bool cr (center == right);
   if ((!(center > left || cl ) && !(center > right || cr )) &&
       (!(center < left || cl ) && !(center < right || cr )))
     rmExceptionMacro (<<" Invalid Data " << left << "," <<
               center << "," << right);
   const T s = left + right;
   const T d = right - left;
   const T c = center + center;
   // case: center is at max
   if (c == s)
     {
       if (maxp) *maxp = center;
       return 0;
     }
   // ymax for the quadratic
   if (maxp) *maxp = (4 * c * c - 4 * c * s + d * d) / (8 * (c - s));
   // position of the max
   return d / (2 * (c - s));
 }
template<> double parabolicFit (const double left, const double center, const double right, double * maxp) inline
Definition at line 43 of file rc_fit.h.
References rfRealEq(), and rmExceptionMacro.
 {
   const bool cl (rfRealEq (center - left, (double) (1.e-15)));
   const bool cr (rfRealEq (center - right, (double) (1.e-15)));
   if ((!(center > left || cl ) && !(center > right || cr )) &&
       (!(center < left || cl ) && !(center < right || cr )))
     rmExceptionMacro (<<" Invalid Data " << left << "," <<
               center << "," << right);
   const double s = left + right;
   const double d = right - left;
   const double c = center + center;
   // case: center is at max
   if (c == s)
     {
       if (maxp) *maxp = center;
       return 0;
     }
   // ymax for the quadratic
   if (maxp) *maxp = (4 * c * c - 4 * c * s + d * d) / (8 * (c - s));
   // position of the max
   return d / (2 * (c - s));
 }
template<> float parabolicFit (const float left, const float center, const float right, float * maxp) inline
Definition at line 74 of file rc_fit.h.
References rfRealEq(), and rmExceptionMacro.
 {
   const bool cl (rfRealEq (center - left, (float) (1.e-10)));
   const bool cr (rfRealEq (center - right, (float) (1.e-10)));
   if ((!(center > left || cl ) && !(center > right || cr )) &&
       (!(center < left || cl ) && !(center < right || cr )))
     rmExceptionMacro (<<" Invalid Data " << left << "," <<
               center << "," << right);
   const float s = left + right;
   const float d = right - left;
   const float c = center + center;
   // case: center is at max
   if (c == s)
     {
       if (maxp) *maxp = center;
       return 0;
     }
   // ymax for the quadratic
   if (maxp) *maxp = (4 * c * c - 4 * c * s + d * d) / (8 * (c - s));
   // position of the max
   return d / (2 * (c - s));
 }
template<class T , class M > void parfit2DR3 (const vector< T > & score, rc2dVector< M > & v) inline
Definition at line 126 of file rc_fit.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rfParfit2DR3().
 {
   M MULTA (0.408248);
   M MULTB (0.816497);
   M a = MULTA * (MULTA * (M) (score[6]) - MULTB * (M) (score[7]) + MULTA * (M) (score[8]) + MULTA * (M) (score[3]) -
           MULTB * (M) (score[4]) + MULTA * (M) (score[5]) + MULTA * (M) (score[0]) - MULTB * (M) (score[1]) +
           MULTA * (M) (score[2]));
   M b = MULTA * (MULTA * (M) (score[6]) + MULTA * (M) (score[7]) + MULTA * (M) (score[8]) - MULTB * (M) (score[3]) -
           MULTB * (M) (score[4]) - MULTB  * (M) (score[5]) + MULTA * (M) (score[0]) + MULTA * (M) (score[1]) +
             MULTA * (M) (score[2]));
   M c = 0.5 * (-0.5 * (M) (score[6]) + 0.5 * (M) (score[8]) + 0.5 * (M) (score[0]) - 0.5 * (M) (score[2]));
   M d = MULTA * (-MULTA * (M) (score[6]) + MULTA * (M) (score[8]) - MULTA * (M) (score[3]) + MULTA * (M) (score[5]) -
           MULTA * (M) (score[0]) + MULTA * (M) (score[2]));
   M e = MULTA * (MULTA * (M) (score[6]) + MULTA * (M) (score[7]) + MULTA * (M) (score[8]) - MULTA * (M) (score[0]) -
           MULTA * (M) (score[1]) - MULTA * (M) (score[2]));
   M f = c * c - 4 * a * b;
   if (f == M(0))
     {
       v = rc2dVector<M> ();
       return;
     }
   v.x((2 * b * d - c * e) / f);
   v.y((2 * a * e - c * d) / f);
   if (v.x() > 1.0 || v.x() < -1.0 || v.y() > 1.0 || v.y() < -1.0)
     v = rc2dVector<M> ();
 }
template<class T , class M > void parfit2DR3 (const T & score11, const T & score12, const T & score13, const T & score21, const T & score22, const T & score23, const T & score31, const T & score32, const T & score33, rc2dVector< M > & v) inline
Definition at line 160 of file rc_fit.h.
References rc2dVector< T >::x(), and rc2dVector< T >::y().
 {
   M MULTA (0.408248);
   M MULTB (0.816497);
   M a = MULTA * (MULTA * score31 - MULTB * score32 + MULTA * score33 + MULTA * score21 -
           MULTB * score22 + MULTA * score23 + MULTA * score11 - MULTB * score12 +
           MULTA * score13);
   M b = MULTA * (MULTA * score31 + MULTA * score32 + MULTA * score33 - MULTB * score21 -
           MULTB * score22 - MULTB  * score23 + MULTA * score11 + MULTA * score12 +
             MULTA * score13);
   M c = 0.5 * (-0.5 * score31 + 0.5 * score33 + 0.5 * score11 - 0.5 * score13);
   M d = MULTA * (-MULTA * score31 + MULTA * score33 - MULTA * score21 + MULTA * score23 -
           MULTA * score11 + MULTA * score13);
   M e = MULTA * (MULTA * score31 + MULTA * score32 + MULTA * score33 - MULTA * score11 -
           MULTA * score12 - MULTA * score13);
   M f = c * c - 4 * a * b;
   if (f == M(0))
     {
       v = rc2dVector<M> ();
       return;
     }
   v.x((2 * b * d - c * e) / f);
   v.y((2 * a * e - c * d) / f);
   if (v.x() > 1.0 || v.x() < -1.0 || v.y() > 1.0 || v.y() < -1.0)
     v = rc2dVector<M> ();
 }
double rfGasDev (int32 & idum)
Definition at line 146 of file rc_units.cpp.
References rfRanOne().
 {
   static int32 iset=0;
   static double gset;
   double fac,rsq,v1,v2;
   if (idum < 0) iset=0;
   if (iset == 0) {
     do {
       v1=2.0*rfRanOne(idum)-1.0;
       v2=2.0*rfRanOne(idum)-1.0;
       rsq=v1*v1+v2*v2;
     } while (rsq >= 1.0 || rsq == 0.0);
     fac=sqrt(-2.0*log(rsq)/rsq);
     gset=v1*fac;
     iset=1;
     return v2*fac;
   } else {
     iset=0;
     return gset;
   }
 }
template<class P > float rfInterpolatePeak (const vector< P > & signal, uint32 index, P * ampP = NULL)
Definition at line 300 of file rc_fit.h.
References NULL, parabolicFit(), and rmExceptionMacro.
Referenced by rcShape::peakDetect1d(), and rf1DPeakDetect().
 {
   float delta, damp, *dampPtr (NULL);
   if (ampP) dampPtr = &damp;
   if (index == (signal.size()-1))  { // Peak is pegged at end
     delta = parabolicFit((float) signal[index-1],
              (float) signal[index], 0.0f, dampPtr);
     if (delta > 0.0)
       rmExceptionMacro (<<" Invalid Data " << (float) signal[index-1] << "," <<
             (float) signal[index]);
   }
   else if (index == 0) { // Peak is pegged at start
     delta = parabolicFit(0.0f, (float) signal[0], (float) signal[1], dampPtr);
     if (delta < 0.0)
       rmExceptionMacro (<<" Invalid Data " <<  (float) signal[0] << "," <<
             (float) signal[1]);
   }
   else { // Interpolate peak location
     delta = parabolicFit((float) signal[ index-1], (float) signal[index],
              (float) signal[index+1], dampPtr);
   }
   if (ampP)
     {
       P amp;
       amp = damp;
       * ((P *) ampP) = amp;
     }
   return index + delta;
 }
template<class T > void rfMomentFit (const vector< T > & first, T & x, T & y) inline
Definition at line 257 of file rc_fit.h.
References rmAssert.
 {
   T sx (0), sy (0);
   rmAssert (first.size() == 9);
   sx += -first[0] + first[2] - first[3] + first[5] - first[6] + first[8];
   sy += -first[0] + first[6] - first[1] + first[7] - first[2] + first[8];
   x = sx / first.size();
   y = sy / first.size();
 }
template<class T > void rfMomentFit (const vector< vector< T > > & space, T & x, T & y) inline
rcMomentFit :Return interpolated positions wrt center of :in the 1D case and top of the search space :in case of the 2D.
Definition at line 275 of file rc_fit.h.
References rmAssert, and space.
 {
   T sx (0), sy (0), mass (0);
   // make sure we are equal sized and non-zero
   uint32 s = space[0].size();
   rmAssert (s);
   for (uint32 j = 0; j < space.size(); j++)
     rmAssert (space[j].size() == s);
   for (uint32 j = 0; j < space.size(); j++)
     for (uint32 i = 0; i < s; i++)
       {
     T val = space[j][i];
     mass += val;
     sx += i * val; sy +=  j * val;
       }
   if (mass > T(0))
     x = sx / mass; y = sy / mass;
 }
double rfParabolicFit (const vector< double > & space) inline
Definition at line 237 of file rc_fit.h.
References parabolicFit().
 {
   double *d (0);
   return parabolicFit ( space[0], space[1], space[2], d);
 }
double rfParabolicFit (const vector< double > & space, double * dmax) inline
Definition at line 244 of file rc_fit.h.
References parabolicFit().
 {
   return parabolicFit ( space[0], space[1], space[2], dmax);
 }
float rfParabolicFit (const vector< float > & space) inline
Definition at line 250 of file rc_fit.h.
References parabolicFit().
 {
   static float *f(0);
   return parabolicFit ( space[0], space[1], space[2], f);
 }
template<class T > T rfParabolicFitNonPeak (const T left, const T center, const T right, T * maxp = NULL) inline
Definition at line 104 of file rc_fit.h.
 {
   const T s = left + right;
   const T d = right - left;
   const T c = center + center;
   // case: center is at max
   if (c == s)
     {
       if (maxp) *maxp = center;
       return 0;
     }
   // ymax for the quadratic
   if (maxp) *maxp = (4 * c * c - 4 * c * s + d * d) / (8 * (c - s));
   // position of the max
   return d / (2 * (c - s));
 }
void rfParfit2DR3 (const vector< double > & score, rc2Dvector & v) inline
Definition at line 203 of file rc_fit.h.
References parfit2DR3().
 {
   return parfit2DR3 (score, v);
 }
void rfParfit2DR3 (const vector< float > & score, rc2Fvector & v) inline
Definition at line 209 of file rc_fit.h.
References parfit2DR3().
 {
   return parfit2DR3 (score, v);
 }
void rfParfit2DR3 (const float & score11, const float & score12, const float & score13, const float & score21, const float & score22, const float & score23, const float & score31, const float & score32, const float & score33, rc2Fvector & v) inline
Definition at line 214 of file rc_fit.h.
References parfit2DR3().
 {
   return parfit2DR3 ( score11,
                score12,
                score13,
                score21,
                score22,
                score23,
                score31,
                score32,
               score33, v);
 }
double rfRanOne (int32 & idum)
Definition at line 115 of file rc_units.cpp.
Referenced by rfGasDev().
 {
   const int32 IA=16807,IM=2147483647,IQ=127773,IR=2836,NTAB=32;
   const int32 NDIV=(1+(IM-1)/NTAB);
   const double EPS=3.0e-16,AM=1.0/IM,RNMX=(1.0-EPS);
   static int32 iy=0;
     static std::vector<int32> iv(NTAB);
   int32 j,k;
   double temp;
   if (idum <= 0 || !iy) {
     if (-idum < 1) idum=1;
     else idum = -idum;
     for (j=NTAB+7;j>=0;j--) {
       k=idum/IQ;
       idum=IA*(idum-k*IQ)-IR*k;
       if (idum < 0) idum += IM;
       if (j < NTAB) iv[j] = idum;
     }
     iy=iv[0];
   }
   k=idum/IQ;
   idum=IA*(idum-k*IQ)-IR*k;
   if (idum < 0) idum += IM;
   j=iy/NDIV;
   iy=iv[j];
   iv[j] = idum;
   if ((temp=AM*iy) > RNMX) return RNMX;
   else return temp;
 }