Visible: include/analysis/rc_filter1d.h File Reference
rc_filter1d.h File Reference
#include <rc_types.h>
#include <vector>
#include <rc_window.h>
#include <rc_fit.h>
Classes
class rc1dPeak< T >
class rcEdgeFilter1DPeak
class rcEdgeFilter1D
Functions
template<class P >
void rf1DPeakDetect (const vector< P > &signal, vector< uint32 > &peakBin, vector< P > &peakLoc, vector< P > &peakVal, const P hysteresisPct, bool DEBUG_PD=false)
template<class S , class D , class T >
void rfCtfDiff1d (deque< S > &src, int32 halfWidth, deque< D > &dst, T &dum, bool direction)
Function Documentation
template<class P > void rf1DPeakDetect (const vector< P > & signal, vector< uint32 > & peakBin, vector< P > & peakLoc, vector< P > & peakVal, const P hysteresisPct, bool DEBUG_PD = false)
Definition at line 50 of file rc_filter1d.h.
References rfInterpolatePeak().
Referenced by calcMusclePeriod(), and rcOptoKineticImage::genFreqImg().
 {
   peakBin.clear();
   peakLoc.clear();
   peakVal.clear();
   if (signal.empty())
     return;
   /* Calculate peaks using hysteresisPct to threshold for true valleys.
    */
   int32 pPeak = 0, pValley = 0, min = 0, max = 0;
   P peakThresh = signal[pPeak]*(1 - hysteresisPct);
   P valleyThresh = signal[pValley]*(1 + hysteresisPct);
   if (DEBUG_PD) printf("signal[%d] = %f peakThresh %f valleyThresh %f\n",
                0, signal[0], peakThresh, valleyThresh);
   for (int32 i = 1; i < (int32)signal.size(); i++) {
     if (DEBUG_PD) printf("signal[%d] = %f", i, signal[i]);
     if ((pPeak >= 0) && signal[i] < peakThresh) {
       // Found peak
       peakBin.push_back((uint32)pPeak);
       P peakValue;
       peakLoc.push_back(rfInterpolatePeak(signal, (uint32)pPeak, &peakValue));
       peakVal.push_back(peakValue);
       if (DEBUG_PD) printf(" Peak (%f) @ %d.", signal[pPeak], pPeak);
       pPeak = -1;
       pValley = i;
       min = max = i;
       valleyThresh = signal[pValley]*(1 + hysteresisPct);
       if (DEBUG_PD)
     printf(" New pPeak %d pValley %d min %d max %d valleyThresh %f.\n",
            pPeak, pValley, min, max, valleyThresh);
     }
     else if (signal[i] < signal[min]) {
       if (pValley >= 0) {
     pValley = i;
     valleyThresh = signal[pValley]*(1 + hysteresisPct);
     if (DEBUG_PD) printf(" New pValley %d valleyThresh %f.",
                  pValley, valleyThresh);
       }
       min = i;
       if (DEBUG_PD) printf(" New min %d.\n", min);
     }
     if ((pValley >= 0) && signal[i] > valleyThresh) {
       // Found valley
       if (DEBUG_PD) printf(" Valley (%f) @ %d.", signal[pValley], pValley);
       pPeak = i;
       pValley = -1;
       min = max = i;
       peakThresh = signal[pPeak]*(1 - hysteresisPct);
       if (DEBUG_PD)
     printf(" New pPeak %d pValley %d min %d max %d peakThresh %f.\n",
            pPeak, pValley, min, max, peakThresh);
     }
     else if (signal[i] > signal[max]) {
       if (pPeak >= 0) {
     pPeak = i;
     peakThresh = signal[pPeak]*(1 - hysteresisPct);
     if (DEBUG_PD) printf(" New pPeak %d peakThresh %f.",
                  pPeak, peakThresh);
       }
       max = i;
       if (DEBUG_PD) printf(" New max %d.\n", max);
     }
   } // End of: for (int32 i = 1; i < signal.size(); i++) {
   if (pPeak >= 0) {
     if (DEBUG_PD) printf("Last Peak (%f) @ %d.\n", signal[pPeak], pPeak);
     peakBin.push_back((uint32)pPeak);
     P peakValue;
     peakLoc.push_back(rfInterpolatePeak(signal, (uint32)pPeak, &peakValue));
     peakVal.push_back(peakValue);
   }
 }
template<class S , class D , class T > void rfCtfDiff1d (deque< S > & src, int32 halfWidth, deque< D > & dst, T & dum, bool direction)
Definition at line 217 of file rc_filter1d.h.
References rfRound(), and rmExceptionMacro.
 {
   int32 kernelWidth = halfWidth * 2 + 1; // one bin of leniency
   if (src.size() < kernelWidth)
     rmExceptionMacro (<< "Ctf Size Error");
   dst.resize (src.size() - kernelWidth + 1);
   int32 i;
   int32 size = dst.size();
   const S* front1ptr = &src[0];
   const S* back1ptr = front1ptr;
   const S* front2ptr = front1ptr;
   const S* back2ptr = front1ptr;
   D* outptr = &dst[0];
   T tmp1;
   D dummy(0);
   int32 rightSize_ (halfWidth);
   int32 leftSize_ (halfWidth);
   if (rightSize_ && leftSize_)
     {
       if (rightSize_ == 1 && leftSize_ == 1)
     {
       if (direction)
         {
           for (i=0; i<size; i++)
         outptr[i] = rfRound((T)back1ptr[i+1] - (T)back1ptr[i], dummy);
         } else
         {
           for (i=0; i<size; i++)
         outptr[i] = rfRound((T)back1ptr[i] - (T)back1ptr[i+1], dummy);
         }
     } else
     {
       tmp1 = 0;
       if (direction) for (i = 0; i < leftSize_; i++)  tmp1 = tmp1 - (T) *front2ptr++;
       else for (i = 0; i < leftSize_; i++)  tmp1 = tmp1 + (T) *front2ptr++;
       front1ptr += leftSize_ + 1;
       back1ptr = front1ptr;
       if (direction) for (i = 0; i < rightSize_; i++)  tmp1 = tmp1 + (T) *front1ptr++;
       else for (i = 0; i < rightSize_; i++)  tmp1 = tmp1 - (T) *front1ptr++;
       *outptr++ = rfRound(tmp1, dummy);
       --size;
       if (direction)
         {
           for (i = 0; i < size; i++)
         {
           tmp1 = tmp1 + (T) front1ptr[i] - (T) back1ptr[i] - (T) front2ptr[i] + (T) back2ptr[i];
           *outptr++ = rfRound(tmp1, dummy);
         }
         } else {
         for (i = 0; i < size; i++)
           {
         tmp1 = tmp1 - (T) front1ptr[i] + (T) back1ptr[i] + (T) front2ptr[i] - (T) back2ptr[i];
         *outptr++ = rfRound(tmp1, dummy);
           }
       }
     }
     }
   else
     {
       tmp1 = 0;
       if (direction)
     {
       for (i = 0; i < rightSize_; i++)  tmp1 += (T) *front1ptr++;
       *outptr++ = rfRound(tmp1, dummy);
       for (i = 0; i < size - 1; i++)
         {
           tmp1 = tmp1 + (T) front1ptr[i] - (T) back1ptr[i];
           outptr[i] = rfRound(tmp1, dummy);
         }
     } else
     {
       for (i = 0; i < rightSize_; i++)  tmp1 -= (T) *front1ptr++;
       *outptr++ = rfRound(tmp1, dummy);
       for (i = 0; i < size - 1; i++)
         {
           tmp1 = tmp1 - (T) front1ptr[i] + (T) back1ptr[i];
           outptr[i] = rfRound(tmp1, dummy);
         }
     }
     }
 }