Visible: include/visual/rc_qtime_capture.h File Reference
rc_qtime_capture.h File Reference
#include <rc_types.h>
#include <rc_framebuf.h>
#include <rc_atomic.h>
#include <rc_gen_capture.h>
Functions
void rfQTVideoCapture (rcSharedMemoryUser &shMem)
Function Documentation
void rfQTVideoCapture (rcSharedMemoryUser & shMem)
Definition at line 1148 of file rc_qtime_capture.cpp.
References rcAcqInfo::acqState, BailErr, DisposeMungData(), InitializeMungData(), InitializeMungData2(), InstallEvenHandlers(), MakeAWindow(), MakeSequenceGrabber(), MakeSequenceGrabChannel(), MungGrabDataProc(), NULL, rcAcqDisabled, and writeAcqInfo().
Referenced by main().
 {
     WindowRef        pMainWindow = NULL;
     SeqGrabComponent seqGrab = 0;
     SGChannel        sgchanVideo = 0;
     Rect             portRect;
     OSErr            err = noErr;
     EnterMovies();
     fprintf(stderr, "made it 1");
     // create the window
     err = MakeAWindow(&pMainWindow);
     BailErr(err);
     fprintf(stderr, "...2");
     GetPortBounds(GetWindowPort(pMainWindow), &portRect);
     fprintf(stderr, "...3");
     // create and initialize the sequence grabber
     seqGrab = MakeSequenceGrabber(pMainWindow);
     BailErr(NULL == seqGrab);
     fprintf(stderr, "...4");
     // create the channel
     err = MakeSequenceGrabChannel(seqGrab, &sgchanVideo, &portRect);
     BailErr(err);
     fprintf(stderr, "...5");
     // initialize our data that's going to be passed around
     pMungData = InitializeMungData(pMainWindow, portRect, seqGrab);
     BailErr(NULL == pMungData);
     fprintf(stderr, "...6");
     // specify a sequence grabber data function
     err = SGSetDataProc(seqGrab, NewSGDataUPP(MungGrabDataProc), (long)pMungData);
     BailErr(err);
     fprintf(stderr, "...7");
     // install carbon event handlers
     err = InstallEvenHandlers(pMungData);
     BailErr(err);
     fprintf(stderr, "...8\n");
     // lights...camera...
     err = SGPrepare(seqGrab, false, true);
     BailErr(err);
     // Now have values available to setup image copy specific values
     err = InitializeMungData2(pMungData, sgchanVideo, &shMem);
     BailErr(err);
     fprintf(stderr, "made it 9");
     // Let peer process know that we are ready to start acquiring frames
     if (!writeAcqInfo(shMem, pMungData->acqInfo, true))
         goto bail2; // Pretty ugly, huh?
     // run the application
     RunApplicationEventLoop();
     fprintf(stderr, "RCQTIME: RETURNED FROM EVENTLOOP\n");
 bail:
     if (err != noErr)
     {
         // Try to notify the peer process that acq process wasn't able to
         // come up.
         //
         rcAcqInfo  acqInfo;
         rcAcqInfo* ip = 0;
         if (pMungData)
             ip = &(pMungData->acqInfo);
         else
         {
             acqInfo.acqState = rcAcqDisabled;
             ip = &acqInfo;
         }
         writeAcqInfo(shMem, *ip, true);
     }
 bail2:
     // clean up
     printf( "\n" );
     if (pMainWindow)
         DisposeWindow(pMainWindow);
     DisposeMungData(pMungData);
     fprintf(stderr, "RCQTIME: DONE\n");
     return;
 }