Visible: include/visual/rc_dcam_capture.h File Reference
rc_dcam_capture.h File Reference
#include <rc_gen_capture.h>
#include <rc_capture.hpp>
Functions
void rfDCAMVideoCapture (rcSharedMemoryUser &shMem)
rcCameraMapper rf_dcam_get_cameras ()
Function Documentation
rcCameraMapper rf_dcam_get_cameras ()
void rfDCAMVideoCapture (rcSharedMemoryUser & shMem)
Definition at line 1399 of file rc_dcam_capture.cpp.
References MungDataRecord::acqInfo, rcAcqInfo::acqState, BailErr, rcSparseHistogram::binsUsed(), rcAcqInfo::cameraInfo, rcAcqInfo::ctrlFlags, didit, DisposeMungData(), endl(), rcSparseHistogram::getArray(), InitializeMungData(), InitializeMungData2(), InstallEventHandlers(), rcMovieFileCamExt::mid(), NULL, rcSparseHistogram::range(), rcAcqDisabled, rcCTRLFLAGS_ERRLIC, rcSparseHistogram::reset(), MungDataRecord::theCameraPtr, and writeAcqInfo().
Referenced by main().
 {
     OSErr            err = noErr;
     OSStatus         status = 0;
     dcamCameraListStruct camera;
     void *theCameraPtr = 0;
 #ifdef DEBUG_INIT
     cerr << "RCDCAM init 1";
 #endif
     // Get list of cameras
     dcamCameraList theCameraList;
     status = ASCDCAMGetListOfCameras(&theCameraList);
     if ( status == -128 ) {
         // No license for this host
         cerr << "RCDCAM: no DCAM license installed for this host" << endl;
         BailErr(status);
     }
     if (status!= 0) {
         cerr << "RCDCAM: ASCDCAMGetListOfCameras error " << status << endl;
         BailErr(status);
     }
     if (theCameraList.numCamerasFound == 0) {
         cerr << "RCDCAM: No camera connected" << endl;
         BailErr(-1);
     }
 #ifdef DEBUG_INIT
     fprintf(stderr, "...2");
 #endif
     // Use first available camera
     camera = theCameraList.theCameras[0];
     // Display camera basic info
     theCameraPtr = ASCDCAMOpenACamera(camera.uniqueID);
     if ( !theCameraPtr ) {
         cerr << "RCDCAM: ASCDCAMOpenACamera failed" << endl;
         BailErr(-1);
     }
 #ifdef DEBUG_INIT
     fprintf(stderr, "...3");
 #endif
     // initialize our data that's going to be passed around
     pMungData = InitializeMungData(theCameraPtr);
     BailErr(NULL == pMungData);
 #ifdef DEBUG_INIT
     fprintf(stderr, "...4");
 #endif
     // install carbon event handlers
     err = InstallEventHandlers(pMungData);
     BailErr(err);
 #ifdef DEBUG_INIT
     fprintf(stderr, "...5\n");
 #endif
     // Now have values available to setup image copy specific values
     err = InitializeMungData2(pMungData, &shMem);
     BailErr(err);
     pMungData->acqInfo.cameraInfo.mid( int32(camera.manufacturerID) );
 #ifdef DEBUG_INIT
     fprintf(stderr, "...6");
 #endif
     // Let peer process know that we are ready to start acquiring frames
     if (!writeAcqInfo(shMem, pMungData->acqInfo, true))
         goto bail2; // Pretty ugly, huh?
 #ifdef DEBUG_INIT
     fprintf(stderr, "...7");
 #endif
     // run the application
     RunApplicationEventLoop();
     //stop the callback..
     ASCDCAMAssignCallback(pMungData->theCameraPtr, NULL,NULL);
     fprintf(stderr, "RCDCAM: RETURNED FROM EVENTLOOP\n");
 #ifdef INTERVAL_LOGGING
     if (sHistogram.binsUsed() > 2) {
         uint32 min, max;
         sHistogram.range(min, max);
         fprintf(stderr, "RCDCAM: Irregular frame intervals, interval range %i-%i ms\n",
                         min, max);
         const rcSparseHistogram::sparseArray& histMap = sHistogram.getArray();
         rcSparseHistogram::sparseArray::const_iterator start = histMap.begin();
         rcSparseHistogram::sparseArray::const_iterator end = histMap.end();
         for ( ; start != end; start++)
             fprintf(stderr, "Interval %d ms Count %d\n", (*start).first,
                             (*start).second);
     }
     sHistogram.reset();
     sHistogramRange = 0;
 #endif
 bail:
     if (err != noErr)
     {
         // Try to notify the peer process that acq process wasn't able to
         // come up.
         //
         rcAcqInfo  acqInfo;
         rcAcqInfo* ip = 0;
         if (pMungData)
             ip = &(pMungData->acqInfo);
         else
         {
             if ( err == -128 ) {
                 // DCAM license error
                 acqInfo.ctrlFlags |= rcCTRLFLAGS_ERRLIC;
             }
             acqInfo.acqState = rcAcqDisabled;
             ip = &acqInfo;
         }
         writeAcqInfo(shMem, *ip, true);
     }
 bail2:
     // clean up
     printf( "\n" );
     DisposeMungData(pMungData);
     pMungData = NULL;
     didit = 0;
     fprintf(stderr, "RCDCAM: DONE\n");
     return;
 }