Visible: src/visual/code/rc_mpeg2grabber.cpp File Reference
rc_mpeg2grabber.cpp File Reference
#include <rc_platform.h>
#include <rc_mpeg2grabber.h>
Macros
#define cRGB(r, g, b) ((0xff << 24) | ((r) << 16) | ((g) << 8) | (b))
Functions
static std::string cCreator ("rcMPEG2Grabber")
static rcMovieFileExpExt generateHeader ()
Macro Definition Documentation
#define cRGB (r, g, b) ((0xff << 24) | ((r) << 16) | ((g) << 8) | (b))
Definition at line 215 of file rc_mpeg2grabber.cpp.
Function Documentation
static std::string cCreator ("rcMPEG2Grabber") static
Referenced by rcMPEG2Grabber::getReifyMovie().
static rcMovieFileExpExt generateHeader () static
Definition at line 259 of file rc_mpeg2grabber.cpp.
References rcMovieFileExpExt::CO2(), rcMovieFileExpExt::imagingMode(), rcMovieFileExpExt::lensMag(), rcMovieFileExpExt::O2(), rcMovieFileExpExt::otherMag(), rcMovieFileExpExt::temperature(), and rcMovieFileExpExt::userName().
Referenced by rcMPEG2Grabber::getReifyMovie().
 {
     // Generate an experiment header
     rcMovieFileExpExt expHdr;
     expHdr.lensMag( 1.0f );
     expHdr.otherMag( 0.0f );
     expHdr.temperature( 21.0f );
     expHdr.CO2( 0.035f );
     expHdr.O2( 21.0f );
     expHdr.userName( "MPEG2Grabber" );
     expHdr.imagingMode( "WhoKnows" );
     return expHdr;
 }