Visible: src/util/code/rc_fixcord.cpp File Reference
rc_fixcord.cpp File Reference
#include <rc_types.h>
Macros
#define DEGREES 1
#define COSCALE 0x11616E8E /* 291597966 = 0.2715717684432241 * 2^30, valid for j>13 */
#define QUARTER (90L << 16)
#define MAXITER 22 /* the resolution of the arctan table */
Typedefs
typedef int32 TFract
Functions
TFract FFracMul (TFract a, TFract b)
static void PseudoRotate (int32 *px, int32 *py, register int32 theta)
static void PseudoPolarize (int32 *argx, int32 *argy)
static int FxPreNorm (int32 *argx, int32 *argy)
void rfFxUnitVec (int32 *cos, int32 *sin, int32 theta)
void rfFxRotate (int32 *argx, int32 *argy, int32 theta)
int32 rfFxAtan2 (int32 x, int32 y)
void rfFxPolarize (int32 *argx, int32 *argy)
Variables
static int32 arctantab []
Macro Definition Documentation
#define COSCALE 0x11616E8E /* 291597966 = 0.2715717684432241 * 2^30, valid for j>13 */
Definition at line 63 of file rc_fixcord.cpp.
Referenced by rfFxPolarize(), rfFxRotate(), and rfFxUnitVec().
#define DEGREES 1
Definition at line 61 of file rc_fixcord.cpp.
#define MAXITER 22 /* the resolution of the arctan table */
Referenced by PseudoPolarize(), and PseudoRotate().
#define QUARTER (90L << 16)
Referenced by PseudoPolarize(), and PseudoRotate().
Typedef Documentation
typedef int32 TFract
Definition at line 96 of file rc_fixcord.cpp.
Function Documentation
int32 FFracMul (TFract a, TFract b) inline
Definition at line 347 of file rc_fixcord.cpp.
Referenced by rfFxPolarize(), and rfFxRotate().
 {
     /* This routine should be written in assembler to calculate the
      * high part of the product, i.e. the product when the operands
      * are considered fractions.
      */
     return((a >> 15) * (b >> 15));
 }
static int FxPreNorm (int32 * argx, int32 * argy) static
Definition at line 217 of file rc_fixcord.cpp.
Referenced by rfFxAtan2(), rfFxPolarize(), and rfFxRotate().
 {
     register int32 x, y;
     int signx, signy;
     register int shiftexp;
     shiftexp = 0;       /* Block normalization exponent */
     signx = signy = 1;
     if ((x = *argx) < 0) {
         x = -x;
         signx = -signx;
     }
     if ((y = *argy) < 0) {
         y = -y;
         signy = -signy;
     }
     /* Prenormalize vector for maximum precision */
     if (x < y) {    /* |y| > |x| */
         while (y < (1 << 27)) {
             x <<= 1;
             y <<= 1;
             shiftexp--;
         }
         while (y > (1 << 28)) {
             x >>= 1;
             y >>= 1;
             shiftexp++;
         }
     }
     else {      /* |x| > |y| */
         while (x < (1 << 27)) {
             x <<= 1;
             y <<= 1;
             shiftexp--;
         }
         while (x > (1 << 28)) {
             x >>= 1;
             y >>= 1;
             shiftexp++;
         }
     }
     *argx = (signx < 0) ? -x : x;
     *argy = (signy < 0) ? -y : y;
     return(shiftexp);
 }
static void PseudoPolarize (int32 * argx, int32 * argy) static
Definition at line 157 of file rc_fixcord.cpp.
References arctantab, MAXITER, and QUARTER.
Referenced by rfFxAtan2(), and rfFxPolarize().
 {
     register int32 theta;
     register int32 yi, i;
     register int32 x, y;
     register int32 *arctanptr;
     x = *argx;
     y = *argy;
     /* Get the vector into the right half plane */
     theta = 0;
     if (x < 0) {
         x = -x;
         y = -y;
         theta = 2 * QUARTER;
     }
     if (y > 0)
         theta = - theta;
     arctanptr = arctantab;
     if (y < 0) {    /* Rotate positive */
         yi = y + (x << 1);
         x  = x - (y << 1);
         y  = yi;
         theta -= *arctanptr++;  /* Subtract angle */
     }
     else {      /* Rotate negative */
         yi = y - (x << 1);
         x  = x + (y << 1);
         y  = yi;
         theta += *arctanptr++;  /* Add angle */
     }
     for (i = 0; i <= MAXITER; i++) {
         if (y < 0) {    /* Rotate positive */
             yi = y + (x >> i);
             x  = x - (y >> i);
             y  = yi;
             theta -= *arctanptr++;
         }
         else {      /* Rotate negative */
             yi = y - (x >> i);
             x  = x + (y >> i);
             y  = yi;
             theta += *arctanptr++;
         }
     }
     *argx = x;
     *argy = theta;
 }
static void PseudoRotate (int32 * px, int32 * py, register int32 theta) static
Definition at line 100 of file rc_fixcord.cpp.
References arctantab, MAXITER, and QUARTER.
Referenced by rfFxRotate(), and rfFxUnitVec().
 {
     register int i;
     register int32 x, y, xtemp;
     register int32 *arctanptr;
     x = *px;
     y = *py;
     /* Get angle between -90 and 90 degrees */
     while (theta < -QUARTER) {
         x = -x;
         y = -y;
         theta += 2 * QUARTER;
     }
     while (theta > QUARTER) {
         x = -x;
         y = -y;
         theta -= 2 * QUARTER;
     }
     /* Initial pseudorotation, with left shift */
     arctanptr = arctantab;
     if (theta < 0) {
         xtemp = x + (y << 1);
         y     = y - (x << 1);
         x     = xtemp;
         theta += *arctanptr++;
     }
     else {
         xtemp = x - (y << 1);
         y     = y + (x << 1);
         x     = xtemp;
         theta -= *arctanptr++;
     }
     /* Subsequent pseudorotations, with right shifts */
     for (i = 0; i <= MAXITER; i++) {
         if (theta < 0) {
             xtemp = x + (y >> i);
             y     = y - (x >> i);
             x     = xtemp;
             theta += *arctanptr++;
         }
         else {
             xtemp = x - (y >> i);
             y     = y + (x >> i);
             x     = xtemp;
             theta -= *arctanptr++;
         }
     }
     *px = x;
     *py = y;
 }
int32 rfFxAtan2 (int32 x, int32 y)
Definition at line 307 of file rc_fixcord.cpp.
References FxPreNorm(), and PseudoPolarize().
 {
     if ((x == 0) && (y == 0))
         return(0);
 #ifndef FASTER
     FxPreNorm(&x, &y);  /* Prenormalize vector for maximum precision */
 #endif FASTER
     PseudoPolarize(&x, &y); /* Convert to polar coordinates */
     return(y);
 }
void rfFxPolarize (int32 * argx, int32 * argy)
Definition at line 319 of file rc_fixcord.cpp.
References COSCALE, FFracMul(), FxPreNorm(), and PseudoPolarize().
Referenced by rcFeature::octants(), and rcFeature::polar().
 {
 #ifndef FASTER
     int shiftexp;
 #endif FASTER
     if ((*argx == 0) && (*argy == 0)) {
         return;
     }
 #ifndef FASTER
     /* Prenormalize vector for maximum precision */
     shiftexp = FxPreNorm(argx, argy);
 #endif FASTER
     /* Perform CORDIC conversion to polar coordinates */
     PseudoPolarize(argx, argy);
     /* Scale radius to undo pseudorotation enlargement factor */
     *argx = FFracMul(*argx, COSCALE);
 #ifndef FASTER
     /* Denormalize radius */
     *argx = (shiftexp < 0) ? (*argx >> -shiftexp) : (*argx << shiftexp);
 #endif FASTER
 }
void rfFxRotate (int32 * argx, int32 * argy, int32 theta)
Definition at line 279 of file rc_fixcord.cpp.
References COSCALE, FFracMul(), FxPreNorm(), and PseudoRotate().
 {
 #ifndef FASTER
     int shiftexp;
 #endif FASTER
     if (((*argx == 0) && (*argy == 0)) || (theta == 0))
         return;
 #ifndef FASTER
     shiftexp = FxPreNorm(argx, argy);  /* Prenormalize vector */
 #endif FASTER
     PseudoRotate(argx, argy, theta);   /* Perform CORDIC pseudorotation */
     *argx = FFracMul(*argx, COSCALE);   /* Compensate for CORDIC enlargement */
     *argy = FFracMul(*argy, COSCALE);
 #ifndef FASTER
     if (shiftexp < 0) {     /* Denormalize vector */
         *argx >>= -shiftexp;
         *argy >>= -shiftexp;
     }
     else {
         *argx <<= shiftexp;
         *argy <<= shiftexp;
     }
 #endif FASTER
 }
void rfFxUnitVec (int32 * cos, int32 * sin, int32 theta)
Definition at line 270 of file rc_fixcord.cpp.
References COSCALE, and PseudoRotate().
 {
     *cos = COSCALE;
     *sin = 0;
     PseudoRotate(cos, sin, theta);
 }
Variable Documentation
int32 arctantab[] static
Initial value:
= {
#define QUARTER
#define MAXITER
    4157273, 2949120, 1740967, 919879, 466945, 234379, 117304, 58666,
    29335, 14668, 7334, 3667, 1833, 917, 458, 229,
    115, 57, 29, 14, 7, 4, 2, 1
}
Definition at line 65 of file rc_fixcord.cpp.
Referenced by PseudoPolarize(), and PseudoRotate().