Visible: src/analysis/code/rc_median.cpp File Reference
rc_median.cpp File Reference
#include <rc_window.h>
#include <rc_ip.h>
Macros
#define rmMedOf3(a, b, c)
#define rmMaxOf3(a, b, c) (rmMax(rmMax(a, b), c))
#define rmMinOf3(a, b, c) (rmMin(rmMin(a, b), c))
Functions
void rfMedian3By3Depth8 (const rcWindow &srcImg, rcWindow &dstImg)
void rfCopyWindowBorder (rcWindow &win, const rcWindow &src)
void rfMedian (const rcWindow &srcImg, rcWindow &dstImg)
Macro Definition Documentation
#define rmMaxOf3 (a, b, c) (rmMax(rmMax(a, b), c))
Definition at line 58 of file rc_median.cpp.
Referenced by _rfRcWindow32to8(), and rfMedian3By3Depth8().
#define rmMedOf3 (a, b, c)
Value:
((a) > (b) ? ((a) < (c) ? (a) : ((b) < (c) ? (c) : (b))) :    \
 ((a) > (c) ? (a) : ((b) < (c) ? (b) : (c))))
Definition at line 54 of file rc_median.cpp.
Referenced by rfMedian3By3Depth8().
#define rmMinOf3 (a, b, c) (rmMin(rmMin(a, b), c))
Definition at line 60 of file rc_median.cpp.
Referenced by rfMedian3By3Depth8().
Function Documentation
void rfCopyWindowBorder (rcWindow & win, const rcWindow & src)
Definition at line 224 of file rc_moreip.cpp.
Referenced by rfMedian().
 {
   const int32 width(win.width());
   const int32 height(win.height());
   rcWindow top (win, 0, 0, width, 1);
   rcWindow dtop (src, 0, 0, width, 1);
   top.copyPixelsFromWindow (dtop);
   rcWindow bot (win, 0, height-1, width, 1);
   rcWindow dbot (src, 0, height-1, width, 1);
   top.copyPixelsFromWindow (dbot);
   rcWindow left (win, 0, 0, 1, height);
   rcWindow dleft (src, 0, 0, 1, height);
   left.copyPixelsFromWindow (dleft);
   rcWindow right (win, width-1, 0, 1, height);
   rcWindow dright (src, width-1, 0, 1, height);
   right.copyPixelsFromWindow (dright);
 }
void rfMedian (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 37 of file rc_median.cpp.
References rcWindow::height(), rcWindow::isBound(), rfCopyWindowBorder(), rfMedian3By3Depth8(), and rcWindow::width().
Referenced by rcVisualFunction::beatProcess(), rcMuscleSegmenter::filterBySize(), rcEngineImpl::groupStatistics(), rcKinetoscope::keepPopulationMeasure(), and rcMutualInfoGrouping::rcMutualInfoGrouping().
 {
    assert (srcImg.isBound());
    assert (dstImg.isBound());
    assert (srcImg.width() == (dstImg.width()));
    assert (srcImg.height() == (dstImg.height()));
    rfCopyWindowBorder(dstImg, srcImg);
    rcWindow dwin (dstImg, 1, 1, dstImg.width() - 2, dstImg.height() - 2);
    rfMedian3By3Depth8(srcImg, dwin);
 }
void rfMedian3By3Depth8 (const rcWindow & srcImg, rcWindow & dstImg)
Definition at line 62 of file rc_median.cpp.
References rcWindow::height(), rcWindow::isBound(), rmMaxOf3, rmMedOf3, rmMinOf3, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
Referenced by rfMedian().
 {
    const uint8  *srcPtr1, *srcPtr2, *srcRowBase;
    uint8        *dstPtr, *dstRowBase;
    uint8         pelFIFO[9], maxOfMin, minOfMax, medOfMed;
    uint8         colMin[3], colMax[3], colMed[3];
    int             i, j, k, m, a, b, c;
    assert (srcImg.isBound());
    assert (dstImg.isBound());
    assert (srcImg.width() == (dstImg.width() + 2));
    assert (srcImg.height() == (dstImg.height() + 2));
    int srcRUC = srcImg.rowUpdate();
    int dstRUC = dstImg.rowUpdate();
    int rowIter = srcImg.height() - 2;
    int colIter = srcImg.width() - 2 - 1;
    srcRowBase = srcImg.rowPointer(0);
    dstRowBase = dstImg.rowPointer(0);
    for(i = rowIter; i;
        i--, srcRowBase += srcRUC, dstRowBase += dstRUC)
    {
       dstPtr = dstRowBase;
       // Initialize FIFO for current row pass
       srcPtr1 = srcRowBase;
       for(j = 3, k = 0; j; j--, srcPtr1++)
       {
          srcPtr2 = srcPtr1;
          for(m = 3; m; m--, srcPtr2 += srcRUC, k++)
             pelFIFO[k] = *srcPtr2;
       }
       // Initalize column miniums
       colMin[0] = rmMinOf3(pelFIFO[0], pelFIFO[1], pelFIFO[2]);
       colMin[1] = rmMinOf3(pelFIFO[3], pelFIFO[4], pelFIFO[5]);
       colMin[2] = rmMinOf3(pelFIFO[6], pelFIFO[7], pelFIFO[8]);
       // Initalize column maximums
       colMax[0] = rmMaxOf3(pelFIFO[0], pelFIFO[1], pelFIFO[2]);
       colMax[1] = rmMaxOf3(pelFIFO[3], pelFIFO[4], pelFIFO[5]);
       colMax[2] = rmMaxOf3(pelFIFO[6], pelFIFO[7], pelFIFO[8]);
       // Initalize column medians
       colMed[0] = rmMedOf3(pelFIFO[0], pelFIFO[1], pelFIFO[2]);
       colMed[1] = rmMedOf3(pelFIFO[3], pelFIFO[4], pelFIFO[5]);
       colMed[2] = rmMedOf3(pelFIFO[6], pelFIFO[7], pelFIFO[8]);
       // Compute column partial orderings
       maxOfMin = rmMaxOf3(colMin[0], colMin[1], colMin[2]);
       minOfMax = rmMinOf3(colMax[0], colMax[1], colMax[2]);
       medOfMed = rmMedOf3(colMed[0], colMed[1], colMed[2]);
       // Compute final median for inital row destination
       *dstPtr = rmMedOf3(maxOfMin, minOfMax, medOfMed);
       for(j = colIter, dstPtr++, m = 0, k = 0;
           j; j--, dstPtr++, srcPtr1++, k += 3, m++)
       {
          if(m == 3)
             m = k = 0;
          // Update current column buffers
          srcPtr2 = srcPtr1;
          a = *srcPtr2;
          srcPtr2 += srcRUC;
          b = *srcPtr2;
          srcPtr2 += srcRUC;
          c = *srcPtr2;
          colMin[m] = rmMinOf3(a, b, c);
          colMax[m] = rmMaxOf3(a, b, c);
          colMed[m] = rmMedOf3(a, b, c);
          // Compute column partial orderings
          maxOfMin = rmMaxOf3(colMin[0], colMin[1], colMin[2]);
          minOfMax = rmMinOf3(colMax[0], colMax[1], colMax[2]);
          medOfMed = rmMedOf3(colMed[0], colMed[1], colMed[2]);
          // Find median 3x3 as the median of the partial min, max, med
          *dstPtr = rmMedOf3(maxOfMin, minOfMax, medOfMed);
       }
    }
 }