Visible: src/visible/src/rc_writermanager.cpp File Reference
rc_writermanager.cpp File Reference
#include <rc_writermanager.h>
#include <rc_xml.h>
#include "rc_writermanagerimpl.h"
Variables
static const rcWriterInfo sWriterInfoArray []
static const rcWriterMapper sWriterMapper (sWriterInfoArray, rmDim(sWriterInfoArray))
Variable Documentation
const rcWriterInfo sWriterInfoArray[] static
Definition at line 21 of file rc_writermanager.cpp.
const rcWriterMapper sWriterMapper(sWriterInfoArray, rmDim(sWriterInfoArray)) static
Referenced by rcWriterManager::createGraphicsWriter(), rcWriterManager::createPositionWriter(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), rcWriterManager::createWriter(), rcWriterManager::nameType(), rcWriterManager::tagType(), rcWriterManager::writerName(), and rcWriterManager::writerTag().