Visible: include/visual/rc_fill.h File Reference
rc_fill.h File Reference
#include <rc_window.h>
Functions
void rc_fill_poly (rcWindow &image, int32 num_pts, double *coords, uint32 colors)
Function Documentation
void rc_fill_poly (rcWindow & image, int32 num_pts, double * coords, uint32 colors)
Definition at line 1049 of file rc_fill.cpp.
References bndry_fract(), CLAMP, clip_polygon_to_pel(), color(), coords_to_poly(), DIAG_ENTRY, DIAG_FILL, diag_flags, DIAG_POLY_CLIP, dump_poly(), poly_segment::dx, poly_segment::dy, FALSE, poly_segment::first_col, rcWindow::getPixel(), rcWindow::height(), poly_segment::ix, poly_segment::iy, poly_segment::last_col, LEFT_BNDRY, poly_segment::max_col, poly_segment::max_row, MAX_STK_SEGS, poly_segment::min_col, poly_segment::min_row, poly_segment::next, NULL, poly_segment::old_vert_int, polygon_area(), rcWindow::rowPointer(), rcWindow::rowUpdate(), rcWindow::setPixel(), poly_segment::slope, SLOPE_HORZ, SLOPE_NEG, SLOPE_POS, SLOPE_VERT, TRUE, poly_segment::type, poly_segment::use_me, poly_segment::vertex_in_image, rcWindow::width(), poly_segment::x, poly_segment::x1, poly_segment::x2, poly_segment::y, poly_segment::y1, poly_segment::y1_start, and poly_segment::y2.
Referenced by rcFillPolygon().
 {
     polygon_a poly;     /* polygon to fill */
     polygon_a new_poly;     /* 2nd, clipped, polygon */
     poly_segment _stk_segs[MAX_STK_SEGS];   /* array of segments on stack */
     poly_segment *segs = _stk_segs; /* array of segments */
     poly_segment _new_stk_segs[MAX_STK_SEGS + 4];   /* array of segments on
                                stack */
     poly_segment *new_segs = _new_stk_segs; /* array of segments */
     int32 num_rows;     /* number of rows containing rectangle */
     int32 num_cols;     /* number of columns containing rect */
     int32 row_incr;     /* address offset between rows */
     uint8 *row;     /* pel row pointer */
     uint8 *pel;     /* pel row pointer */
     int32 row_no;           /* loop index */
     int32 col_no;           /* loop index */
     uint8 fgnd;     /* foreground color */
     uint8 color;    /* pel color to set */
     double bgnd_fract;      /* fraction of background color to use */
     int32 x;            /* current pel X coord */
     int32 y;            /* current pel Y coord */
     double f_x;         /* x as a double */
     double f_y;         /* y as a double */
     int32 col_shift;        /* amount column # is shifted */
     int32 clamped_col1;     /* col1 clamped to image limits */
     poly_segment *seg;      /* ptr to current segment */
     int32 n;            /* loop index */
     int32 max_row;      /* maximum row */
     int32 max_col;      /* maximum column */
     /* Validate input: */
     assert(num_pts >= 3);
     if (num_pts > MAX_STK_SEGS) {
     segs = (poly_segment *) malloc ((int32) (num_pts * sizeof (*segs)));
     new_segs = (poly_segment *) malloc ((int32) ((num_pts + 4)
                               * sizeof (*new_segs)));
     }
     /* Build the polygon: */
     memset ((char *) new_poly, 1, sizeof (new_poly));
     new_poly->max_segs = num_pts + 4;
     max_row = image.height() - 1;
     max_col = image.width() - 1;
     poly->max_segs = num_pts;
     poly->segs = segs;
     coords_to_poly (num_pts, coords, poly, max_row, max_col);
     /* If the polygon is completely outside the image, exit now: */
     if (poly->min_col > max_col
         || poly->max_col < 0
         || poly->min_row > max_row
         || poly->max_row < 0)
     return;
     /* Clamp the polygon limits to image boundaries: */
     CLAMP (poly->min_row, 0, max_row);
     CLAMP (poly->max_row, 0, max_row);
     CLAMP (poly->min_col, 0, max_col);
     CLAMP (poly->max_col, 0, max_col);
     num_rows = poly->max_row - poly->min_row + 1;
     num_cols = poly->max_col - poly->min_col + 1;
     /* Extract colors: */
     fgnd = (uint8) (colors & 0xFF);
 #if DEBUG
     diag_flags = ((colors >> 8) & 0xFF);
 #endif
     /* Remember the intensity values at each vertex. This is to avoid
        time-consuming checking in inner loops; instead we blow away the
        values, and blend later, using the cached original values. */
     for (n = poly->num_segs, seg = poly->segs;
         n > 0;
         --n, seg = seg->next) {
     if (seg->vertex_in_image)
         seg->old_vert_int = image.getPixel (seg->ix, seg->iy);
     }
     /* Determine the X coordinate of the intersection of each segment with
        the line <y=min_row> and the Y coordinate of the intersection of the
        segment with the line <x=min_col>. */
     for (n = poly->num_segs, seg = poly->segs; n > 0; --n, seg = seg->next) {
     switch (seg->slope) {
     case SLOPE_HORZ:
         seg->x2 = poly->min_col;
         seg->y1_start = seg->y;
         break;
     case SLOPE_VERT:
         seg->x2 = seg->x;
         seg->y1_start = poly->min_row;
         break;
     default:
         seg->x2 = seg->x + (poly->min_row - seg->y) * seg->dx;
         seg->y1_start = seg->y + (poly->min_col - seg->x) * seg->dy;
         break;
     }
     }
 #if DEBUG
     if (diag_flags & DIAG_ENTRY) {
     dump_poly (poly);
     }
 #endif
     /* Loop through rows: */
 #if DEBUG
     if (diag_flags & DIAG_FILL) {
     printf ("\n%3s: %2s %2s %2s %3s %3s %3s %3s | %3s: %2s %6s %6s %6s %6s %2s %6s %1s\n\n",
         "row", "SB", "LB", "RB", "C1", "C2", "C3", "C4", "col", "nm", "x1", "x2", "y1", "y2", "it", "area", "I");
     }
 #endif
     row_incr = image.rowUpdate ();
     for (row_no = num_rows, y = poly->min_row,
        row = image.rowPointer(y);
      row_no > 0;
      --row_no, y += 1, row += row_incr) {
     /* Initialize the row loop state: */
     poly->left_bndry = NULL;
     poly->right_bndry = NULL;
     poly->single_bndry = TRUE;
     poly->col1 = poly->col3 = INT_MAX;
     poly->col2 = poly->col4 = INT_MIN;
     /* Update the state for each boundary segment. This stuff is used to
        compute X and Y intercepts, and limits for speed: */
     for (n = poly->num_segs, seg = poly->segs;
         n > 0;
         --n, seg = seg->next) {
         int32 this_col; /* utility column number */
         /* Compute the starting X and Y intercepts. Do the minimum
            updates required for all segments. Later we do more for the
            segments actually in use.  */
         seg->x1 = seg->x2;
         seg->x2 += seg->dx;
         seg->y2 = seg->y1_start;
         /* Check if this segment crosses the current row. If not, ignore
            it: */
         if (seg->max_row < y || seg->min_row > y) {
         seg->use_me = FALSE;
         continue;
         }
         seg->use_me = TRUE;
         switch (seg->slope) {
         case SLOPE_VERT:
         seg->min_col = seg->max_col = seg->first_col;
         break;
         case SLOPE_HORZ:
         poly->single_bndry = FALSE;
         seg->min_col = seg->first_col;
         seg->max_col = seg->last_col;
         break;
         case SLOPE_POS:
         this_col = (int32) seg->x1;
         seg->min_col = max (this_col, seg->first_col);
         this_col = (int32) seg->x2;
         seg->max_col = min (this_col, seg->last_col);
         break;
         case SLOPE_NEG:
         this_col = (int32) seg->x2;
         seg->min_col = max (this_col, seg->first_col);
         this_col = (int32) seg->x1;
         seg->max_col = min (this_col, seg->last_col);
         break;
         }
         /* Update boundaries and limits. */
         if (seg->type & LEFT_BNDRY) {
         if (seg->min_col < poly->col1)
             poly->col1 = seg->min_col;
         if (seg->max_col > poly->col2)
             poly->col2 = seg->max_col;
         if (poly->single_bndry) {
             if (poly->left_bndry == NULL)
             poly->left_bndry = seg;
             else
             poly->single_bndry = FALSE;
         }
         } else {
         if (seg->min_col < poly->col3)
             poly->col3 = seg->min_col;
         if (seg->max_col > poly->col4)
             poly->col4 = seg->max_col;
         if (poly->single_bndry) {
             if (poly->right_bndry == NULL)
             poly->right_bndry = seg;
             else
             poly->single_bndry = FALSE;
         }
         }
     }
     /* Sanity check: make sure we have left and right boundary segments
        if single_bndry is still set: */
     if (poly->single_bndry
         && (poly->left_bndry == NULL || poly->right_bndry == NULL)) {
         printf ("Error! single boundary without both boundaries!\n");
         poly->single_bndry = FALSE;
     }
     /* Compensate Y intercept if not starting at leftmost column: */
     col_shift = poly->col1 - poly->min_col;
     if (col_shift > 0) {
         for (n = poly->num_segs, seg = poly->segs;
             n > 0;
             --n, seg = seg->next) {
         seg->y2 += col_shift * seg->dy;
         }
     }
     /* If this row is outside the image, go to next row: */
     if (poly->col4 < 0 || poly->col1 > max_col)
         continue;
 #if DEBUG
     if (diag_flags & DIAG_FILL) {
         printf ("%3d: %2d %2s %2s %3d %3d %3d %3d\n",
             y, poly->single_bndry,
             poly->single_bndry ? poly->left_bndry->name : "--",
             poly->single_bndry ? poly->right_bndry->name : "--",
             poly->col1, poly->col2, poly->col3, poly->col4);
     }
 #endif
     /* Loop through pels on this row: */
     clamped_col1 = max (0, poly->col1);
     for (x = clamped_col1, pel = row + x,
         col_no = min (max_col, poly->col4) - clamped_col1 + 1;
         col_no > 0;
         --col_no, ++pel, ++x) {
         /* Compute the Y intercepts of the segments: */
         for (n = poly->num_segs, seg = poly->segs;
             n > 0;
             --n, seg = seg->next) {
         seg->y1 = seg->y2;
         seg->y2 += seg->dy;
         }
         /* Check if this pel is completely inside the rectangle. If so,
            set it to the foreground color and continue with the next pel.
            For speed, run through all the interior pels in one inner
            loop, saving add/accumulates. */
         if (x > poly->col2 && x < poly->col3) {
         int32 ni_cols_m1;   /* # interior cols less 1 */
         int32 n1;       /* loop index */
         ni_cols_m1 = poly->col3 - poly->col2 - 2;
         for (n1 = ni_cols_m1; n1 > 0; --n1, --col_no, ++pel, ++x) {
             *pel = fgnd;
         }
         /* We're on the last interior pel. Set it, fix up the Y
            intercepts, and continue: */
         if (ni_cols_m1 > 0) {
             double f = ni_cols_m1;  /* convert to double only
                            once */
             for (n1 = poly->num_segs, seg = poly->segs;
                 n1 > 0;
                 --n1, seg = seg->next) {
             seg->y2 += f * seg->dy;
             }
         }
         *pel = fgnd;
         continue;
         }
         /* This pixel is cut by one of the rectangle boundaries. */
         /* Compute the fraction of the pixel in background, and the
            resulting color. */
         f_x = x;
         f_y = y;
         if (poly->single_bndry) {
         bgnd_fract = bndry_fract (poly->left_bndry, x, f_x, f_y)
             + bndry_fract (poly->right_bndry, x, f_x, f_y);
         } else {
         bgnd_fract = 0.0;
         for (n = poly->num_segs, seg = poly->segs;
             n > 0;
             --n, seg = seg->next) {
             if (seg->use_me)
             bgnd_fract += bndry_fract (seg, x, f_x, f_y);
         }
         }
         /* Clamp the fraction to be in the range 0 to 1, just in case.
            This can happen if the pel contains two or more segments
            intersecting at acute angles. In this case, the color chosen
            is inaccurate. We fix this later by individually setting all
            pels containing vertices. */
         if (bgnd_fract < 0.0)
         bgnd_fract = 0.0;
         else if (bgnd_fract > 1.0)
         bgnd_fract = 1.0;
 #if DEBUG
         if (diag_flags & DIAG_FILL) {
         printf ("%3d: %26s %3d: %33s %6.3f\n",
             y, "", x, "", bgnd_fract);
         }
 #endif
         /* If the pel is completely outside the polygon, don't set the
            color: */
         if (bgnd_fract > 0.998)
         continue;
         /* The pel is partially or completely inside the polygon. Set the
            color: */
         color = (uint8) (fgnd - bgnd_fract * (fgnd - *pel) + 0.5);
         *pel = color;
     }
     }
     /* The above algorithm does not work correctly for pels containing a
        corner point. We do these explicitly here: */
 #if DEBUG
     if (diag_flags & DIAG_POLY_CLIP) {
     printf ("\nPOLYGON VERTEX PEL CLIPPING:\n\n");
     }
 #endif
     for (n = poly->num_segs, seg = poly->segs;
         n > 0;
         --n, seg = seg->next) {
     double fgnd_fract;  /* pel fraction that is foreground */
     /* Clear out space for the resulting polygon: */
     memset ((char *) new_segs, 1, sizeof (new_segs));
     new_poly->segs = new_segs;
     /* Compute intersecting polygon and its area for each corner pixel in
        turn: */
     poly->segs = seg;
     if (!seg->vertex_in_image)
         continue;
     f_x = seg->ix;
     f_y = seg->iy;
     clip_polygon_to_pel (poly, f_x, f_y, new_poly);
     fgnd_fract = fabs (polygon_area (new_poly));
 #if DEBUG
     if (diag_flags & DIAG_POLY_CLIP) {
         printf ("Polygon clipped at pel %d %d:\n", seg->ix, seg->iy);
         dump_poly (new_poly);
         printf ("  area @ %d %d = %6.2f\n", seg->ix, seg->iy, fgnd_fract);
     }
 #endif
     if (fgnd_fract < 0.0)
         fgnd_fract = 0.0;
     else if (fgnd_fract > 1.0)
         fgnd_fract = 1.0;
     if (fgnd_fract < 0.002)
         continue;
     color = (uint8) (seg->old_vert_int
                + fgnd_fract * (fgnd - seg->old_vert_int) + 0.5);
     image.setPixel (seg->ix, seg->iy, color);
     }
     /* Clean up and return: */
     if (segs && segs != _stk_segs)
     free (segs);
     if (new_segs && new_segs != _new_stk_segs)
     free (new_segs);
 }