Visible: include/util/rc_stlplus.h File Reference
rc_stlplus.h File Reference
#include <iomanip>
#include <vector>
#include <list>
#include <deque>
#include <iostream>
#include <iterator>
#include <rc_types.h>
#include <sstream>
#include <file_system.hpp>
Classes
class rcRingContainer< T >
class rcRingContainer< T >::iterator
Macros
#define fileokandwritable(a)
#define fileokandreadable(a)
#define dirokandwritable(a)
#define dirokandreadable(a)
Functions
template<typename Array >
double vectorSum (Array a, long count)
template<typename ForwardIter , typename OutputIter , typename UnaryPred >
OutputIter copy_if (ForwardIter begin, ForwardIter end, OutputIter dest, UnaryPred f)
bool rfNocaseEqual (const std::string &s1, const std::string &s2)
template<class T >
std::string rfToString (const T &val)
template<class T >
void rfPRINT_STL_ELEMENTS (const T &coll, const char *optcstr="")
template<class Storable >
ostream & operator<< (ostream &os, const vector< Storable > &v)
template<class Storable >
ostream & operator<< (ostream &os, const deque< Storable > &v)
template<class Storable >
ostream & operator<< (ostream &os, const list< Storable > &v)
Macro Definition Documentation
#define dirokandreadable (a)
Value:
(! ((a).empty() || ! folder_exists ((a)) || \
! folder_readable ((a)) || ! is_full_path ((a))))
Definition at line 70 of file rc_stlplus.h.
#define dirokandwritable (a)
Value:
(! ((a).empty() || ! folder_exists ((a)) || \
! folder_writable ((a)) || ! is_full_path ((a))))
Definition at line 67 of file rc_stlplus.h.
#define fileokandreadable (a)
Value:
(! ((a).empty() || ! is_present ((a)) || \
! is_file ((a)) || ! file_readable ((a)) || \
! is_full_path ((a))))
Definition at line 63 of file rc_stlplus.h.
#define fileokandwritable (a)
Value:
(! ((a).empty() || ! is_present ((a)) || \
! is_file ((a)) || ! file_writable ((a)) || \
! is_full_path ((a))))
Definition at line 59 of file rc_stlplus.h.
Function Documentation
template<typename ForwardIter , typename OutputIter , typename UnaryPred > OutputIter copy_if (ForwardIter begin, ForwardIter end, OutputIter dest, UnaryPred f)
Definition at line 85 of file rc_stlplus.h.
{
   while(begin != end) {
     if(f(*begin))
       *dest++ = *begin;
     begin++;
   }
   return dest;
 }
template<class Storable > ostream& operator<< (ostream & os, const vector< Storable > & v)
Definition at line 118 of file rc_stlplus.h.
 {
   os.setf (ios::fixed);
   os << setprecision (7);
   os << "{ ";
   // These typename definitions silence gcc compiler warnings
   typedef typename vector<Storable>::const_iterator const_iterator;
   const_iterator p, q;
   int32 i (0);
   q = v.end() - 1;
   for( p = v.begin(); p < q; p++, i++)
     os << "{" << i << "," << *p << "}" << ',';
   os << "{" << i << "," << *q << "}" << '}';
   return os;
 }
template<class Storable > ostream& operator<< (ostream & os, const deque< Storable > & v)
Definition at line 137 of file rc_stlplus.h.
 {
   os.setf (ios::fixed);
   os << setprecision (12);
   // These typename definitions silence gcc compiler warnings
   typedef typename deque<Storable>::const_iterator const_iterator;
   const_iterator p, q;
   int32 i (0);
   q = v.end() - 1;
   for( p = v.begin(); p <= q; p++, i++)
   {
       os << *p;
       if (p < q) os << ",";
   }
   return os;
 }
template<class Storable > ostream& operator<< (ostream & os, const list< Storable > & v)
Definition at line 157 of file rc_stlplus.h.
 {
   os << "{ ";
   // These typename definitions silence gcc compiler warnings
   typedef typename list<Storable>::const_iterator const_iterator;
   const_iterator p;
   for( p = v.begin(); p != v.end(); p++)
     os << *p << ' ';
   os << "}";
   return os;
 }
bool rfNocaseEqual (const std::string & s1, const std::string & s2)
Definition at line 19 of file rc_stlplus.cpp.
References nocase_compare().
 {
     return equal (s1.begin (), s1.end (), s2.begin (), nocase_compare);
 }
template<class T > void rfPRINT_STL_ELEMENTS (const T & coll, const char * optcstr = "") inline
Definition at line 107 of file rc_stlplus.h.
References endl().
Referenced by rcKinetoscope::associate().
 {
   typename T::const_iterator pos;
   std::cout << optcstr;
   for (pos=coll.begin(); pos !=coll.end(); ++pos)
     std::cout << *pos << " ";
   std::cout << std::endl;
 }
template<class T > std::string rfToString (const T & val)
Definition at line 99 of file rc_stlplus.h.
Referenced by rcEngineImpl::focusScript(), and rcEngineImpl::makeTmpName().
 {
     std::ostringstream strm;
     strm << val;
     return strm.str();
 }
template<typename Array > double vectorSum (Array a, long count)
Definition at line 75 of file rc_stlplus.h.
References count().
                                       { // Array can be a pointer or an iterator
   double sum = 0.0;
   for (long i = 0; i<count; ++i)
     sum += a[i];
   return sum;
 }