Visible: src/visual/code/rc_window.cpp File Reference
rc_window.cpp File Reference
#include <rc_window.h>
#include <rc_videocache.h>
#include <sys/param.h>
#include <rc_macro.h>
#include <rc_qtime.h>
#include <rc_tiff.h>
#include <tiff.h>
#include <rc_systeminfo.h>
Macros
#define MASKEDPIXELCOMPARE(depth, pixelTypePtr, maskTypePtr)
#define PIXELEQUAL(depth, pixelTypePtr, Epsilon)
#define PIXELCOMPARE(depth, pixelTypePtr)
#define PIXELCOMPAREVERBOSE(depth, pixelTypePtr)
#define SETPIXELBORDER(depth, pixelType)
Functions
ostream & operator<< (ostream &o, const rcWindow &w)
template<class T >
void rf_SetWindowBorder (rcWindow &win, T val)
void rfSetWindowBorder (rcWindow &win, double val)
Macro Definition Documentation
#define MASKEDPIXELCOMPARE (depth, pixelTypePtr, maskTypePtr)
Value:
case depth:                         \
    {\
      int32 w = width();\
      int32 h = height();\
      for (int32 y = 0 ; y < h ; y++)\
    {\
      const pixelTypePtr pSrc1 = (pixelTypePtr) rowPointer(y);  \
      const pixelTypePtr pOther = (pixelTypePtr) other.rowPointer(y); \
      const maskTypePtr pMask = (maskTypePtr) mask.rowPointer(y);   \
      for (int32 x = 0; x < w; x++, pMask++,pSrc1++, pOther++) \
        {                                \
          if (*pMask) continue;                  \
          if (!(*pSrc1 == *pOther)) \
        {                       \
          cerr << x << "," << y << ":" << getPixel(x,y) << "=" << other.getPixel(x,y) << endl; \
          return 0;                     \
        }                           \
        }\
    }\
      return 1;\
    }
Definition at line 781 of file rc_window.cpp.
Referenced by rcWindow::contentMaskCompare().
#define PIXELCOMPARE (depth, pixelTypePtr)
Value:
case depth:             \
    {\
      int32 w = width();\
      int32 h = height();\
      for (int32 y = 0 ; y < h ; y++)\
    {\
      const pixelTypePtr pSrc1 = (pixelTypePtr) rowPointer(y);  \
      const pixelTypePtr pOther = (pixelTypePtr) other.rowPointer(y); \
      int32 x = w;\
      while (x--)\
        {\
          if (!(*pSrc1++ == *pOther++))\
        return 0;\
        }\
    }\
      return 1;\
    }
Definition at line 824 of file rc_window.cpp.
Referenced by rcWindow::contentCompare().
#define PIXELCOMPAREVERBOSE (depth, pixelTypePtr)
Value:
case depth:             \
    {\
        int32 w = width();\
        int32 h = height();\
        for (int32 y = 0 ; y < h ; y++)\
    {\
        const pixelTypePtr pSrc1 = (pixelTypePtr) rowPointer(y);    \
        const pixelTypePtr pOther = (pixelTypePtr) other.rowPointer(y); \
        int32 x = w;\
        while (x--)\
        {\
            if (!(*pSrc1++ == *pOther++))\
            {\
                cerr << "[" << x - 1 << "," << y << "]: " << pSrc1[-1] << endl;\
                return 0;\
                }\
            }\
        }\
        return 1;\
    }
Definition at line 843 of file rc_window.cpp.
Referenced by rcWindow::contentCompare().
#define PIXELEQUAL (depth, pixelTypePtr, Epsilon)
Value:
case depth:             \
    {\
      int32 w = width();\
      int32 h = height();\
      for (int32 y = 0 ; y < h ; y++)\
    {\
      const pixelTypePtr pSrc1 = (pixelTypePtr) rowPointer(y);  \
      const pixelTypePtr pOther = (pixelTypePtr) other.rowPointer(y); \
      int32 x = w;\
      while (x--)\
        {\
          if (!rfRealEq (*pSrc1++,*pOther++,Epsilon))   \
        {cerr << x << "," << y << " " << pSrc1[-1] << " ?? " << pOther[-1] << endl;\
          return 0;}                        \
        }\
    }\
      return 1;\
    }
Definition at line 804 of file rc_window.cpp.
Referenced by rcWindow::contentCompare().
#define SETPIXELBORDER (depth, pixelType)
Value:
case depth:\
      rf_SetWindowBorder (win, (pixelType) val);\
      return
Definition at line 944 of file rc_window.cpp.
Referenced by rfSetWindowBorder().
Function Documentation
ostream& operator<< (ostream & o, const rcWindow & w)
Definition at line 674 of file rc_window.cpp.
References rcWindow::depth(), endl(), rcWindow::getDoublePixel(), rcWindow::getPixel(), rcWindow::height(), rcWindow::rowUpdate(), and rcWindow::width().
 {
   o << "Size:      " << w.width() << "," << w.height() << endl;
   o << "RowUpdate: " << w.rowUpdate() << endl;
   for (int32 j = 0; j < w.height(); j++)
     {
       o << "[" << setw (3) << j << "]";
       for (int32 i = 0; i < w.width(); i++)
     {
       if (w.depth() != 8)
         o <<  setw(3) << (int32) (w.getPixel (i, j));
       else o <<   fixed << setprecision(2) << w.getDoublePixel (i, j);
     }
       o << endl;
     }
   return o;
 }
template<class T > void rf_SetWindowBorder (rcWindow & win, T val)
Definition at line 928 of file rc_window.cpp.
References rcWindow::height(), rcWindow::rowPointer(), rcWindow::set(), and rcWindow::width().
Referenced by rfSetWindowBorder().
 {
   const int32 width(win.width());
   const int32 height(win.height());
   rcWindow top (win, 0, 0, width, 1);
   rcWindow bot (win, 0, height-1, width, 1);
   top.set ((double) val);
   bot.set ((double) val);
   for(int32 i = 1; i < height - 1; i++)
     {
       T *p = (T*) win.rowPointer (i);
       *p = val;
       *(p + width - 1) = val;
     }
 }
void rfSetWindowBorder (rcWindow & win, double val)
Definition at line 949 of file rc_window.cpp.
References rcWindow::depth(), rcWindow::isD32Float(), rcPixel16, rcPixel32, rcPixel8, rcPixelDouble, rf_SetWindowBorder(), rmExceptionMacro, and SETPIXELBORDER.
 {
   switch (win.depth())
     {
       SETPIXELBORDER(rcPixel8,uint8);
       SETPIXELBORDER(rcPixel16,uint16);
       SETPIXELBORDER(rcPixelDouble,double);
     case rcPixel32:
       if (!win.isD32Float())
     rf_SetWindowBorder (win, (uint32) val);
       else
     rf_SetWindowBorder (win, (float) val);
       return;
     default:
       rmExceptionMacro(<< "IP Window::not implemented");
     }
 }