Visible: include/visual/rc_imageprocessing.h File Reference
rc_imageprocessing.h File Reference
#include <rc_window.h>
Functions
void rcGenHalfRes (char *src, char *dest, uint32 widthInPixels, uint32 heightInLines, uint32 srcRowUpdate, bool invert)
void rfAndImage (const rcWindow &srcWin, const rcWindow &maskWin, rcWindow &destWin)
void rfTemporalMedian (const vector< rcWindow > &srcWin, rcWindow &destWin)
Function Documentation
void rcGenHalfRes (char * src, char * dest, uint32 widthInPixels, uint32 heightInLines, uint32 srcRowUpdate, bool invert)
Definition at line 40 of file rc_imageprocessing.cpp.
References ALTIVEC_VALUE_MODULO, FAST_VALUE_MODULO, and rcCverGenHalfRes().
Referenced by MungGrabDataProc(), and yourDisplayCallback().
 {
   assert(src);
   assert(dest);
   assert(widthInPixels <= srcRowUpdate);
   assert(widthInPixels > 1);
   assert(heightInLines > 1);
 #ifdef __ppc__
   if ((ALTIVEC_VALUE_MODULO(src) == 0) && (ALTIVEC_VALUE_MODULO(dest) == 0) &&
       (ALTIVEC_VALUE_MODULO(srcRowUpdate) == 0) && (FAST_VALUE_MODULO(widthInPixels) == 0))
     rcAltivecGenHalfRes(src, dest, widthInPixels, heightInLines, srcRowUpdate, invert);
   else
 #endif
     rcCverGenHalfRes(src, dest, widthInPixels, heightInLines, srcRowUpdate, invert);
 }
void rfAndImage (const rcWindow & srcWin, const rcWindow & maskWin, rcWindow & destWin)
Definition at line 558 of file rc_imageprocessing.cpp.
References ALTIVEC_VALUE_MODULO, rcWindow::depth(), rcWindow::height(), rcPixel16, rcPixel32, rcPixel8, rfCverAndImages(), rfHasSIMD(), rmExceptionMacro, rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcWindow::width().
Referenced by rcShape::project(), and rfCorrelate().
 {
   if ((srcWin.depth() != rcPixel8 &&
       srcWin.depth() != rcPixel16 &&
        srcWin.depth() != rcPixel32) ||
       srcWin.depth() != maskWin.depth() ||
       srcWin.depth() != destWin.depth() ||
       srcWin.width() != maskWin.width() ||
       srcWin.width() != destWin.width() ||
       srcWin.height() != maskWin.height() ||
       srcWin.height() != destWin.height())
     {
       rmExceptionMacro(<< "IP MisMatch");
     }
   uint8* src = (uint8*)srcWin.rowPointer(0);
   uint8* dest = (uint8*)destWin.rowPointer(0);
   uint8* mask = (uint8*)maskWin.rowPointer(0);
   int32 srcRowUpdate = srcWin.rowUpdate();
   int32 destRowUpdate = destWin.rowUpdate();
   int32 maskRowUpdate = maskWin.rowUpdate();
   int32 widthInPixels = srcWin.width()*((int32)srcWin.depth());
 #ifdef __ppc__
   if (rfHasSIMD () && (ALTIVEC_VALUE_MODULO(src) == 0) && (ALTIVEC_VALUE_MODULO(dest) == 0) &&
       (ALTIVEC_VALUE_MODULO(mask) == 0) &&
       (ALTIVEC_VALUE_MODULO(srcRowUpdate) == 0) &&
       (ALTIVEC_VALUE_MODULO(destRowUpdate) == 0) &&
       (ALTIVEC_VALUE_MODULO(maskRowUpdate) == 0) &&
       (ALTIVEC_VALUE_MODULO(widthInPixels) == 0))
     rfAltivecAndImages(src, mask, dest, widthInPixels, srcWin.height(),
                srcRowUpdate);
   else
 #endif
     rfCverAndImages(srcWin, maskWin, destWin);
 }
void rfTemporalMedian (const vector< rcWindow > & srcWin, rcWindow & destWin)
Definition at line 648 of file rc_imageprocessing.cpp.
References rcWindow::depth(), rcWindow::height(), rcWindow::isBound(), rcPixel16, rcPixel8, rfTemporalMedianPixel16(), rfTemporalMedianPixel8(), rmAssert, and rcWindow::width().
Referenced by main().
 {
     rmAssert (srcWin.size() == 3);
     if (! destWin.isBound () )
     {
         destWin = rcWindow (srcWin[0].width(), srcWin[1].height (), srcWin[0].depth () );
     }
     for (uint32 i = 0; i < srcWin.size(); i++)
     {
         rmAssert(srcWin[i].depth() == destWin.depth());
         rmAssert(srcWin[i].width() == destWin.width());
         rmAssert(srcWin[i].height() == destWin.height());
     }
     switch (destWin.depth ())
     {
         case rcPixel8:
         rfTemporalMedianPixel8 (srcWin, destWin);
         break;
         case rcPixel16:
         rfTemporalMedianPixel16 (srcWin, destWin);
         break;
         default:
         rmAssert (1);
     }
 }