Visible: src/analysis/code/rc_kinereport.cpp File Reference
rc_kinereport.cpp File Reference
#include <rc_kinetoscope.h>
Functions
ostream & operator<< (ostream &output, rcKinetoscope &kin)
Function Documentation
ostream& operator<< (ostream & output, rcKinetoscope & kin)
Definition at line 14 of file rc_kinereport.cpp.
References rcDegree::Double(), endl(), output(), and rcKinetoscope::visualBodies().
 {
   const list<rcVisualFunction>& visualBodies = kin.visualBodies();
   list<rcVisualFunction>::const_iterator cell;
   for( cell = visualBodies.begin(); cell != visualBodies.end(); ++cell )
     {
       output << "cell" << cell->id() << "minLaTtlX" << (int32) cell->position().x() << "tlY" << (int32) cell->position().y() << " = {";
       for (uint32 i = 0; i < cell->interpolatedMin().size() - 1;i++)
     {
       if (i) output << ",";
       output << "{" << cell->interpolatedMin()[i].x() << "," << cell->interpolatedMin()[i].y() << "}";
     }
       output << "};" << endl;
     }
   for( cell = visualBodies.begin(); cell != visualBodies.end(); ++cell )
     {
       output << "cell" << cell->id() << "ceAnglesTlX" << (int32) cell->position().x() << "tlY" << (int32) cell->position().y() << " = {";
       for (uint32 i = 0; i < cell->peakAngles().size() - 1;i++)
     {
       if (i) output << ",";
       rcDegree c (cell->peakAngles()[i].x());
       rcDegree r (cell->peakAngles()[i].y());
       output << "{" << c.Double() << "," << r.Double() << "}";
     }
       output << "};" << endl;
     }
   return output;
 }