Visible: src/visual/code/rc_imagegrabber.cpp File Reference
rc_imagegrabber.cpp File Reference
#include <rc_qtime.h>
#include <rc_imagegrabber.h>
#include <rc_ipconvert.h>
Functions
static OSErr rfImageFileToRcWindow (const FSSpec *pfsspecImage, rcWindow &rcwin, GraphicsImportComponent &gi)
Function Documentation
static OSErr rfImageFileToRcWindow (const FSSpec * pfsspecImage, rcWindow & rcwin, GraphicsImportComponent & gi) static
Definition at line 20 of file rc_imagegrabber.cpp.
References rcWindow::depth(), getPixelInfoFromImageDesc(), NULL, rcPixel16, rcPixel8, rfFillColorMap(), rfReversePixels8(), rcWindow::rowPointer(), rcWindow::rowUpdate(), and rcFrame::setIsGray().
Referenced by rcImageGrabber::getNextFrame(), and rfImageFileToRcWindowGi().
 {
    uint32 imageWidth, imageHeight, pf;
    ImageDescriptionHandle imageDescH = NULL;
    ImageDescription *desc;
    rcWindow tmp;
    GWorldPtr gWorld = NULL;
    ComponentResult result;
    QDErr err = noErr;
    rcPixel pd;
    CTabHandle ctb;
    bool isGray;
    bool isWhiteReversed;
    int32 overEightSize (0), fileSize (0);
    if (pfsspecImage == NULL) return (bdNamErr);
    // Get the file size. We use this to uncover quicktime's inability to tell us if it is 8 or 16 bit monochrom
    // @todo move to util or separate function.
    FSRef filerf;
    OSErr osErr;
    osErr = FSpMakeFSRef(pfsspecImage, &filerf);
    FSCatalogInfoBitmap whichInfo;
    FSCatalogInfo    catalogInfo;
    whichInfo = kFSCatInfoNodeFlags;
    whichInfo |= kFSCatInfoDataSizes;
    whichInfo |= kFSCatInfoRsrcSizes;
    osErr = FSGetCatalogInfo(&filerf, whichInfo, &catalogInfo, NULL, NULL,NULL);
    fileSize = catalogInfo.dataLogicalSize + catalogInfo.rsrcLogicalSize;
    // Get the graphics importer
    GetGraphicsImporterForFile(pfsspecImage, &gi);
    result = GraphicsImportGetImageDescription(gi, &imageDescH);
    if( noErr != result || imageDescH == NULL )
    {
      return (bdNamErr);
    }
    desc = *imageDescH;
    getPixelInfoFromImageDesc (imageDescH, pd, pf, isGray, isWhiteReversed, &ctb);
 #ifdef DEBUG_LOG
    for (int i = 0; i < 256; i++)
       fprintf (stderr, "[%d]: %d\t%d\t%d\n", i, (*ctb)->ctTable[i].rgb.Qt::red, (*ctb)->ctTable[i].rgb.Qt::green, (*ctb)->ctTable[i].rgb.Qt::blue);
 #endif
    // Get size and format information we need
    Rect boundsRect = { 0, 0, desc->height, desc->width };
    imageWidth = desc->width;
    imageHeight = desc->height;
    overEightSize = imageWidth * imageHeight;
    overEightSize += overEightSize / 10; // add 10 percent
    // Check to see if file size and pixel format / depth match
    if (pd == rcPixel8 && pf == k8IndexedGrayPixelFormat && overEightSize < fileSize)
      {
        pd = rcPixel16;
        pf = k16GrayCodecType;
      }
    PixMapHandle pixMap = NULL;
    // We will allocate GWorld memory ourselves as a framebuf ===> Dispose will not free this memory
    try
       {
          rcSharedFrameBufPtr buf(new rcFrame (imageWidth, imageHeight, rcPixel (pd)));
          buf->setIsGray(isGray);
          if ( pd < rcPixel16 ) {
              rfFillColorMap( ctb, buf );
          }
          // set a rcWindow to be an entire window in to this
          rcWindow rw (buf);
          tmp = rw;
          assert (pf);
          err = QTNewGWorldFromPtr( &gWorld, pf, &boundsRect, ctb, NULL, kNativeEndianPixMap,
             (char *) (tmp.rowPointer(0)), tmp.rowUpdate ());
          if (noErr != err)
          {
             goto bail; // Should throw an exception ????
          }
          pixMap = GetGWorldPixMap(gWorld);
          LockPixels(pixMap);
       }
    catch (...)
    {
       goto bail;
    }
    // Associate this GWorld with the importer
    if( (result = GraphicsImportSetGWorld(gi, gWorld, NULL)) != noErr )
    {
       goto bail;
    }
    // Import the pixels in to the GWorld. Note that the image is drawn in to the memory that we own.
    if( (result = GraphicsImportDraw(gi)) != noErr )
    {
       goto bail;
    }
    if ( isWhiteReversed && tmp.depth() == rcPixel8 ) {
        // Reverse pixels and use default color map
        rfReversePixels8( tmp );
    }
    //   if ( isWhiteReversed && tmp.depth() == rcPixel16 ) {
    //       // Reverse pixels and use default color map
    //       rfReversePixels16( tmp );
    //   }
    // Copy window out
    rcwin = tmp;
    UnlockPixels(pixMap);
    bail:
    DisposeGWorld(gWorld);
    CloseComponent(gi);
    if( imageDescH != NULL)
       DisposeHandle((Handle)imageDescH);
    return err;
 }