Visible: src/visible/qt/rc_cellinfowidget.cpp File Reference
rc_cellinfowidget.cpp File Reference
#include <qlayout.h>
#include <qlabel.h>
#include <qtooltip.h>
#include <Q3HBoxLayout>
#include <Q3VBoxLayout>
#include <rc_model.h>
#include <rc_kinetoscope.h>
#include "rc_modeldomain.h"
#include "rc_trackmanager.h"
#include "rc_cellinfowidget.h"
#include "rc_appconstants.h"
Functions
static const QString cBaseCaption ("Locomotive Body Data: ")
static uint32 countDisplayableGroups (QString &caption)
static void getTrackValue (rcTrack *track, const rcTimestamp &timeToDisplay, QString &value)
Variables
static const Qt::BackgroundMode cWidgetBackgroundMode = Qt::FixedColor
static const int cWordBreakAlignment = (Qt::AlignLeft | Qt::AlignTop | Qt::WordBreak)
Function Documentation
static const QString cBaseCaption ("Locomotive Body Data: ") static
Referenced by countDisplayableGroups(), and rcCellInfoWidget::rcCellInfoWidget().
static uint32 countDisplayableGroups (QString & caption) static
Definition at line 34 of file rc_cellinfowidget.cpp.
References cBaseCaption(), eGroupSemanticsBodyMeasurements, rcModelDomain::getExperiment(), rcModelDomain::getModelDomain(), rcTrackGroup::getName(), rcExperiment::getNTrackGroups(), rcExperiment::getTrackGroup(), rcTrackManager::getTrackManager(), rcTrackGroup::getType(), and rcTrackManager::isTrackGroupEnabled().
Referenced by rcCellInfoWidget::updateTrackDisplay().
 {
     rcModelDomain* domain = rcModelDomain::getModelDomain();
     rcExperiment* experiment = domain->getExperiment();
     rcTrackManager* tmp = rcTrackManager::getTrackManager();
     uint32 displayableGroups = 0;
     // Count displayable tracks and compose a window caption
     int nTrackGroups = experiment->getNTrackGroups();
     for (int i = 0; i < nTrackGroups; i++)
     {
         rcTrackGroup* trackGroup = experiment->getTrackGroup( i );
         if ( tmp->isTrackGroupEnabled( i ) ) {
             // Only display data from cell info groups
             if ( trackGroup->getType() == eGroupSemanticsBodyMeasurements ) {
                 // Get track name
                 if ( !displayableGroups ) {
                     caption.sprintf( "%s%s",
                                      cBaseCaption.latin1(), trackGroup->getName() );
                 }
                 ++displayableGroups;
             }
         }
     }
     if ( !displayableGroups ) {
          caption.sprintf( "%sno data",
                           cBaseCaption.latin1() );
     } else if ( displayableGroups > 1 ) {
         caption.sprintf("%s%i cells",
                         cBaseCaption.latin1(), displayableGroups );
     }
     return displayableGroups;
 }
static void getTrackValue (rcTrack * track, const rcTimestamp & timeToDisplay, QString & value) static
Definition at line 70 of file rc_cellinfowidget.cpp.
References rcSegmentIterator::contains(), ePositionTrack, eScalarTrack, eWriterBodyState, rcScalarTrack::getDataSegmentIterator(), rcPositionTrack::getDataSegmentIterator(), rcTrack::getDisplayFormatString(), rcTrack::getTag(), rcTrack::getTrackType(), rcScalarSegmentIterator::getValue(), rcPositionSegmentIterator::getValue(), rfVisualFunctionStateName(), rmDim, rcWriterManager::tagType(), rcPair< T >::x(), and rcPair< T >::y().
Referenced by rcCellInfoWidget::updateTrackDisplay().
 {
     rcTrackType type = track->getTrackType();
     if ( track ) {
         char valueBuf[ 256 ];
         rcSegmentIterator* iter = 0;
         if ( type == eScalarTrack ) {
             // get the scalar track.
             rcScalarTrack* scalarTrack = dynamic_cast<rcScalarTrack*>( track );
             if (scalarTrack == 0)
                 return;
             // get the scalar value at the time to display
             iter = scalarTrack->getDataSegmentIterator( timeToDisplay );
         } else if ( type == ePositionTrack ) {
             // get the position track.
             rcPositionTrack* pTrack = dynamic_cast<rcPositionTrack*>( track );
             if (pTrack == 0) {
                 return;
             }
             // get the value at the time to display
             iter = pTrack->getDataSegmentIterator( timeToDisplay );
         }
         if ( iter ) {
             if ( iter->contains( timeToDisplay ) ) {
                 // timeToDisplay is within the segment
                 if ( type == eScalarTrack ) {
                     rcScalarSegmentIterator* si = dynamic_cast<rcScalarSegmentIterator*>(iter);
                     double value = si->getValue();
                     // Special case for cell state track
                     if ( rcWriterManager::tagType( track->getTag() ) == eWriterBodyState ) {
                         rfVisualFunctionStateName( static_cast<rcVisualFunction::State>(value),
                                    valueBuf,
                                    rmDim(valueBuf) );
                     } else {
                         // Generic scalar track
                         snprintf( valueBuf , rmDim(valueBuf),
                                   track->getDisplayFormatString(), value );
                     }
                 } else if ( type == ePositionTrack ) {
                     rcPositionSegmentIterator* pi = dynamic_cast<rcPositionSegmentIterator*>(iter);
                     rcFPair value = pi->getValue();
                     snprintf( valueBuf, rmDim(valueBuf),
                               "%.4f, %.4f", value.x(), value.y() );
                 }
             } else {
                 // timeToDisplay is either before track start or after track end
                 snprintf( valueBuf , rmDim(valueBuf), "Undefined" );
             }
             value.sprintf( "%s\n", valueBuf );
             delete iter;
         }
     }
 }
Variable Documentation
const Qt::BackgroundMode cWidgetBackgroundMode = Qt::FixedColor static
Definition at line 26 of file rc_cellinfowidget.cpp.
Referenced by rcCellInfoWidget::rcCellInfoWidget().
const int cWordBreakAlignment = (Qt::AlignLeft | Qt::AlignTop | Qt::WordBreak) static
Definition at line 28 of file rc_cellinfowidget.cpp.
Referenced by rcCellInfoWidget::rcCellInfoWidget().