Visible: src/visual/code/rc_movieconverter.cpp File Reference
rc_movieconverter.cpp File Reference
#include <libgen.h>
#include <unistd.h>
#include <iostream>
#include <rc_movieconverter.h>
#include <rc_videocache.h>
#include <rc_imagegrabber.h>
#include <file_system.hpp>
#include <rc_stlplus.h>
Macros
#define kVideoTimeScale 1000
#define cleanupAndReturn
Functions
static movieChannelType channelType (rcChannelConversion c)
ostream & operator<< (ostream &o, const rcMovieConverterOptions &opt)
ostream & operator<< (ostream &o, const rcMovieConverterOptionsRfy &opt)
ostream & operator<< (ostream &o, const rcMovieConverterOptionsQT &opt)
Variables
static uint32 cVideoCacheMem = 1024*1024*32
static uint32 cVideoCacheSize = 10
Macro Definition Documentation
#define cleanupAndReturn
Value:
{                                           \
        SetGWorld(mySavedPort, mySavedDevice);  \
        if (ctabHdl != NULL)                    \
            DisposeHandle((Handle)ctabHdl);     \
        if (myImageDesc != NULL)                \
            DisposeHandle((Handle)myImageDesc); \
        if (myComprDataHdl != NULL)             \
            DisposeHandle(myComprDataHdl);      \
        if (myGWorld != NULL)                   \
            DisposeGWorld(myGWorld);            \
        if (myErr)                              \
            printf("Died %d\n", (int)myErr);    \
        return myErr;                           \
    }
Definition at line 26 of file rc_movieconverter.cpp.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia().
#define kVideoTimeScale 1000
Definition at line 21 of file rc_movieconverter.cpp.
Referenced by rcMovieConverterToQT::addVideoSamplesToMedia(), and rcMovieConverterToQT::createQTMovie().
Function Documentation
static movieChannelType channelType (rcChannelConversion c) static
Definition at line 42 of file rc_movieconverter.cpp.
References movieChannelAll, movieChannelAvg, movieChannelBlue, movieChannelGreen, movieChannelMax, movieChannelRed, movieChannelUnknown, rcSelectAll, rcSelectAverage, rcSelectBlue, rcSelectGreen, rcSelectMax, and rcSelectRed.
Referenced by rcMovieConverterToRfy::createRfyMovie().
 {
     switch ( c ) {
         case rcSelectRed:
             return movieChannelRed;
         case rcSelectGreen:
             return movieChannelGreen;
         case rcSelectBlue:
             return movieChannelBlue;
         case rcSelectAverage:
             return movieChannelAvg;
         case rcSelectMax:
             return movieChannelMax;
         case rcSelectAll:
             return movieChannelAll;
     }
     return movieChannelUnknown;
 }
ostream& operator<< (ostream & o, const rcMovieConverterOptions & opt)
Definition at line 1199 of file rc_movieconverter.cpp.
References rcMovieConverterOptions::creator(), endl(), rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcMovieConverterOptions::frameInterval(), rcMovieConverterOptions::frameOffset(), rcMovieConverterOptions::overWrite(), and rcMovieConverterOptions::samplePeriod().
 {
     o << "FrameInterval:   " << opt.frameInterval() << endl;
     o << "FirstFrameIndex: " << opt.firstFrameIndex() << endl;
     o << "FrameCount:      " << opt.frameCount() << endl;
     o << "FrameOffset:     " << opt.frameOffset() << endl;
     o << "SamplePeriod:    " << opt.samplePeriod() << endl;
     o << "OverWrite:       " << opt.overWrite() << endl;
     o << "Creator:         " << opt.creator() << endl;
     return o;
 }
ostream& operator<< (ostream & o, const rcMovieConverterOptionsRfy & opt)
Definition at line 1212 of file rc_movieconverter.cpp.
References rcMovieConverterOptionsRfy::channelConversion(), endl(), rcMovieConverterOptionsRfy::rev(), and rcMovieConverterOptions::reversePixels().
 {
     const rcMovieConverterOptions& baseOpt = opt;
     o << baseOpt;
     o << "ChannelConversion: " << opt.channelConversion() << endl;
     o << "ReversePixels:     " << opt.reversePixels() << endl;
     o << "FileRev:           " << opt.rev() << endl;
     return o;
 }
ostream& operator<< (ostream & o, const rcMovieConverterOptionsQT & opt)
Definition at line 1223 of file rc_movieconverter.cpp.
 {
     const rcMovieConverterOptions& baseOpt = opt;
     o << baseOpt;
     return o;
 }
Variable Documentation
uint32 cVideoCacheMem = 1024*1024*32 static
Definition at line 23 of file rc_movieconverter.cpp.
Referenced by rcMovieConverterToQT::convert(), and rcMovieConverterToRfy::convert().
uint32 cVideoCacheSize = 10 static
Definition at line 24 of file rc_movieconverter.cpp.
Referenced by rcMovieConverterToQT::convert(), and rcMovieConverterToRfy::convert().