Visible: include/util/rc_rectangle.h File Reference
rc_rectangle.h File Reference
#include <rc_pair.h>
#include <rc_types.h>
#include <rc_vector2d.h>
#include <rc_math.h>
#include <rc_exception.h>
#include <deque>
Classes
class rcRectangle< T >
Typedefs
typedef rcRectangle< float > rcFRect
typedef rcRectangle< double > rcDRect
typedef rcRectangle< int32 > rcIRect
typedef rcRectangle< uint32 > rcUIRect
Functions
template<class P >
rcIRect rfRoundRectangle (const rcRectangle< P > &fr)
void rfBoundingRect (const deque< rc2Dvector > &pts, rcDRect &box)
Typedef Documentation
typedef rcRectangle<double> rcDRect
Definition at line 375 of file rc_rectangle.h.
typedef rcRectangle<float> rcFRect
Definition at line 374 of file rc_rectangle.h.
typedef rcRectangle<int32> rcIRect
Definition at line 376 of file rc_rectangle.h.
typedef rcRectangle<uint32> rcUIRect
Definition at line 377 of file rc_rectangle.h.
Function Documentation
void rfBoundingRect (const deque< rc2Dvector > & pts, rcDRect & box)
Definition at line 23 of file rc_rectangle.cpp.
References rmAssert.
 {
   double x, y, minx, miny, maxx, maxy;
   rmAssert(pts.size() >= 1);
   deque<rc2Dvector>::const_iterator point = pts.begin();
   deque<rc2Dvector>::const_iterator lastplus = pts.end();
   minx = maxx = point->x();
   miny = maxy = point->y();
   for(point++; point != lastplus; point++)
     {
       x = point->x();
       y = point->y();
       if (x < minx)
     minx = x;
       if (x > maxx)
     maxx = x;
       if (y < miny)
     miny = y;
       if (y > maxy)
     maxy = y;
     }
   box = rcDRect (rcDPair (minx, miny), rcDPair (maxx, maxy));
 }
template<class P > rcIRect rfRoundRectangle (const rcRectangle< P > & fr)
Definition at line 617 of file rc_rectangle.h.
References rcRectangle< T >::height(), rcRectangle< T >::lr(), rcRectangle< T >::origin(), rfRound(), rcRectangle< T >::ul(), rcRectangle< T >::width(), rcPair< T >::x(), and rcPair< T >::y().
 {
   static const int32 dummy (0);
   rcIPair iSize (rfRound (fr.width(), dummy), rfRound (fr.height(), dummy));
   int32 right, left, top, bottom;
   if ((fr.ul().x() - (int32) (fr.ul().x())) < ((int32) fr.lr().x() + P (1) -fr.lr().x()))
     {
       left = (int32) fr.origin().x(); right = left + iSize.x();
     }
   else
     {
       right = (int32) fr.lr().x() +1; left = right - iSize.x();
     }
   if ((fr.ul().y() - (int32) fr.ul().y()) < ((int32) fr.lr().y() + P (1) -fr.lr().y()))
     {
       top = rfRound (fr.ul().y(), dummy); bottom = top + iSize.y();
     }
   else
     {
       bottom = (int32) fr.lr().y() + 1; top = bottom - iSize.y();
     }
   return rcIRect (left, top, right - left, bottom - top);
 }