Visible: src/util/code/rc_simd_mac.cpp File Reference
rc_simd_mac.cpp File Reference
#include <rc_types.h>
#include <sys/sysctl.h>
Functions
bool rfHasSIMD ()
bool rfForceSIMD (bool v)
Variables
static bool sForceAltiVec = TRUE
static int sHasAltivec = -1
Function Documentation
bool rfForceSIMD (bool v)
Definition at line 57 of file rc_simd_mac.cpp.
References sForceAltiVec.
 {
    sForceAltiVec = v;
    return v;
 }
bool rfHasSIMD ()
Definition at line 33 of file rc_simd_mac.cpp.
References NULL, sForceAltiVec, and sHasAltivec.
Referenced by rcKinetoscope::epiMotionField(), rfAndImage(), rfCorrelate(), rfCorrelateWindow(), rfGauss3(), rfGaussianConv(), rfImageConvert8to32(), rfPixel8Map(), and rcKinetoscope::selfSimilarMotionField_AttentiveCapture().
 {
 #if defined (__ppc__)
     if ( sHasAltivec < 0 ) {
         // Detect Altivec only once
         int selectors[2] = { CTL_HW, HW_VECTORUNIT };
         int hasVectorUnit = 0;
         size_t length = sizeof(hasVectorUnit);
         int error = sysctl(selectors, 2, &hasVectorUnit, &length, NULL, 0);
         if( 0 == error) {
             sHasAltivec = hasVectorUnit;
         }
         else
             sHasAltivec = 0;
     }
     return (sHasAltivec != 0 && sForceAltiVec);
 #elseif
     return false;
 #endif
 }
Variable Documentation
bool sForceAltiVec = TRUE static
Definition at line 27 of file rc_simd_mac.cpp.
Referenced by rfForceSIMD(), and rfHasSIMD().
int sHasAltivec = -1 static
Definition at line 28 of file rc_simd_mac.cpp.
Referenced by rfHasSIMD().