Visible: include/analysis/rc_associate.h File Reference
rc_associate.h File Reference
#include <rc_macro.h>
#include <rc_polygongroup.h>
Functions
void rfAssociate (vector< rc2Dvector > &cells, vector< rc2Dvector > &regions, vector< int32 > &labels, vector< float > &scores)
Function Documentation
void rfAssociate (vector< rc2Dvector > & cells, vector< rc2Dvector > & regions, vector< int32 > & labels, vector< float > & scores)
Definition at line 40 of file rc_associate.cpp.
References colMaxY(), rc2dVector< T >::distanceSquared(), endl(), PM, rmAssert, rowMaxX(), NR::svdcmp(), rc2dVector< T >::x(), and rc2dVector< T >::y().
Referenced by rcKinetoscope::associate().
 {
   int32 j,k,l,m,n;
   m = cells.size();
   n = regions.size();
   rmAssert (labels.size() == cells.size());
   if (!n || !m) return;
   Vec_DP w(n);
   Mat_DP a(m,n),u(m,n),v(n,n);
   //#define PM(a) pow (2.71828, -(a) / (1.4 * gl))
 #define PM(a) (1.0 / (a))
   rc2Dvector cop;
   rc2Fvector lp;
   vector<rc2Dvector>::iterator cell = cells.begin();
   for (k=0;k<m;k++, cell++)
     {
       labels[k] = 0; // clear the labels (no relation to this loop)
       rc2Fvector kp;
       kp.x((float) cell->x()), kp.y((float) cell->y());
       for (l = 0; l < n; l++)
     {
       lp.x((float) regions[l].x()), lp.y((float) regions[l].y());
       double pm = PM(kp.distanceSquared (lp) + 1e-10);
       a[k][l] = pm;
       u[k][l] = pm;
     }
     }
   // perform decomposition
   NR::svdcmp(u,w,v);
   // Replace the diagonal with 1. And produce U W V^t
   for (k=0;k<m;k++)
     {
       for (l=0;l<n;l++)
     {
       a[k][l]=0.0;
       for (j=0;j<n;j++)
         a[k][l] += u[k][j]*v[l][j];
     }
     }
 #ifdef MATHPRINT
   cerr.setf (ios::fixed);
   cerr << setprecision (4);
   cerr << "{";
   for (k=0;k<m;k++)
     {
       cerr << "{";
     for (l=0;l<n;l++)
       {
       double moo = a[k][l] < 1e-7 ? 0.0 : a[k][l];
       if (l < n - 1)
         cerr << setw(5) << moo << ",\t";
       else
         cerr << setw(5) << moo << "}" << endl;
       }
     if (k < m - 1)
       cerr << " , ";
     else
       cerr << "};" << endl;
     }
   cerr << endl;
 #endif MATHPRINT
   // @note:
   // Look for associations that are max in both x and y
   // For each cell find the best region.
   // Then check that the best region is only best for this cell.
   cell = cells.begin();
   for (k = 0; k < m; k++, cell++)
     {
       double ratio;
       double rmax (-1.0), cmax (-1.0);
       int32 rowMax = rowMaxX (a, n, k, ratio, rmax);
       if (colMaxY (a, m, rowMax, ratio, cmax) == k)
     {
       rmAssert (rowMax >= 0);
       rmAssert (rowMax < n);
       uint32 index = cell - cells.begin();
       labels[index] = rowMax;
       scores[index] = (float) cmax;
     }
     }
 }