Visible: src/visible/src/rc_engineimplcmdline.cpp File Reference
rc_engineimplcmdline.cpp File Reference
#include "rc_engineimpl.h"
#include <rc_parametermap.h>
#include <rc_fileutils.h>
Functions
ostream & rcVisibleBatchUsage (ostream &o)
Function Documentation
ostream& rcVisibleBatchUsage (ostream & o)
Definition at line 278 of file rc_engineimplcmdline.cpp.
References endl().
Referenced by main(), and rcEngineImpl::setFromArgs().
 {
   o << endl;
   o << endl <<
     "       -movie [movieFile]                                                                  " << endl <<
     "       -dirOfTiffs [tiffdir]                                                               " << endl <<
     "       -result [resultFile]                                                                 " << endl <<
     "       -analysis aci|vis|dif|cell   Analysis mode:    aci  - Exhaustive aggregate change index" << endl <<
     "                                               vis  - Exhaustive visual entropy        " << endl <<
     "                                               dif  - Exhaustive diffusion index       " << endl <<
     "                                               cell - Cell tracking (default)          " << endl <<
     "                                               target - Target tracking (default)          " << endl <<
     "       -halfWindow (half window size:            applies to aci/vis/dif                         " << endl <<
     "       -type general|myo|smooth|Flu.    Cell Type: general (default) myocyte              " << endl <<
     "       -report csv|eml            Results format:   csv - Comma separated values            " << endl <<
     "                                               xml - Native Reify XML format           " << endl <<
     "                                               default: Native                         " << endl <<
     "       -graphics no|body|motion|all Graphics output:  no     - None                           " << endl <<
     "                                               body   - Locomotive body (default)      " << endl <<
     "                                               motion - Motion vector                  " << endl <<
     "                                               all    - All                            " << endl <<
     "       -Frame (2 numbers to indicate start/finish  (default: entire frame)             " << endl <<
     "       -TopLeft (2 numbers first indicates X, Second Y)                                " << endl <<
     "       -Size (2 numbers first indicates width, Second height                           " << endl <<
     "       -MaxDisplacement (in Pixels maximum change in position in between sequential frames " << endl <<
     "       -Channel (-1 all, 0, average, 1, 2, 3 (r & g & b or reverse)                    " << endl <<
     "       -advanced: (exp - LongExposure, drg - Dorsal Assay, drgautomask - Dorsal Assay AutoMask)              " << endl <<
     "       -exportImages [exportDirectory]                                         " << endl << endl <<
     "Example: Visible -analysis aci -type myo -graphics no -movie /Users/john/Desktop/foo.rfymov -result /Users/john/Desktop/foo " << endl;
   return o;
 }