Visible: src/analysis/code/rc_visualfunction.cpp File Reference
rc_visualfunction.cpp File Reference
#include <rc_analysis.h>
#include <rc_kinetoscope.h>
#include <rc_math.h>
#include <iomanip.h>
#include <algorithm>
#include <rc_lsfit.h>
#include <rc_xforms.h>
#include <rc_affinewindow.h>
#include <rc_shape.h>
#include <rc_mathmodel.h>
#include <rc_peak.h>
#include <rc_1dcorr.h>
#include <rc_stats.h>
#include <rc_filter1d.h>
Functions
static const int32 sDummy (0)
bool rfCellNotViable (const rcVisualFunction &vf)
void rfVisualFunctionStateName (rcVisualFunction::State state, char *valueBuf, uint32 bufSize)
ostream & operator<< (ostream &o, const rcVisualFunction::State &st)
ostream & operator<< (ostream &o, const rcVisualFunction &p)
Function Documentation
ostream& operator<< (ostream & o, const rcVisualFunction::State & st)
Definition at line 505 of file rc_visualfunction.cpp.
References rfVisualFunctionStateName().
 {
   char buf[64];
   rfVisualFunctionStateName(st, buf, 64);
   o << buf;
   return o;
 }
ostream& operator<< (ostream & o, const rcVisualFunction & p)
Definition at line 514 of file rc_visualfunction.cpp.
References rcVisualFunction::age(), rcBaseMotionPath::anchor(), rcVisualFunction::area(), rcVisualFunction::circularity(), rcVisualFunction::contractionFrequency(), rcVisualFunction::dimensions(), rcVisualFunction::distance(), rcVisualFunction::eBeatInfo, rcVisualFunction::eContraction, rcVisualFunction::eIsBeating, rcVisualFunction::eIsChild, rcVisualFunction::eIsDirected, rcVisualFunction::eIsDivided, rcVisualFunction::eIsDividing, rcVisualFunction::eIsFragmented, rcVisualFunction::eIsJustDivided, rcVisualFunction::eIsMoving, rcVisualFunction::eIsOutSide, rcVisualFunction::eIsParent, rcVisualFunction::eIsRounded, rcVisualFunction::eIsRounding, rcVisualFunction::eIsUnInitialized, rcVisualFunction::eIsUnknown, rcVisualFunction::ellipseRatio(), endl(), rcVisualFunction::ePacingInfo, rcVisualFunction::have(), rcVisualFunction::id(), rcVisualFunction::isCardiacCell(), rcVisualFunction::isLabelProtein(), rcVisualFunction::isState(), rcBaseMotionPath::motion(), rcVisualFunction::mSS, rcBaseMotionPath::mSteps, rcVisualFunction::parentId(), rcVisualFunction::perimeter(), rcVisualFunction::persistence(), rcVisualFunction::position(), rcVisualFunction::shortenning(), rcVisualFunction::speed(), rcVisualFunction::velocity(), and rcPair< T >::x().
 {
   string s (" States: \n");
   if(p.isState(rcVisualFunction::eIsUnInitialized)) s +=  string ("+eUnInitialized\n");
   if(p.isState(rcVisualFunction::eIsUnknown)) s +=  string ("+eIsUnknown\n");
   if(p.isState(rcVisualFunction::eIsMoving)) s +=  string ("+eIsMoving\n");
   if(p.isState(rcVisualFunction::eIsDirected)) s +=  string ("+eIsDirected\n");
   if(p.isState(rcVisualFunction::eIsJustDivided)) s +=  string ("+eIsJustDivided\n");
   if(p.isState(rcVisualFunction::eIsDividing)) s +=  string ("+eIsDividing\n");
   if(p.isState(rcVisualFunction::eIsDivided)) s +=  string ("+eIsDivided\n");
   if(p.isState(rcVisualFunction::eIsFragmented)) s +=  string ("+eIsFragmented\n");
   if(p.isState(rcVisualFunction::eIsOutSide)) s +=  string ("+eIsOutSide\n");
   if(p.isState(rcVisualFunction::eIsBeating)) s +=  string ("+eIsBeating\n");
   if(p.isState(rcVisualFunction::eIsParent)) s +=  string ("+eIsParent\n");
   if(p.isState(rcVisualFunction::eIsChild)) s +=  string ("+eIsChild\n");
   if(p.isState(rcVisualFunction::eIsRounding)) s +=  string ("+eIsRounding\n");
   if(p.isState(rcVisualFunction::eIsRounded)) s +=  string ("+eIsRounded\n");
   string c (" Type: \n");
   if (p.isCardiacCell()) c += string (" Cardiac \n");
   else if (p.isLabelProtein ()) c += string (" Label Protein \n");
   else c += string (" General \n");
   o << endl;
   o << c << " Id: " << p.id() << " Parent: " << p.parentId() << endl;
   o << s << "[" << p.mSteps << "]: ";
   o << "Trace: " << p.motion() << "Area: " << p.area() << endl;
   o << "Dist:  " << p.distance() << "Persistance  : " << p.persistence() << "CEP : " <<
     p.circularity () <<  "," << p.ellipseRatio() << "," << p.perimeter () << endl;
   o << "Age :" << p.age() << "Anchor: " << p.anchor() << "Position: " << p.position () << endl;
   o << "Velocity: " << p.velocity() << "Speed: " << p.speed() << endl;
   if (p.isCardiacCell ())
     {
       if ( p.have( rcVisualFunction::eContraction ) )
     o << "Length: " << p.dimensions().x();
       if ( p.have( rcVisualFunction::ePacingInfo) )
     o << "Pacing Freq: " << p.contractionFrequency ();
       if ( p.have( rcVisualFunction::eBeatInfo) )
     o << "Shortening: " << p.shortenning();
     }
   if (p.mSS.size())
     {
  //     o << p.mSS << endl;
     }
   return o;
 }
bool rfCellNotViable (const rcVisualFunction & vf)
Definition at line 451 of file rc_visualfunction.cpp.
References rcVisualFunction::eIsDivided, rcVisualFunction::eIsOutSide, rcVisualFunction::eIsUnInitialized, and rcVisualFunction::isState().
Referenced by rcKinetoscope::associate(), rcVisualFunction::measure(), rcVisualFunction::reconcile(), rfOfCellsAndPolys(), rcVisualFunction::update(), and rcKinetoscope::visualDebugGraphics().
 {
   return (vf.isState (rcVisualFunction::eIsDivided) || vf.isState(rcVisualFunction::eIsOutSide)
       || vf.isState (rcVisualFunction::eIsUnInitialized));
 }
void rfVisualFunctionStateName (rcVisualFunction::State state, char * valueBuf, uint32 bufSize)
Definition at line 460 of file rc_visualfunction.cpp.
References rcVisualFunction::eIsBeating, rcVisualFunction::eIsDirected, rcVisualFunction::eIsDivided, rcVisualFunction::eIsDividing, rcVisualFunction::eIsFragmented, rcVisualFunction::eIsJustDivided, rcVisualFunction::eIsMoving, rcVisualFunction::eIsOutSide, rcVisualFunction::eIsParent, rcVisualFunction::eIsUnInitialized, and rcVisualFunction::eIsUnknown.
Referenced by getTrackValue(), and operator<<().
 {
     switch ( state ) {
         case rcVisualFunction::eIsUnInitialized:
             snprintf( valueBuf, bufSize, "Uninitialized");
             return;
         case rcVisualFunction::eIsMoving:
             snprintf( valueBuf, bufSize, "Moving");
             return;
         case rcVisualFunction::eIsDirected:
             snprintf( valueBuf, bufSize, "Directed");
             return;
         case rcVisualFunction::eIsJustDivided:
       snprintf( valueBuf, bufSize, "JustDivided");
             return;
         case rcVisualFunction::eIsDividing:
             snprintf( valueBuf, bufSize, "Dividing");
             return;
         case rcVisualFunction::eIsDivided:
             snprintf( valueBuf, bufSize, "Divided");
             return;
         case rcVisualFunction::eIsFragmented:
             snprintf( valueBuf, bufSize, "Fragmented");
             return;
         case rcVisualFunction::eIsOutSide:
             snprintf( valueBuf, bufSize, "Outside");
             return;
         case rcVisualFunction::eIsUnknown:
             snprintf( valueBuf, bufSize, "Unknown");
             return;
         case rcVisualFunction::eIsBeating:
             snprintf( valueBuf, bufSize, "Beating");
             return;
         case rcVisualFunction::eIsParent:
             snprintf( valueBuf, bufSize, "Parent");
             return;
     }
     // Default case
     snprintf( valueBuf, bufSize, "Unknown state %i", state );
 }
static const int32 sDummy (0) static
Referenced by rcVisualFunction::framesPerPeriod().