Visible: include/analysis/rc_cell.h File Reference
rc_cell.h File Reference
#include <rc_types.h>
#include <rc_imageprocessing.h>
Classes
class rcCell
class rcCellCountParams
Typedefs
typedef vector< rcCell > rcVectOfCells
Enumerations
enum RC_CellPlateImaging { rcCellImagingUnknown = 0, rcHighGreyValueCells = 1, rcLowGreyValueCells = 2, rcPhaseImagingFunction = 3 }
Functions
void rfCellCount (rcWindow &image, rcCellCountParams &rcp, vector< rcCell > &cellcounts)
template<class Iterator >
void rfCellDensity (Iterator begin, Iterator end, rcCellCountParams &ccp, vector< rcVectOfCells > &res)
Typedef Documentation
typedef vector<rcCell> rcVectOfCells
Definition at line 71 of file rc_cell.h.
Enumeration Type Documentation
enum RC_CellPlateImaging
Enumerator
rcCellImagingUnknown
rcHighGreyValueCells
rcLowGreyValueCells
rcPhaseImagingFunction
Definition at line 20 of file rc_cell.h.
{
   rcCellImagingUnknown = 0,
   rcHighGreyValueCells = 1,       // Cells have higher intensity values than the background
   rcLowGreyValueCells = 2,         // Cells have lower  intensity values than the background
   rcPhaseImagingFunction = 3        // Phase contrast: Cells have low/high value presentation
 };
Function Documentation
void rfCellCount (rcWindow & image, rcCellCountParams & rcp, vector< rcCell > & cellcounts)
Referenced by rfCellDensity().
template<class Iterator > void rfCellDensity (Iterator begin, Iterator end, rcCellCountParams & ccp, vector< rcVectOfCells > & res)
Definition at line 103 of file rc_cell.h.
References rfCellCount(), rfRcWindow32to8(), rmAssert, and value_type().
 {
   rmAssert (end > begin);
   int32 size = end - begin;
   vector<rcVectOfCells> ires (size);
   // Get container value type
   typedef typename std::iterator_traits<Iterator>::value_type value_type;
   Iterator img = begin;
   vector<rcVectOfCells>::iterator plate = ires.begin();
   for (; img != end; img++, plate++)
     {
       value_type image( *img );
       // Convert to 8bit if needed
       rcWindow local;
       // Convert to 8 bit because
       if (image.depth() > RC_PixelDepth8 )
     {
       fprintf (stderr, "Converting to Depth8 for analysis");
       // Reduce all color and gray 24/32-bit images to 8-bit gray images
       rfRcWindow32to8(image, local);
     }
       else
     local = image;
       rfCellCount (*img, ccp, *plate);
     }
   res = ires;
 }