Visible: include/visual/rc_moviefileformat.h File Reference
rc_moviefileformat.h File Reference
#include <rc_types.h>
#include <rc_framebuf.h>
#include <rc_rect.h>
#include <vector>
Classes
class rcMovieFileIdentifier
class rcMovieFileFormat
struct rcMovieFrameFormat
class rcMovieFileFormat2
class rcMovieFileExt
class rcMovieFileTocExt
class rcMovieFileOrgExt
class rcMovieFileConvExt
class rcMovieFileCamExt
class rcMovieFileExpExt
Macros
#define MOVIEFILE_MAGIC_REV0 "Reify Corp"
#define MOVIEFILE_MAGIC_LTH_REV0 10
#define MOVIEFILE_MAGIC_REV2 "Reify Corp03"
#define MOVIEFILE_MAGIC_LTH_REV2 12
#define MOVIEFILE_GEN_LTH 64
Typedefs
typedef struct rcMovieFrameFormat rcMovieFrameFormat
Enumerations
enum movieFormatRev {
movieFormatInvalid = 0, movieFormatRev0, movieFormatRev1, movieFormatRev2,
movieFormatRevLatest = movieFormatRev2
}
enum movieExtensionType {
movieExtensionEOF = 0, movieExtensionTOC = 1, movieExtensionORG = 2, movieExtensionCNV = 3,
movieExtensionCAM = 4, movieExtensionEXP = 5
}
enum movieOriginType {
movieOriginUnknown = 0, movieOriginCaptureUncertified, movieOriginCaptureCertified, movieOriginConversionExt,
movieOriginSynthetic, movieOriginGrayIsVisibleAlphaIsFlu, movieOriginMultiChannelFlu, movieOriginGrayPlusMultiChannelFlu
}
enum movieChannelType {
movieChannelUnknown = 0, movieChannelAll, movieChannelAvg, movieChannelMax,
movieChannelRed, movieChannelGreen, movieChannelBlue
}
Functions
ostream & operator<< (ostream &os, const rcMovieFileFormat &e)
ostream & operator<< (ostream &os, const rcMovieFileFormat2 &e)
ostream & operator<< (ostream &os, const movieExtensionType &e)
ostream & operator<< (ostream &os, const movieOriginType &e)
ostream & operator<< (ostream &os, const movieChannelType &e)
ostream & operator<< (ostream &os, const rcMovieFileExt &e)
ostream & operator<< (ostream &os, const rcMovieFileTocExt &e)
ostream & operator<< (ostream &os, const rcMovieFileOrgExt &e)
ostream & operator<< (ostream &os, const rcMovieFileConvExt &e)
ostream & operator<< (ostream &os, const rcMovieFileCamExt &e)
ostream & operator<< (ostream &os, const rcMovieFileExpExt &e)
Macro Definition Documentation
#define MOVIEFILE_GEN_LTH 64
Definition at line 69 of file rc_moviefileformat.h.
#define MOVIEFILE_MAGIC_LTH_REV0 10
Definition at line 65 of file rc_moviefileformat.h.
Referenced by rcMovieFileIdentifier::isValid(), and setMagic().
#define MOVIEFILE_MAGIC_LTH_REV2 12
Definition at line 67 of file rc_moviefileformat.h.
Referenced by rcMovieFileIdentifier::isValid(), and setMagic().
#define MOVIEFILE_MAGIC_REV0 "Reify Corp"
Definition at line 64 of file rc_moviefileformat.h.
Referenced by rcMovieFileIdentifier::isValid(), and setMagic().
#define MOVIEFILE_MAGIC_REV2 "Reify Corp03"
Definition at line 66 of file rc_moviefileformat.h.
Referenced by rcMovieFileIdentifier::isValid(), and setMagic().
Typedef Documentation
typedef struct rcMovieFrameFormat rcMovieFrameFormat
Enumeration Type Documentation
enum movieChannelType
Enumerator
movieChannelUnknown
movieChannelAll
movieChannelAvg
movieChannelMax
movieChannelRed
movieChannelGreen
movieChannelBlue
Definition at line 53 of file rc_moviefileformat.h.
                       {
     movieChannelUnknown = 0   // Unknown channel
     , movieChannelAll         // All channels
     , movieChannelAvg         // Average of channels
     , movieChannelMax         // Max of channels
     , movieChannelRed         // Red channel
     , movieChannelGreen       // Green channel
     , movieChannelBlue        // Blue channel
 };
enum movieExtensionType
Enumerator
movieExtensionEOF
movieExtensionTOC
movieExtensionORG
movieExtensionCNV
movieExtensionCAM
movieExtensionEXP
Definition at line 33 of file rc_moviefileformat.h.
{
     movieExtensionEOF = 0     // Always movie's last extension
     , movieExtensionTOC = 1   // Table of contents
     , movieExtensionORG = 2   // Origin data
     , movieExtensionCNV = 3   // Conversion data
     , movieExtensionCAM = 4   // Camera data
     , movieExtensionEXP = 5   // Experiment data
 };
enum movieFormatRev
Enumerator
movieFormatInvalid
movieFormatRev0
movieFormatRev1
movieFormatRev2
movieFormatRevLatest
Definition at line 25 of file rc_moviefileformat.h.
                     {
     movieFormatInvalid = 0
     , movieFormatRev0
     , movieFormatRev1 // Same as rev 0, but supports extensions at end of file
     , movieFormatRev2 // New base header format, new extensions
     , movieFormatRevLatest = movieFormatRev2 // Latest supported rev
 };
enum movieOriginType
Enumerator
movieOriginUnknown
movieOriginCaptureUncertified
movieOriginCaptureCertified
movieOriginConversionExt
movieOriginSynthetic
movieOriginGrayIsVisibleAlphaIsFlu
movieOriginMultiChannelFlu
movieOriginGrayPlusMultiChannelFlu
Definition at line 42 of file rc_moviefileformat.h.
                      {
     movieOriginUnknown = 0          // Unknown origin
     , movieOriginCaptureUncertified // Uncertified Reify capture process (Rev0)
     , movieOriginCaptureCertified   // Certifid Reify capture (Rev1 and later)
     , movieOriginConversionExt      // Conversion from a non-Reify movie
     , movieOriginSynthetic          // Synthetically generated movie
     , movieOriginGrayIsVisibleAlphaIsFlu // put together from 2 channels corresponding to visible and Fluorescence
     , movieOriginMultiChannelFlu // put together from 2 channels corresponding to visible and Fluorescence
     , movieOriginGrayPlusMultiChannelFlu // put together from 2 channels corresponding to visible and Fluorescence
 };
Function Documentation
ostream& operator<< (ostream & os, const rcMovieFileFormat & e)
Definition at line 795 of file rc_moviefileformat.cpp.
References rcMovieFileFormat::averageFrameRate(), rcMovieFileFormat::baseTime(), rcMovieFileFormat::frameCount(), rcMovieFileFormat::height(), rcMovieFileFormat::rev(), rcMovieFileFormat::rowUpdate(), and rcMovieFileFormat::width().
 {
     os << "Hdr rev " << e.rev() << " width " << e.width() << " height " << e.height()
        << " rowUpdate " << e.rowUpdate() << " frameCount " << e.frameCount()
        << " avgFrameRate " << e.averageFrameRate() << " baseTime " << rcTimestamp(e.baseTime());
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileFormat2 & e)
Definition at line 804 of file rc_moviefileformat.cpp.
References rcMovieFileFormat2::averageFrameRate(), rcMovieFileFormat2::baseTime(), rcMovieFileFormat2::bom(), rcMovieFileFormat2::depth(), rcMovieFileFormat2::extensionOffset(), rcMovieFileFormat2::frameCount(), rcMovieFileFormat2::height(), rcMovieFileFormat2::rev(), rcMovieFileFormat2::rowUpdate(), and rcMovieFileFormat2::width().
 {
     os << "Hdr rev " << e.rev() << " BOM " << e.bom() << " width " << e.width()
        << " height " << e.height() << " depth " << e.depth()
        << " rowUpdate " << e.rowUpdate() << " frameCount " << e.frameCount()
        << " avgFrameRate " << e.averageFrameRate() << " baseTime " << rcTimestamp(e.baseTime())
        << " extOffset " << e.extensionOffset();
     return os;
 }
ostream& operator<< (ostream & os, const movieExtensionType & e)
Definition at line 847 of file rc_moviefileformat.cpp.
References movieExtensionCAM, movieExtensionCNV, movieExtensionEOF, movieExtensionEXP, movieExtensionORG, and movieExtensionTOC.
 {
     switch ( e ) {
         case movieExtensionEOF:
             os << "EOF";
             break;
         case movieExtensionTOC:
             os << "TOC";
             break;
         case movieExtensionORG:
             os << "ORG";
             break;
         case movieExtensionCNV:
             os << "CNV";
             break;
         case movieExtensionCAM:
             os << "CAM";
             break;
         case movieExtensionEXP:
             os << "EXP";
             break;
     }
     return os;
 }
ostream& operator<< (ostream & os, const movieOriginType & e)
Definition at line 815 of file rc_moviefileformat.cpp.
References movieOriginCaptureCertified, movieOriginCaptureUncertified, movieOriginConversionExt, movieOriginGrayIsVisibleAlphaIsFlu, movieOriginGrayPlusMultiChannelFlu, movieOriginMultiChannelFlu, movieOriginSynthetic, and movieOriginUnknown.
 {
     switch ( e ) {
     case movieOriginUnknown:
       os << "Unknown";
       break;
     case movieOriginCaptureUncertified:
       os << "Uncertified Reify Capture";
       break;
     case movieOriginCaptureCertified:
       os << "Certified Reify Capture";
       break;
     case movieOriginConversionExt:
       os << "Non-Reify Capture";
       break;
     case movieOriginSynthetic:
       os << "Synthetic";
       break;
     case movieOriginGrayIsVisibleAlphaIsFlu:
       os << "GrayIsVisibleAlphaIsFlu";
       break;
     case movieOriginMultiChannelFlu:
       os << "movieOriginMultiChannelFlu";
       break;
     case movieOriginGrayPlusMultiChannelFlu:
       os << "movieOriginGrayPlusMultiChannelFlu";
       break;
     }
     return os;
 }
ostream& operator<< (ostream & os, const movieChannelType & e)
Definition at line 873 of file rc_moviefileformat.cpp.
References movieChannelAll, movieChannelAvg, movieChannelBlue, movieChannelGreen, movieChannelMax, movieChannelRed, and movieChannelUnknown.
 {
     switch ( e ) {
         case movieChannelUnknown:
             os << "Unknown";
             break;
         case movieChannelAll:
             os << "All";
             break;
         case movieChannelAvg:
             os << "Avg";
             break;
         case movieChannelMax:
             os << "Max";
             break;
         case movieChannelRed:
             os << "Red";
             break;
         case movieChannelGreen:
             os << "Green";
             break;
         case movieChannelBlue:
             os << "Blue";
             break;
     }
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileExt & e)
Definition at line 902 of file rc_moviefileformat.cpp.
References rcMovieFileExt::offset(), and rcMovieFileExt::type().
 {
     os << "HdrExt " << e.type() << " offset " << e.offset();
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileTocExt & e)
Definition at line 909 of file rc_moviefileformat.cpp.
References rcMovieFileTocExt::count().
 {
     const rcMovieFileExt& base = e;
     os << base
        << " count " << e.count();
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileOrgExt & e)
Definition at line 918 of file rc_moviefileformat.cpp.
References rcMovieFileOrgExt::baseTime(), rcMovieFileOrgExt::creatorName(), rcMovieFileOrgExt::depth(), rcMovieFileOrgExt::frameCount(), rcMovieFileOrgExt::height(), rcMovieFileOrgExt::id(), rcMovieFileOrgExt::origin(), rcMovieFileOrgExt::rev(), and rcMovieFileOrgExt::width().
 {
     const rcMovieFileExt& base = e;
     os << base
        << " origin \"" << e.origin() << "\" baseTime " << rcTimestamp(e.baseTime())
        << " frameCount " << e.frameCount() << " depth " << e.depth()
        << " width " << e.width() << " height " << e.height()
        << " rev " << e.rev() << " generator \"" << e.creatorName() << "\""
        << " id " << e.id();
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileConvExt & e)
Definition at line 931 of file rc_moviefileformat.cpp.
References rcMovieFileConvExt::channel(), rcMovieFileConvExt::creatorName(), rcMovieFileConvExt::cropRect(), rcMovieFileConvExt::date(), rcMovieFileConvExt::frameCount(), rcMovieFileConvExt::frameInterval(), rcMovieFileConvExt::id(), rcMovieFileConvExt::pixelsReversed(), rcMovieFileConvExt::rev(), rcMovieFileConvExt::sample(), and rcMovieFileConvExt::startOffset().
 {
     const rcMovieFileExt& base = e;
     os << base
        << " formatRev " << e.rev()
        << " startOffset " << e.startOffset() << " frameCount " << e.frameCount() << " sample " << e.sample()
        << " cropRect " << e.cropRect() << " channel " << e.channel() << " frameInt " << e.frameInterval()
        << " pixelsReversed " << e.pixelsReversed()
        << " converter \"" << e.creatorName() << "\"" << " date " << rcTimestamp(e.date()).localtime()
        << " id " << e.id();
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileCamExt & e)
Definition at line 945 of file rc_moviefileformat.cpp.
References rcMovieFileCamExt::brightness(), rcMovieFileCamExt::cropRect(), endl(), rcMovieFileCamExt::exposure(), rcMovieFileCamExt::filter(), rcMovieFileCamExt::focus(), rcMovieFileCamExt::format(), rcMovieFileCamExt::frameRate(), rcMovieFileCamExt::gain(), rcMovieFileCamExt::gamma(), rcMovieFileCamExt::hue(), rcMovieFileCamExt::id(), rcMovieFileCamExt::iris(), rcMovieFileCamExt::mid(), rcMovieFileCamExt::mode(), rcMovieFileCamExt::name(), rcMovieFileCamExt::pan(), rcMovieFileCamExt::saturation(), rcMovieFileCamExt::sharpness(), rcMovieFileCamExt::shutter(), rcMovieFileCamExt::temperature(), rcMovieFileCamExt::uid(), rcMovieFileCamExt::whiteBalanceUB(), rcMovieFileCamExt::whiteBalanceVR(), and rcMovieFileCamExt::zoom().
 {
     const rcMovieFileExt& base = e;
     os << base
        << " name \"" << e.name() << "\"" << " mid " << e.mid() << " uid " << e.uid()
        << " format " << e.format() << " mode " << e.mode() << " maxFps " << e.frameRate()
        << " bright " << e.brightness() << " exp " << e.exposure() << " sharp " << e.sharpness()
        << " wBalUB " << e.whiteBalanceUB() << " wBalVR " << e.whiteBalanceVR()
        << " hue " << e.hue() << " sat " << e.saturation() << " gamma " << e.gamma()
        << " shutter " << e.shutter() << " gain " << e.gain() << " iris " << e.iris()
        << " focus " << e.focus() << " temp " << e.temperature() << " zoom " << e.zoom()
        << " pan " << e.pan() << " filter " << e.filter() << " crop " << e.cropRect()
        << " id " << e.id();
     os << endl;
     return os;
 }
ostream& operator<< (ostream & os, const rcMovieFileExpExt & e)
Definition at line 962 of file rc_moviefileformat.cpp.
References rcMovieFileExpExt::cellType(), rcMovieFileExpExt::CO2(), rcMovieFileExpExt::comment(), endl(), rcMovieFileExpExt::id(), rcMovieFileExpExt::imagingMode(), rcMovieFileExpExt::lensMag(), rcMovieFileExpExt::O2(), rcMovieFileExpExt::otherMag(), rcMovieFileExpExt::temperature(), rcMovieFileExpExt::title(), rcMovieFileExpExt::treatment1(), rcMovieFileExpExt::treatment2(), and rcMovieFileExpExt::userName().
 {
     const rcMovieFileExt& base = e;
     os << base
        << " title " << e.title() << " user " << e.userName()
        << " treat1 " << e.treatment1() << " treat2 " << e.treatment2()
        << " cell " << e.cellType() << " imgMode " << e.imagingMode()
        << " com " << e.comment()
        << " lensMag " << e.lensMag() << " oMag " << e.otherMag()
        << " temp " << e.temperature() << " CO2 " << e.CO2() << " O2 " << e.O2()
        << " id " << e.id();
     os << endl;
     return os;
 }