Visible: src/analysis/rc_lattice.cpp File Reference
rc_lattice.cpp File Reference
#include <rc_diamondscan.h>
#include <rc_numeric.h>
Classes
class rcDiamondSteps
scanning steps
class rcCrossSteps
scanning steps
Macros
#define rmPrintImage(a)
Functions
static void _exhaustiveImageFind (const rcWindow &moving, const rcWindow &fixed, const rcWindow &mask, rcFindList &locations, rcWindow &space)
void rfImageFind (const rcWindow &moving, const rcWindow &fixed, rcFindList &locations, rcWindow &space)
void rfImageFind (const rcWindow &moving, const rcWindow &fixed, const rcWindow &mask, rcFindList &locations, rcWindow &space, bool exhaustive)
Variables
static rcIPair sDiamond [9]
static rcIPair sCross [4] = {rcIPair (-1,0), rcIPair (0,-1), rcIPair (1,0), rcIPair (0,1)}
static const rcIPair sZeroIPair (rcNumericTraits< int >::Zero, rcNumericTraits< int >::Zero)
static const rcIPair sOneIPair (rcNumericTraits< int >::One, rcNumericTraits< int >::One)
static const rcIPair sTwoIPair = sOneIPair + sOneIPair
rcDiamondSteps sDiamondSteps
rcCrossSteps sCrossSteps
Macro Definition Documentation
#define rmPrintImage (a)
Value:
{                       \
for (int32 i__temp = 0; i__temp < (a).height(); i__temp++) {  \
fprintf (stderr, "\n");                     \
uint16* vp = (uint16*)(a).row_pointer(i__temp);         \
for (int32 j__temp = 0; j__temp < (a).width(); j__temp++)   \
{\
if (vp[j__temp] == rcPointScan::notProcessedLabel ()) fprintf (stderr, "  +  "); \
else \
fprintf (stderr, "%1.3f+", vp[j__temp] == rcPointScan::notProcessedLabel () ? -1.0 : vp[j__temp] / 65000.0f); \
}\
fprintf (stderr, "\n");                     \
}}
Definition at line 14 of file rc_lattice.cpp.
Referenced by _exhaustiveImageFind().
Function Documentation
static void _exhaustiveImageFind (const rcWindow & moving, const rcWindow & fixed, const rcWindow & mask, rcFindList & locations, rcWindow & space) static
Definition at line 130 of file rc_lattice.cpp.
References rcWindow::height(), rcWindow::isBound(), mQuantz, rcTimingInfo::nextPass(), rcWindow::pelPointer(), rcCorr::r(), rcPixel16, rfCorrelate(), rfDetectPeaks(), rmAssert, rmAssertDebug, rmPrintImage, rcWindow::set(), rcWindow::size(), rcTimingInfo::touch(), and rcWindow::width().
Referenced by rfImageFind().
 {
     int32 maxX (-1), maxY(-1);
     rc2Fvector interp;
     vector<float> score (9);
     bitset<4> edge;
     double maxScore (0.0);
     rsCorrParams cp;
     rcIPair step (1,0);
     rcTimingInfo profile (11, 2);
         // Size and create search space
     const rcIPair searchSpace (moving.width() - fixed.width() + 1,
                                moving.height() - fixed.height() + 1);
         // rcCorrelationWindow for the model
     rcWindow movingWin (moving, 0, 0, fixed.width(), fixed.height());
     profile.nextPass (true);
     profile.touch (0);
         // Correlation space. Pad by 2 since we do a 5x5 peak detection
         //@ note that crlf takes into account that space is padded
     static int32 cpad (2);
     rcWindow basespace (searchSpace.x()+cpad+cpad, searchSpace.y()+cpad+cpad, rcPixel16);
     basespace.set (0);
     rcWindow cspace (basespace, cpad, cpad, searchSpace.x(), searchSpace.y(), rcPixel16);
     profile.touch (1);
     const rcIPair colUpdate (1, 0);
     rcIPair row_update (-searchSpace.x(), 1);
     if (mask.isBound() && mask.size () == fixed.size ())
     {
           rmAssert (0);
     }
     else
     {
         uint32 curRow = 0;
         do {
             uint32 curCol = 0;
             do {
                 rcCorr res;
                 profile.touch (2);
                 rmAssertDebug (moving.pelPointer (curCol, curRow) == movingWin.pelPointer (0,0));
                 rfCorrelate (fixed, movingWin,res);
                 profile.touch (3);
                 const float r = res.r();
                 cspace.setPixel (curCol, curRow, (uint16) (mQuantz * r));
                 if (r > maxScore)
                 {
                     maxX = curCol, maxY = curRow, maxScore = r;
                 }
             } while (movingWin.translate(colUpdate) && ++curCol && curCol < searchSpace.x());
             row_update[0] = -curCol;
             curRow++;
         } while(movingWin.translate(row_update) && curRow < searchSpace.y());
         rmAssert(curRow == (searchSpace.y()));
         space = cspace;
     }
 #ifdef FINDEBUG
     rmPrintImage (space);
 #endif
         // Locate peaks in the correlation space
     rcFindList peaks;
         // If result is sized for one, then jus return the best (locally bettered)
         // we add the offset to basespace to match with what we get from the
         // peakDetect
     profile.touch (4);
     if (locations.size() == 1)
     {
         peaks.resize (1);
         rcFindList::iterator tmp = peaks.begin();
         rc2Fvector loc (maxX + cpad, maxY + cpad);
         tmp->interpolated (loc);
         tmp->score ( (uint16) (mQuantz * maxScore) );
     }
     else
     {
         uint16 accept (100);
         rfDetectPeaks (basespace, accept, peaks);
         locations.resize (peaks.size());
     }
     profile.touch (5);
         //@note: peaks are wrt to space passed in to rfDetectPeaks. In this case basespace
     rcFindList::iterator lTr = peaks.begin();
     for (uint32 i = 0; i < peaks.size(); i++, lTr++)
     {
     // Correct to be wrt cspace
     // 0 --> basespace.width() -1 ==> 2 --> basesace.width() - 3  ==> 0 --> cspace.width() - 1
       int32 maxX = lTr->interpolated().x() - cpad;
       int32 maxY = lTr->interpolated().y() - cpad;
           rc2Fvector position (maxX, maxY);
           int16 maxScore = lTr->score ();
       edge[0] = maxX < 0; edge[1] = maxX > (cspace.width() - 1);
       edge[2] = maxY < 0; edge[3] = maxY > (cspace.height() - 1);
       lTr->edges (edge);
       if (edge.none())
         {
           score[0] = cspace.getPixel (maxX-1,maxY-1)/ (float) mQuantz;
           score[1] = cspace.getPixel(maxX, maxY-1)/ (float) mQuantz;
           score[2] = cspace.getPixel(maxX+1, maxY-1)/ (float) mQuantz;
           score[3] = cspace.getPixel(maxX-1, maxY)/ (float) mQuantz;
           score[4] = cspace.getPixel(maxX, maxY)/ (float) mQuantz;
           score[5] = cspace.getPixel(maxX+1, maxY)/ (float) mQuantz;
           score[6] = cspace.getPixel(maxX-1, maxY+1)/ (float) mQuantz;
           score[7] = cspace.getPixel(maxX, maxY+1)/ (float) mQuantz;
           score[8] = cspace.getPixel(maxX+1, maxY+1)/ (float) mQuantz;
           position += interp;
         }
       // If the peak is on the edge of the match space, just return it
       lTr->score ( maxScore);
       lTr->interpolated(position);
     }
     profile.touch (9);
         // Resort. Some peaks might have improved
         // Sort and put the highest first
     peaks.sort();
     peaks.reverse();
     rcFindList::iterator rTr = locations.begin();
     lTr = peaks.begin();
     for (uint32 i = 0; i < peaks.size(); i++, lTr++, rTr++)
     {
         *rTr = *lTr;
     }
 }
void rfImageFind (const rcWindow & moving, const rcWindow & fixed, rcFindList & locations, rcWindow & space)
Definition at line 107 of file rc_lattice.cpp.
References _exhaustiveImageFind().
 {
     rcWindow noMask;
     _exhaustiveImageFind (moving, fixed, noMask, locations, space);
 }
void rfImageFind (const rcWindow & moving, const rcWindow & fixed, const rcWindow & mask, rcFindList & locations, rcWindow & space, bool exhaustive)
Definition at line 117 of file rc_lattice.cpp.
References _exhaustiveImageFind(), and rmAssert.
 {
     if (exhaustive)
         return _exhaustiveImageFind (moving, fixed, mask, locations, space);
     {
       rmAssert (0);
     }
 }
Variable Documentation
rcIPair sCross[4] = {rcIPair (-1,0), rcIPair (0,-1), rcIPair (1,0), rcIPair (0,1)} static
Definition at line 49 of file rc_lattice.cpp.
rcCrossSteps sCrossSteps
Definition at line 99 of file rc_lattice.cpp.
rcIPair sDiamond[9] static
Initial value:
= {rcIPair (0,0), rcIPair(2,0), rcIPair (1,1), rcIPair (0,2),rcIPair (-1,1),
    rcIPair (-2,0), rcIPair (-1,-1), rcIPair (0,-2), rcIPair (1,-1)}
Definition at line 47 of file rc_lattice.cpp.
rcDiamondSteps sDiamondSteps
Definition at line 98 of file rc_lattice.cpp.
const rcIPair sOneIPair(rcNumericTraits< int >::One, rcNumericTraits< int >::One) static
const rcIPair sTwoIPair = sOneIPair + sOneIPair static
Definition at line 53 of file rc_lattice.cpp.
const rcIPair sZeroIPair(rcNumericTraits< int >::Zero, rcNumericTraits< int >::Zero) static