Visible: include/visual/rc_movieconverter.h File Reference
rc_movieconverter.h File Reference
#include <QuickTime/QuickTime.h>
#include <rc_qtime.h>
#include <rc_gen_movie_file.h>
#include <rc_moviegrabber.h>
Classes
class rcMovieConverterOptions
class rcMovieConverterOptionsRfy
class rcMovieConverterOptionsQT
class rcMovieConverter
class rcMovieConverterToQT
class rcMovieConverterToRfy
Enumerations
enum rcMovieConverterError {
eMovieConverterErrorOK = 0, eMovieConverterErrorUnknown, eMovieConverterErrorInternal, eMovieConverterErrorNull,
eMovieConverterErrorHeaderWrite, eMovieConverterErrorExists, eMovieConverterErrorOpen, eMovieConverterErrorRead,
eMovieConverterErrorWrite, eMovieConverterErrorWriteOpen, eMovieConverterErrorSeek, eMovieConverterErrorClose,
eMovieConverterErrorFlush, eMovieConverterErrorUnsupported
}
Functions
ostream & operator<< (ostream &o, const rcMovieConverterOptions &opt)
ostream & operator<< (ostream &o, const rcMovieConverterOptionsRfy &opt)
ostream & operator<< (ostream &o, const rcMovieConverterOptionsQT &opt)
Enumeration Type Documentation
enum rcMovieConverterError
Enumerator
eMovieConverterErrorOK
eMovieConverterErrorUnknown
eMovieConverterErrorInternal
eMovieConverterErrorNull
eMovieConverterErrorHeaderWrite
eMovieConverterErrorExists
eMovieConverterErrorOpen
eMovieConverterErrorRead
eMovieConverterErrorWrite
eMovieConverterErrorWriteOpen
eMovieConverterErrorSeek
eMovieConverterErrorClose
eMovieConverterErrorFlush
eMovieConverterErrorUnsupported
Definition at line 19 of file rc_movieconverter.h.
{
   eMovieConverterErrorOK = 0,
   eMovieConverterErrorUnknown,
   eMovieConverterErrorInternal,
   eMovieConverterErrorNull,
   eMovieConverterErrorHeaderWrite,
   eMovieConverterErrorExists,
   eMovieConverterErrorOpen,
   eMovieConverterErrorRead,
   eMovieConverterErrorWrite,
   eMovieConverterErrorWriteOpen,
   eMovieConverterErrorSeek,
   eMovieConverterErrorClose,
   eMovieConverterErrorFlush,
   eMovieConverterErrorUnsupported
 };
Function Documentation
ostream& operator<< (ostream & o, const rcMovieConverterOptions & opt)
Definition at line 1199 of file rc_movieconverter.cpp.
References rcMovieConverterOptions::creator(), endl(), rcMovieConverterOptions::firstFrameIndex(), rcMovieConverterOptions::frameCount(), rcMovieConverterOptions::frameInterval(), rcMovieConverterOptions::frameOffset(), rcMovieConverterOptions::overWrite(), and rcMovieConverterOptions::samplePeriod().
 {
     o << "FrameInterval:   " << opt.frameInterval() << endl;
     o << "FirstFrameIndex: " << opt.firstFrameIndex() << endl;
     o << "FrameCount:      " << opt.frameCount() << endl;
     o << "FrameOffset:     " << opt.frameOffset() << endl;
     o << "SamplePeriod:    " << opt.samplePeriod() << endl;
     o << "OverWrite:       " << opt.overWrite() << endl;
     o << "Creator:         " << opt.creator() << endl;
     return o;
 }
ostream& operator<< (ostream & o, const rcMovieConverterOptionsRfy & opt)
Definition at line 1212 of file rc_movieconverter.cpp.
References rcMovieConverterOptionsRfy::channelConversion(), endl(), rcMovieConverterOptionsRfy::rev(), and rcMovieConverterOptions::reversePixels().
 {
     const rcMovieConverterOptions& baseOpt = opt;
     o << baseOpt;
     o << "ChannelConversion: " << opt.channelConversion() << endl;
     o << "ReversePixels:     " << opt.reversePixels() << endl;
     o << "FileRev:           " << opt.rev() << endl;
     return o;
 }
ostream& operator<< (ostream & o, const rcMovieConverterOptionsQT & opt)
Definition at line 1223 of file rc_movieconverter.cpp.
 {
     const rcMovieConverterOptions& baseOpt = opt;
     o << baseOpt;
     return o;
 }