Visible: src/visual/code/rc_histstats.cpp File Reference
rc_histstats.cpp File Reference
#include <rc_histstats.h>
#include <math.h>
#include <rc_math.h>
#include <rc_windowhist.h>
#include <Carbon/Carbon.h>
Functions
ostream & operator<< (ostream &o, const rcHistoStats &p)
Function Documentation
ostream& operator<< (ostream & o, const rcHistoStats & p)
Definition at line 9 of file rc_histstats.cpp.
References rcHistoStats::bins(), endl(), rcHistoStats::histogram(), rcHistoStats::max(), rcHistoStats::mean(), rcHistoStats::median(), rcHistoStats::min(), and rcHistoStats::n().
 {
     o << "{" << endl << "Mean: " << p.mean() << ",Median  " << p.median() <<
       "Min:  " << p.min() << "Max: " << p.max() << "Bins " << p.bins () << endl;
     uint32 i = 0;
     if (p.n())
       {
     while (i < p.bins ())
       {
         uint32 pd (p.histogram()[i]);
         if (pd)
           {
         cerr << "[" << i << "]: " << pd << "," << (float) pd / (float) p.n() << endl;
           }
         i++;
       }
       }
     return o;
 }