Visible: src/analysis/code/rc_motionpath.cpp File Reference
rc_motionpath.cpp File Reference
#include <rc_kinetoscope.h>
#include <rc_fit.h>
#include <iomanip.h>
#include <rc_altivecutil.h>
#include <rc_analysis.h>
Macros
#define defineMatchFunction(name, pelType, pelTypePtr)
Functions
ostream & operator<< (ostream &o, const rcMotionVectorPath &p)
Macro Definition Documentation
#define defineMatchFunction (name, pelType, pelTypePtr)
Definition at line 451 of file rc_motionpath.cpp.
Function Documentation
ostream& operator<< (ostream & o, const rcMotionVectorPath & p)
Definition at line 374 of file rc_motionpath.cpp.
References rcMotionVectorPath::anchor(), endl(), and rcMotionVectorPath::motion().
 {
     o << "--------------------------" << endl;
     o << "Trace    :" << p.motion() << endl;
     o << "Anchor   :" << p.anchor() << endl;
     //  o << "Siblings :" << p.sharedKin()->refCount () << endl;
     o << "--------------------------" << endl;
     return o;
 }