Visible: include/util/ringbuffer.h File Reference
ringbuffer.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "ringbuffer.h"
#include <string.h>
Classes
struct RingBuffer
Functions
long RingBuffer_Init (RingBuffer *rbuf, long numBytes, void *dataPtr)
void RingBuffer_Flush (RingBuffer *rbuf)
long RingBuffer_GetWriteAvailable (RingBuffer *rbuf)
long RingBuffer_GetReadAvailable (RingBuffer *rbuf)
long RingBuffer_Write (RingBuffer *rbuf, void *data, long numBytes)
long RingBuffer_Read (RingBuffer *rbuf, void *data, long numBytes)
long RingBuffer_GetWriteRegions (RingBuffer *rbuf, long numBytes, void **dataPtr1, long *sizePtr1, void **dataPtr2, long *sizePtr2)
long RingBuffer_AdvanceWriteIndex (RingBuffer *rbuf, long numBytes)
long RingBuffer_GetReadRegions (RingBuffer *rbuf, long numBytes, void **dataPtr1, long *sizePtr1, void **dataPtr2, long *sizePtr2)
long RingBuffer_AdvanceReadIndex (RingBuffer *rbuf, long numBytes)
Function Documentation
long RingBuffer_AdvanceReadIndex (RingBuffer * rbuf, long numBytes)
Definition at line 153 of file ringbuffer.c.
References RingBuffer::bigMask, and RingBuffer::readIndex.
Referenced by RingBuffer_Read().
 {
     return rbuf->readIndex = (rbuf->readIndex + numBytes) & rbuf->bigMask;
 }
long RingBuffer_AdvanceWriteIndex (RingBuffer * rbuf, long numBytes)
Definition at line 113 of file ringbuffer.c.
References RingBuffer::bigMask, and RingBuffer::writeIndex.
Referenced by RingBuffer_Write().
 {
     return rbuf->writeIndex = (rbuf->writeIndex + numBytes) & rbuf->bigMask;
 }
void RingBuffer_Flush (RingBuffer * rbuf)
Definition at line 71 of file ringbuffer.c.
References RingBuffer::readIndex, and RingBuffer::writeIndex.
Referenced by RingBuffer_Init().
 {
     rbuf->writeIndex = rbuf->readIndex = 0;
 }
long RingBuffer_GetReadAvailable (RingBuffer * rbuf)
Definition at line 58 of file ringbuffer.c.
References RingBuffer::bigMask, RingBuffer::readIndex, and RingBuffer::writeIndex.
Referenced by RingBuffer_GetReadRegions(), and RingBuffer_GetWriteAvailable().
 {
     return ( (rbuf->writeIndex - rbuf->readIndex) & rbuf->bigMask );
 }
long RingBuffer_GetReadRegions (RingBuffer * rbuf, long numBytes, void ** dataPtr1, long * sizePtr1, void ** dataPtr2, long * sizePtr2)
Definition at line 124 of file ringbuffer.c.
References RingBuffer::buffer, RingBuffer::bufferSize, NULL, RingBuffer::readIndex, RingBuffer_GetReadAvailable(), and RingBuffer::smallMask.
Referenced by RingBuffer_Read().
 {
     long   index;
     long   available = RingBuffer_GetReadAvailable( rbuf );
     if( numBytes > available ) numBytes = available;
     /* Check to see if read is not contiguous. */
     index = rbuf->readIndex & rbuf->smallMask;
     if( (index + numBytes) > rbuf->bufferSize )
     {
         /* Write data in two blocks that wrap the buffer. */
         long firstHalf = rbuf->bufferSize - index;
         *dataPtr1 = &rbuf->buffer[index];
         *sizePtr1 = firstHalf;
         *dataPtr2 = &rbuf->buffer[0];
         *sizePtr2 = numBytes - firstHalf;
     }
     else
     {
         *dataPtr1 = &rbuf->buffer[index];
         *sizePtr1 = numBytes;
         *dataPtr2 = NULL;
         *sizePtr2 = 0;
     }
     return numBytes;
 }
long RingBuffer_GetWriteAvailable (RingBuffer * rbuf)
Definition at line 64 of file ringbuffer.c.
References RingBuffer::bufferSize, and RingBuffer_GetReadAvailable().
Referenced by RingBuffer_GetWriteRegions().
 {
     return ( rbuf->bufferSize - RingBuffer_GetReadAvailable(rbuf));
 }
long RingBuffer_GetWriteRegions (RingBuffer * rbuf, long numBytes, void ** dataPtr1, long * sizePtr1, void ** dataPtr2, long * sizePtr2)
Definition at line 82 of file ringbuffer.c.
References RingBuffer::buffer, RingBuffer::bufferSize, NULL, RingBuffer_GetWriteAvailable(), RingBuffer::smallMask, and RingBuffer::writeIndex.
Referenced by RingBuffer_Write().
 {
     long   index;
     long   available = RingBuffer_GetWriteAvailable( rbuf );
     if( numBytes > available ) numBytes = available;
     /* Check to see if write is not contiguous. */
     index = rbuf->writeIndex & rbuf->smallMask;
     if( (index + numBytes) > rbuf->bufferSize )
     {
         /* Write data in two blocks that wrap the buffer. */
         long   firstHalf = rbuf->bufferSize - index;
         *dataPtr1 = &rbuf->buffer[index];
         *sizePtr1 = firstHalf;
         *dataPtr2 = &rbuf->buffer[0];
         *sizePtr2 = numBytes - firstHalf;
     }
     else
     {
         *dataPtr1 = &rbuf->buffer[index];
         *sizePtr1 = numBytes;
         *dataPtr2 = NULL;
         *sizePtr2 = 0;
     }
     return numBytes;
 }
long RingBuffer_Init (RingBuffer * rbuf, long numBytes, void * dataPtr)
Definition at line 46 of file ringbuffer.c.
References RingBuffer::bigMask, RingBuffer::buffer, RingBuffer::bufferSize, RingBuffer_Flush(), and RingBuffer::smallMask.
 {
     if( ((numBytes-1) & numBytes) != 0) return -1; /* Not Power of two. */
     rbuf->bufferSize = numBytes;
     rbuf->buffer = (char *)dataPtr;
     RingBuffer_Flush( rbuf );
     rbuf->bigMask = (numBytes*2)-1;
     rbuf->smallMask = (numBytes)-1;
     return 0;
 }
long RingBuffer_Read (RingBuffer * rbuf, void * data, long numBytes)
Definition at line 182 of file ringbuffer.c.
References RingBuffer_AdvanceReadIndex(), and RingBuffer_GetReadRegions().
 {
     long size1, size2, numRead;
     void *data1, *data2;
     numRead = RingBuffer_GetReadRegions( rbuf, numBytes, &data1, &size1, &data2, &size2 );
     if( size2 > 0 )
     {
         memcpy( data, data1, size1 );
         data = ((char *)data) + size1;
         memcpy( data, data2, size2 );
     }
     else
     {
         memcpy( data, data1, size1 );
     }
     RingBuffer_AdvanceReadIndex( rbuf, numRead );
     return numRead;
 }
long RingBuffer_Write (RingBuffer * rbuf, void * data, long numBytes)
Definition at line 160 of file ringbuffer.c.
References RingBuffer_AdvanceWriteIndex(), and RingBuffer_GetWriteRegions().
 {
     long size1, size2, numWritten;
     void *data1, *data2;
     numWritten = RingBuffer_GetWriteRegions( rbuf, numBytes, &data1, &size1, &data2, &size2 );
     if( size2 > 0 )
     {
         memcpy( data1, data, size1 );
         data = ((char *)data) + size1;
         memcpy( data2, data, size2 );
     }
     else
     {
         memcpy( data1, data, size1 );
     }
     RingBuffer_AdvanceWriteIndex( rbuf, numWritten );
     return numWritten;
 }