Visible: include/stlplus/smart_ptr.hpp File Reference
smart_ptr.hpp File Reference
#include "os_fixes.hpp"
#include "exceptions.hpp"
#include "persistent.hpp"
#include "textio.hpp"
#include <map>
#include <string>
#include "smart_ptr.tpp"
Classes
class simple_ptr< T >
class simple_ptr_clone< T >
class simple_ptr_nocopy< T >
class smart_ptr_holder< T >
class smart_ptr< T >
class smart_ptr_clone< T >
class smart_ptr_nocopy< T >
Functions
template<typename T >
bool operator== (const simple_ptr< T > &, const simple_ptr< T > &)
template<typename T >
bool operator< (const simple_ptr< T > &, const simple_ptr< T > &)
template<typename T >
std::string simple_ptr_to_string (const simple_ptr< T > &ptr, std::string null_string)
template<typename T >
otext & print_simple_ptr (otext &str, const simple_ptr< T > &ptr, std::string null_string)
template<typename T >
otext & print_simple_ptr (otext &str, const simple_ptr< T > &ptr, unsigned indent, std::string null_string)
template<typename T >
void dump_simple_ptr (dump_context &str, const simple_ptr< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_simple_ptr (restore_context &str, simple_ptr< T > &data) throw (persistent_restore_failed)
template<typename T >
bool operator== (const simple_ptr_clone< T > &, const simple_ptr_clone< T > &)
template<typename T >
bool operator< (const simple_ptr_clone< T > &, const simple_ptr_clone< T > &)
template<typename T >
std::string simple_ptr_clone_to_string (const simple_ptr_clone< T > &ptr, std::string null_string)
template<typename T >
otext & print_simple_ptr_clone (otext &str, const simple_ptr_clone< T > &ptr, std::string null_string)
template<typename T >
otext & print_simple_ptr_clone (otext &str, const simple_ptr_clone< T > &ptr, unsigned indent, std::string null_string)
template<typename T >
void dump_simple_ptr_clone (dump_context &str, const simple_ptr_clone< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_simple_ptr_clone (restore_context &str, simple_ptr_clone< T > &data) throw (persistent_restore_failed)
template<typename T >
bool operator== (const simple_ptr_nocopy< T > &, const simple_ptr_nocopy< T > &)
template<typename T >
bool operator< (const simple_ptr_nocopy< T > &, const simple_ptr_nocopy< T > &)
template<typename T >
std::string simple_ptr_nocopy_to_string (const simple_ptr_nocopy< T > &ptr, std::string null_string)
template<typename T >
otext & print_simple_ptr_nocopy (otext &str, const simple_ptr_nocopy< T > &ptr, std::string null_string)
template<typename T >
otext & print_simple_ptr_nocopy (otext &str, const simple_ptr_nocopy< T > &ptr, unsigned indent, std::string null_string)
template<typename T >
bool operator== (const smart_ptr< T > &, const smart_ptr< T > &)
template<typename T >
bool operator< (const smart_ptr< T > &, const smart_ptr< T > &)
template<typename T >
std::string smart_ptr_to_string (const smart_ptr< T > &ptr, std::string null_string)
template<typename T >
otext & print_smart_ptr (otext &str, const smart_ptr< T > &ptr, std::string null_string)
template<typename T >
otext & print_smart_ptr (otext &str, const smart_ptr< T > &ptr, unsigned indent, std::string null_string)
template<typename T >
void dump_smart_ptr (dump_context &str, const smart_ptr< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_smart_ptr (restore_context &str, smart_ptr< T > &data) throw (persistent_restore_failed)
template<typename T >
bool operator== (const smart_ptr_clone< T > &, const smart_ptr_clone< T > &)
template<typename T >
bool operator< (const smart_ptr_clone< T > &, const smart_ptr_clone< T > &)
template<typename T >
std::string smart_ptr_clone_to_string (const smart_ptr_clone< T > &ptr, std::string null_string)
template<typename T >
otext & print_smart_ptr_clone (otext &str, const smart_ptr_clone< T > &ptr, std::string null_string)
template<typename T >
otext & print_smart_ptr_clone (otext &str, const smart_ptr_clone< T > &ptr, unsigned indent, std::string null_string)
template<typename T >
void dump_smart_ptr_clone (dump_context &str, const smart_ptr_clone< T > &data) throw (persistent_dump_failed)
template<typename T >
void restore_smart_ptr_clone (restore_context &str, smart_ptr_clone< T > &data) throw (persistent_restore_failed)
template<typename T >
bool operator== (const smart_ptr_nocopy< T > &, const smart_ptr_nocopy< T > &)
template<typename T >
bool operator< (const smart_ptr_nocopy< T > &, const smart_ptr_nocopy< T > &)
template<typename T >
std::string smart_ptr_nocopy_to_string (const smart_ptr_nocopy< T > &ptr, std::string null_string)
template<typename T >
otext & print_smart_ptr_nocopy (otext &str, const smart_ptr_nocopy< T > &ptr, std::string null_string)
template<typename T >
otext & print_smart_ptr_nocopy (otext &str, const smart_ptr_nocopy< T > &ptr, unsigned indent, std::string null_string)
Function Documentation
template<typename T > void dump_simple_ptr (dump_context & str, const simple_ptr< T > & data) throw (persistent_dump_failed)
template<typename T > void dump_simple_ptr_clone (dump_context & str, const simple_ptr_clone< T > & data) throw (persistent_dump_failed)
template<typename T > void dump_smart_ptr (dump_context & str, const smart_ptr< T > & data) throw (persistent_dump_failed)
Referenced by dump().
template<typename T > void dump_smart_ptr_clone (dump_context & str, const smart_ptr_clone< T > & data) throw (persistent_dump_failed)
template<typename T > bool operator< (const simple_ptr< T > & , const simple_ptr< T > &)
template<typename T > bool operator< (const simple_ptr_clone< T > & , const simple_ptr_clone< T > &)
template<typename T > bool operator< (const simple_ptr_nocopy< T > & , const simple_ptr_nocopy< T > &)
template<typename T > bool operator< (const smart_ptr< T > & , const smart_ptr< T > &)
template<typename T > bool operator< (const smart_ptr_clone< T > & , const smart_ptr_clone< T > &)
template<typename T > bool operator< (const smart_ptr_nocopy< T > & , const smart_ptr_nocopy< T > &)
template<typename T > bool operator== (const simple_ptr< T > & , const simple_ptr< T > &)
template<typename T > bool operator== (const simple_ptr_clone< T > & , const simple_ptr_clone< T > &)
template<typename T > bool operator== (const simple_ptr_nocopy< T > & , const simple_ptr_nocopy< T > &)
template<typename T > bool operator== (const smart_ptr< T > & , const smart_ptr< T > &)
template<typename T > bool operator== (const smart_ptr_clone< T > & , const smart_ptr_clone< T > &)
template<typename T > bool operator== (const smart_ptr_nocopy< T > & , const smart_ptr_nocopy< T > &)
template<typename T > otext& print_simple_ptr (otext & str, const simple_ptr< T > & ptr, std::string null_string)
template<typename T > otext& print_simple_ptr (otext & str, const simple_ptr< T > & ptr, unsigned indent, std::string null_string)
template<typename T > otext& print_simple_ptr_clone (otext & str, const simple_ptr_clone< T > & ptr, std::string null_string)
template<typename T > otext& print_simple_ptr_clone (otext & str, const simple_ptr_clone< T > & ptr, unsigned indent, std::string null_string)
template<typename T > otext& print_simple_ptr_nocopy (otext & str, const simple_ptr_nocopy< T > & ptr, std::string null_string)
template<typename T > otext& print_simple_ptr_nocopy (otext & str, const simple_ptr_nocopy< T > & ptr, unsigned indent, std::string null_string)
template<typename T > otext& print_smart_ptr (otext & str, const smart_ptr< T > & ptr, std::string null_string)
Referenced by print().
template<typename T > otext& print_smart_ptr (otext & str, const smart_ptr< T > & ptr, unsigned indent, std::string null_string)
template<typename T > otext& print_smart_ptr_clone (otext & str, const smart_ptr_clone< T > & ptr, std::string null_string)
template<typename T > otext& print_smart_ptr_clone (otext & str, const smart_ptr_clone< T > & ptr, unsigned indent, std::string null_string)
template<typename T > otext& print_smart_ptr_nocopy (otext & str, const smart_ptr_nocopy< T > & ptr, std::string null_string)
template<typename T > otext& print_smart_ptr_nocopy (otext & str, const smart_ptr_nocopy< T > & ptr, unsigned indent, std::string null_string)
template<typename T > void restore_simple_ptr (restore_context & str, simple_ptr< T > & data) throw (persistent_restore_failed)
template<typename T > void restore_simple_ptr_clone (restore_context & str, simple_ptr_clone< T > & data) throw (persistent_restore_failed)
template<typename T > void restore_smart_ptr (restore_context & str, smart_ptr< T > & data) throw (persistent_restore_failed)
Referenced by restore().
template<typename T > void restore_smart_ptr_clone (restore_context & str, smart_ptr_clone< T > & data) throw (persistent_restore_failed)
template<typename T > std::string simple_ptr_clone_to_string (const simple_ptr_clone< T > & ptr, std::string null_string)
template<typename T > std::string simple_ptr_nocopy_to_string (const simple_ptr_nocopy< T > & ptr, std::string null_string)
template<typename T > std::string simple_ptr_to_string (const simple_ptr< T > & ptr, std::string null_string)
template<typename T > std::string smart_ptr_clone_to_string (const smart_ptr_clone< T > & ptr, std::string null_string)
template<typename T > std::string smart_ptr_nocopy_to_string (const smart_ptr_nocopy< T > & ptr, std::string null_string)
template<typename T > std::string smart_ptr_to_string (const smart_ptr< T > & ptr, std::string null_string)