Visible: include/stlplus/string_arithmetic.hpp File Reference
string_arithmetic.hpp File Reference
#include "os_fixes.hpp"
#include "inf.hpp"
#include <string>
Functions
std::string bitwise_resize (const std::string &argument, unsigned size=0, char pad= '0')
bool bitwise_equality (const std::string &left, const std::string &right)
bool bitwise_inequality (const std::string &left, const std::string &right)
std::string bitwise_not (const std::string &argument)
std::string bitwise_and (const std::string &left, const std::string &right)
std::string bitwise_nand (const std::string &left, const std::string &right)
std::string bitwise_or (const std::string &left, const std::string &right)
std::string bitwise_nor (const std::string &left, const std::string &right)
std::string bitwise_xor (const std::string &left, const std::string &right)
std::string bitwise_xnor (const std::string &left, const std::string &right)
std::string bitwise_shift_left (const std::string &argument, unsigned shift)
std::string bitwise_shift_right (const std::string &argument, unsigned shift)
std::string bitwise_rotate_left (const std::string &argument, unsigned shift)
std::string bitwise_rotate_right (const std::string &argument, unsigned shift)
std::string unsigned_resize (const std::string &argument, unsigned size=0)
bool unsigned_equality (const std::string &left, const std::string &right)
bool unsigned_inequality (const std::string &left, const std::string &right)
bool unsigned_less_than (const std::string &left, const std::string &right)
bool unsigned_less_than_or_equal (const std::string &left, const std::string &right)
bool unsigned_greater_than (const std::string &left, const std::string &right)
bool unsigned_greater_than_or_equal (const std::string &left, const std::string &right)
std::string unsigned_add (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_subtract (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_multiply (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_exponent (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_divide (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_modulus (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_remainder (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_not (const std::string &argument, unsigned size=0)
std::string unsigned_and (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_nand (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_or (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_nor (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_xor (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_xnor (const std::string &left, const std::string &right, unsigned size=0)
std::string unsigned_shift_left (const std::string &argument, unsigned shift, unsigned size=0)
std::string unsigned_shift_right (const std::string &argument, unsigned shift, unsigned size=0)
unsigned long unsigned_to_ulong (const std::string &argument)
inf unsigned_to_inf (const std::string &argument)
std::string ulong_to_unsigned (unsigned long argument, unsigned size=0)
std::string inf_to_unsigned (inf argument, unsigned size=0)
std::string signed_resize (const std::string &argument, unsigned size=0)
bool is_negative (const std::string &argument)
bool is_natural (const std::string &argument)
bool is_positive (const std::string &argument)
bool is_zero (const std::string &argument)
bool signed_equality (const std::string &left, const std::string &right)
bool signed_inequality (const std::string &left, const std::string &right)
bool signed_less_than (const std::string &left, const std::string &right)
bool signed_less_than_or_equal (const std::string &left, const std::string &right)
bool signed_greater_than (const std::string &left, const std::string &right)
bool signed_greater_than_or_equal (const std::string &left, const std::string &right)
std::string signed_negate (const std::string &argument, unsigned size=0)
std::string signed_abs (const std::string &argument, unsigned size=0)
std::string signed_add (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_subtract (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_multiply (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_exponent (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_divide (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_modulus (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_remainder (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_not (const std::string &argument, unsigned size=0)
std::string signed_and (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_nand (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_or (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_nor (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_xor (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_xnor (const std::string &left, const std::string &right, unsigned size=0)
std::string signed_shift_left (const std::string &argument, unsigned shift, unsigned size=0)
std::string signed_shift_right (const std::string &argument, unsigned shift, unsigned size=0)
long signed_to_long (const std::string &argument)
inf signed_to_inf (const std::string &argument)
std::string long_to_signed (long argument, unsigned size=0)
std::string inf_to_signed (inf argument, unsigned size=0)
Function Documentation
std::string bitwise_and (const std::string & left, const std::string & right)
Definition at line 146 of file string_arithmetic.cpp.
References bit_and().
Referenced by bitwise_nand(), signed_and(), and unsigned_and().
 {
   unsigned size = std::max(left.size(),right.size());
   std::string result;
   for (unsigned i = 0; i < size; i++)
     result += bit_and(i < left.size() ? left[i] : '0', i < right.size() ? right[i] : '0');
   return result;
 }
bool bitwise_equality (const std::string & left, const std::string & right)
Definition at line 125 of file string_arithmetic.cpp.
Referenced by bitwise_inequality().
 {
   return left == right;
 }
bool bitwise_inequality (const std::string & left, const std::string & right)
Definition at line 130 of file string_arithmetic.cpp.
References bitwise_equality().
 {
   return !bitwise_equality(left, right);
 }
std::string bitwise_nand (const std::string & left, const std::string & right)
Definition at line 155 of file string_arithmetic.cpp.
References bitwise_and(), and bitwise_not().
Referenced by signed_nand(), and unsigned_nand().
 {
   return bitwise_not(bitwise_and(left,right));
 }
std::string bitwise_nor (const std::string & left, const std::string & right)
Definition at line 169 of file string_arithmetic.cpp.
References bitwise_not(), and bitwise_or().
Referenced by signed_nor(), and unsigned_nor().
 {
   return bitwise_not(bitwise_or(left,right));
 }
std::string bitwise_not (const std::string & argument)
Definition at line 137 of file string_arithmetic.cpp.
References bit_not().
Referenced by bitwise_nand(), bitwise_nor(), bitwise_xnor(), signed_not(), and unsigned_not().
 {
   unsigned size = argument.size();
   std::string result;
   for (unsigned i = 0; i < size; i++)
     result += bit_not(argument[i]);
   return result;
 }
std::string bitwise_or (const std::string & left, const std::string & right)
Definition at line 160 of file string_arithmetic.cpp.
References bit_or().
Referenced by bitwise_nor(), signed_or(), and unsigned_or().
 {
   unsigned size = std::max(left.size(),right.size());
   std::string result;
   for (unsigned i = 0; i < size; i++)
     result += bit_or(i < left.size() ? left[i] : '0', i < right.size() ? right[i] : '0');
   return result;
 }
std::string bitwise_resize (const std::string & argument, unsigned size = 0, char pad = '0')
Definition at line 106 of file string_arithmetic.cpp.
References pad().
 {
   std::string value = argument;
   // resize has two functions:
   if (size > value.size())
   {
     // - zero extend when a greater size specified
     value.insert((std::string::size_type)0u,size-value.size(),pad);
   }
   else if (size < value.size())
   {
     // - truncate when a smaller size specified
     value.erase((std::string::size_type)0u,value.size()-size);
   }
   return value;
 }
std::string bitwise_rotate_left (const std::string & argument, unsigned shift)
Definition at line 210 of file string_arithmetic.cpp.
 {
   // reduce the rotate distance to less than the argument length
   shift %= argument.size();
   return argument.substr(shift, argument.size()-shift) + argument.substr(0, shift);
 }
std::string bitwise_rotate_right (const std::string & argument, unsigned shift)
Definition at line 217 of file string_arithmetic.cpp.
 {
   // reduce the rotate distance to less than the argument length
   shift %= argument.size();
   return argument.substr(argument.size()-shift, shift) + argument.substr(0, argument.size()-shift);
 }
std::string bitwise_shift_left (const std::string & argument, unsigned shift)
Definition at line 190 of file string_arithmetic.cpp.
Referenced by signed_shift_left(), and unsigned_shift_left().
 {
   std::string result = argument;
   if (shift) result.append(shift,'0');
   return result;
 }
std::string bitwise_shift_right (const std::string & argument, unsigned shift)
Definition at line 197 of file string_arithmetic.cpp.
Referenced by signed_shift_right(), and unsigned_shift_right().
 {
   std::string result = argument;
   if (shift)
   {
     if (shift >= result.size())
       result = std::string();
     else
       result.erase(result.size()-shift,shift);
   }
   return result;
 }
std::string bitwise_xnor (const std::string & left, const std::string & right)
Definition at line 183 of file string_arithmetic.cpp.
References bitwise_not(), and bitwise_xor().
Referenced by signed_xnor(), and unsigned_xnor().
 {
   return bitwise_not(bitwise_xor(left,right));
 }
std::string bitwise_xor (const std::string & left, const std::string & right)
Definition at line 174 of file string_arithmetic.cpp.
References bit_xor().
Referenced by bitwise_xnor(), signed_xor(), and unsigned_xor().
 {
   unsigned size = std::max(left.size(),right.size());
   std::string result;
   for (unsigned i = 0; i < size; i++)
     result += bit_xor(i < left.size() ? left[i] : '0', i < right.size() ? right[i] : '0');
   return result;
 }
std::string inf_to_signed (inf argument, unsigned size = 0)
Definition at line 804 of file string_arithmetic.cpp.
References inf::negative(), inf::non_zero(), signed_not(), and signed_resize().
 {
   bool negative = argument.negative();
   if (negative) argument = -(argument+inf(1));
   std::string result = "";
   while(argument.non_zero())
   {
     result.insert((std::string::size_type)0u,1u,((argument % inf(2)).non_zero() ? '1' : '0'));
     argument /= inf(2);
   }
   result.insert((std::string::size_type)0u,1u,'0');
   if (negative) result = signed_not(result);
   return signed_resize(result,size);
 }
std::string inf_to_unsigned (inf argument, unsigned size = 0)
Definition at line 481 of file string_arithmetic.cpp.
References DEBUG_ASSERT, inf::natural(), inf::non_zero(), and unsigned_resize().
 {
   DEBUG_ASSERT(argument.natural());
   std::string result = argument.non_zero() ? "" : "0";
   while(argument.non_zero())
   {
     result.insert((std::string::size_type)0u,1u,((argument % inf(2)).non_zero() ? '1' : '0'));
     argument /= inf(2);
   }
   return unsigned_resize(result,size);
 }
bool is_natural (const std::string & argument)
Definition at line 527 of file string_arithmetic.cpp.
References is_negative().
Referenced by is_positive().
 {
   return !is_negative(argument);
 }
bool is_negative (const std::string & argument)
Definition at line 522 of file string_arithmetic.cpp.
Referenced by is_natural(), signed_abs(), signed_less_than(), signed_to_inf(), signed_to_long(), and unsigned_less_than().
 {
   return argument[0] == '1';
 }
bool is_positive (const std::string & argument)
Definition at line 532 of file string_arithmetic.cpp.
References is_natural(), and is_zero().
Referenced by signed_exponent(), and unsigned_exponent().
 {
   return is_natural(argument) && !is_zero(argument);
 }
bool is_zero (const std::string & argument)
Definition at line 537 of file string_arithmetic.cpp.
Referenced by is_positive(), and signed_modulus().
 {
   for (unsigned i = 0; i < argument.size(); i++)
   {
     if (argument[i] == '1')
       return false;
   }
   return true;
 }
std::string long_to_signed (long argument, unsigned size = 0)
Definition at line 789 of file string_arithmetic.cpp.
References signed_not(), and signed_resize().
 {
   bool negative = argument < 0;
   if (negative) argument = -(argument+1);
   std::string result = "";
   while(argument)
   {
     result.insert((std::string::size_type)0u,1u,(argument%2 ? '1' : '0'));
     argument /= 2;
   }
   result.insert((std::string::size_type)0u,1u,'0');
   if (negative) result = signed_not(result);
   return signed_resize(result,size);
 }
std::string signed_abs (const std::string & argument, unsigned size = 0)
Definition at line 604 of file string_arithmetic.cpp.
References is_negative(), signed_negate(), and signed_resize().
Referenced by signed_divide(), and signed_remainder().
 {
   return is_negative(argument) ? signed_negate(argument, size) : signed_resize(argument, size);
 }
std::string signed_add (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 609 of file string_arithmetic.cpp.
References bit_carry(), bit_sum(), and signed_resize().
Referenced by signed_modulus(), and signed_multiply().
 {
   unsigned add_size = std::max(left.size(),right.size())+1;
   std::string left_value = signed_resize(left, add_size);
   std::string right_value = signed_resize(right, add_size);
   std::string result = signed_resize("0",add_size);
   char carry = '0';
   for (unsigned i = add_size; i--; )
   {
     result[i] = bit_sum(left_value[i], right_value[i], carry);
     carry = bit_carry(left_value[i], right_value[i], carry);
   }
   return signed_resize(result,size);
 }
std::string signed_and (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 708 of file string_arithmetic.cpp.
References bitwise_and(), and signed_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_and(signed_resize(left,size), signed_resize(right,size));
 }
std::string signed_divide (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 663 of file string_arithmetic.cpp.
References divrem(), signed_abs(), signed_negate(), signed_resize(), and unsigned_resize().
 {
   // do unsigned division on the absolute values
   std::pair<std::string,std::string> div_result = divrem(signed_abs(left),signed_abs(right));
   // the result is negated if the signs are different - note also the unsigned to signed conversion
   std::string result = unsigned_resize(div_result.first,div_result.first.size()+1);
   if (left[0] != right[0]) result = signed_negate(result);
   return signed_resize(result,size);
 }
bool signed_equality (const std::string & left, const std::string & right)
Definition at line 550 of file string_arithmetic.cpp.
References signed_resize().
Referenced by signed_inequality().
 {
   std::string left_value = signed_resize(left, std::max(left.size(),right.size()));
   std::string right_value = signed_resize(right, std::max(left.size(),right.size()));
   return left_value == right_value;
 }
std::string signed_exponent (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 655 of file string_arithmetic.cpp.
References count(), is_positive(), signed_multiply(), signed_resize(), and signed_subtract().
 {
   std::string result = "01";
   for (std::string count = right; is_positive(count); count = signed_subtract(count,"01"))
     result = signed_multiply(result, left);
   return signed_resize(result,size);
 }
bool signed_greater_than (const std::string & left, const std::string & right)
Definition at line 574 of file string_arithmetic.cpp.
References signed_less_than().
 {
   // l > r is equivalent to r < l
   return signed_less_than(right,left);
 }
bool signed_greater_than_or_equal (const std::string & left, const std::string & right)
Definition at line 580 of file string_arithmetic.cpp.
References signed_less_than().
 {
   // l >= r is equivalent to !(l < r)
   return !signed_less_than(left,right);
 }
bool signed_inequality (const std::string & left, const std::string & right)
Definition at line 557 of file string_arithmetic.cpp.
References signed_equality().
 {
   return !signed_equality(left,right);
 }
bool signed_less_than (const std::string & left, const std::string & right)
Definition at line 562 of file string_arithmetic.cpp.
References is_negative(), and signed_subtract().
Referenced by signed_greater_than(), signed_greater_than_or_equal(), and signed_less_than_or_equal().
 {
   std::string result = signed_subtract(left,right);
   return is_negative(result);
 }
bool signed_less_than_or_equal (const std::string & left, const std::string & right)
Definition at line 568 of file string_arithmetic.cpp.
References signed_less_than().
 {
   // l <= r is equivalent to !(r < l)
   return !signed_less_than(right,left);
 }
std::string signed_modulus (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 673 of file string_arithmetic.cpp.
References is_zero(), signed_add(), signed_remainder(), and signed_resize().
 {
   // Note: unlike remainder, which cannot be bigger than the left argument, the modulus can be as big as the absolute value of the right too
   //       the solution is to allow the result to expand its own way
   // to convert from remainder to modulus, you add the divisor iff the result is non-zero and signs are different:
   //   3 rem 4 = 3    :  3 mod 4 = 3
   //  -3 rem 4 = -3   : -3 mod 4 = 1 = (-3 rem 4) + 4
   //   3 rem -4 = 3   :  3 mod -4 = -1 = (3 rem -4) + -4
   //  -3 rem -4 = -3  : -3 mod -4 = -3
   std::string result = signed_remainder(left,right);
   if (!is_zero(result) && (right[0] != left[0]))
     result = signed_add(result,right);
   return signed_resize(result,size);
 }
std::string signed_multiply (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 639 of file string_arithmetic.cpp.
References signed_add(), signed_resize(), signed_shift_left(), and signed_subtract().
Referenced by signed_exponent(), and unsigned_exponent().
 {
   // based on numeric_xxx.vhdl
   std::string result = "0";
   std::string add = right;
   for (unsigned i = left.size(); i--; )
   {
     if (left[i] == '1')
       result = signed_add(result, add);
     add = signed_shift_left(add, 1);
   }
   if (left[0] == '1')
     result = signed_subtract(result,add);
   return signed_resize(result,size);
 }
std::string signed_nand (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 714 of file string_arithmetic.cpp.
References bitwise_nand(), and signed_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_nand(signed_resize(left,size), signed_resize(right,size));
 }
std::string signed_negate (const std::string & argument, unsigned size = 0)
Definition at line 589 of file string_arithmetic.cpp.
References bit_or(), bit_xor(), and signed_resize().
Referenced by signed_abs(), signed_divide(), and signed_remainder().
 {
   unsigned negate_size = argument.size()+1;
   std::string value = signed_resize(argument, negate_size);
   std::string result = signed_resize("0",negate_size);
   char borrow = '0';
   for (unsigned i = negate_size; i--; )
   {
     // negation is zero minus the argument, which I have optimised to the following:
     result[i] = bit_xor(value[i], borrow);
     borrow = bit_or(value[i], borrow);
   }
   return signed_resize(result,size);
 }
std::string signed_nor (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 726 of file string_arithmetic.cpp.
References bitwise_nor(), and signed_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_nor(signed_resize(left,size), signed_resize(right,size));
 }
std::string signed_not (const std::string & argument, unsigned size = 0)
Definition at line 702 of file string_arithmetic.cpp.
References bitwise_not(), and signed_resize().
Referenced by inf_to_signed(), long_to_signed(), signed_to_inf(), and signed_to_long().
 {
   if (!size) size = argument.size();
   return bitwise_not(signed_resize(argument,size));
 }
std::string signed_or (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 720 of file string_arithmetic.cpp.
References bitwise_or(), and signed_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_or(signed_resize(left,size), signed_resize(right,size));
 }
std::string signed_remainder (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 688 of file string_arithmetic.cpp.
References divrem(), signed_abs(), signed_negate(), signed_resize(), and unsigned_resize().
Referenced by signed_modulus().
 {
   // do unsigned division on the absolute values
   std::pair<std::string,std::string> div_result = divrem(signed_abs(left),signed_abs(right));
   // the sign of the result is the same as the left argument
   std::string result = unsigned_resize(div_result.second,div_result.second.size()+1);
   if (left[0] == '1')
     result = signed_negate(result);
   return signed_resize(result,size);
 }
std::string signed_resize (const std::string & argument, unsigned size = 0)
Definition at line 496 of file string_arithmetic.cpp.
Referenced by inf_to_signed(), long_to_signed(), signed_abs(), signed_add(), signed_and(), signed_divide(), signed_equality(), signed_exponent(), signed_modulus(), signed_multiply(), signed_nand(), signed_negate(), signed_nor(), signed_not(), signed_or(), signed_remainder(), signed_shift_left(), signed_shift_right(), signed_subtract(), signed_xnor(), and signed_xor().
 {
   std::string value = argument;
   // resize has three functions:
   if (!size)
   {
     // - reduce to minimum size by simply trimming leading sign bits (but not the last bit)
     while(value.size() >= 2 && value[0] == value[1])
       value.erase((std::string::size_type)0u,1);
   }
   else if (size > value.size())
   {
     // - sign extend when a greater size specified
     value.insert((std::string::size_type)0u,size-value.size(),value.empty() ? '0' : value[0]);
   }
   else if (value.size() > size)
   {
     // - truncate when a smaller size specified
     value.erase((std::string::size_type)0u,value.size()-size);
   }
   return value;
 }
std::string signed_shift_left (const std::string & argument, unsigned shift, unsigned size = 0)
Definition at line 746 of file string_arithmetic.cpp.
References bitwise_shift_left(), and signed_resize().
Referenced by signed_multiply().
 {
   return signed_resize(bitwise_shift_left(argument,shift),size);
 }
std::string signed_shift_right (const std::string & argument, unsigned shift, unsigned size = 0)
Definition at line 751 of file string_arithmetic.cpp.
References bitwise_shift_right(), and signed_resize().
 {
   return signed_resize(bitwise_shift_right(argument,shift),size);
 }
std::string signed_subtract (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 624 of file string_arithmetic.cpp.
References bit_carry(), bit_not(), bit_sum(), and signed_resize().
Referenced by signed_exponent(), signed_less_than(), signed_multiply(), unsigned_exponent(), and unsigned_less_than().
 {
   unsigned sub_size = std::max(left.size(),right.size())+1;
   std::string left_value = signed_resize(left, sub_size);
   std::string right_value = signed_resize(right, sub_size);
   std::string result = signed_resize("0",sub_size);
   char borrow = '0';
   for (unsigned i = sub_size; i--; )
   {
     result[i] = bit_sum(left_value[i], right_value[i], borrow);
     borrow = bit_carry(bit_not(left_value[i]), right_value[i], borrow);
   }
   return signed_resize(result,size);
 }
inf signed_to_inf (const std::string & argument)
Definition at line 774 of file string_arithmetic.cpp.
References is_negative(), and signed_not().
 {
   bool negative = is_negative(argument);
   inf result;
   std::string value = negative ? signed_not(argument) : argument;
   for (unsigned i = 0; i < value.size(); i++)
   {
     result *= inf(2);
     if (value[i] == '1') ++result;
   }
   if (negative)
     result = (-result)-inf(1);
   return result;
 }
long signed_to_long (const std::string & argument)
Definition at line 759 of file string_arithmetic.cpp.
References is_negative(), and signed_not().
 {
   bool negative = is_negative(argument);
   long result = 0;
   std::string value = negative ? signed_not(argument) : argument;
   for (unsigned i = 0; i < value.size(); i++)
   {
     result *= 2;
     if (value[i] == '1') ++result;
   }
   if (negative)
     result = (-result)-1;
   return result;
 }
std::string signed_xnor (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 738 of file string_arithmetic.cpp.
References bitwise_xnor(), and signed_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_xnor(signed_resize(left,size), signed_resize(right,size));
 }
std::string signed_xor (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 732 of file string_arithmetic.cpp.
References bitwise_xor(), and signed_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_xor(signed_resize(left,size), signed_resize(right,size));
 }
std::string ulong_to_unsigned (unsigned long argument, unsigned size = 0)
Definition at line 470 of file string_arithmetic.cpp.
References unsigned_resize().
 {
   std::string result = argument ? "" : "0";
   while(argument)
   {
     result.insert((std::string::size_type)0u,1u,(argument%2 ? '1' : '0'));
     argument /= 2;
   }
   return unsigned_resize(result,size);
 }
std::string unsigned_add (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 294 of file string_arithmetic.cpp.
References bit_carry(), bit_sum(), and unsigned_resize().
Referenced by unsigned_multiply().
 {
   unsigned add_size = std::max(left.size(),right.size())+1;
   std::string left_value = unsigned_resize(left, add_size);
   std::string right_value = unsigned_resize(right, add_size);
   std::string result = unsigned_resize("0",add_size);
   char carry = '0';
   for (unsigned i = add_size; i--; )
   {
     result[i] = bit_sum(left_value[i], right_value[i], carry);
     carry = bit_carry(left_value[i], right_value[i], carry);
   }
   return unsigned_resize(result,size);
 }
std::string unsigned_and (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 396 of file string_arithmetic.cpp.
References bitwise_and(), and unsigned_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_and(unsigned_resize(left,size), unsigned_resize(right,size));
 }
std::string unsigned_divide (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 369 of file string_arithmetic.cpp.
References divrem(), and unsigned_resize().
 {
   std::pair<std::string,std::string> result = divrem(left,right);
   return unsigned_resize(result.first,size);
 }
bool unsigned_equality (const std::string & left, const std::string & right)
Definition at line 253 of file string_arithmetic.cpp.
References unsigned_resize().
Referenced by unsigned_inequality().
 {
   // implement numeric equality as bitwise equality by first normalising to the same size
   std::string left_value = unsigned_resize(left, std::max(left.size(),right.size()));
   std::string right_value = unsigned_resize(right, std::max(left.size(),right.size()));
   return left_value == right_value;
 }
std::string unsigned_exponent (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 339 of file string_arithmetic.cpp.
References count(), is_positive(), signed_multiply(), signed_subtract(), and unsigned_resize().
 {
   // simply implemented by repeated multiplication
   std::string result = "1";
   // make the count signed by zero extending one bit so that the test for positive works
   for (std::string count = unsigned_resize(right,right.size()+1); is_positive(count); count = signed_subtract(count,"1"))
     result = signed_multiply(result, left);
   return unsigned_resize(result,size);
 }
bool unsigned_greater_than (const std::string & left, const std::string & right)
Definition at line 279 of file string_arithmetic.cpp.
References unsigned_less_than().
 {
   // l > r is equivalent to r < l
   return unsigned_less_than(right,left);
 }
bool unsigned_greater_than_or_equal (const std::string & left, const std::string & right)
Definition at line 285 of file string_arithmetic.cpp.
References unsigned_less_than().
 {
   // l >= r is equivalent to !(l < r)
   return !unsigned_less_than(left,right);
 }
bool unsigned_inequality (const std::string & left, const std::string & right)
Definition at line 261 of file string_arithmetic.cpp.
References unsigned_equality().
 {
   return !unsigned_equality(left,right);
 }
bool unsigned_less_than (const std::string & left, const std::string & right)
Definition at line 266 of file string_arithmetic.cpp.
References is_negative(), signed_subtract(), and unsigned_resize().
Referenced by divrem(), unsigned_greater_than(), unsigned_greater_than_or_equal(), and unsigned_less_than_or_equal().
 {
   // extend by one bit and treat as signed then do subtraction and test for a negative result
   std::string result = signed_subtract(unsigned_resize(left,left.size()+1),unsigned_resize(right,right.size()+1));
   return is_negative(result);
 }
bool unsigned_less_than_or_equal (const std::string & left, const std::string & right)
Definition at line 273 of file string_arithmetic.cpp.
References unsigned_less_than().
 {
   // l <= r is equivalent to !(r < l)
   return !unsigned_less_than(right,left);
 }
std::string unsigned_modulus (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 375 of file string_arithmetic.cpp.
References unsigned_remainder().
 {
   // for unsigned, modulus is the same as remainder
   return unsigned_remainder(left,right,size);
 }
std::string unsigned_multiply (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 324 of file string_arithmetic.cpp.
References unsigned_add(), unsigned_resize(), and unsigned_shift_left().
 {
   // based on numeric_xxx.vhdl
   // multiplication is repeated addition
   std::string result = "0";
   std::string add = right;
   for (unsigned i = left.size(); i--; )
   {
     if (left[i] == '1')
       result = unsigned_add(result, add);
     add = unsigned_shift_left(add, 1);
   }
   return unsigned_resize(result,size);
 }
std::string unsigned_nand (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 402 of file string_arithmetic.cpp.
References bitwise_nand(), and unsigned_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_nand(unsigned_resize(left,size), unsigned_resize(right,size));
 }
std::string unsigned_nor (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 414 of file string_arithmetic.cpp.
References bitwise_nor(), and unsigned_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_nor(unsigned_resize(left,size), unsigned_resize(right,size));
 }
std::string unsigned_not (const std::string & argument, unsigned size = 0)
Definition at line 390 of file string_arithmetic.cpp.
References bitwise_not(), and unsigned_resize().
 {
   if (!size) size = argument.size();
   return bitwise_not(unsigned_resize(argument,size));
 }
std::string unsigned_or (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 408 of file string_arithmetic.cpp.
References bitwise_or(), and unsigned_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_or(unsigned_resize(left,size), unsigned_resize(right,size));
 }
std::string unsigned_remainder (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 381 of file string_arithmetic.cpp.
References divrem(), and unsigned_resize().
Referenced by unsigned_modulus().
 {
   std::pair<std::string,std::string> result = divrem(left,right);
   return unsigned_resize(result.second,size);
 }
std::string unsigned_resize (const std::string & argument, unsigned size = 0)
Definition at line 227 of file string_arithmetic.cpp.
Referenced by inf_to_unsigned(), signed_divide(), signed_remainder(), ulong_to_unsigned(), unsigned_add(), unsigned_and(), unsigned_divide(), unsigned_equality(), unsigned_exponent(), unsigned_less_than(), unsigned_multiply(), unsigned_nand(), unsigned_nor(), unsigned_not(), unsigned_or(), unsigned_remainder(), unsigned_shift_left(), unsigned_shift_right(), unsigned_subtract(), unsigned_xnor(), and unsigned_xor().
 {
   std::string value = argument;
   // resize has three functions:
   if (!size)
   {
     // - reduce to minimum size when size 0 specified by simply trimming leading zeros (but not the last bit)
     while(value.size() > 1 && value[0] == '0')
       value.erase((std::string::size_type)0u,1);
   }
   else if (size > value.size())
   {
     // - zero extend when a greater size specified
     value.insert((std::string::size_type)0u,size-value.size(),'0');
   }
   else if (size < value.size())
   {
     // - truncate when a smaller size specified
     value.erase((std::string::size_type)0u,value.size()-size);
   }
   return value;
 }
std::string unsigned_shift_left (const std::string & argument, unsigned shift, unsigned size = 0)
Definition at line 434 of file string_arithmetic.cpp.
References bitwise_shift_left(), and unsigned_resize().
Referenced by divrem(), and unsigned_multiply().
 {
   return unsigned_resize(bitwise_shift_left(argument,shift),size);
 }
std::string unsigned_shift_right (const std::string & argument, unsigned shift, unsigned size = 0)
Definition at line 439 of file string_arithmetic.cpp.
References bitwise_shift_right(), and unsigned_resize().
Referenced by divrem().
 {
   return unsigned_resize(bitwise_shift_right(argument,shift),size);
 }
std::string unsigned_subtract (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 309 of file string_arithmetic.cpp.
References bit_carry(), bit_not(), bit_sum(), and unsigned_resize().
Referenced by divrem().
 {
   unsigned sub_size = std::max(left.size(),right.size())+1;
   std::string left_value = unsigned_resize(left, sub_size);
   std::string right_value = unsigned_resize(right, sub_size);
   std::string result = unsigned_resize("0",sub_size);
   char borrow = '0';
   for (unsigned i = sub_size; i--; )
   {
     result[i] = bit_sum(left_value[i], right_value[i], borrow);
     borrow = bit_carry(bit_not(left_value[i]), right_value[i], borrow);
   }
   return unsigned_resize(result,size);
 }
inf unsigned_to_inf (const std::string & argument)
Definition at line 459 of file string_arithmetic.cpp.
 {
   inf result;
   for (unsigned i = 0; i < argument.size(); i++)
   {
     result *= inf(2);
     if (argument[i] == '1') ++result;
   }
   return result;
 }
unsigned long unsigned_to_ulong (const std::string & argument)
Definition at line 448 of file string_arithmetic.cpp.
 {
   unsigned long result = 0;
   for (unsigned i = 0; i < argument.size(); i++)
   {
     result *= 2;
     if (argument[i] == '1') ++result;
   }
   return result;
 }
std::string unsigned_xnor (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 426 of file string_arithmetic.cpp.
References bitwise_xnor(), and unsigned_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_xnor(unsigned_resize(left,size), unsigned_resize(right,size));
 }
std::string unsigned_xor (const std::string & left, const std::string & right, unsigned size = 0)
Definition at line 420 of file string_arithmetic.cpp.
References bitwise_xor(), and unsigned_resize().
 {
   if (!size) size = std::max(left.size(),right.size());
   return bitwise_xor(unsigned_resize(left,size), unsigned_resize(right,size));
 }