Visible: include/stlplus/string_utilities.hpp File Reference
string_utilities.hpp File Reference
#include "os_fixes.hpp"
#include "format_types.hpp"
#include "textio.hpp"
#include <string>
#include <vector>
#include <bitset>
#include <list>
#include <map>
#include <set>
#include <stdexcept>
#include <time.h>
#include "string_utilities.tpp"
Functions
std::string to_string (bool i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (short i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (unsigned short i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (int i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (unsigned int i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (long i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (unsigned long i, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (const void *, unsigned radix=16, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
std::string to_string (float f, real_display_t display=display_mixed, unsigned width=0, unsigned precision=6) throw (std::invalid_argument)
std::string to_string (double f, real_display_t display=display_mixed, unsigned width=0, unsigned precision=6) throw (std::invalid_argument)
std::string to_string (const std::string &value)
std::string to_string (const char *value)
bool to_bool (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
short to_short (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
unsigned short to_ushort (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
int to_int (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
unsigned int to_uint (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
long to_long (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
unsigned long to_ulong (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
void * to_void_star (const std::string &value, unsigned radix=0) throw (std::invalid_argument)
float to_float (const std::string &value) throw (std::invalid_argument)
double to_double (const std::string &value) throw (std::invalid_argument)
template<typename T >
std::string pointer_to_string (const T *value, const std::string &null_string, const std::string &prefix, const std::string &suffix)
template<size_t N>
std::string bitset_to_string (const std::bitset< N > &data)
template<typename T >
std::string list_to_string (const std::list< T > &values, const std::string &separator)
template<typename L , typename R >
std::string pair_to_string (const std::pair< L, R > &values, const std::string &separator)
template<typename K , typename T , typename P >
std::string map_to_string (const std::map< K, T, P > &values, const std::string &pair_separator, const std::string &separator)
template<typename K , typename T , typename P >
std::string multimap_to_string (const std::multimap< K, T, P > &values, const std::string &pair_separator, const std::string &separator)
template<typename K , typename P >
std::string set_to_string (const std::set< K, P > &values, const std::string &separator)
template<typename K , typename P >
std::string multiset_to_string (const std::multiset< K, P > &values, const std::string &separator)
template<typename T >
std::string vector_to_string (const std::vector< T > &values, const std::string &separator)
std::string to_string (const std::vector< bool > &values)
void set_indent_step (unsigned step)
unsigned indent_step (void)
otext & print_indent (otext &str, unsigned indent)
otext & print (otext &str, const bool &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const short &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const unsigned short &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const int &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const unsigned int &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const long &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const unsigned long &value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, const void *&value, unsigned radix=10, radix_display_t display=radix_c_style_or_hash, unsigned width=0) throw (std::invalid_argument)
otext & print (otext &str, float f, real_display_t display=display_mixed, unsigned width=0, unsigned precision=6) throw (std::invalid_argument)
otext & print (otext &str, double f, real_display_t display=display_mixed, unsigned width=0, unsigned precision=6) throw (std::invalid_argument)
otext & print (otext &str, const std::string &value)
otext & print (otext &str, const std::string &value, unsigned indent)
template<typename T >
otext & print_pointer (otext &str, const T *value, const std::string &null_string, const std::string &prefix, const std::string &suffix)
template<typename T >
otext & print_pointer (otext &str, const T *value, unsigned indent, const std::string &null_string, const std::string &prefix, const std::string &suffix)
template<size_t N>
otext & print_bitset (otext &str, const std::bitset< N > &value)
template<size_t N>
otext & print_bitset (otext &str, const std::bitset< N > &value, unsigned indent)
template<typename T >
otext & print_list (otext &str, const std::list< T > &values, const std::string &separator)
template<typename T >
otext & print_list (otext &str, const std::list< T > &values, unsigned indent)
template<typename L , typename R >
otext & print_pair (otext &str, const std::pair< L, R > &values, const std::string &separator)
template<typename L , typename R >
otext & print_pair (otext &str, const std::pair< L, R > &values, const std::string &separator, unsigned indent)
template<typename K , typename T , typename P >
otext & print_map (otext &str, const std::map< K, T, P > &values, const std::string &pair_separator, const std::string &separator)
template<typename K , typename T , typename P >
otext & print_map (otext &str, const std::map< K, T, P > &values, const std::string &pair_separator, unsigned indent)
template<typename K , typename T , typename P >
otext & print_multimap (otext &str, const std::multimap< K, T, P > &values, const std::string &pair_separator, const std::string &separator)
template<typename K , typename T , typename P >
otext & print_multimap (otext &str, const std::multimap< K, T, P > &values, const std::string &pair_separator, unsigned indent)
template<typename K , typename P >
otext & print_set (otext &str, const std::set< K, P > &values, const std::string &separator)
template<typename K , typename P >
otext & print_set (otext &str, const std::set< K, P > &values, unsigned indent)
template<typename K , typename P >
otext & print_multiset (otext &str, const std::multiset< K, P > &values, const std::string &separator)
template<typename K , typename P >
otext & print_multiset (otext &str, const std::multiset< K, P > &values, unsigned indent)
template<typename T >
otext & print_vector (otext &str, const std::vector< T > &values, const std::string &separator)
template<typename T >
otext & print_vector (otext &str, const std::vector< T > &values, unsigned indent)
otext & print (otext &str, const std::vector< bool > &values)
std::string pad (const std::string &str, alignment_t alignment, unsigned width, char padch= ' ') throw (std::invalid_argument)
std::string trim_left (const std::string &val)
std::string trim_right (const std::string &val)
std::string trim (const std::string &val)
std::string lowercase (const std::string &val)
std::string uppercase (const std::string &val)
std::string translate (const std::string &input, const std::string &from_set, const std::string &to_set=std::string())
bool match_wildcard (const std::string &wild, const std::string &match)
std::vector< std::string > split (const std::string &str, const std::string &splitter="\n")
std::string join (const std::vector< std::string > &, const std::string &joiner="\n", const std::string &prefix="", const std::string &suffix="")
std::string display_bytes (long bytes)
std::string display_time (time_t seconds)
Function Documentation
template<size_t N> std::string bitset_to_string (const std::bitset< N > & data)
std::string display_bytes (long bytes)
Definition at line 1420 of file string_utilities.cpp.
References dformat().
 {
   std::string result;
   if (bytes < 0)
   {
     result += '-';
     bytes = -bytes;
   }
   static const long kB = 1024l;
   static const long MB = kB * kB;
   static const long GB = MB * kB;
   if (bytes < kB)
     result += dformat("%iB", bytes);
   else if (bytes < (10l * kB))
     result += dformat("%.2fkB", ((float)bytes / (float)kB));
   else if (bytes < (100l * kB))
     result += dformat("%.1fkB", ((float)bytes / (float)kB));
   else if (bytes < MB)
     result += dformat("%.0fkB", ((float)bytes / (float)kB));
   else if (bytes < (10l * MB))
     result += dformat("%.2fMB", ((float)bytes / (float)MB));
   else if (bytes < (100l * MB))
     result += dformat("%.1fMB", ((float)bytes / (float)MB));
   else if (bytes < GB)
     result += dformat("%.0fMB", ((float)bytes / (float)MB));
   else
     result += dformat("%.2fGB", ((float)bytes / (float)GB));
   return result;
 }
std::string display_time (time_t seconds)
Definition at line 1450 of file string_utilities.cpp.
References radix_none, and to_string().
Referenced by timer::text().
 {
   unsigned minutes = (unsigned)seconds / 60;
   seconds %= 60;
   unsigned hours = minutes / 60;
   minutes %= 60;
   unsigned days = hours / 24;
   hours %= 24;
   unsigned weeks = days / 7;
   days %= 7;
   std::string result;
   if (weeks > 0)
   {
     result += to_string(weeks, 10, radix_none, 1);
     result += "w ";
   }
   if (!result.empty() || days > 0)
   {
     result += to_string(days, 10, radix_none, 1);
     result += "d ";
   }
   if (!result.empty() || hours > 0)
   {
     result += to_string(hours, 10, radix_none, 1);
     result += ":";
   }
   if (!result.empty() || minutes > 0)
   {
     if (!result.empty())
       result += to_string(minutes, 10, radix_none, 2);
     else
       result += to_string(minutes, 10, radix_none, 1);
     result += ":";
   }
   if (!result.empty())
     result += to_string((unsigned)seconds, 10, radix_none, 2);
   else
   {
     result += to_string((unsigned)seconds, 10, radix_none, 1);
     result += "s";
   }
   return result;
 }
unsigned indent_step (void)
Definition at line 490 of file string_utilities.cpp.
References _indent_step.
 {
   return _indent_step;
 }
std::string join (const std::vector< std::string > & , const std::string & joiner = "\n", const std::string & prefix = "", const std::string & suffix = "")
Definition at line 1406 of file string_utilities.cpp.
 {
   std::string result = prefix;
   for (unsigned i = 0; i < str.size(); i++)
   {
     if (i) result += joiner;
     result += str[i];
   }
   result += suffix;
   return result;
 }
template<typename T > std::string list_to_string (const std::list< T > & values, const std::string & separator)
std::string lowercase (const std::string & val)
Definition at line 1186 of file string_utilities.cpp.
Referenced by lm_library::local_find(), library_manager::local_find(), path_compare(), and cli_parser::switch_value().
 {
   std::string text = val;
   for (unsigned i = 0; i < text.size(); i++)
     text[i] = tolower(text[i]);
   return text;
 }
template<typename K , typename T , typename P > std::string map_to_string (const std::map< K, T, P > & values, const std::string & pair_separator, const std::string & separator)
bool match_wildcard (const std::string & wild, const std::string & match)
Definition at line 1376 of file string_utilities.cpp.
References match_remainder().
Referenced by _debug_trace::_debug_trace(), and folder_wildcard().
 {
   return match_remainder(wild, wild.begin(), match, match.begin());
 }
template<typename K , typename T , typename P > std::string multimap_to_string (const std::multimap< K, T, P > & values, const std::string & pair_separator, const std::string & separator)
template<typename K , typename P > std::string multiset_to_string (const std::multiset< K, P > & values, const std::string & separator)
std::string pad (const std::string & str, alignment_t alignment, unsigned width, char padch = ' ') throw (std::invalid_argument)
Definition at line 1121 of file string_utilities.cpp.
References align_centre, align_left, and align_right.
Referenced by bitwise_resize(), and rcKinetoscope::selfSimilarMotionField().
 {
   std::string result = str;
   switch(alignment)
   {
   case align_left:
   {
     unsigned padding = width>str.size() ? width - str.size() : 0;
     unsigned i = 0;
     while (i++ < padding)
       result.insert(result.end(), padch);
     break;
   }
   case align_right:
   {
     unsigned padding = width>str.size() ? width - str.size() : 0;
     unsigned i = 0;
     while (i++ < padding)
       result.insert(result.begin(), padch);
     break;
   }
   case align_centre:
   {
     unsigned padding = width>str.size() ? width - str.size() : 0;
     unsigned i = 0;
     while (i++ < padding/2)
       result.insert(result.end(), padch);
     i--;
     while (i++ < padding)
       result.insert(result.begin(), padch);
     break;
   }
   default:
     throw std::invalid_argument("invalid alignment value");
   }
   return result;
 }
template<typename L , typename R > std::string pair_to_string (const std::pair< L, R > & values, const std::string & separator)
template<typename T > std::string pointer_to_string (const T * value, const std::string & null_string, const std::string & prefix, const std::string & suffix)
otext& print (otext & str, const bool & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 503 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const short & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 509 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const unsigned short & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 515 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const int & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 521 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const unsigned int & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 527 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const long & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 533 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const unsigned long & value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 539 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, const void *& value, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 545 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,radix,display,width);
 }
otext& print (otext & str, float f, real_display_t display = display_mixed, unsigned width = 0, unsigned precision = 6) throw (std::invalid_argument)
Definition at line 553 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,display,width,precision);
 }
otext& print (otext & str, double f, real_display_t display = display_mixed, unsigned width = 0, unsigned precision = 6) throw (std::invalid_argument)
Definition at line 559 of file string_utilities.cpp.
References to_string().
 {
   return str << to_string(value,display,width,precision);
 }
otext& print (otext & str, const std::string & value)
Definition at line 567 of file string_utilities.cpp.
 {
   return str << value;
 }
otext& print (otext & str, const std::string & value, unsigned indent)
Definition at line 572 of file string_utilities.cpp.
References endl(), print(), and print_indent().
 {
   print_indent(str, indent);
   print(str, value);
   return str << endl;
 }
otext& print (otext & str, const std::vector< bool > & values)
Definition at line 1112 of file string_utilities.cpp.
 {
   for (size_t i = 0; i < values.size(); i++)
     str << (values[i] ? '1' : '0');
   return str;
 }
template<size_t N> otext& print_bitset (otext & str, const std::bitset< N > & value)
template<size_t N> otext& print_bitset (otext & str, const std::bitset< N > & value, unsigned indent)
otext& print_indent (otext & str, unsigned indent)
Definition at line 495 of file string_utilities.cpp.
References _indent_step.
Referenced by lm_library::pretty_print(), print(), lm_library::print(), lm_unit::print_long(), and lm_library::print_long().
 {
   for (unsigned i = 0; i < indent; i++)
     for (unsigned j = 0; j < _indent_step; j++)
       str << ' ';
   return str;
 }
template<typename T > otext& print_list (otext & str, const std::list< T > & values, const std::string & separator)
template<typename T > otext& print_list (otext & str, const std::list< T > & values, unsigned indent)
template<typename K , typename T , typename P > otext& print_map (otext & str, const std::map< K, T, P > & values, const std::string & pair_separator, const std::string & separator)
template<typename K , typename T , typename P > otext& print_map (otext & str, const std::map< K, T, P > & values, const std::string & pair_separator, unsigned indent)
template<typename K , typename T , typename P > otext& print_multimap (otext & str, const std::multimap< K, T, P > & values, const std::string & pair_separator, const std::string & separator)
template<typename K , typename T , typename P > otext& print_multimap (otext & str, const std::multimap< K, T, P > & values, const std::string & pair_separator, unsigned indent)
template<typename K , typename P > otext& print_multiset (otext & str, const std::multiset< K, P > & values, const std::string & separator)
template<typename K , typename P > otext& print_multiset (otext & str, const std::multiset< K, P > & values, unsigned indent)
template<typename L , typename R > otext& print_pair (otext & str, const std::pair< L, R > & values, const std::string & separator)
template<typename L , typename R > otext& print_pair (otext & str, const std::pair< L, R > & values, const std::string & separator, unsigned indent)
template<typename T > otext& print_pointer (otext & str, const T * value, const std::string & null_string, const std::string & prefix, const std::string & suffix)
template<typename T > otext& print_pointer (otext & str, const T * value, unsigned indent, const std::string & null_string, const std::string & prefix, const std::string & suffix)
template<typename K , typename P > otext& print_set (otext & str, const std::set< K, P > & values, const std::string & separator)
template<typename K , typename P > otext& print_set (otext & str, const std::set< K, P > & values, unsigned indent)
template<typename T > otext& print_vector (otext & str, const std::vector< T > & values, const std::string & separator)
Referenced by print().
template<typename T > otext& print_vector (otext & str, const std::vector< T > & values, unsigned indent)
void set_indent_step (unsigned step)
Definition at line 485 of file string_utilities.cpp.
 {
   _indent_step = step;
 }
template<typename K , typename P > std::string set_to_string (const std::set< K, P > & values, const std::string & separator)
std::vector<std::string> split (const std::string & str, const std::string & splitter = "\n")
Definition at line 1383 of file string_utilities.cpp.
Referenced by lookup().
 {
   std::vector<std::string> result;
   if (!str.empty())
   {
     for(std::string::size_type offset = 0;;)
     {
       std::string::size_type found = str.find(splitter, offset);
       if (found != std::string::npos)
       {
         result.push_back(str.substr(offset, found-offset));
         offset = found + splitter.size();
       }
       else
       {
         result.push_back(str.substr(offset, str.size()-offset));
         break;
       }
     }
   }
   return result;
 }
bool to_bool (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1038 of file string_utilities.cpp.
Referenced by itext::operator>>().
 {
   return uvalue<unsigned char>(str, radix) != 0;
 }
double to_double (const std::string & value) throw (std::invalid_argument)
Definition at line 1094 of file string_utilities.cpp.
Referenced by itext::operator>>(), and to_float().
 {
   // TODO - error chking
   return strtod(value.c_str(), 0);
 }
float to_float (const std::string & value) throw (std::invalid_argument)
Definition at line 1088 of file string_utilities.cpp.
References to_double().
Referenced by itext::operator>>().
 {
   return (float)to_double(value);
 }
int to_int (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1056 of file string_utilities.cpp.
Referenced by count(), itext::operator>>(), percent(), sample(), and startframe().
 {
   return svalue<int>(str, radix);
 }
long to_long (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1068 of file string_utilities.cpp.
Referenced by itext::operator>>().
 {
   return svalue<long>(str, radix);
 }
short to_short (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1044 of file string_utilities.cpp.
Referenced by itext::operator>>().
 {
   return svalue<short>(str, radix);
 }
std::string to_string (bool i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 374 of file string_utilities.cpp.
 {
   // use the char representation for bool
   return uimage<char>(i, radix, display, width);
 }
std::string to_string (short i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 381 of file string_utilities.cpp.
References simage().
 {
   return simage(i, radix, display, width);
 }
std::string to_string (unsigned short i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 387 of file string_utilities.cpp.
References uimage().
 {
   return uimage(i, radix, display, width);
 }
std::string to_string (int i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 393 of file string_utilities.cpp.
References simage().
 {
   return simage(i, radix, display, width);
 }
std::string to_string (unsigned int i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
std::string to_string (long i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 405 of file string_utilities.cpp.
References simage().
 {
   return simage(i, radix, display, width);
 }
std::string to_string (unsigned long i, unsigned radix = 10, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 411 of file string_utilities.cpp.
References uimage().
 {
   return uimage(i, radix, display, width);
 }
std::string to_string (const void * , unsigned radix = 16, radix_display_t display = radix_c_style_or_hash, unsigned width = 0) throw (std::invalid_argument)
Definition at line 417 of file string_utilities.cpp.
References uimage().
 {
   // use the unsigned representation for pointers
   return uimage((unsigned long)i, radix, display, width);
 }
std::string to_string (float f, real_display_t display = display_mixed, unsigned width = 0, unsigned precision = 6) throw (std::invalid_argument)
Definition at line 426 of file string_utilities.cpp.
References dformat(), display_fixed, display_floating, and display_mixed.
 {
   char* format = 0;
   switch(display)
   {
   case display_fixed:
     format = "%*.*f";
     break;
   case display_floating:
     format = "%*.*e";
     break;
   case display_mixed:
     format = "%*.*g";
     break;
   default:
     throw std::invalid_argument("invalid radix display value");
   }
   return dformat(format, width, precision, f);
 }
std::string to_string (double f, real_display_t display = display_mixed, unsigned width = 0, unsigned precision = 6) throw (std::invalid_argument)
Definition at line 447 of file string_utilities.cpp.
References dformat(), display_fixed, display_floating, and display_mixed.
 {
   char* format = 0;
   switch(display)
   {
   case display_fixed:
     format = "%*.*f";
     break;
   case display_floating:
     format = "%*.*e";
     break;
   case display_mixed:
     format = "%*.*g";
     break;
   default:
     throw std::invalid_argument("invalid radix display value");
   }
   return dformat(format, width, precision, f);
 }
std::string to_string (const std::string & value)
Definition at line 475 of file string_utilities.cpp.
 {
   return value;
 }
std::string to_string (const char * value)
Definition at line 470 of file string_utilities.cpp.
 {
   return std::string(value);
 }
std::string to_string (const std::vector< bool > & values)
Definition at line 1104 of file string_utilities.cpp.
 {
   std::string result;
   for (size_t i = 0; i < values.size(); i++)
     result.append(1, values[i] ? '1' : '0');
   return result;
 }
unsigned int to_uint (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1062 of file string_utilities.cpp.
Referenced by itext::operator>>(), simage(), svalue(), to_inf(), to_string(), uimage(), and uvalue().
 {
   return uvalue<unsigned>(str, radix);
 }
unsigned long to_ulong (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1074 of file string_utilities.cpp.
Referenced by itext::operator>>().
 {
   return uvalue<unsigned long>(str, radix);
 }
unsigned short to_ushort (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1050 of file string_utilities.cpp.
Referenced by itext::operator>>().
 {
   return uvalue<unsigned short>(str, radix);
 }
void* to_void_star (const std::string & value, unsigned radix = 0) throw (std::invalid_argument)
Definition at line 1080 of file string_utilities.cpp.
Referenced by itext::operator>>().
 {
   return (void*)uvalue<unsigned long>(str, radix);
 }
std::string translate (const std::string & input, const std::string & from_set, const std::string & to_set = std::string())
Definition at line 1202 of file string_utilities.cpp.
Referenced by rcImageCanvasGL::panCurrent().
 {
   std::string result;
   for (unsigned i = 0; i < input.size(); i++)
   {
     char ch = input[i];
     // chk to see if the character is in the from set
     std::string::size_type found = from_set.find(ch);
     if (found == std::string::npos)
     {
       // not found so just copy across
       result += ch;
     }
     else if (found < to_set.size())
     {
       // found and in range so translate
       result += to_set[found];
     }
   }
   return result;
 }
std::string trim (const std::string & val)
Definition at line 1176 of file string_utilities.cpp.
Referenced by error_string(), ini_file::read_file(), and rcRectangle< T >::trim().
 {
   std::string result = val;
   while (!result.empty() && isspace(result[0]))
     result.erase(result.begin());
   while (!result.empty() && isspace(result[result.size()-1]))
     result.erase(result.end()-1);
   return result;
 }
std::string trim_left (const std::string & val)
Definition at line 1160 of file string_utilities.cpp.
 {
   std::string result = val;
   while (!result.empty() && isspace(result[0]))
     result.erase(result.begin());
   return result;
 }
std::string trim_right (const std::string & val)
Definition at line 1168 of file string_utilities.cpp.
 {
   std::string result = val;
   while (!result.empty() && isspace(result[result.size()-1]))
     result.erase(result.end()-1);
   return result;
 }
std::string uppercase (const std::string & val)
Definition at line 1194 of file string_utilities.cpp.
 {
   std::string text = val;
   for (unsigned i = 0; i < text.size(); i++)
     text[i] = toupper(text[i]);
   return text;
 }
template<typename T > std::string vector_to_string (const std::vector< T > & values, const std::string & separator)
Referenced by file_specification::image().