Visible: LogBuffer Struct Reference
LogBuffer Struct Reference
#include <include/util/rc_logger.h>
Public Member Functions
LogBuffer (LogStream *s)
~LogBuffer ()
flush ()
int_type overflow (int_type i)
void flush ()
Private Member Functions
int_type overflow (int_type i)
void flush ()
Private Attributes
LogStream * stream_ptr
std::string buffer
Detailed Description
Definition at line 37 of file rc_logger.h.
Constructor & Destructor Documentation
LogBuffer::LogBuffer (LogStream * s) inline
Definition at line 39 of file rc_logger.h.
 :   stream_ptr(s)   { }
LogBuffer::~LogBuffer () inline
Definition at line 40 of file rc_logger.h.
References flush().
 { flush(); }
Member Function Documentation
LogBuffer::flush ()
Referenced by overflow(), and ~LogBuffer().
void LogBuffer::flush (void) inline
Definition at line 53 of file rc_logger.h.
References buffer, LogStream::get_level(), LogRegister::instance(), stream_ptr, and LogRegister::write().
     {
         LogRegister::instance().write(buffer, stream_ptr->get_level());
         buffer.clear();
     }
void LogBuffer::flush () private
int_type LogBuffer::overflow (int_type i) inline
Definition at line 42 of file rc_logger.h.
References buffer, and flush().
     {
         if(!traits_type::eq_int_type(i, traits_type::eof()))
         {
       char_type c = traits_type::to_char_type(i);
       buffer.push_back(c);
       if(c == '\n') flush();
         }
         return traits_type::not_eof(i);
     }
int_type LogBuffer::overflow (int_type i) private
Member Data Documentation
std::string LogBuffer::buffer private
Definition at line 65 of file rc_logger.h.
Referenced by flush(), and overflow().
LogStream* LogBuffer::stream_ptr private
Definition at line 64 of file rc_logger.h.
Referenced by flush().
The documentation for this struct was generated from the following file:
include/util/rc_logger.h