Visible: rcSettingChoice Struct Reference
rcSettingChoice Struct Reference
#include <include/baseUI/rc_setting.h>
Public Member Functions
rcSettingChoice ()
rcSettingChoice (int value, const char *text, const char *descr)
rcSettingChoice (float value, const char *text, const char *descr)
rcSettingChoice (double value, const char *text, const char *descr)
virtual ~rcSettingChoice ()
virtual int getValue (void) const
virtual float getFloatValue (void)
virtual const char * getText (void) const
virtual const char * getDescription (void) const
Public Attributes
float _value
const char * _text
const char * _description
Detailed Description
Definition at line 334 of file rc_setting.h.
Constructor & Destructor Documentation
rcSettingChoice::rcSettingChoice () inline
Definition at line 338 of file rc_setting.h.
                     :
     _value( 0 ),
        _text( 0 ),
_description(0) { };
rcSettingChoice::rcSettingChoice (int value, const char * text, const char * descr) inline
Definition at line 343 of file rc_setting.h.
                                                                     :
     _value( float(value) ),
        _text( text ),
_description(descr) { };
rcSettingChoice::rcSettingChoice (float value, const char * text, const char * descr) inline
Definition at line 348 of file rc_setting.h.
                                                                       :
     _value( value ),
        _text( text ),
_description(descr) { };
rcSettingChoice::rcSettingChoice (double value, const char * text, const char * descr) inline
Definition at line 353 of file rc_setting.h.
                                                                        :
     _value( float(value) ),
        _text( text ),
_description(descr) { };
virtual rcSettingChoice::~rcSettingChoice () inline virtual
Definition at line 359 of file rc_setting.h.
 { };
Member Function Documentation
virtual const char* rcSettingChoice::getDescription (void) const inline virtual
Definition at line 380 of file rc_setting.h.
Referenced by rcRadioChoiceSettingWidget::rcRadioChoiceSettingWidget().
   {
     return _description;
   }
virtual float rcSettingChoice::getFloatValue (void) inline virtual
Definition at line 368 of file rc_setting.h.
Referenced by rcFramerateChoiceSettingWidget::choiceSelected(), rcNumericChoiceSettingWidget::choiceSelected(), rcFramerateChoiceSettingWidget::findChoice(), rcNumericChoiceSettingWidget::findChoice(), rcTextChoiceSettingWidget::findChoice(), and rcRateChoiceSettingWidget::findChoice().
   {
     return _value;
   }
virtual const char* rcSettingChoice::getText (void) const inline virtual
Definition at line 374 of file rc_setting.h.
Referenced by rcTextChoiceSettingWidget::choiceSelected(), rcTextChoiceSettingWidget::findChoice(), rcFramerateChoiceSettingWidget::rcFramerateChoiceSettingWidget(), rcMenuChoiceSettingWidget::rcMenuChoiceSettingWidget(), rcNumericChoiceSettingWidget::rcNumericChoiceSettingWidget(), rcRateChoiceSettingWidget::rcRateChoiceSettingWidget(), rcTextChoiceSettingWidget::rcTextChoiceSettingWidget(), and rcTextChoiceSettingWidget::settingChanged().
   {
     return _text;
   }
virtual int rcSettingChoice::getValue (void) const inline virtual
Definition at line 362 of file rc_setting.h.
Referenced by rcMenuChoiceSettingWidget::choiceSelected(), rcRateChoiceSettingWidget::choiceSelected(), rcMenuChoiceSettingWidget::findChoice(), rcChoiceRadioButton::rcChoiceRadioButton(), and rcTextChoiceSettingWidget::settingChanged().
   {
     return (int)_value; // Coerce the float to an int
   }
Member Data Documentation
const char* rcSettingChoice::_description
Definition at line 387 of file rc_setting.h.
const char* rcSettingChoice::_text
Definition at line 386 of file rc_setting.h.
Referenced by rcSettingInfo::rcSettingInfo().
float rcSettingChoice::_value
Definition at line 385 of file rc_setting.h.
The documentation for this struct was generated from the following file:
include/baseUI/rc_setting.h