Visible: include/stlplus/subprocesses.hpp File Reference
subprocesses.hpp File Reference
#include "os_fixes.hpp"
#include "textio.hpp"
#include "string_vectorio.hpp"
#include <vector>
#include <string>
#include <map>
Classes
class arg_vector
class env_vector
class subprocess
class backtick_subprocess
class async_subprocess
Macros
#define ENVIRON_TYPE char**
#define PID_TYPE int
#define PIPE_TYPE int
Functions
otext & operator<< (otext &, const arg_vector &)
otext & operator<< (otext &, const env_vector &)
std::vector< std::string > backtick (const std::string &path, const arg_vector &argv)
std::vector< std::string > backtick (const std::string &command_line)
Macro Definition Documentation
#define ENVIRON_TYPE char**
Definition at line 104 of file subprocesses.hpp.
#define PID_TYPE int
Definition at line 156 of file subprocesses.hpp.
#define PIPE_TYPE int
Definition at line 157 of file subprocesses.hpp.
Function Documentation
std::vector<std::string> backtick (const std::string & path, const arg_vector & argv)
Definition at line 1424 of file subprocesses.cpp.
References backtick_subprocess::spawn(), and backtick_subprocess::text().
 {
   backtick_subprocess sub;
   sub.spawn(path, argv);
   return sub.text();
 }
std::vector<std::string> backtick (const std::string & command_line)
Definition at line 1431 of file subprocesses.cpp.
References backtick_subprocess::spawn(), and backtick_subprocess::text().
 {
   backtick_subprocess sub;
   sub.spawn(command_line);
   return sub.text();
 }
otext& operator<< (otext & , const arg_vector &)
Definition at line 346 of file subprocesses.cpp.
References arg_vector::image().
 {
   return t << a.image();
 }
otext& operator<< (otext & , const env_vector &)
Definition at line 758 of file subprocesses.cpp.
References endl(), env_vector::get(), and env_vector::size().
 {
   for (unsigned i = 0; i < a.size(); i++)
   {
     std::pair<std::string,std::string> current = a.get(i);
     t << current.first << "=" << current.second << endl;
   }
   return t;
 }