Visible: include/stlplus/subprocesses.cpp File Reference
subprocesses.cpp File Reference
#include "os_fixes.hpp"
#include "subprocesses.hpp"
#include "debug.hpp"
#include "fileio.hpp"
#include "file_system.hpp"
#include "string_utilities.hpp"
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include <errno.h>
#include <sys/wait.h>
#include <unistd.h>
#include <fcntl.h>
Functions
static void skip_white (const std::string &command, unsigned &i)
static std::string get_argument (const std::string &command, unsigned &i)
static std::string make_argument (const std::string &arg)
static char * copy_string (const char *str)
otext & operator<< (otext &t, const arg_vector &a)
static unsigned envp_size (char *const *envp)
static void envp_extract (std::string &name, std::string &value, char *const *envp, unsigned &envi)
static void envp_append (const std::string &name, const std::string &value, char **envp, unsigned &envi)
static char ** envp_copy (char *const *envp)
static void envp_clear (char **&envp)
otext & operator<< (otext &t, const env_vector &a)
std::vector< std::string > backtick (const std::string &path, const arg_vector &argv)
std::vector< std::string > backtick (const std::string &command_line)
Variables
char ** environ
Function Documentation
std::vector<std::string> backtick (const std::string & path, const arg_vector & argv)
Definition at line 1424 of file subprocesses.cpp.
References backtick_subprocess::spawn(), and backtick_subprocess::text().
 {
   backtick_subprocess sub;
   sub.spawn(path, argv);
   return sub.text();
 }
std::vector<std::string> backtick (const std::string & command_line)
Definition at line 1431 of file subprocesses.cpp.
References backtick_subprocess::spawn(), and backtick_subprocess::text().
 {
   backtick_subprocess sub;
   sub.spawn(command_line);
   return sub.text();
 }
static char* copy_string (const char * str) static
Definition at line 179 of file subprocesses.cpp.
Referenced by arg_vector::clear(), envp_append(), and arg_vector::insert().
 {
   char* result = new char[strlen(str)+1];
   strcpy(result,str);
   return result;
 }
static void envp_append (const std::string & name, const std::string & value, char ** envp, unsigned & envi) static
Definition at line 442 of file subprocesses.cpp.
References copy_string().
Referenced by env_vector::add(), envp_copy(), and env_vector::remove().
 {
   std::string entry = name + "=" + value;
   envp[envi] = copy_string(entry.c_str());
   envi++;
   envp[envi] = 0;
 }
static void envp_clear (char **& envp) static
Definition at line 466 of file subprocesses.cpp.
Referenced by env_vector::add(), env_vector::clear(), and env_vector::remove().
 {
   if (envp)
   {
     for (unsigned i = 0; envp[i]; i++)
       delete[] envp[i];
     delete[] envp;
     envp = 0;
   }
 }
static char** envp_copy (char *const * envp) static
Definition at line 450 of file subprocesses.cpp.
References envp_append(), envp_extract(), and envp_size().
Referenced by env_vector::env_vector(), and env_vector::operator=().
 {
   unsigned size = envp_size(envp);
   char** result = new char*[size];
   unsigned i = 0;
   unsigned j = 0;
   while(envp[i])
   {
     std::string name;
     std::string value;
     envp_extract(name, value, envp, i);
     envp_append(name, value, result, j);
   }
   return result;
 }
static void envp_extract (std::string & name, std::string & value, char *const * envp, unsigned & envi) static
Definition at line 428 of file subprocesses.cpp.
Referenced by env_vector::add(), envp_copy(), env_vector::get(), and env_vector::remove().
 {
   name = "";
   value = "";
   if (!envp[envi]) return;
   unsigned i = 0;
   while(envp[envi][i] != '=')
     name += envp[envi][i++];
   i++;
   while(envp[envi][i])
     value += envp[envi][i++];
   envi++;
 }
static unsigned envp_size (char *const * envp) static
Definition at line 420 of file subprocesses.cpp.
Referenced by env_vector::add(), envp_copy(), and env_vector::remove().
 {
   unsigned size = 0;
   while(envp[size]) size++;
   size++;
   return size;
 }
static std::string get_argument (const std::string & command, unsigned & i) static
Definition at line 69 of file subprocesses.cpp.
Referenced by arg_vector::operator=().
 {
   std::string result;
   bool squote = false;
   bool dquote = false;
   bool escaped = false;
   for ( ; i < command.size(); i++)
   {
     char ch = command[i];
     if (!squote && !dquote && !escaped && isspace(ch)) break;
     if (escaped)
     {
       result += ch;
       escaped = false;
     }
     else if (squote)
     {
       if (ch == '\'')
         squote = false;
       else
         result += ch;
     }
     else if (ch == '\\')
       escaped = true;
     else if (dquote)
     {
       if (ch == '\"')
         dquote = false;
       else
         result += ch;
     }
     else if (ch == '\'')
       squote = true;
     else if (ch == '\"')
       dquote = true;
     else
       result += ch;
   }
   return result;
 }
static std::string make_argument (const std::string & arg) static
Definition at line 145 of file subprocesses.cpp.
Referenced by arg_vector::image().
 {
   std::string result;
   bool needs_quotes = false;
   for (unsigned i = 0; i < arg.size(); i++)
   {
     switch (arg[i])
     {
       // set of characters requiring escapes
     case '\\': case '\'': case '\"': case '`': case '(': case ')':
     case '&': case '|': case '<': case '>': case '*': case '?': case '!':
       result += '\\';
       result += arg[i];
       break;
       // set of whitespace characters that force quoting
     case ' ':
       result += arg[i];
       needs_quotes = true;
       break;
     default:
       result += arg[i];
       break;
     }
   }
   if (needs_quotes)
   {
     result.insert(result.begin(), '"');
     result += '"';
   }
   return result;
 }
otext& operator<< (otext & t, const arg_vector & a)
Definition at line 346 of file subprocesses.cpp.
References arg_vector::image().
 {
   return t << a.image();
 }
otext& operator<< (otext & t, const env_vector & a)
Definition at line 758 of file subprocesses.cpp.
References endl(), env_vector::get(), and env_vector::size().
 {
   for (unsigned i = 0; i < a.size(); i++)
   {
     std::pair<std::string,std::string> current = a.get(i);
     t << current.first << "=" << current.second << endl;
   }
   return t;
 }
static void skip_white (const std::string & command, unsigned & i) static
Definition at line 30 of file subprocesses.cpp.
Referenced by arg_vector::operator=().
 {
   while(i < command.size() && isspace(command[i]))
     i++;
 }
Variable Documentation
char** environ