Visible: include/stlplus/textio.cpp File Reference
textio.cpp File Reference
#include "os_fixes.hpp"
#include "textio.hpp"
#include "string_utilities.hpp"
#include <ctype.h>
Functions
static std::string textio_error_string (int error)
std::string to_string (otext::newline_t mode)
std::string to_string (otext::open_t mode)
void flush (otext &ot)
void endl (otext &ot)
void close (otext &ot)
void hex (otext &ot)
void oct (otext &ot)
void dec (otext &ot)
std::string to_string (itext::newline_t mode)
static std::string get_token (itext &str)
void skipwhite (itext &it)
void skiponewhite (itext &it)
void skipspaces (itext &it)
void skipline (itext &it)
void skipendl (itext &it)
void close (itext &it)
Variables
const int textio_uninitialised = -1
const int textio_put_failed = -2
const int textio_format_error = -3
const int textio_get_failed = -4
const int textio_open_failed = -5
Function Documentation
void close (otext & ot)
Definition at line 593 of file textio.cpp.
References otext::close().
Referenced by _tiffCloseProc(), subprocess::close_stderr(), async_subprocess::close_stderr(), subprocess::close_stdin(), async_subprocess::close_stdin(), subprocess::close_stdout(), async_subprocess::close_stdout(), subprocess::spawn(), async_subprocess::spawn(), and TIFFOpen().
 {
   ot.close();
 }
void close (itext & it)
Definition at line 1075 of file textio.cpp.
References itext::close().
 {
   it.close();
 }
void dec (otext & ot)
Definition at line 608 of file textio.cpp.
References otext::set_integer_radix().
Referenced by rcShape::peakDetect1d().
 {
   ot.set_integer_radix(10);
 }
void endl (otext & ot)
Definition at line 588 of file textio.cpp.
References newline, and otext::put().
Referenced by _printCommands(), _sm2out(), rcVideoTrackImpl::addSegment(), rcMovieConverterToQT::addVideoSamplesToMedia(), rcEngineImpl::analyzeFocusArea(), rcKinetoscope::associate(), rcImageCanvasGL::buildImageDlist(), rcVideoCache::camLoad(), rcEngineBaseImpl::checkSettings(), rcEngineMovieSaver::closeHdlr(), rcVideoCache::cnvLoad(), rcPolygon::contains(), rcMovieConverterToQT::convert(), rcMovieConverterToRfy::convert(), rcPolygon::convexComparedToConvex(), rcPolygon::convexIntersection(), rcTrackManager::copyTrackToClipboard(), rcPolygon::createConvexHull(), rcMovieConverterToQT::createQTMovie(), rcMovieConverterToRfy::createRfyMovie(), rcModelDomain::customEvent(), rcValueHistogram::debugDisplay(), rcImageCanvasGL::detectAppleExtensions(), dcam_formats::displayFormat(), displayOpenGLError(), displayOpenGLInfo(), rcImageCanvasGL::drawModelRect(), rcSettingCategory::dump(), rcCameraMapper::dump(), rcPointScan::dump(), rcCameraMapper::dump_capabilities(), rcModelDomain::dumpPolys(), rcKinetoscope::dumpPolys(), rcImageCanvasGL::enableCellGroup(), rcXMLParser::endDocument(), rcVideoCache::expLoad(), rcCSVExporter::exportExperiment(), rcNativeExporter::exportExperiment(), rcExperimentImpl::exportMovie(), rcCSVExporter::exportTracks(), rcPolygon::findPeak(), rcGenMovieFile::flush(), general_exception::general_exception(), generateExpansionMovie(), generateRandomMovie(), generateTinyMovie(), generateTranslationMovie(), rcPolygon::genMinEnclosingRect(), rcPolygon::genMinRectBounds(), rcMuscleSegmenter::genPolygons(), GetCameraProperty(), rcCameraMapper::GetCameraProperty(), TIFFImageIO::GetColor(), rcTrackManager::getTrackInfo(), rcGlob::globErrorHandler(), rcVideoCache::headerLoadRev0(), rcVideoCache::headerLoadRev1(), rcVideoCache::headerLoadRev2(), rcNativeImporter::importExperiment(), TIFFReaderInternal::Initialize(), InitializeMungData2(), rcSharedFrameBufPtr::internalLock(), rcSharedFrameBufPtr::internalUnlock(), rcPolygon::isValid(), rcTimeline::keyPressEvent(), rcEngineMovieCapture::killSaveThread(), rcEngineImpl::loadFrames(), rcEngineImpl::loadImages(), rcEngineImpl::loadMovie(), rcImageCanvasGL::loadrcWindow(), rcMovieFileOrgExt::log(), rcMovieFileConvExt::log(), rcMovieFileCamExt::log(), rcMovieFileExpExt::log(), main(), MGIdleTimer(), rcEngineImpl::modelTracker(), rcImageCanvasGL::mouseReleaseEvent(), rcEngineImpl::muscleTracker(), rcKinetoscope::newGeneration(), nextScale(), rcTrackImpl::nextSegmentStart(), rcBatchExperimentObserver::notifyBlitData(), rcBatchExperimentObserver::notifyBlitGraphics(), rcBatchExperimentObserver::notifyError(), rcModelDomain::notifyLockApp(), rcBatchExperimentObserver::notifyStatus(), rcBatchExperimentObserver::notifyWarning(), NR::nrerror(), operator<<(), rcSharedFrameBufPtr::operator=(), operator==(), rcVideoCache::orgLoad(), rcTimeline::paintScalarTrack(), rcPolygon::parallelInter(), rcNativeImporter::parseExperimentData(), rcNativeImporter::parseFrame(), rcNativeImporter::parseGraphicsCollection(), rcNativeImporter::parseGroup(), rcNativeImporter::parseSetting(), rcNativeImporter::parseSettingCategory(), rcNativeImporter::parseTime(), rcNativeImporter::parseTrack(), rcNativeImporter::parseValue(), rcShape::peakDetect1d(), PeakSpotter::PeakSpotter(), error_handler::plaintext(), rcEngineMoviePlayback::playbackCleanup(), rcCustomEventManager::postEvent(), lm_library::pretty_print(), library_manager::pretty_print(), prevScale(), print(), rcWindow::print(), lm_library::print(), lm_unit::print_long(), lm_library::print_long(), rcShape::printCache(), rcSharedFrameBufPtr::printState(), rcEngineImpl::process(), rcEngineImpl::processCapturedData(), processControlRequests(), rcCustomEventManager::processedEvent(), rcNativeExporter::produceElementCount(), rcNativeExporter::produceTracks(), rcConversionProgress::progress(), rcGraphicsSegment::rcGraphicsSegment(), rcImageCanvasGL::rcImageCanvasGL(), rcMutualInfoGrouping::rcMutualInfoGrouping(), rcPositionSegment::rcPositionSegment(), rcScalarSegment::rcScalarSegment(), rcSharedFrameBufPtr::rcSharedFrameBufPtr(), rcVideoSegment::rcVideoSegment(), rcVisibleBatchUsage(), TIFFImageIO::Read(), rcKinetoscope::reconcileNewGeneration(), rcWriterManager::renameEntropyTrack(), rcEngineImpl::reportOnBadGrabber(), rcEngineImpl::reset(), rfAssociate(), rfCompareFrames(), rfCompareMovies(), rfCompareReifyMovies(), rfConvertMovie(), rfConvertTwoMovies(), rfCountMovieFrames(), rfDCAMVideoCapture(), rfDivisionReport(), rfDumpMatrix(), rfGenerateTimeline(), rfGetCameraMaxFrameRate(), rfGetHostInfo(), rfOfCellsAndPolys(), rfPRINT_STL_ELEMENTS(), rfPrintCorrSpace(), rfRegisteredWindows(), rfSetCapability(), rcCameraMapper::rfSetCapability(), rcVideoCache::rcVideoCachePrefetchUnit::run(), ini_file::save_file(), library_manager::save_mappings(), rcEngineImpl::saveFrames(), segment(), rcPolygon::segmentInter(), rcImageCanvasGL::select(), rcEngineImpl::setCaptureInfo(), rcEngineImpl::setFromArgs(), rcExperimentDomainImpl::setInternalState(), setProperty(), rcEngineImpl::setSettingValue(), rcTrackManager::setTrackInfo(), SetUpDisplayCallback(), rcEngineMoviePlayback::setupTimeCtrlPlayback(), rcEngineImpl::shutdown(), sobelEdgeProcess(), rcEngineImpl::start(), rcXMLParser::startElement(), rcKinetoscope::temporalResults(), rcWindow::tiff(), rcModelDomain::timerTick(), PeakSpotter::to_csv(), rcVideoCache::tocLoadFromTOC(), rcVisualTarget::update(), rcVisualFunction::update(), rcMonitor::updateCachedImage(), rcTrackPanel::updateCamera(), rcEngineImpl::updateCameraLog(), rcEngineImpl::updateCaptureLog(), rcEngineImpl::updateConversionLog(), rcMonitor::updateDisplay(), rcControlPanel::updateSelectionState(), rcTrackPanel::updateSource(), rcTrackPanel::updateState(), rcTrackPanel::updateTrackGroups(), useFormat7(), VDGETGAIN(), VDGETSHUTTER(), VDSETGAIN(), VDSETSHUTTER(), yourDisplayCallback(), rcSharedFrameBufPtr::~rcSharedFrameBufPtr(), and rcVideoCache::~rcVideoCache().
 {
   ot.put(newline);
 }
void flush (otext & ot)
Definition at line 583 of file textio.cpp.
References otext::flush().
Referenced by error_handler::error(), error_handler::fatal(), rcEngineFocusData::flushFocusData(), error_handler::information(), main(), operator<<(), error_handler::plaintext(), and error_handler::warning().
 {
   ot.flush();
 }
static std::string get_token (itext & str) static
Definition at line 847 of file textio.cpp.
References itext::get(), itext::peek(), and skipwhite().
Referenced by itext::operator>>().
 {
   // Keep number handling simple by just getting a token
   // let the string-to-numeric conversions detect any errors
   // TODO - be fussier and allow other delimiters
   std::string result;
   int ch = 0;
   skipwhite(str);
   // get token
   for (ch = str.peek(); ch !=-1 && !isspace(ch); ch = str.peek())
     result += (char)str.get();
   return result;
 }
void hex (otext & ot)
Definition at line 598 of file textio.cpp.
References otext::set_integer_radix().
Referenced by simage(), to_string(), and uimage().
 {
   ot.set_integer_radix(16);
 }
void oct (otext & ot)
Definition at line 603 of file textio.cpp.
References otext::set_integer_radix().
 {
   ot.set_integer_radix(8);
 }
void skipendl (itext & it)
Definition at line 1066 of file textio.cpp.
References itext::get(), newline, and itext::peek().
 {
   for (int ch = it.peek(); ch != -1 && isspace(ch); ch = it.peek())
   {
     it.get();
     if (ch==newline) break;
   }
 }
void skipline (itext & it)
Definition at line 1057 of file textio.cpp.
References itext::get(), newline, and itext::peek().
 {
   for (int ch = it.peek(); ch !=-1 ; ch = it.peek())
   {
     it.get();
     if (ch==newline) break;
   }
 }
void skiponewhite (itext & it)
Definition at line 1044 of file textio.cpp.
References itext::get(), and itext::peek().
 {
   int ch = it.peek();
   if (ch != -1 && isspace(ch))
     it.get();
 }
void skipspaces (itext & it)
Definition at line 1051 of file textio.cpp.
References itext::get(), newline, and itext::peek().
 {
   for (int ch = it.peek(); ch != -1 && ch != newline && isspace(ch); ch = it.peek())
     it.get();
 }
void skipwhite (itext & it)
Definition at line 1038 of file textio.cpp.
References itext::get(), and itext::peek().
Referenced by get_token().
 {
   for (int ch = it.peek(); ch != -1 && isspace(ch); ch = it.peek())
     it.get();
 }
static std::string textio_error_string (int error) static
Definition at line 22 of file textio.cpp.
References textio_format_error, textio_get_failed, textio_open_failed, textio_put_failed, textio_uninitialised, and to_string().
Referenced by otext::error_string(), itext::error_string(), obuff::error_string(), and ibuff::error_string().
 {
   switch(error)
   {
   case 0: return std::string("no error");
   case textio_uninitialised: return std::string("the TextIO device hasn't been initialised");
   case textio_put_failed: return std::string("an attempt to put text failed");
   case textio_format_error: return std::string("a format error was found reading input");
   case textio_get_failed: return std::string("an attempt to get text failed");
   case textio_open_failed: return std::string("the device could not be opened");
   default: return std::string("unknown error number " + to_string(error));
   }
 }
std::string to_string (otext::newline_t mode)
Definition at line 40 of file textio.cpp.
References otext::binary_mode, otext::macos_mode, otext::msdos_mode, and otext::unix_mode.
 {
   switch(mode)
   {
   case otext::binary_mode: return std::string("binary");
   case otext::unix_mode: return std::string("unix");
   case otext::msdos_mode: return std::string("msdos");
   case otext::macos_mode: return std::string("macos");
   }
   return std::string("*unknown mode*");
 }
std::string to_string (otext::open_t mode)
Definition at line 52 of file textio.cpp.
References otext::append, and otext::overwrite.
 {
   switch(mode)
   {
   case otext::overwrite: return std::string("overwrite");
   case otext::append: return std::string("append");
   }
   return std::string("*unknown mode*");
 }
std::string to_string (itext::newline_t mode)
Definition at line 617 of file textio.cpp.
References itext::binary_mode, and itext::convert_mode.
 {
   switch(mode)
   {
   case itext::binary_mode: return std::string("binary");
   case itext::convert_mode: return std::string("convert");
   }
   return std::string("*unknown mode*");
 }
Variable Documentation
const int textio_format_error = -3
Definition at line 18 of file textio.cpp.
Referenced by otext::operator<<(), operator<<(), operator>>(), itext::operator>>(), and textio_error_string().
const int textio_get_failed = -4
Definition at line 19 of file textio.cpp.
Referenced by iiobuff::get(), iiobuff::peek(), and textio_error_string().
const int textio_open_failed = -5
Definition at line 20 of file textio.cpp.
Referenced by ofbuff::open(), ifbuff::open(), and textio_error_string().
const int textio_put_failed = -2
Definition at line 17 of file textio.cpp.
Referenced by oiobuff::flush(), ofbuff::flush(), oiobuff::put(), otext::put(), and textio_error_string().
const int textio_uninitialised = -1
Definition at line 16 of file textio.cpp.
Referenced by otext::error_number(), itext::error_number(), otext::error_string(), itext::error_string(), and textio_error_string().