Visible: src/util/code/tif_extension.c File Reference
tif_extension.c File Reference
#include "tiffiop.h"
Functions
int TIFFGetTagListCount (TIFF *tif)
ttag_t TIFFGetTagListEntry (TIFF *tif, int tag_index)
TIFFTagMethods * TIFFAccessTagMethods (TIFF *tif)
void * TIFFGetClientInfo (TIFF *tif, const char *name)
void TIFFSetClientInfo (TIFF *tif, void *data, const char *name)
Function Documentation
TIFFTagMethods* TIFFAccessTagMethods (TIFF * tif)
Definition at line 60 of file tif_extension.c.
References tiff::tif_tagmethods.
 {
     return &(tif->tif_tagmethods);
 }
void* TIFFGetClientInfo (TIFF * tif, const char * name)
Definition at line 66 of file tif_extension.c.
References client_info::data, client_info::name, client_info::next, NULL, and tiff::tif_clientinfo.
 {
     TIFFClientInfoLink *link = tif->tif_clientinfo;
     while( link != NULL && strcmp(link->name,name) != 0 )
         link = link->next;
     if( link != NULL )
         return link->data;
     else
         return NULL;
 }
int TIFFGetTagListCount (TIFF * tif)
Definition at line 36 of file tif_extension.c.
References TIFFDirectory::td_customValueCount, and tiff::tif_dir.
Referenced by TIFFReaderInternal::Open(), and TIFFPrintDirectory().
 {
     TIFFDirectory* td = &tif->tif_dir;
     return td->td_customValueCount;
 }
ttag_t TIFFGetTagListEntry (TIFF * tif, int tag_index)
Definition at line 44 of file tif_extension.c.
References TIFFFieldInfo::field_tag, _TIFFTagValue::info, TIFFDirectory::td_customValueCount, TIFFDirectory::td_customValues, and tiff::tif_dir.
Referenced by TIFFReaderInternal::Open(), and TIFFPrintDirectory().
 {
     TIFFDirectory* td = &tif->tif_dir;
     if( tag_index < 0 || tag_index >= td->td_customValueCount )
         return (ttag_t) -1;
     else
         return td->td_customValues[tag_index].info->field_tag;
 }
void TIFFSetClientInfo (TIFF * tif, void * data, const char * name)
Definition at line 80 of file tif_extension.c.
References _TIFFmalloc(), client_info::data, client_info::name, client_info::next, NULL, and tiff::tif_clientinfo.
 {
     TIFFClientInfoLink *link = tif->tif_clientinfo;
     /*
     ** Do we have an existing link with this name?  If so, just
     ** set it.
     */
     while( link != NULL && strcmp(link->name,name) != 0 )
         link = link->next;
     if( link != NULL )
     {
         link->data = data;
         return;
     }
     /*
     ** Create a new link.
     */
     link = (TIFFClientInfoLink *) _TIFFmalloc(sizeof(TIFFClientInfoLink));
     assert (link != NULL);
     link->next = tif->tif_clientinfo;
     link->name = (char *) _TIFFmalloc(strlen(name)+1);
     assert (link->name != NULL);
     strcpy(link->name, name);
     link->data = data;
     tif->tif_clientinfo = link;
 }