Visible: src/util/code/tif_compress.c File Reference
tif_compress.c File Reference
#include "tiffiop.h"
Classes
struct _codec
Typedefs
typedef struct _codec codec_t
Functions
static int TIFFNoEncode (TIFF *tif, const char *method)
int _TIFFNoRowEncode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
int _TIFFNoStripEncode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
int _TIFFNoTileEncode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
static int TIFFNoDecode (TIFF *tif, const char *method)
int _TIFFNoRowDecode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
int _TIFFNoStripDecode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
int _TIFFNoTileDecode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
int _TIFFNoSeek (TIFF *tif, uint32 off)
int _TIFFNoPreCode (TIFF *tif, tsample_t s)
static int _TIFFtrue (TIFF *tif)
static void _TIFFvoid (TIFF *tif)
void _TIFFSetDefaultCompressionState (TIFF *tif)
int TIFFSetCompressionScheme (TIFF *tif, int scheme)
const TIFFCodec * TIFFFindCODEC (uint16 scheme)
TIFFCodec * TIFFRegisterCODEC (uint16 scheme, const char *name, TIFFInitMethod init)
void TIFFUnRegisterCODEC (TIFFCodec *c)
TIFFCodec * TIFFGetConfiguredCODECs ()
Variables
static codec_t * registeredCODECS = NULL
Typedef Documentation
typedef struct _codec codec_t
Function Documentation
int _TIFFNoPreCode (TIFF * tif, tsample_t s)
Definition at line 117 of file tif_compress.c.
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) tif; (void) s;
     return (1);
 }
int _TIFFNoRowDecode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s)
Definition at line 87 of file tif_compress.c.
References TIFFNoDecode().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) pp; (void) cc; (void) s;
     return (TIFFNoDecode(tif, "scanline"));
 }
int _TIFFNoRowEncode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s)
Definition at line 51 of file tif_compress.c.
References TIFFNoEncode().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) pp; (void) cc; (void) s;
     return (TIFFNoEncode(tif, "scanline"));
 }
int _TIFFNoSeek (TIFF * tif, uint32 off)
Definition at line 108 of file tif_compress.c.
References tiff::tif_clientdata, tiff::tif_name, and TIFFErrorExt().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) off;
     TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
         "Compression algorithm does not support random access");
     return (0);
 }
int _TIFFNoStripDecode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s)
Definition at line 94 of file tif_compress.c.
References TIFFNoDecode().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) pp; (void) cc; (void) s;
     return (TIFFNoDecode(tif, "strip"));
 }
int _TIFFNoStripEncode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s)
Definition at line 58 of file tif_compress.c.
References TIFFNoEncode().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) pp; (void) cc; (void) s;
     return (TIFFNoEncode(tif, "strip"));
 }
int _TIFFNoTileDecode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s)
Definition at line 101 of file tif_compress.c.
References TIFFNoDecode().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) pp; (void) cc; (void) s;
     return (TIFFNoDecode(tif, "tile"));
 }
int _TIFFNoTileEncode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s)
Definition at line 65 of file tif_compress.c.
References TIFFNoEncode().
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) pp; (void) cc; (void) s;
     return (TIFFNoEncode(tif, "tile"));
 }
void _TIFFSetDefaultCompressionState (TIFF * tif)
Definition at line 127 of file tif_compress.c.
References _TIFFDefaultStripSize(), _TIFFDefaultTileSize(), _TIFFNoPreCode(), _TIFFNoRowDecode(), _TIFFNoRowEncode(), _TIFFNoSeek(), _TIFFNoStripDecode(), _TIFFNoStripEncode(), _TIFFNoTileDecode(), _TIFFNoTileEncode(), _TIFFtrue(), _TIFFvoid(), tiff::tif_cleanup, tiff::tif_close, tiff::tif_decoderow, tiff::tif_decodestatus, tiff::tif_decodestrip, tiff::tif_decodetile, tiff::tif_defstripsize, tiff::tif_deftilesize, tiff::tif_encoderow, tiff::tif_encodestatus, tiff::tif_encodestrip, tiff::tif_encodetile, tiff::tif_flags, tiff::tif_postencode, tiff::tif_predecode, tiff::tif_preencode, tiff::tif_seek, tiff::tif_setupdecode, tiff::tif_setupencode, TIFF_NOBITREV, and TRUE.
Referenced by TIFFClientOpen(), and TIFFSetCompressionScheme().
 {
     tif->tif_decodestatus = TRUE;
     tif->tif_setupdecode = _TIFFtrue;
     tif->tif_predecode = _TIFFNoPreCode;
     tif->tif_decoderow = _TIFFNoRowDecode;
     tif->tif_decodestrip = _TIFFNoStripDecode;
     tif->tif_decodetile = _TIFFNoTileDecode;
     tif->tif_encodestatus = TRUE;
     tif->tif_setupencode = _TIFFtrue;
     tif->tif_preencode = _TIFFNoPreCode;
     tif->tif_postencode = _TIFFtrue;
     tif->tif_encoderow = _TIFFNoRowEncode;
     tif->tif_encodestrip = _TIFFNoStripEncode;
     tif->tif_encodetile = _TIFFNoTileEncode;
     tif->tif_close = _TIFFvoid;
     tif->tif_seek = _TIFFNoSeek;
     tif->tif_cleanup = _TIFFvoid;
     tif->tif_defstripsize = _TIFFDefaultStripSize;
     tif->tif_deftilesize = _TIFFDefaultTileSize;
     tif->tif_flags &= ~TIFF_NOBITREV;
 }
static int _TIFFtrue (TIFF * tif) static
Definition at line 123 of file tif_compress.c.
Referenced by _TIFFSetDefaultCompressionState().
 { (void) tif; return (1); }
static void _TIFFvoid (TIFF * tif) static
Definition at line 124 of file tif_compress.c.
Referenced by _TIFFSetDefaultCompressionState().
 { (void) tif; }
const TIFFCodec* TIFFFindCODEC (uint16 scheme)
Definition at line 177 of file tif_compress.c.
References _TIFFBuiltinCODECS, _codec::info, TIFFCodec::name, _codec::next, and TIFFCodec::scheme.
Referenced by _notConfigured(), TIFFIsCODECConfigured(), TIFFNoDecode(), TIFFNoEncode(), TIFFPrintDirectory(), and TIFFSetCompressionScheme().
 {
     const TIFFCodec* c;
     codec_t* cd;
     for (cd = registeredCODECS; cd; cd = cd->next)
         if (cd->info->scheme == scheme)
             return ((const TIFFCodec*) cd->info);
     for (c = _TIFFBuiltinCODECS; c->name; c++)
         if (c->scheme == scheme)
             return (c);
     return ((const TIFFCodec*) 0);
 }
TIFFCodec* TIFFGetConfiguredCODECs (void)
Get list of configured codecs, both built-in and registered by user. Caller is responsible to free this structure.
Returns
returns array of TIFFCodec records (the last record should be NULL) or NULL if function failed.
Definition at line 243 of file tif_compress.c.
References _TIFFBuiltinCODECS, _TIFFfree(), _TIFFmemcpy(), _TIFFmemset(), _TIFFrealloc(), TIFFCodec::name, _codec::next, NULL, TIFFCodec::scheme, and TIFFIsCODECConfigured().
 {
     int     i = 1;
         codec_t     *cd;
         const TIFFCodec *c;
     TIFFCodec   *codecs = NULL, *new_codecs;
         for (cd = registeredCODECS; cd; cd = cd->next) {
                 new_codecs = (TIFFCodec *)
             _TIFFrealloc(codecs, i * sizeof(TIFFCodec));
         if (!new_codecs) {
             _TIFFfree (codecs);
             return NULL;
         }
         codecs = new_codecs;
         _TIFFmemcpy(codecs + i - 1, cd, sizeof(TIFFCodec));
         i++;
     }
         for (c = _TIFFBuiltinCODECS; c->name; c++) {
                 if (TIFFIsCODECConfigured(c->scheme)) {
                         new_codecs = (TIFFCodec *)
                 _TIFFrealloc(codecs, i * sizeof(TIFFCodec));
             if (!new_codecs) {
                 _TIFFfree (codecs);
                 return NULL;
             }
             codecs = new_codecs;
             _TIFFmemcpy(codecs + i - 1, (const tdata_t)c, sizeof(TIFFCodec));
             i++;
         }
     }
     new_codecs = (TIFFCodec *) _TIFFrealloc(codecs, i * sizeof(TIFFCodec));
     if (!new_codecs) {
         _TIFFfree (codecs);
         return NULL;
     }
     codecs = new_codecs;
     _TIFFmemset(codecs + i - 1, 0, sizeof(TIFFCodec));
         return codecs;
 }
static int TIFFNoDecode (TIFF * tif, const char * method) static
Definition at line 72 of file tif_compress.c.
References TIFFCodec::name, TIFFDirectory::td_compression, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), and TIFFFindCODEC().
Referenced by _TIFFNoRowDecode(), _TIFFNoStripDecode(), and _TIFFNoTileDecode().
 {
     const TIFFCodec* c = TIFFFindCODEC(tif->tif_dir.td_compression);
     if (c)
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%s %s decoding is not implemented",
             c->name, method);
     else
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
             "Compression scheme %u %s decoding is not implemented",
             tif->tif_dir.td_compression, method);
     return (-1);
 }
static int TIFFNoEncode (TIFF * tif, const char * method) static
Definition at line 35 of file tif_compress.c.
References TIFFCodec::name, TIFFDirectory::td_compression, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), and TIFFFindCODEC().
Referenced by _TIFFNoRowEncode(), _TIFFNoStripEncode(), and _TIFFNoTileEncode().
 {
     const TIFFCodec* c = TIFFFindCODEC(tif->tif_dir.td_compression);
     if (c) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%s %s encoding is not implemented",
                           c->name, method);
     } else {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
               "Compression scheme %u %s encoding is not implemented",
             tif->tif_dir.td_compression, method);
     }
     return (-1);
 }
TIFFCodec* TIFFRegisterCODEC (uint16 scheme, const char * name, TIFFInitMethod init)
Definition at line 192 of file tif_compress.c.
References _TIFFmalloc(), _codec::info, TIFFCodec::init, TIFFCodec::name, _codec::next, NULL, registeredCODECS, TIFFCodec::scheme, and TIFFErrorExt().
 {
     codec_t* cd = (codec_t*)
         _TIFFmalloc(sizeof (codec_t) + sizeof (TIFFCodec) + strlen(name)+1);
     if (cd != NULL) {
         cd->info = (TIFFCodec*) ((tidata_t) cd + sizeof (codec_t));
         cd->info->name = (char*)
             ((tidata_t) cd->info + sizeof (TIFFCodec));
         strcpy(cd->info->name, name);
         cd->info->scheme = scheme;
         cd->info->init = init;
         cd->next = registeredCODECS;
         registeredCODECS = cd;
     } else {
         TIFFErrorExt(0, "TIFFRegisterCODEC",
             "No space to register compression scheme %s", name);
         return NULL;
     }
     return (cd->info);
 }
int TIFFSetCompressionScheme (TIFF * tif, int scheme)
Definition at line 151 of file tif_compress.c.
References _TIFFSetDefaultCompressionState(), TIFFCodec::init, and TIFFFindCODEC().
Referenced by _TIFFVSetField().
 {
     const TIFFCodec *c = TIFFFindCODEC((uint16) scheme);
     _TIFFSetDefaultCompressionState(tif);
     /*
      * Don't treat an unknown compression scheme as an error.
      * This permits applications to open files with data that
      * the library does not have builtin support for, but which
      * may still be meaningful.
      */
     return (c ? (*c->init)(tif, scheme) : 1);
 }
void TIFFUnRegisterCODEC (TIFFCodec * c)
Definition at line 215 of file tif_compress.c.
References _TIFFfree(), _codec::info, TIFFCodec::name, _codec::next, and TIFFErrorExt().
 {
     codec_t* cd;
     codec_t** pcd;
     for (pcd = &registeredCODECS; (cd = *pcd); pcd = &cd->next)
         if (cd->info == c) {
             *pcd = cd->next;
             _TIFFfree(cd);
             return;
         }
     TIFFErrorExt(0, "TIFFUnRegisterCODEC",
         "Cannot remove compression scheme %s; not registered", c->name);
 }
Variable Documentation
codec_t* registeredCODECS = NULL static
Definition at line 174 of file tif_compress.c.
Referenced by TIFFRegisterCODEC().