Visible: src/util/code/tif_error.c File Reference
tif_error.c File Reference
#include "tiffiop.h"
Functions
TIFFErrorHandler TIFFSetErrorHandler (TIFFErrorHandler handler)
TIFFErrorHandlerExt TIFFSetErrorHandlerExt (TIFFErrorHandlerExt handler)
void TIFFError (const char *module, const char *fmt,...)
void TIFFErrorExt (thandle_t fd, const char *module, const char *fmt,...)
Variables
TIFFErrorHandlerExt _TIFFerrorHandlerExt = NULL
Function Documentation
void TIFFError (const char * module, const char * fmt, ...)
Definition at line 51 of file tif_error.c.
References _TIFFerrorHandler, and _TIFFerrorHandlerExt.
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFerrorHandler)
         (*_TIFFerrorHandler)(module, fmt, ap);
     if (_TIFFerrorHandlerExt)
         (*_TIFFerrorHandlerExt)(0, module, fmt, ap);
     va_end(ap);
 }
void TIFFErrorExt (thandle_t fd, const char * module, const char * fmt, ...)
Definition at line 63 of file tif_error.c.
References _TIFFerrorHandler, and _TIFFerrorHandlerExt.
Referenced by _notConfigured(), _TIFFCheckMalloc(), _TIFFFieldWithName(), _TIFFFieldWithTag(), _TIFFgetMode(), _TIFFNoSeek(), _tiffSizeProc(), _TIFFVGetField(), _TIFFVSetField(), _TIFFWriteDirectory(), checkInkNamesString(), cvtRational(), DumpModeDecode(), EstimateStripByteCounts(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), initCIELabConversion(), initYCbCrConversion(), makebwmap(), makecmap(), MissingRequired(), multiply(), OkToChangeTag(), PredictorSetup(), setupMap(), summarize(), TIFFAdvanceDirectory(), TIFFAppendToStrip(), TIFFCheckRead(), TIFFCheckTile(), TIFFClientOpen(), TIFFComputeStrip(), TIFFFetchAnyArray(), TIFFFetchData(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFFillStrip(), TIFFFillTile(), TIFFGrowStrips(), TIFFLinkDirectory(), TIFFNoDecode(), TIFFNoEncode(), TIFFOpen(), TIFFRawStripSize(), TIFFReadBufferSetup(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFReadEncodedStrip(), TIFFReadEncodedTile(), TIFFReadRawStrip(), TIFFReadRawStrip1(), TIFFReadRawTile(), TIFFReadRawTile1(), TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), TIFFRegisterCODEC(), TIFFRewriteDirectory(), TIFFRGBAImageGet(), TIFFSeek(), TIFFUnlinkDirectory(), TIFFUnRegisterCODEC(), TIFFVGetFieldDefaulted(), TIFFVStripSize(), TIFFVTileSize(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWriteCheck(), TIFFWriteData(), TIFFWriteEncodedStrip(), TIFFWriteEncodedTile(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), TIFFWriteRationalArray(), TIFFWriteRawStrip(), TIFFWriteRawTile(), and TIFFWriteScanline().
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFerrorHandler)
         (*_TIFFerrorHandler)(module, fmt, ap);
     if (_TIFFerrorHandlerExt)
         (*_TIFFerrorHandlerExt)(fd, module, fmt, ap);
     va_end(ap);
 }
TIFFErrorHandler TIFFSetErrorHandler (TIFFErrorHandler handler)
Definition at line 35 of file tif_error.c.
References _TIFFerrorHandler.
Referenced by TIFFImageIO::CanReadFile().
 {
     TIFFErrorHandler prev = _TIFFerrorHandler;
     _TIFFerrorHandler = handler;
     return (prev);
 }
TIFFErrorHandlerExt TIFFSetErrorHandlerExt (TIFFErrorHandlerExt handler)
Definition at line 43 of file tif_error.c.
References _TIFFerrorHandlerExt.
 {
     TIFFErrorHandlerExt prev = _TIFFerrorHandlerExt;
     _TIFFerrorHandlerExt = handler;
     return (prev);
 }
Variable Documentation
TIFFErrorHandlerExt _TIFFerrorHandlerExt = NULL
Definition at line 32 of file tif_error.c.
Referenced by TIFFError(), TIFFErrorExt(), and TIFFSetErrorHandlerExt().