Visible: src/util/code/tif_predict.c File Reference
tif_predict.c File Reference
#include "tiffiop.h"
#include "tif_predict.h"
Macros
#define PredictorState(tif) ((TIFFPredictorState*) (tif)->tif_data)
#define REPEAT4(n, op)
#define FIELD_PREDICTOR (FIELD_CODEC+0) /* XXX */
#define N(a) (sizeof (a) / sizeof (a[0]))
Functions
static void horAcc8 (TIFF *, tidata_t, tsize_t)
static void horAcc16 (TIFF *, tidata_t, tsize_t)
static void swabHorAcc16 (TIFF *, tidata_t, tsize_t)
static void horDiff8 (TIFF *, tidata_t, tsize_t)
static void horDiff16 (TIFF *, tidata_t, tsize_t)
static void fpAcc (TIFF *, tidata_t, tsize_t)
static void fpDiff (TIFF *, tidata_t, tsize_t)
static int PredictorDecodeRow (TIFF *, tidata_t, tsize_t, tsample_t)
static int PredictorDecodeTile (TIFF *, tidata_t, tsize_t, tsample_t)
static int PredictorEncodeRow (TIFF *, tidata_t, tsize_t, tsample_t)
static int PredictorEncodeTile (TIFF *, tidata_t, tsize_t, tsample_t)
static int PredictorSetup (TIFF *tif)
static int PredictorSetupDecode (TIFF *tif)
static int PredictorSetupEncode (TIFF *tif)
static int PredictorVSetField (TIFF *tif, ttag_t tag, va_list ap)
static int PredictorVGetField (TIFF *tif, ttag_t tag, va_list ap)
static void PredictorPrintDir (TIFF *tif, FILE *fd, long flags)
int TIFFPredictorInit (TIFF *tif)
Variables
static const TIFFFieldInfo predictFieldInfo []
Macro Definition Documentation
#define FIELD_PREDICTOR (FIELD_CODEC+0) /* XXX */
Definition at line 509 of file tif_predict.c.
Referenced by PredictorPrintDir(), and PredictorVSetField().
#define N (a) (sizeof (a) / sizeof (a[0]))
Definition at line 515 of file tif_predict.c.
Referenced by rcPointCorrelation::gen3by3Space(), rcPointCorrelation::gen5by5Space(), rcOptoKineticImage::genAccelEntropyImg(), rcOptoKineticImage::genKineticStats(), rcOptoKineticImage::genStdDevImg(), rcOptoKineticImage::genThetaEntropyImg(), rcOptoKineticImage::genVarImg(), rcOptoKineticImage::genVelEntropyImg(), segPoint(), and TIFFPredictorInit().
#define PredictorState (tif) ((TIFFPredictorState*) (tif)->tif_data)
Definition at line 35 of file tif_predict.c.
Referenced by fpAcc(), fpDiff(), horAcc16(), horAcc8(), horDiff16(), horDiff8(), PredictorDecodeRow(), PredictorDecodeTile(), PredictorEncodeRow(), PredictorEncodeTile(), PredictorPrintDir(), PredictorSetup(), PredictorSetupDecode(), PredictorSetupEncode(), PredictorVGetField(), PredictorVSetField(), swabHorAcc16(), and TIFFPredictorInit().
#define REPEAT4 (n, op)
Value:
switch (n) {        \
    default: { int i; for (i = n-4; i > 0; i--) { op; } } \
    case 4:  op;        \
    case 3:  op;        \
    case 2:  op;        \
    case 1:  op;        \
    case 0:  ;          \
    }
Definition at line 208 of file tif_predict.c.
Referenced by fpAcc(), fpDiff(), horAcc16(), horAcc8(), horDiff16(), horDiff8(), and swabHorAcc16().
Function Documentation
static void fpAcc (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 298 of file tif_predict.c.
References _TIFFfree(), _TIFFmalloc(), _TIFFmemcpy(), count(), PredictorState, REPEAT4, TIFFDirectory::td_bitspersample, and tiff::tif_dir.
Referenced by PredictorSetupDecode().
 {
     tsize_t stride = PredictorState(tif)->stride;
     uint32 bps = tif->tif_dir.td_bitspersample / 8;
     tsize_t wc = cc / bps;
     tsize_t count = cc;
     uint8 *cp = (uint8 *) cp0;
     uint8 *tmp = (uint8 *)_TIFFmalloc(cc);
     if (!tmp)
         return;
     while (count > stride) {
         REPEAT4(stride, cp[stride] += cp[0]; cp++)
         count -= stride;
     }
     _TIFFmemcpy(tmp, cp0, cc);
     cp = (uint8 *) cp0;
     for (count = 0; count < wc; count++) {
         uint32 byte;
         for (byte = 0; byte < bps; byte++) {
 #if WORDS_BIGENDIAN
             cp[bps * count + byte] = tmp[byte * wc + count];
 #else
             cp[bps * count + byte] =
                 tmp[(bps - byte - 1) * wc + count];
 #endif
         }
     }
     _TIFFfree(tmp);
 }
static void fpDiff (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 444 of file tif_predict.c.
References _TIFFfree(), _TIFFmalloc(), _TIFFmemcpy(), count(), PredictorState, REPEAT4, TIFFDirectory::td_bitspersample, and tiff::tif_dir.
Referenced by PredictorSetupEncode().
 {
     tsize_t stride = PredictorState(tif)->stride;
     uint32 bps = tif->tif_dir.td_bitspersample / 8;
     tsize_t wc = cc / bps;
     tsize_t count;
     uint8 *cp = (uint8 *) cp0;
     uint8 *tmp = (uint8 *)_TIFFmalloc(cc);
     if (!tmp)
         return;
     _TIFFmemcpy(tmp, cp0, cc);
     for (count = 0; count < wc; count++) {
         uint32 byte;
         for (byte = 0; byte < bps; byte++) {
 #if WORDS_BIGENDIAN
             cp[byte * wc + count] = tmp[bps * count + byte];
 #else
             cp[(bps - byte - 1) * wc + count] =
                 tmp[bps * count + byte];
 #endif
         }
     }
     _TIFFfree(tmp);
     cp = (uint8 *) cp0;
     cp += cc - stride - 1;
     for (count = cc; count > stride; count -= stride)
         REPEAT4(stride, cp[stride] -= cp[0]; cp--)
 }
static void horAcc16 (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 279 of file tif_predict.c.
References PredictorState, and REPEAT4.
Referenced by PredictorSetupDecode().
 {
     tsize_t stride = PredictorState(tif)->stride;
     uint16* wp = (uint16*) cp0;
     tsize_t wc = cc / 2;
     if (wc > stride) {
         wc -= stride;
         do {
             REPEAT4(stride, wp[stride] += wp[0]; wp++)
             wc -= stride;
         } while ((int32) wc > 0);
     }
 }
static void horAcc8 (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 219 of file tif_predict.c.
References PredictorState, and REPEAT4.
Referenced by PredictorSetupDecode().
 {
     tsize_t stride = PredictorState(tif)->stride;
     char* cp = (char*) cp0;
     if (cc > stride) {
         cc -= stride;
         /*
          * Pipeline the most common cases.
          */
         if (stride == 3)  {
             unsigned int cr = cp[0];
             unsigned int cg = cp[1];
             unsigned int cb = cp[2];
             do {
                 cc -= 3, cp += 3;
                 cp[0] = (char) (cr += cp[0]);
                 cp[1] = (char) (cg += cp[1]);
                 cp[2] = (char) (cb += cp[2]);
             } while ((int32) cc > 0);
         } else if (stride == 4)  {
             unsigned int cr = cp[0];
             unsigned int cg = cp[1];
             unsigned int cb = cp[2];
             unsigned int ca = cp[3];
             do {
                 cc -= 4, cp += 4;
                 cp[0] = (char) (cr += cp[0]);
                 cp[1] = (char) (cg += cp[1]);
                 cp[2] = (char) (cb += cp[2]);
                 cp[3] = (char) (ca += cp[3]);
             } while ((int32) cc > 0);
         } else  {
             do {
                 REPEAT4(stride, cp[stride] =
                     (char) (cp[stride] + *cp); cp++)
                 cc -= stride;
             } while ((int32) cc > 0);
         }
     }
 }
static void horDiff16 (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 423 of file tif_predict.c.
References PredictorState, REPEAT4, and TIFFPredictorState::stride.
Referenced by PredictorSetupEncode().
 {
     TIFFPredictorState* sp = PredictorState(tif);
     tsize_t stride = sp->stride;
     int16 *wp = (int16*) cp0;
     tsize_t wc = cc/2;
     if (wc > stride) {
         wc -= stride;
         wp += wc - 1;
         do {
             REPEAT4(stride, wp[stride] -= wp[0]; wp--)
             wc -= stride;
         } while ((int32) wc > 0);
     }
 }
static void horDiff8 (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 378 of file tif_predict.c.
References PredictorState, REPEAT4, and TIFFPredictorState::stride.
Referenced by PredictorSetupEncode().
 {
     TIFFPredictorState* sp = PredictorState(tif);
     tsize_t stride = sp->stride;
     char* cp = (char*) cp0;
     if (cc > stride) {
         cc -= stride;
         /*
          * Pipeline the most common cases.
          */
         if (stride == 3) {
             int r1, g1, b1;
             int r2 = cp[0];
             int g2 = cp[1];
             int b2 = cp[2];
             do {
                 r1 = cp[3]; cp[3] = r1-r2; r2 = r1;
                 g1 = cp[4]; cp[4] = g1-g2; g2 = g1;
                 b1 = cp[5]; cp[5] = b1-b2; b2 = b1;
                 cp += 3;
             } while ((int32)(cc -= 3) > 0);
         } else if (stride == 4) {
             int r1, g1, b1, a1;
             int r2 = cp[0];
             int g2 = cp[1];
             int b2 = cp[2];
             int a2 = cp[3];
             do {
                 r1 = cp[4]; cp[4] = r1-r2; r2 = r1;
                 g1 = cp[5]; cp[5] = g1-g2; g2 = g1;
                 b1 = cp[6]; cp[6] = b1-b2; b2 = b1;
                 a1 = cp[7]; cp[7] = a1-a2; a2 = a1;
                 cp += 4;
             } while ((int32)(cc -= 4) > 0);
         } else {
             cp += cc - 1;
             do {
                 REPEAT4(stride, cp[stride] -= cp[0]; cp--)
             } while ((int32)(cc -= stride) > 0);
         }
     }
 }
static int PredictorDecodeRow (TIFF * tif, tidata_t op0, tsize_t occ0, tsample_t s) static
Definition at line 335 of file tif_predict.c.
References TIFFPredictorState::coderow, NULL, TIFFPredictorState::pfunc, and PredictorState.
Referenced by PredictorSetupDecode().
 {
     TIFFPredictorState *sp = PredictorState(tif);
     assert(sp != NULL);
     assert(sp->coderow != NULL);
     assert(sp->pfunc != NULL);
     if ((*sp->coderow)(tif, op0, occ0, s)) {
         (*sp->pfunc)(tif, op0, occ0);
         return 1;
     } else
         return 0;
 }
static int PredictorDecodeTile (TIFF * tif, tidata_t op0, tsize_t occ0, tsample_t s) static
Definition at line 357 of file tif_predict.c.
References TIFFPredictorState::codetile, NULL, TIFFPredictorState::pfunc, PredictorState, and TIFFPredictorState::rowsize.
Referenced by PredictorSetupDecode().
 {
     TIFFPredictorState *sp = PredictorState(tif);
     assert(sp != NULL);
     assert(sp->codetile != NULL);
     if ((*sp->codetile)(tif, op0, occ0, s)) {
         tsize_t rowsize = sp->rowsize;
         assert(rowsize > 0);
         assert(sp->pfunc != NULL);
         while ((long)occ0 > 0) {
             (*sp->pfunc)(tif, op0, (tsize_t) rowsize);
             occ0 -= rowsize;
             op0 += rowsize;
         }
         return 1;
     } else
         return 0;
 }
static int PredictorEncodeRow (TIFF * tif, tidata_t bp, tsize_t cc, tsample_t s) static
Definition at line 477 of file tif_predict.c.
References TIFFPredictorState::coderow, NULL, TIFFPredictorState::pfunc, and PredictorState.
Referenced by PredictorSetupEncode().
 {
     TIFFPredictorState *sp = PredictorState(tif);
     assert(sp != NULL);
     assert(sp->pfunc != NULL);
     assert(sp->coderow != NULL);
 /* XXX horizontal differencing alters user's data XXX */
     (*sp->pfunc)(tif, bp, cc);
     return (*sp->coderow)(tif, bp, cc, s);
 }
static int PredictorEncodeTile (TIFF * tif, tidata_t bp0, tsize_t cc0, tsample_t s) static
Definition at line 490 of file tif_predict.c.
References TIFFPredictorState::codetile, NULL, TIFFPredictorState::pfunc, PredictorState, and TIFFPredictorState::rowsize.
Referenced by PredictorSetupEncode().
 {
     TIFFPredictorState *sp = PredictorState(tif);
     tsize_t cc = cc0, rowsize;
     unsigned char* bp = bp0;
     assert(sp != NULL);
     assert(sp->pfunc != NULL);
     assert(sp->codetile != NULL);
     rowsize = sp->rowsize;
     assert(rowsize > 0);
     while ((long)cc > 0) {
         (*sp->pfunc)(tif, bp, (tsize_t) rowsize);
         cc -= rowsize;
         bp += rowsize;
     }
     return (*sp->codetile)(tif, bp0, cc0, s);
 }
static void PredictorPrintDir (TIFF * tif, FILE * fd, long flags) static
Definition at line 550 of file tif_predict.c.
References FIELD_PREDICTOR, TIFFPredictorState::predictor, PredictorState, TIFFPredictorState::printdir, and TIFFFieldSet.
Referenced by TIFFPredictorInit().
 {
     TIFFPredictorState* sp = PredictorState(tif);
     (void) flags;
     if (TIFFFieldSet(tif,FIELD_PREDICTOR)) {
         fprintf(fd, "  Predictor: ");
         switch (sp->predictor) {
         case 1: fprintf(fd, "none "); break;
         case 2: fprintf(fd, "horizontal differencing "); break;
         case 3: fprintf(fd, "floating point predictor "); break;
         }
         fprintf(fd, "%u (0x%x)\n", sp->predictor, sp->predictor);
     }
     if (sp->printdir)
         (*sp->printdir)(tif, fd, flags);
 }
static int PredictorSetup (TIFF * tif) static
Definition at line 50 of file tif_predict.c.
References isTiled, PLANARCONFIG_CONTIG, TIFFPredictorState::predictor, PREDICTOR_FLOATINGPOINT, PREDICTOR_HORIZONTAL, PREDICTOR_NONE, PredictorState, TIFFPredictorState::rowsize, SAMPLEFORMAT_IEEEFP, TIFFPredictorState::stride, TIFFDirectory::td_bitspersample, TIFFDirectory::td_planarconfig, TIFFDirectory::td_sampleformat, TIFFDirectory::td_samplesperpixel, tiff::tif_clientdata, tiff::tif_dir, TIFFErrorExt(), TIFFScanlineSize(), and TIFFTileRowSize().
Referenced by PredictorSetupDecode(), and PredictorSetupEncode().
 {
     static const char module[] = "PredictorSetup";
     TIFFPredictorState* sp = PredictorState(tif);
     TIFFDirectory* td = &tif->tif_dir;
     switch (sp->predictor)      /* no differencing */
     {
         case PREDICTOR_NONE:
             return 1;
         case PREDICTOR_HORIZONTAL:
             if (td->td_bitspersample != 8
                 && td->td_bitspersample != 16) {
                 TIFFErrorExt(tif->tif_clientdata, module,
     "Horizontal differencing \"Predictor\" not supported with %d-bit samples",
                       td->td_bitspersample);
                 return 0;
             }
             break;
         case PREDICTOR_FLOATINGPOINT:
             if (td->td_sampleformat != SAMPLEFORMAT_IEEEFP) {
                 TIFFErrorExt(tif->tif_clientdata, module,
     "Floating point \"Predictor\" not supported with %d data format",
                       td->td_sampleformat);
                 return 0;
             }
             break;
         default:
             TIFFErrorExt(tif->tif_clientdata, module,
                   "\"Predictor\" value %d not supported",
                   sp->predictor);
             return 0;
     }
     sp->stride = (td->td_planarconfig == PLANARCONFIG_CONTIG ?
         td->td_samplesperpixel : 1);
     /*
      * Calculate the scanline/tile-width size in bytes.
      */
     if (isTiled(tif))
         sp->rowsize = TIFFTileRowSize(tif);
     else
         sp->rowsize = TIFFScanlineSize(tif);
     return 1;
 }
static int PredictorSetupDecode (TIFF * tif) static
Definition at line 98 of file tif_predict.c.
References _TIFFNoPostDecode(), TIFFPredictorState::coderow, TIFFPredictorState::codestrip, TIFFPredictorState::codetile, fpAcc(), horAcc16(), horAcc8(), TIFFPredictorState::pfunc, TIFFPredictorState::predictor, PredictorDecodeRow(), PredictorDecodeTile(), PredictorSetup(), PredictorState, TIFFPredictorState::setupdecode, swabHorAcc16(), TIFFDirectory::td_bitspersample, tiff::tif_decoderow, tiff::tif_decodestrip, tiff::tif_decodetile, tiff::tif_dir, tiff::tif_flags, tiff::tif_postdecode, and TIFF_SWAB.
Referenced by TIFFPredictorInit().
 {
     TIFFPredictorState* sp = PredictorState(tif);
     TIFFDirectory* td = &tif->tif_dir;
     if (!(*sp->setupdecode)(tif) || !PredictorSetup(tif))
         return 0;
     if (sp->predictor == 2) {
         switch (td->td_bitspersample) {
             case 8:  sp->pfunc = horAcc8; break;
             case 16: sp->pfunc = horAcc16; break;
         }
         /*
          * Override default decoding method with one that does the
          * predictor stuff.
          */
         sp->coderow = tif->tif_decoderow;
         tif->tif_decoderow = PredictorDecodeRow;
         sp->codestrip = tif->tif_decodestrip;
         tif->tif_decodestrip = PredictorDecodeTile;
         sp->codetile = tif->tif_decodetile;
         tif->tif_decodetile = PredictorDecodeTile;
         /*
          * If the data is horizontally differenced 16-bit data that
          * requires byte-swapping, then it must be byte swapped before
          * the accumulation step.  We do this with a special-purpose
          * routine and override the normal post decoding logic that
          * the library setup when the directory was read.
          */
         if (tif->tif_flags & TIFF_SWAB) {
             if (sp->pfunc == horAcc16) {
                 sp->pfunc = swabHorAcc16;
                 tif->tif_postdecode = _TIFFNoPostDecode;
             } /* else handle 32-bit case... */
         }
     }
     else if (sp->predictor == 3) {
         sp->pfunc = fpAcc;
         /*
          * Override default decoding method with one that does the
          * predictor stuff.
          */
         sp->coderow = tif->tif_decoderow;
         tif->tif_decoderow = PredictorDecodeRow;
         sp->codestrip = tif->tif_decodestrip;
         tif->tif_decodestrip = PredictorDecodeTile;
         sp->codetile = tif->tif_decodetile;
         tif->tif_decodetile = PredictorDecodeTile;
         /*
          * The data should not be swapped outside of the floating
          * point predictor, the accumulation routine should return
          * byres in the native order.
          */
         if (tif->tif_flags & TIFF_SWAB) {
             tif->tif_postdecode = _TIFFNoPostDecode;
         }
         /*
          * Allocate buffer to keep the decoded bytes before
          * rearranging in the ight order
          */
     }
     return 1;
 }
static int PredictorSetupEncode (TIFF * tif) static
Definition at line 166 of file tif_predict.c.
References TIFFPredictorState::coderow, TIFFPredictorState::codestrip, TIFFPredictorState::codetile, fpDiff(), horDiff16(), horDiff8(), TIFFPredictorState::pfunc, TIFFPredictorState::predictor, PredictorEncodeRow(), PredictorEncodeTile(), PredictorSetup(), PredictorState, TIFFPredictorState::setupencode, TIFFDirectory::td_bitspersample, tiff::tif_dir, tiff::tif_encoderow, tiff::tif_encodestrip, and tiff::tif_encodetile.
Referenced by TIFFPredictorInit().
 {
     TIFFPredictorState* sp = PredictorState(tif);
     TIFFDirectory* td = &tif->tif_dir;
     if (!(*sp->setupencode)(tif) || !PredictorSetup(tif))
         return 0;
     if (sp->predictor == 2) {
         switch (td->td_bitspersample) {
             case 8:  sp->pfunc = horDiff8; break;
             case 16: sp->pfunc = horDiff16; break;
         }
         /*
          * Override default encoding method with one that does the
          * predictor stuff.
          */
         sp->coderow = tif->tif_encoderow;
         tif->tif_encoderow = PredictorEncodeRow;
         sp->codestrip = tif->tif_encodestrip;
         tif->tif_encodestrip = PredictorEncodeTile;
         sp->codetile = tif->tif_encodetile;
         tif->tif_encodetile = PredictorEncodeTile;
     }
     else if (sp->predictor == 3) {
         sp->pfunc = fpDiff;
         /*
          * Override default encoding method with one that does the
          * predictor stuff.
          */
         sp->coderow = tif->tif_encoderow;
         tif->tif_encoderow = PredictorEncodeRow;
         sp->codestrip = tif->tif_encodestrip;
         tif->tif_encodestrip = PredictorEncodeTile;
         sp->codetile = tif->tif_encodetile;
         tif->tif_encodetile = PredictorEncodeTile;
     }
     return 1;
 }
static int PredictorVGetField (TIFF * tif, ttag_t tag, va_list ap) static
Definition at line 535 of file tif_predict.c.
References TIFFPredictorState::predictor, PredictorState, TIFFTAG_PREDICTOR, and TIFFPredictorState::vgetparent.
Referenced by TIFFPredictorInit().
 {
     TIFFPredictorState *sp = PredictorState(tif);
     switch (tag) {
     case TIFFTAG_PREDICTOR:
         *va_arg(ap, uint16*) = sp->predictor;
         break;
     default:
         return (*sp->vgetparent)(tif, tag, ap);
     }
     return 1;
 }
static int PredictorVSetField (TIFF * tif, ttag_t tag, va_list ap) static
Definition at line 518 of file tif_predict.c.
References FIELD_PREDICTOR, TIFFPredictorState::predictor, PredictorState, tiff::tif_flags, TIFF_DIRTYDIRECT, TIFFSetFieldBit, TIFFTAG_PREDICTOR, and TIFFPredictorState::vsetparent.
Referenced by TIFFPredictorInit().
 {
     TIFFPredictorState *sp = PredictorState(tif);
     switch (tag) {
     case TIFFTAG_PREDICTOR:
         sp->predictor = (uint16) va_arg(ap, int);
         TIFFSetFieldBit(tif, FIELD_PREDICTOR);
         break;
     default:
         return (*sp->vsetparent)(tif, tag, ap);
     }
     tif->tif_flags |= TIFF_DIRTYDIRECT;
     return 1;
 }
static void swabHorAcc16 (TIFF * tif, tidata_t cp0, tsize_t cc) static
Definition at line 262 of file tif_predict.c.
References PredictorState, REPEAT4, and TIFFSwabArrayOfShort().
Referenced by PredictorSetupDecode().
 {
     tsize_t stride = PredictorState(tif)->stride;
     uint16* wp = (uint16*) cp0;
     tsize_t wc = cc / 2;
     if (wc > stride) {
         TIFFSwabArrayOfShort(wp, wc);
         wc -= stride;
         do {
             REPEAT4(stride, wp[stride] += wp[0]; wp++)
             wc -= stride;
         } while ((int32) wc > 0);
     }
 }
int TIFFPredictorInit (TIFF * tif)
Definition at line 569 of file tif_predict.c.
References _TIFFMergeFieldInfo(), N, NULL, TIFFPredictorState::pfunc, TIFFPredictorState::predictor, PredictorPrintDir(), PredictorSetupDecode(), PredictorSetupEncode(), PredictorState, PredictorVGetField(), PredictorVSetField(), TIFFPredictorState::printdir, TIFFTagMethods::printdir, TIFFPredictorState::setupdecode, TIFFPredictorState::setupencode, tiff::tif_setupdecode, tiff::tif_setupencode, tiff::tif_tagmethods, TIFFTagMethods::vgetfield, TIFFPredictorState::vgetparent, TIFFTagMethods::vsetfield, and TIFFPredictorState::vsetparent.
 {
     TIFFPredictorState* sp = PredictorState(tif);
     /*
      * Merge codec-specific tag information and
      * override parent get/set field methods.
      */
     _TIFFMergeFieldInfo(tif, predictFieldInfo, N(predictFieldInfo));
     sp->vgetparent = tif->tif_tagmethods.vgetfield;
     tif->tif_tagmethods.vgetfield =
             PredictorVGetField;/* hook for predictor tag */
     sp->vsetparent = tif->tif_tagmethods.vsetfield;
     tif->tif_tagmethods.vsetfield =
             PredictorVSetField;/* hook for predictor tag */
     sp->printdir = tif->tif_tagmethods.printdir;
     tif->tif_tagmethods.printdir =
             PredictorPrintDir;  /* hook for predictor tag */
     sp->setupdecode = tif->tif_setupdecode;
     tif->tif_setupdecode = PredictorSetupDecode;
     sp->setupencode = tif->tif_setupencode;
     tif->tif_setupencode = PredictorSetupEncode;
     sp->predictor = 1;          /* default value */
     sp->pfunc = NULL;           /* no predictor routine */
     return 1;
 }
Variable Documentation
const TIFFFieldInfo predictFieldInfo[] static
Initial value:
= {
    { TIFFTAG_PREDICTOR,     1, 1, TIFF_SHORT,   (FIELD_CODEC+0)  ,
      FALSE,    FALSE,  "Predictor" },
}
Definition at line 511 of file tif_predict.c.