Visible: src/util/code/tif_dirinfo.c File Reference
tif_dirinfo.c File Reference
#include "tiffiop.h"
#include <stdlib.h>
Functions
const TIFFFieldInfo * _TIFFGetFieldInfo (size_t *size)
const TIFFFieldInfo * _TIFFGetExifFieldInfo (size_t *size)
void _TIFFSetupFieldInfo (TIFF *tif, const TIFFFieldInfo info[], size_t n)
static int tagCompare (const void *a, const void *b)
static int tagNameCompare (const void *a, const void *b)
void _TIFFMergeFieldInfo (TIFF *tif, const TIFFFieldInfo info[], int n)
void _TIFFPrintFieldInfo (TIFF *tif, FILE *fd)
int TIFFDataWidth (TIFFDataType type)
int _TIFFDataSize (TIFFDataType type)
TIFFDataType _TIFFSampleToTagType (TIFF *tif)
const TIFFFieldInfo * _TIFFFindFieldInfo (TIFF *tif, ttag_t tag, TIFFDataType dt)
const TIFFFieldInfo * _TIFFFindFieldInfoByName (TIFF *tif, const char *field_name, TIFFDataType dt)
const TIFFFieldInfo * _TIFFFieldWithTag (TIFF *tif, ttag_t tag)
const TIFFFieldInfo * _TIFFFieldWithName (TIFF *tif, const char *field_name)
const TIFFFieldInfo * _TIFFFindOrRegisterFieldInfo (TIFF *tif, ttag_t tag, TIFFDataType dt)
TIFFFieldInfo * _TIFFCreateAnonFieldInfo (TIFF *tif, ttag_t tag, TIFFDataType field_type)
Variables
static const TIFFFieldInfo tiffFieldInfo []
static const TIFFFieldInfo exifFieldInfo []
Function Documentation
TIFFFieldInfo* _TIFFCreateAnonFieldInfo (TIFF * tif, ttag_t tag, TIFFDataType field_type)
Definition at line 815 of file tif_dirinfo.c.
References _TIFFfree(), _TIFFmalloc(), _TIFFmemset(), TIFFFieldInfo::field_bit, FIELD_CUSTOM, TIFFFieldInfo::field_name, TIFFFieldInfo::field_oktochange, TIFFFieldInfo::field_passcount, TIFFFieldInfo::field_readcount, TIFFFieldInfo::field_tag, TIFFFieldInfo::field_type, TIFFFieldInfo::field_writecount, NULL, TIFF_VARIABLE, and TRUE.
Referenced by _TIFFFindOrRegisterFieldInfo(), TIFFReadCustomDirectory(), and TIFFReadDirectory().
 {
     TIFFFieldInfo *fld;
     (void) tif;
     fld = (TIFFFieldInfo *) _TIFFmalloc(sizeof (TIFFFieldInfo));
     if (fld == NULL)
         return NULL;
     _TIFFmemset( fld, 0, sizeof(TIFFFieldInfo) );
     fld->field_tag = tag;
     fld->field_readcount = TIFF_VARIABLE;
     fld->field_writecount = TIFF_VARIABLE;
     fld->field_type = field_type;
     fld->field_bit = FIELD_CUSTOM;
     fld->field_oktochange = TRUE;
     fld->field_passcount = TRUE;
     fld->field_name = (char *) _TIFFmalloc(32);
     if (fld->field_name == NULL) {
         _TIFFfree(fld);
         return NULL;
     }
     /* note that this name is a special sign to TIFFClose() and
      * _TIFFSetupFieldInfo() to free the field
      */
     sprintf(fld->field_name, "Tag %d", (int) tag);
     return fld;
 }
int _TIFFDataSize (TIFFDataType type)
Definition at line 655 of file tif_dirinfo.c.
References TIFF_ASCII, TIFF_BYTE, TIFF_DOUBLE, TIFF_FLOAT, TIFF_IFD, TIFF_LONG, TIFF_RATIONAL, TIFF_SBYTE, TIFF_SHORT, TIFF_SLONG, TIFF_SRATIONAL, TIFF_SSHORT, and TIFF_UNDEFINED.
Referenced by _TIFFVGetField(), _TIFFVSetField(), TIFFReaderInternal::Open(), and TIFFPrintDirectory().
 {
     switch (type) {
         case TIFF_BYTE:
         case TIFF_SBYTE:
         case TIFF_ASCII:
         case TIFF_UNDEFINED:
             return 1;
         case TIFF_SHORT:
         case TIFF_SSHORT:
             return 2;
         case TIFF_LONG:
         case TIFF_SLONG:
         case TIFF_FLOAT:
         case TIFF_IFD:
         case TIFF_RATIONAL:
         case TIFF_SRATIONAL:
             return 4;
         case TIFF_DOUBLE:
             return 8;
         default:
             return 0;
     }
 }
const TIFFFieldInfo* _TIFFFieldWithName (TIFF * tif, const char * field_name)
Definition at line 785 of file tif_dirinfo.c.
References _TIFFFindFieldInfoByName(), NULL, tiff::tif_clientdata, TIFF_ANY, and TIFFErrorExt().
 {
     const TIFFFieldInfo* fip =
         _TIFFFindFieldInfoByName(tif, field_name, TIFF_ANY);
     if (!fip) {
         TIFFErrorExt(tif->tif_clientdata, "TIFFFieldWithName",
               "Internal error, unknown tag %s", field_name);
         assert(fip != NULL);
         /*NOTREACHED*/
     }
     return (fip);
 }
const TIFFFieldInfo* _TIFFFieldWithTag (TIFF * tif, ttag_t tag)
Definition at line 771 of file tif_dirinfo.c.
References _TIFFFindFieldInfo(), NULL, tiff::tif_clientdata, TIFF_ANY, and TIFFErrorExt().
Referenced by _TIFFVGetField(), _TIFFVSetField(), CheckDirCount(), cvtRational(), TIFFFetchAnyArray(), TIFFFetchData(), TIFFFetchNormalTag(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFReadDirectory(), TIFFWriteData(), and TIFFWriteRationalArray().
 {
     const TIFFFieldInfo* fip = _TIFFFindFieldInfo(tif, tag, TIFF_ANY);
     if (!fip) {
         TIFFErrorExt(tif->tif_clientdata, "TIFFFieldWithTag",
               "Internal error, unknown tag 0x%x",
                           (unsigned int) tag);
         assert(fip != NULL);
         /*NOTREACHED*/
     }
     return (fip);
 }
const TIFFFieldInfo* _TIFFFindFieldInfo (TIFF * tif, ttag_t tag, TIFFDataType dt)
Definition at line 705 of file tif_dirinfo.c.
References TIFFFieldInfo::field_tag, TIFFFieldInfo::field_type, NULL, tagCompare(), tiff::tif_fieldinfo, tiff::tif_foundfield, tiff::tif_nfields, TIFF_ANY, and TIFF_NOTYPE.
Referenced by _TIFFFieldWithTag(), _TIFFFindOrRegisterFieldInfo(), _TIFFVGetField(), _TIFFVSetField(), OkToChangeTag(), and TIFFVGetField().
 {
     int i, n;
     if (tif->tif_foundfield && tif->tif_foundfield->field_tag == tag &&
         (dt == TIFF_ANY || dt == tif->tif_foundfield->field_type))
         return (tif->tif_foundfield);
     /* NB: use sorted search (e.g. binary search) */
     if(dt != TIFF_ANY) {
         TIFFFieldInfo key = {0, 0, 0, TIFF_NOTYPE, 0, 0, 0, 0};
         TIFFFieldInfo* pkey = &key;
         const TIFFFieldInfo **ret;
         key.field_tag = tag;
             key.field_type = dt;
         ret = (const TIFFFieldInfo **) bsearch(&pkey,
                            tif->tif_fieldinfo,
                            tif->tif_nfields,
                            sizeof(TIFFFieldInfo *),
                            tagCompare);
         return (ret) ? (*ret) : NULL;
         } else for (i = 0, n = tif->tif_nfields; i < n; i++) {
         const TIFFFieldInfo* fip = tif->tif_fieldinfo[i];
         if (fip->field_tag == tag &&
             (dt == TIFF_ANY || fip->field_type == dt))
             return (tif->tif_foundfield = fip);
     }
     return ((const TIFFFieldInfo *)0);
 }
const TIFFFieldInfo* _TIFFFindFieldInfoByName (TIFF * tif, const char * field_name, TIFFDataType dt)
Definition at line 737 of file tif_dirinfo.c.
References TIFFFieldInfo::field_name, TIFFFieldInfo::field_type, NULL, streq, tagNameCompare(), tiff::tif_fieldinfo, tiff::tif_foundfield, tiff::tif_nfields, TIFF_ANY, and TIFF_NOTYPE.
Referenced by _TIFFFieldWithName().
 {
     int i, n;
     if (tif->tif_foundfield
         && streq(tif->tif_foundfield->field_name, field_name)
         && (dt == TIFF_ANY || dt == tif->tif_foundfield->field_type))
         return (tif->tif_foundfield);
     /* NB: use sorted search (e.g. binary search) */
     if(dt != TIFF_ANY) {
         TIFFFieldInfo key = {0, 0, 0, TIFF_NOTYPE, 0, 0, 0, 0};
         TIFFFieldInfo* pkey = &key;
         const TIFFFieldInfo **ret;
             key.field_name = (char *)field_name;
             key.field_type = dt;
             ret = (const TIFFFieldInfo **) lfind(&pkey,
                          tif->tif_fieldinfo,
                          &tif->tif_nfields,
                          sizeof(TIFFFieldInfo *),
                          tagNameCompare);
         return (ret) ? (*ret) : NULL;
         } else
         for (i = 0, n = tif->tif_nfields; i < n; i++) {
             const TIFFFieldInfo* fip = tif->tif_fieldinfo[i];
             if (streq(fip->field_name, field_name) &&
                 (dt == TIFF_ANY || fip->field_type == dt))
                 return (tif->tif_foundfield = fip);
         }
     return ((const TIFFFieldInfo *)0);
 }
const TIFFFieldInfo* _TIFFFindOrRegisterFieldInfo (TIFF * tif, ttag_t tag, TIFFDataType dt)
Definition at line 799 of file tif_dirinfo.c.
References _TIFFCreateAnonFieldInfo(), _TIFFFindFieldInfo(), _TIFFMergeFieldInfo(), and NULL.
 {
     const TIFFFieldInfo *fld;
     fld = _TIFFFindFieldInfo( tif, tag, dt );
     if( fld == NULL )
     {
         fld = _TIFFCreateAnonFieldInfo( tif, tag, dt );
         _TIFFMergeFieldInfo( tif, fld, 1 );
     }
     return fld;
 }
const TIFFFieldInfo* _TIFFGetExifFieldInfo (size_t * size)
Definition at line 520 of file tif_dirinfo.c.
References exifFieldInfo, and TIFFArrayCount.
Referenced by TIFFReadEXIFDirectory().
 {
     *size = TIFFArrayCount(exifFieldInfo);
     return exifFieldInfo;
 }
const TIFFFieldInfo* _TIFFGetFieldInfo (size_t * size)
Definition at line 513 of file tif_dirinfo.c.
References TIFFArrayCount, and tiffFieldInfo.
Referenced by TIFFDefaultDirectory().
 {
     *size = TIFFArrayCount(tiffFieldInfo);
     return tiffFieldInfo;
 }
void _TIFFMergeFieldInfo (TIFF * tif, const TIFFFieldInfo info[], int n)
Definition at line 570 of file tif_dirinfo.c.
References _TIFFmalloc(), _TIFFrealloc(), NULL, tagCompare(), tiff::tif_fieldinfo, tiff::tif_foundfield, and tiff::tif_nfields.
Referenced by _TIFFFindOrRegisterFieldInfo(), _TIFFSetupFieldInfo(), and TIFFPredictorInit().
 {
     TIFFFieldInfo** tp;
     int i;
         tif->tif_foundfield = NULL;
     if (tif->tif_nfields > 0) {
         tif->tif_fieldinfo = (TIFFFieldInfo**)
             _TIFFrealloc(tif->tif_fieldinfo,
             (tif->tif_nfields+n) * sizeof (TIFFFieldInfo*));
     } else {
         tif->tif_fieldinfo = (TIFFFieldInfo**)
             _TIFFmalloc(n * sizeof (TIFFFieldInfo*));
     }
     assert(tif->tif_fieldinfo != NULL);
     tp = tif->tif_fieldinfo + tif->tif_nfields;
     for (i = 0; i < n; i++)
         *tp++ = (TIFFFieldInfo*) (info + i);    /* XXX */
         /* Sort the field info by tag number */
         qsort(tif->tif_fieldinfo, tif->tif_nfields += n,
           sizeof (TIFFFieldInfo*), tagCompare);
 }
void _TIFFPrintFieldInfo (TIFF * tif, FILE * fd)
Definition at line 596 of file tif_dirinfo.c.
References TIFFFieldInfo::field_bit, TIFFFieldInfo::field_name, TIFFFieldInfo::field_oktochange, TIFFFieldInfo::field_passcount, TIFFFieldInfo::field_readcount, TIFFFieldInfo::field_tag, TIFFFieldInfo::field_type, TIFFFieldInfo::field_writecount, tiff::tif_fieldinfo, tiff::tif_name, and tiff::tif_nfields.
 {
     size_t i;
     fprintf(fd, "%s: \n", tif->tif_name);
     for (i = 0; i < tif->tif_nfields; i++) {
         const TIFFFieldInfo* fip = tif->tif_fieldinfo[i];
         fprintf(fd, "field[%2d] %5lu, %2d, %2d, %d, %2d, %5s, %5s, %s\n"
             , (int)i
             , (unsigned long) fip->field_tag
             , fip->field_readcount, fip->field_writecount
             , fip->field_type
             , fip->field_bit
             , fip->field_oktochange ? "TRUE" : "FALSE"
             , fip->field_passcount ? "TRUE" : "FALSE"
             , fip->field_name
         );
     }
 }
TIFFDataType _TIFFSampleToTagType (TIFF * tif)
Definition at line 684 of file tif_dirinfo.c.
References SAMPLEFORMAT_IEEEFP, SAMPLEFORMAT_INT, SAMPLEFORMAT_UINT, SAMPLEFORMAT_VOID, TIFFDirectory::td_bitspersample, TIFFDirectory::td_sampleformat, tiff::tif_dir, TIFF_BYTE, TIFF_DOUBLE, TIFF_FLOAT, TIFF_LONG, TIFF_SBYTE, TIFF_SHORT, TIFF_SLONG, TIFF_SSHORT, TIFF_UNDEFINED, and TIFFhowmany8.
Referenced by _TIFFWriteDirectory().
 {
     uint32 bps = TIFFhowmany8(tif->tif_dir.td_bitspersample);
     switch (tif->tif_dir.td_sampleformat) {
     case SAMPLEFORMAT_IEEEFP:
         return (bps == 4 ? TIFF_FLOAT : TIFF_DOUBLE);
     case SAMPLEFORMAT_INT:
         return (bps <= 1 ? TIFF_SBYTE :
             bps <= 2 ? TIFF_SSHORT : TIFF_SLONG);
     case SAMPLEFORMAT_UINT:
         return (bps <= 1 ? TIFF_BYTE :
             bps <= 2 ? TIFF_SHORT : TIFF_LONG);
     case SAMPLEFORMAT_VOID:
         return (TIFF_UNDEFINED);
     }
     /*NOTREACHED*/
     return (TIFF_UNDEFINED);
 }
void _TIFFSetupFieldInfo (TIFF * tif, const TIFFFieldInfo info[], size_t n)
Definition at line 527 of file tif_dirinfo.c.
References _TIFFfree(), _TIFFMergeFieldInfo(), TIFFFieldInfo::field_bit, FIELD_CUSTOM, TIFFFieldInfo::field_name, tiff::tif_fieldinfo, and tiff::tif_nfields.
Referenced by TIFFDefaultDirectory(), and TIFFReadCustomDirectory().
 {
     if (tif->tif_fieldinfo) {
         size_t  i;
         for (i = 0; i < tif->tif_nfields; i++)
         {
             TIFFFieldInfo *fld = tif->tif_fieldinfo[i];
             if (fld->field_bit == FIELD_CUSTOM &&
                 strncmp("Tag ", fld->field_name, 4) == 0) {
                     _TIFFfree(fld->field_name);
                     _TIFFfree(fld);
                 }
         }
         _TIFFfree(tif->tif_fieldinfo);
         tif->tif_nfields = 0;
     }
     _TIFFMergeFieldInfo(tif, info, n);
 }
static int tagCompare (const void * a, const void * b) static
Definition at line 549 of file tif_dirinfo.c.
References TIFFFieldInfo::field_tag, and TIFFFieldInfo::field_type.
Referenced by _TIFFFindFieldInfo(), and _TIFFMergeFieldInfo().
 {
     const TIFFFieldInfo* ta = *(const TIFFFieldInfo**) a;
     const TIFFFieldInfo* tb = *(const TIFFFieldInfo**) b;
     /* NB: be careful of return values for 16-bit platforms */
     if (ta->field_tag != tb->field_tag)
         return (ta->field_tag < tb->field_tag ? -1 : 1);
     else
         return ((int)tb->field_type - (int)ta->field_type);
 }
static int tagNameCompare (const void * a, const void * b) static
Definition at line 561 of file tif_dirinfo.c.
References TIFFFieldInfo::field_name.
Referenced by _TIFFFindFieldInfoByName().
 {
     const TIFFFieldInfo* ta = *(const TIFFFieldInfo**) a;
     const TIFFFieldInfo* tb = *(const TIFFFieldInfo**) b;
         return strcmp(ta->field_name, tb->field_name);
 }
int TIFFDataWidth (TIFFDataType type)
Definition at line 620 of file tif_dirinfo.c.
Referenced by EstimateStripByteCounts(), TIFFFetchData(), TIFFFetchRationalArray(), TIFFWriteAnyArray(), and TIFFWriteData().
 {
     switch(type)
     {
     case 0:  /* nothing */
     case 1:  /* TIFF_BYTE */
     case 2:  /* TIFF_ASCII */
     case 6:  /* TIFF_SBYTE */
     case 7:  /* TIFF_UNDEFINED */
         return 1;
     case 3:  /* TIFF_SHORT */
     case 8:  /* TIFF_SSHORT */
         return 2;
     case 4:  /* TIFF_LONG */
     case 9:  /* TIFF_SLONG */
     case 11: /* TIFF_FLOAT */
         case 13: /* TIFF_IFD */
         return 4;
     case 5:  /* TIFF_RATIONAL */
     case 10: /* TIFF_SRATIONAL */
     case 12: /* TIFF_DOUBLE */
         return 8;
     default:
         return 0; /* will return 0 for unknown types */
     }
 }
Variable Documentation
const TIFFFieldInfo exifFieldInfo[] static
Definition at line 395 of file tif_dirinfo.c.
Referenced by _TIFFGetExifFieldInfo(), and TIFFReadEXIFDirectory().
const TIFFFieldInfo tiffFieldInfo[] static
Definition at line 47 of file tif_dirinfo.c.
Referenced by _TIFFGetFieldInfo(), and TIFFDefaultDirectory().