Visible: src/util/code/tif_flush.c File Reference
tif_flush.c File Reference
#include "tiffiop.h"
Functions
int TIFFFlush (TIFF *tif)
int TIFFFlushData (TIFF *tif)
Function Documentation
int TIFFFlush (TIFF * tif)
Definition at line 33 of file tif_flush.c.
References tiff::tif_flags, tiff::tif_mode, TIFF_DIRTYDIRECT, TIFFFlushData(), and TIFFWriteDirectory().
Referenced by TIFFCleanup().
 {
     if (tif->tif_mode != O_RDONLY) {
         if (!TIFFFlushData(tif))
             return (0);
         if ((tif->tif_flags & TIFF_DIRTYDIRECT) &&
             !TIFFWriteDirectory(tif))
             return (0);
     }
     return (1);
 }
int TIFFFlushData (TIFF * tif)
Definition at line 56 of file tif_flush.c.
References tiff::tif_flags, tiff::tif_postencode, TIFF_BEENWRITING, TIFF_POSTENCODE, and TIFFFlushData1().
Referenced by TIFFFlush(), and TIFFWriteScanline().
 {
     if ((tif->tif_flags & TIFF_BEENWRITING) == 0)
         return (0);
     if (tif->tif_flags & TIFF_POSTENCODE) {
         tif->tif_flags &= ~TIFF_POSTENCODE;
         if (!(*tif->tif_postencode)(tif))
             return (0);
     }
     return (TIFFFlushData1(tif));
 }