Visible: src/util/code/tif_open.c File Reference
tif_open.c File Reference
#include "tiffiop.h"
Functions
void _TIFFSetDefaultCompressionState (TIFF *tif)
static int _tiffDummyMapProc (thandle_t fd, tdata_t *pbase, toff_t *psize)
static void _tiffDummyUnmapProc (thandle_t fd, tdata_t base, toff_t size)
static void TIFFInitOrder (TIFF *tif, int magic)
int _TIFFgetMode (const char *mode, const char *module)
TIFF * TIFFClientOpen (const char *name, const char *mode, thandle_t clientdata, TIFFReadWriteProc readproc, TIFFReadWriteProc writeproc, TIFFSeekProc seekproc, TIFFCloseProc closeproc, TIFFSizeProc sizeproc, TIFFMapFileProc mapproc, TIFFUnmapFileProc unmapproc)
const char * TIFFFileName (TIFF *tif)
const char * TIFFSetFileName (TIFF *tif, const char *name)
int TIFFFileno (TIFF *tif)
int TIFFSetFileno (TIFF *tif, int fd)
thandle_t TIFFClientdata (TIFF *tif)
thandle_t TIFFSetClientdata (TIFF *tif, thandle_t newvalue)
int TIFFGetMode (TIFF *tif)
int TIFFSetMode (TIFF *tif, int mode)
int TIFFIsTiled (TIFF *tif)
uint32 TIFFCurrentRow (TIFF *tif)
tdir_t TIFFCurrentDirectory (TIFF *tif)
tstrip_t TIFFCurrentStrip (TIFF *tif)
ttile_t TIFFCurrentTile (TIFF *tif)
int TIFFIsByteSwapped (TIFF *tif)
int TIFFIsUpSampled (TIFF *tif)
int TIFFIsMSB2LSB (TIFF *tif)
int TIFFIsBigEndian (TIFF *tif)
TIFFReadWriteProc TIFFGetReadProc (TIFF *tif)
TIFFReadWriteProc TIFFGetWriteProc (TIFF *tif)
TIFFSeekProc TIFFGetSeekProc (TIFF *tif)
TIFFCloseProc TIFFGetCloseProc (TIFF *tif)
TIFFSizeProc TIFFGetSizeProc (TIFF *tif)
TIFFMapFileProc TIFFGetMapFileProc (TIFF *tif)
TIFFUnmapFileProc TIFFGetUnmapFileProc (TIFF *tif)
Variables
static const long typemask [13]
static const int bigTypeshift [13]
static const int litTypeshift [13]
Function Documentation
static int _tiffDummyMapProc (thandle_t fd, tdata_t * pbase, toff_t * psize) static
Definition at line 84 of file tif_open.c.
Referenced by TIFFClientOpen().
 {
     (void) fd; (void) pbase; (void) psize;
     return (0);
 }
static void _tiffDummyUnmapProc (thandle_t fd, tdata_t base, toff_t size) static
Definition at line 91 of file tif_open.c.
Referenced by TIFFClientOpen().
 {
     (void) fd; (void) base; (void) size;
 }
int _TIFFgetMode (const char * mode, const char * module)
Definition at line 119 of file tif_open.c.
References TIFFErrorExt().
Referenced by TIFFClientOpen(), and TIFFOpen().
 {
     int m = -1;
     switch (mode[0]) {
     case 'r':
         m = O_RDONLY;
         if (mode[1] == '+')
             m = O_RDWR;
         break;
     case 'w':
     case 'a':
         m = O_RDWR|O_CREAT;
         if (mode[0] == 'w')
             m |= O_TRUNC;
         break;
     default:
         TIFFErrorExt(0, module, "\"%s\": Bad mode", mode);
         break;
     }
     return (m);
 }
void _TIFFSetDefaultCompressionState (TIFF * tif)
Definition at line 127 of file tif_compress.c.
References _TIFFDefaultStripSize(), _TIFFDefaultTileSize(), _TIFFNoPreCode(), _TIFFNoRowDecode(), _TIFFNoRowEncode(), _TIFFNoSeek(), _TIFFNoStripDecode(), _TIFFNoStripEncode(), _TIFFNoTileDecode(), _TIFFNoTileEncode(), _TIFFtrue(), _TIFFvoid(), tiff::tif_cleanup, tiff::tif_close, tiff::tif_decoderow, tiff::tif_decodestatus, tiff::tif_decodestrip, tiff::tif_decodetile, tiff::tif_defstripsize, tiff::tif_deftilesize, tiff::tif_encoderow, tiff::tif_encodestatus, tiff::tif_encodestrip, tiff::tif_encodetile, tiff::tif_flags, tiff::tif_postencode, tiff::tif_predecode, tiff::tif_preencode, tiff::tif_seek, tiff::tif_setupdecode, tiff::tif_setupencode, TIFF_NOBITREV, and TRUE.
Referenced by TIFFClientOpen(), and TIFFSetCompressionScheme().
 {
     tif->tif_decodestatus = TRUE;
     tif->tif_setupdecode = _TIFFtrue;
     tif->tif_predecode = _TIFFNoPreCode;
     tif->tif_decoderow = _TIFFNoRowDecode;
     tif->tif_decodestrip = _TIFFNoStripDecode;
     tif->tif_decodetile = _TIFFNoTileDecode;
     tif->tif_encodestatus = TRUE;
     tif->tif_setupencode = _TIFFtrue;
     tif->tif_preencode = _TIFFNoPreCode;
     tif->tif_postencode = _TIFFtrue;
     tif->tif_encoderow = _TIFFNoRowEncode;
     tif->tif_encodestrip = _TIFFNoStripEncode;
     tif->tif_encodetile = _TIFFNoTileEncode;
     tif->tif_close = _TIFFvoid;
     tif->tif_seek = _TIFFNoSeek;
     tif->tif_cleanup = _TIFFvoid;
     tif->tif_defstripsize = _TIFFDefaultStripSize;
     tif->tif_deftilesize = _TIFFDefaultTileSize;
     tif->tif_flags &= ~TIFF_NOBITREV;
 }
thandle_t TIFFClientdata (TIFF * tif)
Definition at line 504 of file tif_open.c.
References tiff::tif_clientdata.
 {
     return (tif->tif_clientdata);
 }
TIFF* TIFFClientOpen (const char * name, const char * mode, thandle_t clientdata, TIFFReadWriteProc readproc, TIFFReadWriteProc writeproc, TIFFSeekProc seekproc, TIFFCloseProc closeproc, TIFFSizeProc sizeproc, TIFFMapFileProc mapproc, TIFFUnmapFileProc unmapproc)
Definition at line 143 of file tif_open.c.
References _tiffDummyMapProc(), _tiffDummyUnmapProc(), _TIFFgetMode(), _TIFFmalloc(), _TIFFmemset(), _TIFFSetDefaultCompressionState(), FILLORDER_LSB2MSB, FILLORDER_MSB2LSB, HOST_BIGENDIAN, HOST_FILLORDER, MDI_BIGENDIAN, MDI_LITTLEENDIAN, NULL, ReadOK, STRIPCHOP_DEFAULT, tiff::tif_base, tiff::tif_clientdata, tiff::tif_closeproc, tiff::tif_curdir, tiff::tif_curoff, tiff::tif_curstrip, tiff::tif_dirlist, tiff::tif_dirnumber, tiff::tif_diroff, tiff::tif_flags, tiff::tif_header, tiff::tif_mapproc, tiff::tif_mode, tiff::tif_name, tiff::tif_nextdiroff, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_readproc, tiff::tif_row, tiff::tif_seekproc, tiff::tif_size, tiff::tif_sizeproc, tiff::tif_unmapproc, tiff::tif_writeproc, TIFF_BIGENDIAN, TIFF_BIGTIFF_VERSION, TIFF_BUFFERSETUP, TIFFHeader::tiff_diroff, TIFF_FILLORDER, TIFF_HEADERONLY, TIFF_LITTLEENDIAN, TIFFHeader::tiff_magic, TIFF_MAPPED, TIFF_MYBUFFER, TIFF_STRIPCHOP, TIFF_SWAB, TIFF_VERSION, TIFFHeader::tiff_version, TIFFCleanup(), TIFFDefaultDirectory(), TIFFErrorExt(), TIFFInitOrder(), TIFFMapFileContents, TIFFReadDirectory(), TIFFSeekFile, TIFFSwabLong(), TIFFSwabShort(), and WriteOK.
Referenced by TIFFFdOpen().
 {
     static const char module[] = "TIFFClientOpen";
     TIFF *tif;
     int m;
     const char* cp;
     m = _TIFFgetMode(mode, module);
     if (m == -1)
         goto bad2;
     tif = (TIFF *)_TIFFmalloc(sizeof (TIFF) + strlen(name) + 1);
     if (tif == NULL) {
         TIFFErrorExt(clientdata, module, "%s: Out of memory (TIFF structure)", name);
         goto bad2;
     }
     _TIFFmemset(tif, 0, sizeof (*tif));
     tif->tif_name = (char *)tif + sizeof (TIFF);
     strcpy(tif->tif_name, name);
     tif->tif_mode = m &~ (O_CREAT|O_TRUNC);
     tif->tif_curdir = (tdir_t) -1;      /* non-existent directory */
     tif->tif_curoff = 0;
     tif->tif_curstrip = (tstrip_t) -1;  /* invalid strip */
     tif->tif_row = (uint32) -1;     /* read/write pre-increment */
     tif->tif_clientdata = clientdata;
     if (!readproc || !writeproc || !seekproc || !closeproc || !sizeproc) {
         TIFFErrorExt(clientdata, module,
               "One of the client procedures is NULL pointer.");
         goto bad2;
     }
     tif->tif_readproc = readproc;
     tif->tif_writeproc = writeproc;
     tif->tif_seekproc = seekproc;
     tif->tif_closeproc = closeproc;
     tif->tif_sizeproc = sizeproc;
         if (mapproc)
         tif->tif_mapproc = mapproc;
     else
         tif->tif_mapproc = _tiffDummyMapProc;
     if (unmapproc)
         tif->tif_unmapproc = unmapproc;
     else
         tif->tif_unmapproc = _tiffDummyUnmapProc;
     _TIFFSetDefaultCompressionState(tif);   /* setup default state */
     /*
      * Default is to return data MSB2LSB and enable the
      * use of memory-mapped files and strip chopping when
      * a file is opened read-only.
      */
     tif->tif_flags = FILLORDER_MSB2LSB;
     if (m == O_RDONLY )
             tif->tif_flags |= TIFF_MAPPED;
 #ifdef STRIPCHOP_DEFAULT
     if (m == O_RDONLY || m == O_RDWR)
         tif->tif_flags |= STRIPCHOP_DEFAULT;
 #endif
     /*
      * Process library-specific flags in the open mode string.
      * The following flags may be used to control intrinsic library
      * behaviour that may or may not be desirable (usually for
      * compatibility with some application that claims to support
      * TIFF but only supports some braindead idea of what the
      * vendor thinks TIFF is):
      *
      * 'l'      use little-endian byte order for creating a file
      * 'b'      use big-endian byte order for creating a file
      * 'L'      read/write information using LSB2MSB bit order
      * 'B'      read/write information using MSB2LSB bit order
      * 'H'      read/write information using host bit order
      * 'M'      enable use of memory-mapped files when supported
      * 'm'      disable use of memory-mapped files
      * 'C'      enable strip chopping support when reading
      * 'c'      disable strip chopping support
      * 'h'      read TIFF header only, do not load the first IFD
      *
      * The use of the 'l' and 'b' flags is strongly discouraged.
      * These flags are provided solely because numerous vendors,
      * typically on the PC, do not correctly support TIFF; they
      * only support the Intel little-endian byte order.  This
      * support is not configured by default because it supports
      * the violation of the TIFF spec that says that readers *MUST*
      * support both byte orders.  It is strongly recommended that
      * you not use this feature except to deal with busted apps
      * that write invalid TIFF.  And even in those cases you should
      * bang on the vendors to fix their software.
      *
      * The 'L', 'B', and 'H' flags are intended for applications
      * that can optimize operations on data by using a particular
      * bit order.  By default the library returns data in MSB2LSB
      * bit order for compatibiltiy with older versions of this
      * library.  Returning data in the bit order of the native cpu
      * makes the most sense but also requires applications to check
      * the value of the FillOrder tag; something they probably do
      * not do right now.
      *
      * The 'M' and 'm' flags are provided because some virtual memory
      * systems exhibit poor behaviour when large images are mapped.
      * These options permit clients to control the use of memory-mapped
      * files on a per-file basis.
      *
      * The 'C' and 'c' flags are provided because the library support
      * for chopping up large strips into multiple smaller strips is not
      * application-transparent and as such can cause problems.  The 'c'
      * option permits applications that only want to look at the tags,
      * for example, to get the unadulterated TIFF tag information.
      */
     for (cp = mode; *cp; cp++)
         switch (*cp) {
         case 'b':
 #ifndef WORDS_BIGENDIAN
             if (m&O_CREAT)
                 tif->tif_flags |= TIFF_SWAB;
 #endif
             break;
         case 'l':
 #ifdef WORDS_BIGENDIAN
             if ((m&O_CREAT))
                 tif->tif_flags |= TIFF_SWAB;
 #endif
             break;
         case 'B':
             tif->tif_flags = (tif->tif_flags &~ TIFF_FILLORDER) |
                 FILLORDER_MSB2LSB;
             break;
         case 'L':
             tif->tif_flags = (tif->tif_flags &~ TIFF_FILLORDER) |
                 FILLORDER_LSB2MSB;
             break;
         case 'H':
             tif->tif_flags = (tif->tif_flags &~ TIFF_FILLORDER) |
                 HOST_FILLORDER;
             break;
         case 'M':
             if (m == O_RDONLY)
                 tif->tif_flags |= TIFF_MAPPED;
             break;
         case 'm':
             if (m == O_RDONLY)
                 tif->tif_flags &= ~TIFF_MAPPED;
             break;
         case 'C':
             if (m == O_RDONLY)
                 tif->tif_flags |= TIFF_STRIPCHOP;
             break;
         case 'c':
             if (m == O_RDONLY)
                 tif->tif_flags &= ~TIFF_STRIPCHOP;
             break;
         case 'h':
             tif->tif_flags |= TIFF_HEADERONLY;
             break;
         }
     /*
      * Read in TIFF header.
      */
     if (tif->tif_mode & O_TRUNC ||
         !ReadOK(tif, &tif->tif_header, sizeof (TIFFHeader))) {
         if (tif->tif_mode == O_RDONLY) {
             TIFFErrorExt(tif->tif_clientdata, name, "Cannot read TIFF header");
             goto bad;
         }
         /*
          * Setup header and write.
          */
 #ifdef WORDS_BIGENDIAN
         tif->tif_header.tiff_magic = tif->tif_flags & TIFF_SWAB
             ? TIFF_LITTLEENDIAN : TIFF_BIGENDIAN;
 #else
         tif->tif_header.tiff_magic = tif->tif_flags & TIFF_SWAB
             ? TIFF_BIGENDIAN : TIFF_LITTLEENDIAN;
 #endif
         tif->tif_header.tiff_version = TIFF_VERSION;
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&tif->tif_header.tiff_version);
         tif->tif_header.tiff_diroff = 0;    /* filled in later */
                 /*
                  * The doc for "fopen" for some STD_C_LIBs says that if you
                  * open a file for modify ("+"), then you must fseek (or
                  * fflush?) between any freads and fwrites.  This is not
                  * necessary on most systems, but has been shown to be needed
                  * on Solaris.
                  */
                 TIFFSeekFile( tif, 0, SEEK_SET );
         if (!WriteOK(tif, &tif->tif_header, sizeof (TIFFHeader))) {
             TIFFErrorExt(tif->tif_clientdata, name, "Error writing TIFF header");
             goto bad;
         }
         /*
          * Setup the byte order handling.
          */
         TIFFInitOrder(tif, tif->tif_header.tiff_magic);
         /*
          * Setup default directory.
          */
         if (!TIFFDefaultDirectory(tif))
             goto bad;
         tif->tif_diroff = 0;
         tif->tif_dirlist = NULL;
         tif->tif_dirnumber = 0;
         return (tif);
     }
     /*
      * Setup the byte order handling.
      */
     if (tif->tif_header.tiff_magic != TIFF_BIGENDIAN &&
         tif->tif_header.tiff_magic != TIFF_LITTLEENDIAN
 #if MDI_SUPPORT
         &&
 #if HOST_BIGENDIAN
         tif->tif_header.tiff_magic != MDI_BIGENDIAN
 #else
         tif->tif_header.tiff_magic != MDI_LITTLEENDIAN
 #endif
         ) {
         TIFFErrorExt(tif->tif_clientdata, name,  "Not a TIFF or MDI file, bad magic number %d (0x%x)",
 #else
         ) {
         TIFFErrorExt(tif->tif_clientdata, name,  "Not a TIFF file, bad magic number %d (0x%x)",
 #endif
             tif->tif_header.tiff_magic,
             tif->tif_header.tiff_magic);
         goto bad;
     }
     TIFFInitOrder(tif, tif->tif_header.tiff_magic);
     /*
      * Swap header if required.
      */
     if (tif->tif_flags & TIFF_SWAB) {
         TIFFSwabShort(&tif->tif_header.tiff_version);
         TIFFSwabLong(&tif->tif_header.tiff_diroff);
     }
     /*
      * Now check version (if needed, it's been byte-swapped).
      * Note that this isn't actually a version number, it's a
      * magic number that doesn't change (stupid).
      */
     if (tif->tif_header.tiff_version == TIFF_BIGTIFF_VERSION) {
         TIFFErrorExt(tif->tif_clientdata, name,
                           "This is a BigTIFF file.  This format not supported\n"
                           "by this version of libtiff." );
         goto bad;
     }
     if (tif->tif_header.tiff_version != TIFF_VERSION) {
         TIFFErrorExt(tif->tif_clientdata, name,
             "Not a TIFF file, bad version number %d (0x%x)",
             tif->tif_header.tiff_version,
             tif->tif_header.tiff_version);
         goto bad;
     }
     tif->tif_flags |= TIFF_MYBUFFER;
     tif->tif_rawcp = tif->tif_rawdata = 0;
     tif->tif_rawdatasize = 0;
     /*
      * Sometimes we do not want to read the first directory (for example,
      * it may be broken) and want to proceed to other directories. I this
      * case we use the TIFF_HEADERONLY flag to open file and return
      * immediately after reading TIFF header.
      */
     if (tif->tif_flags & TIFF_HEADERONLY)
         return (tif);
     /*
      * Setup initial directory.
      */
     switch (mode[0]) {
     case 'r':
         tif->tif_nextdiroff = tif->tif_header.tiff_diroff;
         /*
          * Try to use a memory-mapped file if the client
          * has not explicitly suppressed usage with the
          * 'm' flag in the open mode (see above).
          */
         if ((tif->tif_flags & TIFF_MAPPED) &&
     !TIFFMapFileContents(tif, (tdata_t*) &tif->tif_base, &tif->tif_size))
             tif->tif_flags &= ~TIFF_MAPPED;
         if (TIFFReadDirectory(tif)) {
             tif->tif_rawcc = -1;
             tif->tif_flags |= TIFF_BUFFERSETUP;
             return (tif);
         }
         break;
     case 'a':
         /*
          * New directories are automatically append
          * to the end of the directory chain when they
          * are written out (see TIFFWriteDirectory).
          */
         if (!TIFFDefaultDirectory(tif))
             goto bad;
         return (tif);
     }
 bad:
     tif->tif_mode = O_RDONLY;   /* XXX avoid flush */
         TIFFCleanup(tif);
 bad2:
     return ((TIFF*)0);
 }
tdir_t TIFFCurrentDirectory (TIFF * tif)
Definition at line 563 of file tif_open.c.
References tiff::tif_curdir.
 {
     return (tif->tif_curdir);
 }
uint32 TIFFCurrentRow (TIFF * tif)
Definition at line 554 of file tif_open.c.
References tiff::tif_row.
 {
     return (tif->tif_row);
 }
tstrip_t TIFFCurrentStrip (TIFF * tif)
Definition at line 572 of file tif_open.c.
References tiff::tif_curstrip.
 {
     return (tif->tif_curstrip);
 }
ttile_t TIFFCurrentTile (TIFF * tif)
Definition at line 581 of file tif_open.c.
References tiff::tif_curtile.
 {
     return (tif->tif_curtile);
 }
const char* TIFFFileName (TIFF * tif)
Definition at line 464 of file tif_open.c.
References tiff::tif_name.
Referenced by buildMap(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), makebwmap(), makecmap(), setupMap(), TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), and TIFFRGBAImageGet().
 {
     return (tif->tif_name);
 }
int TIFFFileno (TIFF * tif)
Definition at line 484 of file tif_open.c.
References tiff::tif_fd.
 {
     return (tif->tif_fd);
 }
TIFFCloseProc TIFFGetCloseProc (TIFF * tif)
Definition at line 653 of file tif_open.c.
References tiff::tif_closeproc.
 {
     return (tif->tif_closeproc);
 }
TIFFMapFileProc TIFFGetMapFileProc (TIFF * tif)
Definition at line 671 of file tif_open.c.
References tiff::tif_mapproc.
 {
     return (tif->tif_mapproc);
 }
int TIFFGetMode (TIFF * tif)
Definition at line 524 of file tif_open.c.
References tiff::tif_mode.
 {
     return (tif->tif_mode);
 }
TIFFReadWriteProc TIFFGetReadProc (TIFF * tif)
Definition at line 626 of file tif_open.c.
References tiff::tif_readproc.
 {
     return (tif->tif_readproc);
 }
TIFFSeekProc TIFFGetSeekProc (TIFF * tif)
Definition at line 644 of file tif_open.c.
References tiff::tif_seekproc.
 {
     return (tif->tif_seekproc);
 }
TIFFSizeProc TIFFGetSizeProc (TIFF * tif)
Definition at line 662 of file tif_open.c.
References tiff::tif_sizeproc.
 {
     return (tif->tif_sizeproc);
 }
TIFFUnmapFileProc TIFFGetUnmapFileProc (TIFF * tif)
Definition at line 680 of file tif_open.c.
References tiff::tif_unmapproc.
 {
     return (tif->tif_unmapproc);
 }
TIFFReadWriteProc TIFFGetWriteProc (TIFF * tif)
Definition at line 635 of file tif_open.c.
References tiff::tif_writeproc.
 {
     return (tif->tif_writeproc);
 }
static void TIFFInitOrder (TIFF * tif, int magic) static
Definition at line 102 of file tif_open.c.
References bigTypeshift, litTypeshift, tiff::tif_flags, tiff::tif_typemask, tiff::tif_typeshift, TIFF_BIGENDIAN, TIFF_SWAB, and typemask.
Referenced by TIFFClientOpen().
 {
     tif->tif_typemask = typemask;
     if (magic == TIFF_BIGENDIAN) {
         tif->tif_typeshift = bigTypeshift;
 #ifndef WORDS_BIGENDIAN
         tif->tif_flags |= TIFF_SWAB;
 #endif
     } else {
         tif->tif_typeshift = litTypeshift;
 #ifdef WORDS_BIGENDIAN
         tif->tif_flags |= TIFF_SWAB;
 #endif
     }
 }
int TIFFIsBigEndian (TIFF * tif)
Definition at line 617 of file tif_open.c.
References tiff::tif_header, TIFF_BIGENDIAN, and TIFFHeader::tiff_magic.
Referenced by TIFFImageIO::ReadImageInformation().
 {
     return (tif->tif_header.tiff_magic == TIFF_BIGENDIAN);
 }
int TIFFIsByteSwapped (TIFF * tif)
Definition at line 590 of file tif_open.c.
References tiff::tif_flags, and TIFF_SWAB.
 {
     return ((tif->tif_flags & TIFF_SWAB) != 0);
 }
int TIFFIsMSB2LSB (TIFF * tif)
Definition at line 608 of file tif_open.c.
References FILLORDER_MSB2LSB, and isFillOrder.
 {
     return (isFillOrder(tif, FILLORDER_MSB2LSB));
 }
int TIFFIsTiled (TIFF * tif)
Definition at line 545 of file tif_open.c.
References isTiled.
Referenced by TIFFReaderInternal::Initialize(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), and TIFFRGBAImageBegin().
 {
     return (isTiled(tif));
 }
int TIFFIsUpSampled (TIFF * tif)
Definition at line 599 of file tif_open.c.
References isUpSampled.
 {
     return (isUpSampled(tif));
 }
thandle_t TIFFSetClientdata (TIFF * tif, thandle_t newvalue)
Definition at line 513 of file tif_open.c.
References tiff::tif_clientdata.
 {
     thandle_t m = tif->tif_clientdata;
     tif->tif_clientdata = newvalue;
     return m;
 }
const char* TIFFSetFileName (TIFF * tif, const char * name)
Definition at line 473 of file tif_open.c.
References tiff::tif_name.
 {
     const char* old_name = tif->tif_name;
     tif->tif_name = (char *)name;
     return (old_name);
 }
int TIFFSetFileno (TIFF * tif, int fd)
Definition at line 493 of file tif_open.c.
References tiff::tif_fd.
 {
         int old_fd = tif->tif_fd;
     tif->tif_fd = fd;
     return old_fd;
 }
int TIFFSetMode (TIFF * tif, int mode)
Definition at line 533 of file tif_open.c.
References tiff::tif_mode.
 {
     int old_mode = tif->tif_mode;
     tif->tif_mode = mode;
     return (old_mode);
 }
Variable Documentation
const int bigTypeshift[13] static
Initial value:
= {
    0,
    24,
    0,
    16,
    0,
    0,
    24,
    24,
    16,
    0,
    0,
    0,
    0,
}
Definition at line 49 of file tif_open.c.
Referenced by TIFFInitOrder().
const int litTypeshift[13] static
Initial value:
= {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
}
Definition at line 64 of file tif_open.c.
Referenced by TIFFInitOrder().
const long typemask[13] static
Initial value:
= {
    (long)0L,
    (long)0x000000ffL,
    (long)0xffffffffL,
    (long)0x0000ffffL,
    (long)0xffffffffL,
    (long)0xffffffffL,
    (long)0x000000ffL,
    (long)0x000000ffL,
    (long)0x0000ffffL,
    (long)0xffffffffL,
    (long)0xffffffffL,
    (long)0xffffffffL,
    (long)0xffffffffL,
}
Definition at line 34 of file tif_open.c.
Referenced by TIFFInitOrder().