Visible: src/util/code/tif_tile.c File Reference
tif_tile.c File Reference
#include "tiffiop.h"
Functions
static uint32 summarize (TIFF *tif, size_t summand1, size_t summand2, const char *where)
static uint32 multiply (TIFF *tif, size_t nmemb, size_t elem_size, const char *where)
ttile_t TIFFComputeTile (TIFF *tif, uint32 x, uint32 y, uint32 z, tsample_t s)
int TIFFCheckTile (TIFF *tif, uint32 x, uint32 y, uint32 z, tsample_t s)
ttile_t TIFFNumberOfTiles (TIFF *tif)
tsize_t TIFFTileRowSize (TIFF *tif)
tsize_t TIFFVTileSize (TIFF *tif, uint32 nrows)
tsize_t TIFFTileSize (TIFF *tif)
void TIFFDefaultTileSize (TIFF *tif, uint32 *tw, uint32 *th)
void _TIFFDefaultTileSize (TIFF *tif, uint32 *tw, uint32 *th)
Function Documentation
void _TIFFDefaultTileSize (TIFF * tif, uint32 * tw, uint32 * th)
Definition at line 251 of file tif_tile.c.
References TIFFroundup.
Referenced by _TIFFSetDefaultCompressionState().
 {
     (void) tif;
     if (*(int32*) tw < 1)
         *tw = 256;
     if (*(int32*) th < 1)
         *th = 256;
     /* roundup to a multiple of 16 per the spec */
     if (*tw & 0xf)
         *tw = TIFFroundup(*tw, 16);
     if (*th & 0xf)
         *th = TIFFroundup(*th, 16);
 }
static uint32 multiply (TIFF * tif, size_t nmemb, size_t elem_size, const char * where) static
Definition at line 52 of file tif_tile.c.
References tiff::tif_clientdata, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFNumberOfTiles(), TIFFTileRowSize(), and TIFFVTileSize().
 {
     uint32  bytes = nmemb * elem_size;
     if (elem_size && bytes / elem_size != nmemb) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Integer overflow in %s", where);
         bytes = 0;
     }
     return (bytes);
 }
static uint32 summarize (TIFF * tif, size_t summand1, size_t summand2, const char * where) static
Definition at line 35 of file tif_tile.c.
References tiff::tif_clientdata, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFVTileSize().
 {
     /*
      * XXX: We are using casting to uint32 here, because sizeof(size_t)
      * may be larger than sizeof(uint32) on 64-bit architectures.
      */
     uint32  bytes = summand1 + summand2;
     if (bytes - summand1 != summand2) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Integer overflow in %s", where);
         bytes = 0;
     }
     return (bytes);
 }
int TIFFCheckTile (TIFF * tif, uint32 x, uint32 y, uint32 z, tsample_t s)
Definition at line 105 of file tif_tile.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFReadTile(), and TIFFWriteTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (x >= td->td_imagewidth) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Col out of range, max %lu",
             (unsigned long) x, (unsigned long) td->td_imagewidth);
         return (0);
     }
     if (y >= td->td_imagelength) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Row out of range, max %lu",
             (unsigned long) y, (unsigned long) td->td_imagelength);
         return (0);
     }
     if (z >= td->td_imagedepth) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Depth out of range, max %lu",
             (unsigned long) z, (unsigned long) td->td_imagedepth);
         return (0);
     }
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE &&
         s >= td->td_samplesperpixel) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Sample out of range, max %lu",
             (unsigned long) s, (unsigned long) td->td_samplesperpixel);
         return (0);
     }
     return (1);
 }
ttile_t TIFFComputeTile (TIFF * tif, uint32 x, uint32 y, uint32 z, tsample_t s)
Definition at line 68 of file tif_tile.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_dir, and TIFFhowmany.
Referenced by TIFFReadTile(), and TIFFWriteTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     uint32 dx = td->td_tilewidth;
     uint32 dy = td->td_tilelength;
     uint32 dz = td->td_tiledepth;
     ttile_t tile = 1;
     if (td->td_imagedepth == 1)
         z = 0;
     if (dx == (uint32) -1)
         dx = td->td_imagewidth;
     if (dy == (uint32) -1)
         dy = td->td_imagelength;
     if (dz == (uint32) -1)
         dz = td->td_imagedepth;
     if (dx != 0 && dy != 0 && dz != 0) {
         uint32 xpt = TIFFhowmany(td->td_imagewidth, dx);
         uint32 ypt = TIFFhowmany(td->td_imagelength, dy);
         uint32 zpt = TIFFhowmany(td->td_imagedepth, dz);
         if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
             tile = (xpt*ypt*zpt)*s +
                  (xpt*ypt)*(z/dz) +
                  xpt*(y/dy) +
                  x/dx;
         else
             tile = (xpt*ypt)*(z/dz) + xpt*(y/dy) + x/dx;
     }
     return (tile);
 }
void TIFFDefaultTileSize (TIFF * tif, uint32 * tw, uint32 * th)
Definition at line 245 of file tif_tile.c.
References tiff::tif_deftilesize.
 {
     (*tif->tif_deftilesize)(tif, tw, th);
 }
ttile_t TIFFNumberOfTiles (TIFF * tif)
Definition at line 137 of file tif_tile.c.
References multiply(), PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_dir, and TIFFhowmany.
Referenced by TIFFReaderInternal::Initialize(), TIFFReadDirectory(), and TIFFSetupStrips().
 {
     TIFFDirectory *td = &tif->tif_dir;
     uint32 dx = td->td_tilewidth;
     uint32 dy = td->td_tilelength;
     uint32 dz = td->td_tiledepth;
     ttile_t ntiles;
     if (dx == (uint32) -1)
         dx = td->td_imagewidth;
     if (dy == (uint32) -1)
         dy = td->td_imagelength;
     if (dz == (uint32) -1)
         dz = td->td_imagedepth;
     ntiles = (dx == 0 || dy == 0 || dz == 0) ? 0 :
         multiply(tif, multiply(tif, TIFFhowmany(td->td_imagewidth, dx),
                    TIFFhowmany(td->td_imagelength, dy),
                    "TIFFNumberOfTiles"),
              TIFFhowmany(td->td_imagedepth, dz), "TIFFNumberOfTiles");
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
         ntiles = multiply(tif, ntiles, td->td_samplesperpixel,
                   "TIFFNumberOfTiles");
     return (ntiles);
 }
tsize_t TIFFTileRowSize (TIFF * tif)
Definition at line 166 of file tif_tile.c.
References multiply(), PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_dir, and TIFFhowmany8.
Referenced by gtTileContig(), gtTileSeparate(), PredictorSetup(), and TIFFVTileSize().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t rowsize;
     if (td->td_tilelength == 0 || td->td_tilewidth == 0)
         return ((tsize_t) 0);
     rowsize = multiply(tif, td->td_bitspersample, td->td_tilewidth,
                "TIFFTileRowSize");
     if (td->td_planarconfig == PLANARCONFIG_CONTIG)
         rowsize = multiply(tif, rowsize, td->td_samplesperpixel,
                    "TIFFTileRowSize");
     return ((tsize_t) TIFFhowmany8(rowsize));
 }
tsize_t TIFFTileSize (TIFF * tif)
Definition at line 233 of file tif_tile.c.
References TIFFDirectory::td_tilelength, tiff::tif_dir, and TIFFVTileSize().
Referenced by gtTileContig(), gtTileSeparate(), TIFFReadDirectory(), and TIFFWriteCheck().
 {
     return (TIFFVTileSize(tif, tif->tif_dir.td_tilelength));
 }
tsize_t TIFFVTileSize (TIFF * tif, uint32 nrows)
Definition at line 185 of file tif_tile.c.
References isUpSampled, multiply(), PHOTOMETRIC_YCBCR, PLANARCONFIG_CONTIG, summarize(), TIFFDirectory::td_bitspersample, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, TIFFDirectory::td_ycbcrsubsampling, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), TIFFhowmany8, TIFFroundup, and TIFFTileRowSize().
Referenced by ChopUpSingleUncompressedStrip(), and TIFFTileSize().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t tilesize;
     if (td->td_tilelength == 0 || td->td_tilewidth == 0 ||
         td->td_tiledepth == 0)
         return ((tsize_t) 0);
     if (td->td_planarconfig == PLANARCONFIG_CONTIG &&
         td->td_photometric == PHOTOMETRIC_YCBCR &&
         !isUpSampled(tif)) {
         /*
          * Packed YCbCr data contain one Cb+Cr for every
          * HorizontalSampling*VerticalSampling Y values.
          * Must also roundup width and height when calculating
          * since images that are not a multiple of the
          * horizontal/vertical subsampling area include
          * YCbCr data for the extended image.
          */
         tsize_t w =
             TIFFroundup(td->td_tilewidth, td->td_ycbcrsubsampling[0]);
         tsize_t rowsize =
             TIFFhowmany8(multiply(tif, w, td->td_bitspersample,
                       "TIFFVTileSize"));
         tsize_t samplingarea =
             td->td_ycbcrsubsampling[0]*td->td_ycbcrsubsampling[1];
         if (samplingarea == 0) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Invalid YCbCr subsampling");
             return 0;
         }
         nrows = TIFFroundup(nrows, td->td_ycbcrsubsampling[1]);
         /* NB: don't need TIFFhowmany here 'cuz everything is rounded */
         tilesize = multiply(tif, nrows, rowsize, "TIFFVTileSize");
         tilesize = summarize(tif, tilesize,
                      multiply(tif, 2, tilesize / samplingarea,
                           "TIFFVTileSize"),
                      "TIFFVTileSize");
     } else
         tilesize = multiply(tif, nrows, TIFFTileRowSize(tif),
                     "TIFFVTileSize");
     return ((tsize_t)
         multiply(tif, tilesize, td->td_tiledepth, "TIFFVTileSize"));
 }