Visible: src/util/code/tif_read.c File Reference
tif_read.c File Reference
#include "tiffiop.h"
#include <stdio.h>
Macros
#define NOSTRIP ((tstrip_t) -1) /* undefined state */
#define NOTILE ((ttile_t) -1) /* undefined state */
Functions
int TIFFFillStrip (TIFF *, tstrip_t)
int TIFFFillTile (TIFF *, ttile_t)
static int TIFFStartStrip (TIFF *, tstrip_t)
static int TIFFStartTile (TIFF *, ttile_t)
static int TIFFCheckRead (TIFF *, int)
static int TIFFSeek (TIFF *tif, uint32 row, tsample_t sample)
int TIFFReadScanline (TIFF *tif, tdata_t buf, uint32 row, tsample_t sample)
tsize_t TIFFReadEncodedStrip (TIFF *tif, tstrip_t strip, tdata_t buf, tsize_t size)
static tsize_t TIFFReadRawStrip1 (TIFF *tif, tstrip_t strip, tdata_t buf, tsize_t size, const char *module)
tsize_t TIFFReadRawStrip (TIFF *tif, tstrip_t strip, tdata_t buf, tsize_t size)
tsize_t TIFFReadTile (TIFF *tif, tdata_t buf, uint32 x, uint32 y, uint32 z, tsample_t s)
tsize_t TIFFReadEncodedTile (TIFF *tif, ttile_t tile, tdata_t buf, tsize_t size)
static tsize_t TIFFReadRawTile1 (TIFF *tif, ttile_t tile, tdata_t buf, tsize_t size, const char *module)
tsize_t TIFFReadRawTile (TIFF *tif, ttile_t tile, tdata_t buf, tsize_t size)
int TIFFReadBufferSetup (TIFF *tif, tdata_t bp, tsize_t size)
void _TIFFNoPostDecode (TIFF *tif, tidata_t buf, tsize_t cc)
void _TIFFSwab16BitData (TIFF *tif, tidata_t buf, tsize_t cc)
void _TIFFSwab24BitData (TIFF *tif, tidata_t buf, tsize_t cc)
void _TIFFSwab32BitData (TIFF *tif, tidata_t buf, tsize_t cc)
void _TIFFSwab64BitData (TIFF *tif, tidata_t buf, tsize_t cc)
Macro Definition Documentation
#define NOSTRIP ((tstrip_t) -1) /* undefined state */
Definition at line 40 of file tif_read.c.
Referenced by TIFFFillStrip().
#define NOTILE ((ttile_t) -1) /* undefined state */
Definition at line 41 of file tif_read.c.
Referenced by TIFFFillTile().
Function Documentation
void _TIFFNoPostDecode (TIFF * tif, tidata_t buf, tsize_t cc)
Definition at line 613 of file tif_read.c.
Referenced by PredictorSetupDecode(), and TIFFDefaultDirectory().
 {
     (void) tif; (void) buf; (void) cc;
 }
void _TIFFSwab16BitData (TIFF * tif, tidata_t buf, tsize_t cc)
Definition at line 619 of file tif_read.c.
References TIFFSwabArrayOfShort().
Referenced by _TIFFVSetField().
 {
     (void) tif;
     assert((cc & 1) == 0);
     TIFFSwabArrayOfShort((uint16*) buf, cc/2);
 }
void _TIFFSwab24BitData (TIFF * tif, tidata_t buf, tsize_t cc)
Definition at line 627 of file tif_read.c.
References TIFFSwabArrayOfTriples().
Referenced by _TIFFVSetField().
 {
     (void) tif;
     assert((cc % 3) == 0);
     TIFFSwabArrayOfTriples((uint8*) buf, cc/3);
 }
void _TIFFSwab32BitData (TIFF * tif, tidata_t buf, tsize_t cc)
Definition at line 635 of file tif_read.c.
References TIFFSwabArrayOfLong().
Referenced by _TIFFVSetField().
 {
     (void) tif;
     assert((cc & 3) == 0);
     TIFFSwabArrayOfLong((uint32*) buf, cc/4);
 }
void _TIFFSwab64BitData (TIFF * tif, tidata_t buf, tsize_t cc)
Definition at line 643 of file tif_read.c.
References TIFFSwabArrayOfDouble().
Referenced by _TIFFVSetField().
 {
     (void) tif;
     assert((cc & 7) == 0);
     TIFFSwabArrayOfDouble((double*) buf, cc/8);
 }
static int TIFFCheckRead (TIFF * tif, int tiles) static
Definition at line 597 of file tif_read.c.
References isTiled, tiff::tif_clientdata, tiff::tif_mode, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFReadEncodedStrip(), TIFFReadEncodedTile(), TIFFReadRawStrip(), TIFFReadRawTile(), TIFFReadScanline(), and TIFFReadTile().
 {
     if (tif->tif_mode == O_WRONLY) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "File not open for reading");
         return (0);
     }
     if (tiles ^ isTiled(tif)) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, tiles ?
             "Can not read tiles from a stripped image" :
             "Can not read scanlines from a tiled image");
         return (0);
     }
     return (1);
 }
int TIFFFillStrip (TIFF * tif, tstrip_t strip)
Definition at line 245 of file tif_read.c.
References _TIFFfree(), isFillOrder, isMapped, NOSTRIP, TIFFDirectory::td_fillorder, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripoffset, tiff::tif_base, tiff::tif_clientdata, tiff::tif_curstrip, tiff::tif_dir, tiff::tif_flags, tiff::tif_name, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_size, TIFF_MYBUFFER, TIFF_NOBITREV, TIFFErrorExt(), TIFFReadBufferSetup(), TIFFReadRawStrip1(), TIFFReverseBits(), TIFFroundup, and TIFFStartStrip().
Referenced by TIFFReadEncodedStrip(), and TIFFSeek().
 {
     static const char module[] = "TIFFFillStrip";
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t bytecount;
     bytecount = td->td_stripbytecount[strip];
     if (bytecount <= 0) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
             "%lu: Invalid strip byte count, strip %lu",
             (unsigned long) bytecount, (unsigned long) strip);
         return (0);
     }
     if (isMapped(tif) &&
         (isFillOrder(tif, td->td_fillorder)
              || (tif->tif_flags & TIFF_NOBITREV))) {
         /*
          * The image is mapped into memory and we either don't
          * need to flip bits or the compression routine is going
          * to handle this operation itself.  In this case, avoid
          * copying the raw data and instead just reference the
          * data from the memory mapped file image.  This assumes
          * that the decompression routines do not modify the
          * contents of the raw data buffer (if they try to,
          * the application will get a fault since the file is
          * mapped read-only).
          */
         if ((tif->tif_flags & TIFF_MYBUFFER) && tif->tif_rawdata)
             _TIFFfree(tif->tif_rawdata);
         tif->tif_flags &= ~TIFF_MYBUFFER;
         if ( td->td_stripoffset[strip] + bytecount > tif->tif_size) {
             /*
              * This error message might seem strange, but it's
              * what would happen if a read were done instead.
              */
             TIFFErrorExt(tif->tif_clientdata, module,
             "%s: Read error on strip %lu; got %lu bytes, expected %lu",
                 tif->tif_name,
                 (unsigned long) strip,
                 (unsigned long) tif->tif_size - td->td_stripoffset[strip],
                 (unsigned long) bytecount);
             tif->tif_curstrip = NOSTRIP;
             return (0);
         }
         tif->tif_rawdatasize = bytecount;
         tif->tif_rawdata = tif->tif_base + td->td_stripoffset[strip];
     } else {
         /*
          * Expand raw data buffer, if needed, to
          * hold data strip coming from file
          * (perhaps should set upper bound on
          *  the size of a buffer we'll use?).
          */
         if (bytecount > tif->tif_rawdatasize) {
             tif->tif_curstrip = NOSTRIP;
             if ((tif->tif_flags & TIFF_MYBUFFER) == 0) {
                 TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Data buffer too small to hold strip %lu",
                     tif->tif_name, (unsigned long) strip);
                 return (0);
             }
             if (!TIFFReadBufferSetup(tif, 0,
                 TIFFroundup(bytecount, 1024)))
                 return (0);
         }
         if (TIFFReadRawStrip1(tif, strip, (unsigned char *)tif->tif_rawdata,
             bytecount, module) != bytecount)
             return (0);
         if (!isFillOrder(tif, td->td_fillorder) &&
             (tif->tif_flags & TIFF_NOBITREV) == 0)
             TIFFReverseBits(tif->tif_rawdata, bytecount);
     }
     return (TIFFStartStrip(tif, strip));
 }
int TIFFFillTile (TIFF * tif, ttile_t tile)
Definition at line 443 of file tif_read.c.
References _TIFFfree(), isFillOrder, isMapped, NOTILE, TIFFDirectory::td_fillorder, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripoffset, tiff::tif_base, tiff::tif_clientdata, tiff::tif_curtile, tiff::tif_dir, tiff::tif_flags, tiff::tif_name, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_size, TIFF_MYBUFFER, TIFF_NOBITREV, TIFFErrorExt(), TIFFReadBufferSetup(), TIFFReadRawTile1(), TIFFReverseBits(), TIFFroundup, and TIFFStartTile().
Referenced by TIFFReadEncodedTile().
 {
     static const char module[] = "TIFFFillTile";
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t bytecount;
     bytecount = td->td_stripbytecount[tile];
     if (bytecount <= 0) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
             "%lu: Invalid tile byte count, tile %lu",
             (unsigned long) bytecount, (unsigned long) tile);
         return (0);
     }
     if (isMapped(tif) &&
         (isFillOrder(tif, td->td_fillorder)
              || (tif->tif_flags & TIFF_NOBITREV))) {
         /*
          * The image is mapped into memory and we either don't
          * need to flip bits or the compression routine is going
          * to handle this operation itself.  In this case, avoid
          * copying the raw data and instead just reference the
          * data from the memory mapped file image.  This assumes
          * that the decompression routines do not modify the
          * contents of the raw data buffer (if they try to,
          * the application will get a fault since the file is
          * mapped read-only).
          */
         if ((tif->tif_flags & TIFF_MYBUFFER) && tif->tif_rawdata)
             _TIFFfree(tif->tif_rawdata);
         tif->tif_flags &= ~TIFF_MYBUFFER;
         if ( td->td_stripoffset[tile] + bytecount > tif->tif_size) {
             tif->tif_curtile = NOTILE;
             return (0);
         }
         tif->tif_rawdatasize = bytecount;
         tif->tif_rawdata = tif->tif_base + td->td_stripoffset[tile];
     } else {
         /*
          * Expand raw data buffer, if needed, to
          * hold data tile coming from file
          * (perhaps should set upper bound on
          *  the size of a buffer we'll use?).
          */
         if (bytecount > tif->tif_rawdatasize) {
             tif->tif_curtile = NOTILE;
             if ((tif->tif_flags & TIFF_MYBUFFER) == 0) {
                 TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Data buffer too small to hold tile %ld",
                     tif->tif_name, (long) tile);
                 return (0);
             }
             if (!TIFFReadBufferSetup(tif, 0,
                 TIFFroundup(bytecount, 1024)))
                 return (0);
         }
         if (TIFFReadRawTile1(tif, tile,
                                      (unsigned char *)tif->tif_rawdata,
                                      bytecount, module) != bytecount)
             return (0);
         if (!isFillOrder(tif, td->td_fillorder) &&
             (tif->tif_flags & TIFF_NOBITREV) == 0)
             TIFFReverseBits(tif->tif_rawdata, bytecount);
     }
     return (TIFFStartTile(tif, tile));
 }
int TIFFReadBufferSetup (TIFF * tif, tdata_t bp, tsize_t size)
Definition at line 519 of file tif_read.c.
References _TIFFfree(), _TIFFmalloc(), NULL, tiff::tif_clientdata, tiff::tif_flags, tiff::tif_name, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_row, TIFF_MYBUFFER, TIFFErrorExt(), and TIFFroundup.
Referenced by TIFFFillStrip(), and TIFFFillTile().
 {
     static const char module[] = "TIFFReadBufferSetup";
     if (tif->tif_rawdata) {
         if (tif->tif_flags & TIFF_MYBUFFER)
             _TIFFfree(tif->tif_rawdata);
         tif->tif_rawdata = NULL;
     }
     if (bp) {
         tif->tif_rawdatasize = size;
         tif->tif_rawdata = (tidata_t) bp;
         tif->tif_flags &= ~TIFF_MYBUFFER;
     } else {
         tif->tif_rawdatasize = TIFFroundup(size, 1024);
         tif->tif_rawdata = (tidata_t) _TIFFmalloc(tif->tif_rawdatasize);
         tif->tif_flags |= TIFF_MYBUFFER;
     }
     if (tif->tif_rawdata == NULL) {
         TIFFErrorExt(tif->tif_clientdata, module,
             "%s: No space for data buffer at scanline %ld",
             tif->tif_name, (long) tif->tif_row);
         tif->tif_rawdatasize = 0;
         return (0);
     }
     return (1);
 }
tsize_t TIFFReadEncodedStrip (TIFF * tif, tstrip_t strip, tdata_t buf, tsize_t size)
Definition at line 122 of file tif_read.c.
References TIFFDirectory::td_imagelength, TIFFDirectory::td_nstrips, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_decodestrip, tiff::tif_dir, tiff::tif_name, tiff::tif_postdecode, TIFFCheckRead(), TIFFErrorExt(), TIFFFillStrip(), and TIFFVStripSize().
Referenced by gtStripContig(), and gtStripSeparate().
 {
     TIFFDirectory *td = &tif->tif_dir;
     uint32 nrows;
     tsize_t stripsize;
         tstrip_t sep_strip, strips_per_sep;
     if (!TIFFCheckRead(tif, 0))
         return (-1);
     if (strip >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%ld: Strip out of range, max %ld",
             (long) strip, (long) td->td_nstrips);
         return (-1);
     }
     /*
      * Calculate the strip size according to the number of
      * rows in the strip (check for truncated last strip on any
          * of the separations).
      */
         if( td->td_rowsperstrip >= td->td_imagelength )
             strips_per_sep = 1;
         else
             strips_per_sep = (td->td_imagelength+td->td_rowsperstrip-1)
                 / td->td_rowsperstrip;
         sep_strip = strip % strips_per_sep;
     if (sep_strip != strips_per_sep-1 ||
         (nrows = td->td_imagelength % td->td_rowsperstrip) == 0)
         nrows = td->td_rowsperstrip;
     stripsize = TIFFVStripSize(tif, nrows);
     if (size == (tsize_t) -1)
         size = stripsize;
     else if (size > stripsize)
         size = stripsize;
     if (TIFFFillStrip(tif, strip)
             && (*tif->tif_decodestrip)(tif, (tidata_t) buf, size,
                          (tsample_t)(strip / td->td_stripsperimage)) > 0 ) {
         (*tif->tif_postdecode)(tif, (tidata_t) buf, size);
         return (size);
     } else
         return ((tsize_t) -1);
 }
tsize_t TIFFReadEncodedTile (TIFF * tif, ttile_t tile, tdata_t buf, tsize_t size)
Definition at line 344 of file tif_read.c.
References TIFFDirectory::td_nstrips, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_decodetile, tiff::tif_dir, tiff::tif_name, tiff::tif_postdecode, tiff::tif_tilesize, TIFFCheckRead(), TIFFErrorExt(), and TIFFFillTile().
Referenced by TIFFReadTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t tilesize = tif->tif_tilesize;
     if (!TIFFCheckRead(tif, 1))
         return (-1);
     if (tile >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%ld: Tile out of range, max %ld",
             (long) tile, (unsigned long) td->td_nstrips);
         return (-1);
     }
     if (size == (tsize_t) -1)
         size = tilesize;
     else if (size > tilesize)
         size = tilesize;
     if (TIFFFillTile(tif, tile) && (*tif->tif_decodetile)(tif,
         (tidata_t) buf, size, (tsample_t)(tile/td->td_stripsperimage))) {
         (*tif->tif_postdecode)(tif, (tidata_t) buf, size);
         return (size);
     } else
         return (-1);
 }
tsize_t TIFFReadRawStrip (TIFF * tif, tstrip_t strip, tdata_t buf, tsize_t size)
Definition at line 214 of file tif_read.c.
References TIFFDirectory::td_nstrips, TIFFDirectory::td_stripbytecount, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFCheckRead(), TIFFErrorExt(), and TIFFReadRawStrip1().
Referenced by TIFFImageIO::ReadGenericImage().
 {
     static const char module[] = "TIFFReadRawStrip";
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t bytecount;
     if (!TIFFCheckRead(tif, 0))
         return ((tsize_t) -1);
     if (strip >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Strip out of range, max %lu",
             (unsigned long) strip, (unsigned long) td->td_nstrips);
         return ((tsize_t) -1);
     }
     bytecount = td->td_stripbytecount[strip];
     if (bytecount <= 0) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
             "%lu: Invalid strip byte count, strip %lu",
             (unsigned long) bytecount, (unsigned long) strip);
         return ((tsize_t) -1);
     }
     if (size != (tsize_t)-1 && size < bytecount)
         bytecount = size;
     return (TIFFReadRawStrip1(tif, strip, buf, bytecount, module));
 }
static tsize_t TIFFReadRawStrip1 (TIFF * tif, tstrip_t strip, tdata_t buf, tsize_t size, const char * module) static
Definition at line 168 of file tif_read.c.
References _TIFFmemcpy(), isMapped, SeekOK, TIFFDirectory::td_stripoffset, tiff::tif_base, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, tiff::tif_row, tiff::tif_size, TIFFErrorExt(), and TIFFReadFile.
Referenced by TIFFFillStrip(), and TIFFReadRawStrip().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (!isMapped(tif)) {
         tsize_t cc;
         if (!SeekOK(tif, td->td_stripoffset[strip])) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Seek error at scanline %lu, strip %lu",
                 tif->tif_name,
                 (unsigned long) tif->tif_row, (unsigned long) strip);
             return (-1);
         }
         cc = TIFFReadFile(tif, buf, size);
         if (cc != size) {
             TIFFErrorExt(tif->tif_clientdata, module,
         "%s: Read error at scanline %lu; got %lu bytes, expected %lu",
                 tif->tif_name,
                 (unsigned long) tif->tif_row,
                 (unsigned long) cc,
                 (unsigned long) size);
             return (-1);
         }
     } else {
         if (td->td_stripoffset[strip] + size > tif->tif_size) {
             TIFFErrorExt(tif->tif_clientdata, module,
     "%s: Read error at scanline %lu, strip %lu; got %lu bytes, expected %lu",
                 tif->tif_name,
                 (unsigned long) tif->tif_row,
                 (unsigned long) strip,
                 (unsigned long) tif->tif_size - td->td_stripoffset[strip],
                 (unsigned long) size);
             return (-1);
         }
         _TIFFmemcpy(buf, tif->tif_base + td->td_stripoffset[strip],
                             size);
     }
     return (size);
 }
tsize_t TIFFReadRawTile (TIFF * tif, ttile_t tile, tdata_t buf, tsize_t size)
Definition at line 418 of file tif_read.c.
References TIFFDirectory::td_nstrips, TIFFDirectory::td_stripbytecount, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFCheckRead(), TIFFErrorExt(), and TIFFReadRawTile1().
 {
     static const char module[] = "TIFFReadRawTile";
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t bytecount;
     if (!TIFFCheckRead(tif, 1))
         return ((tsize_t) -1);
     if (tile >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Tile out of range, max %lu",
             (unsigned long) tile, (unsigned long) td->td_nstrips);
         return ((tsize_t) -1);
     }
     bytecount = td->td_stripbytecount[tile];
     if (size != (tsize_t) -1 && size < bytecount)
         bytecount = size;
     return (TIFFReadRawTile1(tif, tile, buf, bytecount, module));
 }
static tsize_t TIFFReadRawTile1 (TIFF * tif, ttile_t tile, tdata_t buf, tsize_t size, const char * module) static
Definition at line 369 of file tif_read.c.
References _TIFFmemcpy(), isMapped, SeekOK, TIFFDirectory::td_stripoffset, tiff::tif_base, tiff::tif_clientdata, tiff::tif_col, tiff::tif_dir, tiff::tif_name, tiff::tif_row, tiff::tif_size, TIFFErrorExt(), and TIFFReadFile.
Referenced by TIFFFillTile(), and TIFFReadRawTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (!isMapped(tif)) {
         tsize_t cc;
         if (!SeekOK(tif, td->td_stripoffset[tile])) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Seek error at row %ld, col %ld, tile %ld",
                 tif->tif_name,
                 (long) tif->tif_row,
                 (long) tif->tif_col,
                 (long) tile);
             return ((tsize_t) -1);
         }
         cc = TIFFReadFile(tif, buf, size);
         if (cc != size) {
             TIFFErrorExt(tif->tif_clientdata, module,
         "%s: Read error at row %ld, col %ld; got %lu bytes, expected %lu",
                 tif->tif_name,
                 (long) tif->tif_row,
                 (long) tif->tif_col,
                 (unsigned long) cc,
                 (unsigned long) size);
             return ((tsize_t) -1);
         }
     } else {
         if (td->td_stripoffset[tile] + size > tif->tif_size) {
             TIFFErrorExt(tif->tif_clientdata, module,
     "%s: Read error at row %ld, col %ld, tile %ld; got %lu bytes, expected %lu",
                 tif->tif_name,
                 (long) tif->tif_row,
                 (long) tif->tif_col,
                 (long) tile,
                 (unsigned long) tif->tif_size - td->td_stripoffset[tile],
                 (unsigned long) size);
             return ((tsize_t) -1);
         }
         _TIFFmemcpy(buf, tif->tif_base + td->td_stripoffset[tile], size);
     }
     return (size);
 }
int TIFFReadScanline (TIFF * tif, tdata_t buf, uint32 row, tsample_t sample)
Definition at line 94 of file tif_read.c.
References sample(), tiff::tif_decoderow, tiff::tif_postdecode, tiff::tif_row, tiff::tif_scanlinesize, TIFFCheckRead(), and TIFFSeek().
 {
     int e;
     if (!TIFFCheckRead(tif, 0))
         return (-1);
     if( (e = TIFFSeek(tif, row, sample)) != 0) {
         /*
          * Decompress desired row into user buffer.
          */
         e = (*tif->tif_decoderow)
             (tif, (tidata_t) buf, tif->tif_scanlinesize, sample);
                 /* we are now poised at the beginning of the next row */
                 tif->tif_row = row + 1;
         if (e)
             (*tif->tif_postdecode)(tif, (tidata_t) buf,
                 tif->tif_scanlinesize);
     }
     return (e > 0 ? 1 : -1);
 }
tsize_t TIFFReadTile (TIFF * tif, tdata_t buf, uint32 x, uint32 y, uint32 z, tsample_t s)
Definition at line 330 of file tif_read.c.
References TIFFCheckRead(), TIFFCheckTile(), TIFFComputeTile(), and TIFFReadEncodedTile().
Referenced by gtTileContig(), and gtTileSeparate().
 {
     if (!TIFFCheckRead(tif, 1) || !TIFFCheckTile(tif, x, y, z, s))
         return (-1);
     return (TIFFReadEncodedTile(tif,
         TIFFComputeTile(tif, x, y, z, s), buf, (tsize_t) -1));
 }
static int TIFFSeek (TIFF * tif, uint32 row, tsample_t sample) static
Definition at line 47 of file tif_read.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagelength, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_curstrip, tiff::tif_dir, tiff::tif_name, tiff::tif_row, tiff::tif_seek, TIFFErrorExt(), TIFFFillStrip(), and TIFFStartStrip().
Referenced by TIFFReadScanline().
 {
     register TIFFDirectory *td = &tif->tif_dir;
     tstrip_t strip;
     if (row >= td->td_imagelength) {    /* out of range */
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Row out of range, max %lu",
             (unsigned long) row, (unsigned long) td->td_imagelength);
         return (0);
     }
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
         if (sample >= td->td_samplesperpixel) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
                 "%lu: Sample out of range, max %lu",
                 (unsigned long) sample, (unsigned long) td->td_samplesperpixel);
             return (0);
         }
         strip = sample*td->td_stripsperimage + row/td->td_rowsperstrip;
     } else
         strip = row / td->td_rowsperstrip;
     if (strip != tif->tif_curstrip) {   /* different strip, refill */
         if (!TIFFFillStrip(tif, strip))
             return (0);
     } else if (row < tif->tif_row) {
         /*
          * Moving backwards within the same strip: backup
          * to the start and then decode forward (below).
          *
          * NB: If you're planning on lots of random access within a
          * strip, it's better to just read and decode the entire
          * strip, and then access the decoded data in a random fashion.
          */
         if (!TIFFStartStrip(tif, strip))
             return (0);
     }
     if (row != tif->tif_row) {
         /*
          * Seek forward to the desired row.
          */
         if (!(*tif->tif_seek)(tif, row - tif->tif_row))
             return (0);
         tif->tif_row = row;
     }
     return (1);
 }
static int TIFFStartStrip (TIFF * tif, tstrip_t strip) static
Definition at line 552 of file tif_read.c.
References TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripsperimage, tiff::tif_curstrip, tiff::tif_dir, tiff::tif_flags, tiff::tif_predecode, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_row, tiff::tif_setupdecode, and TIFF_CODERSETUP.
Referenced by TIFFFillStrip(), and TIFFSeek().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if ((tif->tif_flags & TIFF_CODERSETUP) == 0) {
         if (!(*tif->tif_setupdecode)(tif))
             return (0);
         tif->tif_flags |= TIFF_CODERSETUP;
     }
     tif->tif_curstrip = strip;
     tif->tif_row = (strip % td->td_stripsperimage) * td->td_rowsperstrip;
     tif->tif_rawcp = tif->tif_rawdata;
     tif->tif_rawcc = td->td_stripbytecount[strip];
     return ((*tif->tif_predecode)(tif,
             (tsample_t)(strip / td->td_stripsperimage)));
 }
static int TIFFStartTile (TIFF * tif, ttile_t tile) static
Definition at line 574 of file tif_read.c.
References TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripsperimage, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_col, tiff::tif_curtile, tiff::tif_dir, tiff::tif_flags, tiff::tif_predecode, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_row, tiff::tif_setupdecode, TIFF_CODERSETUP, and TIFFhowmany.
Referenced by TIFFFillTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if ((tif->tif_flags & TIFF_CODERSETUP) == 0) {
         if (!(*tif->tif_setupdecode)(tif))
             return (0);
         tif->tif_flags |= TIFF_CODERSETUP;
     }
     tif->tif_curtile = tile;
     tif->tif_row =
         (tile % TIFFhowmany(td->td_imagewidth, td->td_tilewidth)) *
         td->td_tilelength;
     tif->tif_col =
         (tile % TIFFhowmany(td->td_imagelength, td->td_tilelength)) *
         td->td_tilewidth;
     tif->tif_rawcp = tif->tif_rawdata;
     tif->tif_rawcc = td->td_stripbytecount[tile];
     return ((*tif->tif_predecode)(tif,
             (tsample_t)(tile/td->td_stripsperimage)));
 }