Visible: src/util/code/tif_close.c File Reference
tif_close.c File Reference
#include "tiffiop.h"
Functions
void TIFFCleanup (TIFF *tif)
void TIFFClose (TIFF *tif)
Function Documentation
void TIFFCleanup (TIFF * tif)
Auxiliary function to free the TIFF structure. Given structure will be completetly freed, so you should save opened file handle and pointer to the close procedure in external variables before calling _TIFFCleanup(), if you will need these ones to close the file.
Parameters
tif A TIFF pointer.
Definition at line 46 of file tif_close.c.
References _TIFFfree(), TIFFFieldInfo::field_bit, FIELD_CUSTOM, TIFFFieldInfo::field_name, isMapped, client_info::name, client_info::next, tiff::tif_base, tiff::tif_cleanup, tiff::tif_clientinfo, tiff::tif_dirlist, tiff::tif_fieldinfo, tiff::tif_flags, tiff::tif_mode, tiff::tif_nfields, tiff::tif_rawdata, tiff::tif_size, TIFF_MYBUFFER, TIFFFlush(), TIFFFreeDirectory(), and TIFFUnmapFileContents.
Referenced by TIFFClientOpen(), and TIFFClose().
 {
     if (tif->tif_mode != O_RDONLY)
         /*
          * Flush buffered data and directory (if dirty).
          */
         TIFFFlush(tif);
     (*tif->tif_cleanup)(tif);
     TIFFFreeDirectory(tif);
     if (tif->tif_dirlist)
         _TIFFfree(tif->tif_dirlist);
     /* Clean up client info links */
     while( tif->tif_clientinfo )
     {
         TIFFClientInfoLink *link = tif->tif_clientinfo;
         tif->tif_clientinfo = link->next;
         _TIFFfree( link->name );
         _TIFFfree( link );
     }
     if (tif->tif_rawdata && (tif->tif_flags&TIFF_MYBUFFER))
         _TIFFfree(tif->tif_rawdata);
     if (isMapped(tif))
         TIFFUnmapFileContents(tif, tif->tif_base, tif->tif_size);
     /* Clean up custom fields */
     if (tif->tif_nfields > 0)
     {
         size_t  i;
         for (i = 0; i < tif->tif_nfields; i++)
         {
         TIFFFieldInfo *fld = tif->tif_fieldinfo[i];
         if (fld->field_bit == FIELD_CUSTOM &&
             strncmp("Tag ", fld->field_name, 4) == 0)
         {
             _TIFFfree(fld->field_name);
             _TIFFfree(fld);
         }
         }
         _TIFFfree(tif->tif_fieldinfo);
     }
     _TIFFfree(tif);
 }
void TIFFClose (TIFF * tif)
Close a previously opened TIFF file.
TIFFClose closes a file that was previously opened with TIFFOpen(). Any buffered data are flushed to the file, including the contents of the current directory (if modified); and all resources are reclaimed.
Parameters
tif A TIFF pointer.
Definition at line 111 of file tif_close.c.
References tiff::tif_clientdata, tiff::tif_closeproc, and TIFFCleanup().
Referenced by TIFFReaderInternal::Clean(), and rcWindow::tiff().
 {
     TIFFCloseProc closeproc = tif->tif_closeproc;
     thandle_t fd = tif->tif_clientdata;
     TIFFCleanup(tif);
     (void) (*closeproc)(fd);
 }