Visible: src/util/code/tif_aux.c File Reference
tif_aux.c File Reference
#include "tiffiop.h"
#include "tif_predict.h"
#include <math.h>
Functions
tdata_t _TIFFCheckMalloc (TIFF *tif, size_t nmemb, size_t elem_size, const char *what)
static int TIFFDefaultTransferFunction (TIFFDirectory *td)
int TIFFVGetFieldDefaulted (TIFF *tif, ttag_t tag, va_list ap)
int TIFFGetFieldDefaulted (TIFF *tif, ttag_t tag,...)
Function Documentation
tdata_t _TIFFCheckMalloc (TIFF * tif, size_t nmemb, size_t elem_size, const char * what)
Definition at line 37 of file tif_aux.c.
References _TIFFmalloc(), NULL, tiff::tif_clientdata, tiff::tif_name, and TIFFErrorExt().
Referenced by ChopUpSingleUncompressedStrip(), EstimateStripByteCounts(), TIFFFetchNormalTag(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFFetchRationalArray(), TIFFFetchRefBlackWhite(), TIFFFetchStripThing(), TIFFReadCustomDirectory(), and TIFFReadDirectory().
 {
     tdata_t cp = NULL;
     tsize_t bytes = nmemb * elem_size;
     /*
      * XXX: Check for integer overflow.
      */
     if (nmemb && elem_size && bytes / elem_size == nmemb)
         cp = _TIFFmalloc(bytes);
     if (cp == NULL)
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "No space %s", what);
     return (cp);
 }
static int TIFFDefaultTransferFunction (TIFFDirectory * td) static
Definition at line 55 of file tif_aux.c.
References _TIFFfree(), _TIFFmalloc(), _TIFFmemcpy(), pow(), TIFFDirectory::td_bitspersample, TIFFDirectory::td_extrasamples, TIFFDirectory::td_samplesperpixel, and TIFFDirectory::td_transferfunction.
Referenced by TIFFVGetFieldDefaulted().
 {
     uint16 **tf = td->td_transferfunction;
     tsize_t i, n, nbytes;
     tf[0] = tf[1] = tf[2] = 0;
     if (td->td_bitspersample >= sizeof(tsize_t) * 8 - 2)
         return 0;
     n = 1<<td->td_bitspersample;
     nbytes = n * sizeof (uint16);
     if (!(tf[0] = (uint16 *)_TIFFmalloc(nbytes)))
         return 0;
     tf[0][0] = 0;
     for (i = 1; i < n; i++) {
         double t = (double)i/((double) n-1.);
         tf[0][i] = (uint16)floor(65535.*pow(t, 2.2) + .5);
     }
     if (td->td_samplesperpixel - td->td_extrasamples > 1) {
         if (!(tf[1] = (uint16 *)_TIFFmalloc(nbytes)))
             goto bad;
         _TIFFmemcpy(tf[1], tf[0], nbytes);
         if (!(tf[2] = (uint16 *)_TIFFmalloc(nbytes)))
             goto bad;
         _TIFFmemcpy(tf[2], tf[0], nbytes);
     }
     return 1;
 bad:
     if (tf[0])
         _TIFFfree(tf[0]);
     if (tf[1])
         _TIFFfree(tf[1]);
     if (tf[2])
         _TIFFfree(tf[2]);
     tf[0] = tf[1] = tf[2] = 0;
     return 0;
 }
int TIFFGetFieldDefaulted (TIFF * tif, ttag_t tag, ...)
Definition at line 256 of file tif_aux.c.
References TIFFVGetFieldDefaulted().
Referenced by gtStripContig(), gtStripSeparate(), initCIELabConversion(), TIFFReaderInternal::Initialize(), initYCbCrConversion(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), TIFFRGBAImageBegin(), and TIFFRGBAImageOK().
 {
     int ok;
     va_list ap;
     va_start(ap, tag);
     ok =  TIFFVGetFieldDefaulted(tif, tag, ap);
     va_end(ap);
     return (ok);
 }
int TIFFVGetFieldDefaulted (TIFF * tif, ttag_t tag, va_list ap)
Definition at line 104 of file tif_aux.c.
References D50_X0, D50_Y0, D50_Z0, EXTRASAMPLE_ASSOCALPHA, INKSET_CMYK, PHOTOMETRIC_YCBCR, TIFFPredictorState::predictor, TIFFDirectory::td_bitspersample, TIFFDirectory::td_extrasamples, TIFFDirectory::td_fillorder, TIFFDirectory::td_imagedepth, TIFFDirectory::td_maxsamplevalue, TIFFDirectory::td_minsamplevalue, TIFFDirectory::td_orientation, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, TIFFDirectory::td_resolutionunit, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_sampleformat, TIFFDirectory::td_sampleinfo, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_subfiletype, TIFFDirectory::td_threshholding, TIFFDirectory::td_tiledepth, TIFFDirectory::td_transferfunction, TIFFDirectory::td_ycbcrpositioning, TIFFDirectory::td_ycbcrsubsampling, tiff::tif_clientdata, tiff::tif_data, tiff::tif_dir, tiff::tif_name, TIFFDefaultTransferFunction(), TIFFErrorExt(), TIFFTAG_BITSPERSAMPLE, TIFFTAG_DATATYPE, TIFFTAG_DOTRANGE, TIFFTAG_EXTRASAMPLES, TIFFTAG_FILLORDER, TIFFTAG_IMAGEDEPTH, TIFFTAG_INKSET, TIFFTAG_MATTEING, TIFFTAG_MAXSAMPLEVALUE, TIFFTAG_MINSAMPLEVALUE, TIFFTAG_NUMBEROFINKS, TIFFTAG_ORIENTATION, TIFFTAG_PLANARCONFIG, TIFFTAG_PREDICTOR, TIFFTAG_REFERENCEBLACKWHITE, TIFFTAG_RESOLUTIONUNIT, TIFFTAG_ROWSPERSTRIP, TIFFTAG_SAMPLEFORMAT, TIFFTAG_SAMPLESPERPIXEL, TIFFTAG_SUBFILETYPE, TIFFTAG_THRESHHOLDING, TIFFTAG_TILEDEPTH, TIFFTAG_TRANSFERFUNCTION, TIFFTAG_WHITEPOINT, TIFFTAG_YCBCRCOEFFICIENTS, TIFFTAG_YCBCRPOSITIONING, TIFFTAG_YCBCRSUBSAMPLING, and TIFFVGetField().
Referenced by TIFFGetFieldDefaulted().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (TIFFVGetField(tif, tag, ap))
         return (1);
     switch (tag) {
     case TIFFTAG_SUBFILETYPE:
         *va_arg(ap, uint32 *) = td->td_subfiletype;
         return (1);
     case TIFFTAG_BITSPERSAMPLE:
         *va_arg(ap, uint16 *) = td->td_bitspersample;
         return (1);
     case TIFFTAG_THRESHHOLDING:
         *va_arg(ap, uint16 *) = td->td_threshholding;
         return (1);
     case TIFFTAG_FILLORDER:
         *va_arg(ap, uint16 *) = td->td_fillorder;
         return (1);
     case TIFFTAG_ORIENTATION:
         *va_arg(ap, uint16 *) = td->td_orientation;
         return (1);
     case TIFFTAG_SAMPLESPERPIXEL:
         *va_arg(ap, uint16 *) = td->td_samplesperpixel;
         return (1);
     case TIFFTAG_ROWSPERSTRIP:
         *va_arg(ap, uint32 *) = td->td_rowsperstrip;
         return (1);
     case TIFFTAG_MINSAMPLEVALUE:
         *va_arg(ap, uint16 *) = td->td_minsamplevalue;
         return (1);
     case TIFFTAG_MAXSAMPLEVALUE:
         *va_arg(ap, uint16 *) = td->td_maxsamplevalue;
         return (1);
     case TIFFTAG_PLANARCONFIG:
         *va_arg(ap, uint16 *) = td->td_planarconfig;
         return (1);
     case TIFFTAG_RESOLUTIONUNIT:
         *va_arg(ap, uint16 *) = td->td_resolutionunit;
         return (1);
     case TIFFTAG_PREDICTOR:
                 {
             TIFFPredictorState* sp = (TIFFPredictorState*) tif->tif_data;
             *va_arg(ap, uint16*) = (uint16) sp->predictor;
             return 1;
                 }
     case TIFFTAG_DOTRANGE:
         *va_arg(ap, uint16 *) = 0;
         *va_arg(ap, uint16 *) = (1<<td->td_bitspersample)-1;
         return (1);
     case TIFFTAG_INKSET:
         *va_arg(ap, uint16 *) = INKSET_CMYK;
         return 1;
     case TIFFTAG_NUMBEROFINKS:
         *va_arg(ap, uint16 *) = 4;
         return (1);
     case TIFFTAG_EXTRASAMPLES:
         *va_arg(ap, uint16 *) = td->td_extrasamples;
         *va_arg(ap, uint16 **) = td->td_sampleinfo;
         return (1);
     case TIFFTAG_MATTEING:
         *va_arg(ap, uint16 *) =
             (td->td_extrasamples == 1 &&
              td->td_sampleinfo[0] == EXTRASAMPLE_ASSOCALPHA);
         return (1);
     case TIFFTAG_TILEDEPTH:
         *va_arg(ap, uint32 *) = td->td_tiledepth;
         return (1);
     case TIFFTAG_DATATYPE:
         *va_arg(ap, uint16 *) = td->td_sampleformat-1;
         return (1);
     case TIFFTAG_SAMPLEFORMAT:
         *va_arg(ap, uint16 *) = td->td_sampleformat;
                 return(1);
     case TIFFTAG_IMAGEDEPTH:
         *va_arg(ap, uint32 *) = td->td_imagedepth;
         return (1);
     case TIFFTAG_YCBCRCOEFFICIENTS:
         {
             /* defaults are from CCIR Recommendation 601-1 */
             float ycbcrcoeffs[] = { 0.299f, 0.587f, 0.114f };
             *va_arg(ap, float **) = ycbcrcoeffs;
             return 1;
         }
     case TIFFTAG_YCBCRSUBSAMPLING:
         *va_arg(ap, uint16 *) = td->td_ycbcrsubsampling[0];
         *va_arg(ap, uint16 *) = td->td_ycbcrsubsampling[1];
         return (1);
     case TIFFTAG_YCBCRPOSITIONING:
         *va_arg(ap, uint16 *) = td->td_ycbcrpositioning;
         return (1);
     case TIFFTAG_WHITEPOINT:
         {
             static float whitepoint[2];
             /* TIFF 6.0 specification tells that it is no default
                value for the WhitePoint, but AdobePhotoshop TIFF
                Technical Note tells that it should be CIE D50. */
             whitepoint[0] = D50_X0 / (D50_X0 + D50_Y0 + D50_Z0);
             whitepoint[1] = D50_Y0 / (D50_X0 + D50_Y0 + D50_Z0);
             *va_arg(ap, float **) = whitepoint;
             return 1;
         }
     case TIFFTAG_TRANSFERFUNCTION:
         if (!td->td_transferfunction[0] &&
             !TIFFDefaultTransferFunction(td)) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "No space for \"TransferFunction\" tag");
             return (0);
         }
         *va_arg(ap, uint16 **) = td->td_transferfunction[0];
         if (td->td_samplesperpixel - td->td_extrasamples > 1) {
             *va_arg(ap, uint16 **) = td->td_transferfunction[1];
             *va_arg(ap, uint16 **) = td->td_transferfunction[2];
         }
         return (1);
     case TIFFTAG_REFERENCEBLACKWHITE:
         {
             int i;
             static float ycbcr_refblackwhite[] =
             { 0.0F, 255.0F, 128.0F, 255.0F, 128.0F, 255.0F };
             static float rgb_refblackwhite[6];
             for (i = 0; i < 3; i++) {
                 rgb_refblackwhite[2 * i + 0] = 0.0F;
                 rgb_refblackwhite[2 * i + 1] =
                     (float)((1L<<td->td_bitspersample)-1L);
             }
             if (td->td_photometric == PHOTOMETRIC_YCBCR) {
                 /*
                  * YCbCr (Class Y) images must have the
                  * ReferenceBlackWhite tag set. Fix the
                  * broken images, which lacks that tag.
                  */
                 *va_arg(ap, float **) = ycbcr_refblackwhite;
             } else {
                 /*
                  * Assume RGB (Class R)
                  */
                 *va_arg(ap, float **) = rgb_refblackwhite;
             }
             return 1;
         }
     }
     return 0;
 }