Visible: include/util/tif_predict.h File Reference
tif_predict.h File Reference
Classes
struct TIFFPredictorState
Functions
int TIFFPredictorInit (TIFF *)
Function Documentation
int TIFFPredictorInit (TIFF *)
Definition at line 569 of file tif_predict.c.
References _TIFFMergeFieldInfo(), N, NULL, TIFFPredictorState::pfunc, TIFFPredictorState::predictor, PredictorPrintDir(), PredictorSetupDecode(), PredictorSetupEncode(), PredictorState, PredictorVGetField(), PredictorVSetField(), TIFFPredictorState::printdir, TIFFTagMethods::printdir, TIFFPredictorState::setupdecode, TIFFPredictorState::setupencode, tiff::tif_setupdecode, tiff::tif_setupencode, tiff::tif_tagmethods, TIFFTagMethods::vgetfield, TIFFPredictorState::vgetparent, TIFFTagMethods::vsetfield, and TIFFPredictorState::vsetparent.
 {
     TIFFPredictorState* sp = PredictorState(tif);
     /*
      * Merge codec-specific tag information and
      * override parent get/set field methods.
      */
     _TIFFMergeFieldInfo(tif, predictFieldInfo, N(predictFieldInfo));
     sp->vgetparent = tif->tif_tagmethods.vgetfield;
     tif->tif_tagmethods.vgetfield =
             PredictorVGetField;/* hook for predictor tag */
     sp->vsetparent = tif->tif_tagmethods.vsetfield;
     tif->tif_tagmethods.vsetfield =
             PredictorVSetField;/* hook for predictor tag */
     sp->printdir = tif->tif_tagmethods.printdir;
     tif->tif_tagmethods.printdir =
             PredictorPrintDir;  /* hook for predictor tag */
     sp->setupdecode = tif->tif_setupdecode;
     tif->tif_setupdecode = PredictorSetupDecode;
     sp->setupencode = tif->tif_setupencode;
     tif->tif_setupencode = PredictorSetupEncode;
     sp->predictor = 1;          /* default value */
     sp->pfunc = NULL;           /* no predictor routine */
     return 1;
 }