Visible: src/util/code/tif_apple.c File Reference
tif_apple.c File Reference
#include <Carbon/Carbon.h>
#include "tiffiop.h"
Functions
static tsize_t _tiffReadProc (thandle_t fd, tdata_t buf, tsize_t size)
static tsize_t _tiffWriteProc (thandle_t fd, tdata_t buf, tsize_t size)
static toff_t _tiffSeekProc (thandle_t fd, toff_t off, int whence)
static int _tiffMapProc (thandle_t fd, tdata_t *pbase, toff_t *psize)
static void _tiffUnmapProc (thandle_t fd, tdata_t base, toff_t size)
static int _tiffCloseProc (thandle_t fd)
static toff_t _tiffSizeProc (thandle_t fd)
TIFF * TIFFFdOpen (int fd, const char *name, const char *mode)
static void ourc2pstr (char *inString)
TIFF * TIFFOpen (const char *name, const char *mode)
void _TIFFmemset (tdata_t p, int v, tsize_t c)
void _TIFFmemcpy (tdata_t d, const tdata_t s, tsize_t c)
int _TIFFmemcmp (const tdata_t p1, const tdata_t p2, tsize_t c)
tdata_t _TIFFmalloc (tsize_t s)
void _TIFFfree (tdata_t p)
tdata_t _TIFFrealloc (tdata_t p, tsize_t s)
static void appleWarningHandler (const char *module, const char *fmt, va_list ap)
static void appleErrorHandler (const char *module, const char *fmt, va_list ap)
Variables
TIFFErrorHandler _TIFFwarningHandler = appleWarningHandler
TIFFErrorHandler _TIFFerrorHandler = appleErrorHandler
Function Documentation
static int _tiffCloseProc (thandle_t fd) static
Definition at line 113 of file tif_apple.c.
Referenced by TIFFFdOpen().
 {
     return (FSClose((short) fd));
 }
void _TIFFfree (tdata_t p)
Definition at line 233 of file tif_apple.c.
Referenced by _TIFFCreateAnonFieldInfo(), _TIFFSetupFieldInfo(), _TIFFVSetField(), _TIFFWriteDirectory(), ChopUpSingleUncompressedStrip(), EstimateStripByteCounts(), fpAcc(), fpDiff(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), initCIELabConversion(), TIFFReaderInternal::Open(), setByteArray(), setupMap(), rcWindow::tiff(), TIFFCleanup(), TIFFDefaultTransferFunction(), TIFFFetchNormalTag(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFFetchRationalArray(), TIFFFetchRefBlackWhite(), TIFFFetchStripThing(), TIFFFillStrip(), TIFFFillTile(), TIFFFreeDirectory(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), TIFFPrintDirectory(), TIFFReadBufferSetup(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFRGBAImageEnd(), TIFFUnlinkDirectory(), TIFFUnRegisterCODEC(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), and TIFFWriteRationalArray().
 {
     DisposePtr(p);
 }
tdata_t _TIFFmalloc (tsize_t s)
Definition at line 227 of file tif_apple.c.
Referenced by _TIFFCheckMalloc(), _TIFFCreateAnonFieldInfo(), _TIFFMergeFieldInfo(), _TIFFVSetField(), _TIFFWriteDirectory(), fpAcc(), fpDiff(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), initCIELabConversion(), initYCbCrConversion(), makebwmap(), makecmap(), TIFFReaderInternal::Open(), setByteArray(), setupMap(), rcWindow::tiff(), TIFFClientOpen(), TIFFDefaultTransferFunction(), TIFFPrintDirectory(), TIFFReadBufferSetup(), TIFFRegisterCODEC(), TIFFRGBAImageBegin(), TIFFSetClientInfo(), TIFFSetupStrips(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), and TIFFWriteRationalArray().
 {
     return (NewPtr((size_t) s));
 }
static int _tiffMapProc (thandle_t fd, tdata_t * pbase, toff_t * psize) static
Definition at line 102 of file tif_apple.c.
Referenced by TIFFFdOpen().
 {
     return (0);
 }
int _TIFFmemcmp (const tdata_t p1, const tdata_t p2, tsize_t c)
Definition at line 221 of file tif_apple.c.
Referenced by TIFFWriteTransferFunction().
 {
     return (memcmp(p1, p2, (size_t) c));
 }
void _TIFFmemcpy (tdata_t d, const tdata_t s, tsize_t c)
Definition at line 215 of file tif_apple.c.
Referenced by _TIFFVSetField(), _TIFFWriteDirectory(), DumpModeDecode(), DumpModeEncode(), fpAcc(), fpDiff(), setByteArray(), TIFFAdvanceDirectory(), TIFFCIELabToRGBInit(), TIFFDefaultTransferFunction(), TIFFFetchData(), TIFFFetchFloat(), TIFFFetchString(), TIFFGetConfiguredCODECs(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFReadRawStrip1(), TIFFReadRawTile1(), TIFFRGBAImageBegin(), and TIFFWriteByteArray().
 {
     memcpy(d, s, (size_t) c);
 }
void _TIFFmemset (tdata_t p, int v, tsize_t c)
Definition at line 209 of file tif_apple.c.
Referenced by _TIFFCreateAnonFieldInfo(), _TIFFVSetField(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), TIFFClientOpen(), TIFFDefaultDirectory(), TIFFFetchStripThing(), TIFFFreeDirectory(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), TIFFReadRGBATile(), TIFFSetupStrips(), and TIFFYCbCrToRGBInit().
 {
     memset(p, v, (size_t) c);
 }
static tsize_t _tiffReadProc (thandle_t fd, tdata_t buf, tsize_t size) static
Definition at line 55 of file tif_apple.c.
Referenced by TIFFFdOpen().
 {
     return (FSRead((short) fd, (long*) &size, (char*) buf) == noErr ?
         size : (tsize_t) -1);
 }
tdata_t _TIFFrealloc (tdata_t p, tsize_t s)
Definition at line 239 of file tif_apple.c.
Referenced by _TIFFMergeFieldInfo(), _TIFFVSetField(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), and TIFFReadDirectory().
 {
     Ptr n = p;
     SetPtrSize(p, (size_t) s);
     if (MemError() && (n = NewPtr((size_t) s)) != NULL) {
         BlockMove(p, n, GetPtrSize(p));
         DisposePtr(p);
     }
     return ((tdata_t) n);
 }
static toff_t _tiffSeekProc (thandle_t fd, toff_t off, int whence) static
Definition at line 69 of file tif_apple.c.
Referenced by TIFFFdOpen().
 {
     long fpos, size;
     if (GetEOF((short) fd, &size) != noErr)
         return EOF;
     (void) GetFPos((short) fd, &fpos);
     switch (whence) {
     case SEEK_CUR:
         if (off + fpos > size)
             SetEOF((short) fd, off + fpos);
         if (SetFPos((short) fd, fsFromMark, off) != noErr)
             return EOF;
         break;
     case SEEK_END:
         if (off > 0)
             SetEOF((short) fd, off + size);
         if (SetFPos((short) fd, fsFromStart, off + size) != noErr)
             return EOF;
         break;
     case SEEK_SET:
         if (off > size)
             SetEOF((short) fd, off);
         if (SetFPos((short) fd, fsFromStart, off) != noErr)
             return EOF;
         break;
     }
     return (toff_t)(GetFPos((short) fd, &fpos) == noErr ? fpos : EOF);
 }
static toff_t _tiffSizeProc (thandle_t fd) static
Definition at line 119 of file tif_apple.c.
References TIFFErrorExt().
Referenced by TIFFFdOpen().
 {
     long size;
     if (GetEOF((short) fd, &size) != noErr) {
         TIFFErrorExt(fd, "_tiffSizeProc", "%s: Cannot get file size");
         return (-1L);
     }
     return ((toff_t) size);
 }
static void _tiffUnmapProc (thandle_t fd, tdata_t base, toff_t size) static
Definition at line 108 of file tif_apple.c.
Referenced by TIFFFdOpen().
 {
 }
static tsize_t _tiffWriteProc (thandle_t fd, tdata_t buf, tsize_t size) static
Definition at line 62 of file tif_apple.c.
Referenced by TIFFFdOpen().
 {
     return (FSWrite((short) fd, (long*) &size, (char*) buf) == noErr ?
         size : (tsize_t) -1);
 }
static void appleErrorHandler (const char * module, const char * fmt, va_list ap) static
Definition at line 263 of file tif_apple.c.
References NULL.
 {
     if (module != NULL)
         fprintf(stderr, "%s: ", module);
     vfprintf(stderr, fmt, ap);
     fprintf(stderr, ".\n");
 }
static void appleWarningHandler (const char * module, const char * fmt, va_list ap) static
Definition at line 252 of file tif_apple.c.
References NULL.
 {
     if (module != NULL)
         fprintf(stderr, "%s: ", module);
     fprintf(stderr, "Warning, ");
     vfprintf(stderr, fmt, ap);
     fprintf(stderr, ".\n");
 }
static void ourc2pstr (char * inString) static
Definition at line 146 of file tif_apple.c.
Referenced by TIFFOpen().
 {
     int sLen = strlen( inString );
     BlockMoveData( inString, &inString[1], sLen );
     inString[0] = sLen;
 }
TIFF* TIFFFdOpen (int fd, const char * name, const char * mode)
Definition at line 134 of file tif_apple.c.
Referenced by TIFFOpen().
 {
     TIFF* tif;
     tif = TIFFClientOpen(name, mode, (thandle_t) fd,
         _tiffReadProc, _tiffWriteProc, _tiffSeekProc, _tiffCloseProc,
         _tiffSizeProc, _tiffMapProc, _tiffUnmapProc);
     if (tif)
         tif->tif_fd = fd;
     return (tif);
 }
TIFF* TIFFOpen (const char * name, const char * mode)
Definition at line 157 of file tif_apple.c.
Referenced by TIFFReaderInternal::Open(), and rcWindow::tiff().
 {
     static const char module[] = "TIFFOpen";
     Str255 pname;
     FInfo finfo;
     short fref;
     OSErr err;
     FSSpec  fSpec;
     strcpy((char*) pname, name);
     ourc2pstr((char*) pname);
     err = FSMakeFSSpec( 0, 0, pname, &fSpec );
     switch (_TIFFgetMode(mode, module)) {
     default:
         return ((TIFF*) 0);
     case O_RDWR | O_CREAT | O_TRUNC:
         if (FSpGetFInfo(&fSpec, &finfo) == noErr)
             FSpDelete(&fSpec);
         /* fall through */
     case O_RDWR | O_CREAT:
         if ((err = FSpGetFInfo(&fSpec, &finfo)) == fnfErr) {
             if (FSpCreate(&fSpec, '    ', 'TIFF', smSystemScript) != noErr)
                 goto badCreate;
             if (FSpOpenDF(&fSpec, fsRdWrPerm, &fref) != noErr)
                 goto badOpen;
         } else if (err == noErr) {
             if (FSpOpenDF(&fSpec, fsRdWrPerm, &fref) != noErr)
                 goto badOpen;
         } else
             goto badOpen;
         break;
     case O_RDONLY:
         if (FSpOpenDF(&fSpec, fsRdPerm, &fref) != noErr)
             goto badOpen;
         break;
     case O_RDWR:
         if (FSpOpenDF(&fSpec, fsRdWrPerm, &fref) != noErr)
             goto badOpen;
         break;
     }
     return (TIFFFdOpen((int) fref, name, mode));
 badCreate:
     TIFFErrorExt(0, module, "%s: Cannot create", name);
     return ((TIFF*) 0);
 badOpen:
     TIFFErrorExt(0, module, "%s: Cannot open", name);
     return ((TIFF*) 0);
 }
Variable Documentation
TIFFErrorHandler _TIFFerrorHandler = appleErrorHandler
Definition at line 270 of file tif_apple.c.
Referenced by TIFFError(), TIFFErrorExt(), and TIFFSetErrorHandler().
TIFFErrorHandler _TIFFwarningHandler = appleWarningHandler
Definition at line 260 of file tif_apple.c.
Referenced by TIFFSetWarningHandler(), TIFFWarning(), and TIFFWarningExt().