Visible: src/util/code/tif_warning.c File Reference
tif_warning.c File Reference
#include "tiffiop.h"
Functions
TIFFErrorHandler TIFFSetWarningHandler (TIFFErrorHandler handler)
TIFFErrorHandlerExt TIFFSetWarningHandlerExt (TIFFErrorHandlerExt handler)
void TIFFWarning (const char *module, const char *fmt,...)
void TIFFWarningExt (thandle_t fd, const char *module, const char *fmt,...)
Variables
TIFFErrorHandlerExt _TIFFwarningHandlerExt = NULL
Function Documentation
TIFFErrorHandler TIFFSetWarningHandler (TIFFErrorHandler handler)
Definition at line 35 of file tif_warning.c.
References _TIFFwarningHandler.
 {
     TIFFErrorHandler prev = _TIFFwarningHandler;
     _TIFFwarningHandler = handler;
     return (prev);
 }
TIFFErrorHandlerExt TIFFSetWarningHandlerExt (TIFFErrorHandlerExt handler)
Definition at line 43 of file tif_warning.c.
References _TIFFwarningHandlerExt.
 {
     TIFFErrorHandlerExt prev = _TIFFwarningHandlerExt;
     _TIFFwarningHandlerExt = handler;
     return (prev);
 }
void TIFFWarning (const char * module, const char * fmt, ...)
Definition at line 51 of file tif_warning.c.
References _TIFFwarningHandler, and _TIFFwarningHandlerExt.
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFwarningHandler)
         (*_TIFFwarningHandler)(module, fmt, ap);
     if (_TIFFwarningHandlerExt)
         (*_TIFFwarningHandlerExt)(0, module, fmt, ap);
     va_end(ap);
 }
void TIFFWarningExt (thandle_t fd, const char * module, const char * fmt, ...)
Definition at line 63 of file tif_warning.c.
References _TIFFwarningHandler, and _TIFFwarningHandlerExt.
Referenced by _TIFFVSetField(), buildMap(), CheckDirCount(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFWriteRationalArray().
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFwarningHandler)
         (*_TIFFwarningHandler)(module, fmt, ap);
     if (_TIFFwarningHandlerExt)
         (*_TIFFwarningHandlerExt)(fd, module, fmt, ap);
     va_end(ap);
 }
Variable Documentation
TIFFErrorHandlerExt _TIFFwarningHandlerExt = NULL
Definition at line 32 of file tif_warning.c.
Referenced by TIFFSetWarningHandlerExt(), TIFFWarning(), and TIFFWarningExt().