Visible: src/util/code/tif_strip.c File Reference
tif_strip.c File Reference
#include "tiffiop.h"
Functions
static uint32 summarize (TIFF *tif, size_t summand1, size_t summand2, const char *where)
static uint32 multiply (TIFF *tif, size_t nmemb, size_t elem_size, const char *where)
tstrip_t TIFFComputeStrip (TIFF *tif, uint32 row, tsample_t sample)
tstrip_t TIFFNumberOfStrips (TIFF *tif)
tsize_t TIFFVStripSize (TIFF *tif, uint32 nrows)
tsize_t TIFFRawStripSize (TIFF *tif, tstrip_t strip)
tsize_t TIFFStripSize (TIFF *tif)
uint32 TIFFDefaultStripSize (TIFF *tif, uint32 request)
uint32 _TIFFDefaultStripSize (TIFF *tif, uint32 s)
tsize_t TIFFScanlineSize (TIFF *tif)
tsize_t TIFFRasterScanlineSize (TIFF *tif)
Function Documentation
uint32 _TIFFDefaultStripSize (TIFF * tif, uint32 s)
Definition at line 203 of file tif_strip.c.
References TIFFScanlineSize().
Referenced by _TIFFSetDefaultCompressionState().
 {
     if ((int32) s < 1) {
         /*
          * If RowsPerStrip is unspecified, try to break the
          * image up into strips that are approximately 8Kbytes.
          */
         tsize_t scanline = TIFFScanlineSize(tif);
         s = (uint32)(8*1024) / (scanline == 0 ? 1 : scanline);
         if (s == 0)     /* very wide images */
             s = 1;
     }
     return (s);
 }
static uint32 multiply (TIFF * tif, size_t nmemb, size_t elem_size, const char * where) static
Definition at line 52 of file tif_strip.c.
References tiff::tif_clientdata, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFNumberOfStrips(), TIFFRasterScanlineSize(), TIFFScanlineSize(), and TIFFVStripSize().
 {
     uint32  bytes = nmemb * elem_size;
     if (elem_size && bytes / elem_size != nmemb) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Integer overflow in %s", where);
         bytes = 0;
     }
     return (bytes);
 }
static uint32 summarize (TIFF * tif, size_t summand1, size_t summand2, const char * where) static
Definition at line 35 of file tif_strip.c.
References tiff::tif_clientdata, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFVStripSize().
 {
     /*
      * XXX: We are using casting to uint32 here, bacause sizeof(size_t)
      * may be larger than sizeof(uint32) on 64-bit architectures.
      */
     uint32  bytes = summand1 + summand2;
     if (bytes - summand1 != summand2) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Integer overflow in %s", where);
         bytes = 0;
     }
     return (bytes);
 }
tstrip_t TIFFComputeStrip (TIFF * tif, uint32 row, tsample_t sample)
Definition at line 68 of file tif_strip.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, and TIFFErrorExt().
Referenced by gtStripContig(), and gtStripSeparate().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tstrip_t strip;
     strip = row / td->td_rowsperstrip;
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
         if (sample >= td->td_samplesperpixel) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
                 "%lu: Sample out of range, max %lu",
                 (unsigned long) sample, (unsigned long) td->td_samplesperpixel);
             return ((tstrip_t) 0);
         }
         strip += sample*td->td_stripsperimage;
     }
     return (strip);
 }
uint32 TIFFDefaultStripSize (TIFF * tif, uint32 request)
Definition at line 197 of file tif_strip.c.
References tiff::tif_defstripsize.
Referenced by rcWindow::tiff().
 {
     return (*tif->tif_defstripsize)(tif, request);
 }
tstrip_t TIFFNumberOfStrips (TIFF * tif)
Definition at line 90 of file tif_strip.c.
References multiply(), PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagelength, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, tiff::tif_dir, and TIFFhowmany.
Referenced by TIFFReadDirectory(), and TIFFSetupStrips().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tstrip_t nstrips;
     nstrips = (td->td_rowsperstrip == (uint32) -1 ? 1 :
          TIFFhowmany(td->td_imagelength, td->td_rowsperstrip));
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
         nstrips = multiply(tif, nstrips, td->td_samplesperpixel,
                    "TIFFNumberOfStrips");
     return (nstrips);
 }
tsize_t TIFFRasterScanlineSize (TIFF * tif)
Definition at line 245 of file tif_strip.c.
References multiply(), PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_dir, and TIFFhowmany8.
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t scanline;
     scanline = multiply (tif, td->td_bitspersample, td->td_imagewidth,
                  "TIFFRasterScanlineSize");
     if (td->td_planarconfig == PLANARCONFIG_CONTIG) {
         scanline = multiply (tif, scanline, td->td_samplesperpixel,
                      "TIFFRasterScanlineSize");
         return ((tsize_t) TIFFhowmany8(scanline));
     } else
         return ((tsize_t) multiply (tif, TIFFhowmany8(scanline),
                         td->td_samplesperpixel,
                         "TIFFRasterScanlineSize"));
 }
tsize_t TIFFRawStripSize (TIFF * tif, tstrip_t strip)
Definition at line 157 of file tif_strip.c.
References TIFFDirectory::td_stripbytecount, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, and TIFFErrorExt().
 {
     TIFFDirectory* td = &tif->tif_dir;
     tsize_t bytecount = td->td_stripbytecount[strip];
     if (bytecount <= 0) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
               "%lu: Invalid strip byte count, strip %lu",
               (unsigned long) bytecount, (unsigned long) strip);
         bytecount = (tsize_t) -1;
     }
     return bytecount;
 }
tsize_t TIFFScanlineSize (TIFF * tif)
Definition at line 225 of file tif_strip.c.
References multiply(), PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_dir, and TIFFhowmany8.
Referenced by _TIFFDefaultStripSize(), EstimateStripByteCounts(), gtStripContig(), gtStripSeparate(), PredictorSetup(), TIFFReadDirectory(), TIFFVStripSize(), and TIFFWriteCheck().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t scanline;
     scanline = multiply (tif, td->td_bitspersample, td->td_imagewidth,
                  "TIFFScanlineSize");
     if (td->td_planarconfig == PLANARCONFIG_CONTIG)
         scanline = multiply (tif, scanline, td->td_samplesperpixel,
                      "TIFFScanlineSize");
     return ((tsize_t) TIFFhowmany8(scanline));
 }
tsize_t TIFFStripSize (TIFF * tif)
Definition at line 181 of file tif_strip.c.
References TIFFDirectory::td_imagelength, TIFFDirectory::td_rowsperstrip, tiff::tif_dir, and TIFFVStripSize().
Referenced by gtStripContig(), gtStripSeparate(), TIFFReadDirectory(), and TIFFWriteBufferSetup().
 {
     TIFFDirectory* td = &tif->tif_dir;
     uint32 rps = td->td_rowsperstrip;
     if (rps > td->td_imagelength)
         rps = td->td_imagelength;
     return (TIFFVStripSize(tif, rps));
 }
tsize_t TIFFVStripSize (TIFF * tif, uint32 nrows)
Definition at line 107 of file tif_strip.c.
References isUpSampled, multiply(), PHOTOMETRIC_YCBCR, PLANARCONFIG_CONTIG, summarize(), TIFFDirectory::td_bitspersample, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), TIFFGetField(), TIFFhowmany8, TIFFroundup, TIFFScanlineSize(), and TIFFTAG_YCBCRSUBSAMPLING.
Referenced by TIFFReadEncodedStrip(), and TIFFStripSize().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (nrows == (uint32) -1)
         nrows = td->td_imagelength;
     if (td->td_planarconfig == PLANARCONFIG_CONTIG &&
         td->td_photometric == PHOTOMETRIC_YCBCR &&
         !isUpSampled(tif)) {
         /*
          * Packed YCbCr data contain one Cb+Cr for every
          * HorizontalSampling*VerticalSampling Y values.
          * Must also roundup width and height when calculating
          * since images that are not a multiple of the
          * horizontal/vertical subsampling area include
          * YCbCr data for the extended image.
          */
                 uint16 ycbcrsubsampling[2];
                 tsize_t w, scanline, samplingarea;
                 TIFFGetField( tif, TIFFTAG_YCBCRSUBSAMPLING,
                               ycbcrsubsampling + 0,
                               ycbcrsubsampling + 1 );
         samplingarea = ycbcrsubsampling[0]*ycbcrsubsampling[1];
         if (samplingarea == 0) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Invalid YCbCr subsampling");
             return 0;
         }
         w = TIFFroundup(td->td_imagewidth, ycbcrsubsampling[0]);
         scanline = TIFFhowmany8(multiply(tif, w, td->td_bitspersample,
                          "TIFFVStripSize"));
         nrows = TIFFroundup(nrows, ycbcrsubsampling[1]);
         /* NB: don't need TIFFhowmany here 'cuz everything is rounded */
         scanline = multiply(tif, nrows, scanline, "TIFFVStripSize");
         return ((tsize_t)
             summarize(tif, scanline,
                   multiply(tif, 2, scanline / samplingarea,
                        "TIFFVStripSize"), "TIFFVStripSize"));
     } else
         return ((tsize_t) multiply(tif, nrows, TIFFScanlineSize(tif),
                        "TIFFVStripSize"));
 }