Visible: src/util/code/tif_codec.c File Reference
tif_codec.c File Reference
#include "tiffiop.h"
Macros
#define TIFFInitLZW NotConfigured
#define TIFFInitPackBits NotConfigured
#define TIFFInitThunderScan NotConfigured
#define TIFFInitNeXT NotConfigured
#define TIFFInitJPEG NotConfigured
#define TIFFInitOJPEG NotConfigured
#define TIFFInitCCITTRLE NotConfigured
#define TIFFInitCCITTRLEW NotConfigured
#define TIFFInitCCITTFax3 NotConfigured
#define TIFFInitCCITTFax4 NotConfigured
#define TIFFInitJBIG NotConfigured
#define TIFFInitZIP NotConfigured
#define TIFFInitPixarLog NotConfigured
#define TIFFInitSGILog NotConfigured
Functions
static int NotConfigured (TIFF *, int)
static int _notConfigured (TIFF *tif)
int TIFFIsCODECConfigured (uint16 scheme)
Variables
TIFFCodec _TIFFBuiltinCODECS []
Macro Definition Documentation
#define TIFFInitCCITTFax3 NotConfigured
Definition at line 57 of file tif_codec.c.
#define TIFFInitCCITTFax4 NotConfigured
Definition at line 58 of file tif_codec.c.
#define TIFFInitCCITTRLE NotConfigured
Definition at line 55 of file tif_codec.c.
#define TIFFInitCCITTRLEW NotConfigured
Definition at line 56 of file tif_codec.c.
#define TIFFInitJBIG NotConfigured
Definition at line 61 of file tif_codec.c.
#define TIFFInitJPEG NotConfigured
Definition at line 49 of file tif_codec.c.
#define TIFFInitLZW NotConfigured
Definition at line 37 of file tif_codec.c.
#define TIFFInitNeXT NotConfigured
Definition at line 46 of file tif_codec.c.
#define TIFFInitOJPEG NotConfigured
Definition at line 52 of file tif_codec.c.
#define TIFFInitPackBits NotConfigured
Definition at line 40 of file tif_codec.c.
#define TIFFInitPixarLog NotConfigured
Definition at line 67 of file tif_codec.c.
#define TIFFInitSGILog NotConfigured
Definition at line 70 of file tif_codec.c.
#define TIFFInitThunderScan NotConfigured
Definition at line 43 of file tif_codec.c.
#define TIFFInitZIP NotConfigured
Definition at line 64 of file tif_codec.c.
Function Documentation
static int _notConfigured (TIFF * tif) static
Definition at line 102 of file tif_codec.c.
References TIFFCodec::name, TIFFDirectory::td_compression, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), and TIFFFindCODEC().
Referenced by NotConfigured().
 {
     const TIFFCodec* c = TIFFFindCODEC(tif->tif_dir.td_compression);
     TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
         "%s compression support is not configured", c->name);
     return (0);
 }
static int NotConfigured (TIFF * tif, int scheme) static
Definition at line 112 of file tif_codec.c.
References _notConfigured(), FALSE, tiff::tif_decodestatus, tiff::tif_encodestatus, tiff::tif_setupdecode, and tiff::tif_setupencode.
Referenced by TIFFIsCODECConfigured().
 {
     (void) scheme;
     tif->tif_decodestatus = FALSE;
     tif->tif_setupdecode = _notConfigured;
     tif->tif_encodestatus = FALSE;
     tif->tif_setupencode = _notConfigured;
     return (1);
 }
int TIFFIsCODECConfigured (uint16 scheme)
Check whether we have working codec for the specific coding scheme.
Returns
returns 1 if the codec is configured and working. Otherwise 0 will be returned.
Definition at line 135 of file tif_codec.c.
References TIFFCodec::init, NotConfigured(), NULL, and TIFFFindCODEC().
Referenced by TIFFGetConfiguredCODECs().
 {
     const TIFFCodec* codec = TIFFFindCODEC(scheme);
     if(codec == NULL) {
             return 0;
         }
         if(codec->init == NULL) {
             return 0;
         }
     if(codec->init != NotConfigured){
             return 1;
         }
     return 0;
 }
Variable Documentation
TIFFCodec _TIFFBuiltinCODECS[]
Initial value:
= {
    { "None",       COMPRESSION_NONE,   TIFFInitDumpMode },
    { "LZW",        COMPRESSION_LZW,     NotConfigured  },
    { "PackBits",   COMPRESSION_PACKBITS,    NotConfigured  },
    { "ThunderScan",    COMPRESSION_THUNDERSCAN, NotConfigured  },
    { "ISO JBIG",   COMPRESSION_JBIG,    NotConfigured  },
    { "SGILog",     COMPRESSION_SGILOG,  NotConfigured  },
    { "SGILog24",   COMPRESSION_SGILOG24,    NotConfigured  },
    { NULL,             0,                      NULL }
}
Definition at line 79 of file tif_codec.c.
Referenced by TIFFFindCODEC(), and TIFFGetConfiguredCODECs().