Visible: src/util/code/tif_unix.c File Reference
tif_unix.c File Reference
#include "tif_config.h"
#include <stdarg.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "tiffiop.h"
Functions
static tsize_t _tiffReadProc (thandle_t fd, tdata_t buf, tsize_t size)
static tsize_t _tiffWriteProc (thandle_t fd, tdata_t buf, tsize_t size)
static toff_t _tiffSeekProc (thandle_t fd, toff_t off, int whence)
static int _tiffCloseProc (thandle_t fd)
static toff_t _tiffSizeProc (thandle_t fd)
static int _tiffMapProc (thandle_t fd, tdata_t *pbase, toff_t *psize)
static void _tiffUnmapProc (thandle_t fd, tdata_t base, toff_t size)
TIFF * TIFFFdOpen (int fd, const char *name, const char *mode)
TIFF * TIFFOpen (const char *name, const char *mode)
void * _TIFFmalloc (tsize_t s)
void _TIFFfree (tdata_t p)
void * _TIFFrealloc (tdata_t p, tsize_t s)
void _TIFFmemset (tdata_t p, int v, tsize_t c)
void _TIFFmemcpy (tdata_t d, const tdata_t s, tsize_t c)
int _TIFFmemcmp (const tdata_t p1, const tdata_t p2, tsize_t c)
static void unixWarningHandler (const char *module, const char *fmt, va_list ap)
static void unixErrorHandler (const char *module, const char *fmt, va_list ap)
Variables
TIFFErrorHandler _TIFFwarningHandler = unixWarningHandler
TIFFErrorHandler _TIFFerrorHandler = unixErrorHandler
Function Documentation
static int _tiffCloseProc (thandle_t fd) static
Definition at line 74 of file tif_unix.c.
References close().
Referenced by TIFFFdOpen().
 {
     return (close((int) fd));
 }
void _TIFFfree (tdata_t p)
Definition at line 244 of file tif_unix.c.
 {
     free(p);
 }
void* _TIFFmalloc (tsize_t s)
Definition at line 238 of file tif_unix.c.
 {
     return (malloc((size_t) s));
 }
static int _tiffMapProc (thandle_t fd, tdata_t * pbase, toff_t * psize) static
Definition at line 118 of file tif_unix.c.
Referenced by TIFFFdOpen().
 {
     (void) fd; (void) pbase; (void) psize;
     return (0);
 }
int _TIFFmemcmp (const tdata_t p1, const tdata_t p2, tsize_t c)
Definition at line 268 of file tif_unix.c.
 {
     return (memcmp(p1, p2, (size_t) c));
 }
void _TIFFmemcpy (tdata_t d, const tdata_t s, tsize_t c)
Definition at line 262 of file tif_unix.c.
 {
     memcpy(d, s, (size_t) c);
 }
void _TIFFmemset (tdata_t p, int v, tsize_t c)
Definition at line 256 of file tif_unix.c.
 {
     memset(p, v, (size_t) c);
 }
static tsize_t _tiffReadProc (thandle_t fd, tdata_t buf, tsize_t size) static
Definition at line 56 of file tif_unix.c.
Referenced by TIFFFdOpen().
 {
     return ((tsize_t) read((int) fd, buf, (size_t) size));
 }
void* _TIFFrealloc (tdata_t p, tsize_t s)
Definition at line 250 of file tif_unix.c.
References NULL.
 {
     return (realloc(p, (size_t) s));
 }
static toff_t _tiffSeekProc (thandle_t fd, toff_t off, int whence) static
Definition at line 68 of file tif_unix.c.
Referenced by TIFFFdOpen().
 {
     return ((toff_t) lseek((int) fd, (off_t) off, whence));
 }
static toff_t _tiffSizeProc (thandle_t fd) static
Definition at line 81 of file tif_unix.c.
Referenced by TIFFFdOpen().
 {
 #ifdef _AM29K
     long fsize;
     return ((fsize = lseek((int) fd, 0, SEEK_END)) < 0 ? 0 : fsize);
 #else
     struct stat sb;
     return (toff_t) (fstat((int) fd, &sb) < 0 ? 0 : sb.st_size);
 #endif
 }
static void _tiffUnmapProc (thandle_t fd, tdata_t base, toff_t size) static
Definition at line 125 of file tif_unix.c.
Referenced by TIFFFdOpen().
 {
     (void) fd; (void) base; (void) size;
 }
static tsize_t _tiffWriteProc (thandle_t fd, tdata_t buf, tsize_t size) static
Definition at line 62 of file tif_unix.c.
Referenced by TIFFFdOpen().
 {
     return ((tsize_t) write((int) fd, buf, (size_t) size));
 }
TIFF* TIFFFdOpen (int fd, const char * name, const char * mode)
Definition at line 135 of file tif_unix.c.
References _tiffCloseProc(), _tiffMapProc(), _tiffReadProc(), _tiffSeekProc(), _tiffSizeProc(), _tiffUnmapProc(), _tiffWriteProc(), tiff::tif_fd, and TIFFClientOpen().
 {
     TIFF* tif;
     tif = TIFFClientOpen(name, mode,
         (thandle_t) fd,
         _tiffReadProc, _tiffWriteProc,
         _tiffSeekProc, _tiffCloseProc, _tiffSizeProc,
         _tiffMapProc, _tiffUnmapProc);
     if (tif)
         tif->tif_fd = fd;
     return (tif);
 }
TIFF* TIFFOpen (const char * name, const char * mode)
Definition at line 153 of file tif_unix.c.
References _TIFFgetMode(), close(), O_BINARY, ourc2pstr(), TIFFErrorExt(), and TIFFFdOpen().
 {
     static const char module[] = "TIFFOpen";
     int m, fd;
         TIFF* tif;
     m = _TIFFgetMode(mode, module);
     if (m == -1)
         return ((TIFF*)0);
 /* for cygwin and mingw */
 #ifdef O_BINARY
         m |= O_BINARY;
 #endif
 #ifdef _AM29K
     fd = open(name, m);
 #else
     fd = open(name, m, 0666);
 #endif
     if (fd < 0) {
         TIFFErrorExt(0, module, "%s: Cannot open", name);
         return ((TIFF *)0);
     }
     tif = TIFFFdOpen((int)fd, name, mode);
     if(!tif)
         close(fd);
     return tif;
 }
static void unixErrorHandler (const char * module, const char * fmt, va_list ap) static
Definition at line 285 of file tif_unix.c.
References NULL.
 {
     if (module != NULL)
         fprintf(stderr, "%s: ", module);
     vfprintf(stderr, fmt, ap);
     fprintf(stderr, ".\n");
 }
static void unixWarningHandler (const char * module, const char * fmt, va_list ap) static
Definition at line 274 of file tif_unix.c.
References NULL.
 {
     if (module != NULL)
         fprintf(stderr, "%s: ", module);
     fprintf(stderr, "Warning, ");
     vfprintf(stderr, fmt, ap);
     fprintf(stderr, ".\n");
 }
Variable Documentation
TIFFErrorHandler _TIFFerrorHandler = unixErrorHandler
Definition at line 292 of file tif_unix.c.
TIFFErrorHandler _TIFFwarningHandler = unixWarningHandler
Definition at line 282 of file tif_unix.c.