Visible: src/util/code/tif_dumpmode.c File Reference
tif_dumpmode.c File Reference
#include "tiffiop.h"
Functions
static int DumpModeEncode (TIFF *tif, tidata_t pp, tsize_t cc, tsample_t s)
static int DumpModeDecode (TIFF *tif, tidata_t buf, tsize_t cc, tsample_t s)
static int DumpModeSeek (TIFF *tif, uint32 nrows)
int TIFFInitDumpMode (TIFF *tif, int scheme)
Function Documentation
static int DumpModeDecode (TIFF * tif, tidata_t buf, tsize_t cc, tsample_t s) static
Definition at line 71 of file tif_dumpmode.c.
References _TIFFmemcpy(), tiff::tif_clientdata, tiff::tif_name, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_row, and TIFFErrorExt().
Referenced by TIFFInitDumpMode().
 {
     (void) s;
     if (tif->tif_rawcc < cc) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
             "DumpModeDecode: Not enough data for scanline %d",
             tif->tif_row);
         return (0);
     }
     /*
      * Avoid copy if client has setup raw
      * data buffer to avoid extra copy.
      */
     if (tif->tif_rawcp != buf)
         _TIFFmemcpy(buf, tif->tif_rawcp, cc);
     tif->tif_rawcp += cc;
     tif->tif_rawcc -= cc;
     return (1);
 }
static int DumpModeEncode (TIFF * tif, tidata_t pp, tsize_t cc, tsample_t s) static
Definition at line 38 of file tif_dumpmode.c.
References _TIFFmemcpy(), tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdatasize, and TIFFFlushData1().
Referenced by TIFFInitDumpMode().
 {
     (void) s;
     while (cc > 0) {
         tsize_t n;
         n = cc;
         if (tif->tif_rawcc + n > tif->tif_rawdatasize)
             n = tif->tif_rawdatasize - tif->tif_rawcc;
                 assert( n > 0 );
         /*
          * Avoid copy if client has setup raw
          * data buffer to avoid extra copy.
          */
         if (tif->tif_rawcp != pp)
             _TIFFmemcpy(tif->tif_rawcp, pp, n);
         tif->tif_rawcp += n;
         tif->tif_rawcc += n;
         pp += n;
         cc -= n;
         if (tif->tif_rawcc >= tif->tif_rawdatasize &&
             !TIFFFlushData1(tif))
             return (-1);
     }
     return (1);
 }
static int DumpModeSeek (TIFF * tif, uint32 nrows) static
Definition at line 95 of file tif_dumpmode.c.
References tiff::tif_rawcc, tiff::tif_rawcp, and tiff::tif_scanlinesize.
Referenced by TIFFInitDumpMode().
 {
     tif->tif_rawcp += nrows * tif->tif_scanlinesize;
     tif->tif_rawcc -= nrows * tif->tif_scanlinesize;
     return (1);
 }
int TIFFInitDumpMode (TIFF * tif, int scheme)
Definition at line 106 of file tif_dumpmode.c.
References DumpModeDecode(), DumpModeEncode(), DumpModeSeek(), tiff::tif_decoderow, tiff::tif_decodestrip, tiff::tif_decodetile, tiff::tif_encoderow, tiff::tif_encodestrip, tiff::tif_encodetile, and tiff::tif_seek.
 {
     (void) scheme;
     tif->tif_decoderow = DumpModeDecode;
     tif->tif_decodestrip = DumpModeDecode;
     tif->tif_decodetile = DumpModeDecode;
     tif->tif_encoderow = DumpModeEncode;
     tif->tif_encodestrip = DumpModeEncode;
     tif->tif_encodetile = DumpModeEncode;
     tif->tif_seek = DumpModeSeek;
     return (1);
 }