Visible: src/util/code/tif_swab.c File Reference
tif_swab.c File Reference
#include "tiffiop.h"
Functions
void TIFFSwabShort (uint16 *wp)
void TIFFSwabLong (uint32 *lp)
void TIFFSwabArrayOfShort (uint16 *wp, register unsigned long n)
void TIFFSwabArrayOfTriples (uint8 *tp, unsigned long n)
void TIFFSwabArrayOfLong (register uint32 *lp, register unsigned long n)
void TIFFSwabDouble (double *dp)
void TIFFSwabArrayOfDouble (double *dp, register unsigned long n)
const unsigned char * TIFFGetBitRevTable (int reversed)
void TIFFReverseBits (register unsigned char *cp, register unsigned long n)
Variables
static const unsigned char TIFFBitRevTable [256]
static const unsigned char TIFFNoBitRevTable [256]
Function Documentation
const unsigned char* TIFFGetBitRevTable (int reversed)
Definition at line 212 of file tif_swab.c.
References TIFFBitRevTable, and TIFFNoBitRevTable.
 {
     return (reversed ? TIFFBitRevTable : TIFFNoBitRevTable);
 }
void TIFFReverseBits (register unsigned char * cp, register unsigned long n)
Definition at line 218 of file tif_swab.c.
References TIFFBitRevTable.
Referenced by TIFFFillStrip(), TIFFFillTile(), TIFFFlushData1(), TIFFWriteEncodedStrip(), and TIFFWriteEncodedTile().
 {
     for (; n > 8; n -= 8) {
         cp[0] = TIFFBitRevTable[cp[0]];
         cp[1] = TIFFBitRevTable[cp[1]];
         cp[2] = TIFFBitRevTable[cp[2]];
         cp[3] = TIFFBitRevTable[cp[3]];
         cp[4] = TIFFBitRevTable[cp[4]];
         cp[5] = TIFFBitRevTable[cp[5]];
         cp[6] = TIFFBitRevTable[cp[6]];
         cp[7] = TIFFBitRevTable[cp[7]];
         cp += 8;
     }
     while (n-- > 0)
         *cp = TIFFBitRevTable[*cp], cp++;
 }
void TIFFSwabArrayOfDouble (double * dp, register unsigned long n)
Definition at line 120 of file tif_swab.c.
References TIFFSwabArrayOfLong().
Referenced by _TIFFSwab64BitData(), TIFFFetchData(), and TIFFWriteData().
 {
     register uint32* lp = (uint32*) dp;
         register uint32 t;
     TIFFSwabArrayOfLong(lp, n + n);
         while (n-- > 0) {
         t = lp[0]; lp[0] = lp[1]; lp[1] = t;
                 lp += 2;
         }
 }
void TIFFSwabArrayOfLong (register uint32 * lp, register unsigned long n)
Definition at line 91 of file tif_swab.c.
Referenced by _TIFFSwab32BitData(), _TIFFWriteDirectory(), TIFFFetchData(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFSwabArrayOfDouble(), TIFFSwabDouble(), and TIFFWriteData().
 {
     register unsigned char *cp;
     register unsigned char t;
     /* XXX unroll loop some */
     while (n-- > 0) {
         cp = (unsigned char *)lp;
         t = cp[3]; cp[3] = cp[0]; cp[0] = t;
         t = cp[2]; cp[2] = cp[1]; cp[1] = t;
         lp++;
     }
 }
void TIFFSwabArrayOfShort (uint16 * wp, register unsigned long n)
Definition at line 59 of file tif_swab.c.
Referenced by _TIFFSwab16BitData(), _TIFFWriteDirectory(), TIFFImageIO::ReadGenericImage(), swabHorAcc16(), TIFFFetchData(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFWriteData().
 {
     register unsigned char* cp;
     register unsigned char t;
     /* XXX unroll loop some */
     while (n-- > 0) {
         cp = (unsigned char*) wp;
         t = cp[1]; cp[1] = cp[0]; cp[0] = t;
         wp++;
     }
 }
void TIFFSwabArrayOfTriples (uint8 * tp, unsigned long n)
Definition at line 75 of file tif_swab.c.
Referenced by _TIFFSwab24BitData().
 {
     unsigned char* cp;
     unsigned char t;
     /* XXX unroll loop some */
     while (n-- > 0) {
         cp = (unsigned char*) tp;
         t = cp[2]; cp[2] = cp[0]; cp[0] = t;
         tp += 3;
     }
 }
void TIFFSwabDouble (double * dp)
Definition at line 108 of file tif_swab.c.
References TIFFSwabArrayOfLong().
 {
         register uint32* lp = (uint32*) dp;
         uint32 t;
     TIFFSwabArrayOfLong(lp, 2);
     t = lp[0]; lp[0] = lp[1]; lp[1] = t;
 }
void TIFFSwabLong (uint32 * lp)
Definition at line 47 of file tif_swab.c.
Referenced by _TIFFWriteDirectory(), TIFFAdvanceDirectory(), TIFFClientOpen(), TIFFFetchString(), TIFFLinkDirectory(), TIFFReadDirectory(), TIFFRewriteDirectory(), and TIFFUnlinkDirectory().
 {
     register unsigned char* cp = (unsigned char*) lp;
     unsigned char t;
     t = cp[3]; cp[3] = cp[0]; cp[0] = t;
     t = cp[2]; cp[2] = cp[1]; cp[1] = t;
 }
void TIFFSwabShort (uint16 * wp)
Definition at line 36 of file tif_swab.c.
Referenced by _TIFFWriteDirectory(), TIFFAdvanceDirectory(), TIFFClientOpen(), TIFFLinkDirectory(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFRewriteDirectory().
 {
     register unsigned char* cp = (unsigned char*) wp;
     unsigned char t;
     t = cp[1]; cp[1] = cp[0]; cp[0] = t;
 }
Variable Documentation
const unsigned char TIFFBitRevTable[256] static
Definition at line 142 of file tif_swab.c.
Referenced by TIFFGetBitRevTable(), and TIFFReverseBits().
const unsigned char TIFFNoBitRevTable[256] static
Definition at line 176 of file tif_swab.c.
Referenced by TIFFGetBitRevTable().