Visible: include/util/tiffio.h File Reference
tiffio.h File Reference
#include "tiff.h"
#include "tiffvers.h"
#include <stdio.h>
#include <stdarg.h>
Classes
struct TIFFDisplay
struct TIFFYCbCrToRGB
struct TIFFCIELabToRGB
struct _TIFFRGBAImage
struct TIFFCodec
struct TIFFFieldInfo
struct _TIFFTagValue
struct TIFFTagMethods
Macros
#define NULL (void *)0
#define TIFFPRINT_NONE 0x0 /* no extra info */
#define TIFFPRINT_STRIPS 0x1 /* strips/tiles info */
#define TIFFPRINT_CURVES 0x2 /* color/gray response curves */
#define TIFFPRINT_COLORMAP 0x4 /* colormap */
#define TIFFPRINT_JPEGQTABLES 0x100 /* JPEG Q matrices */
#define TIFFPRINT_JPEGACTABLES 0x200 /* JPEG AC tables */
#define TIFFPRINT_JPEGDCTABLES 0x200 /* JPEG DC tables */
#define D65_X0 (95.0470F)
#define D65_Y0 (100.0F)
#define D65_Z0 (108.8827F)
#define D50_X0 (96.4250F)
#define D50_Y0 (100.0F)
#define D50_Z0 (82.4680F)
#define CIELABTORGB_TABLE_RANGE 1500
#define TIFFGetR(abgr) ((abgr) & 0xff)
#define TIFFGetG(abgr) (((abgr) >> 8) & 0xff)
#define TIFFGetB(abgr) (((abgr) >> 16) & 0xff)
#define TIFFGetA(abgr) (((abgr) >> 24) & 0xff)
#define LOGLUV_PUBLIC 1
#define TIFF_ANY TIFF_NOTYPE /* for field descriptor searching */
#define TIFF_VARIABLE -1 /* marker for variable length tags */
#define TIFF_SPP -2 /* marker for SamplesPerPixel tags */
#define TIFF_VARIABLE2 -3 /* marker for uint32 var-length tags */
#define FIELD_CUSTOM 65
#define U_NEU 0.210526316
#define V_NEU 0.473684211
#define UVSCALE 410.
Typedefs
typedef struct tiff TIFF
typedef uint32 ttag_t
typedef uint16 tdir_t
typedef uint16 tsample_t
typedef uint32 tstrip_t
typedef uint32 ttile_t
typedef int32 tsize_t
typedef void * tdata_t
typedef uint32 toff_t
typedef void * thandle_t
typedef unsigned char TIFFRGBValue
typedef struct _TIFFRGBAImage TIFFRGBAImage
typedef void(* tileContigRoutine)(TIFFRGBAImage *, uint32 *, uint32, uint32, uint32, uint32, int32, int32, unsigned char *)
typedef void(* tileSeparateRoutine)(TIFFRGBAImage *, uint32 *, uint32, uint32, uint32, uint32, int32, int32, unsigned char *, unsigned char *, unsigned char *, unsigned char *)
typedef int(* TIFFInitMethod)(TIFF *, int)
typedef void(* TIFFErrorHandler)(const char *, const char *, va_list)
typedef void(* TIFFErrorHandlerExt)(thandle_t, const char *, const char *, va_list)
typedef tsize_t(* TIFFReadWriteProc)(thandle_t, tdata_t, tsize_t)
typedef toff_t(* TIFFSeekProc)(thandle_t, toff_t, int)
typedef int(* TIFFCloseProc)(thandle_t)
typedef toff_t(* TIFFSizeProc)(thandle_t)
typedef int(* TIFFMapFileProc)(thandle_t, tdata_t *, toff_t *)
typedef void(* TIFFUnmapFileProc)(thandle_t, tdata_t, toff_t)
typedef void(* TIFFExtendProc)(TIFF *)
typedef struct _TIFFTagValue TIFFTagValue
typedef int(* TIFFVSetMethod)(TIFF *, ttag_t, va_list)
typedef int(* TIFFVGetMethod)(TIFF *, ttag_t, va_list)
typedef void(* TIFFPrintMethod)(TIFF *, FILE *, long)
Functions
const char * TIFFGetVersion (void)
const TIFFCodec * TIFFFindCODEC (uint16)
TIFFCodec * TIFFRegisterCODEC (uint16, const char *, TIFFInitMethod)
void TIFFUnRegisterCODEC (TIFFCodec *)
int TIFFIsCODECConfigured (uint16)
TIFFCodec * TIFFGetConfiguredCODECs (void)
tdata_t _TIFFmalloc (tsize_t)
tdata_t _TIFFrealloc (tdata_t, tsize_t)
void _TIFFmemset (tdata_t, int, tsize_t)
void _TIFFmemcpy (tdata_t, const tdata_t, tsize_t)
int _TIFFmemcmp (const tdata_t, const tdata_t, tsize_t)
void _TIFFfree (tdata_t)
int TIFFGetTagListCount (TIFF *)
ttag_t TIFFGetTagListEntry (TIFF *, int tag_index)
void TIFFMergeFieldInfo (TIFF *, const TIFFFieldInfo[], int)
const TIFFFieldInfo * TIFFFindFieldInfo (TIFF *, ttag_t, TIFFDataType)
const TIFFFieldInfo * TIFFFindFieldInfoByName (TIFF *, const char *, TIFFDataType)
const TIFFFieldInfo * TIFFFieldWithTag (TIFF *, ttag_t)
const TIFFFieldInfo * TIFFFieldWithName (TIFF *, const char *)
TIFFTagMethods * TIFFAccessTagMethods (TIFF *)
void * TIFFGetClientInfo (TIFF *, const char *)
void TIFFSetClientInfo (TIFF *, void *, const char *)
void TIFFCleanup (TIFF *)
void TIFFClose (TIFF *)
int TIFFFlush (TIFF *)
int TIFFFlushData (TIFF *)
int TIFFGetField (TIFF *, ttag_t,...)
int TIFFVGetField (TIFF *, ttag_t, va_list)
int TIFFGetFieldDefaulted (TIFF *, ttag_t,...)
int TIFFVGetFieldDefaulted (TIFF *, ttag_t, va_list)
int TIFFReadDirectory (TIFF *)
int TIFFReadCustomDirectory (TIFF *, toff_t, const TIFFFieldInfo[], size_t)
int TIFFReadEXIFDirectory (TIFF *, toff_t)
tsize_t TIFFScanlineSize (TIFF *)
tsize_t TIFFRasterScanlineSize (TIFF *)
tsize_t TIFFStripSize (TIFF *)
tsize_t TIFFRawStripSize (TIFF *, tstrip_t)
tsize_t TIFFVStripSize (TIFF *, uint32)
tsize_t TIFFTileRowSize (TIFF *)
tsize_t TIFFTileSize (TIFF *)
tsize_t TIFFVTileSize (TIFF *, uint32)
uint32 TIFFDefaultStripSize (TIFF *, uint32)
void TIFFDefaultTileSize (TIFF *, uint32 *, uint32 *)
int TIFFFileno (TIFF *)
int TIFFSetFileno (TIFF *, int)
thandle_t TIFFClientdata (TIFF *)
thandle_t TIFFSetClientdata (TIFF *, thandle_t)
int TIFFGetMode (TIFF *)
int TIFFSetMode (TIFF *, int)
int TIFFIsTiled (TIFF *)
int TIFFIsByteSwapped (TIFF *)
int TIFFIsUpSampled (TIFF *)
int TIFFIsMSB2LSB (TIFF *)
int TIFFIsBigEndian (TIFF *)
TIFFReadWriteProc TIFFGetReadProc (TIFF *)
TIFFReadWriteProc TIFFGetWriteProc (TIFF *)
TIFFSeekProc TIFFGetSeekProc (TIFF *)
TIFFCloseProc TIFFGetCloseProc (TIFF *)
TIFFSizeProc TIFFGetSizeProc (TIFF *)
TIFFMapFileProc TIFFGetMapFileProc (TIFF *)
TIFFUnmapFileProc TIFFGetUnmapFileProc (TIFF *)
uint32 TIFFCurrentRow (TIFF *)
tdir_t TIFFCurrentDirectory (TIFF *)
tdir_t TIFFNumberOfDirectories (TIFF *)
uint32 TIFFCurrentDirOffset (TIFF *)
tstrip_t TIFFCurrentStrip (TIFF *)
ttile_t TIFFCurrentTile (TIFF *)
int TIFFReadBufferSetup (TIFF *, tdata_t, tsize_t)
int TIFFWriteBufferSetup (TIFF *, tdata_t, tsize_t)
int TIFFSetupStrips (TIFF *)
int TIFFWriteCheck (TIFF *, int, const char *)
void TIFFFreeDirectory (TIFF *)
int TIFFCreateDirectory (TIFF *)
int TIFFLastDirectory (TIFF *)
int TIFFSetDirectory (TIFF *, tdir_t)
int TIFFSetSubDirectory (TIFF *, uint32)
int TIFFUnlinkDirectory (TIFF *, tdir_t)
int TIFFSetField (TIFF *, ttag_t,...)
int TIFFVSetField (TIFF *, ttag_t, va_list)
int TIFFWriteDirectory (TIFF *)
int TIFFCheckpointDirectory (TIFF *)
int TIFFRewriteDirectory (TIFF *)
int TIFFReassignTagToIgnore (enum TIFFIgnoreSense, int)
void TIFFPrintDirectory (TIFF *, FILE *, long)
int TIFFReadScanline (TIFF *, tdata_t, uint32, tsample_t)
int TIFFWriteScanline (TIFF *, tdata_t, uint32, tsample_t)
int TIFFReadRGBAImage (TIFF *, uint32, uint32, uint32 *, int)
int TIFFReadRGBAImageOriented (TIFF *, uint32, uint32, uint32 *, int, int)
int TIFFReadRGBAStrip (TIFF *, tstrip_t, uint32 *)
int TIFFReadRGBATile (TIFF *, uint32, uint32, uint32 *)
int TIFFRGBAImageOK (TIFF *, char[1024])
int TIFFRGBAImageBegin (TIFFRGBAImage *, TIFF *, int, char[1024])
int TIFFRGBAImageGet (TIFFRGBAImage *, uint32 *, uint32, uint32)
void TIFFRGBAImageEnd (TIFFRGBAImage *)
TIFF * TIFFOpen (const char *, const char *)
TIFF * TIFFFdOpen (int, const char *, const char *)
TIFF * TIFFClientOpen (const char *, const char *, thandle_t, TIFFReadWriteProc, TIFFReadWriteProc, TIFFSeekProc, TIFFCloseProc, TIFFSizeProc, TIFFMapFileProc, TIFFUnmapFileProc)
const char * TIFFFileName (TIFF *)
const char * TIFFSetFileName (TIFF *, const char *)
void TIFFError (const char *, const char *,...)
void TIFFErrorExt (thandle_t, const char *, const char *,...)
void TIFFWarning (const char *, const char *,...)
void TIFFWarningExt (thandle_t, const char *, const char *,...)
TIFFErrorHandler TIFFSetErrorHandler (TIFFErrorHandler)
TIFFErrorHandlerExt TIFFSetErrorHandlerExt (TIFFErrorHandlerExt)
TIFFErrorHandler TIFFSetWarningHandler (TIFFErrorHandler)
TIFFErrorHandlerExt TIFFSetWarningHandlerExt (TIFFErrorHandlerExt)
TIFFExtendProc TIFFSetTagExtender (TIFFExtendProc)
ttile_t TIFFComputeTile (TIFF *, uint32, uint32, uint32, tsample_t)
int TIFFCheckTile (TIFF *, uint32, uint32, uint32, tsample_t)
ttile_t TIFFNumberOfTiles (TIFF *)
tsize_t TIFFReadTile (TIFF *, tdata_t, uint32, uint32, uint32, tsample_t)
tsize_t TIFFWriteTile (TIFF *, tdata_t, uint32, uint32, uint32, tsample_t)
tstrip_t TIFFComputeStrip (TIFF *, uint32, tsample_t)
tstrip_t TIFFNumberOfStrips (TIFF *)
tsize_t TIFFReadEncodedStrip (TIFF *, tstrip_t, tdata_t, tsize_t)
tsize_t TIFFReadRawStrip (TIFF *, tstrip_t, tdata_t, tsize_t)
tsize_t TIFFReadEncodedTile (TIFF *, ttile_t, tdata_t, tsize_t)
tsize_t TIFFReadRawTile (TIFF *, ttile_t, tdata_t, tsize_t)
tsize_t TIFFWriteEncodedStrip (TIFF *, tstrip_t, tdata_t, tsize_t)
tsize_t TIFFWriteRawStrip (TIFF *, tstrip_t, tdata_t, tsize_t)
tsize_t TIFFWriteEncodedTile (TIFF *, ttile_t, tdata_t, tsize_t)
tsize_t TIFFWriteRawTile (TIFF *, ttile_t, tdata_t, tsize_t)
int TIFFDataWidth (TIFFDataType)
void TIFFSetWriteOffset (TIFF *, toff_t)
void TIFFSwabShort (uint16 *)
void TIFFSwabLong (uint32 *)
void TIFFSwabDouble (double *)
void TIFFSwabArrayOfShort (uint16 *, unsigned long)
void TIFFSwabArrayOfTriples (uint8 *, unsigned long)
void TIFFSwabArrayOfLong (uint32 *, unsigned long)
void TIFFSwabArrayOfDouble (double *, unsigned long)
void TIFFReverseBits (unsigned char *, unsigned long)
const unsigned char * TIFFGetBitRevTable (int)
double LogL16toY (int)
double LogL10toY (int)
void XYZtoRGB24 (float *, uint8 *)
int uv_decode (double *, double *, int)
void LogLuv24toXYZ (uint32, float *)
void LogLuv32toXYZ (uint32, float *)
int LogL16fromY (double, int)
int LogL10fromY (double, int)
int uv_encode (double, double, int)
uint32 LogLuv24fromXYZ (float *, int)
uint32 LogLuv32fromXYZ (float *, int)
int TIFFCIELabToRGBInit (TIFFCIELabToRGB *, TIFFDisplay *, float *)
void TIFFCIELabToXYZ (TIFFCIELabToRGB *, uint32, int32, int32, float *, float *, float *)
void TIFFXYZToRGB (TIFFCIELabToRGB *, float, float, float, uint32 *, uint32 *, uint32 *)
int TIFFYCbCrToRGBInit (TIFFYCbCrToRGB *, float *, float *)
void TIFFYCbCrtoRGB (TIFFYCbCrToRGB *, uint32, int32, int32, uint32 *, uint32 *, uint32 *)
Macro Definition Documentation
#define CIELABTORGB_TABLE_RANGE 1500
Definition at line 162 of file tiffio.h.
Referenced by TIFFCIELabToRGBInit().
#define D50_X0 (96.4250F)
Definition at line 127 of file tiffio.h.
Referenced by TIFFVGetFieldDefaulted().
#define D50_Y0 (100.0F)
Definition at line 128 of file tiffio.h.
Referenced by TIFFVGetFieldDefaulted().
#define D50_Z0 (82.4680F)
Definition at line 129 of file tiffio.h.
Referenced by TIFFVGetFieldDefaulted().
#define D65_X0 (95.0470F)
Definition at line 123 of file tiffio.h.
#define D65_Y0 (100.0F)
Definition at line 124 of file tiffio.h.
#define D65_Z0 (108.8827F)
Definition at line 125 of file tiffio.h.
#define FIELD_CUSTOM 65
Definition at line 300 of file tiffio.h.
Referenced by _TIFFCreateAnonFieldInfo(), _TIFFSetupFieldInfo(), _TIFFVGetField(), _TIFFVSetField(), _TIFFWriteDirectory(), and TIFFCleanup().
#define LOGLUV_PUBLIC 1
Definition at line 254 of file tiffio.h.
#define NULL (void *)0
Definition at line 101 of file tiffio.h.
Referenced by _TIFFCheckMalloc(), _TIFFCreateAnonFieldInfo(), _TIFFFieldWithName(), _TIFFFieldWithTag(), _TIFFFindFieldInfo(), _TIFFFindFieldInfoByName(), _TIFFFindOrRegisterFieldInfo(), _TIFFMergeFieldInfo(), _TIFFrealloc(), _TIFFVGetField(), _TIFFVSetField(), _TIFFWriteDirectory(), rcMenuBar::about(), rcSharedMemoryUser::acquireSharedMemory(), rcMovieConverterToQT::addVideoSamplesToMedia(), appleErrorHandler(), appleWarningHandler(), CalcLimitsCC(), rcWindow::CGImage(), ChopUpSingleUncompressedStrip(), TIFFReaderInternal::Clean(), clip_polygon_to_pel(), rcWriterManager::createGraphicsWriter(), createKernelCC(), rcWriterManager::createPositionWriter(), rcMovieConverterToQT::createQTMovie(), rcWriterManager::createScalarWriter(), rcWriterManager::createVideoWriter(), rcWriterManager::createWriter(), cvCreateVideoWriter(), cvReleaseVideoWriter(), cvWriteFrame(), DisposeMungData(), exportCGImageToJPGFile(), findEthernetInterfaces(), FSSpecFromPosixPath(), rcDefGenerateImage::genImage(), genRFYmov(), get_architecture(), rcMPEG2Grabber::get_fbuf(), get_numproc(), get_procspeed(), getCurrentTimestamp(), rcTimeline::getFrameTime(), rcImageGrabber::getNextFrame(), rcMovieGrabber::getNextFrame(), getNextVideoSample(), rcMovieGrabber::getNextVideoSample(), rcMovieGrabber::getPixelInfoFromImageDesc(), rcMPEG2Grabber::getReifyMovie(), rcCmdLine::getSafeArgument(), rcTimeline::getSegmentLength(), rcTime::getUnixTime(), getVideoMediaImageDesc(), icvEncodedFrameOutputCallback(), icvGrabFrame_QT_Movie(), icvOpenFile_QT_Movie(), icvSetProperty_QT_Movie(), initCIELabConversion(), InitializeMungData(), InitializeMungData2(), initYCbCrConversion(), rcCmdLine::isSwitch(), main(), MakeAWindow(), makebwmap(), makecmap(), MakeFSSpec(), MakeSequenceGrabber(), MakeSequenceGrabChannel(), MGIdleTimer(), MungGrabDataProc(), rcEngineImpl::muscleTracker(), rcExperimentDomainImpl::notifyRequestSave(), rcGenMovieFile::open(), TIFFReaderInternal::Open(), rcEngineMovieSaver::openHdlr(), rcGlobIterator::operator++(), operator<<(), PredictorDecodeRow(), PredictorDecodeTile(), PredictorEncodeRow(), PredictorEncodeTile(), rc_fill_poly(), rcChainCode::rcChainCode(), rcConditionVariable::rcConditionVariable(), rcCreateChildShmem::rcCreateChildShmem(), rcExecWithShmem::rcExecWithShmem(), rcLabelRLE::rcLabelRLE(), rcMPEG2Grabber::rcMPEG2Grabber(), rcSignalPending::rcSignalPending(), rcVideoCache::rcVideoCache(), rcWriterManager::rcWriterManager(), rfConvertMovie(), rfConvertTwoMovies(), rfCountMovieFrames(), rfDCAMVideoCapture(), rfGauss3(), rfGaussianConv(), rfGetXMLNameMapper(), rfHasSIMD(), rfImageExport2JPG(), rfImageFileToRcWindow(), rfInterpolatePeak(), rfMakeFSSpecFromPosixPath(), rfMovieFileToRcWindow(), rfPixelMax3By3(), rfPixelMin3By3(), rfQTVideoCapture(), rfSystemRam(), RingBuffer_GetReadRegions(), RingBuffer_GetWriteRegions(), setExtraSamples(), setupMap(), rcMPEG2Grabber::start(), rcMovieGrabber::start(), rcWindow::tiff(), TIFFAdvanceDirectory(), TIFFCheckpointDirectory(), TIFFClientOpen(), TIFFDefaultDirectory(), TIFFFetchNormalTag(), TIFFFetchRefBlackWhite(), TIFFFetchStripThing(), TIFFGetClientInfo(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), TIFFIsCODECConfigured(), TIFFNumberOfDirectories(), TIFFPredictorInit(), TIFFPrintDirectory(), TIFFReadBufferSetup(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFReaderInternal::TIFFReaderInternal(), TIFFRegisterCODEC(), TIFFRGBAImageBegin(), TIFFRGBAImageEnd(), TIFFRGBAImageGet(), TIFFSetClientInfo(), TIFFSetDirectory(), TIFFSetupStrips(), TIFFUnlinkDirectory(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWriteCheck(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), TIFFWriteRationalArray(), unixErrorHandler(), unixWarningHandler(), yourDisplayCallback(), rcQVideoGrabber::~rcQVideoGrabber(), and rcVideoCache::~rcVideoCache().
#define TIFF_ANY TIFF_NOTYPE /* for field descriptor searching */
Definition at line 295 of file tiffio.h.
Referenced by _TIFFFieldWithName(), _TIFFFieldWithTag(), _TIFFFindFieldInfo(), _TIFFFindFieldInfoByName(), _TIFFVGetField(), _TIFFVSetField(), OkToChangeTag(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFVGetField().
#define TIFF_SPP -2 /* marker for SamplesPerPixel tags */
Definition at line 297 of file tiffio.h.
Referenced by _TIFFVGetField(), _TIFFVSetField(), TIFFReaderInternal::Open(), TIFFPrintDirectory(), TIFFReadCustomDirectory(), and TIFFReadDirectory().
#define TIFF_VARIABLE -1 /* marker for variable length tags */
Definition at line 296 of file tiffio.h.
Referenced by _TIFFCreateAnonFieldInfo(), _TIFFVGetField(), _TIFFVSetField(), TIFFReaderInternal::Open(), TIFFPrintDirectory(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFWriteNormalTag().
#define TIFF_VARIABLE2 -3 /* marker for uint32 var-length tags */
Definition at line 298 of file tiffio.h.
Referenced by _TIFFVGetField(), _TIFFVSetField(), TIFFReaderInternal::Open(), TIFFPrintDirectory(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFWriteNormalTag().
#define TIFFGetA (abgr) (((abgr) >> 24) & 0xff)
Definition at line 233 of file tiffio.h.
#define TIFFGetB (abgr) (((abgr) >> 16) & 0xff)
Definition at line 232 of file tiffio.h.
#define TIFFGetG (abgr) (((abgr) >> 8) & 0xff)
Definition at line 231 of file tiffio.h.
#define TIFFGetR (abgr) ((abgr) & 0xff)
Definition at line 230 of file tiffio.h.
#define TIFFPRINT_COLORMAP 0x4 /* colormap */
Definition at line 113 of file tiffio.h.
Referenced by TIFFPrintDirectory().
#define TIFFPRINT_CURVES 0x2 /* color/gray response curves */
Definition at line 112 of file tiffio.h.
Referenced by TIFFPrintDirectory().
#define TIFFPRINT_JPEGACTABLES 0x200 /* JPEG AC tables */
Definition at line 115 of file tiffio.h.
#define TIFFPRINT_JPEGDCTABLES 0x200 /* JPEG DC tables */
Definition at line 116 of file tiffio.h.
#define TIFFPRINT_JPEGQTABLES 0x100 /* JPEG Q matrices */
Definition at line 114 of file tiffio.h.
#define TIFFPRINT_NONE 0x0 /* no extra info */
Definition at line 110 of file tiffio.h.
#define TIFFPRINT_STRIPS 0x1 /* strips/tiles info */
Definition at line 111 of file tiffio.h.
Referenced by TIFFPrintDirectory().
#define U_NEU 0.210526316
Definition at line 476 of file tiffio.h.
#define UVSCALE 410.
Definition at line 478 of file tiffio.h.
#define V_NEU 0.473684211
Definition at line 477 of file tiffio.h.
Typedef Documentation
typedef void* tdata_t
Definition at line 67 of file tiffio.h.
typedef uint16 tdir_t
Definition at line 62 of file tiffio.h.
typedef void* thandle_t
Definition at line 97 of file tiffio.h.
typedef struct tiff TIFF
Definition at line 40 of file tiffio.h.
typedef int(* TIFFCloseProc)(thandle_t)
Definition at line 264 of file tiffio.h.
typedef void(* TIFFErrorHandler)(const char *, const char *, va_list)
Definition at line 260 of file tiffio.h.
typedef void(* TIFFErrorHandlerExt)(thandle_t, const char *, const char *, va_list)
Definition at line 261 of file tiffio.h.
typedef void(* TIFFExtendProc)(TIFF *)
Definition at line 268 of file tiffio.h.
typedef int(* TIFFInitMethod)(TIFF *, int)
Definition at line 242 of file tiffio.h.
typedef int(* TIFFMapFileProc)(thandle_t, tdata_t *, toff_t *)
Definition at line 266 of file tiffio.h.
typedef void(* TIFFPrintMethod)(TIFF *, FILE *, long)
Definition at line 328 of file tiffio.h.
typedef tsize_t(* TIFFReadWriteProc)(thandle_t, tdata_t, tsize_t)
Definition at line 262 of file tiffio.h.
typedef struct _TIFFRGBAImage TIFFRGBAImage
Definition at line 174 of file tiffio.h.
typedef unsigned char TIFFRGBValue
Definition at line 133 of file tiffio.h.
typedef toff_t(* TIFFSeekProc)(thandle_t, toff_t, int)
Definition at line 263 of file tiffio.h.
typedef toff_t(* TIFFSizeProc)(thandle_t)
Definition at line 265 of file tiffio.h.
typedef struct _TIFFTagValue TIFFTagValue
typedef void(* TIFFUnmapFileProc)(thandle_t, tdata_t, toff_t)
Definition at line 267 of file tiffio.h.
typedef int(* TIFFVGetMethod)(TIFF *, ttag_t, va_list)
Definition at line 327 of file tiffio.h.
typedef int(* TIFFVSetMethod)(TIFF *, ttag_t, va_list)
Definition at line 326 of file tiffio.h.
typedef void(* tileContigRoutine)(TIFFRGBAImage *, uint32 *, uint32, uint32, uint32, uint32, int32, int32, unsigned char *)
Definition at line 186 of file tiffio.h.
typedef void(* tileSeparateRoutine)(TIFFRGBAImage *, uint32 *, uint32, uint32, uint32, uint32, int32, int32, unsigned char *, unsigned char *, unsigned char *, unsigned char *)
Definition at line 189 of file tiffio.h.
typedef uint32 toff_t
Definition at line 68 of file tiffio.h.
typedef uint16 tsample_t
Definition at line 63 of file tiffio.h.
typedef int32 tsize_t
Definition at line 66 of file tiffio.h.
typedef uint32 tstrip_t
Definition at line 64 of file tiffio.h.
typedef uint32 ttag_t
Definition at line 61 of file tiffio.h.
typedef uint32 ttile_t
Definition at line 65 of file tiffio.h.
Function Documentation
void _TIFFfree (tdata_t)
Definition at line 233 of file tif_apple.c.
Referenced by _TIFFCreateAnonFieldInfo(), _TIFFSetupFieldInfo(), _TIFFVSetField(), _TIFFWriteDirectory(), ChopUpSingleUncompressedStrip(), EstimateStripByteCounts(), fpAcc(), fpDiff(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), initCIELabConversion(), TIFFReaderInternal::Open(), setByteArray(), setupMap(), rcWindow::tiff(), TIFFCleanup(), TIFFDefaultTransferFunction(), TIFFFetchNormalTag(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFFetchRationalArray(), TIFFFetchRefBlackWhite(), TIFFFetchStripThing(), TIFFFillStrip(), TIFFFillTile(), TIFFFreeDirectory(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), TIFFPrintDirectory(), TIFFReadBufferSetup(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFRGBAImageEnd(), TIFFUnlinkDirectory(), TIFFUnRegisterCODEC(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), and TIFFWriteRationalArray().
 {
     DisposePtr(p);
 }
tdata_t _TIFFmalloc (tsize_t)
Definition at line 227 of file tif_apple.c.
Referenced by _TIFFCheckMalloc(), _TIFFCreateAnonFieldInfo(), _TIFFMergeFieldInfo(), _TIFFVSetField(), _TIFFWriteDirectory(), fpAcc(), fpDiff(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), initCIELabConversion(), initYCbCrConversion(), makebwmap(), makecmap(), TIFFReaderInternal::Open(), setByteArray(), setupMap(), rcWindow::tiff(), TIFFClientOpen(), TIFFDefaultTransferFunction(), TIFFPrintDirectory(), TIFFReadBufferSetup(), TIFFRegisterCODEC(), TIFFRGBAImageBegin(), TIFFSetClientInfo(), TIFFSetupStrips(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), and TIFFWriteRationalArray().
 {
     return (NewPtr((size_t) s));
 }
int _TIFFmemcmp (const tdata_t , const tdata_t , tsize_t)
Definition at line 221 of file tif_apple.c.
Referenced by TIFFWriteTransferFunction().
 {
     return (memcmp(p1, p2, (size_t) c));
 }
void _TIFFmemcpy (tdata_t , const tdata_t , tsize_t)
Definition at line 215 of file tif_apple.c.
Referenced by _TIFFVSetField(), _TIFFWriteDirectory(), DumpModeDecode(), DumpModeEncode(), fpAcc(), fpDiff(), setByteArray(), TIFFAdvanceDirectory(), TIFFCIELabToRGBInit(), TIFFDefaultTransferFunction(), TIFFFetchData(), TIFFFetchFloat(), TIFFFetchString(), TIFFGetConfiguredCODECs(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFReadRawStrip1(), TIFFReadRawTile1(), TIFFRGBAImageBegin(), and TIFFWriteByteArray().
 {
     memcpy(d, s, (size_t) c);
 }
void _TIFFmemset (tdata_t , int , tsize_t)
Definition at line 209 of file tif_apple.c.
Referenced by _TIFFCreateAnonFieldInfo(), _TIFFVSetField(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), TIFFClientOpen(), TIFFDefaultDirectory(), TIFFFetchStripThing(), TIFFFreeDirectory(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), TIFFReadRGBATile(), TIFFSetupStrips(), and TIFFYCbCrToRGBInit().
 {
     memset(p, v, (size_t) c);
 }
tdata_t _TIFFrealloc (tdata_t , tsize_t)
Definition at line 239 of file tif_apple.c.
References NULL.
Referenced by _TIFFMergeFieldInfo(), _TIFFVSetField(), TIFFGetConfiguredCODECs(), TIFFGrowStrips(), and TIFFReadDirectory().
 {
     Ptr n = p;
     SetPtrSize(p, (size_t) s);
     if (MemError() && (n = NewPtr((size_t) s)) != NULL) {
         BlockMove(p, n, GetPtrSize(p));
         DisposePtr(p);
     }
     return ((tdata_t) n);
 }
int LogL10fromY (double , int)
double LogL10toY (int)
int LogL16fromY (double , int)
double LogL16toY (int)
uint32 LogLuv24fromXYZ (float * , int)
void LogLuv24toXYZ (uint32 , float *)
uint32 LogLuv32fromXYZ (float * , int)
void LogLuv32toXYZ (uint32 , float *)
TIFFTagMethods* TIFFAccessTagMethods (TIFF *)
Definition at line 60 of file tif_extension.c.
References tiff::tif_tagmethods.
 {
     return &(tif->tif_tagmethods);
 }
int TIFFCheckpointDirectory (TIFF *)
Definition at line 417 of file tif_dirwrite.c.
References _TIFFWriteDirectory(), FALSE, NULL, TIFFDirectory::td_stripoffset, tiff::tif_dir, TIFFSeekFile, TIFFSetupStrips(), and TIFFSetWriteOffset().
 {
     int rc;
     /* Setup the strips arrays, if they haven't already been. */
     if (tif->tif_dir.td_stripoffset == NULL)
         (void) TIFFSetupStrips(tif);
     rc = _TIFFWriteDirectory(tif, FALSE);
     (void) TIFFSetWriteOffset(tif, TIFFSeekFile(tif, 0, SEEK_END));
     return rc;
 }
int TIFFCheckTile (TIFF * , uint32 , uint32 , uint32 , tsample_t)
Definition at line 105 of file tif_tile.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, and TIFFErrorExt().
Referenced by TIFFReadTile(), and TIFFWriteTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (x >= td->td_imagewidth) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Col out of range, max %lu",
             (unsigned long) x, (unsigned long) td->td_imagewidth);
         return (0);
     }
     if (y >= td->td_imagelength) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Row out of range, max %lu",
             (unsigned long) y, (unsigned long) td->td_imagelength);
         return (0);
     }
     if (z >= td->td_imagedepth) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Depth out of range, max %lu",
             (unsigned long) z, (unsigned long) td->td_imagedepth);
         return (0);
     }
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE &&
         s >= td->td_samplesperpixel) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Sample out of range, max %lu",
             (unsigned long) s, (unsigned long) td->td_samplesperpixel);
         return (0);
     }
     return (1);
 }
int TIFFCIELabToRGBInit (TIFFCIELabToRGB * , TIFFDisplay * , float *)
Definition at line 125 of file tif_color.c.
References _TIFFmemcpy(), TIFFCIELabToRGB::bstep, CIELABTORGB_TABLE_RANGE, TIFFDisplay::d_gammaB, TIFFDisplay::d_gammaG, TIFFDisplay::d_gammaR, TIFFDisplay::d_Vrwb, TIFFDisplay::d_Vrwg, TIFFDisplay::d_Vrwr, TIFFDisplay::d_Y0R, TIFFDisplay::d_YCR, TIFFCIELabToRGB::display, TIFFCIELabToRGB::gstep, pow(), TIFFCIELabToRGB::range, TIFFCIELabToRGB::rstep, TIFFCIELabToRGB::X0, TIFFCIELabToRGB::Y0, TIFFCIELabToRGB::Yb2b, TIFFCIELabToRGB::Yg2g, TIFFCIELabToRGB::Yr2r, and TIFFCIELabToRGB::Z0.
Referenced by initCIELabConversion().
 {
     int i;
     double gamma;
     cielab->range = CIELABTORGB_TABLE_RANGE;
     _TIFFmemcpy(&cielab->display, display, sizeof(TIFFDisplay));
     /* Red */
     gamma = 1.0 / cielab->display.d_gammaR ;
     cielab->rstep =
         (cielab->display.d_YCR - cielab->display.d_Y0R) / cielab->range;
     for(i = 0; i <= cielab->range; i++) {
         cielab->Yr2r[i] = cielab->display.d_Vrwr
             * ((float)pow((double)i / cielab->range, gamma));
     }
     /* Green */
     gamma = 1.0 / cielab->display.d_gammaG ;
     cielab->gstep =
         (cielab->display.d_YCR - cielab->display.d_Y0R) / cielab->range;
     for(i = 0; i <= cielab->range; i++) {
         cielab->Yg2g[i] = cielab->display.d_Vrwg
             * ((float)pow((double)i / cielab->range, gamma));
     }
     /* Blue */
     gamma = 1.0 / cielab->display.d_gammaB ;
     cielab->bstep =
         (cielab->display.d_YCR - cielab->display.d_Y0R) / cielab->range;
     for(i = 0; i <= cielab->range; i++) {
         cielab->Yb2b[i] = cielab->display.d_Vrwb
             * ((float)pow((double)i / cielab->range, gamma));
     }
     /* Init reference white point */
     cielab->X0 = refWhite[0];
     cielab->Y0 = refWhite[1];
     cielab->Z0 = refWhite[2];
     return 0;
 }
void TIFFCIELabToXYZ (TIFFCIELabToRGB * , uint32 , int32 , int32 , float * , float * , float *)
Definition at line 46 of file tif_color.c.
References TIFFCIELabToRGB::X0, TIFFCIELabToRGB::Y0, and TIFFCIELabToRGB::Z0.
Referenced by putcontig8bitCIELab().
 {
     float L = (float)l * 100.0F / 255.0F;
     float cby, tmp;
     if( L < 8.856F ) {
         *Y = (L * cielab->Y0) / 903.292F;
         cby = 7.787F * (*Y / cielab->Y0) + 16.0F / 116.0F;
     } else {
         cby = (L + 16.0F) / 116.0F;
         *Y = cielab->Y0 * cby * cby * cby;
     }
     tmp = (float)a / 500.0F + cby;
     if( tmp < 0.2069F )
         *X = cielab->X0 * (tmp - 0.13793F) / 7.787F;
     else
         *X = cielab->X0 * tmp * tmp * tmp;
     tmp = cby - (float)b / 200.0F;
     if( tmp < 0.2069F )
         *Z = cielab->Z0 * (tmp - 0.13793F) / 7.787F;
     else
         *Z = cielab->Z0 * tmp * tmp * tmp;
 }
void TIFFCleanup (TIFF * tif)
Auxiliary function to free the TIFF structure. Given structure will be completetly freed, so you should save opened file handle and pointer to the close procedure in external variables before calling _TIFFCleanup(), if you will need these ones to close the file.
Parameters
tif A TIFF pointer.
Definition at line 46 of file tif_close.c.
References _TIFFfree(), TIFFFieldInfo::field_bit, FIELD_CUSTOM, TIFFFieldInfo::field_name, isMapped, client_info::name, client_info::next, tiff::tif_base, tiff::tif_cleanup, tiff::tif_clientinfo, tiff::tif_dirlist, tiff::tif_fieldinfo, tiff::tif_flags, tiff::tif_mode, tiff::tif_nfields, tiff::tif_rawdata, tiff::tif_size, TIFF_MYBUFFER, TIFFFlush(), TIFFFreeDirectory(), and TIFFUnmapFileContents.
Referenced by TIFFClientOpen(), and TIFFClose().
 {
     if (tif->tif_mode != O_RDONLY)
         /*
          * Flush buffered data and directory (if dirty).
          */
         TIFFFlush(tif);
     (*tif->tif_cleanup)(tif);
     TIFFFreeDirectory(tif);
     if (tif->tif_dirlist)
         _TIFFfree(tif->tif_dirlist);
     /* Clean up client info links */
     while( tif->tif_clientinfo )
     {
         TIFFClientInfoLink *link = tif->tif_clientinfo;
         tif->tif_clientinfo = link->next;
         _TIFFfree( link->name );
         _TIFFfree( link );
     }
     if (tif->tif_rawdata && (tif->tif_flags&TIFF_MYBUFFER))
         _TIFFfree(tif->tif_rawdata);
     if (isMapped(tif))
         TIFFUnmapFileContents(tif, tif->tif_base, tif->tif_size);
     /* Clean up custom fields */
     if (tif->tif_nfields > 0)
     {
         size_t  i;
         for (i = 0; i < tif->tif_nfields; i++)
         {
         TIFFFieldInfo *fld = tif->tif_fieldinfo[i];
         if (fld->field_bit == FIELD_CUSTOM &&
             strncmp("Tag ", fld->field_name, 4) == 0)
         {
             _TIFFfree(fld->field_name);
             _TIFFfree(fld);
         }
         }
         _TIFFfree(tif->tif_fieldinfo);
     }
     _TIFFfree(tif);
 }
thandle_t TIFFClientdata (TIFF *)
Definition at line 504 of file tif_open.c.
References tiff::tif_clientdata.
 {
     return (tif->tif_clientdata);
 }
TIFF* TIFFClientOpen (const char * , const char * , thandle_t , TIFFReadWriteProc , TIFFReadWriteProc , TIFFSeekProc , TIFFCloseProc , TIFFSizeProc , TIFFMapFileProc , TIFFUnmapFileProc)
Definition at line 143 of file tif_open.c.
References _tiffDummyMapProc(), _tiffDummyUnmapProc(), _TIFFgetMode(), _TIFFmalloc(), _TIFFmemset(), _TIFFSetDefaultCompressionState(), FILLORDER_LSB2MSB, FILLORDER_MSB2LSB, HOST_BIGENDIAN, HOST_FILLORDER, MDI_BIGENDIAN, MDI_LITTLEENDIAN, NULL, ReadOK, STRIPCHOP_DEFAULT, tiff::tif_base, tiff::tif_clientdata, tiff::tif_closeproc, tiff::tif_curdir, tiff::tif_curoff, tiff::tif_curstrip, tiff::tif_dirlist, tiff::tif_dirnumber, tiff::tif_diroff, tiff::tif_flags, tiff::tif_header, tiff::tif_mapproc, tiff::tif_mode, tiff::tif_name, tiff::tif_nextdiroff, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_readproc, tiff::tif_row, tiff::tif_seekproc, tiff::tif_size, tiff::tif_sizeproc, tiff::tif_unmapproc, tiff::tif_writeproc, TIFF_BIGENDIAN, TIFF_BIGTIFF_VERSION, TIFF_BUFFERSETUP, TIFFHeader::tiff_diroff, TIFF_FILLORDER, TIFF_HEADERONLY, TIFF_LITTLEENDIAN, TIFFHeader::tiff_magic, TIFF_MAPPED, TIFF_MYBUFFER, TIFF_STRIPCHOP, TIFF_SWAB, TIFF_VERSION, TIFFHeader::tiff_version, TIFFCleanup(), TIFFDefaultDirectory(), TIFFErrorExt(), TIFFInitOrder(), TIFFMapFileContents, TIFFReadDirectory(), TIFFSeekFile, TIFFSwabLong(), TIFFSwabShort(), and WriteOK.
Referenced by TIFFFdOpen().
 {
     static const char module[] = "TIFFClientOpen";
     TIFF *tif;
     int m;
     const char* cp;
     m = _TIFFgetMode(mode, module);
     if (m == -1)
         goto bad2;
     tif = (TIFF *)_TIFFmalloc(sizeof (TIFF) + strlen(name) + 1);
     if (tif == NULL) {
         TIFFErrorExt(clientdata, module, "%s: Out of memory (TIFF structure)", name);
         goto bad2;
     }
     _TIFFmemset(tif, 0, sizeof (*tif));
     tif->tif_name = (char *)tif + sizeof (TIFF);
     strcpy(tif->tif_name, name);
     tif->tif_mode = m &~ (O_CREAT|O_TRUNC);
     tif->tif_curdir = (tdir_t) -1;      /* non-existent directory */
     tif->tif_curoff = 0;
     tif->tif_curstrip = (tstrip_t) -1;  /* invalid strip */
     tif->tif_row = (uint32) -1;     /* read/write pre-increment */
     tif->tif_clientdata = clientdata;
     if (!readproc || !writeproc || !seekproc || !closeproc || !sizeproc) {
         TIFFErrorExt(clientdata, module,
               "One of the client procedures is NULL pointer.");
         goto bad2;
     }
     tif->tif_readproc = readproc;
     tif->tif_writeproc = writeproc;
     tif->tif_seekproc = seekproc;
     tif->tif_closeproc = closeproc;
     tif->tif_sizeproc = sizeproc;
         if (mapproc)
         tif->tif_mapproc = mapproc;
     else
         tif->tif_mapproc = _tiffDummyMapProc;
     if (unmapproc)
         tif->tif_unmapproc = unmapproc;
     else
         tif->tif_unmapproc = _tiffDummyUnmapProc;
     _TIFFSetDefaultCompressionState(tif);   /* setup default state */
     /*
      * Default is to return data MSB2LSB and enable the
      * use of memory-mapped files and strip chopping when
      * a file is opened read-only.
      */
     tif->tif_flags = FILLORDER_MSB2LSB;
     if (m == O_RDONLY )
             tif->tif_flags |= TIFF_MAPPED;
 #ifdef STRIPCHOP_DEFAULT
     if (m == O_RDONLY || m == O_RDWR)
         tif->tif_flags |= STRIPCHOP_DEFAULT;
 #endif
     /*
      * Process library-specific flags in the open mode string.
      * The following flags may be used to control intrinsic library
      * behaviour that may or may not be desirable (usually for
      * compatibility with some application that claims to support
      * TIFF but only supports some braindead idea of what the
      * vendor thinks TIFF is):
      *
      * 'l'      use little-endian byte order for creating a file
      * 'b'      use big-endian byte order for creating a file
      * 'L'      read/write information using LSB2MSB bit order
      * 'B'      read/write information using MSB2LSB bit order
      * 'H'      read/write information using host bit order
      * 'M'      enable use of memory-mapped files when supported
      * 'm'      disable use of memory-mapped files
      * 'C'      enable strip chopping support when reading
      * 'c'      disable strip chopping support
      * 'h'      read TIFF header only, do not load the first IFD
      *
      * The use of the 'l' and 'b' flags is strongly discouraged.
      * These flags are provided solely because numerous vendors,
      * typically on the PC, do not correctly support TIFF; they
      * only support the Intel little-endian byte order.  This
      * support is not configured by default because it supports
      * the violation of the TIFF spec that says that readers *MUST*
      * support both byte orders.  It is strongly recommended that
      * you not use this feature except to deal with busted apps
      * that write invalid TIFF.  And even in those cases you should
      * bang on the vendors to fix their software.
      *
      * The 'L', 'B', and 'H' flags are intended for applications
      * that can optimize operations on data by using a particular
      * bit order.  By default the library returns data in MSB2LSB
      * bit order for compatibiltiy with older versions of this
      * library.  Returning data in the bit order of the native cpu
      * makes the most sense but also requires applications to check
      * the value of the FillOrder tag; something they probably do
      * not do right now.
      *
      * The 'M' and 'm' flags are provided because some virtual memory
      * systems exhibit poor behaviour when large images are mapped.
      * These options permit clients to control the use of memory-mapped
      * files on a per-file basis.
      *
      * The 'C' and 'c' flags are provided because the library support
      * for chopping up large strips into multiple smaller strips is not
      * application-transparent and as such can cause problems.  The 'c'
      * option permits applications that only want to look at the tags,
      * for example, to get the unadulterated TIFF tag information.
      */
     for (cp = mode; *cp; cp++)
         switch (*cp) {
         case 'b':
 #ifndef WORDS_BIGENDIAN
             if (m&O_CREAT)
                 tif->tif_flags |= TIFF_SWAB;
 #endif
             break;
         case 'l':
 #ifdef WORDS_BIGENDIAN
             if ((m&O_CREAT))
                 tif->tif_flags |= TIFF_SWAB;
 #endif
             break;
         case 'B':
             tif->tif_flags = (tif->tif_flags &~ TIFF_FILLORDER) |
                 FILLORDER_MSB2LSB;
             break;
         case 'L':
             tif->tif_flags = (tif->tif_flags &~ TIFF_FILLORDER) |
                 FILLORDER_LSB2MSB;
             break;
         case 'H':
             tif->tif_flags = (tif->tif_flags &~ TIFF_FILLORDER) |
                 HOST_FILLORDER;
             break;
         case 'M':
             if (m == O_RDONLY)
                 tif->tif_flags |= TIFF_MAPPED;
             break;
         case 'm':
             if (m == O_RDONLY)
                 tif->tif_flags &= ~TIFF_MAPPED;
             break;
         case 'C':
             if (m == O_RDONLY)
                 tif->tif_flags |= TIFF_STRIPCHOP;
             break;
         case 'c':
             if (m == O_RDONLY)
                 tif->tif_flags &= ~TIFF_STRIPCHOP;
             break;
         case 'h':
             tif->tif_flags |= TIFF_HEADERONLY;
             break;
         }
     /*
      * Read in TIFF header.
      */
     if (tif->tif_mode & O_TRUNC ||
         !ReadOK(tif, &tif->tif_header, sizeof (TIFFHeader))) {
         if (tif->tif_mode == O_RDONLY) {
             TIFFErrorExt(tif->tif_clientdata, name, "Cannot read TIFF header");
             goto bad;
         }
         /*
          * Setup header and write.
          */
 #ifdef WORDS_BIGENDIAN
         tif->tif_header.tiff_magic = tif->tif_flags & TIFF_SWAB
             ? TIFF_LITTLEENDIAN : TIFF_BIGENDIAN;
 #else
         tif->tif_header.tiff_magic = tif->tif_flags & TIFF_SWAB
             ? TIFF_BIGENDIAN : TIFF_LITTLEENDIAN;
 #endif
         tif->tif_header.tiff_version = TIFF_VERSION;
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&tif->tif_header.tiff_version);
         tif->tif_header.tiff_diroff = 0;    /* filled in later */
                 /*
                  * The doc for "fopen" for some STD_C_LIBs says that if you
                  * open a file for modify ("+"), then you must fseek (or
                  * fflush?) between any freads and fwrites.  This is not
                  * necessary on most systems, but has been shown to be needed
                  * on Solaris.
                  */
                 TIFFSeekFile( tif, 0, SEEK_SET );
         if (!WriteOK(tif, &tif->tif_header, sizeof (TIFFHeader))) {
             TIFFErrorExt(tif->tif_clientdata, name, "Error writing TIFF header");
             goto bad;
         }
         /*
          * Setup the byte order handling.
          */
         TIFFInitOrder(tif, tif->tif_header.tiff_magic);
         /*
          * Setup default directory.
          */
         if (!TIFFDefaultDirectory(tif))
             goto bad;
         tif->tif_diroff = 0;
         tif->tif_dirlist = NULL;
         tif->tif_dirnumber = 0;
         return (tif);
     }
     /*
      * Setup the byte order handling.
      */
     if (tif->tif_header.tiff_magic != TIFF_BIGENDIAN &&
         tif->tif_header.tiff_magic != TIFF_LITTLEENDIAN
 #if MDI_SUPPORT
         &&
 #if HOST_BIGENDIAN
         tif->tif_header.tiff_magic != MDI_BIGENDIAN
 #else
         tif->tif_header.tiff_magic != MDI_LITTLEENDIAN
 #endif
         ) {
         TIFFErrorExt(tif->tif_clientdata, name,  "Not a TIFF or MDI file, bad magic number %d (0x%x)",
 #else
         ) {
         TIFFErrorExt(tif->tif_clientdata, name,  "Not a TIFF file, bad magic number %d (0x%x)",
 #endif
             tif->tif_header.tiff_magic,
             tif->tif_header.tiff_magic);
         goto bad;
     }
     TIFFInitOrder(tif, tif->tif_header.tiff_magic);
     /*
      * Swap header if required.
      */
     if (tif->tif_flags & TIFF_SWAB) {
         TIFFSwabShort(&tif->tif_header.tiff_version);
         TIFFSwabLong(&tif->tif_header.tiff_diroff);
     }
     /*
      * Now check version (if needed, it's been byte-swapped).
      * Note that this isn't actually a version number, it's a
      * magic number that doesn't change (stupid).
      */
     if (tif->tif_header.tiff_version == TIFF_BIGTIFF_VERSION) {
         TIFFErrorExt(tif->tif_clientdata, name,
                           "This is a BigTIFF file.  This format not supported\n"
                           "by this version of libtiff." );
         goto bad;
     }
     if (tif->tif_header.tiff_version != TIFF_VERSION) {
         TIFFErrorExt(tif->tif_clientdata, name,
             "Not a TIFF file, bad version number %d (0x%x)",
             tif->tif_header.tiff_version,
             tif->tif_header.tiff_version);
         goto bad;
     }
     tif->tif_flags |= TIFF_MYBUFFER;
     tif->tif_rawcp = tif->tif_rawdata = 0;
     tif->tif_rawdatasize = 0;
     /*
      * Sometimes we do not want to read the first directory (for example,
      * it may be broken) and want to proceed to other directories. I this
      * case we use the TIFF_HEADERONLY flag to open file and return
      * immediately after reading TIFF header.
      */
     if (tif->tif_flags & TIFF_HEADERONLY)
         return (tif);
     /*
      * Setup initial directory.
      */
     switch (mode[0]) {
     case 'r':
         tif->tif_nextdiroff = tif->tif_header.tiff_diroff;
         /*
          * Try to use a memory-mapped file if the client
          * has not explicitly suppressed usage with the
          * 'm' flag in the open mode (see above).
          */
         if ((tif->tif_flags & TIFF_MAPPED) &&
     !TIFFMapFileContents(tif, (tdata_t*) &tif->tif_base, &tif->tif_size))
             tif->tif_flags &= ~TIFF_MAPPED;
         if (TIFFReadDirectory(tif)) {
             tif->tif_rawcc = -1;
             tif->tif_flags |= TIFF_BUFFERSETUP;
             return (tif);
         }
         break;
     case 'a':
         /*
          * New directories are automatically append
          * to the end of the directory chain when they
          * are written out (see TIFFWriteDirectory).
          */
         if (!TIFFDefaultDirectory(tif))
             goto bad;
         return (tif);
     }
 bad:
     tif->tif_mode = O_RDONLY;   /* XXX avoid flush */
         TIFFCleanup(tif);
 bad2:
     return ((TIFF*)0);
 }
void TIFFClose (TIFF * tif)
Close a previously opened TIFF file.
TIFFClose closes a file that was previously opened with TIFFOpen(). Any buffered data are flushed to the file, including the contents of the current directory (if modified); and all resources are reclaimed.
Parameters
tif A TIFF pointer.
Definition at line 111 of file tif_close.c.
References tiff::tif_clientdata, tiff::tif_closeproc, and TIFFCleanup().
Referenced by TIFFReaderInternal::Clean(), and rcWindow::tiff().
 {
     TIFFCloseProc closeproc = tif->tif_closeproc;
     thandle_t fd = tif->tif_clientdata;
     TIFFCleanup(tif);
     (void) (*closeproc)(fd);
 }
tstrip_t TIFFComputeStrip (TIFF * , uint32 , tsample_t)
Definition at line 68 of file tif_strip.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, and TIFFErrorExt().
Referenced by gtStripContig(), and gtStripSeparate().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tstrip_t strip;
     strip = row / td->td_rowsperstrip;
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
         if (sample >= td->td_samplesperpixel) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
                 "%lu: Sample out of range, max %lu",
                 (unsigned long) sample, (unsigned long) td->td_samplesperpixel);
             return ((tstrip_t) 0);
         }
         strip += sample*td->td_stripsperimage;
     }
     return (strip);
 }
ttile_t TIFFComputeTile (TIFF * , uint32 , uint32 , uint32 , tsample_t)
Definition at line 68 of file tif_tile.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_dir, and TIFFhowmany.
Referenced by TIFFReadTile(), and TIFFWriteTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     uint32 dx = td->td_tilewidth;
     uint32 dy = td->td_tilelength;
     uint32 dz = td->td_tiledepth;
     ttile_t tile = 1;
     if (td->td_imagedepth == 1)
         z = 0;
     if (dx == (uint32) -1)
         dx = td->td_imagewidth;
     if (dy == (uint32) -1)
         dy = td->td_imagelength;
     if (dz == (uint32) -1)
         dz = td->td_imagedepth;
     if (dx != 0 && dy != 0 && dz != 0) {
         uint32 xpt = TIFFhowmany(td->td_imagewidth, dx);
         uint32 ypt = TIFFhowmany(td->td_imagelength, dy);
         uint32 zpt = TIFFhowmany(td->td_imagedepth, dz);
         if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
             tile = (xpt*ypt*zpt)*s +
                  (xpt*ypt)*(z/dz) +
                  xpt*(y/dy) +
                  x/dx;
         else
             tile = (xpt*ypt)*(z/dz) + xpt*(y/dy) + x/dx;
     }
     return (tile);
 }
int TIFFCreateDirectory (TIFF *)
Definition at line 1013 of file tif_dir.c.
References tiff::tif_curoff, tiff::tif_curstrip, tiff::tif_diroff, tiff::tif_nextdiroff, tiff::tif_row, and TIFFDefaultDirectory().
Referenced by _TIFFWriteDirectory().
 {
     TIFFDefaultDirectory(tif);
     tif->tif_diroff = 0;
     tif->tif_nextdiroff = 0;
     tif->tif_curoff = 0;
     tif->tif_row = (uint32) -1;
     tif->tif_curstrip = (tstrip_t) -1;
     return 0;
 }
tdir_t TIFFCurrentDirectory (TIFF *)
Definition at line 563 of file tif_open.c.
References tiff::tif_curdir.
 {
     return (tif->tif_curdir);
 }
uint32 TIFFCurrentDirOffset (TIFF *)
Definition at line 1210 of file tif_dir.c.
References tiff::tif_diroff.
 {
     return (tif->tif_diroff);
 }
uint32 TIFFCurrentRow (TIFF *)
Definition at line 554 of file tif_open.c.
References tiff::tif_row.
 {
     return (tif->tif_row);
 }
tstrip_t TIFFCurrentStrip (TIFF *)
Definition at line 572 of file tif_open.c.
References tiff::tif_curstrip.
 {
     return (tif->tif_curstrip);
 }
ttile_t TIFFCurrentTile (TIFF *)
Definition at line 581 of file tif_open.c.
References tiff::tif_curtile.
 {
     return (tif->tif_curtile);
 }
int TIFFDataWidth (TIFFDataType)
Definition at line 620 of file tif_dirinfo.c.
Referenced by EstimateStripByteCounts(), TIFFFetchData(), TIFFFetchRationalArray(), TIFFWriteAnyArray(), and TIFFWriteData().
 {
     switch(type)
     {
     case 0:  /* nothing */
     case 1:  /* TIFF_BYTE */
     case 2:  /* TIFF_ASCII */
     case 6:  /* TIFF_SBYTE */
     case 7:  /* TIFF_UNDEFINED */
         return 1;
     case 3:  /* TIFF_SHORT */
     case 8:  /* TIFF_SSHORT */
         return 2;
     case 4:  /* TIFF_LONG */
     case 9:  /* TIFF_SLONG */
     case 11: /* TIFF_FLOAT */
         case 13: /* TIFF_IFD */
         return 4;
     case 5:  /* TIFF_RATIONAL */
     case 10: /* TIFF_SRATIONAL */
     case 12: /* TIFF_DOUBLE */
         return 8;
     default:
         return 0; /* will return 0 for unknown types */
     }
 }
uint32 TIFFDefaultStripSize (TIFF * , uint32)
Definition at line 197 of file tif_strip.c.
References tiff::tif_defstripsize.
Referenced by rcWindow::tiff().
 {
     return (*tif->tif_defstripsize)(tif, request);
 }
void TIFFDefaultTileSize (TIFF * , uint32 * , uint32 *)
Definition at line 245 of file tif_tile.c.
References tiff::tif_deftilesize.
 {
     (*tif->tif_deftilesize)(tif, tw, th);
 }
void TIFFError (const char * , const char * , ...)
Definition at line 51 of file tif_error.c.
References _TIFFerrorHandler, and _TIFFerrorHandlerExt.
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFerrorHandler)
         (*_TIFFerrorHandler)(module, fmt, ap);
     if (_TIFFerrorHandlerExt)
         (*_TIFFerrorHandlerExt)(0, module, fmt, ap);
     va_end(ap);
 }
void TIFFErrorExt (thandle_t , const char * , const char * , ...)
Definition at line 63 of file tif_error.c.
References _TIFFerrorHandler, and _TIFFerrorHandlerExt.
Referenced by _notConfigured(), _TIFFCheckMalloc(), _TIFFFieldWithName(), _TIFFFieldWithTag(), _TIFFgetMode(), _TIFFNoSeek(), _tiffSizeProc(), _TIFFVGetField(), _TIFFVSetField(), _TIFFWriteDirectory(), checkInkNamesString(), cvtRational(), DumpModeDecode(), EstimateStripByteCounts(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), initCIELabConversion(), initYCbCrConversion(), makebwmap(), makecmap(), MissingRequired(), multiply(), OkToChangeTag(), PredictorSetup(), setupMap(), summarize(), TIFFAdvanceDirectory(), TIFFAppendToStrip(), TIFFCheckRead(), TIFFCheckTile(), TIFFClientOpen(), TIFFComputeStrip(), TIFFFetchAnyArray(), TIFFFetchData(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFFillStrip(), TIFFFillTile(), TIFFGrowStrips(), TIFFLinkDirectory(), TIFFNoDecode(), TIFFNoEncode(), TIFFOpen(), TIFFRawStripSize(), TIFFReadBufferSetup(), TIFFReadCustomDirectory(), TIFFReadDirectory(), TIFFReadEncodedStrip(), TIFFReadEncodedTile(), TIFFReadRawStrip(), TIFFReadRawStrip1(), TIFFReadRawTile(), TIFFReadRawTile1(), TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), TIFFRegisterCODEC(), TIFFRewriteDirectory(), TIFFRGBAImageGet(), TIFFSeek(), TIFFUnlinkDirectory(), TIFFUnRegisterCODEC(), TIFFVGetFieldDefaulted(), TIFFVStripSize(), TIFFVTileSize(), TIFFWriteAnyArray(), TIFFWriteBufferSetup(), TIFFWriteCheck(), TIFFWriteData(), TIFFWriteEncodedStrip(), TIFFWriteEncodedTile(), TIFFWritePerSampleAnys(), TIFFWritePerSampleShorts(), TIFFWriteRationalArray(), TIFFWriteRawStrip(), TIFFWriteRawTile(), and TIFFWriteScanline().
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFerrorHandler)
         (*_TIFFerrorHandler)(module, fmt, ap);
     if (_TIFFerrorHandlerExt)
         (*_TIFFerrorHandlerExt)(fd, module, fmt, ap);
     va_end(ap);
 }
TIFF* TIFFFdOpen (int , const char * , const char *)
Definition at line 134 of file tif_apple.c.
References _tiffCloseProc(), _tiffMapProc(), _tiffReadProc(), _tiffSeekProc(), _tiffSizeProc(), _tiffUnmapProc(), _tiffWriteProc(), tiff::tif_fd, and TIFFClientOpen().
Referenced by TIFFOpen().
 {
     TIFF* tif;
     tif = TIFFClientOpen(name, mode, (thandle_t) fd,
         _tiffReadProc, _tiffWriteProc, _tiffSeekProc, _tiffCloseProc,
         _tiffSizeProc, _tiffMapProc, _tiffUnmapProc);
     if (tif)
         tif->tif_fd = fd;
     return (tif);
 }
const TIFFFieldInfo* TIFFFieldWithName (TIFF * , const char *)
const TIFFFieldInfo* TIFFFieldWithTag (TIFF * , ttag_t)
Referenced by TIFFReaderInternal::Open(), and TIFFPrintDirectory().
const char* TIFFFileName (TIFF *)
Definition at line 464 of file tif_open.c.
References tiff::tif_name.
Referenced by buildMap(), gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), makebwmap(), makecmap(), setupMap(), TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), and TIFFRGBAImageGet().
 {
     return (tif->tif_name);
 }
int TIFFFileno (TIFF *)
Definition at line 484 of file tif_open.c.
References tiff::tif_fd.
 {
     return (tif->tif_fd);
 }
const TIFFCodec* TIFFFindCODEC (uint16)
Definition at line 177 of file tif_compress.c.
References _TIFFBuiltinCODECS, _codec::info, TIFFCodec::name, _codec::next, and TIFFCodec::scheme.
Referenced by _notConfigured(), TIFFIsCODECConfigured(), TIFFNoDecode(), TIFFNoEncode(), TIFFPrintDirectory(), and TIFFSetCompressionScheme().
 {
     const TIFFCodec* c;
     codec_t* cd;
     for (cd = registeredCODECS; cd; cd = cd->next)
         if (cd->info->scheme == scheme)
             return ((const TIFFCodec*) cd->info);
     for (c = _TIFFBuiltinCODECS; c->name; c++)
         if (c->scheme == scheme)
             return (c);
     return ((const TIFFCodec*) 0);
 }
const TIFFFieldInfo* TIFFFindFieldInfo (TIFF * , ttag_t , TIFFDataType)
const TIFFFieldInfo* TIFFFindFieldInfoByName (TIFF * , const char * , TIFFDataType)
int TIFFFlush (TIFF *)
Definition at line 33 of file tif_flush.c.
References tiff::tif_flags, tiff::tif_mode, TIFF_DIRTYDIRECT, TIFFFlushData(), and TIFFWriteDirectory().
Referenced by TIFFCleanup().
 {
     if (tif->tif_mode != O_RDONLY) {
         if (!TIFFFlushData(tif))
             return (0);
         if ((tif->tif_flags & TIFF_DIRTYDIRECT) &&
             !TIFFWriteDirectory(tif))
             return (0);
     }
     return (1);
 }
int TIFFFlushData (TIFF *)
Definition at line 56 of file tif_flush.c.
References tiff::tif_flags, tiff::tif_postencode, TIFF_BEENWRITING, TIFF_POSTENCODE, and TIFFFlushData1().
Referenced by TIFFFlush(), and TIFFWriteScanline().
 {
     if ((tif->tif_flags & TIFF_BEENWRITING) == 0)
         return (0);
     if (tif->tif_flags & TIFF_POSTENCODE) {
         tif->tif_flags &= ~TIFF_POSTENCODE;
         if (!(*tif->tif_postencode)(tif))
             return (0);
     }
     return (TIFFFlushData1(tif));
 }
void TIFFFreeDirectory (TIFF *)
Definition at line 961 of file tif_dir.c.
References _TIFFfree(), _TIFFmemset(), CleanupField, FIELD_SETLONGS, FIELD_YCBCRPOSITIONING, FIELD_YCBCRSUBSAMPLING, TIFFDirectory::td_customValueCount, TIFFDirectory::td_customValues, TIFFDirectory::td_fieldsset, tiff::tif_dir, TIFFClrFieldBit, and _TIFFTagValue::value.
Referenced by _TIFFWriteDirectory(), TIFFCleanup(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFUnlinkDirectory().
 {
     TIFFDirectory *td = &tif->tif_dir;
     int            i;
     _TIFFmemset(td->td_fieldsset, 0, FIELD_SETLONGS);
     CleanupField(td_colormap[0]);
     CleanupField(td_colormap[1]);
     CleanupField(td_colormap[2]);
     CleanupField(td_sampleinfo);
     CleanupField(td_subifd);
     CleanupField(td_inknames);
     CleanupField(td_transferfunction[0]);
     CleanupField(td_transferfunction[1]);
     CleanupField(td_transferfunction[2]);
     CleanupField(td_stripoffset);
     CleanupField(td_stripbytecount);
     TIFFClrFieldBit(tif, FIELD_YCBCRSUBSAMPLING);
     TIFFClrFieldBit(tif, FIELD_YCBCRPOSITIONING);
     /* Cleanup custom tag values */
     for( i = 0; i < td->td_customValueCount; i++ ) {
         if (td->td_customValues[i].value)
             _TIFFfree(td->td_customValues[i].value);
     }
     td->td_customValueCount = 0;
     CleanupField(td_customValues);
 }
const unsigned char* TIFFGetBitRevTable (int)
Definition at line 212 of file tif_swab.c.
References TIFFBitRevTable, and TIFFNoBitRevTable.
 {
     return (reversed ? TIFFBitRevTable : TIFFNoBitRevTable);
 }
void* TIFFGetClientInfo (TIFF * , const char *)
Definition at line 66 of file tif_extension.c.
References client_info::data, client_info::name, client_info::next, NULL, and tiff::tif_clientinfo.
 {
     TIFFClientInfoLink *link = tif->tif_clientinfo;
     while( link != NULL && strcmp(link->name,name) != 0 )
         link = link->next;
     if( link != NULL )
         return link->data;
     else
         return NULL;
 }
TIFFCloseProc TIFFGetCloseProc (TIFF *)
Definition at line 653 of file tif_open.c.
References tiff::tif_closeproc.
 {
     return (tif->tif_closeproc);
 }
TIFFCodec* TIFFGetConfiguredCODECs (void)
Get list of configured codecs, both built-in and registered by user. Caller is responsible to free this structure.
Returns
returns array of TIFFCodec records (the last record should be NULL) or NULL if function failed.
Definition at line 243 of file tif_compress.c.
References _TIFFBuiltinCODECS, _TIFFfree(), _TIFFmemcpy(), _TIFFmemset(), _TIFFrealloc(), TIFFCodec::name, _codec::next, NULL, TIFFCodec::scheme, and TIFFIsCODECConfigured().
 {
     int     i = 1;
         codec_t     *cd;
         const TIFFCodec *c;
     TIFFCodec   *codecs = NULL, *new_codecs;
         for (cd = registeredCODECS; cd; cd = cd->next) {
                 new_codecs = (TIFFCodec *)
             _TIFFrealloc(codecs, i * sizeof(TIFFCodec));
         if (!new_codecs) {
             _TIFFfree (codecs);
             return NULL;
         }
         codecs = new_codecs;
         _TIFFmemcpy(codecs + i - 1, cd, sizeof(TIFFCodec));
         i++;
     }
         for (c = _TIFFBuiltinCODECS; c->name; c++) {
                 if (TIFFIsCODECConfigured(c->scheme)) {
                         new_codecs = (TIFFCodec *)
                 _TIFFrealloc(codecs, i * sizeof(TIFFCodec));
             if (!new_codecs) {
                 _TIFFfree (codecs);
                 return NULL;
             }
             codecs = new_codecs;
             _TIFFmemcpy(codecs + i - 1, (const tdata_t)c, sizeof(TIFFCodec));
             i++;
         }
     }
     new_codecs = (TIFFCodec *) _TIFFrealloc(codecs, i * sizeof(TIFFCodec));
     if (!new_codecs) {
         _TIFFfree (codecs);
         return NULL;
     }
     codecs = new_codecs;
     _TIFFmemset(codecs + i - 1, 0, sizeof(TIFFCodec));
         return codecs;
 }
int TIFFGetField (TIFF * , ttag_t , ...)
Definition at line 925 of file tif_dir.c.
References TIFFVGetField().
Referenced by TIFFImageIO::GetColor(), gtTileContig(), gtTileSeparate(), TIFFReaderInternal::Initialize(), isCCITTCompression(), TIFFReaderInternal::Open(), TIFFPrintDirectory(), TIFFRGBAImageBegin(), TIFFRGBAImageOK(), TIFFSetupShortPair(), TIFFVStripSize(), TIFFWriteNormalTag(), TIFFWritePerSampleAnys(), and TIFFWritePerSampleShorts().
 {
     int status;
     va_list ap;
     va_start(ap, tag);
     status = TIFFVGetField(tif, tag, ap);
     va_end(ap);
     return (status);
 }
int TIFFGetFieldDefaulted (TIFF * , ttag_t , ...)
Definition at line 256 of file tif_aux.c.
References TIFFVGetFieldDefaulted().
Referenced by gtStripContig(), gtStripSeparate(), initCIELabConversion(), TIFFReaderInternal::Initialize(), initYCbCrConversion(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), TIFFRGBAImageBegin(), and TIFFRGBAImageOK().
 {
     int ok;
     va_list ap;
     va_start(ap, tag);
     ok =  TIFFVGetFieldDefaulted(tif, tag, ap);
     va_end(ap);
     return (ok);
 }
TIFFMapFileProc TIFFGetMapFileProc (TIFF *)
Definition at line 671 of file tif_open.c.
References tiff::tif_mapproc.
 {
     return (tif->tif_mapproc);
 }
int TIFFGetMode (TIFF *)
Definition at line 524 of file tif_open.c.
References tiff::tif_mode.
 {
     return (tif->tif_mode);
 }
TIFFReadWriteProc TIFFGetReadProc (TIFF *)
Definition at line 626 of file tif_open.c.
References tiff::tif_readproc.
 {
     return (tif->tif_readproc);
 }
TIFFSeekProc TIFFGetSeekProc (TIFF *)
Definition at line 644 of file tif_open.c.
References tiff::tif_seekproc.
 {
     return (tif->tif_seekproc);
 }
TIFFSizeProc TIFFGetSizeProc (TIFF *)
Definition at line 662 of file tif_open.c.
References tiff::tif_sizeproc.
 {
     return (tif->tif_sizeproc);
 }
int TIFFGetTagListCount (TIFF *)
Definition at line 36 of file tif_extension.c.
References TIFFDirectory::td_customValueCount, and tiff::tif_dir.
Referenced by TIFFReaderInternal::Open(), and TIFFPrintDirectory().
 {
     TIFFDirectory* td = &tif->tif_dir;
     return td->td_customValueCount;
 }
ttag_t TIFFGetTagListEntry (TIFF * , int tag_index)
Definition at line 44 of file tif_extension.c.
References TIFFFieldInfo::field_tag, _TIFFTagValue::info, TIFFDirectory::td_customValueCount, TIFFDirectory::td_customValues, and tiff::tif_dir.
Referenced by TIFFReaderInternal::Open(), and TIFFPrintDirectory().
 {
     TIFFDirectory* td = &tif->tif_dir;
     if( tag_index < 0 || tag_index >= td->td_customValueCount )
         return (ttag_t) -1;
     else
         return td->td_customValues[tag_index].info->field_tag;
 }
TIFFUnmapFileProc TIFFGetUnmapFileProc (TIFF *)
Definition at line 680 of file tif_open.c.
References tiff::tif_unmapproc.
 {
     return (tif->tif_unmapproc);
 }
const char* TIFFGetVersion (void)
Definition at line 30 of file tif_version.c.
References TIFFVersion.
 {
     return (TIFFVersion);
 }
TIFFReadWriteProc TIFFGetWriteProc (TIFF *)
Definition at line 635 of file tif_open.c.
References tiff::tif_writeproc.
 {
     return (tif->tif_writeproc);
 }
int TIFFIsBigEndian (TIFF *)
Definition at line 617 of file tif_open.c.
References tiff::tif_header, TIFF_BIGENDIAN, and TIFFHeader::tiff_magic.
Referenced by TIFFImageIO::ReadImageInformation().
 {
     return (tif->tif_header.tiff_magic == TIFF_BIGENDIAN);
 }
int TIFFIsByteSwapped (TIFF *)
Definition at line 590 of file tif_open.c.
References tiff::tif_flags, and TIFF_SWAB.
 {
     return ((tif->tif_flags & TIFF_SWAB) != 0);
 }
int TIFFIsCODECConfigured (uint16 scheme)
Check whether we have working codec for the specific coding scheme.
Returns
returns 1 if the codec is configured and working. Otherwise 0 will be returned.
Definition at line 135 of file tif_codec.c.
References TIFFCodec::init, NotConfigured(), NULL, and TIFFFindCODEC().
Referenced by TIFFGetConfiguredCODECs().
 {
     const TIFFCodec* codec = TIFFFindCODEC(scheme);
     if(codec == NULL) {
             return 0;
         }
         if(codec->init == NULL) {
             return 0;
         }
     if(codec->init != NotConfigured){
             return 1;
         }
     return 0;
 }
int TIFFIsMSB2LSB (TIFF *)
Definition at line 608 of file tif_open.c.
References FILLORDER_MSB2LSB, and isFillOrder.
 {
     return (isFillOrder(tif, FILLORDER_MSB2LSB));
 }
int TIFFIsTiled (TIFF *)
Definition at line 545 of file tif_open.c.
References isTiled.
Referenced by TIFFReaderInternal::Initialize(), TIFFReadRGBAStrip(), TIFFReadRGBATile(), and TIFFRGBAImageBegin().
 {
     return (isTiled(tif));
 }
int TIFFIsUpSampled (TIFF *)
Definition at line 599 of file tif_open.c.
References isUpSampled.
 {
     return (isUpSampled(tif));
 }
int TIFFLastDirectory (TIFF *)
Definition at line 1220 of file tif_dir.c.
References tiff::tif_nextdiroff.
 {
     return (tif->tif_nextdiroff == 0);
 }
void TIFFMergeFieldInfo (TIFF * , const TIFFFieldInfo [], int)
Referenced by TIFFReadCustomDirectory(), and TIFFReadDirectory().
tdir_t TIFFNumberOfDirectories (TIFF *)
Definition at line 1149 of file tif_dir.c.
References NULL, tiff::tif_header, TIFFHeader::tiff_diroff, and TIFFAdvanceDirectory().
 {
     toff_t nextdir = tif->tif_header.tiff_diroff;
     tdir_t n = 0;
     while (nextdir != 0 && TIFFAdvanceDirectory(tif, &nextdir, NULL))
         n++;
     return (n);
 }
tstrip_t TIFFNumberOfStrips (TIFF *)
Definition at line 90 of file tif_strip.c.
References multiply(), PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagelength, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, tiff::tif_dir, and TIFFhowmany.
Referenced by TIFFReadDirectory(), and TIFFSetupStrips().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tstrip_t nstrips;
     nstrips = (td->td_rowsperstrip == (uint32) -1 ? 1 :
          TIFFhowmany(td->td_imagelength, td->td_rowsperstrip));
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
         nstrips = multiply(tif, nstrips, td->td_samplesperpixel,
                    "TIFFNumberOfStrips");
     return (nstrips);
 }
ttile_t TIFFNumberOfTiles (TIFF *)
Definition at line 137 of file tif_tile.c.
References multiply(), PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_dir, and TIFFhowmany.
Referenced by TIFFReaderInternal::Initialize(), TIFFReadDirectory(), and TIFFSetupStrips().
 {
     TIFFDirectory *td = &tif->tif_dir;
     uint32 dx = td->td_tilewidth;
     uint32 dy = td->td_tilelength;
     uint32 dz = td->td_tiledepth;
     ttile_t ntiles;
     if (dx == (uint32) -1)
         dx = td->td_imagewidth;
     if (dy == (uint32) -1)
         dy = td->td_imagelength;
     if (dz == (uint32) -1)
         dz = td->td_imagedepth;
     ntiles = (dx == 0 || dy == 0 || dz == 0) ? 0 :
         multiply(tif, multiply(tif, TIFFhowmany(td->td_imagewidth, dx),
                    TIFFhowmany(td->td_imagelength, dy),
                    "TIFFNumberOfTiles"),
              TIFFhowmany(td->td_imagedepth, dz), "TIFFNumberOfTiles");
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
         ntiles = multiply(tif, ntiles, td->td_samplesperpixel,
                   "TIFFNumberOfTiles");
     return (ntiles);
 }
TIFF* TIFFOpen (const char * , const char *)
Definition at line 157 of file tif_apple.c.
References _TIFFgetMode(), close(), O_BINARY, ourc2pstr(), TIFFErrorExt(), and TIFFFdOpen().
Referenced by TIFFReaderInternal::Open(), and rcWindow::tiff().
 {
     static const char module[] = "TIFFOpen";
     Str255 pname;
     FInfo finfo;
     short fref;
     OSErr err;
     FSSpec  fSpec;
     strcpy((char*) pname, name);
     ourc2pstr((char*) pname);
     err = FSMakeFSSpec( 0, 0, pname, &fSpec );
     switch (_TIFFgetMode(mode, module)) {
     default:
         return ((TIFF*) 0);
     case O_RDWR | O_CREAT | O_TRUNC:
         if (FSpGetFInfo(&fSpec, &finfo) == noErr)
             FSpDelete(&fSpec);
         /* fall through */
     case O_RDWR | O_CREAT:
         if ((err = FSpGetFInfo(&fSpec, &finfo)) == fnfErr) {
             if (FSpCreate(&fSpec, '    ', 'TIFF', smSystemScript) != noErr)
                 goto badCreate;
             if (FSpOpenDF(&fSpec, fsRdWrPerm, &fref) != noErr)
                 goto badOpen;
         } else if (err == noErr) {
             if (FSpOpenDF(&fSpec, fsRdWrPerm, &fref) != noErr)
                 goto badOpen;
         } else
             goto badOpen;
         break;
     case O_RDONLY:
         if (FSpOpenDF(&fSpec, fsRdPerm, &fref) != noErr)
             goto badOpen;
         break;
     case O_RDWR:
         if (FSpOpenDF(&fSpec, fsRdWrPerm, &fref) != noErr)
             goto badOpen;
         break;
     }
     return (TIFFFdOpen((int) fref, name, mode));
 badCreate:
     TIFFErrorExt(0, module, "%s: Cannot create", name);
     return ((TIFF*) 0);
 badOpen:
     TIFFErrorExt(0, module, "%s: Cannot open", name);
     return ((TIFF*) 0);
 }
void TIFFPrintDirectory (TIFF * , FILE * , long)
Definition at line 195 of file tif_print.c.
References _TIFFDataSize(), _TIFFfree(), _TIFFmalloc(), _TIFFPrettyPrintField(), _TIFFprintAscii(), _TIFFPrintField(), count(), EXTRASAMPLE_ASSOCALPHA, EXTRASAMPLE_UNASSALPHA, EXTRASAMPLE_UNSPECIFIED, FIELD_BITSPERSAMPLE, FIELD_COLORMAP, FIELD_COMPRESSION, FIELD_EXTRASAMPLES, FIELD_FILLORDER, FIELD_HALFTONEHINTS, FIELD_IMAGEDEPTH, FIELD_IMAGEDIMENSIONS, FIELD_INKNAMES, FIELD_MAXSAMPLEVALUE, FIELD_MINSAMPLEVALUE, FIELD_ORIENTATION, FIELD_PAGENUMBER, TIFFFieldInfo::field_passcount, FIELD_PHOTOMETRIC, FIELD_PLANARCONFIG, FIELD_POSITION, TIFFFieldInfo::field_readcount, FIELD_RESOLUTION, FIELD_RESOLUTIONUNIT, FIELD_ROWSPERSTRIP, FIELD_SAMPLEFORMAT, FIELD_SAMPLESPERPIXEL, FIELD_SMAXSAMPLEVALUE, FIELD_SMINSAMPLEVALUE, FIELD_STRIPOFFSETS, FIELD_SUBFILETYPE, FIELD_SUBIFD, FIELD_THRESHHOLDING, FIELD_TILEDEPTH, FIELD_TILEDIMENSIONS, FIELD_TRANSFERFUNCTION, TIFFFieldInfo::field_type, FIELD_YCBCRPOSITIONING, FIELD_YCBCRSUBSAMPLING, FILETYPE_MASK, FILETYPE_PAGE, FILETYPE_REDUCEDIMAGE, FILLORDER_LSB2MSB, FILLORDER_MSB2LSB, isTiled, TIFFCodec::name, NORIENTNAMES, NPHOTONAMES, NULL, orientNames, PHOTOMETRIC_LOGL, PHOTOMETRIC_LOGLUV, photoNames, PLANARCONFIG_CONTIG, PLANARCONFIG_SEPARATE, TIFFTagMethods::printdir, RESUNIT_CENTIMETER, RESUNIT_INCH, RESUNIT_NONE, SAMPLEFORMAT_COMPLEXIEEEFP, SAMPLEFORMAT_COMPLEXINT, SAMPLEFORMAT_IEEEFP, SAMPLEFORMAT_INT, SAMPLEFORMAT_UINT, SAMPLEFORMAT_VOID, TIFFDirectory::td_bitspersample, TIFFDirectory::td_colormap, TIFFDirectory::td_compression, TIFFDirectory::td_extrasamples, TIFFDirectory::td_fillorder, TIFFDirectory::td_halftonehints, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_inknames, TIFFDirectory::td_maxsamplevalue, TIFFDirectory::td_minsamplevalue, TIFFDirectory::td_nstrips, TIFFDirectory::td_nsubifd, TIFFDirectory::td_orientation, TIFFDirectory::td_pagenumber, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, TIFFDirectory::td_resolutionunit, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_sampleformat, TIFFDirectory::td_sampleinfo, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_smaxsamplevalue, TIFFDirectory::td_sminsamplevalue, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripoffset, TIFFDirectory::td_subfiletype, TIFFDirectory::td_subifd, TIFFDirectory::td_threshholding, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, TIFFDirectory::td_transferfunction, TIFFDirectory::td_xposition, TIFFDirectory::td_xresolution, TIFFDirectory::td_ycbcrpositioning, TIFFDirectory::td_yposition, TIFFDirectory::td_yresolution, THRESHHOLD_BILEVEL, THRESHHOLD_ERRORDIFFUSE, THRESHHOLD_HALFTONE, tiff::tif_dir, tiff::tif_diroff, tiff::tif_tagmethods, TIFF_ASCII, TIFF_SPP, TIFF_VARIABLE, TIFF_VARIABLE2, TIFFFieldSet, TIFFFieldWithTag(), TIFFFindCODEC(), TIFFGetField(), TIFFGetTagListCount(), TIFFGetTagListEntry(), TIFFPRINT_COLORMAP, TIFFPRINT_CURVES, TIFFPRINT_STRIPS, TIFFTAG_YCBCRSUBSAMPLING, YCBCRPOSITION_CENTERED, and YCBCRPOSITION_COSITED.
 {
     TIFFDirectory *td = &tif->tif_dir;
     char *sep;
     uint16 i;
     long l, n;
     fprintf(fd, "TIFF Directory at offset 0x%lx (%lu)\n",
         (unsigned long)tif->tif_diroff, (unsigned long)tif->tif_diroff);
     if (TIFFFieldSet(tif,FIELD_SUBFILETYPE)) {
         fprintf(fd, "  Subfile Type:");
         sep = " ";
         if (td->td_subfiletype & FILETYPE_REDUCEDIMAGE) {
             fprintf(fd, "%sreduced-resolution image", sep);
             sep = "/";
         }
         if (td->td_subfiletype & FILETYPE_PAGE) {
             fprintf(fd, "%smulti-page document", sep);
             sep = "/";
         }
         if (td->td_subfiletype & FILETYPE_MASK)
             fprintf(fd, "%stransparency mask", sep);
         fprintf(fd, " (%lu = 0x%lx)\n",
             (long) td->td_subfiletype, (long) td->td_subfiletype);
     }
     if (TIFFFieldSet(tif,FIELD_IMAGEDIMENSIONS)) {
         fprintf(fd, "  Image Width: %lu Image Length: %lu",
             (unsigned long) td->td_imagewidth, (unsigned long) td->td_imagelength);
         if (TIFFFieldSet(tif,FIELD_IMAGEDEPTH))
             fprintf(fd, " Image Depth: %lu",
                 (unsigned long) td->td_imagedepth);
         fprintf(fd, "\n");
     }
     if (TIFFFieldSet(tif,FIELD_TILEDIMENSIONS)) {
         fprintf(fd, "  Tile Width: %lu Tile Length: %lu",
             (unsigned long) td->td_tilewidth, (unsigned long) td->td_tilelength);
         if (TIFFFieldSet(tif,FIELD_TILEDEPTH))
             fprintf(fd, " Tile Depth: %lu",
                 (unsigned long) td->td_tiledepth);
         fprintf(fd, "\n");
     }
     if (TIFFFieldSet(tif,FIELD_RESOLUTION)) {
         fprintf(fd, "  Resolution: %g, %g",
             td->td_xresolution, td->td_yresolution);
         if (TIFFFieldSet(tif,FIELD_RESOLUTIONUNIT)) {
             switch (td->td_resolutionunit) {
             case RESUNIT_NONE:
                 fprintf(fd, " (unitless)");
                 break;
             case RESUNIT_INCH:
                 fprintf(fd, " pixels/inch");
                 break;
             case RESUNIT_CENTIMETER:
                 fprintf(fd, " pixels/cm");
                 break;
             default:
                 fprintf(fd, " (unit %u = 0x%x)",
                     td->td_resolutionunit,
                     td->td_resolutionunit);
                 break;
             }
         }
         fprintf(fd, "\n");
     }
     if (TIFFFieldSet(tif,FIELD_POSITION))
         fprintf(fd, "  Position: %g, %g\n",
             td->td_xposition, td->td_yposition);
     if (TIFFFieldSet(tif,FIELD_BITSPERSAMPLE))
         fprintf(fd, "  Bits/Sample: %u\n", td->td_bitspersample);
     if (TIFFFieldSet(tif,FIELD_SAMPLEFORMAT)) {
         fprintf(fd, "  Sample Format: ");
         switch (td->td_sampleformat) {
         case SAMPLEFORMAT_VOID:
             fprintf(fd, "void\n");
             break;
         case SAMPLEFORMAT_INT:
             fprintf(fd, "signed integer\n");
             break;
         case SAMPLEFORMAT_UINT:
             fprintf(fd, "unsigned integer\n");
             break;
         case SAMPLEFORMAT_IEEEFP:
             fprintf(fd, "IEEE floating point\n");
             break;
         case SAMPLEFORMAT_COMPLEXINT:
             fprintf(fd, "complex signed integer\n");
             break;
         case SAMPLEFORMAT_COMPLEXIEEEFP:
             fprintf(fd, "complex IEEE floating point\n");
             break;
         default:
             fprintf(fd, "%u (0x%x)\n",
                 td->td_sampleformat, td->td_sampleformat);
             break;
         }
     }
     if (TIFFFieldSet(tif,FIELD_COMPRESSION)) {
         const TIFFCodec* c = TIFFFindCODEC(td->td_compression);
         fprintf(fd, "  Compression Scheme: ");
         if (c)
             fprintf(fd, "%s\n", c->name);
         else
             fprintf(fd, "%u (0x%x)\n",
                 td->td_compression, td->td_compression);
     }
     if (TIFFFieldSet(tif,FIELD_PHOTOMETRIC)) {
         fprintf(fd, "  Photometric Interpretation: ");
         if (td->td_photometric < NPHOTONAMES)
             fprintf(fd, "%s\n", photoNames[td->td_photometric]);
         else {
             switch (td->td_photometric) {
             case PHOTOMETRIC_LOGL:
                 fprintf(fd, "CIE Log2(L)\n");
                 break;
             case PHOTOMETRIC_LOGLUV:
                 fprintf(fd, "CIE Log2(L) (u',v')\n");
                 break;
             default:
                 fprintf(fd, "%u (0x%x)\n",
                     td->td_photometric, td->td_photometric);
                 break;
             }
         }
     }
     if (TIFFFieldSet(tif,FIELD_EXTRASAMPLES) && td->td_extrasamples) {
         fprintf(fd, "  Extra Samples: %u<", td->td_extrasamples);
         sep = "";
         for (i = 0; i < td->td_extrasamples; i++) {
             switch (td->td_sampleinfo[i]) {
             case EXTRASAMPLE_UNSPECIFIED:
                 fprintf(fd, "%sunspecified", sep);
                 break;
             case EXTRASAMPLE_ASSOCALPHA:
                 fprintf(fd, "%sassoc-alpha", sep);
                 break;
             case EXTRASAMPLE_UNASSALPHA:
                 fprintf(fd, "%sunassoc-alpha", sep);
                 break;
             default:
                 fprintf(fd, "%s%u (0x%x)", sep,
                     td->td_sampleinfo[i], td->td_sampleinfo[i]);
                 break;
             }
             sep = ", ";
         }
         fprintf(fd, ">\n");
     }
     if (TIFFFieldSet(tif,FIELD_INKNAMES)) {
         char* cp;
         fprintf(fd, "  Ink Names: ");
         i = td->td_samplesperpixel;
         sep = "";
         for (cp = td->td_inknames; i > 0; cp = strchr(cp,'\0')+1, i--) {
             fputs(sep, fd);
             _TIFFprintAscii(fd, cp);
             sep = ", ";
         }
                 fputs("\n", fd);
     }
     if (TIFFFieldSet(tif,FIELD_THRESHHOLDING)) {
         fprintf(fd, "  Thresholding: ");
         switch (td->td_threshholding) {
         case THRESHHOLD_BILEVEL:
             fprintf(fd, "bilevel art scan\n");
             break;
         case THRESHHOLD_HALFTONE:
             fprintf(fd, "halftone or dithered scan\n");
             break;
         case THRESHHOLD_ERRORDIFFUSE:
             fprintf(fd, "error diffused\n");
             break;
         default:
             fprintf(fd, "%u (0x%x)\n",
                 td->td_threshholding, td->td_threshholding);
             break;
         }
     }
     if (TIFFFieldSet(tif,FIELD_FILLORDER)) {
         fprintf(fd, "  FillOrder: ");
         switch (td->td_fillorder) {
         case FILLORDER_MSB2LSB:
             fprintf(fd, "msb-to-lsb\n");
             break;
         case FILLORDER_LSB2MSB:
             fprintf(fd, "lsb-to-msb\n");
             break;
         default:
             fprintf(fd, "%u (0x%x)\n",
                 td->td_fillorder, td->td_fillorder);
             break;
         }
     }
     if (TIFFFieldSet(tif,FIELD_YCBCRSUBSAMPLING))
         {
             /*
              * For hacky reasons (see tif_jpeg.c - JPEGFixupTestSubsampling),
              * we need to fetch this rather than trust what is in our
              * structures.
              */
             uint16 subsampling[2];
             TIFFGetField( tif, TIFFTAG_YCBCRSUBSAMPLING,
                           subsampling + 0, subsampling + 1 );
         fprintf(fd, "  YCbCr Subsampling: %u, %u\n",
                         subsampling[0], subsampling[1] );
         }
     if (TIFFFieldSet(tif,FIELD_YCBCRPOSITIONING)) {
         fprintf(fd, "  YCbCr Positioning: ");
         switch (td->td_ycbcrpositioning) {
         case YCBCRPOSITION_CENTERED:
             fprintf(fd, "centered\n");
             break;
         case YCBCRPOSITION_COSITED:
             fprintf(fd, "cosited\n");
             break;
         default:
             fprintf(fd, "%u (0x%x)\n",
                 td->td_ycbcrpositioning, td->td_ycbcrpositioning);
             break;
         }
     }
     if (TIFFFieldSet(tif,FIELD_HALFTONEHINTS))
         fprintf(fd, "  Halftone Hints: light %u dark %u\n",
             td->td_halftonehints[0], td->td_halftonehints[1]);
     if (TIFFFieldSet(tif,FIELD_ORIENTATION)) {
         fprintf(fd, "  Orientation: ");
         if (td->td_orientation < NORIENTNAMES)
             fprintf(fd, "%s\n", orientNames[td->td_orientation]);
         else
             fprintf(fd, "%u (0x%x)\n",
                 td->td_orientation, td->td_orientation);
     }
     if (TIFFFieldSet(tif,FIELD_SAMPLESPERPIXEL))
         fprintf(fd, "  Samples/Pixel: %u\n", td->td_samplesperpixel);
     if (TIFFFieldSet(tif,FIELD_ROWSPERSTRIP)) {
         fprintf(fd, "  Rows/Strip: ");
         if (td->td_rowsperstrip == (uint32) -1)
             fprintf(fd, "(infinite)\n");
         else
             fprintf(fd, "%lu\n", (unsigned long) td->td_rowsperstrip);
     }
     if (TIFFFieldSet(tif,FIELD_MINSAMPLEVALUE))
         fprintf(fd, "  Min Sample Value: %u\n", td->td_minsamplevalue);
     if (TIFFFieldSet(tif,FIELD_MAXSAMPLEVALUE))
         fprintf(fd, "  Max Sample Value: %u\n", td->td_maxsamplevalue);
     if (TIFFFieldSet(tif,FIELD_SMINSAMPLEVALUE))
         fprintf(fd, "  SMin Sample Value: %g\n",
             td->td_sminsamplevalue);
     if (TIFFFieldSet(tif,FIELD_SMAXSAMPLEVALUE))
         fprintf(fd, "  SMax Sample Value: %g\n",
             td->td_smaxsamplevalue);
     if (TIFFFieldSet(tif,FIELD_PLANARCONFIG)) {
         fprintf(fd, "  Planar Configuration: ");
         switch (td->td_planarconfig) {
         case PLANARCONFIG_CONTIG:
             fprintf(fd, "single image plane\n");
             break;
         case PLANARCONFIG_SEPARATE:
             fprintf(fd, "separate image planes\n");
             break;
         default:
             fprintf(fd, "%u (0x%x)\n",
                 td->td_planarconfig, td->td_planarconfig);
             break;
         }
     }
     if (TIFFFieldSet(tif,FIELD_PAGENUMBER))
         fprintf(fd, "  Page Number: %u-%u\n",
             td->td_pagenumber[0], td->td_pagenumber[1]);
     if (TIFFFieldSet(tif,FIELD_COLORMAP)) {
         fprintf(fd, "  Color Map: ");
         if (flags & TIFFPRINT_COLORMAP) {
             fprintf(fd, "\n");
             n = 1L<<td->td_bitspersample;
             for (l = 0; l < n; l++)
                 fprintf(fd, "   %5lu: %5u %5u %5u\n",
                     l,
                     td->td_colormap[0][l],
                     td->td_colormap[1][l],
                     td->td_colormap[2][l]);
         } else
             fprintf(fd, "(present)\n");
     }
     if (TIFFFieldSet(tif,FIELD_TRANSFERFUNCTION)) {
         fprintf(fd, "  Transfer Function: ");
         if (flags & TIFFPRINT_CURVES) {
             fprintf(fd, "\n");
             n = 1L<<td->td_bitspersample;
             for (l = 0; l < n; l++) {
                 fprintf(fd, "    %2lu: %5u",
                     l, td->td_transferfunction[0][l]);
                 for (i = 1; i < td->td_samplesperpixel; i++)
                     fprintf(fd, " %5u",
                         td->td_transferfunction[i][l]);
                 fputc('\n', fd);
             }
         } else
             fprintf(fd, "(present)\n");
     }
     if (TIFFFieldSet(tif, FIELD_SUBIFD)) {
         fprintf(fd, "  SubIFD Offsets:");
         for (i = 0; i < td->td_nsubifd; i++)
             fprintf(fd, " %5lu", (long) td->td_subifd[i]);
         fputc('\n', fd);
     }
         /*
         ** Custom tag support.
         */
         {
             int  i;
             short count;
             count = (short) TIFFGetTagListCount(tif);
             for(i = 0; i < count; i++) {
                 ttag_t  tag = TIFFGetTagListEntry(tif, i);
                 const TIFFFieldInfo *fip;
                 uint16 value_count;
                 int mem_alloc = 0;
                 void *raw_data;
                 fip = TIFFFieldWithTag(tif, tag);
                 if(fip == NULL)
             continue;
         if(fip->field_passcount) {
             if(TIFFGetField(tif, tag, &value_count, &raw_data) != 1)
                 continue;
         } else {
             if (fip->field_readcount == TIFF_VARIABLE
                 || fip->field_readcount == TIFF_VARIABLE2)
                 value_count = 1;
             else if (fip->field_readcount == TIFF_SPP)
                 value_count = td->td_samplesperpixel;
             else
                 value_count = fip->field_readcount;
             if (fip->field_type == TIFF_ASCII
                 || fip->field_readcount == TIFF_VARIABLE
                 || fip->field_readcount == TIFF_VARIABLE2
                 || fip->field_readcount == TIFF_SPP
                 || value_count > 1) {
                 if(TIFFGetField(tif, tag, &raw_data) != 1)
                     continue;
             } else {
                 raw_data = _TIFFmalloc(
                     _TIFFDataSize(fip->field_type)
                     * value_count);
                 mem_alloc = 1;
                 if(TIFFGetField(tif, tag, raw_data) != 1) {
                     _TIFFfree(raw_data);
                     continue;
                 }
             }
         }
         /*
          * Catch the tags which needs to be specially handled and
          * pretty print them. If tag not handled in
          * _TIFFPrettyPrintField() fall down and print it as any other
          * tag.
          */
         if (_TIFFPrettyPrintField(tif, fd, tag, value_count, raw_data))
             continue;
         else
             _TIFFPrintField(fd, fip, value_count, raw_data);
         if(mem_alloc)
             _TIFFfree(raw_data);
             }
         }
     if (tif->tif_tagmethods.printdir)
         (*tif->tif_tagmethods.printdir)(tif, fd, flags);
     if ((flags & TIFFPRINT_STRIPS) &&
         TIFFFieldSet(tif,FIELD_STRIPOFFSETS)) {
         tstrip_t s;
         fprintf(fd, "  %lu %s:\n",
             (long) td->td_nstrips,
             isTiled(tif) ? "Tiles" : "Strips");
         for (s = 0; s < td->td_nstrips; s++)
             fprintf(fd, "    %3lu: [%8lu, %8lu]\n",
                 (unsigned long) s,
                 (unsigned long) td->td_stripoffset[s],
                 (unsigned long) td->td_stripbytecount[s]);
     }
 }
tsize_t TIFFRasterScanlineSize (TIFF *)
Definition at line 245 of file tif_strip.c.
References multiply(), PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_dir, and TIFFhowmany8.
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t scanline;
     scanline = multiply (tif, td->td_bitspersample, td->td_imagewidth,
                  "TIFFRasterScanlineSize");
     if (td->td_planarconfig == PLANARCONFIG_CONTIG) {
         scanline = multiply (tif, scanline, td->td_samplesperpixel,
                      "TIFFRasterScanlineSize");
         return ((tsize_t) TIFFhowmany8(scanline));
     } else
         return ((tsize_t) multiply (tif, TIFFhowmany8(scanline),
                         td->td_samplesperpixel,
                         "TIFFRasterScanlineSize"));
 }
tsize_t TIFFRawStripSize (TIFF * , tstrip_t)
Definition at line 157 of file tif_strip.c.
References TIFFDirectory::td_stripbytecount, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, and TIFFErrorExt().
 {
     TIFFDirectory* td = &tif->tif_dir;
     tsize_t bytecount = td->td_stripbytecount[strip];
     if (bytecount <= 0) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
               "%lu: Invalid strip byte count, strip %lu",
               (unsigned long) bytecount, (unsigned long) strip);
         bytecount = (tsize_t) -1;
     }
     return bytecount;
 }
int TIFFReadBufferSetup (TIFF * , tdata_t , tsize_t)
Definition at line 519 of file tif_read.c.
References _TIFFfree(), _TIFFmalloc(), NULL, tiff::tif_clientdata, tiff::tif_flags, tiff::tif_name, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_row, TIFF_MYBUFFER, TIFFErrorExt(), and TIFFroundup.
Referenced by TIFFFillStrip(), and TIFFFillTile().
 {
     static const char module[] = "TIFFReadBufferSetup";
     if (tif->tif_rawdata) {
         if (tif->tif_flags & TIFF_MYBUFFER)
             _TIFFfree(tif->tif_rawdata);
         tif->tif_rawdata = NULL;
     }
     if (bp) {
         tif->tif_rawdatasize = size;
         tif->tif_rawdata = (tidata_t) bp;
         tif->tif_flags &= ~TIFF_MYBUFFER;
     } else {
         tif->tif_rawdatasize = TIFFroundup(size, 1024);
         tif->tif_rawdata = (tidata_t) _TIFFmalloc(tif->tif_rawdatasize);
         tif->tif_flags |= TIFF_MYBUFFER;
     }
     if (tif->tif_rawdata == NULL) {
         TIFFErrorExt(tif->tif_clientdata, module,
             "%s: No space for data buffer at scanline %ld",
             tif->tif_name, (long) tif->tif_row);
         tif->tif_rawdatasize = 0;
         return (0);
     }
     return (1);
 }
int TIFFReadCustomDirectory (TIFF * , toff_t , const TIFFFieldInfo [], size_t)
Definition at line 690 of file tif_dirread.c.
References _TIFFCheckMalloc(), _TIFFCreateAnonFieldInfo(), _TIFFfree(), _TIFFmemcpy(), _TIFFSetupFieldInfo(), CheckDirCount(), TIFFFieldInfo::field_bit, FIELD_IGNORE, TIFFFieldInfo::field_name, TIFFFieldInfo::field_readcount, TIFFFieldInfo::field_tag, TIFFFieldInfo::field_type, IGNORE, isMapped, NULL, ReadOK, SeekOK, TIFFDirectory::td_samplesperpixel, TIFFDirEntry::tdir_count, TIFFDirEntry::tdir_tag, TIFFDirEntry::tdir_type, tiff::tif_base, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_diroff, tiff::tif_fieldinfo, tiff::tif_flags, tiff::tif_name, tiff::tif_nfields, tiff::tif_size, TIFF_ANY, TIFF_SPP, TIFF_SWAB, TIFF_VARIABLE, TIFF_VARIABLE2, TIFFErrorExt(), TIFFFetchNormalTag(), TIFFFreeDirectory(), TIFFMergeFieldInfo(), TIFFSwabArrayOfLong(), TIFFSwabArrayOfShort(), TIFFSwabShort(), and TIFFWarningExt().
Referenced by TIFFReadEXIFDirectory().
 {
     static const char module[] = "TIFFReadCustomDirectory";
     TIFFDirectory* td = &tif->tif_dir;
     TIFFDirEntry *dp, *dir = NULL;
     const TIFFFieldInfo* fip;
     size_t fix;
     uint16 i, dircount;
     _TIFFSetupFieldInfo(tif, info, n);
     tif->tif_diroff = diroff;
     if (!isMapped(tif)) {
         if (!SeekOK(tif, diroff)) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Seek error accessing TIFF directory",
                             tif->tif_name);
             return (0);
         }
         if (!ReadOK(tif, &dircount, sizeof (uint16))) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Can not read TIFF directory count",
                             tif->tif_name);
             return (0);
         }
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&dircount);
         dir = (TIFFDirEntry *)_TIFFCheckMalloc(tif,
                           dircount,
                           sizeof (TIFFDirEntry),
                           "to read TIFF directory");
         if (dir == NULL)
             return (0);
         if (!ReadOK(tif, dir, dircount * sizeof (TIFFDirEntry))) {
             TIFFErrorExt(tif->tif_clientdata, module,
                                   "%.100s: Can not read TIFF directory",
                                   tif->tif_name);
             goto bad;
         }
     } else {
         toff_t off = diroff;
         if (off + sizeof (uint16) > tif->tif_size) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Can not read TIFF directory count",
                             tif->tif_name);
             return (0);
         } else
             _TIFFmemcpy(&dircount, tif->tif_base + off, sizeof (uint16));
         off += sizeof (uint16);
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&dircount);
         dir = (TIFFDirEntry *)_TIFFCheckMalloc(tif,
             dircount, sizeof (TIFFDirEntry), "to read TIFF directory");
         if (dir == NULL)
             return (0);
         if (off + dircount * sizeof (TIFFDirEntry) > tif->tif_size) {
             TIFFErrorExt(tif->tif_clientdata, module,
                                   "%s: Can not read TIFF directory",
                                   tif->tif_name);
             goto bad;
         } else {
             _TIFFmemcpy(dir, tif->tif_base + off,
                     dircount * sizeof (TIFFDirEntry));
         }
     }
     TIFFFreeDirectory(tif);
     fix = 0;
     for (dp = dir, i = dircount; i > 0; i--, dp++) {
         if (tif->tif_flags & TIFF_SWAB) {
             TIFFSwabArrayOfShort(&dp->tdir_tag, 2);
             TIFFSwabArrayOfLong(&dp->tdir_count, 2);
         }
         if (fix >= tif->tif_nfields || dp->tdir_tag == IGNORE)
             continue;
         while (fix < tif->tif_nfields &&
                tif->tif_fieldinfo[fix]->field_tag < dp->tdir_tag)
             fix++;
         if (fix >= tif->tif_nfields ||
             tif->tif_fieldinfo[fix]->field_tag != dp->tdir_tag) {
             TIFFWarningExt(tif->tif_clientdata, module,
                         "%s: unknown field with tag %d (0x%x) encountered",
                     tif->tif_name, dp->tdir_tag, dp->tdir_tag,
                     dp->tdir_type);
             TIFFMergeFieldInfo(tif,
                        _TIFFCreateAnonFieldInfo(tif,
                         dp->tdir_tag,
                         (TIFFDataType)dp->tdir_type),
                        1);
             fix = 0;
             while (fix < tif->tif_nfields &&
                    tif->tif_fieldinfo[fix]->field_tag < dp->tdir_tag)
                 fix++;
         }
         /*
          * Null out old tags that we ignore.
          */
         if (tif->tif_fieldinfo[fix]->field_bit == FIELD_IGNORE) {
     ignore:
             dp->tdir_tag = IGNORE;
             continue;
         }
         /*
          * Check data type.
          */
         fip = tif->tif_fieldinfo[fix];
         while (dp->tdir_type != (unsigned short) fip->field_type
                        && fix < tif->tif_nfields) {
             if (fip->field_type == TIFF_ANY)    /* wildcard */
                 break;
                         fip = tif->tif_fieldinfo[++fix];
             if (fix >= tif->tif_nfields ||
                 fip->field_tag != dp->tdir_tag) {
                 TIFFWarningExt(tif->tif_clientdata, module,
             "%s: wrong data type %d for \"%s\"; tag ignored",
                         tif->tif_name, dp->tdir_type,
                         tif->tif_fieldinfo[fix-1]->field_name);
                 goto ignore;
             }
         }
         /*
          * Check count if known in advance.
          */
         if (fip->field_readcount != TIFF_VARIABLE
             && fip->field_readcount != TIFF_VARIABLE2) {
             uint32 expected = (fip->field_readcount == TIFF_SPP) ?
                 (uint32) td->td_samplesperpixel :
                 (uint32) fip->field_readcount;
             if (!CheckDirCount(tif, dp, expected))
                 goto ignore;
         }
         (void) TIFFFetchNormalTag(tif, dp);
     }
     if (dir)
         _TIFFfree(dir);
     return 1;
 bad:
     if (dir)
         _TIFFfree(dir);
     return 0;
 }
int TIFFReadDirectory (TIFF *)
Definition at line 70 of file tif_dirread.c.
References _TIFFCheckMalloc(), _TIFFCreateAnonFieldInfo(), _TIFFFieldWithTag(), _TIFFfree(), _TIFFmemcpy(), _TIFFrealloc(), BYTECOUNTLOOKSBAD, CheckDirCount(), ChopUpSingleUncompressedStrip(), COMPRESSION_NONE, EstimateStripByteCounts(), TIFFFieldInfo::field_bit, FIELD_COLORMAP, FIELD_COMPRESSION, FIELD_IGNORE, FIELD_IMAGEDIMENSIONS, FIELD_MAXSAMPLEVALUE, TIFFFieldInfo::field_name, FIELD_PLANARCONFIG, TIFFFieldInfo::field_readcount, FIELD_STRIPBYTECOUNTS, FIELD_STRIPOFFSETS, TIFFFieldInfo::field_tag, FIELD_TILEDIMENSIONS, TIFFFieldInfo::field_type, FILETYPE_PAGE, FILETYPE_REDUCEDIMAGE, IGNORE, isMapped, isTiled, MissingRequired(), NULL, OFILETYPE_PAGE, OFILETYPE_REDUCEDIMAGE, PHOTOMETRIC_PALETTE, PLANARCONFIG_CONTIG, PLANARCONFIG_SEPARATE, ReadOK, SeekOK, TIFFDirectory::td_bitspersample, TIFFDirectory::td_compression, TIFFDirectory::td_imagedepth, TIFFDirectory::td_imagewidth, TIFFDirectory::td_maxsamplevalue, TIFFDirectory::td_nstrips, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripbytecountsorted, TIFFDirectory::td_stripoffset, TIFFDirectory::td_stripsperimage, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, TIFFDirEntry::tdir_count, TIFFDirEntry::tdir_offset, TIFFDirEntry::tdir_tag, TIFFDirEntry::tdir_type, tiff::tif_base, tiff::tif_cleanup, tiff::tif_clientdata, tiff::tif_col, tiff::tif_curdir, tiff::tif_curstrip, tiff::tif_curtile, tiff::tif_dir, tiff::tif_dirlist, tiff::tif_dirnumber, tiff::tif_diroff, tiff::tif_fieldinfo, tiff::tif_flags, tiff::tif_name, tiff::tif_nextdiroff, tiff::tif_nfields, tiff::tif_row, tiff::tif_scanlinesize, tiff::tif_size, tiff::tif_tilesize, TIFF_ANY, TIFF_BEENWRITING, TIFF_ISTILED, TIFF_LONG, TIFF_SPP, TIFF_STRIPCHOP, TIFF_SWAB, TIFF_VARIABLE, TIFF_VARIABLE2, TIFFDefaultDirectory(), TIFFErrorExt(), TIFFExtractData, TIFFFetchData(), TIFFFetchNormalTag(), TIFFFetchPerSampleAnys(), TIFFFetchPerSampleLongs(), TIFFFetchPerSampleShorts(), TIFFFetchRefBlackWhite(), TIFFFetchShortPair(), TIFFFetchStripThing(), TIFFFieldSet, TIFFFreeDirectory(), TIFFMergeFieldInfo(), TIFFNumberOfStrips(), TIFFNumberOfTiles(), TIFFScanlineSize(), TIFFSetField(), TIFFSetFieldBit, TIFFStripSize(), TIFFSwabArrayOfLong(), TIFFSwabArrayOfShort(), TIFFSwabLong(), TIFFSwabShort(), TIFFTAG_BITSPERSAMPLE, TIFFTAG_COLORMAP, TIFFTAG_COMPRESSION, TIFFTAG_DATATYPE, TIFFTAG_DOTRANGE, TIFFTAG_EXTRASAMPLES, TIFFTAG_HALFTONEHINTS, TIFFTAG_IMAGEDEPTH, TIFFTAG_IMAGELENGTH, TIFFTAG_IMAGEWIDTH, TIFFTAG_MAXSAMPLEVALUE, TIFFTAG_MINSAMPLEVALUE, TIFFTAG_OSUBFILETYPE, TIFFTAG_PAGENUMBER, TIFFTAG_PLANARCONFIG, TIFFTAG_REFERENCEBLACKWHITE, TIFFTAG_ROWSPERSTRIP, TIFFTAG_SAMPLEFORMAT, TIFFTAG_SAMPLESPERPIXEL, TIFFTAG_SMAXSAMPLEVALUE, TIFFTAG_SMINSAMPLEVALUE, TIFFTAG_STRIPBYTECOUNTS, TIFFTAG_STRIPOFFSETS, TIFFTAG_SUBFILETYPE, TIFFTAG_TILEBYTECOUNTS, TIFFTAG_TILEDEPTH, TIFFTAG_TILELENGTH, TIFFTAG_TILEOFFSETS, TIFFTAG_TILEWIDTH, TIFFTAG_TRANSFERFUNCTION, TIFFTAG_YCBCRSUBSAMPLING, TIFFTileSize(), and TIFFWarningExt().
Referenced by TIFFClientOpen(), TIFFSetDirectory(), and TIFFSetSubDirectory().
 {
     static const char module[] = "TIFFReadDirectory";
     int n;
     TIFFDirectory* td;
     TIFFDirEntry *dp, *dir = NULL;
     uint16 iv;
     uint32 v;
     const TIFFFieldInfo* fip;
     size_t fix;
     uint16 dircount;
     toff_t nextdiroff;
     char* cp;
     int diroutoforderwarning = 0;
     toff_t* new_dirlist;
     tif->tif_diroff = tif->tif_nextdiroff;
     if (tif->tif_diroff == 0)       /* no more directories */
         return (0);
     /*
      * XXX: Trick to prevent IFD looping. The one can create TIFF file
      * with looped directory pointers. We will maintain a list of already
      * seen directories and check every IFD offset against this list.
      */
     for (n = 0; n < tif->tif_dirnumber; n++) {
         if (tif->tif_dirlist[n] == tif->tif_diroff)
             return (0);
     }
     tif->tif_dirnumber++;
     new_dirlist = (toff_t*)_TIFFrealloc(tif->tif_dirlist,
                    tif->tif_dirnumber * sizeof(toff_t));
     if (!new_dirlist) {
         TIFFErrorExt(tif->tif_clientdata, module,
               "%s: Failed to allocate space for IFD list",
               tif->tif_name);
         return (0);
     }
     tif->tif_dirlist = new_dirlist;
     tif->tif_dirlist[tif->tif_dirnumber - 1] = tif->tif_diroff;
     /*
      * Cleanup any previous compression state.
      */
     (*tif->tif_cleanup)(tif);
     tif->tif_curdir++;
     nextdiroff = 0;
     if (!isMapped(tif)) {
         if (!SeekOK(tif, tif->tif_diroff)) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Seek error accessing TIFF directory",
                             tif->tif_name);
             return (0);
         }
         if (!ReadOK(tif, &dircount, sizeof (uint16))) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Can not read TIFF directory count",
                             tif->tif_name);
             return (0);
         }
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&dircount);
         dir = (TIFFDirEntry *)_TIFFCheckMalloc(tif,
                           dircount,
                           sizeof (TIFFDirEntry),
                           "to read TIFF directory");
         if (dir == NULL)
             return (0);
         if (!ReadOK(tif, dir, dircount*sizeof (TIFFDirEntry))) {
             TIFFErrorExt(tif->tif_clientdata, module,
                                   "%.100s: Can not read TIFF directory",
                                   tif->tif_name);
             goto bad;
         }
         /*
          * Read offset to next directory for sequential scans.
          */
         (void) ReadOK(tif, &nextdiroff, sizeof (uint32));
     } else {
         toff_t off = tif->tif_diroff;
         if (off + sizeof (uint16) > tif->tif_size) {
             TIFFErrorExt(tif->tif_clientdata, module,
                 "%s: Can not read TIFF directory count",
                             tif->tif_name);
             return (0);
         } else
             _TIFFmemcpy(&dircount, tif->tif_base + off, sizeof (uint16));
         off += sizeof (uint16);
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&dircount);
         dir = (TIFFDirEntry *)_TIFFCheckMalloc(tif,
             dircount, sizeof (TIFFDirEntry), "to read TIFF directory");
         if (dir == NULL)
             return (0);
         if (off + dircount*sizeof (TIFFDirEntry) > tif->tif_size) {
             TIFFErrorExt(tif->tif_clientdata, module,
                                   "%s: Can not read TIFF directory",
                                   tif->tif_name);
             goto bad;
         } else {
             _TIFFmemcpy(dir, tif->tif_base + off,
                     dircount*sizeof (TIFFDirEntry));
         }
         off += dircount* sizeof (TIFFDirEntry);
         if (off + sizeof (uint32) <= tif->tif_size)
             _TIFFmemcpy(&nextdiroff, tif->tif_base+off, sizeof (uint32));
     }
     if (tif->tif_flags & TIFF_SWAB)
         TIFFSwabLong(&nextdiroff);
     tif->tif_nextdiroff = nextdiroff;
     tif->tif_flags &= ~TIFF_BEENWRITING;    /* reset before new dir */
     /*
      * Setup default value and then make a pass over
      * the fields to check type and tag information,
      * and to extract info required to size data
      * structures.  A second pass is made afterwards
      * to read in everthing not taken in the first pass.
      */
     td = &tif->tif_dir;
     /* free any old stuff and reinit */
     TIFFFreeDirectory(tif);
     TIFFDefaultDirectory(tif);
     /*
      * Electronic Arts writes gray-scale TIFF files
      * without a PlanarConfiguration directory entry.
      * Thus we setup a default value here, even though
      * the TIFF spec says there is no default value.
      */
     TIFFSetField(tif, TIFFTAG_PLANARCONFIG, PLANARCONFIG_CONTIG);
     /*
      * Sigh, we must make a separate pass through the
      * directory for the following reason:
      *
      * We must process the Compression tag in the first pass
      * in order to merge in codec-private tag definitions (otherwise
      * we may get complaints about unknown tags).  However, the
      * Compression tag may be dependent on the SamplesPerPixel
      * tag value because older TIFF specs permited Compression
      * to be written as a SamplesPerPixel-count tag entry.
      * Thus if we don't first figure out the correct SamplesPerPixel
      * tag value then we may end up ignoring the Compression tag
      * value because it has an incorrect count value (if the
      * true value of SamplesPerPixel is not 1).
      *
      * It sure would have been nice if Aldus had really thought
      * this stuff through carefully.
      */
     for (dp = dir, n = dircount; n > 0; n--, dp++) {
         if (tif->tif_flags & TIFF_SWAB) {
             TIFFSwabArrayOfShort(&dp->tdir_tag, 2);
             TIFFSwabArrayOfLong(&dp->tdir_count, 2);
         }
         if (dp->tdir_tag == TIFFTAG_SAMPLESPERPIXEL) {
             if (!TIFFFetchNormalTag(tif, dp))
                 goto bad;
             dp->tdir_tag = IGNORE;
         }
     }
     /*
      * First real pass over the directory.
      */
     fix = 0;
     for (dp = dir, n = dircount; n > 0; n--, dp++) {
         if (fix >= tif->tif_nfields || dp->tdir_tag == IGNORE)
             continue;
         /*
          * Silicon Beach (at least) writes unordered
          * directory tags (violating the spec).  Handle
          * it here, but be obnoxious (maybe they'll fix it?).
          */
         if (dp->tdir_tag < tif->tif_fieldinfo[fix]->field_tag) {
             if (!diroutoforderwarning) {
                 TIFFWarningExt(tif->tif_clientdata, module,
 "%s: invalid TIFF directory; tags are not sorted in ascending order",
                                             tif->tif_name);
                 diroutoforderwarning = 1;
             }
             fix = 0;            /* O(n^2) */
         }
         while (fix < tif->tif_nfields &&
                tif->tif_fieldinfo[fix]->field_tag < dp->tdir_tag)
             fix++;
         if (fix >= tif->tif_nfields ||
             tif->tif_fieldinfo[fix]->field_tag != dp->tdir_tag) {
                     TIFFWarningExt(tif->tif_clientdata, module,
                         "%s: unknown field with tag %d (0x%x) encountered",
                                 tif->tif_name, dp->tdir_tag, dp->tdir_tag,
                                 dp->tdir_type);
                     TIFFMergeFieldInfo( tif,
                                         _TIFFCreateAnonFieldInfo( tif,
                                               dp->tdir_tag,
                           (TIFFDataType) dp->tdir_type ),
                                         1 );
                     fix = 0;
                     while (fix < tif->tif_nfields &&
                            tif->tif_fieldinfo[fix]->field_tag < dp->tdir_tag)
             fix++;
         }
         /*
          * Null out old tags that we ignore.
          */
         if (tif->tif_fieldinfo[fix]->field_bit == FIELD_IGNORE) {
     ignore:
             dp->tdir_tag = IGNORE;
             continue;
         }
         /*
          * Check data type.
          */
         fip = tif->tif_fieldinfo[fix];
         while (dp->tdir_type != (unsigned short) fip->field_type
                        && fix < tif->tif_nfields) {
             if (fip->field_type == TIFF_ANY)    /* wildcard */
                 break;
                         fip = tif->tif_fieldinfo[++fix];
             if (fix >= tif->tif_nfields ||
                 fip->field_tag != dp->tdir_tag) {
                 TIFFWarningExt(tif->tif_clientdata, module,
             "%s: wrong data type %d for \"%s\"; tag ignored",
                         tif->tif_name, dp->tdir_type,
                         tif->tif_fieldinfo[fix-1]->field_name);
                 goto ignore;
             }
         }
         /*
          * Check count if known in advance.
          */
         if (fip->field_readcount != TIFF_VARIABLE
             && fip->field_readcount != TIFF_VARIABLE2) {
             uint32 expected = (fip->field_readcount == TIFF_SPP) ?
                 (uint32) td->td_samplesperpixel :
                 (uint32) fip->field_readcount;
             if (!CheckDirCount(tif, dp, expected))
                 goto ignore;
         }
         switch (dp->tdir_tag) {
         case TIFFTAG_COMPRESSION:
             /*
              * The 5.0 spec says the Compression tag has
              * one value, while earlier specs say it has
              * one value per sample.  Because of this, we
              * accept the tag if one value is supplied.
              */
             if (dp->tdir_count == 1) {
                 v = TIFFExtractData(tif,
                     dp->tdir_type, dp->tdir_offset);
                 if (!TIFFSetField(tif, dp->tdir_tag, (uint16)v))
                     goto bad;
                 break;
             /* XXX: workaround for broken TIFFs */
             } else if (dp->tdir_type == TIFF_LONG) {
                 if (!TIFFFetchPerSampleLongs(tif, dp, &v) ||
                     !TIFFSetField(tif, dp->tdir_tag, (uint16)v))
                     goto bad;
             } else {
                 if (!TIFFFetchPerSampleShorts(tif, dp, &iv)
                     || !TIFFSetField(tif, dp->tdir_tag, iv))
                     goto bad;
             }
             dp->tdir_tag = IGNORE;
             break;
         case TIFFTAG_STRIPOFFSETS:
         case TIFFTAG_STRIPBYTECOUNTS:
         case TIFFTAG_TILEOFFSETS:
         case TIFFTAG_TILEBYTECOUNTS:
             TIFFSetFieldBit(tif, fip->field_bit);
             break;
         case TIFFTAG_IMAGEWIDTH:
         case TIFFTAG_IMAGELENGTH:
         case TIFFTAG_IMAGEDEPTH:
         case TIFFTAG_TILELENGTH:
         case TIFFTAG_TILEWIDTH:
         case TIFFTAG_TILEDEPTH:
         case TIFFTAG_PLANARCONFIG:
         case TIFFTAG_ROWSPERSTRIP:
         case TIFFTAG_EXTRASAMPLES:
             if (!TIFFFetchNormalTag(tif, dp))
                 goto bad;
             dp->tdir_tag = IGNORE;
             break;
         }
     }
     /*
      * Allocate directory structure and setup defaults.
      */
     if (!TIFFFieldSet(tif, FIELD_IMAGEDIMENSIONS)) {
         MissingRequired(tif, "ImageLength");
         goto bad;
     }
     if (!TIFFFieldSet(tif, FIELD_PLANARCONFIG)) {
         MissingRequired(tif, "PlanarConfiguration");
         goto bad;
     }
     /*
      * Setup appropriate structures (by strip or by tile)
      */
     if (!TIFFFieldSet(tif, FIELD_TILEDIMENSIONS)) {
         td->td_nstrips = TIFFNumberOfStrips(tif);
         td->td_tilewidth = td->td_imagewidth;
         td->td_tilelength = td->td_rowsperstrip;
         td->td_tiledepth = td->td_imagedepth;
         tif->tif_flags &= ~TIFF_ISTILED;
     } else {
         td->td_nstrips = TIFFNumberOfTiles(tif);
         tif->tif_flags |= TIFF_ISTILED;
     }
     if (!td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, module, "%s: cannot handle zero number of %s",
               tif->tif_name, isTiled(tif) ? "tiles" : "strips");
         goto bad;
     }
     td->td_stripsperimage = td->td_nstrips;
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
         td->td_stripsperimage /= td->td_samplesperpixel;
     if (!TIFFFieldSet(tif, FIELD_STRIPOFFSETS)) {
         MissingRequired(tif,
             isTiled(tif) ? "TileOffsets" : "StripOffsets");
         goto bad;
     }
     /*
      * Second pass: extract other information.
      */
     for (dp = dir, n = dircount; n > 0; n--, dp++) {
         if (dp->tdir_tag == IGNORE)
             continue;
         switch (dp->tdir_tag) {
         case TIFFTAG_MINSAMPLEVALUE:
         case TIFFTAG_MAXSAMPLEVALUE:
         case TIFFTAG_BITSPERSAMPLE:
         case TIFFTAG_DATATYPE:
         case TIFFTAG_SAMPLEFORMAT:
             /*
              * The 5.0 spec says the Compression tag has
              * one value, while earlier specs say it has
              * one value per sample.  Because of this, we
              * accept the tag if one value is supplied.
              *
                          * The MinSampleValue, MaxSampleValue, BitsPerSample
                          * DataType and SampleFormat tags are supposed to be
                          * written as one value/sample, but some vendors
                          * incorrectly write one value only -- so we accept
                          * that as well (yech). Other vendors write correct
              * value for NumberOfSamples, but incorrect one for
              * BitsPerSample and friends, and we will read this
              * too.
              */
             if (dp->tdir_count == 1) {
                 v = TIFFExtractData(tif,
                     dp->tdir_type, dp->tdir_offset);
                 if (!TIFFSetField(tif, dp->tdir_tag, (uint16)v))
                     goto bad;
             /* XXX: workaround for broken TIFFs */
             } else if (dp->tdir_tag == TIFFTAG_BITSPERSAMPLE
                    && dp->tdir_type == TIFF_LONG) {
                 if (!TIFFFetchPerSampleLongs(tif, dp, &v) ||
                     !TIFFSetField(tif, dp->tdir_tag, (uint16)v))
                     goto bad;
             } else {
                 if (!TIFFFetchPerSampleShorts(tif, dp, &iv) ||
                     !TIFFSetField(tif, dp->tdir_tag, iv))
                     goto bad;
             }
             break;
         case TIFFTAG_SMINSAMPLEVALUE:
         case TIFFTAG_SMAXSAMPLEVALUE:
             {
                 double dv = 0.0;
                 if (!TIFFFetchPerSampleAnys(tif, dp, &dv) ||
                     !TIFFSetField(tif, dp->tdir_tag, dv))
                     goto bad;
             }
             break;
         case TIFFTAG_STRIPOFFSETS:
         case TIFFTAG_TILEOFFSETS:
             if (!TIFFFetchStripThing(tif, dp,
                 td->td_nstrips, &td->td_stripoffset))
                 goto bad;
             break;
         case TIFFTAG_STRIPBYTECOUNTS:
         case TIFFTAG_TILEBYTECOUNTS:
             if (!TIFFFetchStripThing(tif, dp,
                 td->td_nstrips, &td->td_stripbytecount))
                 goto bad;
             break;
         case TIFFTAG_COLORMAP:
         case TIFFTAG_TRANSFERFUNCTION:
             /*
              * TransferFunction can have either 1x or 3x data
              * values; Colormap can have only 3x items.
              */
             v = 1L<<td->td_bitspersample;
             if (dp->tdir_tag == TIFFTAG_COLORMAP ||
                 dp->tdir_count != v) {
                 if (!CheckDirCount(tif, dp, 3 * v))
                     break;
             }
             v *= sizeof(uint16);
             cp = (char*)_TIFFCheckMalloc(tif, dp->tdir_count, sizeof (uint16),
                 "to read \"TransferFunction\" tag");
             if (cp != NULL) {
                 if (TIFFFetchData(tif, dp, cp)) {
                     /*
                      * This deals with there being only
                      * one array to apply to all samples.
                      */
                     uint32 c = 1L << td->td_bitspersample;
                     if (dp->tdir_count == c)
                         v = 0L;
                     TIFFSetField(tif, dp->tdir_tag,
                         cp, cp+v, cp+2*v);
                 }
                 _TIFFfree(cp);
             }
             break;
         case TIFFTAG_PAGENUMBER:
         case TIFFTAG_HALFTONEHINTS:
         case TIFFTAG_YCBCRSUBSAMPLING:
         case TIFFTAG_DOTRANGE:
             (void) TIFFFetchShortPair(tif, dp);
             break;
         case TIFFTAG_REFERENCEBLACKWHITE:
             (void) TIFFFetchRefBlackWhite(tif, dp);
             break;
 /* BEGIN REV 4.0 COMPATIBILITY */
         case TIFFTAG_OSUBFILETYPE:
             v = 0L;
             switch (TIFFExtractData(tif, dp->tdir_type,
                 dp->tdir_offset)) {
             case OFILETYPE_REDUCEDIMAGE:
                 v = FILETYPE_REDUCEDIMAGE;
                 break;
             case OFILETYPE_PAGE:
                 v = FILETYPE_PAGE;
                 break;
             }
             if (v)
                 TIFFSetField(tif, TIFFTAG_SUBFILETYPE, v);
             break;
 /* END REV 4.0 COMPATIBILITY */
         default:
             (void) TIFFFetchNormalTag(tif, dp);
             break;
         }
     }
     /*
      * Verify Palette image has a Colormap.
      */
     if (td->td_photometric == PHOTOMETRIC_PALETTE &&
         !TIFFFieldSet(tif, FIELD_COLORMAP)) {
         MissingRequired(tif, "Colormap");
         goto bad;
     }
     /*
      * Attempt to deal with a missing StripByteCounts tag.
      */
     if (!TIFFFieldSet(tif, FIELD_STRIPBYTECOUNTS)) {
         /*
          * Some manufacturers violate the spec by not giving
          * the size of the strips.  In this case, assume there
          * is one uncompressed strip of data.
          */
         if ((td->td_planarconfig == PLANARCONFIG_CONTIG &&
             td->td_nstrips > 1) ||
             (td->td_planarconfig == PLANARCONFIG_SEPARATE &&
              td->td_nstrips != td->td_samplesperpixel)) {
             MissingRequired(tif, "StripByteCounts");
             goto bad;
         }
         TIFFWarningExt(tif->tif_clientdata, module,
             "%s: TIFF directory is missing required "
             "\"%s\" field, calculating from imagelength",
             tif->tif_name,
                 _TIFFFieldWithTag(tif,TIFFTAG_STRIPBYTECOUNTS)->field_name);
         if (EstimateStripByteCounts(tif, dir, dircount) < 0)
             goto bad;
 /*
  * Assume we have wrong StripByteCount value (in case of single strip) in
  * following cases:
  *   - it is equal to zero along with StripOffset;
  *   - it is larger than file itself (in case of uncompressed image);
  *   - it is smaller than the size of the bytes per row multiplied on the
  *     number of rows.  The last case should not be checked in the case of
  *     writing new image, because we may do not know the exact strip size
  *     until the whole image will be written and directory dumped out.
  */
 #define BYTECOUNTLOOKSBAD \
     ( (td->td_stripbytecount[0] == 0 && td->td_stripoffset[0] != 0) || \
       (td->td_compression == COMPRESSION_NONE && \
        td->td_stripbytecount[0] > TIFFGetFileSize(tif) - td->td_stripoffset[0]) || \
       (tif->tif_mode == O_RDONLY && \
        td->td_compression == COMPRESSION_NONE && \
        td->td_stripbytecount[0] < TIFFScanlineSize(tif) * td->td_imagelength) )
     } else if (td->td_nstrips == 1
                    && td->td_stripoffset[0] != 0
                    && BYTECOUNTLOOKSBAD) {
         /*
          * XXX: Plexus (and others) sometimes give a value of zero for
          * a tag when they don't know what the correct value is!  Try
          * and handle the simple case of estimating the size of a one
          * strip image.
          */
         TIFFWarningExt(tif->tif_clientdata, module,
     "%s: Bogus \"%s\" field, ignoring and calculating from imagelength",
                             tif->tif_name,
                     _TIFFFieldWithTag(tif,TIFFTAG_STRIPBYTECOUNTS)->field_name);
         if(EstimateStripByteCounts(tif, dir, dircount) < 0)
             goto bad;
     } else if (td->td_planarconfig == PLANARCONFIG_CONTIG
            && td->td_nstrips > 2
            && td->td_compression == COMPRESSION_NONE
            && td->td_stripbytecount[0] != td->td_stripbytecount[1]) {
         /*
          * XXX: Some vendors fill StripByteCount array with absolutely
          * wrong values (it can be equal to StripOffset array, for
          * example). Catch this case here.
          */
         TIFFWarningExt(tif->tif_clientdata, module,
     "%s: Wrong \"%s\" field, ignoring and calculating from imagelength",
                             tif->tif_name,
                     _TIFFFieldWithTag(tif,TIFFTAG_STRIPBYTECOUNTS)->field_name);
         if (EstimateStripByteCounts(tif, dir, dircount) < 0)
             goto bad;
     }
     if (dir) {
         _TIFFfree((char *)dir);
         dir = NULL;
     }
     if (!TIFFFieldSet(tif, FIELD_MAXSAMPLEVALUE))
         td->td_maxsamplevalue = (uint16)((1L<<td->td_bitspersample)-1);
     /*
      * Setup default compression scheme.
      */
     /*
      * XXX: We can optimize checking for the strip bounds using the sorted
      * bytecounts array. See also comments for TIFFAppendToStrip()
      * function in tif_write.c.
      */
     if (td->td_nstrips > 1) {
         tstrip_t strip;
         td->td_stripbytecountsorted = 1;
         for (strip = 1; strip < td->td_nstrips; strip++) {
             if (td->td_stripoffset[strip - 1] >
                 td->td_stripoffset[strip]) {
                 td->td_stripbytecountsorted = 0;
                 break;
             }
         }
     }
     if (!TIFFFieldSet(tif, FIELD_COMPRESSION))
         TIFFSetField(tif, TIFFTAG_COMPRESSION, COMPRESSION_NONE);
         /*
          * Some manufacturers make life difficult by writing
      * large amounts of uncompressed data as a single strip.
      * This is contrary to the recommendations of the spec.
          * The following makes an attempt at breaking such images
      * into strips closer to the recommended 8k bytes.  A
      * side effect, however, is that the RowsPerStrip tag
      * value may be changed.
          */
     if (td->td_nstrips == 1 && td->td_compression == COMPRESSION_NONE &&
         (tif->tif_flags & (TIFF_STRIPCHOP|TIFF_ISTILED)) == TIFF_STRIPCHOP)
         ChopUpSingleUncompressedStrip(tif);
     /*
      * Reinitialize i/o since we are starting on a new directory.
      */
     tif->tif_row = (uint32) -1;
     tif->tif_curstrip = (tstrip_t) -1;
     tif->tif_col = (uint32) -1;
     tif->tif_curtile = (ttile_t) -1;
     tif->tif_tilesize = (tsize_t) -1;
     tif->tif_scanlinesize = TIFFScanlineSize(tif);
     if (!tif->tif_scanlinesize) {
         TIFFErrorExt(tif->tif_clientdata, module, "%s: cannot handle zero scanline size",
               tif->tif_name);
         return (0);
     }
     if (isTiled(tif)) {
         tif->tif_tilesize = TIFFTileSize(tif);
         if (!tif->tif_tilesize) {
             TIFFErrorExt(tif->tif_clientdata, module, "%s: cannot handle zero tile size",
                   tif->tif_name);
             return (0);
         }
     } else {
         if (!TIFFStripSize(tif)) {
             TIFFErrorExt(tif->tif_clientdata, module, "%s: cannot handle zero strip size",
                   tif->tif_name);
             return (0);
         }
     }
     return (1);
 bad:
     if (dir)
         _TIFFfree(dir);
     return (0);
 }
tsize_t TIFFReadEncodedStrip (TIFF * , tstrip_t , tdata_t , tsize_t)
Definition at line 122 of file tif_read.c.
References TIFFDirectory::td_imagelength, TIFFDirectory::td_nstrips, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_decodestrip, tiff::tif_dir, tiff::tif_name, tiff::tif_postdecode, TIFFCheckRead(), TIFFErrorExt(), TIFFFillStrip(), and TIFFVStripSize().
Referenced by gtStripContig(), and gtStripSeparate().
 {
     TIFFDirectory *td = &tif->tif_dir;
     uint32 nrows;
     tsize_t stripsize;
         tstrip_t sep_strip, strips_per_sep;
     if (!TIFFCheckRead(tif, 0))
         return (-1);
     if (strip >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%ld: Strip out of range, max %ld",
             (long) strip, (long) td->td_nstrips);
         return (-1);
     }
     /*
      * Calculate the strip size according to the number of
      * rows in the strip (check for truncated last strip on any
          * of the separations).
      */
         if( td->td_rowsperstrip >= td->td_imagelength )
             strips_per_sep = 1;
         else
             strips_per_sep = (td->td_imagelength+td->td_rowsperstrip-1)
                 / td->td_rowsperstrip;
         sep_strip = strip % strips_per_sep;
     if (sep_strip != strips_per_sep-1 ||
         (nrows = td->td_imagelength % td->td_rowsperstrip) == 0)
         nrows = td->td_rowsperstrip;
     stripsize = TIFFVStripSize(tif, nrows);
     if (size == (tsize_t) -1)
         size = stripsize;
     else if (size > stripsize)
         size = stripsize;
     if (TIFFFillStrip(tif, strip)
             && (*tif->tif_decodestrip)(tif, (tidata_t) buf, size,
                          (tsample_t)(strip / td->td_stripsperimage)) > 0 ) {
         (*tif->tif_postdecode)(tif, (tidata_t) buf, size);
         return (size);
     } else
         return ((tsize_t) -1);
 }
tsize_t TIFFReadEncodedTile (TIFF * , ttile_t , tdata_t , tsize_t)
Definition at line 344 of file tif_read.c.
References TIFFDirectory::td_nstrips, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_decodetile, tiff::tif_dir, tiff::tif_name, tiff::tif_postdecode, tiff::tif_tilesize, TIFFCheckRead(), TIFFErrorExt(), and TIFFFillTile().
Referenced by TIFFReadTile().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t tilesize = tif->tif_tilesize;
     if (!TIFFCheckRead(tif, 1))
         return (-1);
     if (tile >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%ld: Tile out of range, max %ld",
             (long) tile, (unsigned long) td->td_nstrips);
         return (-1);
     }
     if (size == (tsize_t) -1)
         size = tilesize;
     else if (size > tilesize)
         size = tilesize;
     if (TIFFFillTile(tif, tile) && (*tif->tif_decodetile)(tif,
         (tidata_t) buf, size, (tsample_t)(tile/td->td_stripsperimage))) {
         (*tif->tif_postdecode)(tif, (tidata_t) buf, size);
         return (size);
     } else
         return (-1);
 }
int TIFFReadEXIFDirectory (TIFF * , toff_t)
Definition at line 851 of file tif_dirread.c.
References _TIFFGetExifFieldInfo(), exifFieldInfo, and TIFFReadCustomDirectory().
 {
     size_t exifFieldInfoCount;
     const TIFFFieldInfo *exifFieldInfo =
         _TIFFGetExifFieldInfo(&exifFieldInfoCount);
     return TIFFReadCustomDirectory(tif, diroff, exifFieldInfo,
                        exifFieldInfoCount);
 }
tsize_t TIFFReadRawStrip (TIFF * , tstrip_t , tdata_t , tsize_t)
Definition at line 214 of file tif_read.c.
References TIFFDirectory::td_nstrips, TIFFDirectory::td_stripbytecount, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFCheckRead(), TIFFErrorExt(), and TIFFReadRawStrip1().
Referenced by TIFFImageIO::ReadGenericImage().
 {
     static const char module[] = "TIFFReadRawStrip";
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t bytecount;
     if (!TIFFCheckRead(tif, 0))
         return ((tsize_t) -1);
     if (strip >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Strip out of range, max %lu",
             (unsigned long) strip, (unsigned long) td->td_nstrips);
         return ((tsize_t) -1);
     }
     bytecount = td->td_stripbytecount[strip];
     if (bytecount <= 0) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
             "%lu: Invalid strip byte count, strip %lu",
             (unsigned long) bytecount, (unsigned long) strip);
         return ((tsize_t) -1);
     }
     if (size != (tsize_t)-1 && size < bytecount)
         bytecount = size;
     return (TIFFReadRawStrip1(tif, strip, buf, bytecount, module));
 }
tsize_t TIFFReadRawTile (TIFF * , ttile_t , tdata_t , tsize_t)
Definition at line 418 of file tif_read.c.
References TIFFDirectory::td_nstrips, TIFFDirectory::td_stripbytecount, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFCheckRead(), TIFFErrorExt(), and TIFFReadRawTile1().
 {
     static const char module[] = "TIFFReadRawTile";
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t bytecount;
     if (!TIFFCheckRead(tif, 1))
         return ((tsize_t) -1);
     if (tile >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "%lu: Tile out of range, max %lu",
             (unsigned long) tile, (unsigned long) td->td_nstrips);
         return ((tsize_t) -1);
     }
     bytecount = td->td_stripbytecount[tile];
     if (size != (tsize_t) -1 && size < bytecount)
         bytecount = size;
     return (TIFFReadRawTile1(tif, tile, buf, bytecount, module));
 }
int TIFFReadRGBAImage (TIFF * , uint32 , uint32 , uint32 * , int)
Definition at line 487 of file tif_getimage.c.
References ORIENTATION_BOTLEFT, and TIFFReadRGBAImageOriented().
 {
     return TIFFReadRGBAImageOriented(tif, rwidth, rheight, raster,
                      ORIENTATION_BOTLEFT, stop);
 }
int TIFFReadRGBAImageOriented (TIFF * , uint32 , uint32 , uint32 * , int , int)
Definition at line 461 of file tif_getimage.c.
References _TIFFRGBAImage::height, _TIFFRGBAImage::req_orientation, tiff::tif_clientdata, TIFFErrorExt(), TIFFFileName(), TIFFRGBAImageBegin(), TIFFRGBAImageEnd(), TIFFRGBAImageGet(), and TIFFRGBAImageOK().
Referenced by TIFFImageIO::Read(), and TIFFReadRGBAImage().
 {
     char emsg[1024] = "";
     TIFFRGBAImage img;
     int ok;
     if (TIFFRGBAImageOK(tif, emsg) && TIFFRGBAImageBegin(&img, tif, stop, emsg)) {
         img.req_orientation = orientation;
         /* XXX verify rwidth and rheight against width and height */
         ok = TIFFRGBAImageGet(&img, raster+(rheight-img.height)*rwidth,
             rwidth, img.height);
         TIFFRGBAImageEnd(&img);
     } else {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif), emsg);
         ok = 0;
     }
     return (ok);
 }
int TIFFReadRGBAStrip (TIFF * , tstrip_t , uint32 *)
Definition at line 2450 of file tif_getimage.c.
References _TIFFRGBAImage::col_offset, _TIFFRGBAImage::height, _TIFFRGBAImage::row_offset, tiff::tif_clientdata, TIFFErrorExt(), TIFFFileName(), TIFFGetFieldDefaulted(), TIFFIsTiled(), TIFFRGBAImageBegin(), TIFFRGBAImageEnd(), TIFFRGBAImageGet(), TIFFRGBAImageOK(), TIFFTAG_ROWSPERSTRIP, and _TIFFRGBAImage::width.
 {
     char    emsg[1024] = "";
     TIFFRGBAImage img;
     int     ok;
     uint32  rowsperstrip, rows_to_read;
     if( TIFFIsTiled( tif ) )
     {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif),
                   "Can't use TIFFReadRGBAStrip() with tiled file.");
     return (0);
     }
     TIFFGetFieldDefaulted(tif, TIFFTAG_ROWSPERSTRIP, &rowsperstrip);
     if( (row % rowsperstrip) != 0 )
     {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif),
                 "Row passed to TIFFReadRGBAStrip() must be first in a strip.");
         return (0);
     }
     if (TIFFRGBAImageOK(tif, emsg) && TIFFRGBAImageBegin(&img, tif, 0, emsg)) {
         img.row_offset = row;
         img.col_offset = 0;
         if( row + rowsperstrip > img.height )
             rows_to_read = img.height - row;
         else
             rows_to_read = rowsperstrip;
     ok = TIFFRGBAImageGet(&img, raster, img.width, rows_to_read );
     TIFFRGBAImageEnd(&img);
     } else {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif), emsg);
         ok = 0;
     }
     return (ok);
 }
int TIFFReadRGBATile (TIFF * , uint32 , uint32 , uint32 *)
Definition at line 2501 of file tif_getimage.c.
References _TIFFmemset(), _TIFFRGBAImage::col_offset, _TIFFRGBAImage::height, _TIFFRGBAImage::row_offset, tiff::tif_clientdata, TIFFErrorExt(), TIFFFileName(), TIFFGetFieldDefaulted(), TIFFIsTiled(), TIFFRGBAImageBegin(), TIFFRGBAImageEnd(), TIFFRGBAImageGet(), TIFFRGBAImageOK(), TIFFTAG_TILELENGTH, TIFFTAG_TILEWIDTH, and _TIFFRGBAImage::width.
 {
     char    emsg[1024] = "";
     TIFFRGBAImage img;
     int     ok;
     uint32  tile_xsize, tile_ysize;
     uint32  read_xsize, read_ysize;
     uint32  i_row;
     /*
      * Verify that our request is legal - on a tile file, and on a
      * tile boundary.
      */
     if( !TIFFIsTiled( tif ) )
     {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif),
                   "Can't use TIFFReadRGBATile() with stripped file.");
         return (0);
     }
     TIFFGetFieldDefaulted(tif, TIFFTAG_TILEWIDTH, &tile_xsize);
     TIFFGetFieldDefaulted(tif, TIFFTAG_TILELENGTH, &tile_ysize);
     if( (col % tile_xsize) != 0 || (row % tile_ysize) != 0 )
     {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif),
                   "Row/col passed to TIFFReadRGBATile() must be top"
                   "left corner of a tile.");
     return (0);
     }
     /*
      * Setup the RGBA reader.
      */
     if (!TIFFRGBAImageOK(tif, emsg)
     || !TIFFRGBAImageBegin(&img, tif, 0, emsg)) {
         TIFFErrorExt(tif->tif_clientdata, TIFFFileName(tif), emsg);
         return( 0 );
     }
     /*
      * The TIFFRGBAImageGet() function doesn't allow us to get off the
      * edge of the image, even to fill an otherwise valid tile.  So we
      * figure out how much we can read, and fix up the tile buffer to
      * a full tile configuration afterwards.
      */
     if( row + tile_ysize > img.height )
         read_ysize = img.height - row;
     else
         read_ysize = tile_ysize;
     if( col + tile_xsize > img.width )
         read_xsize = img.width - col;
     else
         read_xsize = tile_xsize;
     /*
      * Read the chunk of imagery.
      */
     img.row_offset = row;
     img.col_offset = col;
     ok = TIFFRGBAImageGet(&img, raster, read_xsize, read_ysize );
     TIFFRGBAImageEnd(&img);
     /*
      * If our read was incomplete we will need to fix up the tile by
      * shifting the data around as if a full tile of data is being returned.
      *
      * This is all the more complicated because the image is organized in
      * bottom to top format.
      */
     if( read_xsize == tile_xsize && read_ysize == tile_ysize )
         return( ok );
     for( i_row = 0; i_row < read_ysize; i_row++ ) {
         memmove( raster + (tile_ysize - i_row - 1) * tile_xsize,
                  raster + (read_ysize - i_row - 1) * read_xsize,
                  read_xsize * sizeof(uint32) );
         _TIFFmemset( raster + (tile_ysize - i_row - 1) * tile_xsize+read_xsize,
                      0, sizeof(uint32) * (tile_xsize - read_xsize) );
     }
     for( i_row = read_ysize; i_row < tile_ysize; i_row++ ) {
         _TIFFmemset( raster + (tile_ysize - i_row - 1) * tile_xsize,
                      0, sizeof(uint32) * tile_xsize );
     }
     return (ok);
 }
int TIFFReadScanline (TIFF * , tdata_t , uint32 , tsample_t)
Definition at line 94 of file tif_read.c.
References sample(), tiff::tif_decoderow, tiff::tif_postdecode, tiff::tif_row, tiff::tif_scanlinesize, TIFFCheckRead(), and TIFFSeek().
 {
     int e;
     if (!TIFFCheckRead(tif, 0))
         return (-1);
     if( (e = TIFFSeek(tif, row, sample)) != 0) {
         /*
          * Decompress desired row into user buffer.
          */
         e = (*tif->tif_decoderow)
             (tif, (tidata_t) buf, tif->tif_scanlinesize, sample);
                 /* we are now poised at the beginning of the next row */
                 tif->tif_row = row + 1;
         if (e)
             (*tif->tif_postdecode)(tif, (tidata_t) buf,
                 tif->tif_scanlinesize);
     }
     return (e > 0 ? 1 : -1);
 }
tsize_t TIFFReadTile (TIFF * , tdata_t , uint32 , uint32 , uint32 , tsample_t)
Definition at line 330 of file tif_read.c.
References TIFFCheckRead(), TIFFCheckTile(), TIFFComputeTile(), and TIFFReadEncodedTile().
Referenced by gtTileContig(), and gtTileSeparate().
 {
     if (!TIFFCheckRead(tif, 1) || !TIFFCheckTile(tif, x, y, z, s))
         return (-1);
     return (TIFFReadEncodedTile(tif,
         TIFFComputeTile(tif, x, y, z, s), buf, (tsize_t) -1));
 }
int TIFFReassignTagToIgnore (enum TIFFIgnoreSense, int)
Definition at line 1309 of file tif_dir.c.
References FALSE, FIELD_LAST, TIS_EMPTY, TIS_EXTRACT, TIS_STORE, and TRUE.
 {
     static int TIFFignoretags [FIELD_LAST];
     static int tagcount = 0 ;
     int     i;                  /* Loop index */
     int     j;                  /* Loop index */
     switch (task)
     {
       case TIS_STORE:
         if ( tagcount < (FIELD_LAST - 1) )
         {
             for ( j = 0 ; j < tagcount ; ++j )
             {                   /* Do not add duplicate tag */
                 if ( TIFFignoretags [j] == TIFFtagID )
                     return (TRUE) ;
             }
             TIFFignoretags [tagcount++] = TIFFtagID ;
             return (TRUE) ;
         }
         break ;
       case TIS_EXTRACT:
         for ( i = 0 ; i < tagcount ; ++i )
         {
             if ( TIFFignoretags [i] == TIFFtagID )
                 return (TRUE) ;
         }
         break;
       case TIS_EMPTY:
         tagcount = 0 ;          /* Clear the list */
         return (TRUE) ;
       default:
         break;
     }
     return (FALSE);
 }
TIFFCodec* TIFFRegisterCODEC (uint16 , const char * , TIFFInitMethod)
Definition at line 192 of file tif_compress.c.
References _TIFFmalloc(), _codec::info, TIFFCodec::init, TIFFCodec::name, _codec::next, NULL, registeredCODECS, TIFFCodec::scheme, and TIFFErrorExt().
 {
     codec_t* cd = (codec_t*)
         _TIFFmalloc(sizeof (codec_t) + sizeof (TIFFCodec) + strlen(name)+1);
     if (cd != NULL) {
         cd->info = (TIFFCodec*) ((tidata_t) cd + sizeof (codec_t));
         cd->info->name = (char*)
             ((tidata_t) cd->info + sizeof (TIFFCodec));
         strcpy(cd->info->name, name);
         cd->info->scheme = scheme;
         cd->info->init = init;
         cd->next = registeredCODECS;
         registeredCODECS = cd;
     } else {
         TIFFErrorExt(0, "TIFFRegisterCODEC",
             "No space to register compression scheme %s", name);
         return NULL;
     }
     return (cd->info);
 }
void TIFFReverseBits (unsigned char * , unsigned long)
int TIFFRewriteDirectory (TIFF *)
Definition at line 1084 of file tif_dirwrite.c.
References ReadOK, SeekOK, tiff::tif_clientdata, tiff::tif_diroff, tiff::tif_flags, tiff::tif_header, tiff::tif_name, TIFFHeader::tiff_diroff, TIFF_MAGIC_SIZE, TIFF_SWAB, TIFF_VERSION_SIZE, TIFFErrorExt(), TIFFSeekFile, TIFFSwabLong(), TIFFSwabShort(), TIFFWriteDirectory(), and WriteOK.
 {
     static const char module[] = "TIFFRewriteDirectory";
     /* We don't need to do anything special if it hasn't been written. */
     if( tif->tif_diroff == 0 )
         return TIFFWriteDirectory( tif );
     /*
     ** Find and zero the pointer to this directory, so that TIFFLinkDirectory
     ** will cause it to be added after this directories current pre-link.
     */
     /* Is it the first directory in the file? */
     if (tif->tif_header.tiff_diroff == tif->tif_diroff)
     {
         tif->tif_header.tiff_diroff = 0;
         tif->tif_diroff = 0;
         TIFFSeekFile(tif, (toff_t)(TIFF_MAGIC_SIZE+TIFF_VERSION_SIZE),
              SEEK_SET);
         if (!WriteOK(tif, &(tif->tif_header.tiff_diroff),
                      sizeof (tif->tif_diroff)))
         {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Error updating TIFF header");
             return (0);
         }
     }
     else
     {
         toff_t  nextdir, off;
     nextdir = tif->tif_header.tiff_diroff;
     do {
         uint16 dircount;
         if (!SeekOK(tif, nextdir) ||
             !ReadOK(tif, &dircount, sizeof (dircount))) {
             TIFFErrorExt(tif->tif_clientdata, module, "Error fetching directory count");
             return (0);
         }
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabShort(&dircount);
         (void) TIFFSeekFile(tif,
             dircount * sizeof (TIFFDirEntry), SEEK_CUR);
         if (!ReadOK(tif, &nextdir, sizeof (nextdir))) {
             TIFFErrorExt(tif->tif_clientdata, module, "Error fetching directory link");
             return (0);
         }
         if (tif->tif_flags & TIFF_SWAB)
             TIFFSwabLong(&nextdir);
     } while (nextdir != tif->tif_diroff && nextdir != 0);
         off = TIFFSeekFile(tif, 0, SEEK_CUR); /* get current offset */
         (void) TIFFSeekFile(tif, off - (toff_t)sizeof(nextdir), SEEK_SET);
         tif->tif_diroff = 0;
     if (!WriteOK(tif, &(tif->tif_diroff), sizeof (nextdir))) {
         TIFFErrorExt(tif->tif_clientdata, module, "Error writing directory link");
         return (0);
     }
     }
     /*
     ** Now use TIFFWriteDirectory() normally.
     */
     return TIFFWriteDirectory( tif );
 }
int TIFFRGBAImageBegin (TIFFRGBAImage * , TIFF * , int , char [1024])
Definition at line 222 of file tif_getimage.c.
References _TIFFmalloc(), _TIFFmemcpy(), _TIFFRGBAImage::alpha, _TIFFRGBAImage::bitspersample, _TIFFRGBAImage::bluecmap, _TIFFRGBAImage::BWmap, _TIFFRGBAImage::cielab, _TIFFRGBAImage::col_offset, COMPRESSION_JPEG, COMPRESSION_OJPEG, COMPRESSION_SGILOG, COMPRESSION_SGILOG24, EXTRASAMPLE_ASSOCALPHA, EXTRASAMPLE_UNASSALPHA, EXTRASAMPLE_UNSPECIFIED, _TIFFRGBAImage::get, _TIFFRGBAImage::greencmap, gtStripContig(), gtStripSeparate(), gtTileContig(), gtTileSeparate(), _TIFFRGBAImage::height, INKSET_CMYK, isCCITTCompression(), _TIFFRGBAImage::isContig, JPEGCOLORMODE_RGB, _TIFFRGBAImage::Map, NULL, _TIFFRGBAImage::orientation, ORIENTATION_BOTLEFT, _TIFFRGBAImage::PALmap, _TIFFRGBAImage::photometric, PHOTOMETRIC_CIELAB, PHOTOMETRIC_LOGL, PHOTOMETRIC_LOGLUV, PHOTOMETRIC_MINISBLACK, PHOTOMETRIC_MINISWHITE, PHOTOMETRIC_PALETTE, PHOTOMETRIC_RGB, PHOTOMETRIC_SEPARATED, PHOTOMETRIC_YCBCR, photoTag, pickTileContigCase(), pickTileSeparateCase(), PLANARCONFIG_CONTIG, PLANARCONFIG_SEPARATE, _TIFFRGBAImage::redcmap, _TIFFRGBAImage::req_orientation, _TIFFRGBAImage::row_offset, _TIFFRGBAImage::samplesperpixel, SGILOGDATAFMT_8BIT, _TIFFRGBAImage::stoponerr, _TIFFRGBAImage::tif, TIFFGetField(), TIFFGetFieldDefaulted(), TIFFIsTiled(), TIFFSetField(), TIFFTAG_BITSPERSAMPLE, TIFFTAG_COLORMAP, TIFFTAG_COMPRESSION, TIFFTAG_EXTRASAMPLES, TIFFTAG_IMAGELENGTH, TIFFTAG_IMAGEWIDTH, TIFFTAG_INKSET, TIFFTAG_JPEGCOLORMODE, TIFFTAG_ORIENTATION, TIFFTAG_PHOTOMETRIC, TIFFTAG_PLANARCONFIG, TIFFTAG_SAMPLESPERPIXEL, TIFFTAG_SGILOGDATAFMT, _TIFFRGBAImage::width, and _TIFFRGBAImage::ycbcr.
Referenced by TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), and TIFFReadRGBATile().
 {
     uint16* sampleinfo;
     uint16 extrasamples;
     uint16 planarconfig;
     uint16 compress;
     int colorchannels;
     uint16 *red_orig, *green_orig, *blue_orig;
     int n_color;
     /* Initialize to normal values */
     img->row_offset = 0;
     img->col_offset = 0;
     img->redcmap = NULL;
     img->greencmap = NULL;
     img->bluecmap = NULL;
     img->req_orientation = ORIENTATION_BOTLEFT;     /* It is the default */
     img->tif = tif;
     img->stoponerr = stop;
     TIFFGetFieldDefaulted(tif, TIFFTAG_BITSPERSAMPLE, &img->bitspersample);
     switch (img->bitspersample) {
     case 1: case 2: case 4:
     case 8: case 16:
     break;
     default:
     sprintf(emsg, "Sorry, can not handle images with %d-bit samples",
         img->bitspersample);
     return (0);
     }
     img->alpha = 0;
     TIFFGetFieldDefaulted(tif, TIFFTAG_SAMPLESPERPIXEL, &img->samplesperpixel);
     TIFFGetFieldDefaulted(tif, TIFFTAG_EXTRASAMPLES,
     &extrasamples, &sampleinfo);
     if (extrasamples >= 1)
     {
     switch (sampleinfo[0]) {
     case EXTRASAMPLE_UNSPECIFIED:   /* Workaround for some images without */
         if (img->samplesperpixel > 3)   /* correct info about alpha channel */
             img->alpha = EXTRASAMPLE_ASSOCALPHA;
         break;
     case EXTRASAMPLE_ASSOCALPHA:    /* data is pre-multiplied */
     case EXTRASAMPLE_UNASSALPHA:    /* data is not pre-multiplied */
         img->alpha = sampleinfo[0];
         break;
     }
     }
 #ifdef DEFAULT_EXTRASAMPLE_AS_ALPHA
     if( !TIFFGetField(tif, TIFFTAG_PHOTOMETRIC, &img->photometric))
         img->photometric = PHOTOMETRIC_MINISWHITE;
     if( extrasamples == 0
         && img->samplesperpixel == 4
         && img->photometric == PHOTOMETRIC_RGB )
     {
         img->alpha = EXTRASAMPLE_ASSOCALPHA;
         extrasamples = 1;
     }
 #endif
     colorchannels = img->samplesperpixel - extrasamples;
     TIFFGetFieldDefaulted(tif, TIFFTAG_COMPRESSION, &compress);
     TIFFGetFieldDefaulted(tif, TIFFTAG_PLANARCONFIG, &planarconfig);
     if (!TIFFGetField(tif, TIFFTAG_PHOTOMETRIC, &img->photometric)) {
     switch (colorchannels) {
     case 1:
         if (isCCITTCompression(tif))
         img->photometric = PHOTOMETRIC_MINISWHITE;
         else
         img->photometric = PHOTOMETRIC_MINISBLACK;
         break;
     case 3:
         img->photometric = PHOTOMETRIC_RGB;
         break;
     default:
         sprintf(emsg, "Missing needed %s tag", photoTag);
         return (0);
     }
     }
     switch (img->photometric) {
     case PHOTOMETRIC_PALETTE:
     if (!TIFFGetField(tif, TIFFTAG_COLORMAP,
         &red_orig, &green_orig, &blue_orig)) {
         sprintf(emsg, "Missing required \"Colormap\" tag");
         return (0);
     }
         /* copy the colormaps so we can modify them */
         n_color = (1L << img->bitspersample);
         img->redcmap = (uint16 *) _TIFFmalloc(sizeof(uint16)*n_color);
         img->greencmap = (uint16 *) _TIFFmalloc(sizeof(uint16)*n_color);
         img->bluecmap = (uint16 *) _TIFFmalloc(sizeof(uint16)*n_color);
         if( !img->redcmap || !img->greencmap || !img->bluecmap ) {
         sprintf(emsg, "Out of memory for colormap copy");
         return (0);
         }
         _TIFFmemcpy( img->redcmap, red_orig, n_color * 2 );
         _TIFFmemcpy( img->greencmap, green_orig, n_color * 2 );
         _TIFFmemcpy( img->bluecmap, blue_orig, n_color * 2 );
     /* fall thru... */
     case PHOTOMETRIC_MINISWHITE:
     case PHOTOMETRIC_MINISBLACK:
     if (planarconfig == PLANARCONFIG_CONTIG
             && img->samplesperpixel != 1
             && img->bitspersample < 8 ) {
         sprintf(emsg,
                     "Sorry, can not handle contiguous data with %s=%d, "
                     "and %s=%d and Bits/Sample=%d",
                     photoTag, img->photometric,
                     "Samples/pixel", img->samplesperpixel,
                     img->bitspersample);
         return (0);
     }
     break;
     case PHOTOMETRIC_YCBCR:
     if (planarconfig != PLANARCONFIG_CONTIG) {
         sprintf(emsg, "Sorry, can not handle YCbCr images with %s=%d",
         "Planarconfiguration", planarconfig);
         return (0);
     }
     /* It would probably be nice to have a reality check here. */
     if (planarconfig == PLANARCONFIG_CONTIG)
         /* can rely on libjpeg to convert to RGB */
         /* XXX should restore current state on exit */
         switch (compress) {
         case COMPRESSION_OJPEG:
         case COMPRESSION_JPEG:
             TIFFSetField(tif, TIFFTAG_JPEGCOLORMODE, JPEGCOLORMODE_RGB);
             img->photometric = PHOTOMETRIC_RGB;
                     break;
                 default:
                     /* do nothing */;
                     break;
         }
     break;
     case PHOTOMETRIC_RGB:
     if (colorchannels < 3) {
         sprintf(emsg, "Sorry, can not handle RGB image with %s=%d",
         "Color channels", colorchannels);
         return (0);
     }
     break;
     case PHOTOMETRIC_SEPARATED: {
     uint16 inkset;
     TIFFGetFieldDefaulted(tif, TIFFTAG_INKSET, &inkset);
     if (inkset != INKSET_CMYK) {
         sprintf(emsg, "Sorry, can not handle separated image with %s=%d",
         "InkSet", inkset);
         return (0);
     }
     if (img->samplesperpixel < 4) {
         sprintf(emsg, "Sorry, can not handle separated image with %s=%d",
         "Samples/pixel", img->samplesperpixel);
         return (0);
     }
     break;
     }
     case PHOTOMETRIC_LOGL:
     if (compress != COMPRESSION_SGILOG) {
         sprintf(emsg, "Sorry, LogL data must have %s=%d",
         "Compression", COMPRESSION_SGILOG);
         return (0);
     }
     TIFFSetField(tif, TIFFTAG_SGILOGDATAFMT, SGILOGDATAFMT_8BIT);
     img->photometric = PHOTOMETRIC_MINISBLACK;  /* little white lie */
     img->bitspersample = 8;
     break;
     case PHOTOMETRIC_LOGLUV:
     if (compress != COMPRESSION_SGILOG && compress != COMPRESSION_SGILOG24) {
         sprintf(emsg, "Sorry, LogLuv data must have %s=%d or %d",
         "Compression", COMPRESSION_SGILOG, COMPRESSION_SGILOG24);
         return (0);
     }
     if (planarconfig != PLANARCONFIG_CONTIG) {
         sprintf(emsg, "Sorry, can not handle LogLuv images with %s=%d",
         "Planarconfiguration", planarconfig);
         return (0);
     }
     TIFFSetField(tif, TIFFTAG_SGILOGDATAFMT, SGILOGDATAFMT_8BIT);
     img->photometric = PHOTOMETRIC_RGB;     /* little white lie */
     img->bitspersample = 8;
     break;
     case PHOTOMETRIC_CIELAB:
     break;
     default:
     sprintf(emsg, "Sorry, can not handle image with %s=%d",
         photoTag, img->photometric);
     return (0);
     }
     img->Map = NULL;
     img->BWmap = NULL;
     img->PALmap = NULL;
     img->ycbcr = NULL;
     img->cielab = NULL;
     TIFFGetField(tif, TIFFTAG_IMAGEWIDTH, &img->width);
     TIFFGetField(tif, TIFFTAG_IMAGELENGTH, &img->height);
     TIFFGetFieldDefaulted(tif, TIFFTAG_ORIENTATION, &img->orientation);
     img->isContig =
     !(planarconfig == PLANARCONFIG_SEPARATE && colorchannels > 1);
     if (img->isContig) {
     img->get = TIFFIsTiled(tif) ? gtTileContig : gtStripContig;
     if (!pickTileContigCase(img)) {
         sprintf(emsg, "Sorry, can not handle image");
         return 0;
     }
     } else {
     img->get = TIFFIsTiled(tif) ? gtTileSeparate : gtStripSeparate;
     if (!pickTileSeparateCase(img)) {
         sprintf(emsg, "Sorry, can not handle image");
         return 0;
     }
     }
     return 1;
 }
void TIFFRGBAImageEnd (TIFFRGBAImage *)
Definition at line 190 of file tif_getimage.c.
References _TIFFfree(), _TIFFRGBAImage::bluecmap, _TIFFRGBAImage::BWmap, _TIFFRGBAImage::cielab, _TIFFRGBAImage::greencmap, _TIFFRGBAImage::Map, NULL, _TIFFRGBAImage::PALmap, _TIFFRGBAImage::redcmap, and _TIFFRGBAImage::ycbcr.
Referenced by TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), and TIFFReadRGBATile().
 {
     if (img->Map)
         _TIFFfree(img->Map), img->Map = NULL;
     if (img->BWmap)
         _TIFFfree(img->BWmap), img->BWmap = NULL;
     if (img->PALmap)
         _TIFFfree(img->PALmap), img->PALmap = NULL;
     if (img->ycbcr)
         _TIFFfree(img->ycbcr), img->ycbcr = NULL;
     if (img->cielab)
         _TIFFfree(img->cielab), img->cielab = NULL;
     if( img->redcmap ) {
         _TIFFfree( img->redcmap );
         _TIFFfree( img->greencmap );
         _TIFFfree( img->bluecmap );
     }
 }
int TIFFRGBAImageGet (TIFFRGBAImage * , uint32 * , uint32 , uint32)
Definition at line 442 of file tif_getimage.c.
References _TIFFRGBAImage::any, _TIFFRGBAImage::get, NULL, _TIFFRGBAImage::put, _TIFFRGBAImage::tif, tiff::tif_clientdata, TIFFErrorExt(), and TIFFFileName().
Referenced by TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), and TIFFReadRGBATile().
 {
     if (img->get == NULL) {
         TIFFErrorExt(img->tif->tif_clientdata, TIFFFileName(img->tif), "No \"get\" routine setup");
         return (0);
     }
     if (img->put.any == NULL) {
         TIFFErrorExt(img->tif->tif_clientdata, TIFFFileName(img->tif),
         "No \"put\" routine setupl; probably can not handle image format");
         return (0);
     }
     return (*img->get)(img, raster, w, h);
 }
int TIFFRGBAImageOK (TIFF * , char [1024])
Definition at line 73 of file tif_getimage.c.
References COMPRESSION_SGILOG, COMPRESSION_SGILOG24, INKSET_CMYK, PHOTOMETRIC_CIELAB, PHOTOMETRIC_LOGL, PHOTOMETRIC_LOGLUV, PHOTOMETRIC_MINISBLACK, PHOTOMETRIC_MINISWHITE, PHOTOMETRIC_PALETTE, PHOTOMETRIC_RGB, PHOTOMETRIC_SEPARATED, PHOTOMETRIC_YCBCR, photoTag, PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_compression, TIFFDirectory::td_extrasamples, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_decodestatus, tiff::tif_dir, TIFFGetField(), TIFFGetFieldDefaulted(), TIFFTAG_INKSET, and TIFFTAG_PHOTOMETRIC.
Referenced by TIFFReadRGBAImageOriented(), TIFFReadRGBAStrip(), and TIFFReadRGBATile().
 {
     TIFFDirectory* td = &tif->tif_dir;
     uint16 photometric;
     int colorchannels;
     if (!tif->tif_decodestatus) {
     sprintf(emsg, "Sorry, requested compression method is not configured");
     return (0);
     }
     switch (td->td_bitspersample) {
     case 1: case 2: case 4:
     case 8: case 16:
     break;
     default:
     sprintf(emsg, "Sorry, can not handle images with %d-bit samples",
         td->td_bitspersample);
     return (0);
     }
     colorchannels = td->td_samplesperpixel - td->td_extrasamples;
     if (!TIFFGetField(tif, TIFFTAG_PHOTOMETRIC, &photometric)) {
     switch (colorchannels) {
     case 1:
         photometric = PHOTOMETRIC_MINISBLACK;
         break;
     case 3:
         photometric = PHOTOMETRIC_RGB;
         break;
     default:
         sprintf(emsg, "Missing needed %s tag", photoTag);
         return (0);
     }
     }
     switch (photometric) {
     case PHOTOMETRIC_MINISWHITE:
     case PHOTOMETRIC_MINISBLACK:
     case PHOTOMETRIC_PALETTE:
     if (td->td_planarconfig == PLANARCONFIG_CONTIG
             && td->td_samplesperpixel != 1
             && td->td_bitspersample < 8 ) {
         sprintf(emsg,
                     "Sorry, can not handle contiguous data with %s=%d, "
                     "and %s=%d and Bits/Sample=%d",
                     photoTag, photometric,
                     "Samples/pixel", td->td_samplesperpixel,
                     td->td_bitspersample);
         return (0);
     }
         /*
         ** We should likely validate that any extra samples are either
         ** to be ignored, or are alpha, and if alpha we should try to use
         ** them.  But for now we won't bother with this.
         */
     break;
     case PHOTOMETRIC_YCBCR:
     if (td->td_planarconfig != PLANARCONFIG_CONTIG) {
         sprintf(emsg, "Sorry, can not handle YCbCr images with %s=%d",
         "Planarconfiguration", td->td_planarconfig);
         return (0);
     }
     break;
     case PHOTOMETRIC_RGB:
     if (colorchannels < 3) {
         sprintf(emsg, "Sorry, can not handle RGB image with %s=%d",
         "Color channels", colorchannels);
         return (0);
     }
     break;
     case PHOTOMETRIC_SEPARATED:
     {
         uint16 inkset;
         TIFFGetFieldDefaulted(tif, TIFFTAG_INKSET, &inkset);
         if (inkset != INKSET_CMYK) {
             sprintf(emsg,
                 "Sorry, can not handle separated image with %s=%d",
                 "InkSet", inkset);
             return 0;
         }
         if (td->td_samplesperpixel < 4) {
             sprintf(emsg,
                 "Sorry, can not handle separated image with %s=%d",
                 "Samples/pixel", td->td_samplesperpixel);
             return 0;
         }
         break;
     }
     case PHOTOMETRIC_LOGL:
     if (td->td_compression != COMPRESSION_SGILOG) {
         sprintf(emsg, "Sorry, LogL data must have %s=%d",
         "Compression", COMPRESSION_SGILOG);
         return (0);
     }
     break;
     case PHOTOMETRIC_LOGLUV:
     if (td->td_compression != COMPRESSION_SGILOG &&
         td->td_compression != COMPRESSION_SGILOG24) {
         sprintf(emsg, "Sorry, LogLuv data must have %s=%d or %d",
         "Compression", COMPRESSION_SGILOG, COMPRESSION_SGILOG24);
         return (0);
     }
     if (td->td_planarconfig != PLANARCONFIG_CONTIG) {
         sprintf(emsg, "Sorry, can not handle LogLuv images with %s=%d",
         "Planarconfiguration", td->td_planarconfig);
         return (0);
     }
     break;
     case PHOTOMETRIC_CIELAB:
     break;
     default:
     sprintf(emsg, "Sorry, can not handle image with %s=%d",
         photoTag, photometric);
     return (0);
     }
     return (1);
 }
tsize_t TIFFScanlineSize (TIFF *)
Definition at line 225 of file tif_strip.c.
References multiply(), PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_imagewidth, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, tiff::tif_dir, and TIFFhowmany8.
Referenced by _TIFFDefaultStripSize(), EstimateStripByteCounts(), gtStripContig(), gtStripSeparate(), PredictorSetup(), TIFFReadDirectory(), TIFFVStripSize(), and TIFFWriteCheck().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t scanline;
     scanline = multiply (tif, td->td_bitspersample, td->td_imagewidth,
                  "TIFFScanlineSize");
     if (td->td_planarconfig == PLANARCONFIG_CONTIG)
         scanline = multiply (tif, scanline, td->td_samplesperpixel,
                      "TIFFScanlineSize");
     return ((tsize_t) TIFFhowmany8(scanline));
 }
thandle_t TIFFSetClientdata (TIFF * , thandle_t)
Definition at line 513 of file tif_open.c.
References tiff::tif_clientdata.
 {
     thandle_t m = tif->tif_clientdata;
     tif->tif_clientdata = newvalue;
     return m;
 }
void TIFFSetClientInfo (TIFF * , void * , const char *)
Definition at line 80 of file tif_extension.c.
References _TIFFmalloc(), client_info::data, client_info::name, client_info::next, NULL, and tiff::tif_clientinfo.
 {
     TIFFClientInfoLink *link = tif->tif_clientinfo;
     /*
     ** Do we have an existing link with this name?  If so, just
     ** set it.
     */
     while( link != NULL && strcmp(link->name,name) != 0 )
         link = link->next;
     if( link != NULL )
     {
         link->data = data;
         return;
     }
     /*
     ** Create a new link.
     */
     link = (TIFFClientInfoLink *) _TIFFmalloc(sizeof(TIFFClientInfoLink));
     assert (link != NULL);
     link->next = tif->tif_clientinfo;
     link->name = (char *) _TIFFmalloc(strlen(name)+1);
     assert (link->name != NULL);
     strcpy(link->name, name);
     link->data = data;
     tif->tif_clientinfo = link;
 }
int TIFFSetDirectory (TIFF * , tdir_t)
Definition at line 1164 of file tif_dir.c.
References NULL, tiff::tif_curdir, tiff::tif_dirnumber, tiff::tif_header, tiff::tif_nextdiroff, TIFFHeader::tiff_diroff, TIFFAdvanceDirectory(), and TIFFReadDirectory().
 {
     toff_t nextdir;
     tdir_t n;
     nextdir = tif->tif_header.tiff_diroff;
     for (n = dirn; n > 0 && nextdir != 0; n--)
         if (!TIFFAdvanceDirectory(tif, &nextdir, NULL))
             return (0);
     tif->tif_nextdiroff = nextdir;
     /*
      * Set curdir to the actual directory index.  The
      * -1 is because TIFFReadDirectory will increment
      * tif_curdir after successfully reading the directory.
      */
     tif->tif_curdir = (dirn - n) - 1;
     /*
      * Reset tif_dirnumber counter and start new list of seen directories.
      * We need this to prevent IFD loops.
      */
     tif->tif_dirnumber = 0;
     return (TIFFReadDirectory(tif));
 }
TIFFErrorHandler TIFFSetErrorHandler (TIFFErrorHandler)
Definition at line 35 of file tif_error.c.
References _TIFFerrorHandler.
Referenced by TIFFImageIO::CanReadFile().
 {
     TIFFErrorHandler prev = _TIFFerrorHandler;
     _TIFFerrorHandler = handler;
     return (prev);
 }
TIFFErrorHandlerExt TIFFSetErrorHandlerExt (TIFFErrorHandlerExt)
Definition at line 43 of file tif_error.c.
References _TIFFerrorHandlerExt.
 {
     TIFFErrorHandlerExt prev = _TIFFerrorHandlerExt;
     _TIFFerrorHandlerExt = handler;
     return (prev);
 }
int TIFFSetField (TIFF * , ttag_t , ...)
Definition at line 627 of file tif_dir.c.
References TIFFVSetField().
Referenced by ChopUpSingleUncompressedStrip(), rcWindow::tiff(), TIFFDefaultDirectory(), TIFFFetchNormalTag(), TIFFFetchRefBlackWhite(), TIFFFetchShortPair(), TIFFReadDirectory(), and TIFFRGBAImageBegin().
 {
     va_list ap;
     int status;
     va_start(ap, tag);
     status = TIFFVSetField(tif, tag, ap);
     va_end(ap);
     return (status);
 }
const char* TIFFSetFileName (TIFF * , const char *)
Definition at line 473 of file tif_open.c.
References tiff::tif_name.
 {
     const char* old_name = tif->tif_name;
     tif->tif_name = (char *)name;
     return (old_name);
 }
int TIFFSetFileno (TIFF * , int)
Definition at line 493 of file tif_open.c.
References tiff::tif_fd.
 {
         int old_fd = tif->tif_fd;
     tif->tif_fd = fd;
     return old_fd;
 }
int TIFFSetMode (TIFF * , int)
Definition at line 533 of file tif_open.c.
References tiff::tif_mode.
 {
     int old_mode = tif->tif_mode;
     tif->tif_mode = mode;
     return (old_mode);
 }
int TIFFSetSubDirectory (TIFF * , uint32)
Definition at line 1195 of file tif_dir.c.
References tiff::tif_dirnumber, tiff::tif_nextdiroff, and TIFFReadDirectory().
 {
     tif->tif_nextdiroff = diroff;
     /*
      * Reset tif_dirnumber counter and start new list of seen directories.
      * We need this to prevent IFD loops.
      */
     tif->tif_dirnumber = 0;
     return (TIFFReadDirectory(tif));
 }
TIFFExtendProc TIFFSetTagExtender (TIFFExtendProc)
Definition at line 998 of file tif_dir.c.
References _TIFFextender.
 {
     TIFFExtendProc prev = _TIFFextender;
     _TIFFextender = extender;
     return (prev);
 }
int TIFFSetupStrips (TIFF *)
Definition at line 449 of file tif_write.c.
References _TIFFmalloc(), _TIFFmemset(), FIELD_ROWSPERSTRIP, FIELD_STRIPBYTECOUNTS, FIELD_STRIPOFFSETS, FIELD_TILEDIMENSIONS, isTiled, isUnspecified, NULL, PLANARCONFIG_SEPARATE, TIFFDirectory::td_nstrips, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripoffset, TIFFDirectory::td_stripsperimage, tiff::tif_dir, TIFFNumberOfStrips(), TIFFNumberOfTiles(), and TIFFSetFieldBit.
Referenced by TIFFCheckpointDirectory(), and TIFFWriteCheck().
 {
     TIFFDirectory* td = &tif->tif_dir;
     if (isTiled(tif))
         td->td_stripsperimage =
             isUnspecified(tif, FIELD_TILEDIMENSIONS) ?
             td->td_samplesperpixel : TIFFNumberOfTiles(tif);
     else
         td->td_stripsperimage =
             isUnspecified(tif, FIELD_ROWSPERSTRIP) ?
             td->td_samplesperpixel : TIFFNumberOfStrips(tif);
     td->td_nstrips = td->td_stripsperimage;
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE)
         td->td_stripsperimage /= td->td_samplesperpixel;
     td->td_stripoffset = (uint32 *)
         _TIFFmalloc(td->td_nstrips * sizeof (uint32));
     td->td_stripbytecount = (uint32 *)
         _TIFFmalloc(td->td_nstrips * sizeof (uint32));
     if (td->td_stripoffset == NULL || td->td_stripbytecount == NULL)
         return (0);
     /*
      * Place data at the end-of-file
      * (by setting offsets to zero).
      */
     _TIFFmemset(td->td_stripoffset, 0, td->td_nstrips*sizeof (uint32));
     _TIFFmemset(td->td_stripbytecount, 0, td->td_nstrips*sizeof (uint32));
     TIFFSetFieldBit(tif, FIELD_STRIPOFFSETS);
     TIFFSetFieldBit(tif, FIELD_STRIPBYTECOUNTS);
     return (1);
 }
TIFFErrorHandler TIFFSetWarningHandler (TIFFErrorHandler)
Definition at line 35 of file tif_warning.c.
References _TIFFwarningHandler.
 {
     TIFFErrorHandler prev = _TIFFwarningHandler;
     _TIFFwarningHandler = handler;
     return (prev);
 }
TIFFErrorHandlerExt TIFFSetWarningHandlerExt (TIFFErrorHandlerExt)
Definition at line 43 of file tif_warning.c.
References _TIFFwarningHandlerExt.
 {
     TIFFErrorHandlerExt prev = _TIFFwarningHandlerExt;
     _TIFFwarningHandlerExt = handler;
     return (prev);
 }
void TIFFSetWriteOffset (TIFF * , toff_t)
Definition at line 722 of file tif_write.c.
References tiff::tif_curoff.
Referenced by TIFFCheckpointDirectory().
 {
     tif->tif_curoff = off;
 }
tsize_t TIFFStripSize (TIFF *)
Definition at line 181 of file tif_strip.c.
References TIFFDirectory::td_imagelength, TIFFDirectory::td_rowsperstrip, tiff::tif_dir, and TIFFVStripSize().
Referenced by gtStripContig(), gtStripSeparate(), TIFFReadDirectory(), and TIFFWriteBufferSetup().
 {
     TIFFDirectory* td = &tif->tif_dir;
     uint32 rps = td->td_rowsperstrip;
     if (rps > td->td_imagelength)
         rps = td->td_imagelength;
     return (TIFFVStripSize(tif, rps));
 }
void TIFFSwabArrayOfDouble (double * , unsigned long)
void TIFFSwabArrayOfLong (uint32 * , unsigned long)
void TIFFSwabArrayOfShort (uint16 * , unsigned long)
void TIFFSwabArrayOfTriples (uint8 * , unsigned long)
Definition at line 75 of file tif_swab.c.
Referenced by _TIFFSwab24BitData().
 {
     unsigned char* cp;
     unsigned char t;
     /* XXX unroll loop some */
     while (n-- > 0) {
         cp = (unsigned char*) tp;
         t = cp[2]; cp[2] = cp[0]; cp[0] = t;
         tp += 3;
     }
 }
void TIFFSwabDouble (double *)
Definition at line 108 of file tif_swab.c.
References TIFFSwabArrayOfLong().
 {
         register uint32* lp = (uint32*) dp;
         uint32 t;
     TIFFSwabArrayOfLong(lp, 2);
     t = lp[0]; lp[0] = lp[1]; lp[1] = t;
 }
void TIFFSwabLong (uint32 *)
Definition at line 47 of file tif_swab.c.
Referenced by _TIFFWriteDirectory(), TIFFAdvanceDirectory(), TIFFClientOpen(), TIFFFetchString(), TIFFLinkDirectory(), TIFFReadDirectory(), TIFFRewriteDirectory(), and TIFFUnlinkDirectory().
 {
     register unsigned char* cp = (unsigned char*) lp;
     unsigned char t;
     t = cp[3]; cp[3] = cp[0]; cp[0] = t;
     t = cp[2]; cp[2] = cp[1]; cp[1] = t;
 }
void TIFFSwabShort (uint16 *)
Definition at line 36 of file tif_swab.c.
Referenced by _TIFFWriteDirectory(), TIFFAdvanceDirectory(), TIFFClientOpen(), TIFFLinkDirectory(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFRewriteDirectory().
 {
     register unsigned char* cp = (unsigned char*) wp;
     unsigned char t;
     t = cp[1]; cp[1] = cp[0]; cp[0] = t;
 }
tsize_t TIFFTileRowSize (TIFF *)
Definition at line 166 of file tif_tile.c.
References multiply(), PLANARCONFIG_CONTIG, TIFFDirectory::td_bitspersample, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_dir, and TIFFhowmany8.
Referenced by gtTileContig(), gtTileSeparate(), PredictorSetup(), and TIFFVTileSize().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t rowsize;
     if (td->td_tilelength == 0 || td->td_tilewidth == 0)
         return ((tsize_t) 0);
     rowsize = multiply(tif, td->td_bitspersample, td->td_tilewidth,
                "TIFFTileRowSize");
     if (td->td_planarconfig == PLANARCONFIG_CONTIG)
         rowsize = multiply(tif, rowsize, td->td_samplesperpixel,
                    "TIFFTileRowSize");
     return ((tsize_t) TIFFhowmany8(rowsize));
 }
tsize_t TIFFTileSize (TIFF *)
Definition at line 233 of file tif_tile.c.
References TIFFDirectory::td_tilelength, tiff::tif_dir, and TIFFVTileSize().
Referenced by gtTileContig(), gtTileSeparate(), TIFFReadDirectory(), and TIFFWriteCheck().
 {
     return (TIFFVTileSize(tif, tif->tif_dir.td_tilelength));
 }
int TIFFUnlinkDirectory (TIFF * , tdir_t)
Definition at line 1229 of file tif_dir.c.
References _TIFFfree(), NULL, tiff::tif_cleanup, tiff::tif_clientdata, tiff::tif_curoff, tiff::tif_curstrip, tiff::tif_diroff, tiff::tif_flags, tiff::tif_header, tiff::tif_mode, tiff::tif_nextdiroff, tiff::tif_rawcc, tiff::tif_rawdata, tiff::tif_row, TIFF_BEENWRITING, TIFF_BUFFERSETUP, TIFFHeader::tiff_diroff, TIFF_MYBUFFER, TIFF_POSTENCODE, TIFF_SWAB, TIFFAdvanceDirectory(), TIFFDefaultDirectory(), TIFFErrorExt(), TIFFFreeDirectory(), TIFFSeekFile, TIFFSwabLong(), and WriteOK.
 {
     static const char module[] = "TIFFUnlinkDirectory";
     toff_t nextdir;
     toff_t off;
     tdir_t n;
     if (tif->tif_mode == O_RDONLY) {
         TIFFErrorExt(tif->tif_clientdata, module,
                              "Can not unlink directory in read-only file");
         return (0);
     }
     /*
      * Go to the directory before the one we want
      * to unlink and nab the offset of the link
      * field we'll need to patch.
      */
     nextdir = tif->tif_header.tiff_diroff;
     off = sizeof (uint16) + sizeof (uint16);
     for (n = dirn-1; n > 0; n--) {
         if (nextdir == 0) {
             TIFFErrorExt(tif->tif_clientdata, module, "Directory %d does not exist", dirn);
             return (0);
         }
         if (!TIFFAdvanceDirectory(tif, &nextdir, &off))
             return (0);
     }
     /*
      * Advance to the directory to be unlinked and fetch
      * the offset of the directory that follows.
      */
     if (!TIFFAdvanceDirectory(tif, &nextdir, NULL))
         return (0);
     /*
      * Go back and patch the link field of the preceding
      * directory to point to the offset of the directory
      * that follows.
      */
     (void) TIFFSeekFile(tif, off, SEEK_SET);
     if (tif->tif_flags & TIFF_SWAB)
         TIFFSwabLong(&nextdir);
     if (!WriteOK(tif, &nextdir, sizeof (uint32))) {
         TIFFErrorExt(tif->tif_clientdata, module, "Error writing directory link");
         return (0);
     }
     /*
      * Leave directory state setup safely.  We don't have
      * facilities for doing inserting and removing directories,
      * so it's safest to just invalidate everything.  This
      * means that the caller can only append to the directory
      * chain.
      */
     (*tif->tif_cleanup)(tif);
     if ((tif->tif_flags & TIFF_MYBUFFER) && tif->tif_rawdata) {
         _TIFFfree(tif->tif_rawdata);
         tif->tif_rawdata = NULL;
         tif->tif_rawcc = 0;
     }
     tif->tif_flags &= ~(TIFF_BEENWRITING|TIFF_BUFFERSETUP|TIFF_POSTENCODE);
     TIFFFreeDirectory(tif);
     TIFFDefaultDirectory(tif);
     tif->tif_diroff = 0;            /* force link on next write */
     tif->tif_nextdiroff = 0;        /* next write must be at end */
     tif->tif_curoff = 0;
     tif->tif_row = (uint32) -1;
     tif->tif_curstrip = (tstrip_t) -1;
     return (1);
 }
void TIFFUnRegisterCODEC (TIFFCodec *)
Definition at line 215 of file tif_compress.c.
References _TIFFfree(), _codec::info, TIFFCodec::name, _codec::next, and TIFFErrorExt().
 {
     codec_t* cd;
     codec_t** pcd;
     for (pcd = &registeredCODECS; (cd = *pcd); pcd = &cd->next)
         if (cd->info == c) {
             *pcd = cd->next;
             _TIFFfree(cd);
             return;
         }
     TIFFErrorExt(0, "TIFFUnRegisterCODEC",
         "Cannot remove compression scheme %s; not registered", c->name);
 }
int TIFFVGetField (TIFF * , ttag_t , va_list)
Definition at line 943 of file tif_dir.c.
References _TIFFFindFieldInfo(), TIFFFieldInfo::field_bit, isPseudoTag, tiff::tif_tagmethods, TIFF_ANY, TIFFFieldSet, and TIFFTagMethods::vgetfield.
Referenced by TIFFGetField(), and TIFFVGetFieldDefaulted().
 {
     const TIFFFieldInfo* fip = _TIFFFindFieldInfo(tif, tag, TIFF_ANY);
     return (fip && (isPseudoTag(tag) || TIFFFieldSet(tif, fip->field_bit)) ?
         (*tif->tif_tagmethods.vgetfield)(tif, tag, ap) : 0);
 }
int TIFFVGetFieldDefaulted (TIFF * , ttag_t , va_list)
Definition at line 104 of file tif_aux.c.
References D50_X0, D50_Y0, D50_Z0, EXTRASAMPLE_ASSOCALPHA, INKSET_CMYK, PHOTOMETRIC_YCBCR, TIFFPredictorState::predictor, TIFFDirectory::td_bitspersample, TIFFDirectory::td_extrasamples, TIFFDirectory::td_fillorder, TIFFDirectory::td_imagedepth, TIFFDirectory::td_maxsamplevalue, TIFFDirectory::td_minsamplevalue, TIFFDirectory::td_orientation, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, TIFFDirectory::td_resolutionunit, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_sampleformat, TIFFDirectory::td_sampleinfo, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_subfiletype, TIFFDirectory::td_threshholding, TIFFDirectory::td_tiledepth, TIFFDirectory::td_transferfunction, TIFFDirectory::td_ycbcrpositioning, TIFFDirectory::td_ycbcrsubsampling, tiff::tif_clientdata, tiff::tif_data, tiff::tif_dir, tiff::tif_name, TIFFDefaultTransferFunction(), TIFFErrorExt(), TIFFTAG_BITSPERSAMPLE, TIFFTAG_DATATYPE, TIFFTAG_DOTRANGE, TIFFTAG_EXTRASAMPLES, TIFFTAG_FILLORDER, TIFFTAG_IMAGEDEPTH, TIFFTAG_INKSET, TIFFTAG_MATTEING, TIFFTAG_MAXSAMPLEVALUE, TIFFTAG_MINSAMPLEVALUE, TIFFTAG_NUMBEROFINKS, TIFFTAG_ORIENTATION, TIFFTAG_PLANARCONFIG, TIFFTAG_PREDICTOR, TIFFTAG_REFERENCEBLACKWHITE, TIFFTAG_RESOLUTIONUNIT, TIFFTAG_ROWSPERSTRIP, TIFFTAG_SAMPLEFORMAT, TIFFTAG_SAMPLESPERPIXEL, TIFFTAG_SUBFILETYPE, TIFFTAG_THRESHHOLDING, TIFFTAG_TILEDEPTH, TIFFTAG_TRANSFERFUNCTION, TIFFTAG_WHITEPOINT, TIFFTAG_YCBCRCOEFFICIENTS, TIFFTAG_YCBCRPOSITIONING, TIFFTAG_YCBCRSUBSAMPLING, and TIFFVGetField().
Referenced by TIFFGetFieldDefaulted().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (TIFFVGetField(tif, tag, ap))
         return (1);
     switch (tag) {
     case TIFFTAG_SUBFILETYPE:
         *va_arg(ap, uint32 *) = td->td_subfiletype;
         return (1);
     case TIFFTAG_BITSPERSAMPLE:
         *va_arg(ap, uint16 *) = td->td_bitspersample;
         return (1);
     case TIFFTAG_THRESHHOLDING:
         *va_arg(ap, uint16 *) = td->td_threshholding;
         return (1);
     case TIFFTAG_FILLORDER:
         *va_arg(ap, uint16 *) = td->td_fillorder;
         return (1);
     case TIFFTAG_ORIENTATION:
         *va_arg(ap, uint16 *) = td->td_orientation;
         return (1);
     case TIFFTAG_SAMPLESPERPIXEL:
         *va_arg(ap, uint16 *) = td->td_samplesperpixel;
         return (1);
     case TIFFTAG_ROWSPERSTRIP:
         *va_arg(ap, uint32 *) = td->td_rowsperstrip;
         return (1);
     case TIFFTAG_MINSAMPLEVALUE:
         *va_arg(ap, uint16 *) = td->td_minsamplevalue;
         return (1);
     case TIFFTAG_MAXSAMPLEVALUE:
         *va_arg(ap, uint16 *) = td->td_maxsamplevalue;
         return (1);
     case TIFFTAG_PLANARCONFIG:
         *va_arg(ap, uint16 *) = td->td_planarconfig;
         return (1);
     case TIFFTAG_RESOLUTIONUNIT:
         *va_arg(ap, uint16 *) = td->td_resolutionunit;
         return (1);
     case TIFFTAG_PREDICTOR:
                 {
             TIFFPredictorState* sp = (TIFFPredictorState*) tif->tif_data;
             *va_arg(ap, uint16*) = (uint16) sp->predictor;
             return 1;
                 }
     case TIFFTAG_DOTRANGE:
         *va_arg(ap, uint16 *) = 0;
         *va_arg(ap, uint16 *) = (1<<td->td_bitspersample)-1;
         return (1);
     case TIFFTAG_INKSET:
         *va_arg(ap, uint16 *) = INKSET_CMYK;
         return 1;
     case TIFFTAG_NUMBEROFINKS:
         *va_arg(ap, uint16 *) = 4;
         return (1);
     case TIFFTAG_EXTRASAMPLES:
         *va_arg(ap, uint16 *) = td->td_extrasamples;
         *va_arg(ap, uint16 **) = td->td_sampleinfo;
         return (1);
     case TIFFTAG_MATTEING:
         *va_arg(ap, uint16 *) =
             (td->td_extrasamples == 1 &&
              td->td_sampleinfo[0] == EXTRASAMPLE_ASSOCALPHA);
         return (1);
     case TIFFTAG_TILEDEPTH:
         *va_arg(ap, uint32 *) = td->td_tiledepth;
         return (1);
     case TIFFTAG_DATATYPE:
         *va_arg(ap, uint16 *) = td->td_sampleformat-1;
         return (1);
     case TIFFTAG_SAMPLEFORMAT:
         *va_arg(ap, uint16 *) = td->td_sampleformat;
                 return(1);
     case TIFFTAG_IMAGEDEPTH:
         *va_arg(ap, uint32 *) = td->td_imagedepth;
         return (1);
     case TIFFTAG_YCBCRCOEFFICIENTS:
         {
             /* defaults are from CCIR Recommendation 601-1 */
             float ycbcrcoeffs[] = { 0.299f, 0.587f, 0.114f };
             *va_arg(ap, float **) = ycbcrcoeffs;
             return 1;
         }
     case TIFFTAG_YCBCRSUBSAMPLING:
         *va_arg(ap, uint16 *) = td->td_ycbcrsubsampling[0];
         *va_arg(ap, uint16 *) = td->td_ycbcrsubsampling[1];
         return (1);
     case TIFFTAG_YCBCRPOSITIONING:
         *va_arg(ap, uint16 *) = td->td_ycbcrpositioning;
         return (1);
     case TIFFTAG_WHITEPOINT:
         {
             static float whitepoint[2];
             /* TIFF 6.0 specification tells that it is no default
                value for the WhitePoint, but AdobePhotoshop TIFF
                Technical Note tells that it should be CIE D50. */
             whitepoint[0] = D50_X0 / (D50_X0 + D50_Y0 + D50_Z0);
             whitepoint[1] = D50_Y0 / (D50_X0 + D50_Y0 + D50_Z0);
             *va_arg(ap, float **) = whitepoint;
             return 1;
         }
     case TIFFTAG_TRANSFERFUNCTION:
         if (!td->td_transferfunction[0] &&
             !TIFFDefaultTransferFunction(td)) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "No space for \"TransferFunction\" tag");
             return (0);
         }
         *va_arg(ap, uint16 **) = td->td_transferfunction[0];
         if (td->td_samplesperpixel - td->td_extrasamples > 1) {
             *va_arg(ap, uint16 **) = td->td_transferfunction[1];
             *va_arg(ap, uint16 **) = td->td_transferfunction[2];
         }
         return (1);
     case TIFFTAG_REFERENCEBLACKWHITE:
         {
             int i;
             static float ycbcr_refblackwhite[] =
             { 0.0F, 255.0F, 128.0F, 255.0F, 128.0F, 255.0F };
             static float rgb_refblackwhite[6];
             for (i = 0; i < 3; i++) {
                 rgb_refblackwhite[2 * i + 0] = 0.0F;
                 rgb_refblackwhite[2 * i + 1] =
                     (float)((1L<<td->td_bitspersample)-1L);
             }
             if (td->td_photometric == PHOTOMETRIC_YCBCR) {
                 /*
                  * YCbCr (Class Y) images must have the
                  * ReferenceBlackWhite tag set. Fix the
                  * broken images, which lacks that tag.
                  */
                 *va_arg(ap, float **) = ycbcr_refblackwhite;
             } else {
                 /*
                  * Assume RGB (Class R)
                  */
                 *va_arg(ap, float **) = rgb_refblackwhite;
             }
             return 1;
         }
     }
     return 0;
 }
int TIFFVSetField (TIFF * , ttag_t , va_list)
Definition at line 645 of file tif_dir.c.
References OkToChangeTag(), tiff::tif_tagmethods, and TIFFTagMethods::vsetfield.
Referenced by TIFFSetField().
 {
     return OkToChangeTag(tif, tag) ?
         (*tif->tif_tagmethods.vsetfield)(tif, tag, ap) : 0;
 }
tsize_t TIFFVStripSize (TIFF * , uint32)
Definition at line 107 of file tif_strip.c.
References isUpSampled, multiply(), PHOTOMETRIC_YCBCR, PLANARCONFIG_CONTIG, summarize(), TIFFDirectory::td_bitspersample, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), TIFFGetField(), TIFFhowmany8, TIFFroundup, TIFFScanlineSize(), and TIFFTAG_YCBCRSUBSAMPLING.
Referenced by TIFFReadEncodedStrip(), and TIFFStripSize().
 {
     TIFFDirectory *td = &tif->tif_dir;
     if (nrows == (uint32) -1)
         nrows = td->td_imagelength;
     if (td->td_planarconfig == PLANARCONFIG_CONTIG &&
         td->td_photometric == PHOTOMETRIC_YCBCR &&
         !isUpSampled(tif)) {
         /*
          * Packed YCbCr data contain one Cb+Cr for every
          * HorizontalSampling*VerticalSampling Y values.
          * Must also roundup width and height when calculating
          * since images that are not a multiple of the
          * horizontal/vertical subsampling area include
          * YCbCr data for the extended image.
          */
                 uint16 ycbcrsubsampling[2];
                 tsize_t w, scanline, samplingarea;
                 TIFFGetField( tif, TIFFTAG_YCBCRSUBSAMPLING,
                               ycbcrsubsampling + 0,
                               ycbcrsubsampling + 1 );
         samplingarea = ycbcrsubsampling[0]*ycbcrsubsampling[1];
         if (samplingarea == 0) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Invalid YCbCr subsampling");
             return 0;
         }
         w = TIFFroundup(td->td_imagewidth, ycbcrsubsampling[0]);
         scanline = TIFFhowmany8(multiply(tif, w, td->td_bitspersample,
                          "TIFFVStripSize"));
         nrows = TIFFroundup(nrows, ycbcrsubsampling[1]);
         /* NB: don't need TIFFhowmany here 'cuz everything is rounded */
         scanline = multiply(tif, nrows, scanline, "TIFFVStripSize");
         return ((tsize_t)
             summarize(tif, scanline,
                   multiply(tif, 2, scanline / samplingarea,
                        "TIFFVStripSize"), "TIFFVStripSize"));
     } else
         return ((tsize_t) multiply(tif, nrows, TIFFScanlineSize(tif),
                        "TIFFVStripSize"));
 }
tsize_t TIFFVTileSize (TIFF * , uint32)
Definition at line 185 of file tif_tile.c.
References isUpSampled, multiply(), PHOTOMETRIC_YCBCR, PLANARCONFIG_CONTIG, summarize(), TIFFDirectory::td_bitspersample, TIFFDirectory::td_photometric, TIFFDirectory::td_planarconfig, TIFFDirectory::td_tiledepth, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, TIFFDirectory::td_ycbcrsubsampling, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFErrorExt(), TIFFhowmany8, TIFFroundup, and TIFFTileRowSize().
Referenced by ChopUpSingleUncompressedStrip(), and TIFFTileSize().
 {
     TIFFDirectory *td = &tif->tif_dir;
     tsize_t tilesize;
     if (td->td_tilelength == 0 || td->td_tilewidth == 0 ||
         td->td_tiledepth == 0)
         return ((tsize_t) 0);
     if (td->td_planarconfig == PLANARCONFIG_CONTIG &&
         td->td_photometric == PHOTOMETRIC_YCBCR &&
         !isUpSampled(tif)) {
         /*
          * Packed YCbCr data contain one Cb+Cr for every
          * HorizontalSampling*VerticalSampling Y values.
          * Must also roundup width and height when calculating
          * since images that are not a multiple of the
          * horizontal/vertical subsampling area include
          * YCbCr data for the extended image.
          */
         tsize_t w =
             TIFFroundup(td->td_tilewidth, td->td_ycbcrsubsampling[0]);
         tsize_t rowsize =
             TIFFhowmany8(multiply(tif, w, td->td_bitspersample,
                       "TIFFVTileSize"));
         tsize_t samplingarea =
             td->td_ycbcrsubsampling[0]*td->td_ycbcrsubsampling[1];
         if (samplingarea == 0) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name, "Invalid YCbCr subsampling");
             return 0;
         }
         nrows = TIFFroundup(nrows, td->td_ycbcrsubsampling[1]);
         /* NB: don't need TIFFhowmany here 'cuz everything is rounded */
         tilesize = multiply(tif, nrows, rowsize, "TIFFVTileSize");
         tilesize = summarize(tif, tilesize,
                      multiply(tif, 2, tilesize / samplingarea,
                           "TIFFVTileSize"),
                      "TIFFVTileSize");
     } else
         tilesize = multiply(tif, nrows, TIFFTileRowSize(tif),
                     "TIFFVTileSize");
     return ((tsize_t)
         multiply(tif, tilesize, td->td_tiledepth, "TIFFVTileSize"));
 }
void TIFFWarning (const char * , const char * , ...)
Definition at line 51 of file tif_warning.c.
References _TIFFwarningHandler, and _TIFFwarningHandlerExt.
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFwarningHandler)
         (*_TIFFwarningHandler)(module, fmt, ap);
     if (_TIFFwarningHandlerExt)
         (*_TIFFwarningHandlerExt)(0, module, fmt, ap);
     va_end(ap);
 }
void TIFFWarningExt (thandle_t , const char * , const char * , ...)
Definition at line 63 of file tif_warning.c.
References _TIFFwarningHandler, and _TIFFwarningHandlerExt.
Referenced by _TIFFVSetField(), buildMap(), CheckDirCount(), TIFFReadCustomDirectory(), TIFFReadDirectory(), and TIFFWriteRationalArray().
 {
     va_list ap;
     va_start(ap, fmt);
     if (_TIFFwarningHandler)
         (*_TIFFwarningHandler)(module, fmt, ap);
     if (_TIFFwarningHandlerExt)
         (*_TIFFwarningHandlerExt)(fd, module, fmt, ap);
     va_end(ap);
 }
int TIFFWriteBufferSetup (TIFF * , tdata_t , tsize_t)
Definition at line 551 of file tif_write.c.
References _TIFFfree(), _TIFFmalloc(), isTiled, NULL, tiff::tif_clientdata, tiff::tif_flags, tiff::tif_name, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_rawdatasize, tiff::tif_tilesize, TIFF_BUFFERSETUP, TIFF_MYBUFFER, TIFFErrorExt(), and TIFFStripSize().
 {
     static const char module[] = "TIFFWriteBufferSetup";
     if (tif->tif_rawdata) {
         if (tif->tif_flags & TIFF_MYBUFFER) {
             _TIFFfree(tif->tif_rawdata);
             tif->tif_flags &= ~TIFF_MYBUFFER;
         }
         tif->tif_rawdata = NULL;
     }
     if (size == (tsize_t) -1) {
         size = (isTiled(tif) ?
             tif->tif_tilesize : TIFFStripSize(tif));
         /*
          * Make raw data buffer at least 8K
          */
         if (size < 8*1024)
             size = 8*1024;
         bp = NULL;          /* NB: force malloc */
     }
     if (bp == NULL) {
         bp = _TIFFmalloc(size);
         if (bp == NULL) {
             TIFFErrorExt(tif->tif_clientdata, module, "%s: No space for output buffer",
                 tif->tif_name);
             return (0);
         }
         tif->tif_flags |= TIFF_MYBUFFER;
     } else
         tif->tif_flags &= ~TIFF_MYBUFFER;
     tif->tif_rawdata = (tidata_t) bp;
     tif->tif_rawdatasize = size;
     tif->tif_rawcc = 0;
     tif->tif_rawcp = tif->tif_rawdata;
     tif->tif_flags |= TIFF_BUFFERSETUP;
     return (1);
 }
int TIFFWriteCheck (TIFF * , int , const char *)
Definition at line 489 of file tif_write.c.
References FIELD_IMAGEDIMENSIONS, FIELD_PLANARCONFIG, isTiled, NULL, PLANARCONFIG_CONTIG, TIFFDirectory::td_nstrips, TIFFDirectory::td_planarconfig, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripoffset, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_flags, tiff::tif_mode, tiff::tif_name, tiff::tif_scanlinesize, tiff::tif_tilesize, TIFF_BEENWRITING, TIFFErrorExt(), TIFFFieldSet, TIFFScanlineSize(), TIFFSetupStrips(), and TIFFTileSize().
 {
     if (tif->tif_mode == O_RDONLY) {
         TIFFErrorExt(tif->tif_clientdata, module, "%s: File not open for writing",
             tif->tif_name);
         return (0);
     }
     if (tiles ^ isTiled(tif)) {
         TIFFErrorExt(tif->tif_clientdata, tif->tif_name, tiles ?
             "Can not write tiles to a stripped image" :
             "Can not write scanlines to a tiled image");
         return (0);
     }
     /*
      * On the first write verify all the required information
      * has been setup and initialize any data structures that
      * had to wait until directory information was set.
      * Note that a lot of our work is assumed to remain valid
      * because we disallow any of the important parameters
      * from changing after we start writing (i.e. once
      * TIFF_BEENWRITING is set, TIFFSetField will only allow
      * the image's length to be changed).
      */
     if (!TIFFFieldSet(tif, FIELD_IMAGEDIMENSIONS)) {
         TIFFErrorExt(tif->tif_clientdata, module,
             "%s: Must set \"ImageWidth\" before writing data",
             tif->tif_name);
         return (0);
     }
     if (tif->tif_dir.td_samplesperpixel == 1) {
         /*
          * Planarconfiguration is irrelevant in case of single band
          * images and need not be included. We will set it anyway,
          * because this field is used in other parts of library even
          * in the single band case.
          */
         tif->tif_dir.td_planarconfig = PLANARCONFIG_CONTIG;
     } else {
         if (!TIFFFieldSet(tif, FIELD_PLANARCONFIG)) {
             TIFFErrorExt(tif->tif_clientdata, module,
             "%s: Must set \"PlanarConfiguration\" before writing data",
                 tif->tif_name);
             return (0);
         }
     }
     if (tif->tif_dir.td_stripoffset == NULL && !TIFFSetupStrips(tif)) {
         tif->tif_dir.td_nstrips = 0;
         TIFFErrorExt(tif->tif_clientdata, module, "%s: No space for %s arrays",
             tif->tif_name, isTiled(tif) ? "tile" : "strip");
         return (0);
     }
     tif->tif_tilesize = isTiled(tif) ? TIFFTileSize(tif) : (tsize_t) -1;
     tif->tif_scanlinesize = TIFFScanlineSize(tif);
     tif->tif_flags |= TIFF_BEENWRITING;
     return (1);
 }
int TIFFWriteDirectory (TIFF *)
Definition at line 405 of file tif_dirwrite.c.
References _TIFFWriteDirectory(), and TRUE.
Referenced by TIFFFlush(), and TIFFRewriteDirectory().
 {
     return _TIFFWriteDirectory(tif, TRUE);
 }
tsize_t TIFFWriteEncodedStrip (TIFF * , tstrip_t , tdata_t , tsize_t)
Definition at line 184 of file tif_write.c.
References BUFFERCHECK, isFillOrder, PLANARCONFIG_SEPARATE, sample(), TIFFDirectory::td_fillorder, TIFFDirectory::td_imagelength, TIFFDirectory::td_nstrips, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_curoff, tiff::tif_curstrip, tiff::tif_dir, tiff::tif_encodestrip, tiff::tif_flags, tiff::tif_name, tiff::tif_postdecode, tiff::tif_postencode, tiff::tif_preencode, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_row, tiff::tif_setupencode, TIFF_CODERSETUP, TIFF_NOBITREV, TIFF_POSTENCODE, TIFFAppendToStrip(), TIFFErrorExt(), TIFFGrowStrips(), TIFFhowmany, TIFFReverseBits(), and WRITECHECKSTRIPS.
 {
     static const char module[] = "TIFFWriteEncodedStrip";
     TIFFDirectory *td = &tif->tif_dir;
     tsample_t sample;
     if (!WRITECHECKSTRIPS(tif, module))
         return ((tsize_t) -1);
     /*
      * Check strip array to make sure there's space.
      * We don't support dynamically growing files that
      * have data organized in separate bitplanes because
      * it's too painful.  In that case we require that
      * the imagelength be set properly before the first
      * write (so that the strips array will be fully
      * allocated above).
      */
     if (strip >= td->td_nstrips) {
         if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
         "Can not grow image by strips when using separate planes");
             return ((tsize_t) -1);
         }
         if (!TIFFGrowStrips(tif, 1, module))
             return ((tsize_t) -1);
         td->td_stripsperimage =
             TIFFhowmany(td->td_imagelength, td->td_rowsperstrip);
     }
     /*
      * Handle delayed allocation of data buffer.  This
      * permits it to be sized according to the directory
      * info.
      */
     if (!BUFFERCHECK(tif))
         return ((tsize_t) -1);
     tif->tif_curstrip = strip;
     tif->tif_row = (strip % td->td_stripsperimage) * td->td_rowsperstrip;
     if ((tif->tif_flags & TIFF_CODERSETUP) == 0) {
         if (!(*tif->tif_setupencode)(tif))
             return ((tsize_t) -1);
         tif->tif_flags |= TIFF_CODERSETUP;
     }
     tif->tif_rawcc = 0;
     tif->tif_rawcp = tif->tif_rawdata;
         if( td->td_stripbytecount[strip] > 0 )
         {
             /* if we are writing over existing tiles, zero length. */
             td->td_stripbytecount[strip] = 0;
             /* this forces TIFFAppendToStrip() to do a seek */
             tif->tif_curoff = 0;
         }
     tif->tif_flags &= ~TIFF_POSTENCODE;
     sample = (tsample_t)(strip / td->td_stripsperimage);
     if (!(*tif->tif_preencode)(tif, sample))
         return ((tsize_t) -1);
         /* swab if needed - note that source buffer will be altered */
         tif->tif_postdecode( tif, (tidata_t) data, cc );
     if (!(*tif->tif_encodestrip)(tif, (tidata_t) data, cc, sample))
         return ((tsize_t) 0);
     if (!(*tif->tif_postencode)(tif))
         return ((tsize_t) -1);
     if (!isFillOrder(tif, td->td_fillorder) &&
         (tif->tif_flags & TIFF_NOBITREV) == 0)
         TIFFReverseBits(tif->tif_rawdata, tif->tif_rawcc);
     if (tif->tif_rawcc > 0 &&
         !TIFFAppendToStrip(tif, strip, tif->tif_rawdata, tif->tif_rawcc))
         return ((tsize_t) -1);
     tif->tif_rawcc = 0;
     tif->tif_rawcp = tif->tif_rawdata;
     return (cc);
 }
tsize_t TIFFWriteEncodedTile (TIFF * , ttile_t , tdata_t , tsize_t)
Definition at line 340 of file tif_write.c.
References BUFFERCHECK, isFillOrder, sample(), TIFFDirectory::td_fillorder, TIFFDirectory::td_imagelength, TIFFDirectory::td_imagewidth, TIFFDirectory::td_nstrips, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripsperimage, TIFFDirectory::td_tilelength, TIFFDirectory::td_tilewidth, tiff::tif_clientdata, tiff::tif_col, tiff::tif_curoff, tiff::tif_curtile, tiff::tif_dir, tiff::tif_encodetile, tiff::tif_flags, tiff::tif_name, tiff::tif_postdecode, tiff::tif_postencode, tiff::tif_preencode, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_row, tiff::tif_setupencode, tiff::tif_tilesize, TIFF_CODERSETUP, TIFF_NOBITREV, TIFF_POSTENCODE, TIFFAppendToStrip(), TIFFErrorExt(), TIFFhowmany, TIFFReverseBits(), and WRITECHECKTILES.
Referenced by TIFFWriteTile().
 {
     static const char module[] = "TIFFWriteEncodedTile";
     TIFFDirectory *td;
     tsample_t sample;
     if (!WRITECHECKTILES(tif, module))
         return ((tsize_t) -1);
     td = &tif->tif_dir;
     if (tile >= td->td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, module, "%s: Tile %lu out of range, max %lu",
             tif->tif_name, (unsigned long) tile, (unsigned long) td->td_nstrips);
         return ((tsize_t) -1);
     }
     /*
      * Handle delayed allocation of data buffer.  This
      * permits it to be sized more intelligently (using
      * directory information).
      */
     if (!BUFFERCHECK(tif))
         return ((tsize_t) -1);
     tif->tif_curtile = tile;
     tif->tif_rawcc = 0;
     tif->tif_rawcp = tif->tif_rawdata;
         if( td->td_stripbytecount[tile] > 0 )
         {
             /* if we are writing over existing tiles, zero length. */
             td->td_stripbytecount[tile] = 0;
             /* this forces TIFFAppendToStrip() to do a seek */
             tif->tif_curoff = 0;
         }
     /*
      * Compute tiles per row & per column to compute
      * current row and column
      */
     tif->tif_row = (tile % TIFFhowmany(td->td_imagelength, td->td_tilelength))
         * td->td_tilelength;
     tif->tif_col = (tile % TIFFhowmany(td->td_imagewidth, td->td_tilewidth))
         * td->td_tilewidth;
     if ((tif->tif_flags & TIFF_CODERSETUP) == 0) {
         if (!(*tif->tif_setupencode)(tif))
             return ((tsize_t) -1);
         tif->tif_flags |= TIFF_CODERSETUP;
     }
     tif->tif_flags &= ~TIFF_POSTENCODE;
     sample = (tsample_t)(tile/td->td_stripsperimage);
     if (!(*tif->tif_preencode)(tif, sample))
         return ((tsize_t) -1);
     /*
      * Clamp write amount to the tile size.  This is mostly
      * done so that callers can pass in some large number
      * (e.g. -1) and have the tile size used instead.
      */
     if ( cc < 1 || cc > tif->tif_tilesize)
         cc = tif->tif_tilesize;
         /* swab if needed - note that source buffer will be altered */
         tif->tif_postdecode( tif, (tidata_t) data, cc );
     if (!(*tif->tif_encodetile)(tif, (tidata_t) data, cc, sample))
         return ((tsize_t) 0);
     if (!(*tif->tif_postencode)(tif))
         return ((tsize_t) -1);
     if (!isFillOrder(tif, td->td_fillorder) &&
         (tif->tif_flags & TIFF_NOBITREV) == 0)
         TIFFReverseBits((unsigned char *)tif->tif_rawdata, tif->tif_rawcc);
     if (tif->tif_rawcc > 0 && !TIFFAppendToStrip(tif, tile,
         tif->tif_rawdata, tif->tif_rawcc))
         return ((tsize_t) -1);
     tif->tif_rawcc = 0;
     tif->tif_rawcp = tif->tif_rawdata;
     return (cc);
 }
tsize_t TIFFWriteRawStrip (TIFF * , tstrip_t , tdata_t , tsize_t)
Definition at line 268 of file tif_write.c.
References PLANARCONFIG_SEPARATE, TIFFDirectory::td_imagelength, TIFFDirectory::td_nstrips, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_curstrip, tiff::tif_dir, tiff::tif_name, tiff::tif_row, TIFFAppendToStrip(), TIFFErrorExt(), TIFFGrowStrips(), TIFFhowmany, and WRITECHECKSTRIPS.
 {
     static const char module[] = "TIFFWriteRawStrip";
     TIFFDirectory *td = &tif->tif_dir;
     if (!WRITECHECKSTRIPS(tif, module))
         return ((tsize_t) -1);
     /*
      * Check strip array to make sure there's space.
      * We don't support dynamically growing files that
      * have data organized in separate bitplanes because
      * it's too painful.  In that case we require that
      * the imagelength be set properly before the first
      * write (so that the strips array will be fully
      * allocated above).
      */
     if (strip >= td->td_nstrips) {
         if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
         "Can not grow image by strips when using separate planes");
             return ((tsize_t) -1);
         }
         /*
          * Watch out for a growing image.  The value of
          * strips/image will initially be 1 (since it
          * can't be deduced until the imagelength is known).
          */
         if (strip >= td->td_stripsperimage)
             td->td_stripsperimage =
                 TIFFhowmany(td->td_imagelength,td->td_rowsperstrip);
         if (!TIFFGrowStrips(tif, 1, module))
             return ((tsize_t) -1);
     }
     tif->tif_curstrip = strip;
     tif->tif_row = (strip % td->td_stripsperimage) * td->td_rowsperstrip;
     return (TIFFAppendToStrip(tif, strip, (tidata_t) data, cc) ?
         cc : (tsize_t) -1);
 }
tsize_t TIFFWriteRawTile (TIFF * , ttile_t , tdata_t , tsize_t)
Definition at line 429 of file tif_write.c.
References TIFFDirectory::td_nstrips, tiff::tif_clientdata, tiff::tif_dir, tiff::tif_name, TIFFAppendToStrip(), TIFFErrorExt(), and WRITECHECKTILES.
 {
     static const char module[] = "TIFFWriteRawTile";
     if (!WRITECHECKTILES(tif, module))
         return ((tsize_t) -1);
     if (tile >= tif->tif_dir.td_nstrips) {
         TIFFErrorExt(tif->tif_clientdata, module, "%s: Tile %lu out of range, max %lu",
             tif->tif_name, (unsigned long) tile,
             (unsigned long) tif->tif_dir.td_nstrips);
         return ((tsize_t) -1);
     }
     return (TIFFAppendToStrip(tif, tile, (tidata_t) data, cc) ?
         cc : (tsize_t) -1);
 }
int TIFFWriteScanline (TIFF * , tdata_t , uint32 , tsample_t)
Definition at line 49 of file tif_write.c.
References BUFFERCHECK, PLANARCONFIG_SEPARATE, sample(), TIFFDirectory::td_imagelength, TIFFDirectory::td_nstrips, TIFFDirectory::td_planarconfig, TIFFDirectory::td_rowsperstrip, TIFFDirectory::td_samplesperpixel, TIFFDirectory::td_stripbytecount, TIFFDirectory::td_stripsperimage, tiff::tif_clientdata, tiff::tif_curoff, tiff::tif_curstrip, tiff::tif_dir, tiff::tif_encoderow, tiff::tif_flags, tiff::tif_name, tiff::tif_postdecode, tiff::tif_preencode, tiff::tif_rawcc, tiff::tif_rawcp, tiff::tif_rawdata, tiff::tif_row, tiff::tif_scanlinesize, tiff::tif_seek, tiff::tif_setupencode, TIFF_CODERSETUP, TIFF_POSTENCODE, TIFFErrorExt(), TIFFFlushData(), TIFFGrowStrips(), TIFFhowmany, and WRITECHECKSTRIPS.
Referenced by rcWindow::tiff().
 {
     static const char module[] = "TIFFWriteScanline";
     register TIFFDirectory *td;
     int status, imagegrew = 0;
     tstrip_t strip;
     if (!WRITECHECKSTRIPS(tif, module))
         return (-1);
     /*
      * Handle delayed allocation of data buffer.  This
      * permits it to be sized more intelligently (using
      * directory information).
      */
     if (!BUFFERCHECK(tif))
         return (-1);
     td = &tif->tif_dir;
     /*
      * Extend image length if needed
      * (but only for PlanarConfig=1).
      */
     if (row >= td->td_imagelength) {    /* extend image */
         if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
         "Can not change \"ImageLength\" when using separate planes");
             return (-1);
         }
         td->td_imagelength = row+1;
         imagegrew = 1;
     }
     /*
      * Calculate strip and check for crossings.
      */
     if (td->td_planarconfig == PLANARCONFIG_SEPARATE) {
         if (sample >= td->td_samplesperpixel) {
             TIFFErrorExt(tif->tif_clientdata, tif->tif_name,
                 "%d: Sample out of range, max %d",
                 sample, td->td_samplesperpixel);
             return (-1);
         }
         strip = sample*td->td_stripsperimage + row/td->td_rowsperstrip;
     } else
         strip = row / td->td_rowsperstrip;
     if (strip != tif->tif_curstrip) {
         /*
          * Changing strips -- flush any data present.
          */
         if (!TIFFFlushData(tif))
             return (-1);
         tif->tif_curstrip = strip;
         /*
          * Watch out for a growing image.  The value of
          * strips/image will initially be 1 (since it
          * can't be deduced until the imagelength is known).
          */
         if (strip >= td->td_stripsperimage && imagegrew)
             td->td_stripsperimage =
                 TIFFhowmany(td->td_imagelength,td->td_rowsperstrip);
         tif->tif_row =
             (strip % td->td_stripsperimage) * td->td_rowsperstrip;
         if ((tif->tif_flags & TIFF_CODERSETUP) == 0) {
             if (!(*tif->tif_setupencode)(tif))
                 return (-1);
             tif->tif_flags |= TIFF_CODERSETUP;
         }
         tif->tif_rawcc = 0;
         tif->tif_rawcp = tif->tif_rawdata;
         if( td->td_stripbytecount[strip] > 0 )
         {
             /* if we are writing over existing tiles, zero length */
             td->td_stripbytecount[strip] = 0;
             /* this forces TIFFAppendToStrip() to do a seek */
             tif->tif_curoff = 0;
         }
         if (!(*tif->tif_preencode)(tif, sample))
             return (-1);
         tif->tif_flags |= TIFF_POSTENCODE;
     }
     /*
      * Check strip array to make sure there's space.
      * We don't support dynamically growing files that
      * have data organized in separate bitplanes because
      * it's too painful.  In that case we require that
      * the imagelength be set properly before the first
      * write (so that the strips array will be fully
      * allocated above).
      */
     if (strip >= td->td_nstrips && !TIFFGrowStrips(tif, 1, module))
         return (-1);
     /*
      * Ensure the write is either sequential or at the
      * beginning of a strip (or that we can randomly
      * access the data -- i.e. no encoding).
      */
     if (row != tif->tif_row) {
         if (row < tif->tif_row) {
             /*
              * Moving backwards within the same strip:
              * backup to the start and then decode
              * forward (below).
              */
             tif->tif_row = (strip % td->td_stripsperimage) *
                 td->td_rowsperstrip;
             tif->tif_rawcp = tif->tif_rawdata;
         }
         /*
          * Seek forward to the desired row.
          */
         if (!(*tif->tif_seek)(tif, row - tif->tif_row))
             return (-1);
         tif->tif_row = row;
     }
         /* swab if needed - note that source buffer will be altered */
         tif->tif_postdecode( tif, (tidata_t) buf, tif->tif_scanlinesize );
     status = (*tif->tif_encoderow)(tif, (tidata_t) buf,
         tif->tif_scanlinesize, sample);
         /* we are now poised at the beginning of the next row */
     tif->tif_row = row + 1;
     return (status);
 }
tsize_t TIFFWriteTile (TIFF * , tdata_t , uint32 , uint32 , uint32 , tsample_t)
Definition at line 312 of file tif_write.c.
References TIFFCheckTile(), TIFFComputeTile(), and TIFFWriteEncodedTile().
 {
     if (!TIFFCheckTile(tif, x, y, z, s))
         return (-1);
     /*
      * NB: A tile size of -1 is used instead of tif_tilesize knowing
      *     that TIFFWriteEncodedTile will clamp this to the tile size.
      *     This is done because the tile size may not be defined until
      *     after the output buffer is setup in TIFFWriteBufferSetup.
      */
     return (TIFFWriteEncodedTile(tif,
         TIFFComputeTile(tif, x, y, z, s), buf, (tsize_t) -1));
 }
void TIFFXYZToRGB (TIFFCIELabToRGB * , float , float , float , uint32 * , uint32 * , uint32 *)
Definition at line 78 of file tif_color.c.
References TIFFCIELabToRGB::bstep, TIFFDisplay::d_mat, TIFFDisplay::d_Vrwb, TIFFDisplay::d_Vrwg, TIFFDisplay::d_Vrwr, TIFFDisplay::d_Y0B, TIFFDisplay::d_Y0G, TIFFDisplay::d_Y0R, TIFFDisplay::d_YCB, TIFFDisplay::d_YCG, TIFFDisplay::d_YCR, TIFFCIELabToRGB::display, TIFFCIELabToRGB::gstep, TIFFCIELabToRGB::range, RINT, TIFFCIELabToRGB::rstep, TIFFmax, TIFFmin, TIFFCIELabToRGB::Yb2b, TIFFCIELabToRGB::Yg2g, and TIFFCIELabToRGB::Yr2r.
Referenced by putcontig8bitCIELab().
 {
     int i;
     float Yr, Yg, Yb;
     float *matrix = &cielab->display.d_mat[0][0];
     /* Multiply through the matrix to get luminosity values. */
     Yr =  matrix[0] * X + matrix[1] * Y + matrix[2] * Z;
     Yg =  matrix[3] * X + matrix[4] * Y + matrix[5] * Z;
     Yb =  matrix[6] * X + matrix[7] * Y + matrix[8] * Z;
     /* Clip input */
     Yr = TIFFmax(Yr, cielab->display.d_Y0R);
     Yg = TIFFmax(Yg, cielab->display.d_Y0G);
     Yb = TIFFmax(Yb, cielab->display.d_Y0B);
     // Bug http://bugzilla.remotesensing.org/show_bug.cgi?id=1065
     Yr = TIFFmin(Yr, cielab->display.d_YCR); // don't overflow Yr2r[]
     Yg = TIFFmin(Yg, cielab->display.d_YCG); // don't overflow Yg2g[]
     Yb = TIFFmin(Yb, cielab->display.d_YCB); // don't overflow Yb2b[]
     /* Turn luminosity to colour value. */
     i = (int)((Yr - cielab->display.d_Y0R) / cielab->rstep);
     i = TIFFmin(cielab->range, i);
     *r = RINT(cielab->Yr2r[i]);
     i = (int)((Yg - cielab->display.d_Y0G) / cielab->gstep);
     i = TIFFmin(cielab->range, i);
     *g = RINT(cielab->Yg2g[i]);
     i = (int)((Yb - cielab->display.d_Y0B) / cielab->bstep);
     i = TIFFmin(cielab->range, i);
     *b = RINT(cielab->Yb2b[i]);
     /* Clip output. */
     *r = TIFFmin(*r, cielab->display.d_Vrwr);
     *g = TIFFmin(*g, cielab->display.d_Vrwg);
     *b = TIFFmin(*b, cielab->display.d_Vrwb);
 }
void TIFFYCbCrtoRGB (TIFFYCbCrToRGB * , uint32 , int32 , int32 , uint32 * , uint32 * , uint32 *)
Definition at line 183 of file tif_color.c.
References TIFFYCbCrToRGB::Cb_b_tab, TIFFYCbCrToRGB::Cb_g_tab, CLAMP, TIFFYCbCrToRGB::clamptab, TIFFYCbCrToRGB::Cr_g_tab, TIFFYCbCrToRGB::Cr_r_tab, HICLAMP, SHIFT, and TIFFYCbCrToRGB::Y_tab.
 {
     /* XXX: Only 8-bit YCbCr input supported for now */
     Y = HICLAMP(Y, 255), Cb = CLAMP(Cb, 0, 255), Cr = CLAMP(Cr, 0, 255);
     *r = ycbcr->clamptab[ycbcr->Y_tab[Y] + ycbcr->Cr_r_tab[Cr]];
     *g = ycbcr->clamptab[ycbcr->Y_tab[Y]
         + (int)((ycbcr->Cb_g_tab[Cb] + ycbcr->Cr_g_tab[Cr]) >> SHIFT)];
     *b = ycbcr->clamptab[ycbcr->Y_tab[Y] + ycbcr->Cb_b_tab[Cb]];
 }
int TIFFYCbCrToRGBInit (TIFFYCbCrToRGB * , float * , float *)
Definition at line 212 of file tif_color.c.
References _TIFFmemset(), TIFFYCbCrToRGB::Cb_b_tab, TIFFYCbCrToRGB::Cb_g_tab, TIFFYCbCrToRGB::clamptab, Code2V, TIFFYCbCrToRGB::Cr_g_tab, TIFFYCbCrToRGB::Cr_r_tab, FIX, LumaBlue, LumaGreen, LumaRed, ONE_HALF, SHIFT, TIFFroundup, and TIFFYCbCrToRGB::Y_tab.
Referenced by initYCbCrConversion().
 {
     TIFFRGBValue* clamptab;
     int i;
 #define LumaRed     luma[0]
 #define LumaGreen   luma[1]
 #define LumaBlue    luma[2]
     clamptab = (TIFFRGBValue*)(
     (tidata_t) ycbcr+TIFFroundup(sizeof (TIFFYCbCrToRGB), sizeof (long)));
     _TIFFmemset(clamptab, 0, 256);      /* v < 0 => 0 */
     ycbcr->clamptab = (clamptab += 256);
     for (i = 0; i < 256; i++)
     clamptab[i] = (TIFFRGBValue) i;
     _TIFFmemset(clamptab+256, 255, 2*256);  /* v > 255 => 255 */
     ycbcr->Cr_r_tab = (int*) (clamptab + 3*256);
     ycbcr->Cb_b_tab = ycbcr->Cr_r_tab + 256;
     ycbcr->Cr_g_tab = (int32*) (ycbcr->Cb_b_tab + 256);
     ycbcr->Cb_g_tab = ycbcr->Cr_g_tab + 256;
     ycbcr->Y_tab = ycbcr->Cb_g_tab + 256;
     { float f1 = 2-2*LumaRed;       int32 D1 = FIX(f1);
       float f2 = LumaRed*f1/LumaGreen;  int32 D2 = -FIX(f2);
       float f3 = 2-2*LumaBlue;      int32 D3 = FIX(f3);
       float f4 = LumaBlue*f3/LumaGreen; int32 D4 = -FIX(f4);
       int x;
 #undef LumaBlue
 #undef LumaGreen
 #undef LumaRed
       /*
        * i is the actual input pixel value in the range 0..255
        * Cb and Cr values are in the range -128..127 (actually
        * they are in a range defined by the ReferenceBlackWhite
        * tag) so there is some range shifting to do here when
        * constructing tables indexed by the raw pixel data.
        */
       for (i = 0, x = -128; i < 256; i++, x++) {
         int32 Cr = (int32)Code2V(x, refBlackWhite[4] - 128.0F,
                 refBlackWhite[5] - 128.0F, 127);
         int32 Cb = (int32)Code2V(x, refBlackWhite[2] - 128.0F,
                 refBlackWhite[3] - 128.0F, 127);
         ycbcr->Cr_r_tab[i] = (int32)((D1*Cr + ONE_HALF)>>SHIFT);
         ycbcr->Cb_b_tab[i] = (int32)((D3*Cb + ONE_HALF)>>SHIFT);
         ycbcr->Cr_g_tab[i] = D2*Cr;
         ycbcr->Cb_g_tab[i] = D4*Cb + ONE_HALF;
         ycbcr->Y_tab[i] =
             (int32)Code2V(x + 128, refBlackWhite[0], refBlackWhite[1], 255);
       }
     }
     return 0;
 }
int uv_decode (double * , double * , int)
int uv_encode (double , double , int)
void XYZtoRGB24 (float * , uint8 *)