Visible: include/analysis/vbigdsp.h File Reference
vbigdsp.h File Reference
#include <rc_types.h>
Macros
#define IFLAG_FFT_FORWARD (-1)
#define IFLAG_FFT_INVERSE (1)
#define PINGPONG_FFT_MAXLEN (1<<15)
#define ALTIVEC_COMPLEX_MIN_LENGTH 16
#define ALTIVEC_REAL_MIN_LENGTH 32
#define ALTIVEC_COLUMNWISE_FFT_BREAKOVER (1<<15)
Functions
void ShutdownFFT ()
int32 FFTComplex (float *data, int32 length, int32 isign)
int32 FFTRealForward (float *data, int32 len)
int32 FFTRealInverse (float *data, int32 len)
int32 ConvolveComplexAltivec (float *x, float *y, int32 n)
int32 ConvolveRealAltivec (float *x, float *y, int32 n)
int32 FFT2DComplex (float *data, int32 width, int32 height, int32 iflag)
int32 FFT2DRealForward (float *data, int32 width, int32 height)
int32 FFT2DRealInverse (float *data, int32 width, int32 height)
int32 ConvolveComplexAltivec2D (float *x, float *y, int32 width, int32 height)
int32 ConvolveRealAltivec2D (float *x, float *y, int32 width, int32 height)
Macro Definition Documentation
#define ALTIVEC_COLUMNWISE_FFT_BREAKOVER (1<<15)
Definition at line 107 of file vbigdsp.h.
#define ALTIVEC_COMPLEX_MIN_LENGTH 16
Definition at line 93 of file vbigdsp.h.
#define ALTIVEC_REAL_MIN_LENGTH 32
Definition at line 101 of file vbigdsp.h.
#define IFLAG_FFT_FORWARD (-1)
Definition at line 78 of file vbigdsp.h.
#define IFLAG_FFT_INVERSE (1)
Definition at line 79 of file vbigdsp.h.
#define PINGPONG_FFT_MAXLEN (1<<15)
Definition at line 85 of file vbigdsp.h.
Referenced by FFTComplex().
Function Documentation
int32 ConvolveComplexAltivec (float * x, float * y, int32 n)
int32 ConvolveComplexAltivec2D (float * x, float * y, int32 width, int32 height)
int32 ConvolveRealAltivec (float * x, float * y, int32 n)
int32 ConvolveRealAltivec2D (float * x, float * y, int32 width, int32 height)
int32 FFT2DComplex (float * data, int32 width, int32 height, int32 iflag)
int32 FFT2DRealForward (float * data, int32 width, int32 height)
int32 FFT2DRealInverse (float * data, int32 width, int32 height)
int32 FFTComplex (float * data, int32 length, int32 isign)
Definition at line 1008 of file vbigdsp.cpp.
References fft_pingpong(), PINGPONG_FFT_MAXLEN, and rmAssert.
Referenced by fft_real_forward_scalar(), and fft_real_inverse_scalar().
 {
   int32 result = 0;
   if (length <= PINGPONG_FFT_MAXLEN) {
     // length is in the range where pingpong FFT is fastest
     result = fft_pingpong(data, length, isign);
   }
  else {
     rmAssert (0);
   }
   return result;
 }
int32 FFTRealForward (float * data, int32 len)
Definition at line 714 of file vbigdsp.cpp.
References fft_real_forward_scalar().
Referenced by rcOptoKineticImage::genDFT(), and rf1DFourierAnalysisVoxels().
 {
    return fft_real_forward_scalar(data, len);
 }
int32 FFTRealInverse (float * data, int32 len)
Definition at line 726 of file vbigdsp.cpp.
References fft_real_inverse_scalar().
 {
    return fft_real_inverse_scalar(data, len);
 }
void ShutdownFFT ()
Definition at line 293 of file vbigdsp.cpp.
References gSinCosTablePtr, gSinCosTableSize, gTempBufferPtr, and gTempBufferSize.
 {
   if (gSinCosTablePtr != 0) {
     free(gSinCosTablePtr);
     gSinCosTablePtr = 0;
   }
   gSinCosTableSize = 0;
   if (gTempBufferPtr != 0) {
     free(gTempBufferPtr);
     gTempBufferPtr = 0;
   }
   gTempBufferSize = 0;
 }