Visible: src/analysis/code/vbigdsp.cpp File Reference
vbigdsp.cpp File Reference
#include <errno.h>
#include <math.h>
#include "vbigdsp.h"
#include <Accelerate/Accelerate.h>
Macros
#define PI (3.1415926535897932384626433832795)
#define Altivec_Const4(type, e0, e1, e2, e3) ((type)(e0,e1,e2,e3))
#define Altivec_Const8(type, e0, e1, e2, e3, e4, e5, e6, e7) ((type)(e0,e1,e2,e3,e4,e5,e6,e7))
#define Altivec_Const16(type, e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, ea, eb, ec, ed, ee, ef) ((type)(e0,e1,e2,e3,e4,e5,e6,e7,e8,e9,ea,eb,ec,ed,ee,ef))
Functions
static int32 log2max (int32 n)
static int EnsureStaticBufferSize (int32 complexCount)
static int InitFFTSinCos (int32 len)
void ShutdownFFT ()
static int32 fft_real_forward_scalar (float *data, int32 len)
static int32 fft_real_inverse_scalar (float *data, int32 len)
int32 FFTRealForward (float *data, int32 len)
int32 FFTRealInverse (float *data, int32 len)
static int32 fft_scalar (float *pData, float *tempbuff, int32 len, int32 isign)
static int32 fft_pingpong (float *data, int32 len, int32 isign)
int32 FFTComplex (float *data, int32 length, int32 isign)
Variables
static float * gTempBufferPtr = 0
static int32 gTempBufferSize = 0
static float * gSinCosTablePtr = 0
static int32 gSinCosTableSize = 0
Macro Definition Documentation
#define Altivec_Const16 (type, e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, ea, eb, ec, ed, ee, ef) ((type)(e0,e1,e2,e3,e4,e5,e6,e7,e8,e9,ea,eb,ec,ed,ee,ef))
Definition at line 98 of file vbigdsp.cpp.
#define Altivec_Const4 (type, e0, e1, e2, e3) ((type)(e0,e1,e2,e3))
Definition at line 94 of file vbigdsp.cpp.
#define Altivec_Const8 (type, e0, e1, e2, e3, e4, e5, e6, e7) ((type)(e0,e1,e2,e3,e4,e5,e6,e7))
Definition at line 96 of file vbigdsp.cpp.
#define PI (3.1415926535897932384626433832795)
Definition at line 79 of file vbigdsp.cpp.
Referenced by fft_real_forward_scalar(), fft_real_inverse_scalar(), and InitFFTSinCos().
Function Documentation
static int EnsureStaticBufferSize (int32 complexCount) static
Definition at line 165 of file vbigdsp.cpp.
References gTempBufferPtr, and gTempBufferSize.
Referenced by fft_pingpong().
 {
   int32 result = 0;
   if (gTempBufferSize < complexCount) {
     gTempBufferSize = complexCount;
     if (gTempBufferPtr) {
       free(gTempBufferPtr);
       gTempBufferPtr = 0;
     }
     gTempBufferPtr = (float*) valloc(2*complexCount*sizeof(float));
     if (!gTempBufferPtr) result = ENOMEM;
     if (result != 0) {
       gTempBufferPtr = 0;
       gTempBufferSize = 0;
     }
   }
   return result;
 }
static int32 fft_pingpong (float * data, int32 len, int32 isign) static
Definition at line 972 of file vbigdsp.cpp.
References EnsureStaticBufferSize(), fft_scalar(), and gTempBufferPtr.
Referenced by FFTComplex().
 {
   int32 result = 0;
   // make sure that our temp buffer is sufficiently large to hold a copy of
   // the data.
   result = EnsureStaticBufferSize(len);
   if (result == 0) {
       // call scalar version
       result = fft_scalar(data, (float*)gTempBufferPtr, len, isign);
     }
   return result;
 }
static int32 fft_real_forward_scalar (float * data, int32 len) static
Definition at line 316 of file vbigdsp.cpp.
References FFTComplex(), PI, and sin().
Referenced by FFTRealForward().
 {
   int32 result = 0;
   double  updateA, updateB;
   double  currentCos, currentSin, tempCos1;
   float   realLo, realHi, imLo, imHi;
   float   realResultLo, realResultHi, imResultLo, imResultHi;
   float   realDiff, imDiff, realSum, imSum;
   float   *pInLo, *pInHi;
   int32 i;
   // for length of 0 or 1 we do nothing
   if (len < 2) return 0;
   // perform a forward complex fft on our
   // real signal data, treating it as a
   // half-length complex signal.
   result = FFTComplex(data, len/2, -1);
   if (result == 0) {
     //
     //  Given c = cos(w) and s = sin(w), if we
     //  want to find the cos and sin of w plus
     //  some small angle d, then we can do so
     //  by defining:
     //
     //  a = 2 * ((sin(d/2)) ^ 2)
     //  b = sin(d)
     //
     //  Then, we can calculate the cos and sin
     //  of the updated angle w+d as:
     //
     //  cos(w+d) = c - ac - bs
     //  sin(w+d) = s - as + bc
     //
     //  We will need to incrementally calculate
     //  cos(w) and sin(w), so we define the
     //  following scalar values.  We use scalar
     //  because we need the precision of doubles,
     //  and vectors are floats.
     //
     updateA = sin(PI/len);
     updateB = sin(2*PI/len);
     updateA *= updateA*2;
     // start with sin(0) and cos(0)
     currentCos = 1;
     currentSin = 0;
     // first, calculate re[0], and re[n/2]. we don't bother to do the
     // sin, cos multiplies, because we know that they are zero and one.
     realResultLo = data[0]+data[1];
     realResultHi = data[0]-data[1];
     // store re[0].  We don't calculate im[0] because we know that it is 0.
     data[0] = realResultLo;
     // store re[n/2].  We don't calculate im[n/2] because we know it
     // is 0.  We store re[n/2] in the position of im[0] because we
     // don't want to take up any more space than the source data, and
     // if we were to store it in the n/2 position, it would be past
     // the array of source data, which ranges from 0 to (n/2)-1.
     data[1] = realResultHi;
     // Start our source pointers to point at re[1] and re[(n/2)-1].
     pInLo = &data[2];
     pInHi = &data[len-2];
     // for each loop iteration, we calculate two complex results (four
     // floats), so we iterate through the loop len/4 times
     for (i = 0; i < len/4; i++) {
       // calculate the new sin and cos values
       tempCos1   = currentCos - (updateA*currentCos  + updateB * currentSin);
       currentSin = currentSin - (updateA*currentSin  - updateB * currentCos);
       currentCos = tempCos1;
       // load re[i+1], im[i+1]
       realLo      = *pInLo;
       imLo        = *(pInLo+1);
       // load re[(n/2)-1-i], im[(n/2)-1-i]
       realHi      = *pInHi;
       imHi        = *(pInHi+1);
       // calculate:
       // realDiff   = re[i+1]-re[(n/2)-1-i]
       // realSum    = re[i+1]+re[(n/2)-1-i]
       realDiff    = realLo-realHi;
       realSum     = realLo+realHi;
       // calculate:
       // imDiff = im[i+1]-im[(n/2)-1-i]
       // imSum  = im[i+1]+im[(n/2)-1-i]
       imDiff      = imLo-imHi;
       imSum       = imLo+imHi;
       // calculate:
       //
       // realResultLo =
       //    re[i+1]+re[(n/2)-1-i] +
       //    (im[i+1]+im[(n/2)-1-i]) * cos( (i+1) * 2pi / n ) -
       //    (re[i+1]-re[(n/2)-1-i]) * sin( (i+1) * 2pi / n )
       //
       // imResultLo =
       //    im[i+1]-im[(n/2)-1-i] -
       //    (re[i+1]-re[(n/2)-1-i]) * cos( (i+1) * 2pi / n ) -
       //    (im[i+1]+im[(n/2)-1-i]) * sin( (i+1) * 2pi / n )
       //
       realResultLo = realSum + (imSum*currentCos) - (realDiff*currentSin);
       imResultLo   = imDiff - (realDiff * currentCos) - (imSum*currentSin);
       // calculate:
       //
       // realResultHi =
       //    re[(n/2)-1-i]+re[i+1] +
       //    (im[(n/2)-1-i]+im[i+1]) * cos( ((n/2)-i-1) * 2pi / n ) -
       //    (re[(n/2)-1-i]-re[i+1]) * sin( ((n/2)-i-1) * 2pi / n )
       //
       // imResultHi =
       //    im[(n/2)-1-i]-im[i+1] -
       //    (re[(n/2)-1-i]-re[i+1]) * cos( ((n/2)-i-1) * 2pi / n ) -
       //    (im[(n/2)-1-i]+im[i+1]) * sin( ((n/2)-i-1) * 2pi / n )
       //
       // taking advantage of the following:
       //
       // sin(  (i+1) * 2pi / n ) =  sin ( ((n/2)-i-1) * 2pi / n )
       // cos(  (i+1) * 2pi / n ) = -cos ( ((n/2)-i-1) * 2pi / n )
       // re[(n/2)-1-i]-re[i+1]   = -(re[i+1]-re[(n/2)-1-i])
       // re[(n/2)-1-i]-re[i+1]   = -(re[i+1]-re[(n/2)-1-i])
       realResultHi = realSum - (imSum*currentCos) + (realDiff*currentSin);
       imResultHi = -imDiff - (realDiff * currentCos) - (imSum*currentSin);
       // store results, advance low pointer forward to next complex element,
       // and high pointer backward to previous complex element
       *pInLo++ = realResultLo/2;
       *pInLo++ = imResultLo/2;
       *(pInHi+1) = imResultHi/2;
       *pInHi = realResultHi/2;
       pInHi -= 2;
     }
   }
   return result;
 }
static int32 fft_real_inverse_scalar (float * data, int32 len) static
Definition at line 512 of file vbigdsp.cpp.
References FFTComplex(), PI, and sin().
Referenced by FFTRealInverse().
 {
   int32 result = 0;
   double  updateA, updateB;
   double  currentCos, currentSin, tempCos1;
   float   realLo, realHi, imLo, imHi;
   float   realResultLo, realResultHi, imResultLo, imResultHi;
   float   realDiff, imDiff, realSum, imSum;
   float   *pInLo, *pInHi;
   int32 i;
   // for length of 0 or 1 we do nothing
   if (len < 2) return 0;
   // Given c = cos(w) and s = sin(w), if we want to find the cos and
   // sin of w plus some small angle d, then we can do so by defining:
   //
   // a = 2 * ((sin(d/2)) ^ 2)
   // b = sin(d)
   //
   // Then, we can calculate the cos and sin of the updated angle w+d
   // as:
   //
   // cos(w+d) = c - ac - bs
   // sin(w+d) = s - as + bc
   //
   // We will need to incrementally calculate cos(w) and sin(w), so we
   // define the following scalar values.  We use scalar because we
   // need the precision of doubles, and vectors are floats.
   updateA = sin(PI/len);
   updateB = sin(2*PI/len);
   updateA *= updateA*2;
   // start with sin(0) and cos(0)
   currentCos = 1;
   currentSin = 0;
   // load re[0] and im[0].  Only re[0] is stored -- im[0] is
   // understood to be 0.
   realLo   = data[0];
   imLo     = 0;
   // load re[n/2] and im[n/2].
   // Only re[n/2] is stored -- im[n/2] is understood to be 0.
   realHi    = data[1];
   imHi      = 0;
   // calculat sum and difference of real & imaginary values
   realDiff  = realLo-realHi;
   realSum   = realLo+realHi;
   imDiff    = imLo-imHi;
   imSum     = imLo+imHi;
   // calculate re[0], and im[0]. we don't bother to do the sin, cos
   // multiplies, because we know that they are zero and one.
   realResultLo = realSum - imSum;
   imResultLo = imDiff + realDiff;
   data[0] = realResultLo/2;
   data[1] = imResultLo/2;
   // Start our source pointers to point at re[1] and re[(n/2)-1].
   pInLo = &data[2];
   pInHi = &data[len-2];
   // for each loop iteration, we calculate two complex results (four
   // floats), so we iterate through the loop len/4 times
   for (i = 0; i < len/4; i++) {
     // calculate the new sin and cos values
     tempCos1    = currentCos - (updateA*currentCos  + updateB * currentSin);
     currentSin  = currentSin - (updateA*currentSin  - updateB * currentCos);
     currentCos  = tempCos1;
     // load re[i+1], im[i+1]
     realLo  = *pInLo;
     imLo    = *(pInLo+1);
     // load re[(n/2)-1-i], im[(n/2)-1-i]
     realHi  = *pInHi;
     imHi    = *(pInHi+1);
     // calculate:
     // realDiff = re[i+1]-re[(n/2)-1-i]
     // realSum  = re[i+1]+re[(n/2)-1-i]
     realDiff    = realLo-realHi;
     realSum     = realLo+realHi;
     // calculate:
     // imDiff   = im[i+1]-im[(n/2)-1-i]
     // imSum    = im[i+1]+im[(n/2)-1-i]
     imDiff  = imLo-imHi;
     imSum   = imLo+imHi;
     // calculate:
     //
     // realResultLo =
     //      re[i+1]+re[(n/2)-1-i] -
     //      (im[i+1]+im[(n/2)-1-i]) * cos( (i+1) * 2pi / n ) -
     //      (re[i+1]-re[(n/2)-1-i]) * sin( (i+1) * 2pi / n )
     //
     // imResultLo =
     //      im[i+1]-im[(n/2)-1-i] +
     //      (re[i+1]-re[(n/2)-1-i]) * cos( (i+1) * 2pi / n ) -
     //      (im[i+1]+im[(n/2)-1-i]) * sin( (i+1) * 2pi / n )
     //
     realResultLo = realSum - (imSum*currentCos) - (realDiff*currentSin);
     imResultLo = imDiff + (realDiff * currentCos) - (imSum*currentSin);
     // calculate:
     //
     // realResultHi =
     //      re[(n/2)-1-i]+re[i+1] -
     //      (im[(n/2)-1-i]+im[i+1]) * cos( ((n/2)-i-1) * 2pi / n ) -
     //      (re[(n/2)-1-i]-re[i+1]) * sin( ((n/2)-i-1) * 2pi / n )
     //
     // imResultHi =
     //      im[(n/2)-1-i]-im[i+1] +
     //      (re[(n/2)-1-i]-re[i+1]) * cos( ((n/2)-i-1) * 2pi / n ) -
     //      (im[(n/2)-1-i]+im[i+1]) * sin( ((n/2)-i-1) * 2pi / n )
     //
     // taking advantage of the following:
     //
     // sin(  (i+1) * 2pi / n )  =  sin ( ((n/2)-i-1) * 2pi / n )
     // cos(  (i+1) * 2pi / n )  = -cos ( ((n/2)-i-1) * 2pi / n )
     // re[(n/2)-1-i]-re[i+1]    = -(re[i+1]-re[(n/2)-1-i])
     // re[(n/2)-1-i]-re[i+1]    = -(re[i+1]-re[(n/2)-1-i])
     realResultHi = realSum + (imSum*currentCos) + (realDiff*currentSin);
     imResultHi = -imDiff + (realDiff * currentCos) - (imSum*currentSin);
     // store results, advance low pointer forward to next complex
     // element, and high pointer backward to previous complex element
     *pInLo++ = realResultLo/2;
     *pInLo++ = imResultLo/2;
     *(pInHi+1) = imResultHi/2;
     *pInHi = realResultHi/2;
     pInHi -= 2;
   }
   // perform an inverse complex fft on the data.  The resulting data
   // is the real-only inverse fft.
   result = FFTComplex(data, len/2, 1);
   return result;
 }
static int32 fft_scalar (float * pData, float * tempbuff, int32 len, int32 isign) static
Definition at line 747 of file vbigdsp.cpp.
References gSinCosTablePtr, gSinCosTableSize, InitFFTSinCos(), log2max(), and pow().
Referenced by fft_pingpong().
 {
   int32  j, i;
   float    c, s, tre, tim, *srcDataPtr, *dstDataPtr, *tmp;
   double   inverseDivideMultiplier;
   int32  pow, root, trig;
   int32  result = 0;
   float    *sinCosTable;
   // calculate log2(len)
   pow = log2max(len);
   // length must be an exact power of 2
   if ((1 << pow) != len) return EINVAL;
   // make sure that the sin cos lookup table is for the current fft length
   if (len != gSinCosTableSize) result = InitFFTSinCos(len);
   if (result == 0) {
     // initialize "trig" step for destination index
     trig = 1;
     // Start with data as source, and temp buffer as destination
     srcDataPtr = pData;
     dstDataPtr = tempbuff;
     // get pointer to start of sin/cos table pointer for array reference
     sinCosTable = (float*)gSinCosTablePtr;
     for(i = pow-1; i > 0; i--) {
       root = 0;
       while(root < len/2) {
     // load cos and sin values for current root value.
     c = sinCosTable[2*root];
     s = isign*sinCosTable[2*root+1];
     for(j = trig; j > 0; j--) {
       // calculate butterflies.  For inputs:
       // [re0, im0] [re1, im1]
       //
       // we calculate:
       //
       // out0 = [re0+re1, im0+im1]
       //
       // out1 = [ cos * (re0-re1) - sin * (im0-im1),
       //            sin * (re0-re1) + cos * (im0-im1) ]
       //
       tre = srcDataPtr[0] - srcDataPtr[len];
       tim = srcDataPtr[1] - srcDataPtr[len + 1];
       dstDataPtr[0] = srcDataPtr[0] + srcDataPtr[len];
       dstDataPtr[1] = srcDataPtr[1] + srcDataPtr[len+1];
       dstDataPtr[2*trig] = c*tre - s*tim;
       dstDataPtr[2*trig + 1] = s*tre + c*tim;
       srcDataPtr += 2; dstDataPtr += 2;
     }
     // update dest pointer and root value
     dstDataPtr += 2*trig;
     root += trig;
       }
       // update trig value and ping pong source and dest pointers
       trig *= 2; srcDataPtr -= len; dstDataPtr -= 2*len;
       tmp = srcDataPtr; srcDataPtr = dstDataPtr; dstDataPtr = tmp;
     }
     // For last iteration, we are fortunate in that the source indices
     // for the butterfly calculations are the same as the destination
     // indices. This is not true for other loop iterations, which is
     // why we cannot simply store our results directly back to the
     // data -- we would overwrite source data that had not yet been
     // used for the current iteration of the loop. If the power of two
     // of the length is odd, then, on the second to last iteration,
     // the data will end up ping-ponged back to the source buffer.  If
     // this is the case, then we set source and dest to be the
     // same. Otherwise, if the power of two is even, then we will be
     // reading from temp data, and writing back to our original
     // buffer.
     if (pow & 1) {
       dstDataPtr = srcDataPtr;
     }
     root = 0;
     if (isign > 0) {
       // we are performing an inverse FFT.  We need to divide all
       // elements of the final result by len.  Since the float
       // multiply operation is faster than the divide operation, we
       // multiply by the reciprocal.
       inverseDivideMultiplier = (double)1/len;
       while(root < len/2) {
     // load cos and sin values for current root value.
     c = sinCosTable[2*root];
     s = isign*sinCosTable[2*root+1];
     for(j = trig; j > 0; j--) {
       // calculate butterflies.  For inputs:
       // [re0, im0] [re1, im1]
       //
       // we calculate:
       //
       // out0 = [re0+re1, im0+im1]
       //
       // out1 = [ cos * (re0-re1) - sin * (im0-im1),
       //            sin * (re0-re1) + cos * (im0-im1) ]
       //
       //
       // We also divide each element by the length of the signal
       // (this is done by multiplying by the reciprocal).
       tre = srcDataPtr[0] - srcDataPtr[len];
       tim = srcDataPtr[1] - srcDataPtr[len + 1];
       dstDataPtr[0] = (srcDataPtr[0] + srcDataPtr[len])*inverseDivideMultiplier;
       dstDataPtr[1]=(srcDataPtr[1] + srcDataPtr[len+1])*inverseDivideMultiplier;
       dstDataPtr[2*trig] = (c*tre - s*tim)*inverseDivideMultiplier;
       dstDataPtr[2*trig + 1] = (s*tre + c*tim)*inverseDivideMultiplier;
       srcDataPtr += 2; dstDataPtr += 2;
     }
     // update dest pointer and root value
     dstDataPtr += 2*trig;
     root += trig;
       }
     } else {
       while(root < len/2) {
     // load cos and sin values for current root value.
     c = sinCosTable[2*root];
     s = isign*sinCosTable[2*root+1];
     for(j = trig; j > 0; j--) {
       // calculate butterflies.  For inputs:
       // [re0, im0] [re1, im1]
       //
       // we calculate:
       //
       // out0 = [re0+re1, im0+im1]
       //
       // out1 = [ cos * (re0-re1) - sin * (im0-im1),
       //            sin * (re0-re1) + cos * (im0-im1) ]
       //
       tre = srcDataPtr[0] - srcDataPtr[len];
       tim = srcDataPtr[1] - srcDataPtr[len + 1];
       dstDataPtr[0] = srcDataPtr[0] + srcDataPtr[len];
       dstDataPtr[1] = srcDataPtr[1] + srcDataPtr[len+1];
       dstDataPtr[2*trig] = c*tre - s*tim;
       dstDataPtr[2*trig + 1] = s*tre + c*tim;
       srcDataPtr += 2; dstDataPtr += 2;
     }
     // update dest pointer and root value
     dstDataPtr += 2*trig;
     root += trig;
       }
     }
   }
   return result;
 }
int32 FFTComplex (float * data, int32 length, int32 isign)
Definition at line 1008 of file vbigdsp.cpp.
References fft_pingpong(), PINGPONG_FFT_MAXLEN, and rmAssert.
Referenced by fft_real_forward_scalar(), and fft_real_inverse_scalar().
 {
   int32 result = 0;
   if (length <= PINGPONG_FFT_MAXLEN) {
     // length is in the range where pingpong FFT is fastest
     result = fft_pingpong(data, length, isign);
   }
  else {
     rmAssert (0);
   }
   return result;
 }
int32 FFTRealForward (float * data, int32 len)
Definition at line 714 of file vbigdsp.cpp.
References fft_real_forward_scalar().
Referenced by rcOptoKineticImage::genDFT(), and rf1DFourierAnalysisVoxels().
 {
    return fft_real_forward_scalar(data, len);
 }
int32 FFTRealInverse (float * data, int32 len)
Definition at line 726 of file vbigdsp.cpp.
References fft_real_inverse_scalar().
 {
    return fft_real_inverse_scalar(data, len);
 }
static int InitFFTSinCos (int32 len) static
Definition at line 194 of file vbigdsp.cpp.
References cos(), gSinCosTablePtr, gSinCosTableSize, PI, and sin().
Referenced by fft_scalar().
{
   int32 result = 0;
   int32 i;
   float   angle;
   float   *sinCosTable;
   float   curSin;
   float   curCos;
   int32 pointerSize;
   // set length indicator to new length
   gSinCosTableSize = len;
   // deallocate old pointer if there is one
   if(gSinCosTablePtr) free(gSinCosTablePtr);
   // calculate appropriate pointer size for table.  Ensure a minimum length for
   //  a one-entry (two-value: cos & sin) table
   pointerSize = sizeof(float) * len;
   if (!pointerSize) pointerSize = 2 * sizeof(float);
   // alloc new pointer for sin & cos table
   gSinCosTablePtr = (float*) valloc(pointerSize);
   if (!gSinCosTablePtr) result = ENOMEM;
   if (result == 0) {
     // get pointer to start of sin cos table
     // to reference as array
     sinCosTable = (float*)gSinCosTablePtr;
     if (len < 4) {
       // always create first entries in table
       sinCosTable[0] = 1;
       sinCosTable[1] = 0;
       // if len is 2, then add second pair to table
       if (len == 2) {
     sinCosTable[2] = -1;
     sinCosTable[3] = 0;
       }
     } else {
       // calculate cos & sin for range of
       // [0, pi].
       for(i=0; i < len/4; i++) {
     angle = 2.0 * PI * i/len;
     curCos = cos(angle);
     curSin = sin(angle);
     sinCosTable[2*i] = curCos;
     sinCosTable[2*i+1] = curSin;
     sinCosTable[len/2 + 2*i] = -curSin;
     sinCosTable[len/2 + 2*i + 1] = curCos;
       }
     }
   }
   // if there was an error, then dealloc
   // anything we allocated, and reset
   // length indicator to zero.
   if (result != 0) {
     if (gSinCosTablePtr != 0) {
       free(gSinCosTablePtr);
       gSinCosTablePtr = 0;
     }
     gSinCosTableSize = 0;
   }
   return result;
 }
static int32 log2max (int32 n) static
Definition at line 137 of file vbigdsp.cpp.
Referenced by fft_scalar().
 {
   int32 power = 1;
   int32 k = 1;
   if (n==1) {
     return 0;
   }
   while ((k <<= 1) < n) {
     power++;
   }
   return power;
 }
void ShutdownFFT ()
Definition at line 293 of file vbigdsp.cpp.
References gSinCosTablePtr, gSinCosTableSize, gTempBufferPtr, and gTempBufferSize.
 {
   if (gSinCosTablePtr != 0) {
     free(gSinCosTablePtr);
     gSinCosTablePtr = 0;
   }
   gSinCosTableSize = 0;
   if (gTempBufferPtr != 0) {
     free(gTempBufferPtr);
     gTempBufferPtr = 0;
   }
   gTempBufferSize = 0;
 }
Variable Documentation
float* gSinCosTablePtr = 0 static
Definition at line 119 of file vbigdsp.cpp.
Referenced by fft_scalar(), InitFFTSinCos(), and ShutdownFFT().
int32 gSinCosTableSize = 0 static
Definition at line 124 of file vbigdsp.cpp.
Referenced by fft_scalar(), InitFFTSinCos(), and ShutdownFFT().
float* gTempBufferPtr = 0 static
Definition at line 109 of file vbigdsp.cpp.
Referenced by EnsureStaticBufferSize(), fft_pingpong(), and ShutdownFFT().
int32 gTempBufferSize = 0 static
Definition at line 114 of file vbigdsp.cpp.
Referenced by EnsureStaticBufferSize(), and ShutdownFFT().