
OPENCV_RLS_LOCATION=/usr/local/opencv-2.4.8/build/lib/Release/
APP_BUNDLE_FWK_LOCATION=@executable_path/../Frameworks/
OPEN_CV_CORE=libopencv_core.dylib
OPEN_CV_OBJECT=libopencv_objdetect.dylib
OPEN_CV_HIGHGUI=libopencv_highgui.dylib
OPEN_CV_IMGPROC=libopencv_imgproc.dylib
OPEN_CV_GPU=libopencv_gpu.dylib
OPEN_CV_FLANN=libopencv_flann.dylib
OPEN_CV_F2=libopencv_features2d.dylib
OPEN_CV_C3=libopencv_calib3d.dylib
OPEN_CV_ML=libopencv_ml.dylib
OPEN_CV_VIDEO=libopencv_video.dylib
OPEN_CV_PHOTO=libopencv_photo.dylib
OPEN_CV_LEGACY=libopencv_legacy.dylib

CONTAINER_LIB=$CONFIGURATION_BUILD_DIR/$FRAMEWORKS_FOLDER_PATH

install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_CORE $OPEN_CV_CORE
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_OBJECT $OPEN_CV_OBJECT
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_HIGHGUI $OPEN_CV_HIGHGUI
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_IMGPROC $OPEN_CV_IMGPROC
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_GPU $OPEN_CV_GPU
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_FLANN $OPEN_CV_FLANN
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_F2 $OPEN_CV_F2
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_C3 $OPEN_CV_C3
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_ML $OPEN_CV_ML
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_VIDEO $OPEN_CV_VIDEO
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_PHOTO $OPEN_CV_PHOTO
install_name_tool -id $APP_BUNDLE_FWK_LOCATION/$OPEN_CV_LEGACY $OPEN_CV_LEGACY

VFLIB=vfi386.framework/Versions/A/vfi386 
echo $CONTAINER_LIB/$VFLIB


install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$VFLIB
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_OBJECT $APP_BUNDLE_FWK_LOCATION$OPEN_CV_OBJECT  $CONTAINER_LIB/$VFLIB 
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$VFLIB 
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$VFLIB 
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_GPU $APP_BUNDLE_FWK_LOCATION$OPEN_CV_GPU  $CONTAINER_LIB/$VFLIB 


install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_FLANN
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_F2
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_C3
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_ML
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_VIDEO
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_PHOTO

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_OBJECT
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_OBJECT
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_OBJECT
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_GPU $APP_BUNDLE_FWK_LOCATION$OPEN_CV_GPU  $CONTAINER_LIB/$OPEN_CV_OBJECT

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_IMGPROC
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_IMGPROC
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_GPU $APP_BUNDLE_FWK_LOCATION$OPEN_CV_GPU  $CONTAINER_LIB/$OPEN_CV_IMGPROC

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_HIGHGUI
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_HIGHGUI

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_CORE $APP_BUNDLE_FWK_LOCATION$OPEN_CV_CORE  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_FLANN $APP_BUNDLE_FWK_LOCATION$OPEN_CV_FLANN  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_F2 $APP_BUNDLE_FWK_LOCATION$OPEN_CV_F2  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_C3 $APP_BUNDLE_FWK_LOCATION$OPEN_CV_C3  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_ML $APP_BUNDLE_FWK_LOCATION$OPEN_CV_ML  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_OBJECT $APP_BUNDLE_FWK_LOCATION$OPEN_CV_OBJECT  $CONTAINER_LIB/$OPEN_CV_GPU

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_VIDEO $APP_BUNDLE_FWK_LOCATION$OPEN_CV_VIDEO  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_PHOTO $APP_BUNDLE_FWK_LOCATION$OPEN_CV_PHOTO  $CONTAINER_LIB/$OPEN_CV_GPU
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_LEGACY $APP_BUNDLE_FWK_LOCATION$OPEN_CV_LEGACY  $CONTAINER_LIB/$OPEN_CV_GPU

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_FLANN $APP_BUNDLE_FWK_LOCATION$OPEN_CV_FLANN  $CONTAINER_LIB/$OPEN_CV_F2
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_F2
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_F2

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_FLANN $APP_BUNDLE_FWK_LOCATION$OPEN_CV_FLANN  $CONTAINER_LIB/$OPEN_CV_C3
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_C3
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_C3
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_F2 $APP_BUNDLE_FWK_LOCATION$OPEN_CV_F2  $CONTAINER_LIB/$OPEN_CV_C3

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_FLANN $APP_BUNDLE_FWK_LOCATION$OPEN_CV_FLANN  $CONTAINER_LIB/$OPEN_CV_C3
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_VIDEO

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_FLANN $APP_BUNDLE_FWK_LOCATION$OPEN_CV_FLANN  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_C3 $APP_BUNDLE_FWK_LOCATION$OPEN_CV_C3  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_ML $APP_BUNDLE_FWK_LOCATION$OPEN_CV_ML  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_F2 $APP_BUNDLE_FWK_LOCATION$OPEN_CV_F2  $CONTAINER_LIB/$OPEN_CV_LEGACY
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_VIDEO $APP_BUNDLE_FWK_LOCATION$OPEN_CV_VIDEO  $CONTAINER_LIB/$OPEN_CV_LEGACY

install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_IMGPROC $APP_BUNDLE_FWK_LOCATION$OPEN_CV_IMGPROC  $CONTAINER_LIB/$OPEN_CV_PHOTO
install_name_tool -change $OPENCV_RLS_LOCATION$OPEN_CV_HIGHGUI $APP_BUNDLE_FWK_LOCATION$OPEN_CV_HIGHGUI  $CONTAINER_LIB/$OPEN_CV_PHOTO


